### PR TITLE
test: fix concurrency issue in pitr_collector_test

### LINKED ISSUE #60051: DATA RACE in the br/pkg/restore/snap_client.TestConcurrency()
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c0087baf78 by goroutine 12030:
  github.com/pingcap/tidb/br/pkg/restore/snap_client.TestConcurrency()
      br/pkg/restore/snap_client/pitr_collector_test.go:305 +0x911
  github.com/pingcap/failpoint.parseTerm()
      external/com_github_pingcap_failpoint/terms.go:149 +0x233
  github.com/pingcap/failpoint.parse()
      external/com_github_pingcap_failpoint/terms.go:126 +0xa5
  github.com/pingcap/failpoint.newTerms()
      external/com_github_pingcap_failpoint/terms.go:98 +0x3e
  github.com/pingcap/failpoint.(*Failpoint).EnableCall()
      external/com_github_pingcap_failpoint/failpoint.go:94 +0x124
  github.com/pingcap/failpoint.(*Failpoints).EnableCall()
      external/com_github_pingcap_failpoint/failpoints.go:150 +0x296
  github.com/pingcap/failpoint.EnableCall()
      external/com_github_pingcap_failpoint/failpoints.go:270 +0x358
  github.com/pingcap/tidb/br/pkg/restore/snap_client.TestConcurrency()
      br/pkg/restore/snap_client/pitr_collector_test.go:280 +0x277
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1743 +0x44
Previous write at 0x00c0087baf78 by goroutine 12032:
  github.com/pingcap/tidb/br/pkg/restore/snap_client.TestConcurrency.func2()
      br/pkg/restore/snap_client/pitr_collector_test.go:295 +0x1a4
Goroutine 12030 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.runTests()
      GOROOT/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:2034 +0xf17
  github.com/pingcap/tidb/br/pkg/restore/snap_client_test.TestMain()
      br/pkg/restore/snap_client/main_test.go:48 +0x83d
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:285 +0x242
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:143 +0xa24
  fmt.Sscanf()
      GOROOT/src/fmt/scan.go:114 +0x18e
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseByteSize()
      pkg/sessionctx/variable/varsutil.go:319 +0x1d
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func263()
      pkg/sessionctx/variable/sysvar.go:1411 +0x44
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:144 +0xa94
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseSchemaCacheSize()
      pkg/sessionctx/variable/varsutil.go:551 +0x17c
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func622()
      pkg/sessionctx/variable/sysvar.go:3310 +0x67
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:144 +0xa94
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func621()
      pkg/sessionctx/variable/sysvar.go:3302 +0x52
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:285 +0x242
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:143 +0xa24
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadSysVarCacheLoop()
      pkg/domain/domain.go:2053 +0x93
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3553 +0x864
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func622()
      pkg/sessionctx/variable/sysvar.go:3310 +0x67
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:144 +0xa94
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func621()
      pkg/sessionctx/variable/sysvar.go:3302 +0x52
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:285 +0x242
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:143 +0xa24
  fmt.Sscanf()
      GOROOT/src/fmt/scan.go:114 +0x18e
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseByteSize()
      pkg/sessionctx/variable/varsutil.go:319 +0x1d
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func263()
      pkg/sessionctx/variable/sysvar.go:1411 +0x44
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:144 +0xa94
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCacheIfNeeded()
      pkg/domain/sysvar_cache.go:51 +0x1bb
  github.com/pingcap/tidb/pkg/domain.(*Domain).GetSessionCache()
      pkg/domain/sysvar_cache.go:62 +0x4a
  github.com/pingcap/tidb/pkg/session.(*session).loadCommonGlobalVariablesIfNeeded()
      pkg/session/session.go:3964 +0x2bc
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      pkg/session/session.go:2029 +0x17a
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal()
      pkg/session/session.go:1540 +0x3af
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadPrivilegeLoop()
      pkg/domain/domain.go:1981 +0x102
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3546 +0x807
  github.com/pingcap/tidb/pkg/session.BootstrapSession()
      pkg/session/session.go:3422 +0x25b
  github.com/pingcap/tidb/br/pkg/mock.NewCluster()
      br/pkg/mock/mock_cluster.go:76 +0x237
  github.com/pingcap/tidb/br/pkg/restore/snap_client_test.TestMain()
      br/pkg/restore/snap_client/main_test.go:40 +0x7a4
  main.main()
      bazel-out/k8-fastbuild/bin/br/pkg/restore/snap_client/snap_client_test_/testmain.go:175 +0x593
Goroutine 12032 (finished) created at:
  github.com/pingcap/tidb/br/pkg/restore/snap_client.TestConcurrency()
      br/pkg/restore/snap_client/pitr_collector_test.go:292 +0x3d6
  github.com/pingcap/failpoint.parseTerm()
      external/com_github_pingcap_failpoint/terms.go:149 +0x233
  github.com/pingcap/failpoint.parse()
      external/com_github_pingcap_failpoint/terms.go:126 +0xa5
  github.com/pingcap/failpoint.newTerms()
      external/com_github_pingcap_failpoint/terms.go:98 +0x3e
  github.com/pingcap/failpoint.(*Failpoint).EnableCall()
      external/com_github_pingcap_failpoint/failpoint.go:94 +0x124
  github.com/pingcap/failpoint.(*Failpoints).EnableCall()
      external/com_github_pingcap_failpoint/failpoints.go:150 +0x296
  github.com/pingcap/failpoint.EnableCall()
      external/com_github_pingcap_failpoint/failpoints.go:270 +0x358
  github.com/pingcap/tidb/br/pkg/restore/snap_client.TestConcurrency()
      br/pkg/restore/snap_client/pitr_collector_test.go:280 +0x277
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1743 +0x44
================== 
```

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

Issue Number: close #60051

Problem Summary:

It is possible to trigger race after closing the fence. 

### What changed and how does it work?

Added lock to the callbacks. 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > It is a test.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]

File: br/pkg/restore/snap_client/pitr_collector_test.go [hunk 1]
```diff
@@ -302,9 +302,11 @@ func TestConcurrency(t *testing.T) {
 	}, time.Second, 10*time.Millisecond)
 	close(fence)
 
+	l.Lock()
 	for _, cb := range cbs {
 		require.NoError(t, cb())
 	}
+	l.Unlock()
```
Comment (Leavrth) [inline br/pkg/restore/snap_client/pitr_collector_test.go:309]: use `defer l.Unlock` to avoid dead lock or goroutine leak?
