### PR TITLE
planner: avoid scanning multi-valued index when there is no condition related | tidb-test=pr/2276

### LINKED ISSUE #50125: Current MV index maintenance logic will cause wrong query result on empty array values
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a int, d json, index iad(a, (cast(d->'$.b' as signed array))));
insert into t value(1,'{"b":[]}'), (2,'{"b":[]}');
select * from t use index (iad) where a = 1;
select * from t ignore index (iad) where a = 1;
```

### 2. What did you expect to see? (Required)

```sql
> select * from t use index (iad) where a = 1;
+------+-----------+
| a    | d         |
+------+-----------+
|    1 | {"b": []} |
+------+-----------+

> select * from t ignore index (iad) where a = 1;
+------+-----------+
| a    | d         |
+------+-----------+
|    1 | {"b": []} |
+------+-----------+
```

### 3. What did you see instead (Required)

```sql
> select * from t use index (iad) where a = 1;
Empty set (0.002 sec)

> select * from t ignore index (iad) where a = 1;
+------+-----------+
| a    | d         |
+------+-----------+
|    1 | {"b": []} |
+------+-----------+
1 row in set (0.001 sec)
```

```sql
> explain analyze select * from t use index (iad) where a = 1;
+-------------------------------+---------+---------+-----------+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+-----------+------+
| id                            | estRows | actRows | task      | access object                                                              | execution info                                                                                                                                                                                                                                                                                            | operator info                               | memory    | disk |
+-------------------------------+---------+---------+-----------+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+-----------+------+
| IndexMerge_7                  | 10.00   | 0       | root      |                                                                            | time:606.4µs, loops:1                                                                                                                                                                                                                                                                                     | type: union                                 | 270 Bytes | N/A  |
| ├─IndexRangeScan_5(Build)     | 10.00   | 0       | cop[tikv] | table:t, index:iad(a, cast(json_extract(`d`, _utf8'$.b') as signed array)) | time:480.1µs, loops:1, cop_task: {num: 1, max: 409.8µs, proc_keys: 0, rpc_num: 1, rpc_time: 384.5µs, copr_cache_hit_ratio: 0.00, build_task_duration: 33.9µs, max_distsql_concurrency: 1}, tikv_task:{time:0s, loops:1}, scan_detail: {total_keys: 1, get_snapshot_time: 20µs, rocksdb: {block: {}}}      | range:[1,1], keep order:false, stats:pseudo | N/A       | N/A  |
| └─TableRowIDScan_6(Probe)     | 10.00   | 0       | cop[tikv] | table:t                                                                    |                                                                                                                                                                                                                                                                                                           | keep order:false, stats:pseudo              | N/A       | N/A  |
+-------------------------------+---------+---------+-----------+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------+-----------+------+
```

### 4. What is your TiDB version? (Required)

From v6.6.0 to the latest master (v7.6.0)

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #50125

### What changed and how does it work?

We cannot blindly scan on the multi-valued index, because scanning on it assumes that the array is not empty. I added a lot comments on related codes to describe why it's safe now.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

```release-note
Fix the issue that multi-valued index can give incorrect result when the array is empty.
```

### CODE REVIEW

File: pkg/planner/core/indexmerge_path.go [hunk 1]
```diff
@@ -1193,10 +1193,17 @@ func buildPartialPaths4MVIndex(
 	if virColID == -1 { // unexpected, no vir-col on this MVIndex
 		return nil, false, false, nil
 	}
-	if len(accessFilters) <= virColID { // no filter related to the vir-col, build a partial path directly.
-		partialPath, ok, err := buildPartialPath4MVIndex(sctx, accessFilters, idxCols, mvIndex, histColl)
-		return []*util.AccessPath{partialPath}, false, ok, err
+	if len(accessFilters) <= virColID {
```
Comment (AilinKid) [inline pkg/planner/core/indexmerge_path.go:1196]:
```
mysql> show create table t;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                              |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int DEFAULT NULL,
  `d` json DEFAULT NULL,
  UNIQUE KEY `iad` (`a`,(cast(json_extract(`d`,_utf8mb3'$.b') as signed array))),
  KEY `ua` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> explain  analyze select a from t use index(ua);
+-----------------------------------------------------------------------------------------------------+
| EXPLAIN                                                                                             |
+-----------------------------------------------------------------------------------------------------+
| -> Covering index scan on t using ua  (cost=0.45 rows=2) (actual time=0.072..0.084 rows=2 loops=1)
 |
+-----------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> explain  analyze select a from t use index(iad);
+-----------------------------------------------------------------------------------+
| EXPLAIN                                                                           |
+-----------------------------------------------------------------------------------+
| -> Table scan on t  (cost=0.45 rows=2) (actual time=0.086..0.100 rows=2 loops=1)
 |
+-----------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> explain  analyze select d->'$.b' from t use index(iad);
+-----------------------------------------------------------------------------------+
| EXPLAIN                                                                           |
+-----------------------------------------------------------------------------------+
| -> Table scan on t  (cost=0.45 rows=2) (actual time=0.068..0.082 rows=2 loops=1)
 |
+-----------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

seems MySQL does know itself have some rows missing for mv index value, and avoids using mv index to just fetch data for those only mv index columns.

so here is clear, avoid using mv index to fetch data when json column's is not covered by conditions.

File: tests/integrationtest/r/planner/core/indexmerge_path.result [hunk 2]
```diff
@@ -663,12 +654,27 @@ insert into t value(2,2,2, '{"b":[3,4,5,6]}');
...
 explain select * from t use index (iad) where a = 1 and (2 member of (d->'$.b'));
 id	estRows	task	access object	operator info
 IndexMerge_7	1.00	root		type: union
 ├─IndexRangeScan_5(Build)	1.00	cop[tikv]	table:t, index:iad(a, cast(json_extract(`d`, _utf8mb4'$.b') as signed array))	range:[1 2,1 2], keep order:false, stats:partial[d:unInitialized]
 └─TableRowIDScan_6(Probe)	1.00	cop[tikv]	table:t	keep order:false, stats:partial[d:unInitialized]
+drop table if exists t;
+create table t(a int, d json, index iad(a, (cast(d->'$.b' as signed array))));
+insert into t value(1,'{"b":[]}'), (2,'{"b":[]}');
+select * from t use index (iad) where a = 1;
+Error 1815 (HY000): Internal : Can't find a proper physical plan for this query
```
Comment (AilinKid) [inline tests/integrationtest/r/planner/core/indexmerge_path.result:667]: this error is undesirable
a basic table scan should be conductable

**Review by AilinKid — COMMENTED** [review]
/test check_dev

File: pkg/planner/core/indexmerge_path.go (hunk 1 above)
Comment (YangKeao) [reply pkg/planner/core/indexmerge_path.go:1196]: > avoid using mv index to fetch data when json column's is not covered by conditions

Yes. That's what I was trying to do in this PR :beers: .

File: pkg/planner/core/planbuilder.go [hunk 3]
```diff
@@ -1216,6 +1216,19 @@ func getPossibleAccessPaths(ctx sessionctx.Context, tableHints *hint.TableHintIn
...
+	// If all available paths are Multi-Valued Index, it's possible that the only multi-valued index is inapplicable,
+	// so that the table paths are still added here to avoid failing to find any physical plan.
+	allMVIIndexPath := true
+	for _, availablePath := range available {
+		if !isMVIndexPath(availablePath) {
+			allMVIIndexPath = false
+		}
+	}
+	if allMVIIndexPath {
+		available = append(available, tablePath)
```
Comment (YangKeao) [inline pkg/planner/core/planbuilder.go:1229]: Here is how I fixed the "Can't find a proper physical plan for this query". 

Is the former `if len(available) == 0` only an optimization to explore less paths, or it's necessary to ensure the hint works properly? I saw some paths are added to `preferredPath` according to the `.Force` field later, but I'm not sure whether it's really a hard restriction, or just some soft preference :thinking: .

@AilinKid PTAL

Comment (YangKeao) [reply pkg/planner/core/planbuilder.go:1229]: Oops, I realized that the index merge access path doesn't have `.Force` :facepalm: . Let me think about it.

Comment (YangKeao) [reply pkg/planner/core/planbuilder.go:1229]: Oops. I'll need to remove these plan when after finding a valid index merge based in multi- valued index.

Comment (YangKeao) [reply pkg/planner/core/planbuilder.go:1229]: Done

File: tests/integrationtest/r/planner/core/indexmerge_path.result [hunk 4]
```diff
@@ -499,11 +499,18 @@ TableReader_7	8000.00	root		data:Selection_6
 drop table if exists t;
 create table t(a int, j json, index kj((cast(j as signed array))));
 explain format = 'brief' select /*+ use_index(t, kj) */ * from t;
-Error 1815 (HY000): Internal : Can't find a proper physical plan for this query
+id	estRows	task	access object	operator info
+TableReader	10000.00	root		data:TableFullScan
+└─TableFullScan	10000.00	cop[tikv]	table:t	keep order:false, stats:pseudo
```
Comment (YangKeao) [inline tests/integrationtest/r/planner/core/indexmerge_path.result:504]: This is a behavior change. Now it's more compatible with MySQL.

File: pkg/planner/core/planbuilder.go (hunk 3 above)
Comment (AilinKid) [reply pkg/planner/core/planbuilder.go:1229]: LGTM here

**Review by AilinKid — APPROVED** [review]

File: tests/integrationtest/r/planner/core/indexmerge_path.result (hunk 4 above)
Comment (AilinKid) [reply tests/integrationtest/r/planner/core/indexmerge_path.result:504]: make sense

File: pkg/planner/core/indexmerge_path.go [hunk 5]
```diff
@@ -1440,6 +1451,56 @@ func (ds *DataSource) collectFilters4MVIndexMutations(filters []expression.Expre
...
+}
+
+// indexMergeContainSpecificIndex checks whether the index merge path contains at least one index in the `indexSet`
+func indexMergeContainSpecificIndex(path *util.AccessPath, indexSet map[int64]struct{}) bool {
+	if path.PartialIndexPaths == nil {
+		return false
+	}
+	for _, p := range path.PartialIndexPaths {
+		// each partial index path can be an index scan, or still an index merge
+		if len(p.PartialIndexPaths) > 0 {
```
Comment (time-and-fate) [inline pkg/planner/core/indexmerge_path.go:1487]: Currently it's impossible, an index merge access path can only be "a single layer".
It's better to update the comments, while I think it's ok to leave this code.

File: pkg/planner/core/indexmerge_path.go [hunk 6]
```diff
@@ -108,6 +108,8 @@ func (ds *DataSource) generateIndexMergePath() error {
 		}
 	}
 
+	ds.cleanAccessPathForMVIndexHint()
```
Comment (time-and-fate) [inline pkg/planner/core/indexmerge_path.go:111]: Looks like this function will interfere with the logic below and we may need to move it to the end of this function.

Comment (YangKeao) [reply pkg/planner/core/indexmerge_path.go]: Done.

File: pkg/planner/core/indexmerge_path.go (hunk 5 above)
Comment (YangKeao) [reply pkg/planner/core/indexmerge_path.go:1489]: Thanks for the information :heart:  . I added a comment here.
