### PR TITLE
*: insert set default timestamp failed

### LINKED ISSUE #29926: INSERT..SET vs INSERT ..VALUES to set Default current time stamp : INSERT..SET is not setting default timestamp.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1;
create table t1 (a int not null auto_increment,primary key(a), t timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);
insert into t1 values (default,default);
insert into t1 set a=default,t=default;
select * from t1;
```

### 2. What did you expect to see? (Required)
```sql
mysql> select * from t1;
+---+---------------------+
| a | t                   |
+---+---------------------+
| 1 | 2021-11-18 08:29:14 |
| 2 | 2021-11-18 08:29:14 |
+---+---------------------+
2 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> select * from t1;
+---+---------------------+
| a | t                   |
+---+---------------------+
| 1 | 2021-11-18 08:29:10 |
| 2 | 0000-00-00 00:00:00 |
+---+---------------------+
2 rows in set (0.01 sec)
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-67-g17edc5758
Edition: Community
Git Commit Hash: 17edc5758fbf865cada7e156318c41d3ee8a7501
Git Branch: master
UTC Build Time: 2021-11-16 02:57:45
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #29926

Problem Summary:
See bug report.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
`INSERT INTO t1 SET timestamp_col = DEFAULT` would set the timestamp to the zero timestamp for the CURRENT_TIMESTAMP default, instead of NOW().
```

### CODE REVIEW

File: planner/core/planbuilder.go [hunk 1]
```diff
@@ -3215,7 +3215,8 @@ func (b *PlanBuilder) buildSetValuesOfInsert(ctx context.Context, insert *ast.In
 	insertPlan.AllAssignmentsAreConstant = true
 	for i, assign := range insert.Setlist {
 		defaultExpr := extractDefaultExpr(assign.Expr)
-		if defaultExpr != nil {
+		if defaultExpr != nil && !defaultExpr.NameIsGiven {
+			// Set the name of the column in the assignment
```
Comment (djshow832) [inline planner/core/planbuilder.go:3219]: In `buildValuesListOfInsert`, there is a switch-case containing `DefaultExpr`, `ValueExpr`, `ParamMarkerExpr`, and `default`, but there is not such switch-case in `buildSetValuesOfInsert`. I don't know why. Did you figure out why?

Comment (djshow832) [reply planner/core/planbuilder.go:3219]: I guess `DefaultExpr.Name` was previously intended to distinguish `default(a)` from `default`. It's better to follow the convention and call `b.getDefaultValue(exprCols[i])` to return another expression like what `buildValuesListOfInsert` does.

Comment (mjonss) [reply planner/core/planbuilder.go]: Thanks for the suggestion.
I reverted the change in the parser and reorganised the code a bit for `buildValuesListOfInsert`/`buildSetValuesOfInsert` but then I did some more testing and found issues with `UPDATE` and `INSERT ON DUPLICATE KEY UPDATE` as well, and decided to break the "bug" compatibility with MySQL, by also making `SELECT DEFAULT(timestamp_col_with_CURRENT_TIMESTAMP_default)` to return `NOW()` which is more logical and matches INSERT/UPDATE behaviour.

Comment (djshow832) [reply planner/core/planbuilder.go]: > and decided to break the "bug" compatibility with MySQL, by also making SELECT DEFAULT(timestamp_col_with_CURRENT_TIMESTAMP_default) to return NOW() which is more logical and matches INSERT/UPDATE behaviour.

So you think this is a bug:

```sql
mysql> create table t(id int, ti timestamp default current_timestamp);
Query OK, 0 rows affected (0.37 sec)

mysql> insert t(id) value(1);
Query OK, 1 row affected (0.02 sec)

mysql> select default(ti) from t;
+-------------+
| default(ti) |
+-------------+
| NULL        |
+-------------+
1 row in set (0.01 sec)
```

I'm not sure about this. WDYT? @bb7133 @morgo

Comment (mjonss) [reply planner/core/planbuilder.go]: Yes, I think that is a bug. My guess is that it was implemented this way, to be backwards compatible *within* MySQL, since before the DEFAULT CURRENT_TIMESTAMP, it would automatically make the first timestamp to convert 0 or NULL values to current @@timestamp/NOW(). I.e. that is why it would internally return NULL, to make the already existing code to convert it to @@timestamp/NOW().

My main reasoning for consider `SELECT DEFAULT(ts_col)` returning `NULL` is a bug, is that it is not the same as `INSERT INTO t VALUES () / (DEFAULT) / DEFAULT(ts_col)` which is what I would expect. Since INSERT/UPDATE would set the value to @@timestamp or NOW(), that is what I expect SELECT to return as well.

File: planner/core/planbuilder.go [hunk 2]
```diff
@@ -3184,6 +3184,67 @@ func (b *PlanBuilder) getAffectCols(insertStmt *ast.InsertStmt, insertPlan *Inse
...
+		refCol := col
+		if x.Name != nil {
+			found := false
+			for _, col := range insertPlan.Table.Cols() {
+				if col.Name.L == x.Name.Name.L {
+					refCol = col
+					found = true
+					break
+				}
+			}
```
Comment (djshow832) [inline planner/core/planbuilder.go:3202]: We can use `FindColLowerCase`. BTW, should we use `insertPlan.Table.VisibleCols()`?

File: planner/core/point_get_plan.go [hunk 3]
```diff
@@ -1405,6 +1405,11 @@ func buildOrderedList(ctx sessionctx.Context, plan Plan, list []*ast.Assignment,
 			Col:     col,
 			ColName: plan.OutputNames()[idx].ColName,
 		}
+		// TODO: Check if needed!
+		defaultExpr := extractDefaultExpr(assign.Expr)
+		if defaultExpr != nil {
+			defaultExpr.Name = assign.Column
+		}
```
Comment (djshow832) [inline planner/core/point_get_plan.go:1412]: Why add this? Any examples?

**Review by djshow832 — COMMENTED** [review]
Besides `default(col_with_default_current_timestamp)`, rest LGTM

File: planner/core/point_get_plan.go (hunk 3 above)
Comment (mjonss) [reply planner/core/point_get_plan.go:1412]: It would panic for the new test I added. I will remove the TODO line.
```
        tk.MustExec("update t2 set b = default, c = default WHERE a = 2")
```

File: planner/core/planbuilder.go (hunk 2 above)
Comment (mjonss) [reply planner/core/planbuilder.go:3202]: I think it should be all columns, since hidden/generated columns should be OK to use if they refer to their own DEFAULT, like `hidden_generated_col = DEFAULT(hidden_generated_col)`

**Comment by mjonss** [comment]
PTAL @djshow832 @morgo @bb7133

**Comment by morgo** [comment]
> PTAL @djshow832 @morgo @bb7133

I'm sorry, I don't know some of these packages well. I'm not in a good position to review :(

File: planner/core/planbuilder.go (hunk 1 above)
Comment (morgo) [reply planner/core/planbuilder.go]: I agree it looks like a bug - but when we are not sure, we can file bugs against MySQL and wait for them to be verified. It benefits both of us :-)

Comment (mjonss) [reply planner/core/planbuilder.go]: Reported https://bugs.mysql.com/bug.php?id=105829

Comment (mjonss) [reply planner/core/planbuilder.go]: MySQL deemed bug#105829 as 'Not a bug', claiming it is explained here:
https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html
Which I cannot see any mentioning of how it handles `DEFAULT(col)`.

I added another comment just in the MySQL bug to clarify my expectations.
```
I could find a part that may be appropriate in 11.6:
"However, the use of DEFAULT(col_name) to specify the default value for a named column is permitted only for columns that have a literal default value, not for columns that have an expression default value."

Which is clear with this example:
create table t (a int primary key, b int default (3 + 2));

insert into t (a) values (1);
mysql> select default(b) from t;
ERROR 3773 (HY000): DEFAULT function cannot be used with default value expressions

But then I would expect an error when doing it with 'b timestamp default current_timestamp' too, and not silently insert NULL for the second row in the 'How to repeat' section!
```

Since TiDB does not yet support Expressions for column DEFAULTS, see https://github.com/pingcap/tidb/issues/30553, we can safely ignore everything else than `CURRENT_TIMESTAMP` and `NOW()`. (I will also ignore generated columns for now :) )


So current master vs MySQL 8.0.27 does
```
create table t (a int primary key, b timestamp default current_timestamp);
insert into t values (1,default),(2,default(b));
insert into t set a = 3, b = default;
insert into t set a = 4, b = default(b);
```
TiDB:
```
tidb> select a,b,default(b) from t;
+---+---------------------+---------------------+
| a | b                   | default(b)          |
+---+---------------------+---------------------+
| 1 | 2021-12-08 18:00:25 | 0000-00-00 00:00:00 |
| 2 | 2021-12-08 18:00:25 | 0000-00-00 00:00:00 |
| 3 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
| 4 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
+---+---------------------+---------------------+
```
MySQL:
```
mysql> select a,b,default(b) from t;
+---+---------------------+------------+
| a | b                   | default(b) |
+---+---------------------+------------+
| 1 | 2021-12-08 18:01:44 | NULL       |
| 2 | NULL                | NULL       |
| 3 | 2021-12-08 18:01:55 | NULL       |
| 4 | NULL                | NULL       |
+---+---------------------+------------+
```
And with current state of the patch it would be:
```
tidb> select a,b,default(b) from t;
+---+---------------------+---------------------+
| a | b                   | default(b)          |
+---+---------------------+---------------------+
| 1 | 2021-12-08 18:05:41 | 2021-12-08 18:05:52 |
| 2 | 2021-12-08 18:05:41 | 2021-12-08 18:05:52 |
| 3 | 2021-12-08 18:05:41 | 2021-12-08 18:05:52 |
| 4 | 2021-12-08 18:05:43 | 2021-12-08 18:05:52 |
+---+---------------------+---------------------+
4 rows in set (0,00 sec)
```

@morgo @djshow832 should we be bug compatible with MySQL when it comes to handling `DEFAULT(col)` when col is a timestamp and DEFAULT is `CURRENT_TIMESTAMP`/`NOW()` ? If so, I think it makes sense to create a new bug for that and consider this bug to handle the `INSERT ... VALUES` vs `INSERT ... SET` difference.

**Comment by djshow832** [comment]
@winoros  Can you take a look?

File: planner/core/point_get_plan.go [hunk 4]
```diff
@@ -1419,6 +1419,10 @@ func buildOrderedList(ctx sessionctx.Context, plan Plan, list []*ast.Assignment,
 			Col:     col,
 			ColName: plan.OutputNames()[idx].ColName,
 		}
+		defaultExpr := extractDefaultExpr(assign.Expr)
+		if defaultExpr != nil {
+			defaultExpr.Name = assign.Column
+		}
```
Comment (djshow832) [inline planner/core/point_get_plan.go:1425]: Since you're modified the point get, do you need to test it?

Comment (mjonss) [reply planner/core/point_get_plan.go:1425]: It was detected/tested by another unit test:
ddl/db_test.go: TestDefaultSQLFunction
"update t2 set b = default, c = default WHERE a = 2"
after my changes, so it was needed :)

**Review by djshow832 — APPROVED** [review]

**Comment by mjonss** [comment]
PTAL @winoros  @bb7133

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by bb7133** [comment]
@mjonss Please update the PR, thanks.

**Comment by bb7133** [comment]
Hi @mjonss `mysql-test` failed, maybe it should be updated?
