### PR TITLE
table: keep `table.Columns` order by states during modifying column

### LINKED ISSUE #63258: `UPDATE` during multi-schema ddl will cause panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```go
func TestUpdateDuringDDL(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewTestKit(t, store)

	tk.MustExec("use test")
	tk.MustExec("create table t(a int, b int, c int, d int)")

	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/ddl/afterWaitSchemaSynced", func(job *model.Job) {
		tk := testkit.NewTestKit(t, store)
		tk.MustExec("use test")
		tk.MustExec("insert into t(a, c) values (1, 2), (2, 3), (3, 4), (4, 5)")
		tk.MustExec("update t set c = 5 where a = 1")
		tk.MustExec("delete from t")
	})
	tk.MustExec("alter table t change column b e int unsigned, change column d f int unsigned")
	testfailpoint.Disable(t, "github.com/pingcap/tidb/pkg/ddl/afterWaitSchemaSynced")

	tk.MustExec("drop table t")
}
```

### 2. What did you expect to see? (Required)

Test runs successfully

### 3. What did you see instead (Required)

Test failed.

I found this issue when I was adding tests for partial index feature.

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref #62531, close #63258

Problem Summary:

Previously we have an assumption about "table.Cols()": all public columns are at the front of the array. After #62549, the tombstone columns may stay at the origin place and become non-public during multi-schema change.

It may introduce visible "wrong schema" temporarily:

```sql
atler table ... modify column lossy_change_0 ..., add column new_col_0;
```
```
[2025/08/18 20:57:23.687 +08:00] [ERROR] [tables.go:186] ["wrong table schema"] [table="{\"id\":6214,\"name\":{\"O\":\"t16db6fde\",\"L\":\"t16db6fde\"},\"charset\":\"utf8mb4\",\"collate\":\"utf8mb4_bin\",\"cols\":[{\"id\":4,\"name\":{\"O\":\"a66d4758\",\"L\":\"a66d4758\"},\"offset\":0,\"origin_default\":null,\"origin_default_bit\":null,\"default\":\"7328359042526431637\",\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":8,\"Flag\":0,\"Flen\":20,\"Decimal\":0,\"Charset\":\"binary\",\"Collate\":\"binary\",\"Elems\":null,\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":5,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2},{\"id\":5,\"name\":{\"O\":\"col2d2b\",\"L\":\"col2d2b\"},\"offset\":1,\"origin_default\":\"jdiefzdyzikac5qtif49xrqj4y7uhz1uqhx9af1hm0nibke78xx0j6xplflf65kjhfsmfb7f0bi23dpcy6q1j23f1uo17ipsbgyp8pl9dn1owdw98t0jzhu\",\"origin_default_bit\":null,\"default\":\"jdiefzdyzikac5qtif49xrqj4y7uhz1uqhx9af1hm0nibke78xx0j6xplflf65kjhfsmfb7f0bi23dpcy6q1j23f1uo17ipsbgyp8pl9dn1owdw98t0jzhu\",\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":254,\"Flag\":0,\"Flen\":149,\"Decimal\":0,\"Charset\":\"utf8mb4\",\"Collate\":\"utf8mb4_bin\",\"Elems\":null,\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":3,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2},{\"id\":7,\"name\":{\"O\":\"col6772\",\"L\":\"col6772\"},\"offset\":3,\"origin_default\":\"xd4core9rklsdxphrcgqrttyr6w7je15bw1hwleb2agyeyz6bm8hadu2oskf1yhmsg48wokqm1b40ro2nyw32wfj\",\"origin_default_bit\":null,\"default\":\"xd4core9rklsdxphrcgqrttyr6w7je15bw1hwleb2agyeyz6bm8hadu2oskf1yhmsg48wokqm1b40ro2nyw32wfj\",\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":15,\"Flag\":0,\"Flen\":89,\"Decimal\":0,\"Charset\":\"utf8mb4\",\"Collate\":\"utf8mb4_bin\",\"Elems\":null,\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":3,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2}],\"index_info\":null,\"constraint_info\":null,\"fk_info\":null,\"state\":5,\"pk_is_handle\":false,\"is_common_handle\":false,\"common_handle_version\":0,\"comment\":\"2fb1e0c6\",\"auto_inc_id\":5308925789339758613,\"auto_id_cache\":0,\"auto_rand_id\":0,\"max_col_id\":7,\"max_idx_id\":0,\"max_fk_id\":0,\"max_cst_id\":0,\"update_timestamp\":460199518172872747,\"ShardRowIDBits\":0,\"max_shard_row_id_bits\":0,\"auto_random_bits\":0,\"auto_random_range_bits\":0,\"pre_split_regions\":0,\"partition\":null,\"compression\":\"\",\"view\":null,\"sequence\":null,\"Lock\":null,\"version\":5,\"tiflash_replica\":null,\"is_columnar\":false,\"temp_table_type\":0,\"cache_table_status\":0,\"policy_ref_info\":null,\"stats_options\":null,\"exchange_partition_info\":null,\"ttl_info\":null,\"revision\":37}"] [column="{\"id\":7,\"name\":{\"O\":\"col6772\",\"L\":\"col6772\"},\"offset\":3,\"origin_default\":\"xd4core9rklsdxphrcgqrttyr6w7je15bw1hwleb2agyeyz6bm8hadu2oskf1yhmsg48wokqm1b40ro2nyw32wfj\",\"origin_default_bit\":null,\"default\":\"xd4core9rklsdxphrcgqrttyr6w7je15bw1hwleb2agyeyz6bm8hadu2oskf1yhmsg48wokqm1b40ro2nyw32wfj\",\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":15,\"Flag\":0,\"Flen\":89,\"Decimal\":0,\"Charset\":\"utf8mb4\",\"Collate\":\"utf8mb4_bin\",\"Elems\":null,\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":3,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2}"] [index=2] [offset=3] [columnNumber=3]
```

### What changed and how does it work?

- Keep table.Columns order by states during modifying column.
 
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

File: pkg/util/misc.go [hunk 1]
```diff
@@ -120,6 +121,12 @@ func Recover(metricsLabel, funcInfo string, recoverFn func(), quit bool) {
 		zap.Any("r", r),
 		zap.Stack("stack"))
 	metrics.PanicCounter.WithLabelValues(metricsLabel).Inc()
+	if intest.InTest {
+		if strings.Contains(fmt.Sprintf("%v", r), "assert failed") {
+			time.Sleep(100 * time.Minute)
```
Comment (joechenrh) [inline pkg/util/misc.go]: This should be removed?

File: pkg/ddl/modify_column.go [hunk 2]
```diff
@@ -437,6 +459,9 @@ func (w *worker) doModifyColumnTypeWithData(
 	changingCol, oldCol *model.ColumnInfo,
 	args *model.ModifyColumnArgs,
 ) (ver int64, _ error) {
+	printTableInfo(tblInfo)
+	logutil.DDLLogger().Info("doModifyColumnTypeWithData", zap.Int64("jobID", job.ID))
+	defer printTableInfo(tblInfo)
```
Comment (joechenrh) [inline pkg/ddl/modify_column.go]: Remove debug log?

File: pkg/meta/model/table.go [hunk 3]
```diff
@@ -422,6 +433,19 @@ func (t *TableInfo) MoveColumnInfo(from, to int) {
...
+		if col.ChangeStateInfo != nil {
+			depColID := dependence[col.ID]
+			for i, c := range t.Columns {
+				if c.ID == depColID {
+					col.ChangeStateInfo.DependencyColumnOffset = i
+					break
+				}
+			}
+		}
+	}
```
Comment (joechenrh) [inline pkg/meta/model/table.go]: How about
```suggestion
	// Reconstruct the dependency column offsets.
	for _, col := range t.Columns {
		if col.ChangeStateInfo != nil {
			newOffset, ok := updatedOffsets[col.ChangeStateInfo.DependencyColumnOffset]
			if ok {
			    col.ChangeStateInfo.DependencyColumnOffset = newOffset
			}
		}
	}
```

File: pkg/ddl/modify_column.go [hunk 4]
```diff
@@ -563,10 +588,12 @@ func (w *worker) doModifyColumnTypeWithData(
...
-		updateChangingObjState(changingCol, changingIdxInfos, model.StatePublic)
+
+		updateObjectState(oldCol, oldIdxInfos, model.StateWriteOnly)
+		updateObjectState(changingCol, changingIdxInfos, model.StatePublic)
 		markOldObjectRemoving(oldCol, changingCol, oldIdxInfos, changingIdxInfos, colName)
-		moveColumnInfoToDest(tblInfo, oldCol, changingCol, pos)
+		moveChangingColumnInfoToDest(tblInfo, oldCol, changingCol, pos)
+		moveOldColumnInfo(tblInfo, oldCol)
 		moveIndexInfoToDest(tblInfo, changingCol, oldIdxInfos, changingIdxInfos)
 		updateModifyingCols(oldCol, changingCol)
```
Comment (joechenrh) [inline pkg/ddl/modify_column.go:574]: ~~Move the logic related to `changingCol` out and remove `updateModifyingCols`? Seems we have updated `ChangeStateInfo` in `moveOldColumnInfo`~~

**Review by joechenrh — APPROVED** [review]

File: pkg/ddl/modify_column.go [hunk 5]
```diff
@@ -705,6 +708,41 @@ func checkModifyColumnWithGeneratedColumnsConstraint(allCols []*table.Column, ol
 	return nil
 }
 
+var colStateOrd = map[model.SchemaState]int{
```
Comment (YangKeao) [inline pkg/ddl/modify_column.go:711]: Nice! I'm thinking about the order of `Columns` these days :facepalm:. This PR gives me a clear answer. :heart:
