### PR TITLE
unistore: Added error if row is too long to be locked

### LINKED ISSUE #59651: unistore crash on data import
## Bug Report

```
panic: runtime error: index out of range [-1]

goroutine 385 [running]:
github.com/pingcap/tidb/pkg/store/mockstore/unistore/lockstore.(*arena).get(0xc0c4262460?, 0xda8d7a?, 0x3a0b2ff?)
	/workspace/source/tidb/pkg/store/mockstore/unistore/lockstore/arena.go:79 +0x210
github.com/pingcap/tidb/pkg/store/mockstore/unistore/lockstore.(*MemStore).newNode(0xc001210060, 0xc001192000, {0xc0c427a06c, 0x13, 0xc001106e58?}, {0xc1122b6000, 0xda8d4f, 0xc001d41340?}, 0x1)
	/workspace/source/tidb/pkg/store/mockstore/unistore/lockstore/lockstore.go:366 +0x38e
github.com/pingcap/tidb/pkg/store/mockstore/unistore/lockstore.(*MemStore).PutWithHint(0xc001210060, {0xc0c427a06c, 0x13, 0x13}, {0xc1122b6000, 0xda8d4f, 0xda8d4f}, 0xc001106e58?)
	/workspace/source/tidb/pkg/store/mockstore/unistore/lockstore/lockstore.go:316 +0x245
github.com/pingcap/tidb/pkg/store/mockstore/unistore/tikv.writeLockWorker.run({0xc0011a6540?, 0xc00104d480?})
	/workspace/source/tidb/pkg/store/mockstore/unistore/tikv/write.go:170 +0x431
created by github.com/pingcap/tidb/pkg/store/mockstore/unistore/tikv.(*dbWriter).Open in goroutine 1
	/workspace/source/tidb/pkg/store/mockstore/unistore/tikv/write.go:207 +0x147
```

### 1. Minimal reproduce step (Required)

Load sql file created with mysqldump with `mysql -e source some_file.sql`

Config:
```yaml
port = 3306
path = "/var/tidb"
txn-entry-size-limit = 16777216
allow-expression-index = true
```

### 4. What is your TiDB version? (Required)

v8.5.1 with unistore

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #59651

Problem Summary:
The Unistore cannot handle a row is larger than the lockstore arena blocksize.

### What changed and how does it work?
Added an error when trying to lock a row that is too big.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Return error if a row is larger than the unistore lock blocksize instead of panic: runtime error: index out of range [-1]
```

### CODE REVIEW

File: pkg/store/mockstore/unistore/lockstore/lockstore.go [hunk 1]
```diff
@@ -353,6 +353,10 @@ func (ls *MemStore) replace(key, v []byte, hint *Hint, old *node) {
 	ls.getArena().free(old.addr)
 }
 
+func (ls *MemStore) MaxEntrySize() int {
```
Comment (Defined2014) [inline pkg/store/mockstore/unistore/lockstore/lockstore.go:356]: Please add a comment to fix the `check_dev` test

**Review by Defined2014 — APPROVED** [review]

**Review by dveeden — COMMENTED** [review]
Another way of doing this would be to reduce the `tidb_txn_entry_size_limit` on startup if unistore is used. However I think doing this on write as it is done now is easier for people to understand.

Maybe adding a warning on startup would be nice, but I don't think that's needed either.

I think it is clear enough to the user that this is a unistore limitation, but we could explicitly add that to the message as well, just in case it wasn't clear enough.

**Review by dveeden — APPROVED** [review]
Approved, but please add the comment as suggested by @Defined2014

File: pkg/store/mockstore/unistore/tikv/write.go [hunk 2]
```diff
@@ -166,6 +167,11 @@ func (w writeLockWorker) run() {
 					// Ignore if the key doesn't exist
 					ls.DeleteWithHint(entry.Key.UserKey, hint)
 				default:
+					// Make sure it fits into an arena block.
+					if len(entry.Key.UserKey)+len(entry.Value) > ls.MaxEntrySize() {
+						batch.err = fmt.Errorf("Unistore lock entry too big %d > %d", len(entry.Key.UserKey)+len(entry.Value), ls.MaxEntrySize())
```
Comment (dveeden) [inline pkg/store/mockstore/unistore/tikv/write.go:172]:
```suggestion
						batch.err = fmt.Errorf("unistore lock entry too big %d > %d", len(entry.Key.UserKey)+len(entry.Value), ls.MaxEntrySize())
```

Errors in go shouldn't start with a capital right?

Comment (dveeden) [reply pkg/store/mockstore/unistore/tikv/write.go:172]: https://go.dev/wiki/CodeReviewComments#error-strings (maybe not the best source of information) mentions this. But for Unistore this is fine either way I guess.
