### PR TITLE
traceevent,*: refine flight recorder

### LINKED ISSUE #60413: Support continuously tracing
## Enhancement

Tracing is a powerful tool for diagnosing long latency queries. But currently tracing support for TiDB is not good enough.

We can use the trace statement like this, but it doesn't really help much.

```
mysql> trace select * from t5;
+----------------------------------------------+-----------------+------------+
| operation                                    | startTS         | duration   |
+----------------------------------------------+-----------------+------------+
| trace                                        | 20:48:34.871542 | 3.341667ms |
|   ├─session.ExecuteStmt                      | 20:48:34.871786 | 1.2685ms   |
|   │ ├─executor.Compile                       | 20:48:34.871809 | 759.75µs   |
|   │ │ ├─planner.Preprocess                   | 20:48:34.871815 | 13.542µs   |
|   │ │ └─planner.Optimize                     | 20:48:34.872259 | 291.417µs  |
|   │ └─session.runStmt                        | 20:48:34.872579 | 441.042µs  |
|   │   ├─TableReaderExecutor.Open             | 20:48:34.872724 | 288.417µs  |
|   │   │ └─distsql.Select                     | 20:48:34.872759 | 246.458µs  |
|   │   │   ├─copr.buildCopTasks               | 20:48:34.872767 | 212.167µs  |
|   │   │   ├─batchScanRegions                 | 20:48:34.872778 | 162.791µs  |
|   │   │   └─regionRequest.SendReqCtx         | 20:48:34.873100 | 1.0305ms   |
|   │   ├─rs.Finish                            | 20:48:34.874414 | 61.541µs   |
|   │   ├─recordSet.Finish                     | 20:48:34.874420 | 7µs        |
|   │   ├─finishStmt                           | 20:48:34.874435 | 36.041µs   |
|   │   ├─session.CommitTxn                    | 20:48:34.874442 | 19µs       |
|   │   │ └─session.doCommitWithRetry          | 20:48:34.874448 | 5.667µs    |
|   │   ├─recordSet.Close                      | 20:48:34.874484 | 393.083µs  |
|   │   ├─recordSet.Finish                     | 20:48:34.874487 | 250ns      |
|   │   └─ExecStmt.SummaryStmt                 | 20:48:34.874855 | 625ns      |
|   ├─*executor.TableReaderExecutor.Next       | 20:48:34.873068 | 1.113084ms |
|   └─*executor.TableReaderExecutor.Next       | 20:48:34.874396 | 4.708µs    |
+----------------------------------------------+-----------------+------------+
25 rows in set (0.01 sec)
```

We can (in theory) configure the opentracing, but it's affect performance and has never been tested by the real production environment. (And I suspect its broken without been actively maintaned for a long time).

We can use `go tool trace`, it's a great tool, but just used for debugging Go runtime related problems.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: ref #64008, close #60413

Problem Summary:

### What changed and how does it work?

curl http://127.0.0.1:10080/debug/traceevent will continuously dump the traceing event to flight record

```
data: [{"name":"ParseSQL","ph":"B","ts":1762235530496906,"pid":0,"tid":808882597,"cat":"general"},{"name":"ParseSQL","ph":"E","ts":1762235530497191,"pid":0,"tid":808882597,"cat":"general"},{"name":"session.ExecuteStmt","ph":"B","ts":1762235530497196,"pid":0,"tid":808882597,"cat":"general"},{"name":"txn.enter","ph":"i","ts":1762235530497201,"pid":0,"tid":808882597,"cat":"txn_lifecycle","args":{"type":2,"conn_id":2738880518,"explicit":false}},{"name":"executor.Compile","ph":"B","ts":1762235530497226,"pid":0,"tid":808882597,"cat":"general"},{"name":"planner.Preprocess","ph":"B","ts":1762235530497228,"pid":0,"tid":808882597,"cat":"general"},{"name":"planner.Preprocess","ph":"E","ts":1762235530497231,"pid":0,"tid":808882597,"cat":"general"},{"name":"planner.Optimize","ph":"B","ts":1762235530497243,"pid":0,"tid":808882597,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"B","ts":1762235530497253,"pid":0,"tid":808882597,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"E","ts":1762235530497274,"pid":0,"tid":808882597,"cat":"general"},{"name":"planner.Optimize","ph":"E","ts":1762235530497338,"pid":0,"tid":808882597,"cat":"general"},{"name":"stmt.plan.digest","ph":"i","ts":1762235530497341,"pid":0,"tid":808882597,"cat":"stmt_plan","args":{"plan_digest":"","stmt_type":"Show","conn_id":2738880518}},{"name":"executor.Compile","ph":"E","ts":1762235530497345,"pid":0,"tid":808882597,"cat":"general"},{"name":"session.runStmt","ph":"B","ts":1762235530497346,"pid":0,"tid":808882597,"cat":"general"},{"name":"stmt.start","ph":"i","ts":1762235530497349,"pid":0,"tid":808882597,"cat":"stmt_lifecycle","args":{"sql_digest":"show tables","autocommit":true,"conn_id":2738880518,"prev_trace_id":"00000000000000000000000000000000F79004F1","trace_id":"00000000000000000000000000000000a5913630"}},{"name":"stmt.finish","ph":"i","ts":1762235530497387,"pid":0,"tid":808882597,"cat":"stmt_lifecycle","args":{"sql_digest":"show tables","plan_digest":"db3b489a73308fe44800e2c2eb307e63a6db5e11a337089218d93de4fecc8652","autocommit":true,"conn_id":2738880518,"retry_count":1,"trace_id":"00000000000000000000000000000000a5913630"}},{"name":"session.runStmt","ph":"E","ts":1762235530497388,"pid":0,"tid":808882597,"cat":"general"},{"name":"session.ExecuteStmt","ph":"E","ts":1762235530497390,"pid":0,"tid":808882597,"cat":"general"},{"name":"*executor.ShowExec.Next","ph":"B","ts":1762235530497399,"pid":0,"tid":808882597,"cat":"general"},{"name":"*executor.ShowExec.Next","ph":"E","ts":1762235530497418,"pid":0,"tid":808882597,"cat":"general"}]


data: [{"name":"ParseSQL","ph":"B","ts":1762235545256201,"pid":0,"tid":2506930128,"cat":"general"},{"name":"ParseSQL","ph":"E","ts":1762235545256321,"pid":0,"tid":2506930128,"cat":"general"},{"name":"session.ExecuteStmt","ph":"B","ts":1762235545256334,"pid":0,"tid":2506930128,"cat":"general"},{"name":"txn.enter","ph":"i","ts":1762235545256369,"pid":0,"tid":2506930128,"cat":"txn_lifecycle","args":{"type":2,"conn_id":2738880518,"explicit":false}},{"name":"executor.Compile","ph":"B","ts":1762235545256448,"pid":0,"tid":2506930128,"cat":"general"},{"name":"planner.Preprocess","ph":"B","ts":1762235545256453,"pid":0,"tid":2506930128,"cat":"general"},{"name":"planner.Preprocess","ph":"E","ts":1762235545256468,"pid":0,"tid":2506930128,"cat":"general"},{"name":"planner.Optimize","ph":"B","ts":1762235545256469,"pid":0,"tid":2506930128,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"B","ts":1762235545256516,"pid":0,"tid":2506930128,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"E","ts":1762235545256546,"pid":0,"tid":2506930128,"cat":"general"},{"name":"planner.Optimize","ph":"E","ts":1762235545256753,"pid":0,"tid":2506930128,"cat":"general"},{"name":"stmt.plan.digest","ph":"i","ts":1762235545256803,"pid":0,"tid":2506930128,"cat":"stmt_plan","args":{"plan_digest":"","stmt_type":"CreateTable","conn_id":2738880518}},{"name":"executor.Compile","ph":"E","ts":1762235545256811,"pid":0,"tid":2506930128,"cat":"general"},{"name":"session.runStmt","ph":"B","ts":1762235545256815,"pid":0,"tid":2506930128,"cat":"general"},{"name":"stmt.start","ph":"i","ts":1762235545256823,"pid":0,"tid":2506930128,"cat":"stmt_lifecycle","args":{"sql_digest":"create table `t` ( `id` int )","autocommit":true,"conn_id":2738880518,"prev_trace_id":"00000000000000000000000000000000A5913630","trace_id":"00000000000000000000000000000000d0b76c95"}},{"name":"executor.handleNoDelayExecutor","ph":"B","ts":1762235545256992,"pid":0,"tid":2506930128,"cat":"general"},{"name":"*executor.DDLExec.Next","ph":"B","ts":1762235545257025,"pid":0,"tid":2506930128,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"B","ts":1762235545257029,"pid":0,"tid":2506930128,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"E","ts":1762235545257043,"pid":0,"tid":2506930128,"cat":"general"},{"name":"txn.enter","ph":"i","ts":1762235545257847,"pid":0,"tid":2506930128,"cat":"txn_lifecycle","args":{"type":0,"conn_id":2738880518,"explicit":false,"start_ts":461959474768248834,"trace_id":"00000000000000000000000000000000d0b76c95"}},{"name":"*executor.DDLExec.Next","ph":"E","ts":1762235545314681,"pid":0,"tid":2506930128,"cat":"general"},{"name":"executor.handleNoDelayExecutor","ph":"E","ts":1762235545314682,"pid":0,"tid":2506930128,"cat":"general"},{"name":"session.CommitTxn","ph":"B","ts":1762235545314687,"pid":0,"tid":2506930128,"cat":"general"},{"name":"session.doCommitWithRetry","ph":"B","ts":1762235545314688,"pid":0,"tid":2506930128,"cat":"general"},{"name":"txn.commit.start","ph":"i","ts":1762235545314688,"pid":0,"tid":2506930128,"cat":"txn_lifecycle","args":{"start_ts":461959474768248834,"pessimistic":false,"pipelined":false,"txn_size":0,"conn_id":2738880518,"trace_id":"00000000000000000000000000000000d0b76c95"}},{"name":"txn.commit.finish","ph":"i","ts":1762235545314689,"pid":0,"tid":2506930128,"cat":"txn_lifecycle","args":{"start_ts":461959474768248834,"pessimistic":false,"pipelined":false,"conn_id":2738880518,"trace_id":"00000000000000000000000000000000d0b76c95"}},{"name":"session.doCommitWithRetry","ph":"E","ts":1762235545314689,"pid":0,"tid":2506930128,"cat":"general"},{"name":"session.CommitTxn","ph":"E","ts":1762235545314694,"pid":0,"tid":2506930128,"cat":"general"},{"name":"stmt.finish","ph":"i","ts":1762235545314724,"pid":0,"tid":2506930128,"cat":"stmt_lifecycle","args":{"sql_digest":"create table `t` ( `id` int )","plan_digest":"","autocommit":true,"conn_id":2738880518,"retry_count":1,"trace_id":"00000000000000000000000000000000d0b76c95"}},{"name":"session.runStmt","ph":"E","ts":1762235545314724,"pid":0,"tid":2506930128,"cat":"general"},{"name":"session.ExecuteStmt","ph":"E","ts":1762235545314740,"pid":0,"tid":2506930128,"cat":"general"}]


data: [{"name":"ParseSQL","ph":"B","ts":1762235547371906,"pid":0,"tid":2685358063,"cat":"general"},{"name":"ParseSQL","ph":"E","ts":1762235547371930,"pid":0,"tid":2685358063,"cat":"general"},{"name":"session.ExecuteStmt","ph":"B","ts":1762235547371935,"pid":0,"tid":2685358063,"cat":"general"},{"name":"txn.enter","ph":"i","ts":1762235547371938,"pid":0,"tid":2685358063,"cat":"txn_lifecycle","args":{"type":2,"conn_id":2738880518,"explicit":false}},{"name":"executor.Compile","ph":"B","ts":1762235547371955,"pid":0,"tid":2685358063,"cat":"general"},{"name":"planner.Preprocess","ph":"B","ts":1762235547371956,"pid":0,"tid":2685358063,"cat":"general"},{"name":"planner.Preprocess","ph":"E","ts":1762235547371968,"pid":0,"tid":2685358063,"cat":"general"},{"name":"planner.Optimize","ph":"B","ts":1762235547371969,"pid":0,"tid":2685358063,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"B","ts":1762235547371986,"pid":0,"tid":2685358063,"cat":"general"},{"name":"isolation.newOracleFuture","ph":"E","ts":1762235547371993,"pid":0,"tid":2685358063,"cat":"general"},{"name":"planner.Optimize","ph":"E","ts":1762235547372112,"pid":0,"tid":2685358063,"cat":"general"},{"name":"stmt.plan.digest","ph":"i","ts":1762235547372116,"pid":0,"tid":2685358063,"cat":"stmt_plan","args":{"plan_digest":"","stmt_type":"Select","conn_id":2738880518}},{"name":"executor.Compile","ph":"E","ts":1762235547372117,"pid":0,"tid":2685358063,"cat":"general"},{"name":"session.runStmt","ph":"B","ts":1762235547372119,"pid":0,"tid":2685358063,"cat":"general"},{"name":"stmt.start","ph":"i","ts":1762235547372121,"pid":0,"tid":2685358063,"cat":"stmt_lifecycle","args":{"sql_digest":"select * from `t`","autocommit":true,"conn_id":2738880518,"prev_trace_id":"00000000000000000000000000000000D0B76C95","trace_id":"00000000000000000000000000000000ef4f0fa0"}},{"name":"TableReaderExecutor.Open","ph":"B","ts":1762235547372200,"pid":0,"tid":2685358063,"cat":"general"},{"name":"distsql.Select","ph":"B","ts":1762235547372216,"pid":0,"tid":2685358063,"cat":"general"},{"name":"copr.buildCopTasks","ph":"B","ts":1762235547372231,"pid":0,"tid":2685358063,"cat":"general"},{"name":"copr.buildCopTasks","ph":"E","ts":1762235547372240,"pid":0,"tid":2685358063,"cat":"general"},{"name":"distsql.Select","ph":"E","ts":1762235547372245,"pid":0,"tid":2685358063,"cat":"general"},{"name":"TableReaderExecutor.Open","ph":"E","ts":1762235547372246,"pid":0,"tid":2685358063,"cat":"general"},{"name":"stmt.finish","ph":"i","ts":1762235547372249,"pid":0,"tid":2685358063,"cat":"stmt_lifecycle","args":{"sql_digest":"select * from `t`","plan_digest":"ccb0d7dbb386cbf97a7007105f4b9f48d79db972766c84bfba32e55df7ffede8","autocommit":true,"conn_id":2738880518,"retry_count":1,"trace_id":"00000000000000000000000000000000ef4f0fa0"}},{"name":"session.runStmt","ph":"E","ts":1762235547372250,"pid":0,"tid":2685358063,"cat":"general"},{"name":"session.ExecuteStmt","ph":"E","ts":1762235547372251,"pid":0,"tid":2685358063,"cat":"general"},{"name":"*executor.TableReaderExecutor.Next","ph":"B","ts":1762235547372270,"pid":0,"tid":2685358063,"cat":"general"},{"name":"kv.request.send","ph":"i","ts":1762235547372303,"pid":0,"tid":2685358063,"cat":"kv_request","args":{"cmd":"Cop","region_id":4,"region_ver":66,"region_confVer":1,"store_id":1,"store_addr":"192.168.0.226:20160","timeout":60,"region_start_key":"748000000000000003","region_end_key":"748000FFFFFFFFFFC4","trace_id":"00000000000000000000000000000000ef4f0fa0"}},{"name":"kv.request.result","ph":"i","ts":1762235547373094,"pid":0,"tid":2685358063,"cat":"kv_request","args":{"cmd":"Cop","latency":0.000739208,"success":true,"region_error":"message:\"EpochNotMatch current epoch of region 4 is conf_ver: 1 version: 67, but you sent conf_ver: 1 version: 66\" epoch_not_match:\u003ccurrent_regions:\u003cid:4 start_key:\"t\\200\\000\\000\\000\\000\\000\\000\\007\" end_key:\"t\\200\\000\\377\\377\\377\\377\\377\\304\" region_epoch:\u003cconf_ver:1 version:67 \u003e peers:\u003cid:5 store_id:1 \u003e \u003e \u003e ","trace_id":"00000000000000000000000000000000ef4f0fa0"}},{"name":"copr.buildCopTasks","ph":"B","ts":1762235547375466,"pid":0,"tid":2685358063,"cat":"general"},{"name":"copr.buildCopTasks","ph":"E","ts":1762235547375471,"pid":0,"tid":2685358063,"cat":"general"},{"name":"kv.request.send","ph":"i","ts":1762235547375492,"pid":0,"tid":2685358063,"cat":"kv_request","args":{"cmd":"Cop","region_id":4,"region_ver":67,"region_confVer":1,"store_id":1,"store_addr":"192.168.0.226:20160","timeout":60,"region_start_key":"748000000000000007","region_end_key":"748000FFFFFFFFFFC4","trace_id":"00000000000000000000000000000000ef4f0fa0"}},{"name":"kv.request.result","ph":"i","ts":1762235547376269,"pid":0,"tid":2685358063,"cat":"kv_request","args":{"cmd":"Cop","latency":0.000775375,"success":true,"trace_id":"00000000000000000000000000000000ef4f0fa0"}},{"name":"*executor.TableReaderExecutor.Next","ph":"E","ts":1762235547376302,"pid":0,"tid":2685358063,"cat":"general"}]
```

Each of those event json can be visualized in https://ui.perfetto.dev/
Just like this:

image

It's not as good as a previous demo https://github.com/pingcap/tidb/pull/60415 but it works good enough.

Support fine-grained control of what events should be recorded.

```
curl -X POST -d @config.json http://127.0.0.1:10080/debug/traceevent
```

All events:

```
{
	"enabled_categories": ["*"],
	"dump_trigger": {
		"type": "sampling"
		"sampling": 1
	}
}
```

1/1000 Sampling:

```
{
	"enabled_categories": ["*"],
	"dump_trigger": {
		"type": "sampling"
		"sampling": 1000
	}
}
```

Filter by categories:

```
{
	"enabled_categories": ["txn_2pc", "stmt_lifecycle"],
	"dump_trigger": {
		"type": "sampling"
		"sampling": 1
	}
}
```

Filter by user command, like sql regexp, plan digest, login user etc, here is example of plan_digest:

```
{
	"enabled_categories": ["general"],
	"dump_trigger": {
		"type": "user_command"
		"user_command" :  {
			"type": "plan_digest",
			"plan_digest": "42a1c8aae6f133e934d4bf0147491709a8812ea05ff8819ec522780fe657b772"
		}
	}
}
```

Filter by suspicious_event, like query fail, resolve lock, slow query etc

```
{
	"enabled_categories": ["general"],
	"dump_trigger": {
		"type": "suspicious_event"
		"suspicious_event":
		{
			"type": "resolve_lock"
		}
	}
}
```

Here is a overall view of config.json, once we found it's stable enough, we should document it.

```
//	{
//		"enabled_categories": ["general"],
//		"dump_trigger": {
//			"type": "sampling"
//			"sampling": 100
//			"suspicious_event":
//			{
//				"type": "long_txn",
//				"long_txn": ...,
//				"resolve_lock": ...,
//				"slow query": ...,
//				"error": ...,
//			},
//			"user_command" :  {
//				"type": "sql_regexp",
//				"sql_regexp": "select * from xx",
//				"plan_digest": "42a1c8aae6f133e934d4bf0147491709a8812ea05ff8819ec522780fe657b772",
//				"table": "test"
//				"by_user": "root",
//			}
//		}
//	}
```

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [X] Contains experimental features

Introduce new HTTP API http://127.0.0.1:10080/debug/traceevent

- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/http_status.go [hunk 1]
```diff
@@ -733,3 +739,117 @@ func (s *Server) newStatsPriorityQueueHandler() *optimizor.StatsPriorityQueueHan
...
+		e := Event{
+			Name:     event.Name,
+			Phase:    event.Phase,
+			Ts:       event.Timestamp.UnixMicro(),
+			PID:      0,
+			Category: event.Category.String(),
+		}
+		if len(event.TraceID) == 20 {
+			if tid == 0 {
+				tid = *((*uint32)(unsafe.Pointer(&event.TraceID[16])))
```
Comment (ekexium) [inline pkg/server/http_status.go]: It depends on the format of the trace id, which is subject to change. I suggest we introduce a method for the type TraceID to provide its info

File: pkg/executor/adapter.go [hunk 2]
```diff
@@ -1907,6 +1913,30 @@ func getEncodedPlan(stmtCtx *stmtctx.StatementContext, genHint bool) (encodedPla
...
+
+type stmtLabelAlias struct {
+	label string
+}
+
+func (s stmtLabelAlias) stmtLabelDumpTriggerCheck(config *traceevent.DumpTriggerConfig) bool {
+	return config.UserCommand.StmtLabel == s.label
+}
+
+type userAtlas struct {
```
Comment (ekexium) [inline pkg/executor/adapter.go]: alias?

File: pkg/server/http_status.go [hunk 3]
```diff
@@ -733,3 +739,118 @@ func (s *Server) newStatsPriorityQueueHandler() *optimizor.StatsPriorityQueueHan
 
 	return optimizor.NewStatsPriorityQueueHandler(do)
 }
+
+// Event defines the event structure for tracing.
+// See https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview?tab=t.0
+type Event struct {
```
Comment (ekexium) [inline pkg/server/http_status.go]: The trace event format related code is better placed in the traceevent package than in the http module.

**Comment by ekexium** [comment]
How do we define the relationship between the two packages `tracing` and `traceevent`? Should they be merged into one or not?

**Comment by tiancaiamao** [comment]
> I havem't reviewed all. Some of my current thoughts
> 
> 1. Can we use the system variable set configs, instead of via HTTP? We can have one simple HTTP API to trigger a one-time dump.
> 2. Will a set of plain key-value pairs be user-friendlier than a JSON? example: `set tidb_trace_event = 'enabled=true,sample_rate=100,digest=xxxxx,table=test1'`

1. Yes, I have another PR to do it, implement the system variable set config. https://github.com/tiancaiamao/tidb/pull/13
It's based on this PR and implement dump to log instead of HTTP.

2. For some simpler case, that would be easier to user. But JSON can provide the maxinum flexibility if we need to extend implementation. It's not so difficult to write json in SQL after all:

```
select  json_object('enabled_categories', json_array('*'), 'dump_trigger', json_object('type', 'sampling', 'sampling', 10));
+---------------------------------------------------------------------------------------------------------------------+
| json_object('enabled_categories', json_array('*'), 'dump_trigger', json_object('type', 'sampling', 'sampling', 10)) |
+---------------------------------------------------------------------------------------------------------------------+
| {"dump_trigger": {"sampling": 10, "type": "sampling"}, "enabled_categories": ["*"]}                                 |
+---------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

```
mysql> set @@global.tidb_trace_event_control = json_object('enabled_categories', json_array('*'), 'dump_trigger', json_object('type', 'sampling', 'sampling', 10));
Query OK, 0 rows affected (0.03 sec)
```

File: pkg/executor/adapter.go (hunk 2 above)
Comment (tiancaiamao) [reply pkg/executor/adapter.go]: oh, typo... 
It could be write just using a closure function, but I'm not sure the Go escape analyze optimization is good to avoid allocation. So I choose to keep it stupid here, I'm pretty sure this way it would not cause allocation.

File: pkg/server/http_status.go (hunk 3 above)
Comment (tiancaiamao) [reply pkg/server/http_status.go]: This Event definition is for https://ui.perfetto.dev/ to visualize the data...
Our current traceevent.Event definition is not the same as it.
TID is uint32 ... but our trace ID is []byte ... 

How about move it to traceevent and named as `RenderEvent`?
Or, we provide a json marshal on our current `traceevent.Event` definition ( maybe the implementation is just convert to internal RenderEvent and call json.Marshal) ?

**Comment by tiancaiamao** [comment]
> How do we define the relationship between the two packages `tracing` and `traceevent`? Should they by merged into one or not?

It's better to merge into one. @ekexium 
Currently, traceevent is heavier than tracing, it rely on log package etc
When I extend the `tracing.StartRegion` function,  it need to know `traceevent.Event`, then tracing depends on traceevent, and traceevent depends on log, and log depends on tracing ... cycle dependency!
So in this PR I have to move `traceevent.Event` related definition to tracing to avoid this cycle dependency.

File: pkg/server/http_status.go [hunk 4]
```diff
@@ -333,6 +334,7 @@ func (s *Server) startHTTPServer() {
 	router.HandleFunc("/debug/pprof/trace", pprof.Trace)
 	// Other /debug/pprof paths not covered above are redirected to pprof.Index.
 	router.PathPrefix("/debug/pprof/").HandlerFunc(pprof.Index)
+	router.HandleFunc("/debug/traceevent", traceeventHandler)
```
Comment (cfzjywxk) [inline pkg/server/http_status.go:337]: Do we still need the http api if the `json` session variable is used?

Comment (tiancaiamao) [reply pkg/server/http_status.go:337]: The benefit of keeping the json here, is that we don't need to handle the dump trigger config twice:
once in SQL and then http ... this would bring a lot conveniency

They're for different scenario: sink to log is mainly used for transaction bug reproduce and diagnosis
sink to http endpoint always used together with http://ui.prefetto.dev and is mainly for performance diagnosis

Comment (tiancaiamao) [reply pkg/server/http_status.go:337]: For example, when diagnosing performance issue, the enabled_categories tend to be 
`{enable_categories: ["*"], ...}`

when diagnosing transaction bug, it tend to be `{enable_categories: ["-", "general"], ...}` or `{enabled_categories: ["txn_2pc", "txn_lifecycle", "txn_lock_resolve"], ...}`

File: pkg/util/traceevent/flightrecorder.go [hunk 5]
```diff
@@ -0,0 +1,326 @@
...
+	oldEnabledCategories TraceCategory
+	counter              int // used when dump trigger config is sampling
+	Config               *FlightRecorderConfig
+	// Or should it be a Set if we support trigger condition combination?
+	triggerCanonicalName string
+}
+
+// UserCommandConfig is the configuration for DumpTriggerConfig of user command type.
+type UserCommandConfig struct {
+	Type       string `json:"type"`
```
Comment (ekexium) [inline pkg/util/traceevent/flightrecorder.go:53]: So `UserCommandConfig` is a tagged union type. Is `type` redundant? Can we simply assert that there must be exact 1 non-empty following fields?

That means simplifying from this
```json
"dump_trigger": {
	"type": "user_command",
	"user_command": {
       "type": "sql_regexp",
       "sql_regexp": "^select"
	}
}
```
to this
```json
"dump_trigger": {
	"user_command": {
       "sql_regexp": "^select"
	}
}
```

File: pkg/util/traceevent/flightrecorder.go [hunk 6]
```diff
@@ -0,0 +1,326 @@
...
+	default:
+		return fmt.Errorf("wrong dump_trigger.suspicious_event.type")
+	}
+	return nil
+}
+
+// DumpTriggerConfig is the configuration for dump trigger.
+type DumpTriggerConfig struct {
+	Type        string                 `json:"type"`
+	Sampling    int                    `json:"sampling,omitempty"`
```
Comment (ekexium) [inline pkg/util/traceevent/flightrecorder.go:136]: We'd better comment what the integer means and its valid value range. Or consider a more accurate name. Does it mean sample rate = 1/Sampling?

File: pkg/util/traceevent/flightrecorder.go [hunk 7]
```diff
@@ -0,0 +1,326 @@
...
+
+// MarkDump implements the FlightRecorder interface.
+func (r *Trace) MarkDump() {
+	r.keep = true
+}
+
+const maxEvents = 4096
+
+// Reset resets the Trace.
+func (r *Trace) Reset(ctx context.Context) {
```
Comment (ekexium) [inline pkg/util/traceevent/flightrecorder.go]: The name `Reset` doesn't imply it's the point to flush its content to the global http flight recorder. I would suggest renaming it.

**Review by ekexium — COMMENTED** [review]
Do we have 2 flight recorders now?
One is the `var flightRecorder = NewRingBufferSink(DefaultFlightRecorderCapacity)
`. Its events are recorded at the time of `TraceEvent`.
The other is the `HTTPFlightRecorder`, whose events are recorded after a statement finishes.
Is it necessary to have 2? Can we unify them into one?

Update:
I see, the HTTP flight recorder only lives during an HTTP request.
How about:
1. There is only one ring buffer as the only one "flight recorder"
2. `Trace` and `sinkKey` are not needed. `TraceEvent` is the only entry to add a event to the flight recorder.
3. When an HTTP request starts, attach a new sink the the ring buffer, which may have its own filters inside. Detach the sink when it's done

This feels more clear & elegant to me. What do you think?

File: pkg/server/conn.go [hunk 8]
```diff
@@ -1159,10 +1163,13 @@ func (cc *clientConn) Run(ctx context.Context) {
 			}
 		}
 
+		ctx = tracing.WithFlightRecorder(ctx, trace)
```
Comment (ekexium) [inline pkg/server/conn.go]: Is this a memory leak? Every call of this is creating a new wrapper ctx of the previous one

File: pkg/executor/adapter.go [hunk 9]
```diff
@@ -1935,6 +1965,11 @@ func (a *ExecStmt) SummaryStmt(succ bool) {
 	costTime := sessVars.GetTotalCostDuration()
 	charset, collation := sessVars.GetCharsetInfo()
 
+	// Not using closure to avoid unnecessary memory allocation.
+	traceevent.CheckFlightRecorderDumpTrigger(a.GoCtx, "dump_trigger.user_command.plan_digest", digestAlias{digest}.planDigestDumpTriggerCheck)
```
Comment (ekexium) [inline pkg/executor/adapter.go]: The name is plan_digest but `digest` is SQL digest?

File: pkg/util/traceevent/flightrecorder.go [hunk 10]
```diff
@@ -0,0 +1,326 @@
...
+
+// Record implements the FlightRecorder interface.
+func (r *Trace) Record(_ context.Context, event Event) {
+	r.mu.Lock()
+	defer r.mu.Unlock()
+	r.events = append(r.events, event)
+}
+
+// MarkDump implements the FlightRecorder interface.
+func (r *Trace) MarkDump() {
```
Comment (ekexium) [inline pkg/util/traceevent/flightrecorder.go:305]: Do `MarkDump` and `Reset` need to be protected under the mutex?

File: pkg/util/traceevent/flightrecorder.go [hunk 11]
```diff
@@ -0,0 +1,326 @@
...
+
+// Reset resets the Trace.
+func (r *Trace) Reset(ctx context.Context) {
+	sink := globalHTTPFlightRecorder.Load()
+	if sink != nil {
+		if r.keep {
+			sink.collect(ctx, r.events)
+		}
+		if sink.Config.DumpTrigger.Type == "sampling" {
+			sink.counter++
```
Comment (ekexium) [inline pkg/util/traceevent/flightrecorder.go:321]: Seems there can be race on `counter`

File: pkg/server/http_status.go [hunk 12]
```diff
@@ -733,3 +735,53 @@ func (s *Server) newStatsPriorityQueueHandler() *optimizor.StatsPriorityQueueHan
...
+	if len(body) > 0 {
+		if err := json.Unmarshal(body, &cfg); err != nil {
+			http.Error(w, fmt.Sprintf("decode json failed: %s", err.Error()), http.StatusBadRequest)
+			return
+		}
+	}
+
+	logutil.BgLogger().Info("http api /debug/traceevent called", zap.Any("config", cfg))
+	ch := make(chan []traceevent.Event, 256)
+	recorder, err := traceevent.StartHTTPFlightRecorder(ch, &cfg)
```
Comment (ekexium) [inline pkg/server/http_status.go:774]: Is it probelmatic when there are concurrent callers of the http api?

File: pkg/util/traceevent/flightrecorder.go (hunk 5 above)
Comment (tiancaiamao) [reply pkg/util/traceevent/flightrecorder.go:53]: The `type` field facilitate the `Validate()` process and make it hard to write silent incorrect configuration.
Maybe we can discuss here later after we add enough `CheckFlightRecorderDumpTrigger` condition. @ekexium 
This is not the finalized version before we have a formal document.

Comment (tiancaiamao) [reply pkg/util/traceevent/flightrecorder.go:53]: And there is also another desision to made: whether we should support `or` / `and` condition ... this also affect the json design.

Comment (ekexium) [reply pkg/util/traceevent/flightrecorder.go:53]: It's ok we keep it as-is and refine it later

File: pkg/executor/adapter.go (hunk 9 above)
Comment (ekexium) [inline pkg/executor/adapter.go]: Is this place too late to trigger? TiKV requests might have completed.

File: pkg/util/traceevent/flightrecorder.go (hunk 11 above)
Comment (tiancaiamao) [reply pkg/util/traceevent/flightrecorder.go:321]: Usually this will not happen, `Reset()` is not called concurrently, it's just after `dispatch` in the conn dispatch loop.

File: pkg/executor/adapter.go (hunk 9 above)
Comment (tiancaiamao) [reply pkg/executor/adapter.go]: Yes, that's the problem.... we can know some informations before hand
But we cannot guarantee all dump trigger condition be checked before sending tikv requests.

File: pkg/util/traceevent/flightrecorder.go (hunk 7 above)
Comment (tiancaiamao) [reply pkg/util/traceevent/flightrecorder.go]: Renamed to `DiscardOrFlush`

File: pkg/executor/adapter.go (hunk 9 above)
Comment (tiancaiamao) [reply pkg/executor/adapter.go]: fixed

File: pkg/util/traceevent/flightrecorder.go (hunk 10 above)
Comment (tiancaiamao) [reply pkg/util/traceevent/flightrecorder.go:305]: done

File: pkg/server/http_status.go (hunk 12 above)
Comment (tiancaiamao) [reply pkg/server/http_status.go:774]: fixed

File: pkg/executor/adapter.go (hunk 9 above)
Comment (ekexium) [reply pkg/executor/adapter.go]: I suppose digest, user and label are available at the beginning of a statement. Can we move the check forward?

File: pkg/util/traceevent/flightrecorder.go [hunk 13]
```diff
@@ -0,0 +1,339 @@
...
+	r.mu.Lock()
+	defer r.mu.Unlock()
+	r.events = append(r.events, event)
+}
+
+// MarkDump implements the FlightRecorder interface.
+func (r *Trace) MarkDump() {
+	r.mu.Lock()
+	r.keep = true
+	r.mu.Lock()
```
Comment (ekexium) [inline pkg/util/traceevent/flightrecorder.go]: Unlock :)

File: pkg/util/traceevent/flightrecorder.go (hunk 11 above)
Comment (ekexium) [reply pkg/util/traceevent/flightrecorder.go:321]: `counter` is part of the global sink, which can be concurrently accessed by multiple sessions calling `Reset`

File: pkg/session/session.go [hunk 14]
```diff
@@ -1896,11 +1897,22 @@ func (s *session) Execute(ctx context.Context, sql string) (recordSets []sqlexec
 	return []sqlexec.RecordSet{rs}, err
 }
 
+type sqlRegexp struct {
+	regexp string
+}
+
+func (s sqlRegexp) sqlRegexpDumpTriggerCheck(cfg *traceevent.DumpTriggerConfig) bool {
+	match, err := regexp.MatchString(cfg.UserCommand.SQLRegexp, s.regexp)
```
Comment (ekexium) [inline pkg/session/session.go:1906]: It compiles every time. Consider compile once and reuse.
We can leave a TODO here and optimize it later
