### PR TITLE
statistics: add default value of CMSketch for `Analyze`

### LINKED ISSUE #19343: statistic: the default value of CMSketch is not initialized correctly when using `Analyze`
## Development Task
How to reproduce:
```
create table t (a int, key(a));
insert into t values (0);
insert into t values (0);
...
insert into t values (0); // insert 2048 rows

insert into t values (1);
insert into t values (2);
insert into t values (3);

analyze table t with 0 topn;
explain select * from t where a = 1;
explain select * from t where a = 2;
explain select * from t where a = 3;
```

The estimated rows for `a = 1/2/3` is zero, which is not accurate.

This is a bad case for the heuristic rule of removing noise when estimating point get:
```
		noise := (c.count - uint64(c.table[i][j])) / (uint64(c.width) - 1)
		if uint64(c.table[i][j]) < noise {
			vals[i] = 0
		} else {
			vals[i] = c.table[i][j] - uint32(noise)
		}
```

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: close #19343 

Problem Summary:
Add default value of CMSketch for `Analyze`

### What is changed and how it works?
We use `count / NDV` in CMSketch as default value. This means count and NDV are not include topN.

Proposal: [xxx](url) 

What's Changed:
- Use `count / NDV` as default value.
- In `queryHashValue`, if `res` is 0 before the noise is eliminated, the default value is not used.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- 
- Add default value of CMSketch for Analyze

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
Is the CM-Sketch for table column have the same problem?

**Comment by rebelice** [comment]
> Does the CM-Sketch for table column have the same problem?

Yes. But the reason why estRows is 0 when using `Analyze` table column is more complicated. There are other factors that cause it and unstable. It is currently under investigation.

**Comment by zz-jason** [comment]
> There are other factors that cause it and unstable. It is currently under investigation.

Is there an issue for this abnormal phenomenon?

**Comment by rebelice** [comment]
> > There are other factors that cause it and unstable. It is currently under investigation.
> 
> Is there an issue for this abnormal phenomenon?

[issues/19537](https://github.com/pingcap/tidb/issues/19537)

File: statistics/cmsketch.go [hunk 1]
```diff
@@ -547,3 +556,13 @@ func (c *CMSketch) AppendTopN(data []byte, count uint64) {
 func (c *CMSketch) GetWidthAndDepth() (int32, int32) {
 	return c.width, c.depth
 }
+
+// CalcDefaultValForAnalyze calculate the default value for Analyze.
+// The value of it is count / NDV in CMSketch. This means count and NDV are not include topN.
+func (c *CMSketch) CalcDefaultValForAnalyze(NDV uint64) {
+	if NDV < uint64(len(c.topN)) {
+		c.defaultValue = c.count
+	}
```
Comment (qw4990) [inline statistics/cmsketch.go:565]: If `NDV < TopN`, we can set `c.defaultValue` to zero and return immediately since all values should be in `TopN`.

Comment (rebelice) [reply statistics/cmsketch.go:565]: Agree with that.

File: statistics/cmsketch.go [hunk 2]
```diff
@@ -547,3 +556,14 @@ func (c *CMSketch) AppendTopN(data []byte, count uint64) {
 func (c *CMSketch) GetWidthAndDepth() (int32, int32) {
 	return c.width, c.depth
 }
+
+// CalcDefaultValForAnalyze calculate the default value for Analyze.
+// The value of it is count / NDV in CMSketch. This means count and NDV are not include topN.
+func (c *CMSketch) CalcDefaultValForAnalyze(NDV uint64) {
+	if NDV < uint64(len(c.topN)) {
+		c.defaultValue = 0
+		return
```
Comment (qw4990) [inline statistics/cmsketch.go:565]: Almost LGTM. Please add some comments for this branch.

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
PTAL @winoros @eurekaka @lzmhhh123 @zz-jason

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
