### PR TITLE
metric: fix panic when status.record-db-label enable

### LINKED ISSUE #41688: Meet `invalid memory address or nil pointer dereference`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. start up TiDB cluseter by tiup
2. import data
3. exeute the flowing sql:
```
USE sample_data;
WITH starts_by_day AS
  (SELECT repo_name,
          date(created_at) AS DAY,
          COUNT(1) AS stars
   FROM github_events
   WHERE TYPE = 'WatchEvent'
   GROUP BY repo_name,
            DAY)
SELECT s.repo_name,
       max(s.stars) AS daily_stars,
       sum(s.stars) AS total_stars,
       sum(s.stars) / max(s.stars) AS rate
FROM starts_by_day AS s
GROUP BY repo_name
ORDER BY rate DESC
LIMIT 10;
```
### 2. What did you expect to see? (Required)
sql executed successfully

### 3. What did you see instead (Required)
runtime error: invalid memory address or nil pointer dereference

### 4. What is your TiDB version? (Required)
nightly

image

### PR DESCRIPTION
**Pull request by srstack**
### What problem does this PR solve?

Issue Number: close #41688 

Problem Summary:  meet panic when status.record-db-label enable
image

### What is changed and how it works?

add nil check

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] 
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/compiler.go [hunk 1]
```diff
@@ -216,26 +216,37 @@ func getStmtDbLabel(stmtNode ast.StmtNode) map[string]struct{} {
 
 	switch x := stmtNode.(type) {
 	case *ast.AlterTableStmt:
```
Comment (hawkingrei) [inline executor/compiler.go:218]: Have tests?

Comment (srstack) [reply executor/compiler.go:218]: Added a CTE statement to test the issue

**Review by jackysp — APPROVED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]
