### PR TITLE
*: fix memory leak after dom.Close

### LINKED ISSUE #18048: memory leak in mockstore
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
package main

import (
	"os"
	"runtime/pprof"

	"github.com/pingcap/tidb/session"
	. "github.com/pingcap/tidb/store/mockstore"
)

func testMock() {
	opts := []MockTiKVStoreOption{WithStoreType(MockTiKV)}
	store, _ := NewMockStore(opts...)
	defer store.Close()

	dom, _ := session.BootstrapSession(store)
	defer dom.Close()
}

func main() {
	for i := 0; i < 10; i++ {
		testMock()
	}
	f, _ := os.Create("heap_profile")
	pprof.WriteHeapProfile(f)
}
```

### 2. What did you expect to see? (Required)
free the memory when dom.Close()
### 3. What did you see instead (Required)
out

### 4. Affected version (Required)
tidb master

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #18048

Problem Summary: memory leak after dom.Close 

### What is changed and how it works?

How it Works: 
- remove store from `domap` when dom.Close
- expose a way to not RegisterStatistics to global variables

### Check List 

Tests 

- [x] Unit test

Side effects

Documentation

### Release note 

```release-note
None
```

### CODE REVIEW

File: domain/domain.go [hunk 1]
```diff
@@ -605,6 +605,9 @@ func (do *Domain) isClose() bool {
 	return false
 }
 
+// DomainMapDelete is used to avoid cycle import with `session` package.
+var DomainMapDelete func (kv.Storage)
```
Comment (gozssky) [inline domain/domain.go:609]: How about adding a `callback' to Domain instead of another global variable?

File: session/tidb.go [hunk 2]
```diff
@@ -42,6 +42,12 @@ import (
 	"go.uber.org/zap"
 )
 
+func init() {
+	domain.DomainMapDelete = func(store kv.Storage) {
+		domap.Delete(store)
```
Comment (gozssky) [inline session/tidb.go:47]: There is another global map `storeBootstrapped` which hold a `storeUUID -> bool`. `ResetStoreForWithTiKVTest` is a similar  function to clean the two maps.

File: sessionctx/variable/statusvar.go [hunk 3]
```diff
@@ -42,8 +42,11 @@ type Statistics interface {
 	Stats(*SessionVars) (map[string]interface{}, error)
 }
 
-// RegisterStatistics registers statistics.
-func RegisterStatistics(s Statistics) {
+// RegisterStatistics is exposed to avoid holding a reference in global variables, when using TiDB as a library.
+var RegisterStatistics = registerStatistics
+
+// registerStatistics registers statistics.
+func registerStatistics(s Statistics) {
```
Comment (gozssky) [inline sessionctx/variable/statusvar.go:49]: I think we should add a function like `UnregisterStatistics` and called it when domain or ddl is closed. It seems memory leak also happened in TiDB server, because `BootstrapSession` open `domain` twice.

File: domain/domain.go (hunk 1 above)
Comment (lance6716) [reply domain/domain.go:609]: how can we pass the callback? domain package can't access session package

File: sessionctx/variable/statusvar.go (hunk 3 above)
Comment (lance6716) [reply sessionctx/variable/statusvar.go:49]: there's no id for `Statistics`, we can't find the one we appended (maybe by memory address?)

File: domain/domain.go (hunk 1 above)
Comment (gozssky) [reply domain/domain.go]: like this
```go
type Domain struct {
	callback func()
}
```

File: sessionctx/variable/statusvar.go (hunk 3 above)
Comment (gozssky) [reply sessionctx/variable/statusvar.go:49]: Directly comparing interface?

File: domain/domain.go (hunk 1 above)
Comment (gozssky) [reply domain/domain.go]: On the other hand,  `domain` is created by `domap.Get()`, so is `domap's` responsibility to call `Close`?

**Comment by gozssky** [comment]
https://github.com/pingcap/tidb/blob/c26038ba5eb32bc12689f00fb6c73763dfbc0339/bindinfo/handle.go#L106-L122

`BindHandle` also need to unregister statistics.

**Comment by lance6716** [comment]
> https://github.com/pingcap/tidb/blob/c26038ba5eb32bc12689f00fb6c73763dfbc0339/bindinfo/handle.go#L106-L122
> 
> `BindHandle` also need to unregister statistics.

its assigned to Domain and unregistered in `variable.UnregisterStatistics(do.bindHandle)`

**Comment by gozssky** [comment]
> > https://github.com/pingcap/tidb/blob/c26038ba5eb32bc12689f00fb6c73763dfbc0339/bindinfo/handle.go#L106-L122
> > 
> > `BindHandle` also need to unregister statistics.
> 
> its assigned to Domain and unregistered in `variable.UnregisterStatistics(do.bindHandle)`

I missed it 😂

**Review by gozssky — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Comment by tiancaiamao** [comment]
```
[2021-09-14T05:31:45.434Z] ----------------------------------------------------------------------
[2021-09-14T05:31:45.434Z] FAIL: bootstrap_test.go:324: testBootstrapSuite.TestIssue17979_2
[2021-09-14T05:31:45.434Z] 
[2021-09-14T05:31:45.434Z] bootstrap_test.go:364:
[2021-09-14T05:31:45.434Z]     c.Assert(config.GetGlobalConfig().OOMAction, Equals, config.OOMActionCancel)
[2021-09-14T05:31:45.434Z] ... obtained string = "log"
[2021-09-14T05:31:45.434Z] ... expected string = "cancel"
[2021-09-14T05:31:45.434Z] 
[2021-09-14T05:31:46.002Z] 
[2021-09-14T05:31:46.002Z] ----------------------------------------------------------------------
```

**Comment by lance6716** [comment]
> ```
> [2021-09-14T05:31:45.434Z] ----------------------------------------------------------------------
> [2021-09-14T05:31:45.434Z] FAIL: bootstrap_test.go:324: testBootstrapSuite.TestIssue17979_2
> [2021-09-14T05:31:45.434Z] 
> [2021-09-14T05:31:45.434Z] bootstrap_test.go:364:
> [2021-09-14T05:31:45.434Z]     c.Assert(config.GetGlobalConfig().OOMAction, Equals, config.OOMActionCancel)
> [2021-09-14T05:31:45.434Z] ... obtained string = "log"
> [2021-09-14T05:31:45.434Z] ... expected string = "cancel"
> [2021-09-14T05:31:45.434Z] 
> [2021-09-14T05:31:46.002Z] 
> [2021-09-14T05:31:46.002Z] ----------------------------------------------------------------------
> ```

I can't reproduce it in my local `go test -check.f "...TestIssue17979_2"`, need your help 😂
