### PR TITLE
BR: add lock with ttl for checkpoint backup

### LINKED ISSUE #40561: the same task run on different BRs at the same time when BR use checkpoint mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. run BR
2. run another BR with the same parameter

### 2. What did you expect to see? (Required)
1. the second BR runs failed　
### 3. What did you see instead (Required)
2. the second BR runs successfully
### 4. What is your TiDB version? (Required)
master/v6.5.0

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #40561 

Problem Summary:
Add a lock with ttl for checkpoint backup, in order to prevent the same task from being run on different BRs at the same time.

### What is changed and how it works?
1. flush a lock file with ttl to the external storage regularly.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/checkpoint/checkpoint.go [hunk 1]
```diff
@@ -464,6 +524,115 @@ func (r *CheckpointRunner) doFlush(ctx context.Context, meta map[string]*RangeGr
 	return nil
 }
 
+type CheckpointLock struct {
+	LockId   uint64 `json:"lock-id"`
+	LockAt   int64  `json:"lock-at"`
```
Comment (YuJuncen) [inline br/pkg/checkpoint/checkpoint.go:529]: It seems that this field is only used for logging, can we remove it?

File: br/pkg/checkpoint/checkpoint.go [hunk 2]
```diff
@@ -464,6 +524,115 @@ func (r *CheckpointRunner) doFlush(ctx context.Context, meta map[string]*RangeGr
...
+	if err != nil {
+		return errors.Trace(err)
+	}
+	r.lockId = oracle.ComposeTS(p, l)
+	exist, err := r.storage.FileExists(ctx, CheckpointLockPath)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if exist {
+		if err := r.checkLockFile(ctx, "initialize checkpoint lock", p); err != nil {
```
Comment (YuJuncen) [inline br/pkg/checkpoint/checkpoint.go:622]: Maybe we can use `errors.Annotate` here instead of pass the caller explicitly, given the `caller` field is only used for annotating the error.

**Review by YuJuncen — COMMENTED** [review]
rest lgtm

File: br/pkg/checkpoint/checkpoint.go [hunk 3]
```diff
@@ -337,6 +379,15 @@ func (r *CheckpointRunner) startCheckpointRunner(ctx context.Context, wg *sync.W
 					errCh <- err
 					return
 				}
+			case _, ok := <-r.lockCh:
+				if !ok {
+					log.Info("stop checkpoint flush worker")
+					return
+				}
+				if err := r.updateLock(ctx); err != nil {
```
Comment (3pointer) [inline br/pkg/checkpoint/checkpoint.go:387]: How about the stability of `updateLock` function, will it introduce some stability issue for backup?

File: br/pkg/checkpoint/checkpoint.go [hunk 4]
```diff
@@ -464,6 +524,113 @@ func (r *CheckpointRunner) doFlush(ctx context.Context, meta map[string]*RangeGr
...
+		if err := r.checkLockFile(ctx, p); err != nil {
+			return errors.Trace(err)
+		}
+	}
+	if err = r.flushLock(ctx, p); err != nil {
+		return errors.Trace(err)
+	}
+
+	// wait for 3 seconds to check whether the lock file is overwritten by another BR
+	time.Sleep(3 * time.Second)
```
Comment (3pointer) [inline br/pkg/checkpoint/checkpoint.go:629]: why 3 seconds? `tickDurationForLock` seems need 4 minutes to finish one `flushLock`.

File: br/pkg/checkpoint/checkpoint.go (hunk 3 above)
Comment (Leavrth) [reply br/pkg/checkpoint/checkpoint.go:387]: The function `updateLock` do 3 things in total:
1. get TS from pd with retry.
2. read lock from external storage.
3. write lock to external storage.

it would fail only when pd or external storage is unavailable to BR.

Comment (3pointer) [reply br/pkg/checkpoint/checkpoint.go:387]: so can we ignore this error. and wait for next time `updateLock` occur?

File: br/pkg/checkpoint/checkpoint.go (hunk 4 above)
Comment (Leavrth) [reply br/pkg/checkpoint/checkpoint.go:629]: This lock initialization is not an atomic operation. 
1. BR reads the lock at first to check whether the lock belongs to it or the lock has expired.  (atomic)
2. BR write the lock to external storage. (atomic)

BR-A and BR-B do the step-1 at the same time, they find the lock does not exist or the lock has expired. So they are both go to the step-2.

If there is no check again, both BRs will begin to backup file. So we wait for 3 seconds to determine whether multi BRs do step-1 at the same time.

**Review by 3pointer — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
