### PR TITLE
util, executor: parse set value correctly in HashChunkRow

### LINKED ISSUE #20219: Lost connection to MySQL server during query
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use test;
source [test.txt](https://github.com/pingcap/tidb/files/5281854/test.txt);
SELECT /*+ inl_hash_join(t1) */ t1.pk, t2.pk from table_290_utf8_undef t1 right join table_290_utf8_undef t2 on t1. `col_char20_key_signed` = t2. `col_set_key_signed` and t1. `col_bool_key_signed` = t2. `col_enum_key_signed` where t1. `col_smallint_key_unsigned` != -969 order by t1.pk, t2.pk;

tidb stack info
```
panic: runtime error: index out of range [4194303] with length 26 [recovered]
	panic: send on closed channel

goroutine 146332 [running]:
github.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).handleHashJoinInnerWorkerPanic(0xc0013c0600, 0x2e84d60, 0xc001b933a0)
	/root/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:572 +0x10a
github.com/pingcap/tidb/util.WithRecovery.func1(0xc001ec8fd0)
	/root/go/src/github.com/pingcap/tidb/util/misc.go:88 +0x324
panic(0x2e84d60, 0xc001b933a0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/pingcap/tidb/util/codec.encodeHashChunkRowIdx(0xc0001eb600, 0xc000c9a4b0, 0x0, 0xc0011b5cb0, 0x1, 0xc001bc3800, 0xc0011dee10, 0x107c7ff, 0x2cad100, 0xc0011dee10, ...)
	/root/go/src/github.com/pingcap/tidb/util/codec/codec.go:367 +0xc10
github.com/pingcap/tidb/util/codec.HashChunkRow(0xc0001eb600, 0x7fd4e42ec0f8, 0xc0015227e0, 0xc000c9a4b0, 0x0, 0xc00190e080, 0x3, 0x3, 0xc001e3da80, 0x1, ...)
	/root/go/src/github.com/pingcap/tidb/util/codec/codec.go:660 +0x110
github.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).buildHashTableForOuterResult(0xc0013c0600, 0x358dc20, 0xc001b8fc80, 0xc001ea78c0, 0x35a8520, 0xc0015227e0)
	/root/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:548 +0x3b1
github.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).handleTask.func2()
	/root/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:591 +0x57
github.com/pingcap/tidb/util.WithRecovery(0xc001c48c80, 0xc001ec8fd0)
	/root/go/src/github.com/pingcap/tidb/util/misc.go:96 +0x4f
created by github.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).handleTask
	/root/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:591 +0x1bb
```
### 2. What did you expect to see? (Required)
Don't have runtime error

### 3. What did you see instead (Required)
infinite loop query sql 
```
mysql> SELECT /*+ inl_hash_join(t1) */ t1.pk, t2.pk from table_290_utf8_undef t1 right join table_290_utf8_undef t2 on t1. `col_char20_key_signed` = t2. `col_set_key_signed` and t1. `col_bool_key_signed` = t2. `col_enum_key_signed` where t1. `col_smallint_key_unsigned` != -969 order by t1.pk, t2.pk;
ERROR 1105 (HY000): runtime error: index out of range [65535] with length 26
mysql> SELECT /*+ inl_hash_join(t1) */ t1.pk, t2.pk from table_290_utf8_undef t1 right join table_290_utf8_undef t2 on t1. `col_char20_key_signed` = t2. `col_set_key_signed` and t1. `col_bool_key_signed` = t2. `col_enum_key_signed` where t1. `col_smallint_key_unsigned` != -969 order by t1.pk, t2.pk;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
### 4. What is your TiDB version? (Required)

master 32d86e26c and release-4.0 ed939f3f1

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close #20219 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Parse set value correctly in HashChunkRow

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: util/codec/codec.go [hunk 1]
```diff
@@ -363,9 +363,11 @@ func encodeHashChunkRowIdx(sc *stmtctx.StatementContext, row chunk.Row, tp *type
 		b = ConvertByCollation(hack.Slice(str), tp)
 	case mysql.TypeSet:
 		flag = compactBytesFlag
-		v := uint64(row.GetSet(idx).ToNumber())
-		str := tp.Elems[v-1]
-		b = ConvertByCollation(hack.Slice(str), tp)
+		s, err := types.ParseSetValue(tp.Elems, row.GetSet(idx).Value)
+		if err != nil {
```
Comment (wjhuang2016) [inline util/codec/codec.go:367]: Please change `HashChunkSelected()` too.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
