### PR TITLE
planner: let partition table use PointGet in non-fastPlan | tidb-test=pr/2185

### LINKED ISSUE #45354: cannot generate PointGet plan for partition table with date partition key
## Bug Report

cannot generate PointGet plan for partition table with date partition key, but partition table with int partition key can generate PointGet plan.

### 1. Minimal reproduce step (Required)

```
CREATE TABLE ccccc (
    id INT NOT NULL,
    fname VARCHAR(30),
    lname VARCHAR(30),
    hired DATE NOT NULL DEFAULT '1970-01-01',
    separated DATE DEFAULT '9999-12-31',
    job_code INT,
    store_id INT NOT NULL,
    primary key (id,separated) 
)
PARTITION BY list (day(separated)) (
    PARTITION p0 VALUES in (1),
    PARTITION p1 VALUES in (2),
    PARTITION p2 VALUES  in (3)
);

insert into ccccc values(1,'a','a','1970-01-01','1970-01-01',1,1);

explain update ccccc set lname='test1' where id=1 and separated='1970-01-01' limit 1;


analyze table ccccc;

explain update ccccc set lname='test1' where id=1 and separated='1970-01-01' limit 1;  # except Point_Get_12 plan but get IndexRangeScan_11




CREATE TABLE ddddd (
    id INT NOT NULL,
    fname VARCHAR(30),
    lname VARCHAR(30),
    hired DATE NOT NULL DEFAULT '1970-01-01',
    separated DATE DEFAULT '9999-12-31',
    job_code INT,
    store_id INT NOT NULL,
    primary key (id,store_id) 
)
PARTITION BY list (store_id) (
    PARTITION p0 VALUES in (1),
    PARTITION p1 VALUES in (2),
    PARTITION p2 VALUES  in (3)
);


insert into ddddd values(1,'a','a','1970-01-01','1970-01-01',1,1);
insert into ddddd values(2,'b','b','1970-01-02','1970-01-02',2,2);

explain update ddddd set lname='test1' where id=1 and store_id=1 limit 1; 

analyze table ddddd;


explain update ddddd set lname='test1' where id=1 and store_id=1 limit 1; 

```
### 2. What did you expect to see? (Required)

all update statement has pointget plan.

### 3. What did you see instead (Required)
```
MySQL [test]> CREATE TABLE ccccc (
    ->     id INT NOT NULL,
    ->     fname VARCHAR(30),
    ->     lname VARCHAR(30),
    ->     hired DATE NOT NULL DEFAULT '1970-01-01',
    ->     separated DATE DEFAULT '9999-12-31',
    ->     job_code INT,
    ->     store_id INT NOT NULL,
    ->     primary key (id,separated)
    -> )
    -> PARTITION BY list (day(separated)) (
    ->     PARTITION p0 VALUES in (1),
    ->     PARTITION p1 VALUES in (2),
    ->     PARTITION p2 VALUES  in (3)
    -> );
Query OK, 0 rows affected (0.16 sec)

MySQL [test]>
MySQL [test]> insert into ccccc values(1,'a','a','1970-01-01','1970-01-01',1,1);
Query OK, 1 row affected (0.02 sec)

MySQL [test]>
MySQL [test]> explain update ccccc set lname='test1' where id=1 and separated='1970-01-01' limit 1;
+----------------------+---------+------+---------------------------------------------------------+-------------------+
| id                   | estRows | task | access object                                           | operator info     |
+----------------------+---------+------+---------------------------------------------------------+-------------------+
| Update_5             | N/A     | root |                                                         | N/A               |
| └─Limit_11           | 1.00    | root |                                                         | offset:0, count:1 |
|   └─Point_Get_12     | 1.00    | root | table:ccccc, partition:p0, index:PRIMARY(id, separated) |                   |
+----------------------+---------+------+---------------------------------------------------------+-------------------+
3 rows in set, 1 warning (0.00 sec)

MySQL [test]>
MySQL [test]>
MySQL [test]> analyze table ccccc;
Query OK, 0 rows affected, 6 warnings (0.61 sec)

MySQL [test]>
MySQL [test]> explain update ccccc set lname='test1' where id=1 and separated='1970-01-01' limit 1;   # except Point_Get_12 plan but get IndexRangeScan_11
+----------------------------------+---------+-----------+-------------------------------------------+-----------------------------------------------------+
| id                               | estRows | task      | access object                             | operator info                                       |
+----------------------------------+---------+-----------+-------------------------------------------+-----------------------------------------------------+
| Update_5                         | N/A     | root      |                                           | N/A                                                 |
| └─IndexLookUp_14                 | 1.00    | root      | partition:p0                              | limit embedded(offset:0, count:1)                   |
|   ├─Limit_13(Build)              | 1.00    | cop[tikv] |                                           | offset:0, count:1                                   |
|   │ └─IndexRangeScan_11          | 1.00    | cop[tikv] | table:ccccc, index:PRIMARY(id, separated) | range:[1 1970-01-01,1 1970-01-01], keep order:false |
|   └─TableRowIDScan_12(Probe)     | 1.00    | cop[tikv] | table:ccccc                               | keep order:false                                    |
+----------------------------------+---------+-----------+-------------------------------------------+-----------------------------------------------------+
5 rows in set (0.01 sec)

MySQL [test]>




MySQL [test]> CREATE TABLE ddddd (
    ->     id INT NOT NULL,
    ->     fname VARCHAR(30),
    ->     lname VARCHAR(30),
    ->     hired DATE NOT NULL DEFAULT '1970-01-01',
    ->     separated DATE DEFAULT '9999-12-31',
    ->     job_code INT,
    ->     store_id INT NOT NULL,
    ->     primary key (id,store_id)
    -> )
    -> PARTITION BY list (store_id) (
    ->     PARTITION p0 VALUES in (1),
    ->     PARTITION p1 VALUES in (2),
    ->     PARTITION p2 VALUES  in (3)
    -> );
Query OK, 0 rows affected (0.16 sec)

MySQL [test]>
MySQL [test]>
MySQL [test]> insert into ddddd values(1,'a','a','1970-01-01','1970-01-01',1,1);
Query OK, 1 row affected (0.31 sec)

MySQL [test]> insert into ddddd values(2,'b','b','1970-01-02','1970-01-02',2,2);
Query OK, 1 row affected (0.01 sec)

MySQL [test]>
MySQL [test]> explain update ddddd set lname='test1' where id=1 and store_id=1 limit 1;
+-------------------+---------+------+--------------------------------------------------------+---------------+
| id                | estRows | task | access object                                          | operator info |
+-------------------+---------+------+--------------------------------------------------------+---------------+
| Update_3          | N/A     | root |                                                        | N/A           |
| └─Point_Get_1     | 1.00    | root | table:ddddd, partition:p0, index:PRIMARY(id, store_id) |               |
+-------------------+---------+------+--------------------------------------------------------+---------------+
2 rows in set (0.00 sec)

MySQL [test]>
MySQL [test]> analyze table ddddd;
Query OK, 0 rows affected, 6 warnings (0.63 sec)

MySQL [test]>
MySQL [test]>
MySQL [test]> explain update ddddd set lname='test1' where id=1 and store_id=1 limit 1;
+-------------------+---------+------+--------------------------------------------------------+---------------+
| id                | estRows | task | access object                                          | operator info |
+-------------------+---------+------+--------------------------------------------------------+---------------+
| Update_3          | N/A     | root |                                                        | N/A           |
| └─Point_Get_1     | 1.00    | root | table:ddddd, partition:p0, index:PRIMARY(id, store_id) |               |
+-------------------+---------+------+--------------------------------------------------------+---------------+
2 rows in set (0.00 sec)

MySQL [test]>
```
### 4. What is your TiDB version? (Required)

```
Release Version: v6.5.2
Edition: Community
Git Commit Hash: 29116c0256c52b224da2b34d712c1063d171c0ad
Git Branch: heads/refs/tags/v6.5.2
UTC Build Time: 2023-04-19 10:52:06
GoVersion: go1.19.8
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #45354

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
func BenchmarkPointGet(b *testing.B) {
	ctx := context.Background()
	se, do, st := prepareBenchSession()
	defer func() {
		se.Close()
		do.Close()
		st.Close()
	}()
	mustExecute(se, "create table t (pk int primary key) partition by hash(pk) partitions 4")
	mustExecute(se, "insert t values (61),(62),(63),(64),(-1),(-2)")
	mustExecute(se, "analyze table t")
	b.ResetTimer()
	alloc := chunk.NewAllocator()
	for i := 0; i < b.N; i++ {
		rs, err := se.Execute(ctx, "select * from t where pk = -1")
		if err != nil {
			b.Fatal(err)
		}
		_, err = drainRecordSet(ctx, se.(*session), rs[0], alloc)
		if err != nil {
			b.Fatal(err)
		}

		alloc.Reset()
	}
	b.StopTimer()
}

before (TableScan)
BenchmarkPointGet-8   	    8542	    123092 ns/op	   65296 B/op	     966 allocs/op

after (PointGet)
BenchmarkPointGet-8   	   18720	     64514 ns/op	   46968 B/op	     681 allocs/op
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

File: planner/core/find_best_task.go [hunk 1]
```diff
@@ -1118,10 +1118,6 @@ func (ds *DataSource) findBestTask(prop *property.PhysicalProperty, planCounter
 		}
 		var hashPartColName *model.CIStr
 		if tblInfo := ds.table.Meta(); canConvertPointGet && tblInfo.GetPartitionInfo() != nil {
-			// We do not build [batch] point get for dynamic table partitions now. This can be optimized.
-			if ds.ctx.GetSessionVars().StmtCtx.UseDynamicPartitionPrune() {
-				canConvertPointGet = false
-			}
 			if canConvertPointGet && len(path.Ranges) > 1 {
 				// We can only build batch point get for hash partitions on a simple column now. This is
```
Comment (mjonss) [inline planner/core/find_best_task.go:1122]: Please create a follow-up enhancement issue, for adding the support for Range and List partitioned tables as well. Since it currently looks like it only support Key and Hash partitioned tables.

File: planner/core/find_best_task.go [hunk 2]
```diff
@@ -2377,6 +2375,22 @@ func (ds *DataSource) convertToPointGet(prop *property.PhysicalProperty, candida
 		if partitionInfo == nil {
 			return invalidTask
 		}
+	} else if pi != nil && ds.SCtx().GetSessionVars().StmtCtx.UseDynamicPruneMode {
```
Comment (mjonss) [inline planner/core/find_best_task.go:2378]: Can UseDynamicPruneMode be false here (if pi != nil)? Would not that be inconsistent with the setting of ds.isPartition above?

File: planner/core/find_best_task.go [hunk 3]
```diff
@@ -2377,6 +2375,22 @@ func (ds *DataSource) convertToPointGet(prop *property.PhysicalProperty, candida
...
+		// dynamic prune
+		idxs, err := PartitionPruning(ds.ctx, ds.table.GetPartitionedTable(), ds.allConds, ds.partitionNames, ds.TblCols, ds.names)
```
Comment (mjonss) [inline planner/core/find_best_task.go:2380]: Do `convertToBatchPointGet` need the same change?

File: planner/core/find_best_task.go (hunk 1 above)
Comment (Defined2014) [reply planner/core/find_best_task.go:1122]: Opened https://github.com/pingcap/tidb/issues/45532

File: planner/core/find_best_task.go (hunk 2 above)
Comment (Defined2014) [reply planner/core/find_best_task.go]: Updated

File: planner/core/find_best_task.go (hunk 3 above)
Comment (Defined2014) [reply planner/core/find_best_task.go:2380]: No, `BatchPointGet` will get the pid info in `BatchPointGetPlan.Init()`

File: planner/core/find_best_task.go [hunk 4]
```diff
@@ -2377,6 +2375,22 @@ func (ds *DataSource) convertToPointGet(prop *property.PhysicalProperty, candida
...
+		if err != nil {
+			return invalidTask
+		}
+		if len(idxs) == 1 && idxs[0] == FullRange {
+			if len(pi.Definitions) != 1 {
+				return invalidTask
+			}
+			partitionInfo = &pi.Definitions[0]
```
Comment (Defined2014) [inline planner/core/find_best_task.go:2388]: I'm sure it already covered by https://github.com/pingcap/tidb/pull/45472/files#diff-4c4a5d9c358008fc0d3e898b87a14692668d4b60d949b2796d8b6ebc2b890720R236

Seems it has some problems.
