### PR TITLE
expression: refine date_add/sub return type and precision

### LINKED ISSUE #9813: date_add/date_sub can return `mysql.Time`.
## Bug Report

Although in MySQL's docs:
```
The return value depends on the arguments:

DATE if the date argument is a DATE value and your calculations involve only YEAR, MONTH, and DAY parts (that is, no time parts).

DATETIME if the first argument is a DATETIME (or TIMESTAMP) value, or if the first argument is a DATE and the unit value uses HOURS, MINUTES, or SECONDS.

String otherwise.
```

But in its actual implementation:
```
bool Item_date_add_interval::resolve_type(THD *) {
  maybe_null = true;

  /*
    The field type for the result of an Item_date function is defined as
    follows:

    - If first arg is a MYSQL_TYPE_DATETIME result is MYSQL_TYPE_DATETIME
    - If first arg is a MYSQL_TYPE_DATE and the interval type uses hours,
      minutes or seconds then type is MYSQL_TYPE_DATETIME.
    - Otherwise the result is MYSQL_TYPE_STRING
      (This is because you can't know if the string contains a DATE, MYSQL_TIME
    or DATETIME argument)
  */
  enum_field_types arg0_data_type = args[0]->data_type();
  uint8 interval_dec = 0;
  if (int_type == INTERVAL_MICROSECOND ||
      (int_type >= INTERVAL_DAY_MICROSECOND &&
       int_type <= INTERVAL_SECOND_MICROSECOND))
    interval_dec = DATETIME_MAX_DECIMALS;
  else if (int_type == INTERVAL_SECOND && args[1]->decimals > 0)
    interval_dec = MY_MIN(args[1]->decimals, DATETIME_MAX_DECIMALS);

  if (arg0_data_type == MYSQL_TYPE_DATETIME ||
      arg0_data_type == MYSQL_TYPE_TIMESTAMP) {
    uint8 dec = MY_MAX(args[0]->datetime_precision(), interval_dec);
    set_data_type_datetime(dec);
  } else if (arg0_data_type == MYSQL_TYPE_DATE) {
    if (int_type <= INTERVAL_DAY || int_type == INTERVAL_YEAR_MONTH)
      set_data_type_date();
    else
      set_data_type_datetime(interval_dec);
  } else if (arg0_data_type == MYSQL_TYPE_TIME) {
    uint8 dec = MY_MAX(args[0]->time_precision(), interval_dec);
    set_data_type_time(dec);
  } else {
    /* Behave as a usual string function when return type is VARCHAR. */
    set_data_type_char(MAX_DATETIME_FULL_WIDTH, default_charset());
  }
  if (value.alloc(max_length)) return true;

  return false;
}
```
The return type can also be `Time`, which is `Duration` in TiDB.

So currently if the arg[0] is `Duration` we'll get the result with the year, month and day field. Which is not a reasonable return value.
We need to cover this unexpected case.

### LINKED ISSUE #31799: `DATE_ADD` function into VARCHAR column returns inconsistent results in fractional portion
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step 
```sql
SET @@time_zone='+00:00';
SET @@timestamp=1000000000;
DROP TABLE IF EXISTS t1; 
CREATE TABLE t1 (a VARCHAR(32));
INSERT INTO t1 VALUES(DATE_ADD(CAST('2001-01-01 00:00:00' AS DATETIME), INTERVAL 1 SECOND));
INSERT INTO t1 VALUES(DATE_ADD(CAST('2001-01-01 00:00:00' AS DATETIME(6)), INTERVAL 1 SECOND));
INSERT INTO t1 VALUES(DATE_ADD(CAST('2001-01-01 00:00:00' AS DATETIME), INTERVAL 1.1 SECOND));
INSERT INTO t1 VALUES(DATE_ADD(CAST('2001-01-01 00:00:00' AS DATETIME(6)), INTERVAL 1.1 SECOND));
INSERT INTO t1 VALUES(DATE_ADD(CAST('00:00:00' AS TIME), INTERVAL 1.1 SECOND));
SELECT * FROM t1;
DROP TABLE t1;
SET @@timestamp=default;
SET @@time_zone=default;
```

### 2. What did you expect to see?
```sql
mysql> SELECT * FROM t1;
+----------------------------+
| a                          |
+----------------------------+
| 2001-01-01 00:00:01        |
| 2001-01-01 00:00:01.000000 |
| 2001-01-01 00:00:01.1      |
| 2001-01-01 00:00:01.100000 |
| 00:00:01.1                 |
+----------------------------+
```
### 3. What did you see instead 
```sql
tidb> SELECT * FROM t1;
+----------------------------+
| a                          |
+----------------------------+
| 2001-01-01 00:00:01        |
| 2001-01-01 00:00:01        |
| 2001-01-01 00:00:01.100000 |
| 2001-01-01 00:00:01.100000 |
| 00:00:01                   |
+----------------------------+
```

### 4. What is your TiDB version? 
```
tidb_version(): Release Version: v5.5.0-alpha-105-gaabd4e04d
Edition: Community
Git Commit Hash: aabd4e04d994eb91663abaa80865daec4cf970a6
Git Branch: master
UTC Build Time: 2022-01-13 05:36:36
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by zanmato1984**
### What problem does this PR solve?

Issue Number: close #31799, close #9813. And part of #31867 will be resolved by this PR.

Problem Summary:

There exists several issues about function `date_add` and `date_sub`:
1. Return types of several signatures don't match MySQL's [(doc)](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add):
    1. `date_add/sub(int/double/decimal, interval)`: MySQL returns string, TiDB returns datetime.
    2. `date_add/sub(duration, interval)` when interval unit contains YMD part (except for DAY_MICROSECOND - I believe it's a mismatch between MySQL's actual behavior and its document, but it doesn't matter much), MySQL returns datetime with current date padded, TiDB returns time.
    3. Precision of the return type doesn't match MySQL's in many cases. Note that here I mean the precision concluded by type inference - MySQL client option `--column-type-info` is your good friend.
2. Runtime doesn't respect the precision inferred in compile time. For a datetime value, we check if the MS part is zero then adjust the precision to 0 (min fsp) or 6 (max fsp). No respect to compile time type at all.

Honestly I can file 10+ bugs easily about the above issues.

### What is changed and how it works?

Don't get scared of this huge PR - 90% are tests and 80% of which are generated, the core is quite simple. This PR includes the following changes:
1. The core change is in `expression/builtin_time.go`:
    1. Refine the type inference about the return type and precision of `date_add` and `date_sub`.
    2. Refine the evaluation so that the type and precision by type inference is respected.
    3. Add necessary signatures - ideally we should be able to leverage implicit cast to get a datetime value from int/double/decimal/string, however, as described in this [comment](https://github.com/pingcap/tidb/pull/35009/files#diff-084c9cef9b34d2f1b64570e2cf7d4010b7ce5b26170c480cde3a47441eaa1549R3498), to comply with MySQL's weird behaviors we need specialized overload for each of int/double/decimal/string.
    4. Abstract things like "add or sub", "how to evaluate the datetime value", and "how to evaluate the interval value". Use some simple composition to eliminate the mostly-copy-paste individual overloads. And the overall LOC is reduced from 1456 to 591.
 2. The vectorized versions are simple enough to not use generator, thus moved from generator (expression/generator/time_vec.go) to regular implementations (expression/builtin_time_vec.go). I would have to write more code in template than just directly write them in go. However the vectorized tests are enhanced by adding more cases.
 3. Tests:
     1. Add thorough type infer test cases.
     2. Update several existing UT and integration test cases that already mismatch MySQL's result - each of them is a bug-to-be-reported.
     3. Add more cases to existing UT and integration test.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that the return type and precision of function `date_add` and `date_sub` does not match that of MySQL.
```

### CODE REVIEW

**Review by mjonss — COMMENTED** [review]
Would it be possible to generate the test files during build/test phase, instead of having both the generator and the generated code in the repository?
That would save both space in the checked out repository as well as ease the burden of the reviewer :)

**Comment by zanmato1984** [comment]
> Would it be possible to generate the test files during build/test phase, instead of having both the generator and the generated code in the repository? That would save both space in the checked out repository as well as ease the burden of the reviewer :)

That sounds about right. But this process change involves adjusting our CI/CD flow, I'm not sure if we should do that in this innocent PR.

How about we focus on the template change and just ignore the generated tests, for this specific PR's review?

**Review by mjonss — COMMENTED** [review]
First batch of review (only for the test generation so far).

File: expression/builtin_time.go [hunk 1]
```diff
@@ -2977,15 +2999,17 @@ func (du *baseDateArithmetical) subDuration(ctx sessionctx.Context, d types.Dura
 	if err != nil {
 		return types.ZeroDuration, true, err
 	}
+	// Adjust fsp as required by outer - always respect type inference.
+	retDur.Fsp = resultFsp
 	return retDur, false, nil
```
Comment (mjonss) [inline expression/builtin_time.go:3004]: Maybe replace this function body with:
`return addDuration(ctx, Neg(d), interval, unit, resultFsp)`?

File: expression/builtin_time.go [hunk 2]
```diff
@@ -3030,6 +3054,90 @@ func (du *baseDateArithmetical) vecGetDateFromInt(b *baseBuiltinFunc, input *chu
...
+	defer b.bufAllocator.put(buf)
+	if err := b.args[0].VecEvalReal(b.ctx, input, buf); err != nil {
+		return err
+	}
+
+	result.ResizeTime(n, false)
+	result.MergeNulls(buf)
+	dates := result.Times()
+	f64s := buf.Float64s()
+	sc := b.ctx.GetSessionVars().StmtCtx
```
Comment (mjonss) [inline expression/builtin_time.go:3072]: Same as above, Session context should not be needed in ParseTimeFromFloat64.

File: expression/builtin_time.go [hunk 3]
```diff
@@ -3030,6 +3054,90 @@ func (du *baseDateArithmetical) vecGetDateFromInt(b *baseBuiltinFunc, input *chu
...
+			err = handleInvalidTimeError(b.ctx, err)
+			if err != nil {
+				return err
+			}
+			result.SetNull(i, true)
+			continue
+		}
+
+		dateTp := mysql.TypeDate
+		if date.Type() == mysql.TypeDatetime || date.Type() == mysql.TypeTimestamp || isClockUnit {
```
Comment (mjonss) [inline expression/builtin_time.go:3090]: Can it ever be TypeTimestamp?

File: expression/builtin_time.go [hunk 4]
```diff
@@ -3030,6 +3054,90 @@ func (du *baseDateArithmetical) vecGetDateFromInt(b *baseBuiltinFunc, input *chu
...
+	}
+	defer b.bufAllocator.put(buf)
+	if err := b.args[0].VecEvalDecimal(b.ctx, input, buf); err != nil {
+		return err
+	}
+
+	result.ResizeTime(n, false)
+	result.MergeNulls(buf)
+	dates := result.Times()
+	sc := b.ctx.GetSessionVars().StmtCtx
```
Comment (mjonss) [inline expression/builtin_time.go:3113]: Same as above with Session Context not needed.

File: expression/builtin_time.go [hunk 5]
```diff
@@ -3030,6 +3054,90 @@ func (du *baseDateArithmetical) vecGetDateFromInt(b *baseBuiltinFunc, input *chu
...
+			err = handleInvalidTimeError(b.ctx, err)
+			if err != nil {
+				return err
+			}
+			result.SetNull(i, true)
+			continue
+		}
+
+		dateTp := mysql.TypeDate
+		if date.Type() == mysql.TypeDatetime || date.Type() == mysql.TypeTimestamp || isClockUnit {
```
Comment (mjonss) [inline expression/builtin_time.go:3132]: Same as above, Timestamp should never happen here.

File: expression/builtin_time.go [hunk 6]
```diff
@@ -3088,7 +3196,7 @@ func (du *baseDateArithmetical) vecGetDateFromDatetime(b *baseBuiltinFunc, input
 			continue
 		}
 
-		if isClockUnit {
+		if isClockUnit || dates[i].Type() == mysql.TypeTimestamp {
```
Comment (mjonss) [inline expression/builtin_time.go:3199]: Can Timestamp really be possible when returned from Datetime?

File: expression/builtin_time.go [hunk 7]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
 	return nil
 }
 
-type addDateFunctionClass struct {
+type funcTimeOpForDateAddSub func(da *baseDateArithmetical, ctx sessionctx.Context, date types.Time, interval string, unit string, resultFsp int) (types.Time, bool, error)
```
Comment (mjonss) [inline expression/builtin_time.go:3391]:
```suggestion
type funcTimeOpForDateAddSub func(da *baseDateArithmetical, ctx sessionctx.Context, date types.Time, interval, unit string, resultFsp int) (types.Time, bool, error)
```

File: expression/builtin_time.go [hunk 8]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+
+func addTime(da *baseDateArithmetical, ctx sessionctx.Context, date types.Time, interval string, unit string, resultFsp int) (types.Time, bool, error) {
```
Comment (mjonss) [inline expression/builtin_time.go:3393]:
```suggestion
func addTime(da *baseDateArithmetical, ctx sessionctx.Context, date types.Time, interval, unit string, resultFsp int) (types.Time, bool, error) {
```

File: expression/builtin_time.go [hunk 9]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+	return da.add(ctx, date, interval, unit, resultFsp)
+}
+
+func subTime(da *baseDateArithmetical, ctx sessionctx.Context, date types.Time, interval string, unit string, resultFsp int) (types.Time, bool, error) {
```
Comment (mjonss) [inline expression/builtin_time.go:3397]:
```suggestion
func subTime(da *baseDateArithmetical, ctx sessionctx.Context, date types.Time, interval, unit string, resultFsp int) (types.Time, bool, error) {
```

File: expression/builtin_time.go [hunk 10]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+	return da.sub(ctx, date, interval, unit, resultFsp)
+}
+
+type funcDurationOpForDateAddSub func(da *baseDateArithmetical, ctx sessionctx.Context, d types.Duration, interval string, unit string, resultFsp int) (types.Duration, bool, error)
```
Comment (mjonss) [inline expression/builtin_time.go:3401]:
```suggestion
type funcDurationOpForDateAddSub func(da *baseDateArithmetical, ctx sessionctx.Context, d types.Duration, interval, unit string, resultFsp int) (types.Duration, bool, error)
```

File: expression/builtin_time.go [hunk 11]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+
+func addDuration(da *baseDateArithmetical, ctx sessionctx.Context, d types.Duration, interval string, unit string, resultFsp int) (types.Duration, bool, error) {
```
Comment (mjonss) [inline expression/builtin_time.go:3403]:
```suggestion
func addDuration(da *baseDateArithmetical, ctx sessionctx.Context, d types.Duration, interval, unit string, resultFsp int) (types.Duration, bool, error) {
```

File: expression/builtin_time.go [hunk 12]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+	return da.addDuration(ctx, d, interval, unit, resultFsp)
+}
+
+func subDuration(da *baseDateArithmetical, ctx sessionctx.Context, d types.Duration, interval string, unit string, resultFsp int) (types.Duration, bool, error) {
```
Comment (mjonss) [inline expression/builtin_time.go:3407]:
```suggestion
func subDuration(da *baseDateArithmetical, ctx sessionctx.Context, d types.Duration, interval, unit string, resultFsp int) (types.Duration, bool, error) {
```

File: expression/builtin_time.go [hunk 13]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+	return da.subDuration(ctx, d, interval, unit, resultFsp)
+}
+
+type funcSetPbCodeOp func(b builtinFunc, add tipb.ScalarFuncSig, sub tipb.ScalarFuncSig)
```
Comment (mjonss) [inline expression/builtin_time.go:3411]:
```suggestion
type funcSetPbCodeOp func(b builtinFunc, add, sub tipb.ScalarFuncSig)
```

File: expression/builtin_time.go [hunk 14]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+
+func setAdd(b builtinFunc, add tipb.ScalarFuncSig, sub tipb.ScalarFuncSig) {
```
Comment (mjonss) [inline expression/builtin_time.go:3413]:
```suggestion
func setAdd(b builtinFunc, add, sub tipb.ScalarFuncSig) {
```

File: expression/builtin_time.go [hunk 15]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+	b.setPbCode(add)
+}
+
+func setSub(b builtinFunc, add tipb.ScalarFuncSig, sub tipb.ScalarFuncSig) {
```
Comment (mjonss) [inline expression/builtin_time.go:3417]:
```suggestion
func setSub(b builtinFunc, add, sub tipb.ScalarFuncSig) {
```

File: expression/builtin_time.go [hunk 16]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+	b.setPbCode(sub)
+}
+
+type funcGetDateForDateAddSub func(da *baseDateArithmetical, ctx sessionctx.Context, args []Expression, row chunk.Row, unit string) (types.Time, bool, error)
+
+func getDateFromString(da *baseDateArithmetical, ctx sessionctx.Context, args []Expression, row chunk.Row, unit string) (types.Time, bool, error) {
+	return da.getDateFromString(ctx, args, row, unit)
+}
```
Comment (mjonss) [inline expression/builtin_time.go:3425]: Are there other implementations of all these getDate[time]From{String,Int,Real,Decimal} etc. in other places of the repository that can be combined with these new ones?

File: expression/builtin_time.go [hunk 17]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
 	dateEvalTp := args[0].GetType().EvalType()
-	if dateEvalTp != types.ETString && dateEvalTp != types.ETInt && dateEvalTp != types.ETDuration {
+	// Some special evaluation type treatment.
+	// Note that it could be more elegant if we always evaluate datetime for int, real, decimal and string, by leveraging existing implicit casts.
+	// However, MySQL has a weird behavior for date_add(string, ...), whose result depends on the content of the first argument.
+	// E.g., date_add('2000-01-02 00:00:00', interval 1 day) evaluates to '2021-01-03 00:00:00' (which is normal),
+	// whereas date_add('2000-01-02', interval 1 day) evaluates to '2000-01-03' instead of '2021-01-03 00:00:00'.
+	// This requires a customized parsing of the content of the first argument, by recognizing if it is a pure date format or contains HMS part.
+	// So implicit casts are not viable here.
+	if dateEvalTp == types.ETTimestamp {
```
Comment (mjonss) [inline expression/builtin_time.go:3513]: Are there any tests with Timestamps using different time zones (including Daylight Saving Time)?
If not I would suggest having something for Europe/Amsterdam like
timestamp column = '2022-03-27 01:30:00' (CET / GMT+1)
DATE_ADD(ts_col, INTERVAL 1 HOUR) => '2022-03-27 02:30:00' Datetime (non-existing CE(S)T timestamp)
timestamp column = '2022-10-30 02:30:00' (CEST / GMT+2)
DATE_ADD(ts_col, INTERVAL 1 HOUR) => '2022-10-30 03:30:00' Datetime (Two hours later if interpreted as CET timestamp, GMT+1)
timestamp column = '2022-10-30 02:30:00' (CET / GMT+1)
DATE_ADD(ts_col, INTERVAL 1 HOUR) => '2022-10-30 03:30:00' Datetime

File: expression/builtin_time.go [hunk 18]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
-			tp := types.NewFieldType(mysql.TypeDatetime)
-			tp.SetDecimal(args[0].GetType().GetDecimal())
-			tp.SetFlen(mysql.MaxDatetimeWidthNoFsp)
-			if tp.GetDecimal() > 0 {
-				tp.SetFlen(tp.GetFlen() + 1 + tp.GetDecimal())
-			}
-			args[0] = BuildCastFunction(ctx, args[0], tp)
+	resultTp := mysql.TypeVarString
+	resultEvalTp := types.ETString
+	if args[0].GetType().GetType() == mysql.TypeDate {
```
Comment (mjonss) [inline expression/builtin_time.go:3533]:
```suggestion
	if dateEvalTp == mysql.TypeDate {
```

File: expression/builtin_time.go [hunk 19]
```diff
@@ -3280,1581 +3388,616 @@ func (du *baseDateArithmetical) vecGetIntervalFromReal(b *baseBuiltinFunc, input
...
+	interval, isNull, err := b.getInterval(&b.baseDateArithmetical, b.ctx, b.args, row, unit)
 	if isNull || err != nil {
-		return types.ZeroTime, true, err
+		return types.ZeroTime.String(), true, err
 	}
 
-	result, isNull, err := b.add(b.ctx, date, interval, unit)
-	return result, isNull || err != nil, err
+	result, isNull, err := b.timeOp(&b.baseDateArithmetical, b.ctx, date, interval, unit, b.tp.GetDecimal())
+	if result.Microsecond() == 0 {
```
Comment (mjonss) [inline expression/builtin_time.go:3890]: Should it not check actual fsp, what if the result just happens to have a fsp > 0 but evaluates to 0?

File: expression/builtin_time_vec.go [hunk 20]
```diff
@@ -2798,3 +2798,217 @@ func (b *builtinDayOfMonthSig) vecEvalInt(input *chunk.Chunk, result *chunk.Colu
...
+			continue
+		}
+		resDate, isNull, err := b.timeOp(&b.baseDateArithmetical, b.ctx, dateBuf.Times()[i], intervalBuf.GetString(i), unit, b.tp.GetDecimal())
+		if err != nil {
+			return err
+		}
+		if isNull {
+			result.AppendNull()
+		} else {
+			if resDate.Microsecond() == 0 {
```
Comment (mjonss) [inline expression/builtin_time_vec.go:2847]: Is it possible to check actual fsp instead of the value here?

File: expression/integration_test.go [hunk 21]
```diff
@@ -7318,6 +7319,63 @@ func TestIssue34659(t *testing.T) {
...
+	tk.MustExec("insert into t values(1, date_add(cast('2001-01-01 00:00:00' as datetime), interval 1 second))")
+	tk.MustExec("insert into t values(2, date_add(cast('2001-01-01 00:00:00' as datetime(6)), interval 1 second))")
+	tk.MustExec("insert into t values(3, date_add(cast('2001-01-01 00:00:00' as datetime), interval 1.1 second))")
+	tk.MustExec("insert into t values(4, date_add(cast('2001-01-01 00:00:00' as datetime(6)), interval 1.1 second))")
+	tk.MustExec("insert into t values(5, date_add(cast('00:00:00' as time), interval 1.1 second))")
+	tk.MustQuery("select c from t order by i").Check([][]interface{}{{"2001-01-01 00:00:01"}, {"2001-01-01 00:00:01.000000"}, {"2001-01-01 00:00:01.1"}, {"2001-01-01 00:00:01.100000"}, {"00:00:01.1"}})
+	tk.MustExec("drop table t")
+}
+
+func TestIssue31876(t *testing.T) {
```
Comment (mjonss) [inline expression/integration_test.go:7339]: 31876 is a PR?!
```suggestion
func TestIssue31867(t *testing.T) {
```
Please also add close #31867 in the description :)

**Review by mjonss — COMMENTED** [review]
Review part 3

File: types/time_test.go [hunk 22]
```diff
@@ -1727,6 +1786,94 @@ func TestParseTimeFromInt64(t *testing.T) {
...
+	cases := []struct {
+		f   float64
+		t   byte // type: date or datetime.
+		Y   int
+		M   int
+		D   int
+		h   int
+		m   int
+		s   int
+		ms  int
```
Comment (mjonss) [inline types/time_test.go:1802]: `ms` means normally milliseconds (1/1000 second) while microseconds (1/1000000) is normally `us`.
```suggestion
		us  int
```

File: types/time_test.go [hunk 23]
```diff
@@ -1727,6 +1786,94 @@ func TestParseTimeFromInt64(t *testing.T) {
...
+	for _, c := range cases {
+		res, err := types.ParseTimeFromFloat64(sc, c.f)
+		require.Equalf(t, c.t, res.Type(), "Type mismatch for case %v", c)
+		require.Equalf(t, c.Y, res.Year(), "Year mismatch for case %v", c)
+		require.Equalf(t, c.M, res.Month(), "Month mismatch for case %v", c)
+		require.Equalf(t, c.D, res.Day(), "Day mismatch for case %v", c)
+		require.Equalf(t, c.h, res.Hour(), "Hour mismatch for case %v", c)
+		require.Equalf(t, c.m, res.Minute(), "Minute mismatch for case %v", c)
+		require.Equalf(t, c.s, res.Second(), "Second mismatch for case %v", c)
+		require.Equalf(t, c.ms, res.Microsecond(), "Microsecond mismatch for case %v", c)
```
Comment (mjonss) [inline types/time_test.go:1824]:
```suggestion
		require.Equalf(t, c.us, res.Microsecond(), "Microsecond mismatch for case %v", c)
```

File: types/time_test.go [hunk 24]
```diff
@@ -1727,6 +1786,94 @@ func TestParseTimeFromInt64(t *testing.T) {
...
+	cases := []struct {
+		d   *types.MyDecimal
+		t   byte // type: date or datetime.
+		Y   int
+		M   int
+		D   int
+		h   int
+		m   int
+		s   int
+		ms  int
```
Comment (mjonss) [inline types/time_test.go:1846]:
```suggestion
		us  int
```

File: types/time_test.go [hunk 25]
```diff
@@ -1727,6 +1786,94 @@ func TestParseTimeFromInt64(t *testing.T) {
...
+	for _, c := range cases {
+		res, err := types.ParseTimeFromDecimal(sc, c.d)
+		require.Equalf(t, c.t, res.Type(), "Type mismatch for case %v", c)
+		require.Equalf(t, c.Y, res.Year(), "Year mismatch for case %v", c)
+		require.Equalf(t, c.M, res.Month(), "Month mismatch for case %v", c)
+		require.Equalf(t, c.D, res.Day(), "Day mismatch for case %v", c)
+		require.Equalf(t, c.h, res.Hour(), "Hour mismatch for case %v", c)
+		require.Equalf(t, c.m, res.Minute(), "Minute mismatch for case %v", c)
+		require.Equalf(t, c.s, res.Second(), "Second mismatch for case %v", c)
+		require.Equalf(t, c.ms, res.Microsecond(), "Microsecond mismatch for case %v", c)
```
Comment (mjonss) [inline types/time_test.go:1868]:
```suggestion
		require.Equalf(t, c.us, res.Microsecond(), "Microsecond mismatch for case %v", c)
```

**Review by mjonss — COMMENTED** [review]
Last part of review. Great job! I will wait for some answers/reaction before approving :)

**Comment by zanmato1984** [comment]
> Last part of review. Great job! I will wait for some answers/reaction before approving :)

Thanks for the great review! I'm working on your comments. Will be back soon.

File: expression/bench_test.go [hunk 26]
```diff
@@ -715,6 +716,20 @@ func (g *randHexStrGener) gen() interface{} {
...
 
+// dateGener is used to generate a date
+type dateGener struct {
+	randGen *defaultRandGen
+}
+
+func (g dateGener) gen() interface{} {
+	year := 1970 + g.randGen.Intn(100)
+	month := g.randGen.Intn(10) + 1
+	day := g.randGen.Intn(20) + 1
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:727]: Ditto. A copy-paste work.

File: expression/bench_test.go [hunk 27]
```diff
@@ -763,14 +780,17 @@ func (g *dateTimeStrGener) gen() interface{} {
 	if g.Day == 0 {
 		g.Day = g.randGen.Intn(20) + 1
 	}
+	if g.Fsp == -1 {
+		g.Fsp = g.randGen.Intn(10)
+	}
 	hour := g.randGen.Intn(12)
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:786]: Sorry I really don't :(

File: expression/bench_test.go [hunk 28]
```diff
@@ -820,24 +855,184 @@ func (g *timeStrGener) gen() interface{} {
...
+	num, err := t.ToNumber().ToFloat64()
+	if err != nil {
+		panic(err)
+	}
+
+	if g.randGen.Float64() >= g.fspRatio {
+		return num
+	}
+
+	num += g.randGen.Float64()
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:919]: This is not actually a date. It's rather a floating point value that can be recognized by functions like `date_add/sub` as a valid date representation - and the fractional part will be discarded but still is considered valid.

From MySQL:
```
select date_add(cast(20000102.9876 as double), interval 1 second);
+------------------------------------------------------------+
| date_add(cast(20000102.9876 as double), interval 1 second) |
+------------------------------------------------------------+
| 2000-01-02 00:00:01                                        |
+------------------------------------------------------------+
```

This is what this generator is for.

File: expression/bench_test.go [hunk 29]
```diff
@@ -820,24 +855,172 @@ func (g *timeStrGener) gen() interface{} {
...
+	t := g.dateGener.gen().(types.Time)
+	intPart := t.ToNumber()
+
+	if g.randGen.Float64() >= g.fspRatio {
+		return intPart
+	}
+
+	fracPart := new(types.MyDecimal)
+	// Make fractional part no larger than 9 digits.
+	frac := float64(int64(g.randGen.Float64()*1000000000)) / float64(1000000000)
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:979]: Your are right. This is method is problematic. I'm working on a new one.

File: expression/bench_test.go [hunk 30]
```diff
@@ -820,24 +855,184 @@ func (g *timeStrGener) gen() interface{} {
...
+	err := fracPart.FromFloat64(frac)
+	if err != nil {
+		panic(err)
+	}
+	res := new(types.MyDecimal)
+	err = types.DecimalAdd(intPart, fracPart, res)
+	if err != nil {
+		panic(err)
+	}
+	return res
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:989]: Ditto as in `dateRealGener`.

File: expression/builtin_time.go [hunk 31]
```diff
@@ -2811,13 +2782,65 @@ func (du *baseDateArithmetical) getDateFromInt(ctx sessionctx.Context, args []Ex
...
+	}
+
+	// Now the actual date.Type() might be date, datetime or timestamp.
+	// Date and datetime is treated as is.
+	// Timestamp is treated as datetime.
+	// When the unit contains clock, the date part is treated as datetime even though it might be actually a date.
+	dateTp := mysql.TypeDate
+	if date.Type() == mysql.TypeDatetime || date.Type() == mysql.TypeTimestamp || types.IsClockUnit(unit) {
+		dateTp = mysql.TypeDatetime
+	}
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go:2804]: Your are right. Timestamp is not possible here. I wrongly treated `getDateFromReal/Decimal` the same as `getDateFromDatetime` to which timestamp is able to make its way.

File: expression/builtin_time.go [hunk 32]
```diff
@@ -2811,13 +2782,65 @@ func (du *baseDateArithmetical) getDateFromInt(ctx sessionctx.Context, args []Ex
...
 }
 
+func (du *baseDateArithmetical) getDateFromReal(ctx sessionctx.Context, args []Expression, row chunk.Row, unit string) (types.Time, bool, error) {
+	dateReal, isNull, err := args[0].EvalReal(ctx, row)
+	if isNull || err != nil {
+		return types.ZeroTime, true, err
+	}
+
+	sc := ctx.GetSessionVars().StmtCtx
+	date, err := types.ParseTimeFromFloat64(sc, dateReal)
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go:2792]: I'll see if I can get rid of `sc`.

File: expression/builtin_time.go [hunk 33]
```diff
@@ -2811,13 +2782,65 @@ func (du *baseDateArithmetical) getDateFromInt(ctx sessionctx.Context, args []Ex
...
+
+	// Now the actual date.Type() might be date, datetime or timestamp.
+	// Date and datetime is treated as is.
+	// Timestamp is treated as datetime.
+	// When the unit contains clock, the date part is treated as datetime even though it might be actually a date.
+	dateTp := mysql.TypeDate
+	if date.Type() == mysql.TypeDatetime || date.Type() == mysql.TypeTimestamp || types.IsClockUnit(unit) {
+		dateTp = mysql.TypeDatetime
+	}
+	date.SetType(dateTp)
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go:2829]: Both correct. Will do.

File: expression/builtin_time.go [hunk 34]
```diff
@@ -2811,13 +2782,65 @@ func (du *baseDateArithmetical) getDateFromInt(ctx sessionctx.Context, args []Ex
...
 func (du *baseDateArithmetical) getDateFromDatetime(ctx sessionctx.Context, args []Expression, row chunk.Row, unit string) (types.Time, bool, error) {
 	date, isNull, err := args[0].EvalTime(ctx, row)
 	if isNull || err != nil {
 		return types.ZeroTime, true, err
 	}
 
-	if types.IsClockUnit(unit) {
+	// Now the actual date.Type() might be date, datetime or timestamp.
+	// Date and datetime is treated as is.
+	// Timestamp is treated as datetime.
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go:2841]: Yeah, will do.

File: expression/builtin_time.go (hunk 1 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3004]: Nice catch. Will do.

File: expression/builtin_time.go (hunk 2 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3072]: Ditto. Will do.

File: expression/builtin_time.go (hunk 3 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3090]: Ditto. Will remove it.

File: expression/builtin_time.go (hunk 4 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3113]: Will do.

File: expression/builtin_time.go (hunk 16 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3425]: I did have the same concern as yours and did some searching. Didn't see other usage of `baseDateArithmetical` other than `date_add/sub`.

File: expression/builtin_time.go (hunk 17 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3513]: I'll do some experiments and come to this topic later.

File: expression/builtin_time.go (hunk 18 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3533]: I'm afraid this is not valid. There are two type systems in TiDB: "eval type" and "MySQL type". They are for different purpose and not supposed to be mix-used.

Eval type is more like "how data is represented during evaluation", for example, all integer columns, enum columns, and set columns have `ETInt`, and both date and datetime columns have `ETDatetime`.

The examples above reveal exactly the tricks in type inference:
1. Sometimes it is handy to just infer types from eval type - "if this argument has ETInt, no matter it is smallint, bigint, or even enum, the overload is resolved to be this one".
2. Sometimes a function may have a fine-grained type inference rule - "if this argument is date type, the return type is date. If the first argument is datetime type, the return type is datetime". Now the eval type is insufficient. We need to fall back to consulting the mysql type, which is the type specified in the create table statement. And this is what this line does.

File: expression/builtin_time.go (hunk 19 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3890]: Bingo! This is the subtle part! I believe this is what MySQL does. From MySQL:
```
select date_add('2000-01-02 00:00:00.5', interval 500000 microsecond);
+----------------------------------------------------------------+
| date_add('2000-01-02 00:00:00.5', interval 500000 microsecond) |
+----------------------------------------------------------------+
| 2000-01-02 00:00:01                                            |
+----------------------------------------------------------------+
```

But yeah, you reminded me that I should've added this test case, even just for fun. I did this kind of tests several times when studying the essence behind all the MySQL madness. Sadly I forgot to add them into code.

File: expression/builtin_time_vec.go (hunk 20 above)
Comment (zanmato1984) [reply expression/builtin_time_vec.go:2847]: Ditto as explained in non-vec function.

File: expression/typeinfer_test.go [hunk 35]
```diff
@@ -1926,17 +1927,990 @@ func (s *InferTypeSuite) createTestCase4TimeFuncs() []typeInferTestCase {
...
+		{"date_add(c_timestamp_d, interval c_decimal year)", mysql.TypeDatetime, charset.CharsetBin, mysql.BinaryFlag, mysql.MaxDatetimeWidthNoFsp, types.MinFsp},
+
+		// Rest + *.
+		{"date_add(c_bit, interval c_char microsecond)", mysql.TypeVarString, charset.CharsetUTF8MB4, 0, mysql.MaxDatetimeFullWidth, types.MinFsp},
+		{"date_add(c_int_d, interval c_varchar second)", mysql.TypeVarString, charset.CharsetUTF8MB4, 0, mysql.MaxDatetimeFullWidth, types.MinFsp},
+		{"date_add(c_double_d, interval c_int_d day_microsecond)", mysql.TypeVarString, charset.CharsetUTF8MB4, 0, mysql.MaxDatetimeFullWidth, types.MinFsp},
+		{"date_add(c_decimal, interval c_bigint_d hour)", mysql.TypeVarString, charset.CharsetUTF8MB4, 0, mysql.MaxDatetimeFullWidth, types.MinFsp},
+		{"date_add(c_varchar, interval c_double_d day)", mysql.TypeVarString, charset.CharsetUTF8MB4, 0, mysql.MaxDatetimeFullWidth, types.MinFsp},
+		{"date_add(c_binary, interval c_decimal year)", mysql.TypeVarString, charset.CharsetUTF8MB4, 0, mysql.MaxDatetimeFullWidth, types.MinFsp},
 	}
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/typeinfer_test.go:2914]: I'm afraid not. This is just for type inference during compilation and regards no runtime evaluation.

File: testkit/result.go [hunk 36]
```diff
@@ -49,6 +49,16 @@ func (res *Result) Check(expected [][]interface{}) {
 	res.require.Equal(needBuff.String(), resBuff.String(), res.comment)
 }
 
+// CustCheck asserts the result match the expected results in the way `check` function specifies.
+func (res *Result) CustCheck(expected [][]interface{}, check func([]string, []interface{}) bool) {
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply testkit/result.go:53]: Sure, more explicit. Will do.

File: types/time_test.go (hunk 22 above)
Comment (zanmato1984) [reply types/time_test.go:1802]: Right. I kept reminding myself the difference between ms and us all the time. And yet I made this mistake.

There are other mis-uses of "ms", I will fix them as well.

File: expression/bench_test.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go]: Addressed.

File: expression/builtin_time.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go:2792]: Very thoughtful! Doing it now.

[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: expression/builtin_time.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: expression/builtin_time.go (hunk 33 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go]: Both addressed.

File: expression/builtin_time.go (hunk 34 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: expression/builtin_time.go (hunk 2 above)
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: expression/builtin_time.go (hunk 1 above)
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: expression/builtin_time.go (hunk 3 above)
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: expression/builtin_time.go (hunk 4 above)
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: expression/builtin_time.go (hunk 5 above)
Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed.

File: types/time.go [hunk 37]
```diff
@@ -2577,6 +2602,68 @@ func ParseTimeFromInt64(sc *stmtctx.StatementContext, num int64) (Time, error) {
 	return parseDateTimeFromNum(sc, num)
 }
 
+// ParseTimeFromFloat64 parses mysql time value from float64.
+// It is used in scenarios that distinguish date and datetime, e.g., date_add/sub() with first argument being real.
+// For example, 20010203 parses to date (no HMS) and 20010203040506 parses to datetime (with HMS).
+func ParseTimeFromFloat64(sc *stmtctx.StatementContext, f float64) (Time, error) {
+	intPart := int64(f)
+	t, err := parseDateTimeFromNum(sc, intPart)
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply types/time.go]: Sorry I did it this myself just to make sure all changes compile well. It's already committed.

File: types/time.go [hunk 38]
```diff
@@ -2577,6 +2602,68 @@ func ParseTimeFromInt64(sc *stmtctx.StatementContext, num int64) (Time, error) {
...
+		ct.setMicrosecond(fracPart)
+		t.SetCoreTime(ct)
+	}
+	return t, err
+}
+
+// ParseTimeFromDecimal parses mysql time value from decimal.
+// It is used in scenarios that distinguish date and datetime, e.g., date_add/sub() with first argument being decimal.
+// For example, 20010203 parses to date (no HMS) and 20010203040506 parses to datetime (with HMS).
+func ParseTimeFromDecimal(sc *stmtctx.StatementContext, dec *MyDecimal) (t Time, err error) {
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply types/time.go]: Ditto.

File: types/time.go [hunk 39]
```diff
@@ -2577,6 +2602,68 @@ func ParseTimeFromInt64(sc *stmtctx.StatementContext, num int64) (Time, error) {
...
+	intPart, err := dec.ToInt()
+	if err != nil && !terror.ErrorEqual(err, ErrTruncated) {
+		return ZeroTime, err
+	}
+	fsp := mathutil.Min(MaxFsp, int(dec.GetDigitsFrac()))
+	t, err = parseDateTimeFromNum(sc, intPart)
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply types/time.go]: Ditto.

File: expression/builtin_time.go (hunk 1 above)
Comment (zanmato1984) [reply expression/builtin_time.go]: Actually it is "interval" that needs to be neg-ed. Kind of tricky because interval is unparsed string. Looking for other way around.

Comment (zanmato1984) [reply expression/builtin_time.go]: Addressed using composition.

File: testkit/result.go (hunk 36 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply testkit/result.go]: Addressed.

File: expression/generator/time_vec.go [hunk 40]
```diff
@@ -690,6 +537,34 @@ var testFileFuncs = template.FuncMap{
 			"YEAR_MONTH",
 		}
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/generator/time_vec.go]: Addressed.

File: expression/bench_test.go (hunk 27 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:786]: This makes sense but I don't think it suites for datetime string generator - the tricky part here is formatting the string.

Besides, I'm not sure if this is more code-saving as we still have to do many time arithmetics which could be cumbersome, given that our low level representation of time value is complex. IMO, the current way is pretty handy.

File: expression/bench_test.go [hunk 41]
```diff
@@ -715,6 +716,20 @@ func (g *randHexStrGener) gen() interface{} {
...
+	randGen *defaultRandGen
+}
+
+func (g dateGener) gen() interface{} {
+	year := 1970 + g.randGen.Intn(100)
+	month := g.randGen.Intn(10) + 1
+	day := g.randGen.Intn(20) + 1
+	gt := types.FromDate(year, month, day, 0, 0, 0, 0)
+	d := types.NewTime(gt, mysql.TypeDate, types.DefaultFsp)
+	return d
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:730]: Same as explained in the other thread.

File: expression/builtin_time.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go]: Bad news, this change breaks some tests. The reason is that: though `sc` is allowed to be `nil` in `check` function, there are some states in `sc`, namely `IgnoreZeroDate` and `AllowInvalidDate`, that will affect the value validity check.

So I think I'm going to revert this change.

[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/builtin_time.go:2792]: Revert done.

File: expression/builtin_time.go (hunk 19 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3888]: Case added.

File: expression/builtin_time.go (hunk 17 above)
Comment (zanmato1984) [reply expression/builtin_time.go:3511]: I did this in MySQL:
```
set global time_zone = 'cet';
create table t1(ts timestamp);
insert into t1 values ('2022-03-27 01:30:00'), ('2022-10-30 02:30:00');
select date_add(ts, interval 1 hour) from t1;
+-------------------------------+
| date_add(ts, interval 1 hour) |
+-------------------------------+
| 2022-03-27 02:30:00           |
| 2022-10-30 03:30:00           |
+-------------------------------+
```

I think this meets my expectation. Did I get this right?

Comment (zanmato1984) [reply expression/builtin_time.go:3511]: Tried the same thing on TiDB (with this PR) and obtained the same result as MySQL.

If the experiment itself is correct, I'll move forward to add these cases in code.

Comment (zanmato1984) [reply expression/builtin_time.go:3511]: Case `TestDateAddForNonExistingTimestamp` in `integration_tests.go` added.

File: expression/bench_test.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/bench_test.go:919]: What is the difference between `dateRealGener` and `dateTimeRealGener` then? is both needed? Or should `dateRealGener` only generate a `Float64` that would correspond to a Date and `dateTimeRealGener` generate a `Float64` correspond to a Datetime?

File: expression/builtin_time_vec.go (hunk 20 above)
Comment (mjonss) [reply expression/builtin_time_vec.go:2847]: ok

File: expression/typeinfer_test.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/typeinfer_test.go:2914]: ok

File: types/time.go (hunk 37 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply types/time.go:2610]: My bad, statement context may be needed for ZeroDate/Day handling.

File: types/time.go (hunk 38 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply types/time.go:2627]: my fault...

File: types/time.go (hunk 39 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply types/time.go:2633]: ditto :)

**Review by mjonss — COMMENTED** [review]
Thanks for the update and sorry for the comment about Statement Context, I missed the Zero handling :(

File: expression/generator/time_vec.go (hunk 40 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/generator/time_vec.go]: Thanks!

File: expression/bench_test.go [hunk 42]
```diff
@@ -820,24 +855,172 @@ func (g *timeStrGener) gen() interface{} {
...
+
+func (g dateTimeRealGener) gen() interface{} {
 	t := g.dateTimeGener.gen().(types.Time)
-	num, err := t.ToNumber().ToInt()
+	tmp, err := t.ToNumber().ToInt()
 	if err != nil {
 		panic(err)
 	}
+	// Ignore the ms part in generated time - it's too normal, we want sometimes more than 6 digits.
+	num := float64(tmp)
```
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/bench_test.go]: Thanks!

File: expression/bench_test.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/bench_test.go]: Same here, I would expect `dateDecimalGener` to generate a `Decimal` that would be parsed as a `Date`, not a `Datetime`. And I would expect `dateTimeDecimalGener` to be different from `dateDecimalGener` :)

File: expression/builtin_time.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/builtin_time.go:2792]: Sorry for this, I should have checked more thoroughly first :(

File: expression/builtin_time.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/builtin_time.go]: Thanks!

File: expression/builtin_time.go (hunk 33 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/builtin_time.go]: Thanks! And sorry for the `sc` comment, you are right that it is needed...

File: expression/builtin_time.go (hunk 34 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/builtin_time.go]: Thanks!

File: expression/builtin_time.go (hunk 2 above)
Comment (mjonss) [reply expression/builtin_time.go:3066]: Again, sorry for this...

File: expression/builtin_time.go (hunk 4 above)
Comment (mjonss) [reply expression/builtin_time.go:3107]: ...

File: expression/builtin_time.go (hunk 6 above)
Comment (mjonss) [reply expression/builtin_time.go:3197]: Thanks for the explanation!

File: expression/builtin_time.go (hunk 16 above)
Comment (mjonss) [reply expression/builtin_time.go:3423]: Thanks for looking!

**Review by mjonss — COMMENTED** [review]
Suggestion to slightly improved DST test.

File: expression/builtin_time.go (hunk 17 above)
Comment (mjonss) [reply expression/builtin_time.go:3511]: Thanks for adding the test, I did a minor suggestion in a new review.

File: expression/builtin_time.go (hunk 19 above)
Comment (mjonss) [reply expression/builtin_time.go:3888]: Thanks!

File: expression/bench_test.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:919]: `date/dateTimeDecimalGener` has the same purpose and pattern as `date/dateTimeRealGener` so I'll explain them together here.

`dateReal/DecimalGener` inherits `dateGener`, which generates a date value (a time value with type `mysql.TypeDate`), whose `ToNumber()` method returns a number like `20010203`, i.e., no HMS or us portion.

`dateTimeReal/DecimalGener` inherits `dateTimeGener`, which generates a datetime value (a time value with type `mysql.DateTime`), whose `ToNumber()` method returns a number like `20010203040506.789012`, i.e., with HMS and us portion.

The reason why they are distinguished, is that for functions like `date_add/sub` (and possibly others), when the first argument is a real/decimal value and the second argument is using YMD unit, the return value depends on the content of the first argument (note that the return type is always string - there is no ambiguity about returning date or datetime, and precision). The following statements shows this subtle difference:

```
select date_add(20010203.987, interval 1 day);
+----------------------------------------+
| date_add(20010203.987, interval 1 day) |
+----------------------------------------+
| 2001-02-04                             |
+----------------------------------------+

select date_add(20010203040506.987, interval 1 day);
+----------------------------------------------+
| date_add(20010203040506.987, interval 1 day) |
+----------------------------------------------+
| 2001-02-04 04:05:06.987000                   |
+----------------------------------------------+
```

This reveals MySQL must have two different code paths dealing with real/decimal value corresponding to a date and a datetime. So I think both are needed, to explicitly test each code path.

An alternative way would be, combining `dateReal/DecimalGener` and `dateTimeReal/DecimalGener`, and using a dedicated variable to control the ratio of a real/decimal with or w/o HMS portion, i.e., being a date or a datetime. But  I think that's kind of too implicit than the current separated way.

File: expression/bench_test.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go]: Explained in the other thread.

File: expression/integration_test.go [hunk 43]
```diff
@@ -7318,6 +7319,83 @@ func TestIssue34659(t *testing.T) {
...
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t(ts timestamp)")
+	// Non-existing CET timestamp.
+	tk.MustGetErrCode("insert into t values('2022-03-27 02:30:00')", errno.ErrTruncatedWrongValue)
+	tk.MustExec("insert into t values('2022-03-27 01:30:00')")
+	tk.MustExec("insert into t values('2022-10-30 02:30:00')")
+	tk.MustQuery("select date_add(ts, interval 1 hour) from t order by ts").Check([][]interface{}{
+		{"2022-03-27 02:30:00"},
+		{"2022-10-30 03:30:00"},
+	})
```
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/integration_test.go:7395]: Good catch. Applying.

File: expression/bench_test.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply expression/bench_test.go:919]: Ah, then I think I understand you, so the fraction part of the `dateRealGener`/`dateDecimalGener` is added just for testing, to be sure that it is never used?

File: expression/builtin_time.go (hunk 18 above)
Comment (mjonss) [reply expression/builtin_time.go:3531]: Ah, thank you for the explanation and sorry for missing it :(

**Review by mjonss — APPROVED** [review]
Great job and thank you so much for educating me and sorry for wasting some time with some bad assumptions from my side.

**Comment by zanmato1984** [comment]
> Great job and thank you so much for educating me and sorry for wasting some time with some bad assumptions from my side.

Thank you for your great effort reviewing this PR. Really appreciate that!

File: expression/bench_test.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (zanmato1984) [reply expression/bench_test.go:919]: Right. They are for testing only.

**Review by winoros — APPROVED** [review]
