### PR TITLE
br: merge range in lightweight when snapshot restore

### LINKED ISSUE #50613: br restore very slow (like it hangs) when merging files
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run br restore full to restore a 300 TB cluster backup to a cluster with 100 TiKV  nodes.

### 2. What did you expect to see? (Required)
Restore should succeeds.

### 3. What did you see instead (Required)
Restore is very slow,  it looks like it hangs when merging files. br restore doesn't enter "split and scatter phase" after ~40m of restore.

### 4. What is your TiDB version? (Required)
v7.6.0

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #50613

Problem Summary:
Merge file ranges takes too much time when the file ranges's size is much large.
### What changed and how does it work?
use the O(n) algorithm
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/rtree/rtree.go [hunk 1]
```diff
@@ -74,6 +76,47 @@ func (rg *Range) Less(than btree.Item) bool {
 	return bytes.Compare(rg.StartKey, ta.StartKey) < 0
 }
 
+// NeedsMerge checks whether two ranges needs to be merged.
```
Comment (Leavrth) [inline br/pkg/rtree/rtree.go:79]: directly move from br/pkg/restore/merge.go

File: br/pkg/rtree/rtree_test.go [hunk 2]
```diff
@@ -180,3 +183,39 @@ func BenchmarkRangeTreeUpdate(b *testing.B) {
...
+					Name:       fmt.Sprintf("%20d", i),
+					TotalKvs:   1,
+					TotalBytes: 1,
+				},
+			},
+			Size: uint64(i),
+		}
+		rangeTree.Update(item)
+	}
+	sortedRanges := rangeTree.Merge(10, 10)
```
Comment (3pointer) [inline br/pkg/rtree/rtree_test.go:209]: maybe check the length of sortedRanges is equal to 1000

**Review by 3pointer — APPROVED** [review]
rest LGTM

File: br/pkg/rtree/rtree.go [hunk 3]
```diff
@@ -165,6 +208,31 @@ func (rangeTree *RangeTree) InsertRange(rg Range) *Range {
 	return out.(*Range)
 }
 
+func (rangeTree *RangeTree) Merge(splitSizeBytes, splitKeyCount uint64) []Range {
+	var mergeTargetIndex int = -1
+	sortedRanges := make([]Range, 0, rangeTree.Len())
+	rangeTree.Ascend(func(item btree.Item) bool {
+		if item == nil {
+			return false
+		}
```
Comment (YuJuncen) [inline br/pkg/rtree/rtree.go:217]: In what case this will happen? If this never happen, I think it is better to panic here. If it is possible, at lease we need to print some logs.

File: br/pkg/rtree/rtree.go [hunk 4]
```diff
@@ -165,6 +208,31 @@ func (rangeTree *RangeTree) InsertRange(rg Range) *Range {
 	return out.(*Range)
 }
 
+func (rangeTree *RangeTree) Merge(splitSizeBytes, splitKeyCount uint64) []Range {
```
Comment (YuJuncen) [inline br/pkg/rtree/rtree.go:211]: The method name `Merge` sounds like used for merging another tree. How about `MergedRanges`

**Review by YuJuncen — COMMENTED** [review]
rest lgtm

File: br/pkg/rtree/rtree.go (hunk 3 above)
Comment (Leavrth) [reply br/pkg/rtree/rtree.go:217]: Just keep the same as `Ascend` in `GetSortedRanges`

**Review by YuJuncen — APPROVED** [review]
