### PR TITLE
planner: return NULL for empty scalar COUNT/HAVING subquery after decorrelation

### LINKED ISSUE #66619: Correlated subquery with `COUNT` and `HAVING` returns 0 instead of NULL after decorrelation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```SQL
mysql> CREATE TABLE t1(a INT);
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE t2(a INT);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES(1), (2), (3), (4);
Query OK, 4 rows affected (0.01 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t2 VALUES(1), (2);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> SELECT (SELECT COUNT(1) AS cnt FROM t2 WHERE t2.a = t1.a HAVING cnt > 0) FROM t1;
+-------------------------------------------------------------------+
| (SELECT COUNT(1) AS cnt FROM t2 WHERE t2.a = t1.a HAVING cnt > 0) |
+-------------------------------------------------------------------+
|                                                                 1 |
|                                                                 1 |
|                                                                 0 |
|                                                                 0 |
+-------------------------------------------------------------------+
4 rows in set (0.00 sec)

mysql> SELECT (SELECT /*+ NO_DECORRELATE() */ COUNT(1) FROM t2 WHERE t2.a = t1.a HAVING COUNT(1) > 0) FROM t1;
+---------------------------------------------------------------------------------------+
| (SELECT /*+ NO_DECORRELATE()  COUNT(1) FROM t2 WHERE t2.a = t1.a HAVING COUNT(1) > 0) |
+---------------------------------------------------------------------------------------+
|                                                                                     1 |
|                                                                                     1 |
|                                                                                  NULL |
|                                                                                  NULL |
+---------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
For t1.a = 3 and t1.a = 4, the subquery evaluates to COUNT = 0. The HAVING cnt > 0 clause filters this out, resulting in an empty set. A scalar subquery returning an empty set must evaluate to NULL.
```SQL
mysql> SELECT (SELECT COUNT(1) AS cnt FROM t2 WHERE t2.a = t1.a HAVING cnt > 0) FROM t1;
+-------------------------------------------------------------------+
| (SELECT COUNT(1) AS cnt FROM t2 WHERE t2.a = t1.a HAVING cnt > 0) |
+-------------------------------------------------------------------+
|                                                                 1 |
|                                                                 1 |
|                                                              NULL |
|                                                              NULL |
+-------------------------------------------------------------------+
4 rows in set (0.01 sec)
```

### 3. What did you see instead (Required)
```SQL
mysql> SELECT (SELECT COUNT(1) AS cnt FROM t2 WHERE t2.a = t1.a HAVING cnt > 0) FROM t1;
+-------------------------------------------------------------------+
| (SELECT COUNT(1) AS cnt FROM t2 WHERE t2.a = t1.a HAVING cnt > 0) |
+-------------------------------------------------------------------+
|                                                                 1 |
|                                                                 1 |
|                                                                 0 |
|                                                                 0 |
+-------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```SQL
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v9.0.0-beta.2.pre-1288-g9246e723a7
Edition: Community
Git Commit Hash: 9246e723a7477f0157ba726413e6d0d7b392ab20
Git Branch: master
UTC Build Time: 2026-03-02 01:40:27
GoVersion: go1.25.6
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Kernel Type: Classic |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #66619

Problem Summary:
- After decorrelation, a correlated scalar subquery with `COUNT` + `HAVING` can return `0` when it should return `NULL` for the empty result set case.
- The result is inconsistent with `/*+ NO_DECORRELATE() */`.

### What changed and how does it work?

- In the decorrelation rule for scalar aggregations, when `COUNT` (and other aggregates with non-NULL default values) requires default-value handling via `IFNULL`, conditions pulled up from above the aggregation (typically `HAVING`) are no longer attached to the join.
- Instead, those conditions are evaluated in a projection (using defaulted aggregate expressions), and the inner output columns are wrapped as `IF(having, <expr>, NULL)`. This preserves:
  - empty-input aggregate defaults (e.g. `COUNT` -> `0`) when `HAVING` is true on the empty input;
  - scalar-subquery semantics (`HAVING` filters out the only row => empty set => `NULL`).

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Unit test:
- `make failpoint-enable && (cd pkg/planner/core && go test -run TestIssue66619 -tags=intest,deadlock -count=1) && make failpoint-disable`
- `make lint`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix incorrect `0` result for decorrelated scalar `COUNT`/`HAVING` subqueries when the subquery returns an empty result set.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling of correlated scalar aggregates so default values and NULLs are applied without breaking HAVING semantics; preserves HAVING behavior on empty inputs and avoids misapplied join conditions by deferring HAVING evaluation until after defaulting.

* **Tests**
  * Added an integration test for correlated subqueries, counts, NULL behavior and NO_DECORRELATE; updated expected plans to include an additional projection and adjusted projection expression.

### CODE REVIEW

**Comment by qw4990** [comment]
@pantheon-ai Please help review

File: pkg/planner/core/rule_decorrelate.go [hunk 1]
```diff
@@ -427,19 +451,60 @@ func (s *DecorrelateSolver) optimize(ctx context.Context, p base.LogicalPlan, gr
...
-								pos := proj.Schema().ColumnIndex(agg.Schema().Columns[i])
-								ifNullFunc := expression.NewFunctionInternal(agg.SCtx().GetExprCtx(), ast.Ifnull, types.NewFieldType(mysql.TypeLonglong), agg.Schema().Columns[i], val)
-								proj.Exprs[pos] = ifNullFunc
+							if len(havingConds) == 0 {
+								proj := logicalop.LogicalProjection{}.Init(agg.SCtx(), agg.QueryBlockOffset())
+								proj.SetSchema(apply.Schema())
+								proj.Exprs = expression.Column2Exprs(apply.Schema().Columns)
+								for i, val := range defaultValueMap {
+									pos := proj.Schema().ColumnIndex(agg.Schema().Columns[i])
+									ifNullFunc := expression.NewFunctionInternal(agg.SCtx().GetExprCtx(), ast.Ifnull, types.NewFieldType(mysql.TypeLonglong), agg.Schema().Columns[i], val)
```
[the remark this answers is not in the document]
Comment (qw4990) [reply pkg/planner/core/rule_decorrelate.go]: Addressed.

**Review by hawkingrei — APPROVED** [review]

File: pkg/planner/core/rule_decorrelate.go [hunk 2]
```diff
@@ -427,19 +457,62 @@ func (s *DecorrelateSolver) optimize(ctx context.Context, p base.LogicalPlan, gr
...
+								defaultProj.Schema().Append(havingCol)
+								defaultProj.SetChildren(apply)
+
+								proj := logicalop.LogicalProjection{}.Init(agg.SCtx(), agg.QueryBlockOffset())
+								proj.SetSchema(apply.Schema())
+								proj.Exprs = expression.Column2Exprs(defaultProj.Schema().Columns[:apply.Schema().Len()])
+								outerLen := outerPlan.Schema().Len()
+								havingVal := defaultProj.Schema().Columns[defaultProj.Schema().Len()-1]
+								for i := outerLen; i < proj.Schema().Len(); i++ {
+									retType := proj.Schema().Columns[i].RetType.Clone()
```
Comment (AilinKid) [inline pkg/planner/core/rule_decorrelate.go]: RetType.DeepCopy()

Comment (qw4990) [reply pkg/planner/core/rule_decorrelate.go]: It seems like we can write a Skill for this.

Comment (qw4990) [reply pkg/planner/core/rule_decorrelate.go]: To tell AI to always use `DeepCopy()` in the optimization phase.

Comment (qw4990) [reply pkg/planner/core/rule_decorrelate.go]: Addressed, thanks for your review
