### PR TITLE
executor: fix select sleep killed return expected error

### LINKED ISSUE #45813: sleep with `/*+ MAX_EXECUTION_TIME(1) */` hint do not return expected error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run `select /*+ MAX_EXECUTION_TIME(1) */ sleep(1)`.

### 2. What did you expect to see? (Required)

```
mysql> select /*+ MAX_EXECUTION_TIME(1) */ sleep(1);
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
```

### 3. What did you see instead (Required)

```sql
mysql> select /*+ MAX_EXECUTION_TIME(1) */ sleep(1);
+----------+
| sleep(1) |
+----------+
|        1 |
+----------+
1 row in set (0.05 sec)
```

The statement `sleep(1)` should not return without error less than 1 second, and the hint does not return error expectedly.

### 4. What is your TiDB version? (Required)

```
Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 522a00840385dfa43509a3af2bc79e6ff50252a8
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-03 14:26:07
GoVersion: go1.20.7
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #45813

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: expression/builtin_miscellaneous_vec.go [hunk 1]
```diff
@@ -359,13 +359,11 @@ func doSleep(secs float64, sessVars *variable.SessionVars) (isKilled bool) {
...
-				timer.Stop()
-				return true
-			}
-			// Killed because of max execution time
-			if atomic.CompareAndSwapUint32(&sessVars.Killed, 2, 0) {
+			// Regular kill or Killed because of max execution time.
+			if atomic.LoadUint32(&sessVars.Killed) == 1 || atomic.LoadUint32(&sessVars.Killed) == 2 {
+				if len(sessVars.StmtCtx.TableIDs) == 0 {
+					atomic.StoreUint32(&sessVars.Killed, 0)
+				}
```
Comment (you06) [inline expression/builtin_miscellaneous_vec.go:366]: It's ok to seperate compare-and-swap into load and store when `len(sessVars.StmtCtx.TableIDs) == 0`, the `sessVars.Killed` atomic variable is used by sleep thread only. But can we make the code like this because I think load and store in two places are strange when doing atomic operation:

```go
if  len(sessVars.StmtCtx.TableIDs) == 0 {
	// the compare-and-swap code before
} else {
	if atomic.LoadUint32(&sessVars.Killed) == 1 || atomic.LoadUint32(&sessVars.Killed) == 2 {
		return true
	}
}

**Review by you06 — APPROVED** [review]
Thanks for your contribution!

**Comment by you06** [comment]
@zimulala PTAL

File: server/conn_test.go [hunk 2]
```diff
@@ -710,30 +710,13 @@ func TestConnExecutionTimeout(t *testing.T) {
...
-
-	err = cc.handleQuery(context.Background(), "select * FROM testTable2 WHERE SLEEP(1);")
-	require.NoError(t, err)
-
-	err = cc.handleQuery(context.Background(), "select /*+ MAX_EXECUTION_TIME(100)*/  * FROM testTable2 WHERE  SLEEP(1);")
-	require.NoError(t, err)
-
-	tk.MustExec("set @@max_execution_time = 500;")
-
-	err = cc.handleQuery(context.Background(), "alter table testTable2 add index idx(age);")
```
Comment (zimulala) [inline server/conn_test.go:735]: Why remove these cases.

**Review by zimulala — APPROVED** [review]
LGTM
