### PR TITLE
executor: fix projection executor panic and add failpoint test

### LINKED ISSUE #24210: TiDB will panic if ProjectionExec.baseExecutor.Open returns error
## Bug Report

IMHO, we don't need to reproduce this case since it's obvious.

Just read the code.

If `e.baseExecutor.Open()` returns error, then `e.open()` won't be called, which means `e.childResult` and `e.memTracker` won't be initialized.

https://github.com/pingcap/tidb/blob/f973108fc868cc665c0107b71ae767bbfc857881/executor/projection.go#L84-L89

If `Executor.Open()` returns error, then `Executor.Close()` will be called.

https://github.com/pingcap/tidb/blob/f973108fc868cc665c0107b71ae767bbfc857881/executor/adapter.go#L335-L338

If `e.numWorkers == 0`, then `e.isUnparallelExec()` will return true. In this case, `e.memTracker` will try to record memory usage of `e.childResult` where both `e.memTracker` and `e.childResult` are `nil`. 

https://github.com/pingcap/tidb/blob/f973108fc868cc665c0107b71ae767bbfc857881/executor/projection.go#L292-L296

Then TiDB will raise NPE.
### What is your TiDB version? (Required)

```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2658-g281d13465
Edition: Community
Git Commit Hash: 281d1346574cbc07d1e41f6428a5145a146dedfc
Git Branch: master
UTC Build Time: 2021-04-16 05:06:31
GoVersion: go1.16.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #24210 

Problem Summary:

the original issue has the summary: https://github.com/pingcap/tidb/issues/24210

### What is changed and how it works?

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch, 5.0 and 4.0

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- No release note

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -8288,3 +8288,15 @@ func (s *testSuite1) TestIssue24091(c *C) {
 	tk.MustQuery("select null div 0;").Check(testkit.Rows("<nil>"))
 	tk.MustQuery("select * from t;").Check(testkit.Rows("<nil>"))
 }
+
+func (s *testSuite1) TestIssue24210(c *C) {
```
Comment (tangenta) [inline executor/executor_test.go:8292]: Please use `SerialTestSuite` if you use failpoints.

File: executor/projection.go [hunk 2]
```diff
@@ -290,7 +296,9 @@ func (e *ProjectionExec) drainOutputCh(ch chan *projectionOutput) {
 
 // Close implements the Executor Close interface.
 func (e *ProjectionExec) Close() error {
-	if e.isUnparallelExec() {
+	// if e.baseExecutor.Open returns error, e.childResult will be nil, see https://github.com/pingcap/tidb/issues/24210
+	// for more information
+	if e.isUnparallelExec() && e.childResult != nil {
```
Comment (tangenta) [inline executor/projection.go:301]: We should also check every usage of `childResult`, and wrap them with `if e.childResult != nil`.

File: executor/executor_test.go (hunk 1 above)
Comment (ichn-hu) [reply executor/executor_test.go:8292]: addressed

File: executor/projection.go (hunk 2 above)
Comment (ichn-hu) [reply executor/projection.go:301]: I don't think we should check at every usage, because if open returned error, only Close will be called.

**Comment by ichn-hu** [comment]
@tangenta PTALA

File: executor/projection.go (hunk 2 above)
Comment (fzhedu) [reply executor/projection.go:301]: remove this if below [L318](https://github.com/pingcap/tidb/pull/24231/files#diff-ff427415020e8206064bbb4bba684d29e8aa5e8bba1b990164c5460908dab52dR318)

**Comment by fzhedu** [comment]
please check the memtracker in other operators?

**Comment by leiysky** [comment]
Maybe other `Executor`s with `memTracker` should be fixed either?

**Comment by ichn-hu** [comment]
Okay, I found HashAggExec has the same problem, and I'll walk through all 83 executors, please do not merge.

**Comment by ichn-hu** [comment]
I checked all executors (83 of them), and

- HashAggExec
- StreamAggExec
- SelectionExec

has the similar problem, I'll add them into this PR soon.

File: executor/projection.go [hunk 3]
```diff
@@ -85,6 +86,11 @@ func (e *ProjectionExec) Open(ctx context.Context) error {
 	if err := e.baseExecutor.Open(ctx); err != nil {
 		return err
 	}
+	failpoint.Inject("mockProjectionExecBaseExecutorOpenReturnedError", func(val failpoint.Value) {
+		if val.(bool) {
+			failpoint.Return(errors.New("mock e.baseExecutor.Open returned error"))
+		}
+	})
```
Comment (tangenta) [inline executor/projection.go:93]: We can place it in `baseExecutor.Open()` so that all tests can use the same failpoint.

Comment (ichn-hu) [reply executor/projection.go:93]: No, seems we can't, because if we inject error at baseExecutor, then all executor won't open

Comment (ichn-hu) [reply executor/projection.go:93]: and we can't control the granuity.

**Comment by ichn-hu** [comment]
@fzhedu @tangenta @lzmhhh123 it is now ready for review, PTAL

File: executor/aggregate.go [hunk 4]
```diff
@@ -226,11 +227,15 @@ func (d *HashAggIntermData) getPartialResultBatch(sc *stmtctx.StatementContext,
 // Close implements the Executor Close interface.
 func (e *HashAggExec) Close() error {
 	if e.isUnparallelExec {
-		e.memTracker.Consume(-e.childResult.MemoryUsage())
```
Comment (leiysky) [inline executor/aggregate.go:229]: Why removing this?

File: executor/aggregate.go [hunk 5]
```diff
@@ -250,14 +255,15 @@ func (e *HashAggExec) Close() error {
 		}
 	}
 	for _, ch := range e.partialInputChs {
-		for chk := range ch {
-			e.memTracker.Consume(-chk.MemoryUsage())
```
Comment (leiysky) [inline executor/aggregate.go:254]: Ditto.

**Review by leiysky — COMMENTED** [review]
Rest LGTM

File: executor/aggregate.go (hunk 4 above)
Comment (ichn-hu) [reply executor/aggregate.go:229]: Becaue at the end of this Close, there is a `e.memTracker.ReplaceBytesUsed(0)`, so there is really no reason to reduce them here.

File: executor/aggregate.go (hunk 5 above)
Comment (ichn-hu) [reply executor/aggregate.go:254]: Ditto.

**Comment by ichn-hu** [comment]
@leiysky PALA

File: executor/aggregate.go (hunk 4 above)
Comment (leiysky) [reply executor/aggregate.go:229]: Well, IMO, it looks more resonable to remove `e.memTracker.ReplaceBytesUsed(0)` instead that can help to track memory leak...

Comment (XuHuaiyu) [reply executor/aggregate.go:229]: Why not keep them both?

File: executor/aggregate.go [hunk 6]
```diff
@@ -226,11 +227,15 @@ func (d *HashAggIntermData) getPartialResultBatch(sc *stmtctx.StatementContext,
...
 		e.childResult = nil
 		e.groupSet, _ = set.NewStringSetWithMemoryUsage()
 		e.partialResultMap = nil
-		e.memTracker.ReplaceBytesUsed(0)
+		if e.memTracker != nil {
+			e.memTracker.ReplaceBytesUsed(0)
+		}
+		return e.baseExecutor.Close()
+	}
+	if !e.initialized {
```
Comment (fzhedu) [inline executor/aggregate.go:238]: why add `if !e.initialized {` ? because the close should be called to close it child.

Comment (ichn-hu) [reply executor/aggregate.go:238]: we should only close channel when the channel is initialized, close a not initialized channel will cause panic, so if the executor is not initialized, we should return immediately.

Comment (fzhedu) [reply executor/aggregate.go:238]: `e.baseExecutor.Close()` should close its child regardless this operator is compeletly initialized.

Comment (ichn-hu) [reply executor/aggregate.go:238]: In the end, L267, we will call e.baseExecutor.Close()

File: executor/aggregate.go (hunk 4 above)
Comment (ichn-hu) [reply executor/aggregate.go:229]: @XuHuaiyu there is no reason why we need to keep them both:

1. if we want the memTracker to have 0 byte consumption in the end, we should just e.memTracker.ReplaceBytesUsed(0)
2. if we want to detect memory leakage, we should use Consume(-usage) everywhere

@leiysky what I am doing is for 1, but I think 2 should also be a valid point, but I doubt 2 is not satisfied right now, so it could be a future ehancement (we should check more executors), and I would like to add a new ehancement issue for this, does it sounds good to you?

File: executor/aggregate.go (hunk 6 above)
Comment (fzhedu) [reply executor/aggregate.go:238]: plese refactor these code

Comment (XuHuaiyu) [reply executor/aggregate.go]: Why the `e.prepared` is not enough to control this?
I do not understand when will we close an un-initialized channel.

File: executor/aggregate.go (hunk 4 above)
Comment (XuHuaiyu) [reply executor/aggregate.go:229]: For my part, if this modification is aimed to enhance the memory track of `agg.memTracker`, we'd better open another issue or PR to track it.
This modification has nothing to do with the issue that this PR wants to fix.

**Comment by ichn-hu** [comment]
@leiysky PTALA

File: executor/aggregate.go [hunk 7]
```diff
@@ -187,6 +187,7 @@ type HashAggExec struct {
 	// After we support parallel execution for aggregation functions with distinct,
 	// we can remove this attribute.
 	isUnparallelExec bool
+	initialized      bool
```
Comment (tangenta) [inline executor/aggregate.go:190]: This field seems to only meaningful to the "parallelExec"... Should we rename it to `parallelExecInitialized`?

**Comment by ichn-hu** [comment]
@tangenta PTALA

**Comment by ichn-hu** [comment]
@XuHuaiyu @leiysky @tangenta let's merge it soon

**Review by tangenta — APPROVED** [review]

File: executor/aggregate.go (hunk 6 above)
Comment (ichn-hu) [reply executor/aggregate.go]: @XuHuaiyu because e.prepared only protects if e.prepare4ParallelExec has been executed, but not if the channels are initialized.

> I do not understand when will we close an un-initialized channel.

Say, if the baseExecutor.Open() returns error, then `e.initForParallelExec(e.ctx)` will not be called, and when `e.Close()` is called, `e.prepared` will be false, and `close(e.inputCh)` will be executed, and will result in closing un-initialized channel.
