### PR TITLE
planner: index pruning using existing infra

### LINKED ISSUE #63856: Planner: Planning time increases significantly with large number of indexes
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t8` (
  `a` int,
  `b` int,
  `c` int,
  `d` int,
  `e` int,
  `f` int,
  `g` int,
  `h` int,
  `i` int,
  `j` int,
  `k` int,
  `l` int,
  `m` int,
  `n` int,
  `o` int,
  `p` int,
  `q` int,
  `r` int,
  `s` int,
  `t` int,
  `u` int,
  `v` int,
  `w` int,
  `x` int,
  `y` int,
  `z` int,
  `aa` int,
  `ab` int,
  `ac` int,
  `ad` int,
  `ae` int,
  `af` int,
  `ag` int,
  `ah` int,
  `ai` int,
  `aj` int,
  `ak` int,
  `al` int,
  `am` int,
  `an` int,
  `ao` int,
  `ap` int,
  `aq` int,
  `ar` int,
  `as` int,
  `at` int,
  `au` int,
  `av` int,
  `aw` int,
  `ax` int,
  `ay` int,
  `az` int,
  `ba` int,
  `bb` int,
  `bc` int,
  `bd` int,
  `be` int,
  `bf` int,
  `bg` int,
  `bh` int,
  `bi` int,
  `bj` int,
  `bk` int,
  `bl` int,
  `bm` int,
  `bn` int,
  `bo` int,
  `bp` int,
  `bq` int,
  `br` int,
  `bs` int,
  `bt` int,
  `bu` int,
  `bv` int,
  `bw` int,
  `bx` int,
  `by` int,
  `bz` int,
  `ca` int,
  `cb` int,
  `cc` int,
  `cd` int,
  `ce` int,
  `cf` int,
  `cg` int,
  `ch` int,
  `ci` int,
  `cj` int,
  `ck` int,
  `cl` int,
  `cm` int,
  `cn` int,
  `co` int,
  `cp` int,
  `cq` int,
  `cr` int,
  `cs` int,
  `ct` int,
  `cu` int,
  `cv` int,
  `cw` int,
  `cx` int,
  `cy` int,
  `cz` int,
  `da` int,
  `db` int,
  `dc` int,
  `dd` int,
  `de` int,
  `df` int,
  `dg` int,
  `dh` int,
  `di` int,
  `dj` int,
  `dk` int,
  `dl` int,
  `dm` int,
  `dn` int,
  `do` int,
  `dp` int,
  `dq` int,
  `dr` int,
  `ds` int,
  `dt` int,
  `du` int,
  `dv` int,
  `dw` int,
  `dx` int,
  `dy` int,
  `dz` int,
  `ea` int,
  `eb` int,
  `ec` int,
  `ed` int,
  `ee` int,
  `ef` int,
  `eg` int,
  `eh` int,
  `ei` int,
  `ej` int,
  `ek` int,
  `el` int,
  `em` int,
  `en` int,
  `eo` int,
  `ep` int,
  `eq` int,
  `er` int,
  `es` int,
  `et` int,
  `eu` int,
  `ev` int,
  `ew` int,
  `ex` int,
  `ey` int,
  `ez` int,
  
  KEY `ia` (`aa`),
  KEY `iab` (`aa`, `b`),
  KEY `iac` (`a`, `c`),
  KEY `iad` (`aa`, `d`),
  KEY `iae` (`a`, `e`),
  KEY `iaf` (`a`, `f`),
  KEY `iabc` (`ea`, `b`, `c`),
  KEY `iabd` (`ea`, `b`, `d`),
  KEY `iabe` (`ea`, `b`, `e`),
  KEY `iabf` (`ea`, `b`, `f`),
  KEY `iacb` (`ea`, `c`, `b`),
  KEY `iacd` (`ea`, `c`, `d`),
  KEY `iace` (`ea`, `c`, `e`),
  KEY `iacf` (`ea`, `c`, `f`),
  
  KEY `iade` (`ea`, `d`, `e`),
  KEY `iadf` (`ea`, `d`, `f`),
  KEY `iaeb` (`ea`, `e`, `b`),
  KEY `iaec` (`ea`, `e`, `c`),
  KEY `iaed` (`ea`, `e`, `d`),
  KEY `iaef` (`ea`, `e`, `f`),
  KEY `iafb` (`a`, `f`, `b`),
  KEY `iafc` (`ea`, `f`, `a`),
  KEY `iafd` (`ea`, `f`, `d`),
  KEY `iafe` (`ea`, `f`, `e`),
  
  KEY `iabcd` (`a`, `b`, `c`, `ed`),
  KEY `iabce` (`a`, `b`, `c`, `ee`),
  KEY `iabcf` (`a`, `b`, `c`, `ef`),
  KEY `iabdc` (`a`, `b`, `d`, `ec`),
  KEY `iabfc` (`a`, `b`, `f`, `ec`),
  KEY `iabfd` (`a`, `b`, `f`, `ed`),
  KEY `iabfe` (`a`, `b`, `f`, `ee`),
  KEY `iacbd` (`a`, `c`, `b`, `ed`),
  KEY `iacbe` (`a`, `c`, `b`, `ee`),
  KEY `iacbf` (`a`, `c`, `b`, `ef`),
  KEY `iacdb` (`a`, `c`, `d`, `eb`),
  KEY `iacde` (`a`, `c`, `d`, `ee`),
  KEY `iadbe` (`a`, `d`, `b`, `ee`),
  KEY `iadcb` (`a`, `d`, `c`, `eb`),
  KEY `iadcf` (`a`, `d`, `c`, `ef`),
  
  KEY `ib` (`eb`),
  KEY `iba` (`eb`, `a`),
  KEY `ibc` (`eb`, `c`),
  KEY `ibd` (`eb`, `d`),
  KEY `ibe` (`eb`, `e`),
  KEY `ibf` (`eb`, `f`),
  KEY `ibac` (`b`, `a`, `c`),
  KEY `ibad` (`b`, `a`, `d`),
  KEY `ibae` (`b`, `a`, `e`),
  KEY `ibaf` (`b`, `a`, `f`),
  KEY `ibca` (`b`, `c`, `a`),
  KEY `ibcd` (`b`, `c`, `d`),
  KEY `ibce` (`b`, `c`, `e`),
  KEY `ibcf` (`b`, `c`, `f`),
  KEY `ibda` (`b`, `d`, `a`),
  KEY `ibdc` (`b`, `d`, `c`),
  KEY `ibde` (`b`, `d`, `e`),
  KEY `ibdf` (`b`, `d`, `f`),
  KEY `ibea` (`b`, `e`, `a`),
  KEY `ibec` (`b`, `e`, `c`),
  KEY `ibfa` (`b`, `f`, `a`),
  KEY `ibfc` (`b`, `f`, `c`),
  KEY `ibfd` (`b`, `f`, `d`),
  KEY `ibfe` (`b`, `f`, `e`)
);
```

### 2. What did you expect to see? (Required)

This is optimistic - but when I specify "use index" - I can force one index to be considered, and the explain is fast:
```
tidb> explain select a from t8 use index (iaf) where (a = 1 and f = 1) or (a = 2 and f = 1) or (a = 3 and f = 1) or (a = 4 and f = 1) or (a = 5 and f = 1) or (a = 6 and f = 1) or (a = 7 and f = 1) or (a = 8 and f = 1) or (a = 9 and f = 1) or (a = 1 and f = 2) or (a = 2 and f = 2) or (a = 3 and f = 2) or (a = 4 and f = 2) or (a = 5 and f = 2) or (a = 6 and f = 2) or (a = 7 and f = 2) or (a = 8 and f = 2) or (a = 9 and f = 2);
+--------------------------+---------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| id                       | estRows | task      | access object             | operator info                                                                                                                           |
+--------------------------+---------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| IndexReader_10           | 22.50   | root      |                           | index:Projection_6                                                                                                                      |
| └─Projection_6           | 22.50   | cop[tikv] |                           | test.t8.a                                                                                                                               |
|   └─IndexRangeScan_9     | 22.50   | cop[tikv] | table:t8, index:iaf(a, f) | range:[1 1,1 2], [2 1,2 2], [3 1,3 2], [4 1,4 2], [5 1,5 2], [6 1,6 2], [7 1,7 2], [8 1,8 2], [9 1,9 2], keep order:false, stats:pseudo |
+--------------------------+---------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.012 sec)
```

### 3. What did you see instead (Required)

Allowing the optimizer to consider all indexes in 8X slower for the above DDL:
```
tidb> explain select a from t8 where (a = 1 and f = 1) or (a = 2 and f = 1) or (a = 3 and f = 1) or (a = 4 and f = 1) or (a = 5 and f = 1) or (a = 6 and f = 1) or (a = 7 and f = 1) or (a = 8 and f = 1) or (a = 9 and f = 1) or (a = 1 and f = 2) or (a = 2 and f = 2) or (a = 3 and f = 2) or (a = 4 and f = 2) or (a = 5 and f = 2) or (a = 6 and f = 2) or (a = 7 and f = 2) or (a = 8 and f = 2) or (a = 9 and f = 2);
+---------------------------+---------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| id                        | estRows | task      | access object             | operator info                                                                                                                           |
+---------------------------+---------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| IndexReader_13            | 22.50   | root      |                           | index:Projection_6                                                                                                                      |
| └─Projection_6            | 22.50   | cop[tikv] |                           | test.t8.a                                                                                                                               |
|   └─IndexRangeScan_11     | 22.50   | cop[tikv] | table:t8, index:iaf(a, f) | range:[1 1,1 2], [2 1,2 2], [3 1,3 2], [4 1,4 2], [5 1,5 2], [6 1,6 2], [7 1,7 2], [8 1,8 2], [9 1,9 2], keep order:false, stats:pseudo |
+---------------------------+---------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.087 sec)
```

### 4. What is your TiDB version? (Required)

master branch - but true in any release.

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #63856

Problem Summary:

### What changed and how does it work?

Prior PR title:
planner: index pruning using existing infra | tidb-test=pr/2661
Latest commit results in no mysql test changes.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by terry1purcell** [comment]
> ### P2: IndexMerge hints can be broken by early index pruning
> **Impact** For queries relying on `use_index_merge(...)`, pruning can remove hinted index access paths **before** IndexMerge path generation runs, making the hint **“inapplicable”** and forcing fallback to non-IndexMerge plans (potentially a severe plan regression for hint-dependent workloads).
> 
> **Evidence**
> 
> * Pruning mutates the path sets used downstream:
>   
>   * `pkg/planner/core/rule/rule_collect_plan_stats.go:229` prunes `ds.AllPossibleAccessPaths`
>   * `pkg/planner/core/rule/rule_collect_plan_stats.go:269` overwrites `ds.PossibleAccessPaths` with the pruned set
> * The pruning code includes an `indexMergeIndexPaths` bucket but never populates it:
>   
>   * `pkg/planner/core/rule/rule_prune_indexes.go:86`
>   * Yet `buildFinalResult` claims it “always include indexes specified in IndexMerge hints”:
>     
>     * `pkg/planner/core/rule/rule_prune_indexes.go:308`
> * IndexMerge generation depends on the pruned `ds.PossibleAccessPaths`:
>   
>   * `pkg/planner/core/indexmerge_path.go:74`
>   * If hints exist but no IndexMerge paths were added, it returns **“IndexMerge is inapplicable”**:
>     
>     * `pkg/planner/core/indexmerge_path.go:108`
>   * This branch becomes reachable if pruning removed the hinted indexes before IndexMerge path generation.
> 
> **Plausible fix** When `ds.IndexMergeHints` is non-empty (or `ShouldPreferIndexMerge(ds)` is true), either:
> 
> 1. **Disable pruning** for that `DataSource`, **or**
> 2. **Explicitly retain** all access paths referenced/allowed by IndexMerge hints by actually populating
>    `indexMergeIndexPaths` in `pkg/planner/core/rule/rule_prune_indexes.go`, and ensuring those hinted paths
>    are excluded from the `maxToKeep` truncation.

Resolved in recent commits

File: pkg/planner/core/rule/collect_column_stats_usage.go [hunk 1]
```diff
@@ -199,19 +212,124 @@ func (c *columnStatsUsageCollector) collectPredicateColumnsForUnionAll(p *logica
 	}
 }
 
+// collectInterestingColumnsForDataSource collects all interesting columns (WHERE + JOIN + ORDERING) for a DataSource.
+// This unified collection simplifies the code by using a single map instead of three separate ones.
+func (c *columnStatsUsageCollector) collectInterestingColumnsForDataSource(ds *logicalop.DataSource, accumulatedJoinCols []*expression.Column, accumulatedOrderingCols []*expression.Column) {
+	c.colSet = make(map[int64]struct{})
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/rule/collect_column_stats_usage.go]: In next commit

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 2]
```diff
@@ -0,0 +1,431 @@
...
+	totalPathCount := len(paths)
+
+	// If totalPathCount <= threshold, we should keep all indexes with score > 0
+	// Which means only prune with score ==0
+	// Only prune with score > 0 when we have more index paths than the threshold
+	var maxToKeep int
+	if totalPathCount > threshold && threshold > 0 {
+		maxToKeep = max(threshold, defaultMaxIndexes) // Avoid being too aggressive when threshold is small
+	} else {
+		// When not pruning (len(paths) < threshold), set maxToKeep to keep all indexes with score > 0
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/rule/rule_prune_indexes.go]: In the next commit

File: pkg/planner/core/rule/rule_collect_plan_stats.go [hunk 3]
```diff
@@ -70,13 +72,23 @@ func (c *CollectPredicateColumnsPoint) Optimize(_ context.Context, plan base.Log
...
 	dependingVirtualCols := CollectDependingVirtualCols(tblID2TblInfo, histNeededColumns)
 
-	histNeededIndices := collectSyncIndices(plan.SCtx(), append(histNeededColumns, dependingVirtualCols...), tblID2TblInfo)
+	// Only pass keptIndexIDs if pruning actually occurred (map is not empty)
+	// If keptIndexIDs is empty, pass nil to collectSyncIndices to indicate no pruning occurred
+	var keptIndexIDsForCollection map[int64]map[int64]struct{}
+	if len(keptIndexIDs) > 0 {
+		keptIndexIDsForCollection = keptIndexIDs
+	}
+	histNeededIndices := collectSyncIndices(plan.SCtx(), append(histNeededColumns, dependingVirtualCols...), tblID2TblInfo, keptIndexIDsForCollection)
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_collect_plan_stats.go]: Passing an empty map instead of a Null seems simpler here. Then in `collectSyncIndices` we can use `if len(keptIndexIDs) > 0` to check whether it's empty.

File: pkg/planner/core/rule/collect_column_stats_usage.go [hunk 4]
```diff
@@ -322,10 +440,22 @@ func CollectColumnStatsUsage(lp base.LogicalPlan) (
...
+	collectIndexPruningCols := threshold >= 0
+
+	collector := newColumnStatsUsageCollector(lp.SCtx().GetSessionVars().IsPlanReplayerCaptureEnabled(), collectIndexPruningCols)
+	collector.collectFromPlan(nil, lp, nil, nil)
 	if collector.collectVisitedTable {
 		recordTableRuntimeStats(lp.SCtx(), collector.visitedtbls)
 	}
+
+	// Populate DataSource field with the collected interesting columns (if index pruning is enabled)
+	if collectIndexPruningCols {
```
Comment (qw4990) [inline pkg/planner/core/rule/collect_column_stats_usage.go:447]: My original thought was that we could make the `Index Pruning` a separate rule with its own `func (rule) Optimize(ctx, Plan)` function instead of being a part of the `Stats Usage`. 
But now it seems like `Index Pruning` needs to rely on `columnStatsCollector` to collect interesting columns, and notify `Stats Usage` to not collect pruned stats. 
So these 2 rules have certain dependencies and influences on each other. So it seems OK for me to implement `Index Pruning` as part of `Stats Usage` like this now.

File: pkg/planner/core/rule/rule_collect_plan_stats.go (hunk 3 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/rule_collect_plan_stats.go]: Will add it to the next commit. Thanks for the insightful review comment.

File: pkg/planner/core/rule/collect_column_stats_usage.go (hunk 4 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/collect_column_stats_usage.go:447]: Yes - I linked it to stats usage because of the dependency of stats collection for columns used in the query. What we determined (with @0xPoe's help) was that we determine the interesting columns for the query - and will sync load the statistics for those columns if they aren't already in the stats cache. But - any index that has other columns that aren't relevant to this query (but exist in the index) will result in it later issuing an async load for those columns. So we tied the index pruning and "interesting column determination for sync load" together.

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 5]
```diff
@@ -0,0 +1,431 @@
...
+
+	// Categorize each index path
+	for _, path := range paths {
+		if path.IsTablePath() {
+			tablePaths = append(tablePaths, path)
+			continue
+		}
+
+		// Always keep multi-value indexes (like table paths)
+		if path.Index != nil && path.Index.MVIndex {
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_prune_indexes.go:110]: It seems like Partial Indexes also should be treated as special indexes and always be kept. Please help check. @winoros

File: pkg/sessionctx/variable/sysvar.go [hunk 6]
```diff
@@ -326,6 +326,10 @@ var defaultSysVars = []*SysVar{
 		s.OptimizerSelectivityLevel = tidbOptPositiveInt32(val, vardef.DefTiDBOptimizerSelectivityLevel)
 		return nil
 	}},
+	{Scope: vardef.ScopeSession, Name: vardef.TiDBOptIndexPruneThreshold, Value: strconv.Itoa(vardef.DefTiDBOptIndexPruneThreshold), Type: vardef.TypeInt, MinValue: -1, MaxValue: math.MaxInt32, SetSession: func(s *SessionVars, val string) error {
```
Comment (qw4990) [inline pkg/sessionctx/variable/sysvar.go]: It only supports session-level right now, should we support global-level?

File: pkg/planner/core/rule/rule_prune_indexes.go (hunk 5 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/rule_prune_indexes.go:110]: Partial indexes do need to be pruned. Customers that have requested support for a very large number of indexes (and thus are the motivation for this PR) have indicated that they will include partial indexes in their table design.

File: pkg/planner/core/rule/collect_column_stats_usage.go [hunk 7]
```diff
@@ -199,19 +211,128 @@ func (c *columnStatsUsageCollector) collectPredicateColumnsForUnionAll(p *logica
...
+	if c.interestingColsByDS != nil {
+		switch x := lp.(type) {
+		case *logicalop.LogicalJoin:
+			// Extract join columns from EqualConditions and OtherConditions
+			for _, cond := range x.EqualConditions {
+				currentJoinCols = append(currentJoinCols, expression.ExtractColumns(cond)...)
+			}
+			for _, cond := range x.OtherConditions {
+				currentJoinCols = append(currentJoinCols, expression.ExtractColumns(cond)...)
+			}
```
Comment (fixdb) [inline pkg/planner/core/rule/collect_column_stats_usage.go]:
```suggestion
			currentJoinCols = append(currentJoinCols, expression.ExtractColumnsFromExpressions(x.EqualConditions, nil)...)
			currentJoinCols = append(currentJoinCols, expression.ExtractColumnsFromExpressions(x.OtherConditions, nil)...)
```

File: pkg/planner/core/rule/collect_column_stats_usage.go [hunk 8]
```diff
@@ -199,19 +211,128 @@ func (c *columnStatsUsageCollector) collectPredicateColumnsForUnionAll(p *logica
...
+			for _, item := range x.ByItems {
+				currentOrderingCols = append(currentOrderingCols, expression.ExtractColumns(item.Expr)...)
+			}
+		case *logicalop.LogicalTopN:
+			for _, item := range x.ByItems {
+				currentOrderingCols = append(currentOrderingCols, expression.ExtractColumns(item.Expr)...)
+			}
+		case *logicalop.LogicalWindow:
+			for _, item := range x.OrderBy {
+				currentOrderingCols = append(currentOrderingCols, expression.ExtractColumns(item.Col)...)
```
Comment (fixdb) [inline pkg/planner/core/rule/collect_column_stats_usage.go]: tem.Col is already Column type.
`currentOrderingCols = append(currentOrderingCols, item.Col)`

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 9]
```diff
@@ -0,0 +1,434 @@
...
+	// This prevents overly aggressive pruning when the threshold is small.
+	defaultMaxIndexes = 10
+)
+
+// indexWithScore stores an access path along with its coverage scores for ranking.
+type indexWithScore struct {
+	path                 *util.AccessPath
+	interestingCount     int     // Total number of interesting columns covered
+	consecutiveCount     int     // Consecutive interesting columns from start of index
+	consecutiveColumnIDs []int64 // IDs of consecutive columns (for detecting different orderings)
```
Comment (fixdb) [inline pkg/planner/core/rule/rule_prune_indexes.go:43]: consecutiveCount can be find from consecutiveColumnIDs, so this field is duplicate?

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 10]
```diff
@@ -0,0 +1,434 @@
...
+}
+
+// columnRequirements holds the column maps and totals needed for index pruning.
+type columnRequirements struct {
+	interestingColIDs map[int64]struct{}
+	totalColumns      int
```
Comment (fixdb) [inline pkg/planner/core/rule/rule_prune_indexes.go]: The number of elements can be found from interestingColIDs, so field totalColumns is not necessary?

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 11]
```diff
@@ -0,0 +1,434 @@
...
+		}
+		if a.isSingleScan != b.isSingleScan {
+			if a.isSingleScan {
+				return -1
+			}
+			return 1
+		}
+		if a.totalConsecutive == 1 && a.columns != b.columns {
+			return a.columns - b.columns
+		}
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_prune_indexes.go:343]: How to understand this comparison? Could you add some comments, thx!

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 12]
```diff
@@ -0,0 +1,434 @@
...
+		for _, entry := range preferredScored {
+			path := entry.info.path
+			if _, ok := added[path]; ok {
+				continue
+			}
+			if remaining == 0 {
+				break
+			}
+			// If we have at least 1 index with score > 0, don't append any with score == 0
+			if hasNonZeroScore && entry.score == 0 {
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_prune_indexes.go]: It seems like all zero-score indexes have been filtered out in `scoreAndSort`.
image

File: pkg/planner/core/rule/collect_column_stats_usage.go (hunk 7 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/collect_column_stats_usage.go]: Good suggestion. I had to add a conversion for the first however - otherwise it wouldn't compile. I also added your suggestion to the next branch of the switch:
currentJoinCols = append(currentJoinCols, expression.ExtractColumnsFromExpressions(expression.ScalarFuncs2Exprs(x.EqualConditions), nil)...)
			currentJoinCols = append(currentJoinCols, expression.ExtractColumnsFromExpressions(x.OtherConditions, nil)...)

File: pkg/planner/core/rule/collect_column_stats_usage.go (hunk 8 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/collect_column_stats_usage.go]: Good catch. Will be fixed in next commit.

File: pkg/planner/core/rule/rule_prune_indexes.go (hunk 11 above)
Comment (fixdb) [reply pkg/planner/core/rule/rule_prune_indexes.go:343]: When an index only matches 1 consecutive column from the query, it's a weak match. In this case, a smaller/narrower index is preferred because:
- Less storage overhead
- Less I/O during scans
- If the match is weak anyway, no point using a wide index

Comment (fixdb) [reply pkg/planner/core/rule/rule_prune_indexes.go:343]: Agree with @qw4990, a comment in the code will help future maintenance.

File: pkg/planner/core/rule/rule_prune_indexes.go (hunk 12 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/rule_prune_indexes.go]: Yes, that is correct. When this pruning is enabled - regardless of whether we have more plans than the variable setting - we will prune out any plans with a score == 0. This is because the optimizer will otherwise iterate through all indexes - and it causes problems with unnecessary async load because the sync load will not load statistics for columns that are not used in the query. But async load will try to load the statistics because we need to cost the index.

Comment (qw4990) [reply pkg/planner/core/rule/rule_prune_indexes.go]: OOK, make sense!

File: pkg/planner/core/rule/rule_collect_plan_stats.go [hunk 13]
```diff
@@ -189,6 +195,78 @@ func (*CollectPredicateColumnsPoint) markAtLeastOneFullStatsLoadForEachTable(
...
+}
+
+// pruneIndexesForDataSource prunes indexes for a single DataSource if needed.
+func pruneIndexesForDataSource(ds *logicalop.DataSource, keptIndexIDs map[int64]map[int64]struct{}) {
+	threshold := ds.SCtx().GetSessionVars().OptIndexPruneThreshold
+	// Early return if pruning is disabled (threshold < 0)
+	if threshold < 0 {
+		return
+	}
+	if len(ds.AllPossibleAccessPaths) <= 1 {
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_collect_plan_stats.go:230]: It seems like the only access path could be a table scan on the primary key, and we still need to load its stats for estimation. Please see the case below:
```
create table t (a int, b int, primary key(a));
select * from t where a<1;
```
In this case, we only have 1 access-path, which is a table scan on the primary key, and we need the sync-load to load its stats to make our estimation result accurate.

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 14]
```diff
@@ -0,0 +1,430 @@
...
+			orderingKey := buildOrderingKey(idxScore.consecutiveColumnIDs)
+			if len(idxScore.consecutiveColumnIDs) > 0 {
+				if _, seen := consecutiveOrderings[orderingKey]; !seen {
+					// This is a new ordering, keep it
+					preferredIndexes = append(preferredIndexes, idxScore)
+					consecutiveOrderings[orderingKey] = struct{}{}
+				} else {
+					// We've seen this ordering before, but still consider the index
+					// if it has good coverage or is a covering scan
+					if idxScore.interestingCount > 0 || path.IsSingleScan {
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_prune_indexes.go]: Is `idxScore.interestingCount > 0` unnecessary here? Since if `consecutiveColumnIDs` is larger than 0 then `interestingCount` should also be larger than 0?

File: pkg/sessionctx/variable/sysvar.go [hunk 15]
```diff
@@ -326,6 +326,10 @@ var defaultSysVars = []*SysVar{
 		s.OptimizerSelectivityLevel = tidbOptPositiveInt32(val, vardef.DefTiDBOptimizerSelectivityLevel)
 		return nil
 	}},
+	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.TiDBOptIndexPruneThreshold, Value: strconv.Itoa(vardef.DefTiDBOptIndexPruneThreshold), Type: vardef.TypeInt, MinValue: -1, MaxValue: math.MaxInt32, SetSession: func(s *SessionVars, val string) error {
```
Comment (qw4990) [inline pkg/sessionctx/variable/sysvar.go:329]: Should we also support `set_var` for this variable?

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 16]
```diff
@@ -0,0 +1,430 @@
...
+	req := buildColumnRequirements(interestingColumns)
+
+	totalPathCount := len(paths)
+
+	// If totalPathCount <= threshold, we should keep all indexes with score > 0
+	// Which means only prune with score ==0
+	// Only prune with score > 0 when we have more index paths than the threshold
+	// threshold = -1: disable pruning (handled by caller)
+	// threshold = 0: aggressive pruning, keep at least defaultMaxIndexes
+	// threshold > 0: keep at least threshold indexes (but at least defaultMaxIndexes)
```
Comment (winoros) [inline pkg/planner/core/rule/rule_prune_indexes.go:80]: Why don't we set the behavior of one of `threshold=-1/0` to prune all the indexes not related to interesting columns?

File: pkg/planner/core/rule/rule_collect_plan_stats.go (hunk 13 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/rule_collect_plan_stats.go:230]: Pantheon bot had the same recommendation. So I added code to address this in the latest commit - to search through the pruned paths and reinstate the common handle index if it was pruned.

File: pkg/planner/core/rule/rule_prune_indexes.go (hunk 16 above)
Comment (terry1purcell) [reply pkg/planner/core/rule/rule_prune_indexes.go:80]: That's a good suggestion. I think it makes sense for:
-1 : disable pruning
0 : only remove indexes with "zero" interesting columns
greater than 0 : remove indexes with zero interesting columns, and keep at least "threshold" indexes

File: pkg/planner/core/rule/rule_collect_plan_stats.go (hunk 13 above)
Comment (qw4990) [reply pkg/planner/core/rule/rule_collect_plan_stats.go:230]: Oh I saw it ... AI is really smart... This is a very detailed issue...
image

File: pkg/planner/core/rule/rule_prune_indexes.go (hunk 11 above)
Comment (qw4990) [reply pkg/planner/core/rule/rule_prune_indexes.go:343]: @fixdb Thanks for your explanation, that makes sense.

**Comment by qw4990** [comment]
A small supplement about the performance improvements of this PR. 
Asked AI to write a benchmark with 500 indexes – this PR can bring over 2x improvement to the optimizer in both time and memory overhead:
image

**Review by yudongusa — APPROVED** [review]
Please open a document PR on the session variable changes.

File: pkg/planner/core/rule/rule_prune_indexes.go (hunk 16 above)
Comment (winoros) [reply pkg/planner/core/rule/rule_prune_indexes.go:80]: Agree! Mark as resolved~

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 17]
```diff
@@ -0,0 +1,513 @@
...
+func buildFinalResult(tablePaths, mvIndexPaths, indexMergeIndexPaths []*util.AccessPath, preferredIndexes []indexWithScore, maxToKeep int, needPruning bool, req columnRequirements) []*util.AccessPath {
+	result := make([]*util.AccessPath, 0, defaultMaxIndexes)
+
+	// CRITICAL: Always include table paths - this is mandatory for correctness
+	result = append(result, tablePaths...)
+	// CRITICAL: Always include multi-value index paths - we do not have sufficient
+	// information to determine if they should be pruned in this function.
+	result = append(result, mvIndexPaths...)
+	// CRITICAL: Always include indexes specified in IndexMerge hints - index merge needs them to build partial paths
+	result = append(result, indexMergeIndexPaths...)
```
Comment (winoros) [inline pkg/planner/core/rule/rule_prune_indexes.go]:
```suggestion
	result := make([]*util.AccessPath, 0, len(tablePaths)+len(indexMergeIndexPaths)+len(preferredIndexes))

	// CRITICAL: Always include table paths - this is mandatory for correctness
	result = append(result, tablePaths...)
	// CRITICAL: Always include multi-value index paths - we do not have sufficient
	// information to determine if they should be pruned in this function.
	result = append(result, mvIndexPaths...)
	// CRITICAL: Always include indexes specified in IndexMerge hints - index merge needs them to build partial paths
	result = append(result, indexMergeIndexPaths...)
```

`defaultMaxIndexes` is the final capacity, but not the initial one.
So if we only preallocate the capacity by `defaultMaxIndexes`, the later appends will cause re-allocation on the slice.
`min(defaultMaxIndexes, len(tablePaths)+len(indexMergeIndexPaths)+len(preferredIndexes))` is the best answer, but I think directly passing the lengths' sum is acceptable.

Comment (terry1purcell) [reply pkg/planner/core/rule/rule_prune_indexes.go]: Implemented in next commit

**Review by winoros — APPROVED** [review]

File: pkg/planner/core/rule/collect_column_stats_usage.go [hunk 18]
```diff
@@ -199,19 +211,120 @@ func (c *columnStatsUsageCollector) collectPredicateColumnsForUnionAll(p *logica
 	}
 }
 
+// collectInterestingColumnsForDataSource collects all interesting columns (WHERE + JOIN + ORDERING + GROUP BY) for a DataSource.
+func (c *columnStatsUsageCollector) collectInterestingColumnsForDataSource(ds *logicalop.DataSource, accumulatedJoinCols []*expression.Column, accumulatedOrderingCols []*expression.Column) {
+	// Clear the map for reuse instead of allocating a new one
+	for k := range c.colSet {
+		delete(c.colSet, k)
+	}
```
Comment (0xPoe) [inline pkg/planner/core/rule/collect_column_stats_usage.go]:
```suggestion
	clear(c.colSet)
```

File: pkg/statistics/handle/handletest/handle_test.go [hunk 19]
```diff
@@ -1423,7 +1423,7 @@ func TestInitStatsLite(t *testing.T) {
 
 	// async stats load
 	tk.MustExec("set @@tidb_stats_load_sync_wait = 0")
-	tk.MustExec("explain select * from t where b > 1")
+	tk.MustExec("explain select * from t where b > 1 and c > 1")
```
Comment (0xPoe) [inline pkg/statistics/handle/handletest/handle_test.go]: Instead of adding `c` as a predicate column, I think it would be better to check if `c`'s stats are nil to ensure this new feature works well with asynchronous loading. I believe this is a good test case to catch future bugs.

File: pkg/statistics/handle/handletest/handle_test.go [hunk 20]
```diff
@@ -1440,7 +1440,7 @@ func TestInitStatsLite(t *testing.T) {
 
 	// sync stats load
 	tk.MustExec("set @@tidb_stats_load_sync_wait = 60000")
-	tk.MustExec("explain select * from t where c > 1")
+	tk.MustExec("explain select * from t where b > 1 and c > 1")
```
Comment (0xPoe) [inline pkg/statistics/handle/handletest/handle_test.go]: ditto

File: pkg/planner/core/stats_test.go [hunk 21]
```diff
@@ -0,0 +1,348 @@
+// Copyright 2025 PingCAP, Inc.
```
Comment (0xPoe) [inline pkg/planner/core/stats_test.go]:
```suggestion
// Copyright 2026 PingCAP, Inc.
```

File: pkg/planner/core/rule/rule_prune_indexes.go [hunk 22]
```diff
@@ -0,0 +1,513 @@
+// Copyright 2025 PingCAP, Inc.
```
Comment (0xPoe) [inline pkg/planner/core/rule/rule_prune_indexes.go]:
```suggestion
// Copyright 2026 PingCAP, Inc.
```

File: pkg/statistics/handle/handletest/handle_test.go (hunk 19 above)
Comment (0xPoe) [reply pkg/statistics/handle/handletest/handle_test.go]: We could also include this case to cover more logic with stats loading.
```go
func TestPrunedIndexesNoAsyncStatsLoadPartitioned(t *testing.T) {
	oriVal := config.GetGlobalConfig().Performance.LiteInitStats
	config.GetGlobalConfig().Performance.LiteInitStats = true
	defer func() {
		config.GetGlobalConfig().Performance.LiteInitStats = oriVal
	}()

	store, dom := testkit.CreateMockStoreAndDomain(t)
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("set @@tidb_partition_prune_mode = 'dynamic'")

	// Create a partitioned table with many indexes (more than 10 indexes starting with 'a'
	// to trigger pruning since defaultMaxIndexes = 10)
	tk.MustExec(`CREATE TABLE tp(
		a int, b int, c int, d int, e int, f int, g int, h int, i int, j int, k int, l int, m int,
		KEY ia (a), KEY iab (a, b), KEY iac (a, c), KEY iad (a, d),
		KEY iae (a, e), KEY iaf (a, f), KEY iag (a, g), KEY iah (a, h),
		KEY iai (a, i), KEY iaj (a, j), KEY iak (a, k), KEY ial (a, l), KEY iam (a, m),
		KEY ib (b), KEY ibc (b, c), KEY ibd (b, d), KEY ibe (b, e),
		KEY ic (c), KEY icd (c, d), KEY ice (c, e), KEY icf (c, f),
		KEY id (d), KEY ide (d, e), KEY idf (d, f),
		KEY ie (e), KEY ief (e, f),
		KEY if_idx (f)
	) PARTITION BY HASH(a) PARTITIONS 4`)
	tk.MustExec("insert into tp values (1,1,1,1,1,1,1,1,1,1,1,1,1),(2,2,2,2,2,2,2,2,2,2,2,2,2),(3,3,3,3,3,3,3,3,3,3,3,3,3),(4,4,4,4,4,4,4,4,4,4,4,4,4)")

	h := dom.StatsHandle()
	h.SetLease(time.Millisecond)
	defer func() {
		h.SetLease(0)
	}()

	is := dom.InfoSchema()
	tbl, err := is.TableByName(context.Background(), ast.NewCIStr("test"), ast.NewCIStr("tp"))
	require.NoError(t, err)
	tblInfo := tbl.Meta()

	// Build maps for index name to ID
	indexNameToID := make(map[string]int64)
	for _, idx := range tblInfo.Indices {
		indexNameToID[idx.Name.L] = idx.ID
	}

	tk.MustExec("analyze table tp with 2 topn, 2 buckets")

	// Check all stats are evicted initially
	globalStats0 := h.GetPhysicalTableStats(tblInfo.ID, tblInfo)
	checkAllEvicted(t, globalStats0)

	h.Clear()
	require.NoError(t, h.InitStatsLite(context.Background()))

	// After InitStatsLite, check global stats are evicted
	globalStats1 := h.GetPhysicalTableStats(tblInfo.ID, tblInfo)
	checkAllEvicted(t, globalStats1)
	require.Equal(t, int(statistics.Version2), globalStats1.StatsVer)

	// Enable async stats load and aggressive index pruning
	tk.MustExec("set @@tidb_stats_load_sync_wait = 0")
	tk.MustExec("set @@tidb_opt_index_prune_threshold = 1")

	// Run a query that only uses column 'a'
	tk.MustExec("explain select * from tp where a > 1")
	require.NoError(t, h.LoadNeededHistograms(is))

	// Check which indexes have stats loaded (using global stats in dynamic mode)
	globalStats2 := h.GetPhysicalTableStats(tblInfo.ID, tblInfo)

	// Count how many indexes starting with 'a' are loaded vs pruned
	// We have 13 indexes starting with 'a': ia, iab, iac, iad, iae, iaf, iag, iah, iai, iaj, iak, ial, iam
	// With threshold=1 and defaultMaxIndexes=10, at most 10 can be kept
	allAIndexes := []string{"ia", "iab", "iac", "iad", "iae", "iaf", "iag", "iah", "iai", "iaj", "iak", "ial", "iam"}
	loadedCount := 0
	prunedCount := 0
	for _, idxName := range allAIndexes {
		idxID := indexNameToID[idxName]
		idxStats := globalStats2.GetIdx(idxID)
		if idxStats != nil && idxStats.IsFullLoad() {
			loadedCount++
			t.Logf("index %s (id=%d) is loaded", idxName, idxID)
		} else {
			prunedCount++
			t.Logf("index %s (id=%d) is pruned (not loaded)", idxName, idxID)
		}
	}

	// With 13 indexes and maxToKeep=10, some must be pruned
	require.Greater(t, loadedCount, 0, "at least some indexes starting with 'a' should be loaded")
	require.Greater(t, prunedCount, 0, "at least some indexes starting with 'a' should be pruned (we have 13 but maxToKeep=10)")
	require.LessOrEqual(t, loadedCount, 10, "at most 10 indexes can be kept due to defaultMaxIndexes")

	// Indexes NOT starting with 'a' should NOT be loaded (they were pruned due to no coverage)
	for _, idxName := range []string{"ib", "ibc", "ibd", "ibe", "ic", "icd", "ice", "icf", "id", "ide", "idf", "ie", "ief", "if_idx"} {
		idxID := indexNameToID[idxName]
		idxStats := globalStats2.GetIdx(idxID)
		require.Nil(t, idxStats, "index %s (id=%d) should NOT be loaded (was pruned)", idxName, idxID)
	}
}

```

File: pkg/sessionctx/variable/sysvar.go (hunk 15 above)
Comment (0xPoe) [inline pkg/sessionctx/variable/sysvar.go:329]: Should we set the MinValue to defaultMaxIndexes here?

File: pkg/statistics/handle/handletest/handle_test.go (hunk 19 above)
Comment (0xPoe) [reply pkg/statistics/handle/handletest/handle_test.go]: For non-partitioned table:
```go
func TestPrunedIndexesNoAsyncStatsLoad(t *testing.T) {
	oriVal := config.GetGlobalConfig().Performance.LiteInitStats
	config.GetGlobalConfig().Performance.LiteInitStats = true
	defer func() {
		config.GetGlobalConfig().Performance.LiteInitStats = oriVal
	}()

	store, dom := testkit.CreateMockStoreAndDomain(t)
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")

	// Create a table with many indexes (more than 10 indexes starting with 'a'
	// to trigger pruning since defaultMaxIndexes = 10)
	tk.MustExec(`CREATE TABLE t(
		a int, b int, c int, d int, e int, f int, g int, h int, i int, j int, k int, l int, m int,
		KEY ia (a), KEY iab (a, b), KEY iac (a, c), KEY iad (a, d),
		KEY iae (a, e), KEY iaf (a, f), KEY iag (a, g), KEY iah (a, h),
		KEY iai (a, i), KEY iaj (a, j), KEY iak (a, k), KEY ial (a, l), KEY iam (a, m),
		KEY ib (b), KEY ibc (b, c), KEY ibd (b, d), KEY ibe (b, e),
		KEY ic (c), KEY icd (c, d), KEY ice (c, e), KEY icf (c, f),
		KEY id (d), KEY ide (d, e), KEY idf (d, f),
		KEY ie (e), KEY ief (e, f),
		KEY if_idx (f)
	)`)
	tk.MustExec("insert into t values (1,1,1,1,1,1,1,1,1,1,1,1,1),(2,2,2,2,2,2,2,2,2,2,2,2,2),(3,3,3,3,3,3,3,3,3,3,3,3,3),(4,4,4,4,4,4,4,4,4,4,4,4,4)")

	h := dom.StatsHandle()
	h.SetLease(time.Millisecond)
	defer func() {
		h.SetLease(0)
	}()

	is := dom.InfoSchema()
	tbl, err := is.TableByName(context.Background(), ast.NewCIStr("test"), ast.NewCIStr("t"))
	require.NoError(t, err)
	tblInfo := tbl.Meta()

	// Build maps for index name to ID
	indexNameToID := make(map[string]int64)
	for _, idx := range tblInfo.Indices {
		indexNameToID[idx.Name.L] = idx.ID
	}

	tk.MustExec("analyze table t with 2 topn, 2 buckets")

	// Check all stats are evicted initially
	tblStats0 := h.GetPhysicalTableStats(tblInfo.ID, tblInfo)
	checkAllEvicted(t, tblStats0)

	h.Clear()
	require.NoError(t, h.InitStatsLite(context.Background()))

	// After InitStatsLite, check stats are evicted
	tblStats1 := h.GetPhysicalTableStats(tblInfo.ID, tblInfo)
	checkAllEvicted(t, tblStats1)
	require.Equal(t, int(statistics.Version2), tblStats1.StatsVer)

	// Enable async stats load and aggressive index pruning
	tk.MustExec("set @@tidb_stats_load_sync_wait = 0")
	tk.MustExec("set @@tidb_opt_index_prune_threshold = 1")

	// Run a query that only uses column 'a'
	tk.MustExec("explain select * from t where a > 1")
	require.NoError(t, h.LoadNeededHistograms(is))

	// Check which indexes have stats loaded
	tblStats2 := h.GetPhysicalTableStats(tblInfo.ID, tblInfo)

	// Count how many indexes starting with 'a' are loaded vs pruned
	// We have 13 indexes starting with 'a': ia, iab, iac, iad, iae, iaf, iag, iah, iai, iaj, iak, ial, iam
	// With threshold=1 and defaultMaxIndexes=10, at most 10 can be kept
	allAIndexes := []string{"ia", "iab", "iac", "iad", "iae", "iaf", "iag", "iah", "iai", "iaj", "iak", "ial", "iam"}
	loadedCount := 0
	prunedCount := 0
	for _, idxName := range allAIndexes {
		idxID := indexNameToID[idxName]
		idxStats := tblStats2.GetIdx(idxID)
		if idxStats != nil && idxStats.IsFullLoad() {
			loadedCount++
			t.Logf("index %s (id=%d) is loaded", idxName, idxID)
		} else {
			prunedCount++
			t.Logf("index %s (id=%d) is pruned (not loaded)", idxName, idxID)
		}
	}

	// With 13 indexes and maxToKeep=10, some must be pruned
	require.Greater(t, loadedCount, 0, "at least some indexes starting with 'a' should be loaded")
	require.Greater(t, prunedCount, 0, "at least some indexes starting with 'a' should be pruned (we have 13 but maxToKeep=10)")
	require.LessOrEqual(t, loadedCount, 10, "at most 10 indexes can be kept due to defaultMaxIndexes")

	// Indexes NOT starting with 'a' should NOT be loaded (they were pruned due to no coverage)
	for _, idxName := range []string{"ib", "ibc", "ibd", "ibe", "ic", "icd", "ice", "icf", "id", "ide", "idf", "ie", "ief", "if_idx"} {
		idxID := indexNameToID[idxName]
		idxStats := tblStats2.GetIdx(idxID)
		require.Nil(t, idxStats, "index %s (id=%d) should NOT be loaded (was pruned)", idxName, idxID)
	}
}
```

**Comment by 0xPoe** [comment]
This test couldn't pass:
```go

func TestPrunedIndexesNoAsyncStatsLoadPartitionedStatic(t *testing.T) {
        oriVal := config.GetGlobalConfig().Performance.LiteInitStats
        config.GetGlobalConfig().Performance.LiteInitStats = true
        defer func() {
                config.GetGlobalConfig().Performance.LiteInitStats = oriVal
        }()
        store, dom := testkit.CreateMockStoreAndDomain(t)
        tk := testkit.NewTestKit(t, store)
        tk.MustExec("use test")
        tk.MustExec("set @@tidb_partition_prune_mode = 'static'")
        // Create a partitioned table with many indexes (more than 10 indexes starting with 'a'
        // to trigger pruning since defaultMaxIndexes = 10)
        tk.MustExec(`CREATE TABLE tp(
                a int, b int, c int, d int, e int, f int, g int, h int, i int, j int, k int, l int, m int,
                KEY ia (a), KEY iab (a, b), KEY iac (a, c), KEY iad (a, d),
                KEY iae (a, e), KEY iaf (a, f), KEY iag (a, g), KEY iah (a, h),
                KEY iai (a, i), KEY iaj (a, j), KEY iak (a, k), KEY ial (a, l), KEY iam (a, m),
                KEY ib (b), KEY ibc (b, c), KEY ibd (b, d), KEY ibe (b, e),
                KEY ic (c), KEY icd (c, d), KEY ice (c, e), KEY icf (c, f),
                KEY id (d), KEY ide (d, e), KEY idf (d, f),
                KEY ie (e), KEY ief (e, f),
                KEY if_idx (f)
        ) PARTITION BY HASH(a) PARTITIONS 4`)
        tk.MustExec("insert into tp values (1,1,1,1,1,1,1,1,1,1,1,1,1),(2,2,2,2,2,2,2,2,2,2,2,2,2),(3,3,3,3,3,3,3,3,3,3,3,3,3),(4,4,4,4,4,4,4,4,4,4,4,4,4)")
        h := dom.StatsHandle()
        h.SetLease(time.Millisecond)
        defer func() {
                h.SetLease(0)
        }()
        is := dom.InfoSchema()
        tbl, err := is.TableByName(context.Background(), ast.NewCIStr("test"), ast.NewCIStr("tp"))
        require.NoError(t, err)
        tblInfo := tbl.Meta()
        // Build maps for index name to ID
        indexNameToID := make(map[string]int64)
        for _, idx := range tblInfo.Indices {
                indexNameToID[idx.Name.L] = idx.ID
        }
        // Get partition IDs
        pi := tblInfo.GetPartitionInfo()
        require.NotNil(t, pi)
        partitionIDs := make([]int64, 0, len(pi.Definitions))
        for _, def := range pi.Definitions {
                partitionIDs = append(partitionIDs, def.ID)
        }
        tk.MustExec("analyze table tp with 2 topn, 2 buckets")
        // Check all partition stats are evicted initially
        for _, pid := range partitionIDs {
                partStats := h.GetPhysicalTableStats(pid, tblInfo)
                checkAllEvicted(t, partStats)
        }
        h.Clear()
        require.NoError(t, h.InitStatsLite(context.Background()))
        // After InitStatsLite, check partition stats are evicted
        for _, pid := range partitionIDs {
                partStats := h.GetPhysicalTableStats(pid, tblInfo)
                checkAllEvicted(t, partStats)
                require.Equal(t, int(statistics.Version2), partStats.StatsVer)
        }
        // Enable async stats load and aggressive index pruning
        tk.MustExec("set @@tidb_stats_load_sync_wait = 0")
        tk.MustExec("set @@tidb_opt_index_prune_threshold = 1")
        // Run a query that only uses column 'a'
        tk.MustExec("explain select * from tp where a > 1")
        require.NoError(t, h.LoadNeededHistograms(is))
        // In static mode, check partition stats
        // Note: In static mode, each partition is processed separately, so the pruning behavior
        // may differ from dynamic mode. The key verification is that indexes not containing 'a'
        // should not be loaded regardless of mode.
        allAIndexes := []string{"ia", "iab", "iac", "iad", "iae", "iaf", "iag", "iah", "iai", "iaj", "iak", "ial", "iam"}
        for _, pid := range partitionIDs {
                partStats := h.GetPhysicalTableStats(pid, tblInfo)
                loadedCount := 0
                for _, idxName := range allAIndexes {
                        idxID := indexNameToID[idxName]
                        idxStats := partStats.GetIdx(idxID)
                        if idxStats != nil && idxStats.IsFullLoad() {
                                loadedCount++
                                t.Logf("partition %d: index %s (id=%d) is loaded", pid, idxName, idxID)
                        } else {
                                t.Logf("partition %d: index %s (id=%d) is pruned (not loaded)", pid, idxName, idxID)
                        }
                }
                // At least some indexes starting with 'a' should be loaded
                require.Greater(t, loadedCount, 0, "partition %d: at least some indexes starting with 'a' should be loaded", pid)
                // Indexes NOT starting with 'a' should NOT be loaded (they were pruned due to no coverage)
                for _, idxName := range []string{"ib", "ibc", "ibd", "ibe", "ic", "icd", "ice", "icf", "id", "ide", "idf", "ie", "ief", "if_idx"} {
                        idxID := indexNameToID[idxName]
                        idxStats := partStats.GetIdx(idxID)
                        require.Nil(t, idxStats, "partition %d: index %s (id=%d) should NOT be loaded (was pruned)", pid, idxName, idxID)
                }
        }
}```

File: pkg/sessionctx/variable/sysvar.go (hunk 15 above)
Comment (terry1purcell) [reply pkg/sessionctx/variable/sysvar.go:329]: I don't think we should. Because we allow -1 (to disable) and 0 (to only prune score == 0 indexes).

Comment (0xPoe) [reply pkg/sessionctx/variable/sysvar.go:329]: Oh, I see. We can use `Validation` to ensure that users cannot set the value lower than `defaultMaxIndexes`. Otherwise, it would be very confusing. Additionally, we could include `-1 (to disable)` and `0 (to only prune score == 0 indexes)` in the error message as a helpful tip.

Comment (terry1purcell) [reply pkg/sessionctx/variable/sysvar.go:329]: I will add a comment related to a "TODO" item for this defaultMaxIndexes. My goal is that this early pruning does a "first pass", and we later add a 2nd round of pruning where we have more information. If a customer was to set this to a low value - such as 5, then we want this first pass NOT to be too aggressive and keep a minimum number of plans (such as 10), and the later process prunes further. I will add this comment in the next commit.

File: pkg/statistics/handle/handletest/handle_test.go (hunk 19 above)
Comment (terry1purcell) [reply pkg/statistics/handle/handletest/handle_test.go]: Added to latest commit
