### PR TITLE
executor: fix data race on TestPrepareCacheForPartition 

### LINKED ISSUE #15222: unit test TestDataForTableStatsField fails
infoschema_reader_test.go:testInfoschemaTableSuite.TestDataForTableStatsField

## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
[2020-03-09T06:13:08.055Z] FAIL: infoschema_reader_test.go:211: testInfoschemaTableSuite.TestDataForTableStatsField

[2020-03-09T06:13:08.055Z] 

[2020-03-09T06:13:08.055Z] infoschema_reader_test.go:257:

[2020-03-09T06:13:08.055Z]     tk.MustQuery("select table_rows, avg_row_length, data_length, index_length from information_schema.tables where table_name='t'").Check(

[2020-03-09T06:13:08.055Z]         testkit.Rows("3 18 54 6"))

[2020-03-09T06:13:08.055Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:62:

[2020-03-09T06:13:08.056Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)

[2020-03-09T06:13:08.056Z] ... obtained string = "[0 0 0 0]\n"

[2020-03-09T06:13:08.056Z] ... expected string = "[3 18 54 6]\n"

[2020-03-09T06:13:08.056Z] ... sql:select table_rows, avg_row_length, data_length, index_length from information_schema.tables where table_name='t', args:[]

```

It's introduced in https://github.com/pingcap/tidb/pull/15208

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Seen at https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/26675/pipeline
in PR https://github.com/pingcap/tidb/pull/15098#issuecomment-596348934

### LINKED ISSUE #15226: data race detected in TestPartitionsTable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
[2020-03-09T07:54:30.935Z] ==================

[2020-03-09T07:54:30.935Z] WARNING: DATA RACE

[2020-03-09T07:54:30.935Z] Write at 0x000005669660 by goroutine 537:

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestPartitionsTable()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:263 +0x6e

[2020-03-09T07:54:30.935Z]   runtime.call32()

[2020-03-09T07:54:30.935Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-03-09T07:54:30.935Z]   reflect.Value.Call()

[2020-03-09T07:54:30.935Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-03-09T07:54:30.935Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-03-09T07:54:30.935Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-03-09T07:54:30.935Z] 

[2020-03-09T07:54:30.935Z] Previous read at 0x000005669660 by goroutine 572:

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.(*statsCache).get()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:203 +0xb9

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.(*memtableRetriever).dataForTables()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:273 +0x7c

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.(*memtableRetriever).retrieve()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:60 +0x999

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:69 +0xc6

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:213 +0x167

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.(*SelectionExec).Next()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1141 +0x6e5

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:213 +0x167

[2020-03-09T07:54:30.935Z]   github.com/pingcap/tidb/executor.(*projectionInputFetcher).run()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:368 +0x41c

[2020-03-09T07:54:30.935Z] 

[2020-03-09T07:54:30.935Z] Goroutine 537 (running) created at:

[2020-03-09T07:54:30.935Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-03-09T07:54:30.935Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-03-09T07:54:30.935Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-03-09T07:54:30.935Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-03-09T07:54:30.935Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7

[2020-03-09T07:54:30.935Z] 

[2020-03-09T07:54:30.935Z] Goroutine 572 (running) created at:

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).prepare()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:263 +0xd07

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).parallelExecute()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:200 +0x5b7

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Next()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:173 +0x107

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:213 +0x167

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:126 +0x110

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/session.GetRows4Test()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:330 +0x35a

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/session.ResultSetToStringSlice()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:348 +0xb8

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResultWithCtx()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:287 +0xa8

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:282 +0x4e4

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).TestAlterTableComment()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:2935 +0x1a8

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).TestAlterTableComment()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:2934 +0x174

[2020-03-09T07:54:30.936Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).TestAlterTableComment()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:2933 +0x140

[2020-03-09T07:54:30.936Z]   runtime.call32()

[2020-03-09T07:54:30.936Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-03-09T07:54:30.936Z]   reflect.Value.Call()

[2020-03-09T07:54:30.936Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-03-09T07:54:30.936Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-03-09T07:54:30.936Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-03-09T07:54:30.936Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-03-09T07:54:30.936Z] ==================

```

It's introduced in #15208

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Seen at https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/26695/pipeline/ in https://github.com/pingcap/tidb/pull/15098#issuecomment-596381081

### PR DESCRIPTION
**Pull request by reafans**
### What problem does this PR solve? 
fix #15226 , fix #15222

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### CODE REVIEW

File: executor/infoschema_reader_test.go [hunk 1]
```diff
@@ -208,7 +209,11 @@ func (s *testInfoschemaTableSuite) TestUserPrivileges(c *C) {
 	c.Assert(len(result.Rows()), Greater, 0)
 }
 
+// mu is used to test DataForTableStatsField and PartitionsTable serially
+var mu sync.Mutex
```
Comment (lonng) [inline executor/infoschema_reader_test.go]: It's better to restrict the scope of the variable. I think we can put it in suite.

Comment (reafans) [reply executor/infoschema_reader_test.go]: great!
