### PR TITLE
executor: implemented exclusive lock for temp storage dir per tidb instance

### LINKED ISSUE #13981: multiple instances of tidb-server may use the same temporary directory
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Multiple instances of tidb-server may use the same temporary directy.
See https://github.com/pingcap/tidb/blob/0e0faeeb30c340e3dc091aaba01c336427a38f3c/util/chunk/disk.go#L47, if two of `tidb-server`s have same instance name but in different directory, each of them will share the same folder and the next start of one instance will  remove this directory so that another instance may face unexpected problem.

2. What did you expect to see?

- different instances in on node use different directories.
- if one tidb-server uses a temporary directory which another is in use, it should panic.
- When tidb-server starts, find a way to safely remove the temporary directory created when it last starts.
- We need ensure that `tidb-server` instance has the READ/WRITE privilege for the directory, otherwise, panic when starts up.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

4.0.0-alpha

### PR DESCRIPTION
**Pull request by hsqlu**
### What problem does this PR solve? 

fixes #13981 

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)

run tidb-server using the default config 
```shell
➜  tidb git:(exclusive-temp-dir-access) ./bin/tidb-server 
......
[2020/03/08 12:34:24.375 +13:00] [INFO] [delete_range.go:133] ["[ddl] start delRange emulator"]                                      │
[2020/03/08 12:34:24.375 +13:00] [INFO] [ddl_worker.go:130] ["[ddl] start DDL worker"] [worker="worker 1, tp general"]               │
[2020/03/08 12:34:24.375 +13:00] [INFO] [ddl_worker.go:130] ["[ddl] start DDL worker"] [worker="worker 2, tp add index"]             │
[2020/03/08 12:34:24.381 +13:00] [INFO] [domain.go:144] ["full load InfoSchema success"] [usedSchemaVersion=0] [neededSchemaVersion=2│
2] ["start time"=5.728701ms]                                                                                                         │
[2020/03/08 12:34:24.381 +13:00] [INFO] [domain.go:368] ["full load and reset schema validator"]                                     │
[2020/03/08 12:34:24.389 +13:00] [INFO] [server.go:217] ["secure connection is enabled"] ["client verification enabled"=false]       │
[2020/03/08 12:34:24.389 +13:00] [INFO] [server.go:231] ["server is running MySQL protocol"] [addr=0.0.0.0:4000]                     │
[2020/03/08 12:34:24.390 +13:00] [INFO] [http_status.go:266] ["for status and metrics report"] ["listening on addr"=0.0.0.0:10080]   │
[2020/03/08 12:34:24.390 +13:00] [INFO] [domain.go:1015] ["init stats info time"] ["take time"=2.268267ms]    
```

run another tidb-server on the same machine using the default config
```shell
➜  tidb git:(exclusive-temp-dir-access) ✗ ./bin/tidb-server 
acquire the lock of temp storage dir err: fslock: lock is held
```

Code changes
- Has imported new dependency [`github.com/danjacques/gofslock`](https://github.com/danjacques/gofslock)

### CODE REVIEW

File: tidb-server/main.go [hunk 1]
```diff
@@ -188,6 +191,21 @@ func syncLog() {
 	}
 }
 
+func acquireTempDirLock() {
```
Comment (SunRunAway) [inline tidb-server/main.go]: Could this function be named as `initializeTempDir` and do initialization and lock mechanism together here?

Comment (hsqlu) [reply tidb-server/main.go]: Since we have clean the temp storage path before we first use it, so I make it as a sub-directory of the setting `tmp-storage-path`. PTAL

**Comment by hsqlu** [comment]
> LGTM

After changed, the temp storage dir won't be initialized during unit-test running. Is there a good way to resolve this?

**Comment by SunRunAway** [comment]
> > LGTM
> 
> After changed, the temp storage dir won't be initialized during unit-test running. Is there a good way to resolve this?

Yes, LGTM. Thank you.

File: tidb-server/main.go [hunk 2]
```diff
@@ -188,6 +191,36 @@ func syncLog() {
...
+	tempDir := config.GetGlobalConfig().TempStoragePath
+	lockFile := "_dir.lock"
+	_, err := os.Stat(tempDir)
+	if err != nil && !os.IsExist(err) {
+		err = os.MkdirAll(tempDir, 0755)
+		terror.MustNil(err)
+	}
+	tempDirLock, err = fslock.Lock(filepath.Join(tempDir, lockFile))
+	if err != nil {
+		fmt.Fprintln(os.Stderr, "acquire the lock of temp storage dir err:", err)
```
Comment (zz-jason) [inline tidb-server/main.go]: Please use a more user friendly error, a good error message should describe:
1. What's the error(keep it short, use plain language, leave the techno-jargon out)?
2. What's the workaround?

File: tidb-server/main.go [hunk 3]
```diff
@@ -161,6 +163,7 @@ func main() {
 	registerStores()
 	registerMetrics()
 	config.InitializeConfig(*configPath, *configCheck, *configStrict, reloadConfig, overrideConfig)
+	initializeTempDir()
```
Comment (zz-jason) [inline tidb-server/main.go]: we only need to initialize the temp storage directory when `oom-use-tmp-storage` is set to true. we should check the value before calling this function.

**Comment by XuHuaiyu** [comment]
@SunRunAway After this, a physical machine is not allowed to start multiple tidb-server instances if `oom-use-tmp-storage` are set? Is this acceptable?

**Comment by SunRunAway** [comment]
> @SunRunAway After this, a physical machine is not allowed to start multiple tidb-server instances if `oom-use-tmp-storage` are set? Is this acceptable?

Not exactly. Multiple `tidb-server` instances can serve on one machine if you specify exclusive temporary directoreis for each instance.

File: tidb-server/main.go (hunk 2 above)
Comment (SunRunAway) [reply tidb-server/main.go]: And it's better to add troubleshooting instructions [here](https://github.com/pingcap/docs/blob/master/faq/tidb.md#tidb-custom-error-messages)

**Comment by hsqlu** [comment]
PTAL @SunRunAway @zz-jason

**Comment by hsqlu** [comment]
@zz-jason @SunRunAway Hi, you may have to change some config/CI scripts to resolve the multi-instances lunch on single node issue?

**Comment by SunRunAway** [comment]
After reconsideration, it would be better to set the default temporary directory according to the port number, so that the current deploy method would not be affected.

The current default directory is `<TMPDIR>/tidb/tmp-storage`
A suggestion is changing it to `<TMPDIR>/tidb/<url_safe_base64(port+status-port)>/tmp-storage`
Thus, multiple instace of `tidb-server` would start sucessfully without explicitly setting the `tmp-storage-path`.

**Comment by hsqlu** [comment]
> After reconsideration, it would be better to set the default temporary directory according to the port number, so that the current deploy method would not be affected.
> 
> The current default directory is `<TMPDIR>/tidb/tmp-storage`.
> A suggestion is changing it to `<TMPDIR>/tidb/<url_safe_base64(port+status-port)>/tmp-storage`
> Thus, multiple instaces of `tidb-server` would start sucessfully without explicitly setting the `tmp-storage-path`.
> 
> Here's an example code, https://play.golang.org/p/-lal0rICqbo

So after change the direction, should we still keep using the exclusive lock for that temp-dir?

**Comment by hsqlu** [comment]
Can anyone have a look what's wrong with the common-test/integration-common-test?

@SunRunAway @zz-jason 

```
[2020-03-29T09:48:44.049Z] 2020/03/29 17:48:43.823  [fatal] run test [role] err: sql:SHOW GRANTS FOR `root`@`localhost` USING `replication`;: failed to run query 

[2020-03-29T09:48:44.049Z] "SHOW GRANTS FOR `root`@`localhost` USING `replication`;" 

[2020-03-29T09:48:44.049Z]  around line 219, 

[2020-03-29T09:48:44.049Z] we need(122):

[2020-03-29T09:48:44.049Z] SHOW GRANTS FOR `root`@`localhost` USING `replication`;

[2020-03-29T09:48:44.049Z] Error 1044: Access denied for user 'joe'@'localhost' to database '

[2020-03-29T09:48:44.049Z] but got(122):

[2020-03-29T09:48:44.049Z] SHOW GRANTS FOR `root`@`localhost` USING `replication`;

[2020-03-29T09:48:44.049Z] Error 3530: `replication`@`%` is is not granted to root@localhost

[2020-03-29T09:48:44.049Z] 

[2020-03-29T09:48:44.049Z] 

[2020-03-29T09:48:44.049Z] + echo 'tidb-server(PID: 27632) stopped'

[2020-03-29T09:48:44.049Z] tidb-server(PID: 27632) stopped

```

**Comment by zz-jason** [comment]
Hi @hsqlu, we have a test framework modification recently, hope it would pass now. Sorry for the inconvenient.

File: config/config.go [hunk 4]
```diff
@@ -123,6 +130,19 @@ type Config struct {
 	EnableDynamicConfig bool `toml:"enable-dynamic-config" json:"enable-dynamic-config"`
 }
 
+// UpdateTempStoragePath is to update the `TempStoragePath` if port/statusPort was changed
+// and the `tmp-storage-path` was not specified in the conf.toml or was specified the same as the default value.
+func (c *Config) UpdateTempStoragePath() {
+	if c.TempStoragePath == tempStorageDirName {
```
Comment (SunRunAway) [inline config/config.go]: I think this check is redundant.

File: tidb-server/main.go [hunk 5]
```diff
@@ -161,6 +164,9 @@ func main() {
 	registerStores()
 	registerMetrics()
 	config.InitializeConfig(*configPath, *configCheck, *configStrict, reloadConfig, overrideConfig)
+	if config.GetGlobalConfig().OOMUseTmpStorage {
+		initializeTempDir()
```
Comment (SunRunAway) [inline tidb-server/main.go]: `UpdateTempStoragePath` should be called here before `initializeTempDir`.

File: tidb-server/main.go [hunk 6]
```diff
@@ -391,6 +433,7 @@ func overrideConfig(cfg *config.Config) {
 		p, err = strconv.Atoi(*port)
 		terror.MustNil(err)
 		cfg.Port = uint(p)
+		cfg.UpdateTempStoragePath()
```
Comment (SunRunAway) [inline tidb-server/main.go]: If `tidb-server` starts without command-line argument, `UpdateTempStoragePath` may never be called.

File: config/config.go (hunk 4 above)
Comment (hsqlu) [reply config/config.go]: If the TempStoragePath was specified in the config file, UndateTempStoragePath() will override the customized `tmp-storage-path` value without this check. Am I right?

Comment (SunRunAway) [reply config/config.go]: Make sense. Thanks for your explanation.

**Comment by hsqlu** [comment]
@SunRunAway @zz-jason  PTAL

File: config/config.toml.example [hunk 7]
```diff
@@ -38,9 +38,9 @@ mem-quota-query = 1073741824
 oom-use-tmp-storage = true
 
 # Specifies the temporary storage path for some operators when a single SQL statement exceeds the memory quota specified by mem-quota-query.
-# It defaults to `<TMPDIR>/tidb/tmp-storage` if it is unset.
+# It defaults to `<TMPDIR>/tidb/<url_safe_base64(port+status-port)>/tmp-storage` if it is unset. The port and status-port will be concatenated by '/', like `4000/10080`.
```
Comment (SunRunAway) [inline config/config.toml.example:41]:
```suggestion
# It defaults to a generated directory in `<TMPDIR>/tidb/` if it is unset.
```

File: config/config.go [hunk 8]
```diff
@@ -123,6 +130,19 @@ type Config struct {
...
+		c.TempStoragePath = encodeDefTempStorageDir(c.Port, c.Status.StatusPort)
+	}
+}
+
+func encodeDefTempStorageDir(port, statusPort uint) string {
+	dirName := base64.URLEncoding.EncodeToString([]byte(fmt.Sprintf("%v/%v", port, statusPort)))
+	return filepath.Join(os.TempDir(), dirName, "tidb", "tmp-storage")
```
Comment (SunRunAway) [inline config/config.go:143]:
```suggestion
	return filepath.Join(os.TempDir(), "tidb", dirName, "tmp-storage")
```

File: config/config.toml.example [hunk 9]
```diff
@@ -38,9 +38,9 @@ mem-quota-query = 1073741824
...
 # It only takes effect when `oom-use-tmp-storage` is `true`.
-# tmp-storage-path = "/tmp/tidb/tmp-storage"
+# tmp-storage-path = "<TMPDIR>/tidb/<url_safe_base64(port+status-port)>/tmp-storage"
```
Comment (SunRunAway) [inline config/config.toml.example:43]:
```suggestion
# tmp-storage-path = "/tmp/tidb/NDAwMC8xMDA4MA==/tmp-storage"
```

File: tidb-server/main.go [hunk 10]
```diff
@@ -391,6 +434,7 @@ func overrideConfig(cfg *config.Config) {
...
```
[the remark this answers is not in the document]
Comment (hsqlu) [reply tidb-server/main.go]: Sorry, committed by mistake.

**Comment by hsqlu** [comment]
@SunRunAway PTAL

**Comment by SunRunAway** [comment]
@zz-jason Please take another look.
