### PR TITLE
expression: fix the return type of `coalesce` when arg type is `DATE`

### LINKED ISSUE #46475: The result of comparison function on date value should return DATE type
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
bash$ mysql --column-type-info

mysql> select coalesce(current_date(),null) from dual;
```

### 2. What did you expect to see? (Required)

```
Field   1:  `coalesce(current_date(),null)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       DATE
...
```
### 3. What did you see instead (Required)

```
Field   1:  `coalesce(current_date(),null)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       DATETIME
...
```

### 4. What is your TiDB version? (Required)
v6.6.0

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #46475

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the return type of coalesce
```

### CODE REVIEW

File: pkg/expression/builtin_compare.go [hunk 1]
```diff
@@ -141,6 +141,10 @@ func (c *coalesceFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 		return nil, err
 	}
 
+	if resultFieldType.GetType() == mysql.TypeDate {
+		bf.setDecimalAndFlenForDate()
+	}
```
Comment (guo-shaoge) [inline pkg/expression/builtin_compare.go:146]: I'm ok with this fix for this specific issue.
But I wonder why there is no `ETDate`, which makes this type deduction wrong, which cause we have to add this kind of code for every similar situation.

Comment (xzhangxian1008) [reply pkg/expression/builtin_compare.go:146]: > Why not just set resultFieldType to bf.tp? For control functions(case when/ifnull), it use this way to avoid this problem.

The type of resultFieldType is `EvalType` and `EvalType` doesn't have `Date` type.

Comment (windtalker) [reply pkg/expression/builtin_compare.go:146]: I think `resultEvalType` is the `EvalType`, `resultFieldType` is field type.

Comment (xzhangxian1008) [reply pkg/expression/builtin_compare.go:146]: > I think `resultEvalType` is the `EvalType`, `resultFieldType` is field type.

okk, I will change it.

File: pkg/expression/builtin_compare.go [hunk 2]
```diff
@@ -141,6 +141,8 @@ func (c *coalesceFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 		return nil, err
 	}
 
+	bf.tp = resultFieldType
+
 	bf.tp.AddFlag(resultFieldType.GetFlag())
```
Comment (windtalker) [inline pkg/expression/builtin_compare.go:146]: This line can be removed

Comment (windtalker) [reply pkg/expression/builtin_compare.go:146]: And I found there is lots of code(L145-L197) to adjust `resultFieldType` according to input fieldtype, can you double check if we can use `resultFieldType, err := InferType4ControlFuncs(xxx)`, and remove these extra adjustments? Because theoretically, the type infer for `coalesce` should be the same as `case when/ifnull`, which all use `InferType4ControlFuncs`

File: pkg/expression/builtin_compare.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/expression/builtin_compare.go]: > I think `resultEvalType` is the `EvalType`, `resultFieldType` is field type.

From the failure of ut, we can see that when sql is `select coalesce(c_int_d, c_datetime) from xxx;` the test will fail. So, we can't directly set resultFieldType to bf.tp.

File: pkg/expression/builtin_compare.go (hunk 2 above)
Comment (xzhangxian1008) [reply pkg/expression/builtin_compare.go:146]: > And I found there is lots of code(L145-L197) to adjust `resultFieldType` according to input fieldtype, can you double check if we can use `resultFieldType, err := InferType4ControlFuncs(xxx)`, and remove these extra adjustments? Because theoretically, the type infer for `coalesce` should be the same as `case when/ifnull`, which all use `InferType4ControlFuncs`

After check, I think we can not remove these extra adjustments.

File: pkg/expression/builtin_compare.go [hunk 3]
```diff
@@ -119,18 +119,19 @@ func (c *coalesceFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 		return nil, err
 	}
 
-	fieldTps := make([]*types.FieldType, 0, len(args))
+	flag := uint(0)
```
Comment (windtalker) [inline pkg/expression/builtin_compare.go:122]: Why need to handle this NotNullFlag here? I think `InferType4ControlFuncs` already handles this flag?

File: pkg/expression/builtin_compare.go [hunk 4]
```diff
@@ -1157,11 +1105,9 @@ func (b *builtinIntervalIntSig) evalInt(row chunk.Row) (int64, bool, error) {
 	}
 	isUint1 := mysql.HasUnsignedFlag(b.args[0].GetType().GetFlag())
 	var idx int
-	if b.hasNullable {
```
Comment (windtalker) [inline pkg/expression/builtin_compare.go:1160]: why change this?

File: pkg/expression/builtin_control.go [hunk 5]
```diff
@@ -117,37 +117,60 @@ func setDecimalFromArgs(evalType types.EvalType, resultFieldType *types.FieldTyp
...
+	}
+	return false
+}
+
 func addCollateAndCharsetAndFlagFromArgs(ctx sessionctx.Context, funcName string, evalType types.EvalType, resultFieldType *types.FieldType, args ...Expression) error {
 	switch funcName {
-	case ast.If, ast.Ifnull, ast.WindowFuncLead, ast.WindowFuncLag:
-		if len(args) != 2 {
-			panic("unexpected length of args for if/ifnull/lead/lag")
+	case ast.If, ast.Ifnull, ast.WindowFuncLead, ast.WindowFuncLag, ast.Coalesce:
```
Comment (windtalker) [inline pkg/expression/builtin_control.go:142]: maybe `coalesce` should be treated the same as `case`, so you don't need to change these codes

File: pkg/expression/builtin_control.go [hunk 6]
```diff
@@ -198,8 +221,8 @@ func InferType4ControlFuncs(ctx sessionctx.Context, funcName string, args ...Exp
 		tempFlag := resultFieldType.GetFlag()
 		types.SetTypeFlag(&tempFlag, mysql.NotNullFlag, false)
 		resultFieldType.SetFlag(tempFlag)
-		// If both arguments are NULL, make resulting type BINARY(0).
-		resultFieldType.SetType(mysql.TypeString)
+
+		resultFieldType.SetType(mysql.TypeNull)
```
Comment (windtalker) [inline pkg/expression/builtin_control.go:225]: Is this behavior the same as MySQL?

Comment (xzhangxian1008) [reply pkg/expression/builtin_control.go:225]: > Is this behavior the same as MySQL?

Yes, when we execute `select coalesce(null,null);` the return type is:
```
Field   1:  `coalesce(null,null)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       NULL
Collation:  binary (63)
Length:     0
Max_length: 0
Decimals:   0
Flags:      BINARY NUM
```

File: pkg/expression/builtin_compare.go (hunk 3 above)
Comment (xzhangxian1008) [reply pkg/expression/builtin_compare.go:122]: > Why need to handle this NotNullFlag here? I think `InferType4ControlFuncs` already handles this flag?

After check, I think `InferType4ControlFuncs` does not handle this flag.

Comment (windtalker) [reply pkg/expression/builtin_compare.go:122]: `InferType4ControlFuncs` is a common type infer function that aims at aggregating some input types into one "common return type", it should be used by all the functions whose return type has this pattern, for example: `ifnull/case when/coalesce`, if you need add code to handle `NotNullFlag` in `coalesce`, you should double check the following question:
- Why you need to add special code to handle `NotNullFlag` in `coalesce` only? Will the problem you meet also happens in other functions that use `InferType4ControlFuncs` as its type infer function?

**Review by windtalker — APPROVED** [review]
LGTM

**Review by wshwsh12 — APPROVED** [review]
