### PR TITLE
test: improve test by checking gc_delete_range instead of scanning keys

### LINKED ISSUE #27888: Unstable test testDBSuite1.TestDropPrimaryKey
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
[2021-09-08T09:26:28.816Z] db_test.go:1690:

[2021-09-08T09:26:28.816Z]     testDropIndex(c, s.store, s.lease, createSQL, dropIdxSQL, idxName)

[2021-09-08T09:26:28.816Z] db_test.go:2020:

[2021-09-08T09:26:28.816Z]     c.Assert(handles, HasLen, 0, Commentf("take time %v", time.Since(startTime)))

[2021-09-08T09:26:28.817Z] ... obtained map[int64]struct {} = map[int64]struct {}{1:struct {}{}, 2:struct {}{}, 3:struct {}{}, 4:struct {}{}, 5:struct {}{}, 6:struct {}{}, 7:struct {}{}, 8:struct {}{}, 9:struct {}{}, 10:struct {}{}, 11:struct {}{}, 12:struct {}{}, 13:struct {}{}, 14:struct {}{}, 15:struct {}{}, 16:struct {}{}, 17:struct {}{}, 18:struct {}{}, 19:struct {}{}, 20:struct {}{}, 21:struct {}{}, 22:struct {}{}, 23:struct {}{}, 24:struct {}{}, 25:struct {}{}, 26:struct {}{}, 27:struct {}{}, 28:struct {}{}, 29:struct {}{}, 30:struct {}{}, 31:struct {}{}, 32:struct {}{}, 33:struct {}{}, 34:struct {}{}, 35:struct {}{}, 36:struct {}{}, 37:struct {}{}, 38:struct {}{}, 39:struct {}{}, 40:struct {}{}, 41:struct {}{}, 42:struct {}{}, 43:struct {}{}, 44:struct {}{}, 45:struct {}{}, 46:struct {}{}, 47:struct {}{}, 48:struct {}{}, 49:struct {}{}, 50:struct {}{}, 51:struct {}{}, 52:struct {}{}, 53:struct {}{}, 54:struct {}{}, 55:struct {}{}, 56:struct {}{}, 57:struct {}{}, 58:struct {}{}, 59:struct {}{}, 60:struct {}{}, 61:struct {}{}, 62:struct {}{}, 63:struct {}{}, 64:struct {}{}, 65:struct {}{}, 66:struct {}{}, 67:struct {}{}, 68:struct {}{}, 69:struct {}{}, 70:struct {}{}, 71:struct {}{}, 72:struct {}{}, 73:struct {}{}, 74:struct {}{}, 75:struct {}{}, 76:struct {}{}, 77:struct {}{}, 78:struct {}{}, 79:struct {}{}, 80:struct {}{}, 81:struct {}{}, 82:struct {}{}, 83:struct {}{}, 84:struct {}{}, 85:struct {}{}, 86:struct {}{}, 87:struct {}{}, 88:struct {}{}, 89:struct {}{}, 90:struct {}{}, 91:struct {}{}, 92:struct {}{}, 93:struct {}{}, 94:struct {}{}, 95:struct {}{}, 96:struct {}{}, 97:struct {}{}, 98:struct {}{}, 99:struct {}{}, 100:struct {}{}}

[2021-09-08T09:26:28.817Z] ... n int = 0

[2021-09-08T09:26:28.817Z] ... take time 15.186033412s


```

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/32078/pipeline

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #27888

Problem Summary: 

Previously in the tests about `drop table` and `drop index`, we asserted an table/index is dropped by scanning the key in new txn in a period of time(15s) until it is not found. This brings uncertainty so that it failed when the CI machine is in a high load.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: ddl/db_test.go [hunk 1]
```diff
@@ -1969,57 +1934,72 @@ func (s *testDBSuite3) TestCancelDropColumns(c *C) {
...
+	dom.DDL().SetHook(jobIDExt)
+	return jobIDExt, func() {
+		dom.DDL().SetHook(originHook)
 	}
-	c.Assert(handles, HasLen, 0, Commentf("take time %v", time.Since(startTime)))
+}
+
+func checkDelRangeAdded(c *C, tk *testkit.TestKit, jobID int64, elemID int64) {
+	queryTempl := "select count(1) from mysql.%s where job_id = ? and element_id = ?;"
+	rs := tk.MayQuery(fmt.Sprintf(queryTempl, "gc_delete_range_done"), jobID, elemID).Rows()
```
Comment (wjhuang2016) [inline ddl/db_test.go:1995]: Why use MayQuery?

File: ddl/db_test.go [hunk 2]
```diff
@@ -1969,57 +1934,72 @@ func (s *testDBSuite3) TestCancelDropColumns(c *C) {
...
+	cnt := rs[0][0].(string)
+	if cnt == "0" {
+		tk.MustQuery(fmt.Sprintf(queryTempl, "gc_delete_range"), jobID, elemID).
```
Comment (AilinKid) [inline ddl/db_test.go:1998]: how about use a union to combine this two query into one (in one txn), since there is time diff in which the job may slip from` gc_delete_range` into `gc_delete_range_done`

1 & 0
0 & 1 
is both right

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

File: ddl/db_test.go (hunk 1 above)
Comment (tangenta) [reply ddl/db_test.go:1995]: Because the GC worker may not finish yet. In this case, the record is in `gc_delete_range` instead of `gc_delete_range_done`.

File: tidb-server/main.go [hunk 3]
```diff
@@ -183,11 +183,9 @@ func main() {
 	}
 	// Enable failpoints in tikv/client-go if the test API is enabled.
 	// It appears in the main function to be set before any use of client-go to prevent data race.
-	if _, err := failpoint.Status("github.com/pingcap/tidb/server/enableTestAPI"); err == nil {
-		warnMsg := "tikv/client-go failpoint is enabled, this should NOT happen in the production environment"
-		logutil.BgLogger().Warn(warnMsg)
+	failpoint.Inject("enableTestAPI", func(val failpoint.Value) {
```
Comment (wjhuang2016) [inline tidb-server/main.go:186]: Why do you change it?

Comment (tangenta) [reply tidb-server/main.go:186]: It is a mistake :)

**Review by wjhuang2016 — APPROVED** [review]

File: ddl/db_test.go [hunk 4]
```diff
@@ -1991,15 +1991,9 @@ func setupJobIDExtCallback(ctx sessionctx.Context) (jobExt *testDDLJobIDCallback
...
-	queryTempl := "select count(1) from mysql.%s where job_id = ? and element_id = ?;"
-	rs := tk.MayQuery(fmt.Sprintf(queryTempl, "gc_delete_range_done"), jobID, elemID).Rows()
-	cnt := rs[0][0].(string)
-	if cnt == "0" {
-		tk.MustQuery(fmt.Sprintf(queryTempl, "gc_delete_range"), jobID, elemID).
-			Check(testkit.Rows("1"))
-		return
-	}
-	c.Assert(cnt, Equals, "1")
+	query := "(select count(1) from mysql.gc_delete_range where job_id = ? and element_id = ?)" +
```
Comment (AilinKid) [inline ddl/db_test.go]: same name `gc_delete_range`

**Review by AilinKid — APPROVED** [review]
