### PR TITLE
spool: fix data race when to exit

### LINKED ISSUE #42130: DATA RACE in the TestReleaseWhenRunningPool
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c000261228 by goroutine 20:
  runtime.racewrite()
      <autogenerated>:1 +0x24
  github.com/pingcap/tidb/resourcemanager/pool/spool.(*Pool).ReleaseAndWait()
      resourcemanager/pool/spool/spool.go:176 +0x48
  github.com/pingcap/tidb/resourcemanager/pool/spool.TestReleaseWhenRunningPool()
      resourcemanager/pool/spool/spool_test.go:64 +0x224
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1629 +0x47
Previous read at 0x00c000261228 by goroutine 21:
  runtime.raceread()
      <autogenerated>:1 +0x24
  github.com/pingcap/tidb/resourcemanager/pool/spool.(*Pool).run()
      resourcemanager/pool/spool/spool.go:109 +0x3c
  github.com/pingcap/tidb/resourcemanager/pool/spool.(*Pool).Run()
      resourcemanager/pool/spool/spool.go:90 +0xa6
  github.com/pingcap/tidb/resourcemanager/pool/spool.TestReleaseWhenRunningPool.func1()
      resourcemanager/pool/spool/spool_test.go:50 +0xaf
Goroutine 20 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1906 +0xb44
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x70
  github.com/pingcap/tidb/resourcemanager/pool/spool.TestMain()
      resourcemanager/pool/spool/main_test.go:32 +0x435
  main.main()
      bazel-out/k8-fastbuild/bin/resourcemanager/pool/spool/spool_test_/testmain.go:110 +0x5e8
Goroutine 21 (running) created at:
  github.com/pingcap/tidb/resourcemanager/pool/spool.TestReleaseWhenRunningPool()
      resourcemanager/pool/spool/spool_test.go:47 +0x164
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1629 +0x47
==================
--- FAIL: TestReleaseWhenRunningPool (0.01s)
    testing.go:1446: race detected during execution of test
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
	panic: sync: WaitGroup is reused before previous Wait has returned
goroutine 35 [running]:
testing.tRunner.func1.2({0x18fe2e0, 0x1f6da60})
	GOROOT/src/testing/testing.go:1526 +0x372
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1529 +0x650
panic({0x18fe2e0, 0x1f6da60})
	GOROOT/src/runtime/panic.go:890 +0x263
sync.(*WaitGroup).Wait(0xc000261220)
	GOROOT/src/sync/waitgroup.go:118 +0x107
github.com/pingcap/tidb/resourcemanager/pool/spool.(*Pool).ReleaseAndWait(0xc000261220)
	resourcemanager/pool/spool/spool.go:176 +0x49
github.com/pingcap/tidb/resourcemanager/pool/spool.TestReleaseWhenRunningPool(0x0?)
	resourcemanager/pool/spool/spool_test.go:64 +0x225
testing.tRunner(0xc000307ba0, 0x1b7ec50)
	GOROOT/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1629 +0x806 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #42130

Problem Summary:

when we are in exit mode, Some tasks still want to start a new goroutine and call ```waitgroup.Add```. but at the same time, we are calling the ```waitgroup.Wait```.
the data race will happen.

### What is changed and how it works?

Adding the logic of checking the exit mode when to check the running exit and wait to make all tasks called ```waitgroup.Add```.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: resourcemanager/pool/spool/spool.go [hunk 1]
```diff
@@ -142,7 +145,12 @@ func (p *Pool) RunWithConcurrency(fns chan func(), concurrency uint32) error {
 
 // checkAndAddRunning is to check if a task can run. If can, add the running number.
 func (p *Pool) checkAndAddRunning(concurrency uint32) (conc int32, run bool) {
+	p.waiting.Add(1)
+	defer p.waiting.Add(-1)
```
Comment (you06) [inline resourcemanager/pool/spool/spool.go:149]: Move the waiting variable modification into Run? Because it may call `p.wg.Add(1)` after this checking and the check(`for p.waiting.Load() > 0 {...}`) in `ReleaseAndWait` may pass after `checkAndAddRunning` and before `p.wg.Add(1)`, then there is still possible race.

File: resourcemanager/pool/spool/spool.go [hunk 2]
```diff
@@ -173,6 +181,10 @@ func (p *Pool) checkAndAddRunningInternal(concurrency int32) (conc int32, run bo
 // ReleaseAndWait releases the pool and waits for all tasks to be completed.
 func (p *Pool) ReleaseAndWait() {
 	p.isStop.Store(true)
+	// wait for all the task in the pending to exit
+	for p.waiting.Load() > 0 {
+		time.Sleep(waitInterval)
```
Comment (you06) [inline resourcemanager/pool/spool/spool.go:186]: I want to confirm the usage of `ReleaseAndWait`. If it may be called in `Executor.Close`, `5ms` sleep is unacceptable. If it's called when TiDB exiting or kvstore closing, this LGTM.

File: resourcemanager/pool/spool/spool.go (hunk 1 above)
Comment (hawkingrei) [reply resourcemanager/pool/spool/spool.go:149]: You are right.

File: resourcemanager/pool/spool/spool.go (hunk 2 above)
Comment (hawkingrei) [reply resourcemanager/pool/spool/spool.go]: I remove ```5ms``` sleep first.

Comment (you06) [reply resourcemanager/pool/spool/spool.go]: A spinlock is risky because it may loop here while the `Run` or `RunWithConcurrency` threads are scheduled out, why not use a condition variable here?

**Review by you06 — APPROVED** [review]

File: resourcemanager/pool/spool/spool.go (hunk 2 above)
Comment (hawkingrei) [reply resourcemanager/pool/spool/spool.go]: Done

**Review by GMHDBJD — APPROVED** [review]
LGTM
