### PR TITLE
planner, json: restore cast flag after substitute column in cast

### LINKED ISSUE #39806: Invalid JSON text: The document root must not be followed by other values
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
explain 
select a from (
	select JSON_OBJECT('number', `temp1`.`number`, 'name', `temp1`.`name`)  'a' from  
	(
		select 1  as number, 'name-1' as name  union 
		(select 2, 'name-2' ) union 
		(select 3, 'name-3' ) union 		
		(select 4, 'name-4' ) union 
		(select 5, 'name-5' ) union 
		(select 6, 'name-2' ) 
	) temp1 
) temp  
where  a ->> '$.number' = 1

```

执行计划可以执行，但是执行会报错。`Invalid JSON text: The document root must not be followed by other values` 

### 2. What did you expect to see? (Required)

执行结果是：
```
{"name": "name-1", "number": 1}
```

### 3. What did you see instead (Required)

```Invalid JSON text: The document root must not be followed by other values```

### 4. What is your TiDB version? (Required)

```
5.7.25-TiDB-v6.2.0
```

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #39806

Problem Summary:

json functions use a flag `mysql.ParseToJSONFlag` to mark whether the `castStringAsJson` function should try to parse the string as a json, or simply convert the string to a json string. For example, with this flag, `abcd` is not a valid json, and will return an error. Without this flag, `abcd` will be casted to `"abcd"`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that predicate push down could result in json format error with `json_object` function
```

### CODE REVIEW

File: expression/integration_test.go [hunk 1]
```diff
@@ -7896,3 +7896,22 @@ func TestIssue39146(t *testing.T) {
...
+		(
+			select 1  as number, 'name-1' as name  union
+			(select 2, 'name-2' ) union
+			(select 3, 'name-3' ) union
+			(select 4, 'name-4' ) union
+			(select 5, 'name-5' ) union
+			(select 6, 'name-2' )
+		) temp1
+	) temp
+	where  a ->> '$.number' = 1`).Check(testkit.Rows(`{"name": "name-1", "number": 1}`))
```
Comment (hawkingrei) [inline expression/integration_test.go:7916]: May we move it into ```TestAggregationBuiltinJSONObjectAgg```? In fact, it is too much test in the expression. it will slow the test when to use bazel.

Comment (YangKeao) [reply expression/integration_test.go]: Sure. I moved them into the `TestAggregationBuiltinJSONObjectAgg`, and added some comments for it.

**Review by xiongjiwei — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
