### PR TITLE
flashback: make `br backup full` works during `flashback cluster`

### LINKED ISSUE #40404: br full backup fail during flashback for dead lock
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run workload
2. run flashback to before workload run
3. br full backup during flashback
4. br restore to dest tidb from minio files
5. check dest tidb crc32 checksum
```code
flashback cluster to timestamp '2023-01-09 09:00';
tiup br backup full --pd [172.16.6.46:2379](http://172.16.6.46:2379/) --backupts '2023-01-09 10:48:00' --storage "s3://tmp/backup-46-snapshot-20230109104800-empty?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9001&force-path-style=true" --ratelimit 128 --log-file backupfull-46-0109.log
```

### 2. What did you expect to see? (Required)
backup success

### 3. What did you see instead (Required)
backup hang

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #40404 

Problem Summary: When we create a domain and received a flashback error, we can try again with the `flashbackStartTS` returned by error msg. This allows br backup with backups to succeed.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
* Add code below to make flashback loop infinitely
```diff
--- a/ddl/cluster.go
+++ b/ddl/cluster.go
@@ -753,6 +753,8 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
                        return ver, nil
                }

+               time.Sleep(time.Second)
+               return ver, nil
                for _, r := range keyRanges {
                        if err = flashbackToVersion(d.ctx, d,
                                func(ctx context.Context, r tikvstore.KeyRange) (rangetask.TaskStat, error) {
```

* Then do `flashback cluster`,  at the same time use br to backup data with `--backupts=xxx` flags. The backup will return success.
* restore cluster with backup data success and data is correct.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
LGTM

File: domain/domain.go [hunk 1]
```diff
@@ -490,12 +502,21 @@ func (do *Domain) Reload() error {
...
+			// use the lastest available version to create domain
+			version -= 1
+			is, hitCache, oldSchemaVersion, changes, err = do.loadInfoSchema(version)
+		}
+		if err != nil {
+			metrics.LoadSchemaDuration.Observe(time.Since(startTime).Seconds())
+			metrics.LoadSchemaCounter.WithLabelValues("failed").Inc()
+			return err
+		}
 	}
```
Comment (xhebox) [inline domain/domain.go:518]: You could move L518 to L512. I prefer leaving the metrics block at the top indent:

```
xx := load(ver.Ver)
if err != nil {
   // retry with flashback
   xx = load(version - 1)
}
if err != nil {
   return err
}
```

File: domain/schema_validator.go [hunk 2]
```diff
@@ -153,7 +153,9 @@ func (s *schemaValidator) Update(leaseGrantTS uint64, oldVer, currVer int64, cha
 				s.do.Store().GetMemCache().Delete(tblIDs[idx])
 			}
 			if ac == uint64(model.ActionFlashbackCluster) {
-				s.do.InfoSyncer().GetSessionManager().KillNonFlashbackClusterConn()
+				if s.do != nil && s.do.InfoSyncer() != nil && s.do.InfoSyncer().GetSessionManager() != nil {
+					s.do.InfoSyncer().GetSessionManager().KillNonFlashbackClusterConn()
```
Comment (xhebox) [inline domain/schema_validator.go:157]: Maybe mock `tkRoot.Session().SetSessionManager(&testkit.MockSessionManager{PS: ps})`

Comment (Defined2014) [reply domain/schema_validator.go:157]: It's for `br`, not for test only :(

File: domain/domain.go (hunk 1 above)
Comment (Defined2014) [reply domain/domain.go:513]: Done, PTAL @xhebox

**Review by xhebox — APPROVED** [review]
