### PR TITLE
planner: eliminate unused outer join over window top1

### LINKED ISSUE #67517: planner: missing outer join elimination for row_number top1 derived table
### 1. Minimal reproduce

```sql
use test;

drop table if exists t1, t2;
create table t1 (a int, b int, c int);
create table t2 (a int, b int, c int, key(a));

explain format = 'brief'
select t1.a
from t1
left join (
    select
        a,
        row_number() over(partition by a order by c desc) as rn
    from t2
) t2w
    on t1.a = t2w.a and t2w.rn = 1
where t1.a = 1;
```

### 2. Current behavior

TiDB keeps the `LeftOuterJoin` and still plans the right side window subtree, even though:

- the query output does not use any column from the right side
- `row_number() over(partition by a ...)` with `rn = 1` guarantees at most one row per `a`
- therefore the `LEFT JOIN` is semantically redundant

### 3. Expected behavior

The planner should eliminate the redundant `LEFT JOIN` and keep only the left-side scan/filter.

### 4. Why this matters

For this query pattern, failing to eliminate the join can leave an unnecessary `Window + Sort + Scan` subtree in the plan and significantly increase planning/execution cost.

### 5. Root cause

`outer_join_eliminate` currently recognizes uniqueness from schema key information, but it does not recognize the derived-table pattern:

- `row_number() over(partition by join_key order by ...)`
- filtered by `rn = 1` or `rn <= 1`

That pattern also implies uniqueness on the partition key for join elimination purposes.

### 6. Suggested fix

Teach outer join elimination to treat the following right-side shape as unique on the partition key:

- `Selection`
- over `LogicalWindow`
- with a single `row_number()` window function
- partitioned by the join key
- constrained by `rn = 1` or `rn <= 1`

### 7. Validation

Add a planner regression test that checks the join is eliminated for the anonymized query shape above.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #67517

Problem Summary:

TiDB misses an outer join elimination opportunity when the inner side is a derived table built from `row_number() over(partition by join_key ...)` and filtered by `rn = 1`.

If the query does not use any inner-side columns, that pattern guarantees at most one matching row per join key, so the `LEFT JOIN` is redundant and can be eliminated.

### What changed and how does it work?

- Teach `outer_join_eliminate` to recognize `Selection(Window(row_number))` with `rn = 1` or `rn <= 1` as unique on the window partition key.
- Add a planner regression test with an anonymized minimal query shape.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

ref https://github.com/PingCAP-QE/planreplayertest/pull/111

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

## Summary by CodeRabbit

* **Improvements**
  * Enhanced outer-join elimination so LEFT JOINs can be simplified when the inner side is filtered to a single row per partition (row_number = 1), improving query planning for such windowed patterns.

* **Tests**
  * Added a test covering join optimization when the inner side is derived via a row-number window and filtered to one row.

* **Documentation**
  * Added notes describing the new planner behavior and its structural constraints.

### CODE REVIEW

File: pkg/planner/core/rule_join_elimination.go [hunk 1]
```diff
@@ -164,6 +167,72 @@ func (*OuterJoinEliminator) isInnerJoinKeysContainUniqueKey(innerPlan base.Logic
 	return false, nil
 }
 
+func isSelectionPartitionedRowNumberWindowOneUnique(innerPlan base.LogicalPlan, joinKeys *expression.Schema) bool {
```
Comment (qw4990) [inline pkg/planner/core/rule_join_elimination.go:173]: Please add some comments

File: pkg/planner/core/rule_join_elimination.go [hunk 2]
```diff
@@ -164,6 +167,72 @@ func (*OuterJoinEliminator) isInnerJoinKeysContainUniqueKey(innerPlan base.Logic
...
+
+	for _, partitionCol := range window.GetPartitionByCols() {
+		if !joinKeys.Contains(partitionCol) {
+			return false
+		}
+	}
+	return true
+}
+
+func hasRowNumberUpperBoundOne(conditions []expression.Expression, rowNumberCol *expression.Column) bool {
```
Comment (qw4990) [inline pkg/planner/core/rule_join_elimination.go:206]: also please add some comments

**Review by AilinKid — APPROVED** [review]

File: pkg/planner/core/rule_join_elimination.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/planner/core/rule_join_elimination.go:173]: Added comments here to spell out the uniqueness argument more explicitly: the helper only recognizes the Selection(Window(row_number)) shape where the filter keeps at most one row for each partition key, so the inner side is unique on the join keys for outer join elimination. I also updated the planner rule note with the same constraint and scope.

File: pkg/planner/core/rule_join_elimination.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/planner/core/rule_join_elimination.go:206]: Added a clarifying comment for hasRowNumberUpperBoundOne as well. It now states that we only match predicates keeping the row_number() result column at or below 1 through equality to 1 or simple upper bounds recognized by expression.FindUpperBound, and the planner rule note was updated accordingly.

**Review by guo-shaoge — APPROVED** [review]
