### PR TITLE
lightning: add option to return partial mdl on error

### LINKED ISSUE #37861: Lightning: MyDumpLoader Can Return Partial Result on Error
## Enhancement
Currently, if something wrong happened on constructing the MyDumperLoader object, a nil is returned.  However, in some situations, it is caused by the context deadline exceeded.  In this situation, we may want to see the partial result of MyDumperLoader.

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #37861 

Problem Summary:

### What is changed and how it works?
Added an option when constructing an MDLoader, which can control whether we return the partial result on error.

### Check List

Tests 

- [x] Unit test  (current UT has already covered)
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
   create a program to scan a large S3 folder with a limited context.   When setting the new option,
   I can see the partial result when the context deadline exceeded
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/mydump/loader.go [hunk 1]
```diff
@@ -297,7 +312,7 @@ func (s *mdLoaderSetup) setup(ctx context.Context, store storage.ExternalStorage
 	*/
 	var gerr error
 	if err := s.listFiles(ctx, store); err != nil {
-		if errors.ErrorEqual(err, common.ErrTooManySourceFiles) {
+		if s.setupCfg.ReturnPartialResultOnError {
```
Comment (D3Hunter) [inline br/pkg/lightning/mydump/loader.go:315]: should this need to change too ?
https://github.com/pingcap/tidb/blob/5209ac2fa1a3db278661588370786b2991728320/br/pkg/lightning/restore/precheck.go#L76

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: br/pkg/lightning/mydump/loader.go (hunk 1 above)
Comment (dsdashun) [reply br/pkg/lightning/mydump/loader.go:315]: You are right.  Will push the patch soon

Comment (dsdashun) [reply br/pkg/lightning/mydump/loader.go:315]: fixed in 2e935901b98ea5379ff13a9e4dd02ad2b41486c9

File: br/pkg/lightning/restore/precheck.go [hunk 2]
```diff
@@ -73,11 +72,11 @@ func NewPrecheckItemBuilderFromConfig(ctx context.Context, cfg *config.Config, o
 	}
 	mdl, err := mydump.NewMyDumpLoader(ctx, cfg, builderCfg.MDLoaderSetupOptions...)
 	if err != nil {
-		if errors.ErrorEqual(err, common.ErrTooManySourceFiles) {
-			gerr = err
-		} else {
+		if mdl == nil {
 			return nil, errors.Trace(err)
 		}
+		// here means the partial result is returned, so we can continue on processing
```
Comment (D3Hunter) [inline br/pkg/lightning/restore/precheck.go:78]: no need to check `ReturnPartialResultOnError`? maybe comment why we always use partial result here.

Comment (dsdashun) [reply br/pkg/lightning/restore/precheck.go:78]: Because originally, `NewMyDumpLoader` will always return nil when error occurs.  Now this behavior is changed only the user adds the `ReturnPartialResultOnError` option when constructing the MDL.  So, if returned mdl is not nil, we can infer that users sets the `ReturnPartialResultOnError` option or equivalents.

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
some ci fails on master, may block this pr merge, will check it tomorrow
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/13289/pipeline

**Review by niubell — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
> some ci fails on master, may block this pr merge, will check it tomorrow https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/13289/pipeline

fixed in https://github.com/pingcap/tidb/pull/37790

**Comment by dsdashun** [comment]
BR integration test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/10518/pipeline
