### PR TITLE
executor: fix analyze cannot be killed

### LINKED ISSUE #65818: Analyze cannot be cancelled promptly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
  1. Create a table and insert some rows.
  2. Enable a failpoint to stall analyze RPC or NextRaw (e.g. a sleep in analyze pushdown).
  3. Run ANALYZE TABLE t in one session.
  4. From another session, issue KILL QUERY <conn_id>.

```

### 2. What did you expect to see? (Required)

The ANALYZE job should terminate quickly after KILL QUERY, and its RPC/streaming should stop without blocking workers.

### 3. What did you see instead (Required)
 The analyze worker blocks on RPC/NextRaw; the job does not exit promptly after kill, and the analyze execution can hang.
### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/commit/d73149100936b38f15bb7c07504dc5591ca7c9c9

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65818

Problem Summary:

After #63067 removed the coprocessor-side periodic kill polling fallback in `recvFromRespCh`, `ANALYZE` started depending on the caller-provided context to stop blocked `NextRaw` / DistSQL work promptly.

Several analyze paths still used `context.TODO()` or did not propagate the same kill-aware context consistently through workers, merge loops, and result handling. As a result, a kill or cancellation could be observed before the RPC started, but some blocked analyze paths still could not exit promptly once they entered `NextRaw` / DistSQL.

### What changed and how does it work?

- Build one statement-scoped kill-aware context from `SQLKiller` in `AnalyzeExec` and pass it through the analyze workflow explicitly.
- Replace `context.TODO()` in analyze DistSQL / `NextRaw` paths with the propagated context so blocked V1 column and index analyze requests observe cancellation consistently.
- Make the V2 sampling / merge workflow and shared analyze worker orchestration follow the same cancellation path and normalize context errors with their cancel cause.
- Keep analyze job finishing and dropped-result cleanup aligned with the new cancellation flow.
- Add failpoint-gated regression coverage for both context cancellation and kill-triggered exit, plus the supporting Bazel target update for the analyze test package.

### Check List

Tests 

- [x] Unit test
  - `make failpoint-enable`
  - `go test -count=1 -run '^(TestKillAutoAnalyze|TestKillAutoAnalyzeIndex)$' -tags=intest,deadlock ./pkg/executor/test/analyzetest`
  - `make failpoint-disable`
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix cases where ANALYZE could not stop promptly after kill or cancellation.
```

### CODE REVIEW

File: pkg/executor/analyze.go [hunk 1]
```diff
@@ -504,7 +543,80 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
...
+				return
+			}
+		}
+	}()
+	return ctx, func() {
+		cancel(context.Canceled)
+		close(stopCh)
+	}
+}
+
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/executor/analyze.go:554]: Addressed in `f5e23e2` as well. `analyzeWorkerExitErr` now checks `ctx.Err()` first and returns `normalizeCtxErrWithCause(ctx, ctx.Err())` before entering the `select`, so when both `ctx.Done()` and `errExitCh` are ready we deterministically prefer the specific context cause instead of racing with the generic `ErrQueryInterrupted` path.

File: pkg/executor/analyze.go [hunk 2]
```diff
@@ -504,7 +543,78 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
...
+func (e *AnalyzeExec) sendAnalyzeResult(ctx context.Context, statsHandle *handle.Handle, resultsCh chan<- *statistics.AnalyzeResults, result *statistics.AnalyzeResults) {
+	select {
+	case resultsCh <- result:
+		return
+	case <-ctx.Done():
+	case <-e.errExitCh:
+	}
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/executor/analyze.go:580]: Addressed in `f5e23e2`. `sendAnalyzeResult` now uses `normalizeCtxErrWithCause(ctx, result.Err)` and only falls back to the context error when needed, so a generic lower-layer `context.Canceled` no longer overwrites the real kill cause carried by `context.Cause(ctx)`.

File: pkg/executor/analyze.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/executor/analyze.go:554]: /pantheon-bot review

**Comment by hawkingrei** [comment]
@pantheon-bot review

File: pkg/executor/analyze_idx.go [hunk 3]
```diff
@@ -240,8 +260,24 @@ func (e *AnalyzeIndexExec) buildStatsFromResult(result distsql.SelectResult, nee
 	return hist, cms, fms, topn, nil
 }
 
-func (e *AnalyzeIndexExec) buildSimpleStats(ranges []*ranger.Range, considerNull bool) (fms *statistics.FMSketch, nullHist *statistics.Histogram, err error) {
-	if err = e.open(ranges, considerNull); err != nil {
+func (e *AnalyzeIndexExec) logAnalyzeCanceledInTest(ctx context.Context, err error, msg string) {
```
Comment (winoros) [inline pkg/executor/analyze_idx.go]: We name it as `InTest` but its condition can allow `!intest.InTest` pass.
Should we change the name or change the condition?

File: pkg/executor/analyze.go [hunk 4]
```diff
@@ -504,7 +543,74 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
 	return err
 }
 
-func (e *AnalyzeExec) analyzeWorker(taskCh <-chan *analyzeTask, resultsCh chan<- *statistics.AnalyzeResults) {
+func (e *AnalyzeExec) buildAnalyzeKillCtx(parent context.Context) (context.Context, func()) {
```
Comment (winoros) [inline pkg/executor/analyze.go:529]: Could you share your comments on KillCtx's passing and management?

Comment (hawkingrei) [reply pkg/executor/analyze.go:529]: My current view is to keep KillCtx management explicit instead of turning it into task/executor-owned state.

I did try a stateful passing approach earlier, but it widened the invariant surface and made the flow harder to follow. I reverted that and kept the original explicit ctx passing model:
- `buildAnalyzeKillCtx` creates one statement-scoped ctx for the whole `ANALYZE`.
- The same ctx is passed down through the analyze DistSQL/index paths, so parent cancellation and `SQLKiller` share the same cancel cause.
- `stop()` cancels the derived ctx and stops the watcher goroutine.

So for this round I only added inline comments to document ownership/lifecycle; I did not add extra repo docs or introduce hidden binding/state propagation.

File: pkg/executor/analyze_idx.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/executor/analyze_idx.go]: Good point. I changed the helper so the actual debug-only work is fully guarded by `if intest.InTest { ... }`; the outer early return now only filters to canceled errors. With the current behavior I think the name still matches the intent, so I would prefer keeping `logAnalyzeCanceledInTest` rather than renaming it.

File: pkg/executor/analyze_col_v2.go [hunk 5]
```diff
@@ -604,54 +671,108 @@ func (e *AnalyzeColumnsExecV2) subMergeWorker(resultCh chan<- *samplingMergeResu
...
+	for data := range taskCh {
+		memTracker.Release(int64(cap(data)))
+	}
 }
 
-func (e *AnalyzeColumnsExecV2) subBuildWorker(resultCh chan error, taskCh chan *samplingBuildTask, hists []*statistics.Histogram, topns []*statistics.TopN, exitCh chan struct{}) {
+func (e *AnalyzeColumnsExecV2) logAnalyzeCanceledInTest(ctx context.Context, err error, msg string) {
+	if !intest.InTest || err == nil || !stderrors.Is(err, context.Canceled) {
+		return
+	}
```
Comment (winoros) [inline pkg/executor/analyze_col_v2.go]: We can break it into two if to increase readability.

Comment (hawkingrei) [reply pkg/executor/analyze_col_v2.go]: I have updated.

File: pkg/statistics/handle/autoanalyze/autoanalyze.go [hunk 6]
```diff
@@ -845,34 +845,48 @@ func finishAnalyzeJob(sctx sessionctx.Context, job *statistics.AnalyzeJob, analy
 	}
 
 	job.EndTime = time.Now()
-	var sql string
-	var args []any
+	setStartTime := false
```
Comment (0xPoe) [inline pkg/statistics/handle/autoanalyze/autoanalyze.go]: This seems to be separable from this PR, as it mainly focuses on analyzing job start time update. Could you please split it into another PR and also include a test for it? It would also make this part easier to move forward and reduce the size of this PR.

Comment (hawkingrei) [reply pkg/statistics/handle/autoanalyze/autoanalyze.go]: Good point. I found issues around this part while exercising the related tests, so I reverted it from this PR for now. We can follow up with a separate PR later and add a dedicated test for the start_time behavior there.

**Review by 0xPoe — COMMENTED** [review]
As I will be taking a long time off starting tomorrow, I will hand over this PR review to @mjonss and @time-and-fate to hame them take a look on this.

I also want to mention we already have a few issues and PRs around this part of code. For example: https://github.com/pingcap/tidb/issues/65915 and https://github.com/pingcap/tidb/pull/66561.

We should consider redesigning the implementation of this workflow to find a more manageable approach. However, I am not suggesting that we should combine everything together. This is just for more context.

/hold

/cc @mjonss @time-and-fate

**Review by winoros — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
lgtm

File: pkg/statistics/handle/autoanalyze/autoanalyze.go (hunk 6 above)
Comment (hawkingrei) [reply pkg/statistics/handle/autoanalyze/autoanalyze.go]: This part is intended as a bug fix instead of a separate cleanup.

Although it is technically separable, it is still in the same analyze job workflow and leaving it out would keep the current buggy behavior. We still have a key customer relying on this path, so I would prefer to keep this fix in the current PR to avoid delaying the delivery.

I agree the broader workflow can be further cleaned up or redesigned in follow-up work, but for this PR I want to keep the change focused on fixing the current behavior first. I can also add a targeted test for this specific case.

File: pkg/executor/analyze.go [hunk 7]
```diff
@@ -504,7 +543,77 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
...
+					return
+				}
+				err := killer.HandleSignal()
+				if err == nil {
+					err = exeerrors.ErrQueryInterrupted
+				}
+				cancel(err)
+				return
+			}
+		}
```
Comment (time-and-fate) [inline pkg/executor/analyze.go:548]: I think two things are redundant here:
1. The `for` loop. Because each `case` ends with `return`, the `for` is useless.
2. The `stopCh`. `cancel(context.Canceled)` should be enough.

File: pkg/executor/analyze_col_sampling.go [hunk 8]
```diff
@@ -364,7 +389,9 @@ func (e *AnalyzeColumnsExec) buildSamplingStats(
 	indexPushedDownResult := <-idxNDVPushDownCh
 	if indexPushedDownResult.err != nil {
 		close(exitCh)
-		e.samplingBuilderWg.Wait()
+		for err := range buildResultChan {
+			_ = err
+		}
```
Comment (time-and-fate) [inline pkg/executor/analyze_col_sampling.go]:
```suggestion
		for range buildResultChan {
		}
```

File: pkg/executor/analyze_idx.go [hunk 9]
```diff
@@ -243,8 +264,26 @@ func (e *AnalyzeIndexExec) buildStatsFromResult(result distsql.SelectResult, nee
...
```
Comment (time-and-fate) [inline pkg/executor/analyze_idx.go]: This function is exactly the same as `(e *AnalyzeColumnsExec) logAnalyzeCanceledInTest`.

File: pkg/executor/analyze_col_sampling.go [hunk 10]
```diff
@@ -849,33 +963,61 @@ type samplingBuildTask struct {
...
+				logutil.BgLogger().Info("analyze columns nextRaw failed",
+					zap.Uint32("killSignal", sctx.GetSessionVars().SQLKiller.GetKillSignal()),
+					zap.Uint64("connID", sctx.GetSessionVars().ConnectionID),
+					zap.Error(err),
+					zap.Bool("isCtxCanceled", stderrors.Is(err, context.Canceled)),
+					zap.Error(cause),
+					zap.Error(ctxErr),
+					zap.Stack("stack"),
+				)
+			}
```
Comment (time-and-fate) [inline pkg/executor/analyze_col_sampling.go]: It's quite similar to `logAnalyzeCanceledInTest()`. We can consider reusing it.

File: pkg/executor/analyze_col_sampling.go [hunk 11]
```diff
@@ -280,15 +287,33 @@ func (e *AnalyzeColumnsExec) buildSamplingStats(
...
+			logutil.BgLogger().Info("analyze columns read task failed",
+				zap.Uint32("killSignal", e.ctx.GetSessionVars().SQLKiller.GetKillSignal()),
+				zap.Uint64("connID", e.ctx.GetSessionVars().ConnectionID),
+				zap.Error(err),
+				zap.Bool("isCtxCanceled", stderrors.Is(err, context.Canceled)),
+				zap.Error(cause),
+				zap.Error(ctxErr),
+				zap.Stack("stack"),
+			)
+		}
```
Comment (time-and-fate) [inline pkg/executor/analyze_col_sampling.go]: ditto.

File: pkg/executor/analyze.go [hunk 12]
```diff
@@ -504,7 +543,93 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
...
+func (e *AnalyzeExec) buildAnalyzeKillCtx(parent context.Context) (context.Context, func()) {
+	ctx, cancel := context.WithCancelCause(parent)
+	killer := &e.Ctx().GetSessionVars().SQLKiller
+	killCh := killer.GetKillEventChan()
+	go func() {
+		select {
+		case <-ctx.Done():
+		case <-killCh:
+			status := killer.GetKillSignal()
+			if status == 0 {
```
Comment (0xPoe) [inline pkg/executor/analyze.go]:
```suggestion
				if status == sqlkiller.UnspecifiedKillSignal {
					return
				}

```
Could you please add a comment to explain why this happens?

File: pkg/executor/analyze.go [hunk 13]
```diff
@@ -172,7 +177,19 @@ TASKLOOP:
 	}()
 
 	err = e.waitFinish(ctx, g, resultsCh)
+	if err == nil && ctx.Err() != nil {
+		// Preserve the original cancellation cause before follow-up work (for example stats cache update)
+		// can degrade it into a plain context error.
+		err = normalizeCtxErrWithCause(ctx, ctx.Err())
+	}
 	if err != nil {
+		err = normalizeCtxErrWithCause(ctx, err)
```
Comment (0xPoe) [inline pkg/executor/analyze.go]: This seems to be a double normalization.

File: pkg/executor/analyze.go [hunk 14]
```diff
@@ -469,6 +486,28 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
 			break
 		}
 		if results.Err != nil {
+			if intest.InTest && stderrors.Is(results.Err, context.Canceled) {
```
Comment (0xPoe) [inline pkg/executor/analyze.go]: May I ask why we need have this intest only log here? Do we still need it?

File: pkg/executor/analyze_col_sampling.go [hunk 15]
```diff
@@ -443,30 +461,47 @@ func (e *AnalyzeColumnsExec) handleNDVForSpecialIndexes(indexInfos []*model.Inde
 	}
 	var err error
 	statsHandle := domain.GetDomain(e.ctx).StatsHandle()
+LOOP:
```
Comment (time-and-fate) [inline pkg/executor/analyze_col_sampling.go]: The label is unnecessary.

File: pkg/executor/analyze.go [hunk 16]
```diff
@@ -527,23 +652,22 @@ func (e *AnalyzeExec) analyzeWorker(taskCh <-chan *analyzeTask, resultsCh chan<-
...
 		failpoint.Inject("handleAnalyzeWorkerPanic", nil)
-		statsHandle.StartAnalyzeJob(task.job)
 		switch task.taskType {
 		case colTask:
-			select {
-			case <-e.errExitCh:
-				return
-			case resultsCh <- task.colExec.analyzeColumnsPushDown(e.gp):
-			}
+			statsHandle.StartAnalyzeJob(task.job)
```
Comment (0xPoe) [inline pkg/executor/analyze.go]: It seems there is no need to change this line of code.

File: pkg/executor/analyze.go [hunk 17]
```diff
@@ -527,23 +652,22 @@ func (e *AnalyzeExec) analyzeWorker(taskCh <-chan *analyzeTask, resultsCh chan<-
...
+			result := task.colExec.analyzeColumnsPushDown(ctx, e.gp)
+			e.sendAnalyzeResult(ctx, statsHandle, resultsCh, result)
 		case idxTask:
-			select {
-			case <-e.errExitCh:
-				return
-			case resultsCh <- analyzeIndexPushdown(task.idxExec):
-			}
+			statsHandle.StartAnalyzeJob(task.job)
```
Comment (0xPoe) [inline pkg/executor/analyze.go]: ditt

File: pkg/executor/analyze.go [hunk 18]
```diff
@@ -527,23 +652,22 @@ func (e *AnalyzeExec) analyzeWorker(taskCh <-chan *analyzeTask, resultsCh chan<-
 		var ok bool
 		task, ok = <-taskCh
 		if !ok {
-			break
+			return
+		}
+		if err := analyzeWorkerExitErr(ctx, e.errExitCh); err != nil {
```
Comment (0xPoe) [inline pkg/executor/analyze.go:620]: Could you please add comments to explain when this would help abort the workflow?

File: pkg/executor/analyze_col_sampling.go [hunk 19]
```diff
@@ -443,30 +461,47 @@ func (e *AnalyzeColumnsExec) handleNDVForSpecialIndexes(indexInfos []*model.Inde
...
 		totalResult.results[results.Ars[0].Hist[0].ID] = results
 	}
+	if err == nil {
+		if ctxErr := ctx.Err(); ctxErr != nil {
+			err = context.Cause(ctx)
+			if err == nil {
+				err = ctxErr
+			}
+		}
+	}
```
Comment (time-and-fate) [inline pkg/executor/analyze_col_sampling.go:485]: This can be simplified to `err = normalizeCtxErrWithCause(ctx, ctx.Err())`.

File: pkg/executor/analyze.go [hunk 20]
```diff
@@ -504,7 +543,93 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
...
+	case <-ctx.Done():
+		return normalizeCtxErrWithCause(ctx, ctx.Err())
+	case <-errExitCh:
+		return exeerrors.ErrQueryInterrupted
+	default:
+		return nil
+	}
+}
+
+func (e *AnalyzeExec) sendAnalyzeResult(ctx context.Context, statsHandle *handle.Handle, resultsCh chan<- *statistics.AnalyzeResults, result *statistics.AnalyzeResults) {
```
Comment (0xPoe) [inline pkg/executor/analyze.go]:
```suggestion
// Add a comment to notify the caller that this function may fail and the result will be discarded/destroyed once the send fails.
func (e *AnalyzeExec) trySendAnalyzeResult(ctx context.Context, statsHandle *handle.Handle, resultsCh chan<- *statistics.AnalyzeResults, result *statistics.AnalyzeResults) {
```

File: pkg/executor/analyze_idx.go [hunk 21]
```diff
@@ -207,14 +211,30 @@ func (e *AnalyzeIndexExec) buildStatsFromResult(result distsql.SelectResult, nee
...
-		if err := e.ctx.GetSessionVars().SQLKiller.HandleSignal(); err != nil {
+		select {
+		case <-killerCtx.Done():
+			err := context.Cause(killerCtx)
+			if err == nil {
+				err = killerCtx.Err()
+			}
 			return nil, nil, nil, nil, err
+		default:
 		}
```
Comment (time-and-fate) [inline pkg/executor/analyze_idx.go]: This can be simplified.
```suggestion
if err := normalizeCtxErrWithCause(killerCtx); err != nil {
	return nil, nil, nil, nil, err
}
```

File: pkg/executor/analyze.go [hunk 22]
```diff
@@ -504,7 +543,93 @@ func (e *AnalyzeExec) handleResultsErrorWithConcurrency(
...
+		zap.Uint64("connID", sctx.GetSessionVars().ConnectionID),
+		zap.Error(err),
+		zap.Bool("isCtxCanceled", stderrors.Is(err, context.Canceled)),
+		zap.Error(cause),
+		zap.Error(ctxErr),
+		zap.Stack("stack"),
+	)
+}
+
+func logAnalyzeCanceledInTest(ctx context.Context, logger *zap.Logger, sctx sessionctx.Context, err error, msg string) {
```
Comment (0xPoe) [inline pkg/executor/analyze.go]: Do we still need to keep this log? If it is truly helpful, can we make it the standard log?

**Review by 0xPoe — COMMENTED** [review]
Thanks!
Went through the analyze.go.

File: pkg/executor/analyze.go (hunk 7 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go:548]: Addressed in b3eaed8757. buildAnalyzeKillCtx now uses a single select, and stop() directly calls cancel(context.Canceled), so both the redundant for-loop and stopCh are removed.

File: pkg/executor/analyze.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/executor/analyze.go:580]: Addressed in f5e23e2. sendAnalyzeResult now normalizes cancellation via normalizeCtxErrWithCause(ctx, result.Err) and only falls back to the statement context error when needed, so a generic lower-layer context.Canceled no longer overwrites the real kill cause. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/executor/analyze.go:554]: Addressed in f5e23e2 as well. analyzeWorkerExitErr now checks ctx.Err() first and returns normalizeCtxErrWithCause(ctx, ctx.Err()) before entering the select, so we deterministically prefer the specific context cause instead of racing with the generic ErrQueryInterrupted path. Marking this thread resolved.

File: pkg/executor/analyze_idx.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/executor/analyze_idx.go]: Addressed in the current diff. The debug-only logging work is now fully guarded inside the shared helper, so the current helper name still matches the remaining behavior. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 4 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go:529]: Followed up in the current patch set. I kept the explicit statement-scoped KillCtx passing model, and the latest cleanup removed the redundant watcher loop and stopCh without introducing extra hidden state. Marking this thread resolved.

File: pkg/executor/analyze_col_v2.go (hunk 5 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_v2.go]: Addressed in the current diff. Marking this thread resolved.

File: pkg/statistics/handle/autoanalyze/autoanalyze.go (hunk 6 above)
Comment (hawkingrei) [reply pkg/statistics/handle/autoanalyze/autoanalyze.go]: This thread is outdated on the latest diff, and the final patch set already reflects the scope I am keeping in this PR. I will mark this discussion resolved here and follow up separately if more cleanup is needed.

File: pkg/executor/analyze_col_sampling.go (hunk 8 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go]: Addressed in a2af8fde70. I reused channel.Clear(buildResultChan) instead of open-coding the drain loop, which keeps the same drain-until-close behavior and avoids the empty-block lint issue. Marking this thread resolved.

File: pkg/executor/analyze_idx.go (hunk 9 above)
Comment (hawkingrei) [reply pkg/executor/analyze_idx.go]: Addressed in b3eaed8757. The duplicated index-side helper was removed, and both paths now reuse the shared analyze cancel logging helper. Marking this thread resolved.

File: pkg/executor/analyze_col_sampling.go (hunk 10 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go]: Addressed in b3eaed8757. This logging path now reuses the shared helper as suggested. Marking this thread resolved.

File: pkg/executor/analyze_col_sampling.go (hunk 11 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go]: Addressed together with the shared helper cleanup in b3eaed8757. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 12 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed in 416dd0f7f4. I added an inline comment explaining that resetKillEvent may close killCh during statement reset even when no real kill signal was recorded, so this synthetic wake-up should be ignored. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 13 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed in 8f8ef2263c. The double normalization is gone now: we normalize the waitFinish error on the error path, and only derive a normalized ctx error on the nil-error path. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 14 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed in 8f8ef2263c. Those intest-only cancellation logs were only temporary debugging aids while validating the cancel-cause flow, and I removed them from the final patch. Marking this thread resolved.

File: pkg/executor/analyze_col_sampling.go (hunk 15 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go]: Addressed in 416dd0f7f4. The unnecessary label is removed now. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 16 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed in 8f8ef2263c. I moved StartAnalyzeJob back before the switch so we do not duplicate the same call in each task branch. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 17 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed together with the same cleanup in 8f8ef2263c. StartAnalyzeJob is shared again before the switch. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 18 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go:620]: Addressed in 8f8ef2263c. I added a comment to explain that analyzeWorkerExitErr is checked after a task is dequeued but before starting a new analyze request, so the worker can abort promptly when the statement or the whole analyze workflow has already been canceled. Marking this thread resolved.

File: pkg/executor/analyze_col_sampling.go (hunk 19 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go:485]: Addressed in 416dd0f7f4. This path now uses normalizeCtxErrWithCause(ctx, ctx.Err()) directly. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 20 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed in 8f8ef2263c. I renamed the helper to trySendAnalyzeResult and added a comment that the result may be dropped and destroyed when the statement is already aborting. Marking this thread resolved.

File: pkg/executor/analyze_idx.go (hunk 21 above)
Comment (hawkingrei) [reply pkg/executor/analyze_idx.go]: Addressed in 416dd0f7f4. The cancellation pre-check is simplified to normalizeCtxErrWithCause(killerCtx, killerCtx.Err()). Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 22 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed in 8f8ef2263c. I removed the intest-only cancel logs instead of promoting them to standard logs, since they were only useful during the cancel-cause debugging pass. Marking this thread resolved.

File: pkg/executor/analyze.go (hunk 12 above)
Comment (0xPoe) [reply pkg/executor/analyze.go]: Do we need to consider using `sqlkiller.UnspecifiedKillSignal` here, as I suggested in the last comment? Or does it represent something different? Or would it cause cyclic dependencies?

File: pkg/executor/analyze_col_sampling.go [hunk 23]
```diff
@@ -600,54 +644,83 @@ func (e *AnalyzeColumnsExec) subMergeWorker(resultCh chan<- *samplingMergeResult
...
+			newRetCollectorSize := retCollector.Base().MemSize
+			subCollectorSize := subCollector.Base().MemSize
+			e.memTracker.Consume(newRetCollectorSize - oldRetCollectorSize - subCollectorSize)
+			e.memTracker.Release(inflightDataSize + inflightRespSize)
+			inflightDataSize = 0
+			inflightRespSize = 0
+			subCollector.DestroyAndPutToPool()
+		case <-ctx.Done():
+			err := normalizeCtxErrWithCause(ctx, ctx.Err())
+			if (err == nil || stderrors.Is(err, context.Canceled)) && parentCtx != nil {
```
Comment (0xPoe) [inline pkg/executor/analyze_col_sampling.go]: May I ask why the presentCtx fallback is necessary here? It seems we already use context.WithCancelCause when creating this error group. So, I assume the parent cause would pass through to the child error cause?

```go
package main

import (
	"context"
	"errors"
	"fmt"

	"golang.org/x/sync/errgroup"
)

func main() {
	parent, cancelParent := context.WithCancelCause(context.Background())
	g, child := errgroup.WithContext(parent)

	cancelParent(errors.New("root cause from parent"))

	_ = g // just to mirror errgroup.WithContext usage

	fmt.Println("child.Err():", child.Err())
	fmt.Println("child.Cause():", context.Cause(child))
}
```

File: pkg/executor/analyze_col_sampling.go [hunk 24]
```diff
@@ -600,54 +644,83 @@ func (e *AnalyzeColumnsExec) subMergeWorker(resultCh chan<- *samplingMergeResult
 	for range l {
 		retCollector.Base().FMSketches = append(retCollector.Base().FMSketches, statistics.NewFMSketch(statistics.MaxSketchSize))
 	}
+	cleanupCollector := func() {
```
Comment (0xPoe) [inline pkg/executor/analyze_col_sampling.go:648]: This is a good approach to update the memTracker if the work exits. However, when we quit the entire statement execution, we detach the whole memTracker. Therefore, I'm not sure if these changes are necessary. I don't have strong opinions on it. @time-and-fate Not sure what do you think?

**Review by 0xPoe — COMMENTED** [review]
Thanks!

Went through pkg/executor/analyze_col_sampling.go.

File: pkg/executor/analyze_col_sampling.go (hunk 23 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go]: Addressed in 9855d3ef51d. You are right here: with the current `golang.org/x/sync/errgroup` implementation, `errgroup.WithContext(taskCtx)` already derives `mergeCtx` via `context.WithCancelCause(taskCtx)`, so `normalizeCtxErrWithCause(ctx, ctx.Err())` is enough to preserve the parent cancel cause. I removed the extra `parentCtx` fallback and the unused parameter. Marking this thread resolved.

File: pkg/executor/analyze_col_sampling.go (hunk 24 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go:648]: I kept this cleanup as-is. Even though statement shutdown will eventually detach the tracker from its parent, `memory.Tracker.Detach()` only unlinks the tracker; it does not zero the child trackers own consumed bytes. Releasing `retCollector` on these early-return paths still keeps the local tracker state accurate and matches the collector lifecycle better. Since you do not have strong objections here, I will keep this version and mark the thread resolved.

File: pkg/executor/analyze.go (hunk 12 above)
Comment (hawkingrei) [reply pkg/executor/analyze.go]: Addressed in 6e5e975598e. There is no cycle concern here, and `sqlkiller.UnspecifiedKillSignal` is exactly the right constant for this check, so I switched the code from the raw `0` to that named signal. Marking this thread resolved.

**Review by time-and-fate — COMMENTED** [review]
I didn't find any new bugs anymore. And it's OK for me to approve this PR.

The biggest issue is that this PR is too complicated for me to make sure there are absolutely no issues with the code.
So I'll let @0xPoe continue his review and give his conclusion.

File: pkg/executor/analyze_col_sampling.go [hunk 25]
```diff
@@ -600,54 +643,77 @@ func (e *AnalyzeColumnsExec) subMergeWorker(resultCh chan<- *samplingMergeResult
...
-		// Print collect log.
-		oldRetCollectorSize := retCollector.Base().MemSize
-		oldRetCollectorCount := retCollector.Base().Count
-		retCollector.MergeCollector(subCollector)
-		newRetCollectorCount := retCollector.Base().Count
-		printAnalyzeMergeCollectorLog(oldRetCollectorCount, newRetCollectorCount, subCollector.Base().Count,
-			e.tableID.TableID, e.tableID.PartitionID, e.TableID.IsPartitionTable(),
-			"merge subMergeWorker in AnalyzeColumnsExec", index)
-
-		// Consume the memory of the result.
```
Comment (0xPoe) [inline pkg/executor/analyze_col_sampling.go:636]: nit: Maybe this is not a reason to remove these comments that help us divide this code into smaller chunks.

**Review by 0xPoe — APPROVED** [review]
I think it is ready to go.

But please update your PR body to ensure it matches what you changed.

Feel free to unhold after you address these issues.

Thanks! :shipit:

**Comment by 0xPoe** [comment]
First of all, I really want to thank @windtalker @crazycs520 for taking the time to review this PR. That said, I find myself hesitant to bring this up, as it's not the kind of feedback I enjoy giving. We've unfortunately found quite a few issues(Check Kunqin and my comments) in the PR that were approved, which makes me wonder if there may not have been enough bandwidth for a thorough review at the time. I'd gently ask that if that's ever the case, it might be worth holding off on approving until there's a chance to look through the changes more carefully. I truly appreciate your time and just hope we can work together to catch things a bit earlier before they get merged. 🙏

File: pkg/executor/analyze_col_sampling.go (hunk 25 above)
Comment (hawkingrei) [reply pkg/executor/analyze_col_sampling.go:636]: Addressed in abe9c155972. I restored the chunking comments in subMergeWorker so the worker setup, cleanup, and merge loop are easier to scan. Marking this thread resolved.
