### PR TITLE
infoschema: optimize 'select count(*) from information_schema.tables' for v2

### LINKED ISSUE #55515: GC life time is shorter than transaction duration when query information_schema.tables with InfoSchema V2 enable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

set schema cache 2gb
prepare 1 million databases and 2 million tables
```
mysql> select count(*) from information_schema.tables;
ERROR 9006 (HY000): GC life time is shorter than transaction duration, transaction starts at 2024-08-20 07:13:02.343 +0800 CST, GC safe point is 2024-08-20 07:13:24.893 +0800 CST
```
### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
```
2024-08-20 07:23:26 (UTC+08:00)TiDB [tc-tidb-1.tc](http://tc-tidb-1.tc/)-tidb-peer.jira-users-master-v2-8jwmv.svc:4000[conn.go:1178] ["command dispatched failed"] [conn=2575313706] [session_alias=] [connInfo="id:2575313706, addr:[10.200.26.63:41812](http://10.200.26.63:41812/) status:10, collation:latin1_swedish_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="select count(*) from information_schema.tables"] [txn_mode=PESSIMISTIC] [timestamp=0] [err="[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2024-08-20 07:13:02.343 +0800 CST, GC safe point is 2024-08-20 07:13:24.893 +0800 CST\[ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175\ngithub.com/pingcap/tidb/pkg/store/driver/error.ToTiDBErr\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/error/error.go:150\ngithub.com/pingcap/tidb/pkg/store/driver/txn.extractKeyErr\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/txn/error.go:166\ngithub.com/pingcap/tidb/pkg/store/driver/txn.(*tikvSnapshot).Get\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/txn/snapshot.go:61\ngithub.com/pingcap/tidb/pkg/structure.(*TxStructure).HGet\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/structure/hash.go:45\ngithub.com/pingcap/tidb/pkg/meta.(*Meta).checkDBExists\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/meta/meta.go:547\ngithub.com/pingcap/tidb/pkg/meta.(*Meta).GetMetasByDBID\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/meta/meta.go:1006\ngithub.com/pingcap/tidb/pkg/meta.(*Meta).ListTables\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/meta/meta.go:1099\ngithub.com/pingcap/tidb/pkg/infoschema.(*infoschemaV2).SchemaTableInfos\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema_v2.go:761\ngithub.com/pingcap/tidb/pkg/planner/core.listTablesForEachSchema\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/memtable_infoschema_extractor.go:653\ngithub.com/pingcap/tidb/pkg/planner/core.(*InfoSchemaTablesExtractor).ListSchemasAndTables\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/memtable_infoschema_extractor.go:301\ngithub.com/pingcap/tidb/pkg/executor.(*memtableRetriever).setDataFromTables\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/infoschema_reader.go:716\ngithub.com/pingcap/tidb/pkg/executor.(*memtableRetriever).retrieve\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/infoschema_reader.go:133\ngithub.com/pingcap/tidb/pkg/executor.(*MemTableReaderExec).Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/memtable_reader.go:120\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:451\ngithub.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).fetchChildData\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/aggregate/agg_hash_executor.go:482\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650](http://ngithub.com/pingcap/errors.AddStack/n/t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178/ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs/n/t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175/ngithub.com/pingcap/tidb/pkg/store/driver/error.ToTiDBErr/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/error/error.go:150/ngithub.com/pingcap/tidb/pkg/store/driver/txn.extractKeyErr/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/txn/error.go:166/ngithub.com/pingcap/tidb/pkg/store/driver/txn.(*tikvSnapshot).Get/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/store/driver/txn/snapshot.go:61/ngithub.com/pingcap/tidb/pkg/structure.(*TxStructure).HGet/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/structure/hash.go:45/ngithub.com/pingcap/tidb/pkg/meta.(*Meta).checkDBExists/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/meta/meta.go:547/ngithub.com/pingcap/tidb/pkg/meta.(*Meta).GetMetasByDBID/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/meta/meta.go:1006/ngithub.com/pingcap/tidb/pkg/meta.(*Meta).ListTables/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/meta/meta.go:1099/ngithub.com/pingcap/tidb/pkg/infoschema.(*infoschemaV2).SchemaTableInfos/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema_v2.go:761/ngithub.com/pingcap/tidb/pkg/planner/core.listTablesForEachSchema/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/memtable_infoschema_extractor.go:653/ngithub.com/pingcap/tidb/pkg/planner/core.(*InfoSchemaTablesExtractor).ListSchemasAndTables/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/memtable_infoschema_extractor.go:301/ngithub.com/pingcap/tidb/pkg/executor.(*memtableRetriever).setDataFromTables/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/infoschema_reader.go:716/ngithub.com/pingcap/tidb/pkg/executor.(*memtableRetriever).retrieve/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/infoschema_reader.go:133/ngithub.com/pingcap/tidb/pkg/executor.(*MemTableReaderExec).Next/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/memtable_reader.go:120/ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:451/ngithub.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).fetchChildData/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/aggregate/agg_hash_executor.go:482/nruntime.goexit/n/t/usr/local/go/src/runtime/asm_amd64.s:1650)"]
```
### 4. What is your TiDB version? (Required)

Release Version: v8.3.0-alpha
Edition: Community
Git Commit Hash: 336d3a30f12cf11f10593b7131046c2291a22d4c
Git Branch: heads/refs/tags/v8.3.0-alpha
UTC Build Time: 2024-08-17 11:45:28
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #55515
ref #50959 

Problem Summary:

```
mysql> select count(*) from information_schema.tables;
ERROR 9006 (HY000): GC life time is shorter than transaction duration, transaction starts at 2024-08-20 07:13:02.343 +0800 CST, GC safe point is 2024-08-20 07:13:24.893 +0800 CST
```

### What changed and how does it work?

Make a special optimization for reading `INFORMATION_SCHEMA.TABLES`, that is, if only `table_name` or `table_schema` are visited, make the query pure in-memory operation.

~~I tried to support `select count(*)` but found that the aggregation always use the first column for `*`, and in that case for INFORMATION_SCHEMA.TABLES, the column is `table_catalog`. And changing the `select count(*)` to using other columns seems more difficult than I thought.~~

### Check List

Tests 

- [X] Unit test
- [X] Integration test

Test with 1M tables:

```
mysql> select count(table_name) from tables;
+-------------------+
| count(table_name) |
+-------------------+
|           1007314 |
+-------------------+
1 row in set (1.54 sec)
```

Without this optimize:

```
mysql> select count(*) from tables;
+----------+
| count(*) |
+----------+
|  1007315 |
+----------+
1 row in set (9 min 50.39 sec)
```

image

- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
Is `select count(*) from information_schema.tables;` widely used? Just curious.

File: pkg/executor/infoschema_reader.go [hunk 1]
```diff
@@ -706,10 +716,82 @@ func (e *memtableRetriever) setDataFromTables(ctx context.Context, sctx sessionc
...
+	if onlySchemaOrTableColumns(e.columns) {
+		is := e.is
+		if raw, ok := is.(*infoschema.SessionExtendedInfoSchema); ok {
+			is = raw.InfoSchema
+		}
+		v2, ok := is.(interface {
+			IterateAllTableItems(visit func(infoschema.TableItem) bool)
+		})
+		if ok {
+			if x := ctx.Value("cover-check"); x != nil {
```
Comment (lance6716) [inline pkg/executor/infoschema_reader.go:733]: maybe use a failpoint

**Review by lance6716 — APPROVED** [review]

File: pkg/executor/infoschema_reader.go (hunk 1 above)
Comment (tiancaiamao) [reply pkg/executor/infoschema_reader.go:733]: IMO, failpoint is not as convient sometimes. 
- It works globally, so there's no good way for precise control with a specific query.
- It requires `make failpoint-enable`, an extra step to enable the test

Comment (lance6716) [reply pkg/executor/infoschema_reader.go:733]: > It requires make failpoint-enable, an extra step to enable the test

I have added this feature for failpoint, it can be configurated with our other testing command line arguments like `--tags=intest` or `-race` https://github.com/pingcap/failpoint?tab=readme-ov-file#quick-start-use-failpoint-toolexec

File: tests/integrationtest/t/executor/infoschema_reader.test [hunk 2]
```diff
@@ -307,3 +307,11 @@ select * from information_schema.table_constraints where table_schema = 'executo
...
 --sorted_result
 select * from information_schema.table_constraints where table_schema = 'executor__infoschema_reader' and CONSTRAINT_NAME = 'c1';
+
+# TestTables
+select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE,ENGINE,VERSION from information_schema.tables where table_name = 't';
+select table_name, table_schema from information_schema.tables where table_name = 't';
+select table_name from information_schema.tables where table_name = 't';
+explain format='brief' select table_name, table_schema from information_schema.tables;
+select count(*) from information_schema.tables where table_name = 't';
+select count(table_name) from information_schema.tables where table_name = 't';
```
Comment (tangenta) [inline tests/integrationtest/t/executor/infoschema_reader.test:317]:
```suggestion
select count(table_name) from information_schema.tables where table_name = 't';

```

**Review by fixdb — APPROVED** [review]
+1
