### PR TITLE
ddl: fix add index's merge with multi-schema optimization

### LINKED ISSUE #51746: Data inconsistency after adding indexes with multi-schema optimization
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
	store, dom := testkit.CreateMockStoreAndDomain(t)
	defer ingesttestutil.InjectMockBackendMgr(t, store)()
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("CREATE TABLE `19bbb05e` (\n  `cca4a823` smallint(6) DEFAULT '7008',\n  `b5244bf8` bigint(20) DEFAULT '6308994588244965155',\n  `32c733ce` bigint(20) DEFAULT '-1343611900857841884',\n  `5c7e9e66` datetime DEFAULT '9052-06-30 13:10:34',\n  `24e1a62a` mediumint(9) DEFAULT '-4378120',\n  `df1a2915` tinyint(4) DEFAULT '-113',\n  `90a87a70` int(11) DEFAULT '-1057258940',\n  KEY `99d84913` (`df1a2915`),\n  KEY `cb679e68` (`24e1a62a`),\n  KEY `eba0c161` (`32c733ce`),\n  KEY `d5ba3944` (`90a87a70`,`32c733ce`,`24e1a62a`)\n) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci")
	tk.MustExec("ALTER TABLE `19bbb05e` ADD  INDEX `08427bcf` (`cca4a823`), ADD  INDEX `367bc5a4` (`90a87a70`), RENAME INDEX `99d84913` to `06c5d43f`, ADD COLUMN `ae57ec09` SMALLINT NULL DEFAULT '-18721' AFTER `5c7e9e66`;")
```

### 2. What did you expect to see? (Required)

Both of temp indexes get merged.

### 3. What did you see instead (Required)

There are two indexes, but only one "merge temp index" log is observed. It is possible that one of temp index is not merged. That means if there are workload during adding index on the this table, data must be inconsistency.

### 4. What is your TiDB version? (Required)

47a990e7f

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #51746

Problem Summary:

The bug is introduced by #47135: when merging temp index records from multiple indexes, I didn't set `reorgInfo`'s `StartKey` and `EndKey`  correctly. As a result, only one temp index get merged.

### What changed and how does it work?

This PR initializes `reorgInfo.Start` and `reorgInfo.End` with keys encoded by the first index ID and the last index ID.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/reorg.go [hunk 1]
```diff
@@ -706,7 +706,10 @@ func getReorgInfo(ctx *JobContext, d *ddlCtx, rh *reorgHandler, job *model.Job,
 			tb = tbl.(table.PhysicalTable)
 		}
 		if mergingTmpIdx {
-			start, end = tablecodec.GetTableIndexKeyRange(pid, tablecodec.TempIndexPrefix|elements[0].ID)
+			firstElemTempID := tablecodec.TempIndexPrefix | elements[0].ID
```
Comment (Benjamin2037) [inline pkg/ddl/reorg.go:709]: Does all multi-schema change index with continuous id？

Comment (tangenta) [reply pkg/ddl/reorg.go:709]: They are always increasing, but not always continuous: if DDL adds another index between these indexes, it is possible that:

```
multi-schema add index IDs = [1, 2, 4, 5]
another index ID = [3]
```

If the new index rollbacked, temp index 0xFFFFxxx03 may have dirty records. I think we need to skip these dirty records.

Comment (tangenta) [reply pkg/ddl/reorg.go:709]: [01be552](https://github.com/pingcap/tidb/pull/51747/commits/01be5523d88c59cb0f2e73278fb24dc916c790ac)

Comment (Benjamin2037) [reply pkg/ddl/reorg.go:709]: Agree

File: pkg/ddl/index_merge_tmp.go [hunk 2]
```diff
@@ -148,64 +152,62 @@ func newMergeTempIndexWorker(bfCtx *backfillCtx, t table.PhysicalTable, elements
...
+		taskCtx.addedCount = 0
+		taskCtx.scanCount = 0
+		updateTxnEntrySizeLimitIfNeeded(txn)
+		txn.SetOption(kv.Priority, taskRange.priority)
+		if tagger := w.GetCtx().getResourceGroupTaggerForTopSQL(taskRange.getJobID()); tagger != nil {
+			txn.SetOption(kv.ResourceGroupTagger, tagger)
+		}
+		txn.SetOption(kv.ResourceGroupName, w.jobContext.resourceGroupName)
+
+		tmpIdxRecords, nextKey, taskDone, err := w.fetchTempIndexVals(txn, taskRange)
```
Comment (Benjamin2037) [inline pkg/ddl/index_merge_tmp.go:166]: Can we move the skip tempIndex or switch this logic 
`		if len(w.currentTempIndexPrefix) == 0 ||
				!bytes.HasPrefix(indexKey, w.currentTempIndexPrefix) {
				skip, err := w.updateCurrentIndexInfo(indexKey)
				if err != nil || skip {
					return skip, err
				}
			}` 
out of fetchTempIndexVals func and do it in taskRange level ? 
This could reduce compare and switch prefix logic.

Comment (tangenta) [reply pkg/ddl/index_merge_tmp.go:196]: https://github.com/pingcap/tidb/pull/51747/commits/3be8a9d0431f8fa7c7272e72105ef721f7812b79

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by wjhuang2016 — APPROVED** [review]
