### PR TITLE
expression: fix flaky test TestNowAndUTCTimestamp

### LINKED ISSUE #37437: unstable test in the TestNowAndUTCTimestamp
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
 === RUN   TestNowAndUTCTimestamp
    builtin_time_test.go:849: 
        	Error Trace:	/home/jenkins/.tidb/tmp/04446c229c5a73c16deb3edddcb4db34/sandbox/processwrapper-sandbox/5550/execroot/__main__/bazel-out/k8-fastbuild/bin/expression/expression_test_/expression_test.runfiles/__main__/expression/builtin_time_test.go:849
        	Error:      	"3.099621454s" is not less than or equal to "3s"
        	Test:       	TestNowAndUTCTimestamp
--- FAIL: TestNowAndUTCTimestamp (3.05s) 
```

https://prow.pingcap.net/view/gs/pingcapprow/logs/bazel_test_tidb/1564103182567608320#1:build-log.txt%3A2832

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #37437

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: expression/builtin_time_test.go [hunk 1]
```diff
@@ -856,7 +856,7 @@ func TestNowAndUTCTimestamp(t *testing.T) {
 		require.NoError(t, err)
 		mt = v.GetMysqlTime()
 		require.True(t, strings.Contains(mt.String(), "."))
-		require.LessOrEqual(t, ts.Sub(gotime(mt, ts.Location())), 3*time.Second)
```
Comment (tiancaiamao) [inline expression/builtin_time_test.go:859]: The test check call `time.Now()`, and then execute the expression function `Now`,
the difference is within 3s... 
Unless the computer is very slow (under extremely high load), this should not takes 3s+

You can just change 3s to 4s or 5s ... if this test case is not stable enough @hawkingrei

Comment (hawkingrei) [reply expression/builtin_time_test.go:859]: have set to 5s.

**Review by xhebox — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]
