### PR TITLE
*: refactor mpp err recovery logic

### LINKED ISSUE #50221: mpp explain analyze is wrong when mpp err recovery happens in disaggregate mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. setup tidb cluster with **disaggregated and AutoScaler**(or set up tidb cluster with [these failpoints](https://github.com/pingcap/tidb/blob/master/pkg/executor/test/tiflashtest/tiflash_test.go#L1896C76-L1896C105)(mpp_recovery_test_mock_enable, mpp_recovery_test_ignore_recovery_err and mpp_recovery_test_max_err_times) enabled)
2. run the following sql:
```
drop table if exists t1;
create table t1(c1 int);
insert into t1 values(1), (2);
alter table t1 set tiflash replica 1;
explain select * from t1;
```

### 2. What did you expect to see? (Required)
actRows of explain analyze is `2` 
### 3. What did you see instead (Required)
actRows of explain analyze is `4`
### 4. What is your TiDB version? (Required)
```
Release Version: v7.6.0-alpha-dirty
Edition: Community
Git Commit Hash: c21846e2c848ca17c1a47f0ebf5f692be1eccbbf
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2024-01-08 14:00:30
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #50221

Problem Summary:
For now, MPPGather use `mpperr.RecoveryHandler` to recovery mpp err and do mpp retry. But there are a lot of operations in `selectResult` like appending warning into `StmtCtx` or adding runtime stats into `StmtCtx`, which cause these operation will be duplicated when mpp retry happens. That's why the `actRows` in explain analyze is doubled.

### What changed and how does it work?
1. Add an extra abstraction `ExecutorWithRetry` between `selectResult` and `localMPPCoordinator`. So the retry logic will not affect `selectResult`.
2. Move most logic from `MPPGather` into `ExecutorWithRetry`
### Check List

Tests 

- [x] Unit test
- [x] Integration test: endless: https://github.com/PingCAP-QE/endless/pull/2168
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/internal/mpp/executor_with_retry.go [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+		return nil, err
+	}
+	return resp, nil
+}
+
+// Close implements kv.Response interface.
+func (r *ExecutorWithRetry) Close() error {
+	mppcoordmanager.InstanceMPPCoordinatorManager.Unregister(r.getCoordUniqueID())
+	// Handle reports only when it's not failed.
+	r.coord.(*localMppCoordinator).handleAllReports()
```
Comment (windtalker) [inline pkg/executor/internal/mpp/executor_with_retry.go:131]: I'm not sure if it is ok to call `handleAllReports()` before `coord.Close()`, maybe keep the `handleAllReports` inside `coord.Close()`, and add an extra argument to `coord.Close()` to indicate whether this `Close()` it should handleAllReports or not?

File: pkg/executor/internal/mpp/recovery_handler.go [hunk 2]
```diff
@@ -165,35 +158,32 @@ func (*memLimitHandlerImpl) doRecovery(info *RecoveryInfo) error {
...
+	resps      []*mppResponse
+	capacity   uint64
+	cannotHold bool
 }
 
 func newMPPResultHolder(holderCap uint64, parent *memory.Tracker) *mppResultHolder {
 	return &mppResultHolder{
 		capacity:   holderCap,
-		chks:       []*chunk.Chunk{},
+		resps:      []*mppResponse{},
```
Comment (windtalker) [inline pkg/executor/internal/mpp/recovery_handler.go:170]: init `resps` using `holderCap` as the reserved cap?

File: pkg/executor/internal/mpp/executor_with_retry.go (hunk 1 above)
Comment (guo-shaoge) [reply pkg/executor/internal/mpp/executor_with_retry.go:131]: Add a new method `closeWithoutReport` for `localMppCoordinator`.

Better not change `Close()`, because it implement `kv.Response` interface.

File: pkg/executor/internal/mpp/recovery_handler.go (hunk 2 above)
Comment (guo-shaoge) [reply pkg/executor/internal/mpp/recovery_handler.go]: done

**Review by windtalker — APPROVED** [review]
LGTM

**Review by SeaRise — APPROVED** [review]
lgtm

**Comment by SeaRise** [comment]
Comment `/hold cancel` to merge pr
/cc @guo-shaoge
