### PR TITLE
ttl: fix the issue that the TTL execution summary for timeout job is empty

### LINKED ISSUE #61509: TTL Job summary is empty when the job timeout
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Run a TTL job until timeout.

### 2. What did you expect to see? (Required)

The `tidb_ttl_table_status` and `tidb_ttl_job_history` will include the job summary like deleted row counts.

### 3. What did you see instead (Required)

The rows counts are always 0.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #61509 

Problem Summary:

### What changed and how does it work?

1. Create a new function `summarizeTaskResultWithError` to submit summary with error.
2. Find all existing tasks and summary them when the ttl job timeout.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that the summary for timeout TTL job is empty
```

### CODE REVIEW

File: pkg/ttl/ttlworker/job_manager.go [hunk 1]
```diff
@@ -1022,21 +1037,16 @@ type TTLSummary struct {
...
-	}
-	summary.SummaryText = string(buf)
-	return summary, nil
+	return summarizeTaskResultWithError(nil, err)
 }
 
 func summarizeTaskResult(tasks []*cache.TTLTask) (*TTLSummary, error) {
+	return summarizeTaskResultWithError(tasks, nil)
+}
+
```
Comment (Defined2014) [inline pkg/ttl/ttlworker/job_manager.go]: maybe we could remove those two functions.

File: pkg/ttl/ttlworker/job_manager.go [hunk 2]
```diff
@@ -536,34 +536,46 @@ func (m *JobManager) checkNotOwnJob() {
...
-
-		timeoutJobCtx, cancel := context.WithTimeout(m.ctx, ttlInternalSQLTimeout)
-
-		sql, args := cache.SelectFromTTLTaskWithJobID(job.id)
-		rows, err := se.ExecuteSQL(timeoutJobCtx, sql, args...)
-		cancel()
+		allTasks, err := m.findAllTasksForJob(se, job.id)
 		if err != nil {
-			logutil.Logger(m.ctx).Warn("fail to execute sql", zap.String("sql", sql), zap.Any("args", args), zap.Error(err))
+			logutil.Logger(m.ctx).Warn("fail to find all tasks for job", zap.String("jobID", job.id), zap.Error(err))
```
Comment (Defined2014) [inline pkg/ttl/ttlworker/job_manager.go]: Not sure does the log is meaningful or not, `findAllTasksForJob` function always print log when it return an error.

File: pkg/ttl/ttlworker/job_manager.go [hunk 3]
```diff
@@ -941,7 +952,11 @@ func (m *JobManager) updateHeartBeat(ctx context.Context, se session.Session, no
 func (m *JobManager) updateHeartBeatForJob(ctx context.Context, se session.Session, now time.Time, job *ttlJob) error {
 	if job.createTime.Add(ttlJobTimeout).Before(now) {
 		m.jobLogger(job).Info("job is timeout")
-		summary, err := summarizeErr(errors.New("job is timeout"))
+		tasks, err := m.findAllTasksForJob(se, job.id)
+		if err != nil {
+			m.jobLogger(job).Warn("fail to find all tasks for job")
```
Comment (Defined2014) [inline pkg/ttl/ttlworker/job_manager.go]: ditto

File: pkg/ttl/ttlworker/job_manager.go (hunk 1 above)
Comment (YangKeao) [reply pkg/ttl/ttlworker/job_manager.go]: Done. :+1:

File: pkg/ttl/ttlworker/job_manager.go (hunk 2 above)
Comment (YangKeao) [reply pkg/ttl/ttlworker/job_manager.go]: I think it's still meaningful to tell which function called `findAllTasksForJob`. To reach this target, I modified the log message to illustrate the difference between these two callers:

For `checkFinishedJob`, it'll print `fail to find all tasks for job. Skip check finished`.
For `updateHeartBeatForJob`, it'll print `fail to find all tasks for job. Summarize nothing for timeout job`.

**Review by lcwangchao — APPROVED** [review]

File: pkg/ttl/ttlworker/job_manager.go [hunk 4]
```diff
@@ -623,7 +634,7 @@ func (m *JobManager) rescheduleJobs(se session.Session, now time.Time) {
 
 				logger := m.jobLogger(job)
 				logger.Info(fmt.Sprintf("cancel job because %s", cancelReason))
-				summary, err := summarizeErr(errors.New(cancelReason))
+				summary, err := summarizeTaskResultWithError(nil, errors.New(cancelReason))
```
Comment (lcwangchao) [inline pkg/ttl/ttlworker/job_manager.go]: Do we need also to collect tasks here?

Comment (YangKeao) [reply pkg/ttl/ttlworker/job_manager.go]: Added.
