### PR TITLE
expression: fallback vectorized control expressions

### LINKED ISSUE #17725: expression: short-cut expressions cause unnecessary warnings, which even causes errors in update statements.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> use test;
Database changed
mysql> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert t values (1);
Query OK, 1 row affected (0.01 sec)

mysql> select case when a=1 then 1 else 1/(a-1) end from t;
+---------------------------------------+
| case when a=1 then 1 else 1/(a-1) end |
+---------------------------------------+
|                                     1 |
+---------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)

mysql> select if(a=1,1,1/(a-1)) from t;
+-------------------+
| if(a=1,1,1/(a-1)) |
+-------------------+
|                 1 |
+-------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)

 select ifnull(1,1/0);
+---------------+
| ifnull(1,1/0) |
+---------------+
|             1 |
+---------------+
1 row in set, 1 warning (0.00 sec)

select case  when 1/1 then 1/1 when 1/0 then 1/0 end;
+-----------------------------------------------+
| case  when 1/1 then 1/1 when 1/0 then 1/0 end |
+-----------------------------------------------+
|                                        1.0000 |
+-----------------------------------------------+
1 row in set, 2 warnings (0.01 sec)

```

We may also handle AND and OR.
```
mysql> select 0 and 1/0;
+-----------+
| 0 and 1/0 |
+-----------+
|         0 |
+-----------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```

```
mysql> select COALESCE(1, 1/0);
+------------------+
| COALESCE(1, 1/0) |
+------------------+
|                1 |
+------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```

```
mysql> select * from t0;
+------+
| c0   |
+------+
|    0 |
|    1 |
+------+
2 rows in set (0.00 sec)

mysql> select interval(t0.c0, -1,0,1,2,1/0) from t0;
+-------------------------------+
| interval(t0.c0, -1,0,1,2,1/0) |
+-------------------------------+
|                             2 |
|                             5 |
+-------------------------------+
2 rows in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```
### 2. What did you expect to see? (Required)
no warnings like in MySQL
### 3. What did you see instead (Required)
a warning
### 4. Affected version (Required)

v4.0.0

### 5. Root Cause Analysis
1. Bug from the vectorization run all execution paths,
2. constant folding folds all paths.

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #17725 

Problem Summary: the vectorized execution runs each branch, some of them cause unnecessary errors. In fact, the later computation depends on the results of formers, the vectorization of laters should consider the formers. This needs to change the interface of vectorization of expressions. 

We add fallback mechnism to avoid unnecessary warnings or errors. If errors/warnings occur for unsure branches, we fallback the vectorization to scalar execution.

In addition, the constant folding case is in  #19675.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: disable vectroization in the source file of control expressions.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test 

### Release note 

- fallback vectorize control expressions

### CODE REVIEW

**Comment by fzhedu** [comment]
```
mysql> select case  when 1/a then 1/a when 1/(a-1) then 1/(a-1) end from t;
+-------------------------------------------------------+
| case  when 1/a then 1/a when 1/(a-1) then 1/(a-1) end |
+-------------------------------------------------------+
|                                                1.0000 |
+-------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select case  when 1/a then 1/a when 1/(a-1) then 1/0 end from t;
+---------------------------------------------------+
| case  when 1/a then 1/a when 1/(a-1) then 1/0 end |
+---------------------------------------------------+
|                                            1.0000 |
+---------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select case  when 1/a then 1/a when 1/0 then 1/(a-1) end from t;
+---------------------------------------------------+
| case  when 1/a then 1/a when 1/0 then 1/(a-1) end |
+---------------------------------------------------+
|                                            1.0000 |
+---------------------------------------------------+
1 row in set, 1 warning (0.00 sec)


```
We should also disable this in constant folding.

**Comment by fzhedu** [comment]
@nullnotnil @SunRunAway should we disable fold constrants in case...when/if/ifnull expressions? because some branches may not be run, but actually run in folding contrants, like the examples above, which throw unexpected warnings.

**Comment by SunRunAway** [comment]
I think disabling it is not a good solution. It's better to fix the vectorized version of the function signature.

**Comment by zz-jason** [comment]
> I think disabling it is not a good solution. It's better to fix the vectorized version of the function signature.

agree, please fix the vectorized version expression.

**Comment by SunRunAway** [comment]
> @nullnotnil @SunRunAway should we disable fold constrants in case...when/if/ifnull expressions? because some branches may not be run, but actually run in folding contrants, like the examples above, which throw unexpected warnings.

Agree with it. This may be the only way to solve it.

**Review by SunRunAway — COMMENTED** [review]
LGTM 👍

**Review by ti-srebot — DISMISSED** [review]

**Comment by SunRunAway** [comment]
@qw4990 PTAL again.

File: expression/function_traits.go [hunk 1]
```diff
@@ -54,6 +54,9 @@ var unFoldableFunctions = map[string]struct{}{
 // are in child scope of an outer function, and the outer function is recursively folding its children.
 var DisableFoldFunctions = map[string]struct{}{
 	ast.Benchmark: {},
+	ast.If:        {},
+	ast.Ifnull:    {},
```
Comment (zz-jason) [inline expression/function_traits.go:58]: disabling the constant folding optimizations for these functions may bring performance regressions for existing applications. could you elaborate on the reason for disabling these functions?

Comment (SunRunAway) [reply expression/function_traits.go:58]: Could we use the similar fallback policy on constant folding? @fzhedu

Comment (fzhedu) [reply expression/function_traits.go:58]: cc @zz-jason from an oncall, the additional warnings/erros from unknown branches cause a normal `update` statement failed. for example: if(1,1,1/0) should not return errors/warnings, but acutall returns due to directly folding constrants. In contrast to correctness, reducing litttle performance is ok.

Comment (zz-jason) [reply expression/function_traits.go:58]: Can we fix the constant folding algorithm to not return an error or warning for cases like `if(1,1,1/0)`? Can we fix it by short circuit evaluation in the constant evaluation algorithm?

Comment (zz-jason) [reply expression/function_traits.go:58]: It's hard to see how much the performance is impacted. in some cases, folding `if` or `ifnull()` statement can let some filter to be pushed to tikv or enables us to utilize index range scan over table full scan.

Comment (fzhedu) [reply expression/function_traits.go:58]: I try it in #19675

File: expression/generator/control_vec.go [hunk 2]
```diff
@@ -228,6 +334,44 @@ func (b *builtinIfNull{{ .TypeName }}Sig) vectorized() bool {
 
 var builtinIfVec = template.Must(template.New("builtinIfVec").Parse(`
 {{ range .Sigs }}{{ with .Arg0 }}
+func (b *builtinIf{{ .TypeName }}Sig) fallbackEval{{ .TypeName }}(input *chunk.Chunk, result *chunk.Column) error {
```
Comment (lzmhhh123) [inline expression/generator/control_vec.go:337]: Maybe we need to add some comments to explain why we need to fallback for there functions.

File: expression/generator/control_vec.go [hunk 3]
```diff
@@ -238,30 +382,39 @@ func (b *builtinIf{{ .TypeName }}Sig) vecEval{{ .TypeName }}(input *chunk.Chunk,
...
 		return err
 	}
 	defer b.bufAllocator.put(buf1)
-	if err := b.args[1].VecEval{{ .TypeName }}(b.ctx, input, buf1); err != nil {
-		return err
-	}
+	err = b.args[1].VecEval{{ .TypeName }}(b.ctx, input, buf1)
 {{- end }}
+	afterWarns := sc.WarningCount()
+	if err != nil || afterWarns > beforeWarns {
```
Comment (lzmhhh123) [inline expression/generator/control_vec.go:398]: Is it necessary to check the error here? Are warnings enough?

File: expression/generator/control_vec.go (hunk 2 above)
Comment (fzhedu) [reply expression/generator/control_vec.go:337]: ok

File: expression/generator/control_vec.go (hunk 3 above)
Comment (fzhedu) [reply expression/generator/control_vec.go:398]: Some warnings may become errors in different sql mode. So each error and warning should detected here.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
