### PR TITLE
executor: fix plan replayer for sql file input wrongly fetch startTS after `OnTxnEnd`

### LINKED ISSUE #46197: `context provider not set` error when running `plan replayer dump explain <sql file>`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In a.sql:
```
select * from t1;
```

```sql
create table t1(a int, b int);
plan replayer dump explain 'sql.sql';
```

### 2. What did you expect to see? (Required)

Success.

### 3. What did you see instead (Required)

```
ERROR 1105 (HY000): context provider not set
```

### 4. What is your TiDB version? (Required)

master

Introduced by https://github.com/pingcap/tidb/pull/39863, affects from v6.6 to v7.3.

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #46197

Problem Summary:

When we are dumping replayer for the SQL file, it's in `handleFileTransInConn()` and already after `TxnManager.OnTxnEnd()`.
So we are unable to get the startTS, only got the error.

### What is changed and how it works?

Move the timing of getting startTS earlier.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: server/server_test.go [hunk 1]
```diff
@@ -100,3 +102,46 @@ func TestOptimizerDebugTrace(t *testing.T) {
 		require.NoError(t, os.Remove(filepath.Join(replayer.GetPlanReplayerDirName(), task.FileName)))
 	}
 }
+
+func TestIssue46197(t *testing.T) {
+	store, _ := testkit.CreateMockStoreAndDomain(t)
```
Comment (hawkingrei) [inline server/server_test.go:107]:
```suggestion
	store := testkit.CreateMockStore(t)
```

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
