### PR TITLE
planner: generate PointGet plans for PlanCache when all conditions are EQ

### LINKED ISSUE #29850: 8% tpcc performance degradation caused by #29238
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
run tpcc workload on aws ec2 config

### 2. What did you expect to see? (Required)

below prepared statement, all the predicates are all `equal =`, the optimizer should be able to choose the point get plan. kv_get is cheaper than cop in tikv.

```
SELECT
  `c_discount`,
  `c_last`,
  `c_credit`,
  `w_tax`
FROM
  `customer`,
  `warehouse`
WHERE
  `w_id` = ?
  AND `c_w_id` = `w_id`
  AND `c_d_id` = ?
  AND `c_id` = ?
```

```
	id              	task	estRows	operator info                                                                               	actRows	execution info                                                                                                                                                                                                                                                        	memory 	disk
	Projection_7    	root	0.00   	tpcc.customer.c_discount, tpcc.customer.c_last, tpcc.customer.c_credit, tpcc.warehouse.w_tax	1      	time:11.2ms, loops:2, Concurrency:OFF                                                                                                                                                                                                                                 	4.02 KB	N/A
	└─HashJoin_8    	root	0.00   	CARTESIAN inner join                                                                        	1      	time:11.2ms, loops:2, build_hash_table:{total:4.26ms, fetch:4.25ms, build:8.73µs}, probe:{concurrency:5, total:36.1ms, max:9.55ms, probe:2.5ms, fetch:33.6ms}                                                                                                        	48.5 KB	0 Bytes
	  ├─Point_Get_10	root	1      	table:customer, clustered index:PRIMARY(c_w_id, c_d_id, c_id)                               	1      	time:4.83ms, loops:2,                                                                                                                                                                                                                                                 	N/A    	N/A
	  └─Point_Get_11	root	1      	table:warehouse, handle:4220                                                                	1      	time:4.16ms, loops:2, Get:{num_rpc:2, total_time:5.14ms}, scan_detail: {total_process_keys: 2, total_process_keys_size: 720, total_keys: 2, rocksdb: {delete_skipped_count: 0, key_skipped_count: 0, block: {cache_hit_count: 27, read_count: 1, read_byte: 41.7 KB}}}	N/A    	N/A
```

### 3. What did you see instead (Required)
tablereader and tablerangescan
![image](https://user-images.githubusercontent.com/2316425/141999509-1405b207-120e-4055-8cc8-43785d1deba4.png)


### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
v5.3.0

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #29850

Problem Summary: planner: generate PointGet plans for PlanCache when all conditions are EQ

### What is changed and how it works?

planner: generate PointGet plans for PlanCache when all conditions are EQ

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

File: executor/prepared_test.go [hunk 1]
```diff
@@ -780,6 +780,71 @@ func (s *testSerialSuite) TestIssue28782(c *C) {
...
+	  c_last varchar(16) DEFAULT NULL,
+	  c_credit char(2) DEFAULT NULL,
+	  c_discount decimal(4,4) DEFAULT NULL,
+	  PRIMARY KEY (c_w_id,c_d_id,c_id),
+	  KEY idx_customer (c_w_id,c_d_id,c_last,c_first))`)
+	tk.MustExec(`CREATE TABLE warehouse (
+	  w_id int(11) NOT NULL,
+	  w_tax decimal(4,4) DEFAULT NULL,
+	  PRIMARY KEY (w_id))`)
+	tk.MustExec(`prepare stmt from 'SELECT c_discount, c_last, c_credit, w_tax
```
Comment (Reminiscent) [inline executor/prepared_test.go:814]: Please add some test that contains the `or` expression.

File: planner/core/find_best_task.go [hunk 2]
```diff
@@ -812,10 +812,12 @@ func (ds *DataSource) findBestTask(prop *property.PhysicalProperty, planCounter
 				p: dual,
 			}, cntPlan, nil
 		}
-		canConvertPointGet := len(path.Ranges) > 0 && path.StoreType == kv.TiKV && ds.isPointGetConvertableSchema() &&
-			// to avoid the over-optimized risk, do not generate PointGet for plan cache, for example,
-			// `pk>=$a and pk<=$b` can be optimized to a PointGet when `$a==$b`, but it can cause wrong results when `$a!=$b`.
-			!ds.ctx.GetSessionVars().StmtCtx.UseCache
+		canConvertPointGet := len(path.Ranges) > 0 && path.StoreType == kv.TiKV && ds.isPointGetConvertableSchema()
+
+		if ds.ctx.GetSessionVars().StmtCtx.UseCache && canConvertPointGet {
```
Comment (Reminiscent) [inline planner/core/find_best_task.go:817]: Maybe we can use `expression.MaybeOverOptimized4PlanCache(ctx, path.AccessConds)` rather than `ds.ctx.GetSessionVars().StmtCtx.UseCache`?

Comment (qw4990) [reply planner/core/find_best_task.go]: updated

File: executor/prepared_test.go (hunk 1 above)
Comment (qw4990) [reply executor/prepared_test.go:814]: updated

**Review by winoros — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
