### PR TITLE
ddl: use `tidb_allow_remove_auto_inc` to control drop column with auto_inc

### LINKED ISSUE #34891: Can't drop column with auto_increment
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` mysql
create table t (a int, b int auto_increment, key(b));
alter table t drop column b;
```

### 2. What did you expect to see? (Required)

We could use `modify column` to delete the auto_increment ID, so drop column with auto_increment should work.

```
create table t (a int, b int auto_increment, key(b));
alter table t modify column b int(11) not null;
```

### 3. What did you see instead (Required)

get error, error msg
```
ERROR 1075 (42000): Incorrect table definition; there can be only one auto column and it must be defined as a key
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #34891

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix can't drop column with auto_inc
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

File: ddl/column.go [hunk 1]
```diff
@@ -631,15 +631,6 @@ func checkDropColumn(t *meta.Meta, job *model.Job) (*model.TableInfo, *model.Col
...
 	idxInfos := listIndicesWithColumn(colName.L, tblInfo.Indices)
-	if len(idxInfos) > 0 {
-		for _, idxInfo := range idxInfos {
-			err = checkDropIndexOnAutoIncrementColumn(tblInfo, idxInfo)
-			if err != nil {
-				job.State = model.JobStateCancelled
-				return nil, nil, nil, err
-			}
-		}
-	}
```
Comment (tangenta) [inline ddl/column.go:642]: Please add a test so that it breaks when we support dropping column covered with composite index:

```sql
mysql> create table t (a int auto_increment, b int, c int, key(a, b));
Query OK, 0 rows affected (0.01 sec)

mysql> alter table t drop column b;
ERROR 8200 (HY000): can't drop column b with composite index covered or Primary Key covered now

```

Comment (Defined2014) [reply ddl/column.go:642]: In MySQL, the key will change to key(a), the auto_increment will keep.

**Review by tangenta — APPROVED** [review]

**Comment by breezewish** [comment]
I'm interested in why does this feature not enabled by default while MySQL supports it? Are there any pitfalls?

**Comment by Defined2014** [comment]
> I'm interested in why does this feature not enabled by default while MySQL supports it? Are there any pitfalls?

Maybe we could default enable `tidb_allow_remove_auto_inc`. /cc @bb7133
