### PR TITLE
disttask/ddl: refine manager error handling

### LINKED ISSUE #48064: add index failed with error “Error 1105 (HY000): [pd] failed to get cluster id” when inject pdleader network partition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run workload
2、add index for one table
3、inject pdleader network partition

case config
  - name: config_ha_pdleader_to_all_network_partition
    default: |
      tag: "ha-test-add-index"
      workloads:
        - type: sysbench
          storage: s3://benchmark/sysbench_64_7000w
          db: sysbench_64_7000w
          tableNum: 64
          tableSize: 70000000
          threads: 64
          subType: oltp_read_write
          ignoreErrors: "all"
      cases:
        - name: "ha_pdleader_to_all_network_partition"
          warmUpTime: 1m
          faultType: network_partition
          selector: "pdleader_to_all"
          period: "@every 5m"
          faultDuration: 2m
          faultTotalRunTime: 30m
          ddl:
            addIndex:
              - db: "sysbench_64_7000w"
                table: "sbtest1"
                timeout: 60m
                times: 5
                index_col_name: "c"
                job_type: "ingest"
                admin_check: false
                count_check: false

### 2. What did you expect to see? (Required)
add index success

### 3. What did you see instead (Required)
add index failed with error “Error 1105 (HY000): [pd] failed to get cluster id” when inject pdleader network partition

"add index failed at 2023-10-29 16:27:07 (Error 1105 (HY000): [pd] failed to get cluster id)
operatorLogs:
[2023-10-29 16:25:16] ###### start adding index
alter table sbtest1 add index index_test_1698567916120 (c)
[2023-10-29 16:25:16] ###### wait for ddl job finish"

### 4. What is your TiDB version? (Required)
git hash：3682bd82cac05a75241ed9fc9f29a1d320d776a7

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #46258, close #48064

Problem Summary:

### What is changed and how it works?
1. Check error retryable when init scheduler.
2. Add ErrCreatePDClient for ha test met it.
3. Check retryable error for dist task in ddl framework.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

File: pkg/disttask/framework/scheduler/scheduler.go [hunk 1]
```diff
@@ -474,13 +474,13 @@ func (s *BaseScheduler) onError(err error) {
...
 	err = errors.Trace(err)
-	logutil.Logger(s.logCtx).Error("onError", zap.Error(err))
+	logutil.Logger(s.logCtx).Error("onError", zap.Error(err), zap.Stack("stack"))
 	s.mu.Lock()
 	defer s.mu.Unlock()
 
 	if s.mu.err == nil {
 		s.mu.err = err
-		logutil.Logger(s.logCtx).Error("scheduler error", zap.Error(err))
+		logutil.Logger(s.logCtx).Error("scheduler meet first error", zap.Error(err))
```
Comment (ywqzzy) [inline pkg/disttask/framework/scheduler/scheduler.go:483]:
```suggestion
		logutil.Logger(s.logCtx).Error("scheduler met first error", zap.Error(err))
```

**Review by lance6716 — APPROVED** [review]
