### PR TITLE
*: fix goleak in the client-go

### LINKED ISSUE #49038: found unexpected goroutines github.com/tikv/client-go/v2/config/retry.(*Config).createBackoffFn.newBackoffFn.func2
```
goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 119983 in state select, with github.com/tikv/client-go/v2/config/retry.(*Config).createBackoffFn.newBackoffFn.func2 on top of the stack:

github.com/tikv/client-go/v2/config/retry.(*Config).createBackoffFn.newBackoffFn.func2({0x97b7b68, 0xd881bc0}, 0xffffffffffffffff)

	external/com_github_tikv_client_go_v2/config/retry/config.go:194 +0x5f5

github.com/tikv/client-go/v2/config/retry.(*Backoffer).BackoffWithCfgAndMaxSleep(0xc01cc58d80, 0xc000c4f9e0, 0x18?, {0x9787700, 0xc03436d8c0})

	external/com_github_tikv_client_go_v2/config/retry/backoff.go:195 +0xb44

github.com/tikv/client-go/v2/config/retry.(*Backoffer).Backoff(0xc01cc58d80, 0xc000c4f9e0, {0x9787700, 0xc03436d8c0})

	external/com_github_tikv_client_go_v2/config/retry/backoff.go:122 +0x2d5

github.com/tikv/client-go/v2/tikv.(*KVStore).getTimestampWithRetry(0xc00083f800, 0xc01cc58d80, {0x7c95987, 0x6})

	external/com_github_tikv_client_go_v2/tikv/kv.go:435 +0x5fd

github.com/tikv/client-go/v2/tikv.(*KVStore).GetTimestampWithRetry(0xc002df1ba0?, 0xc002df19f8?, {0x7c95987, 0x6})

	external/com_github_tikv_client_go_v2/tikv/kv.go:410 +0x45

github.com/tikv/client-go/v2/txnkv/transaction.keepAlive(0xc00ab61880, 0xc00266c9c0, {0xc004183024, 0x13, 0x13}, 0xc0255bc8c0)

	external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1170 +0x612

created by github.com/tikv/client-go/v2/txnkv/transaction.(*ttlManager).run in goroutine 117003

	external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1130 +0x2e6

]
```

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/34519/pipeline

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #49038

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

File: tests/realtikvtest/testkit.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ func RunTestMain(m *testing.M) {
 		goleak.IgnoreTopFunction("net/http.(*persistConn).writeLoop"),
 		goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/txnkv/transaction.keepAlive"),
 		// backoff function will lead to sleep, so there is a high probability of goroutine leak while it's doing backoff.
-		goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.(*Config).createBackoffFn.newBackoffFn.func2"),
+		goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/config/retry.(*Config).createBackoffFn.newBackoffFn.func2"),
```
Comment (Defined2014) [inline tests/realtikvtest/testkit.go:83]: Maybe we could change all files,
```
./tests/realtikvtest/testkit.go:                goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./tests/realtikvtest/testkit.go:                goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.(*Config).createBackoffFn.newBackoffFn.func2"),
./docs/design/2021-04-26-lock-view.md:    * There are two types of deadlock errors internally: retryable or non-retryable. The transaction will internally retry on retryable deadlocks and won't report error to the client. Therefore, the user are typically more interested in the non-retryable deadlocks.
./br/pkg/lightning/backend/backend.go:  importMaxRetryTimes = 3 // tikv-importer has done retry internally. so we don't retry many times.
./pkg/sessiontxn/isolation/optimistic.go:// If the session is already in transaction, enable retry or internal SQL could retry.
./pkg/sessiontxn/isolation/optimistic.go:       // The internal transaction could always retry.
./pkg/store/copr/copr_test/main_test.go:                goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/nontransactionaltest/main_test.go:                goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/bootstraptest/main_test.go:               goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/test/vars/main_test.go:           goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/test/txn/main_test.go:            goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/test/variable/main_test.go:               goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/test/meta/main_test.go:           goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/test/privileges/main_test.go:             goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/test/common/main_test.go:         goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/test/main_test.go:                goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/clusteredindextest/main_test.go:          goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/schematest/main_test.go:          goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/temporarytabletest/main_test.go:          goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
./pkg/session/main_test.go:             goleak.IgnoreTopFunction("github.com/tikv/client-go/v2/internal/retry.newBackoffFn.func1"),
```

Comment (hawkingrei) [reply tests/realtikvtest/testkit.go:83]: Done

**Review by you06 — APPROVED** [review]
LGTM

File: tests/realtikvtest/testkit.go (hunk 1 above)
Comment (hawkingrei) [reply tests/realtikvtest/testkit.go:83]: Done

**Review by Defined2014 — APPROVED** [review]
