### PR TITLE
types: fix unsigned decimal

### LINKED ISSUE #6101: In-compatible behavior with MySQL when insert signed values into unsigned decimal column
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
set sql_mode='';
create table t1 ( quantity decimal(2) unsigned);
insert into t1 values (500), (-500), (~0), (-1);
select * from t1;
```

2. What did you expect to see?
`MySQL is: 99、0、99、0`

3. What did you see instead?
`TiDB is: 99、-99、99、-1`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
| Release Version: v2.0.0-rc.1-73-g67c948b
Git Commit Hash: 67c948b609503b77b4af7d7aba59b763f261b0a0
Git Branch: master
UTC Build Time: 2018-03-20 07:48:57
GoVersion: go version go1.9 darwin/amd64
TiKV Min Version: 1.1.0-dev.2 |
```

### PR DESCRIPTION
**Pull request by yangwenmai**
fix #6101

### CODE REVIEW

**Comment by yangwenmai** [comment]
CI error:

```
Build-agent version 0.0.4761-f18e895 (2018-03-20T01:12:48+0000)
Starting container golang:1.10
  image cache not found on this host, downloading golang:1.10
Error response from daemon: manifest for golang:1.10 not found
```

File: ddl/ddl_db_test.go [hunk 1]
```diff
@@ -767,6 +767,16 @@ func (s *testDBSuite) TestIssue2293(c *C) {
 	s.tk.MustQuery("select * from t_issue_2293").Check(testkit.Rows("1"))
 }
 
+func (s *testDBSuite) TestIssue6101(c *C) {
+	s.tk = testkit.NewTestKit(c, s.store)
+	s.tk.MustExec("use " + s.schemaName)
+	s.tk.MustExec("set sql_mode=''")
+	s.tk.MustExec("create table t1 (quantity decimal(2) unsigned);")
+	s.tk.MustExec("insert into t1 values (500), (-500), (~0), (-1);")
```
Comment (zhexuany) [inline ddl/ddl_db_test.go]: Are u sure you run this insert query against mysql? 

I am confused because when I tried to, mysql give me an error.

```
mysql> insert into t1 values (500), (-500), (~0), (-1);
ERROR 1264 (22003): Out of range value for column 'quantity' at row 1
```

Comment (zhexuany) [reply ddl/ddl_db_test.go]: FYI, my mysql version is `Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 5.7.21 Homebrew`

Comment (zhexuany) [reply ddl/ddl_db_test.go]: My bad, I forget to set sql_mode.

File: ddl/ddl_db_test.go [hunk 2]
```diff
@@ -995,7 +1005,7 @@ LOOP:
 	c.Assert(count, Greater, int64(0))
 }
 
-// This test is for insert value with a to-be-dropped column when do drop column.
+// testDropColumn2 This test is for insert value with a to-be-dropped column when do drop column.
```
Comment (zhexuany) [inline ddl/ddl_db_test.go]: s/testDropColumn2 This test is for insert value/testDropColumn2 is for inserting value

Comment (zhexuany) [reply ddl/ddl_db_test.go]: @yangwenmai friendly ping

**Comment by coocood** [comment]
@yangwenmai 
We also need to make sure when `sql_mode` is not empty, it returns `Out of range` error.

**Comment by yangwenmai** [comment]
I added a test case where sql_mode is not empty.

**Comment by coocood** [comment]
LGTM

@yangwenmai 
Thank you!
