### PR TITLE
executor: fix value swapping and multi-updates in UPDATE statement

### LINKED ISSUE #11911: Wrong result when `update ... set ...` on same table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table t(x int, y int);
insert into t values();
update t t1, t t2 set t2.y=1, t1.x=2;
select * from t;
```
2. What did you expect to see?

image

3. What did you see instead?

image

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

image

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @qw4990

### LINKED ISSUE #19137: Can not swap values by a multi-tables update
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1, t2;
create table t1 (c_str varchar(40));
create table t2 (c_str varchar(40));
insert into t1 values ('Alice');
insert into t2 values ('Bob');
select t1.c_str, t2.c_str from t1, t2 where t1.c_str <= t2.c_str;
update t1, t2 set t1.c_str = t2.c_str, t2.c_str = t1.c_str where t1.c_str <= t2.c_str;
select t1.c_str, t2.c_str from t1, t2 where t1.c_str <= t2.c_str;
```

### 2. What did you expect to see? (Required)

The values of `t1.c_str` and `t2.c_str` should be swapped in the above case, that is, the last selection should return an empty set.

### 3. What did you see instead (Required)

```
mysql> select t1.c_str, t2.c_str from t1, t2 where t1.c_str <= t2.c_str;
+-------+-------+
| c_str | c_str |
+-------+-------+
| Alice | Bob   |
+-------+-------+
1 row in set (0.06 sec)

mysql> update t1, t2 set t1.c_str = t2.c_str, t2.c_str = t1.c_str where t1.c_str <= t2.c_str;
Query OK, 1 row affected (0.06 sec)
Rows matched: 2  Changed: 1  Warnings: 0

mysql> select t1.c_str, t2.c_str from t1, t2 where t1.c_str <= t2.c_str;
+-------+-------+
| c_str | c_str |
+-------+-------+
| Bob   | Bob   |
+-------+-------+
1 row in set (0.05 sec)

```

### 4. What is your TiDB version? (Required)

master @ 8978773f5e3d43a100550e6babea9904a99e5938
release-4.0 @ 3948c7ba7b5d4a081abf2162b791ab67fe650882

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #11911, close #19137, amendment to #20603 (#20594)

Problem Summary: In `UPDATE` statement:

- Cannot swap values in either single table or multiple tables. (#19137)
- Got wrong results for multi-updates on the same table. (#11911)

### What is changed and how it works?

If we have a table:
``` mysql
create table t(a int primary key, b int, c int);
insert into t values (1, 2, 3);
```

For #19137 (changes in `UpdateExec.composeNewRow`):

- Evaluate expressions using old row data rather than new values.
``` mysql
update t set a=b, b=a; # b ← 2, a ← 1
```

For #11911 :

- Modify `updateRowKeys` to allow the same row be updated once for each table alias (instead of once for each table).

``` mysql
# Originally
update t m, t n set m.c=5, m.b=10, n.b=20; # only updates from m will be written into t;

# Now
update t m, t n set m.c=5, m.b=10, n.b=20; # both updates from m and n will be written into t;
```

- Use `mergedRowData` to merge modifications to a row from each table alias.

``` mysql
update t m, t n set m.c=5, m.b=10, n.b=20;
# Before merge
# | as name |        m        |        n        |
# | --------|-----------------|-----------------|
# | column  |  a  |  b  |  c  |  a  |  b  |  c  |
# | old row |  1  |  2  |  3  |  1  |  2  |  3  |
# | new row |  1  |  10 |  5  |  1  |  20 |  3  |
# | flag    |     |  *  |  *  |     |  *  |     |
# 
# Previous updates to the same row of the same table will be merged into current row.
# For example, updates from m will be merged into n,
# | as name |        m        |        n        |
# | --------|-----------------|-----------------|
# | column  |  a  |  b  |  c  |  a  |  b  |  c  |
# | old row |  1  |  2  |  3  |  1  |  10 |  5  |
# | new row |  1  |  10 |  5  |  1  |  20 |  5  |
# | flag    |     |  *  |  *  |     |  *  |     |
```

- Change the computations order in `UpdateExec.updateRows`:
  1. Prepare handles... (`UpdateExec.prepare`) 
  2. Compose new row for non-generated columns (`composeFunc`)
  3. Merge modifications for non-generated columns (`UpdateExec.merge`)
  4. Compose new row for generated columns using newly evaluated values (`composeGeneratedColumns`)
  5. Merge modifications for generated columns (`UpdateExec.merge`)
  6. Write back to table (`UpdateExec.exec`)

For #20603 :
- Reject the update to a table's primary keys if these exists actual multi-updates to that table (In `checkUpdateLists`). For example:
``` mysql
update t m, t n set m.a=10, n.b=20; # reject
update t m, t n set m.a=10;         # ok
```

### Related changes

- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Support value swapping in UPDATE, e.g. `update t set a=b, b=a`.
  - This may break the compatibility if you have queries like `update t set b=a, c=b`, as the assignments will use values from the original row instead of the newly evaluated row.
- Bug fixes for multi-update on the same table, e.g. `update t m, t n set m.a=1, n.b=2`.
  - Previously, updates from exactly one alias of the same table (`m.a` or `n.b`) can be written to storage.
  - Now this has been corrected, both updates can take effects.

### CODE REVIEW

**Comment by dyzsr** [comment]
PTAL @SunRunAway

File: executor/executor_test.go [hunk 1]
```diff
@@ -1802,15 +1802,15 @@ func (s *testSuiteP1) TestMultiUpdate(c *C) {
 	// Test UPDATE ... set_lists.
 	tk.MustExec(`UPDATE test_mu SET b = 0, c = b WHERE a = 4`)
 	result = tk.MustQuery(`SELECT * FROM test_mu ORDER BY a`)
-	result.Check(testkit.Rows(`1 7 2`, `4 0 0`, `7 8 9`))
```
Comment (lzmhhh123) [inline executor/executor_test.go:1805]: Is the result consistent with MySQL?

Comment (dyzsr) [reply executor/executor_test.go:1805]: No. It could be more consistent with PG and SQLite as discussed in #19137.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: executor/update.go [hunk 2]
```diff
@@ -241,14 +273,21 @@ func (e *UpdateExec) fastComposeNewRow(rowIdx int, oldRow []types.Datum, cols []
...
 		if handleFound && e.canNotUpdate(oldRow[handleIdx]) {
 			continue
 		}
-		val, err := assign.Expr.Eval(e.evalBuffer.ToRow())
+		var val types.Datum
+		var err error
+		if i < e.virtualAssignmentsOffset {
+			val, err = assign.Expr.Eval(oldRowBuffer.ToRow())
+		} else {
+			val, err = assign.Expr.Eval(e.evalBuffer.ToRow())
```
Comment (lysu) [inline executor/update.go:289]: how about add a swap + generated column test case~?

File: executor/update.go [hunk 3]
```diff
@@ -100,10 +116,26 @@ func (e *UpdateExec) exec(ctx context.Context, schema *expression.Schema, row, n
 			continue
 		}
 
+		var updatedData []types.Datum
+		v, ok = e.updatedRowData[content.TblID].Get(handle)
+		if !ok {
+			updatedData = make([]types.Datum, len(oldData))
+			copy(updatedData, oldData)
```
Comment (lysu) [inline executor/update.go:123]: can we avoid this alloc + copy when it's a single table update without swap any value(e.g. update t set v = 2 where k = 1)

**Comment by jackysp** [comment]
PTAL @bobotu

File: executor/update.go (hunk 2 above)
Comment (dyzsr) [reply executor/update.go:289]: Thanks. I've just added some test cases and found bugs in generated columns of table with multiple aliases. I will fix it soon.

**Comment by dyzsr** [comment]
Waiting for #20603

**Comment by wjhuang2016** [comment]
@cfzjywxk PTAL

**Comment by zhouqiang-cl** [comment]
We need update branch, then can pass e2e tests

**Review by bobotu — COMMENTED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
It seems not to be a `compatibility-breaker`, the behavior is correct for now.

**Comment by lysu** [comment]
rest LGTM

**Review by dyzsr — COMMENTED** [review]
.

**Comment by dyzsr** [comment]
PTAL @lysu @cfzjywxk

**Comment by lysu** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
