### PR TITLE
*: rewrite origin SQL with default DB for SQL bindings

### LINKED ISSUE #20417: Plan binding evolution rejecting improved plans
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Consider the following test case:

```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
 pk VARBINARY(36) NOT NULL PRIMARY KEY,
 b BIGINT NOT NULL,
 c BIGINT NOT NULL,
 pad VARBINARY(2048),
 INDEX (b)
);
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM dual;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT uuid(), FLOOR(RAND()*5), FLOOR(RAND()*1000000), HEX(RANDOM_BYTES(1000)) FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
SELECT SLEEP(2);
ANALYZE TABLE t1;
SELECT SLEEP(2);

SELECT * FROM t1 WHERE b = 2 AND c = 123412;
SELECT * FROM t1 WHERE b = 3 AND c = 392812;
SELECT * FROM t1 WHERE b = 4 AND c = 932932;
DROP GLOBAL BINDING FOR SELECT * FROM t1 WHERE b = 3 AND c = 321210; -- drop incase this example is run twice
SHOW GLOBAL BINDINGS;
ADMIN CAPTURE BINDINGS;
SHOW GLOBAL BINDINGS;

EXPLAIN SELECT * FROM t1 WHERE b = 4 AND c = 3921228;
ALTER TABLE t1 ADD INDEX (c);
SELECT SLEEP(2);
ANALYZE TABLE t1;
SELECT SLEEP(2);
EXPLAIN SELECT * FROM t1 WHERE b = 1 AND c = 275628;

SELECT SLEEP(10); -- allow background work from alter table etc to settle

SET tidb_evolve_plan_baselines = 1;
SELECT SLEEP(2);
SELECT * FROM t1 WHERE b = 2 AND c = 3924541;

SHOW GLOBAL BINDINGS;
SELECT SLEEP(1);
SHOW GLOBAL BINDINGS;
SELECT SLEEP(10);
SHOW GLOBAL BINDINGS;
```

### 2. What did you expect to see? (Required)

The new plan is faster, and should be accepted. Here is the output from `EXPLAIN ANALYZE`:

```sql
mysql> explain analyze SELECT /*+ use_index(@`sel_1` `test`.`t1` `b`)*/ * FROM `t1` WHERE `b`=2 AND `c`=123412;
+-------------------------------+-----------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+----------------------+------+
| id                            | estRows   | actRows | task      | access object        | execution info                                                                                                                             | operator info                 | memory               | disk |
+-------------------------------+-----------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+----------------------+------+
| IndexLookUp_8                 | 0.20      | 0       | root      |                      | time:457.133993ms, loops:1, cop_task: {num: 1, max:495.556µs, proc_keys: 0, rpc_num: 1, rpc_time: 469.706µs, copr_cache_hit_ratio: 1.00}   |                               | 6.245874404907227 MB | N/A  |
| ├─IndexRangeScan_5(Build)     | 128139.00 | 128389  | cop[tikv] | table:t1, index:b(b) | time:52ms, loops:130                                                                                                                       | range:[2,2], keep order:false | N/A                  | N/A  |
| └─Selection_7(Probe)          | 0.20      | 0       | cop[tikv] |                      | time:0ns, loops:0                                                                                                                          | eq(test.t1.c, 123412)         | N/A                  | N/A  |
|   └─TableRowIDScan_6          | 128139.00 | 0       | cop[tikv] | table:t1             | time:0ns, loops:0                                                                                                                          | keep order:false              | N/A                  | N/A  |
+-------------------------------+-----------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+----------------------+------+
4 rows in set (0.46 sec)

mysql> explain analyze SELECT /*+ use_index(@`sel_1` `test`.`t1` `c`)*/ * FROM `test`.`t1` WHERE `b`=2 AND `c`=3924541;
+-------------------------------+---------+---------+-----------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| id                            | estRows | actRows | task      | access object        | execution info                                                                                                                           | operator info                             | memory    | disk |
+-------------------------------+---------+---------+-----------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| IndexLookUp_8                 | 0.00    | 0       | root      |                      | time:706.484µs, loops:1, cop_task: {num: 1, max:595.214µs, proc_keys: 0, rpc_num: 1, rpc_time: 564.225µs, copr_cache_hit_ratio: 0.00}    |                                           | 185 Bytes | N/A  |
| ├─IndexRangeScan_5(Build)     | 0.00    | 0       | cop[tikv] | table:t1, index:c(c) | time:0s, loops:1                                                                                                                         | range:[3924541,3924541], keep order:false | N/A       | N/A  |
| └─Selection_7(Probe)          | 0.00    | 0       | cop[tikv] |                      | time:0ns, loops:0                                                                                                                        | eq(test.t1.b, 2)                          | N/A       | N/A  |
|   └─TableRowIDScan_6          | 0.00    | 0       | cop[tikv] | table:t1             | time:0ns, loops:0                                                                                                                        | keep order:false                          | N/A       | N/A  |
+-------------------------------+---------+---------+-----------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
4 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

The new plan is rejected:

```sql
mysql> SHOW GLOBAL BINDINGS\G
*************************** 1. row ***************************
Original_sql: select * from t1 where b = ? and c = ?
    Bind_sql: SELECT /*+ use_index(@`sel_1` `test`.`t1` `b`)*/ * FROM `t1` WHERE `b`=2 AND `c`=123412
  Default_db: test
      Status: using
 Create_time: 2020-10-12 14:50:09.461
 Update_time: 2020-10-12 14:50:09.461
     Charset: 
   Collation: 
      Source: capture
*************************** 2. row ***************************
Original_sql: select * from t1 where b = ? and c = ?
    Bind_sql: SELECT /*+ use_index(@`sel_1` `test`.`t1` `c`)*/ * FROM `test`.`t1` WHERE `b`=2 AND `c`=3924541
  Default_db: test
      Status: rejected
 Create_time: 2020-10-12 14:50:52.311
 Update_time: 2020-10-12 14:50:55.311
     Charset: utf8
   Collation: utf8_general_ci
      Source: evolve
2 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```sql
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1357-g38ecab6a7
Edition: Community
Git Commit Hash: 38ecab6a7c1dde3c9a2ed2713b3a69d63f662b77
Git Branch: master
UTC Build Time: 2020-10-12 12:52:19
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: close #20417 

Problem Summary:

### What is changed and how it works?

Parser:
- Add a flag `RestoreWithDefaultDB` for `Restore`. If has this flag, `TableName.restoreName` will add default DB name if it's schema name is null.

Here is the [parser pr](https://github.com/pingcap/parser/pull/1105)

TiDB:
- For SQL bindings, we use `Stmt.Restore` with `RestoreWithDefaultDB` flag instead of `Stmt.Text()`
- Add `stmtCtx.WithDefaultDBSQL` for SPM capture.
- remove default DB check when compare two bind record

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- 
- rewrite origin SQL with default DB for SQL bindings

### CODE REVIEW

**Review by eurekaka — COMMENTED** [review]
Would this PR break backward compatibility? For example, if there are existing bindings whose original_sql is `select * from t where a > ?`, after applying this PR, the query `select * from t where a > 1` cannot hit this binding anymore?

**Comment by rebelice** [comment]
> Would this PR break backward compatibility? For example, if there are existing bindings whose original_sql is `select * from t where a > ?`, after applying this PR, the query `select * from t where a > 1` cannot hit this binding anymore?

Yes, may need an upgrade tool before it takes effect.

File: bindinfo/bind_test.go [hunk 1]
```diff
@@ -1688,3 +1705,71 @@ func (s *testSuite) TestIssue19836(c *C) {
...
+	// Test for evolve baseline
+	s.cleanBindingEnv(tk)
+	tk.MustExec("set @@tidb_evolve_plan_baselines=1")
+	tk.MustExec("create global binding for select * from t WHERE c=3924541 using select /*+ use_index(@sel_1 test.t b) */ * from t WHERE c=3924541")
+	rows = tk.MustQuery("show global bindings").Rows()
+	c.Assert(len(rows), Equals, 1)
+	c.Assert(rows[0][0], Equals, "select * from test . t where c = ?")
+	c.Assert(rows[0][1], Equals, "SELECT /*+ use_index(@sel_1 test.t b)*/ * FROM test.t WHERE c = 3924541")
+	tk.MustExec("select /*+ use_index(t c)*/ * from t where c=3924541")
+	c.Assert(tk.Se.GetSessionVars().StmtCtx.IndexNames[0], Equals, "t:idxc")
```
Comment (eurekaka) [inline bindinfo/bind_test.go:1760]: If the hint in the binding is valid, planner should choose `idxb` here.

File: bindinfo/bind_test.go [hunk 2]
```diff
@@ -1688,3 +1705,71 @@ func (s *testSuite) TestIssue19836(c *C) {
...
+
+	// Test for evolve baseline
+	s.cleanBindingEnv(tk)
+	tk.MustExec("set @@tidb_evolve_plan_baselines=1")
+	tk.MustExec("create global binding for select * from t WHERE c=3924541 using select /*+ use_index(@sel_1 test.t b) */ * from t WHERE c=3924541")
+	rows = tk.MustQuery("show global bindings").Rows()
+	c.Assert(len(rows), Equals, 1)
+	c.Assert(rows[0][0], Equals, "select * from test . t where c = ?")
+	c.Assert(rows[0][1], Equals, "SELECT /*+ use_index(@sel_1 test.t b)*/ * FROM test.t WHERE c = 3924541")
+	tk.MustExec("select /*+ use_index(t c)*/ * from t where c=3924541")
```
Comment (eurekaka) [inline bindinfo/bind_test.go:1759]: :s/use_index(t c)/use_index(t idxc)?

File: bindinfo/handle.go [hunk 3]
```diff
@@ -522,7 +522,7 @@ func (c cache) removeDeletedBindRecord(hash string, meta *BindRecord) {
 func (c cache) setBindRecord(hash string, meta *BindRecord) {
 	metas := c[hash]
 	for i := range metas {
-		if metas[i].Db == meta.Db && metas[i].OriginalSQL == meta.OriginalSQL {
+		if metas[i].OriginalSQL == meta.OriginalSQL {
```
Comment (eurekaka) [inline bindinfo/handle.go:525]: Change to `isSame()`?

File: planner/core/planbuilder.go [hunk 4]
```diff
@@ -726,23 +726,48 @@ func (b *PlanBuilder) buildSet(ctx context.Context, v *ast.SetStmt) (Plan, error
...
+	if hintsStr == "" && len(warns) > 0 {
+		return warns[0]
+	}
+	return nil
+}
+
 func (b *PlanBuilder) buildCreateBindPlan(v *ast.CreateBindingStmt) (Plan, error) {
 	charSet, collation := b.ctx.GetSessionVars().GetCharsetInfo()
+
+	// Because we use HintedNode.Restore instead of HintedNode.Text, so we need do some check here
```
Comment (eurekaka) [inline planner/core/planbuilder.go:762]: This dbName adjustment is not necessary for BindSQL actually? so this check is unnecessary either?

File: planner/core/preprocess.go [hunk 5]
```diff
@@ -258,8 +259,8 @@ func (p *preprocessor) checkBindGrammar(originNode, hintedNode ast.StmtNode) {
 			return
 		}
 	}
-	originSQL := parser.Normalize(originNode.Text())
-	hintedSQL := parser.Normalize(hintedNode.Text())
+	originSQL := parser.Normalize(utilparser.RestoreWithDefaultDB(originNode, defaultDB))
+	hintedSQL := parser.Normalize(utilparser.RestoreWithDefaultDB(hintedNode, defaultDB))
```
Comment (eurekaka) [inline planner/core/preprocess.go:263]: This change would relax the restriction for CREATE BINDING / DROP BINDING? IMHO this change is unnecessary for this PR?

File: planner/optimize.go [hunk 6]
```diff
@@ -273,13 +274,16 @@ func optimize(ctx context.Context, sctx sessionctx.Context, node ast.Node, is in
 	return finalPlan, names, cost, err
 }
 
-func extractSelectAndNormalizeDigest(stmtNode ast.StmtNode) (ast.StmtNode, string, string) {
+func extractSelectAndNormalizeDigest(stmtNode ast.StmtNode, defaultDB string) (ast.StmtNode, string, string) {
 	switch x := stmtNode.(type) {
 	case *ast.ExplainStmt:
+		if len(x.Text()) == 0 {
+			return x.Stmt, "", ""
+		}
```
Comment (eurekaka) [inline planner/optimize.go:282]: When will this happen?

File: planner/optimize.go [hunk 7]
```diff
@@ -312,7 +316,10 @@ func extractSelectAndNormalizeDigest(stmtNode ast.StmtNode) (ast.StmtNode, strin
 		}
 	case *ast.SelectStmt, *ast.SetOprStmt, *ast.DeleteStmt, *ast.UpdateStmt, *ast.InsertStmt:
 		plannercore.EraseLastSemicolon(x)
-		normalizedSQL, hash := parser.NormalizeDigest(x.Text())
+		if len(x.Text()) == 0 {
+			return x, "", ""
+		}
```
Comment (eurekaka) [inline planner/optimize.go:321]: Ditto.

File: types/parser_driver/value_expr.go [hunk 8]
```diff
@@ -96,7 +96,8 @@ func (n *ValueExpr) Restore(ctx *format.RestoreCtx) error {
 	case types.KindFloat64:
 		ctx.WritePlain(strconv.FormatFloat(n.GetFloat64(), 'e', -1, 64))
 	case types.KindString:
-		if n.Type.Charset != "" {
+		if n.Type.Charset != "" &&
+			(!ctx.Flags.HasStringWithoutDefaultCharset() || n.Type.Charset != mysql.DefaultCharset) {
```
Comment (eurekaka) [inline types/parser_driver/value_expr.go:100]: How is this change related to this PR?

File: util/parser/ast.go [hunk 9]
```diff
@@ -45,3 +48,14 @@ func (i *implicitDatabase) Enter(in ast.Node) (out ast.Node, skipChildren bool)
 func (i *implicitDatabase) Leave(in ast.Node) (out ast.Node, ok bool) {
 	return in, true
 }
+
+// RestoreWithDefaultDB returns restore strings for StmtNode with defaultDB
+func RestoreWithDefaultDB(node ast.StmtNode, defaultDB string) string {
+	var sb strings.Builder
+	ctx := format.NewRestoreCtx(format.RestoreStringSingleQuotes|format.RestoreSpacesAroundBinaryOperation|format.RestoreStringWithoutDefaultCharset, &sb)
```
Comment (eurekaka) [inline util/parser/ast.go:55]: Add a comment to explain why each flag is needed?

File: bindinfo/bind_test.go [hunk 10]
```diff
@@ -1688,3 +1705,71 @@ func (s *testSuite) TestIssue19836(c *C) {
...
+	rows = tk.MustQuery("show global bindings").Rows()
+	c.Assert(len(rows), Equals, 1)
+	c.Assert(rows[0][0], Equals, "select * from test . t where b = ? and c = ?")
+	c.Assert(rows[0][1], Equals, "SELECT /*+ use_index(@`sel_1` `test`.`t` `idxb`)*/ * FROM `test`.`t` WHERE `b`=2 AND `c`=213124")
+	tk.MustExec("set @@tidb_capture_plan_baselines = off")
+
+	// Test for evolve baseline
+	s.cleanBindingEnv(tk)
+	tk.MustExec("set @@tidb_evolve_plan_baselines=1")
+	tk.MustExec("create global binding for select * from t WHERE c=3924541 using select /*+ use_index(@sel_1 test.t b) */ * from t WHERE c=3924541")
```
Comment (eurekaka) [inline bindinfo/bind_test.go:1754]: :s/use_index(@sel_1 test.b b)/use_index(@sel_1 test.b idxb)?

File: planner/core/planbuilder.go [hunk 11]
```diff
@@ -726,23 +726,48 @@ func (b *PlanBuilder) buildSet(ctx context.Context, v *ast.SetStmt) (Plan, error
...
+	if err := checkHintedSQL(v.HintedNode.Text(), charSet, collation, b.ctx.GetSessionVars().CurrentDB); err != nil {
+		return nil, err
+	}
+
 	p := &SQLBindPlan{
 		SQLBindOp:    OpSQLBindCreate,
-		NormdOrigSQL: parser.Normalize(v.OriginNode.Text()),
-		BindSQL:      v.HintedNode.Text(),
+		NormdOrigSQL: parser.Normalize(utilparser.RestoreWithDefaultDB(v.OriginNode, b.ctx.GetSessionVars().CurrentDB)),
+		BindSQL:      utilparser.RestoreWithDefaultDB(v.HintedNode, b.ctx.GetSessionVars().CurrentDB),
```
Comment (eurekaka) [inline planner/core/planbuilder.go:770]: Ditto.

File: planner/core/planbuilder.go (hunk 4 above)
Comment (rebelice) [reply planner/core/planbuilder.go:762]: The reason for doing this check is that in general, the syntax error in hint is just a warning, but in CREATE BINDING, it should be an error.
When I use HintedNode.Restore instead of HintedNode.Text, the syntax error will be a warning and no longer appear in the result of Restore. So it will not trigger subsequent checks.

File: planner/core/preprocess.go (hunk 5 above)
Comment (rebelice) [reply planner/core/preprocess.go:263]: This change is to rewrite SQL with default DB. I did not find a better way to do this.
I think this relaxation of restrictions is acceptable, and it will not have any particular impact in fact. This is the reason why I did this.
Is there anything I haven't considered for this relaxation?

File: bindinfo/bind_test.go [hunk 12]
```diff
@@ -1688,3 +1705,71 @@ func (s *testSuite) TestIssue19836(c *C) {
 	)
 	tk.MustQuery("explain for connection " + strconv.FormatUint(tk.Se.ShowProcess().ID, 10)).Check(explainResult)
 }
+
+func (s *testSuite) TestIssue20417(c *C) {
```
Comment (qw4990) [inline bindinfo/bind_test.go:1709]: Could you please add this case https://github.com/pingcap/tidb/issues/20417#issuecomment-713279869 into this test to make sure the bind can be hit after this PR?

**Review by qw4990 — COMMENTED** [review]
@rebelice PTAL, please address comments and resolve conflicts.

File: types/parser_driver/value_expr.go (hunk 8 above)
Comment (rebelice) [reply types/parser_driver/value_expr.go:104]: This is for the content after the restore to be compatible with the text before this PR, that is, the default charset is not printed.

File: bindinfo/bind_test.go (hunk 12 above)
Comment (rebelice) [reply bindinfo/bind_test.go:1932]: There is already an equivalent test here.

**Comment by rebelice** [comment]
I have addressed all the comments and added compatibility code to make the previous binding take effect. PTAL @qw4990 @eurekaka

File: bindinfo/handle.go [hunk 13]
```diff
@@ -575,6 +578,16 @@ func (c cache) getBindRecord(hash, normdOrigSQL, db string) *BindRecord {
...
+func (c cache) getBindRecord(hash, normdOrigSQL, db string) *BindRecord {
+	bindRecords := c[hash]
+	for _, bindRecord := range bindRecords {
+		if bindRecord.OriginalSQL == normdOrigSQL {
+			return bindRecord
+		}
+	}
+	return nil
+}
+
```
Comment (qw4990) [inline bindinfo/handle.go:590]: Would this logic cause some bad cases?
For example, before updating TiDB, the user has two same bindings in different DBs(DB1 and DB2).
And then the user updates TiDB to this commit and wants to drop the binding in DB1.

File: bindinfo/handle.go [hunk 14]
```diff
@@ -447,7 +447,10 @@ func (h *BindHandle) Size() int {
 }
 
 // GetBindRecord returns the BindRecord of the (normdOrigSQL,db) if BindRecord exist.
-func (h *BindHandle) GetBindRecord(hash, normdOrigSQL, db string) *BindRecord {
+func (h *BindHandle) GetBindRecord(hash, normdOrigSQL, db string, matchDB bool) *BindRecord {
+	if matchDB {
+		return h.bindInfo.Load().(cache).getBindRecordWithDB(hash, normdOrigSQL, db)
+	}
 	return h.bindInfo.Load().(cache).getBindRecord(hash, normdOrigSQL, db)
 }
```
Comment (qw4990) [inline bindinfo/handle.go:455]: How about removing `matchDB` and implementing it as:
``` 
if record := h.bindInfo.Load().(cache).getBindRecordWithDB(hash, normdOrigSQL, db); record != nil { 
    // the old way
    return record
}
return h.bindInfo.Load().(cache).getBindRecord(hash, normdOrigSQL, db) // the new way
```
This implementation makes it more easy-to-use since then callers can avoid trying two ways by hand:
```
var record
if record = h. GetBindRecord(..., true); record != nil {
    ...
} else {
    record = h.GetBindRecord(..., false)
}
```

Comment (rebelice) [reply bindinfo/handle.go:455]: Doing so will cause the old bindings to have a high priority, which is unreasonable. Because the new bindings cannot overwrite the old ones, this will make the user’s modification of bindings ineffective

Comment (rebelice) [reply bindinfo/handle.go:455]: Oh, I got it wrong, I understand what you mean now.

File: planner/optimize.go [hunk 15]
```diff
@@ -342,9 +374,21 @@ func getBindRecord(ctx sessionctx.Context, stmt ast.StmtNode) (*bindinfo.BindRec
...
+	}
+	// Here is the compatibility code.
+	// There may be some bindings that did not contain the DB name in the original SQL, so we need to use the previous matching method.
 	if bindRecord == nil {
-		bindRecord = globalHandle.GetBindRecord(hash, normalizedSQL, "")
+		stmtNode, normalizedSQL, hash = extractSelectAndNormalizeDigest(stmt, ctx.GetSessionVars().CurrentDB, false)
+		if stmtNode == nil {
+			return nil, ""
+		}
+		bindRecord = globalHandle.GetBindRecord(hash, normalizedSQL, ctx.GetSessionVars().CurrentDB, true)
```
Comment (qw4990) [inline planner/optimize.go:388]: Should we get records from `sessionHandle` first?

File: planner/optimize.go [hunk 16]
```diff
@@ -273,13 +274,26 @@ func optimize(ctx context.Context, sctx sessionctx.Context, node ast.Node, is in
 	return finalPlan, names, cost, err
 }
 
-func extractSelectAndNormalizeDigest(stmtNode ast.StmtNode) (ast.StmtNode, string, string) {
+func extractSelectAndNormalizeDigest(stmtNode ast.StmtNode, defaultDB string, restore bool) (ast.StmtNode, string, string) {
```
Comment (qw4990) [inline planner/optimize.go:277]: How about changing its arguments to `(stmtNode ast.StmtNode, specifiedDB string)` and using `specifiledDB` only when it is not empty?

**Comment by qw4990** [comment]
PTAL @eurekaka

File: bindinfo/handle.go [hunk 17]
```diff
@@ -448,6 +448,9 @@ func (h *BindHandle) Size() int {
 
 // GetBindRecord returns the BindRecord of the (normdOrigSQL,db) if BindRecord exist.
 func (h *BindHandle) GetBindRecord(hash, normdOrigSQL, db string) *BindRecord {
+	if record := h.bindInfo.Load().(cache).getBindRecordWithDB(hash, normdOrigSQL, db); record != nil {
```
Comment (eurekaka) [inline bindinfo/handle.go:451]: Why not combine it with `getBindRecord`?

File: bindinfo/handle.go [hunk 18]
```diff
@@ -699,6 +712,7 @@ func GenerateBindSQL(ctx context.Context, stmtNode ast.StmtNode, planHint string
 	hint.BindHint(stmtNode, &hint.HintsSet{})
 	var sb strings.Builder
 	restoreCtx := format.NewRestoreCtx(format.DefaultRestoreFlags, &sb)
+	restoreCtx.DefaultDB = defaultDB
```
Comment (eurekaka) [inline bindinfo/handle.go:715]: Would this `DefaultDB` be used? Looks like the flag is not set?

File: planner/optimize.go [hunk 19]
```diff
@@ -342,9 +371,18 @@ func getBindRecord(ctx sessionctx.Context, stmt ast.StmtNode) (*bindinfo.BindRec
 	if globalHandle == nil {
 		return nil, ""
 	}
-	bindRecord = globalHandle.GetBindRecord(hash, normalizedSQL, ctx.GetSessionVars().CurrentDB)
+	bindRecord = globalHandle.GetBindRecord(hash, normalizedSQL, "")
```
Comment (eurekaka) [inline planner/optimize.go:374]: Why we are using `""` instead of `CurrentDB` here?

File: planner/optimize.go [hunk 20]
```diff
@@ -342,9 +371,18 @@ func getBindRecord(ctx sessionctx.Context, stmt ast.StmtNode) (*bindinfo.BindRec
...
 	if bindRecord == nil {
-		bindRecord = globalHandle.GetBindRecord(hash, normalizedSQL, "")
+		stmtNode, normalizedSQL, hash = extractSelectAndNormalizeDigest(stmt, "")
+		if stmtNode == nil {
+			return nil, ""
+		}
+		bindRecord = globalHandle.GetBindRecord(hash, normalizedSQL, ctx.GetSessionVars().CurrentDB)
+		if bindRecord == nil {
+			bindRecord = globalHandle.GetBindRecord(hash, normalizedSQL, "")
+		}
```
Comment (eurekaka) [inline planner/optimize.go:385]: I believe this approach is not the most effective one for compatibility. i.e, using this method, it is common that user queries would fall into this branch, for each query, we would call one more `Restore` compared with previous implementation, this would impose performance penalty for each query. There may be other alternatives, such as during `Update()` of the bindings, we do `Restore()` once for each binding, or we rewrite the original_sql for all existing bindings in the bootstrap function.

**Review by eurekaka — COMMENTED** [review]
Would it possible to have duplicate bindings whose `original_sql` is like

```
select * from t;
select * from test . t;
```

File: planner/optimize.go (hunk 19 above)
Comment (rebelice) [reply planner/optimize.go:374]: We use `Restore` instead of `Text`, which means that the `DB` information is in SQL, so we don't need to match the `DB`.

File: planner/optimize.go (hunk 20 above)
Comment (rebelice) [reply planner/optimize.go:385]: In fact, even after we restore the old bindings, compared to the previous implementation, we still have to restore one more time, that is, we need to restore the input SQL.

File: bindinfo/handle.go (hunk 18 above)
Comment (rebelice) [reply bindinfo/handle.go:715]: The `DefaultDB` is used in the parser.

File: bindinfo/handle.go (hunk 17 above)
Comment (rebelice) [reply bindinfo/handle.go]: Done.

**Comment by rebelice** [comment]
> Would it possible to have duplicate bindings whose `original_sql` is like
> 
> ```
> select * from t;
> select * from test . t;
> ```

Yes, for this case, we will use the new one `select * from test . t`. I just added this part of the test.

**Comment by rebelice** [comment]
The current method of achieving compatibility is not good enough, I will use restore all existing bindings in `upgrade` to replace the current method.

**Comment by rebelice** [comment]
PTAL @qw4990 @eurekaka

File: session/bootstrap.go [hunk 21]
```diff
@@ -1288,6 +1296,90 @@ func upgradeToVer59(s Session, ver int64) {
...
+
+		_, err = s.ExecuteInternal(context.Background(), "COMMIT")
+		if err != nil {
+			return
+		}
+	}()
+	_, err = s.ExecuteInternal(context.Background(), h.LockBindInfoSQL())
+	if err != nil {
+		return
+	}
```
Comment (qw4990) [inline session/bootstrap.go:1324]: We can use `mustExecute` here.

File: session/bootstrap.go [hunk 22]
```diff
@@ -1288,6 +1296,90 @@ func upgradeToVer59(s Session, ver int64) {
...
+	var recordSets []sqlexec.RecordSet
+	recordSets, err = s.ExecuteInternal(context.Background(), "SELECT original_sql, bind_sql, default_db, charset, collation from mysql.bind_info where source != 'builtin'")
+
+	if len(recordSets) > 0 {
+		defer terror.Call(recordSets[0].Close)
+	}
+	if err != nil {
```
Comment (qw4990) [inline session/bootstrap.go:1331]: We should check the error first here.

File: session/bootstrap.go [hunk 23]
```diff
@@ -1288,6 +1296,90 @@ func upgradeToVer59(s Session, ver int64) {
...
+		bindWithDB := utilparser.RestoreWithDefaultDB(bindStmt, db)
+		_, err = s.ExecuteInternal(context.Background(), fmt.Sprintf(`UPDATE mysql.bind_info SET original_sql=%s, bind_sql=%s, default_db='', update_time=%s where original_sql=%s`,
+			expression.Quote(originWithDB),
+			expression.Quote(bindWithDB),
+			expression.Quote(now),
+			expression.Quote(original)))
+		if err != nil {
+			debug.PrintStack()
+			logutil.BgLogger().Fatal("updateBindInfo error", zap.Error(err))
+		}
```
Comment (qw4990) [inline session/bootstrap.go:1379]: We can use `mustExecute` here.

File: planner/core/planbuilder.go [hunk 24]
```diff
@@ -751,23 +751,52 @@ func (b *PlanBuilder) buildSet(ctx context.Context, v *ast.SetStmt) (Plan, error
...
+	}
+	hintsStr, err := hintsSet.Restore()
+	if err != nil {
+		return err
+	}
+	// For `create global binding for select * from t using select * from t`, we allow it though hintsStr is empty.
+	// For `create global binding for select * from t using select /*+ non_exist_hint() */ * from t`,
+	// the hint is totally invalid, we escalate warning to error.
+	if hintsStr == "" && len(warns) > 0 {
+		return warns[0]
```
Comment (qw4990) [inline planner/core/planbuilder.go:779]: Is there any test that can cover this case?

Comment (rebelice) [reply planner/core/planbuilder.go:779]: https://github.com/pingcap/tidb/blob/master/bindinfo/bind_test.go#L1550

**Review by qw4990 — COMMENTED** [review]
LGTM

File: session/bootstrap.go [hunk 25]
```diff
@@ -1288,6 +1296,76 @@ func upgradeToVer59(s Session, ver int64) {
...
+
+	defer func() {
+		if err != nil {
+			mustExecute(s, "ROLLBACK")
+			return
+		}
+
+		mustExecute(s, "COMMIT")
+	}()
+	mustExecute(s, h.LockBindInfoSQL())
```
Comment (eurekaka) [inline session/bootstrap.go:1315]: We don't need this locking in bootstrap, and `lockBindInfoSQL` does not need to be exported then?

File: session/bootstrap.go [hunk 26]
```diff
@@ -1288,6 +1296,76 @@ func upgradeToVer59(s Session, ver int64) {
...
+func updateBindInfo(s Session, iter *chunk.Iterator4Chunk, p *parser.Parser, now string) {
+	for row := iter.Begin(); row != iter.End(); row = iter.Next() {
+		original := row.GetString(0)
+		bind := row.GetString(1)
+		db := row.GetString(2)
+		charset := row.GetString(3)
+		collation := row.GetString(4)
+		originStmt, err := p.ParseOneStmt(original, charset, collation)
+		if err != nil {
+			debug.PrintStack()
```
Comment (eurekaka) [inline session/bootstrap.go:1351]: Unnecessary changes?

File: session/bootstrap.go [hunk 27]
```diff
@@ -1288,6 +1296,76 @@ func upgradeToVer59(s Session, ver int64) {
...
+			logutil.BgLogger().Fatal("updateBindInfo error", zap.Error(err))
+		}
+		originWithDB := parser.Normalize(utilparser.RestoreWithDefaultDB(originStmt, db))
+		bindWithDB := utilparser.RestoreWithDefaultDB(bindStmt, db)
+		mustExecute(s, fmt.Sprintf(`UPDATE mysql.bind_info SET original_sql=%s, bind_sql=%s, default_db='', update_time=%s where original_sql=%s`,
+			expression.Quote(originWithDB),
+			expression.Quote(bindWithDB),
+			expression.Quote(now),
+			expression.Quote(original)))
+	}
```
Comment (eurekaka) [inline session/bootstrap.go:1366]: Shall we drop the `db` column of this table as well?

File: session/bootstrap.go [hunk 28]
```diff
@@ -1288,6 +1296,76 @@ func upgradeToVer59(s Session, ver int64) {
...
+		charset := row.GetString(3)
+		collation := row.GetString(4)
+		originStmt, err := p.ParseOneStmt(original, charset, collation)
+		if err != nil {
+			debug.PrintStack()
+			logutil.BgLogger().Fatal("updateBindInfo error", zap.Error(err))
+		}
+		bindStmt, err := p.ParseOneStmt(bind, charset, collation)
+		if err != nil {
+			debug.PrintStack()
```
Comment (eurekaka) [inline session/bootstrap.go:1356]: Ditto

File: session/bootstrap.go (hunk 25 above)
Comment (rebelice) [reply session/bootstrap.go:1315]: Will multiple TiDB instances upgrade at the same time have concurrency issues?

File: session/bootstrap.go (hunk 27 above)
Comment (rebelice) [reply session/bootstrap.go:1366]: Yes, when using the `create global binding` statement to create a binding, because `db` is added to `origin sql`, the column of `default_db` is empty. The deletion of the column `default_db` is consistent with the above behavior.

File: session/bootstrap.go (hunk 28 above)
Comment (rebelice) [reply session/bootstrap.go]: updated.

File: session/bootstrap.go (hunk 26 above)
Comment (rebelice) [reply session/bootstrap.go]: updated

File: session/bootstrap.go [hunk 29]
```diff
@@ -1296,6 +1305,74 @@ func upgradeToVer60(s Session, ver int64) {
...
+			return
+		}
+
+		mustExecute(s, "COMMIT")
+	}()
+	mustExecute(s, h.LockBindInfoSQL())
+	var recordSets []sqlexec.RecordSet
+	recordSets, err = s.ExecuteInternal(context.Background(), "SELECT original_sql, bind_sql, default_db, charset, collation from mysql.bind_info where source != 'builtin'")
+	if err != nil {
+		debug.PrintStack()
```
Comment (eurekaka) [inline session/bootstrap.go:1328]:
```suggestion
```

File: session/bootstrap.go [hunk 30]
```diff
@@ -1296,6 +1305,74 @@ func upgradeToVer60(s Session, ver int64) {
...
+		logutil.BgLogger().Fatal("upgradeToVer60 error", zap.Error(err))
```
Comment (eurekaka) [inline session/bootstrap.go:1329]:
```suggestion
		logutil.BgLogger().Fatal("upgradeToVer61 error", zap.Error(err))
```

File: session/bootstrap.go [hunk 31]
```diff
@@ -1296,6 +1305,74 @@ func upgradeToVer60(s Session, ver int64) {
...
+	}
+	req := recordSets[0].NewChunk()
+	iter := chunk.NewIterator4Chunk(req)
+	p := parser.New()
+	now := types.NewTime(types.FromGoTime(time.Now()), mysql.TypeTimestamp, 3)
+	for {
+		err = recordSets[0].Next(context.TODO(), req)
+		if err != nil {
+			debug.PrintStack()
+			logutil.BgLogger().Fatal("upgradeToVer60 error", zap.Error(err))
```
Comment (eurekaka) [inline session/bootstrap.go:1342]:
```suggestion
			logutil.BgLogger().Fatal("upgradeToVer61 error", zap.Error(err))
```

File: session/bootstrap.go [hunk 32]
```diff
@@ -1296,6 +1305,74 @@ func upgradeToVer60(s Session, ver int64) {
...
+		defer terror.Call(recordSets[0].Close)
+	}
+	req := recordSets[0].NewChunk()
+	iter := chunk.NewIterator4Chunk(req)
+	p := parser.New()
+	now := types.NewTime(types.FromGoTime(time.Now()), mysql.TypeTimestamp, 3)
+	for {
+		err = recordSets[0].Next(context.TODO(), req)
+		if err != nil {
+			debug.PrintStack()
```
Comment (eurekaka) [inline session/bootstrap.go:1341]:
```suggestion
```

**Review by eurekaka — COMMENTED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Review by eurekaka — APPROVED** [review]
