### PR TITLE
planner: report error when ORDER BY conflicts with DISTINCT

### LINKED ISSUE #12442: When ORDER BY clause has conflict with DISTINCT, incompatible with mysql
## Bug Report

When `ORDER BY` has conflict with `DISTINCT`, mysql will report error, but TiDB will just ignore `ORDER BY`

1. What did you do?

```sql
create table ttest (v1 int, v2 int);
insert into ttest values(1, 2), (4,6), (1, 7);
select distinct v1 from ttest order by v2;
```

2. What did you expect to see?

In Mysql 8.0.16

```sql
mysql> create table ttest (v1 int, v2 int);
Query OK, 0 rows affected (0.06 sec)

mysql> insert into ttest values(1, 2), (4,6), (1, 7);
Query OK, 3 rows affected (0.02 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select distinct v1 from ttest order by v2;
ERROR 3065 (HY000): Expression #1 of ORDER BY clause is not in SELECT list, references column 'randgen.ttest.v2' which is not in SELECT list; this is incompatible with DISTINCT
```

3. What did you see instead?

In TiDB:

```sql
mysql> create table ttest (v1 int, v2 int);
Query OK, 0 rows affected (0.23 sec)

mysql> insert into ttest values(1, 2), (4,6), (1, 7);
Query OK, 3 rows affected (0.06 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select distinct v1 from ttest order by v2;
+------+
| v1   |
+------+
|    1 |
|    4 |
+------+
2 rows in set (0.01 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```sql
mysql> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                       |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.3
Git Commit Hash: 836982c617fbaa42d74616eb9ba9ed4cae46c46b
Git Branch: HEAD
UTC Build Time: 2019-08-30 02:42:42
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #12442  

Problem Summary: TiDB doesn't report error when `ORDER BY` conflicts with `DISTINCT`
(`ORDER BY` items must show up in `SELECT DISTINCT` fields).

``` mysql
create table t (a int, b int);

# These should be rejected
select distinct a from t order by b;
select distinct count(a) from t group by b order by b;
select distinct b from t group by a, b order by a, b;
select distinct a+1 from t order by a;
select distinct a+1 from t order by a+2;
select distinct a+1 from t order by 1+a;
select distinct sin(a) from t order by sin(a)+1;

# These should be accepted
select distinct a, b from t order by b;
select distinct count(a), b from t group by b order by b;
select distinct a+1 from t order by a+1;
select distinct sin(a) from t order by sin(a);
select distinct a from t order by sin(a);
```

### What is changed and how it works?

- Check for conflicts when `ORDER BY` and `DISTINCT` both show up.
- Check whether every `ORDER BY` item has its reference in `SELECT DISTINCT`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Report error when ORDER BY conflicts with DISTINCT.

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -1584,6 +1598,33 @@ func (b *PlanBuilder) buildSort(ctx context.Context, p LogicalPlan, byItems []*a
...
+			if col.Equal(b.ctx, originalExprs[j]) || col.Equal(b.ctx, p.Schema().Columns[j]) {
+				continue CheckReferenced
+			}
+		}
+
+		if _, ok := byItem.Expr.(*ast.AggregateFuncExpr); ok {
+			return ErrAggregateInOrderNotSelect.GenWithStackByArgs(idx+1, "DISTINCT")
+		}
+		return ErrFieldInOrderNotSelect.GenWithStackByArgs(idx+1, col.OrigName, "DISTINCT")
+	}
```
Comment (XuHuaiyu) [inline planner/core/logical_plan_builder.go:1624]: What's the difference between these two loops?
Any test case can explain it

Comment (dyzsr) [reply planner/core/logical_plan_builder.go]: I added some comments to these loops. PTAL

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
