### PR TITLE
util/ranger: convert range condition like `x >= 2 and x <= 2` to point condition `x = 2`

### LINKED ISSUE #17153: Can't choose better plan when the range condition can convert to point.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
drop table t;
create table t(a int,b int,index(a,b));
insert into t values(1,1);
insert into t values(2,2);
insert into t values(2,2);
insert into t values(2,2);
insert into t values(2,2);
insert into t values(2,2);
insert into t values(3,3);
desc select * from t where a >= 2 and a <= 2 order by b limit 2;
desc select * from t where a = 2 order by b limit 2;
```

### 2. What did you expect to see?
Same plan.
### 3. What did you see instead?
```
tidb> desc select * from t where a >= 2 and a <= 2 order by b limit 2;
+-----------------------------+---------+-----------+------------------------+---------------------------------------------+
| id                          | estRows | task      | access object          | operator info                               |
+-----------------------------+---------+-----------+------------------------+---------------------------------------------+
| TopN_8                      | 2.00    | root      |                        | test.t.b:asc, offset:0, count:2             |
| └─IndexReader_16            | 2.00    | root      |                        | index:TopN_15                               |
|   └─TopN_15                 | 2.00    | cop[tikv] |                        | test.t.b:asc, offset:0, count:2             |
|     └─IndexRangeScan_14     | 10.00   | cop[tikv] | table:t, index:a(a, b) | range:[2,2], keep order:false, stats:pseudo |
+-----------------------------+---------+-----------+------------------------+---------------------------------------------+
4 rows in set (0.00 sec)

tidb> desc select * from t where a = 2 order by b limit 2;
+-----------------------------+---------+-----------+------------------------+--------------------------------------------+
| id                          | estRows | task      | access object          | operator info                              |
+-----------------------------+---------+-----------+------------------------+--------------------------------------------+
| Limit_11                    | 2.00    | root      |                        | offset:0, count:2                          |
| └─IndexReader_21            | 2.00    | root      |                        | index:Limit_20                             |
|   └─Limit_20                | 2.00    | cop[tikv] |                        | offset:0, count:2                          |
|     └─IndexRangeScan_19     | 2.00    | cop[tikv] | table:t, index:a(a, b) | range:[2,2], keep order:true, stats:pseudo |
+-----------------------------+---------+-----------+------------------------+--------------------------------------------+
4 rows in set (0.00 sec)

```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #17153 

Problem Summary:
Range condition like `x >= 2 and x <= 2` cannot be converted to point.

### What is changed and how it works?

What's Changed:
Range condition like `x >= 2 and x <= 2` can be converted to point condition `x = 2`.

For example, create such a table.
```
mysql> create table t(a int, b int, c int, index(a, b, c));
```
Before this PR:
```
mysql> desc select * from t where a >= 2 and a <= 2 and b = 2 and c > 2;
+--------------------------+---------+-----------+---------------------------+---------------------------------------------+
| id                       | estRows | task      | access object             | operator info                               |
+--------------------------+---------+-----------+---------------------------+---------------------------------------------+
| IndexReader_7            | 0.00    | root      |                           | index:Selection_6                           |
| └─Selection_6            | 0.00    | cop[tikv] |                           | eq(test.t.b, 2), gt(test.t.c, 2)            |
|   └─IndexRangeScan_5     | 10.00   | cop[tikv] | table:t, index:a(a, b, c) | range:[2,2], keep order:false, stats:pseudo |
+--------------------------+---------+-----------+---------------------------+---------------------------------------------+
3 rows in set (0.01 sec)
```
After this PR:
```
mysql> desc select * from t where a >= 2 and a <= 2 and b = 2 and c > 2;
+------------------------+---------+-----------+---------------------------+--------------------------------------------------------+
| id                     | estRows | task      | access object             | operator info                                          |
+------------------------+---------+-----------+---------------------------+--------------------------------------------------------+
| IndexReader_6          | 0.33    | root      |                           | index:IndexRangeScan_5                                 |
| └─IndexRangeScan_5     | 0.33    | cop[tikv] | table:t, index:a(a, b, c) | range:(2 2 2,2 2 +inf], keep order:false, stats:pseudo |
+------------------------+---------+-----------+---------------------------+--------------------------------------------------------+
2 rows in set (0.00 sec)
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- convert range condition to point condition if possible

### CODE REVIEW

File: util/ranger/detacher.go [hunk 1]
```diff
@@ -114,7 +116,7 @@ func getEqOrInColOffset(expr expression.Expression, cols []*expression.Column) i
 			offset = curOffset
 		}
 		return offset
-	case ast.EQ, ast.NullEQ:
+	case ast.EQ, ast.NullEQ, ast.LE, ast.GE:
```
Comment (Reminiscent) [inline util/ranger/detacher.go:119]: Can we add `ast.LT` and `ast.GT` here? It seems we can convert `x > 1 and x < 3` to `x = 2`?

**Review by Reminiscent — COMMENTED** [review]
Rest LGTM

File: util/ranger/detacher.go [hunk 2]
```diff
@@ -347,16 +355,53 @@ func (d *rangeDetacher) detachCNFCondAndBuildRangeForIndex(conditions []expressi
...
+				p.excl = false
+			}
+		} else {
+			if val != math.MinInt64 {
+				p.value.SetInt64(val - 1)
+				p.excl = false
+			}
+		}
+	}
+	if p.value.Kind() == types.KindUint64 {
```
Comment (Reminiscent) [inline util/ranger/detacher.go:377]: it's better to change it to `} else if p.value.Kind() == types.KindUint64 {`

File: planner/core/testdata/integration_suite_in.json [hunk 3]
```diff
@@ -226,5 +226,12 @@
       "select approx_percentile(a, 10*10) from t",
       "select approx_percentile(a, 50) from t group by b order by b"
     ]
+  },
+  {
+    "name": "TestConvertRangeToPoint",
+    "cases": [
+      "explain select * from t0 where a > 1 and a < 3 order by b limit 2",
+      "explain select * from t1 where a >= 2 and a <= 2 and b = 2 and c > 2"
```
Comment (Reminiscent) [inline planner/core/testdata/integration_suite_in.json:234]: Can we add more test cases such as `explain select * from t0 where a >= 2.0 and a <= 2.0 order by b limit 2` which `a` is `float` type.

File: util/ranger/detacher.go [hunk 4]
```diff
@@ -345,6 +355,79 @@ func (d *rangeDetacher) detachCNFCondAndBuildRangeForIndex(conditions []expressi
 	return res, nil
 }
 
+// excludeToIncludeForIntPoint converts `(i` to `[i+1` and `i)`
```
Comment (Reminiscent) [inline util/ranger/detacher.go:358]: Can we add some special cases to explain this?

**Comment by morgo** [comment]
This is really cool. Is it possible to extend this to cover other data types? In https://github.com/pingcap/tidb/issues/19941 there is a case where `d` is a date, and should prune to only `p2018`:

```sql
mysql> EXPLAIN SELECT COUNT(*) FROM t1 WHERE d >= '2018-01-01' AND d < '2019-01-01';
+------------------------------------+----------+-----------+---------------------------+--------------------------------------------------------------------------------------+
| id                                 | estRows  | task      | access object             | operator info                                                                        |
+------------------------------------+----------+-----------+---------------------------+--------------------------------------------------------------------------------------+
| HashAgg_15                         | 1.00     | root      |                           | funcs:count(Column#4)->Column#3                                                      |
| └─PartitionUnion_16                | 2.00     | root      |                           |                                                                                      |
|   ├─StreamAgg_31                   | 1.00     | root      |                           | funcs:count(Column#6)->Column#4                                                      |
|   │ └─TableReader_32               | 1.00     | root      |                           | data:StreamAgg_20                                                                    |
|   │   └─StreamAgg_20               | 1.00     | cop[tikv] |                           | funcs:count(1)->Column#6                                                             |
|   │     └─Selection_30             | 250.00   | cop[tikv] |                           | ge(test.t1.d, 2018-01-01 00:00:00.000000), lt(test.t1.d, 2019-01-01 00:00:00.000000) |
|   │       └─TableFullScan_29       | 10000.00 | cop[tikv] | table:t1, partition:p2018 | keep order:false, stats:pseudo                                                       |
|   └─StreamAgg_50                   | 1.00     | root      |                           | funcs:count(Column#8)->Column#4                                                      |
|     └─TableReader_51               | 1.00     | root      |                           | data:StreamAgg_39                                                                    |
|       └─StreamAgg_39               | 1.00     | cop[tikv] |                           | funcs:count(1)->Column#8                                                             |
|         └─Selection_49             | 250.00   | cop[tikv] |                           | ge(test.t1.d, 2018-01-01 00:00:00.000000), lt(test.t1.d, 2019-01-01 00:00:00.000000) |
|           └─TableFullScan_48       | 10000.00 | cop[tikv] | table:t1, partition:p2019 | keep order:false, stats:pseudo                                                       |
+------------------------------------+----------+-----------+---------------------------+--------------------------------------------------------------------------------------+
12 rows in set (0.00 sec)
```

**Comment by xuyifangreeneyes** [comment]
> This is really cool. Is it possible to extend this to cover other data types? In #19941 there is a case where `d` is a date, and should prune to only `p2018`:
> 
> ```sql
> mysql> EXPLAIN SELECT COUNT(*) FROM t1 WHERE d >= '2018-01-01' AND d < '2019-01-01';
> +------------------------------------+----------+-----------+---------------------------+--------------------------------------------------------------------------------------+
> | id                                 | estRows  | task      | access object             | operator info                                                                        |
> +------------------------------------+----------+-----------+---------------------------+--------------------------------------------------------------------------------------+
> | HashAgg_15                         | 1.00     | root      |                           | funcs:count(Column#4)->Column#3                                                      |
> | └─PartitionUnion_16                | 2.00     | root      |                           |                                                                                      |
> |   ├─StreamAgg_31                   | 1.00     | root      |                           | funcs:count(Column#6)->Column#4                                                      |
> |   │ └─TableReader_32               | 1.00     | root      |                           | data:StreamAgg_20                                                                    |
> |   │   └─StreamAgg_20               | 1.00     | cop[tikv] |                           | funcs:count(1)->Column#6                                                             |
> |   │     └─Selection_30             | 250.00   | cop[tikv] |                           | ge(test.t1.d, 2018-01-01 00:00:00.000000), lt(test.t1.d, 2019-01-01 00:00:00.000000) |
> |   │       └─TableFullScan_29       | 10000.00 | cop[tikv] | table:t1, partition:p2018 | keep order:false, stats:pseudo                                                       |
> |   └─StreamAgg_50                   | 1.00     | root      |                           | funcs:count(Column#8)->Column#4                                                      |
> |     └─TableReader_51               | 1.00     | root      |                           | data:StreamAgg_39                                                                    |
> |       └─StreamAgg_39               | 1.00     | cop[tikv] |                           | funcs:count(1)->Column#8                                                             |
> |         └─Selection_49             | 250.00   | cop[tikv] |                           | ge(test.t1.d, 2018-01-01 00:00:00.000000), lt(test.t1.d, 2019-01-01 00:00:00.000000) |
> |           └─TableFullScan_48       | 10000.00 | cop[tikv] | table:t1, partition:p2019 | keep order:false, stats:pseudo                                                       |
> +------------------------------------+----------+-----------+---------------------------+--------------------------------------------------------------------------------------+
> 12 rows in set (0.00 sec)
> ```
Yes, we can extend this to any data type with discrete values.  `d < '2019-01-01'` can be converted to `d <= '2018-12-31'`. Can we open another PR to implement the feature and keep this PR on #17153?

**Comment by morgo** [comment]
> Yes, we can extend this to any data type with discrete values. `d < '2019-01-01'` can be converted to `d <= '2018-12-31'`. Can we open another PR to implement the feature and keep this PR on #17153?

Sounds good to me.

**Comment by morgo** [comment]
LGTM

**Review by time-and-fate — COMMENTED** [review]
LGTM

**Comment by xuyifangreeneyes** [comment]
@eurekaka PTAL

File: util/ranger/detacher.go [hunk 5]
```diff
@@ -345,6 +355,80 @@ func (d *rangeDetacher) detachCNFCondAndBuildRangeForIndex(conditions []expressi
...
+// For example, if p is `(3`, i.e., point { value: int(3), excl: true, start: true }, it is equal to `[4`, i.e., point { value: int(4), excl: false, start: true }.
+// Similarly, if p is `8)`, i.e., point { value: int(8), excl: true, start: false}, it is equal to `7]`, i.e., point { value: int(7), excl: false, start: false }.
+func excludeToIncludeForIntPoint(p point) point {
+	if !p.excl {
+		return p
+	}
+	if p.value.Kind() == types.KindInt64 {
+		val := p.value.GetInt64()
+		if p.start {
+			if val != math.MaxInt64 {
```
Comment (eurekaka) [inline util/ranger/detacher.go:368]: If `val == math.MaxInt64`, we can return an information to the caller that this filer is constant false? Then we can handle this information in `ExtractEqAndInCondition` to return `true` in the last return value.

File: util/ranger/detacher.go [hunk 6]
```diff
@@ -345,6 +355,80 @@ func (d *rangeDetacher) detachCNFCondAndBuildRangeForIndex(conditions []expressi
...
+				p.value.SetUint64(val - 1)
+				p.excl = false
+			}
+		}
+	}
+	return p
+}
+
+func allSinglePoints(sc *stmtctx.StatementContext, points []point) bool {
+	if len(points)%2 == 1 {
```
Comment (eurekaka) [inline util/ranger/detacher.go:396]: This would never happen?

**Comment by xuyifangreeneyes** [comment]
@eurekaka PTAL, thanks.

File: util/ranger/detacher.go [hunk 7]
```diff
@@ -384,12 +486,31 @@ func ExtractEqAndInCondition(sctx sessionctx.Context, conditions []expression.Ex
...
+					accesses[i] = nil
+				}
 			}
 			continue
 		}
-		accesses[i] = points2EqOrInCond(sctx, points[i], cols[i])
-		newConditions = append(newConditions, accesses[i])
+		points[i] = allSinglePoints(sctx.GetSessionVars().StmtCtx, points[i])
+		if points[i] == nil {
+			// There exists an interval whose length is larger than
```
Comment (eurekaka) [inline util/ranger/detacher.go:499]: larger than what?

**Review by eurekaka — DISMISSED** [review]
LGTM

File: util/ranger/detacher.go (hunk 7 above)
Comment (xuyifangreeneyes) [reply util/ranger/detacher.go]: Larger than 0. Sorry that I forgot to complete the comment.

**Comment by qw4990** [comment]
PTAL @time-and-fate

**Review by Reminiscent — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
