### PR TITLE
ddl: handle PD error from getting timestamp

### LINKED ISSUE #58871: PD error is not checked in `waitVersionSyncedWithoutMDL`
## Bug Report

here error is not checked https://github.com/pingcap/tidb/blob/b74eb0f906a73215548c1cf2352c41a802ea37f9/pkg/ddl/schema_version.go#L408

If PD goes wrong here, the error is ignored and continue with `ver=0`. Then It uses `0` to create a snapshot and `latestSchemaVersion` will be `0` too and `updateGlobalVersionAndWaitSynced` will not work.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #58871

Problem Summary:

When we failed to get timestamp from PD, the returned ver is set to zero. This makes `WaitVersionSynced` pass unexpectedly.

https://github.com/tikv/client-go/blob/557a4986e4c43f7809e0305dde9b30d5e433055a/tikv/kv.go#L527-L530

### What changed and how does it work?

We should check the error returned from client to make caller retry syncing version.

I have checked the repo, and now all places that call this function check the error.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/db_test.go [hunk 1]
```diff
@@ -1352,3 +1353,28 @@ func TestGetAllTableInfos(t *testing.T) {
...
+	eg.Go(func() error {
+		tk.MustExec("alter table t add column b int")
+		return nil
+	})
+
+	eg.Go(func() error {
+		time.Sleep(2 * time.Second)
+		testfailpoint.Disable(t, "github.com/pingcap/tidb/pkg/ddl/mockGetCurrentVersionFailed")
+		return nil
+	})
```
Comment (tangenta) [inline pkg/ddl/db_test.go]: It is better not to use sleep in UT, maybe change the failpoint term from `return(true)` to `2*return(true)`
