### PR TITLE
importinto: fix import compressed server file

### LINKED ISSUE #48049: import into from server disk, cannot import compressed file
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
the suffix check not include compressed file

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #48049

Problem Summary:

### What is changed and how it works?

add suffix for compressed files, move some integration test into ut.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/realtikvtest/importintotest/from_server_test.go [hunk 1]
```diff
@@ -1,90 +0,0 @@
...
-		var content []byte
-		rowCnt := 2
-		for j := 0; j < rowCnt; j++ {
-			content = append(content, []byte(fmt.Sprintf("%d,test-%d\n", i*rowCnt+j, i*rowCnt+j))...)
-			allData = append(allData, fmt.Sprintf("%d test-%d", i*rowCnt+j, i*rowCnt+j))
-		}
-		s.NoError(os.WriteFile(path.Join(tempDir, fileName), content, 0o644))
-	}
-	// directory without permission
-	s.NoError(os.MkdirAll(path.Join(tempDir, "no-perm"), 0o700))
```
Comment (D3Hunter) [inline tests/realtikvtest/importintotest/from_server_test.go:40]: all those parts are moved into ut

**Review by lance6716 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
