### PR TITLE
planner: fix the issue that the group by check not allow `cast` expr in both projection and group by | tidb-test=pr/2555

### LINKED ISSUE #62350: Unexpected `SELECT list is not in GROUP BY clause and contains nonaggregated column` error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tiflash CI fails after https://github.com/pingcap/tidb/pull/61476 merged (the PR plan to fix issue https://github.com/pingcap/tidb/issues/61350). Note this issue is not related to tiflash

```
TiDB root@10.2.12.81:test> create table test.t(a datetime, b date, c timestamp(3))
TiDB root@10.2.12.81:test> alter table test.t set tiflash replica 1
TiDB root@10.2.12.81:test> insert into test.t values('2021/04/13 00:34:00.123456', '2021/04/13', '2021/04/13 00:34:00.123456')

-- tidb-server is ok, fe8d82fedd8f9a638d1e0d88472a320dd4f2b392 is OK
TiDB root@10.2.12.81:test> select count(*), cast(a as char), cast(b as char), cast(c as char) from test.t group by cast(a as char), cast(b as char), cast(c as char);
+----------+---------------------+-----------------+-------------------------+
| count(*) | cast(a as char)     | cast(b as char) | cast(c as char)         |
+----------+---------------------+-----------------+-------------------------+
| 1        | 2021-04-13 00:34:00 | 2021-04-13      | 2021-04-13 00:34:00.123 |
+----------+---------------------+-----------------+-------------------------+
TiDB root@10.2.12.81:test> select tidb_version() \G;
***************************[ 1. row ]***************************
tidb_version() | Release Version: v9.0.0-beta.2.pre-83-gfe8d82fedd
Edition: Community
Git Commit Hash: fe8d82fedd8f9a638d1e0d88472a320dd4f2b392
Git Branch: master
UTC Build Time: 2025-07-10 07:16:14
GoVersion: go1.23.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Kernel Type: Classic
1 row in set
Time: 0.001s
```

### 2. What did you expect to see? (Required)

described as above

### 3. What did you see instead (Required)

```
-- tidb-server throw error, 3c2dc46853f5a2edb89da78c1a678da9725ed7b8
TiDB root@10.2.12.81:test> select count(*), cast(a as char), cast(b as char), cast(c as char) from test.t group by cast(a as char), cast(b as char), cast(c as char);
(1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test.t.a' which is not functionally dependent on columns in GROUP BY clause; this
is incompatible with sql_mode=only_full_group_by")
TiDB root@10.2.12.81:test> select tidb_version() \G;
***************************[ 1. row ]***************************
tidb_version() | Release Version: v9.0.0-beta.2.pre-84-g3c2dc46853
Edition: Community
Git Commit Hash: 3c2dc46853f5a2edb89da78c1a678da9725ed7b8
Git Branch: master
UTC Build Time: 2025-07-10 07:12:11
GoVersion: go1.23.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Kernel Type: Classic
```

### 4. What is your TiDB version? (Required)

```
TiDB root@10.2.12.81:test> select tidb_version() \G;
***************************[ 1. row ]***************************
tidb_version() | Release Version: v9.0.0-beta.2.pre-84-g3c2dc46853
Edition: Community
Git Commit Hash: 3c2dc46853f5a2edb89da78c1a678da9725ed7b8
Git Branch: master
UTC Build Time: 2025-07-10 07:12:11
GoVersion: go1.23.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Kernel Type: Classic
```

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #62350

Problem Summary:

The following sql will fail to execute

```
create table t (col timestamp);
select cast(col as char) from t group by cast(col as char);
```

### What changed and how does it work?

1. Split the function `resolveGbyExpr` into two parts, the first one to do the resolve and the second one to rewrite the expression

Previously, the order of check and resolve is like this:

```
                                                                   
 ┌───────────────────────────────────────────────────────────┐     
 │SELECT CAST(col as char) FROM t GROUP BY CAST(col as char);│     
 └──┬────────────────────────────────────────────────────────┘     
    │                                                              
    │RESOLVE                                                       
    │                                                              
    ▼                                                              
 ┌───────────────────────────────────────────────────────────────┐ 
 │SELECT CAST(col as char) FROM t GROUP BY CAST(col as char(19));│ 
 └──┬────────────────────────────────────────────────────────────┘ 
    │                                                              
    │CHECK                                                         
    │                                                              
    ▼                                                              
 ┌───────────┐                                                     
 │FAILED!!!!!│                                                     
 └───────────┘                                                     
```

After this PR:

```
 ┌───────────────────────────────────────────────────────────┐   
 │SELECT CAST(col as char) FROM t GROUP BY CAST(col as char);│   
 └──┬────────────────────────────────────────────────────────┘   
    │                                                            
    │RESOLVE                                                     
    │                                                            
    ▼                                                            
 ┌───────────────────────────────────────────────────────────┐   
 │SELECT CAST(col as char) FROM t GROUP BY CAST(col as char);│   
 └──┬────────────────────────────────────────────────────────┘   
    │                                                            
    │CHECK                                                       
    │                                                            
    ▼                                                            
 ┌───────────┐                                                   
 │SUCCESS!!!!│                                                   
 └──┬────────┘                                                   
    │                                                            
    │REWRITE                                                     
    │                                                            
    ▼                                                            
┌───────────────────────────────────────────────────────────────┐
│SELECT CAST(col as char) FROM t GROUP BY CAST(col as char(19));│
└───────────────────────────────────────────────────────────────┘
```

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/table/tables/tables_test.go [hunk 1]
```diff
@@ -488,7 +488,7 @@ func TestHiddenColumn(t *testing.T) {
 	tk.MustGetErrMsg("select d, b from t;", "[planner:1054]Unknown column 'd' in 'field list'")
 	tk.MustGetErrMsg("select * from t where b > 1;", "[planner:1054]Unknown column 'b' in 'where clause'")
 	tk.MustGetErrMsg("select * from t order by b;", "[planner:1054]Unknown column 'b' in 'order clause'")
-	tk.MustGetErrMsg("select * from t group by b;", "[planner:1054]Unknown column 'b' in 'group statement'")
+	tk.MustGetErrMsg("select sum(a) from t group by b;", "[planner:1054]Unknown column 'b' in 'group statement'")
```
Comment (YangKeao) [inline pkg/table/tables/tables_test.go:491]: It's changed. `select * from t group by b;` will return `Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column`, because we changed the order of checking `ONLY_FULL_GROUP_BY` and `rewrite`.

Comment (AilinKid) [reply pkg/table/tables/tables_test.go:491]: can we check a little bit of what the error will be in mysql

**Review by AilinKid — COMMENTED** [review]
rest LGTM

File: pkg/table/tables/tables_test.go (hunk 1 above)
Comment (YangKeao) [reply pkg/table/tables/tables_test.go:491]: MySQL always return `Unknown column 'b' in 'group statement'`, but I think it's acceptable as this statement actually has two errors :thinking: .

If we want to return `Unknown column 'b' in 'group statement'`, we'll need to bring more changes (e.g. also validate the column in `gbyResolver`), which I think is not necessary.

I think the hidden column is found and returns error in `(*expressionRewriter).toColumn`

**Review by xhebox — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
@AilinKid PTAL again. This has been blocked TiFlash merging PRs to the master branch for a few days. We hope this PR merged and fix the CI failure on TiFlash

File: pkg/table/tables/tables_test.go (hunk 1 above)
Comment (AilinKid) [reply pkg/table/tables/tables_test.go:491]: okk
