### PR TITLE
planner: `DELETE` cannot delete data in some cases when the database name is capitalized (#21202)

### LINKED ISSUE #21200: `DELETE` doesn't delete data in some cases when the database name is capitalized
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop database if exists test1;
create database TEST1;
use TEST1;
create table t(a int);
create table t1(a int);
insert into t values(1);
insert into t1 values(1);

delete a from t a where exists (select 1 from t1 where a.a = t1.a);
```

### 2. What did you expect to see? (Required)

The row in `t` is deleted successfully.

### 3. What did you see instead (Required)

No row is deleted.

### 4. What is your TiDB version? (Required)

Latest master and 4.0.8.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #21202 to release-3.0

---

### What problem does this PR solve?

Issue Number: close #21200  

Problem Summary:

The `CurrentDB` in session vars is stored the original string representation. (i.e. if we create the database name as `tEsT1`, the `CurrentDB` would be `tEsT1`.

However, in the codes that we changed in the pr, we treat the `CurrentDB` as its lower representation. This leads to wrong string comparison result. So `DELETE` might not delete the data correctly.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Wrap `CIStr` upon the `CurrentDB`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note

- `DELETE` may not delete data correctly when the database name is not in pure lower representation.

### CODE REVIEW

File: executor/delete_test.go [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+
+import (
+	"sync"
+	"time"
+
+	. "github.com/pingcap/check"
+	"github.com/pingcap/tidb/util/testkit"
+)
+
+func (s *testSuite8) TestDeleteLockKey(c *C) {
```
Comment (winoros) [inline executor/delete_test.go:24]: I think it's ok to add this test into 3.0?

Comment (lzmhhh123) [inline executor/delete_test.go:24]: Unexpected changes.

Comment (eurekaka) [inline executor/delete_test.go:24]: @winoros this test is unexpected?

Comment (winoros) [reply executor/delete_test.go]: removed

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by eurekaka — APPROVED** [review]
LGTM
