### PR TITLE
ttl: set a result for timeout scan task during shrinking scan worker

### LINKED ISSUE #57708: TTL scan task will leak when down scaling the scan workers if it failed to cancel the task.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

If the scan worker failed to cancel the task, the `task.result` will always be `nil`, and it'll never be regarded as finished. See the following function:

```go
func (m *taskManager) resizeScanWorkers(count int) error {
	var err error
	var canceledWorkers []worker
	m.scanWorkers, canceledWorkers, err = m.resizeWorkers(m.scanWorkers, count, func() worker {
		return newScanWorker(m.delCh, m.notifyStateCh, m.sessPool)
	})
	for _, w := range canceledWorkers {
		...

		result := s.PollTaskResult()
		if result != nil {
			jobID = result.task.JobID
			scanID = result.task.ScanID

			scanErr = result.err
		} else {
			// if the scan worker failed to poll the task, it's possible that the `WaitStopped` has timeout
			// we still consider the scan task as finished
			curTask := s.CurrentTask()
			if curTask == nil {
				continue
			}
			jobID = curTask.JobID
			scanID = curTask.ScanID
			scanErr = errors.New("timeout to cancel scan task")
		}

...

		task.result = result
	}
	return err
}
```

It's easy to fix. We need to assign a result to the scan task.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #57708 

Problem Summary:

The result is not set for the scan task when TiDB is shrinking the scan worker and timeout.

### What changed and how does it work?

Set a result for the scan task.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lcwangchao — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

File: pkg/ttl/ttlworker/scan.go [hunk 1]
```diff
@@ -380,6 +384,10 @@ func (w *ttlScanWorker) handleScanTask(tracer *metrics.PhaseTracer, task *ttlSca
 		result = task.result(nil)
 	}
 
+	if intest.InTest && ctx.Value(TTLScanPostScanHookForTest{}) != nil {
+		ctx.Value(TTLScanPostScanHookForTest{}).(func())()
```
Comment (zimulala) [inline pkg/ttl/ttlworker/scan.go:388]: Could we call the function like `failpoint.InjectCall`? Then we needn't add a new struct.

Comment (YangKeao) [reply pkg/ttl/ttlworker/scan.go:388]: It's more suggested to use context to inject error when it's possible, right? :thinking:, so that we'll not need to `make failpoint-enable` to run this test.

File: pkg/ttl/ttlworker/task_manager_integration_test.go [hunk 2]
```diff
@@ -356,3 +356,64 @@ func TestMeetTTLRunningTasks(t *testing.T) {
...
+	// shrink scan workers, one of them will timeout
+	require.Error(t, m.ResizeScanWorkers(0))
+	require.Len(t, m.GetScanWorkers(), 0)
+
+	// the canceled 3 tasks are still running, but they have results, so after `CheckFinishedTask`, it should be finished
+	tk.MustQuery("SELECT count(1) from mysql.tidb_ttl_task where status = 'running'").Check(testkit.Rows("4"))
+	m.CheckFinishedTask(se, now)
+	require.Len(t, m.GetRunningTasks(), 0)
+	// now, the task should be finished
+	tk.MustQuery("SELECT count(1) from mysql.tidb_ttl_task where status = 'running'").Check(testkit.Rows("0"))
```
Comment (zimulala) [inline pkg/ttl/ttlworker/task_manager_integration_test.go:415]: Do we need to add a check to see if this finished task is failed or successful?

**Review by zimulala — APPROVED** [review]
LGTM
