### PR TITLE
*: refine mysql.tidb_mdl_view

### LINKED ISSUE #46933: explain tidb_mdl_view contains CARTESIAN
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tiup playground v6.5.4 
mysql --comments --host 127.0.0.1 --port 4000 -u root

```
	CreateMDLView = `CREATE OR REPLACE VIEW mysql.tidb_mdl_view as (
		SELECT job_id,
			db_name,
			table_name,
			query,
			session_id,
			txnstart,
			tidb_decode_sql_digests(all_sql_digests, 4096) AS SQL_DIGESTS
		FROM information_schema.ddl_jobs,
			information_schema.cluster_tidb_trx,
			information_schema.cluster_processlist
		WHERE (ddl_jobs.state != 'synced' and ddl_jobs.state != 'cancelled')
			AND Find_in_set(ddl_jobs.table_id, cluster_tidb_trx.related_table_ids)
			AND cluster_tidb_trx.session_id = cluster_processlist.id
	);`
```
https://github.com/pingcap/tidb/blob/a8bd506507a70da985a1e0af6f7c4e31e7e9da4a/session/bootstrap.go#L460 

```
mysql> explain select * from mysql.tidb_mdl_view;
+-------------------------------------+-------------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                  | estRows     | task      | access object             | operator info                                                                                                                                                                                                                           |
+-------------------------------------+-------------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_14                       | 99900000.00 | root      |                           | Column#1, Column#2, Column#3, Column#13, information_schema.cluster_tidb_trx.session_id, information_schema.cluster_processlist.txnstart, tidb_decode_sql_digests(information_schema.cluster_tidb_trx.all_sql_digests, 4096)->Column#43 |
| └─Projection_15                     | 99900000.00 | root      |                           | Column#1, Column#2, Column#3, Column#13, information_schema.cluster_tidb_trx.session_id, information_schema.cluster_tidb_trx.all_sql_digests, information_schema.cluster_processlist.txnstart                                           |
|   └─HashJoin_17                     | 99900000.00 | root      |                           | CARTESIAN inner join, other cond:find_in_set(cast(Column#7, var_string(20)), information_schema.cluster_tidb_trx.related_table_ids)                                                                                                     |
|     ├─HashJoin_18(Build)            | 12487.50    | root      |                           | inner join, equal:[eq(information_schema.cluster_tidb_trx.session_id, information_schema.cluster_processlist.id)]                                                                                                                       |
|     │ ├─TableReader_24(Build)       | 10000.00    | root      |                           | data:TableFullScan_23                                                                                                                                                                                                                   |
|     │ │ └─TableFullScan_23          | 10000.00    | cop[tidb] | table:CLUSTER_PROCESSLIST | keep order:false, stats:pseudo                                                                                                                                                                                                          |
|     │ └─TableReader_22(Probe)       | 9990.00     | root      |                           | data:Selection_21                                                                                                                                                                                                                       |
|     │   └─Selection_21              | 9990.00     | cop[tidb] |                           | not(isnull(information_schema.cluster_tidb_trx.session_id))                                                                                                                                                                             |
|     │     └─TableFullScan_20        | 10000.00    | cop[tidb] | table:CLUSTER_TIDB_TRX    | keep order:false, stats:pseudo                                                                                                                                                                                                          |
|     └─Selection_25(Probe)           | 8000.00     | root      |                           | eq(Column#12, "running")                                                                                                                                                                                                                |
|       └─MemTableScan_26             | 10000.00    | root      | table:DDL_JOBS            |                                                                                                                                                                                                                                         |
+-------------------------------------+-------------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
11 rows in set (0.01 sec)
```

### 2. What did you expect to see? (Required)

The execution plan contains CARTESIAN, and as the production ddl increases, the view query becomes slower and slower. Optimization is recommended.

### 3. What did you see instead (Required)

```
mysql> explain select * from mysql.tidb_mdl_view;
+-------------------------------------+-------------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                  | estRows     | task      | access object             | operator info                                                                                                                                                                                                                           |
+-------------------------------------+-------------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_14                       | 99900000.00 | root      |                           | Column#1, Column#2, Column#3, Column#13, information_schema.cluster_tidb_trx.session_id, information_schema.cluster_processlist.txnstart, tidb_decode_sql_digests(information_schema.cluster_tidb_trx.all_sql_digests, 4096)->Column#43 |
| └─Projection_15                     | 99900000.00 | root      |                           | Column#1, Column#2, Column#3, Column#13, information_schema.cluster_tidb_trx.session_id, information_schema.cluster_tidb_trx.all_sql_digests, information_schema.cluster_processlist.txnstart                                           |
|   └─HashJoin_17                     | 99900000.00 | root      |                           | CARTESIAN inner join, other cond:find_in_set(cast(Column#7, var_string(20)), information_schema.cluster_tidb_trx.related_table_ids)                                                                                                     |
|     ├─HashJoin_18(Build)            | 12487.50    | root      |                           | inner join, equal:[eq(information_schema.cluster_tidb_trx.session_id, information_schema.cluster_processlist.id)]                                                                                                                       |
|     │ ├─TableReader_24(Build)       | 10000.00    | root      |                           | data:TableFullScan_23                                                                                                                                                                                                                   |
|     │ │ └─TableFullScan_23          | 10000.00    | cop[tidb] | table:CLUSTER_PROCESSLIST | keep order:false, stats:pseudo                                                                                                                                                                                                          |
|     │ └─TableReader_22(Probe)       | 9990.00     | root      |                           | data:Selection_21                                                                                                                                                                                                                       |
|     │   └─Selection_21              | 9990.00     | cop[tidb] |                           | not(isnull(information_schema.cluster_tidb_trx.session_id))                                                                                                                                                                             |
|     │     └─TableFullScan_20        | 10000.00    | cop[tidb] | table:CLUSTER_TIDB_TRX    | keep order:false, stats:pseudo                                                                                                                                                                                                          |
|     └─Selection_25(Probe)           | 8000.00     | root      |                           | eq(Column#12, "running")                                                                                                                                                                                                                |
|       └─MemTableScan_26             | 10000.00    | root      | table:DDL_JOBS            |                                                                                                                                                                                                                                         |
+-------------------------------------+-------------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
11 rows in set (0.01 sec)
```
### 4. What is your TiDB version? (Required)
v6.5.4
ALL

### LINKED ISSUE #47743: tidb_mdl_view is not showing blocked ddl when ddl contains multiple table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- create 2 table, t1, t2, insert 1 row to them.
- in session 1:
```sql
begin;
select * from t1;
```
- in session 2, the sql will block
```sql
rename table t1 to t11, t2 to t22;
```

now query block
```sql
mysql> select * from mysql.tidb_mdl_view;
Empty set (0.02 sec)
```

it's because we're not put all table id into `ddl_jobs` view as `ActionMultiSchemaChange` do:
https://github.com/pingcap/tidb/blob/3ef01b5882cccec1d043cba36037b276a3ddbf00/pkg/executor/executor.go#L492

query using this sql, we can see the block, 122 is the table id of `t1`:
```sql
mysql> SELECT job_id,
    ->     json_extract(cast(cast(job_meta as char) as json), '$.schema_name') as db_name,
    ->     json_extract(cast(cast(job_meta as char) as json), '$.table_name') as table_name,
    ->     json_extract(cast(cast(job_meta as char) as json), '$.query') as query,
    ->     session_id,
    ->     txnstart,
    ->     tidb_decode_sql_digests(all_sql_digests, 4096) AS SQL_DIGESTS
    ->   FROM mysql.tidb_ddl_job,
    ->     information_schema.cluster_tidb_trx,
    ->     information_schema.cluster_processlist
    ->   WHERE tidb_ddl_job.processing = 1 and Find_in_set(122, tidb_ddl_job.table_ids)
    ->     AND Find_in_set(122, cluster_tidb_trx.related_table_ids)
    ->     AND cluster_tidb_trx.session_id = cluster_processlist.id;
+--------+---------+------------+-------------------------------------+------------+----------------------------------------+--------------------------------+
| job_id | db_name | table_name | query                               | session_id | txnstart                               | SQL_DIGESTS                    |
+--------+---------+------------+-------------------------------------+------------+----------------------------------------+--------------------------------+
|    126 | "test"  | "t2"       | "rename table t1 to t11, t2 to t22" | 1103101964 | 10-18 14:46:58.547(445018700132384769) | ["begin","select * from `t1`"] |
+--------+---------+------------+-------------------------------------+------------+----------------------------------------+--------------------------------+
```

### 4. What is your TiDB version? (Required)
v7.4.0

### LINKED ISSUE #50149: `tidb_mdl_view` is not accurate
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
sesson1> insert into t values (1);
Query OK, 1 row affected (0.02 sec)

sesson1> insert into t values (1);
Query OK, 1 row affected (0.00 sec)

sesson1> alter table t add unique idx(id);
ERROR 1062 (23000): Duplicate entry '1' for key 't.idx'

sesson2> begin;
Query OK, 0 rows affected (0.00 sec)

sesson2> select id from t;
+------+
| id   |
+------+
|    1 |
|    1 |
+------+
2 rows in set (0.00 sec)

sesson3> select * from tidb_mdl_view\G
*************************** 1. row ***************************
     job_id: 164
    db_name: test
 table_name: t
      query: alter table t add index idx(id)
 session_id: 199229446
   txnstart: 01-07 15:23:00.271(446853855384961025)
SQL_DIGESTS: ["begin","select `id` from `t`"]
*************************** 2. row ***************************
     job_id: 163
    db_name: test
 table_name: t
      query: alter table t add unique idx(id)
 session_id: 199229446
   txnstart: 01-07 15:23:00.271(446853855384961025)
SQL_DIGESTS: ["begin","select `id` from `t`"]
2 rows in set (0.02 sec)

sesson4> begin;
Query OK, 0 rows affected (0.00 sec)

sesson4> select id as col from t;  
+------+
| col  |
+------+
|    1 |
|    1 |
+------+
2 rows in set (0.00 sec)

sesson3> select * from tidb_mdl_view\G
*************************** 1. row ***************************
     job_id: 164
    db_name: test
 table_name: t
      query: alter table t add index idx(id)
 session_id: 199229450
   txnstart: 01-07 15:27:18.021(446853922952577025)
SQL_DIGESTS: ["begin","select `id` as `col` from `t`"]
*************************** 2. row ***************************
     job_id: 164
    db_name: test
 table_name: t
      query: alter table t add index idx(id)
 session_id: 199229446
   txnstart: 01-07 15:23:00.271(446853855384961025)
SQL_DIGESTS: ["begin","select `id` from `t`"]
*************************** 3. row ***************************
     job_id: 163
    db_name: test
 table_name: t
      query: alter table t add unique idx(id)
 session_id: 199229450
   txnstart: 01-07 15:27:18.021(446853922952577025)
SQL_DIGESTS: ["begin","select `id` as `col` from `t`"]
*************************** 4. row ***************************
     job_id: 163
    db_name: test
 table_name: t
      query: alter table t add unique idx(id)
 session_id: 199229446
   txnstart: 01-07 15:23:00.271(446853855384961025)
SQL_DIGESTS: ["begin","select `id` from `t`"]
4 rows in set (0.02 sec)

```

### 2. What did you expect to see? (Required)

```
sesson3> select * from tidb_mdl_view\G
*************************** 1. row ***************************
     job_id: 164
    db_name: test
 table_name: t
      query: alter table t add index idx(id)
 session_id: 199229446
   txnstart: 01-07 15:23:00.271(446853855384961025)
SQL_DIGESTS: ["begin","select `id` from `t`"]
```

### 3. What did you see instead (Required)

tidb_mdl_view information not accurate.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #50149, close #46933, close #47743

Problem Summary:

### What is changed and how it works?
1. Use mysql.tidb_mdl_info and mysql.ddl_job so that we don't query all the history DDLs

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
``` SQL
mysql> SELECT tidb_mdl_info.job_id, JSON_EXTRACT(cast(cast(job_meta as char) as json), "$.schema_name"), JSON_EXTRACT(cast(cast(job_meta as char) as json), "$.table_name"), JSON_EXTRACT(cast(cast(job_meta as char) as json), "$.query"), session_id, cluster_tidb_trx.start_time, tidb_decode_sql_digests(all_sql_digests, 4096) AS SQL_DIGESTS FROM mysql.tidb_ddl_job, mysql.tidb_mdl_info, information_schema.cluster_tidb_trx WHERE tidb_ddl_job.job_id=tidb_mdl_info.job_id AND CONCAT(',', tidb_mdl_info.table_ids, ',') REGEXP CONCAT(',', REPLACE(cluster_tidb_trx.related_table_ids, ',', '|'), ',') != 0;
+--------+---------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------+------------+----------------------------+----------------------------------+
| job_id | JSON_EXTRACT(cast(cast(job_meta as char) as json), "$.schema_name") | JSON_EXTRACT(cast(cast(job_meta as char) as json), "$.table_name") | JSON_EXTRACT(cast(cast(job_meta as char) as json), "$.query") | session_id | start_time                 | SQL_DIGESTS                      |
+--------+---------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------+------------+----------------------------+----------------------------------+
|   1336 | test                                                              | t                                                                | alter table t add index idx(id)                             |    2097160 | 2024-01-08 15:37:26.450000 | ["begin","select `id` from `t`"] |
+--------+---------------------------------------------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------+------------+----------------------------+----------------------------------+
1 row in set (0.00 sec)
```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/sessionctx/variable/session.go [hunk 1]
```diff
@@ -2084,6 +2084,7 @@ func NewSessionVars(hctx HookContext) *SessionVars {
 	if EnableRowLevelChecksum.Load() {
 		vars.EnableRowLevelChecksum = true
 	}
+	vars.systems[MaxAllowedPacket] = strconv.Itoa(int(DefMaxAllowedPacket))
```
Comment (tangenta) [inline pkg/sessionctx/variable/session.go:2087]: Why change this?

Comment (wjhuang2016) [reply pkg/sessionctx/variable/session.go:2094]: So that we can use concat in UT

**Review by tangenta — APPROVED** [review]

File: pkg/infoschema/test/clustertablestest/cluster_tables_test.go [hunk 2]
```diff
@@ -855,7 +863,13 @@ func TestMDLView(t *testing.T) {
 			tk3 := s.newTestKitWithRoot(t)
 			tk.MustExec("use test")
 			tk.MustExec("set global tidb_enable_metadata_lock=1")
-			tk.MustExec(c.createTable)
+			for _, cr := range c.createTable {
+				if strings.Contains(c.name, "err") {
+					_, _ = tk.Exec(cr)
```
Comment (D3Hunter) [inline pkg/infoschema/test/clustertablestest/cluster_tables_test.go:868]: check it does return err?

File: pkg/session/session.go [hunk 3]
```diff
@@ -3707,6 +3707,11 @@ func (s *session) loadCommonGlobalVariablesIfNeeded() error {
 	}
 	if s.Value(sessionctx.Initing) != nil {
 		// When running bootstrap or upgrade, we should not access global storage.
+		// But we need to init max_allowed_packet to use concat function during bootstrap or upgrade.
+		err := vars.SetSystemVar(variable.MaxAllowedPacket, strconv.FormatUint(variable.DefMaxAllowedPacket, 10))
+		if err != nil {
+			logutil.BgLogger().Error("set system variable max_allowed_packet error", zap.Error(err))
```
Comment (D3Hunter) [inline pkg/session/session.go:3713]: should we return err if it's required?

File: pkg/infoschema/test/clustertablestest/cluster_tables_test.go (hunk 2 above)
Comment (wjhuang2016) [reply pkg/infoschema/test/clustertablestest/cluster_tables_test.go:868]: Not all the SQLs return an error, I don't think it's necessary to check the error since it is just a preparation.

File: pkg/session/session.go (hunk 3 above)
Comment (wjhuang2016) [reply pkg/session/session.go:3713]: It's not always required, only when we need to create or replace this view. Do you think we still need to return an error?

**Review by D3Hunter — APPROVED** [review]

File: pkg/session/bootstrap.go [hunk 4]
```diff
@@ -460,19 +460,18 @@ const (
...
-			txnstart,
+			cluster_tidb_trx.start_time,
 			tidb_decode_sql_digests(all_sql_digests, 4096) AS SQL_DIGESTS
-		FROM information_schema.ddl_jobs,
-			information_schema.cluster_tidb_trx,
-			information_schema.cluster_processlist
-		WHERE (ddl_jobs.state != 'synced' and ddl_jobs.state != 'cancelled')
-			AND Find_in_set(ddl_jobs.table_id, cluster_tidb_trx.related_table_ids)
-			AND cluster_tidb_trx.session_id = cluster_processlist.id
+		FROM mysql.tidb_ddl_job,
```
Comment (zimulala) [inline pkg/session/bootstrap.go:470]: TiDB versions less than 6.2 do not have this table. Does this have compatibility issues?

Comment (wjhuang2016) [reply pkg/session/bootstrap.go:470]: After testing, the old owner doesn't check if the table exists or not. So there it no compatibility issues for now.

Comment (zimulala) [reply pkg/session/bootstrap.go:470]: Got it. Maybe we can create an issue.

**Review by zimulala — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM for now but version rollback needs to be considered for the cases like this. @Benjamin2037
