### PR TITLE
ddl:  forbid create `Generated column` with `Grouping` function

### LINKED ISSUE #49909: DDL should report an error when creating a generated column with function "grouping"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
> create table t(a int, b int as ((grouping(a))) stored);
```

### 2. What did you expect to see? (Required)

In MySQL, it reports an error:

```
mysql> create table t(a int, b int as ((grouping(a))) stored);
ERROR 1111 (HY000): Invalid use of group function
```

### 3. What did you see instead (Required)

```
mysql> create table t(a int, b int as ((grouping(a))) stored);
Query OK, 0 rows affected (0.09 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #49909

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/generated_column.go [hunk 1]
```diff
@@ -289,6 +289,11 @@ type illegalFunctionChecker struct {
 func (c *illegalFunctionChecker) Enter(inNode ast.Node) (outNode ast.Node, skipChildren bool) {
 	switch node := inNode.(type) {
 	case *ast.FuncCallExpr:
+		// Grouping function is not allowed, issue #49909.
+		if node.FnName.L == ast.Grouping {
```
Comment (lcwangchao) [inline pkg/ddl/generated_column.go:293]: I think it's better to add it to `IllegalFunctions4GeneratedColumns` ?

Comment (jiyfhust) [reply pkg/ddl/generated_column.go:293]: > I think it's better to add it to `IllegalFunctions4GeneratedColumns` ?

`illegalFunctionChecker ` is for that. It parse the `expr` and set flag, then `IllegalFunctions4GeneratedColumns` judge it.

**Review by lcwangchao — APPROVED** [review]

**Comment by jiyfhust** [comment]
/cc Benjamin2037 tangenta wjhuang2016 ywqzzy zimulala
PTAL, not complex problem.

**Review by wjhuang2016 — APPROVED** [review]
