### PR TITLE
expression: fix the problem that the function cast duration as time do not respect system timestamp

### LINKED ISSUE #36279: The function CAST(duration as time) do not respect system timestamp.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
SET timestamp=UNIX_TIMESTAMP('2011-11-01 17:48:00');
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
  pk time(6) NOT NULL DEFAULT '00:00:00.000000',
  col_date_not_null date NOT NULL,
  PRIMARY KEY (pk)
);
INSERT INTO t1 VALUES ('00:00:00.000000','2001-09-10');
INSERT INTO t1 VALUES ('12:07:41.148239','2000-05-23');
SELECT COALESCE (pk, col_date_not_null) FROM  t1;
DROP TABLE t1;
SET timestamp=DEFAULT; 
```

### 2. What did you expect to see? (Required)
```mysql
mysql> SELECT COALESCE (pk, col_date_not_null) FROM  t1;
+----------------------------------+
| COALESCE (pk, col_date_not_null) |
+----------------------------------+
| 2011-11-01 00:00:00.000000       |
| 2011-11-01 12:07:41.148239       |
+----------------------------------+
2 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
```mysql
mysql> SELECT COALESCE (pk, col_date_not_null) FROM  t1;
+----------------------------------+
| COALESCE (pk, col_date_not_null) |
+----------------------------------+
| 2022-01-11 00:00:00.000000       |
| 2022-01-11 12:07:41.148239       |
+----------------------------------+
2 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v5.5.0-alpha-34-g9cc1b169f
Edition: Community
Git Commit Hash: 9cc1b169f9080b34eda8468d7a974d2a387673dd
Git Branch: master
UTC Build Time: 2022-01-05 19:21:07
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by mengxin9014**
### What problem does this PR solve?

Issue Number: close #36279

Problem Summary:
description in #36279

### What is changed and how it works?
Fix the problem that the function cast duration as time do not respect system timestamp.
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the problem that the function cast duration as time do not respect system timestamp.
```

### CODE REVIEW

File: expression/builtin_cast.go [hunk 1]
```diff
@@ -23,6 +23,7 @@
 package expression
 
 import (
+	"github.com/pingcap/tipb/go-tipb"
```
Comment (hawkingrei) [inline expression/builtin_cast.go:26]: Please re-order the imports.

Comment (mengxin9014) [reply expression/builtin_cast.go]: > Please re-order the imports.

done.

**Review by hawkingrei — APPROVED** [review]

File: expression/builtin_cast_vec.go [hunk 2]
```diff
@@ -608,6 +607,7 @@ func (b *builtinCastDurationAsTimeSig) vecEvalTime(input *chunk.Chunk, result *c
 	ds := buf.GoDurations()
 	times := result.Times()
 	stmtCtx := b.ctx.GetSessionVars().StmtCtx
+	ts, _ := getStmtTimestamp(b.ctx)
```
Comment (hawkingrei) [inline expression/builtin_cast_vec.go:610]: not deal with this error ？

Comment (mengxin9014) [reply expression/builtin_cast_vec.go:610]: > not deal with this error ？

If err is not nil it will return time.Now, this is to be expected

Comment (windtalker) [reply expression/builtin_cast_vec.go:610]: But if may return zero time [when error happens](https://github.com/pingcap/tidb/blob/4b50e6745284d2bdc6ac25e248f884f11bb60319/expression/helper.go#L175).

Comment (mengxin9014) [reply expression/builtin_cast_vec.go]: > But if may return zero time [when error happens](https://github.com/pingcap/tidb/blob/4b50e6745284d2bdc6ac25e248f884f11bb60319/expression/helper.go#L175).

done.
It will handle error here, if err != nil ts will be set to current time.

**Review by windtalker — APPROVED** [review]
Others LGTM

File: expression/builtin_cast.go [hunk 3]
```diff
@@ -23,10 +23,6 @@
 package expression
 
 import (
-	"math"
-	"strconv"
-	"strings"
-
```
[the remark this answers is not in the document]
Comment (mengxin9014) [reply expression/builtin_cast.go:29]: > Why change this?

done.

**Review by hawkingrei — APPROVED** [review]
