### PR TITLE
ttl: fix the issue that the task is not cancelled after transfering owners

### LINKED ISSUE #57784: TTL Task cannot be canceled if the TiDB lost heartbeat
## Bug Report

```go
// checkInvalidTask removes the task whose owner is not myself or which has disappeared
func (m *taskManager) checkInvalidTask(se session.Session) {
...

		if t.OwnerID == m.id {
			ownRunningTask = append(ownRunningTask, task)
		}
	}

	m.runningTasks = ownRunningTask
}
```

If the `t.OwnerID != m.id`, the task should also be canceled and release the worker.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #57784

Problem Summary:

The TTL task is not cancelled after the owner transfers to other TiDB nodes.

### What changed and how does it work?

1. Don't report status when the owner is not myself.
2. Don't update heartbeat when the owenr is not myself.
3. Check the affected rows to see whether task manager `UPDATE` successfully.
4. Cancel the task after finding that the owner is not myself.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/timer/tablestore/store.go [hunk 1]
```diff
@@ -117,7 +117,7 @@ func (s *tableTimerStoreCore) List(ctx context.Context, cond api.Cond) ([]*api.T
 	}
 	defer back()
 
-	if sessVars := sctx.GetSessionVars(); sessVars.GetEnableIndexMerge() {
+	if sessVars := sctx.GetSessionVars(); !sessVars.GetEnableIndexMerge() {
```
Comment (YangKeao) [inline pkg/timer/tablestore/store.go:120]: A tiny typo fix @lcwangchao

File: pkg/ttl/ttlworker/timer_test.go [hunk 2]
```diff
@@ -350,8 +351,9 @@ func TestTTLTimerHookOnEvent(t *testing.T) {
 	require.Equal(t, summaryData, timer.SummaryData)
 	adapter.AssertExpectations(t)
 
+	tz := timeutil.SystemLocation()
 	// job not exists but table ttl not enabled
-	watermark := time.Unix(3600*123, 0)
+	watermark := time.Unix(3600*123, 0).In(tz)
```
Comment (YangKeao) [inline pkg/ttl/ttlworker/timer_test.go:356]: A fix to make this test stable in CI environment (when the `SystemLocation` is possibly not `Local`). I've faced the same error in https://github.com/pingcap/tidb/pull/57718, so I think it's not related to other changes in this PR.

File: pkg/ttl/ttlworker/task_manager.go [hunk 3]
```diff
@@ -451,14 +451,19 @@ func (m *taskManager) updateHeartBeat(ctx context.Context, se session.Session, n
...
 		if err != nil {
 			return err
 		}
 		_, err = se.ExecuteSQL(ctx, sql, args...)
 		if err != nil {
 			return errors.Wrapf(err, "execute sql: %s", sql)
 		}
+
+		if se.GetSessionVars().StmtCtx.AffectedRows() != 1 {
+			return errors.Errorf("fail to update task status, maybe the owner is not myself, affected rows: %d",
```
Comment (zimulala) [inline pkg/ttl/ttlworker/task_manager.go:464]: Do we need to print the current taskManager ID?
Could the `AffectedRows() ` be greater than 1?

Comment (YangKeao) [reply pkg/ttl/ttlworker/task_manager.go]: Good suggestion. Done! :+1:

**Review by zimulala — APPROVED** [review]
LGTM
