### PR TITLE
planner: apply min-max eliminator on common handle columns

### LINKED ISSUE #18571: clustered index min, max in a single statement return error.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> set @@tidb_enable_clustered_index = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> create table t (a int, b int, c int, primary key(a, b));
Query OK, 0 rows affected (0.07 sec)

mysql> insert t values (1, 1, 1);
Query OK, 1 row affected (0.01 sec)

mysql> select max(a), min(a) from t;
ERROR 1105 (HY000): runtime error: index out of range [0] with length 0
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

ERROR 1105 (HY000): runtime error: index out of range [0] with length 0

### 4. Affected version (Required)

latest master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #18571 

Problem Summary:

The original max_min_eliminator treats the common handle path as the index path. A lot of index path related fields are nil, which results in the index out of range error.

### What is changed and how it works?

Proposal: [xxx](url) 

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- No release note.

### CODE REVIEW

File: planner/core/rule_max_min_eliminate.go [hunk 1]
```diff
@@ -61,16 +61,18 @@ func (a *maxMinEliminator) checkColCanUseIndex(plan LogicalPlan, col *expression
...
 		for _, path := range p.possibleAccessPaths {
-			// TODO: support common handle path.
-			if path.IsIntHandlePath {
-				// Since table path can contain accessConds of at most one column,
-				// we only need to check if all of the conditions can be pushed down as accessConds
-				// and `col` is the handle column.
-				if p.handleCols != nil && col.Equal(nil, p.handleCols.GetCol(0)) {
-					if _, filterConds := ranger.DetachCondsForColumn(p.ctx, conditions, col); len(filterConds) != 0 {
-						return false
+			if path.IsIntHandlePath || path.IsCommonHandlePath {
```
Comment (coocood) [inline planner/core/rule_max_min_eliminate.go:64]: we can use `path.IsTablePath()`

File: executor/aggregate_test.go [hunk 2]
```diff
@@ -839,6 +839,21 @@ func (s *testSuiteAgg) TestAggEliminator(c *C) {
...
+func (s *testSuiteAgg) TestClusterIndexMinMaxEliminator(c *C) {
+	tk := testkit.NewTestKitWithInit(c, s.store)
+	tk.MustExec("drop table if exists t;")
+	tk.MustExec("set @@tidb_enable_clustered_index=1;")
+	tk.MustExec("create table t (a int, b int, c int, primary key(a, b));")
+	for i := 0; i < 10+1; i++ {
+		tk.MustExec("insert into t values (?, ?, ?)", i, i, i)
+	}
+	tk.MustQuery("select max(a), max(b) from t;").Check(testkit.Rows("10 10"))
+	tk.MustQuery("select max(a), max(b), max(a) from t;").Check(testkit.Rows("10 10 10"))
```
Comment (coocood) [inline executor/aggregate_test.go:851]: duplicated `max(a)`

File: planner/core/testdata/integration_suite_in.json [hunk 3]
```diff
@@ -29,7 +29,10 @@
   {
     "name": "TestMaxMinEliminate",
     "cases": [
-      "explain (select max(a) from t) union (select min(a) from t)"
+      "explain (select max(a) from t) union (select min(a) from t)",
+      "explain select min(a), max(a) from cluster_index_t",
+      "explain select min(b), max(b) from cluster_index_t where a = 1",
+      "explain select min(b), max(b) from cluster_index_t where b = 1"
```
Comment (coocood) [inline planner/core/testdata/integration_suite_in.json:35]: This case doesn't make much sense.

**Comment by coocood** [comment]
LGTM
