### PR TITLE
*: Fix issue 1135

### LINKED ISSUE #1135: `delete m1 from t1 m1,t1 m2 where m1.F2>m2.F2;` gets the wrong result
1.What did you do?
```
drop table t1;
create table t1 (F1 VARCHAR(30));
insert into t1 (F1) values ('1'), ('2');
delete m1 from t1 m1,t1 m2 where m1.F1>1;
select * from t1;
```

２.What did you expect to see?
+------+
| F1   |
+------+
| 1    |
+------+

３.What did you see instead?
Empty set (0.01 sec)

### PR DESCRIPTION
**Pull request by zimulala**
fix #1135

### CODE REVIEW

File: executor/executor_xapi.go [hunk 1]
```diff
@@ -98,8 +98,16 @@ func (e *XSelectTableExec) Close() error {
 	return nil
 }
 
-func resultRowToRow(t table.Table, h int64, data []types.Datum) *Row {
-	entry := &RowKeyEntry{Handle: h, Tbl: t}
+func resultRowToRow(t table.Table, h int64, data []types.Datum, fields []*ast.ResultField) *Row {
```
Comment (shenli) [inline executor/executor_xapi.go]: Pass tableAsName as parameter is enough?

Comment (zimulala) [inline executor/executor_xapi.go]: Enough, but it will do some judgment, so I use `e.Fields()` as the parameter.

File: executor/executor_write.go [hunk 2]
```diff
@@ -306,9 +304,12 @@ func (e *DeleteExec) Next() (*Row, error) {
 			if !ok {
 				return nil, errors.Errorf("Unknown table '%s' in MULTI DELETE", t.Name.O)
 			}
-			tblIDMap[t.TableInfo.ID] = true
+			tblMap[t.Name.L] = true
```
Comment (coocood) [inline executor/executor_write.go]: tables in different databases may have the same name.

**Comment by zimulala** [comment]
PTAL @coocood @shenli

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM
