### PR TITLE
ttl: escape parameters for finish job sql

### LINKED ISSUE #40115: ttl fail to update error message
The error message can contain unsafe characters, and cannot be concated into the SQL directly. We should pass it through parameters.

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #40115 

Problem Summary:

The summary could contain special characters (as it's a json containing error message, and the error message is unpredictable). We should pass it through the parameters.

### What is changed and how it works?

Pass the summary through parameters, and it should be escaped automatically. This PR also append the SQL to the error information for debug.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that TTL job failed to upload error message to the status table
```

### CODE REVIEW

File: ttl/ttlworker/job.go [hunk 1]
```diff
@@ -30,15 +30,15 @@ import (
...
 	return fmt.Sprintf(updateJobCurrentStatusTemplate, newStatus, tableID, oldStatus, jobID)
 }
 
-func finishJobSQL(tableID int64, finishTime time.Time, summary string, jobID string) string {
-	return fmt.Sprintf(finishJobTemplate, finishTime.Format(timeFormat), summary, tableID, jobID)
+func finishJobSQL(tableID int64, finishTime time.Time, summary string, jobID string) (string, []interface{}) {
+	return fmt.Sprintf(finishJobTemplate, finishTime.Format(timeFormat), tableID, jobID), []interface{}{summary}
 }
 
 func updateJobState(tableID int64, currentJobID string, currentJobState string, currentJobOwnerID string) string {
```
Comment (lcwangchao) [inline ttl/ttlworker/job.go:44]: Does `current_job_state` contains some special characters. I think a more safer way is to move all of paramters to the arguments

File: ttl/ttlworker/job.go [hunk 2]
```diff
@@ -30,15 +30,15 @@ import (
...
-const finishJobTemplate = "UPDATE mysql.tidb_ttl_table_status SET last_job_id = current_job_id, last_job_start_time = current_job_start_time, last_job_finish_time = '%s', last_job_ttl_expire = current_job_ttl_expire, last_job_summary = '%s', current_job_id = NULL, current_job_owner_id = NULL, current_job_owner_hb_time = NULL, current_job_start_time = NULL, current_job_ttl_expire = NULL, current_job_state = NULL, current_job_status = NULL, current_job_status_update_time = NULL WHERE table_id = %d AND current_job_id = '%s'"
+const finishJobTemplate = "UPDATE mysql.tidb_ttl_table_status SET last_job_id = current_job_id, last_job_start_time = current_job_start_time, last_job_finish_time = '%s', last_job_ttl_expire = current_job_ttl_expire, last_job_summary = %%?, current_job_id = NULL, current_job_owner_id = NULL, current_job_owner_hb_time = NULL, current_job_start_time = NULL, current_job_ttl_expire = NULL, current_job_state = NULL, current_job_status = NULL, current_job_status_update_time = NULL WHERE table_id = %d AND current_job_id = '%s'"
```
Comment (lcwangchao) [inline ttl/ttlworker/job.go:33]: Format the SQL to multi lines seems easier to read

**Review by lcwangchao — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
