### PR TITLE
statistics: add Destroy method and handle session recycling (#59546)

### LINKED ISSUE #59524: release the internal session which may meet error like #54022
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

like the analysis in #54022, the internal session may not be released after it meets some error.

the pull that intended to fix that issue only removed the error found in the issue. but the unrealised behavior is not changed.

### PR DESCRIPTION
**Pull request by Rustin170506**
This is an automated cherry-pick of #59546

### What problem does this PR solve?

Issue Number: close #59524 close https://github.com/pingcap/tidb/issues/59560

Problem Summary:

### What changed and how does it work?

ref https://github.com/pingcap/tidb/pull/59522

This is an alternative API design to solve the problem. I believe explicitly using destroy instead of exposing implementation details is a better approach to fix it.

I also added more logs to help us inspect error cases.

Note: This PR doesn’t address the root cause of the issues; it only ensures that we don’t encounter OOM problems. We still need to figure out why we’re running into this kind of stats loading.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that the internal session used by statistics may not be released and cause possible memory leak.
修复统计信息在使用的内部会话在遇到错误时可能没有被释放的问题，该问题可能导致内存泄漏。
```

### CODE REVIEW

**Comment by Rustin170506** [comment]
Tested the logs locally:
```log
[2025/02/19 11:49:05.963 +08:00] [WARN] [domain.go:2449] ["load histograms failed"] [error="not implemented\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).LoadNeededHistograms.func1\n\t/Users/rustin/code/tidb/pkg/statistics/handle/storage/stats_read_writer.go:324\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.WrapTxn\n\t/Users/rustin/code/tidb/pkg/statistics/handle/util/util.go:207\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx\n\t/Users/rustin/code/tidb/pkg/statistics/handle/util/util.go:114\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).LoadNeededHistograms\n\t/Users/rustin/code/tidb/pkg/statistics/handle/storage/stats_read_writer.go:322\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).asyncLoadHistogram\n\t/Users/rustin/code/tidb/pkg/domain/domain.go:2447\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1\n\t/Users/rustin/code/tidb/pkg/util/wait_group_wrapper.go:98\nruntime.goexit\n\t/opt/homebrew/Cellar/go/1.23.6/libexec/src/runtime/asm_arm64.s:1223"]
```

File: pkg/statistics/handle/storage/read.go [hunk 1]
```diff
@@ -535,7 +536,14 @@ func LoadNeededHistograms(sctx sessionctx.Context, statsCache util.StatsCache, l
 			err = loadNeededIndexHistograms(sctx, statsCache, item, loadFMSketch)
 		}
 		if err != nil {
-			return err
+			statslogutil.StatsLogger().Error("load needed histogram failed",
```
Comment (Rustin170506) [inline pkg/statistics/handle/storage/read.go:539]: @winoros Is there any further information we can log here?

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by lance6716 — APPROVED** [review]

File: pkg/statistics/handle/storage/read.go (hunk 1 above)
Comment (winoros) [reply pkg/statistics/handle/storage/read.go:539]: i think is no.

**Review by winoros — APPROVED** [review]
