### PR TITLE
ddl: use another way to get index uniqueness during task exec init

### LINKED ISSUE #50435: add index status is always running after inject pd leader io delay 500ms lasts for 2mins
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、tidb_enable_dist_task='on' and enable global sort
2、add index
3、inject pd leader io delay 500ms lasts for 2mins

[2024/01/12 17:19:09.227 +08:00] [INFO] [add_index.go:78] ["will add index"] [db=sysbench_64_7000w] [table=sbtest1] [addIndexColumnName=c] [addIndexName=index_test_1705051149227]
[2024/01/12 17:19:09.227 +08:00] [INFO] [util.go:74] ["alter table sbtest1 add index index_test_1705051149227 (c)"]

[2024/01/12 17:20:15.057 +08:00] [INFO] [chaos.go:65] ["Run chaos"]
[2024/01/12 17:22:15.074 +08:00] [INFO] [chaos.go:94] ["Clean chaos"]

[2024/01/12 17:27:15.234 +08:00] [INFO] [chaos.go:82] ["Run chaos success"] 
[2024/01/12 17:29:15.234 +08:00] [INFO] [chaos.go:94] ["Clean chaos"] 

[2024/01/12 17:34:15.459 +08:00] [INFO] [chaos.go:82] ["Run chaos success"]
[2024/01/12 17:36:15.460 +08:00] [INFO] [chaos.go:94] ["Clean chaos"] 

[2024/01/12 17:41:15.604 +08:00] [INFO] [chaos.go:65] ["Run chaos"] 
[2024/01/12 17:43:14.778 +08:00] [INFO] [chaos.go:94] ["Clean chaos"]

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index status is always running after inject pd leader io delay 500ms lasts for 2mins

the status of ddl job is not synced after 1h0m0s (now: 2024-01-12 18:19:18, jobId: 546, job type: add index /* ingest cloud */, state: running)
operatorLogs:
[2024-01-12 17:19:09] ###### start adding index
alter table sbtest1 add index index_test_1705051149227 (c)
[2024-01-12 17:19:09] ###### wait for ddl job finish
[2024-01-12 18:19:18] ###### wait for ddl job finish timeout(1h0m0s)
select job_id, job_type, state from information_schema.ddl_jobs where query = 'alter table sbtest1 add index index_test_1705051149227 (c)'
jobId: 546, job type: add index /* ingest cloud */, state: running

tidb logs：
[2024/01/12 17:20:56.877 +08:00] [ERROR] [txn.go:602] ["active transaction fail"] [error="[tikv:9001]PD server timeout: "]
[2024/01/12 17:20:56.877 +08:00] [INFO] [tidb.go:286] ["rollbackTxn called due to ddl/autocommit failure"]
[2024/01/12 17:20:56.877 +08:00] [WARN] [session.go:2251] ["run statement failed"] [conn=2940214166] [session_alias=] [schemaVersion=712] [error="[tikv:9001]PD server timeout: "] [session="{\n  \"currDBName\": \"sysbench_64_7000w\",\n  \"id\": 2940214166,\n  \"preparedStmtCount\": 578,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": {\n    \"Username\": \"root\",\n    \"Hostname\": \"[10.200.75.94](http://10.200.75.94/)\",\n    \"CurrentUser\": false,\n    \"AuthUsername\": \"root\",\n    \"AuthHostname\": \"%\",\n    \"AuthPlugin\": \"mysql_native_password\"\n  }\n}"]
[2024/01/12 17:20:57.186 +08:00] [ERROR] [manager.go:442] ["task manager met error"] [error="[tikv:9001]PD server timeout: "] [stack="[github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).logErr\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/manager.go:442\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).handleExecutableTask\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/manager.go:391\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).handleExecutableTasks.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/manager.go:257\ngithub.com/pingcap/tidb/pkg/resourcemanager/pool/spool.(*Pool).run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/resourcemanager/pool/spool/spool.go:144](http://github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).logErr/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/manager.go:442/ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).handleExecutableTask/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/manager.go:391/ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).handleExecutableTasks.func1/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/manager.go:257/ngithub.com/pingcap/tidb/pkg/resourcemanager/pool/spool.(*Pool).run.func1/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/resourcemanager/pool/spool/spool.go:144)"]
[2024/01/12 17:20:57.186 +08:00] [INFO] [pd_service_discovery.go:871] 
[2024/01/12 17:20:57.187 +08:00] [INFO] [backend_mgr.go:190] ["close one backend for DDL job"] ["job ID"=546] ["current memory usage"=0] ["max memory quota"=8589934592]
[2024/01/12 17:20:57.288 +08:00] [ERROR] [pd_service_discovery.go:534] ["[pd] failed to update member"] [urls="[http://tc-pd-0.tc-pd-peer.endless-ha-test-add-index-tps-5520324-1-724.svc:2379,http://tc-pd-1.tc-pd-peer.endless-ha-test-add-index-tps-5520324-1-724.svc:2379,http://tc-pd-2.tc-pd-peer.endless-ha-test-add-index-tps-5520324-1-724.svc:2379]"] [error="[PD:client:ErrClientGetMember]get member failed"]
[2024/01/12 17:20:57.288 +08:00] [ERROR] [tso_dispatcher.go:498] ["[tso] getTS error after processing requests"] [dc-location=global] [stream-addr=http://tc-pd-0.tc-pd-peer.endless-ha-test-add-index-tps-5520324-1-724.svc:2379/] [error="[PD:client:ErrClientGetTSO]get TSO failed, %v: rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster"]
[2024/01/12 17:20:57.288 +08:00] [WARN] [backoff.go:179] ["pdRPC backoffer.maxSleep 30000ms is exceeded, errors:\nget timestamp failed: rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster at 2024-01-12T17:20:50.69242944+08:00\nget timestamp failed: rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster at 2024-01-12T17:20:52.446763495+08:00\nget timestamp failed: rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster at 2024-01-12T17:20:55.023437291+08:00\ntotal-backoff-times: 15, backoff-detail: pdRPC:15, maxBackoffTimeExceeded: true, maxExcludedTimeExceeded: false\nlongest sleep type: pdRPC, time: 31737ms"]
[2024/01/12 17:20:57.288 +08:00] [ERROR] [txn.go:602] ["active transaction fail"] [error="[tikv:9001]PD server timeout: "]
[2024/01/12 17:20:57.288 +08:00] [INFO] [tidb.go:286] ["rollbackTxn called due to ddl/autocommit failure"]
[2024/01/12 17:20:57.289 +08:00] [INFO] [pd_service_discovery.go:871] ["[pd] cannot update member from this address"] [address=http://tc-pd-0.tc-pd-peer.endless-ha-test-add-index-tps-5520324-1-724.svc:2379/] [error="[PD:client:ErrClientGetLeader]get leader failed, leader address doesn't exist"]
[2024/01/12 17:20:57.289 +08:00] [WARN] [session.go:2251] ["run statement failed"] [schemaVersion=712] [error="[tikv:9001]PD server timeout: "] [session="{\n  \"currDBName\": \"\",\n  \"id\": 0,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": null\n}"]
[2024/01/12 17:20:57.289 +08:00] [WARN] [nodes.go:134] ["get managed nodes met error"] [error="[tikv:9001]PD server timeout: "]

tidb full logs (testbed: endless-ha-test-add-index-tps-5520324-1-724):
[tidb-0.tar.gz](https://github.com/pingcap/tidb/files/13937461/tidb-0.tar.gz)
[tidb-1-2024-01-12T20-47-25.tar.gz](https://github.com/pingcap/tidb/files/13937473/tidb-1-2024-01-12T20-47-25.tar.gz)

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.6.0-alpha
Edition: Community
Git Commit Hash: 1ad36eb0ef293a7a6ec70c7a6783e0096b96ea4e
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2024-01-11 12:34:00
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-01-12T17:12:07.701+0800

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref #50307, close #50435

### What changed and how does it work?

This PR fixes the stuck issue cause by `indexInfo not found` when cancelling the task.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/backfilling_dist_executor.go [hunk 1]
```diff
@@ -156,6 +151,20 @@ func (s *backfillDistExecutor) Init(ctx context.Context) error {
 	return nil
 }
 
+func decodeIndexUniqueness(job *model.Job) (bool, error) {
+	unique := make([]bool, 1)
+	err := job.DecodeArgs(&unique[0])
+	if err != nil {
+		err = job.DecodeArgs(&unique)
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_dist_executor.go:158]: whey will it be a slice, didn't found it

Comment (D3Hunter) [reply pkg/ddl/backfilling_dist_executor.go:158]: would be better to have an explicit `unique` field, ok for now

Comment (tangenta) [reply pkg/ddl/backfilling_dist_executor.go:158]: https://github.com/pingcap/tidb/blob/7bfb7a3a99787fc33154da61e3f02551c9c7b94f/pkg/ddl/multi_schema_change.go#L388

File: go.mod [hunk 2]
```diff
@@ -69,7 +69,7 @@ require (
 	github.com/joho/sqltocsv v0.0.0-20210428211105-a6d6801d59df
 	github.com/kisielk/errcheck v1.6.3
 	github.com/klauspost/compress v1.17.1
-	github.com/ks3sdklib/aws-sdk-go v1.2.9
+	github.com/ks3sdklib/aws-sdk-go v1.2.7
```
Comment (D3Hunter) [inline go.mod:72]: why? we just upgrade it. https://github.com/pingcap/tidb/pull/50179

File: pkg/ddl/backfilling_dist_executor.go [hunk 3]
```diff
@@ -156,6 +151,20 @@ func (s *backfillDistExecutor) Init(ctx context.Context) error {
...
+	}
+	if err != nil {
+		return false, errors.Trace(err)
+	}
+	// We only support adding multiple unique indexes or multiple non-unique indexes,
```
Comment (Benjamin2037) [inline pkg/ddl/backfilling_dist_executor.go:163]: Seems this limitation is too strong, normally, one table only will have one or two uk.

File: go.mod (hunk 2 above)
Comment (tangenta) [reply go.mod:72]: There is a network problem with ks3 `Read()`. I want to make a quick test by downgrade the version.

File: pkg/ddl/backfilling_dist_executor.go (hunk 3 above)
Comment (tangenta) [reply pkg/ddl/backfilling_dist_executor.go:163]: It does not limit how many indexes a table can have. This means if there is a SQL like `add index i1, add unique index i2`, it will fallback to add them sequentially.

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]
