### PR TITLE
expression, types: fix the logic of converting duration to year

### LINKED ISSUE #48557: casting `Time` to `Year` gives the wrong result
### 1. Minimal reproduce step (Required)

```sql
select cast(cast('22:03' as time) as year);
```

### 2. What did you expect to see? (Required)

```sql
mysql> select cast(cast('22:03' as time) as year);
+-------------------------------------+
| cast(cast('22:03' as time) as year) |
+-------------------------------------+
|                                2023 |
+-------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```sql
mysql> select cast(cast('22:03' as time) as year);
+-------------------------------------+
| cast(cast('22:03' as time) as year) |
+-------------------------------------+
|                              220300 |
+-------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #48557

Problem Summary:

The correct behavior of converting time to year should be mixing the `Now` and duration, and then return the year.

Actually, it has two different behaviors when converting the `TIME` to `YEAR`.

1. In DDL, e.g. modify the column type from `TIME` to `YEAR`, it follows the "concatenation" rule. The `00:19:98` will be converted to `1998`. TiDB follows this behavior in all scenario before this PR. It's more like `TIME -> CHAR() -> YEAR`. This behavior has been covered by existing tests in `ddl/column_type_change` and `ddl/modify_column`.
2. In `SELECT` (cast implicitly or explicitly) and `INSERT` (inserting a `TIME` to a `YEAR` column), it's more like `TIME -> DATETIME -> YEAR`. It will mix the duration with the current time, and return the year.

This PR makes the second one the default behavior, and use a flag to follow the first behavior in `DDL` backfilling.

### What is changed and how it works?

Modify the logic of both `CastDurationAsInt` in expression and the `ConvertTo` in `types`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

### Release note

```release-note
Fix the issue that converting the `TIME` to `YEAR` gives an integer which represents the string of the time, rather then the year part of mixing the `TIME` and current time.
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

File: pkg/expression/builtin_cast_vec.go [hunk 1]
```diff
@@ -345,11 +345,18 @@ func (b *builtinCastDurationAsIntSig) vecEvalInt(ctx sessionctx.Context, input *
 
 		duration.Duration = ds[i]
 		duration.Fsp = fsp
-		dur, err := duration.RoundFrac(types.DefaultFsp, ctx.GetSessionVars().Location())
-		if err != nil {
-			return err
+
+		if b.tp.GetType() == mysql.TypeYear {
```
Comment (zanmato1984) [inline pkg/expression/builtin_cast_vec.go:349]: I would recommend to use a local bool variable outside the for loop to do this check, so that the loop body can be tighter.

File: pkg/types/convert_test.go [hunk 2]
```diff
@@ -271,7 +271,7 @@ func TestConvertType(t *testing.T) {
 	require.Equal(t, int64(2015), v)
 	v, err = Convert(ZeroDuration, ft)
 	require.NoError(t, err)
-	require.Equal(t, int64(0), v)
+	require.Equal(t, int64(time.Now().Year()), v)
```
Comment (zanmato1984) [inline pkg/types/convert_test.go:274]: This test may fail when line 272 executes in the past year than this line. But it's ok :)

**Review by zanmato1984 — APPROVED** [review]
LGTM

File: pkg/types/convert_test.go (hunk 2 above)
Comment (YangKeao) [reply pkg/types/convert_test.go:274]: Yes. Once TiDB fixes https://github.com/pingcap/tidb/issues/31648, we can make these tests stabler.

**Comment by YangKeao** [comment]
/retest

Yellow timeout :facepalm:
