### PR TITLE
sessionctx: add tidb_enable_list_partition global system variable

### LINKED ISSUE #25735: “tidb_enable_list_partition” is session variable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
show variables like "tidb_enable_list_partition";
show global variables like "tidb_enable_list_partition";
```

We should have a way to make the list partition work globally
### 2. What did you expect to see? (Required)
```
mysql> show variables like "tidb_enable_list_partition";
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_list_partition | OFF   |
+----------------------------+-------+
1 row in set (0.00 sec)

mysql> show global  variables like "tidb_enable_list_partition";
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_list_partition | OFF   |
+----------------------------+-------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> show variables like "tidb_enable_list_partition";
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_list_partition | OFF   |
+----------------------------+-------+
1 row in set (0.00 sec)

mysql> show global  variables like "tidb_enable_list_partition";
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.0
Edition: Community
Git Commit Hash: 8acd5c88471cb7b4d4c4a8ed73b4d53d6833f13e
Git Branch: heads/refs/tags/v5.1.0
UTC Build Time: 2021-06-23 12:34:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #25735

Problem Summary: tidb_enable_list_partition was only defined as session variable, not a global variable

### What is changed and how it works?

What's Changed: Added ScopeGlobal to the system variable

How it Works: It now is in global scope as well as session scope

### Related changes

- Need to cherry-pick to the release branch
[] release-5.1

### Check List 

Tests 

- Unit test
- Integration test

Side effects
n/a

### Release note 
- No release note.

### CODE REVIEW

File: session/session_test.go [hunk 1]
```diff
@@ -2800,13 +2800,21 @@ func (s *testSessionSuite3) TestEnablePartition(c *C) {
...
 	tk.MustQuery("show variables like 'tidb_enable_list_partition'").Check(testkit.Rows("tidb_enable_list_partition ON"))
 
 	tk.MustExec("set tidb_enable_list_partition=on")
 	tk.MustQuery("show variables like 'tidb_enable_list_partition'").Check(testkit.Rows("tidb_enable_list_partition ON"))
 
+	tk.MustQuery("show global variables like 'tidb_enable_list_partition'").Check(testkit.Rows("tidb_enable_list_partition ON"))
+	tk.MustExec("set global tidb_enable_list_partition=off")
+	tk.MustQuery("show global variables like 'tidb_enable_list_partition'").Check(testkit.Rows("tidb_enable_list_partition OFF"))
+	tk.MustQuery("show variables like 'tidb_enable_list_partition'").Check(testkit.Rows("tidb_enable_list_partition ON"))
+
```
Comment (morgo) [inline session/session_test.go:2817]: It looks like we have some of these tests in `executor/set_test.go` and some in `session/session_test.go`. I think that's probably fine though, since it's an existing case just expanded.

File: sessionctx/variable/sysvar.go [hunk 2]
```diff
@@ -1128,7 +1128,7 @@ var defaultSysVars = []*SysVar{
 		s.EnableTablePartition = val
 		return nil
 	}},
-	{Scope: ScopeSession, Name: TiDBEnableListTablePartition, Value: Off, Type: TypeBool, skipInit: true, SetSession: func(s *SessionVars, val string) error {
+	{Scope: ScopeGlobal | ScopeSession, Name: TiDBEnableListTablePartition, Value: Off, Type: TypeBool, skipInit: true, SetSession: func(s *SessionVars, val string) error {
```
Comment (morgo) [inline sessionctx/variable/sysvar.go:1131]: This has `skipInit` set because when I developed this feature I just copied the existing behavior. Because you are adding a global scope now, I don't think this is intentional:

What `skipInit` does is avoids calling the `SetSession` function when the variables are copied to an initial session. This means that `s.EnableListTablePartition` will only be what the default value was, and does not correctly inherit the global value.

Comment (morgo) [reply sessionctx/variable/sysvar.go:1131]: Here is the original PR if you want to follow it: https://github.com/pingcap/tidb/pull/24836

Comment (mjonss) [reply sessionctx/variable/sysvar.go]: I removed it, but not sure I completely understood the meaning of `skipInit` since I tried both true and false without affecting the extended test case (i.e. a new session would always be correctly copied from the global variable) but I did not dig deeper than that.

**Review by morgo — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by qw4990** [comment]
Should we pick it to v5.1?

**Comment by mjonss** [comment]
> Should we pick it to v5.1?

Yes, I think so. Good catch!

**Review by bb7133 — APPROVED** [review]
