### PR TITLE
executor: fix query hang when sorted column is constant

### LINKED ISSUE #55344: Query is stuck after disabling some optimization rules
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
INSERT INTO mysql.opt_rule_blacklist VALUES("predicate_push_down"),("column_prune");
ADMIN reload opt_rule_blacklist; 
CREATE DATABASE database1;
USE database1;
CREATE TABLE t0(c0 BOOL);
SELECT t0.c0 FROM t0 WHERE 0 ORDER BY -646041453 ASC;
```

### 2. What did you expect to see? (Required)

Query executed successfully.

### 3. What did you see instead (Required)

Query was stuck.

### 4. What is your TiDB version? (Required)

```sql
Release Version: v8.3.0-alpha-50-gb59f5ecb47-dirty
Edition: Community
Git Commit Hash: b59f5ecb472d831f867b079e0a409caef9f4a290
Git Branch: master
UTC Build Time: 2024-07-31 18:41:32
GoVersion: go1.22.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #55344

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that parallel sort may be stuck when sorted column is constant
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/executor/sortexec/parallel_sort_spill_test.go [hunk 1]
```diff
@@ -143,3 +144,16 @@ func TestParallelSortSpillDiskFailpoint(t *testing.T) {
...
 }
+
+func TestIssue55344(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t;")
+	tk.MustExec("CREATE TABLE t0(c0 BOOL);")
+	tk.MustExec("INSERT INTO mysql.opt_rule_blacklist VALUES('predicate_push_down'),('column_prune');")
+	tk.MustExec("ADMIN reload opt_rule_blacklist;")
```
Comment (windtalker) [inline pkg/executor/sortexec/parallel_sort_spill_test.go:155]: I think the `opt_rule_blacklist` should be reset back after the tests

File: pkg/executor/sortexec/sort.go [hunk 2]
```diff
@@ -766,7 +786,11 @@ func (e *SortExec) initCompareFuncs(ctx expression.EvalContext) error {
 func (e *SortExec) buildKeyColumns() {
 	e.keyColumns = make([]int, 0, len(e.ByItems))
 	for _, by := range e.ByItems {
-		col := by.Expr.(*expression.Column)
+		col, ok := by.Expr.(*expression.Column)
```
Comment (windtalker) [inline pkg/executor/sortexec/sort.go:789]: 1. what about other expression, for example the function expression?
2. you should add some correctness tests for constant columns in the byItems

File: pkg/executor/sortexec/sort.go [hunk 3]
```diff
@@ -260,6 +266,7 @@ func (e *SortExec) Next(ctx context.Context, req *chunk.Chunk) error {
 	if e.fetched.CompareAndSwap(false, true) {
 		err := e.initCompareFuncs(e.Ctx().GetExprCtx().GetEvalCtx())
 		if err != nil {
+			e.closeChannels()
```
Comment (windtalker) [inline pkg/executor/sortexec/sort.go:269]: When `e.fetchChunks` return error, don't need to close channels explicitly?

Comment (xzhangxian1008) [reply pkg/executor/sortexec/sort.go:270]: > When `e.fetchChunks` return error, don't need to close channels explicitly?

Yes, because these channels have been closed in the `e.fetchChunks`.

File: pkg/executor/sortexec/parallel_sort_spill_test.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_spill_test.go:155]: > I think the `opt_rule_blacklist` should be reset back after the tests

okk

File: pkg/executor/sortexec/sort.go (hunk 2 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/sort.go]: > 1. what about other expression, for example the function expression?
> 2. you should add some correctness tests for constant columns in the byItems

done

File: pkg/executor/sortexec/sort.go [hunk 4]
```diff
@@ -763,12 +788,18 @@ func (e *SortExec) initCompareFuncs(ctx expression.EvalContext) error {
...
-func (e *SortExec) buildKeyColumns() {
+func (e *SortExec) buildKeyColumns() error {
 	e.keyColumns = make([]int, 0, len(e.ByItems))
 	for _, by := range e.ByItems {
-		col := by.Expr.(*expression.Column)
-		e.keyColumns = append(e.keyColumns, col.Index)
+		switch col := by.Expr.(type) {
+		case *expression.Column:
+			e.keyColumns = append(e.keyColumns, col.Index)
+		case *expression.Constant:
```
Comment (windtalker) [inline pkg/executor/sortexec/sort.go:797]: add some comment here to explain why constant don't need to add to keyColumns

File: pkg/executor/sortexec/parallel_sort_spill_test.go [hunk 5]
```diff
@@ -143,3 +144,19 @@ func TestParallelSortSpillDiskFailpoint(t *testing.T) {
...
+
+	// Should not be panic
+	tk.MustQuery("SELECT t0.c0 FROM t0 WHERE 0 ORDER BY -646041453 ASC;")
+
+	tk.MustExec("delete from mysql.opt_rule_blacklist;")
```
Comment (windtalker) [inline pkg/executor/sortexec/parallel_sort_spill_test.go:160]: should only delete `predicate_pushd_down` and `column_prune`

File: pkg/executor/sortexec/sort.go [hunk 6]
```diff
@@ -260,10 +267,15 @@ func (e *SortExec) Next(ctx context.Context, req *chunk.Chunk) error {
 	if e.fetched.CompareAndSwap(false, true) {
 		err := e.initCompareFuncs(e.Ctx().GetExprCtx().GetEvalCtx())
 		if err != nil {
+			e.closeChannels()
 			return err
 		}
 
-		e.buildKeyColumns()
+		err = e.buildKeyColumns()
```
Comment (windtalker) [inline pkg/executor/sortexec/sort.go:274]: will topN has similar issue？

File: pkg/executor/sortexec/sort.go [hunk 7]
```diff
@@ -96,6 +97,13 @@ type SortExec struct {
 	enableTmpStorageOnOOM bool
 }
 
+// When fetcher and workers are not created, we need to initiatively close these channels
+func (e *SortExec) closeChannels() {
+	close(e.Parallel.resultChannel)
+	close(e.Parallel.chunkChannel)
+	close(e.Parallel.closeSync)
```
Comment (windtalker) [inline pkg/executor/sortexec/sort.go:104]: why add this line here, does it means there is another bug?

File: pkg/executor/sortexec/sort.go (hunk 6 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/sort.go:274]: > will topN has similar issue？

yes

File: pkg/executor/sortexec/parallel_sort_spill_test.go (hunk 5 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_spill_test.go:160]: > should only delete `predicate_pushd_down` and `column_prune`

done

File: pkg/executor/sortexec/sort.go (hunk 4 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/sort.go:797]: > add some comment here to explain why constant don't need to add to keyColumns

done

File: pkg/executor/sortexec/sort.go (hunk 7 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/sort.go:104]: > why add this line here, does it means there is another bug?

We will wait for the `closeSync` only when `fetched` flag is set, so it's the same bug with the current issue.

File: pkg/executor/sortexec/sort.go (hunk 6 above)
Comment (windtalker) [reply pkg/executor/sortexec/sort.go:274]: Why topN will not hang

File: pkg/executor/sortexec/parallel_sort_spill_test.go [hunk 8]
```diff
@@ -143,3 +144,19 @@ func TestParallelSortSpillDiskFailpoint(t *testing.T) {
...
+	tk.MustExec("drop table if exists t;")
+	tk.MustExec("CREATE TABLE t0(c0 BOOL);")
+	tk.MustExec("INSERT INTO mysql.opt_rule_blacklist VALUES('predicate_push_down'),('column_prune');")
+	tk.MustExec("ADMIN reload opt_rule_blacklist;")
+
+	// Should not be panic
+	tk.MustQuery("SELECT t0.c0 FROM t0 WHERE 0 ORDER BY -646041453 ASC;")
+
+	tk.MustExec("delete from mysql.opt_rule_blacklist where name='column_prune' or name='predicate_push_down';")
+	tk.MustExec("ADMIN reload opt_rule_blacklist;")
```
[the remark this answers is not in the document]
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_spill_test.go]: > Looks like there is still no correctness tests

done

File: pkg/executor/sortexec/parallel_sort_test.go [hunk 9]
```diff
@@ -142,3 +145,49 @@ func TestFailpoint(t *testing.T) {
...
+	insertSql := fmt.Sprintf("INSERT INTO t1 values (%d)", insertedValues[0])
+	for i := 1; i < valueNum; i++ {
+		insertSql = fmt.Sprintf("%s, (%d)", insertSql, insertedValues[i])
+	}
+	insertSql += ";"
+
+	tk.MustExec(insertSql)
+	sort.Ints(insertedValues)
+
+	result := tk.MustQuery("select c from t1 order by c, -646041453;")
```
Comment (windtalker) [inline pkg/executor/sortexec/parallel_sort_test.go:181]: add some more tests like 
`order by -646041453, c`
`order by c, -646041453, c+1`
`order by c+1,-646041453,c`

Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_test.go]: > add some more tests like `order by -646041453, c` `order by c, -646041453, c+1` `order by c+1,-646041453,c`

done

**Review by windtalker — APPROVED** [review]
LGTM
