### PR TITLE
session: make tidb_replica_read work correctly (#20386)

### LINKED ISSUE #20392: sessionvar `tidb_replica_read` doesn't work as expected
### 1. Minimal reproduce step (Required)
1. set the session variable `tidb_replica_read` to `leader-and-follower`
2. run some queries

### 2. What did you expect to see? (Required)
Coprocessor (or point get) tasks should be sent to both leader and follower replicas

### 3. What did you see instead (Required)
Tasks are only sent to follower replicas

### 4. What is your TiDB version? (Required)
master branch

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20386 to release-4.0

---

Signed-off-by: qupeng <qupeng@pingcap.com>

Close #20392 .

### What problem does this PR solve?

tidb_replica_read session variable can't work correctly in some situations:
* Value `leader-and-follower` makes same effect as `follower`, which is not expected

### What is changed and how it works?

* Use correct `ReplicaReadType` when get rpc context

### Check List 

Tests 

- Unit test

Side effects

### Release note 
* make session var tidb_replica_read work correctly

### CODE REVIEW

File: store/tikv/region_request.go [hunk 1]
```diff
@@ -242,18 +264,22 @@ func (s *RegionRequestSender) SendReqCtx(
 		}
 	})
 
+<<<<<<< HEAD
```
Comment (lzmhhh123) [inline store/tikv/region_request.go:267]: @hicqu Please resolve the conflicts

**Comment by lysu** [comment]
LGTM

**Review by zz-jason — APPROVED** [review]
LGTM
