### PR TITLE
domain, util/replayer: increase GC duration for plan replayer capture file to 7 days

### LINKED ISSUE #43663: plan replayer capture file's GC time is too short for the user
## Bug Report

Currently, the plan replayer zip file's GC time is 1 hour.

However, for plan replayer capture task, this is too short. The user will easily miss the captured result.

We need to increase it for a better user experience.

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #43663 

### What is changed and how it works?

- For plan replayer capture file without historical stats enabled, name it "capture_normal_replayer_XXX.zip".
- As title says, increase  GC duration for plan relayer capture file to 7 days

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: util/replayer/replayer.go [hunk 1]
```diff
@@ -15,14 +15,15 @@
 package replayer
 
 import (
+	"crypto/rand"
 	"encoding/base64"
 	"fmt"
-	"math/rand"
```
Comment (time-and-fate) [inline util/replayer/replayer.go:20]: Golang doc says `crypto/rand` is more appropriate for almost all use cases.
https://pkg.go.dev/math/rand#Read

**Review by xuyifangreeneyes — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
