### PR TITLE
executor: fix schema-table inconsistent issue in `IS.tables`

### LINKED ISSUE #60593: SELECT `infoschema`.`tables` data is inconsistent, schema and table name do not match.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop database if exists test1;
create database test1;
use test1;
create table t10(id int);
create table t11 like t10;
create table t12 like t10;
create table t13 like t10;
create table t14 like t10;
create table t15 like t10;
create table t16 like t10;
create table t17 like t10;
create table t18 like t10;
create table t19 like t10;

drop database if exists test2;
create database test2;
use test2;
create table t20(id int);
create table t21 like t20;
create table t22 like t20;
create table t23 like t20;
create table t24 like t20;
create table t25 like t20;
create table t26 like t20;
create table t27 like t20;
create table t28 like t20;
create table t29 like t20;

SELECT table_schema, table_name,data_length
FROM information_schema.TABLES
WHERE (TABLE_NAME IN ('t10','t11','t12','t13','t14','t15','t16','t17','t18','t19','t20','t21','t22','t23','t24','t25','t26','t27','t28','t29'));
```
### 2. What did you expect to see? (Required)
```sql
mysql> SELECT table_schema, table_name,data_length FROM information_schema.TABLES WHERE (TABLE_NAME IN ('t10','t11','t12','t13','t14','t15','t16','t17','t18','t19','t20','t21','t22','t23','t24','t25','t26','t27','t28','t29')) order by table_name;
+--------------+------------+-------------+
| table_schema | table_name | data_length |
+--------------+------------+-------------+
| test1        | t10        |           0 |
| test1        | t11        |           0 |
| test1        | t12        |           0 |
| test1        | t13        |           0 |
| test1        | t14        |           0 |
| test1        | t15        |           0 |
| test1        | t16        |           0 |
| test1        | t17        |           0 |
| test1        | t18        |           0 |
| test1        | t19        |           0 |
| test2        | t20        |           0 |
| test2        | t21        |           0 |
| test2        | t22        |           0 |
| test2        | t23        |           0 |
| test2        | t24        |           0 |
| test2        | t25        |           0 |
| test2        | t26        |           0 |
| test2        | t27        |           0 |
| test2        | t28        |           0 |
| test2        | t29        |           0 |
+--------------+------------+-------------+
20 rows in set (0.01 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> SELECT table_schema, table_name,data_length FROM information_schema.TABLES WHERE (TABLE_NAME IN ('t10','t11','t12','t13','t14','t15','t16','t17','t18','t19','t20','t21','t22','t23','t24','t25','t26','t27','t28','t29'));
+--------------+------------+-------------+
| table_schema | table_name | data_length |
+--------------+------------+-------------+
| test1        | t10        |           0 |
| test1        | t11        |           0 |
| test1        | t14        |           0 |
| test1        | t15        |           0 |
| test1        | t17        |           0 |
| test1        | t20        |           0 |
| test1        | t22        |           0 |
| test1        | t23        |           0 |
| test1        | t24        |           0 |
| test1        | t26        |           0 |
| test2        | t25        |           0 |
| test2        | t12        |           0 |
| test2        | t13        |           0 |
| test2        | t16        |           0 |
| test2        | t18        |           0 |
| test2        | t19        |           0 |
| test2        | t21        |           0 |
| test2        | t27        |           0 |
| test2        | t28        |           0 |
| test2        | t29        |           0 |
+--------------+------------+-------------+
20 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

v8.5.0, master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #60593

Problem Summary:

Previous sorting impl is problematic.

### What changed and how does it work?

The original code mistakenly swapped the elements of `tableSlice` manually during sorting, causing it to be out of sync with `schemaSlice`. By merging the data and sorting them uniformly, the order consistency of the two is ensured, eliminating the data misalignment problem caused by manual swapping.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/planner/core/memtable_infoschema_extractor.go [hunk 1]
```diff
@@ -689,24 +689,21 @@ func findTableAndSchemaByName(
...
 			}
-			tableMap[tblInfo.ID] = schemaAndTable{s, tblInfo}
+			schemaAndTbls = append(schemaAndTbls, schemaAndTable{s, tblInfo})
 		}
 	}
-	schemaSlice := make([]ast.CIStr, 0, len(tableMap))
-	tableSlice := make([]*model.TableInfo, 0, len(tableMap))
-	for _, st := range tableMap {
+
+	sort.Slice(schemaAndTbls, func(i, j int) bool {
```
Comment (hawkingrei) [inline pkg/planner/core/memtable_infoschema_extractor.go:696]: We can use slices.SortFunc to avoid boundary check by golang runtime

**Review by River2000i — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
