### PR TITLE
executor: fix hashjoin goleak

### LINKED ISSUE #39026: Hashjoin goroutine leak
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
make failpoint-enable
cd executor
go test -run TestRandomPanicConsume -race -v
```

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Issue Number: close #39026

Problem Summary: `fetchAndBuildHashTable` leaked even after `rs.Close()`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
make failpoint-enable
go test -run TestRandomPanicConsume -race -v
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/join.go [hunk 1]
```diff
@@ -92,9 +93,7 @@ type HashJoinExec struct {
 	prepared    bool
 	isOuterJoin bool
 
-	// joinWorkerWaitGroup is for sync multiple join workers.
-	joinWorkerWaitGroup sync.WaitGroup
-	finished            atomic.Value
+	finished atomic.Value
```
Comment (hawkingrei) [inline executor/join.go:96]: In go1.19, We have [atomic.Bool](https://pkg.go.dev/sync/atomic#Bool)

File: executor/join.go [hunk 2]
```diff
@@ -70,6 +69,8 @@ type HashJoinExec struct {
 
 	// closeCh add a lock for closing executor.
 	closeCh      chan struct{}
+	worker       util.WaitGroupWrapper
+	waiter       util.WaitGroupWrapper
```
Comment (xhebox) [inline executor/join.go:73]: `waitJoinWorkersAndCloseResultChan` will call `worker.Wait()`, but it is running in another goroutine. So `waiter` is to prevent leak of `waitJoinWorkersAndCloseResultChan`.

File: util/wait_group_wrapper.go [hunk 3]
```diff
@@ -43,7 +43,7 @@ func (w *WaitGroupWrapper) RunWithRecover(exec func(), recoverFn func(r interfac
 	go func() {
 		defer func() {
 			r := recover()
-			if r != nil && recoverFn != nil {
+			if recoverFn != nil {
```
Comment (xhebox) [inline util/wait_group_wrapper.go:46]: `util.WithRecovery` will always call `recoveryFn`, align with it and hashjoin relies on this behavior.

File: executor/join.go [hunk 4]
```diff
@@ -283,13 +284,13 @@ func (e *HashJoinExec) wait4BuildSide() (emptyBuild bool, err error) {
...
 // to e.buildSideResult.
-func (e *HashJoinExec) fetchBuildSideRows(ctx context.Context, chkCh chan<- *chunk.Chunk, doneCh <-chan struct{}) {
+func (e *HashJoinExec) fetchBuildSideRows(ctx context.Context, chkCh chan<- *chunk.Chunk, errCh chan<- error, doneCh <-chan struct{}) {
 	defer close(chkCh)
 	var err error
 	failpoint.Inject("issue30289", func(val failpoint.Value) {
 		if val.(bool) {
 			err = errors.Errorf("issue30289 build return error")
-			e.buildFinished <- errors.Trace(err)
+			errCh <- errors.Trace(err)
```
Comment (xhebox) [inline executor/join.go:293]: `fetchBuildSideRows` and `fetchAndBuildHashTable` are running in parallel. So `fetchAndBuildHashTable` may close `buildFinished` before `fetchBuildSideRows` is finised.

File: executor/join.go (hunk 1 above)
Comment (xhebox) [reply executor/join.go:96]: Done.

**Review by hawkingrei — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]
