### PR TITLE
br: backup/restore statistic data in the partition dimension

### LINKED ISSUE #49627: oom when backup/restore the statistic if there are many partitions of a table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. snapshot backup/restore

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
oom
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #49627

Problem Summary:
oom when backup/restore the statistic if there are many partitions of a table
### What changed and how does it work?
backup/restore statistic data in the partition dimension
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/metautil/load.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
+// Copyright 2023 PingCAP, Inc.
```
Comment (Leavrth) [inline br/pkg/metautil/load.go:1]: directly move code from `utils/schema.go`.

File: pkg/statistics/handle/storage/stats_read_writer.go [hunk 2]
```diff
@@ -456,6 +457,47 @@ func (s *statsReadWriter) DumpHistoricalStatsBySnapshot(
 	return jsonTbl, fallbackTbls, nil
 }
 
+// DumpStatsTOJSONBySnapshotFunc dumps statistic to json and call the function for each partition statistic.
+// Notice: It might call the function `fn` with nil jsontable.
+func (s *statsReadWriter) DumpStatsToJSONBySnapshotFunc(
```
Comment (hi-rustin) [inline pkg/statistics/handle/storage/stats_read_writer.go:462]: Could you please move this change to a separate PR? This will make it easier for the optimizer team to review.

**Review by hi-rustin — COMMENTED** [review]
Thanks!

File: br/pkg/metautil/statsfile.go [hunk 3]
```diff
@@ -0,0 +1,235 @@
+// Copyright 2023 PingCAP, Inc.
```
Comment (BornChanger) [inline br/pkg/metautil/statsfile.go:1]:
```suggestion
// Copyright 2024 PingCAP, Inc.
```

File: br/pkg/metautil/statsfile.go [hunk 4]
```diff
@@ -0,0 +1,235 @@
...
+	}
+	return nil
+}
+
+func (s *StatsWriter) BackupStatsDone(ctx context.Context) ([]*backuppb.StatsFileIndex, error) {
+	if s.totalSize == 0 || len(s.statsFile.Blocks) == 0 {
+		return s.statsFileIndexes, nil
+	}
+
+	if err := s.writeStatsFileAndClear(ctx, s.statsFile.Blocks[0].PhysicalId); err != nil {
```
Comment (3pointer) [inline br/pkg/metautil/statsfile.go:139]: may be it's ok for now this file name does not duplicated.
what if file name duplicated? is it could happen during backup checkpoint?

File: br/pkg/metautil/statsfile.go [hunk 5]
```diff
@@ -0,0 +1,235 @@
...
+		Name:     fileName,
+		Sha256:   checksum[:],
+		SizeEnc:  uint64(len(encryptedContent)),
+		SizeOri:  uint64(len(content)),
+		CipherIv: iv,
+	})
+
+	// clear the temporary variables
+	s.totalSize = 0
+	s.statsFile = &backuppb.StatsFile{}
```
Comment (3pointer) [inline br/pkg/metautil/statsfile.go:105]: NIT: prefer use a reset function here. and new StatsFile with a fixed length blocks.

File: br/pkg/backup/schema.go [hunk 6]
```diff
@@ -147,7 +148,8 @@ func (ss *Schemas) BackupSchemas(
 					}
 				}
 				if statsHandle != nil {
-					if err := schema.dumpStatsToJSON(statsHandle, backupTS); err != nil {
+					statsWriter := metaWriter.NewStatsWriter()
+					if err := schema.dumpStatsToJSON(ctx, statsWriter, statsHandle, backupTS); err != nil {
```
Comment (BornChanger) [inline br/pkg/backup/schema.go:152]: Should we return the error here?

File: br/pkg/metautil/statsfile.go (hunk 4 above)
Comment (Leavrth) [reply br/pkg/metautil/statsfile.go:139]: use physical id to distinguish files.

**Review by 3pointer — APPROVED** [review]
rest LGTM

**Review by BornChanger — APPROVED** [review]
