### PR TITLE
ddl: fix rollback of adding partition table

### LINKED ISSUE #19317: Meta information was not cleaned up during rollback of "add partition table"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Cancel the "add partition tables" in `StateReplicaOnly`.

### 2. What did you expect to see? (Required)
Cleanup the meta-information.

### 3. What did you see instead (Required)
The meta-information doesn't clean up.

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-985-g172a2d321-dirty
Edition: Community
Git Commit Hash: 172a2d3214b23fbdaa1df396551aeb75124e6bc1
Git Branch: master
```

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close #19317 

Problem Summary:

- Meta information was not cleaned up during rollback of "add partition table".

- `TestCancelAddTableAndDropTablePartition` didn't really run.

### What is changed and how it works?

How it Works:

- Update table info when rollback "add partition table".

- Update `TestCancelAddTableAndDropTablePartition`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

-

### CODE REVIEW

**Review by AilinKid — COMMENTED** [review]
LGTM

File: ddl/partition.go [hunk 1]
```diff
@@ -884,10 +884,11 @@ func onDropTablePartition(t *meta.Meta, job *model.Job) (ver int64, _ error) {
 			return ver, errors.Trace(err)
 		}
 		physicalTableIDs = removePartitionInfo(tblInfo, partNames)
-		ver, err = updateVersionAndTableInfo(t, job, tblInfo, true)
-		if err != nil {
-			return ver, errors.Trace(err)
-		}
+	}
+
+	ver, err = updateVersionAndTableInfo(t, job, tblInfo, true)
```
Comment (AilinKid) [inline ddl/partition.go:889]: good catch

**Review by djshow832 — COMMENTED** [review]
Please resolve conflicts first.

**Comment by zimulala** [comment]
PTAL @djshow832

**Review by djshow832 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
