### PR TITLE
stats: optimize memory footprint of pseudo stats table

### LINKED ISSUE #60137: planner: prevent pseudo-stats from dominating the Stats Cache
## Enhancement
Use the python script below to reproduce this problem:
```
for i in range(100000):
    print(f"CREATE TEMPORARY TABLE tmp_{i} (id BIGINT(20) NOT NULL,INDEX id_idx(id));")
    print(f"select * from tmp_{i};")
    print(f"DROP TEMPORARY TABLE tmp_{i};")
```

In this case:
1.  create and drop a lots of temporary tables;
2. when accessing these tables, we create a pseudo-stats for each table, and put it into the stats cache;
3. we don't drop stats from the stats cache when dropping a table;
4. if this situation continues, a large number of unused pseudo-stats will dominate the stats cache and cause unexpected high memory usage.

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #60137

Problem Summary:

### What changed and how does it work?

A significant part of memory consumption of pseudo table is creating new chunk for every pseudo table creation. These new chunks are read only and only to provide compatibility to the code of using real stats table struct. We can make it a static object and shared by all pseudo tables to reduce memory usage.
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Tristan1900** [comment]
Not ready to review, trying to see what tests does it break

File: pkg/statistics/histogram.go [hunk 1]
```diff
@@ -53,6 +53,12 @@ const (
 	outOfRangeBetweenRate float64 = 100
 )
 
+var (
+	// Global static chunk for pseudo histograms to avoid chunk allocation
+	globalPseudoChunkOnce sync.Once
+	globalPseudoChunk     *chunk.Chunk
+)
+
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/statistics/histogram.go:61]: sync.Once.Do is thread safe, it's the canonical Go pattern for lazy initialization

File: pkg/statistics/histogram.go [hunk 2]
```diff
@@ -115,6 +121,42 @@ type scalar struct {
 // EmptyScalarSize is the size of empty scalar.
 const EmptyScalarSize = int64(unsafe.Sizeof(scalar{}))
 
+// initGlobalPseudoChunk initializes the global static chunk for pseudo histograms
+func initGlobalPseudoChunk() {
+	// Create a minimal empty chunk that can be shared across all pseudo histograms
+	// Use a basic field type that won't cause issues when shared
+	globalPseudoChunk = chunk.NewEmptyChunk([]*types.FieldType{types.NewFieldType(mysql.TypeBlob)})
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/statistics/histogram.go:128]: it's inherited from the previous version

File: pkg/statistics/table.go [hunk 3]
```diff
@@ -1017,23 +1017,39 @@ func (coll *HistColl) GenerateHistCollFromColumnInfo(tblInfo *model.TableInfo, c
...
+		HistColl:              PseudoHistColl(tblInfo.ID, allowTriggerLoading),
+		Version:               PseudoVersion,
 		ColAndIdxExistenceMap: NewColAndIndexExistenceMap(len(tblInfo.Columns), len(tblInfo.Indices)),
 	}
+
+	// Initialize columns and indices maps only when allowFillHistMeta is true
+	if allowFillHistMeta {
+		t.columns = make(map[int64]*Column, len(tblInfo.Columns))
+		t.indices = make(map[int64]*Index, len(tblInfo.Indices))
+	}
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply pkg/statistics/table.go:1103]: the loop is conditional...

File: pkg/statistics/table.go [hunk 4]
```diff
@@ -1017,23 +1017,39 @@ func (coll *HistColl) GenerateHistCollFromColumnInfo(tblInfo *model.TableInfo, c
...
 // PseudoTable creates a pseudo table statistics.
 // Usually, we don't want to trigger stats loading for pseudo table.
 // But there are exceptional cases. In such cases, we should pass allowTriggerLoading as true.
 // Such case could possibly happen in getStatsTable().
 func PseudoTable(tblInfo *model.TableInfo, allowTriggerLoading bool, allowFillHistMeta bool) *Table {
-	pseudoHistColl := HistColl{
-		RealtimeCount:     PseudoRowCount,
-		PhysicalID:        tblInfo.ID,
-		columns:           make(map[int64]*Column, 2),
-		indices:           make(map[int64]*Index, 2),
```
Comment (0xPoe) [inline pkg/statistics/table.go:1081]: So these two maps have actually never been accessed, right?

Comment (0xPoe) [reply pkg/statistics/table.go:1081]: Oh, I found the allowFillHistMeta flag.

File: pkg/statistics/table.go [hunk 5]
```diff
@@ -1017,23 +1017,39 @@ func (coll *HistColl) GenerateHistCollFromColumnInfo(tblInfo *model.TableInfo, c
...
-	}
 	t := &Table{
-		HistColl:              pseudoHistColl,
+		HistColl:              PseudoHistColl(tblInfo.ID, allowTriggerLoading),
+		Version:               PseudoVersion,
 		ColAndIdxExistenceMap: NewColAndIndexExistenceMap(len(tblInfo.Columns), len(tblInfo.Indices)),
 	}
+
+	// Initialize columns and indices maps only when allowFillHistMeta is true
+	if allowFillHistMeta {
```
Comment (0xPoe) [inline pkg/statistics/table.go:1100]: 👍🏼

File: pkg/statistics/histogram.go [hunk 6]
```diff
@@ -115,6 +121,42 @@ type scalar struct {
...
+}
+
+// NewPseudoHistogram creates a pseudo histogram that reuses global static components
+// This avoids chunk allocation while preserving field type semantics.
+func NewPseudoHistogram(id int64, tp *types.FieldType) *Histogram {
+	if tp.EvalType() == types.ETString {
+		// Same as NewHistogram
+		tp = tp.Clone()
+		tp.SetCollate(charset.CollationBin)
+	}
```
Comment (0xPoe) [inline pkg/statistics/histogram.go]: Do you think it is reasonable to extract this logic into a function and use it in NewHistogram as well, to avoid missing any changes or causing inconsistencies in future updates?

**Comment by 0xPoe** [comment]
Also, it would be great if you could include the actual test results from the test environment in the PR body.

**Comment by Tristan1900** [comment]
Not eliminating the pseudo table memory cost, only reduced some of it. The rest part is kind of difficult and risky to refactor.

Previously

image

after

image

**Comment by 0xPoe** [comment]
@Tristan1900 There are some conflicts that need to be resolved.
