### PR TITLE
*: unifiy the usage of max_execution_time

### LINKED ISSUE #64360: max_execution_time should only take affect on select sql
## Bug Report

Please answer these questions before submitting your issue. Thanks!
According to mysql's doc, max_execution_time only works for select sql, in TiDB, it try to align this behavior, however, there is still some corner cases which max_execution_time affect non select sql, for example, in #56923, it tries to set context's timeout using `max_execution_time`, so rpc can be aware of `max_execution_time`, but it actually does not check `InSelectStmt`, which means a non select sql will be affected by this pr.

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #64360

Problem Summary:
Described in #64360
### What changed and how does it work?
* check `InSelectStmt` in `GetMaxExecutionTime()`
* replace all the usage of `vars.MaxExecutionTime` by `vars.GetMaxExecutionTime()` during sql execution
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/batch_point_get.go [hunk 1]
```diff
@@ -237,10 +237,10 @@ func (e *BatchPointGetExec) initialize(ctx context.Context) error {
 	var indexKeys []kv.Key
 	var err error
 	batchGetter := e.batchGetter
-	if e.Ctx().GetSessionVars().MaxExecutionTime > 0 {
```
Comment (windtalker) [inline pkg/executor/batch_point_get.go:240]: @HaoW30 please take a look, in your pr #56923, the MaxExecutionTime will be set even for non-select sql, which is not expected because MaxExecutionTime should only take affects for select query: https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_max_execution_time

File: pkg/sessionctx/variable/session.go [hunk 2]
```diff
@@ -3556,7 +3556,12 @@ func (s *SessionVars) GetRuntimeFilterMode() RuntimeFilterMode {
 }
 
 // GetMaxExecutionTime get the max execution timeout value.
```
Comment (zimulala) [inline pkg/sessionctx/variable/session.go]: Do we need to explicitly mention “for SELECT statements”, similar to the [MaxExecutionTime](https://github.com/pingcap/tidb/blob/069a5086efd3a47ca0e7906e87b50a3716e18e0d/pkg/sessionctx/variable/session.go#L1224C37-L1224C57) definition?

Comment (windtalker) [reply pkg/sessionctx/variable/session.go]: ok

**Review by zimulala — APPROVED** [review]

**Review by you06 — APPROVED** [review]
