### PR TITLE
planner: align point-update assignment casting

### LINKED ISSUE #63455: Incompatibility Between TiDB and MySQL When Updating `BIGINT UNSIGNED` With Negative Values
## Description

When updating a `BIGINT UNSIGNED` column with a negative value, TiDB produces different results compared to MySQL. Specifically, TiDB converts `-1` into the maximum unsigned value (`18446744073709551615`), while MySQL silently coerces it to `0`. This behavior difference may cause compatibility issues for applications expecting MySQL semantics.

### TiDB
```sql
set sql_mode='';

CREATE TABLE foo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bing BIGINT UNSIGNED DEFAULT NULL
);

INSERT INTO foo (id, bing) VALUES
    (1, -1),
    (2, 1),
    (3, NULL),
    (4, NULL);

UPDATE foo SET bing=-1 WHERE id=3;
UPDATE foo SET bing=1 WHERE id=4;

SELECT * FROM foo;
```

**Output:**
```
+----+----------------------+
| id | bing                 |
+----+----------------------+
|  1 |                    0 |
|  2 |                    1 |
|  3 | 18446744073709551615 |
|  4 |                    1 |
+----+----------------------+
```

### MySQL
```sql
set sql_mode='';

CREATE TABLE foo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bing BIGINT UNSIGNED DEFAULT NULL
);

INSERT INTO foo (id, bing) VALUES
    (1, -1),
    (2, 1),
    (3, NULL),
    (4, NULL);

UPDATE foo SET bing=-1 WHERE id=3;
UPDATE foo SET bing=1 WHERE id=4;

SELECT * FROM foo;
```

**Output:**
```
+----+------+
| id | bing |
+----+------+
|  1 |    0 |
|  2 |    1 |
|  3 |    0 |
|  4 |    1 |
+----+------+
```

## Expected Behavior

TiDB should align with MySQL behavior, coercing negative values assigned to an `UNSIGNED` column into `0`, rather than wrapping around to the maximum unsigned integer value.

## Actual Behavior

- **TiDB**: `-1` is stored as `18446744073709551615`  
- **MySQL**: `-1` is coerced into `0`

## Impact

Applications depending on MySQL behavior may experience incorrect query results or unexpected values when negative integers are inserted or updated into `BIGINT UNSIGNED` columns.

## Environment

- TiDB version: [8.0.11-TiDB-v8.5.0]
- MySQL version: [8.0.40]

## Additional Notes

This issue likely stems from differences in how TiDB handles type coercion and overflow for unsigned integer types compared to MySQL.

### LINKED ISSUE #67534: planner: point-update fast path still diverges from normal UPDATE for unsigned decimal/real and set integer assignments
### 1. Minimal reproduce step (Required)

While checking PR #67212 locally, I found that the point-update fast path still diverges from the normal `UPDATE` path in more cases than the original `bigint unsigned` example from #63455.

The general repro pattern is:
1. Use a subquery on the RHS to force the normal `UPDATE` path.
2. Compare it with the direct constant assignment that takes the point-update fast path.

Example 1: `decimal(10,0) unsigned`
```sql
create table foo (id int primary key, bing decimal(10, 0) unsigned default null);
insert into foo values (1, 1), (2, null);

-- normal UPDATE path
update foo set bing = (select -1) where id = 2;

-- point-update fast path
update foo set bing = -1 where id = 2;
```

Example 2: `double unsigned`
```sql
create table foo (id int primary key, bing double unsigned default null);
insert into foo values (1, 1), (2, null);

-- normal UPDATE path
update foo set bing = (select -1) where id = 2;

-- point-update fast path
update foo set bing = -1 where id = 2;
```

Example 3: `set('1','2','3')`
```sql
create table foo (id int primary key, bing set('1','2','3') default null);
insert into foo values (1, null), (2, null);

-- normal UPDATE path
update foo set bing = (select 3) where id = 1;

-- point-update fast path
update foo set bing = 3 where id = 2;

select id, bing + 0, bing from foo order by id;
```

### 2. What did you expect to see? (Required)

The point-update fast path should have the same assignment semantics as the normal `UPDATE` path.

For the examples above:
- `decimal unsigned` / `double unsigned`: both paths should report the same out-of-range behavior for `-1`.
- `set('1','2','3')`: both rows should end up with the same value after assigning `3`.

### 3. What did you see instead (Required)

Before the local fix:
- `decimal(10,0) unsigned`: the normal path returned `ErrWarnDataOutOfRange`, but the fast path took a different planner-side cast path. In my local run this showed up as `1264` vs `1690`.
- `double unsigned`: same root cause as unsigned decimal / real; planner-side `CAST` does not match `UPDATE` assignment conversion semantics.
- `set('1','2','3')`: the direct integer assignment could lose the enum/set-as-int behavior in the fast path.

This looks like a broader follow-up to #63455: the issue is not limited to `unsigned integer` targets.

### 4. What is your TiDB version? (Required)

Observed on current master while validating PR #67212 locally:
- commit: `be402c585d0db8cf7abad7820bd5f262b5cb8155`

I have not yet reproduced this against a released binary with `SELECT tidb_version()`.

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #63455, close #67534

Problem Summary:
- Point-update fast path builds assignment expressions in the planner and injects an implicit `CAST`, which can be constant-folded during planning.
- For unsigned numeric targets (int/decimal/real), `CAST` semantics can wrap negative constants (e.g. `-1`) via `uint64` conversion, diverging from normal `UPDATE` assignment casting (`table.CastValue`) under default `sql_mode`.
- For `SET` columns with integer assignments, planner-side casting can turn an integer into a string and lose the set-as-int (bitmask) interpretation, so the fast path and normal path produce different stored values.

### What changed and how does it work?
- Keep the implicit `CAST` for most target column types so the fast path stays aligned with normal `UPDATE` typing, but **do not inject planner-side CAST** for unsigned numeric targets (int/decimal/real). Let the executor perform assignment casting via `table.CastValue` with the proper statement context and `sql_mode`.
- For `ENUM/SET` targets with an integer RHS, add `EnumSetAsIntFlag` on the target type so the fast path preserves the integer interpretation consistently with the normal update path.
- Add regression tests covering negative-to-unsigned assignments for bigint/decimal/double and integer assignments to `SET`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix point-update fast path to follow UPDATE assignment semantics for unsigned numeric targets and SET integer assignments.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Negative values can no longer wrap into unsigned columns during UPDATE; assignments to unsigned integer, decimal, and real columns now fail with an out-of-range error consistently across execution paths.
  * Integer assignments to SET columns behave consistently and store expected values.

* **Tests**
  * Added regression tests covering negative-to-unsigned UPDATEs and integer assignments to SET columns (both direct and via subquery).

### CODE REVIEW

**Review by themavik — COMMENTED** [review]
buildOrderedList skips BuildCastFunction on the point-update path so unsigned columns get table.CastValue behavior and -1 now raises ErrWarnDataOutOfRange like the non-fast path. The planner_issue_test guard for #63455 is tight.

**Review by wshwsh12 — APPROVED** [review]
LGTM.

File: pkg/planner/core/point_get_plan.go [hunk 1]
```diff
@@ -1280,7 +1280,13 @@ func buildOrderedList(ctx base.PlanContext, plan base.Plan, list []*ast.Assignme
 		if castToTP.GetType() == mysql.TypeEnum && assign.Expr.GetType().EvalType() == types.ETInt {
 			castToTP.AddFlag(mysql.EnumSetAsIntFlag)
 		}
-		expr = expression.BuildCastFunction(ctx.GetExprCtx(), expr, castToTP)
+		// For unsigned integer columns, avoid wrapping assignment expressions with an implicit CAST.
+		// CAST semantics would wrap negative numbers to UINT64_MAX, while UPDATE assignments should
+		// follow assignment semantics (clip to 0 / overflow error depending on sql_mode). Let the
+		// executor handle conversion via table.CastValue.
```
Comment (winoros) [inline pkg/planner/core/point_get_plan.go]: This comment reads a bit broader than the actual behavior. Maybe make the point-update-specific scope explicit:

```suggestion
		// Point-update builds assignment expressions directly in the planner.
		// Keep the implicit CAST for most target column types so the fast path stays
		// aligned with normal UPDATE typing, but do not CAST unsigned numeric targets:
		// planner-side CAST can apply expression semantics instead of UPDATE assignment
		// semantics, which should be handled later by executor-side table.CastValue
		// under the current statement context and sql_mode.
```

**Review by qw4990 — APPROVED** [review]
