### PR TITLE
executor: fix wrong runtime stats for `ShuffleReceiver`

### LINKED ISSUE #34987: runtime stats for `ShuffleReceiver` is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

dataset: TPC-H 1G
SQL:
```
explain analyze select ps_availqty, row_number() over (partition by ps_suppkey) from partsupp;
```

### 2. What did you expect to see? (Required)

The runtime stats(time, actualRows...) for all operators are correct.

### 3. What did you see instead (Required)

```
> explain analyze select ps_availqty, row_number() over (partition by ps_suppkey) from partsupp;
+---------------------------------+-----------+---------+-----------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------+---------+
| id                              | estRows   | actRows | task      | access object  | execution info                                                                                                                                                                                                                                                                                                       | operator info                                                                                                 | memory   | disk    |
+---------------------------------+-----------+---------+-----------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------+---------+
| Projection_7                    | 800000.00 | 800000  | root      |                | time:857.6ms, loops:784, Concurrency:5                                                                                                                                                                                                                                                                               | tpch1g.partsupp.ps_availqty, Column#8                                                                         | 237.3 KB | N/A     |
| └─Shuffle_12                    | 800000.00 | 800000  | root      |                | time:856.1ms, loops:784, ShuffleConcurrency:5                                                                                                                                                                                                                                                                        | execution info: concurrency:5, data sources:[TableReader_10]                                                  | N/A      | N/A     |
|   └─Window_8                    | 800000.00 | 800000  | root      |                | time:4.24s, loops:788                                                                                                                                                                                                                                                                                                | row_number()->Column#8 over(partition by tpch1g.partsupp.ps_suppkey rows between current row and current row) | N/A      | N/A     |
|     └─Sort_11                   | 800000.00 | 800000  | root      |                | time:3.97s, loops:788                                                                                                                                                                                                                                                                                                | tpch1g.partsupp.ps_suppkey                                                                                    | 2.93 MB  | 0 Bytes |
|       └─ShuffleReceiver_17      | 800000.00 | 0       | root      |                |                                                                                                                                                                                                                                                                                                                      |                                                                                                               | N/A      | N/A     |
|         └─TableReader_10        | 800000.00 | 1600000 | root      |                | time:3.71s, loops:1571, cop_task: {num: 2, max: 550.5ms, min: 284.7ms, avg: 417.6ms, p95: 550.5ms, max_proc_keys: 514747, p95_proc_keys: 514747, tot_proc: 760ms, tot_wait: 3ms, rpc_num: 2, rpc_time: 835.1ms, copr_cache: disabled}                                                                                | data:TableFullScan_9                                                                                          | 12.2 MB  | N/A     |
|           └─TableFullScan_9     | 800000.00 | 800000  | cop[tikv] | table:partsupp | tikv_task:{proc max:441ms, min:239ms, p80:441ms, p95:441ms, iters:790, tasks:2}, scan_detail: {total_process_keys: 800000, total_process_keys_size: 150608990, total_keys: 800002, rocksdb: {delete_skipped_count: 0, key_skipped_count: 800000, block: {cache_hit_count: 2478, read_count: 0, read_byte: 0 Bytes}}} | keep order:false                                                                                              | N/A      | N/A     |
+---------------------------------+-----------+---------+-----------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------+---------+
```

The actual row count and the execution time for `ShuffleReceiver_17` is aggregated to `TableReader_10`.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #34987

Problem Summary: Please see the issue.

### What is changed and how it works?

Before: For one data source, initialize a new physical operator for every shuffle worker.
After: For one data source, initialize only one physical operator and reuse it for every shuffle worker.

This change makes every data source has a single id, and all runtime stats collected for this operator correspond to this id.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/builder.go [hunk 1]
```diff
@@ -4506,26 +4508,34 @@ func (b *executorBuilder) buildShuffle(v *plannercore.PhysicalShuffle) *ShuffleE
...
 		}
 
-		for j, dataSource := range v.DataSources {
-			stub := plannercore.PhysicalShuffleReceiverStub{
-				Receiver:   (unsafe.Pointer)(receivers[j]),
-				DataSource: dataSource,
-			}.Init(b.ctx, dataSource.Stats(), dataSource.SelectBlockOffset(), nil)
-			stub.SetSchema(dataSource.Schema())
+		for j := range v.DataSources {
+			stub := stubs[j]
```
Comment (XuHuaiyu) [inline executor/builder.go:4537]: Do we need to set `stubs[j].Clone` to stub?

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
