### PR TITLE
expression: fix wrong flen from baseFunctionClass

### LINKED ISSUE #56587: TiDB and MySQL behave differently when union `quote(cast('xxxx' as char))` and string literal
### 1. Minimal reproduce step (Required)
```sql
select quote(cast('abcdefg' as char)) union all
select '1' where 0<>0;
```

### 2. What did you expect to see? (Required)
```
mysql> select quote(cast('abcdefg' as char)) union all
    -> select '1' where 0<>0;
+--------------------------------+
| quote(cast('abcdefg' as char)) |
+--------------------------------+
| 'abcdefg'                      |
+--------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select quote(cast('abcdefg' as char)) union all
    -> select '1' where 0<>0;
+--------------------------------+
| quote(cast('abcdefg' as char)) |
+--------------------------------+
| '                              |
+--------------------------------+
1 row in set, 1 warning (0.00 sec)
mysql> show warnings;
+---------+------+----------------------------------------+
| Level   | Code | Message                                |
+---------+------+----------------------------------------+
| Warning | 1406 | Data Too Long, field len 1, data len 9 |
+---------+------+----------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```
Release Version: v8.4.0-alpha-370-gf773b6eeb4
Edition: Community
Git Commit Hash: f773b6eeb4593a3e2c998c265f491a016570a426
Git Branch: HEAD
UTC Build Time: 2024-10-11 02:08:09
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in TiDB that may lead to database logic error.

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #56587

Problem Summary:

### What changed and how does it work?

Previously, `quoteFunctionClass` may return type with flen = 0 when the underlying argument has the `UnspecifiedLength` which equals to -1.

https://github.com/pingcap/tidb/blob/f0b3bf0332ae33b0593f5f89ead872f71816cbd3/pkg/expression/builtin_string.go#L2899

And this type will be passed into `LogicalUnionAll` and a wrong type is deduced.

https://github.com/pingcap/tidb/blob/f0b3bf0332ae33b0593f5f89ead872f71816cbd3/pkg/planner/core/logical_plan_builder.go#L1586-L1591

Some other functions also have this problem, for example:

```mysql
mysql> select elt(2, "123", cast('abcdefg' as char)) union all select "1234";
+----------------------------------------+
| elt(2, "123", cast('abcdefg' as char)) |
+----------------------------------------+
| abcd                                   |
| 1234                                   |
+----------------------------------------+
2 rows in set, 1 warning (0.00 sec)
```

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/builtin_string.go [hunk 1]
```diff
@@ -1604,24 +1604,32 @@ func (c *hexFunctionClass) getFunction(ctx BuildContext, args []Expression) (bui
...
+		bf.tp.SetFlen(types.UnspecifiedLength)
 		if err != nil {
 			return nil, err
 		}
 		argFieldTp := args[0].GetType(ctx.GetEvalCtx())
 		// Use UTF8MB4 as default.
+		if argLen != types.UnspecifiedLength {
+			bf.tp.SetFlen(argLen * 4 * 2)
+		}
 		bf.tp.SetFlen(argFieldTp.GetFlen() * 4 * 2)
```
Comment (windtalker) [inline pkg/expression/builtin_string.go:1620]: This line need to be removed?

File: pkg/expression/builtin_string.go [hunk 2]
```diff
@@ -1604,24 +1604,32 @@ func (c *hexFunctionClass) getFunction(ctx BuildContext, args []Expression) (bui
...
 	switch argTp {
 	case types.ETString, types.ETDatetime, types.ETTimestamp, types.ETDuration, types.ETJson:
 		bf, err := newBaseBuiltinFuncWithTp(ctx, c.funcName, args, types.ETString, types.ETString)
+		bf.tp.SetFlen(types.UnspecifiedLength)
 		if err != nil {
 			return nil, err
 		}
 		argFieldTp := args[0].GetType(ctx.GetEvalCtx())
 		// Use UTF8MB4 as default.
+		if argLen != types.UnspecifiedLength {
```
Comment (windtalker) [inline pkg/expression/builtin_string.go:1617]: I think it's better to use `argFieldTp.GetFlen()` as the `argLen` because inside `newBaseBuiltinFuncWithTp`, args[0] maybe changed by wrap some implict cast function

File: pkg/expression/builtin_string.go [hunk 3]
```diff
@@ -1604,24 +1604,32 @@ func (c *hexFunctionClass) getFunction(ctx BuildContext, args []Expression) (bui
...
 		return sig, nil
 	case types.ETInt, types.ETReal, types.ETDecimal:
 		bf, err := newBaseBuiltinFuncWithTp(ctx, c.funcName, args, types.ETString, types.ETInt)
+		bf.tp.SetFlen(types.UnspecifiedLength)
 		if err != nil {
 			return nil, err
 		}
-		bf.tp.SetFlen(args[0].GetType(ctx.GetEvalCtx()).GetFlen() * 2)
+		if argLen != types.UnspecifiedLength {
+			bf.tp.SetFlen(argLen * 2)
```
Comment (windtalker) [inline pkg/expression/builtin_string.go:1631]: Ditto, better to use `argFieldTp.GetFlen()` as the `argLen`

**Review by windtalker — APPROVED** [review]
lgtm

**Review by yibin87 — APPROVED** [review]
LGTM
