### PR TITLE
ddl: fix invalid index on multi-layer virtual columns

### LINKED ISSUE #11139: should fill index data after adding an index on a virtual generated column
## 1. What did you do?

All the following operations are executed on a tidb-server built from https://github.com/pingcap/tidb/pull/10802

```sql
drop table if exists t;
create table t(a bigint, b bigint as (a+1) virtual, c bigint as (b+1) virtual);
alter table t add index idx_b(b);
alter table t add index idx_c(c);
insert into t(a) values(1);
alter table t add column(d bigint as (c+1) virtual);
```

The query below can produce a correct result:
```sql
TiDB(root@127.0.0.1:test) > select * from t where d > 2;
+------+------+------+------+
| a    | b    | c    | d    |
+------+------+------+------+
|    1 |    2 |    3 |    4 |
+------+------+------+------+
1 row in set (0.00 sec)
```

Then create an index on the newly added column `d`:
```sql
alter table t add index idx_d(d);
```

And run the query again, the result is incorrect:
```sql
TiDB(root@127.0.0.1:test) > select * from t where d > 2;
Empty set (0.00 sec)
```

The execution plan now is changed to:
```sql
TiDB(root@127.0.0.1:test) > desc select * from t where d > 2;
+----------------------+-------+------+----------------------------------------------------------------------------------------------------------------------------------+
| id                   | count | task | operator info                                                                                                                    |
+----------------------+-------+------+----------------------------------------------------------------------------------------------------------------------------------+
| Projection_11        | 0.33  | root | test.t.a, cast(plus(test.t.a, 1)), cast(plus(cast(plus(test.t.a, 1)), 1)), cast(plus(cast(plus(cast(plus(test.t.a, 1)), 1)), 1)) |
| └─IndexLookUp_12     | 0.33  | root |                                                                                                                                  |
|   ├─IndexScan_9      | 0.33  | cop  | table:t, index:d, range:(2,+inf], keep order:false, stats:pseudo                                                                 |
|   └─TableScan_10     | 0.33  | cop  | table:t, keep order:false, stats:pseudo                                                                                          |
+----------------------+-------+------+----------------------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

## 2. What did you expect to see?

produce the correct result

## 3. What did you see instead?

As I mentioned above, it produces no result.

## 4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```sql
TiDB(root@127.0.0.1:test) > select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-rc.1-314-gca686bba7
Git Commit Hash: ca686bba759ea6127fae70746abba5437f6c7e42
Git Branch: pr/10802
UTC Build Time: 2019-07-09 02:44:55
GoVersion: go version go1.12.5 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 

Fix #11139.

### What is changed and how it works?

When a generated column depends on another generated column, like `c -> b -> a`, the old implementation fails to backfill the existing row data when creating an index on `c`.

In `makeupDecodeColMap()`, a `decodeColMap` is used to save the information about a column, containing 
`column id -> table.column & generated expression`. 
In index-value-backfill period, `decodeColMap` can be used to fetch row values.

For example,
```sql
drop table if exists t;
create table t (a int, b int as (a + 1), c int as (b + 1));
insert into t (a) values (1);
create index idx on t (c);
```
When creating an index on `c`, the old implementation of `makeupDecodeColMap()` builds a `decodeColMap` like 

| column ID | table.Column, GenExpr |
| --------- | --------------------- |
| 3         | c, b + 1              |
| 2         | b, nil                |

without considering whether b is a generated column.

In this PR, to build a `decodeColMap`, below three steps is needed:

1. Build a "full" map that contains all the columns mentioned in an index, including directly and indirectly depended columns.
2. Substitute generated `expression.Column` in map with another expression, until no generated column in GenExpr field of every value in map.
3. Delete all unused columns in the map. Here the "unused" means virtual and not included in indexed columns.

Step2 substitute generated columns in a columnID-ascending order, ensuring that no unresolved generated column exists.

The map building process in the above example:
Step 1,

| column ID | table.Column, GenExpr |
| --------- | --------------------- |
| 3         | c, b + 1              |
| 2         | b, a + 1              |
| 1         | a, nil                |

Step 2,

| column ID | table.Column, GenExpr |
| --------- | --------------------- |
| 3         | c, (a + 1) + 1        |
| 2         | b, (a + 1)            |
| 1         | a, nil                |

Step 3,

| column ID | table.Column, GenExpr |
| --------- | --------------------- |
| 3         | c, (a + 1) + 1              |
| 1         | a, nil                |

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes
 - Has exported function/method change

Side effects

 - Possible performance regression

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: util/rowDecoder/decoder.go [hunk 1]
```diff
@@ -14,6 +14,8 @@
 package decoder
 
 import (
+	"github.com/pingcap/parser/ast"
```
Comment (crazycs520) [inline util/rowDecoder/decoder.go]: Please put this line in the right place.

**Comment by tangenta** [comment]
@crazycs520 @bb7133 @zimulala PTAL~

**Comment by bb7133** [comment]
Excellent PR description! @tangenta

File: util/rowDecoder/decoder.go [hunk 2]
```diff
@@ -134,3 +136,74 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle int
...
+// with non-generated one by looking up decodeColMap.
+func SubstituteGenColsInDecodeColMap(decodeColMap map[int64]Column) {
+	// Sort columns by ID in ascending order.
+	var orderedCols []int64
+	for colID := range decodeColMap {
+		orderedCols = append(orderedCols, colID)
+	}
+	sort.Slice(orderedCols, func(i, j int) bool { return orderedCols[i] < orderedCols[j] })
+
+	// Iterate over decodeColMap, substitution only happens once because
```
Comment (bb7133) [inline util/rowDecoder/decoder.go]:
```suggestion
	// Iterate over decodeColMap, the substitution only happens once because
```

File: util/rowDecoder/decoder.go [hunk 3]
```diff
@@ -134,3 +136,74 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle int
...
+	// the column with smaller columnID can not refer to those with larger.
```
Comment (bb7133) [inline util/rowDecoder/decoder.go]:
```suggestion
	// columns with smaller columnID can not refer to those with larger ones.
```

File: util/rowDecoder/decoder.go [hunk 4]
```diff
@@ -134,3 +136,74 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle int
 	}
 	return row, nil
 }
+
+// SubstituteGenColsInDecodeColMap substitutes generated columns in every expression in decodeColMap
```
Comment (bb7133) [inline util/rowDecoder/decoder.go]:
```suggestion
// SubstituteGenColsInDecodeColMap substitutes generated columns in every expression 
```
This comment sounds really weird, maybe removing `in decodeColMap` is just better

File: ddl/db_integration_test.go [hunk 5]
```diff
@@ -797,6 +797,36 @@ func (s *testIntegrationSuite5) TestModifyingColumnOption(c *C) {
...
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t (a int, b int as (a + 1), c int as (b + 1))")
+	tk.MustExec("insert into t (a) values (1)")
+	tk.MustExec("create index idx on t (c)")
+	tk.MustQuery("select * from t where c > 1").Check(testkit.Rows("1 2 3"))
+	tk.MustExec("admin check table t")
+
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t (a int, b int as (a + 1), c int as (b + 1), d int as (c + 1))")
```
Comment (bb7133) [inline ddl/db_integration_test.go]: Please try to add some cases with more complicated expressions and dependencies, for example

`a int, b decimal as (a + 1), c varchar(20) as (b * 2), d float as SOME_NESTED_EXPRESSIONS_WITH(b and c)`

File: util/rowDecoder/decoder.go [hunk 6]
```diff
@@ -134,3 +136,74 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle int
...
+// substituteGeneratedColumn substitutes generated columns in an expression with non-generated one by looking up decodeColMap.
+func substituteGeneratedColumn(expr expression.Expression, decodeColMap map[int64]Column) expression.Expression {
+	switch v := expr.(type) {
+	case *expression.Column:
+		if c, ok := decodeColMap[v.ID]; ok && c.GenExpr != nil {
+			return c.GenExpr
+		}
+		return v
+	case *expression.ScalarFunction:
+		if v.FuncName.L == ast.Cast {
```
Comment (bb7133) [inline util/rowDecoder/decoder.go]: Why do we handle `CAST` in this special way? I don't get the point from `expression.ColumnSubstitute`, neither from here.

File: util/rowDecoder/decoder.go [hunk 7]
```diff
@@ -134,3 +136,74 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle int
...
+	for colID, decCol := range decodeColMap {
+		col := decCol.Col
+		if !col.IsGenerated() || col.GeneratedStored {
+			continue
+		}
+
+		found := false
+		for _, v := range indexedCols {
+			if v.Offset == col.Offset {
+				found = true
```
Comment (bb7133) [inline util/rowDecoder/decoder.go]:
```suggestion
				found = true
				break
```

File: util/rowDecoder/decoder.go [hunk 8]
```diff
@@ -134,3 +136,74 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle int
 	}
 	return row, nil
 }
+
+// SubstituteGenColsInDecodeColMap substitutes generated columns in every expression in decodeColMap
+// with non-generated one by looking up decodeColMap.
+func SubstituteGenColsInDecodeColMap(decodeColMap map[int64]Column) {
+	// Sort columns by ID in ascending order.
```
Comment (crazycs520) [inline util/rowDecoder/decoder.go]: Please Add comment why you need sort here. I think you have an assumption here.

Comment (tangenta) [reply util/rowDecoder/decoder.go]: @crazycs520 I think line 150 does explain it. Do you have any suggestions?

File: util/rowDecoder/decoder.go (hunk 6 above)
Comment (tangenta) [reply util/rowDecoder/decoder.go]: Actually, I am not sure. The removal of them did NOT fail the integration test.

File: ddl/db_integration_test.go (hunk 5 above)
Comment (tangenta) [reply ddl/db_integration_test.go]: @bb7133 Updated. PTAL

File: util/rowDecoder/decoder.go (hunk 8 above)
Comment (bb7133) [reply util/rowDecoder/decoder.go]: The reason is here: (https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html)

```
A generated column definition can refer to other generated columns, but only those occurring earlier in the table definition. A generated column definition can refer to any base (nongenerated) column in the table whether its definition occurs earlier or later.
```
Is it possible that the order of column ID is not the order of columns shown in the table definition? Using column ID is a bit risky here. @crazycs520 @tangenta

Comment (tangenta) [reply util/rowDecoder/decoder.go]: @bb7133 You are right. I have found a test case that violates this assumption. I think 
 sorting by `table.Column.Offset` is the correct choice.

Comment (bb7133) [reply util/rowDecoder/decoder.go]: > @bb7133 You are right. I have found a test case that violates this assumption. I think
> sorting by `table.Column.Offset` is the correct choice.

Good job, would you please show the case here?

Comment (tangenta) [reply util/rowDecoder/decoder.go]:
```sql
create table t (a int, c int as (a + 1));
insert into t (a) value (1);
alter table t add column b int as (a + 1) after a;
alter table t modify column c int as (b + 1);
alter table t add index idx(c);
```
Here the ID of column `a`, `b` and `c` is `1`, `3` and `2` respectively.

File: ddl/index.go [hunk 9]
```diff
@@ -908,27 +908,48 @@ func (w *addIndexWorker) run(d *ddlCtx) {
...
-		tpExpr := decoder.Column{
-			Col: col,
-		}
+	indexedCols := make([]*table.Column, len(indexInfo.Columns))
+	for i, v := range indexInfo.Columns {
+		indexedCols[i] = cols[v.Offset]
+	}
+
+	indexedColsCpy := make([]*table.Column, len(indexedCols))
+	copy(indexedColsCpy, indexedCols)
```
Comment (winkyao) [inline ddl/index.go]: Could you add some comment here, explain why we need a copied indexCols?

Comment (tangenta) [reply ddl/index.go]: @winkyao Because `buildFullDecodeColMap()` will modify it. Fine, let's move this logic into `buildFullDecodeColMap()` for better readability.

File: util/rowDecoder/decoder.go (hunk 8 above)
Comment (crazycs520) [reply util/rowDecoder/decoder.go]: It looks like you need fix bug:https://github.com/pingcap/tidb/issues/11365 first.

File: ddl/index.go [hunk 10]
```diff
@@ -908,27 +908,48 @@ func (w *addIndexWorker) run(d *ddlCtx) {
...
+func buildFullDecodeColMap(indexedCols []*table.Column, sessCtx sessionctx.Context, t table.Table) (map[int64]decoder.Column, error) {
+	pendingCols := make([]*table.Column, len(indexedCols))
+	copy(pendingCols, indexedCols)
+	decodeColMap := make(map[int64]decoder.Column, len(pendingCols))
+	for i := 0; i < len(pendingCols); i++ {
+		col := pendingCols[i]
 		if col.IsGenerated() && !col.GeneratedStored {
-			for _, c := range cols {
+			// Find depended columns and put them into pendingCols.
+			for _, c := range t.Cols() {
```
Comment (winkyao) [inline ddl/index.go]: You'd better add some explaining here, you can give some examples.

File: util/rowDecoder/decoder.go [hunk 11]
```diff
@@ -134,3 +135,75 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle int
...
+		colID     int64
+		colOffset int
+	}
+	var orderedCols []Pair
+	for colID, col := range decodeColMap {
+		orderedCols = append(orderedCols, Pair{colID, col.Col.Offset})
+	}
+	sort.Slice(orderedCols, func(i, j int) bool { return orderedCols[i].colOffset < orderedCols[j].colOffset })
+
+	// Iterate over decodeColMap, the substitution only happens once because
```
Comment (winkyao) [inline util/rowDecoder/decoder.go]: I can't understand these comments, please add more explain

File: ddl/db_integration_test.go [hunk 12]
```diff
@@ -797,6 +797,57 @@ func (s *testIntegrationSuite5) TestModifyingColumnOption(c *C) {
...
+	tk.MustExec("admin check table t")
+
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t(a bigint, b bigint as (a+1) virtual, c bigint as (b+1) virtual)")
+	tk.MustExec("alter table t add index idx_b(b)")
+	tk.MustExec("alter table t add index idx_c(c)")
+	tk.MustExec("insert into t(a) values(1)")
+	tk.MustExec("alter table t add column(d bigint as (c+1) virtual)")
+	tk.MustExec("alter table t add index idx_d(d)")
+	tk.MustQuery("select * from t where d > 2").Check(testkit.Rows("1 2 3 4"))
```
Comment (winkyao) [inline ddl/db_integration_test.go]: why not use `force index` and `ignore index` to check the result is expected？

Comment (tangenta) [reply ddl/db_integration_test.go]: Updated. PTAL :)

**Comment by qw4990** [comment]
@tangenta Please fix the CI problem.

**Comment by tangenta** [comment]
```
[2019-07-24T02:56:21.102Z] ----------------------------------------------------------------------
[2019-07-24T02:56:21.102Z] FAIL: builtin_time_test.go:1222: testEvaluatorSuite.TestCurrentTime
[2019-07-24T02:56:21.102Z] 
[2019-07-24T02:56:21.102Z] builtin_time_test.go:1242:
[2019-07-24T02:56:21.102Z]     c.Assert(n.String(), GreaterEqual, last.Format(tfStr))
[2019-07-24T02:56:21.102Z] ... compare_one string = "10:56:15.950"
[2019-07-24T02:56:21.102Z] ... compare_two string = "10:56:16"
```
/run-unit-test
