### PR TITLE
ddl: update the reorg range after delay for async txn

### LINKED ISSUE #38165: Admin check failed after creating index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Change the TiDB config:

```
[tikv-client.async-commit]
safe-window = "3s"
allowed-clock-drift = "0.2s"
```

Mock the network latency:

```diff
@@ -1888,6 +1890,12 @@ func (c *twoPhaseCommitter) calculateMaxCommitTS(ctx context.Context) error {
                return err
        }
 
+       if counter.Load()%2 == 0 {
+               logutil.BgLogger().Info("calculate max commit ts, sleep 2s...")
+               time.Sleep(2 * time.Second)
+       }
+       counter.Add(1)
+
        safeWindow := config.GetGlobalConfig().TiKVClient.AsyncCommit.SafeWindow
        maxCommitTS := oracle.ComposeTS(int64(safeWindow/time.Millisecond), 0) + currentTS
```

```sql
-- session 1
create table t (a int);
insert into t values (1);
-- session 1 calculate max commit ts, sleep 2s...
-- session 2
alter table t add index idx(a);
admin check table t;
```

### 2. What did you expect to see? (Required)

```sql
tidb> admin check table t;
Query OK, 0 rows affected (0.01 sec)
```

### 3. What did you see instead (Required)

```sql
tidb> admin check table t;
ERROR 8223 (HY000): data inconsistency in table: t, index: idx, handle: 1, index-values:"" != record-values:"handle: 1, values: [KindInt64 1]"
```

### 4. What is your TiDB version? (Required)

63e3570

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #38165

Problem Summary:

Previously, `reorgInfo` is initialized in `getReorgInfo()`, which happens before `delayForAsyncCommit()`. However, the reorg range may change after the delay(for example, an async commit transaction inserts a record). As a result, the backfill transaction does not add the corresponding index record.

### What is changed and how it works?

This PR moves the reorg info range initialization after `delayForAsyncCommit`. It makes sure no async transactions are active.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  It is not easy to write the unit test because client-go is involved. I follow the steps described in issue, the problem does not occur anymore.
  ```
  ["[ddl] split table range from PD"] [physicalTableID=169] [startHandle=1] [endHandle=1]
  ```
  ```
  -- session 1
  mysql> alter table t add index idx(a);
  Query OK, 0 rows affected (3.86 sec)
  mysql> admin check table t;
  Query OK, 0 rows affected (0.00 sec)
  -- session 2
  mysql> insert into t values (1);
  Query OK, 1 row affected (2.01 sec)
  ```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the data inconsistent issue after creating index.
```

### CODE REVIEW

File: ddl/reorg.go [hunk 1]
```diff
@@ -213,6 +213,7 @@ func (w *worker) runReorgJob(rh *reorgHandler, reorgInfo *reorgInfo, tblInfo *mo
 		if job.IsCancelling() {
 			return dbterror.ErrCancelledDDLJob
 		}
+		tryToUpdateRealReorgRange(rh, reorgInfo, tbl)
```
Comment (zimulala) [inline ddl/reorg.go:216]: Could we move the logic of [line635](https://github.com/pingcap/tidb/pull/38195/files#diff-51926b25b437247805c6880b2fd041f096575b30050b560ab934f1d863bb6bf6R635)-[line678](https://github.com/pingcap/tidb/pull/38195/files#diff-51926b25b437247805c6880b2fd041f096575b30050b560ab934f1d863bb6bf6R678) here? Then we needn't do twice this logic.

Comment (tangenta) [reply ddl/reorg.go:216]: Then we have to change `reorgInfo.first` related code. Let's keep it in this PR.

File: ddl/reorg.go [hunk 2]
```diff
@@ -291,6 +292,43 @@ func (w *worker) runReorgJob(rh *reorgHandler, reorgInfo *reorgInfo, tblInfo *mo
...
 }
 
+// tryToUpdateRealReorgRange updates the reorg info range by the existing records.
+func tryToUpdateRealReorgRange(rh *reorgHandler, reorgInfo *reorgInfo, tbl table.Table) {
+	job, pid, elem, dCtx := reorgInfo.Job, reorgInfo.PhysicalTableID, reorgInfo.currElement, reorgInfo.d
+	var start, end kv.Key
+	if reorgInfo.mergingTmpIdx {
+		start, end = tablecodec.GetTableIndexKeyRange(pid, tablecodec.TempIndexPrefix|elem.ID)
+	} else {
+		currentVer, err := getValidCurrentVersion(dCtx.store)
```
Comment (zimulala) [inline ddl/reorg.go:302]: It seems that the `currentVer` value is changed. Before this PR, the version is got when `region.first` is true. Maybe we can use `job.SnapshotVer`?

Comment (tangenta) [reply ddl/reorg.go:302]: If we use `job.SnapshotVer`, we cannot get the latest data.

Comment (zimulala) [reply ddl/reorg.go:302]: Indeed, it went back. 
But if not, does it feel like whether it is "first" doesn't make much of a difference?

Comment (zimulala) [reply ddl/reorg.go:302]: OK~

**Review by zimulala — COMMENTED** [review]
LGTM

**Review by zimulala — APPROVED** [review]

File: ddl/stat_test.go [hunk 3]
```diff
@@ -89,7 +89,7 @@ func TestDDLStatsInfo(t *testing.T) {
 			varMap, err := d.Stats(nil)
 			wg.Done()
 			require.NoError(t, err)
-			require.Equal(t, "1", varMap[ddlJobReorgHandle])
+			require.Equal(t, "", varMap[ddlJobReorgHandle])
```
Comment (xiongjiwei) [inline ddl/stat_test.go:92]: why the test is changed

Comment (tangenta) [reply ddl/stat_test.go:92]: Because the channel `ddl.TestCheckWorkerNumCh` is send, the transaction that updating `ddl_job_reorg_handle` is not committed.

**Review by xiongjiwei — APPROVED** [review]

**Comment by hawkingrei** [comment]
In the Cloud CI，check_2 only have 8 core cpu to run this test case. it maybe an reason。

**Review by xiongjiwei — APPROVED** [review]

File: ddl/reorg.go [hunk 4]
```diff
@@ -608,7 +602,9 @@ func getReorgInfo(ctx *JobContext, d *ddlCtx, rh *reorgHandler, job *model.Job,
 		})
 
 		info.first = true
-		// get the current version for reorganization if we don't have
+		if d.lease > 0 { // Only delay when it's not in test.
+			delayForAsyncCommit()
+		}
 		ver, err := getValidCurrentVersion(d.store)
```
Comment (hawkingrei) [inline ddl/reorg.go:608]: There are the same codes. I think it can be merged into a single function.
```
info.first = true
...
ver, err := getValidCurrentVersion(d.store)
```

Comment (tangenta) [reply ddl/reorg.go:608]: Frankly speaking, `getReorgInfoFromPartitions` should reuse `getReorgInfo` since they are quite similar. Please note that `getReorgInfoFromPartitions` is only used by the global index feature, which is experimental, unstable, and lacks maintenance.

We need to discuss how to handle this piece of code properly.

Comment (hawkingrei) [reply ddl/reorg.go:608]: OK, it may be improved after GA the global index feature.

**Review by hawkingrei — APPROVED** [review]
