### PR TITLE
expression: after introducing collation, the experssion should be thread-safe

### LINKED ISSUE #15810: GROUP BY clause nondeterministically results in an incorrect result or error
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT, c1 INT);
CREATE TABLE t1(c0 INT, c1 INT);
CREATE TABLE t2(c0 INT, c1 INT );
INSERT INTO t1(c0) VALUES (8, 58), (19, 79);
INSERT INTO t1 VALUES (22, 19), (91, 69);
INSERT INTO t0 VALUES (29, 5), (11, NULL);
INSERT INTO t1 VALUES (NULL, 60), (0, 49), (23, NULL);
INSERT INTO t1(c1, c0) VALUES (58, 33), (11, 82);
INSERT INTO t1 VALUES (18, 65), (33, 10), (31, 13), (98, 30);
INSERT INTO t1(c0, c1) VALUES (NULL, 8), (17, 99), (70, 63), (22, 28);
INSERT INTO t2(c0, c1) VALUES (90, NULL), (88, 89), (11, 26);
INSERT INTO t0 VALUES (75, 68);
INSERT INTO t0(c0, c1) VALUES (54, 19);
INSERT INTO t1 VALUES (14, 53);
INSERT INTO t1 VALUES (72, NULL);
INSERT INTO t0 VALUES (29, 94), (48, 3);
INSERT INTO t0(c0, c1) VALUES (29, 9), (66, 39);
INSERT INTO t2 VALUES (92, 75);
INSERT INTO t2(c1) VALUES (23), (67);
INSERT INTO t1 VALUES (69, NULL), (NULL, 78);
INSERT INTO t0(c0) VALUES (71), (59);
INSERT INTO t2 VALUES (97, 8), (92, 45);
INSERT INTO t1 VALUES (37, 57), (46, 89);
INSERT INTO t1(c1) VALUES (51);
INSERT INTO t0 VALUES (24, 70), (14, 87);
INSERT INTO t2 VALUES (33, NULL), (77, 68);
INSERT INTO t1 VALUES (48, 44);
INSERT INTO t2(c0, c1) VALUES (56, 51), (80, NULL), (NULL, 27);
INSERT INTO t0(c0) VALUES (88), (90), (58);
INSERT INTO t2 VALUES (43, 16);
ANALYZE TABLE t1, t2;
SELECT t1.c0 LIKE t1.c0 FROM t1, t2, t0 GROUP BY t1.c0 LIKE t1.c0; -- non-deterministic result or "runtime error: index out of range [1] with length 1"
```

The `SELECT` sometimes produces an incorrect result or results in an error. Here are examples for outputs that I can reproduce locally:
```
mysql> SELECT t1.c0 LIKE t1.c0 FROM t1, t2, t0 GROUP BY t1.c0 LIKE t1.c0;
+------------------+
| t1.c0 LIKE t1.c0 |
+------------------+
|                1 |
|             NULL |
|                1 |
+------------------+
3 rows in set (0.01 sec)

mysql> SELECT t1.c0 LIKE t1.c0 FROM t1, t2, t0 GROUP BY t1.c0 LIKE t1.c0;
+------------------+
| t1.c0 LIKE t1.c0 |
+------------------+
|                1 |
|             NULL |
+------------------+
2 rows in set (0.00 sec)

mysql> SELECT t1.c0 LIKE t1.c0 FROM t1, t2, t0 GROUP BY t1.c0 LIKE t1.c0;
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
```
The first result set is incorrect, since `1` is contained twice. The second one seems to be correct, but in the third case, an error is caused. `tidb-server` logs the following error:
```
[2020/03/29 15:56:29.536 +02:00] [ERROR] [projection.go:443] ["projection executor panicked"] [error="runtime error: index out of range [1] with length 1"] [stack="goroutine 94351 [running]:\ngithub.com/pingcap/tidb/util.GetStack(...)\n\t/tidb/util/misc.go:72\ngithub.com/pingcap/tidb/executor.recoveryProjection(0xc00803c2e0, 0x27b3940, 0xc000d081a0)\n\t/tidb/executor/projection.go:442 +0x90\ngithub.com/pingcap/tidb/executor.(*projectionWorker).run.func1(0xc008906f88, 0xc0076c2280)\n\t/tidb/executor/projection.go:409 +0x70\npanic(0x27b3940, 0xc000d081a0)\n\t/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/util/stringutil.DoMatch(0xc00794a56c, 0x2, 0xc0029c7270, 0x2, 0x1, 0xc00247be7f, 0x1, 0x1, 0x2)\n\t/tidb/util/stringutil/string_util.go:243 +0xfb\ngithub.com/pingcap/tidb/util/collate.(*binPattern).DoMatch(0xc0078aefc0, 0xc00794a56c, 0x2, 0x5c)\n\t/tidb/util/collate/bin.go:69 +0x6f\ngithub.com/pingcap/tidb/expression.(*builtinLikeSig).vecEvalInt(0xc006729ec0, 0xc007690c80, 0xc00765aa10, 0x0, 0x0)\n\t/tidb/expression/builtin_like_vec.go:68 +0x6f9\ngithub.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt(0xc0076a2f50, 0x2d045a0, 0xc004fea500, 0xc007690c80, 0xc00765aa10, 0x8, 0x8)\n\t/tidb/expression/scalar_function.go:51 +0x4b\ngithub.com/pingcap/tidb/expression.evalOneVec(0x2d045a0, 0xc004fea500, 0x2d33380, 0xc0076a2f50, 0xc007690c80, 0xc007690cd0, 0x1, 0xc00118bef0, 0x226f3b3)\n\t/tidb/expression/chunk_executor.go:123 +0x459\ngithub.com/pingcap/tidb/expression.(*defaultEvaluator).run(0xc0067ad440, 0x2d045a0, 0xc004fea500, 0xc007690c80, 0xc007690cd0, 0x0, 0x0)\n\t/tidb/expression/evaluator.go:51 +0x3be\ngithub.com/pingcap/tidb/expression.(*EvaluatorSuite).Run(0xc00781e960, 0x2d045a0, 0xc004fea500, 0xc007690c80, 0xc007690cd0, 0xc0074f29c0, 0xc00118bfb8)\n\t/tidb/expression/evaluator.go:123 +0xc9\ngithub.com/pingcap/tidb/executor.(*projectionWorker).run(0xc0076c2280, 0x2ccbee0, 0xc007155dd0)\n\t/tidb/executor/projection.go:426 +0x17b\ncreated by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare\n\t/tidb/executor/projection.go:267 +0x7ac\n"]
```
Environment:
```
mysql> SELECT tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-75-ga6de0e38d-dirty
Git Commit Hash: a6de0e38d49c97671d316590c8c945eb518ca2b2
Git Branch: master
UTC Build Time: 2020-03-26 12:11:33
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #16156: index out of range [0] with length 0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Run `/run-integration-copr-test` CI unstable.

### 2. What did you expect to see?

Test pass.

### 3. What did you see instead?

[2020-04-08T03:39:23.387Z] 2020/04/08 11:39:23 2020/04/08 11:39:19 Test fail: Outputs are not matching.

```
[2020-04-08T03:39:23.387Z] 2020/04/08 11:39:23 2020/04/08 11:39:19 Test fail: Outputs are not matching.
[2020-04-08T03:39:23.387Z] Test case: sql/randgen-topn/3_compare_1.sql
[2020-04-08T03:39:23.387Z] Statement: #819 -  SELECT STRCMP( '23:10:42.007765', `col_bigint_unsigned` ) AS field1, `col_varbinary_32` NOT LIKE `col_set` AS field2, `col_tinyint_unsigned_key` IS FALSE AS field3, ( INTERVAL( `col_bit`, ( INTERVAL( '2018-04-26 10:38:03.031949', `col_char_2`, NULL ) ), `col_varchar_1_key` ) ) NOT BETWEEN NULL AND NULL AS field4, COALESCE( '2018-04-27', -26901, ( `col_float_unsigned_key` <=> ( `col_float_unsigned_key` > 'pcbqbfmwpebbkyfsxemhlybhtahsdfttztbnrqjpdtwjharagadcroqtxlefjrhcokdymxvanwfvayfdbhtoxwppiavhgmizbrrxgafhbcxkosudjiyckygmuatynejcqwwbclkmfhgrrenyxlyawqekkchtjzebuphvkwswxbtqsjokzalmxfaklbeukgslyqnrheytuhbqsbseiojnyxesmnsdfyyisxjoljtdmdxwycmyxfnxnojmst' ) ), `col_binary_8_key`, `col_char_255` ) AS field5 FROM `table1000_int_autoinc` WHERE COALESCE( `col_blob`, '2030-01-04', `col_decimal_key` ) ORDER BY field1, field2, field3, field4, field5 LIMIT 3 /* QNO 824 CON_ID 112 */ ;
[2020-04-08T03:39:23.387Z] NoPushDown Output: 
[2020-04-08T03:39:23.387Z] Error 1105: runtime error: index out of range [0] with length 0
[2020-04-08T03:39:23.387Z] 
[2020-04-08T03:39:23.387Z] WithPushDown Output: 
[2020-04-08T03:39:23.387Z] field1	field2	field3	field4	field5
[2020-04-08T03:39:23.388Z] NULL	NULL	0	NULL	2018-04-27
[2020-04-08T03:39:23.388Z] NULL	NULL	0	NULL	2018-04-27
[2020-04-08T03:39:23.388Z] NULL	NULL	0	NULL	2018-04-27
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

https://github.com/pingcap/tidb/pull/15540

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #15810 , close #16156
Problem Summary: the like function is not thread-safe, this results in unstable errors.

@bb7133 @qw4990 can this problem occur in other expression fuctions?

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
like in projection, filter and others using expressions, the expression instance in the operator may be used by multi-tread. It should let the expression evaluation be thread-safe. 

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 
- let like functions be thread-safe

### CODE REVIEW

**Comment by SunRunAway** [comment]
Could you help describe when `builtinLikeSig.evalInt` would be in concurrent state?

File: expression/builtin_like_test.go [hunk 1]
```diff
@@ -36,13 +36,17 @@ func (s *testEvaluatorSuite) TestLike(c *C) {
...
+		go func() {
+			for _, tt := range tests {
+				fc := funcs[ast.Like]
+				f, err := fc.getFunction(s.ctx, s.datumsToConstants(types.MakeDatums(tt.input, tt.pattern, 0)))
+				c.Assert(err, IsNil)
+				r, err := evalBuiltinFunc(f, chunk.Row{})
+				c.Assert(err, IsNil)
+				c.Assert(r, testutil.DatumEquals, types.NewDatum(tt.match))
+			}
+		}()
```
Comment (SunRunAway) [inline expression/builtin_like_test.go:49]: The test should wait for all goroutines done with their works.
You may use `sync.WaitGroup`.

File: expression/builtin_like_vec_test.go [hunk 2]
```diff
@@ -33,7 +33,11 @@ var vecBuiltinLikeCases = map[string][]vecExprBenchCase{
 }
 
 func (s *testEvaluatorSuite) TestVectorizedBuiltinLikeFunc(c *C) {
-	testVectorizedBuiltinFunc(c, vecBuiltinLikeCases)
+	for i := 0; i < 10; i++ {
+		go func() {
+			testVectorizedBuiltinFunc(c, vecBuiltinLikeCases)
+		}()
```
Comment (SunRunAway) [inline expression/builtin_like_vec_test.go:39]: ditto.

**Comment by fzhedu** [comment]
> Could you help describe when `builtinLikeSig.evalInt` would be in concurrent state?

added above.

File: planner/core/rule_predicate_push_down.go [hunk 3]
```diff
@@ -316,10 +316,6 @@ func simplifyOuterJoin(p *LogicalJoin, predicates []expression.Expression) {
 	// then simplify embedding outer join.
 	canBeSimplified := false
 	for _, expr := range predicates {
-		// avoid the case where the expr only refers to the schema of outerTable
-		if expression.ExprFromSchema(expr, outerTable.Schema()) {
-			continue
-		}
```
Comment (SunRunAway) [inline planner/core/rule_predicate_push_down.go:322]: Is this change related to this PR?

File: expression/builtin_like_test.go (hunk 1 above)
Comment (fzhedu) [reply expression/builtin_like_test.go:54]: added

File: expression/builtin_like_test.go [hunk 4]
```diff
@@ -36,14 +37,23 @@ func (s *testEvaluatorSuite) TestLike(c *C) {
...
+		go func() {
+			for _, tt := range tests {
+				fc := funcs[ast.Like]
+				f, err := fc.getFunction(s.ctx, s.datumsToConstants(types.MakeDatums(tt.input, tt.pattern, 0)))
+				c.Assert(err, IsNil)
+				r, err := evalBuiltinFunc(f, chunk.Row{})
+				c.Assert(err, IsNil)
+				c.Assert(r, testutil.DatumEquals, types.NewDatum(tt.match))
+			}
+			defer wg.Done()
```
Comment (SunRunAway) [inline expression/builtin_like_test.go:53]: this line should be the first line of this goroutine function.

File: expression/builtin_like_test.go [hunk 5]
```diff
@@ -21,6 +21,7 @@ import (
 	"github.com/pingcap/tidb/util/chunk"
 	"github.com/pingcap/tidb/util/collate"
 	"github.com/pingcap/tidb/util/testutil"
+	"sync"
```
Comment (SunRunAway) [inline expression/builtin_like_test.go:24]: Please group the standard library and the third-party library.

File: expression/builtin_like_test.go [hunk 6]
```diff
@@ -36,14 +37,23 @@ func (s *testEvaluatorSuite) TestLike(c *C) {
...
+	wg := sync.WaitGroup{}
+	concurrency := 10
+	wg.Add(concurrency)
+	for i := 0; i < concurrency; i++ {
+		go func() {
+			for _, tt := range tests {
+				fc := funcs[ast.Like]
+				f, err := fc.getFunction(s.ctx, s.datumsToConstants(types.MakeDatums(tt.input, tt.pattern, 0)))
+				c.Assert(err, IsNil)
+				r, err := evalBuiltinFunc(f, chunk.Row{})
```
Comment (SunRunAway) [inline expression/builtin_like_test.go:49]: Better to add a test for vecEvalInt

File: expression/builtin_like_test.go (hunk 4 above)
Comment (fzhedu) [reply expression/builtin_like_test.go:53]: ok

File: expression/builtin_like_test.go (hunk 5 above)
Comment (fzhedu) [reply expression/builtin_like_test.go:24]: ok

File: expression/builtin_like_test.go (hunk 6 above)
Comment (fzhedu) [reply expression/builtin_like_test.go:51]: changed original single thread model to multi-thread

File: expression/builtin_like_test.go [hunk 7]
```diff
@@ -36,14 +38,23 @@ func (s *testEvaluatorSuite) TestLike(c *C) {
...
-		c.Assert(r, testutil.DatumEquals, types.NewDatum(tt.match))
+	wg := sync.WaitGroup{}
+	concurrency := 10
+	wg.Add(concurrency)
+	for i := 0; i < concurrency; i++ {
+		go func() {
+			defer wg.Done()
+			for _, tt := range tests {
+				fc := funcs[ast.Like]
+				f, err := fc.getFunction(s.ctx, s.datumsToConstants(types.MakeDatums(tt.input, tt.pattern, 0)))
```
Comment (SunRunAway) [inline expression/builtin_like_test.go:49]: If an individual function signature is created in one goroutine, the bug may not be revealed.

File: expression/builtin_like.go [hunk 8]
```diff
@@ -89,8 +89,11 @@ func (b *builtinLikeSig) evalInt(row chunk.Row) (int64, bool, error) {
 			b.isMemorizedPattern = true
 		}
 	}
+	// should be thread-safe
 	if !b.isMemorizedPattern {
-		b.pattern.Compile(patternStr, byte(escape))
+		pattern := b.collator().Pattern()
+		pattern.Compile(patternStr, byte(escape))
+		return boolToInt64(pattern.DoMatch(valStr)), false, nil
```
Comment (SunRunAway) [inline expression/builtin_like.go:96]: Could we move the `ConstItem` judgment to `getFunction`? So that we can keep this optimization in both vectorized and non-vectorized version and avoid data race.

Comment (fzhedu) [reply expression/builtin_like.go:96]: we can refine the expression system in terms of this later.

Comment (SunRunAway) [reply expression/builtin_like.go:96]: It's not a hard change. For both correctness and performance, we may do it here.

Comment (SunRunAway) [reply expression/builtin_like.go:96]: if both args[1] and args[2] are const items, the `b.pattern` could be set in `getFunction`, or a data race may happen at line 86.
