### PR TITLE
planner: fix error when window function is used in view definition

### LINKED ISSUE #25929: Error when create view with Window function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table if exists t6;
    CREATE TABLE t6(t TIME, ts TIMESTAMP);
    INSERT INTO t6 VALUES ('12:30', '2016-07-05 08:30:42');
    INSERT INTO t6 VALUES ('22:30', '2015-07-05 08:30:43');
    INSERT INTO t6 VALUES ('13:30', '2014-07-05 08:30:44');
    INSERT INTO t6 VALUES ('01:30', '2013-07-05 08:30:45');
    INSERT INTO t6 VALUES ('15:30', '2016-08-05 08:31:42');
    INSERT INTO t6 VALUES ('20:30', '2016-09-05 08:32:42');
    INSERT INTO t6 VALUES ('04:30', '2016-10-05 08:33:42');
    INSERT INTO t6 VALUES ('06:30', '2016-11-05 08:34:42');
    INSERT INTO t6 VALUES ('18:30', '2016-07-05 09:30:42');
    INSERT INTO t6 VALUES ('21:30', '2016-07-06 10:30:42');
    INSERT INTO t6 VALUES ('00:30', '2016-07-07 11:30:42');
    INSERT INTO t6 VALUES ('00:31', '2016-07-08 12:30:42');
    
    drop view if exists v;
    CREATE VIEW v AS SELECT COUNT(*) OVER w0, COUNT(*) OVER w from t6 WINDOW w0 AS (), w  AS (w0 ORDER BY t);
    select * from v;

### 2. What did you expect to see? (Required)

    mysql> select * from v;
    +------------------+-----------------+
    | COUNT(*) OVER w0 | COUNT(*) OVER w |
    +------------------+-----------------+
    |               12 |               1 |
    |               12 |               2 |
    |               12 |               3 |
    |               12 |               4 |
    |               12 |               5 |
    |               12 |               6 |
    |               12 |               7 |
    |               12 |               8 |
    |               12 |               9 |
    |               12 |              10 |
    |               12 |              11 |
    |               12 |              12 |
    +------------------+-----------------+
    12 rows in set (0.00 sec)
### 3. What did you see instead (Required)

    mysql> select * from v;
    ERROR 1356 (HY000): View 'test.v' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
### 4. What is your TiDB version? (Required)
only in master

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #25929 

Problem Summary: We got error when add alias name for view definition when window function is used. Check the view definition, an extra column is added(`test.t6`). Becase the `addAliasName()` function should be called before `resolveWindowFunction()`.

    SELECT COUNT(1) OVER `w0` AS `COUNT(*) OVER w0`,COUNT(1) OVER `w` AS `COUNT(*) OVER w`,`test`.`t6`.`t` AS `t` FROM `test`.`t6` WINDOW `w0` AS (),`w` AS (`w0` ORDER BY `t`)

### What is changed and how it works?

What's Changed: 
1. Change position `addAliasName()`

### Check List 

Tests 

- Integration test

Side effects: none

### Release note

```
planner: fix error when window function is used in view definition
```

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -3173,15 +3176,38 @@ func unfoldWildStar(field *ast.SelectField, outputName types.NameSlice, column [
 	return resultList
 }
 
-func (b *PlanBuilder) addAliasName(selectFields []*ast.SelectField, p LogicalPlan) (resultList []*ast.SelectField, err error) {
-	if len(selectFields) != len(p.OutputNames()) {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:3177]: This error should be left instead of being removed directly?

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -3173,15 +3176,38 @@ func unfoldWildStar(field *ast.SelectField, outputName types.NameSlice, column [
...
+			}
+			projOutNames = append(projOutNames, &types.FieldName{
+				TblName:     colNameField.Name.Table,
+				OrigTblName: colNameField.Name.Table,
+				ColName:     colName,
+				OrigColName: colNameField.Name.Name,
+				DBName:      colNameField.Name.Schema,
+			})
+		} else {
+			// create view v as select name_const('col', 100);
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:3197]: The view should be wrapped in a projection when `buildDataSource`, why do we still need this branch?

Comment (winoros) [reply planner/core/logical_plan_builder.go:3197]: Or this function is just called when we build the view?

Comment (guo-shaoge) [reply planner/core/logical_plan_builder.go:3197]: Yeah. Only add alias name for selectField when creating view(_b.capFlag&canExpandAST_). This is compatible with MySQL.

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (guo-shaoge) [reply planner/core/logical_plan_builder.go:3177]: Before this PR, `addAliasName` assumes one to one mapping between sel.Fields.Fields and p.OutputNames().
So we need this check.

After this PR, we only iterate over selectFields. So no need to check this.

**Review by Reminiscent — APPROVED** [review]

**Comment by guo-shaoge** [comment]
@winoros PTAL~

File: planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -3175,15 +3178,38 @@ func unfoldWildStar(field *ast.SelectField, outputName types.NameSlice, column [
...
+			// The column in v should be 'col', so we call `buildProjectionField` to handle this.
+			_, name, err := b.buildProjectionField(ctx, p, field, expr)
```
Comment (xuyifangreeneyes) [inline planner/core/logical_plan_builder.go:3201]: `expr` seems always `nil`?

**Review by xuyifangreeneyes — APPROVED** [review]

File: planner/core/logical_plan_builder.go (hunk 3 above)
Comment (guo-shaoge) [reply planner/core/logical_plan_builder.go]: Done.

**Review by XuHuaiyu — APPROVED** [review]
