### PR TITLE
*: support 2-phases flashback cluster

### LINKED ISSUE #38554: restart tidb during flashback, flashback ddl will hang
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run workload
2. run flashback, 
3. during flashback, restart tidb,tikv

### 2. What did you expect to see? (Required)
flashback successfully
### 3. What did you see instead (Required)
flashback command hang
### 4. What is your TiDB version? (Required)

[root@localhost patch]# ./tidb-server -V
Release Version: v6.3.0-alpha-436-g6c21fd2f2-dirty
Edition: Community
Git Commit Hash: 6c21fd2f2f3f2076d71f47e59c59a9f89fb084da
Git Branch: flashback-2-phase
UTC Build Time: 2022-10-19 08:46:41

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #38554, #37961

Problem Summary:

### What is changed and how it works?

* change flashback to two phases, first stage lock all regions, second stage do flashback.
* close all cross flashback cluster connection.

Above two reasons, we could remove many useless codes in Flashback. Like history flashback time ranges, auto analyze max time etc.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: meta/meta.go [hunk 1]
```diff
@@ -59,26 +59,25 @@ var (
...
-	mRandomIDPrefix          = "TARID"
-	mBootstrapKey            = []byte("BootstrapKey")
-	mSchemaDiffPrefix        = "Diff"
-	mPolicies                = []byte("Policies")
-	mPolicyPrefix            = "Policy"
-	mPolicyGlobalID          = []byte("PolicyGlobalID")
-	mPolicyMagicByte         = CurrentMagicByteVer
-	mDDLTableVersion         = []byte("DDLTableVersion")
-	mConcurrentDDL           = []byte("concurrentDDL")
-	mFlashbackHistoryTSRange = []byte("FlashbackHistoryTSRange")
```
Comment (Defined2014) [inline meta/meta.go:81]: It's useless, because in two phases, we insert new values instead of delete old values.

**Comment by bb7133** [comment]
> Change flashback to two phases

This is not needed before 'flashback cluster' is released as a feature. Please change it to 'None'

File: ddl/cluster.go [hunk 2]
```diff
@@ -156,9 +158,16 @@ func checkAndSetFlashbackClusterInfo(sess sessionctx.Context, d *ddlCtx, t *meta
...
 	// If flashbackSchemaVersion not same as nowSchemaVersion, we've done ddl during [flashbackTs, now).
-	if flashbackSchemaVersion != nowSchemaVersion {
-		return errors.Errorf("schema version not same, have done ddl during [flashbackTS, now)")
+	for i := flashbackSchemaVersion + 1; i <= nowSchemaVersion; i++ {
+		diff, err := t.GetSchemaDiff(i)
+		if err != nil {
+			return errors.Trace(err)
+		}
+		if diff != nil && diff.Type != model.ActionFlashbackCluster {
+			return errors.Errorf("Had ddl history during [%s, now), can't do flashback", oracle.GetTimeFromTS(flashbackTS))
```
Comment (bb7133) [inline ddl/cluster.go:169]:
```suggestion
			return errors.Errorf("Detected schema change due to another DDL job during [%s, now), can't do flashback", oracle.GetTimeFromTS(flashbackTS))
```

**Comment by Defined2014** [comment]
> > Change flashback to two phases
> 
> This is not needed before 'flashback cluster' is released as a feature. Please change it to 'None'

Done, PTAL @bb7133

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by xhebox — COMMENTED** [review]
LGTM, two questions

File: infoschema/builder.go [hunk 3]
```diff
@@ -219,6 +219,8 @@ func (b *Builder) ApplyDiff(m *meta.Meta, diff *model.SchemaDiff) ([]int64, erro
 		return b.applyRecoverTable(m, diff)
 	case model.ActionCreateTables:
 		return b.applyCreateTables(m, diff)
+	case model.ActionFlashbackCluster:
+		return []int64{-1}, nil
```
[the remark this answers is not in the document]
Comment (Defined2014) [reply infoschema/builder.go:223]: 1. use `-1` to represent all tables and it easy expand to `flashback table` and `flashback database`
2. If use empty slice, it will not add action to `relatedChange.ActionTypes`. see codes:
https://github.com/pingcap/tidb/blob/6c55faf034e8c205ffd23126829c637fb8a47451/domain/domain.go#L337-L347

**Review by xhebox — APPROVED** [review]

File: ddl/cluster.go [hunk 4]
```diff
@@ -245,31 +254,100 @@ func GetFlashbackKeyRanges(sess sessionctx.Context, startKey kv.Key) ([]kv.KeyRa
...
+		}
+
+		endKey := loc.EndKey
+		isLast := len(endKey) == 0 || (len(rangeEndKey) > 0 && bytes.Compare(endKey, rangeEndKey) >= 0)
+		// If it is the last region
+		if isLast {
+			endKey = rangeEndKey
+		}
+
+		logutil.BgLogger().Info("send prepare flashback request", zap.Uint64("region_id", loc.Region.GetID()),
```
Comment (zimulala) [inline ddl/cluster.go:291]:
```suggestion
		logutil.BgLogger().Info("[ddl] send prepare flashback request", zap.Uint64("region_id", loc.Region.GetID()),
```

File: ddl/cluster.go [hunk 5]
```diff
@@ -245,31 +254,100 @@ func GetFlashbackKeyRanges(sess sessionctx.Context, startKey kv.Key) ([]kv.KeyRa
...
-			keyRanges[0].StartKey = startKey
+
+		loc, err := s.GetRegionCache().LocateKey(bo, startKey)
+		if err != nil {
+			return taskStat, err
+		}
+
+		endKey := loc.EndKey
+		isLast := len(endKey) == 0 || (len(rangeEndKey) > 0 && bytes.Compare(endKey, rangeEndKey) >= 0)
+		// If it is the last region
```
Comment (zimulala) [inline ddl/cluster.go:286]:
```suggestion
		// If it is the last region.
```

File: ddl/cluster.go [hunk 6]
```diff
@@ -422,16 +565,25 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
 			return ver, nil
 		}
-
-		keyRanges, err := GetFlashbackKeyRanges(sess, tablecodec.EncodeTablePrefix(0))
+		keyRanges, err := GetFlashbackKeyRanges(sess)
 		if err != nil {
 			return ver, errors.Trace(err)
 		}
 
 		for _, ranges := range keyRanges {
```
Comment (zimulala) [inline ddl/cluster.go:573]:
```suggestion
		for _, range := range keyRanges {
```

File: ddl/cluster.go [hunk 7]
```diff
@@ -422,16 +565,25 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
-			if err = flashbackToVersion(context.Background(), d, flashbackTS, ranges.StartKey, ranges.EndKey); err != nil {
+			if err = flashbackToVersion(d.ctx, d,
+				func(ctx context.Context, r tikvstore.KeyRange) (rangetask.TaskStat, error) {
+					// use commitTS - 1 as startTS, make sure it less than commitTS.
+					stats, err := sendFlashbackToVersionRPC(ctx, d.store.(tikv.Storage), flashbackTS, commitTS-1, commitTS, r)
+					completedRegions.Add(uint64(stats.CompletedRegions))
+					logutil.BgLogger().Info("flashback cluster stats",
```
Comment (zimulala) [inline ddl/cluster.go:579]:
```suggestion
					logutil.BgLogger().Info("[ddl] flashback cluster stats",
```

File: ddl/cluster.go [hunk 8]
```diff
@@ -422,16 +565,25 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
+		keyRanges, err := GetFlashbackKeyRanges(sess)
 		if err != nil {
 			return ver, errors.Trace(err)
 		}
 
 		for _, ranges := range keyRanges {
-			if err = flashbackToVersion(context.Background(), d, flashbackTS, ranges.StartKey, ranges.EndKey); err != nil {
+			if err = flashbackToVersion(d.ctx, d,
+				func(ctx context.Context, r tikvstore.KeyRange) (rangetask.TaskStat, error) {
+					// use commitTS - 1 as startTS, make sure it less than commitTS.
```
Comment (zimulala) [inline ddl/cluster.go:576]:
```suggestion
					// Use commitTS - 1 as startTS, make sure it less than commitTS.
```

File: ddl/cluster.go [hunk 9]
```diff
@@ -245,31 +254,100 @@ func GetFlashbackKeyRanges(sess sessionctx.Context, startKey kv.Key) ([]kv.KeyRa
...
 			break
 		}
+		bo = tikv.NewBackoffer(ctx, flashbackMaxBackoff)
+		startKey = endKey
 	}
+	return taskStat, nil
+}
 
-	return keyRanges, nil
+func prepareFlashbackToVersion(
```
Comment (zimulala) [inline ddl/cluster.go:327]: It seems that this function code is the same as `flashbackToVersion`. Is it duplicated?

**Review by zimulala — APPROVED** [review]
