### PR TITLE
ddl: allow multiple `unique` attributes in a column

### LINKED ISSUE #12006: duplicate key name error in column type `a serial serial default value`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table t (a serial serial default value)
create table t (a int unique unique)
```

2. What did you expect to see?
In MySQL 5.7,
```sql
Query OK, 0 rows affected
```

3. What did you see instead?
```sql
(1061, 'duplicate key name a')
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-alpha-180-g7267ca30e                      |
| Git Commit Hash: 7267ca30ebc8f8999829419ffe397ab05e1f9b3c         |
| Git Branch: HEAD                                                  |
| UTC Build Time: 2019-09-03 08:11:53                               |
| GoVersion: go version go1.12.5 linux/amd64                        |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+

```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 
Fix #12006.

### What is changed and how it works?

Remove constraint name assignment when building `ast.Constraint` from `Option` of `ast.ColumnDef`. Let `checkConstraintNames` determine the name later to avoid the name duplication.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Allow multiple `unique` attributes in a column

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -527,11 +527,17 @@ func columnDefToCol(ctx sessionctx.Context, offset int, colDef *ast.ColumnDef, o
 			case ast.ColumnOptionAutoIncrement:
 				col.Flag |= mysql.AutoIncrementFlag
 			case ast.ColumnOptionPrimaryKey:
+				if col.Flag&mysql.PriKeyFlag != 0 {
```
Comment (lonng) [inline ddl/ddl_api.go]: It's better to add some comment.
