### PR TITLE
*: let handleMap supports partitionHandle

### LINKED ISSUE #44312: After exchange partition, the indexLookUp will return wrong result with keepOrder
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (id int not null, store_id int not null )  partition by range (store_id) (partition p0 values less than (6), partition p1 values less than (11), partition p2 values less than (16), partition p3 values less than (21) );
create table t1(id int not null, store_id int not null);
insert into t values (1, 1);
insert into t values (2, 17);
insert into t1 values (0, 18);
alter table t exchange partition p3 with table t1;
alter table t add index idx(id);
analyze table t;
select *,_tidb_rowid from t use index(idx) order by id limit 2;
```

### 2. What did you expect to see? (Required)

```
mysql> select *,_tidb_rowid from t use index(idx) order by id limit 2;
+----+----------+-------------+
| id | store_id | _tidb_rowid |
+----+----------+-------------+
|  0 |       18 |           1 |
|  1 |        1 |           1 |
+----+----------+-------------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select *,_tidb_rowid from t use index(idx) order by id limit 2;
+----+----------+-------------+
| id | store_id | _tidb_rowid |
+----+----------+-------------+
|  1 |        1 |           1 |
|  0 |       18 |           1 |
+----+----------+-------------+
2 rows in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #44312

Problem Summary: After exchange partition, a partition table may have same `_tidb_rowid` in different partition tables. So the handleMap should supports partitionHandle.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: kv/key.go [hunk 1]
```diff
@@ -434,16 +465,32 @@ func (m *HandleMap) Set(h Handle, val interface{}) {
...
-		delete(m.ints, h.IntValue())
+		delete(ints, h.IntValue())
 	} else {
-		delete(m.strs, string(h.Encoded()))
+		delete(strs, string(h.Encoded()))
 	}
 }
 
 // Len returns the length of the map.
 func (m *HandleMap) Len() int {
```
Comment (guo-shaoge) [inline kv/key.go:485]: Can `ints` and `partitionInts` merge into one? Otherwise `Len()` seems strage, because `ints` and `partitionInts` are exclusive.

File: planner/core/find_best_task.go [hunk 2]
```diff
@@ -1635,6 +1635,12 @@ func (ds *DataSource) convertToIndexScan(prop *property.PhysicalProperty,
 	}
 	if candidate.isMatchProp {
 		cop.keepOrder = true
+		if cop.tablePlan != nil && !ds.tableInfo.IsCommonHandle {
+			col, isNew := cop.tablePlan.(*PhysicalTableScan).appendExtraHandleCol(ds)
+			cop.extraHandleCol = col
+			cop.needExtraProj = cop.needExtraProj || isNew
```
Comment (guo-shaoge) [inline planner/core/find_best_task.go:1641]: Does this code related to this issue?

Comment (Defined2014) [reply planner/core/find_best_task.go:1641]: Yes, we should make sure `model.ExtraPhysTblID` in the last column. So move the code to the front.

File: kv/key.go (hunk 1 above)
Comment (Defined2014) [reply kv/key.go:485]: I think we could use `partitionInts[0]` to instead of `ints`, because `partitionID` shouldn't equal to 0. But i don't think that's good
1. an intHandle will do one more map lookup
2. implicitly assumes that partitionID will not be equal to 0, a little bit hack here

And I don't get why `Len()` function seems strange here. Because we could store different handle types in one `HandleMap`. Just like `TestHandleMapWithPartialHandle` test.

File: executor/partition_table_test.go [hunk 3]
```diff
@@ -821,6 +821,42 @@ func TestOrderByOnUnsignedPk(t *testing.T) {
...
+	tk.MustExec("insert into t values (1, 1)")
+	tk.MustExec("insert into t values (2, 17)")
+	tk.MustExec("insert into t1 values (0, 18)")
+	tk.MustExec("alter table t exchange partition p3 with table t1")
+	tk.MustExec("alter table t add index idx(id)")
+	tk.MustExec("analyze table t")
+	tk.MustQuery("select *,_tidb_rowid from t use index(idx) order by id limit 2").Check(testkit.Rows("0 18 1", "1 1 1"))
+
+	tk.MustExec("drop table t, t1")
+	tk.MustExec("create table t (a int, b int, c int, key `idx_ac`(a, c), key `idx_bc`(b, c))" +
```
[the remark this answers is not in the document]
Comment (Defined2014) [reply executor/partition_table_test.go:846]: This cannot happen. If a table has a primary key, it should not have `_tidb_rowid` . And the primary key should be part of the partition key, so it cannot be duplicated in the partitioned table.

And this PR only changed `index_merge.tableScan`, did not modify `partialTableScan` related codes.

**Comment by guo-shaoge** [comment]
rest lgtm

**Review by winoros — APPROVED** [review]
