### PR TITLE
ddl: skip shard_row_id_bits check if it is zero

### LINKED ISSUE #35406: Set `shard_row_id_bits` to zero panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In old TiDB version, it is possible to have both `shard_row_id_bits` and clustered primary key.
```
mysql> show create table t;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                              |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) NOT NULL,
  PRIMARY KEY (`a`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin /*T! SHARD_ROW_ID_BITS=4 */ |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

Altering it to zero can panic:

```
mysql> alter table t shard_row_id_bits = 0;
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
```

### 2. What did you expect to see? (Required)

```
Query OK, 0 rows affected (0.03 sec)
```

### 3. What did you see instead (Required)

```
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
```

### 4. What is your TiDB version? (Required)

129d9bc99

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #35406

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Since it is not possible to have both `shard_row_id_bits` and clustered pk in master, I remove the check:

```diff
--- a/ddl/ddl_api.go
+++ b/ddl/ddl_api.go
@@ -2833,9 +2833,9 @@ func handleTableOptions(options []*ast.TableOption, tbInfo *model.TableInfo) err
                case ast.TableOptionCompression:
                        tbInfo.Compression = op.StrValue
                case ast.TableOptionShardRowID:
-                       if op.UintValue > 0 && tbInfo.HasClusteredIndex() {
-                               return dbterror.ErrUnsupportedShardRowIDBits
-                       }
+                       //if op.UintValue > 0 && tbInfo.HasClusteredIndex() {
+                       //      return dbterror.ErrUnsupportedShardRowIDBits
+                       //}
                        tbInfo.ShardRowIDBits = op.UintValue
```

And I create the table:

```sql
mysql> create table t (a int primary key) shard_row_id_bits = 4;
Query OK, 0 rows affected (0.03 sec)

mysql> show create table t;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                              |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) NOT NULL,
  PRIMARY KEY (`a`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin /*T! SHARD_ROW_ID_BITS=4 */ |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

After this PR:

```sql
mysql> alter table t shard_row_id_bits = 0;
Query OK, 0 rows affected (0.03 sec)

mysql> show create table t;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                  |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) NOT NULL,
  PRIMARY KEY (`a`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: ddl/table.go [hunk 1]
```diff
@@ -857,12 +857,14 @@ func (w *worker) onShardRowID(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int6
 }
 
 func verifyNoOverflowShardBits(s *sessionPool, tbl table.Table, shardRowIDBits uint64) error {
+	if shardRowIDBits == 0 {
```
Comment (hawkingrei) [inline ddl/table.go:860]: Can you add some tests for it?

Comment (tangenta) [reply ddl/table.go:860]: It is not convenient to construct such a test. Please check the "manual test" in the PR description.
