### PR TITLE
planner,executor: fix 'select ...(join on partition table) for update' panic

### LINKED ISSUE #20028: Index out of range when querying on partitioned tables within a transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1, t2;
-- init
create table t1 (c_datetime datetime, primary key (c_datetime)) partition by range (to_days(c_datetime)) ( partition p0 values less than (to_days('2020-02-01')), partition p1 values less than (to_days('2020-04-01')), partition p2 values less than (to_days('2020-06-01')), partition p3 values less than maxvalue) ;
create table t2 (c_datetime datetime, unique key(c_datetime));
insert into t1 values ('2020-06-26 03:24:00'), ('2020-02-21 07:15:33'), ('2020-04-27 13:50:58');
insert into t2 values ('2020-01-10 09:36:00'), ('2020-02-04 06:00:00'), ('2020-06-12 03:45:18');
-- txn
begin;
select * from t1 join t2 on t1.c_datetime >= t2.c_datetime for update; -- ERROR 1105 (HY000): runtime error: index out of range
rollback;
```

### 2. What did you expect to see? (Required)

No error reported.

### 3. What did you see instead (Required)

```
mysql> begin;
Query OK, 0 rows affected (0.05 sec)

mysql> select * from t1 join t2 on t1.c_datetime >= t2.c_datetime for update;
ERROR 1105 (HY000): runtime error: index out of range [2] with length 2

```

### 4. What is your TiDB version? (Required)

master @ fa6baa9f5321d88f81a99e56af00526643e7bcaa
release-4.0 @ 51d365fc45fdfc039eb204a96268c5bd1c55075f

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #20028 

Problem Summary:

'select ... for update' need the table ID to construct the lock key.
When this SQL works on a partitioned table, the table ID should be partition ID.

So how to get that partition ID?  
In http://github.com/pingcap/tidb/pull/14921 I try to avoid column pruning of the partition columns, 
so we can get the partition column data, and then use it to calculate the partition to get the ID.

That fix works on a single table, but not the joining of tables.

### What is changed and how it works?

What's Changed:

In the logical plan phase, if `buildSelectLock` find itself works on partitioned tables, 
change the schema add an extra partition ID column to the DataSource.

Some tiny changes in the column pruning step to get the correct schema.

In the TableReader executor, fill the extra partition ID column in the chunk row.

In the SelectLockExec, use the partition ID from the chunk row, to construct the correct lock key.

How it Works:

Let the table reader return an extra column with partition ID, so the
SelectLockExec can use that partition ID to construct the lock key.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Fix panic when 'select ... for update' works on a join operation and the join uses partition table

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @SunRunAway @eurekaka

File: planner/core/planbuilder.go [hunk 1]
```diff
@@ -986,14 +986,43 @@ func removeIgnoredPaths(paths, ignoredPaths []*util.AccessPath, tblInfo *model.T
...
 	selectLock.SetChildren(src)
-	return selectLock
+
+	if len(b.partitionedTable) > 0 {
+		// If a chunk row is read from a partitioned table, which partition the row
+		// comes from is unknown. With the existence of Join, the situation could be
+		// even worse: SelectLock have to know the `pid` to construct the lock key.
+		// To solve the problem, an extra `pid` column is add to the schema, and the
+		// DataSource need to return the `pid` information in the chunk row.
+		err := addExtraPIDColumnToDataSource(src, &selectLock.extraPIDInfo)
```
[the remark this answers is not in the document]
Comment (tiancaiamao) [reply planner/core/planbuilder.go:1003]: This sounds like a good idea, thanks for pointing out, I'll have a try.

[the remark this answers is not in the document]
Comment (tiancaiamao) [reply planner/core/planbuilder.go]: Done

File: executor/table_reader.go [hunk 2]
```diff
@@ -194,9 +198,26 @@ func (e *TableReaderExecutor) Next(ctx context.Context, req *chunk.Chunk) error
 		return err
 	}
 
+	// When 'select ... for update' work on a partitioned table, the table reader should
+	// add the partition ID as an extra column. The SelectLockExec need this information
+	// to construct the lock key.
+	physicalID := getPhysicalTableID(e.table)
+	if physicalID != e.table.Meta().ID && e.extraPIDColumnIndex >= 0 {
```
[the remark this answers is not in the document]
Comment (tiancaiamao) [reply executor/table_reader.go]: Removed.

**Comment by tiancaiamao** [comment]
Adjusted according to the advice from @eurekaka  

* add ExtraPidCol in buildDataSource and change LogicalLock to a logicalSchemaProducer
* add ExtraPidCol into LogicalLock's schema, and let column pruning handle the rest of the thing

Some extra information is still necessary for SelectLock to know the mapping from table ID to the partition column index.

**Comment by tiancaiamao** [comment]
I have reverted the code to the previous implementation.
Add extra partition ID columns in table reader and depends on column pruning to prune them **does not always work**.

For example, in the physical optimizing phase, if there is only one KV entry in the range, DataSource will be converted to PointGet, but the schema is not correct, the extra PID column is not pruned.
And another case is Delete, delete may not handle the projection of the used columns, so column pruning will not prune the extra partition ID column for Delete, and this lead to a panic in the binlog encoding (the schema mismatch with the chunk data)

The current implementation only adds the partition ID column when there is a SelectLock on the partitioned table, so the change is minimal and no other parts are affected.

PTAL @eurekaka

**Review by eurekaka — COMMENTED** [review]
LGTM

File: executor/builder.go [hunk 3]
```diff
@@ -601,6 +601,16 @@ func (b *executorBuilder) buildSelectLock(v *plannercore.PhysicalLock) Executor
 		tblID2Handle:     v.TblID2Handle,
 		partitionedTable: v.PartitionedTable,
 	}
+	if len(e.partitionedTable) > 0 {
+		schema := v.Schema()
+		e.tblID2PIDColumnIndex = make(map[int64]int)
+		for i := 0; i < len(v.ExtraPIDInfo.Columns); i++ {
+			col := v.ExtraPIDInfo.Columns[i]
+			tblID := v.ExtraPIDInfo.TblIDs[i]
+			offset := schema.ColumnIndex(col)
```
Comment (XuHuaiyu) [inline executor/builder.go:610]: Check the column.ID is better

File: executor/partition_table_test.go [hunk 4]
```diff
@@ -182,3 +184,149 @@ partition p2 values less than (10))`)
...
+		tk2.MustExec("update pt set c = c + 1 where k = 5")
+		_, err := tk.Exec("commit")
+		c.Assert(err, NotNil)
+	}
+
+	optimisticIndexLookUp := func() {
+		tk.MustExec("set @@tidb_txn_mode = 'optimistic'")
+		tk2.MustExec("set @@tidb_txn_mode = 'optimistic'")
+		tk.MustExec("begin")
+		tk.MustQuery("select id, k from pt use index (k) where k = 5 for update").Check(testkit.Rows("5 5"))
```
Comment (XuHuaiyu) [inline executor/partition_table_test.go:257]: This is IndexReader.

We can query `select c, k ...`

File: executor/builder.go (hunk 3 above)
Comment (tiancaiamao) [reply executor/builder.go:610]: Check the column to be `ExtraPidColID` can get the column index in the schema, but can't build the mapping of 

table ID => partition column index in the schema

Here we take each partition column (v.ExtraPIDInfo.Columns[i]) and find its index in the schema (offset), to build the
mapping `tblID(v.ExtraPIDInfo.TblIDs[i])` => `offset`

**Comment by blacktear23** [comment]
@tiancaiamao I have a question:
At https://github.com/pingcap/tidb/blob/master/executor/executor.go#L943, do we need to clean e.keys after `doLockKeys` return success? 
Or the `Next` method is only called once?

**Comment by tiancaiamao** [comment]
> @tiancaiamao I have a question:
> At https://github.com/pingcap/tidb/blob/master/executor/executor.go#L943, do we need to clean e.keys after `doLockKeys` return success?
> Or the `Next` method is only called once?
> If `Next` called more than once, e.keys seems will append new columns and we may lock already locked keys again and again.

`Next` is called multiple times, until the returned `chunk` is empty. Here it's called only once because the `chunk` data is empty. @blacktear23

**Comment by lzmhhh123** [comment]
close #24262

**Comment by tiancaiamao** [comment]
After we introduce dynamic partition pruning, one table reader can read from multiple partitions, so add `extraPIDColumn` in the old way does not work.

A better fix for this issue under  dynamic partition pruning mode could be asking TiKV to return the `pid` column in the chunk row. That change requires much more work.

I just take a shortcut: use the old 'rewrite union' way even in the dynamic partition mode ... then this fix could work. The drawback is that we will not be able to get rid of the `PartitionUnion` executor in a short future.

@qw4990

File: planner/core/logical_plans.go [hunk 5]
```diff
@@ -1021,13 +1021,21 @@ type LogicalLimit struct {
 	limitHints limitHintInfo
 }
 
+type extraPIDInfo struct {
+	Columns []*expression.Column
+	TblIDs  []int64
```
Comment (qw4990) [inline planner/core/logical_plans.go:1026]: Please add more comments about these two fields.

File: executor/table_reader.go [hunk 6]
```diff
@@ -218,9 +237,26 @@ func (e *TableReaderExecutor) Next(ctx context.Context, req *chunk.Chunk) error
 		return err
 	}
 
+	// When 'select ... for update' work on a partitioned table, the table reader should
+	// add the partition ID as an extra column. The SelectLockExec need this information
+	// to construct the lock key.
+	physicalID := getPhysicalTableID(e.table)
+	if e.extraPIDColumnIndex.valid() {
+		fillExtraPIDColumn(req, e.extraPIDColumnIndex.value(), physicalID)
+	}
```
Comment (qw4990) [inline executor/table_reader.go:246]: Should we also do this in `IndexReader` and `IndexLookUp`?

Comment (tiancaiamao) [reply executor/table_reader.go:246]: This might be caused by the extra partition column I added.
Since the schema columns are now more than just the index column, the index read plan is not generated.

https://github.com/pingcap/tidb/pull/21148/files#diff-4c4a5d9c358008fc0d3e898b87a14692668d4b60d949b2796d8b6ebc2b890720R2679

Comment (tiancaiamao) [reply executor/table_reader.go:246]: How about merge this first and improve here later? 
If there is no `IndexReader` generated, there is no problem ... 
The test code cover the necessary cases and will prevent regression.

File: planner/core/logical_plans.go (hunk 5 above)
Comment (tiancaiamao) [reply planner/core/logical_plans.go:1026]: Done

**Review by zhuo-zhi — APPROVED** [review]

File: executor/table_reader.go (hunk 6 above)
Comment (qw4990) [reply executor/table_reader.go:246]: OK for me.

**Review by qw4990 — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by tiancaiamao** [comment]
This PR is terrible... it's a nightmare...
Just see how many bugs it has introduced!
