### PR TITLE
ddl: DROP PARTITION sees a row from a dropped partition in StateDeleteOnly with Global Index

### LINKED ISSUE #60021: During StateDeleteOnly in DROP PARTITION, old row in Global Index could still be seen
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

See this [test line](https://github.com/pingcap/tidb/blob/21f9bb7b7a7478d825c4dee4fbf2ce913e3e7cf1/pkg/ddl/tests/partition/multi_domain_test.go#L260), tkNO should not see this entry!

### 2. What did you expect to see? (Required)
Test fail, since the row should not be visible (see the [select above](https://github.com/pingcap/tidb/blob/21f9bb7b7a7478d825c4dee4fbf2ce913e3e7cf1/pkg/ddl/tests/partition/multi_domain_test.go#L253)).

### 3. What did you see instead (Required)
Test passes

### 4. What is your TiDB version? (Required)
current master 21f9bb7b7a7478d825c4dee4fbf2ce913e3e7cf1

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #60021 

Problem Summary:
The dropped partition was not filtered out when reading from the global index during StateWriteOnly, resulting in a rows from the dropped partition could be seen if the Global Index was used, but not if other access paths was used during that DDL State.

### What changed and how does it work?
Filtering out the dropped partition also for StateWriteOnly

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
During DROP PARTITION StateWriteOnly one could still access rows from the dropped partition through the Global Index.
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

File: pkg/meta/model/table.go [hunk 1]
```diff
@@ -1065,7 +1065,7 @@ func (pi *PartitionInfo) IDsInDDLToIgnore() []int64 {
 			return ids
 		}
 	case ActionDropTablePartition:
-		if len(pi.DroppingDefinitions) > 0 && pi.DDLState == StateDeleteOnly {
+		if len(pi.DroppingDefinitions) > 0 && (pi.DDLState == StateDeleteOnly || pi.DDLState == StateWriteOnly) {
```
Comment (lance6716) [inline pkg/meta/model/table.go:1068]: Do you think it's more clear to change the condition to `pi.DDLState != StatePublic`, or even remove this state filter? IMO Any partition state that started dropping should be ignored.

Comment (mjonss) [reply pkg/meta/model/table.go:1068]: For `pi.DDLAction == ActionDropTablePartition` the only `pi.DDLState`'s that are used are `StateWriteOnly`, `StateDeleteOnly` and `StateDeleteReorganization`, and for `StateDeleteReorganization`, `pi.DroppingDefinitions` is nil, so you are right, we can remove the check for `pi.DDLState`. Thanks!

**Review by lance6716 — APPROVED** [review]
