### PR TITLE
ddl: allow DDL on the system table in BDR mode

### LINKED ISSUE #60042: tidb always crash when rolling restart In BDR mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、BDR cluster
2、run Workload
3、add index
4、rolling restart the tidb of Primary

### 2. What did you expect to see? (Required)
tidb can start successfully

### 3. What did you see instead (Required)
tidb can not start
`{"log":"[bootstrap.go:1736] [\"doReentrantDDL error\"] [error=\"[ddl:8263]The operation is not allowed while the bdr role of this cluster is set to primary.\"] [stack=\"github.com/pingcap/tidb/pkg/session.doReentrantDDL\\n\\t/workspace/source/tidb/pkg/session/bootstrap.go:1736\\ngithub.com/pingcap/tidb/pkg/session.upgradeToVer245\\n\\t/workspace/source/tidb/pkg/session/bootstrap.go:3405\\ngithub.com/pingcap/tidb/pkg/session.upgrade\\n\\t/workspace/source/tidb/pkg/session/bootstrap.go:1583\\ngithub.com/pingcap/tidb/pkg/session.runInBootstrapSession\\n\\t/workspace/source/tidb/pkg/session/session.go:3754\\ngithub.com/pingcap/tidb/pkg/session.bootstrapSessionImpl\\n\\t/workspace/source/tidb/pkg/session/session.go:3476\\ngithub.com/pingcap/tidb/pkg/session.BootstrapSession\\n\\t/workspace/source/tidb/pkg/session/session.go:3422\\nmain.createStoreDDLOwnerMgrAndDomain\\n\\t/workspace/source/tidb/cmd/tidb-server/main.go:420\\nmain.main\\n\\t/workspace/source/tidb/cmd/tidb-server/main.go:323\\nruntime.main\\n\\t/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.7.linux-amd64/src/runtime/proc.go:272\"]","pod":"tc-tidb-1","container":"tidb","filename":"/localpath/pvc-d0cb87cb-7c4e-4add-9c5f-a99e7b44183b_endless-ha-test-bdr-ddl-tps-7828818-1-28_tidb-log-tc-tidb-1/tidb.log","level":"FATAL","namespace":"endless-ha-test-bdr-ddl-tps-7828818-1-28"}`

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v9.0.0-beta.1.pre-393-g89cab6a
Edition: Community
Git Commit Hash: 89cab6ace1da08ab7677cc015fb516d960ad2a13
Git Branch: HEAD
UTC Build Time: 2025-03-12 01:59:19
GoVersion: go1.23.7
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2025-03-13T04:03:59.129+0800

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #60042

Problem Summary:
During the upgrade, TiDB needs to do some DDL on the system table.
Some of them are non-replicable, such as 
```
ALTER TABLE mysql.bind_info MODIFY COLUMN original_sql LONGTEXT NOT NULL
```
In upgradeToVer245(),

```
ALTER TABLE mysql.tidb_pitr_id_map ADD PRIMARY KEY(restore_id, restored_ts, upstream_cluster_id, segment_id)
```
In upgradeToVer248().
If BDR mode is enabled, TiDB would fail to upgrade. 

### What changed and how does it work?
If the DDL is on a system table, we should not report an error.
Since the CDC would not sync the system table, it's ok to execute in BDR mode.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] 
Start an upstream cluster and a downstream cluster. (v8.1.0)

Upstream:
```
ADMIN SET BDR ROLE PRIMARY;
```  

Downstream:
```
ADMIN SET BDR ROLE SECONDARY;
```

Upgrade the upstream cluster to master.
Fail to start:
```
upstream-tidb-0                         0/1     Running     3 (2m6s ago)   3m23s
```
Upgrade the upstream cluster and the downstream cluster to this PR.
Upgrade success.
```
➜  ~ kubectl get pods
NAME                                    READY   STATUS      RESTARTS   AGE
collect-z6zhs-collect-logs-rb2pj        0/1     Completed   0          10m
collect-z6zhs-collect-metrics-8gj57     0/1     Completed   0          10m
downstream-discovery-544858bb56-tvrnb   1/1     Running     0          18m
downstream-monitor-0                    3/3     Running     0          18m
downstream-pd-0                         1/1     Running     0          18m
downstream-tidb-0                       1/1     Running     0          30s
downstream-tidb-1                       1/1     Running     0          56s
downstream-tikv-0                       1/1     Running     0          17m
sdkserver-0                             1/1     Running     0          18m
syncdiff-0                              1/1     Running     0          18m
upstream-discovery-9464fcc66-7l2db      1/1     Running     0          18m
upstream-monitor-0                      3/3     Running     0          18m
upstream-pd-0                           1/1     Running     0          18m
upstream-ticdc-0                        1/1     Running     0          17m
upstream-tidb-0                         1/1     Running     0          2m27s
upstream-tikv-0                         1/1     Running     0          17m
workload-0                              1/1     Running     0          18m
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/session/test/bootstraptest/bootstrap_upgrade_test.go [hunk 1]
```diff
@@ -895,3 +895,63 @@ func TestUpgradeWithCrossJoinDisabled(t *testing.T) {
 		require.NoError(t, store.Close())
 	}()
 }
+
+func TestUpgradeVersion245Primary(t *testing.T) {
+	if kerneltype.IsNextGen() {
+		t.Skip("Skip this case because there is no upgrade in the first release of next-gen kernel")
```
Comment (D3Hunter) [inline pkg/session/test/bootstraptest/bootstrap_upgrade_test.go]: the first release of nextgen have version 250, but now we are at 252, so nextgen also need this test

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

**Review by wlwilliamx — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
