### PR TITLE
monitor: optimize the statistics of db labels

### LINKED ISSUE #42025: metrics: record  tidb_server_handle_query_duration_seconds inaccurate
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. set `status.record-db-label=true`
2. `use test`
3. `select * from mysql.user;`
4. query metric `tidb_server_handle_query_duration_seconds` from prometheus

### 2. What did you expect to see? (Required)
tidb_executor_statement_total{db="mysql", instance="127.0.0.1:10080", job="tidb", type="Select"}

### 3. What did you see instead (Required)

tidb_executor_statement_total{db="test", instance="127.0.0.1:10080", job="tidb", type="Select"}

### 4. What is your TiDB version? (Required)

nightly

### PR DESCRIPTION
**Pull request by srstack**
### What problem does this PR solve?

Issue Number: close #42025 

Problem Summary:  record tidb_server_handle_query_duration_seconds inaccurate

### What is changed and how it works?

get db name label from stmtctx

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: session/session.go [hunk 1]
```diff
@@ -4283,3 +4278,24 @@ func RemoveLockDDLJobs(s Session, job2ver map[int64]int64, job2ids map[int64]str
 		return true
 	})
 }
+
+// GetDBNames gets the sql layer database names from the session.
+func GetDBNames(se *session) []string {
```
Comment (jackysp) [inline session/session.go:4283]: Nearly the same function with https://github.com/pingcap/tidb/pull/42026/files#diff-412615e1c1d4c6ae11a7885a11c879778bf401e0967c9c13c4b9dfd1f13ed29aR2561

File: server/conn.go [hunk 2]
```diff
@@ -2562,4 +2555,4 @@ func (cc getLastStmtInConn) PProfLabel() string {
 	default:
 		return ""
 	}
-}
+}
```
Comment (jackysp) [inline server/conn.go:2558]: I think gofmt will fail here.
