### PR TITLE
executor: add missing update table delta for TxnCtx

### LINKED ISSUE #20975: Unexpected "Information schema is changed" when commits
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### 2. What did you expect to see? (Required)
Commit successfully.
### 3. What did you see instead (Required)
Information schema is changed during the execution of the statement
### 4. What is your TiDB version? (Required)

4.0 master

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #20975

Problem Summary:

```sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### What is changed and how it works?

What's Changed:

When update statement without changes it missing track table ID for SchemaValidator. So when execute `commit` statement will cause SchemaValidator check whole Schema without tables and this will cause schema change error.

### Related changes

- No

### Check List 

Tests 

- Manual test (steps see below)

```sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)
```

Side effects

- Performance regression
    - Consumes more CPU when DML cause nothing changes
    - Consumes more MEM when DML cause nothing changes
    - Add lock for update TableDeltaMap may cause little slower

### Release note 

- No Release Note

### CODE REVIEW

File: executor/write.go [hunk 1]
```diff
@@ -169,6 +169,18 @@ func updateRecord(ctx context.Context, sctx sessionctx.Context, h kv.Handle, old
...
+			for id, col := range t.Cols() {
+				_, err := codec.EstimateValueSize(sc, newData[id])
+				if err != nil {
+					continue
+				}
+				// Nothing changed so size should be 0
+				colSize[col.ID] = 0
+			}
+			udpp := sctx.GetSessionVars().UseDynamicPartitionPrune()
+			txnCtx.UpdateDeltaForTable(t.Meta().ID, physicalID, 0, 0, colSize, udpp)
```
Comment (blacktear23) [inline executor/write.go:183]: @wjhuang2016 do I change `colSize` to nil good for here?

Comment (wjhuang2016) [reply executor/write.go:183]: You can use `map[int64]int64{}`.

File: executor/batch_point_get.go [hunk 2]
```diff
@@ -141,6 +141,13 @@ func (e *BatchPointGetExec) Next(ctx context.Context, req *chunk.Chunk) error {
 		}
 	}
 
+	if e.lock {
```
Comment (cfzjywxk) [inline executor/batch_point_get.go:144]: We could put `updateDeltaForTableID` in `initialize` so it's updated once.

File: executor/write.go (hunk 1 above)
Comment (cfzjywxk) [inline executor/write.go:183]: Seems not needed, the keys are already locked in `SelectLockExec`, `PointGetExec`, `BatchPointGetExec` and table ids are recorded there. If there are no keys locked, and no rows changed, which means there will be nothing in memory buffer, the txn will not be marked as `dirty` so the schema check is not done. Some test cases for the `rows changed but not locked` and `no rows changend and locked` could be added for it.

Comment (blacktear23) [reply executor/write.go:183]: Yes, no need for there.

File: executor/batch_point_get.go [hunk 3]
```diff
@@ -141,6 +141,10 @@ func (e *BatchPointGetExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
```
Comment (wjhuang2016) [inline executor/batch_point_get.go:144]: We can remove it now.

Comment (blacktear23) [reply executor/batch_point_get.go:144]: Why? If the table is not a partition table, initialize function will not add the table delta from `tblInfo.ID`

Comment (wjhuang2016) [reply executor/batch_point_get.go:144]: Why not put this logic into initialize() too?

Comment (blacktear23) [reply executor/batch_point_get.go]: There has a lot of return point in `initialize` function, so move it after `initialize` function return should be good.

File: executor/batch_point_get.go [hunk 4]
```diff
@@ -139,6 +139,9 @@ func (e *BatchPointGetExec) Next(ctx context.Context, req *chunk.Chunk) error {
 		if err := e.initialize(ctx); err != nil {
 			return err
 		}
+		if e.lock {
+			e.updateDeltaForTableID(e.tblInfo.ID)
```
Comment (cfzjywxk) [inline executor/batch_point_get.go:143]: Do we have data race risks on `TableDeltaMap` like https://github.com/pingcap/tidb/pull/19006 if there are multiple `PointGetExec` or `BatchPointGetExec`  with locks executing concurrently as data sources.

Comment (blacktear23) [reply executor/batch_point_get.go:143]: Looks possible. I think we should add a lock for `TxnCtx.UpdateDeltaForTable`.

**Comment by blacktear23** [comment]
@cfzjywxk PTAL

File: executor/executor_test.go [hunk 5]
```diff
@@ -6849,3 +6849,61 @@ func (s *testSuite) TestIssue19667(c *C) {
 	tk.MustExec("INSERT INTO t VALUES('1988-04-17 01:59:59')")
 	tk.MustQuery(`SELECT DATE_ADD(a, INTERVAL 1 SECOND) FROM t`).Check(testkit.Rows("1988-04-17 02:00:00"))
 }
+
```
Comment (cfzjywxk) [inline executor/executor_test.go:6852]: We could add some tests for patition table to verify the physical ids are used, and some tests for `union` statements using multiple data sources like `PointGetExec`.

**Comment by bb7133** [comment]
PTAL @cfzjywxk

**Comment by cfzjywxk** [comment]
LGTM

**Review by lysu — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by jebter** [comment]
@wjhuang2016 Maybe cherry-pick to the 4.0 branch?
