### PR TITLE
ttl: fix a wrong ttl's job schedule for TTL table upgraded from 6.5

### LINKED ISSUE #56539: The scheduling TTL job of table created in v6.5 is particularly frequent after upgraded to 7.5 or later versions
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create table TTL table in 6.5
2. upgrade cluster to 7.5 or later versions
3. select histories in `mysql.tidb_ttl_job_history` to see the schedule history

### 2. What did you expect to see? (Required)

The TTL job should be scheduled every 1 hour.

### 3. What did you see instead (Required)

The history shows the schedule interval is much less than 1 hour.

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #56539

Problem Summary:

In 6.5, the TTL table is created without meta `ttl_job_interval`, so after upgraded, the `SCHED_POLICY_EXPR` in `mysql.tidb_timers` is also empty that causing the frequent scheduling of TTL job.

### What changed and how does it work?

When syncing the timer, insert a default value if `ttl_job_interval` is empty

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/show.go [hunk 1]
```diff
@@ -1429,7 +1429,7 @@ func constructResultOfShowCreateTable(ctx sessionctx.Context, dbName *pmodel.CIS
 			restoreCtx.WriteKeyWord("TTL_JOB_INTERVAL")
 			restoreCtx.WritePlain("=")
 			if len(tableInfo.TTLInfo.JobInterval) == 0 {
-				restoreCtx.WriteString(model.DefaultJobInterval.String())
+				restoreCtx.WriteString(model.DefaultJobIntervalStr)
```
Comment (lcwangchao) [inline pkg/executor/show.go:1432]: We should not use `model.DefaultJobInterval.String()` (return `1h0m0s`) as the string interval value because the unit `s` is not supported in `duration.PartionDuration` @YangKeao

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by D3Hunter — APPROVED** [review]
