### PR TITLE
*: Pass make race

### LINKED ISSUE #1509: make race failed
Failed info:

WARNING: DATA RACE
Write by goroutine 189:
  github.com/pingcap/tidb/executor.(*NewXSelectIndexExec).Close()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/new_executor_xapi.go:112 +0x90
  github.com/pingcap/tidb/executor.(*ProjectionExec).Close()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/new_executor.go:610 +0x7b
  github.com/pingcap/tidb/executor.(*recordSet).Close()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/adapter.go:60 +0x6a
  github.com/pingcap/tidb.(*session).getExecRet()
      github.com/pingcap/tidb/_test/_obj_test/session.go:434 +0x5b6
  github.com/pingcap/tidb.(*session).GetGlobalSysVar()
      github.com/pingcap/tidb/_test/_obj_test/session.go:442 +0x33f
  github.com/pingcap/tidb.(*session).isAutocommit()
      github.com/pingcap/tidb/_test/_obj_test/session.go:477 +0x1dc
  github.com/pingcap/tidb.(*session).GetTxn()
      github.com/pingcap/tidb/_test/_obj_test/session.go:704 +0x2c1
  github.com/pingcap/tidb/executor.(*executorBuilder).buildNewIndexScan()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/new_builder.go:298 +0x8d
  github.com/pingcap/tidb/executor.(*executorBuilder).build()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/builder.go:128 +0x2a52
  github.com/pingcap/tidb/executor.(*executorBuilder).buildProjection()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/new_builder.go:228 +0x16b
  github.com/pingcap/tidb/executor.(*executorBuilder).build()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/builder.go:124 +0x303a
  github.com/pingcap/tidb/executor.(*statement).Exec()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/adapter.go:85 +0x1c4
  github.com/pingcap/tidb.(*session).ExecRestrictedSQL()
      github.com/pingcap/tidb/_test/_obj_test/session.go:395 +0xa4d
  github.com/pingcap/tidb.(*session).getExecRet()
      github.com/pingcap/tidb/_test/_obj_test/session.go:404 +0xd4
  github.com/pingcap/tidb.(*session).getPassword()
      github.com/pingcap/tidb/_test/_obj_test/session.go:771 +0x428
  github.com/pingcap/tidb.(*session).Auth()
      github.com/pingcap/tidb/_test/_obj_test/session.go:801 +0x32f
  github.com/pingcap/tidb.newSession()
      /home/xia/workspace/src/github.com/pingcap/tidb/tidb_test.go:332 +0x18d
  github.com/pingcap/tidb.(*testSessionSuite).TestSelectForUpdate()
      /home/xia/workspace/src/github.com/pingcap/tidb/session_test.go:813 +0x118
  runtime.call32()
      /home/xia/go/src/runtime/asm_amd64.s:472 +0x3d
  reflect.Value.Call()
      /home/xia/go/src/reflect/value.go:303 +0xcd
  github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/xia/workspace/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/check.go:772 +0x5d1
  github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/xia/workspace/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/check.go:666 +0x80

Previous read by goroutine 188:
  github.com/pingcap/tidb/executor.(*NewXSelectIndexExec).pickAndExecTask()
      /home/xia/workspace/src/github.com/pingcap/tidb/executor/new_executor_xapi.go:264 +0x6d

### PR DESCRIPTION
**Pull request by zimulala**
fix #1509

### CODE REVIEW

File: store/tikv/coprocessor.go [hunk 1]
```diff
@@ -291,14 +289,15 @@ func (it *copIterator) Next() (io.ReadCloser, error) {
...
 
-	it.mu.Lock()
-	defer it.mu.Unlock()
 	if err != nil {
 		it.Close()
 		return nil, errors.Trace(err)
 	}
 	it.respGot++
-	if it.respGot == len(it.tasks) {
+	it.mu.Lock()
```
Comment (disksing) [inline store/tikv/coprocessor.go]: The mutex should guard `it.respGot++` too.

**Comment by disksing** [comment]
LGTM.

**Comment by coocood** [comment]
LGTM
