### PR TITLE
infoschema: Fix is.schemata to show correct charset/collation

### LINKED ISSUE #7748: information schema does not show default charset from CREATE DATABASE
## Bug Report

1. What did you do?

```
mysql> CREATE DATABASE `foo` DEFAULT CHARACTER SET = 'utf8mb4';
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT default_character_set_name FROM information_schema.SCHEMATA  WHERE schema_name = 'foo';
+----------------------------+
| default_character_set_name |
+----------------------------+
| utf8                       |
+----------------------------+
1 row in set (0.00 sec)
mysql> show create database foo
    -> ;
+----------+------------------------------------------------------------------+
| Database | Create Database                                                  |
+----------+------------------------------------------------------------------+
| foo      | CREATE DATABASE `foo` /* !40100 DEFAULT CHARACTER SET utf8mb4 */ |
+----------+------------------------------------------------------------------+
1 row in set (0.00 sec)
```

2. What did you expect to see?
utf8mb4

3. What did you see instead?
utf8

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.0-rc.2

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve? 

Fixes #7748

### What is changed and how it works?

Prior to this fix, is.schemata used the global default charset, rather than the db specific default.

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change

Side effects

Unlikely

Related changes

None

### CODE REVIEW

File: infoschema/tables.go [hunk 1]
```diff
@@ -684,13 +684,27 @@ var filesCols = []columnInfo{
...
+		}
+
 		record := types.MakeDatums(
-			catalogVal,                 // CATALOG_NAME
-			schema.Name.O,              // SCHEMA_NAME
-			mysql.DefaultCharset,       // DEFAULT_CHARACTER_SET_NAME
-			mysql.DefaultCollationName, // DEFAULT_COLLATION_NAME
+			catalogVal,    // CATALOG_NAME
+			schema.Name.O, // SCHEMA_NAME
+			charset,       // DEFAULT_CHARACTER_SET_NAME
```
Comment (lamxTyler) [inline infoschema/tables.go]: It is better to update the comment to remove the `DEFAULT` prefix.

Comment (morgo) [reply infoschema/tables.go]: As I understand, the comment refers to the structure of `is.schemata`.  It remains correct with this patch:
```
mysql> SHOW CREATE TABLE schemata\G
*************************** 1. row ***************************
       Table: SCHEMATA
Create Table: CREATE TABLE `SCHEMATA` (
  `CATALOG_NAME` varchar(512) DEFAULT NULL,
  `SCHEMA_NAME` varchar(64) DEFAULT NULL,
  `DEFAULT_CHARACTER_SET_NAME` varchar(64) DEFAULT NULL,
  `DEFAULT_COLLATION_NAME` varchar(32) DEFAULT NULL,
  `SQL_PATH` varchar(512) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
1 row in set (0.01 sec)
```
