### PR TITLE
stats: fix panic caused by local feedback

### LINKED ISSUE #7148: updateStatsWorker got runtime error: index out of range
tidb version:

```
Release Version: v2.1.0-beta-107-g8b913c95e
Git Commit Hash: 8b913c95efc168a5b0811ecd2baa4f7c41385a30
Git Branch: master
UTC Build Time: 2018-07-25 06:32:03
GoVersion: go version go1.10.3 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
```

stack:

``` go
2018/07/25 14:38:39.464 domain.go:750: [error] updateStatsWorker, runtime error: index out of range, goroutine 112 [running]:                                                                                                                             
github.com/pingcap/tidb/util.GetStack(0xc4203933f0, 0x1d52d80, 0x2a056d0)                                                                                                                                                                                 
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/misc.go:52 +0x74
github.com/pingcap/tidb/domain.recoverInDomain(0x1f2ec97, 0x11, 0x1790000)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/domain/domain.go:749 +0x62
panic(0x1d52d80, 0x2a056d0)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/pingcap/tidb/util/chunk.Row.GetString(...)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/chunk/row.go:71
github.com/pingcap/tidb/util/chunk.Compare(0xc4452da8a0, 0xc4, 0x0, 0xc449469580, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/chunk/compare.go:188 +0xc4c
github.com/pingcap/tidb/util/chunk.(*Chunk).LowerBound.func1(0xc4, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/chunk/compare.go:216 +0x4f
sort.Search(0x188, 0xc420393768, 0x1e18b01)
        /usr/local/Cellar/go/1.10.3/libexec/src/sort/search.go:66 +0x58
github.com/pingcap/tidb/util/chunk.(*Chunk).LowerBound(0xc4452da8a0, 0x0, 0xc449469580, 0xffffffffffffffff, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/chunk/compare.go:215 +0x93
github.com/pingcap/tidb/statistics.buildBucketFeedback(0xc445175680, 0xc4448f6900, 0xc4291da8f0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/statistics/feedback.go:224 +0xe5
github.com/pingcap/tidb/statistics.splitBuckets(0xc445175680, 0xc4448f6900, 0xc42ccd4900, 0xc42ccd4900, 0xc420393a40, 0x1010788, 0x90, 0x1ec6240, 0x1)                                                                                                   
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/statistics/feedback.go:504 +0x50
github.com/pingcap/tidb/statistics.UpdateHistogram(0xc445175680, 0xc4448f6900, 0x1)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/statistics/feedback.go:537 +0x39
github.com/pingcap/tidb/statistics.(*Handle).UpdateStatsByLocalFeedback(0xc420526200, 0x20474e0, 0xc43390a930)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/statistics/update.go:432 +0x43f
github.com/pingcap/tidb/domain.(*Domain).updateStatsWorker(0xc4202b9400, 0x205d020, 0xc42040c0e0, 0x203fce0, 0xc4201642e0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/domain/domain.go:684 +0x80d
created by github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/domain/domain.go:606 +0x146
```

### PR DESCRIPTION
**Pull request by lamxTyler**
## What have you changed? (mandatory)

When we update the primary key stats by local feedback, we need to decode the original int values contained in the feedback, otherwise, it will cause panic when updating the histograms.
Fix #7148 

## What is the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

Unit test.
## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No.
## Does this PR affect tidb-ansible update? (mandatory)

No.
## Does this PR need to be added to the release notes? (mandatory)

No.

## Add a few positive/negative examples (optional)

PTAL @coocood @zz-jason @winoros

### CODE REVIEW

File: statistics/update_test.go [hunk 1]
```diff
@@ -693,16 +693,15 @@ func (s *testStatsUpdateSuite) TestUpdateStatsByLocalFeedback(c *C) {
...
 	testKit.MustQuery("select * from t use index(idx) where b = 5")
 
 	h.UpdateStatsByLocalFeedback(s.do.InfoSchema())
 	tbl = h.GetTableStats(tblInfo)
 
 	c.Assert(tbl.Columns[tblInfo.Columns[0].ID].ToString(0), Equals, "column:1 ndv:3 totColSize:0\n"+
 		"num: 1\tlower_bound: 1\tupper_bound: 1\trepeats: 1\n"+
-		"num: 2\tlower_bound: 2\tupper_bound: 2\trepeats: 1\n"+
-		"num: 3\tlower_bound: 4\tupper_bound: 4\trepeats: 1")
+		"num: 3\tlower_bound: 3\tupper_bound: 9223372036854775807\trepeats: 0")
```
Comment (shenli) [inline statistics/update_test.go]: Why the upper bound become so big?

File: statistics/update.go [hunk 2]
```diff
@@ -429,6 +429,7 @@ func (h *Handle) UpdateStatsByLocalFeedback(is infoschema.InfoSchema) {
 				continue
 			}
 			newCol := *col
+			fb = fb.decodeIntValues()
```
Comment (shenli) [inline statistics/update.go]: Without this line, will there always be panic? Why do the existing test cases not cover this case?

File: statistics/update_test.go [hunk 3]
```diff
@@ -721,6 +720,6 @@ func (s *testStatsUpdateSuite) TestUpdateStatsByLocalFeedback(c *C) {
 	c.Assert(tbl.Indices[tblInfo.Indices[0].ID].CMSketch.QueryBytes(low), Equals, uint32(2))
 
 	c.Assert(tbl.Indices[tblInfo.Indices[0].ID].ToString(1), Equals, "index:1 ndv:2\n"+
-		"num: 2\tlower_bound: NULL\tupper_bound: 2\trepeats: 0\n"+
-		"num: 4\tlower_bound: 3\tupper_bound: \trepeats: 0")
+		"num: 2\tlower_bound: \tupper_bound: 2\trepeats: 0\n"+
+		"num: 7\tlower_bound: 3\tupper_bound: 6\trepeats: 0")
```
Comment (zimulala) [inline statistics/update_test.go]: Why is the num `7`?

File: statistics/update_test.go (hunk 1 above)
Comment (zimulala) [reply statistics/update_test.go]: Why is the lower_bound 3？

File: statistics/update_test.go [hunk 4]
```diff
@@ -721,6 +721,6 @@ func (s *testStatsUpdateSuite) TestUpdateStatsByLocalFeedback(c *C) {
 	c.Assert(tbl.Indices[tblInfo.Indices[0].ID].CMSketch.QueryBytes(low), Equals, uint32(2))
 
 	c.Assert(tbl.Indices[tblInfo.Indices[0].ID].ToString(1), Equals, "index:1 ndv:2\n"+
-		"num: 2\tlower_bound: NULL\tupper_bound: 2\trepeats: 0\n"+
-		"num: 4\tlower_bound: 3\tupper_bound: \trepeats: 0")
+		"num: 2\tlower_bound: \tupper_bound: 2\trepeats: 0\n"+
```
Comment (winoros) [inline statistics/update_test.go]: lower_bound is displayed as nothing?

Comment (lamxTyler) [reply statistics/update_test.go]: Because query ` b <= 5` is transformed to `-inf < b <= 5`, after encoding the `-inf`, it is same as an empty string.

**Comment by lamxTyler** [comment]
PTAL @zimulala @winoros

File: statistics/feedback.go [hunk 5]
```diff
@@ -540,16 +560,14 @@ func UpdateHistogram(h *Histogram, feedback *QueryFeedback) *Histogram {
 }
 
 // UpdateCMSketch updates the CMSketch by feedback.
-func UpdateCMSketch(c *CMSketch, feedback *QueryFeedback) *CMSketch {
-	if c == nil {
-		return nil
+func UpdateCMSketch(c *CMSketch, feedbacks []feedback) *CMSketch {
```
Comment (coocood) [inline statistics/feedback.go]: use `pointFeedfacks` is more specific

**Comment by coocood** [comment]
LGTM

File: statistics/feedback.go [hunk 6]
```diff
@@ -727,3 +745,16 @@ func (q *QueryFeedback) recalculateExpectCount(h *Handle) error {
 	q.expected = int64(expected)
 	return nil
 }
+
+// splitFeedback splits the feedbacks into equality feedbacks and range feedbacks.
+func splitFeedbackByQueryType(feedbacks []feedback) ([]feedback, []feedback) {
+	var eqFB, ranFB []feedback
+	for _, fb := range feedbacks {
+		if bytes.Compare(kv.Key(fb.lower.GetBytes()).PrefixNext(), fb.upper.GetBytes()) >= 0 {
```
Comment (zz-jason) [inline statistics/feedback.go]: how about `== 0`?

File: statistics/feedback.go [hunk 7]
```diff
@@ -131,6 +131,26 @@ func (q *QueryFeedback) DecodeToRanges(isIndex bool) ([]*ranger.Range, error) {
 	return ranges, nil
 }
 
+func (q *QueryFeedback) decodeIntValues() *QueryFeedback {
+	nq := &QueryFeedback{}
+	nq.feedback = make([]feedback, 0, len(q.feedback))
+	for _, fb := range q.feedback {
+		_, lowInt, err := codec.DecodeInt(fb.lower.GetBytes())
+		if err != nil {
+			log.Debugf("decode int value failed: ", err)
```
Comment (zz-jason) [inline statistics/feedback.go]: how about:
```go
log.Debugf("decode feedback lower bound \"%v\" to integer failed: %v", fb.lower.GetBytes(), err)
```

File: statistics/feedback.go [hunk 8]
```diff
@@ -131,6 +131,26 @@ func (q *QueryFeedback) DecodeToRanges(isIndex bool) ([]*ranger.Range, error) {
...
+			continue
+		}
+		_, highInt, err := codec.DecodeInt(fb.upper.GetBytes())
+		if err != nil {
+			log.Debugf("decode int value failed: ", err)
```
Comment (zz-jason) [inline statistics/feedback.go]: how about:
```go
log.Debugf("decode feedback upper bound \"%v\" to integer failed: %v", fb.lower.GetBytes(), err)
```

File: statistics/feedback.go (hunk 6 above)
Comment (coocood) [reply statistics/feedback.go]: or `bytes.Equal`

Comment (lamxTyler) [reply statistics/feedback.go]: No, we cannot. Because sometimes the `lower` is equal to `upper`, so use `==0` would miss some feedbacks.

File: statistics/feedback.go [hunk 9]
```diff
@@ -271,7 +271,7 @@ func buildBucketFeedback(h *Histogram, feedback *QueryFeedback) (map[int]*Bucket
 		}
 		res, err = bkt.upper.CompareDatum(nil, ran.upper)
 		if err != nil {
-			log.Debugf("decode feedback lower bound \"%v\" to integer failed: %v", bkt.lower.GetBytes(), err)
+			log.Debugf("decode feedback lower bound \"%v\" to integer failed: %v", bkt.upper.GetBytes(), err)
```
Comment (coocood) [inline statistics/feedback.go]: should be `decode feedback upper bound`?

Comment (lamxTyler) [reply statistics/feedback.go]: Already fixed.
