### PR TITLE
executor: fix select from partition table on TiFlash

### LINKED ISSUE #19089: TiDB return wrong result when select partition table from TiFlash
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
run the following sql:
`create table test.employees  (id int,store_id int not null)partition by hash(store_id) partitions 4;`
`alter table test.employees set tiflash replica 1;`

wait for table available in tiflash

run the following sql:
`insert into test.employees(store_id) values (3);`
`set @@session.tidb_isolation_read_engines = "tiflash"`
`select * from test.employees`
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
+------+----------+
| id   | store_id |
+------+----------+
| NULL |        3 |
+------+----------+
### 3. What did you see instead (Required)
empty result

### 4. What is your TiDB version? (Required)
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-921-gb75a30fda
Edition: Community
Git Commit Hash: b75a30fda8eef5962e2fde1c6254ff02f330fd21
Git Branch: master
UTC Build Time: 2020-08-09 02:54:26
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #19089

Problem Summary:

### What is changed and how it works?

What's Changed:

In `nextPartition`, update the table ID to partition ID in DAGRequest.

How it Works:

The TablePartition executor changes executor for each partition  in `nextPartition`.
The table ID contained in  DAGRequest should also be changed.

TiKV does not really use the table ID field, it just use the encoded KV range, so the current code passes CI.
However, TiFlash use the table ID field. So we should still keep the ID information correct.

Update the table ID of the DAGRequest for each partition in the `nextPartition` function.

### Check List 

Tests 

- Unit test

### Release note 

-  No release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @zanmato1984  @imtbkcat @lysu 

/rebuild

**Comment by zanmato1984** [comment]
@lidezhu Please help to verify this fix on TiFlash daily regression.

File: executor/partition_table.go [hunk 1]
```diff
@@ -107,6 +114,33 @@ func nextPartitionWithTrace(ctx context.Context, n nextPartition, tbl table.Phys
 	return n.nextPartition(ctx, tbl)
 }
 
+// updateDAGRequestTableID update the table ID in the DAG request to partition ID.
+// TiKV only use that table ID for log, but TiFlash use it.
+func updateDAGRequestTableID(ctx context.Context, dag *tipb.DAGRequest, tableID, partitionID int64) {
+	// TiFlash set RootExecutor field and ignore Executors field.
+	if dag.RootExecutor != nil {
+		updateExecutorTableID(ctx, dag.RootExecutor, tableID, partitionID)
```
Comment (hanfei1991) [inline executor/partition_table.go:122]: root executor means the oldest ancestor , which is not always datasource.
In this case ,you should check leaf node

**Comment by lidezhu** [comment]
> @lidezhu Please help to verify this fix on TiFlash daily regression.

Verified that this fix passes TiFlash daily regression.

File: planner/core/exhaust_physical_plans.go [hunk 2]
```diff
@@ -1576,6 +1576,26 @@ func (p *LogicalJoin) tryToGetBroadCastJoin(prop *property.PhysicalProperty) []P
...
 	}
 
+	// Disable broadcast join on partition table for TiFlash.
+	for _, child := range p.children {
+		if ds, isDataSource := child.(*DataSource); isDataSource {
+			if ds.tableInfo.GetPartitionInfo() != nil {
+				return nil
+			}
+		} else {
+			us, isUnionScan := child.(*LogicalUnionScan)
```
Comment (hanfei1991) [inline planner/core/exhaust_physical_plans.go:1586]: needn't check union scan , because union scan will block push down.

File: executor/partition_table.go [hunk 3]
```diff
@@ -75,6 +86,11 @@ type nextPartitionForIndexMerge struct {
 func (n nextPartitionForIndexMerge) nextPartition(ctx context.Context, tbl table.PhysicalTable) (Executor, error) {
 	exec := n.exec
 	exec.table = tbl
+	for i := 0; i < len(exec.dagPBs); i++ {
```
Comment (lzmhhh123) [inline executor/partition_table.go:89]: There's no need to update the dag for index merge. Because it's impossible to build an index merge with TiFlash.

File: executor/partition_table.go [hunk 4]
```diff
@@ -54,6 +59,9 @@ type nextPartitionForIndexLookUp struct {
 
 func (n nextPartitionForIndexLookUp) nextPartition(ctx context.Context, tbl table.PhysicalTable) (Executor, error) {
 	n.exec.table = tbl
+	if err := updateDAGRequestTableID(ctx, n.exec.dagPB, tbl.Meta().ID, tbl.GetPhysicalID()); err != nil {
```
Comment (lzmhhh123) [inline executor/partition_table.go:62]: There's no need to update the dag for index lookup. Because it's impossible to build an index lookup with TiFlash.

File: executor/partition_table.go [hunk 5]
```diff
@@ -65,6 +73,9 @@ func (n nextPartitionForIndexReader) nextPartition(ctx context.Context, tbl tabl
 	exec := n.exec
 	exec.table = tbl
 	exec.physicalTableID = tbl.GetPhysicalID()
+	if err := updateDAGRequestTableID(ctx, n.exec.dagPB, tbl.Meta().ID, tbl.GetPhysicalID()); err != nil {
```
Comment (lzmhhh123) [inline executor/partition_table.go:76]: Ditto as index reader.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by hanfei1991 — APPROVED** [review]
LGTM

**Review by SunRunAway — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]

**Comment by tiancaiamao** [comment]
```
[2020-08-20T09:10:23.832Z] runtime/cgo: pthread_create failed: Resource temporarily unavailable
[2020-08-20T09:10:23.832Z] runtime/cgo: pthread_create failed: Resource temporarily unavailable
[2020-08-20T09:10:23.832Z] SIGABRT: abort
[2020-08-20T09:10:23.832Z] PC=0x7f1fa1951207 m=13 sigcode=18446744073709551610
```
