### PR TITLE
config: return error when `toml.DecodeFile` failed.

### LINKED ISSUE #51399: tidb config doesn't take effects when there are invalid config
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. write config like
```
  global:
    user: "guojiangtao"
    ssh_port: 22
    deploy_dir: "/home/guojiangtao/work/tiup_cluster/s3/data/deploy"
    data_dir: "/home/guojiangtao/work/tiup_cluster/s3/data/data"
    arch: "amd64"

  server_configs:
    tidb:
      mem-quota-query: 1073741824
      log.file.max-backups: 10
      log.file.max-days: 5
      log.slow-threshold: 1000
      disaggregated-tiflash: true
      new_collations_enabled_on_first_bootstrap: false
      oom-action: log
      performance.enforce-mpp: 1
      performance.txn-total-size-limit: 107374182
...
```
2. tiup cluster setup new cluster
3. check `disaggregated-tiflash` config: `show config where name like '%disagg%'`

### 2. What did you expect to see? (Required)
tidb config is correct
### 3. What did you see instead (Required)
`disaggregated-tiflash` config is wrong
ed8e4b65-0641-421e-b169-d883cd75ccd2

### 4. What is your TiDB version? (Required)
v7.5.0

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #51399

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: pkg/config/config.go [hunk 1]
```diff
@@ -1266,13 +1266,16 @@ func (c *Config) RemovedVariableCheck(confFile string) error {
 // Load loads config options from a toml file.
 func (c *Config) Load(confFile string) error {
 	metaData, err := toml.DecodeFile(confFile, c)
+	if err != nil {
+		return err
```
Comment (guo-shaoge) [inline pkg/config/config.go:1270]: Does this err will display in log file? It user set a wrong config, and it's better to let they konw why tidb cannot start.

Comment (Defined2014) [reply pkg/config/config.go:1270]: Yes, the error log will like `toml: line 5 (last key \"performance.enforce-mpp\"): incompatible types: TOML value has type int64; destination has type boolean`

Comment (Defined2014) [reply pkg/config/config.go:1270]: image

Comment (guo-shaoge) [reply pkg/config/config.go:1270]: I'm curious why it works because I remeber `global config` is inited before `logger`. If `global config` init failed, `logger` will not work

**Review by guo-shaoge — APPROVED** [review]

File: pkg/config/config.go (hunk 1 above)
Comment (Defined2014) [reply pkg/config/config.go:1270]: Use `log.Fatal`. 😂
