### PR TITLE
ddl: fix some limitation of primary key + global index

### LINKED ISSUE #56804: create non partition table with primary key + global index shouldn't success.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1(a int, b int, primary key (a) global);
create table t(a int, b int, primary key (a) global) partition by hash(a) partitions 5;
```

Also
```
create table t1(a int, b int);
alter table t1 add primary key (a) global;
```

### 2. What did you expect to see? (Required)

all report error

### 3. What did you see instead (Required)

create table success

### 4. What is your TiDB version? (Required)

```
v8.4.0-alpha-290-gf2ed8228ff
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #56804 

Problem Summary: If the primary index mentioned is a global index, then it should be a non-clustered index.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: pkg/ddl/create_table.go [hunk 1]
```diff
@@ -1570,6 +1570,10 @@ func isSingleIntPK(constr *ast.Constraint, lastCol *model.ColumnInfo) bool {
 // ShouldBuildClusteredIndex is used to determine whether the CREATE TABLE statement should build a clustered index table.
 func ShouldBuildClusteredIndex(mode variable.ClusteredIndexDefMode, opt *ast.IndexOption, isSingleIntPK bool) bool {
 	if opt == nil || opt.PrimaryKeyTp == pmodel.PrimaryKeyTypeDefault {
+		// The primary key is also a global index, shouldn't be a clustered index.
+		if opt != nil && opt.Global {
+			return false
+		}
```
Comment (mjonss) [inline pkg/ddl/create_table.go:1576]: So we are changing the implicit default of CLUSTERED PK depending if we have a global index or not?
I would prefer to always have that explicit, and fail if normally it would be CLUSTERED, but GLOBAL is given.

**Review by mjonss — COMMENTED** [review]
LGTM, but I would prefer not to implicitly change the [NON]CLUSTERED PK depending on GLOBAL option, rather have the implicit default as is, and fail instead of having GLOBAL change the type implicitly.

File: pkg/ddl/create_table.go (hunk 1 above)
Comment (Defined2014) [reply pkg/ddl/create_table.go]: Done

**Review by mjonss — APPROVED** [review]
