### PR TITLE
br: turn off the checkpoint mode when use noop storage

### LINKED ISSUE #41835: BR failed when use noop storage
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. ./br backup full -s "noop:///"

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
```
"br failed"] [error="unexpected end of JSON input"] [errorVerbose="unexpected end of JSON input\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/juju_adaptor.go:15\ngithub.com/pingcap/tidb/br/pkg/checkpoint.(*CheckpointRunner).checkLockFile\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/checkpoint/checkpoint.go:579 ...
```

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #41835 

Problem Summary:
the checkpoint mode lead to failure when br use noop storage

### What is changed and how it works?
turn off the checkpoint mode when use noop storage
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/task/backup.go [hunk 1]
```diff
@@ -365,6 +358,10 @@ func RunBackup(c context.Context, g glue.Glue, cmdName string, cfg *BackupConfig
 	if err != nil {
 		return errors.Trace(err)
 	}
+	// if use noop as external storage, turn off the checkpoint mode
+	if u.GetNoop() != nil {
+		cfg.UseCheckpoint = false
```
Comment (BornChanger) [inline br/pkg/task/backup.go:363]: Please add a message notifying that the checkpoint is ignored for xxx.

Comment (Leavrth) [reply br/pkg/task/backup.go:364]: done

**Review by YuJuncen — APPROVED** [review]
