### PR TITLE
executor: return error when recover indexHash/MergeJoin worker

### LINKED ISSUE #18070: memory-quota: inl_hash_join doesn't raise error when the usage of memory exceeds
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
_tide-config 
oom-action = "cancel"_
```sql
create table t1(a int, index(a));
create table t2(a int, index(a));
insert into t1 values(1),(2);
insert into t2 values(1),(1),(2),(2);
set @@tidb_mem_quota_query=1000;
select /*+ inl_hash_join(t1)*/ * from t1 join t2 on t1.a = t2.a;
```

### 2. What did you expect to see? (Required)
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]

### 3. What did you see instead (Required)
Empty set 
### 4. Affected version (Required)
v4.0.0

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close #18070  

Problem Summary:

### What is changed and how it works?

What's Changed:
return the OOM error when indexHashJoin worker panics

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- executor: return the OOM error when indexHashJoin worker panics

### CODE REVIEW

File: executor/index_lookup_hash_join.go [hunk 1]
```diff
@@ -189,7 +190,9 @@ func (e *IndexNestedLoopHashJoin) startWorkers(ctx context.Context) {
 
 func (e *IndexNestedLoopHashJoin) finishJoinWorkers(r interface{}) {
 	if r != nil {
-		logutil.BgLogger().Error("IndexNestedLoopHashJoin failed", zap.Error(errors.Errorf("%v", r)))
+		e.resultCh <- &indexHashJoinResult{
```
Comment (SunRunAway) [inline executor/index_lookup_hash_join.go:193]: Could you take a glance that if we have similar problems in other executors?
