### PR TITLE
br: support backup for merge_option attribute

### LINKED ISSUE #65060: br cannot presplit regions for table with SHARD_ROW_ID_BITS and PRE_SPLIT_REGIONS and merge_option
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create table
```
create table test.t1 (a int, b int) SHARD_ROW_ID_BITS=2 PRE_SPLIT_REGIONS=2;
alter table test.t1 attributes "merge_option=deny";
```
2. snapshot backup and restore

### 2. What did you expect to see? (Required)
```
show table test.t1 regions;
select * from information_schema.attributes from test.t1;
```
### 3. What did you see instead (Required)
nothing
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by JoyC-dev**
### What problem does this PR solve?

Issue Number: close #65060 

Problem Summary:

### What changed and how does it work?
BR supports merge-option attr. To achieve it, add merge-option attributes for backup schema including table-level and partition-level.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/metautil/metafile.go [hunk 1]
```diff
@@ -509,16 +511,23 @@ func parseSchemaFile(s *backuppb.Schema) (*Table, error) {
 		statsFileIndexes = s.StatsIndex
 	}
 
+	partitionMergeOptionAllowed := make(map[string]bool)
```
Comment (Leavrth) [inline br/pkg/metautil/metafile.go]:
```suggestion
	var partitionMergeOptionAllowed map[string]bool
```

File: br/pkg/restore/snap_client/client.go [hunk 2]
```diff
@@ -1134,10 +1142,150 @@ func (rc *SnapClient) createTables(
...
+		// Set merge_option for partitions if PartitionMergeOptionAllowed is set
+		if len(table.PartitionMergeOptionAllowed) > 0 &&
+			table.Info.Partition != nil && len(table.Info.Partition.Definitions) > 0 &&
+			newTableInfo.Partition != nil && len(newTableInfo.Partition.Definitions) > 0 {
+			// Create a map from old partition name to new partition definition for ID lookup
+			oldPartitionMap := make(map[string]*model.PartitionDefinition)
+			for i := range table.Info.Partition.Definitions {
+				def := &table.Info.Partition.Definitions[i]
+				oldPartitionMap[def.Name.O] = def
+			}
```
Comment (Leavrth) [inline br/pkg/restore/snap_client/client.go]:
```suggestion
```

File: br/pkg/restore/snap_client/client.go [hunk 3]
```diff
@@ -1134,10 +1142,150 @@ func (rc *SnapClient) createTables(
...
+
+					rulesToSet = append(rulesToSet, rule)
+				}
+			}
+		}
+	}
+
+	// Put label rules to PD in batches to avoid overwhelming PD
+	totalRules := len(rulesToSet)
+	for i := 0; i < totalRules; i += utils.LabelRuleBatchSize {
```
Comment (Leavrth) [inline br/pkg/restore/snap_client/client.go]: If `len(totalRules) > 0`, maybe we can use `slices.Chunk` to make codes simpler.
```
for sub := range slices.Chunk(totalRules, utils.LabelRuleBatchSize) {

}
```

File: br/pkg/restore/snap_client/client.go [hunk 4]
```diff
@@ -1134,10 +1142,150 @@ func (rc *SnapClient) createTables(
...
+		}
+		batch := rulesToSet[i:end]
+
+		log.Debug("putting label rules batch",
+			zap.Int("batch_start", i+1),
+			zap.Int("batch_end", end),
+			zap.Int("total", totalRules))
+
+		for _, rule := range batch {
+			err := infosync.PutLabelRule(ctx, rule)
```
Comment (Leavrth) [inline br/pkg/restore/snap_client/client.go]: Finally, is it not in batch?

File: br/pkg/restore/snap_client/client.go [hunk 5]
```diff
@@ -1134,10 +1142,150 @@ func (rc *SnapClient) createTables(
...
+		table := ct.OldTable
+		newTableInfo := ct.Table
+		// Set merge_option for the table itself if IsMergeOptionAllowed is true
+		if table.IsMergeOptionAllowed {
+			rule := label.NewRule()
+			// Use .L (lowercase) to match DDL behavior for case-insensitive matching
+			dbName := table.DB.Name.L
+			tableName := table.Info.Name.L
+			rule.ID = fmt.Sprintf(label.TableIDFormat, label.IDPrefix, dbName, tableName)
+			rule.Labels = []pdhttp.RegionLabel{
```
Comment (Leavrth) [inline br/pkg/restore/snap_client/client.go:1179]: Will it replace the existing labels of the table?

**Review by Leavrth — COMMENTED** [review]
rest LGTM

File: br/pkg/restore/snap_client/client.go (hunk 5 above)
Comment (JoyC-dev) [reply br/pkg/restore/snap_client/client.go:1179]: New tables are not supposed to have existing labels.

File: br/pkg/backup/schema.go [hunk 6]
```diff
@@ -293,13 +296,98 @@ func (s *schemaInfo) encodeToSchema() (*backuppb.Schema, error) {
...
+
+	// Get the specific label rules for this table and its partitions in batches
+	// to avoid overwhelming PD with too many requests at once
+	rules := make(map[string]*label.Rule)
+	totalRuleIDs := len(ruleIDs)
+	for i := 0; i < totalRuleIDs; i += utils.LabelRuleBatchSize {
+		end := i + utils.LabelRuleBatchSize
+		if end > totalRuleIDs {
+			end = totalRuleIDs
+		}
```
Comment (YuJuncen) [inline br/pkg/backup/schema.go]: if statement can be modernized using `min`.

File: br/pkg/backup/schema.go [hunk 7]
```diff
@@ -293,13 +296,98 @@ func (s *schemaInfo) encodeToSchema() (*backuppb.Schema, error) {
...
+		batchRules, err := infosync.GetLabelRules(ctx, batch)
+		if err != nil {
+			return false, nil, errors.Trace(err)
+		}
+
+		// Merge batch results into the main rules map
+		for id, rule := range batchRules {
+			rules[id] = rule
+		}
+	}
```
Comment (YuJuncen) [inline br/pkg/backup/schema.go]: Replace `m[k]=v` loop with `maps.Copy`.

File: br/pkg/backup/schema.go [hunk 8]
```diff
@@ -293,13 +296,98 @@ func (s *schemaInfo) encodeToSchema() (*backuppb.Schema, error) {
...
+			partitionRuleID := fmt.Sprintf(label.PartitionIDFormat, label.IDPrefix, dbName, tableName, def.Name.L)
+			ruleIDs = append(ruleIDs, partitionRuleID)
+		}
+	}
+
+	// Get the specific label rules for this table and its partitions in batches
+	// to avoid overwhelming PD with too many requests at once
+	rules := make(map[string]*label.Rule)
+	totalRuleIDs := len(ruleIDs)
+	for i := 0; i < totalRuleIDs; i += utils.LabelRuleBatchSize {
```
Comment (YuJuncen) [inline br/pkg/backup/schema.go]: `slices.Chunk` can be used here too.

File: br/pkg/backup/schema.go [hunk 9]
```diff
@@ -272,7 +275,7 @@ func (s *schemaInfo) dumpStatsToJSON(ctx context.Context, statsWriter *metautil.
 	return nil
 }
 
-func (s *schemaInfo) encodeToSchema() (*backuppb.Schema, error) {
+func (s *schemaInfo) encodeToSchema(ctx context.Context) (*backuppb.Schema, error) {
```
Comment (YuJuncen) [inline br/pkg/backup/schema.go]: It seems not pretty good to access network in a `encode` function. Consider filling the merge option outside.

File: br/pkg/backup/schema_merge_option_test.go [hunk 10]
```diff
@@ -0,0 +1,208 @@
...
+// mockLabelManagerForTest is a mock label manager for testing
+type mockLabelManagerForTest struct {
+	rules map[string]*label.Rule
+}
+
+func newMockLabelManagerForTest() *mockLabelManagerForTest {
+	return &mockLabelManagerForTest{
+		rules: make(map[string]*label.Rule),
+	}
+}
```
Comment (YuJuncen) [inline br/pkg/backup/schema_merge_option_test.go]: Dead code?

File: br/pkg/backup/schema_merge_option_test.go [hunk 11]
```diff
@@ -0,0 +1,208 @@
...
+
+	// Find normal table and partitioned table
+	var normalTable, partitionTable *metautil.Table
+	for _, schema := range schemas {
+		if schema.Info.Name.O == "t_normal" {
+			normalTable = schema
+		} else if schema.Info.Name.O == "t_partition" {
+			partitionTable = schema
+		}
+	}
```
Comment (YuJuncen) [inline br/pkg/backup/schema_merge_option_test.go:135]: could use tagged switch on `schema.Info.Name.O`

File: br/pkg/restore/snap_client/client.go [hunk 12]
```diff
@@ -1134,10 +1142,135 @@ func (rc *SnapClient) createTables(
...
+			startKey := tablecodec.EncodeTablePrefix(newTableInfo.ID)
+			endKey := tablecodec.EncodeTablePrefix(newTableInfo.ID + 1)
+			rule.Data = []any{
+				map[string]string{
+					"start_key": hex.EncodeToString(codec.EncodeBytes([]byte{}, startKey)),
+					"end_key":   hex.EncodeToString(codec.EncodeBytes([]byte{}, endKey)),
+				},
+			}
+			rule.Index = label.RuleIndexTable
+
```
Comment (YuJuncen) [inline br/pkg/restore/snap_client/client.go]: use `rule.Reset()`?

File: br/pkg/restore/snap_client/client.go [hunk 13]
```diff
@@ -1134,10 +1142,135 @@ func (rc *SnapClient) createTables(
...
+					endKey := tablecodec.EncodeTablePrefix(newDef.ID + 1)
+					rule.Data = []any{
+						map[string]string{
+							"start_key": hex.EncodeToString(codec.EncodeBytes([]byte{}, startKey)),
+							"end_key":   hex.EncodeToString(codec.EncodeBytes([]byte{}, endKey)),
+						},
+					}
+					rule.Index = label.RuleIndexPartition
+
+					rulesToSet = append(rulesToSet, rule)
```
Comment (YuJuncen) [inline br/pkg/restore/snap_client/client.go:1224]: Use `rule.Reset()`?

File: br/tests/br_merge_option_attributes/test_partition_table.sh [hunk 14]
```diff
@@ -0,0 +1,165 @@
+#!/bin/sh
+#
+# Copyright 2024 PingCAP, Inc.
```
Comment (YuJuncen) [inline br/tests/br_merge_option_attributes/test_partition_table.sh]: 2026

File: br/tests/br_merge_option_attributes/test_normal_table.sh [hunk 15]
```diff
@@ -0,0 +1,126 @@
+#!/bin/sh
+#
+# Copyright 2024 PingCAP, Inc.
```
Comment (YuJuncen) [inline br/tests/br_merge_option_attributes/test_normal_table.sh]: 2026

File: br/tests/br_merge_option_attributes/run.sh [hunk 16]
```diff
@@ -0,0 +1,69 @@
+#!/bin/sh
+#
+# Copyright 2024 PingCAP, Inc.
```
Comment (YuJuncen) [inline br/tests/br_merge_option_attributes/run.sh]: 2026.

nit: shebang is `/bin/sh` but `BASH_SOURCE` used. But it seems every script here has the same issue...

File: br/pkg/backup/schema.go (hunk 6 above)
Comment (JoyC-dev) [reply br/pkg/backup/schema.go]: change to slices.Chunk format, so the end process will be removed.

File: br/pkg/restore/snap_client/client.go (hunk 13 above)
Comment (JoyC-dev) [reply br/pkg/restore/snap_client/client.go:1224]: Outdate

**Review by YuJuncen — APPROVED** [review]
