### PR TITLE
types: fix compare float64 with float64 in json

### LINKED ISSUE #10461: Incorrect JSON float compare
## Bug Report

MySQL:

```
mysql> create table tx(id int key, a double, b double, c double, d double);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into tx values (1, 0.1, 0.2, 0.3, 0.0);
Query OK, 1 row affected (0.00 sec)

mysql> select a+b, c from tx;
+---------------------+------+
| a+b                 | c    |
+---------------------+------+
| 0.30000000000000004 |  0.3 |
+---------------------+------+
1 row in set (0.00 sec)

mysql> select json_array(a+b) = json_array(c) from tx;
+---------------------------------+
| json_array(a+b) = json_array(c) |
+---------------------------------+
|                               0 |
+---------------------------------+
1 row in set (0.00 sec)
```

TiDB:

```
mysql> create table tx(id int key, a double, b double, c double, d double);
Query OK, 0 rows affected (0.13 sec)

mysql> insert into tx values (1, 0.1, 0.2, 0.3, 0.0);
Query OK, 1 row affected (0.01 sec)

mysql> select a+b, c from tx;
+---------------------+------+
| a+b                 | c    |
+---------------------+------+
| 0.30000000000000004 |  0.3 |
+---------------------+------+
1 row in set (0.00 sec)

mysql> select json_array(a+b) = json_array(c) from tx;
+---------------------------------+
| json_array(a+b) = json_array(c) |
+---------------------------------+
|                               1 |
+---------------------------------+
1 row in set (0.00 sec)
```
## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close #10461

### What is changed and how it works?

What's Changed: reference https://github.com/mysql/mysql-server/blob/ee4455a33b10f1b1886044322e4893f587b319ed/sql/json_dom.cc#L2656

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix compare float64 with float64 in json

### CODE REVIEW

File: types/json/binary_functions.go [hunk 1]
```diff
@@ -647,6 +647,16 @@ func compareInt64(x int64, y int64) int {
 	return 1
 }
 
+func compareFloat64(x float64, y float64) int {
```
Comment (XuHuaiyu) [inline types/json/binary_functions.go:650]: Can we use compareFloat64PrecisionLoss

Comment (lzmhhh123) [reply types/json/binary_functions.go:650]: The origin code used it. The got the wrong result.

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @wshwsh12

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
