### PR TITLE
variable: fix information_schema.VARIABLES_INFO DEFAULT_VALUE not right problem

### LINKED ISSUE #49461: information_schema.variables_info DEFAULT_VALUE is incorrect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

use variables_info to select DEFAULT_VALUE is incorrect.
for example tidb_enable_1pc and tidb_enable_async_commit's DEFAULT is on
```
mysql> select * from information_schema.variables_info where variable_name in ('tidb_enable_async_commit','tidb_enable_1pc');
+--------------------------+----------------+---------------+---------------+-----------+-----------+-----------------+---------+
| VARIABLE_NAME            | VARIABLE_SCOPE | DEFAULT_VALUE | CURRENT_VALUE | MIN_VALUE | MAX_VALUE | POSSIBLE_VALUES | IS_NOOP |
+--------------------------+----------------+---------------+---------------+-----------+-----------+-----------------+---------+
| tidb_enable_async_commit | SESSION,GLOBAL | OFF           | ON            |      NULL |      NULL | NULL            | NO      |
| tidb_enable_1pc          | SESSION,GLOBAL | OFF           | ON            |      NULL |      NULL | NULL            | NO      |
+--------------------------+----------------+---------------+---------------+-----------+-----------+-----------------+---------+
2 rows in set (0.01 sec)

mysql> show variables like 'tidb_enable_async_commit';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| tidb_enable_async_commit | ON    |
+--------------------------+-------+
1 row in set (0.01 sec)

mysql> show variables like 'tidb_enable_1pc';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| tidb_enable_1pc | ON    |
+-----------------+-------+
1 row in set (0.00 sec)

```
### 2. What did you expect to see? (Required)

information_schema.variables_info DEFAULT_VALUE show correctly
### 3. What did you see instead (Required)
![image](https://github.com/pingcap/tidb/assets/44355590/d544e969-7edb-4943-b6cb-f20f570e924f)

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
master
```
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.6.0-alpha
Edition: Community
Git Commit Hash: 918df0ae50568ebc54bd6d89f2d9a49bc9b79b06
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2023-12-14 04:07:56
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #49968: set global variables default value wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```

1> deploy a new cluster
2> mysql> select VARIABLE_NAME,DEFAULT_VALUE,CURRENT_VALUE from information_schema.VARIABLES_INFO where  variable_name in ('tidb_txn_mode', 'tidb_enable_async_commit','tidb_enable_1pc', 'tidb_mem_oom_action', 'tidb_enable_auto_analyze', 'tidb_row_format_version', 'tidb_txn_assertion_level', 'tidb_enable_mutation_checker', 'tidb_pessimistic_txn_fair_locking') order by VARIABLE_NAME;                        +-----------------------------------+---------------+---------------+
| VARIABLE_NAME                     | DEFAULT_VALUE | CURRENT_VALUE |
+-----------------------------------+---------------+---------------+
| tidb_enable_1pc                   | OFF           | ON            |
| tidb_enable_async_commit          | OFF           | ON            |
| tidb_enable_auto_analyze          | ON            | ON            |
| tidb_enable_mutation_checker      | OFF           | ON            |
| tidb_mem_oom_action               | CANCEL        | CANCEL        |
| tidb_pessimistic_txn_fair_locking | OFF           | ON            |
| tidb_row_format_version           | 1             | 2             |
| tidb_txn_assertion_level          | OFF           | FAST          |
| tidb_txn_mode                     | pessimistic   | pessimistic   |
+-----------------------------------+---------------+---------------+
9 rows in set (0.01 sec)

because it is a new cluster, then the CURRENT_VALUE is the acutall default value.

3. mysql> set global tidb_txn_mode = default;
Query OK, 0 rows affected (0.01 sec)

mysql> set global tidb_enable_async_commit = default;
Query OK, 0 rows affected (0.01 sec)

mysql> set global tidb_enable_1pc = default;
Query OK, 0 rows affected (0.01 sec)

mysql> set global tidb_mem_oom_action = default;
Query OK, 0 rows affected (0.01 sec)

mysql> set global tidb_enable_auto_analyze = default;
Query OK, 0 rows affected (0.01 sec)

mysql> set global tidb_row_format_version = default;
Query OK, 0 rows affected (0.01 sec)

mysql> set global tidb_txn_assertion_level = default;
Query OK, 0 rows affected (0.02 sec)

mysql> set global tidb_enable_mutation_checker = default;
Query OK, 0 rows affected (0.01 sec)

mysql> set global tidb_pessimistic_txn_fair_locking = default;
Query OK, 0 rows affected (0.01 sec)

4.mysql> select a.VARIABLE_NAME, a.DEFAULT_VALUE, a.CURRENT_VALUE , b.VARIABLE_VALUE  from information_schema.VARIABLES_INFO as a, mysql.GLOBAL_VARIABLES as b where a.VARIABLE_NAME = b.VARIABLE_NAME and a.variable_name in ('tidb_txn_mode', 'tidb_enable_async_commit','tidb_enable_1pc', 'tidb_mem_oom_action', 'tidb_enable_auto_analyze', 'tidb_row_format_version', 'tidb_txn_assertion_level', 'tidb_enable_mutation_checker', 'tidb_pessimistic_txn_fair_locking') order by VARIABLE_NAME;
+-----------------------------------+---------------+---------------+----------------+
| VARIABLE_NAME                     | DEFAULT_VALUE | CURRENT_VALUE | VARIABLE_VALUE |
+-----------------------------------+---------------+---------------+----------------+
| tidb_enable_1pc                   | OFF           | ON            | OFF            |
| tidb_enable_async_commit          | OFF           | ON            | OFF            |
| tidb_enable_auto_analyze          | ON            | ON            | ON             |
| tidb_enable_mutation_checker      | OFF           | ON            | OFF            |
| tidb_mem_oom_action               | CANCEL        | CANCEL        | CANCEL         |
| tidb_pessimistic_txn_fair_locking | OFF           | ON            | OFF            |
| tidb_row_format_version           | 1             | 2             | 1              |
| tidb_txn_assertion_level          | OFF           | FAST          | OFF            |
| tidb_txn_mode                     | pessimistic   | pessimistic   | pessimistic    |
+-----------------------------------+---------------+---------------+----------------+
9 rows in set (0.01 sec)
```

After set default, some variable value not same with initt cluster value.

### 4. What is your TiDB version? (Required)

master

### LINKED ISSUE #50155: Cluster variables actual value is inconsistent in information_schema.variables_info
## Bug Report
We observed the default values of some database variables in information_schema.variables_info are inconsistent with its current behavior in v7.6.0 and the [TiDB doc](https://docs.pingcap.com/tidb/stable/system-variables).

### 1. Minimal reproduce step (Required)
tiup playground nightly
select variable_name,default_value,current_value from information_schema.variables_info where default_value !=current_value and default_value !='';
select tidb_version();

### 2. What did you expect to see? (Required)
The default values in information_schema.variables_info is consistent with the value of current value, plus the tidb doc.

### 3. What did you see instead (Required)
mysql> select variable_name,default_value,current_value from information_schema.variables_info where default_value !=current_value and default_value !='';
+-----------------------------------+---------------+--------------------+
| variable_name                     | default_value | current_value      |
+-----------------------------------+---------------+--------------------+
| tidb_enable_mutation_checker      | OFF           | ON                 |
| collation_connection              | utf8mb4_bin   | utf8mb4_0900_ai_ci |
| tidb_pessimistic_txn_fair_locking | OFF           | ON                 |
| tidb_enable_1pc                   | OFF           | ON                 |
| tidb_enable_async_commit          | OFF           | ON                 |
| tidb_txn_assertion_level          | OFF           | FAST               |
| tidb_row_format_version           | 1             | 2                  |
| last_sql_use_alloc                | OFF           | ON                 |
| timestamp                         | 0             | 1704682533.9524422 |
+-----------------------------------+---------------+--------------------+
9 rows in set (0.02 sec)

### 4. What is your TiDB version? (Required)
| Release Version: v7.6.0-alpha
Edition: Community
Git Commit Hash: 9b0fd9ea299266da70456f6e6077ed14bd191cfc
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2024-01-06 14:28:16
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv |

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #49461, close #49968, close #50155

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Without this pr, deploy a cluster:
```
mysql> select VARIABLE_NAME, VARIABLE_SCOPE, DEFAULT_VALUE, CURRENT_VALUE from information_schema.VARIABLES_INFO where DEFAULT_VALUE != CURRENT_VALUE and variable_name in ('tidb_txn_mode', 'tidb_enable_async_commit','tidb_enable_1pc', 'tidb_mem_oom_action', 'tidb_enable_auto_analyze', 'tidb_row_format_version', 'tidb_txn_assertion_level', 'tidb_enable_mutation_checker', 'tidb_pessimistic_txn_fair_locking');
+-----------------------------------+----------------+---------------+---------------+
| VARIABLE_NAME                     | VARIABLE_SCOPE | DEFAULT_VALUE | CURRENT_VALUE |
+-----------------------------------+----------------+---------------+---------------+
| tidb_row_format_version           | SESSION,GLOBAL | 1             | 2             |
| tidb_pessimistic_txn_fair_locking | SESSION,GLOBAL | OFF           | ON            |
| tidb_enable_async_commit          | SESSION,GLOBAL | OFF           | ON            |
| tidb_enable_mutation_checker      | SESSION,GLOBAL | OFF           | ON            |
| tidb_txn_mode                     | SESSION,GLOBAL |               | pessimistic   |
| tidb_txn_assertion_level          | SESSION,GLOBAL | OFF           | FAST          |
| tidb_enable_1pc                   | SESSION,GLOBAL | OFF           | ON            |
+-----------------------------------+----------------+---------------+---------------+
7 rows in set (0.07 sec)
```

With this pr:

```

mysql> select VARIABLE_NAME, VARIABLE_SCOPE, DEFAULT_VALUE, CURRENT_VALUE from information_schema.VARIABLES_INFO where DEFAULT_VALUE != CURRENT_VALUE and variable_name in ('tidb_txn_mode', 'tidb_enable_async_commit','tidb_enable_1pc', 'tidb_mem_oom_action', 'tidb_enable_auto_analyze', 'tidb_row_format_version', 'tidb_txn_assertion_level', 'tidb_enable_mutation_checker', 'tidb_pessimistic_txn_fair_locking');
Empty set (0.01 sec)


mysql> select VARIABLE_NAME, VARIABLE_SCOPE, DEFAULT_VALUE, CURRENT_VALUE from information_schema.VARIABLES_INFO where variable_name in ('tidb_txn_mode', 'tidb_enable_async_commit','tidb_enable_1pc', 'tidb_mem_oom_action', 'tidb_enable_auto_analyze', 'tidb_row_format_version', 'tidb_txn_assertion_level', 'tidb_enable_mutation_checker', 'tidb_pessimistic_txn_fair_locking');
+-----------------------------------+----------------+---------------+---------------+
| VARIABLE_NAME                     | VARIABLE_SCOPE | DEFAULT_VALUE | CURRENT_VALUE |
+-----------------------------------+----------------+---------------+---------------+
| tidb_mem_oom_action               | GLOBAL         | CANCEL        | CANCEL        |
| tidb_enable_1pc                   | SESSION,GLOBAL | ON            | ON            |
| tidb_enable_async_commit          | SESSION,GLOBAL | ON            | ON            |
| tidb_enable_auto_analyze          | GLOBAL         | ON            | ON            |
| tidb_row_format_version           | SESSION,GLOBAL | 2             | 2             |
| tidb_txn_mode                     | SESSION,GLOBAL | pessimistic   | pessimistic   |
| tidb_pessimistic_txn_fair_locking | SESSION,GLOBAL | ON            | ON            |
| tidb_txn_assertion_level          | SESSION,GLOBAL | FAST          | FAST          |
| tidb_enable_mutation_checker      | SESSION,GLOBAL | ON            | ON            |
+-----------------------------------+----------------+---------------+---------------+
9 rows in set (0.01 sec)

```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix the behavior to show the right default value for some variables
```

### CODE REVIEW

**Comment by jiyfhust** [comment]
/cc @dveeden 
PTAL

File: pkg/sessionctx/variable/sysvar.go [hunk 1]
```diff
@@ -2965,6 +2966,40 @@ var defaultSysVars = []*SysVar{
 		}},
 }
 
+func GlobalSyetemVariableInitialValue(varName, varVal string) string {
```
Comment (dveeden) [inline pkg/sessionctx/variable/sysvar.go:2969]: Can we add a unittest for this?

File: pkg/executor/infoschema_reader.go [hunk 2]
```diff
@@ -264,15 +264,20 @@ func (e *memtableRetriever) setDataForVariablesInfo(ctx sessionctx.Context) erro
...
 		row := types.MakeDatums(
 			sv.Name,           // VARIABLE_NAME
 			sv.Scope.String(), // VARIABLE_SCOPE
-			sv.Value,          // DEFAULT_VALUE
-			currentVal,        // CURRENT_VALUE
-			sv.MinValue,       // MIN_VALUE
-			sv.MaxValue,       // MAX_VALUE
-			nil,               // POSSIBLE_VALUES
-			isNoop,            // IS_NOOP
+			defVal,
```
Comment (dveeden) [inline pkg/executor/infoschema_reader.go:275]:
```suggestion
			defVal, // DEFAULT_VALUE
```
(but with `go fmt ...`)

File: pkg/sessionctx/variable/sysvar.go (hunk 1 above)
Comment (dveeden) [reply pkg/sessionctx/variable/sysvar.go:2969]:
```suggestion
// GlobalSystemVariableInitialValue gets the default value for a system variable including ones that are dynamically set (e.g. based on the store)
func GlobalSystemVariableInitialValue(varName, varVal string) string {
```
Please note the typo in the function name.

File: pkg/executor/infoschema_reader.go [hunk 3]
```diff
@@ -264,15 +264,20 @@ func (e *memtableRetriever) setDataForVariablesInfo(ctx sessionctx.Context) erro
 		if sv.IsNoop {
 			isNoop = "YES"
 		}
+		// DEFAULT_VALUE
+		defVal := sv.Value
+		if sv.HasGlobalScope() {
+			defVal = variable.GlobalSyetemVariableInitialValue(sv.Name, defVal)
```
Comment (dveeden) [inline pkg/executor/infoschema_reader.go:270]:
```suggestion
			defVal = variable.GlobalSystemVariableInitialValue(sv.Name, defVal)
```

File: pkg/sessionctx/variable/sysvar.go (hunk 1 above)
Comment (jiyfhust) [reply pkg/sessionctx/variable/sysvar.go]: > Can we add a unittest for this?

@dveeden Thank you for your suggestions. Can you explain more about the unittests，is it about to check the initalValue of some global variables under the `InTest`?

Other suggestions have been updated.

Comment (jiyfhust) [reply pkg/sessionctx/variable/sysvar.go]: > Can we add a unittest for this?

Added [0bdec4e](https://github.com/pingcap/tidb/pull/49524/commits/0bdec4e799b38b6ed2b0dae66d4e3a962aed4e14)

File: pkg/sessionctx/variable/sysvar.go [hunk 4]
```diff
@@ -2965,6 +2966,41 @@ var defaultSysVars = []*SysVar{
...
+// GlobalSystemVariableInitialValue gets the default value for a system variable including ones that are dynamically set (e.g. based on the store)
+func GlobalSystemVariableInitialValue(varName, varVal string) string {
+	switch varName {
+	case TiDBTxnMode:
+		if config.GetGlobalConfig().Store == "tikv" || config.GetGlobalConfig().Store == "unistore" {
+			varVal = "pessimistic"
+		}
+	case TiDBEnableAsyncCommit, TiDBEnable1PC:
+		if config.GetGlobalConfig().Store == "tikv" {
+			varVal = On
```
Comment (JmPotato) [inline pkg/sessionctx/variable/sysvar.go:2978]: Can we retrieve the default value from a centralized location instead of hard coding it here? This could be a problem if we ever need to change the default value in the future but forget to modify this here.

Comment (jiyfhust) [reply pkg/sessionctx/variable/sysvar.go:2978]:
```
diff --git a/pkg/sessionctx/variable/sysvar.go b/pkg/sessionctx/variable/sysvar.go
index 532cd0f..e74cdf9 100644
--- a/pkg/sessionctx/variable/sysvar.go
+++ b/pkg/sessionctx/variable/sysvar.go
@@ -2093,7 +2093,7 @@ var defaultSysVars = []*SysVar{
                s.ShardAllocateStep = TidbOptInt64(val, DefTiDBShardAllocateStep)
                return nil
        }},
-       {Scope: ScopeGlobal | ScopeSession, Name: TiDBEnableAsyncCommit, Value: BoolToOnOff(DefTiDBEnableAsyncCommit), Type: TypeBool, 
+       {Scope: ScopeGlobal | ScopeSession, Name: TiDBEnableAsyncCommit, Value: defaultTiDBEnableAsyncCommit(), Type: TypeBool, SetSess
                s.EnableAsyncCommit = TiDBOptOn(val)
                return nil
        }},
@@ -2965,6 +2965,13 @@ var defaultSysVars = []*SysVar{
                }},
 }
 
+func defaultTiDBEnableAsyncCommit() string {
+       if config.GetGlobalConfig().Store == "tikv" {
+               return On
+       }
+       return BoolToOnOff(DefTiDBEnableAsyncCommit)
+}
+
```

I tried this way. But it seems `defaultSysVars ` is inited early than `config.GetGlobalConfig()`, so it can't work.
Maybe we can set `variable.GetSysVars` after `config.GetGlobalConfig()` loaded, but it is also "hard coding".

Comment (jiyfhust) [reply pkg/sessionctx/variable/sysvar.go:2978]: * if we need set diffrent defalut value for diffrent store types for example `TiDBEnableAsyncCommit`，we need do that after `config.GetGlobalConfig()` loaded
* others，we can move into `defaultSysVars`, for example `TiDBRowFormatVersion`.

/cc @JmPotato

Comment (lcwangchao) [reply pkg/sessionctx/variable/sysvar.go:2978]: It looks like this PR has minimal changes to fix the bug. If we want a more elegant way to make it, some questions should be answered before:

1. Do we need to keep the "right" default value for unistore which is only used for testing ? If we do not need it, we can make variables like `TiDBEnableAsyncCommit` configured statically without reading global config.
2. If cluster upgrades from an old one. What is the right default value for the variables that don't want to change. Just like `tidb_pessimistic_txn_fair_locking`, it should keep the old default value 'OFF' after upgrading and 'ON' for a new cluster.

**Review by lcwangchao — APPROVED** [review]

**Comment by lcwangchao** [comment]
@jiyfhust  seems some tests failed, PTAL

**Comment by jiyfhust** [comment]
> @jiyfhust seems some tests failed, PTAL

Done. Tests passed after #48500 merged.

**Comment by jiyfhust** [comment]
Fix `set global varname = default` `[[209f385](https://github.com/pingcap/tidb/pull/49524/commits/209f385329ce52716aa7e1acd6fe3530e1e8259a)](https://github.com/pingcap/tidb/pull/49524/commits/209f385329ce52716aa7e1acd6fe3530e1e8259a)` .
PTAL @lcwangchao

File: tests/integrationtest/r/executor/infoschema_reader.result [hunk 5]
```diff
@@ -283,3 +283,34 @@ SELECT * FROM information_schema.user_privileges WHERE grantee="'usageuser'@'%'"
...
+VARIABLE_NAME
+tidb_enable_1pc
+tidb_enable_async_commit
+tidb_enable_auto_analyze
+tidb_enable_mutation_checker
+tidb_mem_oom_action
+tidb_pessimistic_txn_fair_locking
+tidb_row_format_version
+tidb_txn_assertion_level
+tidb_txn_mode
```
Comment (Defined2014) [inline tests/integrationtest/r/executor/infoschema_reader.result:296]: `tidb_txn_mode` already covered by https://github.com/pingcap/tidb/pull/48500, no need to add it here.

File: pkg/sessionctx/variable/sysvar.go
Comment (jiyfhust) [inline pkg/sessionctx/variable/sysvar.go:1]: > tidb_txn_mode already covered by https://github.com/pingcap/tidb/pull/48500, no need to add it here.

@Defined2014 How about remove these together?

File: tests/integrationtest/r/executor/infoschema_reader.result (hunk 5 above)
Comment (jiyfhust) [reply tests/integrationtest/r/executor/infoschema_reader.result]: > `tidb_txn_mode` already covered by #48500, no need to add it here.

done. https://github.com/pingcap/tidb/pull/49524/commits/0558302f2ac1a9cc083a7112b6cd51f13b7aed77

**Comment by lcwangchao** [comment]
> Fix `set global varname = default` [209f385](https://github.com/pingcap/tidb/commit/209f385329ce52716aa7e1acd6fe3530e1e8259a) . PTAL @lcwangchao

This update seems to cause a behavior change for setting system variable to a default value. @bb7133 @easonn7. Could you take a look?

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by Defined2014** [comment]
Also could close https://github.com/pingcap/tidb/issues/50155

**Comment by jiyfhust** [comment]
> Also could close #50155, please add it on `Issue Number`

Added.

**Review by hawkingrei — APPROVED** [review]
