### PR TITLE
planner: keep join keys for join optimization in constant propagation | tidb-test=pr/2600

### LINKED ISSUE #60076: planner: keep redundant Join Key predicates when propagating EQ predicates
## Enhancement

See the case below, before adding `t1.a=1`, the `leading` can work well, while after adding it, the `leading` can't work and there are multiple dangerous Cartesian Joins.

The root cause is that before Join Order, the optimizer propagates `t1.a=1` and uses it to convert all join keys like `t1.a=t2.a` to `t2.a=1` directly, which eliminates these join keys, and finally cause some problem to Join Order and the Leading Hint.

```
create table t1 (a int, b int, c int);
create table t2 (a int, b int, c int);
create table t3 (a int, b int, c int);
create table t4 (a int, b int, c int);

mysql> explain select /*+ leading(t1, t4) */ * from t1 join t2 on 
             t1.a=t2.a join t3 on t1.a=t3.a join t4 on t1.a=t4.a;
+------------------------------------+----------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows  | task      | access object | operator info                                                                                                                      |
+------------------------------------+----------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| Projection_18                      | 19511.72 | root      |               | test.t1.a, test.t1.b, test.t1.c, test.t2.a, test.t2.b, test.t2.c, test.t3.a, test.t3.b, test.t3.c, test.t4.a, test.t4.b, test.t4.c |
| └─HashJoin_19                      | 19511.72 | root      |               | inner join, equal:[eq(test.t1.a, test.t3.a)]                                                                                       |
|   ├─TableReader_36(Build)          | 9990.00  | root      |               | data:Selection_35                                                                                                                  |
|   │ └─Selection_35                 | 9990.00  | cop[tikv] |               | not(isnull(test.t3.a))                                                                                                             |
|   │   └─TableFullScan_34           | 10000.00 | cop[tikv] | table:t3      | keep order:false, stats:pseudo                                                                                                     |
|   └─HashJoin_21(Probe)             | 15609.38 | root      |               | inner join, equal:[eq(test.t1.a, test.t2.a)]                                                                                       |
|     ├─TableReader_33(Build)        | 9990.00  | root      |               | data:Selection_32                                                                                                                  |
|     │ └─Selection_32               | 9990.00  | cop[tikv] |               | not(isnull(test.t2.a))                                                                                                             |
|     │   └─TableFullScan_31         | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                                                     |
|     └─HashJoin_23(Probe)           | 12487.50 | root      |               | inner join, equal:[eq(test.t1.a, test.t4.a)]                                                                                       |
|       ├─TableReader_30(Build)      | 9990.00  | root      |               | data:Selection_29                                                                                                                  |
|       │ └─Selection_29             | 9990.00  | cop[tikv] |               | not(isnull(test.t4.a))                                                                                                             |
|       │   └─TableFullScan_28       | 10000.00 | cop[tikv] | table:t4      | keep order:false, stats:pseudo                                                                                                     |
|       └─TableReader_27(Probe)      | 9990.00  | root      |               | data:Selection_26                                                                                                                  |
|         └─Selection_26             | 9990.00  | cop[tikv] |               | not(isnull(test.t1.a))                                                                                                             |
|           └─TableFullScan_25       | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                                                     |
+------------------------------------+----------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
mysql> show warnings;
Empty set (0.00 sec)

mysql> explain select /*+ leading(t1, t4) */ * from t1 join t2 on 
             t1.a=t2.a join t3 on t1.a=t3.a join t4 on t1.a=t4.a where t1.a=1;
+------------------------------------+----------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows  | task      | access object | operator info                                                                                                                      |
+------------------------------------+----------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------+
| Projection_18                      | 10000.00 | root      |               | test.t1.a, test.t1.b, test.t1.c, test.t2.a, test.t2.b, test.t2.c, test.t3.a, test.t3.b, test.t3.c, test.t4.a, test.t4.b, test.t4.c |
| └─HashJoin_19                      | 10000.00 | root      |               | CARTESIAN inner join                                                                                                               |
|   ├─TableReader_36(Build)          | 10.00    | root      |               | data:Selection_35                                                                                                                  |
|   │ └─Selection_35                 | 10.00    | cop[tikv] |               | eq(1, test.t3.a)                                                                                                                   |
|   │   └─TableFullScan_34           | 10000.00 | cop[tikv] | table:t3      | keep order:false, stats:pseudo                                                                                                     |
|   └─HashJoin_21(Probe)             | 1000.00  | root      |               | CARTESIAN inner join                                                                                                               |
|     ├─TableReader_33(Build)        | 10.00    | root      |               | data:Selection_32                                                                                                                  |
|     │ └─Selection_32               | 10.00    | cop[tikv] |               | eq(1, test.t2.a)                                                                                                                   |
|     │   └─TableFullScan_31         | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                                                     |
|     └─HashJoin_23(Probe)           | 100.00   | root      |               | CARTESIAN inner join                                                                                                               |
|       ├─TableReader_30(Build)      | 10.00    | root      |               | data:Selection_29                                                                                                                  |
|       │ └─Selection_29             | 10.00    | cop[tikv] |               | eq(1, test.t4.a)                                                                                                                   |
|       │   └─TableFullScan_28       | 10000.00 | cop[tikv] | table:t4      | keep order:false, stats:pseudo                                                                                                     |
|       └─TableReader_27(Probe)      | 10.00    | root      |               | data:Selection_26                                                                                                                  |
|         └─Selection_26             | 10.00    | cop[tikv] |               | eq(test.t1.a, 1)                                                                                                                   |
|           └─TableFullScan_25       | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                                                     |
+------------------------------------+----------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------+

mysql> show warnings;
+---------+------+-----------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                             |
+---------+------+-----------------------------------------------------------------------------------------------------+
| Warning | 1815 | leading hint is inapplicable, check if the leading hint table has join conditions with other tables |
+---------+------+-----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

### LINKED ISSUE #63314: planner: join order algo can't select the lowest cost join order since join keys are eliminated by constant propagation
## Enhancement
See the example below, the best join order should be `(t1, t3, t2)`:
```
create table t1 (a int, b int, c int); -- 1000 rows
create table t2 (a int, b int, c int); -- 1000 rows
create table t3 (a int, b int, c int); -- 1 rows

insert into t1 select * from (
    with recursive x as (
        select 1 as a, 1 as b, 1 as c, 1 as n
        union all
        select 1 as a, 1 as b, 1 as c, n+1 from x where n < 1000
    )
    select a, b, c from x
) tt;


insert into t2 select * from (
    with recursive x as (
        select 1 as a, 1 as b, 1 as c, 1 as n
        union all
        select 1 as a, 1 as b, 1 as c, n+1 from x where n < 1000
    )
    select a, b, c from x
) tt;

insert into t3 values (1, 1, 1);

analyze table t1, t2, t3;

explain format='verbose' select 1 from
t1 left join t2 on t1.a=t2.a
   join t3 on t1.b=t3.b
where t1.a=1;
```

The best join order is `(t1, t3, t2)`, but the optimizer can't select it:
```
mysql> explain format='verbose' select /*+ leading(t1, t3) */ 1 from
    -> t1 left join t2 on t1.a=t2.a
    ->    join t3 on t1.b=t3.b
    -> where t1.a=1;
+----------------------------------+------------+-------------+-----------+---------------+----------------------------------------------+
| id                               | estRows    | estCost     | task      | access object | operator info                                |
+----------------------------------+------------+-------------+-----------+---------------+----------------------------------------------+
| Projection_11                    | 1000000.00 | 20181212.83 | root      |               | 1->Column#13                                 |
| └─HashJoin_13                    | 1000000.00 | 20081412.83 | root      |               | inner join, equal:[eq(test.t3.b, test.t1.b)] |
|   ├─TableReader_16(Build)        | 1.00       | 23.83       | root      |               | data:Selection_15                            |
|   │ └─Selection_15               | 1.00       | 294.10      | cop[tikv] |               | not(isnull(test.t3.b))                       |
|   │   └─TableFullScan_14         | 1.00       | 244.20      | cop[tikv] | table:t3      | keep order:false                             |
|   └─HashJoin_17(Probe)           | 1000000.00 | 119789.00   | root      |               | CARTESIAN left outer join                    |
|     ├─TableReader_24(Build)      | 1000.00    | 23830.67    | root      |               | data:Selection_23                            |
|     │ └─Selection_23             | 1000.00    | 294100.00   | cop[tikv] |               | eq(1, test.t2.a)                             |
|     │   └─TableFullScan_22       | 1000.00    | 244200.00   | cop[tikv] | table:t2      | keep order:false                             |
|     └─TableReader_21(Probe)      | 1000.00    | 31381.33    | root      |               | data:Selection_20                            |
|       └─Selection_20             | 1000.00    | 344000.00   | cop[tikv] |               | eq(test.t1.a, 1), not(isnull(test.t1.b))     |
|         └─TableFullScan_19       | 1000.00    | 244200.00   | cop[tikv] | table:t1      | keep order:false                             |
+----------------------------------+------------+-------------+-----------+---------------+----------------------------------------------+

mysql> explain format='verbose' select 1 from
    -> t1 left join t2 on t1.a=t2.a
    ->    join t3 on t1.b=t3.b
    -> where t1.a>0 and t1.a<2;
+------------------------------------+------------+-----------+-----------+---------------+------------------------------------------------------------+
| id                                 | estRows    | estCost   | task      | access object | operator info                                              |
+------------------------------------+------------+-----------+-----------+---------------+------------------------------------------------------------+
| Projection_12                      | 1000000.00 | 309432.83 | root      |               | 1->Column#13                                               |
| └─HashJoin_14                      | 1000000.00 | 209632.83 | root      |               | left outer join, equal:[eq(test.t1.a, test.t2.a)]          |
|   ├─HashJoin_16(Build)             | 1000.00    | 56291.83  | root      |               | inner join, equal:[eq(test.t3.b, test.t1.b)]               |
|   │ ├─TableReader_19(Build)        | 1.00       | 23.83     | root      |               | data:Selection_18                                          |
|   │ │ └─Selection_18               | 1.00       | 294.10    | cop[tikv] |               | not(isnull(test.t3.b))                                     |
|   │ │   └─TableFullScan_17         | 1.00       | 244.20    | cop[tikv] | table:t3      | keep order:false                                           |
|   │ └─TableReader_22(Probe)        | 1000.00    | 34708.00  | root      |               | data:Selection_21                                          |
|   │   └─Selection_21               | 1000.00    | 393900.00 | cop[tikv] |               | gt(test.t1.a, 0), lt(test.t1.a, 2), not(isnull(test.t1.b)) |
|   │     └─TableFullScan_20         | 1000.00    | 244200.00 | cop[tikv] | table:t1      | keep order:false                                           |
|   └─TableReader_25(Probe)          | 1000.00    | 30484.00  | root      |               | data:Selection_24                                          |
|     └─Selection_24                 | 1000.00    | 393900.00 | cop[tikv] |               | gt(test.t2.a, 0), lt(test.t2.a, 2), not(isnull(test.t2.a)) |
|       └─TableFullScan_23           | 1000.00    | 244200.00 | cop[tikv] | table:t2      | keep order:false                                           |
+------------------------------------+------------+-----------+-----------+---------------+------------------------------------------------------------+
```

But after propagating `t1.a=1` to `t1.a=t2.a`, the optimizer converted the join key `t1.a=t2.a` to `t1.a=1 and t2.a=1`, where the original join key is eliminated.
Join keys are crucial for join optimization like join-reorder, eliminating the original join key let the optimizer unable to generate a join order like `(t1, t3, t2)` for this query, since the `CARTESIAN LEFT OUTER JOIN` on `(t1, t2)` prevent the optimizer from putting them into the same join group with `t3`.
Image

And this problem also causes `leading` to not work properly:
```
mysql> explain format='verbose' select /*+ leading(t1, t3) */ 1 from
    -> t1 left join t2 on t1.a=t2.a
    ->    join t3 on t1.b=t3.b
    -> where t1.a=1;
...

mysql> show warnings;
+---------+------+------------------------------------------------------------------------------+
| Level   | Code | Message                                                                      |
+---------+------+------------------------------------------------------------------------------+
| Warning | 1815 | leading hint is inapplicable, check the join type or the join algorithm hint |
| Warning | 1815 | leading hint is inapplicable, check if the leading hint table is valid       |
+---------+------+------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #63314, close #60076

Problem Summary: planner: keep join keys for join optimization in constant propagation

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/casetest/join/join_test.go [hunk 1]
```diff
@@ -161,3 +161,88 @@ func TestJoinSimplifyCondition(t *testing.T) {
 				"  └─TableRowIDScan(Probe) 12.49 cop[tikv] table:t2 keep order:false, stats:pseudo"))
 	})
 }
+
+func TestKeepingJoinKeys(t *testing.T) {
```
Comment (hawkingrei) [inline pkg/planner/core/casetest/join/join_test.go:165]: Can we merge these two test cases? It can reduce some initialization for the test environment.

**Review by terry1purcell — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
lgtm

File: pkg/expression/constant_propagation.go [hunk 2]
```diff
@@ -880,13 +895,43 @@ func PropConstForOuterJoin(ctx exprctx.ExprContext, joinConds, filterConds []Exp
...
+			joinKeys = append(joinKeys, expr.Clone())
+		}
+	}
+	return
+}
+
+// isJoinKey returns true if this expression could be a join key like `t1.col = t2.col`.
+func isJoinKey(expr Expression, schema1, schema2 *Schema) bool {
+	binop, ok := expr.(*ScalarFunction)
+	if !ok || binop.FuncName.L != ast.EQ {
```
Comment (AilinKid) [inline pkg/expression/constant_propagation.go:926]: null eq should also work?
