### PR TITLE
br: reused table id is disabled when restore a brand-new cluster

### LINKED ISSUE #41333: br: v6.6 restore performance degradation 22%
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

import CPU increased from ~200% to 1000%

### 3. What did you see instead (Required)

image

### 4. What is your TiDB version? (Required)

v6.6

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?

Issue Number: close #41333 

Problem Summary:
when restoring to a brand-new cluster, reused table id was disabled, which caused restore to consume more resources.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/gluetidb/glue_test.go [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+
+	infos2 := []*model.TableInfo{}
+	infos2 = append(infos2, &model.TableInfo{
+		ID:   124,
+		Name: model.NewCIStr("table_id_new"),
+	})
+
+	tk.Session().SetValue(sessionctx.QueryString, "skip")
+
+	err = se.SplitBatchCreateTable(model.NewCIStr("test"), infos2, ddl.AllocTableIDIf(func(ti *model.TableInfo) bool {
```
Comment (YuJuncen) [inline br/pkg/gluetidb/glue_test.go:79]: Can we call `BatchCreateTable` directly here?

File: br/pkg/gluetidb/glue_test.go [hunk 2]
```diff
@@ -0,0 +1,89 @@
+// Copyright 2021 PingCAP, Inc.
```
Comment (YuJuncen) [inline br/pkg/gluetidb/glue_test.go:1]:
```suggestion
// Copyright 2023 PingCAP, Inc.
```

**Review by YuJuncen — APPROVED** [review]
rest lgtm

File: br/pkg/gluetidb/glue_test.go (hunk 1 above)
Comment (fengou1) [reply br/pkg/gluetidb/glue_test.go:80]: already tried, it always failure in ddl test check, it take too much time to investigate in ddl test package.

Comment (fengou1) [reply br/pkg/gluetidb/glue_test.go:81]: inTest is enabled, QueryString must be skip, otherwise the test shall be failure. BatchCreateTable will reset QueryString to something cause case failure.

File: br/pkg/gluetidb/glue.go [hunk 3]
```diff
@@ -226,11 +226,11 @@ func (gs *tidbSession) SplitBatchCreateTable(schema model.CIStr, info []*model.T
 			return err
 		}
 		mid := len(info) / 2
-		err = gs.SplitBatchCreateTable(schema, info[:mid])
+		err = gs.SplitBatchCreateTable(schema, info[:mid], cs...)
```
Comment (3pointer) [inline br/pkg/gluetidb/glue.go:229]: Maybe do not use optional arguments here?

File: br/pkg/gluetidb/glue_test.go [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+	store, dom := testkit.CreateMockStoreAndDomain(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists table_id_resued")
+	tk.MustExec("drop table if exists table_id_new")
+
+	d := dom.DDL()
+	require.NotNil(t, d)
+
+	infos1 := []*model.TableInfo{}
```
Comment (3pointer) [inline br/pkg/gluetidb/glue_test.go:42]: and also add a case that `len(infos)==0`

Comment (fengou1) [reply br/pkg/gluetidb/glue_test.go:43]: add new case in https://github.com/pingcap/tidb/pull/41358/commits/dd7388a722999c8999664332fbdf694ff03b866a

File: br/pkg/gluetidb/glue.go (hunk 3 above)
Comment (fengou1) [reply br/pkg/gluetidb/glue.go]: remote opt parameter in https://github.com/pingcap/tidb/pull/41358/commits/dd7388a722999c8999664332fbdf694ff03b866a

File: br/pkg/gluetidb/glue.go [hunk 5]
```diff
@@ -218,19 +219,29 @@ func (gs *tidbSession) CreatePlacementPolicy(ctx context.Context, policy *model.
...
+func (gs *tidbSession) SplitBatchCreateTable(schema model.CIStr, infos []*model.TableInfo, cs ...ddl.CreateTableWithInfoConfigurier) error {
 	var err error
 	d := domain.GetDomain(gs.se).DDL()
-	if err = d.BatchCreateTableWithInfo(gs.se, schema, info, append(cs, ddl.OnExistIgnore)...); kv.ErrEntryTooLarge.Equal(err) {
-		if len(info) == 1 {
+
+	err = d.BatchCreateTableWithInfo(gs.se, schema, infos, append(cs, ddl.OnExistIgnore)...)
+	failpoint.Inject("RestoreBatchCreateTableEntryTooLarge", func(val failpoint.Value) {
+		if val.(bool) {
+			if len(infos) > 1 {
```
Comment (3pointer) [inline br/pkg/gluetidb/glue.go:229]:
```suggestion
```

File: br/pkg/gluetidb/glue_test.go [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+	// keep/reused table id verification
+	tk.Session().SetValue(sessionctx.QueryString, "skip")
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/br/pkg/gluetidb/RestoreBatchCreateTableEntryTooLarge", "return(true)"))
+	err := se.SplitBatchCreateTable(model.NewCIStr("test"), infos, ddl.AllocTableIDIf(func(ti *model.TableInfo) bool {
+		return true
+	}))
+
+	require.NoError(t, err)
+
+	require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/br/pkg/gluetidb/RestoreBatchCreateTableEntryTooLarge"))
```
Comment (3pointer) [inline br/pkg/gluetidb/glue_test.go:146]: can we add a check that id has reused?

**Review by 3pointer — APPROVED** [review]
