### PR TITLE
ddl: Fix default value of a newly added enum column

### LINKED ISSUE #20741: The default value of a newly added enum column is set improperly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (id int primary key, c int);
insert into t (id, c) values (1, 1), (2, 2);

alter table t add column cc enum('a','b','c','d','e') not null;
update t set c = 2 where id = 1;
select * from t;
select * from t where cc = 0;
select * from t where cc = 1;
```

### 2. What did you expect to see? (Required)

```
mysql> update t set c = 2 where id = 1;
Query OK, 1 row affected (0.06 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from t;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    2 | a  |
|  2 |    2 | a  |
+----+------+----+
2 rows in set (0.05 sec)

mysql> select * from t where cc = 0;
Empty set (0.05 sec)

mysql> select * from t where cc = 1;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    2 | a  |
|  2 |    2 | a  |
+----+------+----+
2 rows in set (0.06 sec)

```

### 3. What did you see instead (Required)

```
mysql> update t set c = 2 where id = 1;
ERROR 1265 (01000): Data truncated for column '%s' at row %d

mysql> select * from t;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    1 |    |
|  2 |    2 |    |
+----+------+----+
2 rows in set, 1 warning (0.06 sec)

mysql> select * from t where cc = 0;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    1 |    |
|  2 |    2 |    |
+----+------+----+
2 rows in set, 1 warning (0.06 sec)

mysql> select * from t where cc = 1;
Empty set, 1 warning (0.06 sec)

```

### 4. What is your TiDB version? (Required)

master
release-4.0
## Score

- 600

## Mentor

- @wjhuang2016

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #20741 

Problem Summary:

The default value for new add enum column not perform correctly.

### What is changed and how it works?

What's Changed:

Check column's type if is Enum just use first element for default value.

### Related changes

- No

### Check List 

Tests 

- Integration test

Side effects

- No

### Release note 

- Set correct default value for new added enum column.

### CODE REVIEW

File: ddl/column.go [hunk 1]
```diff
@@ -1668,10 +1668,21 @@ func generateOriginDefaultValue(col *model.ColumnInfo) (interface{}, error) {
 	var err error
 	odValue := col.GetDefaultValue()
 	if odValue == nil && mysql.HasNotNullFlag(col.Flag) {
-		zeroVal := table.GetZeroValue(col)
-		odValue, err = zeroVal.ToString()
-		if err != nil {
-			return nil, errors.Trace(err)
+		switch col.Tp {
```
Comment (wjhuang2016) [inline ddl/column.go:1671]: I think `Set` also has this problem, could you fix it together?

Comment (blacktear23) [reply ddl/column.go:1671]: I just compared with mysql, current logic's result is same as mysql.

below is mysql result:

```
mysql> create table t (id int primary key, c int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t (id, c) values (1, 1), (2, 2);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> alter table t add column cc set('a','b','c','d') not null;
Query OK, 0 rows affected (0.05 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> update t set c = 2 where id = 1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from t;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    2 |    |
|  2 |    2 |    |
+----+------+----+
2 rows in set (0.00 sec)

mysql> select * from t where cc = 0;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    2 |    |
|  2 |    2 |    |
+----+------+----+
2 rows in set (0.00 sec)

mysql> select * from t where cc = 1;
Empty set (0.00 sec)

mysql> insert into t (id, c) values (3, 3);
ERROR 1364 (HY000): Field 'cc' doesn't have a default value
```

Then TiDB result:

```
mysql> create table t (id int primary key, c int);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t (id, c) values (1, 1), (2, 2);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> alter table t add column cc set('a','b','c','d') not null;
Query OK, 0 rows affected (0.01 sec)

mysql> update t set c = 2 where id = 1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from t;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    2 |    |
|  2 |    2 |    |
+----+------+----+
2 rows in set (0.00 sec)

mysql> select * from t where cc = 0;
+----+------+----+
| id | c    | cc |
+----+------+----+
|  1 |    2 |    |
|  2 |    2 |    |
+----+------+----+
2 rows in set (0.00 sec)

mysql> select * from t where cc = 1;
Empty set (0.00 sec)

mysql> insert into t (id, c) values (3, 3);
ERROR 1364 (HY000): Field 'cc' doesn't have a default value
```

**Comment by blacktear23** [comment]
@wjhuang2016 after I add some debug log I found when create table the `OriginDefaultValue` is `nil` and then insert some records it can use enum first element as default value. But when execute alter table add column, we should set `OriginDefaultValue` to enum's first element explicit. That makes me feel strange.

**Comment by wjhuang2016** [comment]
> @wjhuang2016 after I add some debug log I found when create table the `OriginDefaultValue` is `nil` and then insert some records it can use enum first element as default value. But when execute alter table add column, we should set `OriginDefaultValue` to enum's first element explicit. That makes me feel strange.

Yeah, this is an optimization. `Add column` can be done quickly.

**Comment by blacktear23** [comment]
> > @wjhuang2016 after I add some debug log I found when create table the `OriginDefaultValue` is `nil` and then insert some records it can use enum first element as default value. But when execute alter table add column, we should set `OriginDefaultValue` to enum's first element explicit. That makes me feel strange.
> 
> Yeah, this is an optimization. `Add column` can be done quickly.

Do we need add `OriginDefaultValue` when create table?

**Comment by wjhuang2016** [comment]
> > > @wjhuang2016 after I add some debug log I found when create table the `OriginDefaultValue` is `nil` and then insert some records it can use enum first element as default value. But when execute alter table add column, we should set `OriginDefaultValue` to enum's first element explicit. That makes me feel strange.
> > 
> > 
> > Yeah, this is an optimization. `Add column` can be done quickly.
> 
> Do we need add `OriginDefaultValue` when create table?

No

File: ddl/column.go (hunk 1 above)
Comment (wjhuang2016) [reply ddl/column.go:1658]: Please add these results as a test.

**Comment by blacktear23** [comment]
@wjhuang2016 PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by bb7133** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by bb7133** [comment]
PTAL @xhebox @tangenta

**Review by xhebox — APPROVED** [review]
LGTM
