### PR TITLE
expression: avoid padding 0 when implicitly cast to binary

### LINKED ISSUE #34823: Two table's comparison in `char(20)  between  binary(20) and binary(20)` is different from MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
drop table if exists t1;drop table if exists t2;
create table t1(a char(20));
create table t2(b binary(20), c binary(20));
insert into t1 value('-1');
insert into t2 value(0x2D31, 0x67);
insert into t2 value(0x2D31, 0x73);
select * from t1, t2 where t1.a between t2.b and t2.c;
```

### 2. What did you expect to see? (Required)
```mysql
mysql> select * from t1, t2 where t1.a between t2.b and t2.c;
Empty set (0.01 sec)
```
### 3. What did you see instead (Required)
```mysql
mysql> select * from t1, t2 where t1.a between t2.b and t2.c;
+------+--------------------------------------------+--------------------------------------------+
| a    | b                                          | c                                          |
+------+--------------------------------------------+--------------------------------------------+
| -1   | 0x2D31000000000000000000000000000000000000 | 0x7300000000000000000000000000000000000000 |
| -1   | 0x2D31000000000000000000000000000000000000 | 0x6700000000000000000000000000000000000000 |
+------+--------------------------------------------+--------------------------------------------+
2 rows in set (0.06 sec)
```
Tips : If it is a single table query, the result is the same as mysql.
```mysql
drop table if exists t;
create table t(a char(20), b binary(20), c binary(20));
insert into t value('-1', 0x2D31, 0x67);
insert into t value('-1', 0x2D31, 0x73);
select a from t where a between b and c;
```
```mysql
mysql> select a from t where a between b and c;
Empty set (0.05 sec)
```
### 4. What is your TiDB version? (Required)

Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: 828a255111cc7aab19754e092062d81e845123ff
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-05-17 23:02:16
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by Willendless**
### What problem does this PR solve?

Issue Number: close #34823 

#### Problem Summary:

For `between and` expression, **implicitly casting string charset to binary string** will pad 0 to the origin string, which causes different string comparison results from mysql. ~We can instead use `mysql.TypeVarString`to avoid this problem. In order to match the behavior of mysql, we can instead avoid doing implicit casting here. See [String::needs_conversion()](https://github.com/mysql/mysql-server/blob/8d8c986e5716e38cb776b627a8eee9e92241b4ce/sql-common/sql_string.cc#L271) in mysql-server for details.~

#### Modification rationale:

For one thing, we still need to build `cast` function to retain binary collation information till execution phase. For another, we can not keep using fixed length representation otherwise 0 padding will affect later string comparison result. Therefore, we need to use VarString type of cast here.

```mysql
drop table if exists t1;drop table if exists t2;
create table t1(a char(20));
create table t2(b binary(20), c binary(20));
insert into t1 value('-1');
insert into t2 value(0x2D31, 0x67);
insert into t2 value(0x2D31, 0x73);
select * from t1, t2 where t1.a between t2.b and t2.c;
```

// previously

```mysql
mysql> select * from t1, t2 where t1.a between t2.b and t2.c;
+------+--------------------------------------------+--------------------------------------------+
| a    | b                                          | c                                          |
+------+--------------------------------------------+--------------------------------------------+
| -1   | 0x2D31000000000000000000000000000000000000 | 0x7300000000000000000000000000000000000000 |
| -1   | 0x2D31000000000000000000000000000000000000 | 0x6700000000000000000000000000000000000000 |
+------+--------------------------------------------+--------------------------------------------+
2 rows in set (0.06 sec)
```

// now

```mysql
mysql> select * from t1, t2 where t1.a between t2.b and t2.c;
Empty set (0.01 sec)
```

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zanmato1984 — APPROVED** [review]
LGTM

File: expression/builtin_cast.go [hunk 1]
```diff
@@ -1830,7 +1831,10 @@ func BuildCastCollationFunction(ctx sessionctx.Context, expr Expression, ec *Exp
 	if expr.GetType().EvalType() != types.ETString {
 		return expr
 	}
-	if expr.GetType().GetCollate() == ec.Collation {
+	// Avoid padding 0 when cast character string to binary,
+	// which might affect string comparision result.
+	// See https://github.com/pingcap/tidb/issues/34823 for details.
+	if expr.GetType().GetCollate() == ec.Collation || ec.Charset == charset.CharsetBin {
```
Comment (xiongjiwei) [inline expression/builtin_cast.go:1837]: we can not just return if the target charset is `binary`. 

because we have had support charset `gbk`, if charset of `t1.a` is `gbk` it will have a `to_binary` function, after we return directly, it will be missed I think.

```sql
mysql> desc select * from t1, t2 where t1.a between t2.b and t2.c;
+-----------------------------+---------+-----------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| id                          | estRows | task      | access object | operator info                                                                                                                                 |
+-----------------------------+---------+-----------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| HashJoin_8                  | 4.00    | root      |               | CARTESIAN inner join, other cond:ge(cast(to_binary(test.t1.a), binary(20)), test.t2.b), le(cast(to_binary(test.t1.a), binary(20)), test.t2.c) |
| ├─TableReader_13(Build)     | 2.00    | root      |               | data:TableFullScan_12                                                                                                                         |
| │ └─TableFullScan_12        | 2.00    | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                                                                |
| └─TableReader_11(Probe)     | 2.00    | root      |               | data:TableFullScan_10                                                                                                                         |
|   └─TableFullScan_10        | 2.00    | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                                                                |
+-----------------------------+---------+-----------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
```

Comment (wjhuang2016) [reply expression/builtin_cast.go:1837]:
``` sql
create table t4(b binary(20), c char(20)) collate utf8mb4_general_ci;
create table t3(a char(20) ) collate utf8mb4_general_ci;
insert into t3 values ("a");
insert into t4 values (0x0, "A");
select * from t3, t4 where t3.a between t4.b and t4.c;
```
The result is wrong because t3.a doesn't convert to binary collation.

Comment (Willendless) [reply expression/builtin_cast.go:1837]: For `gbk`, tidb will build a `to_binary` is because `gbk` doesn't belong to legacy charset and when argument is legacy charset (for example the default charset utf8mb4_bin), there is no need to build `to_binary` function. [HandleBinaryLiteral](https://github.com/pingcap/tidb/blob/fb67ee441281b42032cf38d90ca726f3fdd7545f/expression/builtin_convert_charset.go#L309).

My change actually will still add the `to_binary` function when the code build function for `le/ge`.

```mysql
mysql> drop table t1;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t1(a char(20)) default charset gbk;
Query OK, 0 rows affected (0.00 sec)

mysql> desc select * from t1, t2 where t1.a between t2.b and t2.c;
+-------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object | operator info                                                                                             |
+-------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------------------------+
| Projection_9                  | 20000.00 | root      |               | test.t1.a, test.t2.b, test.t2.c                                                                           |
| └─HashJoin_11                 | 20000.00 | root      |               | CARTESIAN inner join, other cond:ge(to_binary(test.t1.a), test.t2.b), le(to_binary(test.t1.a), test.t2.c) |
|   ├─TableReader_13(Build)     | 2.00     | root      |               | data:TableFullScan_12                                                                                     |
|   │ └─TableFullScan_12        | 2.00     | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                            |
|   └─TableReader_15(Probe)     | 10000.00 | root      |               | data:TableFullScan_14                                                                                     |
|     └─TableFullScan_14        | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                            |
+-------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------------------------+
6 rows in set (0.01 sec)
```

Comment (Willendless) [reply expression/builtin_cast.go:1837]: As for 

```mysql
create table t4(b binary(20), c char(20)) collate utf8mb4_general_ci;
create table t3(a char(20) ) collate utf8mb4_general_ci;
insert into t3 values ("a");
insert into t4 values (0x0, "A");
select * from t3, t4 where t3.a between t4.b and t4.c;
```

It is the expected behavior that t3.a doesn't convert to binary collation since its charset (utf8mb4) is legacy...

Comment (wjhuang2016) [reply expression/builtin_cast.go:1837]: > As for
> 
> ```sql
> create table t4(b binary(20), c char(20)) collate utf8mb4_general_ci;
> create table t3(a char(20) ) collate utf8mb4_general_ci;
> insert into t3 values ("a");
> insert into t4 values (0x0, "A");
> select * from t3, t4 where t3.a between t4.b and t4.c;
> ```
> 
> It is the expected behavior that t3.a doesn't convert to binary collation since its charset (utf8mb4) is legacy...

The point is that we need to make t3.a <= t4.c use the binary collation.

Comment (Willendless) [reply expression/builtin_cast.go:1837]: Will `to_binary` padding 0 for other charsets? If so, then forcing t3.a <= t4.c to use the binary collation will cause mismatch between tidb and mysql. And mysql actually doesn't do conversion when target charset is `binary`.

**Review by wjhuang2016 — COMMENTED** [review]
It happens for in clause:
``` sql
mysql> show create table t1;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                               |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `a` char(20) DEFAULT NULL,
  `b` binary(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t1;
+------+--------------------------------------------+
| a    | b                                          |
+------+--------------------------------------------+
| -1   | 0x2D31000000000000000000000000000000000000 |
+------+--------------------------------------------+
1 row in set (0.00 sec)

mysql>  select * from t1 where t1.b in (t1.a, 3);
+------+--------------------------------------------+
| a    | b                                          |
+------+--------------------------------------------+
| -1   | 0x2D31000000000000000000000000000000000000 |
+------+--------------------------------------------+
1 row in set (0.00 sec)

mysql> desc  select * from t1 where t1.b in (t1.a, 3);
+-------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------+
| id                      | estRows | task      | access object | operator info                                                                         |
+-------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------+
| Selection_7             | 0.96    | root      |               | or(eq(test.t1.b, cast(test.t1.a, binary(20))), eq(cast(test.t1.b, double BINARY), 3)) |
| └─TableReader_6         | 1.00    | root      |               | data:TableFullScan_5                                                                  |
|   └─TableFullScan_5     | 1.00    | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                        |
+-------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------+
3 rows in set, 1 warning (0.00 sec)
```

**Review by wjhuang2016 — APPROVED** [review]
