### PR TITLE
expression: addition between `datetime` and `interval` is not compatible with Mysql

### LINKED ISSUE #9727: addition between `datetime` and `interval` is not compatible with Mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
SELECT "1900-01-01 00:00:00" + INTERVAL "100000000:214748364700" MINUTE_SECOND;
SELECT "1900-01-01 00:00:00" + INTERVAL 1<<37 SECOND;
SELECT "1900-01-01 00:00:00" + INTERVAL 1<<31 MINUTE;
SELECT "1900-01-01 00:00:00" + INTERVAL 1<<38 SECOND;
SELECT "1900-01-01 00:00:00" + INTERVAL 1<<33 MINUTE;
SELECT "1900-01-01 00:00:00" + INTERVAL 1<<30 HOUR;
SELECT "1900-01-01 00:00:00" + INTERVAL "1000000000:214748364700" MINUTE_SECOND;
```

2. What did you expect to see?
In Mysql
```
mysql> SELECT "1900-01-01 00:00:00" + INTERVAL "100000000:214748364700" MINUTE_SECOND;
+-------------------------------------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL "100000000:214748364700" MINUTE_SECOND |
+-------------------------------------------------------------------------+
| 8895-03-27 22:11:40                                                     |
+-------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<37 SECOND;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<37 SECOND |
+-----------------------------------------------+
| 6255-04-08 15:04:32                           |
+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<31 MINUTE;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<31 MINUTE |
+-----------------------------------------------+
| 5983-01-24 02:08:00                           |
+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<38 SECOND;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<38 SECOND |
+-----------------------------------------------+
| NULL                                          |
+-----------------------------------------------+
1 row in set, 1 warning (0.01 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<33 MINUTE;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<33 MINUTE |
+-----------------------------------------------+
| NULL                                          |
+-----------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<30 HOUR;
+---------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<30 HOUR |
+---------------------------------------------+
| NULL                                        |
+---------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL "1000000000:214748364700" MINUTE_SECOND;
+--------------------------------------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL "1000000000:214748364700" MINUTE_SECOND |
+--------------------------------------------------------------------------+
| NULL                                                                     |
+--------------------------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> SELECT "1900-01-01 00:00:00" + INTERVAL "100000000:214748364700" MINUTE_SECOND;
+-------------------------------------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL "100000000:214748364700" MINUTE_SECOND |
+-------------------------------------------------------------------------+
| 1607-09-22 00:12:43.145224                                              |
+-------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<37 SECOND;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<37 SECOND |
+-----------------------------------------------+
| 1607-09-22 00:12:43.145224                    |
+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<31 MINUTE;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<31 MINUTE |
+-----------------------------------------------+
| 1891-03-09 05:06:04.033139                    |
+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<38 SECOND;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<38 SECOND |
+-----------------------------------------------+
| 1607-09-22 00:12:43.145224                    |
+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<33 MINUTE;
+-----------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<33 MINUTE |
+-----------------------------------------------+
| 1864-09-26 20:24:16.132555                    |
+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL 1<<30 HOUR;
+---------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL 1<<30 HOUR |
+---------------------------------------------+
| 1635-07-15 09:02:00.994161                  |
+---------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT "1900-01-01 00:00:00" + INTERVAL "1000000000:214748364700" MINUTE_SECOND;
+--------------------------------------------------------------------------+
| "1900-01-01 00:00:00" + INTERVAL "1000000000:214748364700" MINUTE_SECOND |
+--------------------------------------------------------------------------+
| 1607-09-22 00:12:43.145224                                               |
+--------------------------------------------------------------------------+
1 row in set (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-212-g0681b8125
Git Commit Hash: 0681b8125080045ee0d4747ce61923164c6f2dd1
Git Branch: master
UTC Build Time: 2019-03-14 04:39:19
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by erjiaqing**
### What problem does this PR solve? 

Fix #9727 

### What is changed and how it works?

- Changes in `types/time.go` is to extract day from duration to avoid overflow.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: types/time.go [hunk 1]
```diff
@@ -1615,41 +1615,72 @@ func ExtractDurationNum(d *Duration, unit string) (int64, error) {
...
+		if lf-decimalPointPos >= 6 {
+			if dv, err = strconv.ParseInt(format[decimalPointPos+1:decimalPointPos+7], 10, 64); err != nil {
+				return 0, 0, 0, 0, ErrIncorrectDatetimeValue.GenWithStackByArgs(format)
+			}
+		} else {
+			if dv, err = strconv.ParseInt(format[decimalPointPos+1:]+"000000"[:6-(lf-decimalPointPos)], 10, 64); err != nil {
+				return 0, 0, 0, 0, ErrIncorrectDatetimeValue.GenWithStackByArgs(format)
+			}
+		}
+		if dv >= 500000 { // Round up
```
Comment (qw4990) [inline types/time.go]: Almost LGTM, and please add more test cases for this round up.

File: types/time.go [hunk 2]
```diff
@@ -1615,41 +1615,72 @@ func ExtractDurationNum(d *Duration, unit string) (int64, error) {
...
+			riv++
+		}
+	}
 	switch strings.ToUpper(unit) {
 	case "MICROSECOND":
-		return 0, 0, 0, fv * float64(gotime.Microsecond), nil
+		dayCount := riv / (3600000000 * 24)
```
Comment (lamxTyler) [inline types/time.go]: It is better to use constants for these magic numbers.

File: types/time.go [hunk 3]
```diff
@@ -1687,55 +1718,57 @@ func extractTimeValue(format string, index, cnt int) (int64, int64, int64, float
...
+	seconds %= 3600 * 24
+	return years, months, days, seconds*int64(gotime.Second) + microseconds*int64(gotime.Microsecond), nil
 }
 
-// ExtractTimeValue extracts time value from time unit and format.
-func ExtractTimeValue(unit string, format string) (int64, int64, int64, float64, error) {
+// ParseDurationValue parses time value from time unit and format.
+// Returns y years m months d days + n nanoseconds
+// Nanoseconds will no longer than one day.
+func ParseDurationValue(unit string, format string) (y int64, m int64, d int64, n int64, _ error) {
```
Comment (winoros) [inline types/time.go]: Is this time changing necessary?

Comment (erjiaqing) [reply types/time.go]: I think Parse is better than Extract since we do not only extract the value to variables, but also do something to avoid overflow.

File: types/time.go [hunk 4]
```diff
@@ -1615,41 +1615,74 @@ func ExtractDurationNum(d *Duration, unit string) (int64, error) {
...
+		} else {
+			if dv, err = strconv.ParseInt(format[decimalPointPos+1:]+"000000"[:6-(lf-decimalPointPos)], 10, 64); err != nil {
+				return 0, 0, 0, 0, ErrIncorrectDatetimeValue.GenWithStackByArgs(format)
+			}
+		}
+		if dv >= 500000 { // Round up, and we should keep 6 digits for microsecond, so dv should in [000000, 999999].
+			riv++
+		}
+	}
+	const dayLength = int64(24 * gotime.Hour)
```
Comment (qw4990) [inline types/time.go]:
```suggestion
const daySeconds = int64(24 * gotime.Hour / gotime.Second)
```

File: types/time.go [hunk 5]
```diff
@@ -1615,41 +1615,74 @@ func ExtractDurationNum(d *Duration, unit string) (int64, error) {
...
-	iv := int64(math.Round(fv))
+	riv := iv // Rounded integer value
 
+	dv := int64(0)
+	lf := len(format) - 1
+	// Has fraction part
+	if decimalPointPos < lf {
+		if lf-decimalPointPos >= 6 {
+			// MySQL rounds down to 1e-6.
+			if dv, err = strconv.ParseInt(format[decimalPointPos+1:decimalPointPos+7], 10, 64); err != nil {
```
Comment (lamxTyler) [inline types/time.go]: Should we raise a warning for truncated value?

Comment (erjiaqing) [reply types/time.go]: MySQL does not raise a warning here, I think it is just a rounding rule instead of truncated value.

Comment (lamxTyler) [reply types/time.go]:
```sql
MySQL [(none)]> SELECT 10000101000000 + INTERVAL "111111111111111111.499999999999" MICROSECOND;
+-------------------------------------------------------------------------+
| 10000101000000 + INTERVAL "111111111111111111.499999999999" MICROSECOND |
+-------------------------------------------------------------------------+
| 4520-12-21 05:31:51.111111                                              |
+-------------------------------------------------------------------------+
1 row in set, 1 warning (0.001 sec)

MySQL [(none)]> show warnings;
+---------+------+----------------------------------------------------------------------+
| Level   | Code | Message                                                              |
+---------+------+----------------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: '111111111111111111.499999999999' |
+---------+------+----------------------------------------------------------------------+
1 row in set (0.000 sec)

```

Comment (erjiaqing) [reply types/time.go]: Resolved, this error should not add here, in fact, when unit is not SECOND and get a decimal, we need raise a warning.
