### PR TITLE
executor: fix issue of index merge query scan index may sent redundancy RPC when enable paging

### LINKED ISSUE #54066: index merge query scan index may sent redundancy rpc when enable paging
## Enhancement

Related issue: #53827, Index Merge Reader has the same issue too.

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

```sql
drop table if exists t;
create table t (id int key auto_increment, b int, c int, index idx1 (b), index idx2(c));
insert into t () values (), (), (), (), (), (), (), ();
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
insert into t (b) select b from t;
update t set b = id, c = id;

-- set following variables to default value. 
set @@tidb_enable_paging=1;
set @@tidb_min_paging_size=128;
set @@tidb_max_chunk_size=1024;

explain analyze select /*+ USE_INDEX_MERGE(t, idx1, idx2) */ * from t where b > 0 or c > 0;
```

### 2. What did you see instead (Required)

```sql
> explain analyze select /*+ USE_INDEX_MERGE(t, idx1, idx2) */ * from t where b > 0 or c > 0;
+---------------------------+---------+---------+-----------+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------+---------+------+
| id                        | estRows | actRows | task      | access object          | execution info                                                                                                                                                                                                                                                                                                                          | operator info                                  | memory  | disk |
+---------------------------+---------+---------+-----------+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------+---------+------+
| IndexMerge_8              | 5555.56 | 1024    | root      |                        | time:2.83ms, loops:2, RU:4.930075, index_task:{fetch_handle:3.634626ms, merge:143.416µs}, table_task:{num:1, concurrency:5, fetch_row:598.25µs, wait_time:2.159291ms}                                                                                                                                                                   | type: union                                    | 71.0 KB | N/A  |
| ├─IndexRangeScan_5(Build) | 3333.33 | 1024    | cop[tikv] | table:t, index:idx1(b) | time:1.83ms, loops:2, cop_task: {num: 4, max: 836.1µs, min: 85.3µs, avg: 431.1µs, p95: 836.1µs, copr_cache_hit_ratio: 0.00, build_task_duration: 39.2µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:4, total_time:1.68ms}}, tikv_task:{proc max:752.2µs, min:73.1µs, avg: 398.6µs, p80:752.2µs, p95:752.2µs, iters:0, tasks:4} | range:(0,+inf], keep order:false, stats:pseudo | N/A     | N/A  |
| ├─IndexRangeScan_6(Build) | 3333.33 | 1024    | cop[tikv] | table:t, index:idx2(c) | time:1.76ms, loops:2, cop_task: {num: 4, max: 835.9µs, min: 78.5µs, avg: 412.3µs, p95: 835.9µs, copr_cache_hit_ratio: 0.00, build_task_duration: 46.7µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:4, total_time:1.6ms}}, tikv_task:{proc max:754.8µs, min:68.1µs, avg: 380.2µs, p80:754.8µs, p95:754.8µs, iters:0, tasks:4}  | range:(0,+inf], keep order:false, stats:pseudo | N/A     | N/A  |
| └─TableRowIDScan_7(Probe) | 5555.56 | 1024    | cop[tikv] | table:t                | time:480.3µs, loops:2, cop_task: {num: 1, max: 430.1µs, proc_keys: 0, copr_cache_hit_ratio: 0.00, build_task_duration: 9.58µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:1, total_time:420µs}}, tikv_task:{time:403.2µs, loops:0}                                                                                             | keep order:false, stats:pseudo                 | N/A     | N/A  |
+---------------------------+---------+---------+-----------+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------+---------+------+
```

Attention, `IndexRangeScan` sends 4 cop RPC to scan index.

```sql
IndexRangeScan_5(Build) | ... | table:t, index:idx1(b) | ... cop_task: {num: 4, ...}, rpc_info:{Cop:{num_rpc:4, ...
IndexRangeScan_6(Build) | ... | table:t, index:idx2(c) | ... cop_task: {num: 4, ...}, rpc_info:{Cop:{num_rpc:4, ...
```


### 3. What did you expect to see?

`IndexRangeScan` only send 1 RPC.

```sql
IndexRangeScan_5(Build) | ... | table:t, index:idx1(b) | ... cop_task: {num: 1, ...}, rpc_info:{Cop:{num_rpc:1, ...
IndexRangeScan_6(Build) | ... | table:t, index:idx2(c) | ... cop_task: {num: 1, ...}, rpc_info:{Cop:{num_rpc:1, ...
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

nightly: 42852ee632405bbdc3d2a22f1dbd4bad509047fc

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #54066

Problem Summary: As title said. see more detail in issue #54066

### What changed and how does it work?

Set scan index cop request min_page_size to initial batchSize.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/index_merge_reader.go [hunk 1]
```diff
@@ -395,11 +394,19 @@ func (e *IndexMergeReaderExecutor) startPartialIndexWorker(ctx context.Context,
 					SetIsStaleness(e.isStaleness).
 					SetFromSessionVars(e.Ctx().GetDistSQLCtx()).
 					SetMemTracker(e.memTracker).
-					SetPaging(e.paging).
```
Comment (crazycs520) [inline pkg/executor/index_merge_reader.go:398]: remove this useless code since `SetFromSessionVars` will set it too, and `e.paging` is set from session variable too.

**Review by winoros — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
