### PR TITLE
executor: fix load-data result when field term be the prefix of line term

### LINKED ISSUE #22578: `load data local infile` can only load one row when field-term be the prefix of line-term
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
bash>  cat t.csv
1|
2|
3|
4|
5|

mysql> create table t(a int);

bash>  mysql -u root -P 8012 -h 172.16.5.85 -D tpch_1 --local-infile=1 -e "load data local infile '/data1/jaysonhuang/tiflash/integrated/t.csv' into table t fields terminated by '|' lines terminated by '|\n'"

mysql> select * from t
```

### 2. What did you expect to see? (Required)
There are 5 rows in table `t`

### 3. What did you see instead (Required)
There is only 1 row in table `t`
```
mysql> select * from t;
+---+
| a |
+---+
| 1 |
+---+
```

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2063-gc54932640                    |
| Edition: Community                                                |
| Git Commit Hash: c54932640bcdd4dd7aeeb9ca6f4f41106974beb5         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-27 10:11:59                               |
| GoVersion: go1.13                                                 |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by lysu**
Signed-off-by: lysu <sulifx@gmail.com>

### What problem does this PR solve?

Issue Number: close #22578

Problem Summary:

`load data` will miss line when field-term be the prefix of line-term like issue said

### What is changed and how it works?

What's Changed, How it Works:

for most usage, check field-term first is more efficient, so we only need check line-term first when field-term be the prefix of line-term

- add test case for "field-term be the prefix of line-term" and "line-term be the prefix of field-term"
- extract common cmp logic and reorder check order when"field-term be the prefix of line-term"

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test 

Side effects

- n/a

### Release note 

- Fix wrong load-data result when field term be the prefix of line term 

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/22585)

### CODE REVIEW

File: executor/load_data.go [hunk 1]
```diff
@@ -408,39 +408,73 @@ func (e *LoadDataInfo) indexOfTerminator(bs []byte) int {
...
+			typ = fieldTermType
+			return
+		}
+		if restLen >= lineTermLen && bytes.Equal(bs[:lineTermLen], lineTerm) {
+			typ = lineTermType
+			return
+		}
+		return
+	}
+	if lineTermLen > fieldTermLen && bytes.HasPrefix(lineTerm, fieldTerm) {
```
Comment (cfzjywxk) [inline executor/load_data.go:429]: How about the `line term` and `filed term` are the same?

Comment (tiancaiamao) [reply executor/load_data.go:429]: So return the first line term is acceptable? anyway, the user input is misleading...

Comment (lysu) [reply executor/load_data.go:429]: no, current or before issue's behavior is different from mysql....

mysql will insert 2 rows for `|1|2|3|4` into `create table (a int, b int)`...it's very corner case - -

**Comment by tiancaiamao** [comment]
LGTM

**Comment by lysu** [comment]
last commit address field-term equal to line-term case, it's very dirty.

```
create table t(a int, b int);
```

load data

```
1|2|3
```
into t.

with `fields terminated by '|' lines terminated by '\n'`, result should be

```
row1: 1 2
```

but with `fields terminated by '|' lines terminated by '|'`, result should be

```
row1: 1 2
row2: 3 <nil>
```

@tiancaiamao @cfzjywxk  please help take look carefully...(today this PR need cherry-pick to 4.0 for new release)

File: executor/load_data.go [hunk 2]
```diff
@@ -608,60 +644,77 @@ func (e *LoadDataInfo) SetMessage() {
...
+		}
+		for i := 0; i < len(e.ColumnAssignments); i++ {
+			// eval expression of `SET` clause
+			d, err := expression.EvalAstExpr(e.Ctx, e.ColumnAssignments[i].Expr)
+			if err != nil {
+				e.handleWarning(err)
+				rows = append(rows, nil)
+				if !flattenMode {
+					return
+				}
```
Comment (cfzjywxk) [inline executor/load_data.go:700]: If it's not `flattenMode` should we return directly here?

Comment (lysu) [reply executor/load_data.go:700]: this keep same with old logic.. https://github.com/pingcap/tidb/pull/22585/files#diff-623a44defe93b702087a0127b2fce250a09a70e1e29840d435c19c865c0e1c5aL652

not flattenMode, should ignore remain columns in current line...

Comment (cfzjywxk) [reply executor/load_data.go:700]: A bit confused :frowning:, maybe it needs some refactor in the future.

**Comment by lysu** [comment]
current code struct isn't clear to handle field-term be same as line-term situation, I will do some code refactor in another PR to solve it

make another issue: https://github.com/pingcap/tidb/issues/22598 to trace that.

maybe we can merge 1st commit to fix bug that block tiflash CI first @cfzjywxk  PTAL if free

**Comment by cfzjywxk** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by JaySon-Huang — COMMENTED** [review]
LGTM
