### PR TITLE
expression, parser: fix issue #3691, cast compatibility

### LINKED ISSUE #645: Cast function should not fail.
`select cast("-1" as UNSIGNED)` should return `18446744073709551615`, but we get "constant -1 overflows bigint" error.

This is because we use `Convert` function for cast, but actually `cast` works differently than `convert`.
`cast("xxx" as DATETIME)` should returns NULL, but `Convert` such an invalid time string returns zero time.

### LINKED ISSUE #3691: Builtin function "CAST" compatibilities
select cast(cast(1-2 as unsigned) as signed integer);

MySQL: 
mysql> select cast(cast(1-2 as unsigned) as signed integer);
+-----------------------------------------------+
| cast(cast(1-2 as unsigned) as signed integer) |
+-----------------------------------------------+
|                                            -1 |
+-----------------------------------------------+
1 row in set (0.00 sec)

TiDB:
mysql> select cast(cast(1-2 as unsigned) as signed integer);
ERROR 1690 (22003): constant 18446744073709551615 overflows bigint

### PR DESCRIPTION
**Pull request by winkyao**
fix #3691, also fix #645

this pr will fail the jenkins, so should be merged together.

### CODE REVIEW

**Comment by winkyao** [comment]
@zz-jason @XuHuaiyu @jackysp PTAL

File: util/types/errors.go [hunk 1]
```diff
@@ -37,35 +39,46 @@ var (
 	ErrWrongFieldSpec = terror.ClassTypes.New(codeWrongFieldSpec, "Wrong Field Spec")
 	// ErrBadNumber is return when parsing an invalid binary decimal number.
 	ErrBadNumber = terror.ClassTypes.New(codeBadNumber, "Bad Number")
+	// ErrCastSignedOverflow is returned when positive out-of-range integer, and convert to it's negative complement
```
Comment (XuHuaiyu) [inline util/types/errors.go]: 1. s/ ErrCastSignedOverflow/ ErrCast**As**SignedOverflow be better?
2. add `.` at the end

File: util/types/datum.go [hunk 2]
```diff
@@ -1131,6 +1131,11 @@ func ProduceDecWithSpecifiedTp(dec *MyDecimal, tp *FieldType, sc *variable.State
 			}
 		}
 	}
+
+	if terror.ErrorEqual(err, ErrOverflow) {
```
Comment (winkyao) [inline util/types/datum.go]: @XuHuaiyu no, because the variable.session.go should not import "types" package, because "types" use "variable" package, it will cause circle import problem

**Comment by winkyao** [comment]
@XuHuaiyu @zz-jason PTAL

File: util/types/errors.go [hunk 3]
```diff
@@ -37,35 +39,46 @@ var (
...
+	codeWrongFieldSpec      terror.ErrCode = terror.ErrCode(mysql.ErrWrongFieldSpec)
+	codeTruncatedWrongValue terror.ErrCode = terror.ErrCode(mysql.ErrTruncatedWrongValue)
+	codeUnknown             terror.ErrCode = terror.ErrCode(mysql.ErrUnknown)
 )
 
 var (
-	msgOverflow = mysql.MySQLErrName[mysql.ErrDataOutOfRange]
+	msgOverflow             = mysql.MySQLErrName[mysql.ErrDataOutOfRange]
+	msgTruncatedWrongVal    = mysql.MySQLErrName[mysql.ErrTruncatedWrongValue]
+	msgCastSignedOverflow   = "Cast to signed converted positive out-of-range integer to it's negative complement"
```
Comment (XuHuaiyu) [inline util/types/errors.go]: s/ msgCastSignedOverflow/ msgCast**As**SignedOverflow
s/ msgCastNegIntToUnsigned/ msgCastNegInt**As**Unsigned

File: expression/builtin_cast.go [hunk 4]
```diff
@@ -636,6 +641,27 @@ type builtinCastStringAsIntSig struct {
 	baseIntBuiltinFunc
 }
 
+func (b *builtinCastStringAsIntSig) handleOverflow(origRes int64, origStr string, origErr error, isNegative bool) (res int64, err error) {
```
Comment (XuHuaiyu) [inline expression/builtin_cast.go]: may add a comment for this.

File: expression/builtin_cast_test.go [hunk 5]
```diff
@@ -75,6 +76,90 @@ func (s *testEvaluatorSuite) TestCast(c *C) {
 	c.Assert(len(res.GetString()), Equals, 5)
 	c.Assert(res.GetString(), Equals, string([]byte{'a', 0x00, 0x00, 0x00, 0x00}))
 
+	origSc := sc
+	sc.InSelectStmt = true
+	sc.OverflowAsWarning = true
+
+	// cast('18446744073709551616' as unsigned);
+	tp1 := types.NewFieldType(mysql.TypeLonglong)
```
Comment (XuHuaiyu) [inline expression/builtin_cast_test.go]: will this be more readable?
``` go
tp1 := &types.FieldType{
    Tp:
    Flag:
    Charset:
    ....
}
```

File: expression/builtin_cast_test.go [hunk 6]
```diff
@@ -75,6 +76,90 @@ func (s *testEvaluatorSuite) TestCast(c *C) {
...
+	c.Check(res.GetInt64(), Equals, int64(-2))
+
+	warnings = sc.GetWarnings()
+	lastWarn = warnings[len(warnings)-1]
+	c.Assert(terror.ErrorEqual(types.ErrCastAsSignedOverflow, lastWarn), IsTrue)
+
+	// create table t1(s1 time);
+	// insert into t1 values('11:11:11');
+	// select cast(s1 as decimal(7, 2)) from t1;
+	tpDecimal := types.NewFieldType(mysql.TypeNewDecimal)
```
Comment (XuHuaiyu) [inline expression/builtin_cast_test.go]: ditto

File: parser/parser.y [hunk 7]
```diff
@@ -5909,6 +5909,7 @@ IntegerType:
 OptInteger:
 	{}
 |	"INTEGER"
+|	"INT"
```
Comment (XuHuaiyu) [inline parser/parser.y]: add a test case in parser_test

File: sessionctx/variable/session.go [hunk 8]
```diff
@@ -422,6 +423,19 @@ func (sc *StatementContext) HandleTruncate(err error) error {
 	return err
 }
 
+// HandleOverflow treats ErrOverflow as warnings or returns the error bases on the StmtCtx.OverflowAsWarning state.
```
Comment (XuHuaiyu) [inline sessionctx/variable/session.go]: s/ bases/ based

**Comment by winkyao** [comment]
@XuHuaiyu @jackysp PTAL

**Comment by jackysp** [comment]
LGTM
