### PR TITLE
ddl: fix add a PK when the table's  pk_is_handle is true

### LINKED ISSUE #18333: could add primary key on a table which already has pk when set alter-primary-key  from false to true
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. set `alter-primary-key=false`  and create table with primary key.
``` sql
mysql > create table t1(a int primary key);
Query OK, 0 rows affected
Time: 0.374s
mysql > create table t2 (a int, b int);
Query OK, 0 rows affected
Time: 0.372s
mysql > create table t3 (a int primary key,  b int);
Query OK, 0 rows affected
Time: 0.389s
mysql > alter table t1 add primary key (a);
(1105, 'Unsupported add primary key, alter-primary-key is false')
mysql > alter table t2 add primary key (a);
(1105, 'Unsupported add primary key, alter-primary-key is false')
mysql > alter table t3 add primary key (b);
(1105, 'Unsupported add primary key, alter-primary-key is false')
```

2. set `alter-primary-key=true` and add primary
```sql
alter table t1 add primary key (a);
alter table t2 add primary key (a);
alter table t3 add primary key (b);
```

### 2. What did you expect to see? (Required)
Can not add primary key while a table already has primary key after setting `alter-primary-key = true`
```sql
mysql > alter table t1 add primary key (a);
(1068, 'Multiple primary key defined')
mysql > alter table t2 add primary key (a);
Query OK, 0 rows affected
Time: 0.139s
mysql > alter table t3 add primary key (b);
(1068, 'Multiple primary key defined')
mysql root@172.16.4.131:test>

```
### 3. What did you see instead (Required)
could add primary key  multiple.
```sql
mysql > alter table t1 add primary key (a);
Query OK, 0 rows affected
Time: 0.745s
mysql > alter table t2 add primary key (a);
Query OK, 0 rows affected
Time: 0.822s
mysql > alter table t3 add primary key (b);
Query OK, 0 rows affected
Time: 0.867s
mysql > show create table t1;
+-------+-------------------------------------------------------------+
| Table | Create Table                                                |
+-------+-------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (                                         |
|       |   `a` int(11) NOT NULL,                                     |
|       |   PRIMARY KEY (`a`),                                        |
|       |   PRIMARY KEY (`a`)                                         |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------+

1 row in set
Time: 0.073s
mysql > show create table t2;
+-------+-------------------------------------------------------------+
| Table | Create Table                                                |
+-------+-------------------------------------------------------------+
| t2    | CREATE TABLE `t2` (                                         |
|       |   `a` int(11) NOT NULL,                                     |
|       |   `b` int(11) DEFAULT NULL,                                 |
|       |   PRIMARY KEY (`a`)                                         |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------+

1 row in set
Time: 0.020s
mysql > show create table t3;
+-------+-------------------------------------------------------------+
| Table | Create Table                                                |
+-------+-------------------------------------------------------------+
| t3    | CREATE TABLE `t3` (                                         |
|       |   `a` int(11) NOT NULL,                                     |
|       |   `b` int(11) NOT NULL,                                     |
|       |   PRIMARY KEY (`b`),                                        |
|       |   PRIMARY KEY (`b`)                                         |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------+
```
### 4. Affected version (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v3.0.15-31-g332f2d4                              |
| Git Commit Hash: 332f2d44e4ed2ff6a7a6f049eb1f21c9a93ce89b         |
| Git Branch: HEAD                                                  |
| UTC Build Time: 2020-07-01 06:51:33                               |
| GoVersion: go version go1.13.7 linux/amd64                        |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+

```

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close #18333 

Problem Summary:
 We can't add a primary key when the table's pk_is_handle is true.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
If the table's PKIsHandle is true, we can't add a primary key to this table.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Fix add a primary key when the table's  pk_is_handle is true

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -4241,7 +4241,9 @@ func (d *ddl) CreatePrimaryKey(ctx sessionctx.Context, ti ast.Ident, indexName m
 	}
 
 	indexName = model.NewCIStr(mysql.PrimaryKeyName)
-	if indexInfo := t.Meta().FindIndexByName(indexName.L); indexInfo != nil {
+	if indexInfo := t.Meta().FindIndexByName(indexName.L); indexInfo != nil ||
+		// If the table's PKIsHandle is true, it also means that this table has a primary key.
+		t.Meta().PKIsHandle {
```
Comment (zimulala) [inline ddl/ddl_api.go:4246]: If we support the clustered index, I think need to add a check for `IsCommonHandle`. I don't do it, because other places also don't handle this problem.

Comment (tangenta) [reply ddl/ddl_api.go:4246]: We had better extract these usages into a separate function.
