### PR TITLE
resourcemanager: avoid to schedule when no task is in the pool

### LINKED ISSUE #41094: "overclock goroutine pool" message floods logs
## Bug Report

When running `./bin/tidb-server` (unistore):

```
[2023/02/06 09:49:28.881 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:28.981 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.080 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.181 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.281 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.381 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.481 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.581 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.682 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.781 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.881 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
[2023/02/06 09:49:29.981 +01:00] [INFO] [schedule.go:62] ["[resource manager] overclock goroutine pool"] ["origin concurrency"=33] [concurrency=34] [name=backfill]
```

These are happening multiple times a second. If this happens in production the log volume wouldn't be acceptable. When developing TiDB this makes it harder to see other important log messages.

This seem to have been introduced with #39886

### What is your TiDB version? (Required)

```
$ ./bin/tidb-server -V
Release Version: v6.6.0-alpha-373-g308aaba6b
Edition: Community
Git Commit Hash: 308aaba6b8221fc5781730bd8142e807aa716f07
Git Branch: master
UTC Build Time: 2023-02-06 08:41:04
GoVersion: go1.19.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #41094

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
   test tidb with unistore. It will not print too many logs.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: resourcemanager/schedule.go [hunk 1]
```diff
@@ -31,13 +31,15 @@ func (r *ResourceManager) schedule() {
...
 
 func (r *ResourceManager) schedulePool(pool *util.PoolContainer) scheduler.Command {
-	for _, sch := range r.scheduler {
-		cmd := sch.Tune(pool.Component, pool.Pool)
-		switch cmd {
-		case scheduler.Hold:
-			continue
-		default:
-			return cmd
+	if pool.Pool.Running() != 0 {
```
Comment (YangKeao) [inline resourcemanager/schedule.go:34]: Only a style suggestion:

```
if pool.Pool.Running() == 0 {
    return scheduler.Hold
}

xxxxx
```

But this one is also fine, not a big problem.

**Review by YangKeao — APPROVED** [review]

File: resourcemanager/schedule.go (hunk 1 above)
Comment (hawkingrei) [reply resourcemanager/schedule.go]: Done

**Review by Yisaer — APPROVED** [review]
