### PR TITLE
ddl: Do not consider the clustered index when checking the length of the secondary index

### LINKED ISSUE #29658: ddl:creating a secondary index may isn't compatible with mysql when the table contains cluster index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t9(
id1 varchar(3000),
id2 varchar(3000),
primary key (id1) CLUSTERED,
key id2_key(id2)
) charset = latin1;

### 2. What did you expect to see? (Required)
success

### 3. What did you see instead (Required)
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes

### 4. What is your TiDB version? (Required)
Release Version: v5.0.0
Edition: Community
Git Commit Hash: bdac0885cd11bdf571aad9353bfc24e13554b91c
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-04-06 16:36:29
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by TonsnakeLin**
### What problem does this PR solve?

Issue Number: close #29658 

Problem Summary:

### What is changed and how it works?
It calculates the length of the secondary index to check constraint by the length of index self and the cluster index length before(ddl: fix secondary index len check for clustered index #23710) . Now it calculates the length of the secondary index only by self.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by TonsnakeLin** [comment]
@cfzjywxk @youjiali1995 @sticnarf PTAL

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -4274,40 +4254,30 @@ func checkColumnWithIndexConstraint(tbInfo *model.TableInfo, originalCol, newCol
...
-	var clusteredPkLen int
-	if tbInfo.IsCommonHandle {
-		var err error
-		clusteredPkLen, err = indexColumnsLen(columns, pkIndex.Columns)
-		if err != nil {
-			return err
-		}
-	}
 
-	checkOneIndex := func(indexInfo *model.IndexInfo, pkLenAppendToKey int, skipCheckIfNotModify bool) (modified bool, err error) {
```
Comment (sticnarf) [inline ddl/ddl_api.go:4286]: Now, it seems the return value `modified` is not used. Can it be removed?

Comment (TonsnakeLin) [reply ddl/ddl_api.go:4286]: yes， I think so.

**Comment by xiongjiwei** [comment]
if we just pass the check, the key will be longer than the tikv key length limit.

**Comment by sticnarf** [comment]
> if we just pass the check, the key will be longer than the tikv key length limit.

TiKV is going to raise the default key length limit: https://github.com/tikv/tikv/pull/11331

We should merge this PR later than that TiKV PR.

**Review by wjhuang2016 — COMMENTED** [review]
MySQL does consider the length of the clusterd index.
In the original issue, MySQL returns OK because the charset is latin1, which is 1 byte per character. But TiDB uses 4 bytes, that's why TiDB returns an error.

**Comment by cfzjywxk** [comment]
@wjhuang2016 
Do you think there's other cases that should be refactored accordingly?

**Comment by TonsnakeLin** [comment]
@youjiali1995  @sticnarf  please review or approve, thanks

**Review by wjhuang2016 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
