### PR TITLE
br: add keyspace-aware GC safepoint support for backup and restore

### LINKED ISSUE #65482: br: add keyspace-aware GC safepoint support for backup and restore
## Problem

When running BR (Backup & Restore) with keyspace enabled, the current GC safepoint management uses the deprecated global `UpdateServiceGCSafePoint` API which doesn't support keyspace isolation. This causes BR operations to fail or behave incorrectly in multi-tenant keyspace scenarios.

## Root Cause

The existing BR code directly calls `pd.Client.UpdateServiceGCSafePoint()` which operates at the global cluster level, not per-keyspace. In keyspace mode, BR should use the new `SetGCBarrier` / `DeleteGCBarrier` APIs to set per-keyspace GC barriers.

## Solution

Implement a GC manager abstraction layer that:
1. Automatically detects whether keyspace mode is enabled (via `--keyspace-name` parameter)
2. For non-keyspace mode: uses the existing global `UpdateServiceGCSafePoint` API (backward compatible)
3. For keyspace mode: uses the new `SetGCBarrier` / `DeleteGCBarrier` APIs

## Changes

- Add `gc_manager.go`: Factory and wrapper functions
- Add `gc_manager_unified.go`: Implementation for non-keyspace mode  
- Add `gc_manager_keyspace.go`: Implementation for keyspace mode
- Add `gc_manager_test.go`: Unit tests with >85% coverage
- Update `backup.go`, `restore.go`, `stream.go`, etc. to use new `*WithStorage` wrapper functions

## Testing

- Unit tests covering both keyspace and non-keyspace scenarios
- Tests verify correct API selection based on keyspace configuration
- Backward compatibility verified for existing non-keyspace deployments

## Related

- PD API: `GCStatesClient.SetGCBarrier()` / `DeleteGCBarrier()`

### PR DESCRIPTION
**Pull request by RidRisR**
### What problem does this PR solve?

Issue Number: close #65482

Problem Summary:

BR currently uses the deprecated global GC safepoint API (`pd.Client.UpdateServiceGCSafePoint`) which doesn't support keyspace isolation. When users specify `--keyspace-name` parameter, BR should use the new per-keyspace GC barrier API (`GCStatesClient.SetGCBarrier` / `DeleteGCBarrier`) instead.

### What changed and how does it work?

This PR introduces a GC manager abstraction layer that automatically selects the appropriate GC implementation based on user's `--keyspace-name` parameter:

**New files:**
- `gc_manager.go`: Factory function and wrapper functions
- `gc_manager_unified.go`: Non-keyspace implementation using deprecated global API (backward compatible)
- `gc_manager_keyspace.go`: Keyspace implementation using new GC barrier API

**Design:**
```
GCSafePointManager (interface)
├── UnifiedGCManager    (--keyspace-name NOT provided)
│   └── Uses pd.Client.UpdateServiceGCSafePoint (deprecated, global)
└── KeyspaceGCManager   (--keyspace-name IS provided)
    └── Uses GCStatesClient.SetGCBarrier/DeleteGCBarrier (per-keyspace)
```

**Updated callers:**
- `backup.go`: Use `StartServiceSafePointKeeperWithStorage`
- `restore.go`: Use `UpdateServiceSafePointWithStorage`
- `stream.go`: Use `StartServiceSafePointKeeperWithStorage`
- `backup_ebs.go`, `restore_data.go`, `log_client/client.go`: Updated accordingly

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: br/pkg/gc/manager.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+	SetServiceSafePoint(ctx context.Context, sp BRServiceSafePoint) error
+
+	// DeleteServiceSafePoint removes the service safe point.
+	DeleteServiceSafePoint(ctx context.Context, sp BRServiceSafePoint) error
+}
+
+// NewManager creates a GC Manager based on the storage configuration.
+// If keyspace is configured, it returns a keyspace-aware manager.
+// Otherwise, it returns a global manager.
+func NewManager(pdClient pd.Client, storage kv.Storage) (Manager, error) {
```
Comment (YuJuncen) [inline br/pkg/gc/manager.go]: Why not just accept `pdClient` and `keyspaceID`? It seems other fields in `storage` are not used.

File: br/pkg/gc/mock_test.go [hunk 2]
```diff
@@ -0,0 +1,273 @@
...
+	require.Nil(t, barrier, "barrier %q should not exist", barrierID)
+}
+
+// ============================================================================
+// Simple Mock Manager for Keeper Tests
+// ============================================================================
+
+// mockManager implements gc.Manager interface for keeper tests.
+// This is a lightweight mock that doesn't depend on MockPD.
+type mockManager struct {
```
Comment (YuJuncen) [inline br/pkg/gc/mock_test.go:149]: No need to mock a manager as we have already implemented mocked PD Client. Just create a real manager with mock PD client.

File: br/pkg/gc/manager_test.go [hunk 3]
```diff
@@ -0,0 +1,378 @@
...
+		sp := gc.BRServiceSafePoint{
+			ID:       "br-test-delete",
+			TTL:      300,
+			BackupTS: 1000,
+		}
+		err = mgr.SetServiceSafePoint(ctx, sp)
+		require.NoError(t, err)
+
+		gcClient := pdClient.getGCStatesClientTracking(keyspaceID)
+		require.Equal(t, 1, gcClient.getSetGCBarrierCalls())
```
Comment (YuJuncen) [inline br/pkg/gc/manager_test.go]: Don't use number of calls to check whether safe point was set. Directly check whether this safe point was set in the mock service.

File: br/pkg/gc/manager_test.go [hunk 4]
```diff
@@ -0,0 +1,378 @@
...
+		state, err := pdClient.GetGCStatesClient(keyspaceID).GetGCState(ctx)
+		require.NoError(t, err)
+		requireBarrier(t, state, "br-test-to-delete", sp.BackupTS-1)
+
+		// Delete the barrier
+		err = mgr.DeleteServiceSafePoint(ctx, sp)
+		require.NoError(t, err)
+
+		gcClient := pdClient.getGCStatesClientTracking(keyspaceID)
+		require.Equal(t, 1, gcClient.getDeleteGCBarrierCalls())
```
Comment (YuJuncen) [inline br/pkg/gc/manager_test.go]: Ditto. IMO those "call tracking" functions are not actual necessary.

File: br/pkg/gc/manager_test.go (hunk 3 above)
Comment (RidRisR) [reply br/pkg/gc/manager_test.go]: All deleted

File: br/pkg/gc/mock_test.go (hunk 2 above)
Comment (RidRisR) [reply br/pkg/gc/mock_test.go:149]: It is for counting the number of ttl update in keeper and ingest err.

File: br/pkg/gc/manager_test.go (hunk 4 above)
Comment (RidRisR) [reply br/pkg/gc/manager_test.go]: OK

File: br/pkg/gc/manager.go (hunk 1 above)
Comment (RidRisR) [reply br/pkg/gc/manager.go]: Great idea, and by this way, the backward interfaces could be deleted too.

**Review by YuJuncen — APPROVED** [review]

File: tests/realtikvtest/brietest/gc_keyspace_test.go [hunk 5]
```diff
@@ -0,0 +1,100 @@
+// Copyright 2025 PingCAP, Inc.
```
Comment (Leavrth) [inline tests/realtikvtest/brietest/gc_keyspace_test.go]:
```suggestion
// Copyright 2026 PingCAP, Inc.
```

**Review by Leavrth — APPROVED** [review]
