### PR TITLE
ddl: add states to remove old objects during modifying column

### LINKED ISSUE #60264: TestMultiSchemaModifyColumn shows index inconsistency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Check out c3ea51e172a0f2688bf7a3b16b78fff38971efba , `make failpoint-enable` and run TestMultiSchemaModifyColumn.

### 2. What did you expect to see? (Required)
Test passing

### 3. What did you see instead (Required)
If adding `admin check table t` it fails with:
[admin:8223]data inconsistency in table: t, index: uk_b, handle: 10, index-values:"" != record-values:"handle: 10, values: [KindNull <nil>]"
otherwise it fails with:
```
[2025/03/25 23:10:52.587 +01:00] [INFO] [multi_domain_test.go:1209] [HaveEntriesForTableIndex] [key=7480000000000000705f69800000000000000101203031312e353000fe] [value=08800001000000020800203031312e353020000000000000000b]
[2025/03/25 23:10:52.587 +01:00] [INFO] [multi_domain_test.go:1214] [HaveEntriesForTableIndex] [tableID=112] [indexID=1] [count=1]
    multi_domain_test.go:902: 
        	Error Trace:	/repos/tidb/pkg/ddl/tests/partition/multi_domain_test.go:902
        	            				/repos/tidb/pkg/ddl/tests/partition/multi_domain_test.go:1140
        	            				/repos/tidb/pkg/ddl/tests/partition/multi_domain_test.go:935
        	            				/repos/tidb/pkg/ddl/tests/partition/multi_domain_test.go:643
        	Error:      	Should be false
        	Test:       	TestMultiSchemaModifyColumn
        	Messages:   	Index id range [1,2) for table id 112 has still entries!
```

### 4. What is your TiDB version? (Required)

Similar to current master.
```
tidb_version(): Release Version: v9.0.0-alpha-506-gc3ea51e172
Edition: Community
Git Commit Hash: c3ea51e172a0f2688bf7a3b16b78fff38971efba
Git Branch: non-clustered-reorg-duplicate-_tidb_rowid-fix
UTC Build Time: 2025-03-25 21:57:39
GoVersion: go1.24.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore
```

### LINKED ISSUE #62531: Meet "Data is corrupted, missing data for NOT NULL column" when running "delete from xxx" along with modify column concurrenty
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

1. Setup cluster by `tiup playground`

```
tiup playground v8.5.2 --kv 3 --pd 1 --db 1 --tiflash 0
```

2. Run the program with concurrent DML & DDL workload

Source code: https://github.com/pingyu/ddl-and-delete/blob/main/main.go

```
go run main
```


### 2. What did you expect to see? (Required)

Nothing wrong.

### 3. What did you see instead (Required)

After running for 10s ~ 20s, meet the error:

`2025/07/21 14:43:01 Worker 12 - Delete error: delete failed: Error 1105 (HY000): [components/tidb_query_executors/src/table_scan_executor.rs:425]: Data is corrupted, missing data for NOT NULL column (offset = 1)`

tidb.log:

`[2025/07/21 14:43:01.806 +08:00] [WARN] [session.go:834] ["commit failed"] [conn=2587885920] [session_alias=] ["finished txn"="Txn{state=invalid}"] [error="[tikv:10000][components/tidb_query_executors/src/table_scan_executor.rs:425]: Data is corrupted, missing data for NOT NULL column (offset = 1)"]`

`[2025/07/21 14:43:01.807 +08:00] [WARN] [session.go:2162] ["run statement failed"] [conn=2587885920] [session_alias=] [schemaVersion=90] [error="[tikv:10000][components/tidb_query_executors/src/table_scan_executor.rs:425]: Data is corrupted, missing data for NOT NULL column (offset = 1)"] [session="{\n  \"currDBName\": \"\",\n  \"id\": 2587885920,\n  \"preparedStmtCount\": 1,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": {\n    \"Username\": \"root\",\n    \"Hostname\": \"127.0.0.1\",\n    \"CurrentUser\": false,\n    \"AuthUsername\": \"root\",\n    \"AuthHostname\": \"%\",\n    \"AuthPlugin\": \"mysql_native_password\"\n  }\n}"]
[2025/07/21 14:43:01.808 +08:00] [WARN] [session.go:808] [sql] [conn=2587885960] [session_alias=] [label=general] [error="[kv:9007]Write conflict, txnStartTS=459559451153661954, conflictStartTS=459559451153661962, conflictCommitTS=459559451153661965, key={tableID=112, tableName=uniq.rows, handle=24948}, originalKey=7480000000000000705f728000000000006174, primary={tableID=112, tableName=uniq.rows, handle=24911}, originalPrimaryKey=7480000000000000705f72800000000000614f, reason=Optimistic [try again later]"] [txn="Txn{state=invalid}"]`

`[2025/07/21 14:43:01.810 +08:00] [INFO] [conn.go:1184] ["command dispatched failed"] [conn=2587885920] [session_alias=] [connInfo="id:2587885920, addr:127.0.0.1:42504 status:10, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:0, autocommit:1"] [sql="DELETE FROM `uniq`.`rows` WHERE val0 IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [arguments: (191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290)]"] [txn_mode=PESSIMISTIC] [timestamp=459559450288324618] [err="[tikv:10000][components/tidb_query_executors/src/table_scan_executor.rs:425]: Data is corrupted, missing data for NOT NULL column (offset = 1)\nDELETE FROM `uniq`.`rows` WHERE val0 IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [arguments: (191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290)]\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).executePreparedStmtAndWriteResult\n\t/workspace/source/tidb/pkg/server/conn_stmt.go:322\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).executePlanCacheStmt\n\t/workspace/source/tidb/pkg/server/conn_stmt.go:234\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmtExecute\n\t/workspace/source/tidb/pkg/server/conn_stmt.go:225\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\n\t/workspace/source/tidb/pkg/server/conn.go:1405\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\n\t/workspace/source/tidb/pkg/server/conn.go:1147\ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn\n\t/workspace/source/tidb/pkg/server/server.go:741\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"]`


### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

```sql
MySQL [uniq]> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.5.2
Edition: Community
Git Commit Hash: f43a13324440f92209e2a9f04c0bbe9cf763978d
Git Branch: HEAD
UTC Build Time: 2025-05-29 03:30:55
GoVersion: go1.23.8
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)

MySQL [uniq]>
```

[ddl-tidb-1.log.zip](https://github.com/user-attachments/files/21341694/ddl-tidb-1.log.zip)

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #60264, close #62531

Problem Summary:

```sql
-- origin schema
create table t (a int primary key, b varchar(255), key k_b (b))
-- ddl
alter table t modify column b int unsigned not null;

-- write-reorg -> public
-- non-owner schema (_Col$ and _Idx$ are not visible to users)
create table t (a int primary key, b int, _Col$_b varchar(255), key k_b (b), key _Idx$_k_b (_Col$_b));
-- owner schema
create table t (a int primary key, b int, key k_b (b));

-- owner insert (OLD INDEX IS NOT MAINTAINED!)
insert into t values (10, " 09.60 ");

-- non-owner select
select * from t where a = 10;
10 <nil>

-- non-owner admin check
admin check table t;
[admin:8223]data inconsistency in table: t, index: k_b, handle: 10, index-values:"" != record-values:"handle: 10, values: [KindNull <nil>]"
```

The root cause is that the assumption of "two adjacent schema versions are compatible" is broken for modifying columns covered with indexes:
- Non-owner TiDB has schema version `n-1`. Only old indexes and old columns are visible.
- Owner TiDB has schema version `n`. Only new indexes are visible.

When owner TiDB inserts or deletes a record, only new indexes will be maintained. If you run `SELECT` or `ADMIN CHECK` on non-owner TiDB with schema version `n-1`, either the data has one more record than the index, or the index has one more record than the data, depending on whether the non-owner node executes an insert or delete statement.

This issue doesn't happen on `ADD INDEX` because non-owner TiDBs don't have an "old" index. Any `SELECT` statements will use `TableScan` instead of `IndexLookup`. There is no such chance to see inconsistent data on non-owner TiDBs.

### What changed and how does it work?

Before removing public columns/indexes, we should follow the path `public` -> `write-only` -> `delete-only` -> `none`. In the above case, **owner TiDB is still aware of the old index** (which is in `write-only` state). As long as it maintains the old index mutations, there is no data inconsistent issue.

- Break changing column step `write-reorg` -> `public` into multiple steps:
  - changing column `write-reorg`, old column & indexes `public`
  - changing column `public`, old column & indexes `write-only`
  - changing column `public`, old column & indexes `delete-only`
  - changing column `public`, old column & indexes `none`(removed)
- Don't use column name to locate "old column" anymore. This PR changes to use column ID, and it is persisted to job arguments after the first execution.
- Add an internal column / index name prefix `_Tomestone$_` to represent the objects that need to be removed eventually.

Example 1
```sql
create table t (a int not null default 1, b int default 2, c int not null default 0, primary key(c), index idx(b), index idx1(a), index idx2(b, c));

alter table t change column b bb mediumint first;
```
image

Example 2
```sql
create table t (a int, b int, c int, index i1(a), index i2(b), index i3(c), index i4(a, b), index i5(a, b, c));

alter table t modify column a tinyint, modify column b tinyint, modify column c tinyint;
```
image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Run the [script](https://github.com/pingyu/ddl-and-delete/blob/main/main.go) mentioned in #62531 for 20 min, no data inconsistent issue found.
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/modify_column.go [hunk 1]
```diff
@@ -525,31 +555,49 @@ func (w *worker) doModifyColumnTypeWithData(
...
+			}
 
-		// Finish this job.
-		job.FinishTableJob(model.JobStateDone, model.StatePublic, ver, tblInfo)
-		// Refactor the job args to add the old index ids into delete range table.
-		args.IndexIDs = rmIdxs
-		args.PartitionIDs = getPartitionIDs(tblInfo)
-		job.FillFinishedArgs(args)
+			// Finish this job.
+			job.FinishTableJob(model.JobStateDone, model.StatePublic, ver, tblInfo)
```
Comment (wjhuang2016) [inline pkg/ddl/modify_column.go:600]: Why call FinishTableJob before updateVersionAndTableInfo?

File: pkg/ddl/modify_column.go [hunk 2]
```diff
@@ -525,31 +555,49 @@ func (w *worker) doModifyColumnTypeWithData(
...
+			// Refactor the job args to add the old index ids into delete range table.
+			rmIdxs := append(removedIdxIDs, args.RedundantIdxs...)
+			args.IndexIDs = rmIdxs
+			args.PartitionIDs = getPartitionIDs(tblInfo)
+			job.FillFinishedArgs(args)
+			ver, err = updateVersionAndTableInfo(jobCtx, job, tblInfo, true)
+			return ver, err
+		default:
+			panic("unexpected column state in modify column job")
```
Comment (wjhuang2016) [inline pkg/ddl/modify_column.go]: Avoid using panic directly.

File: pkg/ddl/modify_column.go [hunk 3]
```diff
@@ -208,12 +225,20 @@ func getModifyColumnInfo(
 		return nil, nil, nil, errors.Trace(err)
 	}
 
-	oldCol := model.FindColumnInfo(tblInfo.Columns, oldColName.L)
-	if oldCol == nil || oldCol.State != model.StatePublic {
+	var oldCol *model.ColumnInfo
+	if args.OldColumnID > 0 {
```
Comment (wjhuang2016) [inline pkg/ddl/modify_column.go:228]: Please add a comment here

File: pkg/ddl/modify_column.go [hunk 4]
```diff
@@ -208,12 +225,20 @@ func getModifyColumnInfo(
...
+		oldCol = model.FindColumnInfoByID(tblInfo.Columns, args.OldColumnID)
+	} else {
+		oldCol = model.FindColumnInfo(tblInfo.Columns, args.OldColumnName.L)
+		if oldCol != nil {
+			args.OldColumnID = oldCol.ID
+			logutil.DDLLogger().Info("init old column id", zap.String("oldColumnName", args.OldColumnName.L), zap.Int64("oldColumnID", oldCol.ID))
```
Comment (zimulala) [inline pkg/ddl/modify_column.go]:
```suggestion
			logutil.DDLLogger().Info("run modify column job, init old column id", zap.String("oldColumnName", args.OldColumnName.L), zap.Int64("oldColumnID", oldCol.ID))
```

File: pkg/ddl/modify_column.go [hunk 5]
```diff
@@ -208,12 +225,20 @@ func getModifyColumnInfo(
...
+		}
+	}
+	if oldCol == nil {
```
Comment (zimulala) [inline pkg/ddl/modify_column.go:239]: Why do we remove this check `oldCol.State != model.StatePublic` directly? I think we need to do this check at least once, before the state change for`modify column`.

Comment (tangenta) [reply pkg/ddl/modify_column.go:239]: Because `oldCol.State != model.StatePublic` is valid after this PR. We only add some states for `changingColumn` (see the PR description).

File: pkg/ddl/column.go [hunk 6]
```diff
@@ -899,6 +917,75 @@ func (w *updateColumnWorker) BackfillData(_ context.Context, handleRange reorgBa
...
+	for _, idx := range tblInfo.Indices {
+		idxCols := make([]string, 0, len(idx.Columns))
+		for _, idxCol := range idx.Columns {
+			idxCols = append(idxCols, idxCol.Name.O)
+		}
+
+		logutil.DDLLogger().Info("index", zap.Int64("id", idx.ID),
+			zap.String("name", idx.Name.O), zap.Strings("idxCols", idxCols))
+	}
+}
```
Comment (tangenta) [inline pkg/ddl/column.go]: I will remove this after all unit tests pass.

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/ddl/column.go [hunk 7]
```diff
@@ -365,14 +365,14 @@ func updateNewIdxColsNameOffset(changingIdxs []*model.IndexInfo,
...
+func updateModifyingCols(oldCol, changingCol *model.ColumnInfo) {
+	changingCol.ChangeStateInfo = nil
 	// After changing the column, the column's type is change, so it needs to set OriginDefaultValue back
 	// so that there is no error in getting the default value from OriginDefaultValue.
 	// Besides, nil data that was not backfilled in the "add column" is backfilled after the column is changed.
 	// So it can set OriginDefaultValue to nil.
-	col.OriginDefaultValue = nil
-	return col
+	changingCol.OriginDefaultValue = nil
+	oldCol.ChangeStateInfo = &model.ChangeStateInfo{DependencyColumnOffset: changingCol.Offset}
```
Comment (zimulala) [inline pkg/ddl/column.go:375]: How about the following case:
non-owner: create table t (a varchar(5)（colID1, public）, `_Col_$a` int（colID2, WR）);
owner: create table t (a int（colID2, public）, `_Tomestone_$a` varchar(5)（colID1, WO）);

Execute `insert into t value(12345678)` to the owner, which may return an error.
