### PR TITLE
expression: forbidden bind sql when subquery  or union exists

### LINKED ISSUE #26377: create global binding on global temporary table not prohibited
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)


```
mysql> show create table t1;
+-------+------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                               |
+-------+------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `a` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show create table t;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                      |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE GLOBAL TEMPORARY TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  KEY `a` (`a`),
  KEY `b` (`b`),
  KEY `idx` (`a`)
) ENGINE=memory DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ON COMMIT DELETE ROWS |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> create global binding for select * from t1 where t1.a in (select a from t) using select * from t1 where t1.a in (select a from t use index (a));
Query OK, 0 rows affected (0.00 sec)
```



### 2. What did you expect to see? (Required)

Create binding on global temporary table should report error #25058

### 3. What did you see instead (Required)

Binding created, no error.

### 4. What is your TiDB version? (Required)

master

```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.2.0-alpha-334-g0c7ff7fcb-dirty
Edition: Community
Git Commit Hash: 0c7ff7fcb6533f48156345aac1f1be186a2a4f12
Git Branch: issue-26250
UTC Build Time: 2021-07-20 08:30:56
GoVersion: go1.16.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #26377 

Problem Summary:
When temporary table exits in subquery or be on of setOpr select list, binding sql will be return no error.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
`extractTableList` Modified 

How it Works:
`extractTableList` will work when subquery, setOpr exits.

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -414,11 +414,14 @@ func (p *preprocessor) checkBindGrammar(originNode, hintedNode ast.StmtNode, def
 	var resNode ast.ResultSetNode
 	switch n := originNode.(type) {
 	case *ast.SelectStmt:
-		resNode = n.From.TableRefs
+		resNode = n
+	case *ast.SetOprStmt:
+		resNode = n
 	case *ast.DeleteStmt:
 		resNode = n.TableRefs.TableRefs
 	case *ast.UpdateStmt:
```
Comment (lcwangchao) [inline planner/core/preprocess.go:422]: I think we should also check where expr in Delete/Update

File: bindinfo/bind_test.go [hunk 2]
```diff
@@ -2453,6 +2453,19 @@ func (s *testSerialSuite) TestOptimizeOnlyOnce(c *C) {
...
 
+func (s *testSerialSuite) TestIssue26377(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	s.cleanBindingEnv(tk)
+	tk.MustExec("use test")
+	tk.MustExec("set tidb_enable_global_temporary_table = true")
+	tk.MustExec("drop table if exists t1,tmp1")
+	tk.MustExec("create table t1(a int(11))")
+	tk.MustExec("create global temporary table tmp1(a int(11), key idx_a(a)) on commit delete rows;")
+	//tk.MustGetErrCode("create global binding for select * from t1 inner join tmp1 on t1.a=tmp1.a using select * from  t1 inner join tmp1 on t1.a=tmp1.a;", errno.ErrOptOnTemporaryTable)
```
Comment (lcwangchao) [inline bindinfo/bind_test.go:2464]: Why make this commented？

File: bindinfo/bind_test.go [hunk 3]
```diff
@@ -2453,6 +2453,19 @@ func (s *testSerialSuite) TestOptimizeOnlyOnce(c *C) {
 	c.Assert(failpoint.Disable("github.com/pingcap/tidb/planner/checkOptimizeCountOne"), IsNil)
 }
 
+func (s *testSerialSuite) TestIssue26377(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	s.cleanBindingEnv(tk)
```
Comment (lcwangchao) [inline bindinfo/bind_test.go:2458]: local temporary table should also be tested

File: bindinfo/bind_test.go [hunk 4]
```diff
@@ -2453,6 +2453,19 @@ func (s *testSerialSuite) TestOptimizeOnlyOnce(c *C) {
...
+	tk.MustExec("use test")
+	tk.MustExec("set tidb_enable_global_temporary_table = true")
+	tk.MustExec("drop table if exists t1,tmp1")
+	tk.MustExec("create table t1(a int(11))")
+	tk.MustExec("create global temporary table tmp1(a int(11), key idx_a(a)) on commit delete rows;")
+	//tk.MustGetErrCode("create global binding for select * from t1 inner join tmp1 on t1.a=tmp1.a using select * from  t1 inner join tmp1 on t1.a=tmp1.a;", errno.ErrOptOnTemporaryTable)
+	tk.MustGetErrCode("create global binding for select * from t1 where t1.a in (select a from tmp1) using select * from t1 where t1.a in (select a from tmp1 use index (idx_a));", errno.ErrOptOnTemporaryTable)
+	tk.MustGetErrCode("create global binding for select a from t1 union select a from tmp1 using select a from t1 union select a from tmp1 use index (idx_a);", errno.ErrOptOnTemporaryTable)
```
Comment (lcwangchao) [inline bindinfo/bind_test.go:2466]: More test may needed for subquerys like 
```
create global bind for select t1.a, (select b from tmp1 where tmp1.id=1) as t2 from t1 using ...;
create global bind for select * from (select * from tmp1) using ...;
```

File: planner/core/logical_plan_builder.go [hunk 5]
```diff
@@ -5875,11 +5875,44 @@ func buildWindowSpecs(specs []ast.WindowSpec) (map[string]*ast.WindowSpec, error
...
+			unfoldSelectList(s, unfoldList)
+		}
+	}
+}
+
 // extractTableList extracts all the TableNames from node.
 // If asName is true, extract AsName prior to OrigName.
 // Privilege check should use OrigName, while expression may use AsName.
+// TODO: extracting all tables by vistor model maybe a better way
 func extractTableList(node ast.ResultSetNode, input []*ast.TableName, asName bool) []*ast.TableName {
```
Comment (lcwangchao) [inline planner/core/logical_plan_builder.go:5893]: Maybe we can add a unit test for `extractTableList` ?

File: planner/core/logical_plan_builder.go [hunk 6]
```diff
@@ -5875,11 +5875,44 @@ func buildWindowSpecs(specs []ast.WindowSpec) (map[string]*ast.WindowSpec, error
...
 	switch x := node.(type) {
+	case *ast.SubqueryExpr:
+		input = extractTableList(x.Query, input, asName)
+	case *ast.SelectStmt:
+		input = extractTableList(x.From.TableRefs.Left, input, asName)
+		input = extractTableList(x.From.TableRefs.Right, input, asName)
```
Comment (djshow832) [inline planner/core/logical_plan_builder.go:5899]: `x.From.TableRefs` is a Join, so it's covered in this `switch-case`. It can be simplified as `extractTableList(x.From.TableRefs, input, asName)`.

File: planner/core/logical_plan_builder.go [hunk 7]
```diff
@@ -5875,11 +5875,44 @@ func buildWindowSpecs(specs []ast.WindowSpec) (map[string]*ast.WindowSpec, error
...
+		switch w := x.Where.(type) {
```
Comment (djshow832) [inline planner/core/logical_plan_builder.go:5900]: `From` and `Where` are covered, what about the scalar subquery (column subquery)?

Comment (sylzd) [reply planner/core/logical_plan_builder.go:5900]: `column subquery` goes wrong, I will fix it later

File: bindinfo/bind_test.go (hunk 4 above)
Comment (sylzd) [reply bindinfo/bind_test.go]: added. Thx for this cases

File: planner/core/preprocess.go (hunk 1 above)
Comment (sylzd) [reply planner/core/preprocess.go:422]: Let's open a new issue about Delete/Update/Insert~

File: planner/core/logical_plan_builder.go (hunk 5 above)
Comment (sylzd) [reply planner/core/logical_plan_builder.go:5893]: That's a big project. Most internal methods in `logic_plan_builder.go` do not have a UT, such as `extractTableSourceAsNames` , `extractOnCondition` .... and so on.

**Review by djshow832 — APPROVED** [review]

File: planner/core/logical_plan_builder.go (hunk 5 above)
Comment (lcwangchao) [reply planner/core/logical_plan_builder.go:5893]: Adding a unit test is a better practice to prevent explosion of combinations. So even we have some integration tests we still need unit tests to ensure robustness of our code. But I will approve the pr because it is for `forbidden bind sql when subquery or union exists` . We may add a unit test for this method in another RP.

**Review by lcwangchao — APPROVED** [review]

File: planner/core/preprocess.go (hunk 1 above)
Comment (lcwangchao) [reply planner/core/preprocess.go:422]: ok~ I have created a new issue #27422

Comment (sylzd) [reply planner/core/preprocess.go:422]: thx a lot, Let me working on it.

File: planner/core/logical_plan_builder.go (hunk 5 above)
Comment (sylzd) [reply planner/core/logical_plan_builder.go:5893]: I agree to make a specific project to improve the test coverage about `logic_plan_builder.go`
