### PR TITLE
statistics: fix an unsafe lock operation and adjust some logging levels

### LINKED ISSUE #20366: some lock operations on `statistics.handle.Handle.mu` are not robust
## Development Task
Example1:
```
h.mu.Lock()
... // some lines of code
h.mu.Unlock()
```
If it panics between these two lock operation, the lock would not be released.
We should change it to:
```
h.mu.Lock()
defer h.mu.Unlock()
...
```

Example2: there is a pair of functions:
```
func (h *Handle) getStatsReader(...) (...) {
    h.mu.Lock()
    ...
}

func (h *Handle) releaseStatsReader(...) (...) {
    h.mu.Unlock()
    ...
}
```
Now we use them as below:
```
_, err := h.getStatsReader()
if err != nil {
    return err
}
defer func() {
    h.releaseStatsReader()
}
```
If `getStatsReader` returns an error, the lock would not be released.
It's better to remove lock operations from `getStatsReader` and `releaseStatsReader` and let the outside caller do lock operations.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #20366 

Problem Summary: statistics: fix an unsafe lock operation and adjust some logging levels

### What is changed and how it works?

There is a pair of functions:
```
func (h *Handle) getStatsReader(...) (...) {
    h.mu.Lock()
    ...
}
func (h *Handle) releaseStatsReader(...) (...) {
    h.mu.Unlock()
    ...
}
```

Now we use them as below:
```
_, err := h.getStatsReader()
if err != nil {
    return err
}
defer h.releaseStatsReader()
```
If `getStatsReader` returns an error, the lock will not be released.
This PR releases the lock in `getStatsReader` when errors occur.

This PR also upgrades some logging levels.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- statistics: fix an unsafe lock operation and adjust some logging levels

### CODE REVIEW

File: statistics/handle/handle.go [hunk 1]
```diff
@@ -845,6 +845,7 @@ func (h *Handle) getStatsReader(history sqlexec.RestrictedSQLExecutor) (*statsRe
 	h.mu.Lock()
 	_, err := h.mu.ctx.(sqlexec.SQLExecutor).Execute(context.TODO(), "begin")
 	if err != nil {
+		h.mu.Unlock()
```
Comment (zz-jason) [inline statistics/handle/handle.go:848]: it's better to `defer` the unlock operation.

Comment (qw4990) [reply statistics/handle/handle.go:848]: Since the statement `return nil, err` has no risk to cause panics, it's ok to don't use `defer` here.

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by jackysp — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
PTAL @zz-jason

File: statistics/handle/handle.go (hunk 1 above)
Comment (zz-jason) [reply statistics/handle/handle.go:848]: is there a chance that `_, err := h.mu.ctx.(sqlexec.SQLExecutor).Execute(context.TODO(), "begin")` paniced during the execution?

Comment (qw4990) [reply statistics/handle/handle.go]: OK, I update it and add a fail-point test for it.
PTAL @zz-jason

**Review by zz-jason — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
