### PR TITLE
ddl/ingest: remove backend context manager and refactor code

### LINKED ISSUE #57670: add global index failed with error "[kv:1062]Duplicate entry ...“
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、with local sort
2、run sysbench
3、add global index 
4、kill ddl owner

### 2. What did you expect to see? (Required)
add index can succeed

### 3. What did you see instead (Required)
add global index with error "[kv:1062]Duplicate entry ...“

case logs：
"the state of ddl job is not synced (now: 2024-11-25 09:56:53, jobId: 3839, job type: add index, state: rollback done, comments: ingest, DXF)
operatorLogs:
[2024-11-25 09:54:22] ###### start adding index
ALTER TABLE `sbtest1` ADD unique INDEX `index_test_1732499662632`(`c`) global
[2024-11-25 09:54:22] ###### wait for ddl job finish
[2024-11-25 09:56:53] ###### ddl job failed
select job_id, db_name, table_name, job_type, create_time, start_time, end_time, state, query from information_schema.ddl_jobs where query = 'ALTER TABLE `sbtest1` ADD unique INDEX `index_test_1732499662632`(`c`) global'
jobId: 3839, job type: add index, state: rollback done, comments: ingest, DXF"

tidb logs：
[tidb-0.log.zip](https://github.com/user-attachments/files/17899060/tidb-0.log.zip)
[tidb-1-2024-11-25T10-35-43.276.log.zip](https://github.com/user-attachments/files/17899066/tidb-1-2024-11-25T10-35-43.276.log.zip)

`[2024/11/25 09:51:19.700 +08:00] [ERROR] [task_executor.go:239] ["failed to handle task"] [task-id=210007] [task-type=backfill] [error="[kv:1062]Duplicate entry '99999619784-94058441387-94274379972-79146472490-29741447767-5429' for key 'sbtest1.index_test_1732497921953'"]
[2024/11/25 09:51:19.912 +08:00] [INFO] [manager.go:246] [onCanceledTasks] [task-id=210007]
[2024/11/25 09:51:20.002 +08:00] [INFO] [manager.go:332] ["task executor exit"] [task-id=210007] [type=backfill]
[2024/11/25 09:51:25.592 +08:00] [ERROR] [handle.go:109] ["task reverted"] [task-id=210007] [error="[kv:1062]Duplicate entry '99999619784-94058441387-94274379972-79146472490-29741447767-5429' for key 'sbtest1.index_test_1732497921953'"]
[2024/11/25 09:51:25.599 +08:00] [WARN] [reorg.go:421] ["run reorg job done"] [category=ddl] ["handled rows"=42983527] [error="[kv:1062]Duplicate entry '99999619784-94058441387-94274379972-79146472490-29741447767-5429' for key 'sbtest1.index_test_1732497921953'"]
[2024/11/25 09:51:25.605 +08:00] [WARN] [index.go:1508] ["run add index job failed, convert job to rollback"] [category=ddl] [job="ID:3838, Type:add index, State:running, SchemaState:write reorganization, SchemaID:3626, TableID:3730, RowCount:42983527, ArgLen:1, start time: 2024-11-25 09:25:21.932 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:454163935522455555, Version: v2, UniqueWarnings:0"] [error="[kv:1062]Duplicate entry '99999619784-94058441387-94274379972-79146472490-29741447767-5429' for key 'sbtest1.index_test_1732497921953'"]`

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: ref #57670

Problem Summary:

When DXF is enabled with local ingest, the subtasks are not idempotent because when TiDB gets killed before the subtask is complete, it will use a different ingest TS. As a result, the duplicate detector thinks that there are conflicts.

### What changed and how does it work?

- Remove the backend context manager. Let the subtask/ddl executor own the backend context.
- Move checkpoint manager into the backend context for checkpoint support in DXF in the future.
- Initialize `TS` for each subtask.
- Allow `AdvanceWatermark` to return an error.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ingest/backend.go [hunk 1]
```diff
@@ -218,22 +227,6 @@ func (bc *litBackendCtx) Flush(ctx context.Context, mode FlushMode) (flushed, im
 		}
 	}
 
-	var newTS uint64
-	if mgr := bc.GetCheckpointManager(); mgr != nil {
-		// for local disk case, we need to refresh TS because duplicate detection
```
Comment (lance6716) [inline pkg/ddl/ingest/backend.go:223]: For a subtask, we should use the same TS. But if disk is full and trigger a partitial import, we should switch TS. Because there maybe duplicate key before and after the  partitial import, and we need the different TS to let duplicate detection report error.

In current architecture we can't solve both problem, and because the team didn't arrange a plan for us to solve it. I prefer we keep this refreshTS logic. False alarm of duplicate enrty error is better than false negative that causes data-index inconsistency

File: pkg/ddl/backfilling_dist_scheduler.go [hunk 2]
```diff
@@ -93,14 +93,20 @@ func (sch *BackfillingSchedulerExt) OnNextSubtasksBatch(
 		return nil, err
 	}
 	logger.Info("on next subtasks batch")
+	pdCli := sch.d.store.(kv.StorageWithPD).GetPDClient()
+	p, l, err := pdCli.GetTS(ctx)
+	if err != nil {
+		return nil, err
+	}
+	ingestTS := oracle.ComposeTS(p, l)
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_dist_scheduler.go:101]: so all subtasks have the same ts initially?

Comment (lance6716) [reply pkg/ddl/backfilling_dist_scheduler.go:101]: Oh, in order to find duplicate key in different subtasks, we should not use 1 TS for them all.

File: pkg/ddl/ingest/backend.go (hunk 1 above)
Comment (tangenta) [reply pkg/ddl/ingest/backend.go:223]: For now, the subtask executor can't update the subtask meta directly. Can we create another goroutine to update the subtask meta and ingest TS on demand, like `updateSubtaskSummaryLoop`? @lance6716 @D3Hunter

Comment (lance6716) [reply pkg/ddl/ingest/backend.go:223]: I think we can keep current architecture and only improve a bit to mitigate the problem. We only solve this problem: if no paritial import happens, subtask worker failover should use the same TS. And the fix is, for the first (partial or full) import, use the TS saved in subtask metadata. For subsequential partitial import, acquire a new TS. Leave the issue that failover on subsequential partitial import will cause false alarm of "duplicate entry" error.

Comment (D3Hunter) [reply pkg/ddl/ingest/backend.go:223]: another writer would make it complicate to manage and sync `meta` field, right now `OnFinished` is the only place meta is allowed to be changed.

if we gone to do it, maybe save this info in `summary`, then you can reuse `updateSubtaskSummaryLoop`

File: pkg/ddl/backfilling.go [hunk 3]
```diff
@@ -787,9 +766,6 @@ func (dc *ddlCtx) runAddIndexInLocalIngestMode(
 		}
 		return err
 	}
-	if cpMgr != nil {
-		cpMgr.AdvanceWatermark(true, true)
-	}
```
Comment (tangenta) [inline pkg/ddl/backfilling.go:792]: It should be advanced immediately after partial import.

File: pkg/lightning/backend/local/region_job.go [hunk 4]
```diff
@@ -802,12 +802,17 @@ func (local *Backend) doIngest(ctx context.Context, j *regionJob) (*sst.IngestRe
...
-	local.writeLimiter.UpdateLimit(limit)
+	if local.writeLimiter != nil {
+		local.writeLimiter.UpdateLimit(limit)
+	}
 }
 
 // GetWriteSpeedLimit returns the speed of the write limiter.
 func (local *Backend) GetWriteSpeedLimit() int {
-	return local.writeLimiter.Limit()
+	if local.writeLimiter != nil {
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/region_job.go:812]: no need nil check

Comment (tangenta) [reply pkg/lightning/backend/local/region_job.go:812]: In MockBackendCtx, this field is nil and fail the test with a certain probability.

Comment (D3Hunter) [reply pkg/lightning/backend/local/region_job.go:812]: if so, then init it

and I see we use a `MockBackendCtx` in real tikv test, why not use the real one directly?

Comment (tangenta) [reply pkg/lightning/backend/local/region_job.go:812]: `MockBackendCtx` is also used in unit tests in `ddl/ingest`

Comment (D3Hunter) [reply pkg/lightning/backend/local/region_job.go:812]: > MockBackendCtx is also used in unit tests in ddl/ingest

yes, we need it in UT, but why real-tikv need it?

and, init `local.writeLimiter` in `MockBackendCtx`, no need to change real code for test for this

File: pkg/ddl/ingest/disk_root.go [hunk 5]
```diff
@@ -155,3 +193,20 @@ func (d *diskRootImpl) StartupCheck() error {
...
+			leakObj = "disk usage tracker"
+		} else if BackendCounterForTest.Load() != 0 {
+			leakObj = "backend context"
+		}
+		if len(leakObj) > 0 {
+			fmt.Fprintf(os.Stderr, "add index leakage check failed: %s leak\n", leakObj)
+			os.Exit(1)
+		}
+	}
+	os.Exit(exitCode)
```
Comment (D3Hunter) [inline pkg/ddl/ingest/disk_root.go:211]:
```suggestion
```
seems not needed, let TestMain handle the exit

**Review by D3Hunter — COMMENTED** [review]
11/39

File: pkg/ddl/ingest/disk_root.go (hunk 5 above)
Comment (tangenta) [reply pkg/ddl/ingest/disk_root.go:211]:
```

// Variables for stubbing in unit tests.
var (
	_osExit             = os.Exit
	_osStderr io.Writer = os.Stderr
)
```
```
	var cleanup func(int)
	cleanup, opts.cleanup = opts.cleanup, nil
	if cleanup == nil {
		cleanup = _osExit
	}
	defer func() { cleanup(exitCode) }()
```

Cleanup function should be a replacement of `os.Exit`

File: pkg/ddl/ingest/backend.go [hunk 6]
```diff
@@ -201,8 +217,38 @@ func (bc *litBackendCtx) Flush(ctx context.Context, mode FlushMode) (flushed, im
...
+	}
+	return nil
+}
+
+func (bc *litBackendCtx) tryAcquireDistLock() (func(), error) {
+	if bc.etcdClient == nil {
+		return nil, nil
+	}
+	key := fmt.Sprintf("/tidb/distributeLock/%d", bc.jobID)
+	return owner.AcquireDistributedLock(bc.ctx, bc.etcdClient, key, 10)
```
Comment (fzzf678) [inline pkg/ddl/ingest/backend.go:246]: How about using a constant instead of the number `10`

File: pkg/lightning/backend/local/region_job.go (hunk 4 above)
Comment (tangenta) [reply pkg/lightning/backend/local/region_job.go]: https://github.com/pingcap/tidb/pull/57770/commits/1b0d144f1a5b3c4673a625974074435e9de3cc74

File: pkg/ddl/ingest/disk_root.go (hunk 5 above)
Comment (D3Hunter) [reply pkg/ddl/ingest/disk_root.go:211]: yes, but if exitCode==0 as in this case, it's not necessary

File: pkg/ddl/ingest/disk_root.go [hunk 7]
```diff
@@ -155,3 +193,20 @@ func (d *diskRootImpl) StartupCheck() error {
 func RiskOfDiskFull(available, capacity uint64) bool {
 	return float64(available) < (1-capacityThreshold)*float64(capacity)
 }
+
+// CheckIngestLeakageForTest is only used in test.
+func CheckIngestLeakageForTest(exitCode int) {
```
Comment (D3Hunter) [inline pkg/ddl/ingest/disk_root.go:198]: can move to `testutil` pkg

File: pkg/ddl/ingest/disk_root.go [hunk 8]
```diff
@@ -29,8 +29,17 @@ import (
 	"go.uber.org/zap"
 )
 
+// UsageTracker has the method of GetUsage.
+type UsageTracker interface {
```
Comment (D3Hunter) [inline pkg/ddl/ingest/disk_root.go:33]: maybe DiskTracker or ResourceTracker

**Review by D3Hunter — COMMENTED** [review]
31/39

File: pkg/ddl/backfilling.go [hunk 9]
```diff
@@ -735,34 +735,13 @@ func (dc *ddlCtx) runAddIndexInLocalIngestMode(
...
 	}
 
-	//nolint: forcetypeassert
-	discovery := dc.store.(tikv.Storage).GetRegionCache().PDClient().GetServiceDiscovery()
-	importConc := job.ReorgMeta.GetConcurrencyOrDefault(int(variable.GetDDLReorgWorkerCounter()))
-	maxWriteSpeed := job.ReorgMeta.GetMaxWriteSpeedOrDefault()
-	bcCtx, err := ingest.LitBackCtxMgr.Register(
-		ctx, job.ID, hasUnique, nil, discovery, job.ReorgMeta.ResourceGroupName, importConc, maxWriteSpeed, job.RealStartTS)
+	bcCtx, err := ingest.NewBackendCtxBuilder(ctx, dc.store, job).
+		WithCheckpointManager(sessPool, reorgInfo.PhysicalTableID).
```
[the remark this answers is not in the document]
Comment (tangenta) [reply pkg/ddl/backfilling.go:739]: How about `WithCheckpointManagerParam`

File: pkg/ddl/ingest/disk_root.go (hunk 7 above)
Comment (tangenta) [reply pkg/ddl/ingest/disk_root.go:198]: There is an import cycle. Tests in `ingest` depends on `testutil`, and `testutil` depends on `ingest`.

File: pkg/ddl/ingest/backend.go [hunk 10]
```diff
@@ -158,41 +161,54 @@ func (bc *litBackendCtx) collectRemoteDuplicateRows(indexID int64, tbl table.Tab
...
+
+	err = bc.unsafeImportAndResetAllEngines(ctx)
+	if err != nil {
+		return err
+	}
+	return bc.AdvanceWatermark(true)
+}
+
+// Flush implements FlushController.
+func (bc *litBackendCtx) Flush(ctx context.Context) error {
```
Comment (D3Hunter) [inline pkg/ddl/ingest/backend.go:200]:
```suggestion
func (bc *litBackendCtx) Ingest(ctx context.Context) error {
```

File: pkg/lightning/backend/local/region_job.go [hunk 11]
```diff
@@ -1184,6 +1184,9 @@ func (b *storeBalancer) runSendToWorker(workerCtx context.Context) {
 			select {
 			case <-workerCtx.Done():
 				j.done(b.jobWg)
+				if j.region != nil && j.region.Region != nil {
+					b.releaseStoreLoad(j.region.Region.Peers)
+				}
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/region_job.go:1189]: it doesn't matter to release or not, we also didn't check it at L1167

File: pkg/ddl/ingest/disk_root.go (hunk 7 above)
Comment (D3Hunter) [reply pkg/ddl/ingest/disk_root.go:198]: we can make the pkg of `TestMain` `ingest_test`

File: pkg/ddl/backfilling_import_cloud.go [hunk 12]
```diff
@@ -74,7 +70,12 @@ func (m *cloudImportExecutor) RunSubtask(ctx context.Context, subtask *proto.Sub
 		return err
 	}
 
-	local := m.bc.GetLocalBackend()
+	bCtx, err := ingest.NewBackendCtxBuilder(ctx, m.store, m.job).Build()
```
[the remark this answers is not in the document]
Comment (tangenta) [reply pkg/ddl/backfilling_import_cloud.go:73]: Not sure if the backend context should be rebuilt when DXF encountering a retryable error. Let's change and see what will happen.

File: pkg/lightning/backend/local/region_job.go (hunk 11 above)
Comment (D3Hunter) [reply pkg/lightning/backend/local/region_job.go:1189]: maybe we can refine the assert, if error happened, no need to check it

**Review by D3Hunter — APPROVED** [review]

**Review by fzzf678 — APPROVED** [review]
