### PR TITLE
model: fix decode args error for ddls executed on older version of TiDB

### LINKED ISSUE #64413: 6th args of RenameTables job is missing if the job is run and done on v7.5 but we are decoding it using code of 8.5
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
after 8.5 https://github.com/pingcap/tidb/issues/53930, we switch to uses a structured way to marshal/unmarshal job args

6th args of RenameTables job is missing if the job is run and done on v7.5 but we are decoding it using code of 8.5, it happens on TiCDC 8.5 syncing a v7.5 cluster, see detail in https://github.com/pingcap/tiflow/issues/12388 , while in 8.5 we expects 6. the behavior in 7.5 is confusing and error prone, but we have to be compatible with it

### 4. What is your TiDB version? (Required)
8.5

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #64413

Problem Summary:

Check https://github.com/pingcap/tiflow/issues/12388 for detail

### What changed and how does it work?

Add missing `oldTableNames` in `decodeV1`.

I've checked the tiflow repo, currently we only need to decode `RenameTablesArgs`.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/meta/model/job_args.go [hunk 1]
```diff
@@ -855,6 +855,13 @@ func (a *RenameTablesArgs) decodeV1(job *Job) error {
 		return errors.Trace(err)
 	}
 
+	// oldTableNames may be truncated for job executed on older TiDB versions.
+	// See https://github.com/pingcap/tidb/blob/293331cd9211c214f3431ff789210374378e9697/pkg/ddl/ddl_worker.go#L1442-L1447
+	if oldTableNames == nil {
```
Comment (D3Hunter) [inline pkg/meta/model/job_args.go]:
```suggestion
	if len(oldTableNames) == 0 && len(oldSchemaIDs) != 0 {
```

File: pkg/meta/model/job_args.go [hunk 2]
```diff
@@ -855,6 +855,13 @@ func (a *RenameTablesArgs) decodeV1(job *Job) error {
 		return errors.Trace(err)
 	}
 
+	// oldTableNames may be truncated for job executed on older TiDB versions.
```
Comment (D3Hunter) [inline pkg/meta/model/job_args.go]:
```suggestion
	// if the job is run on older TiDB versions(<=8.1), it will incorrectly remove
	// the last arg oldTableNames
```

File: pkg/meta/model/job_args.go [hunk 3]
```diff
@@ -855,6 +855,14 @@ func (a *RenameTablesArgs) decodeV1(job *Job) error {
 		return errors.Trace(err)
 	}
 
+	// if the job is run on older TiDB versions(<=8.1), it will incorrectly remove
+	// the last arg oldTableNames
+	// See https://github.com/pingcap/tidb/blob/293331cd9211c214f3431ff789210374378e9697/pkg/ddl/ddl_worker.go#L1442-L1447
+	if len(oldTableNames) == 0 && len(oldSchemaIDs) != 0 {
+		oldTableNames = make([]ast.CIStr, len(oldSchemaIDs))
+		job.args = append(job.args, oldTableNames)
```
Comment (D3Hunter) [inline pkg/meta/model/job_args.go]: maybe remove this, we don't need to add back, the remove happens we we make the job schema state into public state, so it won't be changed any more

**Review by D3Hunter — APPROVED** [review]

File: pkg/meta/model/job_args.go [hunk 4]
```diff
@@ -855,6 +855,13 @@ func (a *RenameTablesArgs) decodeV1(job *Job) error {
 		return errors.Trace(err)
 	}
 
+	// if the job is run on older TiDB versions(<=8.1), it will incorrectly remove
```
Comment (wjhuang2016) [inline pkg/meta/model/job_args.go]:
```suggestion
	// If the job is run on older TiDB versions(<=8.1), it will incorrectly remove
```

File: pkg/meta/model/job_args.go [hunk 5]
```diff
@@ -855,6 +855,13 @@ func (a *RenameTablesArgs) decodeV1(job *Job) error {
...
+	// the last arg oldTableNames
```
Comment (wjhuang2016) [inline pkg/meta/model/job_args.go]:
```suggestion
	// the last arg oldTableNames.
```
