### PR TITLE
*: avoid concurrently using the session in the syncload 

### LINKED ISSUE #52827: tidb restart due to “handleOneItemTask panicked” after lightning finished
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、lightning import
2、lightning import success

### 2. What did you expect to see? (Required)
no panic

### 3. What did you see instead (Required)
tidb restart due to “handleOneItemTask panicked”

`[2024/04/23 05:24:38.567 +08:00] [ERROR] [stats_syncload.go:271] ["handleOneItemTask panicked"] [recover="runtime error: invalid memory address or nil pointer dereference"] [stack="github.com/pingcap/tidb/pkg/statistics/handle/syncload.(*statsSyncLoad).handleOneItemTask.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/statistics/handle/syncload/stats_syncload.go:271\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:451\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/pingcap/tidb/pkg/sessiontxn/isolation.(*baseTxnContextProvider).ActivateTxn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/sessiontxn/isolation/base.go:290\ngithub.com/pingcap/tidb/pkg/sessiontxn/isolation.(*baseTxnContextProvider).GetStmtReadTS\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/sessiontxn/isolation/base.go:186\ngithub.com/pingcap/tidb/pkg/sessiontxn/isolation.(*baseTxnContextProvider).GetSnapshotWithStmtReadTS\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/sessiontxn/isolation/base.go:402\ngithub.com/pingcap/tidb/pkg/session.(*txnManager).GetSnapshotWithStmtReadTS\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/txnmanager.go:140\ngithub.com/pingcap/tidb/pkg/executor.(*executorBuilder).getSnapshot\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:1819\ngithub.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildPointGet\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/point_get.go:83\ngithub.com/pingcap/tidb/pkg/executor.(*executorBuilder).build\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:193\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).buildExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:1171\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:521\ngithub.com/pingcap/tidb/pkg/session.runStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2276\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2137\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteInternalStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:1989\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecRestrictedSQL.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:1954\ngithub.com/pingcap/tidb/pkg/session.(*session).withRestrictedSQLExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:1940\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecRestrictedSQL\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:1944\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.ExecRows\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:213\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.HistMetaFromStorage\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/statistics/handle/storage/read.go:66\ngithub.com/pingcap/tidb/pkg/statistics/handle/syncload.(*statsSyncLoad).readStatsForOneItem\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/statistics/handle/syncload/stats_syncload.go:348\ngithub.com/pingcap/tidb/pkg/statistics/handle/syncload.(*statsSyncLoad).handleOneItemTask\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/statistics/handle/syncload/stats_syncload.go:316\ngithub.com/pingcap/tidb/pkg/statistics/handle/syncload.(*statsSyncLoad).HandleOneTask.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/statistics/handle/syncload/stats_syncload.go:234\ngolang.org/x/sync/singleflight.(*Group).doCall.func2\n\t/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:198\ngolang.org/x/sync/singleflight.(*Group).doCall\n\t/go/pkg/mod/golang.org/x/sync@v0.7.0/singleflight/singleflight.go:200"]`

### 4. What is your TiDB version? (Required)
"Git Commit Hash"=cfcc770e8a0451c9786fa288b910b784e36633f2

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #52827

Problem Summary:

### What changed and how does it work?

when ```singleflight``` meets timeout, some goroutines will concurrently use reuse session. we should keep everyone using independent sessions.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

run it in the HA, It can pass test.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lcwangchao — APPROVED** [review]

File: pkg/statistics/handle/syncload/stats_syncload_test.go [hunk 1]
```diff
@@ -318,5 +318,18 @@ func TestRetry(t *testing.T) {
 		t.Logf("task1.ResultCh should get nothing")
 		t.FailNow()
 	}
+	task1.Retry = 0
+	for i := 0; i < syncload.RetryCount*5; i++ {
+		task1, err1 = h.HandleOneTask(testKit.Session().(sessionctx.Context), task1, exitCh)
+		require.Error(t, err1)
```
Comment (AilinKid) [inline pkg/statistics/handle/syncload/stats_syncload_test.go:324]: assert the err1 msg

Comment (hawkingrei) [reply pkg/statistics/handle/syncload/stats_syncload_test.go:324]: It failpoints a panic in the program. so ```HandleOneTask``` can quickly exit and create many goroutine in the tests.

**Review by AilinKid — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold

wait for test result from QA.

**Review by winoros — APPROVED** [review]

**Comment by hawkingrei** [comment]
> /hold
> 
> wait for test result from QA.

image
