### PR TITLE
*: fix a bug causes indexed virtual generated column return wrong value and refine admin check table

### LINKED ISSUE #17989: create index with multi-layer virtual generated column return wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> create table t(a int, b tinyint as(a+1), c int as(b+1));
Query OK, 0 rows affected (0.01 sec)

mysql> set sql_mode="";
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t(a) values(2000);
Query OK, 1 row affected, 1 warning (0.01 sec)

mysql> create index idx on t(c);
Query OK, 0 rows affected (0.02 sec)

mysql> select c from t;
+------+
| c    |
+------+
| 2002 |
+------+
1 row in set (0.00 sec)

mysql> select * from t;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| 2000 |  127 |  128 |
+------+------+------+
1 row in set, 1 warning (0.00 sec)
```

### 2. What did you expect to see? (Required)

```
mysql> select c from t;
+------+
| c    |
+------+
| 128 |
+------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
2002
### 4. Affected version (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #17989 

Problem Summary:
1. Previously, we try to use `column substitution` to decode a multi-level virtual generated column, which is buggy. 
2. Since `admin check table` uses tableReader, and tableReader can output rows with a virtual generated column already, we don't need to compute it again. Besides, the previous implementation also suffered the above problem.
I’m 
### What is changed and how it works?

1. Build virtual expression for virtual generated column in `ColumnInfos2ColumnsAndNames`.
2. Remove `genExprs` in `checkIndexValue`.
3. In `compareData`, don't compute the virtual generated column again.
4. Export a function `rewriteAstExpr`, so that we can use `rewrite` in package expression.
5. Refine `buildPhysicalIndexLookUpReader`, make it simple.
6. Move ` table/tables/gen_expr_test.go → util/generatedexpr/gen_expr_test.go`. to avoid circular reference.

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Fix a bug causes indexed virtual generated column return wrong value and refine admin check table

### CODE REVIEW

File: util/admin/admin.go [hunk 1]
```diff
@@ -385,32 +385,24 @@ func CheckRecordAndIndex(sessCtx sessionctx.Context, txn kv.Transaction, t table
...
-	decodeColsMap, ignored := decoder.BuildFullDecodeColMap(decodeCol, t, func(genCol *table.Column) (expression.Expression, error) {
-		containsVirtualCol = true
-		return genExpr[model.TableColumnID{TableID: t.Meta().ID, ColumnID: genCol.ID}], nil
-	})
-	_ = ignored
+func makeRowDecoder(t table.Table, sctx sessionctx.Context) *decoder.RowDecoder {
+	dbName := model.NewCIStr(sctx.GetSessionVars().CurrentDB)
+	exprCols, _ := expression.ColumnInfos2ColumnsAndNames(sctx, dbName, t.Meta().Name, t.Meta().Columns, t.Meta())
+	mockSchema := expression.NewSchema(exprCols...)
+	decodeColsMap := decoder.BuildFullDecodeColMap(t, mockSchema)
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply util/admin/admin.go:403]: Fixed.

File: util/rowDecoder/decoder.go [hunk 2]
```diff
@@ -142,7 +142,13 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle kv.
 		}
 		rd.mutRow.SetValue(colInfo.Offset, val.GetValue())
 	}
-	for id, col := range rd.columns {
+	var keys []int
+	for k := range rd.columns {
+		keys = append(keys, int(k))
+	}
+	sort.Ints(keys)
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply util/rowDecoder/decoder.go:146]: Fixed.

File: expression/expression.go [hunk 3]
```diff
@@ -780,7 +787,40 @@ func ColumnInfos2ColumnsAndNames(ctx sessionctx.Context, dbName, tblName model.C
...
 		columns = append(columns, newCol)
 	}
-	return columns, names
+	// Resolve virtual generated column.
+	mockSchema := NewSchema(columns...)
+	save := ctx.GetSessionVars().StmtCtx.IgnoreTruncate
+	defer func() {
+		ctx.GetSessionVars().StmtCtx.IgnoreTruncate = save
+	}()
+	ctx.GetSessionVars().StmtCtx.IgnoreTruncate = true
```
Comment (tangenta) [inline expression/expression.go:796]: Is it thread-safe?

Comment (wjhuang2016) [reply expression/expression.go:796]: It's used in the planner and it's used serail.

File: planner/core/planbuilder.go [hunk 4]
```diff
@@ -1143,84 +1138,60 @@ func (b *PlanBuilder) buildPhysicalIndexLookUpReader(ctx context.Context, dbName
 				idxReaderCols = append(idxReaderCols, col)
 				tblReaderCols = append(tblReaderCols, col)
 				schema.Append(fullExprCols.Columns[i])
-				colsMap.Insert(col.ID)
-				if mysql.HasPriKeyFlag(col.Flag) {
-					pkOffsets = append(pkOffsets, len(tblReaderCols)-1)
```
Comment (djshow832) [inline planner/core/planbuilder.go:1148]: Why remove this?

File: util/rowDecoder/decoder.go [hunk 5]
```diff
@@ -166,118 +169,21 @@ func (rd *RowDecoder) DecodeAndEvalRowWithMap(ctx sessionctx.Context, handle kv.
...
-		for _, v := range indexedCols {
-			if v.Offset == col.Offset {
-				found = true
-				break
-			}
-		}
-
-		if !found {
-			delete(decodeColMap, colID)
+// BuildFullDecodeColMap build a map that contains [columnID -> struct{*table.Column, expression.Expression}] from all columns.
```
Comment (djshow832) [inline util/rowDecoder/decoder.go:179]:
```suggestion
// BuildFullDecodeColMap builds a map that contains [columnID -> struct{*table.Column, expression.Expression}] from all columns.
```

File: planner/core/planbuilder.go [hunk 6]
```diff
@@ -1085,7 +1085,6 @@ func (b *PlanBuilder) getGenExprs(ctx context.Context, dbName model.CIStr, tbl t
 			if err != nil {
 				return nil, errors.Trace(err)
 			}
-			expr = expression.BuildCastFunction(b.ctx, expr, colExpr.GetType())
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply planner/core/planbuilder.go:1088]: `Cast` is done by `castInto`, which is the correct function to deal with type.

File: planner/core/planbuilder.go (hunk 4 above)
Comment (wjhuang2016) [reply planner/core/planbuilder.go:1148]: 1. We don't need to deal with genExpr, since tableReader can output virtual generated column.
2. pkOffsets is handled after ExpandVirtualColumn()

**Comment by bb7133** [comment]
LGTM
