### PR TITLE
stmt: clean `rowContainer` if the execution paniced

### LINKED ISSUE #59963: spilling data didn't clean for cursor fetch
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists t1;
CREATE TABLE `t1` (`c1` varchar(100));
insert into t1 (c1)values("201801");
insert into t1 (c1)values("201801");
insert into t1 (c1)values("xxxxx");
insert into t1 (select * from t1);

-- run the last insert multiple times until you have 786432 rows in t1
set global tidb_mem_quota_query =10000000;
```

change tidb config to set `tmp-storage-quota = 16500000`

```
import java.sql.*;

public class MySQLCursorFetch {
    public static void main(String[] args) {
        String url = "jdbc:mysql://127.0.0.1:41501/test?useCursorFetch=true&defaultFetchSize=100";
        String user = "root";
        String password = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(url, user, password);

            String query = "SELECT * FROM test.t1";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setFetchSize(100);

            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                String columnData = rs.getString("c1"); 
                System.out.println("Processing row: " + columnData);
            }

            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
`java -cp .:/home/guojiangtao/tar_gz/jdbc/mysql-connector-j-9.2.0/mysql-connector-j-9.2.0.jar ./jdbc.java` (note: you need set up you java env and download mysql-connector-java first)

### 2. What did you expect to see? (Required)

return error like the following and the spilling files have been deleted.
```
java -cp .:/home/guojiangtao/tar_gz/jdbc/mysql-connector-j-9.2.0/mysql-connector-j-9.2.0.jar ./jdbc.java
java.sql.SQLException: Out Of Quota For Local Temporary Space!
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:612)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1058)
	at MySQLCursorFetch.main(jdbc.java:22)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:484)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:208)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:135)
```

### 3. What did you see instead (Required)
spilling file didn't clean
### 4. What is your TiDB version? (Required)
v6.5.7

### LINKED ISSUE #59976: TiDB panics when network failed when `writeExecuteResultWithCursor` failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Update the TiDB code to mock the network error when writing the packet

```diff
diff --git a/pkg/server/conn_stmt.go b/pkg/server/conn_stmt.go
index d0188c2ddd..04a652d7b1 100644
--- a/pkg/server/conn_stmt.go
+++ b/pkg/server/conn_stmt.go
@@ -462,6 +462,11 @@ func (cc *clientConn) writeExecuteResultWithCursor(ctx context.Context, stmt Pre
                }
        }()

+       if ctx != nil {
+               // mock an error when writing the packet to the client
+               return errors.New("mock network error")
+       }
+
        if err = cc.writeColumnInfo(rs.Columns()); err != nil {
                return err
        }
```

2. run Java program:

```java
package org.example;

import java.sql.*;

public class Main {
    public static void main(String[] args) throws Exception {
        Connection conn = DriverManager.getConnection(
                "jdbc:mysql://127.0.0.1:4001/test?useCursorFetch=true&useServerPrepStmts=true&useSSL=false",
                "root",
                ""
        );
        PreparedStatement stmt = conn.prepareStatement("select * from t1");
        stmt.setFetchSize(10);
        var rs = stmt.executeQuery();
        while (rs.next()) {
            System.out.print(rs.getInt(1) + ", ");
        }
        System.out.println();
    }
}
```

### 2. What did you expect to see? (Required)

No panic

### 3. What did you see instead (Required)

TiDB panics:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1020c5a4c]

goroutine 1232 [running]:
github.com/pingcap/tidb/pkg/util/chunk.(*List).Clear(0x0)
	/Users/wangchao/Code/pingcap/tidb/pkg/util/chunk/list.go:166 +0x1c
github.com/pingcap/tidb/pkg/util/chunk.(*RowContainer).Close(0x1401399b820)
	/Users/wangchao/Code/pingcap/tidb/pkg/util/chunk/row_container.go:349 +0x204
github.com/pingcap/tidb/pkg/server.(*TiDBStatement).Close(0x140139bd500)
	/Users/wangchao/Code/pingcap/tidb/pkg/server/driver_tidb.go:184 +0x128
github.com/pingcap/tidb/pkg/parser/terror.Call(0x1401381e410)
	/Users/wangchao/Code/pingcap/tidb/pkg/parser/terror/terror.go:315 +0x30
github.com/pingcap/tidb/pkg/server.(*TiDBContext).Close(0x1401369ec18)
	/Users/wangchao/Code/pingcap/tidb/pkg/server/driver_tidb.go:307 +0xdc
github.com/pingcap/tidb/pkg/server.closeConn.func1()
	/Users/wangchao/Code/pingcap/tidb/pkg/server/conn.go:414 +0x2a8
sync.(*Once).doSlow(0x1401327330c, 0x1401381e7a0)
	/Users/wangchao/.gvm/pkgsets/go1.23.2/global/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.7.darwin-arm64/src/sync/once.go:76 +0x148
sync.(*Once).Do(0x1401327330c, 0x1401381e7a0)
	/Users/wangchao/.gvm/pkgsets/go1.23.2/global/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.7.darwin-arm64/src/sync/once.go:67 +0x44
github.com/pingcap/tidb/pkg/server.closeConn(0x140132731e0)
	/Users/wangchao/Code/pingcap/tidb/pkg/server/conn.go:393 +0xc8
github.com/pingcap/tidb/pkg/server.(*clientConn).Close(0x140132731e0)
	/Users/wangchao/Code/pingcap/tidb/pkg/server/conn.go:386 +0x94
github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1()
	/Users/wangchao/Code/pingcap/tidb/pkg/server/conn.go:1059 +0x4b8
github.com/pingcap/tidb/pkg/server.(*clientConn).Run(0x140132731e0, {0x10725f2a0, 0x1401393bb30})
	/Users/wangchao/Code/pingcap/tidb/pkg/server/conn.go:1135 +0xa2c
github.com/pingcap/tidb/pkg/server.(*Server).onConn(0x14001bc90e0, 0x140132731e0)
	/Users/wangchao/Code/pingcap/tidb/pkg/server/server.go:739 +0x1a10
created by github.com/pingcap/tidb/pkg/server.(*Server).startNetworkListener in goroutine 565
	/Users/wangchao/Code/pingcap/tidb/pkg/server/server.go:550 +0x980
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #59963, close #59976

Problem Summary:

1. The row container will not be closed if the exclusion panic.
2. The results and cursor will not be reset if there is an error in `cc.flush`.

### What changed and how does it work?

1. Set the row container of stmt right after creating it. Therefore, it can be closed after closing the connection.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/conn_stmt.go [hunk 1]
```diff
@@ -385,8 +385,14 @@ func (cc *clientConn) executeWithCursor(ctx context.Context, stmt PreparedStatem
 		action := memory.NewActionWithPriority(rowContainer.ActionSpill(), memory.DefCursorFetchSpillPriority)
 		vars.MemTracker.FallbackOldAndSetNewAction(action)
 	}
+	// store the rowContainer in the statement right after it's created, so that even if the logic in defer is not triggered,
+	// the rowContainer will be released when the statement is closed.
+	stmt.StoreRowContainer(rowContainer)
 	defer func() {
 		if err != nil {
+			// if the execution panic, it'll not reach this branch. The `rowContainer` will be released in the `stmt.Close`.
```
Comment (Defined2014) [inline pkg/server/conn_stmt.go:393]: The comments it a littile dup with L390.

**Review by Defined2014 — APPROVED** [review]
Please update bazel

**Review by lcwangchao — APPROVED** [review]
