### PR TITLE
planner: fix wrong extend predicate simplification for subquery and nested expressions

### LINKED ISSUE #58451: TiFlash daily test failed after PR 58261 due to resolveColumnIndex failure
[test.txt](https://github.com/user-attachments/files/18224401/test.txt)
The last sql:
```
explain SELECT  ( 4, 5 )  IN ( SELECT 8 , 0 UNION  SELECT 8, 8 ) AS field1 FROM ( D AS table1 RIGHT OUTER JOIN V AS table2 ON (table2 . col_varchar_binary = table1 . col_varchar_binary_key  ) ) WHERE (   EXISTS ( SELECT   SUBQUERY2_t1 . col_decimal_key AS SUBQUERY2_field1 FROM K AS SUBQUERY2_t1    ) ) OR ( table1 . col_varchar_binary_key >= 'm' OR table1 . col_varchar_binary_key  IN ('m') )  GROUP BY field1;
```
Will failed to compile due to the error: 
Can't find column Column#81 in schema Column: [Column#142] PKOrUK: [] NullableUK: []

Use the method of bisection to locate the issue is introduced by https://github.com/pingcap/tidb/pull/58261

### LINKED ISSUE #58509: Tikv cop test failed after PR 58261 due to unexpected result.
After #58261, the copr test failed:
Image

And check that, the first failure of copr test, using the same tikv commit with the last success one, while with tidb new commit #58261:
Image

### PR DESCRIPTION
**Pull request by hawkingrei**
…

### What problem does this PR solve?

Issue Number: close #58509

close #58451

Problem Summary:

### What changed and how does it work?

we will remove some schema info when extending predicate simplification for subqueries and nested expressions. but Those schema info are important and is used in the GroupBy.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/rule_decorrelate.go [hunk 1]
```diff
@@ -160,7 +160,15 @@ func pruneRedundantApply(p base.LogicalPlan) (base.LogicalPlan, bool) {
 	if apply.JoinType != logicalop.LeftOuterJoin && apply.JoinType != logicalop.LeftOuterSemiJoin {
 		return nil, false
 	}
-
+	// add a strong limit for fix the https://github.com/pingcap/tidb/issues/58451. we can remove it when to have better implememnt.
+	// But this problem has affected tiflash CI.
+	applyChildren := apply.Children()
+	if len(applyChildren) >= 2 {
+		corCols := coreusage.ExtractCorColumnsBySchema4LogicalPlan(applyChildren[1], applyChildren[0].Schema())
```
Comment (AilinKid) [inline pkg/planner/core/rule_decorrelate.go:167]: Can you explain the root cause and why this fix works? More details are appreciated

**Review by AilinKid — APPROVED** [review]
