### PR TITLE
ddl: fix a caught panic and add comment for DDL functions

### LINKED ISSUE #54687: Caught panic when canceling DDL jobs
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

check the error message of

https://github.com/pingcap/tidb/blob/2088b342e8f04f362d84cd54ab99f9fc7dc56ddf/pkg/executor/recover_test.go#L578-L582

### 2. What did you expect to see? (Required)

no panic message

### 3. What did you see instead (Required)

[ddl:-1]panic in handling DDL logic and error count beyond the limitation 2, cancelled

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #54687 ref #54436

Problem Summary:

### What changed and how does it work?

- add comments for some DDL functions
- add `updateRawArgs` as a return value of `runOneJobStep`, to decide if RawArgs needs to be updated more accurate

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ddl_worker.go [hunk 1]
```diff
@@ -899,7 +907,27 @@ func (w *worker) prepareTxn(job *model.Job) (kv.Transaction, error) {
 	return txn, err
 }
 
-func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
+// runOneJobStep runs one step of the DDL job and persist the states change. One
+// *step* is defined as the following reason:
```
Comment (D3Hunter) [inline pkg/ddl/ddl_worker.go:911]: other *step*: 1. reorg also has it's own state change, 2. reorg runs in async, it will exter/exist this function to check whether the async routine is done, there is no state change during this time

File: pkg/ddl/ddl_worker.go [hunk 2]
```diff
@@ -899,7 +907,27 @@ func (w *worker) prepareTxn(job *model.Job) (kv.Transaction, error) {
...
+// `runOneJobStepAndWaitSync` waits for other nodes to catch up.
+//
+// - In order to make sure every job is deterministic, idempotent to provide
+// correctness through failover, this function will decide and persist the
+// arguments of a job as a separate *step*. These steps will reuse "schema state"
+// changes, see onRecoverTable as an example.
+//
+// - We may need to use caller `runOneJobStepAndWaitSync` to make sure other node
+// is synchronized before change the job state. So an extra job state *step* is
+// added.
```
Comment (D3Hunter) [inline pkg/ddl/ddl_worker.go:926]: you mean the wait change above runOneJobStep? it's for failover,

File: pkg/ddl/ddl_worker.go [hunk 3]
```diff
@@ -899,7 +907,27 @@ func (w *worker) prepareTxn(job *model.Job) (kv.Transaction, error) {
...
+// - TiDB uses "Asynchronous Schema Change in F1", one job may have multiple
+// *steps* each for a "schema state" such as 'delete only' -> 'write only'. The
+// cluster can only have at most two adjacent schema states for a DDL object.
+// This function forwards one (schema state) *step* and caller
+// `runOneJobStepAndWaitSync` waits for other nodes to catch up.
+//
+// - In order to make sure every job is deterministic, idempotent to provide
+// correctness through failover, this function will decide and persist the
+// arguments of a job as a separate *step*. These steps will reuse "schema state"
+// changes, see onRecoverTable as an example.
```
Comment (D3Hunter) [inline pkg/ddl/ddl_worker.go:922]: you include done->sync in this part? it's not for failover, it must be done in a separate step after wait version.

File: pkg/ddl/ddl_worker.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/ddl_worker.go:926]: Yes the wait change above runOneJobStep. This item wants to describe the job state changes, for example from JobStateDone to JobStateSynced. 

I'm not sure why JobStateDone -> JobStateSynced is relevent to failover. My current understanding is current node (the user connected node) must wait all other nodes to finished synchronize job state, otherwise it breaks the  linearizability (the user connected node shows DDL is finished, but the slow node shows DDL is not finished)

File: pkg/ddl/ddl_worker.go (hunk 3 above)
Comment (lance6716) [reply pkg/ddl/ddl_worker.go:922]: No "done->sync" is included in the item of your above comment. 

This part is like the reason in the comments of onRecoverTable. If the job will change system states (like disable GC) and revert it afterward, if must save the GC state before get running. Otherwise if the job fails between changing states and reverting states, we can't recover the original states.

File: pkg/ddl/ddl_worker.go (hunk 1 above)
Comment (lance6716) [reply pkg/ddl/ddl_worker.go:911]: CI shows the *step* `onLockTables` is not a schema state change. LOCK TABLES may have many table arguments and each step update one table's lock state and persist it. I'll come up with a better comment tomorrow, and align the code to fix UT 😂 Maybe I should keep the old `needUpdateRawArgs` behaviour (if no `runErr` we should marshal RawArgs), and fix wrong `runErr` nilness to close https://github.com/pingcap/tidb/issues/54687

File: pkg/ddl/ddl_worker.go (hunk 2 above)
Comment (D3Hunter) [reply pkg/ddl/ddl_worker.go]: `done`->`synced` might not go through `the wait change above runOneJobStep`, `wait` part might have done in below `waitSchemaChanged`

> JobStateDone -> JobStateSynced is relevant to failover.

suppose owner change during wait, with this state change, we can catch it and wait again on new owner, i.e. the `the wait change above runOneJobStep`

File: pkg/ddl/ddl_worker.go [hunk 4]
```diff
@@ -1181,9 +1174,29 @@ func (w *worker) processJobPausingRequest(d *ddlCtx, job *model.Job) (isRunnable
...
+// Combined with caller transitOneJobStepAndWaitSync waiting for other nodes to
+// catch up with the returned schema version, we can make sure the cluster will
+// only have two adjacent schema state for a DDL object.
+//
+// - Some types of DDL jobs has defined its own *step*s other than F1 paper like
+// onRecoverTable, onLockTables, onCreateIndex, etc. Their purposes are various
+// but they make use of caller transitOneJobStep to persist job changes.
+//
+// - We may need to use caller transitOneJobStepAndWaitSync to make sure all
+// other node is synchronized to provide linearizability. So an extra job state
```
Comment (D3Hunter) [inline pkg/ddl/ddl_worker.go:1192]: please add an example, if i am a new comer, i will ask what is `extra job state`

File: pkg/ddl/ddl_worker.go (hunk 1 above)
Comment (D3Hunter) [reply pkg/ddl/ddl_worker.go]: > reorg runs in async, it will exter/exist this function to check whether the async routine is done, there is no state change during this time

please add this one too

Comment (lance6716) [reply pkg/ddl/ddl_worker.go]: updated some function comments. https://github.com/pingcap/tidb/pull/54685/commits/f782a5208216214e8ca4e9b30872e7584b6859ac

reorg is a bit complex as a breif example in function comments, I only added onLockTables. Please check if it's clear enough.

**Review by D3Hunter — APPROVED** [review]

File: pkg/ddl/ddl_worker.go [hunk 5]
```diff
@@ -1357,11 +1372,22 @@ func (w *worker) runDDLJob(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int64,
...
 
+	// there are too many job types, instead let every job type output its own
+	// updateRawArgs, we try to use these rules as a generalization:
+	//
+	// if job has no error, some arguments may be changed, there's no harm to update
+	// it.
+	updateRawArgs = err == nil
+	// if job changed from running to rolling back, arguments may be changed
+	if prevState == model.JobStateRunning && job.IsRollingback() {
+		updateRawArgs = true
```
Comment (D3Hunter) [inline pkg/ddl/ddl_worker.go:1383]: we should move runtime args change in something like job ctx, we actively mark it if those args changed and fill back depends on the mark

now we are checking whether args are changed passively.

Comment (lance6716) [reply pkg/ddl/ddl_worker.go:1383]: Yes I started in the active way yesterday, and found there are too many cases and many function signatures need to be changed 😂

**Review by tangenta — APPROVED** [review]
