### PR TITLE
planner: steady expression index selection when having duplicate expressions

### LINKED ISSUE #25729: expressional index can be used when have duplicate expresion
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
create table tt(a int, b int, key k((a+1)), key k1((a+1), b), key k2((a+1), b), key k3((a+1)));
desc select * from tt where a+1 = 5 and b=3;
desc select * from tt where a+1 = 5 and b=3;
```

### 2. What did you expect to see? (Required)
stable plan
### 3. What did you see instead (Required)
``` SQL
mysql> desc select * from tt where a+1 = 5 and b=3;
+---------------------------------+---------+-----------+-----------------------------+---------------------------------------------+
| id                              | estRows | task      | access object               | operator info                               |
+---------------------------------+---------+-----------+-----------------------------+---------------------------------------------+
| Projection_4                    | 0.01    | root      |                             | test.tt.a, test.tt.b                        |
| └─IndexLookUp_12                | 0.01    | root      |                             |                                             |
|   ├─IndexRangeScan_9(Build)     | 10.00   | cop[tikv] | table:tt, index:k3(`a` + 1) | range:[5,5], keep order:false, stats:pseudo |
|   └─Selection_11(Probe)         | 0.01    | cop[tikv] |                             | eq(test.tt.b, 3)                            |
|     └─TableRowIDScan_10         | 10.00   | cop[tikv] | table:tt                    | keep order:false, stats:pseudo              |
+---------------------------------+---------+-----------+-----------------------------+---------------------------------------------+
5 rows in set (0.00 sec)

mysql> desc select * from tt where a+1 = 5 and b=3;
+----------------------------------+---------+-----------+--------------------------------+-------------------------------------------------+
| id                               | estRows | task      | access object                  | operator info                                   |
+----------------------------------+---------+-----------+--------------------------------+-------------------------------------------------+
| Projection_4                     | 0.10    | root      |                                | test.tt.a, test.tt.b                            |
| └─IndexLookUp_11                 | 0.10    | root      |                                |                                                 |
|   ├─IndexRangeScan_9(Build)      | 0.10    | cop[tikv] | table:tt, index:k2(`a` + 1, b) | range:[5 3,5 3], keep order:false, stats:pseudo |
|   └─TableRowIDScan_10(Probe)     | 0.10    | cop[tikv] | table:tt                       | keep order:false, stats:pseudo                  |
+----------------------------------+---------+-----------+--------------------------------+-------------------------------------------------+
4 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by zhuo-zhi**
### What problem does this PR solve?

Issue Number: close #25729 

Problem Summary:

- expressional index can be used when have duplicate expression

### What is changed and how it works?

What's Changed:

- Change the logic in selectivity computation in `selectivity.go`.
- Change the logic in virtual column comparison.

How it Works:

- When we have expression indexes that have duplicate expressions, we will have duplicate generated virtual columns. They are one-to-one mapping. Previously, we substitute the expression in the logical plan with a random one of the duplicate generated virtual columns. This will make other duplicate virtual columns pruned out in the logical optimization process. Eventually, a random expression index will be selected. 

- After this commit, we will not prune out the duplicate virtual columns, and let all the expression index paths go into the physical optimization process. Therefore, an optimal index will be selected.

- The selectivity computation of `datasource` will also consider expression indexes that have duplicate expressions after this commit.

### Check List 

Tests 

- Unit test

Side effects

- Some execution plans might change.
- Code complexity.

### Release note 

- planner: steady expression index selection when having duplicate expressions

### CODE REVIEW

File: statistics/selectivity.go [hunk 1]
```diff
@@ -456,3 +456,25 @@ func GetUsableSetsByGreedy(nodes []*StatsNode) (newBlocks []*StatsNode) {
...
 }
+
+// FindPrefixOfIndexByCol will find columns in index by checking the unique id or the virtual expression.
+// So it will return at once no matching column is found.
+func FindPrefixOfIndexByCol(cols []*expression.Column, idxColIDs []int64, cachedPath *planutil.AccessPath) []*expression.Column {
+	if cachedPath != nil {
+		idxCols := cachedPath.IdxCols
+		retCols := make([]*expression.Column, 0, len(idxCols))
+	idLoop:
+		for _, idCol := range idxCols {
```
Comment (winoros) [inline statistics/selectivity.go:467]: @wjhuang2016 Is it possible to reduce the for loop?

**Review by winoros — COMMENTED** [review]
The codes LGTM, but we'd better capitalize the first char of the comment and add a period at the end of the sentence. i.e. Make the comment a full sentence.

File: statistics/selectivity.go (hunk 1 above)
Comment (wjhuang2016) [reply statistics/selectivity.go:467]: No idea.

File: planner/core/find_best_task.go [hunk 2]
```diff
@@ -1281,7 +1288,9 @@ func matchIndicesProp(idxCols []*expression.Column, colLens []int, propItems []p
 		return false
 	}
 	for i, item := range propItems {
-		if colLens[i] != types.UnspecifiedLength || !item.Col.Equal(nil, idxCols[i]) {
+		expr, isOk := item.Col.VirtualExpr.(*expression.ScalarFunction)
```
Comment (wjhuang2016) [inline planner/core/find_best_task.go:1291]: Can we use a function to wrap these code?

Comment (zhuo-zhi) [reply planner/core/find_best_task.go]: Done in the new commit

**Review by wjhuang2016 — APPROVED** [review]

File: planner/core/plan_test.go [hunk 3]
```diff
@@ -589,3 +590,51 @@ func (s *testPlanNormalize) BenchmarkEncodePlan(c *C) {
 		core.EncodePlan(p)
 	}
 }
+
+// Close issue 25729
+func (s *testPlanNormalize) TestIssue25729(c *C) {
+	config.UpdateGlobal(func(conf *config.Config) {
+		conf.Experimental.AllowsExpressionIndex = true
+	})
```
Comment (tangenta) [inline planner/core/plan_test.go:598]: This config is set to true permanently for the following tests. Do we need to restore it to the original value?

File: util/ranger/detacher.go [hunk 4]
```diff
@@ -706,9 +709,10 @@ func removeAccessConditions(conditions, accessConds []expression.Expression) []e
 
 // ExtractAccessConditionsForColumn extracts the access conditions used for range calculation. Since
 // we don't need to return the remained filter conditions, it is much simpler than DetachCondsForColumn.
-func ExtractAccessConditionsForColumn(conds []expression.Expression, uniqueID int64) []expression.Expression {
+func ExtractAccessConditionsForColumn(conds []expression.Expression, col *expression.Column) []expression.Expression {
 	checker := conditionChecker{
-		colUniqueID: uniqueID,
+		colUniqueID: col.UniqueID,
+		checkerCol:  col,
```
Comment (tangenta) [inline util/ranger/detacher.go:715]: Can we remove `colUniqueID`?

File: planner/core/plan_test.go (hunk 3 above)
Comment (zhuo-zhi) [reply planner/core/plan_test.go:598]: Done in the new commit

File: util/ranger/detacher.go (hunk 4 above)
Comment (zhuo-zhi) [reply util/ranger/detacher.go:715]: IMO, this can keep compatibility. If we don't want to compare virtual expressions in some scenarios, we can just use colUniqueID.

Comment (zhuo-zhi) [reply util/ranger/detacher.go]: Oh, I take it wrong. Done in the new commit

**Comment by zhuo-zhi** [comment]
There is some problem with my git commit timestamp. The new commit appears in the past.

**Review by winoros — APPROVED** [review]
