### PR TITLE
ddl: fix error in exchanging list columns partition

### LINKED ISSUE #22207: Exchange list columns partition reports `Partition management on a not partitioned table is not possible`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> create table t1(id char(10)) partition by list columns(id) (partition p0 values in ('a'), partition p1 values in ('b'));
Query OK, 0 rows affected, 1 warning (0.09 sec)

mysql> create table t2(id char(10));
Query OK, 0 rows affected (0.08 sec)

mysql> ALTER TABLE t1 EXCHANGE PARTITION p0 WITH TABLE t2;
ERROR 1505 (HY000): Partition management on a not partitioned table is not possible
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

ERROR 1505 (HY000): Partition management on a not partitioned table is not possible

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #22207  

Problem Summary:

### What is changed and how it works?

What's Changed:
fix error in exchanging list columns partition
How it Works:
Add validation sql in `checkExchangePartitionRecordValidation`

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

File: ddl/partition.go [hunk 1]
```diff
@@ -1335,6 +1335,8 @@ func checkExchangePartitionRecordValidation(w *worker, pt *model.TableInfo, inde
 		} else if len(pi.Columns) == 1 {
 			sql = buildCheckSQLForRangeColumnsPartition(pi, index, schemaName, tableName)
 		}
+	case model.PartitionTypeList:
+		sql = fmt.Sprintf("select 1 from `%s`.`%s` where %s = %s limit 1", schemaName.L, tableName.L, pi.Columns[index], pi.Definitions[index].InValues[index][0])
```
Comment (tangenta) [inline ddl/partition.go:1339]: Shouldn't the SQL be `select 1 from %s.%s where %s not in (ALL OF THE IN VALUES FROM TARGET PARTITION) limit 1`?

File: ddl/db_test.go [hunk 2]
```diff
@@ -6524,3 +6524,12 @@ func (s *testDBSuite4) TestCreateTableWithDecimalWithDoubleZero(c *C) {
 		checkType("test", "tt", "d")
 	*/
 }
+
+func (s *testDBSuite4) TestIssue22207(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test;")
+	tk.MustExec("set @@session.tidb_enable_table_partition = nightly;")
+	tk.MustExec("create table t1(id char(10)) partition by list columns(id) (partition p0 values in ('a'), partition p1 values in ('b'));")
```
Comment (tangenta) [inline ddl/db_test.go:6532]: Please `drop if exists` the table `t1` and `t2` first or create another database to avoid conflict with other tests.

Comment (tangenta) [reply ddl/db_test.go:6532]: BTW, please also insert some rows to the table to verify the correctness.

Comment (TszKitLo40) [reply ddl/db_test.go:6534]: OK, I have added row `a` to t1, PTAL

File: ddl/partition.go [hunk 3]
```diff
@@ -1378,6 +1380,15 @@ func buildCheckSQLForRangeColumnsPartition(pi *model.PartitionInfo, index int, s
 	}
 }
 
+func buildCheckSQLForListPartition(pi *model.PartitionInfo, index int, schemaName, tableName model.CIStr) string {
+	inValues := make([]string, 0, len(pi.Definitions[index].InValues))
+	for _, inValue := range pi.Definitions[index].InValues {
+		inValues = append(inValues, inValue...)
+	}
+	sql := fmt.Sprintf("select 1 from `%s`.`%s` where %s not in (%s) limit 1", schemaName.L, tableName.L, pi.Columns[index], strings.Join(inValues, ","))
```
Comment (xiongjiwei) [inline ddl/partition.go:1388]: is it should be?

```suggestion
	sql := fmt.Sprintf("select 1 from `%s`.`%s` where %s not in (%s) limit 1", schemaName.L, tableName.L, pi.Columns[0].L, strings.Join(inValues, ","))
```

File: ddl/partition.go [hunk 4]
```diff
@@ -1335,6 +1335,8 @@ func checkExchangePartitionRecordValidation(w *worker, pt *model.TableInfo, inde
 		} else if len(pi.Columns) == 1 {
 			sql = buildCheckSQLForRangeColumnsPartition(pi, index, schemaName, tableName)
 		}
+	case model.PartitionTypeList:
```
Comment (xiongjiwei) [inline ddl/partition.go:1338]: well, list partition can be `list` or `list columns` please refer to `PartitionTypeRange`

Comment (TszKitLo40) [reply ddl/partition.go:1338]: OK, I have added `list partition`, PTAL.

File: ddl/partition.go [hunk 5]
```diff
@@ -1378,6 +1384,27 @@ func buildCheckSQLForRangeColumnsPartition(pi *model.PartitionInfo, index int, s
...
+
+func buildCheckSQLForListColumnsPartition(pi *model.PartitionInfo, index int, schemaName, tableName model.CIStr) string {
+	colName := pi.Columns[0].L
+	inValues := getInValues(pi, index)
+	sql := fmt.Sprintf("select 1 from `%s`.`%s` where %s not in (%s) limit 1", schemaName.L, tableName.L, colName, inValues)
+	return sql
+}
+
+func getInValues(pi *model.PartitionInfo, index int) string {
+	inValues := make([]string, 0, len(pi.Definitions[index].InValues))
```
Comment (xiongjiwei) [inline ddl/partition.go:1401]: why not `strings.Join(pi.Definitions[index].InValues, ",")` ?

Comment (TszKitLo40) [reply ddl/partition.go:1401]: `pi.Definitions[index].InValues` is a `[][]string`

Comment (xiongjiwei) [reply ddl/partition.go:1401]: got it

Comment (TszKitLo40) [reply ddl/partition.go:1401]: Any other problems in this issue?

**Review by xiongjiwei — COMMENTED** [review]
LGTM

File: ddl/partition.go [hunk 6]
```diff
@@ -1335,6 +1335,12 @@ func checkExchangePartitionRecordValidation(w *worker, pt *model.TableInfo, inde
 		} else if len(pi.Columns) == 1 {
 			sql = buildCheckSQLForRangeColumnsPartition(pi, index, schemaName, tableName)
 		}
+	case model.PartitionTypeList:
+		if len(pi.Columns) == 0 {
+			sql = buildCheckSQLForListPartition(pi, index, schemaName, tableName)
+		} else {
```
Comment (xhebox) [inline ddl/partition.go:1341]: Lack a check `if len(pi.Columns) == 1`, you are assuming `colName := pi.Columns[0].L`, that `[0]` index in `buildCheckSQLForListColumnsPartition`.

**Review by xhebox — COMMENTED** [review]
Rest LGTM

File: ddl/partition.go (hunk 6 above)
Comment (TszKitLo40) [reply ddl/partition.go]: OK, I have add this check.

**Review by xhebox — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
