### PR TITLE
global sort: use cluster id in file path

### LINKED ISSUE #61537: Using the same `tidb_cloud_storage_uri` value in different clusters may cause file overwriting problem
## Bug Report
When we set the same `tidb_cloud_storage_uri` for different cluster, files uploaded to s3 storage by indexing or import into may overwrite each other, this is will cause unexpected problems, add index or import job may fail. We need to prevent such problems from occurring.
Please answer these questions before submitting your issue. Thanks!

### 4. What is your TiDB version? (Required)
v8.5

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #61537 

Problem Summary:
As the pr title said.

### What changed and how does it work?
We can add the cluster id to the path when we use the `tidb_cloud_storage_uri`. The  cluster id is unique and it can avoid path repetition.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
After setting the variable, test import into and add index with this pr, the file in s3 is in the cluster id folder. The import into and add index can succeed normally.
```
mysql> select @@tidb_cloud_storage_uri\G;
*************************** 1. row ***************************
@@tidb_cloud_storage_uri: s3://qe-testing/kernel-testing/fzzf678/global-sort-dir/plan-431?access-key=xxxxxx&endpoint=abc.com&force-path-style=false&provider=ks&region=Beijing&secret-access-key=xxxxxx
1 row in set (0.01 sec)
```

截屏2025-06-06 15 46 16

截屏2025-06-06 15 51 30

image

```
mysql> show import job 1\G;
*************************** 1. row ***************************
          Job_ID: 1
     Data_Source: 
    Target_Table: `test`.`sbtest1`
        Table_ID: 114
           Phase:
          Status: finished
Source_File_Size: 10.71GiB
   Imported_Rows: 360000
  Result_Message:
     Create_Time: 2025-06-06 07:44:11.855473
      Start_Time: 2025-06-06 07:44:12.374703
        End_Time: 2025-06-06 07:48:23.876170
      Created_By: root@%
1 row in set (0.02 sec)

mysql> admin show ddl jobs 1\G;
*************************** 1. row ***************************
      JOB_ID: 117
     DB_NAME: test
  TABLE_NAME: sbtest1
    JOB_TYPE: add index
SCHEMA_STATE: public
   SCHEMA_ID: 2
    TABLE_ID: 114
   ROW_COUNT: 360000
 CREATE_TIME: 2025-06-06 07:51:11.867000
  START_TIME: 2025-06-06 07:51:11.867000
    END_TIME: 2025-06-06 07:51:34.217000
       STATE: synced
    COMMENTS: ingest, DXF, cloud, max_node_count=3
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/handle/handle.go [hunk 1]
```diff
@@ -267,6 +271,21 @@ func GetTargetScope() string {
...
 }
 
+// GetCloudStorageURI returns the cloud storage URI with cluster ID appended to the path.
+func GetCloudStorageURI(store kv.Storage) string {
+	cloudURI := vardef.CloudStorageURI.Load()
+	if s, ok := store.(kv.StorageWithPD); ok {
+		// When setting the cloudURI value by SQL, we already checked the effectiveness, so we don't need to check it again here.
+		u, _ := litstorage.ParseRawURL(cloudURI)
+		if len(u.Path) != 0 {
+			u.Path = filepath.Join(u.Path, strconv.FormatUint(s.GetPDClient().GetClusterID(context.TODO()), 10))
```
Comment (tangenta) [inline pkg/disttask/framework/handle/handle.go]:
```suggestion
			u.Path = filepath.Join(u.Path, strconv.FormatUint(s.GetPDClient().GetClusterID(ctx), 10))
```

Maybe use the real context?

Comment (fzzf678) [reply pkg/disttask/framework/handle/handle.go]: update in https://github.com/pingcap/tidb/pull/61502/commits/7e36fdec513f0fc58d7bcf291acfc5968d826e27

File: pkg/disttask/framework/handle/handle.go [hunk 2]
```diff
@@ -267,6 +271,21 @@ func GetTargetScope() string {
 	return vardef.ServiceScope.Load()
 }
 
+// GetCloudStorageURI returns the cloud storage URI with cluster ID appended to the path.
+func GetCloudStorageURI(store kv.Storage, ctx context.Context) string {
```
Comment (tangenta) [inline pkg/disttask/framework/handle/handle.go]: The convention is to pass the context as the first argument :)

Comment (fzzf678) [reply pkg/disttask/framework/handle/handle.go]: Yes, :(

**Review by tangenta — APPROVED** [review]

File: pkg/disttask/framework/handle/handle.go [hunk 3]
```diff
@@ -267,6 +271,21 @@ func GetTargetScope() string {
...
 }
 
+// GetCloudStorageURI returns the cloud storage URI with cluster ID appended to the path.
+func GetCloudStorageURI(ctx context.Context, store kv.Storage) string {
+	cloudURI := vardef.CloudStorageURI.Load()
+	if s, ok := store.(kv.StorageWithPD); ok {
+		// When setting the cloudURI value by SQL, we already checked the effectiveness, so we don't need to check it again here.
+		u, _ := litstorage.ParseRawURL(cloudURI)
+		if len(u.Path) != 0 {
+			u.Path = filepath.Join(u.Path, strconv.FormatUint(s.GetPDClient().GetClusterID(ctx), 10))
```
Comment (lance6716) [inline pkg/disttask/framework/handle/handle.go]: nit: `path` is more proper to be used with URL than `filepath`

File: pkg/disttask/framework/handle/handle.go [hunk 4]
```diff
@@ -267,6 +271,21 @@ func GetTargetScope() string {
...
+	cloudURI := vardef.CloudStorageURI.Load()
+	if s, ok := store.(kv.StorageWithPD); ok {
+		// When setting the cloudURI value by SQL, we already checked the effectiveness, so we don't need to check it again here.
+		u, _ := litstorage.ParseRawURL(cloudURI)
+		if len(u.Path) != 0 {
+			u.Path = path.Join(u.Path, strconv.FormatUint(s.GetPDClient().GetClusterID(ctx), 10))
+			return u.String()
+		}
+	}
+	logutil.BgLogger().Error("Can't get cluster id from store, use default cloud storage uri")
```
Comment (Benjamin2037) [inline pkg/disttask/framework/handle/handle.go:285]: What scenario we can not get cluster id? Should we accept this? and can we solve this error by retry?

Comment (Benjamin2037) [inline pkg/disttask/framework/handle/handle.go:285]: Can we add a test case to cover this fail to get cluster id path?

Comment (fzzf678) [reply pkg/disttask/framework/handle/handle.go:285]: In actual scenarios, the tikv is always comes with pd, so we will not meet this scenario. I wrote this to serve as a reminder and protection of unexpected invoking.

Comment (fzzf678) [reply pkg/disttask/framework/handle/handle.go:285]: Currently i can't find a case hit here.
`if s, ok := store.(kv.StorageWithPD); ok {`
But is our code, some places check this type conversion and some did't,  I think it's more safe to do this check, so i add a log here and use the default url if some unexpected occur.

**Review by Benjamin2037 — APPROVED** [review]
LGTM
