### PR TITLE
session: fix a bug that upgrading from 3.1.1 to 4.0 fails

### LINKED ISSUE #17292: upgrade from 3.1.1 to 4.0.0 rc2 fails
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

git checkout v3.1.1
make && run
exit
git checkout v4.0.0-rc.2
make && run

```
[2020/05/19 19:05:28.386 +08:00] [INFO] [ddl_worker.go:130] ["[ddl] start DDL worker"] [worker="worker 4, tp add index"]
[2020/05/19 19:05:28.389 +08:00] [INFO] [domain.go:144] ["full load InfoSchema success"] [usedSchemaVersion=0] [neededSchemaVersion=39] ["start time"=2.534285ms]
[2020/05/19 19:05:28.389 +08:00] [INFO] [domain.go:368] ["full load and reset schema validator"]
[2020/05/19 19:05:28.391 +08:00] [WARN] [cache.go:274] ["load mysql.user fail"] [error="[planner:1054]Unknown column 'reload_priv' in 'field list'"]
[2020/05/19 19:05:28.392 +08:00] [FATAL] [terror.go:348] ["unexpected error"] [error="[privilege:8049]mysql.user"] [stack="github.com/pingcap/log.Fatal\n\t/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/global.go:59\ngithub.com/pingcap/parser/terror.MustNil\n\t/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/parser@v0.0.0-20200427031542-879c7bd4f27d/terror/terror.go:348\nmain.createStoreAndDomain\n\t/Users/bba/pc/tidb/tidb-server/main.go:296\nmain.main\n\t/Users/bba/pc/tidb/tidb-server/main.go:181\nruntime.main\n\t/Users/bba/.gvm/gos/go1.13/src/runtime/proc.go:203"]
```

### 4. Affected version (Required)
v3.1.1

### 5. Root Cause Analysis
The server version 39 in v3.1.1 is not consistent with v4.0+

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #17292 

Problem Summary:
The server version 39 in v3.1.1 is not consistent with v4.0+
### What is changed and how it works?

Add a new server version 46, and redo version 39.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
git checkout v3.1.1
make && run
exit
git checkout this_pr
make && run
success

Side effects

### Release note 
- fix a bug that upgrading from 3.1.1 to 4.0 fails

### CODE REVIEW

File: session/bootstrap.go [hunk 1]
```diff
@@ -1045,6 +1048,16 @@ func upgradeToVer45(s Session, ver int64) {
 	mustExecute(s, "UPDATE HIGH_PRIORITY mysql.user SET Config_priv='Y' where Super_priv='Y'")
 }
 
+func upgradeToVer46(s Session, ver int64) {
```
Comment (bb7133) [inline session/bootstrap.go:1051]: Please add a comment for it(why it is duplicated with version39)
