### PR TITLE
ddl: check owner status before commit DDL changes

### LINKED ISSUE #47105: flaky test TestAddIndexIngestRecoverPartition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
     testkit.go:136: 
        	Error Trace:	testkit/testkit.go:136
        	            				testkit/testkit.go:129
        	            				ddl/ingest/tests/partition_table_test.go:35
        	Error:      	Received unexpected error:
        	            	[schema:1050]Table 't' already exists
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:174
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob
        	            		ddl/ddl.go:1196
        	            	github.com/pingcap/tidb/ddl.(*ddl).CreateTableWithInfo
        	            		ddl/ddl_api.go:2728
        	            	github.com/pingcap/tidb/ddl.(*ddl).CreateTable
        	            		ddl/ddl_api.go:2568
        	            	github.com/pingcap/tidb/executor.(*DDLExec).executeCreateTable
        	            		executor/ddl.go:265
        	            	github.com/pingcap/tidb/executor.(*DDLExec).Next
        	            		executor/ddl.go:157
        	            	github.com/pingcap/tidb/executor/internal/exec.Next
        	            		executor/internal/exec/executor.go:283
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).next
        	            		executor/adapter.go:1223
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
        	            		executor/adapter.go:968
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
        	            		executor/adapter.go:794
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).Exec
        	            		executor/adapter.go:575
        	            	github.com/pingcap/tidb/session.runStmt
        	            		session/session.go:2421
        	            	github.com/pingcap/tidb/session.(*session).ExecuteStmt
        	            		session/session.go:2271
        	            	github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext
        	            		testkit/testkit.go:353
        	            	github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext
        	            		testkit/testkit.go:134
        	            	github.com/pingcap/tidb/testkit.(*TestKit).MustExec
        	            		testkit/testkit.go:129
        	            	ddl/ingest/tests/tests_test.TestAddIndexIngestRecoverPartition
        	            		ddl/ingest/tests/partition_table_test.go:35
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
        	Test:       	TestAddIndexIngestRecoverPartition
        	Messages:   	sql:create table t (a int primary key, b int) partition by hash(a) partitions 8;, [], error stack [schema:1050]Table 't' already exists
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:174
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob
        	            		ddl/ddl.go:1196
        	            	github.com/pingcap/tidb/ddl.(*ddl).CreateTableWithInfo
        	            		ddl/ddl_api.go:2728
        	            	github.com/pingcap/tidb/ddl.(*ddl).CreateTable
        	            		ddl/ddl_api.go:2568
        	            	github.com/pingcap/tidb/executor.(*DDLExec).executeCreateTable
        	            		executor/ddl.go:265
        	            	github.com/pingcap/tidb/executor.(*DDLExec).Next
        	            		executor/ddl.go:157
        	            	github.com/pingcap/tidb/executor/internal/exec.Next
        	            		executor/internal/exec/executor.go:283
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).next
        	            		executor/adapter.go:1223
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
        	            		executor/adapter.go:968
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
        	            		executor/adapter.go:794
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).Exec
        	            		executor/adapter.go:575
        	            	github.com/pingcap/tidb/session.runStmt
        	            		session/session.go:2421
        	            	github.com/pingcap/tidb/session.(*session).ExecuteStmt
        	            		session/session.go:2271
        	            	github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext
        	            		testkit/testkit.go:353
        	            	github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext
        	            		testkit/testkit.go:134
        	            	github.com/pingcap/tidb/testkit.(*TestKit).MustExec
        	            		testkit/testkit.go:129
        	            	ddl/ingest/tests/tests_test.TestAddIndexIngestRecoverPartition
        	            		ddl/ingest/tests/partition_table_test.go:35
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/47103/tiprow_fast_test/1704289474566950912

### LINKED ISSUE #50055: flaky test TestFrameworkWithQuery
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
 --- FAIL: TestFrameworkWithQuery (2.06s)
    testkit.go:138: 
        	Error Trace:	pkg/testkit/testkit.go:138
        	            				pkg/testkit/testkit.go:131
        	            				pkg/disttask/framework/framework_test.go:131
        	Error:      	Received unexpected error:
        	            	[schema:1050]Table 't' already exists
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:174
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).DoDDLJob
        	            		pkg/ddl/ddl.go:1171
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).CreateTableWithInfo
        	            		pkg/ddl/ddl_api.go:2747
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).CreateTable
        	            		pkg/ddl/ddl_api.go:2586
        	            	github.com/pingcap/tidb/pkg/executor.(*DDLExec).executeCreateTable
        	            		pkg/executor/ddl.go:267
        	            	github.com/pingcap/tidb/pkg/executor.(*DDLExec).Next
        	            		pkg/executor/ddl.go:159
        	            	github.com/pingcap/tidb/pkg/executor/internal/exec.Next
        	            		pkg/executor/internal/exec/executor.go:314
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next
        	            		pkg/executor/adapter.go:1252
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor
        	            		pkg/executor/adapter.go:997
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay
        	            		pkg/executor/adapter.go:823
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec
        	            		pkg/executor/adapter.go:598
        	            	github.com/pingcap/tidb/pkg/session.runStmt
        	            		pkg/session/session.go:2380
        	            	github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt
        	            		pkg/session/session.go:2239
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext
        	            		pkg/testkit/testkit.go:364
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext
        	            		pkg/testkit/testkit.go:136
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec
        	            		pkg/testkit/testkit.go:131
        	            	pkg/disttask/framework/framework_test_test.TestFrameworkWithQuery
        	            		pkg/disttask/framework/framework_test.go:131
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
        	Test:       	TestFrameworkWithQuery
        	Messages:   	sql:create table t(a int not null, b int not null), [], error stack [schema:1050]Table 't' already exists
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:174
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).DoDDLJob
        	            		pkg/ddl/ddl.go:1171
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).CreateTableWithInfo
        	            		pkg/ddl/ddl_api.go:2747
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).CreateTable
        	            		pkg/ddl/ddl_api.go:2586
        	            	github.com/pingcap/tidb/pkg/executor.(*DDLExec).executeCreateTable
        	            		pkg/executor/ddl.go:267
        	            	github.com/pingcap/tidb/pkg/executor.(*DDLExec).Next
        	            		pkg/executor/ddl.go:159
        	            	github.com/pingcap/tidb/pkg/executor/internal/exec.Next
        	            		pkg/executor/internal/exec/executor.go:314
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next
        	            		pkg/executor/adapter.go:1252
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor
        	            		pkg/executor/adapter.go:997
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay
        	            		pkg/executor/adapter.go:823
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec
        	            		pkg/executor/adapter.go:598
        	            	github.com/pingcap/tidb/pkg/session.runStmt
        	            		pkg/session/session.go:2380
        	            	github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt
        	            		pkg/session/session.go:2239
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext
        	            		pkg/testkit/testkit.go:364
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext
        	            		pkg/testkit/testkit.go:136
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec
        	            		pkg/testkit/testkit.go:131
        	            	pkg/disttask/framework/framework_test_test.TestFrameworkWithQuery
        	            		pkg/disttask/framework/framework_test.go:131
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
FAIL
================================================================================
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #50055, close #47105

Problem Summary:

Timeline:

1. `TestFrameworkWithQuery` creates multiple domains in order to test the distributed environment.
2. These domains create & initialize their own DDL structures one by one.
3. The first domain(tidb-0) checks that it is DDL owner, and trying to load DDL jobs and run them. [go runtime is lagging for a while]
4. The second domain(tidb-1) starts, `InitOwner()` assign the DDL owner to tidb-1.
5. tidb-1 starts to load DDL jobs. At the same time, the goroutine in step 3 continues to run.

As a result, there are two DDL owners running the same job concurrently.

### What changed and how does it work?

Before updating the error to job table, TiDB should check whether it is owner itself.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ddl_worker.go [hunk 1]
```diff
@@ -958,20 +958,22 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
...
 		return 0, err
 	}
 	writeBinlog(d.binlogCli, txn, job)
 	// reset the SQL digest to make topsql work right.
 	w.sess.GetSessionVars().StmtCtx.ResetSQLDigest(job.Query)
+	if !w.ddlCtx.isOwner() {
+		// This TiDB instance is not DDL owner anymore, it should not commit any transaction.
+		w.sess.Rollback()
+		return 0, dbterror.ErrNotOwner
+	}
```
Comment (ywqzzy) [inline pkg/ddl/ddl_worker.go:975]: Should we do this before HandleJobDone？

Comment (tangenta) [reply pkg/ddl/ddl_worker.go:980]: bc33faf467b5b875b9bc74e8163117c9e7c598b0

File: pkg/ddl/ddl_worker.go [hunk 2]
```diff
@@ -930,13 +935,13 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
 	// If running job meets error, we will save this error in job Error
 	// and retry later if the job is not cancelled.
 	schemaVer, runJobErr = w.runDDLJob(d, t, job)
+	defer d.unlockSchemaVersion(job.ID)
```
Comment (zimulala) [inline pkg/ddl/ddl_worker.go:938]: This should result in a long lock time, such as when `runJobErr! = nil &&errorIsRetryable (runJobErr, job)` is true, it will sleep for a while.

Comment (tangenta) [reply pkg/ddl/ddl_worker.go]: e4e36256cd68ad6a46a18f75f994621db8b30926

File: pkg/ddl/ddl_worker.go [hunk 3]
```diff
@@ -970,6 +975,12 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
 	writeBinlog(d.binlogCli, txn, job)
 	// reset the SQL digest to make topsql work right.
 	w.sess.GetSessionVars().StmtCtx.ResetSQLDigest(job.Query)
+	if !w.ddlCtx.isOwner() {
+		// This TiDB instance is not DDL owner anymore, it should not commit any transaction.
+		w.sess.Rollback()
+		d.unlockSchemaVersion(job.ID)
+		return 0, dbterror.ErrNotOwner
+	}
 	err = w.sess.Commit()
```
Comment (zimulala) [inline pkg/ddl/ddl_worker.go:984]: Could we encapsulate the check and the commit into a function? In this way, we can more uniform processing.

Comment (tangenta) [reply pkg/ddl/ddl_worker.go:984]: For `HandleJobDone` we cannot wrap it together with `commit` because `finishDDLJob` has other logic.

Comment (tangenta) [reply pkg/ddl/ddl_worker.go]: 1fc432f9a8b293040deb3b0104bad80020a09c78

File: pkg/ddl/ddl_worker.go [hunk 4]
```diff
@@ -940,6 +945,11 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
 	d.mu.hook.OnJobRunAfter(job)
 	d.mu.RUnlock()
 
+	if err = w.checkOwnerBeforeCommit(); err != nil {
```
Comment (zimulala) [inline pkg/ddl/ddl_worker.go]: Do we need to do this in line933？

**Review by zimulala — APPROVED** [review]

**Review by zimulala — APPROVED** [review]

**Review by ywqzzy — APPROVED** [review]
