### PR TITLE
planner, executor: return TableDual in tryFastPlan for predicate like handlePK=1.1

### LINKED ISSUE #10677: wrong result for `select * from t where int_pk = 1.1`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
tidb> drop table t;
Query OK, 0 rows affected (0.03 sec)

tidb> create table t(a int signed primary key);
Query OK, 0 rows affected (0.00 sec)

tidb> insert into t values(1);
Query OK, 1 row affected (0.00 sec)


```

2. What did you expect to see?
empty set

3. What did you see instead?
``` sql
tidb> desc select * from t where a = 1.1;
+-------------+-------+------+-------------------+
| id          | count | task | operator info     |
+-------------+-------+------+-------------------+
| Point_Get_1 | 1.00  | root | table:t, handle:1 |
+-------------+-------+------+-------------------+
1 row in set (0.00 sec)

tidb> select * from t where a = 1.1;
+---+
| a |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
``` sql
Release Version: v3.0.0-rc.1-142-g6c31c9b50
Git Commit Hash: 6c31c9b503b1375097560f9960bebc44957bfb2e
Git Branch: master
UTC Build Time: 2019-06-03 07:47:44
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
Fix #10677 

### What is changed and how it works?
Return TableDual when the predicate is `PKIsHandle = 1.1`.

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects

N/A

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -3857,6 +3857,22 @@ func (s *testSuite) TestIssue10448(c *C) {
 	tk.MustQuery("desc select * from t where pk = 9223372036854775808").Check(testkit.Rows("Point_Get_1 1.00 root table:t, handle:9223372036854775808"))
 }
 
+func (s *testSuite) TestIssue10677(c *C) {
```
Comment (zz-jason) [inline executor/executor_test.go]: maybe it's more proper to move this test to `testPointGetSuite`
