### PR TITLE
*: don't save table IDs in schema diff of FLASHBACK DATABASE

### LINKED ISSUE #54415: Can't FLASHBACK DATABASE if there're too many tables under the database
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

drop a database with 10080 tables.

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

```
mysql> FLASHBACK DATABASE db_99;
ERROR 8025 (HY000): entry too large, the max entry size is 6291456, the size of data is 30582644
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #54415

Problem Summary:

### What changed and how does it work?

as title. Follow up of https://github.com/pingcap/tidb/pull/54439

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/parser/model/ddl.go [hunk 1]
```diff
@@ -1199,6 +1199,9 @@ type SchemaDiff struct {
 	OldSchemaID int64 `json:"old_schema_id"`
 	// RegenerateSchemaMap means whether to rebuild the schema map when applying to the schema diff.
 	RegenerateSchemaMap bool `json:"regenerate_schema_map"`
+	// RecoverSnapshotTS is set when the diff is too large to be saved in SchemaDiff.
+	// infoschema should use this TS to read meta directly.
+	RecoverSnapshotTS uint64 `json:"recover_snapshot_ts,omitempty"`
```
Comment (D3Hunter) [inline pkg/parser/model/ddl.go:1204]: what if: after flashback schema job to done, and before reload, GC remove all those keys

File: pkg/infoschema/infoschema_v2.go [hunk 2]
```diff
@@ -871,6 +871,25 @@ func applyDropSchema(b *Builder, diff *model.SchemaDiff) []int64 {
 }
 
 func applyRecoverSchema(b *Builder, m *meta.Meta, diff *model.SchemaDiff) ([]int64, error) {
+	if snapTS := diff.RecoverSnapshotTS; snapTS > 0 {
```
Comment (D3Hunter) [inline pkg/infoschema/infoschema_v2.go:874]: i prefer reload from now, there is no difference.

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/parser/model/ddl.go (hunk 1 above)
Comment (lance6716) [reply pkg/parser/model/ddl.go:1204]: I remember it will fallback to full ode

https://github.com/pingcap/tidb/blob/e858f55f62321b94be2f4962c3c4524a4505d2a6/pkg/domain/domain.go#L345

File: pkg/infoschema/infoschema_v2.go (hunk 2 above)
Comment (lance6716) [reply pkg/infoschema/infoschema_v2.go:874]: Just in case the database is relatively small compared with full load.

Comment (D3Hunter) [reply pkg/infoschema/infoschema_v2.go:874]: why full load? i mean load using current ts, not this saved one

File: pkg/parser/model/ddl.go (hunk 1 above)
Comment (D3Hunter) [reply pkg/parser/model/ddl.go:1204]: we can reload this schema only if we use current ts

File: pkg/infoschema/infoschema_v2.go (hunk 2 above)
Comment (lance6716) [reply pkg/infoschema/infoschema_v2.go]: https://github.com/pingcap/tidb/pull/54665/commits/8f5520c93e14a845ac39c84aa35b654f90d774a7

**Review by D3Hunter — APPROVED** [review]
