### PR TITLE
tikv: add size limit to batch get cache

### LINKED ISSUE #19560: Unbounded memory usage of `BatchGet`'s cache
## Bug Report

The internal cache used by `BatchGet` need a size limit, it is OK to randomly discard some entry in it.

### 1. Minimal reproduce step (Required)
Start a transaction, do a lot of batch get.

### 2. What did you expect to see? (Required)
Low memory usage.

### 3. What did you see instead (Required)
Unbounded memory usage.

图片

### 4. What is your TiDB version? (Required)
v4.0, master

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve?

Issue Number: close #19560 

The internal cache used by `BatchGet` need a size limit, it is OK to randomly discard some entry in it.

### What is changed and how it works?
Add a size limit which equals to default `TxnTotalSizeLimit`. We can delete some entry from it randomly when the limit is exceeded.

### Release note 

- No release note.

### CODE REVIEW

**Review by jackysp — COMMENTED** [review]
LGTM

File: store/tikv/snapshot.go [hunk 1]
```diff
@@ -174,7 +175,23 @@ func (s *tikvSnapshot) BatchGet(ctx context.Context, keys []kv.Key) (map[string]
 		s.mu.cached = make(map[string][]byte, len(m))
 	}
 	for _, key := range keys {
-		s.mu.cached[string(key)] = m[string(key)]
+		val := m[string(key)]
+		s.mu.cachedSize += len(key) + len(val)
+		s.mu.cached[string(key)] = val
+	}
+
+	const cachedSizeLimit = 10 << 30
```
Comment (jackysp) [inline store/tikv/snapshot.go:183]: We could change it to a const for https://github.com/pingcap/tidb/blob/9af236c1b7f8f8050e9c163a78b83ec4564b9e2e/config/config.go#L965 and this one in another PR.

**Comment by tiancaiamao** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]
