### PR TITLE
planner: fix wrong HashAgg estrows for inner operator of index join

### LINKED ISSUE #59902: The estrows is wrong for inner operator of index join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t1(a int primary key, b int);
create table t2(a int, b int, key idx(a));
set tidb_enable_inl_join_inner_multi_pattern=on;
explain select t1.b,(select count(*) from t2 where t2.a=t1.a) as a from t1 where t1.a=1;

### 2. What did you expect to see? (Required)

The hashagg operator has the same estrows with the selection operator.

### 3. What did you see instead (Required)

```
+-----------------------------------+---------+-----------+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| id                                | estRows | task      | access object              | operator info                                                                                                                            |
+-----------------------------------+---------+-----------+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_12                     | 1.00    | root      |                            | test.t1.b, ifnull(Column#10, 0)->Column#10                                                                                               |
| └─IndexHashJoin_21                | 1.00    | root      |                            | left outer join, inner:HashAgg_17, left side:Point_Get_39, outer key:test.t1.a, inner key:test.t2.a, equal cond:eq(test.t1.a, test.t2.a) |
|   ├─Point_Get_39(Build)           | 1.00    | root      | table:t1, index:PRIMARY(a) |                                                                                                                                          |
|   └─HashAgg_17(Probe)             | 7992.00 | root      |                            | group by:test.t2.a, funcs:count(Column#11)->Column#10, funcs:firstrow(test.t2.a)->test.t2.a                                              |
|     └─IndexReader_18              | 7992.00 | root      |                            | index:HashAgg_16                                                                                                                         |
|       └─HashAgg_16                | 7992.00 | cop[tikv] |                            | group by:test.t2.a, funcs:count(1)->Column#11                                                                                            |
|         └─Selection_15            | 1.00    | cop[tikv] |                            | not(isnull(test.t2.a))                                                                                                                   |
|           └─IndexRangeScan_14     | 1.00    | cop[tikv] | table:t2, index:idx(a)     | range: decided by [eq(test.t2.a, test.t1.a)], keep order:false, stats:pseudo                                                             |
+-----------------------------------+---------+-----------+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------+
```

### 4. What is your TiDB version? (Required)

v8.5.1

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #59902

Problem Summary:

### What changed and how does it work?

in the ```constructIndexJoinInnerSideTaskWithAggCheck```, we forget to transfer the parents stats by the child stats.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix wrong HashAgg estrows for inner operator of index join

修复 index join 的 inner operator 中 HashAgg 估算行数错误的问题
```

### CODE REVIEW

File: pkg/planner/core/exhaust_physical_plans.go [hunk 1]
```diff
@@ -1535,7 +1535,16 @@ func constructIndexJoinInnerSideTaskWithAggCheck(p *logicalop.LogicalJoin, prop
...
 	// build hash agg, when the stream agg is illegal such as the order by prop is not matched
 	if aggTask == nil {
-		physicalHashAgg := NewPhysicalHashAgg(la, la.StatsInfo(), prop)
+		stats := la.StatsInfo()
+		if dsCopTask.indexPlan != nil {
+			stats = stats.ScaleByExpectCnt(dsCopTask.indexPlan.StatsInfo().RowCount)
+		} else if dsCopTask.tablePlan != nil {
+			stats = stats.ScaleByExpectCnt(dsCopTask.tablePlan.StatsInfo().RowCount)
+		}
+		physicalHashAgg := NewPhysicalHashAgg(
```
Comment (elsa0520) [inline pkg/planner/core/exhaust_physical_plans.go:1544]:
```suggestion
		physicalHashAgg := NewPhysicalHashAgg(la, stats, prop)
```

**Comment by elsa0520** [comment]
The stream agg also should be changed together

File: pkg/planner/core/exhaust_physical_plans.go [hunk 2]
```diff
@@ -1535,7 +1535,16 @@ func constructIndexJoinInnerSideTaskWithAggCheck(p *logicalop.LogicalJoin, prop
 
 	// build hash agg, when the stream agg is illegal such as the order by prop is not matched
 	if aggTask == nil {
-		physicalHashAgg := NewPhysicalHashAgg(la, la.StatsInfo(), prop)
+		stats := la.StatsInfo()
```
Comment (elsa0520) [inline pkg/planner/core/exhaust_physical_plans.go:1538]: Could we build this stats before build the physicalxxxAgg ? Then we can use this new stats in the streamagg and the hashagg. Don't compute the stats twice

Comment (hawkingrei) [reply pkg/planner/core/exhaust_physical_plans.go:1538]: Actually, the change in his stats is also due to changes in the planner. Therefore, recalculation is needed when changes occur. Currently, the stats for all NewPhysicalHashAgg instances are computed in real time when they are called.

**Comment by hawkingrei** [comment]
> The stream agg also should be changed together

I have updated it.

File: pkg/planner/core/exhaust_physical_plans.go (hunk 2 above)
Comment (AilinKid) [reply pkg/planner/core/exhaust_physical_plans.go:1523]: @elsa0520, the stats from indexPlan or tablePlan is recomputed for single time, the original logic stats is derived for entire inner side. But i think we can merge this two logic together because we don't care it's is stream or hash one.

File: pkg/planner/core/exhaust_physical_plans.go [hunk 3]
```diff
@@ -1504,16 +1504,29 @@ func constructIndexJoinInnerSideTaskWithAggCheck(p *logicalop.LogicalJoin, prop
 				physicalIndexScan, _ = dsCopTask.indexPlan.Children()[0].(*PhysicalIndexScan)
 			}
 			if physicalIndexScan != nil {
+				stats := la.StatsInfo()
```
Comment (elsa0520) [inline pkg/planner/core/exhaust_physical_plans.go:1507]: Please reduce the duplication of code. Calculate stats only once.

Comment (hawkingrei) [reply pkg/planner/core/exhaust_physical_plans.go]: I have merged the two parts of the code.

File: pkg/planner/core/exhaust_physical_plans.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/planner/core/exhaust_physical_plans.go]: I have merged the two parts of the code.

**Review by AilinKid — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
