### PR TITLE
copr: Build cop task should not cancel bo ctx

### LINKED ISSUE #64840: Incorrect usage of context when building cop tasks that may cause backoffer unable to work
## Bug Report

This is a bug introduced by **#56923**. 

In the following code:

https://github.com/pingcap/tidb/blob/a92bbc50f70162a4a4797b27fb8f346505c82d21/pkg/store/copr/coprocessor.go#L359-L364

Here the backoffer `bo` is passed from outside the function. But when processing `MaxExecutionTime`, it wraps the ctx with `context.WithTimeout`, sets the wrapped ctx into the `bo`, and calls `defer cancel()` in the same function. This may cause the ctx of the `bo` to be canceled when the function `buildCopTasks` exits, whihe the execution of the coprocessor haven't been started.  Since then, theoretically, all kinds of errors that's retryable (and requires backing off) will actually cause failures immediately instead, which is unexpected.

It's likely to be the reason that `BucketVersionNotMatch` errors are thrown directly to the user's client, which have happend several times in our user's clusters. We are still confirming that for now.

### 1. Minimal reproduce step (Required)

The following reproduction steps are not confirmed yet.

1. Start a coprocessor query with non-zero max_execution_time
2. Let TiKV generate a `bucket_version_not_match` error for the coprocessor query. This can be simulated using failpoints.

### 2. What did you expect to see? (Required)

It executes normally after a retry.

### 3. What did you see instead (Required)

The `bucket_version_not_match` error is directly reported to the user side.

### 4. What is your TiDB version? (Required)

master, release-nextgen-20251011

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #64840

Problem Summary:

### What changed and how does it work?
save `ctx` in `Backoffer` is not a best practise for golang, however, it need too many changes if we want to refactor this part of code.
So in this pr, it just set `Backoffer`'s ctx to the orginal context.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/store/copr/coprocessor.go [hunk 1]
```diff
@@ -510,10 +510,14 @@ func buildCopTasks(bo *Backoffer, ranges *KeyRanges, opt *buildCopTaskOpt) ([]*c
 	})
 
 	if req.MaxExecutionTime > 0 {
+		orgCtx := bo.GetCtx()
 		// If the request has a MaxExecutionTime, we need to set the deadline of the context.
-		ctxWithTimeout, cancel := context.WithTimeout(bo.GetCtx(), time.Duration(req.MaxExecutionTime)*time.Millisecond)
-		defer cancel()
+		ctxWithTimeout, cancel := context.WithTimeout(orgCtx, time.Duration(req.MaxExecutionTime)*time.Millisecond)
 		bo.TiKVBackoffer().SetCtx(ctxWithTimeout)
```
Comment (cfzjywxk) [inline pkg/store/copr/coprocessor.go]: If the original purpose of <https://github.com/pingcap/tidb/pull/56923> was solely to control PD RPC timeouts, why not modify only the PD RPC-related call handling logic—for example, by creating a separate backoffer specifically for PD RPC calls? Altering the backoffer at a higher level, even if restored afterward, makes it difficult to argue whether there are other side effects.

Comment (windtalker) [reply pkg/store/copr/coprocessor.go]: i think the original pr is try to make max_execution_time take affect for buildcoptask, pd rpc is just the most likely part inside buildcoptask that may take a long time

Comment (cfzjywxk) [reply pkg/store/copr/coprocessor.go]: How about creating a seperate backoffer, its lifecycle is internal to `buildCopTasks`, making modifications relatively safe.
```
newBo, cancelFn := bo.TiKVBackoffer().Fork()
ctxWithTimeout, cancel := context.WithTimeout(newBo.GetCtx(),time.Duration(req.MaxExecutionTime)*time.Millisecond)
newBo.SetCtx(ctxWithTimeout)A
defer cancel()
// Using `newBo` in the following build task processing.
```

Comment (windtalker) [reply pkg/store/copr/coprocessor.go]: I've updated the code to use contextWithTimeout to construct bo if `maxExecutionTime` is not 0, please take a look.
