### PR TITLE
planner: fix outer-join-to-anti-semi rewrite for nested outer joins | tidb-test=pr/2667

### LINKED ISSUE #65748: outer join to anti-semi join rewrite breaks nested LEFT JOIN with IS NULL filter
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
  CREATE TABLE t1 (i INT NOT NULL);
  INSERT INTO t1 VALUES (0), (2), (3), (4);
  CREATE TABLE t2 (i INT NOT NULL);
  INSERT INTO t2 VALUES (0), (1), (3), (4);
  CREATE TABLE t3 (i INT NOT NULL);
  INSERT INTO t3 VALUES (0), (1), (2), (4);

  SELECT * FROM t1
  LEFT JOIN (t2 LEFT JOIN t3 ON t3.i = t2.i)
    ON t2.i = t1.i
  WHERE t3.i IS NULL;

  ### What I expected

  +---+------+------+
  | i | i    | i    |
  +---+------+------+
  | 2 | NULL | NULL |
  | 3 |    3 | NULL |
  +---+------+------+

  ### What I got

  +---+------+------+
  | i | i    | i    |
  +---+------+------+
  | 2 | NULL | NULL |
  +---+------+------+
```

### 4. What is your TiDB version? (Required)

master
d14962d5e64cfce384c6e1e423835f1b4b871ca3

### PR DESCRIPTION
**Pull request by lilinghai**
### What problem does this PR solve?

Issue Number: close #65748

Problem Summary:

The optimizer rule uses NOT NULL flags from schema to decide whether `IS NULL` on an inner column implies no match. With nested outer joins, those columns can become nullable even if the base table says NOT NULL, which leads to wrong results.
  - Use FD not-null information (with fallback) instead of raw schema NOT NULL flags in `canConvertAntiJoin`.
  - Add regression test for the nested LEFT JOIN + IS NULL case
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/casetest/rule/rule_outer_to_semi_join_test.go [hunk 1]
```diff
@@ -58,3 +58,22 @@ func TestOuterToSemiJoin(tt *testing.T) {
 		}
 	})
 }
+
+func TestOuterToSemiJoinNestedOuterJoinNullability(tt *testing.T) {
```
Comment (hawkingrei) [inline pkg/planner/core/casetest/rule/rule_outer_to_semi_join_test.go]: Please put it into the TestOuterToSemiJoin.
