### PR TITLE
external: fix the dead loop in `readNBytes`

### LINKED ISSUE #61177: `readNBytes` may trap in a dead loop
## Bug Report

In method `byteReader.reload`, when [`io.ReadFull`](https://github.com/pingcap/tidb/blob/2dce92429d784d75c94146638c3ac1e437e859c8/pkg/lightning/backend/external/byte_reader.go#L316) returns `(0, io.ErrUnexpectedEOF)`, `readNBytes` would never return

### 1. Minimal reproduce step (Required)

run `IMPORT INTO` using global sort

### 2. What did you expect to see? (Required)

Finish the import task, or fail due to some network reasons

### 3. What did you see instead (Required)

Trap in `readNBytes`, infinitely executing `next` and `reload`

### 4. What is your TiDB version? (Required)

master (2dce92429d784d75c94146638c3ac1e437e859c8)

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #61177

Problem Summary:

See the issue description.

### What changed and how does it work?

Retry `io.ReadFull` if it returns `0, ErrUnexpectedEOF`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/backend/external/byte_reader.go [hunk 1]
```diff
@@ -312,27 +313,33 @@ func (r *byteReader) reload() error {
...
+		n, err := io.ReadFull(r.storageReader, r.curBuf[0])
+		if err != nil {
+			switch {
+			case goerrors.Is(err, io.EOF):
+				// move curBufIdx so following read will also find EOF
+				r.curBufIdx = len(r.curBuf)
+				return false, err
+			case goerrors.Is(err, io.ErrUnexpectedEOF):
+				if n == 0 {
+					return true, err
```
Comment (lance6716) [inline pkg/lightning/backend/external/byte_reader.go:328]: maybe print log for this unexpected case. For `(0, ErrUnexpectedEOF)` lasts for a long time and still fails after retry, we can see it in log.

**Review by lance6716 — APPROVED** [review]

File: pkg/lightning/backend/external/byte_reader.go [hunk 2]
```diff
@@ -312,27 +313,34 @@ func (r *byteReader) reload() error {
...
-		case goerrors.Is(err, io.ErrUnexpectedEOF):
-			// The last batch.
-			r.curBuf[0] = r.curBuf[0][:n]
-		case goerrors.Is(err, context.Canceled):
-			return err
-		default:
-			r.logger.Warn("other error during read", zap.Error(err))
-			return err
+
+	return util.RunWithRetry(util.DefaultMaxRetries, util.RetryInterval, func() (retryable bool, err error) {
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply pkg/lightning/backend/external/byte_reader.go:317]: better make this closure a method of `byteReader`, it's a high frequency call

File: tests/realtikvtest/importintotest4/global_sort_test.go [hunk 3]
```diff
@@ -218,3 +218,51 @@ func (s *mockGCSSuite) TestGlobalSortUniqueKeyConflict() {
...
+
+	// check all sorted data cleaned up
+	<-ch
+
+	_, files, err := s.server.ListObjectsWithOptions("sorted", fakestorage.ListOptions{Prefix: "import"})
+	s.NoError(err)
+	s.Len(files, 0)
+
+	// check subtask external field
+	checkExternalFields(s.T(), s.tk)
```
Comment (D3Hunter) [inline tests/realtikvtest/importintotest4/global_sort_test.go:267]: your case don't test this part, don't copy this part around

File: br/pkg/storage/gcs.go [hunk 4]
```diff
@@ -593,6 +595,12 @@ type gcsObjectReader struct {
 
 // Read implement the io.Reader interface.
 func (r *gcsObjectReader) Read(p []byte) (n int, err error) {
+	failpoint.Inject("GCSReadUnexpectedEOF", func(n failpoint.Value) {
+		if r.prefetchSize > 0 && r.pos > 0 && rand.Intn(2) == 0 {
```
Comment (D3Hunter) [inline br/pkg/storage/gcs.go:599]: we can remove this rand, and let this failpoint always `0, expectedEOF`, and use `3*return(0)` to enable the failpoint, to make the test always retry the reader read

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/lightning/backend/external/byte_reader.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (CbcWestwolf) [reply pkg/lightning/backend/external/byte_reader.go]: [`e1e4b9f` (#61309)](https://github.com/pingcap/tidb/pull/61309/commits/e1e4b9f72b0ed601bd2a73e2b46fa7b365859417)

**Comment by CbcWestwolf** [comment]
@D3Hunter All comments have been resolved, PTAL again, thanks!

**Review by D3Hunter — APPROVED** [review]
