### PR TITLE
server: openSession instead set nil when changeUser

### LINKED ISSUE #33892: server: set ctx for ComChangeUser maybe trigger panic at ShowProcessList
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. execute 'ComChangeUser' many times

### 2. What did you expect to see? (Required)
run success and response ok

### 3. What did you see instead (Required)
maybe trigger panic 
origin_img_v2_1caeb186-0ebb-439b-82a6-9b7c8555b77g

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by knull-cn**
### What problem does this PR solve?

Issue Number: close #33892

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: server/conn.go [hunk 1]
```diff
@@ -2341,7 +2341,11 @@ func (cc *clientConn) handleChangeUser(ctx context.Context, data []byte) error {
 	if err := cc.ctx.Close(); err != nil {
 		logutil.Logger(ctx).Debug("close old context failed", zap.Error(err))
 	}
-	cc.ctx = nil
+	// new openSession here, openSessionAndDoAuth will not run again because ctx was not nil.
+	err := cc.openSession()
```
Comment (wjhuang2016) [inline server/conn.go:2345]: Is it ok not to auth?

Comment (bb7133) [reply server/conn.go:2345]: I think so, as you can see `openSessionAndDoAuth` in line 2349.

Comment (bb7133) [reply server/conn.go:2345]: However, is it fine to only re-set the context here? like:

```
	cc.ctx, err = cc.server.driver.OpenCtx(cc.connectionID, cc.capability, cc.collation, cc.dbname, tlsStatePtr)
	if err != nil {
		return err
	}
```

https://github.com/pingcap/tidb/blob/334508e13d556aef1f1f6f766aacc9c70b44626c/server/conn.go/#L798-L801

Comment (bb7133) [reply server/conn.go:2345]: Also, I just checked the reference of `openSessionAndDoAuth()`, it might be fine if we just remove:

```
if cc.ctx == nil {
```
In `openSessionAndDoAuth`? https://github.com/pingcap/tidb/blob/334508e13d556aef1f1f6f766aacc9c70b44626c/server/conn.go/#L812

@dveeden WDYT?

Comment (knull-cn) [reply server/conn.go:2345]: sometimes reuse the `ctx` , maybe can not remove 
in function `clientConn::readOptionalSSLRequestAndHandshakeResponse`, will  call function `handleAuthPlugin` new ctx; and then call  `clientConn::openSessionAndDoAuth` will not new ctx (reuse the ctx created before)
reuse code see here : https://github.com/pingcap/tidb/blob/master/server/conn.go#L692-L709

**Review by bb7133 — APPROVED** [review]
LGTM

File: server/conn.go [hunk 2]
```diff
@@ -2341,7 +2341,11 @@ func (cc *clientConn) handleChangeUser(ctx context.Context, data []byte) error {
 	if err := cc.ctx.Close(); err != nil {
 		logutil.Logger(ctx).Debug("close old context failed", zap.Error(err))
 	}
-	cc.ctx = nil
+	// new openSession here, openSessionAndDoAuth will not run again because ctx was not nil.
```
Comment (wjhuang2016) [inline server/conn.go:2344]:
```suggestion
	// openSession explicitly to renew session, it won't run again in openSessionAndDoAuth because ctx is not nil.
```

**Review by wjhuang2016 — APPROVED** [review]
