### PR TITLE
server: fix COM_FIELD_LIST response bug that make mariadb-client crash during `use db`

### LINKED ISSUE #6622: when loading data， execute “use database” crashed
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1, loader loading data with sharding aggregation.
2, execute "use [database_name]"
3, mysql client crashed
MySQL [(none)]> use vccsdb
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

*** Error in `mysql': double free or corruption (!prev): 0x00005619903b5d10 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c503)[0x7f05d9053503]
mysql(free_root+0x40)[0x56198ec88010]
mysql(free_rows+0x1c)[0x56198ec61acc]
mysql(unpack_fields+0x2eb)[0x56198ec62eab]
mysql(mysql_list_fields+0xa4)[0x56198ec5caa4]
mysql(+0x43435)[0x56198ec50435]
mysql(+0x447ee)[0x56198ec517ee]
mysql(+0x4929b)[0x56198ec5629b]
mysql(main+0x5f1)[0x56198ec4b681]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f05d8ff8b35]
mysql(+0x3ec99)[0x56198ec4bc99]
======= Memory map: ========
56198ec0d000-56198ef3e000 r-xp 00000000 08:03 1179538                    /usr/bin/mysql
56198f13e000-56198f147000 r--p 00331000 08:03 1179538                    /usr/bin/mysql
56198f147000-56198f16a000 rw-p 0033a000 08:03 1179538                    /usr/bin/mysql
56198f16a000-56198f172000 rw-p 00000000 00:00 0 
5619902ea000-56199085e000 rw-p 00000000 00:00 0                          [heap]
7f05c9ad7000-7f05d0000000 r--p 00000000 08:03 2285                       /usr/lib/locale/locale-archive
7f05d0000000-7f05d0021000 rw-p 00000000 00:00 0 
7f05d0021000-7f05d4000000 ---p 00000000 00:00 0 
7f05d6a12000-7f05d6d8c000 rw-p 00000000 00:00 0 
7f05d6d8c000-7f05d6d98000 r-xp 00000000 08:03 33556516                   /usr/lib64/libnss_files-2.17.so
7f05d6d98000-7f05d6f97000 ---p 0000c000 08:03 33556516                   /usr/lib64/libnss_files-2.17.so
7f05d6f97000-7f05d6f98000 r--p 0000b000 08:03 33556516                   /usr/lib64/libnss_files-2.17.so
7f05d6f98000-7f05d6f99000 rw-p 0000c000 08:03 33556516                   /usr/lib64/libnss_files-2.17.so
7f05d6f99000-7f05d6f9f000 rw-p 00000000 00:00 0 
7f05d6f9f000-7f05d6fa0000 ---p 00000000 00:00 0 
7f05d6fa0000-7f05d79a0000 rw-p 00000000 00:00 0 
7f05d79a0000-7f05d7a00000 r-xp 00000000 08:03 33556858                   /usr/lib64/libpcre.so.1.2.0
7f05d7a00000-7f05d7c00000 ---p 00060000 08:03 33556858                   /usr/lib64/libpcre.so.1.2.0
7f05d7c00000-7f05d7c01000 r--p 00060000 08:03 33556858                   /usr/lib64/libpcre.so.1.2.0
7f05d7c01000-7f05d7c02000 rw-p 00061000 08:03 33556858                   /usr/lib64/libpcre.so.1.2.0
7f05d7c02000-7f05d7c26000 r-xp 00000000 08:03 34317229                   /usr/lib64/libselinux.so.1
7f05d7c26000-7f05d7e25000 ---p 00024000 08:03 34317229                   /usr/lib64/libselinux.so.1
7f05d7e25000-7f05d7e26000 r--p 00023000 08:03 34317229                   /usr/lib64/libselinux.so.1
7f05d7e26000-7f05d7e27000 rw-p 00024000 08:03 34317229                   /usr/lib64/libselinux.so.1
7f05d7e27000-7f05d7e29000 rw-p 00000000 00:00 0 
7f05d7e29000-7f05d7e3f000 r-xp 00000000 08:03 33556526                   /usr/lib64/libresolv-2.17.so
7f05d7e3f000-7f05d803f000 ---p 00016000 08:03 33556526                   /usr/lib64/libresolv-2.17.so
7f05d803f000-7f05d8040000 r--p 00016000 08:03 33556526                   /usr/lib64/libresolv-2.17.so
7f05d8040000-7f05d8041000 rw-p 00017000 08:03 33556526                   /usr/lib64/libresolv-2.17.so
7f05d8041000-7f05d8043000 rw-p 00000000 00:00 0 
7f05d8043000-7f05d8046000 r-xp 00000000 08:03 33558238                   /usr/lib64/libkeyutils.so.1.5
7f05d8046000-7f05d8245000 ---p 00003000 08:03 33558238                   /usr/lib64/libkeyutils.so.1.5
7f05d8245000-7f05d8246000 r--p 00002000 08:03 33558238                   /usr/lib64/libkeyutils.so.1.5
7f05d8246000-7f05d8247000 rw-p 00003000 08:03 33558238                   /usr/lib64/libkeyutils.so.1.5
7f05d8247000-7f05d8254000 r-xp 00000000 08:03 33592005                   /usr/lib64/libkrb5support.so.0.1
7f05d8254000-7f05d8453000 ---p 0000d000 08:03 33592005                   /usr/lib64/libkrb5support.so.0.1
7f05d8453000-7f05d8454000 r--p 0000c000 08:03 33592005                   /usr/lib64/libkrb5support.so.0.1
7f05d8454000-7f05d8455000 rw-p 0000d000 08:03 33592005                   /usr/lib64/libkrb5support.so.0.1
7f05d8455000-7f05d846a000 r-xp 00000000 08:03 33554508                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05d846a000-7f05d8669000 ---p 00015000 08:03 33554508                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05d8669000-7f05d866a000 r--p 00014000 08:03 33554508                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05d866a000-7f05d866b000 rw-p 00015000 08:03 33554508                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05d866b000-7f05d869c000 r-xp 00000000 08:03 33591995                   /usr/lib64/libk5crypto.so.3.1
7f05d869c000-7f05d889b000 ---p 00031000 08:03 33591995                   /usr/lib64/libk5crypto.so.3.1
7f05d889b000-7f05d889d000 r--p 00030000 08:03 33591995                   /usr/lib64/libk5crypto.so.3.1
7f05d889d000-7f05d889e000 rw-p 00032000 08:03 33591995                   /usr/lib64/libk5crypto.so.3.1
7f05d889e000-7f05d88a1000 r-xp 00000000 08:03 33556883                   /usr/lib64/libcom_err.so.2.1
7f05d88a1000-7f05d8aa0000 ---p 00003000 08:03 33556883                   /usr/lib64/libcom_err.so.2.1
7f05d8aa0000-7f05d8aa1000 r--p 00002000 08:03 33556883                   /usr/lib64/libcom_err.so.2.1
7f05d8aa1000-7f05d8aa2000 rw-p 00003000 08:03 33556883                   /usr/lib64/libcom_err.so.2.1
7f05d8aa2000-7f05d8b7a000 r-xp 00000000 08:03 33592002                   /usr/lib64/libkrb5.so.3.3
7f05d8b7a000-7f05d8d79000 ---p 000d8000 08:03 33592002                   /usr/lib64/libkrb5.so.3.3
7f05d8d79000-7f05d8d87000 r--p 000d7000 08:03 33592002                   /usr/lib64/libkrb5.so.3.3
7f05d8d87000-7f05d8d8a000 rw-p 000e5000 08:03 33592002                   /usr/lib64/libkrb5.so.3.3
7f05d8d8a000-7f05d8dd4000 r-xp 00000000 08:03 34317239                   /usr/lib64/libgssapi_krb5.so.2.2
7f05d8dd4000-7f05d8fd4000 ---p 0004a000 08:03 34317239                   /usr/lib64/libgssapi_krb5.so.2.2
7f05d8fd4000-7f05d8fd5000 r--p 0004a000 08:03 34317239                   /usr/lib64/libgssapi_krb5.so.2.2
7f05d8fd5000-7f05d8fd7000 rw-p 0004b000 08:03 34317239                   /usr/lib64/libgssapi_krb5.so.2.2
7f05d8fd7000-7f05d918d000 r-xp 00000000 08:03 33556498                   /usr/lib64/libc-2.17.so
7f05d918d000-7f05d938d000 ---p 001b6000 08:03 33556498                   /usr/lib64/libc-2.17.so
7f05d938d000-7f05d9391000 r--p 001b6000 08:03 33556498                   /usr/lib64/libc-2.17.so
7f05d9391000-7f05d9393000 rw-p 001ba000 08:03 33556498                   /usr/lib64/libc-2.17.so
7f05d9393000-7f05d9398000 rw-p 00000000 00:00 0 
7f05d9398000-7f05d9498000 r-xp 00000000 08:03 33556506                   /usr/lib64/libm-2.17.so
7f05d9498000-7f05d9698000 ---p 00100000 08:03 33556506                   /usr/lib64/libm-2.17.so
7f05d9698000-7f05d9699000 r--p 00100000 08:03 33556506                   /usr/lib64/libm-2.17.so
7f05d9699000-7f05d969a000 rw-p 00101000 08:03 33556506                   /usr/lib64/libm-2.17.so
7f05d969a000-7f05d9783000 r-xp 00000000 08:03 33556828                   /usr/lib64/libstdc++.so.6.0.19
7f05d9783000-7f05d9983000 ---p 000e9000 08:03 33556828                   /usr/lib64/libstdc++.so.6.0.19
7f05d9983000-7f05d998c000 r--p 000e9000 08:03 33556828                   /usr/lib64/libstdc++.so.6.0.19
7f05d998c000-7f05d998e000 rw-p 000f2000 08:03 33556828                   /usr/lib64/libstdc++.so.6.0.19
7f05d998e000-7f05d99a3000 rw-p 00000000 00:00 0 
7f05d99a3000-7f05d99c8000 r-xp 00000000 08:03 33556854                   /usr/lib64/libtinfo.so.5.9
7f05d99c8000-7f05d9bc8000 ---p 00025000 08:03 33556854                   /usr/lib64/libtinfo.so.5.9
7f05d9bc8000-7f05d9bcc000 r--p 00025000 08:03 33556854                   /usr/lib64/libtinfo.so.5.9
7f05d9bcc000-7f05d9bcd000 rw-p 00029000 08:03 33556854                   /usr/lib64/libtinfo.so.5.9
7f05d9bcd000-7f05d9bf3000 r-xp 00000000 08:03 33556844                   /usr/lib64/libncurses.so.5.9
7f05d9bf3000-7f05d9df2000 ---p 00026000 08:03 33556844                   /usr/lib64/libncurses.so.5.9
7f05d9df2000-7f05d9df3000 r--p 00025000 08:03 33556844                   /usr/lib64/libncurses.so.5.9
7f05d9df3000-7f05d9df4000 rw-p 00026000 08:03 33556844                   /usr/lib64/libncurses.so.5.9
7f05d9df4000-7f05d9df6000 r-xp 00000000 08:03 33556504                   /usr/lib64/libdl-2.17.so
7f05d9df6000-7f05d9ff6000 ---p 00002000 08:03 33556504                   /usr/lib64/libdl-2.17.so
7f05d9ff6000-7f05d9ff7000 r--p 00002000 08:03 33556504                   /usr/lib64/libdl-2.17.so
7f05d9ff7000-7f05d9ff8000 rw-p 00003000 08:03 33556504                   /usr/lib64/libdl-2.17.so
7f05d9ff8000-7f05da22c000 r-xp 00000000 08:03 33556869                   /usr/lib64/libcrypto.so.1.0.2k
7f05da22c000-7f05da42c000 ---p 00234000 08:03 33556869                   /usr/lib64/libcrypto.so.1.0.2k
7f05da42c000-7f05da448000 r--p 00234000 08:03 33556869                   /usr/lib64/libcrypto.so.1.0.2k
7f05da448000-7f05da455000 rw-p 00250000 08:03 33556869                   /usr/lib64/libcrypto.so.1.0.2k
7f05da455000-7f05da459000 rw-p 00000000 00:00 0 
7f05da459000-7f05da4c0000 r-xp 00000000 08:03 34317236                   /usr/lib64/libssl.so.1.0.2k
7f05da4c0000-7f05da6c0000 ---p 00067000 08:03 34317236                   /usr/lib64/libssl.so.1.0.2k
7f05da6c0000-7f05da6c4000 r--p 00067000 08:03 34317236                   /usr/lib64/libssl.so.1.0.2k
7f05da6c4000-7f05da6cb000 rw-p 0006b000 08:03 34317236                   /usr/lib64/libssl.so.1.0.2k
7f05da6cb000-7f05da6e0000 r-xp 00000000 08:03 33556871                   /usr/lib64/libz.so.1.2.7
7f05da6e0000-7f05da8df000 ---p 00015000 08:03 33556871                   /usr/lib64/libz.so.1.2.7
7f05da8df000-7f05da8e0000 r--p 00014000 08:03 33556871                   /usr/lib64/libz.so.1.2.7
7f05da8e0000-7f05da8e1000 rw-p 00015000 08:03 33556871                   /usr/lib64/libz.so.1.2.7
7f05da8e1000-7f05da8f8000 r-xp 00000000 08:03 33556524                   /usr/lib64/libpthread-2.17.so
7f05da8f8000-7f05daaf7000 ---p 00017000 08:03 33556524                   /usr/lib64/libpthread-2.17.so
7f05daaf7000-7f05daaf8000 r--p 00016000 08:03 33556524                   /usr/lib64/libpthread-2.17.so
7f05daaf8000-7f05daaf9000 rw-p 00017000 08:03 33556524                   /usr/lib64/libpthread-2.17.so
7f05daaf9000-7f05daafd000 rw-p 00000000 00:00 0 
7f05daafd000-7f05dab1d000 r-xp 00000000 08:03 33556491                   /usr/lib64/ld-2.17.so
7f05dab2a000-7f05dad0e000 rw-p 00000000 00:00 0 
7f05dad12000-7f05dad13000 rw-p 00000000 00:00 0 
7f05dad13000-7f05dad1a000 r--s 00000000 08:03 33556827                   /usr/lib64/gconv/gconv-modules.cache
7f05dad1a000-7f05dad1c000 rw-p 00000000 00:00 0 
7f05dad1c000-7f05dad1d000 r--p 0001f000 08:03 33556491                   /usr/lib64/ld-2.17.so
7f05dad1d000-7f05dad1e000 rw-p 00020000 08:03 33556491                   /usr/lib64/ld-2.17.so
7f05dad1e000-7f05dad1f000 rw-p 00000000 00:00 0 
7fffb9f79000-7fffb9f9a000 rw-p 00000000 00:00 0                          [stack]
7fffb9fe4000-7fffb9fe6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

2. What did you expect to see?
no core dumped.

3. What did you see instead?
Aborted (core dumped)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
MySQL [(none)]> select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.10-TiDB-v2.0.1 |
+--------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by lysu**
## What have you changed? (mandatory)

[column-definitions](https://dev.mysql.com/doc/internals/en/com-query-response.html#column-definition) in COM_FIELD_LIST response need write addition default-values part even though we omit default-values.

and some client like MariaDB-cli(without `-A`)'s `use db` will trigger COM_FEILD_LIST and read default-values length bit in response, it will meet fault if we haven't give it.
https://github.com/MariaDB/server/blob/72b6d01848e56a75349d663bc61bbe71f97a280b/sql-common/client.c#L1519

- `dump()` add option parameter and pass `WithDefaultValues` option  in `handle_field_list()`
- check option and add default values length bit in dump
- remove unuse `DefaultValue` `DefaultValueLength` field from `server.ColumnInfo`

fix #6622 

## What are the type of the changes (mandatory)?

The currently defined types are listed below, please pick one of the types for this PR by removing the others:

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested (mandatory)?

- manual tests

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/6918)

### CODE REVIEW

**Comment by shenli** [comment]
Well done!

File: server/column.go [hunk 1]
```diff
@@ -15,22 +15,30 @@ package server
...
+const (
+	// Normal option indicts that dump with normal steps.
+	Normal DumpOpt = 1 << iota
+	// WithDefaultValue option indicts that dump with an addition defaultValues step.
+	WithDefaultValue
+)
+
 // Dump dumps ColumnInfo to bytes.
-func (column *ColumnInfo) Dump(buffer []byte) []byte {
+func (column *ColumnInfo) Dump(buffer []byte, flags DumpOpt) []byte {
```
Comment (shenli) [inline server/column.go]: Can we use a bool argument to control whether output default value?

File: server/column.go [hunk 2]
```diff
@@ -47,9 +55,10 @@ func (column *ColumnInfo) Dump(buffer []byte) []byte {
 	buffer = append(buffer, column.Decimal)
 	buffer = append(buffer, 0, 0)
 
-	if column.DefaultValue != nil {
-		buffer = dumpUint64(buffer, uint64(len(column.DefaultValue)))
-		buffer = append(buffer, column.DefaultValue...)
+	if flags&WithDefaultValue > 0 {
+		// Current we doesn't output defaultValue but reserve defaultValue length bit to make mariadb client happy.
+		// https://dev.mysql.com/doc/internals/en/com-query-response.html#column-definition
+		buffer = dumpUint64(buffer, 0)
```
Comment (zz-jason) [inline server/column.go]: why this change works?

Comment (lysu) [reply server/column.go]: because in protocol definition https://dev.mysql.com/doc/internals/en/com-query-response.html#column-definition said.

```
  if command was COM_FIELD_LIST {
lenenc_int     length of default-values
string[$len]   default values
  }
```
So, if it's a response of COM_FIELD_LIST, we should actually add default values part use just like this.

```
+----------------------+-------------------+------------+--------------+--------------+-----------+--------------------+
|                      |                   |            |              |              |           |                    |
|                      |                   |            |              |              |           |                    |
|                      |                   |            |              |              |           |                    |
|                      |                   |            |              |              |           |                    |
|      ....sth we      |  length byte of   |   default  |   default    |   default    |  default  |   ..............   |
|      outputed        |  default values   |   value 1  |   value 2    |   value 3    |  value 4  |                    |
|                      |                   |            |              |              |           |                    |
|                      |                   |            |              |              |           |                    |
|                      |                   |            |              |              |           |                    |
+----------------------+-------------------+------------+--------------+--------------+-----------+--------------------+

```
but In tidb we omit default values(It seems not easy to output that....),  and omit all default values bytes...but mariadb will read `length byte of default values` without condition, after send `COM_FIELD_LIST`. see: https://github.com/MariaDB/server/blob/72b6d01848e56a75349d663bc61bbe71f97a280b/sql-common/client.c#L1519

So at this PR, we don't complete fill all default values but follow the protocol give client an `empty default values`

```
+-------------+--------------+
|             |              |
|             |              |
|             |              |
|  sth we     | length byte  |
|  outputed   | of default   |
|             | values       |
|             |              |
|             |    (0)       |
|             |              |
+-------------+--------------+

```
so mariadb will read length byte without out of index crash.

File: server/column.go (hunk 1 above)
Comment (lysu) [reply server/column.go]: done~

**Comment by zz-jason** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @shenli, @tiancaiamao, and @coocood)

---



*Comments from [Reviewable](https://reviewable.io/reviews/pingcap/tidb/6918#-:-LG-_Uw_4QH7QXFcTKgj:bnfp4nl)*

**Comment by tiancaiamao** [comment]
Review status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @shenli, @lysu, @tiancaiamao, and @coocood)

---

*[server/column.go, line 50 at r3](https://reviewable.io/reviews/pingcap/tidb/6918#-LG-ZmO_-AiloB1kNnTe:-LG-ZDuu4F5t-2lrWSMI:b-cln1le) ([raw file](https://github.com/pingcap/tidb/blob/1ab7abbebb95d17fd5133cb387b7624ea9270bc3/server/column.go#L50)):*
>  How about change it like this:

```
if len(column.DefaultValue) == 0 {
    ...
} else {
    buffer = dumpUint64(buffer, 0)
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/pingcap/tidb/6918)*

**Comment by tiancaiamao** [comment]
Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @shenli, @lysu, and @coocood)

---



*Comments from [Reviewable](https://reviewable.io/reviews/pingcap/tidb/6918)*

**Comment by shenli** [comment]
LGTM

**Comment by zz-jason** [comment]
@tiancaiamao PTAL

**Comment by lysu** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
LGTM @shenli

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@lysu Could you add some integration test for this?

**Comment by lysu** [comment]
PTAL @coocood
