### PR TITLE
plugin: fix bug that watch loop will refresh frequently when channel closed

### LINKED ISSUE #49273: flushWatcher loop may call refreshPluginState frequently when watch chan closed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/90e272abc31d22024c36ab095544bf20ba7f3575/pkg/plugin/plugin.go#L279-L289

This above code does not handle case `watchChan` closed, so `refreshPluginState` will be called frequently when this happens.

### 2. What did you expect to see? (Required)

When `watchChan` closed , we should close watch chan

### 3. What did you see instead (Required)

closed chan is not handled correctly

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #49273

### What changed and how does it work?

Recreate watch channel when it is closed

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix bug that watch loop will refresh frequently when channel closed sometimes
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by CbcWestwolf — APPROVED** [review]

File: pkg/plugin/plugin.go [hunk 1]
```diff
@@ -275,14 +276,32 @@ func (w *flushWatcher) refreshPluginState() error {
 	}
 	return nil
 }
-
 func (w *flushWatcher) watchLoop() {
-	watchChan := w.etcd.Watch(w.ctx, w.path)
+	const reWatchInterval = time.Second * 5
```
Comment (LykxSassinator) [inline pkg/plugin/plugin.go:280]: FYI, it seems that this interval hasn't been used. Is it expected? Should it be implemented as a timer ?

Comment (lcwangchao) [reply pkg/plugin/plugin.go:280]: The lost sleep has been added in PR: https://github.com/pingcap/tidb/pull/49292 . Thanks a lot
