### PR TITLE
session: fix wrong etcd mutex key

### LINKED ISSUE #56375: upgrade tidb may block
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
In master branch

### 2. What did you expect to see? (Required)
N/A
### 3. What did you see instead (Required)
N/A
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #56375

Problem Summary:
Used the wrong mutex key. 
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
Start a v8.3.0 tidb cluster and upgrade.
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/session/bootstrap.go [hunk 1]
```diff
@@ -1447,6 +1447,7 @@ func forceToLeader(ctx context.Context, s sessiontypes.Session) error {
 	for !dom.DDL().OwnerManager().IsOwner() {
 		ownerID, err := dom.DDL().OwnerManager().GetOwnerID(ctx)
 		if err != nil && (errors.ErrorEqual(err, concurrency.ErrElectionNoLeader) || strings.Contains(err.Error(), "no owner")) {
+			logutil.BgLogger().Info("no leader", zap.Error(err))
```
Comment (tangenta) [inline pkg/session/bootstrap.go:1450]:
```suggestion
			logutil.BgLogger().Info("ddl owner not found", zap.Error(err))
```

**Review by lance6716 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM
