### PR TITLE
util: Resolve RuntimeStatsColl potential unlock mutex

### LINKED ISSUE #55042: query stuck when trying to kill it because of OOM
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. hack tidb code, delete following code, so we can set `tidb_mem_quota_query` a very small value to help reproduce this bug   https://github.com/pingcap/tidb/blob/199bf90c2a6e914d05733bc6dacd9ed2dea77b7f/pkg/sessionctx/variable/sysvar.go#L1127-L1130 
2. build tidb and start tiup playround
3. download [10-tidb-slow.log](https://github.com/user-attachments/files/16422699/10-tidb-slow.log) and `set @@tidb_slow_query_file = '/home/guojiangtao/10-tidb-slow.log';` (remember to change the slow query file path)
4. `set @@tidb_mem_quota_query = 10;`
5. run `select time,host host_ip,Query_time as exec_max_time,parse_time,compile_time,Query as sql_text,Digest as sql_id,is_internal,succ, Plan as plan_text,mem_max as mem_max,User as parse_user,DB as database_name,total_keys,request_count,process_time,process_keys from information_schema.SLOW_QUERY order by time desc;`
### 2. What did you expect to see? (Required)
query is canceled
### 3. What did you see instead (Required)
query is stucked
### 4. What is your TiDB version? (Required)
master 560e92ed721f9c64d22e2c5e4ff35518310cf48e

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #55042

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > Just a mutex lock changes, using defer to protect it.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that queries may get stuck when they are being killed due to exceeding tidb_mem_quota_query.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/util/execdetails/execdetails.go [hunk 1]
```diff
@@ -1301,6 +1301,7 @@ func NewRuntimeStatsColl(reuse *RuntimeStatsColl) *RuntimeStatsColl {
 // RegisterStats register execStat for a executor.
 func (e *RuntimeStatsColl) RegisterStats(planID int, info RuntimeStats) {
```
Comment (hawkingrei) [inline pkg/util/execdetails/execdetails.go:1302]: replace ```sync.Metux``` with ```syncutil.Mutex``` which can find the potential mutex in the CI.

**Review by wshwsh12 — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]
