### PR TITLE
planner: right deal with predicate in the join reorder

### LINKED ISSUE #61715: Failed to build executor
### 1. Minimal reproduce step (Required)

```sql
create table t0(vkey integer, c3 varchar(0));
create table t1(vkey integer, c10 integer);
create table t2(c12 integer, c13 integer, c14 varchar(0), c15 double);
create table t3(vkey varchar(0), c20 integer);
select 0 from t2 join(t3 join t0 a on 0) left join(t1 b left join t1 c on 0) on(c20 = b.vkey) on(c13 = a.vkey) join(select c14 d from(t2 join t3 on c12 = vkey)) e on(c3 = d) where nullif(c15, case when(c.c10) then 0 end); -- ERROR 8118 (HY000) at line 1: Failed to build executor
```

### 2. What did you expect to see? (Required)
No error

### 4. What is your TiDB version? (Required)

`tiup playground nightly --host 0.0.0.0 --kv 3 --tiflash 3`
```bash
8.0.11-TiDB-v9.0.0-beta.1.pre-554-gb1a5536a64-dirty
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #61715 

Problem Summary:

### What changed and how does it work?

In this case, during join reorder, an inner join that contains both equal conditions and left conditions is constructed, which ultimately leads to the problem. Therefore, the solution is to place the left condition into the left child and add a new select.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/rule_join_reorder.go [hunk 1]
```diff
@@ -655,13 +655,25 @@ func (s *baseSingleGroupJoinOrderSolver) newCartesianJoin(lChild, rChild base.Lo
...
 func (s *baseSingleGroupJoinOrderSolver) newJoinWithEdges(lChild, rChild base.LogicalPlan,
-	eqEdges []*expression.ScalarFunction, otherConds, leftConds, rightConds []expression.Expression, joinType logicalop.JoinType) base.LogicalPlan {
+	eqEdges []*expression.ScalarFunction, otherConds, leftConds, rightConds []expression.Expression, joinType logicalop.JoinType, opt *optimizetrace.LogicalOptimizeOp) base.LogicalPlan {
 	newJoin := s.newCartesianJoin(lChild, rChild)
 	newJoin.EqualConditions = eqEdges
 	newJoin.OtherConditions = otherConds
 	newJoin.LeftConditions = leftConds
 	newJoin.RightConditions = rightConds
 	newJoin.JoinType = joinType
+	if newJoin.EqualConditions != nil && newJoin.JoinType == logicalop.InnerJoin {
```
Comment (winoros) [inline pkg/planner/core/rule_join_reorder.go]: Do we need to check whether the `EqualCondition` is nil or not?

Comment (hawkingrei) [reply pkg/planner/core/rule_join_reorder.go]: Updated. Removed this check, and I think it is impossible that an inner join is without equal conditions.

File: pkg/planner/core/rule_join_reorder_dp.go [hunk 2]
```diff
@@ -22,12 +22,13 @@ import (
...
 	"github.com/pingcap/tidb/pkg/planner/core/base"
 	"github.com/pingcap/tidb/pkg/planner/core/operator/logicalop"
+	"github.com/pingcap/tidb/pkg/planner/util/optimizetrace"
 	"github.com/pingcap/tidb/pkg/util/dbterror/plannererrors"
 )
 
 type joinReorderDPSolver struct {
 	*baseSingleGroupJoinOrderSolver
-	newJoin func(lChild, rChild base.LogicalPlan, eqConds []*expression.ScalarFunction, otherConds, leftConds, rightConds []expression.Expression, joinType logicalop.JoinType) base.LogicalPlan
+	newJoin func(lChild, rChild base.LogicalPlan, eqConds []*expression.ScalarFunction, otherConds, leftConds, rightConds []expression.Expression, joinType logicalop.JoinType, opt *optimizetrace.LogicalOptimizeOp) base.LogicalPlan
```
Comment (AilinKid) [inline pkg/planner/core/rule_join_reorder_dp.go:31]: any test coverage about the tracer

Comment (hawkingrei) [reply pkg/planner/core/rule_join_reorder_dp.go:31]: This tracer is really a bit out of repair. We may need to set up a special topic to strengthen this area.

**Review by AilinKid — APPROVED** [review]
