### PR TITLE
server: Support flag 128 in execution of prepared statements

### LINKED ISSUE #36731: unsupported flag 128 with Connector/Python and prepared statements
### 1. Minimal reproduce step (Required)

```python3
#!/bin/python3
import argparse
import mysql.connector

parser = argparse.ArgumentParser()
parser.add_argument('--host', type=str, default='127.0.0.1')
parser.add_argument('--port', type=int, default=4000)
parser.add_argument('--user', type=str, default='root')
parser.add_argument('--password', type=str, default='')
args = parser.parse_args()
c = mysql.connector.connect(host=args.host, port=args.port, user=args.user, password=args.password)
cur = c.cursor(prepared=True)
cur.execute('DO ?', (1, ))
cur.close()
c.close()
print('OK')
```

### 2. What did you expect to see? (Required)

With MySQL 8.0.30:
```
$ ./prepared.py --port 8030 --user test --password test
OK
```

### 3. What did you see instead (Required)

With TiDB:
```
$ ./prepared.py
Traceback (most recent call last):
  File "/tmp/./prepared.py", line 13, in <module>
    cur.execute('DO ?', (1, ))
  File "/usr/lib/python3.11/site-packages/mysql/connector/cursor.py", line 1213, in execute
    res = self._connection.cmd_stmt_execute(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mysql/connector/connection.py", line 1100, in cmd_stmt_execute
    result = self._handle_binary_result(packet)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mysql/connector/connection.py", line 1025, in _handle_binary_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1105 (HY000): ERROR 1105 (HY000): unsupported flag 128
```

And in the logs:
```
[2022/07/29 16:03:44.416 +02:00] [INFO] [conn.go:1170] ["command dispatched failed"] [conn=2199023255961] [connInfo="id:2199023255961, addr:127.0.0.1:34430 status:0, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:0, autocommit:0"] [sql="DO ?"] [txn_mode=PESSIMISTIC] [timestamp=0] [err="ERROR 1105 (HY000): unsupported flag 128"]
```

### 4. What is your TiDB version? (Required)

```
sql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.2.0-alpha-560-ge5c900c8c
Edition: Community
Git Commit Hash: e5c900c8cd4cea6da2af02768c28cad10a8b1d13
Git Branch: master
UTC Build Time: 2022-07-29 13:51:19
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
1 row in set (0.0001 sec)
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #36731 

Problem Summary: Fix handling of the type of the flag

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix handling of prepared statement flags in the classic MySQL protocol
```

### CODE REVIEW

File: server/conn_stmt.go [hunk 1]
```diff
@@ -149,6 +150,10 @@ func (cc *clientConn) handleStmtExecute(ctx context.Context, data []byte) (err e
 		useCursor = false
 	case 1:
 		useCursor = true
+	case 128: // highest bit set (0x80) so unsigned, no flags (0)
+		useCursor = false
+	case 129: // highest bit set (0x80) so unsigned, flag CURSOR_TYPE_READ_ONLY set.
+		useCursor = true
```
Comment (xhebox) [inline server/conn_stmt.go:156]: I don't  think it is the correct fix. Since `signed/unsigned` flag is for `enum_field_types`, here the flag is `enum_cursor_type`. We should mimic mysql:

```
if flag & CURSOR_TYPE_READ_ONLY {
  useCursor = true
}
```

Comment (dveeden) [reply server/conn_stmt.go:147]: I've tried to address this in 179052cf70b038aaf6e4e067d846680bf6ea9247
PTAL @xhebox

Comment (xhebox) [reply server/conn_stmt.go:147]: Not a correct definition. Say `0x01`, will `flag&mysql.CursorTypeNoCursor > 0`.

Should be something like:

```
const (
	CursorTypeReadOnly uint8 = 1 << iota
	CursorTypeForUpdate
	CursorTypeScrollable
)
```

Comment (dveeden) [reply server/conn_stmt.go:144]: Fixed this in 3b89e33da7fb8975b56c172d67ddfe24ca7989bc
PTAL @xhebox

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
Another thing is that I think it deserve a document change. Since  `CursorTypeForUpdate` and the other will report error @dveeden .

**Comment by dveeden** [comment]
> Another thing is that I think it deserve a document change. Since `CursorTypeForUpdate` and the other will report error @dveeden .

I think the old code would raise a similar error for `CursorTypeForUpdate` and `CursorTypeScrollable` as it checks if `flag` is either 0 or 1. It also looks like MySQL doesn't support anything else than `CURSOR_TYPE_NO_CURSOR`/`CURSOR_TYPE_READ_ONLY` when looking at the code.

Any suggestions for what documentation you think should be updated?

**Comment by bb7133** [comment]
I just curious if the bug(#36731) might be reproduced using JDBC connector? It looks like that `PreparedStatement` cannot be used with a customed cursor(https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html):

For prepared statement, the interface is:
```
conn.prepareStatement(SQL_PATTERN)
```
However, the cursor is specified by:
```
conn.createStatement(java.sql.ResultSet.TYPE_FORWARD_ONLY, java.sql.ResultSet.CONCUR_READ_ONLY);
```

Which confused me.

**Comment by dveeden** [comment]
This results in flag value of 0x80:
```python3
cur.execute('DO ?', (1, ))
```

This results in a flag value of 0x0:
```python3
cur.execute('DO ?', ("1", ))
```

And with this Java code:
```java
package com.pingcap.javademo3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

public class App
{
    public static void main( String[] args )
    {
        try {
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        } catch (Exception ex) {
                System.out.println("Failed to load driver: " + ex.getMessage());
        }

        try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:4000?user=root&useServerPrepStmts=true&emulateUnsupportedPstmts=false");
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT @@hostname, @@port");
                rs.next();
                System.out.println("Connected to: " + rs.getString("@@hostname") + ":" + rs.getString("@@port"));

                conn.setAutoCommit(false);

                PreparedStatement p = conn.prepareStatement("DO ?");
                p.setInt(1, 1);
                p.executeUpdate();

                PreparedStatement p2 = conn.prepareStatement("SELECT ?");
                p2.setInt(1, 1);
                p2.executeQuery();
                p2.setInt(1, 2);
                p2.executeQuery();

                PreparedStatement p3 = conn.prepareStatement("SELECT ?");
                p3.setString(1, "1");
                p3.executeQuery();
        } catch (SQLException ex) {
                System.out.println("SQLException: " + ex.getMessage());
        }

    }
}
```

this shows this difference:

Python:
flag: 0x80
field type: 0x01 (FIELD_TYPE_TINY)
field unsigned: 0x80
field value: 1

Java:
flag: 0x00
field type: 0x03 (FIELD_TYPE_LONG)
field unsigned: 0x00
field value: 1

**Comment by dveeden** [comment]
And when using the original python code with both `-1` and `1`:

`-1` gives:
flag: 0x00
field type: 0x01 (FIELD_TYPE_TINY)
field usnigned: 0x00
field value: -1

`1` gives:
flag: 0x80
field type: 0x01 (FIELD_TYPE_TINY)
field usnigned: 0x80
field value: 1

TiDB works fine with `-1` as the flag is 0x00

**Comment by dveeden** [comment]
```c
#include <mysql.h>
#include <stdio.h>

int main(int argc, char **argv) {
  MYSQL *con = mysql_init(NULL);
  if (mysql_real_connect(con, "127.0.0.1", "root", NULL, NULL, 4000, NULL, 0) ==
      NULL) {
    printf("%s\n", mysql_error(con));
    mysql_close(con);
    exit(1);
  }

  MYSQL_STMT *stmt = mysql_stmt_init(con);
  mysql_stmt_prepare(stmt, "DO ?", 4);

  MYSQL_BIND bind[1];
  int my_int = 1;
  bind[0].buffer_type = MYSQL_TYPE_TINY;
  bind[0].buffer = (void *)&my_int;
  bind[0].is_unsigned = 1;
  bind[0].is_null = 0;

  mysql_stmt_bind_param(stmt, bind);
  mysql_stmt_execute(stmt);
  mysql_stmt_close(stmt);
}

```

This results in:

flag: 0x00
field type: 0x01
field unsigned: 0x80
field value: 1

**Comment by dveeden** [comment]
Looks like this is a bug: https://bugs.mysql.com/bug.php?id=101479
I was using MySQL Connector/Python 8.0.21 and this is fixed in 8.0.24. With 8.0.30 I can't reproduce the issue.

**Comment by xhebox** [comment]
> Looks like this is a bug: https://bugs.mysql.com/bug.php?id=101479 I was using MySQL Connector/Python 8.0.21 and this is fixed in 8.0.24. With 8.0.30 I can't reproduce the issue.

Then what do we do with the PR?

**Review by bb7133 — APPROVED** [review]
LGTM
