### PR TITLE
executor: fix the issue that spill files may not be completely deleted when `Out Of Quota For Local Temporary Space` is triggered

### LINKED ISSUE #63216: Sort/Hash agg/TopN spill data is not completely deleted if out of quota
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Using tpc-h 50 dataset.
Set `tmp-storage-quota` to `10737418240`(10GiB)
```sql
mysql> explain analyze select L_ORDERKEY, L_PARTKEY, L_SUPPKEY, L_LINENUMBER, L_SHIPINSTRUCT, L_SHIPMODE, L_COMMENT from lineitem order by L_ORDERKEY, L_PARTKEY;
ERROR 1105 (HY000): Out Of Quota For Local Temporary Space!
```
Check the tmp-storage directory.

### 2. What did you expect to see? (Required)
Only has a `_dir.lock`, no other data.

### 3. What did you see instead (Required)
```sh
➜  tmp-storage ls
defaultChunkDataInDiskByChunksPath-303605137349  defaultChunkDataInDiskByChunksPath-304203423251  _dir.lock
```

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #63216

Problem Summary:

### What changed and how does it work?

For sort and topn spill, we introduce a variable to record if `inDisk` is appended to `sortedRowsInDisk` so that we can close the `inDisk` when `Out Of Quota For Local Temporary Space` is triggered.

For hash agg spill, we check the length of partial workers' spilledChunksIO. When length is greater than 0. It means that spilledChunksIOs are not collected and we will manually close them.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that spill files may not be completely deleted when `Out Of Quota For Local Temporary Space` is triggered
```

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]
LGTM

File: pkg/executor/sortexec/parallel_sort_spill_test.go [hunk 1]
```diff
@@ -167,3 +170,37 @@ func TestIssue59655(t *testing.T) {
...
 	}
 }
+
+func TestIssue63216(t *testing.T) {
+	sortexec.SetSmallSpillChunkSizeForTest()
+	ctx := mock.NewContext()
+	sortCase := &testutil.SortCase{Rows: 10000, OrderByIdx: []int{0, 1}, Ndvs: []int{0, 0}, Ctx: ctx}
+
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/pkg/executor/sortexec/Issue63216", `return(true)`))
+	defer failpoint.Disable("github.com/pingcap/tidb/pkg/executor/sortexec/Issue63216")
```
Comment (hawkingrei) [inline pkg/executor/sortexec/parallel_sort_spill_test.go]: The right method is like 

image

Comment (hawkingrei) [reply pkg/executor/sortexec/parallel_sort_spill_test.go]: You will not enable the failpoint.

**Review by windtalker — APPROVED** [review]
lgtm
