### PR TITLE
topsql: set RPC interceptor immediately after a txn is activated

### LINKED ISSUE #52845: Flush requests are not tracked by TopSQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

ref #50215 

### 1. Minimal reproduce step (Required)

Run pipelined DMLs

### 2. What did you expect to see? (Required)

TopSQL can track the resource usage of Flush commands.

### 3. What did you see instead (Required)

TopSQL cannot track the resource usage of Flush commands.

### 4. What is your TiDB version? (Required)

master(09313090225382b3756f54438ea7bc53ae6bd937)

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #52845

Problem Summary:

This is to fix the resource group tag problem found in testing of pipelined-dml. The tagger was nil for Flush requests.

### What changed and how does it work?

Set resource group tagger immediately after a txn is activated so that the following Flush requests can use it.

### Check List

Tests 

- [x] Unit test: existing topsql tests are not broken.
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
   Enable P-DML for all UTs, those that failed because of lack of resource group tag now pass.
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/sessiontxn/isolation/base.go [hunk 1]
```diff
@@ -284,6 +284,8 @@ func (p *baseTxnContextProvider) ActivateTxn() (kv.Transaction, error) {
 		return nil, err
 	}
 
+	txn.SetOption(kv.ResourceGroupTagger, p.sctx.GetSessionVars().StmtCtx.GetResourceGroupTagger())
```
Comment (MyonKeminta) [inline pkg/sessiontxn/isolation/base.go:287]: I'm actually not sure whether this is the proper place to do that. And should `RPCInterceptor` be also set? Or should `setOptionForTopSQL` be used instead?

Comment (ekexium) [reply pkg/sessiontxn/isolation/base.go:287]: I put it here to let it work as a backup plan when some auto-commit pipelined dml stmts do not have such option set. It can be override later in other places. Or should we put it in `ExecuteStmt()` after `Compile()`?  @crazycs520 @mornyx What do you think?

Comment (you06) [reply pkg/sessiontxn/isolation/base.go:287]: If the committer is already inited here, `SetOption(kv.ResourceGroupTagger, ...)` won't affect the committer.

https://github.com/tikv/client-go/blob/0606e74e8e373d224ad6e1392729b9780b76a8e8/txnkv/transaction/txn.go#L309-L312

Comment (ekexium) [reply pkg/sessiontxn/isolation/base.go:287]: The pipelined committer is created when txn is created. It seems we need to modify SetOption

Comment (you06) [reply pkg/sessiontxn/isolation/base.go:287]: LGTM

**Review by you06 — APPROVED** [review]
client-go size is updated in https://github.com/tikv/client-go/pull/1212

File: pkg/sessiontxn/isolation/base.go (hunk 1 above)
Comment (ekexium) [reply pkg/sessiontxn/isolation/base.go]: > I'm actually not sure whether this is the proper place to do that. And should RPCInterceptor be also set? Or should setOptionForTopSQL be used instead?

I copied the code to set these options before `commit`, and only apply them for pipelined txns, in favor of caution.

**Review by MyonKeminta — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
