### PR TITLE
restore: set config value to default when failed to get config from tikv

### LINKED ISSUE #36053: Restoring sometimes failed due to `invalid size: ''`
### 1. Minimal reproduce step (Required)

Run BR v6.1.0 and restore to a cluster, with some of TiKV nodes cannot provide the config properly.

### 2. What did you expect to see? (Required)

Restore finished.

### 3. What did you see instead (Required)

```
Error: invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''; invalid size: ''
```

### 4. What is your TiDB version? (Required)

v6.1.0

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Yu Juncen <yujuncen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #36053 

Problem Summary:
If we failed to get region size config from TiKV, we abort the restore procedure, which may not be robust.

### What is changed and how it works?
Use the default config if the region size cannot be fetched from TiKV.

### Check List

Tests 

(TBD)
- [ ] Unit test
- [ ] Manual test (add detailed scripts or steps below)

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fixed a bug that may cause BR reject to restore unexpectedly.
```

### CODE REVIEW

File: br/pkg/conn/conn.go [hunk 1]
```diff
@@ -500,9 +501,10 @@ func (mgr *Mgr) GetMergeRegionSizeAndCount(ctx context.Context, client *http.Cli
 		return nil
 	})
 	if err != nil {
-		return 0, 0, errors.Trace(err)
+		log.Warn("meet error when getting checkpoint from TiKV; using default", logutil.ShortError(err))
```
Comment (3pointer) [inline br/pkg/conn/conn.go:504]:
```suggestion
		log.Warn("meet error when getting config from TiKV; using default", logutil.ShortError(err))
```

**Review by 3pointer — COMMENTED** [review]
rest LGTM

**Review by fengou1 — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Review by joccau — APPROVED** [review]
LGTM
