### PR TITLE
executor: fix clustered index with new collation bug

### LINKED ISSUE #19942: *: unexpected error with both new collation and clustered index are enabled.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Set `new_collations_enabled_on_first_bootstrap` to `True` and start a new cluster.

Enable `CLUSTERED INDEX`:

```
SET @@tidb_enable_clustered_index=1;
```

```
CREATE TABLE test.`t` (
    `a` int(11) NOT NULL,
    `b` int(11) NOT NULL,
    `c` varchar(50) COLLATE utf8_general_ci NOT NULL,
    `s` tinyint(1) NOT NULL,
    PRIMARY KEY (`c`),
    KEY `a_idx` (`a`),
    KEY `b_idx` (`b`),
    KEY `s_idx` (`s`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO test.t (a, b, c, s) VALUES (1, 1, '0', 1);

SELECT * FROM `test`.`t` FORCE INDEX(`a_idx`);
```

### 2. What did you expect to see? (Required)
```
Query succeeded.
```

### 3. What did you see instead (Required)
```
tidb> SELECT * FROM `test`.`t` force index(`a_idx`);
ERROR 1105 (HY000): inconsistent index a_idx handle count 1 isn't equal to value count 0
```
It looks that the value of the secondary index `a_idx` is missing.

### 4. What is your TiDB version? (Required)
```
Release Version: v4.0.0-beta.2-1184-g8a1f11ece
Edition: Community
Git Commit Hash: 8a1f11eceed2a0f6d9a11cb124267a6d9bb86e2c
Git Branch: master
UTC Build Time: 2020-09-10 17:17:28
GoVersion: go1.15beta1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #19942 

Problem Summary:

Normally, index lookup contains 2 phases:

1. get handles from indexed value. (idx_vals -> handle)
2. get the selected fields from handles. (handle -> selected_fields)

The clustered index allows a handle to be a string.

The new collation `utf8_general_ci` encodes the column value to a SortKey(which is not decodable). In a unique or non-unique index, a decodable version of the column value is stored as `RestoredData` in the index value.

But in a `utf8_general_ci` clustered-index table, `RestoredData` is absent. For example,
```sql
CREATE TABLE test.`t` (
    `a` int(11) NOT NULL,
    `b` int(11) NOT NULL,
    `c` varchar(50) COLLATE utf8_general_ci NOT NULL,
    `s` tinyint(1) NOT NULL,
    PRIMARY KEY (`c`),
    KEY `a_idx` (`a`),
    KEY `b_idx` (`b`),
    KEY `s_idx` (`s`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO test.t (a, b, c, s) VALUES (1, 1, '0', 1);

SELECT * FROM `test`.`t` FORCE INDEX(`a_idx`);
```

The layout of `a_idx` is as follows:
- index: a -> handle(c)
- record: handle(c) -> {a, b, s}

When `INSERT` happens, the handle value of column `c` is encoded to a `SortKey`.

When an `IndexLookUp` is running in phase 1, the handle byte slice is searched in the index value, decode to chunk, and encode to a handle. In function `EncodeKey`, the handle is encoded to a `SortKey` for the second time. Thus, the encoded handle is incorrect and invalid:

```
inconsistent index a_idx handle count 1 isn't equal to value count 0
```

We should avoid the handle to be encoded for the second time.

### What is changed and how it works?

What's Changed & How it Works:

For `INSERT` statements in new collation clustered index, the value part of table record save the original handle value.

During index lookup phase 1, we set the new collation common handle to `utf8_bin` temporarily to avoid encoding to a `SortKey` again. Thus we can fetch the correct handle and step forward to phase 2.

For index scan like `select a, c from t use index(a_idx)`, we force it convert to an index lookup to get the origin handle value(`c`).

### Related changes

N/A

### Check List 

Tests 

- Unit test
- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: planner/core/find_best_task.go [hunk 1]
```diff
@@ -932,6 +933,10 @@ func (ds *DataSource) isCoveringIndex(columns, indexColumns []*expression.Column
 		if !indexCoveringCol(col, indexColumns, idxColLens) && !indexCoveringCol(col, ds.commonHandleCols, ds.commonHandleLens) {
 			return false
 		}
+		if collate.NewCollationEnabled() && indexCoveringCol(col, ds.commonHandleCols, ds.commonHandleLens) &&
```
Comment (coocood) [inline planner/core/find_best_task.go:936]: We should check indexCoveringCol for index.
If the column can bound in both index and common handle, we should return true.

File: executor/distsql.go [hunk 2]
```diff
@@ -846,11 +855,23 @@ func (w *tableWorker) pickAndExecTask(ctx context.Context) {
...
 		var handleEncoded []byte
 		var datums []types.Datum
 		for i, idx := range handleIdx {
+			// If the new collation is enabled and the handle contains non-binary string,
+			// we change the collation to "utf8mb4_bin" to avoid encode sortKey again.
+			rtp := e.handleCols[i].RetType
+			if collate.NewCollationEnabled() && rtp.EvalType() == types.ETString &&
+				!mysql.HasBinaryFlag(rtp.Flag) && tp == getHandleFromIndex {
+				origin := rtp.Collate
+				rtp.Collate = charset.CollationUTF8MB4
```
Comment (coocood) [inline executor/distsql.go:870]: We should copy the RetType or there may be data race.

**Comment by coocood** [comment]
LGTM

**Comment by bb7133** [comment]
Excellent description

File: executor/distsql.go [hunk 3]
```diff
@@ -846,11 +855,22 @@ func (w *tableWorker) pickAndExecTask(ctx context.Context) {
...
 
-func (e *IndexLookUpExecutor) getHandle(row chunk.Row, handleIdx []int, isCommonHandle bool) (handle kv.Handle, err error) {
+func (e *IndexLookUpExecutor) getHandle(row chunk.Row, handleIdx []int,
+	isCommonHandle bool, tp getHandleType) (handle kv.Handle, err error) {
 	if isCommonHandle {
 		var handleEncoded []byte
 		var datums []types.Datum
 		for i, idx := range handleIdx {
+			// If the new collation is enabled and the handle contains non-binary string,
+			// we change the collation to "utf8mb4_bin" to avoid encode sortKey again.
```
Comment (bb7133) [inline executor/distsql.go:865]:
```suggestion
			// we change the collation to "binary" to avoid encode sortKey again.
```
BTW, I'm not sure why `binary` and `utf8mb4_bin` both works here.

File: planner/core/integration_test.go [hunk 4]
```diff
@@ -1564,3 +1565,25 @@ func (s *testIntegrationSuite) TestDeleteUsingJoin(c *C) {
...
 	tk.MustQuery("select * from t2").Check(testkit.Rows("2 2"))
 }
+
+func (s *testIntegrationSerialSuite) Test19942(c *C) {
+	collate.SetNewCollationEnabledForTest(true)
+	defer collate.SetNewCollationEnabledForTest(false)
+
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("SET @@tidb_enable_clustered_index=1;")
```
Comment (bb7133) [inline planner/core/integration_test.go:1575]: How about restoring the current `tidb_enable_clustered_index` here and restore it when the test is done?

File: planner/core/integration_test.go [hunk 5]
```diff
@@ -1564,3 +1565,25 @@ func (s *testIntegrationSuite) TestDeleteUsingJoin(c *C) {
...
+	tk.MustExec("CREATE TABLE test.`t` (" +
```
Comment (bb7133) [inline planner/core/integration_test.go:1576]: I suggest changing the test to:

```
DROP TABLE IF EXISTS `test`.`t`;
CREATE TABLE test.`t` (
    `a` int(11) NOT NULL,
    `b` varchar(10) COLLATE utf8_general_ci NOT NULL,
    `c` varchar(50) COLLATE utf8_general_ci NOT NULL,
    `d` char(10) NOT NULL,
    PRIMARY KEY (`c`),
    UNIQUE KEY `a_uniq` (`a`),
    UNIQUE KEY `b_uniq` (`b`),
    UNIQUE KEY `d_uniq` (`d`),
    KEY `a_idx` (`a`),
    KEY `b_idx` (`b`),
    KEY `d_idx` (`d`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO test.t (a, b, c, d) VALUES (1, '1', '0', '1');
INSERT INTO test.t (a, b, c, d) VALUES (2, ' 2', ' 0', ' 2');
INSERT INTO test.t (a, b, c, d) VALUES (3, '  3 ', '  3 ', '  3 ');
INSERT INTO test.t (a, b, c, d) VALUES (4, 'a', 'a   ', 'a');
INSERT INTO test.t (a, b, c, d) VALUES (5, ' A  ', ' A   ', ' A  ');
INSERT INTO test.t (a, b, c, d) VALUES (6, ' E', 'é        ', ' E');

SELECT * FROM `test`.`t` FORCE INDEX(`a_uniq`);
SELECT * FROM `test`.`t` FORCE INDEX(`b_uniq`);
SELECT * FROM `test`.`t` FORCE INDEX(`d_uniq`);
SELECT * FROM `test`.`t` FORCE INDEX(`a_idx`);
SELECT * FROM `test`.`t` FORCE INDEX(`b_idx`);
SELECT * FROM `test`.`t` FORCE INDEX(`d_idx`);
```

So that the "Padding" and unique key are both covered.

File: planner/core/integration_test.go (hunk 4 above)
Comment (tangenta) [reply planner/core/integration_test.go:1575]: This is a session variable. The other tests use a different session by default.

Comment (bb7133) [reply planner/core/integration_test.go:1575]: Oh I see, thanks.

File: executor/distsql.go [hunk 6]
```diff
@@ -846,14 +855,27 @@ func (w *tableWorker) pickAndExecTask(ctx context.Context) {
...
 
-func (e *IndexLookUpExecutor) getHandle(row chunk.Row, handleIdx []int, isCommonHandle bool) (handle kv.Handle, err error) {
+func (e *IndexLookUpExecutor) getHandle(row chunk.Row, handleIdx []int,
+	isCommonHandle bool, tp getHandleType) (handle kv.Handle, err error) {
 	if isCommonHandle {
 		var handleEncoded []byte
 		var datums []types.Datum
 		for i, idx := range handleIdx {
+			// If the new collation is enabled and the handle contains non-binary string,
+			// we change the collation to "binary" to avoid encode sortKey again.
```
Comment (bb7133) [inline executor/distsql.go:865]:
```suggestion
			// we change the collation to "binary" to avoid encode sortKey again.
```
```
// If the new collation is enabled and the handle contains non-binary string, the handle in the index is encoded as "sortKey". So we cannot restore its original value(the primary key) here. 
// we use a trick to avoid encoding the "sortKey" again by changing the charset collation to `binary`.
// TODO: Add the restore value to the secondary index to remove this trick.

**Comment by bb7133** [comment]
LGTM

**Review by coocood — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
