### PR TITLE
executor: special handling is required when an "auto id out of range" error occurs in `insert ignore into ... on on duplicate ...`

### LINKED ISSUE #38950: AUTO_INCREMENT is incompatible with mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE t0(c0 SMALLINT AUTO_INCREMENT PRIMARY KEY);


MySQL [test]> alter table t0 add column c1 int default 1;
Query OK, 0 rows affected (0.081 sec)
Records: 0  Duplicates: 0  Warnings: 0

INSERT IGNORE  INTO t0(c0) VALUES (194626268);

MySQL [test]> INSERT ignore INTO t0(c0) VALUES ('*') on duplicate key update c1 = 2;
Query OK, 2 rows affected, 1 warning (0.040 sec)

```

### 2. What did you expect to see? (Required)
```
MySQL [test]> select * from t0;
+-------+------+
| c0    | c1   |
+-------+------+
| 32767 |    2 |
+-------+------+
1 row in set (0.001 sec)
```

### 3. What did you see instead (Required)

return error

### PR DESCRIPTION
**Pull request by Dousir9**
### What problem does this PR solve?

Issue Number: close #38950 

Problem Summary:

### What is changed and how it works?

The code below is added by PR https://github.com/pingcap/tidb/pull/30301 to fix Issue https://github.com/pingcap/tidb/issues/29483. When `replace` encounters a duplicate `PRIMARY KEY` or `UNIQUE KEY`, it is expected to have the semantics of `DELETE` + `INSERT`, when Auto ID is out of range, the truncated ID is possible to duplicate with an existing ID, this leads to data corruption as unrelated rows are modified and removed.

```go
if err == nil && d.GetInt64() < id {
    // Auto ID is out of range, the truncated ID is possible to duplicate with an existing ID.
    // To prevent updating unrelated rows in the REPLACE statement, it is better to throw an error.
    return autoid.ErrAutoincReadFailed
}
```

So when the `ignore` keyword exists in the SQL (or `SET sql_mode='NO_ENGINE_SUBSTITUTION';`), if the Auto ID is out of range, the above code prevents `replace into` before it is actually executed, but it also prevents a lot SQLs that need to be executed, so special handling is required when an `auto id out of range` error occurs in `insert ignore into ... on duplicate ... ` to allow SQL to be executed successfully.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/insert_common.go [hunk 1]
```diff
@@ -744,11 +744,6 @@ func setDatumAutoIDAndCast(ctx sessionctx.Context, d *types.Datum, id int64, col
 	d.SetAutoID(id, col.GetFlag())
 	var err error
 	*d, err = table.CastValue(ctx, *d, col.ToInfo(), false, false)
-	if err == nil && d.GetInt64() < id {
```
Comment (hawkingrei) [inline executor/insert_common.go:747]: Please add some test cases for it.

File: executor/insert_common.go [hunk 2]
```diff
@@ -747,6 +748,11 @@ func setDatumAutoIDAndCast(ctx sessionctx.Context, d *types.Datum, id int64, col
 	if err == nil && d.GetInt64() < id {
 		// Auto ID is out of range, the truncated ID is possible to duplicate with an existing ID.
 		// To prevent updating unrelated rows in the REPLACE statement, it is better to throw an error.
+		sc := ctx.GetSessionVars().StmtCtx
+		var insertPlan *core.Insert = sc.GetPlan().(*core.Insert)
```
Comment (lance6716) [inline executor/insert_common.go:752]: better to check if the type cast is ok to avoid panic `insertPlan, ok := sc.GetPlan().(*core.Insert)`.

Comment (lance6716) [reply executor/insert_common.go:752]: /cc @tangenta please help decide the behaviour when AUTO_ID reaches limit

File: executor/insert_common.go (hunk 1 above)
Comment (lance6716) [reply executor/insert_common.go:747]: maybe we should add a check about core.Insert.IsReplace in this line 🤔

File: executor/insert_common.go (hunk 2 above)
Comment (Dousir9) [reply executor/insert_common.go]: thanks, done.

File: executor/insert_common.go (hunk 1 above)
Comment (Dousir9) [reply executor/insert_common.go:747]: yes, this also works, but we can put `sc := ctx.GetSessionVars().StmtCtx` and `insertPlan, ok := sc.GetPlan().(*core.Insert)` inside the if statement block to avoid more calls.

**Comment by lance6716** [comment]
Seems @tangenta does not have enough time 😄 

@Dousir9 please help check if current tests have covered all combinations of REPLACE / ON DUPLICATE KEY UPDATE with VALUES `0` / invalid value, and TiDB's behaviour is same as MySQL. rest lgtm

**Comment by Dousir9** [comment]
> Seems @tangenta does not have enough time 😄
> 
> @Dousir9 please help check if current tests have covered all combinations of REPLACE / ON DUPLICATE KEY UPDATE with VALUES `0` / invalid value, and TiDB's behaviour is same as MySQL. rest lgtm

`TestIssue38950` and `TestReplaceAllocatingAutoID` can do that, these cases both cover the value 0 (can be replaced by '*' in ignore mode) and the invalid value (overflowed value), when auto id overflow occurs, the value will be truncated.

there is a MySQL incompatibility caused by PR [#30301](https://github.com/pingcap/tidb/pull/30301)：

```sql
SET sql_mode="";
CREATE TABLE t1 (a tinyint not null auto_increment primary key, b char(20));
INSERT INTO t1 VALUES (127,"maxvalue");
DELETE FROM t1;
REPLACE INTO t1 VALUES (0,"newmaxvalue"); -- MySQL executes successfully
-- ERROR 1467 (HY000): Failed to read auto-increment value from storage engine
```
but [@tangenta](https://github.com/tangenta) thinks it is fine because this error can be an alert, reminding the users that auto-IDs are exhausted.

**Review by lance6716 — APPROVED** [review]

File: executor/writetest/write_test.go [hunk 3]
```diff
@@ -592,6 +592,35 @@ commit;`
...
+	rowStr := fmt.Sprintf("%v %v", "32767", "1")
+	r.Check(testkit.Rows(rowStr))
+
+	tk.MustExec("insert ignore into t(id) values ('*') on duplicate key update c1 = 2;")
+	require.Equal(t, int64(2), int64(tk.Session().AffectedRows()))
+	require.Empty(t, tk.Session().LastMessage())
+
+	r = tk.MustQuery("select * from t;")
+	rowStr = fmt.Sprintf("%v %v", "32767", "2")
+	r.Check(testkit.Rows(rowStr))
```
Comment (mjonss) [inline executor/writetest/write_test.go:621]:
```suggestion
	tk.MustQuery("select * from t").Check(testkit.Rows("32767 2"))
```

File: executor/writetest/write_test.go [hunk 4]
```diff
@@ -592,6 +592,35 @@ commit;`
...
+	testSQL = `alter table t add column c1 int default 1;`
+	tk.MustExec(testSQL)
+
+	testSQL = `insert ignore into t(id) values (194626268);`
+	tk.MustExec(testSQL)
+	require.Empty(t, tk.Session().LastMessage())
+
+	r := tk.MustQuery("select * from t;")
+	rowStr := fmt.Sprintf("%v %v", "32767", "1")
+	r.Check(testkit.Rows(rowStr))
```
Comment (mjonss) [inline executor/writetest/write_test.go:613]:
```suggestion
	tk.MustQuery("select * from t").Check(testkit.Rows("32767 1"))
```

File: executor/writetest/write_test.go [hunk 5]
```diff
@@ -592,6 +592,35 @@ commit;`
...
+	tk.MustExec("use test")
+	testSQL := `drop table if exists t;
+    create table t (id smallint auto_increment primary key);`
+	tk.MustExec(testSQL)
+
+	testSQL = `alter table t add column c1 int default 1;`
+	tk.MustExec(testSQL)
+
+	testSQL = `insert ignore into t(id) values (194626268);`
+	tk.MustExec(testSQL)
```
Comment (mjonss) [inline executor/writetest/write_test.go:608]: Minor, keep as-is if you prefer, otherwise I would suggest to have the testSQL string directly in the `tk.MustExec()`, like
```
tk.MustExec("alter table t add column c1 int default 1")
```

File: executor/insert_common.go [hunk 6]
```diff
@@ -773,6 +774,11 @@ func setDatumAutoIDAndCast(ctx sessionctx.Context, d *types.Datum, id int64, col
 	if err == nil && d.GetInt64() < id {
 		// Auto ID is out of range, the truncated ID is possible to duplicate with an existing ID.
 		// To prevent updating unrelated rows in the REPLACE statement, it is better to throw an error.
```
Comment (mjonss) [inline executor/insert_common.go:776]: Now the comment is out-of-sync with the code, since `err == nil` here.
Please update the comment to clarify why we return nil in this case.

**Review by mjonss — COMMENTED** [review]
Minor suggestions, otherwise LGTM

File: executor/insert_common.go (hunk 6 above)
Comment (Dousir9) [reply executor/insert_common.go]: thanks, done

**Comment by Dousir9** [comment]
@mjonss  I have updated the PR, please review it.

**Review by mjonss — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]
