### PR TITLE
ddl: cancel the job context before rolling back

### LINKED ISSUE #64129: DXF goroutine leak after create index job is cancelled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Enable `tidb_enable_dist_task`.

Run adding index job and cancel the ddl job when reorg timeout occurred.

### 2. What did you expect to see? (Required)

The DDL job should be rolled back and no DXF global task is running.

### 3. What did you see instead (Required)

The job is in "rollback done" state, but the global task & subtasks are still running.

```
mysql> admin show ddl jobs where job_id = 8501;
+--------+---------+------------+-----------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+---------------+----------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE  | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME                | START_TIME                 | END_TIME                   | STATE         | COMMENTS |
+--------+---------+------------+-----------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+---------------+----------+
|   8501 | c66_dc  | orders_1   | add index | none         |      8497 |     8414 | 112374347 | 2025-10-21 14:01:32.171000 | 2025-10-21 14:01:32.221000 | 2025-10-21 14:07:59.871000 | rollback done |          |
+--------+---------+------------+-----------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+---------------+----------+
1 row in set (0.05 sec)
```

```
[2025/10/23 20:15:05.176 +00:00] [WARN] [engine_mgr.go:64] ["build ingest engine failed"] [keyspaceName=SYSTEM] [task-id=1] [task-key=keyspace_a/ddl/backfill/8501] [subtaskID=2] [step=read-index] ["job ID"=8501] ["index ID"=8] [error="lock held by current process"] [errorVerbose="lock held by current process\n(1) attached stack trace\n  -- stack trace:\n  | github.com/cockroachdb/pebble/vfs.defaultFS.Lock\n  | \t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/vfs/file_lock_unix.go:50\n  | github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).Lock\n  | \t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/vfs/disk_health.go:679\n  | github.com/cockroachdb/pebble.LockDirectory\n  | \t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/open.go:1068\n  | github.com/cockroachdb/pebble.Open\n  | \t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/open.go:116\n  | github.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngineDB\n  | \t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:230\n  | github.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngine\n  | \t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:236\n  | github.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).OpenEngine\n  | \t/workspace/source/tidb/pkg/lightning/backend/local/local.go:833\n  | github.com/pingcap/tidb/pkg/lightning/backend.EngineManager.OpenEngine\n  | \t/workspace/source/tidb/pkg/lightning/backend/backend.go:271\n  | github.com/pingcap/tidb/pkg/ddl/ingest.(*litBackendCtx).Register\n  | \t/workspace/source/tidb/pkg/ddl/ingest/engine_mgr.go:62\n  | github.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).buildLocalStorePipeline\n  | \t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:358\n  | github.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).runLocalPipeline\n  | \t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:160\n  | github.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).RunSubtask\n  | \t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:206\n  | github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask.func1\n  | \t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:466\n  | github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask\n  | \t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:467\n  | github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).Run\n  | \t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:344\n  | github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).startTaskExecutor.func2\n  | \t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/manager.go:345\n  | github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1\n  | \t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:181\n  | runtime.goexit\n  | \t/usr/local/go/src/runtime/asm_amd64.s:1700\nWraps: (2) lock held by current process\nError types: (1) *withstack.withStack (2) *errutil.leafError\ngithub.com/pingcap/errors.Trace\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20250523034308-74f78ae071ee/juju_adaptor.go:15\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngineDB\n\t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:231\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngine\n\t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:236\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).OpenEngine\n\t/workspace/source/tidb/pkg/lightning/backend/local/local.go:833\ngithub.com/pingcap/tidb/pkg/lightning/backend.EngineManager.OpenEngine\n\t/workspace/source/tidb/pkg/lightning/backend/backend.go:271\ngithub.com/pingcap/tidb/pkg/ddl/ingest.(*litBackendCtx).Register\n\t/workspace/source/tidb/pkg/ddl/ingest/engine_mgr.go:62\ngithub.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).buildLocalStorePipeline\n\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:358\ngithub.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).runLocalPipeline\n\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:160\ngithub.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).RunSubtask\n\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:206\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask.func1\n\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:466\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask\n\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:467\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).Run\n\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:344\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).startTaskExecutor.func2\n\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/manager.go:345\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1\n\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:181\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"]
```

```
goroutine 115111222 [semacquire, 7999 minutes]:
sync.runtime_Semacquire(0xc0b75cfde8?)
        /usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*WaitGroup).Wait(0x7298560?)
        /usr/local/go/src/sync/waitgroup.go:118 +0x48
golang.org/x/sync/errgroup.(*Group).Wait(0xc045bb72c0)
        /root/go/pkg/mod/golang.org/x/sync@v0.16.0/errgroup/errgroup.go:56 +0x25
github.com/pingcap/tidb/pkg/ddl.(*worker).executeDistTask(0xc051eb25b0, 0xc032990000, {0x7fe8b58, 0xc016de09a0}, 0xc016ddb300)
        /workspace/source/tidb/pkg/ddl/index.go:2917 +0xbfb
github.com/pingcap/tidb/pkg/ddl.(*worker).addTableIndex(0xc051eb25b0, 0xc0166a9600?, {0x7fe8b58, 0xc016de09a0}, 0xc016ddb300)
        /workspace/source/tidb/pkg/ddl/index.go:2599 +0x75
github.com/pingcap/tidb/pkg/ddl.runReorgJobAndHandleErr.func1()
        /workspace/source/tidb/pkg/ddl/index.go:1713 +0xc6
github.com/pingcap/tidb/pkg/ddl.(*worker).runReorgJob.func1()
        /workspace/source/tidb/pkg/ddl/reorg.go:380 +0x29
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
        /workspace/source/tidb/pkg/util/wait_group_wrapper.go:167 +0x4c
created by github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run in goroutine 115096206
        /workspace/source/tidb/pkg/util/wait_group_wrapper.go:165 +0x73
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #64129

Problem Summary: See #64129

### What changed and how does it work?

When a reorganization timeout error occurs, `ADMIN CANCEL` change the state of the DDL job and the job context is not canceled. As a result, background global tasks continue to run and never complete.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/db_integration_test.go [hunk 1]
```diff
@@ -3147,3 +3147,27 @@ func TestCreateIndexWithChangeMaxIndexLength(t *testing.T) {
 	tk.MustExec("create table t(id int, a json DEFAULT NULL, b varchar(2) DEFAULT NULL);")
 	tk.MustGetErrMsg("CREATE INDEX idx_test on t ((cast(a as char(2000) array)),b);", "[ddl:1071]Specified key was too long (2000 bytes); max key length is 1000 bytes")
 }
+
+func TestCancelAfterReorgTimeout(t *testing.T) {
```
Comment (D3Hunter) [inline pkg/ddl/db_integration_test.go]: move to real-tikv test? and verify the dxf task is cancelled before the DDL finishes

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 2]
```diff
@@ -261,3 +264,56 @@ func TestMultiSchemaChangeAnalyzeOnlyOnce(t *testing.T) {
...
+	})
+	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/ddl/onRunReorgJobTimeout", func() {
+		if !afterTimeout {
+			timeout <- struct{}{}
+			afterTimeout = true
+		}
+	})
+	tk.MustGetErrCode("alter table t add index idx(a);", errno.ErrCancelledDDLJob)
+	require.Eventually(t, func() bool {
+		result := tk.MustQuery("select state from mysql.tidb_global_task;").Rows()
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest4/integration_test.go]: cleaner might move it into history table

**Review by D3Hunter — COMMENTED** [review]
rest lgtm
