### PR TITLE
bootstrap: split index merge bootstrap case

### LINKED ISSUE #46834: slow test `TestIndexMergeUpgradeFrom400To540` in `session` pkg
## Bug Report

<details><summary><h3>Average timecost was 294480.0000ms between "2023-09-01" AND "2023-09-08"<h3></summary>

Found records: 1  (filter only for runs that timecost >= threshold)
Max timecost: 294480ms
Min timecost: 294480ms
Avg timecost: 294480.0000ms

- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32079/): used 294480ms

</details>

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #46834

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/session/bootstrap_test.go [hunk 1]
```diff
@@ -851,71 +851,77 @@ func TestIndexMergeUpgradeFrom300To540(t *testing.T) {
...
-			// We are now in 4.0.0, tidb_enable_index_merge is off.
-			res := MustExecToRecodeSet(t, seV4, fmt.Sprintf("select * from mysql.GLOBAL_VARIABLES where variable_name='%s'", variable.TiDBEnableIndexMerge))
-			chk := res.NewChunk(nil)
-			err = res.Next(ctx, chk)
-			require.NoError(t, err)
-			require.Equal(t, 1, chk.NumRows())
-			row := chk.GetRow(0)
-			require.Equal(t, 2, row.Len())
-			require.Equal(t, variable.Off, row.GetString(1))
+func indexMergeUpgradeFrom400To540(t *testing.T, enable bool) {
```
Comment (wuhuizuo) [inline pkg/session/bootstrap_test.go:864]:
```suggestion
func testIndexMergeUpgradeFrom400To540(t *testing.T, enable bool) {
```

File: pkg/session/bootstrap_test.go [hunk 2]
```diff
@@ -851,71 +851,77 @@ func TestIndexMergeUpgradeFrom300To540(t *testing.T) {
...
-func TestIndexMergeUpgradeFrom400To540(t *testing.T) {
-	for i := 0; i < 2; i++ {
-		func() {
-			ctx := context.Background()
-			store, dom := CreateStoreAndBootstrap(t)
-			defer func() { require.NoError(t, store.Close()) }()
+// We set tidb_enable_index_merge as on.
+// And after upgrade to 5.x, tidb_enable_index_merge should remains to be on.
+func TestIndexMergeUpgradeFrom400To540Enable(t *testing.T) {
+	indexMergeUpgradeFrom400To540Helper(t, true)
```
Comment (wuhuizuo) [inline pkg/session/bootstrap_test.go:857]:
```suggestion
	testIndexMergeUpgradeFrom400To540(t, true)
```

File: pkg/session/bootstrap_test.go [hunk 3]
```diff
@@ -851,71 +851,77 @@ func TestIndexMergeUpgradeFrom300To540(t *testing.T) {
...
-			require.NoError(t, err)
-			MustExec(t, seV4, fmt.Sprintf("update mysql.tidb set variable_value=%d where variable_name='tidb_server_version'", ver400))
-			MustExec(t, seV4, fmt.Sprintf("update mysql.GLOBAL_VARIABLES set variable_value='%s' where variable_name='%s'", variable.Off, variable.TiDBEnableIndexMerge))
-			MustExec(t, seV4, "commit")
-			unsetStoreBootstrapped(store.UUID())
-			ver, err := getBootstrapVersion(seV4)
-			require.NoError(t, err)
-			require.Equal(t, int64(ver400), ver)
+func TestIndexMergeUpgradeFrom400To540Disable(t *testing.T) {
+	indexMergeUpgradeFrom400To540Helper(t, false)
```
Comment (wuhuizuo) [inline pkg/session/bootstrap_test.go:861]:
```suggestion
	testIndexMergeUpgradeFrom400To540(t, false)
```

**Review by Defined2014 — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]
