### PR TITLE
server: increase the failed SQL log level from Info to Warn

### LINKED ISSUE #65359: server: increase the failed SQL log level from Info to Warn
## Enhancement

See the code below, for each failed SQL, now we record a metric and a log for it.

Image

But the default log level is Info, some of our users are using the Warn level since their QPS is too high, if using the Info level, there are too many logs.
Then for these users, if they have some failed SQLs, we can see them on the Metrcis but can't see their details in logs.

For the example below, we can see the failed SQL QPS is around 300+, but we can't get any details about them in our log.
Failed SQL info is critical and its number shouldn't be very large, so it's fair to increase its log level from Info to Warn.

Image

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #65359

Problem Summary: server: increase the failed SQL log level from Info to Warn

### What changed and how does it work?

Please see https://github.com/pingcap/tidb/issues/65359

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/server/conn.go [hunk 1]
```diff
@@ -1212,7 +1212,7 @@ func (cc *clientConn) Run(ctx context.Context) {
 						timestamp = ctx.GetSessionVars().TxnCtx.StaleReadTs
 					}
 				}
-				logutil.Logger(ctx).Info("command dispatched failed",
+				logutil.Logger(ctx).Warn("command dispatched failed",
```
Comment (zimulala) [inline pkg/server/conn.go:1215]: Should we consider handling `ErrKeyExists` as a noisy / expected error (similar to `errIsNoisy`) and filter it out?
Otherwise, this could result in a large number of warning logs in certain scenarios, which may reduce log signal quality.

Comment (qw4990) [reply pkg/server/conn.go:1215]: I've discussed this with our Txn Team, and they just said it's better to use `Warn` also for `ErrKeyExsits`.
