### PR TITLE
planner: natural join not consider rowid and null eq not propagate

### LINKED ISSUE #17817: P1-[4.0 bug hunting]-[SQL Plan Management]-NATURAL LEFT JOIN results in incorrect result for <=> operator
Bug Hunter issue tidb-challenge-program/bug-hunting-issue#5

---

Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t0 VALUES (0);
INSERT INTO t1 VALUES (0);
SELECT * FROM t1 NATURAL LEFT JOIN t0 WHERE NOT(t0.c0<=>t1.c0); -- expected: {}, actual: {0}
```
Unexpectedly, the `SELECT` fetches a row:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1452
Server version: 5.7.25-TiDB-v4.0.0-beta.2-231-gc66320c46 TiDB Server (Apache License 2.0), MySQL 5.7 compatible

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE TABLE t0(c0 INT);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t1(c0 INT);
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t0 VALUES (0);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (0);
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t1 NATURAL LEFT JOIN t0 WHERE NOT(t0.c0<=>t1.c0); -- expected: {}, actual: {0}
+------+
| c0   |
+------+
|    0 |
+------+
1 row in set (0.00 sec)
```

 Interestingly, the following query with the negated predicate also fetches a row, which is expected:
```sql
SELECT t1.c0 FROM t1 NATURAL LEFT JOIN t0 WHERE t0.c0<=>t1.c0 -- {0}
```
I double-checked with MySQL 8.0.19, which does not fetch a row for the first query, as expected:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 14
Server version: 8.0.19 MySQL Community Server - GPL

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE TABLE t0(c0 INT);
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE t1(c0 INT);
Query OK, 0 rows affected (0.04 sec)

mysql> INSERT INTO t0 VALUES (0);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t1 VALUES (0);
Query OK, 1 row affected (0.01 sec)

mysql> SELECT * FROM t1 NATURAL LEFT JOIN t0 WHERE NOT(t0.c0<=>t1.c0); -- expected: {}, actual: {0}
Empty set (0.00 sec)
```
Environment:
```
| Release Version: v4.0.0-beta.2-231-gc66320c46
Git Commit Hash: c66320c46456c0d5b23b3b0403be6b9f8227d6d8
Git Branch: master
UTC Build Time: 2020-04-14 11:12:29
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```
I propose P0 as a bug level, since it matches the following description: `wrong results returned by the query, and inconsistent results returned by the SQL output`.

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #17817

### What is changed and how it works?

How it Works: as the title says.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- natural join should not consider rowid and null eq should not propagate in outer join.

### CODE REVIEW

File: expression/constant_propagation.go [hunk 1]
```diff
@@ -132,11 +132,15 @@ func tryToReplaceCond(ctx sessionctx.Context, src *Column, tgt *Column, cond Exp
 	if _, ok := inequalFunctions[sf.FuncName.L]; ok {
 		return false, true, cond
 	}
-	// See https://github.com/pingcap/tidb/issues/15782. The control function's result may rely on the original nullable
-	// information of the outer side column. Its args cannot be replaced easily.
+	// See https://github.com/pingcap/tidb/issues/15782. The null sensitive function's result may rely on the original
```
Comment (winoros) [inline expression/constant_propagation.go:135]: We'd better add the new issue here too?

Comment (lzmhhh123) [reply expression/constant_propagation.go:135]: OK.

**Review by winoros — COMMENTED** [review]
lgtm

File: planner/core/testdata/point_get_plan_out.json [hunk 2]
```diff
@@ -87,14 +87,14 @@
         "Plan": [
           "Point_Get_1 1.00 root table:t1, clustered index:PRIMARY(id) "
         ],
-        "Res": []
+        "Res": null
```
Comment (eurekaka) [inline planner/core/testdata/point_get_plan_out.json:90]: How is this change related to this PR?

File: expression/constant_propagation.go [hunk 3]
```diff
@@ -119,7 +119,7 @@ func validEqualCond(ctx sessionctx.Context, cond Expression) (*Column, *Constant
 //  for 'a, b, a < 3', it returns 'true, false, b < 3'
 //  for 'a, b, sin(a) + cos(a) = 5', it returns 'true, false, returns sin(b) + cos(b) = 5'
 //  for 'a, b, cast(a) < rand()', it returns 'false, true, cast(a) < rand()'
-func tryToReplaceCond(ctx sessionctx.Context, src *Column, tgt *Column, cond Expression, rejectControl bool) (bool, bool, Expression) {
+func tryToReplaceCond(ctx sessionctx.Context, src *Column, tgt *Column, cond Expression, rejectNullSens bool) (bool, bool, Expression) {
```
Comment (eurekaka) [inline expression/constant_propagation.go:122]:
```suggestion
func tryToReplaceCond(ctx sessionctx.Context, src *Column, tgt *Column, cond Expression, nullAware bool) (bool, bool, Expression) {
```

File: planner/core/testdata/point_get_plan_out.json (hunk 2 above)
Comment (lzmhhh123) [reply planner/core/testdata/point_get_plan_out.json:90]: It's unrelated. But run `go test -record` changes it automatically. Both `[]` and `null` are correct for this test.

**Review by eurekaka — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
