### PR TITLE
ddl: job context will be canceled when cancel or pause job

### LINKED ISSUE #56017: non-dist-task fast-reorg ADD INDEX can't be canceled timely
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

It has been stuck in "cancelling" for a long time, and lightning's goroutine didn't exit.

```
1 @ 0x474cf87 0x474fbea 0x474e93b 0x474e9c5 0x474e9c5 0x472e3cc 0x472e38b 0x472d8aa 0x472dba5 0x476b42b 0x48a8970 0x48a83d3 0x481cb25 0x481c4e9 0x481c1a5 0x492d6f0 0x492b545 0x30f90ef 0x1f6c901
#	0x474cf86	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).flushKVs.func1+0xc6				/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1355
#	0x474fbe9	slices.partitionCmpFunc[...]+0xe49										/usr/local/go/src/slices/zsortanyfunc.go:154
#	0x474e93a	slices.pdqsortCmpFunc[...]+0x49a										/usr/local/go/src/slices/zsortanyfunc.go:114
#	0x474e9c4	slices.pdqsortCmpFunc[...]+0x524										/usr/local/go/src/slices/zsortanyfunc.go:121
#	0x474e9c4	slices.pdqsortCmpFunc[...]+0x524										/usr/local/go/src/slices/zsortanyfunc.go:121
#	0x472e3cb	slices.SortFunc[...]+0x8b											/usr/local/go/src/slices/sort.go:28
#	0x472e38a	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).flushKVs+0x4a					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1355
#	0x472d8a9	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).appendRowsUnsorted+0x5e9				/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1242
#	0x472dba4	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).AppendRows+0x264					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1279
#	0x476b42a	github.com/pingcap/tidb/pkg/ddl/ingest.(*writerContext).WriteRow+0x1aa						/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/ingest/engine.go:217
#	0x48a896f	github.com/pingcap/tidb/pkg/ddl.writeOneKVToLocal+0x1ef								/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/index.go:1781
#	0x48a83d2	github.com/pingcap/tidb/pkg/ddl.writeChunkToLocal+0xb92								/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/index.go:1740
#	0x481cb24	github.com/pingcap/tidb/pkg/ddl.(*indexIngestBaseWorker).WriteChunk+0x124					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:874
#	0x481c4e8	github.com/pingcap/tidb/pkg/ddl.(*indexIngestBaseWorker).HandleTask+0xa8					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:812
#	0x481c1a4	github.com/pingcap/tidb/pkg/ddl.(*indexIngestLocalWorker).HandleTask+0x124					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:763
#	0x492d6ef	github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool.(*WorkerPool[...]).handleTaskWithRecover+0x1cf	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool/workerpool.go:142
#	0x492b544	github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool.(*WorkerPool[...]).runAWorker.func1+0x84		/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool/workerpool.go:158
#	0x30f90ee	github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1+0x4e						/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:157

1 @ 0x474cf87 0x474fdc4 0x474e93b 0x474ea38 0x474ea38 0x474ea38 0x474ea38 0x474e9c5 0x474ea38 0x472e3cc 0x472e38b 0x472d8aa 0x472dba5 0x476b42b 0x48a8970 0x48a83d3 0x481cb25 0x481c4e9 0x481c1a5 0x492d6f0 0x492b545 0x30f90ef 0x1f6c901
#	0x474cf86	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).flushKVs.func1+0xc6				/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1355
#	0x474fdc3	slices.partitionCmpFunc[...]+0x1023										/usr/local/go/src/slices/zsortanyfunc.go:157
#	0x474e93a	slices.pdqsortCmpFunc[...]+0x49a										/usr/local/go/src/slices/zsortanyfunc.go:114
#	0x474ea37	slices.pdqsortCmpFunc[...]+0x597										/usr/local/go/src/slices/zsortanyfunc.go:125
#	0x474ea37	slices.pdqsortCmpFunc[...]+0x597										/usr/local/go/src/slices/zsortanyfunc.go:125
#	0x474ea37	slices.pdqsortCmpFunc[...]+0x597										/usr/local/go/src/slices/zsortanyfunc.go:125
#	0x474ea37	slices.pdqsortCmpFunc[...]+0x597										/usr/local/go/src/slices/zsortanyfunc.go:125
#	0x474e9c4	slices.pdqsortCmpFunc[...]+0x524										/usr/local/go/src/slices/zsortanyfunc.go:121
#	0x474ea37	slices.pdqsortCmpFunc[...]+0x597										/usr/local/go/src/slices/zsortanyfunc.go:125
#	0x472e3cb	slices.SortFunc[...]+0x8b											/usr/local/go/src/slices/sort.go:28
#	0x472e38a	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).flushKVs+0x4a					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1355
#	0x472d8a9	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).appendRowsUnsorted+0x5e9				/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1242
#	0x472dba4	github.com/pingcap/tidb/pkg/lightning/backend/local.(*Writer).AppendRows+0x264					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/lightning/backend/local/engine.go:1279
#	0x476b42a	github.com/pingcap/tidb/pkg/ddl/ingest.(*writerContext).WriteRow+0x1aa						/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/ingest/engine.go:217
#	0x48a896f	github.com/pingcap/tidb/pkg/ddl.writeOneKVToLocal+0x1ef								/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/index.go:1781
#	0x48a83d2	github.com/pingcap/tidb/pkg/ddl.writeChunkToLocal+0xb92								/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/index.go:1740
#	0x481cb24	github.com/pingcap/tidb/pkg/ddl.(*indexIngestBaseWorker).WriteChunk+0x124					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:874
#	0x481c4e8	github.com/pingcap/tidb/pkg/ddl.(*indexIngestBaseWorker).HandleTask+0xa8					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:812
#	0x481c1a4	github.com/pingcap/tidb/pkg/ddl.(*indexIngestLocalWorker).HandleTask+0x124					/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:763
#	0x492d6ef	github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool.(*WorkerPool[...]).handleTaskWithRecover+0x1cf	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool/workerpool.go:142
#	0x492b544	github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool.(*WorkerPool[...]).runAWorker.func1+0x84		/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/resourcemanager/pool/workerpool/workerpool.go:158
#	0x30f90ee	github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1+0x4e						/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:157
```

Then it begins to `generateAndSendJob`. Seems the `ctx` is not cancelled

### 4. What is your TiDB version? (Required)

```
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v8.5.0-alpha                             |
| Edition: Community                                        |
| Git Commit Hash: b97baba693964ef0625eb7f0b4b321d40a16b3fe |
| Git Branch: heads/refs/tags/v8.5.0-alpha                  |
| UTC Build Time: 2024-09-09 04:40:51                       |
| GoVersion: go1.21.10                                      |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

### LINKED ISSUE #56398: refine the context and context-like struct usage in DDL
## Enhancement

Currently the context usage is a bit of messy. One problem is https://github.com/pingcap/tidb/issues/56017 and I think a better context usage and cancellation will solve it. After a simple review of current DDL code, I think there should to 2 type of context:

1. the context of a DDL job. All job execution logic should use this context. And another goroutine polling the job state should cancel the context if it's not `JobStateRunning`.
2. the context of DDL module. Job rollingback, scheduling, execution and other module-level action should use this context. It's canceled when the parent context is canceled which means domain is closing.

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #56398 close #56017

Problem Summary:

### What changed and how does it work?

This PR aims to remove the logic that periodically return to main loop and check job state. Instead, the job execution can occupy the main goroutine for a long time and a background goroutine checks the job state and cancel the context. 

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — COMMENTED** [review]
13/25 will review later

File: pkg/ddl/rollingback.go [hunk 1]
```diff
@@ -293,6 +293,7 @@ func rollingbackAddIndex(w *worker, jobCtx *jobContext, job *model.Job, isPK boo
 	return
 }
 
+// TODO(lance6716): delete now?
```
Comment (tangenta) [inline pkg/ddl/rollingback.go:296]: +1

Comment (tangenta) [inline pkg/ddl/rollingback.go:296]: +1

File: pkg/ddl/job_scheduler.go [hunk 2]
```diff
@@ -470,6 +471,47 @@ func (s *jobScheduler) deliveryJob(wk *worker, pool *workerPool, job *model.Job)
...
+					logutil.DDLLogger().Error("get job failed, will retry later",
+						zap.Int64("job_id", jobID), zap.Error(err))
+					continue
+				}
+				switch latestJob.State {
+				case model.JobStateCancelling, model.JobStateCancelled:
+					logutil.DDLLogger().Info("job is cancelled",
+						zap.Int64("job_id", jobID),
+						zap.Stringer("state", latestJob.State))
+					jobCtx.cancel(dbterror.ErrCancelledDDLJob)
```
Comment (D3Hunter) [inline pkg/ddl/job_scheduler.go:501]: seems we can return here too

File: pkg/ddl/constraint.go [hunk 3]
```diff
@@ -371,7 +371,7 @@ func (w *worker) verifyRemainRecordsForCheckConstraint(dbInfo *model.DBInfo, tab
 	// can let the check expression restored string as the filter in where clause directly.
 	// Prepare internal SQL to fetch data from physical table under this filter.
 	sql := fmt.Sprintf("select 1 from `%s`.`%s` where not %s limit 1", dbInfo.Name.L, tableInfo.Name.L, constr.ExprString)
-	ctx := kv.WithInternalSourceType(w.ctx, kv.InternalTxnDDL)
+	ctx := kv.WithInternalSourceType(w.workCtx, kv.InternalTxnDDL)
```
Comment (tangenta) [inline pkg/ddl/constraint.go:374]: What are the criteria for using `jobCtx.ctx` or `w.workerCtx`? I think using `jobCtx.ctx` is also reasonable here.

Comment (lance6716) [reply pkg/ddl/constraint.go:374]: Yes job context is better. I want the action has no related job to use worker's context. Here I forget to change the function signature to pass job context.

File: pkg/ddl/rollingback.go [hunk 4]
```diff
@@ -662,6 +624,11 @@ func convertJob2RollbackJob(w *worker, jobCtx *jobContext, job *model.Job) (ver
 		err = dbterror.ErrCancelledDDLJob
 	}
 
+	if job.State == model.JobStateRollingback {
+		// try the best effort to rollback, ignore the cancellation.
+		jobCtx.ctx = w.workCtx
```
Comment (D3Hunter) [inline pkg/ddl/rollingback.go:629]: harder to reason if we change context in the middle of execution, please add more comment for this field

the `context` we want to cancel if the job transit to `canceling` state should be the context of the step, not the context of job execution loop, we still need to handle `cancelling -> rollback if needed -> cancelled` step, see ideas below.

other ideas I can think of now is
- have a context per step, only start the cancel check routine on non-cancel/done/rollbackdone state, but it might be too heavy for general DDL, they normally runs fast, we might need to test the real overhead.
- only start the check routine for reorg jobs, but then this loop is a little duplicate with transitOneJobStepAndWaitSync loop, 1 should be enough

File: pkg/ddl/job_worker.go [hunk 5]
```diff
@@ -970,7 +973,12 @@ func toTError(err error) *terror.Error {
 
 // updateGlobalVersionAndWaitSynced update global schema version to notify all TiDBs
 // to reload info schema, and waits for all servers' schema or MDL synced.
-func updateGlobalVersionAndWaitSynced(jobCtx *jobContext, latestSchemaVersion int64, job *model.Job) error {
+func updateGlobalVersionAndWaitSynced(
+	ctx context.Context,
+	jobCtx *jobContext,
+	latestSchemaVersion int64,
+	job *model.Job,
+) error {
```
Comment (D3Hunter) [inline pkg/ddl/job_worker.go:981]: line 993 is using jobCtx.ctx, it might now working if state overwritten, see https://github.com/pingcap/tidb/issues/52747
- job worker change to done, but before we wait cancelled by other session
- cancel check routine cancelled it
- we start wait version using a cancelled context, never work

File: pkg/ddl/rollingback.go (hunk 4 above)
Comment (lance6716) [reply pkg/ddl/rollingback.go:629]: I want to discuss this topic "the context belongs to job step or job or other things?" here @tangenta 

My idea is the job workflow has two directions: forward and rollingback. Both directions have multiple job steps. Only the forward direction can cancel the context. And my original thought is there are two types of job context like `jobContext` and `rollbackJobContext`, only the former one has a `cancel` member. But I think we don't bother to add a new struct. Maybe I can add a `IsRollback` to `jobContext` and add `getCtx` to return `jobCtx.ctx` or `context.Background()` based on it?

Another idea is the `getCtx` function should have a `JobState` argument, and check state to return `jobCtx.ctx` or `context.Background()`.

> have a context per step

I think this is similar to "`getCtx` function should have a `JobState` argument" and has less overhead.

> only start the check routine for reorg jobs

For simplicity I don't want to treat reorg jobs specially.

File: pkg/ddl/job_worker.go (hunk 5 above)
Comment (lance6716) [reply pkg/ddl/job_worker.go:984]: https://github.com/pingcap/tidb/pull/56404/commits/41a7af827efedc60521e5c435787c471005d1e39 not sure I understand it correctly.

File: pkg/ddl/rollingback.go (hunk 4 above)
Comment (D3Hunter) [reply pkg/ddl/rollingback.go:629]: the thing we want to cancel is the running step when job state changed by other session, and the job worker loop should keeps running other following steps.

in this pr we create a context for the entire job worker loop, and then we change it if we detect it's cancelled, to keep the code working, quite anti-pattern. I expect something similar to this: 
if we need to cancel a subtask, then we cancel its own context, leave upper layers of context unchanged
https://github.com/pingcap/tidb/blob/025c2a3c5b72557b1a4fc2df7c0ee7be8f551957/pkg/disttask/framework/taskexecutor/task_executor.go#L384-L404

Comment (lance6716) [reply pkg/ddl/rollingback.go:629]: > the thing we want to cancel is the running step when job state changed by other session, and the job worker loop should keeps running other following steps.

This does not describe the property "rollback steps should not be canceled" or "cancelation only happens once". Extra logic should be introduced to accomplish this step context model and make it more complex. I think the two direction model is more clear.

To avoid replace the context on the fly, maybe this code is more clear

```golang
func transitOneJobStep() {
  if job.IsRollingback() {
    worker.runOneRollingbackJobStep(worker.ctx, jobCtx, job)
  } else {
    worker.runOneJobStep(jobCtx.ctx, jobCtx, job)
  }
}
```

But it's a bit weird that the `jobCtx` has `Ctx` in its name but doesn't have a `ctx` member.

Or we construct another `jobCtx`?

```golang
jobStepCtx := jobCtx
if job.IsRollingback() {
  jobStepCtx = newRollingbackJobCtx(jobCtx)
}
worker.runOneJobStep(jobStepCtx, job)
```

Comment (tangenta) [reply pkg/ddl/rollingback.go:629]: @D3Hunter We cannot cancel the own context directly in `admin cancel` because it may be executed in another TiDB. In any case, another loop is needed, whether it is put to the "entire job worker" or "step".

Comment (D3Hunter) [reply pkg/ddl/rollingback.go:629]: > @D3Hunter We cannot cancel the own context directly in `admin cancel` because it may be executed in another TiDB. In any case, another loop is needed, whether it is put to the "entire job worker" or "step".

yes, we have consensus on that. I think we are discussing context lifecycle and avoiding changing context here

Comment (lance6716) [reply pkg/ddl/rollingback.go]: updated https://github.com/pingcap/tidb/pull/56404/commits/3516e3c36765fcd59c06e16b49f9a6c6599e1868

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
/hold

i will test how this bg routine affects create-table, will unhold it later

**Comment by D3Hunter** [comment]
/unhold

100K, 9m11.9s, cpu/mem looks fine too

**Review by tangenta — APPROVED** [review]
