### PR TITLE
executor: modify the error message of insert time value

### LINKED ISSUE #20207: Different error code from MySQL when inserting incorrect time value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
drop table if exists t; create table t(a time); insert into t values(8385966);
```
### 2. What did you expect to see? (Required)

Both MySQL 5.7 and MySQL 8.0 produces error code 1292
```mysql
mysql> drop table if exists t; create table t(a time); insert into t values(8385966);
Query OK, 0 rows affected (0.02 sec)

Query OK, 0 rows affected (0.02 sec)

ERROR 1292 (22007): Incorrect time value: '8385966' for column 'a' at row 1
```

### 3. What did you see instead (Required)

```mysql
mysql> drop table if exists t; create table t(a time); insert into t values(8385966);
Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.01 sec)

ERROR 1366 (HY000): Incorrect time value: '8385966' for column 'a' at row 1
```

### 4. What is your TiDB version? (Required)

master (6a10e2129)

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by ou-bing**
### What problem does this PR solve?

Issue Number: close #20207   

Problem Summary:

### What is changed and how it works?

What's Changed:

Change error code and error info when insert time value.

### Check List 

Tests 

- Unit test

### Release note 

- Change error code and error info when insert time value.

### CODE REVIEW

**Comment by ou-bing** [comment]
@lzmhhh123 I fixed it.

File: executor/insert_common.go [hunk 1]
```diff
@@ -291,6 +293,17 @@ func (e *InsertValues) handleErr(col *table.Column, val *types.Datum, rowIdx int
 		err = types.ErrWarnDataOutOfRange.GenWithStackByArgs(colName, rowIdx+1)
 	} else if types.ErrTruncated.Equal(err) {
 		err = types.ErrTruncated.GenWithStackByArgs(colName, rowIdx+1)
+	} else if types.ErrTruncatedWrongVal.Equal(err) && (colTp == mysql.TypeDuration || colTp == mysql.TypeDatetime) {
+		valStr, err1 := val.ToString()
+		if err1 != nil {
+			logutil.BgLogger().Warn("truncate value failed", zap.Error(err1))
```
Comment (lzmhhh123) [inline executor/insert_common.go:299]: We'd better ignore the error here instead of log it.

Comment (ou-bing) [reply executor/insert_common.go:299]: 好的👌

Comment (ou-bing) [reply executor/insert_common.go]: The log has been removed.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ichn-hu — DISMISSED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

File: executor/insert_common.go [hunk 2]
```diff
@@ -291,10 +291,21 @@ func (e *InsertValues) handleErr(col *table.Column, val *types.Datum, rowIdx int
 		err = types.ErrWarnDataOutOfRange.GenWithStackByArgs(colName, rowIdx+1)
 	} else if types.ErrTruncated.Equal(err) {
 		err = types.ErrTruncated.GenWithStackByArgs(colName, rowIdx+1)
+	} else if types.ErrTruncatedWrongVal.Equal(err) && (colTp == mysql.TypeDuration || colTp == mysql.TypeDatetime) {
```
Comment (lzmhhh123) [inline executor/insert_common.go:294]: After I test on MySQL. The column type could also be `TypeDate`.

Comment (ou-bing) [reply executor/insert_common.go]: Already added.

File: executor/insert_common.go [hunk 3]
```diff
@@ -291,10 +291,21 @@ func (e *InsertValues) handleErr(col *table.Column, val *types.Datum, rowIdx int
 		err = types.ErrWarnDataOutOfRange.GenWithStackByArgs(colName, rowIdx+1)
 	} else if types.ErrTruncated.Equal(err) {
 		err = types.ErrTruncated.GenWithStackByArgs(colName, rowIdx+1)
+	} else if types.ErrTruncatedWrongVal.Equal(err) && (colTp == mysql.TypeDuration || colTp == mysql.TypeDatetime || colTp == mysql.TypeDate) {
```
Comment (lzmhhh123) [inline executor/insert_common.go:294]: It seems also `TypeTimestamp` should be here.

Comment (ou-bing) [reply executor/insert_common.go:294]: OK😂

**Review by lzmhhh123 — APPROVED** [review]
