### PR TITLE
privilege/privileges:  refactor the data struct for user privilege data

### LINKED ISSUE #55563: Modify user or privilege will consume a significant amount of time and resources in million users scenario
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create 1 million databases with 2 tables per database.
2. Create 2 users for each schema and grant privileges on the schema to the users.

From the monitoring of TiDB, it can be observed that the QPS for creating users and granting permissions is continuously declining. When the number of users reaches 200,000, the QPS is nearly 1. 
TiDB maintains a full set of user and permission information in memory. When there are changes to users or permissions (triggered by statements such as create/alter user, grant, etc.), TiDB calls the NotifyUpdatePrivilege function which loads the full user and permission information from TiKV to refresh the cache. As the user information increases, this operation will become increasingly time-consuming and resource-intensive. Actual tests show CPU resource consumption at over 80%, and Golang GC causes memory fluctuations exceeding 10GB.

image
image
image

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #55563

Problem Summary:

### What changed and how does it work?

The old data struct is not fit for a lot of users, it use copy-on-write and, when there are 2M users, the cost of copy 2M item for every change is not acceptable.

I have optimize the code to avoid holding all user's privilege data in-memory, and instead maintain just the active users.
However, it does not help the worst case when all users are active.

So this commit is for the worst case:  refactor the data struct using a btree, make the update cost small enough.

The main difference is the `merge` function.
Before this change, we merge two (huge) slices s1, s2:  create a new big slice s3,  copy the data from the old one s1, remove duplicated, and than append the data from s2.

Now it works by s1.Clone(), and updates on this clone by adding the data of s2. 
The underlying btree implement is a lazy clone,  the clone will share the same node with the old btree, and copy-on-write after the modifications.  This way the cost is much smaller.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by CbcWestwolf — APPROVED** [review]
LGTM.
Is there any test to show how much memory btree can save compared with slice's?

File: pkg/privilege/privileges/cache.go [hunk 1]
```diff
@@ -506,78 +572,87 @@ func (p *immutable) loadSomeUsers(ctx sqlexec.RestrictedSQLExecutor, userList ..
...
-		if !slices.ContainsFunc(userList, func(usr string) bool { return usr == v.User }) {
-			ret.user = append(ret.user, v)
-		}
-	}
-	ret.user = append(ret.user, diff.user...)
-	slices.SortFunc(ret.user, compareUserRecord)
-	ret.buildUserMap()
+func (p *MySQLPrivilege) merge(diff *MySQLPrivilege, userList []string) *MySQLPrivilege {
+	ret := newMySQLPrivilege()
+	user := p.user.Clone()
```
Comment (lcwangchao) [inline pkg/privilege/privileges/cache.go:577]: Do we need some mutex for `Clone` ? The BTreeG is documented as:

> // Clone clones the btree, lazily.  Clone should not be called concurrently,
// but the original tree (t) and the new tree (t2) can be used concurrently
// once the Clone call completes.

**Review by lcwangchao — APPROVED** [review]

File: pkg/privilege/privileges/cache.go (hunk 1 above)
Comment (tiancaiamao) [reply pkg/privilege/privileges/cache.go:589]: Done

**Review by lance6716 — COMMENTED** [review]
/approve

for domain part

**Review by GMHDBJD — APPROVED** [review]
LGTM
