### PR TITLE
br/operator: fix adapt env for snapshot backup stuck when encountered error

### LINKED ISSUE #52846: snapshot backup stuck when encountered error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create volumebackupschedule
2. create cluster

### 2. What did you expect to see? (Required)
1. snapshot backup will not stuck when encountered error, it will be set to failed Immediately

### 3. What did you see instead (Required)
1. snapshot backup stuck when encountered error

### 4. What is your TiDB version? (Required)

img_v3_029n_674cd881-a67b-4e05-ba0e-c4645417107g

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

Issue Number: close #52846 

Problem Summary:
When we failed to prepare the connections for wait apply, the channel may never be closed. Hence the pause PD operation (which relies on the finishing of the prepare connections stage) get stuck.

### What changed and how does it work?
Selected over the context so it can be canceled.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > 
  > The change is almost trivial.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

File: br/pkg/backup/prepare_snap/prepare.go [hunk 1]
```diff
@@ -453,6 +454,9 @@ func (p *Preparer) pushWaitApply(reqs pendingRequests, region Region) {
 // PrepareConnections prepares the connections for each store.
 // This will pause the admin commands for each store.
 func (p *Preparer) PrepareConnections(ctx context.Context) error {
+	failpoint.Inject("PrepareConnectionsErr", func() {
+		failpoint.Return(errors.New("meow meow meow"))
```
Comment (BornChanger) [inline br/pkg/backup/prepare_snap/prepare.go:458]:
```suggestion
		failpoint.Return(errors.New("mock PrepareConnectionsErr"))
```

**Review by BornChanger — COMMENTED** [review]
Rest lgtm.

**Review by BornChanger — APPROVED** [review]
