### PR TITLE
lightning: fix auto_increment out-of-range error

### LINKED ISSUE #27937: lighting: local backend import failed if data has largest number as bigint auto_increment column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Prepare test data, with biggest number (9223372036854775807) as bigint  auto_increment column.
[root@idc-4-30 ~]# cat /minio/tools_test_data/PK_AUTO_INCREMENT9096/new_data1.PK_AUTO_INCREMENT9096.000000000.csv
"COL1","COL2","COL4","COL3","COL5"
1,"鐚傆Ē榉牖纜径鉾抍镒获肾É鷓开纻緖扻鏶囮","8431-02-26 15:01:24",5737257244447821569,-1.20365e38
9223372036854775807,"多鵾嚟咕勓鞒轊嵵呮觧栽榨娅猋荪桍舉宰籕僸","0032-10-07 22:42:25",-6700431522805297345,-2.51818e38

[root@idc-4-30 ~]# cat /minio/tools_test_data/PK_AUTO_INCREMENT9096/new_data1.PK_AUTO_INCREMENT9096-schema.sql
/*!40101 SET NAMES binary*/;
CREATE TABLE `PK_AUTO_INCREMENT9096` (
  `COL1` bigint(20) NOT NULL AUTO_INCREMENT,
  `COL2` varchar(20) DEFAULT NULL,
  `COL4` datetime DEFAULT NULL,
  `COL3` bigint(20) DEFAULT NULL,
  `COL5` float DEFAULT NULL,
  PRIMARY KEY (`COL1`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

2, Import the data with local backend
[root@idc-4-30 ~]# tiup tidb-lightning --tidb-host=172.16.4.30 --tidb-port=4000 --check-requirements=false --backend=local --sorted-kv-dir=/home/sorted-kvs -d 's3://nfs/tools_test_data/PK_AUTO_INCREMENT9096/?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9000&force-path-style=true' -config lightning_min.toml -log-file PK_AUTO_INCREMENT9096.log.6
Starting component `tidb-lightning`: /root/.tiup/components/tidb-lightning/v5.2.0/tidb-lightning --tidb-host=172.16.4.30 --tidb-port=4000 --check-requirements=false --backend=local --sorted-kv-dir=/home/sorted-kvs -d s3://nfs/tools_test_data/PK_AUTO_INCREMENT9096/?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9000&force-path-style=true -config lightning_min.toml -log-file PK_AUTO_INCREMENT9096.log.6
Verbose debug logs will be written to PK_AUTO_INCREMENT9096.log.6
...
Error: restore table `new_data1`.`PK_AUTO_INCREMENT9096` failed: ALTER TABLE `new_data1`.`PK_AUTO_INCREMENT9096` AUTO_INCREMENT=-9223372036854775808: alter table auto_increment failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 64 near "-9223372036854775808"
tidb lightning encountered error:  restore table `new_data1`.`PK_AUTO_INCREMENT9096` failed: ALTER TABLE `new_data1`.`PK_AUTO_INCREMENT9096` AUTO_INCREMENT=-9223372036854775808: alter table auto_increment failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 64 near "-9223372036854775808"

### 2. What did you expect to see? (Required)
Import succeed

### 3. What did you see instead (Required)
Import failed with error: ALTER TABLE `new_data1`.`PK_AUTO_INCREMENT9096` AUTO_INCREMENT=-9223372036854775808

Note: import is OK for tidb backend.

### 4. What is your TiDB version? (Required)
TiDB: v5.0.0-nightly-20210908
[root@idc-4-30 ~]# tiup tidb-lightning -V
Starting component `tidb-lightning`: /root/.tiup/components/tidb-lightning/v5.2.0/tidb-lightning -V
Release Version: v5.2.0
Git Commit Hash: 05d2210647d6a1503a8d772477e43b14a024f609
Git Branch: heads/refs/tags/v5.2.0
Go Version: go1.16.4
UTC Build Time: 2021-08-27 05:56:11
Race Enabled: false

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: close #27937

Problem Summary:

### What is changed and how it works?
- Change `AlterAutoIncrement`'s parameter to `uint64` whose maximum is larger than `BIGINT`.
- Throw warning and return immediately while `incr` is larger than `math.MaxInt64` (i.e. maximum of `BIGINT`)

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/restore/tidb.go [hunk 1]
```diff
@@ -373,8 +374,12 @@ func ObtainNewCollationEnabled(ctx context.Context, g glue.SQLExecutor) (bool, e
...
 // the the auto incremanet base in tidb side, we needn't fetch currently auto increment value here.
 // See: https://github.com/pingcap/tidb/blob/64698ef9a3358bfd0fdc323996bb7928a56cadca/ddl/ddl_api.go#L2528-L2533
-func AlterAutoIncrement(ctx context.Context, g glue.SQLExecutor, tableName string, incr int64) error {
-	logger := log.With(zap.String("table", tableName), zap.Int64("auto_increment", incr))
+func AlterAutoIncrement(ctx context.Context, g glue.SQLExecutor, tableName string, incr uint64) error {
+	logger := log.With(zap.String("table", tableName), zap.Uint64("auto_increment", incr))
+	if incr > math.MaxInt64 {
+		logger.Warn("auto_increment out of the maximum value TiDB supports", zap.Uint64("auto_increment", incr))
+		return nil
+	}
```
Comment (gozssky) [inline br/pkg/lightning/restore/tidb.go:382]: Do we need to set `auto_increment` to math.MaxInt64`?

Comment (buchuitoudegou) [reply br/pkg/lightning/restore/tidb.go:382]: MaxInt64 is a legal value in TiDB (i.e. you can insert (9223372036854775807, ....) to a table) whereas MaxInt64+1 is illegal, which will trigger the error, `ERROR 1467 (HY000): Failed to read auto-increment value from storage engine`.

Comment (gozssky) [reply br/pkg/lightning/restore/tidb.go:382]: Does `incr > math.MaxInt64` means lightning has inserted rows whose id is greater than `math.MaxInt64`? Will this cause duplicate entry or data corruption?

Comment (buchuitoudegou) [reply br/pkg/lightning/restore/tidb.go:382]: Mostly yes. But in terms of the case shown in the linked issue, `9223372036854775807` is a valid input, but after inserting it, Lightning would try `alter table xxx auto_increment=9223372036854775807+1`, get syntax error from TiDB, and fail unexpectedly.

So I'm not trying to legalize auto-incr value that exceeds math.MaxInt64 but try to skip this syntax error and let Lightning fail by other clearer issues (such as data corruption, duplicate entry, etc.). As for the case in this issue, because Lightning doesn't try to write entries that are larger than 9223372036854775807, it will succeed.

Failing by duplicate entries might be more intuitive in terms of the effectiveness of reporting the error. Syntax error is helpless...

Comment (gozssky) [reply br/pkg/lightning/restore/tidb.go:382]: Could confirm whether data corruption or any other error can be reported when using local backend and auto_inc is overflow?

Comment (buchuitoudegou) [reply br/pkg/lightning/restore/tidb.go:382]: Yes. If the `auto_incr` column overflows, the checksum will be mismatched.

Comment (gozssky) [reply br/pkg/lightning/restore/tidb.go:382]: "checksum mismatch" is hard for user to know what happened. How about checking overflow during encoding and give a clear error to user?

Comment (buchuitoudegou) [reply br/pkg/lightning/restore/tidb.go:382]: > "checksum mismatch" is hard for user to know what happened. How about checking overflow during encoding and give a clear error to user?

Yes. Actually I'm looking at it #28776. This PR only solves the unexpected syntax error.

**Review by gozssky — APPROVED** [review]

File: br/pkg/lightning/restore/tidb.go [hunk 2]
```diff
@@ -373,8 +374,12 @@ func ObtainNewCollationEnabled(ctx context.Context, g glue.SQLExecutor) (bool, e
 // NOTE: since tidb can make sure the auto id is always be rebase even if the `incr` value is smaller
 // the the auto incremanet base in tidb side, we needn't fetch currently auto increment value here.
 // See: https://github.com/pingcap/tidb/blob/64698ef9a3358bfd0fdc323996bb7928a56cadca/ddl/ddl_api.go#L2528-L2533
-func AlterAutoIncrement(ctx context.Context, g glue.SQLExecutor, tableName string, incr int64) error {
-	logger := log.With(zap.String("table", tableName), zap.Int64("auto_increment", incr))
+func AlterAutoIncrement(ctx context.Context, g glue.SQLExecutor, tableName string, incr uint64) error {
+	logger := log.With(zap.String("table", tableName), zap.Uint64("auto_increment", incr))
+	if incr > math.MaxInt64 {
```
Comment (glorv) [inline br/pkg/lightning/restore/tidb.go:379]: Since `incr > math.MaxInt64` can only happen when there is one row that there is one rwo explitly set the max-value, so here you should alter the auto increment value to the max value then. So the behavior then is the same as import via sql.
Please also add a test case to ensure: Lightning local backend can successfully import data which explicitly set auto_increment row value to the max valid value according to tidb's restriction. After import, any new insert statement without explicitly set the auto_increment row will result with an error.

**Review by glorv — COMMENTED** [review]
BTW, please also fix and add test for auto_random, auto_random should have the same issue as auto_increment.

File: br/pkg/lightning/restore/tidb.go (hunk 2 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/restore/tidb.go:379]: I'll add a IT later. But it seems `alter table xxx auto_increment=math.MaxInt64` will lead to some unexpected errors (I've talked to the guys from sql-infra, it might be bugs of TiDB #34142). So I won't set it until they fix this issue (leave a TODO here).

**Comment by buchuitoudegou** [comment]
@glorv PTAL again

File: br/tests/lightning_max_incr/run.sh [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+    rm -f $TEST_DIR/lightning.log
+    rm -rf $TEST_DIR/sst
+    run_sql 'DROP DATABASE IF EXISTS db;'
+}
+
+cleanup
+
+run_lightning --sorted-kv-dir "$TEST_DIR/sst" --config "tests/$TEST_NAME/config.toml" --log-file "$TEST_DIR/lightning.log"
+check_result
+run_sql 'INSERT INTO db.test(b) VALUES(11) ON DUPLICATE KEY UPDATE b=10000;' # verify incr set to MaxInt64
```
Comment (glorv) [inline br/tests/lightning_max_incr/run.sh:45]: Please add another check that after this insert, any other insert with implicit auto_increment value would fail.
Please also add a comment the explain why this statement can be executed since for tidb backend, this sql should not return successful result.

**Review by glorv — COMMENTED** [review]
rest LGTM

File: br/pkg/lightning/restore/table_restore.go [hunk 4]
```diff
@@ -683,10 +683,17 @@ func (tr *TableRestore) postProcess(
 		tblInfo := tr.tableInfo.Core
 		var err error
 		if tblInfo.PKIsHandle && tblInfo.ContainsAutoRandomBits() {
-			err = AlterAutoRandom(ctx, rc.tidbGlue.GetSQLExecutor(), tr.tableName, tr.alloc.Get(autoid.AutoRandomType).Base()+1)
+			var maxAutoRandom uint64
+			autoRandomBits := tblInfo.AutoRandomBits // range from (0, 15]
+			if !tblInfo.IsAutoRandomBitColUnsigned() {
+				// if auto_random is signed, leave one extra bit
+				autoRandomBits += 1
```
Comment (D3Hunter) [inline br/pkg/lightning/restore/table_restore.go:690]: it's not obvious to change `autoRandomBits`, prefer to use 63 else 64

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

**Review by D3Hunter — APPROVED** [review]

**Comment by buchuitoudegou** [comment]
ptal @glorv

File: br/tests/lightning_max_incr/data/db.test1.000000000.csv [hunk 5]
```diff
@@ -0,0 +1,3 @@
+"a","b"
+1,2
+9223372036854775807,3
```
Comment (glorv) [inline br/tests/lightning_max_incr/data/db.test1.000000000.csv:3]: I think `2^53` should be a good value here to show the max auto value is far more smaller than `2^63-1` as expected.

File: br/tests/lightning_max_incr/run.sh [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+    run_sql 'DROP DATABASE IF EXISTS db;'
+}
+
+cleanup
+
+run_lightning --sorted-kv-dir "$TEST_DIR/sst" --config "tests/$TEST_NAME/config.toml" --log-file "$TEST_DIR/lightning.log"
+check_result
+# local-backend set auto_increment to 9223372036854775807 after importing
+# sql fail because of of duplicate key
+run_sql 'INSERT INTO db.test(b) VALUES(11);' 2>&1 | tee -a "$TEST_DIR/sql_res.$TEST_NAME.txt"
```
Comment (glorv) [inline br/tests/lightning_max_incr/run.sh:47]: please also check the result of `db.test1` here.

**Review by glorv — COMMENTED** [review]
rest LGTM

File: br/tests/lightning_max_incr/data/db.test1.000000000.csv (hunk 5 above)
Comment (buchuitoudegou) [reply br/tests/lightning_max_incr/data/db.test1.000000000.csv:3]: Why is 2^53 better? Though 2^63-1 is larger than the max_auto_random_base, it's still a valid value. Perhaps I could add a check to see if we could go on inserting tuples to test1 to prove auto_random_base is set to correct value so that the table remains available and fulfills constraints.

**Comment by buchuitoudegou** [comment]
Added a check for db.test1, ptal @glorv

File: br/tests/lightning_max_incr/data/db.test1.000000000.csv (hunk 5 above)
Comment (gozssky) [reply br/tests/lightning_max_incr/data/db.test1.000000000.csv:3]: Just a reminder, we should compare the `max_auto_random_base`, but not the final value. e.g. The `max_auto_random_base` of `(2^54)+1` is `1`.

Comment (glorv) [reply br/tests/lightning_max_incr/data/db.test1.000000000.csv:3]: As `2^63-1` it the max value of int64, so it's obvious that any further allocate will cause overflow. But the available allocation range for autorandom is much smaller, so inserting with this value cause panic can't fully prove that the logic is correct. E.g, a implement the same as auto increment will also pass this check. BTW, you should use a different test case to show the difference between auto_increment and auto_random.

Comment (buchuitoudegou) [reply br/tests/lightning_max_incr/data/db.test1.000000000.csv]: Fix in 17b9c33
