### PR TITLE
br: Fix backupmeta division bug

### LINKED ISSUE #37244: br: backupmeta is not divided as expected.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Run `br backup full -u '{IP}:{Port}' -s 'local:///{path}'  --use-backupmeta-v2=true`
Run `du -sh *` in backup dir

### 2. What did you expect to see? (Required)
The `backupmeta` file is divided by 128 MiB.
https://github.com/pingcap/tidb/blob/d1f75f0dd9ac12efad421c4470a7b6b3ce558fc8/br/pkg/metautil/metafile.go#L44

### 3. What did you see instead (Required)
Currently `backupmeta` is divided according to SST file size `Size_`.
https://github.com/pingcap/tidb/blob/41b9e26d1ef468e079937e1e2aab33d411f28841/br/pkg/metautil/metafile.go#L442

```
4.0K    backup.lock
4.0K    backupmeta
16K     backupmeta.datafile.000000001
4.0K    backupmeta.datafile.000000002
4.0K    backupmeta.datafile.000000003
4.0K    backupmeta.datafile.000000004
4.0K    backupmeta.datafile.000000005
4.0K    backupmeta.datafile.000000006
4.0K    backupmeta.datafile.000000007
4.0K    backupmeta.datafile.000000008
8.0K    backupmeta.datafile.000000009
4.0K    backupmeta.datafile.000000010
4.0K    backupmeta.datafile.000000011
4.0K    backupmeta.datafile.000000012
4.0K    backupmeta.datafile.000000013
4.0K    backupmeta.datafile.000000014
4.0K    backupmeta.datafile.000000015
4.0K    backupmeta.datafile.000000016
4.0K    backupmeta.datafile.000000017
8.0K    backupmeta.datafile.000000018
4.0K    backupmeta.datafile.000000019
4.0K    backupmeta.datafile.000000020
4.0K    backupmeta.datafile.000000021
4.0K    backupmeta.datafile.000000022
4.0K    backupmeta.datafile.000000023
4.0K    backupmeta.datafile.000000024
4.0K    backupmeta.datafile.000000025
4.0K    backupmeta.datafile.000000026
4.0K    backupmeta.datafile.000000027
4.0K    backupmeta.datafile.000000028
4.0K    backupmeta.datafile.000000029
4.0K    backupmeta.datafile.000000030
4.0K    backupmeta.datafile.000000031
4.0K    backupmeta.datafile.000000032
200K    backupmeta.schema.000000033
```

### 4. What is your TiDB version? (Required)

nightly

### PR DESCRIPTION
**Pull request by MoCuishle28**
Signed-off-by: zhanggaoming <gaoming.zhang@pingcap.com>

### What problem does this PR solve?

Issue Number: close #37244

Problem Summary:
`backupmeta` is not divided as expected.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Manual Test
For testing, I modified `MetaFileSize` to 20 units.KiB. (i.e., Flush is executed when backupmeta is larger than 20 KiB.)
But in the committed code, `MetaFileSize` is still 128 * units.MiB.
https://github.com/pingcap/tidb/blob/d1f75f0dd9ac12efad421c4470a7b6b3ce558fc8/br/pkg/metautil/metafile.go#L44

Run `br backup full -u '{IP}:{Port}' -s '{path}' --use-backupmeta-v2=true`
```
Detail BR log in /tmp/br.log.2022-08-22T15.44.54+0800 
Full Backup <--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> 100.00%
Checksum <-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> 100.00%
[2022/08/22 15:45:42.462 +08:00] [INFO] [collector.go:69] ["Full Backup success summary"] [total-ranges=264] [ranges-succeed=264] [ranges-failed=0] [backup-checksum=11.125195947s] [backup-fast-checksum=53.509755ms] [backup-total-ranges=89] [backup-total-regions=244] [total-take=48.402973686s] [BackupTS=435461631597346817] [total-kv=108954045] [total-kv-size=12.51GB] [average-speed=258.5MB/s] [backup-data-size(after-compressed)=4.843GB] [Size=4843046770]
```

Run `du -sh *` in backup dir
```
4.0K    backup.lock
4.0K    backupmeta
24K     backupmeta.datafile.000000001
24K     backupmeta.datafile.000000002
24K     backupmeta.datafile.000000003
4.0K    backupmeta.datafile.000000004
24K     backupmeta.schema.000000005
24K     backupmeta.schema.000000006
24K     backupmeta.schema.000000007
24K     backupmeta.schema.000000008
24K     backupmeta.schema.000000009
24K     backupmeta.schema.000000010
24K     backupmeta.schema.000000011
24K     backupmeta.schema.000000012
28K     backupmeta.schema.000000013
8.0K    backupmeta.schema.000000014
```

drop database

Run `br restore full -u '{IP}:{Port}' -s '{path}'`
```
Detail BR log in /tmp/br.log.2022-08-22T15.59.49+0800 
Full Restore <-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> 100.00%
[2022/08/22 16:00:39.523 +08:00] [INFO] [collector.go:69] ["Full Restore success summary"] [total-ranges=256] [ranges-succeed=256] [ranges-failed=0] [split-region=227.871055ms] [restore-ranges=176] [total-take=50.097892323s] [total-kv=108910298] [total-kv-size=12.51GB] [average-speed=249.6MB/s] [restore-data-size(after-compressed)=4.842GB] [Size=4842191785] [BackupTS=435461866045833217]
```

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/metautil/metafile.go [hunk 1]
```diff
@@ -427,19 +427,22 @@ func (op AppendOp) name() string {
...
-func (op AppendOp) appendFile(a *backuppb.MetaFile, b interface{}) (size int, itemCount int) {
+func (op AppendOp) appendFile(a *backuppb.MetaFile, b interface{}) (sstFilesSize int, size int, itemCount int) {
 	switch op {
 	case AppendMetaFile:
-		a.MetaFiles = append(a.MetaFiles, b.(*backuppb.File))
-		size += int(b.(*backuppb.File).Size_)
+		metaFile := b.(*backuppb.File)
+		a.MetaFiles = append(a.MetaFiles, metaFile)
+		size += metaFile.Size()
+		sstFilesSize += int(metaFile.Size_)
```
Comment (WangLe1321) [inline br/pkg/metautil/metafile.go:436]: metaFile is not belong to sst file.

File: br/pkg/metautil/metafile.go [hunk 2]
```diff
@@ -427,19 +427,22 @@ func (op AppendOp) name() string {
...
 		itemCount++
 	case AppendDataFile:
 		// receive a batch of file because we need write and default sst are adjacent.
 		files := b.([]*backuppb.File)
 		a.DataFiles = append(a.DataFiles, files...)
 		for _, f := range files {
 			itemCount++
-			size += int(f.Size_)
+			size += f.Size()
+			sstFilesSize += int(f.Size_)
```
Comment (WangLe1321) [inline br/pkg/metautil/metafile.go:445]: Maybe `sstFilesSize` calls `dataFileSize` better? Because the op name is `AppendDataFile`

File: br/pkg/metautil/metafile.go [hunk 3]
```diff
@@ -715,7 +720,7 @@ func (writer *MetaWriter) flushMetasV2(ctx context.Context, op AppendOp) error {
 	}
 
 	name := op.name()
-	writer.metafileSizes[name] += writer.metafiles.size
+	writer.metafileSizes[name] += writer.metafiles.sstFilesSize
```
Comment (WangLe1321) [inline br/pkg/metautil/metafile.go:723]: I think you can add a `dataFileSize` to `writer`, `writer.metafileSizes` should store the size of meta files.

File: br/pkg/metautil/metafile.go (hunk 2 above)
Comment (MoCuishle28) [reply br/pkg/metautil/metafile.go]: Done.

File: br/pkg/metautil/metafile.go (hunk 3 above)
Comment (MoCuishle28) [reply br/pkg/metautil/metafile.go]: Done.

**Review by WangLe1321 — APPROVED** [review]

**Review by joccau — APPROVED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]

**Comment by 3pointer** [comment]
merge
