### PR TITLE
*: make 'tidb_enable_change_column_type' available as a session variable

### LINKED ISSUE #20234: change tidb_enable_change_column_type to include global | session scope
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> create table test.tb(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> alter table test.tb modify column a smallint;
ERROR 8200 (HY000): Unsupported modify column: length 6 is less than origin 11, and tidb_enable_change_column_type is false
mysql> set @@global.tidb_enable_change_column_type=1;
Query OK, 0 rows affected (0.00 sec)

mysql> alter table test.tb modify column a smallint;
ERROR 8200 (HY000): Unsupported modify column: length 6 is less than origin 11, and tidb_enable_change_column_type is false
mysql> exit
```
after reconnect to TiDB
```
mysql> alter table test.tb modify column a smallint;
Query OK, 0 rows affected (0.02 sec)
```

### 2. What did you expect to see? (Required)
tidb_enable_change_column_type effects for the current connection
### 4. What is your TiDB version? (Required)

```
mocktikv

Release Version: v4.0.0-beta.2-1288-g10fd83446-dirty
Edition: Community
Git Commit Hash: 10fd834463ea6f44b187993e2ea189e3d5c72097
Git Branch: master
UTC Build Time: 2020-09-24 14:04:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by cncal**
### What problem does this PR solve?

Issue Number: close #20234 

### What is changed and how it works?

Make `tidb_enable_change_column_type` available as a session variable.

### Check List 

Tests 

- Manual test

```sql
mysql> create table test.tb(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> alter table test.tb modify column a smallint;
ERROR 8200 (HY000): Unsupported modify column: length 6 is less than origin 11, and tidb_enable_change_column_type is false

mysql> set @@session.tidb_enable_change_column_type=1;
Query OK, 0 rows affected (0.00 sec)

mysql> alter table test.tb modify column a smallint;
Query OK, 0 rows affected (0.00 sec)
```

### Release note 

- No release note

### CODE REVIEW

**Comment by bb7133** [comment]
Hi @cncal , thanks for contributing. Please add a unit test for your code, thanks again!

**Comment by bb7133** [comment]
PTAL @AilinKid

**Comment by AilinKid** [comment]
thanks for your contribution, you can also add some test for this.

**Review by AilinKid — COMMENTED** [review]
thanks for your contribution, you could also add some tests for this.

**Comment by cncal** [comment]
Unit tests added.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by bb7133 — DISMISSED** [review]
LGTM

**Comment by morgo** [comment]
@cncal please fix conflicts. Thanks!

**Comment by cncal** [comment]
Conflicts resolved.

File: sessionctx/variable/sysvar.go [hunk 1]
```diff
@@ -664,6 +664,7 @@ var defaultSysVars = []*SysVar{
 	{Scope: ScopeGlobal, Name: TiDBEnableChangeMultiSchema, Value: BoolToOnOff(DefTiDBChangeMultiSchema), Type: TypeBool},
 	{Scope: ScopeGlobal, Name: TiDBEnablePointGetCache, Value: BoolToOnOff(DefTiDBPointGetCache), Type: TypeBool},
 	{Scope: ScopeGlobal, Name: TiDBEnableAlterPlacement, Value: BoolToOnOff(DefTiDBEnableAlterPlacement), Type: TypeBool},
+	{Scope: ScopeGlobal | ScopeSession, Name: TiDBEnableChangeColumnType, Value: BoolToOnOff(DefTiDBChangeColumnType), Type: TypeBool},
```
Comment (morgo) [inline sessionctx/variable/sysvar.go:667]: Please edit the existing line for `TiDBEnableChangeColumnType` (it is on line 663). This is currently adding a new line, which may confuse someone in the future :-)

Comment (cncal) [reply sessionctx/variable/sysvar.go]: Replicated sysVar removed.

**Comment by morgo** [comment]
LGTM

**Review by tangenta — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
