### PR TITLE
session: fix upgraded cluster mysql.user columns order is different from new cluster

### LINKED ISSUE #33650: upgraded cluster `mysql.user` columns order is different from the new cluster
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a v6.0.0  cluster show create table user
2. deploy a v4.0.16 cluster and upgrade to v6.0.0 show create table mysql.user

https://github.com/pingcap/tidb/blob/fa834a08063f857c77a8bba2362815702c9fd3a8/session/bootstrap.go#L88-L94

https://github.com/pingcap/tidb/blob/fa834a08063f857c77a8bba2362815702c9fd3a8/session/bootstrap.go#L1592-L1599

### 2. What did you expect to see? (Required)
the `mysql.user` table columns order is same
### 3. What did you see instead (Required)
the `mysql.user` table columns order is different
### 4. What is your TiDB version? (Required)
v6.0.0

### PR DESCRIPTION
**Pull request by littlelittlehorse**
### What problem does this PR solve?

Issue Number: close #33650

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
1. If the version is smaller than `version64`, upgrade to `version88`, column order become right.
2. If the version is greater than `version64`, upgrade to `version88`, column order become right.
````
- [ ] No code

None Side effects

None Documentation

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that upgraded cluster mysql.user columns order is different from new cluster.
```

### CODE REVIEW

File: session/bootstrap.go [hunk 1]
```diff
@@ -1593,7 +1593,7 @@ func upgradeToVer64(s Session, ver int64) {
 	if ver >= version64 {
 		return
 	}
-	doReentrantDDL(s, "ALTER TABLE mysql.user ADD COLUMN `Repl_slave_priv` ENUM('N','Y') CHARACTER SET utf8 NOT NULL DEFAULT 'N' AFTER `Execute_priv`", infoschema.ErrColumnExists)
+	doReentrantDDL(s, "ALTER TABLE mysql.user ADD COLUMN `Repl_slave_priv` ENUM('N','Y') CHARACTER SET utf8 NOT NULL DEFAULT 'N' AFTER `Create_Tablespace_Priv`", infoschema.ErrColumnExists)
```
Comment (morgo) [inline session/bootstrap.go:1596]: This will only fix installs for those who have not run bootstrap version 64 yet. Can you introduce a new bootstrap version to detect if this historical corruption exists and fix it?

File: session/bootstrap.go [hunk 2]
```diff
@@ -1790,6 +1792,13 @@ func upgradeToVer87(s Session, ver int64) {
 	doReentrantDDL(s, CreateAnalyzeJobs)
 }
 
+func upgradeToVer88(s Session, ver int64) {
+	if ver >= version88 {
+		return
+	}
+	doReentrantDDL(s, "ALTER TABLE `mysql.user` CHANGE `Repl_slave_priv` `Repl_slave_priv` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `Create_Tablespace_Priv`")
+}
+
```
Comment (morgo) [inline session/bootstrap.go:1801]: Getting an error in CI:
```
[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check/detail/tidb_ghpr_check/59947/pipeline#step-122-log-355)[2022-04-18T11:57:54.822Z] session/bootstrap.go:1795:6: `upgradeToVer88` is unused (deadcode)
[2022-04-18T11:57:54.822Z] func upgradeToVer88(s Session, ver int64) {
```

As well as incrementing the currentBootstrapVersion, you'll need to add this to the list of bootstrap tasks.

**Review by morgo — COMMENTED** [review]
Looking good now, but we might have trouble cherry picking this to release branches because they will not be able to upgrade to bootstrap ver 88 safely. In the past we have done this by combining bootstrap versions for earlier versions so they can execute the next number in sequence with this + the intended change for that version.

File: session/bootstrap.go (hunk 2 above)
Comment (littlelittlehorse) [reply session/bootstrap.go]: done.

Comment (littlelittlehorse) [reply session/bootstrap.go]: done.

File: session/bootstrap.go [hunk 3]
```diff
@@ -1593,7 +1596,7 @@ func upgradeToVer64(s Session, ver int64) {
 	if ver >= version64 {
 		return
 	}
-	doReentrantDDL(s, "ALTER TABLE mysql.user ADD COLUMN `Repl_slave_priv` ENUM('N','Y') CHARACTER SET utf8 NOT NULL DEFAULT 'N' AFTER `Execute_priv`", infoschema.ErrColumnExists)
+	doReentrantDDL(s, "ALTER TABLE mysql.user ADD COLUMN `Repl_slave_priv` ENUM('N','Y') CHARACTER SET utf8 NOT NULL DEFAULT 'N' AFTER `Create_Tablespace_Priv`", infoschema.ErrColumnExists)
```
Comment (Defined2014) [inline session/bootstrap.go:1599]: I think it's better to follow MySQL. Like
```mysql
show create table mysql.user;
...
  `Super_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Create_tmp_table_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Lock_tables_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Execute_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Repl_slave_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Repl_client_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Create_view_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Show_view_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `Create_routine_priv` enum('N','Y') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
...
```

We can change the create stmt. https://github.com/pingcap/tidb/blob/master/session/bootstrap.go#L92

Comment (littlelittlehorse) [reply session/bootstrap.go:1599]: I think this a good idea, but the will make now new cluster mysql.user columns orders which is different with previous cluster columns orders, does that cause problem?

Comment (Defined2014) [reply session/bootstrap.go:1599]: I don't think it will be a big problem. But don't forget change `insert` stmt in `doDMLWorks`.

Comment (littlelittlehorse) [reply session/bootstrap.go]: done, I hope you can check the latest changes,  thank you.

Comment (Defined2014) [reply session/bootstrap.go]: Also need an `upgradeToVerXX` to change the user table which create by old version like 87.

Comment (littlelittlehorse) [reply session/bootstrap.go]: done.

Comment (Defined2014) [reply session/bootstrap.go]: Please also update `doDMLWorks` func to fix the UT

**Review by Defined2014 — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM
