### PR TITLE
planner, executor: support batchget for range and list partition table

### LINKED ISSUE #24476: dynamic partition pruning mode cannot use PointGet and BatchGet
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create database test_batchget_pointget;

use test_batchget_pointget;

set @@tidb_partition_prune_mode = 'dynamic';

create table trange(a int, unique key(a)) partition by range(a) (
		partition p0 values less than (30),
		partition p1 values less than (60),
		partition p2 values less than (90),
		partition p3 values less than (120));


explain select a from trange where a=10;
```

### 2. What did you expect to see? (Required)

Use PointGet.

### 3. What did you see instead (Required)

Use IndexReader

### 4. What is your TiDB version? (Required)

Release Version: v4.0.0-beta.2-2792-g337beb1f8-dirty

### PR DESCRIPTION
**Pull request by zhuo-zhi**
### What problem does this PR solve?

Issue Number: close #24476, subitem of #24150 

Problem Summary:

- Support batchget for range and list partition table.

### What is changed and how it works?

What's Changed:

- Change BatchGet logic in the func TryFastPlan. Change executor logic for BatchGet accordingly.

How it Works:

- Allow partition table other than hash partition to support BatchGet. Locate partition column in the func TryFastPlan, and locate partition table ID in the func Next in the executor accordingly.

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- planner, executor: support batchget for range and list partition table

### CODE REVIEW

File: executor/batch_point_get.go [hunk 1]
```diff
@@ -449,13 +463,41 @@ func (getter *PessimisticLockCacheGetter) Get(_ context.Context, key kv.Key) ([]
...
-	partIdx := math.Abs(intVal % int64(pi.Num))
-	return pi.Definitions[partIdx].ID
+
+	switch pi.Type {
+	case model.PartitionTypeHash:
+		partIdx := math.Abs(intVal % int64(pi.Num))
+		return pi.Definitions[partIdx].ID, nil
+	case model.PartitionTypeRange:
+		// we've check the type assertions in func TryFastPlan
+		col := partitionExpr.Expr.(*expression.Column)
```
Comment (qw4990) [inline executor/batch_point_get.go:482]: For safety, please check the type again here in case of returning the wrong results.

File: planner/core/point_get_plan.go [hunk 2]
```diff
@@ -1556,7 +1568,57 @@ func findPartitionIdx(idxInfo *model.IndexInfo, pos int, pairs []nameValuePair)
...
+	case model.PartitionTypeHash:
+		if col, ok := partitionExpr.OrigExpr.(*ast.ColumnNameExpr); ok {
+			partitionName = col.Name.Name
+		} else {
+			return 0, errors.Errorf("unsupported partition type in BatchGet")
+		}
+	case model.PartitionTypeRange:
+		// left range columns partition for future development
+		if len(pi.Columns) == 0 {
+			if col, ok := partitionExpr.Expr.(*expression.Column); ok {
```
Comment (qw4990) [inline planner/core/point_get_plan.go:1592]: Can we get the column name from `partitionExpr.OrigExpr` like what we do under `TypeHash`?

File: planner/core/point_get_plan.go [hunk 3]
```diff
@@ -1556,7 +1568,57 @@ func findPartitionIdx(idxInfo *model.IndexInfo, pos int, pairs []nameValuePair)
...
+				partitionName = colInfo.Name
+			}
+		} else {
+			return 0, errors.Errorf("unsupported partition type in BatchGet")
+		}
+	case model.PartitionTypeList:
+		// left list columns partition for future development
+		if partitionExpr.ForListPruning.ColPrunes == nil {
+			locateExpr := partitionExpr.ForListPruning.LocateExpr
+			if locateExpr, ok := locateExpr.(*expression.Column); ok {
```
Comment (qw4990) [inline planner/core/point_get_plan.go:1603]: ditto

File: executor/partition_table_test.go [hunk 4]
```diff
@@ -683,6 +683,79 @@ func (s *partitionTableSuite) TestDynamicPruningUnderIndexJoin(c *C) {
...
+		partition p0 values in (1, 2, 3, 4),
+			partition p1 values in (5, 6, 7, 8),
+			partition p2 values in (9, 10, 11, 12));`)
+
+	// range partition table
+	tk.MustExec(`create table trange(a int, unique key(a)) partition by range(a) (
+		partition p0 values less than (30),
+		partition p1 values less than (60),
+		partition p2 values less than (90),
+		partition p3 values less than (120));`)
```
Comment (qw4990) [inline executor/partition_table_test.go:707]: Please add more cases with unsigned/varchar/datetime/decimal types~

**Comment by qw4990** [comment]
Almost LGTM, please address my small comments at your convenience @zhuo-zhi

File: planner/core/point_get_plan.go (hunk 2 above)
Comment (zhuo-zhi) [reply planner/core/point_get_plan.go:1592]: No. We don't assign `OrigExpr` when generating range partition table. see [code](https://github.com/pingcap/tidb/blob/master/table/tables/partition.go#L473)

File: planner/core/point_get_plan.go (hunk 3 above)
Comment (zhuo-zhi) [reply planner/core/point_get_plan.go:1603]: No. Different types of  partition table are initialized with different `partitionExpr`. See the referenced code in the comment above.

File: executor/partition_table_test.go (hunk 4 above)
Comment (zhuo-zhi) [reply executor/partition_table_test.go:707]: It seems that range and list partition can only support `INT` typed partition key. How about we only add tests about unsigned?

Comment (zhuo-zhi) [reply executor/partition_table_test.go:707]: unsigned type case is updated in the new commit.

Comment (zhuo-zhi) [reply executor/partition_table_test.go:707]: `partition by range columns(...)` can support other types, but `partition by range columns(...)` doesn't support `BatchGet`.

Comment (qw4990) [reply executor/partition_table_test.go:707]: Oh, my fault.

**Review by qw4990 — APPROVED** [review]

**Review by mjonss — COMMENTED** [review]
Some minor questions/suggestions

File: executor/batch_point_get.go [hunk 5]
```diff
@@ -210,7 +214,11 @@ func (e *BatchPointGetExec) initialize(ctx context.Context) error {
 				continue
 			}
 
-			physID := getPhysID(e.tblInfo, idxVals[e.partPos].GetInt64())
+			physID, err := getPhysID(e.tblInfo, e.partExpr, idxVals[e.partPos].GetInt64())
+			if err != nil {
+				continue
```
[the remark this answers is not in the document]
Comment (zhuo-zhi) [reply executor/batch_point_get.go:219]: As for `BathGet`, if one data point in the where clause `where col in (....)` doesn't match any partition, we can just safely ignore it, and continue trying to fetch the next data point.

TableDual is not applicable here because we have already build out executor in `buildBatchPointGet` instead of `buildTableDual`.

File: executor/batch_point_get.go [hunk 6]
```diff
@@ -449,13 +463,41 @@ func (getter *PessimisticLockCacheGetter) Get(_ context.Context, key kv.Key) ([]
...
+	case model.PartitionTypeHash:
+		partIdx := math.Abs(intVal % int64(pi.Num))
+		return pi.Definitions[partIdx].ID, nil
+	case model.PartitionTypeRange:
+		// we've check the type assertions in func TryFastPlan
+		col := partitionExpr.Expr.(*expression.Column)
+		unsigned := mysql.HasUnsignedFlag(col.GetType().Flag)
+		ranges := partitionExpr.ForRangePruning
+		length := len(ranges.LessThan)
+		partIdx := sort.Search(length, func(i int) bool {
```
[the remark this answers is not in the document]
Comment (zhuo-zhi) [reply executor/batch_point_get.go:489]: Yes, now it's more like an ad hoc solution. Maybe we can refactor our code after `partition by range columns(...)` and `partition by list columns(...)` GA.

File: planner/core/point_get_plan.go [hunk 7]
```diff
@@ -1556,7 +1568,57 @@ func findPartitionIdx(idxInfo *model.IndexInfo, pos int, pairs []nameValuePair)
...
+			return 0, errors.Errorf("unsupported partition type in BatchGet")
+		}
+	}
+
+	for i, idxCol := range idx.Columns {
+		if partitionName.L == idxCol.Name.L {
+			return i, nil
+		}
+	}
+	panic("unique index must include all partition columns")
```
[the remark this answers is not in the document]
Comment (zhuo-zhi) [reply planner/core/point_get_plan.go:1617]: Ok. It's updated in the new commit.

**Review by rebelice — APPROVED** [review]
/lgtm
