### PR TITLE
type: make decimal default precision visible in `show create table`

### LINKED ISSUE #7665: decimal type in `show create table` is not same as MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.  
      
          create table decimalschema(x decimal(15));
          show create table decimalschema;

2. What did you expect to see?
  
        +---------------+-------------------------------------------------------------------------------- 
       ----------------------------------------------+
        | Table         | Create Table                                                                                                                 |
        +---------------+-------------------------------------------------------------------------------- 
       ----------------------------------------------+
        | decimalschema | CREATE TABLE `decimalschema` (
          `x` decimal(15,0) DEFAULT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
        +---------------+-------------------------------------------------------------------------------- 
       ----------------------------------------------+
        1 row in set (0.00 sec)

3. What did you see instead?
  
        +---------------+-------------------------------------------------------------------------------- 
       ----------------------------------------------+
        | Table         | Create Table                                                                                                                 |
        +---------------+-------------------------------------------------------------------------------- 
       ----------------------------------------------+
        | decimalschema | CREATE TABLE `decimalschema` (
          `x` decimal(15) DEFAULT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
        +---------------+-------------------------------------------------------------------------------- 
       ----------------------------------------------+
        1 row in set (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.0

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
Fix #7665 to make jdbc test happy.

### What is changed and how it works?
Add code to make default decimal precision visible in `show create table`.
See #7665 for detail.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

### CODE REVIEW

File: types/field_type.go [hunk 1]
```diff
@@ -231,8 +231,12 @@ func (ft *FieldType) CompactStr() string {
 			suffix = fmt.Sprintf("(%d", displayFlen)
 			if isDecimalNotDefault {
 				suffix += fmt.Sprintf(",%d", displayDecimal)
+			} else {
+				suffix += fmt.Sprintf(",%d", 0)
 			}
 			suffix += ")"
+		} else {
+			suffix = "(10,0)"
```
Comment (lysu) [inline types/field_type.go]: the default fsp for tidb seem be not `10` which is different to mysql

https://github.com/lysu/tidb/commit/ea29a1c30dc89aa1874a9bcd1e796412cf6c7253#diff-af881ce5457dfb227fd7fb66090a339cR32

**Comment by imtbkcat** [comment]
PTAL @lysu

File: types/field_type.go [hunk 2]
```diff
@@ -231,8 +231,12 @@ func (ft *FieldType) CompactStr() string {
 			suffix = fmt.Sprintf("(%d", displayFlen)
 			if isDecimalNotDefault {
 				suffix += fmt.Sprintf(",%d", displayDecimal)
+			} else {
+				suffix += fmt.Sprintf(",%d", 0)
 			}
 			suffix += ")"
+		} else {
+			suffix = fmt.Sprintf("(%d,0)", defaultFlen)
 		}
```
Comment (jackysp) [inline types/field_type.go]: how about
```
if isFlenNotDefault {
} else {
}
if isDecimalNotDefault {
} else {
}

File: types/field_type.go [hunk 3]
```diff
@@ -231,8 +231,12 @@ func (ft *FieldType) CompactStr() string {
 			suffix = fmt.Sprintf("(%d", displayFlen)
 			if isDecimalNotDefault {
 				suffix += fmt.Sprintf(",%d", displayDecimal)
+			} else {
+				suffix += fmt.Sprintf(",%d", 0)
 			}
 			suffix += ")"
+		} else {
+			suffix = fmt.Sprintf("(%d,0)", defaultFlen)
```
Comment (coocood) [inline types/field_type.go]: It would be simpler if calculate the `displayFlen` and `displayDecimal` first, then just Sprintf once.
```go
suffix = fmt.Sprintf("(%d,%d)", displayFlen, displayDecimal)
```

File: types/field_type.go [hunk 4]
```diff
@@ -231,8 +231,12 @@ func (ft *FieldType) CompactStr() string {
 			suffix = fmt.Sprintf("(%d", displayFlen)
 			if isDecimalNotDefault {
```
Comment (zz-jason) [inline types/field_type.go]: how about:
```go
if isFlenNotDefault {
	prefix = xxx
	break
}
if isDecimalNotDefault {
	prefix = xxx
	break
}
prefix = xx
```

File: types/field_type.go (hunk 3 above)
Comment (winkyao) [reply types/field_type.go]: When the type is mysql.TypeNewDecimal, why still need to check isFlenNotDefault or isDecimalNotDefault? What about just using `suffix = fmt.Sprintf("(%d,%d)", displayFlen, displayDecimal)` ?

Comment (jackysp) [reply types/field_type.go]: @winkyao , have you checked it with MySQL?

Comment (imtbkcat) [reply types/field_type.go]: I think just use `suffix = fmt.Sprintf("(%d,%d)", displayFlen, displayDecimal)` is okay.

**Comment by imtbkcat** [comment]
PTAL @zz-jason @jackysp @coocood
