### PR TITLE
executor: reset groupChecker for StreamAggExec when Close

### LINKED ISSUE #10608: GROUP_CONCAT error. subquery returns more than 1 row
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

`
SELECT
	(
	SELECT
		GROUP_CONCAT( CONCAT( 123, '-' ) )
	FROM
		user_info ui
	WHERE
		 ui.id = read_cust_user_id
	GROUP BY
		 ui.id
	 ) AS levelCode 
FROM
	ods_order_item_base_two 
`
 Error information is ：
> 1105 - subquery returns more than 1 row
Remarks：
read_cust_user_id is ods_order_item_base_two  table field。
2. What did you expect to see?

 Give an explanation. 

3. What did you see instead?
`GROUP BY ui.id  `
Change to
`GROUP BY read_cust_user_id`
 Successful implementation 
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.1
Git Commit Hash: 990f859384b834fe5edf1410d2a4142def5c3fa9
Git Branch: release-2.1
UTC Build Time: 2018-12-12 10:57:44
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
Fix #10608 

### What is changed and how it works?
Reset StreamAggExec.groupChecker when Close.

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects
N/A

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: executor/aggregate_test.go [hunk 1]
```diff
@@ -710,3 +710,14 @@ func (s *testSuite1) TestIssue10098(c *C) {
 	tk.MustExec("insert into t values('1', '222'), ('12', '22')")
 	tk.MustQuery("select group_concat(distinct a, b) from t").Check(testkit.Rows("1222,1222"))
 }
+
+func (s *testSuite1) TestIssue10608(c *C) {
+	tk := testkit.NewTestKitWithInit(c, s.store)
+	tk.MustExec(`drop table if exists t, s;`)
+	tk.MustExec("create table t(a int)")
```
Comment (cosven) [inline executor/aggregate_test.go]: this test case currently does not cover the bug since it can't reproduce the bug.

we should modify this line to `create table t(a int primary key);`

Comment (XuHuaiyu) [reply executor/aggregate_test.go]: What do you mean by ` it can't reproduce the bug`?

Comment (cosven) [reply executor/aggregate_test.go]: **I expect**
this test case should fail in previous commits(version), such as `3.0.0-beta`
it should return error `1105 - subquery returns more than 1 row`

**what I see instead**
it passed.

-----------------

> What do you mean by it can't reproduce the bug?

this test case can't prove this PR fix the bug described in issues 10608, because this test case will always pass.
