### PR TITLE
planner: fix sql with static partition pruning mode got nil pointer error

### LINKED ISSUE #62331: explain sql with static partition pruning mode got nil pointer error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> CREATE TABLE `tl431e2968` (
    ->   `col_1` time DEFAULT NULL,
    ->   `col_2` mediumint NOT NULL DEFAULT '-7351173',
    ->   KEY `idx_1` (`col_2`,`col_1`) /*T![global_index] GLOBAL */,
    ->   KEY `idx_2` (`col_2`,`col_1`),
    ->   PRIMARY KEY (`col_2`) /*T![clustered_index] NONCLUSTERED */,
    ->   UNIQUE KEY `idx_4` (`col_2`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    -> PARTITION BY RANGE COLUMNS(`col_2`)
    -> (PARTITION `p0` VALUES LESS THAN (7429676));
Query OK, 0 rows affected (0.016 sec)

mysql>  set @@tidb_partition_prune_mode="static" ;
Query OK, 0 rows affected, 1 warning (0.001 sec)

mysql> explain  select /*+ read_from_storage(tiflash[ tl431e2968 ]) */ /*+ use_index( tl431e2968 ) */ /*+ agg_to_cop() hash_agg() */  bit_and( tl431e2968.col_2 ) as r0 , bit_xor( tl431e2968.col_2 ) as r1 , substring( tl431e2968.col_2 , 4 ) as r2 from tl431e2968 where tl431e2968.col_1 in ( '04:00:09.00' ,'21:06:18.00' ,'18:43:53.00' ) group by tl431e2968.col_1,tl431e2968.col_2  having not( tl431e2968.col_1 <> '06:32:23.00' );
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference

```

### 2. What did you expect to see? (Required)
success

### 3. What did you see instead (Required)
nil pointer error

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by King-Dylan**
### What problem does this PR solve?

Issue Number: close #62331 

Problem Summary:
Since PR [#61571](https://github.com/pingcap/tidb/pull/61571), `applyPredicateSimplification` invokes `PropagateConstant`. Then`ds.AllConds` and `ds.PushedDownConds` may not kept in sync after `rule.PartitionProcessor`, it will cause a nil pointer panic.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/casetest/physicalplantest/physical_plan_test.go [hunk 1]
```diff
@@ -1594,6 +1594,33 @@ func TestRuleAggElimination4Join(t *testing.T) {
 		}
 	})
 }
+func TestIssue62331(t *testing.T) {
```
Comment (hawkingrei) [inline pkg/planner/core/casetest/physicalplantest/physical_plan_test.go:1598]: add a empty line here

Comment (hawkingrei) [reply pkg/planner/core/casetest/physicalplantest/physical_plan_test.go:1598]: and run the ```make bazel_prepare```.

**Review by AilinKid — APPROVED** [review]
