### PR TITLE
ddl: Also check column types in ALTER TABLE t PARTITION BY ...

### LINKED ISSUE #56094: restrictions on partitioning in `CREATE TABLE` can be bypass with `ALTER TABLE`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a varchar(20), b int) partition by hash(a) partitions 2; -- fail
create table t(a varchar(20), b int);
alter table t partition by hash(a) partitions 2; -- success
```

### 2. What did you expect to see? (Required)

Both succeed or both fail.

### 3. What did you see instead (Required)

```
> create table t(a varchar(20), b int) partition by hash(a) partitions 2;
ERROR 1659 (HY000): Field 'a' is of a not allowed type for this type of partitioning
> create table t(a varchar(20), b int);
Query OK, 0 rows affected (0.045 sec)

> alter table t partition by hash(a) partitions 2;
Query OK, 0 rows affected, 1 warning (1.080 sec)

> show create table t;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                   |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` varchar(20) DEFAULT NULL,
  `b` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY HASH (`a`) PARTITIONS 2 |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)

```

### 4. What is your TiDB version? (Required)

nightly

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #56094

Problem Summary:
There were no checks for partitioning expression type if ALTER TABLE t PARTITION BY ..., like it was for CREATE TABLE t ... PARTITION BY ...

### What changed and how does it work?
Added check.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/partition.go [hunk 1]
```diff
@@ -1833,6 +1833,26 @@ func checkPartitionFuncType(ctx sessionctx.Context, expr ast.ExprNode, schema st
 	return errors.Trace(dbterror.ErrPartitionFuncNotAllowed.GenWithStackByArgs("PARTITION"))
 }
 
+func checkPartitionFuncTypeExprString(ctx sessionctx.Context, expr, schema string, tblInfo *model.TableInfo) error {
```
Comment (Defined2014) [inline pkg/ddl/partition.go:1836]: We could combine two functions and use type `any` for expr param.

Comment (mjonss) [reply pkg/ddl/partition.go:1836]: Yes, but I think the result would be less readable, since it needs to check the input type twice, once for converting to an expression.Expression and once for checking if it is an column, to give a more precise error.

If the two functions are small as they are, same name prefix and close to each other, is that OK? I can merge them, but the result will be schema check and `type == int` check to be common, while expression and error refinement will be different.

What do you prefer?

File: pkg/ddl/partition.go [hunk 2]
```diff
@@ -1809,38 +1809,23 @@ func checkResultOK(ok bool) error {
...
-	}
-	if schema == "" {
-		schema = ctx.GetSessionVars().CurrentDB
+	var e expression.Expression
+	var err error
+	switch expr := anyExpr.(type) {
+	case *ast.ColumnNameExpr:
+		e, err = expression.BuildSimpleExpr(ctx.GetExprCtx(), expr, expression.WithTableInfo(schema, tblInfo))
+	case string:
+		e, err = expression.ParseSimpleExpr(ctx.GetExprCtx(), expr, expression.WithTableInfo(schema, tblInfo))
```
Comment (Defined2014) [inline pkg/ddl/partition.go:1825]: Should check `expr == ""` here?

**Review by Defined2014 — APPROVED** [review]
Others LGTM

File: pkg/ddl/partition.go [hunk 3]
```diff
@@ -1809,27 +1809,32 @@ func checkResultOK(ok bool) error {
...
-
 	if schema == "" {
 		schema = ctx.GetSessionVars().CurrentDB
 	}
-
-	e, err := expression.BuildSimpleExpr(ctx.GetExprCtx(), expr, expression.WithTableInfo(schema, tblInfo))
+	var e expression.Expression
+	var err error
+	switch expr := anyExpr.(type) {
+	case *ast.ColumnNameExpr:
```
Comment (Defined2014) [inline pkg/ddl/partition.go:1822]: And this should be `ast.ExprNode`

File: pkg/ddl/partition.go (hunk 2 above)
Comment (mjonss) [reply pkg/ddl/partition.go:1825]: I added it just for code safety, but it should be checked earlier.

File: pkg/ddl/partition.go [hunk 4]
```diff
@@ -3109,6 +3120,22 @@ func (w *worker) onReorganizePartition(jobCtx *jobContext, t *meta.Meta, job *mo
 			return ver, err
 		}
 
+		if job.Type == model.ActionAlterTablePartitioning {
+			// Also verify same things as in CREATE TABLE ... PARTITION BY
+			if len(partInfo.Columns) > 0 {
+				// shallow copy, only for reading/checking
+				tmpTblInfo := *tblInfo
+				tmpTblInfo.Partition = partInfo
+				if err = checkColumnsPartitionType(&tmpTblInfo); err != nil {
```
Comment (Defined2014) [inline pkg/ddl/partition.go:3129]: Set `job.State = model.JobStateCancelled`

File: pkg/ddl/partition.go [hunk 5]
```diff
@@ -1809,27 +1809,38 @@ func checkResultOK(ok bool) error {
...
 		schema = ctx.GetSessionVars().CurrentDB
 	}
-
-	e, err := expression.BuildSimpleExpr(ctx.GetExprCtx(), expr, expression.WithTableInfo(schema, tblInfo))
+	var e expression.Expression
+	var err error
+	switch expr := anyExpr.(type) {
+	case string:
+		if expr == "" {
+			return errors.Trace(dbterror.ErrPartitionFuncNotAllowed.GenWithStackByArgs("PARTITION"))
```
Comment (Defined2014) [inline pkg/ddl/partition.go:1824]: Should return nil? Just like `anyExpr == nil`?

**Review by D3Hunter — APPROVED** [review]

**Comment by Frank945946** [comment]
@mjonss Please cherry-pick it to LTS v6.5, v7.1, v7.5, and v8.1.
