### PR TITLE
*: Add https/http depending on config for pdapi

### LINKED ISSUE #26568: MetricRetriever doesn't support mTLS when calling pd
### 1. Minimal reproduce step (Required)

Set up a cluster using e.g. `tidb-operator` with full intra-cluster mTLS enabled. Watch the logs and you will eventually find the following error:

```
query metric error: Get "http://https//tidb-pd-1.tidb-pd-peer.mynamespace.svc:2379/pd/api/v1/config": dial tcp: lookup https on 172.20.0.10:53: no such host
github.com/pingcap/tidb/telemetry.readSQLMetric
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/telemetry/data_window.go:116
github.com/pingcap/tidb/telemetry.RotateSubWindow
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/telemetry/data_window.go:193
github.com/pingcap/tidb/domain.(*Domain).TelemetryRotateSubWindowLoop.func1
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/domain/domain.go:1100
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

### 2. What did you expect to see? (Required)

That it connects to pd using mTLS.

### 3. What did you see instead (Required)

That it fails to connect to pd using mTLS.

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.1.0
Edition: Community
Git Commit Hash: 8acd5c88471cb7b4d4c4a8ed73b4d53d6833f13e
Git Branch: heads/refs/tags/v5.1.0
UTC Build Time: 2021-06-24 07:10:32
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

The issue is that the following code doesn't support https:// URLs:
https://github.com/pingcap/tidb/blob/cc5e161ac06827589c4966674597c137cc9e809c/domain/infosync/info.go#L687-L692

And the following code should in case of mTLS pass in a `Roundtripper` transport that has a tls.Config set up with the mTLS client certificate:
https://github.com/pingcap/tidb/blob/4172f473dad30a53878a4539ad6d5cbf3b03e722/executor/metrics_reader.go#L109-L111

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #26568

Problem Summary:
Using 'https://' prefix for pd api configuration fails for `Telemetry.readSQLMetric` / Only checks for 'http://' prefix, not 'https://' prefix

### What is changed and how it works?

What's Changed:
Allow both `http` and `https` protocols/prefix and if not specified, use the one matching current configuration.

How it Works:
Check full prefix for both 'http://' and 'https://' and use if exists, otherwise add 'http://'/'https://' according to configuration

### Check List 

Tests 

- [X] Unit test
- [X] Manual test (add detailed scripts or steps below).

Tested manually by setting up a local cluster with tiup cluster (v5.0.1; 1 tidb node, 1 pd node, 3 tikv + monitoring like prometheus, grafana etc.) and then started a patched tidb-server from master (this patch + debug output and comparing with old implementation). All with TLS setup for the cluster components.

Result:
```
[...] [INFO] [info.go:709] ["pdAddr old"] [url=http://https://127.0.0.1:2379/pd/api/v1/config]
[...] [INFO] [info.go:711] ["pdAddr new"] [url=https://127.0.0.1:2379/pd/api/v1/config]
```

Side effects
N/A

Documentation
- None needed.
### Release note 

```release-note
Fixed bug when https:// was configured for pdapi, resulting on telemetry error.
```

### CODE REVIEW

File: domain/infosync/info.go [hunk 1]
```diff
@@ -699,12 +693,7 @@ func (is *InfoSyncer) getPrometheusAddr() (string, error) {
...
 
 	// Get prometheus address from pdApi.
-	var url, res string
-	if strings.HasPrefix(pdAddrs[0], "http://") {
-		url = fmt.Sprintf("%s%s", pdAddrs[0], pdapi.Config)
-	} else {
-		url = fmt.Sprintf("http://%s%s", pdAddrs[0], pdapi.Config)
-	}
+	url := util2.ComposeURL(pdAddrs[0], pdapi.Config)
 	resp, err := http.Get(url) // #nosec G107
```
Comment (bb7133) [inline domain/infosync/info.go:697]: When `https` scheme is used, the `http.Get(url)` reports an error. 

Please try to use https://github.com/pingcap/tidb/issues/26568#issuecomment-887426960 instead of `http.Get()`.

Comment (bb7133) [inline domain/infosync/info.go:697]: When `https` scheme is used, the `http.Get(url)` reports an error. 

Please try to use https://github.com/pingcap/tidb/issues/26568#issuecomment-887426960 instead of `http.Get()`.

**Comment by bb7133** [comment]
Hi @mjonss Could you update the PR?

File: domain/infosync/info.go (hunk 1 above)
Comment (mjonss) [reply domain/infosync/info.go]: Thanks, I have changed it and also verified by setting up a full cluster.

**Comment by mjonss** [comment]
@bb7133 & @lysu Please take a look. I have manually tested the patch (see the 'manual test' in the description).

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
LGTM

**Review by morgo — APPROVED** [review]
