### PR TITLE
executor: Fix tidb crash on index merge reader

### LINKED ISSUE #40877: TiDB may crash if Index Merge reader meet error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. in https://github.com/pingcap/tidb/blob/ee758bcf8b68ad52ce46cfe9d42647f71614ee26/executor/index_merge_reader.go#L611-L620
the init value of `task` is nil, and it will be assigned by `task = worker.pickAndExecTask(ctx1)`, and it is also be passed as an argument of `worker.handlePickAndExecTaskPanic(ctx1, task)`
2. in https://github.com/pingcap/tidb/blob/ee758bcf8b68ad52ce46cfe9d42647f71614ee26/executor/index_merge_reader.go#L1133-L1143
the recover function will call `task.doneCh <- err4Panic` directly without check if the `task` is nill or not, if `task` is nil, tidb will hit SIGSEGV. A typical crash stack is
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x3c72deb]
panic: runtime error: invalid memory address or nil pointer dereference
panic: Out Of Memory Quota![conn_id=1964567794091557931] [recovered]
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:611 +0x76
created by github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startIndexMergeTableScanWorker
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:614 +0x129
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startIndexMergeTableScanWorker.func1()
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/misc.go:96 +0x53
github.com/pingcap/tidb/util.WithRecovery(0x4fb0730?, 0x4fb0688?)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:615 +0x2e
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startIndexMergeTableScanWorker.func1.1()
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:1123 +0x159
github.com/pingcap/tidb/executor.(*indexMergeTableScanWorker).pickAndExecTask(0xc044d0d1c0, {0x4fb0688, 0xc044d0d200})
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:1174 +0x47a
github.com/pingcap/tidb/executor.(*indexMergeTableScanWorker).executeTask(0xc044d0d1c0, {0x4fb0688, 0xc044d0d200}, 0xc0411a3180)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:478 +0x332
github.com/pingcap/tidb/util/memory.(*Tracker).Consume(0x4fb0688?, 0xc1d96c0)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:437 +0x10b
github.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1(0xc001ad68d0, 0xc0003377d0?)
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/action.go:148 +0x11f
github.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action(0xc044d0c200, 0xc001ad68c0)
/usr/local/go/src/runtime/panic.go:884 +0x212
panic({0x418a100, 0xc0018b0050})
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/misc.go:88 +0x58
github.com/pingcap/tidb/util.WithRecovery.func1()
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:1141 +0xeb
github.com/pingcap/tidb/executor.(*indexMergeTableScanWorker).handlePickAndExecTaskPanic.func1({0x418a100?, 0xc0018b0050?})
```

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #40877

Problem Summary:

### What is changed and how it works?
Let both `pickAndExecTask` and `handlePickAndExecTaskPanic` take the address of `task` as its argument, so once `*task` is assigned in `pickAndExecTask`,  `handlePickAndExecTaskPanic` will get a non nil value.
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

File: executor/index_merge_reader.go [hunk 1]
```diff
@@ -1107,38 +1107,41 @@ type indexMergeTableScanWorker struct {
...
 }
 
-func (w *indexMergeTableScanWorker) pickAndExecTask(ctx context.Context) (task *indexMergeTableTask) {
+func (w *indexMergeTableScanWorker) pickAndExecTask(ctx context.Context, task **indexMergeTableTask) {
 	var ok bool
 	for {
 		waitStart := time.Now()
 		select {
-		case task, ok = <-w.workCh:
+		case *task, ok = <-w.workCh:
```
Comment (time-and-fate) [inline executor/index_merge_reader.go:1115]: It looks like the main point of this PR is to assign to the `task` here, so that even if we panic in `executeTask`, `startIndexMergeTableScanWorker` and `handlePickAndExecTaskPanic` could also get the `doneCh`.

I think it's not easy to realize this. I suggest we add some comments to clarify it.

Comment (windtalker) [reply executor/index_merge_reader.go:1120]: OK, I've add some comments to explain why need use the address of `task` here.

**Review by time-and-fate — APPROVED** [review]
