### PR TITLE
executor: fix incorrect result produced by addtime() or subtime() function when using the date type

### LINKED ISSUE #56861: The subtime() function returns an incorrect result when using the `date` type
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table lrr_test(`COL1` date);
insert into lrr_test values('2024-11-01');
insert into lrr_test values('2020-11-01');
select col1,subtime(col1,'12:00:01.341300') from lrr_test;
```

### 2. What did you expect to see? (Required)
Mysql：
+------------+---------------------------------+
| col1       | subtime(col1,'12:00:01.341300') |
+------------+---------------------------------+
| 2024-11-01 | 2024-10-31 11:59:58.658700      |
| 2020-11-01 | 2020-10-31 11:59:58.658700      |
+------------+---------------------------------+

### 3. What did you see instead (Required)
+------------+---------------------------------+
| col1       | subtime(col1,'12:00:01.341300') |
+------------+---------------------------------+
| 2024-11-01 | -12:00:01.341300                |
| 2020-11-01 | -12:00:01.341300                |
+------------+---------------------------------+

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: 2511e928966110964414e6bbb630a565a9870a52
Git Branch: HEAD
UTC Build Time: 2024-10-27 16:16:04
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #56861

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that addtime() and subtime() function produces incorrect result when the first arg type is date type
```

### CODE REVIEW

File: pkg/expression/builtin_time_test.go [hunk 1]
```diff
@@ -1025,6 +1025,83 @@ func TestAddTimeSig(t *testing.T) {
...
+			require.True(t, err != nil)
+			continue
+		}
+		require.NoError(t, err)
+		result, _ := d.ToString()
+		require.Equal(t, c.expect, result)
+	}
+}
+
+func TestTmp(t *testing.T) {
```
Comment (windtalker) [inline pkg/expression/builtin_time_test.go:1066]: what is this for？

File: pkg/expression/builtin_time_test.go [hunk 2]
```diff
@@ -1025,6 +1025,83 @@ func TestAddTimeSig(t *testing.T) {
...
+		{types.NewTime(types.FromDate(2024, 11, 1, 0, 0, 0, 0), mysql.TypeDate, 0), "-12:00:01.341300", "2024-10-31 11:59:58.658700", nil},
+		{types.NewTime(types.FromDate(2024, 11, 1, 0, 0, 0, 0), mysql.TypeDate, 0), "1 12:00:01.341300", "2024-11-02 12:00:01.341300", nil},
+		{types.NewTime(types.FromDate(2024, 11, 1, 0, 0, 0, 0), mysql.TypeDate, 0), "-1 12:00:01.341300", "2024-10-30 11:59:58.658700", nil},
+		{types.NewTime(types.FromDate(1000, 1, 1, 0, 0, 0, 0), mysql.TypeDate, 0), "12:00:01.341300", "1000-01-01 12:00:01.341300", nil},
+		{types.NewTime(types.FromDate(1000, 1, 1, 0, 0, 0, 0), mysql.TypeDate, 0), "-12:00:01.341300", "0999-12-31 11:59:58.658700", nil},
+		{types.NewTime(types.FromDate(9999, 12, 31, 0, 0, 0, 0), mysql.TypeDate, 0), "12:00:01.341300", "9999-12-31 12:00:01.341300", nil},
+		{types.NewTime(types.FromDate(9999, 12, 31, 0, 0, 0, 0), mysql.TypeDate, 0), "-12:00:01.341300", "9999-12-30 11:59:58.658700", nil},
+		{types.NewTime(types.FromDate(9999, 12, 31, 0, 0, 0, 0), mysql.TypeDate, 0), "1 12:00:01.341300", "", errors.NewNoStackError("")},
```
Comment (windtalker) [inline pkg/expression/builtin_time_test.go:1044]: add some coner case like null value/zero date/empty string/invalid string

Comment (windtalker) [reply pkg/expression/builtin_time_test.go:1044]: And add case to test `AddDateAndDuration`

File: pkg/expression/generator/time_vec.go [hunk 3]
```diff
@@ -299,30 +299,36 @@ func (b *{{.SigName}}) vecEval{{ .Output.TypeName }}(ctx EvalContext, input *chu
...
+		res, err := arg0.Add(tc, arg1Duration)
 		{{ else }}
-		sum, err := types.Duration{Duration: arg0, Fsp: fsp0}.Sub(arg1Duration)
+		res, err := arg0.Add(tc, arg1Duration.Neg())
 		{{ end }}
 		if err != nil {
-			return err
+			tc.AppendWarning(err)
+			result.AppendNull()
+			continue
```
Comment (windtalker) [inline pkg/expression/generator/time_vec.go:314]: why err is ignored?

File: pkg/expression/generator/time_vec.go [hunk 4]
```diff
@@ -785,8 +791,8 @@ var addTimeSigsTmpl = []sig{
 	{SigName: "builtinAddDurationAndStringSig", TypeA: TypeDuration, TypeB: TypeString, Output: TypeDuration},
 	{SigName: "builtinAddStringAndDurationSig", TypeA: TypeString, TypeB: TypeDuration, Output: TypeString},
 	{SigName: "builtinAddStringAndStringSig", TypeA: TypeString, TypeB: TypeString, Output: TypeString},
-	{SigName: "builtinAddDateAndDurationSig", TypeA: TypeDuration, TypeB: TypeDuration, Output: TypeString, FieldTypeA: "Date", FieldTypeB: "Duration", TestTypeA: "Datetime", TestTypeB: "Duration"},
-	{SigName: "builtinAddDateAndStringSig", TypeA: TypeDuration, TypeB: TypeString, Output: TypeString, FieldTypeA: "Date", FieldTypeB: "String", TestTypeA: "Datetime", TestTypeB: "String"},
+	{SigName: "builtinAddDateAndDurationSig", TypeA: TypeDatetime, TypeB: TypeDuration, Output: TypeString, FieldTypeA: "Date", FieldTypeB: "Duration", TestTypeA: "Datetime", TestTypeB: "Duration"},
```
Comment (windtalker) [inline pkg/expression/generator/time_vec.go:794]: what is the `TestTypeA` and `TestTypeB` mean

File: pkg/expression/builtin_time_test.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/expression/builtin_time_test.go]: > what is this for？

Useless, I will delete it.

File: pkg/expression/generator/time_vec.go (hunk 3 above)
Comment (xzhangxian1008) [reply pkg/expression/generator/time_vec.go:314]: > why err is ignored?

Because mysql ignores this err.

File: pkg/expression/generator/time_vec.go (hunk 4 above)
Comment (xzhangxian1008) [reply pkg/expression/generator/time_vec.go:794]: > what is the `TestTypeA` and `TestTypeB` mean

I think `TypeA` and `TypeB` refer to the type of arg0 and arg1 respectively.

**Review by wshwsh12 — APPROVED** [review]

File: tests/integrationtest/r/expression/time.result [hunk 5]
```diff
@@ -1064,3 +1064,314 @@ a	d
...
+select addtime(col0, col2) from t;
+Error 1292 (22007): Incorrect date value: '2024-00-01 00:00:00'
+select subtime(col0, col2) from t;
+Error 1292 (22007): Incorrect date value: '2024-00-01 00:00:00'
+drop table if exists t;
+create table t(col0 date, col1 time, col2 varchar(30));
+set sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
+insert into t values('0-0-0', '1:1:1', '1:1:1');
+set sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
+select addtime(col0, col1) from t;
```
Comment (windtalker) [inline tests/integrationtest/r/expression/time.result:1346]: add tests that the sql mode does contains NO_ZERO_IN_DATE/NO_ZERO_DATE?

File: pkg/expression/builtin_time.go [hunk 6]
```diff
@@ -5255,15 +5255,28 @@ func (b *builtinAddDateAndDurationSig) Clone() builtinFunc {
...
 func (b *builtinAddDateAndDurationSig) evalString(ctx EvalContext, row chunk.Row) (string, bool, error) {
-	arg0, isNull, err := b.args[0].EvalDuration(ctx, row)
+	arg0, isNull, err := b.args[0].EvalTime(ctx, row)
 	if isNull || err != nil {
 		return "", isNull, err
 	}
+
+	mode := sqlMode(ctx)
+	if (mode.HasNoZeroDateMode() && arg0.IsZero()) || (mode.HasNoZeroInDateMode() && arg0.InvalidZero()) {
+		return arg0.String(), true, types.ErrWrongValue.GenWithStackByArgs(types.DateStr, arg0.String())
```
[the remark this answers is not in the document]
Comment (xzhangxian1008) [reply pkg/expression/builtin_time.go]: > maybe return `"", true, types.ErrWrongValue.GenWithStackByArgs(types.DateStr, arg0.String())` is enough

I have deleted it as I find that mysql only check if zero is in date in the result.

File: tests/integrationtest/r/expression/time.result (hunk 5 above)
Comment (xzhangxian1008) [reply tests/integrationtest/r/expression/time.result]: > add tests that the sql mode does contains NO_ZERO_IN_DATE/NO_ZERO_DATE?

done

File: pkg/expression/generator/time_vec.go [hunk 7]
```diff
@@ -299,30 +308,39 @@ func (b *{{.SigName}}) vecEval{{ .Output.TypeName }}(ctx EvalContext, input *chu
...
-		sum, err := types.Duration{Duration: arg0, Fsp: fsp0}.Add(arg1Duration)
+		res, err := arg0.Add(tc, arg1Duration)
 		{{ else }}
-		sum, err := types.Duration{Duration: arg0, Fsp: fsp0}.Sub(arg1Duration)
+		res, err := arg0.Add(tc, arg1Duration.Neg())
 		{{ end }}
 		if err != nil {
-			return err
+			tc.AppendWarning(err)
+			result.AppendNull()
```
Comment (windtalker) [inline pkg/expression/generator/time_vec.go:323]: call `setnull` template?

**Review by windtalker — APPROVED** [review]
lgtm
