### PR TITLE
planner: outer join cannot be eliminated due to the impact of the expression index | tidb-test=pr/2657

### LINKED ISSUE #65166: planner: outer join cannot be eliminated due to the impact of the expression index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

See the example below:
```
DROP TABLE IF EXISTS t_outer;
CREATE TABLE `t_outer` (
  `id` bigint(20) NOT NULL,
  `scode` varchar(64) NOT NULL,
  `username` varchar(60) NOT NULL,
  `real_name` varchar(100) NOT NULL DEFAULT '',
  KEY `idx1` ((lower(`real_name`))),
  -- KEY `idx11` (real_name),
  UNIQUE KEY `idx2` (`username`,`scode`)
);

DROP TABLE IF EXISTS t;
CREATE TABLE `t` (
  `id` int(11) unsigned NOT NULL,
  `scode` varchar(64) NOT NULL DEFAULT '',
  `plat_id` varchar(64) NOT NULL
);

EXPLAIN SELECT
  a.id
FROM
  t AS a
  LEFT JOIN t_outer b -- force index(idx2)  
  ON b.username = a.plat_id
  AND b.scode = a.scode
ORDER BY a.id;
+-------------------------------+----------+-----------+--------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object                        | operator info                                                                                                                     |
+-------------------------------+----------+-----------+--------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Sort_10                       | 12500.00 | root      |                                      | test.t.id                                                                                                                         |
| └─HashJoin_19                 | 12500.00 | root      |                                      | left outer join, left side:TableReader_22, equal:[eq(test.t.plat_id, test.t_outer.username) eq(test.t.scode, test.t_outer.scode)] |
|   ├─IndexReader_28(Build)     | 10000.00 | root      |                                      | index:IndexFullScan_27                                                                                                            |
|   │ └─IndexFullScan_27        | 10000.00 | cop[tikv] | table:b, index:idx2(username, scode) | keep order:false, stats:pseudo                                                                                                    |
|   └─TableReader_22(Probe)     | 10000.00 | root      |                                      | data:TableFullScan_21                                                                                                             |
|     └─TableFullScan_21        | 10000.00 | cop[tikv] | table:a                              | keep order:false, stats:pseudo                                                                                                    |
+-------------------------------+----------+-----------+--------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+

mysql> EXPLAIN SELECT
    ->   a.id
    -> FROM
    ->   t AS a
    ->   LEFT JOIN t_outer b force index(idx2)  
    ->   ON b.username = a.plat_id
    ->   AND b.scode = a.scode
    -> ORDER BY a.id;
+--------------------------+----------+-----------+---------------+--------------------------------+
| id                       | estRows  | task      | access object | operator info                  |
+--------------------------+----------+-----------+---------------+--------------------------------+
| Sort_6                   | 10000.00 | root      |               | test.t.id                      |
| └─TableReader_11         | 10000.00 | root      |               | data:TableFullScan_10          |
|   └─TableFullScan_10     | 10000.00 | cop[tikv] | table:a       | keep order:false, stats:pseudo |
+--------------------------+----------+-----------+---------------+--------------------------------+
```

See the case above, the outer join `b` is not eliminated at first place, but after putting the force index hint on `idx2`, we can eliminate it.

The problem is that the expression index affects the `parentCols` when eliminating outer join and causes us to stop eliminating early (see the picture below): 

Image

If `t_outer.idx1` is a normal index instead of an expression index, the outer join elimination can also work:

```
DROP TABLE IF EXISTS t_outer;
CREATE TABLE `t_outer` (
  `id` bigint(20) NOT NULL,
  `scode` varchar(64) NOT NULL,
  `username` varchar(60) NOT NULL,
  `real_name` varchar(100) NOT NULL DEFAULT '',
  -- KEY `idx1` ((lower(`real_name`))),
  KEY `idx11` (real_name),
  UNIQUE KEY `idx2` (`username`,`scode`)
);
```

### 2. What did you expect to see? (Required)

The outer join should be eliminated.

### 4. What is your TiDB version? (Required)

Master

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #65166

Problem Summary: [65166](planner: outer join cannot be eliminated due to the impact of the expression index)

### What changed and how does it work?

Please see https://github.com/pingcap/tidb/issues/65166#issuecomment-3685823039 for more details.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/integration_test.go [hunk 1]
```diff
@@ -913,6 +913,29 @@ func TestHypoIndexHint(t *testing.T) {
...
+			id int(11) unsigned NOT NULL,
+			scode varchar(64) NOT NULL DEFAULT '',
+			plat_id varchar(64) NOT NULL)`)
+		tk.MustQuery(`EXPLAIN FORMAT='plan_tree' SELECT a.id FROM
+			t AS a LEFT JOIN t_outer b ON b.username = a.plat_id
+			AND b.scode = a.scode ORDER BY a.id`).Check(testkit.Rows(
+			`Sort root  test.t.id`, // the outer join is eliminated
+			`└─TableReader root  data:TableFullScan`,
+			`  └─TableFullScan cop[tikv] table:a keep order:false, stats:pseudo`))
+	})
```
Comment (winoros) [inline pkg/planner/core/integration_test.go:933]: We can use `func (res *Result) CheckNotContain(unexpected string) {` to check there's no `Join` in the output. This can avoid to compare the full explain result.

Comment (qw4990) [reply pkg/planner/core/integration_test.go:933]: Good suggestion, I've updated it.

File: pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json [hunk 2]
```diff
@@ -371,31 +371,34 @@
...
-          "                                └─TableFullScan 10000.00 mpp[tiflash] table:orders keep order:false, stats:pseudo"
+          "          └─HashAgg 8000.00 mpp[tiflash]  group by:test.customer.c_custkey, test.customer.c_name, test.orders.o_orderdate, test.orders.o_orderkey, test.orders.o_totalprice, funcs:sum(Column#91)->Column#52, funcs:firstrow(test.customer.c_custkey)->test.customer.c_custkey, funcs:firstrow(test.customer.c_name)->test.customer.c_name, funcs:firstrow(test.orders.o_orderkey)->test.orders.o_orderkey, funcs:firstrow(test.orders.o_totalprice)->test.orders.o_totalprice, funcs:firstrow(test.orders.o_orderdate)->test.orders.o_orderdate",
+          "            └─ExchangeReceiver 8000.00 mpp[tiflash]  ",
+          "              └─ExchangeSender 8000.00 mpp[tiflash]  ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: test.customer.c_name, collate: utf8mb4_bin], [name: test.customer.c_custkey, collate: binary], [name: test.orders.o_orderkey, collate: binary], [name: test.orders.o_orderdate, collate: binary], [name: test.orders.o_totalprice, collate: binary]",
```
Comment (guo-shaoge) [inline pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json:665]: why we got this extra`ExchangeSedner` compared with the original one

File: pkg/planner/core/testdata/plan_suite_unexported_out.json [hunk 3]
```diff
@@ -170,8 +170,8 @@
       "UnionAll{DataScan(t)->TopN([test.t.a test.t.b],0,5)->Projection->DataScan(s)->TopN([test.t.a test.t.b],0,5)->Projection}->TopN([Column#25 Column#26],0,5)",
       "UnionAll{DataScan(t)->TopN([test.t.a test.t.b],0,10)->Projection->DataScan(s)->TopN([test.t.a test.t.b],0,10)->Projection}->TopN([Column#25 Column#26],5,5)",
       "UnionAll{DataScan(t)->Limit->Projection->DataScan(s)->TopN([test.t.a],0,5)->Projection}->Limit",
-      "Join{DataScan(t1)->TopN([cast(test.t.b, int(11) BINARY)],0,5)->DataScan(t2)}(test.t.e,test.t.e)->TopN([cast(test.t.b, int(11) BINARY)],0,5)->Projection->Projection",
-      "Join{DataScan(t1)->DataScan(t2)}(test.t.e,test.t.e)->TopN([ifnull(test.t.h, test.t.b)],0,5)->Projection->Projection"
+      "Join{DataScan(t1)->TopN([cast(test.t.b, int(11) BINARY)],0,5)->DataScan(t2)}(test.t.e,test.t.e)->Projection->TopN([cast(test.t.b, int(11) BINARY)],0,5)->Projection->Projection",
+      "Join{DataScan(t1)->DataScan(t2)}(test.t.e,test.t.e)->Projection->TopN([ifnull(test.t.h, test.t.b)],0,5)->Projection->Projection"
```
Comment (guo-shaoge) [inline pkg/planner/core/testdata/plan_suite_unexported_out.json:174]: Is this the extra `Projection` expected?

File: pkg/planner/core/casetest/cascades/testdata/cascades_suite_out.json [hunk 4]
```diff
@@ -72,7 +72,7 @@
           "GID:1, GE:DataSource_30{}, logic prop:{stats:{count 5, ColNDVs map[1:2 2:2], GroupNDVs [{[1 2] 4}]}, schema:{Column: [test.t1.a,test.t1.b] PKOrUK: [] NullableUK: []}, fd:{()-->(1,2,7,8)}}",
           "GID:2, GE:DataSource_33{}, logic prop:{stats:{count 3.333333333333333, ColNDVs map[7:1 8:1], GroupNDVs []}, schema:{Column: [test.t2.a,test.t2.b] PKOrUK: [] NullableUK: []}, fd:{()-->(7)}}",
           "GID:3, GE:MaxOneRow_36{GID:2}, logic prop:{stats:{count 1, ColNDVs map[7:1 8:1], GroupNDVs []}, schema:{Column: [test.t2.a,test.t2.b] PKOrUK: [] NullableUK: []}, fd:{()-->(7)}}",
-          "GID:4, GE:Apply_37{GID:1, GID:3}, logic prop:{stats:{count 5, ColNDVs map[1:2 2:2 7:5 8:5], GroupNDVs [{[1 2] 4}]}, schema:{Column: [test.t1.a,test.t1.b,test.t2.a,test.t2.b] PKOrUK: [] NullableUK: []}, fd:{()-->(1,2,7,8)}}",
```
Comment (qw4990) [inline pkg/planner/core/casetest/cascades/testdata/cascades_suite_out.json:75]: expected, the column pruning can take effect again.

File: tests/integrationtest/r/planner/core/rule_constant_propagation.result [hunk 5]
```diff
@@ -120,16 +120,15 @@ HashJoin	root		inner join, equal:[eq(planner__core__rule_constant_propagation.t.
 explain format='plan_tree' select * from t, (select id, count(name) from s where s.id>1 group by id) tmp where t.id=tmp.id; -- can't, constant propagation can't through the aggregation node;
 id	task	access object	operator info
 Projection	root		planner__core__rule_constant_propagation.t.id, planner__core__rule_constant_propagation.t.name, planner__core__rule_constant_propagation.s.id, Column#7
-└─Projection	root		planner__core__rule_constant_propagation.t.id, planner__core__rule_constant_propagation.t.name, Column#7, planner__core__rule_constant_propagation.s.id
```
Comment (qw4990) [inline tests/integrationtest/r/planner/core/rule_constant_propagation.result:123]: Expected, the column pruning can take effect again so we don't need this Projection.

File: tests/integrationtest/r/planner/core/casetest/rule/rule_result_reorder.result [hunk 6]
```diff
@@ -245,11 +245,8 @@ Sort	root		planner__core__casetest__rule__rule_result_reorder.t1.a, planner__cor
 explain format='plan_tree' select t1.* from t1 left outer join t2 on t1.a=t2.a;
 id	task	access object	operator info
 Sort	root		planner__core__casetest__rule__rule_result_reorder.t1.a, planner__core__casetest__rule__rule_result_reorder.t1.b, planner__core__casetest__rule__rule_result_reorder.t1.c, planner__core__casetest__rule__rule_result_reorder.t1.d
-└─MergeJoin	root		left outer join, left side:TableReader, left key:planner__core__casetest__rule__rule_result_reorder.t1.a, right key:planner__core__casetest__rule__rule_result_reorder.t2.a
```
Comment (qw4990) [inline tests/integrationtest/r/planner/core/casetest/rule/rule_result_reorder.result:248]: The merge join has been eliminated.

File: pkg/planner/core/testdata/plan_suite_unexported_out.json (hunk 3 above)
Comment (qw4990) [reply pkg/planner/core/testdata/plan_suite_unexported_out.json:174]: I think YES, since we've changed the join's schema, then later in the `join reorder` rule, it might inject some Projection operator according to the current join's schema.
image

File: pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json (hunk 2 above)
Comment (qw4990) [reply pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json:665]: Yes is a little tricky... the reason why this plan changed is that since we've updated the underlying Join's output schema, which could change row width size, and some part of the cost of the upper Agg is based on row width, this change led to the plan changing from 1-phase-agg to 2-phase-agg.
image

Comment (AilinKid) [reply pkg/planner/core/casetest/tpch/testdata/tpch_suite_out.json:665]: thanks for detailed explanation, great

File: pkg/planner/core/rule_eliminate_projection.go [hunk 7]
```diff
@@ -173,10 +173,8 @@ func (pe *ProjectionEliminator) eliminate(p base.LogicalPlan, replace map[string
 		p.Children()[i] = pe.eliminate(child, replace, childFlag)
 	}
 
-	// replace logical plan schema
+	// Replace all columns in the schema with the replaced columns.
 	switch x := p.(type) {
-	case *logicalop.LogicalJoin:
-		x.SetSchema(logicalop.BuildLogicalJoinSchema(x.JoinType, x))
 	case *logicalop.LogicalApply:
 		x.SetSchema(logicalop.BuildLogicalJoinSchema(x.JoinType, x))
```
Comment (AilinKid) [inline pkg/planner/core/rule_eliminate_projection.go:179]: should we remove the BuildLogicalJoinSchema from apply as well?

Comment (qw4990) [reply pkg/planner/core/rule_eliminate_projection.go:179]: Yeah, I've tried, but @winoros suggested that for safety we'd better keep it unchanged, and remove it later in another separate PR.
