### PR TITLE
*: retry auto-analyze with adjusted samplerate when oom panic

### LINKED ISSUE #29938: "analyze table" has a potential oom risk
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a table
2. insert many data
3. analyze table t with 0.999999 samplerate;

### 3. What did you see instead (Required)
```
tidb-server invoked oom-killer: gfp_mask=0x600040(GFP_NOFS), nodemask=(null), order=0, oom_score_adj=0
```

### 4. What is your TiDB version? (Required)

release-5.3

### PR DESCRIPTION
**Pull request by chrysan**
### What problem does this PR solve?

Issue Number: close #29938
Problem Summary:

### What is changed and how it works?
```
+--------------+------------+----------------+-------------------------------------------------------------------------------------------+----------------+---------------------+---------------------+----------+------------------------------------------------------------------------------------------------------+--------------------+------------+
| Table_schema | Table_name | Partition_name | Job_info                                                                                  | Processed_rows | Start_time          | End_time            | State    | Fail_reason                                                                                          | Instance           | Process_ID |
+--------------+------------+----------------+-------------------------------------------------------------------------------------------+----------------+---------------------+---------------------+----------+------------------------------------------------------------------------------------------------------+--------------------+------------+
| test         | sbtest1    |                | retry auto analyze table all columns with 100 topn, 0.055 samplerate                      |        2000000 | 2022-05-07 16:41:09 | 2022-05-07 16:41:20 | finished | NULL                                                                                                 | 192.168.10.18:4000 |       NULL |
| test         | sbtest1    |                | auto analyze table all columns with 100 topn, 0.5 samplerate                              |              0 | 2022-05-07 16:40:50 | 2022-05-07 16:41:09 | failed   | analyze panic due to memory quota exceeds, please try with smaller samplerate(refer to 110000/count) | 192.168.10.18:4000 |       NULL |
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/builder.go [hunk 1]
```diff
@@ -2466,7 +2420,6 @@ func (b *executorBuilder) buildAnalyzeSamplingPushdown(task plannercore.AnalyzeC
 		DBName:        task.DBName,
 		TableName:     task.TableName,
 		PartitionName: task.PartitionName,
-		JobInfo:       describeV2AnalyzeJobInfo(task, autoAnalyze, opts, *sampleRate),
```
Comment (Yisaer) [inline executor/builder.go:2469]: What about jobinfo for v1 auto analyze? It seems lost.

File: executor/analyze.go [hunk 2]
```diff
@@ -2489,6 +2526,66 @@ func FinishAnalyzeJob(ctx sessionctx.Context, job *statistics.AnalyzeJob, analyz
 	}
 }
 
+func prepareV2AnalyzeJobInfo(e *AnalyzeColumnsExec, retry bool) {
```
Comment (Yisaer) [inline executor/analyze.go:2529]: it seems equal between introducing retry param for `describeV2AnalyzeJobInfo` and passing by `analyzeColumnsPushdownWithRetry`

File: executor/analyze.go [hunk 3]
```diff
@@ -408,6 +410,41 @@ func (e *AnalyzeExec) analyzeWorker(taskCh <-chan *analyzeTask, resultsCh chan<-
...
 }
 
+func analyzeColumnsPushdownWithRetry(e *AnalyzeColumnsExec) *statistics.AnalyzeResults {
+	analyzeResult := analyzeColumnsPushdown(e)
+	// do not retry if succeed / not oom error / not auto-analyze / samplerate not set
+	if analyzeResult.Err == nil || analyzeResult.Err != errAnalyzeOOM ||
+		!e.ctx.GetSessionVars().InRestrictedSQL ||
+		e.analyzePB.ColReq == nil || *e.analyzePB.ColReq.SampleRate <= 0 {
+		return analyzeResult
+	}
```
Comment (Yisaer) [inline executor/analyze.go:420]: We need to assert statsVersion if we only wanted retry v2 analyze job according to `	// only statistics.Version2 will throw oom error and retry`

**Review by Yisaer — COMMENTED** [review]
rest lgtm

File: executor/analyze.go [hunk 4]
```diff
@@ -408,6 +410,41 @@ func (e *AnalyzeExec) analyzeWorker(taskCh <-chan *analyzeTask, resultsCh chan<-
...
+	} else {
+		statsTbl = statsHandle.GetPartitionStats(e.tableInfo, tid)
+	}
+	if statsTbl == nil || statsTbl.Count <= 0 {
+		return analyzeResult
+	}
+	newSampleRate := math.Min(1, float64(config.DefRowsForSampleRate)/float64(statsTbl.Count))
+	if newSampleRate >= *e.analyzePB.ColReq.SampleRate {
+		return analyzeResult
+	}
```
Comment (xuyifangreeneyes) [inline executor/analyze.go:439]: What if 110000 samples still causes oom? Do we need to handle that case?

File: util/memory/tracker.go [hunk 5]
```diff
@@ -601,9 +601,9 @@ const (
 	// LabelForNonTransactionalDML represents the label of the non-transactional DML
 	LabelForNonTransactionalDML = -23
 	// LabelForAnalyzeMemory represents the label of the memory of each analyze job
-	LabelForAnalyzeMemory int = -23
+	LabelForAnalyzeMemory int = -24
```
Comment (xuyifangreeneyes) [inline util/memory/tracker.go:604]: Why do we change this?

File: executor/analyze.go (hunk 4 above)
Comment (chrysan) [reply executor/analyze.go:439]: If 110000 samples still cause oom, it could be a problem with data or quota settings. As we once discussed before, I think we need metrics and alerts for this kind of case to involve ops. Let's do it in another PR.

File: executor/analyze.go (hunk 3 above)
Comment (chrysan) [reply executor/analyze.go]: Updated

**Review by Yisaer — APPROVED** [review]

**Review by xuyifangreeneyes — APPROVED** [review]
