### PR TITLE
stats: use an alternative function to read the bound from `BLOB` stored in `mysql.stats_buckets`. | tidb-test=pr/2503

### LINKED ISSUE #59759: `Data Too Long, field len X` error when loading stats for a `bit` column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set tidb_stats_load_sync_wait = 5000;
create table t(a bit(1));
insert into t value(1),(0);
analyze table t all columns with 0 topn;
explain select * from t where a = 0;
```

### 2. What did you expect to see? (Required)

Stats loading success.

### 3. What did you see instead (Required)

Both async and sync load failed.

```
127.0.0.1:4000[test]> explain select * from t where a = 0;
+-------------------------+---------+-----------+---------------+-----------------------------------------------+
| id                      | estRows | task      | access object | operator info                                 |
+-------------------------+---------+-----------+---------------+-----------------------------------------------+
| TableReader_7           | 0.00    | root      |               | data:Selection_6                              |
| └─Selection_6           | 0.00    | cop[tikv] |               | eq(test.t.a, 0)                               |
|   └─TableFullScan_5     | 2.00    | cop[tikv] | table:t       | keep order:false, stats:partial[a:allEvicted] |
+-------------------------+---------+-----------+---------------+-----------------------------------------------+
3 rows in set (0.635 sec)
```

In tidb log:
```log
[2025/02/25 21:35:53.446 +08:00] [WARN] [stats_syncload.go:142] ["SyncWaitStatsLoad meets error"] [errors="[\"tableID:110, id:1, isIndex:false, err:[types:1406]Data Too Long, field len 1\"]"]
[2025/02/25 21:35:55.796 +08:00] [INFO] [owner_daemon.go:56] ["daemon became owner"] [id=a2ab1778-2b94-4749-b4b2-22fcb8fe60e8] [daemon-id=LogBackup::Advancer]
[2025/02/25 21:35:55.797 +08:00] [INFO] [advancer.go:518] ["Subscription handler spawned."] [category="log backup subscription manager"]
[2025/02/25 21:35:55.797 +08:00] [INFO] [advancer.go:664] ["No tasks yet, skipping advancing."]
[2025/02/25 21:35:55.824 +08:00] [WARN] [domain.go:2605] ["load histograms failed"] [error="[types:1406]Data Too Long, field len 1"]
[2025/02/25 21:35:58.825 +08:00] [WARN] [domain.go:2605] ["load histograms failed"] [error="[types:1406]Data Too Long, field len 1"]
[2025/02/25 21:36:01.234 +08:00] [WARN] [stats_syncload.go:142] ["SyncWaitStatsLoad meets error"] [errors="[\"tableID:110, id:1, isIndex:false, err:[types:1406]Data Too Long, field len 1\"]"]
[2025/02/25 21:36:01.825 +08:00] [WARN] [domain.go:2605] ["load histograms failed"] [error="[types:1406]Data Too Long, field len 1"]
[2025/02/25 21:36:04.428 +08:00] [WARN] [stats_syncload.go:142] ["SyncWaitStatsLoad meets error"] [errors="[\"tableID:110, id:1, isIndex:false, err:[types:1406]Data Too Long, field len 1\"]"]
[2025/02/25 21:36:04.819 +08:00] [WARN] [domain.go:2605] ["load histograms failed"] [error="[types:1406]Data Too Long, field len 1"]
[2025/02/25 21:36:07.796 +08:00] [INFO] [advancer.go:664] ["No tasks yet, skipping advancing."]
[2025/02/25 21:36:07.824 +08:00] [WARN] [domain.go:2605] ["load histograms failed"] [error="[types:1406]Data Too Long, field len 1"]
[2025/02/25 21:36:10.816 +08:00] [WARN] [domain.go:2605] ["load histograms failed"] [error="[types:1406]Data Too Long, field len 1"]
```

### 4. What is your TiDB version? (Required)

from v7.5 to nightly (v9.0)

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #59759 

Problem Summary:

The stats logic relies on the behavior that type conversion from A to Blob to A is still equal to the original value. However, it's not true for `BIT` after https://github.com/pingcap/tidb/pull/57303.

### What changed and how does it work?

Add an extra function to handle the load of `BLOB` bound specially. It'll not affect the behavior of any expression, but only modify the stats part.

BTW, I add some test assertion, because I don't know in which case the `BIT` cannot be formatted into an integer. Maybe never.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that the stats of a table with `BIT` column cannot be loaded.
```

### CODE REVIEW

File: pkg/statistics/handle/storage/read.go [hunk 1]
```diff
@@ -843,3 +843,35 @@ func StatsMetaByTableIDFromStorage(sctx sessionctx.Context, tableID int64, snaps
...
+func convertBoundFromBlob(ctx types.Context, blob types.Datum, tp *types.FieldType) (types.Datum, error) {
+	// For `BIT` type, when converting to `BLOB`, it's formated as an integer (when it's possible). Therefore, we should try to
+	// parse it as an integer first.
+	if tp.GetType() == mysql.TypeBit {
+		var ret types.Datum
+
+		// The implementation of converting BIT to BLOB will try to format it as an integer first. Theoretically, it should
+		// always be able to format the integer because the `BIT` length is limited to 64. Therefore, this err should never
+		// happen.
+		uintValue, err := strconv.ParseInt(string(blob.GetBytes()), 10, 64)
```
Comment (YangKeao) [inline pkg/statistics/handle/storage/read.go:859]: Another question, are the bucket bounds always a value from the table? 

If not (e.g. it's somehow calculated), it's possible that it's an invalid utf8mb4 string or it's not an integer string. Then this logic is incorrect and I don't know how to do it properly 🤔 .

File: pkg/statistics/handle/storage/read.go [hunk 2]
```diff
@@ -843,3 +843,35 @@ func StatsMetaByTableIDFromStorage(sctx sessionctx.Context, tableID int64, snaps
 	count = rows[0].GetInt64(2)
 	return
 }
+
+// convertBoundFromBlob reads the bound from blob. The `blob` is read from the `mysql.stats_buckets` table.
+// The `convertBoundFromBlob(convertBoundToBlob(a))` should be equal to `a`.
+// TODO: add a test to make sure that this assumption is correct.
```
Comment (YangKeao) [inline pkg/statistics/handle/storage/read.go:849]: BTW, I think the stats need a more stable serialization/deserialization method. Depending on `ConvertTo` to/from `BLOB` is not good in long term 🤦 .

File: pkg/statistics/handle/storage/read.go (hunk 1 above)
Comment (time-and-fate) [reply pkg/statistics/handle/storage/read.go:859]: Yes. We can assume it's always a real value from the table.

Comment (time-and-fate) [inline pkg/statistics/handle/storage/read.go:859]: The `uintValue` is actually an `int64`. I think it's better to name it `intValue` or use `ParseUint()`.

File: pkg/statistics/handle/storage/read.go [hunk 3]
```diff
@@ -843,3 +843,35 @@ func StatsMetaByTableIDFromStorage(sctx sessionctx.Context, tableID int64, snaps
...
+		}
+
+		if tp.GetFlen() < 64 && uintValue >= 1<<(uint64(tp.GetFlen())) {
+			logutil.BgLogger().Warn("bound in stats exceeds the bit length", zap.Int64("bound", uintValue), zap.Int("flen", tp.GetFlen()))
+			intest.Assert(false, "bound in stats exceeds the bit length")
+			uintValue = (1 << (uint64(tp.GetFlen()))) - 1
+		}
+		byteSize := (tp.GetFlen() + 7) >> 3
+		ret.SetMysqlBit(types.NewBinaryLiteralFromUint(uint64(uintValue), byteSize))
+		return blob, nil
```
Comment (time-and-fate) [inline pkg/statistics/handle/storage/read.go:874]:
```suggestion
		return ret, nil
```
Typo?

File: pkg/statistics/handle/storage/read.go [hunk 4]
```diff
@@ -843,3 +843,35 @@ func StatsMetaByTableIDFromStorage(sctx sessionctx.Context, tableID int64, snaps
...
+		intest.AssertNoError(err)
+		if err != nil {
+			// Fail to parse, return the original blob as BIT directly.
+			ret.SetBinaryLiteral(types.BinaryLiteral(blob.GetBytes()))
+			return ret, nil
+		}
+
+		if tp.GetFlen() < 64 && uintValue >= 1<<(uint64(tp.GetFlen())) {
+			logutil.BgLogger().Warn("bound in stats exceeds the bit length", zap.Int64("bound", uintValue), zap.Int("flen", tp.GetFlen()))
+			intest.Assert(false, "bound in stats exceeds the bit length")
```
Comment (time-and-fate) [inline pkg/statistics/handle/storage/read.go:869]: Originally we will return this error. Here it's only logged.
I think it's probably better to return the error still. What do you think about it? @Rustin170506

Comment (Rustin170506) [reply pkg/statistics/handle/storage/read.go:869]: I think we better return an error here. Also, we can keep the assertion here.

Comment (YangKeao) [reply pkg/statistics/handle/storage/read.go]: Done.

File: pkg/statistics/handle/storage/read.go (hunk 1 above)
Comment (YangKeao) [reply pkg/statistics/handle/storage/read.go]: Done.

File: pkg/statistics/handle/storage/read.go [hunk 5]
```diff
@@ -914,3 +914,36 @@ func StatsMetaByTableIDFromStorage(sctx sessionctx.Context, tableID int64, snaps
...
+
+		if tp.GetFlen() < 64 && uintValue >= 1<<(uint64(tp.GetFlen())) {
+			logutil.BgLogger().Warn("bound in stats exceeds the bit length", zap.Uint64("bound", uintValue), zap.Int("flen", tp.GetFlen()))
+			err = types.ErrDataTooLong.GenWithStack("Data Too Long, field len %d", tp.GetFlen())
+			intest.Assert(false, "bound in stats exceeds the bit length")
+			uintValue = (1 << (uint64(tp.GetFlen()))) - 1
+		}
+		byteSize := (tp.GetFlen() + 7) >> 3
+		ret.SetMysqlBit(types.NewBinaryLiteralFromUint(uintValue, byteSize))
+		return ret, errors.Trace(err)
```
Comment (time-and-fate) [inline pkg/statistics/handle/storage/read.go:946]: Could you help to add a comment that this part of the logic is from `convertToMysqlBit()`?

Comment (YangKeao) [reply pkg/statistics/handle/storage/read.go:947]: Done.

**Comment by YangKeao** [comment]
Strange. I cannot reproduce the failure in my dev environment 🤦 .

File: pkg/statistics/handle/handletest/handle_test.go [hunk 6]
```diff
@@ -1512,3 +1512,25 @@ func TestStatsCacheUpdateTimeout(t *testing.T) {
 	require.Equal(t, 6, int(globalStats2.RealtimeCount))
 	require.Equal(t, 2, int(globalStats2.ModifyCount))
 }
+
+func TestLoadStatsForBitColumn(t *testing.T) {
```
Comment (Rustin170506) [inline pkg/statistics/handle/handletest/handle_test.go:1516]: Could you please add another test case for values other than 0 or 1? Thanks!

File: pkg/statistics/handle/storage/read.go [hunk 7]
```diff
@@ -914,3 +914,37 @@ func StatsMetaByTableIDFromStorage(sctx sessionctx.Context, tableID int64, snaps
...
+		if err != nil {
+			// Fail to parse, return the original blob as BIT directly.
+			ret.SetBinaryLiteral(types.BinaryLiteral(blob.GetBytes()))
+			return ret, nil
+		}
+
+		// part of the code is copied from `(*Datum).convertToMysqlBit`.
+		if tp.GetFlen() < 64 && uintValue >= 1<<(uint64(tp.GetFlen())) {
+			logutil.BgLogger().Warn("bound in stats exceeds the bit length", zap.Uint64("bound", uintValue), zap.Int("flen", tp.GetFlen()))
+			err = types.ErrDataTooLong.GenWithStack("Data Too Long, field len %d", tp.GetFlen())
```
Comment (Rustin170506) [inline pkg/statistics/handle/storage/read.go:941]: Why can’t we return an error here immediately?

**Review by Rustin170506 — APPROVED** [review]
Thanks! :shipit:

/hold

File: pkg/statistics/handle/handletest/handle_test.go (hunk 6 above)
Comment (YangKeao) [reply pkg/statistics/handle/handletest/handle_test.go:1516]: Done. Add more tests which also includes `"0"` (string) / `"a"` and `2` and `3`...

File: pkg/statistics/handle/storage/read.go (hunk 7 above)
Comment (YangKeao) [reply pkg/statistics/handle/storage/read.go:941]: It's fine to return the error directly for this use case.

In the original codes, it'll need to return a valid truncated value with an error, and the caller can decide whether to return an error to the user or return a truncated value with warning to the user. 

The caller of this function always returns the error and ignore the truncated value, so it's fine to return an error here immediately. However, I chose to keep the same code logic with the original one, to make it clearer (and the comment already describes that these codes are copied 🤦, so copying code is usually not a good thing).
