### PR TITLE
*: reduce the allocation of error constructing in `DecodeTableID`

### LINKED ISSUE #41300: sysbench update index performance degradation by commit e8c32a
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

compare the sysbench oltp_update_index on commit e8fb81b4fb316723251e2c41dd52f8795a with baseline.

### 2. What did you expect to see? (Required)
no performance degradation

### 3. What did you see instead (Required)
before
img_v2_02e792f2-b08e-430a-af62-f65200e65a9g

after
img_v2_93b9ba44-df77-4759-bb96-55c9c325edeg

### 4. What is your TiDB version? (Required)
v6.6

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: close #41300

Problem Summary:

The original decode process checks if the key is API v2 first, which will always fail while the user is using API V1. This will cause the code will read the stack every time it decodes the key, which is CPU/MEM expensive.

### What is changed and how it works?

This pull request checks if the key is API V1 first, if it's not, then try API v2 decoding.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviours
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
*: reduce the allocation of error constructing in `DecodeTableID`
```

### CODE REVIEW

File: tablecodec/tablecodec.go [hunk 1]
```diff
@@ -278,13 +278,14 @@ func DecodeKeyHead(key kv.Key) (tableID int64, indexID int64, isRecordKey bool,
...
-	}
 	if !key.HasPrefix(tablePrefix) {
-		return 0
+		// If the key is in API V2, then ignore the prefix
+		_, k, err := tikv.DecodeKey(key, kvrpcpb.APIVersion_V2)
+		if err != nil {
+			terror.Log(errors.Trace(err))
+			return 0
+		}
+		key = k
```
Comment (zeminzhou) [inline tablecodec/tablecodec.go:288]: If the `k` we parsed from the `key` still doesn't start with tablePrefix?

**Review by ekexium — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Comment by ystaticy** [comment]
LGTM
