### PR TITLE
ddl: let partition table pre split index regions

### LINKED ISSUE #59530: ddl: the region which presplit at create table, was different on table and partition table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

test case : presplit regions when create `partition table`
```sql
-- create table with partitions ;
CREATE TABLE sbtest0000(
  id bigint,
  k bigint DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  UNIQUE KEY uk(id),
  key idx0(k,c),
  key idx1(c)
)SHARD_ROW_ID_BITS=3 PRE_SPLIT_REGIONS=2
PARTITION BY RANGE(id)(PARTITION p VALUES LESS THAN (MAXVALUE));
-- show regions for table;
show table sbtest0000 regions;
```
test case : presplit regions when create `normal table`
```sql
-- create table ;
CREATE TABLE sbtest1111(
  id bigint,
  k bigint DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  UNIQUE KEY uk(id),
  key idx0(k,c),
  key idx1(c)
)SHARD_ROW_ID_BITS=3 PRE_SPLIT_REGIONS=2;
-- show regions for table;
show table sbtest1111 regions;
```

### 2. What did you expect to see? (Required)
the regions splited same numbers

### 3. What did you see instead (Required)
normal table, the index was splited ,and record was splited to 4 regions;
partition table, all the data for `partition table` was splited to 4 regions (index was not splited).

Image

### 4. What is your TiDB version? (Required)

Image

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #59530

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: pkg/ddl/split_region.go [hunk 1]
```diff
@@ -38,6 +38,8 @@ func splitPartitionTableRegion(ctx sessionctx.Context, store kv.SplittableStore,
 	defer cancel()
 	ctxWithTimeout = kv.WithInternalSourceType(ctxWithTimeout, kv.InternalTxnDDL)
 	if shardingBits(tbInfo) > 0 && tbInfo.PreSplitRegions > 0 {
+		scatter, tableID := getScatterConfig(scatterScope, tbInfo.ID)
+		regionIDs = append(regionIDs, splitIndexRegion(store, tbInfo, scatter, tableID)...)
```
Comment (zimulala) [inline pkg/ddl/split_region.go:42]: Is it for the global index？ Could we add a comment for it？

Besides, do we need to update the capacity for `regionIDs`?

File: pkg/executor/test/splittest/split_table_test.go [hunk 2]
```diff
@@ -575,6 +575,29 @@ func TestShowTableRegion(t *testing.T) {
...
+	require.Len(t, rows, 7) // 3 index regions + 4 record regions
+
+	tbl = external.GetTableByName(t, tk, "test", "sbtest0000")
+	require.Equal(t, fmt.Sprintf("t_%d_i_1_", tbl.Meta().ID), rows[0][1]) // index `uk``
+	require.Equal(t, fmt.Sprintf("t_%d_i_4_", tbl.Meta().ID+1), rows[1][1])
+	require.Regexp(t, fmt.Sprintf("t_%d_r_.*", tbl.Meta().ID+1), rows[2][1])
+	require.Regexp(t, fmt.Sprintf("t_%d_r_.*", tbl.Meta().ID+1), rows[3][1])
+	require.Regexp(t, fmt.Sprintf("t_%d_r_.*", tbl.Meta().ID+1), rows[4][1])
+	require.Equal(t, fmt.Sprintf("t_%d_", tbl.Meta().ID+1), rows[5][1])     // index `idx0`
+	require.Equal(t, fmt.Sprintf("t_%d_i_3_", tbl.Meta().ID+1), rows[6][1]) // index `idx1`
```
Comment (zimulala) [inline pkg/executor/test/splittest/split_table_test.go:600]: Should we consider adding a test case with both a global index and a normal index?

File: pkg/ddl/split_region.go (hunk 1 above)
Comment (Defined2014) [reply pkg/ddl/split_region.go:44]: Done
