### PR TITLE
txn: change check logic for column type change for amend

### LINKED ISSUE #21470: Amending transaction accepts DDLs that changes column types but gives wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set @@global.tidb_enable_change_column_type=true;
create table t (id int primary key, v varchar(10));
```

| session 1 | session 2 | |
|--|--|--|
| `begin;` | | |
| `insert into t values (1, "123456789");` | | |
| | `alter table t modify column v varchar(5);` | |
| `commit;` | | |
| `select * from t;` | | Gets `(1, NULL)` |

### 2. What did you expect to see? (Required)

Transaction on session 1 fails, either because not support by amend txn or value of `v` too long.

### 3. What did you see instead (Required)

v = NULL in the final result.

### 4. What is your TiDB version? (Required)

master (c9288d246c99073ff04304363dc7234d9caa5090 )

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #21470 

Problem Summary:
On the 5.0 or the master branch, the change column ddl may **NOT** keep the original column id as in the release-4.0 branch, checking the modify colum action type in amend phase could not decide whether it's a newly added column or if this column type change is accepatable, so report error for such branches. 

### What is changed and how it works?

What's Changed:
Report error for checking modify colum action type if the column could not be found in early schema version though column type change is not GA release currently. This change will make the amend fail for ddl change with both adding column and modifying column.

How it Works:

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note`.

### CODE REVIEW

File: session/schema_amender.go [hunk 1]
```diff
@@ -200,6 +200,13 @@ func (a *amendCollector) collectModifyColAmendOps(tblAtStart, tblAtCommit table.
 			if err != nil {
 				return nil, err
 			}
+		} else {
+			// If the column could not be found in the original schema, it could not be decided if this column
+			// is newly added or modified from an original column.Report error to solve the issue
+			// https://github.com/pingcap/tidb/issues/21470. This change will make amend fail for adding column
+			// and modifying columns at the same time.
+			return nil, errors.Trace(errors.Errorf("column=%v id=%v is not found for table=%v checking column modify",
```
Comment (you06) [inline session/schema_amender.go:208]: Is it ok to make add-column amend fail?

Comment (cfzjywxk) [reply session/schema_amender.go:208]: Single add-column will not fail, change type containing add column with modify/change column will.

Comment (zyguan) [reply session/schema_amender.go:208]: It seems that `errors.Errorf` will attach stack info, thus I think `errors.Trace` is unnecessary.

**Comment by lysu** [comment]
LGTM

File: session/schema_amender.go (hunk 1 above)
Comment (MyonKeminta) [reply session/schema_amender.go]: Looks like the function's comment at L193 needs to be  updated?

**Review by jackysp — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
