### PR TITLE
lightning: fix routes panic for csv data load

### LINKED ISSUE #43284: lightning: routes panic  for  csv data  load
## Bug Report

routes not worked for standard csv data  

### 1. Minimal reproduce step (Required)
tidb-lightning config file

[[routes]]
schema-pattern = "test1"
target-schema = "test"

[tidb@vm dump]$ ls -lrt
total 12
-rw-rw-r-- 1 tidb tidb  8 Apr 21 15:54 test1.dump_test.001.sql
-rw-rw-r-- 1 tidb tidb 12 Apr 21 15:54 test1.dump_test.002.sql
-rw-rw-r-- 1 tidb tidb  4 Apr 21 15:54 test1.dump_test.003.sql
[tidb@vm dump]$ cat *
1,a
2,b
3,c
4,d
5,e
6,f

[tidb@vm ~]$ tiup tidb-lightning:v6.5.1  -config ./tidb-lightning.toml
Starting component `tidb-lightning`: /home/tidb/.tiup/components/tidb-lightning/v6.5.1/tidb-lightning -config ./tidb-lightning.toml
Verbose debug logs will be written to tidb-lightning01.log

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x32b613d]

goroutine 1 [running]:
github.com/pingcap/tidb/br/pkg/lightning/mydump.(*mdLoaderSetup).route(0xc00067e480)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/mydump/loader.go:514 +0x5bd
github.com/pingcap/tidb/br/pkg/lightning/mydump.(*mdLoaderSetup).setup(0xc00067e480, {0x4d13bc8, 0xc000b2e2c0})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/mydump/loader.go:350 +0x1b9
github.com/pingcap/tidb/br/pkg/lightning/mydump.NewMyDumpLoaderWithStore({0x4d13bc8, 0xc000b2e2c0}, 0xc000bf4000, {0x4d30cc0?, 0xc000485ef0}, {0x0, 0x0, 0x2760?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/mydump/loader.go:273 +0x6ae
github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).run(0xc000bd01a0, {0x4d13c00, 0xc00011a000}, 0xc000bf4000, 0xc000bce770)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/lightning.go:497 +0xa4b
github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).RunOnceWithOptions(0xc000bd01a0, {0x4d13c00, 0xc00011a000}, 0xc000bf4000, {0x0, 0x0, 0xc000012798?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/lightning.go:373 +0x205
main.main.func2(0xc000bc6f00, 0xc000bbff30?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/tidb-lightning/main.go:94 +0x74
main.main()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/tidb-lightning/main.go:95 +0x6b3

### 2. What did you expect to see? (Required)

import data to table test.dump_test successful

### 3. What did you see instead (Required)

tidb-lightning panic: runtime error: invalid memory address or nil pointer dereference

### 4. What is your TiDB version? (Required)
tidb v6.5.1
tidb-lightning v6.5.1

### PR DESCRIPTION
**Pull request by lyzx2001**
### What problem does this PR solve?

Issue Number: close #43284 

Problem Summary:

Routes does not work for standard csv data.

https://github.com/pingcap/tidb/blob/c0e705723331ba2ea6bb4f167189959af14c0161/br/pkg/lightning/mydump/loader.go#L512-L527

It does map initialization for `s.dbSchemas`, then operate on `s.tableSchemas`, `s.viewSchemas`, and `s.tableDatas`. However, the scope of `s.tableSchemas` does not cover the latter three ones, resulting in accessing invalid memory address or nil pointer dereference.

### What is changed and how it works?

For `s.tableSchemas`, `s.viewSchemas`, and `s.tableDatas`, initialize for each of them respectively, instead of initializing for `s.dbSchemas`.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/mydump/loader.go [hunk 1]
```diff
@@ -510,19 +510,25 @@ func (s *mdLoaderSetup) route() error {
...
 		knownDBNames[info.TableName.Schema] = &dbInfo{
 			fileMeta: info.FileMeta,
 			count:    1,
 		}
-	}
-	for _, info := range s.tableSchemas {
 		knownDBNames[info.TableName.Schema].count++
 	}
 	for _, info := range s.viewSchemas {
+		knownDBNames[info.TableName.Schema] = &dbInfo{
```
Comment (lance6716) [inline br/pkg/lightning/mydump/loader.go:521]: we should check if the item is already in knownDBNames, otherwise we will overwrite existing items.

val, ok := m[key]

File: br/pkg/lightning/mydump/loader.go [hunk 2]
```diff
@@ -510,19 +510,25 @@ func (s *mdLoaderSetup) route() error {
 	}
 
 	knownDBNames := make(map[string]*dbInfo)
-	for _, info := range s.dbSchemas {
```
Comment (lance6716) [inline br/pkg/lightning/mydump/loader.go:513]: I'm not sure if dbSchemas can be removed. Let's check CI

File: br/pkg/lightning/mydump/loader.go (hunk 1 above)
Comment (lyzx2001) [reply br/pkg/lightning/mydump/loader.go]: yes I realized that later too, modified

File: br/pkg/lightning/mydump/loader.go [hunk 3]
```diff
@@ -517,12 +517,30 @@ func (s *mdLoaderSetup) route() error {
 		}
 	}
 	for _, info := range s.tableSchemas {
+		if _, ok := knownDBNames[info.TableName.Schema]; !ok {
+			knownDBNames[info.TableName.Schema] = &dbInfo{
+				fileMeta: info.FileMeta,
+				count:    1,
```
Comment (lance6716) [inline br/pkg/lightning/mydump/loader.go:523]: I'm not sure we should use 1 or 0 here. Wrong value may cause problem in following logic. Can you add an integration test for it?

**Review by lance6716 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM
