### PR TITLE
expression: fix values null value issue

### LINKED ISSUE #4921: values function bug.
```
drop table if exists test;

create table test(
id int not null,
txt text,
blb blob,
vc varchar(20),
num int,
fnum float,
primary key(id));

insert into test values(1,'txt hello','blb hello','vc hello', 1, 1.1);

insert into test values(1, NULL,NULL,NULL,NULL,NULL)
on duplicate key update
txt = values(txt),
blb = values(blb),
vc = values(vc),
num = values(num),
fnum = values(fnum);

select * from test; 
— WRONG ANSWER: 1, NULL, NULL, NULL, 0, 0
— EXPECTED: 1, NULL, NULL, NULL, NULL, NULL
```

TiDB version:

```
select tidb_version();

Release Version: 1.0.0
Git Commit Hash: 9fd150d1bc2c631792a9fedca92909b120a1e608
Git Branch: release-1.0
UTC Build Time: 2017-10-25 08:58:58
```

### PR DESCRIPTION
**Pull request by winkyao**
fix #4921

### CODE REVIEW

**Comment by winkyao** [comment]
@XuHuaiyu @shenli @zz-jason PTAL

File: expression/builtin_other.go [hunk 1]
```diff
@@ -198,6 +198,9 @@ func (b *builtinValuesIntSig) evalInt(_ types.Row) (int64, bool, error) {
 	}
 	row := values.([]types.Datum)
 	if b.offset < len(row) {
+		if row[b.offset].IsNull() {
+			return 0, true, nil
+		}
 		return row[b.offset].GetInt64(), false, nil
```
Comment (zz-jason) [inline expression/builtin_other.go]: how about `return row[b.offset].GetInt64(), row[b.offset].IsNull(), nil`
