### PR TITLE
executor,infoschema: Change column type on information_schema.CLUSTER_INFO

### LINKED ISSUE #45221: CLUSTER_INFO START_TIME column doesn't have native time format
## Bug Report

The `START_TIME` column of the `information_schema.CLUSTER_INFO` table has a string that also isn't in MySQL timestamp format. Would be better to have this column as a real timestamp or date format.

### 1. Minimal reproduce step (Required)

```
mysql> SET @a:=CURRENT_TIMESTAMP(); DO SLEEP(5); SELECT TIMESTAMPDIFF(SECOND, @a, CURRENT_TIMESTAMP);
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (5.01 sec)

+----------------------------------------------+
| TIMESTAMPDIFF(SECOND, @a, CURRENT_TIMESTAMP) |
+----------------------------------------------+
|                                            5 |
+----------------------------------------------+
1 row in set (0.01 sec)

mysql> SELECT START_TIME, TIMESTAMPDIFF(SECOND, START_TIME, CURRENT_TIMESTAMP) FROM information_schema.CLUSTER_INFO WHERE START_TIME<>'';
+---------------------------+------------------------------------------------------+
| START_TIME                | TIMESTAMPDIFF(SECOND, START_TIME, CURRENT_TIMESTAMP) |
+---------------------------+------------------------------------------------------+
| 2023-07-06T14:49:46+02:00 |                                                    0 |
+---------------------------+------------------------------------------------------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```
mysql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v7.3.0-alpha-128-g967699a509
Edition: Community
Git Commit Hash: 967699a50938848bcd3504a43856d5487af2d0b3
Git Branch: master
UTC Build Time: 2023-07-06 12:42:35
GoVersion: go1.20.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore
1 row in set (0.00 sec)
```

Related:
- #24858

### PR DESCRIPTION
**Pull request by dveeden**
Issue Number: close #45221 

Related: #24858

### What problem does this PR solve?

The `START_TIME` column of `information_schema.CLUSTER_INFO` was a `VARCHAR` with values like `2021-11-15T07:32:19+01:00`. This changes the column to be a MySQL datetime format.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
The type of the `START_TIME` column of the `CLUSTER_INFO` table in the `information_schema` was changed from a `VARCHAR` to `DATETIME`.
```

### CODE REVIEW

File: infoschema/tables.go [hunk 1]
```diff
@@ -1079,7 +1079,7 @@ var tableClusterInfoCols = []columnInfo{
 	{name: "STATUS_ADDRESS", tp: mysql.TypeVarchar, size: 64},
 	{name: "VERSION", tp: mysql.TypeVarchar, size: 64},
 	{name: "GIT_HASH", tp: mysql.TypeVarchar, size: 64},
-	{name: "START_TIME", tp: mysql.TypeVarchar, size: 32},
+	{name: "START_TIME", tp: mysql.TypeDatetime, size: -1},
```
Comment (morgo) [inline infoschema/tables.go:1082]: It looks like for `TypeDatetime` we inconsistently specify the size as: `-1`, `19`, or omit it.

This doesn't introduce any new inconsistencies, but it would be nice to get an answer on what is considered most correct. @wjhuang2016 do you have ideas?

Comment (wjhuang2016) [reply infoschema/tables.go:1082]: 19 (which ignores fraction) or 26 (which uses the max fraction) is ok.

Comment (dveeden) [reply infoschema/tables.go]: Is this something that should be in https://pingcap.github.io/tidb-dev-guide/ or not?

Comment (wjhuang2016) [reply infoschema/tables.go]: I don't think so.

**Review by morgo — APPROVED** [review]
LGTM. I think the CI failure is unrelated

**Review by wjhuang2016 — COMMENTED** [review]
Is it ok to remove the suffix `+08:00`?

**Comment by dveeden** [comment]
> Is it ok to remove the suffix `+08:00`?

I think it is. Do you see any problem with that?

**Comment by wjhuang2016** [comment]
> > Is it ok to remove the suffix `+08:00`?
> 
> I think it is. Do you see any problem with that?

I'm not sure, maybe we should request other people to review it.

**Comment by dveeden** [comment]
@wjhuang2016 Any suggestions for additional reviewers?

**Review by mjonss — COMMENTED** [review]
Is it possible to create a test case for this PR?

**Comment by dveeden** [comment]
> Is it possible to create a test case for this PR?

done

File: infoschema/tables_test.go [hunk 2]
```diff
@@ -1591,3 +1591,11 @@ func TestTableConstraintsContainForeignKeys(t *testing.T) {
 	tk.MustQuery("SELECT *  FROM INFORMATION_SCHEMA.table_constraints WHERE constraint_schema = 'tableconstraints' AND table_name = 't2'").Sort().Check(testkit.Rows("def tableconstraints PRIMARY tableconstraints t2 PRIMARY KEY", "def tableconstraints fk_t2_t1 tableconstraints t2 FOREIGN KEY"))
 	tk.MustQuery("SELECT *  FROM INFORMATION_SCHEMA.table_constraints WHERE constraint_schema = 'tableconstraints' AND table_name = 't1'").Sort().Check(testkit.Rows("def tableconstraints PRIMARY tableconstraints t1 PRIMARY KEY"))
 }
+
+func TestClusterInfoTime(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("SELECT START_TIME+1 FROM information_schema.CLUSTER_INFO")
+	warnings := tk.Session().GetSessionVars().StmtCtx.GetWarnings()
+	require.Lenf(t, warnings, 0, "expect no warnings, but found: %+v", warnings)
```
Comment (mjonss) [inline infoschema/tables_test.go:1600]: Hmm, this test does not fail in unpatched master :(

**Comment by dveeden** [comment]
Without this PR:
```
mysql> SELECT START_TIME+1 FROM information_schema.CLUSTER_INFO;
+--------------+
| START_TIME+1 |
+--------------+
|         2024 |
|            1 |
+--------------+
2 rows in set, 1 warning (0.00 sec)

mysql> SHOW WARNINGS;
+---------+------+---------------------------------------------------------------+
| Level   | Code | Message                                                       |
+---------+------+---------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: '2023-07-06T13:52:40+02:00' |
+---------+------+---------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by dveeden** [comment]
```
$ mysql --comments --host 127.0.0.1 --port 4000 -u root --column-type-info 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.7.25-TiDB-v7.3.0-alpha-137-g8c71149116 TiDB Server (Apache License 2.0) Community Edition, MySQL 8.0 compatible

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT START_TIME FROM information_schema.CLUSTER_INFO;
Field   1:  `START_TIME`
Catalog:    `def`
Database:   `information_schema`
Table:      `CLUSTER_INFO`
Org_table:  `CLUSTER_INFO`
Type:       DATETIME
Collation:  binary (63)
Length:     19
Max_length: 19
Decimals:   0
Flags:      


+---------------------+
| START_TIME          |
+---------------------+
| 2023-07-06 14:58:14 |
| 0000-00-00 00:00:00 |
+---------------------+
2 rows in set (0.00 sec)
```

File: infoschema/test/clustertablestest/tables_test.go [hunk 3]
```diff
@@ -1806,3 +1806,11 @@ func TestAddFieldsForBinding(t *testing.T) {
 	require.Equal(t, rows[0][7], "use_index(@`sel_1` `test`.`t` ), ignore_index(`t` `a`)")
 	require.Equal(t, rows[0][8], "select * from `t` where `a` = ?")
 }
+
+func TestClusterInfoTime(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustQuery("SELECT START_TIME+1 FROM information_schema.CLUSTER_INFO")
+	warnings := tk.Session().GetSessionVars().StmtCtx.GetWarnings()
+	require.Lenf(t, warnings, 0, "expect no warnings, but found: %+v", warnings)
```
Comment (Defined2014) [inline infoschema/test/clustertablestest/tables_test.go:1815]: How about use `require.Nil` here

**Comment by Defined2014** [comment]
And pls fixed `TestTiDBClusterInfo` test case

File: infoschema/test/clustertablestest/tables_test.go (hunk 3 above)
Comment (dveeden) [reply infoschema/test/clustertablestest/tables_test.go]: Done. Thanks for the suggestion.

**Comment by dveeden** [comment]
> And pls fixed `TestTiDBClusterInfo` test case

Done

**Review by wjhuang2016 — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
