### PR TITLE
ddl: use session begin timestamp to read record for adding index

### LINKED ISSUE #40074: GC life time is shorter than transaction duration while running DDL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Run add index job in a large table, and set the batch_size to 10240.

It is not easy to reproduce because the DDL txn is usually fast.

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

Ingest add index job fallback to txn-merge mode. 
```
[INFO] [index.go:762] ["[ddl] fallback to txn-merge backfill process"] [error="[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2022-12-20 10:58:20.94 +0000 UTC, GC safe point is 2022-12-20 10:58:22.14 +0000 UTC"]
```

### 4. What is your TiDB version? (Required)

ed33fdea6

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #40074

Problem Summary:

Previously, we use `store.CurrentVersion` to get the latest start TS to read table records. This is problematic because it does not take the GC life time into account.

### What is changed and how it works?

Get an internal session and begin transaction explicitly. Thus, we can utilize the mechanism introduced in #42897 to block the progress of GC safe point before the reading is complete.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/index_cop.go [hunk 1]
```diff
@@ -151,11 +163,27 @@ func (c *copReqSender) run() {
...
+	sessVars := se.GetSessionVars()
+	sessVars.TxnCtxMu.Lock()
+	startTS = sessVars.TxnCtx.StartTS
+	sessVars.TxnCtxMu.Unlock()
+	return f(startTS)
 }
 
 func newCopReqSenderPool(ctx context.Context, copCtx *copContext, store kv.Storage,
-	taskCh chan *reorgBackfillTask, checkpointMgr *ingest.CheckpointManager) *copReqSenderPool {
+	taskCh chan *reorgBackfillTask, sessPool *sess.Pool,
```
Comment (Benjamin2037) [inline ddl/index_cop.go:185]: Seems v6.5， there is no checkpointManager?

Comment (tangenta) [reply ddl/index_cop.go:185]: It has nothing related to the checkpoint manager.

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by wjhuang2016 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
