### PR TITLE
ddl: correct ingest row count for partition tables

### LINKED ISSUE #43586: The row count is not accurate during adding index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create a partition table and load data.
2. Create an index in ingest mode.
3. `ADMIN SHOW DDL JOBS` and check the `row_count`.

### 2. What did you expect to see? (Required)

The row count should be accurate.

### 3. What did you see instead (Required)

It only counts the last partition of the table.

### 4. What is your TiDB version? (Required)

98bead0

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #43586

Problem Summary:

Previously, the checkpoint manager is created or closed in each partition. It doesn't have a way to "remember" the row count in previous partition. As a result, the row count reported by the `Status()` function from checkpoint manager is always the last partition.

### What is changed and how it works?

Create or close the checkpoint manager for each table instead of each partition.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/backfilling_scheduler.go [hunk 1]
```diff
@@ -296,11 +296,9 @@ func (b *ingestBackfillScheduler) setupWorkers() error {
...
 	}
 	b.backendCtx = bc
-	if !b.distribute {
-		mgr, err := ingest.NewCheckpointManager(b.ctx, bc, b.sessPool, job.ID, b.reorgInfo.currElement.ID)
-		if err != nil {
-			return errors.Trace(err)
-		}
+	mgr := bc.GetCheckpointManager()
+	if mgr != nil {
+		mgr.Reset(b.tbl.GetPhysicalID())
```
Comment (Benjamin2037) [inline ddl/backfilling_scheduler.go:301]: When resume from last checkpoint, should

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by wjhuang2016 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
