### PR TITLE
planner: use the original table stats to estimate NDV for index selection of IndexJoin

### LINKED ISSUE #63869: planner: can't select the lowest-cost index for IndexJoin in some cases
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use SQLs below to prepare data:
```
create table ts (idx int, code int, a int, key k(idx, code));
set @@cte_max_recursion_depth=10000;

insert into ts select * from (
  with recursive tt as (
    select 0 as idx, 0 as code, 0 as a
    union all
    select mod(a, 100) as idx, 0 as code, a+1 as a from tt where a<5000
  ) select * from tt
) tt;


create table h (idx int, code int, typ1 int, typ2 int, update_time int, key k1(idx, typ1, typ2), key k2(idx, update_time));
insert into h select * from (
  with recursive tt as (
    select 0 idx, 0 as code, 0 as typ1, 0 as typ2, 0 as update_time
    union all
    select mod(update_time, 100) as idx, 0 as code, 0 as typ1, 0 as typ2, update_time+1 as update_time from tt where update_time<5000
  ) select * from tt
) tt;

analyze table ts, h;
explain select /*+ tidb_inlj(h) */ 1 from ts inner join h on ts.idx=h.idx and ts.code=h.code
where h.typ1=0 and h.typ2=0 and h.update_time>0 and h.update_time<2 and h.code=0;
```

By default, the optimizer chose `k1(idx, typ1, typ2)` as the index of the `IndexJoin`, but actually `k2(idx, update_time)` has a much lower cost:
```
mysql> explain format='verbose' select /*+ tidb_inlj(h) */ 1 from ts inner join h on ts.idx=h.idx and ts.code=h.code
    -> where h.typ1=0 and h.typ2=0 and h.update_time>0 and h.update_time<2 and h.code=0;
+---------------------------------+-----------+-------------+-----------+------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| id                              | estRows   | estCost     | task      | access object                      | operator info                                                                                                         |
+---------------------------------+-----------+-------------+-----------+------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| Projection_9                    | 50.01     | 19013288.28 | root      |                                    | 1->Column#11                                                                                                          |
| └─IndexJoin_28                  | 50.01     | 19013283.28 | root      |                                    | inner join, inner:IndexLookUp_27, outer key:test.ts.idx, inner key:test.h.idx, equal cond:eq(test.ts.idx, test.h.idx) |
|   ├─IndexReader_41(Build)       | 5001.00   | 126732.01   | root      |                                    | index:Selection_40                                                                                                    |
|   │ └─Selection_40              | 5001.00   | 1267253.40  | cop[tikv] |                                    | eq(test.ts.code, 0)                                                                                                   |
|   │   └─IndexFullScan_39        | 5001.00   | 1017703.50  | cop[tikv] | table:ts, index:k(idx, code)       | keep order:false                                                                                                      |
|   └─IndexLookUp_27(Probe)       | 50.01     | 98313.71    | root      |                                    |                                                                                                                       |
|     ├─Selection_25(Build)       | 250100.01 | 14707.94    | cop[tikv] |                                    | not(isnull(test.h.idx))                                                                                               |
|     │ └─IndexRangeScan_23       | 250100.01 | 12212.44    | cop[tikv] | table:h, index:k1(idx, typ1, typ2) | range: decided by [eq(test.h.idx, test.ts.idx) eq(test.h.typ1, 0) eq(test.h.typ2, 0)], keep order:false               |
|     └─Selection_26(Probe)       | 50.01     | 20889.58    | cop[tikv] |                                    | eq(test.h.code, 0), gt(test.h.update_time, 0), lt(test.h.update_time, 2)                                              |
|       └─TableRowIDScan_24       | 250100.01 | 13403.08    | cop[tikv] | table:h                            | keep order:false                                                                                                      |
+---------------------------------+-----------+-------------+-----------+------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
10 rows in set, 1 warning (0.004 sec)

mysql> 
mysql> explain format='verbose' select /*+ tidb_inlj(h) use_index(h, k2) */ 1 from ts inner join h on ts.idx=h.idx and ts.code=h.code
    -> where h.typ1=0 and h.typ2=0 and h.update_time>0 and h.update_time<2 and h.code=0;
+---------------------------------+---------+------------+-----------+-------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| id                              | estRows | estCost    | task      | access object                       | operator info                                                                                                         |
+---------------------------------+---------+------------+-----------+-------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| Projection_9                    | 50.01   | 2627663.80 | root      |                                     | 1->Column#11                                                                                                          |
| └─IndexJoin_27                  | 50.01   | 2627658.81 | root      |                                     | inner join, inner:IndexLookUp_26, outer key:test.ts.idx, inner key:test.h.idx, equal cond:eq(test.ts.idx, test.h.idx) |
|   ├─IndexReader_40(Build)       | 5001.00 | 126732.01  | root      |                                     | index:Selection_39                                                                                                    |
|   │ └─Selection_39              | 5001.00 | 1267253.40 | cop[tikv] |                                     | eq(test.ts.code, 0)                                                                                                   |
|   │   └─IndexFullScan_38        | 5001.00 | 1017703.50 | cop[tikv] | table:ts, index:k(idx, code)        | keep order:false                                                                                                      |
|   └─IndexLookUp_26(Probe)       | 50.01   | 19.63      | root      |                                     |                                                                                                                       |
|     ├─Selection_24(Build)       | 50.01   | 2.77       | cop[tikv] |                                     | not(isnull(test.h.idx))                                                                                               |
|     │ └─IndexRangeScan_22       | 50.01   | 2.27       | cop[tikv] | table:h, index:k2(idx, update_time) | range: decided by [eq(test.h.idx, test.ts.idx) eq(test.h.update_time, 1)], keep order:false                           |
|     └─Selection_25(Probe)       | 50.01   | 4.18       | cop[tikv] |                                     | eq(test.h.code, 0), eq(test.h.typ1, 0), eq(test.h.typ2, 0)                                                            |
|       └─TableRowIDScan_23       | 50.01   | 2.68       | cop[tikv] | table:h                             | keep order:false                                                                                                      |
+---------------------------------+---------+------------+-----------+-------------------------------------+-----------------------------------------------------------------------------------------------------------------------+
```

### 2. What did you expect to see? (Required)
The optimizer should chose the second plan.

### 3. What did you see instead (Required)
`k1`

### 4. What is your TiDB version? (Required)

v7.5.x, Master

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #63869

Problem Summary: planner: use the original table stats to estimate NDV for index selection of IndexJoin

### What changed and how does it work?

When estimating NDV for index selection for IndexJoin, we should use the original table stats instead of the stats AFTER APPLYING ALL FILTERS:
image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/integration_test.go [hunk 1]
```diff
@@ -2377,6 +2377,30 @@ JOIN
...
+		tk.MustExec(`insert into h select * from (
+		  with recursive tt as (
+			select 0 idx, 0 as code, 0 as typ1, 0 as typ2, 0 as update_time
+			union all
+			select mod(update_time, 5) as idx, 0 as code, 0 as typ1, 0 as typ2, update_time+1 as update_time from tt where update_time<200
+		  ) select * from tt) tt`)
+		tk.MustExec(`analyze table ts, h`)
+		// use the index k2(idx, update_time) since update_time has a higher NDV than typ1 and typ2
+		tk.MustUseIndex(`select /*+ tidb_inlj(h) */ 1 from ts inner join h on ts.idx=h.idx and ts.code=h.code
+				where h.typ1=0 and h.typ2=0 and h.update_time>0 and h.update_time<2 and h.code=0`, "k2")
```
Comment (terry1purcell) [inline pkg/planner/core/integration_test.go:2400]: A problem with this new logic - if I change this where clause to be:
"where h.typ1=0 and h.typ2=1 and h.update_time>0 and h.code=0;" <-- such that I changed typ2=1 (which qualifies 0% of the rows), and removed update_time<2 (such that >0 qualifies 100%) - then we now choose the wrong index because this is based upon the NDV of update_time and does not reflect the fact that typ2=1 is more selective than update_time>0

File: pkg/planner/core/integration_test.go [hunk 2]
```diff
@@ -2377,6 +2377,30 @@ JOIN
 	})
 }
 
+func TestIssue63869(t *testing.T) {
+	testkit.RunTestUnderCascades(t, func(t *testing.T, tk *testkit.TestKit, cascades, caller string) {
+		tk.MustExec(`use test`)
+		tk.MustExec(`create table ts (idx int, code int, a int, key k(idx, code))`)
+		tk.MustExec(`insert into ts select * from (
```
Comment (terry1purcell) [inline pkg/planner/core/integration_test.go:2384]: Can you mock the statistics of both tables rather than inserting and running analyze?

File: pkg/planner/core/index_join_path.go [hunk 3]
```diff
@@ -316,7 +316,11 @@ func indexJoinPathConstructResult(
 	lastColManager *physicalop.ColWithCmpFuncManager,
 	usedColsLen int) *indexJoinPathResult {
 	var innerNDV float64
-	if stats := indexJoinInfo.innerStats; stats != nil && stats.StatsVersion != statistics.PseudoVersion {
+	if stats := indexJoinInfo.innerTableStats; stats != nil && stats.StatsVersion != statistics.PseudoVersion {
+		// NOTE: use the original table's stats (DataSource.TableStats) to estimate NDV instead of stats
+		// AFTER APPLYING ALL FILTERS (DataSource.stats). Because here we'll use the NDV to measure how many
+		// rows we need to scan in double-read, and these filters will be applied after the scanning, so we need to
+		// ignore these filters to avoid underestimation. See #63869.
 		innerNDV, _ = cardinality.EstimateColsNDVWithMatchedLen(
```
Comment (elsa0520) [inline pkg/planner/core/index_join_path.go:324]: If I switch to using the original table's stats, will the inner ndv still be adjusted based on the filter?
This is because the inner side ndv should theoretically include the ndv after the filter, not the original ndv.

File: pkg/planner/core/integration_test.go (hunk 1 above)
Comment (qw4990) [reply pkg/planner/core/integration_test.go:2400]: Thanks for bring this case, the root cause that we have these issues is that we're using NDV to decide which index to use for IndexJoin, this method is naturally not perfect and has many bad cases. 
But the purpose of this PR is not to change the fundamental method, just correct the stats used in this method.
