### PR TITLE
cop: ignore locks with the same start_ts

### LINKED ISSUE #52460: Pipelined DML cannot ignore its own locks when reading
## Bug Report

Please answer these questions before submitting your issue. Thanks!
ref #50215 
### 1. Minimal reproduce step (Required)

Keep repeating this SQL (to make the dataset large enough and trigger region splits)
`insert into t select * from t`

### 2. What did you expect to see? (Required)

No errors.

### 3. What did you see instead (Required)

`Resolve lock timeout` error, which is reported by coprocessor.

### 4. What is your TiDB version? (Required)

master(ab90c771a21590a14c842e6dd1db03c998a9e3a2)

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #52460 

Problem Summary:

### What changed and how does it work?

If this cop is not a stale read, which means its start_ts is fetched from PD, which means the start_ts cannot conflict with other transactions, add this ts to resolved_locks so that in a pipelined txn the locks belonging to the same txn will not block coprocessor.

For get and batch_get, they already put start_ts in resolved_locks.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below): repeating `insert into t select * from t` no longer reports `resolve lock timeout` error. I found it hard to be tested in unit test.
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by you06 — APPROVED** [review]

File: pkg/store/copr/coprocessor.go [hunk 1]
```diff
@@ -190,6 +190,17 @@ func (c *CopClient) BuildCopIterator(ctx context.Context, req *kv.Request, vars
...
 	}
+	// Pipelined-dml can flush locks when it is still reading.
+	// The coprocessor of the txn should not be blocked by itself.
+	// It should be the only case where a coprocessor can read locks of the same ts.
+	//
+	// But when start_ts is not obtained from PD,
+	// the start_ts could conflict with another pipelined-txn's start_ts.
+	// in which case the locks of same ts cannot be ignored.
+	// We rely on the assumption: start_ts is not from PD => this is a stale read.
+	if !req.IsStaleness {
```
Comment (cfzjywxk) [inline pkg/store/copr/coprocessor.go:201]: For `tidb_snapshot` read path, the `staleness` may not be set.

Comment (ekexium) [reply pkg/store/copr/coprocessor.go:201]: This is a bit confusing. Is it intentional or an oversight? I suppose that `tidb_snapshot` is solely used for stale reads.

Comment (cfzjywxk) [reply pkg/store/copr/coprocessor.go:201]: The `stale` flag is not set in the kv request if I do not remember wrong, there are two stale read implementaions in tidb and `tidb_snasphot` is the earlier one.

Comment (ekexium) [reply pkg/store/copr/coprocessor.go:201]: Yes I've verified that. I mean if it's unintentional we can fix it by setting `IsStaleness` for this case.

Comment (cfzjywxk) [reply pkg/store/copr/coprocessor.go:201]: Do you mean setting `IsStaleness` for `tidb_snaoshot` read?

Comment (ekexium) [reply pkg/store/copr/coprocessor.go:201]: Yes

Comment (cfzjywxk) [reply pkg/store/copr/coprocessor.go:201]: In theory, this is the way to proceed with the change. 
However, it's a breaking change because `tidb_snapshot` wasn't set before (setting it will trigger a check on `safe_ts`). Currently, it's unclear if other components rely on this behavior. 
We can proceed by merging this PR first.

**Review by cfzjywxk — APPROVED** [review]

File: pkg/store/copr/coprocessor.go (hunk 1 above)
Comment (ekexium) [reply pkg/store/copr/coprocessor.go:201]: Then it's possible that when `tidb_snapshot` is set to a ts conflicting with a pipelined txn, coprocessor ignores the locks while point_get doens't?

Comment (cfzjywxk) [reply pkg/store/copr/coprocessor.go:201]: I think so though `tidb_snapshot` seems not to be used widely currenly.
