### PR TITLE
executor: add conversion to opaque value for json_objectagg and json_arrayagg

### LINKED ISSUE #25053: `json_objectagg()` is not compatible with MySQL on `varbinary` type
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists tbl_0;
create table tbl_0 (col_2 int, col_3 varbinary(163));
insert into tbl_0 values (1,'o');
select json_objectagg( col_2, col_3 ) from tbl_0;
```

### 2. What did you expect to see? (Required)

MySQL returns a strange string:
```
+--------------------------------+
| json_objectagg( col_2, col_3 ) |
+--------------------------------+
| {"1": "base64:type15:bw=="}    |
+--------------------------------+
```

### 3. What did you see instead (Required)

TiDB returns `o` for varbinary:
```
+--------------------------------+
| json_objectagg( col_2, col_3 ) |
+--------------------------------+
| {"1": "o"}                     |
+--------------------------------+
```

### 4. What is your TiDB version? (Required)

```
commit 0158f71cda6ccbbd382c6e8759904234baca259c (HEAD, upstream/master)
Author: tangenta <tangenta@126.com>
Date:   Tue Jun 1 18:59:37 2021 +0800

    ddl: support type conversion between non-varchar and varchar (#24959)
```

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #25053 

Problem Summary:

The behavior of `json_objectagg` and `json_arrayagg` are different with MySQL, about the binary opaque value.

### What is changed and how it works?

Add a condition for the binary values, and convert them to the JSON Opaque. It needs to notice that:

1. The value cannot be directly casted into JSON. The cast json behavior will try to cast a string to json, which is not expected.
2. The key could contain control character (e.g. `\t`, `\n`). The MySQL also has the same behavior, though JSON path cannot contain control character.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

```
drop table if exists test;
create table test (col_2 int, col_3 varbinary(163));
insert into test values (1,'o');
select json_objectagg( col_2, col_3 ) from test;

drop table if exists test;
create table test (col_2 int, col_3 binary(163));
insert into test values (1,'o');
select json_objectagg( col_2, col_3 ) from test;

drop table if exists test;
create table test (col_2 int, col_3 blob);
insert into test values (1,'o');
select json_objectagg( col_2, col_3 ) from test;

select json_objectagg( 'a', b'1010111' ) from test;
```

### Release note
```release-note
Fix the issue that the json_objectagg and json_arrayagg is not compatible with MySQL on binary value.
```

### CODE REVIEW

File: executor/aggfuncs/func_json_objectagg.go [hunk 1]
```diff
@@ -15,6 +15,9 @@
 package aggfuncs
 
 import (
+	"github.com/pingcap/tidb/parser/charset"
+	"github.com/pingcap/tidb/parser/mysql"
```
Comment (xhebox) [inline executor/aggfuncs/func_json_objectagg.go:19]: Fix the lint plz

**Review by xhebox — APPROVED** [review]

**Comment by YangKeao** [comment]
PTAL @xiongjiwei

**Review by xiongjiwei — APPROVED** [review]
