### PR TITLE
*: fix tiny bug and add more DML test for list partition table

### LINKED ISSUE #21437: error message of list partition table has no partition is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (a int) partition by list (a%10) (partition p0 values in (0,1));
insert into t values (null);
```

### 2. What did you expect to see? (Required)

```sql
> insert into t values (null);
(1526, 'Table has no partition for value NULL')
```

### 3. What did you see instead (Required)

```sql
> insert into t values (null);
(1526, 'Table has no partition for value 0')
```

### 4. What is your TiDB version? (Required)

```sql
> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1714-gb56f2f80f                    |
| Edition: Community                                                |
| Git Commit Hash: b56f2f80fe7236c35fa3c61e9b010c02e2380b90         |
| Git Branch: list-p-test2                                          |
| UTC Build Time: 2020-12-02 08:22:33                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

close #21437

Fix tiny bug and add more DML test for list partition table.

### What is changed and how it works?

N/A

### Related changes

- N/A

### Check List 

Tests 

- Unit test
- No code

Side effects

- N/A

### Release note 

- N/A

### CODE REVIEW

**Comment by crazycs520** [comment]
@xiongjiwei @tiancaiamao PTAL

**Review by xiongjiwei — COMMENTED** [review]
LGTM

**Review by xiongjiwei — APPROVED** [review]

**Comment by crazycs520** [comment]
@wjhuang2016 PTAL

File: executor/write_test.go [hunk 1]
```diff
@@ -2968,6 +2968,541 @@ func (s *testSuite4) TestWriteListColumnsPartitionTable(c *C) {
...
+	// Test add unique index failed.
+	tk.MustExec("insert into t values  (1, 'a'),(1,'b')")
+	_, err := tk.Exec("alter table t add unique index idx (id)")
+	c.Assert(err.Error(), Equals, "[kv:1062]Duplicate entry '1' for key 'idx'")
+	// Test add unique index success.
+	tk.MustExec("delete from t where name='b'")
+	tk.MustExec("alter table t add unique index idx (id)")
+
+	// --------------------------Test insert---------------------------
+	// Test insert 1 partition.
```
Comment (wjhuang2016) [inline executor/write_test.go:2993]: Replace?

Comment (crazycs520) [reply executor/write_test.go:2993]: ? replace what?

Comment (wjhuang2016) [reply executor/write_test.go:2993]: Replace into

Comment (crazycs520) [reply executor/write_test.go:2993]: Already has `replace test` in line 3060.

Comment (wjhuang2016) [reply executor/write_test.go:2993]: Sorry, I missed that.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
