### PR TITLE
show column comment, table auto-increment; change index default collation

### LINKED ISSUE #3747: auto_increment is missing from `show create table`
`AUTO_INCREMENT=X` is missing from `show create table`.

MySQL:

```
mysql> create table t2(a int key auto_increment, b int, c int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t2 values (0, 1, 1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t2 values (0, 1, 1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t2 values (0, 1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> show create table t2;
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                 |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t2    | CREATE TABLE `t2` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

TiDB:

```
mysql> create table t2(a int key auto_increment, b int, c int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t2 values (0, 1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t2 values (0, 1, 1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t2 values (0, 1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> show create table t2;
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                 |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t2    | CREATE TABLE `t2` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #4224: `SHOW FULL COLUMNS` fail to show a table/column comments
## 1. What did you do?

I exported mysql DDL-s by using `mysqldump` with parameter `--no-data`, so I got DDL-s like below:

```sql
CREATE TABLE `t_bs_s_data_item` (
  `ITEM_CD` varchar(10) NOT NULL COMMENT '数据项代码  ',
  `ITEM_NM` varchar(50) NOT NULL COMMENT '数据项名称',
  `ITEM_TYPE` varchar(20) NOT NULL COMMENT '数据项值类型',
  `TS` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '时间戳',
  `NT` varchar(256) DEFAULT NULL COMMENT '备注'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='数据项表';
```

I got success msgs after executed all the DDL-s in TiDB, but all the table/column comments seem missing.

## 2. What did you expect to see?

```sql
MySQL > SHOW FULL COLUMNS FROM t_bs_s_data_item;
+-----------+--------------+-----------------+------+-----+-------------------+-----------------------------+---------------------------------+--------------------+
| Field     | Type         | Collation       | Null | Key | Default           | Extra                       | Privileges                      | Comment            |
+-----------+--------------+-----------------+------+-----+-------------------+-----------------------------+---------------------------------+--------------------+
| ITEM_CD   | varchar(10)  | utf8_general_ci | NO   |     | NULL              |                             | select,insert,update,references | 数据项代码         |
| ITEM_NM   | varchar(50)  | utf8_general_ci | NO   |     | NULL              |                             | select,insert,update,references | 数据项名称         |
| ITEM_TYPE | varchar(20)  | utf8_general_ci | NO   |     | NULL              |                             | select,insert,update,references | 数据项值类型       |
| TS        | timestamp    | NULL            | YES  |     | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP | select,insert,update,references | 时间戳             |
| NT        | varchar(256) | utf8_general_ci | YES  |     | NULL              |                             | select,insert,update,references | 备注               |
+-----------+--------------+-----------------+------+-----+-------------------+-----------------------------+---------------------------------+--------------------+
5 rows in set (0.00 sec)
```

## 3. What did you see instead?

comments are missing:
```sql
TiDB > SHOW FULL COLUMNS FROM t_bs_s_data_item;
+-----------+--------------+-----------+------+------+-------------------+-----------------------------+---------------------------------+---------+
| Field     | Type         | Collation | Null | Key  | Default           | Extra                       | Privileges                      | Comment |
+-----------+--------------+-----------+------+------+-------------------+-----------------------------+---------------------------------+---------+
| ITEM_CD   | varchar(10)  | utf8_bin  | NO   |      | NULL              |                             | select,insert,update,references |         |
| ITEM_NM   | varchar(50)  | utf8_bin  | NO   |      | NULL              |                             | select,insert,update,references |         |
| ITEM_TYPE | varchar(20)  | utf8_bin  | NO   |      | NULL              |                             | select,insert,update,references |         |
| TS        | timestamp    | binary    | YES  |      | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP | select,insert,update,references |         |
| NT        | varchar(256) | utf8_bin  | YES  |      | NULL              |                             | select,insert,update,references |         |
+-----------+--------------+-----------+------+------+-------------------+-----------------------------+---------------------------------+---------+
5 rows in set (0.00 sec)
```

## 4. What version of TiDB are you using (`tidb-server -V`)?

```sh
[tidb@TiDB_PD bin]$ ./tidb-server -V
Git Commit Hash: 365e4ab491b683a69c2004f30b1ae4f86256e2ad
Git Commit Branch: master
UTC Build Time:  2017-08-16 01:24:27
```

### PR DESCRIPTION
**Pull request by mxlxm**
- change index default collation from "utf8_bin" to "A".
- show column comment. fix #4224.
- show table auto-increment. fix #3747.

### CODE REVIEW

File: infoschema/tables.go [hunk 1]
```diff
@@ -712,7 +712,7 @@ func dataForColumnsInTable(schema *model.DBInfo, tbl *model.TableInfo) [][]types
 			columnDesc.Key,                    // COLUMN_KEY
 			columnDesc.Extra,                  // EXTRA
 			"select,insert,update,references", // PRIVILEGES
-			"", // COLUMN_COMMENT
+			col.Comment,                       // COLUMN_COMMENT
```
Comment (breeswish) [inline infoschema/tables.go]: I think it would be better to use `columnDesc.Comment` here.

**Comment by ngaut** [comment]
LGTM
