### PR TITLE
planner: do not cache prepared plan if optimization depends on mutable constant

### LINKED ISSUE #22167: incorrectly reuse cached plan which turns outer join to inner join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `ta` (
  `k` varchar(32) NOT NULL DEFAULT ' ',
  PRIMARY KEY (`k`)
);

CREATE TABLE `tb` (
  `k` varchar(32) NOT NULL DEFAULT ' ',
  `s` varchar(1) NOT NULL DEFAULT ' ',
  PRIMARY KEY (`k`)
);

insert into ta values ('aabb');

prepare stmt from "select * from ta a left join tb b on 1 where ? = 1 or b.s is not null";
set @a=2; 
set @b=1;
execute stmt using @a;
execute stmt using @b;
```

Make sure that the 'prepared plan cache' is enabled:
```
tidb> select * from information_schema.CLUSTER_CONFIG where `KEY` like '%plan-cache%enable%'; 
+------+----------------------+-----------------------------+-------+
| TYPE | INSTANCE             | KEY                         | VALUE |
+------+----------------------+-----------------------------+-------+
| tidb | 192.168.196.124:4000 | prepared-plan-cache.enabled | true  |
+------+----------------------+-----------------------------+-------+
1 row in set, 1 warning (0.00 sec)
```

### 2. What did you expect to see? (Required)
```
mysql> execute stmt using @a;
Empty set (0.00 sec)

mysql> execute stmt using @b;
+------+------+------+
| k    | k    | s    |
+------+------+------+
| aabb | NULL | NULL |
+------+------+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
tidb> execute stmt using @a;
Empty set (0.00 sec)

tidb> execute stmt using @b;
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```
tidb> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1957-g7c8171956
Edition: Community
Git Commit Hash: 7c817195688833291fcabf01b0ab372170f19347
Git Branch: master
UTC Build Time: 2021-01-05 02:41:17
GoVersion: go1.15.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #22167 

Problem Summary:
Incorrectly reuse cached plan which turns outer join to inner join.

### What is changed and how it works?

What's Changed & How it Works:
`EvaluateExprWithNull` is used in several optimizations such as converting outer join to inner join. If the result of `EvaluateExprWithNull` depends on parameters of execute statement, whether the optimizations can be used is affected by the parameters. When optimizing a prepared plan, if `expr` passed into `EvaluateExprWithNull` contains mutable constant, we still do optimization but do not cache the plan.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests a

- Unit test
- Integration test

### Release note 

- fix a bug about incorrectly reuse cached plan

### CODE REVIEW

File: planner/core/common_plans.go [hunk 1]
```diff
@@ -374,7 +374,7 @@ REBUILD:
 	e.names = names
 	e.Plan = p
 	_, isTableDual := p.(*PhysicalTableDual)
-	if !isTableDual && prepared.UseCache {
+	if !isTableDual && prepared.UseCache && !stmtCtx.OptimDependOnMutableConst {
```
Comment (qw4990) [inline planner/core/common_plans.go:377]: Nice. It seems all places that use `ContainMutableConst` should be modified. We can only modify `EvaluateExprWithNull` in this PR and change all other places later in another PR.

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
PTAL @eurekaka

**Review by ti-srebot — APPROVED** [review]
