### PR TITLE
disttask: update error to subtasks properly

### LINKED ISSUE #44440: ddl: create unique index stuck when tidb_enable_dist_task='on'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
bV5EMUZu4E

### 2. What did you expect to see? (Required)
duplicate key error
### 3. What did you see instead (Required)
stuck
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #44440

Problem Summary:

Previously, the error reported in `InitSubtaskExecEnv` is not handled. The scheduler keeps running the "pending" subtasks and it finally causes the dead loop.

### What is changed and how it works?

- When `scheduler.Run` reports an error, we update it to one of the subtask.
- Fix the rollback logic to prevent removing `reorgCtx` twice. Otherwise it may panic in the goroutine spawned by `executeDistGlobalTask`.
- Load the whole global task in `probeTask` to make it updated as possible.
- Refine the interface method `UpdateGlobalTaskAndAddSubTasks`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: disttask/framework/scheduler/scheduler.go [hunk 1]
```diff
@@ -45,7 +45,8 @@ type InternalSchedulerImpl struct {
 
 	mu struct {
 		sync.RWMutex
-		err error
+		err     error
+		handled bool
```
Comment (wjhuang2016) [inline disttask/framework/scheduler/scheduler.go:49]: Please add a comment for `handled`

Comment (tangenta) [reply disttask/framework/scheduler/scheduler.go:50]: Done.

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by wjhuang2016 — APPROVED** [review]
