### PR TITLE
session: fix auto commit variable change effect on transaction commit

### LINKED ISSUE #36581: autocommit handles process issues
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

set autocommit = ON;
begin;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test.t1;
+-----+
| id  |
+-----+
| 590 |
+-----+
1 row in set (0.01 sec)

mysql> update test.t1 set id = id+1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from test.t1;
+-----+
| id  |
+-----+
| 591 |
+-----+
1 row in set (0.01 sec)

mysql> set autocommit = ON;
Query OK, 0 rows affected (0.01 sec)

mysql> rollback;
### 2. What did you expect to see? (Required)
consistent with mysql
select * from test.t1;
+-----+
| id  |
+-----+
| 590 |
+-----+
### 3. What did you see instead (Required)
select * from test.t1;
+-----+
| id  |
+-----+
| 591 |
+-----+
1 row in set (0.01 sec)
### 4. What is your TiDB version? (Required)

Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #36581 

Problem Summary:

### What is changed and how it works?

When changing the value of the session variable `auto-commit`, the implicit commit for ongoing transactions should happen only when it's changed from off to on. 

### Check List

Tests 

- [ ] Unit test

Side effects

Documentation

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the auto-commit mode change related transaction commit behaviours.
```

### CODE REVIEW

**Review by ekexium — APPROVED** [review]

File: session/session_test/session_test.go [hunk 1]
```diff
@@ -3656,15 +3656,49 @@ func TestAutocommit(t *testing.T) {
...
 
-	// TODO: MySQL compatibility for setting global variable.
-	// tk.MustExec("begin")
-	// tk.MustExec("insert into t values (42)")
-	// tk.MustExec("set @@global.autocommit = 1")
-	// tk.MustExec("rollback")
-	// tk.MustQuery("select count(*) from t where id = 42").Check(testkit.Rows("0"))
-	// Even the transaction is rollbacked, the set statement succeed.
-	// tk.MustQuery("select @@global.autocommit").Rows("1")
+	// When the transaction is committed because of switching mode, the session set statement shold succeed.
```
Comment (jackysp) [inline session/session_test/session_test.go:3670]:
```suggestion
	// When the transaction is committed because of switching mode, the session set statement should succeed.
```

**Comment by hawkingrei** [comment]
```
    executor_txn_test.go:334: 
        	Error Trace:	executor_txn_test.go:334
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestTxnSavepoint0
        	Messages:   	txn_mode: optimistic,idx: 26, struct { sql string; sps []string; err string }{sql:"set autocommit=1", sps:[]string(nil), err:""}
```

**Comment by cfzjywxk** [comment]
@crazycs520 
Please take a look if the savepoint behaviors would be affected.

**Review by crazycs520 — APPROVED** [review]
