### PR TITLE
expression: fix substring_index() gets wrong result for uint64 index.

### LINKED ISSUE #28077: Substring_index() gets wrong result for uint64 index.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551615);
select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551614);
select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551613);
```

### 2. What did you expect to see? (Required)

```
MySQL [test]> select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551615);
+-------------------------------------------------------------------------+
| substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551615) |
+-------------------------------------------------------------------------+
| aaa.bbb.ccc.ddd.eee.fff.ggg                                             |
+-------------------------------------------------------------------------+
1 row in set (0.000 sec)

MySQL [test]> select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551614);
+-------------------------------------------------------------------------+
| substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551614) |
+-------------------------------------------------------------------------+
| aaa.bbb.ccc.ddd.eee.fff.ggg                                             |
+-------------------------------------------------------------------------+
1 row in set (0.000 sec)

MySQL [test]> select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551613);
+-------------------------------------------------------------------------+
| substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551613) |
+-------------------------------------------------------------------------+
| aaa.bbb.ccc.ddd.eee.fff.ggg                                             |
+-------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

### 3. What did you see instead (Required)

```
[tidb]> select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551615);
+-------------------------------------------------------------------------+
| substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551615) |
+-------------------------------------------------------------------------+
| ggg                                                                     |
+-------------------------------------------------------------------------+
1 row in set (0.000 sec)

[tidb]> select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551614);
+-------------------------------------------------------------------------+
| substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551614) |
+-------------------------------------------------------------------------+
| fff.ggg                                                                 |
+-------------------------------------------------------------------------+
1 row in set (0.000 sec)

[tidb]> select substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551613);
+-------------------------------------------------------------------------+
| substring_index("aaa.bbb.ccc.ddd.eee.fff.ggg",'.',18446744073709551613) |
+-------------------------------------------------------------------------+
| eee.fff.ggg                                                             |
+-------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

### 4. What is your TiDB version? (Required)

all version.

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #28077 

Problem Summary: When index is bigger than MaxInt64, it will cause overflow. And the behavior is not compatible with mysql.

### What is changed and how it works?

What's Changed: When index bigger than MaxInt64, it will return the whole string

### Check List 

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note 

```release-note
For compatible with mysql, substring_index will returns whole string when index is bigger than MaxInt64.
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @morgo @xhebox 
PTAL

**Review by morgo — APPROVED** [review]

File: expression/builtin_string.go [hunk 1]
```diff
@@ -1364,6 +1364,11 @@ func (b *builtinSubstringIndexSig) evalString(row chunk.Row) (d string, isNull b
 	if len(delim) == 0 {
 		return "", false, nil
 	}
+	// when count > MaxInt64, returns whole string.
+	c, ok := b.args[2].(*Constant)
```
Comment (mmyj) [inline expression/builtin_string.go:1368]: In this case
```
select substring_index('aaa.bbb.ccc.ddd.eee.fff.ggg', '.', 18446744073709551615 - 1 + id)
from (select 1 as id) as t1
where id = 1;
```
the result is `ggg`, because of the type of `b.args[2]` is a plus function.

btw, don't forget`builtinSubstringIndexSig.vecEvalString`.

**Comment by mmyj** [comment]
The result is difference between mysql 5.7 and mysql 8.
What version should tidb to be compatibled?
```
MySQL root@192.168.204.128:(none)> select version()                                                                 as ver,
                                ->        substring_index('aaa.bbb.ccc.ddd.eee.fff.ggg', '.', 18446744073709551615) as v15,
                                ->        substring_index('aaa.bbb.ccc.ddd.eee.fff.ggg', '.', 18446744073709551614) as v14,
                                ->        substring_index('aaa.bbb.ccc.ddd.eee.fff.ggg', '.', 18446744073709551613) as v13;
+--------+-----+---------+-------------+
| ver    | v15 | v14     | v13         |
+--------+-----+---------+-------------+
| 5.7.33 | ggg | fff.ggg | eee.fff.ggg |
+--------+-----+---------+-------------+

MySQL root@192.168.204.128:(none)> select version()                                                                 as ver,
                                ->        substring_index('aaa.bbb.ccc.ddd.eee.fff.ggg', '.', 18446744073709551615) as v15,
                                ->        substring_index('aaa.bbb.ccc.ddd.eee.fff.ggg', '.', 18446744073709551614) as v14,
                                ->        substring_index('aaa.bbb.ccc.ddd.eee.fff.ggg', '.', 18446744073709551613) as v13;
+--------+-----------------------------+-----------------------------+-----------------------------+
| ver    | v15                         | v14                         | v13                         |
+--------+-----------------------------+-----------------------------+-----------------------------+
| 8.0.23 | aaa.bbb.ccc.ddd.eee.fff.ggg | aaa.bbb.ccc.ddd.eee.fff.ggg | aaa.bbb.ccc.ddd.eee.fff.ggg |
+--------+-----------------------------+-----------------------------+-----------------------------+
```

**Comment by wshwsh12** [comment]
> @wshwsh12 The result is difference between mysql 5.7 and mysql 8.
> What version should tidb to be compatibled in this case?

I think we should follow mysql8.0.23..  The result is reasonable.

File: expression/builtin_string.go (hunk 1 above)
Comment (Defined2014) [reply expression/builtin_string.go:1368]: Updated, PTAL. Thx

Comment (mmyj) [reply expression/builtin_string.go:1368]: The following case which using  scalar evaluate way still be failed.
```
	tk.Se.GetSessionVars().EnableVectorizedExpression = false
	tk.MustQuery(`select substring_index('aaa.bbb.ccc.ddd.eee', '.', 18446744073709551615 - 1 + id) from (select 1 as id) as t1`).Check(testkit.Rows(`aaa.bbb.ccc.ddd.eee`))
	tk.MustQuery(`select substring_index('aaa.bbb.ccc.ddd.eee', '.', -18446744073709551615 - 1 + id) from (select 1 as id) as t1`).Check(testkit.Rows(`aaa.bbb.ccc.ddd.eee`))
	tk.Se.GetSessionVars().EnableVectorizedExpression = true
```

Expression has two ways to evaluate value, vectorized and scalar.  You can use session var `session.GetSessionVars().EnableVectorizedExpression` to control to use which way.

Comment (mmyj) [reply expression/builtin_string.go:1368]: Should we use `mysql.HasUnsignedFlag(b.args[2].GetType().Flag)` like `vecEvalString`?

File: expression/integration_test.go [hunk 2]
```diff
@@ -998,12 +998,18 @@ func (s *testIntegrationSuite2) TestStringBuiltin(c *C) {
...
 	result = tk.MustQuery(`select substring_index(null, '.', 1), substring_index('www.pingcap.com', null, 1), substring_index('www.pingcap.com', '.', null)`)
 	result.Check(testkit.Rows("<nil> <nil> <nil>"))
 
+	// for substring_index with overflow
+	tk.MustQuery(`select substring_index('xyz', 'abc', 9223372036854775808)`).Check(testkit.Rows(`xyz`))
+	tk.MustQuery(`select substring_index("aaa.bbb.ccc.ddd.eee",'.',18446744073709551613);`).Check(testkit.Rows(`aaa.bbb.ccc.ddd.eee`))
+	tk.MustQuery(`select substring_index("aaa.bbb.ccc.ddd.eee",'.',-18446744073709551613);`).Check(testkit.Rows(`aaa.bbb.ccc.ddd.eee`))
+	tk.MustQuery(`select substring_index('aaa.bbb.ccc.ddd.eee', '.', 18446744073709551615 - 1 + id) from (select 1 as id) as t1`).Check(testkit.Rows(`aaa.bbb.ccc.ddd.eee`))
+	tk.MustQuery(`select substring_index('aaa.bbb.ccc.ddd.eee', '.', -18446744073709551615 - 1 + id) from (select 1 as id) as t1`).Check(testkit.Rows(`aaa.bbb.ccc.ddd.eee`))
+
```
Comment (mmyj) [inline expression/integration_test.go:1012]: We need to more test cases to ensure both of vectorized and scalar function are fixed.

File: expression/builtin_string.go (hunk 1 above)
Comment (Defined2014) [reply expression/builtin_string.go]: Done, PTAL

Comment (mmyj) [reply expression/builtin_string.go]: It's OK to me. PTAL @wshwsh12 @xhebox.

**Comment by Defined2014** [comment]
/cc @wjhuang2016 
PTAL

**Comment by Defined2014** [comment]
/cc @wshwsh12 
PTAL

**Review by wjhuang2016 — COMMENTED** [review]
Please address mmyj's comment.

**Comment by Defined2014** [comment]
> Please address mmyj's comment.

Already followed, forgot close the comment. :(

**Review by wjhuang2016 — APPROVED** [review]

**Comment by wshwsh12** [comment]
Does this pr need cherry-pick?
