### PR TITLE
planner: invalidate cached plan if no UnionScan for tables that need it (#15429)

### LINKED ISSUE #14969: prepare plan cache is broken across transaction boundary
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
mysql> create table t(a int not null);
Query OK, 0 rows affected (0.01 sec)

mysql> prepare stmt from "select * from t where a > ?";
Query OK, 0 rows affected (0.00 sec)

mysql> set @p = 0;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @p;
Empty set (0.01 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values(1);
Query OK, 1 row affected (0.00 sec)

mysql> execute stmt using @p;
Empty set (0.00 sec)

mysql> rollback;
Query OK, 0 rows affected (0.00 sec)
```

2. What did you expect to see?

The second `execute` should return `1`.

3. What did you see instead?

It returns nothing, because it reuses the plan without `UnionScan`. Note that, to reproduce this bug, you'd better have enough free memory, otherwise the plan inserted into cache may be removed to reduce memory usage.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
master: 0f9a973e96a442c14a9f292fd2d329491a014518
```

### PR DESCRIPTION
**Pull request by winoros**
Cherry-pick PR
---

### What problem does this PR solve?

Issue Number: close #14969 

Problem Summary:
Plan cache mechanism is broken across transaction boundary, i.e, when UnionScan is needed for tables.

### What is changed and how it works?

What's Changed:

Collect `TableInfo` and whether it has been built `UnionScan` during plan building, and store this map into `StatementContext`, then this map is further stored into LRUCache when the plan is put into cache. In `getPhysicalPlan`, if the cached plan contains no `UnionScan` for any query table which has been modified in the transaction, invalidate this cached plan and build a new one.

How it Works:

It can solve cases where the table needs `UnionScan` but the plan doesn't contain one, for cases where the table does not need `UnionScan` but the plan contains one, it does not impact result, so I don't invalidate those plans for a higher cache hit ratio.

### Related changes

N/A

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more MEM: an additional small map is stored in plan cache for each plan

### Release note 
- Fix wrong result for some cached plans used in transaction.

### CODE REVIEW

**Review by eurekaka — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: planner/core/common_plans.go [hunk 1]
```diff
@@ -227,17 +227,28 @@ func (e *Execute) getPhysicalPlan(ctx context.Context, sctx sessionctx.Context,
 	if prepared.UseCache {
 		cacheKey = NewPSTMTPlanCacheKey(sessionVars, e.ExecID, prepared.SchemaVersion)
```
Comment (lzmhhh123) [inline planner/core/common_plans.go:228]: Why not move the `TblInfo2UnionScan` to `PlanCacheKey`?

**Review by jebter — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
