### PR TITLE
ddl: add `lease not found` and `deadline exceed` to retryable errors

### LINKED ISSUE #56550: add index failed with error "Error 1105 (HY000): etcdserver: requested lease not found" when injection pd leader network partition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、tidb_enable_dist_task='on' 
2、run sysbench
3、add index for one table
4、injection pd leader network partition 
[tidb-0.log.zip](https://github.com/user-attachments/files/17337137/tidb-0.log.zip)
[tidb-1.log.zip](https://github.com/user-attachments/files/17337140/tidb-1.log.zip)

### 2. What did you expect to see? (Required)
add index failed with error "Error 1105 (HY000): etcdserver: requested lease not found"

add index failed at 2024-10-02 17:47:22: Error 1105 (HY000): etcdserver: requested lease not found
operatorLogs:
[2024-10-02 17:43:21] ###### start adding index
ALTER TABLE `sbtest1` ADD INDEX `index_test_1727862201803`(`c`)
[2024-10-02 17:43:21] ###### wait for ddl job finish

### 3. What did you see instead (Required)
add index success

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.4.0-alpha-325-g74034d4
Edition: Community
Git Commit Hash: 74034d4ac243b3c14dbf5f8a9edb92e740da4212
Git Branch: HEAD
UTC Build Time: 2024-09-30 12:15:59
GoVersion: go1.21.13
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-10-02T14:15:43.671+0800

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #56550

Problem Summary:

```
[2024/10/02 17:46:51.687 +08:00] [INFO] [info.go:1001] ["get key failed"] [key=/tidb/server/info] [error="context deadline exceeded"]
[2024/10/02 17:46:52.841 +08:00] [WARN] [manager.go:536] ["close session error"] [error="etcdserver: requested lease not found"]
[2024/10/02 17:46:52.841 +08:00] [ERROR] [backfilling_operators.go:962] ["import error"] [task-id=120028] [subtask-id=120055] [category=ddl] [error="etcdserver: requested lease not found"]
[2024/10/02 17:46:52.841 +08:00] [INFO] [backend.go:352] ["engine close start"] [category=ddl-ingest] [engineTag=sbtest1:35] [engineUUID=dd035f55-b760-5f2e-b67a-4e79ffec0f3d]
[2024/10/02 17:46:52.842 +08:00] [INFO] [backend.go:354] ["engine close completed"] [category=ddl-ingest] [engineTag=sbtest1:35] [engineUUID=dd035f55-b760-5f2e-b67a-4e79ffec0f3d] [takeTime=860.297µs] []
[2024/10/02 17:46:52.842 +08:00] [INFO] [backend.go:413] ["cleanup start"] [category=ddl-ingest] [engineTag=sbtest1:35] [engineUUID=dd035f55-b760-5f2e-b67a-4e79ffec0f3d]
[2024/10/02 17:46:52.948 +08:00] [INFO] [reorg.go:451] ["run reorg job wait timeout"] [category=ddl] ["wait time"=5s] ["total added row count"=70003100]
[2024/10/02 17:46:52.949 +08:00] [INFO] [job_worker.go:981] ["schema version doesn't change"] [category=ddl] [jobID=430]
[2024/10/02 17:46:52.956 +08:00] [INFO] [job_worker.go:763] ["run DDL job"] [category=ddl] [jobID=430] [conn=3544189572] [job="ID:430, Type:add index, State:running, SchemaState:write reorganization, SchemaID:358, TableID:245, RowCount:70003100, ArgLen:0, start time: 2024-10-02 17:43:21.782 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:452948709115691080, Version: v1, UniqueWarnings:0"]
[2024/10/02 17:46:52.960 +08:00] [INFO] [index.go:1211] ["index backfill state running"] [category=ddl] ["job ID"=430] [table=sbtest1] ["ingest mode"=true] [index=index_test_1727862201803]
```

This is introduced by #56184.

### What changed and how does it work?

Add "lease not found" and "deadline exceed" to retryable errors.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/owner/manager.go [hunk 1]
```diff
@@ -530,6 +530,11 @@ func AcquireDistributedLock(
 		}
 		return false, nil
 	})
+	failpoint.Inject("mockAcquireDistLockFailed", func(val failpoint.Value) {
+		if ok := val.(bool); ok {
+			err = errors.Errorf("requested lease not found")
+		}
+	})
```
Comment (D3Hunter) [inline pkg/owner/manager.go:537]:
```suggestion
	failpoint.Inject("mockAcquireDistLockFailed", func() {
		err = errors.Errorf("requested lease not found")
	})
```

File: pkg/ddl/index.go [hunk 2]
```diff
@@ -1267,6 +1267,12 @@ func errorIsRetryable(err error, job *model.Job) bool {
 	if job.ErrorCount+1 >= variable.GetDDLErrorCountLimit() {
 		return false
 	}
+	errMsg := err.Error()
```
Comment (D3Hunter) [inline pkg/ddl/index.go:1270]: can this part call isRetryableError?

Comment (tangenta) [reply pkg/ddl/index.go:1274]: https://github.com/pingcap/tidb/pull/56630/commits/53627b28cb694ee80f95c0a265b05b7c43f0deb3

File: pkg/owner/manager.go (hunk 1 above)
Comment (tangenta) [reply pkg/owner/manager.go]: https://github.com/pingcap/tidb/pull/56630/commits/53627b28cb694ee80f95c0a265b05b7c43f0deb3

**Review by D3Hunter — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
