### PR TITLE
Lightning: increase backoff if split fails

### LINKED ISSUE #49517: Lightning: split backoff is not long enough, and fail when EBS BR disabled region split
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run EBS BR while lightning is running. It might fail lightning if BR suspends region split for more than 1 - 2 min. 

### 2. What did you expect to see? (Required)
Lightning to not fail if region split are suspended because of EBS BR
### 3. What did you see instead (Required)
Lightning failed
### 4. What is your TiDB version? (Required)
6.5

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What problem does this PR solve?

Issue Number: close #49517

Problem Summary:
Lightning job is failing intermittently after enable BR on prod clusters because of batch split failure. During the backup process, BR temporarily disables the schedulers for a period of 1-2 minutes. However, the Lightning job, which does not have a backoff mechanism, continues to retry the process for up to 5 times without pausing or spacing out the retries.
### What changed and how does it work?
i am adding a exponential back off before each retry and now it will retry upto 930 seconds before if fails the job
### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects
NO
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation
NO
- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/local/local.go [hunk 1]
```diff
@@ -1129,6 +1129,8 @@ func (local *Backend) prepareAndSendJob(
 		needSplit = true
 	})
 	logger := log.FromContext(ctx).With(zap.String("uuid", engine.ID())).Begin(zap.InfoLevel, "split and scatter ranges")
+	// we are going to do max backoff of 15 min 30 second
+	backOffTime := 30 * time.Second
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/local/local.go:1133]: init backoff is too large for transient error, and there's no max-backoff

**Comment by D3Hunter** [comment]
some background about this pr: https://github.com/pingcap/tidb/issues/49517#issuecomment-1862018888

**Comment by D3Hunter** [comment]
there are already backoff in region split
https://github.com/pingcap/tidb/blob/0719329ee71f6aef85fdaaf1193c370af936a4db/br/pkg/lightning/backend/local/localhelper.go#L171-L174

**Comment by mittalrishabh** [comment]
> there are already backoff in region split， just not long enough
> 
> https://github.com/pingcap/tidb/blob/0719329ee71f6aef85fdaaf1193c370af936a4db/br/pkg/lightning/backend/local/localhelper.go#L171-L174

It is only for 4 seconds. BR can suspend split from 60 seconds to 10 min. And i don't want to increase this backoff time as it is going to add backoff in each region split which will be very expensive.

File: br/pkg/lightning/backend/local/local.go (hunk 1 above)
Comment (mittalrishabh) [reply br/pkg/lightning/backend/local/local.go:1132]: i added the max backoff. BR can suspend split for 60 to 300 seconds

**Comment by mittalrishabh** [comment]
can you please review this PR

File: br/pkg/lightning/backend/local/local.go (hunk 1 above)
Comment (lance6716) [reply br/pkg/lightning/backend/local/local.go:1132]: I also suggest to lower the initial backoff time. If there's some transient error like network problems, sleeping 30 seconds is too long. Maybe starting from 1 second.

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: br/pkg/lightning/backend/local/local.go (hunk 1 above)
Comment (mittalrishabh) [reply br/pkg/lightning/backend/local/local.go:1132]: Lets start with 10 seconds. There is already a 1 second back off during region split and scatter.

**Comment by mittalrishabh** [comment]
Let me know if you agree with 10 second initial back off

**Review by lance6716 — APPROVED** [review]
just noticed that `SplitAndScatterRegionByRanges` has a maximum 4 seconds sleep for 8 times, so I think here we sleep 10 seconds is good.

**Comment by mittalrishabh** [comment]
I need lgtm label to checkin

**Comment by lance6716** [comment]
PTAL @D3Hunter

**Review by D3Hunter — APPROVED** [review]
