### PR TITLE
server: fix show problem for kill tidb connection (#24031)

### LINKED ISSUE #24031: Killing connections needs cooperation from the to-be-killed connection
### 1. Minimal reproduce step (Required)

- Run TiDB playground.
- Connect two sessions with `mysql --host 127.0.0.1 --port 4000 -u root -p`
- From connection A: run `SHOW PROCESSLIST` and get the connection ID of the other connection (`mysql` reports its own connection id when starting up)
- Now from connection A issue: `KILL TIDB CONNECTION <id>` where ID is the connection ID of the other connection.
- Now run `SHOW PROCESSLIST` again.

Note that this is with a single `tidb` node.

### 2. What did you expect to see? (Required)

The killed connection gone from the processlist.

### 3. What did you see instead (Required)

The other connection still being in the processlist until it tries to run a query.

Once a query like `do 1` is attempted on connection B the connection is gone from the processlist and connection B shows `ERROR 2013 (HY000): Lost connection to MySQL server during query`

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.0.0
Edition: Community
Git Commit Hash: bdac0885cd11bdf571aad9353bfc24e13554b91c
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-04-06 16:36:29
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by yiwen92**
### What problem does this PR solve?

Issue Number: close #24031

Problem Summary:
Customer cannot be noticed with a killed session, which still stay in processlist info shown as normal sessions.

### What is changed and how it works?

If a session has been killed by another session, it will not be showed in show processlist query.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
https://github.com/pingcap/automated-tests/pull/881
- [X] Manual test (add detailed scripts or steps below)
Before:
middle_img_v2_693a49bf-abe0-45fe-8163-89b2f7b1fd0g

After fix:
image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix kill tidb connection problem
```

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -685,6 +685,8 @@ func (s *Server) getTLSConfig() *tls.Config {
 func killConn(conn *clientConn) {
 	sessVars := conn.ctx.GetSessionVars()
 	atomic.StoreUint32(&sessVars.Killed, 1)
+	// 'Kill' status can be showed in Command/Info field when show processlist
+	conn.ctx.SetProcessInfo("this session is being killed", time.Now(), mysql.ComProcessKill, 0)
```
Comment (morgo) [inline server/server.go:689]: Ideally, for MySQL compatibility the `Info` column is not overwritten. This helps you see what is being actively killed. The State should also say "Killed" instead of autocommit.

For #24031, there are really two issues:
1. Update the status for connections which have been "killed" so that it is more accurate.
2. Change the `wait_timeout` to be a loop, so the connection which is being killed can cleanup faster.

This fixes issue (1), but we should also fix (2) to consider #24031 resolved.

Comment (yiwen92) [reply server/server.go:689]: thx for your review, and do we need design doc for fix (2)?

**Comment by yiwen92** [comment]
@bb7133 @tiancaiamao Please review, thx.

**Review by morgo — APPROVED** [review]
There is some risk that "killed connections" that are not shown could still be consuming a fair amount of memory, and this makes it less transparent to users what the cause is. But it's also an existing problem, since background threads are not well instrumented. It is not typical that a user will have a very high count of killed connections, if we receive bug reports we can advise them to lower the `wait_timeout`.

So there is some risk, but overall the change LGTM so I think we should proceed with it.

**Comment by yiwen92** [comment]
@dveeden PTAL. Thx!

**Comment by bb7133** [comment]
@yiwen92 Please add a test case for your change.

**Review by dveeden — COMMENTED** [review]
Could this lead to a situation where a killed connection still owns locks or other things that might block other sessions?

**Comment by morgo** [comment]
> Could this lead to a situation where a killed connection still owns locks or other things that might block other sessions?

Yes I think it could happen. This sounds like a deal breaker too :(

**Comment by yiwen92** [comment]
> Could this lead to a situation where a killed connection still owns locks or other things that might block other sessions?

Firstly, this change will not affect any thing expect show processlist print info. Then for this concern, we don't receive related issue raised by user for now, maybe @tiancaiamao can give more comments here.

**Comment by morgo** [comment]
> > Could this lead to a situation where a killed connection still owns locks or other things that might block other sessions?
> 
> Firstly, this change will not affect any thing expect show processlist print info. Then for this concern, we don't receive related issue raised by user for now, maybe @tiancaiamao can give more comments here.

Yes, it is an existing problem - but I think the issue is more about transparency. The MySQL behavior is that a connection first appears as killed in the processlist, and then it is removed when it is actually killed (and resources + locks are freed).

The current behavior in TiDB is that a killed connection lingers in the processlist and does not update its status. It is also finally killed much later (waiting on a timeout). This could create problems when a user is trying to debug, and they do not account for killed sessions which are not truly killed.

**Comment by yiwen92** [comment]
> @yiwen92 Please add a test case for your change.

an integration test was added in https://github.com/pingcap/automated-tests/pull/881

**Comment by tiancaiamao** [comment]
> > Could this lead to a situation where a killed connection still owns locks or other things that might block other sessions?
> 
> Yes I think it could happen. This sounds like a deal breaker too :(

Well, this is a bug if it really happens. If we found such kind of bug or any user report a bug to us, we need to figure out why and fix the bug.

Our promise to the user is, he killed a session, then he doesn't see the killed session, it's killed, right? **Even the resource is not released immediately, or even the query continue for a while,  it will (and should) be done eventually** ... If a user observe that the kill doesn't take effect (the query still running for a long time...) then its our bug.

Some common situations are: a query eat up the memory, or a query use up tikv coprocessor resource, or a query just takes too long ... the user want to kill it.
If we display something like "the killing is still in process" ... it doesn't really solve the problem 
... it's not something the user really want... he would be confused and report another issue: I kill the query and why TiDB still OOM? then we still need to fix the bug ...

So my point is, the user doesn't really care about the internal state or willing to know why, display "the killing is still in process" is not what he expected ... and we deliver what he wants and ... fix bugs :trollface:

**Review by tiancaiamao — APPROVED** [review]

**Comment by morgo** [comment]
I've discussed this with everyone: we will approve it for now because the goal is to cherry pick to 5.3. We will work on an additional fix for master to clean up killed connections faster.
