### PR TITLE
executor,util: write slow query to slow log no matter what log level

### LINKED ISSUE #30309: TiDB doesn't log any slow log if log.level >= "error"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Deploy a nightly cluster with config below:
```toml
[log]
level = "error"
slow-threshold = 0
```
2. Execute any query.
3. See whether there is the `tidb_slow_query.log` file.

### 2. What did you expect to see? (Required)

slow logs show.

### 3. What did you see instead (Required)

No slow logs.

### 4. What is your TiDB version? (Required)

[v5.1-v5.3], nightly

### PR DESCRIPTION
**Pull request by TonsnakeLin**
### What problem does this PR solve?

Issue Number: close #30309

Problem Summary:

### What is changed and how it works?
The slow log uses the default log level that is info level. 
Executor writes slow query by log.WARN methods

### Check List

Tests 

- [x] Unit test
- [ ] Integration test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by youjiali1995 — DISMISSED** [review]

**Comment by Defined2014** [comment]
Can't pass `testSlowQuery.TestSlowQuerySensitiveQuery` tests.
image

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/50581/pipeline

**Comment by SabaPing** [comment]
I think this bug has been covered by this PR https://github.com/pingcap/tidb/pull/28688 and I already added it to the 5.1 5.2 5.3 bug triage list.
Please refer to oncall issue https://internal.pingcap.net/jira/browse/ONCALL-3746

File: executor/adapter.go [hunk 1]
```diff
@@ -1022,12 +1022,12 @@ func (a *ExecStmt) LogSlowQuery(txnTS uint64, succ bool, hasMoreResults bool) {
...
 	if trace.IsEnabled() {
-		trace.Log(a.GoCtx, "details", sessVars.SlowLogFormat(slowItems))
+		trace.Log(a.GoCtx, "details", slowLog)
 	}
-	if costTime < threshold {
-		logutil.SlowQueryLogger.Debug(sessVars.SlowLogFormat(slowItems))
-	} else {
+	logutil.SlowQueryLogger.Warn(slowLog)
+	if costTime >= threshold {
 		logutil.SlowQueryLogger.Warn(sessVars.SlowLogFormat(slowItems))
```
Comment (youjiali1995) [inline executor/adapter.go:1031]:
```suggestion
```

**Comment by youjiali1995** [comment]
> I think this bug has been covered by this PR #28688 and I already added it to the 5.1 5.2 5.3 bug triage list. Please refer to oncall issue https://internal.pingcap.net/jira/browse/ONCALL-3746

Please file a bug issue on github if you want to fix a bug otherwise no one knows it's being fixed. And we use github issues for bug triage now, it's not proper to link an internal Jira issue here.

**Review by youjiali1995 — APPROVED** [review]

File: util/logutil/slow_query_logger.go [hunk 2]
```diff
@@ -32,6 +32,9 @@ func newSlowQueryLogger(cfg *LogConfig) (*zap.Logger, *log.ZapProperties, error)
 	// copy the global log config to slow log config
 	// if the filename of slow log config is empty, slow log will behave the same as global log.
 	sqConfig := cfg.Config
+	// level of the global log config doesn't affect the slow query logger which determines whether to
+	// log by execution duration.
+	sqConfig.Level = LogConfig{}.Level
```
Comment (SabaPing) [inline util/logutil/slow_query_logger.go:37]: `LogConfig{}.Level` set slowlogger to `info` level implicitly. Since `executor/adapter.go` logs slowlog with `warn()` method, this implicit setting could hide necessary information from developers.
```suggestion
	sqConfig.Level = zap.InfoLevel.String()
```

Comment (TonsnakeLin) [reply util/logutil/slow_query_logger.go:37]: Yes, I fixed the bug just like you at begin. But I talked about it with @youjiali1995 and We two think that It‘s best not to expose zap.InfoLevel here.
Anyway, I think the two fixed methods all can work.

File: executor/adapter.go [hunk 3]
```diff
@@ -1022,13 +1022,12 @@ func (a *ExecStmt) LogSlowQuery(txnTS uint64, succ bool, hasMoreResults bool) {
 	if _, ok := a.StmtNode.(*ast.CommitStmt); ok {
 		slowItems.PrevStmt = sessVars.PrevStmt.String()
 	}
+	slowLog := sessVars.SlowLogFormat(slowItems)
 	if trace.IsEnabled() {
-		trace.Log(a.GoCtx, "details", sessVars.SlowLogFormat(slowItems))
+		trace.Log(a.GoCtx, "details", slowLog)
```
Comment (breeswish) [inline executor/adapter.go:1027]: Does this mean that if we set the log level to error then slow query will not be recorded any more?

File: util/logutil/slow_query_logger.go (hunk 2 above)
Comment (breeswish) [reply util/logutil/slow_query_logger.go:37]: I would prefer to explicitly indicate that the default log level is INFO, and slow log will always use WARN to log so that it is always printed out.

Otherwise as a reader I will have no idea about how slow log will be outputted. What do you think? @youjiali1995

Comment (youjiali1995) [reply util/logutil/slow_query_logger.go:37]: Using the default value indicates slow logger doesn't care about log level. I would like to delete the `Level` field of the config if I could. 

There is a test to cover the constraint that the default log level is less than warn level.

**Review by SabaPing — APPROVED** [review]
LGTM.

**Review by djshow832 — APPROVED** [review]
