### PR TITLE
fix(ddl): invalid InvolvingSchemaInfo for AlterTableMode and RefreshM…

### LINKED ISSUE #62200: involvedSchemaInfo is invalid for AlterTableMode and RefreshMeta
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

there are no explicit set or schema/table name set
https://github.com/pingcap/tidb/blob/339f07ae8f2ba406abc7f4757ffcce918cc86a56/pkg/ddl/executor.go#L7076-L7084
https://github.com/pingcap/tidb/blob/339f07ae8f2ba406abc7f4757ffcce918cc86a56/pkg/ddl/executor.go#L5769-L5777
```
[2025/07/03 16:44:33.813 +00:00] [ERROR] [wait_group_wrapper.go:178] ["panic in the wait group"] [recover="assert failed, InvolvingSchemaInfo should be like an enumerate type: model.InvolvingSchemaInfo{Database:\"\", Table:\"\", Policy:\"\", ResourceGroup:\"\", Mode:0}"] [stack="github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1.1
  pkg/util/wait_group_wrapper.go:178
runtime.gopanic
  GOROOT/src/runtime/panic.go:791
github.com/pingcap/tidb/pkg/util/intest.doPanic
  pkg/util/intest/assert_common.go:58
github.com/pingcap/tidb/pkg/util/intest.doAssert
  pkg/util/intest/assert_common.go:30
github.com/pingcap/tidb/pkg/util/intest.Assert
  pkg/util/intest/assert.go:25
github.com/pingcap/tidb/pkg/ddl.(*runningJobs).checkRunnable
  pkg/ddl/ddl_running_jobs.go:166
github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).loadAndDeliverJobs
  pkg/ddl/job_scheduler.go:423
github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).schedule
  pkg/ddl/job_scheduler.go:333
github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).scheduleLoop
  pkg/ddl/job_scheduler.go:268
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1
  pkg/util/wait_group_wrapper.go:181"] [stack="github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1.1
  pkg/util/wait_group_wrapper.go:178
runtime.gopanic
  GOROOT/src/runtime/panic.go:791
github.com/pingcap/tidb/pkg/util/intest.doPanic
  pkg/util/intest/assert_common.go:58
github.com/pingcap/tidb/pkg/util/intest.doAssert
  pkg/util/intest/assert_common.go:30
github.com/pingcap/tidb/pkg/util/intest.Assert
  pkg/util/intest/assert.go:25
github.com/pingcap/tidb/pkg/ddl.(*runningJobs).checkRunnable
  pkg/ddl/ddl_running_jobs.go:166
github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).loadAndDeliverJobs
  pkg/ddl/job_scheduler.go:423
github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).schedule
  pkg/ddl/job_scheduler.go:333
github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).scheduleLoop
  pkg/ddl/job_scheduler.go:268
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1
  pkg/util/wait_group_wrapper.go:181"]
```

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
assert fail
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by abrarr21**
### What problem does this PR solve?

Issue Number: close #62200 

Problem Summary:
An assertion failure occurs in the job scheduler due to uninitialized `InvolvingSchemaInfo` fields in DDL jobs of types `RefreshMeta` and `AlterTableMode`. This causes a panic and crash during job scheduling.

### What changed and how does it work?
Explicitly initialize `InvolvingSchemaInfo` fields (such as Database, Table, Policy, Mode) in the DDL job structs within the `RefreshMeta` and `AlterTableMode` executor functions. This ensures the job scheduler sees valid metadata and prevents the assertion failure and panic.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/executor.go [hunk 1]
```diff
@@ -7073,6 +7082,18 @@ func NewDDLReorgMeta(ctx sessionctx.Context) *model.DDLReorgMeta {
...
+	schema, ok := is.SchemaByID(args.SchemaID)
+	if !ok {
+		return infoschema.ErrDatabaseNotExists.GenWithStackByArgs(fmt.Sprintf("SchemaID: %v", args.SchemaID))
+	}
+
+	table, ok := is.TableByID(e.ctx, args.TableID)
+	if !ok {
+		return infoschema.ErrTableNotExists.GenWithStackByArgs(schema.Name, args.TableID)
+	}
+
```
Comment (JQWong7) [inline pkg/ddl/executor.go]: `RefreshMeta` is an internal DDL for BR, should not validate schema and table in infoschema

Comment (abrarr21) [reply pkg/ddl/executor.go]: Thanks for the clarification! I've removed the infoschema validations and set default values in InvolvingSchemaInfo accordingly.

File: pkg/ddl/executor.go [hunk 2]
```diff
@@ -5774,6 +5774,15 @@ func (e *executor) AlterTableMode(sctx sessionctx.Context, args *model.AlterTabl
...
 		SQLMode:        sctx.GetSessionVars().SQLMode,
+		InvolvingSchemaInfo: []model.InvolvingSchemaInfo{
+			{
+				Database:      schema.Name.O,
+				Table:         table.Meta().Name.O,
+				Policy:        "",
+				ResourceGroup: "",
+				Mode:          0,
+			},
+		},
```
Comment (D3Hunter) [inline pkg/ddl/executor.go]:
```suggestion
		InvolvingSchemaInfo: []model.InvolvingSchemaInfo{{
				Database:      schema.Name.O,
				Table:         table.Meta().Name.O,
		}},
```

File: pkg/ddl/executor.go [hunk 3]
```diff
@@ -7081,6 +7090,15 @@ func (e *executor) RefreshMeta(sctx sessionctx.Context, args *model.RefreshMetaA
...
 		SQLMode:        sctx.GetSessionVars().SQLMode,
+		InvolvingSchemaInfo: []model.InvolvingSchemaInfo{
+			{
+				Database:      "",
+				Table:         "",
+				Policy:        "",
+				ResourceGroup: "",
+				Mode:          0,
+			},
+		},
```
Comment (D3Hunter) [inline pkg/ddl/executor.go]:
```suggestion
		InvolvingSchemaInfo: []model.InvolvingSchemaInfo{{
				Database:      "",
				Table:         "",
		}},
```

File: pkg/ddl/executor.go (hunk 1 above)
Comment (D3Hunter) [reply pkg/ddl/executor.go]: @River2000i why not validate, it might not a already dropped table?

Comment (JQWong7) [reply pkg/ddl/executor.go]: BR will drop/create table. If BR create table in log restore, the table is not exists in infoschema cache(since BR restore table meta kv directly instead of DDL). If BR call `RefreshMeta` after create table, it will failure. As design, BR will do all table/schema validation.

File: pkg/ddl/executor.go [hunk 4]
```diff
@@ -7081,6 +7087,12 @@ func (e *executor) RefreshMeta(sctx sessionctx.Context, args *model.RefreshMetaA
 		BinlogInfo:     &model.HistoryInfo{},
 		CDCWriteSource: sctx.GetSessionVars().CDCWriteSource,
 		SQLMode:        sctx.GetSessionVars().SQLMode,
+		InvolvingSchemaInfo: []model.InvolvingSchemaInfo{
+			{
+				Database: "",
+				Table:    "",
```
Comment (D3Hunter) [inline pkg/ddl/executor.go]:
```suggestion
				Database: model.InvolvingAll,
				Table:    model.InvolvingAll,
```
as in previous comment, for `RefreshMeta` the db/table might not exist anymore, we don't know which table is involved, so maybe block all DDLs

Comment (D3Hunter) [reply pkg/ddl/executor.go]: and please add comment on why do it

Comment (abrarr21) [reply pkg/ddl/executor.go]: Done

File: pkg/ddl/executor.go [hunk 5]
```diff
@@ -5774,6 +5774,12 @@ func (e *executor) AlterTableMode(sctx sessionctx.Context, args *model.AlterTabl
 		BinlogInfo:     &model.HistoryInfo{},
 		CDCWriteSource: sctx.GetSessionVars().CDCWriteSource,
 		SQLMode:        sctx.GetSessionVars().SQLMode,
+		InvolvingSchemaInfo: []model.InvolvingSchemaInfo{
+			{
+				Database: schema.Name.O,
+				Table:    table.Meta().Name.O,
```
Comment (D3Hunter) [inline pkg/ddl/executor.go]:
```suggestion
				Database: schema.Name.L,
				Table:    table.Meta().Name.L,
```

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/ddl/executor.go (hunk 5 above)
Comment (abrarr21) [reply pkg/ddl/executor.go]: Done

**Review by D3Hunter — APPROVED** [review]

**Comment by abrarr21** [comment]
Hey @D3Hunter, This PR need one more lgtm. Whom should I ask for it and also please let me know if is there anything else thats need to be done in PR.

**Comment by JQWong7** [comment]
@wjhuang2016 PTAL~

**Comment by abrarr21** [comment]
> Hey @D3Hunter, This PR need one more lgtm. Whom should I ask for it and also please let me know if is there anything else thats need to be done in PR.

@you06 @hawkingrei

**Review by tangenta — APPROVED** [review]
