### PR TITLE
ddl: process temp global index correctly

### LINKED ISSUE #56535: unexpected assertion failed using global index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Here is the log from our internal test schrddl. 
```
2024/10/09 16:48:19 ddl.go:212: [0;31m[fatal] [error] [instance 16] ERROR: Error 8141: assertion failed: key: 7480000000000000ba5f69800000000000000307800029e4698b0200, assertion: Exist, start_ts: 453113916671131764, existing start ts: 0, existing commit ts: 0
/build/ddl/dml_ops.go:52: Error when executing SQL: delete from `b5d472af` where not( IsNull( `b5d472af`.`56b0971e` ) ) or `b5d472af`.`56b0971e` in ( 1444517 ,824880 ) 
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
assertion failed
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #56535

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
test with schrddl, no error report.
```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/realtikvtest/addindextest3/ingest_test.go [hunk 1]
```diff
@@ -700,3 +700,29 @@ func TestIssue55808(t *testing.T) {
...
+	var i atomic.Int32
+	i.Store(3)
+	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/ddl/writeLocalExec", func(bool) {
+		tk2 := testkit.NewTestKit(t, store)
+		tmp := i.Add(1)
+		_, err := tk2.Exec(fmt.Sprintf("insert into test.t values (%d, %d)", tmp, tmp))
+		assert.Nil(t, err)
+	})
+	tk.MustExec("alter table t add index idx_1(b), add unique index idx_2(b) global;")
+	testfailpoint.Disable(t, "github.com/pingcap/tidb/pkg/ddl/writeLocalExec")
```
Comment (tangenta) [inline tests/realtikvtest/addindextest3/ingest_test.go:721]:
```suggestion
```

This will be done in `t.Cleanup()`

File: pkg/ddl/ingest/integration_test.go [hunk 2]
```diff
@@ -424,3 +424,30 @@ func TestAddIndexIngestPartitionCheckpoint(t *testing.T) {
 	require.Equal(t, 20, int(rowCnt.Load()))
 	tk.MustExec("admin check table t;")
 }
+
+func TestAddGlobalIndexInIngest(t *testing.T) {
+	store := realtikvtest.CreateMockStoreAndSetup(t)
```
Comment (tangenta) [inline pkg/ddl/ingest/integration_test.go:429]:
```suggestion
	store := testkit.CreateMockStore(t)
```

File: pkg/ddl/index.go [hunk 3]
```diff
@@ -2549,7 +2555,11 @@ func getNextPartitionInfo(reorg *reorgInfo, t table.PartitionedTable, currPhysic
 		if len(pi.AddingDefinitions) == 0 {
 			// case 1
 			// Simply AddIndex, without any partitions added or dropped!
-			pid, err = findNextPartitionID(currPhysicalTableID, pi.Definitions)
+			if reorg.mergingTmpIdx && currPhysicalTableID == t.Meta().ID {
+				pid = pi.Definitions[0].ID
```
Comment (tangenta) [inline pkg/ddl/index.go:2559]: I don't understand why the first partition ID is used for global index, could you explain it?

Comment (Defined2014) [reply pkg/ddl/index.go:2559]: If the current Physical id is the table id, the next Physical id should be the first partition id.

Comment (Defined2014) [reply pkg/ddl/index.go:2561]: We cannot distinguish whether this reorg only has the global index, so the partition-related parts must also be scanned.

File: pkg/ddl/index.go [hunk 4]
```diff
@@ -2220,9 +2220,15 @@ func (w *worker) addTableIndex(t table.Table, reorgInfo *reorgInfo) error {
 	if tbl, ok := t.(table.PartitionedTable); ok {
 		var finish bool
 		for !finish {
-			p := tbl.GetPartition(reorgInfo.PhysicalTableID)
-			if p == nil {
-				return dbterror.ErrCancelledDDLJob.GenWithStack("Can not find partition id %d for table %d", reorgInfo.PhysicalTableID, t.Meta().ID)
+			var p table.PhysicalTable
+			if tbl.Meta().ID == reorgInfo.PhysicalTableID {
+				//nolint:forcetypeassert
+				p = t.(table.PhysicalTable)
```
Comment (tangenta) [inline pkg/ddl/index.go:2226]:
```suggestion
				p = t.(table.PhysicalTable) // global index
```

**Review by tangenta — COMMENTED** [review]
Rest LGTM

**Review by tangenta — APPROVED** [review]

File: pkg/ddl/index.go [hunk 5]
```diff
@@ -2220,9 +2220,15 @@ func (w *worker) addTableIndex(t table.Table, reorgInfo *reorgInfo) error {
 	if tbl, ok := t.(table.PartitionedTable); ok {
 		var finish bool
 		for !finish {
-			p := tbl.GetPartition(reorgInfo.PhysicalTableID)
-			if p == nil {
-				return dbterror.ErrCancelledDDLJob.GenWithStack("Can not find partition id %d for table %d", reorgInfo.PhysicalTableID, t.Meta().ID)
+			var p table.PhysicalTable
+			if tbl.Meta().ID == reorgInfo.PhysicalTableID {
+				//nolint:forcetypeassert
+				p = t.(table.PhysicalTable) // global index
```
Comment (mjonss) [inline pkg/ddl/index.go:2226]: Why not having a proper check, like `p, ok = t.(table.PhysicalTable)` + error check?

File: pkg/ddl/ingest/integration_test.go [hunk 6]
```diff
@@ -424,3 +424,30 @@ func TestAddIndexIngestPartitionCheckpoint(t *testing.T) {
 	require.Equal(t, 20, int(rowCnt.Load()))
 	tk.MustExec("admin check table t;")
 }
+
+func TestAddGlobalIndexInIngest(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	defer ingesttestutil.InjectMockBackendMgr(t, store)()
+
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test;")
```
Comment (mjonss) [inline pkg/ddl/ingest/integration_test.go:433]: (minor nit-pick) No need for `;` at the end of the statements.

File: pkg/ddl/reorg.go [hunk 7]
```diff
@@ -882,6 +883,17 @@ func getReorgInfo(ctx *ReorgContext, jobCtx *jobContext, rh *reorgHandler, job *
...
 		if mergingTmpIdx {
+			for _, element := range elements {
+				if !bytes.Equal(element.TypeKey, meta.IndexElementKey) {
+					continue
+				}
+				// If has a global index in elements, need start process at `tblInfo.ID`
+				// because there are some temporary global indexes prefixed with table ID.
+				idxInfo := model.FindIndexInfoByID(tblInfo.Indices, element.ID)
+				if idxInfo.Global {
+					pid = tblInfo.ID
```
Comment (mjonss) [inline pkg/ddl/reorg.go:894]: Is there always only a single index/element with IndexElementKey here?
What happens for `alter table t add index idx_1(b), add unique index idx_2(c) global`, where the indexes have different columns?
I'm not very familiar with the ingest add index code, but for non-index it will add all indexes in one go, one partition at a time. Is this the same for the mergingTmpIdx?

**Review by mjonss — COMMENTED** [review]
LGTM, but I wonder about what happens when you add multiple indexes with a mix of global and non-global indexes for different columns?

File: pkg/ddl/reorg.go (hunk 7 above)
Comment (Defined2014) [reply pkg/ddl/reorg.go:894]: For multi-schema change, we will combine add indexes into one reorg job. So the elements will greatter than 1. See https://github.com/pingcap/tidb/pull/47135 for details.

File: pkg/ddl/index.go [hunk 8]
```diff
@@ -2549,7 +2557,13 @@ func getNextPartitionInfo(reorg *reorgInfo, t table.PartitionedTable, currPhysic
 		if len(pi.AddingDefinitions) == 0 {
 			// case 1
 			// Simply AddIndex, without any partitions added or dropped!
-			pid, err = findNextPartitionID(currPhysicalTableID, pi.Definitions)
+			if reorg.mergingTmpIdx && currPhysicalTableID == t.Meta().ID {
+				// If the current Physical id is the table id,
+				// the next Physical id should be the first partition id.
+				pid = pi.Definitions[0].ID
```
Comment (mjonss) [inline pkg/ddl/index.go:2563]: Should we loop through `reorg.elements` and match against `t.indices` to find the corresponding index (with the correct ID and state) and if every index in the elements are Global, set `pid = 0` to avoid searching for local temporary indexes?

File: pkg/ddl/reorg.go (hunk 7 above)
Comment (mjonss) [reply pkg/ddl/reorg.go:894]: Ah, if there is any global index in elements, it will first do all global indexes by reading from the TableID, then it will do local indexes by looping over each partitionID and all the elements.

So do we also loop over all partitions even if there only are global indexes added?

Comment (Defined2014) [reply pkg/ddl/reorg.go:894]: Updated, fixed in `getNextPartitionInfo` function

**Review by mjonss — APPROVED** [review]
LGTM

File: pkg/ddl/index.go [hunk 9]
```diff
@@ -2549,7 +2557,30 @@ func getNextPartitionInfo(reorg *reorgInfo, t table.PartitionedTable, currPhysic
 		if len(pi.AddingDefinitions) == 0 {
 			// case 1
 			// Simply AddIndex, without any partitions added or dropped!
-			pid, err = findNextPartitionID(currPhysicalTableID, pi.Definitions)
+			if reorg.mergingTmpIdx && currPhysicalTableID == t.Meta().ID {
+				// If the current Physical id is the table id,
+				// 1. All indexes are global index, the next Physical id should be the first partition id.
+				// 2. Not all indexes are global index, return 0.
```
Comment (mjonss) [inline pkg/ddl/index.go:2563]:
```suggestion
				// 1. All elements are global index, we are done, return 0.
				// 2. Not all indexes are global index, we need to continue with the non-global ones,
				//    starting with the first partition, so the next Physical id should be the first partition id..
```
