### PR TITLE
br: fix unit test

### LINKED ISSUE #59925: fix br/pkg/task unit tests
## Enhancement
fix `br/pkg/task` unit tests

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #59925

Problem Summary:
fix `br/pkg/task` unit tests
### What changed and how does it work?
fix `br/pkg/task` unit tests
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/task/restore_test.go [hunk 1]
```diff
@@ -755,19 +845,37 @@ func TestAdjustTablesToRestoreAndCreateTableTracker(t *testing.T) {
 			)
 			require.NoError(t, err)
 
-			for dbID, tableIDs := range tc.expectedTableIDs {
-				for _, tableID := range tableIDs {
-					require.True(t, cfg.PiTRTableTracker.ContainsTableId(dbID, tableID))
+			/*
```
Comment (BornChanger) [inline br/pkg/task/restore_test.go:848]: why not remove the commented code?

Comment (Leavrth) [reply br/pkg/task/restore_test.go:848]: fixed by another PR.

**Review by BornChanger — APPROVED** [review]
