### PR TITLE
ddl notifier: use pagination for SELECT to reduce memory usage

### LINKED ISSUE #58368: TiDB OOM after created about 6.5M tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiDB is 16c32g(about 27.3G usable to the pod), we are creating 500K DB with 9M tables total with `split-table` disabled, after created about 6.5M table, ddl owner OOM
Image

### 2. What did you expect to see? (Required)
keep running
### 3. What did you see instead (Required)
OOM
### 4. What is your TiDB version? (Required)
master aec0fc58bde1b6f5bdff46dabcf229ebad9ab1de

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #58368

Problem Summary:

### What changed and how does it work?

as title. refine the `Store.List`.

```golang
// Store is the (de)serialization and persistent layer.
type Store interface {
...
	// List will start a transaction of given session and read all schema changes
	// through a ListResult. The ownership of session is occupied Store until CloseFn
	// is called.
	List(ctx context.Context, se *sess.Session) ListResult
}

// ListResult is the result stream of a List operation.
type ListResult interface {
	// Read tries to decode at most `len(changes)` SchemaChange into given slices. It
	// returns the number of schemaChanges decoded, 0 means no more schemaChanges.
	//
	// Note that the previous SchemaChange in the slice will be overwritten when call
	// Read.
	Read(changes []*SchemaChange) (int, error)
}
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/notifier/store.go [hunk 1]
```diff
@@ -106,34 +122,75 @@ func (t *tableStore) DeleteAndCommit(
...
+	se                  *sess.Session
+	sqlTemplate         string
+	maxReturnedDDLJobID int64
+	maxReturnedSubJobID int64
+}
+
+// Read implements ListResult interface.
+func (r *listResult) Read(changes []*SchemaChange) (int, error) {
+	if r.maxReturnedDDLJobID == 0 && r.maxReturnedSubJobID == 0 {
+		err := r.se.Begin(r.ctx)
```
Comment (tiancaiamao) [inline pkg/ddl/notifier/store.go:158]: Is there a commit or rollback?

Comment (tiancaiamao) [reply pkg/ddl/notifier/store.go:158]: This API design looks scary to me.
Maybe you can use some like 

````
type CloseFn func()
List(ctx context.Context, se *sess.Session) (ListResult, CloseFn)
```

And wrap the session rollback to `CloseFn` 

If you just use this it doesn't help: 

```
res, _ = List()
```

but if you use this and forget to handle the defer, then lint check may remind you variable `done` is not used 

```
res, done := List() 
// defer done()
```

I'm not sure this work, but maybe you can take a try.

File: pkg/ddl/notifier/subscribe.go [hunk 2]
```diff
@@ -166,61 +166,82 @@ func (n *DDLNotifier) start() {
...
-				if !goerr.Is(err2, ErrNotReadyRetryLater) {
-					logutil.Logger(ctx).Error("Error processing change",
-						zap.Int64("ddlJobID", change.ddlJobID),
-						zap.Int64("multiSchemaChangeSeq", change.multiSchemaChangeSeq),
-						zap.Stringer("handler", handlerID),
-						zap.Error(err2))
+	changes := make([]*SchemaChange, ProcessEventsBatchSize)
+
+	for {
+		count, err2 := result.Read(changes)
```
Comment (tiancaiamao) [inline pkg/ddl/notifier/subscribe.go:197]: Why not let read return `[]*SchemaChange` directly?
Return `count` and use `changes[:count]` is just a unnecessary detour

Comment (lance6716) [reply pkg/ddl/notifier/subscribe.go:197]: It's like an `io.Reader` calling convention. Caller can reuse the previous results. Because we are in 1M tables project, I'm afraid that returning 1M `[]*SchemaChange` (it also has internal pointers like `TableInfo`) will add pressure to GC. 

Though it's less common, I think this package / function is the only caller of `ListResult.Read`. Other developers will not modify this package and will not be confused by it.

However I notice that I use `json.Unmarshal` on an non-empty object, not sure the leftover of the object will be overwritten or causes some problems. I'll check it tomorrow.

Comment (Rustin170506) [reply pkg/ddl/notifier/subscribe.go:197]: What was your test result?

Comment (tiancaiamao) [reply pkg/ddl/notifier/subscribe.go:197]: >　pass-in slices so caller can reuse the previous results

Yes, I mean the same thing, just that the code can be write as:

```
func f(changes []*SchemaChange) []*SchemaChange {
     ret := changes[:0]
     ret = append(ret, xxx)
     return ret
}
```

Anyway, this is just some personal taste, so you can choose to accept it or not.

**Review by tiancaiamao — APPROVED** [review]

File: pkg/ddl/notifier/subscribe.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/notifier/subscribe.go:197]: > What was your test result?

I didn't test it yet 😂 I hope other colleague can help check it. Theoretically there's no big query now.

> func f(changes []*SchemaChange) []*SchemaChange {

In this new signature, the batch size of one `Read` is not obvious when input is `nil`, or it seems like an `append` where the slice will be grown and batch size is not be limited. Your suggestion is like `EncodeBytes` but here we want to control the batch size as well as reuse buffer.

File: pkg/ddl/notifier/store.go [hunk 3]
```diff
@@ -106,34 +126,85 @@ func (t *tableStore) DeleteAndCommit(
...
+	for i, row := range rows {
+		if changes[i] == nil {
+			changes[i] = new(SchemaChange)
+		}
+		if changes[i].event == nil {
+			changes[i].event = new(SchemaChangeEvent)
+		}
+		if changes[i].event.inner == nil {
+			changes[i].event.inner = new(jsonSchemaChangeEvent)
+		}
```
Comment (Rustin170506) [inline pkg/ddl/notifier/store.go:192]: How about:
```go
// Add constructor function
func NewSchemaChange() *SchemaChange {
    return &SchemaChange{
        event: &SchemaChangeEvent{
            inner: &jsonSchemaChangeEvent{},
        },
    }
}

// Replace existing code
if changes[i] == nil {
    changes[i] = NewSchemaChange()
}
```

**Review by Rustin170506 — APPROVED** [review]
Better to verify if this can fix the memory consumption issue. 

Thanks! :shipit:

/hold

File: pkg/ddl/notifier/store.go (hunk 3 above)
Comment (Rustin170506) [reply pkg/ddl/notifier/store.go:192]: Or do you mean there is a case that `changes[i]` is not nil, but the event or the inner is nil?

Comment (lance6716) [reply pkg/ddl/notifier/store.go:192]: just to improve robustness, I don't want to assume caller uses some kind of `SchemaChange`.

I'll test the OOM problem soon

**Comment by lance6716** [comment]
/unhold

due to test resource limit, I can't create a test cluster before the coming version release. So I plan to test the effect later, and don't cherry-pick to v8.5.1 before we get the test result
