### PR TITLE
executor: accelerate TestUpdateScanningHandles and TestIssue20658 and TestParallelStreamAggGroupConcat

### LINKED ISSUE #24130: reduce the execution time of `go test -race` for package executor
## Development Task

Update: 2021-04-20 15:35 CST

``` shell
$ make failpoint-enable
$ cd executor
$ GO111MODULE=on go test -v -vet=off -p 5 -timeout 20m -race  
```

The execution time of the above commands is optimized.
git hash | execution time
-- | --
bc4bde76eb7081731646e2dbde1bed37ce121f62 (before)| 769.181s
fa39b79006c1d35cb1ba0cdafc1febd78fa36f50 (after)| 319.095s

The top 3 most execution time test cases in different test suite are are listed as the following:
``` sql
+------------------+-----------------------------------------+-----------+--------------------+---------+
| suiteName        | testCaseName                            | execTime  | sumExecTime        | ranking |
+------------------+-----------------------------------------+-----------+--------------------+---------+
| testSuite5       | TestShowVar                             |  9.193000 |  74.55300000000003 |       1 |
| testSuite5       | TestAdminRecoverIndex                   |  7.043000 |  74.55300000000003 |       2 |
| testSuite5       | TestAdminCleanupIndexForPartitionTable  |  6.651000 |  74.55300000000003 |       3 |
| testSuite1       | TestAnalyzeParameters                   | 16.355000 |             69.984 |       1 |
| testSuite1       | TestClusterIndexAnalyze                 | 13.896000 |             69.984 |       2 |
| testSuite1       | TestAnalyzePartition                    |  6.401000 |             69.984 |       3 |
| testSuiteJoin3   | TestVectorizedMergeJoin                 | 30.432000 |              68.59 |       1 |
| testSuiteJoin3   | TestVectorizedShuffleMergeJoin          | 12.236000 |              68.59 |       2 |
| testSuiteJoin3   | TestSubquery                            | 11.849000 |              68.59 |       3 |
| testSuite3       | TestAdminCheckPartitionTableFailed      | 12.173000 |  63.17900000000002 |       1 |
| testSuite3       | TestAdmin                               |  4.496000 |  63.17900000000002 |       2 |
| testSuite3       | TestGrantDBScope                        |  3.158000 |  63.17900000000002 |       3 |
| tiflashTestSuite | TestMppExecution                        | 35.770000 |             62.286 |       1 |
| tiflashTestSuite | TestPartitionTable                      |  7.973000 |             62.286 |       2 |
| tiflashTestSuite | TestMppApply                            |  6.540000 |             62.286 |       3 |
| testSuite        | TestApplyMultiColumnType                |  7.333000 | 59.210000000000015 |       1 |
| testSuite        | TestApplyWithOtherOperators             |  6.549000 | 59.210000000000015 |       2 |
| testSuite        | TestApplyColumnType                     |  6.236000 | 59.210000000000015 |       3 |
| testSuite7       | TestUpdateScanningHandles               | 11.999000 | 59.004000000000005 |       1 |
| testSuite7       | TestInsertCalculatedValue               |  8.051000 | 59.004000000000005 |       2 |
| testSuite7       | TestUnionScanForMemBufferReader         |  7.323000 | 59.004000000000005 |       3 |
| testSuite2       | TestInsertReorgDelete                   | 30.686000 |             58.191 |       1 |
| testSuite2       | TestAddIndexPriority                    |  7.792000 |             58.191 |       2 |
| testSuite2       | TestMergeJoin                           |  5.135000 |             58.191 |       3 |
| testSerialSuite  | TestPrepareStmtAfterIsolationReadChange | 40.288000 | 56.957000000000015 |       1 |
| testSerialSuite  | TestSplitRegionTimeout                  |  3.171000 | 56.957000000000015 |       2 |
| testSerialSuite  | TestRandomPanicAggConsume               |  3.001000 | 56.957000000000015 |       3 |
| testSuite4       | TestWriteListColumnsPartitionTable1     |  4.991000 |  55.63199999999998 |       1 |
| testSuite4       | TestWriteListPartitionTable1            |  4.552000 |  55.63199999999998 |       2 |
| testSuite4       | TestWriteListPartitionTable2            |  4.286000 |  55.63199999999998 |       3 |
| testSuiteP1      | TestUpdateClustered                     | 13.861000 |  52.21700000000002 |       1 |
| testSuiteP1      | TestGrantGlobal                         |  4.005000 |  52.21700000000002 |       2 |
| testSuiteP1      | TestAllowInvalidDates                   |  3.737000 |  52.21700000000002 |       3 |
| testSuite8       | TestAdminCheckTable                     | 14.238000 | 49.489000000000004 |       1 |
| testSuite8       | TestInsertOnDuplicateKey                | 10.569000 | 49.489000000000004 |       2 |
| testSuite8       | TestShardRowIDBits                      |  7.053000 | 49.489000000000004 |       3 |
| testSuiteAgg     | TestAggregation                         | 13.911000 |  43.95099999999999 |       1 |
| testSuiteAgg     | TestIssue20658                          |  5.525000 |  43.95099999999999 |       2 |
| testSuiteAgg     | TestGroupConcatAggr                     |  2.874000 |  43.95099999999999 |       3 |
| testSuite6       | TestCreateView                          |  6.680000 |             43.533 |       1 |
| testSuite6       | TestRole                                |  4.711000 |             43.533 |       2 |
| testSuite6       | TestAlterTableModifyColumn              |  3.558000 |             43.533 |       3 |
| testSuiteJoin2   | TestJoinCast                            | 15.504000 |             37.941 |       1 |
| testSuiteJoin2   | TestJoin                                | 12.205000 |             37.941 |       2 |
| testSuiteJoin2   | TestNullEmptyAwareSemiJoin              | 10.232000 |             37.941 |       3 |
| testSuiteJoin1   | TestUsing                               | 11.967000 |  37.92399999999999 |       1 |
| testSuiteJoin1   | TestIndexLookupJoin                     |  7.180000 |  37.92399999999999 |       2 |
| testSuiteJoin1   | TestInSubquery                          |  5.017000 |  37.92399999999999 |       3 |
| testSuiteP2      | TestUnion                               | 15.535000 |  37.43899999999998 |       1 |
| testSuiteP2      | TestCurrentTimestampValueSelection      |  2.170000 |  37.43899999999998 |       2 |
| testSuiteP2      | TestHistoryRead                         |  1.592000 |  37.43899999999998 |       3 |
| testFastAnalyze  | TestFastAnalyze                         | 10.861000 | 24.791999999999998 |       1 |
| testFastAnalyze  | TestAnalyzeFastSample                   |  7.057000 | 24.791999999999998 |       2 |
| testFastAnalyze  | TestFastAnalyzeRetryRowCount            |  6.874000 | 24.791999999999998 |       3 |
+------------------+-----------------------------------------+-----------+--------------------+---------+
20 rows in set (0.01 sec)
```

There are some test cases we may refine further:
- [x] | testSuiteJoin3   | TestVectorizedMergeJoin                 | 30.432000 |              68.59 |       1 |
- [x] | tiflashTestSuite | TestMppExecution                        | 35.770000 |             62.286 |       1 | @hanfei1991 
- [x] | testSuite2       | TestInsertReorgDelete                   | 30.686000 |             58.191 |       1 | @lysu 
- [x] | testSerialSuite  | TestPrepareStmtAfterIsolationReadChange | 40.288000 | 56.957000000000015 |       1 | @lzmhhh123 

<details>
  <summary> Archived 2021-04-19 </summary>
  When run `go test -v -vet=off -p 5 -timeout 20m -race` on my Mac, it'll be broken because of running out of time.

The top 10 most time-consuming test functions are listed as the following, we can refine most of them to accelerate the execution time.

- [x] show_test.go:1233:testSuite5.TestShowVar	339.521 https://github.com/pingcap/tidb/pull/24131
- [x] union_scan_test.go:336:testSuite7.TestUpdateScanningHandles	211.422
- [x] aggregate_test.go:1271:testSuiteAgg.TestIssue20658	79.173
- [x] aggregate_test.go\:1234\:testSuiteAgg.TestParallelStreamAggGroupConcat	37.414
- [ ] tiflash_test.go:136:tiflashTestSuite.TestMppExecution	35.742
- [ ] merge_join_test.go:728:testSuiteJoin3.TestVectorizedMergeJoin	34.125
- [ ] insert_test.go:248:testSuite2.TestInsertReorgDelete	27.665
- [ ] merge_join_test.go:825:testSuiteJoin3.TestVectorizedShuffleMergeJoin	22.180
- [ ] sort_test.go:29:testSerialSuite1.TestSortInDisk	20.755
- [ ] analyze_test.go:166:testSuite1.TestAnalyzeParameters	19.487

</details>

### PR DESCRIPTION
**Pull request by mmyj**
### What problem does this PR solve?

Issue Number: #24130 

Problem Summary:

### What is changed and how it works?

1. using batch insert instead of  insert one by one
2. reduce the unit test size, from 10000 to 1000

Before:
```
go test -v -vet=off -p 5 -timeout 20m -race -check.f TestIssue20658
ok      github.com/pingcap/tidb/executor        18.889s
go test -v -vet=off -p 5 -timeout 20m -race -check.f TestParallelStreamAggGroupConcat
ok      github.com/pingcap/tidb/executor        12.697s
go test -v -vet=off -p 5 -timeout 20m -race -check.f  TestUpdateScanningHandles
ok      github.com/pingcap/tidb/executor        12.697s
```

After
```
go test -v -vet=off -p 5 -timeout 20m -race -check.f TestIssue20658
ok      github.com/pingcap/tidb/executor        4.868s
go test -v -vet=off -p 5 -timeout 20m -race -check.f TestParallelStreamAggGroupConcat
ok      github.com/pingcap/tidb/executor        4.358s
go test -v -vet=off -p 5 -timeout 20m -race -check.f  TestUpdateScanningHandles
ok      github.com/pingcap/tidb/executor        5.962s
```

### Release note 

- No release note

### CODE REVIEW

File: executor/aggregate_test.go [hunk 1]
```diff
@@ -1237,9 +1237,15 @@ func (s *testSuiteAgg) TestParallelStreamAggGroupConcat(c *C) {
 	tk.MustExec("drop table if exists t;")
 	tk.MustExec("CREATE TABLE t(a bigint, b bigint);")
 
-	for i := 0; i < 10000; i++ {
-		tk.MustExec("insert into t values(?, ?);", rand.Intn(100), rand.Intn(100))
+	var insertSQL string
+	for i := 0; i < 1000; i++ {
```
Comment (XuHuaiyu) [inline executor/aggregate_test.go:1241]: Should we set the init_chunk_size and max_chunk_size to small values since we want to test the parallel scenario in this test?

File: executor/aggregate_test.go [hunk 2]
```diff
@@ -1283,9 +1289,15 @@ func (s *testSuiteAgg) TestIssue20658(c *C) {
 
 	tk.MustExec("drop table if exists t;")
 	tk.MustExec("CREATE TABLE t(a bigint, b bigint);")
-	for i := 0; i < 10000; i++ {
-		tk.MustExec("insert into t values (?, ?);", rand.Intn(100), rand.Intn(100))
+	var insertSQL string
+	for i := 0; i < 1000; i++ {
```
Comment (XuHuaiyu) [inline executor/aggregate_test.go:1293]: ditto

**Review by wshwsh12 — APPROVED** [review]
