### PR TITLE
ddl: fix anonymous indexes on the `primary` column

### LINKED ISSUE #14243: The results of anonymous indexes created using `alter table ... add index` on the` primary` column is inconsistent with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Case 1:
```
create table tt(`primary` int);
alter table tt add index (`primary`);
show create table tt;
```
Case 2:
```
create table tt(`primary` int, b int);
alter table tt add index (`primary`);
alter table tt add primary key(b);
```

2. What did you expect to see?
Case 1:
```
mysql> show create table tt;
+-------+--------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                             |
+-------+--------------------------------------------------------------------------------------------------------------------------+
| tt    | CREATE TABLE `tt` (
  `primary` int(11) DEFAULT NULL,
  KEY `primary_2` (`primary`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+-------+--------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
Case 2:
```
Query OK, 0 rows affected (0.03 sec)
```

3. What did you see instead?
Case 1:
```
tidb> show create table tt;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                  |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| tt    | CREATE TABLE `tt` (
  `primary` int(11) DEFAULT NULL,
  KEY `primary` (`primary`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

Case 2:
```
ERROR 1068 (42000): Multiple primary key defined
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v4.0.0-alpha-1183-g55e540738-dirty
Git Commit Hash: 55e54073862a6b8d7aead548550cdfe8d426f5af

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve? 
Fix #14243(The results of anonymous indexes created using `alter table ... add index` on the` primary` column is inconsistent with MySQL).

### What is changed and how it works?
Special handling of anonymous indexes on the `primary` column.
Remove the duplicate test case.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Fix the result of anonymous indexes created using `alter table ... add index` on the` primary` column.

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -3415,6 +3415,10 @@ func getAnonymousIndex(t table.Table, colName model.CIStr) model.CIStr {
 	id := 2
 	l := len(t.Indices())
 	indexName := colName
+	if strings.EqualFold(indexName.L, strings.ToLower(mysql.PrimaryKeyName)) {
```
Comment (wjhuang2016) [inline ddl/ddl_api.go]: `ToLower` is redundant since `EqualFold` is case insensitive.

File: ddl/db_integration_test.go [hunk 2]
```diff
@@ -1257,56 +1257,6 @@ func (s *testIntegrationSuite3) TestResolveCharset(c *C) {
 	c.Assert(tbl.Meta().Charset, Equals, "binary")
 }
 
-func (s *testIntegrationSuite2) TestAddAnonymousIndex(c *C) {
```
Comment (wjhuang2016) [inline ddl/db_integration_test.go]: Why remove these tests?

Comment (zimulala) [reply ddl/db_integration_test.go]: It's duplicated with `(s *testDBSuite3) TestAddAnonymousIndex`. This is written in the PR description.
