### PR TITLE
domain: fix unstable test TestRepairTable

### LINKED ISSUE #53667: Unstable test TestRepairTable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Can be found in our CI, this is a flaky test

### 2. What did you expect to see? (Required)

CI stable

### 3. What did you see instead (Required)

```
--- FAIL: TestRepairTable (1.05s)
    util.go:36:
                Error Trace:        /Users/tangliu/eng/tidb/pkg/testkit/external/util.go:36
                                                            /Users/tangliu/eng/tidb/pkg/ddl/repair_table_test.go:137
                Error:              Received unexpected error:
                                    [schema:1146]Table 'test.origin' doesn't exist
                Test:               TestRepairTable
FAIL
run all tasks takes 16m14.210871666s
panic: runtime error: index out of range [28] with length 25

goroutine 1 [running]:
[github.com/pingcap/failpoint/code.Restorer.Restore](http://github.com/pingcap/failpoint/code.Restorer.Restore)({{0x140000a0078?, 0x1400038a0d0?}})
        /Users/tangliu/eng/go/pkg/mod/[github.com/pingcap/failpoint@v0.0.0-20240527053858-9b3b6e34194a/code/restorer.go:114](http://github.com/pingcap/failpoint@v0.0.0-20240527053858-9b3b6e34194a/code/restorer.go:114) +0x49c
main.restoreFiles({0x140000b0020, 0x492, 0x140000d9f28?})
        /Users/tangliu/eng/go/pkg/mod/[github.com/pingcap/failpoint@v0.0.0-20240527053858-9b3b6e34194a/failpoint-ctl/main.go:94](http://github.com/pingcap/failpoint@v0.0.0-20240527053858-9b3b6e34194a/failpoint-ctl/main.go:94) +0x5c
main.main()
        /Users/tangliu/eng/go/pkg/mod/[github.com/pingcap/failpoint@v0.0.0-20240527053858-9b3b6e34194a/failpoint-ctl/main.go:82](http://github.com/pingcap/failpoint@v0.0.0-20240527053858-9b3b6e34194a/failpoint-ctl/main.go:82) +0x4e0
```

### 4. What is your TiDB version? (Required)

master 

```
commit c9c865ced461b01b08095c760b705642c7f6c838 (HEAD -> master, origin/master, origin/HEAD)
Author: D3Hunter <jujj603@gmail.com>
Date:   Wed May 29 15:58:21 2024 +0800

    test: fix flaky test TestParallelDDL (#53636)
    
    close pingcap/tidb#39222
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #53667 

Problem Summary:

### What changed and how does it work?

The DDL of 'admin repair table' works like this:

- create a list of tables been repairing
- ddl owner publish the ddl job
- ddl worker receive ddl job, execute onRepairTable function
- repairment done, update the table info, set the DDL state to public
- remove the table from repair table list

After we set the DDL state to public, and just before the table been removed from the list,
If we trigger a full reload of infoschema, we will goto this line:

https://github.com/pingcap/tidb/blob/22c41d0e0c86ddb98dd029d49a2df038d7ac42bf/pkg/domain/domain.go#L437-L440

And tidb will skip loading this table. (but the table is public, the repairment is done in fact)

In the past, the full reload in not triggered so the bug is not exposed.
After we adding infoschema v2 to our CI, the v1 -> v2 switch could trigger a full reload, and expose this bug.

### Check List

Tests 

- [X] Unit test

After this fix, the unit test TestRepairTable become stable.

- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

File: pkg/domain/domain.go [hunk 1]
```diff
@@ -436,7 +438,14 @@ func (*Domain) fetchSchemasWithTables(schemas []*model.DBInfo, m *meta.Meta, don
 			infoschema.ConvertCharsetCollateToLowerCaseIfNeed(tbl)
 			// Check whether the table is in repair mode.
 			if domainutil.RepairInfo.InRepairMode() && domainutil.RepairInfo.CheckAndFetchRepairedTable(di, tbl) {
-				continue
+				if !tbl.State == model.StatePublic {
```
Comment (D3Hunter) [inline pkg/domain/domain.go:441]: 😓
