### PR TITLE
lightning: specify collation when parquet value to string datum

### LINKED ISSUE #38351: Lightning: Performance Regression on 6.2.0 Compared with 5.3.3 on Parquet Data Source with Strings
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Import a moderate data set into different versions of Lightning: 1) 6.2.0; 2) 5.3.3
The reproduce conditions: 
* The data format of the source is parquet
* The data set to import contains some string columns
* The table schema should set the encoding to 'binary'

### 2. What did you expect to see? (Required) 
* It takes longer time to finish the import on 6.2.0 than in 5.3.3 
* From the log, we can see the encode KV time is much longer in 6.2.0, the import KV time is roughly the same as in 5.3.3

### 3. What did you see instead (Required)
The import time on newer version of Lightning should be roughly the same as the older version

### 4. What is your TiDB version? (Required)
6.2.0

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #38351 

Problem Summary:

### What is changed and how it works?
For parquet parser, when setting a value into the string datum, use the "utf8mb4_bin" collation instead of an empty collation.  This will make the string conversion logic not report errors, thus improving the performance.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/mydump/parquet_parser.go [hunk 1]
```diff
@@ -458,7 +458,7 @@ func setDatumByString(d *types.Datum, v string, meta *parquet.SchemaElement) {
 		ts = ts.UTC()
 		v = ts.Format(utcTimeLayout)
 	}
-	d.SetString(v, "")
+	d.SetString(v, "utf8mb4_bin")
```
Comment (lance6716) [inline br/pkg/lightning/mydump/parquet_parser.go:461]: There are many places need to consider string encodings, one is string data in parquet file, the other one is string variables in the memory of lightning process which read by parquet reader. Since golang string is always  assumed utf8-encoded I think this PR is OK. But I'm not sure if parquet file has another encoding for string data and go-parquet reader wrongly cast it to golang string without encode/decode.

**Review by lance6716 — APPROVED** [review]

**Comment by dsdashun** [comment]
integration BR test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/10757/pipeline

**Review by okJiang — APPROVED** [review]
