### PR TITLE
planner: refine the codes of embeded limit of double read

### LINKED ISSUE #43528: SQL execution efficiency is low when paging is turned on
## Bug Report
After [PR 41120](https://github.com/pingcap/tidb/pull/41120/files) , when sql condition `limit` is less than 128,tidb will disable paging by default. But when the condition is  `limit 10000`, sql execution efficiency is still better paging is turned off than paging is turned on,especially when there are many regions.
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql>  CREATE TABLE `test` (`id` int(11) DEFAULT NULL,`name` varchar(100) DEFAULT NULL, KEY `idx_id` (`id`));
Query OK, 0 rows affected (0.11 sec)
mysql>  insert into test(id,name) values(1,'ssss'),(2,'ssss'),(3,'ssss'),(4,'ssss')...;
mysql>  split table test index idx_id between ("1") and ("4") regions 4;
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
```
mysql> explain analyze select * from test use index(idx_id) where id>0 order by id limit 10000;
+------------------------------------+----------+---------+-----------+------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+----------+------+
| id                                 | estRows  | actRows | task      | access object                | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | operator info                                        | memory   | disk |
+------------------------------------+----------+---------+-----------+------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+----------+------+
| Limit_12                           | 10000.00 | 10000   | root      |                              | time:162.5ms, loops:11, RRU:91.687405, WRU:0.000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | offset:0, count:10000                                | N/A      | N/A  |
| └─Projection_21                    | 10000.00 | 10240   | root      |                              | time:162.5ms, loops:10, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | test.test.id, test.test.name, test.test.repometadata | 412.6 KB | N/A  |
|   └─IndexLookUp_20                 | 10000.00 | 11024   | root      |                              | time:162.4ms, loops:11, index_task: {total_time: 38.1ms, fetch_handle: 21.3ms, build: 16.8ms, wait: 48.8µs}, table_task: {total_time: 463.5ms, num: 6, concurrency: 5}, next: {wait_index: 16.8ms, wait_table_lookup_build: 1.87ms, wait_table_lookup_resp: 140.6ms}                                                                                                                                                                                                                                                                                                                  |                                                      | 1.49 MB  | N/A  |
|     ├─Limit_19(Build)              | 10000.00 | 40000   | cop[tikv] |                              | time:16.2ms, loops:42, cop_task: {num: 4, max: 14.9ms, min: 1.22ms, avg: 4.96ms, p95: 14.9ms, max_proc_keys: 10000, p95_proc_keys: 10000, tot_proc: 13.6ms, tot_wait: 2.85ms, rpc_num: 4, rpc_time: 19.7ms, copr_cache_hit_ratio: 0.75, build_task_duration: 59.4µs, max_distsql_concurrency: 1}, tikv_task:{proc max:14ms, min:7ms, avg: 11.5ms, p80:14ms, p95:14ms, iters:56, tasks:4}, scan_detail: {total_process_keys: 10000, total_process_keys_size: 460000, total_keys: 10001, get_snapshot_time: 2.42ms, rocksdb: {key_skipped_count: 10000, block: {cache_hit_count: 15}}}  | offset:0, count:10000                                | N/A      | N/A  |
|     │ └─IndexRangeScan_17          | 10000.00 | 40000   | cop[tikv] | table:test, index:idx_id(id) | tikv_task:{proc max:14ms, min:7ms, avg: 11.5ms, p80:14ms, p95:14ms, iters:56, tasks:4}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | range:(0,+inf], keep order:true                      | N/A      | N/A  |
|     └─TableRowIDScan_18(Probe)     | 10000.00 | 23072   | cop[tikv] | table:test                   | time:409.5ms, loops:31, cop_task: {num: 5, max: 118.6ms, min: 28.6ms, avg: 60ms, p95: 118.6ms, max_proc_keys: 8976, p95_proc_keys: 8976, tot_proc: 186.4ms, tot_wait: 702.3µs, rpc_num: 5, rpc_time: 299.6ms, copr_cache_hit_ratio: 0.00, build_task_duration: 1.92ms, max_distsql_concurrency: 1}, tikv_task:{proc max:99ms, min:20ms, avg: 46.4ms, p80:99ms, p95:99ms, iters:46, tasks:5}, scan_detail: {total_process_keys: 23072, total_process_keys_size: 1015840, total_keys: 23072, get_snapshot_time: 331µs, rocksdb: {block: {cache_hit_count: 207}}}                        | keep order:false                                     | N/A      | N/A  |
+------------------------------------+----------+---------+-----------+------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+----------+------+
6 rows in set (0.16 sec)
```
### 3. What did you see instead (Required)
```
mysql> explain analyze select * from test use index(idx_id) where id>0 order by id limit 10000;
+------------------------------------+----------+---------+-----------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+----------+------+
| id                                 | estRows  | actRows | task      | access object                | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | operator info                                        | memory   | disk |
+------------------------------------+----------+---------+-----------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+----------+------+
| Limit_12                           | 10000.00 | 10000   | root      |                              | time:197.5ms, loops:11, RRU:146.568723, WRU:0.000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | offset:0, count:10000                                | N/A      | N/A  |
| └─Projection_21                    | 10000.00 | 10240   | root      |                              | time:197.4ms, loops:10, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | test.test.id, test.test.name, test.test.repometadata | 412.6 KB | N/A  |
|   └─IndexLookUp_20                 | 10000.00 | 11024   | root      |                              | time:197.3ms, loops:11, index_task: {total_time: 196.5ms, fetch_handle: 92.5ms, build: 68.6ms, wait: 35.4ms}, table_task: {total_time: 714.7ms, num: 10, concurrency: 5}, next: {wait_index: 7.39ms, wait_table_lookup_build: 1.14ms, wait_table_lookup_resp: 184.6ms}                                                                                                                                                                                                                                                                                                                        |                                                      | 3.29 MB  | N/A  |
|     ├─Limit_19(Build)              | 10000.00 | 124096  | cop[tikv] |                              | time:71.8ms, loops:126, cop_task: {num: 32, max: 31.9ms, min: 395.7µs, avg: 3.88ms, p95: 24.7ms, max_proc_keys: 10000, p95_proc_keys: 10000, tot_proc: 81.3ms, tot_wait: 4.89ms, rpc_num: 32, rpc_time: 123.4ms, copr_cache_hit_ratio: 0.47, build_task_duration: 55.7µs, max_distsql_concurrency: 1}, tikv_task:{proc max:24ms, min:0s, avg: 5.63ms, p80:11ms, p95:14ms, iters:244, tasks:32}, scan_detail: {total_process_keys: 53312, total_process_keys_size: 2452352, total_keys: 53329, get_snapshot_time: 2.2ms, rocksdb: {key_skipped_count: 53312, block: {cache_hit_count: 109}}}   | offset:0, count:10000                                | N/A      | N/A  |
|     │ └─IndexRangeScan_17          | 10000.00 | 124096  | cop[tikv] | table:test, index:idx_id(id) | tikv_task:{proc max:24ms, min:0s, avg: 5.63ms, p80:11ms, p95:14ms, iters:244, tasks:32}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | range:(0,+inf], keep order:true                      | N/A      | N/A  |
|     └─TableRowIDScan_18(Probe)     | 10000.00 | 17952   | cop[tikv] | table:test                   | time:553.2ms, loops:28, cop_task: {num: 4, max: 145ms, min: 15.6ms, avg: 72.2ms, p95: 145ms, max_proc_keys: 9184, p95_proc_keys: 9184, tot_proc: 180.8ms, tot_wait: 425.7µs, rpc_num: 4, rpc_time: 288.7ms, copr_cache_hit_ratio: 0.00, build_task_duration: 1.59ms, max_distsql_concurrency: 1}, tikv_task:{proc max:122ms, min:11ms, avg: 59ms, p80:122ms, p95:122ms, iters:36, tasks:4}, scan_detail: {total_process_keys: 17952, total_process_keys_size: 771936, total_keys: 17952, get_snapshot_time: 176.5µs, rocksdb: {block: {cache_hit_count: 160}}}                                | keep order:false                                     | N/A      | N/A  |
+------------------------------------+----------+---------+-----------+------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------+----------+------+
6 rows in set (0.21 sec)
```
### 4. What is your TiDB version? (Required)
v7.0.0
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/24636, close https://github.com/pingcap/tidb/issues/35952, close #43528

Problem Summary:

### What is changed and how it works?

We fully disabled the embedded limit for double read before.
But we can actually open it by adding one more extra projection.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/task.go [hunk 1]
```diff
@@ -897,20 +897,27 @@ func (p *PhysicalLimit) sinkIntoIndexLookUp(t task) bool {
...
 	// If the Limit is sunk into the IndexLookUp, the IndexLookUp's schema needs to be updated as well,
-	//  but updating it here is not safe, so do not sink Limit into this IndexLookUp in this case now.
+	// So we add an extra projection to solve the problem.
 	if p.Schema().Len() != reader.Schema().Len() {
-		return false
+		extraProj := PhysicalProjection{
+			Exprs: expression.Column2Exprs(p.schema.Columns),
+		}.Init(p.SCtx(), p.statsInfo(), p.blockOffset, nil)
+		extraProj.SetSchema(p.schema)
+		// If the root.p is ready a Projection. We left the optimization for the later Projection Elimination.
```
Comment (time-and-fate) [inline planner/core/task.go:916]:
```suggestion
		// If the root.p is already a Projection. We left the optimization for the later Projection Elimination.
```

**Review by time-and-fate — APPROVED** [review]
