### PR TITLE
br: remove duplicate bind info after snapshot restore

### LINKED ISSUE #46527: Duplicated records in mysql.bind_info after restoring from a full backup
### 1. Minimal reproduce step (Required)
Restore `mysql.bind_info` from backup
```
tiup br restore full --pd "127.0.0.1:2379"  --storage "s3://us-west-2-demo-bucket-backup/full/snapshot-20230830?access-key=xxxx&secret-access-key=xxxx" --filter 'mysql.bind_info'  --with-sys-table --log-file restore.log
```
Check the SQL binding info 
```
mysql> select * from mysql.bind_info where original_sql = 'builtin_pseudo_sql_for_bind_lock'; 
```

### 2. What did you expect to see? (Required)
```
mysql> select * from bind_info where original_sql = 'builtin_pseudo_sql_for_bind_lock'\G
*************************** 1. row ***************************
original_sql: builtin_pseudo_sql_for_bind_lock
    bind_sql: builtin_pseudo_sql_for_bind_lock
  default_db: mysql
      status: builtin
 create_time: 0000-00-00 00:00:00.000
 update_time: 0000-00-00 00:00:00.000
     charset:
   collation:
      source: builtin
  sql_digest: NULL
 plan_digest: NULL
*************************** 2. row ***************************
original_sql: builtin_pseudo_sql_for_bind_lock
    bind_sql: builtin_pseudo_sql_for_bind_lock
  default_db: mysql
      status: builtin
 create_time: 0000-00-00 00:00:00.000
 update_time: 0000-00-00 00:00:00.000
     charset:
   collation:
      source: builtin
  sql_digest: NULL
 plan_digest: NULL
2 rows in set (0.01 sec)

```

### 3. What did you see instead (Required)
```
mysql> select * from bind_info where original_sql = 'builtin_pseudo_sql_for_bind_lock'\G
*************************** 1. row ***************************
original_sql: builtin_pseudo_sql_for_bind_lock
    bind_sql: builtin_pseudo_sql_for_bind_lock
  default_db: mysql
      status: builtin
 create_time: 0000-00-00 00:00:00.000
 update_time: 0000-00-00 00:00:00.000
     charset:
   collation:
      source: builtin
  sql_digest: NULL
 plan_digest: NULL
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```
| Release Version: v7.3.0
Edition: Community
Git Commit Hash: 40b72e7a9a4fc9670d4c5d974dd503a3c6097471
Git Branch: heads/refs/tags/v7.3.0
UTC Build Time: 2023-08-08 09:27:28
GoVersion: go1.20.7
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
```

### LINKED ISSUE #46528: SQL bindings are not reload automatically after restore mysql.bind_info
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Restore mysql.bind_info from backup
```
tiup br restore full --pd "127.0.0.1:2379"  --storage "s3://us-west-2-demo-bucket-backup/full/snapshot-20230830?access-key=xxxx&secret-access-key=xxxx" --filter 'mysql.bind_info'  --with-sys-table --log-file restore.log
```

### 2. What did you expect to see? (Required)
After restore table, the SQL bindings are reload automatically.

### 3. What did you see instead (Required)
After restore table, the SQL bindings are not reload automatically.
```
mysql> show global bindings;
Empty set (0.00 sec)

mysql> select * from bind_info;
+----------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+---------+-------------------------+-------------------------+---------+-------------+---------+------------------------------------------------------------------+-------------+
| original_sql                                                   | bind_sql                                                                                 | default_db | status  | create_time             | update_time             | charset | collation   | source  | sql_digest                                                       | plan_digest |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+---------+-------------------------+-------------------------+---------+-------------+---------+------------------------------------------------------------------+-------------+
| builtin_pseudo_sql_for_bind_lock                               | builtin_pseudo_sql_for_bind_lock                                                         | mysql      | builtin | 0000-00-00 00:00:00.000 | 0000-00-00 00:00:00.000 |         |             | builtin | NULL                                                             | NULL        |
| builtin_pseudo_sql_for_bind_lock                               | builtin_pseudo_sql_for_bind_lock                                                         | mysql      | builtin | 0000-00-00 00:00:00.000 | 0000-00-00 00:00:00.000 |         |             | builtin | NULL                                                             | NULL        |
| select * from `sbtest` . `sbtest1` where `id` > ? and `id` < ? | SELECT * FROM `sbtest`.`sbtest1` USE INDEX (`primary`) WHERE `id` > 1000 AND `id` < 4000 | sbtest     | enabled | 2023-08-30 16:31:54.555 | 2023-08-30 16:31:54.555 | utf8mb4 | utf8mb4_bin | manual  | ee99782e1182983034ce78bbf7c46b73e047d8c9b0bfef69f49523abacbd4688 |             |
+----------------------------------------------------------------+------------------------------------------------------------------------------------------+------------+---------+-------------------------+-------------------------+---------+-------------+---------+------------------------------------------------------------------+-------------+
3 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```
| Release Version: v7.3.0
Edition: Community
Git Commit Hash: 40b72e7a9a4fc9670d4c5d974dd503a3c6097471
Git Branch: heads/refs/tags/v7.3.0
UTC Build Time: 2023-08-08 09:27:28
GoVersion: go1.20.7
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
```

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #46527

Problem Summary:
After snapshot restore, there are duplicated bind infos.
### What changed and how does it work?
execute SQL to remove duplicate bind info after snapshot restore.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

```
+-------------------------------------------+--------------------------------------------------------------+------------+---------+-------------------------+-------------------------+---------+-----------------+---------+------------------------------------------------------------------+-------------+
| original_sql                              | bind_sql                                                     | default_db | status  | create_time             | update_time             | charset | collation       | source  | sql_digest                                                       | plan_digest |
+-------------------------------------------+--------------------------------------------------------------+------------+---------+-------------------------+-------------------------+---------+-----------------+---------+------------------------------------------------------------------+-------------+
| builtin_pseudo_sql_for_bind_lock          | builtin_pseudo_sql_for_bind_lock                             | mysql      | builtin | 0000-00-00 00:00:00.000 | 0000-00-00 00:00:00.000 |         |                 | builtin | NULL                                                             | NULL        |
| select * from `test` . `t1` where `b` = ? | SELECT * FROM `test`.`t1` IGNORE INDEX (`b`) WHERE `b` = 123 | test       | enabled | 2023-11-20 16:22:22.239 | 2023-11-20 16:22:22.239 | utf8    | utf8_general_ci | manual  | 94c28782ed1110d4cf67f3a836f92d110a0ebe69113e8d9e1ff5c86523905a3e |             |
+-------------------------------------------+--------------------------------------------------------------+------------+---------+-------------------------+-------------------------+---------+-----------------+---------+------------------------------------------------------------------+-------------+
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/systable_restore.go [hunk 1]
```diff
@@ -179,15 +180,13 @@ func (rc *Client) RestoreSystemSchemas(ctx context.Context, f filter.Filter) {
...
 			tablesRestored = append(tablesRestored, tableName.L)
 		}
 	}
-	if err := rc.afterSystemTablesReplaced(tablesRestored); err != nil {
-		for _, e := range multierr.Errors(err) {
-			log.Warn("error during reconfigurating the system tables", zap.String("database", sysDB), logutil.ShortError(e))
-		}
-	}
+	err := rc.afterSystemTablesReplaced(ctx, tablesRestored)
+	return errors.Trace(err)
```
Comment (3pointer) [inline br/pkg/restore/systable_restore.go:189]: maybe `return rc.afterSystemTablesReplaced` directly

**Review by 3pointer — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]
