### PR TITLE
planner: a parition table's column UniqueID may mismatch or collide with planner's (#13490)

### LINKED ISSUE #13491: Partition pruning does not work with union.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
CREATE TABLE partition_table (x int) PARTITION BY RANGE (x) ( 
PARTITION p1 VALUES LESS THAN (100), 
PARTITION p2 VALUES LESS THAN (200) 
);
```

It works without `union`

```mysql
mysql> desc select * from partition_table where x > 100 ;
+---------------------+----------+-----------+----------------------------------------------------------------------------------------+
| id                  | count    | task      | operator info                                                                          |
+---------------------+----------+-----------+----------------------------------------------------------------------------------------+
| TableReader_8       | 3333.33  | root      | data:Selection_7                                                                       |
| └─Selection_7       | 3333.33  | cop[tikv] | gt(Column#1, 100)                                                                      |
|   └─TableScan_6     | 10000.00 | cop[tikv] | table:partition_table, partition:p2, range:[-inf,+inf], keep order:false, stats:pseudo |
+---------------------+----------+-----------+----------------------------------------------------------------------------------------+
3 rows in set (0.01 sec)
```

2. What did you expect to see?

3. What did you see instead?

But it does not work with one part of `union`.
```mysql
mysql> desc select * from partition_table where x > 100 union select * from partition_table where x > 100;
+--------------------------------+----------+-----------+----------------------------------------------------------------------------------------+
| id                             | count    | task      | operator info                                                                          |
+--------------------------------+----------+-----------+----------------------------------------------------------------------------------------+
| HashAgg_17                     | 8000.00  | root      | group by:Column#7, funcs:firstrow(Column#7)                                            |
| └─Union_18                     | 10000.00 | root      |                                                                                        |
|   ├─Union_20                   | 6666.67  | root      |                                                                                        |
|   │ ├─TableReader_23           | 3333.33  | root      | data:Selection_22                                                                      |
|   │ │ └─Selection_22           | 3333.33  | cop[tikv] | gt(Column#4, 100)                                                                      |
|   │ │   └─TableScan_21         | 10000.00 | cop[tikv] | table:partition_table, partition:p1, range:[-inf,+inf], keep order:false, stats:pseudo |
|   │ └─TableReader_26           | 3333.33  | root      | data:Selection_25                                                                      |
|   │   └─Selection_25           | 3333.33  | cop[tikv] | gt(Column#4, 100)                                                                      |
|   │     └─TableScan_24         | 10000.00 | cop[tikv] | table:partition_table, partition:p2, range:[-inf,+inf], keep order:false, stats:pseudo |
|   └─TableReader_30             | 3333.33  | root      | data:Selection_29                                                                      |
|     └─Selection_29             | 3333.33  | cop[tikv] | gt(Column#1, 100)                                                                      |
|       └─TableScan_28           | 10000.00 | cop[tikv] | table:partition_table, partition:p2, range:[-inf,+inf], keep order:false, stats:pseudo |
+--------------------------------+----------+-----------+----------------------------------------------------------------------------------------+
12 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

4a5bc928d

### PR DESCRIPTION
**Pull request by SunRunAway**
Automated cherry pick of #13490 on release-3.0.

---

### What problem does this PR solve? 

Fix #13491 
A partition table's column `UniqueID` is generated by itself using its own `SessionContext` and does not associate with planner's.
If mismatched, partition pruning does not take any effect.
If collided, partition pruning may prune extra partitions and lead wrong results.

### What is changed and how it works?

Use planner's schema to build partition expression during optimization.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 

Side effects

 - None

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Fix partition pruning when partition table working with union.

### CODE REVIEW

File: planner/core/logical_plans.go [hunk 1]
```diff
@@ -350,6 +350,10 @@ type DataSource struct {
 	isPartition     bool
 	physicalTableID int64
 	partitionNames  []model.CIStr
+
+	// TblCols contains the original columns of table before being pruned, and it
+	// is used for estimating table scan cost.
+	TblCols []*expression.Column
```
Comment (SunRunAway) [inline planner/core/logical_plans.go]: I've ported this entry from MASTER branch manually.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by ericsyh** [comment]
@SunRunAway Pls merge this PR.
