### PR TITLE
executor: fill correlated column value in late materialization filter conditions

### LINKED ISSUE #49241: Cop Apply operator will not fill correlated column value in late materialization filter condition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(id int, value int);
create table t1(id int, value int);
insert into t values(10,5),(9,5),(8,5),(7,5),(6,5),(5,5),(4,5),(3,5),(2,5),(1,5);
insert into t1 values(2,5);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
alter database set tiflash replica 1;
set tidb_allow_mpp=off;
select (select t.value from t where t.id = t1.id order by t.value limit 1) xx from t1 order by t1.value limit 5;
+------+
| xx   |
+------+
| NULL |
+------+
1 row in set (0.02 sec)
```

### 2. What did you expect to see? (Required)

```
select (select t.value from t where t.id = t1.id order by t.value limit 1) xx from t1 order by t1.value limit 5;
+------+
| xx   |
+------+
|    5 |
+------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```sql
select (select t.value from t where t.id = t1.id order by t.value limit 1) xx from t1 order by t1.value limit 5;
+------+
| xx   |
+------+
| NULL |
+------+
1 row in set (0.02 sec)
```

### 4. What is your TiDB version? (Required)

v7.1.2

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
… condition

### What problem does this PR solve?

Issue Number: close #49241

Problem Summary:

### What changed and how does it work?

tidb integration test does not support tiflash now, add test in tiflash https://github.com/pingcap/tiflash/pull/8480

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/builder.go [hunk 1]
```diff
@@ -2972,13 +2972,18 @@ func markChildrenUsedCols(outputCols []*expression.Column, childSchemas ...*expr
...
 func (*executorBuilder) corColInDistPlan(plans []plannercore.PhysicalPlan) bool {
 	for _, p := range plans {
-		x, ok := p.(*plannercore.PhysicalSelection)
-		if !ok {
-			continue
-		}
-		for _, cond := range x.Conditions {
-			if len(expression.ExtractCorColumns(cond)) > 0 {
-				return true
+		switch x := p.(type) {
```
Comment (windtalker) [inline pkg/executor/builder.go:2975]: Why mpp plan works fine?

Comment (Lloyd-Pottiger) [reply pkg/executor/builder.go:2975]: mpp returns a `MPPGather` when `buildTableReader `

https://github.com/pingcap/tidb/blob/cf23666766d03ec9c2551465fbb92e0f9bba25a2/pkg/executor/builder.go#L3414-L3435

MPPGather will always call `ConstructTreeBasedDistExec` when `ConstructDAGReq`

https://github.com/pingcap/tidb/blob/cf23666766d03ec9c2551465fbb92e0f9bba25a2/pkg/executor/internal/builder/builder_utils.go#L46-L59

For `TableReaderExecutor`, only when `e.corColInFilter = true` will call `ConstructTreeBasedDistExec`

https://github.com/pingcap/tidb/blob/cf23666766d03ec9c2551465fbb92e0f9bba25a2/pkg/executor/table_reader.go#L142-L161

**Review by windtalker — APPROVED** [review]
LGTM

**Review by SeaRise — APPROVED** [review]
lgtm

**Comment by SeaRise** [comment]
@Lloyd-Pottiger 
comment `/unhold` to merge pr.
