### PR TITLE
br: use AWS CreateSnapshots API to automic create snapshots for multiple volumes

### LINKED ISSUE #43433: br: use CreateSnapshots to create snapshots for multiple volumes
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

EBS snapshot backup and restore a tidb cluster whose TiKV has multiple volumes

### 2. What did you expect to see? (Required)

Restore succeed with consistent data

### 3. What did you see instead (Required)

Restored cluster might fail to restart due to data inconsistency

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Issue Number: close #43433 

Problem Summary:

### What is changed and how it works?

Use AWS SDK API CreateSnapshots to create snapshots for multiple volumes to make crash consistent.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. Established a real tidb cluster on tidb cloud
2. Run `bin/br backup full --type=aws-ebs --volume-file=../../built/clustermeta.txt --pd=localhost:2379 --send-credentials-to-tikv=false --storage=s3://xxxxx --s3.region=ap-northeast-1 --s3.provider=aws` command and verify snapshots are created for and only for specified EBS volumes, and tags for volumes are copied
3. Verify above logic work also for tidb cloud

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/aws/ebs.go [hunk 1]
```diff
@@ -49,66 +48,92 @@ func NewEC2Session(concurrency uint) (*EC2Session, error) {
...
-					return true
-				}
-				if strings.Contains(volumes[j].Type, "raft") {
-					return false
+		if len(volumes) >= 1 {
+			log.Info("fetch EC2 instance id using first volume")
+			var targetVolumeIDs []*string
+			for j := range volumes {
+				volume := volumes[j]
+				targetVolumeIDs = append(targetVolumeIDs, &volume.ID)
```
Comment (3pointer) [inline br/pkg/aws/ebs.go:75]: looks like keep one of `targetVolumeIDs` or `volumeIDs` is enough

File: br/pkg/aws/ebs.go [hunk 2]
```diff
@@ -49,66 +48,92 @@ func NewEC2Session(concurrency uint) (*EC2Session, error) {
...
-					return true
+				if !toInclude {
+					excludedVolumeIDs = append(excludedVolumeIDs, device.Ebs.VolumeId)
 				}
-				return true
-			})
-		}
+			}
+
+			log.Info("exclude volume list", zap.Any("exclude volume list", excludedVolumeIDs))
```
Comment (3pointer) [inline br/pkg/aws/ebs.go:115]: maybe also log the instance name.

File: br/pkg/aws/ebs.go (hunk 1 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go:75]: targetVolumeIDs are for current tikv store, while volumeIDs are for all tikv stores.

File: br/pkg/aws/ebs.go (hunk 2 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go]: fixed.

File: br/pkg/aws/ebs.go [hunk 3]
```diff
@@ -49,66 +48,90 @@ func NewEC2Session(concurrency uint) (*EC2Session, error) {
...
 	var mutex sync.Mutex
 	eg, _ := errgroup.WithContext(context.Background())
-	fillResult := func(snap *ec2.Snapshot, volume *config.EBSVolume) {
+	fillResult := func(createOutput *ec2.CreateSnapshotsOutput) {
 		mutex.Lock()
 		defer mutex.Unlock()
-		snapIDMap[volume.ID] = *snap.SnapshotId
+		for j := range createOutput.Snapshots {
+			snapshot := createOutput.Snapshots[j]
+			snapIDMap[*snapshot.VolumeId] = *snapshot.SnapshotId
```
Comment (YuJuncen) [inline br/pkg/aws/ebs.go:62]: Perhaps use [`StringValue`](https://pkg.go.dev/github.com/aws/aws-sdk-go/aws#StringValue) instead of dereferencing directly to avoid panic.

File: br/pkg/aws/ebs.go [hunk 4]
```diff
@@ -49,66 +48,90 @@ func NewEC2Session(concurrency uint) (*EC2Session, error) {
...
+			// determine the ec2 instance id
+			resp, err := e.ec2.DescribeVolumes(&ec2.DescribeVolumesInput{VolumeIds: targetVolumeIDs[0:1]})
+			if err != nil {
+				return snapIDMap, nil, errors.Trace(err)
+			}
+			if resp.Volumes[0].Attachments[0] == nil || resp.Volumes[0].Attachments[0].InstanceId == nil {
+				return snapIDMap, nil, errors.Errorf("specified volume %s is not attached", volumes[0].ID)
+			}
+			ec2InstanceId := resp.Volumes[0].Attachments[0].InstanceId
+			log.Info("EC2 instance id", zap.Any("id", ec2InstanceId))
```
Comment (YuJuncen) [inline br/pkg/aws/ebs.go:88]: Prefer using the typed API for logging.
```suggestion
			log.Info("EC2 instance id", zap.Stringp("id", ec2InstanceId))
```

**Review by YuJuncen — APPROVED** [review]

File: br/pkg/aws/ebs.go (hunk 3 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go]: Done.

File: br/pkg/aws/ebs.go (hunk 4 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go]: Done

**Review by 3pointer — APPROVED** [review]
