### PR TITLE
executor: fix cluster index encode wrong key in plan cached point get

### LINKED ISSUE #19002: wrong point-get result when clustered index is used with plan-cache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start a tidb-server with plan cache enable:

```
MySQL [ut]> set @@tidb_enable_clustered_index = 1;
Query OK, 0 rows affected (0.00 sec)

MySQL [ut]> create table t1(a int, b int, c int, primary key(a, b));
Query OK, 0 rows affected (0.01 sec)

MySQL [ut]> insert into t1 values(1,1,111),(2,2,222),(3,3,333);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

MySQL [ut]> prepare stmt2 from "select * from t1 where t1.a = ? and t1.b = ?";
Query OK, 0 rows affected (0.00 sec)

MySQL [ut]> set @v1=1;
Query OK, 0 rows affected (0.00 sec)

MySQL [ut]> set @v2=1;
Query OK, 0 rows affected (0.00 sec)

MySQL [ut]> execute stmt2 using @v1,@v2;
+---+---+------+
| a | b | c    |
+---+---+------+
| 1 | 1 |  111 |
+---+---+------+
1 row in set (0.00 sec)

MySQL [ut]> set @v1=2;
Query OK, 0 rows affected (0.00 sec)

MySQL [ut]> set @v2=2;
Query OK, 0 rows affected (0.01 sec)

MySQL [ut]> execute stmt2 using @v1,@v2;
Empty set (0.00 sec)
```

### 2. What did you expect to see? (Required)

The second execute should return 1 record.

### 3. What did you see instead (Required)

It returns empty record.

### 4. Affected version (Required)

master branch: 6ccd8248a8e7f89a9e5987e78e74b13a3e47cd5d

### 5. Root Cause Analysis

In `PointGetExecutor::Next`, for non-clustered-index, it uses `EncodeUniqueIndexKey`, which would impose type casting on `e.idxVals` before encoding it to keys, while for clustered-index, it directly calls `EncodeKey` for `e.idxVals`. `e.idxVals` may contain datums of string type, while the primary key columns are defined as integer types.

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #19002

### What is changed and how it works?

What's Changed: encode key for common handle should keep consistent with unique index.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- none.

### CODE REVIEW

File: executor/point_get.go [hunk 1]
```diff
@@ -337,6 +337,15 @@ func (e *PointGetExecutor) get(ctx context.Context, key kv.Key) ([]byte, error)
...
 func EncodeUniqueIndexKey(ctx sessionctx.Context, tblInfo *model.TableInfo, idxInfo *model.IndexInfo, idxVals []types.Datum, tID int64) (_ []byte, err error) {
+	encodedIdxVals, err := EncodeUniqueIndexValues(ctx, tblInfo, idxInfo, idxVals)
+	if err != nil {
+		return nil, err
+	}
+	return tablecodec.EncodeIndexSeekKey(tID, idxInfo.ID, encodedIdxVals), nil
+}
+
+// EncodeUniqueIndexValues encodes a unique index values.
+func EncodeUniqueIndexValues(ctx sessionctx.Context, tblInfo *model.TableInfo, idxInfo *model.IndexInfo, idxVals []types.Datum) (_ []byte, err error) {
```
Comment (coocood) [inline executor/point_get.go:348]: It would more clear if we rename it to `EncodeUniqueIndexValuesForKey`, so we don't confuse it with methods like `tablecodec.GenIndexValue`.

**Comment by coocood** [comment]
LGTM
