### PR TITLE
planner: fix panic in `extractSelectAndNormalizeDigest `

### LINKED ISSUE #22290: executor: desc table panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
desc table t;
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

### 3. What did you see instead (Required)
```
[ERROR] [conn.go:733] ["connection running loop panic"] [conn=3] [lastSQL="desc table t1"] [err="runtime error: slice bounds out of range [-1:]"] [stack="goroutine 616 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x6aae200, 0xc000f65860, 0xc000137100)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:731 +0xee\npanic(0x6296300, 0xc000d52680)\n\t/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166\ngithub.com/pingcap/tidb/planner.extractSelectAndNormalizeDigest(0x6ad1f20, 0xc0010a3ec0, 0xc0005dcfbc, 0x4, 0xc000a1c5a0, 0xc000fc6640, 0xc0010c49c0, 0x6aca9c0, 0xc001038d00, 0xc000fc6640)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/optimize.go:312 +0x84a\ngithub.com/pingcap/tidb/planner.getBindRecord(0x6b00b80, 0xc0009b3300, 0x6ad1f20, 0xc0010a3ec0, 0xc0010a3ec0, 0xc0010a3e01, 0x6af3740)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/optimize.go:358 +0xb7\ngithub.com/pingcap/tidb/planner.Optimize(0x6aae200, 0xc0010c4840, 0x6b00b80, 0xc0009b3300, 0x6ac9580, 0xc0010a3ec0, 0x6af3740, 0xc000c7b830, 0x0, 0x0, ...)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/optimize.go:134 +0x571\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile(0xc000fc6dd8, 0x6aae200, 0xc0010c4840, 0x6ad1f20, 0xc0010a3ec0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/executor/compiler.go:62 +0x2fd\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc0009b3300, 0x6aae200, 0xc0010c4540, 0x6ad1f20, 0xc0010a3ec0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/session/session.go:1379 +0x33a\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc00101b050, 0x6aae200, 0xc0010c4540, 0x6ad1f20, 0xc0010a3ec0, 0xc0006a8210, 0x6aae200, 0xc0010c4540, 0x874ae58)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/driver_tidb.go:212 +0x68\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc000137100, 0x6aae200, 0xc0010c4540, 0x6ad1f20, 0xc0010a3ec0, 0x874ae58, 0x0, 0x0, 0x1, 0x0, ...)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:1561 +0x139\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc000137100, 0x6aae140, 0xc0010a3e40, 0xc000f5e431, 0xd, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:1453 +0x49b\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc000137100, 0x6aae140, 0xc0010a3e40, 0xc000f5e430, 0xe, 0xd, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:1027 +0x696\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc000137100, 0x6aae200, 0xc000f65860)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:792 +0x29c\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc0010c61a0, 0xc000137100)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/server.go:461 +0xa97\ncreated by github.com/pingcap/tidb/server.(*Server).Run\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/server.go:364 +0x894\n"]

```
### 4. What is your TiDB version? (Required)
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.14.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #22290 

Problem Summary: planner: fix panic in `extractSelectAndNormalizeDigest `

### What is changed and how it works?

In `extractSelectAndNormalizeDigest` we assume that a `SelectStmt` must contains a substring `select`, but after https://github.com/pingcap/tidb/issues/19934, this assumption has been broken.

https://github.com/pingcap/tidb/blob/51794e9d304896a315d80ccb4603f59dc75f26d9/planner/optimize.go#L299-L300

This PR removes this assumption and uses `Node.Restore()` to get the underlying SQL in `explain`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- planner: fix panic in `extractSelectAndNormalizeDigest `

### CODE REVIEW

File: planner/optimize.go [hunk 1]
```diff
@@ -337,42 +324,45 @@ func extractSelectAndNormalizeDigest(stmtNode ast.StmtNode, specifiledDB string)
...
+	}
+	stmtNode, normalizedSQL, hash, err := extractSelectAndNormalizeDigest(stmt, ctx.GetSessionVars().CurrentDB)
+	if err != nil {
+		return nil, "", err
 	}
-	stmtNode, normalizedSQL, hash := extractSelectAndNormalizeDigest(stmt, ctx.GetSessionVars().CurrentDB)
 	if stmtNode == nil {
-		return nil, ""
+		return nil, "", nil
 	}
```
Comment (Reminiscent) [inline planner/optimize.go:351]: We can merge here to 
```
if err != nil || stmtNode == nil {
    return nil, "", err
}
```
Rest LGTM

**Review by Reminiscent — COMMENTED** [review]
LGTM

**Review by eurekaka — DISMISSED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: planner/optimize.go (hunk 1 above)
Comment (qw4990) [reply planner/optimize.go]: addressed.

**Review by Reminiscent — APPROVED** [review]
LGTM

**Review by eurekaka — APPROVED** [review]
