### PR TITLE
*: refine the behavior of StrToInt and StrToFloat and support convert JSON to date, time and timestamp 

### LINKED ISSUE #17898: Wrong handling of  strToInt and strToFloat
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
TiDB> create table t0(a char(10), b int as ((a))); 
Execute success (0.02 sec)
TiDB> insert into t0(a) values("0.5");
Execute success (0.00 sec)
TiDB> select * from t0;
+-----+---+
| a   | b | 
+-----+---+
| 0.5 | 0 | 
+-----+---+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t0;
+------+------+
| a    | b    |
+------+------+
| 0.5  |    1 |
+------+------+
1 row in set (0.00 sec)
```

### 4. Affected version (Required)

master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #17898 

Problem Summary:

TiDB don't distinguish cast(explicit CAST function or implicit cast) from cast(when casting into a column type, CastValue()). 
We try to distinguish them according to if the statement is a select statement or an insert statement. 
However, it's not correct, especially when the virtual generated column comes out. We can't make sure the value inserted and read are the same.
So we can't depend on if the type of the statement. We need to keep a principle. If some values are converted to a column type, then use CastValue(). Otherwise, don't use it.

Here is an example:
We didn't support converted a JSON to date. When we had a virtual generated column and it needed to be converted from a JSON to date,  we used CastJsonAsDuration to do that. This is wrong. So I supported convert JSON to date, time, and timestamp within CastValue(), though their logics are quite similar.

Finally, I correct some tests.  If you test these tests in MySQL and previously TiDB, you will see that the warnings of TiDB are wrong.

### What is changed and how it works?

1. refine the behavior of StrToInt and StrToFloat. Handling them differently according to the function call them.
2. implement convert JSON to date, time, and timestamp.
3. correct some tests.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- refine the behavior of StrToInt and StrToFloat and support convert JSON to date, time and timestamp

### CODE REVIEW

File: expression/builtin_cast.go [hunk 1]
```diff
@@ -1110,7 +1110,7 @@ func (b *builtinCastStringAsIntSig) handleOverflow(origRes int64, origStr string
 	}
 
 	sc := b.ctx.GetSessionVars().StmtCtx
-	if sc.InSelectStmt && types.ErrOverflow.Equal(origErr) {
+	if types.ErrOverflow.Equal(origErr) {
```
Comment (Reminiscent) [inline expression/builtin_cast.go:1113]: It looks like it would only happen in select statements before. Does the change make the insert statement different from mysql?

File: expression/builtin_time.go [hunk 2]
```diff
@@ -5774,20 +5774,7 @@ func (c *makeTimeFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
...
-	} else {
-		arg0Type = types.ETInt
-	}
-	if arg1Type == types.ETString {
-		arg1Type = types.ETReal
-	} else {
-		arg1Type = types.ETInt
-	}
-	bf, err := newBaseBuiltinFuncWithTp(ctx, c.funcName, args, types.ETDuration, arg0Type, arg1Type, types.ETReal)
+	bf, err := newBaseBuiltinFuncWithTp(ctx, c.funcName, args, types.ETDuration, types.ETInt, types.ETInt, types.ETReal)
```
Comment (Reminiscent) [inline expression/builtin_time.go:5777]: For all types, arg is evaluated rounding to int64? Please add some comments.

File: expression/builtin_cast.go (hunk 1 above)
Comment (wjhuang2016) [reply expression/builtin_cast.go:1113]: According to the test, this change won't break the existing test. The reason I delete sc.InSelectStmt is that we shouldn't use InSelectStmt to decide how to handle the err. We should use `TruncateAsWarning` , `IgnoreTruncate` to do that.
