### PR TITLE
domain: fix bug that after 'skip-grant-table', set password doesn't take effect immediately

### LINKED ISSUE #29653: `skip-grant` tidb set password can't take affect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster with (node tidb1)
2. start a new tidb node  with `security.skip-grant-table=true` (node tidb2)
3. connect  tidb2 to set the password and `flush privileges`
4. connect tidb1 use the password

### 2. What did you expect to see? (Required)
1. can login successfully with the set password connect to tidb1
### 3. What did you see instead (Required)
1. can not use the set password connect tidb1
2. `select * from mysql.user` dispaly that the password was record correct
3. use tidb1 `flush privileges`, then it's will take affect
### 4. What is your TiDB version? (Required)
release-5.3(c6d652), master (99ab8bf16f6f61cb8d4a)

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #29653

Problem Summary:

### What is changed and how it works?

When `skip-grant-table` is configured, the changes of privilege data in one TiDB instance should still notify to other TiDB instance. Because without notification, set the password in a special TiDB instance will not take effect in the whole cluaster immediately.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

It's hard to write a unit test for this case.

I've test the change with those steps:

1. tiup playground
2. create user xxx@% identified by yyy
3. mysql -h 127.0.0.1 -u xxx -P -p , use password zzz, fail
4. use a `skip-grant-table` tidb node to connect to the cluster
5. set password for xxx@% = 'zzz'
6. mysql -h 127.0.0.1 -u xxx -P -p , use password zzz, success
 
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix a bug that when 'skip-grant-table' is set, changing password doesn't take effect to the whole cluster immediately
```

### CODE REVIEW

File: domain/domain.go [hunk 1]
```diff
@@ -1446,20 +1446,24 @@ const (
...
-	// If skip-grant-table is configured, do not flush privileges.
-	// Because LoadPrivilegeLoop does not run and the privilege Handle is nil,
-	// the call to do.PrivilegeHandle().Update would panic.
-	if config.GetGlobalConfig().Security.SkipGrantTable {
-		return nil
-	}
-
+	// No matter skip-grant-table is configured or not, send etcd message is required.
+	// Because we need to tell other TiDB instances to update privilege data, say, we're change the
+	// password using a special TiDB instance and want the new password to take effect.
```
Comment (djshow832) [inline domain/domain.go:1451]:
```suggestion
	// No matter skip-grant-table is configured or not, sending an etcd message is required.
	// Because we need to tell other TiDB instances to update privilege data, say, we're changing the
	// password using a special TiDB instance and want the new password to take effect.
```

**Review by djshow832 — COMMENTED** [review]
Please write the steps and the results of the manual test in the PR description, thank you!

**Review by morgo — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Comment by winoros** [comment]
@ti-chi-bot
