### PR TITLE
ddl, executor: add warning log for lock/unlock tables

### LINKED ISSUE #28967: LOCK TABLE T1 write;  does not raise error or warning
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
--sesson 1
drop table if exists t1,t2,t3,t11,t12;
CREATE TABLE t1 (a tinyint(3), b tinyint(5));
INSERT INTO t1 VALUES (1,1);
LOCK TABLE t1 write;

--session 2
INSERT INTO t1 VALUES (1,2); --lock wait timeout and eventually fail
```

### 2. What did you expect to see? (Required)

This should return an error if not possible:

```sql
mysql> INSERT INTO t1 VALUES (1,2);   --lock wait timeout and eventually fail
```

### 3. What did you see instead (Required)

```sql
--session 1
drop table if exists t1,t2,t3,t11,t12;
CREATE TABLE t1 (a tinyint(3), b tinyint(5));
INSERT INTO t1 VALUES (1,1);
LOCK TABLE t1 write;

--session 2
INSERT INTO t1 VALUES (1,2); --session 2 is still allow to insert data in t1
```
### 4. What is your TiDB version? (Required)

```sql
 Release Version: v5.2.1                                          +
 Edition: Community                                               +
 Git Commit Hash: cd8fb24c5f7ebd9d479ed228bb41848bd5e97445        +
 Git Branch: heads/refs/tags/v5.2.1                               +
 UTC Build Time: 2021-09-08 02:29:53                              +
 GoVersion: go1.16.4                                              +
 Race Enabled: false                                              +
 TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306+
 Check Table Before Drop: false 
(1 row)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #28967

Problem Summary: Add warning log for `lock tables` and `unlock tables` when `enable-table-lock` flag not enabled.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @morgo 
PTAL

File: executor/ddl.go [hunk 1]
```diff
@@ -798,13 +798,15 @@ func (e *DDLExec) executeLockTables(s *ast.LockTablesStmt) error {
...
 		return nil
 	}
 	return domain.GetDomain(e.ctx).DDL().LockTables(e.ctx, s)
 }
 
 func (e *DDLExec) executeUnlockTables(_ *ast.UnlockTablesStmt) error {
 	if !config.TableLockEnabled() {
+		e.ctx.GetSessionVars().StmtCtx.AppendWarning(errors.Errorf("Unlock tables works only when enable-table-lock is set in config file"))
 		return nil
 	}
```
Comment (morgo) [inline executor/ddl.go:811]: A couple of suggestions:
1. We make the mode dependent on https://docs.pingcap.com/tidb/dev/system-variables#tidb_enable_noop_functions-new-in-v40 -- but it only ever returns warnings at most (since it's important DDL can restore). This provides a mechanism for users to kill the warning if that is problematic for their script.
2. We add a new error number / error code. This helps us track the errors in information schema so we know which unsupported syntax the user is encountering.

Let me know what you think about either. These are just suggestions.

Comment (Defined2014) [reply executor/ddl.go:811]: 1. Sounds good for me.
2. Maybe we can use `mysql.ErrNotSupportedYet` with different error message between `ErrFunctionsNoopImpl`.

Comment (morgo) [reply executor/ddl.go:811]: Sounds good to me.

Comment (Defined2014) [reply executor/ddl.go]: Done，PTAL @morgo

File: executor/ddl.go [hunk 2]
```diff
@@ -791,20 +791,35 @@ func (e *DDLExec) executeFlashbackTable(s *ast.FlashBackTableStmt) error {
...
 func (e *DDLExec) executeLockTables(s *ast.LockTablesStmt) error {
+	if !config.TableLockEnabled() {
+		noopFuncsMode := e.ctx.GetSessionVars().NoopFuncsMode
+		err := ErrFuncNotEnabled.GenWithStackByArgs("Lock tables", "enable-table-lock")
+		if noopFuncsMode == variable.OffInt {
+			return err
+		} else if noopFuncsMode == variable.WarnInt {
+			e.ctx.GetSessionVars().StmtCtx.AppendWarning(err)
+		}
+		return nil
```
Comment (morgo) [inline executor/ddl.go:802]: Sorry, for this syntax I think we can only `WARN` at most. I know this is different from most other noop functions, but this syntax is used by `mysqldump`. If we generate an error, mysqldump files won't restore by default :(

Comment (Defined2014) [reply executor/ddl.go:802]: The behavior will be very strange. If we only have `WARN`, I think use `TableLockEnabled()` is better than `noopFuncsMode `.

Comment (morgo) [reply executor/ddl.go]: I agree it is strange, but the change is too severe if mysqldump can not be restored.

For the docs: https://docs.pingcap.com/tidb/dev/system-variables#tidb_enable_noop_functions-new-in-v40

We can add a sentence: Setting `tidb_enable_noop_functions` to `OFF` does not prevent `LOCK TABLE t1 WRITE` from executing. A warning is returned instead. This behavior is required for compatibility with mysqldump.

Comment (Defined2014) [reply executor/ddl.go]: Updated, PTAL @morgo

File: executor/errors.go [hunk 3]
```diff
@@ -64,6 +64,7 @@ var (
 	ErrNotSupportedWithSem           = dbterror.ClassOptimizer.NewStd(mysql.ErrNotSupportedWithSem)
 	ErrPluginIsNotLoaded             = dbterror.ClassExecutor.NewStd(mysql.ErrPluginIsNotLoaded)
 	ErrSetPasswordAuthPlugin         = dbterror.ClassExecutor.NewStd(mysql.ErrSetPasswordAuthPlugin)
+	ErrFuncNotEnabled                = dbterror.ClassExecutor.NewStdErr(mysql.ErrNotSupportedYet, parser_mysql.Message("%-.32s works only when %-.32s is set in config file", nil))
```
Comment (morgo) [inline executor/errors.go:67]: The warning is not clear that the behavior is a noop. This distinction is important in understanding the risks. May I suggest instead:

> LOCK TABLE is not supported. To enable this experimental feature, set 'enable-table-lock' in the configuration file.

Otherwise LGTM.

Comment (Defined2014) [reply executor/errors.go:67]: Yes, it's too confusing. I think we should return warning whether `noop_funcs` enabled or not. Maybe controlled by 'enable-table-lock' is enough. @morgo

Comment (Defined2014) [reply executor/errors.go]: Modified according to your suggestion. @morgo

@AilinKid PTAL

**Review by morgo — APPROVED** [review]
LGTM, thanks for making edits!

**Review by tangenta — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
