### PR TITLE
planner: fix "invalid memory address or nil pointer dereference" when using Instance Plan Cache in some cases

### LINKED ISSUE #58395: `execute` statement get "invalid memory address or nil pointer dereference" error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set GLOBAL tidb_enable_instance_plan_cache=1;

drop table t3;
CREATE TABLE t3 (c datetime, PRIMARY KEY (c));

use test
prepare p4 from "select * from t3 where c in (?, ? , '2033-11-23')";
set @i0 = '2027-12-17', @i1 = '1986-12-03';
execute p4 using @i0, @i1;
```

open another session and run

```sql
use test
prepare p4 from "select * from t3 where c in (?, ?, '2033-11-23')";
set @i0 = 'a', @i1 = 'b';
execute p4 using @i0, @i1;
```

### 2. What did you expect to see? (Required)

```
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```sql
Error 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
```

If you run the second `execute` in the same session, there will be no error. As you can in the warnings, plan cache is skipped for this SQL:

```
Warning | 1105 | skip prepared plan-cache: Batch/PointGet plans may be over-optimized
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #58395

Problem Summary: planner: fix "invalid memory address or nil pointer dereference" when using Instance Plan Cache in some cases

### What changed and how does it work?

planner: fix "invalid memory address or nil pointer dereference" when using Instance Plan Cache in some cases

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/plan_clone_utils.go [hunk 1]
```diff
@@ -140,6 +140,9 @@ func cloneConstantsForPlanCache(constants, cloned []*expression.Constant) []*exp
 	}
 	allSafe := true
 	for _, c := range constants {
+		if c == nil {
```
Comment (AilinKid) [inline pkg/planner/core/plan_clone_utils.go:143]: why it's nil here

Comment (qw4990) [reply pkg/planner/core/plan_clone_utils.go:143]: In cases like "where pk in (?, ?, 1)", then this constant can be nil: https://github.com/pingcap/tidb/blob/master/pkg/planner/core/point_get_plan.go#L1160

**Review by AilinKid — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
