### PR TITLE
table, meta: fix auto_increment initialization for temporary tables

### LINKED ISSUE #36224: Temporary table does not use AUTO_INCREMENT initialisation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create temporary table t (a int not null auto_increment primary key) auto_increment = 100;
show create table t;
insert into t values (null);
select * from t;
```

### 2. What did you expect to see? (Required)

```
mysql> create temporary table t (a int not null auto_increment primary key) auto_increment = 100;
Query OK, 0 rows affected (0,01 sec)

mysql> show create table t;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                              |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TEMPORARY TABLE `t` (
  `a` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0,01 sec)

mysql> insert into t values (null);
Query OK, 1 row affected (0,00 sec)

mysql> select * from t;
+-----+
| a   |
+-----+
| 100 |
+-----+
1 row in set (0,00 sec)
```
### 3. What did you see instead (Required)

```
tidb> create temporary table t (a int not null auto_increment primary key) auto_increment = 100;
Query OK, 0 rows affected (0,00 sec)

tidb> show create table t;
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                           |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TEMPORARY TABLE `t` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`a`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0,00 sec)

tidb> insert into t values (null);
Query OK, 1 row affected (0,01 sec)

tidb> select * from t;
+---+
| a |
+---+
| 1 |
+---+
1 row in set (0,00 sec)
```

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v6.2.0-alpha-378-g987bdd3014
Edition: Community
Git Commit Hash: 987bdd3014d8c90302caac3e99092d8014c47109
Git Branch: master
UTC Build Time: 2022-07-14 16:08:35
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #36224

Problem Summary:
The base of the `auto_increment` value doesn't conform to the `create table` statement.

### What is changed and how it works?

- Rebase the allocator after it's created.
- Modify the return value of `NextGlobalAutoID`, which is used for `show create table`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
- Fix the issue that temporary tables don't use `AUTO_INCREMENT ` initialization.
```

### CODE REVIEW

File: table/tables/tables.go [hunk 1]
```diff
@@ -1963,10 +1963,16 @@ type TemporaryTable struct {
 
 // TempTableFromMeta builds a TempTable from model.TableInfo.
 func TempTableFromMeta(tblInfo *model.TableInfo) tableutil.TempTable {
+	alloc := autoid.NewAllocatorFromTempTblInfo(tblInfo)
+	// Rebase the allocator if the base is specified.
+	if tblInfo.AutoIncID > 1 {
+		// We can omit the error because it won't return an error.
+		_ = alloc.Rebase(context.Background(), tblInfo.AutoIncID-1, false)
```
Comment (djshow832) [inline table/tables/tables.go:1970]: Note: It's not easy to return an error here. It needs to update lots of interfaces because outer interfaces don't expect errors either.

**Review by tiancaiamao — APPROVED** [review]

File: table/temptable/ddl.go [hunk 2]
```diff
@@ -180,6 +180,12 @@ func newTemporaryTableFromTableInfo(sctx sessionctx.Context, tbInfo *model.Table
 	alloc := autoid.NewAllocatorFromTempTblInfo(tbInfo)
 	allocs := make([]autoid.Allocator, 0, 1)
 	if alloc != nil {
+		// Rebase the allocator if the base is specified.
+		if tbInfo.AutoIncID > 1 {
```
Comment (lcwangchao) [inline table/temptable/ddl.go:184]: Why not moving these codes to `NewAllocatorFromTempTblInfo` ?

Comment (djshow832) [reply table/temptable/ddl.go:184]: I want to make `NewAllocatorFromTempTblInfo` consistent with `NewAllocatorsFromTblInfo`: `NewAllocatorsFromTblInfo` doesn't rebase the allocator, and the callers rebase the allocators.

Comment (djshow832) [reply table/temptable/ddl.go:184]: I think it's also fine to break the consistency. I'll do it.

**Review by lcwangchao — APPROVED** [review]
