### PR TITLE
topsql: add more test case for topsql

### LINKED ISSUE #32405: add more test case for topsql
## Dev Task

Add more test cases to make sure the data correctness of a topsql:

[] analyze sql
[] explain analyze sql
[] trace sql
[] set global sql and the related internal sql
[] multi-statement
[] multi-statement but the first statement execute failed
[] multi-statement but the second statement execute failed.
[] sql with execution in optimize stage.
[] sql with many compile plan time
[] sql with syntax error
[] DDL sql but execute failed.
[] sql execute failed cause by kv error
[] make sure the data correctness of `ExecCount` for the long execution time sql.

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #32405

add more test case for topsql

Tests 

- [x] Integration test
- [x] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@zhongzc @mornyx PTAL

**Comment by crazycs520** [comment]
@zhongzc @mornyx PTAL

File: util/topsql/topsql.go [hunk 1]
```diff
@@ -104,34 +104,43 @@ func AttachSQLInfo(ctx context.Context, normalizedSQL string, sqlDigest *parser.
...
+	if !match {
+		return false
+	}
+	start := time.Now()
+	for {
+		if time.Since(start) > 12*time.Millisecond {
+			break
+		}
+		for i := 0; i < 10e5; i++ {
+		}
```
Comment (mornyx) [inline util/topsql/topsql.go:139]: I'm not sure, won't this loop be optimized by the compiler?

Comment (crazycs520) [reply util/topsql/topsql.go:139]: no, it won't.

File: util/topsql/stmtstats/aggregator.go [hunk 2]
```diff
@@ -120,6 +117,7 @@ func (m *aggregator) unregisterCollector(collector Collector) {
 // close ends the execution of the current aggregator.
 func (m *aggregator) close() {
 	m.cancel()
+	m.running.Store(false)
```
Comment (zhongzc) [inline util/topsql/stmtstats/aggregator.go:120]: Why moving to here?

Comment (crazycs520) [reply util/topsql/stmtstats/aggregator.go:120]: Because in the original logic, After I call `m.close()` then call `m.start()`, the aggregator won't start again since `m.running` is still true in the original logic.

Comment (zhongzc) [reply util/topsql/stmtstats/aggregator.go:120]: We can wait for the goroutine to be done via `WaitGroup` in `close()`

Comment (crazycs520) [reply util/topsql/stmtstats/aggregator.go]: ok, done.

**Comment by mornyx** [comment]
LGTM

File: util/topsql/collector/mock/mock.go [hunk 3]
```diff
@@ -118,6 +118,20 @@ func (c *TopSQLCollector) GetSQLStatsBySQL(sql string, planIsNotNull bool) []*co
 	return stats
 }
 
+// GetSQLCPUTimeBySQL uses for testing.
+func (c *TopSQLCollector) GetSQLCPUTimeBySQL(sql string) uint32 {
```
Comment (breeswish) [inline util/topsql/collector/mock/mock.go:122]: This is a mock collector. How about CPU time in real life?

Comment (crazycs520) [reply util/topsql/collector/mock/mock.go:122]: The CPU time of SQL is real data, not a mock data.

**Review by breeswish — APPROVED** [review]

**Review by zhongzc — APPROVED** [review]

File: server/tidb_test.go [hunk 4]
```diff
@@ -1452,7 +1452,7 @@ func TestTopSQLCPUProfile(t *testing.T) {
 		dbt := testkit.NewDBTestKit(t, db)
 		for _, ca := range cases4 {
 			if ca.isQuery {
-				require.NoError(t, dbt.MustQuery(ca.sql).Close())
```
Comment (zhongzc) [inline server/tidb_test.go]: L1424, L1372 and L1335 need the same change.

**Review by zhongzc — APPROVED** [review]
