### PR TITLE
executor: set the correct resultCh for task when indexHashJoin keep order

### LINKED ISSUE #18744: memory_quota: the query is blocked
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

oom-action=cancel
```
use test;
drop table if exists t, t1;
CREATE TABLE `t` (
  `id` int(11) NOT NULL,
  `a` bigint(20) DEFAULT NULL,
  `b` char(20) DEFAULT NULL,
  `c` datetime DEFAULT NULL,
  `d` double DEFAULT NULL,
  `e` json DEFAULT NULL,
  `f` decimal(40,6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `a` (`a`),
  KEY `b` (`b`),
  KEY `c` (`c`),
  KEY `d` (`d`),
  KEY `f` (`f`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `t1` (
  `id` int(11) NOT NULL,
  `a` bigint(20) DEFAULT NULL,
  `b` char(20) DEFAULT NULL,
  `c` datetime DEFAULT NULL,
  `d` double DEFAULT NULL,
  `e` json DEFAULT NULL,
  `f` decimal(40,6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `a` (`a`),
  KEY `b` (`b`),
  KEY `c` (`c`),
  KEY `d` (`d`),
  KEY `f` (`f`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into t1(id) values(0),(1),(2);
insert into t values(0, 2010,  "2010-01-01 01:01:00" , "2010-01-01 01:01:00" , 2010 , 2010 , 2010.000000);
insert into t values(1 , NULL , NULL                , NULL                , NULL , NULL ,        NULL);
insert into t values(2 , 2012 , "2012-01-01 01:01:00" , "2012-01-01 01:01:00" , 2012 , 2012 , 2012.000000);
set tidb_mem_quota_query=500;
select /*+ inl_hash_join(t2) */ t1.id, t2.id from t1 join t t2 on t1.a = t2.a order by t1.a ASC limit 1;
```
### 2. What did you expect to see? (Required)
```
mysql> select /*+ inl_hash_join(t2) */ t1.id, t2.id from t1 join t t2 on t1.a = t2.a order by t1.a ASC limit 1;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select /*+ inl_hash_join(t2) */ t1.id, t2.id from t1 join t t2 on t1.a = t2.a order by t1.a ASC limit 1;
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql> show processlist;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    3
Current database: test

+------+------+-----------------+------+---------+------+-------+------------------------------------------------------------------------------------------------------+
| Id   | User | Host            | db   | Command | Time | State | Info                                                                                                 |
+------+------+-----------------+------+---------+------+-------+------------------------------------------------------------------------------------------------------+
|    3 | root | 192.168.228.166 | test | Query   |    0 | 2     | show processlist                                                                                     |
|    1 | root | 192.168.228.166 | test | Query   | 1911 | 2     | select /*+ inl_hash_join(t2) */ t1.id, t2.id from t1 join t t2 on t1.a = t2.a order by t1.a ASC limi |
+------+------+-----------------+------+---------+------+-------+------------------------------------------------------------------------------------------------------+
2 rows in set (0.02 sec)
```

### 4. Affected version (Required)

```
Release Version: v4.0.2-56-g4bfa9df9a
Edition: Community
Git Commit Hash: 4bfa9df9ad62e03db8d4968461b152f72e3b7035
Git Branch: release-4.0
UTC Build Time: 2020-07-23 09:53:15
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
cherry-pick #18757 

### What problem does this PR solve?

Issue Number: close #18744  

Problem Summary:
Before this commit, we do not set the `resultCh` for the returned task when indexHashJoin need to keep order.

### What is changed and how it works?

What's Changed:
Set the correct resultCh for the task

How it Works:

### Related changes

N/A

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: executor/index_lookup_hash_join.go [hunk 1]
```diff
@@ -452,13 +453,14 @@ func (iw *indexHashJoinInnerWorker) run(ctx context.Context, cancelFunc context.
 		if !ok {
 			break
 		}
+		// We need to init resultCh before the err is returned.
+		if task.keepOuterOrder {
+			resultCh = task.resultCh
+		}
```
Comment (SunRunAway) [inline executor/index_lookup_hash_join.go:459]: Please cover this path in the unit test. The `testIndexHashJoinInnerWorkerErr` failpoint can be used.
