### PR TITLE
planner: add missing table lock check for fast plan

### LINKED ISSUE #20945: table with read lock can be updated
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
lock tablse sbtest1 read;
update sbtest1 set k = 2 where id = 1;

### 2. What did you expect to see? (Required)
update unsuccessful
### 3. What did you see instead (Required)
update success
MySQL [benchmark]> unlock tables;
Query OK, 0 rows affected (1.01 sec)

MySQL [benchmark]> lock table sbtest1 read;
Query OK, 0 rows affected (1.01 sec)

MySQL [benchmark]> insert into sbtest1 values(12121,3232,'a','df');
ERROR 1099 (HY000): Table 'sbtest1' was locked with a READ lock and can't be updated
MySQL [benchmark]> update sbtest1 set k=2 where id=1;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

### 4. What is your TiDB version? (Required)
master

| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.15.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #20945 

Problem Summary:

when lock table as read update with where statement can update the row.

### What is changed and how it works?

What's Changed:

Add table lock check in TryFastPlan code path

### Related changes

- No

### Check List 

Tests 

- Unit test
- Integration test
- Manual test

Manual test step:

```
create table t (id int, c int);
insert into t values(1, 1), (2, 1);
lock table t read;
update t set c = 2 where id = 2;
```

Side effects

- No

### Release note 

- Fix table lock for update statement.

### CODE REVIEW

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -853,15 +853,25 @@ func newPointGetPlan(ctx sessionctx.Context, dbName string, schema *expression.S
 
 func checkFastPlanPrivilege(ctx sessionctx.Context, dbName, tableName string, checkTypes ...mysql.PrivilegeType) error {
 	pm := privilege.GetPrivilegeManager(ctx)
-	if pm == nil {
-		return nil
-	}
+
```
Comment (crazycs520) [inline planner/core/point_get_plan.go:856]: remove this blank line?

**Review by crazycs520 — COMMENTED** [review]
REST LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @crazycs520

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
