### PR TITLE
lightning: don't ignore error if check new collation failed

### LINKED ISSUE #31088: tidb-lightning import wrong data if user doesn't has right permission
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Use tidb-lightning to import data into a v5.3.0 cluster with (new_collations_enabled_on_first_bootstrap=true). The user in tidb-lightning's config doesn't has permission to access to table `mysql.tidb`

### 2. What did you expect to see? (Required)
The import should either return an error or import success.

### 3. What did you see instead (Required)
TiDB-Lightning return success but data in target db is not consistent.

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #31088

Problem Summary:

### What is changed and how it works?
Do not ignore the error when execute query `SELECT variable_value FROM mysql.tidb WHERE variable_name = 'new_collation_enabled'`, if the return err is `sql.NORows`, lightning will treat it as false, otherwise, directly return an error and exit.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the error that if tidb-lightning doesn't has permission to access mysql.tidb, it will generate kv with wrong format.
```

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

File: br/pkg/lightning/restore/tidb.go [hunk 1]
```diff
@@ -379,9 +379,13 @@ func ObtainNewCollationEnabled(ctx context.Context, g glue.SQLExecutor) bool {
 	)
 	if err == nil && newCollationVal == "True" {
 		newCollationEnabled = true
+	} else if errors.ErrorEqual(err, sql.ErrNoRows) {
+		// ignore if target variable is not found, this may happen if tidb < v4.0
+		newCollationEnabled = false
```
Comment (wjhuang2016) [inline br/pkg/lightning/restore/tidb.go:384]: No need to set it.
