### PR TITLE
planner: correct the generation of the field name

### LINKED ISSUE #11313: Outputing column name missing
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
mysql> select if(1,st,st) from t1;
```

2. What did you expect to see?

```
+-----------------------+
| select if(1,st,st)    |
+-----------------------+
| aa                    |
+-----------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```
+----+
|    |
+----+
| aa |
+----+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve? 

fix #11313 

Also, this will help us remove the `IsReferenced` field in `expression.Column`.

### What is changed and how it works?

`*expression.Column` may be generated from a simplified expression.
But one `ast.ColumnNameExpr` must refer to a column, though it may be a correlated column.
So check the ast instead of the expr.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -2205,6 +2205,13 @@ func (s *testSuite) TestColumnName(c *C) {
 	c.Assert(fields[1].ColumnAsName.L, Equals, "num")
 	tk.MustExec("set @@tidb_enable_window_function = 0")
 	rs.Close()
+
+	rs, err = tk.Exec("select if(1,c,c) from t;")
+	c.Check(err, IsNil)
+	fields = rs.Fields()
+	c.Assert(fields[0].Column.Name.L, Equals, "if(1,c,c)")
+	// It's a compatibility issue. Should be empty instead.
+	c.Assert(fields[0].ColumnAsName.L, Equals, "if(1,c,c)")
```
Comment (winoros) [inline executor/executor_test.go]: This comptibility issue is separated work. https://github.com/pingcap/tidb/issues/11323

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -591,12 +591,10 @@ func (b *PlanBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
 }
 
 // buildProjectionFieldNameFromColumns builds the field name, table name and database name when field expression is a column reference.
-func (b *PlanBuilder) buildProjectionFieldNameFromColumns(field *ast.SelectField, c *expression.Column) (colName, origColName, tblName, origTblName, dbName model.CIStr) {
-	if astCol, ok := getInnerFromParenthesesAndUnaryPlus(field.Expr).(*ast.ColumnNameExpr); ok {
-		origColName, tblName, dbName = astCol.Name.Name, astCol.Name.Table, astCol.Name.Schema
-	}
-	if field.AsName.L != "" {
-		colName = field.AsName
+func (b *PlanBuilder) buildProjectionFieldNameFromColumns(origField *ast.SelectField, colNameField *ast.ColumnNameExpr, c *expression.Column) (colName, origColName, tblName, origTblName, dbName model.CIStr) {
```
Comment (XuHuaiyu) [inline planner/core/logical_plan_builder.go]: Can we set `Schema` and `Table` for ColumnNameExpr when building `expression.Column` from it? Thus we can remove `c` here which will make the code clearer.

Comment (winoros) [reply planner/core/logical_plan_builder.go]: I prefer not to change the ast's content :joy:

Comment (XuHuaiyu) [reply planner/core/logical_plan_builder.go]: It will not be changed.
Check https://github.com/pingcap/tidb/blob/master/planner/core/logical_plan_builder.go#L2119

Comment (winoros) [reply planner/core/logical_plan_builder.go]: No, if there's no wild star. It's the original content.

Comment (XuHuaiyu) [reply planner/core/logical_plan_builder.go]: But we can create a new `ast.ColumnNameExpr` here? 
https://github.com/pingcap/tidb/blob/master/planner/core/logical_plan_builder.go#L1889

Comment (winoros) [reply planner/core/logical_plan_builder.go]: I think we don't need to change it for now. The logic of creating the field names will be rewritten in the following PRs.
