### PR TITLE
expression: add json opaque value

### LINKED ISSUE #9996: json_array with base64 is not same with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```SQL
select json_array(b'0', b'1', b'10');
```
2. What did you expect to see?
## In MySQL
```SQL
mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.7.25-0ubuntu0.18.04.2 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select json_array(b'0', b'1', b'10');
+--------------------------------------------------------------------+
| json_array(b'0', b'1', b'10')                                      |
+--------------------------------------------------------------------+
| ["base64:type16:AA==", "base64:type16:AQ==", "base64:type16:Ag=="] |
+--------------------------------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?
## In TIDB
```SQL
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-beta-321-gc6a757b24
Git Commit Hash: c6a757b2435965a72ada9d61ea8b7a367bd89b5f
Git Branch: master
UTC Build Time: 2019-04-02 02:38:04
GoVersion: go version go1.12.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.01 sec)

mysql> select json_array(b'0', b'1', b'10');
+--------------------------------+
| json_array(b'0', b'1', b'10')  |
+--------------------------------+
| ["\u0000", "\u0001", "\u0002"] |
+--------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #31918: The comparison between json and binary is different from MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1, t2;
create table t1 (a binary(13));
insert into t1 values('');
create table t2 (a json);
insert into t2 values ('"str"');
select * from t1 join t2 on t1.a <= t2.a;
```

### 2. What did you expect to see? (Required)

MySQL(5.7 && 8.0):
```
Empty set (0.03 sec)
```

### 3. What did you see instead (Required)
```
+---------------+-------+
| a             | a     |
+---------------+-------+
|               | "str" |
+---------------+-------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

afa1335f2

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #31918 , close #9996

Problem Summary:

The cast and comparison is incompatible with MySQL. It's because we didn't consider the "opaque json" values. With considering the opaque json, and add it to the comparison order (actually, it has been in the list for a while :laughing: ).

### What is changed and how it works?

This PR added a "Opaque JSON` values to store the binary strings. When this kind of json value is marshaled to the string, it's converted to `base64:typeXX:<base64 encoded string>`. It records both the mysql type (in `typeXX`), and the underlying binary data.

Considered three kinds of binary strings: `(.*)BLOB`, `BINARY`, `VARBINARY`. The `BLOB` and `VARBINARY` will not have extra zeros. However, the `BINARY` kind in opaque json will always have the same length (with padding zeros).

### Check List

Tests

- [x] Unit test
- [x] Manual test

Run the following SQL in both MySQL and TiDB:

```
drop table if exists t1, t2, t3, t4;
create table t1 (a binary(13));
insert into t1 values('');
create table t2 (a json);
insert into t2 values ('"str"');

create table t3 (a varbinary(13));
insert  into t3 values ('a');

create table t4 (a blob);
insert  into t4 values (x'AA');

select * from t1 join t2 on t1.a <= t2.a;
select cast(a as json) from t1;
select cast(a as json) from t3;
select cast(a as json) from t4;
```

### Release note

```release-note
Fix the issue that the cast and comparison between binary string and json is incompatible with MySQL
```

### CODE REVIEW

File: types/json/binary_functions.go [hunk 1]
```diff
@@ -51,6 +51,8 @@ func (bj BinaryJSON) Type() string {
 		return "DOUBLE"
 	case TypeCodeString:
 		return "STRING"
+	case TypeCodeOpaque:
+		return "OPAQUE"
```
Comment (xiongjiwei) [inline types/json/binary_functions.go:55]: not all opaque type will return "OPAQUE" directly, it sometimes returns `BLOB` or `BIT`. e.g.
```sql
mysql> select json_type(cast(0x41 as json));
+-------------------------------+
| json_type(cast(0x41 as json)) |
+-------------------------------+
| BLOB                          |
+-------------------------------+
```

Comment (YangKeao) [reply types/json/binary_functions.go]: Fixed.

`select json_type(cast(0x41 as json));` runs on MySQL 5.7.39 could return `BIT`, but in your comment (and TiDB situation) it will return `BLOB`. But I think it has nothing to do with the `JsonOpaque`.

**Comment by xiongjiwei** [comment]
maybe also close https://github.com/pingcap/tidb/issues/9996

File: expression/builtin_cast_vec.go [hunk 2]
```diff
@@ -788,8 +788,30 @@ func (b *builtinCastStringAsJSONSig) vecEvalJSON(input *chunk.Chunk, result *chu
...
+	if types.IsBinaryStr(typ) {
+		var res json.BinaryJSON
+		for i := 0; i < n; i++ {
+			if buf.IsNull(i) {
+				result.AppendNull()
+				continue
+			}
+
+			val := buf.GetString(i)
+			resultBuf := []byte(val)
```
Comment (xiongjiwei) [inline expression/builtin_cast_vec.go:801]: we can use `buf.GetBytes` here

File: types/json/binary.go [hunk 3]
```diff
@@ -192,6 +201,34 @@ func (bj BinaryJSON) GetString() []byte {
...
+type Opaque struct {
+	// TypeCode is the same with database type code
+	TypeCode byte
+	// Buf is the underlying bytes of the data
+	Buf []byte
+}
+
+// GetOpaque gets the opaque value
+func (bj BinaryJSON) GetOpaque() Opaque {
+	typ := bj.Value[0]
```
Comment (xiongjiwei) [inline types/json/binary.go:214]: in the comment, the opaque data is `opaque ::= data-length typeId byte*`, but here seems it is `opaque ::= typeId data-length byte*`

Comment (YangKeao) [reply types/json/binary.go:214]: Nice catch. I reordered the layout for the convenience to get the type, but forgot to modify the comments :crying_cat_face:

**Review by xiongjiwei — APPROVED** [review]

**Comment by xiongjiwei** [comment]
> maybe also close #9996 #25053

can you please take a look to if we can close these?

**Comment by YangKeao** [comment]
> can you please take a look to if we can close these?

Oops. The test case in #9996 makes it panic :facepalm: . Let me find the problem.

**Comment by YangKeao** [comment]
@xiongjiwei This PR does fix the #9998, but doesn't fix the https://github.com/pingcap/tidb/issues/25053. 

```
MySQL [test]> select cast(col_3 as json) from tbl_0;
+----------------------+
| cast(col_3 as json)  |
+----------------------+
| "base64:type15:bw==" |
+----------------------+
1 row in set (0.001 sec)

MySQL [test]> select json_objectagg( col_2, col_3 ) from tbl_0;
+--------------------------------+
| json_objectagg( col_2, col_3 ) |
+--------------------------------+
| {"1": "o"}                     |
+--------------------------------+
```

**Comment by YangKeao** [comment]
I think this PR is fine to merge. I'll fix https://github.com/pingcap/tidb/issues/25053 in another PR (it seems that there has been one contributed by the community :thinking: )

**Comment by xiongjiwei** [comment]
I will find another reviewer. The contributer does not update it for over one year, I think we can fix it by ourself

File: types/json/binary.go [hunk 4]
```diff
@@ -237,6 +274,13 @@ func (bj BinaryJSON) valEntryGet(valEntryOff int) BinaryJSON {
 		}
 		totalLen := uint32(lenLen) + uint32(strLen)
 		return BinaryJSON{TypeCode: tpCode, Value: bj.Value[valOff : valOff+totalLen]}
+	case TypeCodeOpaque:
+		strLen, lenLen := uint64(bj.Value[valOff+1]), 1
+		if strLen >= utf8.RuneSelf {
+			strLen, lenLen = binary.Uvarint(bj.Value[valOff+1:])
```
Comment (xhebox) [inline types/json/binary.go:280]: `binary.Uvarint` should have handled cases of `strLen > utf8.RuneSelf`, why manual? For performance?

**Review by xhebox — COMMENTED** [review]
LGTM

File: types/json/binary.go (hunk 4 above)
Comment (YangKeao) [reply types/json/binary.go]: I think it's fine to use the `binary.Uvarint` directly. I also modified the existing `GetString` implementation to use `binary.Uvarint` without the special condition.

PTAL

**Review by xhebox — APPROVED** [review]
