### PR TITLE
planner: Improve predicate simplification in logicalAnd

### LINKED ISSUE #61574: Cannot simplify the predicate in the subquery
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run ```TestExplainNonEvaledSubquery``` and note the case

```
explain format = 'brief' select * from t1 where exists(select 1 from t2 where a = (select a from t3 limit 1) and b = a);
```

### 2. What did you expect to see? (Required)

```
└─Selection 6400.00 root  eq(cast(test.t2.a, double BINARY), cast(ScalarQueryCol#13, double BINARY)), eq(cast(test.t2.b, double BINARY)
```

### 3. What did you see instead (Required)

```
└─Selection 6400.00 root  eq(cast(test.t2.a, double BINARY), cast(ScalarQueryCol#13, double BINARY)), eq(cast(test.t2.b, double BINARY), cast(ScalarQueryCol#13, double BINARY))",
```

it has two same ```cast(ScalarQueryCol#13, double BINARY))```
### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/commit/22b49eab5b57808b6c743d8c8ae51050ae527534

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #61574

Problem Summary:

### What changed and how does it work?

Before this PR, ```expression.PropagateConstant``` and ```constraint.DeleteTrueExprs``` were called in ```ApplyPredicateSimplification```, but with many additional restrictions that led to only partial simplification and prevented full simplification from being achieved. They were not subsets of ```ApplyPredicateSimplification```. Now that they have been added, they can provide more complete simplification capabilities.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/rule_predicate_simplification.go [hunk 1]
```diff
@@ -187,7 +188,9 @@ func applyPredicateSimplification(sctx base.PlanContext, predicates []expression
 	simplifiedPredicate = mergeInAndNotEQLists(sctx, simplifiedPredicate)
 	removeRedundantORBranch(sctx, simplifiedPredicate)
 	pruneEmptyORBranches(sctx, simplifiedPredicate)
-	simplifiedPredicate = splitCNF(simplifiedPredicate)
+	exprCtx := sctx.GetExprCtx()
+	simplifiedPredicate = expression.PropagateConstant(exprCtx, simplifiedPredicate)
```
Comment (hawkingrei) [inline pkg/planner/core/rule_predicate_simplification.go:182]: ```splitCNF``` has been in the ```PropagateConstant```

**Review by AilinKid — APPROVED** [review]

**Review by winoros — APPROVED** [review]
