### PR TITLE
planner: fixed index out of range, in explicit partition pruning

### LINKED ISSUE #62458: `DELETE ... PARTITION` statement meets runtime error
## Bug Report

`DELETE ... PARTITION` statement meets runtime error. It can be reproduced on the docker image `pingcap/tidb:nightly`.

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t (c1 INT, c2 VARCHAR(255)) PARTITION BY LIST (c1) (PARTITION p1 VALUES IN (1, 2, 3), PARTITION p2 VALUES IN (4, 5, 6));
CREATE UNIQUE INDEX i ON t (c1);
DELETE FROM t PARTITION (p1) WHERE c1 = 15;
```

### 2. What did you expect to see? (Required)

No runtime error.

### 3. What did you see instead (Required)

```sql
mysql> DELETE FROM t PARTITION (p1) WHERE c1 = 15;
ERROR 1105 (HY000): runtime error: index out of range [-1]
```

Logs:
```
[2025/07/16 13:51:38.626 +00:00] [ERROR] [conn.go:1047] ["connection running loop panic"] [conn=2097176] [session_alias=] 
[lastSQL="DELETE FROM t PARTITION (p1) WHERE c1 = 15"] 
[err="runtime error: index out of range [-1]"] 
github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1
        /workspace/source/tidb/pkg/server/conn.go:1050
runtime.gopanic
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.11.linux-amd64/src/runtime/panic.go:791
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec.func1
        /workspace/source/tidb/pkg/executor/adapter.go:544
runtime.gopanic
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.11.linux-amd64/src/runtime/panic.go:791
runtime.goPanicIndex
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.11.linux-amd64/src/runtime/panic.go:115
github.com/pingcap/tidb/pkg/planner/core.isInExplicitPartitions
        /workspace/source/tidb/pkg/planner/core/point_get_plan.go:678
github.com/pingcap/tidb/pkg/planner/core.(*PointGetPlan).PrunePartitions
        /workspace/source/tidb/pkg/planner/core/point_get_plan.go:424
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildPointGet
        /workspace/source/tidb/pkg/executor/point_get.go:59
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build
        /workspace/source/tidb/pkg/executor/builder.go:200
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildDelete
        /workspace/source/tidb/pkg/executor/builder.go:2936
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build
        /workspace/source/tidb/pkg/executor/builder.go:192
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).buildExecutor
        /workspace/source/tidb/pkg/executor/adapter.go:1283
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec
        /workspace/source/tidb/pkg/executor/adapter.go:624
github.com/pingcap/tidb/pkg/session.runStmt
        /workspace/source/tidb/pkg/session/session.go:2358
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt
        /workspace/source/tidb/pkg/session/session.go:2210
github.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt
        /workspace/source/tidb/pkg/server/driver_tidb.go:291
github.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt
        /workspace/source/tidb/pkg/server/conn.go:2038
github.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery
        /workspace/source/tidb/pkg/server/conn.go:1794
github.com/pingcap/tidb/pkg/server.(*clientConn).dispatch
        /workspace/source/tidb/pkg/server/conn.go:1384
github.com/pingcap/tidb/pkg/server.(*clientConn).Run
        /workspace/source/tidb/pkg/server/conn.go:1153
github.com/pingcap/tidb/pkg/server.(*Server).onConn
        /workspace/source/tidb/pkg/server/server.go:740
```

### 4. What is your TiDB version? (Required)

```
Release Version: v9.0.0-beta.2.pre-118-g6ec4810
Edition: Community
Git Commit Hash: 6ec48101cae75529682a0f9fa8c16cbc42f246d3
Git Branch: HEAD
UTC Build Time: 2025-07-16 11:00:02
GoVersion: go1.23.11
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Kernel Type: Classic
```

### PR DESCRIPTION
**Pull request by yihong0618**
### What problem does this PR solve?

This patch close issue 62458 by check the err first in PrunePartitions

because in isInExplicitPartitions idx can be -1 if err

```go
	s := pi.Definitions[idx].Name.L
```

cc @hawkingrei @fuboat @lance6716 
 

Issue Number: close #62458

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by yihong0618** [comment]
merged main

File: pkg/planner/core/point_get_plan.go [hunk 1]
```diff
@@ -422,8 +422,14 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
 	partIdx, err := pt.GetPartitionIdxByRow(sctx.GetExprCtx().GetEvalCtx(), row)
 	partIdx, err = pt.Meta().Partition.ReplaceWithOverlappingPartitionIdx(partIdx, err)
-	noMatch := !isInExplicitPartitions(pi, partIdx, p.PartitionNames)
-	if err != nil || noMatch || partIdx < 0 {
+
+	// partIdx can be -1 more to check issue #62458
+	noMatch := false
+	if err == nil {
+		noMatch = !isInExplicitPartitions(pi, partIdx, p.PartitionNames)
+	}
```
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go]: I think it is better to let `isInExplicitPartitions()` handle the case where partIdx < 0 or > len(pi.Definitions), since there are at least one more place where this could happen.

Comment (mjonss) [inline pkg/planner/core/point_get_plan.go]: Great find and thank you for the PR!

I think it is better to let `isInExplicitPartitions()` handle the case where partIdx < 0 or > len(pi.Definitions), since there is at least one more place where this could happen.

Maybe something like:
```diff
diff --git a/pkg/planner/core/point_get_plan.go b/pkg/planner/core/point_get_plan.go
index de7d766310..8856b5a675 100644
--- a/pkg/planner/core/point_get_plan.go
+++ b/pkg/planner/core/point_get_plan.go
@@ -676,6 +676,9 @@ func isInExplicitPartitions(pi *model.PartitionInfo, idx int, names []ast.CIStr)
        if len(names) == 0 {
                return true
        }
+       if pi == nil || idx < 0 || idx >= len(pi.Definitions) {
+               return false
+       }
        s := pi.Definitions[idx].Name.L
        for _, name := range names {
                if s == name.L {
```

**Comment by mjonss** [comment]
Please also update the title according to the format in https://github.com/pingcap/community/blob/master/contributors/commit-message-pr-style.md#commit-message-and-pull-request-style

Like:
planner: fixed index out of range, in explicit partition pruning

**Comment by yihong0618** [comment]
addressed and added co-author and fix the title 
thank you very much

**Review by mjonss — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]
