### PR TITLE
planner: apply predicate simplification before extract condition

### LINKED ISSUE #62212: SQL with join failed to build executor
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Found from instance plan cache test

```SQL
drop table t1, t2 if exists;

create table t1 (c0 int, c1 int);

create table t2 (c0 int, c1 int);

select * from t1 join t2 on t1.c0 = t2.c0
	where t2.c1 = null or t2.c1 > 0 and t1.c1 > 0;
```

### 2. What did you expect to see? (Required)

succeed

### 3. What did you see instead (Required)

```sql
ERROR 8118 (HY000): Failed to build executor   
```

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #62212

Problem Summary:

### What changed and how does it work?

This is introduced by https://github.com/pingcap/tidb/pull/61739, where we apply predicate simplification after extracting condition.

image

Considering the following case:

```SQL
create table t1 (c0 int, c1 int);

create table t2 (c0 int, c1 int);

select * from t1 join t2 on t1.c0 = t2.c0
	where t2.c1 = null or t2.c1 > 0 and t1.c1 > 0;
```

After `ApplyPredicateSimplification`, we get `t1.c1 > 0` and `t2.c1 > 0` in `OtherConditions`, and these conditions will be set in `LeftConditions` and `RightConditions` of physical join respectively.

Then we fail to build hash join executor:

```SQL
mysql> select * from t1 join t2 on t1.c0 = t2.c0 where t2.c1 = null or t2.c1 > 0 and t1.c1 > 0;                                                                            
ERROR 8118 (HY000): Failed to build executor    
```

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 1]
```diff
@@ -256,7 +256,7 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression, opt
 		tempCond = append(tempCond, p.OtherConditions...)
 		tempCond = append(tempCond, predicates...)
 		tempCond = expression.ExtractFiltersFromDNFs(p.SCtx().GetExprCtx(), tempCond)
-		tempCond = expression.PropagateConstant(p.SCtx().GetExprCtx(), tempCond...)
+		tempCond = utilfuncp.ApplyPredicateSimplification(p.SCtx(), tempCond, true)
```
Comment (hawkingrei) [inline pkg/planner/core/operator/logicalop/logical_join.go:259]: PreopagateConstant has contained in the ```utilfuncp.ApplyPredicateSimplification```

**Review by AilinKid — APPROVED** [review]
