### PR TITLE
*: new secondary index value format

### LINKED ISSUE #19942: *: unexpected error with both new collation and clustered index are enabled.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Set `new_collations_enabled_on_first_bootstrap` to `True` and start a new cluster.

Enable `CLUSTERED INDEX`:

```
SET @@tidb_enable_clustered_index=1;
```

```
CREATE TABLE test.`t` (
    `a` int(11) NOT NULL,
    `b` int(11) NOT NULL,
    `c` varchar(50) COLLATE utf8_general_ci NOT NULL,
    `s` tinyint(1) NOT NULL,
    PRIMARY KEY (`c`),
    KEY `a_idx` (`a`),
    KEY `b_idx` (`b`),
    KEY `s_idx` (`s`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO test.t (a, b, c, s) VALUES (1, 1, '0', 1);

SELECT * FROM `test`.`t` FORCE INDEX(`a_idx`);
```

### 2. What did you expect to see? (Required)
```
Query succeeded.
```

### 3. What did you see instead (Required)
```
tidb> SELECT * FROM `test`.`t` force index(`a_idx`);
ERROR 1105 (HY000): inconsistent index a_idx handle count 1 isn't equal to value count 0
```
It looks that the value of the secondary index `a_idx` is missing.

### 4. What is your TiDB version? (Required)
```
Release Version: v4.0.0-beta.2-1184-g8a1f11ece
Edition: Community
Git Commit Hash: 8a1f11eceed2a0f6d9a11cb124267a6d9bb86e2c
Git Branch: master
UTC Build Time: 2020-09-10 17:17:28
GoVersion: go1.15beta1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

1. Optimized _bin collation.
2. Only write the restored data for the new collation column in composed indexes. 
3. Write restored data for the new collation column in the common handle.

Fix #19942 completely.

### What is changed and how it works?

1. When creating the clustered index, set the CommonHandleVersion to 1.
2. Add a method `TryGetHandleRestoredDataWrapper` to get the restored data for the clustered index. Ignore it if the version is 0.
3. Add a parameter(handleRestoreData) for index.create.
4. Add rsData(restored data for handle) to struct `indexRecord` and `recoverRows`.
5. IndexLookUpExecutor.getHandle(), for previous logic, add condition `e.table.Meta().CommonHandleVersion == 0`.
6. DataSource.isCoveringIndex(), for previous logic,  add condition `e.table.Meta().CommonHandleVersion == 0`.
7.  Remove interface and the implementation of GenIndexValue, use GenIndexValuePortal instead.
8. Change containNonBinaryString to needRestoredData. NeedRestoredData() is more accurate than ContainsNonBinaryString().
9. Add IndexVersionFlag 125.
10. Implement decodeIndexKvForClusteredIndexVersion1()
11. Implement getIndexVersion()
12. In DecodeHandleInUniqueIndexValue(), handle case ClusteredIndexVersion1
13. In decodeHandleInIndexValue(), handle case ClusteredIndexVersion1

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

File: tablecodec/tablecodec.go [hunk 1]
```diff
@@ -956,14 +1049,34 @@ func GenIndexKey(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo
...
+			pkColIds = append(pkColIds, tbl.Columns[idxCol.Offset].ID)
+		}
+	}
+	return pkColIds
 }
 
 // GenIndexValueNew create index value for both local and global index.
-func GenIndexValueNew(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo *model.IndexInfo, containNonBinaryString bool,
-	distinct bool, untouched bool, indexedValues []types.Datum, h kv.Handle, partitionID int64) ([]byte, error) {
+func GenIndexValueNew(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo *model.IndexInfo, needRestoredData bool, distinct bool, untouched bool, indexedValues []types.Datum, h kv.Handle, partitionID int64, restoredData []types.Datum) ([]byte, error) {
```
Comment (tangenta) [inline tablecodec/tablecodec.go:1079]: It sounds unreasonable that a function has both `needRestoredData bool` and `restoredData []types.Datum` at the same time.

File: tablecodec/tablecodec.go [hunk 2]
```diff
@@ -975,13 +1088,30 @@ func GenIndexValueNew(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, id
...
+				} else {
+					allRestoredData = append(allRestoredData, indexedValues[i])
+				}
+			}
+		}
+
+		if len(restoredData) > 0 {
+			pkColIds := TryGetCommonPkColumnRestoredIds(tblInfo)
+			colIds = append(colIds, pkColIds...)
+			allRestoredData = append(allRestoredData, restoredData...)
```
Comment (tangenta) [inline tablecodec/tablecodec.go:1110]: If a plain index contains a common handle column, there will be a redundancy.

File: table/tables/index_test.go [hunk 3]
```diff
@@ -354,12 +364,23 @@ func (s *testIndexSuite) TestMultiColumnCommonHandle(c *C) {
...
+		colInfo = append(colInfo, rowcodec.ColInfo{
+			ID:         a.ID,
+			IsPKHandle: false,
+			Ft:         rowcodec.FieldTypeFromModelColumn(a),
+		})
+		colInfo = append(colInfo, rowcodec.ColInfo{
+			ID:         b.ID,
+			IsPKHandle: false,
+			Ft:         rowcodec.FieldTypeFromModelColumn(b),
+		})
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply table/tables/index_test.go:381]: Then we need to get pkIdx, I think it's ok here because it's test code.

File: tablecodec/tablecodec.go (hunk 1 above)
Comment (wjhuang2016) [reply tablecodec/tablecodec.go:1079]: Yeah, you're right. restoredData means handle's restored data. needRestoredData means index values' restored data. I will rename it.

File: table/tables/index.go [hunk 4]
```diff
@@ -176,7 +179,7 @@ func (c *index) GenIndexKey(sc *stmtctx.StatementContext, indexedValues []types.
 //		   If neither Handle nor UntouchedFlag exists, value will be one single byte '0' (i.e. []byte{'0'}).
 //		   Length of value <= 9, use to distinguish from the new encoding.
 //
-func (c *index) Create(sctx sessionctx.Context, us kv.UnionStore, indexedValues []types.Datum, h kv.Handle, opts ...table.CreateIdxOptFunc) (kv.Handle, error) {
+func (c *index) Create(sctx sessionctx.Context, us kv.UnionStore, indexedValues []types.Datum, h kv.Handle, handleRestoreData []types.Datum, opts ...table.CreateIdxOptFunc) (kv.Handle, error) {
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply table/tables/index.go:182]: indexValues is not restoreData.

File: table/tables/tables.go [hunk 5]
```diff
@@ -1671,6 +1673,43 @@ func (t *TableCommon) GetSequenceCommon() *sequenceCommon {
...
+		if !types.NeedRestoredData(&col.FieldType) {
+			continue
+		}
+		if collate.IsBinCollation(col.Collate) {
+			if useIDMap {
+				datum = rowMap[col.ID]
+			} else {
+				datum = row[col.Offset]
+			}
+			rsData = append(rsData, types.NewIntDatum(stringutil.GetTailSpaceCount(datum.GetString())))
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply table/tables/tables.go:1700]: Yeah, but putting the TryGetHandleRestoredDataWrapper's logic into GenIndexValueNew is also dirty. I think it's acceptable here,

File: expression/integration_test.go [hunk 6]
```diff
@@ -7550,6 +7550,53 @@ func (s *testIntegrationSuite) TestIssue17476(c *C) {
...
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t(a int, b char(10) collate utf8mb4_bin, c char(10) collate utf8mb4_general_ci," +
+		"d varchar(10) collate utf8mb4_bin, e varchar(10) collate utf8mb4_general_ci," +
+		"primary key(a, b, c, d, e), key a(a), unique key ua(a), key b(b), unique key ub(b), key c(c), unique key uc(c)," +
+		"key d(d), unique key ud(d),key e(e), unique key ue(e))")
+
+	// Single Read.
+	tk.MustExec("insert into t values (1, '啊  ', '啊  ', '啊  ', '啊  ')")
+	tk.MustQuery("select * from t ").Check(testkit.Rows("1 啊 啊 啊   啊  "))
+	tk.MustQuery("select * from t use index(a)").Check(testkit.Rows("1 啊 啊 啊   啊  "))
```
Comment (coocood) [inline expression/integration_test.go:7568]: use `testutil.RowsWithSep("|",` would be more clear

File: tablecodec/tablecodec.go [hunk 7]
```diff
@@ -729,6 +755,73 @@ func decodeRestoredValues(columns []rowcodec.ColInfo, restoredVal []byte) ([][]b
...
+		if collate.IsBinCollation(columns[allOffset].Ft.Collate) {
+			noPaddingStr, err := DecodeColumnValue(keyVal[allOffset], columns[allOffset].Ft, nil)
+			if err != nil {
+				return nil, errors.Trace(err)
+			}
+			paddingCount, err := DecodeColumnValue(restoredValues[offset], types.NewFieldType(mysql.TypeLonglong), nil)
+			if err != nil {
+				return nil, errors.Trace(err)
+			}
+			noPaddingStr.SetString(noPaddingStr.GetString()+strings.Repeat(" ", int(paddingCount.GetInt64())), noPaddingStr.Collation())
```
Comment (coocood) [inline tablecodec/tablecodec.go:813]: We can skip if padding count is 0.

Comment (coocood) [reply tablecodec/tablecodec.go:813]: And we don't need to Decode `noPaddingStr`.

File: tablecodec/tablecodec.go [hunk 8]
```diff
@@ -715,6 +719,28 @@ func reEncodeHandle(handle kv.Handle, unsigned bool) ([][]byte, error) {
...
+		intHandleBytes, err := codec.EncodeValue(nil, nil, handleDatum)
+		return [][]byte{intHandleBytes}, err
+	}
+
+	handleColLen := handle.NumCols()
+	cHandleBytes := make([][]byte, 0, handleColLen)
+	for i := 0; i < handleColLen; i++ {
+		cHandleBytes = append(cHandleBytes, handle.EncodedCol(i))
+	}
+	if len(restoreData) == 0 {
```
Comment (coocood) [inline tablecodec/tablecodec.go:738]: If len(restoredData) > 0, we don't need to create `cHandleBytes`.

File: tablecodec/tablecodec.go [hunk 9]
```diff
@@ -729,6 +755,73 @@ func decodeRestoredValues(columns []rowcodec.ColInfo, restoredVal []byte) ([][]b
...
+
+	// Collate some information, restoredColumns means the columns whose value need to restore from the index value.
+	for i, col := range columns {
+		if types.NeedRestoredData(col.Ft) {
+			colIDs[col.ID] = j
+			restoredData2All[j] = i
+			j++
+			copyColInfo := rowcodec.ColInfo{
+				ID: col.ID,
+				Ft: columns[i].Ft.Clone(),
```
Comment (coocood) [inline tablecodec/tablecodec.go:779]: We don't need to clone the field type.

File: tablecodec/tablecodec.go [hunk 10]
```diff
@@ -729,6 +755,73 @@ func decodeRestoredValues(columns []rowcodec.ColInfo, restoredVal []byte) ([][]b
...
+	restoredColumns := make([]rowcodec.ColInfo, 0, len(columns))
+	j := 0
+
+	// Collate some information, restoredColumns means the columns whose value need to restore from the index value.
+	for i, col := range columns {
+		if types.NeedRestoredData(col.Ft) {
+			colIDs[col.ID] = j
+			restoredData2All[j] = i
+			j++
+			copyColInfo := rowcodec.ColInfo{
```
Comment (coocood) [inline tablecodec/tablecodec.go:777]: If the column is not BinCollation, we don't need to copy col.

File: tablecodec/tablecodec.go [hunk 11]
```diff
@@ -729,6 +755,73 @@ func decodeRestoredValues(columns []rowcodec.ColInfo, restoredVal []byte) ([][]b
...
+// decodeRestoredValuesV5 decodes index values whose format is introduced in TiDB 5.0.
+// Unlike the format in TiDB 4.0, the new format is optimized for storage space:
+// 1. If the index is a composed index, only the non-binary string column's value need to write to value, not all.
+// 2. If a string column's collation is _bin, then we only write the number of the truncated spaces to value.
+// 3. If a string column is char, not varchar, then we use the sortKey directly.
+func decodeRestoredValuesV5(columns []rowcodec.ColInfo, keyVal [][]byte, restoredVal []byte) ([][]byte, error) {
+	colIDs := make(map[int64]int, len(columns))
+	result := make([][]byte, len(columns))
+	// restoredData2All is the map from the offset in restoredColumns to the offset in columns.
+	restoredData2All := make(map[int]int)
```
Comment (coocood) [inline tablecodec/tablecodec.go:767]: We can use a slice instead of a map.

File: tablecodec/tablecodec.go [hunk 12]
```diff
@@ -980,13 +1093,33 @@ func GenIndexValueNew(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, id
...
+	if collate.NewCollationEnabled() && (IdxValNeedRestoredData || len(handleRestoredData) > 0) {
+		idxVal = append(idxVal, RestoredDataV5)
+
+		colIds := make([]int64, 0, len(idxInfo.Columns))
+		allRestoredData := make([]types.Datum, 0, len(handleRestoredData)+len(idxInfo.Columns))
+		for i, idxCol := range idxInfo.Columns {
+			col := tblInfo.Columns[idxCol.Offset]
+			// If handle is common handle and the column is the primary key's column,
+			// the restored data will be written later. Skip writing it here to avoid redundancy.
+			if (h.IsInt() || !mysql.HasPriKeyFlag(col.Flag)) && types.NeedRestoredData(&col.FieldType) {
```
Comment (coocood) [inline tablecodec/tablecodec.go:1105]: The condition is too complex.

How about
```
if !h.IsInt() && mysql.HasPriKeyFlag(col.Flag) {
    continute
}

```

File: tablecodec/tablecodec.go (hunk 9 above)
Comment (wjhuang2016) [reply tablecodec/tablecodec.go]: Otherwise, it would be modified.

Comment (coocood) [reply tablecodec/tablecodec.go]: It's a pointer, we just change the pointer value, the content if the type is not changed.

File: expression/integration_test.go [hunk 13]
```diff
@@ -7552,6 +7552,53 @@ func (s *testIntegrationSuite) TestIssue17476(c *C) {
 	tk.MustQuery(`SELECT * FROM (table_int_float_varchar AS tmp3) WHERE (col_varchar_6 AND NULL) IS NULL AND col_int_6=0;`).Check(testkit.Rows("13 0 -0.1 <nil>"))
 }
 
+func (s *testIntegrationSerialSuite) TestClusteredIndexAndNewCollationIndexEncodeDecodeV5(c *C) {
```
Comment (coocood) [inline expression/integration_test.go:7555]: Need to test unicode_ci?

**Comment by coocood** [comment]
LGTM

**Comment by wjhuang2016** [comment]
Wait for TiKV PR

File: tablecodec/tablecodec.go [hunk 14]
```diff
@@ -964,15 +1071,95 @@ func GenIndexKey(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo
...
+	for _, idxCol := range pkIdx.Columns {
+		if types.NeedRestoredData(&tbl.Columns[idxCol.Offset].FieldType) {
+			pkColIds = append(pkColIds, tbl.Columns[idxCol.Offset].ID)
+		}
+	}
+	return pkColIds
+}
+
+// GenIndexValueNewForClusteredIndexVersion1 generates the index value for the clustered index with version 1(New in v5.0.0).
+func GenIndexValueNewForClusteredIndexVersion1(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo *model.IndexInfo, IdxValNeedRestoredData bool, distinct bool, untouched bool, indexedValues []types.Datum, h kv.Handle, partitionID int64, handleRestoredData []types.Datum) ([]byte, error) {
```
Comment (coocood) [inline tablecodec/tablecodec.go:1105]: We can remove the `New` in the name since we have `Version1`.

File: tablecodec/tablecodec.go [hunk 15]
```diff
@@ -964,15 +1071,95 @@ func GenIndexKey(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo
...
+	idxVal[0] = byte(tailLen)
+
+	return idxVal, nil
 }
 
-// GenIndexValueNew create index value for both local and global index.
-func GenIndexValueNew(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo *model.IndexInfo, containNonBinaryString bool,
-	distinct bool, untouched bool, indexedValues []types.Datum, h kv.Handle, partitionID int64) ([]byte, error) {
+// genIndexValueNew create index value for both local and global index.
+func genIndexValueNew(sc *stmtctx.StatementContext, tblInfo *model.TableInfo, idxInfo *model.IndexInfo, IdxValNeedRestoredData bool, distinct bool, untouched bool, indexedValues []types.Datum, h kv.Handle, partitionID int64) ([]byte, error) {
```
Comment (coocood) [inline tablecodec/tablecodec.go:1162]: Can we name it `Version0` instead of `New`?

File: tablecodec/tablecodec.go (hunk 14 above)
Comment (wjhuang2016) [reply tablecodec/tablecodec.go:1105]: Yeah

File: tablecodec/tablecodec.go (hunk 15 above)
Comment (coocood) [reply tablecodec/tablecodec.go:1162]: But at least it's not new anymore.

File: table/tables/tables.go [hunk 16]
```diff
@@ -1710,6 +1713,43 @@ func (t *TableCommon) GetSequenceCommon() *sequenceCommon {
 	return t.sequence
 }
 
+// TryGetHandleRestoredDataWrapper tries to get the restored data. The argument can be a slice or a map.
+func (t *TableCommon) TryGetHandleRestoredDataWrapper(row []types.Datum, rowMap map[int64]types.Datum) []types.Datum {
```
Comment (coocood) [inline table/tables/tables.go:1717]: Should we truncate the restored data by prefix?

File: ddl/index.go [hunk 17]
```diff
@@ -897,6 +898,7 @@ func (w *baseIndexWorker) getIndexRecord(idxInfo *model.IndexInfo, handle kv.Han
 		}
 	})
 	idxVal := make([]types.Datum, len(idxInfo.Columns))
+	rsData := make([]types.Datum, len(idxInfo.Columns))
```
Comment (tangenta) [inline ddl/index.go:901]:
```suggestion
	var rsData []types.Datum
```

File: ddl/index.go [hunk 18]
```diff
@@ -1127,7 +1132,12 @@ func (w *addIndexWorker) batchCheckUniqueKey(txn kv.Transaction, idxRecords []*i
 		} else if w.distinctCheckFlags[i] {
 			// The keys in w.batchCheckKeys also maybe duplicate,
 			// so we need to backfill the not found key into `batchVals` map.
-			val, err := w.index.GenIndexValue(stmtCtx, idxRecords[i].vals, w.distinctCheckFlags[i], false, idxRecords[i].handle)
+			var rsData []types.Datum
+			if t, ok := w.table.(*tables.TableCommon); ok {
+				rsData = t.TryGetHandleRestoredDataWrapper(idxRecords[i].vals, nil)
+			}
```
Comment (tangenta) [inline ddl/index.go:1138]: How about the partitioned table?

```sql
drop table if exists t;
create table t (a varchar(255) COLLATE utf8_general_ci primary key clustered, b int) partition by range columns(a) 
(partition p0 values less than ('0'), partition p1 values less than MAXVALUE);
alter table t add index b;
insert into t values ('0', 1);
```

```sql
select * from t use index(b);

+---+------+
| a | b    |
+---+------+
| NULL |    1 |
+---+------+
```

```sql
select * from t ignore index(b);

+---+------+
| a | b    |
+---+------+
| 0 |    1 |
+---+------+
```

Comment (tangenta) [reply ddl/index.go:1138]: I think `TryGetHandleRestoredDataWrapper` can be refactored to accept a `table.Table` interface as an argument.

File: tablecodec/tablecodec.go [hunk 19]
```diff
@@ -719,6 +723,19 @@ func reEncodeHandle(handle kv.Handle, unsigned bool) ([][]byte, error) {
 	return [][]byte{intHandleBytes}, err
 }
 
+// reEncodeHandleConsiderNewCollation encodes the handle as a Datum so it can be properly decoded later.
+func reEncodeHandleConsiderNewCollation(handle kv.Handle, columns []rowcodec.ColInfo, restoreData []byte, unsigned bool) ([][]byte, error) {
```
Comment (tangenta) [inline tablecodec/tablecodec.go:727]:
```suggestion
func reEncodeHandleConsiderNewCollation(handle kv.Handle, columns []rowcodec.ColInfo, restoreData []byte) ([][]byte, error) {
```

The `unsigned` parameter is unused.

**Review by tangenta — COMMENTED** [review]
/lgtm

**Review by tangenta — APPROVED** [review]

**Comment by wjhuang2016** [comment]
I found a bug related to TryGetHandleRestoredDataWrapper.

File: planner/core/handle_cols.go [hunk 20]
```diff
@@ -256,3 +256,17 @@ func (ib *IntHandleCols) GetFieldsTypes() []*types.FieldType {
 func NewIntHandleCols(col *expression.Column) HandleCols {
 	return &IntHandleCols{col: col}
 }
+
+func GetHandleDatum(cols HandleCols, row chunk.Row) []types.Datum {
```
Comment (coocood) [inline planner/core/handle_cols.go:260]: I think the name should be `GetCommanHandleDatums`

File: session/schema_amender.go [hunk 21]
```diff
@@ -406,6 +407,19 @@ func (a *amendOperationAddIndex) genMutations(ctx context.Context, sctx sessionc
 	return nil
 }
 
+func getHandleDatum(tbl table.Table, row chunk.Row) []types.Datum {
```
Comment (coocood) [inline session/schema_amender.go:410]: ditto

File: planner/core/handle_cols.go [hunk 22]
```diff
@@ -256,3 +256,17 @@ func (ib *IntHandleCols) GetFieldsTypes() []*types.FieldType {
 func NewIntHandleCols(col *expression.Column) HandleCols {
 	return &IntHandleCols{col: col}
 }
+
```
Comment (coocood) [inline planner/core/handle_cols.go:259]: Need comment
