### PR TITLE
server: Skip checking sequence number of the sub header when compression protocol is active

### LINKED ISSUE #49845: Metabase connection tidb  error unexpected end of stream, read 0 bytes from 7 (socket was closed by server)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Metabase v0.48.1 [Latest](https://github.com/metabase/metabase/releases/latest)
2. TIDB version 7.5
3. Connect to TiDB and establish an SQL query.
4. Control panel returns(unexpected end of stream, read 0 bytes from 7 (socket was closed by server))

Similar problems：https://asktug.com/t/topic/1019620
### 4. What is your TiDB version? (Required)
Release Version: v7.5.0
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-24 08:50:14
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by onlyacat**
### What problem does this PR solve?

Issue Number: close #49845

Problem Summary:

Make TiDB be compatible with MariaDB Java Connecter 2.X.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/internal/packetio_test.go [hunk 1]
```diff
@@ -424,3 +424,35 @@ func TestCompressedReaderLong(t *testing.T) {
 		require.Equal(t, expected, data)
 	})
 }
+
+// MariaDB Java Connecter 2.X would generate wrong sequence number for the sub header.
+// TiDB should be compatible with it.
+//
+// Header:
```
Comment (dveeden) [inline pkg/server/internal/packetio_test.go:431]:
```suggestion
// MySQL Compressed Protocol Header:
```

File: pkg/server/internal/packetio.go [hunk 2]
```diff
@@ -150,19 +150,21 @@ func (p *PacketIO) readOnePacket() ([]byte, error) {
...
 		if _, err := io.ReadFull(p.compressedReader, header[:]); err != nil {
 			return nil, errors.Trace(err)
 		}
 	}
 
 	length := int(uint32(header[0]) | uint32(header[1])<<8 | uint32(header[2])<<16)
-	sequence := header[3]
-
-	if sequence != p.sequence {
-		return nil, server_err.ErrInvalidSequence.GenWithStack(
```
Comment (dveeden) [inline pkg/server/internal/packetio.go:163]: Maybe we could log an error instead of returning? Then we can still keep this runtime check.

File: pkg/server/internal/packetio.go [hunk 3]
```diff
@@ -150,19 +150,21 @@ func (p *PacketIO) readOnePacket() ([]byte, error) {
 		if _, err := io.ReadFull(r, header[:]); err != nil {
 			return nil, errors.Trace(err)
 		}
+
+		// To be compatible with MariaDB Java Connecter 2.X,
```
Comment (dveeden) [inline pkg/server/internal/packetio.go:154]:
```suggestion
		// To be compatible with MariaDB Connector/J 2.x, 
```

This seems to be the product name according to https://mariadb.com/kb/en/about-mariadb-connector-j/

File: pkg/server/internal/packetio.go (hunk 2 above)
Comment (onlyacat) [reply pkg/server/internal/packetio.go:163]: > Maybe we could log an error instead of returning? Then we can still keep this runtime check.

Yeah. For the normal packet, the sequence check is supposed to be passed. As for the compressed packet, we generate a log and then let the process continue. Did I get that right?

File: pkg/server/internal/packetio.go [hunk 4]
```diff
@@ -150,19 +150,21 @@ func (p *PacketIO) readOnePacket() ([]byte, error) {
 		if _, err := io.ReadFull(r, header[:]); err != nil {
 			return nil, errors.Trace(err)
 		}
+
+		// To be compatible with MariaDB Connector/J 2.x,
```
Comment (lance6716) [inline pkg/server/internal/packetio.go:154]:
```suggestion
		// To be compatible with MariaDB Connector/J 2.x,
```

please format this file using your IDE or `make fmt`

Comment (onlyacat) [reply pkg/server/internal/packetio.go:154]: Done. Sorry, forgot to fmt the code

File: pkg/server/internal/packetio.go (hunk 2 above)
Comment (dveeden) [reply pkg/server/internal/packetio.go:163]: Yes indeed.

File: pkg/server/internal/packetio_test.go [hunk 5]
```diff
@@ -424,3 +424,35 @@ func TestCompressedReaderLong(t *testing.T) {
...
+	brc := util.NewBufferedReadConn(&testutil.BytesConn{Buffer: inBuffer})
+	pkt := NewPacketIO(brc)
+	pkt.SetCompressionAlgorithm(mysql.CompressionZlib)
+	readBytes, err := pkt.ReadPacket()
+	require.NoError(t, err)
+	require.Equal(t, uint8(1), pkt.sequence)
+	require.Equal(t, uint8(1), pkt.compressedSequence)
+	require.Equal(t, []byte{0x03, 0x73, 0x65, 0x6c, 0x65, 0x63,
+		0x74, 0x20, 0x31, 0x3b}, readBytes)
+
```
Comment (dveeden) [inline pkg/server/internal/packetio_test.go:457]:
```
pkg/server/internal/packetio_test.go:441:57: empty-lines: extra empty line at the end of a block (all_revive)
```

```suggestion
```

**Comment by lance6716** [comment]
You can check these links to see why CI is failed
image
scroll down and you will see
image

**Comment by onlyacat** [comment]
Not sure but the failed tasks seem not to be related to the commit, right 🤔? 
```
    testkit.go:454: 
        	Error Trace:	pkg/testkit/testkit.go:454
        	            				pkg/executor/recover_test.go:580
        	Error:      	Error message not equal:
        	            	expected: "Can't find dropped database: db_not_exists in DDL history jobs"
        	            	actual  : "Can't find dropped database 'db_not_exists' in GC safe point 2024-01-06 04:31:39.411 +0000 UTC"
        	Test:       	TestFlashbackSchema
```

```
================================================================================
[11,717 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 285s remote ... (89 actions running)
[11,719 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 287s remote ... (89 actions running)
[11,720 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 288s remote ... (89 actions running)
[11,721 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 289s remote ... (89 actions running)
[11,722 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 291s remote ... (89 actions running)
FAIL: //pkg/executor:executor_test (shard 6 of 50) (see /root/.cache/bazel/_bazel_root/37ff7b0eddea115f60ab9f853788d7f5/execroot/__main__/bazel-out/k8-fastbuild/testlogs/pkg/executor/executor_test/shard_6_of_50/test.log)
ERROR: /home/prow/go/src/github.com/pingcap/tidb/pkg/executor/BUILD.bazel:294:8: Testing //pkg/executor:executor_test (shard 6 of 50) failed: Test failed, aborting
==================== Test output for //pkg/executor:executor_test (shard 6 of 50):
=== RUN   TestCacheSnapShot
```

**Comment by lance6716** [comment]
> Not sure but the failed tasks seem not to be related to the commit, right 🤔?
> 
> ```
>     testkit.go:454: 
>         	Error Trace:	pkg/testkit/testkit.go:454
>         	            				pkg/executor/recover_test.go:580
>         	Error:      	Error message not equal:
>         	            	expected: "Can't find dropped database: db_not_exists in DDL history jobs"
>         	            	actual  : "Can't find dropped database 'db_not_exists' in GC safe point 2024-01-06 04:31:39.411 +0000 UTC"
>         	Test:       	TestFlashbackSchema
> ```
> 
> ```
> ================================================================================
> [11,717 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 285s remote ... (89 actions running)
> [11,719 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 287s remote ... (89 actions running)
> [11,720 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 288s remote ... (89 actions running)
> [11,721 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 289s remote ... (89 actions running)
> [11,722 / 11,819] 374 / 380 tests; Testing //pkg/executor:executor_test (shard 10 of 50); 291s remote ... (89 actions running)
> FAIL: //pkg/executor:executor_test (shard 6 of 50) (see /root/.cache/bazel/_bazel_root/37ff7b0eddea115f60ab9f853788d7f5/execroot/__main__/bazel-out/k8-fastbuild/testlogs/pkg/executor/executor_test/shard_6_of_50/test.log)
> ERROR: /home/prow/go/src/github.com/pingcap/tidb/pkg/executor/BUILD.bazel:294:8: Testing //pkg/executor:executor_test (shard 6 of 50) failed: Test failed, aborting
> ==================== Test output for //pkg/executor:executor_test (shard 6 of 50):
> === RUN   TestCacheSnapShot
> ```

Yes you don't need to worry about it, seems the unit test is flaky. And "tiprow_fast_test" will not block the merging.

**Review by lance6716 — APPROVED** [review]

**Review by dveeden — APPROVED** [review]
