### PR TITLE
planner: fix wrong column offsets when processing dynamic pruning for IndexJoin

### LINKED ISSUE #24631: Wrong results when accessing partition tables by IndexJoin
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set @@tidb_partition_prune_mode = 'dynamic'

create table thash (a int, b int, c int, primary key(a), index idx_b(b)) partition by hash(a) partitions 4;
create table tnormal (a int, b int, c int, primary key(a), index idx_b(b));
create table touter (a int, b int, c int);

insert into thash values (1, 2, 3);
insert into tnormal values (1, 2, 3);
insert into touter values (1, 2, 3);



mysql> select /*+ INL_JOIN(touter, thash) */ thash.b from touter join thash use index(idx_b) on touter.b = thash.b;
Empty set (0.01 sec)

mysql> select /*+ INL_JOIN(touter, tnormal) */ tnormal.b from touter join tnormal use index(idx_b) on touter.b = tnormal.b;
+------+
| b    |
+------+
|    2 |
+------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
They should return the same result.

### 3. What did you see instead (Required)
Their results are different.

### 4. What is your TiDB version? (Required)

Master Branch

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #24631 

Problem Summary: planner: fix wrong column offsets when processing dynamic pruning for IndexJoin

### What is changed and how it works?
Before this PR, when processing dynamic pruning for `IndexJoin` in `prunePartitionForInnerExecutor`, `indexJoinLookUpContent.keyCols` is used directly, but this is wrong.
`indexJoinLookUpContent.keyCols` is offsets of these columns after column pruning instead of their actual offsets in the original table.
For example, for a table with columns `(a, b, c)` and a query `select b, c from ...`, `keyCols` for `b` and `c` is 0 and 1 since `a` is not read by this query, but the actual offsets of `b` and `c` in the original table is `1` and `2`.
When processing dynamic pruning, what we need is their actual offsets in the original table since we need to reconstruct a row and do partition pruning on it.
So I propagate the original column IDs to the place handling dynamic pruning and use them to recalculate the actual offsets of these columns.

More test cases will be added by https://github.com/pingcap/tidb/pull/24497.

### Check List 

Tests 

- Unit test

### Release note 

- planner: fix wrong column offsets when processing dynamic pruning for IndexJoin

### CODE REVIEW

File: executor/partition_table_test.go [hunk 1]
```diff
@@ -374,7 +433,7 @@ func (s *partitionTableSuite) TestGlobalStatsAndSQLBinding(c *C) {
 		partition p2 values less than (600),
 		partition p3 values less than (800),
 		partition p4 values less than (1001))`)
-	tk.MustExec(`create table tlist(a int, b int, key(a)) partition by list (a) (
+	tk.MustExec(`create table tlist(a int, b int, key(a)) partition by list (a) (7
```
Comment (rebelice) [inline executor/partition_table_test.go:436]:
```suggestion
	tk.MustExec(`create table tlist(a int, b int, key(a)) partition by list (a) (
```

**Review by rebelice — COMMENTED** [review]
rest LGTM

**Review by rebelice — APPROVED** [review]
/lgtm
