### PR TITLE
br: Enhance stream restore logs

### LINKED ISSUE #53645: Duplicate attributes in BR json log for pitr
## Bug Report

The `"restore log success summary"` looks like this in the output of `br`:
```
[2024/05/29 08:40:10.537 +02:00] [INFO] [collector.go:77] ["restore log success summary"] [total-take=3.607614879s] [restore-from=450091587356590086] [restore-to=450091627315200000] [restore-from="2024-05-29 08:12:27.57 +0200"] [restore-to="2024-05-29 08:15:00 +0200"] [total-kv-count=2] [skipped-kv-count-by-checkpoint=0] [total-size=191B] [skipped-size-by-checkpoint=0B] [average-speed=52.94B/s]
```

And when using `--log-format json` this looks like this:
```json
{"level":"INFO","time":"2024/05/29 08:43:01.784 +02:00","caller":"collector.go:78","message":"restore log success summary","total-take":"3.595453335s","restore-from":450091587356590086,"restore-to":450091627315200000,"restore-from":"2024-05-29 08:12:27.57 +0200","restore-to":"2024-05-29 08:15:00 +0200","total-kv-count":2,"skipped-kv-count-by-checkpoint":0,"total-size":"191B","skipped-size-by-checkpoint":"0B","average-speed":"53.12B/s"}
```

When using `jq` to do display/filtering/etc it looks like this:
```json
{
  "level": "INFO",
  "time": "2024/05/29 08:43:01.784 +02:00",
  "caller": "collector.go:78",
  "message": "restore log success summary",
  "total-take": "3.595453335s",
  "restore-from": "2024-05-29 08:12:27.57 +0200",
  "restore-to": "2024-05-29 08:15:00 +0200",
  "total-kv-count": 2,
  "skipped-kv-count-by-checkpoint": 0,
  "total-size": "191B",
  "skipped-size-by-checkpoint": "0B",
  "average-speed": "53.12B/s"
}
```

The problem here is that there are duplicate keys in this output for `restore-to` and `restore-from`. Once with the TS and once with the human readable timestamp.

Suggestion:
Rename one of these for each group to avoid duplicate attributes.

### LINKED ISSUE #53648: PiTR log is missing a RestoreTS
## Bug Report

When doing a point in time restore there are two stages. The first stage is the restore of a full backup, for which a `BackupTS` and `RestoreTS` is reported. The next stage is the log restore, for which the range is reported for which the restore is done, but there is no RestoreTS reported.

This is an issue in this case:

1. Start a stream/pitr task on systemA.
2. Start a full backup on systemA.
3. Perform a pitr on systemB.
4. Now run `sync_diff_inspector` to check data integrity
  a. use the `restore-to` TSO from the logs for the TSO of systemA
  b. Now try to get the right TSO for systemB.... There is no `RestoreTS`. Now `SHOW MASTER STATUS` might work, but it would be better to have this in the logs directly.

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #53648, close #53645 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
BR Logging of point-in-time restore was updated to avoid duplicate keys and include a RestoreTS
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]

File: br/pkg/task/stream.go [hunk 1]
```diff
@@ -1243,9 +1244,12 @@ func restoreStream(
 		} else {
 			totalDureTime := time.Since(startTime)
 			summary.Log("restore log success summary", zap.Duration("total-take", totalDureTime),
-				zap.Uint64("restore-from", cfg.StartTS), zap.Uint64("restore-to", cfg.RestoreTS),
+				zap.Uint64("restore-from-tso", cfg.StartTS),
+				zap.Uint64("restore-to-tso", cfg.RestoreTS),
+				zap.Uint64("RestoreTS-tso", currentTS),
```
Comment (3pointer) [inline br/pkg/task/stream.go:1249]: I feel like we need mention the upstream/downstream cluster for user to easy understand.
for example. `restore-from` and `restore-to` were belong to upstream cluster.
Maybe call them `upstream-start-point` and `upstream-end-point`. `downstream-end-point`  or something like that?

Comment (dveeden) [reply br/pkg/task/stream.go:1249]: image

I think we should aim to use similar names for the restore of a full backup and for the restore based on pitr.

I like think the `-{start,end}-point` names are much better than `-tso`.

Instead of upstream/downstream, I think we should use source and target.

Another difference with a regular restore is that this message returns a timestamp in uint64 and human readable form while a regular restore only has the uint64 version.

Comment (dveeden) [reply br/pkg/task/stream.go]: @3pointer I have updated the names. PTAL

Comment (3pointer) [reply br/pkg/task/stream.go]: it looks better now.
