### PR TITLE
planner: fix partition selection of point plan for the update statement

### LINKED ISSUE #23563: partition selection doesn't take affect on PointUpdate
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

like https://github.com/pingcap/tidb/pull/17285 but point-get update

```
create table t1(a int primary key, b int) partition by hash(a) partitions 2;
insert into t1(a, b) values(1, 1),(2, 2),(3, 3);
update t1 partition(p0) set a = 5 where a = 2;
```

### 2. What did you expect to see? (Required)

report error like `Found a row not matching the given partition set`

### 3. What did you see instead (Required)

success

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by TszKitLo40**
Signed-off-by: alfredlu <wslzj40@gmail.com>

### What problem does this PR solve?

Issue Number: close #23563  

Problem Summary:

### What is changed and how it works?

What's Changed:
fix partition selection of point plan for the update statement
How it Works:
Add PartitionedTable in `UpdatePlan`
### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -6800,6 +6800,11 @@ func (s *testSuite1) TestUpdateGivenPartitionSet(c *C) {
 
 	tk.MustExec("update t2 partition(p0) set a = 3 where a = 2")
 	tk.MustExec("update t2 partition(p0, p3) set a = 33 where a = 1")
+
+	tk.MustExec("create table t4(a int primary key, b int) partition by hash(a) partitions 2")
+	tk.MustExec("insert into t4(a, b) values(1, 1),(2, 2),(3, 3);")
+	err = tk.ExecToErr("update t4 partition(p0) set a = 6 where a = 2")
```
Comment (tiancaiamao) [inline executor/executor_test.go:6806]: The test case is not correct, both a = 6 and a = 2 are in the same partition p0.
You get to check the original test case in the issue. @TszKitLo40

**Comment by tiancaiamao** [comment]
How it works:
Replace `PartitionTable` with `PartitionTableithGivenSets`, and the later one would check the data destination fit into the given partition list. For example, `PartitionTableithGivenSets (p0, p1, p2)` only allow the data be write to p0, p1, p2...
