### PR TITLE
ddl: properly handle existence checks for deleted records in temp index

### LINKED ISSUE #39321: unit tests failed when fast reorg is enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
set global tidb_ddl_enable_fast_reorg=0
run ut 
TestCreateUniqueExpressionIndex
TestCancel
TestRunDDLJobPanicEnableClusteredIndex
TestRunDDLJobPanicDisableClusteredIndex
TestIndexChange
TestMultiSchemaChangeAddIndexesCancelled
TestCancelAddIndexPanic
TestDDLStatsInfo

### 2. What did you expect to see? (Required)
ut passed
### 3. What did you see instead (Required)
ut failed
### 4. What is your TiDB version? (Required)
v6.4 & v6.3

### PR DESCRIPTION
**Pull request by Benjamin2037**
### What problem does this PR solve?

Issue Number: close #39321

Problem Summary:
When set fast reorg variable on, some ut will failed. 

### What is changed and how it works?

> TestCreateUniqueExpressionIndex

When user issue` insert on dulplicate update` statement during add index processing.

1. During `insert on dulplicate update`, it need check unique key exists.  when this check processing is in fast_reorg add index period,  the check key exists should be done on temp index.
2. Also the deleted key in temp index is not real delete, it is marked delete. So if this key was return, it should be skiped. 
3. When user insert one row in unique index, we also need check if there is marked deleted key exist, if this deleted key exist, then we skip unique conflict check and then let insert could be successful.

> TestIndexChange

This case has some trick place, it test different  adding index schema stage to see if key is exist or not.  But here still has above problem. In non-public status index, all changes on table that is adding index will reflect to temp idx. 
So we have to change key exist also on temp index first.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/index_merge_tmp_test.go [hunk 1]
```diff
@@ -259,3 +259,96 @@ func TestPessimisticAmendIncompatibleWithFastReorg(t *testing.T) {
...
 		"amend pessimistic transactions is not compatible with tidb_ddl_enable_fast_reorg")
 }
+
+// TestCreateUniqueIndexKeyExist this case will test below things:
+// Create one unique index idx((a*b+1));
+// insert (0, 6) and delete it;
+// insert (0, 9), it should be successful;
+// Should check temp key exist and skip deleted mark
+// The error returned below:
+// Error Trace:	/tidb/ddl/index_merge_tmp_test.go:345
```
Comment (tangenta) [inline ddl/index_merge_tmp_test.go:269]:
```suggestion
```

It is easy to be outdated and not informative.

File: ddl/index_merge_tmp_test.go [hunk 2]
```diff
@@ -259,3 +259,95 @@ func TestPessimisticAmendIncompatibleWithFastReorg(t *testing.T) {
...
+	d := dom.DDL()
+	originalCallback := d.GetHook()
+	defer d.SetHook(originalCallback)
+	callback := &ddl.TestDDLCallback{}
+	onJobUpdatedExportedFunc := func(job *model.Job) {
+		if checkErr != nil {
+			return
+		}
+		err := originalCallback.OnChanged(nil)
+		require.NoError(t, err)
```
Comment (tangenta) [inline ddl/index_merge_tmp_test.go:297]: Why is it called?

Comment (Benjamin2037) [reply ddl/index_merge_tmp_test.go:297]: This is from the old test case :-(, I will remove it.

File: ddl/index_merge_tmp_test.go [hunk 3]
```diff
@@ -259,3 +259,92 @@ func TestPessimisticAmendIncompatibleWithFastReorg(t *testing.T) {
...
+	originalCallback := d.GetHook()
+	defer d.SetHook(originalCallback)
+	callback := &ddl.TestDDLCallback{}
+	onJobUpdatedExportedFunc := func(job *model.Job) {
+		err := originalCallback.OnChanged(nil)
+		require.NoError(t, err)
+		switch job.SchemaState {
+		case model.StateDeleteOnly:
+			for _, sql := range stateDeleteOnlySQLs {
+				_, checkErr = tk1.Exec(sql)
```
Comment (tangenta) [inline ddl/index_merge_tmp_test.go:298]: It is better to add `assert.NoError(checkErr)` after each execution so that the problem could be diagnosed quickly on failed.

File: table/tables/index.go [hunk 4]
```diff
@@ -463,3 +503,52 @@ func TryAppendCommonHandleRowcodecColInfos(colInfo []rowcodec.ColInfo, tblInfo *
...
+	value, err := txn.Get(context.TODO(), key)
+	if kv.IsErrNotFound(err) {
+		return KeyInTempIndexNotExist, nil, nil
+	}
+	if err != nil {
+		return KeyInTempIndexUnknown, nil, err
+	}
+
+	length := len(value)
+	value = value[:length-1]
```
Comment (tangenta) [inline table/tables/index.go:531]:
```suggestion
	// Remove the ending key version.
	value = value[:length-1]
```

File: table/tables/index.go [hunk 5]
```diff
@@ -463,3 +503,52 @@ func TryAppendCommonHandleRowcodecColInfos(colInfo []rowcodec.ColInfo, tblInfo *
...
+	KeyInTempIndexIsDeleted = 2
+	// KeyInTempIndexIsItself the key is correlated to itself in temp index.
+	KeyInTempIndexIsItself = 3
+	// KeyInTempIndexConflict the key is conflict in temp index.
+	KeyInTempIndexConflict = 4
+)
+
+// KeyExistInTempIndex is used to check if there is unique key is marked delete in temp index.
+func KeyExistInTempIndex(txn kv.Transaction, key kv.Key, distinct bool, h kv.Handle, IsCommonHandle bool) (int, kv.Handle, error) {
+	value, err := txn.Get(context.TODO(), key)
```
Comment (tangenta) [inline table/tables/index.go:522]: It is better to pass in the context in instead of using `context.TODO()`.

File: table/tables/index.go [hunk 6]
```diff
@@ -463,3 +503,54 @@ func TryAppendCommonHandleRowcodecColInfos(colInfo []rowcodec.ColInfo, tblInfo *
...
+	KeyInTempIndexNotExist = 1
+	// KeyInTempIndexIsDeleted the key is marked deleted in temp index.
+	KeyInTempIndexIsDeleted = 2
+	// KeyInTempIndexIsItself the key is correlated to itself in temp index.
+	KeyInTempIndexIsItself = 3
+	// KeyInTempIndexConflict the key is conflict in temp index.
+	KeyInTempIndexConflict = 4
+)
+
+// KeyExistInTempIndex is used to check if there is unique key is marked delete in temp index.
```
Comment (wjhuang2016) [inline table/tables/index.go:520]:
```suggestion
// KeyExistInTempIndex is used to check if the unique key is marked as deleted in the temp index.
```

File: table/tables/index.go [hunk 7]
```diff
@@ -364,6 +380,30 @@ func (c *index) Exist(sc *stmtctx.StatementContext, txn kv.Transaction, indexedV
...
 	}
 
+	var (
+		tempKey []byte
+		keyVer  byte
+	)
+	// If index current is in creating status and using ingest mode, we need first
+	// check key exist status in temp index.
+	key, tempKey, keyVer = GenTempIdxKeyByState(c.idxInfo, key)
+	if keyVer != TempIndexKeyTypeNone {
```
Comment (wjhuang2016) [inline table/tables/index.go:390]: if keyVer != TempIndexKeyTypeNone, then len(tempKey) must be > 0?

File: table/tables/index.go [hunk 8]
```diff
@@ -226,11 +227,26 @@ func (c *index) Create(sctx sessionctx.Context, txn kv.Transaction, indexedValue
 	}
 	if err != nil || len(value) == 0 {
 		lazyCheck := sctx.GetSessionVars().LazyCheckKeyNotExists() && err != nil
+		var needPresumeKey int
```
Comment (wjhuang2016) [inline table/tables/index.go:230]: It's strange that needPresumeKey is an integer.

Comment (Benjamin2037) [reply table/tables/index.go:230]: TestCreateUniqueExpressionIndex

File: ddl/index_merge_tmp_test.go [hunk 9]
```diff
@@ -259,3 +259,65 @@ func TestPessimisticAmendIncompatibleWithFastReorg(t *testing.T) {
...
+// TestCreateUniqueIndexKeyExist this case will test below things:
+// Create one unique index idx((a*b+1));
+// insert (0, 6) and delete it;
+// insert (0, 9), it should be successful;
+// Should check temp key exist and skip deleted mark
+// The error returned below:
+// Error:      	Received unexpected error:
+//
+//	[kv:1062]Duplicate entry '1' for key 't.idx'
+func TestCreateUniqueIndexKeyExist(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (Benjamin2037) [reply ddl/index_merge_tmp_test.go:272]: TestCreateUniqueExpressionIndex is for that purpose, this pr also fix that.

**Review by wjhuang2016 — APPROVED** [review]

File: executor/insert.go [hunk 10]
```diff
@@ -264,6 +266,12 @@ func (e *InsertExec) batchUpdateDupRows(ctx context.Context, newRows [][]types.D
 				}
 				return err
 			}
+			// Since the temp index stores deleted key with marked 'deleteu' for unique key at the end
+			// of value, So if return a key we check and skip deleted key.
+			rowVal := val[:len(val)-1]
+			if bytes.Equal(rowVal, tables.DeleteMarkerUnique) {
+				continue
+			}
```
Comment (tangenta) [inline executor/insert.go:274]: We need to check this only if the key is temporary key. Otherwise, if the value of an ordinary index is "deleteux", the thing goes wrong.

File: ddl/index_merge_tmp_test.go [hunk 11]
```diff
@@ -259,3 +259,73 @@ func TestPessimisticAmendIncompatibleWithFastReorg(t *testing.T) {
...
+
+	// If waitReorg timeout, the worker may enter writeReorg more than 2 times.
+	reorgTime := 0
+	d := dom.DDL()
+	originalCallback := d.GetHook()
+	defer d.SetHook(originalCallback)
+	callback := &ddl.TestDDLCallback{}
+	onJobUpdatedExportedFunc := func(job *model.Job) {
+		err := originalCallback.OnChanged(nil)
+		assert.NoError(t, err)
```
Comment (tangenta) [inline ddl/index_merge_tmp_test.go:293]:
```suggestion
```

File: executor/insert.go (hunk 10 above)
Comment (Benjamin2037) [reply executor/insert.go:274]: Yes only check temp index key is marked deleted, if it is ordinary index this should not be equal and it should keep on going into original check logical.

File: table/tables/index.go [hunk 12]
```diff
@@ -463,3 +501,56 @@ func TryAppendCommonHandleRowcodecColInfos(colInfo []rowcodec.ColInfo, tblInfo *
...
+		return KeyInTempIndexNotExist, nil, nil
+	}
+	if err != nil {
+		return KeyInTempIndexUnknown, nil, err
+	}
+
+	length := len(value)
+	// Firstly, we will remove the last byte of key version.
+	// It should be TempIndexKeyTypeBackfill or TempIndexKeyTypeMerge.
+	value = value[:length-1]
```
Comment (tangenta) [inline table/tables/index.go:533]: Is it necessary to check the length? (to avoid panic because of the out-of-range error)

File: executor/insert.go (hunk 10 above)
Comment (tangenta) [reply executor/insert.go:274]: > if it is ordinary index this should not be equal and it should keep on going into original check logical.

We had better not to make this assumption on the encoding.

File: ddl/index_merge_tmp_test.go [hunk 13]
```diff
@@ -259,3 +259,73 @@ func TestPessimisticAmendIncompatibleWithFastReorg(t *testing.T) {
...
+
+	stateDeleteOnlySQLs := []string{"insert into t values (5, 5)", "begin pessimistic;", "insert into t select * from t", "rollback", "insert into t set b = 6", "update t set b = 7 where a = 1", "delete from t where b = 4"}
+
+	// If waitReorg timeout, the worker may enter writeReorg more than 2 times.
+	reorgTime := 0
+	d := dom.DDL()
+	originalCallback := d.GetHook()
+	defer d.SetHook(originalCallback)
+	callback := &ddl.TestDDLCallback{}
+	onJobUpdatedExportedFunc := func(job *model.Job) {
```
Comment (tangenta) [inline ddl/index_merge_tmp_test.go:291]:
```suggestion
	onJobUpdatedExportedFunc := func(job *model.Job) {
		if t.Failed() {
			return
		}
```

**Review by tangenta — APPROVED** [review]
