### PR TITLE
cgroup: improve test to find cgroup compatibility issues 

### LINKED ISSUE #39786: unstable test: TestGetCgroupCPU
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```shell
=== RUN   TestGetCgroupCPU
    cgroup_cpu_test.go:45: 
        	Error Trace:	/home/jenkins/.tidb/tmp/5b8829669b2a941b840f9eb369e2b54f/sandbox/processwrapper-sandbox/2105/execroot/__main__/bazel-out/k8-fastbuild/bin/util/cgroup/cgroup_test_/cgroup_test.runfiles/__main__/util/cgroup/cgroup_cpu_test.go:45
        	Error:      	Received unexpected error:
        	            	no cpu controller detected
        	            	github.com/pingcap/tidb/util/cgroup.getCgroupCPU
        	            		util/cgroup/cgroup_cpu.go:33
        	            	github.com/pingcap/tidb/util/cgroup.GetCgroupCPU
        	            		util/cgroup/cgroup_cpu_linux.go:28
        	            	github.com/pingcap/tidb/util/cgroup.TestGetCgroupCPU
        	            		util/cgroup/cgroup_cpu_test.go:44
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1446
        	            	runtime.goexit
        	            		GOROOT/src/runtime/asm_amd64.s:1594
        	Test:       	TestGetCgroupCPU
--- FAIL: TestGetCgroupCPU (0.00s)

```
link  https://ci.pingcap.net/blue/organizations/jenkins/tidb-unit-test-hourly/detail/tidb-unit-test-hourly/13322/tests

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #39786

Problem Summary:

### What is changed and how it works?

If you are in the linux 3.x, Your cgroup path is different from the latest version.
the path of CPU cgroup is ```cpu,cpuacct```. But the old is ```cpuacct,cpu```. it just is a small problem. But it has a more serious problem. the path in old version is nonexistent like 
```cpuacct.usage_sys``` and ```cpuacct.usage_user``` which is created at the Linux 4.x.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

File: util/cgroup/cgroup_cpu_test.go [hunk 1]
```diff
@@ -42,9 +42,13 @@ func TestGetCgroupCPU(t *testing.T) {
 		}()
 	}
 	cpu, err := GetCgroupCPU()
-	require.NoError(t, err)
-	require.NotZero(t, cpu.Period)
-	require.Less(t, int64(1), cpu.Period)
+	if err == errNoCPUControllerDetected {
+		require.False(t, InContainer(), "Please check linux version. This is related to cgroup compatibility.")
```
Comment (Defined2014) [inline util/cgroup/cgroup_cpu_test.go:46]: better to figure out in comments which version of Linux is supported. Like `> 4.x` or `>= 5.x` etc.

**Review by Defined2014 — APPROVED** [review]
Reset LGTM

File: util/cgroup/cgroup_cpu_test.go (hunk 1 above)
Comment (hawkingrei) [reply util/cgroup/cgroup_cpu_test.go]: Thx, I have updated it.
