### PR TITLE
planner: set windowClause only in WindowFuncExpr

### LINKED ISSUE #11943: TiDB requires columns referred to in OVER clause of a window function to also be in the field list of the SELECT statement
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

data:
```
CREATE TABLE `t` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `i` int(10) unsigned DEFAULT NULL,
  `x` int(10) unsigned DEFAULT 0,
  PRIMARY KEY (`id`)
);
INSERT INTO `t` (id, i) VALUES (1,1),(2,2),(3,3),(4,4),(5,5);
```

query:
```
select row_number() over( partition by i ) - x as rnk from t;
```

2. What did you expect to see?

From MySQL 8.0:
```
mysql> select row_number() over( partition by i ) - x as rnk from t;
+------+
| rnk  |
+------+
|    1 |
|    1 |
|    1 |
|    1 |
|    1 |
+------+
5 rows in set (0.00 sec)
```

3. What did you see instead?

From TiDB:
```
TiDB> select row_number() over(partition by i) - x from t;
ERROR 1054 (42S22): Unknown column 'x' in 'field list'
```

After explicitly adding column `x` to the field list:
```
TiDB> select x, row_number() over(partition by i) - x as rnk from t;
+------+------+
| x    | rnk  |
+------+------+
|    0 |    1 |
|    0 |    1 |
|    0 |    1 |
|    0 |    1 |
|    0 |    1 |
+------+------+
5 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
tidb_version(): Release Version: v3.0.3
Git Commit Hash: 836982c617fbaa42d74616eb9ba9ed4cae46c46b
Git Branch: HEAD
UTC Build Time: 2019-08-29 04:59:41
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve? 
Fix #11943 

### What is changed and how it works?
Presently, TiDB sets windowClause even if the expr is a binaryExpr. So
set windowClause only in WindowFuncExpr to fix it.

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Write release note for bug-fix or new feature.

### CODE REVIEW

**Comment by wjhuang2016** [comment]
@lamxTyler PTAL

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -1206,6 +1206,9 @@ func (a *havingWindowAndOrderbyExprResolver) Enter(n ast.Node) (node ast.Node, s
 		a.inAggFunc = true
 	case *ast.WindowFuncExpr:
 		a.inWindowFunc = true
+		if a.curClause == unknowClause {
```
Comment (lamxTyler) [inline planner/core/logical_plan_builder.go]: Why not just use `inWindowFunc` to determine the resolve rule?

File: expression/integration_test.go [hunk 2]
```diff
@@ -4909,3 +4909,12 @@ func (s *testIntegrationSuite) TestIssue11309And11319(c *C) {
 	tk.MustQuery(`SELECT DATE_ADD('2007-03-28 22:08:28',INTERVAL 2.2 DAY_HOUR)`).Check(testkit.Rows("2007-03-31 00:08:28"))
 	tk.MustQuery(`SELECT DATE_ADD('2007-03-28 22:08:28',INTERVAL 2.2 YEAR_MONTH)`).Check(testkit.Rows("2009-05-28 22:08:28"))
 }
+
+func (s *testIntegrationSuite) TestIssue11943(c *C) {
```
Comment (lamxTyler) [inline expression/integration_test.go]: You can put it in the `TestWindowFunction` of plan package or `TestWindowFunctions` of executor package.

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (wjhuang2016) [reply planner/core/logical_plan_builder.go]: We can use `inWindowFunc` here. But I'm not sure how windowClause is used and what's the difference between them.

File: expression/integration_test.go (hunk 2 above)
Comment (wjhuang2016) [reply expression/integration_test.go]: ok

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (wjhuang2016) [reply planner/core/logical_plan_builder.go]: @lamxTyler Take `select a, b as z from t order by (sum(z) over())` for example,
If we use `inWindowFunc`, resolveFieldsFirst will be false, which should be true.

Comment (lamxTyler) [reply planner/core/logical_plan_builder.go]: Actually `windowClause` is only readed in one place, and from the code itself, it is set at the same time with `inWindowFunc`. You can search the code to find these facts.

Comment (wjhuang2016) [reply planner/core/logical_plan_builder.go]: > Actually `windowClause` is only readed in one place, and from the code itself, it is set at the same time with `inWindowFunc`. You can search the code to find these facts.

I use fieldList to replace windowClause, and I think it's more understandable. PTAL

Comment (lamxTyler) [reply planner/core/logical_plan_builder.go]: > @lamxTyler Take `select a, b as z from t order by (sum(z) over())` for example,
> If we use `inWindowFunc`, resolveFieldsFirst will be false, which should be true.

But currently it is false? Since `inWindowFunc` is true.

Comment (wjhuang2016) [reply planner/core/logical_plan_builder.go]: > > @lamxTyler Take `select a, b as z from t order by (sum(z) over())` for example,
> > If we use `inWindowFunc`, resolveFieldsFirst will be false, which should be true.
> 
> But currently it is false? Since `inWindowFunc` is true.

Sorry for my mistake, when using `inWindowFunc`, we need also deal with `if index == -1 && a.curClause != windowClause {` . So we can't just use `inWindowFunc` and leave alone `windowClause`. The concept `windowClause` is too cunfusing to distinguish from `inWindowFunc`. In fact, it should be `fieldList`. Base on this, the root cause of this bug is obvious, for some `column` in `filedList` but not in `WindowFunc`, we should set `resolveFieldsFirst` as `false`

File: planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -1414,7 +1414,7 @@ func (b *PlanBuilder) resolveWindowFunction(sel *ast.SelectStmt, p LogicalPlan)
 		colMapper:    b.colMapper,
 		outerSchemas: b.outerSchemas,
 	}
-	extractor.curClause = windowClause
```
Comment (winoros) [inline planner/core/logical_plan_builder.go]: We can remove windowCluase directly?

Comment (wjhuang2016) [reply planner/core/logical_plan_builder.go]: I had changed all the usages of `windowClause` to `fieldList`.

Comment (winoros) [reply planner/core/logical_plan_builder.go]: @wjhuang2016 windowCluase is not referenced by any places so we can totally remove it.

Comment (wjhuang2016) [reply planner/core/logical_plan_builder.go]: I got it.

**Comment by zz-jason** [comment]
@wjhuang2016 Any update?

**Comment by wjhuang2016** [comment]
> @wjhuang2016 Any update?

I will update it in a few days.

File: cmd/explaintest/r/select.result [hunk 4]
```diff
@@ -470,3 +470,16 @@ HashLeftJoin_10	7984.01	root	semi join, inner:TableReader_16, equal:[eq(test.t1.
 └─TableReader_16	9980.01	root	data:Selection_15
   └─Selection_15	9980.01	cop	not(isnull(test.t2.a)), not(isnull(test.t2.b))
     └─TableScan_14	10000.00	cop	table:t2, range:[-inf,+inf], keep order:false, stats:pseudo
+ drop table t;
```
Comment (lamxTyler) [inline cmd/explaintest/r/select.result]: You can use `./run-tests.sh -r select` to generate the result, it has a leading blank space now.

Comment (wjhuang2016) [reply cmd/explaintest/r/select.result]: Thanks

**Comment by wjhuang2016** [comment]
@lamxTyler I can't find out why the test failed and  I passed the `make dev`, could you help we and take a see?

**Comment by lamxTyler** [comment]
@wjhuang2016 You need to regenereate the result file now, there are some changes that affects the result after merging master.
