### PR TITLE
explaintest: improve retry for open db

### LINKED ISSUE #45681: flaky test explaintest
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
[2023/07/31 14:05:45.699 +08:00] [ERROR] [main.go:674] ["open Db failed"] ["take time"=30.066849144s] [error="dial tcp [::1]:35611: connect: connection refused"]

[2023/07/31 14:05:45.700 +08:00] [FATAL] [main.go:694] ["open DB failed"] [error="dial tcp [::1]:35611: connect: connection refused"] [errorVerbose="dial tcp [::1]:35611: connect: connection refused\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/juju_adaptor.go:15\nmain.openDBWithRetry\n\t/home/jenkins/agent/workspace/pingcap/tidb/ghpr_check/tidb/cmd/explaintest/main.go:675\nmain.main\n\t/home/jenkins/agent/workspace/pingcap/tidb/ghpr_check/tidb/cmd/explaintest/main.go:689\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"] [stack="main.main\n\t/home/jenkins/agent/workspace/pingcap/tidb/ghpr_check/tidb/cmd/explaintest/main.go:694\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]

```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #45681

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: cmd/explaintest/main.go [hunk 1]
```diff
@@ -649,26 +650,33 @@ func loadAllTests() ([]string, error) {
...
 		if err == nil {
 			break
 		}
-		log.Warn("ping DB failed", zap.Int("retry count", i), zap.Error(err))
+		log.Warn("ping DB failed", zap.Duration("retry duration", time.Since(now)), zap.Error(err))
 		if err1 := mdb.Close(); err1 != nil {
 			log.Error("close DB failed", zap.Error(err1))
 		}
 		time.Sleep(sleepTime)
+		sleepTime = sleepTime * 2
```
Comment (zimulala) [inline cmd/explaintest/main.go:678]: Maybe we need put it to line660？Otherwise, we can't update the `sleepTime` value in line666.

Comment (hawkingrei) [reply cmd/explaintest/main.go]: Done

**Review by zimulala — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
