### PR TITLE
planner,txn: fix the bug that RESOURCE_GROUP() hint can not take effect for write …

### LINKED ISSUE #44512: the RESOURCE_GROUP() hint can not take effect for write statement
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE RESOURCE GROUP rg1 ru_per_sec = 1000;
USE test;
CREATE TABLE t(id int);

# run following sql for 100 times.
INSERT /*+ RESOURCE_GROUP(rg1) */  INTO t value (1); 
```

### 2. What did you expect to see? (Required)
The `Resource Control` grafana should show WRU consumption for rg1.

### 3. What did you see instead (Required)
The `Resource Control` grafana should show WRU consumption only for default.

### 4. What is your TiDB version? (Required)

nightly

### PR DESCRIPTION
**Pull request by glorv**
…statement

### What problem does this PR solve?

Issue Number: close #44512

Problem Summary:

### What is changed and how it works?

- Fix the bug that `RESOURCE_GROUP()` hint does not effect `UPDATE` statement.
- Update the transaction's bind resource group name when there is `RESOURCE_GROUP` hint in the statement hint.

NOTE:
Before this change, this hint only effect the read request but not the prewrite/commit kv request because when the 2pc commit is executed, all statements are finished and so the resource group is rollback to the session's default value.

If a transaction contains multiple statements and they has different RESOURCE_GROUP hints, after this change the last hint will be used for the prewrite/commit request.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
> overall lgtm, need to add some tests.

@nolouch Do you have any ideas about how to add a test? I found there is no available metrics for us to observe the internal state of the resource control client

File: sessiontxn/isolation/base.go [hunk 1]
```diff
@@ -337,6 +337,7 @@ func (p *baseTxnContextProvider) ActivateTxn() (kv.Transaction, error) {
 	if sessVars.LoadBasedReplicaReadThreshold > 0 {
 		txn.SetOption(kv.LoadBasedReplicaReadThreshold, sessVars.LoadBasedReplicaReadThreshold)
 	}
+	txn.SetOption(kv.ResourceGroupName, sessVars.ResourceGroupName)
```
Comment (HuSharp) [inline sessiontxn/isolation/base.go:340]: I noticed `StalenessTxnContextProvider`'s `ActivateTxn`, do we need to SetOption also?

Comment (glorv) [reply sessiontxn/isolation/base.go:340]: fixed

File: sessiontxn/staleread/provider.go [hunk 2]
```diff
@@ -114,6 +114,7 @@ func (p *StalenessTxnContextProvider) activateStaleTxn() error {
 	txn.SetVars(sessVars.KVVars)
 	txn.SetOption(kv.IsStalenessReadOnly, true)
 	txn.SetOption(kv.TxnScope, txnScope)
+	txn.SetOption(kv.ResourceGroupName, p.sctx.GetSessionVars().ResourceGroupName)
```
Comment (HuSharp) [inline sessiontxn/staleread/provider.go:117]:
```suggestion
	txn.SetOption(kv.ResourceGroupName, sessVars.ResourceGroupName)
```

File: session/session.go [hunk 3]
```diff
@@ -644,7 +644,6 @@ func (s *session) doCommit(ctx context.Context) error {
 	s.txn.SetOption(kv.EnableAsyncCommit, sessVars.EnableAsyncCommit)
 	s.txn.SetOption(kv.Enable1PC, sessVars.Enable1PC)
 	s.txn.SetOption(kv.ResourceGroupTagger, sessVars.StmtCtx.GetResourceGroupTagger())
-	s.txn.SetOption(kv.ResourceGroupName, sessVars.ResourceGroupName)
```
Comment (Connor1996) [inline session/session.go:647]: why remove it here

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
@nolouch  @HuSharp PTAL again, thanks

**Review by nolouch — APPROVED** [review]
lgtm

File: session/txn.go [hunk 4]
```diff
@@ -598,7 +598,7 @@ func (txn *LazyTxn) Wait(ctx context.Context, sctx sessionctx.Context) (kv.Trans
 		}
 		txn.lazyUniquenessCheckEnabled = !sctx.GetSessionVars().ConstraintCheckInPlacePessimistic
 		// set resource group name for kv request such as lock pessimistic keys.
-		txn.SetOption(kv.ResourceGroupName, sctx.GetSessionVars().ResourceGroupName)
+		kv.SetTxnResourceGroup(txn, sctx.GetSessionVars().ResourceGroupName)
```
Comment (MyonKeminta) [inline session/txn.go:601]: Can this be put into `txn.changePendingToValid` (though it's only called in this Wait function), to avoid this being forgotten if there's going to be more invocations to `changePendingToValid` in the future?

**Review by MyonKeminta — COMMENTED** [review]
Rest LGTM

File: session/txn.go (hunk 4 above)
Comment (glorv) [reply session/txn.go]: done.

**Comment by glorv** [comment]
@MyonKeminta  PTAL again, thanks~

**Review by HuSharp — APPROVED** [review]
LGTM!

File: planner/optimize.go [hunk 5]
```diff
@@ -176,6 +176,25 @@ func Optimize(ctx context.Context, sctx sessionctx.Context, node ast.Node, is in
 	for _, warn := range warns {
 		sessVars.StmtCtx.AppendWarning(warn)
 	}
+
+	defer func() {
+		// Override the resource group if necessary
+		// TODO: we didn't check the existence of the hinted resource group now to save the cost per query
+		if retErr == nil && sessVars.StmtCtx.StmtHints.HasResourceGroup {
+			if variable.EnableResourceControl.Load() {
+				sessVars.ResourceGroupName = sessVars.StmtCtx.StmtHints.ResourceGroup
```
Comment (MyonKeminta) [inline planner/optimize.go:185]: Is the hint statement level, thus it needs to be reset after the statement finishes in a transaction?

**Review by MyonKeminta — COMMENTED** [review]
some questions

File: planner/optimize.go (hunk 5 above)
Comment (glorv) [reply planner/optimize.go:185]: Yes, actually we do reset the `sessVars.ResourceGroupName` after this statement finish executing.

**Review by MyonKeminta — APPROVED** [review]
