### PR TITLE
store/tikv: fix a concurrency bug that may cause the batchClient timeout

### LINKED ISSUE #22334: batchClient may timeout due to use recycled Idle connArray
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

not ease to reproduce, but it should be happen when:

- recycleIdleConnArray running after connection long time without any request,  and will log like this

```
[2020/12/04 09:47:08.776 +08:00] [INFO] [client_batch.go:655] ["recycle idle connection"] [target=10.142.201.27:20172]
[2020/12/04 09:47:08.778 +08:00] [INFO] [client_batch.go:655] ["recycle idle connection"] [target=10.142.201.27:20171]
[2020/12/04 09:47:14.994 +08:00] [INFO] [region_cache.go:833] ["invalidate region cache due to cannot find peer when updating leader"] [regionID=344196] [currIdx=2] [leaderStoreID=7]
```

- another question arrival at the same time as recycleIdleConnArray running

### 2. What did you expect to see? (Required)

need request success or fail(and retry succcess) quickly

### 3. What did you see instead (Required)

it will block a long time and timeout like

```
[2020/12/04 09:48:08.775 +08:00] [WARN] [expensivequery.go:168] [expensive_query] [cost_time=60.035280495s] [conn_id=1805330] [user=chain_fact] [database=supply_chain_factory] [txn_start_ts=0] [mem_max="2261000 Bytes (2.1562576293945312 MB)"] [sql="i

[2020/12/04 09:48:09.152 +08:00] [WARN] [client_batch.go:617] ["send request is cancelled"] [to=10.142.200.29:20171] [cause="context canceled"]
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

closes #22334

Problem Summary:

The `recycleIdleConnArray()` logic  has a bug: when one goroutine `getConnArray()` and the other goroutine recycle the idle connection, the prior goroutine may get a stale `batchConn` which is closed already.

`sendBatchRequest()` using that stale `batchConn` would block until timeout.

```
++++++++++++++++++++++++++++++++++++++++++++++++++++++
g1: connArray := getConnArray(addr, enableBatch)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                                                                                            g2: c.Lock()    
                                                                                                            g2: conn := c.conns[addr]
                                                                                                            g2: Unlock()
                                                                                                            g2: conn.Close()
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
g1: sendBatchRequest(connArray)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

### What is changed and how it works?

What's Changed:

```
RLock()
conn := getConArray()
RUnlock()
sendBatchRequest(conn)
```

This is not enough to protect the conn from been recycle and close.
Now the whole sending process is protected by the read lock, and modify conn map should obtain the write lock.

How it Works:

As long as the sending operation hold the read lock, the recycle connection operation need to wait to obtain the write lock.

### Related changes

- Need to cherry-pick to the release branch

Maybe we can cherry-pick it to 5.0, it's rare to see this bug in the production environment.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

- fix a concurrency bug that may cause the batch client timeout

### CODE REVIEW

**Comment by lysu** [comment]
LGTM

**Comment by hicqu** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: store/tikv/client.go [hunk 1]
```diff
@@ -344,11 +347,15 @@ func (c *rpcClient) SendRequest(ctx context.Context, addr string, req *tikvrpc.R
...
 
 	if atomic.CompareAndSwapUint32(&c.idleNotify, 1, 0) {
+		c.recycleMu.Lock()
 		c.recycleIdleConnArray()
+		c.recycleMu.Unlock()
 	}
 
 	// TiDB will not send batch commands to TiFlash, to resolve the conflict with Batch Cop Request.
 	enableBatch := req.StoreTp != kv.TiDB && req.StoreTp != kv.TiFlash
+	c.recycleMu.RLock()
```
Comment (zhangjinpeng1987) [inline store/tikv/client.go:357]: Does this will impact the send speed?
