### PR TITLE
planner: converting to TableDual only when the empty range is not derived from parameterized constants (#7579)

### LINKED ISSUE #7579: plan cache would be broken if empty range DataSource is converted to TableDual
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

set `prepared-plan-cache-enabled=true` first in config.toml and start TiDB using this config file.

```sql
MySQL [test]> create table t(a int, b int, index a_idx(a));
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> insert into t values(1,1),(2,2),(null,3);
Query OK, 3 rows affected (0.00 sec)

MySQL [test]> select * from t;
+------+------+
| a    | b    |
+------+------+
|    1 |    1 |
|    2 |    2 |
| NULL |    3 |
+------+------+
3 rows in set (0.00 sec)

MySQL [test]> prepare stmt from 'select * from t where ?';
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> execute stmt using @param;
Empty set (0.00 sec)

MySQL [test]> set @param = true;
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> execute stmt using @param;
Empty set (0.00 sec)
```

2. What did you expect to see?

last `execute` statement should return all 3 rows of table.

3. What did you see instead?

empty set returned.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```sql
MySQL [test]> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-rc.1-18-geec6899
Git Commit Hash: eec68995689d5811f4d52846586e969652ed8ffc
Git Branch: master
UTC Build Time: 2018-09-01 06:53:29
GoVersion: go version go1.11rc1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by dbjoa**
### What problem does this PR solve? 
fixes #7579

### What is changed and how it works?
fix the condition to allow only non-deferred constants

### Check List 

Tests 

 - Unit test

Code changes

 - Impl changes

Side effects

 - No

Related changes

 - Need to be included in the release note

### CODE REVIEW

File: expression/util.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func SubstituteCorCol2Constant(expr Expression) (Expression, error) {
 	case *Constant:
 		if x.DeferredExpr != nil {
 			newExpr := FoldConstant(x)
-			return &Constant{Value: newExpr.(*Constant).Value, RetType: x.GetType()}, nil
+			return &Constant{Value: newExpr.(*Constant).Value, RetType: x.GetType(), DeferredExpr: x.DeferredExpr}, nil
```
Comment (eurekaka) [inline expression/util.go]: Since we rely on `DeferredExpr` to decide whether this constant is stable, we should maintain `DeferredExpr` properly as we do in `foldConstant`. Hence, in this function, we should handle `CorrelatedColumn` and `ScalarFunction` branch as well IMHO.

Comment (dbjoa) [reply expression/util.go]: @eurekaka, Thank you for the comment. I agree that the PR should also handle ScalarFunction like as done in Constant branch except for CorrelatedColumn.  I've update the PR.

BTW, if CorrelatedColumn can be parameterized like Constant, its struct should be extended to hold DeferredExpr like Constant. Otherwise, we can leave it.

Comment (dbjoa) [reply expression/util.go]: Thank you for the correction. I've reverted the changes.

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -470,7 +470,7 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
 		}
 		cnfItems := expression.SplitCNFItems(expr)
 		for _, item := range cnfItems {
-			if con, ok := item.(*expression.Constant); ok {
+			if con, ok := item.(*expression.Constant); ok && con.DeferredExpr == nil {
```
[the remark this answers is not in the document]
Comment (dbjoa) [reply planner/core/logical_plan_builder.go]: 1. Adding UseCache is technically possible, but it can not replace the code to check whether or not a constant is parameterized since prepared statements can have the parameterized constants or the non-parameterized ones. That is, 'UseCache == False" is the condition to guarantee all 'DeferredExpr == nil', but 'UseCache == True' is not the condition to guarantee all 'DeferredExpr != nil'.  

2. If a prepared statement has a limit expression, it is not cached(see the code planner/core/cacheable_checker.go). Thus, TableDual will be generated without breaking the plan cache. 

3. To address the optimization issue, we can extend the plan cache to maintain plans according to the parameter ranges. In addition, the optimizer is required to be extended to generate general plans for the given parameters' ranges.

[the remark this answers is not in the document]
Comment (eurekaka) [reply planner/core/logical_plan_builder.go]: > but it can not replace the code to check whether or not a constant is parameterized since prepared statements can have the parameterized constants or the non-parameterized ones

I mean we should use condition like:
```go
if con, ok := item.(*expression.Constant); ok && (con.DeferredExpr == nil || !xxx.UseCache)
```
otherwise, when plan cache is disabled, we indeed should return `TableDual`, but we don't.

> If a prepared statement has a limit expression, it is not cached(see the code planner/core/cacheable_checker.go).

Got it, thanks.
