### PR TITLE
executor: reset kvRange in TableReaderExec.Close

### LINKED ISSUE #19431: Apply return non empty set in transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
DROP TABLE IF EXISTS `t`;
CREATE TABLE `t` (
  `c_int` int(11) NOT NULL,
  `c_str` varchar(40) NOT NULL,
  `c_datetime` datetime NOT NULL,
  PRIMARY KEY (`c_int`,`c_str`,`c_datetime`),
  KEY `c_str` (`c_str`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `t` VALUES (1,'cool pasteur','2020-04-21 19:01:04'),(3,'friendly stonebraker','2020-06-09 18:58:00'),(5,'happy shannon','2020-02-29 21:39:08'),(6,'competent torvalds','2020-05-24 04:18:45'),(7,'fervent kapitsa','2020-05-21 16:58:12'),(8,'quirky jennings','2020-03-12 12:52:58'),(9,'adoring swartz','2020-04-19 02:20:32'),(14,'intelligent keller','2020-01-08 09:47:42'),(15,'vibrant zhukovsky','2020-04-15 15:15:55'),(18,'keen chatterjee','2020-02-09 06:39:31'),(20,'elastic gauss','2020-03-01 13:34:06'),(21,'affectionate margulis','2020-06-20 10:20:29'),(27,'busy keldysh','2020-05-21 09:10:45'),(31,'flamboyant banach','2020-03-04 21:28:44'),(39,'keen banach','2020-06-09 03:07:57'),(41,'nervous gagarin','2020-06-12 23:43:04'),(47,'wonderful chebyshev','2020-04-15 14:51:17'),(50,'reverent brahmagupta','2020-06-25 21:50:52'),(52,'suspicious elbakyan','2020-05-28 04:55:34'),(55,'epic lichterman','2020-05-16 19:24:09'),(57,'determined taussig','2020-06-18 22:51:37');

DROP TABLE IF EXISTS `t1`;
CREATE TABLE `t1` (
  `c_int` int(11) DEFAULT NULL,
  `c_str` varchar(40) NOT NULL,
  `c_datetime` datetime DEFAULT NULL,
  PRIMARY KEY (`c_str`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `t1` VALUES (19,'nervous johnson','2020-05-04 13:15:19'),(22,'pedantic tu','2020-02-19 09:32:44'),(24,'wizardly robinson','2020-02-03 18:39:36'),(33,'eager stonebraker','2020-05-03 08:20:54'),(34,'zen taussig','2020-06-29 01:18:48'),(36,'epic ganguly','2020-04-23 17:25:13'),(38,'objective euclid','2020-05-21 01:04:27'),(40,'infallible hodgkin','2020-05-07 03:52:52'),(43,'wizardly hellman','2020-04-11 20:20:05'),(46,'inspiring hoover','2020-06-28 14:47:34'),(48,'amazing cerf','2020-05-15 08:04:32'),(49,'objective hermann','2020-04-25 18:01:06'),(51,'upbeat spence','2020-01-27 21:59:54'),(53,'hardcore nightingale','2020-01-20 18:57:37'),(54,'silly hellman','2020-06-24 00:22:47'),(56,'elastic driscoll','2020-02-27 22:46:57'),(58,'nifty buck','2020-03-12 03:56:16');


begin;
insert into t values (59, 'suspicious feistel', '2020-01-29 19:52:14');
insert into t1 values (60, 'practical thompson', '2020-03-25 04:33:10');
select c_int, c_str from t where (select count(*) from t1 where t1.c_int in (t.c_int, t.c_int + 2, t.c_int + 10)) > 2;
rollback;
```

### 2. What did you expect to see? (Required)
```
mysql> select c_int, c_str from t where (select count(*) from t1 where t1.c_int in (t.c_int, t.c_int + 2, t.c_int + 10)) > 2;
Empty set (0.01 sec)
```
### 3. What did you see instead (Required)
```
mysql> select c_int, c_str from t where (select count(*) from t1 where t1.c_int in (t.c_int, t.c_int + 2, t.c_int + 10)) > 2;
+-------+----------------------+
| c_int | c_str                |
+-------+----------------------+
|    50 | reverent brahmagupta |
+-------+----------------------+
1 row in set (0.01 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.3-72-g61f1150e4
Edition: Community
Git Commit Hash: 61f1150e45f929fac9b4b82fc475840efd6b43a1
Git Branch: release-4.0
UTC Build Time: 2020-08-24 11:39:00
GoVersion: go1.14.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

### LINKED ISSUE #19435: apply return wrong result in transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
drop table if exists t, t1;
create table t1(c_int int);
create table t(c_int int);
insert into t values(1),(2),(3),(4),(5),(6),(7),(8),(9);
begin;
insert into t1 values(18);
select (select min(t1.c_int) from t1 where t1.c_int > t.c_int), (select max(t1.c_int) from t1 where t1.c_int> t.c_int), (select sum(t1.c_int) from t1 where t1.c_int> t.c_int) from t;
rollback;
```

### 2. What did you expect to see? (Required)
```
mysql> select (select min(t1.c_int) from t1 where t1.c_int > t.c_int), (select max(t1.c_int) from t1 where t1.c_int> t.c_int), (select sum(t1.c_int) from t1 where t1.c_int> t.c_int) from t;
+---------------------------------------------------------+--------------------------------------------------------+--------------------------------------------------------+
| (select min(t1.c_int) from t1 where t1.c_int > t.c_int) | (select max(t1.c_int) from t1 where t1.c_int> t.c_int) | (select sum(t1.c_int) from t1 where t1.c_int> t.c_int) |
+---------------------------------------------------------+--------------------------------------------------------+--------------------------------------------------------+
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     18 |
+---------------------------------------------------------+--------------------------------------------------------+--------------------------------------------------------+
9 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
```

mysql> select (select min(t1.c_int) from t1 where t1.c_int > t.c_int), (select max(t1.c_int) from t1 where t1.c_int> t.c_int), (select sum(t1.c_int) from t1 where t1.c_int> t.c_int) from t;
+---------------------------------------------------------+--------------------------------------------------------+--------------------------------------------------------+
| (select min(t1.c_int) from t1 where t1.c_int > t.c_int) | (select max(t1.c_int) from t1 where t1.c_int> t.c_int) | (select sum(t1.c_int) from t1 where t1.c_int> t.c_int) |
+---------------------------------------------------------+--------------------------------------------------------+--------------------------------------------------------+
|                                                      18 |                                                     18 |                                                     18 |
|                                                      18 |                                                     18 |                                                     36 |
|                                                      18 |                                                     18 |                                                     54 |
|                                                      18 |                                                     18 |                                                     72 |
|                                                      18 |                                                     18 |                                                     90 |
|                                                      18 |                                                     18 |                                                    108 |
|                                                      18 |                                                     18 |                                                    126 |
|                                                      18 |                                                     18 |                                                    144 |
|                                                      18 |                                                     18 |                                                    162 |
+---------------------------------------------------------+--------------------------------------------------------+--------------------------------------------------------+
9 rows in set (0.01 sec)
```
### 4. What is your TiDB version? (Required)

master & release-4.0

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #19431 and close #19435

Problem Summary:

When union scan is under apply's inner side, it will be called multiple times, and for the memTableReader that reads the dirty table, it uses kvRanges from the base table scan as the range, while the base table scanner will update the kvRanges, it does not set it back when it is closed, therefore the kvRange array will grow, and duplicated rows will be read from the dirty table, resulted in errors.

### What is changed and how it works?

What's Changed:

Add a back up kvRange variable, reset it upon the close of table reader.

### Related changes

- Need to cherry-pick to the release branch 4.0, 3.1 and 3.0

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- No release note.

### CODE REVIEW

**Comment by ichn-hu** [comment]
@XuHuaiyu PTAL and please help assign reviewer.

File: executor/table_reader.go [hunk 1]
```diff
@@ -72,9 +72,10 @@ type TableReaderExecutor struct {
 	ranges []*ranger.Range
 
 	// kvRanges are only use for union scan.
-	kvRanges []kv.KeyRange
-	dagPB    *tipb.DAGRequest
-	startTS  uint64
+	kvRanges       []kv.KeyRange
+	kvRangesBackup []kv.KeyRange
```
Comment (lzmhhh123) [inline executor/table_reader.go:76]: A better way is moving the `buildResp` out of `Open` to `Next`.

Comment (lzmhhh123) [reply executor/table_reader.go:76]: A `Backup` makes me feel weird.

Comment (ichn-hu) [reply executor/table_reader.go:76]: I am feeling ackward as well, perhaps a better name like `initialKvRanges` would make it less weird, while I did not quite get it what you mean by moving the buildResp to `Next`, and I don't think it would solve the problem here. The problem is, whenever `buildResp` is called, new ranges will be added to `kvRanges`, even if it is put under `Next`, as long as it is not cleaned, the redundant ranges will be remained.

**Comment by XuHuaiyu** [comment]
LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by winoros — COMMENTED** [review]
lgtm
