### PR TITLE
planner, type:  fix AggFieldType error when encouter unsigned and sign type

### LINKED ISSUE #9869: Bigint unsigned column value in CASE WHEN operator is converted to bigint signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
drop table if exists t1;
create table t1(a int, b bigint unsigned);
insert into t1 (a, b) values (1,4572794622775114594), (2,18196094287899841997),(3,11120436154190595086);
select (case t1.a when 0 then 0 else t1.b end), cast(t1.b as signed)  from t1;
```
See also https://bugs.mysql.com/bug.php?id=79657
2. What did you expect to see?
```
mysql> select (case t1.a when 0 then 0 else t1.b end), cast(t1.b as signed)  from t1;
+-----------------------------------------+----------------------+
| (case t1.a when 0 then 0 else t1.b end) | cast(t1.b as signed) |
+-----------------------------------------+----------------------+
|                     4572794622775114594 |  4572794622775114594 |
|                    18196094287899841997 |  -250649785809709619 |
|                    11120436154190595086 | -7326307919518956530 |
+-----------------------------------------+----------------------+
3 rows in set (0.01 sec)

```


3. What did you see instead?
```
mysql> select (case t1.a when 0 then 0 else t1.b end), cast(t1.b as signed)  from t1;
+-----------------------------------------+----------------------+
| (case t1.a when 0 then 0 else t1.b end) | cast(t1.b as signed) |
+-----------------------------------------+----------------------+
|                     4572794622775114594 |  4572794622775114594 |
|                     -250649785809709619 |  -250649785809709619 |
|                    -7326307919518956530 | -7326307919518956530 |
+-----------------------------------------+----------------------+
3 rows in set (0.00 sec)
```



4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                        |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-260-g47a564b-dirty
Git Commit Hash: 47a564be2fc6045c6423e63b28a421924d5557bf
Git Branch: master
UTC Build Time: 2019-03-22 07:10:11
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

### LINKED ISSUE #17652: `IFNULL` produce different result with MySQL on bigint column with unsigned flag
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
MySQL [test]> create table t(x bigint unsigned);
Query OK, 0 rows affected (0.006 sec)

MySQL [test]> insert into t values( 9999999703771440633);
Query OK, 1 row affected (0.001 sec)

MySQL [test]> select ifnull(max(x), 0) from t
    -> ;
+----------------------+
| ifnull(max(x), 0)    |
+----------------------+
| -8446744369938110983 |
+----------------------+
1 row in set (0.001 sec)
```

### 2. What did you expect to see? (Required)
result should be 9999999703771440633

### 3. What did you see instead (Required)
-8446744369938110983
### 4. Affected version (Required)
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-rc.2-35-g8ab455575
Edition: Community
Git Commit Hash: 8ab45557504c922b240ab1aed56e66dc566c71be
Git Branch: release-4.0
UTC Build Time: 2020-06-03 09:30:35
GoVersion: go1.13.9
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
<!-- v3.0.0, v4.0.0, etc -->

### 5. Root Cause Analysis

<!-- should be filled by the investigator before it's closed -->

### PR DESCRIPTION
**Pull request by RogerYK**
### What problem does this PR solve?

Issue Number: 
close #9869 
close #17652 

Problem Summary: not process UnsignedFlag in AggFieldType

### What is changed and how it works?

What's Changed:

types/field_type.go

How it Works:

add UnsignedFlag check in mergeFlag
add integral promotion when encounter signed and unsigned

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 
- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- fix Bigint unsigned column value in CASE WHEN operator is converted to bigint signed #9869

### CODE REVIEW

File: expression/constant.go [hunk 1]
```diff
@@ -28,17 +28,21 @@ import (
 
 // NewOne stands for a number 1.
 func NewOne() *Constant {
+	retT := types.NewFieldType(mysql.TypeTiny)
```
Comment (XuHuaiyu) [inline expression/constant.go:31]: I do not understand why we need to change these 2 funcs

File: types/field_type.go [hunk 2]
```diff
@@ -66,15 +66,38 @@ func NewFieldTypeWithCollation(tp byte, collation string, length int) *FieldType
...
 		mtp := MergeFieldType(currType.Tp, t.Tp)
+		isMixedSign = isMixedSign || (mysql.HasUnsignedFlag(currType.Flag) != mysql.HasUnsignedFlag(t.Flag))
 		currType.Tp = mtp
 		currType.Flag = mergeTypeFlag(currType.Flag, t.Flag)
 	}
+	// integral promotion when tps contains signed and unsigned
+	if isMixedSign && IsTypeInteger(currType.Tp) {
+		bumpRange := false // indicate one of tps bump currType range
+		for _, t := range tps {
+			bumpRange = bumpRange || (mysql.HasUnsignedFlag(t.Flag) && (t.Tp == currType.Tp || t.Tp == mysql.TypeBit))
```
Comment (XuHuaiyu) [inline types/field_type.go:84]: Why check `mysql.TypeBit` specially

File: types/field_type.go [hunk 3]
```diff
@@ -66,15 +66,38 @@ func NewFieldTypeWithCollation(tp byte, collation string, length int) *FieldType
...
 			continue
 		}
 		mtp := MergeFieldType(currType.Tp, t.Tp)
+		isMixedSign = isMixedSign || (mysql.HasUnsignedFlag(currType.Flag) != mysql.HasUnsignedFlag(t.Flag))
 		currType.Tp = mtp
 		currType.Flag = mergeTypeFlag(currType.Flag, t.Flag)
 	}
+	// integral promotion when tps contains signed and unsigned
+	if isMixedSign && IsTypeInteger(currType.Tp) {
+		bumpRange := false // indicate one of tps bump currType range
```
Comment (XuHuaiyu) [inline types/field_type.go:82]: Does MySQL also bumpRange ?

File: expression/constant.go (hunk 1 above)
Comment (RogerYK) [reply expression/constant.go:31]: because i make test fail when i modify AggFieldType. The test is palnner/cascades/transformation_rules_test.go  TestTransformAggToProj.  "SQL": "select count(b), sum(b), avg(b), b, max(b), min(b), bit_and(b), bit_or(b), bit_xor(b) from t group by a having sum(b) >= 0 and count(b) >= 0 order by b",

The reason for fail is that the bit_or will add a cast wrap  (cast(b as bigint unsigned binary), the arg is unsigned.
the TransformAggToProj  will add ifnull wrap ifnull(cast(b as bigint unsigned binary), expression.NewZero()).
ifnull use AggFieldType infer type to tigger integral promotion.
[rule_aggregation_elimination.go](https://github.com/pingcap/tidb/blob/master/planner/core/rule_aggregation_elimination.go)  rewriteBitFunc

I think this is a easy way to process. what do you think?

File: types/field_type.go (hunk 3 above)
Comment (RogerYK) [reply types/field_type.go:82]: yes, I refer from here [mysql sql/item.cc](https://github.com/mysql/mysql-server/blob/8.0/sql/item.cc) 557 aggregate_type

File: types/field_type.go (hunk 2 above)
Comment (RogerYK) [reply types/field_type.go:84]: because the TypeBit can't be mergeType and assume it max range bit(64). so it must bump.
I find the all ```IntegerType``` merege  ```mysql.TypeBit```  is ```mysql.TypeVarchar```. 
It is inconsistent with mysql 8.0 <https://github.com/mysql/mysql-server/blob/8.0/sql/field.cc#L248>.

Whether it will be consistent with mysql in the future. if not, No need to consider ```mysql.TypeBit``` here

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @lzmhhh123

**Comment by XuHuaiyu** [comment]
@RogerYK Please add the test case in #17652 to this commit.
It seems that this PR can also fix that issue.

**Comment by RogerYK** [comment]
> @RogerYK Please add the test case in #17652 to this commit.
> It seems that this PR can also fix that issue.

Ok i will add

**Comment by RogerYK** [comment]
> @RogerYK Please add the test case in #17652 to this commit.
> It seems that this PR can also fix that issue.

done

**Comment by XuHuaiyu** [comment]
PTAL @ichn-hu

**Review by ichn-hu — DISMISSED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Comment by RogerYK** [comment]
PTAL @lzmhhh123

**Comment by RogerYK** [comment]
@lzmhhh123 The tests look not stable. How can I avoid it?

**Comment by lzmhhh123** [comment]
> @lzmhhh123 The tests look not stable. How can I avoid it?

Which test?

**Comment by RogerYK** [comment]
> > @lzmhhh123 The tests look not stable. How can I avoid it?
> 
> Which test?

<https://github.com/pingcap/tidb/blob/master/planner/core/physical_plan_test.go#L1647>
<https://github.com/pingcap/tidb/blob/master/planner/core/physical_plan_test.go#L1691>
the test offen fail. but i replay test, it pass.

**Comment by lzmhhh123** [comment]
What's the error of the fail.

**Comment by RogerYK** [comment]
> What's the error of the fail.

The error is the estRows is not equal. now I have no infomation.

**Comment by lzmhhh123** [comment]
Is this test failed?

```

[2020-11-23T09:45:42.107Z] physical_plan_test.go:1731:

[2020-11-23T09:45:42.107Z]     tk.MustQuery("explain " + ts).Check(testkit.Rows(output[i].Plan...))

[2020-11-23T09:45:42.107Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:63:

[2020-11-23T09:45:42.107Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)

[2020-11-23T09:45:42.107Z] ... obtained string = "" +

[2020-11-23T09:45:42.107Z] ...     "[IndexLookUp_7 1441.12 root  ]\n" +

[2020-11-23T09:45:42.107Z] ...     "[├─IndexRangeScan_5(Build) 1441.12 cop[tikv] table:test, index:idx_age(age) range:[5,5], keep order:false]\n" +

[2020-11-23T09:45:42.108Z] ...     "[└─TableRowIDScan_6(Probe) 1441.12 cop[tikv] table:test keep order:false]\n"

[2020-11-23T09:45:42.108Z] ... expected string = "" +

[2020-11-23T09:45:42.108Z] ...     "[IndexLookUp_7 2048.00 root  ]\n" +

[2020-11-23T09:45:42.108Z] ...     "[├─IndexRangeScan_5(Build) 2048.00 cop[tikv] table:test, index:idx_age(age) range:[5,5], keep order:false]\n" +

[2020-11-23T09:45:42.108Z] ...     "[└─TableRowIDScan_6(Probe) 2048.00 cop[tikv] table:test keep order:false]\n"
```

**Comment by RogerYK** [comment]
> Is this test failed?
> 
> ```
> 
> [2020-11-23T09:45:42.107Z] physical_plan_test.go:1731:
> 
> [2020-11-23T09:45:42.107Z]     tk.MustQuery("explain " + ts).Check(testkit.Rows(output[i].Plan...))
> 
> [2020-11-23T09:45:42.107Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:63:
> 
> [2020-11-23T09:45:42.107Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
> 
> [2020-11-23T09:45:42.107Z] ... obtained string = "" +
> 
> [2020-11-23T09:45:42.107Z] ...     "[IndexLookUp_7 1441.12 root  ]\n" +
> 
> [2020-11-23T09:45:42.107Z] ...     "[├─IndexRangeScan_5(Build) 1441.12 cop[tikv] table:test, index:idx_age(age) range:[5,5], keep order:false]\n" +
> 
> [2020-11-23T09:45:42.108Z] ...     "[└─TableRowIDScan_6(Probe) 1441.12 cop[tikv] table:test keep order:false]\n"
> 
> [2020-11-23T09:45:42.108Z] ... expected string = "" +
> 
> [2020-11-23T09:45:42.108Z] ...     "[IndexLookUp_7 2048.00 root  ]\n" +
> 
> [2020-11-23T09:45:42.108Z] ...     "[├─IndexRangeScan_5(Build) 2048.00 cop[tikv] table:test, index:idx_age(age) range:[5,5], keep order:false]\n" +
> 
> [2020-11-23T09:45:42.108Z] ...     "[└─TableRowIDScan_6(Probe) 2048.00 cop[tikv] table:test keep order:false]\n"
> ```

yes, sometime it is right.

**Comment by XuHuaiyu** [comment]
https://github.com/pingcap/tidb/issues/21092

It has nothing to do with this PR. I'll trigger merge again.

**Review by XuHuaiyu — APPROVED** [review]
