### PR TITLE
ranger: fix prefix index when charset is UTF-8

### LINKED ISSUE #7115: Prefix index breaks for ASCII 0xFF(ÿ)
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

After #7109 merged: 
```sql
CREATE TABLE `prefix` (
  `a` int(11) NOT NULL,
  `b` varchar(55) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`),
  KEY `prefix_index` (`b`(2)),
  KEY `prefix_complex` (`a`,`b`(2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO `prefix` VALUES(0, "b", 2), (1, "bbb", 3), (2, "bbc", 4), (3, "bbb", 5), (4, "abc", 6), (5, "abc", 7), (6, "abc", 7), (7, "ÿÿ", 8), (8, "ÿÿ0", 9), (9, "ÿÿÿ", 10)
```

2. What did you expect to see?
```sql
mysql> select c, b from prefix where b > "ÿ" and b < "ÿÿc";
+------+-------+
| c    | b     |
+------+-------+
|    8 | ÿÿ    |
|    9 | ÿÿ0   |
+------+-------+
2 rows in set (0.01 sec)
```

3. What did you see instead?
```sql
mysql> select c, b from prefix where b > "ÿ" and b < "ÿÿc";
Empty set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v2.1.0-beta-83-g48a42fe4
Git Commit Hash: 48a42fe4242b9fb1e1d274bfe3c3b9df99eba43f
Git Branch: master
UTC Build Time: 2018-07-19 07:24:43
GoVersion: go version go1.10.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
```

### PR DESCRIPTION
**Pull request by birdstorm**
## What have you changed? (mandatory)

Fix #7115, this PR will fix prefix index when charset is UTF-8. Previously the index was cut by bytes rather than characters.

## What is the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

Unit Test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

NO

## Does this PR affect tidb-ansible update? (mandatory)

NO

## Does this PR need to be added to the release notes? (mandatory)

```
release note:
fix prefix index, when the charset is utf8 or utf8mb4, truncate it from runes rather than bytes.
```

### CODE REVIEW

File: util/ranger/ranger.go [hunk 1]
```diff
@@ -410,23 +412,38 @@ func hasPrefix(lengths []int) bool {
...
 	}
 }
 
-func fixRangeDatum(v *types.Datum, length int) {
+func fixRangeDatum(v *types.Datum, length int, tp *types.FieldType) {
 	// If this column is prefix and the prefix length is smaller than the range, cut it.
-	if length != types.UnspecifiedLength && length < len(v.GetBytes()) {
-		v.SetBytes(v.GetBytes()[:length])
+	// In case of UTF8, prefix should be cut by characters rather than bytes
+	if v.Kind() == types.KindString || v.Kind() == types.KindBytes {
```
Comment (shenli) [inline util/ranger/ranger.go]: For other types, should we consider length?

File: util/ranger/ranger.go [hunk 2]
```diff
@@ -25,7 +25,9 @@ import (
 	"github.com/pingcap/tidb/mysql"
 	"github.com/pingcap/tidb/sessionctx/stmtctx"
 	"github.com/pingcap/tidb/types"
+	"github.com/pingcap/tidb/util/charset"
 	"github.com/pingcap/tidb/util/codec"
+	"unicode/utf8"
```
Comment (shenli) [inline util/ranger/ranger.go]: Move this to the upper group.

File: plan/physical_plan_test.go [hunk 3]
```diff
@@ -178,7 +178,7 @@ func (s *testPlanSuite) TestDAGPlanBuilderSimpleCase(c *C) {
 		// Test index filter condition push down.
 		{
 			sql:  "select * from t use index(e_d_c_str_prefix) where t.c_str = 'abcdefghijk' and t.d_str = 'd' and t.e_str = 'e'",
-			best: "IndexLookUp(Index(t.e_d_c_str_prefix)[[\"e\" \"d\" \"[97 98 99 100 101 102 103 104 105 106]\",\"e\" \"d\" \"[97 98 99 100 101 102 103 104 105 106]\"]], Table(t)->Sel([eq(test.t.c_str, abcdefghijk)]))",
+			best: "IndexLookUp(Index(t.e_d_c_str_prefix)[[\"e\" \"d\" \"abcdefghij\",\"e\" \"d\" \"abcdefghij\"]], Table(t)->Sel([eq(test.t.c_str, abcdefghijk)]))",
```
Comment (shenli) [inline plan/physical_plan_test.go]: Why is this changed?

File: util/ranger/ranger.go (hunk 2 above)
Comment (winkyao) [reply util/ranger/ranger.go]: Use `gofmt` to format it.

**Comment by shenli** [comment]
@birdstorm Please fix the CI.

File: util/ranger/ranger.go [hunk 4]
```diff
@@ -410,23 +412,38 @@ func hasPrefix(lengths []int) bool {
...
+				truncateStr := string(rs[:length])
+				// truncate value and limit its length
+				v.SetString(truncateStr)
+			}
+		} else {
+			if length != types.UnspecifiedLength && len(v.GetBytes()) > length {
+				// truncate value and limit its length
+				v.SetBytes(v.GetBytes()[:length])
+			}
+		}
```
Comment (winkyao) [inline util/ranger/ranger.go]: what about other types?

File: plan/physical_plan_test.go (hunk 3 above)
Comment (birdstorm) [reply plan/physical_plan_test.go]: You see, now prefix index is set by string when charset is UTF-8 rather than bytes.

File: util/ranger/ranger.go (hunk 1 above)
Comment (birdstorm) [reply util/ranger/ranger.go]: I doubt if it is possible to have prefix index on other types...

Comment (birdstorm) [reply util/ranger/ranger.go]: For string columns, indexes can be created that use only the leading part of column values, using col_name(length) syntax to specify an index prefix length:

- Prefixes can be specified for CHAR, VARCHAR, BINARY, and VARBINARY key parts.

- Prefixes must be specified for BLOB and TEXT key parts. Additionally, BLOB and TEXT columns can be indexed only for InnoDB, MyISAM, and BLACKHOLE tables.

File: util/ranger/ranger.go [hunk 5]
```diff
@@ -410,23 +412,38 @@ func hasPrefix(lengths []int) bool {
...
 
-func fixRangeDatum(v *types.Datum, length int) {
+func fixRangeDatum(v *types.Datum, length int, tp *types.FieldType) {
 	// If this column is prefix and the prefix length is smaller than the range, cut it.
-	if length != types.UnspecifiedLength && length < len(v.GetBytes()) {
-		v.SetBytes(v.GetBytes()[:length])
+	// In case of UTF8, prefix should be cut by characters rather than bytes
+	if v.Kind() == types.KindString || v.Kind() == types.KindBytes {
+		colCharset := tp.Charset
+		if colCharset == charset.CharsetUTF8 || colCharset == charset.CharsetUTF8MB4 {
```
Comment (zz-jason) [inline util/ranger/ranger.go]: how about:
```go
colValue := v.GetBytes()
isUTF8Charset := colCharset == charset.CharsetUTF8 || colCharset == charset.CharsetUTF8MB4
if isUTF8Charset && length != types.UnspecifiedLength && utf8.RuneCount(colValue) > length {
	...
} else if length != types.UnspecifiedLength && len(colValue) > length {
	v.SetBytes(colValue[:length])
}
```

Comment (birdstorm) [reply util/ranger/ranger.go]: @zz-jason Actually I just copied the same logic from https://github.com/pingcap/tidb/blob/e0034f959a54ff58a24eea744d5cc5a095da0454/table/tables/index.go#L133
I left it the same because it seems hard to decide where to put the reusable code. Should both logic be changed or I could move onto another PR to solve this?

Comment (zz-jason) [reply util/ranger/ranger.go]: Uh, I think we can change both logic here in this PR.

Comment (birdstorm) [reply util/ranger/ranger.go]: Done. In addition, isUTF8Charset must be on the outer if-statement to maintain the correct logic.

**Comment by zz-jason** [comment]
Yes, and I think this PR needs a release note.

**Comment by birdstorm** [comment]
@zz-jason yes, I have it in issue description. BTW, please note that this PR might affect speed of prefix index because it has an extra Rune than before (and it might be pretty _**SLOW**_).
