### PR TITLE
executor: fix uint type overflow on generated column not compatible with mysql | tidb-test=pr/2088

### LINKED ISSUE #40066: generate column is not compatible with mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
mysql> CREATE TABLE table_name (
    ->     column1 INT,
    ->     column2 INT UNSIGNED GENERATED ALWAYS AS (column1 - 100)
    -> );
mysql> insert into table_name(column1) values (99);
ERROR 1690 (22003): constant -1 overflows int
mysql> set @@sql_mode='';
Query OK, 0 rows affected (0.00 sec)

mysql> insert into table_name(column1) values (99);
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> select * from table_name;
+---------+------------+
| column1 | column2    |
+---------+------------+
|     101 |          1 |
|      99 | 4294967295 |
+---------+------------+
2 rows in set, 1 warning (0.00 sec)
```

### 2. What did you expect to see? (Required)

```sql
mysql> CREATE TABLE table_name (
    ->     column1 INT,
    ->     column2 INT UNSIGNED GENERATED ALWAYS AS (column1 - 100)
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> insert into table_name(column1) values (101);
Query OK, 1 row affected (0.00 sec)

mysql> insert into table_name(column1) values (99);
ERROR 1264 (22003): Out of range value for column 'column2' at row 1
mysql> set @@sql_mode='';
Query OK, 0 rows affected (0.01 sec)

mysql> insert into table_name(column1) values (99);
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+--------------------------------------------------+
| Level   | Code | Message                                          |
+---------+------+--------------------------------------------------+
| Warning | 1264 | Out of range value for column 'column2' at row 1 |
+---------+------+--------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t;
Empty set (0.00 sec)

mysql> select * from table_name;
+---------+---------+
| column1 | column2 |
+---------+---------+
|     101 |       1 |
|      99 |       0 |
+---------+---------+
2 rows in set (0.00 sec)
```

as you can see: there are 2 issues
1. error message is not the same
2. the query result is different

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #40066

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/write_test.go [hunk 1]
```diff
@@ -4299,3 +4299,19 @@ func TestIssueInsertPrefixIndexForNonUTF8Collation(t *testing.T) {
 	tk.MustExec("insert into t3 select 'abc '")
 	tk.MustGetErrCode("insert into t3 select 'abc d'", 1062)
 }
+
+func TestIssue40066(t *testing.T) {
```
Comment (wjhuang2016) [inline executor/write_test.go:4303]: Please add more tests, for example, type char, decimal

File: table/column.go [hunk 2]
```diff
@@ -691,7 +691,9 @@ func FillVirtualColumnValue(virtualRetTypes []*types.FieldType, virtualColumnInd
 			}
 			// Because the expression might return different type from
 			// the generated column, we should wrap a CAST on the result.
+			sctx.GetSessionVars().StmtCtx.InFillVirtualColumnValue = true
```
Comment (wjhuang2016) [inline table/column.go:694]: Setting it here may cause a data race. FillVirtualColumnValue() can be called concurrently.

Comment (jiyfhust) [reply table/column.go:694]: hi @wjhuang2016 , Can you give me some advice on how to fix it? The core reason is the "ShouldClipToZero"，but i have no idea how to solve it properly.

**Comment by mjonss** [comment]
@jiyfhust, please re-merge with master and resolve conflicts, now that https://github.com/pingcap/tidb/pull/40076 was merged.

File: table/column.go (hunk 2 above)
Comment (wjhuang2016) [reply table/column.go:694]: I'm afraid there is not a clean way to do it. But we can add a particular check after CastValue() in FillVirtualColumnValue. We can check its type and value, then clip it to 0 if necessary.

Comment (jiyfhust) [reply table/column.go:694]: @wjhuang2016 i'm not very sure how to check it as you mentioned. After CastValue()，it should be a valiad destination type value already，how can judge it properly?

**Comment by jiyfhust** [comment]
@wjhuang2016 @mjonss how about change this pr only solve the compatible error and warnings message? The select CastValue seems a little complex, an other pr to solve it specially?

File: table/column.go (hunk 2 above)
Comment (wjhuang2016) [reply table/column.go:694]: You can know its type before CastValue(), and validate its value after CastValue(). If it doesn't obey the `ShouldClipToZero`, then ClipToZero.

File: table/column.go [hunk 3]
```diff
@@ -697,6 +697,24 @@ func FillVirtualColumnValue(virtualRetTypes []*types.FieldType, virtualColumnInd
 			if err != nil {
 				return err
 			}
+
+			if mysql.HasUnsignedFlag(colInfos[idx].FieldType.GetFlag()) && castDatum.GetUint64() > 0 && !sctx.GetSessionVars().StmtCtx.ShouldClipToZero() {
+				switch datum.Kind() {
+				case types.KindInt64:
+					if datum.GetInt64() < 0 {
+						castDatum.SetUint64(0)
```
Comment (mjonss) [inline table/column.go:705]: Should it not be:
```suggestion
						castDatum = GetZeroValue(colInfos[idx])
```

File: table/column.go [hunk 4]
```diff
@@ -697,6 +697,24 @@ func FillVirtualColumnValue(virtualRetTypes []*types.FieldType, virtualColumnInd
...
+					}
+				case types.KindFloat32, types.KindFloat64:
+					if types.RoundFloat(datum.GetFloat64()) < 0 {
+						castDatum.SetUint64(0)
```
Comment (mjonss) [inline table/column.go:709]:
```suggestion
						castDatum = GetZeroValue(colInfos[idx])
```

File: table/column.go [hunk 5]
```diff
@@ -697,6 +697,24 @@ func FillVirtualColumnValue(virtualRetTypes []*types.FieldType, virtualColumnInd
...
+					}
+				case types.KindMysqlDecimal:
+					if datum.GetMysqlDecimal().IsNegative() {
+						castDatum.SetUint64(0)
```
Comment (mjonss) [inline table/column.go:713]:
```suggestion
						castDatum = GetZeroValue(colInfos[idx])
```

**Review by mjonss — COMMENTED** [review]
Should the `castvalue` be set to Uint64(0) or the zero value according to the `colInfos[idx]` type?

File: table/column.go [hunk 6]
```diff
@@ -697,6 +697,24 @@ func FillVirtualColumnValue(virtualRetTypes []*types.FieldType, virtualColumnInd
 			if err != nil {
 				return err
 			}
+
+			if mysql.HasUnsignedFlag(colInfos[idx].FieldType.GetFlag()) && castDatum.GetUint64() > 0 && !sctx.GetSessionVars().StmtCtx.ShouldClipToZero() {
```
Comment (mjonss) [inline table/column.go:701]: What if decimal or float is used and `GetUin64()` would return 0, due to truncation, like if castDatum is float(0.1)?

Comment (mjonss) [reply table/column.go]: Please add a test where castDatum becomes 0.1 (and I think you need to use `castDatum.GetFloat64() > float64(0)` instead of integer types here.
Otherwise LTGM

Comment (jiyfhust) [reply table/column.go]: @mjonss how about remove "castDatum.GetUint64() > 0", if mysql.HasUnsignedFlag(colInfos[idx].FieldType.GetFlag()) && !sctx.GetSessionVars().StmtCtx.ShouldClipToZero(), then check the value?

**Comment by jiyfhust** [comment]
How can solve the tests failed problem? @mjonss

**Comment by wjhuang2016** [comment]
```
    result.go:49: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/execroot/__main__/bazel-out/k8-fastbuild/bin/executor/executor_test_/executor_test.runfiles/__main__/executor/result.go:49
        	            				/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/execroot/__main__/bazel-out/k8-fastbuild/bin/executor/executor_test_/executor_test.runfiles/__main__/executor/stale_txn_test.go:1049
        	Error:      	Not equal: 
        	            	expected: "[1 10]\n"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1 @@
        	            	-[1 10]
        	            	 
        	Test:       	TestStaleReadPrepare
        	Messages:   	sql:execute s1, args:[]
```

**Comment by jiyfhust** [comment]
> 1 10

It seems to be a StaleRead test. I run go test --tags=intest  -run="TestStaleReadPrepare" passed.

Have a retry the test case?

**Comment by jiyfhust** [comment]
@wjhuang2016 fail again...
Where can i see the failed test case as you pasted above?

File: table/column.go [hunk 7]
```diff
@@ -695,6 +695,24 @@ func FillVirtualColumnValue(virtualRetTypes []*types.FieldType, virtualColumnInd
 			if err != nil {
 				return err
 			}
+
+			if mysql.HasUnsignedFlag(colInfos[idx].FieldType.GetFlag()) && !castDatum.IsNull() && !sctx.GetSessionVars().StmtCtx.ShouldClipToZero() {
```
Comment (wjhuang2016) [inline table/column.go:699]: Please add a comment.

**Review by wjhuang2016 — COMMENTED** [review]
rest LGTM

**Comment by jiyfhust** [comment]
> You can check the details on the right side.

I can see log like this, but it does not show which test case failed.

```
time="2023-02-20T19:37:18+08:00" level=warning msg="Create new db&{0 0xc0001a8540 0 {0 0} [0xc0005ea000] map[] 0 1 0xc0005af560 false map[0xc0005ea000:map[0xc0005ea000:true]] map[] 0 0 0 0 <nil> 0 0 0 0 0x490dc0}"

time="2023-02-20T19:37:18+08:00" level=info msg="enable tidb_enable_analyze_snapshot"

./t/prepare.test: ok! 19 test cases passed, take time 0.112661597 s

time="2023-02-20T19:37:18+08:00" level=info msg="run test [prepare] ok"



time="2023-02-20T19:37:18+08:00" level=error msg="1 tests failed\n"

time="2023-02-20T19:37:18+08:00" level=error msg="run test [json_gcol] err: sql:INSERT INTO t(j) VALUES ('{}');: failed to run query \n\"INSERT INTO t(j) VALUES ('{}');\" \n around line 22, \nwe need(95):\nINSERT INTO t(j) VALUES ('{}');\nError 1292: Truncated incorrect INTEGER value: '{}'\nINSERT INTO\nbut got(95):\nINSERT INTO t(j) VALUES ('{}');\nError 1366: Incorrect int value: '{}' for column 'gc' at row 1\n\n"

tidb-server(PID: 1904) stopped

script returned exit code 1
```

Can i get this from somewhere?

```
    result.go:49: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/execroot/__main__/bazel-out/k8-fastbuild/bin/executor/executor_test_/executor_test.runfiles/__main__/executor/result.go:49
        	            				/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/execroot/__main__/bazel-out/k8-fastbuild/bin/executor/executor_test_/executor_test.runfiles/__main__/executor/stale_txn_test.go:1049
        	Error:      	Not equal: 
        	            	expected: "[1 10]\n"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1 @@
        	            	-[1 10]
        	            	 
        	Test:       	TestStaleReadPrepare
        	Messages:   	sql:execute s1, args:[]

```

**Review by wjhuang2016 — APPROVED** [review]

**Comment by wjhuang2016** [comment]
Need to fix mysql-test
``` sql
CREATE TABLE t(id INT, j JSON,
 gc INT GENERATED ALWAYS AS (JSON_EXTRACT(j, '$[0]')));
 INSERT INTO t(id, j) VALUES (0, '"5"'), (1, '[]'), (2, '[1,2]'), (3, '5');
 INSERT INTO t(j) VALUES ('{}');
-Error 1292: Truncated incorrect INTEGER value: '{}'
+Error 1366: Incorrect int value: '{}' for column 'gc' at row 1
 INSERT INTO t(j) VALUES ('{"a":1}');
-Error 1292: Truncated incorrect INTEGER value: '{"a": 1}'
+Error 1366: Incorrect int value: '{"a": 1}' for column 'gc' at row 1
 INSERT INTO t(j) VALUES ('"abc"');
-Error 1292: Truncated incorrect DOUBLE value: 'abc'
+Error 1366: Incorrect int value: '"abc"' for column 'gc' at row 1
 INSERT INTO t(j) VALUES ('');
```

**Comment by jiyfhust** [comment]
Some other mysql-test need to be fixed?
```
time="2023-02-27T14:47:22+08:00" level=error msg="1 tests failed\n"

time="2023-02-27T14:47:22+08:00" level=error msg="run test [gcol_illegal_expression] err: sql:insert into t value (default);: failed to run query \n\"insert into t value (default);\" \n around line 12, \nwe need(86):\ninsert into t value (default);\nError 1690: constant 1.6331239353195392e+16 overflows i\nbut got(86):\ninsert into t value (default);\nError 1264: Out of range value for column 'a' at row 1\n\n"
```

**Review by mjonss — APPROVED** [review]
