### PR TITLE
expression: fix issue that function `dayname` is incompatible with Mysql when doing arithmetic

### LINKED ISSUE #9713: Function `dayname` is incompatible with Mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select dayname("1962-03-01")+0;
select dayname("1962-03-02")+0;
select dayname("1962-03-03")+0;
select dayname("1962-03-04")+0;
select dayname("1962-03-05")+0;
select dayname("1962-03-06")+0;
select dayname("1962-03-07")+0;
select dayname("1962-03-08")+0;
select dayname("1962-03-01")+1;
select dayname("1962-03-01")+2;
select dayname("1962-03-01")+3;
select dayname("1962-03-01")+4;
select dayname("1962-03-01")+5;
select dayname("1962-03-01")+6;
select dayname("1962-03-01")+7;
select dayname("1962-03-01")+2333;
select dayname("1962-03-01")+2.333;

select dayname("1962-03-01")>2;
select dayname("1962-03-01")<2;
select dayname("1962-03-01")=3;
select dayname("1962-03-01")!=3;
select dayname("1962-03-01")<4;
select dayname("1962-03-01")>4;
select !dayname("1962-03-01");
select dayname("1962-03-01")&1;
select dayname("1962-03-01")&3;
select dayname("1962-03-01")&7;
select dayname("1962-03-01")|1;
select dayname("1962-03-01")|3;
select dayname("1962-03-01")|7;
select dayname("1962-03-01")^1;
select dayname("1962-03-01")^3;
select dayname("1962-03-01")^7;
```

2. What did you expect to see?

```
mysql> select dayname("1962-03-01")+0;
+-------------------------+
| dayname("1962-03-01")+0 |
+-------------------------+
|                       3 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-02")+0;
+-------------------------+
| dayname("1962-03-02")+0 |
+-------------------------+
|                       4 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-03")+0;
+-------------------------+
| dayname("1962-03-03")+0 |
+-------------------------+
|                       5 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-04")+0;
+-------------------------+
| dayname("1962-03-04")+0 |
+-------------------------+
|                       6 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-05")+0;
+-------------------------+
| dayname("1962-03-05")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-06")+0;
+-------------------------+
| dayname("1962-03-06")+0 |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-07")+0;
+-------------------------+
| dayname("1962-03-07")+0 |
+-------------------------+
|                       2 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-08")+0;
+-------------------------+
| dayname("1962-03-08")+0 |
+-------------------------+
|                       3 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+1;
+-------------------------+
| dayname("1962-03-01")+1 |
+-------------------------+
|                       4 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+2;
+-------------------------+
| dayname("1962-03-01")+2 |
+-------------------------+
|                       5 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+3;
+-------------------------+
| dayname("1962-03-01")+3 |
+-------------------------+
|                       6 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+4;
+-------------------------+
| dayname("1962-03-01")+4 |
+-------------------------+
|                       7 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+5;
+-------------------------+
| dayname("1962-03-01")+5 |
+-------------------------+
|                       8 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+6;
+-------------------------+
| dayname("1962-03-01")+6 |
+-------------------------+
|                       9 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+7;
+-------------------------+
| dayname("1962-03-01")+7 |
+-------------------------+
|                      10 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+2333;
+----------------------------+
| dayname("1962-03-01")+2333 |
+----------------------------+
|                       2336 |
+----------------------------+
1 row in set (0.00 sec)

mysql> select dayname("1962-03-01")+2.333;
+-----------------------------+
| dayname("1962-03-01")+2.333 |
+-----------------------------+
|                       5.333 |
+-----------------------------+
1 row in set (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> select dayname("1962-03-01")+0;
+-------------------------+
| dayname("1962-03-01")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-02")+0;
+-------------------------+
| dayname("1962-03-02")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-03")+0;
+-------------------------+
| dayname("1962-03-03")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-04")+0;
+-------------------------+
| dayname("1962-03-04")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-05")+0;
+-------------------------+
| dayname("1962-03-05")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-06")+0;
+-------------------------+
| dayname("1962-03-06")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-07")+0;
+-------------------------+
| dayname("1962-03-07")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-08")+0;
+-------------------------+
| dayname("1962-03-08")+0 |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+1;
+-------------------------+
| dayname("1962-03-01")+1 |
+-------------------------+
|                       1 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+2;
+-------------------------+
| dayname("1962-03-01")+2 |
+-------------------------+
|                       2 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+3;
+-------------------------+
| dayname("1962-03-01")+3 |
+-------------------------+
|                       3 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+4;
+-------------------------+
| dayname("1962-03-01")+4 |
+-------------------------+
|                       4 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+5;
+-------------------------+
| dayname("1962-03-01")+5 |
+-------------------------+
|                       5 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+6;
+-------------------------+
| dayname("1962-03-01")+6 |
+-------------------------+
|                       6 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+7;
+-------------------------+
| dayname("1962-03-01")+7 |
+-------------------------+
|                       7 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+2333;
+----------------------------+
| dayname("1962-03-01")+2333 |
+----------------------------+
|                       2333 |
+----------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayname("1962-03-01")+2.333;
+-----------------------------+
| dayname("1962-03-01")+2.333 |
+-----------------------------+
|                       2.333 |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-212-g0681b8125
Git Commit Hash: 0681b8125080045ee0d4747ce61923164c6f2dd1
Git Branch: master
UTC Build Time: 2019-03-14 04:39:19
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve? 
Fix #9713 

When doing arithmetic using results of function `DayName` in MySQL, there is a special cast process that "Monday" should be cast to 0, "Tuesday" should be cast to 1 and so on.
Now TiDB doesn't have this special cast process.

### What is changed and how it works?
When building cast function, check if it is `DayName`, and if it is, use its own special cast function.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: expression/builtin_cast.go [hunk 1]
```diff
@@ -1687,6 +1687,23 @@ func (i inCastContext) String() string {
...
+// hasSpecialCast checks if this expr has its own special cast function.
+// for example(#9713): when doing arithmetic using results of function DayName,
+// "Monday" should be regarded as 0, "Tuesday" should be regarded as 1 and so on.
+func hasSpecialCast(ctx sessionctx.Context, expr Expression, tp *types.FieldType) bool {
+	switch f := expr.(type) {
+	case *ScalarFunction:
+		switch f.FuncName.L {
+		case ast.DayName:
+			switch tp.EvalType() {
+			case types.ETInt, types.ETReal:
```
Comment (lamxTyler) [inline expression/builtin_cast.go]: What about first check the type?

File: expression/function_traits.go [hunk 2]
```diff
@@ -42,6 +42,7 @@ var unFoldableFunctions = map[string]struct{}{
 	ast.GetVar:    {},
 	ast.GetParam:  {},
 	ast.Benchmark: {},
+	ast.DayName:   {},
```
Comment (lamxTyler) [inline expression/function_traits.go]: Why unfoldable?

Comment (qw4990) [reply expression/function_traits.go]: If we fold it, it's unable to check the function name in `BuildCastFunction`, since `expr` corresponding to `DayName` has been converted from `*ScalarFunction` to `*Constant`.

File: expression/builtin_cast.go (hunk 1 above)
Comment (qw4990) [reply expression/builtin_cast.go]: Checking function name first may be faster? 
There are only a small amount of functions who have a special cast process but almost all functions need to be cast to `Int` or `Real` in some cases.
So in most cases, checking function name first will do `switch-case` only once while it have to do it twice if we check type first.

File: expression/builtin_time.go [hunk 3]
```diff
@@ -1079,21 +1079,45 @@ func (b *builtinDayNameSig) Clone() builtinFunc {
...
+// See https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_dayname
+func (b *builtinDayNameSig) evalString(row chunk.Row) (string, bool, error) {
+	idx, isNull, err := b.evalIndex(row)
+	if isNull || err != nil {
+		return "", isNull, err
+	}
+	return types.WeekdayNames[idx], false, nil
+}
+
+func (b *builtinDayNameSig) evalReal(row chunk.Row) (float64, bool, error) {
```
Comment (lzmhhh123) [inline expression/builtin_time.go]: When does it call this function?

Comment (qw4990) [reply expression/builtin_time.go]: When handling a arithmetic expression like `dayname(xxx)+2.333`, since `2.333` is a real number, `expression_rewriter` will convert the type of `dayname(xxx)` to `real` by wrapping a cast function.
It is the cast function that will call the `evalReal`.

File: expression/builtin_cast.go [hunk 4]
```diff
@@ -1699,6 +1716,10 @@ func BuildCastFunction4Union(ctx sessionctx.Context, expr Expression, tp *types.
 
 // BuildCastFunction builds a CAST ScalarFunction from the Expression.
 func BuildCastFunction(ctx sessionctx.Context, expr Expression, tp *types.FieldType) (res Expression) {
+	if hasSpecialCast(ctx, expr, tp) {
```
Comment (zz-jason) [inline expression/builtin_cast.go]: this check should be added in the case of `types.ETInt`, `types.ETReal` and `types.ETString`

Comment (qw4990) [reply expression/builtin_cast.go]: Do you means that check `tp.Type` here and call `hasSpecialCast` only when it's `int`, `real` or `string`?

Comment (zz-jason) [reply expression/builtin_cast.go]: Oh, I missed the type check in function `hasSpecialCast()`. How about s/hasSpecialCast/skipCastDayname/?

Comment (qw4990) [reply expression/builtin_cast.go]: I'm afraid that there may be more functions who have a special cast process, then we can add them all here and it's not just for `DayName`.

Comment (zz-jason) [reply expression/builtin_cast.go]: okay
