### PR TITLE
lightning: fix pd leader switch CI after PD upgrading

### LINKED ISSUE #55487: When PD leader switches, `SchemaChecker` may return `ErrInfoSchemaExpired`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/1084/pipeline

### 3. What did you see instead (Required)

```
[2024/08/16 19:09:35.821 +08:00] [INFO] [session.go:4061] ["CRUCIAL OPERATION"] [conn=2283798532] [schemaVersion=51] [cur_db=] [sql="CREATE DATABASE IF NOT EXISTS `cpeng`;"] [user=root@%]
[2024/08/16 19:09:40.837 +08:00] [WARN] [session.go:816] ["can not retry txn"] [label=internal] [error="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV"] [IsBatchInsert=false] [IsPessimistic=true] [InRestrictedSQL=true] [tidb_retry_limit=10] [tidb_disable_txn_auto_retry=true]
```

the 5 second interval equals to `SchemaOutOfDateRetryInterval` * `SchemaOutOfDateRetryTimes`

[tidb.log](https://github.com/user-attachments/files/16654464/tidb.log)

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #55487

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: lightning/tests/lightning_pd_leader_switch/run.sh [hunk 1]
```diff
@@ -43,7 +45,7 @@ pd-server --join "https://$PD_ADDR" \
 killall tidb-server
 # wait for TiDB to exit to release file lock
 sleep 5
-start_tidb
+PD_ADDR="${PD_ADDR},${PD_ADDR}2,${PD_ADDR}3" start_tidb
```
Comment (lance6716) [inline lightning/tests/lightning_pd_leader_switch/run.sh:48]: we focus on testing lightning's behaviour of discovering new PD members, not testing TiDB. So passing all PD addresses to TiDB

Comment (lhy1024) [reply lightning/tests/lightning_pd_leader_switch/run.sh:48]: I think we do not to add it

Comment (lhy1024) [reply lightning/tests/lightning_pd_leader_switch/run.sh:48]: The results of this test show that it can still pass the test https://github.com/pingcap/tidb/pull/55491
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/1115/pipeline

File: lightning/tests/config/pd.toml [hunk 2]
```diff
@@ -1,6 +1,3 @@
-lease = 360
```
Comment (lhy1024) [inline lightning/tests/config/pd.toml:1]: Do we need to update BR test config?

Comment (lance6716) [reply lightning/tests/config/pd.toml:1]: https://github.com/pingcap/tidb/pull/55498/commits/4ed8bf7d95a7a23df8706a68219644c1651c5ae2

I have confirmed with @YuJuncen . @YuJuncen  PTAL

File: lightning/tests/lightning_pd_leader_switch/run.sh (hunk 1 above)
Comment (lance6716) [reply lightning/tests/lightning_pd_leader_switch/run.sh:48]: OK, I'll remove it

**Review by D3Hunter — APPROVED** [review]

File: lightning/tests/lightning_pd_leader_switch/run.sh (hunk 1 above)
Comment (lance6716) [reply lightning/tests/lightning_pd_leader_switch/run.sh]: https://github.com/pingcap/tidb/pull/55498/commits/0e6beb4ec1424710de1eca54d9ca9a6e8e077860

**Comment by joccau** [comment]
Maybe need to run the br intergration test ?

**Review by joccau — APPROVED** [review]
LGTM

**Review by lhy1024 — APPROVED** [review]

**Comment by lance6716** [comment]
> Maybe need to run the br intergration test ?

It's run automatically, in a recent change of CI pipeline.

**Review by Leavrth — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
