### PR TITLE
domain: disable closest-adaptive dynamically to make read traffic more even

### LINKED ISSUE #35926: more flexible follower read dispatch strategy
## Enhancement

In the cloud environment, the tidb clusters are commonly deployed across multiple "Access Zone"(AZ for short)s. Because the traffic cost across different AZ is much higher than within the same AZ. We can reduce the cost by dispatching read request to 
the TiKV/TiFlash with a higher priority. 

#28033 introduced a new `tidb_replica_read` option "closest-replica" that always dispatch all read request to the closest TiKV. But since the "follower read" feature need to propose an extra "readIndex" message through the raft state machine. This overhead may cause performance regression. For cop requests with small response, read from local AZ can not save the traffic because the extra "readIndex" messages are always cross AZ traffic. And the extra cpu usage to process these raft message can hurt the performance.

I propose to add a new option "closest-adaptive" for `tidb_replica_read` variable. This new option tries to dispatch request to the nearest store only when the response size is bigger than a certain threshold which is define by a new variable "tidb_adaptive_closest_read_threshold".

BTW, when the cop traffic from tidbs in different AZ are not evenly distributed, it may cause high load in some store while other are low loaded. This can cause high tail-lantency and low overall throughput. So when follow-read is enabled, the tikv client may need to track the load of each storage and force fallback to leader read when some stores' load are high.

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: ref #35926

Problem Summary:

### What is changed and how it works?
This PR is an enhancement of #36824, in the previous PR, we only enable "closest-adaptive" when all AZ's contains both tidb and tikv instance. But the previous change can't guarantee that traffic is evenly distribute in different when the tidb instances number is different across AZs.

This PR improve the strategy by always enable the same number of tidb instances' "closest-adaptive" in all AZs and set the extra instances with "leader" read.
Since tidb is stateless, we use a simple algorithm to choose the extra tidb instance by choosing tidb with a bigger ID first.

Example:
There are 3 tikv instance in 3 AZ az1, az2, az3. And 5 tidb server: tidb1 in az1, tidb2 and tidb3 in az2, tidb4 in az3, tidb5 in az4.
In the previous version we will just disable "closest-adaptive" on all tidb because az4 contains no tikv.
After this change, only tidb5 and tidb3 is disabled, and the other 3 are enabled.

### Check List

Tests 

- [x] Unit test

Side effects

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: domain/domain.go [hunk 1]
```diff
@@ -1134,32 +1158,48 @@ func (do *Domain) checkReplicaRead(ctx context.Context, pdClient pd.Client) erro
...
 		}
 	}
+	enabledCount := math.MaxInt
+	for _, count := range storeZones {
+		if count < enabledCount {
+			enabledCount = count
+		}
+	}
+	// sort tidb in the same AZ by ID and disable the tidb with bigger ID
+	// because ID is unchangable, so this is a simple and stable algorithm to select
```
Comment (xhebox) [inline domain/domain.go:1189]:
```suggestion
	// because ID is unchangeable, so this is a simple and stable algorithm to select
```

Fix CI build

File: domain/domain.go [hunk 2]
```diff
@@ -1134,32 +1158,48 @@ func (do *Domain) checkReplicaRead(ctx context.Context, pdClient pd.Client) erro
...
+		}
+	}
+	// sort tidb in the same AZ by ID and disable the tidb with bigger ID
+	// because ID is unchangeable, so this is a simple and stable algorithm to select
+	// some instances across all tidb servers.
+	if enabledCount < len(svrIdsInThisZone) {
+		sort.Slice(svrIdsInThisZone, func(i, j int) bool {
+			return strings.Compare(svrIdsInThisZone[i], svrIdsInThisZone[j]) < 0
+		})
+	}
```
Comment (xhebox) [inline domain/domain.go:1195]: Is there a possiblity of `enabledCount > len(svrIdsInThisZone)`? Then `svrIdsInThisZone[enabledCount:]` is invalid.

File: domain/infosync/info.go [hunk 3]
```diff
@@ -314,22 +317,26 @@ func (is *InfoSyncer) getServerInfoByID(ctx context.Context, id string) (*Server
...
-				},
-			},
-			"ad84dbbd-5a50-4742-a73c-4f674d41d4bd": {
-				Labels: map[string]string{
-					"zone": "zone2",
-				},
-			},
-		}
-		failpoint.Return(res, nil)
+		failpoint.Return(allServerInfo4Test, nil)
```
Comment (xhebox) [inline domain/infosync/info.go:339]: Maybe we can use `failpoint.Enable("github.com/pingcap/tidb/domain/infosync/mockGetServerInfo", fmt.Sprintf("return(\"%s\")", the_result_of_json_marshaled_info))`, then you could unmarshal that string in `failpoint.Inject("mockGetAllServerInfo", ` without global vars.

Comment (glorv) [reply domain/infosync/info.go:339]: Is this the recommended way to do so. This will decrease the readablity as some value are relatively long.

Comment (xhebox) [reply domain/infosync/info.go:339]: You could construct a struct and marshal it into string. Yeah, this is actually a best practice of failpoint, though lots of people don't know how to pass value into the inject point.

Comment (glorv) [reply domain/infosync/info.go]: done. @xhebox  PTAL again, thank you~

**Review by xhebox — APPROVED** [review]

**Comment by glorv** [comment]
@nolouch  PTAL

**Review by nolouch — APPROVED** [review]
lgtm
