### PR TITLE
infoschema: fix panic for `TableByID` when table id is negative

### LINKED ISSUE #52012: panic log for some http API with negative table id
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
> curl "http://127.0.0.1:10080/db-table/-123"
```

### 2. What did you expect to see? (Required)

```
> curl "http://127.0.0.1:10080/db-table/-123"
[schema:1146]Table which ID = -123 does not exist.
```

### 3. What did you see instead (Required)

```
> curl "http://127.0.0.1:10081/db-table/-123"
curl: (52) Empty reply from server
```

And a panic log in tidb

```
2024/03/22 10:42:52 http: panic serving 127.0.0.1:53256: runtime error: index out of range [-123]
goroutine 5202 [running]:
net/http.(*conn).serve.func1()
        /Users/wangchao/.gvm/gos/go1.21.0/src/net/http/server.go:1868 +0x118
panic({0x1081c98c0?, 0x140189ca198?})
        /Users/wangchao/.gvm/gos/go1.21.0/src/runtime/panic.go:920 +0x254
github.com/pingcap/tidb/pkg/infoschema.(*infoSchema).TableByID(0x140059bba00, 0xffffffffffffff85)
        /Users/wangchao/Code/pingcap/tidb/pkg/infoschema/infoschema.go:235 +0xfc
github.com/pingcap/tidb/pkg/server/handler/tikvhandler.DBTableHandler.ServeHTTP({0x1401179e5d0}, {0x10850bac0, 0x140189b6000}, 0x14017be9c00)
        /Users/wangchao/Code/pingcap/tidb/pkg/server/handler/tikvhandler/tikv_handler.go:1805 +0x238
github.com/gorilla/mux.(*Router).ServeHTTP(0x1401142cf00, {0x10850bac0, 0x140189b6000}, 0x14017be9c00)
        /Users/wangchao/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x254
net/http.(*ServeMux).ServeHTTP(0x140118b5900, {0x10850bac0, 0x140189b6000}, 0x14017be9a00)
        /Users/wangchao/.gvm/gos/go1.21.0/src/net/http/server.go:2514 +0x160
github.com/pingcap/tidb/pkg/server/internal/util.CorsHandler.ServeHTTP({{0x1084ed0e0, 0x140118b5900}, 0x140007de900}, {0x10850bac0, 0x140189b6000}, 0x14017be9a00)
        /Users/wangchao/Code/pingcap/tidb/pkg/server/internal/util/util.go:219 +0xe0
net/http.serverHandler.ServeHTTP({0x1401142f1d0}, {0x10850bac0, 0x140189b6000}, 0x14017be9a00)
        /Users/wangchao/.gvm/gos/go1.21.0/src/net/http/server.go:2938 +0x2a0
net/http.(*conn).serve(0x140189a4000, {0x108520c18, 0x140189a6050})
        /Users/wangchao/.gvm/gos/go1.21.0/src/net/http/server.go:2009 +0x155c
created by net/http.(*Server).Serve in goroutine 573
        /Users/wangchao/.gvm/gos/go1.21.0/src/net/http/server.go:3086 +0x7f8
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #52012

### What changed and how does it work?

tableBucketIdx should always return an non-negative value.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/infoschema/builder.go [hunk 1]
```diff
@@ -969,8 +969,11 @@ func NewBuilder(r autoid.Requirement, factory func() (pools.Resource, error), in
 	}
 }
 
-func tableBucketIdx(tableID int64) int {
-	return int(tableID % bucketCount)
+func tableBucketIdx(tableID int64) (idx int) {
+	if idx = int(tableID % bucketCount); idx < 0 {
+		idx = -idx
```
Comment (tiancaiamao) [inline pkg/infoschema/builder.go:974]: If I just read this line with no more context ... I would be feel puzzled why tableID could be a negative number ...

**Review by tiancaiamao — APPROVED** [review]

File: pkg/infoschema/builder.go (hunk 1 above)
Comment (lcwangchao) [reply pkg/infoschema/builder.go:974]: You can see the issue: https://github.com/pingcap/tidb/issues/52012

Comment (tiancaiamao) [reply pkg/infoschema/builder.go:974]: And maybe it would be a better way if we can track where negative tableID comes from, and return error for the illegal input ...

**Review by AilinKid — APPROVED** [review]

File: pkg/infoschema/builder.go (hunk 1 above)
Comment (lcwangchao) [reply pkg/infoschema/builder.go:974]: In fact, this PR sees a negative `tableID` as an "legal" value even if we will not not create an table with a negative id. And pass a negative table id to `TableByID` still returns error because table not exist...

Another option is regarding negative id as "illegal", so we need also check the table id both in building a infoschema and `TableByID`, and returns error if it is negative instead of panic

**Review by AilinKid — COMMENTED** [review]
/dismiss

File: pkg/infoschema/builder.go [hunk 2]
```diff
@@ -970,9 +971,10 @@ func NewBuilder(r autoid.Requirement, factory func() (pools.Resource, error), in
 }
 
 func tableBucketIdx(tableID int64) int {
+	intest.Assert(tableID > 0)
```
Comment (zimulala) [inline pkg/infoschema/builder.go:974]: Will this `tableID > 0` be false in the test scenario? If so, whether it is possible to encounter real scenes. If not, is the test unnecessary?

Comment (lcwangchao) [reply pkg/infoschema/builder.go:974]: We found `tableID <= 0` in some test cases but they are handled before `tableBucketIdx`. Adding assert here for two propose:

- Provide a more clear reason for the failed test even if it would also fail without the assert function. The assert function is a more straightforward way to check the constraints.

- This assert also checks `tableID` should not be `0`. It may not fail if some codes building infoschema with an zero id table.

**Review by zimulala — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]
