### PR TITLE
 ddl: Fix rename table bug

### LINKED ISSUE #4858: rename table to anothor database causing insert to fail
1. What did you do?

There's some history about rename schema name in MySQL as described in this blog:
https://www.percona.com/blog/2013/12/24/renaming-database-schema-mysql/

It seems that TiDB doen't support rename database name in a simple way either.

Because we tend to create all databases in one TiDB cluster,  we must choose schema carefully, but if name clash actually happens, we have to rename the database name.

So I tried to rename database as described in above blog using syntax as: `rename table db1.t1  to  db2.t1`

this is a simple test case to reproduce:
```sql

create database db1;
create database db2;
create table db1.t1 (id int);
rename table db1.t1 to  db2.t1;
insert into db2.t1 values (1);
use db2;
insert into t1 values (1);
```

2. What did you expect to see?

the moved table should work properly

3. What did you see instead?

I can not insert data into the new table any longer (while select is OK)

```sql
TiDB-Server [test]> create database db1;
Query OK, 0 rows affected (1.25 sec)

TiDB-Server [test]> create database db2;
Query OK, 0 rows affected (1.21 sec)

TiDB-Server [test]> create table db1.t1 (id int);
Query OK, 0 rows affected (1.32 sec)

TiDB-Server [test]> rename table db1.t1 to  db2.t1;
Query OK, 0 rows affected (1.17 sec)

TiDB-Server [test]> insert into db2.t1 values (1);
ERROR 1146 (42S02): table doesn't exist

TiDB-Server [test]> use db2
Database changed
TiDB-Server [db2]> show tables;
+---------------+
| Tables_in_db2 |
+---------------+
| t1            |
+---------------+
1 row in set (0.00 sec)

TiDB-Server [db2]> insert into t1 values (1);
ERROR 1146 (42S02): table doesn't exist
```

4. What version of TiDB are you using (`tidb-server -V`)?

Release Version: 1.0.0
Git Commit Hash: 21c21973c092e3e192c0210933448d7b394e74cb
Git Branch: master
UTC Build Time: 2017-10-17 01:35:28

### PR DESCRIPTION
**Pull request by zimulala**
Fix #4858

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL  @winkyao @coocood @shenli

**Comment by shenli** [comment]
@coocood @winkyao PTAL

File: infoschema/builder.go [hunk 1]
```diff
@@ -98,6 +103,19 @@ func (b *Builder) ApplyDiff(m *meta.Meta, diff *model.SchemaDiff) ([]int64, erro
 	return tblIDs, nil
 }
 
+func (b *Builder) getAllocatorAfterRenameTable(m *meta.Meta, oldSchemaID, newSchemaID, tableID int64) (autoid.Allocator, error) {
+	id, err := m.GetAutoTableID(oldSchemaID, tableID)
+	if err != nil {
+		return nil, errors.Trace(err)
+	}
+	alloc := autoid.NewAllocator(b.handle.store, newSchemaID)
+	err = alloc.Rebase(tableID, id, true)
```
Comment (shenli) [inline infoschema/builder.go]: What about we have multiple tidb-servers?

Comment (zimulala) [reply infoschema/builder.go]: We use `GetAutoTableID` to get the ID from TiKV, so it‘s no problem.

Comment (shenli) [reply infoschema/builder.go]: Move this to the ddl owner.

**Comment by zimulala** [comment]
PTAL @shenli

File: executor/ddl_test.go [hunk 2]
```diff
@@ -219,18 +219,37 @@ func (s *testSuite) TestRenameTable(c *C) {
...
+	tk.MustQuery("select * from rename3.t").Check(testkit.Rows("1", "5001", "10001"))
 	tk.MustExec("drop database rename1")
 	tk.MustExec("drop database rename2")
 	tk.MustExec("drop database rename3")
+
+	tk.MustExec("create database rename1")
+	tk.MustExec("create database rename2")
+	tk.MustExec("create table rename1.t (a int primary key auto_increment)")
+	tk.MustExec("rename table rename1.t to rename2.t1")
+	tk.MustExec("insert rename2.t1 values ()")
```
[the remark this answers is not in the document]
Comment (zimulala) [reply executor/ddl_test.go]: `rename2.t1` ? Done.

File: ddl/table.go [hunk 3]
```diff
@@ -265,6 +265,14 @@ func (d *ddl) onRenameTable(t *meta.Meta, job *model.Job) (ver int64, _ error) {
 		return ver, errors.Trace(err)
 	}
 
+	// Update the table's auto increment ID.
+	if newSchemaID != oldSchemaID {
+		_, err = t.GenAutoTableID(newSchemaID, tblInfo.ID, baseID)
```
Comment (shenli) [inline ddl/table.go]: When running this DDL, user insert a bulk of data into the table. So some tidb-sever may allocate ID larger than current baseID.

File: executor/ddl_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (winkyao) [reply executor/ddl_test.go]: no, I means insert back to rename1.t, it should fail as expected.

[the remark this answers is not in the document]
Comment (zimulala) [reply executor/ddl_test.go]: I did it in line 253.

File: ddl/table.go (hunk 3 above)
Comment (winkyao) [reply ddl/table.go]: @shenli If others update the autoTableID base, this ddl txn will fail cause by key changed?

File: executor/ddl_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (winkyao) [reply executor/ddl_test.go]: Okay

File: ddl/table.go (hunk 3 above)
Comment (winkyao) [reply ddl/table.go]: I think line 255 should change to `err = t.DropTable(oldSchemaID, tblInfo.ID, true)`, It will be more reasonable. But the issue you mention will not happen, because allocate ID is got from GenAutoTableID, which will hinc the old autoID key, and the dll job will failed cause by the key changed.

Comment (winkyao) [reply ddl/table.go]: Okay, I got it. if this ddl commit firstly, maybe in other tidb will get the old autoID key because the schema is not syncd in this tidb.

File: ddl/table.go [hunk 4]
```diff
@@ -309,3 +316,15 @@ func updateTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.TableInfo, ori
 
 	return ver, t.UpdateTable(job.SchemaID, tblInfo)
 }
+
+// cleanAllocatorKey cleans up auto ID key.
+func cleanAllocatorKey(t *meta.Meta, tblInfo *model.TableInfo) error {
```
Comment (coocood) [inline ddl/table.go]: Can we remove the `delAutoID` argument in `meta.DropTable` and do it in this method?

Comment (winkyao) [reply ddl/table.go]: +1

**Comment by zimulala** [comment]
PTAL @coocood @winkyao

**Comment by coocood** [comment]
LGTM
