### PR TITLE
local backend: fix sst skip ingest when multiIngest=false and exhausted retry count

### LINKED ISSUE #50198: some sst might be skipped ingest when inner loop exhausted retry count
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)
when `multiIngest = false`, some sst might be skipped ingest when
- there're at least 2 batches
- on the first batch, inner loop exhausted retry count, as the err is not handled after this loop, it continue, so this batch is skipped
- continue with second batch, success

https://github.com/pingcap/tidb/blob/6a5b2a3f0be393de06aa194d7b7d471a18468476/br/pkg/lightning/backend/local/local.go#L1469

### 4. What is your TiDB version? (Required)
6.5/6.1

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #50198

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by D3Hunter** [comment]
cc @mittalrishabh

**Comment by D3Hunter** [comment]
/hold

to wait ci

File: br/pkg/lightning/backend/local/local.go [hunk 1]
```diff
@@ -1531,19 +1531,18 @@ loopWrite:
 					continue
 				}
 			}
+			if err != nil {
```
Comment (lance6716) [inline br/pkg/lightning/backend/local/local.go:1534]: after I comment this part, the UT still passed

```diff
diff --git a/br/pkg/lightning/backend/local/local.go b/br/pkg/lightning/backend/local/local.go
index c21d363c90..24ccf23588 100644
--- a/br/pkg/lightning/backend/local/local.go
+++ b/br/pkg/lightning/backend/local/local.go
@@ -1531,11 +1531,11 @@ loopWrite:
                                        continue
                                }
                        }
-                       if err != nil {
-                               log.FromContext(ctx).Warn("batch ingest fail after retry, will retry import full range", log.ShortError(err),
-                                       logutil.Region(region.Region), zap.Reflect("meta", ingestMetas))
-                               return errors.Trace(err)
-                       }
+                       //if err != nil {
+                       //      log.FromContext(ctx).Warn("batch ingest fail after retry, will retry import full range", log.ShortError(err),
+                       //              logutil.Region(region.Region), zap.Reflect("meta", ingestMetas))
+                       //      return errors.Trace(err)
+                       //}
                }
 
                engine.importedKVSize.Add(rangeStats.totalBytes)
diff --git a/br/pkg/lightning/backend/local/local_test.go b/br/pkg/lightning/backend/local/local_test.go
index 32cc72441c..b032c8bad3 100644
--- a/br/pkg/lightning/backend/local/local_test.go
+++ b/br/pkg/lightning/backend/local/local_test.go
@@ -1499,5 +1499,4 @@ func TestIngestFailOnFirstBatch(t *testing.T) {
        }, []byte{}, []byte("b"), 0, 0)
        require.ErrorContains(t, err, "Suspended { time_to_lease_expire: 1.204s }")
        require.Equal(t, []uint64{1}, apiInvokeRecorder["Write"])
-       require.Equal(t, []uint64{1, 1, 1, 1, 1}, apiInvokeRecorder["Ingest"])
 }
```

`apiInvokeRecorder["Ingest"]` is `1` repeated 15 times so I also remove its check

Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1534]: the check is required, it should repeat 5 times on the first batch, and report err, not continue

Comment (lance6716) [reply br/pkg/lightning/backend/local/local.go:1534]: `        require.ErrorContains(t, err, "Suspended { time_to_lease_expire: 1.204s }")` this check is not deleted and it passed

Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1534]: cause this: https://github.com/pingcap/tidb/pull/50282/files#diff-2c33db76e1a37e0c61c9a3af56d0b96174e83cbf622672e9330e013cf9f10d66R1458

we could change it to 5, but it didn't change the correctness of the ut

**Review by lance6716 — APPROVED** [review]

File: br/pkg/lightning/backend/local/local.go (hunk 1 above)
Comment (mittalrishabh) [inline br/pkg/lightning/backend/local/local.go:1534]: if error is because of suspended, should we try to add more backoff time as we know that it can take some time. It will prevent unnecessary re writes.

Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1534]: this pr only tries to fix the bug

for the Pause Ingest introduced by EBS BR, we need to handle it in whole later

**Comment by D3Hunter** [comment]
ci pass https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Frelease-6.5%2Fpull_br_integration_test/detail/pull_br_integration_test/8/pipeline

**Review by Benjamin2037 — APPROVED** [review]
LGTM
