### PR TITLE
types: fix the incorrect behavior of "%y"/"%Y" for STR_TO_DATE()

### LINKED ISSUE #8465: format error: select str_to_date('18/10/22','%y/%m/%d') from dual
select str_to_date('18/10/22','%y/%m/%d') from dual 
return null

### PR DESCRIPTION
**Pull request by FateTHarlaown**
### What problem does this PR solve? 
fix #8465

### What is changed and how it works?
change the implemention of how "%Y" and "%y" be dealt in built-in function str_to_date()
for "%y", it can deal with 1 or 2 digits.
for "%Y", it can deal with 1 to 4 digits.

### Check List 

Tests 
 Unit test
integration test

Code changes

Side effects

Related changes

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8517)

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
@FateTHarlaown Hi, thanks for your contribution
Please add some integration tests for this commit.

**Comment by FateTHarlaown** [comment]
I updated the branch and can't  pass the  test case TestModifyColumnRollBack  in ddl/db_test.go , I feel very confused about this........   is the builtint function str_to_date() related with ddl?:(
@XuHuaiyu

**Comment by XuHuaiyu** [comment]
@ciscoxll PTAL

**Comment by ciscoxll** [comment]
@FateTHarlaown Please update branch.

File: executor/executor_test.go [hunk 1]
```diff
@@ -3360,3 +3360,13 @@ func (s *testSuite) TestDoSubquery(c *C) {
 	c.Assert(err, IsNil, Commentf("err %v", err))
 	c.Assert(r, IsNil, Commentf("result of Do not empty"))
 }
+
+func (s *testSuite) TestStrToDateBuiltin(c *C) {
```
Comment (XuHuaiyu) [inline executor/executor_test.go]: Please add some invalid cases, like:
`select str_to_date('69001010','%Y0%m0%d') from dual; `
`select  str_to_date('001001/10','%Y0%m/%d') from dual;`

Comment (FateTHarlaown) [reply executor/executor_test.go]: the warning message in TiDB is different from mysql. for example, the sql
`select str_to_date('00000/10/22','%Y/%m/%d') from dual;`

in mysql 
```
mysql> select str_to_date('00000/10/22','%Y/%m/%d') from dual;
+---------------------------------------+
| str_to_date('00000/10/22','%Y/%m/%d') |
+---------------------------------------+
| NULL                                  |
+---------------------------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> show warnings;
+---------+------+------------------------------------------------------------------+
| Level   | Code | Message                                                          |
+---------+------+------------------------------------------------------------------+
| Warning | 1411 | Incorrect datetime value: '00000/10/22' for function str_to_date |
| Warning | 1411 | Incorrect datetime value: '00000/10/22' for function str_to_date |
+---------+------+------------------------------------------------------------------+
```
in TiDB
```
mysql root@localhost:(none)> select str_to_date('00000/10/22','%Y/%m/%d') from dual
+-----------------------------------------+
|   str_to_date('00000/10/22','%Y/%m/%d') |
|-----------------------------------------|
|                                  <null> |
+-----------------------------------------+
1 row in set
Time: 0.002s
mysql root@localhost:(none)> SHOW warnings;
+---------+--------+-------------------------------------------------+
| Level   |   Code | Message                                         |
|---------+--------+-------------------------------------------------|
| Warning |   1292 | Incorrect datetime value: '0000-00-00 00:00:00' |
+---------+--------+-------------------------------------------------+
```

should I just use the TiDB version to write some integration test cases ?

**Comment by FateTHarlaown** [comment]
have done, PTAL
@ciscoxll

File: executor/executor_test.go (hunk 1 above)
Comment (XuHuaiyu) [reply executor/executor_test.go]: @FateTHarlaown Sorry for this late reply, I did not notice this comment.
What I mentioned here means that we also need some integration tests for **other separators** except `/`.

File: executor/executor_test.go [hunk 2]
```diff
@@ -3488,3 +3488,23 @@ func (s *testSuite3) TearDownTest(c *C) {
...
+	tk.MustQuery(`select str_to_date('69/10/22','%Y/%m/%d') from dual`).Check(testkit.Rows("2069-10-22"))
+	tk.MustQuery(`select str_to_date('70/10/22','%Y/%m/%d') from dual`).Check(testkit.Rows("1970-10-22"))
+	tk.MustQuery(`select str_to_date('018/10/22','%Y/%m/%d') from dual`).Check(testkit.Rows("0018-10-22"))
+	tk.MustQuery(`select str_to_date('2018/10/22','%Y/%m/%d') from dual`).Check(testkit.Rows("2018-10-22"))
+	tk.MustQuery(`select str_to_date('018/10/22','%y/%m/%d') from dual`).Check(testkit.Rows("<nil>"))
+	tk.MustQuery(`select str_to_date('18/10/22','%y0/%m/%d') from dual`).Check(testkit.Rows("<nil>"))
+	tk.MustQuery(`select str_to_date('18/10/22','%Y0/%m/%d') from dual`).Check(testkit.Rows("<nil>"))
+	tk.MustQuery(`select str_to_date('18a/10/22','%y/%m/%d') from dual`).Check(testkit.Rows("<nil>"))
+	tk.MustQuery(`select str_to_date('18a/10/22','%Y/%m/%d') from dual`).Check(testkit.Rows("<nil>"))
+	tk.MustQuery(`select str_to_date('20188/10/22','%Y/%m/%d') from dual`).Check(testkit.Rows("<nil>"))
```
Comment (XuHuaiyu) [inline executor/executor_test.go]: We'd better add some test case for some abnormal separators like digit.

File: types/time.go [hunk 3]
```diff
@@ -2432,12 +2432,29 @@ func microSeconds(t *MysqlTime, input string, ctx map[string]int) (string, bool)
...
+	return yearNumericNDigits(t, input, ctx, 4)
+}
+
+func yearNumericTwoDigits(t *MysqlTime, input string, ctx map[string]int) (string, bool) {
+	return yearNumericNDigits(t, input, ctx, 2)
+}
+
+func yearNumericNDigits(t *MysqlTime, input string, ctx map[string]int, n int) (string, bool) {
+	var l int
+	for l = 1; l < n+1; l++ {
```
Comment (qw4990) [inline types/time.go]: Variable `l` and this loop is unnecessary?
I think just parse `n` bytes is briefer and better to understand.

Comment (FateTHarlaown) [reply types/time.go]: The n is the max number of digits,  year like '218/10/22' is also right in MySQL, it can be 2 to 4 digits. If we just pasrse n bytes, the year must have exactly n digits. SQL like `select str_to_date('18/10/22','%Y/%m/%d') from dual` or `select str_to_date('218/10/22','%Y/%m/%d') from dual` will return null.

File: executor/executor_test.go (hunk 2 above)
Comment (FateTHarlaown) [reply executor/executor_test.go]: have added more tests use other separators  :)

File: types/time.go [hunk 4]
```diff
@@ -2432,12 +2432,29 @@ func microSeconds(t *MysqlTime, input string, ctx map[string]int) (string, bool)
...
+		if _, succ := parseDigits(input, l); !succ {
+			break
+		}
+	}
+	v, succ := parseDigits(input, l-1)
```
Comment (zz-jason) [inline types/time.go]: Reaching here, I think `parseDigits(input, l-1)` is guaranteed to be `true`?

File: types/time.go [hunk 5]
```diff
@@ -2432,12 +2432,29 @@ func microSeconds(t *MysqlTime, input string, ctx map[string]int) (string, bool)
...
-	v, succ := parseDigits(input, 4)
+	return yearNumericNDigits(t, input, ctx, 4)
+}
+
+func yearNumericTwoDigits(t *MysqlTime, input string, ctx map[string]int) (string, bool) {
+	return yearNumericNDigits(t, input, ctx, 2)
+}
+
+func yearNumericNDigits(t *MysqlTime, input string, ctx map[string]int, n int) (string, bool) {
+	var l int
```
Comment (zz-jason) [inline types/time.go]: how about:
```go
effectiveCount, effectiveValue := 0, true
for effectiveCount+1 <= n {
	// try to parse the next digit.
	value, succeed := parseDigits(input, effectiveCount+1)
	if !succeed {
		break
	}
	effectiveCount++
	effectiveValue = value
}
```

Thus we don't need to parse it again in https://github.com/pingcap/tidb/pull/8517/files#diff-3d97ef53b300d76ad11d0d73a7b7a7ebR2449

File: types/time.go (hunk 4 above)
Comment (FateTHarlaown) [reply types/time.go]: I think if the first byte of the year str is not a digit, like
```
select str_to_date('a69/10/22','%Y/%m/%d')
```
 `parseDigits(input, l-1)`  will not success...It become  `parseDigits(input, 0)`

File: types/time.go (hunk 5 above)
Comment (FateTHarlaown) [reply types/time.go]: If parseDigits return false when pasrse first digit, we should return false....
maybe we should add another `if` after this code to decide if we shoud return according to effectiveCount ?

like 
```
effectiveCount, effectiveValue := 0, true
for effectiveCount+1 <= n {
	// try to parse the next digit.
	value, succeed := parseDigits(input, effectiveCount+1)
	if !succeed {
		break
	}
	effectiveCount++
	effectiveValue = value
}
if (effectiveCount == 0) {
    return input, false
}
```

Comment (FateTHarlaown) [reply types/time.go]: have done:)

**Comment by zz-jason** [comment]
@FateTHarlaown @qw4990 There are some unresolved comments in reviewable, could you take a look and resolve them so we can get this PR merged?
