### PR TITLE
table, sessionctx: fix bug where mlog consumes reserved row IDs from base table

### LINKED ISSUE #66245: assertion failed with  assertion: NotExist when updating a masterialized table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int);
create materialized view log on t (a);
insert into t values (1);
select _tidb_rowid, a from t;
select _tidb_rowid, a, `_MLOG$_DML_TYPE`, `_MLOG$_OLD_NEW` from `$mlog$t`;
update t set a = a+1 where a = 1;
insert into t values (2), (3);
```

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

an error reported:

```
> insert into t values (2), (3);
(HY000): assertion failed: key: 7480000000000086535f728000000000000003, assertion: NotExist, start_ts: 464245659724677120, existing start ts: 464245659724414977, existing commit ts: 464245659724414978 
```

### 4. What is your TiDB version? (Required)

feature/release-8.5-materialized-view

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #66245

Problem Summary:
When a statement reserves `_tidb_rowid` values for the base table, the mlog table write in the same statement can incorrectly consume those reserved IDs. This causes the base table to lose reserved IDs and breaks expected rowid continuity/order in mixed UPDATE/INSERT flows.

### What changed and how does it work?
- Added `ReservedRowIDAlloc.Current()` to snapshot the current reserved range.
- In `mlogTable.writeMLogRow`, temporarily clear the statement-level reserved rowid allocator before writing to the mlog table, then restore it with `defer` after the mlog insert.
- Added unit test coverage for `ReservedRowIDAlloc.Current()`.
- Added integration test for issue #66245 to verify mlog writes no longer consume base table reserved row IDs.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Test commands:
- `go test ./pkg/sessionctx/stmtctx -run TestReservedRowIDAlloc --tags=intest`
- `tests/integrationtest/run-tests.sh -r executor/mview_log_dml`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug where materialized view log writes could consume reserved `_tidb_rowid` values from the base table within the same statement.
```

### CODE REVIEW

**Review by wfxr — APPROVED** [review]
LGTM

File: pkg/table/tables/mview_log.go [hunk 1]
```diff
@@ -354,6 +357,15 @@ func (t *mlogTable) writeMLogRow(
 	}
 	mlogRow = append(mlogRow, types.NewStringDatum(string(dmlType)), types.NewIntDatum(oldNew))
 
+	if alloc, ok := ctx.GetReservedRowIDAlloc(); ok {
+		// `ReservedRowIDAlloc` does not support multiple tables.
+		// We should reset the allocator to avoid reading the reserved IDs for base table by mistake,
+		// and after writing the mlog row, we restore the allocator for the base table.
+		// TODO: optimize this by also reserving IDs for mlog table in the statement execution phase.
```
Comment (cfzjywxk) [inline pkg/table/tables/mview_log.go:364]: Mixing usage of allocator introduces implicit depdencies and poses risk, we could write down some todos in the development plan.
