### PR TITLE
expression, types: fix decimal precision for SUM function

### LINKED ISSUE #19426: `select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t` returns wrong decimal
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` sql
create table t(a int primary key, b int);
insert into t values (1, 11), (4, 44), (2, 22), (3, 33);
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                   110 |
+-------------------------------------------------------+
1 row in set (0.01 sec)
```

### 2. What did you expect to see? (Required)

``` sql
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                 110.0 |
+-------------------------------------------------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)
``` sql
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                   110 |
+-------------------------------------------------------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #19426 

Problem Summary:

``` mysql
create table t(a int primary key, b int);
insert into t values (1, 11), (4, 44), (2, 22), (3, 33);
select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
```

returns

```
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                   110 |
+-------------------------------------------------------+
```

instead of 

```
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                 110.0 |
+-------------------------------------------------------+
```

### What is changed and how it works?

What's Changed:

- Preserve the length of fraction part in decimal result of `sum` function.

How it Works:

- add function `NewZeroDec` to produce zero decimal value of certain precision.
- initialize the accumulative result with certain precision in `AllocPartialResult` for `sum` function.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- fix decimal precision for SUM function

### CODE REVIEW

**Review by wshwsh12 — COMMENTED** [review]
Please resolve conflicts.

File: types/mydecimal.go [hunk 1]
```diff
@@ -2345,3 +2345,21 @@ func NewMaxOrMinDec(negative bool, prec, frac int) *MyDecimal {
...
+	str := make([]byte, prec+1)
+	for i := 0; i < len(str); i++ {
+		str[i] = '0'
+	}
+	if frac != UnspecifiedLength {
+		str[prec-frac] = '.'
+	}
+	dec := new(MyDecimal)
+	err := dec.FromString(str)
+	terror.Log(errors.Trace(err))
```
Comment (qw4990) [inline types/mydecimal.go:2363]: Please return this error instead of just printing it.

Comment (dyzsr) [reply types/mydecimal.go:2363]: Function `NewMaxOrMinDec` in this file is similar to this (just print the error). Also, functions that call `NewZeroDec` does not return error (`AllocPartialResult`). So I think it's better not to return an error.

**Review by qw4990 — COMMENTED** [review]
LGTM

File: executor/aggfuncs/func_sum.go [hunk 2]
```diff
@@ -341,9 +340,7 @@ func (e *sum4DistinctDecimal) UpdatePartialResult(sctx sessionctx.Context, rowsI
 		p.valSet.Insert(decStr)
 		memDelta += int64(len(decStr))
 		if p.isNull {
-			p.val = *input
 			p.isNull = false
-			continue
 		}
```
Comment (wshwsh12) [inline executor/aggfuncs/func_sum.go:344]: Set `p.isNull = false` directly? = =

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
LGTM
