### PR TITLE
lightning: Add source dir existence check for s3

### LINKED ISSUE #28031: lightning: DBaaS lightning import doesn't fail if source folder not exist
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
From DBaaS, start a import task, specify a S3 folder which doesn't exists.

### 2. What did you expect to see? (Required)
Appropriate error should be displayed to user to let user know import failed.

### 3. What did you see instead (Required)
Lightning doesn't report error for the import. And go through all the import steps: schema create, precheck, etc.

dbaas_not_exist_folder

dbaas_not_exist_folder_2

### 4. What is your TiDB version? (Required)
Lightning: [release-version=v5.2.0] [git-hash=05d2210647d6a1503a8d772477e43b14a024f609]

### LINKED ISSUE #30709: S3's `check-path` is not specific enough
Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

1. dump some SQL files into `s3://some-bucket/some-prefix/` on AWS S3.
2. create a role, give it the `s3:ListBucket` and `s3:GetObject` permission, conditioned with `s3:prefix`=`some-prefix/`.
3. run Lightning using that role

### 2. What did you expect to see?

successfully restored.

### 3. What did you see instead?

failed due to an unnecessary `HeadBucket` call:

```
tidb lightning encountered error:  create storage failed: Bucket some-bucket is not accessible: Forbidden: Forbidden
        status code: 403, request id: ..., host id: ...: [BR:ExternalStorage:ErrStorageInvalidConfig]invalid external storage config
```

### 4. What version of BR and TiDB/TiKV/PD are you using?

master

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #28031, close #30709

Problem Summary:

### What is changed and how it works?
- Add a `WalkDir` after build remote storage to check whether target directory contains at least one regular file. 
- Remove the deprecated `skip-check-path` parameter for br and lightning because the requirement privilege is too high.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the but that lightning doesn't report error if s3 storage path not exist.
```

### CODE REVIEW

File: br/pkg/storage/s3.go [hunk 1]
```diff
@@ -416,12 +416,18 @@ func (rs *S3Storage) DeleteFile(ctx context.Context, file string) error {
...
+	key := aws.String(rs.options.Prefix + file)
+	// empty path means check the bucket itself
+	if len(*key) == 0 || *key == "/" {
+		err = checkS3Bucket(rs.svc, rs.options)
+	} else {
+		input := &s3.HeadObjectInput{
+			Bucket: aws.String(rs.options.Bucket),
+			Key:    key,
+		}
+		_, err = rs.svc.HeadObjectWithContext(ctx, input)
```
[the remark this answers is not in the document]
Comment (glorv) [reply br/pkg/storage/s3.go]: Update the check logic by do a `WalkDir`. Because s3/gcs does not support check non-regular file like directory, I leave the `FileExist` method to only support check regular file as its original logic.

File: br/pkg/lightning/lightning.go [hunk 2]
```diff
@@ -296,6 +296,19 @@ func (l *Lightning) run(taskCtx context.Context, taskCfg *config.Config, g glue.
...
+	walkErr := s.WalkDir(ctx, &storage.WalkOption{ListCount: 1}, func(string, int64) error {
+		// return an error when meet the first regular file to break the walk loop
+		return expectedErr
+	})
+	if !errors.ErrorEqual(walkErr, expectedErr) {
+		if walkErr == nil {
+			return errors.Errorf("data-source-dir '%s' not exist or contains no files", taskCfg.Mydumper.SourceDir)
+		}
+		return errors.Annotatef(walkErr, "visit data-source-dir '%s' failed: ", taskCfg.Mydumper.SourceDir)
+	}
```
Comment (gozssky) [inline br/pkg/lightning/lightning.go:310]:
```suggestion
	if !errors.ErrorEqual(walkErr, expectedErr) {
		if walkErr == nil {
			return errors.Errorf("data-source-dir '%s' doesn't exist or contains no files", taskCfg.Mydumper.SourceDir)
		}
		return errors.Annotatef(walkErr, "visit data-source-dir '%s' failed", taskCfg.Mydumper.SourceDir)
	}
```

**Review by gozssky — COMMENTED** [review]
rest LGTM

File: br/pkg/lightning/lightning.go [hunk 3]
```diff
@@ -296,6 +296,19 @@ func (l *Lightning) run(taskCtx context.Context, taskCfg *config.Config, g glue.
...
+	expectedErr := errors.New("Stop Iter")
+	walkErr := s.WalkDir(ctx, &storage.WalkOption{ListCount: 1}, func(string, int64) error {
+		// return an error when meet the first regular file to break the walk loop
+		return expectedErr
+	})
+	if !errors.ErrorEqual(walkErr, expectedErr) {
+		if walkErr == nil {
+			return errors.Errorf("data-source-dir '%s' doesn't exist or contains no files", taskCfg.Mydumper.SourceDir)
+		}
+		return errors.Annotatef(walkErr, "visit data-source-dir '%s' failed: ", taskCfg.Mydumper.SourceDir)
```
Comment (gozssky) [inline br/pkg/lightning/lightning.go:309]: Seems forget this line?

File: br/pkg/lightning/lightning.go (hunk 2 above)
Comment (glorv) [reply br/pkg/lightning/lightning.go]: 😂 done

File: br/pkg/lightning/lightning.go (hunk 3 above)
Comment (glorv) [reply br/pkg/lightning/lightning.go]: done😂

**Review by gozssky — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
LGTM
