### PR TITLE
store/kv: fix panic for EOF-stream & add recover to copIterateWorker

### LINKED ISSUE #8100: TiClient Region Error OPS on a new setup of TiDB 2.0.8
## Question
I just now set up an empty cluster of TiDB and ran a few create table commands. I started receiving TiClient Errors.
screen shot 2018-10-29 at 7 20 38 pm

Next, I ran `bin/tikv-ctl --db /data/tikv/db bad-regions`  command and received below response
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "IO error: While lock file: /data/tikv/db/LOCK: Resource temporarily unavailable"', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:475
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   4: rust_begin_unwind
             at libstd/panicking.rs:325
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   7: tikv_ctl::new_debug_executor
             at /checkout/src/libcore/result.rs:782
             at src/bin/tikv-ctl.rs:94
   8: tikv_ctl::main
             at src/bin/tikv-ctl.rs:1247
   9: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  10: main
  11: __libc_start_main
  12: <unknown>
```

`enable-streaming` is set to `true` and it does not work as expected. TiDB crashes if streaming is enabled. I receive below error

```
/go/src/github.com/pingcap/tidb/parser/yy_parser.go:106:
Oct 29 19:07:04 tidb-1 docker[17366]: /go/src/github.com/pingcap/tidb/session/session.go:819:
Oct 29 19:07:04 tidb-1 docker[17366]: /go/src/github.com/pingcap/tidb/server/conn.go:859:
Oct 29 19:07:13 tidb-1 docker[17366]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 29 19:07:13 tidb-1 docker[17366]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xd0415e]
Oct 29 19:07:13 tidb-1 docker[17366]: goroutine 488 [running]:
Oct 29 19:07:13 tidb-1 docker[17366]: github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).logTimeCopTask(0xc422dd2330, 0x14bc3d99, 0xc421037740, 0xc422fd87e0, 0xc
Oct 29 19:07:13 tidb-1 docker[17366]:         /go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:665 +0x56e
Oct 29 19:07:13 tidb-1 docker[17366]: github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTaskOnce(0xc422dd2330, 0xc422fd87e0, 0xc421037740, 0xc422fd8660, 0
Oct 29 19:07:13 tidb-1 docker[17366]:         /go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:636 +0x584
Oct 29 19:07:13 tidb-1 docker[17366]: github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTask(0xc422dd2330, 0xc422fd87e0, 0xc421037740, 0xc422fd8660)
Oct 29 19:07:13 tidb-1 docker[17366]:         /go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:588 +0xb7
Oct 29 19:07:13 tidb-1 docker[17366]: github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).run(0xc422dd2330, 0x7f2bc28af528, 0xc422dd2090)
Oct 29 19:07:13 tidb-1 docker[17366]:         /go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:443 +0x1d4
Oct 29 19:07:13 tidb-1 docker[17366]: github.com/pingcap/tidb/store/tikv.(*copIterator).open.func1()
Oct 29 19:07:13 tidb-1 docker[17366]:         /go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:471 +0x3c
Oct 29 19:07:13 tidb-1 docker[17366]: github.com/pingcap/tidb/util/goroutine_pool.(*goroutine).workLoop(0xc42069c7e0, 0xc4201c6dc0)
Oct 29 19:07:13 tidb-1 docker[17366]:         /go/src/github.com/pingcap/tidb/util/goroutine_pool/gp.go:115 +0x171
Oct 29 19:07:13 tidb-1 docker[17366]: created by github.com/pingcap/tidb/util/goroutine_pool.(*Pool).alloc
Oct 29 19:07:13 tidb-1 docker[17366]:         /go/src/github.com/pingcap/tidb/util/goroutine_pool/gp.go:90 +0x97
```

Before asking a question, make sure you have:

- Searched existing Stack Overflow questions.
- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tidb/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiDB Readme](https://github.com/pingcap/tidb)
  - [TiDB Doc](https://github.com/pingcap/docs)

### PR DESCRIPTION
**Pull request by lysu**
#### 1. EOF-stream panic

fixes #8100 's TiDB panic question, that can be reproduce by

- enable stream
- make a smaller `minLogCopTaskTime` in TiDB
- start TiDB-Server and see panic

#### 1. EOF-stream panic

https://github.com/pingcap/tidb/blob/32b1dbd8d59fbd725ec3f2971da2323cae0bf885/store/tikv/client.go#L281

```
	// Read the first streaming response to get CopStreamResponse.
	// This can make error handling much easier, because SendReq() retry on
	// region error automatically.
	var first *coprocessor.Response
	first, err = copStream.Recv()
	if err != nil {
		if errors.Cause(err) != io.EOF {
			return nil, errors.Trace(err)
		}
		log.Debug("copstream returns nothing for the request.")
	}
	copStream.Response = first
```

kv in stream mode may return EOF and make response be `nil` and log logic doesn't take about that...

so fix just add nil check in log logic

#### 2. panic make TiDB exit

add recover to copIterateWorker run, alway close channel and send error response if panic occured.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

```
- enable stream
- make a smaller `minLogCopTaskTime` in TiDB
- start TiDB-Server and doesn't saw panic in log and TiDB doesn't exit.
```

Code changes

- add nil-check
- add recover

Side effects

 - add a annoy function call and defer

Related changes

 - Need to cherry-pick to the release branch

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8297)

### CODE REVIEW

File: store/tikv/coprocessor.go [hunk 1]
```diff
@@ -416,22 +417,33 @@ const minLogCopTaskTime = 300 * time.Millisecond
 func (worker *copIteratorWorker) run(ctx context.Context) {
 	defer worker.wg.Done()
 	for task := range worker.taskCh {
-		respCh := worker.respChan
-		if respCh == nil {
-			respCh = task.respChan
-		}
+		func() {
+			defer func(t *copTask) {
```
Comment (tiancaiamao) [inline store/tikv/coprocessor.go]: don't defer here.
defer in the handle function...
The dispatch loop should be as simple as possible.

File: store/tikv/coprocessor.go [hunk 2]
```diff
@@ -639,7 +651,7 @@ func (worker *copIteratorWorker) logTimeCopTask(costTime time.Duration, task *co
 	var detail *kvrpcpb.ExecDetails
 	if resp.Cop != nil {
 		detail = resp.Cop.ExecDetails
-	} else if resp.CopStream != nil {
+	} else if resp.CopStream != nil && resp.CopStream.Response != nil {
```
Comment (tiancaiamao) [inline store/tikv/coprocessor.go]: Maybe a better fix is make CopStream.Response always not nil, and report error when it's used ?
