### PR TITLE
lightning: add more retryable error type (#31484)

### LINKED ISSUE #31376: Lightning import error: init table allocator base failed: commit transaction failed: Error 9007: Write conflict
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Jenkins CI fails when running case: lightning_duplicate_detection

### 2. What did you expect to see? (Required)
Case passed

### 3. What did you see instead (Required)
Case failed due to error "Error: restore table `dup_detect`.`tb` failed: init table allocator base failed: commit transaction failed: Error 9007: Write conflict, txnStartTS=430280826485735492, conflictStartTS=430280826485735498, conflictCommitTS=0, key={tableID=137, handle=4} primary=[]byte(nil) [try again later]"
For details, refer to: https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/9376/pipeline/103/

```
[2022-01-05T13:58:09.736Z] + echo '[Wed Jan  5 21:58:09 CST 2022] <<<<<< RUNNING TEST FOR: tests/lightning_duplicate_detection --backend' local --sorted-kv-dir /tmp/backup_restore_test/lightning_duplicate_detection.sorted1 --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-duplicate-detection1.log --config 'tests/lightning_duplicate_detection/config1.toml >>>>>>'

[2022-01-05T13:58:09.736Z] + echo '[Wed Jan  5 21:58:09 CST 2022] <<<<<< RUNNING TEST FOR: tests/lightning_duplicate_detection --backend' local --sorted-kv-dir /tmp/backup_restore_test/lightning_duplicate_detection.sorted2 --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-duplicate-detection2.log --config 'tests/lightning_duplicate_detection/config2.toml >>>>>>'

[2022-01-05T13:58:09.737Z] + bin/tidb-lightning.test -test.coverprofile=/tmp/backup_restore_test/cov.lightning_duplicate_detection.1526.out DEVEL --ca /tmp/backup_restore_test/certs/ca.pem --cert /tmp/backup_restore_test/certs/lightning.pem --key /tmp/backup_restore_test/certs/lightning.key --log-file /tmp/backup_restore_test/lightning.log --tidb-port 4000 --pd-urls 127.0.0.1:2379 --config tests/lightning_duplicate_detection/config.toml -d tests/lightning_duplicate_detection/data --importer 127.0.0.1:8808 --sorted-kv-dir /tmp/backup_restore_test/lightning_duplicate_detection.sorted --enable-checkpoint=0 --check-requirements=0 --backend local --sorted-kv-dir /tmp/backup_restore_test/lightning_duplicate_detection.sorted1 --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-duplicate-detection1.log --config tests/lightning_duplicate_detection/config1.toml

[2022-01-05T13:58:09.737Z] + bin/tidb-lightning.test -test.coverprofile=/tmp/backup_restore_test/cov.lightning_duplicate_detection.1527.out DEVEL --ca /tmp/backup_restore_test/certs/ca.pem --cert /tmp/backup_restore_test/certs/lightning.pem --key /tmp/backup_restore_test/certs/lightning.key --log-file /tmp/backup_restore_test/lightning.log --tidb-port 4000 --pd-urls 127.0.0.1:2379 --config tests/lightning_duplicate_detection/config.toml -d tests/lightning_duplicate_detection/data --importer 127.0.0.1:8808 --sorted-kv-dir /tmp/backup_restore_test/lightning_duplicate_detection.sorted --enable-checkpoint=0 --check-requirements=0 --backend local --sorted-kv-dir /tmp/backup_restore_test/lightning_duplicate_detection.sorted2 --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-duplicate-detection2.log --config tests/lightning_duplicate_detection/config2.toml

[2022-01-05T13:58:09.737Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-duplicate-detection2.log

[2022-01-05T13:58:09.737Z] 

[2022-01-05T13:58:09.737Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-duplicate-detection1.log

[2022-01-05T13:58:09.737Z] 

[2022-01-05T13:58:16.303Z] 

[2022-01-05T13:58:16.303Z] Import Data Error Summary: 

[2022-01-05T13:58:16.303Z] +---+---------------------+-------------+------------------------------------- ~

[2022-01-05T13:58:16.303Z] | # | ERROR TYPE          | ERROR COUNT | ERROR DATA TABLE                     ~

[2022-01-05T13:58:16.303Z] +---+---------------------+-------------+------------------------------------- ~

[2022-01-05T13:58:16.303Z] | 1 | Unique Key Conflict |          81 | `lightning_task_info`.`conflict_erro ~

[2022-01-05T13:58:16.303Z] +---+---------------------+-------------+------------------------------------- ~

[2022-01-05T13:58:16.303Z] 

[2022-01-05T13:58:16.303Z] Error: restore table `dup_detect`.`tb` failed: init table allocator base failed: commit transaction failed: Error 9007: Write conflict, txnStartTS=430280826485735492, conflictStartTS=430280826485735498, conflictCommitTS=0, key={tableID=137, handle=4} primary=[]byte(nil) [try again later]

[2022-01-05T13:58:16.303Z] tidb lightning encountered error:  restore table `dup_detect`.`tb` failed: init table allocator base failed: commit transaction failed: Error 9007: Write conflict, txnStartTS=430280826485735492, conflictStartTS=430280826485735498, conflictCommitTS=0, key={tableID=137, handle=4} primary=[]byte(nil) [try again later]

[2022-01-05T13:58:16.561Z] 

[2022-01-05T13:58:16.561Z] Import Data Error Summary: 

[2022-01-05T13:58:16.561Z] +---+---------------------+-------------+------------------------------------- ~

[2022-01-05T13:58:16.561Z] | # | ERROR TYPE          | ERROR COUNT | ERROR DATA TABLE                     ~

[2022-01-05T13:58:16.561Z] +---+---------------------+-------------+------------------------------------- ~

[2022-01-05T13:58:16.561Z] | 1 | Unique Key Conflict |         114 | `lightning_task_info`.`conflict_erro ~

[2022-01-05T13:58:16.561Z] +---+---------------------+-------------+------------------------------------- ~
```

### 4. What is your TiDB version? (Required)
["Welcome to TiDB-Lightning"] [release-version=v5.0.0-master] [git-hash=None] [git-branch=None] [go-version=go1.16.4]

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31484 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31506
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31506:release-5.3-0649ee84ac44
```

---

### What problem does this PR solve?

Issue Number: close #31376

Problem Summary:

### What is changed and how it works?
Reference: retry check implementation in tidb-tools: https://github.com/pingcap/tidb-tools/blob/b1def7746ec382a71a70b8958b1053202092f95c/pkg/dbutil/retry.go#L43

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: br/pkg/utils/retry_test.go [hunk 1]
```diff
@@ -28,6 +28,7 @@ func (s *utilSuite) TestIsRetryableError(c *C) {
 	c.Assert(IsRetryableError(&net.DNSError{IsTimeout: true}), IsTrue)
 
 	// MySQL Errors
+<<<<<<< HEAD
```
Comment (gozssky) [inline br/pkg/utils/retry_test.go:31]: merge conflicts

**Review by lichunzhu — APPROVED** [review]
