### PR TITLE
*: fix the flen type datetime for union/case-when/control-funcs

### LINKED ISSUE #29498: concat(ifnull(time(3)) returns different results from MySQL
## Bug Report
SET TIMESTAMP doesn't take effect. 

### 1. Minimal reproduce step (Required)
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (t3 TIME(3), d DATE);
INSERT INTO t1 VALUES ('00:00:00.567', '2002-01-01');
SELECT CONCAT(IFNULL(t3, d)) AS col1 FROM t1;
```
### 2. What did you expect to see? (Required)
```sql
+-------------------------+
| col1                    |
+-------------------------+
| 2019-03-11 00:00:00.567 |
+-------------------------+
```

### 3. What did you see instead (Required)
```sql
+----------------+
| col1           |
+----------------+
| 2021-11-04 00: |
+----------------+
```
### 4. What is your TiDB version? (Required)
```sql
+-------------------------+--------------------------------------------------------------------------+
| Variable_name           | Value                                                                    |
+-------------------------+--------------------------------------------------------------------------+
| innodb_version          | 5.6.25                                                                   |
| protocol_version        | 10                                                                       |
| tidb_analyze_version    | 2                                                                        |
| tidb_row_format_version | 2                                                                        |
| tls_version             | TLSv1,TLSv1.1,TLSv1.2                                                    |
| version                 | 5.7.25-TiDB-v5.2.2                                                       |
| version_comment         | TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible |
| version_compile_machine | x86_64                                                                   |
| version_compile_os      | osx10.8                                                                  |
+-------------------------+--------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by bestwoody**
### What problem does this PR solve?

Issue Number: close #29498

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
bugfix: concat(ifnull(time(3)) returns different results from MySQL
```
<https://github.com/pingcap/tidb/issues/29498>

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -9501,3 +9501,31 @@ func (s *testSerialSuite) TestIssue30289(c *C) {
...
+	tk.MustExec("INSERT INTO t29498_t1 VALUES ('00:00:00.567', '2002-01-01', '00:00:02');")
+	res := tk.MustQuery("SELECT CONCAT(IFNULL(t3, d)) AS col1 FROM t29498_t1;")
+	for _, row := range res.Rows() {
+		c.Assert(len(row), Equals, mysql.MaxDatetimeWidthNoFsp+3+1)
+		c.Assert(row[len(row)-12:], Equals, "00:00:00.567")
+	}
+	res = tk.MustQuery("SELECT IFNULL(t3, d) AS col1 FROM t29498_t1;")
+	for _, row := range res.Rows() {
+		c.Assert(len(row), Equals, mysql.MaxDatetimeWidthNoFsp+3+1)
+		c.Assert(row[len(row)-12:], Equals, "00:00:00.567")
```
Comment (XuHuaiyu) [inline executor/executor_test.go:9519]: res.Check(testkit.Rows("00:00:00.567"))

Comment (bestwoody) [reply executor/executor_test.go:9519]: not check the whole row，but the prefix. Because the prefix subtring is undefined when time convert datetime.

File: expression/builtin_control.go [hunk 2]
```diff
@@ -155,6 +155,12 @@ func InferType4ControlFuncs(ctx sessionctx.Context, funcName string, lexp, rexp
 		if resultFieldType.Tp == mysql.TypeEnum || resultFieldType.Tp == mysql.TypeSet {
 			resultFieldType.Tp = mysql.TypeVarchar
 		}
+	} else if resultFieldType.Tp == mysql.TypeDatetime {
+		maxDecimal := mathutil.Max(lhs.Decimal, rhs.Decimal)
+		resultFieldType.Flen = mysql.MaxDatetimeWidthNoFsp + mathutil.Max(lhs.Decimal, rhs.Decimal)
```
[the remark this answers is not in the document]
Comment (bestwoody) [reply expression/builtin_control.go:160]: 1. yes, resultFieldType is Datetime
2. ok
3. this place will be safer and avoid post-change-after-fix, so we can see other type checks here.

[the remark this answers is not in the document]
Comment (windtalker) [reply expression/builtin_control.go]: 1. I don't understand why `Datetime` type does not need to set `Decimal`, AFAIK, the decimal of type `Datetime` is 0, and the decimal of type `Datetime(3)` is 3. 
2. Other type checks check the `EvalType` here, not the field type, I think `types.AggFieldType` should guarantee that its result's flen and decimal is set correctly.

[the remark this answers is not in the document]
Comment (bestwoody) [reply expression/builtin_control.go]: > 1. I don't understand why `Datetime` type does not need to set `Decimal`, AFAIK, the decimal of type `Datetime` is 0, and the decimal of type `Datetime(3)` is 3.
> 2. Other type checks check the `EvalType` here, not the field type, I think `types.AggFieldType` should guarantee that its result's flen and decimal is set correctly.

Decimal is correct, the bug caused incorrent length.

File: expression/builtin_control.go [hunk 3]
```diff
@@ -155,6 +155,12 @@ func InferType4ControlFuncs(ctx sessionctx.Context, funcName string, lexp, rexp
 		if resultFieldType.Tp == mysql.TypeEnum || resultFieldType.Tp == mysql.TypeSet {
 			resultFieldType.Tp = mysql.TypeVarchar
 		}
+	} else if resultFieldType.Tp == mysql.TypeDatetime {
+		maxDecimal := mathutil.Max(lhs.Decimal, rhs.Decimal)
+		resultFieldType.Flen = mysql.MaxDatetimeWidthNoFsp + maxDecimal
+		if maxDecimal > 0 { //addiional '.' between time and fracs
```
Comment (XuHuaiyu) [inline expression/builtin_control.go:161]:
```suggestion
		if maxDecimal > 0 { // additional '.' between time and fracs
```

Comment (bestwoody) [reply expression/builtin_control.go]: ok

**Comment by bestwoody** [comment]
also solve cases of "case when" and "union"

File: types/field_type.go [hunk 4]
```diff
@@ -103,6 +103,19 @@ func AggFieldType(tps []*FieldType) *FieldType {
...
+func TryToFixFlenOfDatetime(resultTp *FieldType) bool {
+	if resultTp.Tp == mysql.TypeDatetime {
+		resultTp.Flen = mysql.MaxDatetimeWidthNoFsp
+		if resultTp.Decimal > 0 {
+			resultTp.Flen += resultTp.Decimal + 1
+		}
+		return true
+	} else {
+		return false
+	}
```
Comment (guo-shaoge) [inline types/field_type.go:116]: Looks like the returned bool value is useless.

**Review by guo-shaoge — COMMENTED** [review]
Looks like the returned bool value is useless.

File: types/field_type.go [hunk 5]
```diff
@@ -103,6 +103,19 @@ func AggFieldType(tps []*FieldType) *FieldType {
 	return &currType
 }
 
+// TryToFixFlenOfDatetime try to fix flen of Datetime for specific func or other field merge cases
+func TryToFixFlenOfDatetime(resultTp *FieldType) bool {
```
Comment (XuHuaiyu) [inline types/field_type.go:107]: Why do we need to return a bool value even if we do not check it ?

Comment (bestwoody) [reply types/field_type.go]: removed

File: types/field_type.go (hunk 4 above)
Comment (bestwoody) [reply types/field_type.go:113]: removed

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Comment by bestwoody** [comment]
> Looks like the returned bool value is useless.

removed

**Review by windtalker — APPROVED** [review]
LGTM

File: expression/typeinfer_test.go [hunk 6]
```diff
@@ -838,6 +840,8 @@ func (s *InferTypeSuite) createTestCase4ControlFuncs() []typeInferTestCase {
 		{"case when c_int_d > 1 then c_double_d else c_bchar end", mysql.TypeString, charset.CharsetUTF8MB4, mysql.BinaryFlag, 22, types.UnspecifiedLength},
 		{"case when c_int_d > 2 then c_double_d when c_int_d < 1 then c_decimal else c_double_d end", mysql.TypeDouble, charset.CharsetBin, mysql.BinaryFlag, 22, 3},
 		{"case when c_double_d > 2 then c_decimal else 1 end", mysql.TypeNewDecimal, charset.CharsetBin, mysql.BinaryFlag, 6, 3},
+		{"case when c_time is not null then c_time else c_date end", mysql.TypeDatetime, charset.CharsetUTF8MB4, mysql.BinaryFlag, mysql.MaxDatetimeWidthNoFsp + 3 + 1, 3},
+		{"case when c_time_d is not null then c_time_d else c_date end", mysql.TypeDatetime, charset.CharsetUTF8MB4, mysql.BinaryFlag, mysql.MaxDatetimeWidthNoFsp, 0},
```
Comment (xiongjiwei) [inline expression/typeinfer_test.go:844]: a question here, why it has `binaryFlag` with `utf8mb4` charset?
