### PR TITLE
ttl,partition: Stabilize test TestReorgPartExtensivePart

### LINKED ISSUE #51845: DATA RACE TestReorgPartExtensivePart
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c01e825198 by goroutine 36414:
  github.com/pingcap/tidb/pkg/table/tables.(*TableCommon).Meta()
      pkg/table/tables/tables.go:265 +0x3b
  github.com/pingcap/tidb/pkg/table/tables.(*partitionedTable).Meta()
      <autogenerated>:1 +0x17
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*TTLTimersSyncer).SyncTimers()
      pkg/ttl/ttlworker/timer_sync.go:189 +0x1859
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).onTimerTick()
      pkg/ttl/ttlworker/job_manager.go:305 +0x409
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).jobLoop()
      pkg/ttl/ttlworker/job_manager.go:204 +0x126d
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).jobLoop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).loop()
      pkg/ttl/ttlworker/worker.go:134 +0xbb
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).loop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:157 +0x86
Previous write at 0x00c01e825198 by goroutine 146784:
  github.com/pingcap/tidb/pkg/table/tables.SwapReorgPartFields()
      pkg/table/tables/testutil.go:30 +0x25e
  pkg/table/tables/test/partition/partition_test.checkDMLInAllStates.func1()
      pkg/table/tables/test/partition/partition_test.go:2639 +0x15fb
  pkg/table/tables/test/partition/partition_test.(*testCallback).OnJobRunBefore()
      pkg/table/tables/test/partition/partition_test.go:2087 +0x65
  github.com/pingcap/tidb/pkg/ddl.(*worker).HandleDDLJobTable()
      pkg/ddl/ddl_worker.go:926 +0x33a
  github.com/pingcap/tidb/pkg/ddl.(*ddl).delivery2Worker.func1()
      pkg/ddl/job_table.go:462 +0x805
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:157 +0x86
Goroutine 36414 (running) created at:
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run()
      pkg/util/wait_group_wrapper.go:155 +0xe4
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).Start()
      pkg/ttl/ttlworker/worker.go:71 +0x12e
  github.com/pingcap/tidb/pkg/domain.(*Domain).StartTTLJobManager()
      pkg/domain/domain.go:2937 +0x1c9
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3493 +0x1b51
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:147 +0x974
  github.com/pingcap/tidb/pkg/sessionctx/variable.glob..func202()
      pkg/sessionctx/variable/sysvar.go:1035 +0x58
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:365 +0x210
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:146 +0x904
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadSysVarCacheLoop()
      pkg/domain/domain.go:1730 +0x93
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3386 +0x844
  github.com/pingcap/tidb/pkg/domain.(*Domain).GetSessionCache()
      pkg/domain/sysvar_cache.go:62 +0x50
  github.com/pingcap/tidb/pkg/session.(*session).loadCommonGlobalVariablesIfNeeded()
      pkg/session/session.go:3754 +0x2ce
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      pkg/session/session.go:2107 +0x184
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal()
      pkg/session/session.go:1622 +0x3b9
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadPrivilegeLoop()
      pkg/domain/domain.go:1673 +0x108
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3379 +0x7e4
  github.com/pingcap/tidb/pkg/session.BootstrapSession()
      pkg/session/session.go:3286 +0xad
  github.com/pingcap/tidb/pkg/testkit.bootstrap()
      pkg/testkit/mockstore.go:290 +0x94
  github.com/pingcap/tidb/pkg/testkit.CreateMockStoreAndDomain()
      pkg/testkit/mockstore.go:263 +0xd5
  github.com/pingcap/tidb/pkg/testkit.CreateMockStore()
      pkg/testkit/mockstore.go:71 +0x3bd
  pkg/table/tables/test/partition/partition_test.TestReorgPartExtensivePart()
      pkg/table/tables/test/partition/partition_test.go:2434 +0x4c
  testing.tRunner()
      GOROOT/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1648 +0x44
Goroutine 146784 (running) created at:
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run()
      pkg/util/wait_group_wrapper.go:155 +0xe4
  github.com/pingcap/tidb/pkg/ddl.(*ddl).delivery2Worker()
      pkg/ddl/job_table.go:422 +0x1b3
  github.com/pingcap/tidb/pkg/ddl.(*ddl).loadDDLJobAndRun()
      pkg/ddl/job_table.go:378 +0x4ef
  github.com/pingcap/tidb/pkg/ddl.(*ddl).startDispatchLoop()
      pkg/ddl/job_table.go:313 +0xe55
  github.com/pingcap/tidb/pkg/ddl.(*ddl).startDispatchLoop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:157 +0x86
================== 
```

### PR DESCRIPTION
**Pull request by mjonss**
The tests makes direct changes to table.Meta, which is later read by TTL. Fixed by disable TTL and not trigger the TTL loop when disabled.

### What problem does this PR solve?

Issue Number: close #51845 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Ran this on both a linux and a macOs box without issues.
```bash
(cd pkg/table/tables/test/partition ; go test -v -tags intest -race -run TestReorgPartExtensivePart -failfast -count 1000 -timeout 90m)
```
- [ ] No need to test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/ttl/ttlworker/job_manager.go [hunk 1]
```diff
@@ -286,6 +286,9 @@ func (m *JobManager) jobLoop() error {
 }
 
 func (m *JobManager) onTimerTick(se session.Session, rt *ttlTimerRuntime, syncer *TTLTimersSyncer, now time.Time) {
+	if !variable.EnableTTLJob.Load() {
```
Comment (lcwangchao) [inline pkg/ttl/ttlworker/job_manager.go:289]: This line will make some logic changes. How about just stopping ttl manager in the tests? See:

https://github.com/pingcap/tidb/blob/6aef624c8d4fc6e0301c4ef2f527f3b8a056edd7/pkg/ttl/ttlworker/job_manager_integration_test.go#L823-L828

**Review by tangenta — APPROVED** [review]
