### PR TITLE
session: make tidb_replica_read work correctly

### LINKED ISSUE #20392: sessionvar `tidb_replica_read` doesn't work as expected
### 1. Minimal reproduce step (Required)
1. set the session variable `tidb_replica_read` to `leader-and-follower`
2. run some queries

### 2. What did you expect to see? (Required)
Coprocessor (or point get) tasks should be sent to both leader and follower replicas

### 3. What did you see instead (Required)
Tasks are only sent to follower replicas

### 4. What is your TiDB version? (Required)
master branch

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

Close #20392 .

### What problem does this PR solve?

tidb_replica_read session variable can't work correctly in some situations:
* Value `leader-and-follower` makes same effect as `follower`, which is not expected

### What is changed and how it works?

* Use correct `ReplicaReadType` when get rpc context

### Check List 

Tests 

- Unit test

Side effects

### Release note 
* make session var tidb_replica_read work correctly

### CODE REVIEW

File: store/tikv/region_request.go [hunk 1]
```diff
@@ -250,12 +250,8 @@ func (s *RegionRequestSender) SendReqCtx(
...
 	})
 
-	var replicaRead kv.ReplicaReadType
-	if req.ReplicaRead {
-		replicaRead = kv.ReplicaReadFollower
-	} else {
-		replicaRead = kv.ReplicaReadLeader
-	}
+	var replicaRead kv.ReplicaReadType = req.ReplicaReadType
+
```
Comment (lysu) [inline store/tikv/region_request.go:254]: can simplify this by change L266 to

```
rpcCtx, err = s.regionCache.GetTiKVRPCContext(bo, regionID, req.ReplicaReadType, seed)
```

File: store/tikv/batch_coprocessor.go [hunk 2]
```diff
@@ -343,7 +343,7 @@ func (b *batchCopIterator) handleTaskOnce(ctx context.Context, bo *Backoffer, ta
 		Regions:   regionInfos,
 	}
 
-	req := tikvrpc.NewRequest(task.cmdType, &copReq, kvrpcpb.Context{
+	req := tikvrpc.NewReplicaReadRequest(task.cmdType, &copReq, b.req.ReplicaRead, &b.replicaReadSeed, kvrpcpb.Context{
```
Comment (lysu) [inline store/tikv/batch_coprocessor.go:346]: it seems only tiflash use batchCop

**Review by lysu — COMMENTED** [review]
rest LGTM

maybe better help fire a bugfix issue, our QA will test based on github issue

**Review by zz-jason — COMMENTED** [review]
could you add some tests?

**Comment by lysu** [comment]
LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
