### PR TITLE
ddl: check local file existence before resume checkpoint

### LINKED ISSUE #53009: fast reorg checkpoint has wrong prerequisite
If the checkpoint record shows the it is generated by current node

https://github.com/pingcap/tidb/blob/c24dca58f5ee68941a656ac898136eaf63070703/pkg/ddl/ingest/checkpoint.go#L307-L308
 
we skip the data whose key is smaller that "local storage key watermark" and assume the data is already stay in local storage. 

https://github.com/pingcap/tidb/blob/c24dca58f5ee68941a656ac898136eaf63070703/pkg/ddl/ingest/checkpoint.go#L128-L137

However this is not reliable, especially we are using `/tmp` folder to store the data https://docs.pingcap.com/tidb/stable/command-line-flags-for-tidb-configuration#--temp-dir. If the node restarts in many OS `/tmp` folder will be cleaned.

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #53009

Problem Summary:

### What changed and how does it work?

- use word "flushed"/"imported" to replace "local"/"global" to unify the terminology with lightning engine
- rename some methods
- remove `FlushModeForceLocalAndCheckDiskQuota` because it's not used
- use `ctx` to detect the closing of `CheckpointManager` and let other goroutine communications check the context
- add a tagged logger to `CheckpointManager`
- remove `updating` field because only one goroutine calls `updateCheckpoint`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ingest/checkpoint.go [hunk 1]
```diff
@@ -389,24 +416,24 @@ func (s *CheckpointManager) updateCheckpointLoop() {
...
 			err := s.updateCheckpoint()
 			if err != nil {
-				logutil.DDLIngestLogger().Error("update checkpoint failed", zap.Error(err))
+				s.logger.Error("update checkpoint failed", zap.Error(err))
 			}
-			wg.Done()
+			close(finishCh)
 		case <-ticker.C:
 			s.mu.Lock()
-			if !s.dirty || s.updating {
```
Comment (tangenta) [inline pkg/ddl/ingest/checkpoint.go:400]: If this is removed, is it possible to update checkpoint to a smaller value? For example,

1. g1 invokes updateCheckpoint, current checkpoint is 1.
2. g2 invokes updateCheckpoint, current checkpoint is 2.
3. g2 updates checkpoint 2 to table.
4. g1 updates checkpoint 1 to table.

Comment (lance6716) [reply pkg/ddl/ingest/checkpoint.go:400]: I see `updateCheckpoint` is only called by one goroutine which is `updateCheckpointLoop`

**Review by tangenta — APPROVED** [review]

File: pkg/ddl/ingest/checkpoint.go [hunk 2]
```diff
@@ -34,52 +34,57 @@ import (
...
+	startKeyFlushed kv.Key
+	endKeyFlushed   kv.Key
 
 	// Persisted to the storage.
-	minKeySyncLocal  kv.Key
-	minKeySyncGlobal kv.Key
-	localCnt         int
-	globalCnt        int
+	minKeyFlushed  kv.Key
+	minKeyImported kv.Key
```
Comment (D3Hunter) [inline pkg/ddl/ingest/checkpoint.go:68]: shouldn't we call it maxKeyImported, it means all keys < it are imported

**Review by D3Hunter — APPROVED** [review]
rest lgtm

File: pkg/ddl/ingest/checkpoint.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/ingest/checkpoint.go:68]: ChatGPT still prefer the minXXX

---

You
How to name a variable which means "all keys less than it are flushed, but the keys larger than it can be flushed or not flushed". And it's calculated from the minimum value of some concurrency worker's progress.

ChatGPT
You might consider naming the variable something descriptive yet succinct, like "minFlushedKey" or "flushThreshold". This would indicate that it represents the minimum key value up to which all keys are flushed, but keys larger than it might or might not be flushed depending on their status. Alternatively, you could name it "minFlushedProgressKey" to be more explicit about its relationship to progress.

Here's a breakdown of each potential name:

minFlushedKey: This name clearly indicates that it represents the minimum key value that has been flushed. It suggests that any keys smaller than this value are flushed, while those larger than it may or may not be flushed.
flushThreshold: This name implies that it's a point or level that determines when flushing occurs. It's like a threshold that, once reached, triggers the flushing of keys. "FlushThreshold" conveys that keys below this threshold are flushed, while those above it may or may not be.
minFlushedProgressKey: This name explicitly links the variable to progress and flushing. It suggests that it represents the minimum key based on the progress made, and keys less than or equal to this value are considered flushed.
Choose the name that best fits the context and naming conventions of your project. The most important thing is that the name is clear and understandable to anyone reading your code.

Comment (D3Hunter) [reply pkg/ddl/ingest/checkpoint.go]: i don't think `minFlushedKey` suggests that any keys smaller than this value are flushed, it only states that it's the min key that have flushed and any key before or after it may or may not flushed

> And it's calculated from the minimum value of some concurrency worker's progress.

from this description, we can only got a name like min key of on-going task

Comment (lance6716) [reply pkg/ddl/ingest/checkpoint.go]: How about rename it to `flushedKeyLowWatermark`? I can do it in https://github.com/pingcap/tidb/pull/52993

Comment (D3Hunter) [reply pkg/ddl/ingest/checkpoint.go]: lgtm
