### PR TITLE
planner: fix bug some cases index merge join hint doesn't work

### LINKED ISSUE #15484: inl_merge_join doesn't work
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

``` sql
CREATE TABLE `t` ( `a` bigint(20) NOT NULL, `b` tinyint(1) DEFAULT NULL, `c` datetime DEFAULT NULL, `d` int(10) unsigned DEFAULT NULL, `e` varchar(20) DEFAULT NULL, `f` double DEFAULT NULL, `g` decimal(30,5) DEFAULT NULL, `h` float DEFAULT NULL, `i` date DEFAULT NULL, `j` timestamp NULL DEFAULT NULL, PRIMARY KEY (`a`), UNIQUE KEY `b` (`b`), KEY `c` (`c`,`d`,`e`), KEY `f` (`f`), KEY `g` (`g`,`h`), KEY `g_2` (`g`), UNIQUE KEY `g_3` (`g`), KEY `i` (`i`) );

insert into t select 0, -128, "2020-01-02 12:00:0", 2020, "xxxxx", 2020, -9762.572100, 4265.963532, "2007-04-12 03:20:53.095679", "2003-11-18 15:45:00.182053";

insert into t select 1, -127, "2020-01-02 12:00:1", 2021, "xxxxx", 2021, -8048.946020, -3085.125561, "1959-05-26 11:27:27.574917", "2007-01-08 16:17:17.564787";

insert into t select 2, -126, "2020-01-02 12:00:2", 2022, "xxxxx", 2022, -1320.388700, -5713.948181, "1930-06-16 18:40:31.447895", "1980-04-26 09:58:01.770144";

analyze table t;

explain select /*+inl_merge_join(t2)*/ t1.a, t2.a from t t1 left join t t2 use index(g_2) on t1.g=t2.g;

explain select /*+inl_merge_join(t2)*/ t1.a, t2.a from t t1 left join t t2 use index(g_2) on t1.g=t2.g order by t1.a;
```

### 2. What did you expect to see?

2 SQLs both use index merge join.

### 3. What did you see instead?

The SQL with order by can not use index merge join.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-beta-444-g0c5e58107-dirty
Git Commit Hash: 0c5e58107dad2fbf5ae3464d9b9719ee503cc03a
Git Branch: master
UTC Build Time: 2020-03-19 06:02:12
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #15484 

Problem Summary: As title says.

### What is changed and how it works?

What's Changed: A hack change, you can check the comment in the code change.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
PTAL @eurekaka 
Any better idea for fixing this issue?

File: planner/core/exhaust_physical_plans.go [hunk 1]
```diff
@@ -1271,10 +1271,30 @@ func (p *LogicalJoin) tryToGetIndexJoin(prop *property.PhysicalProperty) (indexJ
...
+		if !canForced && needForced {
+			if hasINLMJHint && len(indexJoins) > 0 && len(prop.Items) > 0 {
+				containIdxMergeJoin := false
+				for _, idxJoin := range indexJoins {
+					if _, ok := idxJoin.(*PhysicalIndexMergeJoin); ok {
+						containIdxMergeJoin = true
+						break
+					}
+				}
+				// Index merge join has more strict conditions than index join and index hash join,
```
Comment (XuHuaiyu) [inline planner/core/exhaust_physical_plans.go]: 1. IndexMergeJoin requires stricter conditions than Index(Hash)Join when the output order is needed.
2. IndexMergeJoin requires looser conditions than Index(Hash)Join when the output is unordered.
3. If ordered-Index(Hash)Join can be chosen but ordered-IndexMergeJoin can not be chosen, we can build a plan with an enforced sort on IndexMergeJoin.
4. Thus we can give up the plans here if IndexMergeJoin is nil when `hasINLMJHint` is true. Because we can make sure that an IndexMeregJoin with enforced sort will be built.

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @eurekaka
