### PR TITLE
planner: fix prefer task logic when enumerate physical limit/topn | tidb-test=pr/2622

### LINKED ISSUE #63985: plan changed unexpectedly because expression index wasn't chosen by default
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
you can reproduce this problem using dataset as https://github.com/pingcap/tidb/issues/57090

And I think this is introduced by recent commit between  be3ba74ef819842dae045121eec5f3f6f0aaf1a7 and 3e7f31765ebe78bea7e4fdbd762180e20ade300b
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
choose expression index(`idx_metadata_location_id`) by default
```
+----------------------------------+---------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                               | estRows | task      | access object                                                                                                                                   | operator info                                                                                                                                                                                                                                                |
+----------------------------------+---------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_8                     | 14.84   | root      |                                                                                                                                                 | business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                               |
| └─TopN_12                        | 14.84   | root      |                                                                                                                                                 | business_db.event_log.created_time:desc, offset:0, count:70000                                                                                                                                                                                               |
|   └─Projection_27                | 14.84   | root      |                                                                                                                                                 | business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)) |
|     └─IndexLookUp_26             | 14.84   | root      |                                                                                                                                                 |                                                                                                                                                                                                                                                              |
|       ├─IndexRangeScan_23(Build) | 827.01  | cop[tikv] | table:e, index:idx_metadata_location_id(cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) | range:["498","498"], keep order:false, stats:partial[primary:unInitialized, _v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                    |
|       └─Selection_25(Probe)      | 14.84   | cop[tikv] |                                                                                                                                                 | eq(business_db.event_log.category, "payment"), ge(business_db.event_log.created_time, 2024-09-30 15:00:00.000000), le(business_db.event_log.created_time, 2099-01-01 00:00:01.000000)                                                                        |
|         └─TableRowIDScan_24      | 827.01  | cop[tikv] | table:e                                                                                                                                         | keep order:false, stats:partial[primary:unInitialized, _v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                         |
+----------------------------------+---------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
7 rows in set
Time: 0.009s
TiDB root@127.0.0.1:business_db> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v9.0.0-beta.2.pre-455-gbe3ba74ef8        |
| Edition: Community                                        |
| Git Commit Hash: be3ba74ef819842dae045121eec5f3f6f0aaf1a7 |
| Git Branch: HEAD                                          |
| UTC Build Time: 2025-10-16 01:52:55                       |
| GoVersion: go1.24.5                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
| Kernel Type: Classic                                      |
+-----------------------------------------------------------+
```

### 3. What did you see instead (Required)
choose `idx_created_time` by default
```
+------------------------------------+------------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows    | task      | access object                                 | operator info                                                                                                                                                                                                                                                |
+------------------------------------+------------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_8                       | 14.84      | root      |                                               | business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                               |
| └─Limit_15                         | 14.84      | root      |                                               | offset:0, count:70000                                                                                                                                                                                                                                        |
|   └─Selection_33                   | 775.61     | root      |                                               | eq(cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)), "498")                                                                                                                      |
|     └─Projection_32                | 775606.29  | root      |                                               | business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)) |
|       └─IndexLookUp_31             | 775606.29  | root      |                                               |                                                                                                                                                                                                                                                              |
|         ├─IndexRangeScan_28(Build) | 1396311.43 | cop[tikv] | table:e, index:idx_created_time(created_time) | range:[2024-09-30 15:00:00.000,2099-01-01 00:00:01.000], keep order:true, desc, stats:partial[primary:unInitialized, _v$_idx_metadata_location_id_0:unInitialized]                                                                                           |
|         └─Selection_30(Probe)      | 775606.29  | cop[tikv] |                                               | eq(business_db.event_log.category, "payment")                                                                                                                                                                                                                |
|           └─TableRowIDScan_29      | 1396311.43 | cop[tikv] | table:e                                       | keep order:false, stats:partial[primary:unInitialized, _v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                         |
+------------------------------------+------------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
8 rows in set
Time: 0.014s
TiDB root@127.0.0.1:business_db> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v9.0.0-beta.2.pre-626-g3e7f31765e        |
| Edition: Community                                        |
| Git Commit Hash: 3e7f31765ebe78bea7e4fdbd762180e20ade300b |
| Git Branch: master                                        |
| UTC Build Time: 2025-10-15 09:52:15                       |
| GoVersion: go1.24.5                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
| Kernel Type: Classic                                      |
+-----------------------------------------------------------+
```
### 4. What is your TiDB version? (Required)
nightly 3e7f31765ebe78bea7e4fdbd762180e20ade300b
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #63985

Problem Summary: check https://github.com/pingcap/tidb/issues/63985#issuecomment-3449963065 for detail.

### What changed and how does it work?
there will be two kinds of tasks:
1. hintTask: this task was chosen because of hint
2. normalTask: non-hint task. There will be two kinds of normalTask:
    1. normalPreferTask: when topn/limit meet threshold, it will be a normalPreferTask
    2. normalIterTask: other normal tasks

hintTask has highest priority, then normalPreferTask, the last is normalIterTask. And normalPreferTask only take effects inside one physical plan slice.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

```
set @@global.tidb_enable_auto_analyze = 'OFF';

set names utf8mb4;
drop database if exists business_db;
create database business_db;
use business_db;
CREATE TABLE `event_log` (
    `id` varchar(255) NOT NULL,
    `created_time` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
    `modified_time` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
    `money_info` json DEFAULT NULL,
    `actors` json DEFAULT NULL,
    `recipient` varchar(255) GENERATED ALWAYS AS (json_extract(`actors`, _utf8mb4'$[*].recipient')) STORED,
    `operator_id` varchar(255) GENERATED ALWAYS AS (json_extract(`actors`, _utf8mb4'$[*].operator_id')) STORED,
    `category` varchar(255) DEFAULT NULL,
    `action` varchar(255) DEFAULT NULL,
    `cancelled_by_id` varchar(255) DEFAULT NULL,
    `cancellation_of_id` varchar(255) DEFAULT NULL,
    `metadata` json DEFAULT NULL,
    `money_details` json DEFAULT NULL,
    PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
    KEY `idx_operator_id` (`operator_id`),
    KEY `idx_created_time` (`created_time`),
    KEY `idx_category` (`category`),
    KEY `idx_action` (`action`),
    KEY `idx_recipient` (`recipient`),
    KEY `idx_cancelled_by_id` (`cancelled_by_id`),
    KEY `idx_cancellation_of_id` (`cancellation_of_id`),
    KEY `idx_metadata_location_id` ((
        cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
-- stats are from issue https://github.com/pingcap/tidb/issues/57090
load stats '/Users/guojiangtao/Downloads/business_db.event_log.json';
explain SELECT SQL_NO_CACHE e.id, e.category, e.created_time, e.money_info
FROM `event_log` e
WHERE e.`category` = "payment"
AND e.`created_time` BETWEEN "2024-09-30 15:00:00.000" AND "2099-01-01 00:00:01.000"
AND (cast(json_unquote(json_extract(e.`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) = "498"
ORDER BY e.`created_time` DESC
LIMIT 70000;

-- use expression index by default
id	estRows	task	access object	operator info
Projection_8	14.84	root		business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info
└─TopN_12	14.84	root		business_db.event_log.created_time:desc, offset:0, count:70000
  └─Projection_27	14.84	root		business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255))
    └─IndexLookUp_26	14.84	root
      ├─IndexRangeScan_23(Build)	827.01	cop[tikv]	table:e, index:idx_metadata_location_id(cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin)	range:["498","498"], keep order:false, stats:partial[primary:unInitialized]
      └─Selection_25(Probe)	14.84	cop[tikv]		eq(business_db.event_log.category, "payment"), ge(business_db.event_log.created_time, 2024-09-30 15:00:00.000000), le(business_db.event_log.created_time, 2099-01-01 00:00:01.000000)
        └─TableRowIDScan_24	827.01	cop[tikv]	table:e	keep order:false, stats:partial[primary:unInitialized]
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/cascades/memo/group_expr.go [hunk 1]
```diff
@@ -273,42 +274,50 @@ func ExhaustPhysicalPlans4GroupExpression(e *GroupExpression, prop *property.Phy
...
 		panic("unreachable")
 	}
+
+	if err != nil {
+		return nil, hintCanWork, err
+	}
+	if len(ops) > 0 {
+		return [][]base.PhysicalPlan{ops}, hintCanWork, nil
+	}
+	return nil, hintCanWork, nil
```
Comment (AilinKid) [inline pkg/planner/cascades/memo/group_expr.go]: if len(ops) > 0 && err == nil {
		return [][]base.PhysicalPlan{ops}, hintCanWork, nil
	}
return nil, hintCanWork, nil

File: pkg/planner/core/find_best_task.go [hunk 2]
```diff
@@ -83,18 +83,48 @@ type enumerateState struct {
 	limitCopExist bool
 }
 
-// @first: indicates the best task returned.
-// @second: indicates the plan cnt in this subtree.
-// @third: indicates whether this plan apply the hint.
-// @fourth: indicates error
 func enumeratePhysicalPlans4Task(
+	super base.LogicalPlan,
+	physicalPlans [][]base.PhysicalPlan,
```
Comment (hawkingrei) [inline pkg/planner/core/find_best_task.go]: We can add a comment to explain why this is a two-dimensional array here.

File: pkg/planner/core/exhaust_physical_plans.go [hunk 3]
```diff
@@ -50,49 +50,62 @@ import (
...
 	case *mockLogicalPlan4Test:
-		return ExhaustPhysicalPlans4MockLogicalPlan(x, prop)
+		ops, hintCanWork, err = ExhaustPhysicalPlans4MockLogicalPlan(x, prop)
 	default:
 		panic("unreachable")
 	}
+
+	if err != nil {
+		return nil, hintCanWork, err
+	}
```
Comment (AilinKid) [inline pkg/planner/core/exhaust_physical_plans.go:104]: ditto

File: pkg/planner/core/find_best_task.go [hunk 4]
```diff
@@ -83,18 +83,48 @@ type enumerateState struct {
 	limitCopExist bool
 }
 
-// @first: indicates the best task returned.
-// @second: indicates the plan cnt in this subtree.
-// @third: indicates whether this plan apply the hint.
```
Comment (AilinKid) [inline pkg/planner/core/find_best_task.go:88]: kept it?

Comment (guo-shaoge) [reply pkg/planner/core/find_best_task.go:88]: I think the code is clear enough.

File: pkg/planner/core/operator/physicalop/physical_topn.go [hunk 5]
```diff
@@ -44,9 +44,9 @@ type PhysicalTopN struct {
 }
 
 // ExhaustPhysicalPlans4LogicalTopN exhausts PhysicalTopN plans from LogicalTopN.
-func ExhaustPhysicalPlans4LogicalTopN(lt *logicalop.LogicalTopN, prop *property.PhysicalProperty) ([]base.PhysicalPlan, bool, error) {
+func ExhaustPhysicalPlans4LogicalTopN(lt *logicalop.LogicalTopN, prop *property.PhysicalProperty) ([][]base.PhysicalPlan, bool, error) {
 	if MatchItems(prop, lt.ByItems) {
-		return append(getPhysTopN(lt, prop), getPhysLimits(lt, prop)...), true, nil
+		return [][]base.PhysicalPlan{getPhysTopN(lt, prop), getPhysLimits(lt, prop)}, true, nil
```
Comment (qw4990) [inline pkg/planner/core/operator/physicalop/physical_topn.go:53]: Please add some comments to explain why we have to split this into 2 groups.

Comment (guo-shaoge) [reply pkg/planner/core/operator/physicalop/physical_topn.go:53]: done

**Review by qw4990 — APPROVED** [review]

**Comment by AilinKid** [comment]
test on BXXX replayer env, passed
