### PR TITLE
codec: encode checksum for timestamp consider tz

### LINKED ISSUE #50851: row level checksum calculation failed on timestamp value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

ref https://github.com/pingcap/tiflow/issues/10573

### 1. Minimal reproduce step (Required)
```
set global tidb_enable_row_level_checksum=true;

set @@global.time_zone = '-05:00'

create table t (a int primary key, b timestamp);

insert into t values (1, '2023-02-09 13:00:00');
```

### 2. What did you expect to see? (Required)

When calculating checksum for timestamp value, should convert it to UTC, and then perform the calculation, to make the checksum value irrelevant to the time zone.

### 3. What did you see instead (Required)

Calculate checksum for the timestamp value based on time zone, this makes the downstream TiCDC changefeed verify changefeed failed, if the TiCDC server time zone is not the same as the TiDB.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #50851

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix row checksum calculation on the timestamp does not consider time zone cause the CDC failed to verify the checksum
```

### CODE REVIEW

File: pkg/table/tables/tables.go [hunk 1]
```diff
@@ -1825,7 +1825,11 @@ func (t *TableCommon) calcChecksums(sctx sessionctx.Context, h kv.Handle, data [
 	}
 	checksums := make([]uint32, len(data))
 	for i, cols := range data {
-		row := rowcodec.RowData{Cols: cols, Data: buf}
+		row := rowcodec.RowData{
+			Cols: cols,
+			Data: buf,
+			Loc:  sctx.GetSessionVars().TimeZone,
```
Comment (zyguan) [inline pkg/table/tables/tables.go:1831]: To be consistent with `Encode`, using `sctx.GetSessionVars().StmtCtx.TimeZone()` is better.

File: pkg/util/rowcodec/common.go [hunk 2]
```diff
@@ -264,6 +265,9 @@ type RowData struct {
 	// Data stores the result of Encode. However, it mostly acts as a buffer for encoding columns on checksum
 	// calculation.
 	Data []byte
+
+	// loc is used to convert Timestamp value to UTC for checksum calculation.
+	Loc *time.Location
```
Comment (zyguan) [inline pkg/util/rowcodec/common.go:270]: Instead of adding a new field here, why not to let `Checksum` accept a `loc` argument? (just like `Encode`)

File: pkg/ddl/column.go [hunk 3]
```diff
@@ -1416,6 +1416,7 @@ func (w *updateColumnWorker) calcChecksums() []uint32 {
 		if !sort.IsSorted(w.checksumBuffer) {
 			sort.Sort(w.checksumBuffer)
 		}
+		w.checksumBuffer.Loc = w.sessCtx.GetSessionVars().TimeZone
```
Comment (zyguan) [inline pkg/ddl/column.go:1419]: ditto

**Review by zyguan — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@wjhuang2016 @tangenta 
Please help take a look

**Review by ywqzzy — APPROVED** [review]
