### PR TITLE
planner/codec: fix issue of decode plan error cause by without escape special char

### LINKED ISSUE #21642: decode plan in statement summary failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
select tidb_version();
SELECT exec_count, schema_name, query_sample_text, plan  FROM information_schema.statements_summary;
```

### 2. What did you expect to see? (Required)
```
mysql> SELECT exec_count, schema_name, query_sample_text, plan  FROM information_schema.statements_summary;
+------------+-------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| exec_count | schema_name | query_sample_text                | plan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+------------+-------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|          1 |             | select tidb_version()            |        id ... N/A                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|          1 |             | select @@version_comment limit 1 | 	id           	task	estRows	operator info                                                                     	actRows	execution info                        	memory 	disk
	Projection_5 	root	1      	TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible->Column#1	1      	time:5.64µs, loops:2, Concurrency:OFF	0 Bytes	N/A
	└─TableDual_6	root	1      	rows:1                                                                            	1      	time:1.12µs, loops:2                 	N/A    	N/A       |
+------------+-------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)
```
mysql> SELECT exec_count, schema_name, query_sample_text, plan  FROM information_schema.statements_summary;
+------------+-------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| exec_count | schema_name | query_sample_text                | plan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+------------+-------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|          1 |             | select tidb_version()            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|          1 |             | select @@version_comment limit 1 | 	id           	task	estRows	operator info                                                                     	actRows	execution info                        	memory 	disk
	Projection_5 	root	1      	TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible->Column#1	1      	time:5.64µs, loops:2, Concurrency:OFF	0 Bytes	N/A
	└─TableDual_6	root	1      	rows:1                                                                            	1      	time:1.12µs, loops:2                 	N/A    	N/A       |
+------------+-------------+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
```
[2020/12/10 08:21:50.620 +00:00] [ERROR] [statement_summary.go:831] ["decode plan in statement summary failed"] [plan="twPwPDAJM18zCTAJMQlSZWxlYXNlIFZlcnNpb246IHY0LjAuMC1iZXRhLjItMTc4NC1nYjljNWFhZjU1CkVkaXQFJzBDb21tdW5pdHkKR2l0BQ4gaXQgSGFzaDogFS58MjkwY2ZiYjczMjA4NGYwMzMyNDg2NGJhOTZhYzc4YwoBOtBCcmFuY2g6IG1hc3RlcgpVVEMgQnVpbGQgVGltZTogMjAyMC0xMi0xMCAwODoxMjoxOQpHbxWtkGdvMS4xNS4zClJhY2UgRW5hYmxlZDogZmFsc2UKVGlLViBNaW4d3AAzBdzwQDYwOTY1YjAwNjg3N2NhNzIzNGFkYWNlZDc4OTBkN2IwMjllZDEzMDYKQ2hlY2sgVGFibGUgQmVmb3JlIERyb3A6CWE0LT5Db2x1bW4jMQkxCXQBr/A+Ni45M8K1cywgbG9vcHM6MiwgQ29uY3VycmVuY3k6T0ZGCTAgQnl0ZXMJTi9BCjEJMjVfNAkwCTEJcm93czoxEUcMMS4yOC5HACAJTi9BCU4vQQo="] [error="decode plan: Check Table Before Drop: false->Column#1\t1\ttime:6.93µs, loops:2, Concurrency:OFF\t0 Bytes\tN/A, depth: Check Table Before Drop: false->Column#1, error: strconv.Atoi: parsing \"Check Table Before Drop: false->Column#1\": invalid syntax"]
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
Release Version: v4.0.0-beta.2-1784-gb9c5aaf55
Edition: Community
Git Commit Hash: b9c5aaf55290cfbb732084f03324864ba96ac78c
Git Branch: master
UTC Build Time: 2020-12-10 08:12:19
GoVersion: go1.15.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

- close #21642
- Refine projection explain information display.

**Before**

```sql
test> explain select tidb_version();
+---------------+---------+------+---------------+-------------------------------------------------------------------+
| id            | estRows | task | access object | operator info                                                     |
+---------------+---------+------+---------------+-------------------------------------------------------------------+
| Projection_3  | 1.00    | root |               | Release Version: v4.0.0-beta.2-1832-g7fac2ba02                    |
|               |         |      |               | Edition: Community                                                |
|               |         |      |               | Git Commit Hash: 7fac2ba027aee70cad4f4a307240ef5b7e6a64f8         |
|               |         |      |               | Git Branch: master                                                |
|               |         |      |               | UTC Build Time: 2020-12-16 03:32:17                               |
|               |         |      |               | GoVersion: go1.14.4                                               |
|               |         |      |               | Race Enabled: false                                               |
|               |         |      |               | TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
|               |         |      |               | Check Table Before Drop: false->Column#1                          |
| └─TableDual_4 | 1.00    | root |               | rows:1                                                            |
+---------------+---------+------+---------------+-------------------------------------------------------------------+
```

**This PR**

```sql
test> explain select tidb_version();
+---------------+---------+------+---------------+------------------------------------------------+
| id            | estRows | task | access object | operator info                                  |
+---------------+---------+------+---------------+------------------------------------------------+
| Projection_3  | 1.00    | root |               | Release Version: v4.0.0-beta.2-1889-g2b5e3e355 |
|               |         |      |               | Edition: Communit(len:331)->Column#1           |
| └─TableDual_4 | 1.00    | root |               | rows:1                                         |
+---------------+---------+------+---------------+------------------------------------------------+
```

### What is changed and how it works?

N/A
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- Fix issue of decode plan error cause by without escape special char.

### CODE REVIEW

File: expression/explain.go [hunk 1]
```diff
@@ -95,6 +95,15 @@ func ExplainExpressionList(exprs []Expression, schema *Schema) string {
 		switch expr.(type) {
 		case *Column, *CorrelatedColumn:
 			builder.WriteString(expr.String())
+		case *Constant:
+			v := expr.String()
+			if len(v) < 16 {
+				builder.WriteString(v)
+			} else {
+				builder.WriteString(fmt.Sprintf("%s(len:%d)", v[:16], len(v)))
```
Comment (crazycs520) [inline expression/explain.go:103]: @winoros @XuHuaiyu PTAL, I'm not sure if this change is appropriate.

**Comment by crazycs520** [comment]
@winoros @XuHuaiyu PTAL

File: expression/explain.go (hunk 1 above)
Comment (winoros) [reply expression/explain.go:103]: I'm ok with this change. But the 16 may be a little small?

Comment (crazycs520) [reply expression/explain.go:103]: How about 64?

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
