### PR TITLE
planner,indexjoin: Fix the panic of indexjoin + streamagg

### LINKED ISSUE #60297: index out of range using IndexJoin
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `tc04ef7a8` (
  `col_1` json DEFAULT NULL,
  `col_2` text NOT NULL,
  `col_3` varbinary(23) DEFAULT NULL,
  `col_4` timestamp NOT NULL,
  `col_5` date NOT NULL DEFAULT '2018-02-16',
  `col_6` text DEFAULT NULL,
  `col_7` datetime DEFAULT '1971-02-24 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `col_8` float DEFAULT NULL,
  KEY `idx_1` (`col_4`),
  KEY `idx_2` (`col_4`,`col_5`,`col_8`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `tc04ef7a8` VALUES ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:56:13','2023-11-22','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:56:13','1980-12-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:56:13','1989-04-25','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:56:13','2001-11-19','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:56:13','1988-10-11','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:56:13','1991-04-01','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2005-09-13 00:00:00','1975-12-19','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2006-11-26 00:00:00','2030-08-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2004-06-07 00:00:00','2010-12-21','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-30 00:00:00','2008-11-02','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:57:00','2000-01-24','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2022-07-17 00:00:00','1973-01-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2013-04-23 00:00:00','2009-04-02','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:57:00','1992-06-30','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2005-01-31 00:00:00','1999-10-26','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2025-03-27 00:57:00','1987-04-05','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1999-11-04','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7526.346), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1985-08-13 00:00:00','1998-01-18','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1987-08-27 00:00:00','1983-05-05','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1973-09-09 00:00:00','2008-02-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1999-08-30 00:00:00','2014-04-25','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1973-09-09 00:00:00','2008-02-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1980-07-01 00:00:00','2012-06-01','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2017-11-09 00:00:00','1974-12-28','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2008-11-07 00:00:00','2003-10-19','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1999-06-27 00:00:00','2009-01-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2005-07-12 00:00:00','1986-06-26','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2008-07-18 00:00:00','2013-08-12','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2022-09-27 00:00:00','1984-08-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1984-03-18 00:00:00','2013-02-18','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1981-08-27 00:00:00','2015-04-22','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2013-11-18 00:00:00','2018-08-03','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2033-07-22 00:00:00','2032-05-03','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2036-04-22 00:00:00','2031-09-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1980-12-01','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8161.617), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1974-10-29 00:00:00','2002-10-24','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2028-05-20 00:00:00','1999-06-17','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4497.738), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1971-10-06','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6947.1206), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1973-10-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9113.898), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2032-05-30 00:00:00','1998-11-29','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3937.0806), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1989-01-24 00:00:00','1994-05-10','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',1726.1567), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1981-02-09 00:00:00','2004-10-18','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3082.2595), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2030-07-21','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8399.795), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1975-04-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7810.977), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1985-01-28 00:00:00','2013-11-20','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',2334.298), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1986-07-21 00:00:00','2031-10-17','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',1746.9595), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2019-02-07','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',5682.377), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2004-04-20 00:00:00','1977-12-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4927.688), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1985-05-01 00:00:00','1989-03-14','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4933.195), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2028-06-30 00:00:00','1999-08-08','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4682.0674), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1980-10-10 00:00:00','1976-05-06','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',1982.0607), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2031-06-26 00:00:00','1992-10-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6843.6216), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1995-06-09 00:00:00','1977-10-04','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',NULL), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2016-07-19 00:00:00','2010-02-17','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',5100.1396), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1997-08-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7113.8213), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2007-07-07','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8241.565), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2029-09-24','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6826.217), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1996-02-25','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8946.759), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2001-12-31','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6014.626), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1973-04-20','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7059.8438), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2016-05-13','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6683.394), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2034-07-19 00:00:00','1971-11-04','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4526.2705), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1998-04-06 00:00:00','2005-08-05','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6843.6216), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2010-06-17','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8347.349), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1976-05-14','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9032.411), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2012-08-05','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',5344.923), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1979-09-03','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9578.189), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1978-02-05','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9261.848), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2024-10-18','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6142.061), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2032-10-11 00:00:00','2026-02-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',809.17523), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2014-06-11 00:00:00','2006-08-11','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9917.4795), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2029-02-06 00:00:00','2012-09-30','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4066.3318), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2008-05-22 00:00:00','1997-03-20','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',990.44824), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1976-11-18','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7451.6147), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2030-06-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7311.961), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1987-11-13','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',5587.787), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2012-04-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7958.4697), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2012-01-23','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7100.2817), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2024-12-30 00:00:00','2010-06-28','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3139.812), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2030-09-25 00:00:00','2026-09-03','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3905.9797), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2004-08-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6239.8438), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2022-04-18','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9170.682), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','2011-07-31','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7287.9595), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2031-10-14 00:00:00','1984-04-30','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',2888.2983), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','2027-05-22 00:00:00','2027-04-11','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',2295.8054), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1996-02-10 00:00:00','1988-10-05','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3301.4358), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1982-09-01 00:00:00','1981-01-23','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',1911.2974), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1992-02-03 00:00:00','2022-01-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9739.668), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'61784f4b626f6e7030514c6b','1971-11-01 00:00:00','1971-01-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8818.118), ('[\"Wm7Xts0sTL8U6LZFU0awOSfrcyOKbQ24NNGIguhvSvqwPz4JFKyEU0JK2Mi6cuST\", \"ukeamBebpW567Zyi68tr0Q9Sy0WDeM10Epp62VicDPJzyUZcqT6tMx4cqDqMStEx\"]','SNGCs)L5',NULL,'1971-11-01 00:00:00','1970-08-26','V^@+90hk(&','2025-03-27 01:00:18',9340.397), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'6b6a6246236539297445726a6d5e6e7a6152','1971-11-01 00:00:00','1982-12-06','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7364.4727), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'6842','1971-11-01 00:00:00','1991-02-02','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9565.764), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'53694a6356574d','1971-11-01 00:00:00','2028-05-10','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6912.949), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'407e4a64','1971-11-01 00:00:00','1989-11-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6684.926), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'374b4f5a575e7a3440525f6761774f33533374','1971-11-01 00:00:00','2001-03-12','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6102.835), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'464a24','1971-11-01 00:00:00','1988-06-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8630.564), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'5943444258754e334f','1970-01-26 00:00:00','1975-03-19','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3606.3813), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'6d6a524f446d393158','1971-11-01 00:00:00','1996-05-31','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6287.723), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'256d4551572d236d26654c26436a','2014-12-19 00:00:00','1973-08-15','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4150.954), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'23','1971-11-01 00:00:00','1970-05-19','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',7031.1016), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'676352752b37353d4562','2025-01-28 00:00:00','2009-08-21','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3031.3337), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'462540377e79445f5634416e44317925636151','1977-12-29 00:00:00','2005-01-06','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',2038.1078), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'706c5e','2002-12-02 00:00:00','1987-07-10','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4710.8906), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'2a33547e42','1985-03-04 00:00:00','1971-08-06','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',1777.1173), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'2a742825','2017-10-24 00:00:00','1975-01-17','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4585.4316), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'794b756f2357482934463330','2000-05-08 00:00:00','2034-05-10','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',4150.192), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'','2015-07-18 00:00:00','1993-08-10','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',3339.85), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'4f40295629577a236373','1971-11-01 00:00:00','2013-05-15','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',5871.92), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'6f4a3d622a316446514e544529','2021-08-15 00:00:00','2019-09-12','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',1566.1105), ('[\"hNfyVYdkgn3EGmhtU2HskJJ4vG25fcVz4ziGzVNAj893BanroXp45rB9reDLDwdc\", \"BDrT2ciR1wOnDkwWxFu0o5bI9xZdi7lBaOvr1GDgYQV8L8Ngo8SXxgGI3eiGUKJz\", \"M6JDwvdprR1MpRf9crpqsbn04jUL8rFkSQ4YlbMK55TWYy9dPY9yYV2dzHoga2Jf\"]','SNGCs)L5',x'4a5f4354753535286b447647244c7a53544062','1971-11-01 00:00:00','2034-03-04','Gb@Os9~jir(2nJ','2025-03-27 01:00:18',8683.723), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'4b41692d4826','1972-05-27 00:00:00','2017-09-13','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',403.09402), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'6a674c','1971-11-01 00:00:00','2021-01-01','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8451.833), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'395a53296e','1971-11-01 00:00:00','1975-10-08','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6990.6567), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'776a42566c7463434b','1971-11-01 00:00:00','2027-06-03','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8538.979), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'7a7962516c58735169714e4958416c35702123','1971-11-01 00:00:00','2023-01-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8535.956), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'2a446a32','2022-04-06 00:00:00','2025-10-10','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',NULL), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'5e75573046445077644e65377e','1975-02-23 00:00:00','2030-12-08','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',923.494), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'6944656e57476a','1997-07-04 00:00:00','1971-03-15','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',416.11377), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'4f4447566a353921496e446c594c576b394037','1971-11-01 00:00:00','1990-11-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',6169.3423), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'2838334c416b41244b5833','2036-06-11 00:00:00','2031-09-16','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',2788.476), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'2938492d42472b','2019-01-06 00:00:00','2005-04-14','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',9894.699), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'25','2030-08-12 00:00:00','2008-12-11','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',2067.6208), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'4e3054706a716161792d3971453775642a','1994-07-18 00:00:00','2015-12-27','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',113.515945), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'6f624b2b6e7253374479324359','2009-05-03 00:00:00','2036-11-30','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8673.501), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'58637a6d28','1972-05-14 00:00:00','1994-10-20','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8566.794), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'5131674d792b6a436c536f466832','1994-04-26 00:00:00','1977-05-05','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',2351.8042), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'3850','2012-12-08 00:00:00','1983-03-09','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',1628.4546), ('[\"a9aQipQwjHVW6WvlI3wTNzS9IShhaN2bpDypWXjPxkLKDRz13L4uVhkmCmWL5sPP\"]','SNGCs)L5',x'744e6c6b314944303d78287854404c','1991-02-10 00:00:00','1984-09-23','xUhXa6=s%j7h~!G','2025-03-27 01:00:18',8749.709), ('[\"r6lqerWZmktpMDO1bmGjdjRtfdJWF2As15HiYXFcJ9ZgQCjiK705p04k9RFDXsJZ\", \"YredJ55f7WWXbxCB3HOveHfUkvk5bPiE6ruS4qPUkD7HNDIcClPiUgtY8lEbSzE5\", \"i65a0Fk1KSBTexl4OggRKFE2XL6MKeEi8Yembg9gyimwV9xS5Pu0sUyEZ4EVgPjC\", \"xzadW0HHONNYUNxdOgKV0LK4tlVPLiG792DbczmH3lv3MqvVh5U1c3cMzsBDc0AY\", \"GST5yqSWoieEpsiGlJcd44T2RgpYxaU6ghziIkHdAIyobgpLThpWLDLUlOKu8Dvw\"]','SNGCs)L5',x'516d39','1996-10-25 00:00:00','2012-09-30','v@RJJoWBBg@rNNX&#','2025-03-27 01:00:18',1327.6902), ('[\"hIsDT59lbKTfKg0sZRDX728FLtWEE3IoFNusMboq9jQrOALW2yhaHQzVQcSCmOqg\", \"H8IcUUHlODBOSY9RbXiEqXAsxKEeSgpv9m4OrL9SlihKPpt3RUdRDsJ8WJZcg06E\", \"yCAlwtobSAGlekVgkF5ksx1oouvGJKn9zGqe2zGRbjlpM0yHO2cARhNrde8DCejW\", \"eMiBpy1lpDQOYiQ4gdA251qB2CkJTmpE0WrzvYR5hHCeucljoiqYnSMvCaeiiuCX\", \"xcZ4ALZATwmZY98xWqWMmVoW3NBeycH3cE0NFRoMMptgZoSsFqPi7Ef3jWXxFlcb\"]','SNGCs)L5',x'4f523674746c314d6c4f642a327632756b','2004-05-25 00:00:00','1978-05-02','Yz1tpB5','2025-03-27 01:00:18',145.96391), ('[\"7OSFpFtRe8fFgmb8GNZwSM2rZw13r6xbaYi7TWHtySxmCvAGFCRNyUDcSfkaTjfk\", \"RwzTHmBj1E30nOhLIwClqlY2ENTTwulgi9rL9XyGWRxj228w4U9ODXPNzBUrVUOe\"]','SNGCs)L5',x'','2009-03-21 00:00:00','1992-01-07','5Q','2025-03-27 01:00:18',547.2869), ('[\"XwIO0oVwHcB4pLxMf2Sabqg6hYqPlNEJ5nIJtFH1i2KwhFLclfaoV53zrfF6PknO\", \"Kzq4fhFCdZLb3xTWfuxZVZWF4S4yNKxI7adK1oSx1ed6fCo3i56zpBIDxcFVnyI4\", \"QzrA6pJAMggz4ZydGwDeAzTbCPcHs6cTuHsG7znLCYyrgotPgdPHdLFvsvZWwiol\", \"RZkDffnnhGvqqsxPa1ktre8aMVZM8prhIl1YVug8zYVF7F1Wl982PIfh0Bc3njIQ\"]','SNGCs)L5',x'7e39525a426d5f6c463d4b4e345e306f50','2006-11-26 00:00:00','1976-08-18','UHBG_s^p5^OjB','2025-03-27 01:00:18',6504.2075), ('[\"9MuyDqBXEWiu4qzVvoeKbMnRDT9CbMz3N0KRN9HDuqHgG05D8ajNHXnWT9Rv97X8\", \"7Qj1VxOjsOoMEBwVWwB7SDQ5d8CiAn9HCV7Xl8XZRVEH8DXbXm4qL26QOzpSpyKb\", \"33ZcMfQ1v6hFqj9BwYNPOLSSiWfd5IhvTj92eGwrxvsElCMlZm8vPRP46wiaUvWU\"]','SNGCs)L5',x'462672783d412d4c36473936356737702b','2001-01-06 00:00:00','2029-05-30','LF$zv&x9dNr1B*_-9A','2025-03-27 01:00:18',2092.5554), ('[\"cxjOS4eu6mKKHc7pwVSMS6oPWSwuuT3NOJKSLL8xpsfT3TX2i3LeQL0gCTpZX2Vv\", \"QmSL4b3bHCBCreIbn8f82Gj4fq2QpgDDPOmbQRhE3gzesNKsGTN43QjhB7EM0Sn4\", \"Yl3d0hOzEfzfvWE4oxeGxF2ju7EydGq3KxsXWznb5bc3hiqDV69bEQc0TMS2wvZZ\", \"QyPzXHsJRq1HrCuPnHudrjQyZZneQAEkCAWkbGjVSZS4tdtSd3aJlp7JqXuoTFXR\", \"cRvXN8NDGXRR0tIyKwYiX3zlcnsbmfGxAchLjlOEai3hGNIkd09QnjHDxVqMWkgh\"]','SNGCs)L5',x'30','1996-08-17 00:00:00','2009-06-25','%','2025-03-27 01:00:18',9714.284), ('[\"ivPELJbSeOf950W45jslxfxubYMvu826bz9MkXdxmWwqIZLv4ZE8wdiwNmCfMrwI\", \"WUHmNE4Pym35SUHEPgg7oedDSwmhY2Vc67gzBP5Ty1CfWRnDwNd4OgEqBShayw6m\", \"ZKPTOIgfJHKqQGDpXQjsJgdezOk59DeKXghhumNDV8j4pm6g4KdX61fpJnS9QptS\", \"QL9hb5nNjDkxVQ6K2K8k7cgg3MnbUF4mde73bbI0qQ8Shl31yPL8gXycfNtok1vN\"]','SNGCs)L5',x'5371554d656251725a4b6745','1973-11-29 00:00:00','1976-12-12','Oz)VtkY#a9W@*8%Vx','2025-03-27 01:00:18',5222.995), ('[\"TOKhs0dV6Z8I4urXsUCrpZZnBxp5nqqHKENcP2iGrSP61bMrfNa4CvNUhT2GWbih\", \"gNnb7rRe1hkI25gRumJcMqNjG9hhG00qp4MUw4kOZLd1GEYix7S7JARPaaTCoQbr\"]','SNGCs)L5',x'77395379666f7446246f','2020-08-22 00:00:00','2008-03-14','s','2025-03-27 01:00:18',6985.5386), ('[\"UzysxwJmhyhTTAaVH5UI0x8jcaucyJx0Q05vnrdFOjxHmb0XjWngWCmp6JHx0Jnc\"]','SNGCs)L5',x'42455a4a413545664921','1974-11-29 00:00:00','1985-03-20','6daPv99O@oRiL8&8Epw','2025-03-27 01:00:18',8565.601), ('[\"10YH9Zxynxw2OzCACkvUwVeQO2d7Si9y3tawc9iQkSHQY6NUS5QmCFwX1VdYChGl\", \"Vs1zpnnPEmn0SDyDxn1B1XtKAVfDTvQ8gkIDjjkeD4bZ3rV1TB7QnVol75hIQr6Z\"]','SNGCs)L5',x'2a','2026-07-13 00:00:00','2035-11-28','','2025-03-27 01:00:18',3653.733), ('[\"RWNicpZJPJ8saxwtmCqIdyzhrSwF3bKP1MzJxgsHljytD80v7jHRCcVg1fX3QRmP\"]','SNGCs)L5',x'6a306a7a364e23553d2a792b6e255938','2000-01-24 00:00:00','2012-06-30','(L&37IR@ckJ','2025-03-27 01:00:18',5194.01), ('[\"hnggiy14NLbWGS1ZMXGUNNqLSbljEa1pNXnHjonIFKAU5hQ62Qed18JVhrcKlR8k\", \"rS7MxUH6vznW5t9BZx8wwATt92DzGuL1Zglr9vcpNZrzrkg6xiB0SzG4g2x7ygq8\", \"gcrW6EU6JF75FbmmJFhBOTZRYM7ajqUuujxrs4dYdIABztxi7R5dSlDVlZZJximL\", \"7pL3czeWDZ3TBeoOUhBNnSZkFEPJ8FqK3XVV52srvpAN3jS03se1UuqO5FfQjuVW\", \"hpURagFFTBEj5C5waHlvYMEFhKrjzBAWZsw25HfjlC78GRneZ4PZ6oxdzpIh3umg\"]','SNGCs)L5',x'4b366c6740286b29675a6138353d','1992-07-10 00:00:00','2001-11-05','Ed)','2025-03-27 01:00:18',3890.6755), ('[\"ZtWVtPvMaWX86zoNIS573RFwUmXyco3LXpyidbhmAsxTDdrFFpl5g41NMzvxmHNM\", \"qVP9Fp2XQOzH2Jh2x6ZkY36ipG897Y6EaPhLHlgyomCZVMpnwBzHu6lIYclGeAu2\", \"0n7crIizSBIJ312z16Yd50bdwNzHRakCEGGNJP23V2pFADKJHTSq3M9WjE4wfTzl\"]','SNGCs)L5',x'61454e52352548247833434c50796e286853','1999-09-11 00:00:00','1989-08-17','h5x*','2025-03-27 01:00:18',3475.339), ('[\"tTaw8vOnOC2Ip8fbJlTl1cojbzMNkE3xsLfOFpW4T5Wrwm2hiGvqTXAY3HgxrYNO\", \"wSXD1bfQ6B3fzktcXCcfWj3YSVtoI1GQousAyMPHpzQyEjTadmERJhQzcmLnDIpR\", \"Ru2Vk1hIjmSII6xcaQ6zw1oMlBgPvm6iBH3fqZEoiz035HyZX7t7GbxmJZhQ7TpB\", \"TLEdVJGOa97TUMl6zIVPusZE02DwJCJBk78nDSYo1kvZxdntpz9iINzK4aEgyMBt\"]','SNGCs)L5',x'6334386c65352a696e373d696952545f6f','2008-10-13 00:00:00','1971-07-20','HEKj@N+#BB1N4','2025-03-27 01:00:18',6691.2417), (NULL,'SNGCs)L5',x'634d6158465163517332332353','2024-09-25 00:00:00','2005-06-12','','2025-03-27 01:00:18',583.688), ('[\"AgYSIf5iXn2bAHqOWE49KlfDqTAlUJQvXN8F0kGjzUMDIwYAhX8SwChICYCRfqJV\", \"qoC6Otxtl4UoNoQs9xcXeT2oeh0zI4z80YUn4iZQmQ1KBgNSnJYJWLKUgEgiMiKy\", \"2UO6HiFtSuxt21vKAqErK69qD7bK0p3KNG4oSAiveKTjCO7PcgsES6YtQ2igCMlW\"]','SNGCs)L5',x'5e56573243633874','1974-10-17 00:00:00','1977-05-24','#35a','2025-03-27 01:00:18',2180.2764), ('[\"u0jiFM9HTAD6PB972hxF3UgwdpWqVXBsCxN87VYgTa93M5ejgoW5T05cqWh14emy\", \"c80Dec3VO3wbO88VqVd7vKz1GvHm2uXoNWe7sLgoPC1EcKDy3a0B0aNat0vaTGGt\", \"pqYsL2HXY7b5xZlbMXlydTZ2ix0Kp5lOrxyC6LNH48kx1DTngnFBhslrT5QU5FIx\", \"syDC71fyW9AoalGm2xJsbBPbxFCim8a7ZlVVD79K6NhOZdzcNOHmP3WwhMQRfPyD\"]','%WZJa!tuzrtKe2^)',x'3162724e7724462b562b4249332a584b7940','2021-09-03 00:00:00','2025-05-17',NULL,'2030-07-05 00:00:00',6080.7603), ('[\"6SIoJvOcZK8J7ebWaSHGXaoBGILKX6W8iuLHL2Gn8HFWvi3WvPTlM6QTDZzeOEJ0\", \"SaKaHruzQgAhfEnh2XSus7D4S9ve1bu8iBBBaJDH1xNuZUVn2FrVczXoGhYN8aUf\"]','SNGCs)L5',x'4b7879256953','1994-05-01 00:00:00','1974-04-07','Wy3p-=+i2Ex','2025-03-27 01:00:18',4884.9814), ('[\"pHgMgJoPNs7njTWN5hJ44ZfmeNu582i7sWJeukK1ZHl5o00u2dkrJgLJPQ05PWQw\", \"n8Zad40yucQZZR9W8mHrDf8zYCHYFKZCR1s59pKw6KseJiT7TfcPVM9WTkn7byPC\", \"JDhbpLmAAowaQOuQ2FQoc3r94c9Y8X7KCxxWJoN1vn4OHXGpuC4jZZTo9ShDsvd0\"]','SNGCs)L5',x'36','2011-02-19 00:00:00','2021-06-15',')n=u7-9D2=t!!!D','2025-03-27 01:00:18',2063.5923), ('[\"GE0Az4a2NX5bUa0dAN4Ei6VbnImL9DHhTOo8co1SraW9zTbU9TpjBEooOVd7v9g1\"]','SNGCs)L5',x'4f4d7463766a663d','2030-08-03 00:00:00','1979-01-31','','2025-03-27 01:00:18',5322.2495), ('[\"pors0j0lqxDCU9xBlV79rBg9N8RtKjC2fc5einOvdO9SDTGPXIVbqTwp6yT0SD4d\", \"XJRKl4MP1JesAiVUOpZ9qZ8hjn3wK1RQJ0CLUcPivSBQYVVWbTvE9oWvVZXG3vd2\", \"BOOupYcLthOYy2BhKCQ33ZyALDLOqez3xwGbPnWYfPEtjSOVbrbCJ2dtfE3dn1LD\", \"Ww2XoynDLInZg6jXuFT63BZtq9keyaYWFwcm9oVZ7X0RdpBg4TWFUGfIUTRusrJV\"]','SNGCs)L5',x'727636','1982-10-26 00:00:00','2014-12-22','X1M5)T+Hr$b8%i_R','2025-03-27 01:00:18',4203.909), ('[\"Mrxtgxy8nLq1cgcIoTUzpqiuKpMMPBzxGUvRSql3kVOFxURw85jp4kk8sSoDTbC1\", \"26TeAOgdlczzUD1lor4bSJv60QoxyQ8zGgKhAtGBipyREXRrEv8jzxNnmUdNDGjb\"]','SNGCs)L5',x'56616f627a43696b3d61436b6e66715a','2031-06-21 00:00:00','2016-10-07','sfu%SPfzV0$GA*oTj4_','2025-03-27 01:00:18',6362.059), ('[\"qxvLBnz4IW1DaKk51ZIKFTKp3brHKmm5BMSwbLNVd5jo5ueYdeecNDAALMi6IswL\", \"RWZ0A0xXNAojQEA1J8hYBW5eX2GnHSL1oz1nMGey7Ipy9VBzLr3jAbDC1lDGU7uW\", \"5MTj5DWP60VFPsI7iPEQwNLygnyzM4mOuCAQ2xK1CqSAlKqCdAttSkVUsUgFy6F1\", \"KrCJ96btrMPU9AG36BBjynCuqc9dkdPQExvOvISqfpzdgdyq4o89UEkkCa8HeM9k\"]','SNGCs)L5',x'762942286e645e425f','1975-01-12 00:00:00','2012-07-20','n7+pdd1=m','2025-03-27 01:00:18',3236.46), ('[\"FkAH9NA6rtAOKKDuflCPzwy6w39ATVMxX6dO2eZ5tXhUmSmeHibpvYEH6jf6ocpX\"]','SNGCs)L5',x'7e7544287264395f6f697334704e4f254d','1986-07-02 00:00:00','1993-10-15','g!*^B!YwV','2025-03-27 01:00:18',9962.9375), ('[\"E19PNV6d7BqjrTwrmMuub7bboxn2twKofe36AxynHMrMc7LTge877WR7IgeNr373\", \"hj7YVwfx31QsCFOLqAnIYjFIOPcZ6kg5lzw3JQmrnl7YxF329W9Obm1ObvMrUmc6\", \"DQSPXms4lM0AzxQC44hhhVOz527pfFSwMCptxOdgTnGeSl1Tqnod8WIJ6upkLdP9\", \"S9K4QV6RgTtStRrGh2PeVpV9ZakWhuYUjrgf8kT0Dh9TYr0ZPSShgCcoihvyrwOG\"]','SNGCs)L5',x'35282d','1995-02-21 00:00:00','1978-01-24','3!=z)VYDJk','2025-03-27 01:00:18',9247.132), ('[\"S4UAACYvg43uzHNNiI8DkYjauD8QRhIBoFWzQgTtyYY4KWesSGxcRNeRp7JiPpow\", \"IlsZv4C1nILFQmyrL64SiL57ceGIVTPn3L6iz8AvlTjVtKlEP3dAov910ernYP7I\"]','SNGCs)L5',x'4d4b66484b75332933767556306f43396429','1985-07-20 00:00:00','2010-11-06','-&','2025-03-27 01:00:18',9763.737), ('[\"yhjU2HwmAZeuRhyXqGumaCkCzR45ay14n9SzfhLvYCuALaSdzHH1W4cBQtuLlsK6\", \"vWzAK56QJs0yagWD2RLtN9zlqNcjJ2IZdNgtlD2F30JsT4l37sgB2Dt8gYKeqr5p\", \"QBUMPvl5VygHIZ76zHlqFLoYiGNQMVFwKTod7EiaBb8Mv7pQnX6UATObsEKsnjYk\", \"ezNvYQwgCd8hF9ExK2puffeaie0ugPUyUuJqeKMrFofthhpEkemtZKkFxMhUTc0k\", \"B2PWepH0PDFtav8o4OxZTuqc0dOA1RW0H2HPKWkCtYI9B4Jpp6JpXxZtjuNGP7TS\"]','SNGCs)L5',x'7e487252','2024-04-10 00:00:00','2035-01-18','mGfrUx%9Wjp#T7q','2025-03-27 01:00:18',794.3717), ('[\"sno85G7v7myF9Rh3Ih6scqh3uA5OyfgYXMHzjICJEIirURpYJAxfJ0wS09APw35g\", \"pwmg9rD9SGULUu7MHLMkcwsHkc3xV140h3ary87j25wnz3xvNLeZZcEmvEwpRiRx\", \"fjRV4gxFdXHe5wFwSlrxLfcaXB8oSXTELgB0AeGhKy4bkkdBGIyBvlOznmWXlcep\"]','SNGCs)L5',x'707876','1990-02-26 00:00:00','2018-05-30',')fn!Ci&)5i_4-urVZoJ','2025-03-27 01:00:18',3184.625), ('[\"Hbum0UuyCDysnzWx4JchcgbylZp0zLzVkYNocagU6Gz6CLtcrtfwAYTSbjzd2oKi\"]','SNGCs)L5',x'306270595458414e6d2538','2021-10-19 00:00:00','1977-07-10','t3$s@)a&)ivHiN-ff','2025-03-27 01:00:18',9500.755), ('[\"5qdJ3LWKWImRkcrUnXi2VfwFWvkbjYDv0gcHRjlExZcGLjzEDkxq5sUDJj5xq63Y\"]','SNGCs)L5',NULL,'2018-10-11 00:00:00','1971-07-25','LEPg1$(QUl49o','2025-03-27 01:00:18',9944.247), ('[\"LmuULIfmMY8bBGCWSt7sWVseb1Rcr9qXBl6CgYmwIZfCPMyYcdwLqWgX6mFekHJA\", \"zjJOQlKpvUNQpNLhhZEvoSrzyxky3AUCkEmFGeGygFtdzniVwsCSRMbnlIVrJjdQ\", \"ilGiq9bb7zCd8h6xqcQbExrgMotM52P8T1ArBEuifN6EXmkB3wkQg8WxCXizd4lI\", \"uV74kdr9dDwpx3UoFDIyqX6bsiti3BIE4DX9uwXKLMarHKs10hh3xjcypBwC0Cz8\"]','SNGCs)L5',x'40472832','1999-11-15 00:00:00','1988-04-29','pcYO8F5-%','2025-03-27 01:00:18',9708.866), ('[\"7ydDDuvigqLACg30jCZRRFzd19EHbhHSVTXSp1E5FVvm7kAuEquln3LXWwvi2fLo\", \"jZWFIYrIlqhVwALU5Y5SKXoUdw6jz1KYC1LoLEZTtkfjEqlxUfSm6bkaToKDTTyX\", \"P79zMZlcrPNq45pu4G1EVUc6e8L868cyDMBAMGdQH6fWgw1pr2ljkidIe0mmKIkU\"]','SNGCs)L5',x'2d6f7441264d2669517a3231284e425e','2018-09-20 00:00:00','1976-02-05','cW)U%jA$R-Ql','2025-03-27 01:00:18',3383.3982), ('[\"RnkUfvjoYZdvVJYuIjqnXL7jB0Suf0O24tWuCNBh5baP06AbdTx5NeBSKoSAb36H\", \"NIuu96Ssb9vsebtDfrL3qceCMM3kbcGsHZ2aiis7NhT1nSUC7zpCPEsnh2UXqHUm\", \"eJ10TiEUu0gFXV9FCPlfk0nEPc1KiybMe2FLVKZJ36KZIX3bOykUTFZ9n3Qutqnq\", \"Kwtvz3VQrmswHH6dKcNfQ7S69EsnhBsw01sEhqMI3Mi1XN00vEbCqZICj3Phdnu3\", \"VMxRNCCjdifIBWrdRVdCgW5UE8zWcWAbV7RCYfHsy0AnaM3P8jXil1j6e1BU2dzS\"]','@1Yd8*(xQQfqI!H0DC',x'2b73','1981-12-10 00:00:00','2004-02-23','YnW','2031-06-28 00:00:00',3511.3806), ('[\"wrg1gQh5XmQ6iUGkQfHmVhRlI0OfN1H6sjqQsJzika7JDCBU6lT1f3UkMu84n90g\", \"9gvFf7AtGRH9UKS7oWa7AYeOP8mUUdnR4fTAcmAXTHotkbXtrsAObsbiF2bZwWtA\", \"2IL9fxY93PfBeSIs1jvV3sGfgiD06g2ffayz3HOtUEhH3lTVt4kB8KuiPTYnyuob\"]','&va-v22=JLgb',x'675f6d557643794221355f40715970','2016-11-07 00:00:00','2032-12-12','3Oh5ox-d6r','1974-04-27 00:00:00',1454.9667), ('[\"OtxmFstpf8gwbbK1ZmuMfF6CY6Ss58g9G41HbEsiJRF9MqXszDmWIuoJKxKtHTS8\", \"IaKMbpEECyQCc8EsKlttOjRf0ARurtZD6mBSoBvuvbkWoKXfBHRn1zzs72qnHEmi\"]','k^98rMX!sS',x'564b6833305f58665233554e4873','1991-11-14 00:00:00','1989-08-28','A5xzxe*SLH@ZY8','2012-10-14 00:00:00',640.59784), ('[\"bEqKJebOoZhM6WSrt4rKcTD4Jpu5KoieFpzoOecIOMXnu6nbsTXm3RUx3Ybz9cc1\", \"BN0oanTHZv77ymY8kcRYXsCqscLJOi3HjSWMXJWdRMLJfcotMPkzKfRLQZt29bfk\", \"BbW5a9kn62dNLzaT7A3YcRZKOsAZtw74NMQxzQGgVJlMFTq908VZx9F2fMHFOnKL\"]','F&^b%p1',x'','2005-05-11 00:00:00','2036-10-26','9yEKuBU','2015-12-02 00:00:00',2855.658), ('[\"C0MbNjlSZ2x3F4XZAeejQr1DTesUpuBNDaPYUYcbb6D1ZAzbE4yxv7u4Mn18uYIj\", \"BI81OkBrGkja9tuCsFY6iIRPMou5AQ2WVyslukSaPI3TPmc5jEuAGSiFJ5L4sH5u\"]','',x'4e32644d4d4d452179','1990-11-20 00:00:00','2016-10-10','8)L)acMl15-Hcqdk$*','1994-03-16 00:00:00',7975.541);

CREATE TABLE `tl9d770ffc` ( `col_1` json DEFAULT NULL, `col_2` text NOT NULL, `col_3` varbinary(23) DEFAULT NULL, `col_4` timestamp NOT NULL, `col_5` date NOT NULL DEFAULT '2018-02-16', `col_6` text DEFAULT NULL, `col_7` datetime DEFAULT '1971-02-24 00:00:00' ON UPDATE CURRENT_TIMESTAMP, `col_8` float DEFAULT NULL, KEY `idx_1` (`col_4`), KEY `idx_2` (`col_4`,`col_5`,`col_8`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `tl9d770ffc` VALUES ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','+J8V1doNCnQA',NULL,'2025-03-27 00:58:56','2025-03-27','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','+J8V1doNCnQA',NULL,'2025-03-27 00:58:56','2025-03-27','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','+J8V1doNCnQA',NULL,'2025-03-27 00:58:56','2012-07-14','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','+J8V1doNCnQA',NULL,'2025-03-27 00:58:56','2025-03-27','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','+J8V1doNCnQA',NULL,'2025-03-27 00:58:56','2025-03-27','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','+J8V1doNCnQA',NULL,'2025-03-27 00:58:56','1997-07-02','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','kWLF!Agj(OBTxWkPI',NULL,'2025-03-27 00:58:56','2013-12-01','IVdtGpX(mIhr','2032-02-27 00:00:00',6223.036), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','%',NULL,'2025-03-27 00:58:56','1996-10-09','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','S5tN6',NULL,'1999-07-06 00:00:00','2025-10-21','IVdtGpX(mIhr','2032-02-27 00:00:00',6518.5405), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','',NULL,'2025-03-27 00:58:56','1994-11-16','IVdtGpX(mIhr','2032-02-27 00:00:00',6424.037), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','))BP!2=g',NULL,'2007-06-09 00:00:00','1977-08-23','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','hcm-fJLUi',NULL,'2028-07-29 00:00:00','1979-05-15','IVdtGpX(mIhr','2032-02-27 00:00:00',5074.166), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','r',NULL,'2033-11-19 00:00:00','1975-10-29','IVdtGpX(mIhr','2032-02-27 00:00:00',4817.4575), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]',')lI(wj*u',NULL,'1972-01-30 00:00:00','2015-05-05','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','!DE&Mk4Q5(f#l(',NULL,'2000-07-28 00:00:00','2004-01-31','IVdtGpX(mIhr','2032-02-27 00:00:00',1514.1029), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','1cL~2h',NULL,'2020-10-22 00:00:00','1982-06-13','IVdtGpX(mIhr','2032-02-27 00:00:00',8787.51), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','sFG4#@9ittRxSKL_I#',NULL,'1971-12-12 00:00:00','1988-09-30','IVdtGpX(mIhr','2032-02-27 00:00:00',1720.4863), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','$',NULL,'1974-06-07 00:00:00','1990-03-12','IVdtGpX(mIhr','2032-02-27 00:00:00',4325.0986), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','4k_1',NULL,'2029-02-06 00:00:00','1971-12-06','IVdtGpX(mIhr','2032-02-27 00:00:00',4845.289), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','Xw4299j2BlHi!E)yW',NULL,'2001-10-17 00:00:00','2013-11-27','IVdtGpX(mIhr','2032-02-27 00:00:00',8842.021), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','06K&O2*s',NULL,'2030-03-23 00:00:00','2016-02-14','IVdtGpX(mIhr','2032-02-27 00:00:00',8300.924), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','(=r=DoMF',NULL,'1980-05-15 00:00:00','1996-06-29','IVdtGpX(mIhr','2032-02-27 00:00:00',889.45575), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','ZEatIL$8Kb_&&(Cxm',NULL,'2016-01-28 00:00:00','2002-08-22','IVdtGpX(mIhr','2032-02-27 00:00:00',5456.3257), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','dxQ2Gu9=D%j',NULL,'2014-07-26 00:00:00','2030-07-04','IVdtGpX(mIhr','2032-02-27 00:00:00',4507.4756), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','g',NULL,'1993-07-30 00:00:00','2022-12-05','IVdtGpX(mIhr','2032-02-27 00:00:00',2533.8955), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','wlQ5bWD16I8',NULL,'1977-01-17 00:00:00','2006-09-26','IVdtGpX(mIhr','2032-02-27 00:00:00',9339.985), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','rPjv',NULL,'2031-06-15 00:00:00','2033-03-19','IVdtGpX(mIhr','2032-02-27 00:00:00',5983.647), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','(',NULL,'2023-03-12 00:00:00','2027-03-15','IVdtGpX(mIhr','2032-02-27 00:00:00',7553.776), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','=TK-f',NULL,'2029-10-25 00:00:00','2035-10-23','IVdtGpX(mIhr','2032-02-27 00:00:00',4353.097), ('[\"umVciu5eOvevA4tEvLqWhfG1pIan06V47oDaUiWYBFFJiq8qxz9ejKiTEN0QM1HE\", \"jAkJHKKf6IGeqbV6jrCs0fyuIv9McFUOccaFAXcaRvENf8wRWdXBzBYSyKhyRlg2\", \"mlP3tQaJMWxcTbBxgafLterHi0Kc0BbsJtL75BzYNrMIjyrI34l63baBHVnn9BX3\", \"9i4tNtQpUW5kCNR5MDVYlpVhgvrrxEYPHflvRwT9Y4tMV6cLTBs3ridsWFWUrcMI\"]','iErjhoQ05oymN',NULL,'2012-07-27 00:00:00','1987-05-04','IVdtGpX(mIhr','2032-02-27 00:00:00',787.99646), ('[\"YrgkJXsoth7WbbS4mvWQnPNEI1qgOMikjgY54lrXbeN2kpTC1XnhIw51m3Neladx\", \"Ibr0pNEZZ8KCeCetc9jf3Yiqp7Ai4mxXuo8BBceCHga0n0nHWXxicZXbJ1YuRhRi\", \"4JzUg2wMoBiuwbMlhC6OS5OR0kATK4IkztqljU49fsdWZOFma0zMl9u4V61dcgD3\", \"eG2T3awDPq4L5Br64s7zg6DB748uDUVWFYJSbOyoHQEiygr5JThWxWlwBEEFuc5x\", \"zHruTOCLXn2aXprRfx6GrjTFi9xTNURbWpa7YwTcK35nSNtWalIpVc51vvmBRxuW\"]','!',NULL,'1972-12-04 00:00:00','2009-07-20','IVdtGpX(mIhr','2032-02-27 00:00:00',3623.0562), ('[\"821Yi2ILbhfWpXekH7NxQ895KJmdLch3tsgO08goddh3Y45OSnnsOWAHanPwi2u7\", \"ZE7c7TWWbKzzTA0lu5y8QZiIB2qaYaVW1yaQVgIo5joBsfmM5NRy57JcnnRpU2Ul\", \"HHjZdsoXA18QZveuvYAu8RtT5TgxRejeMFGVYJPxzzAuqJxufW6MecMHHZTwdcgd\"]','',NULL,'2010-08-07 00:00:00','2031-10-02','IVdtGpX(mIhr','2032-02-27 00:00:00',4971.252), ('[\"LUErkAHU4vZRC9qQz5c1lnO4vnSSnktTRymyM1TpiUCRreuoLQfRQVHBm7CCFb96\", \"hbPNufli5eTsJ7ErIG1lI9xwjxy9YiE1t3KqjNuyqLBN6Vns4TRv9NAr8xMPkTkk\", \"mmeu8rvbYFNzxy5wwFS3WrREm8ArN9AVhXlkwLH2STSeTpaMWKdJyXajRAjU556p\"]','DfTv(8*qPuB=SCG-S5p',NULL,'1997-11-12 00:00:00','1973-11-26','IVdtGpX(mIhr','2032-02-27 00:00:00',3032.7073), ('[\"PvGlcp0yizD77rcbjDME7swKB8abFlOdCiBlFseTfnJFg5Z2zTYBS95yOuXCA9MX\", \"xvICSGyMekQIDU7X5k1NWOM2s9n99AxNPSSk2nZCuww2iIcfWon3BudwJLixp9ym\"]','BBEwcbs@',NULL,'2008-07-27 00:00:00','2004-02-26','IVdtGpX(mIhr','2032-02-27 00:00:00',2515.8047), ('[\"sfgk0pX4tp63GSYwRhGEfM9njuEuxqqZnuc7O0e0YR8Hf0cC06Mpeekau7jufmYd\", \"f9nuRIBkBIsN9lhhbhCd1eVBuLdpghvFvWVsBSqEJQUz88T4dCvq2KL4NyNXr9oW\", \"kAS8E0pu7o0Zz6xGGbtZFxK9yas0m2wGBzlDLA01z2S3XoLZ8cOkpkWfVDEbFF6L\", \"H4HL6VrnDKvIq7dD2ldwA0dxM1htZ1YUhMWRpTsQwpYhHae1JbytgYYSlL8URljP\", \"xlKtawxIefTCZIHbpV63JRHI1pcZxcE0W81jwlzMYhwOA4n5Am365f0zKA9S4vCS\"]','1b*26@0!-HsZqZ',NULL,'2003-07-17 00:00:00','2008-06-03','IVdtGpX(mIhr','2032-02-27 00:00:00',8107.181), ('[\"SX5OXglaCfv1rsv6PzxoNdWMeOLBM2wBQTkwy8xo7MFWRNTVp4xU8tuTtIzwi50r\"]','m)cFFbg4Ei5',NULL,'2024-01-07 00:00:00','2018-12-03','IVdtGpX(mIhr','2032-02-27 00:00:00',5086.8306), ('[\"URfnpkSCvcKAFCI0vZXqEiqGJxWFkb15dKRHp0GmdaC45OAQjutCLg5FRrmdlh5c\", \"RkyqN5uHpUs0j3ZZLwpBvTUVonig4GubxgoUi7VzIVJ8GMnHWMnAPdtChnzagOBY\", \"DivgeeU3ub3Z6t4mTc6Amo6sgac1i8jctCHyHh3zofILVFAhaQr9AdckAjX4BvGy\"]',')uHq',NULL,'1979-08-23 00:00:00','2003-10-16','IVdtGpX(mIhr','2032-02-27 00:00:00',7238.231), ('[\"jsPqTEqdSJyBhF2iJgXN4inba8NONEm9rFcA6chE710hoLed0jhOwvi69z3VBYXn\", \"lhVCfaqgJjBghsEp9VKjAt2LvnHTjcuQMzepCC2gio6l8wM0Oak1iYLMK5BGJgQS\", \"gPubZOwxLUyJtNAGaacOPzOcGGNRz5Kfi8IT2CbIctUKZkWcolbLeITYmcVkInIS\"]','7',NULL,'1998-06-24 00:00:00','2005-07-08','IVdtGpX(mIhr','2032-02-27 00:00:00',799.3357), ('[\"1k3Lemaq0dBRrvWAakprAQxWuvx9SOgZzAlKdoFq7qXeohyvaE0v6SOnfJyQkwNU\"]','$!S*R',NULL,'2036-08-23 00:00:00','1984-02-22','IVdtGpX(mIhr','2032-02-27 00:00:00',9058.462), ('[\"CdMgswemgIz6kIiSrhUTN5AEgydCbjg3j4aTrUFJuucuM22NUkt5gstBaGPA1ZXA\", \"iCz9BMArSd1clswPL27gdHRGSSlfveXFhBtwKTTSoaedm6TqriZHO9jiycqXTPI0\", \"YP2ev5iDGOpK0LyTI3Iq3ajlytTEudETOhg8OP0vN3Tt36aerDmf2FUDeFFxKoe2\", \"b3VllWAoBUEv0hcFSOcQ0PbasdU6jw0x2h3qZPqeUo7viGkXpYLD87XnbZN511Mn\"]','Q~EkduZG*sp@~',NULL,'1980-05-02 00:00:00','2020-04-08','IVdtGpX(mIhr','2032-02-27 00:00:00',9447.873), ('[\"oFg7VQksdvntBUm0WbpKOcx9h5sxCbkWwJbxIwHISro5rY1dGMHHD8hrxao8snHH\", \"dZoefh6njlqAppwLm458cirvJuMBtbjqSmltHPldVO8OJQ2Wi9x7JCrSyqad6rhG\", \"IJnFxvm5ynks00Dk9gEGq1ZUM8f4LA7g2lX9SzzAkA6FUKBC3HpASuFcfdf4iQu8\", \"12gmGt6V7ke8mYy4llrLbtsegoo3aK6G7cXLoEPgNuPa6Sm2E6JVCkRAPAlF8kuG\", \"hBn3aE6J5C9OcWhdaZRa0KIsCac3nuyBZewa9jtmYv3SgI5yUZcT92y5zkNrIsM0\"]','!MYZaNLbMUL',NULL,'1997-09-02 00:00:00','1999-06-30','IVdtGpX(mIhr','2032-02-27 00:00:00',8170.202), ('[\"oCVlcbkjMjyzalj63sHJWJY5FYxe3z5NlJ32gL5pLqKaSogXviKp8PlZFFKxrkoB\", \"3mYAJ2FRwQjtWyjYglxD5D4mpFjHGXow7NqYMu2roijslT1jhq6F0hW2dxMup9BX\", \"ixjU6mVATMnNEqika7NUaB31j88LVY2A6YjLEHucw7ZgrWQKx1BSSVeLnriqcd2c\", \"dFNSva8W3eBgRCzDTVJJwSVBoEvga9JMal060XDdnNyLPf6QG7ekhngaTzodv0xa\"]','KMHWVW(=okU#f0-%qp',NULL,'2006-08-15 00:00:00','2023-12-05','IVdtGpX(mIhr','2032-02-27 00:00:00',3301.944), ('[\"WrAozXSWcvC7Hnbgq4vNDcU5jwMzoKZtcSk0OlipDyk491C5d1ri3N8sO1LUSOBC\", \"QzZbKLELZ10yEICH9oTQBf9FVwjp5y4OSsgBj6UL1FY3TdBjxDaJgT4MsvTJkWdU\"]','UkTKplJyANc9YR*rYL8',NULL,'2002-08-07 00:00:00','2035-12-01','IVdtGpX(mIhr','2032-02-27 00:00:00',1109.6173), ('[\"oxAKGWC7k7PogXZfTmKYiS670eQRvWduXPIpNUq5Y6jedjC6mDpnvjbUyVESRo2m\", \"8zZy2e5vJ4lDQlu4y5ZeSPLfKqKqkdmtbmyfWLFQJsXSUgvaUmVgzKNP7MjTqLS4\", \"WbBnY7jSYxLfTY47lViSkgmUn7ayMJhSC6Ps0g7Qvc2JnTlz1Ox6rMPsedFl0Siy\"]','H89eUO$4TH7^iM',NULL,'1984-03-14 00:00:00','1979-06-02','IVdtGpX(mIhr','2032-02-27 00:00:00',5248.184), ('[\"GDdee9iMKf7hbKKaFnynAdGuA417MySKkXix6cuXDs1X1BX3KH5EnGLxl2w56zsR\", \"DiPKGTXLpCaPMMtTMBur4nvpT8YorvOGFYF6RrxUToEgBWuwjQqIb1iIjA4jG6oX\", \"FrD5l44c63JpQdLsGF6PcYTuRFKv6ZtFdtJttiU2XUQdGxf7OWW72ezUZoBZv2LD\", \"W0tpPorKjXLmDWUQ52srzr3lSj0zPEgtmIWQRsmAQUKUCqOl66huE4o6WwL8mJex\", \"4Ae0dzr0FSgJpuiF7ESJuIFPhOq3YerY1XNn8qQXGURcMzMgBSuQ1VVGwprDCn38\"]','8pF',NULL,'2029-03-20 00:00:00','2009-11-06','IVdtGpX(mIhr','2032-02-27 00:00:00',4824.3594), ('[\"1KrVjjerIeHrydkrGcz6QlsdphJwAesXAKnugOWkigdvvJWYoD4qc7tAmuZbjXcB\", \"K34r0aLLqVigVetI9CPUk12MMbGaUWEtL2OItOuqlovVCBb91jWhjXbeaa2NmxA4\", \"cEBqN4CmwgYQiMcjLjbqHnQjOR6ePqZVqYdYdHn0y9LN3H9QHhNvlnudiZMQaOQS\", \"YQwNQpJDQhkWMTpRXqA6d0UF8lqSxve3ThIRxurFYL83MeYnYvzI7012cbBJKPUi\", \"Z8Bsxm6B81DsDuU81I1zLkma5NWSa9YYJ3xcDHI6ioM2rI57TecAPG5V6ZFhavSe\"]','X40Veku',NULL,'2015-01-10 00:00:00','1979-05-27','IVdtGpX(mIhr','2032-02-27 00:00:00',6170.399), ('[\"d2B37AhgJJj0DS0g7ESf0NI6riSB6ybsrzRY45a9WcVXiRSj1AbSD4mDyNDus706\"]','Ya61yU',NULL,'1984-12-18 00:00:00','2035-07-13','IVdtGpX(mIhr','2032-02-27 00:00:00',9509.278), ('[\"j5uw41kvuU8B0b4fprgrJrWgvrDvjfOlWZBNAj9NubTne9BYq6NnIoO0RKs8Z0XH\"]','84ny$ExZu',NULL,'2007-02-12 00:00:00','2017-10-31','IVdtGpX(mIhr','2032-02-27 00:00:00',7418.3467), ('[\"unM9EPoWy0SoZZvOKXIrtgB29jIa4sT69QMqkgm5PUN7kG2pIbxKkA0rFksX2TTy\"]','x&MokfBw*mJW-k2M7u',NULL,'1993-08-22 00:00:00','2016-03-15','IVdtGpX(mIhr','2032-02-27 00:00:00',1897.0829), ('[\"7Deo1fnh75p0fxaDb3MP4MSvx75oQ9WH561SApYvEDGacLrn0GUqgZBysQPY6vvd\", \"mCDivPUr9KDs0jFOCKkHxR2wMA5urc9t35ECEup5zxuN8L5yR8G7E4EkkuHDjCek\"]','pe5UCbWx2A+!~U7gFQ',NULL,'2008-03-29 00:00:00','1973-11-20','IVdtGpX(mIhr','2032-02-27 00:00:00',1482.7887), ('[\"9LAEoi4SHNsFfMkyJIEJCqSvGRkWiX7mkx5sq8Oo1pMgaOt7k2wKKJFNWRddXI4D\", \"hbtRp77fp2DL5RuQIz9xor0cAixGHBieZZ1hEDS7yNRqsPJ3hJQ7KumO5HPqkSYA\", \"d70rVAUYO8iX6iWycnvElvy4ynXjkAiCzStFrKIwQBfx4EZc46FmqeAKx9YcPyMJ\"]','Mm-eHK*mL)(C~Fwz',NULL,'2007-02-06 00:00:00','1982-05-27','IVdtGpX(mIhr','2032-02-27 00:00:00',774.41284), ('[\"IDGYv6SPRs1J5HuHSqJPuSWSs8XCl1CcyBTQTBWgL3WyPkVMVGcSbfwcplxNCsjA\", \"zZ0CBKP0OkWbXaWdgdWLPyyV9qWuOu2JqskozwWvg4s1vTdlC5plbX1iN2WaklPc\"]','!',NULL,'2001-01-20 00:00:00','1998-11-19','IVdtGpX(mIhr','2032-02-27 00:00:00',7640.187), ('[\"PxqFQxDXDmkmV7cYp2d6RUCEIlA7a57TtzyipzY8vHsD9BDlNHxZPAxCMrtMWK9J\"]','BJF2xgem=dV~1OsquzU',NULL,'2006-05-22 00:00:00','1983-06-02','IVdtGpX(mIhr','2032-02-27 00:00:00',6061.8486), ('[\"QhtYmUVOoG7AEUlKJrQqyfH6HjRFMN8ZdZ4LQtBNe51YzRnNp82PxypMz9f1wmX7\", \"T3bMNI1c8Ie5PPKEkAzBq9lLiuyfXRSHIO5yHDu3qeM9YmUyG3sM2BbFLvZjwkn5\", \"rNtleSxoDvzskoLe3DHLSv51nXLJpNBf9kP5VcKcd6HGWsAXROMuw2SDrnadNIPU\"]','Kc8$FL4lsQ3',NULL,'1975-08-13 00:00:00','2020-03-16','IVdtGpX(mIhr','2032-02-27 00:00:00',2593.0342), ('[\"DaPT5QHGKYG5oQ9g9yz6aGSsBPgjkZ8vYVVgzX4ABhYkuzDx6jU5mpk0XHLh9oP3\", \"PwRHFOwxx3i1gCPg2CnnC6y5XNPQeGNysEl8VZi5hcsvvVU2PmuzMrpBjUviG2zs\", \"DETs1bMkdyGeLoMiz3RrNjgNWJmJog84FJMxy8I9O6yUZKVhEuuvAar892mpHMvb\", \"AKI15KuWtJatDDgI5Jlq6tDJ1kIOHVYRpyX8giRaxljrmy7lg4pJYHKurUfqcFFn\"]','WfzrlbFuW(IZ=hg',NULL,'1975-09-12 00:00:00','2007-08-26','IVdtGpX(mIhr','2032-02-27 00:00:00',893.053), ('[\"twxH0f4JfEVYC3bxNsBqM1RTlhazd3iG3ghJaib8hkiQzQLES7sEVbIBzb0OEloN\", \"TMRjxdpdZSvOCPJ4jbLBeYRWBW23M9ZtB4tIjRIrjy8wfdoTfPDSl7fXU4ZqG7gU\"]','6*6M',NULL,'1975-10-06 00:00:00','2002-02-23','IVdtGpX(mIhr','2032-02-27 00:00:00',1363.9156), ('[\"mWFrALNyYSUR17EnywGaMAaSAkPG5XaSRSzKcfsK0gsuk3JKl3K5ASdDq1rsLBSg\", \"mXf659nueUvs999QAUxjugC6cUMOlpFj9kjfgHUtIEmd3U2jBFAD8zcFF8elaY9L\"]','bQ_SB+ig-z0o',NULL,'2024-05-10 00:00:00','2024-06-13','IVdtGpX(mIhr','2032-02-27 00:00:00',3232.9312), ('[\"zQdxxlMfWVvIXXCaVSl11AxKX4m3fxB16POynB28HigCNUkHqeBRlkvr4nZo73fR\", \"WVEjSX1IqZjVOB6WdO4D9CGhw5dOqUu6G7j0ImxLajVRPeR9RC4WTC9TdeJbfBjj\", \"8sKgfRlLsp5bBBYD8mjE9AYC9ovyyGxxFQRDkeKcXESvnBuwJ0llzG0Y253BeSTw\", \"nrUV7BPoGg0Q6a1EvgwJb9kX9NnB7dVxBZ6lWtJODBfQy9jrDisvfhvbE5FlMmNJ\"]','7!PMY3Cp1fp4dwUIYt',NULL,'2022-03-23 00:00:00','2032-07-08','IVdtGpX(mIhr','2032-02-27 00:00:00',646.46375), ('[\"WztSsNSbN9Qy8pm2Y2jNkZywfZKaIBR8yP9A9Nf0fL9R4772vhpxk5QMaRV17U4p\", \"O6D835hKbH31pGeqDJSCqL59JCvWsdpoK7DKYTafBiiIEWL0qkeTajv8798Cqp01\", \"dSzC3mutqyY5QgnvKzCVTDxGZCmeDErakrPJawuNu21Dw5A0LtEwZNJKI5WyRJmi\", \"YmlzWyY49TiSzI2ADP5SQzxWRh821WpiBaKv6c7rjbqmqxE8QpdW4myHvdnC4RD8\", \"5p0nnhkRZ8hi4OUB0dVmvCz8j5LnMDCSgza76b4sAwDUTzeiSUoqvJB6I0jec8fn\"]','jezTv#y#8Cj!Y%cme+',NULL,'1991-03-11 00:00:00','2001-04-17','IVdtGpX(mIhr','2032-02-27 00:00:00',2699.9775), ('[\"j5qlKArjDTIKBiAQnpZXWPIxMx1n0wJVyYgHfMLYiF9oaHnsV5x8unYEbPJxEyfh\"]','7*lD^aMm&!',NULL,'1974-11-03 00:00:00','2019-04-01','IVdtGpX(mIhr','2032-02-27 00:00:00',208.04456), ('[\"1hkLSpQqZF6IfCOMEJcDdr6ZEEKqgnq7pSb5UMj85PNeJ96CBiZTJZKv87XalbqS\", \"0cTJHiugQYUgkdm094TwOj3sfMoU1U6AWLTIg8XbTBknXfNF7P6q8tWp1C7aKoci\", \"Y5wS5JybDviKf7Jb1qJphmAVVSZ17CCsNDKBDVmEzcAPBAHE2z3SWrFCWvxiquAG\", \"L5RVLjni5FvLo4pWcRAjcibwt8WD3bRY8aH5oOuLIkLtwiQRYG1nSgpen1H5IYEu\"]','w#5P~',NULL,'1973-08-17 00:00:00','1987-02-16','IVdtGpX(mIhr','2032-02-27 00:00:00',1603.7274), ('[\"UtGLouzB4HTlAgflkI1UdocKTTJc3cIfKBbkeY29bLsGvuaZvPOv6CujesBN2lpS\", \"tc1VIiCkucFrwxIAeXUi7k19ZAcZDBoXjDYL3QVBJ4fIuNbncLvqhBC6vSTYNgyN\", \"2NKUkuUQHmVIraxH1eSRcwu7BTEDGKxZDPcVjSRLWX1dshWN6fbStescCuEUXRDj\"]','kULK8&EmjZ*)5',NULL,'2024-06-06 00:00:00','2016-05-11','IVdtGpX(mIhr','2032-02-27 00:00:00',NULL), ('[\"KoHOK9KAvClIHrxcekkAJi433WPq0LcMtOt4rwMbsDcSyGTU0rKqtJrq1A9K55h1\", \"op9wV7Q8BOt2YPQECpU49dUzQP8iCF0XkDEIDTPZHLwb8Kuf2VeYvZovVkBirCYh\"]','VetyD9Rs9X4_w%%hwl',NULL,'2023-10-21 00:00:00','2020-05-22','IVdtGpX(mIhr','2032-02-27 00:00:00',2865.7642), ('[\"VoWNrwsVeizDGC7XBFveS0Pxcpbs79VZafWf4oY1msItWENbqW03Vg2zAc9Vouco\", \"SmTO3VPORKwKehLXRhEJl26J75NamGtXwDUbgSwzXmULlnSpzONm4oIHRz5uXeIx\", \"45Vyx7YFjqYOkZkLW7uZUxSHkePGqdIiNaQZ3RQF8Yliies689bWSChKmKYCXHAC\"]','0',NULL,'2027-06-20 00:00:00','2018-05-29','IVdtGpX(mIhr','2032-02-27 00:00:00',7566.442), ('[\"EdUirD9CisHmMAcEhf1r6he5I7IxAVOttGKI19edrBUeUBJnUwZXcOlWA0sEqp1a\", \"cUEaE5aKMLmWDNhsMrtxRJxsZVTiC0rAmgyUORdKUn48niwWKvZLGqVpvyfKHIOQ\", \"xz1eMweq4shhFMYHKipkH1uAU85A3uRKPsNwq0MGstZbhqZTw8u9ClnmPg11CRxJ\"]','I5xJd9Eb*ds_VST',x'','1972-07-27 00:00:00','2009-08-24','SFks@$13a-','2026-03-13 00:00:00',8840.267), ('[\"WxXtUDuhJ8ekElz2TDCKmOZwQn5tmMA7J7L4tByGGLCHb9MiDMrudlfNzBuPdbGj\", \"0Rm4rQl6r5QhAtzXfM4XQ0Rvpe2NIIv8wHsN6E445kOb5KNcGwHBF9ezz39y35Lq\", \"Fp5asLA8bhekMFWzTAAkHih9tHINfVpTmlvicMg5l3fIZMlit1Xu5lbHP1WY1BXE\"]','KFVBVvAdcVB',x'28696e624b6d2a364426336b78','1976-06-25 00:00:00','1984-06-09','-AQKeAz%dp_o@IbU','2031-06-20 00:00:00',5465.9937), ('[\"Z2no9YWGJZy27lRVApczWlk8A2S9Id280MkeHlIGvUJexZBc1W17i3vOXIyqP4qd\", \"SmOsvCumS5V37Zxj8CuNpdtpZANDOAFid5yG2uak2C6B6MRIh9oCGNq03nbQK1Zh\", \"OSrMSDTymuiZI4wOq0Uw9uiHR9yrz3FuDcLn1NpECeVJV5440qy6BP7xiOaSeKzQ\", \"5iyiSKae9M8J01XAcRq0bU4H1a29aesCQKXSe2s8OCJFk96V9cFtDLMlDM9ZABMH\", \"ZpkHnnrx1WgsbkOeCxNauZM1MlaCE6NuXQKMycZy8EUYYWOQMJZ08DTBD4c0Z4Ub\"]','vLF5QfI2LF',x'32532970684c65654c234a6d444666','2014-04-14 00:00:00','1979-08-02','d','1987-02-15 00:00:00',9501.778), ('[\"eiVIMHeeQMlkMdomw08dZ56SY27pygLedAhud1FHQnQd1by8vjzGyqcBUqc20ezY\", \"29tYqnHXpWZI4VR5xsiaCgseV2l94uB9v0KhfNkHis28NGB2QC1MWFLExHQqcMx3\", \"r5XJwki7YO6PXszmAOsnJoba26n2zVvzUOOrkHas5B2V5OQTNywpTVxDKmLrCoZE\", \"JvRmnMZqHLEee2GZBr8ejsToOhNj5TY4U6HBRfZGxwDRN3ZuaUu73dhL6iIO7dRJ\", \"HrD6cw1evA5oWXz8aiRqqgRuXRByt3LIdZsflEn1qGNdvYJSxWZEA5INX3788CEk\"]','5*WMPVC',x'5555','1990-07-06 00:00:00','1996-02-15','ri$6Vgz!YPY','1993-01-21 00:00:00',891.00543), ('[\"zOzHfnnrrDIT2EsuIAL20XsPqGJaUKWhQ496SUvUBz6nhdn3yDle9x15gUpYxOiW\", \"Zo3UJv0hxC0a90W84N2TH5yCX3ANk8GMQWEPx8VwMO3GP0cxbePAaeC7yY2baeBR\", \"R6Fq1mglpM7IHB9gGRqUGqSkOXjDqILG3pynSW1Tukd8D7QAvVM2yJjLMTkA4Rds\", \"wPOaqRYTgxsHhNq7Fm8aCZfpDkLFyO5631sfp5xxdo68Qsh7rlKjBiDWvCvnlaMy\", \"Nbm0u9rTWvHd7ETL2tuxq545ZB5jRYW3c40NoFJUnGIBZEFyX9tsZxgbzZ6EJ4oe\"]','D',x'75774d235f735878576251672b517847522b','2012-08-09 00:00:00','2010-04-29','Y__)','1996-03-24 00:00:00',1253.7045), ('[\"z88c8oUkZmH8pcf3d3v2xc5ULNML9uMpurtLmBTkd3VxVuGopwrmgxpXXDrAHTb9\"]','zYsnjWMp)NlcDf%w',x'4873384d723d747978543676577056594d','1985-04-29 00:00:00','2002-06-15','28U1bw5PPuKE@t','1990-10-01 00:00:00',6906.9634), ('[\"efjdMOR2te6JjuNFDpiDZdxxHzTM57KVBf8HMvJSVRLLlB0R6xd4v5LwVeOWQ2Kx\", \"oHNYAlLtbZNinKQN7Yjx2WG434Rx6UfkdlRfkqbJ789nkHt1Sdc5cgIc73Gc4dKn\"]','YzhzcpPDv',x'494a45564767412a26387a65','2007-11-23 00:00:00','1995-10-01','ackem3&Mn7hZ','2012-05-15 00:00:00',9152.317), ('[\"EQa6IqnVND5EpfZGrwy1w2uW2fSXQcfXBr53YBcrBIlfCRDS9glLRFFRYqtCbhFc\"]','sZdr',x'2d716b52472b4b6f4b79','2015-12-11 00:00:00','1977-01-22','d9ZZKu1)Vj2zi1','1999-12-12 00:00:00',2191.8223), ('[\"67RgCLQirk6sSN0ro9X19VWMLtKlQPozN67EXvXA8sS9Thf8jQFlKnCR5BPfkDdv\"]','HWXkQDF6jb(de',x'49485236','1991-03-13 00:00:00','2019-08-14','JsgZs','2025-09-28 00:00:00',959.7349), ('[\"0BBHhe6Y2jCVMVLB5eyNxtVS27QU4Q15lB2hr90ifHzdWdluBAnu1NqqKvOboDP4\"]','_d$ZqV&7SPL',x'2174','1980-02-05 00:00:00','2011-10-18','2-','1994-07-01 00:00:00',NULL), ('[\"hW1Vox7utxJcrkRYZen9k8o8us8AM9DfMyVP72AwNPmQhKY3O57Zx5rHuj0Rt35V\", \"7aKDBiNKPPw68tqPZ9VxTE5ptDa9Ln39kYnw33g4QM66NbB5aTu0XEc1T6biZMxt\"]','N0DiPczHkE9#A',x'2a2b6e522634594a484f5f50635e','1988-04-18 00:00:00','2028-04-18','MVdWHwe_6sJb9&UePA','2019-05-15 00:00:00',9742.141);

select /*+ inl_join(st_475) */ ucase( st_475.r4 ) as r0 , concat_ws(',', tc04ef7a8.col_6 , tc04ef7a8.col_3 ) as r1 , lower( tc04ef7a8.col_3 ) as r2 , ucase( st_475.r4 ) as r3 from tc04ef7a8 left join (select /*+  stream_agg() */ tl9d770ffc.col_4 as r0 , max(   tl9d770ffc.col_4 ) as r1 , tl9d770ffc.col_4 as r2 , count(   tl9d770ffc.col_4 ) as r3 , min(   tl9d770ffc.col_3 ) as r4 from tl9d770ffc where IsNull( tl9d770ffc.col_3 ) group by tl9d770ffc.col_4) st_475 on tc04ef7a8.col_4 = st_475.r0 order by r0,r1,r2,r3;

```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
ERROR 1105 (HY000): runtime error: index out of range [0] with length 0

```
github.com/pingcap/tidb/pkg/util/chunk.(*Column).GetInt64
	/workspace/source/tidb/pkg/util/chunk/column.go:644
github.com/pingcap/tidb/pkg/util/chunk.Row.GetInt64
	/workspace/source/tidb/pkg/util/chunk/row.go:56
github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).getHandle
	/workspace/source/tidb/pkg/executor/distsql.go:1307
github.com/pingcap/tidb/pkg/executor.(*tableWorker).executeTask
	/workspace/source/tidb/pkg/executor/distsql.go:1591
github.com/pingcap/tidb/pkg/executor.execTableTask
	/workspace/source/tidb/pkg/executor/distsql.go:1250
github.com/pingcap/tidb/pkg/executor.(*indexWorker).fetchHandles.func2
	/workspace/source/tidb/pkg/executor/distsql.go:1096
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by elsa0520**
### What problem does this PR solve?

Issue Number: close #60297

Problem Summary:

### What changed and how does it work?

The "indexjoin + streamagg + indexlookup + nocommonhandle" will trigger a panic in ISSUE.
The root cause is that when building the stream agg and push it into coptask, tidb miss the handlecolumns on the coptask and double read tablescan side.

The reason why the reset cop task needs to be specially modified here is that:
1. The cop task has been constructed in the **previous logic**, but it was not possible to determine whether the stream agg was needed (that is, whether keep order was true).
2. when updating the keep order, the relevant properties in the cop task need to be modified at the same time.

All reset code is copied from the logic when keep order is true in function **constructDS2IndexScanTask**.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
修复 indexjoin + streamagg 可能遇到的 panic 问题。
```

### CODE REVIEW

File: pkg/planner/core/exhaust_physical_plans.go [hunk 1]
```diff
@@ -1950,15 +1950,45 @@ func constructIndexJoinInnerSideTaskWithAggCheck(p *logicalop.LogicalJoin, prop
...
+			// The double read case should change the table plan together,
+			// so it need to find out the table scan
+			// Try to get the physical table scan from dsCopTask.tablePlan
+			// now, we only support the pattern tablescan and tablescan+selection
+			var physicalTableScan *PhysicalTableScan
+			if dsCopTask.tablePlan != nil {
+				physicalTableScan, _ = dsCopTask.tablePlan.(*PhysicalTableScan)
+				if physicalTableScan == nil && len(dsCopTask.tablePlan.Children()) == 1 {
+					physicalTableScan, _ = dsCopTask.tablePlan.Children()[0].(*PhysicalTableScan)
+				}
```
Comment (winoros) [inline pkg/planner/core/exhaust_physical_plans.go:1962]: Is there any other case? Projection or UnionScan?

Comment (elsa0520) [reply pkg/planner/core/exhaust_physical_plans.go:1962]: For now, there is no logic in the code.

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/core/exhaust_physical_plans.go [hunk 2]
```diff
@@ -1950,15 +1950,45 @@ func constructIndexJoinInnerSideTaskWithAggCheck(p *logicalop.LogicalJoin, prop
...
+				if physicalTableScan == nil {
+					goto buildHashAgg
```
Comment (winoros) [inline pkg/planner/core/exhaust_physical_plans.go:1964]: this case is the one that will not build agg. but the goto name is `buildHashAgg`. it's a little rediculous

File: pkg/planner/core/exhaust_physical_plans.go [hunk 3]
```diff
@@ -1950,15 +1950,45 @@ func constructIndexJoinInnerSideTaskWithAggCheck(p *logicalop.LogicalJoin, prop
 			if physicalIndexScan == nil && len(dsCopTask.indexPlan.Children()) == 1 {
 				physicalIndexScan, _ = dsCopTask.indexPlan.Children()[0].(*PhysicalIndexScan)
 			}
+			// The double read case should change the table plan together,
```
Comment (winoros) [inline pkg/planner/core/exhaust_physical_plans.go:1953]:
```suggestion
			// The double read case should change the table plan together if we want to build stream agg,
```

File: pkg/planner/core/exhaust_physical_plans.go [hunk 4]
```diff
@@ -1950,15 +1950,45 @@ func constructIndexJoinInnerSideTaskWithAggCheck(p *logicalop.LogicalJoin, prop
...
+			// so it need to find out the table scan
+			// Try to get the physical table scan from dsCopTask.tablePlan
+			// now, we only support the pattern tablescan and tablescan+selection
+			var physicalTableScan *PhysicalTableScan
+			if dsCopTask.tablePlan != nil {
+				physicalTableScan, _ = dsCopTask.tablePlan.(*PhysicalTableScan)
+				if physicalTableScan == nil && len(dsCopTask.tablePlan.Children()) == 1 {
+					physicalTableScan, _ = dsCopTask.tablePlan.Children()[0].(*PhysicalTableScan)
+				}
+				if physicalTableScan == nil {
```
Comment (winoros) [inline pkg/planner/core/exhaust_physical_plans.go:1963]:
```suggestion
				// We may not be able to build stream agg, break here and directly build hash agg
				if physicalTableScan == nil {
```

**Review by winoros — APPROVED** [review]
