### PR TITLE
planner: update the fundamental NDV scaling estimation formula 

### LINKED ISSUE #54812: planner: NDV scaling estimation formula is too naive
## Enhancement
Now our NDV estimation formula is too naive, for example, for the query `select distinct(a) from t where b=1`, we need to estimate `NDV(a)`, and now our formula is `NDV(a) = NDV_a_from_stats * Selectivity(b=1)`, which might cause a large estimation error.

Below is a concrete case:
```
create table t (a int, b int, key(a), key(b));
insert into t values (0, 1);
insert into t values (1, 1);
...
insert into t values (99, 1); -- 100 rows with b=1, (i, b)
insert into t values (100, 2);
insert into t values (100, 2);
...
insert into t values (100, 2); -- 1000 rows with b=2, (100, 2)
```

Then for the query above, to estimate `NDV(a)`, we use `NDV_a_from_stats * Selectivity(b=1) = 101 * 100/1100 = 9.18`, but the actual result is `100`:
```
mysql> explain analyze select distinct(a) from t where b=1;
+------------------------------+---------+---------+-----------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------+---------+
| id                           | estRows | actRows | task      | access object | execution info                                                                                                                                                                                                                                                                                                                                            | operator info                                                                 | memory     | disk    |
+------------------------------+---------+---------+-----------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------+---------+
| HashAgg_12                   | 9.18    | 100     | root      |               | time:1.2ms, loops:6, RU:0.487909, partial_worker:{wall_time:1.182167ms, concurrency:5, task_num:1, tot_wait:5.661418ms, tot_exec:83.708µs, tot_time:5.753293ms, max:1.162125ms, p95:1.162125ms}, final_worker:{wall_time:1.188667ms, concurrency:5, task_num:5, tot_wait:20.625µs, tot_exec:250ns, tot_time:5.854959ms, max:1.175125ms, p95:1.175125ms}   | group by:htktidb_test.t.a, funcs:firstrow(htktidb_test.t.a)->htktidb_test.t.a | 25.0 KB    | 0 Bytes |
| └─TableReader_13             | 9.18    | 100     | root      |               | time:1.06ms, loops:2, cop_task: {num: 1, max: 990.1µs, proc_keys: 0, copr_cache_hit_ratio: 0.00, build_task_duration: 20.8µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:1, total_time:955.3µs}}                                                                                                                                                 | data:HashAgg_5                                                                | 1009 Bytes | N/A     |
|   └─HashAgg_5                | 9.18    | 100     | cop[tikv] |               | tikv_task:{time:905.8µs, loops:0}                                                                                                                                                                                                                                                                                                                         | group by:htktidb_test.t.a,                                                    | N/A        | N/A     |
|     └─Selection_11           | 100.00  | 100     | cop[tikv] |               | tikv_task:{time:905.8µs, loops:0}                                                                                                                                                                                                                                                                                                                         | eq(htktidb_test.t.b, 1)                                                       | N/A        | N/A     |
|       └─TableFullScan_10     | 1100.00 | 100     | cop[tikv] | table:t       | tikv_task:{time:905.8µs, loops:0}                                                                                                                                                                                                                                                                                                                         | keep order:false                                                              | N/A        | N/A     |
+------------------------------+---------+---------+-----------+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------+------------+---------+
```

Another case is for Join Estimation: `select * from t1, t2 where t1.a=t2.a and t2.b=1`, for this case we might get a wrong estimation result of `NDV(t2.a)` and then finally get a wrong Join Plan.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #54812

Problem Summary: planner: update the fundamental NDV scaling estimation formula 

### What changed and how does it work?

The prior formula is too aggressive and biased, we'll use this new formula based on uniform assumption.
Please see more details on the comments of `ScaleNDV` function.

image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/sessionctx/vardef/tidb_vars.go [hunk 1]
```diff
@@ -1337,6 +1340,7 @@ const (
 	DefOptCorrelationExpFactor              = 1
 	DefOptRiskEqSkewRatio                   = 0.0
 	DefOptRiskRangeSkewRatio                = 0.0
+	DefOptRiskScaleNDVSkewRatio             = 1.0
```
Comment (qw4990) [inline pkg/sessionctx/vardef/tidb_vars.go:1349]: Keep the behavior unchanged in this PR, the default value should be 1.0.

File: pkg/planner/cardinality/ndv_test.go [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+		{10, 100, 80, 10.00},
+		{10, 100, 90, 10.00},
+	}
+	for _, tc := range cases {
+		newNDV := cardinality.ScaleNDV(tk.Session().GetSessionVars(), tc.OriginalNDV, tc.OriginalRows, tc.SelectedRows)
+		require.Equal(t, fmt.Sprintf("%.2f", tc.NewNDV), fmt.Sprintf("%.2f", newNDV), tc)
+	}
+}
+
+func TestIssue54812(t *testing.T) {
```
Comment (terry1purcell) [inline pkg/planner/cardinality/ndv_test.go:79]: Can this test use mock statistics rather than insert+analyze?

File: pkg/planner/cardinality/ndv_test.go [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+	tk.MustExec(`create table t (a int, b int, key(a), key(b));`)
+	for i := 0; i < 100; i++ {
+		tk.MustExec(fmt.Sprintf("insert into t values (%d, %d)", i, 1))
+	}
+	for i := 0; i < 1000; i++ {
+		tk.MustExec(fmt.Sprintf("insert into t values (%d, %d)", 100, 2))
+	}
+	tk.MustExec("analyze table t")
+	tk.MustExec(`set @@tidb_stats_load_sync_wait=100`)
+	tk.MustQuery(`explain select distinct(a) from t where b=1`).Check(testkit.Rows(
```
Comment (terry1purcell) [inline pkg/planner/cardinality/ndv_test.go]: Does this need to test the entire plan output? Can it just test the estimated rows?

Comment (qw4990) [reply pkg/planner/cardinality/ndv_test.go]: You're right, I've update it, now we only check the `estRows`.

File: pkg/planner/cardinality/ndv_test.go (hunk 2 above)
Comment (qw4990) [reply pkg/planner/cardinality/ndv_test.go:79]: It's hard to use mock-stats to construct some specific data distribution, and using SQL seems more clear and end-2-end, so I still use SQL here.
But I've combined these hundreds of `insert` into 2 to speed this test case up.

**Review by yudongusa — APPROVED** [review]
Please open a document PR

File: pkg/planner/cardinality/ndv_test.go [hunk 4]
```diff
@@ -12,18 +12,97 @@
...
 	"github.com/pingcap/tidb/pkg/expression"
+	"github.com/pingcap/tidb/pkg/planner/cardinality"
 	"github.com/pingcap/tidb/pkg/planner/property"
+	"github.com/pingcap/tidb/pkg/testkit"
 	"github.com/pingcap/tidb/pkg/util/mock"
 	"github.com/stretchr/testify/require"
 )
 
+func TestScaleNDV(t *testing.T) {
+	store, _ := testkit.CreateMockStoreAndDomain(t)
```
Comment (hawkingrei) [inline pkg/planner/cardinality/ndv_test.go]:
```suggestion
	store := testkit.CreateMockStore(t)
```

File: pkg/planner/cardinality/ndv_test.go [hunk 5]
```diff
@@ -12,18 +12,97 @@
...
+		{10, 100, 90, 10.00},
+	}
+	for _, tc := range cases {
+		newNDV := cardinality.ScaleNDV(tk.Session().GetSessionVars(), tc.OriginalNDV, tc.OriginalRows, tc.SelectedRows)
+		require.Equal(t, fmt.Sprintf("%.2f", tc.NewNDV), fmt.Sprintf("%.2f", newNDV), tc)
+	}
+}
+
+func TestOptScaleNDVSkewRatioSetVar(t *testing.T) {
+	store, _ := testkit.CreateMockStoreAndDomain(t)
```
Comment (hawkingrei) [inline pkg/planner/cardinality/ndv_test.go]:
```suggestion
	store := testkit.CreateMockStore(t)
```
