### PR TITLE
expression: fix panic of `explain for connection` when plan cache is enabled

### LINKED ISSUE #16110: Explaining for connection return runtime error after EXECUTE Statement
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

prepared-plan-cache.enabled=true;
```
use test;
drop table if exists t;
create table t(a int);
select connection_id();
prepare stmt from "select * from t where a=?";
set @a=1;
execute stmt using @a;
# explain for connection id;
```

### 2. What did you expect to see?
```
mysql> explain for connection 1;
+-------------------------+----------+-----------+---------------+--------------------------------+
| id                      | estRows  | task      | access object | operator info                  |
+-------------------------+----------+-----------+---------------+--------------------------------+
| TableReader_7           | 10.00    | root      |               | data:Selection_6               |
| └─Selection_6       | 10.00    | cop[tikv] |               | eq(test.t.a, 1)                |
|   └─TableFullScan_5 | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-------------------------+----------+-----------+---------------+--------------------------------+
```
### 3. What did you see instead?
```
mysql> explain for connection 1;
ERROR 1105 (HY000): runtime error: index out of range [0] with length 0
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-beta.2-151-g78922a8ab
Git Commit Hash: 78922a8abef2f21e4d8990d37c6c67ac7b0eef42
Git Branch: release-4.0
UTC Build Time: 2020-04-07 06:22:22
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close #16110  

Problem Summary:

`explain for connection` causes panic.

### What is changed and how it works?

What's Changed:
If plan cache is enabled, `Constant` in plan may refer to `ParamMarker`, which would be reset if other queries are executed, so `explain for connection` would panic when trying to access `PreapredParams`.

How it Works:

If we are in `explain for connection`, just use the pre-evaluated type and datum of the `Constant`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

N/A

### CODE REVIEW

File: expression/constant.go [hunk 1]
```diff
@@ -176,8 +176,13 @@ func (c *Constant) VecEvalJSON(ctx sessionctx.Context, input *chunk.Chunk, resul
 }
 
 func (c *Constant) getLazyDatum() (dt types.Datum, isLazy bool, err error) {
-	if c.ParamMarker != nil {
-		dt = c.ParamMarker.GetUserVar()
+	if p := c.ParamMarker; p != nil {
+		if p.ctx.GetSessionVars().StmtCtx.InExplainStmt {
+			// Since `ParamMarker` is not nil only in prepare/execute context, the query must be `explain for connection` when coming here.
+			// The PreparedParams may have been reset already, to avoid panic, we just use the pre-evaluated datum for this constant.
+			return
```
Comment (zz-jason) [inline expression/constant.go:183]:
```suggestion
			return dt, false, nil
```

maybe explicitly return a false `isLazy` is more readable?
