### PR TITLE
expression: fix incompatible result of `JSON_SEARCH()`

### LINKED ISSUE #20161: json_search result different from mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (
  id BIGINT,
  raw JSON
);

insert into test.t(id,raw) values(1,'["a","ab"]');
insert into test.t(id,raw) values(2,'["a"]');
insert into test.t(id) values(3);
```

```
SELECT JSON_SEARCH(raw,'one','c') FROM t;
```

### 2. What did you expect to see? (Required)
```
mysql> SELECT JSON_SEARCH(raw,'one','c') FROM t;
+----------------------------+
| JSON_SEARCH(raw,'one','c') |
+----------------------------+
| NULL                       |
| NULL                       |
| NULL                       |
+----------------------------+
3 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> SELECT JSON_SEARCH(raw,'one','c') FROM t;
+----------------------------+
| JSON_SEARCH(raw,'one','c') |
+----------------------------+
|                            |
|                            |
| NULL                       |
+----------------------------+
3 rows in set (0.01 sec)
```

the two blank is somewhat EMPTY

### 4. What is your TiDB version? (Required)

v4.0.6

### PR DESCRIPTION
**Pull request by elvizlai**
### What problem does this PR solve?

Issue Number: close #20161 

Problem Summary:

When search result isNull, need using AppendNull appended to result.

### Release note 

- Fix #20161, json search result null is not compatible with mysql

### CODE REVIEW

**Comment by elvizlai** [comment]
PTAL

File: expression/builtin_json_vec.go [hunk 1]
```diff
@@ -448,10 +448,14 @@ func (b *builtinJSONSearchSig) vecEvalJSON(input *chunk.Chunk, result *chunk.Col
 				pathExprs = append(pathExprs, pathExpr)
 			}
 		}
-		bj, _, err := jsonBuf.GetJSON(i).Search(containType, searchBuf.GetString(i), escape, pathExprs)
+		bj, isNull, err := jsonBuf.GetJSON(i).Search(containType, searchBuf.GetString(i), escape, pathExprs)
```
Comment (francis0407) [inline expression/builtin_json_vec.go:451]: Could you please add a unit test for this?

Comment (elvizlai) [reply expression/builtin_json_vec.go:451]: Any suggestions or guides for where to properly add this unit test? The origin presentation of this issue is JSON_SEARCH, but cause of this is from expression.

Comment (francis0407) [reply expression/builtin_json_vec.go:451]: PTAL @SunRunAway

Comment (SunRunAway) [reply expression/builtin_json_vec.go:451]: 1) Add cases [here](https://github.com/pingcap/tidb/blob/7cc2c700414d0ba6a71115538d3fcf523dfd40a1/expression/builtin_json_vec_test.go#L115), for comparing the results of `evalJSON` and `vecEvalJSON`.
2) integration test also can be added in [integration_test.go](https://github.com/pingcap/tidb/blob/5eaaa5c64909bd9f3833209e6b0d974d31f9917a/expression/integration_test.go)

Comment (elvizlai) [reply expression/builtin_json_vec.go:451]: PTAL

**Review by time-and-fate — COMMENTED** [review]
LGTM

**Review by rebelice — COMMENTED** [review]
LGTM

**Review by ichn-hu — DISMISSED** [review]
LGTM

**Comment by elvizlai** [comment]
PTAL

**Review by ichn-hu — APPROVED** [review]
LGTM

**Comment by ichn-hu** [comment]
@lzmhhh123 PTAL

**Comment by elvizlai** [comment]
friendly ping😁

**Review by XuHuaiyu — DISMISSED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by XuHuaiyu** [comment]
@elvizlai Please resolve the conflicts.

**Review by XuHuaiyu — APPROVED** [review]
