### PR TITLE
*: Enable plan cache for partitioned tables | tidb-test=pr/2273

### LINKED ISSUE #33031: return wrong results when using plan-cache and dynamic-mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepared-plan-cache.enabled = true
```
use test;
drop table if exists UK_RP17396;
CREATE TABLE `UK_RP17396` (
  `COL1` int(16) DEFAULT '29' COMMENT 'NUMERIC UNIQUE INDEX',
  `COL2` varchar(20) DEFAULT NULL,
  `COL4` datetime DEFAULT NULL,
  `COL3` bigint(20) DEFAULT NULL,
  `COL5` float DEFAULT NULL,
  UNIQUE KEY `UK_COL1` (`COL1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`COL1`)
(PARTITION `P0` VALUES LESS THAN (-1964648596),
 PARTITION `P1` VALUES LESS THAN (-1798171365),
 PARTITION `P2` VALUES LESS THAN (-224353317),
 PARTITION `P3` VALUES LESS THAN (74739562),
 PARTITION `P4` VALUES LESS THAN (330180811),
 PARTITION `P5` VALUES LESS THAN (1267470870));

insert into UK_RP17396 values(-556906299, "竂揿蜓锌璸籾珵岄浑祿恺鮘茷拦没盬饎醱僛橉", "9269-08-13 18:36:02", 363208857940760420, -1.28355e38);


set tidb_partition_prune_mode=static;
prepare stmt from 'select * from UK_RP17396 where col3 < ? and col1 in (?, ?, ?) and col2 != ?;';
set @a=4020185825752602279, @b=-4331, @c=-29749, @d=-13306, @e="AgHVfFsnfEO";
execute stmt using @a,@b,@c,@d,@e;
set @a=2972768264503339938, @b=5150, @c=-556906299, @d=1232847360, @e="=姵犵駘鏤ⱴȴ褋韨窷晢镸辈夁沶蚩皭兩隧撬";
execute stmt using @a,@b,@c,@d,@e;


set tidb_partition_prune_mode=dynamic;
prepare stmt from 'select * from UK_RP17396 where col3 < ? and col1 in (?, ?, ?) and col2 != ?;';
set @a=4020185825752602279, @b=-4331, @c=-29749, @d=-13306, @e="AgHVfFsnfEO";
execute stmt using @a,@b,@c,@d,@e;
set @a=2972768264503339938, @b=5150, @c=-556906299, @d=1232847360, @e="=姵犵駘鏤ⱴȴ褋韨窷晢镸辈夁沶蚩皭兩隧撬";
execute stmt using @a,@b,@c,@d,@e;
```
### 2. What did you expect to see? (Required)
```
MySQL [test]> execute stmt using @a,@b,@c,@d,@e;
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
| COL1       | COL2                                                         | COL4                | COL3               | COL5        |
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
| -556906299 | 竂揿蜓锌璸籾珵岄浑祿恺鮘茷拦没盬饎醱僛橉 | 9269-08-13 18:36:02 | 363208857940760420 | -1.28355e38 |
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
1 row in set (0.00 sec)

MySQL [test]>
MySQL [test]>
MySQL [test]> set tidb_partition_prune_mode=dynamic;
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> prepare stmt from 'select * from UK_RP17396 where col3 < ? and col1 in (?, ?, ?) and col2 != ?;';
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> set @a=4020185825752602279, @b=-4331, @c=-29749, @d=-13306, @e="AgHVfFsnfEO";
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> execute stmt using @a,@b,@c,@d,@e;
Empty set (0.01 sec)

;ySQL [test]> set @a=2972768264503339938, @b=5150, @c=-556906299, @d=1232847360, @e="=姵犵駘鏤ⱴȴ褋韨窷晢镸辈夁沶蚩皭兩隧撬"
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> execute stmt using @a,@b,@c,@d,@e;
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
| COL1       | COL2                                                         | COL4                | COL3               | COL5        |
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
| -556906299 | 竂揿蜓锌璸籾珵岄浑祿恺鮘茷拦没盬饎醱僛橉 | 9269-08-13 18:36:02 | 363208857940760420 | -1.28355e38 |
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+

1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```
MySQL [test]> execute stmt using @a,@b,@c,@d,@e;
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
| COL1       | COL2                                                         | COL4                | COL3               | COL5        |
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
| -556906299 | 竂揿蜓锌璸籾珵岄浑祿恺鮘茷拦没盬饎醱僛橉 | 9269-08-13 18:36:02 | 363208857940760420 | -1.28355e38 |
+------------+--------------------------------------------------------------+---------------------+--------------------+-------------+
1 row in set (0.00 sec)

MySQL [test]>
MySQL [test]>
MySQL [test]> set tidb_partition_prune_mode=dynamic;
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> prepare stmt from 'select * from UK_RP17396 where col3 < ? and col1 in (?, ?, ?) and col2 != ?;';
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> set @a=4020185825752602279, @b=-4331, @c=-29749, @d=-13306, @e="AgHVfFsnfEO";
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> execute stmt using @a,@b,@c,@d,@e;
Empty set (0.01 sec)

;ySQL [test]> set @a=2972768264503339938, @b=5150, @c=-556906299, @d=1232847360, @e="=姵犵駘鏤ⱴȴ褋韨窷晢镸辈夁沶蚩皭兩隧撬"
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> execute stmt using @a,@b,@c,@d,@e;
Empty set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v6.0.0-alpha-56-g9a4ca3c
Edition: Community
Git Commit Hash: 9a4ca3ca6919699fb4f0da72edd7151c56f84edd
Git Branch: master
UTC Build Time: 2022-03-11 01:02:55
GoVersion: go1.17.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### LINKED ISSUE #45532: Support `BatchPointGet` for Range and List Partition
## Enhancement
We could support  `BatchPointGet` plan for Range and List Partition and remove the code below. https://github.com/pingcap/tidb/blob/e68c8ff2a59817920b5ab7c1db4eb9a2ed7fff4c/planner/core/find_best_task.go#L1126-L1134

Some things need to consider,
1. https://github.com/pingcap/tidb/issues/45702
2. Explain info, like https://github.com/pingcap/tidb/issues/45888
3. https://github.com/pingcap/tidb/issues/45720
4. https://github.com/pingcap/tidb/issues/45889
5. https://github.com/pingcap/tidb/blob/6b536ae1cb5cf39e15008621df7907bce7a7a1fa/server/conn.go#L1875, `prefetchPointPlanKeys` function, not sure if this will affect.

Most test cases are added in `TestBatchPointGetTablePartition`, but please take care about all of them.

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #33031 , close #45532

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/plan_cacheable_checker.go [hunk 1]
```diff
@@ -658,7 +658,9 @@ func checkTableCacheable(ctx context.Context, sctx sessionctx.Context, schema in
 				return in, false // dynamic-mode for partition tables can use plan-cache
 			}
 		*/
-		return false, "query accesses partitioned tables is un-cacheable"
+		if sctx == nil || !sctx.GetSessionVars().IsDynamicPartitionPruneEnabled() {
```
Comment (qw4990) [inline pkg/planner/core/plan_cacheable_checker.go:661]: Should we introduce a `fix-control` as switch for safety? Then if there is any problem, the user can at least fall back to the previous behavior.
You can refer to this PR as an example: https://github.com/pingcap/tidb/pull/49754

File: pkg/expression/util.go [hunk 2]
```diff
@@ -1492,6 +1492,28 @@ func containMutableConst(ctx EvalContext, exprs []Expression) bool {
 	return false
 }
 
+// ReEvaluateParamMarkerConst updates all constants to their current ParamMarkers
+func ReEvaluateParamMarkerConst(ctx sessionctx.Context, exprs []Expression) error {
```
Comment (qw4990) [inline pkg/expression/util.go:1496]: Could we move this function into `plan_cache_utils.go` since it seems like only plan cache will use it?

Comment (qw4990) [reply pkg/expression/util.go:1496]: It seems like only the Plan Cache has the requirement to Re-Eval some expressions...

File: pkg/planner/core/plan_cache.go [hunk 3]
```diff
@@ -432,16 +437,28 @@ func rebuildRange(p Plan) error {
...
+		err = expression.ReEvaluateParamMarkerConst(sctx, x.PlanPartInfo.PruningConds)
+		if err != nil {
+			return err
+		}
 		err = rebuildRange(x.TablePlans[0])
 		if err != nil {
 			return err
 		}
 	case *PhysicalIndexReader:
+		err = expression.ReEvaluateParamMarkerConst(sctx, x.PlanPartInfo.PruningConds)
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:449]: Do we need to call `executor.partitionPruning` here, and update `PhysicalIndexReader.partitions`?

File: pkg/planner/core/plan_cache.go [hunk 4]
```diff
@@ -718,6 +848,15 @@ func buildRangeForIndexScan(sctx sessionctx.Context, is *PhysicalIndexScan) (err
 		return errors.New("rebuild to get an unsafe range")
 	}
 	is.Ranges = res.Ranges
+	if is.isPartition || (is.physicalTableID > 0 && is.physicalTableID != is.Table.ID) {
+		panic("static pruning mode, when dynamic prune mode is a must for plan cache?!?")
+	}
+	// PhysicalIndexScan will recalculate partition pruning, so no need to do it here!
+	// In executorBuilder.buildIndex{Reader|LookUpReader|MergeReader}
+	// Can PhysicalIndexScan plan be used without IndexReader/IndexLookupReader/MergeReader?
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:856]: The answer is no :D There is always a Reader (IndexReader/LookUp/Merge) on Scan

File: pkg/planner/core/plan_cache.go [hunk 5]
```diff
@@ -585,7 +660,62 @@ func rebuildRange(p Plan) error {
 				}
 			}
 		}
+		// TODO: fix TableDual!
+		if len(x.PartitionDefs) > 0 {
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:664]: Can we put the operation of updating PointGet.PartitionDef and BatchPointGet.PartitionDef to the executor builder?  Just like all other Readers, then they have the same process to handle partitioning tables: 1) Re-Eval some expressions at the optimization phase, 2) Re-Partition Prunning at the executor builder phase.

Comment (mjonss) [reply pkg/planner/core/plan_cache.go]: I have made a major code move/refactor to only re-evaluate the ParamMarkers in rebuildRange, and move the (re)partition pruning to the executor building phase.

By moving the partition pruning to the Executor building phase, several changes was needed:
- EXPLAIN now needs to build the executor, even if not EXPLAIN ANALYZE, to get the partition pruning correct.
- We can remove a lot of code for partition pruning for `[Batch]PointGet`, which only covered a smaller set of partitioning, and replace it with the more commonly used `GetPartition[Idx]ByRow()`/`LocatePartition()` functionality (which is used when you have the actual values to check which partition a row belongs to, and is used in the write path).

And some side effects happened:
- EXPLAIN now starts a transaction (to get the current schema version?)
- the [Batch]PointGet plan will be explained as PointGet with `partition:dual` instead of TableDual plan (the executor is still TableDual, but EXPLAIN uses the plan, not the executor)

I'm still updating test results for various test to reflect these changes, but before I'm done, I just wanted to check with you, @qw4990, if you think this is the right way?

**Comment by mjonss** [comment]
Also fixes #45532.

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 6]
```diff
@@ -1205,12 +1205,11 @@
       {
         "SQL": "select * from thash2 where a in (1,2) and b = 1 order by a desc",
         "DynamicPlan": [
-          "Sort 0.02 root  test.thash2.a:desc",
-          "└─TableReader 2.00 root partition:p1 data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:thash2 range:[1 1,1 1], [2 1,2 1], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:p1 data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:thash2 range:[1 1,1 1], [2 1,2 1], keep order:true, desc"
```
Comment (mjonss) [inline pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json:1209]: TODO: Why is sorting enabled in this PR, where did that happen?

**Comment by mjonss** [comment]
@tiancaiamao @qw4990 please take a new look, I have moved logic from the planner phase to the build executor phase, and also hade to build the executor for EXPLAIN.

So EXPLAIN will not show TableDual in case no matching partition, but partition:dual with the [Batch]PointGet plan instead.

I will continue do some minor cleanup and verify some more parts, but please take a new look to see if this is the right way for this PR.

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 7]
```diff
@@ -1253,15 +1252,14 @@
       {
         "SQL": "select * from thash2 where a = 1 and b in (1,2) order by b desc",
         "DynamicPlan": [
-          "Sort 0.02 root  test.thash2.b:desc",
-          "└─TableReader 2.00 root partition:p0,p1 data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:thash2 range:[1 1,1 1], [1 2,1 2], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:p0,p1 data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:thash2 range:[1 1,1 1], [1 2,1 2], keep order:true, desc"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR.

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 8]
```diff
@@ -1301,14 +1299,12 @@
       {
         "SQL": "select * from trange2 where a in (1,2) and b = 1 order by a desc",
         "DynamicPlan": [
-          "Sort 0.02 root  test.trange2.a:desc",
-          "└─TableReader 2.00 root partition:p0 data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:trange2 range:[1 1,1 1], [2 1,2 1], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:p0 data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:trange2 range:[1 1,1 1], [2 1,2 1], keep order:true, desc"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR.

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 9]
```diff
@@ -1405,14 +1400,12 @@
...
-          "  └─TableRangeScan 2.00 cop[tikv] table:tlist2 range:[1 1,1 1], [2 1,2 1], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:p0 data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:tlist2 range:[1 1,1 1], [2 1,2 1], keep order:true, desc"
         ],
         "StaticPlan": [
-          "Sort 0.02 root  test.tlist2.a:desc",
-          "└─TableReader 2.00 root  data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:tlist2, partition:p0 range:[1 1,1 1], [2 1,2 1], keep order:false, stats:pseudo"
+          "TableReader 2.00 root  data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:tlist2, partition:p0 range:[1 1,1 1], [2 1,2 1], keep order:true, desc"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR. Reverted the change in the test (failpoint vs analyze table).

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 10]
```diff
@@ -1832,22 +1824,19 @@
       {
         "SQL": "explain format='brief' select * from t3 where id in (1, 3)",
         "Plan": [
-          "TableReader 2.00 root partition:p0,p1 data:TableRangeScan",
-          "└─TableRangeScan 2.00 cop[tikv] table:t3 range:[1,1], [3,3], keep order:false, stats:pseudo"
+          "Batch_Point_Get 2.00 root table:t3, partition:p0,p1 handle:[1 3], keep order:false, desc:false"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR. Reverted the change in the test (failpoint vs analyze table).

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 11]
```diff
@@ -1832,22 +1824,19 @@
...
         ]
       },
       {
         "SQL": "explain format='brief' select * from t4 where (id, name_id) in ((1, 1), (3, 3))",
         "Plan": [
-          "IndexReader 2.00 root partition:p0,p1 index:IndexRangeScan",
-          "└─IndexRangeScan 2.00 cop[tikv] table:t4, index:id(id, name_id) range:[1 1,1 1], [3 3,3 3], keep order:false, stats:pseudo"
+          "Batch_Point_Get 2.00 root table:t4, partition:p0,p1, index:id(id, name_id) keep order:false, desc:false"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR. Reverted the change in the test (failpoint vs analyze table).

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 12]
```diff
@@ -1459,17 +1452,16 @@
       {
         "SQL": "select * from tlist2 where a = 1 and b in (1,2) order by b desc",
         "DynamicPlan": [
-          "Sort 0.02 root  test.tlist2.b:desc",
-          "└─TableReader 2.00 root partition:p0,p1 data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:tlist2 range:[1 1,1 1], [1 2,1 2], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:p0,p1 data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:tlist2 range:[1 1,1 1], [1 2,1 2], keep order:true, desc"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR. Reverted the change in the test (failpoint vs analyze table).

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 13]
```diff
@@ -1405,14 +1400,12 @@
       {
         "SQL": "select * from tlist2 where a in (1,2) and b = 1 order by a desc",
         "DynamicPlan": [
-          "Sort 0.02 root  test.tlist2.a:desc",
-          "└─TableReader 2.00 root partition:p0 data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:tlist2 range:[1 1,1 1], [2 1,2 1], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:p0 data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:tlist2 range:[1 1,1 1], [2 1,2 1], keep order:true, desc"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR. Reverted the change in the test (failpoint vs analyze table).

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 14]
```diff
@@ -1355,17 +1351,16 @@
       {
         "SQL": "select * from trange2 where a = 1 and b in (1,2) order by b desc",
         "DynamicPlan": [
-          "Sort 0.02 root  test.trange2.b:desc",
-          "└─TableReader 2.00 root partition:all data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:trange2 range:[1 1,1 1], [1 2,1 2], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:all data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:trange2 range:[1 1,1 1], [1 2,1 2], keep order:true, desc"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR. Reverted the change in the test (failpoint vs analyze table).

File: pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json [hunk 15]
```diff
@@ -1301,14 +1299,12 @@
...
-          "  └─TableRangeScan 2.00 cop[tikv] table:trange2 range:[1 1,1 1], [2 1,2 1], keep order:false, stats:pseudo"
+          "TableReader 2.00 root partition:p0 data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:trange2 range:[1 1,1 1], [2 1,2 1], keep order:true, desc"
         ],
         "StaticPlan": [
-          "Sort 0.02 root  test.trange2.a:desc",
-          "└─TableReader 2.00 root  data:TableRangeScan",
-          "  └─TableRangeScan 2.00 cop[tikv] table:trange2, partition:p0 range:[1 1,1 1], [2 1,2 1], keep order:false, stats:pseudo"
+          "TableReader 2.00 root  data:TableRangeScan",
+          "└─TableRangeScan 2.00 cop[tikv] table:trange2, partition:p0 range:[1 1,1 1], [2 1,2 1], keep order:true, desc"
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/partition/testdata/integration_partition_suite_out.json]: Change was due to replacing failpoint with analyze table, so not related to code changes in this PR. Reverted the change in the test (failpoint vs analyze table).

File: pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json [hunk 16]
```diff
@@ -188,16 +188,14 @@
       {
         "SQL": "explain select /*+ read_from_storage(tiflash[t3]) */ * from t3 where sala='a' and id =1; -- once hinted, walk with tiflash range scan",
         "Plan": [
-          "TableReader_11 0.01 root partition:p1 MppVersion: 2, data:ExchangeSender_10",
-          "└─ExchangeSender_10 0.01 mpp[tiflash]  ExchangeType: PassThrough",
-          "  └─TableRangeScan_9 1.00 mpp[tiflash] table:t3 range:[1 \"a\",1 \"a\"], keep order:false, stats:pseudo, PartitionTableScan:true"
+          "Point_Get_1 1.00 root table:t3, partition:p1, clustered index:PRIMARY(id, sala) "
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/casetest/enforcempp/testdata/enforce_mpp_suite_out.json:191]: When tested manually on latest master, it also give the Point_Get result, so not investigating further.

File: pkg/executor/merge_join_test.go [hunk 17]
```diff
@@ -286,13 +286,15 @@ func TestVectorizedShuffleMergeJoin(t *testing.T) {
 			`Shuffle 4150.01 root  execution info: concurrency:4, data sources:[TableReader TableReader]`,
 			fmt.Sprintf(`└─MergeJoin 4150.01 root  inner join, left key:test.%s.a, right key:test.%s.a`, t1, t2),
 			fmt.Sprintf(`  ├─Sort(Build) 3320.01 root  test.%s.a`, t2),
-			`  │ └─TableReader 3320.01 root  data:Selection`,
-			fmt.Sprintf(`  │   └─Selection 3320.01 cop[tikv]  lt(test.%s.b, 5), not(isnull(test.%s.a))`, t2, t2),
-			fmt.Sprintf(`  │     └─TableFullScan 10000.00 cop[tikv] table:%s keep order:false, stats:pseudo`, t2),
+			`  │ └─ShuffleReceiver 3320.01 root  `,
```
Comment (mjonss) [inline pkg/executor/merge_join_test.go:289]: FYI: This is added since the executor was now built as a part of explain, see change in `buildExplain()`

File: pkg/planner/core/plan_cache.go [hunk 18]
```diff
@@ -618,6 +663,28 @@ func rebuildRange(p Plan) error {
 	return nil
 }
 
+// reEvaluateParamMarkerConst updates all constants to their current ParamMarkers
+func reEvaluateParamMarkerConst(ctx PlanContext, exprs []expression.Expression) error {
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:667]: I can understand what this function is doing, but I'm not sure whether this operation is necessary.
It seems like we don't need to update `Constant.Value` manually, since when using or evaluating a `Constant`, it first checks whether it is a `Parameter` automatically:
image

What if we remove these `reEvaluateParamMakerConst` operations, will it cause any error?

File: pkg/planner/core/plan_cache.go [hunk 19]
```diff
@@ -516,17 +533,25 @@ func rebuildRange(p Plan) error {
...
+		}
 		// if access condition is not nil, which means it's a point get generated by cbo.
 		if x.AccessConditions != nil {
 			if x.IndexInfo != nil {
 				ranges, err := ranger.DetachCondAndBuildRangeForIndex(x.ctx, x.AccessConditions, x.IdxCols, x.IdxColLens, 0)
 				if err != nil {
 					return err
 				}
+				if len(ranges.Ranges) != len(x.IndexValues) {
+					// Previous run may have removed duplicates or non matching partitions
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:548]: In this case, we'd better generate a new plan rather than reusing the old one for safety.

File: pkg/planner/core/rule_partition_processor.go [hunk 20]
```diff
@@ -91,6 +91,7 @@ func (s *partitionProcessor) rewriteDataSource(lp LogicalPlan, opt *logicalOptim
 				children = append(children, us)
 			}
 			ua.SetChildren(children...)
+			ua.SCtx().GetSessionVars().StmtCtx.UseCache = false
```
Comment (qw4990) [inline pkg/planner/core/rule_partition_processor.go:94]: Please use `StmtCtx.SetSkipPlanCache` to set this flag.

File: pkg/planner/core/rule_partition_processor.go [hunk 21]
```diff
@@ -1799,6 +1803,7 @@ func (s *partitionProcessor) makeUnionAllChildren(ds *DataSource, pi *model.Part
 	}
 	s.checkHintsApplicable(ds, partitionNameSet)
 
+	ds.SCtx().GetSessionVars().StmtCtx.UseCache = false
```
Comment (qw4990) [inline pkg/planner/core/rule_partition_processor.go:1806]: Please use `StmtCtx.SetSkipPlanCache`

File: pkg/planner/core/plan_cache.go (hunk 18 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go:667]: Ah, now I see, since I replaced the old 'quick' [Batch]PointGet limited pruning, GetPhysID(), which used datum.GetInt64(), with the generic partitioned_table.GetPartition[Idx]ByRow() which uses Eval, I can now remove this.

I will remove this from the PR.

File: pkg/executor/point_get.go [hunk 22]
```diff
@@ -315,6 +333,24 @@ func (e *PointGetExecutor) Next(ctx context.Context, req *chunk.Chunk) error {
 					return err
 				}
 				tblID = pid
+				if len(e.partitionNames) > 0 {
+					found := false
+					for _, name := range e.partitionNames {
+						// TODO: create a map from id to partition definition index
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/executor/point_get.go]: I extracted it to a separate function, but I still think it could be useful to have a map for performance :)

File: pkg/executor/batch_point_get.go [hunk 23]
```diff
@@ -208,50 +209,23 @@ func (e *BatchPointGetExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
-}
-
 func (e *BatchPointGetExec) initialize(ctx context.Context) error {
 	var handleVals map[string][]byte
 	var indexKeys []kv.Key
 	var err error
 	batchGetter := e.batchGetter
 	rc := e.Ctx().GetSessionVars().IsPessimisticReadConsistency()
 	if e.idxInfo != nil && !isCommonHandleRead(e.tblInfo, e.idxInfo) {
-		// `SELECT a, b FROM t WHERE (a, b) IN ((1, 2), (1, 2), (2, 1), (1, 2))` should not return duplicated rows
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/executor/batch_point_get.go]: Added it back :) Can't remember why I removed it...

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 24]
```diff
@@ -1455,8 +1455,8 @@ func TestTruncatePartitionWithGlobalIndex(t *testing.T) {
 	tk3 := testkit.NewTestKit(t, store)
 	tk3.MustExec(`begin`)
 	tk3.MustExec(`use test`)
-	tk3.MustQuery(`select b from test_global use index(idx_b) where b = 15`).Check(testkit.Rows())
-	tk3.MustQuery(`select c from test_global use index(idx_c) where c = 15`).Check(testkit.Rows())
+	tk3.MustQuery(`select b from test_global use index(idx_b) where b = 15`).Check(testkit.Rows("15"))
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/ddl/tests/partition/db_partition_test.go]: This is during DeleteOnly state, where the global index is not yet reorganized/cleaned up. I added back code to block PointGet for this.

File: pkg/planner/core/plan_cache.go [hunk 25]
```diff
@@ -447,6 +448,12 @@ func rebuildRange(p Plan) error {
 			return err
 		}
 	case *PointGetPlan:
+		if x.TblInfo.GetPartitionInfo() != nil {
+			if fixcontrol.GetBoolWithDefault(sctx.GetSessionVars().OptimizerFixControl, fixcontrol.Fix33031, false) {
+				sctx.GetSessionVars().StmtCtx.UseCache = false
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:453]: Please use `stmtctx.SetSkipPlanCache` as well.

File: pkg/planner/core/plan_cache.go [hunk 26]
```diff
@@ -516,6 +517,10 @@ func rebuildRange(p Plan) error {
 		}
 		return nil
 	case *BatchPointGetPlan:
+		if x.TblInfo.GetPartitionInfo() != nil && fixcontrol.GetBoolWithDefault(sctx.GetSessionVars().OptimizerFixControl, fixcontrol.Fix33031, false) {
+			sctx.GetSessionVars().StmtCtx.UseCache = false
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:521]: Should use `SetSkipPlanCache`

File: pkg/planner/core/plan_cache.go [hunk 27]
```diff
@@ -553,7 +558,13 @@ func rebuildRange(p Plan) error {
 						return errors.New("rebuild to get an unsafe range")
 					}
 					for i := range ranges {
-						x.Handles[i] = kv.IntHandle(ranges[i].LowVal[0].GetInt64())
+						if i >= len(x.Handles) {
+							// Previous execution might have removed duplicates,
+							// so Handles are not the same length as HandleParams
+							x.Handles = append(x.Handles, kv.IntHandle(ranges[i].LowVal[0].GetInt64()))
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:564]: I recommend returning an unsafe-range error directly for safety. We've encountered some wrong result bugs caused by re-using wrong plans with unsafe-ranges, so better to return an error directly here.

File: pkg/planner/core/plan_cache.go [hunk 28]
```diff
@@ -568,13 +579,23 @@ func rebuildRange(p Plan) error {
 				if err != nil {
 					return err
 				}
-				x.Handles[i] = kv.IntHandle(iv)
+				if i >= len(x.Handles) {
+					// Previous execution might have removed duplicates,
+					// so Handles are not the same length as HandleParams
+					x.Handles = append(x.Handles, kv.IntHandle(iv))
```
Comment (qw4990) [inline pkg/planner/core/plan_cache.go:585]: Better to return an error directly for safety.

File: pkg/planner/core/plan_cache.go (hunk 25 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go:453]: I changed the calling function to use `SetSkipPlanCache` instead, so now only returning an error. If I would use `SetSkipPlanCache` here, it would duplicate the warnings otherwise.

File: pkg/planner/core/plan_cache.go (hunk 27 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go:564]: I just removed this, since the previous statement checks `if len(ranges) != len(x.Handles)` so it cannot happen here.

File: pkg/planner/core/plan_cache.go (hunk 28 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go:585]: Done by checking it before the loop.

File: pkg/planner/core/plan_cache.go (hunk 26 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go]: I will keep `UseCache = false`, since `SetSkipPlanCache` will also append a warning, which is already done if `rebuildRange` fails, like here. So to avoid duplicate warnings, I will keep this as-is.

File: pkg/planner/core/plan_cache.go (hunk 25 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go]: A bit too early, I will keep the `UseCache = false` here, and not changing the calling function to use `SetSkipPlanCache` instead of `AppendWarning`.

File: pkg/planner/core/plan_cache.go (hunk 27 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go]: I added a check and return an error in case `len(x.Handles) != len(x.HandleParams)`

File: pkg/planner/core/plan_cache.go (hunk 28 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go]: I added a check and return an error in case len(x.Handles) != len(x.HandleParams)

File: pkg/planner/core/plan_cache.go (hunk 25 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go]: We agreed on just remove the UseCache = false and accept possible duplicate warnings.

File: pkg/planner/core/plan_cache.go (hunk 26 above)
Comment (mjonss) [reply pkg/planner/core/plan_cache.go]: We agreed to remove the `UseCache = false` and only return an error, and accept possible duplicate warnings.

File: pkg/planner/core/point_get_plan.go [hunk 29]
```diff
@@ -544,6 +624,225 @@ func (p *BatchPointGetPlan) LoadTableStats(ctx sessionctx.Context) {
...
+	s := pi.Definitions[idx].Name.L
+	for _, name := range names {
+		if s == name.L {
+			return true
+		}
+	}
+	return false
+}
+
+// Map each index value to Partition ID
```
Comment (tiancaiamao) [inline pkg/planner/core/point_get_plan.go:640]: // Map each index value to Partition index

**Review by tiancaiamao — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
