### PR TITLE
domain: fix data race in the Domain.bindHandle

### LINKED ISSUE #38062: DATA RACE in the Domain.bindHandle
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c001e77ba0 by goroutine 141765:
  github.com/pingcap/tidb/domain.(*Domain).BindHandle()
      domain/domain.go:1371 +0x249
  github.com/pingcap/tidb/planner.getBindRecord()
      planner/optimize.go:516 +0x23a
  github.com/pingcap/tidb/planner.matchSQLBinding()
      planner/optimize.go:69 +0x92
  github.com/pingcap/tidb/planner.Optimize()
      planner/optimize.go:169 +0x93e
  github.com/pingcap/tidb/executor.(*Compiler).Compile()
      executor/compiler.go:98 +0x864
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2030 +0x7e4
  github.com/pingcap/tidb/session.(*session).ExecRestrictedSQL.func1()
      session/session.go:1955 +0x2b7
  github.com/pingcap/tidb/session.(*session).withRestrictedSQLExecutor()
      session/session.go:1941 +0x391
  github.com/pingcap/tidb/session.(*session).ExecRestrictedSQL()
      session/session.go:1945 +0x124
  github.com/pingcap/tidb/domain.(*Domain).refreshMDLCheckTableInfo()
      domain/domain.go:629 +0x421
  github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop()
      domain/domain.go:779 +0x17b
  github.com/pingcap/tidb/domain.(*Domain).Init.func9()
      domain/domain.go:1024 +0x64
Previous write at 0x00c001e77ba0 by goroutine 126611:
  github.com/pingcap/tidb/domain.(*Domain).LoadBindInfoLoop()
      domain/domain.go:1379 +0xe6
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:2782 +0x548
  github.com/pingcap/tidb/session.createStoreAndBootstrap()
      session/main_test.go:87 +0x64
  github.com/pingcap/tidb/session.TestANSISQLMode()
      session/bootstrap_test.go:414 +0x4a
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47
Goroutine 141765 (running) created at:
  github.com/pingcap/tidb/domain.(*Domain).Init()
      domain/domain.go:1024 +0x146d
  github.com/pingcap/tidb/session.(*domainMap).Get.func1()
      session/tidb.go:93 +0x6c4
  github.com/pingcap/tidb/util.RunWithRetry()
      util/misc.go:69 +0x93
  github.com/pingcap/tidb/session.(*domainMap).Get()
      session/tidb.go:76 +0x258
  github.com/pingcap/tidb/session.createSessionWithOpt()
      session/session.go:2894 +0x75
  github.com/pingcap/tidb/session.createSession()
      session/session.go:2890 +0x84
  github.com/pingcap/tidb/session.createSessions()
      session/session.go:2879 +0x6e
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:2755 +0x337
  github.com/pingcap/tidb/session.createStoreAndBootstrap()
      session/main_test.go:87 +0x64
  github.com/pingcap/tidb/session.TestANSISQLMode()
      session/bootstrap_test.go:414 +0x4a
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47
Goroutine 126611 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1726 +0xa84
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      testkit/testmain/wrapper.go:27 +0x42
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x59
  github.com/pingcap/tidb/session.TestMain()
      session/main_test.go:77 +0xe19
  main.main()
      bazel-out/k8-fastbuild/bin/session/session_test_/testmain.go:328 +0x5e8
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #38062

Problem Summary:

### Check List

Tests 

- [x] Unit test
enable race for unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: bindinfo/handle.go [hunk 1]
```diff
@@ -124,6 +124,25 @@ func NewBindHandle(ctx sessionctx.Context) *BindHandle {
 	return handle
 }
 
+// Reset is to reset the BindHandle and clean old info.
+func (h *BindHandle) Reset(ctx sessionctx.Context) {
```
Comment (Defined2014) [inline bindinfo/handle.go:128]: It likes similar with `NewBindHandle`, maybe could combine those two functions.

**Review by Defined2014 — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
