### PR TITLE
planner: fix limit in exists subquery will make TiDB plan not optimal

### LINKED ISSUE #34969: limit clause in `exists` subquery make TiDB plan not optimal
## Enhancement
```
mysql> desc test;
+-------+---------+------+------+---------+-------+
| Field | Type    | Null | Key  | Default | Extra |
+-------+---------+------+------+---------+-------+
| id    | int(11) | YES  |      | NULL    |       |
| value | int(11) | YES  |      | NULL    |       |
+-------+---------+------+------+---------+-------+
2 rows in set (0.00 sec)

mysql> explain select count(*) from test t1 where exists (select value from test t2 where t1.id = t2.id limit 1);
+------------------------------------+---------+--------------+---------------+--------------------------------+
| id                                 | estRows | task         | access object | operator info                  |
+------------------------------------+---------+--------------+---------------+--------------------------------+
| StreamAgg_14                       | 1.00    | root         |               | funcs:count(1)->Column#7       |
| └─Apply_36                         | 2.00    | root         |               | CARTESIAN semi join            |
|   ├─TableReader_20(Build)          | 2.00    | root         |               | data:TableFullScan_19          |
|   │ └─TableFullScan_19             | 2.00    | cop[tiflash] | table:t1      | keep order:false, stats:pseudo |
|   └─Limit_23(Probe)                | 0.00    | root         |               | offset:0, count:1              |
|     └─TableReader_34               | 0.00    | root         |               | data:ExchangeSender_33         |
|       └─ExchangeSender_33          | 0.00    | mpp[tiflash] |               | ExchangeType: PassThrough      |
|         └─Limit_32                 | 0.00    | mpp[tiflash] |               | offset:0, count:1              |
|           └─Selection_31           | 0.00    | mpp[tiflash] |               | eq(test.test.id, test.test.id) |
|             └─TableFullScan_30     | 2.00    | mpp[tiflash] | table:t2      | keep order:false, stats:pseudo |
+------------------------------------+---------+--------------+---------------+--------------------------------+
10 rows in set (0.00 sec)

mysql> explain select count(*) from test t1 where exists (select value from test t2 where t1.id = t2.id);
+----------------------------------------+---------+--------------+---------------+---------------------------------------------------+
| id                                     | estRows | task         | access object | operator info                                     |
+----------------------------------------+---------+--------------+---------------+---------------------------------------------------+
| StreamAgg_15                           | 1.00    | root         |               | funcs:count(1)->Column#7                          |
| └─TableReader_45                       | 1.60    | root         |               | data:ExchangeSender_44                            |
|   └─ExchangeSender_44                  | 1.60    | mpp[tiflash] |               | ExchangeType: PassThrough                         |
|     └─HashJoin_42                      | 1.60    | mpp[tiflash] |               | semi join, equal:[eq(test.test.id, test.test.id)] |
|       ├─ExchangeReceiver_23(Build)     | 2.00    | mpp[tiflash] |               |                                                   |
|       │ └─ExchangeSender_22            | 2.00    | mpp[tiflash] |               | ExchangeType: Broadcast                           |
|       │   └─Selection_21               | 2.00    | mpp[tiflash] |               | not(isnull(test.test.id))                         |
|       │     └─TableFullScan_20         | 2.00    | mpp[tiflash] | table:t2      | keep order:false, stats:pseudo                    |
|       └─Selection_19(Probe)            | 2.00    | mpp[tiflash] |               | not(isnull(test.test.id))                         |
|         └─TableFullScan_18             | 2.00    | mpp[tiflash] | table:t1      | keep order:false, stats:pseudo                    |
+----------------------------------------+---------+--------------+---------------+---------------------------------------------------+
10 rows in set (0.00 sec)

```
Currently, if the subquery of `exists` contains a limit clause, TiDB will choose `Apply` instead of `Join`, compared to `Join`, `Apply` is much slower, considering that the limit clause in `exists` subquery is always redundant, I think optimizer should rewrite `select count(*) from test t1 where exists (select value from test t2 where t1.id = t2.id limit 1)` to `select count(*) from test t1 where exists (select value from test t2 where t1.id = t2.id)` and generate a better plan.

### PR DESCRIPTION
**Pull request by dayicklp**
### What problem does this PR solve?

Issue Number: close #34969

Problem Summary:
At present, when there is a `limit` in the subquery of `exists`, the execution plan is not optimal. You can refer to [issue#34969](https://github.com/pingcap/tidb/issues/34969). The main reason is that the `limit` is not filtered in the subquery.
### What is changed and how it works?
In the `optimize` of `rule_decorrelate`, we added the filter for `limit`.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix limit in exists subquery will make TiDB plan not optimal
```

### CODE REVIEW

File: planner/core/rule_decorrelate.go [hunk 1]
```diff
@@ -189,6 +189,13 @@ func (s *decorrelateSolver) optimize(ctx context.Context, p LogicalPlan, opt *lo
 			}
 			appendRemoveProjTraceStep(apply, proj, opt)
 			return s.optimize(ctx, p, opt)
+		} else if li, ok := innerPlan.(*LogicalLimit); ok {
+			if li.Offset == 0 {
```
Comment (winoros) [inline planner/core/rule_decorrelate.go:193]: Add some comments here about why we could apply the rule and why we should only consider the `offset=0`

**Comment by dayicklp** [comment]
Here I need to see if the Apply and TopN test cases need to be modified

File: planner/core/rule_decorrelate.go (hunk 1 above)
Comment (dayicklp) [reply planner/core/rule_decorrelate.go]: Add some comments

File: planner/core/rule_decorrelate.go [hunk 2]
```diff
@@ -189,6 +189,24 @@ func (s *decorrelateSolver) optimize(ctx context.Context, p LogicalPlan, opt *lo
 			}
 			appendRemoveProjTraceStep(apply, proj, opt)
 			return s.optimize(ctx, p, opt)
+		} else if li, ok := innerPlan.(*LogicalLimit); ok {
+			//If offset is not zero, subquery will become always true or always false. This scenario optimizer has internal optimizations.
```
Comment (winoros) [inline planner/core/rule_decorrelate.go:193]: This comment should be put at `if li.Offset = 0`.
And there should be a space between the `//` and the first char.

File: planner/core/rule_decorrelate.go [hunk 3]
```diff
@@ -189,6 +189,24 @@ func (s *decorrelateSolver) optimize(ctx context.Context, p LogicalPlan, opt *lo
...
+			//If apply is not SemiJoin, innerplan which is limit will expand the join result.
+			if apply.JoinType != SemiJoin && apply.JoinType != LeftOuterSemiJoin && apply.JoinType != AntiSemiJoin && apply.JoinType != AntiLeftOuterSemiJoin {
+				// TODO: Actually, it can be optimized. We need to keep the APPLY can be decorrelated.
```
Comment (winoros) [inline planner/core/rule_decorrelate.go:196]: Would we need this TODO?

File: planner/core/rule_decorrelate.go [hunk 4]
```diff
@@ -377,6 +395,16 @@ func appendRemoveMaxOneRowTraceStep(m *LogicalMaxOneRow, opt *logicalOptimizeOp)
 	opt.appendStepToCurrent(m.ID(), m.TP(), reason, action)
 }
 
+func appendRemoveLimitTraceStep(limit *LogicalLimit, opt *logicalOptimizeOp) {
+	action := func() string {
+		return fmt.Sprintf("%v_%v removed from plan tree", limit.TP(), limit.ID())
+	}
+	reason := func() string {
+		return ""
```
Comment (winoros) [inline planner/core/rule_decorrelate.go:403]: Add the reason for the optimization.

File: planner/core/rule_decorrelate.go [hunk 5]
```diff
@@ -189,6 +189,24 @@ func (s *decorrelateSolver) optimize(ctx context.Context, p LogicalPlan, opt *lo
 			}
 			appendRemoveProjTraceStep(apply, proj, opt)
 			return s.optimize(ctx, p, opt)
+		} else if li, ok := innerPlan.(*LogicalLimit); ok {
+			//If offset is not zero, subquery will become always true or always false. This scenario optimizer has internal optimizations.
+			//If apply is not SemiJoin, innerplan which is limit will expand the join result.
```
Comment (winoros) [inline planner/core/rule_decorrelate.go:194]:
```suggestion
			// If apply is not SemiJoin, the output of it might be expanded even though we are `limit 1`.
```

**Review by winoros — COMMENTED** [review]
We also need to add the test mentioned in the issue.

File: planner/core/rule_decorrelate.go (hunk 3 above)
Comment (dayicklp) [reply planner/core/rule_decorrelate.go]: Delete this TODO comment.

File: planner/core/rule_decorrelate.go (hunk 1 above)
Comment (dayicklp) [reply planner/core/rule_decorrelate.go]: > We also need to add the test mentioned in the issue.

add this test which mentioned.

File: planner/core/rule_decorrelate.go [hunk 6]
```diff
@@ -189,6 +189,24 @@ func (s *decorrelateSolver) optimize(ctx context.Context, p LogicalPlan, opt *lo
...
+			// e.g. select count(*) from test t1 where exists (select value from test t2 where t1.id = t2.id limit 1); When using 'limit' in subquery, the plan will not optimal.
+			// If apply is not SemiJoin, the output of it might be expanded even though we are `limit 1`.
+			if apply.JoinType != SemiJoin && apply.JoinType != LeftOuterSemiJoin && apply.JoinType != AntiSemiJoin && apply.JoinType != AntiLeftOuterSemiJoin {
+				goto NoOptimize
+			}
+			// If subquery has some filter condition, we will not optimize limit.
+			if len(apply.LeftConditions) > 0 || len(apply.RightConditions) > 0 || len(apply.OtherConditions) > 0 || len(apply.EqualConditions) > 0 {
+				goto NoOptimize
+			}
+			// If offset is not zero, subquery will become always true or always false. This scenario optimizer has internal optimizations.
```
Comment (AilinKid) [inline planner/core/rule_decorrelate.go:203]: better refine the comment here (eg: limit with non-0 offset will conduct an impact of itself on the final result set from its sub-child, consequently determining the bool value of the Exist subq)

File: planner/core/testdata/integration_suite_in.json [hunk 7]
```diff
@@ -288,6 +288,15 @@
       "explain format = 'brief' select * from t where exists (select 1 from t t1 join t t2 on t1.a = t2.a and t1.a = t.a)"
     ]
   },
+  {
+    "name": "TestDecorrelateLimitInSubquery",
+    "cases": [
+      // Query with EXISTS and subquery with LIMIT should have the same plan, i.e, the Limit has been decorrelated.
+      "explain format = 'brief' select count(*) from test t1 where exists (select value from test t2 where t1.id = t2.id limit 1)",
+      "explain format = 'brief' select count(*) from test t1 where exists (select value from test t2 where t1.id = t2.id)",
+      "explain format = 'brief' select * from t where 9 in (select c from t s where s.c < t.c limit 3)"
```
Comment (AilinKid) [inline planner/core/testdata/integration_suite_in.json:297]: you can add an offset case

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

File: planner/core/rule_decorrelate.go (hunk 6 above)
Comment (dayicklp) [reply planner/core/rule_decorrelate.go]: well done

**Review by AilinKid — APPROVED** [review]
