### PR TITLE
statistics: fix wrong singleflight implementation for stats' syncload

### LINKED ISSUE #52294: wrong singleflight implementation for stats' syncload
## Bug Report

image
We use the `setWorking` for sync load's duplicate task detection.
image
It will return a boolean value directly after it finds duplicates.
image
And we can see that the `writeToResultChan` also returns directly by writing an ok result to the `resultCh`.

So the duplicated task will directly return without waiting for the executing one to finish.

As a result, if there are two TiDB nodes and we run sysbench's select_random_points with more than 2 threads, we will find out the following slow query:
image
The sync load doesn't timeout but we still have the SQLs executed without stats.
Such a slow query would disappear if the thread number is equal to or less than 2.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #52294

Problem Summary:

### What changed and how does it work?

the problem has been described in the issue. we refactor the singleflight using the golang official library.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/syncload/stats_syncload.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ func NewStatsSyncLoad(statsHandle statstypes.StatsHandle) statstypes.StatsSyncLo
 	s.StatsLoad.SubCtxs = make([]sessionctx.Context, cfg.Performance.StatsLoadConcurrency)
 	s.StatsLoad.NeededItemsCh = make(chan *statstypes.NeededItemTask, cfg.Performance.StatsLoadQueueSize)
 	s.StatsLoad.TimeoutItemsCh = make(chan *statstypes.NeededItemTask, cfg.Performance.StatsLoadQueueSize)
-	s.StatsLoad.WorkingColMap = map[model.TableItemID][]chan stmtctx.StatsLoadResult{}
+	//s.StatsLoad.WorkingColMap = map[model.TableItemID][]chan stmtctx.StatsLoadResult{}
```
Comment (elsa0520) [inline pkg/statistics/handle/syncload/stats_syncload.go:51]: Remove it directly

File: pkg/statistics/handle/types/interfaces.go [hunk 2]
```diff
@@ -375,8 +376,9 @@ type NeededItemTask struct {
 type StatsLoad struct {
 	NeededItemsCh  chan *NeededItemTask
 	TimeoutItemsCh chan *NeededItemTask
-	WorkingColMap  map[model.TableItemID][]chan stmtctx.StatsLoadResult
-	SubCtxs        []sessionctx.Context
+
+	Singleflight singleflight.Group
```
Comment (elsa0520) [inline pkg/statistics/handle/types/interfaces.go:380]: Could you please add some comment for this param?

Comment (hawkingrei) [reply pkg/statistics/handle/types/interfaces.go]: I have updated the comment.

File: pkg/statistics/handle/syncload/stats_syncload.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/statistics/handle/syncload/stats_syncload.go]: removed.

File: pkg/parser/model/model.go [hunk 3]
```diff
@@ -1786,6 +1786,11 @@ type TableItemID struct {
 	IsSyncLoadFailed bool
 }
 
+// Key is used to generate unique key for TableItemID to use in the syncload
+func (t TableItemID) Key() string {
+	return fmt.Sprintf("%d%d%t%t", t.ID, t.TableID, t.IsIndex, t.IsSyncLoadFailed)
```
Comment (winoros) [inline pkg/parser/model/model.go:1791]: Use some char like `#` or `-` as the separator, both `t.id=1&t.tableid=11` and `t.id=11&t.tableid=1` will map to `111`.
And we don't need the `is sync load failed` as the key. But we need one more field to tell whether it's a meta load or a full load.

Comment (hawkingrei) [reply pkg/parser/model/model.go]: Updated.

**Review by winoros — APPROVED** [review]

**Comment by hawkingrei** [comment]
@elsa0520 @hi-rustin PTAL

**Review by tangenta — APPROVED** [review]

File: pkg/statistics/handle/syncload/stats_syncload.go [hunk 4]
```diff
@@ -231,24 +230,45 @@ func (s *statsSyncLoad) HandleOneTask(sctx sessionctx.Context, lastTask *statsty
...
+	})
+	timeout := time.Until(task.ToTimeout)
+	select {
+	case result := <-resultChan:
+		if result.Err == nil {
+			slr := *(result.Val.(*stmtctx.StatsLoadResult))
+			if slr.Error != nil {
+				return task, slr.Error
+			}
+			task.ResultCh <- slr
```
Comment (hi-rustin) [inline pkg/statistics/handle/syncload/stats_syncload.go:244]: How about
```suggestion
			slr := result.Val.(*stmtctx.StatsLoadResult)
			if slr.Error != nil {
				return task, slr.Error
			}
			task.ResultCh <- *slr
```

This can help us to simplify this assessment code.

File: pkg/statistics/handle/syncload/stats_syncload_test.go [hunk 5]
```diff
@@ -207,17 +207,14 @@ func TestConcurrentLoadHistWithPanicAndFail(t *testing.T) {
...
-		require.Nil(t, task2)
-
 		require.NoError(t, failpoint.Disable(fp.failPath))
 		task3, err3 := h.HandleOneTask(testKit.Session().(sessionctx.Context), task1, exitCh)
 		require.NoError(t, err3)
 		require.Nil(t, task3)
 
-		require.Len(t, stmtCtx1.StatsLoad.ResultCh, 1)
-		require.Len(t, stmtCtx2.StatsLoad.ResultCh, 1)
+		task, err3 := h.HandleOneTask(testKit.Session().(sessionctx.Context), nil, exitCh)
```
Comment (hi-rustin) [inline pkg/statistics/handle/syncload/stats_syncload_test.go:215]: Does this change cover the issue? Or is it just a refactoring?

**Review by elsa0520 — APPROVED** [review]
LGTM

File: pkg/statistics/handle/syncload/stats_syncload_test.go (hunk 5 above)
Comment (hawkingrei) [reply pkg/statistics/handle/syncload/stats_syncload_test.go:215]: It is refactoring. the old one is wrong.

Comment (hawkingrei) [reply pkg/statistics/handle/syncload/stats_syncload_test.go:215]: checking length of the channel is unnecessay.
