### PR TITLE
statistics: add cache for handleGlobalStats's load data

### LINKED ISSUE #47247: statistics: there is a 22% performance regression in ANALYZE table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster with 1 tidb + 6tikv + 2tiflash
2. restore data of ossinsight (nearly 650GB, with partition tables)
3. analyze all the tables of the ossinsight database

### 2. What did you expect to see? (Required)
No performance regression
### 3. What did you see instead (Required)

image

### 4. What is your TiDB version? (Required)

good commit: https://github.com/pingcap/tidb/pull/47132
bad commit: https://github.com/pingcap/tidb/pull/47037

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #47247

Problem Summary:

### What is changed and how it works?

we need to handGlobalStats with index and without index. so we need to add cache here. to avoid load data twice.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

the benchmark result is from benchbot. 

this pr: 416.19412s
the old: 479.01944s

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: statistics/handle/globalstats/global_stats.go [hunk 1]
```diff
@@ -80,9 +80,15 @@ func MergePartitionStats2GlobalStats(
 	globalTableInfo *model.TableInfo,
 	isIndex bool,
 	histIDs []int64,
+	allPartitionStats map[int64]*statistics.Table,
 	getTableByPhysicalIDFn getTableByPhysicalIDFunc,
 	loadTablePartitionStatsFn loadTablePartitionStatsFunc,
```
Comment (qw4990) [inline statistics/handle/globalstats/global_stats.go:85]: Can we wrap it as a closure function outside:
image

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM
