### PR TITLE
planner: report error for invalid window specs which are not used

### LINKED ISSUE #12356: Window Function: not report error when a illegal windown not use (inconsistent with mysql)
## Bug Report

1. What did you do?

```sql
create table temptest (val int, val1 int);

SELECT val FROM temptest WINDOW w AS (ORDER BY val, val1 RANGE 1 PRECEDING);
```

Note that there have an unuse window `w` in select


2. What did you expect to see?

In Mysql 8.0.16

```sql
mysql> create table temptest (val int, val1 int);
Query OK, 0 rows affected (0.05 sec)

mysql> SELECT val FROM temptest WINDOW w AS (ORDER BY val, val1 RANGE 1 PRECEDING);
ERROR 3587 (HY000): Window 'w' with RANGE N PRECEDING/FOLLOWING frame requires exactly one ORDER BY expression, of numeric or temporal type
```

3. What did you see instead?

In TiDB

```sql
mysql> create table temptest (val int, val1 int);
Query OK, 0 rows affected (0.16 sec)

mysql> SELECT val FROM temptest WINDOW w AS (ORDER BY val, val1 RANGE 1 PRECEDING);
Empty set (0.01 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```sql
mysql> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                       |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.3
Git Commit Hash: 836982c617fbaa42d74616eb9ba9ed4cae46c46b
Git Branch: HEAD
UTC Build Time: 2019-08-30 02:42:42
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #12356 

Problem Summary: Didn't check for invalid window specs if they are not used in window functions.

### What is changed and how it works?

- Add new clause codes `windowOrderBy`, `partitionBy`.
- Modify `groupWindowFuncs` to store unused named window specs.
- Check for unused named window specs in `buildWindowFunctions`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- Report error for invalid window specifications which are not used in window functions.

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -4613,38 +4641,60 @@ func (b *PlanBuilder) checkOriginWindowSpecs(funcs []*ast.WindowFuncExpr, orderB
...
 		}
+	}
+	return nil
+}
 
-		err := b.checkOriginWindowFrameBound(&start, spec, orderByItems)
+// checkWindowSpecs checks the validity for named window specifications.
+func (b *PlanBuilder) checkWindowSpecs(ctx context.Context, p LogicalPlan, aggMap map[*ast.AggregateFuncExpr]int) error {
+	for _, spec := range b.windowSpecs {
+		_, _, orderBy, _, err := b.buildProjectionForWindow(ctx, p, spec, nil, aggMap)
```
Comment (lzmhhh123) [inline planner/core/logical_plan_builder.go:4654]: Is there any method to avoid redundantly rebuild projection?

Comment (dyzsr) [reply planner/core/logical_plan_builder.go:4654]: Let me try another approach.

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -4809,6 +4854,17 @@ func (b *PlanBuilder) groupWindowFuncs(windowFuncs []*ast.WindowFuncExpr) (map[*
...
+	// so we add them to `groupedWindow` with empty window functions.
+	for _, spec := range b.windowSpecs {
+		if _, ok := groupedWindow[spec]; ok {
+			continue
+		}
+		if _, ok := updatedSpecMap[spec.Name.L]; ok {
+			continue
+		}
+		groupedWindow[spec] = []*ast.WindowFuncExpr{}
+	}
```
Comment (lzmhhh123) [inline planner/core/logical_plan_builder.go:4867]: How about check whether the array is `nil` in `buildWindowFunctions` rather than set an empty array here?

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by winoros — COMMENTED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
