### PR TITLE
ddl: stablize testSerialSuite.TestCancelAddIndexPanic

### LINKED ISSUE #16548: serial_test.go:testSerialSuite.TestCancelAddIndexPanic failed
serial_test.go:testSerialSuite.TestCancelAddIndexPanic

Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/32872/display/redirect

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #16548 

Problem Summary:
The test case sometimes failed due to #17904
Cancelling jobs sometimes takes effect, but sometimes doesn't. It depends on whether it's read.

For this case:
1. Worker reads the job from KV with state `reorg`
2. `admin.CancelJobs` writes the job with state `cancelling`
3. Worker panics and writes the job with state `running` and error `panic`
4. Worker reads the job from KV <--- The state can be either `cancelling` or `running`

As step 2 and 3 are running in parallel, step 4 may read either the job.
Even we wait some time before step 3 to let step 4 read the cancelled job, after step 3 finishes, it may still override the cancelled job.

So, to ensure the job is cancelled finally, both 2 conditions must be guaranteed:
- The cancelled job is always read in step 4, not the `panic` one
- The `panic` error (or reorg timeout error) after step 3 won't override the cancelled job

As there's no lock in accessing the job, the second condition can't be guaranteed.

### What is changed and how it works?

What's Changed: Just modify the expectation: both errors are fine.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- No release note

### CODE REVIEW

File: ddl/serial_test.go [hunk 1]
```diff
@@ -591,7 +591,10 @@ func (s *testSerialSuite) TestCancelAddIndexPanic(c *C) {
 	}
 	c.Assert(checkErr, IsNil)
 	c.Assert(err, NotNil)
-	c.Assert(err.Error(), Equals, "[ddl:8214]Cancelled DDL job")
+	errMsg := err.Error()
+	// Cancelling the job can either succeed or not, it depends on whether the cancelled job takes affect.
+	// For now, there's no way to guarantee that cancelling will always take effect.
```
Comment (AilinKid) [inline ddl/serial_test.go:596]: better add a todo here, when issue  #17904 is closed, there is no need to tolerate it here.

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

File: ddl/serial_test.go (hunk 1 above)
Comment (bb7133) [reply ddl/serial_test.go:596]: Please address the comment @djshow832

**Comment by bb7133** [comment]
LGTM

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
