### PR TITLE
ddl: fix unstable tests

### LINKED ISSUE #25456: unstable test `testDBSuite2.TestAddUniqueIndexRollback`
## Bug Report
```
db_test.go:294:
    testAddIndexRollback(c, s.store, s.lease, idxName, addIdxSQL, errMsg, hasNullValsInKey)
db_test.go:372:
    c.Assert(err.Error(), Equals, errMsg, Commentf("err:%v", err))
... obtained string = "[kv:1062]Duplicate entry '2039' for key 'c3_index'"
... expected string = "[kv:1062]Duplicate entry '2038' for key 'c3_index'"
... err:[kv:1062]Duplicate entry '2039' for key 'c3_index'
```
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb-unit-test-nightly/detail/tidb-unit-test-nightly/663/pipeline/

### 4. What is your TiDB version? (Required)
master 57fa70a90d62222578a8f050a0ba24547d91327c

### LINKED ISSUE #25634: unstable test `testDBSuite5.TestAddPrimaryKeyRollback1`
## Bug Report
```
db_test.go:277:
    testAddIndexRollback(c, s.store, s.lease, idxName, addIdxSQL, errMsg, hasNullValsInKey)
db_test.go:372:
    c.Assert(err.Error(), Equals, errMsg, Commentf("err:%v", err))
... obtained string = "[kv:1062]Duplicate entry '2039' for key 'PRIMARY'"
... expected string = "[kv:1062]Duplicate entry '2038' for key 'PRIMARY'"
... err:[kv:1062]Duplicate entry '2039' for key 'PRIMARY'
```
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb-unit-test-nightly/detail/tidb-unit-test-nightly/1542/pipeline/

### 4. What is your TiDB version? (Required)
master 57fa70a90d62222578a8f050a0ba24547d91327c

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #25634, close #25456 

Don't delete the duplicate row.

### What is changed and how it works?

Don't delete the duplicate row.

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: ddl/db_test.go [hunk 1]
```diff
@@ -516,8 +514,9 @@ LOOP:
 			// delete some rows, and add some data
 			for i := count; i < count+step; i++ {
 				n := rand.Intn(count)
-				// Don't delete this row, otherwise error message would change.
-				if n == defaultBatchSize*2-10 {
+				// (2048, 2038, 2038) and (2038, 2038, 2038)
```
Comment (bb7133) [inline ddl/db_test.go:517]: I don't get the comment here. Could you add an explanation with more details?

Comment (wjhuang2016) [reply ddl/db_test.go:517]: These are the two duplicate rows. So we shouldn't delete either of them.

File: ddl/db_test.go [hunk 2]
```diff
@@ -516,8 +514,9 @@ LOOP:
...
+				// Don't delete rows where c1 is 2048 or 2038, otherwise error message would change.
```
Comment (zimulala) [inline ddl/db_test.go:518]:
```suggestion
				// Don't delete rows where c1 is 2048 or 2038, otherwise, the entry value in duplicated error message would change.
```

File: ddl/db_test.go (hunk 1 above)
Comment (wjhuang2016) [reply ddl/db_test.go:517]: count += step, so it may > 2048.
This test wants to randomly delete some rows. So it doesn't remove data in the range of [0, 2037] directly.
It's not easy to understand, that why I missed this check at the first fix.

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by zhouqiang-cl** [comment]
fail caused by https://github.com/pingcap/tidb/issues/24679
