### PR TITLE
owner: migrate test-infra to testify

### LINKED ISSUE #26743: migrate test-infra to testify for `owner` pkg

### LINKED ISSUE #26765: ERROR 1493 (HY000): VALUES LESS THAN value must be strictly increasing for each partition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t2;
SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
create table t2 (a bigint unsigned) partition by range (a) (
    partition p1 values less than (0),
    partition p2 values less than (1),
    partition p3 values less than (18446744073709551614),
    partition p4 values less than (18446744073709551615),
    partition p5 values less than maxvalue
);
```
### 2. What did you expect to see? (Required)
```
mysql> SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
Query OK, 0 rows affected (0.00 sec)

mysql> create table t2 (a bigint unsigned) partition by range (a) (
    ->     partition p1 values less than (0),
    ->     partition p2 values less than (1),
    ->     partition p3 values less than (18446744073709551614),
    ->     partition p4 values less than (18446744073709551615),
    ->     partition p5 values less than maxvalue
    -> );
Query OK, 0 rows affected (0.05 sec)
```

### 3. What did you see instead (Required)
release-5.1 & master
```
mysql> SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
Query OK, 0 rows affected (0.00 sec)

mysql> create table t2 (a bigint unsigned) partition by range (a) (
    ->     partition p1 values less than (0),
    ->     partition p2 values less than (1),
    ->     partition p3 values less than (18446744073709551614),
    ->     partition p4 values less than (18446744073709551615),
    ->     partition p5 values less than maxvalue
    -> );
ERROR 1493 (HY000): VALUES LESS THAN value must be strictly increasing for each partition
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.1
Edition: Community
Git Commit Hash: 797bddd25310ed42f0791c8eccb78be8cce2f502
Git Branch: release-5.1
UTC Build Time: 2021-07-31 02:01:43
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by hu00yan**
Signed-off-by: hu00yan <wuyan19981@gmail.com>

### What problem does this PR solve?

Issue Number: close #26743 

### What is changed and how it works?

What's Changed: Removed pingcap/check for owner/, moved to testify.

### Release note 

```release-note
None
```

### CODE REVIEW

File: owner/manager_test.go [hunk 1]
```diff
@@ -194,7 +190,7 @@ func TestCluster(t *testing.T) {
 	}
 	err = d.Stop()
 	if err != nil {
```
Comment (tisonkun) [inline owner/manager_test.go:192]: You can refactor the code as

```go
require.NoError(t, err)
```

ditto others.

Comment (hu00yan) [reply owner/manager_test.go:193]: Thank you, fixed.

**Comment by hu00yan** [comment]
@tisonkun Excuse me, what should I do to resolve conflicts? Change code as my PR and leave comment here?

File: owner/manager_test.go [hunk 2]
```diff
@@ -56,12 +56,12 @@ func TestSingle(t *testing.T) {
 	}
 	store, err := mockstore.NewMockStore()
 	if err != nil {
-		t.Fatal(err)
+		require.NoError(t, err)
 	}
```
Comment (xhebox) [inline owner/manager_test.go:60]:
```
if err != nil {
 Fatal...
}
```

is equivalent to

```
require.NoError(t, err)
```

There is no need to guard the require assertion with an if branch.

File: owner/manager_test.go [hunk 3]
```diff
@@ -80,15 +80,15 @@ func TestSingle(t *testing.T) {
 	)
 	err = d.Start(nil)
 	if err != nil {
-		t.Fatalf("DDL start failed %v", err)
+		require.NoErrorf(t, err, "DDL start failed %v")
```
Comment (xhebox) [inline owner/manager_test.go:83]: `NoErrorf` is like `Noerror(testing, error)`, but with formats `Noerror(testing, error, msg, args...)`. You can see it as a combination of `NoError(testing, error)` + `Printf(msg, args...)`. So should be `require.NoErrorf(t, err, "DDL start failed %v", err)`.

But, since the require assertion will print `err` variable/the assertion variable anyway, you can just write  `require.NoErrorf(t, err, "DDL start failed")`.

Same to your other format functions.

File: owner/manager_test.go [hunk 4]
```diff
@@ -79,17 +75,13 @@ func TestSingle(t *testing.T) {
...
+	require.NoErrorf(t, err, "DDL start failed")
 	defer func() {
 		_ = d.Stop()
 	}()
 
 	isOwner := checkOwner(d, true)
-	if !isOwner {
-		require.Emptyf(t, isOwner, "expet true, got isOowner:%v")
-	}
+	require.Emptyf(t, isOwner, "expet true, got isOowner false")
```
Comment (xhebox) [inline owner/manager_test.go:84]: Could be `require.Truef`, which is more obvious than `empty`.

File: owner/manager_test.go [hunk 5]
```diff
@@ -101,9 +93,7 @@ func TestSingle(t *testing.T) {
 		require.NoErrorf(t, err, "campaigned result don't match, err %v")
 	}
 	isOwner = checkOwner(d, true)
-	if !isOwner {
-		require.NotEmptyf(t, isOwner, "expected true, got isOwner:%v")
-	}
+	require.NotEmptyf(t, isOwner, "expected true, got isOwner false")
```
Comment (xhebox) [inline owner/manager_test.go:96]: ditto

File: owner/manager_test.go [hunk 6]
```diff
@@ -153,13 +137,9 @@ func TestCluster(t *testing.T) {
...
 	err = d.Start(nil)
-	if err != nil {
-		require.NoErrorf(t, err, "DDL start failed %v")
-	}
+	require.NoErrorf(t, err, "DDL start failed")
 	isOwner := checkOwner(d, true)
-	if !isOwner {
-		require.Emptyf(t, isOwner, "expect true, got isOwner:%v")
-	}
+	require.Emptyf(t, isOwner, "expect true, got isOwner false")
```
Comment (xhebox) [inline owner/manager_test.go:142]: ditto

File: owner/manager_test.go [hunk 7]
```diff
@@ -171,28 +151,18 @@ func TestCluster(t *testing.T) {
...
 	err = d1.Start(nil)
-	if err != nil {
-		require.NoErrorf(t, err, "DDL start failed %v")
-	}
+	require.NoErrorf(t, err, "DDL start failed")
 	isOwner = checkOwner(d1, false)
-	if isOwner {
-		require.Emptyf(t, isOwner, "expect false, got isOwner:%v")
-	}
+	require.Emptyf(t, isOwner, "expect false, got isOwner true")
```
Comment (xhebox) [inline owner/manager_test.go:156]: ditto, there is `Falsef`.

File: owner/manager_test.go [hunk 8]
```diff
@@ -171,28 +151,18 @@ func TestCluster(t *testing.T) {
...
 	err = deleteLeader(cliRW, DDLOwnerKey)
-	if err != nil {
-		require.NoError(t, err)
-	}
+	require.NoError(t, err)
 	isOwner = checkOwner(d, false)
-	if isOwner {
-		require.Emptyf(t, isOwner, "expect false, got isOwner:%v")
-	}
+	require.Emptyf(t, isOwner, "expect false, got isOwner true")
```
Comment (xhebox) [inline owner/manager_test.go:163]: ditto

File: owner/manager_test.go [hunk 9]
```diff
@@ -205,33 +175,21 @@ func TestCluster(t *testing.T) {
...
-		if err != nil {
-			require.NoErrorf(t, err, "DDL stop failed %v")
-		}
+		require.NoErrorf(t, err, "DDL stop failed")
 	}()
 	isOwner = checkOwner(d3, false)
-	if isOwner {
-		require.Emptyf(t, isOwner, "expect false, got isOwner:%v")
-	}
+	require.Emptyf(t, isOwner, "expect false, got isOwner true")
```
Comment (xhebox) [inline owner/manager_test.go:184]: ditto

**Review by xhebox — COMMENTED** [review]
Rest LGTM

**Comment by hu00yan** [comment]
> You should remove the old `TestT`, there is already the new `TestMain`.

Should I rename it to TestInitLogger?

**Comment by xhebox** [comment]
> 
> 
> > You should remove the old `TestT`, there is already the new `TestMain`.
> 
> Should I rename it to TestInitLogger?

No, it is not a test for init logger. `TestT` is the entry for all tests with go-check framework. `InitLogger` is some thing that needs to be inited before all tests. Move it to `TestMain` and remove `TestT`.

**Comment by hu00yan** [comment]
@xhebox Thank you for so kindly respond. One more question, how to assert InitLogger is success ? TestMain's argument can't be modified.

**Comment by xhebox** [comment]
> 
> 
> @xhebox Thank you for so kindly respond. One more question, how to assert InitLogger is success ? TestMain's argument can't be modified.

You can use `log.Fatal` from `github.com/pingcap/log`. `TestMain` is the entry and it is reasonable to be special.

File: owner/manager_test.go [hunk 10]
```diff
@@ -204,39 +173,27 @@ func TestCluster(t *testing.T) {
...
-		t.Fatalf("new session failed %v", err)
-	}
+	require.NoErrorf(t, err, "new session failed")
 	elec := concurrency.NewElection(session, DDLOwnerKey)
 	logPrefix := fmt.Sprintf("[ddl] %s ownerManager %s", DDLOwnerKey, "useless id")
 	logCtx := logutil.WithKeyValue(context.Background(), "owner info", logPrefix)
 	_, err = owner.GetOwnerInfo(goctx.Background(), logCtx, elec, "useless id")
 	if !terror.ErrorEqual(err, concurrency.ErrElectionNoLeader) {
-		t.Fatalf("get owner info result don't match, err %v", err)
+		require.NoErrorf(t, err, "get owner info result don't match, err %v")
```
Comment (xhebox) [inline owner/manager_test.go:196]: Could be `require.Truef(t, terror.ErrorEqual(err, concurrency.ErrElectionNoLeader), "get owner info result don't match, err %v"))`.

Comment (hu00yan) [reply owner/manager_test.go:196]: Won't this be too long and affect readability?

Comment (xhebox) [reply owner/manager_test.go:196]: I think some editors will wrap the line automatically. The thing is that the change here is not equivalent. `NoError` checks if it is nil, while the origin branch checks if it is a specific error.

**Review by xhebox — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by hu00yan** [comment]
@tisonkun As time goes by, not just check_dev_2，more test failed. What should I do to solve this problem?

**Comment by tisonkun** [comment]
@hu00yan TiDB v5.2 planning is due by 8.6, these days CI may be unstable. We're working on a more stable CI experience #25899 . You may retrigger tests by `/run-all-tests` or take a look at the failure and report ci bugs (search if there is one first).

**Comment by tisonkun** [comment]
check_dev_2 failed with test fail, PTAL @hu00yan 

```
2021-08-04T12:55:13.026Z]     manager_test.go:138: 
[2021-08-04T12:55:13.026Z]         	Error Trace:	manager_test.go:138
[2021-08-04T12:55:13.026Z]         	Error:      	Received unexpected error:
[2021-08-04T12:55:13.026Z]         	            	rpc error: code = Canceled desc = grpc: the client connection is closing
[2021-08-04T12:55:13.027Z]         	            	github.com/pingcap/errors.AddStack
[2021-08-04T12:55:13.027Z]         	            		/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174
[2021-08-04T12:55:13.027Z]         	            	github.com/pingcap/errors.Trace
[2021-08-04T12:55:13.027Z]         	            		/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/juju_adaptor.go:15
[2021-08-04T12:55:13.027Z]         	            	github.com/pingcap/tidb/owner.contextDone
[2021-08-04T12:55:13.027Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/owner/manager.go:389
[2021-08-04T12:55:13.027Z]         	            	github.com/pingcap/tidb/owner.NewSession
[2021-08-04T12:55:13.027Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/owner/manager.go:148
[2021-08-04T12:55:13.027Z]         	            	github.com/pingcap/tidb/owner.(*ownerManager).CampaignOwner
[2021-08-04T12:55:13.027Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/owner/manager.go:189
[2021-08-04T12:55:13.027Z]         	            	github.com/pingcap/tidb/ddl.(*ddl).Start
[2021-08-04T12:55:13.027Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/ddl/ddl.go:351
[2021-08-04T12:55:13.027Z]         	            	github.com/pingcap/tidb/owner_test.TestCluster
[2021-08-04T12:55:13.027Z]         	            		/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/owner/manager_test.go:137
[2021-08-04T12:55:13.027Z]         	            	testing.tRunner
[2021-08-04T12:55:13.027Z]         	            		/usr/local/go/src/testing/testing.go:1193
[2021-08-04T12:55:13.027Z]         	            	runtime.goexit
[2021-08-04T12:55:13.027Z]         	            		/usr/local/go/src/runtime/asm_amd64.s:1371
[2021-08-04T12:55:13.027Z]         	Test:       	TestCluster
[2021-08-04T12:55:13.027Z]         	Messages:   	DDL start failed
[2021-08-04T12:55:13.027Z]     cluster.go:1252: context canceled
```

**Comment by tisonkun** [comment]
Let me take a closer look

**Comment by tisonkun** [comment]
It seems owner tests hand forever.

**Comment by tisonkun** [comment]
I'll try to push follow ups, this patch cannot pass locally, please test locally before you push commits.

**Comment by zhouqiang-cl** [comment]
It caused by https://github.com/pingcap/tidb/issues/24679

**Comment by tisonkun** [comment]
@zhouqiang-cl not really. These tests modify failpoints and global variable, I'd like to run them in serial at this point.

**Comment by tisonkun** [comment]
/cc @xhebox @zimulala 

PTAL

File: owner/manager_test.go [hunk 11]
```diff
@@ -11,12 +11,13 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+// +build !windows
```
Comment (xhebox) [inline owner/manager_test.go:14]: Maybe the original is better: if someone adds another test that is not related to `NewClusterV3`, it is ignored. It is not likely tests in the packages will change, though.

Comment (tisonkun) [reply owner/manager_test.go]: Updated.

**Review by xhebox — COMMENTED** [review]
LGTM

**Comment by tisonkun** [comment]
@xhebox @zimulala may you help on merging this PR?
