### PR TITLE
expression: fix a bug that the coercibilities of enum and set are wrong

### LINKED ISSUE #20268: enum doesn't support collation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

new_collations_enabled_on_first_bootstrap = true
```
use test;
drop table if exists t;
CREATE TABLE `t` (   `a` enum('a','b') DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
insert into t values('a');
select * from t where a = 'A';
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t where a = 'A';
+------+
| a    |
+------+
| a    |
+------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```
mysql> select * from t where a = 'A';
Empty set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

master 0cdd24d36b9e5f441d4cb7425969fae9fc1c0e7f and release-4.0 ddba4fe39be2c702403ab12653d3d3d6940f3f29

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #20268 

Problem Summary:

enum and set get the wrong coercibility.
### What is changed and how it works?

Don't set their coercibility to CoercibilityNumeric.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- fix a bug that the coercibilities of enum and set are wrong.

### CODE REVIEW

File: expression/collation.go [hunk 1]
```diff
@@ -153,7 +154,7 @@ func deriveCoercibilityForScarlarFunc(sf *ScalarFunction) Coercibility {
 	if _, ok := sysConstFuncs[sf.FuncName.L]; ok {
 		return CoercibilitySysconst
 	}
-	if !types.IsString(sf.RetType.Tp) {
+	if !types.IsString(sf.RetType.Tp) && sf.RetType.Tp != mysql.TypeEnum && sf.RetType.Tp != mysql.TypeSet {
```
Comment (XuHuaiyu) [inline expression/collation.go:157]: `sf.RetType.EvalType == types.ETString` ?

Comment (wjhuang2016) [reply expression/collation.go]: Done

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
