### PR TITLE
executor/infoschema_reader: exclude virtual schema in TIKV_REGION_STATUS

### LINKED ISSUE #59698: query TIKV_REGION_STATUS table returns unexpected result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. creat a tidb cluster.
```sh
tiup playground nightly --tiflash 0 --kv 3 --db 1
```

2. do following query:

```sql
test> use information_schema;
You are now connected to database "information_schema" as user "root"
Time: 0.001s
information_schema> select count(*) as cnt, region_id from `TIKV_REGION_STATUS` group by region_id order by cnt desc limit 1;
+-----+-----------+
| cnt | region_id |
+-----+-----------+
| 767 | 14        |
+-----+-----------+
1 row in set
Time: 0.026s
information_schema> select count(*) as cnt, DB_NAME from `TIKV_REGION_STATUS` where REGION_ID=14 group by DB_NAME;
+-----+--------------------+
| cnt | DB_NAME            |
+-----+--------------------+
| 1   | mysql              |
| 94  | INFORMATION_SCHEMA |
| 637 | METRICS_SCHEMA     |
| 35  | PERFORMANCE_SCHEMA |
+-----+--------------------+
```

The problem is, `INFORMATION_SCHEMA`, `METRICS_SCHEMA` and `PERFORMANCE_SCHEMA` don't have data store in TiKV regions, they are virtual table, so the `TIKV_REGION_STATUS` shouldn't contain those database info.

### 4. What is your TiDB version? (Required)

```
> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v9.0.0-alpha-302-g21487468b5             |
| Edition: Community                                        |
| Git Commit Hash: 21487468b5f29cc6daae52684b4706a56b311506 |
| Git Branch: HEAD                                          |
| UTC Build Time: 2025-02-21 02:28:16                       |
| GoVersion: go1.23.6                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by sriramrajendiran**
### What problem does this PR solve?

Issue Number: close #59698

Problem Summary:

### What changed and how does it work?

Add a check to exclude INFORMATION_SCHEMA, METRICS_SCHEMA and PERFORMANCE_SCHEMA when TIKV_REGION_STATUS is queried.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Previously, when you query TIKV_REGION_STATUS, results will show tables from INFORMATION_SCHEMA, METRICS_SCHEMA and PERFORMANCE_SCHEMA. From now on, it will not be shown as a part of this TIKV_REGION_STATUS results as they are not a part of TiKV data store.
```

### CODE REVIEW

File: pkg/executor/infoschema_cluster_table_test.go [hunk 1]
```diff
@@ -365,6 +365,9 @@ func TestTikvRegionStatus(t *testing.T) {
 		"1 test test_t2 1 p_a 1 p1",
 		"1 test test_t2 1 p_b 0 <nil>",
 	))
+
+	// Run the query to ensure virtual schemas are excluded and expect no rows to be returned
+	tk.MustQuery(`SELECT DB_NAME FROM information_schema.TIKV_REGION_STATUS WHERE DB_NAME IN ('information_schema', 'metrics_schema', 'performance_schema')`).Check(testkit.Rows())
```
Comment (lance6716) [inline pkg/executor/infoschema_cluster_table_test.go:370]: Without the fix, this test can still pass. I think it's because the column is case-sensitive. Please change the names to upper-case words.

File: pkg/executor/infoschema_reader.go [hunk 2]
```diff
@@ -2095,12 +2095,17 @@ func (e *memtableRetriever) setDataForTiKVRegionStatus(ctx context.Context, sctx
 	}
 
 	tableInfos := tikvHelper.GetRegionsTableInfo(allRegionsInfo, is, nil)
+	virtualSchemas := []string{"information_schema", "metrics_schema", "performance_schema"}
```
Comment (lance6716) [inline pkg/executor/infoschema_reader.go:2098]: I found we already defined some variables for these database names

https://github.com/pingcap/tidb/blob/b9c54c4019636174f6c1d984344809f4499ad860/pkg/util/misc.go#L183-L189

So you can use `virtualSchemas := []string{util.InformationSchemaName.L, ... }`

**Review by lance6716 — APPROVED** [review]

File: pkg/executor/infoschema_reader.go [hunk 3]
```diff
@@ -2095,12 +2095,17 @@ func (e *memtableRetriever) setDataForTiKVRegionStatus(ctx context.Context, sctx
...
 	tableInfos := tikvHelper.GetRegionsTableInfo(allRegionsInfo, is, nil)
+	virtualSchemas := []string{util.InformationSchemaName.L, util.PerformanceSchemaName.L, util.MetricSchemaName.L}
 	for i := range allRegionsInfo.Regions {
 		regionTableList := tableInfos[allRegionsInfo.Regions[i].ID]
 		if len(regionTableList) == 0 {
 			e.setNewTiKVRegionStatusCol(&allRegionsInfo.Regions[i], nil)
 		}
 		for j, regionTable := range regionTableList {
+			// Exclude virtual schemas
+			if slices.Contains(virtualSchemas, regionTable.DB.Name.L) {
```
Comment (crazycs520) [inline pkg/executor/infoschema_reader.go:2106]: you can use `util.IsMemDB` function.

**Review by tangenta — APPROVED** [review]
