### PR TITLE
privilege: avoid processing the same privilege event twice

### LINKED ISSUE #61206: `check_dev2` test may fails on privilege related cases.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

SQLs show below
```sql
CREATE USER tcd1, tcd2;
GRANT ALL ON *.* to tcd2 WITH GRANT OPTION;
```

```sql
connect (tcd2,localhost,tcd2,,);
connection tcd2;
DROP USER tcd1;
```

### 2. What did you expect to see? (Required)

`DROP USER tcd1` executes success.

### 3. What did you see instead (Required)

Sometimes it will check privilege failed.

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #61206

Problem Summary:

The root case is:

Two SQL statements are executed consecutively:  
1. `CREATE USER tcd1, tcd2;`  
2. `GRANT ALL ON *.* to tcd2 WITH GRANT OPTION;`  

**Normal sequence:**  
`notifyUpdatePrivilege()` → priv 0  
`etcd` → `LoadPrivilegeLoop()` → priv 0  
`notifyUpdatePrivilege()` → priv all  
`etcd` → `LoadPrivilegeLoop()` → priv all  

**After adding a sleep between `LoadAll` and `h.priv.Store` in `UpdateAll` for the etcd case, it becomes:**  
`notifyUpdatePrivilege()` → priv 0  
`notifyUpdatePrivilege()` → priv all  
`etcd` → `LoadPrivilegeLoop()` → priv 0  
*(At this point, executing some SQL on tcd2 will result in permission denied errors.)*  
`etcd` → `LoadPrivilegeLoop()` → priv all  

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Add logs in `func privReloadEvent(h *privileges.Handle, event *PrivilegeEvent)` function, use the command below to create a cluster
```
tiup playground nightly --db 2 --db.binpath bin/tidb-server --kv 1 --tiflash 0 --without-monitor
```

Then execute the SQLs below
```sql
CREATE USER tcd1, tcd2;
GRANT ALL ON *.* to tcd2 WITH GRANT OPTION;
```

You can see two logs in each TiDB-Server's log file. Before this PR, it had 4 logs on the execution node and 2 logs on the other node.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

File: pkg/domain/domain.go [hunk 1]
```diff
@@ -2045,7 +2051,11 @@ func (do *Domain) LoadPrivilegeLoop(sctx sessionctx.Context) error {
 				}
 			case <-time.After(duration):
 				event.All = true
-				event = batchReadMoreData(watchCh, event)
+				event = do.batchReadMoreData(watchCh, event)
+			}
+
+			if !event.All && len(event.UserList) == 0 {
+				continue
 			}
```
Comment (tiancaiamao) [inline pkg/domain/domain.go:2059]: How could this happen?

Comment (tiancaiamao) [reply pkg/domain/domain.go:2059]: OK, I see, you skip decoding the event ...
Why not decode the event faithfully, and avoid the unnecessary reloading in `privReloadEvent` function?

File: pkg/domain/domain.go [hunk 2]
```diff
@@ -2058,7 +2058,12 @@ func (do *Domain) LoadPrivilegeLoop(sctx sessionctx.Context) error {
 	return nil
 }
 
-func privReloadEvent(h *privileges.Handle, event *PrivilegeEvent) (err error) {
+func (do *Domain) privReloadEvent(h *privileges.Handle, event *PrivilegeEvent) (err error) {
+	if event.ServerID == do.ServerID() {
```
Comment (tiancaiamao) [inline pkg/domain/domain.go:2062]: We need to make do.ServerID() never be 0, otherwise it would be buggy here.

**Review by tiancaiamao — APPROVED** [review]

File: pkg/domain/domain.go (hunk 2 above)
Comment (Defined2014) [reply pkg/domain/domain.go]: Done

**Review by tangenta — APPROVED** [review]
