### PR TITLE
disttask: fix subtask finished immediately and mark success when encountering network partition 

### LINKED ISSUE #48649: crc32Checksum is inconsistency after import into finished which was injected ddl owner network partition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run import into
2、 inject ddl owner network partition

case config：
      tag: "ha-test-import-into"
      cases:
        - name: "ha_tidb(ddl-owner)_to_all_network_partition"
          warmUpTime: 1m
          faultType: network_partition
          selector: "tidb(ddl-owner)_to_all"
          period: "@every 5m"
          faultDuration: 3m
          faultTotalRunTime: 30m
          importInto:
            - db: "importtest"
              schema: "CREATE TABLE `user_data1` (
                `uid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                `data` mediumblob NOT NULL,
                `update_data` blob NOT NULL,
                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `update_time` datetime DEFAULT NULL,
                PRIMARY KEY (`uid`) /*T![clustered_index] CLUSTERED */,
                KEY `k_1` (`update_time`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5850196;"
              cmd: "import into user_data1 from 's3://qe-testing/brie/lightning-mhy-100G-csv/sysbench.user_data1.000001*.csv?access-key=AKLTwRZn26DMQ1KAOqZBwb2N\u0026secret-access-key=OGpscvlaU8gJCOIMZsCDJJZvhVWt8urXjQRBuQ6u\u0026endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com\u0026force-path-style=false\u0026region=Beijing\u0026provider=ks' WITH DETACHED,thread=8,skip_rows=1"
              timeout: 120m
              crc32Checksum: 3582177512

### 2. What did you expect to see? (Required)
crc32Checksum is consistency

### 3. What did you see instead (Required)
crc32Checksum is inconsistency after import into finished which was injected ddl owner network partition

operatorLogs:
[2023-11-15 22:51:28] ###### start import into
import into user_data1 from 's3://qe-testing/brie/lightning-mhy-100G-csv/sysbench.user_data1.000001*.csv?access-key=AKLTwRZn26DMQ1KAOqZBwb2N&secret-access-key=OGpscvlaU8gJCOIMZsCDJJZvhVWt8urXjQRBuQ6u&endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com&force-path-style=false&region=Beijing&provider=ks' WITH DETACHED,thread=8,skip_rows=1
[2023-11-15 22:51:28] ###### wait for import job to finish
[2023-11-15 23:13:08] ###### import job finished
select id, step, status from mysql.tidb_import_jobs where start_time >= '2023-11-15 22:51:28'
jobId: 60005, step: , status: finished
import done, it takes: 21m40.447941577s

[2023/11/15 23:23:01.405 +08:00] [INFO] [client.go:826] ["Get table checksum"] [database=importtest] [table=user_data1] ["table crc32 checksum"=244735121]
ImportIntoConsistencyCheck failed: user_data1 expected cCrc32Checksum is 3582177512, the actual is 244735121

### 4. What is your TiDB version? (Required)
git hash：151b5b1df9d595bf0b568ff82f2ea2e13ae3eddb

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #48649 ref #46258

Problem Summary:
see the comments in issue.
### What is changed and how it works?
1. change taskTable interface using ctx
2. when updating subtasks, check the exec_id of them
Most of the code are editing tests.
Main logic modifications only occur in task_table.go and scheduler.go
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/scheduler/scheduler.go [hunk 1]
```diff
@@ -216,15 +218,19 @@ func (s *BaseScheduler) run(ctx context.Context, task *proto.Task) (resErr error
 		if err := s.getError(); err != nil {
 			break
 		}
+		if ctx.Err() != nil {
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/scheduler.go:221]: `runCtx` is the cancelled ctx on `startCancelCheck`

File: pkg/disttask/framework/scheduler/scheduler.go [hunk 2]
```diff
@@ -387,7 +393,7 @@ func (s *BaseScheduler) Rollback(ctx context.Context, task *proto.Task) error {
 
 	// We should cancel all subtasks before rolling back
 	for {
-		subtask, err := s.taskTable.GetFirstSubtaskInStates(s.id, task.ID, task.Step,
+		subtask, err := s.taskTable.GetFirstSubtaskInStates(ctx, s.id, task.ID, task.Step,
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/scheduler.go:396]: use `rollbackCtx`?

File: pkg/disttask/framework/scheduler/scheduler.go [hunk 3]
```diff
@@ -610,27 +615,29 @@ func (s *BaseScheduler) markSubTaskCanceledOrFailed(ctx context.Context, subtask
 		err := errors.Cause(err)
 		if ctx.Err() != nil && context.Cause(ctx) == ErrCancelSubtask {
 			logutil.Logger(s.logCtx).Warn("subtask canceled", zap.Error(err))
-			s.updateSubtaskStateAndError(subtask, proto.TaskStateCanceled, nil)
+			updateCtx := util.WithInternalSourceType(context.Background(), kv.InternalDistTask)
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/scheduler.go:618]: tidb might not be able to shutdown gracefully if we block here
deadline might not work in all case, might we can use parent ctx, ok for now,

File: pkg/disttask/framework/scheduler/scheduler.go (hunk 2 above)
Comment (ywqzzy) [reply pkg/disttask/framework/scheduler/scheduler.go:396]: > use `rollbackCtx`?

Not neccessary? Since the ctx is used right before rollbackctx?But ok to change it.

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
plz fix comments before merge

File: pkg/disttask/framework/scheduler/scheduler.go (hunk 3 above)
Comment (ywqzzy) [reply pkg/disttask/framework/scheduler/scheduler.go]: fixed

File: pkg/disttask/framework/scheduler/scheduler.go (hunk 1 above)
Comment (ywqzzy) [reply pkg/disttask/framework/scheduler/scheduler.go]: fixed

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
ci failed
```
    job_test.go:612: 
        	Error Trace:	tests/realtikvtest/importintotest/job_test.go:612
        	            				src/runtime/asm_amd64.s:1650
        	Error:      	Target error should be in err chain:
        	            	expected: "context canceled"
        	            	in chain: "unexpected no source type context, if you see this error, the `RequestSourceTypeKey` is missing in your context"
        	Test:       	TestLoadRemote/TestKillBeforeFinish
```

**Comment by ywqzzy** [comment]
> ci failed
> 
> ```
>     job_test.go:612: 
>         	Error Trace:	tests/realtikvtest/importintotest/job_test.go:612
>         	            				src/runtime/asm_amd64.s:1650
>         	Error:      	Target error should be in err chain:
>         	            	expected: "context canceled"
>         	            	in chain: "unexpected no source type context, if you see this error, the `RequestSourceTypeKey` is missing in your context"
>         	Test:       	TestLoadRemote/TestKillBeforeFinish
> ```

fixed

**Comment by ywqzzy** [comment]
Working on the ci fail
