### PR TITLE
planner: TTL scan can trigger sync/async load/generateRuntimeFilter

### LINKED ISSUE #61822: TTL scan cannot trigger sync/async load/generateRuntimeFilter
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

We previously thought that internal SQL was for system tables,and since system tables do not have statistics,we could skip the sync load.However,TTL is different because it generates SQL execution based on user tables.Therefore,we need to align its behavior with regular tables.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #61822

Problem Summary:

### What changed and how does it work?

The TTL scan is different from our other internal SQL, as it reads user tables. So, our previous approach of determining whether to perform sync load based on whether it is internal SQL has issues.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/sessionctx/variable/session.go [hunk 1]
```diff
@@ -1732,6 +1732,9 @@ type SessionVars struct {
 
 	// BulkDMLEnabled indicates whether to enable bulk DML in pipelined mode.
 	BulkDMLEnabled bool
+
+	// InternalSQLUseUserTable indicates whether to use user table for internal SQL. it will be used by TTL scan
+	InternalSQLUseUserTable bool
```
Comment (elsa0520) [inline pkg/sessionctx/variable/session.go]: Is it better to add this variable here? Because it seems to be an internal variable, is there any other place to add it? Because the session variable seems to be visible to the client.

Comment (hawkingrei) [reply pkg/sessionctx/variable/session.go]: The session variable needs to be hooked onto the session in order to be used externally. Since we haven't implemented this hook, it is only for internal use and there won't be any issues in this regard. `se.GetSessionVars()` is a mature and universal solution.

Comment (hawkingrei) [reply pkg/sessionctx/variable/session.go]: We cannot allow this switch to be turned on but appear in places where it should not be.

Comment (AilinKid) [inline pkg/sessionctx/variable/session.go]:
```suggestion
	InternalSQLScanUserTable bool
```

**Review by AilinKid — COMMENTED** [review]
rest lgtm

File: pkg/sessionctx/variable/session.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/sessionctx/variable/session.go]: Updated

**Review by AilinKid — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/core/optimizer.go [hunk 2]
```diff
@@ -480,7 +481,8 @@ func postOptimize(ctx context.Context, sctx base.PlanContext, plan base.Physical
 }
 
 func generateRuntimeFilter(sctx base.PlanContext, plan base.PhysicalPlan) {
-	if !sctx.GetSessionVars().IsRuntimeFilterEnabled() || sctx.GetSessionVars().InRestrictedSQL {
+	if !sctx.GetSessionVars().IsRuntimeFilterEnabled() ||
```
Comment (elsa0520) [inline pkg/planner/core/optimizer.go]: Will ttl scan using the Join?

Comment (hawkingrei) [reply pkg/planner/core/optimizer.go]: No, I think we can remove it.
