### PR TITLE
ddl: fix flaky test TestColumnAdd

### LINKED ISSUE #64559: flaky test TestColumnAdd
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run `TestColumnAdd`

### 2. What did you expect to see? (Required)

Pass

### 3. What did you see instead (Required)

https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/44383/artifact/bazel-test.log 

```
    column_change_test.go:69: 
        	Error Trace:	pkg/ddl/column_change_test.go:69
        	            				GOROOT/src/reflect/value.go:584
        	            				GOROOT/src/reflect/value.go:368
        	            				external/com_github_pingcap_failpoint/failpoint.go:149
        	            				external/com_github_pingcap_failpoint/failpoints.go:247
        	            				external/com_github_pingcap_failpoint/failpoints.go:323
        	            				pkg/ddl/job_scheduler.go:630
        	            				pkg/ddl/job_scheduler.go:512
        	            				pkg/util/wait_group_wrapper.go:167
        	            				src/runtime/asm_amd64.s:1700
        	Error:      	Received unexpected error:
        	            	expect [[1 2 3] [2 3 3]], got [[1 2 3] [2 3 3] [4 4 3]]
        	            	github.com/pingcap/tidb/pkg/ddl_test.checkResult
        	            		pkg/ddl/column_change_test.go:360
        	            	github.com/pingcap/tidb/pkg/ddl_test.checkAddWriteOnly
        	            		pkg/ddl/column_change_test.go:220
        	            	github.com/pingcap/tidb/pkg/ddl_test.TestColumnAdd.func1
        	            		pkg/ddl/column_change_test.go:69
        	            	reflect.Value.call
        	            		GOROOT/src/reflect/value.go:584
        	            	reflect.Value.Call
        	            		GOROOT/src/reflect/value.go:368
        	            	github.com/pingcap/failpoint.(*Failpoint).Call
        	            		external/com_github_pingcap_failpoint/failpoint.go:149
        	            	github.com/pingcap/failpoint.(*Failpoints).Call
        	            		external/com_github_pingcap_failpoint/failpoints.go:247
        	            	github.com/pingcap/failpoint.Call
        	            		external/com_github_pingcap_failpoint/failpoints.go:323
        	            	github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).transitOneJobStepAndWaitSync
        	            		pkg/ddl/job_scheduler.go:630
        	            	github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).deliveryJob.func1
        	            		pkg/ddl/job_scheduler.go:512
        	            	github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1
        	            		pkg/util/wait_group_wrapper.go:167
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1700
        	Test:       	TestColumnAdd
```

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/64559

Problem Summary:

**TestColumnAdd**

See https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/44383/artifact/bazel-test.log for the failed test.

(Also found this in release 8.5 CI 😢)

The problem is caused by the usage of `afterWaitSchemaSynced` failpoint in `transitOneJobStepAndWaitSync`:

https://github.com/pingcap/tidb/blob/d059a7de1b1a1c4f06c0fd39bd832b6048f6177f/pkg/ddl/column_change_test.go#L60

We expect it to work after `CREATE TABLE` finished. But we may enter this failpoint before `ADD COLUMN` is executed.

### What changed and how does it work?

Skip synced state in failpoint, so the check of `first` is also unecessary.

### Check List

Tests 

- [x] Unit test
- Fix existing test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/column_change_test.go [hunk 1]
```diff
@@ -396,23 +379,21 @@ func checkEqualTable(t *testing.T, t1, t2 *model.TableInfo) {
...
-		return
+	if tblInfo != nil {
+		checkEqualTable(t, historyJob.BinlogInfo.TableInfo, tblInfo)
 	}
 
-	// for handling schema job
-	require.Equal(t, historyJob.BinlogInfo.SchemaVersion, args.ver)
-	require.Equal(t, historyJob.BinlogInfo.DBInfo, args.db)
-	// only for creating schema job
-	if args.db != nil && len(args.tblIDs) == 0 {
```
Comment (joechenrh) [inline pkg/ddl/column_change_test.go:414]: `args.tblIDs` is not checked, so I remove it.

**Review by wjhuang2016 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
