### PR TITLE
planner, statistics: skip plan cache for sync-load fallback plans

### LINKED ISSUE #66585: planner, statistics: plan cache is not invalidated after sync-load timeout fallback when stats become fully loaded
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set global tidb_enable_prepared_plan_cache = 1;
set global tidb_plan_cache_invalidation_on_fresh_stats = 1;
set global tidb_stats_load_pseudo_timeout = 1;
set session tidb_stats_load_sync_wait = 1;

drop table if exists t;
create table t(a int primary key, b int, key idx_b(b));
insert into t values
(1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10);
analyze table t all columns;

prepare st from 'select * from t where b > ?';
set @p = 3;
execute st using @p;
execute st using @p;
select @@last_plan_from_cache;

-- switch to async load and trigger async load request
set session tidb_stats_load_sync_wait = 0;
execute st using @p;

-- poll until needed stats are no longer allEvicted/unInitialized
-- (one way to check)
show stats_histograms where db_name='test' and table_name='t';

execute st using @p;
select @@last_plan_from_cache;
```

Observed in our case: after async load success, `@@last_plan_from_cache` is still `1` (the plan generated under sync-load timeout fallback is reused).

### 2. What did you expect to see? (Required)

If a plan was generated when `sync load` timed out and optimizer fell back to pseudo/partial stats,
then once related stats become fully loaded, the cached plan should be invalidated (or bypassed once)
so optimizer can re-plan with loaded stats.

### 3. What did you see instead (Required)

The cached plan keeps being reused (`@@last_plan_from_cache = 1`) after stats become fully loaded in memory,
until an operation that bumps stats version (e.g. `ANALYZE TABLE`) or manual cache flush happens.

### 4. What is your TiDB version? (Required)

Built from current `master` branch for code verification:

- commit: `d2b270aa57`

(Please replace with `SELECT tidb_version()` output if needed in production reproductions.)

### Code snippets (suspected root cause)

1. Timeout fallback keeps SQL going and can still allow cacheable plan generation:

```go
// pkg/planner/core/rule/rule_collect_plan_stats.go
if err != nil {
    stmtCtx.IsSyncStatsFailed = true
    if vardef.StatsLoadPseudoTimeout.Load() {
        stmtCtx.AppendWarning(err)
        return nil
    }
}
```

2. Plan cache invalidation on fresh stats is keyed by stats version hash only:

```go
// pkg/planner/core/plan_cache_utils.go
if sctx.GetSessionVars().PlanCacheInvalidationOnFreshStats {
    var statsVerHash uint64
    for _, t := range stmt.tables {
        statsVerHash += getLatestVersionFromStatsTable(sctx, t.Meta(), t.Meta().ID)
    }
    hash = codec.EncodeUint(hash, statsVerHash)
}
```

3. `getLatestVersionFromStatsTable` uses `LastUpdateVersion` from columns/indices:

```go
// pkg/planner/core/logical_plan_builder.go
statsTbl.ForEachColumnImmutable(func(_ int64, col *statistics.Column) bool {
    version = max(version, col.LastUpdateVersion)
    return false
})
statsTbl.ForEachIndexImmutable(func(_ int64, idx *statistics.Index) bool {
    version = max(version, idx.LastUpdateVersion)
    return false
})
```

4. Sync-load mainly flips load status (`allEvicted`/`fullLoaded`) but does not bump `LastUpdateVersion`:

```go
// pkg/statistics/handle/syncload/stats_syncload.go
if fullLoad {
    colHist.StatsLoadedStatus = statistics.NewStatsFullLoadStatus()
} else {
    colHist.StatsLoadedStatus = statistics.NewStatsAllEvictedStatus()
}
```

### Impact

- A fallback plan generated under timeout can remain cached even after stats are fully loaded.
- Self-healing is delayed unless stats version changes.
- Can cause long-tail latency regressions for hot prepared statements.

### Workarounds

1. Increase `tidb_stats_load_sync_wait` to reduce timeout fallback probability.
2. Trigger `ANALYZE TABLE` to bump stats version.
3. Use `/*+ IGNORE_PLAN_CACHE() */` on affected SQL.
4. Flush plan cache manually if needed.

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #66585

Problem Summary:
When sync-load times out and the optimizer falls back to pseudo/partial stats, TiDB can cache the plan built under that temporary degraded state. Later executions may then keep reusing the fallback-built plan even after the missing stats have been loaded.

### What changed and how does it work?
This PR simplifies the fix by treating sync-load timeout fallback as a non-cacheable planning path.

When sync-load falls back and `tidb_stats_load_pseudo_timeout` allows the statement to continue, TiDB now marks that statement as `skip plan cache`.

This means:
- plans built under sync-load timeout fallback are never inserted into the plan cache
- no special fresh-stats invalidation is needed for those fallback-built plans later
- once the needed stats are loaded, a later execution can build and cache a fresh plan normally

### Check List

Tests 

- [x] Unit test
  - `make failpoint-enable`
  - `go test -run TestPreparedPlanCacheInvalidatedAfterSyncLoadTimeoutFallback -tags=intest,deadlock ./pkg/planner/core/casetest/planstats`
  - `go test -run 'TestLRUPCPut|TestInstancePlanCacheWithMatchOpts' -tags=intest,deadlock ./pkg/planner/core`
  - `make failpoint-disable`
  - `make lint`
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [x] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug where plans built under sync-load timeout fallback could be cached and reused after the needed stats were loaded.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed query plan caching to be skipped when synchronous statistics loading times out.

* **Tests**
  * Added test coverage for plan cache behavior during statistics loading timeouts.

### CODE REVIEW

File: pkg/planner/core/plan_cache_utils.go [hunk 1]
```diff
@@ -665,16 +668,55 @@ func NewPlanCacheValue(
...
+				return true
+			}
+			continue
+		}
+		if col := statsTbl.GetCol(item.ID); col != nil && col.IsFullLoad() {
+			return true
+		}
+	}
+	return false
+}
```
Comment (winoros) [inline pkg/planner/core/plan_cache_utils.go]: This check is a little heavy. But this will ensure that the plan cache will not be invalidated for the case:
- When we cache the plan, all stats are in memory
- Due to some reason, like we hit the stats memory limitation, then eviction happens.
- The stats load failed at this time.

If we invalidate the cache for this case, it will increase the possibility of wrong plan generation.

Thus, I think this check is reasonable.

File: pkg/planner/core/plan_cache_utils.go [hunk 2]
```diff
@@ -665,16 +669,55 @@ func NewPlanCacheValue(
...
```
[the remark this answers is not in the document]
Comment (winoros) [reply pkg/planner/core/plan_cache_utils.go]: I may create a seperate pr to make the instance-level plan cache be able to evict specific cache keys first.

File: pkg/planner/core/plan_cache_utils.go [hunk 3]
```diff
@@ -665,16 +669,55 @@ func NewPlanCacheValue(
...
 }
 
+func cloneSyncLoadFallbackItemsForPlanCache(enabled bool, items []model.TableItemID) []model.TableItemID {
+	if !enabled || len(items) == 0 {
+		return nil
+	}
+	return slices.Clone(items)
+}
+
+func shouldInvalidatePlanCacheForFreshStats(sctx sessionctx.Context, pcv *PlanCacheValue) bool {
```
Comment (qw4990) [inline pkg/planner/core/plan_cache_utils.go]: Could we simplify this implementation? For example, we just record whether this query has a sync-load failure, if yes, we just skip caching this query's plan. The assumption here is that we assume sync-load failure is a temporary case, and we shouldn't cache any plan based on this temporary failure.

File: pkg/planner/core/plan_cache_utils.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (winoros) [reply pkg/planner/core/plan_cache_utils.go]: This pr is refined in a new way.

File: pkg/planner/core/plan_cache_utils.go (hunk 3 above)
Comment (winoros) [reply pkg/planner/core/plan_cache_utils.go]: Now it's aligned with the comment
