### PR TITLE
session: add summary field to tidb_background_subtask_history

### LINKED ISSUE #54241: v7.5.2(upgrade from 7.1.5) show import jobs report `unknow column summary`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2024/06/25 09:17:18.256 +08:00] [INFO] [conn.go:1116] ["command dispatched failed"] [conn=4080637346] [session_alias=] [connInfo="id:4080637346, addr:172.21.82.187:45984 status:10, collation:utf8_general_ci, user:lightling"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="show import jobs"] [txn_mode=PESSIMISTIC] [timestamp=0] [err="[planner:1054]Unknown column 'summary' in 'field list'\ngithub.com/pingcap/errors.AddStack\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175\ngithub.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).toColumn\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:2204\ngithub.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).Leave\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:1258\ngithub.com/pingcap/tidb/pkg/parser/ast.(*ColumnName).Accept\n\t/workspace/source/tidb/pkg/parser/ast/expressions.go:534\ngithub.com/pingcap/tidb/pkg/parser/ast.(*ColumnNameExpr).Accept\n\t/workspace/source/tidb/pkg/parser/ast/expressions.go:596\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).rewriteExprNode\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:201\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).rewriteWithPreprocess\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:146\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildProjection\n\t/workspace/source/tidb/pkg/planner/core/logical_plan_builder.go:1804\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildSelect\n\t/workspace/source/tidb/pkg/planner/core/logical_plan_builder.go:4597\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).Build\n\t/workspace/source/tidb/pkg/planner/core/planbuilder.go:859\ngithub.com/pingcap/tidb/pkg/planner.buildLogicalPlan\n\t/workspace/source/tidb/pkg/planner/optimize.go:576\ngithub.com/pingcap/tidb/pkg/planner.optimize\n\t/workspace/source/tidb/pkg/planner/optimize.go:494\ngithub.com/pingcap/tidb/pkg/planner.Optimize\n\t/workspace/source/tidb/pkg/planner/optimize.go:352\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile\n\t/workspace/source/tidb/pkg/executor/compiler.go:98\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\t/workspace/source/tidb/pkg/session/session.go:2221\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal\n\t/workspace/source/tidb/pkg/session/session.go:1657\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.ExecSQL\n\t/workspace/source/tidb/pkg/disttask/framework/storage/task_table.go:97\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).GetSubtasksForImportInto.func1\n\t/workspace/source/tidb/pkg/disttask/framework/storage/task_table.go:924\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewTxn.func1\n\t/workspace/source/tidb/pkg/disttask/framework/storage/task_table.go:168\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewSession\n\t/workspace/source/tidb/pkg/disttask/framework/storage/task_table.go:144\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewTxn\n\t/workspace/source/tidb/pkg/disttask/framework/storage/task_table.go:150\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).GetSubtasksForImportInto\n\t/workspace/source/tidb/pkg/disttask/framework/storage/task_table.go:913\ngithub.com/pingcap/tidb/pkg/disttask/importinto.GetTaskImportedRows\n\t/workspace/source/tidb/pkg/disttask/importinto/job.go:269\ngithub.com/pingcap/tidb/pkg/executor.handleImportJobInfo\n\t/workspace/source/tidb/pkg/executor/show.go:2300\ngithub.com/pingcap/tidb/pkg/executor.(*ShowExec).fetchShowImportJobs\n\t/workspace/source/tidb/pkg/executor/show.go:2347\ngithub.com/pingcap/tidb/pkg/executor.(*ShowExec).fetchAll\n\t/workspace/source/tidb/pkg/executor/show.go:288\ngithub.com/pingcap/tidb/pkg/executor.(*ShowExec).Next\n\t/workspace/source/tidb/pkg/executor/show.go:131\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/workspace/source/tidb/pkg/executor/internal/exec/executor.go:283\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).next\n\t/workspace/source/tidb/pkg/executor/adapter.go:1216\ngithub.com/pingcap/tidb/pkg/executor.(*recordSet).Next\n\t/workspace/source/tidb/pkg/executor/adapter.go:156\ngithub.com/pingcap/tidb/pkg/server/internal/resultset.(*tidbResultSet).Next\n\t/workspace/source/tidb/pkg/server/internal/resultset/resultset.go:62"]
```

it's because we didn't add `summary` column for the history table, see
https://github.com/pingcap/tidb/blob/8bf55a4d6958ecd5a442f19cb13019411bbe0bbf/pkg/session/bootstrap.go#L2819-L2824

new created clusters of version >= 7.5.0 are not affected

a temp workaround is to add the column manually using
```sql
ALTER TABLE mysql.tidb_background_subtask_history ADD COLUMN `summary` JSON
```

### 4. What is your TiDB version? (Required)
7.5.2

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #54241

Problem Summary:

### What changed and how does it work?

- Add summary field to tidb_background_subtask_history.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]

File: pkg/session/bootstrap_test.go [hunk 1]
```diff
@@ -2321,3 +2321,42 @@ func TestTiDBUpgradeWithDistTaskRunning(t *testing.T) {
...
+	require.Equal(t, int64(ver210), ver)
+	MustExec(t, seV210, "alter table mysql.tidb_background_subtask_history drop column summary;")
+
+	dom, err := BootstrapSession(store)
+	require.NoError(t, err)
+	ver, err = getBootstrapVersion(seV210)
+	require.NoError(t, err)
+	require.Less(t, int64(ver210), ver)
+
+	r := MustExecToRecodeSet(t, seV210, "select count(summary) from mysql.tidb_background_subtask_history;")
```
Comment (D3Hunter) [inline pkg/session/bootstrap_test.go:2354]: can you add a test to check history has same columns as normal one using sql like below?
```
select (select group_concat(column_name) from information_schema.columns where table_name='tidb_background_subtask' order by ordinal_position) = (select group_concat(column_name) from information_schema.columns where table_name='tidb_background_subtask_history' order by ordinal_position);

select (select group_concat(column_name) from information_schema.columns where table_name='tidb_global_task' order by ordinal_position) = (select group_concat(column_name) from information_schema.columns where table_name='tidb_global_task_history' order by ordinal_position);
```

**Review by D3Hunter — APPROVED** [review]
