### PR TITLE
expression: fix different types compare error

### LINKED ISSUE #20128: different types compare error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
# case 1
use test;
drop table if exists t;
create table t(b enum('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z') DEFAULT NULL, c decimal(40,20));
insert into t values('z', 19.18040000000000000000);
select * from t where t.b > t.c;

# case 2
drop table if exists t;
create table t(a bit(64), b double);
insert into t values(-21172, -11623);
select * from t where a < b;
```

### 2. What did you expect to see? (Required)
```
# case 1
mysql> create table t(b enum('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z') DEFAULT NULL, c decimal(40,20));
Query OK, 0 rows affected (0.08 sec)

mysql> insert into t values('z', 19.18040000000000000000);
Query OK, 1 row affected (0.01 sec)

mysql> select * from t where t.b > t.c;
+------+-------------------------+
| b    | c                       |
+------+-------------------------+
| z    | 19.18040000000000000000 |
+------+-------------------------+
1 row in set (0.00 sec)

# case 2
mysql> drop table if exists t;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t(a bit(64), b double);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values(-21172, -11623);
Query OK, 1 row affected (0.00 sec)

mysql> select * from t where a < b;
+----------+--------+
| a        | b      |
+----------+--------+
| �������L        | -11623 |
+----------+--------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
# case 1
mysql> create table t(b enum('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z') DEFAULT NULL, c decimal(40,20));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values('z', 19.18040000000000000000);
Query OK, 1 row affected (0.00 sec)

mysql> select * from t where t.b > t.c;
Empty set, 1 warning (0.00 sec)

# case 2
mysql> drop table if exists t;
Query OK, 0 rows affected (0.19 sec)

mysql> create table t(a bit(64), b double);
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t values(-21172, -11623);
Query OK, 1 row affected (0.01 sec)

mysql> select * from t where a < b;
Empty set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

master f6d445c7af707edd34f4f74d657d278c5aeab4d7 and release-4.0 0fbe796e98399fc988911170b6711bfebf44bd46

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 900

## Mentor

* @XuHuaiyu

### PR DESCRIPTION
**Pull request by zhaoxugang**
### What problem does this PR solve?

Issue Number: close #20128 

Problem Summary:

### What is changed and how it works?
What's Changed:
fix different types compare error
How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

- fix different types compare error

### CODE REVIEW

File: expression/builtin.go [hunk 1]
```diff
@@ -255,6 +259,31 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, funcName string, args []Ex
 	return bf, nil
 }
 
+func generateRetFlag(res Expression, evalType types.EvalType, args []Expression) {
```
[the remark this answers is not in the document]
Comment (zhaoxugang) [reply expression/builtin.go:265]: done

**Comment by XuHuaiyu** [comment]
PTAL @wshwsh12

File: expression/builtin.go [hunk 2]
```diff
@@ -258,6 +262,34 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, funcName string, args []Ex
...
+	if len(args) < 2 {
+		return
+	}
+	var retType = res.GetType()
+	lhs, rhs := args[0], args[1]
+	if fun, ok := res.(*ScalarFunction); (ok && fun.FuncName.L == ast.Cast) || res.GetType().Tp == mysql.TypeBit {
+		if evalType == types.ETInt || evalType == types.ETReal {
+			lfg, rfg := args[0].GetType().Flag, args[1].GetType().Flag
+			// set signedFlag to 0 when bit convert explicitly or implicitly to int or real
```
Comment (wshwsh12) [inline expression/builtin.go:274]: I can't understand the logic.  In the case, all evalType.flag don't contain UnsignedFlag, I think.  Could you provide an example?
```
drop table if exists t;
create table t(a bit(64), b double);
insert into t values(-21172, -11623);
select * from t where a < b;
```

I have a try, only add builtin_cast.goL487 and builtin_cast_vec.goL111, it also works. Is there any negligence in what I thought?

File: expression/builtin.go [hunk 3]
```diff
@@ -258,6 +262,34 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, funcName string, args []Ex
...
+				retType.Flag |= mysql.UnsignedFlag
+				if mysql.TypeBit == rhs.GetType().Tp {
+					retType.Flag &= ^(mysql.UnsignedFlag ^ lfg)
+				} else {
+					retType.Flag &= ^(mysql.UnsignedFlag ^ rfg)
+				}
+			}
+		} else if evalType == types.ETDecimal && (mysql.TypeEnum == lhs.GetType().Tp || mysql.TypeEnum == rhs.GetType().Tp) {
+			// set Flen and Decimal as unspecified length(-1) when the enum type is compare with decimal type,avoid loss of data,
+			// like the enum'z'(26), wher Flen=2,Decimal=2 the enum=26.00 but when Flen= 1,Decimal=2 the enum=9
```
Comment (wshwsh12) [inline expression/builtin.go:285]: I think the logic is wrong..  When comparing enum and decimal, we should cast both enum and decimal to double....
In mysql 8.0, 
```
MySQL [test]> desc format=tree select * from t where t.b > t.c;
+------------------------------------------------------------------------------------------------------------------------+
| EXPLAIN                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------+
| -> Filter: (cast(t.b as double) > cast(t.c as double))  (cost=0.35 rows=1)
    -> Table scan on t  (cost=0.35 rows=1)
 |
+------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.004 sec)

```
In tidb, enum will convert to decimal.
```
[tidb]> desc select * from t where t.b > t.c;
+-------------------------+---------+-----------+---------------+--------------------------------+
| id                      | estRows | task      | access object | operator info                  |
+-------------------------+---------+-----------+---------------+--------------------------------+
| Selection_5             | 0.80    | root      |               | gt(cast(test.t.b), test.t.c)   |
| └─TableReader_7         | 1.00    | root      |               | data:TableFullScan_6           |
|   └─TableFullScan_6     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-------------------------+---------+-----------+---------------+--------------------------------+
3 rows in set (0.000 sec)
```

File: expression/builtin.go (hunk 2 above)
Comment (zhaoxugang) [reply expression/builtin.go:274]: I removed builtin.goL173,it not work,for this case i see the step:
1.Invoke GetAccurateCmpType() output ETReal
2.Invoke newBaseBuiltinFuncWithTp() 
    in this method the param a will produce the scalarFunction named cast,retFlag=160,arg's retFlag=32  by WrapWithCastAsReal()
so in builtin_cast_vec.goL111 the unsignedArgs0=true,the a will change to uint.

File: expression/builtin.go (hunk 3 above)
Comment (zhaoxugang) [reply expression/builtin.go]: done,I don't know why convert enum,decimal to double but not convert enum to decimal

Comment (zhaoxugang) [reply expression/builtin.go]: done,I don't know why convert enum,decimal to double but not convert enum to decimal

File: expression/builtin.go (hunk 2 above)
Comment (wshwsh12) [reply expression/builtin.go:274]: Why the flag for column a is 32..? It doesn't has the unsigned flag when creating table.

Comment (wshwsh12) [reply expression/builtin.go:274]: If cast a as double explicitly, it works... 
```
[tidb]>  select * from t where cast(a as double) < b;
+----------+--------+
| a        | b      |
+----------+--------+
| �������L        | -11623 |
+----------+--------+
1 row in set (5.925 sec)

```

Comment (zhaoxugang) [reply expression/builtin.go:274]: in ddl_api.goL537 invoke col.Flag |= mysql.UnsignedFlag when create table,
you mean i should't change retFlag in generateRetFlag, but cast bit,decimal to double?

Comment (wshwsh12) [reply expression/builtin.go]: I have a try in mysql8.0.22..   So the behavior in tidb is right? It maybe a bug in mysql8.0.21 and the previous version?
```
MySQL [test]> select version();
+-----------+
| version() |
+-----------+
| 8.0.22    |
+-----------+
1 row in set (0.000 sec)

MySQL [test]> drop table if exists t;
Query OK, 0 rows affected (0.006 sec)

MySQL [test]> create table t(a bit(64), b double);
Query OK, 0 rows affected (0.009 sec)

MySQL [test]> insert into t values(-21172, -11623);
Query OK, 1 row affected (0.002 sec)

MySQL [test]> select * from t where a < b;
Empty set (0.000 sec)
```

But in mysql8.0.21,
```
MySQL [test]> select version();
+-----------+
| version() |
+-----------+
| 8.0.21    |
+-----------+
1 row in set (0.000 sec)

MySQL [test]> drop table if exists t;
Query OK, 0 rows affected (0.007 sec)

MySQL [test]> create table t(a bit(64), b double);
Query OK, 0 rows affected (0.008 sec)

MySQL [test]> insert into t values(-21172, -11623);
Query OK, 1 row affected (0.001 sec)

MySQL [test]> select * from t where a < b;
+----------+--------+
| a        | b      |
+----------+--------+
| �������L        | -11623 |
+----------+--------+
1 row in set (0.000 sec)

```

File: expression/builtin.go [hunk 4]
```diff
@@ -906,3 +910,25 @@ func GetBuiltinList() []string {
 	sort.Strings(res)
 	return res
 }
+
+func generateRetFlag(res Expression, evalType types.EvalType, args []Expression) {
```
Comment (wshwsh12) [inline expression/builtin.go:914]: Could we remove the logic?

Comment (zhaoxugang) [reply expression/builtin.go:914]: I think your mean is I should closed this pull request?

Comment (zhaoxugang) [reply expression/builtin.go]: done

File: expression/integration_test.go [hunk 5]
```diff
@@ -8293,6 +8293,21 @@ func (s *testIntegrationSuite) TestIssue12205(c *C) {
 		testkit.Rows("Warning 1292 Truncated incorrect time value: '18446744072635875000'"))
 }
 
+// for issue 20128
+func (s *testIntegrationSerialSuite) TestIssue20128(c *C) {
+	collate.SetNewCollationEnabledForTest(true)
+	defer collate.SetNewCollationEnabledForTest(false)
```
Comment (wshwsh12) [inline expression/integration_test.go:8299]: Remove these lines.

**Review by wshwsh12 — COMMENTED** [review]
Rest LGTM

**Comment by wshwsh12** [comment]
Please resolve conflicts.

File: expression/integration_test.go (hunk 5 above)
Comment (zhaoxugang) [reply expression/integration_test.go]: done

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — COMMENTED** [review]
Please resolve conflicts.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
