### PR TITLE
pitr: add ingest recorder to repair indexes

### LINKED ISSUE #41668: compatibility between pitr and accelerated indexing
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start log backup
2. add 5000 rows
3. add an index
4. restore to anthoer cluster

### 2. What did you expect to see? (Required)
1. the upstream cluster use accelerated indexing
2. the data recovery is complete

### 3. What did you see instead (Required)
either the upstream cluster doesn't use accelerated indexing, or data recovery is not complete.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #41668  ref #38045

Problem Summary:
PiTR is not compatible with accelerated indexing
### What is changed and how it works?
1. record the ingest indexes from history ddl
2. drop the indexes
3. re-add the indexes
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

upstream SQL
```SQL
CREATE TABLE test.pairs(x int auto_increment primary key, y int DEFAULT RAND(), z int DEFAULT RAND());
INSERT INTO test.pairs VALUES (), ... (skip 500), ();
ALTER TABLE test.pairs ADD INDEX i1(y, z) USING HASH COMMENT "edelw;fe?fewfe\nefwe" INVISIBLE;
ALTER TABLE test.pairs ADD UNIQUE KEY u1(x, y) USING RTREE VISIBLE;
ALTER TABLE test.pairs ADD INDEX i2(y, (z + 1)) USING BTREE COMMENT "123";
ALTER TABLE test.pairs ADD UNIQUE KEY u2(x, (y+1)) USING HASH COMMENT "243";

CREATE TABLE test.pairs2(x int, y int, z varchar(20));
INSERT INTO test.pairs2 VALUES (1,1,"1"), ... (skip 500), (500,500,"500");
ALTER TABLE test.pairs2 ADD INDEX i1(y, z(10));
ALTER TABLE test.pairs2 ADD UNIQUE KEY u1(y, z(10), (y * 2)) USING RTREE VISIBLE;
ALTER TABLE test.pairs2 ADD PRIMARY KEY (x) USING HASH;

CREATE TABLE test.pairs3(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, name CHAR(10), custinfo JSON);
INSERT INTO test.pairs3 VALUES (1, 'pingcap', '{"zipcode": [1,2]}');
ALTER TABLE test.pairs3 ADD INDEX zips2((CAST(custinfo->'$.zipcode' AS UNSIGNED ARRAY)));

CREATE TABLE test.pairs4(x int auto_increment primary key, y int DEFAULT RAND(), z int DEFAULT RAND());
INSERT INTO test.pairs4 VALUES (), ... (skip 500), ();
ALTER TABLE test.pairs4 ADD INDEX i1(y, z) USING HASH COMMENT "edelw;fe?fewfe\nefwe" INVISIBLE;
ALTER TABLE test.pairs4 ADD UNIQUE KEY u1(x, y) USING RTREE VISIBLE;
ALTER TABLE test.pairs4 ADD INDEX i2(y, (z + 1)) USING BTREE COMMENT "123";
ALTER TABLE test.pairs4 ADD UNIQUE KEY u2(x, (y+1)) USING HASH COMMENT "243";
ALTER TABLE test.pairs4 DROP INDEX i1;
ALTER TABLE test.pairs4 DROP INDEX u1;
ALTER TABLE test.pairs4 DROP INDEX i2;
ALTER TABLE test.pairs4 DROP INDEX u2;

CREATE TABLE test.pairs5(x int, y int, z varchar(20));
INSERT INTO test.pairs5 VALUES (1,1,"1"), ... (skip 500), (500,500,"500");
ALTER TABLE test.pairs5 ADD INDEX i1(y, z(10));
ALTER TABLE test.pairs5 ADD UNIQUE KEY u1(y, z(10), (y * 2)) USING RTREE VISIBLE;
ALTER TABLE test.pairs5 ADD PRIMARY KEY (x) USING HASH;
ALTER TABLE test.pairs5 DROP INDEX i1;
ALTER TABLE test.pairs5 DROP INDEX u1;
ALTER TABLE test.pairs5 DROP INDEX `PRIMARY`;

CREATE TABLE test.pairs6(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, `nam``;e` int, `cust``;info` JSON);
INSERT INTO test.pairs6 VALUES (1, 1, '{"zipcode": [1,2]}');
ALTER TABLE test.pairs6 ADD INDEX zips2((CAST(`cust``;info`->'$.zipcode' AS UNSIGNED ARRAY)));
ALTER TABLE test.pairs6 ADD INDEX i1(`nam``;e`, (`nam``;e` * 2));
RENAME TABLE test.pairs6 TO test.pairs7;
ALTER TABLE test.pairs7 RENAME INDEX i1 to i2;
```

restore repair ingest index SQL from BR log
```SQL
ALTER TABLE `test`.`pairs` DROP INDEX `i1`
ALTER TABLE `test`.`pairs` ADD INDEX `i1`(`y`,`z`) USING HASH COMMENT 'edelw;fe?fewfe\\nefwe' INVISIBLE
ALTER TABLE `test`.`pairs` DROP INDEX `u1`
ALTER TABLE `test`.`pairs` ADD UNIQUE KEY `u1`(`x`,`y`) USING RTREE VISIBLE
ALTER TABLE `test`.`pairs` DROP INDEX `i2`
ALTER TABLE `test`.`pairs` ADD INDEX `i2`(`y`,(`z` + 1)) USING BTREE COMMENT '123' VISIBLE
ALTER TABLE `test`.`pairs` DROP INDEX `u2`
ALTER TABLE `test`.`pairs` ADD UNIQUE KEY `u2`(`x`,(`y` + 1)) USING HASH COMMENT '243' VISIBLE
ALTER TABLE `test`.`pairs2` DROP INDEX `PRIMARY`
ALTER TABLE `test`.`pairs2` ADD PRIMARY KEY (`x`) NONCLUSTERED USING HASH VISIBLE
ALTER TABLE `test`.`pairs2` DROP INDEX `i1`
ALTER TABLE `test`.`pairs2` ADD INDEX `i1`(`y`,`z`(10)) USING BTREE VISIBLE
ALTER TABLE `test`.`pairs2` DROP INDEX `u1`
ALTER TABLE `test`.`pairs2` ADD UNIQUE KEY `u1`(`y`,`z`(10),(`y` * 2)) USING RTREE VISIBLE
ALTER TABLE `test`.`pairs3` DROP INDEX `zips2`
ALTER TABLE `test`.`pairs3` ADD INDEX `zips2`((cast(json_extract(`custinfo`, _utf8'$.zipcode') as unsigned array))) USING BTREE VISIBLE
ALTER TABLE `test`.`pairs7` DROP INDEX `zips2`
ALTER TABLE `test`.`pairs7` ADD INDEX `zips2`((cast(json_extract(`cust``;info`, _utf8'$.zipcode') as unsigned array))) USING BTREE VISIBLE
ALTER TABLE `test`.`pairs7` DROP INDEX `i2`
ALTER TABLE `test`.`pairs7` ADD INDEX `i2`(`nam``;e`,(`nam``;e` * 2)) USING BTREE VISIBLE
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/client.go [hunk 1]
```diff
@@ -2535,6 +2536,35 @@ func (rc *Client) UpdateSchemaVersion(ctx context.Context) error {
 	return nil
 }
 
+const (
+	alterTableDropIndexFormat  = "ALTER TABLE `%s`.`%s` DROP INDEX `%s`;"
+	alterTableAddIndexFormat   = "ALTER TABLE `%s`.`%s` ADD INDEX `%s`(%s);"
+	alterTableAddPrimaryFormat = "ALTER TABLE `%s`.`%s` ADD PRIMARY KEY (%s)"
```
Comment (Benjamin2037) [inline br/pkg/restore/client.go:2542]: here, currently, do not support clusterd PK online changed. also should care able add unique index.

File: br/pkg/restore/client.go [hunk 2]
```diff
@@ -2535,6 +2536,35 @@ func (rc *Client) UpdateSchemaVersion(ctx context.Context) error {
...
+)
+
+// RepairIngestIndex drops the indexes from IngestRecorder and re-add them.
+func (rc *Client) RepairIngestIndex(ctx context.Context, ingestRecorder *ingestrec.IngestRecorder) error {
+	err := ingestRecorder.Iterate(func(_ int64, _ int64, info ingestrec.IngestIndexInfo) error {
+		var dropSQL string = fmt.Sprintf(alterTableDropIndexFormat, info.SchemaName, info.TableName, info.IndexName)
+		var addSQL string
+		if info.IsPrimary {
+			addSQL = fmt.Sprintf(alterTableAddPrimaryFormat, info.SchemaName, info.TableName, info.ColumnList)
+		} else {
```
Comment (Benjamin2037) [inline br/pkg/restore/client.go:2552]: Add generate uk statement

File: br/pkg/restore/ingestrec/ingest_recorder.go [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+		tableindexes = make(map[int64]*IngestIndexInfo)
+		i.items[job.TableID] = tableindexes
+	}
+
+	// the current information of table/index might be modified by other ddl jobs,
+	// therefore update the index information at last
+	tableindexes[indexID] = &IngestIndexInfo{
+		IsPrimary: job.Type == model.ActionAddPrimaryKey,
+		Updated:   false,
+	}
```
Comment (tangenta) [inline br/pkg/restore/ingestrec/ingest_recorder.go:102]: Why not record `job.Query` as the SQL?

File: br/pkg/restore/client.go [hunk 4]
```diff
@@ -2535,6 +2536,68 @@ func (rc *Client) UpdateSchemaVersion(ctx context.Context) error {
...
+		addSQL = fmt.Sprintf("%s%s%s%s", addSQL, indexTypeSQL, commentSQL, visibleSQL)
+
+		log.Debug("repair ingest sql", zap.String("drop", dropSQL))
+		if err := rc.db.se.Execute(ctx, dropSQL); err != nil {
+			return errors.Trace(err)
+		}
+		log.Debug("repair ingest sql", zap.String("add", addSQL))
+		if err := rc.db.se.ExecuteInternal(ctx, addSQL, info.IndexInfo.Comment); err != nil {
+			return errors.Trace(err)
+		}
```
[the remark this answers is not in the document]
Comment (Leavrth) [reply br/pkg/restore/client.go:2595]: Because the `Comment` has some escape characters such as `"` and `\n`, so here use `ExecuteInter` to send with args instead of plaintext.
The function pattern is as follow:
`Execute(context, sql string)`
`ExecuteInternal(context, sql string, args...)`

File: br/pkg/restore/ingestrec/ingest_recorder.go (hunk 3 above)
Comment (Leavrth) [reply br/pkg/restore/ingestrec/ingest_recorder.go:102]: Beacuse the record `job.Query` is not the final information.
In the upstream cluster, we first create an index by `ALTER TABLE test.pairs ADD INDEX i1(x, y)`.
Then we rename something such like `RENAME TABLE test.pairs TO test.pairs2`.

When we do restore, the ingest job's `Query` we get is `ALTER TABLE test.pairs ADD INDEX i1(x, y)`. However, the table `test.pairs` is not exists currently.

File: br/pkg/restore/client.go [hunk 5]
```diff
@@ -2535,6 +2536,68 @@ func (rc *Client) UpdateSchemaVersion(ctx context.Context) error {
...
+		var (
+			dropSQL      string = fmt.Sprintf(alterTableDropIndexFormat, info.SchemaName, info.TableName, info.IndexInfo.Name.O)
+			addSQL       string
+			indexTypeSQL string
+			commentSQL   string
+			visibleSQL   string = " VISIBLE"
+		)
+
+		if info.IsPrimary {
+			addSQL = fmt.Sprintf(alterTableAddPrimaryFormat, info.SchemaName, info.TableName, info.ColumnList)
```
Comment (YuJuncen) [inline br/pkg/restore/client.go:2565]: Should we escape here? Perhaps some guys like to name their indices like(How absurd!):
```SQL
CREATE INDEX `idx``; DROP DATABASE business; --`(some_row);
```

Comment (Leavrth) [reply br/pkg/restore/client.go]: done. test updated

File: br/pkg/restore/client.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (Leavrth) [reply br/pkg/restore/client.go]: done, both use `ExecuteInternal`.

File: br/pkg/restore/client.go [hunk 6]
```diff
@@ -2754,6 +2819,38 @@ func (rc *Client) ResetTiFlashReplicas(ctx context.Context, g glue.Glue, storage
 	})
 }
 
+// RangeFilterFromIngestRecorder rewrites the table id of items in the ingestRecorder
+// TODO: need to implement the range filter out feature
+func (rc *Client) RangeFilterFromIngestRecorder(recorder *ingestrec.IngestRecorder, rewriteRules map[int64]*RewriteRules) error {
+	filter := rtree.NewRangeTree()
```
Comment (tangenta) [inline br/pkg/restore/client.go:2825]: What is the `filter` used for?

**Review by tangenta — APPROVED** [review]

File: br/pkg/restore/client.go [hunk 7]
```diff
@@ -2535,6 +2536,70 @@ func (rc *Client) UpdateSchemaVersion(ctx context.Context) error {
...
+	dom, err := g.GetDomain(storage)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	info := dom.InfoSchema()
+	allSchema := info.AllSchemas()
+	ingestRecorder.UpdateIndexInfo(allSchema)
+	err = ingestRecorder.Iterate(func(_, _ int64, info *ingestrec.IngestIndexInfo) error {
+		var (
+			addSQL  string
```
Comment (YuJuncen) [inline br/pkg/restore/client.go:2557]: Perhaps use `strings.Builder` here?

**Review by YuJuncen — APPROVED** [review]
rest lgtm

File: br/pkg/restore/client.go (hunk 7 above)
Comment (Leavrth) [reply br/pkg/restore/client.go]: done

**Comment by Leavrth** [comment]
add progress for repair ingest index
2884e86f-ed72-4e50-b76e-2f838fea2ef8

**Review by YuJuncen — APPROVED** [review]
LGTM for the PB part
