### PR TITLE
ddl: create temp dir automatically for adding index

### LINKED ISSUE #45456: Add index causes DDL to get stuck when the temp dir does not exist
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create a TiDB cluster and bootstrap it.
2. Remove the directory `/tmp/tmp_ddl-4000`.
3. Turn on the fast add index feature: `set global tidb_ddl_enable_fast_reorg = 1`.
4. Add index for an arbitrary table.

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

DDL hangs.

```
[2023/07/19 09:36:45.117 +08:00] [INFO] [ddl_worker.go:981] ["run DDL job"] [worker="worker 2, tp add index"] [category=ddl] [job="ID:150, Type:add index, State:running, SchemaState:none, SchemaID:2, TableID:148, RowCount:0, ArgLen:0, start time: 2023-07-19 09:36:39.884 +0800 CST, Err:[ddl:-1]cannot get disk capacity at /tmp/tidb/tmp_ddl-4000: no such file or directory, ErrCount:5, SnapshotVersion:0, UniqueWarnings:0"]
[2023/07/19 09:36:45.118 +08:00] [INFO] [index.go:620] ["run add index job"] [category=ddl] [job="ID:150, Type:add index, State:running, SchemaState:none, SchemaID:2, TableID:148, RowCount:0, ArgLen:6, start time: 2023-07-19 09:36:39.884 +0800 CST, Err:[ddl:-1]cannot get disk capacity at /tmp/tidb/tmp_ddl-4000: no such file or directory, ErrCount:5, SnapshotVersion:0, UniqueWarnings:0"] [indexInfo="{\"id\":1,\"idx_name\":{\"O\":\"idx\",\"L\":\"idx\"},\"tbl_name\":{\"O\":\"\",\"L\":\"\"},\"idx_cols\":[{\"name\":{\"O\":\"k\",\"L\":\"k\"},\"offset\":2,\"length\":-1}],\"state\":0,\"backfill_state\":0,\"comment\":\"\",\"index_type\":1,\"is_unique\":false,\"is_primary\":false,\"is_invisible\":false,\"is_global\":false,\"mv_index\":false}"]
[2023/07/19 09:36:45.118 +08:00] [INFO] [backend_mgr.go:78] ["ingest backfill is not available"] [category=ddl-ingest] [error="cannot get disk capacity at /tmp/tidb/tmp_ddl-4000: no such file or directory"]
[2023/07/19 09:36:45.118 +08:00] [WARN] [ddl_worker.go:943] ["run DDL job error"] [worker="worker 2, tp add index"] [category=ddl] [error="cannot get disk capacity at /tmp/tidb/tmp_ddl-4000: no such file or directory"]
[2023/07/19 09:36:45.124 +08:00] [INFO] [ddl_worker.go:826] ["run DDL job failed, sleeps a while then retries it."] [worker="worker 2, tp add index"] [category=ddl] [waitTime=1s] [error="cannot get disk capacity at /tmp/tidb/tmp_ddl-4000: no such file or directory"]
[2023/07/19 09:36:46.124 +08:00] [INFO] [ddl_worker.go:1191] ["schema version doesn't change"] [category=ddl]
```

### 4. What is your TiDB version? (Required)

17cda10e97

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #45456

Problem Summary:

#43210 added the `PrecheckUsage()` function which depends on the existence of temp dir. However, the automatically creation of temp dir happens after `PrecheckUsage()`. It cause the unexpected behavior.

### What is changed and how it works?

Create temp dir automatically for adding index.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Terminal 1:
```
mysql> alter table t1 add index idx(k);
Query OK, 0 rows affected (2.59 sec)
```

Terminal 2:
```
➜  tidb ls
import-4000
➜  tidb ls
import-4000  tmp_ddl-4000
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

File: ddl/index.go [hunk 1]
```diff
@@ -626,6 +626,12 @@ func (w *worker) onCreateIndex(d *ddlCtx, t *meta.Meta, job *model.Job, isPK boo
 		var reorgTp model.ReorgType
 		reorgTp, err = pickBackfillType(w.ctx, job, indexInfo.Unique, d)
 		if err != nil {
+			if !errorIsRetryable(err, job) {
```
Comment (zimulala) [inline ddl/index.go:629]: Could we cancel it directly which needn't do `convertAddIdxJob2RollbackJob`(Here the job is StateNone) ?

File: ddl/index.go [hunk 2]
```diff
@@ -626,6 +626,9 @@ func (w *worker) onCreateIndex(d *ddlCtx, t *meta.Meta, job *model.Job, isPK boo
...
+				job.State = model.JobStateCancelled
```
Comment (zimulala) [inline ddl/index.go:630]: Do we need to return the error here？Or does it feel like this `err` message might be overwritten?

**Review by zimulala — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM
