### PR TITLE
executor: make  the results of `show create table` more consistent with MySQL

### LINKED ISSUE #9211: "show create table" shows that the generated column is inconsistent with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(c int, b int as (c + 1));
show create table t;
```
2. What did you expect to see?
```
mysql> create table t(c int, b int as (c + 1))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
Query OK, 0 rows affected (0.03 sec)

mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                     |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `c` int(11) DEFAULT NULL,
  `b` int(11) GENERATED ALWAYS AS ((`c` + 1)) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
mysql> create table t(c int, b int as (c + 1))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
Query OK, 0 rows affected (0.03 sec)

tidb> show create table t;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `c` int(11) DEFAULT NULL,
  `b` int(11) GENERATED ALWAYS AS (`c` + 1) VIRTUAL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.0-beta-18-g7648317da
Git Commit Hash: 7648317dad4fe4b076158339fd205dfa76b0d5ea
Git Branch: master
UTC Build Time: 2019-01-28 07:42:09

### PR DESCRIPTION
**Pull request by spongedu**
### What problem does this PR solve? 
Fix issue #9211  , Make results of `show create table` more consistent with MySQL

### What is changed and how it works?
1.  Don't show default values for generated columns
2. Refine demonstration for `CHARSET` for character type columns

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by spongedu** [comment]
@zimulala @zz-jason  PTAL :)

File: executor/show.go [hunk 1]
```diff
@@ -614,7 +615,8 @@ func (e *ShowExec) fetchShowCreateTable() error {
 			if mysql.HasNotNullFlag(col.Flag) {
 				buf.WriteString(" NOT NULL")
 			}
-			if !mysql.HasNoDefaultValueFlag(col.Flag) {
+			// don't show default value for generated columns
```
Comment (xiekeyi98) [inline executor/show.go]: I think we'd better to explain why "not show default value for generated columns".
For example, "Default value are not shown for generated columns in mysql".
The current comment, I think, is the same as the code(a little bit redundant)

Comment (spongedu) [reply executor/show.go]: Reasonable ~

File: executor/show.go [hunk 2]
```diff
@@ -595,8 +595,9 @@ func (e *ShowExec) fetchShowCreateTable() error {
 	var hasAutoIncID bool
 	for i, col := range tb.Cols() {
 		fmt.Fprintf(&buf, "  %s %s", escape(col.Name, sqlMode), col.GetTypeDesc())
-		if col.Charset != "binary" {
-			fmt.Fprintf(&buf, " CHARSET %s COLLATE %s", col.Charset, col.Collate)
+		// charset && collate are not shown for generated columns in MySQL
+		if col.Charset != "binary" && !col.IsGenerated() {
```
Comment (xiekeyi98) [inline executor/show.go]: "Because it is generated , charset and collate are not shown." OR "Because it is generated and charset is binary, charset and collate are not shown".

File: executor/show_test.go [hunk 3]
```diff
@@ -312,6 +312,36 @@ func (s *testSuite2) TestShowCreateTable(c *C) {
...
+	tk.MustExec("create table t ( a char(10) charset utf8 collate utf8_bin, b char(10) as (rtrim(a)));")
+	tk.MustQuery("show create table `t`").Check(testutil.RowsWithSep("|",
+		""+
+			"t CREATE TABLE `t` (\n"+
+			"  `a` char(10) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,\n"+
+			"  `b` char(10) GENERATED ALWAYS AS (rtrim(`a`)) VIRTUAL\n"+
+			") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin",
+	))
+	tk.MustExec("drop table t")
 }
```
Comment (xiekeyi98) [inline executor/show_test.go]: I was wondering if you could add test like this `create table test ( a char(10) charset gb2312 , b char(10) charset utf8 as (rtrim(a)) );`?
BTW, The following is the result of MYSQL:
```sql
mysql> create table test ( a char(10) charset gb2312 , b char(10) charset utf8 as (rtrim(a)) );
Query OK, 0 rows affected (0.02 sec)

mysql> show create table test;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                              |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test  | CREATE TABLE `test` (
  `a` char(10) CHARACTER SET gb2312 DEFAULT NULL,
  `b` char(10) CHARACTER SET utf8 GENERATED ALWAYS AS (rtrim(`a`)) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.7.25-0ubuntu0.18.04.2 |
+-------------------------+
1 row in set (0.00 sec)
```

Comment (spongedu) [reply executor/show_test.go]: @xiekeyi98 I seems make a mistake here. I made several tests and found that whether a column is generated do not actually determine whether `CHARSET` && `COLLATE` are shown.  In fact, it's determined by whether `CHARSET` && `COLLATE` are specified explicitly.  
I'd prefer left it to another issue and make this pr clearer.

BTW, `TiDB` seems don't support `gb2312` for now.
The following are my tests:
```sql
mysql> select version();
+------------+
| version()  |
+------------+
| 5.7.17-log |
+------------+
1 row in set (0.01 sec)

mysql> create table test ( a char(10) charset utf8 , b char(10) charset utf8 as (rtrim(a)) );
Query OK, 0 rows affected (0.03 sec)

mysql> show create table test;
+-------+-------------------------------------------------------------------------------------------------------------------------------------+| Table | Create Table                                                                                                                        |+-------+-------------------------------------------------------------------------------------------------------------------------------------+| test  | CREATE TABLE `test` (
  `a` char(10) CHARACTER SET utf8 DEFAULT NULL,
  `b` char(10) CHARACTER SET utf8 GENERATED ALWAYS AS (rtrim(`a`)) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+-------------------------------------------------------------------------------------------------------------------------------------+1 row in set (0.00 sec)

mysql> drop table test;
Query OK, 0 rows affected (0.02 sec)

mysql> create table test ( a char(10) charset utf8 , b char(10) as (rtrim(a)) );
Query OK, 0 rows affected (0.03 sec)

mysql> show create table test;
+-------+-------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                        |
+-------+-------------------------------------------------------------------------------------------------------------------------------------+
| test  | CREATE TABLE `test` (
  `a` char(10) CHARACTER SET utf8 DEFAULT NULL,
  `b` char(10) GENERATED ALWAYS AS (rtrim(`a`)) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+-------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
mysql> drop table test;
Query OK, 0 rows affected (0.02 sec)

mysql> create table test ( a char(10), b char(10) as (rtrim(a)) );
Query OK, 0 rows affected (0.03 sec)

mysql> show create table test;
+-------+-------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                        |
+-------+-------------------------------------------------------------------------------------------------------------------------------------+
| test  | CREATE TABLE `test` (
  `a` char(10) DEFAULT NULL,
  `b` char(10) GENERATED ALWAYS AS (rtrim(`a`)) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-------+-------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> desc test;
+-------+----------+------+-----+---------+-------------------+
| Field | Type     | Null | Key | Default | Extra             |
+-------+----------+------+-----+---------+-------------------+
| a     | char(10) | YES  |     | NULL    |                   |
| b     | char(10) | YES  |     | NULL    | VIRTUAL GENERATED |
+-------+----------+------+-----+---------+-------------------+
2 rows in set (0.01 sec)

```

Comment (spongedu) [reply executor/show_test.go]: @xiekeyi98 I've opened another issue #9232  for the demonstration of the demonstration of `CHARSET` && `COLLATE`.  It's not related to generated columns, indeed. I'll look into this later.

Comment (xiekeyi98) [reply executor/show_test.go]: Well done. Thanks for you contribution.

Comment (spongedu) [reply executor/show_test.go]: seems you've working on this in #9113  :P

**Comment by xiekeyi98** [comment]
@spongedu 
Would you mind solve the conflicts?
And then I will update the test cases for this PR.

**Comment by spongedu** [comment]
@xiekeyi98 OK

**Comment by spongedu** [comment]
@xiekeyi98  PTAL :)
