### PR TITLE
executor: correct the table range built by 'recover index'

### LINKED ISSUE #32915: admin recover index miss some rows
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
MySQL [test]>  create table t(id bigint(20) primary key, col varchar(255) unique key);
Query OK, 0 rows affected (0.10 sec)

MySQL [test]> insert into t values(9223372036854775807, "test");
Query OK, 1 row affected (0.01 sec)

MySQL [test]> admin recover index t col;
+-------------+------------+
| ADDED_COUNT | SCAN_COUNT |
+-------------+------------+
|           0 |          0 |
+-------------+------------+
1 row in set (0.00 sec)

```

### 2. What did you expect to see? (Required)
SCAN_COUNT should be 1.

### 3. What did you see instead (Required)
截屏2022-03-08 下午6 12 22
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #32915

Problem Summary:

See https://github.com/pingcap/tidb/issues/32915#issuecomment-1061624547:
> The root cause is [here](https://github.com/pingcap/tidb/blob/9c64224c4951fdffb05f284b011c48c50c188a04/executor/admin.go#L302).
codec.EncodeKey(sctx, nil, types.MaxValueDatum() is the byte 250 which is not the unlimited end key.
>
> For intHandle it should becodec.EncodeInt(nil, math.MaxInt64)

### What is changed and how it works?

This PR corrects the table range built by 'recover index'.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix an issue that `admin recover index` cannot recovers for some rows.
```

### CODE REVIEW

File: executor/admin.go [hunk 1]
```diff
@@ -295,15 +294,11 @@ func (e *RecoverIndexExec) buildTableScan(ctx context.Context, txn kv.Transactio
...
 	} else {
-		startKey = tablecodec.EncodeRowKey(tid, startHandle.Next().Encoded())
+		startKey = tablecodec.EncodeRowKey(tid, startHandle.Encoded()).PrefixNext()
 	}
-	maxVal, err := codec.EncodeKey(sctx, nil, types.MaxValueDatum())
-	if err != nil {
-		return nil, errors.Trace(err)
-	}
-	endKey := tablecodec.EncodeRowKey(tid, maxVal)
+	endKey := tablecodec.GenTableRecordPrefix(tid).PrefixNext()
```
Comment (3pointer) [inline executor/admin.go:301]: suppose there exists lots of index keys between `(t_1, t_2)`. will this range scan index keys?

Comment (tangenta) [reply executor/admin.go:301]: No, it does't scan index keys because `GenTableRecordPrefix` represent `"t[tableID]_r"`. So the `PrefixNext` is `"t[tableID]_s"`.

**Review by 3pointer — APPROVED** [review]
LGTM

**Review by Defined2014 — APPROVED** [review]
