### PR TITLE
statstics: correctly handle error when merging global stats

### LINKED ISSUE #47771: merge global stats hold due to meet error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

 run merge global stats

### 2. What did you expect to see? (Required)

it can finish.

### 3. What did you see instead (Required)

it never finishes.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #47771

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/globalstats/globalstats_test.go [hunk 1]
```diff
@@ -76,6 +76,24 @@ func TestGlobalStatsPanicInIOWorker(t *testing.T) {
 	simpleTest(t)
 }
 
+func TestGlobalStatsWithCMSketchErr(t *testing.T) {
```
Comment (qw4990) [inline pkg/statistics/handle/globalstats/globalstats_test.go:79]: Please add 2 more test cases:
1. both IOWorker and CPUWorker error
2. both IOWorker and CPUWorker panic

Comment (hawkingrei) [reply pkg/statistics/handle/globalstats/globalstats_test.go:79]: Done

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
