### PR TITLE
ddl: replace local ingest impl with backfill operators

### LINKED ISSUE #53909: add index blocked after injection network partition between pd leader and all other pods
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb_enable_dist_task='off'
1、run sysbench
2、add index for one of table
3、inject network partition between pd leader and all other pods

tidb logs:
[tidb-0-2024-06-09T22-21-12.334.log.tar.gz](https://github.com/user-attachments/files/15780801/tidb-0-2024-06-09T22-21-12.334.log.tar.gz)
[tidb-1-2024-06-09T22-09-07.701.log.tar.gz](https://github.com/user-attachments/files/15780841/tidb-1-2024-06-09T22-09-07.701.log.tar.gz)

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index blocked after injection network partition between pd leader and all other pods

operator logs：
the status of ddl job is not synced after 1h0m0s (now: 2024-06-09 12:39:47, jobId: 491, job type: add index /* ingest */, state: running)
operatorLogs:
[2024-06-09 11:39:29] ###### start adding index
ALTER TABLE `sbtest1` ADD INDEX `index_test_1717904369842`(`c`)
[2024-06-09 11:39:29] ###### wait for ddl job finish
[2024-06-09 12:39:47] ###### wait for ddl job finish timeout(1h0m0s)
select job_id, job_type, state from information_schema.ddl_jobs where query = 'ALTER TABLE `sbtest1` ADD INDEX `index_test_1717904369842`(`c`)'
jobId: 491, job type: add index /* ingest */, state: running

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: d75ff829f2b28df771ce66a96e10fd031d156b5a
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-08 11:46:12
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-06-09T11:28:46.842+0800

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #53909

Problem Summary: See https://github.com/pingcap/tidb/issues/53909#issuecomment-2187818087

### What changed and how does it work?

Before fixing the context usage, I prefer to unify local ingest and distributed ingest implementation, remove the old `ingestBackfillScheduler`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/sessionctx/variable/tidb_vars.go [hunk 1]
```diff
@@ -1379,7 +1379,7 @@ const (
 	DefTiDBSessionPlanCacheSize                    = 100
 	DefTiDBEnablePrepPlanCacheMemoryMonitor        = true
 	DefTiDBPrepPlanCacheMemoryGuardRatio           = 0.1
-	DefTiDBEnableDistTask                          = true
+	DefTiDBEnableDistTask                          = false // TODO: remove this after CI passed.
```
Comment (tangenta) [inline pkg/sessionctx/variable/tidb_vars.go:1382]: Remove this before merging.

File: pkg/ddl/backfilling_scheduler.go
Comment (lance6716) [inline pkg/ddl/backfilling_scheduler.go:1]: type definition of `newIngestBackfillScheduler` can be removed

File: pkg/ddl/backfilling.go [hunk 2]
```diff
@@ -619,6 +621,146 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
 }
 
+func (dc *ddlCtx) runAddIndexInLocalIngestMode(
+	ctx context.Context,
+	sessPool *sess.Pool,
+	t table.PhysicalTable,
+	reorgInfo *reorgInfo,
+) error {
+	// TODO(tangenta): support adjust worker count dynamically.
+	startKey, endKey := reorgInfo.StartKey, reorgInfo.EndKey
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:631]: move them closer to usage (like line 672), or directly use `reorgInfo.StartKey` and `reorgInfo.EndKey`

File: pkg/ddl/backfilling.go [hunk 3]
```diff
@@ -619,6 +621,146 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+	if err := dc.isReorgRunnable(reorgInfo.Job.ID, false); err != nil {
+		return errors.Trace(err)
+	}
+	job := reorgInfo.Job.Clone()
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:635]: why do we need to clone it?

File: pkg/ddl/backfilling.go [hunk 4]
```diff
@@ -619,6 +621,146 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+	}
+	idxCnt := len(reorgInfo.elements)
+	indexIDs := make([]int64, 0, idxCnt)
+	indexInfos := make([]*model.IndexInfo, 0, idxCnt)
+	uniques := make([]bool, 0, idxCnt)
+	for _, e := range reorgInfo.elements {
+		indexIDs = append(indexIDs, e.ID)
+		indexInfo := model.FindIndexInfoByID(t.Meta().Indices, e.ID)
+		if indexInfo == nil {
+			logutil.DDLIngestLogger().Warn("index info not found",
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:650]: not sure why we have many types of logger (line 636, 661)

File: pkg/ddl/backfilling.go [hunk 5]
```diff
@@ -619,6 +621,146 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+	}
+	err = pipe.Close()
+	if opCtx.OperatorErr() != nil {
+		return opCtx.OperatorErr()
+	}
+	if err != nil {
+		return err
+	}
+	for _, indexID := range indexIDs {
+		err := bcCtx.CollectRemoteDuplicateRows(indexID, t)
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:740]: only collect for unique index? In another comment I added a TODO and we can improve the API of `CollectRemoteDuplicateRows` later

File: pkg/ddl/ingest/backend.go [hunk 6]
```diff
@@ -53,16 +52,6 @@ type BackendCtx interface {
 	// BackendCtx.
 	Register(indexIDs []int64, uniques []bool, tableName string) ([]Engine, error)
 	UnregisterEngines()
-	// FinishImport imports all Register-ed engines of into the storage, collects
-	// the duplicate errors for unique engines.
-	//
-	// TODO(lance6716): unify with CollectRemoteDuplicateRows.
```
Comment (lance6716) [inline pkg/ddl/ingest/backend.go:59]: change this TODO to "remove the indexID argument from CollectRemoteDuplicateRows"

File: pkg/ddl/backfilling.go [hunk 7]
```diff
@@ -619,6 +621,146 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+		logutil.DDLIngestLogger().Warn("create checkpoint manager failed", zap.Error(err))
+	} else {
+		defer cpMgr.Close()
+		cpMgr.Reset(t.GetPhysicalID(), startKey, endKey)
+		bcCtx.AttachCheckpointManager(cpMgr)
+	}
+
+	reorgCtx := dc.getReorgCtx(reorgInfo.Job.ID)
+	previousTotal := reorgCtx.getRowCount()
+	var rowCnt int64
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:692]: I slightly prefer using a member of structure rather than closure. It has better readability. In other words,

newLocalRowCntListener(*reorgCtx)

File: pkg/ddl/ingest/backend.go [hunk 8]
```diff
@@ -156,34 +142,6 @@ func (bc *litBackendCtx) CollectRemoteDuplicateRows(indexID int64, tbl table.Tab
 	return bc.handleErrorAfterCollectRemoteDuplicateRows(err, indexID, tbl, hasDupe)
 }
 
-// FinishImport imports all the key-values in engine into the storage, collects
-// the duplicate errors if any, and removes the engine from the backend context.
-// When duplicate errors are found, it will return ErrKeyExists error.
-func (bc *litBackendCtx) FinishImport(tbl table.Table) error {
-	for _, ei := range bc.engines {
-		if err := ei.ImportAndClean(); err != nil {
```
Comment (lance6716) [inline pkg/ddl/ingest/backend.go:164]: `ImportAndClean()` is also dead code now.

File: pkg/ddl/backfilling.go [hunk 9]
```diff
@@ -619,6 +621,146 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+		job.ID,
+		indexIDs,
+		bcCtx.GetLocalBackend().LocalStoreDir,
+		dc.store.(kv.StorageWithPD).GetPDClient(),
+	)
+	if err != nil {
+		logutil.DDLIngestLogger().Warn("create checkpoint manager failed", zap.Error(err))
+	} else {
+		defer cpMgr.Close()
+		cpMgr.Reset(t.GetPhysicalID(), startKey, endKey)
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:686]: // Reset resets the checkpoint manager between two partitions.

This is not the expected usage of `Reset`. And I see `importStarted` logic is deleted, in this PR which line can we find that the last failure is happened after all data is flushed and we only need to import after resuming?

File: pkg/ddl/backfilling.go (hunk 3 above)
Comment (tangenta) [reply pkg/ddl/backfilling.go:635]: Because in `hasUniqueIndex()`, we call `DecodeArgs`, which destroy `job.Args` with 
```
job.Args = args[:sz]
```

It seems that we can get this information from `indexInfos`. Let me refine the usage by inlining `getBackendCtx`.

File: pkg/ddl/backfilling.go (hunk 9 above)
Comment (tangenta) [reply pkg/ddl/backfilling.go:686]: If all data is flushed, we will `(src *TableScanTaskSource) adjustStartKey` according to the checkpoint manager. Thus, no data will be written again.

File: pkg/ddl/ingest/backend.go (hunk 8 above)
Comment (tangenta) [reply pkg/ddl/ingest/backend.go:165]: Removed in https://github.com/pingcap/tidb/pull/54149/commits/545c9e9c4bd59aa756d688ab4dae9cfdd9248d9d

File: pkg/ddl/ingest/backend.go (hunk 6 above)
Comment (tangenta) [reply pkg/ddl/ingest/backend.go:59]: See https://github.com/pingcap/tidb/pull/54149/commits/545c9e9c4bd59aa756d688ab4dae9cfdd9248d9d

File: pkg/ddl/backfilling.go (hunk 4 above)
Comment (tangenta) [reply pkg/ddl/backfilling.go]: Unified with `tidblogutil.Logger(ctx)`

File: pkg/ddl/backfilling.go (hunk 2 above)
Comment (tangenta) [reply pkg/ddl/backfilling.go]: Changed to `reorgInfo.StartKey` and `reorgInfo.EndKey`. https://github.com/pingcap/tidb/pull/54149/commits/545c9e9c4bd59aa756d688ab4dae9cfdd9248d9d

File: pkg/ddl/backfilling.go (hunk 7 above)
Comment (tangenta) [reply pkg/ddl/backfilling.go]: https://github.com/pingcap/tidb/pull/54149/commits/3dfe9bf9550513720eeb78db844a7e77d20fee03

File: pkg/ddl/backfilling.go (hunk 4 above)
Comment (tangenta) [reply pkg/ddl/backfilling.go:644]: Maybe `logutil.DDLIngestLogger()` is better :)

https://github.com/pingcap/tidb/pull/54149/commits/b81b2c3e10ce84a122ec6d2f4e35581452b840d2

File: pkg/ddl/backfilling.go [hunk 10]
```diff
@@ -619,6 +620,154 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+
+type localRowCntListener struct {
+	EmptyRowCntListener
+	reorgCtx *reorgCtx
+	counter  prometheus.Counter
+
+	// prevPhysicalRowCnt records the row count from previous physical tables (partitions).
+	prevPhysicalRowCnt int64
+	// curPhysicalRowCnt records the row count of current physical table.
+	curPhysicalRowCnt int64
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply pkg/ddl/backfilling.go:758]: it seems it means row count that has been written to disk on last time we run the job

**Comment by wjhuang2016** [comment]
```
    testkit.go:157: 

        	Error Trace:	pkg/testkit/testkit.go:157

        	            				pkg/testkit/testkit.go:150

        	            				pkg/ddl/ingest/tests/partition_table_test.go:58

        	Error:      	Received unexpected error:

        	            	[meta:8235]DDL reorg element does not exist
```

File: pkg/ddl/backfilling.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (tangenta) [reply pkg/ddl/backfilling.go:758]: For now, we process partitions one by one. This value will be shown in `row_count` field of `ADMIN SHOW DDL JOBS`, it does not need to be accurate.

Maybe we can improve this in next PR.

File: pkg/ddl/backfilling.go [hunk 11]
```diff
@@ -619,6 +620,154 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+		bcCtx.GetLocalBackend().LocalStoreDir,
+		dc.store.(kv.StorageWithPD).GetPDClient(),
+	)
+	if err != nil {
+		logutil.DDLIngestLogger().Warn("create checkpoint manager failed",
+			zap.Int64("jobID", job.ID),
+			zap.Error(err))
+	} else {
+		defer cpMgr.Close()
+		cpMgr.Reset(t.GetPhysicalID(), reorgInfo.StartKey, reorgInfo.EndKey)
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:693]: need to update the comment of `Reset`

File: pkg/ddl/backfilling_operators.go [hunk 12]
```diff
@@ -301,18 +340,43 @@ func (src *TableScanTaskSource) Open() error {
...
+func (src *TableScanTaskSource) adjustStartKey(start, end kv.Key) kv.Key {
+	if src.cpMgr == nil {
+		return start
+	}
+	cpKey := src.cpMgr.LastProcessedKey()
+	if len(cpKey) == 0 {
+		return start
+	}
+	cpKeyNext := cpKey.Next()
+	if cpKeyNext.Cmp(start) > 0 || cpKey.Cmp(end) >= 0 {
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go:354]: if `start <= end` and `cpKey >= end`, then `cpKeyNext > cpKey >= end >= start` -> `cpKeyNext > start`, so seems we only need to check `cpKeyNext.Cmp(start) > 0`

File: pkg/ddl/backfilling.go [hunk 13]
```diff
@@ -619,6 +620,154 @@ func SetBackfillTaskChanSizeForTest(n int) {
...
+	err = pipe.Close()
+	if opCtx.OperatorErr() != nil {
+		return opCtx.OperatorErr()
+	}
+	if err != nil {
+		return err
+	}
+	if hasUnique {
+		for _, indexID := range indexIDs {
+			err := bcCtx.CollectRemoteDuplicateRows(indexID, t)
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:741]: to speed up we should skip non-unique index

for i, b := range uniques {...}

File: pkg/ddl/backfilling_operators.go [hunk 14]
```diff
@@ -447,14 +515,20 @@ func (w *tableScanWorker) scanRecords(task TableScanTask, sender func(IndexRecor
 
 	var idxResult IndexRecordChunk
 	err := wrapInBeginRollback(w.se, func(startTS uint64) error {
-		failpoint.Inject("mockScanRecordError", func(_ failpoint.Value) {
+		failpoint.Inject("mockScanRecordError", func() {
 			failpoint.Return(errors.New("mock scan record error"))
 		})
+		failpoint.Inject("mockScanRecordPanic", func() {
+			panic("mock panic")
+		})
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go:523]: reuse below `scanRecordExec` to inject panic?

File: pkg/ddl/backfilling_operators.go [hunk 15]
```diff
@@ -112,6 +123,30 @@ func (ctx *OperatorCtx) OperatorErr() error {
...
+
+// RowCountListener is invoked when some index records are flushed to disk or imported to TiKV.
+type RowCountListener interface {
+	Written(rowCnt int)
+	SetTotal(total int)
+}
+
+// EmptyRowCntListener implements a noop RowCountListener.
+type EmptyRowCntListener struct {
+}
```
Comment (lance6716) [inline pkg/ddl/backfilling_operators.go:140]:
```suggestion
type EmptyRowCntListener struct {}
```

Also for below two functions, just a matter of preference

File: pkg/ddl/backfilling_operators.go (hunk 12 above)
Comment (lance6716) [inline pkg/ddl/backfilling_operators.go:354]: here I think we should skip all data if cpKey == end.

and the invalid case should be `cpKey < start` or `cpKey > end`?

File: pkg/ddl/index.go [hunk 16]
```diff
@@ -979,31 +977,25 @@ func runIngestReorgJob(w *worker, d *ddlCtx, t *meta.Meta, job *model.Job,
...
 			logutil.DDLLogger().Warn("import index duplicate key, convert job to rollback", zap.Stringer("job", job), zap.Error(err))
 			ver, err = convertAddIdxJob2RollbackJob(d, t, job, tbl.Meta(), allIndexInfos, err)
+		} else if !errorIsRetryable(err, job) {
+			logutil.DDLLogger().Warn("run reorg job failed, convert job to rollback",
+				zap.String("job", job.String()), zap.Error(err))
+			ver, err = convertAddIdxJob2RollbackJob(d, t, job, tbl.Meta(), allIndexInfos, err)
 		} else {
-			logutil.DDLLogger().Warn("lightning import error", zap.Error(err))
+			logutil.DDLLogger().Warn("run add index ingest job error", zap.Error(err))
 			if !errorIsRetryable(err, job) {
```
Comment (lance6716) [inline pkg/ddl/index.go:990]: why here is another `errorIsRetryable`? We already have line 984

File: pkg/ddl/ingest/checkpoint.go [hunk 17]
```diff
@@ -253,26 +268,18 @@ func (s *CheckpointManager) afterFlush() {
...
 
-	err = s.updateCheckpoint()
+	err := s.updateCheckpoint()
 	if err != nil {
 		s.logger.Error("update checkpoint failed", zap.Error(err))
 	}
+
+	s.cancel()
+	s.updaterWg.Wait()
+	s.logger.Info("close checkpoint manager")
```
Comment (D3Hunter) [inline pkg/ddl/ingest/checkpoint.go:282]:
```suggestion
	s.logger.Info("checkpoint manager closed")
```

**Review by lance6716 — COMMENTED** [review]
rest lgtm

**Review by D3Hunter — COMMENTED** [review]
rest lgtm, please remember to revert `default DXF enable`

File: pkg/ddl/index.go (hunk 16 above)
Comment (tangenta) [reply pkg/ddl/index.go:990]: I forgot to remove one of `errorIsRetryable` when I merged the error handling logic of `FinishImport()` and `runReorgJobAndHandleErr()`..

File: pkg/ddl/backfilling_operators.go [hunk 18]
```diff
@@ -301,18 +340,43 @@ func (src *TableScanTaskSource) Open() error {
 	return nil
 }
 
+// adjustRange adjusts the range so that we can skip the ranges that have been processed
```
[the remark this answers is not in the document]
Comment (tangenta) [reply pkg/ddl/backfilling_operators.go]: https://github.com/pingcap/tidb/pull/54149/commits/559aab2774b4a9a2de6be81d160c4a0159650ec6

File: pkg/ddl/backfilling_operators.go [hunk 19]
```diff
@@ -270,6 +305,8 @@ type TableScanTaskSource struct {
 	store    kv.Storage
 	startKey kv.Key
 	endKey   kv.Key
+
+	cpMgr *ingest.CheckpointManager
```
[the remark this answers is not in the document]
Comment (tangenta) [reply pkg/ddl/backfilling_operators.go]: https://github.com/pingcap/tidb/pull/54149/commits/559aab2774b4a9a2de6be81d160c4a0159650ec6

File: pkg/ddl/index.go (hunk 16 above)
Comment (tangenta) [reply pkg/ddl/index.go]: https://github.com/pingcap/tidb/pull/54149/commits/559aab2774b4a9a2de6be81d160c4a0159650ec6

File: pkg/ddl/backfilling_operators.go (hunk 12 above)
Comment (tangenta) [reply pkg/ddl/backfilling_operators.go]: Yes.. let me add a test for this in next PR.

https://github.com/pingcap/tidb/pull/54149/commits/559aab2774b4a9a2de6be81d160c4a0159650ec6

Comment (tangenta) [reply pkg/ddl/backfilling_operators.go]: It should be `cpKey < start` or `cpKey > end`... I will add a test for this in next PR.

**Review by D3Hunter — APPROVED** [review]

File: pkg/sessionctx/variable/tidb_vars.go (hunk 1 above)
Comment (lance6716) [reply pkg/sessionctx/variable/tidb_vars.go:1382]: Need to resolve this

**Review by lance6716 — COMMENTED** [review]
rest lgtm

**Review by lance6716 — APPROVED** [review]
