### PR TITLE
ebs br: handle tag limit exceed issue

### LINKED ISSUE #50942: ebs br: EBS br failed due to tag limit exceeded
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Rotate backup, restore for multiple rounds, say more than 6 times

### 2. What did you expect to see? (Required)

Every round can succeed

### 3. What did you see instead (Required)

img_v3_027l_edc8d6f7-f894-44d6-812c-157f2b9850bg

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Issue Number: close #50942 

Problem Summary:

### What changed and how does it work?

Avoid recursively copy tagging from snapshots when creating volumes.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/aws/ebs.go [hunk 1]
```diff
@@ -149,8 +149,18 @@ func (e *EC2Session) CreateSnapshots(backupInfo *config.EBSBasedBRMeta) (map[str
 				resp, err := e.createSnapshotsWithRetry(context.TODO(), &createSnapshotInput)
 
 				if err != nil {
-					return errors.Trace(err)
+					if aErr, ok := err.(awserr.Error); !ok || aErr.Code() != "TagLimitExceeded" {
```
Comment (WangLe1321) [inline br/pkg/aws/ebs.go:152]: why not check the error in the ec2 api call? In the `createSnapshotsWithRetry` function, it will do useless retry if the error is `TagLimitExceeded`

File: br/pkg/aws/ebs.go [hunk 2]
```diff
@@ -149,8 +149,18 @@ func (e *EC2Session) CreateSnapshots(backupInfo *config.EBSBasedBRMeta) (map[str
...
+						return errors.Trace(err)
+					}
+
+					log.Warn("tag number exceeds AWS limitation during snapshots, retry without tagging")
+					createSnapshotInput.SetTagSpecifications(nil)
```
Comment (YuJuncen) [inline br/pkg/aws/ebs.go:157]: It seems we are going to create a snapshot / volume with no tags. Is such a snapshot / volume still expected?

**Review by WangLe1321 — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]
