### PR TITLE
executor, session, sessionctx/variable: add validate function for sysval sql_auto_is_null

### LINKED ISSUE #28230: Changing sql_auto_is_null is a noop (unsafe)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I was reading through the Django source code, and noticed that it had a flag for [`sql_auto_is_null`.](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_auto_is_null) I am not sure of any applications that actually use this feature, but TiDB has a "noop" handling, which is unsafe. It should instead refuse to change the sysvar.

```sql
SET sql_auto_is_null = 1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY auto_increment, b char(20));
INSERT INTO t1 VALUES (NULL, 'b');
SELECT * FROM t1 WHERE id IS NULL;
```

### 2. What did you expect to see? (Required)

```sql
mysql [localhost:5731] {msandbox} (test) > SELECT * FROM t1 WHERE id IS NULL;
+----+------+
| id | b    |
+----+------+
|  1 | b    |
+----+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```sql
mysql> SELECT * FROM t1 WHERE id IS NULL;
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.3.0-alpha-118-gbf873602e-dirty
Edition: Community
Git Commit Hash: bf873602e25ea114598b5d68325a4edf5c367d63
Git Branch: add-last-insert-id
UTC Build Time: 2021-09-15 14:54:44
GoVersion: go1.16.7
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: true
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by unconsolable**
### What problem does this PR solve?

Issue Number: close #28230 

### What is changed and how it works?

What's Changed:
- Add validate function `checkSQLAutoIsNull`
- return error ErrValueNotSupportedWhen when `set tidb_enable_noop_functions = 0` while `checkSQLAutoIsNull == 1`
- Set tidb_enable_noop_functions to 1 in test cases which changes checkSQLAutoIsNull to 1
- Add validate function test cases in `executor/set_test.go`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
set sql_auto_is_null to 1 will error as follows when tidb_enable_noop_functions is 0
ERROR 1235 (42000): function sql_auto_is_null has only noop implementation in tidb now, use tidb_enable_noop_functions to enable these functions
```

### CODE REVIEW

**Comment by unconsolable** [comment]
/cc @morgo 
PTAL

File: executor/set_test.go [hunk 1]
```diff
@@ -1408,6 +1408,34 @@ func (s *testSuite5) TestSetClusterConfigJSONData(c *C) {
 	}
 }
 
+func (s *testSuite5) TestIssue28230(c *C) {
```
Comment (morgo) [inline executor/set_test.go:1411]: I know there are other exceptions, but it's recommended to name the issue something descriptive and add a comment for the issue. i.e. `TestSQLAutoIsNull()`

File: executor/set_test.go [hunk 2]
```diff
@@ -1408,6 +1408,34 @@ func (s *testSuite5) TestSetClusterConfigJSONData(c *C) {
...
+	c.Assert(terror.ErrorEqual(err, variable.ErrFunctionsNoopImpl), IsTrue, Commentf("err %v", err))
+	tk.MustExec("set @@global.tidb_enable_noop_functions = 1;")
+	tk.MustExec("set @@global.sql_auto_is_null = 1;")
+	tk.MustQuery("select @@global.tidb_enable_noop_functions;").Check(testkit.Rows("1"))
+	err = tk.ExecToErr("set @@global.tidb_enable_noop_functions = 0;")
+	c.Assert(terror.ErrorEqual(err, variable.ErrValueNotSupportedWhen), IsTrue, Commentf("err %v", err))
+	tk.MustExec("set @@global.sql_auto_is_null = 0;")
+	tk.MustExec("set @@global.tidb_enable_noop_functions = 0;")
+}
+
```
Comment (morgo) [inline executor/set_test.go:1438]: I think you can move this test to `sessionctx/variable/sysvar_test.go` and test it through the sysvar API (unit test). That will save you from having to make `errValueNotSupportedWhen` public, and increase the unit test coverage of `sessionctx/variable`.

File: sessionctx/variable/varsutil.go [hunk 3]
```diff
@@ -160,6 +160,28 @@ func checkIsolationLevel(vars *SessionVars, normalizedValue string, originalValu
...
+		if err != nil {
+			return originalValue, errUnknownSystemVariable.GenWithStackByArgs(TiDBEnableNoopFuncs)
+		}
+		if !TiDBOptOn(val) {
+			return Off, ErrFunctionsNoopImpl.GenWithStackByArgs(feature)
+		}
+	}
+	return normalizedValue, nil
+}
+
```
Comment (morgo) [inline sessionctx/variable/varsutil.go:184]: Because this `func` is only used in one place, you might consider inlining it to `sessionctx/variable/noop.go` (up to you: it's also considerably longer than most other validation functions because it has to handle both session/global scope rules.

**Review by morgo — APPROVED** [review]

**Comment by morgo** [comment]
LGTM. I've added the compatibility-breaker tag. It's not a commonly used feature, but we can't cherry pick this, and it needs to be clear in docs.

**Review by djshow832 — APPROVED** [review]
