### PR TITLE
expression, sessionctx: support rand_seed1 and rand_seed2 sysvar

### LINKED ISSUE #29819: `rand_seed` system variable does not support replication of the RAND() function
## Bug Report
In TiDB, rand_seed variables are ignored.  The result should always respond 0.02887.

### 1. Minimal reproduce step 
Repeat this several times. 
```sql
set @@rand_seed1=10000000,@@rand_seed2=1000000;
select ROUND(RAND(),5);
```
### 2. What did you expect to see?
In MySQL
```sql
mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.00 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.02887 |
+-----------------+
1 row in set (0.00 sec)

mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.00 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.02887 |
+-----------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead 
In TiDB
```sql
mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.03 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.27441 |
+-----------------+
1 row in set (0.01 sec)

mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.00 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.34586 |
+-----------------+
1 row in set (0.01 sec)

mysql> show variables like '%rand_seed%';
+---------------+----------+
| Variable_name | Value    |
+---------------+----------+
| rand_seed1    | 10000000 |
| rand_seed2    | 1000000  |
+---------------+----------+
2 rows in set (0.00 sec)
```

### 4. What is your TiDB version?
```sql
tidb_version(): Release Version: v5.2.2
Edition: Community
Git Commit Hash: da1c21fd45a4ea5900ac16d2f4a248143f378d18
Git Branch: heads/refs/tags/v5.2.2
UTC Build Time: 2021-10-20 06:03:29
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #29819

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
support `rand_seed1` and `rand_seed2` sysvar
```

### CODE REVIEW

**Comment by Defined2014** [comment]
@morgo PTAL

Not sure is this a good way to implement `rand_seed` sysvar.

**Comment by Defined2014** [comment]
/cc @morgo
PTAL

Not sure is this a good way to implement rand_seed sysvar.

File: expression/builtin_math.go [hunk 1]
```diff
@@ -1030,7 +1030,7 @@ func (c *randFunctionClass) getFunction(ctx sessionctx.Context, args []Expressio
 			// The behavior same as MySQL.
 			seed = 0
 		}
-		sig = &builtinRandSig{bt, &sync.Mutex{}, NewWithSeed(seed)}
+		sig = &builtinRandSig{bt, utilMath.NewWithSeed(seed)}
```
Comment (morgo) [inline expression/builtin_math.go:1033]: LGTM, but I'm not sure about removing the mutex that was previously used. Can you explain in the notes why it is safe?

File: sessionctx/variable/sysvar.go [hunk 2]
```diff
@@ -1861,6 +1861,18 @@ var defaultSysVars = []*SysVar{
 	{Scope: ScopeNone, Name: "version_compile_os", Value: runtime.GOOS},
 	{Scope: ScopeNone, Name: "version_compile_machine", Value: runtime.GOARCH},
 	{Scope: ScopeNone, Name: TiDBAllowFunctionForExpressionIndex, ReadOnly: true, Value: collectAllowFuncName4ExpressionIndex()},
+	{Scope: ScopeSession, Name: "rand_seed1", Type: TypeInt, Value: "0", skipInit: true, MaxValue: math.MaxInt32, SetSession: func(s *SessionVars, val string) error {
```
Comment (morgo) [inline sessionctx/variable/sysvar.go:1864]: Our convention for supported sysvars is to use a const for the name. It looks like it is broken above for version_compile_os, but it is mostly consistent in sysvar.go otherwise.

File: expression/builtin_math.go (hunk 1 above)
Comment (Defined2014) [reply expression/builtin_math.go:1033]: Added it in https://github.com/pingcap/tidb/pull/29936/files#diff-f499163276ef45b95eb6434def8e512154988d9dad6c82a6342e8244514c3da8R39. The `mysqlRng` includes the lock.

File: sessionctx/variable/sysvar.go (hunk 2 above)
Comment (Defined2014) [reply sessionctx/variable/sysvar.go]: Done, PTAL @morgo

**Comment by morgo** [comment]
I tested locally. You've got the behavior perfectly:
```sql
tidb> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.00 sec)

tidb> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.02887 |
+-----------------+
1 row in set (0.00 sec)

tidb> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.11642 |
+-----------------+
1 row in set (0.00 sec)

tidb> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.49546 |
+-----------------+
1 row in set (0.00 sec)

tidb> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.12807 |
+-----------------+
1 row in set (0.00 sec)

tidb> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.15397 |
+-----------------+
1 row in set (0.00 sec)

tidb> select ROUND(RAND(),5), RAND();
+-----------------+--------------------+
| ROUND(RAND(),5) | RAND()             |
+-----------------+--------------------+
|         0.38565 | 0.4663202440983804 |
+-----------------+--------------------+
1 row in set (0.00 sec)
```

**Review by morgo — APPROVED** [review]

**Comment by Defined2014** [comment]
/cc @winkyao @XuHuaiyu @winoros @zz-jason @qw4990 @xhebox 
PTAL

**Review by xhebox — APPROVED** [review]
