### PR TITLE
br: fix backup to aliyum OSS not support ak/sk as env

### LINKED ISSUE #45551: br backup to aliyum OSS not support ak/sk as env
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. set env `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
2. br full backup --s3.provider "alibaba" --s3.endpoint "xxx" xxxxx

### 2. What did you expect to see? (Required)
access OSS sucess

### 3. What did you see instead (Required)
access by  RAM first
get `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` by env args was latter by s3 lib

### 4. What is your TiDB version? (Required)

v7.1.0
(OSS was import in v6.1.0 ,so this bug was in >= v6.1.0)

### PR DESCRIPTION
**Pull request by RidRisR**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/45551

Problem Summary:

### What changed and how does it work?

Fix the problem that BR only accept credentials from ISM service.
Now, if the BR can't get the ISM credentials, it will try to retrieve credentials from other sources.
And even if it got, it will still try to apply env provider and then shared provider first.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Protocol:
1. Set access-key and secret-access-key as my local machine environmental variable.
2. Try `br backup full` from a public address (my local machine) without ISM access-key.
3. Check if the full backup task finished and if the Aliyun OSS server received the backup files.

Result:
1. On my local machine:
```
./bin/br backup full     --pd "localhost:45129"     --storage "s3://test-cred/backup-data-2?endpoint=https://oss-cn-beijing.aliyuncs.com&provider=alibaba" --check-requirements=false
Detail BR log in /tmp/br.log.2024-06-27T15.12.35+0800 
Full Backup <------------------------------------------------------------------> 100.00%
Checksum <---------------------------------------------------------------------> 100.00%
[2024/06/27 15:13:10.064 +08:00] [INFO] [collector.go:77] ["Full Backup success summary"
] [total-ranges=13] [ranges-succeed=13] [ranges-failed=0] [backup-checksum=75.981913ms] [backup-fast-checksum=59.160314ms] [backup-total-ranges=119] [backup-total-regions=119] [total-take=34.226278783s] [BackupTS=450749369217187841] [total-kv=1402] [total-kv-size=409kB] [average-speed=11.95kB/s] [backup-data-size(after-compressed)=92.64kB] [Size=92636]                                                                                      
```

2. On the Aliyun OSS machine
截屏2024-06-27 15 19 08

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the problem that BR only accept credentials from ISM service.
Now, if the BR can't get the ISM credentials, it will behave as same as other endpoints and try to retrieve credentials from other sources. 
And even if it got, it will still try to apply env provider and then shared provider first.
```

### CODE REVIEW

File: br/pkg/storage/s3.go [hunk 1]
```diff
@@ -292,7 +296,11 @@ func createOssRAMCred() (*credentials.Credentials, error) {
 		return nil, errors.Annotate(err, "Alibaba RAM Provider Retrieve")
 	}
 	ncred := cred.(*alicred.StsTokenCredential)
-	return credentials.NewStaticCredentials(ncred.AccessKeyId, ncred.AccessKeySecret, ncred.AccessKeyStsToken), nil
+	return credentials.NewChainCredentials([]credentials.Provider{
```
Comment (YuJuncen) [inline br/pkg/storage/s3.go:299]: Can we add the `aliproviders.NewInstanceMetadataProvider()` to the chain directly?

**Review by YuJuncen — APPROVED** [review]

File: br/pkg/storage/s3.go [hunk 2]
```diff
@@ -289,10 +289,14 @@ func autoNewCred(qs *backuppb.S3) (cred *credentials.Credentials, err error) {
 func createOssRAMCred() (*credentials.Credentials, error) {
 	cred, err := aliproviders.NewInstanceMetadataProvider().Retrieve()
 	if err != nil {
-		return nil, errors.Annotate(err, "Alibaba RAM Provider Retrieve")
+		return nil, nil
+	}
+	aliCred := cred.(*alicred.StsTokenCredential)
```
Comment (BornChanger) [inline br/pkg/storage/s3.go:294]:
```suggestion
    var aliCred, ok = cred.(*alicred.StsTokenCredential)
	if !ok {
		return nil, errors.Errorf("invalid credential type %T", cred)
	}
```

**Review by YuJuncen — APPROVED** [review]
