### PR TITLE
executor: set the inner join keys' field length to unspecified

### LINKED ISSUE #21232: Unexpected insert error happened when the execution plan contains index join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a varchar(1), index idx(a));
create table t1(a varchar(5), index idx(a));
insert into t values('a'), ('b');
insert into t1 values('a'), ('bbbbb');
update /*+ INL_JOIN(t) */ t, t1 set t.a='a' where t.a=t1.a;
update /*+ INL_HASH_JOIN(t) */ t, t1 set t.a='a' where t.a=t1.a;
update /*+ INL_MERGE_JOIN(t) */ t, t1 set t.a='a' where t.a=t1.a;
```

### 2. What did you expect to see? (Required)

The update executed successfully and one row is affected(though actually no changes happened).

### 3. What did you see instead (Required)

Error thrown. `Data Too Long, field len 1, data len 5`

A related behavior. If you run `select /*+ HASH_JOIN(t) */ * from t, t1 where t.a=t1.a;` and `select /*+ INL_JOIN(t) */ * from t, t1 where t.a=t1.a;`. You will see that the there's no warning returned from hash join but some warnings returned from index join.

### 4. What is your TiDB version? (Required)

Current master and 4.0.8

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #21232  

Problem Summary:

See issue description for details. There's unexpected type conversion error/warnings when index join's join keys meet difference field length.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Reset its length to unspecified.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Fix unexpected error when `INSERT` meets index join in some cases.

### CODE REVIEW

File: executor/builder.go [hunk 1]
```diff
@@ -2257,7 +2257,10 @@ func (b *executorBuilder) buildIndexLookUpJoin(v *plannercore.PhysicalIndexJoin)
 	innerPlan := v.Children()[v.InnerChildIdx]
 	innerTypes := make([]*types.FieldType, innerPlan.Schema().Len())
 	for i, col := range innerPlan.Schema().Columns {
-		innerTypes[i] = col.RetType
+		innerTypes[i] = col.RetType.Clone()
+		if innerTypes[i].EvalType() == types.ETString {
```
Comment (XuHuaiyu) [inline executor/builder.go:2261]: We need a comment for this.

File: executor/builder.go [hunk 2]
```diff
@@ -2346,7 +2349,10 @@ func (b *executorBuilder) buildIndexLookUpMergeJoin(v *plannercore.PhysicalIndex
...
```
Comment (lzmhhh123) [inline executor/builder.go:2353]: Could we only modify the `flen` for join keys?

Comment (winoros) [reply executor/builder.go:2353]: Only change the `flen` for join keys will make the codes more complicated to be understand. It should be ok since the `ConvertTo` only happens when build hash map and construct lookup keys.

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
