### PR TITLE
ddl: flush data in local engine serially

### LINKED ISSUE #43523: Unexpected fallback to txn-merge mode while creating index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Set @@tidb_ddl_enable_fast_reorg = true.
2. Create index for a large table.

### 2. What did you expect to see? (Required)

No fallback.

### 3. What did you see instead (Required)

```
[2023/05/04 02:12:05.519 +00:00] [INFO] [index.go:857] ["[ddl] index backfill state running"] ["job ID"=341] [table=sbtest1] ["ingest mode"=true] [index=idx4]
[2023/05/04 02:12:06.238 +00:00] [INFO] [gc_worker.go:389] ["[gc worker] there's already a gc job running, skipped"] ["leaderTick on"=61f5cbcb8b0000a]
[2023/05/04 02:12:06.880 +00:00] [ERROR] [engine.go:84] ["[ddl-ingest] flush engine data err"] [error="context canceled"] ["job ID"=341] ["index ID"=1]
[2023/05/04 02:12:06.880 +00:00] [ERROR] [engine.go:84] ["[ddl-ingest] flush engine data err"] [error="context canceled"] ["job ID"=341] ["index ID"=1]
[2023/05/04 02:12:06.880 +00:00] [WARN] [backfilling.go:496] ["[ddl] backfill worker failed"] ["job ID"=341] ["result next key"=] [error="context canceled"]
[2023/05/04 02:12:06.880 +00:00] [WARN] [backfilling.go:496] ["[ddl] backfill worker failed"] ["job ID"=341] ["result next key"=] [error="context canceled"]
[2023/05/04 02:12:06.880 +00:00] [ERROR] [engine.go:84] ["[ddl-ingest] flush engine data err"] [error="context canceled"] ["job ID"=341] ["index ID"=1]
[2023/05/04 02:12:06.880 +00:00] [WARN] [backfilling.go:496] ["[ddl] backfill worker failed"] ["job ID"=341] ["result next key"=] [error="context canceled"]
[2023/05/04 02:12:07.084 +00:00] [INFO] [backfilling_scheduler.go:481] ["[ddl-ingest] finish a cop-request task"] [id=180]
[2023/05/04 02:12:07.084 +00:00] [INFO] [backfilling_scheduler.go:481] ["[ddl-ingest] finish a cop-request task"] [id=181]
[2023/05/04 02:12:07.086 +00:00] [WARN] [backfilling.go:450] ["[ddl] backfill worker handle tasks failed"] ["total added count"=228150830] ["start key"=7480000000000000e85f728000000053724e00] ["task failed error"="context canceled"]
[2023/05/04 02:12:07.086 +00:00] [WARN] [reorg.go:221] ["[ddl] run reorg job done"] ["handled rows"=228150830] [error="context canceled"]
[2023/05/04 02:12:07.086 +00:00] [INFO] [backend.go:305] ["engine close start"] [engineTag=sbtest1:1] [engineUUID=5ea1dc56-2537-5671-9b99-e8759b0ba99e]
[2023/05/04 02:12:07.467 +00:00] [ERROR] [backend.go:307] ["engine close failed"] [engineTag=sbtest1:1] [engineUUID=5ea1dc56-2537-5671-9b99-e8759b0ba99e] [takeTime=381.234573ms] [error="open /data/tmp/tmp_ddl-4000/341/5ea1dc56-2537-5671-9b99-e8759b0ba99e.sst/4ab00c59-5bc7-4f8e-9a3b-3321ca1e1126.sst: no such file or directory"]
```

Context is canceled and fallback to `txn-merge` mode.

### 4. What is your TiDB version? (Required)

476e104d04d0

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #43523

Problem Summary:

We should not call `FlushEngine()` concurrently.

### What is changed and how it works?

Aquire the lock before `FlushEngine()`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM

File: ddl/index.go [hunk 1]
```diff
@@ -1675,6 +1677,8 @@ func writeOneKVToLocal(writer ingest.Writer,
 	index table.Index, sCtx *stmtctx.StatementContext, writeBufs *variable.WriteStmtBufs,
 	idxDt, rsData []types.Datum, handle kv.Handle) error {
 	iter := index.GenIndexKVIter(sCtx, idxDt, handle, rsData)
+	unlock := writer.LockForWrite()
```
Comment (Benjamin2037) [inline ddl/index.go:1680]: Can we move this lock/unlock operation out to writeChunkToLocal and cover all for loop?

File: ddl/ingest/backend.go [hunk 2]
```diff
@@ -133,38 +133,47 @@ func (bc *litBackendCtx) Flush(indexID int64, force bool) (flushed, imported boo
...
-		shouldImport ||
-		time.Since(bc.timeOfLastFlush.Load()) >= bc.updateInterval
+	shouldFlush, _ := bc.ShouldSync(force)
+	if !shouldFlush {
+		return false, false, nil
+	}
+	ei.flushLock.Lock()
+	defer ei.flushLock.Unlock()
+	// Check for the second time to avoid duplicate import.
+	shouldFlush, shouldImport := bc.ShouldSync(force)
```
Comment (Benjamin2037) [inline ddl/ingest/backend.go:143]: I do not think the second-round check is necessary.

File: ddl/ingest/disk_root.go [hunk 3]
```diff
@@ -98,6 +98,10 @@ func (d *diskRootImpl) ShouldImport() bool {
 func (d *diskRootImpl) UsageInfo() string {
 	d.mu.RLock()
 	defer d.mu.RUnlock()
+	return d.usageInfo()
```
Comment (Benjamin2037) [inline ddl/ingest/disk_root.go:101]: Why this can cause deadlock?

File: ddl/ingest/backend.go (hunk 2 above)
Comment (Benjamin2037) [reply ddl/ingest/backend.go:143]: Since we only allow one writelock at one time, can we add one atomic bool to show whether the lock has been granted currently.

**Review by Benjamin2037 — APPROVED** [review]
LGTM
