### PR TITLE
plan: check schema name for column when create table

### LINKED ISSUE #3848: create table should fail if the database name is incorrect
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`create table t1(xyz.t1.name int);`

2. What did you expect to see?

```
mysql> create table t1(xyz.t1.name int);
ERROR 1102 (42000): Incorrect database name 'xyz'
```

3. What did you see instead?

```
mysql> create table t1(xyz.t1.name int);
Query OK, 0 rows affected (0.08 sec)
```

4. What version of TiDB are you using (`tidb-server -V`)?

### PR DESCRIPTION
**Pull request by spongedu**
fix #3848

### CODE REVIEW

File: plan/preprocess.go [hunk 1]
```diff
@@ -496,10 +496,14 @@ func isIncorrectName(name string) bool {
...
+	sName := stmt.Table.Schema.String()
 
 	for _, colDef := range stmt.Cols {
-		// check table name.
-		if colDef.Name.Table.O != tName && len(colDef.Name.Table.O) != 0 {
+		// check schema and table names.
+		if colDef.Name.Schema.O != sName && len(colDef.Name.Schema.O) != 0 {
+			p.err = ddl.ErrWrongDBName.GenByArgs(colDef.Name.Schema.O)
+			return
+		} else if colDef.Name.Table.O != tName && len(colDef.Name.Table.O) != 0 {
```
Comment (shenli) [inline plan/preprocess.go]: The `else` is useless.
