### PR TITLE
planner: make index-hash-join and index-merge-join consider collation

### LINKED ISSUE #20723: join return wrong results when new collation enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

new_collations_enabled_on_first_bootstrap = true
use test;
source [test2.txt](https://github.com/pingcap/tidb/files/5458048/test2.txt);
```
SELECT /*+ inl_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned`  from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;

SELECT /*+ hash_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;

SELECT /*+ merge_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;

SELECT /*+ inl_hash_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;

SELECT /*+ inl_merge_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
```
### 2. What did you expect to see? (Required)
```
mysql> SELECT /*+ inl_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned`  from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|    0 |    8 | D                       | d                  |                   15584 |
|   24 |   34 | y                       | y                  |                      95 |
|   87 |    0 | T                       | t                  |                      17 |
+------+------+-------------------------+--------------------+-------------------------+
3 rows in set (0.01 sec)

mysql>
mysql> SELECT /*+ hash_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|    0 |    8 | D                       | d                  |                   15584 |
|   24 |   34 | y                       | y                  |                      95 |
|   87 |    0 | T                       | t                  |                      17 |
+------+------+-------------------------+--------------------+-------------------------+
3 rows in set (0.01 sec)
mysql>
mysql> SELECT /*+ merge_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|    0 |    8 | D                       | d                  |                   15584 |
|   24 |   34 | y                       | y                  |                      95 |
|   87 |    0 | T                       | t                  |                      17 |
+------+------+-------------------------+--------------------+-------------------------+
3 rows in set (0.01 sec)

mysql>
mysql> SELECT /*+ inl_hash_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|    0 |    8 | D                       | d                  |                   15584 |
|   24 |   34 | y                       | y                  |                      95 |
|   87 |    0 | T                       | t                  |                      17 |
+------+------+-------------------------+--------------------+-------------------------+
3 rows in set (0.01 sec)
mysql>
mysql> SELECT /*+ inl_merge_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|    0 |    8 | D                       | d                  |                   15584 |
|   24 |   34 | y                       | y                  |                      95 |
|   87 |    0 | T                       | t                  |                      17 |
+------+------+-------------------------+--------------------+-------------------------+
3 rows in set (0.01 sec)
```
### 3. What did you see instead (Required)
```
mysql> SELECT /*+ inl_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned`  from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|   24 |   34 | y                       | y                  |                      95 |
+------+------+-------------------------+--------------------+-------------------------+
1 row in set (0.00 sec)

mysql>
mysql> SELECT /*+ hash_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
ERROR 1105 (HY000): runtime error: index out of range [255] with length 26
mysql>
mysql> SELECT /*+ merge_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|    0 |    8 | D                       | d                  |                   15584 |
|   24 |   34 | y                       | y                  |                      95 |
|   87 |    0 | T                       | t                  |                      17 |
+------+------+-------------------------+--------------------+-------------------------+
3 rows in set (0.01 sec)

mysql>
mysql> SELECT /*+ inl_hash_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
ERROR 1105 (HY000): runtime error: index out of range [255] with length 26
mysql>
mysql> SELECT /*+ inl_merge_join(t1) */ t1.pk, t2.pk, t1. `col_char_20__key_signed`, t2. `col_set_key_signed`, t1. `col_bigint_key_unsigned` from table_290_latin1_latin1_bin_undef_1 t1 right join table_300_utf8mb4_utf8mb4_general_ci_undef_1 t2 on t1. `col_char_20__key_signed` = t2. `col_set_key_signed` and t1. `col_bigint_key_unsigned` < 2150813936724763564 where t1. `col_int_key_signed` != -759 order by t1.pk, t2.pk;
+------+------+-------------------------+--------------------+-------------------------+
| pk   | pk   | col_char_20__key_signed | col_set_key_signed | col_bigint_key_unsigned |
+------+------+-------------------------+--------------------+-------------------------+
|   24 |   34 | y                       | y                  |                      95 |
+------+------+-------------------------+--------------------+-------------------------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

master 3d536a6e7e8da7f6dc591013ae69e05a9728855b and release-4.0 5fd5527e48f28a010420ae4dddbecac046f4e425

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #20723 

Problem Summary:
We didn't correct the collation for index-hash-join and index-merge-join.

### What is changed and how it works?

Set all the collations to the result collation.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Fix a bug that index-hash-join and index-merge-join doesn't consider collation

### CODE REVIEW

File: planner/core/exhaust_physical_plans.go [hunk 1]
```diff
@@ -1248,16 +1260,19 @@ loopOtherConds:
...
 	ijHelper.curPossibleUsedKeys = make([]*expression.Column, 0, len(idxCols))
 	for idxColPos, notKeyColPos := 0, 0; idxColPos < len(idxCols); idxColPos++ {
 		if ijHelper.curIdxOff2KeyOff[idxColPos] != -1 {
-			ijHelper.curPossibleUsedKeys = append(ijHelper.curPossibleUsedKeys, idxCols[idxColPos])
-			continue
+			// Check collation is the new collation is enabled.
+			tmpType := make([]expression.Expression, 0)
+			tmpType = append(tmpType, idxCols[idxColPos])
+			tmpType = append(tmpType, outerJoinKeys[ijHelper.curIdxOff2KeyOff[idxColPos]])
+			_, coll := expression.DeriveCollationFromExprs(nil, tmpType...)
```
Comment (lzmhhh123) [inline planner/core/exhaust_physical_plans.go:1271]:
```suggestion
			_, coll := expression.DeriveCollationFromExprs(nil, idxCols[idxColPos], outerJoinKeys[ijHelper.curIdxOff2KeyOff[idxColPos]])
```

**Review by lzmhhh123 — COMMENTED** [review]
Rest LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by winoros — COMMENTED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
