### PR TITLE
executor: Refact pointGetExecutor init function to ensure member fields are correctly reset

### LINKED ISSUE #57528: Runtime error occurs when do sysbench
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sh
sysbench --config-file=sysbench.conf oltp_point_select --tables=16 --table-size=1000000 --threads=128 run
```

During running, execute following SQL in TiDB:

```sql
set global tidb_enable_stmt_summary=off;
set global tidb_enable_collect_execution_info=off;
set global tidb_max_chunk_size=128;
```

panic log:

```log
[2024/11/20 03:23:22.528 +00:00] [INFO] [conn.go:1184] ["command dispatched failed"] [conn=2868903952] [session_alias=] [connInfo="id:2868903952, addr:10.202.0.103:37728 status:10, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:0, autocommit:1"] [sql="SELECT c FROM sbtest11 WHERE id=? [arguments: 500555]"] [txn_mode=PESSIMISTIC] [timestamp=0] [err="runtime error: invalid memory address or nil pointer dereference
github.com/pingcap/errors.AddStack
	/home/transaction/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178
github.com/pingcap/errors.Trace
	/home/transaction/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/juju_adaptor.go:15
github.com/pingcap/tidb/pkg/util.GetRecoverError
	/home/transaction/tidb/pkg/util/util.go:288
github.com/pingcap/tidb/pkg/executor/internal/exec.Close.func1
	/home/transaction/tidb/pkg/executor/internal/exec/executor.go:473
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:785
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:917
github.com/pingcap/tidb/pkg/util/execdetails.(*RuntimeStatsColl).RegisterStats
	/home/transaction/tidb/pkg/util/execdetails/execdetails.go:1476
github.com/pingcap/tidb/pkg/executor.(*PointGetExecutor).Close.func1
	/home/transaction/tidb/pkg/executor/point_get.go:257
github.com/pingcap/tidb/pkg/executor.(*PointGetExecutor).Close
	/home/transaction/tidb/pkg/executor/point_get.go:278
github.com/pingcap/tidb/pkg/executor/internal/exec.Close
	/home/transaction/tidb/pkg/executor/internal/exec/executor.go:480
github.com/pingcap/tidb/pkg/executor.(*recordSet).Finish.func1
	/home/transaction/tidb/pkg/executor/adapter.go:202
sync.(*Once).doSlow
	/usr/local/go/src/sync/once.go:76
sync.(*Once).Do
	/usr/local/go/src/sync/once.go:67
github.com/pingcap/tidb/pkg/executor.(*recordSet).Finish
	/home/transaction/tidb/pkg/executor/adapter.go:201
github.com/pingcap/tidb/pkg/server/internal/resultset.(*tidbResultSet).Finish
	/home/transaction/tidb/pkg/server/internal/resultset/resultset.go:79
github.com/pingcap/tidb/pkg/server.(*clientConn).writeChunks
	/home/transaction/tidb/pkg/server/conn.go:2375
github.com/pingcap/tidb/pkg/server.(*clientConn).writeResultSet
	/home/transaction/tidb/pkg/server/conn.go:2262
github.com/pingcap/tidb/pkg/server.(*clientConn).executePreparedStmtAndWriteResult
	/home/transaction/tidb/pkg/server/conn_stmt.go:342
github.com/pingcap/tidb/pkg/server.(*clientConn).executePlanCacheStmt
	/home/transaction/tidb/pkg/server/conn_stmt.go:234
github.com/pingcap/tidb/pkg/server.(*clientConn).handleStmtExecute
	/home/transaction/tidb/pkg/server/conn_stmt.go:225
github.com/pingcap/tidb/pkg/server.(*clientConn).dispatch
	/home/transaction/tidb/pkg/server/conn.go:1405
github.com/pingcap/tidb/pkg/server.(*clientConn).Run
	/home/transaction/tidb/pkg/server/conn.go:1147
github.com/pingcap/tidb/pkg/server.(*Server).onConn
	/home/transaction/tidb/pkg/server/server.go:741
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
SELECT c FROM sbtest11 WHERE id=? [arguments: 500555]"]
```

### 4. What is your TiDB version? (Required)

```sql
> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v8.5.0-alpha-164-g9530fdc238
Edition: Community
Git Commit Hash: 9530fdc2388d025af86eb6fce5e617972c361000
Git Branch: master
UTC Build Time: 2024-11-20 03:18:44
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #57528 

Problem Summary:
In #57528, point get sysbench started to run with execution info set on, and point get executors with execution info will be stored in plan cache. Then we turned off the execution info system variable. However, we can get the cached executors with execution info in a session which execution info is set off. This is caused due to incomplete re-initialization of point get executor: the stats field should be reset to nil when a cached point get executor is reused in an "execution-info-off" session. 
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Do manually test as #57528 described, ensure no errors happen
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that a PointGet executor's member fields may not be reset correctly when it is reused from plan cache.
```

### CODE REVIEW

File: pkg/executor/point_get.go [hunk 1]
```diff
@@ -203,15 +180,19 @@ func matchPartitionNames(pid int64, partitionNames []ast.CIStr, pi *model.Partit
...
+func (e *PointGetExecutor) Recreated(p *plannercore.PointGetPlan, ctx sessionctx.Context) {
 	// It's necessary to at least reset the `runtimeStats` of the `BaseExecutor`.
 	// As the `StmtCtx` may have changed, a new index usage reporter should also be created.
-	e.BaseExecutor = exec.NewBaseExecutor(e.Ctx(), p.Schema(), p.ID())
-	e.indexUsageReporter = buildIndexUsageReporter(e.Ctx(), p, false)
+	e.BaseExecutor = exec.NewBaseExecutor(ctx, p.Schema(), p.ID())
+	e.indexUsageReporter = buildIndexUsageReporter(ctx, p, false)
+
+	e.Init(p)
+	InitSnapshotWithSessCtx(e.snapshot, ctx, nil)
```
Comment (cfzjywxk) [inline pkg/executor/point_get.go:190]: The oreder here is different from `buildPointGet` in which the `getSnapshot` is called before `Init`, need to ensure there is no implicit order requirement bettween `Init` and getSnapshot`.

**Review by cfzjywxk — COMMENTED** [review]
Better to have a test case to cover the problem in the issue.

**Comment by yibin87** [comment]
> Better to have a test case to cover the problem in the issue.

Will add one.

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
