### PR TITLE
expression: fix convert number base for hybrid type

### LINKED ISSUE #5817: conv bit error
## Description
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```sql
CREATE TABLE `bit` (
  `b` bit(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `bit` (`b`)
VALUES
	(0b0000010101),
	(0b0000010101),
	(NULL),
	(0b0000000001),
	(0b0000000000),
	(0b1111111111),
	(0b1111111111),
	(0b1111111111),
	(0b0000000000),
	(0b0000000000),
	(0b0000000000),
	(0b0000000000),
	(0b0000100000);
```

```sql
select conv(b, 2, 2) from `bit`;
```

2. What did you expect to see?

```
+---------------+
| conv(b, 2, 2) |
+---------------+
| 10101         |
| 10101         |
| NULL          |
| 1             |
| 0             |
| 1111111111    |
| 1111111111    |
| 1111111111    |
| 0             |
| 0             |
| 0             |
| 0             |
| 100000        |
+---------------+
13 rows in set (0.00 sec)
```

3. What did you see instead?

```
+---------------+
| conv(b, 2, 2) |
+---------------+
| 0             |
| 0             |
| NULL          |
| 0             |
| 0             |
| 0             |
| 0             |
| 0             |
| 0             |
| 0             |
| 0             |
| 0             |
| 0             |
+---------------+
13 rows in set (0.01 sec)
``` 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v1.1.0-alpha-544-gbe1eeac-dirty
Git Commit Hash: be1eeaccb90e75f2ce6defd8947a5218e0372378
Git Branch: master
UTC Build Time: 2018-02-07 03:54:18 |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @wshwsh12

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close #5817

### What is changed and how it works?

How it Works: specified handle hybrid type for conv function.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- fix convert number base for hybrid type

### CODE REVIEW

File: expression/builtin_math.go [hunk 1]
```diff
@@ -1163,11 +1164,25 @@ func (b *builtinConvSig) Clone() builtinFunc {
...
+			arg0 := x.GetArgs()[0]
+			if arg0.GetType().Hybrid() || IsBinaryLiteral(arg0) {
+				str, isNull, err = arg0.EvalString(b.ctx, row)
+				if isNull || err != nil {
+					return str, isNull, err
+				}
+				d := types.NewStringDatum(str)
+				str = d.GetBinaryLiteral().ToBitLiteralString(true)
+			}
+		}
```
Comment (ichn-hu) [inline expression/builtin_math.go:1184]: what if the func is not Cast but produces string that needs to be converted?

File: expression/builtin_math_vec.go [hunk 2]
```diff
@@ -1070,7 +1070,8 @@ func (b *builtinSignSig) vecEvalInt(input *chunk.Chunk, result *chunk.Column) er
 }
 
 func (b *builtinConvSig) vectorized() bool {
-	return true
+	// TODO: change the vecEval match hybrid type fixing. Then open the vectorized evaluation.
+	return false
```
Comment (ichn-hu) [inline expression/builtin_math_vec.go:1074]: would you like to create an issue for this?

**Review by ichn-hu — COMMENTED** [review]
Rest LGTM

File: expression/builtin_math.go (hunk 1 above)
Comment (lzmhhh123) [reply expression/builtin_math.go:1184]: When we build `conv` function. If the first argument is NOT string type. The `cast` would be wrapped. No other cases. You can refer to this code.

```go
func (c *convFunctionClass) getFunction(ctx sessionctx.Context, args []Expression) (builtinFunc, error) {
	if err := c.verifyArgs(args); err != nil {
		return nil, err
	}

	bf, err := newBaseBuiltinFuncWithTp(ctx, c.funcName, args, types.ETString, types.ETString, types.ETInt, types.ETInt)
	if err != nil {
		return nil, err
	}
	bf.tp.Charset, bf.tp.Collate = ctx.GetSessionVars().GetCharsetInfo()
	bf.tp.Flen = 64
	sig := &builtinConvSig{bf}
	sig.setPbCode(tipb.ScalarFuncSig_Conv)
	return sig, nil
}
```

File: expression/builtin_math_vec.go (hunk 2 above)
Comment (lzmhhh123) [reply expression/builtin_math_vec.go:1074]: I will update https://github.com/pingcap/tidb/issues/12106, since the PR merged.

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
