### PR TITLE
ddl: fix cancel the rollbacking back may lead to meta data broken

### LINKED ISSUE #44143: Index may not rollback correctly if cancel during rollback
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create a unique index that would rollback because of the duplicated key.
2. Cancel this add index job during the rollback.

### 2. What did you expect to see? (Required)
No incompleted index in the table meta.

### 3. What did you see instead (Required)
An incompleted index in the table meta.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #44143

Problem Summary:
It doesn't Unmarshal the rawArg to Arg if the job is rollbacking.

### What is changed and how it works?
Don't update the RawArg since it doesn't change during cancel/pause/resume.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix cancel the rollbacking back may lead to meta data broken
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: ddl/ddl.go [hunk 1]
```diff
@@ -1480,7 +1477,7 @@ func pauseRunningJob(sess *sess.Session, job *model.Job,
 		return nil
```
Comment (zimulala) [inline ddl/ddl.go:1477]: Could we remove these logic(line-1479-1481)?

**Review by zimulala — APPROVED** [review]
LGTM
