### PR TITLE
br: register import task to pd

### LINKED ISSUE #41536: log backup task is conflict with restore/lightning
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run restore or lightning
2. run log backup task
### 2. What did you expect to see? (Required)
log backup task should be failed
### 3. What did you see instead (Required)
log bakcup task success to run
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #41536 

Problem Summary:
log backup task is conflict with restore/lightning
### What is changed and how it works?
register task key with ttl to pd, and keepalive it during running.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/utils/register.go [hunk 1]
```diff
@@ -0,0 +1,280 @@
...
+	const minTimeLeftThreshold time.Duration = 20 * time.Second
+	var timeLeftThreshold time.Duration = tr.ttl / 4
+	if timeLeftThreshold < minTimeLeftThreshold {
+		timeLeftThreshold = minTimeLeftThreshold
+	}
+	failpoint.Inject("brie-task-register-always-grant", func(_ failpoint.Value) {
+		timeLeftThreshold = tr.ttl
+	})
+	var lastUpdateTime time.Time = time.Now()
+	var err error
```
Comment (YuJuncen) [inline br/pkg/utils/register.go:147]: Can we merge these variable definitions into one block like:
```go
var (
  foo = somewhat
  bar = somewhat
) 
```

File: br/pkg/utils/register.go [hunk 2]
```diff
@@ -0,0 +1,280 @@
...
+}
+
+type RegisterTasksList struct {
+	Tasks []RegisterTask
+}
+
+func (list RegisterTasksList) MessageToUser() string {
+	var tasksMsgBuf strings.Builder
+	for _, task := range list.Tasks {
+		tasksMsgBuf.WriteString(task.MessageToUser())
```
Comment (YuJuncen) [inline br/pkg/utils/register.go:245]: Should we add some whitespaces between tasks?

**Review by YuJuncen — APPROVED** [review]
rest lgtm

**Review by joccau — APPROVED** [review]
LGTM~ 
Nice code! good job!

File: br/pkg/utils/register.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/utils/register.go]: done

File: br/pkg/utils/register.go (hunk 2 above)
Comment (Leavrth) [reply br/pkg/utils/register.go:247]: done
