### PR TITLE
parser,planner: fix the compatiblity of explain_format

### LINKED ISSUE #25913: FORMAT in EXPLAIN is compatible with MySQL
## Bug Report

In Mysql, when you use ``` EXPLAIN FORMAT=<formatStmt>```, This ```formatStmt``` support string and identifier.
but In TiDB, it is in confusion.

### 1. Minimal reproduce step (Required)

explain FORMAT='TRADITIONAL'   select * from mysql.db;

### 2. What did you expect to see? (Required)

in mysql 8.0.25

```
+----+-------------+-------+------------+------+---------------+--------+---------+--------+------+----------+--------+
| id | select_type | table | partitions | type | possible_keys | key    | key_len | ref    | rows | filtered | Extra  |
+----+-------------+-------+------------+------+---------------+--------+---------+--------+------+----------+--------+
| 1  | SIMPLE      | db    | <null>     | ALL  | <null>        | <null> | <null>  | <null> | 2    | 100.0    | <null> |
+----+-------------+-------+------------+------+---------------+--------+---------+--------+------+----------+--------+
```
### 3. What did you see instead (Required)

```
(1791, "Unknown EXPLAIN format name: 'TRADITIONAL'")
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #25913  

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

fix the compatiblity of explain_format in the tidb/parser, and remove some code into TiDB.

How it Works:

change parser for make explain-format support string and identifer

### Related changes

- Need to cherry-pick to the release branch

### Check List 

- Unit test
- Integration test

### Release note 

- fix the compatiblity of explain_format

### CODE REVIEW

File: types/explain_format.go [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+	ExplainFormatJSON = "json"
+	// ExplainFormatROW presents the output in tabular format.
+	ExplainFormatROW = "row"
+	// ExplainFormatVerbose display additional information regarding the plan.
+	ExplainFormatVerbose = "verbose"
+	// ExplainFormatTraditional is the same as ExplainFormatROW.
+	ExplainFormatTraditional = "traditional"
+
+	// ExplainFormats stores the valid formats for explain statement, used by validator.
+	ExplainFormats = []string{
```
Comment (zimulala) [inline types/explain_format.go:33]: Why move this structure to this repo? It's not processed directly in the parser

Comment (tiancaiamao) [reply types/explain_format.go:33]: The definitions are removed from the parser.
The field type is a string, rather than a enum type, so it's not useful in the parser repo.

Comment (zimulala) [reply types/explain_format.go:33]: Got it. Please write the link about `remove definitions`.

File: planner/core/planbuilder.go [hunk 2]
```diff
@@ -3782,7 +3782,10 @@ func (b *PlanBuilder) buildExplainFor(explainFor *ast.ExplainForStmt) (Plan, err
 		return &Explain{Format: explainFor.Format}, nil
 	}
 	var explainRows [][]string
-	if explainFor.Format == ast.ExplainFormatROW {
+	if explainFor.Format == types.ExplainFormatTraditional {
+		explainFor.Format = types.ExplainFormatROW
+	}
+	if explainFor.Format == types.ExplainFormatROW {
```
Comment (zimulala) [inline planner/core/planbuilder.go:3788]: Could we rewrite the code as follows:
```
if explainFor.Format == types.ExplainFormatTraditional || explainFor.Format == types.ExplainFormatROW{
```

**Review by zimulala — APPROVED** [review]
LGTM

File: go.mod [hunk 3]
```diff
@@ -43,7 +43,7 @@ require (
 	github.com/pingcap/failpoint v0.0.0-20210316064728-7acb0f0a3dfd
 	github.com/pingcap/fn v0.0.0-20200306044125-d5540d389059
 	github.com/pingcap/kvproto v0.0.0-20210611081648-a215b4e61d2f
-	github.com/pingcap/log v0.0.0-20210317133921-96f4fcab92a4
+	github.com/pingcap/log v0.0.0-20210625125904-98ed8e2eb1c7
 	github.com/pingcap/parser v0.0.0-20210618124025-07ae8d9291c4
```
Comment (tiancaiamao) [inline go.mod:47]: Parser is not changed?

Comment (hawkingrei) [reply go.mod]: fixed

File: go.sum [hunk 4]
```diff
@@ -440,8 +442,9 @@ github.com/pingcap/kvproto v0.0.0-20210611081648-a215b4e61d2f/go.mod h1:IOdRDPLy
 github.com/pingcap/log v0.0.0-20191012051959-b742a5d432e9/go.mod h1:4rbK1p9ILyIfb6hU7OG2CiWSqMXnp3JMbiaVJ6mvoY8=
 github.com/pingcap/log v0.0.0-20200511115504-543df19646ad/go.mod h1:4rbK1p9ILyIfb6hU7OG2CiWSqMXnp3JMbiaVJ6mvoY8=
 github.com/pingcap/log v0.0.0-20201112100606-8f1e84a3abc8/go.mod h1:4rbK1p9ILyIfb6hU7OG2CiWSqMXnp3JMbiaVJ6mvoY8=
-github.com/pingcap/log v0.0.0-20210317133921-96f4fcab92a4 h1:ERrF0fTuIOnwfGbt71Ji3DKbOEaP189tjym50u8gpC8=
 github.com/pingcap/log v0.0.0-20210317133921-96f4fcab92a4/go.mod h1:4rbK1p9ILyIfb6hU7OG2CiWSqMXnp3JMbiaVJ6mvoY8=
+github.com/pingcap/log v0.0.0-20210625125904-98ed8e2eb1c7 h1:k2BbABz9+TNpYRwsCCFS8pEEnFVOdbgEjL/kTlLuzZQ=
+github.com/pingcap/log v0.0.0-20210625125904-98ed8e2eb1c7/go.mod h1:8AanEdAHATuRurdGxZXBz0At+9avep+ub7U1AGYLIMM=
```
[the remark this answers is not in the document]
Comment (AilinKid) [reply go.sum:448]: did you exec `make tidy` before?

**Review by AilinKid — APPROVED** [review]

**Comment by AilinKid** [comment]
did you exec `make tidy` which clean the go mod and sum

**Comment by hawkingrei** [comment]
> did you exec `make tidy` which clean the go mod and sum

Done
