### PR TITLE
external: fix decoding the last key in split keys

### LINKED ISSUE #59725: Fail to add unique key using global sort in large data
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Add unique key using global sort in large data 

### 2. What did you expect to see? (Required)

Succeed

### 3. What did you see instead (Required)

```text
[2025/02/18 10:05:47.292 +00:00] [ERROR] [task_executor.go:344] ["run subtask failed"] [task-id=30001] [task-type=backfill] [error="insufficient bytes to decode value"] [errorVerbose="insufficient bytes to decode value
github.com/pingcap/tidb/pkg/lightning/common.DupDetectKeyAdapter.Decode
    /workspace/source/tidb/pkg/lightning/common/key_adapter.go:91
github.com/pingcap/tidb/pkg/lightning/backend/external.(*Engine).GetRegionSplitKeys
    /workspace/source/tidb/pkg/lightning/backend/external/engine.go:470
github.com/pingcap/tidb/pkg/lightning/backend/local.getRegionSplitKeys
    /workspace/source/tidb/pkg/lightning/backend/local/local.go:885
github.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).ImportEngine
    /workspace/source/tidb/pkg/lightning/backend/local/local.go:1327
github.com/pingcap/tidb/pkg/ddl.(*cloudImportExecutor).RunSubtask
    /workspace/source/tidb/pkg/ddl/backfilling_import_cloud.go:145
github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask.func1
    /workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:460
github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask
    /workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:461
github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).Run
    /workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:339
github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).startTaskExecutor.func2
    /workspace/source/tidb/pkg/disttask/framework/taskexecutor/manager.go:377
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1
    /workspace/source/tidb/pkg/util/wait_group_wrapper.go:181
runtime.goexit
    /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64/src/runtime/asm_amd64.s:1700"]
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #59725

Problem Summary:

When the kv size or kv count of unique key is large, we will call `GetRegionSplitKeys`, which did not properly consider the case of `key.Next()`. Then it fails due to the decoding.

### What changed and how does it work?

Introduce the method `tryDecodeEndKey` to decode the last key

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug that fails to add unique key using global sort in large data
```

### CODE REVIEW

File: pkg/lightning/backend/external/engine.go [hunk 1]
```diff
@@ -98,7 +99,6 @@ type Engine struct {
 	endKey            []byte
 	jobKeys           [][]byte
 	splitKeys         [][]byte
-	regionSplitSize   int64
```
Comment (CbcWestwolf) [inline pkg/lightning/backend/external/engine.go:101]: just remove useless field

File: pkg/lightning/backend/external/engine.go [hunk 2]
```diff
@@ -110,8 +110,7 @@ type Engine struct {
 	// this flag also affects the strategy of loading data, either:
 	// 	less load routine + check and read hotspot file concurrently (add-index uses this one)
 	// 	more load routine + read each file using 1 reader (import-into uses this one)
-	checkHotspot          bool
-	mergerIterConcurrency int
```
Comment (CbcWestwolf) [inline pkg/lightning/backend/external/engine.go:114]: DITTO

**Review by lance6716 — APPROVED** [review]
