### PR TITLE
planner: implements support for dumping multiple SQL statements in a single `PLAN REPLAYER DUMP EXPLAIN` command

### LINKED ISSUE #66151: planner: Plan Replayer supports dumping multiple SQL records at once
## Enhancement
The current Plan Replayer implementation only supports dumping one SQL record at a time, and we could extend it to support multiple SQL records, for example:
```
PLAN REPLAYER DUMP EXPLAIN (STMT_LIST);

PLAN REPLAYER DUMP EXPLAIN (
    "SELECT * FROM t1 WHERE id = 1",
    "SELECT * FROM t1 WHERE id > 1",
    "SELECT * FROM t2 WHERE status = 'active'",
    "SELECT * FROM t1, t2 WHERE t1.id = t2.id"
);
```
By combining them in a single Plan Replayer command, we can reduce the amount of duplicated data. For example, we only need to collect the stats data of `t1` once instead of 3 times if we run single-SQL Plan Replayer command for them one by one.

A common usage of this could be: before upgrading, we use this command to dump all highly-frequent SQLs in this workload, and verify whether they'll have any plan regression in the new TiDB version.

How to organize the output file? If there are multiple statements:
1. put these SQLs under `/sql`, each SQL has a separate file, for example, `/sql/sql0.sql`, `/sql/sql1.sql`;
2. create a new dictionary `explain` and put their plans under it, each has a separate file, for example, `/explain/explain0.txt`, `/explain/explain1.txt`.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #66151

Problem Summary: Implements support for dumping multiple SQL statements in a single `PLAN REPLAYER DUMP EXPLAIN` command, addressing issue #66151.

### Parser
- Added `StmtList []string` field to `PlanReplayerStmt` AST
- Added grammar rules for `PLAN REPLAYER DUMP EXPLAIN ( 'sql1', 'sql2', ... )`
- Updated `Restore` method to handle multi-SQL format

### Planner/Executor
- Added `StmtList` field to `PlanReplayer` plan
- Executor builder parses SQL strings from `StmtList` into AST nodes

### Dump Output
- **Single SQL** (backward compatible): `sql/sql0.sql` + `explain.txt`
- **Multiple SQLs**: `sql/sql0.sql`, `sql/sql1.sql`, ... + `explain/explain0.txt`, `explain/explain1.txt`, ...
- Fixed table extraction to properly handle unqualified table names

## Example

```
PLAN REPLAYER DUMP EXPLAIN (
    'SELECT * FROM t1 WHERE id = 1',
    'SELECT * FROM t1 WHERE id > 1',
    'SELECT * FROM t2 WHERE status = "active"'
);
```

Output zip contains:
1. `/sql/sql0.sql`, `/sql/sql1.sql`, `/sql/sql2.sql`
2. `/explain/explain0.txt`, `/explain/explain1.txt`, `/explain/explain2.txt`
3. Schema/stats files for referenced tables (collected once)

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/test/planreplayer/plan_replayer_test.go [hunk 1]
```diff
@@ -226,3 +226,85 @@ func TestPlanReplayerDumpSingle(t *testing.T) {
...
+		require.Contains(t, names, fmt.Sprintf("explain/explain%d.txt", i))
+	}
+	require.NotContains(t, names, "explain.txt") // single explain.txt is not used for multi-SQL
+
+	// Check 5 stats files and 5 schema files for the 5 tables
+	const numTables = 5
+	for i := 1; i <= numTables; i++ {
+		tableName := fmt.Sprintf("t_dump_multi_%d", i)
+		require.Contains(t, names, fmt.Sprintf("stats/test.%s.json", tableName))
+		require.Contains(t, names, fmt.Sprintf("schema/test.%s.schema.txt", tableName))
```
Comment (hawkingrei) [inline pkg/executor/test/planreplayer/plan_replayer_test.go]: The tests are a bit thin; can we have AI generate some examples with multiple databases?

File: pkg/parser/ast/misc.go [hunk 2]
```diff
@@ -347,6 +351,17 @@ func (n *PlanReplayerStmt) Restore(ctx *format.RestoreCtx) error {
...
+		for i, s := range n.StmtList {
+			if i > 0 {
+				ctx.WritePlain(", ")
+			}
+			ctx.WriteString(s)
+		}
+		ctx.WritePlain(")")
+		return nil
+	}
 	if n.Stmt == nil {
```
Comment (guo-shaoge) [inline pkg/parser/ast/misc.go:365]: question: When will `n.Stmt` is nil

File: pkg/parser/ast/misc_test.go [hunk 3]
```diff
@@ -343,6 +343,10 @@ func TestPlanReplayerStmtRestore(t *testing.T) {
 			"PLAN REPLAYER DUMP EXPLAIN ANALYZE 'test'"},
 		{"plan replayer dump with stats as of timestamp '12345' explain analyze 'test2'",
 			"PLAN REPLAYER DUMP WITH STATS AS OF TIMESTAMP _UTF8MB4'12345' EXPLAIN ANALYZE 'test2'"},
+		{"plan replayer dump explain ('SELECT * FROM t1', 'SELECT * FROM t2')",
+			"PLAN REPLAYER DUMP EXPLAIN ('SELECT * FROM t1', 'SELECT * FROM t2')"},
+		{"plan replayer dump explain analyze ('SELECT * FROM t1')",
+			"PLAN REPLAYER DUMP EXPLAIN ANALYZE ('SELECT * FROM t1')"},
```
Comment (guo-shaoge) [inline pkg/parser/ast/misc_test.go:349]: Add edge case that with empty and non empty in the stmt list?

File: pkg/parser/ast/misc.go (hunk 2 above)
Comment (qw4990) [reply pkg/parser/ast/misc.go:365]: It seems like we can specify a SQL file, for example: `plan replayer dump explain {sql.txt}`:
image

File: pkg/parser/ast/misc_test.go (hunk 3 above)
Comment (qw4990) [reply pkg/parser/ast/misc_test.go:349]: I'll error if it's empty. I added an test in `TestPlanReplayerDumpMultiple`:
image

File: pkg/executor/test/planreplayer/plan_replayer_test.go (hunk 1 above)
Comment (qw4990) [reply pkg/executor/test/planreplayer/plan_replayer_test.go]: Added more databases.

**Comment by qw4990** [comment]
The doc PR: https://github.com/pingcap/docs/pull/22429

**Review by D3Hunter — COMMENTED** [review]
/approve

File: pkg/executor/builder.go [hunk 4]
```diff
@@ -1181,7 +1181,21 @@ func (b *executorBuilder) buildPlanReplayer(v *plannercore.PlanReplayer) exec.Ex
 			HistoricalStatsTS: v.HistoricalStatsTS,
 		},
 	}
-	if v.ExecStmt != nil {
+	if len(v.StmtList) > 0 {
+		// Parse multiple SQL strings from StmtList
+		e.DumpInfo.ExecStmts = make([]ast.StmtNode, 0, len(v.StmtList))
+		for _, sqlStr := range v.StmtList {
+			node, err := b.ctx.GetRestrictedSQLExecutor().ParseWithParams(context.Background(), sqlStr)
+			if err != nil {
```
[the remark this answers is not in the document]
Comment (qw4990) [reply pkg/executor/builder.go:1189]: Updated, now it'll return the error directly instead of warning.
