### PR TITLE
ddl, executor: add error for functional index cannot refer to an auto-increment column

### LINKED ISSUE #20317: Refine the error message for the expression index on auto-increment column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> CREATE TABLE t1 (t1_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE INDEX idx1 ON t1 ((t1_id + t1_id));
ERROR 3109 (HY000): Generated column '' cannot refer to auto-increment column.
```

### 2. What did you expect to see? (Required)

Expression index 'idx1' cannot refer to an auto-increment column.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by Howie59**
Signed-off-by: lihaowei <haoweili35@gmail.com>

### What problem does this PR solve?

Issue Number: close #20317

### Release note
- No release note

### CODE REVIEW

**Comment by Howie59** [comment]
> No release note, Please follow https://github.com/pingcap/community/blob/master/contributors/release-note-checker.md

No release note

File: errno/errname.go [hunk 1]
```diff
@@ -826,6 +826,7 @@ var MySQLErrName = map[uint16]string{
 	ErrGeneratedColumnNonPrior:                               "Generated column can refer only to generated columns defined prior to it.",
 	ErrDependentByGeneratedColumn:                            "Column '%s' has a generated column dependency.",
 	ErrGeneratedColumnRefAutoInc:                             "Generated column '%s' cannot refer to auto-increment column.",
+	ErrExpressionIndexCanNotRefer:                            "Expression index '%s' cannot refer to an auto-increment column.",
```
Comment (zz-jason) [inline errno/errname.go:829]: In MySQL 8.0.21, the error message is `Functional index 'idx1' cannot refer to an auto-increment column.`, and the error code is `3754` instead of `3110`:

```sql
MySQL(root@127.0.0.1:test) > CREATE TABLE t1 (t1_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
Query OK, 0 rows affected (0.01 sec)

MySQL(root@127.0.0.1:test) > CREATE INDEX idx1 ON t1 ((t1_id + t1_id));
ERROR 3754 (HY000): Functional index 'idx1' cannot refer to an auto-increment column.
MySQL(root@127.0.0.1:test) > select version();
+-----------+
| version() |
+-----------+
| 8.0.21    |
+-----------+
1 row in set (0.00 sec)
```

**Review by zz-jason — COMMENTED** [review]
LGTM

**Comment by Howie59** [comment]
@wshwsh12 PTAL

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
