### PR TITLE
parser: add custom_gbk encoding to deal with 0x80

### LINKED ISSUE #30581: Insert 3 bytes of data into gbk column, result is inconsistent with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set names gbk;
create table t3(a char(10) charset gbk);
insert into t3 values('一a');
```

```
xxx> select @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
```
mysql> insert into t3 values('一a');
ERROR 1366 (HY000): Incorrect string value: '\x80a' for column 'a' at row 1
```

### 3. What did you see instead (Required)
```
tidb> insert into t3 values('一a');
Query OK, 1 row affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #30581

Problem Summary: 0x80 is invalid in character in GBK.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @tangenta @xiongjiwei 
PTAL

File: parser/charset/encoding_gbk.go [hunk 1]
```diff
@@ -105,3 +106,41 @@ var GBKCase = unicode.SpecialCase{
...
+	gbkDecoder *encoding.Decoder
+}
+
+// Transform special treatment for 0x80,
+// see https://github.com/pingcap/tidb/issues/30581 get details.
+func (c customGBKDecoder) Transform(dst, src []byte, atEOF bool) (nDst, nSrc int, err error) {
+	if len(src) == 0 {
+		return 0, 0, nil
+	}
+	if src[0] == 0x80 {
```
Comment (xiongjiwei) [inline parser/charset/encoding_gbk.go:137]: in golang lib, it write `utf8.RuneError` with no error

**Review by xiongjiwei — COMMENTED** [review]
we should also consider `encoder`
```sql
mysql> select convert('€' using gbk);
+--------------------------+
| convert('€' using gbk)   |
+--------------------------+
| ?                        |
+--------------------------+
1 row in set (0.01 sec)
```

File: parser/charset/encoding_gbk.go [hunk 2]
```diff
@@ -105,3 +107,65 @@ var GBKCase = unicode.SpecialCase{
...
+}
+
+// Transform special treatment for `€`,
+// see https://github.com/pingcap/tidb/issues/30581 get details.
+func (c customGBKEncoder) Transform(dst, src []byte, atEOF bool) (nDst, nSrc int, err error) {
+	if len(src) == utf8.RuneLen('€') {
+		if r,_ := utf8.DecodeRune(src[:]); r == '€' {
+			return 0, 0, errInvalidCharacterString
+		}
+	}
```
Comment (tangenta) [inline parser/charset/encoding_gbk.go:164]:
```suggestion
	if bytes.HasPrefix(src, []byte{0xe2, 0x82, 0xac} /* '€' */) {
		return 0, 0, errInvalidCharacterString
	}
```

How about using bytes directly since the utf-8 encoding of '€' should be constant.

Comment (tangenta) [reply parser/charset/encoding_gbk.go:164]: Here is the result:
```go
func main() {
	var buf [4]byte
	i := utf8.EncodeRune(buf[:], '€')
	euroSign := buf[:i]
	fmt.Printf("%x\n", euroSign)
}
```
```console
e282ac
```

**Review by tangenta — APPROVED** [review]

File: parser/charset/encoding_test.go [hunk 3]
```diff
@@ -55,6 +55,9 @@ func TestEncoding(t *testing.T) {
 		{"移維緯胃萎衣謂違", "绉荤董绶?儍钀庤。璎傞仌", false},
 		{"仆仂仗仞仭仟价伉佚估", "浠嗕粋浠椾粸浠?粺浠蜂級浣氫及", false},
 		{"佝佗佇佶侈侏侘佻佩佰侑佯", "浣濅綏浣囦蕉渚堜緩渚樹交浣╀桨渚戜蒋", true},
+		{"\x80", "?", false},
+		{"\x80a", "?", false},
+		{"\x80aa", "?a", false},
```
Comment (xiongjiwei) [inline parser/charset/encoding_test.go:60]: how about add `\x80`  into the middle of the string?

**Review by xiongjiwei — APPROVED** [review]
