### PR TITLE
fix: shut down test without error

### LINKED ISSUE #62230: an error when run test  ./run-tests.sh: line 332: kill: (86298) - No such process

### PR DESCRIPTION
**Pull request by yihong0618**
for now when run tests  locall there's always  an error after the test

e.g. before this patch
```cli
start tidb-server, log file: ./integration-test.out
tidb-server(PID: 86298) started
record result for case: "executor/issues"
./t/executor/issues.test: ok! 467 test cases passed, take time 5.68635825 s
```

Great, All tests passed
integrationtest passed!
./run-tests.sh: line 332: kill: (86298) - No such process

This patch swallow the `trap` error for better dev experience

after this patch

```cli
# github.com/pingcap/tidb/cmd/tidb-server
building mysql-tester binary: ./mysql_tester
start tidb-server, log file: ./integration-test.out
tidb-server(PID: 95300) started
record result for case: "executor/issues"
./t/executor/issues.test: ok! 465 test cases passed, take time 5.830736958 s

Great, All tests passed
```

Issue Number: close #62230

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/globalkilltest/run-tests.sh [hunk 1]
```diff
@@ -14,7 +14,7 @@
 # limitations under the License.
 
 set -eu
-trap 'set +e; PIDS=$(jobs -p); [ -n "$PIDS" ] && kill -9 $PIDS' EXIT
```
Comment (lance6716) [inline tests/globalkilltest/run-tests.sh:17]: we don't need to add a `for` loop? I think the key  point of this fix is `|| true`

**Review by lance6716 — COMMENTED** [review]
please update PR description

File: tests/globalkilltest/run-tests.sh (hunk 1 above)
Comment (yihong0618) [reply tests/globalkilltest/run-tests.sh:17]: That is better will fix it on weekend~

On vocation for now 😌

Comment (yihong0618) [reply tests/globalkilltest/run-tests.sh:17]: @lance6716 checked kill -9 xxx || true  also have this error
we can only kill one by one then || true

Comment (lance6716) [reply tests/globalkilltest/run-tests.sh:17]: I did a simple test

```
[root@vm172-16-201-151 cse]# pgrep vim
473188
[root@vm172-16-201-151 cse]# kill 12345 473188 || true && echo "$?"
-bash: kill: (12345) - No such process
0
```

seems we don't need to kill them one by one. And this is my bash version

```
[root@vm172-16-201-151 cse]# bash --version
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Comment (yihong0618) [reply tests/globalkilltest/run-tests.sh:17]: yes it also has warning

echo "$?"
-bash: kill: (12345) - No such process

**Review by lance6716 — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]
