### PR TITLE
*: kill auto analyze out of the auto analyze time windows

### LINKED ISSUE #55283: cannot kill auto-analyze which is out the analyze time window
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

With 1m tables which is unhealthy, start auto analyze and set the analyze time windows. 

### 2. What did you expect to see? (Required)

it can still run
### 3. What did you see instead (Required)

it cannot run because it will be killed.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #55283

Problem Summary:

### What changed and how does it work?

TiDB forget to kill the anto analyze which is out of the time windows

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/autoanalyze/exec/exec.go [hunk 1]
```diff
@@ -72,7 +72,8 @@ func AutoAnalyze(
 	}
 }
 
-func execAnalyzeStmt(
+// RunAnalyzeStmt executes the analyze statement.
+func RunAnalyzeStmt(
```
Comment (hawkingrei) [inline pkg/statistics/handle/autoanalyze/exec/exec.go:76]: Be public for test and ```exec.ExecXXXX``` is not acceptable for linter.

**Review by qw4990 — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
