### PR TITLE
test: stabilize test case

### LINKED ISSUE #21912: PANIC: pessimistic_test.go:657: testPessimisticSuite.TestInnodbLockWaitTimeout failed
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/68245/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/68245/display/redirect</a>

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #21912 #17991

Problem Summary:
If the lock is resolved and no lock error reportes, the test may panic like this:
[2020-12-23T18:27:10.707Z] PANIC: pessimistic_test.go:657: testPessimisticSuite.TestInnodbLockWaitTimeout
[2020-12-23T18:27:10.707Z] 
[2020-12-23T18:27:10.707Z] ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x1392B31)
[2020-12-23T18:27:10.707Z] 
[2020-12-23T18:27:10.707Z] /usr/local/go/src/runtime/panic.go:679
[2020-12-23T18:27:10.707Z]   in gopanic
[2020-12-23T18:27:10.707Z] /usr/local/go/src/runtime/panic.go:199
[2020-12-23T18:27:10.707Z]   in panicmem
[2020-12-23T18:27:10.707Z] /usr/local/go/src/runtime/signal_unix.go:394
[2020-12-23T18:27:10.707Z]   in sigpanic
[2020-12-23T18:27:10.707Z] pessimistic_test.go:739
[2020-12-23T18:27:10.707Z]   in testPessimisticSuite.TestInnodbLockWaitTimeout
[2020-12-23T18:27:10.707Z] /usr/local/go/src/reflect/value.go:321
[2020-12-23T18:27:10.707Z]   in Value.Call

### What is changed and how it works?

What's Changed:
The default set for test 300ms is a bit short, try increasing the `ManagedLockTTL` in the test so that the lock will not be resolved testing with TiKV.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- `No release note`

### CODE REVIEW

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
Please check the err before `c.Check(err.Error(), Equals, tikv.ErrLockWaitTimeout.Error())`.

File: session/pessimistic_test.go [hunk 1]
```diff
@@ -703,10 +709,15 @@ func (s *testPessimisticSuite) TestInnodbLockWaitTimeout(c *C) {
 		tk5.MustExec("set innodb_lock_wait_timeout = 2")
 		tk5.MustExec("begin pessimistic")
 		_, err := tk5.Exec("update tk set c2 = c2 - 1 where c1 = 1")
-		c.Check(err.Error(), Equals, tikv.ErrLockWaitTimeout.Error())
+		timeoutErrCh <- err
 		tk5.MustExec("rollback")
 	}()
 
+	timeoutErr := <-timeoutErrCh
+	c.Assert(timeoutErr.Error(), Equals, tikv.ErrLockWaitTimeout.Error())
```
Comment (wjhuang2016) [inline session/pessimistic_test.go:717]: I mean, make sure err is not null before calling err.Error(), otherwise may lead to panic.

**Review by you06 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
LGTM
