### PR TITLE
ddl: check TTL constraints for temporary tables

### LINKED ISSUE #64948: Should check the TTL constraints in `create temporary table like ...`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(t timestamp) ttl=`t` + interval 1 day;
create temporary table temp like t;
show create table temp;
```

### 2. What did you expect to see? (Required)

temporary table should not have TTL options

### 3. What did you see instead (Required)

```
> show create table temp;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                       |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| temp  | CREATE TEMPORARY TABLE `temp` (                                                                                                                                    |
|       |   `t` timestamp NULL DEFAULT NULL                                                                                                                                  |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin /*T![ttl] TTL=`t` + INTERVAL 1 DAY */ /*T![ttl] TTL_ENABLE='ON' */ /*T![ttl] TTL_JOB_INTERVAL='24h' */ |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by cryo-zd**
### What problem does this PR solve?

Issue Number: close #64948
This PR checked TTL constraints and removed them( if set ) when executing statement `create temporary table temp like t;` 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/create_table.go [hunk 1]
```diff
@@ -1268,7 +1268,10 @@ func BuildTableInfoWithLike(ident ast.Ident, referTblInfo *model.TableInfo, s *a
 		tblInfo.Partition = &pi
 	}
 
-	if referTblInfo.TTLInfo != nil {
+	// for issue #64948, temporary table does not support TLL, we should remove it
+	if s.TemporaryKeyword != ast.TemporaryNone {
+		tblInfo.TTLInfo = nil
```
Comment (YangKeao) [inline pkg/ddl/create_table.go:1283]: IMO, it'd be better to validate after it builds the table. I'd suggest to add the check in `(*DDLExec).createSessionTemporaryTable`: `if tblInfo.TTLInfo != nil {return dbterror.ErrTempTableNotAllowedWithTTL}`.

Because for other cases, `create table like` and `create global temporary table like ON COMMIT DELETE ROWS;`, they are also validated after `BuildTableInfoWithLike`.

**Comment by YangKeao** [comment]
Good job. I've checked the following case (on tidb master branch):

```
mysql> create table t (id int primary key, created_time datetime) TTL = created_time + interval 24 hour;
Query OK, 0 rows affected (0.04 sec)

mysql> create temporary table t1 like t;
Query OK, 0 rows affected (0.00 sec)

mysql> create temporary table t2 (id int primary key, created_time datetime) TTL = created_time + interval 24 hour;
ERROR 8151 (HY000): Set TTL for temporary table is not allowed
mysql> create global temporary table t2 like t ON COMMIT DELETE ROWS;
ERROR 8151 (HY000): Set TTL for temporary table is not allowed
```

It seems that the `create temporary table like` is the only issue.
