### PR TITLE
ddl, planner: avoid running queries on the non-Public state table

### LINKED ISSUE #55813: FK constraint might not enforced when child table is in state write_only
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use the case in the design doc: https://github.com/pingcap/tidb/blob/b71f6c33d69ff8884d4ef3d15f9db485fba9926f/docs/design/2022-06-22-foreign-key.md#L104-L115

steps:
1. apply this diff to code of v8.1.0, after that we will wait when create child table and it's in write-only state, and on 4001 node, we skip load schema diff of child table, so we can make a case that 4000 and 4001 have different version
```diff
diff --git a/pkg/ddl/ddl_worker.go b/pkg/ddl/ddl_worker.go
index 916458f1d0..1dc34f79f0 100644
--- a/pkg/ddl/ddl_worker.go
+++ b/pkg/ddl/ddl_worker.go
@@ -1430,6 +1430,9 @@ func waitSchemaChanged(d *ddlCtx, waitTime time.Duration, latestSchemaVersion in
                         return nil
                 }
         }
+        if job.TableName == "child" {
+                time.Sleep(time.Hour)
+        }

         return checkAllVersions(d, job, latestSchemaVersion, timeStart)
 }
diff --git a/pkg/infoschema/builder.go b/pkg/infoschema/builder.go
index d03b07d7d1..62347c888e 100644
--- a/pkg/infoschema/builder.go
+++ b/pkg/infoschema/builder.go
@@ -659,6 +659,9 @@ func applyCreateTable(b *Builder, m *meta.Meta, dbInfo *model.DBInfo, tableID in
                         fmt.Sprintf("(Table ID %d)", tableID),
                 )
         }
+        if tblInfo.Name.L == "child" && config.GetGlobalConfig().Port == 4001 {
+                return []int64{}, nil
+        }

         b.updateBundleForCreateTable(tblInfo, tp)
```
2. start 2 tidb on port 4000 and 4001
3. connect 4000, and run below, it will block on create `child`, check `admin show ddl jobs 1` to make sure child is in write_only state.
```sql
CREATE TABLE parent (
    id INT KEY
);

insert into parent values(1)

CREATE TABLE child (
    id INT,
    pid INT,
    INDEX idx_pid (pid),
    FOREIGN KEY (pid) REFERENCES parent(id) ON DELETE CASCADE
);
```
3. start 2 sessions, and run the case in the design doc

|connect 4000 session| 4001 session|
|---|---|
|begin||
|insert into child values(1,1)||
||begin|
||delete from parent where id=1; // it blocks until prev txn commit|
|commit||
||commit|
|select * from child; // we can see 1 row||
||select * from parent;// empty result|

### 2. What did you expect to see? (Required)
FK constraint enforced
### 3. What did you see instead (Required)
it's not
### 4. What is your TiDB version? (Required)
8.1.0

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #55813

Problem Summary:

When the table is in `WriteOnly` state (and hasn't been synchronized to other tidb instances), it'll cause inconsistency:

|WriteOnly TiDB| None TiDB |
|---|---|
|begin||
|insert into child values(1,1)||
||begin|
||delete from parent where id=1; // it blocks until prev txn commit|
|commit||
||commit|
|select * from child; // we can see 1 row||
||select * from parent;// empty result|

### What changed and how does it work?

Make the table invisible when it's in `WriteOnly/DeleteOnly` state. Previously, the users can see/write/delete any data for any table without considering the state. I think it's because the key range of the table is not affected by newly written things, so the `DROP TABLE` always has a good behavior.

In conclusion, the behavior of foreign key in ` `WriteOnly` (or `DeleteOnly` is that:

1. The table is not visible for any explicit DML (or any query? Maybe only DML is enough 🤔, but make it always invisible is clearer).
2. The table will be modified by implicit modification caused by ON DELETE CASCADE or ON UPDATE CASCADE

For more detail, see #55813

This PR also modified the state from `WriteOnly` to `DeleteOnly`. Both state have the same effect, but using `DeleteOnly` is more suitable considering the semantic.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

TODO

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by YangKeao** [comment]
/hold

I'm doing some manual test.

**Comment by YangKeao** [comment]
Another concern is that: when the table is in `WriteOnly` state, should it show in the `show tables`? The current behavior is that it'll show in the `show tables`, and I didn't change the behavior in this PR.

File: pkg/planner/core/preprocess.go [hunk 1]
```diff
@@ -1634,6 +1634,10 @@ func (p *preprocessor) handleTableName(tn *ast.TableName) {
 			return
 		}
 	}
+	if err := p.checkTableVisible(tableInfo); err != nil {
```
Comment (crazycs520) [inline pkg/planner/core/preprocess.go:1637]: I am not sure about this modification, please ask the DDL owner to take a look.

REST LGTM.

File: pkg/infoschema/builder.go [hunk 2]
```diff
@@ -341,6 +341,18 @@ func (b *Builder) getTableIDs(diff *model.SchemaDiff) (oldTableID, newTableID in
 		newTableID = diff.TableID
 	case model.ActionDropTable, model.ActionDropView, model.ActionDropSequence:
 		oldTableID = diff.TableID
+
+		// Still keep the table in infoschema until when the state of table reaches StateNone. This is because
+		// the `ON DELETE/UPDATE CASCADE` function of foreign key may need to find the table in infoschema. Not
+		// only the table with foreign keys are stored in the infoschema to keep a consistent behavior for all
+		// tables.
+		tblInfo, err := m.GetTable(diff.SchemaID, oldTableID)
```
Comment (YangKeao) [inline pkg/infoschema/builder.go:349]: Here is the key change to avoid removing `WriteOnly` table from the infoschema.

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/executor/infoschema_reader_test.go [hunk 3]
```diff
@@ -1066,3 +1066,43 @@ func TestInfoschemaTablesSpecialOptimizationCovered(t *testing.T) {
...
+
+func testInfoschemaTablesWhenTableIsNotPublic(t *testing.T, enableV2 bool) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	if enableV2 {
+		tk.MustExec("set @@global.tidb_schema_cache_size = 512 * 1024 * 1024")
+	} else {
+		tk.MustExec("set @@global.tidb_schema_cache_size = 0")
+	}
```
Comment (tiancaiamao) [inline pkg/executor/infoschema_reader_test.go:1078]: This is unnecessary now?  We 70% chance run v2 and 30% chance v1 automatically (in testkit).
So there is no need to do it twice.

File: pkg/infoschema/builder.go (hunk 2 above)
Comment (tiancaiamao) [reply pkg/infoschema/builder.go:349]: FYI: In the past, there is a bug https://github.com/pingcap/tidb/issues/54906 and the behaviour is:
infoschema full load do not load any non-public table
apply diff load the tables in the intermediate state.

And it's fixed to load all non-publice tables recently.

File: pkg/infoschema/builder.go [hunk 4]
```diff
@@ -341,6 +341,18 @@ func (b *Builder) getTableIDs(diff *model.SchemaDiff) (oldTableID, newTableID in
...
+		if err != nil {
+			return 0, 0, err
```
Comment (tiancaiamao) [inline pkg/infoschema/builder.go:351]: When will this code branch happen?
If an error is returned, it cause full reload ... and not easy to notice the case.

Comment (tiancaiamao) [reply pkg/infoschema/builder.go:351]: Because everything still works, just slower.

File: pkg/infoschema/infoschema_v2.go [hunk 5]
```diff
@@ -49,6 +49,7 @@ type tableItem struct {
 	tableID       int64
 	schemaVersion int64
 	tomb          bool
+	state         model.SchemaState
```
Comment (tiancaiamao) [inline pkg/infoschema/infoschema_v2.go:52]: This should be the value field instead of the key field?

Comment (tiancaiamao) [reply pkg/infoschema/infoschema_v2.go:52]: The non-public state is also a schema version ...

File: pkg/infoschema/infoschema_v2_test.go [hunk 6]
```diff
@@ -657,15 +657,34 @@ func TestDataStructFieldsCorrectnessInSchemaChange(t *testing.T) {
...
+	require.False(t, tblItem.tomb)
+	tblItem, ok = v2.Data.byID.Get(tableItem{tableID: tblInfo.ID, schemaVersion: 5})
+	require.True(t, ok)
+	require.False(t, tblItem.tomb)
+	_, ok = v2.Data.tableCache.Get(tableCacheKey{tableID: tblInfo.ID, schemaVersion: 5})
+	require.True(t, ok)
+	require.Equal(t, v2.Data.pid2tid.Len(), 5) // tomb partition info
+	tblInfoItem, ok = v2.Data.pid2tid.Get(partitionItem{partitionID: 1, schemaVersion: 5})
+	require.True(t, ok)
+	require.False(t, tblInfoItem.tomb)
```
Comment (tiancaiamao) [inline pkg/infoschema/infoschema_v2_test.go:675]: Do you mean it's a drop table but the state is not public still, so not tomb?

File: pkg/executor/infoschema_reader_test.go (hunk 3 above)
Comment (YangKeao) [reply pkg/executor/infoschema_reader_test.go:1078]: It may be treated as a flaky test if it has the opportunity to success :facepalm:. BTW, by default, bazel will retry the failed tests (marked with `flaky = True`) three times, so it has more chances to success.

Therefore, I think it's better to actually run it twice.

File: pkg/infoschema/infoschema_v2_test.go (hunk 6 above)
Comment (YangKeao) [reply pkg/infoschema/infoschema_v2_test.go:675]: Yes.
The expected behavior is that all functions should return all tables in any state (except tables in `None` state), then the callers can filter out the needed tables.

If it's marked as `tomb`, it seems that some functions (like `IterateAllTableItems` and `SchemaSimpleTableInfos`) will not return the table, then it'll be easy for the callers to make mistakes. For example, during `drop schema`, tidb will call `checkDatabaseHasForeignKeyReferred -> is.SchemaSimpleTableInfos` to check whether a database has foreign key referred. If a table is marked `tomb`, it'll give unexpected result.

Though it's actually not a big issue because everything will finally be dropped, it's only an example to show that it's easy to make mistakes / the logic becomes hard to think or understand if it's marked as `tomb` during dropping tables.

File: pkg/infoschema/infoschema_v2.go (hunk 5 above)
Comment (YangKeao) [reply pkg/infoschema/infoschema_v2.go]: Removed.

File: pkg/executor/infoschema_reader_test.go (hunk 3 above)
Comment (YangKeao) [reply pkg/executor/infoschema_reader_test.go]: Not needed now.

**Review by tiancaiamao — APPROVED** [review]

File: pkg/planner/core/preprocess.go [hunk 7]
```diff
@@ -1839,14 +1839,39 @@ func (p *preprocessor) hasAutoConvertWarning(colDef *ast.ColumnDef) bool {
 	return false
 }
 
-func tryLockMDLAndUpdateSchemaIfNecessary(ctx context.Context, sctx base.PlanContext, dbName pmodel.CIStr, tbl table.Table, is infoschema.InfoSchema) (table.Table, error) {
+func tryLockMDLAndUpdateSchemaIfNecessary(ctx context.Context, sctx base.PlanContext, dbName pmodel.CIStr, tbl table.Table, is infoschema.InfoSchema) (retTbl table.Table, err error) {
+	skipLock := false
+	shouldLockMDL := false
+	var lockedID int64
+
+	defer func() {
```
Comment (winoros) [inline pkg/planner/core/preprocess.go:1847]: Why it's defined as a defer instead of directly checking it?

Comment (YangKeao) [reply pkg/planner/core/preprocess.go:1847]: Because we need to check `retTbl`. The only way to check the `retTbl` without modifying every `return` statement is to check it in `defer` :thinking:  .

The `retTbl` can be different with the `tbl` in argument, so we cannot check it only once at the entry of this function.

**Review by winoros — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
