### PR TITLE
executor, session: store utf8 string in `sessionctx`

### LINKED ISSUE #57646: TiDCD CI failed after PR 57393
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

CI Pass.

### 3. What did you see instead (Required)

You can find the error in https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_cdc_integration_kafka_test/detail/pull_cdc_integration_kafka_test/3278/pipeline/

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #57646

Problem Summary:

TiCDC relies on DDL Statements from `mysql.tidb_ddl_history` table to do replication in downstream database, and these DDL statements are obtained through the `OriginText()` function.

https://github.com/pingcap/tidb/blob/6e22b8cb1314b539dec40623c17d0df577cc7af4/pkg/session/session.go#L2265

https://github.com/pingcap/tidb/blob/6e22b8cb1314b539dec40623c17d0df577cc7af4/pkg/executor/adapter.go#L379-L380

Before PR #57393, `OriginText` mistakenly return UTF-8 encoded queries. However, after that PR, this function returns the original queries, which may lead to different results in the upstream and downstream.

For example, in the failed CI,  DDLs use GBK encoding. Therefore, you can see the following results in the log:

```
An error occured while initializing diff: from upstream: please make sure the filter is correct.: the target has no table to be compared. source-table is ``test`.`表2``, please check log info in /tmp/tidb_cdc_test/kafka_simple_basic/output/sync_diff.log for full details

An error occured while initializing diff: from upstream: please make sure the filter is correct.: the source has no table to be compared. target-table is ``test`.`��2``, please check log info in /tmp/tidb_cdc_test/kafka_simple_basic/output/sync_diff.log for full details
```

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/adapter.go [hunk 1]
```diff
@@ -381,6 +379,11 @@ func (a *ExecStmt) OriginText() string {
 	return a.StmtNode.OriginalText()
 }
 
+// Text returns utf8 encoded statement as a string.
+func (a *ExecStmt) Text() string {
+	return a.StmtNode.Text()
```
Comment (lcwangchao) [inline pkg/executor/adapter.go:384]: You can just use `a.Text`

**Review by lcwangchao — APPROVED** [review]

**Review by zimulala — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
