### PR TITLE
planner: Handle NullEQ <=> in range columns partition pruning

### LINKED ISSUE #61176: Partition table work with PointGet plan get a wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t235e2b52` (
  `col_36` bigint DEFAULT NULL,
  `col_37` varchar(463) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'T',
  `col_39` bigint DEFAULT '272523819217945548',
  `col_40` timestamp DEFAULT '2023-09-11 00:00:00',
  `col_41` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `col_42` bigint unsigned NOT NULL DEFAULT '5329417101757332864',
  PRIMARY KEY (`col_37`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
PARTITION BY RANGE COLUMNS(`col_37`)
(PARTITION `p0` VALUES LESS THAN ('q&Gmxiqq8qDCv1Lc5w'),
 PARTITION `p1` VALUES LESS THAN (MAXVALUE));

insert into t235e2b52(col_37, col_41) values ('YOqtJ', '');
select * from t235e2b52 where col_37 <=> 'YOqtJ';
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t235e2b52 where col_37 <=> 'YOqtJ';
+--------+--------+--------------------+---------------------+--------+---------------------+
| col_36 | col_37 | col_39             | col_40              | col_41 | col_42              |
+--------+--------+--------------------+---------------------+--------+---------------------+
|   NULL | YOqtJ  | 272523819217945548 | 2023-09-11 00:00:00 |        | 5329417101757332864 |
+--------+--------+--------------------+---------------------+--------+---------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

Before https://github.com/pingcap/tidb/pull/61141, return empty result.

After https://github.com/pingcap/tidb/pull/61141, report unexpected error like
```
mysql> select * from t235e2b52 where col_37 <=> 'YOqtJ';
ERROR 1105 (HY000): too many partitions matching for PointGetPlan
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #61176

Problem Summary:

### What changed and how does it work?
Partition pruning for NullEQ `<=>` of range columns could return more than one partition, resulting in PointGet failed.

Added handling to first check if constant is NULL, then just use first partition, else treat as EQ `=`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fixed an issue where PointGet could fail when using NullEQ (<=>) for a table partitioned by range column
```

### CODE REVIEW

File: pkg/planner/core/casetest/partition/partition_pruner_test.go [hunk 1]
```diff
@@ -649,3 +649,109 @@ func TestIssue61134(t *testing.T) {
...
+		tk.MustExec(`drop table t`)
+		tk.MustExec(`CREATE TABLE t (a int PRIMARY KEY)` + t.partitionBy)
+		tk.MustExec(`insert into t values (1),(5)`)
+		tk.MustContainErrMsg(`insert into t values (NULL)`, "[table:1048]Column 'a' cannot be null")
+		tk.MustQuery(`select a from t where a <=> 1`).Check(testkit.Rows("1"))
+		tk.MustQuery(`select a from t where a <=> 5`).Check(testkit.Rows("5"))
+		tk.MustQuery(`select a from t where a <=> NULL`).Check(testkit.Rows())
+		tk.MustQuery(`explain format=brief select a from t where a <=> 1`).MultiCheckContain([]string{"Point_Get", "partition:" + t.part1})
+		tk.MustQuery(`explain format=brief select a from t where a <=> 5`).MultiCheckContain([]string{"Point_Get", "partition:" + t.part5})
+		// TODO: Also do this for RANGE COLUMNS? Why is this different?!?
```
Comment (Defined2014) [inline pkg/planner/core/casetest/partition/partition_pruner_test.go:753]: Maybe because `a` will not be `null` here, so the planner has made an optimization in advance.

Comment (mjonss) [reply pkg/planner/core/casetest/partition/partition_pruner_test.go:753]: So `a` cannot be NULL here, since it is the primary key (not null), but above for RANGE COLUMNS, it should be the same, i.e. the optimizer should detect it there as well.
But I think that is outside the scope of this issue.

File: pkg/planner/core/rule_partition_processor.go [hunk 2]
```diff
@@ -1423,6 +1423,10 @@ func (p *rangePruner) partitionRangeForExpr(sctx base.PlanContext, expr expressi
 	if !ok {
 		return 0, 0, false
 	}
+	if dataForPrune.op == ast.NullEQ {
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/rule_partition_processor.go]: Good suggestion, I changed the `(*rangePruner) extractDataForPrune()` to return `ast.IsNull` if `ast.NullEQ` and `IsNull`, since IsNull is already handled in `pruneUseBinarySearch()`

**Review by hawkingrei — APPROVED** [review]
