### PR TITLE
gc_worker: Fix the problem that GC may kill the transaction whose start ts is exactly the same as the txn safe point

### LINKED ISSUE #64662: GC may kill the transaction whose start ts is exactly the same as the txn safe point
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Start a transaction that keeps running for a long time.
2. (Under default configuration) Wait for 2 turns of GC, so that the txn safe point would be blocked by the long transaction and has the same value as the transaction's start ts.
3. Start a transaction that writes the same key as the first transaction (prevent TiKV's amending lock behavior).
4. Try to commit the first transaction.

### 2. What did you expect to see? (Required)

* The first transaction shouldn't be killed by GC
* The second transction (in step 3) should be blocked)
* The first transction can finally successfully commit.

### 3. What did you see instead (Required)

The first transaction may be killed by resolving lock.

### 4. What is your TiDB version? (Required)

master (classic, nextgen)

### Explanation

In the GC refactor project #8978 , the beehavior and definition is strengthened. One of the rules is that transactions whose start ts >= txn safe point should be safe to run. Note it's inclusive.

However, the `scan_lock` API of TiKV accepts the parameter `max_version` and uses it to scan locks, inclusively. When we pass the txn safe point directly to `max_version` during resolve locks, it may force rolling back the trasnaction that shouldn't be rolled back.

The problem doesn't exist before because we don't have strict definition of the behavior when some transaction's ts exactly equals to the safe point, and the case was avoided silently by non-strict calculation that drops the logical part of the timestamps.

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

Issue Number: close #64662

Problem Summary:

### What changed and how does it work?

This PR passes txnSafePoint - 1, instead of txnSafePoint itself, to the resolving lock function which accepts `maxVersion` when scanning locks to be resolved. This avoids locks whose ts exactly equals to the txnSafePoint to be unexpectedly resolved.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/store/mockstore/unistore/tikv/mvcc.go [hunk 1]
```diff
@@ -1590,7 +1590,7 @@ func (store *MVCCStore) Cleanup(reqCtx *requestCtx, key []byte, startTS, current
 
 func (store *MVCCStore) appendScannedLock(locks []*kvrpcpb.LockInfo, it *lockstore.Iterator, maxTS uint64) []*kvrpcpb.LockInfo {
 	lock := mvcc.DecodeLock(it.Value())
-	if lock.StartTS < maxTS {
+	if lock.StartTS <= maxTS {
```
Comment (MyonKeminta) [inline pkg/store/mockstore/unistore/tikv/mvcc.go:1593]: The implementation in unistore was inconsistent with TiKV before.

**Review by tiancaiamao — APPROVED** [review]
Shall we add some comment or document at SOME PLACE about txn_safe_point, that start ts == txn_safe_point is valid to avoid the +-1 problem in the future? @MyonKeminta
