### PR TITLE
ddl: ignore reorg elem error when the job is cancelling

### LINKED ISSUE #41381: Unexpected error "DDL reorg element does not exist" when adding index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(id int primary key, b int);
insert into t values (1, 1);
alter table t add unique index idx(b);

insert into t values (2, 1); -- write only
admin cancel ddl jobs X; -- the job must be rolling back because of the duplicated entry
```

It is not easy to reproduce with MySQL client because the state changes are usually fast.

### 2. What did you expect to see? (Required)

```
Cancelled DDL job
```

or

```
Duplicate entry '1' for key 't.idx'
```

### 3. What did you see instead (Required)

```
ERROR 8235 (HY000): DDL job rollback, error msg: DDL reorg element does not exist
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #41381

Problem Summary:

The root cause is the write-conflict between DDL job's transaction and `ADMIN CANCEL` transaction. The latter wins and aborts the DDL job's transaction. As a result, the "duplicate entry" error is lost.

DDL worker starts to handle the cancelling case. It finds that the job is in write-reorg state, and tries to pick up the work by getting reorg handle. However, the reorg handle is cleaned by another previous transaction.

### What is changed and how it works?

This PR ignores the "reorg element not exist" error when the job is cancelling.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: ddl/ddl_worker.go [hunk 1]
```diff
@@ -770,6 +770,10 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
 	// and retry later if the job is not cancelled.
 	schemaVer, runJobErr = w.runDDLJob(d, t, job)
 
+	d.mu.RLock()
```
Comment (Benjamin2037) [inline ddl/ddl_worker.go:773]: Does this code only for test？

Comment (tangenta) [reply ddl/ddl_worker.go:773]: Yes.

File: ddl/column.go [hunk 2]
```diff
@@ -822,7 +822,7 @@ func doReorgWorkForModifyColumn(w *worker, d *ddlCtx, t *meta.Meta, job *model.J
 		return false, ver, errors.Trace(err)
 	}
 	reorgInfo, err := getReorgInfo(d.jobContext(job.ID), d, rh, job, dbInfo, tbl, BuildElements(changingCol, changingIdxs), false)
-	if err != nil || reorgInfo.first {
+	if err != nil || reorgInfo == nil || reorgInfo.first {
```
Comment (Benjamin2037) [inline ddl/column.go:825]: Why modify column need this logic？

Comment (tangenta) [reply ddl/column.go:825]: Because `reorgInfo` is possible to be `nil` after the changes in `getReorgInfo`. `reorgInfo == nil` means the job is cancelling.

File: ddl/ddl_worker.go (hunk 1 above)
Comment (Benjamin2037) [reply ddl/ddl_worker.go:773]: Do we have a way to execute these three lines codes only in test?

Comment (tangenta) [reply ddl/ddl_worker.go:773]: The overhead is negligible. 

Please also check the other methods of this interface. All of them are written in this style.

**Review by Benjamin2037 — APPROVED** [review]
LGTM

File: ddl/ddl_worker.go (hunk 1 above)
Comment (Benjamin2037) [reply ddl/ddl_worker.go:773]: I know the lock and a nil function call and unlock overhead is very small. Just want to know if there is a way like c "debug micro" that only debug mode has this code.
