### PR TITLE
planner: fix a sporadic panic due to the PR #7684 when using the prepared plan cache

### LINKED ISSUE #8065: prepare panic via binary protocol when plan cache is enable
## Bug Report

1. What did you do?
If possible, provide a recipe for reproducing the error.

first enable plan cache via `tidb.toml` configuration file.

a. create two table

```sql
create table test1 (id int, v int);
create table test2 (id int, k int, v int);
```

b. prepare and execute 2 sql in binary mode(cli's `prepare stmt from xxx` have no problem)

```sql
select * from test1 where id = ?;
select * from test2 where id = ? and k = ?
```
can use this java snippet

```java
	List<String> text;

	@PostConstruct
	public void init() throws IOException {
		tests = new ArrayList<>(9);
		tests.add(new Entry(){{
			sql = "SELECT * FROM test1 WHERE id = ?";
			args = new String[][] {
					{"3"},
			};
		}});

		tests.add(new Entry(){{
			sql = "SELECT * FROM test2 WHERE id = ? AND k = ?`";
			args = new String[][] {
					{"1", "2"},
			};
		}});
	}


	@RequestMapping("/")
	public Map<String, Object> test() throws SQLException {
		for (Entry test : tests) {
			runSQL(test.sql, test.args);
		}
		return new HashMap<>();
	}

	private void runSQL(String sql, String[][] execs) throws SQLException {
		try (Connection connection = dataSource.getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
			for (String[] args : execs) {
				for (int i = 0; i < args.length; i++) {
					preparedStatement.setString(i + 1, args[i]);
				}
				ResultSet resultSet = preparedStatement.executeQuery();
				while (resultSet.next()) { }
			}
		}
	}
```

2. What did you expect to see?

```
execute success
```

3. What did you see instead?

TiDB Panic with

```
2018/10/26 01:04:09.865 conn.go:427: [error] lastCmd SELECT * FROM test2 WHERE id = ? AND k = ?`, runtime error: index out of range, goroutine 564 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc00a4ec0d0, 0xc00762bbf0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:425 +0xc2
panic(0x175da60, 0x2a46240)
	/home/robi/go1.11.1/src/runtime/panic.go:513 +0x1e6
github.com/pingcap/tidb/expression.(*builtinGetParamStringSig).evalString(0xc007e02fc0, 0x0, 0x0, 0x0, 0x0, 0x7fe9c044f600, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/expression/builtin_other.go:772 +0x34b
github.com/pingcap/tidb/expression.(*ScalarFunction).EvalString(0xc0099b8aa0, 0x1c4aea0, 0xc00a448d20, 0x0, 0x0, 0x0, 0x0, 0x418600, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/expression/scalar_function.go:217 +0x95
github.com/pingcap/tidb/expression.(*ScalarFunction).Eval(0xc0099b8aa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/robi/Code/go/src/github.com/pingcap/tidb/expression/scalar_function.go:189 +0x677
github.com/pingcap/tidb/expression.foldConstant(0x1c4a1e0, 0xc007ef4af0, 0x0, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/expression/constant_fold.go:145 +0x1987
github.com/pingcap/tidb/expression.foldConstant(0x1c4a360, 0xc0099b8af0, 0x0, 0x0, 0x40f100)
	/home/robi/Code/go/src/github.com/pingcap/tidb/expression/constant_fold.go:95 +0x3b8
github.com/pingcap/tidb/expression.FoldConstant(0x1c4a360, 0xc0099b8af0, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/expression/constant_fold.go:34 +0x45
github.com/pingcap/tidb/expression.NewFunction(0x1c4aea0, 0xc00a448d20, 0x1920b92, 0x2, 0xc00a61a7e0, 0xc007629a80, 0x2, 0x2, 0x0, 0x0, ...)
	/home/robi/Code/go/src/github.com/pingcap/tidb/expression/scalar_function.go:99 +0x5e7
github.com/pingcap/tidb/planner/core.(*expressionRewriter).constructBinaryOpFunction(0xc009768e80, 0x1c4a120, 0xc009ef97a0, 0x1c4a1e0, 0xc007ef4af0, 0x1920b92, 0x2, 0x0, 0x0, 0x0, ...)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:184 +0x202
github.com/pingcap/tidb/planner/core.(*expressionRewriter).binaryOpToExpression(0xc009768e80, 0xc00a6eca90)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:914 +0x17c
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave(0xc009768e80, 0x1c1d7e0, 0xc00a6eca90, 0x0, 0x0, 0xc000689200)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:776 +0xf15
github.com/pingcap/tidb/ast.(*BinaryOperationExpr).Accept(0xc00a6eca90, 0x1c196c0, 0xc009768e80, 0x0, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/ast/expressions.go:227 +0x440
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc0006d9b80, 0xc009768e80, 0x1c34340, 0xc00a6eca90, 0xc000689200, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:133 +0x8d
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc0006d9b80, 0x1c34340, 0xc00a6eca90, 0x1c4a420, 0xc0074a14a0, 0x0, 0xc007dbbe00, 0x0, 0x0, 0x0, ...)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:105 +0x1ec
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewrite(0xc0006d9b80, 0x1c34340, 0xc00a6eca90, 0x1c4a420, 0xc0074a14a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:81 +0xd8
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelection(0xc0006d9b80, 0x1c4a420, 0xc0074a14a0, 0x1c34340, 0xc00a6ecb60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:464 +0x29b
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc0006d9b80, 0xc008ded0e0, 0x1c4a420, 0xc0074a14a0, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:1704 +0x9f2
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc0006d9b80, 0x1c1e8a0, 0xc008ded0e0, 0x0, 0x0, 0x0, 0x0)
	/home/robi/Code/go/src/github.com/pingcap/tidb/planner/core/planbuilder.go:178 +0xe0d
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v2.0.0-rc.4-881-g19f56480d-dirty
Git Commit Hash: 19f56480d5591718a0d16936cb8af09d890091e9
Git Branch: fix-prepare-plan-cache-panic
UTC Build Time: 2018-10-25 05:04:59
GoVersion: go version go1.11.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by dbjoa**
### What problem does this PR solve? 

fixes #8065

Fix the panics are occurred sporadically after merging the PR #7684 when using the prepared plan cache.

```
2018/10/19 09:40:58.035 conn.go:427: [error] lastCmd UPDATE usertable SET field9=? WHERE YCSB_KEY = ?, runtime error: index out of range, goroutine 531 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc0071d09c0, 0xc007301dff)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/server/conn.go:425 +0x10c
panic(0x11dddc0, 0x225f220)
    /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/pingcap/tidb/expression.(*builtinGetParamStringSig).evalString(0xc0080de400, 0x0, 0x0, 0x0, 0xc28114, 0xc0080de400, 0x15493a0, 0xc0072a2b60)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/builtin_other.go:772 +0x1ec
github.com/pingcap/tidb/expression.(*ScalarFunction).EvalString(0xc00802f1d0, 0x15493a0, 0xc0072a2b60, 0x0, 0x0, 0x17, 0x0, 0x0, 0x116bf00, 0x86ede8)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/scalar_function.go:217 +0x4c
github.com/pingcap/tidb/expression.(*ScalarFunction).Eval(0xc00802f1d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/scalar_function.go:189 +0x439
github.com/pingcap/tidb/expression.foldConstant(0x15486e0, 0xc0080c50a0, 0x1, 0xc007ec5821, 0x1)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/constant_fold.go:145 +0x107
github.com/pingcap/tidb/expression.foldConstant(0x1548860, 0xc00802f270, 0x12a78a0, 0x13a0401, 0xc00802f270)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/constant_fold.go:95 +0x5ac
github.com/pingcap/tidb/expression.FoldConstant(0x1548860, 0xc00802f270, 0x13a042d, 0x4)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/constant_fold.go:34 +0x35
github.com/pingcap/tidb/expression.BuildCastFunction(0x15493a0, 0xc0072a2b60, 0x15486e0, 0xc0080c50a0, 0xc008102000, 0x1548860, 0xc00802f220)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/builtin_cast.go:1681 +0x2ba
github.com/pingcap/tidb/expression.WrapWithCastAsReal(0x15493a0, 0xc0072a2b60, 0x15486e0, 0xc0080c50a0, 0x1548860, 0xc00802f220)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/builtin_cast.go:1709 +0x135
github.com/pingcap/tidb/expression.newBaseBuiltinFuncWithTp(0x15493a0, 0xc0072a2b60, 0xc0080a4b60, 0x2, 0x2, 0xc0080a4b00, 0xc007300b96, 0x2, 0x2, 0x0, ...)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/builtin.go:74 +0x474
github.com/pingcap/tidb/expression.(*compareFunctionClass).generateCmpSigs(0xc00021f6b0, 0x15493a0, 0xc0072a2b60, 0xc0080a4b60, 0x2, 0x2, 0xc0080a4b01, 0x2, 0x2, 0x203002, ...)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1169 +0xbb
github.com/pingcap/tidb/expression.(*compareFunctionClass).getFunction(0xc00021f6b0, 0x15493a0, 0xc0072a2b60, 0xc0080a4b40, 0x2, 0x2, 0x2, 0x2, 0xc00805fec0, 0x0)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1163 +0x178
github.com/pingcap/tidb/expression.NewFunction(0x15493a0, 0xc0072a2b60, 0x139f7f2, 0x2, 0xc00805fec0, 0xc007301040, 0x2, 0x2, 0xc0073010b8, 0x10, ...)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/expression/scalar_function.go:87 +0x210
github.com/pingcap/tidb/planner/core.(*expressionRewriter).constructBinaryOpFunction(0xc007f7b900, 0x1548620, 0xc00807ae00, 0x15486e0, 0xc0080c50a0, 0x139f7f2, 0x2, 0x2, 0x10, 0x0, ...)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:184 +0xcc7
github.com/pingcap/tidb/planner/core.(*expressionRewriter).binaryOpToExpression(0xc007f7b900, 0xc008056b60)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:914 +0xe8
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave(0xc007f7b900, 0x151ac00, 0xc008056b60, 0x1532c80, 0xc007f73c80, 0x1)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:776 +0x8ec
github.com/pingcap/tidb/ast.(*BinaryOperationExpr).Accept(0xc008056b60, 0x1516b20, 0xc007f7b900, 0x1548920, 0xc0080a22c0, 0xc0073012e0)
    /home/jsheo/dev/deps/go/src/github.com/pingcap/tidb/ast/expressions.go:227 +0x1a9
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc007eeb130, 0xc007f7b900, 0x1532700, 0xc008056b60, 0x13a6900, 0x9, 0x1548f20,
2018/10/19 09:40:58.035 server.go:316: [info] con:9 close connection
```

### What is changed and how it works?
Initialize UseCache of the statement context in BuildLogicalPlan 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 - Enable the prepared plan cache in the TiDB configuration
```
[prepared-plan-cache]
enabled = true
capacity = 100
```
 - Deploy TiDB, TiKV, and PD with standalone mode
 - Create YCSB schema and user
```
create database ycsb;
use ycsb;
drop table usertable;

CREATE TABLE usertable (
    YCSB_KEY VARCHAR(255) PRIMARY KEY,
    FIELD0 TEXT, FIELD1 TEXT,
    FIELD2 TEXT, FIELD3 TEXT,
    FIELD4 TEXT, FIELD5 TEXT,
    FIELD6 TEXT, FIELD7 TEXT,
    FIELD8 TEXT, FIELD9 TEXT
) SHARD_ROW_ID_BITS = 2;

CREATE USER 'ycsb'@'localhost' IDENTIFIED BY 'pass';
CREATE USER 'ycsb'@'%' IDENTIFIED BY 'pass';
GRANT ALL ON *.* TO 'ycsb'@'localhost';
GRANT ALL ON *.* TO 'ycsb'@'%';
```

 - Load YCSB data
```
./bin/ycsb load jdbc \
        -P workloads/workloada \
        -s -p status.interval=10 \
        -p db.url='jdbc:mysql://127.0.0.1:4000/ycsb?useSSL=false&useServerPrepStmts=true&rewriteBatchedStatements=true' \
        -p db.driver=com.mysql.jdbc.Driver -p db.user=ycsb -p db.passwd=pass \
        -p jdbc.autocommit=true \
        -p recordcount=1000000 \
        -p jdbc.batchupdateapi=true \
        -p db.batchsize=100 \
        -threads 16
```
 - Run YCSB workloada (i.e., select : update = 1 : 1)
```
./bin/ycsb run jdbc \
        -P workloads/workloada \
        -s -p status.interval=10 \
        -p db.url='jdbc:mysql://127.0.0.1:4000/ycsb?useSSL=false&useServerPrepStmts=true&rewriteBatchedStatements=false' \
        -p db.driver=com.mysql.jdbc.Driver -p db.user=ycsb -p db.passwd=pass \
        -p jdbc.autocommit=true \
        -p operationcount=100000 \
        -target 1000 \
        -threads 10
```

Code changes

 - Has exported variable/fields change

Side effects

 - No

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: planner/core/optimizer.go [hunk 1]
```diff
@@ -66,6 +66,7 @@ type logicalOptRule interface {
 func BuildLogicalPlan(ctx sessionctx.Context, node ast.Node, is infoschema.InfoSchema) (Plan, error) {
 	ctx.GetSessionVars().PlanID = 0
 	ctx.GetSessionVars().PlanColumnID = 0
+	ctx.GetSessionVars().StmtCtx.UseCache = false
```
Comment (zz-jason) [inline planner/core/optimizer.go]: `StmtCtx.UseCache` is set in: https://github.com/pingcap/tidb/blob/master/executor/prepared.go#L155

Then the function `BuildLogicalPlan()` is called. Maybe it's better to set `StmtCtx.UseCache` to false before the function `BuildLogicalPlan()` call: https://github.com/pingcap/tidb/blob/master/executor/prepared.go#L162

Comment (dbjoa) [reply planner/core/optimizer.go]: If we can ensure calling `BuildLogicalPlan()`  at `prepared.go#L162` only, setting the variable at the location as you said is good. Otherwise, setting the variable in `BuildLogicalPlan()` might be a good choice in order to prevent from a potential risk because `StmtCtx.UseCache` should be false in the call paths of `BuildLogicalPlan()`.

Comment (zz-jason) [reply planner/core/optimizer.go]: Yes, we can ensure. Function `BuildLogicalPlan()` is only used in the test code and the prepare statements:

Comment (zz-jason) [reply planner/core/optimizer.go]: You can get the similar result by:
```sh
find . -name "*.go" | xargs grep --color -n "\<BuildLogicalPlan\>"
```

**Comment by jackysp** [comment]
I think we should add the following lines after https://github.com/pingcap/tidb/blob/b7a8f91e0a239b0484da6ac8b7fae7e39e01da89/session/session.go#L846
```go
	stmt := &ast.PrepareStmt{
		SQLText: sql,
	}
	if err = executor.ResetContextOfStmt(s, stmt); err != nil {
		return
	}
```
@dbjoa 
I have not tested it. Could you please provide a simple case for this bug?

**Comment by dbjoa** [comment]
@jackysp 
Unfortunately, I couldn't find a simple case to reproduce the bug. Please use [YCSB](https://github.com/brianfrankcooper/YCSB) as I mentioned above.

**Comment by lysu** [comment]
It's a simple test case:

```java
	public void testPrepareCacheIssue8065() throws Exception {
 		createTable("test_prepare1", "(a int)");
 		createTable("test_prepare2", "(a int, b int)");
 		try {
 			try (PreparedStatement pStmt = this.conn.prepareStatement("select * from test_prepare1 where a = ?")) {
 				pStmt.setInt(1, 1);
 				this.rs = pStmt.executeQuery();
 				while(this.rs.next()) {}
 			}
 			try (PreparedStatement pStmt = this.conn.prepareStatement("select * from test_prepare2 where a = ? and b = ?")) {
 				pStmt.setInt(1, 1);
 				pStmt.setInt(2, 2);
 				this.rs = pStmt.executeQuery();
 				while(this.rs.next()) {}
 			}
 		} finally {
 			if (this.rs != null) {
 				this.rs.close();
 			}
 			this.rs = null;
 		}
 	}
```

and 9643cded950678cea37ebdbe5517f028f657cc62 make plan-cache enable in CI env

**Comment by lysu** [comment]
@dbjoa how about @jackysp 's advise, I think call reset ctx if more safe too~? :laughing:

**Comment by jackysp** [comment]
@dbjoa I still prefer that we should reset the context of the statement, due to it may contain some other bugs if the context was not reset clearly.
I think you could consider @lysu ' pr https://github.com/pingcap/tidb/pull/8067 or my suggestion.

**Comment by jackysp** [comment]
PTAL @lysu
