### PR TITLE
expression: fix infinity loop in `timestampadd`

### LINKED ISSUE #54908: timestampadd may get stuck when subtracting months
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

select timestampadd(month,-10,date'2021-09-01');

### 2. What did you expect to see? (Required)

```
+------------------------------------------+
| timestampadd(month,-10,date'2021-09-01') |
+------------------------------------------+
| 2020-11-01                               |
+------------------------------------------+
```

### 3. What did you see instead (Required)

The query is stuck.

```
goroutine 18009 [runnable]:
time.Date(0xfffffffffff506dd?, 0x3?, 0x19?, 0x1?, 0x0?, 0x0?, 0x0?, 0x953e620?)
        /usr/local/go/src/time/time.go:1467 +0x4f3
time.Time.AddDate({0x0, 0xffffeb5c2c9599b9, 0x953e620}, 0x0, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/time/time.go:946 +0xdb
github.com/pingcap/tidb/pkg/expression.addUnitToTime({0x59a98c3, 0x5}, {0xc003b5d400?, 0x0?, 0x953e620?}, 0x1?)
        /workspace/source/tidb/pkg/expression/builtin_time.go:6197 +0x8db
github.com/pingcap/tidb/pkg/expression.(*builtinTimestampAddSig).evalString(0xc002fdfc30, {0x0?, 0xc0031b3490?})
        /workspace/source/tidb/pkg/expression/builtin_time.go:6235 +0x187
github.com/pingcap/tidb/pkg/expression.(*ScalarFunction).EvalString(...)
        /workspace/source/tidb/pkg/expression/scalar_function.go:464
github.com/pingcap/tidb/pkg/expression.(*ScalarFunction).Eval(0xc0031b3570, {0x0?, 0x6353540?})
        /workspace/source/tidb/pkg/expression/scalar_function.go:423 +0x2f5
github.com/pingcap/tidb/pkg/expression.foldConstant({0x63e0600?, 0xc0031b3570?})
        /workspace/source/tidb/pkg/expression/constant_fold.go:232 +0xa25
github.com/pingcap/tidb/pkg/expression.FoldConstant({0x63e0600, 0xc0031b3570})
        /workspace/source/tidb/pkg/expression/constant_fold.go:40 +0x25
github.com/pingcap/tidb/pkg/expression.newFunctionImpl({0x63e1f60, 0xc003b5d400}, 0x1, {0xc002f04e18?, 0xc001ad09c8?}, 0xc002fd9d80, 0x52d30c0?, {0xc003288140, 0x3, 0x4})
        /workspace/source/tidb/pkg/expression/scalar_function.go:252 +0x9a5
github.com/pingcap/tidb/pkg/expression.NewFunction(...)
        /workspace/source/tidb/pkg/expression/scalar_function.go:288
github.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).newFunctionWithInit(0xc002a25b20, {0xc002f04e18?, 0xc002f04e18?}, 0xc?, 0x1c0fac5?, {0xc003288140?, 0x2?, 0x10?})
        /workspace/source/tidb/pkg/planner/core/expression_rewriter.go:1408 +0xcf
github.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).newFunction(...)
        /workspace/source/tidb/pkg/planner/core/expression_rewriter.go:1421
github.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).funcCallToExpression(0xc002a25b20, 0xc002fd9d40)
        /workspace/source/tidb/pkg/planner/core/expression_rewriter.go:2142 +0xe97
github.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).Leave(0xc002a25b20, {0x6375940?, 0xc002fd9d40?})
        /workspace/source/tidb/pkg/planner/core/expression_rewriter.go:1251 +0x6ca
github.com/pingcap/tidb/pkg/parser/ast.(*FuncCallExpr).Accept(0xc002fd4680?, {0x63453d0, 0xc002a25b20})
        /workspace/source/tidb/pkg/parser/ast/functions.go:584 +0x16f
github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).rewriteExprNode(0xc002b5c000, 0xc002a25b20, {0x638c130?, 0xc002fd9d40?}, 0x1)
        /workspace/source/tidb/pkg/planner/core/expression_rewriter.go:201 +0x119
github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc002b5c000, {0x6368d60?, 0xc002fceff0?}, {0x638c130, 0xc002fd9d40}, {0x63b1be0?, 0xc002fd4680?}, 0x0, 0x0, 0x1, ...)
        /workspace/source/tidb/pkg/planner/core/expression_rewriter.go:146 +0x170
github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildProjection(0xc002b5c000, {0x6368d60, 0xc002fceff0}, {0x63b1be0?, 0xc002fd4680}, {0xc001570bd0, 0x1, 0x1?}, 0x59a6c8e?, 0x0, ...)
        /workspace/source/tidb/pkg/planner/core/logical_plan_builder.go:1804 +0x606
github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildSelect(0xc002b5c000, {0x6368d60, 0xc002fceff0}, 0xc002fd9e60)
        /workspace/source/tidb/pkg/planner/core/logical_plan_builder.go:4597 +0x14a5
github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).Build(0xc002b5c000, {0x6368d60?, 0xc002fceff0?}, {0x6375ed0?, 0xc002fd9e60?})
        /workspace/source/tidb/pkg/planner/core/planbuilder.go:859 +0x367
github.com/pingcap/tidb/pkg/planner.buildLogicalPlan({0x6368d60, 0xc002fceff0}, {0x63e1f60, 0xc003b5d400}, {0x6375ed0, 0xc002fd9e60}, 0xc002b5c000)
        /workspace/source/tidb/pkg/planner/optimize.go:576 +0x165
github.com/pingcap/tidb/pkg/planner.optimize({0x6368d60, 0xc002fceff0}, {0x63e1f60?, 0xc003b5d400}, {0x6375ed0?, 0xc002fd9e60?}, {0x63a5c68, 0xc002fcf020})
        /workspace/source/tidb/pkg/planner/optimize.go:494 +0x466
github.com/pingcap/tidb/pkg/planner.Optimize({0x6368d60, 0xc002fceff0}, {0x63e1f60, 0xc003b5d400}, {0x6375ed0, 0xc002fd9e60}, {0x63a5c68, 0xc002fcf020})
        /workspace/source/tidb/pkg/planner/optimize.go:352 +0x18c5
github.com/pingcap/tidb/pkg/executor.(*Compiler).Compile(0xc001ad2918, {0x6368d60?, 0xc002fceff0?}, {0x637d3e8?, 0xc002fd9e60})
        /workspace/source/tidb/pkg/executor/compiler.go:98 +0x44d
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt(0xc003b5d400, {0x6368d60?, 0xc002fceff0?}, {0x637d3e8?, 0xc002fd9e60?})
        /workspace/source/tidb/pkg/session/session.go:2221 +0x754
github.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt(0xc004602900, {0x6368d60, 0xc002fceff0}, {0x637d3e8?, 0xc002fd9e60})
        /workspace/source/tidb/pkg/server/driver_tidb.go:292 +0xa7
github.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt(0xc0030afba0, {0x6368d98, 0xc002fe3130}, {0x637d3e8, 0xc002fd9e60}, {0x0, 0x0, 0x0}, 0x1)
        /workspace/source/tidb/pkg/server/conn.go:2056 +0x189
github.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery(0xc0030afba0, {0x6368d98, 0xc002fe3130}, {0xc002f04e11, 0x2f})
        /workspace/source/tidb/pkg/server/conn.go:1823 +0x9ac
github.com/pingcap/tidb/pkg/server.(*clientConn).dispatch(0xc0030afba0, {0x6368d60?, 0xc002a13ef0?}, {0xc002f04e10, 0x30, 0x30})
        /workspace/source/tidb/pkg/server/conn.go:1310 +0xf8b
github.com/pingcap/tidb/pkg/server.(*clientConn).Run(0xc0030afba0, {0x6368d60, 0xc002a13ef0})
        /workspace/source/tidb/pkg/server/conn.go:1083 +0x53e
github.com/pingcap/tidb/pkg/server.(*Server).onConn(0xc00333a700?, 0xc0030afba0)
        /workspace/source/tidb/pkg/server/server.go:736 +0x89d
created by github.com/pingcap/tidb/pkg/server.(*Server).startNetworkListener in goroutine 16968
        /workspace/source/tidb/pkg/server/server.go:554 +0x78d
```

### 4. What is your TiDB version? (Required)

v7.5.2

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #54908

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that `timestampadd` function enters into infinity loop when the first parameter is 'month' and the second parameter is a negative number.
```

### CODE REVIEW

File: pkg/expression/builtin_time.go [hunk 1]
```diff
@@ -6233,11 +6233,28 @@ func addUnitToTime(unit string, t time.Time, v float64) (time.Time, bool, error)
...
-		for int(tb.Month())%12 != (int(t.Month())+int(v))%12 {
+		for int(tb.Month())%12 != expectMonth {
 			tb = tb.AddDate(0, 0, -1)
+
+			// TODO remove it in the future
+			// Prevent infinity loop when there are bugs
+			loopCount++
+			if loopCount > 100000 {
+				panic("Enter into infinity loop because of bugs")
+			}
```
Comment (XuHuaiyu) [inline pkg/expression/builtin_time.go:6257]: It's unacceptable to panic here

**Review by XuHuaiyu — COMMENTED** [review]
``` go
	case "MONTH":
		if !validAddMonth(v, t.Year(), int(t.Month())) {
			return tb, true, nil
		}
		year, month := t.Year(), int(t.Month())
		targetMonth := month + int(v)
		// Adjust the year and month based on the total months calculated
		targetYear := year + (targetMonth-1)/12
		targetMonth = (targetMonth-1)%12 + 1
	
		// Handle cases where month might become negative or zero
		if targetMonth <= 0 {
			targetYear -= 1
			targetMonth += 12
		}
	
		targetDay := t.Day()
		// Try to create the target date
		tb = time.Date(targetYear, time.Month(targetMonth), targetDay, t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), t.Location())
		if tb.Month() != time.Month(targetMonth) {
			// If the day overflows (like trying to get Feb 30), adjust to the last day of the target month
			tb = time.Date(targetYear, time.Month(targetMonth+1), 0, t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), t.Location())
		}
```

**Comment by XuHuaiyu** [comment]
release note needed

File: pkg/expression/builtin_time.go (hunk 1 above)
Comment (windtalker) [reply pkg/expression/builtin_time.go:6261]: Date_add has the exactly problem and this pr(https://github.com/pingcap/tidb/pull/8988/files) introduce a new function
`types.AddDate` to fix the difference between mysql and golang api, I think you can just reuse that function instead of writing a new one.

Comment (xzhangxian1008) [reply pkg/expression/builtin_time.go]: done

File: pkg/expression/builtin_time_test.go [hunk 2]
```diff
@@ -2592,6 +2592,40 @@ func TestTimestampAdd(t *testing.T) {
...
+		{"MONTH", -13, "2024-02-29", "2023-01-29 00:00:00"},
+		{"MONTH", -11, "2023-02-28", "2022-03-28 00:00:00"},
+		{"MONTH", -12, "2023-02-28", "2022-02-28 00:00:00"},
+		{"MONTH", -13, "2023-02-28", "2022-01-28 00:00:00"},
+		{"MONTH", -2, "2023-02-28", "2022-12-28 00:00:00"},
+		{"MONTH", -14, "2023-02-28", "2021-12-28 00:00:00"},
+		{"MONTH", -3, "2023-03-20", "2022-12-20 00:00:00"},
+		{"MONTH", -3, "2023-03-31", "2022-12-31 00:00:00"},
+		{"MONTH", -15, "2023-03-20", "2021-12-20 00:00:00"},
+		{"MONTH", -15, "2023-03-31", "2021-12-31 00:00:00"},
```
Comment (windtalker) [inline pkg/expression/builtin_time_test.go:2628]: Add tests to test from `2020-02-29` to `2021-02-28` and from `2020-02-29` to `2019-02-28`

Comment (windtalker) [reply pkg/expression/builtin_time_test.go:2628]: And add some invalid input test cases

Comment (xzhangxian1008) [reply pkg/expression/builtin_time_test.go:2628]: > And add some invalid input test cases

done

**Review by XuHuaiyu — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM
