### PR TITLE
stmtsummary: issue left in #32156

### LINKED ISSUE #32156: statement table `FIRST_SEEN`, `LAST_SEEN` field value is not sync with `time_zone` variable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Change `time_zone` to another value that is different from `system_time_zone`.

```
mysql> show variables like '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | UTC    |
| time_zone        | SYSTEM |
+------------------+--------+
2 rows in set (0.12 sec)

mysql> set global time_zone='+09:00';

// exit and reconnect

mysql> show variables like '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | UTC    |
| time_zone        | +09:00 |
+------------------+--------+
2 rows in set (0.12 sec)
```

Check current time:

```
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2022-02-08 15:16:07 |
+---------------------+
1 row in set (0.04 sec)
```

Run some SQLs:

```
mysql> select sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.10 sec)

mysql> select sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.04 sec)
```

Query statement table:

```
mysql> select FIRST_SEEN, LAST_SEEN, QUERY_SAMPLE_TEXT from INFORMATION_SCHEMA.CLUSTER_STATEMENTS_SUMMARY_HISTORY order by LAST_SEEN desc limit 1\G
*************************** 1. row ***************************
       FIRST_SEEN: 2022-02-08 06:16:21
        LAST_SEEN: 2022-02-08 06:16:33
QUERY_SAMPLE_TEXT: select `sleep` ( ? )
1 row in set (0.14 sec)
```

### 2. What did you expect to see? (Required)

The `FIRST_SEEN` value should be the time of +9:00 time zone instead of UTC time zone (aka `system_time_zone` in this case). same as `LAST_SEEN`, `SUMMARY_BEGIN_TIME` and `SUMMARY_END_TIME` field.

### 3. What did you see instead (Required)

These filed values are shown as the UTC time zone (aka `system_time_zone` in this case).

### 4. What is your TiDB version? (Required)

```
mysql> select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v5.3.0 |
+--------------------+
1 row in set (0.10 sec)
```

### PR DESCRIPTION
**Pull request by LemonHX**
### What problem does this PR solve?

Issue Number: close #32156

Problem Summary:

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

File: infoschema/cluster_tables_test.go [hunk 1]
```diff
@@ -415,20 +415,30 @@ func TestStmtSummaryHistoryTableWithUserTimezone(t *testing.T) {
...
 	require.NoError(t, err)
+	date1Begin, err := time.Parse("2006-01-02 15:04:05", r.Rows()[0][2].(string))
+	require.NoError(t, err)
+	date1End, err := time.Parse("2006-01-02 15:04:05", r.Rows()[0][3].(string))
+	require.NoError(t, err)
 
 	require.Less(t, date1First.Unix(), date8First.Unix())
 	require.Less(t, date1Last.Unix(), date8Last.Unix())
+	require.Less(t, date1Begin.Unix(), date8Begin.Unix())
+	require.Less(t, date1End.Unix(), date8End.Unix())
```
Comment (djshow832) [inline infoschema/cluster_tables_test.go:441]: It should be `date1Begin=date8Begin` and `date1End=date8End` because the statements summary refreshing is disabled.
Besides, I don't think this is related to the issue to be closed.

File: util/stmtsummary/reader.go [hunk 2]
```diff
@@ -313,11 +313,19 @@ var columnValueFactoryMap = map[string]columnValueFactory{
 	ClusterTableInstanceColumnNameStr: func(reader *stmtSummaryReader, ssElement *stmtSummaryByDigestElement, ssbd *stmtSummaryByDigest) interface{} {
 		return reader.instanceAddr
 	},
-	SummaryBeginTimeStr: func(_ *stmtSummaryReader, ssElement *stmtSummaryByDigestElement, _ *stmtSummaryByDigest) interface{} {
-		return types.NewTime(types.FromGoTime(time.Unix(ssElement.beginTime, 0)), mysql.TypeTimestamp, 0)
+	SummaryBeginTimeStr: func(reader *stmtSummaryReader, ssElement *stmtSummaryByDigestElement, _ *stmtSummaryByDigest) interface{} {
+		beginTime := time.Unix(ssElement.beginTime, 0)
+		if beginTime.Location() != reader.tz {
+			beginTime = beginTime.In(reader.tz)
+		}
```
Comment (djshow832) [inline util/stmtsummary/reader.go:320]: The test case doesn't prove that the beginTime and endTime follow the time zone.

File: infoschema/cluster_tables_test.go (hunk 1 above)
Comment (LemonHX) [reply infoschema/cluster_tables_test.go:441]: nope, that is the feature they want

**Review by djshow832 — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
