### PR TITLE
executor: enable index_merge used in transaction.

### LINKED ISSUE #29901: Cannot use IndexMerge in transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table if exists t1;
    create table t1(c1 int, c2 int, key(c1), key(c2));
    begin;
    explain select /*+ use_index_merge(t1) */ * from t1 where c1 < 10 or c2 < 10;
    insert into t1 values(1, 1);
    explain select /*+ use_index_merge(t1) */ * from t1 where c1 < 10 or c2 < 10;
    commit; 

### 2. What did you expect to see? (Required)
By using hint, we can use IndexMerge
### 3. What did you see instead (Required)

     MySQL [test]>     explain select /*+ use_index_merge(t1) */ * from t1 where c1 < 10 or c2 < 10;
    +-------------------------------+---------+-----------+------------------------+-------------------------------------------------+
    | id                            | estRows | task      | access object          | operator info                                   |
    +-------------------------------+---------+-----------+------------------------+-------------------------------------------------+
    | IndexMerge_8                  | 5542.21 | root      |                        |                                                 |
    | ├─IndexRangeScan_5(Build) | 3323.33 | cop[tikv] | table:t1, index:c1(c1) | range:[-inf,10), keep order:false, stats:pseudo |
    | ├─IndexRangeScan_6(Build) | 3323.33 | cop[tikv] | table:t1, index:c2(c2) | range:[-inf,10), keep order:false, stats:pseudo |
    | └─TableRowIDScan_7(Probe) | 5542.21 | cop[tikv] | table:t1               | keep order:false, stats:pseudo                  |
    +-------------------------------+---------+-----------+------------------------+-------------------------------------------------+
    4 rows in set (0.01 sec)
    
    MySQL [test]>     insert into t1 values(1, 1);
    Query OK, 1 row affected (0.00 sec)
    
    MySQL [test]>     explain select /*+ use_index_merge(t1) */ * from t1 where c1 < 10 or c2 < 10;
    +-----------------------------+----------+-----------+---------------+--------------------------------------------+
    | id                          | estRows  | task      | access object | operator info                              |
    +-----------------------------+----------+-----------+---------------+--------------------------------------------+
    | Projection_5                | 5542.21  | root      |               | test.t1.c1, test.t1.c2                     |
    | └─UnionScan_6           | 5542.21  | root      |               | or(lt(test.t1.c1, 10), lt(test.t1.c2, 10)) |
    |   └─TableReader_9       | 5542.21  | root      |               | data:Selection_8                           |
    |     └─Selection_8       | 5542.21  | cop[tikv] |               | or(lt(test.t1.c1, 10), lt(test.t1.c2, 10)) |
    |       └─TableFullScan_7 | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo             |
    +-----------------------------+----------+-----------+---------------+--------------------------------------------+
    5 rows in set, 1 warning (0.00 sec)
### 4. What is your TiDB version? (Required)
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()
                               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0-alpha-140-g68b5e0658c
Edition: Community
Git Commit Hash: 68b5e0658c103e524b9879f6ed62fbd8afa8f417
Git Branch: index_merge
UTC Build Time: 2021-11-18 07:12:21
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #29901

Problem Summary: We need UnionScan to read dirty buffer when we got write operation in transaction. But there is no implementation for IndexMergeReader to scan buffer. So we disable the usage of IndexMerge in this situation. So we need to implement `memIndexMergeReader` just like `memIndexLookupReader`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
executor: enable index_merge used in transaction
```

### CODE REVIEW

File: executor/mem_reader.go [hunk 1]
```diff
@@ -525,3 +545,188 @@ func (m *memIndexLookUpReader) getMemRows() ([][]types.Datum, error) {
...
+				table:           indexMergeReader.table.Meta(),
+				kvRanges:        nil,
+				desc:            indexMergeReader.descs[i],
+				retFieldTypes:   retTypes(us),
+				outputOffset:    outputOffset,
+				belowHandleCols: us.belowHandleCols,
+			})
+			tableReaders = append(tableReaders, nil)
+		}
+	}
```
Comment (winoros) [inline executor/mem_reader.go:606]: Could we extract an interface to merge this if branch?

File: cmd/explaintest/r/index_merge.result [hunk 2]
```diff
@@ -0,0 +1,116 @@
+drop table if exists t1;
```
Comment (winoros) [inline cmd/explaintest/r/index_merge.result:1]: Seems that we would add the same tests if we want to add some tests in the executor package.
So we don't add that this time?
Or add these to the executor package so the tests can be run parellelly.

File: executor/builder.go [hunk 3]
```diff
@@ -1088,6 +1088,14 @@ func (b *executorBuilder) buildUnionScanFromReader(reader Executor, v *plannerco
 		us.columns = x.columns
 		us.table = x.table
 		us.virtualColumnIndex = buildVirtualColumnIndex(us.Schema(), us.columns)
+	case *IndexMergeReaderExecutor:
+		// IndexMergeReader doesn't care order.
```
Comment (winoros) [inline executor/builder.go:1092]: But, the CNF form may care order. We need to take it carefully, not to forget add it here(

File: executor/mem_reader.go [hunk 4]
```diff
@@ -313,6 +316,23 @@ func (m *memTableReader) getRowData(handle kv.Handle, value []byte) ([][]byte, e
 	return values, nil
 }
 
+// Used when memIndexMergeReader.partialPlans[i] is TableScan.
```
Comment (winoros) [inline executor/mem_reader.go:319]:
```suggestion
// getMemRowsHandle is called when memIndexMergeReader.partialPlans[i] is TableScan.
```

File: executor/builder.go (hunk 3 above)
Comment (guo-shaoge) [reply executor/builder.go:1092]: Sorry I don't understand why we care CNF. If the required prop needs to be [ordered](https://github.com/pingcap/tidb/blob/b1352ded030c33065e711440939b97767a518d76/planner/core/find_best_task.go#L961), we will not generate IndexMergeReader?

File: executor/mem_reader.go (hunk 1 above)
Comment (guo-shaoge) [reply executor/mem_reader.go:606]: I'm not sure if you mean the following:

    for i := 0; i < indexCount; i++ {
        // if partialPlans[i] is IndexScan, this is an invalid tableReader.
        tableReaders = append(tableReaders, &memTableReader{...});
        // if partialPlans[i] is not IndexScan, this is a invalid indexReader.
        indexReaders = append(indexReaders, &memIndexReader{...}); 
    }

However, this may lead to the need to construct additional tableReader or indexReader?

File: cmd/explaintest/r/index_merge.result (hunk 2 above)
Comment (guo-shaoge) [reply cmd/explaintest/r/index_merge.result:1]: Of course.

File: executor/builder.go (hunk 3 above)
Comment (winoros) [reply executor/builder.go:1092]: For the DNF case, we cannot maintain the order since it's hard to maintain the order for `a = 1 or b = 1 order by a`.
But for CNF case `a > 1 and b > 1 order by a`. Is possible that we choose the a as a primary path to keep the order.

File: executor/mem_reader.go (hunk 1 above)
Comment (winoros) [reply executor/mem_reader.go:603]: Oh, i mean the one like this
```
for i := 0; i < partialPathCount; i ++ {
	partialReaders = append(partialReaders, index/table reader)
}
```

File: executor/builder.go (hunk 3 above)
Comment (guo-shaoge) [reply executor/builder.go:1092]: Really sorry for the late reply. IMHO in the CNF case, a sort operator should be added instead of choosing `a` as the primary key for sorting?

Because according to the [current implementation](https://github.com/pingcap/tidb/blob/b1352ded030c33065e711440939b97767a518d76/planner/core/find_best_task.go#L961), if the `prop` has sorting requirements, `convertToIndexMergeScan` will directly return invalidTask. Then the optimizer should clear the prop then choosing the index merge again, and finally a sort operator will be added? Is that the process?

File: executor/mem_reader.go (hunk 1 above)
Comment (guo-shaoge) [reply executor/mem_reader.go]: I extract an interface `memReader`, but the if branch still exists. But we only need one slice to store memTableReader/memIndexReader.

**Review by winoros — APPROVED** [review]

File: executor/index_merge_reader_test.go [hunk 5]
```diff
@@ -170,3 +170,75 @@ func (s *testSuite1) TestPartitionTableRandomIndexMerge(c *C) {
 		tk.MustQuery("select /*+ USE_INDEX_MERGE(tpk, a, b) */ * from tpk where " + cond).Sort().Check(result)
 	}
 }
+
+func (s *testSuite1) TestIndexMergeInTransaction(c *C) {
```
Comment (cfzjywxk) [inline executor/index_merge_reader_test.go:174]: We could add some `for update` read and `set transaction isolation level read committed;` test cases, the result shoue be the same if there's no concurrency.

File: executor/mem_reader.go [hunk 6]
```diff
@@ -525,3 +556,185 @@ func (m *memIndexLookUpReader) getMemRows() ([][]types.Datum, error) {
...
+		buffer: allocBuf{
+			handleBytes: make([]byte, 0, 16),
+			rd:          rd,
+		},
+	}
+
+	return memTblReader.getMemRows()
+}
+
+func getColIDAndPkColIDs(table table.Table, columns []*model.ColumnInfo) (map[int64]int, []int64, *rowcodec.BytesDecoder) {
```
Comment (XuHuaiyu) [inline executor/mem_reader.go:683]: We can also use this function in `memIndexLookUpReader.getMemRows` to avoid the duplicate codes

File: executor/mem_reader.go [hunk 7]
```diff
@@ -525,3 +556,185 @@ func (m *memIndexLookUpReader) getMemRows() ([][]types.Datum, error) {
...
+	pkColIDs := tables.TryGetCommonPkColumnIds(tblInfo)
+	if len(pkColIDs) == 0 {
+		pkColIDs = []int64{-1}
+	}
+	rd := rowcodec.NewByteDecoder(colInfos, pkColIDs, nil, nil)
+	return colIDs, pkColIDs, rd
+}
+
+// Union all handles of different Indexes.
+func unionHandles(kvRanges [][]kv.KeyRange, memReaders []memReader) (finalHandles []kv.Handle, err error) {
```
Comment (XuHuaiyu) [inline executor/mem_reader.go:708]: define this function as the member function of `memIndexMergeReader` since this function will only be invoked by it.

Comment (guo-shaoge) [reply executor/mem_reader.go]: done

File: executor/mem_reader.go (hunk 6 above)
Comment (guo-shaoge) [reply executor/mem_reader.go]: done

File: executor/index_merge_reader_test.go (hunk 5 above)
Comment (guo-shaoge) [reply executor/index_merge_reader_test.go:176]: done

File: executor/mem_reader.go [hunk 8]
```diff
@@ -520,8 +656,66 @@ func (m *memIndexLookUpReader) getMemRows() ([][]types.Datum, error) {
...
 			rd:          rd,
 		},
-		cacheTable: m.cacheTable,
 	}
 
 	return memTblReader.getMemRows()
 }
+
+// Union all handles of different Indexes.
+func (m *memIndexMergeReader) unionHandles(kvRanges [][]kv.KeyRange, memReaders []memReader) (finalHandles []kv.Handle, err error) {
```
Comment (XuHuaiyu) [inline executor/mem_reader.go:665]: the input argument `memReader` is useless

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]
