### PR TITLE
ddl: refine the criterion for modify column

### LINKED ISSUE #10509: daily regression tests (`ddl-basic/modify_column_issue_904.test`) failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Execute tiflash_regression_test_daily like 
https://ci.pingcap.net/blue/organizations/jenkins/tiflash_regression_test_daily/detail/tiflash_regression_test_daily/5318/pipeline

### 3. What did you see instead (Required)

```
[2025-10-28T18:18:15.079Z] /home/jenkins/agent/git/tiflash/integrated/ops/ti.sh.cmds/ci/fullstack_tests/ci/ddl-basic/modify_column_ch.test: OK
[2025-10-28T18:18:25.033Z]   File: /home/jenkins/agent/git/tiflash/integrated/ops/ti.sh.cmds/ci/fullstack_tests/ci/ddl-basic/modify_column_issue_904.test
[2025-10-28T18:18:25.033Z]   Error line: 31
[2025-10-28T18:18:25.033Z]   Error: tiflash select c1, c2 from test.t
[2025-10-28T18:18:25.033Z]   Result:
[2025-10-28T18:18:25.033Z]     ERROR 1105 (HY000) at line 1: other error for mpp stream: Code: 48, e.displayText() = DB::Exception: Reading mismatch data type pack. Cast from Nullable(Int32) to Nullable(Int8) is NOT supported, column_id=2, e.what() = DB::Exception,
[2025-10-28T18:18:25.033Z]   Expected:
[2025-10-28T18:18:25.033Z]     +-------------+------+
[2025-10-28T18:18:25.033Z]     | c1          | c2   |
[2025-10-28T18:18:25.033Z]     +-------------+------+
[2025-10-28T18:18:25.033Z]     | Hello world |    1 |
[2025-10-28T18:18:25.033Z]     | abc         |    2 |
[2025-10-28T18:18:25.033Z]     | xyz         |   10 |
[2025-10-28T18:18:25.033Z]     +-------------+------+
```

```

[2025/11/05 10:49:27.654 +08:00] [WARN] [SegmentReader.cpp:92] ["ErrMsg: Reading mismatch data type pack. Cast from Nullable(Int32) to Nullable(Int8) is NOT supported, column_id=2 StackTrace 
  0x560ef467b403    DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, long const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, long const&) [tiflash+130540547]
                    dbms/src/Common/StackTrace.cpp:25
  0x560ef467b131    DB::DM::convertColumnByColumnDefineIfNeed(std::__1::shared_ptr<DB::IDataType const> const&, COWPtr<DB::IColumn>::immutable_ptr<DB::IColumn>&&, DB::DM::ColumnDefine const&) [tiflash+130539825]
                    dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp:489
  0x560ef4673ed6    DB::DM::ColumnFileInMemory::fillColumns(std::__1::vector<DB::DM::ColumnDefine, std::__1::allocator<DB::DM::ColumnDefine>> const&, unsigned long, std::__1::vector<COWPtr<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COWPtr<DB::IColumn>::immutable_ptr<DB::IColumn>>>&) const [tiflash+130510550]
                    dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp:47
  0x560ef46747d8    DB::DM::ColumnFileInMemoryReader::readNextBlock() [tiflash+130512856]
                    dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp:145
  0x560ef4667c15    DB::DM::ColumnFileSetInputStream::read(DB::PODArray<unsigned char, 4096ul, Allocator<false>, 15ul, 16ul>*&, bool) [tiflash+130460693]
                    dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.cpp:52
  0x560ef4668034    DB::DM::ColumnFileSetInputStream::read() [tiflash+130461748]
                    dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.h:53
  0x560eeebf479c    DB::DM::ConcatSkippableBlockInputStream<false>::read() (.llvm.merged) [tiflash+35616668]
                    dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp:130
  0x560ef4653e7e    DB::DM::BitmapFilterBlockInputStream::read() [tiflash+130379390]
                    dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp:35
  0x560ef4961715    DB::AddExtraTableIDColumnInputStream::read() [tiflash+133580565]
                    dbms/src/DataStreams/AddExtraTableIDColumnInputStream.cpp:32
  0x560ef4635381    DB::DM::SegmentReadTaskPool::readOneBlock(std::__1::shared_ptr<DB::IBlockInputStream>&, std::__1::shared_ptr<DB::DM::SegmentReadTask> const&) [tiflash+130253697]
                    dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp:297
  0x560ef48a264d    DB::DM::MergedTask::readOneBlock() [tiflash+132798029]
                    dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp:91
  0x560ef48a9b70    DB::DM::SegmentReader::run() [tiflash+132828016]
                    dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp:32
  0x560ef48ab652    void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (DB::DM::SegmentReader::*)(), DB::DM::SegmentReader*>>(void*) [tiflash+132834898]
                    /usr/local/bin/../include/c++/v1/__type_traits/invoke.h:308
  0x7f4766e8a19a    start_thread [libc.so.6+565658]
  0x7f4766f0f210    __clone3 [libc.so.6+1110544]"] [source="MPP<gather_id:1, query_ts:1762310963745564708, local_query_id:5, server_id:957, start_ts:461979245269745665,task_id:1> table_id=114 seg_id=1"] [thread_id=75]
```

### 4. What is your TiFlash version? (Required)

61ed7fdc5815baca08dfa614f2f45328d6ebb687

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tidb/issues/63366, close https://github.com/pingcap/tiflash/issues/10509

Problem Summary:

### What changed and how does it work?

Disable lossy modify column optimization in the following cases:
- table contains **TiFlash replica**.  See https://github.com/pingcap/tiflash/issues/10509 for the reason.
- signed/unsigned changes, or string with different collations. Since **stats and DDL have different criteria for "lossy type change"**.
  - For example, "utf8mb4_bin" and "utf8mb4_general_ci" belong to same charset, so the table data can be reused between such collations. But since stats store collate key instead of original string. Such changes should be lossy.

~~Besides, this PR do some minor refactor to the check of modify column type, to support more changes with reorg, ref https://github.com/pingcap/tidb/commit/8f380b5b704ccd2b43dfa85b564d5a248b0b184b)~~ To reduce the risk, I revert this part, maybe we can refactor it later.

### Check List

Tests 

- [x] Unit test **modify existing tests**
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/modify_column.go [hunk 1]
```diff
@@ -129,18 +129,20 @@ func getModifyColumnType(
...
 
-	failpoint.Inject("disableLossyDDLOptimization", func(val failpoint.Value) {
-		if v, ok := val.(bool); ok && v {
-			failpoint.Return(ModifyTypeReorg)
-		}
-	})
+	// FIXME(joechenrh): handle partition and TiFlash replica case
+	if tblInfo.Partition != nil || tblInfo.TiFlashReplica != nil && tblInfo.TiFlashReplica.Count > 0 {
+		return ModifyTypeReorg
+	}
```
Comment (JaySon-Huang) [inline pkg/ddl/modify_column.go:103]: This part lgtm

**Review by fzzf678 — APPROVED** [review]

File: pkg/ddl/modify_column.go [hunk 2]
```diff
@@ -1102,7 +1117,7 @@ func (w *worker) doModifyColumnTypeWithData(
 		default:
 			errMsg := fmt.Sprintf("unexpected column state %s in modify column job", oldCol.State)
 			intest.Assert(false, errMsg)
-			return ver, errors.Errorf(errMsg)
+			return ver, errors.Errorf("%s", errMsg)
```
Comment (joechenrh) [inline pkg/ddl/modify_column.go:1120]: It's for go version upgrade

**Review by wjhuang2016 — APPROVED** [review]

**Comment by joechenrh** [comment]
Remove needs-cherry-pick-release-8.5 as we will manually cherry-pick this.

**Comment by JaySon-Huang** [comment]
> Remove needs-cherry-pick-release-8.5 as we will manually cherry-pick this.

Note: Done in this cherry-pick PR: https://github.com/pingcap/tidb/pull/65005
