### PR TITLE
expression: fix warning/error info of `group_concat()` 

### LINKED ISSUE #7797: group_concat error/warning question
### 1. What did you do?
If possible, provide a recipe for reproducing the error.

```
CREATE TABLE `t1` (
  `p` varchar(16000) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE `t2` (
  `e` varchar(100) DEFAULT NULL,
  `id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

insert into t2 values ('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1),('加入购物车', 1);

set group_concat_max_len=7;
```

then execute `select` and `insert select` 

#### 1. select

```
mysql> select group_concat(e) from t2 group by id;
+-----------------+
| group_concat(e) |
+-----------------+
| 加入            |
+-----------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------------------------+
| Level   | Code | Message                         |
+---------+------+---------------------------------+
| Warning | 1260 | Row 1 was cut by GROUP_CONCAT() |
+---------+------+---------------------------------+
1 row in set (0.00 sec)

```

#### 2. insert select

```
mysql>  insert into t1 select group_concat(e) from t2 group by id;
ERROR 1260 (HY000): Row 1 was cut by GROUP_CONCAT()
```

#### 1. select result

```
mysql> select group_concat(e) from t2 group by id;
+-----------------+
| group_concat(e) |
+-----------------+
| 加�              |
+-----------------+
1 row in set, 2 warnings (0.01 sec)

mysql> show warnings;
+---------+------+---------------------------------+
| Level   | Code | Message                         |
+---------+------+---------------------------------+
| Warning | 1105 | Row %d was cut by GROUPCONCAT() |
| Warning | 1105 | Row %d was cut by GROUPCONCAT() |
+---------+------+---------------------------------+
2 rows in set (0.00 sec)
```

question: return more than 1 warnings; error code is wrong.

#### 2. insert select

```
mysql> insert into t1 select group_concat(e) from t2 group by id;
ERROR 1366 (HY000): incorrect utf8 value e58aa0e5(加�) for column p

```

question: error type is wrong.

### 4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
2.1.0.rc2
```

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

fixes #7797

### What is changed and how it works?

- fixes group_truncat error code, also arrange message content(we can't got row num after parallel)
- fixes `baseGroupConcat4String#truncated` doesn't work in parallel execution problem
- handle error returned by `truncatePartialResultIfNeed`

### Check List 

Tests 

 - Unit test

Code changes

 - impl changes

Side effects

 - no

Related changes

 - Need to cherry-pick to the 2.0 release branch
 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/7799)

### CODE REVIEW

File: mysql/errname.go [hunk 1]
```diff
@@ -275,7 +275,7 @@ var MySQLErrName = map[uint16]string{
 	ErrZlibZMem:                                 "ZLIB: Not enough memory",
 	ErrZlibZBuf:                                 "ZLIB: Not enough room in the output buffer (probably, length of uncompressed data was corrupted)",
 	ErrZlibZData:                                "ZLIB: Input data corrupted",
-	ErrCutValueGroupConcat:                      "Row %d was cut by GROUPCONCAT()",
+	ErrCutValueGroupConcat:                      "Some row was cut by GROUPCONCAT()",
```
Comment (winoros) [inline mysql/errname.go]: `Some rows were`?

File: mysql/errname.go [hunk 2]
```diff
@@ -275,7 +275,7 @@ var MySQLErrName = map[uint16]string{
 	ErrZlibZMem:                                 "ZLIB: Not enough memory",
 	ErrZlibZBuf:                                 "ZLIB: Not enough room in the output buffer (probably, length of uncompressed data was corrupted)",
 	ErrZlibZData:                                "ZLIB: Input data corrupted",
-	ErrCutValueGroupConcat:                      "Row %d was cut by GROUPCONCAT()",
+	ErrCutValueGroupConcat:                      "Some rows was cut by GROUPCONCAT()",
```
Comment (zimulala) [inline mysql/errname.go]: Why change this?
```
mysql> show warnings;
+---------+------+---------------------------------+
| Level   | Code | Message                         |
+---------+------+---------------------------------+
| Warning | 1260 | Row 2 was cut by GROUP_CONCAT() |
+---------+------+---------------------------------+
1 row in set (0.00 sec)
```
If there is no row number, or we can use `GenWithStackByArgs`.

Comment (lysu) [reply mysql/errname.go]: we are can not got accurate row number, so it seems have no good value to set `GenWithStackByArgs` parameter ...and got stranger message like this~  :joy_cat: 

```
mysql> show warnings;
+---------+------+---------------------------------+
| Level   | Code | Message                         |
+---------+------+---------------------------------+
| Warning | 1105 | Row %d was cut by GROUPCONCAT() |
| Warning | 1105 | Row %d was cut by GROUPCONCAT() |
+---------+------+---------------------------------+
```
so I think maybe change a new message...

File: executor/aggfuncs/func_group_concat.go [hunk 3]
```diff
@@ -52,10 +53,12 @@ func (e *baseGroupConcat4String) truncatePartialResultIfNeed(sctx sessionctx.Con
 			i = int(e.maxLen)
 		}
 		buffer.Truncate(i)
-		if !e.truncated {
+		if atomic.CompareAndSwapInt32(e.truncated, 0, 1) {
+			if sctx.GetSessionVars().SQLMode.HasStrictMode() && sctx.GetSessionVars().StmtCtx.InInsertStmt {
+				return expression.ErrCutValueGroupConcat
```
Comment (coocood) [inline executor/aggfuncs/func_group_concat.go]: Need to add stack?

File: executor/aggfuncs/func_group_concat.go [hunk 4]
```diff
@@ -32,7 +33,7 @@ type baseGroupConcat4String struct {
 	// According to MySQL, a 'group_concat' function generates exactly one 'truncated' warning during its life time, no matter
 	// how many group actually truncated. 'truncated' acts as a sentinel to indicate whether this warning has already been
 	// generated.
-	truncated bool
+	truncated *int32
```
Comment (zz-jason) [inline executor/aggfuncs/func_group_concat.go]: can we remove this field, use `sctx.GetSessionVars().StmtCtx.GroupConcatTruncated` instead.

Comment (lysu) [reply executor/aggfuncs/func_group_concat.go]: No, I found stmtCtx level is bug... fix one stmt with two `group_conat()` functions need got 2 warnings, so `StmtCtx.GroupConcatTruncated` has be removed.

and @spongedu's https://github.com/pingcap/tidb/commit/e3ba021f5a25c3b4ba63fe91f904da270f7fc22a seems not all right..

for mysql, 


```
mysql> select version();
+-----------------------------+
| version()                   |
+-----------------------------+
| 5.7.23-0ubuntu0.18.04.1-log |
+-----------------------------+
1 row in set (0.00 sec)

mysql> select * from tt;
+------+-------+-------+
| id   | a     | b     |
+------+-------+-------+
|    1 | hello | hello |
|    1 | world | world |
|    2 | hello | hello |
|    2 | world | world |
|    3 | hello | hello |
|    3 | world | world |
|    4 | hello | hello |
|    4 | world | world |
|    3 | hello | hello |
|    3 | world | world |
|    4 | hello | hello |
|    4 | world | world |
+------+-------+-------+
12 rows in set (0.01 sec)

mysql> set @@group_concat_max_len=7;                                                                                                                                                               Query OK, 0 rows affected (0.00 sec)

mysql> show warnings;
+---------+------+---------------------------------+
| Level   | Code | Message                         |
+---------+------+---------------------------------+
| Warning | 1260 | Row 2 was cut by GROUP_CONCAT() |
| Warning | 1260 | Row 2 was cut by GROUP_CONCAT() |
| Warning | 1260 | Row 4 was cut by GROUP_CONCAT() |
| Warning | 1260 | Row 4 was cut by GROUP_CONCAT() |
| Warning | 1260 | Row 6 was cut by GROUP_CONCAT() |
| Warning | 1260 | Row 6 was cut by GROUP_CONCAT() |
| Warning | 1260 | Row 8 was cut by GROUP_CONCAT() |
| Warning | 1260 | Row 8 was cut by GROUP_CONCAT() |
+---------+------+---------------------------------+
8 rows in set (0.00 sec)
```

it will issue one warning message for each group and each function call,  so 4 x 2  => 8

but I thinks it's not useful. :rofl:  so keep @spongedu's way for each function call only issue one warning message.

**Comment by lysu** [comment]
@zz-jason PTAL if free thx~

File: executor/aggfuncs/func_group_concat.go (hunk 4 above)
Comment (zz-jason) [reply executor/aggfuncs/func_group_concat.go]: what is the query you issued?

Comment (lysu) [reply executor/aggfuncs/func_group_concat.go]: sorry, miss query...

```
CREATE TABLE `tt` (
  `id` int(11) DEFAULT NULL,
  `a` varchar(100) DEFAULT NULL,
  `b` varchar(100) DEFAULT NULL
) ENGINE=InnoDB;

insert into tt values (1, 'hello', 'hello'), (2, 'world', 'world'), (3, 'hello', 'hello'), (4, 'world', 'world'), (3, 'hello', 'hello'), (3, 'world', 'world'), (4, 'hello', 'hello'), (4, 'world', 'world'), (3, 'hello', 'hello'), (3, 'world', 'world'), (4, 'hello', 'hello'), (4, 'world', 'world');

set @@group_concat_max_len=7; 

select group_concat(a), group_concat(b) from tt group by id;
```

File: mysql/errname.go (hunk 2 above)
Comment (zz-jason) [reply mysql/errname.go]: s/was/were/

File: executor/aggfuncs/func_group_concat.go (hunk 4 above)
Comment (zz-jason) [reply executor/aggfuncs/func_group_concat.go]: It seems that the main code change of this PR is the error/warning message? We still return only one error message per function, ignore the number of rows?

Comment (zz-jason) [reply executor/aggfuncs/func_group_concat.go]: As for the "parallel execution problem" described in the PR description, do you mean the data race on the `truncated` field?

Comment (lysu) [reply executor/aggfuncs/func_group_concat.go]: The main purpose of this pr is make group_concate truncate alway return error in `insert  select`.

before this pr `insert select` with truncated will got 

```
mysql> insert into t1 select group_concat(e) from t2 group by id;
ERROR 1366 (HY000): incorrect utf8 value e58aa0e5(加�) for column p
```
if utf8 value after truncate doesn't incorrect will sliently insert wrong value.

warning count question is meet during test..not main purpose :laughing:

Comment (lysu) [reply executor/aggfuncs/func_group_concat.go]: No, there are no race condition, 

but hash agg parallel execution will got `x2` warnings..one in partial worker and another in final worker, because each worker alloc seperate  baseGroupConcat4String and `truncated` memory, so duplicate mechanism doesn't work

File: executor/aggfuncs/func_group_concat.go [hunk 5]
```diff
@@ -52,10 +53,12 @@ func (e *baseGroupConcat4String) truncatePartialResultIfNeed(sctx sessionctx.Con
 			i = int(e.maxLen)
 		}
 		buffer.Truncate(i)
-		if !e.truncated {
-			sctx.GetSessionVars().StmtCtx.AppendWarning(expression.ErrCutValueGroupConcat)
+		if atomic.CompareAndSwapInt32(e.truncated, 0, 1) {
+			if sctx.GetSessionVars().SQLMode.HasStrictMode() && sctx.GetSessionVars().StmtCtx.InInsertStmt {
```
Comment (jackysp) [inline executor/aggfuncs/func_group_concat.go]: Why not use `TruncateAsWarning` here?

**Comment by XuHuaiyu** [comment]
@lysu 
This commit needs to be cherry-picked to release-2.1.
Another cherry-pick needs this. 😢

**Comment by clanstyles** [comment]
We've been running into this "incorrect utf8 value" while inserting data. Is there a fix for this?

**Comment by lysu** [comment]
Hi, @clanstyles this just fix "incorrect utf8 value" cause by `group_concat` over max count but not all "incorrect utf8 value", do you using `group_concat` and concat too many data? if not maybe there are another question.
 
please file a github issue to describe the detail for reproduce error, we will address it if it cause by another question, thx~
