### PR TITLE
planner: add HasTiflash to avoid generating unnecessary mpp task | tidb-test=pr/2660 

### LINKED ISSUE #65335: wrongly generate the intermediate results for MPP in the optimizor
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

If ```prop.TaskTp``` is not `MppTaskType` and `checkCanPushDownToMPP` is true, Optimizor will create the MPP type again. It is unnecessary.

https://github.com/pingcap/tidb/blob/79ec3b66cf709e182f47e4d71ce6b7d3f9e03f9d/pkg/planner/core/operator/physicalop/physical_hash_agg.go#L52-L108

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65335

Problem Summary:
- `checkCanPushDownToMPP` was evaluated twice in hash aggregation planning and could run on non-TiFlash paths.
- After introducing `HasTiflash`, some physical plan partition metadata still relied on pruned `OutputNames`, which could break partition pruning expression rewrite in TiFlash partition-table paths (for example `Unknown column 'a' in 'expression'`).
- `tidb_allow_mpp=OFF` could still enter MPP-related planning branches in some TiFlash paths.

### What changed and how does it work?
- Introduce and reuse `rule.ReconstructTableColNames(ds)` for partition pruning column-name reconstruction from `ds.TblCols`.
- Add `buildPhysPlanPartInfo(ds)` and centralize `PhysPlanPartInfo` production in planner physical-task construction.
  - Applied in `find_best_task.go` and `exhaust_physical_plans.go`.
- Gate MPP-specific paths with explicit MPP capability:
  - `hasTiflashForMPP = hasTiflash && IsMPPAllowed()`.
- Preserve produced partition metadata when converting MPP task to root task:
  - reuse and clone `PhysPlanPartInfo` in `ConvertToRootTaskImpl`.
- Keep unistore MPP table-scan stop path idempotent (`sync.Once`) to avoid repeated close/wait in teardown paths.
- Refresh `enforcempp` test expectations.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Executed:
- `go test -run TestTiflashPartitionTableScan --tags=intest ./pkg/executor/test/tiflashtest`
- `go test -run TestVirtualExprPushDown --tags=intest ./pkg/planner/core`
- `go test -run TestMPPSkewedGroupDistinctRewrite --tags=intest ./pkg/planner/core/casetest/enforcempp`
- `go test -run TestEnforceMPP --tags=intest ./pkg/planner/core/casetest/enforcempp`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix incorrect TiFlash partition pruning metadata propagation after `HasTiflash` planner changes, and avoid entering MPP planning paths when MPP is disabled.
```

## Summary by CodeRabbit

* **Refactor**
  * Restructured query plan property representation to improve TiFlash and distributed execution tracking, enabling more accurate property propagation across complex queries.

* **Tests**
  * Updated test expectations across planner and executor test suites to reflect internal identifier renumbering; plan structure and semantics remain unchanged.

### CODE REVIEW

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -4361,6 +4361,8 @@ func (b *PlanBuilder) buildDataSource(ctx context.Context, tn *ast.TableName, as
 		return nil, err
 	}
 	tableInfo := tbl.Meta()
+	sessionVars.StmtCtx.HasTiflash = sessionVars.StmtCtx.HasTiflash || b.ctx.GetSessionVars().IsMPPAllowed() &&
```
Comment (winoros) [inline pkg/planner/core/logical_plan_builder.go]: I think we don't need to add this together in this pr.
Current physical optimization needs to generate the mpp task type first because we don't know whether its children can be converted to mpp plan.
If we want to do the pruning completely, we'll need to change the physical opt framework itself.

Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: But under the current circumstances, most users actually won't have TiFlash replicas. So when building the data source, it can quickly determine whether it contains TiFlash based on the table metadata.

File: pkg/planner/core/operator/logicalop/logical_aggregation.go [hunk 2]
```diff
@@ -265,25 +265,36 @@ func (la *LogicalAggregation) ExtractColGroups(_ [][]*expression.Column) [][]*ex
...
 	childProps := childrenProperties[0]
+	la.hasTiflash = childProps.HasTiflash
 	// If there's no group-by item, the stream aggregation could have no order property. So we can add an empty property
 	// when its group-by item is empty.
 	if len(la.GroupByItems) == 0 {
 		la.PossibleProperties = [][]*expression.Column{nil}
-		return nil
+		return &base.PossiblePropertiesInfo{
+			HasTiflash: la.hasTiflash,
+		}
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_aggregation.go]: We can change the `PossibleProperties`'s type to the new `PossiblePropertiesInfo`.
This can make the code clearer.

**Comment by terry1purcell** [comment]
@pantheon-bot please review

File: pkg/planner/core/operator/logicalop/logical_union_scan.go [hunk 3]
```diff
@@ -122,7 +122,7 @@ func (p *LogicalUnionScan) PruneColumns(parentUsedCols []*expression.Column) (ba
 // ExtractColGroups inherits BaseLogicalPlan.LogicalPlan.<12th> implementation.
 
 // PreparePossibleProperties inherits BaseLogicalPlan.LogicalPlan.<13th> implementation.
-func (p *LogicalUnionScan) PreparePossibleProperties(schema *expression.Schema, childrenProperties ...[][]*expression.Column) [][]*expression.Column {
+func (p *LogicalUnionScan) PreparePossibleProperties(schema *expression.Schema, childrenProperties ...*base.PossiblePropertiesInfo) *base.PossiblePropertiesInfo {
 	// ref exhaustPhysicalPlans4LogicalUnionScan: it will push down the sort prop directly.
```
[the remark this answers is not in the document]
Comment (fixdb) [reply pkg/planner/core/operator/logicalop/logical_union_scan.go:126]: +1

File: pkg/planner/core/base/plan_base.go [hunk 4]
```diff
@@ -366,3 +372,63 @@ type PhysicalJoin interface {
...
+			for _, col := range one {
+				col.Hash64(h)
+			}
+		}
+	}
+	h.HashBool(info.HasTiflash)
+}
+
+// Equals implements the HashEquals interface.
+func (info *PossiblePropertiesInfo) Equals(other any) bool {
```
Comment (AilinKid) [inline pkg/planner/core/base/plan_base.go:412]: logical prop should no matters in op finger print, we can remove the suffix tag

File: pkg/planner/core/base/plan_base.go [hunk 5]
```diff
@@ -271,6 +271,12 @@ type LogicalPlan interface {
 
 	// GetJoinChildStatsAndSchema gets the stats and schema of both children.
 	GetJoinChildStatsAndSchema() (stats0, stats1 *property.StatsInfo, schema0, schema1 *expression.Schema)
+
+	// SetHasTiFlash sets whether the plan has tiflash replica.
+	SetHasTiFlash(hasTiFlash bool)
```
Comment (AilinKid) [inline pkg/planner/core/base/plan_base.go]: don't amplify the logical interface, logical interface should keep clean and small

File: pkg/planner/core/base/plan_base.go [hunk 6]
```diff
@@ -366,3 +372,63 @@ type PhysicalJoin interface {
 	GetInnerChildIdx() int
 	GetJoinType() JoinType
 }
+
+// PossiblePropertiesInfo is used to store all possible order properties.
+type PossiblePropertiesInfo struct {
```
Comment (AilinKid) [inline pkg/planner/core/base/plan_base.go:383]: this is interesting

File: pkg/planner/core/casetest/join/join_test.go [hunk 7]
```diff
@@ -48,9 +48,7 @@ func TestSemiJoinOrder(t *testing.T) {
 			"  └─TableReader(Probe) 9990.00 root  data:Selection",
 			"    └─Selection 9990.00 cop[tikv]  not(isnull(test.t2.col0))",
 			"      └─TableFullScan 10000.00 cop[tikv] table:t2 keep order:false, stats:pseudo"))
-		tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1815 Some HASH_JOIN_BUILD and HASH_JOIN_PROBE hints cannot be utilized for MPP joins, please check the hints",
-			"Warning 1815 Some HASH_JOIN_BUILD and HASH_JOIN_PROBE hints cannot be utilized for MPP joins, please check the hints",
-			"Warning 1815 Some HASH_JOIN_BUILD and HASH_JOIN_PROBE hints cannot be utilized for MPP joins, please check the hints"))
+		tk.MustQuery("show warnings").Check(testkit.Rows())
```
Comment (AilinKid) [inline pkg/planner/core/casetest/join/join_test.go:51]: since change file is about 135, we can just leverage this time, and add brief format for them, the late comer will thank you

File: pkg/planner/core/base/plan_base.go (hunk 5 above)
Comment (hawkingrei) [reply pkg/planner/core/base/plan_base.go]: I have removed.

File: pkg/planner/core/base/plan_base.go (hunk 4 above)
Comment (hawkingrei) [reply pkg/planner/core/base/plan_base.go:412]: I have removed.

File: pkg/planner/core/casetest/join/join_test.go (hunk 7 above)
Comment (hawkingrei) [reply pkg/planner/core/casetest/join/join_test.go:51]: It has updated.

File: pkg/planner/core/operator/logicalop/logical_selection.go [hunk 8]
```diff
@@ -240,7 +240,7 @@ func (p *LogicalSelection) DeriveStats(childStats []*property.StatsInfo, _ *expr
 // ExtractColGroups inherits BaseLogicalPlan.<12th> implementation.
 
 // PreparePossibleProperties implements base.LogicalPlan.<13th> interface.
-func (*LogicalSelection) PreparePossibleProperties(_ *expression.Schema, childrenProperties ...[][]*expression.Column) [][]*expression.Column {
+func (*LogicalSelection) PreparePossibleProperties(_ *expression.Schema, childrenProperties ...*base.PossiblePropertiesInfo) *base.PossiblePropertiesInfo {
 	return childrenProperties[0]
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_selection.go:249]: It has updated.

File: pkg/planner/core/operator/logicalop/logical_union_scan.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_union_scan.go:126]: it has been updated.

File: pkg/planner/core/operator/logicalop/logical_top_n.go [hunk 9]
```diff
@@ -141,12 +141,20 @@ func (lt *LogicalTopN) DeriveStats(childStats []*property.StatsInfo, _ *expressi
...
 // PreparePossibleProperties implements base.LogicalPlan.<13th> interface.
-func (lt *LogicalTopN) PreparePossibleProperties(_ *expression.Schema, _ ...[][]*expression.Column) [][]*expression.Column {
+func (lt *LogicalTopN) PreparePossibleProperties(_ *expression.Schema, infos ...*base.PossiblePropertiesInfo) *base.PossiblePropertiesInfo {
+	hasTiflash := false
+	if len(infos) > 0 && infos[0] != nil {
+		hasTiflash = infos[0].HasTiflash
+	}
+	lt.hasTiflash = hasTiflash
 	propCols := getPossiblePropertyFromByItems(lt.ByItems)
 	if len(propCols) == 0 {
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_top_n.go:148]: resolved

**Comment by hawkingrei** [comment]
@pantheon-ai review

**Comment by hawkingrei** [comment]
> ​

I have improved it.

**Comment by hawkingrei** [comment]
@pantheon-ai review

File: pkg/planner/core/operator/logicalop/logical_cte.go [hunk 10]
```diff
@@ -229,7 +229,28 @@ func (p *LogicalCTE) DeriveStats(_ []*property.StatsInfo, selfSchema *expression
...
 // ExtractColGroups inherits BaseLogicalPlan.LogicalPlan.<12th> implementation.
 
-// PreparePossibleProperties inherits BaseLogicalPlan.LogicalPlan.<13th> implementation.
+// PreparePossibleProperties implements base.LogicalPlan.<13th> interface.
+func (p *LogicalCTE) PreparePossibleProperties(_ *expression.Schema, childrenProperties ...*base.PossiblePropertiesInfo) *base.PossiblePropertiesInfo {
+	if len(childrenProperties) > 0 {
+		hasTiflash := true
+		for _, child := range childrenProperties {
+			if child == nil {
+				hasTiflash = false
```
Comment (AilinKid) [inline pkg/planner/core/operator/logicalop/logical_cte.go]: once a child is nil, we don't need reset the global hasTiflash, otherwise it will block other child's hasTiflash status

**Comment by Mini256** [comment]
@pantheon-bot review

File: pkg/planner/core/operator/logicalop/logical_cte.go (hunk 10 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_cte.go]: Updated. In LogicalCTE.PreparePossibleProperties, nil child properties are now skipped instead of forcing hasTiflash=false. We aggregate HasTiflash across non-nil children only, and fallback to seed-plan TiFlash availability when all child properties are nil. Added a unit test: TestLogicalCTEPreparePossiblePropertiesSkipNilChild.

File: pkg/planner/core/base/plan_base.go [hunk 11]
```diff
@@ -378,3 +378,63 @@ type PhysicalJoin interface {
...
+	// all possible order properties
+	Order [][]*expression.Column
```
Comment (fixdb) [inline pkg/planner/core/base/plan_base.go]: Orders or OrderArray

Comment (hawkingrei) [reply pkg/planner/core/base/plan_base.go]: Updated. Renamed it to `Orders` in commit 44eee457c4c. Thanks for the suggestion.

**Comment by hawkingrei** [comment]
@pantheon-bot review

File: pkg/planner/cascades/memo/group_expr.go [hunk 12]
```diff
@@ -223,19 +223,23 @@ func (e *GroupExpression) DeriveLogicalProp() (err error) {
...
+			HasTiflash: childGProp.HasTiflash,
+		})
 	}
 	e.GetGroup().SetLogicalProperty(property.NewLogicalProp())
 	// currently the schemaProducer side logical op is still useful for group schema.
 	tmpFD := e.LogicalPlan.GetBaseLogicalPlan().(*logicalop.BaseLogicalPlan).FDs()
 	tmpSchema := e.LogicalPlan.Schema()
 	tmpStats := e.LogicalPlan.StatsInfo()
 	var tmpPossibleProps [][]*expression.Column
+	var tmpHasTiflash bool
```
Comment (windtalker) [inline pkg/planner/cascades/memo/group_expr.go]: I think you should either use TiFlash or tiflash.

Comment (hawkingrei) [reply pkg/planner/cascades/memo/group_expr.go]: I have update code for it.
