### PR TITLE
timer: fix data race in timer store

### LINKED ISSUE #44576: DATA RACE in the memoryStoreCore
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c0001e7620 by goroutine 7:
  runtime.mapassign_faststr()
      GOROOT/src/runtime/map_faststr.go:203 +0x0
  github.com/pingcap/tidb/timer/api.(*memoryStoreCore).Update()
      timer/api/mem_store.go:136 +0x2f3
  github.com/pingcap/tidb/timer/api.(*defaultTimerClient).CloseTimerEvent()
      timer/api/client.go:189 +0x521
  github.com/pingcap/tidb/timer/runtime.TestTimerFullProcess()
      timer/runtime/runtime_test.go:774 +0x15fd
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1629 +0x47
Previous read at 0x00c0001e7620 by goroutine 8:
  runtime.mapiterinit()
      GOROOT/src/runtime/map.go:815 +0x0
  github.com/pingcap/tidb/timer/api.(*memoryStoreCore).List()
      timer/api/mem_store.go:103 +0x164
  github.com/pingcap/tidb/timer/runtime.(*TimerGroupRuntime).partialRefreshTimers()
      timer/runtime/runtime.go:337 +0x61c
  github.com/pingcap/tidb/timer/runtime.(*TimerGroupRuntime).batchHandleWatchResponses()
      timer/runtime/runtime.go:386 +0x204
  github.com/pingcap/tidb/timer/runtime.(*TimerGroupRuntime).loop()
      timer/runtime/runtime.go:179 +0xcf4
  github.com/pingcap/tidb/timer/runtime.(*TimerGroupRuntime).Start.func2()
      timer/runtime/runtime.go:115 +0x39
Goroutine 7 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1906 +0xb44
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x70
  github.com/pingcap/tidb/timer/runtime.TestMain()
      timer/runtime/main_test.go:32 +0x44
  main.main()
      bazel-out/k8-fastbuild/bin/timer/runtime/runtime_test_/testmain.go:136 +0x5e8
Goroutine 8 (running) created at:
  github.com/pingcap/tidb/timer/runtime.(*TimerGroupRuntime).Start()
      timer/runtime/runtime.go:115 +0x1f6
  github.com/pingcap/tidb/timer/runtime.TestTimerFullProcess()
      timer/runtime/runtime_test.go:733 +0xb86
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1629 +0x47
================== 
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #44576

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: timer/api/mem_store.go [hunk 1]
```diff
@@ -98,6 +98,9 @@ func (s *memoryStoreCore) Create(_ context.Context, record *TimerRecord) (string
 }
```
Comment (hawkingrei) [inline timer/api/mem_store.go:98]: Please add ```race = "on",``` in the timer/api/BUILD.bazel.

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
