### PR TITLE
planner: fix inconsistent schema between UnionAll and child operator

### LINKED ISSUE #29705: Internal error when pushdown agg into partitionUnion
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
drop table if exists t;
create table t(id int) partition by hash(id) partitions 4;
insert into t values(1);
SELECT COUNT(1) FROM ( SELECT COUNT(1)  FROM t b GROUP BY id) a;

### 2. What did you expect to see? (Required)
```
MySQL [test]> SELECT COUNT(1) FROM ( SELECT COUNT(1)  FROM t b GROUP BY id) a;
+----------+
| COUNT(1) |
+----------+
|        1 |
+----------+
1 row in set (0.000 sec)
```

### 3. What did you see instead (Required)
ERROR 1105 (HY000): Internal error: UnionExec chunk column count mismatch, req: 1, result: 2
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #29705

Problem Summary:

The schema of the `UnionAll` is different from its children operators. Then the Union Exec returns an error.

In this case, the `UnionAll` has one column but its child `Aggregation` has two. It's caused by an extra column is added to `Aggregation` in `(*LogicalAggregation).PruneColumns()`.

### What is changed and how it works?

Add extra logic in `(*LogicalUnionAll).PruneColumns` to handle this case. 
When `UnionAll` finds its child has more columns, it will add the extra column to its schema.

About the additional changes in the test, please see the issue.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: planner/core/rule_column_pruning.go [hunk 1]
```diff
@@ -241,6 +241,17 @@ func (p *LogicalUnionAll) PruneColumns(parentUsedCols []*expression.Column) erro
 				p.schema.Columns = append(p.schema.Columns[:i], p.schema.Columns[i+1:]...)
 			}
 		}
+		// It's possible that the child operator adds extra columns to the schema.
+		// Currently, (*LogicalAggregation).PruneColumns() might do this.
+		// When this happened, we need to detect the extra column and keep the UnionAll's schema
+		// 	consistent with the children's schema.
+		if p.schema.Len() < p.Children()[0].Schema().Len() {
```
Comment (lcwangchao) [inline planner/core/rule_column_pruning.go:248]: Why not just copy all columns from `children[0].Schema().Columns` to `p.schema.Columns`

File: planner/core/rule_column_pruning.go [hunk 2]
```diff
@@ -241,6 +241,17 @@ func (p *LogicalUnionAll) PruneColumns(parentUsedCols []*expression.Column) erro
 				p.schema.Columns = append(p.schema.Columns[:i], p.schema.Columns[i+1:]...)
 			}
 		}
+		// It's possible that the child operator adds extra columns to the schema.
```
Comment (lcwangchao) [inline planner/core/rule_column_pruning.go:244]: Is it possible that `children[0]` is `LogicalAggregation` and `child[1]` is `LogicalProjection` which will not add extra column?

Comment (time-and-fate) [reply planner/core/rule_column_pruning.go:244]: Switched to a new method to avoid errors in such cases.

File: planner/core/rule_column_pruning.go [hunk 3]
```diff
@@ -241,6 +241,25 @@ func (p *LogicalUnionAll) PruneColumns(parentUsedCols []*expression.Column) erro
...
+		// Currently, (*LogicalAggregation).PruneColumns() might do this.
+		// But we don't need such columns, so we add an extra Projection to prune this column when this happened.
+		for i, child := range p.Children() {
+			if p.schema.Len() < child.Schema().Len() {
+				// Copy and use the Union's schema as the Projection's Exprs and schema.
+				newCols := make([]expression.Column, len(p.schema.Columns))
+				exprs := make([]expression.Expression, len(p.schema.Columns))
+				for j, col := range p.schema.Columns {
+					newCols[j] = *col
```
Comment (winoros) [inline planner/core/rule_column_pruning.go:253]: We don't need this change?

Comment (time-and-fate) [reply planner/core/rule_column_pruning.go]: Updated. Now the `Projection`'s schema and `Exprs` share the same `Column`s.

File: planner/core/rule_column_pruning.go [hunk 4]
```diff
@@ -241,6 +241,23 @@ func (p *LogicalUnionAll) PruneColumns(parentUsedCols []*expression.Column) erro
 				p.schema.Columns = append(p.schema.Columns[:i], p.schema.Columns[i+1:]...)
 			}
 		}
+		// It's possible that the child operator adds extra columns to the schema.
+		// Currently, (*LogicalAggregation).PruneColumns() might do this.
+		// But we don't need such columns, so we add an extra Projection to prune this column when this happened.
+		for i, child := range p.Children() {
+			if p.schema.Len() < child.Schema().Len() {
```
Comment (lcwangchao) [inline planner/core/rule_column_pruning.go:248]: `p.schema` is adjusted with child[0] . Will it happens that  `p.schema.Len() > child[1].Schema().Len()` ?

**Review by winoros — APPROVED** [review]
This change is not a very good solution though we decide to merge this into the master.
I'm curious that we can do this in the execution phase. So our planner doesn't need to do these ad-hoc changes.
@XuHuaiyu @fuzhe1989

**Comment by lcwangchao** [comment]
It will still have some risks when child[0] returns a extra column which also exists in LogicalUnion columns.  I think we need some further discuss about it.

But even so it will not introduce more problems than the previous code. I think we can merge it to fix the current bug.

**Review by lcwangchao — APPROVED** [review]

**Comment by time-and-fate** [comment]
/needs-cherry-pick-5.0
/needs-cherry-pick-5.1
/needs-cherry-pick-5.2
/needs-cherry-pick-5.3
