### PR TITLE
ast: Allow SELECT statements to set user-defined variables in read-only mode.

### LINKED ISSUE #55281: Rewriting user-defined variable in select stmt isn't treated as read only
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> set global tidb_super_read_only=1;
Query OK, 0 rows affected (0.00 sec)

mysql> select @i:=@i+1;
ERROR 1836 (HY000): Running in read-only mode

mysql> set @i:=@i+1;
Query OK, 0 rows affected (0.00 sec)
```
### 2. What did you expect to see? (Required)

The behavior is allowed like mysql:
```
mysql> select @@super_read_only;
+-------------------+
| @@super_read_only |
+-------------------+
|                 1 |
+-------------------+
1 row in set (0.00 sec)

mysql> select @i:=@i+1;
+----------+
| @i:=@i+1 |
+----------+
|     NULL |
+----------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                                              |
+---------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1287 | Setting user variables within expressions is deprecated and will be removed in a future release. Consider alternatives: 'SET variable=expression, ...', or 'SELECT expression(s) INTO variables(s)'. |
+---------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select @i+1 into @i;
Query OK, 1 row affected (0.00 sec)

mysql> set @i:=@i+1;
Query OK, 0 rows affected (0.00 sec)
```

### 3. What did you see instead (Required)

ERROR 1836 (HY000): Running in read-only mode

### 4. What is your TiDB version? (Required)
v6.5.10

### PR DESCRIPTION
**Pull request by wddevries**
### What problem does this PR solve?

Issue Number: close #55281

Problem Summary:
In read-only mode user-defined variables cannot be set with select statements.  You can reproduce this by running:

`set global tidb_super_read_only=1; select @i:=@i+1;`

This is allowed on MySQL.

### What changed and how does it work?
After reviewing the various code paths that can reach ast.IsReadOnly, I could find no reason this function would need to return false for read-only queries that set user-defined variables. This patch removes the part of ast.IsReadOnly that checks for writes to user-defined variables, which fixes the bug.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by songrijie** [comment]
LGTM. There's no reason to make it incompatible with MySQL. 

The impact of the backward-compatibility is minor.  Such logic should not exist in running applications as it errors out.

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by dveeden — APPROVED** [review]

File: pkg/parser/ast/util.go [hunk 1]
```diff
@@ -69,28 +64,3 @@ func IsReadOnly(node Node) bool {
...
-// Enter implements Visitor interface.
-func (checker *readOnlyChecker) Enter(in Node) (out Node, skipChildren bool) {
-	if node, ok := in.(*VariableExpr); ok {
-		// like func rewriteVariable(), this stands for SetVar.
-		if !node.IsSystem && node.Value != nil {
-			checker.readOnly = false
-			return in, true
-		}
-	}
-	return in, false
```
Comment (tiancaiamao) [inline pkg/parser/ast/util.go:90]:
```
// Enter implements Visitor interface.
func (checker *readOnlyChecker) Enter(in Node) (out Node, skipChildren bool) {
	if node, ok := in.(*VariableExpr); ok {
		// like func rewriteVariable(), this stands for SetVar.
		// By default, in select statement, readOnly is set to true
		if node.Value != nil {
			// But in 'select var to val', readOnly should be false
			checker.readOnly = false
			if !node.IsSystem {
				// One exception is 'select @val to val', change user variable is readOnly
				checker.readOnly = true
				return in, false
			}
			return in, true
		}
	}
	return in, false
}
```

I think the original author's intention is correct, just that he used wrong logic of `&&` to combine two differect branch and introduce the bug.
I try to express it in the original intention, and this should work.


Your changes still work but less robust, it removes the checker totally, 
the correctness depends on the parser not adding some other `*VariableExpr` in the future,
and once the assumption break, bug may sneak in.

@wddevries

**Comment by tiancaiamao** [comment]
By the way, I find set operation is allowed in `tidb_super_read_only=1`, is that expected?   @wddevries 

`set global tidb_super_read_only=1;  set @@tidb_enable_paging = 0`

File: pkg/parser/ast/util.go (hunk 1 above)
Comment (wddevries) [reply pkg/parser/ast/util.go:90]: You may be correct.  For the record, your function simplifies to:
```
// Enter implements Visitor interface.
func (checker *readOnlyChecker) Enter(in Node) (out Node, skipChildren bool) {
    if node, ok := in.(*VariableExpr); ok {
        // like func rewriteVariable(), this stands for SetVar.
        if node.IsSystem && node.Value != nil {
            checker.readOnly = false
            return in, true
        }
    }
    return in, false
}
```
Instead of marking queries that update user-variables are non-read-only, we would mark queries that update global variables as non-read-only.  Since updates to global variables are written to the database, this may be reasonable.

Generally ast.IsReadOnly is used to:
1. determine if a user can run a query in read-only mode.
2. determine compile/planning and commit options.

I am not sure you can actually create queries have global variable updates in the ast, but maybe we should still handle it correctly.

I will update the code.

**Comment by wddevries** [comment]
> By the way, I find set operation is allowed in `tidb_super_read_only=1`, is that expected? @wddevries
> 
> `set global tidb_super_read_only=1; set @@tidb_enable_paging = 0`

Yes.  The SET command work correctly already.

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
PTAL @fixdb

File: pkg/planner/optimize.go [hunk 2]
```diff
@@ -416,7 +421,7 @@ func allowInReadOnlyMode(sctx planctx.PlanContext, node ast.Node) (bool, error)
 	}
 
 	vars := sctx.GetSessionVars()
-	return IsReadOnly(node, vars), nil
+	return isReadOnlyInternal(node, vars, false), nil
```
[the remark this answers is not in the document]
Comment (wddevries) [reply pkg/planner/optimize.go:425]: I added a comment.
