### PR TITLE
globalsort: reduce number of SST ingested into TiKV (#59870)

### LINKED ISSUE #59962: global-sort: reduce number of SST ingested into TiKV
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

currently, global sort always split data into ranges of 96M, but TiKV already increased the default region size to 256M now, so we will ingest 3 SST files per region.
for import-into see https://github.com/pingcap/tidb/blob/bf21e5964b693f1974599fdc7a9154e3c6852721/pkg/disttask/importinto/planner.go#L550-L551, for add-index see https://github.com/pingcap/tidb/blob/bf21e5964b693f1974599fdc7a9154e3c6852721/pkg/ddl/backfilling_dist_scheduler.go#L675
and the ingest performance of TiKV slows down when the number of SST files grows too much, say more than 300K

### 4. What is your TiDB version? (Required)
v8.1.0

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #59962, ref #51734

Problem Summary:

### What changed and how does it work?
this PR is a manually pick of https://github.com/pingcap/tidb/pull/59870

- calculate range-size depends on available memory and region-split-size, to reduce the number of SST ingest into TiKV by
  - reduce the worker concurrency from `2*concurrency` to `concurrency`(there might be a small performance degradation in this step, see below result)
  - abstract memory usage during ingest step based on range size, see detail in https://github.com/pingcap/tidb/pull/59870/files#diff-14ea038e11c33e3fe22e36a619fc1721f9dc71c59f01d83086247fa92d7548deR40-R70
- remove the hardcode `12G` memory limit for loading range data, we calculate it by the above abstraction too, to allow loading bigger range data
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

for a test with region-size 256M，`sst-count:region` ratio，`3.4` -> `1.6`

for a cluster with `region-size = 200M`, adding 8 index, with this pr, SST at L6 `8701 -> 9229 = 528`. without this pr, `9229 -> 10205 = 976`. about `45%` reduction in number of SST generated.

image

also test IMPORT-INTO with 800G, and add index on it, there's no block on `membuf.Aquire`
test add-index on 15.6T data, also no block on `membuf.Aquire`

with this PR, import a 800G table and 4447200 rows using 2 16c32g TiDB, with 24 secondary indices. the result SST count in write-L6 is 9.73k
```sql
+-----------------+----------+
| step            | duration |
+-----------------+----------+
| 0. total        | 00:42:43 |
| 1. encode&sort  | 00:11:27 |
| 2. merge-sort   | NULL     |
| 3. write&ingest | 00:24:19 | // a little slower
| 4. post-process | 00:06:43 |
+-----------------+----------+
```

without this PR, same scenario, the result SST count in write-L6 is 15.9K:
```sql
+-----------------+----------+
| step            | duration |
+-----------------+----------+
| 0. total        | 00:49:58 |
| 1. encode&sort  | 00:11:23 |
| 2. merge-sort   | NULL     |
| 3. write&ingest | 00:22:46 |
| 4. post-process | 00:15:38 | // The read IO of TiKV became small when checksum data KV, not sure why, need check it later
+-----------------+----------+
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/backend/external/engine.go [hunk 1]
```diff
@@ -257,6 +302,8 @@ func getFilesReadConcurrency(
 			)
 		}
 	}
+	logutil.Logger(ctx).Info("estimated file size of this range group",
+		zap.Uint64("totalSize", totalFileSize))
```
Comment (tangenta) [inline pkg/lightning/backend/external/engine.go:306]: Use `units.BytesSize` instead?

File: pkg/lightning/config/const.go [hunk 2]
```diff
@@ -31,7 +31,7 @@ const (
 	// 	https://github.com/tikv/tikv/blob/e030a0aae9622f3774df89c62f21b2171a72a69e/etc/config-template.toml#L360
 	// lower the max-key-count to avoid tikv trigger region auto split
 	SplitRegionSize         ByteSize = 96 * units.MiB
-	SplitRegionKeys         int      = 1_280_000
+	SplitRegionKeys         int      = 960_000
```
Comment (D3Hunter) [inline pkg/lightning/config/const.go:34]: this is the default for TiKV, see https://github.com/tikv/tikv/blob/e030a0aae9622f3774df89c62f21b2171a72a69e/etc/config-template.toml#L361

**Review by tangenta — APPROVED** [review]

**Review by CbcWestwolf — APPROVED** [review]
