### PR TITLE
domain,server,session: optimize gc safepoint advancing for internal transaction

### LINKED ISSUE #32725: Optimize gc safepoint advancing for internal transaction
## Enhancement
TiDB advances gc safepoint every `tidb_gc_run_interval` time with step `tidb_gc_life_time`. If there is a long time transaction from user client lives more than `tidb_gc_life_time`, the safpoint can't be advanced until the long transaction is finished or lives than 24h. This mechanism ensures the continuous advancement of gc safepoint and ensures that the data that active transactions need to access will not be cleared.
However, Internal transactions run in TiDB don't comply with the mechanism above. If the internal transaction lives more than `tidb_gc_life_time`,  maybe failed because the data it needs to access was cleared. 
Here is an example that an auto analyze task run failed when it lived more than 20 minutes because the data was cleared. The TiDB log printed `[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2021-11-17 14:09:54.756 +0800 CST, GC safe point is 2021-11-17 14:11:54.755 +0800 CST`

### PR DESCRIPTION
**Pull request by TonsnakeLin**
Signed-off-by: TonsnakeLin <lpbgytong@163.com>

### What problem does this PR solve?

TiDB advances gc safepoint every tidb_gc_run_interval time with step tidb_gc_life_time. If there is a long time transaction from user client lives more than tidb_gc_life_time, the safpoint can't be advanced until the long transaction is finished or lives than 24h. This mechanism ensures the continuous advancement of gc safepoint and ensures that the data that active transactions need to access will not be cleared.
However, Internal transactions run in TiDB don't comply with the mechanism above. If the internal transaction lives more than tidb_gc_life_time, maybe failed because the data it needs to access was cleared. This PR is used to solve the problem that internal transactions run in TiDB may be executed failed because the accessed data was cleared.

Issue Number: close #32725

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility
image
image

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by TonsnakeLin** [comment]
@cfzjywxk @MyonKeminta @youjiali1995 @sticnarf @you06 ,thanks !!

**Comment by TonsnakeLin** [comment]
@cfzjywxk @MyonKeminta @youjiali1995 @sticnarf @you06

File: kv/txn.go [hunk 1]
```diff
@@ -19,21 +19,269 @@ import (
...
+
+	innerTSLock        sync.Mutex
+	innerTxnStartTsMap map[uint64]uint64
+
+	// `storeInnerTxnStartTsLoop` and `deleteInnerTxnStartTsLoop` run asynchronously,
+	// It can't ensure `storeInnerTxnStartTsLoop` receives startTS before `deleteInnerTxnStartTsLoop`,
+	// though `RunInNewTxn`send startTS to `storeInnerTxnStartTsLoop` firstly. If `deleteInnerTxnStartTsLoop`
+	// recevied startTS before `storeInnerTxnStartTsLoop`, the `startTS` couldn't be deleted from `innerTxnStartTsMap`,
+	// and GC safepoint can't be advanced properly.
+	undeletedTsLock        sync.Mutex
```
Comment (youjiali1995) [inline kv/txn.go:59]: Why not use a single channel and goroutine to process 2 types of task - put and delete?

File: util/processinfo.go [hunk 2]
```diff
@@ -169,6 +170,12 @@ type SessionManager interface {
 	KillAllConnections()
 	UpdateTLSConfig(cfg *tls.Config)
 	ServerID() uint64
+	// Put the internal session pointer to the map in the SessionManager
+	StoreInternalSession(addr unsafe.Pointer)
```
Comment (youjiali1995) [inline util/processinfo.go:174]: Why use `unsafe.Pointer`?

File: kv/txn.go [hunk 3]
```diff
@@ -19,21 +19,124 @@ import (
...
+	ib := getGlobalInnerTxnTsBox()
+	if ib == nil {
+		logutil.BgLogger().Info("Fail to get internal txn startTS, globalInnerTxnTsBox is nil")
+		return curMinStartTS
+	}
+	return ib.getMinStartTs(now, startTSLowerLimit, curMinStartTS)
+}
+
+func (ib *innerTxnStartTsBox) getMinStartTs(now time.Time, startTSLowerLimit uint64,
+	curMinStartTS uint64) uint64 {
```
Comment (sticnarf) [inline kv/txn.go:110]: IMHO `curMinStartTS` needn't be passed into this function, so the function itself does exactly one thing, instead of mixing getting min startTS and combining it with other timestamps.

File: sessionctx/variable/tidb_vars.go [hunk 4]
```diff
@@ -631,6 +631,8 @@ const (
 	TiDBGCConcurrency = "tidb_gc_concurrency"
 	// TiDBGCScanLockMode enables the green GC feature (default)
 	TiDBGCScanLockMode = "tidb_gc_scan_lock_mode"
+	// TiDBGCMaxWaitTime sets max time for gc advances the safepoint delayed by active transactions
+	TiDBGCMaxWaitTime = "tidb_gc_txn_max_wait_time"
```
[the remark this answers is not in the document]
Comment (TonsnakeLin) [reply sessionctx/variable/tidb_vars.go:635]: ok

File: kv/txn.go (hunk 1 above)
Comment (TonsnakeLin) [reply kv/txn.go]: I worry about that it maybe cause a message block. I removed these code and don't use channel now

File: util/processinfo.go (hunk 2 above)
Comment (TonsnakeLin) [reply util/processinfo.go:174]: If I use Session interface, it causes package cycle.

File: domain/infosync/info.go [hunk 5]
```diff
@@ -629,7 +631,18 @@ func (is *InfoSyncer) ReportMinStartTS(store kv.Storage) {
 		}
 	}
 
-	is.minStartTS = minStartTS
+	for _, interTS := range InnerSessionStartTSList {
+		innerTxnStartTime := oracle.GetTimeFromTS(interTS)
+		if now.Sub(innerTxnStartTime) > kv.TimeToPrintLongTimeInternalTxn {
+			logutil.BgLogger().Info("An internal trasanction running by internal session lasts long time",
```
[the remark this answers is not in the document]
Comment (TonsnakeLin) [reply domain/infosync/info.go:637]: Yes, I'll fix it and please review it again.

File: kv/txn.go [hunk 6]
```diff
@@ -19,21 +19,124 @@ import (
...
 	"github.com/pingcap/failpoint"
 	"github.com/pingcap/tidb/parser/terror"
 	"github.com/pingcap/tidb/util/logutil"
+	"github.com/tikv/client-go/v2/oracle"
 	"go.uber.org/zap"
 )
 
+const (
+	chanBufferSize             = 256
+	undeletedStartTsBufferSize = 16
```
[the remark this answers is not in the document]
Comment (TonsnakeLin) [reply kv/txn.go]: `undeletedStartTsBufferSize` is used to for the channel `undeletedchan`, I removed it.

File: kv/txn.go (hunk 3 above)
Comment (TonsnakeLin) [reply kv/txn.go:109]: If do that, the caller must compare the returned startTS with current min startTS and get the smaller. It looks not so cleanly. And I think the function getMinStartTs doesn't mix more things together, It just gets the minimum startTS which consider the current one.

File: kv/txn.go [hunk 7]
```diff
@@ -17,23 +17,112 @@ package kv
...
+//					false means the transaction is run by internal session
+func PrintLongTimeInternalTxn(now time.Time, startTS uint64, runByFunction bool) {
+	if startTS > 0 {
+		innerTxnStartTime := oracle.GetTimeFromTS(startTS)
+		if now.Sub(innerTxnStartTime) > TimeToPrintLongTimeInternalTxn {
+			callerName := "internal session"
+			if runByFunction {
+				callerName = "RunInNewTxn"
+			}
+			infoHeder := fmt.Sprintf("An internal transaction running by %s lasts long time", callerName)
```
Comment (sticnarf) [inline kv/txn.go:105]:
```suggestion
			infoHeader := fmt.Sprintf("An internal transaction running by %s lasts long time", callerName)
```

File: kv/txn.go [hunk 8]
```diff
@@ -17,23 +17,112 @@ package kv
...
+	ib.innerTxnStartTsMap[startTS] = struct{}{}
+	ib.innerTSLock.Unlock()
+
+}
+
+// wrapDeleteInterTxnTS delete the startTS from globalInnerTxnTsBox when the transaciotn is commted
+// @param startTS	the startTS of the internal transaction produced by `RunInNewTxn`
+func wrapDeleteInterTxnTS(startTS uint64) {
+	globalInnerTxnTsBox.deleteInnerTxnTS(startTS)
+}
```
Comment (sticnarf) [inline kv/txn.go:66]: Do we still need the function? Its content is too simple...

File: kv/txn.go [hunk 9]
```diff
@@ -17,23 +17,112 @@ package kv
...
+	ib.innerTSLock.Lock()
+	delete(ib.innerTxnStartTsMap, startTS)
+	ib.innerTSLock.Unlock()
+}
+
+// WrapGetMinStartTs get the min StartTS between startTSLowerLimit and curMinStartTS in globalInnerTxnTsBox
+func WrapGetMinStartTs(now time.Time, startTSLowerLimit uint64,
+	curMinStartTS uint64) uint64 {
+	return globalInnerTxnTsBox.getMinStartTs(now, startTSLowerLimit, curMinStartTS)
+}
```
Comment (sticnarf) [inline kv/txn.go:78]: Can we just make `globalInnerTxnTsBox` and `getMinStartTs` public because the wrappers are too simple?

File: kv/txn.go (hunk 3 above)
Comment (sticnarf) [reply kv/txn.go:81]: Well, I prefer to compare current min start TS out of the function because in my mind the logic is (1) get min start TS among internal sessions (2) get min startTS among `RunInNewTxn`s (3) use the smaller one
Each step is independent. It's not necessary for step (2) to depend on the min start TS got from step (1).

File: kv/txn.go (hunk 8 above)
Comment (TonsnakeLin) [reply kv/txn.go:66]: I‘ll remove it

File: kv/txn.go (hunk 9 above)
Comment (TonsnakeLin) [reply kv/txn.go:78]: I agree

File: kv/txn.go [hunk 10]
```diff
@@ -17,23 +17,112 @@ package kv
...
+		if now.Sub(innerTxnStartTime) > TimeToPrintLongTimeInternalTxn {
+			callerName := "internal session"
+			if runByFunction {
+				callerName = "RunInNewTxn"
+			}
+			infoHeader := fmt.Sprintf("An internal transaction running by %s lasts long time", callerName)
+
+			logutil.BgLogger().Info(infoHeder,
+				zap.Duration("time", now.Sub(innerTxnStartTime)), zap.Uint64("startTS", startTS),
+				zap.Time("start time", innerTxnStartTime))
```
Comment (cfzjywxk) [inline kv/txn.go:109]: The transaction fingerprint may help to output more information about what actually is the inner transaction doing.
The `start_ts` itself could not help much if there's not enough logs about it, we could do some improvements in the future
/cc @longfangsong

File: kv/txn.go [hunk 11]
```diff
@@ -17,23 +17,112 @@ package kv
...
 	"github.com/pingcap/tidb/parser/terror"
 	"github.com/pingcap/tidb/util/logutil"
+	"github.com/tikv/client-go/v2/oracle"
 	"go.uber.org/zap"
 )
 
+const (
+	// TimeToPrintLongTimeInternalTxn is the duration if the internal transaction lasts more than it,
+	// TiDB prints a log message
+	TimeToPrintLongTimeInternalTxn = time.Minute * 5
```
Comment (cfzjywxk) [inline kv/txn.go:36]: This seems to be a bit bigger for most cases? Not quite sure, @wjhuang2016 @tangenta @tiancaiamao any advices about it?

File: kv/txn.go [hunk 12]
```diff
@@ -17,23 +17,112 @@ package kv
...
 // RunInNewTxn will run the f in a new transaction environment.
 func RunInNewTxn(ctx context.Context, store Storage, retryable bool, f func(ctx context.Context, txn Transaction) error) error {
 	var (
 		err           error
 		originalTxnTS uint64
 		txn           Transaction
 	)
+
+	defer func() {
+		wrapDeleteInterTxnTS(originalTxnTS)
```
Comment (cfzjywxk) [inline kv/txn.go:123]: This change may introduce contetion getting or releasing the internal session. 
@wjhuang2016 @tangenta @zimulala PTAL

File: kv/txn.go (hunk 3 above)
Comment (TonsnakeLin) [reply kv/txn.go:69]: Yes, the logic looks clear. But the original code mixed minStartTS and startTSLowerLimit with getting the minimum startTS for client sessions as bellow. 
	for _, info := range pl {
		if info.CurTxnStartTS > startTSLowerLimit && info.CurTxnStartTS < minStartTS {
			minStartTS = info.CurTxnStartTS
		}
	} 
In actually , I intended to wrap this code into a function too because of similar logic. But the structures for store TS are different and I give it up.
And I think it can remove minStartTS from the function getMinStartTs, but can't remove startTSLowerLimit . So, I put it together.

File: kv/txn.go [hunk 13]
```diff
@@ -17,23 +17,100 @@ package kv
...
+	ib.innerTSLock.Unlock()
+}
+
+// WrapGetMinStartTs get the min StartTS between startTSLowerLimit and curMinStartTS in globalInnerTxnTsBox
+func WrapGetMinStartTs(now time.Time, startTSLowerLimit uint64,
+	curMinStartTS uint64) uint64 {
+	return globalInnerTxnTsBox.getMinStartTs(now, startTSLowerLimit, curMinStartTS)
+}
+
+func (ib *innerTxnStartTsBox) getMinStartTs(now time.Time, startTSLowerLimit uint64,
```
Comment (youjiali1995) [inline kv/txn.go:68]: Unify the format of ts, `Ts` ❌, `TS` ✔️.

File: kv/txn.go (hunk 9 above)
Comment (sticnarf) [reply kv/txn.go:66]: My confusion is that I cannot understand what `Wrap` means here... So, it's actually hard for me to recognize what `WrapGetMinStartTS` is from the caller...
If you call transactions from `RunInNewTxn` as `InnerTxn`, what about renaming `WrapGetMinStartTs` to `GetMinInnerTxnStartTS`>

Comment (TonsnakeLin) [reply kv/txn.go:66]: ok

File: server/server.go [hunk 14]
```diff
@@ -797,6 +802,35 @@ func (s *Server) ServerID() uint64 {
...
+// @param addr	The address of a session.session struct variable
+func (s *Server) DeleteInternalSession(se interface{}) {
+	s.isRwlock.Lock()
+	delete(s.internalSessions, se)
+	s.isRwlock.Unlock()
+}
+
+// GetInternalSessionStartTSList implements SessionManager interface.
+func (s *Server) GetInternalSessionStartTSList() []uint64 {
+	s.isRwlock.RLock()
```
[the remark this answers is not in the document]
Comment (TonsnakeLin) [reply server/server.go:823]: done

File: kv/txn.go (hunk 13 above)
Comment (TonsnakeLin) [reply kv/txn.go:68]: done

File: session/session.go [hunk 15]
```diff
@@ -3223,6 +3241,21 @@ func (s *session) ShowProcess() *util.ProcessInfo {
 	return pi
 }
 
+// GetStartTSFromSession returns the ProcessInfo in the session whose
+// address is `addr`
```
[the remark this answers is not in the document]
Comment (TonsnakeLin) [reply session/session.go:3229]: done

File: kv/txn.go (hunk 11 above)
Comment (TonsnakeLin) [reply kv/txn.go:36]: sysbench test data was pasted in the PR description.
I think the tps and duaration variance is deviation

File: domain/infosync/info.go [hunk 16]
```diff
@@ -620,7 +621,8 @@ func (is *InfoSyncer) ReportMinStartTS(store kv.Storage) {
 		return
 	}
 	now := oracle.GetTimeFromTS(currentVer.Ver)
-	startTSLowerLimit := oracle.GoTimeToLowerLimitStartTS(now, tikv.MaxTxnTimeUse)
+	// GCMaxWaitTime is in seconds, GCMaxWaitTime * 1000 converts it to milliseconds
```
Comment (zimulala) [inline domain/infosync/info.go:624]: Please add a `.` for a complete sentence.

File: domain/infosync/info.go [hunk 17]
```diff
@@ -1047,3 +1057,29 @@ func ConfigureTiFlashPDForPartitions(accel bool, definitions *[]model.PartitionD
 	}
 	return nil
 }
+
+// StoreInternalSession is the entry function for store an internal session to SessionManager
```
Comment (zimulala) [inline domain/infosync/info.go:1061]: Ditto.

File: domain/infosync/info.go [hunk 18]
```diff
@@ -1047,3 +1057,29 @@ func ConfigureTiFlashPDForPartitions(accel bool, definitions *[]model.PartitionD
...
+		return
+	}
+	sm := is.GetSessionManager()
+	if sm == nil {
+		return
+	}
+	sm.StoreInternalSession(se)
+}
+
+// DeleteInternalSession is the entry function for delete an internal session from SessionManager
```
Comment (zimulala) [inline domain/infosync/info.go:1074]: Ditto.

File: kv/txn.go [hunk 19]
```diff
@@ -17,23 +17,100 @@ package kv
...
+
+}
+
+func (ib *innerTxnStartTsBox) deleteInnerTxnTS(startTS uint64) {
+	ib.innerTSLock.Lock()
+	delete(ib.innerTxnStartTsMap, startTS)
+	ib.innerTSLock.Unlock()
+}
+
+// GetMinInnerTxnStartTS get the min StartTS between startTSLowerLimit and curMinStartTS in globalInnerTxnTsBox
```
Comment (zimulala) [inline kv/txn.go:62]: Ditto.
There are many places that have this problem, please deal with it together.

File: domain/infosync/info.go [hunk 20]
```diff
@@ -612,6 +612,7 @@ func (is *InfoSyncer) ReportMinStartTS(store kv.Storage) {
 		return
 	}
 	pl := is.manager.ShowProcessList()
+	InnerSessionStartTSList := is.manager.GetInternalSessionStartTSList()
```
Comment (sticnarf) [inline domain/infosync/info.go:615]: `InnerSessionStartTSList` -> `innerSessionStartTSList`
Local variables generally start with lowercase.

File: domain/infosync/info.go [hunk 21]
```diff
@@ -1047,3 +1057,29 @@ func ConfigureTiFlashPDForPartitions(accel bool, definitions *[]model.PartitionD
...
+	is, err := getGlobalInfoSyncer()
+	if err != nil {
+		return
+	}
+	sm := is.GetSessionManager()
+	if sm == nil {
+		return
+	}
+	sm.DeleteInternalSession(se)
+}
```
Comment (sticnarf) [inline domain/infosync/info.go:1085]: Can you explain why we need these two functions defined in `infosync`? Now, I search the code and only find them used from `session`, but `session` itself has `GetSessionManager`. So, I think it's already convenient to write `s.GetSessionManager().StoreInternalSession(se)` (probably need a nil check)

**Review by sticnarf — COMMENTED** [review]
The rest LGTM

File: domain/infosync/info.go (hunk 21 above)
Comment (cfzjywxk) [reply domain/infosync/info.go:1085]: The initialization process of the internal and user sessions are quite different, it seems the refactoring work is paused by now. Maybe we could file an issue to record this.

File: domain/infosync/info.go (hunk 20 above)
Comment (TonsnakeLin) [reply domain/infosync/info.go]: done

File: domain/infosync/info.go (hunk 21 above)
Comment (TonsnakeLin) [reply domain/infosync/info.go:1085]: I will do it

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by youjiali1995 — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
