### PR TITLE
ddl: defining the placement rule of a leader requires `REPLICAS` option

### LINKED ISSUE #20751: ddl: defining the placement rule of a leader requires `REPLICAS` option
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
alter table t_part_pk_id alter partition p0 add placement policy constraints='["+host=store1"]' role=leader;
```

### 2. What did you expect to see? (Required)

It should not report an error, as `role=leader` implies `REPLICAS=1`.

### 3. What did you see instead (Required)

```
ERROR 8234 (HY000): Invalid placement policy 'add placement policy constraints='["+host=store1"]' role=leader replicas=0': array CONSTRAINTS should be with a positive REPLICAS
```

### 4. What is your TiDB version? (Required)

master

## Score

- 600

## Mentor

- @djshow832 
- @AilinKid

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #20751 

Problem Summary:

### What is changed and how it works?

What's Changed:
defining the placement rule of a leader requires `REPLICAS` option
How it Works:
If the role is leader, set the `replicas` to 1

### Check List 

Tests 

- Unit test

### Release note 

-  No release note

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -5810,6 +5810,9 @@ func buildPlacementSpecs(bundle *placement.Bundle, specs []*ast.PlacementSpec) (
 		case ast.PlacementRoleFollower:
 			role = placement.Follower
 		case ast.PlacementRoleLeader:
+			if spec.Replicas == 0 {
+				spec.Replicas = 1
+			}
```
Comment (djshow832) [inline ddl/ddl_api.go:5815]: What if the user sets it to 0 explicitly?
e.g. `leader=role replicas=0`

Comment (TszKitLo40) [reply ddl/ddl_api.go:5815]: This case has been treated in the `parser`.

File: ddl/placement_sql_test.go [hunk 2]
```diff
@@ -274,6 +274,12 @@ add placement policy
 	role=leader
 	replicas=3`)
 	c.Assert(ddl.ErrPartitionMgmtOnNonpartitioned.Equal(err), IsTrue)
+
+	// issue 20751
+	tk.MustExec("drop table if exists t_part_pk_id")
+	tk.MustExec("create TABLE t_part_pk_id (c1 int,c2 int) partition by range(c1 div c2 ) (partition p0 values less than (2))")
+	tk.MustExec("alter table t_part_pk_id alter partition p0 add placement policy constraints='[\"+host=store1\"]' role=leader;")
```
Comment (djshow832) [inline ddl/placement_sql_test.go:281]:
```suggestion
	tk.MustExec(`alter table t_part_pk_id alter partition p0 add placement policy constraints='["+host=store1"]' role=leader;`)
```

File: ddl/ddl_api.go (hunk 1 above)
Comment (AilinKid) [reply ddl/ddl_api.go:5815]: why not just throw "Invalid placement option REPLICAS, it is should be identified"? @djshow832

Comment (djshow832) [reply ddl/ddl_api.go:5815]: The number of leaders can be only 1. It's unnecessary to declare it.

**Review by djshow832 — COMMENTED** [review]
LGTM

File: ddl/ddl_api.go (hunk 1 above)
Comment (AilinKid) [reply ddl/ddl_api.go:5815]: ok

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by wjhuang2016 — DISMISSED** [review]
LGTM

**Review by djshow832 — APPROVED** [review]
