### PR TITLE
executor: fix null type print the wrong column type in infoschema

### LINKED ISSUE #38108: view leads to information_schema.columns data_type null
### 1. Minimal reproduce step (Required)
1.create view such as ,so the information_schema.columns data_type can get null 
```SQL
 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`1.1.1.1` SQL SECURITY DEFINER VIEW `v_test` (
   `type`) AS
SELECT
 NULL AS `type`,
FROM
 `test` AS `f`
```
2.so we can see the null or other type in information_schema.columns data_type

### 2. What did you expect to see? (Required)
the right data_type just like mysql

### 3. What did you see instead (Required)
the null or wrong data_type

### 4. What is your TiDB version? (Required)
newest 6.2.0 and 4.0.x

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #38108

Problem Summary:

### What is changed and how it works?

In this SQL
```
 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`1.1.1.1` SQL SECURITY DEFINER VIEW `v_test` (
   `type`) AS
SELECT
 NULL AS `type`,
FROM
 `test` AS `f`
```

```Null as `type` ```  should be as a ```binary(0)``` column in MySQL. but in tidb it is a null type.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: parser/types/etc.go [hunk 1]
```diff
@@ -121,6 +121,8 @@ func TypeToStr(tp byte, cs string) (r string) {
 		ts = strings.Replace(ts, "text", "blob", 1)
 	} else if IsTypeChar(tp) {
 		ts = strings.Replace(ts, "char", "binary", 1)
+	} else if tp == mysql.TypeNull {
+		ts = "binary"
```
Comment (xhebox) [inline parser/types/etc.go:125]: So every `null` becomes `binary`? Why not change `type2Str`?

Comment (hawkingrei) [reply parser/types/etc.go]: You are right. Done.

**Review by xhebox — APPROVED** [review]

File: parser/types/etc.go (hunk 1 above)
Comment (hawkingrei) [reply parser/types/etc.go:125]: I revert this. I find if null as binary, ```StrToType``` will be output ```"char"```. 

I think it is a problem with the information in infoschema. so that giving the right output can fix this problem.

**Review by zimulala — APPROVED** [review]
LGTM

**Review by xiongjiwei — APPROVED** [review]
