### PR TITLE
types: convert string to MySQL BIT correctly

### LINKED ISSUE #18681: load data can't load value 0/1/true/false for bit(1)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create data file `test.txt`
```
cat test.txt
true    false   0       1
```
2. Start a tidb and connect.
```
use test;
create table t(a bit(1),b bit(1),c bit(1),d bit(1));
load data local infile 'test.txt' into table t fields terminated by '\t' enclosed by '^' lines terminated by '\n';
select * from t;
+------+------+------+------+
| a    | b    | c    | d    |
+------+------+------+------+
| NULL | NULL | NULL | NULL |
+------+------+------+------+
1 row in set (0.00 sec)

```

### 2. What did you expect to see? (Required)

Can load successfully.

### 3. What did you see instead (Required)

Null.

### 4. Affected version (Required)

All version.

### 5. Root Cause Analysis

String '0','1','true','false' convert bit(1) will cause truncated.

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: close #18681 

Problem Summary:

`LOAD DATA` does not take effect on BIT. Because `LOAD DATA` regards all input as strings and TiDB cannot convert any string to bit correctly

### What is changed and how it works?

What's Changed:

- convert string to bit correctly
- consider `true`, `false`, `0`, `1`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- 
- convert string to MySQL BIT correctly

### CODE REVIEW

**Review by ichn-hu — CHANGES_REQUESTED** [review]
I would suggest to add a intergration test for #18681 , see TestLoadData in executor/write_test.go

File: types/datum.go [hunk 1]
```diff
@@ -1423,13 +1423,38 @@ func (d *Datum) convertToMysqlFloatYear(sc *stmtctx.StatementContext, target *Fi
...
+	case KindBytes:
 		uintValue, err = BinaryLiteral(d.b).ToInt(sc)
+	case KindString:
+		// To solve issue #18681, we need consider true, false, 0, 1.
+		// More situations, we also consider b'0', b'1' and so on.
+		s := BinaryLiteral(d.b).ToString()
+		if target.Flen == 1 {
+			switch strings.ToLower(s) {
+			case "true", "1":
+				uintValue = 1
```
Comment (lzmhhh123) [inline types/datum.go:1449]: In mysql 8.0:

```sql
mysql > select true, b'1', cast(true as binary);
+------+------------+--------------------------------------------+
| true | b'1'       | cast(true as binary)                       |
+------+------------+--------------------------------------------+
|    1 | 0x01       | 0x31                                       |
+------+------------+--------------------------------------------+
1 row in set (0.00 sec)
```

Maybe we should handle it in another place.

Comment (rebelice) [reply types/datum.go:1449]: This sentence of SQL has nothing to do with convert. It can be seen from the following that these values can be converted correctly, but they are returned as binary, so the output to MySQL Client may not be displayed.
```sql
MySQL [test]> select true, HEX(b'1'), HEX(cast(true as binary));
+------+-----------+---------------------------+
| TRUE | HEX(b'1') | HEX(cast(true as binary)) |
+------+-----------+---------------------------+
|    1 | 01        | 31                        |
+------+-----------+---------------------------+
1 row in set (0.001 sec)

MySQL [test]> select true, b'1', cast(true as binary);
+------+------+----------------------+
| TRUE | b'1' | cast(true as binary) |
+------+------+----------------------+
|    1 |     | 1                    |
+------+------+----------------------+
1 row in set (0.001 sec)
```
I think these are two different problems, and it's best to solve it in another PR

File: types/datum.go [hunk 2]
```diff
@@ -1429,13 +1429,38 @@ func (d *Datum) convertToMysqlFloatYear(sc *stmtctx.StatementContext, target *Fi
 	return ret, err
 }
 
+func (d *Datum) convertStringToMysqlBit(sc *stmtctx.StatementContext) (uint64, error) {
+	bitStr, err := ParseBitStr(BinaryLiteral(d.b).ToString())
+	if err != nil {
+		// This is to be compatible with the previous processing method.
```
Comment (ichn-hu) [inline types/datum.go:1435]: please be more precise with this comment, because once the PR get merged, no one will know what the "previous processing method" is.

File: types/datum.go [hunk 3]
```diff
@@ -1429,13 +1429,38 @@ func (d *Datum) convertToMysqlFloatYear(sc *stmtctx.StatementContext, target *Fi
...
 	var ret Datum
 	var uintValue uint64
 	var err error
 	switch d.k {
-	case KindString, KindBytes:
+	case KindBytes:
 		uintValue, err = BinaryLiteral(d.b).ToInt(sc)
+	case KindString:
+		// To solve issue #18681, we need consider true, false, 0, 1.
+		// More situations, we also consider b'0', b'1' and so on.
```
Comment (ichn-hu) [inline types/datum.go:1450]: I guess this fix is not specific to 18681, and the code itself is self-explaining, if you want to add comment, it is better to find if there is a reference to MySQL's doc.

File: executor/write_test.go [hunk 4]
```diff
@@ -2017,6 +2017,54 @@ func (s *testSuite8) TestLoadDataMissingColumn(c *C) {
...
+	originIgnoreTruncate := sc.IgnoreTruncate
+	defer func() {
+		sc.IgnoreTruncate = originIgnoreTruncate
+	}()
+	sc.IgnoreTruncate = false
+	// fields and lines are default, InsertData returns data is nil
+	tests := []testCase{
+		// data1 = nil, data2 != nil
+		{nil, []byte("true\tfalse\t0\t1\n"), []string{"1|0|0|1"}, nil, "Records: 1  Deleted: 0  Skipped: 0  Warnings: 0"},
+	}
```
Comment (ichn-hu) [inline executor/write_test.go:2063]: Probably you can consider intergrate this test into the following `TestLoadData` function?

File: types/datum.go (hunk 3 above)
Comment (rebelice) [reply types/datum.go:1450]: There is no mention of related behavior in the MySQL documentation, and I think there is nothing wrong with this comment

File: executor/write_test.go (hunk 4 above)
Comment (rebelice) [reply executor/write_test.go:2063]: May not work because the table structure is not the same.

File: executor/write_test.go [hunk 5]
```diff
@@ -2021,6 +2021,38 @@ func (s *testSuite8) TestLoadDataMissingColumn(c *C) {
 
 }
 
+func (s *testSuite4) TestIssue18681(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	createSQL := `drop table if exists load_data_test;
+		create table load_data_test (a bit(1),b bit(1),c bit(1),d bit(1));`
+	tk.MustExec(createSQL)
+	tk.MustExec("load data local infile '/tmp/nonexistence.csv' ignore into table load_data_test")
```
Comment (ichn-hu) [inline executor/write_test.go:2030]: this line is still irrelevant?

File: types/datum.go (hunk 3 above)
Comment (ichn-hu) [reply types/datum.go:1456]: What I am saying is that this comment is not comprehensive enough if not redundant, you don't fix code because of an issue report, you fix code because you want proper behavior, that's why I am asking for a doc reference.

I am not against referencing to an issue here, but I would like a comment like this:

```
// For single bit value, we take string like "true", "1" as 1, and "false", "0" as 0,
// this behavior is not documented in MySQL, but it behaves so, for more information, see issue #18681
```

File: executor/write_test.go (hunk 5 above)
Comment (rebelice) [reply executor/write_test.go:2030]: No, this is initialization.

File: types/datum.go (hunk 3 above)
Comment (rebelice) [reply types/datum.go]: Updated.

**Review by ichn-hu — APPROVED** [review]

**Comment by ichn-hu** [comment]
@lzmhhh123 PTAL

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
