### PR TITLE
*: improve log about stale-read query

### LINKED ISSUE #52492: improve log about stale-read query
## Enhancement

The `timestamp` field in following log is 0, which is unexpected when execute stale-read query.

```log
[2024/04/11 11:13:22.780 +08:00] [INFO] [conn.go:1146] ["command dispatched failed"] [conn=3850371262] [session_alias=] [connInfo="id:3850371262, addr:192.168.80.1:53038 status:10, collation:latin1_swedish_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="select pk, sk, ts, v, n from (             select pk, sk, ts, v, row_number() over (partition by pk, sk order by ts desc) as n             from t1 as of timestamp now() - interval 5 second where pk = '000000000000000000000000939372' and sk like '0000-0001%'         ) as tt where n <= 3 order by sk asc"] [txn_mode=PESSIMISTIC] [timestamp=0] [err="[executor:3024]Query execution was interrupted, maximum statement execution time exceeded\ngithub.com/pingcap/errors.AddStack\n\t/data/cs/code/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/data/cs/code/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175\ngithub.com/pingcap/tidb/pkg/util/sqlkiller.(*SQLKiller).HandleSignal\n\t/data/cs/tidb/pkg/util/sqlkiller/sqlkiller.go:68\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.(*executorKillerHandler).HandleSQLKillerSignal\n\t/data/cs/tidb/pkg/executor/internal/exec/executor.go:251\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/data/cs/tidb/pkg/executor/internal/exec/executor.go:409\ngithub.com/pingcap/tidb/pkg/executor/sortexec.(*SortExec).fetchChunksUnparallel\n\t/data/cs/tidb/pkg/executor/sortexec/sort.go:620\ngithub.com/pingcap/tidb/pkg/executor/sortexec.(*SortExec).fetchChunks\n\t/data/cs/tidb/pkg/executor/sortexec/sort.go:533\ngithub.com/pingcap/tidb/pkg/executor/sortexec.(*SortExec).Next\n\t/data/cs/tidb/pkg/executor/sortexec/sort.go:277\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/data/cs/tidb/pkg/executor/internal/exec/executor.go:403\ngithub.com/pingcap/tidb/pkg/executor.(*PipelinedWindowExec).fetchChild\n\t/data/cs/tidb/pkg/executor/pipelined_window.go:210\ngithub.com/pingcap/tidb/pkg/executor.(*PipelinedWindowExec).getRowsInPartition\n\t/data/cs/tidb/pkg/executor/pipelined_window.go:181\ngithub.com/pingcap/tidb/pkg/executor.(*PipelinedWindowExec).Next\n\t/data/cs/tidb/pkg/executor/pipelined_window.go:126\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/data/cs/tidb/pkg/executor/internal/exec/executor.go:403\ngithub.com/pingcap/tidb/pkg/executor.(*SelectionExec).Next\n\t/data/cs/tidb/pkg/executor/executor.go:1615\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/data/cs/tidb/pkg/executor/internal/exec/executor.go:403\ngithub.com/pingcap/tidb/pkg/executor/sortexec.(*SortExec).fetchChunksUnparallel\n\t/data/cs/tidb/pkg/executor/sortexec/sort.go:620\ngithub.com/pingcap/tidb/pkg/executor/sortexec.(*SortExec).fetchChunks\n\t/data/cs/tidb/pkg/executor/sortexec/sort.go:533\ngithub.com/pingcap/tidb/pkg/executor/sortexec.(*SortExec).Next\n\t/data/cs/tidb/pkg/executor/sortexec/sort.go:277\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/data/cs/tidb/pkg/executor/internal/exec/executor.go:403\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).next\n\t/data/cs/tidb/pkg/executor/adapter.go:1212\ngithub.com/pingcap/tidb/pkg/executor.(*recordSet).Next\n\t/data/cs/tidb/pkg/executor/adapter.go:158\ngithub.com/pingcap/tidb/pkg/server/internal/resultset.(*tidbResultSet).Next\n\t/data/cs/tidb/pkg/server/internal/resultset/resultset.go:64\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).writeChunks\n\t/data/cs/tidb/pkg/server/conn.go:2311\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).writeResultSet\n\t/data/cs/tidb/pkg/server/conn.go:2254\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt\n\t/data/cs/tidb/pkg/server/conn.go:2047\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery\n\t/data/cs/tidb/pkg/server/conn.go:1769\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\n\t/data/cs/tidb/pkg/server/conn.go:1343\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\n\t/data/cs/tidb/pkg/server/conn.go:1113\ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn\n\t/data/cs/tidb/pkg/server/server.go:737\nruntime.goexit\n\t/data/cs/go/src/runtime/asm_amd64.s:1650"]
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #52492 #45545

Problem Summary: improve log about stale-read query

#### Log

Before this PR, `timestamp` field in log is 0 when executing stale-read query.

This PR, `timestamp ` field is `stale-read ts`.

```log
[2024/04/11 13:40:12.617 +08:00] [INFO] [conn.go:1152] ["command dispatched failed"] [conn=2097154] [session_alias=] [connInfo="id:2097154, addr:127.0.0.1:49367 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="select /*+ MAX_EXECUTION_TIME(10), SET_VAR(TIKV_CLIENT_READ_TIMEOUT=5) */ * from t as of timestamp NOW() - INTERVAL 1 SECOND"] [txn_mode=PESSIMISTIC] [timestamp=449003916099584000] [err="[executor:3024]Query execution was interrupted, maximum statement execution time exceeded\ngithub.com/pingcap/errors.AddStack\n\t/Users/cs/code/goread/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/Users/cs/code/goread/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175\ngithub.com/pingcap/tidb/pkg/util/sqlkiller.(*SQLKiller).HandleSignal\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/util/sqlkiller/sqlkiller.go:68\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.(*executorKillerHandler).HandleSQLKillerSignal\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:251\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:409\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).next\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/executor/adapter.go:1209\ngithub.com/pingcap/tidb/pkg/executor.(*recordSet).Next\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/executor/adapter.go:158\ngithub.com/pingcap/tidb/pkg/server/internal/resultset.(*tidbResultSet).Next\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/internal/resultset/resultset.go:64\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).writeChunks\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/conn.go:2317\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).writeResultSet\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/conn.go:2260\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/conn.go:2053\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/conn.go:1775\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/conn.go:1349\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/conn.go:1113\ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn\n\t/Users/cs/code/goread/src/github.com/pingcap/tidb/pkg/server/server.go:737\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1197"]
```

#### Slow log

**Before This PR**

The slow log of stale-read query is the following, `Txn_start_ts` is 0, which is unexpected. 

```log
...
# Txn_start_ts: 0
...
select * from t;
```

**This PR**

```log
...
# Txn_start_ts: 448987604713472000
...
select * from t;
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

File: pkg/server/conn.go [hunk 1]
```diff
@@ -1139,17 +1139,23 @@ func (cc *clientConn) Run(ctx context.Context) {
...
-				if ctx := cc.getCtx(); ctx != nil && ctx.GetSessionVars() != nil && ctx.GetSessionVars().TxnCtx != nil {
-					startTS = ctx.GetSessionVars().TxnCtx.StartTS
+				var timestamp uint64
+				if ctx := cc.getCtx(); ctx != nil && ctx.GetSessionVars() != nil {
+					if ctx.GetSessionVars().TxnCtx != nil {
+						timestamp = ctx.GetSessionVars().TxnCtx.StartTS
+					}
+					if timestamp == 0 && ctx.GetSessionVars().StmtCtx != nil && ctx.GetSessionVars().StmtCtx.StaleReadTs > 0 {
+						// for state-read query.
+						timestamp = ctx.GetSessionVars().StmtCtx.StaleReadTs
```
Comment (zyguan) [inline pkg/server/conn.go:1149]: It's little weird to me to read a field of StmtCtx here, because when we reach here, the stmt should be [finished](https://github.com/pingcap/tidb/blob/master/pkg/executor/adapter.go#L1329) and related fields might be reset (like [IsStaleness](https://github.com/pingcap/tidb/blob/master/pkg/executor/adapter.go#L1382)).

How about to add a field to SessionVars (eg. LastStmtTS), then we can record it on FinishExecuteStmt and use it here (no need to resolve it from TxnCtx or StmtCtx). By this way, the logged timestamps are also consistent with those in slow logs.

Comment (crazycs520) [reply pkg/server/conn.go:1149]: The problem is, I can't record stale-read-ts on FinishExecuteStmt, since  https://github.com/pingcap/tidb/blob/6cca89c79459911201f7ce7429ab696ed18fcc1d/pkg/session/session.go#L768

will reset the `txnManager.ctxProvider`, and then in `FinishExecuteStmt `, I can't get stale-read-ts anymore.

Comment (crazycs520) [reply pkg/server/conn.go:1149]: Actually I don't understand why reset [IsStaleness](https://github.com/pingcap/tidb/blob/master/pkg/executor/adapter.go#L1382) here, since [IsStaleness] (https://github.com/pingcap/tidb/blob/19e61e2d35f0ca02d511637a87e590e3875832a7/pkg/executor/executor.go#L1995) will be reset in `ResetContextOfStmt`.

Comment (zyguan) [reply pkg/server/conn.go:1149]: > The problem is, I can't record stale-read-ts on FinishExecuteStmt

I think you've recored it in https://github.com/pingcap/tidb/pull/52484.

> I don't understand why reset IsStaleness here

The issue is not where to reset these fields, but accessing stmt scoped fields here is somehow improper.

Comment (crazycs520) [reply pkg/server/conn.go:1149]: > The issue is not where to reset these fields, but accessing stmt scoped fields here is somehow improper.

Yes, It is a little unreasonable here. How about store `StaleReadTs` in `TxnCtx` here, it maybe more reasonable?

Comment (zyguan) [reply pkg/server/conn.go:1149]: > How about to add a field to SessionVars (eg. LastStmtTS), then we can record it on FinishExecuteStmt and use it here (no need to resolve it from TxnCtx or StmtCtx). By this way, the logged timestamps are also consistent with those in slow logs.

This is my proposal. "we can record it on FinishExecuteStmt" means putting `sessVars.LastStmtTS = txnTS` in `FinishExecuteStmt`. Then we can use `timestamp = ctx.GetSessionVars().LastStmtTS` here.

Comment (crazycs520) [reply pkg/server/conn.go:1149]: I prefer to record `StaleReadTs` in `TxnCtx`. since I only care about the current statement, and this log is for current statement, so use `LastStmtTS` in this log is a little strange.

Comment (zyguan) [reply pkg/server/conn.go]: When you reach here, no stmt is running actually.

Comment (crazycs520) [reply pkg/server/conn.go]: I already move `StaleReadTs` to `TxnCtx`, I think it's better than put it in `StmtCtx` and `SessionVar`, since `StaleReadTs` is the concept of transaction.

File: pkg/executor/adapter.go [hunk 2]
```diff
@@ -1579,6 +1579,9 @@ func (a *ExecStmt) LogSlowQuery(txnTS uint64, succ bool, hasMoreResults bool) {
 	if !keyspace.IsKeyspaceNameEmpty(keyspaceName) {
 		keyspaceID = uint32(a.Ctx.GetStore().GetCodec().GetKeyspaceID())
 	}
+	if txnTS == 0 {
+		txnTS = sessVars.TxnCtx.StaleReadTs
+	}
```
Comment (zyguan) [inline pkg/executor/adapter.go:1584]: Here `txnTS` is somehow ambiguous, we may leave a comment to describe its current meaning and the following TODOs.

**Review by zyguan — APPROVED** [review]

File: pkg/executor/adapter.go (hunk 2 above)
Comment (crazycs520) [reply pkg/executor/adapter.go:1585]: nice catch, done.

File: pkg/executor/slow_query_sql_test.go [hunk 3]
```diff
@@ -158,6 +159,21 @@ func TestSlowQueryPrepared(t *testing.T) {
...
+	tk.MustExec("set @@tidb_read_staleness='-1'")
+	tk.MustQuery("select a from test.t_stale_read")
+	tk.MustExec("set @@tidb_read_staleness='0'")
+	t1 := time.Now()
+	tk.MustQuery(fmt.Sprintf("select a from test.t_stale_read as of timestamp '%s'", t1.Format("2006-1-2 15:04:05")))
+	tk.MustExec(fmt.Sprintf("start transaction read only as of timestamp '%v'", t1.Format("2006-1-2 15:04:05")))
+	tk.MustQuery("select a from test.t_stale_read")
+	tk.MustExec("commit")
+	require.Len(t, tk.MustQuery("SELECT query, txn_start_ts  FROM `information_schema`.`slow_query` "+
+		"where query like 'select % from %t_stale_read%' and Txn_start_ts > 0").Rows(), 3)
```
Comment (MyonKeminta) [inline pkg/executor/slow_query_sql_test.go:176]: Perhaps it's better to check the exact value.

**Review by MyonKeminta — APPROVED** [review]

File: pkg/executor/slow_query_sql_test.go (hunk 3 above)
Comment (crazycs520) [reply pkg/executor/slow_query_sql_test.go]: done.

**Review by qw4990 — APPROVED** [review]
