### PR TITLE
statistics: fix illegal bucket order when to merge global stats

### LINKED ISSUE #49023: analyze the same table concurrency may raise illegal bucket order error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create a partition table 
2. analyze partition table (job1)
3. wait for job1 in merge global stats, analyze the same table (job2)

### 2. What did you expect to see? (Required)
job1 and job2 can running success
### 3. What did you see instead (Required)
after job2 collect stats, job1 and job2 in merge global stats phase,  meget stats return `illegal bucket order` error
图片

### 4. What is your TiDB version? (Required)
```sql
[10:19:32]TiDB root:db0ios> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v7.5.0                                   |
| Edition: Community                                        |
| Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020 |
| Git Branch: heads/refs/tags/v7.5.0                        |
| UTC Build Time: 2023-11-24 08:50:14                       |
| GoVersion: go1.21.3                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #49023

Problem Summary:

### What changed and how does it work?

for better performance, we reuse memory to avoid allocating memory frequently. but bug will happen here. when we remove the empty bucket, use the non-empty bucket to overwrite it. but we cannot use the empty bucket to put into the pool. we wrongly put the non-empty bucket into the pool. it will lead to problems.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

We have tested with problem data. it will not raise this error.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

File: pkg/statistics/histogram.go [hunk 1]
```diff
@@ -1474,7 +1474,7 @@ func MergePartitionHist2GlobalHist(sc *stmtctx.StatementContext, hists []*Histog
 	tail := 0
 	for i := range buckets {
 		if buckets[i].Count != 0 {
-			buckets[tail] = buckets[i]
+			buckets[tail], buckets[i] = buckets[i], buckets[tail]
```
Comment (time-and-fate) [inline pkg/statistics/histogram.go:1477]: Suggest we add some comments to explain why the swap is necessary.

**Review by time-and-fate — APPROVED** [review]
