### PR TITLE
executor, util: fix spilling disk when oom.

### LINKED ISSUE #16696: Spilling disk with sort executor does not work
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```mysql
CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL
);

mysql> truncate table t;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values (1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t select * from t;
Query OK, 1 row affected (0.00 sec)
Records: 1  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 4 rows affected (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 8 rows affected (0.00 sec)
Records: 8  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 16 rows affected (0.00 sec)
Records: 16  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 32 rows affected (0.00 sec)
Records: 32  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 64 rows affected (0.00 sec)
Records: 64  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 128 rows affected (0.00 sec)
Records: 128  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 256 rows affected (0.00 sec)
Records: 256  Duplicates: 0  Warnings: 0

mysql> insert into t select * from t;
Query OK, 512 rows affected (0.01 sec)
Records: 512  Duplicates: 0  Warnings: 0
```

```mysql
mysql> explain analyze  select t1.a, t1.a +1 from t t1 join t t2 join t t3 order by t1.a;
+-----------------------------------+------------------+-----------+-----------+---------------+------------------------------------------------------------------------------------+----------------------------------------+-----------------------+---------+
| id                                | estRows          | actRows   | task      | access object | execution info                                                                     | operator info                          | memory                | disk    |
+-----------------------------------+------------------+-----------+-----------+---------------+------------------------------------------------------------------------------------+----------------------------------------+-----------------------+---------+
| Sort_10                           | 1000000000000.00 | 134217728 | root      |               | time:12.713145506s, loops:131073                                                   | test.t.a:asc                           | 3.21484375 GB         | 0 Bytes |
| └─Projection_12                   | 1000000000000.00 | 134217728 | root      |               | time:2.998321566s, loops:131073, Concurrency:4                                     | test.t.a, plus(test.t.a, 1)->Column#10 | 1.1401567347347736 GB | N/A     |
|   └─HashJoin_13                   | 1000000000000.00 | 134217728 | root      |               | time:2.814318715s, loops:131073, Concurrency:5, probe collision:0, build:105.04µs  | CARTESIAN inner join                   | 8.234375 KB           | 0 Bytes |
|     ├─TableReader_22(Build)       | 10000.00         | 512       | root      |               | time:5.177027ms, loops:2, rpc num: 1, rpc time:5.183946ms, proc keys:0             | data:TableFullScan_21                  | 4.2421875 KB          | N/A     |
|     │ └─TableFullScan_21          | 10000.00         | 512       | cop[tikv] | table:t3      | time:4.935532ms, loops:513                                                         | keep order:false, stats:pseudo         | N/A                   | N/A     |
|     └─HashJoin_15(Probe)          | 100000000.00     | 262144    | root      |               | time:7.162505ms, loops:257, Concurrency:5, probe collision:0, build:101.022µs      | CARTESIAN inner join                   | 8.234375 KB           | 0 Bytes |
|       ├─TableReader_20(Build)     | 10000.00         | 512       | root      |               | time:4.965126ms, loops:2, rpc num: 1, rpc time:5.186233ms, proc keys:0             | data:TableFullScan_19                  | 4.2421875 KB          | N/A     |
|       │ └─TableFullScan_19        | 10000.00         | 512       | cop[tikv] | table:t2      | time:4.940069ms, loops:513                                                         | keep order:false, stats:pseudo         | N/A                   | N/A     |
|       └─TableReader_18(Probe)     | 10000.00         | 512       | root      |               | time:4.619251ms, loops:2, rpc num: 1, rpc time:4.714003ms, proc keys:0             | data:TableFullScan_17                  | 4.2421875 KB          | N/A     |
|         └─TableFullScan_17        | 10000.00         | 512       | cop[tikv] | table:t1      | time:4.459083ms, loops:513                                                         | keep order:false, stats:pseudo         | N/A                   | N/A     |
+-----------------------------------+------------------+-----------+-----------+---------------+------------------------------------------------------------------------------------+----------------------------------------+-----------------------+---------+
10 rows in set (12.73 sec)
```
### 2. What did you expect to see?

The memory usage of Sort Executor is less than 1GB. The disk usage of Sort Executor is larger than 0.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

master (a9091029b) , and run `./tidb-server` directly 

source: https://asktug.com/t/topic/33681

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #16696 

Problem Summary: RowContainer can't spill disk sometimes.

### What is changed and how it works?

What's Changed:
1. Add a lock in rowContainer, for Get/Spill mutually exclusive.
2. Add an atomic variable in Tracker.actionMu, to avoid deadlock.

How it Works:

### Related changes

- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
- [Bug-fix] Make spilling disk work well.

### CODE REVIEW

File: util/chunk/row_container.go [hunk 1]
```diff
@@ -37,18 +37,18 @@ type RowContainer struct {
...
-	diskTracker        *disk.Tracker
-	actionSpill        *SpillDiskAction
-	onExceededCallback func(rowContainer *RowContainer)
+	memTracker  *memory.Tracker
+	diskTracker *disk.Tracker
+	actionSpill *SpillDiskAction
+	// status indicates that records status.
+	// 1 indicates the records is read-only.
+	// 2 indicates that the sql is oom and panic.
+	status uint32
```
Comment (XuHuaiyu) [inline util/chunk/row_container.go:50]:
``` go
type rowContainerStatus int
const(
	readOnly rowContainerStatus = iota
	alreadyOOM
)

status rowContainerStatus
```

File: executor/sort.go [hunk 2]
```diff
@@ -263,34 +274,34 @@ func (e *SortExec) fetchRowChunks(ctx context.Context) error {
...
-		}
-		if e.rowChunks.AlreadySpilled() {
-			e.rowChunks = chunk.NewRowContainer(retTypes(e), e.maxChunkSize)
-			e.rowChunks.GetMemTracker().AttachTo(e.memTracker)
-			e.rowChunks.GetMemTracker().SetLabel(rowChunksLabel)
-			e.rowChunks.SetOnExceededCallback(onExceededCallback)
-			e.spillAction.ResetOnceAndSetRowContainer(e.rowChunks)
-			e.rowChunks.GetDiskTracker().AttachTo(e.diskTracker)
-			e.rowChunks.GetDiskTracker().SetLabel(rowChunksLabel)
+		for err := e.rowChunks.Add(chk); err != nil; {
```
Comment (XuHuaiyu) [inline executor/sort.go:277]: We may get data race on e.rowChunks

File: executor/sort_test.go [hunk 3]
```diff
@@ -58,3 +59,26 @@ func (s *testSuite) TestSortInDisk(c *C) {
 	c.Assert(tk.Se.GetSessionVars().StmtCtx.DiskTracker.BytesConsumed(), Equals, int64(0))
 	c.Assert(tk.Se.GetSessionVars().StmtCtx.DiskTracker.MaxConsumed(), Greater, int64(0))
 }
+
+func (s *testSuite) TestIssue16696(c *C) {
```
Comment (glorv) [inline executor/sort_test.go:63]: This test is so much slow.  currently cost nearly 500s.
```
[2020-05-28T03:26:24.163Z] PASS: sort_test.go:63: testSuite.TestIssue16696	496.950s
```
[detail link](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/37651/pipeline/69)

File: executor/join.go [hunk 4]
```diff
@@ -414,17 +414,24 @@ func (e *HashJoinExec) handleUnmatchedRowsFromHashTableInDisk(workerID uint) {
 func (e *HashJoinExec) waitJoinWorkersAndCloseResultChan() {
 	e.joinWorkerWaitGroup.Wait()
 	if e.useOuterToBuild {
-		if e.rowContainer.alreadySpilled() {
+		inMemory := !e.rowContainer.alreadySpilledSafe()
+		if inMemory {
+			e.rowContainer.rowContainer.GetMutex().RLock()
+			inMemory = !e.rowContainer.alreadySpilledSafe()
```
Comment (XuHuaiyu) [inline executor/join.go:420]: Add a comment for why we need to double-check this

File: util/memory/tracker.go [hunk 5]
```diff
@@ -47,6 +47,7 @@ type Tracker struct {
 	actionMu struct {
 		sync.Mutex
 		actionOnExceed ActionOnExceed
+		actionDoing    uint32
```
Comment (XuHuaiyu) [inline util/memory/tracker.go:50]: add a comment for this

File: util/chunk/row_container.go [hunk 6]
```diff
@@ -229,6 +251,12 @@ func (a *SpillDiskAction) Action(t *memory.Tracker) {
 		logutil.BgLogger().Info("memory exceeds quota, spill to disk now.",
 			zap.Int64("consumed", t.BytesConsumed()), zap.Int64("quota", t.GetBytesLimit()))
 	})
+	if atomic.LoadUint32(&a.c.readOnly) == 1 {
+		err := a.c.spillToDisk()
+		if err != nil {
+			panic(err)
```
Comment (XuHuaiyu) [inline util/chunk/row_container.go:257]: Should we change `Action(t *Tracker)` to `Action(t *Tracker) error`

File: util/chunk/row_container.go [hunk 7]
```diff
@@ -229,6 +251,12 @@ func (a *SpillDiskAction) Action(t *memory.Tracker) {
 		logutil.BgLogger().Info("memory exceeds quota, spill to disk now.",
 			zap.Int64("consumed", t.BytesConsumed()), zap.Int64("quota", t.GetBytesLimit()))
 	})
+	if atomic.LoadUint32(&a.c.readOnly) == 1 {
+		err := a.c.spillToDisk()
```
Comment (SunRunAway) [inline util/chunk/row_container.go:255]: `memory exceeds quota, spill to disk now.`

This log is missing

File: executor/sort.go [hunk 8]
```diff
@@ -143,6 +143,8 @@ func (e *SortExec) Next(ctx context.Context, req *chunk.Chunk) error {
 	} else {
 		// Check whether the one partition is spilled.
 		// If the partition is in memory, use List.GetRow() to get better performance.
+		e.partitionList[0].GetMutex().RLock()
+		defer e.partitionList[0].GetMutex().RUnlock()
```
Comment (SunRunAway) [inline executor/sort.go:147]: We may introduce a method named `rowContainer.GetChunk`, which read a chunk from disk if it is spilled, or directly get a Chunk from its memory. After that, the mutex could not be exposed and the code below can be cleaner.

File: util/chunk/row_container.go (hunk 6 above)
Comment (wshwsh12) [reply util/chunk/row_container.go]: Should we ignore and log the error and try to find the next action ?

File: util/chunk/row_container.go (hunk 7 above)
Comment (wshwsh12) [reply util/chunk/row_container.go:255]: It logs when the rowContainer is exceeded.

**Comment by wshwsh12** [comment]
@SunRunAway @XuHuaiyu PTAL

File: executor/join.go [hunk 9]
```diff
@@ -346,43 +346,13 @@ func (e *HashJoinExec) handleJoinWorkerPanic(r interface{}) {
...
 // Concurrently handling unmatched rows from the hash table
-func (e *HashJoinExec) handleUnmatchedRowsFromHashTableInMemory(workerID uint) {
+func (e *HashJoinExec) handleUnmatchedRowsFromHashTable(workerID uint) {
 	ok, joinResult := e.getNewJoinResult(workerID)
 	if !ok {
 		return
 	}
 	numChks := e.rowContainer.NumChunks()
 	for i := int(workerID); i < numChks; i += int(e.concurrency) {
-		chk := e.rowContainer.GetChunk(i)
```
Comment (XuHuaiyu) [inline executor/join.go:356]: why remove this?

File: executor/sort.go [hunk 10]
```diff
@@ -527,8 +496,174 @@ func (e *TopNExec) doCompaction() error {
...
+	fallbackAction memory.ActionOnExceed
+	m              sync.Mutex
+}
+
+// Action sends a signal to trigger sortAndSpillToDisk method of RowContainer
+// and if it is already triggered before, call its fallbackAction.
+func (a *SortAndSpillDiskAction) Action(t *memory.Tracker, trigger *memory.Tracker) {
+	a.m.Lock()
+	defer a.m.Unlock()
+	if a.c.AlreadySpilledSafe() || a.c.GetMemTracker().BytesConsumed() == 0 {
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/sort.go:641]: Maybe create a SortedRowContainer in SortExec , and trigger oom-action in other place.
A spilled SortedRowContainer that consumed 0 bytes is meaningless. It can't add records anymore.

File: executor/sort.go [hunk 11]
```diff
@@ -527,8 +496,174 @@ func (e *TopNExec) doCompaction() error {
...
+	rowJ := c.GetList().GetRow(c.rowPtrs[j])
+	return c.lessRow(rowI, rowJ)
+}
+
+func (c *SortedRowContainer) initPointerAndSort(needLock bool) {
+	if needLock {
+		c.m.RLock()
+		defer c.m.RUnlock()
+	}
+	if c.rowPtrs != nil {
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/sort.go:572]: initPointerAndSort consume some bytes and trigger oom-action, maybe call the function again.

File: util/chunk/list.go [hunk 12]
```diff
@@ -117,10 +117,10 @@ func (l *List) Add(chk *Chunk) {
 		l.memTracker.Consume(l.chunks[chkIdx].MemoryUsage())
 		l.consumedIdx = chkIdx
 	}
-	l.memTracker.Consume(chk.MemoryUsage())
 	l.consumedIdx++
 	l.chunks = append(l.chunks, chk)
 	l.length += chk.NumRows()
+	l.memTracker.Consume(chk.MemoryUsage())
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply util/chunk/list.go:123]: Consume must execute after append chk to l.chunks, so the chunk can be spilled.

File: util/memory/tracker.go [hunk 13]
```diff
@@ -47,6 +47,7 @@ type Tracker struct {
 	actionMu struct {
 		sync.Mutex
 		actionOnExceed ActionOnExceed
+		actionDoing    uint32 // actionDoing indicates whether this tracker is running an oom-action.
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply util/memory/tracker.go]: 1. Used for all oom-action.

File: executor/join.go (hunk 9 above)
Comment (wshwsh12) [reply executor/join.go:356]: GetChunk thinks that the data is in memory, but the rowContainer may be spilled to disk.

File: executor/errors.go [hunk 14]
```diff
@@ -42,6 +42,7 @@ var (
 	ErrRoleNotGranted              = terror.ClassPrivilege.New(mysql.ErrRoleNotGranted, mysql.MySQLErrName[mysql.ErrRoleNotGranted])
 	ErrDeadlock                    = terror.ClassExecutor.New(mysql.ErrLockDeadlock, mysql.MySQLErrName[mysql.ErrLockDeadlock])
 	ErrQueryInterrupted            = terror.ClassExecutor.New(mysql.ErrQueryInterrupted, mysql.MySQLErrName[mysql.ErrQueryInterrupted])
+	ErrInsertToPartitionFailed     = terror.ClassExecutor.New(mysql.ErrInsertToPartitionFailed, mysql.MySQLErrName[mysql.ErrInsertToPartitionFailed])
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/errors.go]: Ok. I define the error in sort.go , because SortedRowContainer can't move to row_container.go

File: executor/sort.go [hunk 15]
```diff
@@ -327,8 +295,8 @@ func (e *SortExec) lessRow(rowI, rowJ chunk.Row) bool {
 
 // keyColumnsLess is the less function for key columns.
 func (e *SortExec) keyColumnsLess(i, j int) bool {
-	rowI := e.rowChunks.GetList().GetRow(e.rowPtrs[i])
-	rowJ := e.rowChunks.GetList().GetRow(e.rowPtrs[j])
+	rowI := e.rowChunks.GetList().GetRow(e.rowChunks.rowPtrs[i])
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/sort.go]: When calling sort.slice(.....) ,  the records must be in memory.

File: util/chunk/row_container.go [hunk 16]
```diff
@@ -60,7 +52,14 @@ func NewRowContainer(fieldType []*types.FieldType, chunkSize int) *RowContainer
 	return rc
 }
 
-func (c *RowContainer) spillToDisk() (err error) {
+// SpillToDisk spills data to disk.
+func (c *RowContainer) SpillToDisk(needLock bool) (err error) {
+	// Maybe the function call stack includes RowContainer.Add() and gets lock in that function,
+	// so we don't need to get the lock again.
+	if needLock {
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply util/chunk/row_container.go]: address comments.

File: util/chunk/row_container.go [hunk 17]
```diff
@@ -83,23 +82,28 @@ func (c *RowContainer) Reset() error {
...
 
 // AlreadySpilled indicates that records have spilled out into disk.
-func (c *RowContainer) AlreadySpilled() bool { return c.recordsInDisk != nil }
+func (c *RowContainer) AlreadySpilled() bool {
+	return c.recordsInDisk != nil
+}
 
 // AlreadySpilledSafe indicates that records have spilled out into disk. It's thread-safe.
-func (c *RowContainer) AlreadySpilledSafe() bool { return atomic.LoadUint32(&c.spilled) == 1 }
+func (c *RowContainer) AlreadySpilledSafe() bool {
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply util/chunk/row_container.go]: Action (I think this function is outside `RowContainer`) need use `AlreadySpilledSafe()` to check whether the rowContainer is spilled, to choose spilling or continue to find the next rowContainer.

File: executor/sort.go [hunk 18]
```diff
@@ -527,8 +496,174 @@ func (e *TopNExec) doCompaction() error {
...
+	sort.Slice(c.rowPtrs, c.keyColumnsLess)
+	c.GetMemTracker().Consume(int64(8 * cap(c.rowPtrs)))
+}
+
+func (c *SortedRowContainer) sortAndSpillToDisk(needLock bool) (err error) {
+	if needLock {
+		c.m.Lock()
+		defer c.m.Unlock()
+	}
+	c.initPointerAndSort(!needLock)
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/sort.go]: Maybe `initPointerAndSort` will call `tacker.Consume` but held write lock.

File: executor/sort.go [hunk 19]
```diff
@@ -264,35 +232,30 @@ func (e *SortExec) fetchRowChunks(ctx context.Context) error {
...
+				e.rowChunks.GetMemTracker().AttachTo(e.memTracker)
+				e.rowChunks.GetMemTracker().SetLabel(rowChunksLabel)
+				e.rowChunks.GetDiskTracker().AttachTo(e.diskTracker)
+				e.rowChunks.GetDiskTracker().SetLabel(rowChunksLabel)
+				e.spillAction.ResetRowContainer(e.rowChunks)
+				err = e.rowChunks.Add(chk)
+			}
+			if err != nil {
+				return err
+			}
```
Comment (fzhedu) [inline executor/sort.go:248]: return err directly.

File: executor/sort.go [hunk 20]
```diff
@@ -141,37 +128,18 @@ func (e *SortExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
-			for !req.IsFull() && e.Idx < len(e.rowPtrs) {
-				rowPtr := e.partitionRowPtrs[0][e.Idx]
-				row, err := e.partitionList[0].GetRow(rowPtr)
-				if err != nil {
-					return err
-				}
-				req.AppendRow(row)
-				e.Idx++
+		for !req.IsFull() && e.Idx < e.partitionList[0].NumRow() {
+			row, err := e.partitionList[0].GetRowByIdx(e.Idx)
```
Comment (fzhedu) [inline executor/sort.go:132]: use too many RLocks in GetRowByIdx. 
It is better to keep the lowest callee function thread-safe.

File: executor/sort.go [hunk 21]
```diff
@@ -264,35 +232,30 @@ func (e *SortExec) fetchRowChunks(ctx context.Context) error {
...
-			e.rowChunks.GetDiskTracker().SetLabel(rowChunksLabel)
+			if chunk.ErrInsertToPartitionFailed.Equal(err) {
+				e.rowChunks.GetMemTracker().Consume(int64(8 * cap(e.rowChunks.M.RowPtrs)))
+				e.partitionList = append(e.partitionList, e.rowChunks)
+				e.rowChunks = chunk.NewSortedRowContainer(fields, e.maxChunkSize, byItemsDesc, e.keyColumns, e.keyCmpFuncs)
+				e.rowChunks.GetMemTracker().AttachTo(e.memTracker)
+				e.rowChunks.GetMemTracker().SetLabel(rowChunksLabel)
+				e.rowChunks.GetDiskTracker().AttachTo(e.diskTracker)
+				e.rowChunks.GetDiskTracker().SetLabel(rowChunksLabel)
+				e.spillAction.ResetRowContainer(e.rowChunks)
```
Comment (fzhedu) [inline executor/sort.go]: they are different from the Line 215~222, may be can in a function.

File: executor/sort.go [hunk 22]
```diff
@@ -264,35 +232,30 @@ func (e *SortExec) fetchRowChunks(ctx context.Context) error {
...
+				err = e.rowChunks.Add(chk)
```
Comment (fzhedu) [inline executor/sort.go:244]: too many locks in the calling line.

**Comment by fzhedu** [comment]
`Add a lock in rowContainer, for Get/Spill mutually exclusive.`
There are too many lock when calling the lowest function in container.

File: util/chunk/row_container.go [hunk 23]
```diff
@@ -185,11 +212,11 @@ func (c *RowContainer) GetDiskTracker() *disk.Tracker {
 
 // Close close the RowContainer
 func (c *RowContainer) Close() (err error) {
-	if c.AlreadySpilled() {
-		err = c.recordsInDisk.Close()
-		c.recordsInDisk = nil
+	if c.alreadySpilled() {
```
Comment (SunRunAway) [inline util/chunk/row_container.go:215]: All the usage of `alreadySpilled` should be read locked because it touches `c.m.recordsInDisk`

File: util/chunk/row_container.go [hunk 24]
```diff
@@ -28,149 +29,175 @@ import (
...
 	rc.memTracker = li.memTracker
 	rc.diskTracker = disk.NewTracker(stringutil.StringerStr("RowContainer"), -1)
 	return rc
 }
 
-func (c *RowContainer) spillToDisk() (err error) {
-	N := c.records.NumChunks()
-	c.recordsInDisk = NewListInDisk(c.records.FieldTypes())
-	c.recordsInDisk.diskTracker.AttachTo(c.diskTracker)
+// SpillToDisk spills data to disk.
```
Comment (SunRunAway) [inline util/chunk/row_container.go:62]: Document that this function may be called in parallel.

File: util/chunk/row_container.go (hunk 23 above)
Comment (SunRunAway) [reply util/chunk/row_container.go:215]: Because `SpillToDisk` may be called after Close happens, this situation should be considered.

File: util/chunk/row_container.go [hunk 25]
```diff
@@ -28,149 +29,175 @@ import (
...
-
-// GetList returns the list of in memory records.
-func (c *RowContainer) GetList() *List {
-	return c.records
+func (c *RowContainer) GetChunk(chkIdx int) (*Chunk, error) {
+	c.m.RLock()
+	defer c.m.RUnlock()
+	if !c.alreadySpilled() {
+		return c.m.records.GetChunk(chkIdx), nil
+	}
```
Comment (SunRunAway) [inline util/chunk/row_container.go:177]: Is Checking `spillError` necessary here?

File: util/chunk/row_container.go [hunk 26]
```diff
@@ -28,149 +29,175 @@ import (
...
+	chk := NewChunkWithCapacity(c.m.records.FieldTypes(), c.m.records.maxChunkSize)
```
Comment (SunRunAway) [inline util/chunk/row_container.go:178]:
```suggestion
	chk := NewChunkWithCapacity(c.m.records.FieldTypes(), c.m.recordsInDisk.NumRowsOfChunk(chkIdx))
```

File: util/chunk/row_container.go [hunk 27]
```diff
@@ -28,149 +29,175 @@ import (
...
+	offsets := c.m.recordsInDisk.offsets[chkIdx]
+	for rowIdx := range offsets {
+		row, err := c.m.recordsInDisk.GetRow(RowPtr{ChkIdx: uint32(chkIdx), RowIdx: uint32(rowIdx)})
+		if err != nil {
+			return chk, err
+		}
+		chk.AppendRow(row)
+	}
```
Comment (SunRunAway) [inline util/chunk/row_container.go:186]: Would it be better to put this logic into a method in `recordsInDisk.GetChunk` so it's easy for us to maintain if we refactor or optimize the internal data format of `recordsInDisk` in future?

File: util/chunk/row_container.go [hunk 28]
```diff
@@ -239,17 +282,181 @@ func (a *SpillDiskAction) SetFallback(fallback memory.ActionOnExceed) {
...
+// ResetRowContainer resets the spill action and sets the RowContainer for the SpillDiskAction.
+func (a *SpillDiskAction) ResetRowContainer(c *RowContainer) {
 	a.m.Lock()
 	defer a.m.Unlock()
-	a.once = sync.Once{}
+	a.c = c
+}
+
+// ErrInsertToPartitionFailed indicate that the SortedRowContainer is sorted and prohibit inserting data.
+var ErrInsertToPartitionFailed = terror.ClassExecutor.New(1, "Insert the records unsuccessfully. The SortedRowContainer is sorted.")
```
Comment (SunRunAway) [inline util/chunk/row_container.go:293]: The word `Partition` is used in sort executor, but it's confused for code readers when reading this package. I think `ErrCannotAddBecauseSorted` would be better. Besides, a simple `errors.New` may be more suitable.

```suggestion
var ErrCannotAddBecauseSorted = errors.New("can not add because sorted")
```

File: util/chunk/row_container.go [hunk 29]
```diff
@@ -239,17 +282,181 @@ func (a *SpillDiskAction) SetFallback(fallback memory.ActionOnExceed) {
...
+func (c *SortedRowContainer) keyColumnsLess(i, j int) bool {
+	rowI := c.m.records.GetRow(c.ptrM.rowPtrs[i])
+	rowJ := c.m.records.GetRow(c.ptrM.rowPtrs[j])
+	return c.lessRow(rowI, rowJ)
 }
 
-// ResetOnceAndSetRowContainer resets the spill action and sets the RowContainer for the SpillDiskAction.
-func (a *SpillDiskAction) ResetOnceAndSetRowContainer(c *RowContainer) {
+// InitPointersAndSort inits pointers and sorts the records.
+func (c *SortedRowContainer) InitPointersAndSort() {
```
Comment (SunRunAway) [inline util/chunk/row_container.go:351]: `InitPointers` may confuse the code readers because the caller does not care the unexported `rowPtrs` field.

```suggestion
func (c *SortedRowContainer) Sort() {
```

File: util/chunk/row_container.go [hunk 30]
```diff
@@ -239,17 +282,181 @@ func (a *SpillDiskAction) SetFallback(fallback memory.ActionOnExceed) {
...
+	c.ptrM.RLock()
+	defer c.ptrM.RUnlock()
+	if c.ptrM.rowPtrs != nil {
+		return ErrInsertToPartitionFailed
+	}
+	return c.RowContainer.Add(chk)
+}
+
+// GetRowByIdx returns the row the idx pointed to.
+func (c *SortedRowContainer) GetRowByIdx(idx int) (Row, error) {
```
Comment (SunRunAway) [inline util/chunk/row_container.go:388]: How about `GetSortedRow`?

File: util/chunk/row_container.go [hunk 31]
```diff
@@ -220,15 +251,27 @@ func (a *SpillDiskAction) Action(t *memory.Tracker) {
...
+			return
+		}
 		if a.fallbackAction != nil {
 			a.fallbackAction.Action(t)
 		}
-	}
-	a.once.Do(func() {
-		atomic.StoreUint32(&a.c.exceeded, 1)
+	} else {
+		// TODO: Refine processing for various errors. Return or Panic.
```
Comment (SunRunAway) [inline util/chunk/row_container.go:261]: Can this TODO be removed now?

File: util/chunk/row_container.go [hunk 32]
```diff
@@ -239,17 +282,181 @@ func (a *SpillDiskAction) SetFallback(fallback memory.ActionOnExceed) {
...
+	defer a.m.Unlock()
+	if a.c.AlreadySpilledSafe() || a.c.GetMemTracker().BytesConsumed() == 0 {
+		if !t.CheckExceed() {
+			return
+		}
+		if a.fallbackAction != nil {
+			a.fallbackAction.Action(t)
+		}
+	} else {
+		// TODO: Refine processing various errors. Return or Panic.
```
Comment (SunRunAway) [inline util/chunk/row_container.go:433]: Can this TODO be removed now?

File: util/chunk/row_container_test.go [hunk 33]
```diff
@@ -30,15 +30,15 @@ func (r *rowContainerTestSuite) TestNewRowContainer(c *check.C) {
 	fields := []*types.FieldType{types.NewFieldType(mysql.TypeLonglong)}
 	rc := NewRowContainer(fields, 1024)
 	c.Assert(rc, check.NotNil)
-	c.Assert(rc.AlreadySpilled(), check.Equals, false)
+	c.Assert(rc.AlreadySpilledSafe(), check.Equals, false)
 }
 
 func (r *rowContainerTestSuite) TestSel(c *check.C) {
```
Comment (SunRunAway) [inline util/chunk/row_container_test.go:36]: Could you add some tests for `SortedRowContainer`?

File: util/chunk/row_container.go (hunk 27 above)
Comment (wshwsh12) [reply util/chunk/row_container.go]: ok

File: executor/sort.go [hunk 34]
```diff
@@ -264,35 +232,30 @@ func (e *SortExec) fetchRowChunks(ctx context.Context) error {
...
+			}
+			if err != nil {
+				return err
+			}
 		}
 	}
 	if e.rowChunks.NumRow() > 0 {
-		e.generatePartition()
+		e.rowChunks.InitPointersAndSort()
+		e.rowChunks.GetMemTracker().Consume(int64(8 * e.rowChunks.NumRow()))
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/sort.go]: Yes.

File: util/chunk/row_container.go (hunk 23 above)
Comment (wshwsh12) [reply util/chunk/row_container.go:202]: Ok, I add RLock in Close().

File: executor/join.go [hunk 35]
```diff
@@ -415,7 +421,7 @@ func (e *HashJoinExec) handleUnmatchedRowsFromHashTableInDisk(workerID uint) {
 func (e *HashJoinExec) waitJoinWorkersAndCloseResultChan() {
 	e.joinWorkerWaitGroup.Wait()
 	if e.useOuterToBuild {
-		if e.rowContainer.alreadySpilled() {
+		if e.rowContainer.alreadySpilledSafe() {
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/join.go]: Addressed.

File: executor/benchmark_test.go [hunk 36]
```diff
@@ -863,7 +864,8 @@ func benchmarkHashJoinExecWithCase(b *testing.B, casTest *hashJoinTestCase) {
 			totalRow += chk.NumRows()
 		}
 
-		if spilled := exec.rowContainer.alreadySpilled(); spilled != casTest.disk {
+		time.Sleep(200 * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/benchmark_test.go:868]: I move the sleeping out of the timer.....

File: executor/executor_pkg_test.go [hunk 37]
```diff
@@ -312,11 +313,20 @@ func (s *testExecSerialSuite) TestSortSpillDisk(c *C) {
 		}
 	}
 	// Test 2 partitions and all data in disk.
-	c.Assert(len(exec.partitionList), Equals, 2)
-	c.Assert(exec.partitionList[0].AlreadySpilled(), Equals, true)
-	c.Assert(exec.partitionList[1].AlreadySpilled(), Equals, true)
-	c.Assert(exec.partitionList[0].NumRow(), Equals, 1024)
-	c.Assert(exec.partitionList[1].NumRow(), Equals, 1024)
+	// Now spilling is parallel.
+	time.Sleep(200 * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/executor_pkg_test.go:317]: How to remove the sleep?

File: util/chunk/row_container_test.go (hunk 33 above)
Comment (wshwsh12) [reply util/chunk/row_container_test.go:37]: Addressed.

File: executor/executor_pkg_test.go [hunk 38]
```diff
@@ -312,11 +313,20 @@ func (s *testExecSerialSuite) TestSortSpillDisk(c *C) {
...
+	if len(exec.partitionList) == 2 {
+		c.Assert(len(exec.partitionList), Equals, 2)
+		c.Assert(exec.partitionList[0].AlreadySpilledSafe(), Equals, true)
+		c.Assert(exec.partitionList[1].AlreadySpilledSafe(), Equals, true)
+		c.Assert(exec.partitionList[0].NumRow(), Equals, 1024)
+		c.Assert(exec.partitionList[1].NumRow(), Equals, 1024)
+	} else {
```
[the remark this answers is not in the document]
Comment (wshwsh12) [reply executor/executor_pkg_test.go:324]: How to make a definite result...  Maybe the rowContainer has added 2048 line and then spilled to disk... Spilling is parallel and can't be controlled well in test... Any idea？

File: executor/benchmark_test.go [hunk 39]
```diff
@@ -839,6 +840,40 @@ func benchmarkHashJoinExecWithCase(b *testing.B, casTest *hashJoinTestCase) {
 	dataSource1 := buildMockDataSource(opt1)
 	dataSource2 := buildMockDataSource(opt2)
 
+	{ // Check Spill.
+		exec := prepare4HashJoin(casTest, dataSource1, dataSource2)
```
Comment (SunRunAway) [inline executor/benchmark_test.go:844]: Please avoid copy and paste code.

File: executor/benchmark_test.go (hunk 36 above)
[the remark this answers is not in the document]
Comment (SunRunAway) [reply executor/benchmark_test.go:864]: Could you avoid this sleep?

File: executor/sort.go (hunk 20 above)
Comment (wshwsh12) [reply executor/sort.go]:
```
GetSortedRow(idx)
BenchmarkSortExec/(rows:300000,_orderBy:[0_1],_ndvs:_[0_0])-8         	       5	 236137816 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0_1],_ndvs:_[1_0])-8         	       4	 306196869 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0],_ndvs:_[1_0])-8           	      21	  53316005 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[1],_ndvs:_[1_0])-8           	       5	 234143878 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0_1],_ndvs:_[10000_0])-8     	       4	 285625359 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0],_ndvs:_[10000_0])-8       	       5	 214384946 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[1],_ndvs:_[10000_0])-8       	       5	 242921345 ns/op

Master
BenchmarkSortExec/(rows:300000,_orderBy:[0_1],_ndvs:_[0_0])-8         	       6	 202542442 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0_1],_ndvs:_[1_0])-8         	       4	 259148025 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0],_ndvs:_[1_0])-8           	      55	  20992548 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[1],_ndvs:_[1_0])-8           	       6	 191120944 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0_1],_ndvs:_[10000_0])-8     	       5	 238929357 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[0],_ndvs:_[10000_0])-8       	       6	 179271168 ns/op
BenchmarkSortExec/(rows:300000,_orderBy:[1],_ndvs:_[10000_0])-8       	       6	 193617344 ns/op
```

File: util/chunk/row_container.go [hunk 40]
```diff
@@ -239,17 +277,200 @@ func (a *SpillDiskAction) SetFallback(fallback memory.ActionOnExceed) {
...
+// NewSortedRowContainer creates a new SortedRowContainer in memory.
+func NewSortedRowContainer(fieldType []*types.FieldType, chunkSize int, ByItemsDesc []bool,
+	keyColumns []int, keyCmpFuncs []CompareFunc) *SortedRowContainer {
+	return &SortedRowContainer{RowContainer: NewRowContainer(fieldType, chunkSize),
+		ByItemsDesc: ByItemsDesc, keyColumns: keyColumns, keyCmpFuncs: keyCmpFuncs}
+}
+
+// Close close the SortedRowContainer
+func (c *SortedRowContainer) Close() error {
+	c.GetMemTracker().Consume(int64(-8 * cap(c.ptrM.rowPtrs)))
```
Comment (SunRunAway) [inline util/chunk/row_container.go:323]: Should set `c.ptrM.rowPtrs` to `nil` to prevent the unrelease of `SortedRowContainer `.

File: util/chunk/row_container.go [hunk 41]
```diff
@@ -28,149 +28,161 @@ import (
...
 	rc.memTracker = li.memTracker
 	rc.diskTracker = disk.NewTracker(stringutil.StringerStr("RowContainer"), -1)
 	return rc
 }
 
-func (c *RowContainer) spillToDisk() (err error) {
-	N := c.records.NumChunks()
-	c.recordsInDisk = NewListInDisk(c.records.FieldTypes())
-	c.recordsInDisk.diskTracker.AttachTo(c.diskTracker)
+// SpillToDisk spills data to disk. This function maybe called in parallel.
```
Comment (SunRunAway) [inline util/chunk/row_container.go:61]:
```suggestion
// SpillToDisk spills data to disk. This function may be called in parallel.
```

File: executor/sort.go [hunk 42]
```diff
@@ -48,48 +50,35 @@ type SortExec struct {
...
+	rowChunks *chunk.SortedRowContainer
 
 	memTracker  *memory.Tracker
 	diskTracker *disk.Tracker
 
 	// partitionList is the chunks to store row values for partitions.
-	partitionList []*chunk.RowContainer
-	// partitionRowPtrs store the sorted RowPtrs for each row for partitions.
-	partitionRowPtrs [][]chunk.RowPtr
+	partitionList []*chunk.SortedRowContainer
```
Comment (XuHuaiyu) [inline executor/sort.go:59]: add a comment that every partition is a sorted chunk?

File: util/chunk/row_container.go [hunk 43]
```diff
@@ -28,149 +31,170 @@ import (
...
+		// RWMutex guarantees spill and get operator for rowContainer is mutually exclusive.
+		sync.RWMutex
+		// records stores the chunks in memory.
+		records *List
+		// recordsInDisk stores the chunks in disk.
+		recordsInDisk *ListInDisk
+		// spillError stores the error when spilling.
+		spillError error
+		// spilled indicate whether the RowContainer is spilled.
+		spilled uint32
```
Comment (XuHuaiyu) [inline util/chunk/row_container.go:44]: We need to add comment to explain that we need to use `atomic` when trying to modify `spilled`

**Comment by wshwsh12** [comment]
@XuHuaiyu  All comments have been addressed. PTAL again.
