### PR TITLE
expression, executor: fix unexpectedly modifying `Flen` and `Decimal` of `CorrelatedColumn`

### LINKED ISSUE #29412: register error after initialized is prohibited
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[1.txt](https://github.com/pingcap/tidb/files/7467505/1.txt)
```sql
source 1.txt
select sum( distinct `col_int_undef_unsigned`) as x from table_75_latin1_undef as t1 having x > some (select `col_float_undef_signed` from table_10_latin1_undef as t2 where x in (col_double_undef_signed));
/*
+------------------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows | task      | access object | operator info                                                                                                                                                                   |
+------------------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Selection_13                       | 0.64    | root      |               | Column#55                                                                                                                                                                       |
| └─Apply_15                         | 0.80    | root      |               | CARTESIAN semi join, other cond:or(gt(cast(Column#55, double BINARY), Column#83), if(ne(Column#84, 0), NULL, 0))                                                                |
|   ├─Selection_17(Build)            | 0.80    | root      |               | if(isnull(Column#55), NULL, 1)                                                                                                                                                  |
|   │ └─StreamAgg_19                 | 1.00    | root      |               | funcs:sum(distinct Column#92)->Column#55                                                                                                                                        |
|   │   └─Projection_44              | 75.00   | root      |               | cast(rs.table_75_latin1_undef.col_int_undef_unsigned, decimal(48,31) BINARY)->Column#92                                                                                         |
|   │     └─TableReader_23           | 75.00   | root      |               | data:TableFullScan_22                                                                                                                                                           |
|   │       └─TableFullScan_22       | 75.00   | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                                                                                                  |
|   └─Selection_24(Probe)            | 0.80    | root      |               | ne(Column#85, 0)                                                                                                                                                                |
|     └─StreamAgg_39                 | 1.00    | root      |               | funcs:min(Column#89)->Column#83, funcs:sum(Column#90)->Column#84, funcs:count(Column#91)->Column#85                                                                             |
|       └─TableReader_40             | 1.00    | root      |               | data:StreamAgg_28                                                                                                                                                               |
|         └─StreamAgg_28             | 1.00    | cop[tikv] |               | funcs:min(rs.table_10_latin1_undef.col_float_undef_signed)->Column#89, funcs:sum(isnull(rs.table_10_latin1_undef.col_float_undef_signed))->Column#90, funcs:count(1)->Column#91 |
|           └─Selection_38           | 8.00    | cop[tikv] |               | eq(cast(Column#55, double BINARY), rs.table_10_latin1_undef.col_double_undef_signed)                                                                                            |
|             └─TableFullScan_37     | 10.00   | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                                                                                                  |
+------------------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
*/
```

### 2. What did you expect to see? (Required)
successfully
### 3. What did you see instead (Required)
ERROR 1105 (HY000): register error after initialized is prohibited
### 4. What is your TiDB version? (Required)

Release Version: v5.3.0-alpha-1304-ga96deabe7
Edition: Community
Git Commit Hash: a96deabe7e46385722cf96f7fc254de86fd5bd1a
Git Branch: master
UTC Build Time: 2021-11-02 05:14:52
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #29412

Problem Summary:

In changes of https://github.com/pingcap/tidb/pull/26651, the `Column` should be copied. But the `CorrelatedColumn` case is missed.

### What is changed and how it works?

Deep copy `CorrelatedColumn`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: expression/expression.go [hunk 1]
```diff
@@ -1383,6 +1383,11 @@ func PropagateType(evalType types.EvalType, args ...Expression) {
 				newCol.(*Column).RetType = col.RetType.Clone()
 				args[0] = newCol
 			}
+			if col, ok := args[0].(*CorrelatedColumn); ok {
+				newCol := col.Clone()
+				newCol.(*CorrelatedColumn).RetType = col.RetType.Clone()
+				args[0] = newCol
```
Comment (time-and-fate) [inline expression/expression.go:1389]: Repeating the same code twice may be a little ugly. We may need a `SetType()` or `DeepCopy()` method on `Expression` to avoid this.

**Review by wshwsh12 — APPROVED** [review]

**Review by winoros — APPROVED** [review]
