### PR TITLE
disttask: fix failed step is taken as success

### LINKED ISSUE #49950: distask scheduler takes step success while it's failed actually
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

as we're checking whether task step fails or success using 2 sql, if the task fail in the middle, we will take it as success and switch task to next step. **if it's already the last step, the task will be marked as success incorrectly**
https://github.com/pingcap/tidb/blob/7af117d818dba9472a0b09b6445a46426865374d/pkg/disttask/framework/scheduler/scheduler.go#L322-L336

it might cause some real-tikv case fail
https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_check2/runs/381/nodes/107/steps/598/log/?start=0
```
[2023/12/29 11:06:09.434 +00:00] [INFO] [client.go:639] ["[pd] service mode changed"] [old-mode=UNKNOWN_SVC_MODE] [new-mode=PD_SVC_MODE]
    scheduler.go:387: Unexpected call to *mocklocal.MockTiKVModeSwitcher.ToNormalMode([context.Background.WithValue(type util.RequestSourceKeyType, val <not Stringer>).WithCancel.WithValue(type metric.ctxKeyType, val <not Stringer>)]) at pkg/disttask/importinto/scheduler.go:387 because: 
        expected call at tests/realtikvtest/importintotest/import_into_test.go:812 has already been called the max number of times
        expected call at tests/realtikvtest/importintotest/import_into_test.go:845 has already been called the max number of times
        expected call at tests/realtikvtest/importintotest/import_into_test.go:880 has already been called the max number of times
```

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #49950

Problem Summary:

### What changed and how does it work?
- see issue. also fix some flaky test
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/handle/handle_test.go [hunk 1]
```diff
@@ -52,6 +53,8 @@ func TestHandle(t *testing.T) {
 	mgr := storage.NewTaskManager(pool)
 	storage.SetTaskManager(mgr)
 
+	testutil.WaitNodeRegistered(t, ctx)
```
Comment (ywqzzy) [inline pkg/disttask/framework/handle/handle_test.go:56]: also in planner_test

**Review by ywqzzy — APPROVED** [review]

File: pkg/disttask/framework/scheduler/scheduler_nokit_test.go [hunk 2]
```diff
@@ -0,0 +1,40 @@
+// Copyright 2023 PingCAP, Inc.
```
Comment (okJiang) [inline pkg/disttask/framework/scheduler/scheduler_nokit_test.go:1]:
```suggestion
// Copyright 2024 PingCAP, Inc.
```

File: pkg/disttask/framework/scheduler/interface.go [hunk 3]
```diff
@@ -59,7 +59,7 @@ type TaskManager interface {
 	// we only consider pending/running subtasks, subtasks related to revert are
 	// not considered.
 	GetUsedSlotsOnNodes(ctx context.Context) (map[string]int, error)
-	GetSubtaskInStatesCnt(ctx context.Context, taskID int64, states ...proto.SubtaskState) (int64, error)
+	GetSubtaskCntByStates(ctx context.Context, taskID int64, step proto.Step) (map[proto.SubtaskState]int64, error)
```
Comment (okJiang) [inline pkg/disttask/framework/scheduler/interface.go:62]:
```suggestion
	GetSubtaskCntByStep(ctx context.Context, taskID int64, step proto.Step) (map[proto.SubtaskState]int64, error)
```

File: pkg/disttask/framework/scheduler/scheduler.go [hunk 4]
```diff
@@ -240,12 +240,13 @@ func (s *BaseScheduler) onCancelling() error {
 // handle task in pausing state, cancel all running subtasks.
 func (s *BaseScheduler) onPausing() error {
 	logutil.Logger(s.logCtx).Info("on pausing state", zap.Stringer("state", s.Task.State), zap.Int64("step", int64(s.Task.Step)))
-	cnt, err := s.taskMgr.GetSubtaskInStatesCnt(s.ctx, s.Task.ID, proto.SubtaskStateRunning, proto.SubtaskStatePending)
+	cntByStates, err := s.taskMgr.GetSubtaskCntByStates(s.ctx, s.Task.ID, s.Task.Step)
```
Comment (okJiang) [inline pkg/disttask/framework/scheduler/scheduler.go:243]:
```suggestion
	state2Cnt, err := s.taskMgr.GetSubtaskCntByStep(s.ctx, s.Task.ID, s.Task.Step)
```

File: pkg/disttask/framework/scheduler/scheduler.go [hunk 5]
```diff
@@ -727,6 +729,11 @@ func (s *BaseScheduler) WithNewTxn(ctx context.Context, fn func(se sessionctx.Co
 	return s.taskMgr.WithNewTxn(ctx, fn)
 }
 
+func (*BaseScheduler) isStepSucceed(cntByStates map[proto.SubtaskState]int64) bool {
```
Comment (okJiang) [inline pkg/disttask/framework/scheduler/scheduler.go:732]:
```suggestion
func isSucceed(cntByStates map[proto.SubtaskState]int64) bool {
```

No step input

**Review by okJiang — COMMENTED** [review]
rest lgtm

File: pkg/disttask/framework/scheduler/scheduler.go (hunk 5 above)
Comment (D3Hunter) [reply pkg/disttask/framework/scheduler/scheduler.go:732]: the input is subtask count map for current step

File: pkg/disttask/framework/scheduler/interface.go (hunk 3 above)
Comment (D3Hunter) [reply pkg/disttask/framework/scheduler/interface.go:62]: the `ByStates` means group by state. will change to InStates to avoid conflict with normal `ByXXX`

File: pkg/disttask/framework/scheduler/scheduler.go (hunk 5 above)
Comment (okJiang) [reply pkg/disttask/framework/scheduler/scheduler.go:732]: > the input is subtask count map for current step

For the current function, we don't know this background🤔

File: pkg/disttask/framework/scheduler/interface.go (hunk 3 above)
Comment (okJiang) [reply pkg/disttask/framework/scheduler/interface.go:62]: Indeed exist confusion

> conflict with normal ByXXX

File: pkg/disttask/framework/scheduler/scheduler.go (hunk 5 above)
Comment (okJiang) [reply pkg/disttask/framework/scheduler/scheduler.go:732]: I know the input. But the input that make sense of `isStepSucceed` should be task——step of task is succeed.

File: pkg/disttask/framework/scheduler/interface.go (hunk 3 above)
Comment (tangenta) [reply pkg/disttask/framework/scheduler/interface.go:62]: GetSubtaskCntGroupByStates?

File: pkg/disttask/framework/scheduler/scheduler.go (hunk 5 above)
Comment (D3Hunter) [reply pkg/disttask/framework/scheduler/scheduler.go:732]: we're in task scheduler already, `isStepSucceed` is clear enough

File: pkg/disttask/framework/scheduler/interface.go (hunk 3 above)
Comment (D3Hunter) [reply pkg/disttask/framework/scheduler/interface.go]: https://github.com/pingcap/tidb/pull/49971/commits/6d9a55aa98ce7582a2fe91bb3065127b7d6e1ab2

**Review by tangenta — APPROVED** [review]

**Review by okJiang — APPROVED** [review]
