### PR TITLE
expression: fix unexpected error msg for cast string to decimal

### LINKED ISSUE #44274: ERROR 1265 (01000): Data truncated for column '%s' at row %d
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```SQL
CREATE TABLE t1 (c1 TEXT);
INSERT INTO t1 VALUES ('a');
UPDATE t1 SET c1 = CAST('61QW' AS DECIMAL);
```
### 2. What did you expect to see? (Required)
The error message should not have the %s, %d.
### 3. What did you see instead (Required)
```SQL
ERROR 1265 (01000): Data truncated for column '%s' at row %d
```
### 4. What is your TiDB version? (Required)

Release Version: v7.0.0
Edition: Community
Git Commit Hash: 7376954cd868dbc44fc3015c9ef89c53749339a7
Git Branch: heads/refs/tags/v7.0.0
UTC Build Time: 2023-03-29 13:32:13
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #44274

Problem Summary: When you use `ErrTruncated`, you should use it like [here](https://github.com/pingcap/tidb/blob/master/ddl/column.go#L1423). Otherwise the err msg will got `%s %d`

For cast, should use `ErrTruncatedWrongVal`, just like mysql.
```
MySQL [test]> select CAST('61QW' AS DECIMAL);
+-------------------------+
| CAST('61QW' AS DECIMAL) |
+-------------------------+
|                      61 |
+-------------------------+
1 row in set, 1 warning (0.000 sec)

MySQL [test]> show warnings;
+---------+------+-------------------------------------------+
| Level   | Code | Message                                   |
+---------+------+-------------------------------------------+
| Warning | 1292 | Truncated incorrect DECIMAL value: '61QW' |
+---------+------+-------------------------------------------+
1 row in set (0.001 sec)
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: expression/builtin_cast.go [hunk 1]
```diff
@@ -1440,7 +1440,11 @@ func (b *builtinCastStringAsDecimalSig) evalDecimal(row chunk.Row) (res *types.M
 	res = new(types.MyDecimal)
 	sc := b.ctx.GetSessionVars().StmtCtx
 	if !(b.inUnion && mysql.HasUnsignedFlag(b.tp.GetFlag()) && isNegative) {
-		err = sc.HandleTruncate(res.FromString([]byte(val)))
+		err = res.FromString([]byte(val))
```
Comment (Defined2014) [inline expression/builtin_cast.go:1443]:
```suggestion
		err = sc.HandleTruncate(res.FromString([]byte(val)))
```
Maybe this is better? We handled `TruncateAsWarning` and `IgnoreTruncate` in `HandleTruncate` function.

File: expression/integration_test/integration_test.go [hunk 2]
```diff
@@ -2059,3 +2059,15 @@ func TestIssue41986(t *testing.T) {
 	// shouldn't report they can't find column error and return the right result.
 	tk.MustQuery("SELECT GROUP_CONCAT(effective_date order by stlmnt_hour DESC) FROM ( SELECT (COALESCE(pct.clearing_time, 0)/3600000) AS stlmnt_hour ,COALESCE(pct.effective_date, '1970-01-01 08:00:00') AS effective_date FROM poi_clearing_time_topic pct ORDER BY pct.effective_date DESC ) a;").Check(testkit.Rows("2023-08-25 00:00:00"))
 }
+
+func TestCastErrMsg(t *testing.T) {
```
Comment (Defined2014) [inline expression/integration_test/integration_test.go:2063]: Better move it to `tests/integrationtest`. It will have better performance.

**Review by Defined2014 — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

File: expression/integration_test/integration_test.go (hunk 2 above)
Comment (guo-shaoge) [reply expression/integration_test/integration_test.go]: done
