### PR TITLE
*: support send flashback cluster RPC

### LINKED ISSUE #37651: set tidb_gc_enable=OFF, after flashback, gc is turned on
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. SET GLOBAL tidb_gc_enable=FALSE; 
2. flashback
3. check  tidb_gc_enable

### 2. What did you expect to see? (Required)
tidb_gc_enable=FALSE; 
### 3. What did you see instead (Required)
tidb_gc_enable=ON

### 4. What is your TiDB version? (Required)

29a2143aa418dd182daf8532e3283206ef55b7ca

### LINKED ISSUE #37665: call client-go interface to send request

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #37651, close #37665

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Support send flashback RPC.
```

### CODE REVIEW

File: sessionctx/variable/tidb_vars.go [hunk 1]
```diff
@@ -444,6 +444,9 @@ const (
 	// TiDBDDLReorgWorkerCount defines the count of ddl reorg workers.
 	TiDBDDLReorgWorkerCount = "tidb_ddl_reorg_worker_cnt"
 
+	// TiDBFlashbackConcurrency defines the count of ddl flashback workers.
+	TiDBFlashbackConcurrency = "tidb_flashback_concurrency"
```
Comment (bb7133) [inline sessionctx/variable/tidb_vars.go:448]: How about 'tidb_ddl_flashback_concurrency'?

File: ddl/cluster.go [hunk 2]
```diff
@@ -223,17 +265,122 @@ func GetFlashbackKeyRanges(sess sessionctx.Context, startKey kv.Key) ([]kv.KeyRa
...
+	// TODO support flashback in unistore
+	if d.store.Name() != "TiKV" && !inFlashbackTest {
+		job.State = model.JobStateCancelled
+		return ver, errors.Errorf("Not support flashback cluster in non-TiKV env")
+	}
+
 	var flashbackTS uint64
 	var pdScheduleValue map[string]interface{}
-	if err := job.DecodeArgs(&flashbackTS, &pdScheduleValue); err != nil {
+	var readOnlyValue, gcEnabledValue bool
```
Comment (bb7133) [inline ddl/cluster.go:372]: Can we define `readOnlyValue` as `string`? So that we don't need a convert like:
```
	if value {
		setValue = variable.On
	} else {
		setValue = variable.Off
	}
```
In `setTiDBRestrictedReadOnly()`

File: ddl/cluster.go [hunk 3]
```diff
@@ -96,6 +117,24 @@ func ValidateFlashbackTS(ctx context.Context, sctx sessionctx.Context, flashBack
...
 }
 
+func setTiDBRestrictedReadOnly(sess sessionctx.Context, value bool) error {
+	var setValue string
+	if value {
+		setValue = variable.On
+	} else {
+		setValue = variable.Off
+	}
+	return sess.GetSessionVars().GlobalVarsAccessor.SetGlobalSysVar(variable.TiDBRestrictedReadOnly, setValue)
```
Comment (bb7133) [inline ddl/cluster.go:127]: Please notice that setting `tidb_restricted_read_only` to `on`, `tidb_super_read_only` is also applied, see:

https://docs.pingcap.com/tidb/stable/system-variables#tidb_restricted_read_only-new-in-v520

I would like to suggest using `tidb_super_read_only` instead.

**Comment by Defined2014** [comment]
Updated, PTAL
@bb7133

File: sessionctx/variable/sysvar.go [hunk 4]
```diff
@@ -507,6 +507,10 @@ var defaultSysVars = []*SysVar{
 		MemQuotaBindingCache.Store(TidbOptInt64(val, DefTiDBMemQuotaBindingCache))
 		return nil
 	}},
+	{Scope: ScopeGlobal, Name: TiDBDDLFlashbackConcurrency, Value: strconv.Itoa(DefTiDBDDLFlashbackConcurrency), Type: TypeUnsigned, MinValue: 1, MaxValue: MaxConfigurableConcurrency, SetGlobal: func(s *SessionVars, val string) error {
```
Comment (zimulala) [inline sessionctx/variable/sysvar.go:510]: Please add UT for `tidb_ddl_flashback_concurrency`.

Comment (Defined2014) [reply sessionctx/variable/sysvar.go:510]: Done PTAL @zimulala

File: ddl/cluster.go [hunk 5]
```diff
@@ -263,31 +417,39 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
-		if err != nil {
-			job.State = model.JobStateCancelled
-			return ver, errors.Trace(err)
-		}
-		defer w.sessPool.put(sess)
 		if err = checkAndSetFlashbackClusterInfo(sess, d, t, job, flashbackTS); err != nil {
 			job.State = model.JobStateCancelled
 			return ver, errors.Trace(err)
 		}
+		// A hack way to make global variables are synchronized to all tidb.
```
Comment (zimulala) [inline ddl/cluster.go:424]:
```suggestion
		// A hack way to make global variables are synchronized to all TiDB.
```

File: ddl/cluster.go [hunk 6]
```diff
@@ -263,31 +417,39 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
+		// TiKV will block read/write request during flashback cluster,
```
Comment (zimulala) [inline ddl/cluster.go:425]:
```suggestion
		// TiKV will block read/write requests during flashback cluster.
```

File: ddl/cluster.go [hunk 7]
```diff
@@ -263,31 +417,39 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
+		time.Sleep(1 * time.Second)
 		job.SchemaState = model.StateWriteReorganization
 		return ver, nil
 	// Stage 3, get key ranges.
 	case model.StateWriteReorganization:
-		sess, err := w.sessPool.get()
-		if err != nil {
-			job.State = model.JobStateCancelled
-			return ver, errors.Trace(err)
+		// TODO support flashback in unistore
```
Comment (zimulala) [inline ddl/cluster.go:432]:
```suggestion
		// TODO: Support flashback in unistore.
```

File: ddl/cluster.go [hunk 8]
```diff
@@ -263,31 +417,39 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
-		}
-		defer w.sessPool.put(sess)
 		if err = checkAndSetFlashbackClusterInfo(sess, d, t, job, flashbackTS); err != nil {
 			job.State = model.JobStateCancelled
 			return ver, errors.Trace(err)
 		}
+		// A hack way to make global variables are synchronized to all tidb.
+		// TiKV will block read/write request during flashback cluster,
+		// So it's not very dangerous when sync failed.
+		time.Sleep(1 * time.Second)
```
Comment (zimulala) [inline ddl/cluster.go:427]: Why here is `1s`?

File: ddl/cluster.go [hunk 9]
```diff
@@ -223,17 +259,123 @@ func GetFlashbackKeyRanges(sess sessionctx.Context, startKey kv.Key) ([]kv.KeyRa
...
+		}
+
+		endKey := loc.EndKey
+		isLast := len(endKey) == 0 || (len(rangeEndKey) > 0 && bytes.Compare(endKey, rangeEndKey) >= 0)
+		// If it is the last region
+		if isLast {
+			endKey = rangeEndKey
+		}
+
+		req := tikvrpc.NewRequest(tikvrpc.CmdFlashbackToVersion, &kvrpcpb.FlashbackToVersionRequest{
```
Comment (zimulala) [inline ddl/cluster.go:294]: Do we need to set `MaxExecutionDurationMs`?

File: ddl/cluster.go (hunk 8 above)
Comment (Defined2014) [reply ddl/cluster.go:427]: You can see the comments, just let most TiDB synced this global variable.

File: ddl/cluster.go (hunk 9 above)
Comment (Defined2014) [reply ddl/cluster.go:294]: It will be set to `timeout` in client-go.
https://github.com/tikv/client-go/blob/426055b5755b4a64df7b92b278aee6e65479d53c/internal/locate/region_request.go#L962-L965

File: ddl/cluster.go (hunk 8 above)
Comment (Defined2014) [reply ddl/cluster.go:427]: `1s` just a magic number. I found the global variable will synced by ETCD, so the time cost will be very small

Comment (zimulala) [reply ddl/cluster.go:427]: Got it.

File: ddl/cluster_test.go [hunk 10]
```diff
@@ -154,6 +156,71 @@ func TestFlashbackCloseAndResetPDSchedule(t *testing.T) {
...
+	hook := &ddl.TestDDLCallback{Do: dom}
+	hook.OnJobRunBeforeExported = func(job *model.Job) {
+		assert.Equal(t, model.ActionFlashbackCluster, job.Type)
+		if job.SchemaState == model.StateWriteReorganization {
+			rs, err := tk.Exec("show variables like 'tidb_super_read_only'")
+			assert.NoError(t, err)
+			assert.Equal(t, tk.ResultSetToResult(rs, "").Rows()[0][1], variable.On)
+			rs, err = tk.Exec("show variables like 'tidb_gc_enable'")
+			assert.NoError(t, err)
+			assert.Equal(t, tk.ResultSetToResult(rs, "").Rows()[0][1], variable.Off)
```
Comment (zimulala) [inline ddl/cluster_test.go:194]: How about user do `set global tidb_gc_enable = on"` in this state?

File: ddl/cluster.go [hunk 11]
```diff
@@ -255,6 +397,18 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
+				job.State = model.JobStateCancelled
+				return ver, errors.Trace(err)
+			}
+			job.Args[readOnlyArgsOffset] = &readOnlyValue
+			gcEnableValue, err := gcutil.CheckGCEnable(sess)
+			if err != nil {
+				job.State = model.JobStateCancelled
+				return ver, errors.Trace(err)
+			}
+			job.Args[gcEnabledArgsOffset] = &gcEnableValue
```
[the remark this answers is not in the document]
Comment (zimulala) [reply ddl/cluster.go:411]: OK, but I think putting it to `model.StateWriteOnly` is also OK. But it should be a little bit easier to understand here

File: ddl/cluster_test.go (hunk 10 above)
Comment (Defined2014) [reply ddl/cluster_test.go:194]: This is an illegal operation, we will add it into doc

**Review by zimulala — APPROVED** [review]
LGTM
