### PR TITLE
ddl: fix corrupted default value for bit type column

### LINKED ISSUE #17641: Incorrect default value for bit type column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t(i int);
Query OK, 0 rows affected (0.10 sec)

mysql> insert into t values(1);
Query OK, 1 row affected (0.02 sec)

mysql> alter table t add column b bit(1) default b'0';
Query OK, 0 rows affected (0.28 sec)

mysql> select b from t;
+------------+
| b          |
+------------+
| 0x00       |
+------------+
1 row in set (0.00 sec)

mysql> alter table t modify column b bit(1) default b'1';
Query OK, 0 rows affected (0.09 sec)

mysql> select b from t;
+------------+
| b          |
+------------+
| 0x01       |
+------------+
1 row in set (0.01 sec)

```
### 2. What did you expect to see? (Required)

Second select should see 0x00 still.

### 3. What did you see instead (Required)

Second select outputs 0x01.

### 4. Affected version (Required)

v3.0.0, v3.1.0, v4.0.0

### 5. Root Cause Analysis

Filling default value for missing bit column of rows doesn't regard origin default value.

### LINKED ISSUE #17642: Possible corrupted bit default value
### 1. Minimal reproduce step (Required)

Once https://github.com/pingcap/tidb/issues/17641 get fixed, we'll see:

```
mysql> create table t(i int);
Query OK, 0 rows affected (0.10 sec)

mysql> insert into t values(1);
Query OK, 1 row affected (0.02 sec)

mysql> alter table t add column b bit(1) default b'<SOME VALUE TREATED AS INVALID STRING>';
Query OK, 0 rows affected (0.28 sec)

mysql> select b from t;
+------------+
| b          |
+------------+
| <SOME VALUE TREATED AS INVALID STRING> | // this value comes from `default_bit` which is OK.
+------------+
1 row in set (0.00 sec)

mysql> alter table t modify column b bit(1) default b'1';
Query OK, 0 rows affected (0.09 sec)

mysql> select b from t;
+------------+
| b          |
+------------+
| <CORRUPTED VALUE> | // this value comes from `origin_default` which is corrupted.
+------------+
1 row in set (0.01 sec)

```

### 4. Affected version (Required)

v3.0.0, v3.1.0, v4.0.0

### 5. Root Cause Analysis

Lack something like "origin_default_bit".

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #17641 close #17642 

Problem Summary: 

The `ColumnInfo.OriginDefaultValue` is corrupted when the column type is `BIT`. `BIT` type column values are stored as __strings__ by JSON marshaling and read it by unmarshaling later. However, the data in a string can be changed in this case: 
```go
originBytes := []byte{25, 185}
originStr := string(originBytes)

mr, _ := json.Marshal(originStr)
var jsoned string
_ = json.Unmarshal(mr, &jsoned)

fmt.Printf("%v\n", []byte(originStr))
fmt.Printf("%v\n", []byte(jsoned))
```
```
[25 185]
[25 239 191 189]
```

If we store it as __[]byte__, the problem disappeared. This is how `DefaultValueBit` works.

```go
type ColumnInfo struct {
	// ...
	OriginDefaultValue    interface{} `json:"origin_default"`
	DefaultValue          interface{} `json:"default"`
	DefaultValueBit       []byte      `json:"default_bit"`
	// ...
}
```

The same problem exists in `OriginDefaultValue`. PR #12168 tried to restore the `OriginDefaultValue` from `DefaultValueBit` in the getter, but `OriginDefaultValue` is different from `DefaultValue`: `OriginDefaultValue` is used to skip the backfilling phase of `AddColumn()`. If a column's default value is modified by `ALTER TABLE MODIFY COLUMN DEFAULT`, they are not equal anymore(see the example in #17641).

### What is changed and how it works?
This PR adds a field `OriginDefaultValueBit` to `ColumnInfo`, which borrows from `DefaultValueBit` to solve the problem completely.

Proposal: [xxx](url) 

What's Changed:
- Getter and setter for `OriginDefaultValue`.
- A simple test case in #17641.

How it Works:
If the column type is `BIT`, set/get the content with `OriginDefaultValueBit`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- fix corrupted default value for bit type column.

### CODE REVIEW

**Comment by zimulala** [comment]
Do we need cherry-pick this PR to v4.0, v3.1, and v3.0?

**Comment by tangenta** [comment]
> Do we need cherry-pick this PR to v4.0, v3.1, and v3.0?

Sure. Let's pick manually since there will be lots of conflicts(the parser also needs to be picked).

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -3383,6 +3385,7 @@ func (d *ddl) getModifiableColumnJob(ctx sessionctx.Context, ident ast.Ident, or
 		Offset:             col.Offset,
 		State:              col.State,
 		OriginDefaultValue: col.OriginDefaultValue,
+		OriginDefaultValueBit: col.OriginDefaultValueBit,
```
Comment (djshow832) [inline ddl/ddl_api.go:3388]: Seems need formatting.

**Comment by tangenta** [comment]
/run_check_dev_2

```
FAIL: http_handler_test.go:1058: HTTPHandlerTestSuite.TestAllServerInfo

http_handler_test.go:1080:
    c.Assert(ok, Equals, true)
... obtained bool = false
... expected bool = true
```

**Comment by tangenta** [comment]
```
FAIL: client_fail_test.go:47: testClientFailSuite.TestPanicInRecvLoop

client_fail_test.go:70:
    c.Assert(err, IsNil)
... value context.deadlineExceededError = context.deadlineExceededError{} ("context deadline exceeded")
```

**Comment by wjhuang2016** [comment]
Please fix the mysql_test

**Comment by tangenta** [comment]
I run mysql_test locally, and there is no problem.

**Comment by wjhuang2016** [comment]
> I run mysql_test locally, and there is no problem.

JDBC test?

**Comment by wjhuang2016** [comment]
> I run mysql_test locally, and there is no problem.

JDBC test?

**Review by zz-jason — APPROVED** [review]

**Review by ti-srebot — DISMISSED** [review]

**Comment by tangenta** [comment]
```
[2020-08-27T07:59:51.437Z] FAIL: client_fail_test.go:47: testClientFailSuite.TestPanicInRecvLoop
[2020-08-27T07:59:51.437Z] 
[2020-08-27T07:59:51.437Z] client_fail_test.go:72:
[2020-08-27T07:59:51.437Z]     c.Assert(err, IsNil)
[2020-08-27T07:59:51.437Z] ... value *errors.withStack = wait recvLoop: context deadline exceeded ("wait recvLoop: context deadline exceeded")
```
/merge

**Comment by wjhuang2016** [comment]
@tangenta Please resolve the conflict.

**Review by zz-jason — APPROVED** [review]
LGTM

**Comment by AndreMouche** [comment]
LGTM
