### PR TITLE
ddl: correct the remain ranges check for adding index

### LINKED ISSUE #41459: Index records incomplete after adding index for a large table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create a table with more than 1024 regions.
2. Add index for an arbitrary column.
3. Admin check table.

### 2. What did you expect to see? (Required)

No data inconsistency.

### 3. What did you see instead (Required)

```
[admin:8223]data inconsistency in table
```

### 4. What is your TiDB version? (Required)

3cc368d45e

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #41459

Problem Summary:

The condition `remains == 0` does not indicate the whole task is finished after #40411.

### What is changed and how it works?

Correct the remain check code.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/backfilling.go [hunk 1]
```diff
@@ -1067,12 +1072,18 @@ func (dc *ddlCtx) writePhysicalTableRecord(sessPool *sessionPool, t table.Physic
 	}
 
 	for {
+		if startKey.Cmp(endKey) >= 0 {
```
Comment (zimulala) [inline ddl/backfilling.go:1075]: Could we remove this check?

Comment (tangenta) [reply ddl/backfilling.go:1075]: No, `kvRanges[len(kvRanges)-1].EndKey` may equal to `endKey`.

The function `splitTableRanges()` doesn't handle the cases like `start_key <= end_key`.

File: tests/realtikvtest/addindextest/integration_test.go [hunk 2]
```diff
@@ -444,6 +444,26 @@ func TestAddIndexIngestCancel(t *testing.T) {
...
+	tk.MustExec("use addindexlit;")
+	tk.MustExec(`set global tidb_ddl_enable_fast_reorg=on;`)
+
+	tk.MustExec("create table t (a int primary key, b int);")
+	for i := 0; i < 8; i++ {
+		tk.MustExec(fmt.Sprintf("insert into t values (%d, %d);", i*10000, i*10000))
+	}
+	tk.MustQuery("split table t between (0) and (80000) regions 7;").Check(testkit.Rows("6 1"))
+
+	ddl.SetBackfillTaskChanSizeForTest(4)
```
Comment (zimulala) [inline tests/realtikvtest/addindextest/integration_test.go:461]: Please add a case like `ddl.SetBackfillTaskChanSizeForTest(7)` which can test the logic of `len(remains)==0`.

File: ddl/backfilling.go (hunk 1 above)
Comment (zimulala) [reply ddl/backfilling.go:1075]: Got it.

File: ddl/backfilling.go [hunk 3]
```diff
@@ -1067,12 +1072,18 @@ func (dc *ddlCtx) writePhysicalTableRecord(sessPool *sessionPool, t table.Physic
...
 		kvRanges, err := splitTableRanges(t, reorgInfo.d.store, startKey, endKey, backfillTaskChanSize)
 		if err != nil {
 			return errors.Trace(err)
 		}
-		scheduler.setMaxWorkerSize(len(kvRanges))
+		if len(kvRanges) == 0 {
+			break
+		}
 
+		scheduler.setMaxWorkerSize(len(kvRanges))
```
Comment (Benjamin2037) [inline ddl/backfilling.go:1086]: Why here add this line to set worker size?

Comment (zimulala) [reply ddl/backfilling.go:1086]: This is the old logic.

File: ddl/backfilling.go (hunk 1 above)
Comment (Benjamin2037) [reply ddl/backfilling.go:1075]: is above  start_key > end_key scenario for `splitTableRanges()` not handle?

File: tests/realtikvtest/addindextest/integration_test.go (hunk 2 above)
Comment (zimulala) [reply tests/realtikvtest/addindextest/integration_test.go:461]: Rest LGTM

File: ddl/backfilling.go (hunk 1 above)
Comment (zimulala) [reply ddl/backfilling.go:1075]: It handles in [line1082](https://github.com/pingcap/tidb/pull/41460/files#diff-1bbc7833321782b3a22a842b6237974b6a60cb07b49b246b85552ab5e915ed6eR1082)

**Review by zimulala — APPROVED** [review]
LGTM

File: ddl/backfilling.go (hunk 1 above)
Comment (Benjamin2037) [reply ddl/backfilling.go:1075]: My question is if we send a smaller start_key to `splitTableRanges(), will it return an err?

**Review by Benjamin2037 — APPROVED** [review]
LGTM

File: ddl/backfilling.go [hunk 4]
```diff
@@ -1095,14 +1106,15 @@ func (dc *ddlCtx) writePhysicalTableRecord(sessPool *sessionPool, t table.Physic
...
-		if len(remains) == 0 {
-			if ingestBeCtx != nil {
-				ingestBeCtx.EngMgr.ResetWorkers(ingestBeCtx, job.ID, reorgInfo.currElement.ID)
-			}
-			break
+		if len(remains) > 0 {
+			startKey = remains[0].StartKey
+		} else {
+			lastFinishedKey := kvRanges[len(kvRanges)-1].EndKey
+			startKey = lastFinishedKey.Next()
```
Comment (wjhuang2016) [inline ddl/backfilling.go:1113]: Why use the Next()? The end key is not covered yet.

Comment (tangenta) [reply ddl/backfilling.go]: Updated.
