### PR TITLE
ddl: forbid creating a column with name _tidb_rowid

### LINKED ISSUE #19167: DML failed on table with column _tidb_rowid
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table test_1(id int, value int, `_tidb_rowid` int);
Query OK, 0 rows affected (0.08 sec)

mysql> insert into test_1 values(1,2,3);
ERROR 1105 (HY000): insert, update and replace statements for _tidb_rowid are not supported.
mysql> select _tidb_rowid from test_1;
ERROR 1060 (42S21): Duplicate column name '_tidb_rowid'
```

### 2. What did you expect to see? (Required)
DML succeed or DDL failed when creating a table with column `_tidb_rowid`

### 3. What did you see instead (Required)
DDL succeed but DML failed.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #19167, #12835

Problem Summary: According to #8126, `_tidb_rowid` is a reserved column. It is not likely to be useful for users. So I think it is acceptable to forbid creating such a column.

### Check List

Tests

- Unit test
- Integration test

### Release note

- Forbid creating a column with name `_tidb_rowid`

### CODE REVIEW

**Comment by xhebox** [comment]
@ti-srebot /run-all-tests

**Comment by xhebox** [comment]
@ti-srebot /run-unit-test

**Comment by xhebox** [comment]
@ti-srebot /run-common-test

**Comment by xhebox** [comment]
@ti-srebot /run-common-test

File: ddl/db_integration_test.go [hunk 1]
```diff
@@ -533,6 +535,8 @@ func (s *testIntegrationSuite5) TestErrnoErrorCode(c *C) {
 	tk.MustGetErrCode(sql, errno.ErrNoSuchTable)
 	sql = "alter table test_error_code_succ add column `a ` int ;"
 	tk.MustGetErrCode(sql, errno.ErrWrongColumnName)
+	sql = "alter table test_error_code_succ add column `_tidb_rowid` int ;"
+	tk.MustGetErrCode(sql, errno.ErrWrongColumnName)
```
Comment (djshow832) [inline ddl/db_integration_test.go:539]: What about rename column?

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -384,6 +384,10 @@ func buildColumnAndConstraint(
 	tblCharset string,
 	tblCollate string,
 ) (*table.Column, []*ast.Constraint, error) {
+	if colName := colDef.Name.Name.L; colName == "_tidb_rowid" {
```
Comment (tangenta) [inline ddl/ddl_api.go:387]: Maybe we should use `model.ExtraHandleName.L`.

File: ddl/db_integration_test.go (hunk 1 above)
Comment (xhebox) [reply ddl/db_integration_test.go:539]: Handled.

File: ddl/ddl_api.go (hunk 2 above)
Comment (xhebox) [reply ddl/ddl_api.go]: Done.

**Review by djshow832 — COMMENTED** [review]
LGTM

File: ddl/db_integration_test.go [hunk 3]
```diff
@@ -583,6 +587,10 @@ func (s *testIntegrationSuite5) TestErrnoErrorCode(c *C) {
 	tk.MustGetErrCode(sql, errno.ErrWrongDBName)
 	sql = "alter table test_error_code_succ modify t.c1 bigint"
 	tk.MustGetErrCode(sql, errno.ErrWrongTableName)
+	sql = "alter table test_error_code_succ change c1 _tidb_rowid bigint"
+	tk.MustGetErrCode(sql, errno.ErrWrongColumnName)
+	sql = "alter table test_error_code_succ rename column c1 to _tidb_rowid"
```
Comment (tangenta) [inline ddl/db_integration_test.go:592]: What about `alter table add column`?

```sql
alter table t add column _tidb_rowid int;
```

Comment (djshow832) [reply ddl/db_integration_test.go:592]: It's at line 538

Comment (xhebox) [reply ddl/db_integration_test.go:592]: I think there is one? https://github.com/pingcap/tidb/pull/19418/files#diff-703ae6b7872b425273d1832c198598c8R538

Comment (tangenta) [reply ddl/db_integration_test.go:592]: Sorry. I didn't notice that.

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
