### PR TITLE
executor: refine maxOneRow

### LINKED ISSUE #10151: Error subquery returns more than 1 row for insert on dup
## Description
Bug Report
Please answer these questions before submitting your issue. Thanks!

What did you do?
If possible, provide a recipe for reproducing the error.
CREATE TABLE t1(a INTEGER);
CREATE TABLE t11(a INTEGER primary key);
CREATE TABLE t2(b INTEGER);
INSERT INTO t2 VALUES (1),(1);

INSERT INTO t1(a) VALUES (1)
ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);

INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);

DROP TABLE t1, t2;
What did you expect to see
MySQL behavior:
for inserting into t1

INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
Query OK, 1 row affected (0.01 sec)
INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
Query OK, 1 row affected (0.01 sec)

for inserting into t11
INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
Query OK, 1 row affected (0.02 sec)

INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row

TiDB behvaior:
for inserting into t1
mysql>  INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row
mysql>  INSERT INTO t1(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row

for inserting into t11
mysql>  INSERT INTO t11(a) VALUES (1) ON DUPLICATE KEY UPDATE a= (SELECT b FROM t2);
ERROR 1105 (HY000): subquery returns more than 1 row
Create issue (#10151) from GitHub user jackysp at 16:26 PM, April 15 2019
## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Refine the code.

### What is changed and how it works?

How it Works:

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No Release note.

### CODE REVIEW

File: executor/executor.go [hunk 1]
```diff
@@ -1152,17 +1153,16 @@ func init() {
...
+
+		err = Next(ctx, exec, chk)
+		if err != nil {
+			return nil, err
+		}
+		if chk.NumRows() == 0 {
+			return nil, nil
 		}
+		row := chk.GetRow(0).GetDatumRow(retTypes(exec))
+		return row, err
```
Comment (ichn-hu) [inline executor/executor.go:1165]: Kind of curious who wrote the for loop here previously...

**Review by ichn-hu — CHANGES_REQUESTED** [review]
Rest LGTM

**Review by ichn-hu — DISMISSED** [review]

File: executor/executor.go [hunk 2]
```diff
@@ -1371,41 +1372,65 @@ func (e *MaxOneRowExec) Open(ctx context.Context) error {
...
 	e.evaluated = false
 	return nil
 }
 
 // Next implements the Executor Next interface.
 func (e *MaxOneRowExec) Next(ctx context.Context, req *chunk.Chunk) error {
 	req.Reset()
-	if e.evaluated {
+
+	if e.evaluated && len(e.rowData) == 0 {
```
Comment (wshwsh12) [inline executor/executor.go:1384]: Why we need check `len(e.rowData) == 0`? 
I think the logic after this line should only run once..

File: executor/executor.go [hunk 3]
```diff
@@ -1371,41 +1372,65 @@ func (e *MaxOneRowExec) Open(ctx context.Context) error {
...
+		e.evaluated = true
+		if num := req.NumRows(); num == 0 {
+			for i := range e.schema.Columns {
+				req.AppendNull(i)
+			}
+			return nil
+		}
+		row := req.GetRow(0)
+		for i := 0; i < req.NumCols(); i++ {
+			e.rowData = append(e.rowData, row.GetRaw(i))
```
Comment (wshwsh12) [inline executor/executor.go:1402]: IsNull is also should be check.

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by ichn-hu — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]
