### PR TITLE
executor: show consistent table and schema name for `RENAME TABLE`

### LINKED ISSUE #46897: Inconsistent db+table name in RENAME TABLE in ADMIN SHOW DDL JOBS
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
tidb1> use test;
tidb1> create schema test2;
tidb1> create table t (a int);
tidb1> begin;
tidb1> insert into t values (1);

tidb2> rename table t to test2.t2; -- will hang, due to MDL waiting on tidb1

tidb3> admin show ddl jobs where state != 'synced'; -- will show test2.t which is incorrect!
```

### 2. What did you expect to see? (Required)
test.t (or test2.t2 would be not as good, but still acceptable)

### 3. What did you see instead (Required)
test2.t (which is not matching before or after)
```mysql
tidb3> admin show ddl jobs where state != 'synced';
+--------+---------+------------+--------------+--------------+-----------+----------+-----------+---------------------+---------------------+----------+---------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE     | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME | STATE   |
+--------+---------+------------+--------------+--------------+-----------+----------+-----------+---------------------+---------------------+----------+---------+
|     94 | test2   | t          | rename table | public       |        88 |       90 |         0 | 2023-09-12 09:51:21 | 2023-09-12 09:51:21 | NULL     | running |
+--------+---------+------------+--------------+--------------+-----------+----------+-----------+---------------------+---------------------+----------+---------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v7.1.1
Edition: Community
Git Commit Hash: cf441574864be63938524e7dfcf7cc659edc3dd8
Git Branch: heads/refs/tags/v7.1.1
UTC Build Time: 2023-07-19 10:20:53
GoVersion: go1.20.6
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #46897

Problem Summary:

For `RENAME TABLE`, we store new schema name and old table name in the job, and old schema and new table name are stored in job args. 

And for running jobs, the table/schema name displayed in `ADMIN SHOW DDL JOBS` is get from job. So we will get inconsistent names for running `RENAME TABLE`

### What changed and how does it work?

I don't want to change the way we store job arguments, since it may arise compatibility issues, so just apply a patch for the outputs.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/ddl/db_rename_test.go [hunk 1]
```diff
@@ -488,3 +490,24 @@ func TestRenameConcurrentAutoID(t *testing.T) {
...
+	tk1.MustExec("create database test2")
+	tk1.MustExec("create table t1 (a int, b int)")
+
+	tk2 := testkit.NewTestKit(t, store)
+	failpoint.EnableCall("github.com/pingcap/tidb/pkg/ddl/beforeWaitSchemaSynced", func(job *model.Job, _ int64) {
+		if job.State != model.JobStateSynced && job.Type == model.ActionRenameTable {
+			rs := tk2.MustQuery("admin show ddl jobs where state != 'synced'").Rows()
+			require.Len(t, rs, 1)
+			require.Equal(t, "test2", rs[0][1])
+			require.Equal(t, "t2", rs[0][2])
```
Comment (tangenta) [inline pkg/ddl/db_rename_test.go:508]: Is it necessary to add a test for column `schema_name` and `table_name` in `information_schema.ddl_jobs`?
