### PR TITLE
executor: fix issue of execute prepared DML panic with foreign key cascade

### LINKED ISSUE #39732: execute prepared DML panic with foreign key cascade
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t1 (id int key, leader int,  index(leader), foreign key (leader) references t1(id) ON DELETE CASCADE);
insert into t1 values (1, null), (10, 1), (11, 1), (20, 10);
prepare stmt1 from 'delete from t1 where id = ?';
set @a = 1;
execute stmt1 using @a;
```

panic log

```
[2022/12/07 19:44:05.889 +08:00] [ERROR] [conn.go:1058] ["connection running loop panic"] [conn=2199023255955] [lastSQL="execute stmt1 using @a"] [err="interface conversion: *core.Delete is not core.PhysicalPlan: missing method Children"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1
	/Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:1061
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:884
runtime.getitab
	/usr/local/go/src/runtime/iface.go:92
runtime.assertI2I
	/usr/local/go/src/runtime/iface.go:429
github.com/pingcap/tidb/planner/core.GenHintsFromFlatPlan
	/Users/cs/code/goread/src/github.com/pingcap/tidb/planner/core/hints.go:46
github.com/pingcap/tidb/executor.getEncodedPlan
	/Users/cs/code/goread/src/github.com/pingcap/tidb/executor/adapter.go:1675
github.com/pingcap/tidb/executor.(*ExecStmt).SummaryStmt.func1
	/Users/cs/code/goread/src/github.com/pingcap/tidb/executor/adapter.go:1732
github.com/pingcap/tidb/util/stmtsummary.newStmtSummaryByDigestElement
	/Users/cs/code/goread/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:646
github.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigest).add.func1
	/Users/cs/code/goread/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:601
github.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigest).add
	/Users/cs/code/goread/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:612
github.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigestMap).AddStatement
	/Users/cs/code/goread/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:340
github.com/pingcap/tidb/executor.(*ExecStmt).SummaryStmt
	/Users/cs/code/goread/src/github.com/pingcap/tidb/executor/adapter.go:1819
github.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt
	/Users/cs/code/goread/src/github.com/pingcap/tidb/executor/adapter.go:1388
github.com/pingcap/tidb/session.runStmt
	/Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2373
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/Users/cs/code/goread/src/github.com/pingcap/tidb/session/session.go:2210
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt
	/Users/cs/code/goread/src/github.com/pingcap/tidb/server/driver_tidb.go:247
github.com/pingcap/tidb/server.(*clientConn).handleStmt
	/Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:2093
github.com/pingcap/tidb/server.(*clientConn).handleQuery
	/Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:1943
github.com/pingcap/tidb/server.(*clientConn).dispatch
	/Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:1374
github.com/pingcap/tidb/server.(*clientConn).Run
	/Users/cs/code/goread/src/github.com/pingcap/tidb/server/conn.go:1123
github.com/pingcap/tidb/server.(*Server).onConn
	/Users/cs/code/goread/src/github.com/pingcap/tidb/server/server.go:625"]
```

### 4. What is your TiDB version? (Required)

```sql
***************************[ 1. row ]***************************
tidb_version() | Release Version: v6.5.0-alpha-293-g770e75b47b-dirty
Edition: Community
Git Commit Hash: 770e75b47b505dfb7e76562a4fc5cb4b2bf45c74
Git Branch: master
UTC Build Time: 2022-12-07 11:42:56
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #39732

Problem Summary: Fix issue of execute prepared DML panic with foreign key cascade

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/flat_plan.go [hunk 1]
```diff
@@ -55,22 +55,34 @@ type FlatPhysicalPlan struct {
...
+		return nil, 0
 	}
+	hasDML := false
 	for i, op := range e {
 		switch op.Origin.(type) {
 		case *Insert, *Delete, *Update:
+			hasDML = true
 		default:
-			return e[i:]
+			if hasDML {
```
Comment (time-and-fate) [inline planner/core/flat_plan.go:73]: Is this check necessary?

File: planner/core/flat_plan.go [hunk 2]
```diff
@@ -55,22 +55,34 @@ type FlatPhysicalPlan struct {
...
+				for j := i; j < len(e); j++ {
+					switch e[j].Origin.(type) {
+					// Skip foreign key check/cascade plan, since the later plan doesn't belong to select plan.
+					case *FKCheck, *FKCascade:
+						return e[i:j], i
```
Comment (time-and-fate) [inline planner/core/flat_plan.go:78]: We have an assumption here that the `FKCheck`, `FKCascade`, and their children might only appear at the end of a `FlatPlanTree`. And the returned select plan would not reference operators in the skipped FK check/cascade plan.
Please clarify this in the comments.

File: planner/core/flat_plan.go [hunk 3]
```diff
@@ -55,22 +55,34 @@ type FlatPhysicalPlan struct {
 type FlatPlanTree []*FlatOperator
 
 // GetSelectPlan skips Insert, Delete and Update at the beginning of the FlatPlanTree.
+// GetSelectPlan also skips foreign key check/cascade plan.
```
Comment (time-and-fate) [inline planner/core/flat_plan.go:58]:
```suggestion
// GetSelectPlan skips Insert, Delete, and Update at the beginning of the FlatPlanTree and the foreign key check/cascade plan at the end of the FlatPlanTree.
```

File: planner/core/flat_plan.go [hunk 4]
```diff
@@ -55,22 +55,34 @@ type FlatPhysicalPlan struct {
...
 // Note:
 //
-//	It returns a reference to the original FlatPlanTree, please avoid modifying the returned value.
+//	It returns a reference to the original FlatPlanTree and the offset, please avoid modifying the returned value.
 //	Since you get a part of the original slice, you need to adjust the FlatOperator.Depth and FlatOperator.ChildrenIdx when using them.
```
Comment (time-and-fate) [inline planner/core/flat_plan.go:62]:
```suggestion
//	It returns a reference to the original FlatPlanTree, please avoid modifying the returned value.
//	The second return value is the offset. Because the returned FlatPlanTree is a part of the original slice, you need to minus them by the offset when using the returned FlatOperator.Depth and FlatOperator.ChildrenIdx.
```

File: planner/core/flat_plan.go (hunk 2 above)
Comment (crazycs520) [reply planner/core/flat_plan.go]: done.

File: planner/core/flat_plan.go (hunk 1 above)
Comment (crazycs520) [reply planner/core/flat_plan.go:72]: Since only DML contains foreign key check/cascade, so it is a tiny optimization to avoid always iterator all FlatPlan.

**Review by time-and-fate — APPROVED** [review]

**Review by winoros — APPROVED** [review]
