### PR TITLE
copr: fallback when bucket path meets error

### LINKED ISSUE #66096: Infinite loop in splitKeyRangesByBuckets
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Unknown

### 2. What did you expect to see? (Required)

Infinite loop in splitKeyRangesByBuckets and it causes high gc pressure, possibly leading to OOM.

### 4. What is your TiDB version? (Required)

Only observed in TiDB-X.

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: ref #64008, close #66096

Problem Summary:

If the start key of a range is smaller than the start key of the region, there can be an infinite loop in `splitKeyRangesByBuckets`.

### What changed and how does it work?

- When anything bad happens in the bucket path, fallback to the non-bucket path.
- Add more diagnostics logs
- Try to catch and work around several unexpected situations.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/store/copr/region_cache.go [hunk 1]
```diff
@@ -442,87 +450,25 @@ func (l *LocationKeyRanges) splitKeyRangesByBuckets(ctx context.Context) []*Loca
...
+				remainingRangeCount: ranges.Len(),
 			}
+		}
 
-			if gapDetected {
-				fields = append(fields,
-					keyField("expectedNextStart", expectedNextStart))
+		// Input consistency guard: Bucket splitting assumes the first range starts inside this location.
+		// If it doesn't, continuing can livelock (no progress) and/or over-split incorrectly.
+		if !loc.Contains(startKey) {
```
Comment (gengliqi) [inline pkg/store/copr/region_cache.go]: I think it would be better to move this check before `bucket := loc.LocateBucket(startKey)`.

File: pkg/store/copr/region_cache.go [hunk 2]
```diff
@@ -774,13 +722,59 @@ func (c *RegionCache) SplitKeyRangesByBuckets(bo *Backoffer, ranges *KeyRanges)
...
 		})
-		res = append(res, locs[locIdx].splitKeyRangesByBuckets(ctx)...)
+		var r []*LocationKeyRanges
+		r, fallback = locs[locIdx].splitKeyRangesByBuckets(ctx)
+		if fallback != nil {
+			break
+		}
+		res = append(res, r...)
+	}
+	if fallback != nil {
```
Comment (cfzjywxk) [inline pkg/store/copr/region_cache.go:866]: Would all the partial work be dicarded if fallback happens after some locations were already processed?

Comment (ekexium) [reply pkg/store/copr/region_cache.go:866]: Yes, this is an intentional complete fallback

**Review by cfzjywxk — APPROVED** [review]
