### PR TITLE
br: adjust default tidb global config for br

### LINKED ISSUE #45793: failed to restore DDL when upstream has some different limit config from default value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. upstream, set some limit config, suche as table-column-count, to its max value.
2. create a table with too many column or index.
3. backup
4. restore to downstream

### 2. What did you expect to see? (Required)
1. success
### 3. What did you see instead (Required)
failed to restore for DDL check error.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #45793

Problem Summary:
When the upstream set the column count limit to any value larger than the default one, the downstream would be not able to restore the data for DDL check error.
### What is changed and how it works?
use the max value as the default value for br.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/task/restore.go [hunk 1]
```diff
@@ -1117,6 +1117,10 @@ func enableTiDBConfig() func() {
 		// when upstream and downstream both set this value greater than default(3072)
 		conf.MaxIndexLength = config.DefMaxOfMaxIndexLength
```
Comment (lance6716) [inline br/pkg/task/restore.go:1118]: seems fail on same type of mistake again? Do you consider to skip checks when creating table? like https://github.com/pingcap/tidb/blob/522a00840385dfa43509a3af2bc79e6ff50252a8/ddl/schematracker/dm_tracker.go#L178

Comment (lance6716) [reply br/pkg/task/restore.go:1118]: https://github.com/pingcap/tidb/blob/522a00840385dfa43509a3af2bc79e6ff50252a8/ddl/schematracker/dm_tracker_test.go#L50

DM has met a similar problem before, which is upstream MySQL has more capability than TiDB, so we use a special DDL implementation to apply DDL SQL.

Comment (Leavrth) [reply br/pkg/task/restore.go:1118]: There is a check before create table with DDL.
https://github.com/pingcap/tidb/blob/57d778f0b1b6daebe0f330af2baa54e9e5310ea4/ddl/ddl_api.go#L2337-L2352

When use br, every check config is default value. If upstream has large value, for example set `TableColumnCountLimit` to 4000, the restore might be failed when there is a table with 4000 columns.

Comment (Leavrth) [reply br/pkg/task/restore.go:1118]: BR import the DDL package, but doesn't expose these configs.

**Review by 3pointer — APPROVED** [review]
please leave to TODO here, we need customize check for `createTableWithInfo`
