### PR TITLE
expression: add annotations to inform user to import planner/core to initalize expression.RewriteAstExpr and expression.EvalAstExpr

### LINKED ISSUE #21342: call tables.TableFromMeta panic with partition table meta
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Running lightning with current master branch tidb(`fd0299f58ecc174e5ed8f91660299ebac8fa2b9c`) panic.
table schema:
```
CREATE TABLE `test_perm` (
	`id` int(11) NOT NULL,
	`batch_date` varchar(32) DEFAULT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE COLUMNS(batch_date) (
	PARTITION `P20200224` VALUES LESS THAN ("2020-02-05 00:00:00"),
	PARTITION `P20200324` VALUES LESS THAN ("2020-03-05 00:00:00"),
	PARTITION `P20200424` VALUES LESS THAN ("2020-04-05 00:00:00"),
	PARTITION `P20200524` VALUES LESS THAN ("2020-05-05 00:00:00"),
	PARTITION `P_MAXVALUE` VALUES LESS THAN MAXVALUE
);
```
panic stack trace:
```
[2020-11-27T02:38:41.551Z] panic: runtime error: invalid memory address or nil pointer dereference

[2020-11-27T02:38:41.551Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x163eb89]

[2020-11-27T02:38:41.551Z] 

[2020-11-27T02:38:41.551Z] goroutine 242 [running]:

[2020-11-27T02:38:41.551Z] github.com/pingcap/tidb/expression.RewriteSimpleExprWithNames(0x26ecf40, 0xc000cf1f20, 0x26df500, 0xc0003c2cf0, 0xc000e9bd10, 0xc000814150, 0xd, 0xd, 0xc0010547b0, 0xc000d22640, ...)

[2020-11-27T02:38:41.551Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20201126095401-55c106afb89b/expression/simple_rewriter.go:113 +0x89

[2020-11-27T02:38:41.551Z] github.com/pingcap/tidb/table/tables.parseSimpleExprWithNames(0xc0007ae9c0, 0x26ecf40, 0xc000cf1f20, 0xc0010547b0, 0x28, 0xc000e9bd10, 0xc000814150, 0xd, 0xd, 0x0, ...)

[2020-11-27T02:38:41.551Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20201126095401-55c106afb89b/table/tables/partition.go:197 +0xf8

[2020-11-27T02:38:41.551Z] github.com/pingcap/tidb/table/tables.generateRangePartitionExpr(0x26ecf40, 0xc000cf1f20, 0xc000e1eab0, 0xc0008140e0, 0xd, 0xd, 0xc000814150, 0xd, 0xd, 0x9, ...)

[2020-11-27T02:38:41.551Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20201126095401-55c106afb89b/table/tables/partition.go:295 +0x32a

[2020-11-27T02:38:41.551Z] github.com/pingcap/tidb/table/tables.newPartitionExpr(0xc000b93c80, 0xc00106be00, 0xc000814000, 0x70)

[2020-11-27T02:38:41.551Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20201126095401-55c106afb89b/table/tables/partition.go:116 +0x2f1

[2020-11-27T02:38:41.551Z] github.com/pingcap/tidb/table/tables.newPartitionedTable(0xc000626140, 0xc000b93c80, 0x78, 0xc000c9ddc0, 0xd, 0xd)

[2020-11-27T02:38:41.551Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20201126095401-55c106afb89b/table/tables/partition.go:78 +0x95

[2020-11-27T02:38:41.551Z] github.com/pingcap/tidb/table/tables.TableFromMeta(0xc000c312c0, 0x3, 0x3, 0xc000b93c80, 0x40e186, 0xc000c31290, 0x30, 0x30)

[2020-11-27T02:38:41.551Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20201126095401-55c106afb89b/table/tables/tables.go:147 +0xc62

[2020-11-27T02:38:41.551Z] github.com/pingcap/tidb-lightning/lightning/restore.NewTableRestore(0xc001054780, 0x12, 0xc000be4210, 0xc000c99920, 0xc000c30e10, 0xc000aa3480, 0x0, 0x0, 0x2c)
```

The cause of the panic is https://github.com/pingcap/tidb/blob/d084651fafb69f5b9ff09e9ffcc5102e5dcb2c62/expression/expression.go#L54 this variable function is not inited. 

In my manual test, an extra  import `github.com/pingcap/tidb/planner/core`  can avoid this panic.

### 4. What is your TiDB version? (Required)
`fd0299f58ecc174e5ed8f91660299ebac8fa2b9c `

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @XuHuaiyu

### PR DESCRIPTION
**Pull request by xuhui-lu**
### What problem does this PR solve?

Issue Number: close #21342 

Problem Summary:
When external project(like `tidb-lightning`) calls `expression.RewriteAstExpr` and `expression.EvalAstExpr`, it will cause a panic because they are not initialized. To initialize them, `planner/core` needs to be imported as well.

### What is changed and how it works?

What's Changed:
Add annotation to inform user to import planner/core to initalize expression.RewriteAstExpr and expression.EvalAstExpr

How it Works:
Just add some annotation. And there is also another PR in `tidb-lightning` to fix the panic.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- add annotation for expression.RewriteAstExpr and expression.EvalAstExpr for func var initialization

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
@xuhui-lu Does it mean that, the bug is caused by the misusage in tidb-lightning?

**Comment by xuhui-lu** [comment]
> @xuhui-lu Does it mean that, the bug is caused by the misusage in tidb-lightning?

Yea, I think so. To avoid cycle dependency, `expression.RewriteAstExpr` is defined in expression pkg but initialized in planner/core pkg. That is why we need to import planner/core as well when we call `expression.RewriteAstExpr`. I also have a PR in tidb-lightning to fix this issue.

File: expression/expression.go [hunk 1]
```diff
@@ -48,9 +48,13 @@ const (
 )
 
 // EvalAstExpr evaluates ast expression directly.
+// it is initialized in planner/core
```
Comment (XuHuaiyu) [inline expression/expression.go:51]:
```
...
Note: initialized in planner/core
...
```

**Comment by XuHuaiyu** [comment]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
