### PR TITLE
ddl: Fix validation error for column default value

### LINKED ISSUE #51592: Table creation with auto_increment and default expressions has different error messages than MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t0 (c int(10), c1 date auto_increment default (current_date()));
```

### 2. What did you expect to see? (Required)
```
ERROR 1067 (42000): Invalid default value for 'c1'
```

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): Incorrect column specifier for column 'c1'
```

### 4. What is your TiDB version? (Required)

```
Release Version: v8.0.0-alpha-419-gf94a6bacf8-dirty
Edition: Community
Git Commit Hash: f94a6bacf872084630397b945ebf86561ce48bc8
Git Branch: master
```

### PR DESCRIPTION
**Pull request by danqixu**
### What problem does this PR solve?

Issue Number: close #51592 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/preprocess.go [hunk 1]
```diff
@@ -762,6 +762,19 @@ func (p *preprocessor) checkAutoIncrement(stmt *ast.CreateTableStmt) {
...
 		default:
+			if col.Tp.GetType() == mysql.TypeDate {
+				var defaultValueOpt *ast.ColumnOption
+				for _, op := range col.Options {
+					if op.Tp == ast.ColumnOptionDefaultValue {
+						defaultValueOpt = op
+						break
+					}
+				}
+				if defaultValueOpt != nil && defaultValueOpt.Expr != nil {
```
Comment (zimulala) [inline pkg/planner/core/preprocess.go:773]: I think we put this check to `checkAutoIncrementOp` is better. Because this function checks some `Invalid default value for ...` errors.

**Comment by danqixu** [comment]
Can anyone help review the PR?

File: pkg/planner/core/preprocess.go (hunk 1 above)
Comment (danqixu) [reply pkg/planner/core/preprocess.go]: I have made the changes as requested, could you please review it again?

**Review by zimulala — APPROVED** [review]

**Review by okJiang — APPROVED** [review]
