### PR TITLE
*: fix bug of profiling conflict between TopSQL and pprof profile HTTP API

### LINKED ISSUE #30890: Continuous Profiling do cpu profile maybe conflict with TopSQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

Since both `Continuous Profiling` and `TopSQL` need to do cpu profiling. there are conflict exist since golang only allow 1 profiling by `pprof.StartCPUProfile` at one time.

### 2. What did you expect to see? (Required)
To avoid conflict.

### 4. What is your TiDB version? (Required)

```
master:
92207005ec8e37b545d810ec35da477844cca2f4 
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #30890

Problem Summary: Continuous Profiling do cpu profile maybe conflict with TopSQL.

### What is changed and how it works?

This PR introduce a `ParallelCPUProfiler` to be responsible for handling profiling requests. Then both the TopSQL and pprof Profile HTTP API get profile data by `ParallelCPUProfiler`.

### Check List

Tests 

- [x] Unit test
- [x] Integration test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory

Documentation

N/A

### Release note

```release-note
*: fix bug of profiling conflict between TopSQL and pprof profile HTTP API
```

### CODE REVIEW

File: util/topsql/topsql.go [hunk 1]
```diff
@@ -120,7 +122,7 @@ func linkSQLTextWithDigest(sqlDigest []byte, normalizedSQL string, isInternal bo
 		normalizedSQL = normalizedSQL[:MaxSQLTextSize]
 	}
 
-	c := tracecpu.GlobalSQLCPUProfiler.GetCollector()
+	c := tracecpu.GlobalSQLCPUCollector.GetCollector()
```
Comment (zhongzc) [inline util/topsql/topsql.go:125]: Weired... '`GetCollector`', change it dynamicly to `TopSQLReporter` for calling `RegisterSQL` and `RegisterPlan`.

File: util/topsql/topsql.go [hunk 2]
```diff
@@ -48,8 +49,9 @@ func SetupTopSQL() {
 
 	globalTopSQLReport = remoteReporter
 
-	tracecpu.GlobalSQLCPUProfiler.SetCollector(remoteReporter)
-	tracecpu.GlobalSQLCPUProfiler.Run()
+	cpuprofile.GlobalCPUProfiler.Start()
```
Comment (zhongzc) [inline util/topsql/topsql.go:52]: If the profiler only starts once, I don't think it's topsql's business.

File: util/topsql/tracecpu/profile.go [hunk 3]
```diff
@@ -15,34 +15,26 @@
...
 const (
-	labelSQL        = "sql"
 	labelSQLDigest  = "sql_digest"
 	labelPlanDigest = "plan_digest"
 )
 
-// GlobalSQLCPUProfiler is the global SQL stats profiler.
-var GlobalSQLCPUProfiler = newSQLCPUProfiler()
+// GlobalSQLCPUCollector is the global SQL CPU stats collector.
+var GlobalSQLCPUCollector = newSQLCPUCollector()
```
Comment (zhongzc) [inline util/topsql/tracecpu/profile.go:37]: Consider removing this global variable. I think it can be a field of the reporter.

File: util/topsql/reporter/reporter.go [hunk 4]
```diff
@@ -252,6 +252,7 @@ func (tsr *RemoteTopSQLReporter) Register(dataSink DataSink) error {
 
 		if len(tsr.dataSinks) > 0 {
 			variable.TopSQLVariable.Enable.Store(true)
```
Comment (zhongzc) [inline util/topsql/reporter/reporter.go:254]: It doesn't need `Enable` anymore if we use `profiler.Consumer`.

But `TopSQLReporter` should export its enabled state to let people know if topsql is enabled.

File: util/topsql/topsql.go (hunk 1 above)
Comment (crazycs520) [reply util/topsql/topsql.go]: great, resolved.

File: util/topsql/topsql.go (hunk 2 above)
Comment (crazycs520) [reply util/topsql/topsql.go]: done.

File: util/topsql/tracecpu/profile.go (hunk 3 above)
Comment (crazycs520) [reply util/topsql/tracecpu/profile.go]: great, done.

File: util/topsql/reporter/reporter.go (hunk 4 above)
Comment (crazycs520) [reply util/topsql/reporter/reporter.go:259]: Yes, but we still need this variable for other pkg use.

File: server/main_test.go [hunk 5]
```diff
@@ -61,7 +61,8 @@ func TestMain(m *testing.M) {
 		goleak.IgnoreTopFunction("go.opencensus.io/stats/view.(*worker).start"),
 		goleak.IgnoreTopFunction("go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop"),
 		goleak.IgnoreTopFunction("github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1"),
-		goleak.IgnoreTopFunction("github.com/pingcap/tidb/util/topsql/tracecpu.(*sqlCPUProfiler).startAnalyzeProfileWorker"),
+		goleak.IgnoreTopFunction("github.com/pingcap/tidb/util/topsql/tracecpu.(*sqlCPUCollector).startAnalyzeProfileWorker"),
+		goleak.IgnoreTopFunction("github.com/pingcap/tidb/util/cpuprofile.(*ParallelCPUProfiler).profilingLoop"),
```
Comment (zhongzc) [inline server/main_test.go:65]: Can these be removed? Cuz we can close them now.

File: server/tidb_test.go [hunk 6]
```diff
@@ -1283,7 +1281,11 @@ func TestTopSQLCPUProfile(t *testing.T) {
 	}()
 
 	collector := mockTopSQLTraceCPU.NewTopSQLCollector()
-	tracecpu.GlobalSQLCPUProfiler.SetCollector(&collectorWrapper{collector})
+	topsql.SetupTopSQLForTest(collector)
+	sqlCPUCollector := tracecpu.NewSQLCPUCollector(collector)
+	sqlCPUCollector.Start()
+	sqlCPUCollector.Enable()
```
Comment (zhongzc) [inline server/tidb_test.go:1287]:
```suggestion
```

File: util/cpuprofile/consumer.go [hunk 7]
```diff
@@ -0,0 +1,105 @@
+// Copyright 2021 PingCAP, Inc.
```
Comment (zhongzc) [inline util/cpuprofile/consumer.go:1]: `consumer.go` is too general. I think this file can be combined with `handler.go` as `pprof_api.go`

File: util/cpuprofile/cpuprofile_test.go [hunk 8]
```diff
@@ -0,0 +1,255 @@
...
+
+func TestMain(m *testing.M) {
+	testbridge.WorkaroundGoCheckFlags()
+	goleak.VerifyTestMain(m)
+}
+
+func TestParallelCPUProfiler(t *testing.T) {
+	if GlobalCPUProfiler != nil {
+		GlobalCPUProfiler.Close()
+	}
```
Comment (zhongzc) [inline util/cpuprofile/cpuprofile_test.go:42]:
```suggestion
	if GlobalCPUProfiler != nil {
		GlobalCPUProfiler.Close()
		GlobalCPUProfiler = nil
	}
```

File: util/cpuprofile/cpuprofile_test.go [hunk 9]
```diff
@@ -0,0 +1,255 @@
...
+	// Test register/unregister nil
+	Register(nil)
+	require.Equal(t, 0, GlobalCPUProfiler.ConsumersCount())
+	Unregister(nil)
+	require.Equal(t, 0, GlobalCPUProfiler.ConsumersCount())
+	require.False(t, GlobalCPUProfiler.inProfilingStatus())
+
+	// Test profile error and duplicate register.
+	dataCh := make(ProfileConsumer, 10)
+	err := pprof.StartCPUProfile(bytes.NewBuffer(nil))
```
Comment (zhongzc) [inline util/cpuprofile/cpuprofile_test.go:56]: I'm a bit curious about the purpose of calling `pprof.StartCPUProfile` directly, is that to prevent `GlobalCPUProfiler` from profiling successfully?

File: util/cpuprofile/cpuprofile_test.go [hunk 10]
```diff
@@ -0,0 +1,255 @@
...
+	GlobalCPUProfiler.Start()
+	defer GlobalCPUProfiler.Close()
+
+	// Test profile error
+	err := pprof.StartCPUProfile(bytes.NewBuffer(nil))
+	require.NoError(t, err)
+	err = GetCPUProfile(context.Background(), 1, bytes.NewBuffer(nil))
+	require.Error(t, err)
+	require.Equal(t, "cpu profiling already in use", err.Error())
+	pprof.StopCPUProfile()
```
Comment (zhongzc) [inline util/cpuprofile/cpuprofile_test.go:147]: Why do we need to test it failed, intentionally? Do you think someone will call `pprof.StartCPUProfile` directly?

Comment (crazycs520) [reply util/cpuprofile/cpuprofile_test.go:147]: The test was just used to improve the test coverage.

File: util/cpuprofile/cpuprofile_test.go (hunk 8 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile_test.go:42]: This is useless, since the next line, `GlobalCPUProfiler ` will be reassign a new value.

File: util/cpuprofile/cpuprofile_test.go (hunk 9 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile_test.go:56]: Yes

File: util/cpuprofile/cpuprofile.go [hunk 11]
```diff
@@ -0,0 +1,200 @@
...
+// The unregistered ProfileConsumer won't receive the cpu profile data any more.
+// This function is thread-safe.
+func Unregister(ch ProfileConsumer) {
+	GlobalCPUProfiler.unregister(ch)
+}
+
+// ParallelCPUProfiler is a cpu profiler.
+// With ParallelCPUProfiler, it is possible to have multiple profile consumer at the same time.
+// WARN: Only one running ParallelCPUProfiler is allowed in the process, otherwise some profiler may profiling fail.
+type ParallelCPUProfiler struct {
```
[the remark this answers is not in the document]
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go]: great, done.

File: util/cpuprofile/handler.go [hunk 12]
```diff
@@ -0,0 +1,87 @@
...
+	"strconv"
+
+	"github.com/pingcap/tidb/util/logutil"
+	"go.uber.org/zap"
+)
+
+// GetCPUProfile uses to get the cpu profile data from GlobalCPUProfiler.
+// You should use GetCPUProfile instead of `pprof.StartCPUProfile`, `pprof.StopCPUProfile`.
+// Otherwise you may fail, or affect the TopSQL feature and pprof profile HTTP API .
+func GetCPUProfile(ctx context.Context, seconds uint64, w io.Writer) error {
```
[the remark this answers is not in the document]
Comment (crazycs520) [reply util/cpuprofile/handler.go]: great, done.

File: util/cpuprofile/cpuprofile.go [hunk 13]
```diff
@@ -0,0 +1,243 @@
...
+	cs     map[ProfileConsumer]struct{}
+	notify chan struct{}
+
+	// some data cache for profiling.
+	data         *ProfileData
+	nextData     *ProfileData
+	lastDataSize int
+
+	started  atomic.Bool
+	closed   chan struct{}
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:93]: You can use a `context.WithCancel` and store the `CancelFn` and the `ctx` here, instead of manually develop this stop mechanism.

File: util/cpuprofile/cpuprofile.go [hunk 14]
```diff
@@ -0,0 +1,243 @@
...
+var (
+	errProfilerAlreadyStarted = errors.New("parallelCPUProfiler already started")
+	errProfilerAlreadyClosed  = errors.New("parallelCPUProfiler already closed")
+)
+
+func (p *parallelCPUProfiler) start() error {
+	if !p.started.CAS(false, true) {
+		return errProfilerAlreadyStarted
+	}
+	if p.isClosed.Load() {
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:116]: Actually this is not concurrent safe. There is a race condition from the API perspective that `p` is closed after this check. This effectively makes your API not concurrent safe. So if you cannot achieve concurrent safe, then do it with a lock, or simply provide a non concurrent safe API.

File: util/cpuprofile/cpuprofile.go [hunk 15]
```diff
@@ -0,0 +1,243 @@
...
+	}
+}
+
+var (
+	errProfilerAlreadyStarted = errors.New("parallelCPUProfiler already started")
+	errProfilerAlreadyClosed  = errors.New("parallelCPUProfiler already closed")
+)
+
+func (p *parallelCPUProfiler) start() error {
+	if !p.started.CAS(false, true) {
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:113]: This function is not concurrent safe, so that unfortunately your CAS means nothing.. It is even worse than a simple lock, or no concurrent guard at all.

File: util/cpuprofile/cpuprofile.go [hunk 16]
```diff
@@ -0,0 +1,243 @@
...
+	return globalCPUProfiler.consumersCount()
+}
+
+// parallelCPUProfiler is a cpu profiler.
+// With parallelCPUProfiler, it is possible to have multiple profile consumer at the same time.
+// WARN: Only one running parallelCPUProfiler is allowed in the process, otherwise some profiler may profiling fail.
+type parallelCPUProfiler struct {
+	sync.Mutex
+	cs     map[ProfileConsumer]struct{}
+	notify chan struct{}
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:85]: What does it notify? It would be great if this can be known from the name instead of reading the code thoroughly.

File: util/cpuprofile/cpuprofile.go [hunk 17]
```diff
@@ -0,0 +1,243 @@
...
+			if !p.inProfilingStatus() {
+				p.doProfiling()
+			}
+		case <-checkTicker.C:
+			p.doProfiling()
+		}
+	}
+}
+
+func (p *parallelCPUProfiler) doProfiling() {
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:177]: The name is misleading. A `doXxx` function in Golang usually means it does something and waits for it. But this function is not. Please either change your API name or change or implementation.

File: util/cpuprofile/cpuprofile.go [hunk 18]
```diff
@@ -0,0 +1,243 @@
...
+	if p.inProfilingStatus() {
+		p.stopCPUProfile()
+		p.sendToConsumers()
+	}
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:181]: How about simply: start profile -> wait 1s -> stop profile -> send to consumers? Then you don't need `inProfilingStatus`, `data`, `nextData` any more.

File: util/cpuprofile/cpuprofile.go [hunk 19]
```diff
@@ -0,0 +1,243 @@
...
+		select {
+		case c <- p.data:
+		default:
+			// ignore
+		}
+	}
+	p.Unlock()
+	p.lastDataSize = p.data.Data.Len()
+	p.data = nil
+}
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:243]: Please reduce your L82 to L243 to within 50 LOC. You made a simple thing really unnecessarily complex.

File: util/cpuprofile/pprof_api.go [hunk 20]
```diff
@@ -0,0 +1,204 @@
...
+		serveError(w, http.StatusInternalServerError, "Could not enable CPU profiling: "+err.Error())
+		return
+	}
+	// TODO: fix me.
+	// This can be fixed by always starts a 1 second profiling one by one,
+	// but to aggregate (merge) multiple profiles into one according to the precision.
+	//  |<-- 1s -->|
+	// -|----------|----------|----------|----------|----------|-----------|-----> Background profile task timeline.
+	//                            |________________________________|
+	//       (start cpu profile)  v                                v (stop cpu profile)    // expected profile timeline
```
Comment (breeswish) [inline util/cpuprofile/pprof_api.go:65]: Seems that this is already implemented.

File: util/cpuprofile/pprof_api.go [hunk 21]
```diff
@@ -0,0 +1,204 @@
...
+	firstRead chan struct{}
+	wg        sync.WaitGroup
+
+	dataCh   ProfileConsumer
+	profiles []*ProfileData
+	writer   io.Writer
+}
+
+// NewPprofAPICollector returns a new NewPprofAPICollector.
+func NewPprofAPICollector() *PprofAPICollector {
```
Comment (breeswish) [inline util/cpuprofile/pprof_api.go:93]: This is a bad naming. From the perspective of `PprofAPICollector`'s user: what does it collect? Does it collect a API? Why do I need to collect a API?

How about just call it `NewCPUProfiler`? This API looks nice:

CPUProfiler::Start(w)
CPUProfiler::Stop()

File: util/cpuprofile/cpuprofile.go [hunk 22]
```diff
@@ -0,0 +1,243 @@
...
+	"github.com/pingcap/tidb/metrics"
+	"github.com/pingcap/tidb/util"
+	"github.com/pingcap/tidb/util/logutil"
+	"go.uber.org/atomic"
+)
+
+var defProfileDuration = time.Second
+
+// globalCPUProfiler is the global CPU profiler.
+// If you want to create a new global cpu profiler, you should stop the old global cpu profiler.
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:33]: Maybe you should not ever want anybody to do this, since the rest of your package (for example, your Pprof API compatible layer) does not work well when `globalCPUProfiler` is substituted (for example, the registered consumers just lost) or use a non global `ParallelCPUProfiler`. They simply doesn't work at all. 

So, instead of suggesting someone to stop a global cpu profiler to create a new global one, you should warn people DO NOT EVER try to replace it.

File: util/cpuprofile/cpuprofile.go [hunk 23]
```diff
@@ -0,0 +1,243 @@
...
+// ProfileData contains the cpu profile data and some additional information.
+type ProfileData struct {
+	Data  *bytes.Buffer
+	Begin time.Time
+	End   time.Time
+	Error error
+}
+
+// StartCPUProfiler uses to start to run the global parallelCPUProfiler.
+func StartCPUProfiler() error {
```
Comment (zhongzc) [inline util/cpuprofile/cpuprofile.go:50]: What will happen if I call twice?

Comment (zhongzc) [reply util/cpuprofile/cpuprofile.go:50]: Got

File: util/cpuprofile/pprof_api.go [hunk 24]
```diff
@@ -0,0 +1,204 @@
...
+}
+
+// StopCPUProfile is a substitute for the `pprof.StopCPUProfile` function.
+func (pc *PprofAPICollector) StopCPUProfile() error {
+	if !pc.started.Load() {
+		return nil
+	}
+
+	// wait for reading least 1 profile data.
+	<-pc.firstRead
```
Comment (zhongzc) [inline util/cpuprofile/pprof_api.go:123]: Will deadlock happen?

File: util/cpuprofile/cpuprofile.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:50]: em... the name is `StartCPUProfiler`, not `StartCPUProfiling`, Is this also misleading?

File: util/cpuprofile/pprof_api.go (hunk 21 above)
Comment (crazycs520) [reply util/cpuprofile/pprof_api.go:93]: `CPUProfiler ` will conflict with `parallelCPUProfiler`? And it is just a consumer/collector, not really to do cpu profiling.
How about rename to `CPUProfileCollector`

File: util/cpuprofile/pprof_api.go (hunk 24 above)
Comment (crazycs520) [reply util/cpuprofile/pprof_api.go:123]: no, it should never happen.

File: util/cpuprofile/cpuprofile.go (hunk 22 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:33]: Great. I will remove this comment.

File: util/cpuprofile/cpuprofile.go (hunk 23 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:48]: The second call will get an error.

File: util/cpuprofile/cpuprofile.go (hunk 18 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go]: If I add a sleep 1s, then listen on `ctx.Done()` channel will not be timely.

File: util/cpuprofile/cpuprofile.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (breeswish) [reply util/cpuprofile/cpuprofile.go:48]: Of course, what does a CPU Profiler do? A CPU Profiler do profiling. So starting a CPU Profiler is starting CPU profiling, unless other people have looked at your implementation -- this already indicates that the name is bad, as the name is a part of the public API, where the quality of the API has nothing related with your implementation.

File: util/cpuprofile/cpuprofile.go (hunk 18 above)
Comment (breeswish) [reply util/cpuprofile/cpuprofile.go]: But why do you want to make it timely? What will happen if it is not listened timely?

File: util/topsql/tracecpu/profile.go [hunk 25]
```diff
@@ -15,35 +15,24 @@
 package tracecpu
```
Comment (breeswish) [inline util/topsql/tracecpu/profile.go:15]: As now there is a package called `topsql/reporter`, then how about moving this to `topsql/collector/cpu.go`?

File: util/topsql/tracecpu/profile.go [hunk 26]
```diff
@@ -62,123 +51,90 @@ type SQLCPUTimeRecord struct {
...
+		profileConsumer: make(cpuprofile.ProfileConsumer, 1),
+		collector:       c,
 	}
 }
 
-func (sp *sqlCPUProfiler) Run() {
-	logutil.BgLogger().Info("cpu profiler started")
-	go sp.startCPUProfileWorker()
+// Start uses to start to run SQLCPUCollector.
+func (sp *SQLCPUCollector) Start() {
```
Comment (breeswish) [inline util/topsql/tracecpu/profile.go:76]: How about reducing the API surface to only `Start` and `Stop`? The current API seems to be unsound - `disable` does not disable all data producing from `SQLCPUCollector`, and it only disables the CPU profiler. It is usually very rare that a module has `Start`, `Stop`, `Enable`, `Disable`.

File: util/topsql/tracecpu/profile.go [hunk 27]
```diff
@@ -62,123 +51,90 @@ type SQLCPUTimeRecord struct {
...
-func (sp *sqlCPUProfiler) startCPUProfileWorker() {
-	defer util.Recover("top-sql", "profileWorker", nil, false)
-	for {
-		if sp.IsEnabled() {
-			sp.doCPUProfile()
-		} else {
-			time.Sleep(time.Second)
-		}
-	}
+// Enable uses to enable the SQLCPUCollector to work.
```
Comment (breeswish) [inline util/topsql/tracecpu/profile.go:90]: This API design is very uncommon -- in your API design, a `Start` does not make it functional, but a `Enable` will make it functional. Then what does `Start` do? It is usually a signal of bad API design, as a good API design should be fully understandable and reasonable according to the public API (w/ API doc comments).

File: util/topsql/topsql.go [hunk 28]
```diff
@@ -50,16 +50,18 @@ func SetupTopSQL() {
...
-	tracecpu.GlobalSQLCPUProfiler.SetCollector(remoteReporter)
-	tracecpu.GlobalSQLCPUProfiler.Run()
 	stmtstats.SetupAggregator()
 }
 
+// SetupTopSQLForTest sets up the global top-sql reporter, it's exporting for test.
+func SetupTopSQLForTest(r reporter.TopSQLReporter) {
+	globalTopSQLReport = r
+}
+
```
Comment (breeswish) [inline util/topsql/topsql.go:60]: Maybe you will find your unit testing easier if it is not a "global", but a "default". The `package.DefaultXxx` pattern is widely used to make the API easy to use while maintaining testability, as for something `Default`, there is still possibility to be not a default, which makes it fully testable.

File: util/cpuprofile/cpuprofile.go [hunk 29]
```diff
@@ -0,0 +1,219 @@
...
+func (p *parallelCPUProfiler) unregister(ch ProfileConsumer) {
+	if ch == nil {
+		return
+	}
+	p.Lock()
+	delete(p.cs, ch)
+	p.Unlock()
+}
+
+func (p *parallelCPUProfiler) profilingLoop() {
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:155]: "Loop" is duplicated with "Cycle". They are same meanings. Please change names to clearly indicate their different roles.

File: util/cpuprofile/cpuprofile.go [hunk 30]
```diff
@@ -0,0 +1,219 @@
...
+	p.Lock()
+	defer p.Unlock()
+	if !p.started {
+		return
+	}
+	p.started = false
+	if p.cancel != nil {
+		p.cancel()
+	}
+	p.wg.Wait()
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:128]: There is a double wait here (the previous wait is at L119). Will this cause deadlocks?

File: util/cpuprofile/cpuprofile.go [hunk 31]
```diff
@@ -0,0 +1,219 @@
...
+		pprof.StopCPUProfile()
+		p.lastDataSize = p.data.Data.Len()
+		p.sendToConsumers()
+	}
+
+	// Only do cpu profiling when there are consumers.
+	if p.consumersCount() > 0 {
+		metrics.CPUProfileCounter.Inc()
+		p.data = &ProfileData{Data: bytes.NewBuffer(make([]byte, 0, p.lastDataSize)), Begin: time.Now()}
+		err := pprof.StartCPUProfile(p.data.Data)
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:187]: When error happens when calling `StartCPUProfile`, you should not call `StopCPUProfile`, as it is a violation of the pprof API design.

File: util/cpuprofile/cpuprofile.go (hunk 30 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:131]: yes, already fix me.

File: util/cpuprofile/cpuprofile.go (hunk 18 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go]: Not timely will slow down the test running.

File: util/cpuprofile/cpuprofile.go (hunk 31 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go]: resolved, done.

File: util/topsql/tracecpu/profile.go (hunk 25 above)
Comment (crazycs520) [reply util/topsql/tracecpu/profile.go:15]: You mean to create a new pkg which name is `collector`?

Comment (mornyx) [reply util/topsql/tracecpu/profile.go:15]: `tracecpu` and `stmtstats` both have their respective `Collector` definitions, and `RemoteTopSQLReporter` implements both of them. If we renamed `tracecpu` to `collector/cpu`, then `stmtstats` should also be renamed to `collector/stmtstats`.

File: util/cpuprofile/cpuprofile.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:47]: How about rename to `StartCPUProfileController?

File: util/topsql/state/state.go [hunk 32]
```diff
@@ -52,3 +52,11 @@ type State struct {
...
 	return GlobalState.Enable.Load()
 }
+
+// StateController is the interface uses to control the top SQL feature.
+type StateController interface {
+	// Enable the top SQL feature.
+	Enable()
+	// Disable the top SQL feature.
+	Disable()
+}
```
Comment (breeswish) [inline util/topsql/state/state.go:62]: Why do we need this interface?

File: util/topsql/reporter/reporter.go [hunk 33]
```diff
@@ -84,28 +85,42 @@ type RemoteTopSQLReporter struct {
...
+func (tsr *RemoteTopSQLReporter) Enable() {
+	tsr.sqlCPUCollector.Start()
+	topsqlstate.GlobalState.Enable.Store(true)
+}
+
+// Disable implemented StateController interface.
+func (tsr *RemoteTopSQLReporter) Disable() {
+	tsr.sqlCPUCollector.Stop()
+	topsqlstate.GlobalState.Enable.Store(false)
+}
```
Comment (breeswish) [inline util/topsql/reporter/reporter.go:117]: It seems incorrect that the external can control the top sql feature via the `tsr`. By design, the only way to control the top sql state is the reporter's internal logic. No other 3rd-parties are allowed to control.

File: util/topsql/state/state.go [hunk 34]
```diff
@@ -52,3 +52,11 @@ type State struct {
 func TopSQLEnabled() bool {
```
Comment (breeswish) [inline util/topsql/state/state.go:52]: Seems that usually this package is referenced as `topsqlstate`, so that this can be named as `Enabled`?

File: util/topsql/topsql.go [hunk 35]
```diff
@@ -50,17 +50,19 @@ func SetupTopSQL() {
...
 // RegisterPubSubServer registers TopSQLPubSubService to the given gRPC server.
 func RegisterPubSubServer(s *grpc.Server) {
-	if globalTopSQLReport != nil {
-		service := reporter.NewTopSQLPubSubService(globalTopSQLReport)
+	if register, ok := globalTopSQLReport.(reporter.DataSinkRegisterer); ok {
```
Comment (breeswish) [inline util/topsql/topsql.go:64]: Why not simply keep `globalTopSQLReport` in type `reporter.RemoteTopSQLReporter`? Then you don't need a type check any more.

File: util/topsql/topsql.go [hunk 36]
```diff
@@ -50,17 +50,19 @@ func SetupTopSQL() {
 	singleTargetDataSink = reporter.NewSingleTargetDataSink(remoteReporter)
 
 	globalTopSQLReport = remoteReporter
-
-	tracecpu.GlobalSQLCPUProfiler.SetCollector(remoteReporter)
-	tracecpu.GlobalSQLCPUProfiler.Run()
 	stmtstats.RegisterCollector(remoteReporter)
 	stmtstats.SetupAggregator()
 }
```
Comment (breeswish) [inline util/topsql/topsql.go:55]: How about use a init() to assign the `globalTopSQLReport`? Then you don't need to worry about it is possibly nil. You can start its internal goroutine later in `SetupTopSQL`.

File: util/topsql/reporter/reporter.go [hunk 37]
```diff
@@ -150,6 +165,7 @@ func (tsr *RemoteTopSQLReporter) RegisterPlan(planDigest []byte, normalizedPlan
 // Close implements TopSQLReporter.
 func (tsr *RemoteTopSQLReporter) Close() {
 	tsr.cancel()
+	tsr.sqlCPUCollector.Stop()
```
Comment (breeswish) [inline util/topsql/reporter/reporter.go:168]: What about other collectors? Do they need to be closed?

File: util/topsql/topsql.go (hunk 35 above)
Comment (crazycs520) [reply util/topsql/topsql.go:64]: `globalTopSQLReport` use `reporter.TopSQLReporter` is for the test, since some the use the `mock.TopSQLCollector`

File: util/topsql/topsql.go (hunk 36 above)
Comment (crazycs520) [reply util/topsql/topsql.go:60]: done.

File: util/topsql/reporter/reporter.go (hunk 37 above)
Comment (crazycs520) [reply util/topsql/reporter/reporter.go:163]: There are no other collectors in `RemoteTopSQLReporter`.

File: util/cpuprofile/cpuprofile.go [hunk 38]
```diff
@@ -0,0 +1,216 @@
...
+	}
+
+	// wait 1 second
+	select {
+	case <-p.ctx.Done():
+	case <-time.After(defProfileDuration):
+	}
+
+	pprof.StopCPUProfile()
+	p.lastDataSize = data.Data.Len()
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:194]: how about simply allocating a fixed size buffer by default? For now you are updating the `lastDataSize` for each time, but the size may vary, sometimes big and sometimes small. I'm afraid this might not be able to avoid all re-allocations.

File: util/cpuprofile/cpuprofile.go [hunk 39]
```diff
@@ -0,0 +1,216 @@
...
+
+func (p *parallelCPUProfiler) doProfiling() {
+	if p.consumersCount() == 0 {
+		return
+	}
+
+	data := &ProfileData{Data: bytes.NewBuffer(make([]byte, 0, p.lastDataSize)), Begin: time.Now()}
+	err := pprof.StartCPUProfile(data.Data)
+	if err != nil {
+		data.Error = err
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:181]: I'm not sure, but maybe both `data.Begin` and `data.End` doesn't need to exist?

File: util/cpuprofile/pprof_api.go [hunk 40]
```diff
@@ -0,0 +1,196 @@
...
+		firstRead: make(chan struct{}),
+		dataCh:    make(ProfileConsumer, 1),
+	}
+}
+
+// StartCPUProfile is a substitute for the `pprof.StartCPUProfile` function.
+// You should use this function instead of `pprof.StartCPUProfile`.
+// Otherwise you may fail, or affect the TopSQL feature and pprof profile HTTP API .
+func (pc *Collector) StartCPUProfile(w io.Writer) error {
+	if !pc.started.CAS(false, true) {
```
Comment (breeswish) [inline util/cpuprofile/pprof_api.go:99]: How about simply adding a lock or does not handle concurrent at all? I see that your `StopCPUProfile` is not thread-safe.

File: util/cpuprofile/pprof_api.go (hunk 24 above)
Comment (breeswish) [reply util/cpuprofile/pprof_api.go:115]: I do worry about this channel. For example, if there are problems for the global parallel collector, you may never receive any data? How about accepting the behavior that, if start and stop are called too close, there will be no data at all? Will it cause any problems?

File: util/cpuprofile/pprof_api.go [hunk 41]
```diff
@@ -0,0 +1,196 @@
...
+		if err != nil {
+			return nil, err
+		}
+		ds = append(ds, pd)
+	}
+
+	profileData, err := profile.Merge(ds)
+	if err != nil {
+		return nil, err
+	}
```
Comment (breeswish) [inline util/cpuprofile/pprof_api.go:165]: Maybe you can merge them one by one and there is no need to build extra array to store them?

File: util/cpuprofile/pprof_api.go [hunk 42]
```diff
@@ -0,0 +1,196 @@
...
+// Since TopSQL will set the sql_digest and plan_digest label, they are strange for other users.
+func (pc *Collector) removeLabel(profileData *profile.Profile) {
+	for _, s := range profileData.Sample {
+		for k := range s.Label {
+			if k == labelSQLDigest || k == labelPlanDigest {
+				delete(s.Label, k)
+			}
+		}
+	}
+}
```
Comment (breeswish) [inline util/cpuprofile/pprof_api.go:180]: How about only preserve the label you want? Otherwise this module must be aware of how top sql is implemented. It is not a good design.

File: util/topsql/collector/cpu.go [hunk 43]
```diff
@@ -0,0 +1,257 @@
...
+	if sp.cancel != nil {
+		sp.cancel()
+	}
+	sp.mu.Unlock()
+
+	sp.wg.Wait()
+	logutil.BgLogger().Info("sql cpu collector stopped")
+}
+
+func (sp *SQLCPUCollector) collectSQLCPULoop() {
```
Comment (breeswish) [inline util/topsql/collector/cpu.go:106]: I suspect your register and unregister can be greatly simplified (or even removed) if you do this:

```
c := new CPU profiler
loop {
    if Enabled {
        c.StartCPUProfiler(w)
        thread.Sleep(1s)
        c.StopCPUProfiler()
        // deal with data in w
    }
    // wait ticker
}
```

**Review by breeswish — COMMENTED** [review]
the rest LGTM

File: util/cpuprofile/cpuprofile.go (hunk 38 above)
Comment (breeswish) [reply util/cpuprofile/cpuprofile.go:194]: I'm not sure whether a sync pool is a better choice if you really like to reduce allocations here.

File: util/topsql/state/state.go (hunk 34 above)
Comment (crazycs520) [reply util/topsql/state/state.go:62]: How about do this refactor in another PR, since this PR already very large.

File: util/cpuprofile/cpuprofile.go (hunk 38 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:194]: The problem is, the profile data size may vary in different kinds of loads, so It is hard to find a suitable `fixed size`.

But if the loads are same, then the profile data size of each second should also similar. And we can assume the load per second is similar to the previous second.

Comment (breeswish) [reply util/cpuprofile/cpuprofile.go:194]: How about aligning with 4KB boundaries? e.g. always to be (4 * N) KB. In this way, small workload varies will still be suitable while also possible to adjust dynamically when the workload changes drastically.

File: util/cpuprofile/cpuprofile.go (hunk 39 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:179]: great, already removed.

File: util/cpuprofile/pprof_api.go (hunk 40 above)
Comment (crazycs520) [reply util/cpuprofile/pprof_api.go]: done.

File: util/cpuprofile/pprof_api.go (hunk 24 above)
Comment (crazycs520) [reply util/cpuprofile/pprof_api.go]: Ok, I alread add another timeout here.

File: util/cpuprofile/pprof_api.go (hunk 41 above)
Comment (crazycs520) [reply util/cpuprofile/pprof_api.go]: great, done.

File: util/topsql/collector/cpu.go (hunk 43 above)
Comment (crazycs520) [reply util/topsql/collector/cpu.go:108]: addressed, PTAL again.

File: util/cpuprofile/pprof_api.go (hunk 42 above)
Comment (crazycs520) [reply util/cpuprofile/pprof_api.go]: ok

File: util/cpuprofile/cpuprofile.go (hunk 38 above)
Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:192]: ok

File: util/topsql/collector/cpu.go (hunk 43 above)
Comment (breeswish) [reply util/topsql/collector/cpu.go:108]: No, I mean there is no need to create a profileConsumer by yourself. Just use your `cpuprofile.Collector` is enough. It has already encapsulated an API that is easy to use (with simple Start and Stop). The only thing you need to modify is to make it possible to specify what label to preserve. For Top SQL, it needs to preserve SQL digest labels. For HTTP, it needs to preserve SQL text labels. So the label to preserve should be able to configured.

File: util/topsql/collector/test [hunk 44]
```diff
@@ -0,0 +1,54 @@
+mode: set
```
Comment (breeswish) [inline util/topsql/collector/test]: What's this?

Comment (crazycs520) [reply util/topsql/collector/test]: a mistake, already removed.

File: util/topsql/collector/cpu.go [hunk 45]
```diff
@@ -0,0 +1,260 @@
...
+func NewSQLCPUCollector(c Collector) *SQLCPUCollector {
+	return &SQLCPUCollector{
+		collector: c,
+	}
+}
+
+// Start uses to start to run SQLCPUCollector.
+// This will register a consumer into globalCPUProfiler, then SQLCPUCollector will receive cpu profile data per seconds.
+func (sp *SQLCPUCollector) Start() {
+	sp.mu.Lock()
```
Comment (breeswish) [inline util/topsql/collector/cpu.go:76]: I'm not sure, but seems that the start doesn't need to be thread-safe?

File: util/topsql/collector/cpu.go [hunk 46]
```diff
@@ -0,0 +1,260 @@
...
+}
+
+// Stop uses to stop the SQLCPUCollector.
+func (sp *SQLCPUCollector) Stop() {
+	sp.mu.Lock()
+	if !sp.stared {
+		sp.mu.Unlock()
+		return
+	}
+	sp.stared = false
```
Comment (breeswish) [inline util/topsql/collector/cpu.go:96]: typo: it should be `started`

**Review by breeswish — APPROVED** [review]
Generally looks good.  I guess SQLCPUCollector does not need to be thread-safe for its Start and Stop.

File: util/topsql/reporter/single_target.go [hunk 47]
```diff
@@ -63,19 +63,23 @@ func NewSingleTargetDataSink(registerer DataSinkRegisterer) *SingleTargetDataSin
...
+	return dataSink
+}
 
+// Start starts to run SingleTargetDataSink.
+func (ds *SingleTargetDataSink) Start() {
 	addr := config.GetGlobalConfig().TopSQL.ReceiverAddress
 	if addr != "" {
-		dataSink.curRPCAddr = addr
-		if err := registerer.Register(dataSink); err != nil {
+		ds.curRPCAddr = addr
```
Comment (breeswish) [inline util/topsql/reporter/single_target.go:73]: Seems that when address is empty at that time, register will not be called. Will register be called later when address becomes not empty?

File: util/topsql/state/state.go [hunk 48]
```diff
@@ -48,6 +48,16 @@ type State struct {
 	ReportIntervalSeconds *atomic.Int64
 }
 
+// EnabledTopSQL enable the top SQL feature.
+func EnabledTopSQL() {
```
Comment (breeswish) [inline util/topsql/state/state.go:52]: This should be called `EnableTopSQL`. `Enable` is a verb. `Enabled` is a state.

File: util/topsql/state/state.go [hunk 49]
```diff
@@ -48,6 +48,16 @@ type State struct {
...
+	GlobalState.Enable.Store(true)
+}
+
+// DisabledTopSQL disable the top SQL feature.
+func DisabledTopSQL() {
```
Comment (breeswish) [inline util/topsql/state/state.go:57]: This should be called `DisableTopSQL`.

File: util/topsql/state/state.go [hunk 50]
```diff
@@ -48,6 +48,16 @@ type State struct {
 	ReportIntervalSeconds *atomic.Int64
 }
 
+// EnabledTopSQL enable the top SQL feature.
```
Comment (breeswish) [inline util/topsql/state/state.go:51]:
```suggestion
// EnableTopSQL enables the top SQL feature.
```

File: util/topsql/collector/cpu.go (hunk 45 above)
Comment (crazycs520) [reply util/topsql/collector/cpu.go]: ok

File: util/topsql/state/state.go (hunk 48 above)
Comment (crazycs520) [reply util/topsql/state/state.go]: great

File: util/topsql/reporter/single_target.go (hunk 47 above)
Comment (crazycs520) [reply util/topsql/reporter/single_target.go:73]: Yes, it will be called later in `trySwitchRegistration`.

**Review by breeswish — APPROVED** [review]

**Review by zhongzc — APPROVED** [review]
LGTM

**Review by tangenta — APPROVED** [review]
