### PR TITLE
executor: fix wrong is-null result of ShowExec.fetchShowIndex

### LINKED ISSUE #19507: show index got wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t2(a int primary key, b int unique, c int not null, unique index (c));
show create table t2;
show index in t2;
```
### 2. What did you expect to see? (Required)
The `Null` column of c is null
```
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| t2    | 0          | PRIMARY  | 1            | a           | A         | 0           | <null>   | <null> |      | BTREE      |         |               | YES     | NULL       |
| t2    | 0          | c        | 1            | c           | A         | 0           | <null>   | <null> |      | BTREE      |         |               | YES     | NULL       |
| t2    | 0          | b        | 1            | b           | A         | 0           | <null>   | <null> | YES  | BTREE      |         |               | YES     | NULL       |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+

```

### 3. What did you see instead (Required)
The `Null` column of c is `YES`
```sql
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| t2    | 0          | PRIMARY  | 1            | a           | A         | 0           | <null>   | <null> |      | BTREE      |         |               | YES     | NULL       |
| t2    | 0          | c        | 1            | c           | A         | 0           | <null>   | <null> | YES  | BTREE      |         |               | YES     | NULL       |
| t2    | 0          | b        | 1            | b           | A         | 0           | <null>   | <null> | YES  | BTREE      |         |               | YES     | NULL       |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+

```
### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1034-g1b56a070e                    |
| Edition: Community                                                |
| Git Commit Hash: 1b56a070ebd56a2b86b5b06e72cc7cbc434344d8         |
| Git Branch: master                                                |
| UTC Build Time: 2020-08-25 14:37:44                               |
| GoVersion: go1.13                                                 |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+

```

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @XuHuaiyu

### PR DESCRIPTION
**Pull request by LENSHOOD**
### What problem does this PR solve?

Issue Number: close #19507 

Problem Summary:

The `SHOW INDEX IN {table}` executor may get wrong result about column "is null".
e.g.:
```sql
mysql> CREATE TABLE t2(a int primary key, b int unique, c int not null, unique index (c));
```
Expected:
```sql
mysql> SHOW INDEX IN t2;
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| t2    |          0 | PRIMARY  |            1 | a           | A         |           0 |     NULL | NULL   |      | BTREE      |         |               | YES     | NULL       |
| t2    |          0 | c        |            1 | c           | A         |           0 |     NULL | NULL   |      | BTREE      |         |               | YES     | NULL       |
| t2    |          0 | b        |            1 | b           | A         |           0 |     NULL | NULL   | YES  | BTREE      |         |               | YES     | NULL       |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
3 rows in set (0.00 sec)
```
Actual:
```sql
mysql> SHOW INDEX IN t2;
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| t2    |          0 | PRIMARY  |            1 | a           | A         |           0 |     NULL | NULL   |      | BTREE      |         |               | YES     | NULL       |
| t2    |          0 | c        |            1 | c           | A         |           0 |     NULL | NULL   | YES  | BTREE      |         |               | YES     | NULL       |
| t2    |          0 | b        |            1 | b           | A         |           0 |     NULL | NULL   | YES  | BTREE      |         |               | YES     | NULL       |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
3 rows in set (0.00 sec)
```
As we can see, the actual non-null column "c" was mistakenly displayed as null.

The reason is the logic to judge whether the index column is or not null - which locate at `ShowExec`(`show.go`) - are carelessly assume all index column are "NULL" except the primary key:
```go
nullVal := "YES"
if idx.Meta().Name.O == mysql.PrimaryKeyName {
    nullVal = ""
}
```

Actually we should deal with "NULL" check by column flag` NotNullFlag` defined at `mysql/type.go` .

### What is changed and how it works?

What's Changed:
Refine the null value fetcher to check by column flag `NotNullFlag`.

How it Works:
Find column by column name, then call `Column.Flag` to get the flag and check null by `mysql.HasNotNullFlag`.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix wrong column "is-null" result of show index

### CODE REVIEW

**Comment by LENSHOOD** [comment]
@ti-srebot run-all-tests

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

**Comment by LENSHOOD** [comment]
@ti-srebot /run-unit-test

**Comment by LENSHOOD** [comment]
@lzmhhh123 
The `common-test` and `integration-common-test` fail are all same:
```
we need(227):\nSHOW INDEXES FROM t1;\nTable\tNon_unique\tKey_name\tSeq_in_index\tColumn_name\tCollation\tCardinality\tSub_part\tPacked\tNull\tIndex_type\tComment\tIndex_comment\tVisible\tExpression\nt1\t1\tint_field\t1\tint_field\tA\t0\tNULL\tNULL\tYES\tBTREE\t\t\tYES\tNU\n

but got(227):\nSHOW INDEXES FROM t1;\nTable\tNon_unique\tKey_name\tSeq_in_index\tColumn_name\tCollation\tCardinality\tSub_part\tPacked\tNull\tIndex_type\tComment\tIndex_comment\tVisible\tExpression\nt1\t1\tint_field\t1\tint_field\tA\t0\tNULL\tNULL\t\tBTREE\t\t\tYES\tNULL\n\n"
```

What the difference of "need" and "got" are exactly what I fixed in this PR.

**Seems those test cases are broken and need to update ?**

**Comment by LENSHOOD** [comment]
@ti-srebot /run-unit-test

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

**Review by AilinKid — COMMENTED** [review]
LGTM

File: executor/show.go [hunk 1]
```diff
@@ -587,8 +587,13 @@ func (e *ShowExec) fetchShowIndex() error {
 				subPart = col.Length
 			}
 
+			tbCol, err := findColumnByName(tb.Cols(), col.Name.O)
```
Comment (tangenta) [inline executor/show.go:590]: We can use `tb.Meta().Columns[col.Offset]` to get the `ColumnInfo`.

Comment (LENSHOOD) [reply executor/show.go:590]: Thx, I'll give it a try.

**Comment by LENSHOOD** [comment]
@ti-srebot /run-unit-test

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
