### PR TITLE
executor, planner: fix some cases for natural_using_join

### LINKED ISSUE #15844: NATURAL RIGHT JOIN results in an unexpected "Unknown column" error
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
SELECT t0.c0 FROM t0 NATURAL RIGHT JOIN t1 WHERE t1.c0; -- Unknown column 't0.c0' in 'field list'
```
Unexpectedly, the `SELECT` results in an error `ERROR 1054 (42S22): Unknown column 't0.c0' in 'field list'`. I would expect the SELECT to execute without errors, fetching no rows.

When removing the `WHERE` condition, the query executes as expected:
```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
SELECT t0.c0 FROM t0 NATURAL RIGHT JOIN t1; -- {}
```
It also works to not explicitly refer to `t0.c0`:
```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
SELECT * FROM t0 NATURAL RIGHT JOIN t1; -- {}
```

Environment:
```
mysql> SELECT tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-75-ga6de0e38d-dirty
Git Commit Hash: a6de0e38d49c97671d316590c8c945eb518ca2b2
Git Branch: master
UTC Build Time: 2020-03-26 12:11:33
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #20441: Unknown column 't3.i' in 'order clause'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
DROP TABLE if exists t1, t2, t3;
create table t1 (i int);
create table t2 (i int);
create table t3 (i int);
select * from t1,t2 natural left join t3 order by t1.i,t2.i,t3.i;
select t1.i,t2.i,t3.i from t2 natural left join t3,t1 order by t1.i,t2.i,t3.i;
select * from t1,t2 natural right join t3 order by t1.i,t2.i,t3.i;
select t1.i,t2.i,t3.i from t2 natural right join t3,t1 order by t1.i,t2.i,t3.i;
```
### 2. What did you expect to see? (Required)
```
mysql> select * from t1,t2 natural left join t3 order by t1.i,t2.i,t3.i;
Empty set (0.00 sec)
mysql> select t1.i,t2.i,t3.i from t2 natural left join t3,t1 order by t1.i,t2.i,t3.i;
Empty set (0.01 sec)
mysql> select * from t1,t2 natural right join t3 order by t1.i,t2.i,t3.i;
Empty set (0.00 sec)
mysql> select t1.i,t2.i,t3.i from t2 natural right join t3,t1 order by t1.i,t2.i,t3.i;
Empty set (0.01 sec)
```

### 3. What did you see instead (Required)
```
mysql> select * from t1,t2 natural left join t3 order by t1.i,t2.i,t3.i;
ERROR 1054 (42S22): Unknown column 't3.i' in 'order clause'
mysql> select t1.i,t2.i,t3.i from t2 natural left join t3,t1 order by t1.i,t2.i,t3.i;
ERROR 1054 (42S22): Unknown column 't3.i' in 'order clause'
mysql> select * from t1,t2 natural right join t3 order by t1.i,t2.i,t3.i;
ERROR 1054 (42S22): Unknown column 't2.i' in 'order clause'
mysql> select t1.i,t2.i,t3.i from t2 natural right join t3,t1 order by t1.i,t2.i,t3.i;
ERROR 1054 (42S22): Unknown column 't2.i' in 'order clause'
```
### 4. What is your TiDB version? (Required)

master a17d3a978a2483e6a40981fc72d787893f8d0372 and release-4.0 8c6879c3f2f2c1b3ae8f570eafab448e3aaa2333

### LINKED ISSUE #20476: ERROR 1051 (42S02): Unknown table 't2'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists t1;
create table t1(a int);
select t1.*, t2.* from t1 join t1 t2 using(a);
```
### 2. What did you expect to see? (Required)
```
mysql> select t1.*, t2.* from t1 join t1 t2;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select t1.*, t2.* from t1 join t1 t2 using(a);
ERROR 1051 (42S02): Unknown table 't2'
```

### 4. What is your TiDB version? (Required)

master cd16de894b4bc523bc6b7dd6241ab6f0e608a6fb and release-4.0 c71000046cf1c5ade501cc2b14d3b130863f366d

### LINKED ISSUE #20477: the result returned doesn't exist 't2.a' column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE t1 (
  grp int(11) default NULL,
  a bigint(20) unsigned default NULL,
  c char(10) NOT NULL default ''
) ENGINE=MyISAM;
INSERT INTO t1 VALUES (1,1,'a'),(2,2,'b'),(2,3,'c'),(3,4,'E'),(3,5,'C'),(3,6,'D'),(NULL,NULL,'');
create table t2 (id int, a bigint unsigned not null, c char(10), d int, primary key (a));
insert into t2 values (1,1,"a",1),(3,4,"A",4),(3,5,"B",5),(3,6,"C",6),(4,7,"D",7);
select t1.*, t2.* from t1 left join t2 using(a);
```

### 2. What did you expect to see? (Required)
mysql 8.0.14
```
mysql> select t1.*, t2.* from t1 left join t2 using(a);
+------+------+---+------+------+------+------+
| grp  | a    | c | id   | a    | c    | d    |
+------+------+---+------+------+------+------+
|    1 |    1 | a |    1 |    1 | a    |    1 |
|    2 |    2 | b | NULL | NULL | NULL | NULL |
|    2 |    3 | c | NULL | NULL | NULL | NULL |
|    3 |    4 | E |    3 |    4 | A    |    4 |
|    3 |    5 | C |    3 |    5 | B    |    5 |
|    3 |    6 | D |    3 |    6 | C    |    6 |
| NULL | NULL |   | NULL | NULL | NULL | NULL |
+------+------+---+------+------+------+------+
7 rows in set (0.01 sec)
```
### 3. What did you see instead (Required)
```
mysql> select t1.*, t2.* from t1 left join t2 using(a);
+------+------+---+------+------+------+
| a    | grp  | c | id   | c    | d    |
+------+------+---+------+------+------+
|    1 |    1 | a |    1 | a    |    1 |
|    2 |    2 | b | NULL | NULL | NULL |
|    3 |    2 | c | NULL | NULL | NULL |
|    4 |    3 | E |    3 | A    |    4 |
|    5 |    3 | C |    3 | B    |    5 |
|    6 |    3 | D |    3 | C    |    6 |
| NULL | NULL |   | NULL | NULL | NULL |
+------+------+---+------+------+------+
7 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master cd16de894b4bc523bc6b7dd6241ab6f0e608a6fb and release-4.0 c71000046cf1c5ade501cc2b14d3b130863f366d

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 900

## Mentor

* @lzmhhh123

### LINKED ISSUE #20958: The query result using INNER JOIN xxx USING(col1) didn't return col1 value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t1(id int, name varchar(20));
create table t2(id int, address varchar(30));
insert into t1 values(1,'gangshen');
insert into t2 values(1,'HangZhou');
select t2.* from t1 inner join t2 using (id) limit 1;
select t2.* from t1 inner join t2 on t1.id = t2.id  limit 1;
```

### 2. What did you expect to see? (Required)

- MySQL-8.0.19
```
root@127.0.0.1 : gangshen 07:23:45> select t2.* from t1 inner join t2 using (id) limit 1;
+------+----------+
| id   | address  |
+------+----------+
|    1 | HangZhou |
+------+----------+
1 row in set (0.01 sec)

root@127.0.0.1 : gangshen 07:23:50> select t2.* from t1 inner join t2 on t1.id = t2.id  limit 1;
+------+----------+
| id   | address  |
+------+----------+
|    1 | HangZhou |
+------+----------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```
MySQL [gangshen]> select t2.* from t1 inner join t2 using (id) limit 1;
+----------+
| address  |
+----------+
| HangZhou |
+----------+
1 row in set (0.01 sec)

MySQL [gangshen]> select t2.* from t1 inner join t2 on t1.id = t2.id  limit 1;
+------+----------+
| id   | address  |
+------+----------+
|    1 | HangZhou |
+------+----------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)
```
MySQL [gangshen]> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.8
Edition: Community
Git Commit Hash: 66ac9fc31f1733e5eb8d11891ec1b38f9c422817
Git Branch: heads/refs/tags/v4.0.8
UTC Build Time: 2020-10-30 08:21:16
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: 
close #20477 
close #20441 
close #15844 
close #20958
close #20476
 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Support querying the coalesced columns in natural_using_join.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

/AN

### Release note 

- Fix the bug that can not query the coalesced column when use using-join.

### CODE REVIEW

File: planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -1644,27 +1644,42 @@ func (er *expressionRewriter) toColumn(v *ast.ColumnName) {
...
+	switch x := p.(type) {
+	case *LogicalLimit, *LogicalSelection, *LogicalTopN, *LogicalSort, *LogicalMaxOneRow:
+		return findFieldNameFromNaturalUsingJoin(p.Children()[0], v)
+	case *LogicalJoin:
+		if x.redundantSchema != nil {
+			idx, err := expression.FindFieldName(x.redundantNames, v)
+			if err != nil {
+				return nil, nil, err
+			}
+			if idx >= 0 {
```
Comment (lzmhhh123) [inline planner/core/expression_rewriter.go:1675]: Do we need to recursively find `redundantNames` for `LogicalJoin` if can't find it.

Comment (XuHuaiyu) [reply planner/core/expression_rewriter.go:1675]: No, the inner redundantNames will be appended to the outer redundantNames.

Comment (lzmhhh123) [reply planner/core/expression_rewriter.go:1675]: OK, then others LGTM.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -799,8 +799,14 @@ func (b *PlanBuilder) coalesceCommonColumns(p *LogicalJoin, leftPlan, rightPlan
 
 	p.SetSchema(expression.NewSchema(schemaCols...))
 	p.names = names
-	p.redundantSchema = expression.MergeSchema(p.redundantSchema, expression.NewSchema(rColumns[:commonLen]...))
-	p.redundantNames = append(p.redundantNames.Shallow(), rNames[:commonLen]...)
+	if joinTp == ast.RightJoin {
+		leftPlan, rightPlan = rightPlan, leftPlan
+	}
+	p.redundantSchema = expression.MergeSchema(p.redundantSchema, expression.NewSchema(rightPlan.Schema().Clone().Columns...))
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:805]: Add comment for this part.

File: planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -978,6 +980,19 @@ func (b *PlanBuilder) buildProjectionField(ctx context.Context, p LogicalPlan, f
 	return newCol, name, nil
 }
 
+func findColFromNaturalUsingJoin(p LogicalPlan, col *expression.Column) (name *types.FieldName) {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:983]: Add comment for the function header.

File: planner/core/logical_plan_builder.go [hunk 4]
```diff
@@ -1634,14 +1649,26 @@ func (a *havingWindowAndOrderbyExprResolver) resolveFromPlan(v *ast.ColumnNameEx
 	if err != nil {
 		return -1, err
 	}
+	schemaCols, outputNames := p.Schema().Columns, p.OutputNames()
 	if idx < 0 {
-		return -1, nil
+		switch x := p.(type) {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:1654]: Add comment for this switch clause

**Review by winoros — COMMENTED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
