### PR TITLE
util: fix bad number error with DISTINCT when dividing long decimals

### LINKED ISSUE #15563: Bad Number: error with DISTINCT when dividing long decimals
The below session (version 5.7.25-TiDB-v3.0.12) illustrates a bug when DISTINCT is used while dividing two long numbers. When a digit is removed from the second number, it succeeds. It also succeeds if DISTINCT is removed.

```
MySQL [(none)]> select distinct 0.7544678906163867 /  0.68234634;
ERROR 1105 (HY000): Bad Number
MySQL [(none)]> select 0.7544678906163867 /  0.68234634;
+----------------------------------+
| 0.7544678906163867 /  0.68234634 |
+----------------------------------+
|           1.10569639842486251190 |
+----------------------------------+
1 row in set (0.001 sec)

MySQL [(none)]> select distinct 0.7544678906163867 /  0.6823463;
+---------------------------------+
| 0.7544678906163867 /  0.6823463 |
+---------------------------------+
|          1.10569646324217878810 |
+---------------------------------+
1 row in set (0.001 sec)
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #15563 

Problem Summary:

### What is changed and how it works?

What's Changed:
fix bad number error with DISTINCT when dividing long decimals
How it Works:
set precision and frac before calling `EncodeDecimal`
### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- No release note

### CODE REVIEW

**Comment by b41sh** [comment]
LGTM

File: util/codec/codec.go [hunk 1]
```diff
@@ -1209,7 +1209,15 @@ func HashGroupKey(sc *stmtctx.StatementContext, n int, col *chunk.Column, buf []
...
 				buf[i] = append(buf[i], decimalFlag)
-				buf[i], err = EncodeDecimal(buf[i], &ds[i], ft.Flen, ft.Decimal)
+				precision := ft.Flen
+				frac := ft.Decimal
+				if precision == 0 {
+					precision, frac = ds[i].PrecisionAndFrac()
+				}
+				if frac > mysql.MaxDecimalScale {
+					frac = mysql.MaxDecimalScale
+				}
```
Comment (Reminiscent) [inline util/codec/codec.go:1219]: Should we add this to `EncodeDecimal` rather than here? Because `EncodeDecimal` is also called elsewhere, this problem may also occur here?

Comment (TszKitLo40) [reply util/codec/codec.go]: Yes, I think so and I have moved the logic to `EncodeDecimal`.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
