### PR TITLE
executor: make index merge join close gracefully when tasks not finish

### LINKED ISSUE #18068: index merge join hang when call `Close function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
executes twice
```sql
SELECT /*+ INL_JOIN(uc) */ 1 FROM user_class uc JOIN class c ON (uc.class_id = c.class_id AND c.state = '1') WHERE c.school_id = 120052 LIMIT 0, 1000;
```

### 2. What did you expect to see? (Required)
Both queries get the right results.

### 3. What did you see instead (Required)
The second query hangs.
image

### 4. Affected version (Required)
v4.0

### 5. Root Cause Analysis
Index merge join can't close the outer worker.

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #18068 

Problem Summary: PTAL at the #18068 

### What is changed and how it works?

What's Changed: make it close outer worker gracefully.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- make index merge join executor close gracefully when tasks not finish

### CODE REVIEW

File: executor/index_lookup_merge_join.go [hunk 1]
```diff
@@ -331,6 +336,8 @@ func (omw *outerMergeWorker) run(ctx context.Context, wg *sync.WaitGroup, cancel
 
 func (omw *outerMergeWorker) pushToChan(ctx context.Context, task *lookUpMergeJoinTask, dst chan<- *lookUpMergeJoinTask) (finished bool) {
 	select {
+	case <-omw.lookup.closeCh:
```
Comment (SunRunAway) [inline executor/index_lookup_merge_join.go:339]: `case <-ctx.Done()` can be used to exit this method.
