### PR TITLE
ddl: fix CREATE GLOBAL TEMPORARY TABLE ... LIKE creates a normal table

### LINKED ISSUE #25613: `CREATE GLOBAL TEMPORARY TABLE ... LIKE` creates a normal table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> create table tb2(id int);
Query OK, 0 rows affected (0.07 sec)

mysql> create global temporary table tb3 like tb2 on commit delete rows;
Query OK, 0 rows affected (0.07 sec)

mysql> show create table tb3;
+-------+--------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                 |
+-------+--------------------------------------------------------------------------------------------------------------+
| tb3   | CREATE TABLE `tb3` (
  `id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+--------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

### 2. What did you expect to see? (Required)

`show create table` shows a global temporary table.

### 3. What did you see instead (Required)

It shows a normal table.

### 4. What is your TiDB version? (Required)

mysql> select version();
+----------------------------------------+
| version()                              |
+----------------------------------------+
| 5.7.25-TiDB-v5.2.0-alpha-88-ged52601e6 |
+----------------------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by Howie59**
### What problem does this PR solve?

Issue Number: close #25613

### What is changed and how it works?

Proposal: [temporary table](https://github.com/pingcap/tidb/issues/24169)

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -1815,6 +1815,13 @@ func (d *ddl) CreateTable(ctx sessionctx.Context, s *ast.CreateTableStmt) (err e
 	if err != nil {
 		return errors.Trace(err)
 	}
+	switch s.TemporaryKeyword {
+	case ast.TemporaryGlobal:
+		tbInfo.TempTableType = model.TempTableGlobal
+	case ast.TemporaryLocal:
+		tbInfo.TempTableType = model.TempTableLocal
+	default:
+	}
```
Comment (djshow832) [inline ddl/ddl_api.go:1824]: It's already checked in `buildTableInfoWithStmt` but it's more complete. E.g. It also checks `EnableGlobalTemporaryTable` and `OnCommitDelete`.
So I think you can extract that part as a function and call it both in `buildTableInfoWithLike` and `buildTableInfoWithStmt`.

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -1731,9 +1731,9 @@ func buildTableInfoWithStmt(ctx sessionctx.Context, s *ast.CreateTableStmt, dbCh
 	if err != nil {
 		return nil, errors.Trace(err)
 	}
+	setTemporaryType(tbInfo, s.TemporaryKeyword)
 	switch s.TemporaryKeyword {
```
Comment (djshow832) [inline ddl/ddl_api.go:1735]: This `switch case` is also needed for `create temporary tables like`.
E.g. If `EnableGlobalTemporaryTable` is disabled, or `OnCommitDelete` is omitted, an error is reported.
So you need to put this into `setTemporaryType`.

File: ddl/ddl_api.go [hunk 3]
```diff
@@ -1731,22 +1731,11 @@ func buildTableInfoWithStmt(ctx sessionctx.Context, s *ast.CreateTableStmt, dbCh
...
-		if !s.OnCommitDelete {
-			return nil, errors.Trace(errUnsupportedOnCommitPreserve)
-		}
-	case ast.TemporaryLocal:
-		// TODO: set "tbInfo.TempTableType = model.TempTableLocal" after local temporary table is supported.
-		tbInfo.TempTableType = model.TempTableNone
+	if err = setTemporaryType(ctx, tbInfo, s); err != nil {
+		return nil, errors.Trace(err)
+	}
+	if s.TemporaryKeyword == ast.TemporaryLocal {
```
Comment (djshow832) [inline ddl/ddl_api.go:1737]: I don't understand. Why leave this judgement out of `setTemporaryType`?

Comment (Howie59) [reply ddl/ddl_api.go:1737]: put it into the method would AppendWarning twice

**Comment by tiancaiamao** [comment]
I meet this bug too...

File: ddl/ddl_api.go [hunk 4]
```diff
@@ -1815,6 +1804,9 @@ func (d *ddl) CreateTable(ctx sessionctx.Context, s *ast.CreateTableStmt) (err e
 	if err != nil {
 		return errors.Trace(err)
 	}
+	if err = setTemporaryType(ctx, tbInfo, s); err != nil {
+		return errors.Trace(err)
+	}
```
Comment (djshow832) [inline ddl/ddl_api.go:1809]: You can't put it here. `buildTableInfoWithStmt` relies on `tbInfo.TempTableType`. 
For example, previously, `buildTableInfoWithStmt` sets `tbInfo.TempTableType` and then calls `handleTableOptions`. But `handleTableOptions` has such codes:
```go
    if tbInfo.TempTableType != model.TempTableNone {
```

File: ddl/ddl_api.go (hunk 3 above)
Comment (djshow832) [reply ddl/ddl_api.go:1737]: `CreateTable` calls `buildTableInfoWithLike` and `buildTableInfoWithStmt`. So there are 2 ways:
1. Call `setTemporaryType` only in `CreateTable`, which is impossible. Because `setTemporaryType` must be called in the middle of `buildTableInfoWithStmt`, unless you remove the dependence of `tbInfo.TempTableType` in `buildTableInfoWithStmt`.
2. Call `setTemporaryType` both in `buildTableInfoWithLike` and `buildTableInfoWithStmt`.

**Comment by djshow832** [comment]
> I meet this bug too...

Did you meet the case `create global temporary table like a global temporary table`?

File: ddl/serial_test.go [hunk 5]
```diff
@@ -613,6 +613,23 @@ func (s *testSerialSuite) TestCreateTableWithLikeAtTemporaryMode(c *C) {
 	c.Assert(err, IsNil)
 	tableInfo := table.Meta()
 	c.Assert(len(tableInfo.ForeignKeys), Equals, 0)
+
+	// Issue 25613.
+	tk.MustExec("drop table if exists tb2, tb3")
+	tk.MustExec("create table tb2(id int);")
+	tk.MustExec("create global temporary table tb3 like tb2 on commit delete rows;")
```
Comment (djshow832) [inline ddl/serial_test.go:620]: Try `create global temporary table tb3 like tb2` and `create table tb3 like tb2 on commit delete rows` first.

**Comment by tiancaiamao** [comment]
> > I meet this bug too...
> 
> Did you meet the case `create global temporary table like a global temporary table`? @tiancaiamao

No, I mean create a global temporary table from a normal table...

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
This PR does exactly what its title says: fix CREATE GLOBAL TEMPORARY TABLE ... LIKE creates a normal table

Maybe we can pay more attention to the combinations, it's a complex matrix:

| from \ to              | normal table  | global temporary table | local temporary table |
| -------------          | ------------- | -----                  | ---                   |
| normal table           | yes  (done)         | yes   (this PR)                  | ?                    |
| global temporary table | no           | yes  (?)                  | ?                    |
| local temporary table  | ?             | ?                      | ?                     |

**Comment by Howie59** [comment]
PTAL @djshow832

**Review by djshow832 — APPROVED** [review]

**Comment by tiancaiamao** [comment]
ref https://github.com/pingcap/tidb/pull/25724
