### PR TITLE
executor: get the right result for stmt `select ... for update union select …`

### LINKED ISSUE #31530: Wrong result for `select ... for update union select ...`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t1(a int); -- init
begin pessimistic; -- session1
select * from t1; -- session1
           insert into t1 values(1); --- session2
(select * from t1 for update) union all (select * from t1); -- session1
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t1;
Empty set (0.00 sec)

mysql> (select * from t1 for update) union all (select * from t1);
+------+
| a    |
+------+
|    1 |
+------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t1;
Empty set (0.00 sec)

mysql> (select * from t1 for update) union all (select * from t1);
+------+
| a    |
+------+
|    1 |
|    1 |
+------+
2 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

master

```
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.16.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #31530

Problem Summary:

### What is changed and how it works?

1. In `executorBuilder` , store `snapshotReadTS` and `forUpdateTS` separately. So every executor can get the right ts according to its own statement.
2.  Introduce `executorBuilder.forDataReaderBuilder` to indicate wether this builder is used by `dataReaderBuilder` . If it is true, the `getSnapshotTS` for executorBuilder is thread safe. This may be a better fix for #30468

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
`select ... for update union select` . The second query will use snapshot read ts instead of for update ts
```

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -9850,6 +9850,31 @@ func (s *testSerialSuite) TestFix31038(c *C) {
...
+	tk.MustExec("drop table if exists t1")
+	tk.MustExec("create table t1 (id int primary key, v int)")
+	tk.MustExec("insert into t1 values(1, 10)")
+	tk.MustExec("begin pessimistic")
+	tk.MustQuery("select * from t1").Check(testkit.Rows("1 10"))
+
+	// update t1 before session1 transaction not finished
+	tk2.MustExec("update t1 set v=11 where id=1")
+
+	tk.MustExec("set tidb_enable_list_partition=1")
```
Comment (tiancaiamao) [inline executor/executor_test.go:9870]: What's this?

**Review by tiancaiamao — APPROVED** [review]

File: executor/builder.go [hunk 2]
```diff
@@ -1476,8 +1489,35 @@ func (b *executorBuilder) buildTableDual(v *plannercore.PhysicalTableDual) Execu
...
+	if b.inInsertStmt || b.inUpdateStmt || b.inDeleteStmt || b.inSelectLockStmt {
+		return b.getForUpdateTS()
+	}
+
+	return b.getSnapshotReadTS()
+}
+
+// getSnapshotReadTS returns the ts used by insert/update/delete and select for update
+func (b *executorBuilder) getForUpdateTS() (uint64, error) {
+	ts, err := b.getSnapshotReadTS()
```
Comment (MyonKeminta) [inline executor/builder.go:1507]: The semantics of these terms of the TS names still looks confusing to me. Will it be better after your later refactoring?

File: executor/builder.go [hunk 3]
```diff
@@ -1476,8 +1489,35 @@ func (b *executorBuilder) buildTableDual(v *plannercore.PhysicalTableDual) Execu
 	return e
 }
 
-// `getSnapshotTS` returns the timestamp of the snapshot that a reader should read.
+// `getSnapshotTS` returns for-update-ts if in insert/update/delete/lock statement otherwise snapshot-read-ts
```
Comment (MyonKeminta) [inline executor/builder.go:1492]: I think maybe you can mention that under RC isolation level, the *for-update_ts* and the *snapshot-read-ts* are the same.

File: executor/builder.go [hunk 4]
```diff
@@ -86,7 +86,8 @@ var (
 type executorBuilder struct {
 	ctx              sessionctx.Context
 	is               infoschema.InfoSchema
-	snapshotTS       uint64 // The consistent snapshot timestamp for the executor to read data.
+	snapshotTS       uint64 // The ts for snapshot-read, if a select statement without for update will use this ts
+	minForUpdateTS   uint64 // The min ts should be used by insert/update/delete/select-for-update statement
```
[the remark this answers is not in the document]
Comment (lcwangchao) [reply executor/builder.go:90]: > Btw what does `min` mean here?

For example, when buildUpdate, `b. minForUpdateTS = b.ctx.GetSessionVars().TxnCtx.GetForUpdateTS()` is set. But when the inner plan is `PointGet` , the builder will skip fetch the latest ts so the it will return 0 ... It is the old logical and I don't want to change it in this PR. So the actual meaning of this variable is "updateTS should not smaller than it" instead of "updateTS should be it"

File: executor/builder.go (hunk 2 above)
Comment (lcwangchao) [reply executor/builder.go:1507]: Yes. I'll refactor it in the later refactoring. But I think I can change the method `getSnapshotReadTS` to `getIsolateTS` and returns the no-update ts according to isolation level.

File: executor/builder.go [hunk 5]
```diff
@@ -1476,8 +1489,38 @@ func (b *executorBuilder) buildTableDual(v *plannercore.PhysicalTableDual) Execu
...
+// getSnapshotReadTS returns the ts used by insert/update/delete and select for update
+func (b *executorBuilder) getForUpdateTS() (uint64, error) {
+	ts, err := b.getIsolationReadTS()
+	if err != nil {
+		return 0, err
+	}
+
+	if b.minForUpdateTS > ts {
+		return b.minForUpdateTS, nil
+	}
```
Comment (MyonKeminta) [inline executor/builder.go:1515]: When will this happen?

**Review by MyonKeminta — APPROVED** [review]
