### PR TITLE
test: fix t.Parallel() is called in the range method but is not reinitialised

### LINKED ISSUE #27779: maybe common mistakes with table driven tests and t.Parallel()
## Bug Report

I am tring to figure out a strang problem in pr #27557, in which 2 tests fail if i add `t.Parallel()` and work well if i removed it. Then when i tried to find more info about `t.Parallel()`, i found that there maybe an common mistake in our test.

###  problem

```go
func TestWithParallel(t *testing.T) {
	tests := []struct {
		name  string
		value int
	}{
		{name: "test 1", value: 4},
		{name: "test 2", value: 4},
		{name: "test 3", value: 4},
		{name: "test 4", value: 4},
	}
	for i, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
                         // uncomment below line will make 4 tests pass
			//t.Parallel()
			fmt.Printf("%+v == %+v \n", i+1, tc.value)
			require.Equal(t, i+1, tc.value)
		})
	}
}
```
for above table driven tests, `test1`, `test2`, `test3` should fail, `test 4` should pass, it works as expect.
but if we add `t.Parallel()` by uncomment the line, 4 test will pass, and the output is:

```shell
4 == 4 
4 == 4 
4 == 4 
4 == 4 
```

### reason

the reason is explained well in [Go common mistakes guide](https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables), 2 reason:

1. In Go, the loop iterator variable is a single variable that takes different values in each loop iteration
2. there is a very good chance that when you run this code you will see the last element printed for every iteration instead of each value in sequence, because the goroutines will probably not begin executing until after the loop

### how to resolve

- adding val as a parameter to the closure
```go
for _, val := range values {
	go func(val interface{}) {
		fmt.Println(val)
	}(val)
}
```

- Copy  iterator variable into a new variable
```diff
 for i := 0; i < 3; i++ {
+	i := i // Copy i into a new variable.
 	out = append(out, &i)
 }

```

also, we may add linter to avoid such pitfall https://github.com/kunwardeep/paralleltest

### todo
i seached repo, there already some wrong occurance there,  such as  `request_builder_test.go` , `table/column_test.go`,
i am not sure how many contributors are awared of this, the occurances ge merged means even some experienced reviewer may not aware of it. 

so i submit a issue here, we need fix them and **pay attention** to this scenario, and may also add notice to https://pingcap.github.io/tidb-dev-guide/get-started/write-and-run-unit-tests.html

### PR DESCRIPTION
**Pull request by feitian124**
### What problem does this PR solve?

Issue Number: ref #27779 
fixed the exists of errors mentioned in above issue.

### todo

in my branch which is 3 days ago the  occurance is 11, in master branch tody the the  occurance is 14.
maybe we'd better add the linter to ci, or add to dev guide to let more people know it?

### Release note

```release-note
None
```

### CODE REVIEW

File: distsql/request_builder_test.go [hunk 1]
```diff
@@ -529,6 +529,7 @@ func TestRequestBuilder7(t *testing.T) {
 		{kv.ReplicaReadFollower, "Follower"},
 		{kv.ReplicaReadMixed, "Mixed"},
 	} {
+		replicaRead := replicaRead
```
Comment (mjonss) [inline distsql/request_builder_test.go:532]: Please create a variable with a different name, to make it clear it is a copy, instead of overloading the variable name. And/or add a comment on why this is needed, so it is less confusing for developers unknown of the issue.

**Review by mjonss — COMMENTED** [review]
Please do not overload the variable name with its copy, create a new variable to make it less confusing.

File: distsql/request_builder_test.go (hunk 1 above)
Comment (feitian124) [reply distsql/request_builder_test.go:532]: this paradigm is so common that i believe use the same name is the best/acceptable practise
see 
- https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks
- https://github.com/golang/go/wiki/CommonMistakes#introduction

maybe add comment to make it more clear

Comment (feitian124) [reply distsql/request_builder_test.go:533]: added

**Review by xhebox — APPROVED** [review]
Sound like there are similar problems for other migration PRs.

**Comment by feitian124** [comment]
> Sound like there are similar problems for other migration PRs.

i used a linter to check whole repo, all 14 occurances are fixed in this pr.
i did a scan again, no new one find these two days.

**Comment by feitian124** [comment]
@mjonss @bb7133 @morgo 
could you help review? thanks.

**Review by tisonkun — APPROVED** [review]
LGTM. Could you try to investigate how to add a linter to spot this kind of risk?

**Comment by feitian124** [comment]
> LGTM. Could you try to investigate how to add a linter to spot this kind of risk?

sure, i will try, that's why i kept the issue open.
