### PR TITLE
ddl: fix duplicate entry message report by add index

### LINKED ISSUE #13093: should show correct duplicate entry while add index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
tidb:
```
mysql> CREATE TABLE binlog_pk_add_duplicate_uk(id INT PRIMARY KEY, a1 INT);
Query OK, 0 rows affected (0.18 sec)

mysql> INSERT INTO binlog_pk_add_duplicate_uk(id, a1) VALUES(1,1),(2,1);
Query OK, 2 rows affected (0.03 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE binlog_pk_add_duplicate_uk ADD UNIQUE INDEX aidx(a1);
ERROR 1062 (23000): Duplicate entry '' for key 'aidx'
mysql>
```

2. What did you expect to see?
mysql:
```
mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> CREATE TABLE binlog_pk_add_duplicate_uk(id INT PRIMARY KEY, a1 INT);
Query OK, 0 rows affected (0.08 sec)

mysql> INSERT INTO binlog_pk_add_duplicate_uk(id, a1) VALUES(1,1),(2,1);
Query OK, 2 rows affected (0.03 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE binlog_pk_add_duplicate_uk ADD UNIQUE INDEX aidx(a1);
ERROR 1062 (23000): Duplicate entry '1' for key 'aidx'
```

3. What did you see instead?
Duplicate entry '' for key 'aidx'  

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v4.0.0-alpha-689-g11cd41d2b
Git Commit Hash: 11cd41d2b59f17055bc25dfb281262f0665f4cdf
Git Branch: master
UTC Build Time: 2019-11-03 04:53:59
GoVersion: go version go1.13 darwin/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by bobotu**
### What problem does this PR solve?

Issue Number: close #13093

### What is changed and how it works?
Generating the error message based on column values. But do this need to fix another bug, the encode/decode of index key-value is incorrect in `batchCheckUniqueKey`.

### Check List 

Tests 

- Unit test

### Release note 

- Display column values in duplicate entry messages reported by add index operation.

### CODE REVIEW

File: ddl/index.go [hunk 1]
```diff
@@ -1046,21 +1116,20 @@ func (w *addIndexWorker) batchCheckUniqueKey(txn kv.Transaction, idxRecords []*i
 	for i, key := range w.batchCheckKeys {
 		if val, found := batchVals[string(key)]; found {
 			if w.distinctCheckFlags[i] {
-				handle, err1 := tablecodec.DecodeHandleInUniqueIndexValue(val, w.table.Meta().IsCommonHandle)
-				if err1 != nil {
-					return errors.Trace(err1)
-				}
-
-				if handle != idxRecords[i].handle {
```
Comment (bobotu) [inline ddl/index.go:1054]: This line is buggy because it is trying to use reference equality to check if the index key is duplicated. The `handle` returned by `DecodeHandleInUniqueIndexValue` would never equal to `idxRecords[i].handle`, which means the index will always be treated as a duplicate.

I fixed this potential critical bug as part of the rewrite of the decoding of the index key-value.

Comment (bobotu) [reply ddl/index.go:1054]: The good news is we haven't done the same thing in another place. I have checked the codebase at `master` using this naive analyzer.

```go
func run(pass *analysis.Pass) (interface{}, error) {
	inspect := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)
	nodeFilter := []ast.Node{
		(*ast.BinaryExpr)(nil),
	}

	const typeName = "github.com/pingcap/tidb/kv.Handle"

	inspect.Preorder(nodeFilter, func(node ast.Node) {
		expr := node.(*ast.BinaryExpr)

		if expr.Op != token.EQL && expr.Op != token.NEQ {
			return
		}

		if pass.TypesInfo.TypeOf(expr.X).String() != typeName || pass.TypesInfo.TypeOf(expr.Y).String() != typeName {
			return
		}

		pass.Reportf(expr.Pos(), "use %s on two handle type", expr.Op.String())
	})

	return nil, nil
}
```

The output contains only one line and it says
```
tidb/ddl/index.go:1054:8: use != on two handle type
```

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: ddl/index.go (hunk 1 above)
Comment (tangenta) [reply ddl/index.go:1054]: Should we add this static check to `make check`?
