### PR TITLE
*: fix union result when mix signed/unsigned columns

### LINKED ISSUE #7075: union result is not differ from mysql
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
create table t(a int);
create table s(a int unsigned);

insert into t value(-1);
insert into s value(1);
```

2. What did you expect to see?
``` sql
select * from t union all select * from s;
+------+
| a    |
+------+
|   -1 |
|    1 |
+------+

select * from s union all select * from t;
+------+
| a    |
+------+
|    0 |
|    1 |
+------+
```

3. What did you see instead?
``` sql
select * from t union all select * from s;
+------+
| a    |
+------+
|   -1 |
|    1 |
+------+

select * from s union all select * from t;
+------+
| a    |
+------+
|   -1 |
|    1 |
+------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v2.1.0-beta-61-g44e34bd-dirty
Git Commit Hash: 44e34bd30468fb35df4526d37c8511b259c6794d
Git Branch: castintasdecimal
UTC Build Time: 2018-07-17 09:39:23
GoVersion: go version go1.10.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
```

### PR DESCRIPTION
**Pull request by lysu**
## What have you changed? (mandatory)

fix #7075 

- make logical_plan_builder infer `unsigned_flag` right
- mark resultType need be zero if it's an unsigned num but < 0
- union builder also consider unsigned_flag to determine whether add cast projection
- make cast expression cast zero if type marked in step 2 for int/bigint/double/float/decimal

## What is the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

- unit tests
- integration tests

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Does this PR need to be added to the release notes? (mandatory)

```
fix union result when mix signed/unsigned columns
```

## Refer to a related PR or issue link (optional)

#7075 

## Add a few positive/negative examples (optional)

see #7075  and unit test

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/7112)

### CODE REVIEW

File: types/field_type.go [hunk 1]
```diff
@@ -39,7 +39,8 @@ type FieldType struct {
 	Charset string
 	Collate string
 	// Elems is the element list for enum and set type.
-	Elems []string
+	Elems           []string
+	BelowZeroBeZero bool
```
Comment (lysu) [inline types/field_type.go]: we need this... because we can not cast < 0 to zero directly in chunk_executor...- -

because `select cast(-1 as unsigned)` need be MAX_UINT64..
but for union or insert need be 0

File: executor/executor_test.go [hunk 2]
```diff
@@ -2916,3 +2916,21 @@ func (s *testSuite) TestIndexJoinTableDualPanic(c *C) {
...
+	tk.MustExec("create table t1 (id int, i int, b bigint, d double, dd decimal)")
+	tk.MustExec("create table t2 (id int, i int unsigned, b bigint unsigned, d double unsigned, dd decimal unsigned)")
+	tk.MustExec("insert into t1 values(1, -1, -1, -1.1, -1)")
+	tk.MustExec("insert into t2 values(2, 1, 1, 1.1, 1)")
+	tk.MustQuery("select * from t1 union select * from t2 order by id").
+		Check(testkit.Rows("1 -1 -1 -1.1 -1", "2 1 1 1.1 1"))
+	tk.MustQuery("select id, i, b, d, dd from t2 union select id, i, b, d, dd from t1 order by id").
+		Check(testkit.Rows("1 0 0 0 -1", "2 1 1 1.1 1"))
+	tk.MustQuery("select id, i from t2 union select id, cast(i as unsigned int) from t1 order by id").
+		Check(testkit.Rows("1 18446744073709551615", "2 1"))
```
Comment (jackysp) [inline executor/executor_test.go]: Is it the same as MySQL's?

File: types/field_type.go [hunk 3]
```diff
@@ -39,7 +39,8 @@ type FieldType struct {
 	Charset string
 	Collate string
 	// Elems is the element list for enum and set type.
-	Elems []string
+	Elems                  []string
+	NegativeUnsignedBeZero bool
```
[the remark this answers is not in the document]
Comment (lysu) [reply types/field_type.go]: yes~ because in union context cast(negative unsigned be zero) is differ to cast in normal(negative unsigned be int.Max)...so we need a flag.

we can add it in field_type or cast expression/executor, and it seems previous way's modification is less.

yes, it is not very comfortable for mee too, or have any other good way ~ ^ ^ ?

File: executor/executor_test.go (hunk 2 above)
Comment (lysu) [reply executor/executor_test.go]: yes~ mysql, cast will got int.Max

File: types/field_type.go [hunk 4]
```diff
@@ -40,6 +40,9 @@ type FieldType struct {
 	Collate string
 	// Elems is the element list for enum and set type.
 	Elems []string
+	// NegativeUnsignedBeZero indicates that unsigned type with negative number will be cast 0 instead of Big number.
+	// it's only used in union implicitly cast.
+	NegativeUnsignedBeZero bool
```
Comment (coocood) [inline types/field_type.go]: Please take more time to find a way to avoid adding this field.

Comment (zz-jason) [reply types/field_type.go]: I think we should move this field to the cast function.

**Comment by lysu** [comment]
@coocood @zz-jason @XuHuaiyu  PTAL thx~

File: plan/logical_plan_builder.go [hunk 5]
```diff
@@ -647,7 +655,7 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
 			dstType := unionSchema.Columns[i].RetType
 			srcType := srcCol.RetType
 			if !srcType.Equal(dstType) {
-				exprs[i] = expression.BuildCastFunction(b.ctx, srcCol, dstType)
+				exprs[i] = expression.BuildCastFunction4Insert(b.ctx, srcCol, dstType)
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: Seems like `BuildCastFunction4Insert` is only used for `Union`, maybe name the function to `BuildCastFunction4Union` is better?

File: plan/logical_plan_builder.go [hunk 6]
```diff
@@ -612,6 +612,14 @@ func (b *planBuilder) buildDistinct(child LogicalPlan, length int) LogicalPlan {
 // joinFieldType finds the type which can carry the given types.
 func joinFieldType(a, b *types.FieldType) *types.FieldType {
 	resultTp := types.NewFieldType(types.MergeFieldType(a.Tp, b.Tp))
+	// This logic need be combined with buildProjection4Union.
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: I think we'd better not embed this function to `buildProjection4Union`. this function is focused on deciding the data type for each column of the `union`.

File: plan/logical_plan_builder.go [hunk 7]
```diff
@@ -612,6 +612,14 @@ func (b *planBuilder) buildDistinct(child LogicalPlan, length int) LogicalPlan {
...
+	if a.Tp == mysql.TypeNewDecimal {
+		// For Decimal result be unsigned when all union children be unsigned.
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: how about: "the decimal type could be unsigned only when all the decimals to be united are unsigned" @CaitinChen We need your help to refine this comment 😂

File: expression/builtin_cast.go [hunk 8]
```diff
@@ -426,25 +426,34 @@ func (c *castAsJSONFunctionClass) getFunction(ctx sessionctx.Context, args []Exp
 
 type builtinCastIntAsIntSig struct {
 	baseBuiltinFunc
```
Comment (zz-jason) [inline expression/builtin_cast.go]: how about defining another struct to wrap `baseBuiltinFunc` and `insertContext`, and use this struct for every `builtinCastXAsYSig`:
```go
type baseBuiltinCastFunc struct {
	baseBuiltinFunc
	inUnionAll bool
}
```

If so, we only need to change the `base` or `bf` when constructing `builtinCastXAsYSig`s, and the code can be cleaner.

File: expression/builtin_cast.go [hunk 9]
```diff
@@ -456,20 +465,26 @@ func (b *builtinCastIntAsRealSig) evalReal(row types.Row) (res float64, isNull b
 	if !mysql.HasUnsignedFlag(b.args[0].GetType().Flag) {
 		res = float64(val)
 	} else {
```
Comment (zz-jason) [inline expression/builtin_cast.go]: how about:
```go
if !mysql.HasUnsignedFlag(b.args[0].GetType().Flag) {
	...
} else if b.insertContext && val < 0 {
	...
} else {
	...
}
```

File: expression/builtin_cast.go [hunk 10]
```diff
@@ -873,9 +914,13 @@ func (b *builtinCastDecimalAsIntSig) evalInt(row types.Row) (res int64, isNull b
 	}
 
 	if mysql.HasUnsignedFlag(b.tp.Flag) {
```
Comment (zz-jason) [inline expression/builtin_cast.go]: how about:
```go
if !mysql.HasUnsignedFlag(b.tp.Flag) {
	...
} else if b.insertContext && val < 0 {
	...
} else {
	...
}
```

File: plan/logical_plan_builder.go (hunk 5 above)
Comment (lysu) [reply plan/logical_plan_builder.go]: Emma, but maybe it will use for insert, insert cast logic is the same as this one, but now insert values is datum based cast, or we change to insert in future?

Comment (zz-jason) [reply plan/logical_plan_builder.go]: We can change it in the future. I believe it will take us a long time to reach that future 😂

File: expression/builtin_cast.go [hunk 11]
```diff
@@ -1593,6 +1659,24 @@ func (b *builtinCastJSONAsDurationSig) evalDuration(row types.Row) (res types.Du
 	return
 }
 
+type castContext int
```
[the remark this answers is not in the document]
Comment (lysu) [reply expression/builtin_cast.go]: it used in BuildCastFunction4Insert, build a special tmp ctx to void modify `BuildCastFunction`, `castXXFunctionClass` or `getFunction`

File: expression/builtin_cast.go [hunk 12]
```diff
@@ -1051,32 +1078,33 @@ func (b *builtinCastStringAsIntSig) evalInt(row types.Row) (res int64, isNull bo
...
 		res = int64(ures)
 
 		if err == nil && !mysql.HasUnsignedFlag(b.tp.Flag) && ures > uint64(math.MaxInt64) {
 			sc.AppendWarning(types.ErrCastAsSignedOverflow)
 		}
+	} else if b.inUnionAll && mysql.HasUnsignedFlag(b.tp.Flag) && isNegative {
+		res = 0
+	} else {
+		res, err = types.StrToInt(sc, val)
+		if err == nil {
```
Comment (zz-jason) [inline expression/builtin_cast.go]: `if err != nil`?

Comment (lysu) [reply expression/builtin_cast.go]: maybe this old logic is by design https://github.com/pingcap/tidb/pull/3894

File: plan/logical_plan_builder.go (hunk 7 above)
Comment (lysu) [reply plan/logical_plan_builder.go]: @CaitinChen  need help~~

File: expression/builtin_cast.go (hunk 12 above)
Comment (lysu) [reply expression/builtin_cast.go]: .....it seems a old bug.
`select cast(-1 as signed)` should not return a warning but master branch does.
I think it should be f2a38a96f46809e13dd6e5f0de4fc124f3e1300d ?

File: plan/logical_plan_builder.go (hunk 7 above)
Comment (CaitinChen) [reply plan/logical_plan_builder.go]: The decimal type is unsigned only when all the decimals to be united are unsigned.

Comment (CaitinChen) [reply plan/logical_plan_builder.go]: @zz-jason @lysu I think Jason's may be right, but I don't know why you use "could be".

File: plan/logical_plan_builder.go (hunk 6 above)
Comment (CaitinChen) [reply plan/logical_plan_builder.go]: This logic is intelligible when it is associated with the buildProjection4Union logic.

File: plan/logical_plan_builder.go [hunk 13]
```diff
@@ -609,9 +609,17 @@ func (b *planBuilder) buildDistinct(child LogicalPlan, length int) LogicalPlan {
...
-func joinFieldType(a, b *types.FieldType) *types.FieldType {
+// unionJoinFieldType finds the type which can carry the given types in Union.
+func unionJoinFieldType(a, b *types.FieldType) *types.FieldType {
 	resultTp := types.NewFieldType(types.MergeFieldType(a.Tp, b.Tp))
+	// This logic need be understood with buildProjection4Union logic.
+	if a.Tp == mysql.TypeNewDecimal {
+		// the decimal type could be unsigned only when all the decimals to be united are unsigned
+		resultTp.Flag &= b.Flag & mysql.UnsignedFlag
+	} else {
+		// Other types result will be unsigned only if first child be unsigned.
```
Comment (CaitinChen) [inline plan/logical_plan_builder.go]: Non-decimal results will be unsigned when the first SQL statement result in the union is unsigned.

File: plan/logical_plan_builder.go [hunk 14]
```diff
@@ -609,9 +609,17 @@ func (b *planBuilder) buildDistinct(child LogicalPlan, length int) LogicalPlan {
 	return plan4Agg
 }
 
-// joinFieldType finds the type which can carry the given types.
-func joinFieldType(a, b *types.FieldType) *types.FieldType {
+// unionJoinFieldType finds the type which can carry the given types in Union.
+func unionJoinFieldType(a, b *types.FieldType) *types.FieldType {
 	resultTp := types.NewFieldType(types.MergeFieldType(a.Tp, b.Tp))
+	// This logic need be understood with buildProjection4Union logic.
```
Comment (CaitinChen) [inline plan/logical_plan_builder.go]: This logic will be intelligible when it is associated with the buildProjection4Union logic.

File: plan/logical_plan_builder.go [hunk 15]
```diff
@@ -609,9 +609,17 @@ func (b *planBuilder) buildDistinct(child LogicalPlan, length int) LogicalPlan {
...
+	if a.Tp == mysql.TypeNewDecimal {
+		// the decimal type could be unsigned only when all the decimals to be united are unsigned
```
Comment (CaitinChen) [inline plan/logical_plan_builder.go]: The decimal type will be unsigned only when all the decimals to be united are unsigned.

**Comment by lysu** [comment]
@coocood @XuHuaiyu PTAL thx~

**Comment by lysu** [comment]
@coocood @XuHuaiyu PTAL thx~

File: expression/builtin.go [hunk 16]
```diff
@@ -235,6 +235,24 @@ func (b *baseBuiltinFunc) Clone() builtinFunc {
 	panic("you should not call this method.")
 }
 
+// baseBuiltinCastFunc will be contained in every struct that implement cast builtinFunc
+type baseBuiltinCastFunc struct {
+	baseBuiltinFunc
+	inUnionAll bool
```
Comment (XuHuaiyu) [inline expression/builtin.go]: add a comment for this.

File: expression/builtin_cast.go [hunk 17]
```diff
@@ -1593,6 +1626,26 @@ func (b *builtinCastJSONAsDurationSig) evalDuration(row types.Row) (res types.Du
 	return
 }
 
+// inCastContext is session key type that indicates whether executing in special cast context.
```
Comment (XuHuaiyu) [inline expression/builtin_cast.go]: Can we make a more detail explaination for `special`?

File: expression/builtin.go (hunk 16 above)
Comment (lysu) [reply expression/builtin.go]: done

File: expression/builtin.go [hunk 18]
```diff
@@ -235,6 +235,26 @@ func (b *baseBuiltinFunc) Clone() builtinFunc {
...
+	// inUnion indicates whether cast is in union context.
+	inUnion bool
+}
+
+func (b *baseBuiltinCastFunc) cloneFrom(from *baseBuiltinCastFunc) {
+	b.baseBuiltinFunc.cloneFrom(&from.baseBuiltinFunc)
+	b.inUnion = from.inUnion
+}
+
+func newBaseBuiltinCastFunc(builtinFunc baseBuiltinFunc, inUnionAll bool) baseBuiltinCastFunc {
```
Comment (XuHuaiyu) [inline expression/builtin.go]: s/ inUnionAll/ inUnion

File: expression/builtin.go [hunk 19]
```diff
@@ -235,6 +235,26 @@ func (b *baseBuiltinFunc) Clone() builtinFunc {
...
+	return baseBuiltinCastFunc{
+		baseBuiltinFunc: builtinFunc,
+		inUnion:         inUnionAll,
```
Comment (XuHuaiyu) [inline expression/builtin.go]: ditto

File: expression/builtin.go [hunk 20]
```diff
@@ -235,6 +235,26 @@ func (b *baseBuiltinFunc) Clone() builtinFunc {
 	panic("you should not call this method.")
 }
 
+// baseBuiltinCastFunc will be contained in every struct that implement cast builtinFunc.
+type baseBuiltinCastFunc struct {
+	baseBuiltinFunc
+
+	// inUnion indicates whether cast is in union context.
+	inUnion bool
```
Comment (XuHuaiyu) [inline expression/builtin.go]: This is never used ?

File: executor/executor_test.go (hunk 2 above)
Comment (XuHuaiyu) [reply executor/executor_test.go]: what about `unsigned double union int`? we need a case to cover union different types.

**Comment by lysu** [comment]
PTAL @coocood @XuHuaiyu
