### PR TITLE
meta/autoid:  reduce get autoID's backoff

### LINKED ISSUE #61987: latency spike(30 ms -->500ms) in auto increment writes during tidb auto id reboot
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create table
 `CREATE TABLE `sbtest1` (
  `id` int NOT NULL AUTO_INCREMENT,
  `k` int NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=320439141 /*T![auto_id_cache] AUTO_ID_CACHE=1 */ `
2. run sysbench  
`sysbench oltp_insert --non_index_updates=1 --skip_trx=true --tables=1 --table_size=16384 --threads=64 --mysql-host=${HOST} --mysql-user=root --mysql-db=test --mysql-port=4000 --report-interval=10 --time=6000 run`

### 2. What did you expect to see? (Required)
Minimal impact on write latency
### 3. What did you see instead (Required)
See latency spike from 31 to 500 ms

Image

### 4. What is your TiDB version? (Required)
8.5

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What problem does this PR solve?

Issue Number: close #61987

Problem Summary:

### What changed and how does it work?
reducing backoff from 250 ms to 5 ms and adding retry if leader is not assigned in etcd.
### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```
test results
Screenshot 2025-06-24 at 11 09 30 PM

### CODE REVIEW

File: pkg/meta/autoid/autoid_service.go [hunk 1]
```diff
@@ -97,10 +97,20 @@ func (d *ClientDiscover) GetClient(ctx context.Context, keyspaceID uint32) (auto
...
 		return d.mu.AutoIDAllocClient, atomic.LoadUint64(&d.version), nil
 	}
-
-	resp, err := d.etcdCli.Get(ctx, GetAutoIDServiceLeaderEtcdPath(keyspaceID), clientv3.WithFirstCreate()...)
-	if err != nil {
-		return nil, 0, errors.Trace(err)
+	// write a for loop to retry in case of etcd connection error.
+	var resp *clientv3.GetResponse
+	var err error
+	for range 1 {
```
Comment (tiancaiamao) [inline pkg/meta/autoid/autoid_service.go]: unrelated change?  range 1 is once

File: pkg/meta/autoid/autoid_service.go [hunk 2]
```diff
@@ -159,7 +170,7 @@ retry:
 		IsUnsigned: sp.isUnsigned,
 		KeyspaceID: sp.keyspaceID,
 	})
-	metrics.AutoIDHistogram.WithLabelValues(metrics.TableAutoIDAlloc, metrics.RetLabel(err)).Observe(time.Since(start).Seconds())
+	metrics.AutoIDHistogram.WithLabelValues(metrics.TableAutoIDAlloc, metrics.RetLabel(err)).Observe(time.Since(clientStart).Seconds())
```
Comment (tiancaiamao) [inline pkg/meta/autoid/autoid_service.go:176]: Yes, this is a correct change

File: pkg/meta/autoid/autoid_service.go (hunk 1 above)
Comment (mittalrishabh) [reply pkg/meta/autoid/autoid_service.go]: aah sorry. I corrected it

**Review by tiancaiamao — APPROVED** [review]

**Comment by mittalrishabh** [comment]
can i get another LGTM and label

**Comment by zhangjinpeng87** [comment]
bugbot run

**Comment by bb7133** [comment]
Could you please add some test cases?

File: pkg/meta/autoid/autoid_service.go [hunk 3]
```diff
@@ -97,10 +97,21 @@ func (d *ClientDiscover) GetClient(ctx context.Context, keyspaceID uint32) (auto
...
 		return d.mu.AutoIDAllocClient, atomic.LoadUint64(&d.version), nil
 	}
-
-	resp, err := d.etcdCli.Get(ctx, GetAutoIDServiceLeaderEtcdPath(keyspaceID), clientv3.WithFirstCreate()...)
-	if err != nil {
-		return nil, 0, errors.Trace(err)
+	// write a for loop to retry in case of etcd connection error.
+	var resp *clientv3.GetResponse
+	var err error
+	for range []int{0, 1} {
```
Comment (lance6716) [inline pkg/meta/autoid/autoid_service.go]: seems you can use `for range 2 {`. BTW, I double only retry once is not enough 🤔

File: pkg/meta/autoid/autoid_service.go [hunk 4]
```diff
@@ -97,10 +97,21 @@ func (d *ClientDiscover) GetClient(ctx context.Context, keyspaceID uint32) (auto
...
+		resp, err = d.etcdCli.Get(ctx, GetAutoIDServiceLeaderEtcdPath(keyspaceID), clientv3.WithFirstCreate()...)
+		if err != nil {
+			return nil, 0, errors.Trace(err)
+		}
+		if len(resp.Kvs) == 0 {
+			// If the key is not found, it means the autoid service leader is not elected yet.
+			// We can retry to get the leader.
+			time.Sleep(10 * time.Millisecond)
```
Comment (lance6716) [inline pkg/meta/autoid/autoid_service.go]: please use `select { <- ctx.Done(): ... <- time.After(...): ... } ` to find context canceled earlier.

File: pkg/meta/autoid/autoid_service.go [hunk 5]
```diff
@@ -97,10 +97,21 @@ func (d *ClientDiscover) GetClient(ctx context.Context, keyspaceID uint32) (auto
...
+			continue
+		}
+		break
```
Comment (lance6716) [inline pkg/meta/autoid/autoid_service.go]: it's more shorter to write

```
for {
  if satisfied { break }
  // no explicit continue
}
```

File: pkg/meta/autoid/autoid_service.go (hunk 3 above)
Comment (mittalrishabh) [reply pkg/meta/autoid/autoid_service.go]: i generally see 10 milliseconds is good enough time to relect the leader during graceful shutdown. I agree it won't be enough for ungraceful shutdown which can take upto 8 seconds. What is the max time you want to wait for ?

**Comment by mittalrishabh** [comment]
@lance6716 can you review it now ? And any existing test case which is mocking the autoID leader

File: pkg/meta/autoid/autoid_service.go [hunk 6]
```diff
@@ -97,14 +97,27 @@ func (d *ClientDiscover) GetClient(ctx context.Context, keyspaceID uint32) (auto
...
 	}
 	if len(resp.Kvs) == 0 {
-		return nil, 0, errors.New("autoid service leader not found")
+		// If the key is not found, it means the autoid service leader is not elected yet.
+		// We can retry to get the leader.
+		select {
+		case <-ctx.Done():
+			return nil, 0, errors.Trace(ctx.Err())
+		default:
+			bo.Backoff()
```
Comment (lance6716) [inline pkg/meta/autoid/autoid_service.go]: There's a `time.Sleep` inside `bo.Backoff()`. If this goroutine sleeps, it will not see `<-ctx.Done()` and latency also increases. So IMO the idea way to handle it is

```
select {
case <-ctx.Done():
  ...
case <-time.After(...): // should not use default branch, the goroutine should be blocked at select statement.
}
```

However because the maximum backoff time has been changed to 100ms it's also acceptable even if code sleeps when context is done.

And for current code, we can refine it to

```
if err := ctx.Err(); err != nil { return ... }
bo.Backoff()
goto retry
```

Because there's only one case in select statement, we can directly check `ctx.Err()`. The function comment of it says not nil error is the same as `<-ctx.Done()`

File: pkg/meta/autoid/autoid_service.go [hunk 7]
```diff
@@ -179,8 +200,8 @@ retry:
 	return resp.Min, resp.Max, err
 }
 
-const backoffMin = 200 * time.Millisecond
-const backoffMax = 5 * time.Second
+const backoffMin = 5 * time.Millisecond
+const backoffMax = 100 * time.Millisecond
```
Comment (lance6716) [inline pkg/meta/autoid/autoid_service.go:200]: @tiancaiamao please check again about this change

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
@tiancaiamao please help triage the affected versions of linked issue

**Comment by mittalrishabh** [comment]
i could not merge.
@tiancaiamao can you help in making this check passed [check-issue-triage-complete](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/cherrypick-a-pr.html#pass-triage-complete-check)

**Review by tiancaiamao — APPROVED** [review]

**Comment by mittalrishabh** [comment]
@lance6716 it is still waiting for LGTM from some one in approver list

**Review by GMHDBJD — APPROVED** [review]
