### PR TITLE
ddl/ingest: fix checkpoint resume when owner changes several times

### LINKED ISSUE #44619: data index inconsistent after DDL owner change several times (at least twice)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluter with 3 tidb instance
2. create a partition table and insert some data
3. add index for the table use ingest mode.
4. during add index, upgrade the cluster or resign the ddl owner several times, at least twice
5. after cluster upgraded, admin check index

### 2. What did you expect to see? (Required)
admin check index pass
### 3. What did you see instead (Required)
check index failed
```sql
error="[admin:8003]table count 10000800 != index(idx1) count 4666669"
```
图片

### 4. What is your TiDB version? (Required)
v7.1.0

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #44619

Problem Summary:

When the owner restarts to check if owner instance address has changed, the partitition ID of the checkpoint record will not be written into the checkpoint manager.

This results in the partition ID not being restored to the global checkpoint when restoring adding index job, and finally missing part of the partition's index records.

### What is changed and how it works?

Regardless of whether the owner instance address has changed, always record the partition ID of the checkpoint to the checkpoint manager

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Benjamin2037** [comment]
Could you add some brief description about the root cause?

File: ddl/index.go [hunk 1]
```diff
@@ -1850,6 +1850,10 @@ func (w *worker) addTableIndex(t table.Table, reorgInfo *reorgInfo) error {
 			if err != nil {
 				break
 			}
+			w.ddlCtx.mu.RLock()
```
Comment (Benjamin2037) [inline ddl/index.go:1853]: why here do we need a. read lock?  can we remove lock?

Comment (tangenta) [reply ddl/index.go:1853]: This is how we use the hook. There is only one hook instance globally.

File: ddl/index.go [hunk 2]
```diff
@@ -1850,6 +1850,10 @@ func (w *worker) addTableIndex(t table.Table, reorgInfo *reorgInfo) error {
...
+			w.ddlCtx.mu.hook.OnUpdateReorgInfo(reorgInfo.Job, reorgInfo.PhysicalTableID)
+			w.ddlCtx.mu.RUnlock()
```
Comment (Benjamin2037) [inline ddl/index.go:1855]:
```suggestion
			defer w.ddlCtx.mu.RUnlock()
```
to ensure release lock.

File: ddl/util/callback/callback.go [hunk 3]
```diff
@@ -58,6 +58,8 @@ type TestDDLCallback struct {
 	OnGetJobBeforeExported  func(string)
 	OnGetJobAfterExported   func(string, *model.Job)
 	OnJobSchemaStateChanged func(int64)
+
```
Comment (Benjamin2037) [inline ddl/util/callback/callback.go:61]:
```suggestion
```

**Review by wjhuang2016 — APPROVED** [review]

File: ddl/index.go (hunk 2 above)
Comment (tangenta) [reply ddl/index.go:1855]: No, inside the loop we cannot use "defer". Otherwise it will block `RLock` forever.

File: ddl/util/callback/callback.go (hunk 3 above)
Comment (tangenta) [reply ddl/util/callback/callback.go:61]: The line break is used to distinguish plain DDL hooks and reorg hooks.

**Review by ywqzzy — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM
