### PR TITLE
*: fix log for statistics

### LINKED ISSUE #49216: wrong log output for statistics
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #49216

Problem Summary:

### What changed and how does it work?

```statstics.logutil``` is initialized after the global one. so it prints the log at the stdout.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by zimulala — COMMENTED** [review]
Could you describe the problem? I don't see any explanation in ref the issue

**Review by zimulala — APPROVED** [review]
Rest LGTM

File: pkg/statistics/handle/logutil/logutil.go [hunk 1]
```diff
@@ -1,25 +0,0 @@
...
-package logutil
-
-import (
-	"github.com/pingcap/tidb/pkg/util/logutil"
-	"go.uber.org/zap"
-)
-
-var (
-	// StatsLogger with category "stats" is used to log statistic related messages.
-	StatsLogger = logutil.BgLogger().With(zap.String("category", "stats"))
```
Comment (hi-rustin) [inline pkg/statistics/handle/logutil/logutil.go:24]: How about we make it a function instead of a variable?

**Review by hi-rustin — COMMENTED** [review]
Thanks!

File: pkg/statistics/handle/logutil/logutil.go (hunk 1 above)
Comment (hi-rustin) [reply pkg/statistics/handle/logutil/logutil.go:24]: It would always get the latest logger and save many duplications.

Comment (hi-rustin) [reply pkg/statistics/handle/logutil/logutil.go:24]: Updated.
