### PR TITLE
ddl: forbid alter table partition with global index needed

### LINKED ISSUE #51634: alter table t partitioning with unique index which not include partition columns should be forbiden
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists t;
create table t(a int, b int, unique idx_b(b));
alter table t partition by hash(a) partitions 3;
insert into t values (1,1), (2,1), (3, 1);
```

### 2. What did you expect to see? (Required)

return error.

### 3. What did you see instead (Required)

```
mysql> drop table t;
Query OK, 0 rows affected (0.28 sec)

mysql> drop table if exists t;
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> create table t(a int, b int, unique idx_b(b));
alter table t partition by hash(a) partitions 3;Query OK, 0 rows affected (0.12 sec)

mysql> alter table t partition by hash(a) partitions 3;
Query OK, 0 rows affected, 1 warning (2.02 sec)

mysql>  insert into t values (1,1), (2,1), (3, 1);
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select b from t;
+------+
| b    |
+------+
|    1 |
|    1 |
|    1 |
+------+
3 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #51634

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
Very good catch!

**Review by Benjamin2037 — APPROVED** [review]
LGTM

File: pkg/ddl/ddl_api.go [hunk 1]
```diff
@@ -4603,6 +4603,41 @@ func (d *ddl) AlterTablePartitioning(ctx sessionctx.Context, ident ast.Ident, sp
 	}
 	newPartInfo := newMeta.Partition
 
+	// Only non-partition table to partition table need to check global index.
+	if piOld.Type == model.PartitionTypeNone {
```
Comment (mjonss) [inline pkg/ddl/ddl_api.go:4607]:
```suggestion
```
I think it needs to be checked for all types, since this is still accepted:
```mysql
create table t4 (a int primary key, b int) partition by hash(a) partitions 3;
alter table t4 partition by hash(b) partitions 3;
```

**Review by mjonss — CHANGES_REQUESTED** [review]
I found a new case that should be fixed by this PR,
`ALTER TABLE t PARTITION BY ...` on an already partitioned table, must be checked as well, not only non-partitioned tables.

File: pkg/ddl/ddl_api.go (hunk 1 above)
Comment (jiyfhust) [reply pkg/ddl/ddl_api.go:4607]: Yes, you are right. Updated https://github.com/pingcap/tidb/pull/51635/commits/6ab2ba122c80b701a048f6b426c346893e3c1a5f.

**Review by mjonss — APPROVED** [review]
Thanks for the updated PR, LGTM.

**Review by Defined2014 — APPROVED** [review]
