### PR TITLE
txn: Cherry pick client-go#274 to release-5.1

### LINKED ISSUE #27400: information_schema.deadlocks incorrectly collects retryable deadlocks as if it's non-retryble
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Construct a scenario where retryable (single-statement) deadlocks occurs.
2. Check `information_schema.deadlocks` for the information of the retryable deadlock.

### 2. What did you expect to see? (Required)

When the config `pessimistic-txn.deadlock-history-collect-retryable` is not enabled, there shouldn't be information about it; otherwise, there is a deadlock information about it with `retryable` column be `1`.

### 3. What did you see instead (Required)

In both case the deadlock information shows up, and `retryable` column is always `0`.

The reason is that client-go invokes a callback from TiDB to collect the deadlocks, but it's invoked prior to the `IsRetryable` field being set.

### 4. What is your TiDB version? (Required)

master, 5.2, 5.1

### PR DESCRIPTION
**Pull request by longfangsong**
### What problem does this PR solve?

Issue Number: close #27400 on release 5.1

### What is changed and how it works?

What's Changed:

Cherry pick modification in client-go#274 to release-5.1

### Check List 

Tests 

- [x] Unit test
- [x] Integration test

Side effects

NA

Documentation

NA

### Release note 

```release-note
Fix a bug that retryable deadlocks are incorrectly recorded into `INFORMATION_SCHEMA.DEADLOCKS` table.
```

### CODE REVIEW

File: store/tikv/txn.go [hunk 1]
```diff
@@ -593,13 +593,18 @@ func (txn *KVTxn) LockKeys(ctx context.Context, lockCtx *tikv.LockCtx, keysInput
...
+						// Call OnDeadlock before pessimistic rollback.
+						lockCtx.OnDeadlock(dl)
+					}
 				}
 				wg := txn.asyncPessimisticRollback(ctx, keys)
-				if ok {
+				if isDeadlock {
 					logutil.Logger(ctx).Debug("deadlock error received", zap.Uint64("startTS", txn.startTS), zap.Stringer("deadlockInfo", dl))
 					if hashInKeys(dl.DeadlockKeyHash, keys) {
 						dl.IsRetryable = true
```
Comment (youjiali1995) [inline store/tikv/txn.go:610]:
```suggestion
					if dl.IsRetryable {
```

**Review by youjiali1995 — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]
