### PR TITLE
*: Bug Fix/CLUSTER_INFO system table may not work after PD is scaled-in

### LINKED ISSUE #18990: CLUSTER_INFO system table may not work after PD is scaled-in
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Scale-in PD.

### 2. What did you expect to see? (Required)

Successfully query INFORMATION_SCHEMA.CLUSTER_INFO

### 3. What did you see instead (Required)

It tries to access a PD that no longer exists. dial tcp xxxx: connect: connection refused

### 4. Affected version (Required)

v4.0.4

### PR DESCRIPTION
**Pull request by jyz0309**
### What problem does this PR solve?

Issue Number: close #18990

Problem Summary:
CLUSTER_INFO system table may not work after PD is scaled-in

### What is changed and how it works?
What's Changed:
Changed the EtcdAddrs() to get correct pd members info
Changed the GetPDServerInfo function, add rpc GetMember() in pd and TiDB use grpc to get the pd members info.
How it Works:
Use grpc to get the pd members url, then use pd-api `/pd/api/v1/config/cluster-version` and `/pd/api/v1/config/status` to get member version githash info

### Related changes
- PR to update `pingcap/tidb/infoschema/tables.go` and `pingcap/tidb/util/pdapi/const.go`:
- Need to cherry-pick to the release branch

### Check List 

Tests 
- Unit test
- Manual test (add detailed scripts or steps below)
steps:
use tiup playground scale-out --pd 2 to scale out pd
use mysql to connect TiDB
`select * from  INFORMATION_SCHEMA.CLUSTER_INFO; `to test scale out and scale in

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
- Bug fix:CLUSTER_INFO system table may not work after PD is scaled-in or out

### CODE REVIEW

**Comment by jyz0309** [comment]
go get -u github.com/tikv/pd@master

**Comment by breeswish** [comment]
Can we ship this fix in v4.0.6?

**Comment by breeswish** [comment]
Etcd already provides membership API under `/v2/members`. Can we use it directly, instead of introducing another new API in https://github.com/tikv/pd/pull/2830?

**Comment by jyz0309** [comment]
> Etcd already provides membership API under `/v2/members`. Can we use it directly, instead of introducing another new API in [tikv/pd#2830](https://github.com/tikv/pd/pull/2830)?

because this bug is caused by the `Etcdaddr()` function, if we don't add a new API, when we scale in the pd leader,  we can't get the leader ip, and we can't use the `/v2/members` api

**Comment by jyz0309** [comment]
@crazycs520 @XuHuaiyu PTAL

File: domain/domain.go [hunk 1]
```diff
@@ -675,30 +675,32 @@ func NewDomain(store kv.Storage, ddlLease time.Duration, statsLease time.Duratio
...
-					grpc.WithKeepaliveParams(keepalive.ClientParameters{
-						Time:    time.Duration(cfg.TiKVClient.GrpcKeepAliveTime) * time.Second,
-						Timeout: time.Duration(cfg.TiKVClient.GrpcKeepAliveTimeout) * time.Second,
-					}),
-				},
-				TLS: ebd.TLSConfig(),
-			})
-			if err != nil {
-				return errors.Trace(err)
+		if addrs, err := ebd.EtcdAddrs(); err == nil {
```
Comment (crazycs520) [inline domain/domain.go:678]: What happened if `err != nil`?

File: domain/domain.go [hunk 2]
```diff
@@ -700,6 +705,7 @@ func (do *Domain) Init(ddlLease time.Duration, sysFactory func(*Domain) (pools.R
 			}
 			do.etcdClient = cli
 		}
+
```
Comment (crazycs520) [inline domain/domain.go:708]: remove this useless line.

File: domain/domain.go [hunk 3]
```diff
@@ -711,6 +717,7 @@ func (do *Domain) Init(ddlLease time.Duration, sysFactory func(*Domain) (pools.R
 	sysFac := func() (pools.Resource, error) {
 		return sysFactory(do)
 	}
+
```
Comment (crazycs520) [inline domain/domain.go:720]: ditto.

**Comment by jyz0309** [comment]
@breeswish @crazycs520 @XuHuaiyu PTAL

File: executor/infoschema_reader.go [hunk 4]
```diff
@@ -1882,7 +1882,7 @@ type tiflashInstanceInfo struct {
 func (e *TiFlashSystemTableRetriever) initialize(sctx sessionctx.Context, tiflashInstances set.StringSet) error {
 	store := sctx.GetStore()
 	if etcd, ok := store.(tikv.EtcdBackend); ok {
-		if addrs := etcd.EtcdAddrs(); addrs != nil {
+		if addrs, err := etcd.EtcdAddrs(); addrs != nil {
```
Comment (crazycs520) [inline executor/infoschema_reader.go:1885]:
```go
addrs, err := etcd.EtcdAddrs()
if err != nil {
    return err
}
if addrs != nil {
    ....
}
```

File: store/tikv/kv.go [hunk 5]
```diff
@@ -234,8 +235,40 @@ func (s *tikvStore) IsLatchEnabled() bool {
...
+	if s.etcdAddrs == nil {
+		return nil, nil
+	}
+	ctx := context.Background()
+	bo := NewBackofferWithVars(ctx, GetMemberInfoBackoff, nil)
+	etcdAddrs := make([]string, 0)
+	pdClient := s.GetRegionCache().PDClient()
+	if pdClient == nil {
+		return nil, errors.New("Etcd client not found")
+	}
```
Comment (crazycs520) [inline store/tikv/kv.go:248]: Just use `s.pdClient` will be ok.

File: store/tikv/kv.go [hunk 6]
```diff
@@ -234,8 +235,40 @@ func (s *tikvStore) IsLatchEnabled() bool {
...
+				return nil, err
+			}
+		}
+		members, err := pdClient.GetMemberInfo(ctx)
+		if err != nil {
+			backoffErr = err
+			continue
+		}
+		for _, member := range members {
+			u, err := url.Parse(member.ClientUrls[0])
```
Comment (crazycs520) [inline store/tikv/kv.go:263]: Should check `len(member.ClientUrls) > 0`?

**Comment by jyz0309** [comment]
@crazycs520 @XuHuaiyu PTAL

File: store/tikv/kv.go [hunk 7]
```diff
@@ -234,8 +235,41 @@ func (s *tikvStore) IsLatchEnabled() bool {
...
 }
 
-func (s *tikvStore) EtcdAddrs() []string {
-	return s.etcdAddrs
+func (s *tikvStore) EtcdAddrs() ([]string, error) {
+	if s.etcdAddrs == nil {
+		return nil, nil
+	}
+	ctx := context.Background()
+	bo := NewBackofferWithVars(ctx, GetMemberInfoBackoff, nil)
```
Comment (crazycs520) [inline store/tikv/kv.go:243]:
```suggestion
	bo := NewBackoffer(ctx, GetMemberInfoBackoff)
```

File: store/tikv/kv.go [hunk 8]
```diff
@@ -234,8 +235,41 @@ func (s *tikvStore) IsLatchEnabled() bool {
...
+		members, err := pdClient.GetMemberInfo(ctx)
+		if err != nil {
+			backoffErr = err
+			continue
+		}
+		for _, member := range members {
+			if len(member.ClientUrls) > 0 {
+				u, err := url.Parse(member.ClientUrls[0])
+				if err != nil {
+					continue
```
Comment (crazycs520) [inline store/tikv/kv.go:266]: It's better to add an error log here, normally it should never fail.

File: store/tikv/kv.go [hunk 9]
```diff
@@ -234,8 +235,41 @@ func (s *tikvStore) IsLatchEnabled() bool {
...
+	for {
+		if backoffErr != nil {
+			err := bo.Backoff(BoRegionMiss, backoffErr)
+			if err != nil {
+				return nil, err
+			}
+		}
+		members, err := pdClient.GetMemberInfo(ctx)
+		if err != nil {
+			backoffErr = err
```
Comment (crazycs520) [inline store/tikv/kv.go:259]: How about move code in line 252~ 255 to here?

File: store/tikv/kv.go [hunk 10]
```diff
@@ -234,8 +235,38 @@ func (s *tikvStore) IsLatchEnabled() bool {
...
+			if err != nil {
+				return nil, err
+			}
+			continue
+		}
+		for _, member := range members {
+			if len(member.ClientUrls) > 0 {
+				u, err := url.Parse(member.ClientUrls[0])
+				if err != nil {
+					logutil.BgLogger().Error("fail to parse url from member.ClientUrl", zap.Error(err))
```
Comment (crazycs520) [inline store/tikv/kv.go:262]:
```suggestion
					logutil.BgLogger().Error("fail to parse client url from pd members", zap.String("client_url", member.ClientUrls[0]), zap.Error(err))
```

**Review by crazycs520 — COMMENTED** [review]
REST LGTM

File: store/tikv/kv.go [hunk 11]
```diff
@@ -234,8 +235,38 @@ func (s *tikvStore) IsLatchEnabled() bool {
...
+				return nil, err
+			}
+			continue
+		}
+		for _, member := range members {
+			if len(member.ClientUrls) > 0 {
+				u, err := url.Parse(member.ClientUrls[0])
+				if err != nil {
+					logutil.BgLogger().Error("fail to parse client url from pd members", zap.String("client_url", member.ClientUrls[0]), zap.Error(err))
+					continue
```
Comment (wjhuang2016) [inline store/tikv/kv.go:263]: Why not return here?

Comment (jyz0309) [reply store/tikv/kv.go:263]: Becaue I think that parer this member's url have error. but maybe parse the next member url is success

Comment (crazycs520) [reply store/tikv/kv.go:263]: Maybe return error is better, parse URL error is not expected.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by crazycs520 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
