### PR TITLE
server: Cleanup UNIX Socket file

### LINKED ISSUE #26058: tidb using unix socket cannot restart if after SIGKILL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```bash
shell1> ./bin/tidb-server -socket /tmp/tidb.sock
shell2> pkill -SIGKILL tidb-server
shell1> ./bin/tidb-server -socket /tmp/tidb.sock
```

### 2. What did you expect to see? (Required)
Success / tidb-server started again

### 3. What did you see instead (Required)
FATAL error, server not started
```
[2021/07/08 11:23:10.190 +02:00] [FATAL] [main.go:626] ["failed to create the server"] [error="listen unix /tmp/tidb.sock: bind: address already in use"] [stack="main.createServer\n\t/repos/tidb/tidb-server/main.go:626\nmain.main\n\t/repos/tidb/tidb-server/main.go:190\nruntime.main\n\t/usr/lib/go-1.16/src/runtime/proc.go:225"] [stack="main.createServer\n\t/repos/tidb/tidb-server/main.go:626\nmain.main\n\t/repos/tidb/tidb-server/main.go:190\nruntime.main\n\t/usr/lib/go-1.16/src/runtime/proc.go:225"]
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.2.0-alpha-227-g14adc4625
Edition: Community
Git Commit Hash: 14adc46253e4c47b15798b143dcd4055440c5915
Git Branch: master
UTC Build Time: 2021-07-08 09:22:04
GoVersion: go1.16.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #26058

Problem Summary: When `tidb-server` stops unexpectedly it might not be able to cleanup the UNIX socket file it was listening on. The result is that the server can't start again until the file is removed.

### What is changed and how it works?

How it Works:

Getting the list of listening UNIX sockets is possible on Linux, but is not portable.
So instead this tries to `os.Stat()` the socket file and then:

- Checks if this is a socket file
- Checks if it can connect with `net.Dial`
- Removes the file if it is a socket file and if it can't connect.

### Check List 

Tests 

- [x] Manual test (add detailed scripts or steps below)

### Release note 

```release-note
On startup `tidb-server` removes unused socket files from previous instances
```

### CODE REVIEW

**Review by mjonss — APPROVED** [review]
LGTM, nice error handling!

**Review by lysu — APPROVED** [review]
LTGM

File: server/server.go [hunk 1]
```diff
@@ -249,6 +249,30 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
 	}
 
 	if s.cfg.Socket != "" {
+
+		// Try to cleanup the socket file
+		sockStat, err := os.Stat(s.cfg.Socket)
+		if err == nil {
+			if sockStat.Mode().Type() != os.ModeSocket {
+				logutil.BgLogger().Warn("Unix socket has the wrong file type, not removing it",
+					zap.String("socket", s.cfg.Socket), zap.String("file_mode", sockStat.Mode().String()))
```
Comment (morgo) [inline server/server.go:258]: Why not return an error here? The server will fail to bind on line 276, but it could be more descriptive for debugging if you bailout right here.

File: server/server.go [hunk 2]
```diff
@@ -249,6 +249,30 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
...
+					logutil.BgLogger().Warn("Unix socket exists and is nonfunctional, removing it",
+						zap.String("socket", s.cfg.Socket), zap.Error(err))
+					err = os.Remove(s.cfg.Socket)
+					if err != nil {
+						logutil.BgLogger().Warn("Failed to remove socket file",
+							zap.String("socket", s.cfg.Socket), zap.Error(err))
+					}
+				} else {
+					logutil.BgLogger().Warn("Unix socket exists and is functional, not removing it",
+						zap.String("socket", s.cfg.Socket), zap.String("file_mode", sockStat.Mode().String()))
```
Comment (morgo) [inline server/server.go:271]: Same here and here - I would prefer if the error is returned and server start fails, since these errors are more descriptive than the error which will be returned on line 276 which is inevitable.

File: server/server.go [hunk 3]
```diff
@@ -249,6 +249,30 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
 	}
 
 	if s.cfg.Socket != "" {
+
+		// Try to cleanup the socket file
+		sockStat, err := os.Stat(s.cfg.Socket)
```
Comment (xhebox) [inline server/server.go:254]: Maybe we could do the cleanup after `net.Listen("unix", s.cfg.Socket);` failed.

File: server/server.go (hunk 1 above)
Comment (morgo) [reply server/server.go:258]: Yes, you can use `fmt.Errorf` instead.

I realize it will still error successfully later on, but users when inspecting will often look at the last error. My point is that failing at the point you know you won't be able to continue is useful (and the error is more descriptive).

File: server/server.go (hunk 3 above)
Comment (dveeden) [reply server/server.go:254]: So something like
```go
for i := 0; i < 2; i++ {
    if s.socket, err = net.Listen("unix", s.cfg.Socket); err != nil {
        if i > 0 {
            return nil, errors.Trace(err)
        } else {
            // Try to cleanup socket file
        }
    } else {
        break
    }
}
```

Doing this before the `net.Listen()` looks cleaner to me. What would be the benefit of doing this once it has failed?

File: server/server.go [hunk 4]
```diff
@@ -295,6 +301,30 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
...
+				zap.String("socket", socket), zap.Error(err))
+			err = os.Remove(socket)
+			if err != nil {
+				return fmt.Errorf("failed to remove socket file %s", socket)
+			}
+		} else {
+			return fmt.Errorf("unix socket %s exists and is functional, not removing it", socket)
+		}
+	}
+	return err
```
Comment (morgo) [inline server/server.go:325]: I think there's a bug here. If the file doesn't exist, won't it return an `err`? In which case, you need to return `nil` since there was no cleanup required versus returning the error.

File: server/server.go (hunk 3 above)
Comment (xhebox) [reply server/server.go]: We don't have any overhead if it succeeds. Not a big benefit, but it is my preference

Comment (morgo) [reply server/server.go]: @xhebox I prefer to cleanup the stale socket first. Otherwise the logging scenario is not clear, because if the `net.Listen` fails you probably want to log it, but only on `i > 0` scenarios.

**Review by morgo — APPROVED** [review]
LGTM, but lets give @xhebox a moment to respond as well before merging.

File: server/server.go (hunk 3 above)
Comment (xhebox) [reply server/server.go]: OK, anyway, it is fine.
