### PR TITLE
copr: increase extra concurrency for small coprocessor tasks

### LINKED ISSUE #37724: Optimize handle read in large cluster
### Background

TiDB indexes data with global index, which lead to a problem that when data grows, some the required data may be sharded into many regions. One of those problem is when reading with indexlookup executor, the table scan may be divided into many coprocessor tasks.

bad-indexlookup

As the figure shows, the continuous index range may point to many discontinuous handle ranges in indexlookup executor. The default [`tidb_distsql_scan_concurrency`](https://github.com/pingcap/tidb/blob/e75a079d432ef0f40ae11b72ef61316d2e0adbd5/sessionctx/variable/tidb_vars.go#L839)  is 15, with a big number of handle read tasks, the concurrency is not sufficient and the latency increases. I wrote a [script](https://gist.github.com/you06/3df2f6d00162cda4f4545728c5784c23) to reproduce this issue.

### Solution

Note we can know the entries in handle ranges because TiDB guarantees the consistency of index and data, which means we already know the size of coprocessor tasks when reading handles, and we can adjust the concurrency by increasing the extra concurrency for small tasks. Small tasks won't block other queries on TiKV side because they are extremely fast(mostly less than 1ms on TiKV side).

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: close #37724

Problem Summary:

### What is changed and how it works?

When there are many small coprocessor tasks, the default value of `tidb_distsql_scan_concurrency` harms the latency. This PR increases extra concurrency when we exactly know there are small coprocessor tasks.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
- [x] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Optimize handles read requests by increasing extra concurrency for small coprocessor tasks.
```

### CODE REVIEW

**Comment by you06** [comment]
@wshwsh12 PTAL

**Comment by cfzjywxk** [comment]
@you06 
Any update?

**Comment by you06** [comment]
> @you06 Any update?

I'm fixing the tests broken by this PR.

**Review by guo-shaoge — APPROVED** [review]

File: store/copr/coprocessor.go [hunk 1]
```diff
@@ -66,6 +67,8 @@ var (
 const (
 	copBuildTaskMaxBackoff = 5000
 	copNextMaxBackoff      = 20000
+	copSmallTaskRow        = 6
```
Comment (cfzjywxk) [inline store/copr/coprocessor.go:70]: Is this number a bit small?

File: store/copr/coprocessor.go [hunk 2]
```diff
@@ -244,6 +264,24 @@ func buildCopTasks(bo *Backoffer, cache *RegionCache, ranges *KeyRanges, req *kv
 		}
 		for i := 0; i < rLen; {
 			nextI := mathutil.Min(i+rangesPerTask, rLen)
+			hint := -1
+			// calculate the row count hint
+			if req.FixedRowCountHint != nil {
+				startKey, endKey := loc.Ranges.At(i).StartKey, loc.Ranges.At(nextI-1).EndKey
+				// move to the previous range if startKey of current range is lower than endKey of previous location.
```
Comment (cfzjywxk) [inline store/copr/coprocessor.go:271]: Better to add an example here as this part itself is quite complex and difficult to understand.

File: store/copr/coprocessor_test.go [hunk 3]
```diff
@@ -655,3 +655,63 @@ func TestCalculateRemain(t *testing.T) {
...
+	require.False(t, isSmallTask(&copTask{RowCountHint: -1}))
+	require.False(t, isSmallTask(&copTask{RowCountHint: 0}))
+	require.True(t, isSmallTask(&copTask{RowCountHint: 1}))
+	require.True(t, isSmallTask(&copTask{RowCountHint: 6}))
+	require.False(t, isSmallTask(&copTask{RowCountHint: 7}))
+	_, conc := smallTaskConcurrency([]*copTask{})
+	require.GreaterOrEqual(t, conc, 0)
+}
+
+func TestBuildCopTasksWithRowCountHint(t *testing.T) {
```
Comment (cfzjywxk) [inline store/copr/coprocessor_test.go:669]: Should we add a cross-region long range here?

File: store/copr/coprocessor.go (hunk 1 above)
Comment (cfzjywxk) [reply store/copr/coprocessor.go:70]: Maybe it's difficult to set it to a certain value, we could add some comments about the scenarios that may benefit from this value and some others may not.

Comment (you06) [reply store/copr/coprocessor.go:70]: What about `32`, the initial batch size of TiKV.

Comment (cfzjywxk) [reply store/copr/coprocessor.go:70]: It's fine to me.

File: store/copr/coprocessor.go [hunk 4]
```diff
@@ -164,20 +195,17 @@ func (c *CopClient) Send(ctx context.Context, req *kv.Request, variables interfa
 				}
 			})
 		}
-		it.sendRate = util.NewRateLimit(2 * it.concurrency)
+		if it.smallTaskConcurrency > 20 {
+			it.smallTaskConcurrency = 20
+		}
```
Comment (wshwsh12) [inline store/copr/coprocessor.go:200]: 1. What happens if user set tidb_distsql_scan_concurrency bigger than 20?  Will it cause the SQL latency to be worse than before the feature was implemented?
2. If 20 is ok, why the default value 15 can not work well?

File: store/copr/coprocessor.go [hunk 5]
```diff
@@ -307,11 +361,37 @@ func reverseTasks(tasks []*copTask) {
...
+		if isSmallTask(task) {
+			res++
+		}
+	}
+	if res == 0 {
+		return 0, 0
+	}
+	// Calculate the extra concurrency for small tasks
+	// extra concurrency = tasks / (1 + sigma * sqrt(log(tasks ^ 2)))
+	extraConc := float64(res) / (1 + smallTaskSigma*math.Sqrt(math.Log(float64(res*res))))
```
Comment (wshwsh12) [inline store/copr/coprocessor.go:385]:
```suggestion
	extraConc := float64(res) / (1 + smallTaskSigma*math.Sqrt(2*math.Log(float64(res))))
```
`res*res` maybe overflow in 32-bits machine when `res >= 65536`

File: store/copr/coprocessor.go (hunk 4 above)
Comment (you06) [reply store/copr/coprocessor.go:200]: > Will it cause the SQL latency to be worse than before the feature was implemented?

The concurrency is adjusted in keep order mode, before the feature, concurrency will be reduced to 2 in this case and it's not affected by `tidb_distsql_scan_concurrency`, see [description](https://github.com/pingcap/tidb/blob/84fbfcada3d9564fe922771f010db318d27fc77a/store/copr/coprocessor.go#L149-L158).

> If 20 is ok, why the default value 15 can not work well?

This number is not carefully chosen, just set an upper limit.

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Comment by you06** [comment]
> Any bench result to show the great improvement of this change?

I attached the bench result to the description.

**Comment by zhangjinpeng1987** [comment]
> > Any bench result to show the great improvement of this change?
> 
> I attached the bench result to the description.

When there many requests has fan out characteristics, the test result including p99 should be much more better?

**Comment by cfzjywxk** [comment]
> > > Any bench result to show the great improvement of this change?
> > 
> > 
> > I attached the bench result to the description.
> 
> When there many requests has fan out characteristics, the test result including p99 should be much more better?

@zhangjinpeng1987 
The average latency and p99 should both be better if the coprocessor tasks are not accumulated in the tikv side, and this PR just optimizes the task wait in the tidb side. If there's already task queueing in the tikv side, this change may in turn increase latency.
