### PR TITLE
expression: fix using tidb_decode_plan to decode plan and query in information_schema.slow_query returns error

### LINKED ISSUE #16939: using `tidb_decode_plan` to decode plan and query in `information_schame.slow_query` returns error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
```
select sleep(2);
select tidb_decode_plan(query), time from information_schema.slow_query order by time desc limit 1;
```

### 2. What did you expect to see?
Return the query `select sleep(2)`.

### 3. What did you see instead?
```
ERROR 1105 (HY000): illegal base64 data at input byte 6
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
The latest master branch.

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #16939

Problem Summary:

### What is changed and how it works?

What's Changed:
fix using tidb_decode_plan to decode plan and query in information_schema.slow_query returns error
How it Works:
return the original string when `tidb_decode_plan` can't decode plan

### Check List 

Tests 
- Integration test

### Release note 

- No release note

### CODE REVIEW

File: expression/builtin_info.go [hunk 1]
```diff
@@ -803,6 +803,9 @@ func (b *builtinTiDBDecodePlanSig) evalString(row chunk.Row) (string, bool, erro
 		return "", isNull, err
 	}
 	planTree, err := plancodec.DecodePlan(planString)
+	if err != nil {
+		return planString, false, nil
+	}
 	return planTree, false, err
 }
```
Comment (crazycs520) [inline expression/builtin_info.go:810]:
```suggestion
	planTree, _ := plancodec.DecodePlan(planString)
	return planTree, false, nil
}
```

File: expression/integration_test.go [hunk 2]
```diff
@@ -4649,6 +4649,9 @@ func (s *testIntegrationSuite) TestTiDBDecodePlanFunc(c *C) {
 		"\t  └─IndexReader_28  \troot\t1      \tindex:Limit_27                                              \t1      \ttime:216.85µs, loops:1, rpc num: 1, rpc time:150.824µs, proc keys:0\t198 Bytes\tN/A\n" +
 		"\t    └─Limit_27      \tcop \t1      \toffset:0, count:1                                           \t1      \ttime:57.396µs, loops:2                                              \tN/A      \tN/A\n" +
 		"\t      └─IndexScan_26\tcop \t1      \ttable:t, index:idx(a), range:(0,+inf], keep order:true, desc\t1      \ttime:56.661µs, loops:1                                              \tN/A      \tN/A"))
+
+	// Test issue16939
+	tk.MustQuery("select tidb_decode_plan(query), time from information_schema.slow_query order by time desc limit 1;")
```
Comment (crazycs520) [inline expression/integration_test.go:4654]: Also add test for: 


```sql
tk.MustQuery("select tidb_decode_plan('xxx')").Check(testkit.Rows("xxx"))
```

File: expression/builtin_info.go (hunk 1 above)
Comment (crazycs520) [reply expression/builtin_info.go:810]: Ops, look like `make check` will get a warning for doesn't check the error, forgot that.

**Review by crazycs520 — COMMENTED** [review]
LGTM

@qw4990 PTAL

File: expression/builtin_info.go [hunk 3]
```diff
@@ -803,6 +803,9 @@ func (b *builtinTiDBDecodePlanSig) evalString(row chunk.Row) (string, bool, erro
 		return "", isNull, err
 	}
 	planTree, err := plancodec.DecodePlan(planString)
+	if err != nil {
+		return planString, false, nil
+	}
 	return planTree, false, err
```
Comment (XuHuaiyu) [inline expression/builtin_info.go:809]: err --> nil ?

Comment (TszKitLo40) [reply expression/builtin_info.go:809]: If the `planString` can't be decoded, we should return planString directly, and it should not be considered as error.

Comment (XuHuaiyu) [reply expression/builtin_info.go:809]: I mean the err in line must be nil. So we can `return nil` here

Comment (TszKitLo40) [reply expression/builtin_info.go:809]: Do you mean return `planTree, false, nil` in L809?

Comment (XuHuaiyu) [reply expression/builtin_info.go:809]: Yes

**Comment by XuHuaiyu** [comment]
LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
