### PR TITLE
ddl: Add checks for all partitioning columns during EXCHANGE PARTITION for RANGE COLUMNS

### LINKED ISSUE #59534: exchange partition incorrectly report `Found a row that does not match the partition`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE di_tidb_wzp_test (a1 int(11) not null,a2 int(11) not null,a3 date default null, primary key (`a1`,`a2`)) partition by range columns(`a1`,`a2`)(partition `p10` values less than (10,10),partition `p20` values less than (20,20),partition `pmax` values less than (maxvalue,maxvalue));
insert into di_tidb_wzp_test values(5,10,null);
insert into di_tidb_wzp_test values(10,4,null);
CREATE TABLE di_tidb_wzp_test_np (a1 int(11) not null,a2 int(11) not null,a3 date default null, primary key (`a1`,`a2`));
insert into di_tidb_wzp_test_np values(10,4,null);
insert into di_tidb_wzp_test_np values(4,10,null);
alter table di_tidb_wzp_test exchange partition p10 with table di_tidb_wzp_test_np;
```

### 2. What did you expect to see? (Required)

alter table succeeds.

### 3. What did you see instead (Required)

```
mysql> alter table di_tidb_wzp_test exchange partition p10 with table di_tidb_wzp_test_np;
ERROR 1737 (HY000): Found a row that does not match the partition
```

### 4. What is your TiDB version? (Required)

v8.5.0

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #59534

Problem Summary:
The validation for RANGE COLUMNS partitioned tables in EXCHANGE PARTITION only checked the first column.

### What changed and how does it work?
Extended the implementation for multiple columns and added tests to verify the validation.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
`ALTER TABLE pt EXCHANGE PARTITION p1 WITH TABLE npt` for RANGE COLUMNS partitioned tables, only checked the first partitioning column, now fixed to handle the full list in PARTITION BY RANGE COLUMNS (c1,c2,c3,...)
```

### CODE REVIEW

File: pkg/ddl/tests/partition/exchange_partition_test.go [hunk 1]
```diff
@@ -0,0 +1,130 @@
+package partition
```
Comment (Defined2014) [inline pkg/ddl/tests/partition/exchange_partition_test.go:1]: Please add a valid license header

**Review by Defined2014 — COMMENTED** [review]
`TestMultiSchemaPartitionByGlobalIndex` test failed

**Review by Defined2014 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
