### PR TITLE
lightning: allow parallel import with conflict detection

### LINKED ISSUE #52001: conflict.strategy cannot be used with tikv-importer.parallel-import and tikv-importer.backend = "local" and conflict.precheck-conflict-before-import = true
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

parallel import data with two lightning
config is : [conflict]\nprecheck-conflict-before-import = true\nstrategy=\"replace\"\n[tikv-importer]\nparallel-import = true

### 2. What did you expect to see? (Required)
import successfully
### 3. What did you see instead (Required)
fail with 
```
2024-03-21T21:22:11.310+0800    INFO    host/host.go:52 Execute command error   {"command": "/tidb-lightning \"-c\" \"/tmp/tidb-lightning.toml\"", "exit code": 1, "stdout": "Verbose debug logs will be written to /tmp/lightning.log.2024-03-21T13.22.11Z\n\n", "stderr": "tidb lightning encountered error: [Lightning:Config:ErrInvalidConfig]conflict.strategy cannot be used with tikv-importer.parallel-import and tikv-importer.backend = \"local\" and conflict.precheck-conflict-before-import = true\n", "error": "command terminated with exit code 1"}
```
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by lyzx2001**
### What problem does this PR solve?

Issue Number: close #52001 

Problem Summary:
conflict.strategy cannot be used with tikv-importer.parallel-import and tikv-importer.backend = "local" and conflict.precheck-conflict-before-import = true
### What changed and how does it work?
allow parallel import with conflict detection
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/config/config.go [hunk 1]
```diff
@@ -1361,17 +1361,10 @@ func (c *Conflict) adjust(i *TikvImporter, l *Lightning) error {
...
-			return common.ErrInvalidConfig.GenWithStack(
-				`%s cannot be used with tikv-importer.parallel-import and tikv-importer.backend = "local" and conflict.precheck-conflict-before-import = true`,
-				strategyConfigFrom)
-		}
-		if !strategyFromDuplicateResolution && i.DuplicateResolution != NoneOnDup {
-			return common.ErrInvalidConfig.GenWithStack(
-				"%s cannot be used with tikv-importer.duplicate-resolution",
-				strategyConfigFrom)
-		}
+	if !strategyFromDuplicateResolution && c.Strategy != NoneOnDup && i.DuplicateResolution != NoneOnDup {
```
Comment (Benjamin2037) [inline br/pkg/lightning/config/config.go:1364]: Now， we will not distinct whether it is logical import?

Comment (lyzx2001) [reply br/pkg/lightning/config/config.go:1364]: I removed the check of 
```
if c.Strategy != NoneOnDup {
		if i.ParallelImport && i.Backend == BackendLocal && c.PrecheckConflictBeforeImport {
```
Since now we can support parallel import with preprocess conflict detection for local backend.

Originally this was not supported because preprocess and post-import conflict detection are not allowed to be used together, so only conducting preprocess conflict detection may still result in conflicts in the scenarios of parallel import.

Comment (Benjamin2037) [reply br/pkg/lightning/config/config.go:1364]: So now we support preprocess + post-import conflict， post-import conflict。 the post-import conflict will always enabled, right?

**Review by Benjamin2037 — APPROVED** [review]
rest LGTM

File: br/pkg/lightning/config/config.go (hunk 1 above)
Comment (lyzx2001) [reply br/pkg/lightning/config/config.go:1364]: yes

**Review by D3Hunter — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]
The change is for lightning. LGTM.
