### PR TITLE
cpuprofile: make sure the cpu profile will be produced each second

### LINKED ISSUE #31435: Top SQL is not reporting workload for all seconds
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start a continuous workload by using the sysbench.

### 2. What did you expect to see? (Required)

I can see the workload of every second according to the UI dashboard for Top SQL.

### 3. What did you see instead (Required)

image

Several seconds of data is missing.

### 4. What is your TiDB version? (Required)

v5.4.0

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

close #31435

issue #31539

### What is changed and how it works?

This PR remove `sleep 1 second` and only use `ticker` to make sure produce cpu profile each second.
And tiny refine the reporter collect cpu/stmt data logic.

image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Documentation

N/A

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@breeswish @mornyx PTAL

**Comment by mornyx** [comment]
LGTM

File: util/cpuprofile/cpuprofile.go [hunk 1]
```diff
@@ -133,12 +134,15 @@ func (p *parallelCPUProfiler) register(ch ProfileConsumer) {
...
+	isFirst := len(p.cs) == 0
 	p.cs[ch] = struct{}{}
 	p.Unlock()
 
-	select {
-	case p.notifyRegister <- struct{}{}:
-	default:
+	if isFirst {
+		select {
+		case p.notifyRegister <- struct{}{}:
```
Comment (zhongzc) [inline util/cpuprofile/cpuprofile.go:143]: Generally LGTM. But I'm considering if `notifyRegister` can be eliminated.

Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:143]: `notifyRegister` should better to keep it for handling cpu profile request timely for the first consumer.

File: util/cpuprofile/cpuprofile.go [hunk 2]
```diff
@@ -133,12 +135,15 @@ func (p *parallelCPUProfiler) register(ch ProfileConsumer) {
...
 	}
 	p.Lock()
+	isFirst := len(p.cs) == 0
 	p.cs[ch] = struct{}{}
 	p.Unlock()
 
-	select {
-	case p.notifyRegister <- struct{}{}:
-	default:
+	if isFirst {
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:142]: There is a race condition there that the isFirst in L138 is not the same as the actual "is first" when you use it at L142.

Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:142]: Sorry, I can't get you, there is already a lock, why still have race condition?

Comment (breeswish) [reply util/cpuprofile/cpuprofile.go:142]: Suppose:

- When executed at L138 there is one registered downstream, so that your `isFirst = false`. 
- During executing L140 ~ L142, this downstream is deregistered.
- Then at L143 `notifyRegister` is not called as you have `isFirst = false` but at that time there is already no downstream any more.

Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go]: Ok, look like the `isFirst` variable is misleading, I already remove it, and use another way to implement this logic, PTAL

File: util/cpuprofile/cpuprofile.go [hunk 3]
```diff
@@ -155,43 +157,46 @@ func (p *parallelCPUProfiler) profilingLoop() {
...
+			}
 		case <-checkTicker.C:
 		}
 		p.doProfiling()
 	}
 }
 
 func (p *parallelCPUProfiler) doProfiling() {
+	if p.profileData != nil {
+		pprof.StopCPUProfile()
```
Comment (breeswish) [inline util/cpuprofile/cpuprofile.go:180]: This implementation is buggy. Suppose that someone has already started a profiling before starting the parallel cpu profiler:

At L193 you will have err != nil since the global profiler is already started by someone else.
Then at L179 you stops the other people's cpu profiler unexpectedly.

Comment (crazycs520) [reply util/cpuprofile/cpuprofile.go:180]: No, since in `sendToConsumers`, `p.profileData` will be set to `nil` after send.

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
Unit test failed

**Review by wjhuang2016 — APPROVED** [review]

**Review by zhongzc — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
Approved on behalf of @zhongzc

**Comment by breeswish** [comment]
@crazycs520 Unit test failed


[2022-01-13T07:47:56.242Z] === FAIL: util/topsql/collector TestPProfCPUProfile (1.11s)
[2022-01-13T07:47:56.242Z]     main_test.go:73: 
[2022-01-13T07:47:56.242Z]         	Error Trace:	main_test.go:73
[2022-01-13T07:47:56.242Z]         	Error:      	Should be true
[2022-01-13T07:47:56.242Z]         	Test:       	TestPProfCPUProfile
[2022-01-13T07:47:56.242Z]
