### PR TITLE
ddl, owner: refresh ddl sequence cache after becoming the owner

### LINKED ISSUE #35513: seq_num may be duplicate
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
2 TiDB.
TiDB 1 to be the owner and execute a DDL.
Resign owner.
TiDB 2 to be the owner and execute a DDL.

### 2. What did you expect to see? (Required)
The seq_num is unique.

### 3. What did you see instead (Required)
```
 {
  "id": 70,
  "type": 3,
  "schema_id": 1,
  "table_id": 69,
  "schema_name": "test",
  "table_name": "t",
  "state": 6,
  "err": null,
  "err_count": 0,
  "row_count": 0,
  "raw_args": null,
  "query": "create table t(a int)",
   ....
  "version": 1,
  "reorg_meta": null,
  "multi_schema_info": null,
  "priority": 0,
  "seq_num": 35
 },
 {
  "id": 72,
  "type": 3,
  "schema_id": 1,
  "table_id": 71,
  "schema_name": "test",
  "table_name": "t3",
  "query": "create table t3(a int)",
...
  "version": 1,
  "reorg_meta": null,
  "multi_schema_info": null,
  "priority": 0,
  "seq_num": 35
 }
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #35513

Problem Summary:
We init the ddl sequence cache when ddl gets start. But if it's not owner anymore, the cache is out of date.
We should refresh it after a TiDB becomes the owner.

### What is changed and how it works?
Add a callback function for ownerManager.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
As I did in https://github.com/pingcap/tidb/issues/35513, the DDL sequence is unique now.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/ddl.go [hunk 1]
```diff
@@ -476,6 +476,14 @@ func (d *ddl) Start(ctxPool *pools.ResourcePool) error {
 	// If RunWorker is true, we need campaign owner and do DDL job.
 	// Otherwise, we needn't do that.
 	if RunWorker {
+		d.ownerManager.SetBeOwnerHook(func() {
+			var err error
+			d.ddlSeqNumMu.seqNum, err = d.GetNextDDLSeqNum()
+			if err != nil {
+				logutil.BgLogger().Error("error when getting the ddl history count", zap.Error(err))
```
Comment (tangenta) [inline ddl/ddl.go:483]: So when there is a temporary error, the seqNum is still wrong. Is it acceptable?

Comment (wjhuang2016) [reply ddl/ddl.go:483]: It's used for debug/testing propose, so I think it's fine to ignore the error.

**Review by tangenta — APPROVED** [review]
