### PR TITLE
br: fix br integration test

### LINKED ISSUE #53835: fix unstable integration test for br
## Bug Report

The br integration test `br_full_ddl` is unstable.

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #53835

Problem Summary:

### What changed and how does it work?
1. fix br integration test `br_txn` and `br_full_ddl`.
2. add br integration test for corruption of snapshot/log backup file.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by BornChanger — APPROVED** [review]

File: br/tests/br_file_corruption/run.sh [hunk 1]
```diff
@@ -0,0 +1,41 @@
+#!/bin/sh
```
Comment (BornChanger) [inline br/tests/br_file_corruption/run.sh:1]: can we also add scenarios where sst file or log file is missing and is out of sync with backup meta file?

**Review by 3pointer — APPROVED** [review]
