### PR TITLE
br: retry to set tiflash replicas

### LINKED ISSUE #63685: log restore setting tiflash replica should retry
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
PITR restore

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
```
[2025/09/22 12:30:45.126 +00:00] [INFO] [collector.go:77] ["restore log failed summary"] [error="failed to reset tiflash replicas: [domain:8028]Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]"] 
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #63685

Problem Summary:
some error may occur during reset tiflash replica, which is retryable.
### What changed and how does it work?
retry the error
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/log_client/client.go [hunk 1]
```diff
@@ -1518,8 +1518,22 @@ func (rc *LogClient) ResetTiflashReplicas(ctx context.Context, sqls []string, g
...
 			resetSession := resetSessions[id%uint64(len(resetSessions))]
-			log.Info("reset tiflash replica", zap.String("sql", sql))
-			return resetSession.ExecuteInternal(ectx, sql)
+			log.Info("reset tiflash replica", zap.Uint64("task id", id), zap.String("sql", sql))
+			var resetErr error
+			for range 5 {
+				resetErr = resetSession.ExecuteInternal(ectx, sql)
+				if resetErr == nil {
+					break
+				}
```
Comment (lance6716) [inline br/pkg/restore/log_client/client.go:1527]: no need to retry if `ectx.Err()` is not nil (canceled or timed-out)

Comment (Leavrth) [reply br/pkg/restore/log_client/client.go:1527]: done

**Review by YuJuncen — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
