### PR TITLE
planner,executor: fix cannot dump plan replayer when query happen to panic

### LINKED ISSUE #64835: Even if the query panics, it should still be possible to perform a plan replayer dump.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

for example. The bug https://github.com/pingcap/tidb/issues/63862 need to dump plan replayer.

### 2. What did you expect to see? (Required)

success to dump plan replayer
### 3. What did you see instead (Required)

```
TiDB root@127.0.0.1:test> plan replayer dump explain SELECT /*+ read_from_storage(tikv[t0,t1,t2,t3]) */ COUNT(t2.c0), COUNT(*) FROM v
                       -> 1 AS t0 INNER JOIN tb1 AS t1 ON (t0.data_status = t1.c0) INNER JOIN tb0 AS t2 ON (t1.id = t2.c2) RIGHT JOIN
                       ->  (SELECT /*+ read_from_storage(tikv[t0]) */ t0.c0 AS col_0 FROM tb1 AS t0) AS t3 ON (t2.c1 = t3.col_0) WHER
                       -> E t2.c2 GROUP BY t0.id, t0.c0, t0.c2, t0.data_status HAVING (COUNT(*) < 87);
(1105, 'interface conversion: expression.Expression is nil, not *expression.ScalarFunction')
```
### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/commit/f9d957a1e7b213f793d662a60935272f9ef3bc68

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #64835

Problem Summary:

### What changed and how does it work?

There are two issues here. 

- First, the failure to recover during optimization led to the entire plan replayer dump failing. 
- Second, the error judgment in dumping the explain plan caused the dump to be interrupted.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

test case from https://github.com/pingcap/tidb/issues/63862

```
mysql> SELECT /*+ read_from_storage(tikv[t0,t1,t2,t3]) */ COUNT(t2.c0), COUNT(*) FROM v1 AS t0 INNER JOIN tb1 AS t1 ON (t0.data_status = t1.c0) INNER JOIN tb0 AS t2 ON (t1.id = t2.c2) RIGHT JOIN (SELECT /*+ read_from_storage(tikv[t0]) */ t0.c0 AS col_0 FROM tb1 AS t0) AS t3 ON (t2.c1 = t3.col_0) WHERE t2.c2 GROUP BY t0.id, t0.c0, t0.c2, t0.data_status HAVING (COUNT(*) < 87);
ERROR 1105 (HY000): interface conversion: expression.Expression is nil, not *expression.ScalarFunction
mysql> plan replayer dump explain SELECT /*+ read_from_storage(tikv[t0,t1,t2,t3]) */ COUNT(t2.c0), COUNT(*) FROM v1 AS t0 INNER JOIN
tb1 AS t1 ON (t0.data_status = t1.c0) INNER JOIN tb0 AS t2 ON (t1.id = t2.c2) RIGHT JOIN (SELECT /*+ read_from_storage(tikv[t0]) */ t0.c0 AS col_0 FROM tb1 AS t0
 87) ;
+-----------------------------------------------------------+
| File_token                                                |
+-----------------------------------------------------------+
| replayer_HGAtXY8Blo2NEkaW5L0N2Q==_1764745398864348000.zip |
+-----------------------------------------------------------+
1 row in set, 2 warnings (0.06 sec)

```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/server/handler/optimizor/plan_replayer_test.go [hunk 1]
```diff
@@ -598,6 +598,13 @@ FROM test_table t1
 JOIN test_table t2 ON t1.id = t2.id;
 `)
 	tk.MustExec(`use test`)
+	if injectedPanic {
+		fpName := "github.com/pingcap/tidb/pkg/planner/core/ConsumeVolcanoOptimizePanic"
+		require.NoError(t, failpoint.Enable(fpName, "5%panic(\"injected panic\")"))
```
Comment (AilinKid) [inline pkg/server/handler/optimizor/plan_replayer_test.go]: what this 5% here means

Comment (hawkingrei) [reply pkg/server/handler/optimizor/plan_replayer_test.go]: I updated the code to remove 5%
