### PR TITLE
planner: fix range partition prune with an unsigned column

### LINKED ISSUE #50082: incorrect tableDual plan caused by range partition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` SQL
CREATE TABLE `t5adc716d` (
  `col_38` mediumint(8) unsigned DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
PARTITION BY RANGE (`col_38`)
(PARTITION `p0` VALUES LESS THAN (5086706),
 PARTITION `p1` VALUES LESS THAN (7268292),
 PARTITION `p2` VALUES LESS THAN (16545422));

desc select * from t5adc716d where col_38 BETWEEN -6895222 AND 3125507;
```

### 2. What did you expect to see? (Required)

TableScan

### 3. What did you see instead (Required)

``` SQL
mysql> desc select * from t5adc716d where col_38 BETWEEN -6895222 AND 3125507;
+-------------+---------+------+---------------+---------------+
| id          | estRows | task | access object | operator info |
+-------------+---------+------+---------------+---------------+
| TableDual_7 | 0.00    | root |               | rows:0        |
+-------------+---------+------+---------------+---------------+
1 row in set, 1 warning (0.00 sec)
```
### 4. What is your TiDB version? (Required)
ebe334f48b8a1244f6aea527c3e64df299d416aa

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #50082

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/rule_partition_processor.go [hunk 1]
```diff
@@ -1419,18 +1400,21 @@ func partitionRangeForInExpr(sctx sessionctx.Context, args []expression.Expressi
...
 		var err error
+		var unsigned bool
 		if pruner.partFn != nil {
 			// replace fn(col) to fn(const)
 			partFnConst := replaceColumnWithConst(pruner.partFn, constExpr)
 			val, _, err = partFnConst.EvalInt(sctx, chunk.Row{})
+			unsigned = mysql.HasUnsignedFlag(partFnConst.GetType().GetFlag())
 		} else {
-			val, err = constExpr.Value.ToInt64(sctx.GetSessionVars().StmtCtx.TypeCtx())
+			val, _, err = constExpr.EvalInt(sctx, chunk.Row{})
```
Comment (Defined2014) [inline pkg/planner/core/rule_partition_processor.go:1410]: Before it will return an overflow error, the we will select full range.

**Review by tiancaiamao — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

File: pkg/planner/core/rule_partition_processor.go [hunk 2]
```diff
@@ -852,39 +852,21 @@ func (*partitionProcessor) name() string {
...
-		if lt.maxvalue {
-			return 1
-		}
-	}
-	if unsigned {
-		return compareUnsigned(lt.data[ith], v)
-	}
-	switch {
-	case lt.data[ith] > v:
+	// TODO: get an extra partition when `v` bigger than `lt.maxvalue``, but the result still correct.
```
Comment (mjonss) [inline pkg/planner/core/rule_partition_processor.go:864]: Can you elaborate on this comment?
Does not this mean that it there is a `MAXVALUE` as the last partition, it will always be bigger / fit the value?

File: pkg/types/compare.go [hunk 3]
```diff
@@ -84,3 +85,27 @@ func VecCompareIU(x []int64, y []uint64, res []int64) {
 func CompareString(x, y, collation string) int {
 	return collate.GetCollator(collation).Compare(x, y)
 }
+
+// CompareInt return an integer comparing the integer x to y with signed or unsigned.
+func CompareInt(arg0 int64, isUnsigned0 bool, arg1 int64, isUnsigned1 bool) int {
+	var res int
+	switch {
+	case isUnsigned0 && isUnsigned1:
+		res = cmp.Compare(uint64(arg0), uint64(arg1))
```
Comment (mjonss) [inline pkg/types/compare.go:94]: Why use cmp.Compare here? Just curious since it has a small overhead trying to check for NaN and have some generic code for handling Floats, which is not needed for ints.

File: pkg/planner/core/rule_partition_processor.go (hunk 2 above)
Comment (Defined2014) [reply pkg/planner/core/rule_partition_processor.go:864]:
```
mysql> explain select * from t where a > 9223372036854775809;
+-------------------------+----------+-----------+-----------------------+-----------------------------------+
| id                      | estRows  | task      | access object         | operator info                     |
+-------------------------+----------+-----------+-----------------------+-----------------------------------+
| TableReader_9           | 0.00     | root      |                       | data:Selection_8                  |
| └─Selection_8           | 0.00     | cop[tikv] |                       | gt(test.t.a, 9223372036854775809) |
|   └─TableFullScan_7     | 10000.00 | cop[tikv] | table:t, partition:p1 | keep order:false, stats:pseudo    |
+-------------------------+----------+-----------+-----------------------+-----------------------------------+
3 rows in set, 1 warning (0.00 sec)

mysql> show create table t;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                   |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`a`)
(PARTITION `p0` VALUES LESS THAN (5086706),
 PARTITION `p1` VALUES LESS THAN (MAXVALUE)) |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

`9223372036854775809` already bigger than max value of signed bigint. In MySQL the plan is like 

```
mysql> explain select * from t where a > 9223372036854775809;
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra            |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------+
|  1 | SIMPLE      | NULL  | NULL       | NULL | NULL          | NULL | NULL    | NULL | NULL |     NULL | Impossible WHERE |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------+
1 row in set, 1 warning (0.00 sec)
```

File: pkg/types/compare.go (hunk 3 above)
Comment (Defined2014) [reply pkg/types/compare.go:94]: Just copy it from `pkg/expression/builtin_compare.go`. The same code can be used in three places.

File: pkg/planner/core/rule_partition_processor.go (hunk 2 above)
Comment (mjonss) [reply pkg/planner/core/rule_partition_processor.go:864]: Ah, you mean that it should return table dual (or no set of partitions), not an extra partition?

Comment (Defined2014) [reply pkg/planner/core/rule_partition_processor.go:864]: Yes.

File: pkg/types/compare.go (hunk 3 above)
Comment (mjonss) [reply pkg/types/compare.go:94]: OK, I just checked and it has only a minor performance difference, like a few percentage difference.
