### PR TITLE
*: fix data race for plan cache

### LINKED ISSUE #14723: Data race in TestPointGetPlanCache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
[2020-02-10T17:01:08.343Z] WARNING: DATA RACE

[2020-02-10T17:01:08.343Z] Write at 0x000005b10cb0 by goroutine 80:

[2020-02-10T17:01:08.343Z]   github.com/pingcap/tidb/planner/core_test.(*testPointGetSuite).TestPointGetPlanCache.func1()

[2020-02-10T17:01:08.343Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/point_get_plan_test.go:64 +0x4b

[2020-02-10T17:01:08.343Z]   github.com/pingcap/tidb/planner/core_test.(*testPointGetSuite).TestPointGetPlanCache()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/point_get_plan_test.go:176 +0x2071

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/planner/core_test.(*testPointGetSuite).TestPointGetPlanCache()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/point_get_plan_test.go:76 +0x295

[2020-02-10T17:01:08.344Z]   runtime.call32()

[2020-02-10T17:01:08.344Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-02-10T17:01:08.344Z]   reflect.Value.Call()

[2020-02-10T17:01:08.344Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-02-10T17:01:08.344Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:850 +0x9aa

[2020-02-10T17:01:08.344Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:739 +0x113

[2020-02-10T17:01:08.344Z] 

[2020-02-10T17:01:08.344Z] Previous read at 0x000005b10cb0 by goroutine 120:

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/session.CreateSessionWithDomain()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1729 +0x62d

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/session.createSessionWithDomainFunc.func1()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:864 +0x75

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/domain.(*Domain).Init.func1()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:654 +0x49

[2020-02-10T17:01:08.344Z]   github.com/ngaut/pools.(*ResourcePool).get()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/ngaut/pools@v0.0.0-20180318154953-b7bc8c42aac7/resource_pool.go:119 +0x1df

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*sessionPool).get()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/ngaut/pools@v0.0.0-20180318154953-b7bc8c42aac7/resource_pool.go:84 +0xd5

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*delRange).addDelRangeJob()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/delete_range.go:85 +0x81

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).deleteRange()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:266 +0x92

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).finishDDLJob()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:292 +0x680

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue.func1()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:403 +0x3c2

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/kv.RunInNewTxn()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/kv/txn.go:47 +0x110

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:376 +0x19b

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:376 +0x19b

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:376 +0x19b

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:376 +0x19b

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).start()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:140 +0x335

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:376 +0x19b

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).start()

[2020-02-10T17:01:08.344Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:140 +0x335

[2020-02-10T17:01:08.344Z]   github.com/pingcap/tidb/ddl.(*worker).handleDDLJobQueue()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:376 +0x19b

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/ddl.(*worker).start()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl_worker.go:140 +0x335

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/ddl.(*ddl).start.func1()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl.go:462 +0x71

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/util.WithRecovery()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:86 +0x68

[2020-02-10T17:01:08.345Z] 

[2020-02-10T17:01:08.345Z] Goroutine 80 (running) created at:

[2020-02-10T17:01:08.345Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:734 +0x4a3

[2020-02-10T17:01:08.345Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:832 +0x1b9

[2020-02-10T17:01:08.345Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:666 +0x13a

[2020-02-10T17:01:08.345Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:650 +0xae

[2020-02-10T17:01:08.345Z] 

[2020-02-10T17:01:08.345Z] Goroutine 120 (running) created at:

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/ddl.(*ddl).start()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl.go:461 +0xaef

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/ddl.newDDL()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl.go:411 +0xa56

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/domain.(*Domain).Init()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/ddl/ddl.go:370 +0x3e6

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.(*domainMap).Get.func1()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:78 +0x5bd

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/util.RunWithRetry()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:51 +0x90

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.(*domainMap).Get()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:70 +0x269

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.createSession()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1692 +0x7c

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.BootstrapSession()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1597 +0xfe

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:987 +0x3d9

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:985 +0x3ac

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:983 +0x37f

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:981 +0x352

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:979 +0x325

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:977 +0x2f8

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:975 +0x2cb

[2020-02-10T17:01:08.345Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.345Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:973 +0x29e

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:971 +0x271

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:969 +0x244

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:967 +0x217

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:965 +0x1ea

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:963 +0x1bd

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:962 +0x190

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:961 +0x163

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:960 +0x136

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:958 +0x109

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:956 +0xdc

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:954 +0x5b

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.bootstrap()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:305 +0x1a1

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.runInBootstrapSession()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1682 +0xe2

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/session.BootstrapSession()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1592 +0xad3

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/planner/core_test.newStoreWithBootstrap()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/cbo_test.go:565 +0xb7

[2020-02-10T17:01:08.346Z]   github.com/pingcap/tidb/planner/core_test.(*testPlanNormalize).SetUpSuite()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/plan_test.go:40 +0x47

[2020-02-10T17:01:08.346Z]   runtime.call32()

[2020-02-10T17:01:08.346Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-02-10T17:01:08.346Z]   reflect.Value.Call()

[2020-02-10T17:01:08.346Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-02-10T17:01:08.346Z]   github.com/pingcap/check.(*suiteRunner).runFixture.func1()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:799 +0x195

[2020-02-10T17:01:08.346Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-02-10T17:01:08.346Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20191216031241-8a5a85928f12/check.go:739 +0x113

[2020-02-10T17:01:08.346Z] ==================

```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve? 

Fix #14723 

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

### CODE REVIEW

File: executor/seqtest/prepared_test.go [hunk 1]
```diff
@@ -21,33 +21,31 @@ import (
...
+	"github.com/pingcap/tidb/session"
 	"github.com/pingcap/tidb/types"
+	"github.com/pingcap/tidb/util/kvcache"
 	"github.com/pingcap/tidb/util/testkit"
 	dto "github.com/prometheus/client_model/go"
 )
 
 func (s *seqTestSuite) TestPrepared(c *C) {
 	orgEnable := plannercore.PreparedPlanCacheEnabled()
-	orgCapacity := plannercore.PreparedPlanCacheCapacity
```
Comment (glorv) [inline executor/seqtest/prepared_test.go]: after this change, it seems many of the tests under `seqTestSuite` can be run in parallel now. Shall we reorganize `seqTestSuite` and `seqTestSuite1` to caange one of them to `Suite` so we can gain better performance

Comment (SunRunAway) [reply executor/seqtest/prepared_test.go]: but `orgEnable := plannercore.PreparedPlanCacheEnabled()` is still a global variable it changed, I don't know if it will affect other test cases.

Comment (glorv) [reply executor/seqtest/prepared_test.go]: ok, they should stay serial then
