### PR TITLE
*: handle region error for GetMvccByEncodedKey API(#47811)

### LINKED ISSUE #47807: unexpected error: There is no Write MVCC info for the schema version
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"]
- trigger a lot of load schema OPS.

img_v2_0f786210-a576-47d7-97e8-17d78c88324g

```
# rg "failed to get schema version"
tidb.log
9758:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9760:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9762:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9764:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
10034:[2023/10/19 18:11:28.173 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]

```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #47807

Problem Summary: pick #47811

### What is changed and how it works?

Before:

Related TIDB Log:

```log
# rg "failed to get schema version"
tidb.log
9758:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9760:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9762:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9764:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
10034:[2023/10/19 18:11:28.173 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
```

img_v2_0f786210-a576-47d7-97e8-17d78c88324g

This PR:

```log
# rg "failed to get schema version"

```

image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: store/helper/helper.go [hunk 1]
```diff
@@ -96,23 +96,36 @@ func NewHelper(store Storage) *Helper {
...
+		regionErr, err := kvResp.GetRegionError()
+		if err != nil {
+			return nil, errors.Trace(err)
+		}
+		if regionErr != nil {
+			if err = bo.Backoff(tikv.BoRegionMiss(), errors.New(regionErr.String())); err != nil {
+				return nil, err
+			}
+			continue
+		}
```
Comment (cfzjywxk) [inline store/helper/helper.go:126]: How about
```
if regionErr != nil {
  // For other region error and the fake region error, backoff because
  // there's something wrong.
  // For the real EpochNotMatch error, don't backoff.
  if regionErr.GetEpochNotMatch() == nil || locate.IsFakeRegionError(regionErr) {
    err = bo.Backoff(retry.BoRegionMiss, errors.New(regionErr.String()))
    if err != nil {
        return nil, err
  }
}
continue
```

File: store/helper/helper.go [hunk 2]
```diff
@@ -96,23 +96,36 @@ func NewHelper(store Storage) *Helper {
...
+		return kvResp.Resp.(*kvrpcpb.MvccGetByKeyResponse), nil
```
Comment (zyguan) [inline store/helper/helper.go:127]: Maybe also translate `resp.GetError()` to the returned error?

Comment (crazycs520) [reply store/helper/helper.go:127]: great, addressed in https://github.com/pingcap/tidb/pull/47811

File: store/helper/helper.go [hunk 3]
```diff
@@ -96,23 +96,36 @@ func NewHelper(store Storage) *Helper {
...
-	kvResp, err := h.Store.SendReq(tikv.NewBackofferWithVars(context.Background(), 500, nil), tikvReq, keyLocation.Region, time.Minute)
-	if err != nil {
-		logutil.BgLogger().Info("get MVCC by encoded key failed",
-			zap.Stringer("encodeKey", encodedKey),
-			zap.Reflect("region", keyLocation.Region),
-			zap.Stringer("keyLocation", keyLocation),
-			zap.Reflect("kvResp", kvResp),
-			zap.Error(err))
-		return nil, errors.Trace(err)
+		tikvReq := tikvrpc.NewRequest(tikvrpc.CmdMvccGetByKey, &kvrpcpb.MvccGetByKeyRequest{Key: encodedKey})
```
[the remark this answers is not in the document]
Comment (crazycs520) [reply store/helper/helper.go:106]: great, addressed in https://github.com/pingcap/tidb/pull/47811

**Review by zyguan — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
