### PR TITLE
planner, executor: return TableDual when tryFastPlan is promised to be false

### LINKED ISSUE #10448: unexpected behavior of `float_col = int_cnst`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
``` sql
CREATE TABLE `table10_int_autoinc` (
  `col_decimal_40_20_unsigned_key` decimal(40,20) unsigned DEFAULT NULL,
  `col_bigint_unsigned` bigint(20) unsigned DEFAULT NULL,
  `col_bigint_signed` bigint(20) DEFAULT NULL,
  `col_decimal_10_4_signed_key` decimal(10,4) DEFAULT NULL,
  `col_double_signed` double DEFAULT NULL,
  `col_decimal_6_3_signed` decimal(6,3) DEFAULT NULL,
  `col_float_unsigned` float unsigned DEFAULT NULL,
  `col_decimal_40_20_unsigned` decimal(40,20) unsigned DEFAULT NULL,
  `col_varchar_20_utf8` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `col_decimal_10_4_unsigned_key` decimal(10,4) unsigned DEFAULT NULL,
  `col_float_signed_key` float DEFAULT NULL,
  `col_decimal_10_4_unsigned` decimal(10,4) unsigned DEFAULT NULL,
  `col_decimal_10_4_signed` decimal(10,4) DEFAULT NULL,
  `col_char_20_utf8` char(20) CHARACTER SET utf8 DEFAULT NULL,
  `col_double_unsigned` double unsigned DEFAULT NULL,
  `col_char_20_utf8_key` char(20) CHARACTER SET utf8 DEFAULT NULL,
  `col_decimal_40_20_signed` decimal(40,20) DEFAULT NULL,
  `col_decimal_6_3_unsigned_key` decimal(6,3) unsigned DEFAULT NULL,
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_decimal_40_20_signed_key` decimal(40,20) DEFAULT NULL,
  `col_bigint_signed_key` bigint(20) DEFAULT NULL,
  `col_double_unsigned_key` double unsigned DEFAULT NULL,
  `col_decimal_6_3_signed_key` decimal(6,3) DEFAULT NULL,
  `col_decimal_6_3_unsigned` decimal(6,3) unsigned DEFAULT NULL,
  `col_bigint_unsigned_key` bigint(20) unsigned DEFAULT NULL,
  `col_varchar_20_utf8_key` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `col_float_signed` float DEFAULT NULL,
  `col_double_signed_key` double DEFAULT NULL,
  `col_float_unsigned_key` float unsigned DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_decimal_40_20_unsigned_key` (`col_decimal_40_20_unsigned_key`),
  KEY `col_decimal_10_4_signed_key` (`col_decimal_10_4_signed_key`),
  KEY `col_decimal_10_4_unsigned_key` (`col_decimal_10_4_unsigned_key`),
  KEY `col_float_signed_key` (`col_float_signed_key`),
  KEY `col_char_20_utf8_key` (`col_char_20_utf8_key`),
  KEY `col_decimal_6_3_unsigned_key` (`col_decimal_6_3_unsigned_key`),
  KEY `col_decimal_40_20_signed_key` (`col_decimal_40_20_signed_key`),
  KEY `col_bigint_signed_key` (`col_bigint_signed_key`),
  KEY `col_double_unsigned_key` (`col_double_unsigned_key`),
  KEY `col_decimal_6_3_signed_key` (`col_decimal_6_3_signed_key`),
  KEY `col_bigint_unsigned_key` (`col_bigint_unsigned_key`),
  KEY `col_varchar_20_utf8_key` (`col_varchar_20_utf8_key`),
  KEY `col_double_signed_key` (`col_double_signed_key`),
  KEY `col_float_unsigned_key` (`col_float_unsigned_key`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;
INSERT INTO `table10_int_autoinc` VALUES (18704.00000000000000000000,0,0,0.0000,0,NULL,0,0.00000000000000000000,'his',0.0000,0,116.0000,0.0000,'good',0,'come',-3810.00000000000000000000,999.999,1,NULL,-16250,NULL,0.000,0.000,0,'v',NULL,12883,0);
INSERT INTO `table10_int_autoinc` VALUES (0.00000000000000000000,0,0,0.0000,-25,0.000,0,30619.00000000000000000000,NULL,44.0000,-22364,0.0000,64.0000,'cmmxqxci',0,NULL,NULL,NULL,2,NULL,16284,31229,0.000,0.000,455145037341130752,'v',NULL,NULL,0);
INSERT INTO `table10_int_autoinc` VALUES (0.00000000000000000000,0,-710724316194406400,0.0000,NULL,0.000,0,NULL,NULL,0.0000,-8,36.0000,0.0000,'ccmmx',14,'x',0.00000000000000000000,0.000,3,NULL,47,0,-999.999,0.000,0,NULL,0,0,121);
INSERT INTO `table10_int_autoinc` VALUES (0.00000000000000000000,0,-1679842661009195008,22446.0000,-36,93.000,0,0.00000000000000000000,'well',23.0000,0,9499.0000,NULL,'he',0,'your',0.00000000000000000000,0.000,4,0.00000000000000000000,62,0,-999.999,NULL,5284129737789145088,'d',0,0,NULL);
INSERT INTO `table10_int_autoinc` VALUES (0.00000000000000000000,0,0,0.0000,23293,-999.999,0,0.00000000000000000000,'n',0.0000,0,0.0000,-97.0000,NULL,0,'on',NULL,NULL,5,0.00000000000000000000,-7922957644451545088,0,0.000,0.000,66,'fccmmxqxcilxqv',0,NULL,0);
INSERT INTO `table10_int_autoinc` VALUES (0.00000000000000000000,NULL,4617878467915022336,0.0000,0,-999.999,0,0.00000000000000000000,'xfccmmxqxcilx',0.0000,0,0.0000,0.0000,'l',0,'b',-9267.00000000000000000000,0.000,6,-67.00000000000000000000,24498,10405,0.000,0.000,0,'e',NULL,0,0);
INSERT INTO `table10_int_autoinc` VALUES (0.00000000000000000000,4625,0,12553.0000,0,0.000,0,0.00000000000000000000,'f',0.0000,0,0.0000,-28228.0000,'he',61,'got',NULL,0.000,7,0.00000000000000000000,NULL,43,-999.999,0.000,0,'all',0,0,4859);
INSERT INTO `table10_int_autoinc` VALUES (0.00000000000000000000,0,0,0.0000,0,0.000,0,0.00000000000000000000,'bxfccmmxqxcilx',0.0000,4098,21396.0000,25.0000,'why',21049,NULL,0.00000000000000000000,NULL,8,0.00000000000000000000,0,0,0.000,0.000,NULL,'rbxfccmmxqxcilx',NULL,-12239,107);
INSERT INTO `table10_int_autoinc` VALUES (NULL,0,-19,-124.0000,0,0.000,NULL,0.00000000000000000000,NULL,NULL,0,0.0000,0.0000,NULL,0,NULL,0.00000000000000000000,0.000,9,0.00000000000000000000,NULL,9028,0.000,0.000,615867249042915328,'y',0,NULL,0);
INSERT INTO `table10_int_autoinc` VALUES (73.00000000000000000000,0,0,0.0000,28122,0.000,0,0.00000000000000000000,'urbxfccmmxqxci',0.0000,0,0.0000,0.0000,'x',0,'as',0.00000000000000000000,0.000,10,NULL,NULL,0,0.000,13.000,0,'u',NULL,NULL,0);
SELECT a FROM (SELECT `pk` AS a, `col_float_unsigned_key` AS b FROM `table10_int_autoinc` ) tmp WHERE a = 18446744073709551615 ORDER BY a;
```

2. What did you expect to see?

no error happens

3. What did you see instead?

error happens

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

`373317f6a55fb01f656f247e1596ef789e15ba1c` in master branch

### LINKED ISSUE #10678: wrong result of `select * from t where signed_int8_pk=18446744073709551615`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
tidb> create table t(a int8 signed primary key);
Query OK, 0 rows affected (0.00 sec)

tidb> desc select * from t where a = 18446744073709551615;
ERROR 1690 (22003): constant 18446744073709551615 overflows bigint
```

2. What did you expect to see?
no error raised

3. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
``` sql
 Release Version: v3.0.0-rc.1-142-g6c31c9b50
Git Commit Hash: 6c31c9b503b1375097560f9960bebc44957bfb2e
Git Branch: master
UTC Build Time: 2019-06-03 07:47:44
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
Fix #10678 .
Before this commit:
``` sql
CREATE TABLE `t` (
  `pk` bigint(11) signed NOT NULL,
  PRIMARY KEY (`pk`)
);
tidb> SELECT `pk` FROM `t` WHERE `pk` = 18446744073709551615;
ERROR 1690 (22003): constant 18446744073709551615 overflows bigint

tidb> SELECT `pk` FROM `t` WHERE `pk` = 18446744073709551616;
Empty set (0.00 sec)
```

``` sql
drop table t;
CREATE TABLE `t` (
  `pk` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`pk`)
);

tidb> desc select * from t where pk = 18446744073709551615;
+-------------------+-------+------+----------------------------------------------------------------------------+
| id                | count | task | operator info                                                              |
+-------------------+-------+------+----------------------------------------------------------------------------+
| TableReader_6     | 0.33  | root | data:TableScan_5                                                           |
| └─TableScan_5     | 0.33  | cop  | table:t, range:[18446744073709551615,+inf], keep order:false, stats:pseudo |
+-------------------+-------+------+----------------------------------------------------------------------------+
2 rows in set (0.00 sec)



```
After this commit:
``` sql
CREATE TABLE `t` (
  `pk` bigint(11) signed NOT NULL,
  PRIMARY KEY (`pk`)
);
tidb> SELECT `pk` FROM `t` WHERE `pk` = 18446744073709551615;
Empty set (0.00 sec)
tidb> SELECT `pk` FROM `t` WHERE `pk` = 18446744073709551616;
Empty set (0.00 sec)
```

``` sql
drop table t;
CREATE TABLE `t` (
  `pk` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`pk`)
);
tidb> desc select * from t where pk = 18446744073709551615;
+-------------+-------+------+--------------------------------------+
| id          | count | task | operator info                        |
+-------------+-------+------+--------------------------------------+
| Point_Get_1 | 1.00  | root | table:t, handle:18446744073709551615 |
+-------------+-------+------+--------------------------------------+
1 row in set (0.00 sec)
```

### What is changed and how it works?
1. Return TableDual when the constant overflows the range of the primary key type .
2. Do not cache the prepared plan when the plan is TableDual.

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects

N/A

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -427,6 +442,11 @@ func tryUpdatePointPlan(ctx sessionctx.Context, updateStmt *ast.UpdateStmt) Plan
 	if checkFastPlanPrivilege(ctx, fastSelect, mysql.SelectPriv, mysql.UpdatePriv) != nil {
 		return nil
 	}
+	if fastSelect.IsTableDual {
+		return Update{
```
Comment (zz-jason) [inline planner/core/point_get_plan.go]: can we directly return a `TableDual` instead of `Update->TableDual`?

File: planner/core/point_get_plan.go [hunk 2]
```diff
@@ -186,19 +197,23 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt) *PointGetP
...
 		if err != nil {
+			if terror.ErrorEqual(types.ErrOverflow, err) {
+				p.IsTableDual = true
+				return p
+			}
 			return nil
 		}
-		p.UnsignedHandle = unsigned
+		p.Handle = intDatum.GetInt64()
+		p.UnsignedHandle = mysql.HasUnsignedFlag(fieldType.Flag)
```
Comment (zz-jason) [inline planner/core/point_get_plan.go]: `fieldType` can be nil pointer according to function `fieldType()`

Comment (XuHuaiyu) [reply planner/core/point_get_plan.go]: `fieldType` is the FieldType of PKHandle, it's can not be nil theoretically. https://github.com/pingcap/tidb/pull/10676/files#diff-f888b92d66ee2d478ea975b08cddaa6cR200
