### PR TITLE
statistics: batch write into stats cache when to init stats

### LINKED ISSUE #52339: TiDB may got bootstrap failed when stats initialization is concurrent and TiDB cpu core number is big
## Bug Report

Please answer these questions before submitting your issue. Thanks!

If we set `concurrently-init-stats = true` in config and the TiDB node has a lot CPU cores and the table num is also big.
We may hit the write throttle threshold of the [ristretto](https://github.com/dgraph-io/ristretto) cache we are using

### LINKED ISSUE #52346: When `force-init-stats` is true, auto analyze is alive before init stats finished
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2024/04/03 21:44:50.446 +00:00] [INFO] [refresher.go:120] ["No table to analyze"] [category=stats]
```
```
[2024/04/03 21:45:11.538 +00:00] [INFO] [domain.go:2292] ["init stats info time"] [lite=false] ["take time"=51.156816516s]
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #52339

Problem Summary:

### What changed and how does it work?

During the init stats, we will read many stats and write them into the stats cache. but if too many things need to be written, the cache will return fail because the channel in the internal will be full. so we need to do optimization on it.

1、avoid writing a cache when reading a record from the DB. 
   we read all the data about the statistics of the table, then write it into DB.
   and if fails, we will retry to write.
2、 Open too many concurrencies for the init stats.
   We set the upper bound and changed the default value of concurrency.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

test with 50k tables, it can work.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/initstats/load_stats.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func NewWorker(
 
 // LoadStats loads stats concurrently when to init stats
 func (ls *Worker) LoadStats(is infoschema.InfoSchema, cache statstypes.StatsCache, rc sqlexec.RecordSet) {
-	concurrency := runtime.GOMAXPROCS(0)
+	concurrency := max(2, runtime.GOMAXPROCS(0)/2)
```
Comment (hawkingrei) [inline pkg/statistics/handle/initstats/load_stats.go:52]: concurrency is too high before that customer will feel uneasy.

Comment (winoros) [inline pkg/statistics/handle/initstats/load_stats.go:52]: We set an upper bound for the concurrency? TiDB may be set up in a node with 64c, especially for OP cases?

File: pkg/statistics/handle/cache/statscacheinner.go [hunk 2]
```diff
@@ -92,16 +93,20 @@ func (sc *StatsCache) putCache(id int64, t *statistics.Table) bool {
...
+		if ok {
+			// update the maxTblStatsVer
+			for v := sc.maxTblStatsVer.Load(); v < t.Version; v = sc.maxTblStatsVer.Load() {
+				if sc.maxTblStatsVer.CompareAndSwap(v, t.Version) {
+					break
+				} // other goroutines have updated the sc.maxTblStatsVer, so we need to check again.
+			}
+			return
+		}
 		logutil.BgLogger().Warn("fail to put the stats cache", zap.Int64("id", id))
```
Comment (winoros) [inline pkg/statistics/handle/cache/statscacheinner.go:108]: Do we need to modify or remove this log?
It's possible that there're too many logs when startup

Comment (hawkingrei) [reply pkg/statistics/handle/cache/statscacheinner.go:108]: May add an mechanism to reduce the log

File: pkg/statistics/handle/initstats/load_stats.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/statistics/handle/initstats/load_stats.go]: I add max ```16``` concurrency limit.

File: pkg/statistics/handle/bootstrap.go [hunk 3]
```diff
@@ -549,7 +585,9 @@ func (*Handle) initStatsBuckets4Chunk(cache statstypes.StatsCache, iter *chunk.I
 			}
 		}
 		hist.AppendBucketWithNDV(&lower, &upper, row.GetInt64(3), row.GetInt64(4), row.GetInt64(7))
-		cache.Put(tableID, table) // put this table again since it is updated
+	}
+	if table != nil {
```
Comment (AilinKid) [inline pkg/statistics/handle/bootstrap.go:589]: when we arrive here, it could be the end of single chunk iter, rather than the end of all result chunks?
if yes, the possibility that same physical table id records could be exists in next chunk iter

Comment (hawkingrei) [reply pkg/statistics/handle/bootstrap.go:589]: It will check the table ID. if the table is not the same as the last one, it will be written into the stats cache.  this code is above here.

Comment (AilinKid) [reply pkg/statistics/handle/bootstrap.go:589]: okk

**Review by AilinKid — APPROVED** [review]

File: pkg/statistics/handle/initstats/load_stats_page.go [hunk 4]
```diff
@@ -46,7 +47,12 @@ func NewRangeWorker(dealFunc func(task Task) error) *RangeWorker {
 
 // LoadStats loads stats concurrently when to init stats
 func (ls *RangeWorker) LoadStats() {
-	concurrency := runtime.GOMAXPROCS(0)
+	var concurrency int
+	if config.GetGlobalConfig().Performance.ForceInitStats {
+		concurrency = min(max(2, runtime.GOMAXPROCS(0)-2), 16)
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/statistics/handle/initstats/load_stats_page.go]: updated

**Comment by hawkingrei** [comment]
/hold 

wait for @winoros's test result.

File: pkg/statistics/handle/initstats/load_stats.go [hunk 5]
```diff
@@ -15,72 +15,24 @@
...
-	"github.com/pingcap/tidb/pkg/statistics/handle/logutil"
-	statstypes "github.com/pingcap/tidb/pkg/statistics/handle/types"
-	"github.com/pingcap/tidb/pkg/util"
-	"github.com/pingcap/tidb/pkg/util/chunk"
-	"github.com/pingcap/tidb/pkg/util/sqlexec"
-	"go.uber.org/zap"
+	"github.com/pingcap/tidb/pkg/config"
 )
 
-// Worker is used to load stats concurrently.
```
Comment (hawkingrei) [inline pkg/statistics/handle/initstats/load_stats.go:32]: remove the concurrent init stats for loading stats meta.

**Comment by winoros** [comment]
tested against 170k tables, 9column+2index. Lite can be finished within 20s without any potential error. Non-lite can be finished within 18min without any potential error.

**Review by winoros — APPROVED** [review]
