### PR TITLE
session: release lock correctly for tidb to exit

### LINKED ISSUE #34123: After Ctrl+C tidb-server fail to exit
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start a tidb server with plugin enabled:

```
./bin/tidb-server -config config/config.toml.example -plugin-dir /home/genius/project/src/github.com/pingcap/enterprise-plugin/audit -plugin-load audit-1
```

Use mysql client to login to the server and execute some sql.

Then, Ctrl+C to kill tidb

### 2. What did you expect to see? (Required)

tidb server exit

### 3. What did you see instead (Required)

It doesn't exit, hang forever.

Collect the goroutine stack:

```
$ ps -ef|grep tidb-server
genius    115406   32320  0 13:53 pts/1    00:00:02 ./bin/tidb-server -config config/config.toml.example -plugin-dir /home/genius/project/src/github.com/pingcap/enterprise-plugin/audit -plugin-load audit-1
genius    118883   94845  0 14:13 pts/3    00:00:00 grep --color=auto tidb-server

$ kill -s SIGUSR1 115406
```

```
=== Got signal [user defined signal 1] to dump goroutine stack. ===
goroutine 569 [running]:
github.com/pingcap/tidb/util/signal.SetupSignalHandler.func1()
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:40 +0x9d
created by github.com/pingcap/tidb/util/signal.SetupSignalHandler
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:35 +0xb6

goroutine 1 [chan receive, 17 minutes]:
main.main()
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:221 +0x5d1

goroutine 33 [select, 17 minutes]:
google.golang.org/grpc.newClientStreamWithParams.func4()
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/stream.go:333 +0x92
created by google.golang.org/grpc.newClientStreamWithParams
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/stream.go:332 +0xb5e

goroutine 41 [select]:
github.com/tikv/pd/client.(*client).watchTSDeadline.func1({0x38602bf, 0x6}, 0xc00037c060)
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:538 +0xd2
created by github.com/tikv/pd/client.(*client).watchTSDeadline
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:536 +0x185

goroutine 9 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
	/home/genius/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/genius/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf

goroutine 10 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000c2d300)
	/home/genius/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	/home/genius/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 268 [select]:
github.com/pingcap/tidb/util/cpuprofile.(*parallelCPUProfiler).profilingLoop(0xc00012c180)
	/home/genius/project/src/github.com/pingcap/tidb/util/cpuprofile/cpuprofile.go:166 +0x105
github.com/pingcap/tidb/util.WithRecovery(0x0?, 0xc000248c00?)
	/home/genius/project/src/github.com/pingcap/tidb/util/misc.go:100 +0x53
created by github.com/pingcap/tidb/util/cpuprofile.(*parallelCPUProfiler).start
	/home/genius/project/src/github.com/pingcap/tidb/util/cpuprofile/cpuprofile.go:113 +0x165

goroutine 269 [chan receive]:
github.com/pingcap/tidb/util/systimemon.StartMonitor(0x3995e20, 0x39954d0, 0xc000a89bb0)
	/home/genius/project/src/github.com/pingcap/tidb/util/systimemon/systime_mon.go:32 +0x185
created by main.setupMetrics
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:715 +0x115

goroutine 270 [select, 17 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000dfe500)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:67 +0x245

goroutine 290 [select, 17 minutes]:
github.com/tikv/pd/client.(*client).handleDispatcher.func2()
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:731 +0x188
created by github.com/tikv/pd/client.(*client).handleDispatcher
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:719 +0x20f

goroutine 273 [select]:
google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc001038000)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1573 +0x165
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:359 +0x18dc

goroutine 274 [IO wait]:
internal/poll.runtime_pollWait(0x7f83e36fb138, 0x72)
	/home/genius/project/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00101e080?, 0xc001020000?, 0x0)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00101e080, {0xc001020000, 0x8000, 0x8000})
	/home/genius/project/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00101e080, {0xc001020000?, 0x36a6a60?, 0x200000001?})
	/home/genius/project/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00011a7b8, {0xc001020000?, 0x0?, 0x802010601?})
	/home/genius/project/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc000249860, {0xc0006917e0, 0x9, 0x18?})
	/home/genius/project/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x3db3380, 0xc000249860}, {0xc0006917e0, 0x9, 0x9}, 0x9)
	/home/genius/project/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/home/genius/project/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc0006917e0?, 0x9?, 0xf4f1b74eaf?}, {0x3db3380?, 0xc000249860?})
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0006917a0)
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc001038000)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1499 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:364 +0x191f

goroutine 275 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000dfe8c0, 0x1)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000249980)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x1f71

goroutine 276 [select]:
github.com/tikv/pd/client.(*baseClient).memberLoop(0xc000d9f8c0)
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/base_client.go:134 +0x13b
created by github.com/tikv/pd/client.(*baseClient).init
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/base_client.go:108 +0x1af

goroutine 277 [select]:
github.com/tikv/pd/client.(*tsoBatchController).fetchPendingRequests(0xc000dfe960, {0x3dd13c8, 0xc000db28c0}, 0x0)
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:214 +0xd1
github.com/tikv/pd/client.(*client).handleDispatcher(0xc000de0870, {0x3dd13c8?, 0xc000db28c0}, {0x38602bf, 0x6}, 0xc000dfe960)
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:766 +0x37c
created by github.com/tikv/pd/client.(*client).createTSODispatcher
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:685 +0x225

goroutine 278 [select]:
github.com/tikv/pd/client.(*client).tsLoop(0xc000de0870)
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:602 +0x199
created by github.com/tikv/pd/client.NewClientWithContext
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:408 +0x33c

goroutine 279 [select]:
github.com/tikv/pd/client.(*client).tsCancelLoop(0xc000de0870)
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:521 +0x1e5
created by github.com/tikv/pd/client.NewClientWithContext
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:409 +0x37f

goroutine 280 [select]:
github.com/tikv/pd/client.(*client).leaderCheckLoop(0xc000de0870)
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:473 +0x166
created by github.com/tikv/pd/client.NewClientWithContext
	/home/genius/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20220307081149-841fa61e9710/client.go:410 +0x3c5

goroutine 281 [select, 17 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000dfee10)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:67 +0x245

goroutine 283 [select]:
go.etcd.io/etcd/client/v3.(*Client).autoSync(0xc0000eefc0)
	/home/genius/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.2/client.go:199 +0xc5
created by go.etcd.io/etcd/client/v3.newClient
	/home/genius/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.2/client.go:444 +0xedc

goroutine 284 [select]:
github.com/tikv/client-go/v2/oracle/oracles.(*pdOracle).updateTS(0xc000d8d420, {0x3dd1400, 0xc0000540d0}, 0x0?)
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/oracle/oracles/pd.go:229 +0x125
created by github.com/tikv/client-go/v2/oracle/oracles.NewPdOracle
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/oracle/oracles/pd.go:77 +0x119

goroutine 285 [select]:
github.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop(0xc000472180, 0x0?)
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/internal/locate/region_cache.go:423 +0xd1
created by github.com/tikv/client-go/v2/internal/locate.NewRegionCache
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/internal/locate/region_cache.go:394 +0x2da

goroutine 286 [select]:
github.com/tikv/client-go/v2/tikv.(*KVStore).runSafePointChecker(0xc000933cc0)
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/tikv/kv.go:234 +0x12b
created by github.com/tikv/client-go/v2/tikv.NewKVStore
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/tikv/kv.go:189 +0x40a

goroutine 287 [select]:
github.com/tikv/client-go/v2/tikv.(*KVStore).safeTSUpdater(0xc000933cc0)
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/tikv/kv.go:521 +0x165
created by github.com/tikv/client-go/v2/tikv.NewKVStore
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/tikv/kv.go:190 +0x44a

goroutine 288 [select, 17 minutes]:
github.com/dgraph-io/ristretto.(*lfuPolicy).processItems(0xc000db2e40)
	/home/genius/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/policy.go:67 +0x91
created by github.com/dgraph-io/ristretto.newPolicy
	/home/genius/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/policy.go:51 +0x156

goroutine 306 [select]:
google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc0005d2000)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1573 +0x165
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:359 +0x18dc

goroutine 322 [IO wait]:
internal/poll.runtime_pollWait(0x7f83e36fb048, 0x72)
	/home/genius/project/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000f6e980?, 0xc0005b8000?, 0x0)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000f6e980, {0xc0005b8000, 0x8000, 0x8000})
	/home/genius/project/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000f6e980, {0xc0005b8000?, 0x36a6a60?, 0x200000001?})
	/home/genius/project/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0005b4000, {0xc0005b8000?, 0x0?, 0x800010601?})
	/home/genius/project/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc0005b0060, {0xc000160120, 0x9, 0x18?})
	/home/genius/project/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x3db3380, 0xc0005b0060}, {0xc000160120, 0x9, 0x9}, 0x9)
	/home/genius/project/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/home/genius/project/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc000160120?, 0x9?, 0xf4802ea37f?}, {0x3db3380?, 0xc0005b0060?})
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001600e0)
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0005d2000)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1499 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:364 +0x191f

goroutine 289 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000d8d570)
	/home/genius/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/cache.go:476 +0x18a
created by github.com/dgraph-io/ristretto.NewCache
	/home/genius/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/cache.go:213 +0x756

goroutine 323 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0005ac0a0, 0x1)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc001300180)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x1f71

goroutine 568 [syscall]:
os/signal.signal_recv()
	/home/genius/project/go/src/runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	/home/genius/project/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/home/genius/project/go/src/os/signal/signal.go:151 +0x2a

goroutine 1135 [select]:
google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc001039680)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1573 +0x165
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:359 +0x18dc

goroutine 1412 [select, 3 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00241e910)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:67 +0x245

goroutine 1417 [select, 3 minutes]:
github.com/tikv/client-go/v2/internal/client.(*batchConn).fetchAllPendingRequests(0xc002526b00, 0x80)
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/internal/client/client_batch.go:224 +0xb5
github.com/tikv/client-go/v2/internal/client.(*batchConn).batchSendLoop(0xc002526b00, {0x4, 0xa, 0x3, {0xc000f363d8, 0x4}, {0xc000f363f8, 0x3}, {0x100, 0x1000, ...}, ...})
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/internal/client/client_batch.go:315 +0x165
created by github.com/tikv/client-go/v2/internal/client.(*connArray).Init
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/internal/client/client.go:224 +0x105b

goroutine 1414 [select, 3 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00241f130)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:67 +0x245

goroutine 1416 [select]:
github.com/tikv/client-go/v2/tikvrpc.CheckStreamTimeoutLoop(0xc001e90cc0, 0xc000e3b140)
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/tikvrpc/tikvrpc.go:1116 +0x185
created by github.com/tikv/client-go/v2/internal/client.(*connArray).Init
	/home/genius/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/internal/client/client.go:222 +0xf7e

goroutine 1404 [IO wait]:
internal/poll.runtime_pollWait(0x7f83e36fae68, 0x72)
	/home/genius/project/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00064a180?, 0xc0005f8000?, 0x0)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00064a180, {0xc0005f8000, 0x8000, 0x8000})
	/home/genius/project/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00064a180, {0xc0005f8000?, 0x36a6a60?, 0x1?})
	/home/genius/project/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00106a700, {0xc0005f8000?, 0x10000012bf100?, 0x4e0000801?})
	/home/genius/project/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc001a41500, {0xc0001602e0, 0x9, 0xc000fd170c?})
	/home/genius/project/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x3db3380, 0xc001a41500}, {0xc0001602e0, 0x9, 0x9}, 0x9)
	/home/genius/project/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/home/genius/project/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc0001602e0?, 0x9?, 0xc00100ed70?}, {0x3db3380?, 0xc001a41500?})
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001602a0)
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc000f0c780)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1499 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:364 +0x191f

goroutine 1137 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc001ea2050, 0x1)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc001498060)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x1f71

goroutine 1136 [IO wait]:
internal/poll.runtime_pollWait(0x7f83e36fac88, 0x72)
	/home/genius/project/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0006e9100?, 0xc000888000?, 0x0)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0006e9100, {0xc000888000, 0x8000, 0x8000})
	/home/genius/project/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0006e9100, {0xc000888000?, 0x36a6a60?, 0x12e6a01?})
	/home/genius/project/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000dfc008, {0xc000888000?, 0x100c0000a8c00?, 0x4e0000801?})
	/home/genius/project/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc001498000, {0xc0006918c0, 0x9, 0xc001d3c5bc?})
	/home/genius/project/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x3db3380, 0xc001498000}, {0xc0006918c0, 0x9, 0x9}, 0x9)
	/home/genius/project/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/home/genius/project/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc0006918c0?, 0x9?, 0xc0000a8d70?}, {0x3db3380?, 0xc001498000?})
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000691880)
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc001039680)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1499 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:364 +0x191f

goroutine 1421 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00241f540, 0x1)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc001e91860)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x1f71

goroutine 1410 [select, 3 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00241e280)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:67 +0x245

goroutine 647 [semacquire, 17 minutes]:
sync.runtime_SemacquireMutex(0xc0003dfd20?, 0x6?, 0x5b595a0?)
	/home/genius/project/go/src/runtime/sema.go:71 +0x25
sync.(*RWMutex).Lock(0xc0003dfd78?)
	/home/genius/project/go/src/sync/rwmutex.go:144 +0x71
github.com/pingcap/tidb/session.(*domainMap).Delete(0x5b24580, {0x3ded190, 0xc000dff3b0})
	/home/genius/project/src/github.com/pingcap/tidb/session/tidb.go:102 +0x36
github.com/pingcap/tidb/session.(*domainMap).Get.func1.1()
	/home/genius/project/src/github.com/pingcap/tidb/session/tidb.go:81 +0x25
github.com/pingcap/tidb/domain.(*Domain).Close(0xc0004ac640)
	/home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:709 +0x178
main.closeDomainAndStorage({0x3ded190, 0xc000dff3b0}, 0xc00197e820?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:733 +0x35
main.cleanup(0xc00197e7e0?, {0x3ded190, 0xc000dff3b0}, 0x0?, 0x0?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:746 +0x8c
main.main.func1(0x0?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:215 +0x6f
github.com/pingcap/tidb/util/signal.SetupSignalHandler.func2()
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:56 +0x1e2
created by github.com/pingcap/tidb/util/signal.SetupSignalHandler
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:53 +0x19f

goroutine 621 [chan receive, 17 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc000fb95c0)
	/home/genius/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	/home/genius/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0x8e

goroutine 565 [chan receive, 17 minutes]:
github.com/pingcap/tidb/server.NewServer.func1()
	/home/genius/project/src/github.com/pingcap/tidb/server/server.go:213 +0x97
created by github.com/pingcap/tidb/server.NewServer
	/home/genius/project/src/github.com/pingcap/tidb/server/server.go:212 +0x38a

goroutine 1403 [select]:
google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc000f0c780)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1573 +0x165
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:359 +0x18dc

goroutine 646 [semacquire, 17 minutes]:
sync.runtime_SemacquireMutex(0xc0018cd801?, 0x0?, 0xc00250c140?)
	/home/genius/project/go/src/runtime/sema.go:71 +0x25
sync.(*RWMutex).RLock(...)
	/home/genius/project/go/src/sync/rwmutex.go:63
github.com/pingcap/tidb/session.(*domainMap).Get(0x5b24580, {0x3ded190, 0xc000dff3b0})
	/home/genius/project/src/github.com/pingcap/tidb/session/tidb.go:51 +0x67
github.com/pingcap/tidb/session.createSessionWithOpt({0x3ded190, 0xc000dff3b0}, 0x0)
	/home/genius/project/src/github.com/pingcap/tidb/session/session.go:2929 +0x59
github.com/pingcap/tidb/session.CreateSessionWithOpt({0x3ded190, 0xc000dff3b0}, 0x1?)
	/home/genius/project/src/github.com/pingcap/tidb/session/session.go:2673 +0x27
github.com/pingcap/tidb/session.CreateSession(...)
	/home/genius/project/src/github.com/pingcap/tidb/session/session.go:2667
github.com/pingcap/tidb/store/gcworker.createSession({0x3ded190, 0xc000dff3b0})
	/home/genius/project/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:238 +0x71
github.com/pingcap/tidb/store/gcworker.(*GCWorker).checkLeader(0xc0012ea870)
	/home/genius/project/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:1688 +0xa9
github.com/pingcap/tidb/store/gcworker.(*GCWorker).tick(0xc001eb9e60?, {0x3dd13c8, 0xc000c54880})
	/home/genius/project/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:279 +0x45
github.com/pingcap/tidb/store/gcworker.(*GCWorker).start(0xc0012ea870, {0x3dd13c8, 0xc000c54880}, 0xc001692900?)
	/home/genius/project/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:222 +0x327
created by github.com/pingcap/tidb/store/gcworker.(*GCWorker).Start
	/home/genius/project/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:116 +0xf8

goroutine 648 [select]:
github.com/pingcap/tidb/util/topsql/collector.(*SQLCPUCollector).collectSQLCPULoop(0xc000140b40)
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/collector/cpu.go:121 +0x1a5
created by github.com/pingcap/tidb/util/topsql/collector.(*SQLCPUCollector).Start
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/collector/cpu.go:83 +0xc5

goroutine 649 [select]:
github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).collectWorker(0xc000a87800)
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/reporter/reporter.go:175 +0x18e
created by github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/reporter/reporter.go:110 +0x6a

goroutine 650 [select]:
github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).reportWorker(0xc000a87800)
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/reporter/reporter.go:261 +0xfd
created by github.com/pingcap/tidb/util/topsql/reporter.(*RemoteTopSQLReporter).Start
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/reporter/reporter.go:111 +0xaa

goroutine 651 [select]:
github.com/pingcap/tidb/util/topsql/reporter.(*SingleTargetDataSink).run(0xc000140b90)
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/reporter/single_target.go:116 +0x12f
github.com/pingcap/tidb/util/topsql/reporter.(*SingleTargetDataSink).recoverRun(0xc000140b90)
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/reporter/single_target.go:98 +0x65
created by github.com/pingcap/tidb/util/topsql/reporter.(*SingleTargetDataSink).Start
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/reporter/single_target.go:82 +0x2ab

goroutine 652 [select]:
github.com/pingcap/tidb/util/topsql/stmtstats.(*aggregator).run(0xc00069d5f0)
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/stmtstats/aggregator.go:67 +0xff
created by github.com/pingcap/tidb/util/topsql/stmtstats.(*aggregator).start
	/home/genius/project/src/github.com/pingcap/tidb/util/topsql/stmtstats/aggregator.go:56 +0xca

goroutine 1419 [select]:
google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc001d7e000)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1573 +0x165
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:359 +0x18dc

goroutine 1420 [IO wait]:
internal/poll.runtime_pollWait(0x7f83e36faf58, 0x72)
	/home/genius/project/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc002526c00?, 0xc000924000?, 0x0)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc002526c00, {0xc000924000, 0x8000, 0x8000})
	/home/genius/project/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc002526c00, {0xc000924000?, 0x36a6a60?, 0x12aa601?})
	/home/genius/project/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc001242710, {0xc000924000?, 0x100c000953c00?, 0x4e0000801?})
	/home/genius/project/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc001e91800, {0xc0011c8120, 0x9, 0xc0011f9d9c?})
	/home/genius/project/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x3db3380, 0xc001e91800}, {0xc0011c8120, 0x9, 0x9}, 0x9)
	/home/genius/project/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/home/genius/project/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc0011c8120?, 0x9?, 0xc000953d70?}, {0x3db3380?, 0xc001e91800?})
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0011c80e0)
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc001d7e000)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1499 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:364 +0x191f

goroutine 1392 [select]:
google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc0019781e0)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1573 +0x165
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:359 +0x18dc

goroutine 1393 [IO wait]:
internal/poll.runtime_pollWait(0x7f83e36fad78, 0x72)
	/home/genius/project/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0026acf00?, 0xc0009e4000?, 0x0)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/genius/project/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0026acf00, {0xc0009e4000, 0x8000, 0x8000})
	/home/genius/project/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0026acf00, {0xc0009e4000?, 0x36a6a60?, 0x12aa601?})
	/home/genius/project/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00119c500, {0xc0009e4000?, 0x100c000723c00?, 0x4e0000801?})
	/home/genius/project/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc002445860, {0xc00026c660, 0x9, 0xc000fd198c?})
	/home/genius/project/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x3db3380, 0xc002445860}, {0xc00026c660, 0x9, 0x9}, 0x9)
	/home/genius/project/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/home/genius/project/go/src/io/io.go:350
golang.org/x/net/http2.readFrameHeader({0xc00026c660?, 0x9?, 0xc000723d70?}, {0x3db3380?, 0xc002445860?})
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00026c620)
	/home/genius/go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0019781e0)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:1499 +0x414
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:364 +0x191f

goroutine 1426 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc001aa29b0, 0x1)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0024458c0)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x1f71

goroutine 1376 [select, 3 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000dff2c0)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/balancer_conn_wrappers.go:67 +0x245

goroutine 1405 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc001a44370, 0x1)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc001a41560)
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:414 +0x65
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/genius/go/pkg/mod/google.golang.org/grpc@v1.44.0/internal/transport/http2_client.go:412 +0x1f71

=== Finished dumping goroutine stack. ===
```

As you can see, the tidb server is waiting on a mutex here after it receive the Ctrl+C exit signal:

```
goroutine 647 [semacquire, 17 minutes]:
sync.runtime_SemacquireMutex(0xc0003dfd20?, 0x6?, 0x5b595a0?)
	/home/genius/project/go/src/runtime/sema.go:71 +0x25
sync.(*RWMutex).Lock(0xc0003dfd78?)
	/home/genius/project/go/src/sync/rwmutex.go:144 +0x71
github.com/pingcap/tidb/session.(*domainMap).Delete(0x5b24580, {0x3ded190, 0xc000dff3b0})
	/home/genius/project/src/github.com/pingcap/tidb/session/tidb.go:102 +0x36
github.com/pingcap/tidb/session.(*domainMap).Get.func1.1()
	/home/genius/project/src/github.com/pingcap/tidb/session/tidb.go:81 +0x25
github.com/pingcap/tidb/domain.(*Domain).Close(0xc0004ac640)
	/home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:709 +0x178
main.closeDomainAndStorage({0x3ded190, 0xc000dff3b0}, 0xc00197e820?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:733 +0x35
main.cleanup(0xc00197e7e0?, {0x3ded190, 0xc000dff3b0}, 0x0?, 0x0?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:746 +0x8c
main.main.func1(0x0?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:215 +0x6f
github.com/pingcap/tidb/util/signal.SetupSignalHandler.func2()
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:56 +0x1e2
created by github.com/pingcap/tidb/util/signal.SetupSignalHandler
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:53 +0x19f
```

### 4. What is your TiDB version? (Required)

master 1355937bb39b2d6d58adc3bb83e6f74a068f1b5a

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #34123

Problem Summary:

### What is changed and how it works?

When `store == nil`, `domainMap.Get()` function would exit without release the read lock.
In the tidb exit code path, tidb can't obtain the lock and hang forever.
Ctrl+C can't make tidb exit.

```
goroutine 647 [semacquire, 17 minutes]:
sync.runtime_SemacquireMutex(0xc0003dfd20?, 0x6?, 0x5b595a0?)
	/home/genius/project/go/src/runtime/sema.go:71 +0x25
sync.(*RWMutex).Lock(0xc0003dfd78?)
	/home/genius/project/go/src/sync/rwmutex.go:144 +0x71
github.com/pingcap/tidb/session.(*domainMap).Delete(0x5b24580, {0x3ded190, 0xc000dff3b0})
	/home/genius/project/src/github.com/pingcap/tidb/session/tidb.go:102 +0x36
github.com/pingcap/tidb/session.(*domainMap).Get.func1.1()
	/home/genius/project/src/github.com/pingcap/tidb/session/tidb.go:81 +0x25
github.com/pingcap/tidb/domain.(*Domain).Close(0xc0004ac640)
	/home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:709 +0x178
main.closeDomainAndStorage({0x3ded190, 0xc000dff3b0}, 0xc00197e820?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:733 +0x35
main.cleanup(0xc00197e7e0?, {0x3ded190, 0xc000dff3b0}, 0x0?, 0x0?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:746 +0x8c
main.main.func1(0x0?)
	/home/genius/project/src/github.com/pingcap/tidb/tidb-server/main.go:215 +0x6f
github.com/pingcap/tidb/util/signal.SetupSignalHandler.func2()
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:56 +0x1e2
created by github.com/pingcap/tidb/util/signal.SetupSignalHandler
	/home/genius/project/src/github.com/pingcap/tidb/util/signal/signal_posix.go:53 +0x19f
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

After this fix, Ctrl+C can make tidb exit successfully.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug that Ctrl+C can't make the tidb-server exit, the bug is more likely to trigger when the enterprise plugin is used.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]

File: session/tidb.go [hunk 1]
```diff
@@ -53,6 +53,7 @@ func (dm *domainMap) Get(store kv.Storage) (d *domain.Domain, err error) {
 	// If this is the only domain instance, and the caller doesn't provide store.
 	if len(dm.domains) == 1 && store == nil {
 		for _, r := range dm.domains {
+			dm.mu.RUnlock()
```
Comment (zimulala) [inline session/tidb.go:56]: Or should we use `defer` in line52?

Comment (tangenta) [inline session/tidb.go:56]: How about using `defer dm.mu.RUnlock()` to make it less error prone?

**Review by tangenta — APPROVED** [review]

File: session/tidb.go (hunk 1 above)
Comment (hawkingrei) [reply session/tidb.go:56]: it is an optimization that will unlock in advance， don't unlock when to return. I think the front part can be a function that uses ```defer``` to unlock.
