### PR TITLE
expression: return upper bound for enum

### LINKED ISSUE #40855: query got error "Input byte is not a mysql type"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `17727daf-49e7-415c-83be-74c0ff7665a2` (
  `2dbd888c-7a13-402e-b45e-df771c58b8a2` set('p','htwl','rg','5naac','8gnba','5njhl','g2','8kl2','ga9v3','hm89u','v') DEFAULT 'p,5naac',
  `b10a5e29-8ec8-49f8-812a-eb6aca85081f` mediumint(9) NOT NULL DEFAULT '-4713386',
  `aecbdd04-400d-41e0-93fc-8fe949f3fe71` year(4) NOT NULL DEFAULT '1908',
  PRIMARY KEY (`b10a5e29-8ec8-49f8-812a-eb6aca85081f`,`aecbdd04-400d-41e0-93fc-8fe949f3fe71`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci;

CREATE TABLE `4e8a7745-94c7-49f7-b653-3e3e255ccf45` (
  `66856456-0550-4ac2-bc3d-484dae5d3655` set('rj','ouk3','y8o','k','vy4en','u1','7jj1','6','kf9ra','5p8g','nud') DEFAULT 'ouk3,y8o'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='db6bab11-18a8-49de-b4af-f237795b7db0';

CREATE TABLE `f93abdb0-c6af-472c-93ab-33432e8fd836` (
  `7c0cb0f1-4160-4718-be37-4dcc8bd62155` enum('8hrtq','7xs','jum1p','uyc','pj','vh913','db','i','5nle','si','9y') NOT NULL DEFAULT '7xs',
  `e1001878-7411-42aa-b22f-3419a944355c` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`7c0cb0f1-4160-4718-be37-4dcc8bd62155`,`e1001878-7411-42aa-b22f-3419a944355c`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `fe523fd1-7161-4d5a-b074-588119679bf1` (`7c0cb0f1-4160-4718-be37-4dcc8bd62155`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;

set @@sql_mode="";

INSERT INTO `17727daf-49e7-415c-83be-74c0ff7665a2` VALUES ('8kl2',-6698594,'1997'), ('8kl2',-6468423,'2004'), ('8kl2',-5661283,'1994'), ('8kl2',-5482103,'1908'), ('8kl2',-5146834,'2018'), ('rg',-4713386,'0000'), ('8kl2',-4713386,'1908'), ('5naac',-4713386,'1987'), ('v',-4713386,'2009'), ('8kl2',-4713386,'2018'), ('8kl2',-4713386,'2027'), ('8kl2',-4057715,'2017'), ('8kl2',-3427611,'0000'), ('8kl2',-3213207,'1975'), ('8kl2',-2282447,'1908'), ('8kl2',-2240520,'1975'), ('8kl2',-1890607,'2015'), ('p,5naac',-34879,'1974'), ('8kl2',0,'1985'), ('8kl2',219634,'2020'), ('8kl2',697507,'1991'), ('p,5naac',1298584,'1973'), ('p,5naac',1401179,'2030'), ('p,5naac',1507974,'1978'), ('p,5naac',2512413,'2035'), ('p,5naac',2740745,'2023'), ('8kl2',2779651,'1995'), ('8kl2',4098469,'1984'), ('8kl2',4660647,'2028'), ('p,5naac',5723619,'0000'), ('8kl2',6056113,'1979'), ('p',7039256,'2026');

INSERT INTO `f93abdb0-c6af-472c-93ab-33432e8fd836` VALUES ('',0), ('7xs',0), ('jum1p',1), ('pj',0), ('db',0), ('si',0);

select  *  from `17727daf-49e7-415c-83be-74c0ff7665a2` where not( `17727daf-49e7-415c-83be-74c0ff7665a2`.`2dbd888c-7a13-402e-b45e-df771c58b8a2` in ( select `66856456-0550-4ac2-bc3d-484dae5d3655` from `4e8a7745-94c7-49f7-b653-3e3e255ccf45` where not( `17727daf-49e7-415c-83be-74c0ff7665a2`.`2dbd888c-7a13-402e-b45e-df771c58b8a2` in ( select `66856456-0550-4ac2-bc3d-484dae5d3655` from `4e8a7745-94c7-49f7-b653-3e3e255ccf45` where `17727daf-49e7-415c-83be-74c0ff7665a2`.`aecbdd04-400d-41e0-93fc-8fe949f3fe71` in ( select `7c0cb0f1-4160-4718-be37-4dcc8bd62155` from `f93abdb0-c6af-472c-93ab-33432e8fd836`  ) ) )  ) );

```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
``` SQL
[err="Input byte is not a mysql type\ngithub.com/pingcap/tidb/executor.(*probeSideTupleFetcher).handleProbeSideFetcherPanic\n\t/Users/bba/pc/tidb/executor/join.go:391\ngithub.com/pingcap/tidb/util.(*WaitGroupWrapper).RunWithRecover.func1.1\n\t/Users/bba/pc/tidb/util/wait_group_wrapper.go:168\nruntime.gopanic\n\t/Users/bba/.gvm/gos/go1.19/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/types.IntergerSignedUpperBound\n\t/Users/bba/pc/tidb/types/convert.go:77\ngithub.com/pingcap/tidb/expression.(*compareFunctionClass).refineArgsByUnsignedFlag\n\t/Users/bba/pc/tidb/expression/builtin_compare.go:1705\ngithub.com/pingcap/tidb/expression.(*compareFunctionClass).refineArgs\n\t/Users/bba/pc/tidb/expression/builtin_compare.go:1672\ngithub.com/pingcap/tidb/expression.(*compareFunctionClass).getFunction\n\t/Users/bba/pc/tidb/expression/builtin_compare.go:1740\ngithub.com/pingcap/tidb/expression.newFunctionImpl\n\t/Users/bba/pc/tidb/expression/scalar_function.go:230\ngithub.com/pingcap/tidb/expression.NewFunction\n\t/Users/bba/pc/tidb/expression/scalar_function.go:261\ngithub.com/pingcap/tidb/expression.NewFunctionInternal\n\t/Users/bba/pc/tidb/expression/scalar_function.go:276\ngithub.com/pingcap/tidb/expression.SubstituteCorCol2Constant\n\t/Users/bba/pc/tidb/expression/util.go:570\ngithub.com/pingcap/tidb/planner/core.(*PhysicalTableScan).ResolveCorrelatedColumns\n\t/Users/bba/pc/tidb/planner/core/physical_plans.go:891\ngithub.com/pingcap/tidb/executor.(*TableReaderExecutor).Open\n\t/Users/bba/pc/tidb/executor/table_reader.go:172\ngithub.com/pingcap/tidb/executor.(*baseExecutor).Open\n\t/Users/bba/pc/tidb/executor/executor.go:202\ngithub.com/pingcap/tidb/executor.(*SelectionExec).Open\n\t/Users/bba/pc/tidb/executor/executor.go:1607\ngithub.com/pingcap/tidb/executor.(*baseExecutor).Open\n\t/Users/bba/pc/tidb/executor/executor.go:202\ngithub.com/pingcap/tidb/executor.(*HashJoinExec).Open\n\t/Users/bba/pc/tidb/executor/join.go:196\ngithub.com/pingcap/tidb/executor.(*baseExecutor).Open\n\t/Users/bba/pc/tidb/executor/executor.go:202\ngithub.com/pingcap/tidb/executor.(*SelectionExec).Open\n\t/Users/bba/pc/tidb/executor/executor.go:1607\ngithub.com/pingcap/tidb/executor.(*baseExecutor).Open\n\t/Users/bba/pc/tidb/executor/executor.go:202\ngithub.com/pingcap/tidb/executor.(*HashJoinExec).Open\n\t/Users/bba/pc/tidb/executor/join.go:196\ngithub.com/pingcap/tidb/executor.(*baseExecutor).Open\n\t/Users/bba/pc/tidb/executor/executor.go:202\ngithub.com/pingcap/tidb/executor.(*SelectionExec).Open\n\t/Users/bba/pc/tidb/executor/executor.go:1607\ngithub.com/pingcap/tidb/executor.(*NestedLoopApplyExec).fetchAllInners\n\t/Users/bba/pc/tidb/executor/join.go:1397\ngithub.com/pingcap/tidb/executor.(*NestedLoopApplyExec).Next\n\t/Users/bba/pc/tidb/executor/join.go:1464\ngithub.com/pingcap/tidb/executor.Next\n\t/Users/bba/pc/tidb/executor/executor.go:328\ngithub.com/pingcap/tidb/executor.(*SelectionExec).Next\n\t/Users/bba/pc/tidb/executor/executor.go:1663\ngithub.com/pingcap/tidb/executor.Next\n\t/Users/bba/pc/tidb/executor/executor.go:328\ngithub.com/pingcap/tidb/executor.(*probeSideTupleFetcher).fetchProbeSideChunks\n\t/Users/bba/pc/tidb/executor/join.go:245\ngithub.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndProbeHashTable.func1\n\t/Users/bba/pc/tidb/executor/join.go:373\ngithub.com/pingcap/tidb/util.(*WaitGroupWrapper).RunWithRecover.func1\n\t/Users/bba/pc/tidb/util/wait_group_wrapper.go:172\nruntime.goexit\n\t/Users/bba/.gvm/gos/go1.19/src/runtime
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #40855

Problem Summary:

The `enum` can also be evaluated to an integer, so we should return the upperbound (but not panic directly) here. This error is hard to find, because the enum has to be attached with the `mysql.EnumSetAsIntFlag`, which usually happens after this function is called. However, if the user compares the enum with a correlated column, during the `SubstituteCorCol2Constant`, the flag will be attached to the field type before this function is called.

This PR also has some connection with #21042

### What is changed and how it works?

Return 65536 as the upperbound of the enum.

This PR also makes the error message clearer.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that comparing integer value with enum in subquery will return "Input byte is not a mysql type"
```

### CODE REVIEW

File: types/convert.go [hunk 1]
```diff
@@ -73,8 +73,12 @@ func IntergerSignedUpperBound(intType byte) int64 {
 		return math.MaxInt32
 	case mysql.TypeLonglong:
 		return math.MaxInt64
+	case mysql.TypeEnum:
+		// enum can have at most 65535 distinct elements
+		// it would be better to use len(FieldType.GetElems()), but we only have a byte type here
+		return 65535
```
Comment (wjhuang2016) [inline types/convert.go:79]: It is MaxUint64 in IntergerUnsignedUpperBound. Besides, do we need to cover IntergerSignedLowerBound?

Comment (YangKeao) [reply types/convert.go:81]: Nice catch. I also modify it to 65536. I think 65536 is a more reasonable value.

> Besides, do we need to cover IntergerSignedLowerBound?

It would be better to set it to zero :thinking:, though I don't know whether it's reachable.

**Review by wjhuang2016 — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold 

CI is too busy.

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
unhold
