### PR TITLE
util: build right range when where stmt only have string column.

### LINKED ISSUE #16190: Failed Integration Push Down Test
### 1. What did you do?
I got Failed Integration Push Down Test failed when I merged my PR and ran `tidb_ghpr_integration_copr_test`.
It seems that no relevant codes are modified in my [PR](https://github.com/pingcap/tidb/pull/15941)
This error logs are listed [here](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/3315/pipeline)

### 2. What did you expect to see?

No error

### 3. What did you see instead?

Error logs shown before.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
tidb/master

### LINKED ISSUE #16505: Error 1690: DOUBLE value is out of range
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
CI task `integration-copr-test` failed
data: https://github.com/tikv/copr-test/blob/master/push-down-test/prepare/0_data.sql

### 2. What did you expect to see?
Test pass

### 3. What did you see instead?
```
[2020-04-16T07:39:40.548Z] Test case: sql/randgen/5_math_2.sql
[2020-04-16T07:39:40.548Z] Statement: #1665 -  SELECT EXP( `col_set` ) AS field1, `col_timestamp_key` % '2013-03-22' AS field2, DEGREES( '15:00:34.037137' ) AS field3 FROM `table1_int_autoinc` WHERE `col_binary_8_key` AND '2006-04-04 16:25:30.047980' /* QNO 1670 CON_ID 204 */ ;
[2020-04-16T07:39:40.548Z] NoPushDown Output: 
[2020-04-16T07:39:40.548Z] field1	field2	field3
[2020-04-16T07:39:40.548Z] 
[2020-04-16T07:39:40.548Z] 
[2020-04-16T07:39:40.548Z] WithPushDown Output: 
[2020-04-16T07:39:40.548Z] Error 1690: DOUBLE value is out of range in 'exp(cast(push_down_test_db.table1_int_autoinc.col_set, double BINARY))'
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/3851/pipeline/

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #16505  , close #16190  

Problem Summary: TableIndexScan's result is different from TableFullScan and Selection.

### What is changed and how it works?

What's Changed: If the where stmt only have String column, it shouldn't be one of accessCondition to build access range. Because we should convert the string to float to check it is ture/false.

How it Works: However, revert #16135  that only cover some cases. The pr can cover all situations.

### Related changes

- Need to cherry-pick to the release branch 2.1,3.0,3.1,4.0

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
Fix the wrong result when where stmt only have string column.

### CODE REVIEW

**Comment by wshwsh12** [comment]
@winoros @eurekaka  PTAL

File: util/ranger/checker.go [hunk 1]
```diff
@@ -32,6 +32,11 @@ func (c *conditionChecker) check(condition expression.Expression) bool {
 	case *expression.ScalarFunction:
 		return c.checkScalarFunction(x)
 	case *expression.Column:
+		if s, ok := condition.(*expression.Column); ok {
```
Comment (eurekaka) [inline util/ranger/checker.go:35]: The condition must be `Column` when coming here?

File: util/ranger/checker.go [hunk 2]
```diff
@@ -32,6 +32,11 @@ func (c *conditionChecker) check(condition expression.Expression) bool {
...
+			if s.RetType.EvalType() == types.ETString {
+				return false
```
Comment (eurekaka) [inline util/ranger/checker.go:37]: Then we cannot use index for this kind of filter? would it cause performance regression?

Comment (wshwsh12) [reply util/ranger/checker.go:37]: Yes.  Maybe it cause performance regression, but It is a correctness question.   In Mysql, the range is empty also. If we use index, it can only filter `null` and `''`.
