### PR TITLE
expression: fix wrong warning when comparing binary column

### LINKED ISSUE #17824: Wrong warning when compaing binary column
## Description
## Bug Report


### 1. Minimal reproduce step (Required)
````
mysql> show create table t7;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                      |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t7    | CREATE TABLE `t7` (
  `col0` binary(63) DEFAULT NULL,
  `col1` datetime DEFAULT NULL,
  `col2` bigint(20) DEFAULT NULL,
  `col3` varchar(300) DEFAULT NULL,
  `col4` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

insert into t7 values ('1101001', '1000-01-02 00:00:00', '9223372036854775807', '1ee46528-2b9a-4b3f-9042-8c5d061c2f26', '-614.0876077308573');

mysql> select binary col0 = 1101001 from t7;  
+-----------------------+
| binary col0 = 1101001 |
+-----------------------+
|                     1 |
+-----------------------+
1 row in set, 1 warning (0.00 sec)

````

### 2. What did you expect to see? (Required)

No warnings should be displayed.

````
-- MySQL 5.7
mysql> select binary col0 = 1101001 from t7;  
+-----------------------+
| binary col0 = 1101001 |
+-----------------------+
|                     1 |
+-----------------------+
1 row in set (0.01 sec)

-- MySQL 8
mysql> select binary col0 = 1101001 from t7;
+-----------------------+
| binary col0 = 1101001 |
+-----------------------+
|                     1 |
+-----------------------+
1 row in set (0.00 sec)
````

### 3. What did you see instead (Required)

````
1 row in set, 1 warning (0.00 sec)
````

### 4. Affected version (Required)

````
commit 8369ffd500f3fb235d8b584ac4298b2e59d8db55 (HEAD -> master, origin/master, origin/HEAD)
Author: Soup <ilovesoup@gmail.com>
Date:   Tue May 26 15:38:29 2020 +0800
````

### 5. Root Cause Analysis

<!-- should be filled by the investigator before it's closed -->




## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by yufan022**
### What problem does this PR solve?

Issue Number: fix #17824 

Problem Summary:

### What is changed and how it works?

optimize warning when comparing binary column.

What's Changed: add condition.

How it Works:

when char end with  '\u0000' , meaning  it was  converted from  binary .
making string length can be equals validLen variable.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- fix binary column warnings

### CODE REVIEW

File: types/convert.go [hunk 1]
```diff
@@ -654,6 +654,9 @@ func getValidFloatPrefix(sc *stmtctx.StatementContext, s string, isFuncCast bool
 				break
 			}
 			eIdx = i
+		} else if c == '\u0000' {
+			s = s[:validLen]
```
Comment (ichn-hu) [inline types/convert.go:658]: This line can be removed, you only need to break from this loop, because line 667 will cut `s`.

**Review by ichn-hu — CHANGES_REQUESTED** [review]
Rest LGTM

File: types/convert.go (hunk 1 above)
Comment (yufan022) [reply types/convert.go:658]: > This line can be removed, you only need to break from this loop, because line 667 will cut `s`.

Variable `s` need reset, because line 671 compare `validLen` and `len(s)`.
Or I can remove line 658 and modify line 671 to `validLen != len(valid)`.

**Review by ichn-hu — APPROVED** [review]
LGTM

File: types/convert.go (hunk 1 above)
Comment (ichn-hu) [reply types/convert.go:658]: I think both are acceptable then. It would be better if you could make the refactorization.

Comment (yufan022) [reply types/convert.go:658]: if c < '0' || c > '9'

Comment (ichn-hu) [reply types/convert.go:658]: > It will lead to another question. If we modify `validLen != len(valid)` ，when `c <'0' || c> '9'` ， then no exception will be thrown.
> I think it's right now.

sure, then let's just keep it this way.

**Comment by rebelice** [comment]
LGTM

**Comment by yufan022** [comment]
> There is no reward for this challenge pull request, so you can request a reward from @SunRunAway.
> 
> More

Can I get [high-performance] score？ @SunRunAway

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
