### PR TITLE
expression: fix index out of range for `AES_DECRYPT`

### LINKED ISSUE #43063: Index out of range [1] with length 1 when using AES_DECRYPT
## Bug Report
Index out of range [1] with length 1 when using AES_DECRYPT

### 1. Minimal reproduce step (Required)
```
create table test (name1 varchar(64),name2 varchar(64));
insert into test values('99FAFD8059A44BC14BCCC70154AC00F3','99FAFD8059A44BC14BCCC70154AC00F3');
SELECT * FROM test WHERE CAST(AES_DECRYPT(UNHEX(name1), 'r��Lu-t�AS�h)%R`') AS CHAR) = '00' AND CAST(AES_DECRYPT(UNHEX(name2), 'r��`') AS CHAR) = '1';
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
github.com/pingcap/tidb/executor.(*recordSet).Next.func1
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:149
runtime.gopanic
\t/usr/local/go/src/runtime/panic.go:884
runtime.goPanicIndex
\t/usr/local/go/src/runtime/panic.go:113
github.com/pingcap/tidb/util/chunk.(*Column).GetBytes
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/chunk/column.go:588
github.com/pingcap/tidb/expression.(*builtinAesDecryptSig).vecEvalString
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/builtin_encryption_vec.go:73
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalString
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/scalar_function.go:58
github.com/pingcap/tidb/expression.(*builtinInternalFromBinarySig).vecEvalString
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/builtin_convert_charset.go:198
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalString
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/scalar_function.go:58
github.com/pingcap/tidb/expression.(*builtinCastStringAsStringSig).vecEvalString
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/builtin_cast_vec.go:1895
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalString
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/scalar_function.go:58
github.com/pingcap/tidb/expression.(*builtinEQStringSig).vecEvalInt
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/builtin_compare_vec_generated.go:1003
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/scalar_function.go:48
github.com/pingcap/tidb/expression.(*builtinLogicOrSig).vecEvalInt
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/builtin_op_vec.go:77
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/scalar_function.go:48
github.com/pingcap/tidb/expression.EvalExpr
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/expression.go:574
github.com/pingcap/tidb/expression.VecEvalBool
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/expression.go:369

```
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #43063

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix index out of range for `AES_DECRYPT`
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

File: expression/builtin_encryption_vec.go [hunk 1]
```diff
@@ -43,6 +43,11 @@ func (b *builtinAesDecryptSig) vectorized() bool {
 
 func (b *builtinAesDecryptSig) vecEvalString(input *chunk.Chunk, result *chunk.Column) error {
 	n := input.NumRows()
+	if n == 0 {
```
Comment (guo-shaoge) [inline expression/builtin_encryption_vec.go:46]: Maybe add a comment to explain why add check `n == 0`, because normally we handle `n == 0` in the `for loop` implicitly .

**Review by guo-shaoge — APPROVED** [review]
