### PR TITLE
planner: fix `PointGetPlan.PrunePartitions` function works with non-binary collate

### LINKED ISSUE #61965: Report `too many partitions matching for PointGetPlan` for range partition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t5f0caf27` (
  `col_95` char(181) COLLATE gbk_bin NOT NULL DEFAULT 'SaMKHTyg+nlID-X3Y',
  PRIMARY KEY (`col_95`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_bin
PARTITION BY RANGE COLUMNS(`col_95`)
(PARTITION `p0` VALUES LESS THAN ('6)nvX^uj0UGxqX'),
 PARTITION `p1` VALUES LESS THAN ('BHSluf6'),
 PARTITION `p2` VALUES LESS THAN (MAXVALUE));

select t5f0caf27.col_95 as r0 from t5f0caf27 where t5f0caf27.col_95 between 'Dyw=*7nigCMh' and 'Im0*7sZ' or t5f0caf27.col_95 in ( '58y-j)84-&Y*' ,'WNe(rS5uwmvIvFnHw' ,'j9FsMawX5uBro%$p' ,'C(#EQm@J' ) group by t5f0caf27.col_95  having t5f0caf27.col_95 between '%^2' and '38ABfC-' or t5f0caf27.col_95 between 'eKCAE$d2x_hxscj' and 'zcw35^ATEEp1md=L';
```

### 2. What did you expect to see? (Required)

PointGet plan with access partition p2.

### 3. What did you see instead (Required)

report error

### 4. What is your TiDB version? (Required)

caused by #59918, affects v8.5.2 and later.

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #61965, close https://github.com/pingcap/tidb/issues/59827

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/point_get_plan.go [hunk 1]
```diff
@@ -341,67 +342,6 @@ func (p *PointGetPlan) LoadTableStats(ctx sessionctx.Context) {
...
 }
 
-// needsPartitionPruning checks if IndexValues can be used by GetPartitionIdxByRow() or if they have already been
-// converted to SortKey and would need GetPartitionIdxByRow() to be refactored to work, since it will unconditionally
-// convert it again.
-// Returns:
-// Matching partition
-// if done Partition pruning (else not needed, can use GetPartitionIdxByRow() instead)
-// error
-// TODO: Also supporting BatchPointGet? Problem is that partition ID must be mapped to handle/IndexValue.
```
Comment (hawkingrei) [inline pkg/planner/core/point_get_plan.go:351]: Has this TODO been completed?

File: pkg/planner/core/point_get_plan.go [hunk 2]
```diff
@@ -446,32 +385,32 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
 	if p.HandleConstant == nil && len(p.IndexValues) > 0 {
-		partColsNames := pt.Meta().Partition.Columns
-		if len(partColsNames) > 0 {
-			partIdx, done, err := needsPartitionPruning(sctx, p.TblInfo, pt, p.dbName, p.IndexInfo, p.IdxCols, p.IndexValues, p.AccessConditions, p.PartitionNames)
-			if table.ErrNoPartitionForGivenValue.Equal(err) {
-				err = nil
-				partIdx = nil
+		hasNonBinaryCollate := false
+		for _, col := range p.IdxCols {
+			switch col.GetType(sctx.GetExprCtx().GetEvalCtx()).GetCollate() {
```
Comment (hawkingrei) [inline pkg/planner/core/point_get_plan.go]: We can move this ```sctx.GetExprCtx().GetEvalCtx()```  outside the for-loop.

File: pkg/planner/core/point_get_plan.go (hunk 1 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go:351]: No, this function is useless and the result is different with the result from planner part. So I remove it.

File: pkg/planner/core/point_get_plan.go (hunk 2 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go]: Done

**Review by hawkingrei — APPROVED** [review]

File: pkg/planner/core/point_get_plan.go [hunk 3]
```diff
@@ -419,7 +359,6 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
 			if def.Name.L == p.PartitionNames[0].L {
 				idx := i
 				p.PartitionIdx = &idx
-				break
```
Comment (AilinKid) [inline pkg/planner/core/point_get_plan.go]: why should we remove this break, cuz i think only one partition can be matched?

File: pkg/planner/core/point_get_plan.go [hunk 4]
```diff
@@ -446,32 +385,34 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
-			if table.ErrNoPartitionForGivenValue.Equal(err) {
-				err = nil
-				partIdx = nil
+		hasNonBinaryCollate := false
+		indexValues := p.IndexValues
+
+		evalCtx := sctx.GetExprCtx().GetEvalCtx()
+		for _, col := range p.IdxCols {
+			switch col.GetType(evalCtx).GetCollate() {
+			case "utf8mb4_bin", "binary", "ascii_bin", "latin1_bin", "utf8_bin", "utf8mb4_0900_bin":
```
Comment (AilinKid) [inline pkg/planner/core/point_get_plan.go]: we can use the defined string: CollationUTF8MB4 and so on

File: pkg/planner/core/point_get_plan.go [hunk 5]
```diff
@@ -446,32 +385,34 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
+			default:
+				hasNonBinaryCollate = true
 			}
+			if hasNonBinaryCollate {
+				break
+			}
+		}
+		// If a non-binary collation is used, the values in `p.IndexValues` are sort keys and cannot be used for partition pruning.
+		if hasNonBinaryCollate {
+			r, err := ranger.DetachCondAndBuildRange(sctx.GetRangerCtx(), p.AccessConditions, p.IdxCols, p.IdxColLens, sctx.GetSessionVars().RangeMaxSize, false, true)
```
Comment (AilinKid) [inline pkg/planner/core/point_get_plan.go]: i saw a similar function named: DetachCondAndBuildRangeForPartition, which the last bool is fixed as false, i think since this func is also amended for partition usage, maybe we can use the same portal and adjust the param?

File: pkg/planner/core/point_get_plan.go [hunk 6]
```diff
@@ -446,32 +385,34 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
-					return true, nil
-				}
-				return false, errors.Errorf("too many partitions matching for PointGetPlan")
+			if len(r.Ranges) != 1 || !r.Ranges[0].IsPoint(sctx.GetRangerCtx()) {
+				return false, errors.Errorf("internal error, build ranger for PointGet failed")
 			}
+			indexValues = r.Ranges[0].LowVal
 		}
 		for i := range p.IndexInfo.Columns {
 			// TODO: Skip copying non-partitioning columns?
```
Comment (AilinKid) [inline pkg/planner/core/point_get_plan.go:410]: can this todo be solved by the way

File: pkg/planner/core/point_get_plan.go (hunk 5 above)
Comment (AilinKid) [reply pkg/planner/core/point_get_plan.go]: with that we don't need to export DetachCondAndBuildRange

**Review by AilinKid — COMMENTED** [review]
rest LGTM

File: pkg/planner/core/point_get_plan.go (hunk 6 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go:410]: No

File: pkg/planner/core/point_get_plan.go (hunk 4 above)
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go]: Are there not `isBinaryCollation()` or similar function that can be used?

Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go]: The sortKey for `gbk_bin` and `gb18030_bin` is different with original string

Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go]: It's the default collation for utf8mb4, maybe it will changed in some day.

File: pkg/planner/core/point_get_plan.go (hunk 3 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go]: It'a a mistake.

File: pkg/planner/core/point_get_plan.go [hunk 7]
```diff
@@ -446,32 +386,34 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
-				return false, err
-			}
-			if done {
-				if len(partIdx) == 1 {
-					p.PartitionIdx = &partIdx[0]
-					return false, nil
+		indexValues := p.IndexValues
+
+		evalCtx := sctx.GetExprCtx().GetEvalCtx()
+		binaryCollations := map[string]struct{}{
```
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go]: Would it be possible to use `CompatibleCollate("utf8mb4_bin", col.GetType(evalCtx).GetCollate())` or something else, to avoid having yet another place to maintain the list of binary collations?

Comment (mjonss) [reply pkg/planner/core/point_get_plan.go]: Ah, there is a `IsBinCollation()`, please use that :)

File: pkg/planner/core/point_get_plan.go (hunk 4 above)
Comment (mjonss) [reply pkg/planner/core/point_get_plan.go]: Oh, so binary collations can still use a different sortKey? Then we should have a collation utility function saying if a sort key is needed or not?

File: pkg/planner/core/point_get_plan.go (hunk 7 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go]: Done, PTAL

File: pkg/planner/core/point_get_plan.go [hunk 8]
```diff
@@ -446,32 +386,25 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
+				// If a non-binary collation is used, the values in `p.IndexValues` are sort keys and cannot be used for partition pruning.
+				r, err := ranger.DetachCondAndBuildRangeForPartition(sctx.GetRangerCtx(), p.AccessConditions, p.IdxCols, p.IdxColLens, sctx.GetSessionVars().RangeMaxSize)
+				if err != nil {
+					return false, err
 				}
-				if len(partIdx) == 0 {
-					idx := -1
-					p.PartitionIdx = &idx
-					return true, nil
+				if len(r.Ranges) != 1 || !r.Ranges[0].IsPoint(sctx.GetRangerCtx()) {
```
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go:402]: Please add a test where `len(r.Ranges) == 0`. Like RANGE partition without MAXVALUE and a condition for value greater than last partition.
I would assume it should `return true, nil` in such case and use table DUAL.

File: pkg/planner/core/point_get_plan.go [hunk 9]
```diff
@@ -446,32 +386,25 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) (bool, error) {
...
-			if done {
-				if len(partIdx) == 1 {
-					p.PartitionIdx = &partIdx[0]
-					return false, nil
+		indexValues := p.IndexValues
+		evalCtx := sctx.GetExprCtx().GetEvalCtx()
+		for _, col := range p.IdxCols {
+			if !collate.IsBinCollation(col.GetType(evalCtx).GetCollate()) {
+				// If a non-binary collation is used, the values in `p.IndexValues` are sort keys and cannot be used for partition pruning.
+				r, err := ranger.DetachCondAndBuildRangeForPartition(sctx.GetRangerCtx(), p.AccessConditions, p.IdxCols, p.IdxColLens, sctx.GetSessionVars().RangeMaxSize)
```
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go:398]: Why are we looping on `p.IdxCols` and doing this for the full conditions, and all columns (`p.IdxCols`)?
Should we also check if the column is part of the partitioning expression and then check if binary collation?

File: tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result [hunk 10]
```diff
@@ -928,3 +928,19 @@ Point_Get	1.00	root	table:t, partition:p4, index:idx_3(col_4)
 select * from t where col_4 in ( 'u^D92@_4' ,null );
 col_4
 u^D92@_4
+drop table if exists t;
+CREATE TABLE `t` (
+`col_95` char(181) COLLATE gbk_bin NOT NULL DEFAULT 'SaMKHTyg+nlID-X3Y',
+PRIMARY KEY (`col_95`) /*T![clustered_index] CLUSTERED */
+) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_bin
+PARTITION BY RANGE COLUMNS(`col_95`)
```
Comment (mjonss) [inline tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result:936]: Do we need to test other partitioning schemes as well? Like RANGE COLUMNS, LIST [COLUMNS] and KEY?

File: pkg/planner/core/point_get_plan.go (hunk 8 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go:402]: This function isn't related to partition tables — it only processes the `AccessConditions` and returns the ranger. So even it's not meet any exists partition, the `len(r.Ranges)` also should equals to 1.

The pruning stage is handled separately [here](https://github.com/pingcap/tidb/pull/62002/files#diff-989673423ebb0def5c5df96de2bdf7095411d398cf7ee5a04f89d3921f49e168L485).

Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go:402]: The root cause of these problems is that the planner uses a different function from this one, and the results of the two are not always consistent. To ensure correctness, we should use the same function here.

File: tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result (hunk 10 above)
Comment (Defined2014) [reply tests/integrationtest/r/planner/core/casetest/partition/partition_pruner.result:936]: I don't think this is related to partition types. And also I think the test cases have already been added in [PR #59918](https://github.com/pingcap/tidb/pull/59918).

File: pkg/planner/core/point_get_plan.go (hunk 9 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go:400]: Done

Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go:398]: I added a comments here, I think it's not easy to do this right now. And this part will not affect the performance very much.

> However, we currently don't have a safe and reliable way to do that. `col` is of type `expression.Column`, while the IDs from `pt.GetPartitionColumnIDs()` are derived from `t.Cols()` which type is `table.Column`. It's not always correctly to compare them.

**Comment by Defined2014** [comment]
/cherry-pick-release-8.5
