### PR TITLE
external: set the period of checking merge iter hotspot according to the key size

### LINKED ISSUE #47923: bad performance for global sort if key is small and has hotspot
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

bad performance for global sort if key is small and has hotspot

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #47923

Problem Summary:
If a hotspot is detected, the reader would change to concurrent mode and read 32M data by default.
If the hotspot shifts to other files, the previous reader will drop the unread byte to release memory. If dropping too many bytes, the whole performance would be very bad.

### What is changed and how it works?
Set the period of checking merge iter hotspot according to the key size.
For example, if the average key size is 0.1K (by sampling), then we can check the hotspot every
(32M / 0.1K) = 320000 KVs.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
before:
image
after:
image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/external/iter.go [hunk 1]
```diff
@@ -179,6 +182,15 @@ func newMergeIter[
 			elem:      e,
 			readerIdx: j,
 		})
+		sampleKeySize += len(e.sortKey())
+		sampleKeyCnt++
+	}
+	// We check the hotspot when the elements size is almost the same as the concurrent reader buffer size.
+	// So that we don't drop too many bytes if the hotspot shifts to other files.
+	if sampleKeySize == 0 {
```
Comment (lance6716) [inline br/pkg/lightning/backend/external/iter.go:190]: it's a bit safer to check `sampleKeySize/sampleKeyCnt` is zero

**Review by lance6716 — APPROVED** [review]

File: br/pkg/lightning/backend/external/iter.go (hunk 1 above)
Comment (wjhuang2016) [reply br/pkg/lightning/backend/external/iter.go:190]: If sampleKeySize > 0, then `sampleKeySize/sampleKeyCnt` can't be 0

**Review by tangenta — APPROVED** [review]
