### PR TITLE
br: fix stats meta count is zero if backup has no checksum

### LINKED ISSUE #60978: the count of stats_meta is zero when restore if backup has no checksum
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. backup with `--checksum=false`
2. snapshot restore

### 2. What did you expect to see? (Required)
the count of stats_meta is larger than 0.
### 3. What did you see instead (Required)
the count of stats_meta is 0.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #60978

Problem Summary:
the count of stats_meta is zero if backup has no checksum
### What changed and how does it work?
get the count of stats_meta by collecting the files instead of total kvs of table.
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/snap_client/pipeline_items.go [hunk 1]
```diff
@@ -367,6 +367,75 @@ func (buffer *statsMetaItemBuffer) TryUpdateMetas(ctx context.Context, statsHand
 	return statsHandler.SaveMetaToStorage("br restore", false, metaUpdates...)
 }
 
+func calculateRowCountForPhysicalTable(files []*backuppb.File, availableIndexCount int) int64 {
+	totalKvs := uint64(0)
+	for _, file := range files {
+		totalKvs += file.TotalKvs
+	}
+	return int64(totalKvs / uint64(availableIndexCount+1))
```
Comment (BornChanger) [inline br/pkg/restore/snap_client/pipeline_items.go:375]: If the `no_null_index` feature comes in, this won't work. cc @bb7133

Comment (BornChanger) [reply br/pkg/restore/snap_client/pipeline_items.go:375]: @Leavrth is it a must to make the table row count accurate?

Comment (Leavrth) [reply br/pkg/restore/snap_client/pipeline_items.go:375]: After analyze, it will update the real row count.

**Review by 3pointer — APPROVED** [review]

File: br/pkg/restore/snap_client/pipeline_items_test.go [hunk 2]
```diff
@@ -100,3 +107,133 @@ func TestPipelineConcurrentHandler2(t *testing.T) {
...
+				ID:        tableID + 1000,
+				Partition: upPart,
+				Indices:   indices,
+			},
+			FilesOfPhysicals: files,
+		},
+	}
+}
+
+func TestUpdateStatsMeta(t *testing.T) {
```
Comment (BornChanger) [inline br/pkg/restore/snap_client/pipeline_items_test.go:201]: please add json column with mvi

Comment (Leavrth) [reply br/pkg/restore/snap_client/pipeline_items_test.go:215]: Done, added in integration test.
