### PR TITLE
planner: do not eliminate group_concat in aggregate elimination

### LINKED ISSUE #9922: wrong aggEliminateCheck for `select group_concat() group by unique`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
create table t(id int primary key, a int, b int);
insert into t values(1,1,1);
insert into t values(2,1,1);
select group_concat(a,b) from t group by id;
```

2. What did you expect to see?
``` sql
+-------------------+
| group_concat(a,b) |
+-------------------+
| 11                |
| 11                |
+-------------------+
```

3. What did you see instead?
``` sql
+-------------------+
| group_concat(a,b) |
+-------------------+
| 1                 |
| 1                 |
+-------------------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
``` sql
Release Version: v3.0.0-beta.1-8-g7cabaac61
Git Commit Hash: 7cabaac61dbc7fa65948ee7fbd11018af7765369
Git Branch: master
UTC Build Time: 2019-03-27 03:25:00
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
fix #9922 

### What is changed and how it works?
Do not eliminate group_concat considering system variable group_concat_max_len.

Actually, we can rewrite GROUP_CONCAT when all the arguments it
accepts are promised to be NOT-NULL. (Recorded as a task in #9968)
When it accepts only 1 argument, we can extract this argument into a
projection.
When it accepts multiple arguments, we can wrap the arguments with a
function CONCAT_WS and extract this function into a projection.
BUT, GROUP_CONCAT should truncate the final result according to the
system variable `group_concat_max_len`. To ensure the correctness of
the result, we close the elimination of GROUP_CONCAT here.
### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects

 - Possible performance regression
 Performance may regress when group_concat accepts only 1 argument.

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: planner/core/rule_aggregation_elimination.go [hunk 1]
```diff
@@ -36,6 +36,19 @@ type aggregationEliminateChecker struct {
...
 func (a *aggregationEliminateChecker) tryToEliminateAggregation(agg *LogicalAggregation) *LogicalProjection {
+	for _, af := range agg.AggFuncs {
+		// TODO: Actually, we can rewrite GROUP_CONCAT.
+		// When it accepts only 1 argument, we can extract this argument into a
+		// projection.
+		// When it accepts multiple arguments, we can wrap the arguments with a
+		// function CONCAT_WS and extract this function into a projection.
+		// BUT, GROUP_CONCAT should truncate the final result according to the
+		// system variable `group_concat_max_len`. To ensure the correctness of
+		// the result, we close the elimination of GROUP_CONCAT here.
```
Comment (zz-jason) [inline planner/core/rule_aggregation_elimination.go]: please create a github issue for this TODO.

File: planner/core/rule_aggregation_elimination.go [hunk 2]
```diff
@@ -36,6 +36,19 @@ type aggregationEliminateChecker struct {
...
+		if af.Name == ast.AggFuncGroupConcat {
+			return nil
```
Comment (zz-jason) [inline planner/core/rule_aggregation_elimination.go]: please add a explain test for this behavior.

**Comment by XuHuaiyu** [comment]
PTAL @zz-jason 
Issue created as #9968

File: planner/core/rule_aggregation_elimination.go [hunk 3]
```diff
@@ -36,6 +36,19 @@ type aggregationEliminateChecker struct {
 // For count(expr), sum(expr), avg(expr), count(distinct expr, [expr...]) we may need to rewrite the expr. Details are shown below.
 // If we can eliminate agg successful, we return a projection. Else we return a nil pointer.
 func (a *aggregationEliminateChecker) tryToEliminateAggregation(agg *LogicalAggregation) *LogicalProjection {
+	for _, af := range agg.AggFuncs {
+		// TODO: Actually, we can rewrite GROUP_CONCAT.
+		// When it accepts only 1 argument, we can extract this argument into a
```
Comment (winoros) [inline planner/core/rule_aggregation_elimination.go]: This case is easy to be added in this pr?

Comment (XuHuaiyu) [reply planner/core/rule_aggregation_elimination.go]: Noop, since group_concat_max_len is configurable.
We can not ensure whether the length of the final result exceeds max_len even if there is only 1 argument.

And, maybe it'll be easier to implement if we wrap the argument(s) into a concat_ws despite the count of the arguments.
