### PR TITLE
importinto: fix panic when field is missing for generated column

### LINKED ISSUE #64657: import into runtime panic: index out of range [7] with length 0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
table schema:
```
CREATE TABLE `t1` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) GENERATED ALWAYS AS (`a` + 1) VIRTUAL,
  KEY `idx_v_b` (`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
csv file content:
```
"a"
1
2
3
4
```

### 2. What did you expect to see? (Required)
import into success

### 3. What did you see instead (Required)
```
[2025/11/24 13:29:02.016 +00:00] [INFO] [conn.go:1215] ["command dispatched failed"] [keyspaceName=keyspace_a] [conn=507510916] [session_alias=] [connInfo="id:507510916, addr:10.200.52.41:38324 status:10, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="IMPORT INTO `test`.`t1` FROM 's3://nfs/tools_test_data/virutal_column_index/test.t1.[0-9]*.csv?access-key=xxx&secret-access-key=xxxx&endpoint=http%3a%2f%2fminio.pingcap.net%3a9001&force-path-style=true' WITH DETACHED,skip_rows=1"] [txn_mode=PESSIMISTIC] [timestamp=0] [err="runtime error: index out of range [7] with length 0\ngithub.com/pingcap/errors.Trace\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20250523034308-74f78ae071ee/juju_adaptor.go:15\ngithub.com/pingcap/tidb/pkg/util.GetRecoverError\n\t/workspace/source/tidb/pkg/util/util.go:330\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next.func1\n\t/workspace/source/tidb/pkg/executor/internal/exec/executor.go:444\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:791\nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:115\nencoding/binary.littleEndian.PutUint64\n\t/usr/local/go/src/encoding/binary/binary.go:115\ngithub.com/pingcap/tidb/pkg/util/chunk.MutRow.SetDatum\n\t/workspace/source/tidb/pkg/util/chunk/mutrow.go:307\ngithub.com/pingcap/tidb/pkg/lightning/backend/kv.evalGeneratedColumns\n\t/workspace/source/tidb/pkg/lightning/backend/kv/base.go:380\ngithub.com/pingcap/tidb/pkg/lightning/backend/kv.(*BaseKVEncoder).EvalGeneratedColumns\n\t/workspace/source/tidb/pkg/lightning/backend/kv/base.go:312\ngithub.com/pingcap/tidb/pkg/executor/importer.(*TableKVEncoder).fillRow\n\t/workspace/source/tidb/pkg/executor/importer/kv_encode.go:227\ngithub.com/pingcap/tidb/pkg/executor/importer.(*TableKVEncoder).getRow\n\t/workspace/source/tidb/pkg/executor/importer/kv_encode.go:192\ngithub.com/pingcap/tidb/pkg/executor/importer.(*TableKVEncoder).parserData2TableData\n\t/workspace/source/tidb/pkg/executor/importer/kv_encode.go:154\ngithub.com/pingcap/tidb/pkg/executor/importer.(*TableKVEncoder).Encode\n\t/workspace/source/tidb/pkg/executor/importer/kv_encode.go:95\ngithub.com/pingcap/tidb/pkg/executor/importer.(*chunkEncoder).encodeLoop\n\t/workspace/source/tidb/pkg/executor/importer/chunk_process.go:355\ngithub.com/pingcap/tidb/pkg/executor/importer.(*LoadDataController).sampleIndexRatioForOneFile\n\t/workspace/source/tidb/pkg/executor/importer/sampler.go:139\ngithub.com/pingcap/tidb/pkg/executor/importer.(*LoadDataController).sampleIndexSizeRatio\n\t/workspace/source/tidb/pkg/executor/importer/sampler.go:74\ngithub.com/pingcap/tidb/pkg/executor/importer.(*LoadDataController).CalResourceParams\n\t/workspace/source/tidb/pkg/executor/importer/import.go:1421\ngithub.com/pingcap/tidb/pkg/executor.(*ImportIntoExec).Next\n\t/workspace/source/tidb/pkg/executor/import_into.go:114\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/workspace/source/tidb/pkg/executor/internal/exec/executor.go:460\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).next\n\t/workspace/source/tidb/pkg/executor/adapter.go:1350\ngithub.com/pingcap/tidb/pkg/executor.(*recordSet).Next\n\t/workspace/source/tidb/pkg/executor/adapter.go:188\ngithub.com/pingcap/tidb/pkg/server/internal/resultset.(*tidbResultSet).Next\n\t/workspace/source/tidb/pkg/server/internal/resultset/resultset.go:72\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).writeChunks\n\t/workspace/source/tidb/pkg/server/conn.go:2383\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).writeResultSet\n\t/workspace/source/tidb/pkg/server/conn.go:2326\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt\n\t/workspace/source/tidb/pkg/server/conn.go:2129\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery\n\t/workspace/source/tidb/pkg/server/conn.go:1838\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\n\t/workspace/source/tidb/pkg/server/conn.go:1428\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\n\t/workspace/source/tidb/pkg/server/conn.go:1176\ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn\n\t/workspace/source/tidb/pkg/server/server.go:791\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"]
```
### 4. What is your TiDB version? (Required)

 Release Version: v9.0.0-beta.2.pre-813-g5e34015
Edition: Enterprise
Git Commit Hash: 5e340159ca0460f01646a3d4eb950f16fcf57872
Git Branch: HEAD
UTC Build Time: 2025-11-24 15:05:40
GoVersion: go1.23.12
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Enterprise Extension Commit Hash: dc633aae52eb11b4e3549e3a7ef5b0ed14e159b1
Kernel Type: Next Generation

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #64657

Problem Summary:

### What changed and how does it work?
the `hasValue` should be false in this case, so `ProcessColDatum` can handle this case correctly
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

same case in the issue
```sql
mysql> create table t(id int, b int);
Query OK, 0 rows affected (0.13 sec)

mysql> import into t from '/Users/jujiajia/Downloads/test.t1.000000000.csv' with skip_rows=1;
select+--------+-----------+-------------------------------------------------+--------------+----------+-------+----------+------------------+---------------+----------------+----------------------------+----------------------------+----------------------------+------------+----------------------------+----------+-------------------------+---------------------+-----------------------+----------------+--------------+
| Job_ID | Group_Key | Data_Source                                     | Target_Table | Table_ID | Phase | Status   | Source_File_Size | Imported_Rows | Result_Message | Create_Time                | Start_Time                 | End_Time                   | Created_By | Last_Update_Time           | Cur_Step | Cur_Step_Processed_Size | Cur_Step_Total_Size | Cur_Step_Progress_Pct | Cur_Step_Speed | Cur_Step_ETA |
+--------+-----------+-------------------------------------------------+--------------+----------+-------+----------+------------------+---------------+----------------+----------------------------+----------------------------+----------------------------+------------+----------------------------+----------+-------------------------+---------------------+-----------------------+----------------+--------------+
| 120001 | NULL      | /Users/jujiajia/Downloads/test.t1.000000000.csv | `test`.`t`   |       50 |       | finished | 12B              |             4 |                | 2025-11-25 13:52:10.533079 | 2025-11-25 13:52:11.071388 | 2025-11-25 13:52:13.094640 | root@%     | 2025-11-25 13:52:13.094640 | NULL     | NULL                    | NULL                | NULL                  | NULL           | NULL         |
+--------+-----------+-------------------------------------------------+--------------+----------+-------+----------+------------------+---------------+----------------+----------------------------+----------------------------+----------------------------+------------+----------------------------+----------+-------------------------+---------------------+-----------------------+----------------+--------------+
1 row in set (2.83 sec)

mysql> select * from t;
+------+------+
| id   | b    |
+------+------+
|    1 | NULL |
|    2 | NULL |
|    3 | NULL |
|    4 | NULL |
+------+------+
4 rows in set (0.00 sec)

mysql> drop table t;
Query OK, 0 rows affected (0.19 sec)

mysql> create table t(id int, b int generated always as (id+1));
Query OK, 0 rows affected (0.07 sec)

mysql> import into t from '/Users/jujiajia/Downloads/test.t1.000000000.csv' with skip_rows=1;
select * from t;+--------+-----------+-------------------------------------------------+--------------+----------+-------+----------+------------------+---------------+----------------+----------------------------+----------------------------+----------------------------+------------+----------------------------+----------+-------------------------+---------------------+-----------------------+----------------+--------------+
| Job_ID | Group_Key | Data_Source                                     | Target_Table | Table_ID | Phase | Status   | Source_File_Size | Imported_Rows | Result_Message | Create_Time                | Start_Time                 | End_Time                   | Created_By | Last_Update_Time           | Cur_Step | Cur_Step_Processed_Size | Cur_Step_Total_Size | Cur_Step_Progress_Pct | Cur_Step_Speed | Cur_Step_ETA |
+--------+-----------+-------------------------------------------------+--------------+----------+-------+----------+------------------+---------------+----------------+----------------------------+----------------------------+----------------------------+------------+----------------------------+----------+-------------------------+---------------------+-----------------------+----------------+--------------+
| 120002 | NULL      | /Users/jujiajia/Downloads/test.t1.000000000.csv | `test`.`t`   |       55 |       | finished | 12B              |             4 |                | 2025-11-25 13:52:42.642442 | 2025-11-25 13:52:43.164485 | 2025-11-25 13:52:45.190578 | root@%     | 2025-11-25 13:52:45.190578 | NULL     | NULL                    | NULL                | NULL                  | NULL           | NULL         |
+--------+-----------+-------------------------------------------------+--------------+----------+-------+----------+------------------+---------------+----------------+----------------------------+----------------------------+----------------------------+------------+----------------------------+----------+-------------------------+---------------------+-----------------------+----------------+--------------+
1 row in set (2.77 sec)

mysql> select * from t;
+------+------+
| id   | b    |
+------+------+
|    1 |    2 |
|    2 |    3 |
|    3 |    4 |
|    4 |    5 |
+------+------+
4 rows in set (0.00 sec)

mysql>

```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/realtikvtest/importintotest/import_into_test.go [hunk 1]
```diff
@@ -478,13 +478,18 @@ func (s *mockGCSSuite) TestInputCountMisMatchAndDefault() {
...
+	loadDataSQL = fmt.Sprintf(`IMPORT INTO t FROM 'gs://test-multi-load/input-cnt-mismatch.csv?endpoint=%s'`, gcsEndpoint)
+	s.tk.MustQuery(loadDataSQL)
+	s.tk.MustQuery("SELECT * FROM t;").Check(testkit.Rows([]string{"1 test1 2", "2 test2 3"}...))
 	// mapped column of the missed field has non-null default
 	s.tk.MustExec("drop table if exists t;")
 	s.tk.MustExec("create table t (a bigint, b varchar(100), c int default 100);")
 	loadDataSQL = fmt.Sprintf(`IMPORT INTO t FROM 'gs://test-multi-load/input-cnt-mismatch.csv?endpoint=%s'`, gcsEndpoint)
 	s.tk.MustQuery(loadDataSQL)
-	// we convert it to null all the time
-	s.tk.MustQuery("SELECT * FROM t;").Check(testkit.Rows([]string{"1 test1 <nil>", "2 test2 22"}...))
```
Comment (D3Hunter) [inline tests/realtikvtest/importintotest/import_into_test.go:487]: the previous behavior is wrong, we should use the column default value

Comment (lance6716) [reply tests/realtikvtest/importintotest/import_into_test.go:487]: I remember lightning has some requests about fill the missing columns with default value rather than NULL, but I can't find them
