### PR TITLE
session: ensure pitr id map schema upgrade when ver221 was reused

### LINKED ISSUE #66994: Upgrade may skip bootstrap ver221 from specified branch
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Upgrade TiDB from customer branch `release-8.5-20250606-v8.5.2` to `release-8.5` (v8.5.6+).

### 2.Reason
The customer branch already used bootstrap version `221` for different changes. During upgrade, TiDB only executes bootstrap steps with a greater bootstrap version, so the upstream `upgradeToVer221` step is skipped, leaving `mysql.tidb_pitr_id_map` schema not updated (e.g. missing `restore_id` and/or incorrect PRIMARY KEY).

### 4. What is your TiDB version? (Required)
`release-8.5-20250606-v8.5.2`

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #66994 ref #61706

Problem Summary:

- Customer branch `release-8.5-20250606-v8.5.2` was forked from 8.5.2 and used bootstrap version 221 to add `i_user` indexes on mysql privilege tables.
- Upstream `release-8.5` later used bootstrap version 221 for a different change: updating `mysql.tidb_pitr_id_map` to add `restore_id` and extend the primary key.
- When a cluster upgrades from that customer branch back to upstream `release-8.5`, bootstrap sees version 221 as already applied and skips the upstream `upgradeToVer221` path.
- As a result, `mysql.tidb_pitr_id_map` can remain on the old schema, missing `restore_id` and keeping the old primary key definition. Later PITR operations may then fail on this table.

### What changed and how does it work?

- Keep bootstrap version 226 for writing `cluster_id` into `mysql.tidb` (upstream behavior).
- Add a new bootstrap version 227 as a compatibility repair step for the version 221 conflict.
- In `upgradeToVer227`, ensure `mysql.tidb_pitr_id_map` exists, then read the PRIMARY KEY column order from `information_schema.STATISTICS`.
- If the PRIMARY KEY is already `(restore_id, restored_ts, upstream_cluster_id, segment_id)`, skip the remaining DDLs.
- Otherwise, execute the same DDLs as version 221 to add `restore_id` and rebuild the PRIMARY KEY.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix an upgrade issue where a customer branch reused bootstrap version 221 for a different change, causing the upstream PITR schema upgrade for `mysql.tidb_pitr_id_map` to be skipped.
```

### CODE REVIEW

File: pkg/session/bootstrap.go [hunk 1]
```diff
@@ -3341,6 +3347,59 @@ func upgradeToVer225(s sessiontypes.Session, ver int64) {
...
+		logutil.BgLogger().Fatal("get primary key columns failed", zap.Error(err), zap.String("db", dbName), zap.String("table", tableName))
+	}
+	cols := make([]string, 0, len(rows))
+	for _, row := range rows {
+		cols = append(cols, row.GetString(0))
+	}
+	return cols
+}
+
+func sameStringSlice(a, b []string) bool {
```
Comment (bb7133) [inline pkg/session/bootstrap.go]: We can simply use `slice.Equal`(https://pkg.go.dev/slices#Equal).

File: pkg/session/bootstrap.go [hunk 2]
```diff
@@ -1254,16 +1254,21 @@ const (
 	// Add index on user field for some mysql tables.
 	version225 = 225
 
+	// version 226
+	// Ensure `mysql.tidb_pitr_id_map` has `restore_id` and correct primary key.
+	// This is a compatibility fix for upgrade paths where version221 was already used.
```
Comment (bb7133) [inline pkg/session/bootstrap.go]: IMHO we can explain this with more details like 'version221 was used in other branches/releases for a different purpose'.

Comment (fzzf678) [reply pkg/session/bootstrap.go]: Updated in https://github.com/pingcap/tidb/pull/66993/commits/46abf0490f8878d087a1cba1fba0017c93eee605

**Review by yudongusa — APPROVED** [review]
