### PR TITLE
copr: fix the issue that busy threshold may redirect batch copr to followers

### LINKED ISSUE #58001: batched coprocessor task may be sent to wrong store
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Manually inject server-is-busy error in client-go: https://github.com/you06/client-go/blob/939d1305079f8d7a208f1ae914b043dc1092bcc4/internal/client/client.go#L692-L705
2. Build TiDB & Run cluster with 3 tikv `tiup playground nightly --kv=3 --tiflash=0 --db.binpath=tidb-server`
3. Run the following script

```bash
sysbench --config-file=config oltp_read_only --tables=1 --table-size=100000 --auto_inc=false prepare
mysql -h 127.0.0.1 -P 4000 -u root -D test -e "update sbtest1 set k = mod(id, 100)"
mysql -h 127.0.0.1 -P 4000 -u root -D test -e "delete from sbtest1 where mod(id, 9) != 0"
mysql -h 127.0.0.1 -P 4000 -u root -D test -e "split table sbtest1 between (0) and (100000) regions 99"
mysql -h 127.0.0.1 -P 4000 -u root -D test -e "analyze table sbtest1"


for (( i=1; i<=300; i++ ))
do
  mysql -h 127.0.0.1 -P 4000 -u root -D test -e "select * from sbtest1 force index(k_1) where k between 1 and 10" > /dev/null
  sleep 1
done
```

### 2. What did you expect to see? (Required)

No region errors or region errors in the beginning only.

### 3. What did you see instead (Required)

Image

### 4. What is your TiDB version? (Required)

nightly.

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: close #58001

Problem Summary:

### What changed and how does it work?

When the coprocessor tasks are batched by store, the busy threshold may redirect them to follower peer of the main task. The main tasks' follower peer can easily be the wrong store for batched tasks and cause unexpected error and retries.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

File: pkg/store/copr/coprocessor.go [hunk 1]
```diff
@@ -568,10 +568,17 @@ func (b *batchStoreTaskBuilder) handle(task *copTask) (err error) {
 			// disable paging for batched task.
 			b.tasks[idx].paging = false
 			b.tasks[idx].pagingSize = 0
+			// The task and it's batched can be served only in the store we chose.
+			// If the task is redirected to other replica, the batched task may not meet region-miss or store-not-match error.
+			// So disable busy threshold for the task which carries batched tasks.
```
Comment (cfzjywxk) [inline pkg/store/copr/coprocessor.go:573]: Need to polish the comments here.

**Review by cfzjywxk — APPROVED** [review]
