### PR TITLE
planner: use TxnCtx.InfoSchema to prevent schema inconsistency

### LINKED ISSUE #49751: v7.1 serverless: sysbench update hit runtime error: index out of range [4] with length 4
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

```
{"level":"ERROR","namespace":"cse-oltp-fun-follower-v71-tps-5251483-1-764","pod":"tc1-tidb-0","log":"[conn.go:1133] [\"connection running loop panic\"] [keyspaceName=keyspace_b] [keyspaceID=2] [conn=8407789495742633465] [lastSQL=\"update `sbtest5` set `c` = ? where `id` = ?\"] [err=\"runtime error: index out of range [4] with length 4\"] [stack=\"github.com/pingcap/tidb/server.(*clientConn).Run.func1\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1136\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:914\\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile.func1\\n\\t/go/src/github.com/pingcap/tidb/executor/compiler.go:54\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:914\\nruntime.goPanicIndex\\n\\t/usr/local/go/src/runtime/panic.go:114\\ngithub.com/pingcap/tidb/planner/core.GetUpdateColumnsInfo\\n\\t/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:5631\\ngithub.com/pingcap/tidb/planner/core.(*Update).buildTbl2UpdateColumns\\n\\t/go/src/github.com/pingcap/tidb/planner/core/foreign_key.go:335\\ngithub.com/pingcap/tidb/planner/core.(*Update).buildOnUpdateFKTriggers\\n\\t/go/src/github.com/pingcap/tidb/planner/core/foreign_key.go:223\\ngithub.com/pingcap/tidb/planner/core.buildPointUpdatePlan\\n\\t/go/src/github.com/pingcap/tidb/planner/core/point_get_plan.go:1637\\ngithub.com/pingcap/tidb/planner/core.tryUpdatePointPlan\\n\\t/go/src/github.com/pingcap/tidb/planner/core/point_get_plan.go:1576\\ngithub.com/pingcap/tidb/planner/core.TryFastPlan\\n\\t/go/src/github.com/pingcap/tidb/planner/core/point_get_plan.go:587\\ngithub.com/pingcap/tidb/planner.Optimize\\n\\t/go/src/github.com/pingcap/tidb/planner/optimize.go:214\\ngithub.com/pingcap/tidb/planner/core.generateNewPlan\\n\\t/go/src/github.com/pingcap/tidb/planner/core/plan_cache.go:302\\ngithub.com/pingcap/tidb/planner/core.GetPlanFromSessionPlanCache\\n\\t/go/src/github.com/pingcap/tidb/planner/core/plan_cache.go:205\\ngithub.com/pingcap/tidb/planner.OptimizeExecStmt\\n\\t/go/src/github.com/pingcap/tidb/planner/optimize.go:537\\ngithub.com/pingcap/tidb/planner.Optimize\\n\\t/go/src/github.com/pingcap/tidb/planner/optimize.go:170\\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile\\n\\t/go/src/github.com/pingcap/tidb/executor/compiler.go:98\\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\\n\\t/go/src/github.com/pingcap/tidb/session/session.go:2193\\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt\\n\\t/go/src/github.com/pingcap/tidb/server/driver_tidb.go:294\\ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult\\n\\t/go/src/github.com/pingcap/tidb/server/conn_stmt.go:308\\ngithub.com/pingcap/tidb/server.(*clientConn).executePlanCacheStmt\\n\\t/go/src/github.com/pingcap/tidb/server/conn_stmt.go:236\\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute\\n\\t/go/src/github.com/pingcap/tidb/server/conn_stmt.go:227\\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1463\\ngithub.com/pingcap/tidb/server.(*clientConn).Run\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1214\\ngithub.com/pingcap/tidb/server.(*Server).onConn\\n\\t/go/src/github.com/pingcap/tidb/server/server.go:716\"]","container":"tidb"}
```

### 4. What is your TiDB version? (Required)
```
./pd-server -V
 Release Version: v7.1.1-serverless
Edition: Community
Git Commit Hash: 013d876c84de90568645dc430f22b36cc709fe9d
Git Branch: release-7.1-keyspace
UTC Build Time:  2023-12-20 01:38:39
2023-12-21T15:50:04.124+0800	INFO	k8s/client.go:135	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./tidb-server -V
 Release Version: v7.1.1-serverless
Edition: Community
Git Commit Hash: 534517c1d35d65098a1ba5c5ba87ac3cfb6d4338
Git Branch: release-7.1-keyspace
UTC Build Time: 2023-12-20 10:08:43
GoVersion: go1.21.4
Race Enabled: false
TiKV Min Version: 6.1.0
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: ref #41622

close #49751

Problem Summary:

### What changed and how does it work?

The result of  `sctx.GetInfoSchema().(infoschema.InfoSchema)` **is not stable** if the caller side is not in a transaction && snapshot_ts is not set, it just get the latest InfoSchema:

https://github.com/pingcap/tidb/blob/c20874ed33df4621f2a8e12baf43a705755e3291/pkg/session/session.go#L4052-L4074

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: use TxnCtx.InfoSchema to prevent schema inconsistency
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

File: pkg/util/mock/context.go [hunk 1]
```diff
@@ -450,6 +450,11 @@ func (c *Context) InSandBoxMode() bool {
 	return c.inSandBoxMode
 }
 
+// SetInfoSchema implements the sessionctx.Context interface.
```
Comment (qw4990) [inline pkg/util/mock/context.go:453]: Setting InfoSchema manually seems dangerous, please comment this is only for test, do not use it in TiDB.

**Review by qw4990 — APPROVED** [review]

File: pkg/util/mock/context.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/util/mock/context.go:453]: This package is only used in the test. it is a mock context.

Comment (hawkingrei) [reply pkg/util/mock/context.go]: Done
