### PR TITLE
types: fix CAST('2.0.8 X' AS DATE)

### LINKED ISSUE #24387: Cast string to date failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> CREATE TABLE t(title text, created_at datetime);
Query OK, 0 rows affected (0.72 sec)

mysql>  INSERT INTO t(`title`, `created_at`) VALUES("2.0.8 hotfix", current_timestamp());
Query OK, 1 row affected (0.26 sec)

mysql> SELECT * FROM t WHERE title=created_at;
Empty set, 1 warning (0.10 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------------+
| Level   | Code | Message                                                     |
+---------+------+-------------------------------------------------------------+
| Warning | 1292 | evaluation failed: Incorrect datetime value: '2.0.8 hotfix' |
+---------+------+-------------------------------------------------------------+
1 row in set (0.12 sec)

mysql> select cast(title as date) from t;
ERROR 1105 (HY000): strconv.Atoi: parsing "8 hotfix": invalid syntax
mysql> SELECT * FROM t WHERE cast(title as date) = '2021-03-31';
Empty set, 1 warning (0.09 sec)

```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
Returns no error.

### 3. What did you see instead (Required)
```
mysql> select cast(title as date) from t;
ERROR 1105 (HY000): strconv.Atoi: parsing "8 hotfix": invalid syntax
```


### 4. What is your TiDB version? (Required)
```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.0.1
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 05:51:17
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.09 sec)
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by wzru**
Signed-off-by: WangZhengru <wangshaun@outlook.com>

### What problem does this PR solve?

Issue Number: close #24387 

Problem Summary:

```sql
SELECT CAST('2.0.8 hotfix' as DATE);
```

MySQL:
```bash
mysql> SELECT CAST('2.0.8 hotfix' as DATE);
+------------------------------+
| CAST('2.0.8 hotfix' as DATE) |
+------------------------------+
| 2002-00-08                   |
+------------------------------+
1 row in set, 1 warning (0.01 sec)

mysql> SELECT version();
+-----------+
| version() |
+-----------+
| 5.7.34    |
+-----------+
1 row in set (0.00 sec)
```

TiDB:
```bash
mysql> SELECT CAST('2.0.8 hotfix' as DATE);
ERROR 1105 (HY000): strconv.Atoi: parsing "8 hotfix": invalid syntax
mysql> SELECT version();
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 5.7.25-TiDB-v5.2.0-alpha-284-g1641b3411 |
+-----------------------------------------+
1 row in set (0.00 sec)
```

### What is changed and how it works?

What's Changed:

`splitDateTime()` and `parseDatetime()` implementation

How it Works:

Tests 

- [x] Unit test
- [x] Integration test

Side effects

- [ ] Performance regression: Consumes more CPU

### Release note 

- No release note

### CODE REVIEW

**Comment by wzru** [comment]
As for modifying tests, we have found bugs in mysql-server `str_to_datetime` function and reported to MySQL. https://bugs.mysql.com/bug.php?id=104350
```sql
mysql> SELECT year("1.1.1");
+---------------+
| year("1.1.1") |
+---------------+
|          2001 |
+---------------+
1 row in set (0.00 sec)

mysql> SELECT year("1-1-1");
+---------------+
| year("1-1-1") |
+---------------+
|             1 |
+---------------+
1 row in set (0.00 sec)
```
We will make all years with less than or equal to 2 digits and `<=70` be 21th century. This behavior will be incompatible with MySQL until this bug is fixed in MySQL.

**Review by guo-shaoge — APPROVED** [review]

File: expression/integration_test.go [hunk 1]
```diff
@@ -1408,7 +1408,7 @@ func (s *testIntegrationSuite2) TestTimeBuiltin(c *C) {
 
 	// for year
 	result = tk.MustQuery(`select year("2013-01-09"), year("2013-00-09"), year("000-01-09"), year("1-01-09"), year("20131-01-09"), year(null);`)
-	result.Check(testkit.Rows("2013 2013 0 1 <nil> <nil>"))
+	result.Check(testkit.Rows("2013 2013 0 2001 <nil> <nil>"))
```
Comment (ichn-hu) [inline expression/integration_test.go:1411]: MySQL report `1` here, I doubt it might be MySQL's bug, you can propose it on https://bugs.mysql.com/, until they verified this, we should not modify the tests.

File: expression/integration_test.go [hunk 2]
```diff
@@ -10006,10 +10006,10 @@ func (s *testIntegrationSuite) TestTimestampIssue25093(c *C) {
 	tk.MustExec("drop table if exists t")
 	tk.MustExec("create table t(col decimal(45,8) default 13.654 not null);")
 	tk.MustExec("insert  into t set col = 0.4352;")
-	tk.MustQuery("select timestamp(0.123)").Check(testkit.Rows("0000-00-00 00:00:00.123"))
-	tk.MustQuery("select timestamp(col) from t;").Check(testkit.Rows("0000-00-00 00:00:00.435200"))
+	tk.MustQuery("select timestamp(0.123)").Check(testkit.Rows("2000-00-00 00:00:00.123"))
+	tk.MustQuery("select timestamp(col) from t;").Check(testkit.Rows("2000-00-00 00:00:00.435200"))
```
Comment (ichn-hu) [inline expression/integration_test.go:10010]: mysql 8.0.23 reports 0000 here.

**Review by ichn-hu — CHANGES_REQUESTED** [review]
Please verify all the changed test cases against MySQL, I found some of them not compliant. We don't want to introduce new incompatibility from fixing existing incompatibility.

File: expression/integration_test.go (hunk 1 above)
Comment (wzru) [reply expression/integration_test.go:1411]: As for this test, we have found bugs in mysql-server str_to_datetime function and reported to MySQL. https://bugs.mysql.com/bug.php?id=104350

**Review by ichn-hu — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]
LGTM
