### PR TITLE
dupdetect: gRPC cancel should trigger retry

### LINKED ISSUE #58523: DDL failed with error `failed to create remote duplicate kv stream` when TiKV is unstable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

when add unique index, restart TiKV or make network unstable

### 2. What did you expect to see? (Required)

DDL job should retry and succeed 

### 3. What did you see instead (Required)

Image

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #58523

Problem Summary:

### What changed and how does it work?

gRPC "canceled" error may be caused by network problems, for example the server thinks the client is gone so it cancels the RPC, and then the client receives canceled error, because streaming RPC has 2 connections independently for C->S and S->C. In lightning use case, we only want to break the retry when the user cancels it.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/backend/local/duplicate.go [hunk 1]
```diff
@@ -997,7 +998,7 @@ func (m *dupeDetector) processRemoteDupTask(
 			}
 			return nil
 		}
-		if log.IsContextCanceledError(err) {
+		if stderrors.Is(err, context.Canceled) {
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/duplicate.go:1001]: will err be nested? maybe check `ctx.Err() != nil`

Comment (lance6716) [reply pkg/lightning/backend/local/duplicate.go:1001]: I see https://pkg.go.dev/errors#Is can handle nested error by checking `Unwrap` interface. However I think check the `ctx` argument is more direct. I'll check it soon.

**Review by D3Hunter — APPROVED** [review]

**Comment by OliverS929** [comment]
LGTM

**Review by wjhuang2016 — APPROVED** [review]
