### PR TITLE
br: fix advancer log

### LINKED ISSUE #60559: br: improve regionIter logging
## Enhancement

```
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F72800000000886CF26] [end=7480000000000005C65F7280000000088CE8BE]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F728000000006B42D44] [end=7480000000000005C65F728000000006B7DBC0]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F7280000000086195F0] [end=7480000000000005C65F72800000000864AEA8]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F728000000006C85726] [end=7480000000000005C65F728000000006CB20C3]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F728000000006F5759A] [end=7480000000000005C65F728000000006FCDC02]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005BE5F72800000004CEA82FC] [end=7480000000000005BE5F72800000004D86B21A]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F728000000007A35BEF] [end=7480000000000005C65F728000000007A764D6]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F728000000002D5B36E] [end=7480000000000005C65F728000000002D9480C]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F728000000002E62406] [end=7480000000000005C65F728000000002E9CA7F]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F728000000007FA8235] [end=7480000000000005C65F72800000000802423D]
[2025/03/27 18:37:36.043 +00:00] [WARN] [regioniter.go:141] ["failed with trying to scan regions"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [start=7480000000000005C65F7280000000076D027C] [end=7480000000000005C65F728000000007735776]
```
huge log spamming can simplify

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #60559

Problem Summary:

### What changed and how does it work?
code cleanup and fix log spamming when context cancelled and millions of region scanning returns same error.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/streamhelper/flush_subscriber.go [hunk 1]
```diff
@@ -125,14 +125,15 @@ func (f *FlushSubscriber) Drop() {
...
-func (f *FlushSubscriber) HandleErrors(ctx context.Context) {
+func (f *FlushSubscriber) HandleErrors() {
 	for id, sub := range f.subscriptions {
 		err := sub.loadError()
 		if err != nil {
 			retry := f.canBeRetried(err)
 			log.Warn("Meet error.", zap.String("category", "log backup flush subscriber"),
 				logutil.ShortError(err), zap.Bool("can-retry?", retry), zap.Uint64("store", id))
 			if retry {
+				log.Info("retry connecting to store to add subscription")
```
Comment (YuJuncen) [inline br/pkg/streamhelper/flush_subscriber.go:136]: It seems this log can be derived from `zap.Bool("can-retry?", retry)` in the previous log?

**Review by YuJuncen — APPROVED** [review]
rest lgtm

File: br/pkg/streamhelper/flush_subscriber.go (hunk 1 above)
Comment (BornChanger) [reply br/pkg/streamhelper/flush_subscriber.go:136]: how about removing l134, and track the record id to l136?

**Review by Leavrth — APPROVED** [review]
