### PR TITLE
server, tidb-server: improve unix socket handling

### LINKED ISSUE #8459: tidb-server options -socket and -host are incompatible
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
./bin/tidb-server -socket /tmp/mysql.sock -host 127.0.0.1 -P 3306
```

2. What did you expect to see?

I would expect it to listen on both.  This is important because of MySQL's special handling of localhost:
- For the libmysql derived clients it will switch to using unix socket.
- For other drivers like JDBC it will only ever use tcp.

So it is useful to be able to have the server listen on both for a fully local install.

3. What did you see instead?

 It will only listen on one (the socket!)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-beta-644-g89cd59d21
Git Commit Hash: 89cd59d217637f5e79fdc81681c98531c668e688
Git Branch: newmaster
UTC Build Time: 2018-11-26 04:47:59
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by morgo**
### What problem does this PR solve? 

Fixes #8459

### What is changed and how it works?

- Allows server to listen on both unix socket and TCP at the same time
- Removes socket file on server clean exit
- Handles the error / refuses to start if the socket file is already in use.
- Supports the case that neither a socket file or tcp (host,port) are specified

### Check List 

Tests 

 - Manual test

I'm not actually sure how to write tests to validate it, but happy to do so with pointers.

Code changes

 - Has exported function/method change

Side effects

 - Possible performance regression (socket access may be slower)
 - Breaking backward compatibility (socket access when both tcp and socket enabled will authenticate like tcp connections)
 - Increased code complexity

Related changes

 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8836)

### CODE REVIEW

**Comment by morgo** [comment]
PTAL @coocood, @jackysp.  Thx!

File: server/server.go [hunk 1]
```diff
@@ -151,15 +182,23 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
 	}
 
 	var err error
-	if cfg.Socket != "" {
-		if s.listener, err = net.Listen("unix", cfg.Socket); err == nil {
-			log.Infof("Server is running MySQL Protocol through Socket [%s]", cfg.Socket)
-		}
-	} else {
+
+	if s.cfg.Host != "" && s.cfg.Port != 0 {
```
Comment (gregwebs) [inline server/server.go]: An empty Host can be valid for the Listen API.
A zero port is also valid to the Listen API. Its practical use seems limited, but we should note all changes in behavior.

File: server/server.go [hunk 2]
```diff
@@ -405,6 +444,16 @@ func (s *Server) GracefulDown() {
 	}
 }
 
+// CleanupSocketFile cleans up socket file if it was created.
+func (s *Server) CleanupSocketFile() {
+	if s.cfg.Socket != "" {
+		log.Infof("[server] removing socket file [%s]", s.cfg.Socket)
+		if err := os.Remove(s.cfg.Socket); err != nil {
+			log.Warningf("[server] failed to remove socket file! err: %s", err)
```
Comment (gregwebs) [inline server/server.go]: I think this should be logged at the Error level since there is clearly an error occurring.

File: tidb-server/main.go [hunk 3]
```diff
@@ -548,4 +548,5 @@ func cleanup() {
 		svr.KillAllConnections()
 	}
 	closeDomainAndStorage()
+	svr.CleanupSocketFile()
```
Comment (gregwebs) [inline tidb-server/main.go]: This may be out of the scope of this PR, but it seems that at least for this cleanup it should happen in the context of a defer that recovers from a panic.

File: server/server.go [hunk 4]
```diff
@@ -151,15 +182,23 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
...
 			log.Infof("Server is running MySQL Protocol at [%s]", addr)
 		}
+		if cfg.Socket != "" {
+			go s.forwardUnixSocketToTCP(cfg.Socket, addr) // listen on both
+		}
+	} else if cfg.Socket != "" {
+		if s.listener, err = net.Listen("unix", cfg.Socket); err == nil {
+			log.Infof("Server is running MySQL Protocol through Socket [%s]", cfg.Socket)
+		} else {
+			log.Fatalf("err: %s", err) // in use?
```
Comment (gregwebs) [inline server/server.go]: Yes, all errors must be handled!

Instead of logging fatally, this function should probably return the error and log at the error level as needed.

File: server/server.go [hunk 5]
```diff
@@ -133,6 +135,35 @@ func (s *Server) isUnixSocket() bool {
...
 
+func (s *Server) forwardUnixSocketToTCP(socket string, addr string) {
+	if sock, err := net.Listen("unix", socket); err == nil {
+		log.Infof("Server redirecting [%s] to [%s]", socket, addr)
+		for {
+			if uconn, err := sock.Accept(); err == nil {
+				log.Infof("server socket forwarding from [%s] to [%s]", socket, addr)
+				go s.handleForwardedConnection(uconn, addr)
+			} else {
+				log.Warningf("server failed to forward from [%s] to [%s], err: %s", socket, addr, err)
```
Comment (gregwebs) [inline server/server.go]: This seems like an error rather than a warning.

File: server/server.go [hunk 6]
```diff
@@ -133,6 +135,35 @@ func (s *Server) isUnixSocket() bool {
...
+
+func (s *Server) handleForwardedConnection(uconn net.Conn, addr string) {
+	if tconn, err := net.Dial("tcp", addr); err == nil {
+		if _, err := io.Copy(tconn, uconn); err != nil {
+			log.Warningf("socket forward copy failed: %s", err)
+		}
+	} else {
+		log.Warningf("socket forward failed: could not connect to [%s], err: %s", addr, err)
+	}
+	if err := uconn.Close(); err != nil {
```
Comment (gregwebs) [inline server/server.go]: a close is usually done in a defer statement.

File: server/server.go [hunk 7]
```diff
@@ -133,6 +135,35 @@ func (s *Server) isUnixSocket() bool {
...
+			} else {
+				log.Warningf("server failed to forward from [%s] to [%s], err: %s", socket, addr, err)
+			}
+		}
+	} else {
+		log.Fatalf("err: %s", err) // in use?
+	}
+}
+
+func (s *Server) handleForwardedConnection(uconn net.Conn, addr string) {
```
Comment (gregwebs) [inline server/server.go]: Rather than logging warnings, I would return an error and have the caller deal with it (the caller can log or retry).

File: server/server.go (hunk 6 above)
Comment (morgo) [reply server/server.go]: If I use defer, I have to use an anonymous function to catch the error though.  it looks longer?

File: server/server.go (hunk 1 above)
Comment (morgo) [reply server/server.go]: The configuration system defaults a Host and Port.  There needs to be a use case to disable tcp/ip, so in practical terms it is `./tidb-server -host '' -socket /tmp/tidb.sock`   It can be documented..

File: server/server.go (hunk 4 above)
Comment (morgo) [reply server/server.go]: I've refactored this now, so the err is caught further down.  Outcome is the same.

File: server/server.go [hunk 8]
```diff
@@ -133,6 +135,35 @@ func (s *Server) isUnixSocket() bool {
 	return s.cfg.Socket != ""
 }
 
+func (s *Server) forwardUnixSocketToTCP(socket string, addr string) {
+	if sock, err := net.Listen("unix", socket); err == nil {
```
Comment (coocood) [inline server/server.go]: We should store the socket listener in `Server` and close it in in `Close` method if both TCP and socket is enabled.

File: server/server.go (hunk 6 above)
Comment (coocood) [reply server/server.go]: We don't care much about the error returned by the Close method.
So we use
```
defer terror.Call(uconn.Close)
```

File: server/server.go [hunk 9]
```diff
@@ -151,15 +182,21 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
...
-			log.Infof("Server is running MySQL Protocol through Socket [%s]", cfg.Socket)
-		}
-	} else {
+
+	if s.cfg.Host != "" && s.cfg.Port != 0 {
 		addr := fmt.Sprintf("%s:%d", s.cfg.Host, s.cfg.Port)
 		if s.listener, err = net.Listen("tcp", addr); err == nil {
 			log.Infof("Server is running MySQL Protocol at [%s]", addr)
+			if cfg.Socket != "" {
+				go s.forwardUnixSocketToTCP(cfg.Socket, addr) // listen on both
```
Comment (coocood) [inline server/server.go]: We can listen to the socket here, only handle connections in goroutine.

Comment (morgo) [reply server/server.go]: I like the idea, but if I inline and remove the goroutine, it blocks (the for loop below with `socket.Accept()` needs to be run async).  Ideas?

Comment (morgo) [reply server/server.go]: I think I made a mistake in my testing; it is blocking on the socket regardless :(

**Comment by morgo** [comment]
I am not sure if I tested it wrong yesterday, but I can't seem to get the server to listen on tcp + socket.  I tried:
```
make server && ./bin/tidb-server -socket /tmp/tidb.sock &
mysql --no-defaults -S /tmp/tidb.sock 
```

The mysql client just hangs until I control + c, then get the error:
```
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 95
```

I appreciate any feedback if you know what's wrong :(

**Comment by coocood** [comment]
The listener seems still not closed in `Server.Close` method.

File: server/server.go (hunk 9 above)
Comment (coocood) [reply server/server.go]: Listen doesn't block, `Accept` in a goroutine.

File: tidb-server/main.go (hunk 3 above)
Comment (morgo) [reply tidb-server/main.go]: It now handles correctly in server `Close()`

File: server/tidb_test.go [hunk 10]
```diff
@@ -163,6 +163,9 @@ func (ts *TidbTestSuite) TestMultiStatements(c *C) {
 func (ts *TidbTestSuite) TestSocket(c *C) {
 	cfg := config.NewConfig()
 	cfg.Socket = "/tmp/tidbtest.sock"
+	cfg.Host = ""
```
Comment (coocood) [inline server/tidb_test.go]: The feature will be covered by this test if host and port is not empty.

File: server/server.go [hunk 11]
```diff
@@ -292,6 +336,10 @@ func (s *Server) Close() {
 		terror.Log(errors.Trace(err))
 		s.listener = nil
 	}
+	if s.socket != nil {
+		err := s.socket.Close()
+		terror.Log(errors.Trace(err))
```
Comment (coocood) [inline server/server.go]: Better set to nil like the above, keep it consistent.

File: server/tidb_test.go (hunk 10 above)
Comment (morgo) [reply server/tidb_test.go]: I did this to restore compatibility:
- Prior to this patch, specifying socket meant that the server would not listen on TCP/IP.
- Now, to prevent listening on TCP/IP you need to specify host as empty string.

I think it makes sense that the test-suite should not require TCP/IP.

Comment (morgo) [reply server/tidb_test.go]: I've renamed this test to `TestSocketForwarding`, and created a new test for just `TestSocket`.

**Comment by coocood** [comment]
LGTM
