### PR TITLE
import: check table empty skips using index

### LINKED ISSUE #39477: Lightning: Table Empty Check Cannot Find Imported Dirty Data on Previous Failed Imports
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Import the data using Lightning, and halt it half-way during importing the data records, but before importing any indices .  
2. Import the data a second time.  

### 2. What did you expect to see? (Required)
The second import should not be allowed (if check-requirements is turned on ), because the table has actually imported some record data in the previous import.

### 3. What did you see instead (Required)
* The second import can be executed successfully
* If checking the record count, we can find inconsistencies on these two statements: 
```
SELECT COUNT(*) FROM t;
SELECT COUNT(*) FROM t USE INDEX();
```
Seems the dirty data is still inside the table, and it cannot be cleared unless dropping the table and re-import again.  

### 4. What is your TiDB version? (Required)
Latest master version

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #39477 

Problem Summary:

### What is changed and how it works?
* When pre-checking whether target table is empty, skip using the index and directly scan the record.
* Added integration tests to verify that.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dsdashun** [comment]
Integration BR test failed at `br_foreign_key`.  All Lightning tests have passed: https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/14309/pipeline

File: br/pkg/lightning/restore/get_pre_info.go [hunk 1]
```diff
@@ -189,7 +189,12 @@ func (g *TargetInfoGetterImpl) IsTableEmpty(ctx context.Context, schemaName stri
 	}
 	var dump int
 	err = exec.QueryRow(ctx, "check table empty",
-		fmt.Sprintf("SELECT 1 FROM %s LIMIT 1", common.UniqueTable(schemaName, tableName)),
+		// Here we use the `USE INDEX()` hint to skip fetch the record from index.
+		// In Lightning, if previous importing is halted half-way, it is possible that
+		// the data is partially imported, but the index data has not been imported.
+		// In this situation, if no hint is added, the SQL executor might fetch the record from index,
+		// which is empty.  This will result in missing check.
```
Comment (lance6716) [inline br/pkg/lightning/restore/get_pre_info.go:196]: it's still possible that index data in partially imported.

**Review by lance6716 — APPROVED** [review]
please fix unit tests, rest lgtm

File: br/pkg/lightning/restore/get_pre_info.go (hunk 1 above)
Comment (dsdashun) [reply br/pkg/lightning/restore/get_pre_info.go:196]: > it's still possible that index data in partially imported.

If index data is partially imported, table-empty check will report errors on the second import even if `USE INDEX()` is not used.  So it will be figured out by the current table-empty-check logic.

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
> tried on `tiup playground nightly`(v6.5.0-alpha-nightly-20221205), cannot reproduce it, steps:
> 
> * run lightning, data imported, but failed before import index
> * rm checkpoint
> * import again:
> .....

seems when table rows is small, tidb will use full-table-scan, but when rows is larger it will use index-scan
```
mysql> explain select 1 from t limit 1;
+-----------------------------+---------+-----------+---------------+--------------------------------+
| id                          | estRows | task      | access object | operator info                  |
+-----------------------------+---------+-----------+---------------+--------------------------------+
| Projection_6                | 1.00    | root      |               | 1->Column#3                    |
| └─Limit_7                   | 1.00    | root      |               | offset:0, count:1              |
|   └─TableReader_11          | 1.00    | root      |               | data:Limit_10                  |
|     └─Limit_10              | 1.00    | cop[tikv] |               | offset:0, count:1              |
|       └─TableFullScan_9     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-----------------------------+---------+-----------+---------------+--------------------------------+
```

**Comment by dsdashun** [comment]
> tried on `tiup playground nightly`(v6.5.0-alpha-nightly-20221205), cannot reproduce it, steps:
> 
> * run lightning, data imported, but failed before import index
> * rm checkpoint
> * import again:
>   .....

You can use the data introduced in c0e0c3ceebdea550c5609055c6583d2eaf4da436 , which is reproducible.
