### PR TITLE
driver: check argument types

### LINKED ISSUE #95: NullData test failed.
https://github.com/ngaut/beego/tree/tidb-support

https://github.com/astaxie/beego/blob/master/orm/orm_test.go#L268

	orm_test.go:136: 	
		Error: cannot use 2015-09-10 16:26:58.291379202 +0800 CST (type time.Time) in assignment to, or comparison with, column datetime (type DATETIME)
		orm_test.go:362: 
		      353:           Uint16Ptr:   &uint16Ptr,
		      354:           Uint32Ptr:   &uint32Ptr,
		      355:           Uint64Ptr:   &uint64Ptr,
		      356:           Float32Ptr:  &float32Ptr,
		      357:           Float64Ptr:  &float64Ptr,
		      358:           DecimalPtr:  &decimalPtr,
		      359:       }
		      360:   
		      361:       id, err = dORM.Insert(&d)
		 >>   362:       throwFail(t, err)

### PR DESCRIPTION
**Pull request by coocood**
We use mysql.Time internally and time.Time type has not been handled, so when user pass in time.Time type, TiDB returns error.
Since we reduced integer types to only 'int', 'int64', 'uint64' recently, all other integer types needs to be converted to int64 or uint64.

Fixes #95

### CODE REVIEW

File: session.go [hunk 1]
```diff
@@ -269,18 +268,40 @@ func (s *session) PrepareStmt(sql string) (stmtID uint32, paramCount int, fields
...
+			args[i] = int64(x)
+		case uint8:
+			args[i] = uint64(x)
+		case uint16:
+			args[i] = uint64(x)
+		case uint32:
+			args[i] = uint64(x)
+		case uint:
+			args[i] = uint64(x)
+		case int64:
```
Comment (qiuyesuifeng) [inline session.go]: Use one line?

Comment (coocood) [inline session.go]: Then it won't compile

**Comment by qiuyesuifeng** [comment]
LGTM

File: session.go (hunk 1 above)
Comment (ngaut) [inline session.go]: Why skip these type ? Please add comments.

File: session.go [hunk 2]
```diff
@@ -267,20 +266,45 @@ func (s *session) PrepareStmt(sql string) (stmtID uint32, paramCount int, fields
 	return prepareStmt(s, sql)
 }
 
+// checkArgs make sure all the arguments's type is known and can be handled.
```
Comment (qiuyesuifeng) [inline session.go]: makes

File: session.go [hunk 3]
```diff
@@ -267,20 +266,45 @@ func (s *session) PrepareStmt(sql string) (stmtID uint32, paramCount int, fields
...
+// integer types are converted to int64 and uint64, time.Time is converted to mysql.Time.
+// time.Duration. is converted to mysql.Duration, other known types is leaved as it is.
```
Comment (qiuyesuifeng) [inline session.go]: time.Duration. －> time.Duration

Comment (qiuyesuifeng) [inline session.go]: leaved -> left?

**Comment by ngaut** [comment]
LGTM
