### PR TITLE
executor: avoid `ProjectoinExec`'s goroutine leak 

### LINKED ISSUE #14125: execution: go routine leak when executing explain analyze
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
step 1: load tpch sf=1 data;
step 2:  explain analyze select l_partkey*200 from lineitem ;
step 3: kill tidb id

http://127.0.0.1:10080/debug/pprof/goroutine?debug=2
shows some active goroutine of projection

note: select l_partkey*200 from lineitem; runs correctly.

2. What did you expect to see?
no leak

3. What did you see instead?
leak

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
+------------------------------------------------+
| version()                                      |
+------------------------------------------------+
| 5.7.25-TiDB-v4.0.0-alpha-1178-g5940bb2ce-dirty |
+------------------------------------------------+

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve? 
fix #14125

### What is changed and how it works?
invoke close() even next() errors in explain statements

### Check List 

Tests 

 - No code

Code changes

 - N/A

Side effects

 - N/A

Related changes

 - Need to cherry-pick to the release branch

Release note

 - Write release note for bug-fix or new feature.

### CODE REVIEW

File: executor/explain.go [hunk 1]
```diff
@@ -73,17 +73,22 @@ func (e *ExplainExec) Next(ctx context.Context, req *chunk.Chunk) error {
 func (e *ExplainExec) generateExplainInfo(ctx context.Context) ([][]string, error) {
 	if e.analyzeExec != nil {
 		chk := newFirstChunk(e.analyzeExec)
+		var next_err, close_err error
 		for {
-			err := Next(ctx, e.analyzeExec, chk)
-			if err != nil {
-				return nil, err
+			next_err = Next(ctx, e.analyzeExec, chk)
```
Comment (lonng) [inline executor/explain.go]: Please use Golang idiomatic name convention.

File: executor/explain.go [hunk 2]
```diff
@@ -73,17 +73,22 @@ func (e *ExplainExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
 			if chk.NumRows() == 0 {
 				break
 			}
 		}
-		if err := e.analyzeExec.Close(); err != nil {
-			return nil, err
+		close_err = e.analyzeExec.Close()
+		if next_err != nil {
+			return nil, next_err
+		}
```
Comment (SunRunAway) [inline executor/explain.go]: Is it better?
`defer terror.Log(e.analyzeExec.Close())`

File: executor/explain.go [hunk 3]
```diff
@@ -73,17 +74,22 @@ func (e *ExplainExec) Next(ctx context.Context, req *chunk.Chunk) error {
 func (e *ExplainExec) generateExplainInfo(ctx context.Context) ([][]string, error) {
 	if e.analyzeExec != nil {
 		chk := newFirstChunk(e.analyzeExec)
+		var nextErr, closeErr error
```
Comment (SunRunAway) [inline executor/explain.go]: Suggest,

```go
func (e *EExplainExec) generateExplainInfo(ctx context.Context) (result [][]string, err error) {
...

var nextErr, closeErr error
defer func() 
    closeErr = e.analyzeExec.Close()
    	if nextErr != nil {
			if closeErr != nil {
				err = errors.New(nextErr.Error() + ", " + closeErr.Error())
			} else {
				err =nextErr
			}
		} else {
                err = closeErr
        }
}
...    
}
```

File: executor/explain.go [hunk 4]
```diff
@@ -15,6 +15,7 @@ package executor
 
 import (
 	"context"
+	"github.com/pingcap/errors"
```
[the remark this answers is not in the document]
Comment (fzhedu) [reply executor/explain.go]: done

File: executor/explain.go (hunk 3 above)
Comment (fzhedu) [reply executor/explain.go]: If next() or close() encounter errors, this function should return, rather than execute the code after Line:95. This logic is changed if taking the code above.

Comment (fzhedu) [reply executor/explain.go]: add defer to handle panic

File: executor/explain.go [hunk 5]
```diff
@@ -70,23 +71,40 @@ func (e *ExplainExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
 
-func (e *ExplainExec) generateExplainInfo(ctx context.Context) ([][]string, error) {
+func (e *ExplainExec) generateExplainInfo(ctx context.Context) (rows [][]string, err error) {
+	closed := false
+	defer func() {
+		// handle panic
+		if panicErr := recover(); panicErr != nil && !closed {
+			err = e.analyzeExec.Close()
+			closed = true
+		}
```
Comment (SunRunAway) [inline executor/explain.go]: If you call `recover` here, the panic will be recovered here, which is not we want.
Suggest just check `closed`.

```go
defer func() {
    if !closed { e.analyzeExec.Close() }
}()

Comment (fzhedu) [reply executor/explain.go]: if without recover, the goroutine will panic, and test will not work.
