### PR TITLE
planner: check infoSchema when builing cacheKey

### LINKED ISSUE #34974: *: inconsistency between prepare execute and normal sql in rc or for update read when inforSchema is changed
## Bug Report

In Rc or For-update-read, when information schema is changed, there may be some inconsistencies between prepare-execute and normal sql.

### 1. Minimal reproduce step (Required)

```
func TestInconsistency(t *testing.T) {
	store, clean := testkit.CreateMockStore(t)
	defer clean()

	tk1 := testkit.NewTestKit(t, store)
	tk2 := testkit.NewTestKit(t, store)
	tk1.MustExec("use test")
	tk2.MustExec("use test")

	tk1.MustExec("drop table if exists t1")
	tk1.MustExec("create table t1(id int primary key, c int)")
	tk1.MustExec("insert into t1 values(1, 1), (2, 2)")

	tk1.MustExec("prepare s from 'select * from t1'")

	tk1.MustExec("set tx_isolation='READ-COMMITTED'")
	tk1.MustExec("begin pessimistic")

	tk1.MustQuery("execute s").Check(testkit.Rows("1 1", "2 2"))

	// Change infoSchema
	tk2.MustExec("alter table t1 drop column c")

	tk1.MustQuery("select * from t1").Check(testkit.Rows("1 1", "2 2"))
	// It should be consistent with above
	tk1.MustQuery("execute s").Check(testkit.Rows("1", "2"))
}
```

### 2. What did you expect to see? (Required)
The results of `execute s` and `select * from t1` are different even though they should be the same.

### 4. What is your TiDB version? (Required)

dce5064e9e15d0b17c36f73e21fc71bcaa419e90

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What problem does this PR solve?

Solve the problem of inconsistency between prepare execute and normal sql in rc or for update read when inforSchema is changed.

Previously, in rc or for update read, the latest information schema is used to get the plan in prepare execute mode, while in normal sql, however, the context provider's information schema is used. 

If the schema changed, for example, from two columns to three columns, prepare execute mode will return rows with three column while the normal sql (select * from ...) will return rows with two column, even though they represent the same sql.

This PR solves this inconsistency and let them return rows with two columns both.

Issue Number: close #34974

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/common_plans.go [hunk 1]
```diff
@@ -451,9 +451,22 @@ func (e *Execute) getPhysicalPlan(ctx context.Context, sctx sessionctx.Context,
 	stmtCtx.UseCache = prepared.UseCache
 
 	var bindSQL string
+
+	schemaCheck := sctx.GetSessionVars().IsIsolation(ast.ReadCommitted) || preparedStmt.ForUpdateRead
 	if prepared.UseCache {
 		bindSQL = GetBindSQL4PlanCache(sctx, preparedStmt)
-		if cacheKey, err = NewPlanCacheKey(sctx.GetSessionVars(), preparedStmt.StmtText, preparedStmt.StmtDB, prepared.SchemaVersion); err != nil {
```
Comment (lcwangchao) [inline planner/core/common_plans.go:456]: I think we should add a field with the latest schema version to compute the cacheKey, instead of replacing the old one. Or sometimes the newer txn will use the old one's cache. For example:

```sql
create table t(id int);
insert into t values(1);
prepare s from 'select * from t for update';
begin optimistic;
              alter table t add column (v int); --- another session add a new column v
execute s; --- result: 1, and the plan will be cached
rollback;
begin optimistic;
execute s; --- Should be (1, NULL), but the second txn is using the cached plan, so only one column is returned in fact
```

File: planner/core/preprocess.go [hunk 2]
```diff
@@ -1696,13 +1696,7 @@ func (p *preprocessor) ensureInfoSchema() infoschema.InfoSchema {
...
 		return p.InfoSchema
 	}
-	// `Execute` under some conditions need to see the latest information schema.
-	if p.PreprocessExecuteISUpdate != nil {
-		if newInfoSchema := p.ExecuteInfoSchemaUpdate(p.Node, p.ctx); newInfoSchema != nil {
-			p.InfoSchema = newInfoSchema
-			return p.InfoSchema
-		}
-	}
+
```
Comment (lcwangchao) [inline planner/core/preprocess.go:1699]: After this fix some codes will not be used any more, you can remove them too:

https://github.com/pingcap/tidb/blob/0f85650aa43cb60a77ce507e02203db45584e914/planner/core/preprocess.go#L79-L83
https://github.com/pingcap/tidb/blob/0f85650aa43cb60a77ce507e02203db45584e914/planner/optimize.go#L68-L88

File: planner/core/prepare_test.go [hunk 3]
```diff
@@ -2931,3 +2931,178 @@ func TestPlanCacheWithRCWhenInfoSchemaChange(t *testing.T) {
...
+	tk2.MustExec("alter table t1 drop column c")
+	tk2.MustExec("insert into t1 values (3)")
+	// Execute using sql
+	tk1.MustQuery("execute s").Check(testkit.Rows("1 1", "2 2", "3 <nil>"))
+	// Execute using binary
+	rs, err = tk1.Session().ExecutePreparedStmt(ctx, stmtID, []types.Datum{})
+	require.Nil(t, err)
+	tk1.ResultSetToResult(rs, fmt.Sprintf("%v", rs)).Check(testkit.Rows("1 1", "2 2", "3 <nil>"))
+	// Normal sql
+	tk1.MustQuery("select * from t1").Check(testkit.Rows("1 1", "2 2", "3 <nil>"))
```
Comment (lcwangchao) [inline planner/core/prepare_test.go:2976]: Please add a new case after this. 

1. begin a new transaction
2. execute
3. The infoschema of the result should keep the same with the latest one.

File: planner/core/prepare_test.go [hunk 4]
```diff
@@ -2931,3 +2931,178 @@ func TestPlanCacheWithRCWhenInfoSchemaChange(t *testing.T) {
...
+	tk2 := testkit.NewTestKit(t, store)
+	tk1.MustExec("use test")
+	tk2.MustExec("use test")
+	tk1.MustExec("drop table if exists t1")
+	tk1.MustExec("create table t1(id int primary key, c int)")
+	tk1.MustExec("insert into t1 values(1, 1), (2, 2)")
+	// prepare text protocol
+	tk1.MustExec("prepare s from 'select * from t1'")
+	// prepare binary protocol
+	stmtID, _, _, err := tk1.Session().PrepareStmt("select * from t1")
```
Comment (lcwangchao) [inline planner/core/prepare_test.go:2950]: Could you add some cases for preparing point get plan with binary proto?

File: planner/core/common_plans.go (hunk 1 above)
Comment (SpadeA-Tang) [reply planner/core/common_plans.go:456]: I have fixed it and add a test. Thanks.

File: planner/core/prepare_test.go (hunk 4 above)
Comment (SpadeA-Tang) [reply planner/core/prepare_test.go:2950]: This is  already covered in the `TestCacheHitInForUpdateRead`.

File: planner/core/preprocess.go (hunk 2 above)
Comment (SpadeA-Tang) [reply planner/core/preprocess.go:1685]: Done.

File: planner/core/prepare_test.go (hunk 3 above)
Comment (SpadeA-Tang) [reply planner/core/prepare_test.go:2976]: Done.

File: planner/core/cache.go [hunk 5]
```diff
@@ -56,14 +56,21 @@ func PreparedPlanCacheEnabled() bool {
...
+	connID        uint64
+	stmtText      string
+	schemaVersion int64
+
+	// Used for RC or ForUpdateRead Only. It represents the version used to build plan cache last time.
+	// In Rc or ForUpdateRead, we should check whether the information schema has been changed when using plan cache.
+	// If it changed, we should rebuild the plan. However, the plan is rebuilt by using the information schema from
+	// the context provider, not the latest information schema to be consistent with the non-prepare-execute sql. But we
+	// save the latest' information schema version, which is used to build cacheKey, in order to hit plan cache.
+	LastUpdatedSchemaVersion int64
```
Comment (qw4990) [inline planner/core/cache.go:69]:
```suggestion
	lastUpdatedSchemaVersion int64
```

File: planner/core/cache.go [hunk 6]
```diff
@@ -115,7 +123,7 @@ func SetPstmtIDSchemaVersion(key kvcache.Key, stmtText string, schemaVersion int
 }
 
 // NewPlanCacheKey creates a new planCacheKey object.
-func NewPlanCacheKey(sessionVars *variable.SessionVars, stmtText, stmtDB string, schemaVersion int64) (kvcache.Key, error) {
+func NewPlanCacheKey(sessionVars *variable.SessionVars, stmtText, stmtDB string, schemaVersion int64, lastUpdatedSchemaVersion int64) (kvcache.Key, error) {
 	if stmtText == "" {
```
Comment (qw4990) [inline planner/core/cache.go:127]: Better to return an error if `lastUpdatedSchemaVersion` is zero for safety?

Comment (SpadeA-Tang) [reply planner/core/cache.go:127]: Done.

File: parser/ast/misc.go [hunk 7]
```diff
@@ -485,9 +485,16 @@ type Prepared struct {
...
-	UseCache      bool
-	CachedPlan    interface{}
-	CachedNames   interface{}
+
+	// Used for RC or ForUpdateRead Only. It represents the version used to build plan cache last time.
+	// In Rc or ForUpdateRead, we should check whether the information schema has been changed when using plan cache.
+	// If it changed, we should rebuild the plan. However, the plan is rebuilt by using the information schema from
+	// the context provider, not the latest information schema to be consistent with the non-prepare-execute sql. But we
+	// save the latest' information schema version, which is used to build cacheKey, in order to hit plan cache.
+	LastUpdatedSchemaVersion int64
```
Comment (lcwangchao) [inline parser/ast/misc.go:494]: Do we need `LastUpdatedSchemaVersion` cached here? If the statement is not for update, we can pass 0 for the second infoshcema, and if it is for update, we can get the latest schema version from domain directly.

File: planner/core/cache.go [hunk 8]
```diff
@@ -115,10 +122,16 @@ func SetPstmtIDSchemaVersion(key kvcache.Key, stmtText string, schemaVersion int
...
-func NewPlanCacheKey(sessionVars *variable.SessionVars, stmtText, stmtDB string, schemaVersion int64) (kvcache.Key, error) {
+// Note: lastUpdatedSchemaVersion will only be set in the case of rc or for update read in order to
+// differentiate the cache key. In other cases, it will be 0.
+func NewPlanCacheKey(sessionVars *variable.SessionVars, stmtText, stmtDB string, schemaVersion int64,
+	lastUpdatedSchemaVersion int64) (kvcache.Key, error) {
 	if stmtText == "" {
 		return nil, errors.New("no statement text")
 	}
+	if schemaVersion == 0 {
+		return nil, errors.New("Schema version / latest schema version uninitialized")
```
Comment (lcwangchao) [inline planner/core/cache.go:133]: remove "/ latest schema" because it can be zero now?

File: parser/ast/misc.go (hunk 7 above)
Comment (SpadeA-Tang) [reply parser/ast/misc.go]: Done.

File: planner/core/cache.go (hunk 8 above)
Comment (SpadeA-Tang) [reply planner/core/cache.go]: Done.

File: planner/core/common_plans.go [hunk 9]
```diff
@@ -451,9 +451,21 @@ func (e *Execute) getPhysicalPlan(ctx context.Context, sctx sessionctx.Context,
...
 	var bindSQL string
+
+	// In rc or for update read, we need the latest schema version to decide whether we need to
+	// rebuild the plan. So we set this value in rc or for update read. In other cases, let it be 0.
+	var latestSchemaVersion int64
+	schemaCheck := sctx.GetSessionVars().IsIsolation(ast.ReadCommitted) || preparedStmt.ForUpdateRead
 	if prepared.UseCache {
 		bindSQL = GetBindSQL4PlanCache(sctx, preparedStmt)
-		if cacheKey, err = NewPlanCacheKey(sctx.GetSessionVars(), preparedStmt.StmtText, preparedStmt.StmtDB, prepared.SchemaVersion); err != nil {
+		if schemaCheck {
```
Comment (lcwangchao) [inline planner/core/common_plans.go:461]: Replace the `schemaCheck` to `sctx.GetSessionVars().IsIsolation(ast.ReadCommitted) || preparedStmt.ForUpdateRead` directly here? I'm not sure schemaCheck is a good name, but I think we do not to name it and the below comments describes what it is doing.

**Review by lcwangchao — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Comment by you06** [comment]
The commit history looks weird, you may rebase your code, @SpadeA-Tang
