### PR TITLE
planner, executor: fix the logic for inline projection of executors

### LINKED ISSUE #45112: Got index out of range error for subqyery
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
drop table if exists t1, t2, t3;
create table t1(a varchar(20), b varchar(20), c varchar(20), primary key(a, b, c));
create table t2(a varchar(20), b varchar(20), c varchar(20), primary key(a));
create table t3(aa varchar (20), bb varchar (20), cc varchar(20), primary key(aa, bb));
insert into t1 values('1','1','1');
insert into t2 values('1','1','1');
insert into t3 values('1','1','1');
select (select max(b) from t2 where t2.a = t1.a), (select cc from t3 where t3.bb = t1.b and t3.aa = '1'), a from t1 where t1.a = '1' group by t1.a,  t1.b;
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
```
+-------------------------------------------+--------------------------------------------------------+---+
| (select max(b) from t2 where t2.a = t1.a) | (select cc from t3 where t3.bb = t1.b and t3.aa = '1') | a |
+-------------------------------------------+--------------------------------------------------------+---+
| 1                                         | 1                                                      | 1 |
+-------------------------------------------+--------------------------------------------------------+---+
1 row in set (0.001 sec)
```
### 3. What did you see instead (Required)
ERROR 1105 (HY000): runtime error: index out of range [0] with length 0
### 4. What is your TiDB version? (Required)
```
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.3.0-alpha-94-gc44ba1c1a8
Edition: Community
Git Commit Hash: c44ba1c1a868220764d9f11274b683d1aaecacb6
Git Branch: master
UTC Build Time: 2023-07-02 08:50:32
GoVersion: go1.20.1
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.009 sec)
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #45112 

Problem Summary:

### What is changed and how it works?

The Physical Projection Elimination permits the case that the parent plan has a column which cannot be found by the child(ren).

The only thing we can rely on during the execution phase is the `Column.Index`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by fixdb — APPROVED** [review]
+1

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]

File: planner/core/pb_to_plan.go [hunk 1]
```diff
@@ -81,6 +78,17 @@ func (b *PBPlanBuilder) pbToPhysicalPlan(e *tipb.Executor) (p PhysicalPlan, err
 		// TODO: Support other types.
 		err = errors.Errorf("this exec type %v doesn't support yet", e.GetTp())
 	}
+	if subPlan != nil {
+		p.SetChildren(subPlan)
+	}
+	// The limit missed its output cols via the protobuf.
+	// We need to add it back and do a ResolveIndicies for the later inline projection.
```
Comment (AilinKid) [inline planner/core/pb_to_plan.go:85]: limit schema will not always like what its children are, like its children are projection, and it may have been eliminated

File: planner/core/resolve_indices.go [hunk 2]
```diff
@@ -173,12 +194,32 @@ func (p *PhysicalMergeJoin) ResolveIndices() (err error) {
...
+	colsNeedResolving := p.schema.Len()
+	// The last output column of this two join is the generated column to indicate whether the row is matched or not.
+	if p.JoinType == LeftOuterSemiJoin || p.JoinType == AntiLeftOuterSemiJoin {
+		colsNeedResolving--
+	}
+	// To avoid that two plan shares the same column slice.
+	shallowColSlice := make([]*expression.Column, p.schema.Len())
+	copy(shallowColSlice, p.schema.Columns)
+	p.schema = expression.NewSchema(shallowColSlice...)
+	for i := 0; i < colsNeedResolving; i++ {
```
Comment (AilinKid) [inline planner/core/resolve_indices.go:216]: the only thing we can trust is the column.Index
while there will be some same cols ref to single one problems

Comment (AilinKid) [reply planner/core/resolve_indices.go:216]: see #45831
