### PR TITLE
bindinfo, planner: emit NO_DECORRELATE hints in EXPLAIN EXPLORE

### LINKED ISSUE #65986: planner: Explain Explore should consider `NO_DECORRELATE()` hint
## Enhancement
Whether or not decorrelate a query is not cost-based now in TiDB, which caused many suboptimal queries in the past.
The current behavior is that the optimizer always decorrelates sub-queries unless there is a `NO_DECORRELATE()` hint.
If the outer table is small, always-decorrelate leads to sub-optimal plans. For example, if `o` is small, the second undecorrelated plan would be better, since it can avoid the full scan on `b`.

```

mysql> EXPLAIN select o.* from o
    ->   where exists (select 1 from r inner join o1 on o1.a=r.a where r.b=o.b)
    -> order by o.b limit 1;
+--------------------------------------------+---------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
| id                                         | estRows | task      | access object        | operator info                                                                                                 |
+--------------------------------------------+---------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
| Limit_23                                   | 1.00    | root      |                      | offset:0, count:1                                                                                             |
| └─MergeJoin_101                            | 1.00    | root      |                      | semi join, left side:Projection_111, left key:test.o.b, right key:test.r.b                                    |
|   ├─IndexHashJoin_118(Build)               | 1.56    | root      |                      | inner join, inner:IndexReader_52, outer key:test.r.a, inner key:test.o1.a, equal cond:eq(test.r.a, test.o1.a) |
|   │ ├─Projection_123(Build)                | 1.25    | root      |                      | test.r.a, test.r.b                                                                                            |
|   │ │ └─IndexLookUp_122                    | 1.25    | root      |                      |                                                                                                               |
|   │ │   ├─IndexFullScan_119(Build)         | 101.14  | cop[tikv] | table:r, index:b(b)  | keep order:true, stats:pseudo                                                                                 |
|   │ │   └─Selection_121(Probe)             | 1.25    | cop[tikv] |                      | not(isnull(test.r.a))                                                                                         |
|   │ │     └─TableRowIDScan_120             | 101.14  | cop[tikv] | table:r              | keep order:false, stats:pseudo                                                                                |
|   │ └─IndexReader_52(Probe)                | 1.56    | root      |                      | index:Selection_51                                                                                            |
|   │   └─Selection_51                       | 1.56    | cop[tikv] |                      | not(isnull(test.o1.a))                                                                                        |
|   │     └─IndexRangeScan_50                | 1.56    | cop[tikv] | table:o1, index:a(a) | range: decided by [eq(test.o1.a, test.r.a)], keep order:false, stats:pseudo                                   |
|   └─Projection_111(Probe)                  | 1.25    | root      |                      | test.o.a, test.o.b, test.o.c, test.o.d                                                                        |
|     └─IndexLookUp_110                      | 1.25    | root      |                      |                                                                                                               |
|       ├─IndexFullScan_108(Build)           | 1.25    | cop[tikv] | table:o, index:b(b)  | keep order:true, stats:pseudo                                                                                 |
|       └─TableRowIDScan_109(Probe)          | 1.25    | cop[tikv] | table:o              | keep order:false, stats:pseudo                                                                                |
+--------------------------------------------+---------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+

mysql> EXPLAIN select o.* from o
    ->   where exists (select /*+ NO_DECORRELATE() */ 1 from r inner join o1 on o1.a=r.a where r.b=o.b)
    -> order by o.b limit 1;
+------------------------------------------+----------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
| id                                       | estRows  | task      | access object        | operator info                                                                                                 |
+------------------------------------------+----------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
| TopN_22                                  | 1.00     | root      |                      | test.o.b, offset:0, count:1                                                                                   |
| └─Apply_28                               | 10000.00 | root      |                      | CARTESIAN semi join, left side:TableReader_30                                                                 |
|   ├─TableReader_30(Build)                | 10000.00 | root      |                      | data:TableFullScan_29                                                                                         |
|   │ └─TableFullScan_29                   | 10000.00 | cop[tikv] | table:o              | keep order:false, stats:pseudo                                                                                |
|   └─Limit_33(Probe)                      | 10000.00 | root      |                      | offset:0, count:1                                                                                             |
|     └─IndexHashJoin_42                   | 10000.00 | root      |                      | inner join, inner:IndexReader_71, outer key:test.r.a, inner key:test.o1.a, equal cond:eq(test.r.a, test.o1.a) |
|       ├─IndexLookUp_68(Build)            | 8000.00  | root      |                      |                                                                                                               |
|       │ ├─IndexRangeScan_65(Build)       | 8927.93  | cop[tikv] | table:r, index:b(b)  | range: decided by [eq(test.r.b, test.o.b)], keep order:false, stats:pseudo                                    |
|       │ └─Selection_67(Probe)            | 8000.00  | cop[tikv] |                      | not(isnull(test.r.a))                                                                                         |
|       │   └─TableRowIDScan_66            | 8927.93  | cop[tikv] | table:r              | keep order:false, stats:pseudo                                                                                |
|       └─IndexReader_71(Probe)            | 10000.00 | root      |                      | index:Selection_70                                                                                            |
|         └─Selection_70                   | 10000.00 | cop[tikv] |                      | not(isnull(test.o1.a))                                                                                        |
|           └─IndexRangeScan_69            | 10010.01 | cop[tikv] | table:o1, index:a(a) | range: decided by [eq(test.o1.a, test.r.a)], keep order:false, stats:pseudo                                   |
+------------------------------------------+----------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
```

`Explain Explore` should consider whether to decorrelate sub-queries to find potential optimal plans.
A quick solution could be enumerate `NO_DECORRELATE()` hint with query block number:
```
mysql> EXPLAIN select /*+ NO_DECORRELATE(@sel_2) */ o.* from o
    ->   where exists (select 1 from r inner join o1 on o1.a=r.a where r.b=o.b)
    ->   order by o.b limit 1;
+------------------------------------------+----------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
| id                                       | estRows  | task      | access object        | operator info                                                                                                 |
+------------------------------------------+----------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
| TopN_22                                  | 1.00     | root      |                      | test.o.b, offset:0, count:1                                                                                   |
| └─Apply_28                               | 10000.00 | root      |                      | CARTESIAN semi join, left side:TableReader_30                                                                 |
|   ├─TableReader_30(Build)                | 10000.00 | root      |                      | data:TableFullScan_29                                                                                         |
|   │ └─TableFullScan_29                   | 10000.00 | cop[tikv] | table:o              | keep order:false, stats:pseudo                                                                                |
|   └─Limit_33(Probe)                      | 10000.00 | root      |                      | offset:0, count:1                                                                                             |
|     └─IndexHashJoin_42                   | 10000.00 | root      |                      | inner join, inner:IndexReader_71, outer key:test.r.a, inner key:test.o1.a, equal cond:eq(test.r.a, test.o1.a) |
|       ├─IndexLookUp_68(Build)            | 8000.00  | root      |                      |                                                                                                               |
|       │ ├─IndexRangeScan_65(Build)       | 8927.93  | cop[tikv] | table:r, index:b(b)  | range: decided by [eq(test.r.b, test.o.b)], keep order:false, stats:pseudo                                    |
|       │ └─Selection_67(Probe)            | 8000.00  | cop[tikv] |                      | not(isnull(test.r.a))                                                                                         |
|       │   └─TableRowIDScan_66            | 8927.93  | cop[tikv] | table:r              | keep order:false, stats:pseudo                                                                                |
|       └─IndexReader_71(Probe)            | 10000.00 | root      |                      | index:Selection_70                                                                                            |
|         └─Selection_70                   | 10000.00 | cop[tikv] |                      | not(isnull(test.o1.a))                                                                                        |
|           └─IndexRangeScan_69            | 10010.01 | cop[tikv] | table:o1, index:a(a) | range: decided by [eq(test.o1.a, test.r.a)], keep order:false, stats:pseudo                                   |
+------------------------------------------+----------+-----------+----------------------+---------------------------------------------------------------------------------------------------------------+
```

### LINKED ISSUE #66041: supplement limited operator should follow it's child's offset
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Image

### 2. What did you expect to see? (Required)
Added limit for exist query's (apply's inner child) should follow the offset it has, rather than inherit the offset from outer plan builder.
Otherwise, when we gen hint from constructed plan, we will generate no_decorreate(@sel_2) and never get it to work. 

### 3. What did you see instead (Required)
we can generate correct hint as. no_decorreate(@sel_2)

### 4. What is your TiDB version? (Required)

master

### LINKED ISSUE #66044: planner: EXPLAIN EXPLORE should emit NO_DECORRELATE hint
## Enhancement
EXPLAIN EXPLORE misses NO_DECORRELATE(@sel_x) hints when a plan keeps Apply due to NO_DECORRELATE, so generated bindings may not reproduce non-decorrelated plans.

Expected: when PhysicalApply is preserved with no_decorrelate, EXPLAIN EXPLORE should emit NO_DECORRELATE with the inner query block.

### PR DESCRIPTION
**Pull request by AilinKid**
### What problem does this PR solve?

Issue Number: close #65986, close #66041, close #66044

Problem Summary:
EXPLAIN EXPLORE did not emit NO_DECORRELATE(@sel_x) for plans that keep Apply due to NO_DECORRELATE, so generated bindings could not reproduce non-decorrelated plans.

### What changed and how does it work?
- Propagate NoDecorrelate from LogicalApply to PhysicalApply.
- Emit NO_DECORRELATE(@sel_x) in GenHintsFromSingle when PhysicalApply carries NoDecorrelate.
- Enumerate NO_DECORRELATE query blocks during explore generation (skipping the top-level QB) and keep the hint in generated bindings if the plan hints do not include it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/bindinfo/binding_plan_generation.go [hunk 1]
```diff
@@ -136,10 +136,12 @@ func (gp *genedPlan) PlanText() string {
 type state struct {
 	leading2   [2]*tableName // leading-2 table names
 	indexHints []*indexHint  // optional index hints per table
-	varNames   []string      // relevant variables and their values to generate a certain plan
-	varValues  []any
-	fixIDs     []uint64 // relevant fixes and their values to generate a certain plan
-	fixValues  []string
+	// noDecorrelateQB stores the query block name for NO_DECORRELATE() hint.
+	noDecorrelateQB ast.CIStr
```
Comment (qw4990) [inline pkg/bindinfo/binding_plan_generation.go:140]: If there are multiple sub-queries, should we be able to enumerate different combinations of them? For example, if there are 2 sub-queries, there should be 4 combinations: `no_dec(sel_2), no_dec(sel_3)`, `no_dec(sel_2)`, `no_dec(sel_3)`, ` (just empty, decorrelate them both) `. 
But this could make our code much more complex, we can leave this as a further optimization.

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/core/operator/physicalop/physical_apply.go [hunk 2]
```diff
@@ -33,6 +33,8 @@ type PhysicalApply struct {
 	CanUseCache bool
 	Concurrency int
 	OuterSchema []*expression.CorrelatedColumn
+	// NoDecorrelate indicates this apply is preserved by NO_DECORRELATE hint.
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/physicalop/physical_apply.go]:
```suggestion
	// NoDecorrelate is used to flag that an Apply operator remained undecorrelated due to the no_decorrelate hint exists. This allows the EXPLAIN EXPLORE feature to know exactly when to suggest adding a no_decorrelate hint when reverse-generating the sql recommended hints from the physical plan tree."
```

File: pkg/bindinfo/binding_plan_generation.go [hunk 3]
```diff
@@ -669,6 +770,40 @@ func extractSelectTableNames(defaultSchema string, node ast.StmtNode) []*tableNa
...
+		}
+		qbName, err := hint.GenerateQBName(hint.TypeSelect, offset)
+		if err != nil {
+			continue
+		}
+		qbNames = append(qbNames, qbName)
+	}
+	sort.Slice(qbNames, func(i, j int) bool {
+		return qbNames[i].L < qbNames[j].L
+	})
```
Comment (guo-shaoge) [inline pkg/bindinfo/binding_plan_generation.go:803]: looks like we will also generate hint for NON-Decorralted subquery, which is useless to explore.

Comment (guo-shaoge) [reply pkg/bindinfo/binding_plan_generation.go:803]: Maybe we can improve in the future.

Comment (AilinKid) [reply pkg/bindinfo/binding_plan_generation.go:803]: for unnecessary select query block enumeration? yes

**Review by hawkingrei — APPROVED** [review]
