### PR TITLE
planner: generate addition selection when plan cache enable

### LINKED ISSUE #28259: prepared-plan-cache: return wrong result using bigint column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepared-plan-cache.enable = true
```sql
use test;
drop table if exists UK_GCOL_VIRTUAL_18588;
CREATE TABLE `UK_GCOL_VIRTUAL_18588` (
  `COL1` bigint(20),
  UNIQUE KEY `UK_COL1` (`COL1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into UK_GCOL_VIRTUAL_18588 values("8502658334322817163");
prepare stmt from 'select col1 from UK_GCOL_VIRTUAL_18588 where col1 between ? and ? or col1 < ?';
set @a=5516958330762833919, @b=8551969118506051323, @c=2887622822023883594;
execute stmt using @a,@b,@c;
set @a=-1696020282760139948, @b=-2619168038882941276, @c=-4004648990067362699;
execute stmt using @a,@b,@c;
select col1 from UK_GCOL_VIRTUAL_18588 where col1 between -1696020282760139948 and -2619168038882941276 or col1 < -4004648990067362699;
```

### 2. What did you expect to see? (Required)
release-4.0 & release-5.0
```
mysql> execute stmt using @a,@b,@c;
Empty set (0.00 sec)

mysql> select col1 from UK_GCOL_VIRTUAL_18588 where col1 between -1696020282760139948 and -2619168038882941276 or col1 < -4004648990067362699;
Empty set (0.00 sec)
```
### 3. What did you see instead (Required)
release-5.1 & release-5.2 & master
```
mysql> execute stmt using @a,@b,@c;
+---------------------+
| col1                |
+---------------------+
| 8502658334322817163 |
+---------------------+
1 row in set (0.00 sec)

mysql> select col1 from UK_GCOL_VIRTUAL_18588 where col1 between -1696020282760139948 and -2619168038882941276 or col1 < -4004648990067362699;
Empty set (0.00 sec)

```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.1-58-gdc079337e
Edition: Community
Git Commit Hash: dc079337ef0c9d78eec2d2acb1eb31e12117d29b
Git Branch: release-5.1
UTC Build Time: 2021-09-22 02:01:55
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close #28259 

Problem Summary:
When plan cache is available, we may eliminate Selection when generating RangeScan, but it will cause errors when parameter values are changed.

### What is changed and how it works?
Add the eliminated selection.

### Check List 

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
'None'
```

### CODE REVIEW

File: planner/core/find_best_task.go [hunk 1]
```diff
@@ -1629,6 +1631,18 @@ func getMostCorrCol4Index(path *util.AccessPath, histColl *statistics.Table, thr
 	return nil, corr
 }
 
+// keepAccessCondsAsFilter4TablePlan is used to keep the access conditions as
+// filter conditions when the following conditions are met:
+// 1. Filter conditions are nil.
+// 2. Access conditions satisfies the conditions of the MaybeOverOptimized4PlanCache function.
+func keepAccessCondsAsFilter4TablePlan(ctx sessionctx.Context, access_conds []expression.Expression, filter_conds []expression.Expression) []expression.Expression {
```
Comment (Reminiscent) [inline planner/core/find_best_task.go:1638]: The name can be optimized. Any suggestions? @qw4990

File: executor/explainfor_test.go [hunk 2]
```diff
@@ -568,3 +568,56 @@ func (s *testPrepareSerialSuite) TestExpressionIndexPreparePlanCache(c *C) {
 	c.Assert(res.Rows()[2][3], Matches, ".*expression_index.*")
 	c.Assert(res.Rows()[2][4], Matches, ".*[1234,1234].*")
 }
+
+func (s *testPrepareSerialSuite) TestIssue28259(c *C) {
```
Comment (Reminiscent) [inline executor/explainfor_test.go:572]: Need to add more test cases.

File: planner/core/find_best_task.go [hunk 3]
```diff
@@ -1342,6 +1343,7 @@ func (is *PhysicalIndexScan) initSchema(idxExprCols []*expression.Column, isDoub
 func (is *PhysicalIndexScan) addPushedDownSelection(copTask *copTask, p *DataSource, path *util.AccessPath, finalStats *property.StatsInfo) {
 	// Add filter condition to table plan now.
 	indexConds, tableConds := path.IndexFilters, path.TableFilters
```
Comment (Reminiscent) [inline planner/core/find_best_task.go:1345]: Need to consider the `tableConds`.

File: planner/core/prepare_test.go [hunk 4]
```diff
@@ -191,7 +191,7 @@ func (s *testPlanSerialSuite) TestPrepareCacheDeferredFunction(c *C) {
 	tk.MustExec("prepare sel1 from 'select id, c1 from t1 where c1 < now(3)'")
 
 	sql1 := "execute sel1"
-	expectedPattern := `IndexReader\(Index\(t1.idx1\)\[\[-inf,[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9][0-9][0-9]\)\]\)`
+	expectedPattern := `IndexReader\(Index\(t1.idx1\)\[\[-inf,[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9][0-9][0-9]\)\]\)->Sel\(\[lt\(test.t1.c1, now\(3\)\)\]\)\)`
```
Comment (Reminiscent) [inline planner/core/prepare_test.go:194]: May got the wrong result because of `now(3)` is non-deterministic functions.

File: planner/core/find_best_task.go [hunk 5]
```diff
@@ -1629,6 +1631,19 @@ func getMostCorrCol4Index(path *util.AccessPath, histColl *statistics.Table, thr
 	return nil, corr
 }
 
+// keepAccessCondsAsFilter4TablePlan is used to keep the access conditions as
+// filter conditions when the following conditions are met:
+// 1. Filter conditions are nil.
+// 2. Access conditions satisfies the conditions of the
+// MaybeOverOptimized4PlanCache function.
+func keepAccessCondsAsFilter4TablePlan(ctx sessionctx.Context, accessConds []expression.Expression, filterConds []expression.Expression) []expression.Expression {
```
Comment (qw4990) [inline planner/core/find_best_task.go:1639]: How about `keepAccessCondsAsFilter4PlanCache`?
For all particular functions for plan cache, we use `4PlanCache` as their suffix.

File: planner/core/find_best_task.go [hunk 6]
```diff
@@ -1935,6 +1950,7 @@ func (ds *DataSource) convertToBatchPointGet(prop *property.PhysicalProperty, ca
 }
 
 func (ts *PhysicalTableScan) addPushedDownSelectionToMppTask(mpp *mppTask, stats *property.StatsInfo) *mppTask {
+	ts.filterCondition = keepAccessCondsAsFilter4TablePlan(ts.ctx, ts.AccessCondition, ts.filterCondition)
```
Comment (qw4990) [inline planner/core/find_best_task.go:1953]: We do not cache plans accessing TiFlash, so this action can be omitted here?

File: planner/core/find_best_task.go [hunk 7]
```diff
@@ -1629,6 +1631,19 @@ func getMostCorrCol4Index(path *util.AccessPath, histColl *statistics.Table, thr
 	return nil, corr
 }
 
+// keepAccessCondsAsFilter4PlanCache is used to keep the access conditions as
+// filter conditions when the following conditions are met:
+// 1. Access conditions contains the lazy constant, see the MaybeOverOptimized4PlanCache
+// function for more details.
+func keepAccessCondsAsFilter4PlanCache(ctx sessionctx.Context, accessConds []expression.Expression, filterConds []expression.Expression) []expression.Expression {
```
Comment (qw4990) [inline planner/core/find_best_task.go:1638]: Please add an example in its comment.

**Review by qw4990 — APPROVED** [review]

**Review by rebelice — APPROVED** [review]
