### PR TITLE
executor: remove redundant memory pre-allocations in parallel sort executor

### LINKED ISSUE #54070: PR#53537 caused 20-34% performance regression in oltp_read_only and oltp_read_write
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster with 3 tidb and 3 tikv
2. run sysbench oltp_read_only and oltp_read_write with pr #53341 and  #53537

### 2. What did you expect to see? (Required)
No regression.

### 3. What did you see instead (Required)
PR#53537 caused performance regression in oltp_read_only (34%) and oltp_read_write(20%)
image

### 4. What is your TiDB version? (Required)

#53537

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #54070

Problem Summary:

### What changed and how does it work?

From clinic we can see that tidb memory usage is larger than normal and most of memory are allocated in sort executor. So we suspect that it's too many allocations which caused the performance regression.
mem-cmp
memory

To verify our suspicion we check the cpu usage and find that most cpu are consumed by memory allocation in sort executor. Moreover, GC STW Duration is very high. So I think we can ensure that it's too memory allocation who causes the performance regression in benchbot.
cpu
stw

In order to eliminate the memory re-allocation when slice expands, we set a large capacity when creating slices. However, It's a waste to reserving so many memory and wasted memory will be very large because tp sqls usually process few rows while sort executos will be created for many times(showed in the following picture). So I think we can remove the pre-allocation in sort executor to fix this regression. I think this fix will not have a strong impact on sort performance because main bottleneck in parallel sort is io, not memory allocation.
sort

With this pr, performance regression is fixed.

fixed:
BenchmarkUnionScanTableReadDescRead:
1863      618281 ns/op    148918 B/op     2677 allocs/op
BenchmarkUnionScanIndexReadDescRead:
1922      620293 ns/op    153910 B/op     2750 allocs/op
BenchmarkUnionScanIndexLookUpDescRead:
1744      673479 ns/op    248234 B/op     2820 allocs/op

master:
BenchmarkUnionScanTableReadDescRead:
1826      599392 ns/op    215502 B/op     2674 allocs/op
BenchmarkUnionScanIndexReadDescRead:
1964      593482 ns/op    219032 B/op     2740 allocs/op
BenchmarkUnionScanIndexLookUpDescRead:
1791      659653 ns/op    320267 B/op     2815 allocs/op

dataset: tpch10
sql1: explain analyze select L_COMMENT, L_EXTENDEDPRICE from lineitem where L_SUPPKEY > 95000 order by L_COMMENT desc, L_EXTENDEDPRICE asc;

sql2: explain analyze select * from lineitem where L_SUPPKEY > 95000 order by L_COMMENT desc, L_EXTENDEDPRICE asc;

  | Sql1 | Sql2
-- | -- | --
Master | 7.30s | 15.36s
Fixed | 6.94s | 16.36s

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Remove redundant memory pre-allocations in parallel sort executor
```

### CODE REVIEW

File: pkg/executor/sortexec/parallel_sort_worker.go [hunk 1]
```diff
@@ -73,9 +72,9 @@ func newParallelSortWorker(
 		timesOfRowCompare:      0,
 		memTracker:             memTracker,
 		sortedRowsIter:         sortedRowsIter,
-		maxSortedRowsLimit:     maxSortedRowsLimit,
+		maxSortedRowsLimit:     maxChunkSize * 30,
 		spillHelper:            spillHelper,
-		batchRows:              make([]chunk.Row, 0, maxSortedRowsLimit),
+		batchRows:              make([]chunk.Row, 0),
```
Comment (hawkingrei) [inline pkg/executor/sortexec/parallel_sort_worker.go:77]: Can you add some benchmarks for it?

Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_worker.go:77]: > Can you add some benchmarks for it?

parallel sort benchmark?

Comment (hawkingrei) [reply pkg/executor/sortexec/parallel_sort_worker.go:77]: Yes, BTW can you check ```BenchmarkUnionScanTableReadDescRead```， ```BenchmarkUnionScanIndexReadDescRead``` and ```BenchmarkUnionScanIndexLookUpDescRead``` wich can test for parallel sort?

**Review by zanmato1984 — COMMENTED** [review]
Could you update the PR description by adding how the performance regression is introduced and how this fixes it?

**Comment by xzhangxian1008** [comment]
> ### What problem does this PR solve?
> Issue Number: close #54070
> 
> Problem Summary:
> 
> ### What changed and how does it work?
> ### Check List
> Tests
> 
> * [x]  Unit test
> * [ ]  Integration test
> * [ ]  Manual test (add detailed scripts or steps below)
> * [ ]  No need to test
>   > * [ ]  I checked and no code files have been changed.
> 
> Side effects
> 
> * [ ]  Performance regression: Consumes more CPU
> * [ ]  Performance regression: Consumes more Memory
> * [ ]  Breaking backward compatibility
> 
> Documentation
> 
> * [ ]  Affects user behaviors
> * [ ]  Contains syntax changes
> * [ ]  Contains variable changes
> * [ ]  Contains experimental features
> * [ ]  Changes MySQL compatibility
> 
> ### Release note
> Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.
> 
> ```
> Remove redundant memory pre-allocations in parallel sort executor
> ```



> Could you update the PR description by adding how the performance regression is introduced and how this fixes it?

updated

**Comment by xzhangxian1008** [comment]
> Could you update the PR description by adding how the performance regression is introduced and how this fixes it?

updated

File: pkg/executor/sortexec/parallel_sort_worker.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_worker.go:77]: > Yes, BTW can you check `BenchmarkUnionScanTableReadDescRead`， `BenchmarkUnionScanIndexReadDescRead` and `BenchmarkUnionScanIndexLookUpDescRead` wich can test for parallel sort?

okk

Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_worker.go:77]: > Yes, BTW can you check `BenchmarkUnionScanTableReadDescRead`， `BenchmarkUnionScanIndexReadDescRead` and `BenchmarkUnionScanIndexLookUpDescRead` wich can test for parallel sort?

fixed:
BenchmarkUnionScanTableReadDescRead:
1863      618281 ns/op    148918 B/op     2677 allocs/op
BenchmarkUnionScanIndexReadDescRead:
1922      620293 ns/op    153910 B/op     2750 allocs/op
BenchmarkUnionScanIndexLookUpDescRead:
1744      673479 ns/op    248234 B/op     2820 allocs/op

master:
BenchmarkUnionScanTableReadDescRead:
1826      599392 ns/op    215502 B/op     2674 allocs/op
BenchmarkUnionScanIndexReadDescRead:
1964      593482 ns/op    219032 B/op     2740 allocs/op
BenchmarkUnionScanIndexLookUpDescRead:
1791      659653 ns/op    320267 B/op     2815 allocs/op

dataset: tpch10
sql1: explain analyze select L_COMMENT, L_EXTENDEDPRICE from lineitem where L_SUPPKEY > 95000 order by L_COMMENT desc, L_EXTENDEDPRICE asc;

sql2: explain analyze select * from lineitem where L_SUPPKEY > 95000 order by L_COMMENT desc, L_EXTENDEDPRICE asc;

  | Sql1 | Sql2
-- | -- | --
Master | 7.30s | 15.36s
Fixed | 6.94s | 16.36s

Comment (hawkingrei) [reply pkg/executor/sortexec/parallel_sort_worker.go:77]: add it to PR's description.

Comment (hawkingrei) [inline pkg/executor/sortexec/parallel_sort_worker.go:77]: You should set a small init size unless slices have to resize.

File: pkg/executor/sortexec/parallel_sort_worker.go [hunk 2]
```diff
@@ -129,7 +128,7 @@ func (p *parallelSortWorker) multiWayMergeLocalSortedRows() ([]chunk.Row, error)
 func (p *parallelSortWorker) sortBatchRows() {
 	slices.SortFunc(p.batchRows, p.keyColumnsLess)
 	p.localSortedRows = append(p.localSortedRows, chunk.NewIterator4Slice(p.batchRows))
-	p.batchRows = make([]chunk.Row, 0, p.maxSortedRowsLimit)
+	p.batchRows = make([]chunk.Row, 0)
```
Comment (hawkingrei) [inline pkg/executor/sortexec/parallel_sort_worker.go:131]: ditto

**Comment by windtalker** [comment]
How about we just save the orignal `chunk` in `addChunkToBatchRows`, and only construct the `batchRows` before `sortBatchRows`? So in `sortBatchRows` we already know the row size, and can pre-allocate it without waste.

**Comment by xzhangxian1008** [comment]
> How about we just save the orignal `chunk` in `addChunkToBatchRows`, and only construct the `batchRows` before `sortBatchRows`? So in `sortBatchRows` we already know the row size, and can pre-allocate it without waste.

I think this is very good.

File: pkg/executor/sortexec/parallel_sort_worker.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_worker.go:79]: > You should set a small init size unless slices have to resize.

We don't need to reserve small init size any more as I save chunks and pre-allocate whole memory before sort.

File: pkg/executor/sortexec/parallel_sort_worker.go (hunk 2 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_worker.go]: > ditto

dito

**Comment by xzhangxian1008** [comment]
> How about we just save the orignal `chunk` in `addChunkToBatchRows`, and only construct the `batchRows` before `sortBatchRows`? So in `sortBatchRows` we already know the row size, and can pre-allocate it without waste.

done

File: pkg/executor/sortexec/parallel_sort_worker.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_worker.go:79]: > add it to PR's description.

done

File: pkg/executor/sortexec/parallel_sort_worker.go [hunk 3]
```diff
@@ -126,28 +127,39 @@ func (p *parallelSortWorker) multiWayMergeLocalSortedRows() ([]chunk.Row, error)
 	return resultSortedRows, nil
 }
 
+func (p *parallelSortWorker) fillBatchRows() {
+	p.batchRows = make([]chunk.Row, 0, p.rowNumInChunkIters)
```
[the remark this answers is not in the document]
Comment (xzhangxian1008) [reply pkg/executor/sortexec/parallel_sort_worker.go]: > Looks like if `fillBatchRows` returns `batchRows`, then there is no need to make `batchRows` as a variable of `parallelSortWorker`?

I have deleted it.

**Review by windtalker — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]
