### PR TITLE
session: fix the problem that lost connection in the next sql after out of memory quota

### LINKED ISSUE #18540: memory_quota: lost connection in the next sql after out of memory quota
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

oom-action=cancel
```
drop table if exists t;
create table t(a int);
insert into t values(1), (-1), (0);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert /*+ memory_quota(1 MB) */ into t select * from t;
insert /*+ memory_quota(2 MB) */ into t select * from t;
insert /*+ memory_quota(14 MB) */ into t select * from t;
insert /*+ memory_quota(15 MB) */ into t select * from t;
select count(*) from t;
```

### 2. What did you expect to see? (Required)
```
mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
|   393216 |
+----------+
1 row in set (3.38 sec)
```
### 3. What did you see instead (Required)
```
mysql> select count(*) from t;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
### 4. Affected version (Required)

```
Release Version: v4.0.2-23-g89e34b707
Edition: Community
Git Commit Hash: 89e34b707fdfeb1bcac5b3ecd13f5614bd2f0291
Git Branch: release-4.0
UTC Build Time: 2020-07-14 06:30:07
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by xiaodong-ji**
### What problem does this PR solve?

Issue Number: close #18540

Problem Summary:
lost connection in the next sql after out of memory quota

### What is changed and how it works?

What's Changed:
Add recover function in `runStmt` to avoid losing connection.

### Check List

Tests

- Manual test
```
drop table if exists t;
create table t(a int);
insert into t values(1), (-1), (0);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert /*+ memory_quota(1 MB) */ into t select * from t;
insert /*+ memory_quota(2 MB) */ into t select * from t;
insert /*+ memory_quota(14 MB) */ into t select * from t;
insert /*+ memory_quota(15 MB) */ into t select * from t;
tidb> select count(*) from t;
+----------+
| count(*) |
+----------+
|   393216 |
+----------+
1 row in set (0.03 sec)
```

### Release note
- Fix lost connection in the next sql after out of memory quota.

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by bobotu** [comment]
Maybe you should do something like https://github.com/pingcap/tidb/blob/9e5e2a933e8f311899d8594f3310c59770092fa8/session/txn.go#L534-L537

**Comment by xiaodong-ji** [comment]
> Maybe you should do something like
> 
> https://github.com/pingcap/tidb/blob/9e5e2a933e8f311899d8594f3310c59770092fa8/session/txn.go#L534-L537

@bobotu Thank you very much for your advice, I tried to recreate this process using transactions, as follows:
```
drop table if exists t;
create table t(a int);
begin;
insert into t values(1), (-1), (0);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert /*+ memory_quota(1 MB) */ into t select * from t;
insert /*+ memory_quota(2 MB) */ into t select * from t;
insert /*+ memory_quota(14 MB) */ into t select * from t;
insert /*+ memory_quota(15 MB) */ into t select * from t;
commit;
tidb> select count(*) from t;
+----------+
| count(*) |
+----------+
|   393216 |
+----------+
1 row in set (0.06 sec)
```

File: session/session.go [hunk 1]
```diff
@@ -1180,6 +1181,16 @@ func (s *session) ExecuteStmt(ctx context.Context, stmtNode ast.StmtNode) (sqlex
 
 // runStmt executes the sqlexec.Statement and commit or rollback the current transaction.
 func runStmt(ctx context.Context, se *session, s sqlexec.Statement) (rs sqlexec.RecordSet, err error) {
+	defer func() {
+		r := recover()
+		if r != nil {
+			if str, ok := r.(string); !ok || !strings.HasPrefix(str, memory.PanicMemoryExceed) {
+				panic(r)
+			}
+			err = errors.Errorf("%v", r)
```
Comment (bobotu) [inline session/session.go:1190]: We should use 

```go
if !s.IsReadOnly(sessVars) && se.txn.Valid() {
	se.StmtRollback()
}
```
to keep transaction states clean.

We also need a `recover` in https://github.com/pingcap/tidb/blob/d941ff5cc8b4babf9dcfdd91b66a5c53b798c122/session/txn.go#L513-L523. The logical is.

```go
func (s *session) StmtCommit(memTracker *memory.Tracker) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = errors.Errorf("%v", r)
			st.doNotCommit = err
		}
		if err == nil && memTracker != nil {
			memTracker.Consume(int64(-s.txn.Size()))
		}
		s.txn.cleanup()
	}()
// Others...
}
```

Comment (bobotu) [reply session/session.go:1190]: PTAL @tiancaiamao

Comment (XuHuaiyu) [reply session/session.go:1190]: If we recover in `stmtCommit`, it seems that we do not need to recover in `runStmt`.

File: session/session.go [hunk 2]
```diff
@@ -1203,6 +1203,11 @@ func runStmt(ctx context.Context, se *session, s sqlexec.Statement) (rs sqlexec.
 	rs, err = s.Exec(ctx)
 	sessVars.TxnCtx.StatementCount++
 	if !s.IsReadOnly(sessVars) {
+		// Handle the stmt panic in a transaction.
+		if err != nil {
+			se.txn.doNotCommit = err
+		}
+
```
Comment (xiaodong-ji) [inline session/session.go:1210]: @bobotu @XuHuaiyu 
I've tested it in transaction or non-transaction, it works.
```
// with transaction
drop table if exists t;
create table t(a int);
begin;
insert into t values(1), (-1), (0);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
tidb> insert /*+ memory_quota(1 MB) */ into t select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> insert /*+ memory_quota(2 MB) */ into t select * from t;
ERROR 1105 (HY000): current transaction is aborted, commands ignored until end of transaction block:Out Of Memory Quota![conn_id=1]
tidb> insert /*+ memory_quota(14 MB) */ into t select * from t;
ERROR 1105 (HY000): current transaction is aborted, commands ignored until end of transaction block:Out Of Memory Quota![conn_id=1]
tidb> insert /*+ memory_quota(15 MB) */ into t select * from t;
ERROR 1105 (HY000): current transaction is aborted, commands ignored until end of transaction block:Out Of Memory Quota![conn_id=1]
tidb> commit;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> select count(*) from t;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)


// without transaction
drop table if exists t;
create table t(a int);
insert into t values(1), (-1), (0);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
tidb> insert /*+ memory_quota(1 MB) */ into t select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> insert /*+ memory_quota(2 MB) */ into t select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> insert /*+ memory_quota(14 MB) */ into t select * from t;
Query OK, 393216 rows affected (1.62 sec)
Records: 393216  Duplicates: 0  Warnings: 0
tidb> insert /*+ memory_quota(15 MB) */ into t select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> select count(*) from t;
+----------+
| count(*) |
+----------+
|   786432 |
+----------+
1 row in set (0.09 sec)
```

**Comment by xiaodong-ji** [comment]
@ti-srebot/run-all-tests

**Comment by xiaodong-ji** [comment]
@ti-srebot/run-all-tests

File: session/session.go (hunk 2 above)
Comment (XuHuaiyu) [reply session/session.go:1210]: You may follow @bobotu 's suggestion that recovers in `stmtCommit`

Comment (bobotu) [reply session/session.go:1210]: This change is incorrect. This will invalidate all transactions even it is valid. The correct way to fix the original issue is add `recover` in `StmtCommit`.

File: session/txn.go [hunk 3]
```diff
@@ -516,6 +516,11 @@ func (s *session) StmtCommit(memTracker *memory.Tracker) error {
 		// in memTracker to avoid double-counting. If it's not batch mode, this
 		// work has no effect because that no more data will be appended into
 		// s.txn.
+
+		if r := recover(); r != nil {
+			err := errors.Errorf("%v", r)
+			s.txn.doNotCommit = err
+		}
```
Comment (xiaodong-ji) [inline session/txn.go:523]: @bobotu @XuHuaiyu
The problem remains.
```
drop table if exists t;
create table t(a int);
begin;
insert into t values(1), (-1), (0);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
tidb> insert /*+ memory_quota(1 MB) */ into t select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> insert /*+ memory_quota(2 MB) */ into t select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> insert /*+ memory_quota(14 MB) */ into t select * from t;
Query OK, 393216 rows affected (1.60 sec)
Records: 393216  Duplicates: 0  Warnings: 0
tidb> insert /*+ memory_quota(15 MB) */ into t select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]
tidb> commit;
Query OK, 0 rows affected (1.04 sec)

mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
|   786432 |
+----------+
1 row in set (0.07 sec)
```

Comment (bobotu) [reply session/txn.go:523]: You need to change the definition of `StmtCommit` to 

```go
func (s *session) StmtCommit(memTracker *memory.Tracker) (err error)
```

Then add change the code you added to

```go
if r := recover(); r != nil {
	err = errors.Errorf("%v", r)
	s.txn.doNotCommit = err
}
```

Comment (bobotu) [reply session/txn.go:523]: We need to return an error to the caller.

**Comment by bobotu** [comment]
After https://github.com/pingcap/tidb/pull/15931, we use in-place merge instead of copy-and-insert to flush `stmtBuf` into `txnBuf`. So it is unnecessary to use `MemTracker` in `StmtCommit`.

@xiaodong-ji You simply remove `memTracker` in `StmtCommit`.

**Comment by xiaodong-ji** [comment]
> After #15931, we use in-place merge instead of copy-and-insert to flush `stmtBuf` into `txnBuf`. So it is unnecessary to use `MemTracker` in `StmtCommit`.
> 
> @xiaodong-ji You can simply remove `memTracker` in `StmtCommit`.

@bobotu Thank you for your answer, I still have some questions.
1. The current problem is that the transaction is not rollback after a statement panic in the transaction.
2. What I understand is because `s.Exec` in the `session.go` has already handled panic, so `StmtCommit` in the `txn.go` will no longer receive an exception.
3. Where should we rollback the transaction, my attempts are shown below, but it didn't pass the Jenkins test.
```
// Handle the stmt commit/rollback.
if se.txn.Valid() {
	if err != nil {
		se.txn.doNotCommit = err
	} else {
		err = se.StmtCommit(sessVars.StmtCtx.MemTracker)
	}
}
```
4. What problem did you answer `You can simply remove memTracker in StmtCommit` to solve. ❤️

**Comment by bobotu** [comment]
>  3. Where should we rollback the transaction, my attempts are shown below, but it didn't pass the Jenkins test.

We have already rollback statements here.

https://github.com/pingcap/tidb/blob/f5c6e59f0daf2c297b4ee8cd4fc08e1423257438/session/session.go#L1203-L1215

`se.txn.doNotCommit = err` means an `err` happened after something in statement buffer has merged into the final txn buffer. In this situation, we cannot revert the txn buffer to a clean state, so use this to mark this txn cannot commit.

If panic happened in `Exec`, all modification happens in `statement-level buffer`, we can safely revert all of the changes, this is what `StmtRollback` did.

>  1. What problem did you answer `You can simply remove memTracker in StmtCommit` to solve. ❤️

You what to fix https://github.com/pingcap/tidb/issues/18540, this issue is triggered by `Consume` in `StmtCommit`. There is two way to fix the **lost connection** problem: 

1. Add a `recover` in `StmtCommit`, convert `panic` into an `err`. Then set `txn.doNotCommit` to this `err` and **return** this `err` to caller.
	- You have tried it, but forget to **return err to caller**, so it cannot pass some tests
2. The use of `memTracker` in `StmtCommit` is based on the outdated assumption that `StmtCommit` makes a memory copy, causing an instantaneous increase in memory usage.
	- We do not do memory copy anymore for now.
	- The original usage has a large statistical error, resulting in the cancellation of queries that could have been executed successfully.
	- So I suggest you, **simply remove them in `StmtCommit`.

@xiaodong-ji
