### PR TITLE
session: Mising OptimizeWithPlanAndThenWarmUp in prepare-execute path

### LINKED ISSUE #36311: Refactoring of sessiontxn introduces extra TSO waits
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
func TestTSO(t *testing.T) {
	store, clean := testkit.CreateMockStore(t)
	defer clean()
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("drop table if exists t")
	tk.MustExec("create table t(id int, v int, primary key (id), key i1(v))")
	tk.MustExec("create table t2(id int, v int, primary key (id), key i1(v))")
	tk.MustExec("insert into t values (1, 1)")
	tk.MustExec("begin pessimistic")
	tk.MustExec("select * from t where id = 1 for update")
	tk.MustExec("update t set v = v + 1 where id = 1")
	tk.MustExec("insert into t2 values (1, 1)")
	tk.MustExec("commit")
}

```

### 2. What did you expect to see? (Required)

Before #35885, the test consists of 21 tso waits (that in `changePendingToValid`).

### 3. What did you see instead (Required)

With #35885, the test needs 91 tso waits.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What problem does this PR solve?

Issue Number: close #36311

Problem Summary:

### What is changed and how it works?

This PR solves the problem of extra tso cmd requests after the PR https://github.com/pingcap/tidb/pull/35158.

We have an optimization for not fetch tso from PD for `point get for update` related operations including operating includes them (update, delete and so on). However, it is missed in prepare-pattern. This PR supplements it.

Tso cmd request counts are not related to the correctness of the programme and have not been covered by the current unit tests. This PR also adds the related unit test to avoid similar mistakes in the future.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: session/session.go [hunk 1]
```diff
@@ -2267,6 +2267,9 @@ func (s *session) preparedStmtExec(ctx context.Context, execStmt *ast.ExecuteStm
 
 	is := sessiontxn.GetTxnManager(s).GetTxnInfoSchema()
 	st, tiFlashPushDown, tiFlashExchangePushDown, err := executor.CompileExecutePreparedStmt(ctx, s, execStmt, is)
+	if err == nil {
+		err = sessiontxn.OptimizeWithPlanAndThenWarmUp(s, st.Plan)
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply session/session.go:2271]: It's the same. In that way, we have to deal with another `if err != nil`.

File: sessiontxn/txn_context_test.go [hunk 2]
```diff
@@ -882,3 +883,91 @@ func TestOptimisticTxnRetryInPessimisticMode(t *testing.T) {
...
+	sqlInsertId2, _, _, _ := tk.Session().PrepareStmt("insert into t3 values(?, ?)")
+
+	tk.MustExec("insert into t1 values (1, 1, 1)")
+
+	for i := 1; i < 100; i++ {
+		tk.MustExec("begin pessimistic")
+		stmt, err := tk.Session().ExecutePreparedStmt(ctx, sqlSelectId, []types.Datum{types.NewDatum(1)})
+		require.NoError(t, err)
+		require.NoError(t, stmt.Close())
+		_, err = tk.Session().ExecutePreparedStmt(ctx, sqlUpdateId, []types.Datum{types.NewDatum(1)})
```
Comment (lcwangchao) [inline sessiontxn/txn_context_test.go:923]: You should close all rs returned by ExecutePreparedStmt

File: session/session.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (ekexium) [reply session/session.go:2271]: I think it would be more idiomatic?

File: sessiontxn/txn_context_test.go [hunk 3]
```diff
@@ -882,3 +883,91 @@ func TestOptimisticTxnRetryInPessimisticMode(t *testing.T) {
...
+	// Note, we do not record all tso requests but some typical requests.
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/sessiontxn/isolation/requestTsoFromPD", "return"))
+	store, clean := testkit.CreateMockStore(t)
+	defer clean()
+
+	ctx := context.Background()
+	tk := testkit.NewTestKit(t, store)
+
+	sctx := tk.Session()
+	sctx.SetValue(sessiontxn.TsoRequestCount, 0)
```
Comment (lcwangchao) [inline sessiontxn/txn_context_test.go:900]: Why not set the `TsoRequestCount` before loop, `117` in `require.Equal(t, uint64(117), count)` is a little harder to understand

**Review by lcwangchao — COMMENTED** [review]
Rest LGTM

File: session/session.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply session/session.go:2271]: Actually, it is written this way in text sql path in `ExecuteStmt`.

File: sessiontxn/txn_context_test.go (hunk 2 above)
Comment (SpadeA-Tang) [reply sessiontxn/txn_context_test.go:923]: Fine.

File: sessiontxn/txn_context_test.go [hunk 4]
```diff
@@ -882,3 +883,95 @@ func TestOptimisticTxnRetryInPessimisticMode(t *testing.T) {
...
+
+	require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/sessiontxn/isolation/requestTsoFromPD"))
+}
+
+func TestTSOCmdCountForTextSql(t *testing.T) {
+	// This is a mock workload mocks one which discovers that the tso request count is abnormal.
+	// After the bug fix, the tso request count recovers, so we use this workload to record the current tso request count
+	// to reject future works that accidentally causes tso request increasing.
+	// Note, we do not record all tso requests but some typical requests.
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/sessiontxn/isolation/requestTsoFromPD", "return"))
```
Comment (lcwangchao) [inline sessiontxn/txn_context_test.go:946]: ditto

**Review by lcwangchao — APPROVED** [review]

**Review by ekexium — APPROVED** [review]
