### PR TITLE
executor: fix the issue that `SELECT ... INTO OUTFILE` returns runtime error

### LINKED ISSUE #19314: `SELECT ... INTO OUTFILE` returns runtime error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
CREATE TABLE `t` (
  `a` bit(10) DEFAULT NULL,
  `b` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `t` VALUES (_binary '\0',1),(_binary '\0',2),(_binary '\0',5),(_binary '\0',4),(_binary '\0',2),(_binary '\0	',4);
SELECT * FROM t INTO OUTFILE '/tmp/abcde';
```

### 2. What did you expect to see? (Required)
All data of table `t` should be dumped into `/tmp/abcd` successfully.

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): runtime error: index out of range [16] with length 12
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-974-g92513a2f4
Edition: Community
Git Commit Hash: 92513a2f4d382dc89bb47d3907261d49175f20ac
Git Branch: HEAD
UTC Build Time: 2020-08-20 03:40:38
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #19314 

Problem Summary: `SELECT ... INTO OUTFILE` returns runtime error

### What is changed and how it works?
Handle bit type correctly when dumping rows into files.

### Check List 

Tests 

- Unit test

### Release note 

- executor: fix the issue that `SELECT ... INTO OUTFILE` returns runtim…

### CODE REVIEW

File: executor/select_into.go [hunk 1]
```diff
@@ -121,26 +121,31 @@ func (s *SelectIntoExec) dumpToOutfile() error {
 				(encloseFlag && encloseOpt && s.considerEncloseOpt(et)) {
 				s.lineBuf = append(s.lineBuf, encloseByte)
 			}
-			switch col.GetType().EvalType() {
-			case types.ETInt:
+			switch col.GetType().Tp {
+			case mysql.TypeTiny, mysql.TypeShort, mysql.TypeInt24, mysql.TypeLong:
```
Comment (winoros) [inline executor/select_into.go:125]: Why this branch doesn't need to consider signed or unsigned?

Comment (qw4990) [reply executor/select_into.go:125]: For these types, we ignore their signs and store them simply as `int64` in TiDB since there is no risk to overflow.
I add one more test for this.
PTAL @winoros

Comment (XuHuaiyu) [reply executor/select_into.go:125]: Can we load this file into mysql successfully if we ignore the signs?

Comment (qw4990) [reply executor/select_into.go:125]: Sure, I test it successfully in local:
```
mysql> create table t (v tinyint unsigned);
Query OK, 0 rows affected (0.01 sec)

mysql> load data local infile '/tmp/rrrr' into table t;
Query OK, 1 row affected (0.00 sec)
Records: 1  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from t;
+------+
| v    |
+------+
|  127 |
+------+
1 row in set (0.00 sec)
```

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by winoros — APPROVED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
