### PR TITLE
util: Fix range construction for `in` predicate

### LINKED ISSUE #6661: Result error for IN Predicate.
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
tidb> create table t1 (some_id smallint(5) unsigned,key (some_id) );
Query OK, 0 rows affected (0.01 sec)

tidb> insert into t1 values (1),(2);
Query OK, 2 rows affected (0.10 sec)

tidb> select some_id from t1 where some_id not in(2,-1);

```

2. What did you expect to see?

```sql
+---------+
| some_id |
+---------+
|       1 |
+---------+
2 rows in set (0.00 sec)

```

3. What did you see instead?

```sql
+---------+
| some_id |
+---------+
|       1 |
|       2 |
+---------+
2 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```sql
tidb> select tidb_version()
    -> ;
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.0.0-rc.4-244-g4607251d2
Git Commit Hash: 4607251d231a449944977265f479e308f08b3504
Git Branch: fix_in_predicate
UTC Build Time: 2018-05-28 07:10:47
GoVersion: go version go1.10.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.0.0-rc.4.1 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```


If a negative integer is used in `IN_PREDICATE`  for an `UNSIGNED` column, the result goes wrong.
It seems that the index range deduction for `IndexScan` is wrong under this circumstance.

```sql
tidb> explain select some_id as b from t1 where some_id not in(1,-1);
+---------------+---------+----------+------+-------------------------------------------------------------------------+-------+
| id            | parents | children | task | operator info                                                           | count |
+---------------+---------+----------+------+-------------------------------------------------------------------------+-------+
| IndexScan_8   |         |          | cop  | table:t1, index:some_id, range:(<nil>,+inf), (1,+inf], keep order:false | 2.51  |
| IndexReader_9 |         |          | root | index:IndexScan_8                                                       | 2.51  |
+---------------+---------+----------+------+-------------------------------------------------------------------------+-------+

```

The range `(<nil>,+inf)` is obvious wrong here.

### PR DESCRIPTION
**Pull request by spongedu**
fix #6661  #4473

### CODE REVIEW

File: util/ranger/points.go [hunk 1]
```diff
@@ -421,15 +422,45 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
...
+		if x, ok := expr.GetArgs()[0].(*expression.Column); ok {
+			unsignedInt = mysql.HasUnsignedFlag(x.RetType.Flag) && mysql.IsIntegerType(x.RetType.Tp)
+		}
+		inPoints, hasNull := r.buildFromIn(expr)
 		if hasNull {
 			return nil
 		}
-		retRangePoints := make([]point, 0, len(rangePoints)+2)
+		var rangePoints []point
+		if unsignedInt {
```
Comment (shenli) [inline util/ranger/points.go]: Please add a few comments for the following logic.

File: util/ranger/points.go [hunk 2]
```diff
@@ -421,15 +422,45 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
...
+			rangePoints = make([]point, 0, 0)
```
Comment (shenli) [inline util/ranger/points.go]: Init the slice with 2 + len(inPoints)

File: util/ranger/points.go [hunk 3]
```diff
@@ -421,15 +422,45 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
...
+						rangePoints = append(rangePoints, point{value: types.NewIntDatum(0)})
+					}
+					rangePoints = append(rangePoints, inPoints[i])
+					rangePoints = append(rangePoints, inPoints[i+1])
+				}
+			}
+		} else {
+			rangePoints = inPoints
+		}
+		retRangePoints := make([]point, 0, 0)
```
Comment (shenli) [inline util/ranger/points.go]: Init the slice with 2 + len(inPoints)

File: util/ranger/points.go (hunk 1 above)
Comment (spongedu) [reply util/ranger/points.go]: ok

File: util/ranger/points.go (hunk 2 above)
Comment (spongedu) [reply util/ranger/points.go]: Done

File: util/ranger/points.go (hunk 3 above)
Comment (spongedu) [reply util/ranger/points.go]: Done

**Comment by shenli** [comment]
@zz-jason @winoros PTAL

**Comment by winoros** [comment]
The value bigger than `MaxInt64` will be treated as negative integer if you call `GetInt64()`.

**Comment by winoros** [comment]
The value bigger than `MaxInt64` will be treated as negative integer if you call `GetInt64()`.

**Comment by winoros** [comment]
Need to add test for this case.

```
mysql> explain select * from t where a not in(1, 2, 9223372036854775810);
+---------------+---------+----------+------+---------------------------------------------------------------+---------+
| id            | parents | children | task | operator info                                                 | count   |
+---------------+---------+----------+------+---------------------------------------------------------------+---------+
| IndexScan_8   |         |          | cop  | table:t, index:a, range:(<nil>,0], (2,+inf], keep order:false | 3583.33 |
| IndexReader_9 |         |          | root | index:IndexScan_8                                             | 3583.33 |
+---------------+---------+----------+------+---------------------------------------------------------------+---------+
2 rows in set (0.00 sec)
```

File: util/ranger/points.go [hunk 4]
```diff
@@ -421,15 +422,48 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
...
+		// negative ranges can be directly ignored for unsigned int columns.
+		// Point `0` should be considered specially here. If the `IN` predicate contains `0`, `0` should be
+		// excluded from the result range, otherwise `0` should be included.
+		if unsignedInt {
+			rangePoints = make([]point, 0, 2+len(inPoints))
+			for i := 0; i < len(inPoints); i += 2 {
+				value := inPoints[i].value.GetInt64()
+				if value < 0 {
+					continue
+				} else if value == 0 {
```
Comment (winoros) [inline util/ranger/points.go]: In this branch, the appended value should be the same as `rangePoints[i]` an  d `rangePoints[i+1]`?

File: util/ranger/points.go [hunk 5]
```diff
@@ -421,15 +422,48 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
...
+					rangePoints = append(rangePoints, point{value: types.NewIntDatum(0), start: true})
+					rangePoints = append(rangePoints, point{value: types.NewIntDatum(0)})
+				} else {
+					if len(rangePoints) == 0 {
+						rangePoints = append(rangePoints, point{value: types.NewIntDatum(0), start: true, excl: true})
```
Comment (winoros) [inline util/ranger/points.go]:
```
mysql> explain select * from t where a not in(111);
+---------------+---------+----------+------+--------------------------------------------------------------------------+---------+
| id            | parents | children | task | operator info                                                            | count   |
+---------------+---------+----------+------+--------------------------------------------------------------------------+---------+
| IndexScan_8   |         |          | cop  | table:t, index:a, range:(<nil>,0], (0,111), (111,+inf], keep order:false | 3833.33 |
| IndexReader_9 |         |          | root | index:IndexScan_8                                                        | 3833.33 |
+---------------+---------+----------+------+--------------------------------------------------------------------------+---------+
2 rows in set (0.00 sec)
```
When the column is `unsigned`. `(<nil>,111)` is the same as `(<nil>,0], (0,111)`.

Comment (spongedu) [reply util/ranger/points.go]: yes. I'll refine here

File: util/ranger/points.go (hunk 4 above)
Comment (spongedu) [reply util/ranger/points.go]: I think twice, and found that there's no need to consider `0` as a special case. I'll fix here

**Comment by spongedu** [comment]
Have resolved the issues in comments. PTAL @winoros

File: util/ranger/points.go [hunk 6]
```diff
@@ -421,11 +422,27 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
...
+		}
+		inPoints, hasNull := r.buildFromIn(expr)
 		if hasNull {
 			return nil
 		}
-		retRangePoints := make([]point, 0, len(rangePoints)+2)
+		var rangePoints []point
+		// negative ranges can be directly ignored for unsigned int columns.
+		if unsignedInt {
+			rangePoints = make([]point, 0, 2+len(inPoints))
```
Comment (winoros) [inline util/ranger/points.go]: Since the `rangePoints` is in order, the negative one must be the head of the slice.
So we can just get the position and use `rangePoints = rangePoints[nonNegativePos:]`

Comment (spongedu) [reply util/ranger/points.go]: ok

File: util/ranger/points.go [hunk 7]
```diff
@@ -421,11 +422,27 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
 	case ast.IsFalsity:
 		return r.buildFromIsFalse(expr, 1)
 	case ast.In:
+		var (
+			unsignedInt    bool
+			nonNegativePos int
+		)
+		if x, ok := expr.GetArgs()[0].(*expression.Column); ok {
+			unsignedInt = mysql.HasUnsignedFlag(x.RetType.Flag) && mysql.IsIntegerType(x.RetType.Tp)
```
Comment (zz-jason) [inline util/ranger/points.go]: s/unsignedInt/isUnsignedIntCol/ ?

File: util/ranger/points.go [hunk 8]
```diff
@@ -421,11 +422,27 @@ func (r *builder) buildFromNot(expr *expression.ScalarFunction) []point {
 	case ast.IsFalsity:
 		return r.buildFromIsFalse(expr, 1)
 	case ast.In:
+		var (
+			unsignedInt    bool
+			nonNegativePos int
+		)
+		if x, ok := expr.GetArgs()[0].(*expression.Column); ok {
```
Comment (zz-jason) [inline util/ranger/points.go]: move this after line 435?

File: util/ranger/points.go (hunk 7 above)
Comment (spongedu) [reply util/ranger/points.go]: ok

File: util/ranger/points.go (hunk 8 above)
Comment (spongedu) [reply util/ranger/points.go]: ok
