### PR TITLE
planner: set the default of the tidb_cost_model_version correctly

### LINKED ISSUE #61565: internal SQL wrongly use get plan cost v1
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When you enable the flame graph, you will find that some of the internal SQL stacks have stacks that call ```get_plan_cost_v1```, which is clearly incorrect.

Image

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #61565

Problem Summary:

### What changed and how does it work?

We don't set the default of the tidb_cost_model_version in the right place. so it led many problems in the internal SQL. The internal SQL will not use the cost model v2.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: rightly set the default of the tidb_cost_model_version

正确设置 tidb_cost_model_version 的默认值
```

### CODE REVIEW

File: pkg/planner/core/plan_cost_ver1.go [hunk 1]
```diff
@@ -87,6 +88,7 @@ func (p *PhysicalProjection) GetCost(count float64) float64 {
 
 // GetPlanCostVer1 calculates the cost of the plan if it has not been calculated yet and returns the cost.
 func (p *PhysicalProjection) GetPlanCostVer1(taskType property.TaskType, option *optimizetrace.PlanCostOption) (float64, error) {
+	intest.Assert(p.SCtx().GetSessionVars().CostModelVersion != 0)
```
Comment (hawkingrei) [inline pkg/planner/core/plan_cost_ver1.go:91]: CostModelVersion's value is only 1 or 2, so if we get 0, it has a problem.

**Review by yudongusa — APPROVED** [review]
