### PR TITLE
expression: Wrong type value in INET6_ATON/INET_ATON should return errors

### LINKED ISSUE #32221: TiDB doesn't give errors for wrong  type value in `INET6_ATON`, `INET_ATON`, `UNHEX`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step 
```sql
SET sql_mode = default;
DROP TABLE IF EXISTS t2;
CREATE TABLE t2(ip VARBINARY(16));
INSERT INTO t2 VALUES (INET6_ATON('1.0002.3.4'));
INSERT INTO t2 VALUES (INET6_ATON('1.2.255'));
INSERT INTO t2 VALUES (INET6_ATON('1.2.256'));
INSERT INTO t2 VALUES (INET6_ATON('192.168.0x8.2'));
INSERT INTO t2 VALUES (inet_aton("122.256"));
INSERT INTO t2 VALUES (inet_aton("122.226."));
INSERT INTO t2 VALUES (inet_aton(""));
INSERT INTO t2 VALUES (UNHEX('Z0Q80F02'));

SELECT INET6_NTOA(ip), HEX(ip), LENGTH(ip) FROM t2;
DROP TABLE t2;
```
### 2. What did you expect to see? 
```sql
mysql> CREATE TABLE t2(ip VARBINARY(16));
Query OK, 0 rows affected (0.07 sec)
mysql> INSERT INTO t2 VALUES (INET6_ATON('1.0002.3.4'));
ERROR 1411 (HY000): Incorrect string value: ''1.0002.3.4'' for function inet6_aton
mysql> INSERT INTO t2 VALUES (INET6_ATON('1.2.255'));
ERROR 1411 (HY000): Incorrect string value: ''1.2.255'' for function inet6_aton
mysql> INSERT INTO t2 VALUES (INET6_ATON('1.2.256'));
ERROR 1411 (HY000): Incorrect string value: ''1.2.256'' for function inet6_aton
mysql> INSERT INTO t2 VALUES (INET6_ATON('192.168.0x8.2'));
ERROR 1411 (HY000): Incorrect string value: ''192.168.0x8.2'' for function inet6_aton
mysql> INSERT INTO t2 VALUES (inet_aton("122.256"));
ERROR 1411 (HY000): Incorrect string value: ''122.256'' for function inet_aton
mysql> INSERT INTO t2 VALUES (inet_aton("122.226."));
ERROR 1411 (HY000): Incorrect string value: ''122.226.'' for function inet_aton
mysql> INSERT INTO t2 VALUES (inet_aton(""));
ERROR 1411 (HY000): Incorrect string value: '''' for function inet_aton
mysql> INSERT INTO t2 VALUES (UNHEX('Z0Q80F02'));
ERROR 1411 (HY000): Incorrect string value: ''Z0Q80F02'' for function unhex
mysql> SELECT INET6_NTOA(ip), HEX(ip), LENGTH(ip) FROM t2;
Empty set (0.01 sec)
```

### 3. What did you see instead 
```sql
tidb> CREATE TABLE t2(ip VARBINARY(16));
Query OK, 0 rows affected (0.03 sec)
tidb> INSERT INTO t2 VALUES (INET6_ATON('1.0002.3.4'));
Query OK, 1 row affected (0.00 sec)
tidb> INSERT INTO t2 VALUES (INET6_ATON('1.2.255'));
Query OK, 1 row affected (0.00 sec)
tidb> INSERT INTO t2 VALUES (INET6_ATON('1.2.256'));
Query OK, 1 row affected (0.00 sec)
tidb> INSERT INTO t2 VALUES (INET6_ATON('192.168.0x8.2'));
Query OK, 1 row affected (0.00 sec)
tidb> INSERT INTO t2 VALUES (inet_aton("122.256"));
Query OK, 1 row affected (0.02 sec)
tidb> INSERT INTO t2 VALUES (inet_aton("122.226."));
Query OK, 1 row affected (0.00 sec)
tidb> INSERT INTO t2 VALUES (inet_aton(""));
Query OK, 1 row affected (0.00 sec)
tidb>INSERT INTO t2 VALUES (UNHEX('Z0Q80F02'));
Query OK, 1 row affected (0.01 sec)
tidb> SELECT INET6_NTOA(ip), HEX(ip), LENGTH(ip) FROM t2;
+----------------+---------+------------+
| INET6_NTOA(ip) | HEX(ip) | LENGTH(ip) |
+----------------+---------+------------+
| NULL           | NULL    |       NULL |
| NULL           | NULL    |       NULL |
| NULL           | NULL    |       NULL |
| NULL           | NULL    |       NULL |
| NULL           | NULL    |       NULL |
| NULL           | NULL    |       NULL |
| NULL           | NULL    |       NULL |
| NULL           | NULL    |       NULL |
+----------------+---------+------------+
8 rows in set (0.01 sec)
```

### 4. What is your TiDB version?
```
tidb_version(): Release Version: v5.5.0-alpha-210-g11f4ca802
Edition: Community
Git Commit Hash: 11f4ca802083ee38d5972730ba8f9b72395316fb
Git Branch: master
UTC Build Time: 2022-02-09 22:07:29
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by fanrenhoo**
Signed-off-by: fanrenhoo <fanrenhoo@sina.com>

### What problem does this PR solve?

Issue Number: close #32221

Problem Summary: with wrong type value in func INET6_ATON/INET_ATON give no errors and insert a NULL in database, this should return error message

### What is changed and how it works?
Change the previous incomplete logic, when wrong type value detected, should not return like no error, now should return error with correct error message 
Add also changed test case for this issue to make it right.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
Test with wrong and correct type value, both works OK, like:

>SET sql_mode = default;
>DROP TABLE IF EXISTS t2;
>CREATE TABLE t2(ip VARBINARY(16));
>INSERT INTO t2 VALUES (INET6_ATON('1.0002.3.4'));
ERROR 1411 (HY000): Incorrect string value: ''1.0002.3.4'' for function inet6_aton

> INSERT INTO t2 VALUES (inet_aton("122.226."));
ERROR 1411 (HY000): Incorrect string value: ''122.226.'' for function inet_aton

>SELECT INET6_NTOA(ip), HEX(ip), LENGTH(ip) FROM t2;
Empty set (0.01 sec)

- [ ] No code

Side effects
no
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation
no
- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
make the wrong type value in func INET6_ATON/INET_ATON call give correct errors, and insert nothing in table either 
```

### CODE REVIEW

File: expression/builtin_miscellaneous.go [hunk 1]
```diff
@@ -564,12 +564,14 @@ func (b *builtinInet6AtonSig) evalString(row chunk.Row) (string, bool, error) {
...
-		return "", true, nil
+		return "", false, errWrongValueForType.GenWithStackByArgs("string", val, "inet_aton6")
+		//return "", true, nil
 	}
 
 	ip := net.ParseIP(val)
 	if ip == nil {
-		return "", true, nil
+		return "", false, errWrongValueForType.GenWithStackByArgs("string", val, "inet_aton6")
+		//return "", true, nil
```
Comment (xhebox) [inline expression/builtin_miscellaneous.go:574]: Comment?

File: expression/builtin_miscellaneous.go [hunk 2]
```diff
@@ -564,12 +564,14 @@ func (b *builtinInet6AtonSig) evalString(row chunk.Row) (string, bool, error) {
 	}
 
 	if len(val) == 0 {
-		return "", true, nil
+		return "", false, errWrongValueForType.GenWithStackByArgs("string", val, "inet_aton6")
+		//return "", true, nil
```
Comment (xhebox) [inline expression/builtin_miscellaneous.go:568]: Same

File: expression/builtin_miscellaneous_test.go [hunk 3]
```diff
@@ -55,8 +56,11 @@ func TestInetAton(t *testing.T) {
 		f, err := fc.getFunction(ctx, datumsToConstants(tt["Input"]))
 		require.NoError(t, err)
 		d, err := evalBuiltinFunc(f, chunk.Row{})
-		require.NoError(t, err)
-		testutil.DatumEqual(t, tt["Expected"][0], d)
+		if err == nil {
```
Comment (xhebox) [inline expression/builtin_miscellaneous_test.go:59]: Your fix for tests are not correct. All these fixes should be fixed somehow.

You should do something like:

```
if tt.expecterr !=  nil {
        require.True(t, terror.ErrorEqual(err, tt.expecterr))
} else {
        require.NoError(t, err)
		testutil.DatumEqual(t, tt["Expected"][0], d)
}
```

In short, the result of execution must be fail/succ. If the implementation is wrong and tje exeution failed, won't it also get `errWrongValueForType`? Then how does `require.True(t, terror.ErrorEqual(err, errWrongValueForType))` make sense? Your fix of tests break some fundamental logic of testing.

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go:59]: Hi, thks much for comment. but I think the tt..expecterr sure is errWrongValueForType, so I use what really output to compare with it should be OK, like many other test's logic. e.g. tt["Expected"][0] is just set by self on the above map code. We can also set errWrongValueForType message in the  tt map but that make the code look bad, so I did this. is this right?

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go:58]: > so I did this. is this right?

No, obviously.

> tt..expecterr sure is errWrongValueForType

Yes, but the point is that, it is the case written by ourselves determines whether the test should fail or not. Not the result of the test determines whether it should fail or not. How could use the execution result to determine if it should fail? What are you testing? Did you get the poit?

The correct fix may be add a new column to indicate whether the test should fail or not. Or use something like `_, ok := tt["Expected"][0].(error)` to indicate whether the test should fail or not. Or whatever other methods.

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go:58]: unterstood, you are right, I'll do some amendation and recommit. THKS.

**Comment by fanrenhoo** [comment]
Hi, I made a new fix, please check, THKS

File: expression/builtin_miscellaneous_test.go [hunk 4]
```diff
@@ -295,7 +299,10 @@ func TestInet6AtoN(t *testing.T) {
 		f, err := fc.getFunction(ctx, datumsToConstants([]types.Datum{ip}))
 		require.NoError(t, err)
 		result, err := evalBuiltinFunc(f, chunk.Row{})
-		require.NoError(t, err)
+		if err != nil {
```
Comment (xhebox) [inline expression/builtin_miscellaneous_test.go:302]: You are still using the result `result, err` of `evalBuiltinFunc`to determine if the test check `require.True(t, terror.ErrorEqual(err, errWrongValueForType))` should be executed.

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go:302]: Yes, but this is not the same as before, and as you suggested: in err case we must be as we preset expected, not err case also must as we preset expected. So the logic should be same as if (espected ....). I write it this way is because same the code is more concise.

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go:302]: But `err` is the result of execution, not the expected error.

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go:302]: No. Results can never be the expectation.

Take an  example, I could say "[roly-poly toy](https://en.wikipedia.org/wiki/Roly-poly_toy) will never fail", and that is true. In this case, it is that my expectation happens to be true. Whatever my expectation is, `roly-poly toy` is designed not to fail.

But this is not true on program, where it may be written to a wrong form easily. So you don't know whether the result is correct or not. Thus it will not always match your expectation theoretically, even if *they now match your expectation*.

And we write tests for correctness now, to prevent regression in future. Your argument ignores that *tests will serve for regression*.

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go:302]: You are right!!! Sorry and THKS, I'll refix and resubmit

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go]: Hi, I made new fix, please check. THKS much!

File: expression/builtin_miscellaneous_test.go [hunk 5]
```diff
@@ -295,8 +299,12 @@ func TestInet6AtoN(t *testing.T) {
...
 		require.NoError(t, err)
 		result, err := evalBuiltinFunc(f, chunk.Row{})
-		require.NoError(t, err)
-		testutil.DatumEqual(t, types.NewDatum(test.expect), result)
+		expect := types.NewDatum(test.expect)
+		if expect.IsNull() {
+			result.SetNull()
+			require.True(t, terror.ErrorEqual(err, errWrongValueForType))
+		}
+		testutil.DatumEqual(t, expect, result)
```
Comment (xhebox) [inline expression/builtin_miscellaneous_test.go:307]: I suggest you to test like this:

```
if expect.IsNull() {
			require.True(t, terror.ErrorEqual(err, errWrongValueForType))
} else {
            require.NoError(t, err)
		    testutil.DatumEqual(t, expect, result)
}
```

File: expression/builtin_miscellaneous_test.go [hunk 6]
```diff
@@ -55,7 +56,10 @@ func TestInetAton(t *testing.T) {
 		f, err := fc.getFunction(ctx, datumsToConstants(tt["Input"]))
 		require.NoError(t, err)
 		d, err := evalBuiltinFunc(f, chunk.Row{})
-		require.NoError(t, err)
+		if tt["Expected"][0].IsNull() && !tt["Input"][0].IsNull() {
+			d.SetNull()
+			require.True(t, terror.ErrorEqual(err, errWrongValueForType))
+		}
```
Comment (xhebox) [inline expression/builtin_miscellaneous_test.go:62]: I suggest you to test like this:

```
if  tt["Expected"][0].IsNull() && !tt["Input"][0].IsNull() {
			require.True(t, terror.ErrorEqual(err, errWrongValueForType))
} else {
            require.NoError(t, err)
		    testutil.DatumEqual(t, tt["Expected"][0], d)
}
```

File: expression/bench_test.go [hunk 7]
```diff
@@ -1128,7 +1128,12 @@ func testVectorizedEvalOneVec(t *testing.T, vecExprCases vecExprBenchCases) {
 			output2 := output.CopyConstruct()
 			require.NoErrorf(t, evalOneVec(ctx, expr, input, output, 0), "func: %v, case: %+v", funcName, testCase)
 			it := chunk.NewIterator4Chunk(input)
-			require.NoErrorf(t, evalOneColumn(ctx, expr, it, output2, 0), "func: %v, case: %+v", funcName, testCase)
+			if err := evalOneColumn(ctx, expr, it, output2, 0); err == nil {
+				require.NoErrorf(t, evalOneColumn(ctx, expr, it, output2, 0), "func: %v, case: %+v", funcName, testCase)
+			} else {
+				require.True(t, terror.ErrorEqual(err, errWrongValueForType))
+				return
+			}
```
Comment (xhebox) [inline expression/bench_test.go:1136]: Did not modify this.

File: expression/bench_test.go [hunk 8]
```diff
@@ -1382,6 +1387,11 @@ func testVectorizedBuiltinFunc(t *testing.T, vecExprCases vecExprBenchCases) {
 				i64s := output.Int64s()
 				for row := it.Begin(); row != it.End(); row = it.Next() {
 					val, isNull, err := baseFunc.evalInt(row)
+					if err != nil {
+						i++
+						require.True(t, terror.ErrorEqual(err, errWrongValueForType))
+						continue
+					}
```
Comment (xhebox) [inline expression/bench_test.go:1394]: ditto

**Review by xhebox — COMMENTED** [review]
You still need to:

1. fix cases in `bench_test.go`, too. You are judging cases by the results.
2. Fixes in `builtin_xxx` are almost correct, but there is `require.NoError` in the original while your cases did not have.

File: expression/builtin_miscellaneous_test.go (hunk 4 above)
Comment (xhebox) [reply expression/builtin_miscellaneous_test.go]: Commented.

File: expression/builtin_miscellaneous_test.go (hunk 5 above)
Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go:307]: OK. A bit doubt in bench_test.go, with this vec bench test it seems the original test cases generate IP strings use rand()  machnism, not set expect result as above, thats why I did not change it the same way as we agreed already. I thought what we want to test already proved in above case, so in vec bench case may just avoid show error is ok to reach the vec bench test aim also, dont need to test the above logic again. is that reasonable?

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go:307]: OK. A bit doubt in bench_test.go, with this vec bench test it seems the original test cases generate IP strings use rand() machnism, not set expect result as above, thats why I did not change it the same way as we agreed already. I thought what we want to test already proved in above case, so in vec bench case may just avoid show error is ok to reach the vec bench test aim also, dont need to test the above logic again. is that reasonable? anyway, I will deep to learn the logic to find. THKS

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go:307]: That makes sense. I'll double check if your logic is correct.

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go:307]: But better add `NoError`, asserting more is better than nothing.

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go]: > OK. A bit doubt in bench_test.go, with this vec bench test it seems the original test cases generate IP strings use rand() machnism, not set expect result as above, thats why I did not change it the same way as we agreed already. I thought what we want to test already proved in above case, so in vec bench case may just avoid show error is ok to reach the vec bench test aim also, dont need to test the above logic again. is that reasonable? anyway, I will deep to learn the logic to find. THKS

A better fix would be removing invalid cases here https://github.com/pingcap/tidb/blob/f9a324829b71a24141d5326ddc0026f6b12125c3/expression/builtin_miscellaneous_vec_test.go#L51-L66. And all cases will pass, then there is no need to use the result as expectation.

Since your midifications applies to a lot, a lot of tests rather than INET_ATON cases. So no, your changes may let other cases fail without even knowing.

Honestly, just don't use the result as expectation. As I said, it breaks the fundamental rules of testing. Tests should be reliable and sound forever. Tests are to fail, not to pass all the time.

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go]: BTW, resolve the comment, after you address the corresponding changes, like what I did :)

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go]: THKS! Did you mean just leave the test errors there with bench_test.go because not to pass all the time?

Comment (xhebox) [reply expression/builtin_miscellaneous_test.go]: > THKS! Did you mean just leave the test errors there with bench_test.go because not to pass all the time?

I mean fix it by removing tests that will fail, that is recover the test code to the original.

Since failed tests are covered in other tests, it is ok.

Comment (fanrenhoo) [reply expression/builtin_miscellaneous_test.go]: I just did new fix, follow the above logic. Actually before I tried this, but because the bench_test inet_aton also generate IP string by rand way, so err always happens, and I dont want to change too much of the previous logic before. Now I think it make no senso for Inet_aton, so just remove those random string gen. please check and THKS.

**Review by xhebox — APPROVED** [review]

File: expression/builtin_miscellaneous_test.go (hunk 5 above)
Comment (xhebox) [reply expression/builtin_miscellaneous_test.go]: The last thing, resolve the conversation/comment after you addressing the problem.

**Comment by Defined2014** [comment]
Seems the `unhex` function still can't work. Do you have interest about it? @fanrenhoo

**Comment by fanrenhoo** [comment]
@you06 Hi, how about this one, THKS

File: expression/builtin_miscellaneous.go [hunk 9]
```diff
@@ -445,17 +445,17 @@ func (b *builtinInetAtonSig) evalInt(row chunk.Row) (int64, bool, error) {
 			digit := uint64(c - '0')
 			byteResult = byteResult*10 + digit
 			if byteResult > 255 {
```
Comment (you06) [inline expression/builtin_miscellaneous.go:447]: The implementation does not handle `SELECT INET6_ATON('1.0002.3.4')` which returns `NULL` in MySQL.

**Comment by you06** [comment]
@fanrenhoo Can you help port the cases from the issues to the unit tests?

**Comment by fanrenhoo** [comment]
> 

Hi, I'd like to help, just not sure how to do this? is it in the "test" package of tidb?

**Comment by you06** [comment]
They can be easily added to the case array. And all the test cases in the issue should return `NULL`, so just left a `nil` in the expected field.

https://github.com/pingcap/tidb/blob/6b3b73bbec85550afa89d92418da743700b6ff29/expression/builtin_miscellaneous_test.go#L37-L49

https://github.com/pingcap/tidb/blob/6b3b73bbec85550afa89d92418da743700b6ff29/expression/builtin_miscellaneous_test.go#L284-L290

**Comment by fanrenhoo** [comment]
> '1.2.256'

do you mean in unit_test for inet6_aton, add cases like:

'1.0002.3.4', nil
'1.2.256', nil
'1.2.2.23', nil

and open a new issue to fix this?

**Comment by you06** [comment]
> do you mean in unit_test for inet6_aton, add cases like:

Yes, and with some investigation, I confirmed that '1.0002.3.4' is handled when parsing ip with go >= 1.17, and TiDB use go 1.18 now, so it's not required to fix them, just add it to the test in case of regression.

**Comment by fanrenhoo** [comment]
@you06 Hi, I made the change as suggested and commit again, please check, THKS

**Review by you06 — APPROVED** [review]
