### PR TITLE
br: modify how to parse the add index job args

### LINKED ISSUE #47451: br: full restore to cluster would possibly fail and shows 'Error: failed to restore meta files: json: cannot unmarshal array into Go value of type int64'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
full restore

### 3. What did you see instead (Required)
error: failed to restore meta files: json: cannot unmarshal array into Go value of type int64

[2023/10/04 10:08:48.449 +00:00] [INFO] [collector.go:78] ["restore log failed summary"] [error="failed to restore meta files: json: cannot unmarshal array into Go value of type int64"] [errorVerbose="json: cannot unmarshal array into Go value of type int64\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/juju_adaptor.go:15\ngithub.com/pingcap/tidb/parser/model.(*Job).DecodeArgs\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/parser/model/ddl.go:598\ngithub.com/pingcap/tidb/br/pkg/restore/ingestrec.(*IngestRecorder).AddJob\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/ingestrec/ingest_recorder.go:83\ngithub.com/pingcap/tidb/br/pkg/stream.(*SchemasReplace).restoreFromHistory\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/stream/rewrite_meta_rawkv.go:688\ngithub.com/pingcap/tidb/br/pkg/stream.(*SchemasReplace).RewriteKvEntry\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/stream/rewrite_meta_rawkv.go:652\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).restoreMetaKvEntries\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:3124\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).RestoreBatchMetaKVFiles\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:3093\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).RestoreMetaKVFilesWithBatchMethod\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:3033\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).RestoreMetaKVFiles\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:2895\ngithub.com/pingcap/tidb/br/pkg/task.restoreStream.func6\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/stream.go:1357\ngithub.com/pingcap/tidb/br/pkg/task.withProgress\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/stream.go:1519\ngithub.com/pingcap/tidb/br/pkg/task.restoreStream\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/stream.go:1355\ngithub.com/pingcap/tidb/br/pkg/task.RunStreamRestore\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/stream.go:1178\ngithub.com/pingcap/tidb/br/pkg/task.RunRestore\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/restore.go:593\nmain.runRestoreCommand\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/restore.go:63\nmain.newStreamRestoreCommand.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/restore.go:237\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/main.go:58\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\nfailed to restore meta files"]

### 4. What is your TiDB version? (Required)
v7.4.0

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #47451 

Problem Summary:
currently the `addindex` ddl job's `Args[0]` might be `[]int64` instead of `int64`.

### What is changed and how it works?
retry to parse by `[]int64` when failed to parse by `int64`.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: br/pkg/restore/ingestrec/ingest_recorder.go [hunk 1]
```diff
@@ -79,9 +79,11 @@ func (i *IngestRecorder) AddJob(job *model.Job) error {
 		return nil
 	}
 
-	var indexID int64 = 0
-	if err := job.DecodeArgs(&indexID); err != nil {
-		return errors.Trace(err)
+	allIndexIDs := make([]int64, 1)
```
Comment (BornChanger) [inline br/pkg/restore/ingestrec/ingest_recorder.go:82]: add some comments here

File: br/pkg/stream/rewrite_meta_rawkv.go [hunk 2]
```diff
@@ -840,15 +840,16 @@ func (sr *SchemasReplace) deleteRange(job *model.Job) error {
...
 			return nil
 		}
-		var indexID int64
-		var ifExists bool
+		indexIDs := make([]int64, 1)
+		ifExists := make([]bool, 1)
 		var partitionIDs []int64
-		if err := job.DecodeArgs(&indexID, &ifExists, &partitionIDs); err != nil {
-			return errors.Trace(err)
+		if err := job.DecodeArgs(&indexIDs[0], &ifExists[0], &partitionIDs); err != nil {
```
Comment (BornChanger) [inline br/pkg/stream/rewrite_meta_rawkv.go:846]: ditto

**Review by BornChanger — APPROVED** [review]

**Comment by Leavrth** [comment]
/cherry-pick-7.4

**Comment by Leavrth** [comment]
/cherry-pick-to-7.4
