### PR TITLE
ddl: release scan chunks earlier to cap the memory usage

### LINKED ISSUE #64911: addindex: add index OOM in read index stage
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create index with large table in next gen

### 2. What did you expect to see? (Required)
no oom
### 3. What did you see instead (Required)
oom

Image

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #64911

Problem Summary:
The add-index backfill scan path buffers each scan task's chunks before sending them downstream, which holds chunks in memory longer than necessary. This PR improves that behavior for the global-sort path, while keeping the classic local-ingest path buffered to preserve the ordering fixed by #62014.

### What changed and how does it work?

`(*tableScanWorker).scanRecords` now streams scanned chunks immediately only when `UseCloudStorage` is enabled, that is, on the global-sort path.

For the classic local-ingest path, scanned chunks are still sent after the scan task finishes. This avoids starting partial import while the scan transaction is still open and keeps `TestAddIndexDiskQuotaTS` passing.

This PR also adds a failpoint-based regression test for partial-scan checkpoint recovery.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Reduce peak memory retention during the add-index read-index stage by streaming scanned chunks on the global-sort path instead of buffering a whole scan task. Keep the classic local-ingest path buffered to preserve correct partial-import ordering, and add a regression test for partial-scan checkpoint recovery.
```

### CODE REVIEW

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 1]
```diff
@@ -489,3 +496,45 @@ func TestAddIndexResumesFromCheckpointAfterPartialImport(t *testing.T) {
 	t.Run("dist_task_off", func(t *testing.T) { runCase(t, false) })
 	t.Run("dist_task_on", func(t *testing.T) { runCase(t, true) })
 }
+
+func TestAddIndexResumesFromCheckpointAfterPartialScan(t *testing.T) {
```
Comment (joechenrh) [inline tests/realtikvtest/addindextest4/integration_test.go:500]: This test prevents `scanRecords` from regressing to a buffer-then-flush model. In that model, a scan that ends with a partial error can mark the last chunk as `done=true`, which may let `CheckpointManager.afterFlush` advance the watermark past unread keys. On master, this latent bug appears only when writers win a race against scan-error cancellation, so the resulting data loss is intermittent rather than deterministic.

The failpoint `1*return(false)->1*return(true)` makes the first chunk fetch succeed and the second fail, so the retry path is exercised.

File: pkg/ddl/backfilling_operators.go [hunk 2]
```diff
@@ -574,19 +589,19 @@ func (w *tableScanWorker) scanRecords(task TableScanTask, sender func(IndexRecor
...
 
 			_, tableScanRowCount := distsqlCtx.RuntimeStatsColl.GetCopCountAndRows(tableScanCopID)
-			idxResults = append(idxResults, IndexRecordChunk{ID: task.ID, Chunk: srcChk, Done: done, ctx: w.ctx, tableScanRowCount: tableScanRowCount - lastTableScanRowCount, conditionPushed: conditionPushed})
+			idxResult := IndexRecordChunk{ID: task.ID, Chunk: srcChk, Done: done, ctx: w.ctx, tableScanRowCount: tableScanRowCount - lastTableScanRowCount, conditionPushed: conditionPushed}
 			lastTableScanRowCount = tableScanRowCount
+			if streamResults {
+				sendResult(idxResult)
+				continue
+			}
+			idxResults = append(idxResults, idxResult)
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go]: maybe use if/else to be more clear

File: pkg/ddl/backfilling_operators.go [hunk 3]
```diff
@@ -574,19 +589,19 @@ func (w *tableScanWorker) scanRecords(task TableScanTask, sender func(IndexRecor
...
 
-	for i, idxResult := range idxResults {
-		sender(idxResult)
-		if w.cpOp != nil {
-			done := i == len(idxResults)-1
-			w.cpOp.UpdateChunk(task.ID, int(idxResult.tableScanRowCount), done)
-		}
-		w.totalCount.Add(idxResult.tableScanRowCount)
+	for _, idxResult := range idxResults {
+		sendResult(idxResult)
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go]: bound in `if branch` as it only run when not streaming way

File: pkg/ddl/backfilling_operators.go [hunk 4]
```diff
@@ -532,6 +532,16 @@ func (w *tableScanWorker) scanRecords(task TableScanTask, sender func(IndexRecor
 		idxResults  []IndexRecordChunk
 		execDetails kvutil.ExecDetails
 	)
+	// Local ingest may trigger partial import/reset while the scan transaction is
+	// still open, so only the global-sort path can stream results immediately.
+	streamResults := w.reorgMeta.UseCloudStorage
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go]: maybe name as `enableStreaming`, current name sounds like a noun and seems storing some `results`

**Review by D3Hunter — COMMENTED** [review]
### Summary

- Total findings: 4
- Inline comments: 4
- Summary-only findings (no inline anchor): 0

<details>
<summary>Findings (highest risk first)</summary>

#### ⚠️ **[Major]** (1)

1. Global-sort checkpoint streaming branch is changed but not covered by the new regression test (`pkg/ddl/backfilling_operators.go:537, tests/realtikvtest/addindextest4/integration_test.go:446, tests/realtikvtest/addindextest4/integration_test.go:500, pkg/dxf/framework/handle/handle.go:323`)

#### 🟡 **[Minor]** (2)

1. Checkpoint-resume test harness is duplicated across two cases (`tests/realtikvtest/addindextest4/integration_test.go:461; tests/realtikvtest/addindextest4/integration_test.go:501`)
2. Partial-scan failpoint scenario can silently pass without proving the intended branch was hit (`tests/realtikvtest/addindextest4/integration_test.go:512, tests/realtikvtest/addindextest4/integration_test.go:521`)

#### ℹ️ **[Info]** (1)

1. N/N-1 mixed-version behavior for new checkpoint emission timing is not demonstrated (`pkg/ddl/backfilling_operators.go:594`)

</details>

File: pkg/ddl/backfilling_operators.go (hunk 4 above)
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go]: #### ⚠️ **[Major]** Global-sort checkpoint streaming branch is changed but not covered by the new regression test

**Why**
The behavioral change is gated by `UseCloudStorage`, but the added test never configures cloud storage, so the changed streaming path is not exercised. This leaves a compatibility-sensitive recovery path unvalidated in the same change set.

**Scope**
pkg/ddl/backfilling_operators.go:537, tests/realtikvtest/addindextest4/integration_test.go:446, tests/realtikvtest/addindextest4/integration_test.go:500, pkg/dxf/framework/handle/handle.go:323

**Risk if unchanged**
A regression in global-sort partial-scan resume/checkpoint behavior can pass CI and surface only in production DDL retries, including upgrade windows where this path is operationally critical.

**Evidence**
`scanRecords` now streams results only when `w.reorgMeta.UseCloudStorage` is true (`streamResults := w.reorgMeta.UseCloudStorage`). The new test sets only `tidb_ddl_enable_fast_reorg` and `tidb_enable_dist_task`; it does not set `tidb_cloud_storage_uri`. `GetCloudStorageURI` returns empty when unset, so `UseCloudStorage` remains false.

**Change request**
please add an integration test for this path by explicitly enabling global-sort (`tidb_cloud_storage_uri`) and validating the partial-scan checkpoint resume branch under that mode.

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 5]
```diff
@@ -443,21 +443,28 @@ func TestCancelAfterReorgTimeout(t *testing.T) {
...
+	tk.MustExec("set global tidb_ddl_enable_fast_reorg = 1")
+	if distTaskOn {
+		tk.MustExec("set global tidb_enable_dist_task = 1")
+	} else {
+		tk.MustExec("set global tidb_enable_dist_task = 0")
+	}
+}
+
 func TestAddIndexResumesFromCheckpointAfterPartialImport(t *testing.T) {
 	runCase := func(t *testing.T, distTaskOn bool) {
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest4/integration_test.go:461]: #### 🟡 **[Minor]** Checkpoint-resume test harness is duplicated across two cases

**Why**
The new partial-scan resume test repeats nearly the full setup and verification flow from the partial-import resume test, while only the injected failpoint behavior differs.

**Scope**
tests/realtikvtest/addindextest4/integration_test.go:461; tests/realtikvtest/addindextest4/integration_test.go:501

**Risk if unchanged**
Future changes to schema setup, row population, or post-DDL validation can drift between the two tests and reduce confidence that both checkpoint paths are being validated consistently.

**Evidence**
Both runCase closures create store/testkit, set classic vars, build the same table/data, run add-index DDL, compare base/index row counts, and run `admin check table`; the only material delta is failpoint configuration.

**Change request**
this looks duplicated with the sibling resume test; can we keep one canonical definition by extracting a shared helper that accepts a failpoint setup callback for each scenario?

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 6]
```diff
@@ -489,3 +496,45 @@ func TestAddIndexResumesFromCheckpointAfterPartialImport(t *testing.T) {
...
+
+		tk := testkit.NewTestKit(t, store)
+		tk.MustExec("use test")
+
+		setupAddIndexClassicVars(tk, distTaskOn)
+		ingest.ForceSyncFlagForTest.Store(true)
+
+		tk.MustExec("drop table if exists t")
+		tk.MustExec("create table t (a bigint primary key, b bigint)")
+		for i := range 2000 {
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest4/integration_test.go:512]: #### 🟡 **[Minor]** Partial-scan failpoint scenario can silently pass without proving the intended branch was hit

**Why**
The test injects an error on the second `scanRecords` fetch, but it does not assert that the failpoint was consumed or that partial-scan checkpoint state advanced before retry. The test can therefore pass while not actually validating the intended failure-path behavior.

**Scope**
tests/realtikvtest/addindextest4/integration_test.go:512, tests/realtikvtest/addindextest4/integration_test.go:521

**Risk if unchanged**
Future changes to batch sizing/chunking can turn this into a false-negative regression test, reducing determinism and allowing checkpoint-resume regressions to slip through.

**Evidence**
The case relies on `1*return(false)->1*return(true)` (second invocation). The test does not pin scan batch size or assert failpoint-hit/checkpoint-progress signals; it only checks final row-count parity and `admin check table`.

**Change request**
add a case for this edge scenario with an explicit assertion that the injected partial-scan error path was exercised (for example by pinning batch size to force multiple fetches and checking a deterministic retry/progress signal).

File: pkg/ddl/backfilling_operators.go [hunk 7]
```diff
@@ -574,19 +589,19 @@ func (w *tableScanWorker) scanRecords(task TableScanTask, sender func(IndexRecor
 			execDetails = kvutil.ExecDetails{}
 
 			_, tableScanRowCount := distsqlCtx.RuntimeStatsColl.GetCopCountAndRows(tableScanCopID)
-			idxResults = append(idxResults, IndexRecordChunk{ID: task.ID, Chunk: srcChk, Done: done, ctx: w.ctx, tableScanRowCount: tableScanRowCount - lastTableScanRowCount, conditionPushed: conditionPushed})
+			idxResult := IndexRecordChunk{ID: task.ID, Chunk: srcChk, Done: done, ctx: w.ctx, tableScanRowCount: tableScanRowCount - lastTableScanRowCount, conditionPushed: conditionPushed}
 			lastTableScanRowCount = tableScanRowCount
+			if streamResults {
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go]: #### ℹ️ **[Info]** N/N-1 mixed-version behavior for new checkpoint emission timing is not demonstrated

**Why**
This change adjusts when chunk progress is emitted in one backfill mode. The diff does not include explicit mixed-version or rollback validation for that transition.

**Scope**
pkg/ddl/backfilling_operators.go:594

**Risk if unchanged**
If old/new binaries differ in operational assumptions around partial checkpoint progress timing, rolling upgrades may expose edge-case resume behavior that is hard to diagnose.

**Evidence**
Result emission moved into the scan loop for `UseCloudStorage` (`sendResult(idxResult); continue`), while no upgrade/downgrade or mixed-version coverage appears in the changed tests.

**Change request**
is this backward compatible with N-1 nodes? can we add an upgrade/compat test for this path or document the expected mixed-version behavior explicitly?

File: pkg/ddl/backfilling_operators.go (hunk 4 above)
Comment (joechenrh) [reply pkg/ddl/backfilling_operators.go]: Done in https://github.com/pingcap/tidb/commit/41e7df5ed22cd3b0f379fc8d20d3a2442662e22b . Renamed `streamResults` to `enableStreaming` so it reads as a boolean flag instead of a result container.

File: pkg/ddl/backfilling_operators.go (hunk 3 above)
Comment (joechenrh) [reply pkg/ddl/backfilling_operators.go]: Done in https://github.com/pingcap/tidb/commit/41e7df5ed22cd3b0f379fc8d20d3a2442662e22b . I also scoped the post-loop flush to `if !enableStreaming`, since that replay only exists on the local-ingest buffered path.

File: pkg/ddl/backfilling_operators.go (hunk 2 above)
Comment (joechenrh) [reply pkg/ddl/backfilling_operators.go]: Done in https://github.com/pingcap/tidb/commit/41e7df5ed22cd3b0f379fc8d20d3a2442662e22b . I rewrote the branch as an explicit `if/else` so the streaming send path and the buffered append path sit next to each other more clearly.

File: tests/realtikvtest/addindextest4/integration_test.go (hunk 6 above)
Comment (joechenrh) [reply tests/realtikvtest/addindextest4/integration_test.go:512]: I don't think this is silently passing today. `scanRecords` uses `reorgMeta.GetBatchSize()` as the chunk cap, and the default `tidb_ddl_reorg_batch_size` is 256, so the 2000 inserted rows here force multiple fetches and consume the second-step failpoint expression `1*return(false)->1*return(true)`.

See https://github.com/pingcap/tidb/blob/41e7df5ed21f517b9f2978c0d45809149dffecb7/pkg/ddl/ingest/config.go#L95-L99 and https://github.com/pingcap/tidb/blob/41e7df5ed21f517b9f2978c0d45809149dffecb7/pkg/sessionctx/vardef/tidb_vars.go#L1516 . If we later make the batch sizing in this test dynamic, then I agree we should pin it explicitly.

File: tests/realtikvtest/addindextest4/integration_test.go (hunk 5 above)
Comment (joechenrh) [reply tests/realtikvtest/addindextest4/integration_test.go:461]: This is fair as a cleanup idea, but I'd prefer to keep the two tests split here.

They cover different failure modes (`ddlIngestFailOnceBeforeCheckpointUpdated` vs `mockScanRecordPartialError`), and after extracting `setupAddIndexClassicVars` the remaining duplication is mostly the common DDL setup/assertions. I'd rather not add another helper layer in the same PR for that.

File: pkg/ddl/backfilling_operators.go (hunk 7 above)
Comment (joechenrh) [reply pkg/ddl/backfilling_operators.go]: Same point here: I don't think this PR changes checkpoint emission timing on the global-sort path. `sendResult` only touches checkpoints when `w.cpOp != nil`, and the global-sort pipeline wires `cpOp=nil`, so there isn't a new mixed-version checkpoint-compat surface from that branch.

File: pkg/ddl/backfilling_operators.go (hunk 4 above)
Comment (joechenrh) [reply pkg/ddl/backfilling_operators.go]: I don't think this one applies. The global-sort pipeline constructs `TableScanOperator` with `cpOp=nil` in `NewWriteIndexToExternalStoragePipeline`, and `scanRecords` only updates checkpoint state behind `if w.cpOp != nil`.

So `UseCloudStorage` changes when chunks are handed downstream, but not checkpoint resume state on that path. The partial-scan regression test is intentionally on the local-ingest path, where checkpoint resume actually exists.

**Review by D3Hunter — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
