### PR TITLE
expression: fix the error of parsing time

### LINKED ISSUE #21455: Builtin function `MAKETIME` produces wrong results
### 1. Minimal reproduce step (Required)

```sql
select maketime(838, 50, 59.1);
select maketime(838, 50, 59.999);
select maketime(838, 58, 59.1);
select maketime(838, 58, 59.999);
```

returns

```sql
+-------------------------+
| maketime(838, 50, 59.1) |
+-------------------------+
| 34 days, 22:50:59       |
+-------------------------+
+---------------------------+
| maketime(838, 50, 59.999) |
+---------------------------+
| 34 days, 22:50:59         |
+---------------------------+
+-------------------------+
| maketime(838, 58, 59.1) |
+-------------------------+
| 34 days, 22:58:59       |
+-------------------------+
+---------------------------+
| maketime(838, 58, 59.999) |
+---------------------------+
| 34 days, 22:58:59         |
+---------------------------+
```

### 2. What did you expect to see? (Required)

```sql
+--------------------------+
| maketime(838, 50, 59.1)  |
+--------------------------+
| 34 days, 22:50:59.100000 |
+--------------------------+
+---------------------------+
| maketime(838, 50, 59.999) |
+---------------------------+
| 34 days, 22:50:59.999000  |
+---------------------------+
+--------------------------+
| maketime(838, 58, 59.1)  |
+--------------------------+
| 34 days, 22:58:59.100000 |
+--------------------------+
+---------------------------+
| maketime(838, 58, 59.999) |
+---------------------------+
| 34 days, 22:58:59.999000  |
+---------------------------+
```

### 3. What is your TiDB version? (Required)

5723034c061711107ecc2edc0fbc97d366e8396e

## Score
- 200

## Mentor
- @zhongzc

### PR DESCRIPTION
**Pull request by jackwener**
### What problem does this PR solve?

Issue Number: close #21455

Problem Summary: fix the error of parsing time

### What is changed and how it works?

What's Changed: tidb/expression/builtin_time.go

How it Works: add an addtional check.

### Related changes

- PR to update `expression/builtin_time.go` and `expression/builtin_time_test.go`:
- Need to cherry-pick to the release branch

### Check List

Tests 

- Unit test

Side effects

- No

### Release note

- Now time can be parsed correctly.

### CODE REVIEW

File: expression/builtin_time.go [hunk 1]
```diff
@@ -5799,7 +5799,7 @@ func (b *builtinMakeTimeSig) makeTime(hour int64, minute int64, second float64,
 		hour = 838
 		overflow = true
 	}
-	if hour == -838 || hour == 838 {
+	if (hour == -838 || hour == 838) && minute == 59 {
 		if second > 59 {
 			second = 59
 		}
```
Comment (zhongzc) [inline expression/builtin_time.go:5805]:
```suggestion
	if (hour == -838 || hour == 838) && minute == 59 && second > 59 {
		overflow = true
```

**Review by zhongzc — APPROVED** [review]
LGTM

**Review by andylokandy — APPROVED** [review]

**Comment by jyz0309** [comment]
LGTM

**Review by jyz0309 — APPROVED** [review]

**Comment by jyz0309** [comment]
@XuHuaiyu PTAL

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
