### PR TITLE
charset: fix data race in the Collation.IsDefault

### LINKED ISSUE #35145: DATA RACE in the switchDefaultCollation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
 WARNING: DATA RACE
Write at 0x000008b55ca8 by goroutine 115:
  github.com/pingcap/tidb/util/collate.switchDefaultCollation()
      /go/tidb/util/collate/charset.go:27 +0x28f
  github.com/pingcap/tidb/util/collate.SetNewCollationEnabledForTest()
      /go/tidb/util/collate/collate.go:84 +0x26
  github.com/pingcap/tidb/session.BootstrapSession()
      /go/tidb/session/session.go:2860 +0x3b8
  github.com/pingcap/tidb/testkit.bootstrap()
      /go/tidb/testkit/mockstore.go:49 +0x8c
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      /go/tidb/testkit/mockstore.go:42 +0xcd
  github.com/pingcap/tidb/testkit.CreateMockStore()
      /go/tidb/testkit/mockstore.go:34 +0x84
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey.func1()
      /go/tidb/executor/point_get_test.go:689 +0x69
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey.func2()
      /go/tidb/executor/point_get_test.go:800 +0xde
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey.func3()
      /go/tidb/executor/point_get_test.go:801 +0x8e
Previous write at 0x000008b55ca8 by goroutine 117:
  github.com/pingcap/tidb/util/collate.switchDefaultCollation()
      /go/tidb/util/collate/charset.go:27 +0x28f
  github.com/pingcap/tidb/util/collate.SetNewCollationEnabledForTest()
      /go/tidb/util/collate/collate.go:84 +0x26
  github.com/pingcap/tidb/session.BootstrapSession()
      /go/tidb/session/session.go:2860 +0x3b8
  github.com/pingcap/tidb/testkit.bootstrap()
      /go/tidb/testkit/mockstore.go:49 +0x8c
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      /go/tidb/testkit/mockstore.go:42 +0xcd
  github.com/pingcap/tidb/testkit.CreateMockStore()
      /go/tidb/testkit/mockstore.go:34 +0x84
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey.func1()
      /go/tidb/executor/point_get_test.go:689 +0x69
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey.func2()
      /go/tidb/executor/point_get_test.go:800 +0xde
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey.func3()
      /go/tidb/executor/point_get_test.go:801 +0x8e
Goroutine 115 (running) created at:
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey()
      /go/tidb/executor/point_get_test.go:798 +0x3e9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47
Goroutine 117 (running) created at:
  github.com/pingcap/tidb/executor_test.TestPointGetLockExistKey()
      /go/tidb/executor/point_get_test.go:798 +0x3e9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47 
```

https://prow.pingcap.net/view/gs/pingcapprow/logs/tidb_race/1533003187395497984

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #35145

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Manual test (add detailed scripts or steps below)
```
make ut race
```

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: util/collate/charset.go [hunk 1]
```diff
@@ -23,6 +23,6 @@ func switchDefaultCollation(flag bool) {
 	} else {
 		charset.CharacterSetInfos[charset.CharsetGBK].DefaultCollation = charset.CollationGBKBin
 	}
-	charset.CharacterSetInfos[charset.CharsetGBK].Collations[charset.CollationGBKBin].IsDefault = !flag
-	charset.CharacterSetInfos[charset.CharsetGBK].Collations[charset.CollationGBKChineseCI].IsDefault = flag
+	charset.CharacterSetInfos[charset.CharsetGBK].Collations[charset.CollationGBKBin].IsDefault.Store(!flag)
```
Comment (Defined2014) [inline util/collate/charset.go:26]: I think `switchDefaultCollation` is only called in test, so the data race only appears in test. Should we change a lot to fix this, not sure for me.

Comment (hawkingrei) [reply util/collate/charset.go:26]: it may be related with 

https://github.com/pingcap/tidb/blob/1fac141f35446c8942e2f413afbe2cd54cdb0964/executor/point_get_test.go#L800

Comment (hawkingrei) [reply util/collate/charset.go:26]: All the data race goroutine starts with L800. We can not run parallelly test or set atomic for this value.

Comment (Defined2014) [reply util/collate/charset.go:26]: or move `wg.Wait()` into for loop

Comment (hawkingrei) [reply util/collate/charset.go]: I have removed the outside ```wg.Wait()```  when to call ```testLock```.

**Review by you06 — APPROVED** [review]
