### PR TITLE
expression: avoid unnecessary warnings/errors when folding constants in control expr

### LINKED ISSUE #17725: expression: short-cut expressions cause unnecessary warnings, which even causes errors in update statements.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> use test;
Database changed
mysql> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert t values (1);
Query OK, 1 row affected (0.01 sec)

mysql> select case when a=1 then 1 else 1/(a-1) end from t;
+---------------------------------------+
| case when a=1 then 1 else 1/(a-1) end |
+---------------------------------------+
|                                     1 |
+---------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)

mysql> select if(a=1,1,1/(a-1)) from t;
+-------------------+
| if(a=1,1,1/(a-1)) |
+-------------------+
|                 1 |
+-------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)

 select ifnull(1,1/0);
+---------------+
| ifnull(1,1/0) |
+---------------+
|             1 |
+---------------+
1 row in set, 1 warning (0.00 sec)

select case  when 1/1 then 1/1 when 1/0 then 1/0 end;
+-----------------------------------------------+
| case  when 1/1 then 1/1 when 1/0 then 1/0 end |
+-----------------------------------------------+
|                                        1.0000 |
+-----------------------------------------------+
1 row in set, 2 warnings (0.01 sec)

```

We may also handle AND and OR.
```
mysql> select 0 and 1/0;
+-----------+
| 0 and 1/0 |
+-----------+
|         0 |
+-----------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```

```
mysql> select COALESCE(1, 1/0);
+------------------+
| COALESCE(1, 1/0) |
+------------------+
|                1 |
+------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```

```
mysql> select * from t0;
+------+
| c0   |
+------+
|    0 |
|    1 |
+------+
2 rows in set (0.00 sec)

mysql> select interval(t0.c0, -1,0,1,2,1/0) from t0;
+-------------------------------+
| interval(t0.c0, -1,0,1,2,1/0) |
+-------------------------------+
|                             2 |
|                             5 |
+-------------------------------+
2 rows in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```
### 2. What did you expect to see? (Required)
no warnings like in MySQL
### 3. What did you see instead (Required)
a warning
### 4. Affected version (Required)

v4.0.0

### 5. Root Cause Analysis
1. Bug from the vectorization run all execution paths,
2. constant folding folds all paths.

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #17725 

following https://github.com/pingcap/tidb/pull/19367, avoid unnecessary warnings/errors when folding constants in control expr.

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: 

the scalar `if` is wrong, to be corrected here,
add `tryFoldCounter` to try fold constrants but not throw warnings/erros.
correct the special handler for control expressions.

How it Works:

each branch of control expressions fold contrants whenever possible, but not throw uncessary warnings/errors. When folding the control expressions, it run the normal branches and return normally like evaluating scalar expressions. If a branch is not const, it will stop folding constrants.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- avoid unnecessary warnings/errors when folding constants in control expr

### CODE REVIEW

File: expression/constant_fold.go [hunk 1]
```diff
@@ -56,12 +56,8 @@ func ifFoldHandler(expr *ScalarFunction) (Expression, bool) {
...
 		return foldConstant(args[2])
 	}
-	var isDeferred, isDeferredConst bool
-	expr.GetArgs()[1], isDeferred = foldConstant(args[1])
-	isDeferredConst = isDeferredConst || isDeferred
-	expr.GetArgs()[2], isDeferred = foldConstant(args[2])
-	isDeferredConst = isDeferredConst || isDeferred
-	return expr, isDeferredConst
+	// if the condition is not const, which branch is unknown to run, so directly return.
+	return expr, false
```
Comment (zz-jason) [inline expression/constant_fold.go:60]: There probably are some constants in its arguments that can be folded. For example:
```sql
select if(a, 1+100, 2+100) from t;
```

Comment (fzhedu) [reply expression/constant_fold.go:60]: for control expression, it involves two steps: its all parameters (branches), itself.

1. When invocking `Enter`, each branch of control expressions fold contrants whenever possible, but not throw uncessary warnings/errors.
2. folding the control expression itself.

So the constants are folded with best. 
Your case is also folded.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: expression/scalar_function.go [hunk 2]
```diff
@@ -174,7 +174,7 @@ func typeInferForNull(args []Expression) {
 }
 
 // newFunctionImpl creates a new scalar function or constant.
-func newFunctionImpl(ctx sessionctx.Context, fold bool, funcName string, retType *types.FieldType, args ...Expression) (Expression, error) {
+func newFunctionImpl(ctx sessionctx.Context, fold int, funcName string, retType *types.FieldType, args ...Expression) (Expression, error) {
```
Comment (qw4990) [inline expression/scalar_function.go:177]: Almost LGTM. Please add some comments for the argument `fold`.

Comment (fzhedu) [reply expression/scalar_function.go:177]: ok

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by zz-jason — APPROVED** [review]
LGTM
