### PR TITLE
cgmon: fix the issue that CPU quota is 0 if it's not limited by cgroup

### LINKED ISSUE #61223: TiDB should be able to handle the case when `cgroup.max` doesn't exist and the cgroup config doesn't have cpu controller
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use `tiup cluster` to deploy a cluster in rockylinux 9.

### 2. What did you expect to see? (Required)

TiDB doesn't report any error.

### 3. What did you see instead (Required)

TiDB reports error that the `cpu.max` doesn't exist.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #61223

Problem Summary:

The cpu quota will always be 0 if it failed to get the cgroup limit. The same issue also exists for memory. 

### What changed and how does it work?

Change the logic of error handling in cgmon. Make the cpu quota defaults to the count of CPU, and the memory quota defaults to the memory get from `/proc/meminfo`. Then update these values according to the cgroup settings.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

1. Deploy master branch of tidb in rockylinux 9. Open the grafana. The cpu quota is 0.

image

2. Deploy this branch of TiDB in rockylinux 9. Open the grafana. The cpu quota is 16.

image

3. Modify the tiup config of TiDB. Set CPU quota to 800 and memory quota to 8G. The value is correct.

image
image

4. Manually remove the memory controller from related cgroup, so that TiDB will get error when it's reading the memory quota, then the memory quota goes to the memory of the whole machine (16G).

image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that the cpu quota is always 0 if `cpu.max` doesn't exist
```

### CODE REVIEW

File: pkg/util/cgmon/cgmon.go [hunk 1]
```diff
@@ -38,7 +38,6 @@ var (
 	ctx             context.Context
 	cancel          context.CancelFunc
 	wg              sync.WaitGroup
-	cfgMaxProcs     int
```
Comment (YangKeao) [inline pkg/util/cgmon/cgmon.go:41]: This variable is not used. I don't know why it was here before.

**Review by hawkingrei — APPROVED** [review]

File: pkg/util/cgmon/cgmon.go [hunk 2]
```diff
@@ -115,45 +114,47 @@ func refreshCgroupCPU() error {
...
 	if memLimit != lastMemoryLimit {
 		log.Info("set the memory limit", zap.Uint64("memLimit", memLimit))
 		metrics.MemoryLimit.Set(float64(memLimit))
 		lastMemoryLimit = memLimit
 	}
-	return nil
+	return err
 }
+
+var getCgroupCPUPeriodAndQuota = cgroup.GetCPUPeriodAndQuota
```
Comment (hawkingrei) [inline pkg/util/cgmon/cgmon.go:159]: This kind of variable is best placed at the beginning of the file

**Review by Defined2014 — APPROVED** [review]
