### PR TITLE
pkg/lightning: fix TestRegionJobBaseWorker waitgroup race

### LINKED ISSUE #66702: lightning: TestRegionJobBaseWorker is flaky in nextgen CI (sync: negative WaitGroup counter)
### 1. Minimal reproduce step (Required)

Observed in CI run:
- Pipeline: `pull_unit_test_next_gen`
- Run: `#11975` (2026-03-05)
- Node log: https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/pull_unit_test_next_gen/runs/11975/nodes/54/log/?start=0

Failure happens in:
- `//pkg/lightning/backend/local:local_test (shard 27 of 50)`
- `TestRegionJobBaseWorker/if_the_region_has_no_leader,_rescan_the_region`

The first attempt failed with panic:
- `sync: negative WaitGroup counter`
- stack includes:
  - `pkg/lightning/backend/local/job_worker.go:95` (`mockJobWgDone` failpoint path)
  - `pkg/lightning/backend/local/region_job.go:312` (`regionJob.done -> wg.Done`)

Same shard then passed on retry and Bazel marked it `FLAKY`.

Root-cause analysis from code path:
- In test helper `prepareAndExecute`:
  - `jobInCh <- job` is executed before `jobWg.Add(1)`.
- In the no-leader subtest, failpoint `mockJobWgDone` is set to `return(3)`.
- Worker can process job immediately and execute `w.jobWg.Add(-3)` before producer goroutine executes `jobWg.Add(1)`.
- If this interleaving happens, WaitGroup counter goes negative and panics.

Relevant code:
- `pkg/lightning/backend/local/job_worker_test.go:134-135`
- `pkg/lightning/backend/local/job_worker.go:93-96`
- `pkg/lightning/backend/local/region_job.go:312`

### 2. What did you expect to see? (Required)

`TestRegionJobBaseWorker` should be deterministic and should not panic with `sync: negative WaitGroup counter`.

### 3. What did you see instead (Required)

A flaky panic in CI:
- First attempt fails with `sync: negative WaitGroup counter`.
- Retry passes, and test target is reported as `FLAKY`.

### 4. What is your TiDB version? (Required)

N/A for SQL runtime (this is a unit-test-only failure in CI).

Test context:
- TiDB repo `master` nextgen unit test pipeline
- CI run `pull_unit_test_next_gen #11975` on 2026-03-05

---

Potential fix direction:
- In `prepareAndExecute`, move `jobWg.Add(1)` before `jobInCh <- job` to avoid race between producer accounting and worker-side decrement/failpoint behavior.

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #66702

Problem Summary:

`TestRegionJobBaseWorker/if_the_region_has_no_leader,_rescan_the_region` is flaky in nextgen CI. In test helper `prepareAndExecute`, `jobInCh <- job` happened before `jobWg.Add(1)`, so worker-side `Done` could race ahead and trigger `sync: negative WaitGroup counter`.

### What changed and how does it work?

- Reordered test helper accounting to call `jobWg.Add(1)` before `jobInCh <- job`.
- This guarantees waitgroup accounting is established before workers can decrement it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Tests**
  * Improved job worker test to tighten synchronization around enqueue timing, reducing flakiness for timing-sensitive scenarios and ensuring more reliable verification of job enqueueing and processing behavior.

### CODE REVIEW

File: pkg/lightning/backend/local/job_worker_test.go [hunk 1]
```diff
@@ -149,21 +154,34 @@ func TestRegionJobBaseWorker(t *testing.T) {
...
 			&regionJob{stage: regionScanned, ingestData: mockIngestData{}, region: dummyRegion},
-			nil, nil, nil)
+			nil, nil, nil, nil)
 		require.NoError(t, err)
 		require.Equal(t, 1, len(jobOutCh))
 		outJob := <-jobOutCh
 		require.Equal(t, ingested, outJob.stage)
 	})
 
+	t.Run("track waitgroup before enqueue to avoid negative counter", func(t *testing.T) {
```
Comment (joechenrh) [inline pkg/lightning/backend/local/job_worker_test.go]: Is this test necessary?

Comment (D3Hunter) [reply pkg/lightning/backend/local/job_worker_test.go]: 😓
```
Not strictly necessary for the runtime fix itself, but necessary for the bugfix quality bar.

The reorder at [job_worker_test.go (line 136)](app://-/index.html?hostId=local#) fixes the race.
The new subtest at [job_worker_test.go (line 164)](app://-/index.html?hostId=local#) is what makes this a stable regression guard. Without it, we’re back to relying on flaky scheduling/CI to detect reintroduction.
Repo policy in AGENTS.md says bug fixes must include a regression test and red/green evidence; this test is the deterministic proof.
If you want a smaller diff, I can remove the helper hook and keep only the reorder, but I’d recommend keeping this test (or replacing it with an equally deterministic one).
```
