### PR TITLE
planner:  correctly handle expression.ScalarFunction in the buildSemiJoinForSetOperator

### LINKED ISSUE #40279: query got error "interface conversion: expression.Expression is *expression.ScalarFunction, not *expression.Column"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `e162aa34-6b56-4223-b14d-f8a51b935837` (
  `1962ae66-f5f5-4e85-8550-d59e24887fc3` char(155) NOT NULL DEFAULT 'on1unvbxp5sko6mbetn3ku26tuiyju7w3wc0olzto9ew7gsrx',
  `f4ae1c37-92f1-4f91-9080-c15c9e106c42` mediumint(9) NOT NULL DEFAULT '2525518',
  PRIMARY KEY (`f4ae1c37-92f1-4f91-9080-c15c9e106c42`,`1962ae66-f5f5-4e85-8550-d59e24887fc3`) /*T![clustered_index] CLUSTERED */
);
( select    `e162aa34-6b56-4223-b14d-f8a51b935837`.`f4ae1c37-92f1-4f91-9080-c15c9e106c42` as r0 , from_base64( `e162aa34-6b56-4223-b14d-f8a51b935837`.`1962ae66-f5f5-4e85-8550-d59e24887fc3` ) as r1 from `e162aa34-6b56-4223-b14d-f8a51b935837` ) except ( select    `e162aa34-6b56-4223-b14d-f8a51b935837`.`1962ae66-f5f5-4e85-8550-d59e24887fc3` as r0 , elt(2, `e162aa34-6b56-4223-b14d-f8a51b935837`.`1962ae66-f5f5-4e85-8550-d59e24887fc3` , `e162aa34-6b56-4223-b14d-f8a51b935837`.`1962ae66-f5f5-4e85-8550-d59e24887fc3` ) as r1 from `e162aa34-6b56-4223-b14d-f8a51b935837`);
```

### 2. What did you expect to see? (Required)
No error
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #40279

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
██╗    ██╗██╗██████╗ 
██║    ██║██║██╔══██╗
██║ █╗ ██║██║██████╔╝
██║███╗██║██║██╔═══╝ 
╚███╔███╔╝██║██║     
 ╚══╝╚══╝ ╚═╝╚═╝

File: planner/core/logical_plans.go [hunk 1]
```diff
@@ -369,8 +369,8 @@ func (p *LogicalJoin) extractFDForOuterJoin(filtersFromApply []expression.Expres
 // means whether there is a `NullEQ` of a join key.
 func (p *LogicalJoin) GetJoinKeys() (leftKeys, rightKeys []*expression.Column, isNullEQ []bool, hasNullEQ bool) {
 	for _, expr := range p.EqualConditions {
-		leftKeys = append(leftKeys, expr.GetArgs()[0].(*expression.Column))
-		rightKeys = append(rightKeys, expr.GetArgs()[1].(*expression.Column))
+		leftKeys = append(leftKeys, expression.ExtractColumnsFromExpression(expr.GetArgs()[0], nil)...)
```
Comment (wjhuang2016) [inline planner/core/logical_plans.go:372]: Why not use ExtractColumns?

Comment (AilinKid) [inline planner/core/logical_plans.go:372]: i‘ll change the`buildSemiJoinForSetOperator` in `buildExcept`, add another projection under it like what `updateEQCond` does.

EQ((a-b)，(c-d)), for join keys extracted here, means (a,b), (c,d), the join match means the exact equivalence for a=c, and b = d here， actually, we need a project (a-b) as E，(c-d) as F， and join keys here are simply as(E),(F), the join match means the exact equivalence for E = F here. @winoros

Comment (hawkingrei) [reply planner/core/logical_plans.go]: ```ExtractColumnsFromExpression``` have been removed.

**Review by wjhuang2016 — APPROVED** [review]

**Comment by AilinKid** [comment]
```
mysql> CREATE TABLE `t2` (   `a` varchar(20) CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t2 values(0xCED2);
Query OK, 1 row affected (0.04 sec)

mysql> (select elt(2,t2.a,t2.a) from t2) except (select 0xCED2  from t2);
Empty set (0.01 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.31    |
+-----------+
1 row in set (0.03 sec)
```

this 
```
tidb>  (select elt(2,t2.a,t2.a) from t2) except (select 0xCED2  from t2);
+------------------+
| elt(2,t2.a,t2.a) |
+------------------+
| 我               |
+------------------+
1 row in set (0.00 sec)

tidb> select version();
+------------------------------------------------+
| version()                                      |
+------------------------------------------------+
| 5.7.25-TiDB-v6.6.0-alpha-110-gb7d25760c2-dirty |
+------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by hawkingrei** [comment]
@AilinKid Let me try to fix it.

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -1747,7 +1760,7 @@ func (b *PlanBuilder) buildSemiJoinForSetOperator(
 		if err != nil {
 			return nil, err
 		}
-		if leftCol.RetType.GetType() != rightCol.RetType.GetType() {
+		if leftCol.RetType.GetType() != rightCol.RetType.GetType() || (leftIsColumnList != nil && !leftIsColumnList[j]) {
```
Comment (AilinKid) [inline planner/core/logical_plan_builder.go:1763]:
```
_, leftArgIsColumn := eqCond.(*expression.ScalarFunction).GetArgs()[0].(*expression.Column)
_, rightArgIsColumn := eqCond.(*expression.ScalarFunction).GetArgs()[1].(*expression.Column)
if leftCol.RetType.GetType() != rightCol.RetType.GetType() || !leftArgIsColumn || !rightArgIsColumn {
```

File: planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -1736,6 +1736,19 @@ func (b *PlanBuilder) buildSemiJoinForSetOperator(
...
+			result := make([]bool, 0, len(lp.Exprs))
+			for _, expr := range lp.Exprs {
+				_, ok := expr.(*expression.Column)
+				result = append(result, ok)
+			}
+			return result
+		}
+		return nil
+	}
+	leftIsColumnList := isAllColumn(leftOriginPlan)
```
Comment (AilinKid) [inline planner/core/logical_plan_builder.go:1751]: seems we don't need here

File: planner/core/logical_plan_builder.go (hunk 2 above)
Comment (hawkingrei) [reply planner/core/logical_plan_builder.go:1763]: Done

**Review by AilinKid — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
