### PR TITLE
ddl, test: fix deadloop in test about doDDLJob

### LINKED ISSUE #19798: `testRunInterruptedJob` may cause deadlock
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

diff:

```
diff --git a/ddl/ddl.go b/ddl/ddl.go
index 755e972b0..98d2635b1 100644
--- a/ddl/ddl.go
+++ b/ddl/ddl.go
@@ -460,6 +460,7 @@ func (d *ddl) asyncNotifyWorker(jobTp model.ActionType) {
 }

 func (d *ddl) doDDLJob(ctx sessionctx.Context, job *model.Job) error {
+       time.Sleep(1 * time.Second)
        if isChanClosed(d.ctx.Done()) {
                return d.ctx.Err()
        }
diff --git a/ddl/restart_test.go b/ddl/restart_test.go
index 489f635ec..66b8d09f9 100644
--- a/ddl/restart_test.go
+++ b/ddl/restart_test.go
@@ -161,6 +161,7 @@ LOOP:
                select {
                case <-ticker.C:
                        d.Stop()
+                       time.Sleep(2 * time.Second)
                        c.Assert(s.getDDLSchemaVer(c, d), GreaterEqual, ver)
                        d.restartWorkers(context.Background())
                        time.Sleep(time.Millisecond * 20)
```

### 2. What did you expect to see? (Required)

test pass

### 3. What did you see instead (Required)

deadlock

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #19798 

Problem Summary:

### What is changed and how it works?

What's Changed: revert some changes made in #18844, which may cause deadloop 

How it works: #18844 faces a problem of data race at `d.ctx`, in fact add `// +build !race` is enough, other changes wrongly changed the behaviour of ddl workers and `doDDLJobs`, which may cause a deadloop and weaken the code.

NOTE that `doDDLJob` will block if ddl worker accidentally exit (but stop block if restart later), at waiting `task.err` channel. If we want to resolve this block, such as exit when context canceled, it will cause restarted ddl worker of the sending end's block. Sending end's block can't be resolved by detecting context canceled in same way, because `d.ctx` may be replaced thus new context is not canceled at that time.
So I just hope ddl worker won't accidentally exit

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

File: ddl/ddl.go [hunk 1]
```diff
@@ -459,15 +458,16 @@ func (d *ddl) asyncNotifyWorker(jobTp model.ActionType) {
...
 func (d *ddl) doDDLJob(ctx sessionctx.Context, job *model.Job) error {
-	if isChanClosed(d.ctx.Done()) {
-		return d.ctx.Err()
-	}
-
 	// Get a global job ID and put the DDL job in the queue.
 	job.Query, _ = ctx.Value(sessionctx.QueryString).(string)
 	task := &limitJobTask{job, make(chan error)}
 	d.limitJobCh <- task
+	// worker should restart to continue handling tasks in limitJobCh, and send back through task.err
```
Comment (lance6716) [inline ddl/ddl.go:470]: sorry I misunderstood the behaviour of ddl worker in https://github.com/pingcap/tidb/pull/18844 😢

File: ddl/ddl.go [hunk 2]
```diff
@@ -318,7 +318,6 @@ func (d *ddl) Start(ctxPool *pools.ResourcePool) error {
 	logutil.BgLogger().Info("[ddl] start DDL", zap.String("ID", d.uuid), zap.Bool("runWorker", RunWorker))
 	d.ctx, d.cancel = context.WithCancel(d.ctx)
 
-	d.wg.Add(1)
```
Comment (lance6716) [inline ddl/ddl.go:321]: moved into `limitDDLJobs`

File: ddl/restart_test.go [hunk 3]
```diff
@@ -29,11 +30,8 @@ import (
 // restartWorkers is like the function of d.start. But it won't initialize the "workers" and create a new worker.
 // It only starts the original workers.
 func (d *ddl) restartWorkers(ctx context.Context) {
-	d.cancel()
-	d.wg.Wait()
 	d.ctx, d.cancel = context.WithCancel(ctx)
 
-	d.wg.Add(1)
```
Comment (lance6716) [inline ddl/restart_test.go:36]: moved into `limitDDLJobs`

File: ddl/ddl.go [hunk 4]
```diff
@@ -459,15 +458,16 @@ func (d *ddl) asyncNotifyWorker(jobTp model.ActionType) {
 	}
 }
 
+// doDDLJob will return
+// - nil: found in history DDL job and no job error
+// - context.Cancel: job has been sent to worker, but not found in history DDL job before cancel
+// - other: found in history DDL job and return that job error
 func (d *ddl) doDDLJob(ctx sessionctx.Context, job *model.Job) error {
-	if isChanClosed(d.ctx.Done()) {
```
Comment (lance6716) [inline ddl/ddl.go:463]: revert this part from #18844

File: ddl/restart_test.go [hunk 5]
```diff
@@ -29,11 +30,8 @@ import (
 // restartWorkers is like the function of d.start. But it won't initialize the "workers" and create a new worker.
 // It only starts the original workers.
 func (d *ddl) restartWorkers(ctx context.Context) {
-	d.cancel()
```
Comment (lance6716) [inline ddl/restart_test.go:32]: revert this part from #18844

**Comment by lance6716** [comment]
PTAL @wjhuang2016 @zimulala

**Comment by lance6716** [comment]
PTAL @AilinKid

File: ddl/ddl.go (hunk 2 above)
Comment (zimulala) [reply ddl/ddl.go:321]: Why put it into `limitDDLJobs `? If put it into `limitDDLJobs`,  how about the case of calling `d.wg.Wait()` before `go d.limitDDLJobs()`.

Comment (lance6716) [reply ddl/ddl.go:321]: It looks clear to move `d.wg.Add(1)` and `d.wg.Done()` together since currently all call to `d.wg.Add(1)` are following `go d.limitDDLJobs()`.

I'm not sure what's the required sequence of "calling `d.wg.Wait()` before `go d.limitDDLJobs()`". If we need manually 

- `wg.Add`
- do something
- `wg.Wait`
- run `limitDDLJobs`

then what are we waiting for? Currently the only `wg.Done` is in `limitDDLJobs`, so that means we are waiting for previous `limitDDLJobs` finishing. That should equal to put `wg.Add` into `limitDDLJobs` and doesn't need us manually call it.

File: ddl/restart_test.go (hunk 3 above)
Comment (wjhuang2016) [reply ddl/restart_test.go:36]: Why do you move it?

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
