### PR TITLE
planner: replace outer-join null-reject evaluation with structural proof | tidb-test=pr/2724

### LINKED ISSUE #58793: Bug Case in Left Join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
DROP TABLE IF EXISTS t0;
DROP TABLE IF EXISTS t1;
CREATE TABLE t0(c0 TEXT(227));
CREATE TABLE t1 LIKE t0;
INSERT INTO t1 VALUES ('');
SELECT COUNT(*) FROM t1 LEFT JOIN t0 ON t0.c0 <> t1.c0 WHERE (NULL AND t1.c0) <=> (t0.c0 IS NOT NULL);
```

### 2. What did you expect to see? (Required)

see the following case:

### 3. What did you see instead (Required)

```sql
// MySQL 8.4.1
MySQL [test]> SELECT COUNT(*) FROM t1 LEFT JOIN t0 ON t0.c0 <> t1.c0 WHERE (NULL AND t1.c0) <=> (t0.c0 IS NOT NULL);
+----------+
| COUNT(*) |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)

// TiDB
mysql> SELECT COUNT(*) FROM t1 LEFT JOIN t0 ON t0.c0 <> t1.c0 WHERE (NULL AND t1.c0) <=> (t0.c0 IS NOT NULL);
+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
1 row in set (0.04 sec)
```

### 4. What is your TiDB version? (Required)

TiDB v8.5.0

### LINKED ISSUE #59162: Where clause on right outer join might lead to rows not being fetched
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES (1);
CREATE TABLE t1(c0 INT);
INSERT INTO t1(c0) VALUES (NULL), (0), (1);

SELECT
    t0.c0 AS ref0,
    t1.c0 AS ref1
FROM t0
RIGHT OUTER JOIN t1 ON t0.c0 = t1.c0
WHERE (t1.c0 AND (t0.c0 != NULL)) IS FALSE;
```

### 2. What did you expect to see? (Required)

|  ref0 |  ref1   |
| ----  | ----    |
| null  | 0       |

This is also the expected result in MySQL (8.0) and MariaDB (11.5).

### 3. What did you see instead (Required)

no rows

Moreover, the result obtained in the above query is inconsistent with the following:

```sql
SELECT
    t0.c0 AS ref0,
    t1.c0 AS ref1,
    (t1.c0 AND (t0.c0 != NULL)) IS FALSE AS ref2
FROM t0
RIGHT OUTER JOIN t1 ON t0.c0 = t1.c0;
```

In this query, the result is:

|  ref0 |  ref1   |  ref2   |
| ----  | ----    | ----    |
| null  | null    | 0       |
| null  | 0       | 1       |
| 1     | 1       | 0       |

Thus, the condition in the `WHERE` clause evaluates to true in the 2nd row, and the 2nd row should be returned in the original query.

### 4. What is your TiDB version? (Required)

```
                      tidb_version()                       
-----------------------------------------------------------
 Release Version: v8.5.1                                  +
 Edition: Community                                       +
 Git Commit Hash: fea86c8e35ad4a86a5e1160701f99493c2ee547c+
 Git Branch: HEAD                                         +
 UTC Build Time: 2025-01-16 07:40:33                      +
 GoVersion: go1.23.2                                      +
 Race Enabled: false                                      +
 Check Table Before Drop: false                           +
 Store: tikv 
(1 row)
```

### LINKED ISSUE #60080: Unexpected Empty Result When Adding OR Condition in TiDB
### 1. Minimal reproduce step (Required)
The following SQL statements create the necessary tables and insert sample data:
DROP TABLE IF EXISTS `t0`;
CREATE TABLE `t0` (
  `c0` int
) ;

INSERT INTO `t0` VALUES (61);

DROP TABLE IF EXISTS `t1`;
CREATE TABLE `t1` (
  `c1` int,
  `c2` double 
);
INSERT INTO `t1` VALUES (NULL,0);

DROP TABLE IF EXISTS `t2`;
CREATE TABLE `t2` (
  `c3` varchar(100),
  `c4` varchar(100)
) ;

INSERT INTO `t2` VALUES (NULL,NULL);

Then, executing the following two queries produces inconsistent behavior, which is unexpected:
Query 1:
select  
  subq_0.c_0 as c_0, 
  subq_0.c_1 as c_1, 
  subq_0.c_2 as c_2
from 
  (select  
        ref_1.c0 as c_0, 
        ref_0.c2 as c_1,  
        ref_0.c2 as c_2
      from 
        (t1 as ref_0
          right join (t0 as ref_1
            )
          on (ref_0.c1 = ref_1.c0 ))
       ) as subq_0
where ((('' = ( 
      select  
          (' n1`')  as c_0
        from 
          (t2 as ref_3
            left join t2 as ref_4
            on (ref_3.c4 = ref_4.c3 ))
        where ((subq_0.c_1) <> (subq_0.c_2)) 
          or (true)
        order by c_0 desc
         limit 1)) is null)) 
Output:
+------+------+------+
| c_0  | c_1  | c_2  |
+------+------+------+
|   61 | NULL | NULL |
+------+------+------+
1 row in set (0.01 sec)

Query 1:
select  
  subq_0.c_0 as c_0, 
  subq_0.c_1 as c_1, 
  subq_0.c_2 as c_2
from 
  (select  
        ref_1.c0 as c_0, 
        ref_0.c2 as c_1,  
        ref_0.c2 as c_2
      from 
        (t1 as ref_0
          right join (t0 as ref_1
            )
          on (ref_0.c1 = ref_1.c0 ))
       ) as subq_0
where (('' = ( 
      select  
          (' n1`')  as c_0
        from 
          (t2 as ref_3
            left join t2 as ref_4
            on (ref_3.c4 = ref_4.c3 ))
        where ((subq_0.c_1) <> (subq_0.c_2)) 
          or (true)
        order by c_0 desc
         limit 1)) is null)
     or ('' = ( 
      select  
          (' n1`')  as c_0
        from 
          (t2 as ref_3
            left join t2 as ref_4
            on (ref_3.c4 = ref_4.c3 ))
        where ((subq_0.c_1) <> (subq_0.c_2)) 
          or (true)
        order by c_0 desc
         limit 1))
Output:
Empty set (0.01 sec)

### 2. What did you expect to see? (Required)
Since the second query extends the condition from the first query with an additional OR clause, it should return at least the same rows as the first query, or possibly more.

### 3. What did you see instead (Required)
The first query returns one row (61, NULL, NULL).
The second query, which adds an additional OR condition, unexpectedly returns an empty set.

### 4. What is your TiDB version? (Required)
8.0.11-TiDB
master b6141ec589ed8e73176692dc982a210ad7cf070b

GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore |

### LINKED ISSUE #60081: Query with WHERE subq_0.c_0 IS NULL Incorrectly Returns a Row with NULL
### 1. Minimal reproduce step (Required)
The following SQL statements create the necessary tables and insert sample data:
```
DROP TABLE IF EXISTS `t0`;
CREATE TABLE `t0` (
  `c0` int
);
INSERT INTO `t0` VALUES (1),(2),(3),(4),(5),(6),(7),(8);

DROP TABLE IF EXISTS `t1`;
CREATE TABLE `t1` (
  `c1` double
);
INSERT INTO `t1` VALUES (1),(2),(3),(4),(5),(6),(7),(8);

DROP TABLE IF EXISTS `t2`;
DROP VIEW IF EXISTS `t2`;
CREATE VIEW `t2` (`c_0`,  `c_1`,  `c_2`) 
  AS SELECT DISTINCT `ref_0`.`c0` AS `c_0`,
  RIGHT( ((_UTF8MB4'1>yQ') ), 
    CASE WHEN (((`ref_0`.`c0`)>(SELECT DISTINCT `ref_0`.`c0` AS `c_0` FROM `t0`  
                  WHERE  ((SELECT `c1` AS `c1` FROM `t1` ORDER BY `t1`.`c1` LIMIT 2,1)) <
                ((SELECT `c1` AS `c1` FROM `t1` ORDER BY `t1`.`c1` LIMIT 1,1)) ORDER BY `c_0` LIMIT 1))) 
    THEN (1) ELSE (2) END) AS `c_1`,
  (SELECT SUM(`t1`.`c1`) AS `sum(t1.c1)` FROM `t1`) AS `c_2`
FROM `t0` AS `ref_0` 
ORDER BY`c_0`, `c_1`, `c_2`;
```

Then, executing the following two queries produces inconsistent behavior, which is unexpected:
Query 1:
```
select distinct 
  subq_0.c_0 as c_0
from 
  (select  
        (select c_2 from t2 order by t2.c_2 limit 1 offset 6)
           as c_0
      from 
        t2 as ref_0
      where (ref_0.c_2) is not null
      order by c_0 desc
       ) as subq_0
```
         limit 1)) is null)) 
Output:
```
+------+
| c_0  |
+------+
|   36 |
+------+
1 row in set (0.01 sec)
```

Query 1:
```
select distinct 
  subq_0.c_0 as c_0
from 
  (select  
        (select c_2 from t2 order by t2.c_2 limit 1 offset 6)
           as c_0
      from 
        t2 as ref_0
      where (ref_0.c_2) is not null
      order by c_0 desc
       ) as subq_0
where 
   ((subq_0.c_0) is null)
```
Output:
```
+------+
| c_0  |
+------+
| NULL |
+------+
1 row in set (0.01 sec)
```
### 2. What did you expect to see? (Required)
The query2 should return no rows, as there is no NULL value for subq_0.c_0 in query1.

### 3. What did you see instead (Required)
The query incorrectly returns one row with the value of c_0 as NULL.

### 4. What is your TiDB version? (Required)
8.0.11-TiDB
master https://github.com/pingcap/tidb/commit/b6141ec589ed8e73176692dc982a210ad7cf070b

GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore |

### LINKED ISSUE #60370: Incorrect Filtering Behavior When Using COALESCE in WHERE Clause in TiDB
### 1. Minimal reproduce step (Required)
The following SQL statements create tables, insert sample data, and execute queries that demonstrate unexpected behavior:
```
CREATE TABLE `t1` (
  `c1` int
);

INSERT INTO `t1` VALUES (1);

CREATE TABLE `t2` (
  `c2` int
);

INSERT INTO `t2` VALUES (-71);
```

Query1:
```
select  
  coalesce(NULL | (SIGN(STRCMP(case when ( (ref_0.c1) is null) then ('b') else ('b') end, 'a'))), 
                         length(nullif(CHAR(ref_1.c2), 'KV')))    as w_1
from 
  (t1 as ref_0
    right join t2 as ref_1
    on (ref_0.c1 = ref_1.c2))
where coalesce(NULL | (SIGN(STRCMP(case when ( (ref_0.c1) is null) then ('b') else ('b') end, 'a'))), 
                         length(nullif(CHAR(ref_1.c2), 'KV'))) > 0;
```

Output:
```
+------+
| w_1  |
+------+
|    4 |
+------+
1 row in set, 2 warnings (0.00 sec)
```

Query2:
```
select  
  coalesce(NULL | (SIGN(STRCMP(case when ( (ref_0.c1) is null) then ('b') else ('b') end, 'a'))), 
                         length(nullif(CHAR(ref_1.c2), 'KV')))    as w_1
from 
  (t1 as ref_0
    right join t2 as ref_1
    on (ref_0.c1 = ref_1.c2))
where coalesce(NULL | (SIGN(STRCMP(case when ( (ref_0.c1) is null) then ('b') else ('b') end, 'a'))), 
                         length(nullif(CHAR(ref_1.c2), 'KV'))) > 1;
```

Output:
`Empty set, 2 warnings (0.01 sec)`

### 2. What did you expect to see? (Required)
Since the first query returns w_1 = 4, and 4 > 0 and 4 > 1 are both TRUE, the second query should also return at least the same row.

The filtering condition w_1 > 1 should not remove all results, given that w_1 = 4 is valid.

### 3. What did you see instead (Required)
The second query unexpectedly returns an empty set, even though the computed w_1 value (4) satisfies the filtering condition > 1.

### 4. What is your TiDB version? (Required)
8.0.11-TiDB
master https://github.com/pingcap/tidb/commit/b6141ec589ed8e73176692dc982a210ad7cf070b

GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore |

### LINKED ISSUE #61327: Unexpected multiple join result
## Bug Report

Dear Developers,
I meet some unexpected result, and I analyze the root case. The optimizer wrongly choose inner join when handling left join in this query.

### 1. Minimal reproduce step (Required)

```sql

CREATE TABLE t0(c0 INT);
CREATE TABLE t2(c0 INT);
CREATE TABLE t3(c0 INT);
INSERT INTO t0 VALUES(0);
INSERT INTO t3 VALUES(3);

SELECT *
FROM t0
         LEFT JOIN (SELECT NULL AS col_2
                    FROM t2) as subQuery1
                   ON true
         INNER JOIN t3 ON (((((CASE 1
                                   WHEN subQuery1.col_2 THEN t3.c0
                                   ELSE NULL END)) AND (((t0.c0))))) < 1);
-- empty result, wrong result
-- expected result: 0, NULL, 3

```

### 2. What did you expect to see? (Required)
```
expected result: 0, NULL, 3
```

### 3. What did you see instead (Required)
```
empty result
```

Additionally, we can see from the query plan that the optimizer select a inner join algorithm (CARTESIAN inner join) for left join evaluation.
```
Projection_13,10000.00,root,"","database15.t0.c0, Column#5, database15.t3.c0"
└─HashJoin_15,10000.00,root,"","CARTESIAN inner join, other cond:lt(and(case(eq(1, cast(Column#5, double BINARY)), database15.t3.c0, NULL), database15.t0.c0), 1)"
  ├─HashJoin_16(Build),1.00,root,"",CARTESIAN inner join
  │ ├─TableReader_21(Build),1.00,root,"",data:TableFullScan_20
  │ │ └─TableFullScan_20,1.00,cop[tikv],table:t3,"keep order:false, stats:pseudo"
  │ └─TableReader_19(Probe),1.00,root,"",data:TableFullScan_18
  │   └─TableFullScan_18,1.00,cop[tikv],table:t0,"keep order:false, stats:pseudo"
  └─Projection_22(Probe),10000.00,root,"",<nil>->Column#5
    └─TableReader_24,10000.00,root,"",data:TableFullScan_23
      └─TableFullScan_23,10000.00,cop[tikv],table:t2,"keep order:false, stats:pseudo"


```

### 4. What is your TiDB version? (Required)

```
Release Version: v9.0.0-beta.1.pre-801-gd7d62ce0d2
Edition: Community
Git Commit Hash: d7d62ce0d26d15b902361010aab2526a4e2c511f
Git Branch: HEAD
UTC Build Time: 2025-05-25 04:45:44
GoVersion: go1.23.9
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### LINKED ISSUE #66824: Incorrect result with LEFT/RIGHT JOIN and NULL boolean expression in WHERE clause
### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);

INSERT INTO t1(c0) VALUES(1);

SELECT t1.c0 AS ref0, t0.c0 AS ref1 FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0) WHERE 1 >= ((t0.c0 OR NULL) AND (t1.c0 != t1.c0));
```

### 2. What did you expect to see? (Required)

```sql
mysql > SELECT t1.c0 AS ref0, t0.c0 AS ref1 FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0);

+------+------+
| ref0 | ref1 |
+------+------+
|    1 | NULL |
+------+------+
1 row in set (0.01 sec)

mysql> SELECT 1 >= ((t0.c0 OR NULL) AND (t1.c0 != t1.c0)) FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0);
+---------------------------------------------+
| 1 >= ((t0.c0 OR NULL) AND (t1.c0 != t1.c0)) |
+---------------------------------------------+
|                                           1 |
+---------------------------------------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```sql
mysql> SELECT t1.c0 AS ref0, t0.c0 AS ref1 FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0) WHERE 1 >= ((t0.c0 OR NULL) AND (t1.c0 != t1.c0));
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

Release Version: v8.5.5
Edition: Community
Git Commit Hash: 1fa258b833ff113883beeba40bc130be7ce66610
Git Branch: HEAD
UTC Build Time: 2026-01-14 22:20:57
GoVersion: go1.25.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore

### LINKED ISSUE #66825: Incorrect result with OUTER JOIN caused by wrong null-reject judgement on `IN (NULL, …)`
## Bug Report

This issue appears similar to https://github.com/pingcap/tidb/issues/66824, but the predicate involves an `IN (NULL, ...)` expression.

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1 LIKE t0; 

INSERT INTO t1(c0) VALUES(1);

SELECT t1.c0 AS ref0, t0.c0 AS ref1 FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0) WHERE (t1.c0 = 2) IN ( NULL, t0.c0 IS FALSE);

```
### 2. What did you expect to see? (Required)

```sql

mysql> SELECT t1.c0 AS ref0, t0.c0 AS ref1 FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0);
+------+------+
| ref0 | ref1 |
+------+------+
|    1 | NULL |
+------+------+
1 row in set (0.01 sec)

mysql> SELECT (t1.c0 = 2) IN ( NULL, t0.c0 IS FALSE) FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0);
+----------------------------------------+
| (t1.c0 = 2) IN ( NULL, t0.c0 IS FALSE) |
+----------------------------------------+
|                                      1 |
+----------------------------------------+
1 row in set (0.00 sec)
```

Since `(t1.c0 = 2) IN (NULL, t0.c0 IS FALSE)` evaluates to `1`, the row produced by the LEFT JOIN should not be filtered.

### 3. What did you see instead (Required)

```sql
mysql> SELECT t1.c0 AS ref0, t0.c0 AS ref1 FROM t1 LEFT JOIN t0 ON (t1.c0) = (t0.c0) WHERE (t1.c0 = 2) IN ( NULL, t0.c0 IS FALSE);
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

Release Version: v8.5.5
Edition: Community
Git Commit Hash: 1fa258b833ff113883beeba40bc130be7ce66610
Git Branch: HEAD
UTC Build Time: 2026-01-14 22:20:57
GoVersion: go1.25.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore

### LINKED ISSUE #67048: planner: prepared plan cache is skipped for parameter-invariant outer join null-reject checks
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1, t2;
create table t1 (a int, b int);
create table t2 (a int, b int);
insert into t1 values (1, 1), (2, 2), (3, 3), (4, 4), (5, 5);
insert into t2 values (2, 2), (3, 3), (4, 4), (5, 5);

prepare stmt from
'select t1.a as t1_a, t2.a as t2_a
 from t1 left join t2 on t1.a = t2.b
 where t2.a > ?
 order by t1.a';

set @v = 1;
execute stmt using @v;

set @v = 2;
execute stmt using @v;

select @@last_plan_from_cache;


# Another reproducer for a parameter-invariant non-null-reject case:
prepare stmt from
'select t1.a as t1_a, t2.a as t2_a
 from t1 left join t2 on t1.a = t2.b
 where t2.a > ? or t2.a is null
 order by t1.a';

set @v = 1;
execute stmt using @v;

set @v = 2;
execute stmt using @v;

select @@last_plan_from_cache;

```

### 2. What did you expect to see? (Required)

For predicates whose null-reject property is invariant across parameter bindings, TiDB should be able to determine the outcome structurally before falling back to the old null-reject path.

Examples:
* `t2.a > ?` is always null-rejected when the inner-side value is NULL
* `t2.a > ? or t2.a is null` is always non-null-rejected when the inner-side value is NULL

These cases should not need to skip prepared plan cache just because the predicate contains parameters.

### 3. What did you see instead (Required)

TiDB falls back to the legacy null-reject evaluation path for these parameterized predicates during outer-join simplification. In plan-cache-sensitive scenarios, this may mark the statement as uncacheable before the optimizer determines whether the null-reject property actually depends on the parameter values.

As a result, prepared plan cache is skipped even for parameter-invariant cases.

```
mysql> drop table if exists t1, t2;
Query OK, 0 rows affected, 2 warnings (0.00 sec)

mysql> create table t1 (a int, b int);
Query OK, 0 rows affected (0.02 sec)

mysql> create table t2 (a int, b int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1, 1), (2, 2), (3, 3), (4, 4), (5, 5);
Query OK, 5 rows affected (0.00 sec)
Records: 5  Duplicates: 0  Warnings: 0

mysql> insert into t2 values (2, 2), (3, 3), (4, 4), (5, 5);
Query OK, 4 rows affected (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> 
mysql> prepare stmt from
    -> 'select t1.a as t1_a, t2.a as t2_a
    '>  from t1 left join t2 on t1.a = t2.b
    '>  where t2.a > ?
    '>  order by t1.a';
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> set @v = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @v;
+------+------+
| t1_a | t2_a |
+------+------+
|    2 |    2 |
|    3 |    3 |
|    4 |    4 |
|    5 |    5 |
+------+------+
4 rows in set, 1 warning (0.00 sec)

mysql> 
mysql> set @v = 2;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @v;
+------+------+
| t1_a | t2_a |
+------+------+
|    3 |    3 |
|    4 |    4 |
|    5 |    5 |
+------+------+
3 rows in set, 1 warning (0.00 sec)

mysql> 
mysql> select @@last_plan_from_cache;
+------------------------+
| @@last_plan_from_cache |
+------------------------+
|                      0 |
+------------------------+
1 row in set (0.01 sec)

mysql> 
mysql> 
mysql> # Another reproducer for a parameter-invariant non-null-reject case:
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt from
    -> 'select t1.a as t1_a, t2.a as t2_a
    '>  from t1 left join t2 on t1.a = t2.b
    '>  where t2.a > ? or t2.a is null
    '>  order by t1.a';
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> set @v = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @v;
+------+------+
| t1_a | t2_a |
+------+------+
|    1 | NULL |
|    2 |    2 |
|    3 |    3 |
|    4 |    4 |
|    5 |    5 |
+------+------+
5 rows in set, 1 warning (0.00 sec)

mysql> 
mysql> set @v = 2;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @v;
+------+------+
| t1_a | t2_a |
+------+------+
|    1 | NULL |
|    3 |    3 |
|    4 |    4 |
|    5 |    5 |
+------+------+
4 rows in set, 1 warning (0.00 sec)

mysql> 
mysql> select @@last_plan_from_cache;
+------------------------+
| @@last_plan_from_cache |
+------------------------+
|                      0 |
+------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

lastest master

### LINKED ISSUE #67330: Query with NULLIF and CAST in WHERE clause returns incorrect results
## Bug Report

Hi, I found a logic bug in TiDB 8.5.5

### 1. Minimal reproduce step

```sql
-- create table
DROP TABLE IF EXISTS t0;
CREATE TABLE t0 ( c0 varchar(500)   DEFAULT NULL, c1 decimal(10,0) unsigned  DEFAULT NULL, UNIQUE KEY c1 (c1) );
DROP TABLE IF EXISTS t2;
CREATE TABLE t2 ( c1 decimal(10,0) unsigned  DEFAULT NULL, UNIQUE KEY c1 (c1) ) ;
INSERT INTO t2 VALUES (NULL),(0000000000);


-- query, expect:{0}, actual: Empty Set
SELECT
  t3._col_27 AS c0 
FROM (
  SELECT
    t_lhs_0.c1 AS _col_26,
    t_rhs_0.c1 AS _col_27
  FROM t0 AS t_lhs_0
  RIGHT JOIN t2 AS t_rhs_0 ON (TRUE)
) AS t3
WHERE
CAST(NULLIF(
  CAST((t3._col_27 IN (FALSE, t3._col_26)) AS CHAR),
  CAST(('a' LIKE t3._col_26) AS CHAR)
) AS DECIMAL(65, 30)) * CAST((-(t3._col_27 >= t3._col_27)) AS DECIMAL(65, 30));

```

### 2. What did you expect to see?

The query should return one row with value 0.

### 3. What did you see instead

The query returned an empty set.

### 4. What is your TiDB version?

I found this logic bug in TiDB 8.5.5

### LINKED ISSUE #67373: Query returns incorrect results (missing rows) with derived tables in UNION ALL, while CTE works correctly
## Bug Report


### 1. Minimal reproduce step

```sql
-- create table
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 ( c0 tinyint DEFAULT NULL COMMENT 'asdf', c2 mediumint(35) unsigned DEFAULT NULL, UNIQUE KEY c0 (c0), UNIQUE KEY c2 (c2), KEY i0 (c2), KEY i66 (c0) USING BTREE ) CHARSET=utf8mb4;
INSERT INTO t1 VALUES (NULL,NULL),(NULL,NULL),(NULL,NULL),(NULL,NULL),(NULL,00000000000000000000000000000000000),(NULL,NULL),(0,NULL),(NULL,NULL);
DROP TABLE IF EXISTS t2;
CREATE TABLE t2 ( c0 tinyint DEFAULT NULL COMMENT 'asdf', c2 mediumint(35) unsigned DEFAULT NULL, UNIQUE KEY c0 (c0), UNIQUE KEY c2 (c2), KEY i1 (c0,c2) USING BTREE ) CHARSET=utf8mb4;
INSERT INTO t2 VALUES (1,NULL),(0,NULL),(-128,00000000000000000000000000000000000),(NULL,00000000000000000000000000000000001),(NULL,NULL);

-- PoC
SELECT _col_12 AS c0
FROM (
  SELECT * FROM (
    SELECT t_lhs_2.c2 AS _col_11, t_rhs_2.c0 AS _col_12, t_rhs_2.c2 AS _col_13 
    FROM t2 AS t_lhs_2 RIGHT JOIN t2 AS t_rhs_2 ON (FALSE)
  ) AS derived 
  WHERE ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13)
  UNION ALL
  SELECT * FROM (
    SELECT t_lhs_2.c2 AS _col_11, t_rhs_2.c0 AS _col_12, t_rhs_2.c2 AS _col_13 
    FROM t2 AS t_lhs_2 RIGHT JOIN t2 AS t_rhs_2 ON (FALSE)
  ) AS derived 
  WHERE NOT ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13)
  UNION ALL
  SELECT * FROM (
    SELECT t_lhs_2.c2 AS _col_11, t_rhs_2.c0 AS _col_12, t_rhs_2.c2 AS _col_13 
    FROM t2 AS t_lhs_2 RIGHT JOIN t2 AS t_rhs_2 ON (FALSE)
  ) AS derived 
  WHERE ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13) IS NULL
) AS wrapper;
```

### 2. Bug Description

Two equivalent queries return different results, possibly triggering a logical bug.

```sql
-- query 1
WITH t AS (SELECT t_lhs_2.c2 AS _col_11, t_rhs_2.c0 AS _col_12, t_rhs_2.c2 AS _col_13 
    FROM t2 AS t_lhs_2 RIGHT JOIN t2 AS t_rhs_2 ON (FALSE))
SELECT _col_12 AS c0
FROM (
  SELECT * FROM t AS derived 
  WHERE ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13)
  UNION ALL
  SELECT * FROM t AS derived 
  WHERE NOT ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13)
  UNION ALL
  SELECT * FROM t AS derived 
  WHERE ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13) IS NULL
) AS wrapper;
```
Result of query 1:
```
+------+
| c0   |
+------+
| -128 |
| NULL |
| NULL |
|    0 |
|    1 |
+------+
5 rows in set (0.00 sec)
```

```sql
-- query 2
SELECT _col_12 AS c0
FROM (
  SELECT * FROM (
    SELECT t_lhs_2.c2 AS _col_11, t_rhs_2.c0 AS _col_12, t_rhs_2.c2 AS _col_13 
    FROM t2 AS t_lhs_2 RIGHT JOIN t2 AS t_rhs_2 ON (FALSE)
  ) AS derived 
  WHERE ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13)
  UNION ALL
  SELECT * FROM (
    SELECT t_lhs_2.c2 AS _col_11, t_rhs_2.c0 AS _col_12, t_rhs_2.c2 AS _col_13 
    FROM t2 AS t_lhs_2 RIGHT JOIN t2 AS t_rhs_2 ON (FALSE)
  ) AS derived 
  WHERE NOT ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13)
  UNION ALL
  SELECT * FROM (
    SELECT t_lhs_2.c2 AS _col_11, t_rhs_2.c0 AS _col_12, t_rhs_2.c2 AS _col_13 
    FROM t2 AS t_lhs_2 RIGHT JOIN t2 AS t_rhs_2 ON (FALSE)
  ) AS derived 
  WHERE ((TRUE >= (FALSE IN (_col_11, _col_11, _col_13))) <> _col_13) IS NULL
) AS wrapper;
```
Result of query 2:
```
+------+
| c0   |
+------+
| NULL |
| NULL |
|    0 |
|    1 |
+------+
4 rows in set (0.01 sec)
```

### 3. What is your TiDB version?
mysql> SELECT tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.5.5
Edition: Community
Git Commit Hash: 1fa258b833ff113883beeba40bc130be7ce66610
Git Branch: HEAD
UTC Build Time: 2026-03-23 14:08:54
GoVersion: go1.25.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #60080, close #61327, close #59162, close #60081, close #66825, close #58793, close #67048, close #60370, close #66824, close #67330, close #67373

Problem Summary:

### What changed and how does it work?

Rewrite the current null-reject judging function with a well-designed algorithm.

You can view the doc for details.

The algorithm provides a reliable way to perform the check and address issues from the old buggy version.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Corrected outer-to-inner join conversions for NULL-valued predicates, IN-lists with NULLs, and NULL-safe comparisons; improved prepared-plan cache behavior for these cases.

* **Improvements**
  * Added a conservative null-rejection proof framework to strengthen optimizer decisions around NULLs and predicate folding.

* **Documentation**
  * New design document describing the null-rejection framework and proof rules.

* **Tests**
  * Expanded unit and integration test coverage, including registry snapshot checks and many edge-case scenarios.

### CODE REVIEW

File: pkg/planner/util/null_misc.go [hunk 1]
```diff
@@ -15,17 +15,193 @@
...
+type nullRejectTestMode uint8
+
+const (
+	nullRejectTestReturnsFalse nullRejectTestMode = iota // f(NULL) = FALSE; nonTrue but not mustNull
+	nullRejectTestKeepsNull                              // f(NULL) = NULL; both nonTrue and mustNull
+)
+
+// nullRejectNullPreservingFunctions lists builtins that return NULL when any
+// argument is NULL. See the file-level comment for how this drives the proof.
+var nullRejectNullPreservingFunctions = map[string]struct{}{
```
Comment (Reminiscent) [inline pkg/planner/util/null_misc.go]: How do we determine whether a function should belong to this list?
For example, in PostgreSQL each function has a dedicated property (proisstrict) to indicate whether it is strict (i.e., returns NULL when any input is NULL).

I’m asking this because when I had Codex review this PR, it pointed out that ast.ConvertTz, ast.RegexpLike, ast.RegexpInStr, ast.RegexpSubstr, and ast.RegexpReplace do not seem to belong in nullRejectNullPreservingFunctions.

File: pkg/planner/util/null_misc.go [hunk 2]
```diff
@@ -41,86 +217,265 @@ func allConstants(ctx expression.BuildContext, expr expression.Expression) bool
...
-			newArgs = append(newArgs, arg)
-			eQCondition, err := expression.NewFunction(ctx.GetExprCtx(), ast.EQ,
-				expr.GetType(ctx.GetExprCtx().GetEvalCtx()), newArgs...)
-			if err != nil {
-				return false
+// IsNullRejected proves whether `predicate` can be TRUE after every column in
+// `innerSchema` is replaced with SQL NULL.
+func IsNullRejected(ctx base.PlanContext, innerSchema *expression.Schema, predicate expression.Expression,
+	skipPlanCacheCheck bool) bool {
+	_ = skipPlanCacheCheck // kept for API compatibility; the new proof does not use EvaluateExprWithNull
```
Comment (Reminiscent) [inline pkg/planner/util/null_misc.go:97]: Should we update the API directly here?
Do we need to maintain backward compatibility, or should that be handled separately later?

**Review by Reminiscent — APPROVED** [review]

File: pkg/planner/util/null_misc.go (hunk 1 above)
Comment (winoros) [reply pkg/planner/util/null_misc.go]: I think the best way to do it is to have agents conduct a multi-round check.

I'll check these functions later.

File: pkg/planner/util/null_misc.go [hunk 3]
```diff
@@ -41,86 +217,265 @@ func allConstants(ctx expression.BuildContext, expr expression.Expression) bool
...
+	innerSchema *expression.Schema,
+	expr expression.Expression,
+) nullRejectProof {
+	if cons, ok := tryFoldNullifiedConstant(ctx, innerSchema, expr); ok {
+		return proofFromConstant(ctx, cons)
+	}
+
+	switch x := expr.(type) {
+	case *expression.Column:
+		if innerSchema.Contains(x) {
```
Comment (qw4990) [inline pkg/planner/util/null_misc.go:133]: Could you add some comments with examples for this scenario? For example, `select * from t1 left join t2 on t1.a=t2.a where t2.b` then I assume `t2.b` should be the column `x` here?

File: pkg/planner/util/null_misc.go [hunk 4]
```diff
@@ -41,86 +217,265 @@ func allConstants(ctx expression.BuildContext, expr expression.Expression) bool
...
+		}
+	case *expression.Constant:
+		return proofFromConstant(ctx, x)
+	case *expression.ScalarFunction:
+		return proveNullRejectedScalarFunc(ctx, innerSchema, x)
+	}
+	return nullRejectProof{}
+}
+
+func proveNullRejectedScalarFunc(
```
Comment (qw4990) [inline pkg/planner/util/null_misc.go:161]: Also please add some comments for proveNullRejectedScalarFunc, proofFromConstant and proveNullRejected...

File: pkg/planner/util/null_misc.go [hunk 5]
```diff
@@ -41,86 +217,265 @@ func allConstants(ctx expression.BuildContext, expr expression.Expression) bool
...
-		return false
+// proveNullRejectedIn handles IN(value, list...).
+// IN returns NULL (not FALSE) when value is NULL, or when all list-element
+// comparisons yield NULL, making the whole predicate nonTrue in either case.
+func proveNullRejectedIn(
+	ctx base.PlanContext,
+	innerSchema *expression.Schema,
+	expr *expression.ScalarFunction,
+) nullRejectProof {
+	args := expr.GetArgs()
```
Comment (qw4990) [inline pkg/planner/util/null_misc.go:236]: If the args is too long, would this cause any performance risk? Should we have a fallback logic here just like how we handle long in-list for building ranges?

File: pkg/planner/util/null_misc.go [hunk 6]
```diff
@@ -41,86 +217,265 @@ func allConstants(ctx expression.BuildContext, expr expression.Expression) bool
...
+		}
+	case ast.LogicOr:
+		lhs := proveNullRejected(ctx, innerSchema, expr.GetArgs()[0])
+		rhs := proveNullRejected(ctx, innerSchema, expr.GetArgs()[1])
+		return nullRejectProof{
+			nonTrue:  lhs.nonTrue && rhs.nonTrue,
+			mustNull: lhs.mustNull && rhs.mustNull,
+		}
+	case ast.UnaryNot:
+		// NOT(IS NULL(x)): when x is mustNull, IS NULL(NULL) = TRUE and
```
Comment (qw4990) [inline pkg/planner/util/null_misc.go:182]: Sorry, still can't understand why we need to handle this case specially 🤦 ... could you please add more comments and examples...

File: pkg/planner/util/null_misc.go [hunk 7]
```diff
@@ -41,86 +217,265 @@ func allConstants(ctx expression.BuildContext, expr expression.Expression) bool
...
+		}
+	}
+	if allListMustNull {
+		return nullRejectProof{nonTrue: true, mustNull: true}
+	}
+	return nullRejectProof{}
+}
 
-	switch expr := predicate.(type) {
+func tryFoldNullifiedConstant(
```
Comment (qw4990) [inline pkg/planner/util/null_misc.go:263]: Please also add some comments.

File: pkg/planner/util/null_misc.go [hunk 8]
```diff
@@ -41,86 +217,265 @@ func allConstants(ctx expression.BuildContext, expr expression.Expression) bool
...
+	ctx base.PlanContext,
+	innerSchema *expression.Schema,
+	expr *expression.ScalarFunction,
+) (*expression.Constant, bool) {
+	switch expr.FuncName.L {
+	case ast.Coalesce, ast.Ifnull:
+		return tryFoldNullifiedCoalesceLike(ctx, innerSchema, expr)
+	case ast.If:
+		return tryFoldNullifiedIf(ctx, innerSchema, expr)
+	}
```
Comment (qw4990) [inline pkg/planner/util/null_misc.go:333]: Please add more comments to explain why we need to handle them specially...

File: pkg/planner/util/null_misc.go (hunk 5 above)
Comment (winoros) [reply pkg/planner/util/null_misc.go:236]: There's no regression in the performance. The original buggy one has the same time complexity.

Comment (qw4990) [reply pkg/planner/util/null_misc.go:236]: Got it.

**Review by qw4990 — APPROVED** [review]

**Comment by winoros** [comment]
/unhold
I think it's ready to merge.

**Review by windtalker — APPROVED** [review]
lgtm
