### PR TITLE
br: add some unit test and retry for get all tikv stores

### LINKED ISSUE #37581: ebs restore failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

ebs backup to s3
try to restore

### 2. What did you expect to see? (Required)
restore success

### 3. What did you see instead (Required)
Below error happened
I0902 14:54:33.703400       9 restore.go:244] [2022/09/02 14:54:33.703 +00:00] [INFO] [base_client.go:378] ["[pd] switch leader"] [new-leader=http://basic-pd-0.basic-pd-peer.tidb-cluster.svc:2379/] [old-leader=]
I0902 14:54:33.703492       9 restore.go:244] [2022/09/02 14:54:33.703 +00:00] [INFO] [base_client.go:105] ["[pd] init cluster id"] [cluster-id=7138795429752494907]
I0902 14:54:33.703573       9 restore.go:244] [2022/09/02 14:54:33.703 +00:00] [INFO] [client.go:690] ["[pd] tso dispatcher created"] [dc-location=global]
I0902 14:54:33.734761       9 restore.go:244] [2022/09/02 14:54:33.734 +00:00] [INFO] [restore_ebs_meta.go:216] ["starting to remove some PD schedulers"]
I0902 14:54:33.736319       9 restore.go:244] [2022/09/02 14:54:33.736 +00:00] [INFO] [collector.go:246] ["EBS restore failed, please check the log for details."]
I0902 14:54:33.738403       9 restore.go:244] 
E0902 14:54:33.738557       9 manager.go:287] restore cluster tidb-cluster/rt-ebs from ebs failed, err: cluster tidb-cluster/rt-ebs, the CSB file not found, path: /var/lib/br-bin/csb_restore.json
E0902 14:54:33.746309       9 restore_status_updater.go:81] Failed to update resotre [tidb-cluster/rt-ebs], error: Operation cannot be fulfilled on [restores.pingcap.com](http://restores.pingcap.com/) "rt-ebs": the object has been modified; please apply your changes to the latest version and try again
I0902 14:54:33.768643       9 restore_status_updater.go:78] Restore: [tidb-cluster/rt-ebs] updated successfully
error: cluster tidb-cluster/rt-ebs, the CSB file not found, path: /var/lib/br-bin/csb_restore.json

### 4. What is your TiDB version? (Required)
nightly

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?
1. add unit test
2. add retry for tikv stores
3. refactor code
4. fix 1st restore failure

Issue Number: close #37581

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/data_test.go [hunk 1]
```diff
@@ -0,0 +1,121 @@
+package restore_test
```
Comment (3pointer) [inline br/pkg/restore/data_test.go:1]: plz add license

File: br/pkg/restore/data.go [hunk 2]
```diff
@@ -227,14 +227,14 @@ func (recovery *Recovery) getTotalRegions() int {
 	return len(regions)
 }
 
-// RecoverRegions send the recovery plan to recovery region (force leader etc)
+// RecoverRegion send the recovery plan to recovery region (force leader etc)
```
Comment (3pointer) [inline br/pkg/restore/data.go:230]:
```suggestion
// RecoverRegions send the recovery plan to recovery region (force leader etc)
```

File: br/pkg/restore/data.go [hunk 3]
```diff
@@ -227,14 +227,14 @@ func (recovery *Recovery) getTotalRegions() int {
...
 // only tikvs have regions whose have to recover be sent
 func (recovery *Recovery) RecoverRegions(ctx context.Context) (err error) {
 	eg, ectx := errgroup.WithContext(ctx)
-	totalRecoveredStores := len(recovery.recoveryPlan)
-	workers := utils.NewWorkerPool(uint(mathutil.Min(totalRecoveredStores, maxStoreConcurrency)), "Recover Regions")
+	totalRecoveredStores := len(recovery.RecoveryPlan)
+	workers := utils.NewWorkerPool(uint(mathutil.Min(totalRecoveredStores, maxStoreConcurrency)), "Recover RecoverRegion")
```
Comment (3pointer) [inline br/pkg/restore/data.go:235]:
```suggestion
	workers := utils.NewWorkerPool(uint(mathutil.Min(totalRecoveredStores, maxStoreConcurrency)), "Recover Regions")
```

File: br/pkg/restore/util.go [hunk 4]
```diff
@@ -599,3 +601,152 @@ func unQuoteName(name string) string {
...
+			EndKey:        ek,
+			TombStone:     peers[0].Tombstone,
+		})
+	}
+
+	sort.Slice(regionInfos, func(i, j int) bool { return regionInfos[i].RegionVersion > regionInfos[j].RegionVersion })
+	return regionInfos
+}
+
+func CheckConsistencyAndValidPeer(regionInfos []*RecoverRegionInfo) (map[uint64]struct{}, error) {
```
Comment (3pointer) [inline br/pkg/restore/util.go:707]: maybe add a unit test for this function.

**Comment by D3Hunter** [comment]
please fix lint to make it build

File: br/pkg/restore/util.go (hunk 4 above)
Comment (fengou1) [reply br/pkg/restore/util.go:707]: fixed

File: br/pkg/restore/data_test.go (hunk 1 above)
Comment (fengou1) [reply br/pkg/restore/data_test.go:2]: fixed

File: br/pkg/restore/data.go [hunk 5]
```diff
@@ -320,7 +319,7 @@ func (recovery *Recovery) ResolveData(ctx context.Context, resolvedTs uint64) (e
 	totalStores := len(recovery.allStores)
 	workers := utils.NewWorkerPool(uint(mathutil.Min(totalStores, maxStoreConcurrency)), "resolve data from tikv")
 
-	// TODO: what if the resolved data take long time take long time?, it look we need some handling here, at least some retry may necessary
+	// TODO: what if the resolved data take long time take long time?, it look we need some handling here, at least some retry may neccessary
```
Comment (3pointer) [inline br/pkg/restore/data.go:322]:
```suggestion
	// TODO: what if the resolved data take long time take long time?, it look we need some handling here, at least some retry may necessary
```

File: br/pkg/restore/data.go [hunk 6]
```diff
@@ -348,208 +347,79 @@ func (recovery *Recovery) ResolveData(ctx context.Context, resolvedTs uint64) (e
 					log.Info("current delete key", zap.Uint64("resolved key num", resp.ResolvedKeyCount), zap.Uint64("store id", resp.StoreId))
 				} else if err == io.EOF {
 					break
-				} else {
+				} else if err != nil {
```
Comment (3pointer) [inline br/pkg/restore/data.go:350]:
```suggestion
				} else {
```

File: br/pkg/restore/data.go [hunk 7]
```diff
@@ -120,8 +118,8 @@ func (recovery *Recovery) newRecoveryClient(ctx context.Context, storeAddr strin
 		grpc.FailOnNonTempDialError(true),
 		grpc.WithConnectParams(grpc.ConnectParams{Backoff: bfConf}),
 		grpc.WithKeepaliveParams(keepalive.ClientParameters{
-			Time:    time.Duration(10) * time.Second,
-			Timeout: time.Duration(300) * time.Second,
+			Time:    time.Duration(3) * time.Second,
+			Timeout: time.Duration(10) * time.Second,
```
Comment (D3Hunter) [inline br/pkg/restore/data.go:122]: to `cfg.GRPCKeepaliveTime` and `cfg.GRPCKeepaliveTimeout`

File: br/pkg/task/restore_data.go [hunk 8]
```diff
@@ -146,28 +145,43 @@ func RunResolveKvData(c context.Context, g glue.Glue, cmdName string, cfg *Resto
 	}()
 
 	var allStores []*metapb.Store
-	allStores, err = conn.GetAllTiKVStoresWithRetry(ctx, mgr.GetPDClient(), util.SkipTiFlash)
+
+	var numOnlineStore int
+	err = utils.WithRetry(
```
Comment (D3Hunter) [inline br/pkg/task/restore_data.go:150]: why add another layer of retry on top of GetAllTiKVStoresWithRetry

Comment (fengou1) [reply br/pkg/task/restore_data.go:157]: the inner function has retry only 500 ms, it is enough for BR other restore, but here for EBS, 2nd restore may failure since pd + tikv startup take longer than 500 ms, to separate from BR legacy restore, add XX Ext retry.

File: br/pkg/restore/data.go (hunk 7 above)
Comment (fengou1) [reply br/pkg/restore/data.go]: should be good idea

Comment (fengou1) [reply br/pkg/restore/data.go]: fixed

File: br/pkg/task/restore_ebs_meta.go [hunk 9]
```diff
@@ -211,26 +220,10 @@ func (h *restoreEBSMetaHelper) restore() error {
 		return errors.Trace(err)
 	}
 
-	// stop scheduler before recover data
-	log.Info("starting to remove some PD schedulers")
```
Comment (3pointer) [inline br/pkg/task/restore_ebs_meta.go:215]: why remove it?

**Review by 3pointer — COMMENTED** [review]
LGTM
