### PR TITLE
DDL: create table should not allow explicit empty name index 

### LINKED ISSUE #18149: TiDB can create empty name index.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> CREATE TABLE t1(x INT, KEY ``(x));
Query OK, 0 rows affected (0.00 sec)
```
### 2. What did you expect to see? (Required)
In MySQL:
```
mysql> CREATE TABLE t1(x INT, KEY ``(x));
ERROR 1280 (42000): Incorrect index name ''
```

## Score
400

## SIG Slack Channel
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)
* @wjhuang2016 

## Recommended Skills

* Golang

## Learning Materials
N/A

### PR DESCRIPTION
**Pull request by watchpoints**
### What problem does this PR solve?

Issue Number: close #18149 
create table  not support  create empty name index

after parser PR: pingcap/parser/pull/1059
then update go.mod.

Problem Summary:

### What is changed and how it works?

change token IndexName from ident to item type
use a NullIndexName struct to represent a empty index to distinguish from a anonymous index

### Related changes
- pingcap/parser

### Check List 

Tests 

- Unit test
go test -check.f TestValidator 
go test -check.f TestCreateTable

- Manual test (add detailed scripts or steps below)
In TiDB
~~~
mysql> CREATE TABLE t(x INT, KEY ``(x));
ERROR 1280 (42000): Incorrect index name '
~~~
In MySQL:
~~~
mysql> CREATE TABLE t1(x INT, KEY ``(x));
ERROR 1280 (42000): Incorrect index name ''
~~~
It has the same action with MySQL

Side effects

### Release note 

- No release note.

### CODE REVIEW

**Comment by watchpoints** [comment]
@ti-srebot /run-all-tests

**Review by xhebox — CHANGES_REQUESTED** [review]
`ddl_api.go` changed its file permission from 644 to 755.

File: planner/core/preprocess_test.go [hunk 1]
```diff
@@ -255,6 +255,11 @@ func (s *testValidatorSuite) TestValidator(c *C) {
 		{"CREATE TABLE origin (a int primary key auto_increment, b int);", false, nil},
 		{"CREATE TABLE origin (a int unique auto_increment, b int);", false, nil},
 		{"CREATE TABLE origin (a int key auto_increment, b int);", false, nil},
+		// issue 18149
+		{"CREATE TABLE t (a int, index ``(a));", true, errors.New("[ddl:1280]Incorrect index name ''")},
+		{"CREATE TABLE t (a int, key ``(a));", true, errors.New("[ddl:1280]Incorrect index name ''")},
+		{"CREATE TABLE t (a int, index(a));", false, nil},
+		{"CREATE TABLE t (a int,key(a));", false, nil},
```
Comment (bb7133) [inline planner/core/preprocess_test.go:262]: Please add the following tests and make sure `Incorrect index name ''` is raised:

* Create expression index in `CREATE TABLE`:
```
create table t(a varchar(10), index `` ((lower(a))));
```

* Create column index by `CREATE INDEX`:
```
create index `` on t (a);
```
* Create expression index by `CREATE INDEX`:
```
create index `` on t ((lower(a)));
```

Comment (watchpoints) [reply planner/core/preprocess_test.go]: the lenght of  Index name  must greater than 0  in CreateIndexStmt.

File: planner/core/preprocess.go [hunk 2]
```diff
@@ -767,6 +776,13 @@ func checkIndexInfo(indexName string, IndexPartSpecifications []*ast.IndexPartSp
 	return checkDuplicateColumnName(IndexPartSpecifications)
 }
 
+// checkEmptyIndexInfo checks  empty index name
+func checkEmptyIndexInfo(name string, isEmptyIndex bool) error {
+	if isEmptyIndex {
+		return ddl.ErrWrongNameForIndex.GenWithStackByArgs(name)
+	}
+	return nil
+}
```
Comment (tangenta) [inline planner/core/preprocess.go:785]: This function is simple enough. Please move the body to `checkCreateIndexGrammar`.

**Comment by watchpoints** [comment]
@tangenta ,  when runing make test int tidb with my parser,I get err: 
tidb-server(PID: 129817) started
```
run all explain test cases
[2020/10/27 14:44:27.050 +08:00] [FATAL] [main.go:694] ["run test"] [test=select] [error="sql:sc;: run \"select !(1 + 2);\" at line 89 err Error 1105: Unknown Unary Op opcode.Op"] [errorVerbose="run \"select !(1 + 2);\" at line 89 err Error 1105: Unknown Unary Op opcode.Op\nmain.

(*tester).execute\n\t/root/code/src/github.com/watchpoints/tidb/cmd/explaintest/main.go:356\nmain.
```

but I run this sql , it is right.

**Comment by tangenta** [comment]
> @tangenta , when runing make test int tidb with my parser,I get err:
> tidb-server(PID: 129817) started
> 
> ```
> run all explain test cases
> [2020/10/27 14:44:27.050 +08:00] [FATAL] [main.go:694] ["run test"] [test=select] [error="sql:sc;: run \"select !(1 + 2);\" at line 89 err Error 1105: Unknown Unary Op opcode.Op"] [errorVerbose="run \"select !(1 + 2);\" at line 89 err Error 1105: Unknown Unary Op opcode.Op\nmain.
> 
> (*tester).execute\n\t/root/code/src/github.com/watchpoints/tidb/cmd/explaintest/main.go:356\nmain.
> ```
> 
> but I run this sql , it is right.
> select !(1 + 2);

This is caused by https://github.com/pingcap/tidb/pull/20612. You can update your TiDB to latest to solve the problem.

**Comment by watchpoints** [comment]
update your TiDB ,and make test is ok in my local ,

but the push tidb/pull/20617,and pingcap/parser/pull/1059  

both failed in dc-jenkin. @tangenta

**Comment by watchpoints** [comment]
update TiDB  ， make test is ok，

but   parser/pull/1059 和tidb/pull/20617（now replace go.mod）  idc-jenkins-ci  check failed。

i follow https://github.com/pingcap/parser/blob/master/docs/update-parser-for-tidb.md @tangenta 

> > @tangenta , when runing make test int tidb with my parser,I get err:
> > tidb-server(PID: 129817) started
> > ```
> > run all explain test cases
> > [2020/10/27 14:44:27.050 +08:00] [FATAL] [main.go:694] ["run test"] [test=select] [error="sql:sc;: run \"select !(1 + 2);\" at line 89 err Error 1105: Unknown Unary Op opcode.Op"] [errorVerbose="run \"select !(1 + 2);\" at line 89 err Error 1105: Unknown Unary Op opcode.Op\nmain.
> > 
> > (*tester).execute\n\t/root/code/src/github.com/watchpoints/tidb/cmd/explaintest/main.go:356\nmain.
> > ```
> > 
> > 
> > but I run this sql , it is right.
> > select !(1 + 2);
> 
> This is caused by #20612. You can update your TiDB to latest to solve the problem.

update TiDB  ， make test is ok，

but   parser/pull/1059 和tidb/pull/20617（now replace go.mod）  idc-jenkins-ci  check failed。

i follow https://github.com/pingcap/parser/blob/master/docs/update-parser-for-tidb.md @tangenta

**Comment by tangenta** [comment]
Weird. Let's merge pingcap/parser/pull/1059 first.

**Comment by xhebox** [comment]
@ti-srebot /run-all-tests

**Comment by watchpoints** [comment]
@ti-srebot /run-all-tests

**Comment by watchpoints** [comment]
@ti-srebot /run-all-tests

**Comment by tangenta** [comment]
Please run `make fmt` to pass the check from linter.

**Comment by tangenta** [comment]
It is recommended to run `make check` before committing :)

**Comment by watchpoints** [comment]
@ti-srebot /run-make check

**Comment by watchpoints** [comment]
@ti-srebot /run-all-tests

**Comment by tangenta** [comment]
```
[2020-11-01T10:17:31.051Z] + GOPATH=/home/jenkins/agent/workspace/tidb_ghpr_check/go
[2020-11-01T10:17:31.051Z] + make check
[2020-11-01T10:17:31.051Z] gofmt (simplify)
[2020-11-01T10:17:39.136Z] planner/core/preprocess.go
[2020-11-01T10:17:39.136Z] planner/core/preprocess_test.go
[2020-11-01T10:17:39.136Z] make: *** [fmt] Error 1
script returned exit code 2
```

**Comment by watchpoints** [comment]
> ```
> [2020-11-01T15:38:52.701Z] + GOPATH=/home/jenkins/agent/workspace/tidb_ghpr_check/go
> [2020-11-01T15:38:52.701Z] + make check
> [2020-11-01T15:38:52.701Z] gofmt (simplify)
> [2020-11-01T15:39:48.903Z] cd tools/check; \
> [2020-11-01T15:39:48.903Z] GO111MODULE=on go build -o ../bin/errcheck github.com/kisielk/errcheck
> [2020-11-01T15:39:48.903Z] errcheck
> [2020-11-01T15:39:58.910Z] cd tools/check; \
> [2020-11-01T15:39:58.910Z] GO111MODULE=on go build -o ../bin/unconvert github.com/mdempsky/unconvert
> [2020-11-01T15:39:58.910Z] unconvert check
> [2020-11-01T15:41:07.428Z] cd tools/check; \
> [2020-11-01T15:41:07.428Z] GO111MODULE=on go build -o ../bin/revive github.com/mgechev/revive
> [2020-11-01T15:41:14.053Z] linting
> [2020-11-01T15:41:24.026Z] go mod tidy
> [2020-11-01T15:41:24.026Z] ./tools/check/check-tidy.sh
> [2020-11-01T15:41:42.083Z] Files go.sum and /tmp/go.sum.before differ
> [2020-11-01T15:41:42.083Z] make: *** [tidy] Error 1
> script returned exit code 2
> ```

go mod tidy 
first run make check is right

**second run make check is wrong ,i not know why ?

Files go.sum and /tmp/go.sum.before differ**

i update tidb,now is 
```
go: github.com/pingcap/tidb/_tools/util/timeutil imports
	github.com/uber-go/atomic: github.com/uber-go/atomic@v1.7.0: parsing go.mod:
	module declares its path as: go.uber.org/atomic
	        but was required as: github.com/uber-go/atomic

```

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]
LGTM
