### PR TITLE
executor: fix drop role failed after revoke role from current user

### LINKED ISSUE #29781: drop role failed after revoke role from current user
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create role r1, r2, r3;
grant r1,r2,r3 to current_user();
set role all;
revoke r1, r3 from root;
drop role r1;
```

### 2. What did you expect to see? (Required)
```sql
mysql> create role r1, r2, r3;
Query OK, 0 rows affected (0.06 sec)

mysql> grant r1,r2,r3 to current_user();
Query OK, 0 rows affected (0.07 sec)

mysql> set role all;
Query OK, 0 rows affected (0.05 sec)

mysql> revoke r1, r3 from root;
Query OK, 0 rows affected (0.05 sec)

mysql> drop role r1;
Query OK, 0 rows affected (0.05 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> create role r1, r2, r3;
Query OK, 0 rows affected (0.00 sec)

mysql> grant r1,r2,r3 to current_user();
Query OK, 0 rows affected (0.01 sec)

mysql> set role all;
Query OK, 0 rows affected (0.00 sec)

mysql> show grants;
+-------------------------------------------------------------+
| Grants for User                                             |
+-------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION |
| GRANT 'r1'@'%', 'r2'@'%', 'r3'@'%' TO 'root'@'%'            |
+-------------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> revoke r1, r3 from root;
Query OK, 0 rows affected (0.01 sec)

mysql> drop role r1;
ERROR 3530 (HY000): `r3`@`%` is not granted to root@127.0.0.1
mysql>
```
### 4. What is your TiDB version? (Required)
master: 4b295081eaf81d9430f2f0ab2daab678257c

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #29781 

Problem Summary:

### What is changed and how it works?
Seems a follow-up of https://github.com/pingcap/tidb/pull/29494
- When an active role of current user is revoked, remove it from activeRoles.
- Add unit test.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by unconsolable** [comment]
Through it still fails on `common-test`, but it seems that the failure in `[role]` is resolved.
```
[2021-11-15T13:26:16.159Z] time="2021-11-15T21:26:16+08:00" level=error msg="1 tests failed\n"
[2021-11-15T13:26:16.159Z] time="2021-11-15T21:26:16+08:00" level=error msg="run test [update] err: sql:create table t2 (id int unsigned not null auto_increment primary key, a int);: run \"create table t2 (id int unsigned not null auto_increment primary key, a int);\" at line 148 err Error 1050: Table 'test.t2' already exists"
```

**Comment by unconsolable** [comment]
Although it still fails on `common-test`, it seems that the failure in `[role]` is resolved.
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/7350/pipeline/86
```
[2021-11-15T13:26:16.159Z] time="2021-11-15T21:26:16+08:00" level=error msg="1 tests failed\n"
[2021-11-15T13:26:16.159Z] time="2021-11-15T21:26:16+08:00" level=error msg="run test [update] err: sql:create table t2 (id int unsigned not null auto_increment primary key, a int);: run \"create table t2 (id int unsigned not null auto_increment primary key, a int);\" at line 148 err Error 1050: Table 'test.t2' already exists"
```

**Comment by unconsolable** [comment]
/cc @morgo @mjonss 
PTAL

File: executor/simple_test.go [hunk 1]
```diff
@@ -974,3 +974,17 @@ func (s *testSuite3) TestShowGrantsAfterDropRole(c *C) {
...
 }
+
+func (s *testSuite3) TestDropRoleAfterRevoke(c *C) {
+	// issue 29781
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test;")
+	tk.Se.Auth(&auth.UserIdentity{Username: "root", Hostname: "localhost"}, nil, nil)
+
+	tk.MustExec("create role r1, r2, r3;")
+	defer tk.MustExec("drop role r2, r3;")
```
Comment (mjonss) [inline executor/simple_test.go:985]: I think `drop role if exists r1, r2, r3` will be better.

File: executor/simple_test.go [hunk 2]
```diff
@@ -974,3 +974,17 @@ func (s *testSuite3) TestShowGrantsAfterDropRole(c *C) {
...
+	tk.MustExec("grant r1,r2,r3 to current_user();")
+	tk.MustExec("set role all;")
+	tk.MustExec("revoke r1, r3 from root;")
```
Comment (mjonss) [inline executor/simple_test.go:988]: Here `root` will most likely map to `"root"@"%"` which is not the same as `"root"@"localhost"`.

File: executor/simple.go [hunk 3]
```diff
@@ -661,6 +661,12 @@ func (e *SimpleExec) executeRevokeRole(ctx context.Context, s *ast.RevokeRoleStm
 		return errors.Trace(err)
 	}
 	sql := new(strings.Builder)
+	// when an active role of current user is revoked,
+	// it should be removed from activeRoles
```
Comment (mjonss) [inline executor/simple.go:665]: What would happen for other active users with the role being revoked?

**Review by mjonss — COMMENTED** [review]
Looks good, but I have a few questions :)

File: executor/simple_test.go (hunk 2 above)
Comment (unconsolable) [reply executor/simple_test.go:988]: I think it may not be a problem.
```
if currentUser == user.Username {
  for i := 0; i < len(activeRoles); i++ {
    if activeRoles[i].Username == role.Username && activeRoles[i].Hostname == role.Hostname {
```
If the user name is the same, we will compare the role's username & hostname.

File: executor/simple.go (hunk 3 above)
Comment (mjonss) [reply executor/simple.go:665]: What has priority to be fixed, is that the `revoke role r1 from u1` revokes the extra rights the `r1` role gives to `u1`, even in currently running sessions (for any statement started after the revoke succeeded). If there are errors or other issues, that has lower impact. Could you please test what would happen for a concurrent u1 session (preferably on another tidb instance)? I'm all good in not fixing those in this bug, but we should at least check and report new bugs, since it is security related.

Comment (mjonss) [reply executor/simple.go:665]: I wonder if the error is not because the u1 user did not set the role? (I at least see it as a bug, but can probably be seen as a different bug that this).
See below that it warns about role `r1`, which I never gave to u1@localhost!
```sql
$ mysql -S /tmp/tidb-4001.sock -u u1 --prompt="tidb> " --comments  --database test -v
...
Your MySQL connection id is 17
Server version: 5.7.25-TiDB-v5.4.0-alpha-121-g724020289 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible
...
tidb> show grants;
ERROR 3530 (HY000): `r1`@`%` is not granted to u1@localhost

tidb> set role r1;
ERROR 3530 (HY000): `r1`@`%` is not granted to u1@localhost

tidb> set role r2;
Query OK, 0 rows affected (0,00 sec)

tidb> show grants;
+---------------------------------------------+
| Grants for User                             |
+---------------------------------------------+
| GRANT USAGE ON *.* TO 'u1'@'localhost'      |
| GRANT SELECT ON test.t2 TO 'u1'@'localhost' |
| GRANT 'r2'@'%' TO 'u1'@'localhost'          |
+---------------------------------------------+
3 rows in set (0,00 sec)
```

Users, tables and roles created by:
```sql
tidb> create user u1;
Query OK, 0 rows affected (0,00 sec)

tidb> create user u1@localhost;
Query OK, 0 rows affected (0,01 sec)

tidb> create role r1, r2;
Query OK, 0 rows affected (0,01 sec)

tidb> show tables;
Empty set (0,00 sec)

tidb> create table t1 (a int);
Query OK, 0 rows affected (0,00 sec)

tidb> create table t2 (a int);
Query OK, 0 rows affected (0,00 sec)

tidb> grant select on test.t2 to r2;
Query OK, 0 rows affected (0,01 sec)

tidb> grant select on test.* to r1;
Query OK, 0 rows affected (0,01 sec)

tidb> grant r1 to u1;
Query OK, 0 rows affected (0,01 sec)

tidb> grant r2 to u1@localhost;
Query OK, 0 rows affected (0,01 sec)
```

Comment (mjonss) [reply executor/simple.go:665]: I just tried and revoking a role does still leave the privileges intact for the user, even for new sessions, while revoking the privileges from the role, does remove the privileges granted through the role.

Comment (unconsolable) [reply executor/simple.go:665]: > it warns about role r1, which I never gave to u1@localhost!

Does it means that  `revoke r1 from u1` will cause `show grants`  of `u1@localhost` fail? I tried but can't reproduce it, could you please give some advice?

> I just tried and revoking a role for another user does still leave the privileges intact for that user, even for new sessions,

After execute `revoke r1 from u1`, `u1` still can execute `select * from t1;`, but I think it may be another issue to be reported

File: executor/simple_test.go (hunk 1 above)
Comment (unconsolable) [reply executor/simple_test.go]: Resolved.

**Review by mjonss — APPROVED** [review]
LGTM

Thanks for reporting the new bug too!

**Review by xhebox — APPROVED** [review]
