### PR TITLE
expression: fix enum and set type expression in where clause

### LINKED ISSUE #22717: Wrong enum calculation result in where condition.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table t;
create table t(e enum('a','','b'));
insert into t values(1),(2),(3);
select * from t where e;
```

### 2. What did you expect to see? (Required)

```
MySQL [test]> select * from t where e;
+------+
| e    |
+------+
| a    |
|      |
| b    |
+------+
3 rows in set (0.000 sec)
```

### 3. What did you see instead (Required)

```
[tidb]> select * from t where e;
+------+
| e    |
+------+
| a    |
| b    |
+------+
2 rows in set (0.001 sec)
```

### 4. What is your TiDB version? (Required)
17a65ab98bf1c5b86b7b9d8fc5c6e28a57e741a8

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close #22717 

### What is changed and how it works?

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix enum and set type expression in where clause

### CODE REVIEW

File: expression/expression.go [hunk 1]
```diff
@@ -459,7 +459,8 @@ func toBool(sc *stmtctx.StatementContext, tp *types.FieldType, eType types.EvalT
 				if tp.Hybrid() {
 					switch tp.Tp {
 					case mysql.TypeEnum, mysql.TypeSet:
-						fVal = float64(len(sVal))
+						// Enum and Set type value to bool is always true.
+						fVal = 1
```
Comment (XuHuaiyu) [inline expression/expression.go:463]: Any reference in the mysql manual?

Comment (XuHuaiyu) [reply expression/expression.go:463]:
``` sql
mysql> create table t(a enum("a", "b", "c"));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values('a'),('b');
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> set @@sql_mode='';
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> insert into t values("");
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> select * from t;
+------+
| a    |
+------+
| a    |
| b    |
|      |
+------+
3 rows in set (0.00 sec)

mysql> select * from t where a;
+------+
| a    |
+------+
| a    |
| b    |
+------+
2 rows in set (0.00 sec)
```

File: expression/expression.go [hunk 2]
```diff
@@ -458,8 +458,17 @@ func toBool(sc *stmtctx.StatementContext, tp *types.FieldType, eType types.EvalT
 				sVal := buf.GetString(i)
 				if tp.Hybrid() {
 					switch tp.Tp {
-					case mysql.TypeEnum, mysql.TypeSet:
+					case mysql.TypeSet, mysql.TypeEnum:
 						fVal = float64(len(sVal))
+						if fVal == 0 {
+							// Check whether "" in set type.
```
Comment (XuHuaiyu) [inline expression/expression.go:464]: change this comment to:
The elements listed in the column specification are assigned index numbers, beginning with 1. The index value of the empty string error value (distinguish from a “normal” empty string) is 0. Thus we need to check whether it's an empty string error value when \`fVal==0\`

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
