### PR TITLE
planner: a quick fix to solve the column alias in ORDER BY's subquery

### LINKED ISSUE #42732: Column alias is not propagated to subquery
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is related to #26945 which was resolved in #33640 but is about column aliases.

```sql
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1 (a INT, b INT);
CREATE TABLE t2 (a INT, b INT);
INSERT INTO t1 VALUES (1, 1);
INSERT INTO t2 VALUES (1, 1);

-- does not work (but works in mysql, and is similar to what hibernate generates)
SELECT one.a, one.b as b2 FROM t1 one ORDER BY (SELECT two.b FROM t2 two WHERE two.a = one.b);
```

### 2. What did you expect to see? (Required)

```sql
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

```

### 3. What did you see instead (Required)

```
ERROR 1054 (42S22): Unknown column 'one.b' in 'where clause'
```

### 4. What is your TiDB version? (Required)

```
Release Version: v6.1.2
Edition: Community
Git Commit Hash: 5d2030e1d19629b71811c3f14514bad7ed63261a
Git Branch: heads/refs/tags/v6.1.2
UTC Build Time: 2022-10-18 08:04:48
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

(Also, tested locally against 6.5.0 and the issue still persisted)

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #42732

Problem Summary:

### What is changed and how it works?

The column alias is not seeable in ORDER BY's subquery clause.

This pr provides a quick way to fix the issue.

It's not the final solution to the AST resolution problems.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -2734,6 +2734,9 @@ func (b *PlanBuilder) resolveHavingAndOrderBy(ctx context.Context, sel *ast.Sele
 		}
 	}
 	sel.Fields.Fields = extractor.selectFields
+	if !b.ctx.GetSessionVars().InRestrictedSQL {
+		logutil.BgLogger().Warn("1")
```
Comment (fixdb) [inline planner/core/logical_plan_builder.go:2738]: remove log?

File: planner/core/issuetest/BUILD.bazel [hunk 2]
```diff
@@ -9,7 +9,7 @@ go_test(
     ],
     flaky = True,
     race = "on",
-    shard_count = 4,
+    shard_count = 5,
```
Comment (fixdb) [inline planner/core/issuetest/BUILD.bazel:12]: why this change?

Comment (winoros) [reply planner/core/issuetest/BUILD.bazel:12]: It seems that the shard will increase as the test increase. The maximum number of the shard is 50.

**Review by time-and-fate — APPROVED** [review]

**Review by fixdb — APPROVED** [review]
+1
