### PR TITLE
ddl: check the key existence on original index

### LINKED ISSUE #40730: add unique index may cause duplicate row value.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

There is no simple way to reproduce.
We need to modify the code.
Here is the test case:
``` sql
func TestCreateUniqueRowDuplicExist(t *testing.T) {
	store, dom := testkit.CreateMockStoreAndDomain(t)

	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("create table t(a int default 0, b int default 0)")

	tk1 := testkit.NewTestKit(t, store)
	tk1.MustExec("use test")

	d := dom.DDL()
	originalCallback := d.GetHook()
	defer d.SetHook(originalCallback)
	callback := &ddl.TestDDLCallback{}
	onJobUpdatedExportedFunc := func(job *model.Job) {
		if t.Failed() {
			return
		}
		var err error
		switch job.SchemaState {
		case model.StateDeleteOnly:
			_, err = tk1.Exec("insert into t values (5, 5)")
			assert.NoError(t, err)
		case model.StateWriteOnly:
			_, err = tk1.Exec("insert into t values (5, 7)")
			assert.NoError(t, err)
			_, err = tk1.Exec("delete from t where b = 7")
			assert.NoError(t, err)
		case model.StateWriteReorganization:
		}
	}
	callback.OnJobUpdatedExported.Store(&onJobUpdatedExportedFunc)
	d.SetHook(callback)
	tk.MustExec("alter table t add unique index idx(a)")
	tk.MustExec("admin check table t")
} 
```

besides:
in onCreateIndex()

``` sql
	case model.StateWriteReorganization:
		// reorganization -> public
		tbl, err := getTable(d.store, schemaID, tblInfo)
		if err != nil {
			return ver, errors.Trace(err)
		}

		var done bool
		if job.MultiSchemaInfo != nil {
			done, ver, err = doReorgWorkForCreateIndexMultiSchema(w, d, t, job, tbl, indexInfo)
		} else {
			done, ver, err = doReorgWorkForCreateIndex(w, d, t, job, tbl, indexInfo)
		}
		if !done {
			return ver, err
		}

		sess, _ := w.sessPool.get()
		se := newSession(sess)
		se.execute(w.ctx, "insert into test.t values(5, 9)", "")

		// Set column index flag.
		AddIndexColumnFlag(tblInfo, indexInfo)
```

Modify the code to execute this query.

### 2. What did you expect to see? (Required)
test pass

### 3. What did you see instead (Required)
```
[admin:8223]data inconsistency in table: t, index: idx, handle: 1, index-values:"handle: 3, values: [KindInt64 5]" != record-values:"handle: 1, values: [KindInt64 5]"
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #40730

Problem Summary:

```sql
create table t(a int default 0, b int default 0);
alter table t add unique index idx(a);

-- delete-only
insert into t values (5, 5);
-- rows    = [h1 -> (5, 5)]
-- idx     = []
-- tmp_idx = []
-- It writes nothing to the index or temp index because of the delete-only state.

-- write-only
insert into t values (5, 7);
-- rows    = [h1 -> (5, 5), h2 -> (5, 7)]
-- idx     = []
-- tmp_idx = [5 -> h2]
-- It is redirected to the temp index for write-only state.

delete from t where b = 7;
-- rows    = [h1 -> (5, 5)]
-- idx     = []
-- tmp_idx = [5 -> h2d]
-- It is redirected to the temp index for write-only state.
-- The delete operation is converted to a deletion marker(h2d).

-- write-reorg, backfill
-- rows    = [h1 -> (5, 5)]
-- idx     = [5 -> h1]
-- tmp_idx = [5 -> h2d]

-- write-reorg, after merging
insert into t values(5, 9);
-- rows    = [h1 -> (5, 5), h3 -> (5, 9)]
-- idx     = [5 -> h1]   + 5 -> h3
-- tmp_idx = [5 -> h2d]  + 5 -> h3
-- Double write. New changes are written to both index and temp index (+ 5 -> h3).
-- When TiDB checks the unique constraint, "h2d" is found as the deleted marker and the flag of "presume key exists" is incorrectly unset.
-- Finally, these two records are overwritten.

-- rows    = [h1 -> (5, 5), h3 -> (5, 9)]
-- idx     = [5 -> h3]
-- tmp_idx = [5 -> h3]

-- public
admin check table t;
-- [admin:8223]data inconsistency in table: t, index: idx, handle: 1, index-values:"handle: 3, values: [KindInt64 5]" != record-values:"handle: 1, values: [KindInt64 5]"
```

The problem happens on the unique check. A deletion marker on temporary index doesn't mean the corresponding row record is deleted.

### What is changed and how it works?

Because the last DML in above issue happens in the final stage of adding index, there is no way to "detect" duplicated keys after the insertion. In other words, this DML must report a key duplicated error. Thus, we have to correct the key uniqueness check mechanism when TiDB writes to temp index. This is also crucial to DML like `REPLACE` and `INSERT ON DUPLICATE UPDATE` because the uniqueness determines the semantic of the following action.

Here is the new uniqueness check introduced in this PR:

```go
func key_is_unique(temp_index_key, handle) bool {
    temp_val = get(temp_index_key)
    if temp_val == nil {
        val := get(index_key)
        if val == nil {
            return is_unique
        } else {
            return not_unique
        }
    } else if temp_val == delete_marker {
        val = get(index_key)
        if val == nil {
            return is_unique
        } else {
            deleted_handle = decode_handle(temp_val)
            index_handle = decode_handle(val)
            if deleted_handle == index_handle {
                return is_unique
            }
            row_key = encode(index_handle)
            row_val = get(row_key)
            if row_val == nil {
                return is_unique
            } else {
                return not_unique
            }
        }
    } else {
        return not_unique
    }
}
```

The second change is about the encoding of temp index value. 

When there are multiple insertions or deletions to the temp index, TiDB always overwrites the previous value in current implementation. This may cause some of the user changes lost and data-index inconsistency. Several test cases in this PR show the problems.

This PR introduces a new temp index value encoding, storing all the insertion/deletion history by appending new value to existing value. In the merge process, the temp index merge worker extracts the operations in temp index value, and replay them to the index.

```
// TempIndexValue is the value of temporary index.
// It contains one or more element, each element represents a history index operations on the original index.
// A temp index value element is encoded as one of:
//   - [flag 1 byte][value_length 2 bytes ] [value value_len bytes]   [key_version 1 byte] {distinct normal}
//   - [flag 1 byte][value value_len bytes]                           [key_version 1 byte] {non-distinct normal}
//   - [flag 1 byte][handle_length 2 bytes] [handle handle_len bytes] [key_version 1 byte] {distinct deleted}
//   - [flag 1 byte]                                                  [key_version 1 byte] {non-distinct deleted}
```

### Check List

Tests

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix data inconsistency issue after adding unique index.
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

File: table/tables/index.go [hunk 1]
```diff
@@ -485,50 +498,89 @@ func (c *index) Exist(sc *stmtctx.StatementContext, txn kv.Transaction, indexedV
...
-			handle, err := tablecodec.DecodeHandleInUniqueIndexValue(value, c.tblInfo.IsCommonHandle)
+// FetchDuplicatedHandle is used to find the duplicated row's handle for a given unique index key.
+func FetchDuplicatedHandle(ctx context.Context, key kv.Key, distinct bool,
+	txn kv.Transaction, tableID int64, isCommon bool) (foundKey bool, dupHandle kv.Handle, err error) {
+	val, err := txn.Get(ctx, key)
+	if err != nil {
+		if kv.IsErrNotFound(err) {
+			return false, nil, nil
+		}
+		// Unexpected errors.
```
Comment (wjhuang2016) [inline table/tables/index.go:527]: Can we print an error log?

File: table/tables/index.go [hunk 2]
```diff
@@ -485,50 +498,89 @@ func (c *index) Exist(sc *stmtctx.StatementContext, txn kv.Transaction, indexedV
...
+			originKey := key.Clone()
+			tablecodec.TempIndexKey2IndexKey(idxID, originKey)
+			originVal, err := txn.Get(ctx, originKey)
 			if err != nil {
+				if kv.IsErrNotFound(err) {
+					// The key has been deleted. This is not a duplicated key.
+					return false, nil, nil
+				}
+				// Unexpected errors.
 				return false, nil, err
```
Comment (wjhuang2016) [inline table/tables/index.go:542]: Can we print an error log?

File: table/tables/index.go [hunk 3]
```diff
@@ -485,50 +498,89 @@ func (c *index) Exist(sc *stmtctx.StatementContext, txn kv.Transaction, indexedV
...
+			}
+			if originHandle.Equal(deletedHandle) {
+				// The key has been deleted. This is not a duplicated key.
+				return false, nil, nil
+			}
+			// The inequality means multiple modifications happened in the same key.
+			// We use the handle in origin index value to check if the row exists.
+			recPrefix := tablecodec.GenTableRecordPrefix(tableID)
+			rowKey := tablecodec.EncodeRecordKey(recPrefix, originHandle)
+			_, err = txn.Get(context.Background(), rowKey)
```
Comment (wjhuang2016) [inline table/tables/index.go:559]: Why use background()

File: table/tables/index.go (hunk 1 above)
Comment (tangenta) [reply table/tables/index.go:527]: The error is returned to the outer function. Is it still necessary to add a log?

File: table/tables/index.go (hunk 3 above)
Comment (tangenta) [reply table/tables/index.go:559]: Otherwise we have to change the interface like `index.Create()`, and pass the context to a parameter like `CreateIdxOpt`. What's your suggestion?

File: tablecodec/tablecodec.go [hunk 4]
```diff
@@ -1153,7 +1153,7 @@ func TempIndexKey2IndexKey(originIdxID int64, tempIdxKey []byte) {
 }
 
 // IsTempIndexKey check whether the input key is for a temp index.
-func IsTempIndexKey(indexKey []byte) bool {
+func IsTempIndexKey(indexKey []byte) (bool, int64) {
```
[the remark this answers is not in the document]
Comment (tangenta) [reply tablecodec/tablecodec.go]: Done.

File: executor/insert.go [hunk 5]
```diff
@@ -158,11 +159,8 @@ func prefetchConflictedOldRows(ctx context.Context, txn kv.Transaction, rows []t
 	for _, r := range rows {
 		for _, uk := range r.uniqueKeys {
 			if val, found := values[string(uk.newKey)]; found {
-				if tablecodec.IsTempIndexKey(uk.newKey) {
-					if tablecodec.CheckTempIndexValueIsDelete(val) {
-						continue
-					}
-					val = tablecodec.DecodeTempIndexOriginValue(val)
+				if isTemp, _ := tablecodec.IsTempIndexKey(uk.newKey); isTemp {
+					continue
```
[the remark this answers is not in the document]
Comment (tangenta) [reply executor/insert.go:166]: Done.

File: table/tables/index.go [hunk 6]
```diff
@@ -239,18 +238,21 @@ func (c *index) Create(sctx sessionctx.Context, txn kv.Transaction, indexedValue
 		opt.IgnoreAssertion = opt.IgnoreAssertion || c.idxInfo.State != model.StatePublic
 
 		if !distinct || skipCheck || opt.Untouched {
+			val := idxVal
```
Comment (Benjamin2037) [inline table/tables/index.go:241]: Here is for normal index, our solution should only for uk scenario.

File: table/tables/index.go [hunk 7]
```diff
@@ -360,6 +386,16 @@ func (c *index) Delete(sc *stmtctx.StatementContext, txn kv.Transaction, indexed
 		}
 
 		key, tempKey, tempKeyVer := GenTempIdxKeyByState(c.idxInfo, key)
+		var originTempVal []byte
+		if len(tempKey) > 0 {
```
Comment (Benjamin2037) [inline table/tables/index.go:390]: Only tempKey>0 && c.idxInfo.Unique then need get origin index key

File: ddl/index_merge_tmp.go [hunk 8]
```diff
@@ -252,40 +259,49 @@ func (w *mergeIndexWorker) fetchTempIndexVals(txn kv.Transaction, taskRange reor
...
-				// For 'm' version kvs, they are double-written.
-				// For 'd' version kvs, they are written in the delete-only state and can be dropped safely.
-				return true, nil
+			tempIdxVal, err := tablecodec.DecodeTempIndexValue(rawValue, isCommonHandle)
+			if err != nil {
+				return false, err
 			}
+			tempIdxVal = tempIdxVal.FilterOverwritten()
+
+			// Extract the operations on the original index and replay them later.
```
Comment (Benjamin2037) [inline ddl/index_merge_tmp.go:268]: Where is the replay operations?

File: ddl/index_merge_tmp.go [hunk 9]
```diff
@@ -252,40 +259,49 @@ func (w *mergeIndexWorker) fetchTempIndexVals(txn kv.Transaction, taskRange reor
...
-			originVal, handle, isDelete, unique, keyVer := tablecodec.DecodeTempIndexValue(rawValue, isCommonHandle)
-			if keyVer == tables.TempIndexKeyTypeMerge || keyVer == tables.TempIndexKeyTypeDelete {
-				// For 'm' version kvs, they are double-written.
-				// For 'd' version kvs, they are written in the delete-only state and can be dropped safely.
-				return true, nil
+			tempIdxVal, err := tablecodec.DecodeTempIndexValue(rawValue, isCommonHandle)
+			if err != nil {
+				return false, err
 			}
+			tempIdxVal = tempIdxVal.FilterOverwritten()
```
Comment (Benjamin2037) [inline ddl/index_merge_tmp.go:266]: For non-uk, there is no need to do this tempIdxVal.FilterOverwritten() task.

Comment (tangenta) [reply ddl/index_merge_tmp.go:266]: This function does nothing when the key is non distinct.

File: ddl/index_merge_tmp.go (hunk 8 above)
Comment (tangenta) [reply ddl/index_merge_tmp.go:268]: It appends the key-values to a slice. The upper function replays them.

File: table/tables/index.go (hunk 7 above)
Comment (tangenta) [reply table/tables/index.go]: Done.

**Review by wjhuang2016 — APPROVED** [review]
