### PR TITLE
privileges: fix create temporary tables privilege

### LINKED ISSUE #29271: Creating temporary tables should need `CREATE TEMPORARY TABLES` privilege instead of `CREATE`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql -h127.1 -uroot -Ac

mysql> grant create on *.* to test_user;
Query OK, 0 rows affected (0.10 sec)

mysql> revoke create temporary tables on *.* from test_user;
Query OK, 0 rows affected (0.01 sec)
```

```sql
mysql -h127.1 -utest_user -Ac

mysql> create temporary table test.tmp(id int);
Query OK, 0 rows affected (0.00 sec)
```

### 2. What did you expect to see? (Required)

```sql
mysql -h127.1 -utest_user -Ac

mysql> create temporary table test.tmp(id int);
ERROR 1044 (42000): Access denied for user 'test_user'@'localhost' to database 'test'
```

### 3. What did you see instead (Required)

```sql
mysql -h127.1 -utest_user -Ac

mysql> create temporary table test.tmp(id int);
Query OK, 0 rows affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #29271

Problem Summary:
In MySQL, creating a temporary table needs `create temporary tables` privilege on the database, and subsequent statements on the table require no privileges.

Not fixed issues:
https://github.com/pingcap/tidb/issues/29280
https://github.com/pingcap/tidb/issues/29281
https://github.com/pingcap/tidb/issues/29282

### What is changed and how it works?

After collecting the `visitInfo`, filter the temporary tables.

This doesn't need a release note because it's not documented yet.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by djshow832** [comment]
I encountered an unstable test https://github.com/pingcap/tidb/issues/29283 and try to run it again.

File: planner/core/planbuilder.go [hunk 1]
```diff
@@ -3868,8 +3868,15 @@ func (b *PlanBuilder) buildDDL(ctx context.Context, node ast.DDLNode) (Plan, err
 			}
 		}
 		if b.ctx.GetSessionVars().User != nil {
-			authErr = ErrTableaccessDenied.GenWithStackByArgs("CREATE", b.ctx.GetSessionVars().User.AuthUsername,
-				b.ctx.GetSessionVars().User.AuthHostname, v.Table.Name.L)
+			// This is tricky here: we always need the visitInfo because it's not only used in privilege checks, and we
+			// must pass the table name. However, the privilege check is towards the database. We'll deal with it later.
+			if v.TemporaryKeyword == ast.TemporaryLocal {
+				authErr = ErrDBaccessDenied.GenWithStackByArgs(b.ctx.GetSessionVars().User.AuthUsername,
+					b.ctx.GetSessionVars().User.AuthHostname, v.Table.Schema.L)
```
Comment (lcwangchao) [inline planner/core/planbuilder.go:3875]: Why format `ErrDBaccessDenied` error message with table name?

File: privilege/privileges/privileges_test.go [hunk 2]
```diff
@@ -2677,6 +2679,156 @@ func TestGrantCreateTmpTables(t *testing.T) {
...
+	require.EqualError(t, err, "[planner:1044]Access denied for user 'vcreate'@'%' to database 'test'")
+	tk.Session().Auth(&auth.UserIdentity{Username: "vcreate_tmp", Hostname: "localhost"}, nil, nil)
+	tk.MustExec(createStmt)
+	tk.MustExec(dropStmt)
+	tk.Session().Auth(&auth.UserIdentity{Username: "vcreate_tmp_all", Hostname: "localhost"}, nil, nil)
+	// TODO: issue #29280 to be fixed.
+	//err = tk.ExecToErr(createStmt)
+	//require.EqualError(t, err, "[planner:1044]Access denied for user 'vcreate_tmp_all'@'%' to database 'test'")
+
+	tests := []struct {
```
Comment (lcwangchao) [inline privilege/privileges/privileges_test.go:2710]: Please add a case：

```
create view v1 as select * from tmp; -- should fail even user has CREATE VIEW priv
```

File: planner/core/optimizer.go [hunk 3]
```diff
@@ -120,6 +121,68 @@ func CheckPrivilege(activeRoles []*auth.RoleIdentity, pm privilege.Manager, vs [
...
+		privVisitInfo = make([]visitInfo, 0, len(vs))
+		for _, v := range vs {
+			if stmt.TemporaryKeyword == ast.TemporaryLocal && v.privilege == mysql.CreatePriv {
+				// `CREATE TEMPORARY TABLE` privilege is required from the database, not the table.
+				newVisitInfo := v
+				newVisitInfo.privilege = mysql.CreateTMPTablePriv
+				newVisitInfo.table = ""
+				privVisitInfo = append(privVisitInfo, newVisitInfo)
+			} else {
+				privVisitInfo = append(privVisitInfo, v)
```
Comment (lcwangchao) [inline planner/core/optimizer.go:143]: Do we need `needCheckTmpTablePriv` here?

Comment (djshow832) [reply planner/core/optimizer.go:143]: I don't think so. Any examples?

File: planner/core/planbuilder.go (hunk 1 above)
Comment (djshow832) [reply planner/core/planbuilder.go:3875]: It's not table name, it's schema name: `v.Table.Schema.L`.

File: privilege/privileges/privileges_test.go (hunk 2 above)
Comment (djshow832) [reply privilege/privileges/privileges_test.go:2710]: I don't think it's very related to the purpose of this PR. To avoid doing too many things in one PR, I'll file another issue and then test it.

Comment (djshow832) [reply privilege/privileges/privileges_test.go:2710]: See https://github.com/pingcap/tidb/issues/29286

File: planner/core/optimizer.go (hunk 3 above)
Comment (lcwangchao) [reply planner/core/optimizer.go:143]: For example: `create table t1 from select * from tmp` . Tough we do not support this syntax currently, adding some checks here can avoid hidden problems in the future.

File: planner/core/optimizer.go [hunk 4]
```diff
@@ -120,6 +121,68 @@ func CheckPrivilege(activeRoles []*auth.RoleIdentity, pm privilege.Manager, vs [
 	return nil
 }
 
+// VisitInfo4PrivCheck generates privilege check infos because privilege check of local temporary tables is different
+// with normal tables. `CREATE` statement needs `CREATE TEMPORARY TABLE` privilege from the database, and subsequent
+// statements do not need any privileges.
```
Comment (tiancaiamao) [inline planner/core/optimizer.go:126]: > `CREATE` statement needs `CREATE TEMPORARY TABLE` privilege from the database, and subsequent
// statements do not need any privileges.

Why not check it in the DDL operation?
If you add it as an additional check, it slow down all operations a bit which is unnecessary.

Comment (djshow832) [reply planner/core/optimizer.go:126]: I know, but there are too many operations to check, not only DDL but also DML and others.
If I add all these checks in the `planbuilder`, it will be too dirty.

Comment (djshow832) [reply planner/core/optimizer.go:126]: Besides, in `planbuilder`, I cannot add `visitInfo` but do not require privilege checks in a graceful way. `visitInfo` and privilege checks are bound together.

File: planner/core/optimizer.go (hunk 3 above)
Comment (djshow832) [reply planner/core/optimizer.go]: Addressed.

**Review by tiancaiamao — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Comment by djshow832** [comment]
Another bug https://github.com/pingcap/tidb/issues/29302 is just introduced after I submitted the PR, so I removed that test case until the bug is fixed.
