### PR TITLE
planner: fix invalid convert type in between...and...

### LINKED ISSUE #11177: Invalid results using BETWEEN...AND... with type conversion
## Bug Report

Please answer these questions before submitting your issue. Thanks!

Invalid results using BETWEEN...AND... with type conversation.

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
SELECT 'lvuleck' BETWEEN '2008-09-16 22:23:50' AND 0;
```

2. What did you expect to see?

```mysql
mysql> SELECT 'lvuleck' BETWEEN '2008-09-16 22:23:50' AND 0;
+-----------------------------------------------+
| 'lvuleck' BETWEEN '2008-09-16 22:23:50' AND 0 |
+-----------------------------------------------+
|                                             0 |
+-----------------------------------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> show warnings;
+---------+------+---------------------------------------------------------+
| Level   | Code | Message                                                 |
+---------+------+---------------------------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'lvuleck'             |
| Warning | 1292 | Truncated incorrect DOUBLE value: '2008-09-16 22:23:50' |
+---------+------+---------------------------------------------------------+
2 rows in set (0.00 sec)
```

3. What did you see instead?

```mysql
mysql> SELECT 'lvuleck' BETWEEN '2008-09-16 22:23:50' AND 38.8;
+--------------------------------------------------+
| 'lvuleck' BETWEEN '2008-09-16 22:23:50' AND 38.8 |
+--------------------------------------------------+
|                                                1 |
+--------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+----------------+
| Level   | Code | Message        |
+---------+------+----------------+
| Warning | 1265 | Data Truncated |
+---------+------+----------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @SunRunAway

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close #11177

Problem Summary:

### What is changed and how it works?
- get correct type for all type conversion in between ... and ...

Tests 

- Unit test

### Release note 

- fix an issue that invalid results using BETWEEN...AND... with type conversion

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: expression/integration_test.go [hunk 1]
```diff
@@ -7268,3 +7268,14 @@ func (s *testIntegrationSerialSuite) TestIssue18949(c *C) {
...
+
+func (s *testIntegrationSerialSuite) TestIssue11177(c *C) {
+	collate.SetNewCollationEnabledForTest(true)
+	defer collate.SetNewCollationEnabledForTest(false)
+
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustQuery("SELECT 'lvuleck' BETWEEN '2008-09-16 22:23:50' AND 0;").Check(testkit.Rows("0"))
+	tk.MustQuery("show warnings;").Check(testkit.Rows("Warning 1292 Truncated incorrect FLOAT value: 'lvuleck'", "Warning 1292 Truncated incorrect FLOAT value: '2008-09-16 22:23:50'"))
+	tk.MustQuery("SELECT 'aa' BETWEEN 'bb' AND 0;").Check(testkit.Rows("1"))
+	tk.MustQuery("show warnings;").Check(testkit.Rows("Warning 1292 Truncated incorrect FLOAT value: 'aa'", "Warning 1292 Truncated incorrect FLOAT value: 'bb'"))
```
Comment (SunRunAway) [inline expression/integration_test.go:7280]: Could you add more test cases for `CmpTp` is `ETInt` or `ETString`?

Comment (xiongjiwei) [reply expression/integration_test.go]: updated

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Comment by xiongjiwei** [comment]
@SunRunAway hi, please help me merge

**Review by XuHuaiyu — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
