### PR TITLE
executor: fix prepare 'do 1' statement panic

### LINKED ISSUE #31141: prepare 'do 1' panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
prepare stmt from 'do 1'
```

A regression found by tidb-test https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/8001/pipeline/

Introduced by https://github.com/pingcap/tidb/pull/30981/

The problem is, we seems to be not running tidb-test for several days, otherwise the bug should expose early.

### 2. What did you expect to see? (Required)

Success

### 3. What did you see instead (Required)

nil pointer panic

### 4. What is your TiDB version? (Required)

commit fb3a3b356305dd1cce9c9b3ab5a2c6bdf70912cc (HEAD -> master, origin/master, origin/HEAD)
Author: zyguan <zhongyangguan@gmail.com>
Date:   Wed Dec 29 18:35:50 2021 +0800

    unistore: avoid nil region.meta in ut (#31116)

    close pingcap/tidb#30440

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #31141

Problem Summary:

### What is changed and how it works?

'do' statement is a bit special, it's translated to Projection in our code, but the query do not return result to the client.

https://dev.mysql.com/doc/refman/8.0/en/do.html

The old code check `p.Schema().Len() > 0` and can't handle the `do` case, so it panics.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: executor/adapter.go [hunk 1]
```diff
@@ -481,22 +481,48 @@ func (a *ExecStmt) handleNoDelay(ctx context.Context, e Executor, isPessimistic
...
-		return true, r, err
+		return true
 	}
+	return false
+}
 
-	return false, nil, nil
+func isNoResultPlan(p plannercore.Plan) bool {
+	fmt.Println("in is no result plan ===", p)
+
```
Comment (tangenta) [inline executor/adapter.go:511]:
```suggestion
```

Please remove debug lines.

File: executor/adapter.go [hunk 2]
```diff
@@ -481,22 +481,48 @@ func (a *ExecStmt) handleNoDelay(ctx context.Context, e Executor, isPessimistic
...
+	}
+
+	return false, nil, nil
+}
+
+func isNoResultExecutor(e Executor) bool {
+	if e.Schema().Len() == 0 {
+		return true
+	}
+	if proj, ok := e.(*ProjectionExec); ok && proj.calculateNoDelay {
```
Comment (djshow832) [inline executor/adapter.go:500]: This is different from before. It didn't call `handlePessimisticDML` in this case. Are you intended to modify the logic?

File: executor/prepared.go [hunk 3]
```diff
@@ -229,7 +229,7 @@ func (e *PrepareExec) Next(ctx context.Context, req *chunk.Chunk) error {
 	if err != nil {
 		return err
 	}
-	if p.Schema().Len() > 0 {
+	if !isNoResultPlan(p) {
```
Comment (djshow832) [inline executor/prepared.go:232]: Please add some comments here.

Comment (tiancaiamao) [reply executor/prepared.go:235]: Done

File: executor/adapter.go (hunk 2 above)
Comment (tiancaiamao) [reply executor/adapter.go]: I'm not intending to modify the old logic... just a tiny refactor ...
I get trapped here because this special logic, and want to avoid others been trapped again, so the refactor

Comment (tiancaiamao) [reply executor/adapter.go]: OK, I just reset the change here and touch only the necessary code.

**Review by tangenta — APPROVED** [review]

**Review by djshow832 — APPROVED** [review]
