### PR TITLE
plan, executor_test: fix bug for user variable.

### LINKED ISSUE #3774: local variable assignment dosen't take effect in join statement.
```sql
mysql> select @a := @a + 1 from t, (select @a := 0) b;
+--------------+
| @a := @a + 1 |
+--------------+
|         NULL |
|         NULL |
|         NULL |
+--------------+
3 rows in set (0.00 sec)

mysql> select @a := @a + 1 from t, (select @a := 0) b;
+--------------+
| @a := @a + 1 |
+--------------+
|            1 |
|            2 |
|            3 |
+--------------+
3 rows in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by hanfei1991**
fix #3774

### CODE REVIEW

File: executor/join_test.go [hunk 1]
```diff
@@ -231,6 +231,11 @@ func (s *testSuite) TestJoin(c *C) {
 	_, err = tk.Exec("select /*+ TIDB_INLJ(t) TIDB_SMJ(t) */ * from t join t1 on t.a=t1.a")
 	c.Assert(err, NotNil)
 
+	tk.MustExec("drop table if exists t, t1")
```
Comment (shenli) [inline executor/join_test.go]: Why drop t1 here?

Comment (hanfei1991) [inline executor/join_test.go]: My mistake.

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@XuHuaiyu @zimulala  PTAL

**Comment by XuHuaiyu** [comment]
LGTM
