### PR TITLE
executor: reset all state when table reader executor close

### LINKED ISSUE #33214: the query results for enum column is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
source  [test.txt](https://github.com/pingcap/tidb/files/8285072/test.txt);

alter table IDT_MULTI15863STROBJSTROBJ cache;
# please execute many times to reporduce
 select col1 from IDT_MULTI15863STROBJSTROBJ t1 where (select count(*) from IDT_MULTI15863STROBJSTROBJ t2 where t2.col1 in (t1.col1, "none")) > 1;
```
### 2. What did you expect to see? (Required)
```
MySQL [test]> select col1 from IDT_MULTI15863STROBJSTROBJ t1 where (select count(*) from IDT_MULTI15863STROBJSTROBJ t2 where t2.col1 in (t1.col1, "none")) > 1;
+------+
| col1 |
+------+
...
+------+
58 rows in set (0.03 sec)
```
### 3. What did you see instead (Required)
```

MySQL [test]> select col1 from IDT_MULTI15863STROBJSTROBJ t1 where (select count(*) from IDT_MULTI15863STROBJSTROBJ t2 where t2.col1 in (t1.col1, "none")) > 1;
+------+
| col1 |
+------+
...
+------+
60 rows in set (0.03 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v6.0.0-alpha-122-g46c43fe
Edition: Community
Git Commit Hash: 46c43febcac0e24bc9f0872e93cf6125db69d93d
Git Branch: master
UTC Build Time: 2022-03-17 01:02:30
GoVersion: go1.17.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #33214

Problem Summary:

### What is changed and how it works?

When there is a `Apply` executor, it may Open/Close its children executor several times.

```
mysql> explain select col from t t1 where (select count(*) from t t2 where t2.col = t1.col or t2.col =  'sdf') > 1;
+------------------------------------+---------+-----------+---------------+-------------------------------------------------------+
| id                                 | estRows | task      | access object | operator info                                         |
+------------------------------------+---------+-----------+---------------+-------------------------------------------------------+
| Projection_13                      | 5.00    | root      |               | test.t.col                                            |
| └─Apply_15                         | 5.00    | root      |               | CARTESIAN inner join                                  |
|   ├─UnionScan_16(Build)            | 5.00    | root      |               |                                                       |
|   │ └─TableReader_18               | 5.00    | root      |               | data:TableFullScan_17                                 |
|   │   └─TableFullScan_17           | 5.00    | cop[tikv] | table:t1      | keep order:false, stats:pseudo                        |
|   └─Selection_19(Probe)            | 0.80    | root      |               | gt(Column#5, 1)                                       |
|     └─StreamAgg_21                 | 1.00    | root      |               | funcs:count(1)->Column#5                              |
|       └─UnionScan_22               | 0.01    | root      |               | or(eq(test.t.col, test.t.col), eq(test.t.col, "sdf")) |
|         └─TableReader_25           | 0.01    | root      |               | data:Selection_24                                     |
|           └─Selection_24           | 0.01    | cop[tikv] |               | or(eq(test.t.col, test.t.col), eq(test.t.col, "sdf")) |
|             └─TableFullScan_23     | 5.00    | cop[tikv] | table:t2      | keep order:false, stats:pseudo                        |
+------------------------------------+---------+-----------+---------------+-------------------------------------------------------+
11 rows in set (0.00 sec)
```

So it's important that after Open/Close, the executor can be reused.
However, the table reader doen't reset its `keyRange` and when UnionScan Open/Close it will get repeated keyRange.
And finally return wrong result to its parent executor.

### Check List

Tests 

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ichn-hu — APPROVED** [review]
LGTM

File: executor/table_reader.go [hunk 1]
```diff
@@ -246,15 +246,14 @@ func (e *TableReaderExecutor) Next(ctx context.Context, req *chunk.Chunk) error
 
 // Close implements the Executor Close interface.
 func (e *TableReaderExecutor) Close() error {
-	if e.dummy {
-		return nil
-	}
-
 	var err error
 	if e.resultHandler != nil {
 		err = e.resultHandler.Close()
```
Comment (lcwangchao) [inline executor/table_reader.go:251]: Do we need to set `e.resultHandler = nil` ? It seems will not cause any problem now because `Open()` will reassign it every time. But I think it's better to reset its state to the state before Open to decouple with the implement in `Open`

Comment (tiancaiamao) [reply executor/table_reader.go:251]: This is kind of refactor... **but if we don't have cases to cover that, it's better to keep the old code**/behaviour IMO.
I don't want any fix on fix to be introduced.

**Review by lcwangchao — APPROVED** [review]
