### PR TITLE
ddl: correct default year value

### LINKED ISSUE #13094: The default year should be '0000' instead of '2000'
## Bug Report

1. What did you do?

```sql
create table w(a int);
insert into w values (1);
alter table w add column b year(4) not null;
select * from w;
```

2. What did you expect to see?

```
mysql> select * from w;
+------+------+
| a    | b    |
+------+------+
|    1 | 0000 |
+------+------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```
mysql> select * from w;
+------+------+
| a    | b    |
+------+------+
|    1 | 2000 |
+------+------+
1 row in set (0.00 sec)
```

Seems to be missed with fixing #8291. 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-685-g5b161df35
Git Commit Hash: 5b161df3533db3dce6badca54c867b95f4a0d672
Git Branch: master
UTC Build Time: 2019-11-02 10:21:24
GoVersion: go version go1.13.3 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #13094
Problem Summary: Set the correct default year value. And wrap the function to stress the consistence of the code path between add/modify columns.

### Related changes

- Need to cherry-pick to the release branch

### Check List

Tests

- Unit test
- Integration test

### Release note

- fix the default year column value from "2000" to "0000"

### CODE REVIEW

**Review by zimulala — COMMENTED** [review]
LGTM

**Comment by zimulala** [comment]
PTAL @tangenta

File: ddl/db_test.go [hunk 1]
```diff
@@ -2115,6 +2115,12 @@ LOOP:
 	hasNotNull = mysql.HasNotNullFlag(colC.Flag)
 	c.Assert(hasNotNull, IsFalse)
 
+	// add datetime type column
+	s.mustExec(tk, c, "create table test_on_update_e (c1 int);")
```
Comment (djshow832) [inline ddl/db_test.go:2119]: No defer dropping?

Comment (xhebox) [reply ddl/db_test.go:2119]: There are multiple `create` statements without defer dropping, e.g. https://github.com/pingcap/tidb/blob/322639bf25dfa54496d4f4bdd6a81fdc62c96b97/ddl/db_test.go#L2096. I  did not think much. Maybe it is because `txn.Rollback` at line https://github.com/pingcap/tidb/blob/322639bf25dfa54496d4f4bdd6a81fdc62c96b97/ddl/db_test.go#L2066 or a read-only storage backend?

Comment (djshow832) [reply ddl/db_test.go:2119]: Rollback won't rollback DDL. Some other test cases contain dropping tables.
You'd better add dropping.

Comment (xhebox) [reply ddl/db_test.go:2121]: Checked, no drop statements for other two tables. Added drop statements to these three tables.

**Review by djshow832 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
