### PR TITLE
test: fix next gen tests

### LINKED ISSUE #62883: Fix txn related tests for next-gen
## Enhancement
Fix the txn related tests for next-gen to enable CI

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #62883 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by ekexium** [comment]
2 remaining issues that for txn_test and pessimistic_test: #62775 and next-gen tikv issue 3204.

**Comment by ekexium** [comment]
`TestValidateReadOnlyInStalenessTransaction` failed, but I can't reproduce it yet. Will keep an eye on it.

**Review by MyonKeminta — APPROVED** [review]

File: tests/realtikvtest/txntest/txn_test.go [hunk 1]
```diff
@@ -546,7 +547,9 @@ func TestDMLWithAddForeignKey(t *testing.T) {
 	store := realtikvtest.CreateMockStoreAndSetup(t)
 	tk := testkit.NewTestKit(t, store)
 	tk.MustExec("set global tidb_enable_1pc='OFF';")
-	tk.MustExec("set global tidb_enable_metadata_lock='OFF';")
+	if !kerneltype.IsNextGen() {
```
Comment (D3Hunter) [inline tests/realtikvtest/txntest/txn_test.go:550]:
```suggestion
	if kerneltype.IsClassic() {
```
