### PR TITLE
planner: Fix CAST AS BINARY index usage | tidb-test=pr/2732

### LINKED ISSUE #67899: planner: CAST to BINARY results in index full scan
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

# CAST AS BINARY should use index range scan instead of index full scan.
drop table if exists t;
create table t (uuid varchar(36) charset utf8mb4 collate utf8mb4_general_ci, index idx_uuid(uuid));
insert into t values ('7dce58ba-ba84-4297-94cf-c23cf3a39ed3');
insert into t values ('ABC');
insert into t values ('abc');
# EQ with CAST AS BINARY: should use IndexRangeScan + Selection, not IndexFullScan.
explain format='plan_tree' select * from t where uuid = cast('7dce58ba-ba84-4297-94cf-c23cf3a39ed3' as binary);
# Without CAST: should use IndexRangeScan (point range).
explain format='plan_tree' select * from t where uuid = '7dce58ba-ba84-4297-94cf-c23cf3a39ed3';

### 2. What did you expect to see? (Required)

Index range scan

### 3. What did you see instead (Required)

```
 explain format='plan_tree' select * from t where uuid = cast('7dce58ba-ba84-4297-94cf-c23cf3a39ed3' as binary);
+-----------------------+-----------+-------------------------------+---------------------------------------------------------+
| id                    | task      | access object                 | operator info                                           |
+-----------------------+-----------+-------------------------------+---------------------------------------------------------+
| IndexReader           | root      |                               | index:Selection                                         |
| └─Selection           | cop[tikv] |                               | eq(test.t.uuid, "7dce58ba-ba84-4297-94cf-c23cf3a39ed3") |
|   └─IndexFullScan     | cop[tikv] | table:t, index:idx_uuid(uuid) | keep order:false, stats:pseudo                          |
+-----------------------+-----------+-------------------------------+---------------------------------------------------------+
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #67899

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Equality and IN comparisons involving binary collation are now treated as usable index access conditions while still being preserved for correct binary filtering; IN lists require constant values when applicable.

* **Chores**
  * Range-detection flow now preserves remaining CNF conditions for later filtering and propagates errors/values through the caller chain.

* **Tests**
  * Added and updated unit and integration tests validating EXPLAIN plans and results for CAST AS BINARY and collation scenarios.

### CODE REVIEW

File: pkg/util/ranger/detacher.go [hunk 1]
```diff
@@ -1101,8 +1104,10 @@ func (d *rangeDetacher) detachCondAndBuildRangeForCols() (*DetachRangeResult, er
 // It will find the point query column firstly and then extract the range query column.
 // rangeMaxSize is the max memory limit for ranges. O indicates no memory limit. If you ask that all conditions must be used
 // for building ranges, set rangeMemQuota to 0 to avoid range fallback.
+// The returned remainedConds are conditions that must be re-applied as filters (e.g. when a
+// collation mismatch makes the range approximate but the condition is still needed for correctness).
 func DetachSimpleCondAndBuildRangeForIndex(sctx *rangerctx.RangerContext, conditions []expression.Expression,
-	cols []*expression.Column, lengths []int, rangeMaxSize int64) (Ranges, []expression.Expression, error) {
+	cols []*expression.Column, lengths []int, rangeMaxSize int64) (ranges Ranges, accessConds []expression.Expression, remainedConds []expression.Expression, err error) {
```
Comment (qw4990) [inline pkg/util/ranger/detacher.go:1110]: This change seems unnecessary?

Comment (qw4990) [reply pkg/util/ranger/detacher.go:1110]: Oh it's for test only.

**Review by qw4990 — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
