### PR TITLE
*: Fix issue 39999, used wrong column id list for checking partitions

### LINKED ISSUE #39999: wrong result for clustered index and dynamic mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists c, t;
CREATE TABLE `c` (
  `serial_id` varchar(24),
  `txt_account_id` varchar(24),
  `capital_sub_class` varchar(10),
  `occur_trade_date` date,
  `occur_amount` decimal(16,2),
  `broker` varchar(10),
  PRIMARY KEY (`txt_account_id`,`occur_trade_date`,`serial_id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_serial_id` (`serial_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci 
PARTITION BY RANGE COLUMNS(`serial_id`)(
 PARTITION `p202209` VALUES LESS THAN ("20221001"),
 PARTITION `p202210` VALUES LESS THAN ("20221101"),
 PARTITION `p202211` VALUES LESS THAN ("20221201")
);


CREATE TABLE `t` (
  `txn_account_id` varchar(24),
  `account_id` varchar(32),
  `broker` varchar(10),
  PRIMARY KEY (`txn_account_id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `c` VALUES ('2022111700196920','04482786','CUST','2022-11-17',-2.01,'0009');
INSERT INTO `t` VALUES ('04482786','1142927','0009');

set tidb_partition_prune_mode='dynamic';
analyze table c;
select c.occur_amount from c force index (primary) join t on c.txt_account_id=t.txn_account_id and c.capital_sub_class='CUST' and t.account_id='1142927' and t.broker='0009' and c.occur_trade_date = '2022-11-17';
select sleep(30);  -- maybe need more time
select c.occur_amount from  c force index (primary) join  t on c.txt_account_id=t.txn_account_id and c.capital_sub_class='CUST' and t.account_id='1142927' and t.broker='0009' and c.occur_trade_date = '2022-11-17';



```

### 2. What did you expect to see? (Required)
```sql
[20:16:30]MySQL root:db1> select c.occur_amount from  c force index (primary) join  t on c.txt_account_id=t.txn_account_id and c.capital_sub_class='CUST' and t.account_id='1142927' and t.broker='0009' and c.occur_trade_date = '2022-11-17';
+--------------+
| occur_amount |
+--------------+
| -2.01        |
+--------------+
```
### 3. What did you see instead (Required)
```sql
[20:16:30]MySQL root:db1> select c.occur_amount from  c force index (primary) join  t on c.txt_account_id=t.txn_account_id and c.capital_sub_class='CUST' and t.account_id='1142927' and t.broker='0009' and c.occur_trade_date = '2022-11-17';
+--------------+
| occur_amount |
+--------------+
+--------------+
```

### 4. What is your TiDB version? (Required)
```sql
[20:17:42]MySQL root:db1> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v6.6.0-alpha                             |
| Edition: Community                                        |
| Git Commit Hash: 4ad530ecdcc6a54e7be0fe449c261be10fb555bb |
| Git Branch: heads/refs/tags/v6.6.0-alpha                  |
| UTC Build Time: 2022-12-14 14:26:06                       |
| GoVersion: go1.19.3                                       |
| Race Enabled: false                                       |
| TiKV Min Version: 6.2.0-alpha                             |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #39999 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/builder.go [hunk 1]
```diff
@@ -4149,12 +4146,6 @@ func (builder *dataReaderBuilder) buildTableReaderForIndexJoin(ctx context.Conte
 	}
 	tbl, _ := builder.is.TableByID(tbInfo.ID)
 	pt := tbl.(table.PartitionedTable)
-	pe, err := tbl.(interface {
```
Comment (bb7133) [inline executor/builder.go:4152]: Why removing the code here?

Comment (mjonss) [reply executor/builder.go:4152]: I think the logic should really be encapsulated with the tables pkg. But I have just gone through the use of this interface check and it is used in several places, so I think it may be better to adjust this patch and then create a separate 'refactor' issue for future versions.

I will change the patch to go with the old style.

Comment (bb7133) [reply executor/builder.go:4152]: Got it, thanks!

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]
