### PR TITLE
Lightning: clarify disk-quota precheck message and add warning for invalid quota

### LINKED ISSUE #61542: lightning: refine the error message of lightning `DiskQuota` precheck
## Enhancement

Currently, during the precheck phase, if the disk capacity is less than disk quota, precheck will failed. But the error message is a bit misleading:

```
+----+------------------------------------------------------------------------------------------------------------------------------------+-------------+--------+
|  6 | local disk space may not enough to finish import, estimate sorted data size is XXX, but local available is XXX, please s | critical    | false  |
|    | et `tikv-importer.disk-quota` to a smaller value than XXX or change `mydumper.sorted-kv-dir` to another disk with enough spac |             |        |
|    | e to finish imports                                                                                                                |             |        |                                                                                                             |             |        |
+----+------------------------------------------------------------------------------------------------------------------------------------+-------------+--------+
```

This check has nothing to do with estimated sorted size, but it's outputed at the beginning of the error message.  If users don't read the error message carefully, they may misunderstand it.

https://github.com/pingcap/tidb/blob/0d8e2bb4c57ecfaaee14a42a693f9e41f34cda34/lightning/pkg/importer/precheck_impl.go#L591-L598

### PR DESCRIPTION
**Pull request by abrarr21**
Issue Number: close #61542

### What problem does this PR solve?

The current error message during Lightning's disk quota precheck is misleading. It incorrectly references the estimated sorted data size when the real problem is that the configured disk-quota exceeds available local disk space. This causes confusion for users trying to troubleshoot disk space issues.

### What changed and how does it work?

- Refined the disk quota precheck error message to clearly state that local disk space is insufficient compared to the configured disk-quota.
- Removed misleading references to estimated data size from the error message.
- Added a warning log when `tikv-importer.disk-quota` is set to 0 or a negative value, indicating possible misconfiguration.
- Improved variable naming and code comments for clarity and maintainability.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 
Only error message wording was changed; no functional logic impacted.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by alastori** [comment]
Warning and error message content LGTM. Thanks @abrarr21.

File: lightning/pkg/importer/precheck_impl.go [hunk 1]
```diff
@@ -576,32 +576,43 @@ func (ci *localTempKVDirCheckItem) Check(ctx context.Context) (*precheck.CheckRe
 	if err != nil {
 		return nil, errors.Trace(err)
 	}
-	localAvailable := int64(storageSize.Available)
+	localAvailable := int64(storageSize.Available)           //Available disk space in bytes
+	availableStr := units.BytesSize(float64(localAvailable)) //Human-readable availabe space
```
Comment (joechenrh) [inline lightning/pkg/importer/precheck_impl.go]:
```suggestion
	localAvailable := int64(storageSize.Available)           // Available disk space in bytes
	availableStr := units.BytesSize(float64(localAvailable))
```
I think we don't need to add comment for every variable

File: lightning/pkg/importer/precheck_impl.go [hunk 2]
```diff
@@ -576,32 +576,43 @@ func (ci *localTempKVDirCheckItem) Check(ctx context.Context) (*precheck.CheckRe
...
+
 	estimatedDataSizeResult, err := ci.preInfoGetter.EstimateSourceDataSize(ctx)
 	if err != nil {
 		return nil, errors.Trace(err)
 	}
 	estimatedDataSizeWithIndex := estimatedDataSizeResult.SizeWithIndex
+	estimatedStr := units.BytesSize(float64(estimatedDataSizeWithIndex)) //Human-readable estimated size
+
+	diskQuota := int64(ci.cfg.TikvImporter.DiskQuota)   //Configured disk quota in bytes
+	diskQuotaStr := units.BytesSize(float64(diskQuota)) //Human-readabledisk quota
```
Comment (joechenrh) [inline lightning/pkg/importer/precheck_impl.go]: ditto

File: lightning/pkg/importer/precheck_impl.go [hunk 3]
```diff
@@ -576,32 +576,43 @@ func (ci *localTempKVDirCheckItem) Check(ctx context.Context) (*precheck.CheckRe
...
+
+	//Warn the user if diskQuota is 0 or negative, as it's likely a misconfiguration
+	if diskQuota <= 0 {
+		log.FromContext(ctx).Warn("`tikv-importer.disk-quota` is set to 0 or less; please configure a valid positive value.")
```
Comment (joechenrh) [inline lightning/pkg/importer/precheck_impl.go]:
```suggestion
		log.FromContext(ctx).Warn("`tikv-importer.disk-quota` is set to 0 or less; please configure a valid positive value")
```
By usual, we don't add symbol at the end of the log

File: lightning/pkg/importer/precheck_impl.go [hunk 4]
```diff
@@ -577,31 +577,42 @@ func (ci *localTempKVDirCheckItem) Check(ctx context.Context) (*precheck.CheckRe
...
 	if err != nil {
 		return nil, errors.Trace(err)
 	}
 	estimatedDataSizeWithIndex := estimatedDataSizeResult.SizeWithIndex
+	estimatedStr := units.BytesSize(float64(estimatedDataSizeWithIndex))
+
+	diskQuota := int64(ci.cfg.TikvImporter.DiskQuota)
+	diskQuotaStr := units.BytesSize(float64(diskQuota))
+
+	//Warn the user if diskQuota is 0 or negative, as it's likely a misconfiguration
```
Comment (joechenrh) [inline lightning/pkg/importer/precheck_impl.go]:
```suggestion
	// Warn the user if diskQuota is 0 or negative, as it's likely a misconfiguration
```

**Comment by joechenrh** [comment]
`TestLocalResource` failed, please fix this test
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/34916/pipeline

**Comment by abrarr21** [comment]
@joechenrh Please review it.

**Comment by D3Hunter** [comment]
@abrarr21 please **DO NOT** change the template of the PR description, the bot will do static check by checking some words in the template, else you PR will be labeled as `do-not-merge/needs-tests-checked`, especially those enclosed inside  
 markdown comment `<!--   -->`

**Comment by abrarr21** [comment]
Hey @alastori, just a quick ping — the PR’s all set and waiting for one last LGTM. Would be great if you could take a look. Thanks!

**Review by D3Hunter — APPROVED** [review]

**Comment by alastori** [comment]
> Hey @alastori, just a quick ping — the PR’s all set and waiting for one last LGTM. Would be great if you could take a look. Thanks!

@joechenrh , @lance6716 , or @D3Hunter PTAL
