### PR TITLE
timer: fix some timezone behavior in timer framework

### LINKED ISSUE #51768: The time drifts in timer store in daylight saving time
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The below test will fail:

```
func TestTimerStoreWithDST(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewTestKit(t, store)
	dbName := "test"
	tblName := "timerstore"
	tk.MustExec("use test")
	tk.MustExec(tablestore.CreateTimerTableSQL(dbName, tblName))
	tk.MustExec("set @@time_zone = 'America/Los_Angeles'")

	pool := pools.NewResourcePool(func() (pools.Resource, error) {
		return tk.Session(), nil
	}, 1, 1, time.Second)
	defer pool.Close()

	timerStore := tablestore.NewTableTimerStore(1, pool, dbName, tblName, nil)
	defer timerStore.Close()

	watermark, err := time.ParseInLocation(time.DateTime, "2024-11-03 09:30:00", time.UTC)
	require.NoError(t, err)

	id, err := timerStore.Create(context.TODO(), &api.TimerRecord{
		TimerSpec: api.TimerSpec{
			Namespace:       "default",
			Key:             "test",
			SchedPolicyType: api.SchedEventInterval,
			SchedPolicyExpr: "1h",
			Watermark:       watermark,
		},
	})
	require.NoError(t, err)

	timer, err := timerStore.GetByID(context.TODO(), id)
	require.NoError(t, err)
	// this assert will fail
	require.Equal(t, watermark.In(time.UTC).String(), timer.Watermark.In(time.UTC).String())
}
```

### 2. What did you expect to see? (Required)

test success

### 3. What did you see instead (Required)

```
--- FAIL: TestTimerStoreWithDST (2.53s)

Expected :2024-11-03 09:30:00 +0000 UTC
Actual   :2024-11-03 08:30:00 +0000 UTC
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #51768

### What changed and how does it work?

- fix the timer store's watermark drift for DST
- refine the behavior for the timer store with time zone. For time fields in `TimerRecord`, their location should be same with the `TimerRecord.Location` field

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/timer/tablestore/store.go [hunk 1]
```diff
@@ -148,12 +148,27 @@ func (s *tableTimerStoreCore) List(ctx context.Context, cond api.Cond) ([]*api.T
 			timerData = row.GetBytes(3)
 		}
 
+		tz := row.GetString(4)
```
Comment (YangKeao) [inline pkg/timer/tablestore/store.go:151]: Why use a separated `tzParse`, rather than use `tz` directly here?

Comment (lcwangchao) [reply pkg/timer/tablestore/store.go:151]: because `tz` will be assigned to `TimerSpec.TimeZone` but `tzParse` is used to parse the real location.

For example, if user created a timer with time zone "" (an empty string, means to use database timezone). The returned `TimerSpec.TimeZone` should also be an empty, but we should use a valid time zone string to parse it to `time.Location`

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]
LGTM
