### PR TITLE
disttask: do not retry meta initialization if context done

### LINKED ISSUE #49753: flaky test TestIssue24210
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
 [2023/12/25 03:46:07.786 +00:00] [WARN] [session.go:2240] ["run statement failed"] [schemaVersion=50] [error="mock ProjectionExec.baseExecutor.Open returned error"] [errorVerbose="mock ProjectionExec.baseExecutor.Open returned error\ngithub.com/pingcap/tidb/pkg/executor.(*ProjectionExec).Open\n\tpkg/executor/projection.go:93\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).openExecutor\n\tpkg/executor/adapter.go:1238\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec\n\tpkg/executor/adapter.go:566\ngithub.com/pingcap/tidb/pkg/session.runStmt\n\tpkg/session/session.go:2386\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\tpkg/session/session.go:2228\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext\n\tpkg/testkit/testkit.go:364\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).Exec\n\tpkg/testkit/testkit.go:337\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecToErr\n\tpkg/testkit/testkit.go:410\npkg/executor/test/issuetest/issuetest_test_test.TestIssue24210\n\tpkg/executor/test/issuetest/executor_issue_test.go:47\ntesting.tRunner\n\tGOROOT/src/testing/testing.go:1595\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1650"] [session="{\n  \"currDBName\": \"test\",\n  \"id\": 1,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": null\n}"]
[2023/12/25 03:46:07.786 +00:00] [WARN] [session.go:2240] ["run statement failed"] [schemaVersion=50] [error="mock ProjectionExec.baseExecutor.Open returned error"] [errorVerbose="mock ProjectionExec.baseExecutor.Open returned error\ngithub.com/pingcap/tidb/pkg/executor.(*ProjectionExec).Open\n\tpkg/executor/projection.go:93\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*InsertExec).Open\n\tpkg/executor/insert.go:344\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).openExecutor\n\tpkg/executor/adapter.go:1238\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec\n\tpkg/executor/adapter.go:566\ngithub.com/pingcap/tidb/pkg/session.runStmt\n\tpkg/session/session.go:2386\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\tpkg/session/session.go:2228\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal\n\tpkg/session/session.go:1600\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.ExecSQL\n\tpkg/disttask/framework/storage/task_table.go:119\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).executeSQLWithNewSession.func1\n\tpkg/disttask/framework/storage/task_table.go:214\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewSession\n\tpkg/disttask/framework/storage/task_table.go:179\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).executeSQLWithNewSession\n\tpkg/disttask/framework/storage/task_table.go:213\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).StartManager\n\tpkg/disttask/framework/storage/task_table.go:702\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).initMeta\n\tpkg/disttask/framework/taskexecutor/manager.go:111\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).Start\n\tpkg/disttask/framework/taskexecutor/manager.go:129\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).distTaskFrameworkLoop\n\tpkg/domain/domain.go:1497\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).InitDistTaskLoop.func1\n\tpkg/domain/domain.go:1491\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1\n\tpkg/util/wait_group_wrapper.go:99\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1650"] [session="{\n  \"currDBName\": \"\",\n  \"id\": 0,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": null\n}"]
[2023/12/25 03:46:07.786 +00:00] [WARN] [manager.go:116] ["start manager failed"] [scope=] ["retry times"=0] [error="mock ProjectionExec.baseExecutor.Open returned error"] [errorVerbose="mock ProjectionExec.baseExecutor.Open returned error\ngithub.com/pingcap/tidb/pkg/executor.(*ProjectionExec).Open\n\tpkg/executor/projection.go:93\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*InsertExec).Open\n\tpkg/executor/insert.go:344\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).openExecutor\n\tpkg/executor/adapter.go:1238\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec\n\tpkg/executor/adapter.go:566\ngithub.com/pingcap/tidb/pkg/session.runStmt\n\tpkg/session/session.go:2386\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\tpkg/session/session.go:2228\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal\n\tpkg/session/session.go:1600\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.ExecSQL\n\tpkg/disttask/framework/storage/task_table.go:119\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).executeSQLWithNewSession.func1\n\tpkg/disttask/framework/storage/task_table.go:214\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewSession\n\tpkg/disttask/framework/storage/task_table.go:179\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).executeSQLWithNewSession\n\tpkg/disttask/framework/storage/task_table.go:213\ngithub.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).StartManager\n\tpkg/disttask/framework/storage/task_table.go:702\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).initMeta\n\tpkg/disttask/framework/taskexecutor/manager.go:111\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).Start\n\tpkg/disttask/framework/taskexecutor/manager.go:129\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).distTaskFrameworkLoop\n\tpkg/domain/domain.go:1497\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).InitDistTaskLoop.func1\n\tpkg/domain/domain.go:1491\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1\n\tpkg/util/wait_group_wrapper.go:99\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1650"]
[2023/12/25 03:46:07.787 +00:00] [INFO] [tidb.go:286] ["rollbackTxn called due to ddl/autocommit failure"]
[2023/12/25 03:46:07.787 +00:00] [WARN] [session.go:2240] ["run statement failed"] [schemaVersion=50] [error="mock HashAggExec.baseExecutor.Open returned error"] [errorVerbose="mock HashAggExec.baseExecutor.Open returned error\ngithub.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).Open\n\tpkg/executor/aggregate/agg_hash_executor.go:204\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).openExecutor\n\tpkg/executor/adapter.go:1238\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec\n\tpkg/executor/adapter.go:566\ngithub.com/pingcap/tidb/pkg/session.runStmt\n\tpkg/session/session.go:2386\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\tpkg/session/session.go:2228\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext\n\tpkg/testkit/testkit.go:364\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).Exec\n\tpkg/testkit/testkit.go:337\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecToErr\n\tpkg/testkit/testkit.go:410\npkg/executor/test/issuetest/issuetest_test_test.TestIssue24210\n\tpkg/executor/test/issuetest/executor_issue_test.go:53\ntesting.tRunner\n\tGOROOT/src/testing/testing.go:1595\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1650"] [session="{\n  \"currDBName\": \"test\",\n  \"id\": 1,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": null\n}"]
[2023/12/25 03:46:07.787 +00:00] [INFO] [tidb.go:286] ["rollbackTxn called due to ddl/autocommit failure"]
[2023/12/25 03:46:07.787 +00:00] [WARN] [session.go:2240] ["run statement failed"] [schemaVersion=50] [error="mock StreamAggExec.baseExecutor.Open returned error"] [errorVerbose="mock StreamAggExec.baseExecutor.Open returned error\ngithub.com/pingcap/tidb/pkg/executor/aggregate.(*StreamAggExec).Open\n\tpkg/executor/aggregate/agg_stream_executor.go:58\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).openExecutor\n\tpkg/executor/adapter.go:1238\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec\n\tpkg/executor/adapter.go:566\ngithub.com/pingcap/tidb/pkg/session.runStmt\n\tpkg/session/session.go:2386\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\tpkg/session/session.go:2228\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext\n\tpkg/testkit/testkit.go:364\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).Exec\n\tpkg/testkit/testkit.go:337\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecToErr\n\tpkg/testkit/testkit.go:410\npkg/executor/test/issuetest/issuetest_test_test.TestIssue24210\n\tpkg/executor/test/issuetest/executor_issue_test.go:59\ntesting.tRunner\n\tGOROOT/src/testing/testing.go:1595\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1650"] [session="{\n  \"currDBName\": \"test\",\n  \"id\": 1,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": null\n}"]
[2023/12/25 03:46:07.788 +00:00] [INFO] [tidb.go:286] ["rollbackTxn called due to ddl/autocommit failure"]
[2023/12/25 03:46:07.788 +00:00] [WARN] [session.go:2240] ["run statement failed"] [schemaVersion=50] [error="mock SelectionExec.baseExecutor.Open returned error"] [errorVerbose="mock SelectionExec.baseExecutor.Open returned error\ngithub.com/pingcap/tidb/pkg/executor.(*SelectionExec).Open\n\tpkg/executor/executor.go:1550\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Open\n\tpkg/executor/internal/exec/executor.go:291\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).openExecutor\n\tpkg/executor/adapter.go:1238\ngithub.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec\n\tpkg/executor/adapter.go:566\ngithub.com/pingcap/tidb/pkg/session.runStmt\n\tpkg/session/session.go:2386\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\tpkg/session/session.go:2228\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext\n\tpkg/testkit/testkit.go:364\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).Exec\n\tpkg/testkit/testkit.go:337\ngithub.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecToErr\n\tpkg/testkit/testkit.go:410\npkg/executor/test/issuetest/issuetest_test_test.TestIssue24210\n\tpkg/executor/test/issuetest/executor_issue_test.go:65\ntesting.tRunner\n\tGOROOT/src/testing/testing.go:1595\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1650"] [session="{\n  \"currDBName\": \"test\",\n  \"id\": 1,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": null\n}"] 
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #49753

Problem Summary:

```
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=loadPrivilegeInLoop]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=topNSlowQueryLoop]
[INFO] [mock.go:105] ["owner manager is canceled"] [category=ddl] [ID=4d0f1deb-2066-4e6f-b6bd-b7cd26a25837] [ownerKey=/tidb/bindinfo/owner]
[INFO] [domain.go:1346] ["closestReplicaReadCheckLoop exited."]
[INFO] [domain.go:1866] ["globalBindHandleWorkerLoop exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=closestReplicaReadCheckLoop]
[INFO] [domain.go:725] ["globalConfigSyncerKeeper exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=globalBindHandleWorkerLoop]
[INFO] [domain.go:2106] ["dumpFileGcChecker exited."]
[INFO] [domain.go:699] ["infoSyncerKeeper exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=loadSigningCertLoop]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=dumpFileGcChecker]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=runawayWatchSyncLoop]
[INFO] [stats_syncload.go:187] ["SubLoadWorker exited."]
[INFO] [stats_syncload.go:187] ["SubLoadWorker exited."]
[INFO] [stats_syncload.go:187] ["SubLoadWorker exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=runawayRecordFlushLoop]
[INFO] [stats_syncload.go:187] ["SubLoadWorker exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=mdlCheckLoop]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=infoSyncerKeeper]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=topologySyncerKeeper]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=globalConfigSyncerKeeper]
[INFO] [domain.go:892] ["loadSchemaInLoop exited."]
[INFO] [domain.go:1727] ["LoadSysVarCacheLoop exited."]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=loadSchemaInLoop]
[INFO] [mock.go:105] ["owner manager is canceled"] [category=ddl] [ID=4d0f1deb-2066-4e6f-b6bd-b7cd26a25837] [ownerKey=/tidb/stats/owner]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=LoadSysVarCacheLoop]
[INFO] [wait_group_wrapper.go:140] ["background process exited"] [source=domain] [process=quitStatsOwner]
[INFO] [stats_syncload.go:187] ["SubLoadWorker exited."]
[WARN] [session.go:900] ["can not retry txn"] [label=internal] [error="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV"] [errorVerbose="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).checkSchemaValid
    external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1791
github.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).execute
    external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1616
github.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).Commit
    external/com_github_tikv_client_go_v2/txnkv/transaction/txn.go:508
github.com/pingcap/tidb/pkg/store/driver/txn.(*tikvTxn).Commit
    pkg/store/driver/txn/txn_driver.go:99
github.com/pingcap/tidb/pkg/session.(*LazyTxn).Commit
    pkg/session/txn.go:428
github.com/pingcap/tidb/pkg/session.(*session).commitTxnWithTemporaryData
    pkg/session/session.go:740
github.com/pingcap/tidb/pkg/session.(*session).doCommit
    pkg/session/session.go:621
github.com/pingcap/tidb/pkg/session.(*session).doCommitWithRetry
    pkg/session/session.go:874
github.com/pingcap/tidb/pkg/session.(*session).CommitTxn
    pkg/session/session.go:1001
github.com/pingcap/tidb/pkg/session.autoCommitAfterStmt
    pkg/session/tidb.go:298
github.com/pingcap/tidb/pkg/session.finishStmt
    pkg/session/tidb.go:260
github.com/pingcap/tidb/pkg/session.runStmt
    pkg/session/session.go:2405
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt
    pkg/session/session.go:2228
github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal
    pkg/session/session.go:1600
github.com/pingcap/tidb/pkg/disttask/framework/storage.ExecSQL
    pkg/disttask/framework/storage/task_table.go:119
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).executeSQLWithNewSession.func1
    pkg/disttask/framework/storage/task_table.go:214
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewSession
    pkg/disttask/framework/storage/task_table.go:179
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).executeSQLWithNewSession
    pkg/disttask/framework/storage/task_table.go:213
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).StartManager
    pkg/disttask/framework/storage/task_table.go:702
github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).initMeta
    pkg/disttask/framework/taskexecutor/manager.go:111
github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).Start
    pkg/disttask/framework/taskexecutor/manager.go:129
github.com/pingcap/tidb/pkg/domain.(*Domain).distTaskFrameworkLoop
    pkg/domain/domain.go:1497
github.com/pingcap/tidb/pkg/domain.(*Domain).InitDistTaskLoop.func1
    pkg/domain/domain.go:1491
github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1
    pkg/util/wait_group_wrapper.go:99
...
```

`initMeta` should not retry if the context is canceled. Otherwise, it will keep retry until timeout in the scenario of `domain.Close()`.

### What changed and how does it work?

Check if context is done before retrying.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by ywqzzy — APPROVED** [review]

File: pkg/disttask/framework/scheduler/scheduler.go [hunk 1]
```diff
@@ -491,6 +491,12 @@ func (s *BaseScheduler) updateTask(taskState proto.TaskState, newSubTasks []*pro
 		if err == nil || !retryable {
 			break
 		}
+		select {
+		case <-s.ctx.Done():
```
Comment (lance6716) [inline pkg/disttask/framework/scheduler/scheduler.go:495]: if err := s.ctx.Err(); err != nil {
  return err
}

Comment (lance6716) [reply pkg/disttask/framework/scheduler/scheduler.go:495]: also for below code

Comment (tangenta) [reply pkg/disttask/framework/scheduler/scheduler.go:495]: d0a5a2c8bbbc4c80cd88906ec4d0d8f792f91fc8

Comment (lance6716) [reply pkg/disttask/framework/scheduler/scheduler.go:495]: no I mean the whole select can be replaced

**Review by lance6716 — APPROVED** [review]
