### PR TITLE
txn: check `max_execution_time` when locking keys

### LINKED ISSUE #62960: `max_execution_time` does not affect `SELECT FOR UPDATE` query
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In a pessimistic txn, use `SELECT FOR UPDATE` with `max_execution_time`, and it blocks on waiting for lock.

### 2. What did you expect to see? (Required)

Timeout due to `max_execution_time`

### 3. What did you see instead (Required)

Timeout at 50s, which is the default lock wait timeout.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #62960 

Problem Summary:

### What changed and how does it work?

Check `max_execution_time` when locking keys.
Depend on https://github.com/tikv/client-go/pull/1731

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that `max_execution_duration` didn't affect SELECT FOR UPDATE queries.
```

### CODE REVIEW

File: pkg/executor/select.go [hunk 1]
```diff
@@ -291,6 +291,23 @@ func (e *SelectLockExec) Next(ctx context.Context, req *chunk.Chunk) error {
 		lockWaitTime = int64(e.Lock.WaitSec) * 1000
 	}
 
+	// Check max_execution_time constraint for SELECT FOR UPDATE/SHARE
+	// max_execution_time only applies to SELECT statements
+	sessVars := e.Ctx().GetSessionVars()
```
Comment (cfzjywxk) [inline pkg/executor/select.go]: Is it possible to merge the pre-check into a function so it could be used for both point/batch point get and the apater.

File: tests/realtikvtest/pessimistictest/pessimistic_test.go [hunk 2]
```diff
@@ -3761,3 +3761,49 @@ func TestForShareWithPromotionPlanCache(t *testing.T) {
...
+
+	// Check if it's a max execution time exceeded error
+	// Error 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
+	require.True(t, strings.Contains(err.Error(), "Query execution was interrupted") ||
+		strings.Contains(err.Error(), "maximum statement execution time exceeded") ||
+		err.Error() == "context deadline exceeded",
+		"Expected max_execution_time error, but got: %v", err)
+
+	require.Greater(t, elapsed, 2340*time.Millisecond, "Query should take more than 2 seconds due to max_execution_time, but took %v", elapsed)
+	require.Less(t, elapsed, 4*time.Second, "Query should timeout within 4 seconds due to max_execution_time, but took %v", elapsed)
```
Comment (cfzjywxk) [inline tests/realtikvtest/pessimistictest/pessimistic_test.go]: This could be unstable in high pressure test environment, perhaps checking some flags like `max_execution_timeout canceld etc`?

Comment (ekexium) [reply tests/realtikvtest/pessimistictest/pessimistic_test.go]: If we don't want to test the time, then the error message check is enough. I've removed these lines.

**Review by cfzjywxk — APPROVED** [review]
LGTM

File: pkg/executor/adapter.go [hunk 3]
```diff
@@ -638,8 +653,8 @@ func (a *ExecStmt) Exec(ctx context.Context) (_ sqlexec.RecordSet, err error) {
 		if a.Ctx.GetSessionVars().StmtCtx.StmtType == "" {
 			a.Ctx.GetSessionVars().StmtCtx.StmtType = stmtctx.GetStmtLabel(ctx, a.StmtNode)
 		}
-		// Since maxExecutionTime is used only for query statement, here we limit it affect scope.
-		if !a.IsReadOnly(a.Ctx.GetSessionVars()) {
+		// Since maxExecutionTime is used only for SELECT statements, here we limit its scope.
+		if !isSelectStmt(a.StmtNode, a.Ctx.GetSessionVars()) {
```
Comment (MyonKeminta) [inline pkg/executor/adapter.go]: Is this change to include `select ... for update` into the scope affected by max exec time?
And, is `stmtCtx.InSelectStmt` available here? If so, perhaps the `isSelectStmt` function is not necessary? I'm afraid that too many this kind of judgement logic may easily introduce mistakes, either now or in the future.

Comment (ekexium) [reply pkg/executor/adapter.go]: > Is this change to include select ... for update into the scope affected by max exec time?

Yes.

> is stmtCtx.InSelectStmt available here?

I remember I was mimicing the way `InSelectStmt` is set, but I don't remember why I didn't use it directly... Seems it should be already set at this place.

Comment (ekexium) [reply pkg/executor/adapter.go]: And we double checked this in `checkMaxExecutionTimeExceeded`. I've refactored to use `InSelectStmt`.

File: tests/realtikvtest/pessimistictest/pessimistic_test.go [hunk 4]
```diff
@@ -3761,3 +3761,42 @@ func TestForShareWithPromotionPlanCache(t *testing.T) {
...
+
+	// Transaction 1: Hold the lock
+	tk1.MustExec("begin pessimistic")
+	tk1.MustQuery("select * from test_lock where id = 1 for update").Check(testkit.Rows("1 100"))
+
+	// Transaction 2: Try to acquire lock with max_execution_time
+	tk2.MustExec("begin pessimistic")
+	tk2.MustExec("set max_execution_time = 2345")
+
+	// Also test with hint
```
Comment (MyonKeminta) [inline tests/realtikvtest/pessimistictest/pessimistic_test.go]: What does this comment mean? Is there any test cases you were going to write but missing?

File: tests/realtikvtest/pessimistictest/pessimistic_test.go [hunk 5]
```diff
@@ -3761,3 +3761,42 @@ func TestForShareWithPromotionPlanCache(t *testing.T) {
...
+	err := tk2.ExecToErr("select * from test_lock where id = 1 for update")
```
Comment (MyonKeminta) [inline tests/realtikvtest/pessimistictest/pessimistic_test.go]: Can we also check some different formats (e.g., with parentheses around the statement), and also check that DMLs are not affected?

File: tests/realtikvtest/pessimistictest/pessimistic_test.go (hunk 4 above)
Comment (ekexium) [reply tests/realtikvtest/pessimistictest/pessimistic_test.go]: Sorry. AI wrote a unnecessary case which was deleted by me.

**Review by MyonKeminta — APPROVED** [review]
