### PR TITLE
store: forbid collecting info if enable-collect-execution-info disabled (#31282)

### LINKED ISSUE #31038: Runtime stats collection shouldn't collect stats if enable-collect-execution-info isn't enabled.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start a cluster and running a workload with setting `enable-collect-execution-info` as false. Scrape the heap profile on tidb-server and we can see the following case:

image

If we try to use `list` to see the detail in function, we can find that many little memory objects make consuming lots of memory due to collecting stats info event if we disabled it.

image

image

### 2. What did you expect to see? (Required)

There shouldn't exist so much memory consuming.

### 3. What did you see instead (Required)

As above said

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #31282 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/31409
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/31409:release-5.3-2bbeebd0d46a
```

---

Signed-off-by: yisaer <disxiaofei@163.com>

### What problem does this PR solve?

Issue Number: close #31038 

### What is changed and how it works?

forbid collecting info if enable-collect-execution-info disabled

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

File: executor/executor_test.go [hunk 1]
```diff
@@ -9384,3 +9384,226 @@ func (s *testSerialSuite) TestIssue28650(c *C) {
 		}()
 	}
 }
+<<<<<<< HEAD
+=======
```
Comment (longfangsong) [inline executor/executor_test.go:9388]:
```suggestion
```

File: executor/executor_test.go [hunk 2]
```diff
@@ -9384,3 +9384,226 @@ func (s *testSerialSuite) TestIssue28650(c *C) {
...
+	})
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t123")
+	tk.MustExec("create table t123 (id int);")
+	failpoint.Enable("github.com/pingcap/tidb/store/copr/disable-collect-execution", `return(true)`)
+	tk.MustQuery("select * from t123;")
+	failpoint.Disable("github.com/pingcap/tidb/store/copr/disable-collect-execution")
+}
+>>>>>>> 2bbeebd0d... store: forbid collecting info if enable-collect-execution-info disabled (#31282)
```
Comment (longfangsong) [inline executor/executor_test.go:9609]:
```suggestion
```

**Review by longfangsong — APPROVED** [review]
