### PR TITLE
backup/pitr_coll: use target client of S3

### LINKED ISSUE #59043: log_backup: copy object uses wrong client making impossible to copy cross-region
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Start Log Backup and cluster at region A.
2. Restore from AWS Region B.  (Not the best practice, but anyway...)

### 2. What did you expect to see? (Required)
Restore should success.

### 3. What did you see instead (Required)
Restore failed with:
```
BucketRegionError: incorrect region, the bucket is not in 'us-east-2' region at endpoint '', bucket is in 'us-west-2' region
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

Issue Number: close #59043

Problem Summary:

We used the wrong client to copy object.

### What changed and how does it work?

Used the rightly configured client to copy object.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
With the new client, now it returns no more `BucketRegionError`.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/storage/s3.go [hunk 1]
```diff
@@ -110,9 +110,8 @@ func (rs *S3Storage) CopyFrom(ctx context.Context, e ExternalStorage, spec CopyS
 		Key:        aws.String(rs.options.Prefix + spec.To),
 	}
 
-	// NOTE: Maybe check whether the Go SDK will handle 200 OK errors.
-	// https://repost.aws/knowledge-center/s3-resolve-200-internalerror
```
Comment (YuJuncen) [inline br/pkg/storage/s3.go:114]: This was removed because I have checked the document and it reads:

> If you call this API operation directly, make sure to design your application to parse the content of the response and handle it appropriately. If you use AWS SDKs, SDKs handle this condition. The SDKs detect the embedded error and apply error handling per your configuration settings (including automatically retrying the request as appropriate). If the condition persists, the SDKs throw an exception (or, for the SDKs that don't use exceptions, they return an error).

**Review by BornChanger — APPROVED** [review]

**Review by RidRisR — APPROVED** [review]
