### PR TITLE
expression, planner: fix decimal results for aggregate functions

### LINKED ISSUE #19426: `select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t` returns wrong decimal
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` sql
create table t(a int primary key, b int);
insert into t values (1, 11), (4, 44), (2, 22), (3, 33);
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                   110 |
+-------------------------------------------------------+
1 row in set (0.01 sec)
```

### 2. What did you expect to see? (Required)

``` sql
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                 110.0 |
+-------------------------------------------------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)
``` sql
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                   110 |
+-------------------------------------------------------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #19426, fix PR #19592  

Problem Summary:

Execute

```sql
create table t(a int primary key, b int);
insert into t values (1, 11), (4, 44), (2, 22), (3, 33);
```

Obtained

``` sql
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                   110 |
+-------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select group_concat(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+----------------------------------------------------------------+
| group_concat(case when a <= 0 or a > 1000 then 0.0 else b end) |
+----------------------------------------------------------------+
| 11,22,33,44                                                    |
+----------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select distinct case when a <= 0 or a > 1000 then 0.0 else b end from t;
+--------------------------------------------------+
| case when a <= 0 or a > 1000 then 0.0 else b end |
+--------------------------------------------------+
|                                               11 |
|                                               22 |
|                                               33 |
|                                               44 |
+--------------------------------------------------+
4 rows in set (0.00 sec)
```

Expect

``` sql
mysql> select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+-------------------------------------------------------+
| sum(case when a <= 0 or a > 1000 then 0.0 else b end) |
+-------------------------------------------------------+
|                                                 110.0 |
+-------------------------------------------------------+
1 row in set (0.00 sec)

mysql>  select group_concat(case when a <= 0 or a > 1000 then 0.0 else b end) from t;
+----------------------------------------------------------------+
| group_concat(case when a <= 0 or a > 1000 then 0.0 else b end) |
+----------------------------------------------------------------+
| 11.0,22.0,33.0,44.0                                            |
+----------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select distinct case when a <= 0 or a > 1000 then 0.0 else b end from t;
+--------------------------------------------------+
| case when a <= 0 or a > 1000 then 0.0 else b end |
+--------------------------------------------------+
|                                             11.0 |
|                                             22.0 |
|                                             33.0 |
|                                             44.0 |
+--------------------------------------------------+
4 rows in set (0.00 sec)
```

### What is changed and how it works?

- wrap `cast as decimal` for arguments of `group_concat` to preserve fraction part digits of the results.
- round the decimal final result in `AppendFinalResult2Chunk` to the argument's precision.

### Related changes

- Need to cherry-pick to the release branch 3.0, 4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
   - Consumes more CPU
   - Consumes more MEM

### Release note 

- fix the fraction part of decimal results for aggregate functions

### CODE REVIEW

**Comment by dyzsr** [comment]
@wjhuang2016 PTAL

**Comment by dyzsr** [comment]
PTAL @wjhuang2016

File: expression/aggregation/base_func.go [hunk 1]
```diff
@@ -305,6 +305,24 @@ var noNeedCastAggFuncs = map[string]struct{}{
 	ast.AggFuncJsonObjectAgg:       {},
 }
 
+// We need to wrap cast as decimal upon these functions,
+// since we need to keep the fraction part of their decimal results
+var needCastAsDecimalAggFuncs = map[string]struct{}{
```
Comment (winoros) [inline expression/aggregation/base_func.go:310]: Will other agg func have the same cast needs?

Comment (dyzsr) [reply expression/aggregation/base_func.go:310]: I think `group_conat` is the only one.

File: expression/aggregation/base_func.go [hunk 2]
```diff
@@ -305,6 +305,16 @@ var noNeedCastAggFuncs = map[string]struct{}{
 	ast.AggFuncJsonObjectAgg:       {},
 }
 
+// WrapCastAsDecimalForAggArgs wraps the args of some specific aggregate functions
+// with a cast as decimal function. See issue #19426
+func (a *baseFuncDesc) WrapCastAsDecimalForAggArgs(ctx sessionctx.Context) {
+	if a.Name == ast.AggFuncGroupConcat {
+		if tp := a.Args[0].GetType(); tp.Tp == mysql.TypeNewDecimal {
+			a.Args[0] = expression.BuildCastFunction(ctx, a.Args[0], tp)
```
Comment (SunRunAway) [inline expression/aggregation/base_func.go:313]: What if the second argument needs to be cast?
```mysql
select group_concat(a, case when a <= 2 or a > 1000 then 0.0 else b end) from t;
```

File: executor/aggfuncs/func_max_min.go [hunk 3]
```diff
@@ -752,6 +754,14 @@ func (e *maxMin4Decimal) AppendFinalResult2Chunk(sctx sessionctx.Context, pr Par
 		chk.AppendNull(e.ordinal)
 		return nil
 	}
+	frac := e.args[0].GetType().Decimal
```
Comment (winoros) [inline executor/aggfuncs/func_max_min.go:757]: The `FieldType` of the `e.args[0]` should be unchanged during execution.
So do we need to set its value every time we evaluate a new row?

Comment (dyzsr) [reply executor/aggfuncs/func_max_min.go:757]: Do you mean we have to call `Round` for each row in `UpdatePartialResult` and `Slide`?

**Review by winoros — COMMENTED** [review]
lgtm

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
