### PR TITLE
ddl: ignore ingest's disk check in the darwin

### LINKED ISSUE #60893: cannot run the ```TestIngestPartitionRowCount``` with high disk usage
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

cannot run the ```TestIngestPartitionRowCount``` with high disk usage

### 3. What did you see instead (Required)

```
[ddl:8256]Check ingest environment failed: no enough space in /var/folders/n1/xjxdkbfd201b5bb23syfgprm0000gn/T/TestIngestPartitionRowCount1084960501/001
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #60893 

Problem Summary:

### What changed and how does it work?

darwin‘s disk is too expensive and we only use it in the development environment. so we ignore the error.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]

File: pkg/ddl/ingest/disk_root.go [hunk 1]
```diff
@@ -169,6 +170,10 @@ func (d *diskRootImpl) PreCheckUsage() error {
 		logutil.DDLIngestLogger().Warn("available disk space is less than 10%, cannot use ingest mode",
 			zap.String("sort path", d.path),
 			zap.String("usage", d.usageInfo()))
+		if runtime.GOOS == "darwin" {
+			// darwin‘s disk is too expensive and we only use it in the development environment. so we ignore the error.
```
Comment (tangenta) [inline pkg/ddl/ingest/disk_root.go:174]:
```suggestion
			// darwin's disk is too expensive and we only use it in the development environment. so we ignore the error.
```

Comment (hawkingrei) [reply pkg/ddl/ingest/disk_root.go]: Thank you

**Review by tangenta — APPROVED** [review]
