### PR TITLE
tests: fix unstable `TestIssue20236` and `TestShowTableRegion`

### LINKED ISSUE #17191: executor: split region test fail randomly
## Bug Report

Please answer these questions before submitting your issue. Thanks!
split region test fail

### 1. Minimal reproduce step (Required)
```
[2020-05-14T03:14:59.584Z] [2020/05/14 11:14:56.902 +08:00] [INFO] [split_region.go:251] ["wait scatter region finished"] [regionID=32]
[2020-05-14T03:14:59.584Z] [2020/05/14 11:14:56.904 +08:00] [INFO] [split_region.go:56] ["split batch regions request"] ["split key count"=1] ["batch count"=1] ["first batch, region ID"=12] ["first split key"=748000000000000030]
[2020-05-14T03:14:59.584Z] [2020/05/14 11:14:56.904 +08:00] [INFO] [split_region.go:153] ["batch split regions complete"] ["batch region ID"=12] ["first at"=748000000000000030] ["first new region left"="{Id:12 StartKey:7480000000000000ff2d5f728000000000ff0013880000000000fa EndKey:7480000000000000ff305f698000000000ff0000010380000000ff000000fa03000000ff0000000000000000fc RegionEpoch:{ConfVer:0 Version:4} Peers:[id:13 store_id:1 ]}"] ["new region count"=1]
[2020-05-14T03:14:59.584Z] [2020/05/14 11:14:56.904 +08:00] [INFO] [split_region.go:205] ["split regions complete"] ["region count"=1] ["region IDs"="[12]"]
[2020-05-14T03:14:59.584Z] 
[2020-05-14T03:14:59.584Z] ----------------------------------------------------------------------
[2020-05-14T03:14:59.584Z] FAIL: executor_test.go:4247: testSplitTable.TestShowTableRegion
[2020-05-14T03:14:59.584Z] 
[2020-05-14T03:14:59.584Z] executor_test.go:4326:
[2020-05-14T03:14:59.584Z]     // Check the region start key.
[2020-05-14T03:14:59.584Z]     c.Assert(rows[0][1], Equals, fmt.Sprintf("t_%d_", tbl.Meta().ID))
[2020-05-14T03:14:59.584Z] ... obtained string = "t_45_5f728000000000001388"
[2020-05-14T03:14:59.584Z] ... expected string = "t_48_"
[2020-05-14T03:14:59.584Z] 
[2020-05-14T03:14:59.584Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [ddl_worker.go:124] ["[ddl] DDL worker closed"] [worker="worker 132, tp add index"] ["take time"=6.688µs]
[2020-05-14T03:14:59.584Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [ddl_worker.go:124] ["[ddl] DDL worker closed"] [worker="worker 131, tp general"] ["take time"=8.458µs]
[2020-05-14T03:14:59.585Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [delete_range.go:130] ["[ddl] closing delRange"]
[2020-05-14T03:14:59.585Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [session_pool.go:85] ["[ddl] closing sessionPool"]
[2020-05-14T03:14:59.585Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [ddl.go:410] ["[ddl] DDL closed"] [ID=1dc8ab82-c34f-48f3-ac70-a59994d1c4c5] ["take time"=109.868µs]
[2020-05-14T03:14:59.585Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [ddl.go:298] ["[ddl] stop DDL"] [ID=1dc8ab82-c34f-48f3-ac70-a59994d1c4c5]
[2020-05-14T03:14:59.585Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [domain.go:415] ["topNSlowQueryLoop exited."]
[2020-05-14T03:14:59.585Z] [2020/05/14 11:14:56.923 +08:00] [INFO] [domain.go:937] ["handleEvolvePlanTasksLoop exited."]
```

### 2. What did you expect to see? (Required)
should be ok
### 3. Affected version (Required)

CI found in [master link](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36317/pipeline)

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #17191

Problem Summary:

- `TestIssue20236`: Wait for the rpc server to be ready. Also cleanup the temporary files even if the test failed.
- `TestShowTableRegion`: Set the session variable `tidb_scatter_region` instead of global variable, because global variable only takes effect after recreated the session.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/cluster_table_test.go [hunk 1]
```diff
@@ -58,8 +62,23 @@ func createRPCServer(t *testing.T, dom *domain.Domain) *grpc.Server {
 
 	config.UpdateGlobal(func(conf *config.Config) {
 		conf.Status.StatusPort = uint(port)
+		conf.AdvertiseAddress = "127.0.0.1"
 	})
 
+	// Wait for server to be ready by attempting to dial
+	addr := fmt.Sprintf("127.0.0.1:%d", port)
```
Comment (lance6716) [inline pkg/executor/cluster_table_test.go]: not sure if this can be directly get from `lis`

File: pkg/executor/cluster_table_test.go [hunk 2]
```diff
@@ -188,6 +207,14 @@ func TestIssue20236(t *testing.T) {
 	srv := createRPCServer(t, dom)
 	defer srv.Stop()
 
+	// Mock cluster info to provide cluster topology
+	statusAddr := fmt.Sprintf("127.0.0.1:%d", config.GetGlobalConfig().Status.StatusPort)
```
Comment (lance6716) [inline pkg/executor/cluster_table_test.go]: ditto

**Review by lance6716 — APPROVED** [review]
rest lgtm

File: pkg/executor/cluster_table_test.go [hunk 3]
```diff
@@ -33,11 +34,15 @@ import (
 	"github.com/pingcap/tidb/pkg/server"
 	"github.com/pingcap/tidb/pkg/session/sessmgr"
 	"github.com/pingcap/tidb/pkg/testkit"
+	"github.com/pingcap/tidb/pkg/testkit/testfailpoint"
 	"github.com/stretchr/testify/require"
 	"google.golang.org/grpc"
 )
 
 func createRPCServer(t *testing.T, dom *domain.Domain) *grpc.Server {
+	restoreCfg := config.RestoreFunc()
```
Comment (D3Hunter) [inline pkg/executor/cluster_table_test.go]:
```suggestion
	restoreCfgFn := config.RestoreFunc()
```

File: pkg/executor/cluster_table_test.go [hunk 4]
```diff
@@ -48,18 +53,36 @@ func createRPCServer(t *testing.T, dom *domain.Domain) *grpc.Server {
...
+	for range 100 {
+		conn, err := net.DialTimeout("tcp", addr, 100*time.Millisecond)
+		if err == nil {
+			conn.Close()
+			lastErr = nil
+			break
+		}
+		lastErr = err
+		time.Sleep(100 * time.Millisecond)
+	}
```
Comment (D3Hunter) [inline pkg/executor/cluster_table_test.go]: maybe change to `require.Eventually`

File: pkg/executor/cluster_table_test.go [hunk 5]
```diff
@@ -188,6 +211,14 @@ func TestIssue20236(t *testing.T) {
 	srv := createRPCServer(t, dom)
 	defer srv.Stop()
 
+	// Mock cluster info to provide cluster topology
+	statusAddr := fmt.Sprintf("127.0.0.1:%d", config.GetGlobalConfig().Status.StatusPort)
+	instances := []string{
+		fmt.Sprintf("tidb,%s,%s,mock-version,mock-githash,1001", statusAddr, statusAddr),
+	}
+	fpExpr := `return("` + strings.Join(instances, ";") + `")`
+	testfailpoint.Enable(t, "github.com/pingcap/tidb/pkg/infoschema/mockClusterInfo", fpExpr)
```
Comment (D3Hunter) [inline pkg/executor/cluster_table_test.go]: is this new failpoint related to the flaky?

Comment (tangenta) [reply pkg/executor/cluster_table_test.go]: It is used for debug, removed
