### PR TITLE
DDL: Reduce the impact on DML when executing partition DDL

### LINKED ISSUE #19913: Reduce the impact on DML when executing partition DDL
### Example

Table schema:
```sql
create table t(id int primary key) 
    partition by hash(id) partitions 4;
```

Conn1:
```sql
begin;
# insert into partition p1.
insert into t values(1);
```

Conn2:
```sql
alter table t truncate partition p0;
```

Conn1:
```sql
commit;
```

Executing the last statement `commit` reports an error:
```
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### Explanation

DDL will make the concurrent transactions fail, as long as the transactions are writing to the same tables.
The tables which the transactions wrote to are recorded in a map. After the schema of a table changes, TiDB will check whether the changed table exists in the map. If it's true, the transaction will fail.

Assuming we are always writing to the newest partition and truncating the oldest partition, the two partitions are always different. But currently, the truncating operations affect the writing operations.

### Solution

Only put the ids of affected partitions in the map if the table is a partitioned table. Thus the map contains both partition ids and table ids. When judging whether to abort a transaction, just compare the ids, regardless of whether they are partition ids or table ids.

## Score

- 300

## Mentor

 * @djshow832

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## SIG Slack Channel

You can join [#sig-ddl](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU) on slack in your spare time to discuss and get help with mentors or others.

## Recommended Skills

* DDL
* Transaction
* Golang

## Learning Materials

* [TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

### PR DESCRIPTION
**Pull request by xiaodong-ji**
### What problem does this PR solve?

Issue Number: close #19913

Problem Summary:
DDL will make the concurrent transactions fail, as long as the transactions are writing to the same partition table.

### What is changed and how it works?

What's Changed: modify updateSchemaVersion and ApplyDiff functions.

### Check List

- Manual test

Table schema:
```
tidb> create table t(id int primary key) 
    ->     partition by hash(id) partitions 4;
Query OK, 0 rows affected (0.00 sec)
```

Conn1:
```
// insert into partition p1.

tidb> begin;
Query OK, 0 rows affected (0.00 sec)

tidb> insert into t values(1);
Query OK, 1 row affected (0.00 sec)
```

Conn2:
```
tidb> alter table t truncate partition p0;
Query OK, 0 rows affected (0.01 sec)
```

Conn1:
```
tidb> commit;
Query OK, 0 rows affected (0.00 sec)
```

Conn2:
```
tidb> select * from t;
+----+
| id |
+----+
|  1 |
+----+
1 row in set (0.00 sec)
```
- Unit test

### Release note

- Reduce the impact on DML when executing partition DDL

### CODE REVIEW

File: infoschema/builder.go [hunk 1]
```diff
@@ -111,9 +111,17 @@ func (b *Builder) ApplyDiff(m *meta.Meta, diff *model.SchemaDiff) ([]int64, erro
 		if err != nil {
 			return nil, errors.Trace(err)
 		}
+		if diff.Type == model.ActionTruncateTablePartition {
+			tblIDs = []int64{}
+			tblIDs = append(tblIDs, newTableID)
```
Comment (djshow832) [inline infoschema/builder.go:116]: Why add the table ID?

Comment (xiaodong-ji) [reply infoschema/builder.go]: I've removed the table ID.

File: infoschema/builder.go [hunk 2]
```diff
@@ -111,9 +111,16 @@ func (b *Builder) ApplyDiff(m *meta.Meta, diff *model.SchemaDiff) ([]int64, erro
 		if err != nil {
 			return nil, errors.Trace(err)
 		}
+		if diff.Type == model.ActionTruncateTablePartition {
```
Comment (AilinKid) [inline infoschema/builder.go:114]: the code is not elegant to put here, how about move it to the `applyCreateTable` and merge it with `appendAffectedIDs`. They are all about modifying the ids.

File: infoschema/builder.go [hunk 3]
```diff
@@ -111,9 +111,16 @@ func (b *Builder) ApplyDiff(m *meta.Meta, diff *model.SchemaDiff) ([]int64, erro
...
+			tblIDs = []int64{}
+		}
 	}
 	if diff.AffectedOpts != nil {
 		for _, opt := range diff.AffectedOpts {
+			if diff.Type == model.ActionTruncateTablePartition {
```
Comment (AilinKid) [inline infoschema/builder.go:120]: better add a comment for the follower readers.

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

File: infoschema/builder.go (hunk 2 above)
Comment (xiaodong-ji) [reply infoschema/builder.go]: ok, done.

File: infoschema/builder.go (hunk 3 above)
Comment (xiaodong-ji) [reply infoschema/builder.go:120]: ok, done.

**Comment by xiaodong-ji** [comment]
PTAL @AilinKid

**Review by djshow832 — COMMENTED** [review]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
@AilinKid

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
