### PR TITLE
planner: LEADING hint works with non-equijoin + outer join | tidb-test=pr/2688 

### LINKED ISSUE #56513: `leading` hint doesn't work with cartesian join + outer join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

For `t1 INNER JOIN t2 ON (non-eq conditions) LEFT JOIN t3 ON (eq conditions)`, we can't use the hint to enforce the join order.

```sql
create table t1(a int, b int, c int);
create table t2(a int, b int, c int);
create table t3(a int, b int, c int);
explain select /*+ leading(t1,t3,t2) */ * from t1 join t2 on (t1.a = t2.a or t1.a = t2.b) left join t3 on t1.a = t3.b;
explain select /*+ leading(t1,t2,t3) */ * from t1 join t2 on (t1.a = t2.a or t1.a = t2.b) left join t3 on t1.a = t3.b;
```

### 2. What did you expect to see? (Required)

The hint should work well in both queries, meaning two execution plans should be different.

### 3. What did you see instead (Required)

```sql
> explain select /*+ leading(t1,t3,t2) */ * from t1 join t2 on (t1.a = t2.a or t1.a = t2.b) left join t3 on t1.a = t3.b;
+----------------------------------+--------------+-----------+---------------+---------------------------------------------------------------------------------------------------+
| id                               | estRows      | task      | access object | operator info                                                                                     |
+----------------------------------+--------------+-----------+---------------+---------------------------------------------------------------------------------------------------+
| Projection_13                    | 124875000.00 | root      |               | test.t1.a, test.t1.b, test.t1.c, test.t2.a, test.t2.b, test.t2.c, test.t3.a, test.t3.b, test.t3.c |
| └─HashJoin_14                    | 124875000.00 | root      |               | CARTESIAN inner join, other cond:or(eq(test.t1.a, test.t2.a), eq(test.t1.a, test.t2.b))           |
|   ├─TableReader_24(Build)        | 10000.00     | root      |               | data:TableFullScan_23                                                                             |
|   │ └─TableFullScan_23           | 10000.00     | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                    |
|   └─HashJoin_16(Probe)           | 12487.50     | root      |               | left outer join, equal:[eq(test.t1.a, test.t3.b)]                                                 |
|     ├─TableReader_22(Build)      | 9990.00      | root      |               | data:Selection_21                                                                                 |
|     │ └─Selection_21             | 9990.00      | cop[tikv] |               | not(isnull(test.t3.b))                                                                            |
|     │   └─TableFullScan_20       | 10000.00     | cop[tikv] | table:t3      | keep order:false, stats:pseudo                                                                    |
|     └─TableReader_19(Probe)      | 10000.00     | root      |               | data:TableFullScan_18                                                                             |
|       └─TableFullScan_18         | 10000.00     | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                    |
+----------------------------------+--------------+-----------+---------------+---------------------------------------------------------------------------------------------------+
10 rows in set, 1 warning (0.002 sec)

> explain select /*+ leading(t1,t2,t3) */ * from t1 join t2 on (t1.a = t2.a or t1.a = t2.b) left join t3 on t1.a = t3.b;
+----------------------------------+--------------+-----------+---------------+---------------------------------------------------------------------------------------------------+
| id                               | estRows      | task      | access object | operator info                                                                                     |
+----------------------------------+--------------+-----------+---------------+---------------------------------------------------------------------------------------------------+
| Projection_12                    | 124875000.00 | root      |               | test.t1.a, test.t1.b, test.t1.c, test.t2.a, test.t2.b, test.t2.c, test.t3.a, test.t3.b, test.t3.c |
| └─HashJoin_13                    | 124875000.00 | root      |               | CARTESIAN inner join, other cond:or(eq(test.t1.a, test.t2.a), eq(test.t1.a, test.t2.b))           |
|   ├─TableReader_23(Build)        | 10000.00     | root      |               | data:TableFullScan_22                                                                             |
|   │ └─TableFullScan_22           | 10000.00     | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                    |
|   └─HashJoin_15(Probe)           | 12487.50     | root      |               | left outer join, equal:[eq(test.t1.a, test.t3.b)]                                                 |
|     ├─TableReader_21(Build)      | 9990.00      | root      |               | data:Selection_20                                                                                 |
|     │ └─Selection_20             | 9990.00      | cop[tikv] |               | not(isnull(test.t3.b))                                                                            |
|     │   └─TableFullScan_19       | 10000.00     | cop[tikv] | table:t3      | keep order:false, stats:pseudo                                                                    |
|     └─TableReader_18(Probe)      | 10000.00     | root      |               | data:TableFullScan_17                                                                             |
|       └─TableFullScan_17         | 10000.00     | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                    |
+----------------------------------+--------------+-----------+---------------+---------------------------------------------------------------------------------------------------+
10 rows in set, 1 warning (0.002 sec)

> show warnings;
+---------+------+------------------------------------------------------------------------+
| Level   | Code | Message                                                                |
+---------+------+------------------------------------------------------------------------+
| Warning | 1815 | leading hint is inapplicable, check if the leading hint table is valid |
+---------+------+------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

### 4. What is your TiDB version? (Required)

From v6.2.0 (when the `leading` hint starts support outer join) until the latest nightly (v8.4.0-alpha-nightly)

### PR DESCRIPTION
**Pull request by fixdb**
### What problem does this PR solve?

Issue Number: close #56513

Problem Summary:

### What changed and how does it work?
Fixes bug where LEADING hint can't work with non-equijoin + outer join.
The leading hint fails to enforce join order when combining a non-equijoin (inner join with OR conditions like t1.a = t2.a OR t1.a = t2.b) with an outer join. The optimizer generates the warning "leading hint is inapplicable" even though the specified join order is valid.

Modified connectJoinNodes to check whether there's a non-equijoin condition in otherConds that connects the two sides before rejecting. Added the helper method hasOtherJoinCondition that verifies if any condition in otherConds references columns from both the left and right plans.

- If there is such a condition, the join is not truly cartesian (it just lacks an equijoin edge), and the leading hint is allowed.
- If there is no such condition, the cartesian join is still rejected as before for safety with outer joins.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fixes bug where LEADING hint can't work with non-equijoin + outer join
```

## Release Notes

* **Improvements**
  * Enhanced query optimizer to safely handle join reordering with non-equality conditions in outer join scenarios, preventing unsafe cartesian joins while preserving correct query semantics.

* **Tests**
  * Added comprehensive test coverage for leading hints and null-extended column handling in complex join scenarios to validate optimizer behavior.

### CODE REVIEW

File: pkg/planner/core/rule_join_reorder.go [hunk 1]
```diff
@@ -535,6 +575,30 @@ func (s *baseSingleGroupJoinOrderSolver) checkConnection(leftPlan, rightPlan bas
 	return
 }
 
+// hasOtherJoinCondition checks whether there are non-equality join conditions
+// connecting the two plans (i.e. conditions referencing columns from both sides).
+// Conditions referencing null-extended columns are excluded since reordering
+// across them can change outer-join semantics.
+func (s *baseSingleGroupJoinOrderSolver) hasOtherJoinCondition(leftPlan, rightPlan base.LogicalPlan) bool {
```
Comment (guo-shaoge) [inline pkg/planner/core/rule_join_reorder.go:582]: the case from the original issue is:
`(t1 inner join t2 P12) left join t3 on P13` (P12 is not an eq cond),

but check the following case and `P12` is just like `t1.c1 = t22.c1`, and `t22` is the null-producing side. looks like this pr cannot handle this case?
`(t1 inner join (t21 left join t22 on xxx) P12) left join t3 on P13`

Comment (fixdb) [reply pkg/planner/core/rule_join_reorder.go:582]: It seems to work for the case you mentioned:
```sql
mysql> explain select /*+ leading(t1,t5,t3) */ * from t1 join (select t2.a,t4.b from t2 left join t4 on t2.a=t4.a ) t5 on (t1.a = t5.a or t1.b=t5.b) left join t3 on t1.a = t3.b;
+---------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------+
| id                              | estRows  | task      | access object | operator info                                                                           |
+---------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------+
| HashJoin_24                     | 15609.38 | root      |               | left outer join, left side:HashJoin_41, equal:[eq(test.t1.a, test.t3.b)]                |
| ├─TableReader_65(Build)         | 9990.00  | root      |               | data:Selection_64                                                                       |
| │ └─Selection_64                | 9990.00  | cop[tikv] |               | not(isnull(test.t3.b))                                                                  |
| │   └─TableFullScan_63          | 10000.00 | cop[tikv] | table:t3      | keep order:false, stats:pseudo                                                          |
| └─HashJoin_41(Probe)            | 12487.50 | root      |               | CARTESIAN inner join, other cond:or(eq(test.t1.a, test.t2.a), eq(test.t1.b, test.t4.b)) |
|   ├─TableReader_43(Build)       | 1.00     | root      |               | data:TableFullScan_42                                                                   |
|   │ └─TableFullScan_42          | 1.00     | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                          |
|   └─HashJoin_56(Probe)          | 12487.50 | root      |               | left outer join, left side:TableReader_58, equal:[eq(test.t2.a, test.t4.a)]             |
|     ├─TableReader_58(Build)     | 10000.00 | root      |               | data:TableFullScan_57                                                                   |
|     │ └─TableFullScan_57        | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                          |
|     └─TableReader_61(Probe)     | 9990.00  | root      |               | data:Selection_60                                                                       |
|       └─Selection_60            | 9990.00  | cop[tikv] |               | not(isnull(test.t4.a))                                                                  |
|         └─TableFullScan_59      | 10000.00 | cop[tikv] | table:t4      | keep order:false, stats:pseudo                                                          |
+---------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------+
13 rows in set (0.00 sec)

mysql> explain select /*+ leading(t1,t3,t5) */ * from t1 join (select t2.a,t4.b from t2 left join t4 on t2.a=t4.a ) t5 on (t1.a = t5.a or t1.b=t5.b) left join t3 on t1.a = t3.b;
+-----------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------+
| id                                | estRows  | task      | access object | operator info                                                                           |
+-----------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------+
| Projection_18                     | 15609.38 | root      |               | test.t1.a, test.t1.b, test.t1.c, test.t2.a, test.t4.b, test.t3.a, test.t3.b, test.t3.c  |
| └─HashJoin_34                     | 15609.38 | root      |               | CARTESIAN inner join, other cond:or(eq(test.t1.a, test.t2.a), eq(test.t1.b, test.t4.b)) |
|   ├─HashJoin_44(Build)            | 1.25     | root      |               | left outer join, left side:TableReader_46, equal:[eq(test.t1.a, test.t3.b)]             |
|   │ ├─TableReader_46(Build)       | 1.00     | root      |               | data:TableFullScan_45                                                                   |
|   │ │ └─TableFullScan_45          | 1.00     | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                          |
|   │ └─TableReader_49(Probe)       | 9990.00  | root      |               | data:Selection_48                                                                       |
|   │   └─Selection_48              | 9990.00  | cop[tikv] |               | not(isnull(test.t3.b))                                                                  |
|   │     └─TableFullScan_47        | 10000.00 | cop[tikv] | table:t3      | keep order:false, stats:pseudo                                                          |
|   └─HashJoin_62(Probe)            | 12487.50 | root      |               | left outer join, left side:TableReader_64, equal:[eq(test.t2.a, test.t4.a)]             |
|     ├─TableReader_64(Build)       | 10000.00 | root      |               | data:TableFullScan_63                                                                   |
|     │ └─TableFullScan_63          | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                          |
|     └─TableReader_67(Probe)       | 9990.00  | root      |               | data:Selection_66                                                                       |
|       └─Selection_66              | 9990.00  | cop[tikv] |               | not(isnull(test.t4.a))                                                                  |
|         └─TableFullScan_65        | 10000.00 | cop[tikv] | table:t4      | keep order:false, stats:pseudo                                                          |
+-----------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------+
14 rows in set (0.00 sec)
```

File: pkg/planner/core/rule_join_reorder.go [hunk 2]
```diff
@@ -535,6 +575,30 @@ func (s *baseSingleGroupJoinOrderSolver) checkConnection(leftPlan, rightPlan bas
...
+	}
+	mergedSchema := expression.MergeSchema(leftPlan.Schema(), rightPlan.Schema())
+	for _, cond := range s.otherConds {
+		if !expression.ExprFromSchema(cond, mergedSchema) {
+			continue
+		}
+		if expression.ExprFromSchema(cond, leftPlan.Schema()) || expression.ExprFromSchema(cond, rightPlan.Schema()) {
+			continue
+		}
+		if s.nullExtendedCols != nil && expression.ExprReferenceSchema(cond, s.nullExtendedCols) {
```
Comment (guo-shaoge) [inline pkg/planner/core/rule_join_reorder.go:594]: IMO this check is meanless, since the null-producing side and preserved side will not be in the same join group at the same time.(check `extractJoinGroup`).
But it doesn't break the correctness, so I'll leave a LGTM here, and I'll sort out everything in the new implementation.
