### PR TITLE
disttask: subtasks rebalance during task execution

### LINKED ISSUE #47298: subtask can't be re-assigned back when tidb node restart
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run import into command, data in s3, and global-sort mode
2. check subtask assigned to different tidb node
3. rolling restart tidb
4. after tidb recoveried, check subtask 

### 2. What did you expect to see? (Required)
runnable subtasks should be assigned to different tidb node
### 3. What did you see instead (Required)
all subtask are in one tidb node
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #48795 close #47298

Problem Summary:
See issue #47298 
### What is changed and how it works?

RebalanceSubtasks process flow:
1.  find out nodes need to clean subtasks.
2. get subtasks for each node before scaling out.
3. group subtasks for each scheduler.
4. prepare subtasks that need to rebalance to other nodes.
5. rebalance subtasks to other nodes.
6. rebalance rest subtasks evenly to liveNodes.
7. update subtasks and do clean up logic.

Behavior:
see ut in rebalance_test.go

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   
  
1. first run on 1 tidb then scale out 1 tidb.
  
image

2.  from 2 tidb to 1 tidb
  
image
image

3.  from 1 tidb to 3 tidb
  
image
image

4. from 3 tidb to 1 tidb
image
image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/dispatcher/dispatcher.go [hunk 1]
```diff
@@ -397,37 +401,114 @@ func (d *BaseDispatcher) replaceDeadNodesIfAny() error {
...
-				n := d.liveNodes[d.rand.Int()%len(d.liveNodes)] //nolint:gosec
-				replaceNodes[nodeID] = disttaskutil.GenerateExecID(n.IP, n.Port)
-				cleanNodes = append(cleanNodes, nodeID)
-			}
+		d.LiveNodes = newInfos
+		// 3. rebalance subtasks.
+		d.LiveNodes, err = d.filterByRole(d.LiveNodes)
+		if err != nil {
+			return err
 		}
```
Comment (ywqzzy) [inline pkg/disttask/framework/dispatcher/dispatcher.go:409]: Useless filter

File: pkg/disttask/framework/dispatcher/dispatcher.go [hunk 2]
```diff
@@ -397,37 +401,114 @@ func (d *BaseDispatcher) replaceDeadNodesIfAny() error {
...
+	}
+
+	averageSubtaskCnt := liveNodeSubtaskCnt / len(d.LiveNodes)
+	for id, v := range subtasksForEachScheduler {
+		if ok := cleanNodeMap[id]; ok {
+			continue
+		}
+		if len(v) > averageSubtaskCnt {
+			for i := 0; i < len(v)-averageSubtaskCnt; i++ {
+				v[i].SchedulerID = scaleOutNodes[lastScaleOutIdx%len(scaleOutNodes)]
```
Comment (D3Hunter) [inline pkg/disttask/framework/dispatcher/dispatcher.go:481]: this loop should consider together with below loop:

suppose we have 5 live nodes, 2 out of it is scale-out nodes, 1 dead node
on live node 1 we have 2 subtasks, on dead node 1 we have 3 subtasks
after this loop, we might have this"
1 subtask on node 1, 1 on some scale-out node

and after below loop, we have
2 1 1 on live nodes
1 0 on scale out nodes

File: pkg/disttask/framework/storage/task_table.go [hunk 3]
```diff
@@ -635,42 +654,25 @@ func (stm *TaskManager) IsSchedulerCanceled(ctx context.Context, execID string,
...
-		return err
-	}
-	i := 0
-	for k := range replaceNodes {
-		if i != 0 {
-			if err := sqlescape.FormatSQL(sql, ","); err != nil {
+	err := stm.WithNewTxn(ctx, func(se sessionctx.Context) error {
+		for _, subtask := range subtasks {
+			_, err := ExecSQL(ctx, se,
+				"update mysql.tidb_background_subtask set exec_id = %? where id = %? and state = %?",
```
Comment (D3Hunter) [inline pkg/disttask/framework/storage/task_table.go:666]: why care about `state`?

maybe we should consider add old exec_id in where clause in case there are 2 owners. ok for now

File: pkg/disttask/framework/dispatcher/dispatcher.go [hunk 4]
```diff
@@ -397,37 +401,163 @@ func (d *BaseDispatcher) replaceDeadNodesIfAny() error {
...
+	cleanNodes := make([]string, 0)
+	deadNodes := make(map[string]bool, 0)
+	for _, node := range d.TaskNodes {
+		if !disttaskutil.MatchServerInfo(d.LiveNodes, node) {
+			deadNodes[node] = true
+			cleanNodes = append(cleanNodes, node)
+		}
+	}
+	// 3. get subtasks for each node before scaling out.
+	subtasks, err := d.taskMgr.GetSubtasksByStepAndState(d.ctx, d.Task.ID, d.Task.Step, proto.TaskStatePending)
```
Comment (ywqzzy) [inline pkg/disttask/framework/dispatcher/dispatcher.go:444]: TODO: revert pending

File: pkg/disttask/framework/storage/task_table.go (hunk 3 above)
Comment (ywqzzy) [reply pkg/disttask/framework/storage/task_table.go:647]: state may changed before updateSubtasks.
The timeline will be like:
1. Dispatcher: getSubtasks
2. scheduler: getSubtasks and mark it as running
3. Dispatcher: rebalance the subtask to other node.

File: pkg/disttask/framework/dispatcher/dispatcher.go [hunk 5]
```diff
@@ -397,37 +401,116 @@ func (d *BaseDispatcher) replaceDeadNodesIfAny() error {
...
+			rebalanceSubtasks = append(rebalanceSubtasks, v[0:len(v)-averageSubtaskCnt]...)
+		}
+	}
+	// 5. skip rebalance.
+	if len(rebalanceSubtasks) == 0 {
+		return nil
+	}
+	// 6.rebalance subtasks to other nodes.
+	rebalanceIdx := 0
+	for k, v := range subtasksOnScheduler {
```
Comment (D3Hunter) [inline pkg/disttask/framework/dispatcher/dispatcher.go:485]: maybe merge this loop with below one, by first generating expected subtask count on live nodes, say `3 3 2`
then, assign subtasks to meet the expectation

ok for now.

**Review by D3Hunter — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM

File: pkg/disttask/framework/dispatcher/dispatcher.go [hunk 6]
```diff
@@ -403,37 +407,116 @@ func (d *BaseDispatcher) replaceDeadNodesIfAny() error {
...
+	rebalanceSubtasks := make([]*proto.Subtask, 0)
+	for k, v := range subtasksOnScheduler {
+		if ok := deadNodesMap[k]; ok {
+			rebalanceSubtasks = append(rebalanceSubtasks, v...)
+			continue
+		}
+		// When no tidb scale-in/out and averageSubtaskCnt*len(d.LiveNodes) < len(subtasks),
+		// no need to send subtask to other nodes.
+		// eg: tidb1 with 3 subtasks, tidb2 with 2 subtasks, subtasks are balanced now.
+		if averageSubtaskCnt*len(d.LiveNodes) < len(subtasks) && len(d.TaskNodes) == len(d.LiveNodes) {
```
Comment (tangenta) [inline pkg/disttask/framework/dispatcher/dispatcher.go:475]: `averageSubtaskCnt*len(d.LiveNodes) < len(subtasks)` seems to be always true?

**Review by tangenta — COMMENTED** [review]
rest lgtm

File: pkg/disttask/framework/dispatcher/dispatcher.go (hunk 6 above)
Comment (ywqzzy) [reply pkg/disttask/framework/dispatcher/dispatcher.go:475]: No, eg:
tidb1: 3 subtasks, tidb2: 3subtasks, tidb3:：2 subtasks, then average = 2, 
average * len(liveNodes) = 6 < 7

**Review by tangenta — APPROVED** [review]
