### PR TITLE
planner: add projection if expand virtual generated column

### LINKED ISSUE #20071: runtime error: index out of range [8] with length 8
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists table_30_utf8_4;
drop table if exists t;
create table t(a int);
insert into t values(1);
create table table_30_utf8_4 (
`pk` int primary key,
`col_int_key_unsigned` int unsigned ,
`col_int_key_signed` int,
`col_float_key_signed` float  ,
`col_float_key_unsigned` float unsigned
) character set utf8 
partition by hash(pk)
partitions 4;

insert ignore into table_30_utf8_4 values (0,91, 10, 14,19.0495);
alter table table_30_utf8_4 add column a int as (col_int_key_signed * 2);


SELECT count(1) AS val FROM table_30_utf8_4 WHERE table_30_utf8_4.col_int_key_unsigned!=table_30_utf8_4.a OR (SELECT count(1) AS val FROM t WHERE table_30_utf8_4.col_float_key_signed!=table_30_utf8_4.col_float_key_unsigned )!=7984764426240273913;
```
### 2. What did you expect to see? (Required)
```
mysql> SELECT count(1) AS val FROM table_30_utf8_4 WHERE table_30_utf8_4.col_int_key_unsigned!=table_30_utf8_4.a OR (SELECT count(1) AS val FROM t WHERE table_30_utf8_4.col_float_key_signed!=table_30_utf8_4.col_float_key_unsigned )!=7984764426240273913;
+-----+
| val |
+-----+
|   1 |
+-----+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```
mysql> SELECT count(1) AS val FROM table_30_utf8_4 WHERE table_30_utf8_4.col_int_key_unsigned!=table_30_utf8_4.a OR (SELECT count(1) AS val FROM t WHERE table_30_utf8_4.col_float_key_signed!=table_30_utf8_4.col_float_key_unsigned )!=7984764426240273913;
ERROR 1105 (HY000): runtime error: index out of range [5] with length 5
```
### 4. What is your TiDB version? (Required)

master and release-4.0

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #20071 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- fix a bug that may cause panic if use partition and virtual generated column.

### CODE REVIEW

File: planner/core/task.go [hunk 1]
```diff
@@ -172,6 +172,14 @@ func (p *basePhysicalPlan) attach2Task(tasks ...task) task {
 }
 
 func (p *PhysicalUnionScan) attach2Task(tasks ...task) task {
+	if pj, ok := tasks[0].plan().(*PhysicalProjection); ok {
+		p.SetChildren(pj.children...)
+		p.stats = tasks[0].plan().statsInfo()
+		rt, _ := tasks[0].(*rootTask)
+		rt.p = pj.children[0]
+		pj.SetChildren(p)
+		return pj.attach2Task(p.basePhysicalPlan.attach2Task(tasks...))
```
Comment (eurekaka) [inline planner/core/task.go:181]: Why do we need to pull up the projection?

File: planner/core/exhaust_physical_plans.go [hunk 2]
```diff
@@ -598,13 +598,24 @@ func (p *LogicalJoin) getIndexJoinByOuterIdx(prop *property.PhysicalProperty, ou
 	}
 	if isUnionScan {
 		// The child of union scan may be union all for partition table.
-		ds, isDataSource = us.Children()[0].(*DataSource)
+		proj, isProj := us.Children()[0].(*LogicalProjection)
+		if isProj {
+			ds, isDataSource = proj.children[0].(*DataSource)
+		} else {
+			ds, isDataSource = us.Children()[0].(*DataSource)
+		}
```
Comment (eurekaka) [inline planner/core/exhaust_physical_plans.go:606]: How are these changes related to this PR?

File: planner/core/task.go [hunk 3]
```diff
@@ -727,7 +737,12 @@ func finishCopTask(ctx sessionctx.Context, task task) task {
 			}
 		}
 		ts := tp.(*PhysicalTableScan)
+		prevColumnLen := len(ts.Columns)
+		prevSchema = ts.schema.Clone()
 		ts.Columns = ExpandVirtualColumn(ts.Columns, ts.schema, ts.Table.Columns)
+		if len(ts.Columns) > prevColumnLen {
+			needExtraProj = true
+		}
```
Comment (eurekaka) [inline planner/core/task.go:745]: Could you add comments to explain why we need an extra projection? How does it help to fix the panic?

**Review by eurekaka — COMMENTED** [review]
Please simplify and add the panic case in the issue as a unit test.

**Review by winoros — COMMENTED** [review]
lgtm

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
