### PR TITLE
expression: fix the length of casting from INT/REAL/DECIMAL/.... to string | tidb-test=pr/2549

### LINKED ISSUE #61350: incompatible with mysql in column-type-info when use cast()
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table testfield (f0 int,f1 decimal(10,2),f2 bigint,f3 datetime,f4 float,f5 double,primary key (f0));
insert into testfield values (1,1.1,1,'20250527',1.1,1.1);
insert into testfield values (2,2.2,2,'20250527',2.2,2.2);

TiDB nightly:
mysql> select cast(f0 as char),cast(f1 as char),cast(f2 as char),cast(f3 as char),cast(f4 as char),cast(f5 as char) from testfield;
Field   1:  `cast(f0 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
Length:     44
Max_length: 1
Decimals:   31
Flags:      

Field   2:  `cast(f1 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
**Length:     5**
Max_length: 4
Decimals:   31
Flags:      

Field   3:  `cast(f2 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
Length:     80
Max_length: 1
Decimals:   31
Flags:      

Field   4:  `cast(f3 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
**Length:     5**
Max_length: 19
Decimals:   31
Flags:      

Field   5:  `cast(f4 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
**Length:     5**
Max_length: 3
Decimals:   31
Flags:      

Field   6:  `cast(f5 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
**Length:     5**
Max_length: 3
Decimals:   31
Flags:      

+------------------+------------------+------------------+---------------------+------------------+------------------+
| cast(f0 as char) | cast(f1 as char) | cast(f2 as char) | cast(f3 as char)    | cast(f4 as char) | cast(f5 as char) |
+------------------+------------------+------------------+---------------------+------------------+------------------+
| 1                | 1.10             | 1                | 2025-05-27 00:00:00 | 1.1              | 1.1              |
| 2                | 2.20             | 2                | 2025-05-27 00:00:00 | 2.2              | 2.2              |
+------------------+------------------+------------------+---------------------+------------------+------------------+
2 rows in set (0.00 sec)

MySQL 8.4.4:
[tidb@k8s-master ~]$ mysql --column-type-info  -u root -p123123 -D test
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.4.4 MySQL Community Server - GPL

Copyright (c) 2000, 2025, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select cast(f0 as char),cast(f1 as char),cast(f2 as char),cast(f3 as char),cast(f4 as char),cast(f5 as char) from testfield;
Field   1:  `cast(f0 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     44
Max_length: 1
Decimals:   31
Flags:      

Field   2:  `cast(f1 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
**Length:     48**
Max_length: 4
Decimals:   31
Flags:      

Field   3:  `cast(f2 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     80
Max_length: 1
Decimals:   31
Flags:      

Field   4:  `cast(f3 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
**Length:     76**
Max_length: 19
Decimals:   31
Flags:      

Field   5:  `cast(f4 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
**Length:     48**
Max_length: 3
Decimals:   31
Flags:      

Field   6:  `cast(f5 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
**Length:     88**
Max_length: 3
Decimals:   31
Flags:      

+------------------+------------------+------------------+---------------------+------------------+------------------+
| cast(f0 as char) | cast(f1 as char) | cast(f2 as char) | cast(f3 as char)    | cast(f4 as char) | cast(f5 as char) |
+------------------+------------------+------------------+---------------------+------------------+------------------+
| 1                | 1.10             | 1                | 2025-05-27 00:00:00 | 1.1              | 1.1              |
| 2                | 2.20             | 2                | 2025-05-27 00:00:00 | 2.2              | 2.2              |
+------------------+------------------+------------------+---------------------+------------------+------------------+
2 rows in set (0.00 sec)

mysql> 

### 2. What did you expect to see? (Required)

Compatible with MySQL when use cast(XXX as varchar), include datetime\float\double\decimal

### 3. What did you see instead (Required)
the values of length in column-type-info incompatible with MySQL when use cast(xxx as varchar)

### 4. What is your TiDB version? (Required)
+--------------------------------------------+
| version()                                  |
+--------------------------------------------+
| 8.0.11-TiDB-v9.0.0-beta.1.pre-803-g7702f73 |
+--------------------------------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #61350 

Problem Summary:

The length returned by TiDB is not compatible with MySQL. Sometimes it's too small so that the client may fail to allocate big enough buffer and cause panic/security issue. This PR modifies the logic of calculating the length, and make it compatible with MySQL for most of the cases.

### What changed and how does it work?

1. Change the logic of calculating length for casting many types to string.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Run the SQLs provided in #61350 and check the results are the same.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that the length returned by `cast` function is not compatible with MySQL.
```

### CODE REVIEW

**Comment by YangKeao** [comment]
Oops. I found it also affects the behavior. For example:

```sql
select binary(123)
```

Will return different values with/without this PR. I should be more careful.

/hold

File: pkg/expression/builtin_cast.go [hunk 1]
```diff
@@ -361,11 +357,125 @@ func (c *castAsStringFunctionClass) getFunction(ctx BuildContext, args []Express
...
 	return sig, nil
 }
 
+func estimateLengthForCastString(retFt, argFt *types.FieldType) (newFlen int, retNewTp byte) {
+	newFlen = retFt.GetFlen()
+	retNewTp = retFt.GetType()
+
+	// Only estimate the length for variable length string types, because different length for fixed
+	// length string types will have different behaviors and may cause compatibility issues.
+	if retFt.GetType() == mysql.TypeString {
```
Comment (YangKeao) [inline pkg/expression/builtin_cast.go:372]: `select binary(123)` will use `cast` to return `TypeString`. However, it's also not compatible with MySQL because MySQL also returns `TypeVarString`. Maybe we should modify it to `TypeVarString` in parser later.

BTW, `binary` function is deprecated by MySQL.

File: pkg/expression/builtin_cast.go [hunk 2]
```diff
@@ -361,11 +357,154 @@ func (c *castAsStringFunctionClass) getFunction(ctx BuildContext, args []Express
 		sig = &builtinCastStringAsStringSig{bf}
 		sig.setPbCode(tipb.ScalarFuncSig_CastStringAsString)
 	default:
-		return nil, errors.Errorf("cannot cast from %s to %s", argTp, "String")
+		return nil, errors.Errorf("cannot cast from %s to %s", argFt.EvalType(), "String")
 	}
 	return sig, nil
 }
 
+func estimateLengthForCastString(retFt, argFt *types.FieldType) (newFlen int, retNewTp byte) {
```
Comment (windtalker) [inline pkg/expression/builtin_cast.go]: maybe rename this function to `adjustRetFtForCastString` and adjust the flen and type of `retFt` inside this function? In this way we can skip some unnecessary `bf.tp.SetFlen/bf.tp.SetType`

Comment (YangKeao) [reply pkg/expression/builtin_cast.go]: Done.

**Review by xhebox — APPROVED** [review]

File: pkg/expression/builtin_cast.go [hunk 3]
```diff
@@ -361,11 +359,156 @@ func (c *castAsStringFunctionClass) getFunction(ctx BuildContext, args []Express
...
+		//
+		// The largest float/double value is around `3.40e38`/`1.79e308`, and the smallest positive float/double value
+		// is around `1.40e-45`/`4.94e-324`. Therefore, we need at least `1 (sign) + 1 (integer) + 1 (dot) + (45 + 39) (decimal) = 87`
+		// for float and `1 (sign) + 1 (integer) + 1 (dot) + (324 + 43) (decimal) = 370` for double.
+		//
+		// Actually, the golang will usually generate a much smaller string. It used ryu algorithm to generate the shortest
+		// decimal representation. It's not necessary to keep all decimals. Ref:
+		// - https://github.com/ulfjack/ryu
+		// - https://dl.acm.org/doi/10.1145/93548.93559
+		// So maybe 48/327 is enough for float/double, but we still set 87/370 for safety.
```
Comment (AilinKid) [inline pkg/expression/builtin_cast.go:444]: nice explaination
