### PR TITLE
ddl: fix duplicate elementID allocation to make sure gc work for partition table

### LINKED ISSUE #33620: delete range of `drop index for partition table` is not correct.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> create table t (id int, c1 int, c2 int, primary key(id), key i1(c1), key i2(c2)) partition by range(id) (partition p0 values less than (6), partition p01 values less than (10) , partition p1 values less than maxvalue);
Query OK, 0 rows affected (0.01 sec)

mysql> alter table t  drop index i1;
Query OK, 0 rows affected (0.02 sec)

mysql> select * from mysql.gc_delete_range_done;
+--------+------------+----------------------------------------+----------------------------------------+--------------------+
| job_id | element_id | start_key                              | end_key                                | ts                 |
+--------+------------+----------------------------------------+----------------------------------------+--------------------+
|    147 |          2 | 74800000000000008f5f698000000000000002 | 74800000000000008f5f698000000000000003 | 432199516397240321 |
+--------+------------+----------------------------------------+----------------------------------------+--------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
3 rows in gc_delete_range_done
### 3. What did you see instead (Required)
only 1 row.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #33620

Problem Summary:
We use partitionID or indexID as elementID sometimes.
When `drop index for partition table`, we use indexID as elementID. So we may miss some deleteRange.

### What is changed and how it works?
Allocate elementID as 1, 2, 3, 4 for a DDL job.
Besides, add a comment to log so that we can debug easier.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix duplicate elementID allocation to make sure gc work for partition table
```

### CODE REVIEW

File: ddl/delete_range.go [hunk 1]
```diff
@@ -238,12 +239,13 @@ func (dr *delRange) doTask(ctx sessionctx.Context, r util.DelRangeTask) error {
 
 // insertJobIntoDeleteRangeTable parses the job into delete-range arguments,
 // and inserts a new record into gc_delete_range table. The primary key is
-// job ID, so we ignore key conflict error.
+// (job ID, element ID), so we ignore key conflict error.
```
Comment (bb7133) [inline ddl/delete_range.go:242]: So the bug exists from day 1 of table partition?

File: ddl/delete_range.go [hunk 2]
```diff
@@ -274,15 +276,16 @@ func insertJobIntoDeleteRangeTable(ctx context.Context, sctx sessionctx.Context,
 			for _, pid := range physicalTableIDs {
 				startKey = tablecodec.EncodeTablePrefix(pid)
 				endKey := tablecodec.EncodeTablePrefix(pid + 1)
-				if err := doInsert(ctx, s, job.ID, pid, startKey, endKey, now); err != nil {
+				if err := doInsert(ctx, s, job.ID, elementID, startKey, endKey, now, fmt.Sprintf("partition table ID is %d", pid)); err != nil {
```
Comment (bb7133) [inline ddl/delete_range.go:279]:
```suggestion
				if err := doInsert(ctx, s, job.ID, elementID, startKey, endKey, now, fmt.Sprintf("partition ID: %d", pid)); err != nil {
```

I don't think 'partition table' is an accurate term, it might confuse the customer...using 'partition ID' is better.

File: ddl/delete_range.go (hunk 1 above)
Comment (wjhuang2016) [reply ddl/delete_range.go:242]: No, it's a long story.

File: ddl/main_test.go [hunk 3]
```diff
@@ -76,23 +75,16 @@ func wrapJobIDExtCallback(oldCallback ddl.Callback) *testDDLJobIDCallback {
 	}
 }
 
-func setupJobIDExtCallback(ctx sessionctx.Context) (jobExt *testDDLJobIDCallback, tearDown func()) {
+func setupJobIDExtCallback(ctx sessionctx.Context) (tearDown func()) {
```
Comment (tangenta) [inline ddl/main_test.go:78]: The `JobExt` callback is not used anymore. We can remove the entire function.

**Review by zimulala — COMMENTED** [review]
Please add some cases like "dropping some indexes on a partition table" and "dropping some columns on a partition table".

**Review by tangenta — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM
