### PR TITLE
expression: fix issue  that results of `unix_timestamp()-unix_timestamp(now())` is wrong and not stable

### LINKED ISSUE #9710: Results of `unix_timestamp()-unix_timestamp(now())` is wrong and not stable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select unix_timestamp()-unix_timestamp(now());
select unix_timestamp()-unix_timestamp(now());
select unix_timestamp()-unix_timestamp(now());
select unix_timestamp()-unix_timestamp(now());
```

2. What did you expect to see?
In Mysql
```
mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                     -1 |
+----------------------------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set (0.00 sec)

mysql> select unix_timestamp()-unix_timestamp(now());
+----------------------------------------+
| unix_timestamp()-unix_timestamp(now()) |
+----------------------------------------+
|                                     -1 |
+----------------------------------------+
1 row in set (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-212-g0681b8125
Git Commit Hash: 0681b8125080045ee0d4747ce61923164c6f2dd1
Git Branch: master
UTC Build Time: 2019-03-14 04:39:19
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve? 
Fix #9710 

In MySQL, `Now()` and `UnixTimestamp()` will truncate the result while they will round the result in TiDB.

These results below from MySQL 5.7 can prove it.
```
mysql> select now(6), now(3), now();
+----------------------------+-------------------------+---------------------+
| now(6)                     | now(3)                  | now()               |
+----------------------------+-------------------------+---------------------+
| 2019-03-25 15:57:56.612966 | 2019-03-25 15:57:56.612 | 2019-03-25 15:57:56 |
+----------------------------+-------------------------+---------------------+

mysql> select unix_timestamp(), unix_timestamp(now(0)), now(0), unix_timestamp(now(3)), now(3), now(6);
+------------------+------------------------+---------------------+------------------------+-------------------------+----------------------------+
| unix_timestamp() | unix_timestamp(now(0)) | now(0)              | unix_timestamp(now(3)) | now(3)                  | now(6)                     |
+------------------+------------------------+---------------------+------------------------+-------------------------+----------------------------+
|       1553503194 |             1553503194 | 2019-03-25 16:39:54 |         1553503194.992 | 2019-03-25 16:39:54.992 | 2019-03-25 16:39:54.992969 |
+------------------+------------------------+---------------------+------------------------+-------------------------+----------------------------+
	
``` 

### What is changed and how it works?
Let `Now()` and `UnixTimestamp()` truncate the result instead of rounding it.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: expression/integration_test.go [hunk 1]
```diff
@@ -4046,3 +4046,11 @@ func (s *testIntegrationSuite) TestIssue9325(c *C) {
 	result = tk.MustQuery("select * from t where a < timestamp'2019-02-16 14:21:00'")
 	result.Check(testkit.Rows("2019-02-16 14:19:59", "2019-02-16 14:20:01"))
 }
+
+func (s *testIntegrationSuite) TestIssue9710(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	for i := 0; i < 40; i++ {
```
Comment (winoros) [inline expression/integration_test.go]: This for loop is used to test whether it truncate the floating part?

Comment (qw4990) [reply expression/integration_test.go]: Yes, but this UT is a bit hard to understand and explain...
So I remove it and use a new approach to test it..

File: expression/builtin_time.go [hunk 2]
```diff
@@ -235,8 +235,14 @@ var (
 	_ builtinFunc = &builtinSubDateDatetimeDecimalSig{}
 )
 
-func convertTimeToMysqlTime(t time.Time, fsp int) (types.Time, error) {
-	tr, err := types.RoundFrac(t, fsp)
+func convertTimeToMysqlTime(t time.Time, fsp int, useTrunc bool) (types.Time, error) {
```
Comment (zz-jason) [inline expression/builtin_time.go]: how about s/useTrunc/types.RoundMode/?

File: executor/executor_test.go [hunk 3]
```diff
@@ -3371,7 +3371,7 @@ func (s *testSuite3) TestCurrentTimestampValueSelection(c *C) {
 	tk.MustQuery("select id from t where t0 = ?", t0).Check(testkit.Rows("1"))
 	tk.MustQuery("select id from t where t1 = ?", t1).Check(testkit.Rows("1"))
 	tk.MustQuery("select id from t where t2 = ?", t2).Check(testkit.Rows("1"))
-	time.Sleep(time.Second / 2)
```
[the remark this answers is not in the document]
Comment (qw4990) [reply executor/executor_test.go]: There are two calls of `now()` around this `sleep()`.
One is used to insert a record `t0=now()` and the other is used to update it `set t0=now()`.
Before this PR, since `now()` rounds the result, so we can assume that these two calls of `now()` must get two time with different seconds.
After this PR, this assumption is broken, so I increase the waiting time to ensure they can get two time with different seconds.

File: expression/builtin_time.go (hunk 2 above)
Comment (qw4990) [reply expression/builtin_time.go]: updated

File: types/time.go [hunk 4]
```diff
@@ -420,6 +420,14 @@ func RoundFrac(t gotime.Time, fsp int) (gotime.Time, error) {
 	return t.Round(gotime.Duration(math.Pow10(9-fsp)) * gotime.Nanosecond), nil
 }
 
+// TruncateFrac truncates fractional seconds precision with new fsp and returns a new one.
+func TruncateFrac(t gotime.Time, fsp int) (gotime.Time, error) {
+	if _, err := CheckFsp(fsp); err != nil {
+		return t, errors.Trace(err)
```
Comment (XuHuaiyu) [inline types/time.go]: return t, err

File: types/time.go [hunk 5]
```diff
@@ -420,6 +420,14 @@ func RoundFrac(t gotime.Time, fsp int) (gotime.Time, error) {
 	return t.Round(gotime.Duration(math.Pow10(9-fsp)) * gotime.Nanosecond), nil
 }
 
+// TruncateFrac truncates fractional seconds precision with new fsp and returns a new one.
```
Comment (XuHuaiyu) [inline types/time.go]: Maybe it's better to add an example here as the `RoundFrac` does?

File: types/time.go (hunk 4 above)
Comment (qw4990) [reply types/time.go]: fixed
