### PR TITLE
*: fix data races in some other tests from TiFlash Cluster Manager

### LINKED ISSUE #31828: DATA RACE in the tiflashDDLTestSuite
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Write at 0x000007dfc500 by goroutine 1957:
  github.com/pingcap/tidb/ddl_test.(*tiflashDDLTestSuite).SetUpSuite()
      /go/tidb/ddl/ddl_tiflash_test.go:94 +0x506
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:625 +0x48
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).runFixture.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799 +0x245
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x12b
Previous read at 0x000007dfc500 by goroutine 82:
  github.com/pingcap/tidb/ddl.(*ddl).PollTiFlashRoutine()
      /go/tidb/ddl/ddl_tiflash_api.go:442 +0x76e
  github.com/pingcap/tidb/ddl.(*ddl).Start·dwrap·16()
      /go/tidb/ddl/ddl.go:408 +0x39
Goroutine 1957 (running) created at:
  github.com/pingcap/check.(*suiteRunner).forkCall()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x5e4
  github.com/pingcap/check.(*suiteRunner).runFunc()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:751 +0x67
  github.com/pingcap/check.(*suiteRunner).runFixture()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:795 +0x45
  github.com/pingcap/check.(*suiteRunner).run()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:695 +0xd8
  github.com/pingcap/check.Run()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x49
  github.com/pingcap/check.RunAll()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:136 +0x1184
  github.com/pingcap/check.TestingT()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x664
  github.com/pingcap/tidb/ddl.TestT()
      /go/tidb/ddl/ddl_test.go:96 +0x311
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Goroutine 82 (running) created at:
  github.com/pingcap/tidb/ddl.(*ddl).Start()
      /go/tidb/ddl/ddl.go:408 +0xee5
  github.com/pingcap/tidb/ddl.testNewDDLAndStart()
      /go/tidb/ddl/ddl_test.go:106 +0x285
  github.com/pingcap/tidb/ddl.(*testDDLSuite).TestPlacementPolicyInUse()
      /go/tidb/ddl/placement_policy_ddl_test.go:63 +0x1ab
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:625 +0x48
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xa54
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x12b
==================
```

### LINKED ISSUE #31829: DATA RACE at the PullTiFlashPdTick
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
 WARNING: DATA RACE
Read at 0x000007dfc508 by goroutine 82:
  github.com/pingcap/tidb/ddl.(*ddl).pollTiFlashReplicaStatus.func1()
      /go/tidb/ddl/ddl_tiflash_api.go:209 +0x91
  github.com/pingcap/tidb/ddl.(*ddl).pollTiFlashReplicaStatus()
      /go/tidb/ddl/ddl_tiflash_api.go:305 +0x7df
  github.com/pingcap/tidb/ddl.(*ddl).PollTiFlashRoutine()
      /go/tidb/ddl/ddl_tiflash_api.go:426 +0x4ec
  github.com/pingcap/tidb/ddl.(*ddl).Start·dwrap·16()
      /go/tidb/ddl/ddl.go:408 +0x39
Previous write at 0x000007dfc508 by goroutine 648:
  github.com/pingcap/tidb/ddl_test.(*tiflashDDLTestSuite).SetPdLoop()
      /go/tidb/ddl/ddl_tiflash_test.go:218 +0x244
  github.com/pingcap/tidb/ddl_test.(*tiflashDDLTestSuite).TestSetPlacementRuleWithGCWorker()
      /go/tidb/ddl/ddl_tiflash_test.go:546 +0x21d
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:625 +0x48
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xa54
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x12b
Goroutine 82 (running) created at:
  github.com/pingcap/tidb/ddl.(*ddl).Start()
      /go/tidb/ddl/ddl.go:408 +0xee5
  github.com/pingcap/tidb/ddl.testNewDDLAndStart()
      /go/tidb/ddl/ddl_test.go:106 +0x285
  github.com/pingcap/tidb/ddl.(*testDDLSuite).TestPlacementPolicyInUse()
      /go/tidb/ddl/placement_policy_ddl_test.go:63 +0x1ab
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:625 +0x48
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xa54
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x12b
Goroutine 648 (running) created at:
  github.com/pingcap/check.(*suiteRunner).forkCall()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x5e4
  github.com/pingcap/check.(*suiteRunner).forkTest()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x164
  github.com/pingcap/check.(*suiteRunner).doRun()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x1fa
  github.com/pingcap/check.(*suiteRunner).run()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0xe5
  github.com/pingcap/check.Run()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x49
  github.com/pingcap/check.RunAll()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:136 +0x1184
  github.com/pingcap/check.TestingT()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x664
  github.com/pingcap/tidb/ddl.TestT()
      /go/tidb/ddl/ddl_test.go:96 +0x311
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47 
```

### PR DESCRIPTION
**Pull request by CalvinNeo**
Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

### What problem does this PR solve?

Issue Number: close #31828 close #31829 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix data races in some other tests from TiFlash Cluster Manager
```

### CODE REVIEW

File: ddl/ddl_tiflash_test.go [hunk 1]
```diff
@@ -91,16 +91,16 @@ func (s *tiflashDDLTestSuite) SetUpSuite(c *C) {
 	s.dom.SetStatsUpdating(true)
 
 	log.Info("Mock stat", zap.Any("infosyncer", s.dom.InfoSyncer()))
-	ddl.PollTiFlashInterval = 1000 * time.Millisecond
-	ddl.PullTiFlashPdTick = 60
+	ddl.PollTiFlashInterval.Store(1000 * time.Millisecond)
+	ddl.PullTiFlashPdTick.Store(60)
```
[the remark this answers is not in the document]
Comment (CalvinNeo) [reply ddl/ddl_tiflash_test.go:95]: I can move them to the beginning. However, these values will be modified in test cases which I think is in a goroutine other than DDL. I think it may also lead to some data race?

File: ddl/ddl_tiflash_test.go [hunk 2]
```diff
@@ -60,6 +60,8 @@ const (
 func (s *tiflashDDLTestSuite) SetUpSuite(c *C) {
 	var err error
 
+	ddl.PollTiFlashInterval.Store(1000 * time.Millisecond)
```
Comment (zimulala) [inline ddl/ddl_tiflash_test.go:63]: `PollTiFlashInterval` is now only set here and `TearDownSuite`, could you remove the atomic way?

Comment (zimulala) [inline ddl/ddl_tiflash_test.go:63]: `PollTiFlashInterval` is now only set here and `TearDownSuite`, could you remove the atomic way?

**Review by xhebox — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]
