### PR TITLE
ddl: fix flaky test TestCancel & fix panic when we failed to get job in delivery2Worker

### LINKED ISSUE #36582: unstable test in the ddl.TestCancel
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2022-07-26T09:15:29.490Z]     testkit.go:310: 
[2022-07-26T09:15:29.490Z]         	Error Trace:	testkit.go:310
[2022-07-26T09:15:29.490Z]         	            				cancel_test.go:327
[2022-07-26T09:15:29.490Z]         	Error:      	An error is expected but got nil.
[2022-07-26T09:15:29.490Z]         	Test:       	TestCancel
[2022-07-26T09:15:29.490Z]         	Messages:   	sql: alter table t_partition add primary key c3_index (c1)
```

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #36582

ref #53246 

Problem Summary:

### What changed and how does it work?
- see https://github.com/pingcap/tidb/issues/36582#issuecomment-2148790415 for the cause of flaky
- when we failed to get job in delivery2Worker, job variable is nil, it cannot be accecssed, it's introduced in this pr https://github.com/pingcap/tidb/pull/53747
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/cancel_test.go [hunk 1]
```diff
@@ -204,6 +206,14 @@ func cancelSuccess(rs *testkit.Result) bool {
 }
 
 func TestCancel(t *testing.T) {
+	var enterCnt, exitCnt atomic.Int32
+	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/ddl/beforeDelivery2Worker", func(job *model.Job) { enterCnt.Add(1) })
+	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/ddl/afterDelivery2Worker", func(job *model.Job) { exitCnt.Add(1) })
+	waitDDLWorkerExisted := func() {
```
Comment (tangenta) [inline pkg/ddl/cancel_test.go:212]:
```suggestion
	waitDDLWorkerExited := func() {
```

**Review by lance6716 — APPROVED** [review]
lgtm after address existing comments

**Review by tangenta — APPROVED** [review]
