### PR TITLE
planner: fix join reorder correctness with conflict detection algorithm

### LINKED ISSUE #67290: implement the CD-C join reorder detection algorithm

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #67290 , ref #63887

Problem Summary:
While TiDB's Join Reorder module has supported both INNER JOIN and OUTER JOIN for a very long time, it continues to suffer from persistent correctness issues. There issues, analyzed over the last three years, basically fall into three categories:
1. Correctness problem:
    1. case-1: Lack of effective validation logic for OUTER JOIN reordering: The current detection logic for OUTER JOINs is simple (it prevents reordering the null-producing side). This leads to implementations where the semantics after reordering deviate from the original SQL.
    2. case-2: Logical errors in splitting and migrating OUTER JOIN conditions: Numerous bugs stem from incorrectly splitting OUTER JOIN conditions or moving them onto invalid join operators, resulting in incorrect query results. I'll show you some specific examples below.
2. Performance problem:
    1. case-1: Suboptimal plans caused by excluding Cross Products and "other conditions" when connecting subgraphs: We have already one fix for this problem, which is found in wetech. And this fix only handle INNER JOIN, and Non INNER JOIN still have this problem.

Value of the new design:
- **Correctness**: The CD-C algorithm resolves remaining correctness issues without
  reducing the search space. Previously addressed edge cases can now be covered in a
  unified manner, eliminating the current mess of fragmented, case-by-case special logic.
- **Extensibility**: CD-C elegantly handles validity checks for all join types, providing
  a solid foundation for future development. It is a well-proven algorithm adopted by
  many production systems as their default join

The core idea of the new implementation is described in the comment in `conflict_detector.go`, you can get the overall idea of CD-C and its workflow.

### What changed and how does it work?
This PR introduces the new CD-C implementation behind a **failpoint gate**
(`enableCDCJoinReorder`), so no existing behavior is changed. The new code path
will be enabled by default in a follow-up PR.

**New files:**
- `pkg/planner/core/joinorder/conflict_detector.go`: Core CD-C implementation
  including `ConflictDetector`, edge/rule structures, TES computation, conflict rule
  generation, and the assoc/l-asscom/r-asscom rule tables for all join type pairs.
- `pkg/planner/core/joinorder/join_order.go`: Entry point (`Optimize()`), join group
  extraction (`extractJoinGroup`), greedy join ordering algorithm
  (`greedyConnectJoinNodes`), and leading hint support.

**Modified files:**
- `pkg/planner/core/rule_join_reorder.go`: Added failpoint to route to the new
  `joinorder.Optimize()` when enabled.
- `pkg/planner/core/base/plan_base.go`: Added `init()` assertion to ensure `JoinType`
  enum values stay stable (they are used as indices in the rule tables).

**Test files:**
- `pkg/planner/core/casetest/rule/rule_cdc_join_reorder_test.go`: New test covering
  19 SQL cases across all supported join type combinations (INNER, LEFT OUTER,
  RIGHT OUTER), verifying both EXPLAIN plans and query results.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: fix join reorder correctness with conflict detection algorithm
```

### CODE REVIEW

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 1]
```diff
@@ -0,0 +1,552 @@
...
+
+type edge struct {
+	// No need to store the original join operator,
+	// because we may generate a new join operator, so only join conditions are enough.
+	joinType base.JoinType
+	eqConds  []*expression.ScalarFunction
+	// It could be otherCond, leftCond or rightCond.
+	nonEQConds expression.CNFExprs
+
+	tes   BitSet
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: There's an imported bitset

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 2]
```diff
@@ -0,0 +1,552 @@
...
+	join.SetChildren(left, right)
+	join.SetSchema(expression.MergeSchema(left.Schema(), right.Schema()))
+	join.SetChildren(left, right)
+	return join, nil
+}
+
+// 0: rule doesn't apply
+// 1: rule applies
+// 2: rule applies when null-rejective holds
+type ruleTableEntry int
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go:817]: Why it's not bool

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 3]
```diff
@@ -0,0 +1,552 @@
...
+	rule := &rule{from: child.leftVertexes}
+	if child.rightVertexes.HasIntersect(child.tes) {
+		rule.to = child.rightVertexes.Intersect(child.tes)
+	} else {
+		rule.to = child.rightVertexes
+	}
+	return rule
+}
+
+func (d *ConflictDetector) calcTES(conds []base.Expression) BitSet {
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: add comments

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 4]
```diff
@@ -0,0 +1,552 @@
...
+	}
+	return join, nil
+}
+
+func makeInnerJoin(ctx base.PlanContext, checkResult *CheckConnectionResult, existingJoin *logicalop.LogicalJoin) (*logicalop.LogicalJoin, error) {
+	if existingJoin != nil {
+		// Append selections to existing join
+		selection := logicalop.LogicalSelection{
+			Conditions: []expression.Expression{}, // gjt todo reserve space
+		}
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: When will we enter this? Why is it not in `makeNonInnerJoin`?

File: pkg/planner/core/base/plan_base.go [hunk 5]
```diff
@@ -298,6 +298,7 @@ func GetGEAndLogicalOp[T LogicalPlan](super LogicalPlan) (ge GroupExpression, lo
 // JoinType contains CrossJoin, InnerJoin, LeftOuterJoin, RightOuterJoin, SemiJoin, AntiJoin.
 type JoinType int
 
+// NOTE: keep the order and value unchanged, because they are used in conflict_detector.go!!!
```
Comment (winoros) [inline pkg/planner/core/base/plan_base.go]: Add an `intest.Assert` instead.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 6]
```diff
@@ -0,0 +1,780 @@
...
+type edge struct {
+	idx uint64
+	// No need to store the original join operator,
+	// because we may generate a new join operator, so only join conditions are enough.
+	joinType base.JoinType
+	eqConds  []*expression.ScalarFunction
+	// It could be otherCond, leftCond or rightCond.
+	nonEQConds expression.CNFExprs
+
+	tes   intset.FastIntSet
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: use the imported bitset instead.

FastIntSet is used for sparse case.

File: pkg/planner/core/joinorder/join_order.go [hunk 7]
```diff
@@ -0,0 +1,775 @@
...
+			curJoinIdx++
+		} else {
+			nodes[curJoinIdx] = bestNode
+			nodes = append(nodes[:bestIdx], nodes[bestIdx+1:]...)
+		}
+	}
+	return nodes, nil
+}
+
+// TODO add example
```
Comment (winoros) [inline pkg/planner/core/joinorder/join_order.go]: remember to modify this comment

File: pkg/executor/test/indexmergereadtest/index_merge_reader_test.go [hunk 8]
```diff
@@ -228,31 +228,30 @@ func TestPessimisticLockOnPartitionForIndexMerge(t *testing.T) {
 			where t1.c1 < 10 or t1.c2 < 10 for update`).Check(testkit.Rows(
 		"Projection 16635.64 root  test.t1.c1",
 		"└─SelectLock 16635.64 root  for update 0",
-		"  └─Projection 16635.64 root  test.t1.c1, test.t1._tidb_rowid, test.t1._tidb_tid, test.t2._tidb_rowid",
```
Comment (winoros) [inline pkg/executor/test/indexmergereadtest/index_merge_reader_test.go:231]: Why did this test change? Is this expected?

File: tests/integrationtest/r/planner/core/casetest/rule/rule_join_reorder.result [hunk 9]
```diff
@@ -1956,7 +1950,7 @@ HashJoin	root		CARTESIAN inner join
         └─Selection	cop[tikv]		not(isnull(planner__core__casetest__rule__rule_join_reorder.t8.a))
           └─TableFullScan	cop[tikv]	table:t8	keep order:false, stats:pseudo
 Level	Code	Message
-Warning	1815	We can only use one leading hint at most, when multiple leading hints are used, all leading hints will be invalid
```
Comment (winoros) [inline tests/integrationtest/r/planner/core/casetest/rule/rule_join_reorder.result]: Is this change expected?

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 6 above)
Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go]: `go.mod: github.com/bits-and-blooms/bitset v1.14.3`

Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]:
```
goos: darwin
goarch: arm64
pkg: github.com/pingcap/tidb/pkg/planner/core/joinorder
cpu: Apple M2 Pro
BenchmarkJoinOrderConflictDetectorOps/fastintset/conflict/n16_e32-10         	 2033569	       591.9 ns/op
BenchmarkJoinOrderConflictDetectorOps/bitset/conflict/n16_e32-10             	  352449	      3336 ns/op
BenchmarkJoinOrderConflictDetectorOps/fastintset/conflict/n32_e64-10         	 1000000	      1183 ns/op
BenchmarkJoinOrderConflictDetectorOps/bitset/conflict/n32_e64-10             	  178701	      6671 ns/op
BenchmarkJoinOrderConflictDetectorOps/fastintset/conflict/n64_e128-10        	  504903	      2373 ns/op
BenchmarkJoinOrderConflictDetectorOps/bitset/conflict/n64_e128-10            	   89239	     13976 ns/op
BenchmarkJoinOrderConflictDetectorOps/fastintset/conflict/n128_e256-10       	   51154	     23590 ns/op
BenchmarkJoinOrderConflictDetectorOps/bitset/conflict/n128_e256-10           	   38972	     31334 ns/op
PASS
```
fastintset is much faster than bitset

File: pkg/planner/core/rule_join_reorder.go [hunk 10]
```diff
@@ -704,16 +548,6 @@ func (s *baseSingleGroupJoinOrderSolver) checkConnection(leftPlan, rightPlan bas
 	return
 }
 
-func (*baseSingleGroupJoinOrderSolver) injectExpr(p base.LogicalPlan, expr expression.Expression) (base.LogicalPlan, *expression.Column) {
```
Comment (qw4990) [inline pkg/planner/core/rule_join_reorder.go]: And could we split this PR into 2 parts? The first part is used to move code and refactor, and the second part is used to add the CDC implementation.

File: pkg/planner/core/joinorder/join_order.go [hunk 11]
```diff
@@ -0,0 +1,775 @@
...
+	// For now, we only handle inner join and left/right outer join.
+	if join.JoinType != base.InnerJoin && join.JoinType != base.LeftOuterJoin && join.JoinType != base.RightOuterJoin {
+		return makeSingleGroup(p)
+	}
+
+	if join.PreferJoinType > uint(0) && !p.SCtx().GetSessionVars().EnableAdvancedJoinHint {
+		return makeSingleGroup(p)
+	}
+
+	if slices.ContainsFunc(join.EqualConditions, func(expr *expression.ScalarFunction) bool {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/join_order.go:103]: Could you help add some comments? Why our join-reorder can't handle `nulleq`?

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 12]
```diff
@@ -0,0 +1,780 @@
...
+	}
+}
+
+// Build will construct the conflict detector from the given join group.
+func (d *ConflictDetector) Build(group *joinGroup) ([]*Node, error) {
+	if len(group.vertexes) > 64 {
+		return nil, errors.Errorf("too many vertexes in join group: %d, exceeds maximum supported 64", len(group.vertexes))
+	}
+	d.groupRoot = group.root
+	d.allInnerJoin = group.allInnerJoin
```
Comment (qw4990) [inline pkg/planner/core/joinorder/conflict_detector.go:234]: Could we skip all below operations if `allInner` is true?

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 13]
```diff
@@ -0,0 +1,780 @@
...
+	rule := &rule{from: child.leftVertexes}
+	if child.rightVertexes.Intersects(child.tes) {
+		rule.to = child.rightVertexes.Intersection(child.tes)
+	} else {
+		rule.to = child.rightVertexes
+	}
+	return rule
+}
+
+func (d *ConflictDetector) calcTES(conds []expression.Expression) intset.FastIntSet {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/conflict_detector.go]: Please add more comments about this function.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 14]
```diff
@@ -0,0 +1,780 @@
...
+	idx uint64
+	// No need to store the original join operator,
+	// because we may generate a new join operator, so only join conditions are enough.
+	joinType base.JoinType
+	eqConds  []*expression.ScalarFunction
+	// It could be otherCond, leftCond or rightCond.
+	nonEQConds expression.CNFExprs
+
+	tes   intset.FastIntSet
+	rules []*rule
```
Comment (qw4990) [inline pkg/planner/core/joinorder/conflict_detector.go:129]: Better to add more comments to briefly describe `tes` and `rules`.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 15]
```diff
@@ -0,0 +1,780 @@
...
+		}
+	}
+
+	if _, _, err := d.buildRecursive(group.root, group.vertexes, vertexMap); err != nil {
+		return nil, err
+	}
+	return d.groupVertexes, nil
+}
+
+func (d *ConflictDetector) buildRecursive(p base.LogicalPlan, vertexes []base.LogicalPlan, vertexMap map[int]*Node) ([]*edge, intset.FastIntSet, error) {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/conflict_detector.go]: It seems like `vertexes []base.LogicalPlan` is useless in this function? Can we simplify it?

Image

**Comment by guo-shaoge** [comment]
> 1. **P2: Hard limit of 64 join vertices causes planning failure**
>    
>    * When a join group has >64 leaf vertices, the conflict detector returns an error that propagates to query planning, causing the query to fail instead of gracefully falling back.
>    * Evidence: `pkg/planner/core/joinorder/conflict_detector.go:108` - `if len(group.vertexes) > 64 { return nil, errors.Errorf("too many vertexes...") }`
>    * Impact: Queries with very wide joins (>64 tables in one group) will fail with an error on the default path.
> 2. **P2: DP join reorder support removed, threshold ignored**
>    
>    * The new join reorder implementation hardcodes greedy mode, making `tidb_opt_join_reorder_threshold` ineffective.
>    * Evidence: `pkg/planner/core/joinorder/join_order.go:261` - `useGreedy := true` with DP path as `panic("not implement yet")`
>    * Impact: Configuration/feature parity gap for non-default deployments using threshold tuning.
> 3. **P2: Session variable tidb_opt_join_reorder_through_sel silently ignored**
>    
>    * When outer join reorder is enabled (default), the code bypasses legacy join group extraction that honors this session variable.
>    * Evidence: `pkg/planner/core/rule_join_reorder.go:248` - short-circuits to `joinorder.Optimize` which doesn't check the variable
>    * Impact: The session variable becomes a no-op under default configuration.
> 4. **P2: alignEQConds can create invalid join keys**
>    
>    * The function has logic that may build equality functions with nil arguments and doesn't propagate injected projections back to join children.
>    * Evidence: `pkg/planner/core/joinorder/conflict_detector.go:506` - declares `var lCol, rCol expression.Expression` but may not assign both before using
>    * Impact: Latent bug, likely unreachable with current planner invariants but represents faulty porting from legacy code.

1 and 4 have been fixed
2: DP will be implement in the future
3. `tidb_opt_join_reorder_through_sel` will be supported in the next PR

File: pkg/executor/test/indexmergereadtest/index_merge_reader_test.go (hunk 8 above)
Comment (guo-shaoge) [reply pkg/executor/test/indexmergereadtest/index_merge_reader_test.go:231]: No, it's unexpected. I've added the second call of `greedyConnectJoinNodes` with `allowNoEQ` as true to fix this.

File: pkg/planner/core/casetest/hint/testdata/integration_suite_out.json [hunk 16]
```diff
@@ -1921,9 +1921,7 @@
           "    └─TableReader(Probe) 10000.00 root  data:TableFullScan",
           "      └─TableFullScan 10000.00 cop[tikv] table:t1 keep order:false, stats:pseudo"
         ],
-        "Warn": [
-          "Warning 1815 leading hint is inapplicable, check if the leading hint table has join conditions with other tables"
-        ]
+        "Warn": null
```
Comment (guo-shaoge) [inline pkg/planner/core/casetest/hint/testdata/integration_suite_out.json]: The new impl doesn't has warning, which is correct, check https://github.com/pingcap/tidb/blob/dbf86b016d0bedb43a473c14c7c49e455d5335a3/pkg/planner/core/rule_join_reorder_greedy.go#L84-L89

File: pkg/planner/core/casetest/mpp/testdata/integration_suite_out.json [hunk 17]
```diff
@@ -1705,23 +1705,22 @@
...
-          "                └─HashJoin 12475.01 mpp[tiflash]  inner join, equal:[eq(test.t.c2, test.t.c1)]",
-          "                  ├─ExchangeReceiver(Build) 9980.01 mpp[tiflash]  ",
-          "                  │ └─ExchangeSender 9980.01 mpp[tiflash]  ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: test.t.c2, collate: binary]",
-          "                  │   └─Selection 9980.01 mpp[tiflash]  not(isnull(test.t.c2)), not(isnull(test.t.c5))",
-          "                  │     └─TableFullScan 10000.00 mpp[tiflash] table:t2 keep order:false, stats:pseudo",
-          "                  └─ExchangeReceiver(Probe) 9990.00 mpp[tiflash]  ",
-          "                    └─ExchangeSender 9990.00 mpp[tiflash]  ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: test.t.c1, collate: binary]",
-          "                      └─Selection 9990.00 mpp[tiflash]  not(isnull(test.t.c1))",
-          "                        └─TableFullScan 10000.00 mpp[tiflash] table:t1 keep order:false, stats:pseudo"
+          "        └─HashJoin 15593.77 mpp[tiflash]  inner join, equal:[eq(test.t.c5, test.t.c3)]",
```
Comment (guo-shaoge) [inline pkg/planner/core/casetest/mpp/testdata/integration_suite_out.json]: the new impl only has one `Projection`, but the old impl has more. because the old impl cannot handle `right join`, so there will be multiple join groups, but in new impl, there will only be one join group.

File: pkg/planner/core/casetest/rule/testdata/join_reorder_suite_out.json [hunk 18]
```diff
@@ -303,60 +301,58 @@
...
-          "    │ └─Selection 9990.00 cop[tikv]  not(isnull(test.t6.b))",
-          "    │   └─TableFullScan 10000.00 cop[tikv] table:t6 keep order:false, stats:pseudo",
-          "    └─HashJoin(Probe) 12475.01 root  inner join, equal:[eq(test.t5.a, test.t2.a)]",
-          "      ├─TableReader(Build) 9980.01 root partition:all data:Selection",
-          "      │ └─Selection 9980.01 cop[tikv]  not(isnull(test.t5.a)), not(isnull(test.t5.b))",
-          "      │   └─TableFullScan 10000.00 cop[tikv] table:t5 keep order:false, stats:pseudo",
-          "      └─TableReader(Probe) 9990.00 root partition:all data:Selection",
-          "        └─Selection 9990.00 cop[tikv]  not(isnull(test.t2.a))",
-          "          └─TableFullScan 10000.00 cop[tikv] table:t2 keep order:false, stats:pseudo"
+          "└─HashJoin 30426.12 root  inner join, equal:[eq(test.t5.b, test.t6.b)]",
```
Comment (guo-shaoge) [inline pkg/planner/core/casetest/rule/testdata/join_reorder_suite_out.json]: got different join order because old impl doesn't support reorder the right side of `left join`

File: pkg/planner/core/casetest/rule/testdata/join_reorder_suite_out.json [hunk 19]
```diff
@@ -303,60 +301,58 @@
...
+          "          └─TableReader(Probe) 9990.00 root partition:all data:Selection",
+          "            └─Selection 9990.00 cop[tikv]  not(isnull(test.t4.b))",
+          "              └─TableFullScan 10000.00 cop[tikv] table:t4 keep order:false, stats:pseudo"
         ],
         "Warning": null
       },
       {
         "SQL": "select /*+ leading(t3, t4) leading(t5, t6) */ * from t2 left join (t1 join t3 on t1.a=t3.a join t4 on t3.b = t4.b) on t2.b=t1.b join t5 on t2.a = t5.a join t6 on t5.b=t6.b;",
         "Plan": [
-          "Projection 30426.12 root  test.t2.a, test.t2.b, test.t1.a, test.t1.b, test.t3.a, test.t3.b, test.t4.a, test.t4.b, test.t5.a, test.t5.b, test.t6.a, test.t6.b",
```
Comment (guo-shaoge) [inline pkg/planner/core/casetest/rule/testdata/join_reorder_suite_out.json:336]: same reason as above

File: pkg/planner/core/casetest/rule/testdata/join_reorder_suite_out.json [hunk 20]
```diff
@@ -365,33 +361,31 @@
       {
         "SQL": "select /*+ leading(t5, t6, t3, t4) */ * from t2 left join (t1 join t3 on t1.a=t3.a join t4 on t3.b = t4.b) on t2.b=t1.b join t5 on t2.a = t5.a join t6 on t5.b=t6.b;",
         "Plan": [
-          "Projection 30426.12 root  test.t2.a, test.t2.b, test.t1.a, test.t1.b, test.t3.a, test.t3.b, test.t4.a, test.t4.b, test.t5.a, test.t5.b, test.t6.a, test.t6.b",
```
Comment (guo-shaoge) [inline pkg/planner/core/casetest/rule/testdata/join_reorder_suite_out.json:368]: old impl doesn't support reorder the right side of `left join`

File: pkg/planner/core/joinorder/join_order.go [hunk 21]
```diff
@@ -0,0 +1,587 @@
...
+		return expr.FuncName.L == ast.NullEQ
```
Comment (qw4990) [inline pkg/planner/core/joinorder/join_order.go:104]: Could you add some comments or examples about this? Why `nulleq` could block the join-order?

File: pkg/planner/core/joinorder/join_order.go [hunk 22]
```diff
@@ -0,0 +1,587 @@
...
+	// Original Order: (R1 INNER R2 ON P12) LEFT JOIN (R3 INNER R4 ON P34) ON P23 (Pxy denotes a join condition using Rx and Ry as inputs.)
+	//   The LEFT JOIN condition P23 contains only otherCond (non-equi conditions) without any eqCond.
+	// Potential Suboptimal Order: R1 INNER (R2 LEFT JOIN (R3 INNER R4 ON P34) ON P23) ON P12
+	//   This implies that the edge P23 (lacking an eqCond) is applied earlier than in the original order.
+	//   Since edges without equi-conditions perform poorly (as the executor cannot utilize Hash Join),
+	//   and the current single-sequence greedy algorithm cannot explore enough alternative sequences, it may return this poor-performing order directly.
+	// So We have temporarily disabled reordering for non INNER JOIN that without eqCond.
+	// For INNER JOINs, we introduced a penalty factor. If the factor is set less equal to 0,
+	// Cartesian products will only be applied at the final step(which will generate a bushy tree).
+	if join.JoinType != base.InnerJoin && len(join.EqualConditions) == 0 {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/join_order.go:125]: It seems like the prior implementation doesn't have this limitation, do I understand this correctly?

File: pkg/planner/core/joinorder/join_order.go [hunk 23]
```diff
@@ -0,0 +1,587 @@
...
+		return makeSingleGroup(p)
+	}
+
+	var curLeadingHint *hint.PlanHints
+	if join.PreferJoinOrder {
+		curLeadingHint = join.HintInfo
+	}
+	defer func() {
+		if curLeadingHint != nil {
+			resJoinGroup.leadingHints = []*hint.PlanHints{curLeadingHint}
```
Comment (qw4990) [inline pkg/planner/core/joinorder/join_order.go]: Will this cover the original `resJoinGroup.leadingHints`? Should we use `resJoinGroup.leadingHints = append(resJoinGroup.leadingHints, curLeadingHint...)`

File: pkg/planner/core/joinorder/join_order.go [hunk 24]
```diff
@@ -0,0 +1,587 @@
...
+	if len(vertexMap) > 0 {
+		joinGroup.root = replaceJoinGroupVertexes(joinGroup.root, vertexMap)
+	}
+	if p, err = optimizeForJoinGroup(p.SCtx(), joinGroup); err != nil {
+		return nil, err
+	}
+	return p, nil
+}
+
+func replaceJoinGroupVertexes(root base.LogicalPlan, vertexMap map[int]base.LogicalPlan) base.LogicalPlan {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/join_order.go:248]: I can guess this function is used to update references in the old Plan Tree to their newly optimized children... but please add more comments for this since this seems subtle and tricky...

File: pkg/planner/core/joinorder/join_order.go [hunk 25]
```diff
@@ -0,0 +1,587 @@
...
+		befLen := len(nodes)
+		if nodes, err = greedyConnectJoinNodes(detector, nodes, j.group.vertexHints, cartesianFactor, true); err != nil {
+			return nil, err
+		}
+		if len(nodes) != befLen {
+			// Only collect usedEdges when new joins are made in the second round.
+			usedEdges = collectUsedEdges(nodes)
+		}
+	}
+	if detector.HasRemainingEdges(usedEdges) {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/join_order.go:456]: Could you add some comments to explain when this could happen?

File: pkg/planner/core/joinorder/join_order.go [hunk 26]
```diff
@@ -0,0 +1,587 @@
...
+	if useGreedy {
+		joinOrderGreedy := newJoinOrderGreedy(ctx, group)
+		if p, err = joinOrderGreedy.optimize(); err != nil {
+			return nil, err
+		}
+	} else {
+		joinOrderDP := newJoinOrderDP(ctx, group)
+		if p, err = joinOrderDP.optimize(); err != nil {
+			return nil, err
+		}
```
Comment (winoros) [inline pkg/planner/core/joinorder/join_order.go:283]: Because we're directly using it to replace the current outer join reorder. 
We'd better make the behavior consistent. If possible, choose dp if there's no non-inner join.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 13 above)
Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go]: At least we need to repeat what the paper mentioned

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 27]
```diff
@@ -0,0 +1,784 @@
...
+				return nil, errors.New("multiple non-inner edges applied between two nodes")
+			}
+			result.appliedNonInnerEdge = e
+			result.hasEQCond = result.hasEQCond || len(e.eqConds) > 0
+		}
+	}
+	return result, nil
+}
+
+func (e *edge) checkInnerEdge(node1, node2 *Node) bool {
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: add comment that it's aligned with the CD-C's `IsApplicable` in the paper.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 28]
```diff
@@ -0,0 +1,784 @@
...
+	if !e.skipRules && !e.checkRules(node1, node2) {
+		return false
+	}
+	return e.tes.SubsetOf(node1.bitSet.Union(node2.bitSet)) &&
+		e.tes.Intersects(node1.bitSet) &&
+		e.tes.Intersects(node2.bitSet)
+}
+
+func (e *edge) checkNonInnerEdge(node1, node2 *Node) bool {
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: the same as `checkInnerEdge`

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 27 above)
Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go]: And we can organize them together.
`them` here means the fundamental concepts we directly learned from the paper.

Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go]: In this way, it's easy to check the things from the paper and the engineering efforts we need to adopt it in tidb.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 29]
```diff
@@ -0,0 +1,784 @@
...
+		leftVertexes:  leftVertexes,
+		rightVertexes: rightVertexes,
+		leftEdges:     leftEdges,
+		rightEdges:    rightEdges,
+		skipRules:     d.allInnerJoin,
+	}
+
+	// setup TES. Only consider EqualConditions and NAEQConditions.
+	// OtherConditions are not edges.
+	e.tes = d.calcTES(conds)
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: Actually, we are using the `calcSES` from the paper. So better to keep its name and comment that this is the initialization of the tes.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 30]
```diff
@@ -0,0 +1,784 @@
...
+
+	e := d.makeEdge(joinop.JoinType, conds, leftVertexes, rightVertexes, leftEdges, rightEdges)
+	e.eqConds = make([]*expression.ScalarFunction, len(joinop.EqualConditions))
+	copy(e.eqConds, joinop.EqualConditions)
+	e.nonEQConds = nonEQConds
+
+	return e
+}
+
+func (d *ConflictDetector) makeEdge(joinType base.JoinType, conds []expression.Expression, leftVertexes, rightVertexes intset.FastIntSet, leftEdges, rightEdges []*edge) *edge {
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go:369]:
```suggestion
func (d *ConflictDetector) makeEdgeAndAddConflictRules(joinType base.JoinType, conds []expression.Expression, leftVertexes, rightVertexes intset.FastIntSet, leftEdges, rightEdges []*edge) *edge {
```

We'd better keep the terms borrowed from the paper. So, one who is not familiar with the codes can easily find the reference.

Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go:369]: Also, add comments that it implements the core of the CD-C from the paper.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 31]
```diff
@@ -0,0 +1,784 @@
...
+		d.innerEdges = append(d.innerEdges, e)
+	} else {
+		d.nonInnerEdges = append(d.nonInnerEdges, e)
+	}
+
+	// setup conflict rules
+	if d.allInnerJoin {
+		return e
+	}
+	for _, child := range leftEdges {
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go:415]: From the `checkInnerEdge` and `checkNonInnerEdge`, we can see that the general time complexity is `O(JoinReorderAlgo) * O(Check Applicable)`.

So it's safe not to implement the 5.5 of the paper for now.
But it's needed when we add dp reorder.

**Review by winoros — COMMENTED** [review]
When we add comments about the paper. Better to include the chapter name or the original function name in the paper's pseudo code.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 27 above)
Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go]: And maybe `checkInnerEdgeApplicable` can make it easier to match with the paper.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 13 above)
Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go]: And it's actually the `calcSES` in the paper.
followed by 

Image

We'd better keep the original name.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 32]
```diff
@@ -0,0 +1,784 @@
...
+// 2: rule applies when null-rejective holds
+// NOTE: for now 2 is not used, and both assoc(left, left) and assoc(right, right) are 1:
+//  1. TiDB doesn't support FULL OUTER JOIN: in the table-2 of the original paper, most of null-rejective is related to FULL OUTER JOIN.
+//  2. We only support reorder NON-INNER JOIN when it has eqConds, which means it must be null-rejective on both sides.
+//     See the eqCond check in extractJoinGroup() for the guarantee.
+//
+// But I still leave 2 here for future extension.
+type ruleTableEntry int
+
+var assocRuleTable = [][]ruleTableEntry{
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go:825]: It's okay to keep the original matrix version from the paper, I think.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 33]
```diff
@@ -0,0 +1,784 @@
...
+		}
+		return true
+	})
+	return
+}
+
+// 0: rule doesn't apply
+// 1: rule applies
+// 2: rule applies when null-rejective holds
+// NOTE: for now 2 is not used, and both assoc(left, left) and assoc(right, right) are 1:
```
Comment (winoros) [inline pkg/planner/core/joinorder/conflict_detector.go]: Now that 2 is not used, we can simply change it to a bool and only mention it in the comment.

Comment (winoros) [reply pkg/planner/core/joinorder/conflict_detector.go]: Oh, I'll check the paper again. I saw your comment in another place. Maybe I misunderstood the paper's meaning. Let me check it.

File: pkg/planner/core/joinorder/join_order.go (hunk 22 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go:125]: The old implementation doesn't this situation(reorder Non-INNER JOIN without eqConds) either, check https://github.com/pingcap/tidb/blob/c6d1fffb98c66aca65f9751f2cd01a049092f9d8/pkg/planner/core/rule_join_reorder.go#L75

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 33 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: Since tidb doesn't support FULL OUTER JOIN(neither for mysql), so only assoc(left, left) and assoc(right, right) need the check of null-rejective.
And since we currently don't support reorder for NON-INNER JOIN that without eqCond, so `2` is useless for now.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 32 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:825]: This table is basically same as the one from the paper. A few changes:
1. Add support for RIGHT JOIN, which wasn't included in the paper. We can also transfer all RIGHT JOIN to LEFT JOIN before reorder, but I choose to extend the original matrix since it's much more controllable.
2. change `assoc(left, left)/assoc(right, right)` from `2` to `1`: explained in the code.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 31 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:415]: Yes, aggred. I'll add a todo here.

File: pkg/planner/core/joinorder/join_order.go (hunk 26 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go:283]: Yes, your comment make sense. But it requires plenty of code changes to integrate the new `joinGroup` struct with the old DP implementation.

I planned to merge the old and the new code path in the next PR. I will add a TODO here, and fix this problem in the next PR.

This PR only focus on the pure CD-C implementation.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 27 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: done

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 28 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: done

File: pkg/planner/core/joinorder/join_order.go (hunk 23 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go]: Yes, you're right, I should use `append`. Because in `CheckAndGenerateLeadingHint`, it requires there should only has one hint in one join group. If we dont use `append`, we may miss this check.

File: pkg/planner/core/joinorder/join_order.go (hunk 24 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go:248]: done

File: pkg/planner/core/joinorder/join_order.go (hunk 25 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go:456]: done

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 2 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:817]: explained

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 1 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: done

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 4 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: explained

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 30 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:369]: done

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 29 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: how about use comment to explain the difference, instead of modifying the code?

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 14 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:129]: done

File: pkg/planner/core/casetest/rule/rule_cdc_join_reorder_test.go [hunk 34]
```diff
@@ -0,0 +1,82 @@
...
+		tk.MustExec("CREATE TABLE t2 (a INT, b INT)")
+		tk.MustExec("CREATE TABLE t3 (a INT, b INT)")
+		tk.MustExec("CREATE TABLE t4 (a INT, b INT)")
+		tk.MustExec("CREATE TABLE t5 (a INT, b INT)")
+
+		tk.MustExec("INSERT INTO t1 VALUES (1, 10), (2, 20), (3, 30)")
+		tk.MustExec("INSERT INTO t2 VALUES (1, 100), (2, 200), (4, 400)")
+		tk.MustExec("INSERT INTO t3 VALUES (1, 1000), (3, 3000), (5, 5000)")
+		tk.MustExec("INSERT INTO t4 VALUES (1, 10000), (4, 40000), (6, 60000)")
+		tk.MustExec("INSERT INTO t5 VALUES (2, 20000), (5, 50000), (7, 70000)")
```
Comment (qw4990) [inline pkg/planner/core/casetest/rule/rule_cdc_join_reorder_test.go:40]: Should we enumerate more column types like `string`, `decimal`, `not null`, `default null`?
And prepare more extreme values like `null`, `0`, `""`.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 35]
```diff
@@ -0,0 +1,936 @@
...
+	var curEdges []*edge
+	if joinop.JoinType == base.InnerJoin {
+		if curEdges, err = d.makeInnerEdge(joinop, leftVertexes, rightVertexes, leftEdges, rightEdges); err != nil {
+			return nil, curVertexes, err
+		}
+	} else {
+		curEdge := d.makeNonInnerEdge(joinop, leftVertexes, rightVertexes, leftEdges, rightEdges)
+		curEdges = []*edge{curEdge}
+	}
+	if leftVertexes.Intersects(rightVertexes) {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/conflict_detector.go:294]: When could this happen? Just for safety?

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 36]
```diff
@@ -0,0 +1,936 @@
...
+
+	e := d.makeEdge(joinop.JoinType, conds, leftVertexes, rightVertexes, leftEdges, rightEdges)
+	e.eqConds = make([]*expression.ScalarFunction, len(joinop.EqualConditions))
+	copy(e.eqConds, joinop.EqualConditions)
+	e.nonEQConds = nonEQConds
+
+	return e
+}
+
+func (d *ConflictDetector) makeEdge(joinType base.JoinType, conds []expression.Expression, leftVertexes, rightVertexes intset.FastIntSet, leftEdges, rightEdges []*edge) *edge {
```
Comment (qw4990) [inline pkg/planner/core/joinorder/conflict_detector.go:369]: Please add more comments for this function. It seems like this is the main function that refers to the original paper.

Image

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 37]
```diff
@@ -0,0 +1,936 @@
...
+	e := &edge{
+		idx:           uint64(len(d.innerEdges) + len(d.nonInnerEdges)),
```
Comment (qw4990) [inline pkg/planner/core/joinorder/conflict_detector.go:374]: This seems strange at first glance. So as we add more edges, the index would increase automatically? Could you add a simple comment for this...

File: pkg/planner/core/joinorder/join_order.go [hunk 38]
```diff
@@ -0,0 +1,603 @@
...
+		return nil, nil, err
+	}
+	if !checkResult.Connected() {
+		if !allowNoEQ {
+			return nil, nil, nil
+		}
+		if checkResult = detector.TryCreateCartesianCheckResult(leftPlan, rightPlan); checkResult == nil {
+			return nil, nil, nil
+		}
+	}
```
Comment (qw4990) [inline pkg/planner/core/joinorder/join_order.go:399]: It seems like there are 2 cases:
1. left and right are invalid to join now;
2. left and right are valid to join without any edge, but we can still use cartesian-join;
Now both case-1 and case-2 are judged by `!connected`. Should we use another more explicit way to distinguish them?

Comment (qw4990) [reply pkg/planner/core/joinorder/join_order.go:399]: offline discussed.

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 36 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:369]: comment added

File: pkg/planner/core/joinorder/join_order.go (hunk 38 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go:399]: For these two cases, `checkResult.Connected()` both returns false.
1. For the first point, it's reasonable to return false.
2. For the second point, other DBMS implementations support a `fallback cross edge`, which can connect two different subsets even there is no join condition between them in the original sql. And `checkResult.Connected()` will return true if we also implementat using this way. But now we choose a more easier way that `checkResult.Connected()` return false and we call `TryCreateCartesianCheckResult` to create a cartesian edge explicitly if join group is all inner join.

PS: The cartesian edge will be created in two situations(check function calls that call `checkConnectionAndMakeJoin` with `allowNoEQ` as true):
1. leading hint force this connection
2. maybe cartesian edge is a better chose, for example this issue: https://github.com/pingcap/tidb/issues/63290

Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go:399]: I've added to comment for `TryCreateCartesianCheckResult`

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 37 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:374]: comment added

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 35 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:294]: Yes, it's just a santify test.

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 39]
```diff
@@ -0,0 +1,961 @@
...
+// But for now, we take a simpler approach: checkResult.Connected() return false for above both situations,
+// and let the caller explicitly call TryCreateCartesianCheckResult to construct a
+// cartesian edge when the join group is all-inner-join.
+//
+// The cartesian edge is created in two situations (callers that pass allowNoEQ=true
+// to checkConnectionAndMakeJoin):
+//  1. A leading hint forces the connection (e.g. LEADING(R1, R3) when there is no
+//     predicate between R1 and R3).
+//  2. The greedy enumerator's second pass, where allowing cartesian joins may find
+//     a better plan. See https://github.com/pingcap/tidb/issues/63290.
```
Comment (AilinKid) [inline pkg/planner/core/joinorder/conflict_detector.go:161]:
```suggestion
//     a worse plan. See https://github.com/pingcap/tidb/issues/63290.
```

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 40]
```diff
@@ -0,0 +1,961 @@
...
+		}
+	} else {
+		curEdge, err := d.makeNonInnerEdge(joinop, leftVertexes, rightVertexes, leftEdges, rightEdges)
+		if err != nil {
+			return nil, curVertexes, err
+		}
+		curEdges = []*edge{curEdge}
+	}
+	if leftVertexes.Intersects(rightVertexes) {
+		return nil, curVertexes, errors.New("conflicting join edges detected")
```
Comment (AilinKid) [inline pkg/planner/core/joinorder/conflict_detector.go:295]: once detect conflict we just use the original tree right？

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 41]
```diff
@@ -0,0 +1,961 @@
...
+	}
+	curVertexes = leftVertexes.Union(rightVertexes)
+
+	return append(leftEdges, append(rightEdges, curEdges...)...), curVertexes, nil
+}
+
+// makeInnerEdge splits an inner join into one edge per conjunct (eq-cond or
+// non-eq-cond). This follows the approach from CockroachDB: splitting enlarges
+// the search space by allowing each predicate to be applied independently.
```
Comment (AilinKid) [inline pkg/planner/core/joinorder/conflict_detector.go]: you can comment with example
```
ON A.id = C.id AND B.k = D.k
```
if not split, we still need to wait ACBD, but id we did, first and item can be applied only with (AC) first

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 40 above)
Comment (AilinKid) [reply pkg/planner/core/joinorder/conflict_detector.go:295]: should we log as well?

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 42]
```diff
@@ -0,0 +1,961 @@
...
+	for _, e := range d.nonInnerEdges {
+		if node1.checkUsedEdges(e.idx) || node2.checkUsedEdges(e.idx) {
+			continue
+		}
+		if e.checkNonInnerEdgeApplicable(node1, node2) {
+			if result.appliedNonInnerEdge != nil {
+				return nil, errors.New("multiple non-inner edges applied between two nodes")
+			}
+			result.appliedNonInnerEdge = e
+			result.hasEQCond = result.hasEQCond || len(e.eqConds) > 0
```
Comment (AilinKid) [inline pkg/planner/core/joinorder/conflict_detector.go:554]: since non-inner edges can only be applied once, we can just break here?

File: pkg/planner/core/joinorder/conflict_detector.go [hunk 43]
```diff
@@ -0,0 +1,961 @@
...
+// to checkConnectionAndMakeJoin):
+//  1. A leading hint forces the connection (e.g. LEADING(R1, R3) when there is no
+//     predicate between R1 and R3).
+//  2. The greedy enumerator's second pass, where allowing cartesian joins may find
+//     a better plan. See https://github.com/pingcap/tidb/issues/63290.
+func (d *ConflictDetector) TryCreateCartesianCheckResult(left, right *Node) *CheckConnectionResult {
+	if !d.allInnerJoin {
+		return nil
+	}
+	cartesianEdge := d.makeEdge(base.InnerJoin, []expression.Expression{}, left.bitSet, right.bitSet, nil, nil)
```
Comment (AilinKid) [inline pkg/planner/core/joinorder/conflict_detector.go:166]: makeEdge will add one more temporary cartesianEdge to detector edges, causing enumeration pressure which is necessary.

File: pkg/planner/core/joinorder/join_order.go [hunk 44]
```diff
@@ -0,0 +1,603 @@
...
+	usedEdges := collectUsedEdges(nodes)
+	if !allowNoEQ && detector.HasRemainingEdges(usedEdges) {
+		// After the first round of greedy connection, there are still some remaining edges,
+		// for example: R1 INNER JOIN R2 ON R1.c1 < R2.c2
+		// the above join can only be connected when non-eq edges are allowed,
+		// and the first round of greedy enumeration is not allowed to use non-eq edges.
+		// So we got here and we need to the second round of enumeration with `allowNoEQ` as true.
+		befLen := len(nodes)
+		if nodes, err = greedyConnectJoinNodes(detector, nodes, j.group.vertexHints, cartesianFactor, true); err != nil {
+			return nil, err
```
Comment (AilinKid) [inline pkg/planner/core/joinorder/join_order.go:449]: detection failure should log once as well？

**Review by AilinKid — COMMENTED** [review]
rest LGTM

File: pkg/planner/core/joinorder/join_order.go (hunk 44 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/join_order.go:449]: I think no need to log, since this error will throw to user directly.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 43 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:166]: Adding this cartesian edge is required when leading hint is used or we want a cartesian edge explicitly, check the comment of this function.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 40 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:295]: this is not a detect conflict, this is a logical error.
this could only happen when we have implementation bug. 
It's just a santity check.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 42 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go:554]: We expect there should no such situation(more than one non inner edges), if it does happen, it's a logical eror or some situation that we never known.
In that case, it's better to report error to avoid incorrect result instead of silently use the first non inner edge.

File: pkg/planner/core/joinorder/conflict_detector.go (hunk 41 above)
Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: ok

Comment (guo-shaoge) [reply pkg/planner/core/joinorder/conflict_detector.go]: done

**Review by AilinKid — APPROVED** [review]
