### PR TITLE
planner: preserve UnionScan child rewrite for NULL predicates

### LINKED ISSUE #67967: planner: col = NULL under UnionScan regresses to table full scan
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start TiDB with the default local store, then run:

```sql
DROP TABLE IF EXISTS t_issue_67552_repro;
CREATE TABLE t_issue_67552_repro (
  id bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
  delete_flag tinyint DEFAULT NULL
);

BEGIN;
INSERT INTO t_issue_67552_repro(delete_flag) VALUES (NULL);
EXPLAIN SELECT 1 FROM t_issue_67552_repro USE INDEX() WHERE delete_flag = NULL;
ROLLBACK;

DROP TABLE t_issue_67552_repro;
```

This is minimized from a larger query on a table with more columns and predicates. The key point is that the `EXPLAIN` is executed inside a transaction after an `INSERT`, so the plan contains `UnionScan`.

I also verified that, on current master, removing `USE INDEX()` still reproduces the same table full scan.

Bisect result:

- good parent: `c60c8415a3bb0d54d03a69d6fdf0d40233097a2b` (`*: bump pd client (#59313)`)
- first bad commit: `fa0bc8e5bcdb416ddf2e50ca19d0bf2c20b9d5fd` (`planner: change more conditions that are always false to dual (#59199)`)
- current bad commit tested: `874ff3792e7e0f51068547f90cefc1acbfed7232`

### 2. What did you expect to see? (Required)

`delete_flag = NULL` cannot match any row under SQL semantics, so the optimizer should keep the data source as `TableDual` even when `UnionScan` is needed for the transaction buffer.

On the parent commit `c60c8415a3bb0d54d03a69d6fdf0d40233097a2b`, the minimized query produces:

```text
+---------------------+---------+------+---------------+------------------------------------------------+
| id                  | estRows | task | access object | operator info                                  |
+---------------------+---------+------+---------------+------------------------------------------------+
| Projection_5        | 0.00    | root |               | 1->Column#3                                    |
| └─UnionScan_6       | 0.00    | root |               | eq(test.t_issue_67552_repro.delete_flag, NULL) |
|   └─TableDual_7     | 0.00    | root |               | rows:0                                         |
+---------------------+---------+------+---------------+------------------------------------------------+
```

### 3. What did you see instead (Required)

Starting from `fa0bc8e5bcdb416ddf2e50ca19d0bf2c20b9d5fd`, the same minimized query scans the table:

```text
+---------------------------+----------+-----------+---------------------------+------------------------------------------------+
| id                        | estRows  | task      | access object             | operator info                                  |
+---------------------------+----------+-----------+---------------------------+------------------------------------------------+
| Projection_6              | 10000.00 | root      |                           | 1->Column#3                                    |
| └─UnionScan_7             | 10000.00 | root      |                           | eq(test.t_issue_67552_repro.delete_flag, NULL) |
|   └─TableReader_9         | 10000.00 | root      |                           | data:TableFullScan_8                           |
|     └─TableFullScan_8     | 10000.00 | cop[tikv] | table:t_issue_67552_repro | keep order:false, stats:pseudo                 |
+---------------------------+----------+-----------+---------------------------+------------------------------------------------+
```

Outside of the transaction / without the uncommitted insert, the same `delete_flag = NULL` predicate is planned as `TableDual`, so this appears to be specific to the `UnionScan` path.

### 4. What is your TiDB version? (Required)

Current master tested:

```text
Release Version: v8.5.4-nextgen.202510.0-990-g874ff3792e
Edition: Community
Git Commit Hash: 874ff3792e7e0f51068547f90cefc1acbfed7232
Git Branch: now-master
UTC Build Time: 2026-04-22 13:18:23
GoVersion: go1.25.8
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Kernel Type: Classic
```

First bad commit tested:

```text
Release Version: v9.0.0-beta.1.pre-215-gfa0bc8e5bc
Git Commit Hash: fa0bc8e5bcdb416ddf2e50ca19d0bf2c20b9d5fd
Store: unistore
```

Good parent tested:

```text
Release Version: v9.0.0-beta.1.pre-214-gc60c8415a3
Git Commit Hash: c60c8415a3bb0d54d03a69d6fdf0d40233097a2b
Store: unistore
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #67967

Problem Summary:

`delete_flag = NULL` is always false, so the optimizer should preserve the
`TableDual` rewrite even when the query runs inside a transaction and goes
through `UnionScan` predicate pushdown.

After `#59199`, `DataSource.PredicatePushDown()` can already turn this predicate
into `TableDual`, but `LogicalUnionScan.PredicatePushDown()` dropped the child
plan returned from its child. That kept the original scan child and regressed
the issue case to a full table scan.

### What changed and how does it work?

- Keep the child plan returned from `LogicalUnionScan.PredicatePushDown()`.
- If the rewritten child is already `TableDual`, return it directly instead of
  keeping a redundant `UnionScan`.
- Add a regression test for the transaction + `col = NULL` case, covering both
  `USE INDEX()` and the no-hint variant from the issue report.
- Extend the prepared-plan-cache test to verify the transaction path still keeps
  the result empty and remains cache-safe.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Queries with NULL comparisons involving union-scan logic now produce stable, correct execution plans and no longer lead to incorrect plan reuse or unexpected empty results across transactional boundaries.

* **Tests**
  * Added regression and plan-cache tests validating correct plan generation, proper cache invalidation and safe reuse for NULL-comparison scenarios, including behavior across transactions, rollbacks, and prepared/executed statements.

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]

File: pkg/planner/core/operator/logicalop/logical_union_scan.go [hunk 1]
```diff
@@ -70,10 +70,11 @@ func (p *LogicalUnionScan) PredicatePushDown(predicates []expression.Expression)
 		}
 	}
 	predicates = predicatesWithoutVCol
-	retainedPredicates, _, err := p.Children()[0].PredicatePushDown(predicates)
+	retainedPredicates, child, err := p.Children()[0].PredicatePushDown(predicates)
 	if err != nil {
 		return nil, nil, err
 	}
+	p.SetChild(0, child)
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_union_scan.go:80]: We can go further?
```suggestion
	if _, ok := child.(LogicalTableDual); ok {
		return child, nil, err
	}
	p.SetChild(0, child)
```

Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_union_scan.go:80]: Done

Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_union_scan.go:80]: Fixed in b2b4b37421e0df9a0f57ad51d71b80e7a535f824. I adjusted the suggestion to use *LogicalTableDual and return the rewritten child directly.

**Review by winoros — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
