### PR TITLE
topsql: make TestPProfCPUProfile test stable

### LINKED ISSUE #33808: TestPProfCPUProfile test is unstable
## Enhancement

```go
[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-517)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-518)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-519)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-520)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-521)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-522)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-523)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-524)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/#step-73-log-525)[2022-04-07T09:44:13.124Z] [FAIL]  util/topsql/collector TestPProfCPUProfile

[2022-04-07T09:44:13.124Z] err=exit status 1

[2022-04-07T09:44:13.124Z] --- FAIL: TestPProfCPUProfile (1.66s)

[2022-04-07T09:44:13.124Z]     main_test.go:69: 

[2022-04-07T09:44:13.124Z]         	Error Trace:	main_test.go:69

[2022-04-07T09:44:13.124Z]         	Error:      	Not equal: 

[2022-04-07T09:44:13.124Z]         	            	expected: 0

[2022-04-07T09:44:13.124Z]         	            	actual  : 1

[2022-04-07T09:44:13.124Z]         	Test:       	TestPProfCPUProfile

[2022-04-07T09:44:13.124Z] FAIL
```

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44136/pipeline/

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #33808

### Check List

Tests 

- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: util/topsql/collector/main_test.go [hunk 1]
```diff
@@ -63,12 +63,9 @@ func TestPProfCPUProfile(t *testing.T) {
 	require.True(t, len(data) > 0)
 	require.Equal(t, []byte("sql_digest value"), data[0].SQLDigest)
 
-	// Test after disabled, shouldn't receive any data.
+	// Test disable then re-enable.
 	topsqlstate.DisableTopSQL()
 	time.Sleep(interval * 2)
-	require.Equal(t, 0, len(mc.dataCh))
```
Comment (breeswish) [inline util/topsql/collector/main_test.go:69]: Could you explain why is this removed?

Comment (crazycs520) [reply util/topsql/collector/main_test.go:69]: This check actually is meanless, it doesn't affect anything.

Comment (mornyx) [reply util/topsql/collector/main_test.go:69]: When we call `topsqlstate.DisableTopSQL()`, I think there may be unconsumed data in `dataCh`, so we can't guarantee that "re-enable" is in effect.

How about:
```go
	// Test disable then re-enable.
	topsqlstate.DisableTopSQL()
	time.Sleep(interval * 2)
	dataChLen := len(mc.dataCh)
	topsqlstate.EnableTopSQL()
	deltaLen := 0
	for i := 0; i < 10; i++ {
		t1 := time.Now()
		data = <-mc.dataCh
		require.True(t, time.Since(t1) < interval*4)
		if len(data) > 0 {
			deltaLen++
			if deltaLen > dataChLen {
				// Here we can ensure that we receive new data after "re-enable".
				break
			}
		}
	}
```

Comment (zhongzc) [reply util/topsql/collector/main_test.go:69]: It's not a good idea not to check `Test after disabled, shouldn't receive any data.`

Comment (crazycs520) [reply util/topsql/collector/main_test.go:69]: @zhongzc, the current implementation in corner case can't make sure it, and actually we don't need to make sure this behavior, it doesn't matter.

Comment (crazycs520) [reply util/topsql/collector/main_test.go:69]: > ```go
> require.True(t, deltaLen > dataChLen)
> ```

nice catch, done.

**Comment by mornyx** [comment]
LGTM

**Review by zhongzc — APPROVED** [review]

**Review by breeswish — APPROVED** [review]
