### PR TITLE
gctuner: fix goleak in the memoryLimitTuner.tuning

### LINKED ISSUE #41524: goleak in the gctuner.(*memoryLimitTuner).tuning
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 20408 in state sleep, with time.Sleep on top of the stack:
goroutine 20408 [sleep]:
time.Sleep(0xdf8475800)
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/time.go:195 +0x118
github.com/pingcap/tidb/util/gctuner.(*memoryLimitTuner).tuning.func1()
	/Users/weizhenwang/devel/opensource/tidb/util/gctuner/memory_limit_tuner.go:74 +0x10c
created by github.com/pingcap/tidb/util/gctuner.(*memoryLimitTuner).tuning
	/Users/weizhenwang/devel/opensource/tidb/util/gctuner/memory_limit_tuner.go:64 +0x15c
]
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #41524

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

File: util/gctuner/memory_limit_tuner.go [hunk 1]
```diff
@@ -41,6 +42,17 @@ type memoryLimitTuner struct {
 // fallbackPercentage indicates the fallback memory limit percentage when turning.
 const fallbackPercentage float64 = 1.1
 
+var memoryGoroutineCntInTest = *atomicutil.NewInt64(0)
+
+// WaitMemoryLimitTunerExitInTest is used to wait memory limit tuner exit in test.
+func WaitMemoryLimitTunerExitInTest() {
+	if intest.InTest {
+		for memoryGoroutineCntInTest.Load() > 0 {
+			time.Sleep(time.Millisecond)
```
Comment (lance6716) [inline util/gctuner/memory_limit_tuner.go:51]: Maybe 100*time.Millisecond?

**Review by lance6716 — APPROVED** [review]

File: util/gctuner/memory_limit_tuner.go (hunk 1 above)
Comment (hawkingrei) [reply util/gctuner/memory_limit_tuner.go]: updated

**Review by wshwsh12 — APPROVED** [review]
