### PR TITLE
topsql: fix the issue of TiDB doesn't set the request tag for DDL before send RPC request to TiKV

### LINKED ISSUE #33132: TiKV Top SQL failed to catch the CPU of DDL executions
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

just like https://github.com/pingcap/tidb/issues/31434, But this issue is TiDB has DDL CPU data in topsql ui, but TiKV doesn't has DDL cpu executions.

### 4. What is your TiDB version? (Required)

master:  `2dd0074e4ecebebba85b2726cc09f6f0c7e56005 `

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #33132

Problem Summary: This PR fix the issue of TiDB doesn't set the request tag for DDL before send rpc to TiKV.

### What is changed and how it works?

Set the DDL request tag.

Other problem: After this PR, TopSQL still doesn't contain the `scan_row`/`scan_index` data , I will fix this in next PR.

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)

1. create a table and insert 10000000 rows data.

```sql
CREATE TABLE `t_full_table_scan` (
  `a` bigint(20) NOT NULL,
  `b` bigint(20) DEFAULT NULL,
  `c` timestamp(6) NULL DEFAULT NULL,
  `d` varchar(100) DEFAULT NULL,
  `e` decimal(30,8) DEFAULT NULL,
  PRIMARY KEY (`a`)
);
```

3. execute following DDL:

```sql
alter table t_full_table_scan add index idx2 (c,d,b);
alter table t_full_table_scan modify column e decimal(30, 8);
```
4. check the topsql UI in tidb-dashboard.

TiDB:
image

TiKV:
image

### Release note

```release-note
None
```

### CODE REVIEW

File: server/tidb_test.go [hunk 1]
```diff
@@ -1877,13 +1880,37 @@ func TestTopSQLStatementStats(t *testing.T) {
...
 	require.Equal(t, 20, found)
 }
 
-func setupForTestTopSQLStatementStats(t *testing.T) (*tidbTestSuite, stmtstats.StatementStatsMap, chan struct{}, func()) {
+type resourceTagChecker struct {
+	sync.Mutex
+	sqlDigests map[stmtstats.BinaryDigest]struct{}
+}
+
+func (c *resourceTagChecker) checkExist(t *testing.T, digest stmtstats.BinaryDigest, sqlStr string) {
```
Comment (breeswish) [inline server/tidb_test.go:1895]: How about checkExist for all requests happened in the test suite? In this way, when there are new kind of requests, it will be caught.

**Comment by breeswish** [comment]
This PR should not close #33132 since it does not fully resolve the issue.

File: server/tidb_test.go (hunk 1 above)
Comment (zhongzc) [reply server/tidb_test.go:1895]: I have a similar thought: require all requests to contain tags.

**Review by zhongzc — APPROVED** [review]

**Comment by crazycs520** [comment]
> This PR should not close #33132 since it does not fully resolve the issue.

Great, I already changed the issue description.

File: server/tidb_test.go (hunk 1 above)
Comment (crazycs520) [reply server/tidb_test.go:1895]: Not all RPC requests are caused by SQL. So I can't check the all request. But maybe I can check the ALL `cop` kind  RPC request, since as I know, `cop` kind request must cause by SQL.

Comment (breeswish) [reply server/tidb_test.go:1895]: Maybe we can use black lists. In this way, when there are new kind of RPC requests, people must review, check and change the test case in order to pass CI.

**Comment by breeswish** [comment]
> > This PR should not close #33132 since it does not fully resolve the issue.
> 
> Great, I already changed the issue description.

@crazycs520 This is a nice workaround. Just remember to also fix remaining problems. You may like to open new issues to track them.

**Review by breeswish — APPROVED** [review]

File: server/tidb_test.go (hunk 1 above)
Comment (crazycs520) [reply server/tidb_test.go:1895]: I will refine this test in this issue later. https://github.com/pingcap/tidb/issues/33208
