### PR TITLE
*: fix a transaction bug which causes false 'Duplicate entry' error

### LINKED ISSUE #18956: Delete statement reports `ERROR 1062: Duplicate entry`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (
    c_int       int,
    c_double    double,
    c_decimal   decimal(12, 6),
    c_string    varchar(40),
    c_datetime  datetime,
    c_timestamp timestamp,
    c_enum      enum ('a', 'b', 'c', 'd', 'e'),
    c_set       set ('1', '2', '3', '4', '5'),
    c_json      json,
    primary key (c_int),
    unique key (c_string),
    key (c_enum),
    key (c_set),
    key (c_timestamp),
    key (c_datetime),
    key (c_decimal)
);
insert into t (`c_int`, `c_double`, `c_decimal`, `c_string`, `c_datetime`, `c_timestamp`, `c_enum`, `c_set`, `c_json`) values
  (2, 0.029523, 74.040000, 'gold mistress', '2020-01-02 00:00:00', '2019-12-25 03:24:58', 'c', '1,3,5', '{\"datetime\": \"2019-12-26 13:00:00\", \"enum\": \"d\", \"int\": 3, \"set\": \"1,4,5\", \"str\": \"gray koala\"}')
, (4, 0.924873, 35.020000, 'gray witch', '2019-12-26 17:00:00', '2020-01-05 13:01:59', 'd', '1', '{\"datetime\": \"2019-12-30 19:00:00\", \"enum\": \"d\", \"int\": 4, \"set\": \"1,5\", \"str\": \"violet head\"}')
, (5, 0.268598, 59.660000, 'pink fly', '2020-01-04 12:00:00', '2020-01-06 05:33:43', 'd', '1,3,4,5', '{\"datetime\": \"2020-01-04 06:00:00\", \"enum\": \"c\", \"int\": 10, \"set\": \"\", \"str\": \"gold fly\"}')
, (6, 0.551611, 70.960000, 'azure bard', '2020-01-06 02:00:00', '2020-01-07 13:20:29', 'd', '3,4,5', '{\"datetime\": \"2019-12-30 21:00:00\", \"enum\": \"b\", \"int\": 4, \"set\": \"2,5\", \"str\": \"dark kangaroo\"}')
, (7, 0.197616, 9.090000, 'dark curtain', '2020-01-06 02:00:00', '2019-12-30 05:50:54', 'e', '1,2,4', '{\"datetime\": \"2019-12-31 05:00:00\", \"enum\": \"b\", \"int\": 17, \"set\": \"3\", \"str\": \"dark jester\"}')
, (8, 0.515967, 28.090000, 'cyan crown', '2019-12-29 09:00:00', '2019-12-30 00:17:50', 'e', '1,2,3,4,5', '{\"datetime\": \"2020-01-02 22:00:00\", \"enum\": \"d\", \"int\": 19, \"set\": \"4\", \"str\": \"black seer\"}')
, (9, 0.688223, 5.000000, 'gold bard', '2020-01-01 06:00:00', '2019-12-26 14:17:18', 'e', '3', '{\"datetime\": \"2019-12-27 11:00:00\", \"enum\": \"c\", \"int\": 9, \"set\": \"2\", \"str\": \"ivory paladin\"}')
, (10, 0.460531, 11.080000, 'brown cat', '2020-01-01 08:00:00', '2019-12-31 16:51:26', 'd', '2', '{\"datetime\": \"2019-12-28 11:00:00\", \"enum\": \"c\", \"int\": 20, \"set\": \"3\", \"str\": \"crimson tooth\"}')
, (11, 0.360937, 4.630000, 'yellow master', '2019-12-31 15:00:00', '2019-12-31 06:12:42', 'c', '', '{\"datetime\": \"2019-12-29 13:00:00\", \"enum\": \"d\", \"int\": 17, \"set\": \"2,5\", \"str\": \"cyan spider\"}')
, (12, 0.745632, 58.540000, 'yellow kangaroo', '2020-01-01 18:00:00', '2020-01-02 15:50:29', 'b', '1,3', '{\"datetime\": \"2019-12-31 17:00:00\", \"enum\": \"a\", \"int\": 20, \"set\": \"3,4\", \"str\": \"light song\"}')
, (13, 0.203077, 4.870000, 'light fly', '2020-01-03 10:00:00', '2020-01-01 03:05:33', 'c', '1,5', '{\"datetime\": \"2020-01-02 12:00:00\", \"enum\": \"c\", \"int\": 15, \"set\": \"1,3,4,5\", \"str\": \"navy carpet\"}')
, (14, 0.622945, 99.270000, 'white kangaroo', '2019-12-29 13:00:00', '2019-12-26 22:21:32', 'a', '1,2,3,5', '{\"datetime\": \"2019-12-28 03:00:00\", \"enum\": \"b\", \"int\": 18, \"set\": \"2,4,5\", \"str\": \"carnelian kangaroo\"}')
, (15, 0.663324, 17.760000, 'orange kangaroo', '2020-01-01 00:00:00', '2019-12-28 12:57:30', 'c', '1', '{\"datetime\": \"2019-12-25 19:00:00\", \"enum\": \"d\", \"int\": 1, \"set\": \"2,3\", \"str\": \"cream roach\"}')
, (16, 0.218067, 25.030000, 'cyan watcher', '2020-01-01 10:00:00', '2019-12-31 10:36:08', 'd', '3,4,5', '{\"datetime\": \"2019-12-30 03:00:00\", \"enum\": \"d\", \"int\": 3, \"set\": \"4\", \"str\": \"green trader\"}');

begin;
update t set c_decimal = c_decimal + 5 where c_decimal <= 20;
insert into t values (5, 0.157960, 67.26, 'brown cat', '2019-12-28 15:00:00', '2020-01-07 07:22:43', 'c', '1', '{"int":13,"str":"ivory vulture","datetime":"2019-12-31 05:00:00","enum":"b","set":"3,5"}');
delete from t where c_int = 5;
rollback;
```

### 2. What did you expect to see? (Required)

The insert statement should report `ERROR 1062: Duplicate entry`, but the last delete statement shouldn't.

### 3. What did you see instead (Required)

```
mysql> begin;
Query OK, 0 rows affected (0.05 sec)

mysql> update t set c_decimal = c_decimal + 5 where c_decimal <= 20;
Query OK, 6 rows affected (0.05 sec)
Rows matched: 6  Changed: 6  Warnings: 0

mysql> insert into t values (5, 0.157960, 67.26, 'brown cat', '2019-12-28 15:00:00', '2020-01-07 07:22:43', 'c', '1', '{"int":13,"str":"ivory vulture","datetime":"2019-12-31 05:00:00","enum":"b","set":"3,5"}');
ERROR 1062 (23000): Duplicate entry 'brown cat' for key 'c_string'

mysql> delete from t where c_int = 5;
ERROR 1062 (23000): Duplicate entry '5' for key 'PRIMARY'

mysql> rollback;
Query OK, 0 rows affected (0.06 sec)
```

### 4. Affected version (Required)

v4.0.4

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #18956 #19194 

Problem Summary:

In a pessimistic transaction, we set existError and leave the check to lock stage. However, if later we encounter other errors, the existError we set is not correctly reset. Then in the next statement, we may return `Duplicate entry` because of the existError.

### What is changed and how it works?

There are two situations:
1. handle conflict + handle conflict ( insert into t values(1, x, x), (1, x, x))
The key related to the existError set by the first `(1, x, x)` can be got by KeysNeedToLock().
If the statement fails, we use KeysNeedToLock() to get the key and clean it.
2. handle conflict + unique index conflict ( insert into t values(1, 2, x))
Use `txn.CleanupKeyExistErrInfo([]kv.Key{t.RecordKey(recordID)})` to clean it.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- fix a transaction bug which causes false 'Duplicate entry' error

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

File: executor/adapter.go [hunk 1]
```diff
@@ -534,21 +534,22 @@ func (a *ExecStmt) handlePessimisticDML(ctx context.Context, e Executor) error {
 		if !txn.Valid() {
 			return err
 		}
+		keys, err1 := txn.(pessimisticTxn).KeysNeedToLock()
```
Comment (jackysp) [inline executor/adapter.go:537]: Will it lock more keys?

Comment (wjhuang2016) [reply executor/adapter.go:537]: lock?  We don't lock here.

**Review by jackysp — APPROVED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

File: executor/adapter.go [hunk 2]
```diff
@@ -534,21 +534,22 @@ func (a *ExecStmt) handlePessimisticDML(ctx context.Context, e Executor) error {
...
+			return err1
+		}
 		if err != nil {
 			// It is possible the DML has point get plan that locks the key.
 			e, err = a.handlePessimisticLockError(ctx, err)
 			if err != nil {
 				if ErrDeadlock.Equal(err) {
 					metrics.StatementDeadlockDetectDuration.Observe(time.Since(startPointGetLocking).Seconds())
 				}
+				txn.CleanupKeyExistErrInfo(keys)
```
Comment (cfzjywxk) [inline executor/adapter.go:548]: May it mistakenly clean the `PresumeKeyNotExistsError` added by a previous statement, so that this flag is missing at commit phase.

File: table/tables/tables.go [hunk 3]
```diff
@@ -669,6 +669,7 @@ func (t *TableCommon) addIndices(sctx sessionctx.Context, recordID int64, r []ty
 		}
 		if dupHandle, err := v.Create(sctx, rm, indexVals, recordID, opts...); err != nil {
 			if kv.ErrKeyExists.Equal(err) {
+				txn.CleanupKeyExistErrInfo([]kv.Key{t.RecordKey(recordID)})
```
Comment (cfzjywxk) [inline table/tables/tables.go:672]: Could we put the clean operations at one place, not quite sure.

**Comment by bobotu** [comment]
Use a statement-level map and a txn-level map just like what `dirty table` do maybe a better solution?

File: executor/adapter.go (hunk 2 above)
Comment (coocood) [reply executor/adapter.go:548]: For pessimistic transaction, every duplicate keys are checked in the pessimistic lock phase, not in commit phase.

Comment (cfzjywxk) [reply executor/adapter.go:548]: This flag may still be used in the commit phase like deciding if `Op_Insert` should be used for pessimistic transactions. We still need to make sure if it won't be cleared mistakenly.

**Comment by wjhuang2016** [comment]
> Use a statement-level map and a txn-level map just like what `dirty table` do maybe a better solution?

I'm not sure if this statement-level map will incur performance problems.

File: executor/adapter.go (hunk 2 above)
Comment (wjhuang2016) [reply executor/adapter.go:548]: If so, then the key won't be put into the memBuffer?

File: table/tables/tables.go (hunk 3 above)
Comment (bobotu) [reply table/tables/tables.go:672]: This line will introduce a new bug in optimistic txn. Here is an example
```sql
create table t (pk int primary key, uk int unique);
insert into t values (1, 2);

begin optimistic;
insert into t values (1, 4);
update t set pk = 2 where uk = 4; -- Duplicate entry '4' for key 'uk'
insert into t values (1, 4);
insert into t values (1, 5);
commit; -- no error

admin check table t; -- ERROR 1105 (HY000): col uk, handle 1, index:types.Datum{k:0x1, collation:"", decimal:0x0, length:0x0, i:2, b:[]uint8(nil), x:interface {}(nil)} != record:types.Datum{k:0x1, collation:"", decimal:0x0, length:0x0, i:5, b:[]uint8(nil), x:interface {}(nil)}
```

**Review by bobotu — CHANGES_REQUESTED** [review]

**Comment by bobotu** [comment]
> 
> 
> > Use a statement-level map and a txn-level map just like what `dirty table` do maybe a better solution?
> 
> I'm not sure if this statement-level map will incur performance problems.

I think correctness is more important than performance. There are actually some potential problems in this patch

1. Optimistic txn have the same problem like #18956, if the execution aborted by memory quota or something.
2. Potential edge cases are difficult to construct, the SQLs I have post is an example.

I hope ths fix can be implemented in the logical semantic instead of specialize it to some **optimized trick**, because it is really hard to debug.

The last reason is, memdb on master support stmt level `PersumeKeyNotExist` buffer, we'd better use the same logic in 4.0 branch to make it easier to maintain.

**Review by bobotu — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by bobotu — APPROVED** [review]
LGTM
