### PR TITLE
ttl: use a pessimistic transaction to finish the job

### LINKED ISSUE #56422: TTL Task will not be canceled if facing write conflict
## Bug Report

See the following function:

```
// finish turns current job into last job, and update the error message and statistics summary
func (job *ttlJob) finish(se session.Session, now time.Time, summary *TTLSummary) {
	// at this time, the job.ctx may have been canceled (to cancel this job)
	// even when it's canceled, we'll need to update the states, so use another context
	err := se.RunInTxn(context.TODO(), func() error {
		sql, args := finishJobSQL(job.tbl.ID, now, summary.SummaryText, job.id)
...
		sql, args = removeTaskForJob(job.id)
...
		sql, args = finishJobHistorySQL(job.id, now, summary)
,,,
		return nil
	}, session.TxnModeOptimistic)

	if err != nil {
		logutil.BgLogger().Error("fail to finish a ttl job", zap.Error(err), zap.Int64("tableID", job.tbl.ID), zap.String("jobID", job.id))
	}
}
```

It'll update records in three tables: `tidb_ttl_table_status`, `tidb_ttl_task` and `tidb_ttl_job_history`. It's usually fine to write to `tidb_ttl_table_status` and `tidb_ttl_job_history`, because the `job_manager ` always holds the owner and runs as a single goroutine, but it may have conflict to write to `tidb_ttl_task`.

When it faces a write conflict error, the job will be forgot by the job manager, and nobody will update the status, clean the tasks and update the history again.

The `DoGC` didn't work because it cleans the tasks using the following SQL:

```sql
DELETE task FROM
		mysql.tidb_ttl_task task
	left join
		mysql.tidb_ttl_table_status job
	ON task.job_id = job.current_job_id
	WHERE job.table_id IS NULL
```

If the `tidb_ttl_table_status` is not updated, the `tidb_ttl_task` will also not be cleaned.

Therefore, I propose to execute this transaction in pessimistic mode. (Actually, it's not necessary to execute them in a single transaction. They are safe to be executed one-by-one.)

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #56422

Problem Summary:

When the job is finished, and at the same time the task is assigned to some TiDB node, it may fail to finish the job.

### What changed and how does it work?

Use the pessimistic transaction to finish job. Then the `DELETE ... FROM tidb_ttl_tasks` will block `UPDATE mysql.tidb_ttl_task SET owner_id = ?...` (or in another direction).

If the ttl task is removed, it'll finally be removed by `(m *taskManager) checkInvalidTask` in the memory.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that a TTL job cannot be finished in some situation.
```

### CODE REVIEW

File: pkg/ttl/ttlworker/job.go [hunk 1]
```diff
@@ -146,8 +146,9 @@ func (job *ttlJob) finish(se session.Session, now time.Time, summary *TTLSummary
 		}
 
 		return nil
-	}, session.TxnModeOptimistic)
+	}, session.TxnModePessimistic)
```
Comment (lcwangchao) [inline pkg/ttl/ttlworker/job.go:149]: Tough it can reduce the issue but cannot fully fix it because some other cases can also cause the sql execution failed, i.e network failure. Should we also finish the job first before we remove it from memory, if the finish fails, it will try it again next time.

https://github.com/pingcap/tidb/blob/1e24d39608214cc463c1de913e9a308be1c8193c/pkg/ttl/ttlworker/job_manager.go#L561-L562

Comment (YangKeao) [reply pkg/ttl/ttlworker/job.go:150]: Done.

**Review by lcwangchao — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
