### PR TITLE
*: fix nil pointer panic of some operations when skip-grant-table is true

### LINKED ISSUE #29317: execute privilege related SQL failed in TiDB server when security.skip-grant-table=true
## Bug Report

Please answer these questions before submitting your issue. Thanks!

#### background

I want to execute some `create user` and `grant privilege` SQL in the TiDB server which config `security.skip-grant-table=true`, but I meet some errors.

#### reproduce

1. start a TiDB server with `security.skip-grant-table=true`.
2. execute the following SQL in the TiDB server which `security.skip-grant-table=true`:

```sql
CREATE USER 'test1'@'%';
GRANT BACKUP_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTORE_ADMIN ON *.* TO 'test1'@'%';
GRANT RELOAD ON *.* TO 'test1'@'%';
GRANT SHUTDOWN ON *.* TO 'test1'@'%';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_VARIABLES_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_STATUS_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_CONNECTION_ADMIN, CONNECTION_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_USER_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_TABLES_ADMIN ON *.* TO 'test1'@'%';
GRANT PROCESS ON *.* TO 'test1'@'%';
GRANT SHUTDOWN ON *.* TO 'test1'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON mysql.* TO 'test1'@'%';
GRANT SELECT ON information_schema.* TO 'test1'@'%';
GRANT SELECT ON performance_schema.* TO 'test1'@'%';
GRANT ALL PRIVILEGES ON *.* TO root;
revoke SHUTDOWN on *.* from root;
revoke CONFIG on *.* from root;


CREATE USER 'test2'@'%' IDENTIFIED BY '12345';
GRANT PROCESS, CONFIG ON *.* TO 'test2'@'%';
GRANT SHOW DATABASES ON *.* TO 'test2'@'%';
GRANT DASHBOARD_CLIENT ON *.* TO 'test2'@'%';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_VARIABLES_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_STATUS_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_TABLES_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_USER_ADMIN ON *.* TO 'test2'@'%';
```

you will meet some errors, such as:

```sql
(none)> CREATE USER 'test'@'%';
(1396, "Operation CREATE USER failed for 'test'@'%'")
(none)> SHOW GRANTS FOR CURRENT_USER();
(1141, "There is no such grant defined for user 'root' on host '%'")
(none)> GRANT DASHBOARD_CLIENT ON *.* TO 'root'@'%';  -- TiDB server panic!!!
(1105, 'runtime error: invalid memory address or nil pointer dereference')
```

### 2. What did you expect to see? (Required)

Execute success.

### 3. What did you see instead (Required)

Execute failed.

### 4. What is your TiDB version? (Required)

```sql
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.3.0-alpha-1292-g4b6291f45
Edition: Community
Git Commit Hash: 4b6291f45cb2f34833ffa4d066b628bc197c25a3
Git Branch: master
UTC Build Time: 2021-11-01 09:28:59
GoVersion: go1.16.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #29317

Problem Summary:

When `skip-grant-table` is configured, some operation panic.

### What is changed and how it works?

Check `config.GetGlobalConfig().Security.SkipGrantTable` in `NotifyUpdatePrivilege`, if it's set, do nothing to avoid nil pointer panic.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix nil pointer panic of some operations when `skip-grant-table` is true
```

### CODE REVIEW

File: domain/domain.go [hunk 1]
```diff
@@ -1446,6 +1446,13 @@ const (
 // NotifyUpdatePrivilege updates privilege key in etcd, TiDB client that watches
 // the key will get notification.
 func (do *Domain) NotifyUpdatePrivilege() error {
+	// If skip-grant-table is configured, do not flush privileges.
+	// Because LoadPrivilegeLoop does not run and the privilege Handle is nil,
+	// Call dom.PrivilegeHandle().Update would panic.
```
Comment (gregwebs) [inline domain/domain.go:1451]:
```suggestion
	// the call to do.PrivilegeHandle().Update would panic.
```

**Review by gregwebs — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]

**Comment by crazycs520** [comment]
I still get the following error in `tidb-server` which use `skip-grant-table=true`, but I'm not sure how to fix it, but I think we can handle this problem in another PR.

```sql
▶ mysql -u user_not_exist -h 127.0.0.1 -P 4000
mysql> show grants for current_user();
ERROR 1141 (42000): There is no such grant defined for user 'root' on host '%'
```

**Review by wjhuang2016 — APPROVED** [review]
