### PR TITLE
executor: add test for same table name in two schemas

### LINKED ISSUE #55221: `information_schema.tables` return wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create database test1;
create database test2;
create table test1.t (a int);
create table test2.t (a int);

select table_schema, table_name, tidb_table_id from information_schema.tables where tidb_table_id = 108;
```

### 2. What did you expect to see? (Required)

There should be one row.

### 3. What did you see instead (Required)

Two rows with same table ID but different schema names.

### 4. What is your TiDB version? (Required)

19856622942a

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #55221

Problem Summary:

### What changed and how does it work?

- Check if table ID is consistent after getting from schema.
- Add a test for the issue.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

File: pkg/planner/core/memtable_infoschema_extractor.go [hunk 1]
```diff
@@ -444,15 +444,23 @@ func listTablesForEachSchema(
...
+) ([]model.CIStr, []*model.TableInfo, error) {
 	schemaSlice := make([]model.CIStr, 0, len(tableSlice))
 	for i, tbl := range tableSlice {
 		found := false
 		for _, s := range schemas {
-			if is.TableExists(s, tbl.Name) {
+			isTbl, err := is.TableByName(ctx, s, tbl.Name)
+			if err != nil {
+				if terror.ErrorEqual(err, infoschema.ErrTableNotExists) {
+					continue
```
Comment (AilinKid) [inline pkg/planner/core/memtable_infoschema_extractor.go:459]: why can we tolerate the TableNotExist error here?

**Review by AilinKid — APPROVED** [review]
