### PR TITLE
expression: pass the arg's nullable type to target type for cast function

### LINKED ISSUE #31399: TiDB drops the nullable type info when implicit cast happen for bit functions
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t2(a int primary key,b bigint);
alter table t2 set tiflash replica 1;
insert into t2 values(1,2);
insert into t2 values(2,3);
insert into t2 values(3,null);
set @@tidb_enforce_mpp=on;
select count(*) from t2 group by a having bit_and(b) >1;

### 2. What did you expect to see? (Required)
expect 1,1,1
### 3. What did you see instead (Required)
but got 
-- ERROR 1105 (HY000): Cannot convert NULL value to non-Nullable type
### 4. What is your TiDB version? (Required)
Release Version: v5.4.0-alpha-662-g8d133648f-dirty
Edition: Community
Git Commit Hash: 8d133648fcd3151350488b5ccb3d125fe8e9d566
Git Branch: master
UTC Build Time: 2022-01-06 11:23:45
GoVersion: go1.16
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #31399

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by fzhedu** [comment]
add tests pls.

File: planner/core/rule_aggregation_elimination.go [hunk 1]
```diff
@@ -208,6 +208,9 @@ func wrapCastFunction(ctx sessionctx.Context, arg expression.Expression, targetT
 	if arg.GetType().Equal(targetTp) {
 		return arg
 	}
+	if !mysql.HasNotNullFlag(arg.GetType().Flag) {
+		targetTp.Flag &= ^mysql.NotNullFlag
+	}
```
Comment (fzhedu) [inline planner/core/rule_aggregation_elimination.go:213]: add a comment

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by chrysan — APPROVED** [review]
LGTM

File: expression/builtin_cast.go [hunk 2]
```diff
@@ -1840,6 +1840,11 @@ func BuildCastCollationFunction(ctx sessionctx.Context, expr Expression, ec *Exp
 
 // BuildCastFunction builds a CAST ScalarFunction from the Expression.
 func BuildCastFunction(ctx sessionctx.Context, expr Expression, tp *types.FieldType) (res Expression) {
+	argType := expr.GetType()
+	// If source argument's nullable, then target type should be nullable
+	if !mysql.HasNotNullFlag(argType.Flag) {
+		tp.Flag &= ^mysql.NotNullFlag
+	}
```
Comment (chrysan) [inline expression/builtin_cast.go:1847]: Looks like we have a similar problem in other functions, like coalesce, if... you can double-check.
Prefer to define an interface like "nullable(args []Expression) bool" and force every function to implement it. So that next time we add a new function, we won't forget to consider the null handling.

Comment (yibin87) [reply expression/builtin_cast.go:1847]: Nice comments, I'll discuss it with @fzhedu.

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by xiongjiwei** [comment]
this pr has also fix https://github.com/pingcap/tidb/issues/36398. Please help cherry-pick

**Comment by yibin87** [comment]
I see, I'll do it later.
