### PR TITLE
*: upgrade gomod to fix data race

### LINKED ISSUE #34511: DATA RACE in the tikv/client-go.SetRPCInterceptor
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c001e118e0 by goroutine 123:
  github.com/tikv/client-go/v2/txnkv/txnsnapshot.(*KVSnapshot).SetRPCInterceptor()
      /home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/txnkv/txnsnapshot/snapshot.go:763 +0x82a
  github.com/pingcap/tidb/store/driver/txn.(*tikvSnapshot).SetOption()
      /go/tidb/store/driver/txn/snapshot.go:125 +0x7de
  github.com/pingcap/tidb/executor.setOptionForTopSQL()
      /go/tidb/executor/executor.go:2018 +0xd0
  github.com/pingcap/tidb/executor.(*BatchPointGetExec).Open()
      /go/tidb/executor/batch_point_get.go:156 +0xe50
  github.com/pingcap/tidb/executor.(*UnionExec).resultPuller()
      /go/tidb/executor/executor.go:1660 +0x3d4
  github.com/pingcap/tidb/executor.(*UnionExec).initialize.func1()
      /go/tidb/executor/executor.go:1627 +0x64
Previous write at 0x00c001e118e0 by goroutine 111:
  github.com/tikv/client-go/v2/txnkv/txnsnapshot.(*KVSnapshot).SetRPCInterceptor()
      /home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/txnkv/txnsnapshot/snapshot.go:763 +0x82a
  github.com/pingcap/tidb/store/driver/txn.(*tikvSnapshot).SetOption()
      /go/tidb/store/driver/txn/snapshot.go:125 +0x7de
  github.com/pingcap/tidb/executor.setOptionForTopSQL()
      /go/tidb/executor/executor.go:2018 +0xd0
  github.com/pingcap/tidb/executor.(*BatchPointGetExec).Open()
      /go/tidb/executor/batch_point_get.go:156 +0xe50
  github.com/pingcap/tidb/executor.(*UnionExec).resultPuller()
      /go/tidb/executor/executor.go:1660 +0x3d4
  github.com/pingcap/tidb/executor.(*UnionExec).initialize.func1()
      /go/tidb/executor/executor.go:1627 +0x64
Goroutine 123 (running) created at:
  github.com/pingcap/tidb/executor.(*UnionExec).initialize()
      /go/tidb/executor/executor.go:1627 +0x4d0
  github.com/pingcap/tidb/executor.(*UnionExec).Next()
      /go/tidb/executor/executor.go:1703 +0xc4
  github.com/pingcap/tidb/executor.Next()
      /go/tidb/executor/executor.go:306 +0x5af
  github.com/pingcap/tidb/executor.(*recordSet).Next()
      /go/tidb/executor/adapter.go:151 +0x134
  github.com/pingcap/tidb/session.(*execStmtResult).Next()
      <autogenerated>:1 +0x76
  github.com/pingcap/tidb/session.GetRows4Test()
      /go/tidb/session/tidb.go:333 +0xea
  github.com/pingcap/tidb/session.ResultSetToStringSlice()
      /go/tidb/session/tidb.go:351 +0xb9
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResultWithCtx()
      /go/tidb/testkit/testkit.go:169 +0xb5
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResult()
      /go/tidb/testkit/testkit.go:164 +0x266
  github.com/pingcap/tidb/testkit.(*TestKit).MustQuery()
      /go/tidb/testkit/testkit.go:104 +0x26c
  github.com/pingcap/tidb/planner/core_test.TestBatchPointGetTablePartition()
      /go/tidb/planner/core/cbo_test.go:855 +0x357
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47
Goroutine 111 (running) created at:
  github.com/pingcap/tidb/executor.(*UnionExec).initialize()
      /go/tidb/executor/executor.go:1627 +0x4d0
  github.com/pingcap/tidb/executor.(*UnionExec).Next()
      /go/tidb/executor/executor.go:1703 +0xc4
  github.com/pingcap/tidb/executor.Next()
      /go/tidb/executor/executor.go:306 +0x5af
  github.com/pingcap/tidb/executor.(*recordSet).Next()
      /go/tidb/executor/adapter.go:151 +0x134
  github.com/pingcap/tidb/session.(*execStmtResult).Next()
      <autogenerated>:1 +0x76
  github.com/pingcap/tidb/session.GetRows4Test()
      /go/tidb/session/tidb.go:333 +0xea
  github.com/pingcap/tidb/session.ResultSetToStringSlice()
      /go/tidb/session/tidb.go:351 +0xb9
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResultWithCtx()
      /go/tidb/testkit/testkit.go:169 +0xb5
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResult()
      /go/tidb/testkit/testkit.go:164 +0x266
  github.com/pingcap/tidb/testkit.(*TestKit).MustQuery()
      /go/tidb/testkit/testkit.go:104 +0x26c
  github.com/pingcap/tidb/planner/core_test.TestBatchPointGetTablePartition()
      /go/tidb/planner/core/cbo_test.go:855 +0x357
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #34511

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/pessimistictest/pessimistic_test.go [hunk 1]
```diff
@@ -158,7 +158,7 @@ func createMockStoreAndSetup(t *testing.T, opts ...mockstore.MockTiKVStoreOption
 	return store, func() {
 		dom.Close()
 		require.NoError(t, store.Close())
-		transaction.PrewriteMaxBackoff = 20000
+		transaction.PrewriteMaxBackoff.Store(20000)
```
Comment (tiancaiamao) [inline tests/pessimistictest/pessimistic_test.go:161]: It should be safe already after `dom.Close`?
No transaction should be using `transaction.PrewriteMaxBackoff` unless there is a leaked goroutine.

Comment (hawkingrei) [reply tests/pessimistictest/pessimistic_test.go:161]: Yes, I agree. but this is the mistake of design. Client-go classmate says ```PrewriteMaxBackoff``` is a parameter to use in the test so that it is public to use. it should consider concurrent scenarios to avoid the data race. Become atomic, which can prevent this kind of problem from happening.

**Review by sticnarf — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Review by disksing — APPROVED** [review]
