### PR TITLE
variable: unifiy MaxExecuteTime usage and fix some problem

### LINKED ISSUE #50872: tidb_stats_load_sync_wait Parameter does not take effect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
set global tidb_stats_load_sync_wait=30000;


### 2. What did you expect to see? (Required)

execute SQL need to wait 30 seconds

### 3. What did you see instead (Required)

SQL return result in 3 seconds, ****and report a warning :**   sync load stats timeout**

### 4. What is your TiDB version? (Required)

MySQL [lifedata]> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.5.0
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-24 08:50:14
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

### LINKED ISSUE #50914: somewhere `max_execute_time` is not properly used when  sql hint `max_execute_time` is set
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

For example: https://github.com/pingcap/tidb/blob/9bad2027d535279c47aee0fa3ea99401c9948fff/pkg/planner/core/plan_stats.go#L103-L112

if sql hint `max_execute_time` is set, then session variable `max_execute_time` should be ignored.

and https://github.com/pingcap/tidb/blob/9bad2027d535279c47aee0fa3ea99401c9948fff/pkg/expression/builtin_info.go#L940:

sql hint `max_execute_time` is not considered.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: close #50914, close #50872

Problem Summary:

### What changed and how does it work?

1. provide a Function `GetMaxExecutionTime` for `SessionVars`.
2. Fix two potential bug, caused by not properly used `MaxExecutionTime`, one about `plan_stats`，the other `expression/build_in`.
3. Fix a bug related with `tidb_stats_load_sync_wait`
4. unify code for `GetMaxExecutionTime`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by jiyfhust** [comment]
@YangKeao Could you take a look at this? I is a more like a code unifiy enfencement.

File: pkg/planner/core/plan_stats.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func (collectPredicateColumnsPoint) optimize(_ context.Context, plan LogicalPlan
 		return plan, planChanged, nil
 	}
 	predicateNeeded := variable.EnableColumnTracking.Load()
-	syncWait := plan.SCtx().GetSessionVars().StatsLoadSyncWait * time.Millisecond.Nanoseconds()
```
Comment (winoros) [inline pkg/planner/core/plan_stats.go:41]: This change is not about the max execution time, just wrong time unit is used?

Comment (jiyfhust) [reply pkg/planner/core/plan_stats.go:41]: Yes, it fix issue #50872.

**Comment by jiyfhust** [comment]
PTAL @winoros @hawkingrei @qw4990

**Comment by jiyfhust** [comment]
brothers, look look.

**Comment by jiyfhust** [comment]
@qw4990 
PTAL PTAL PTAL

**Review by qw4990 — APPROVED** [review]

**Comment by jiyfhust** [comment]
> please assign [yudongusa](https://github.com/yudongusa), [zanmato1984](https://github.com/zanmato1984) for approval

Can you take a look at this, thanks. @zanmato1984

**Review by windtalker — APPROVED** [review]
LGTM
