### PR TITLE
charset: add missing ascii check(close #17375)

### LINKED ISSUE #17375: charset: TiDB missed character validation for `ASCII` charset
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
tidb> create table t(a varchar(10)) charset ascii;
Query OK, 0 rows affected (0.13 sec)

tidb> insert into t values ('我');
```

### 2. What did you expect to see? (Required)
```
tidb> insert into t values ('我');
ERROR 1366 (HY000): Incorrect string value: '\xE6\x88\x91' for column 'a' at row 1
```

### 3. What did you see instead (Required)
```
tidb> insert into t values ('我');
Query OK, 1 row affected (0.04 sec)
```

### 4. Affected version (Required)
All versions of TiDB

### 5. Root Cause Analysis
The check is missed.

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #17375 

### What is changed and how it works?

This PR/commit add a simple loop to check non-ASCII chars with a charset of ASCII.

### Related changes

None

### Check List

Tests

- Integration test

### Release note

- ASCII charset character validation

### CODE REVIEW

**Comment by bb7133** [comment]
Hi @xhebox , thanks for your contribution!

This is a potential compatibility breaker for existing TiDB users, so I put a label on it, it is not related to your codes, thanks anyway!

File: table/column.go [hunk 1]
```diff
@@ -203,6 +213,21 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
...
+
+	if col.Charset == charset.CharsetASCII {
+		str := casted.GetString()
+		for i := 0; i < len(str); i++ {
+			if str[i] > unicode.MaxASCII {
+				casted, err = handleWrongASCIIValue(ctx, col, &casted, str, i)
+				break
+			}
+		}
+		if forceIgnoreTruncate {
```
Comment (bb7133) [inline table/column.go:225]: Would you please add a test for this?

Comment (xhebox) [reply table/column.go:225]: Done

Comment (wjhuang2016) [reply table/column.go:225]: It happens in virtual generated column.
Here is the test:
create table t(a char(10) charset utf8);
insert into t values('我');
alter table t add column b char(10) as ((a)) charset ascii;
select * from t;

Comment (xhebox) [reply table/column.go:225]: OK... I missed that. I never touched SQL or database things.

Those statements will cause an SQL syntax error near `charset ascii`. It took me some time to figure out the correct SQL statements and test it out.

**Comment by xhebox** [comment]
@wjhuang2016 SkipASCIICheck added. But I am not sure if there is something i missed.

File: table/column.go (hunk 1 above)
Comment (wjhuang2016) [reply table/column.go:225]: Sorry about that.

**Comment by wjhuang2016** [comment]
@xhebox We will try to merge it ASAP.

**Comment by xhebox** [comment]
@wjhuang2016 Appreciate. Glad to hear that. :)

So the official mysql test failed(related mysql 8.0 test code [here](https://github.com/mysql/mysql-server/blob/8.0/mysql-test/t/insert_update.test#L270-L274)). And the test treats the invalid ASCII bytes insertion as a warning rather than an error. I assume that the error is expected and should be fixed in the internal Jenkins repo.

But I have no idea on that data race error. It seems unrelated.

File: table/column.go [hunk 2]
```diff
@@ -200,9 +210,28 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
 		truncateTrailingSpaces(&casted)
 	}
 
+	if col.Charset == charset.CharsetASCII {
+		if ctx.GetSessionVars().SkipASCIICheck {
```
Comment (bb7133) [inline table/column.go:214]: Please add a test for this variable, rest LGTM.

Comment (xhebox) [reply table/column.go:214]: Added, and this is the output in case that the jenkins test failed.
```
PASS: statement_context_test.go:32: testSuite1.TestStatementContext     0.055s
```

**Comment by bb7133** [comment]
Hi @xhebox , this PR is ready for merge, thanks for your contribution!
