### PR TITLE
ddl: avoid commit conflicts when updating/delete from mysql.tidb_ddl_reorg.

### LINKED ISSUE #38669: modify column on partitioned table does not give warning about truncated rows.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
set sql_mode = default;
create table t (a varchar(255)) partition by range columns (a) (partition p1 values less than ("0"), partition p2 values less than ("zzzzzz"));
insert into t values ("123456");
alter table t modify a varchar(5);
set sql_mode = '';
alter table t modify a varchar(5);
show warnings;
```

### 2. What did you expect to see? (Required)
**Note the change in p1 partition definition, leading to the truncated value is in first partition!**
```sql
tidb> create table t (a varchar(255)) partition by range columns (a) (partition p1 values less than ("2"), partition p2 values less than ("zzzzzz"));
--------------
create table t (a varchar(255)) partition by range columns (a) (partition p1 values less than ("2"), partition p2 values less than ("zzzzzz"))
--------------

Query OK, 0 rows affected (0.16 sec)

tidb> insert into t values ("123456");
--------------
insert into t values ("123456")
--------------

Query OK, 1 row affected (0.02 sec)

tidb> alter table t modify a varchar(5);
--------------
alter table t modify a varchar(5)
--------------

ERROR 1265 (01000): Data truncated for column 'a', value is '123456'
tidb> set sql_mode = '';
--------------
set sql_mode = ''
--------------

Query OK, 0 rows affected (0.00 sec)

tidb> alter table t modify a varchar(5);
--------------
alter table t modify a varchar(5)
--------------

Query OK, 0 rows affected, 1 warning (2.96 sec)

tidb> show warnings;
--------------
show warnings
--------------

+---------+------+--------------------------------------------------+
| Level   | Code | Message                                          |
+---------+------+--------------------------------------------------+
| Warning | 1265 | Data truncated for column 'a', value is '123456' |
+---------+------+--------------------------------------------------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
tidb> create table t (a varchar(255)) partition by range columns (a) (partition p1 values less than ("0"), partition p2 values less than ("zzzzzz"));
--------------
create table t (a varchar(255)) partition by range columns (a) (partition p1 values less than ("0"), partition p2 values less than ("zzzzzz"))
--------------

Query OK, 0 rows affected (0.12 sec)

tidb> insert into t values ("123456");
--------------
insert into t values ("123456")
--------------

Query OK, 1 row affected (0.05 sec)

tidb> alter table t modify a varchar(5);
--------------
alter table t modify a varchar(5)
--------------

ERROR 1265 (01000): Data truncated for column 'a', value is '123456'
tidb> set sql_mode = '';
--------------
set sql_mode = ''
--------------

Query OK, 0 rows affected (0.00 sec)

tidb> alter table t modify a varchar(5);
--------------
alter table t modify a varchar(5)
--------------

Query OK, 0 rows affected (3.06 sec)

tidb> show warnings;
--------------
show warnings
--------------

Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

tidb_version(): Release Version: v6.4.0-alpha
Edition: Community
Git Commit Hash: 753e3da26af53be093ea74311ee9a13f50cbb9da
Git Branch: heads/refs/tags/v6.4.0-alpha
UTC Build Time: 2022-10-26 14:24:52
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #38669, https://github.com/pingcap/tidb/issues/24427

Problem Summary:

Root cause of the issue is that in HandleDDLJobTable it will
1) start a new transaction
2) call runReorgJob for reorganization work, which can update mysql.tidb_ddl_reorg table in a new transaction, for 'savepoints' in case of crash, so it can continue instead of having to restart from the beginning.
3) when runReorgJob returns it will delete the job from mysql.tidb_ddl_reorg and commit the transaction started in 1) and if 2) did update the same table, this is where the commit conflict will occur, resulting in updates to reorg_meta will not be committed and the warnings and other updates will be lost.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/column.go [hunk 1]
```diff
@@ -1274,8 +1274,8 @@ func (w *updateColumnWorker) getRowRecord(handle kv.Handle, recordKey []byte, ra
 	if err != nil {
 		return w.reformatErrors(err)
 	}
-	if w.sessCtx.GetSessionVars().StmtCtx.GetWarnings() != nil && len(w.sessCtx.GetSessionVars().StmtCtx.GetWarnings()) != 0 {
-		warn := w.sessCtx.GetSessionVars().StmtCtx.GetWarnings()
+	warn := w.sessCtx.GetSessionVars().StmtCtx.GetWarnings()
```
Comment (mjonss) [inline ddl/column.go:1277]: Since GetWarnings takes a mutex and copies the data, it is better to only do it once instead of up to three times.

File: ddl/column.go [hunk 2]
```diff
@@ -1359,8 +1359,9 @@ func (w *updateColumnWorker) BackfillDataInTxn(handleRange reorgBackfillTask) (t
 		taskCtx.nextKey = nextKey
 		taskCtx.done = taskDone
 
-		warningsMap := make(map[errors.ErrorID]*terror.Error, len(rowRecords))
-		warningsCountMap := make(map[errors.ErrorID]int64, len(rowRecords))
+		// Optimize for few warnings!
```
Comment (mjonss) [inline ddl/column.go:1362]: I think it is better to avoid reserving too much memory that may not be needed.
On the other hand it will be a single allocation instead of multiple ones when resizing the maps.

File: parser/model/ddl.go [hunk 3]
```diff
@@ -595,6 +595,9 @@ func (job *Job) String() string {
 	rowCount := job.GetRowCount()
 	ret := fmt.Sprintf("ID:%d, Type:%s, State:%s, SchemaState:%s, SchemaID:%d, TableID:%d, RowCount:%d, ArgLen:%d, start time: %v, Err:%v, ErrCount:%d, SnapshotVersion:%v",
 		job.ID, job.Type, job.State, job.SchemaState, job.SchemaID, job.TableID, rowCount, len(job.Args), TSConvert2Time(job.StartTS), job.Error, job.ErrorCount, job.SnapshotVer)
+	if job.ReorgMeta != nil {
+		ret += fmt.Sprintf(", UniqueWarnings:%d", len(job.ReorgMeta.Warnings))
```
Comment (mjonss) [inline parser/model/ddl.go:599]: Just to be able to trace the warnings as well.

File: ddl/reorg.go [hunk 4]
```diff
@@ -742,6 +745,35 @@ func getReorgInfoFromPartitions(ctx *JobContext, d *ddlCtx, rh *reorgHandler, jo
...
+	if err != nil {
+		return errors.Trace(err)
+	}
+	txn, err := sess.txn()
+	if err != nil {
+		sess.rollback()
+		return errors.Trace(err)
+	}
+	rh := newReorgHandler(meta.NewMeta(txn), sess, variable.EnableConcurrentDDL.Load())
+	err = rh.RemoveDDLReorgHandle(r.Job, r.elements)
```
Comment (zimulala) [inline ddl/reorg.go:769]: If this `err` is not nil, do we need to do `rollback`?

**Comment by Defined2014** [comment]
I think this PR also fixed https://github.com/pingcap/tidb/issues/24427, maybe we could linked them.

**Review by Defined2014 — APPROVED** [review]

File: ddl/reorg.go [hunk 5]
```diff
@@ -248,7 +248,10 @@ func (w *worker) runReorgJob(rh *reorgHandler, reorgInfo *reorgInfo, tblInfo *mo
 		}
 
 		updateBackfillProgress(w, reorgInfo, tblInfo, 0)
-		if err1 := rh.RemoveDDLReorgHandle(job, reorgInfo.elements); err1 != nil {
+
+		// Do this is a separate transaction, since mysql.tidb_ddl_reorg may have been updated
+		// by the inner function and could result in commit conflicts.
+		if err1 := reorgInfo.deleteReorgMeta(w.sessPool); err1 != nil {
```
Comment (tangenta) [inline ddl/reorg.go:254]: It is possible that the transaction in (1 fails due to a retryable error. If we delete the reorg handle in a separate transaction, the whole reorg work will be restarted in the next loop because the reorg handle could not be found. For the tables with millions of rows, it could be unacceptable :(

Maybe we can record the reorg state to the memory struct like `reorgCtx`. 
- When the reorg work is completed, update this field. 
- Check this field before starting a reorg work.

However, this approach still cannot handle the cases like "TiDB crash" or "DDL owner change".

**Comment by mjonss** [comment]
@zimulala, @tangenta and @Defined2014 thank you for your reviews and insightful comments and questions. Would any of you have time to take over this PR/Issue? I will not have time until some time next week to address the issues and move forward.

File: ddl/reorg.go (hunk 4 above)
Comment (mjonss) [reply ddl/reorg.go]: I changed the implementation, so it will remove entries for the job in a separate transaction when the job is finished. In case the cleanup fails, it will now only log it.

File: ddl/reorg.go (hunk 5 above)
Comment (mjonss) [reply ddl/reorg.go]: I changed the implementation so it will cleanup the tidb_ddl_reorg entries for the job when the job is completed. There is still a small chance that the cleanup will not happen (in case of crash in a very limited time window). I think it is good enough, otherwise we could instead delete all orphan job_ids from tidb_ddl_reorg, so it will be cleaned up when the next job finishes. (like `select job_id from mysql.tidb_ddl_reorg where job_id not in (select job_id from tidb_ddl_job)`)

**Comment by mjonss** [comment]
@tangenta @zimulala @Defined2014 I have updated the PR, please review it.

File: ddl/concurrentddltest/switch_test.go [hunk 6]
```diff
@@ -70,8 +70,9 @@ func TestConcurrentDDLSwitch(t *testing.T) {
 		}
 	}
 
-	c := atomic.NewInt32(0)
-	ch := make(chan struct{})
+	ddlDoneCnt := atomic.NewInt32(0)
```
Comment (wjhuang2016) [inline ddl/concurrentddltest/switch_test.go:73]: this test would be removed soon.

File: ddl/ddl_worker.go [hunk 7]
```diff
@@ -779,6 +779,7 @@ func (w *worker) HandleJobDone(d *ddlCtx, job *model.Job, t *meta.Meta) error {
 	if err != nil {
 		return err
 	}
+	CleanupDDLReorgHandles(job, w.sessPool, w.concurrentDDL)
```
Comment (wjhuang2016) [inline ddl/ddl_worker.go:782]: CleanupDDLReorgHandles is enough? No need in HandleDDLJobTable?

File: ddl/reorg.go [hunk 8]
```diff
@@ -838,6 +835,55 @@ func (r *reorgHandler) RemoveDDLReorgHandle(job *model.Job, elements []*meta.Ele
...
+		logutil.BgLogger().Info("CleanupDDLReorgHandles new session failed", zap.Error(err))
+		return
+	}
+	txn, err := sess.txn()
+	if err != nil {
+		logutil.BgLogger().Info("CleanupDDLReorgHandles new txn failed", zap.Error(err))
+		sess.rollback()
+	}
+	if concurrentDDL {
+		err = cleanDDLReorgHandles(sess, job)
```
Comment (wjhuang2016) [inline ddl/reorg.go:865]: can the job be nil here?

File: ddl/concurrentddltest/switch_test.go (hunk 6 above)
Comment (mjonss) [reply ddl/concurrentddltest/switch_test.go:73]: OK, so no issues with updating it for now then :)

File: ddl/ddl_worker.go (hunk 7 above)
Comment (mjonss) [reply ddl/ddl_worker.go:782]: HandleDDLJobTable has a call to CleanupDDLReorgHandles as well, after the runDDLJob (which encapsulates the changes in a new transaction) is done. See line 881.

File: ddl/reorg.go (hunk 8 above)
Comment (mjonss) [reply ddl/reorg.go:865]: Hmm, during development it could, but with the three current entry points of CleaupDDLReorgHandles, job cannot be nil. But the code should be able to handle job == nil, just in case.

File: ddl/concurrentddltest/switch_test.go (hunk 6 above)
Comment (wjhuang2016) [reply ddl/concurrentddltest/switch_test.go:73]: FYI: https://github.com/pingcap/tidb/pull/39684, it's in merging.

Comment (mjonss) [reply ddl/concurrentddltest/switch_test.go:73]: Thanks, merging those changes here now.

Comment (mjonss) [reply ddl/concurrentddltest/switch_test.go]: Just merged, thank you for the heads up!

File: ddl/reorg.go [hunk 9]
```diff
@@ -252,10 +253,6 @@ func (w *worker) runReorgJob(rh *reorgHandler, reorgInfo *reorgInfo, tblInfo *mo
 		}
 
 		updateBackfillProgress(w, reorgInfo, tblInfo, 0)
-		if err1 := rh.RemoveDDLReorgHandle(job, reorgInfo.elements); err1 != nil {
-			logutil.BgLogger().Warn("[ddl] run reorg job done, removeDDLReorgHandle failed", zap.Error(err1))
-			return errors.Trace(err1)
-		}
```
Comment (mjonss) [inline ddl/reorg.go:258]: This is where the conflict was created. The tidb_ddl_reorg table had already been changed in the reorg work function `f()` given as an argument. While this change is in the scope of the `w.sess` session which was started before calling this function and committed after returning. It has been replaced by `CleanupDDLReorgHandles` in `HandleDDLJobDone` and `HandleDDLJobTable`.

File: ddl/ddl_worker.go [hunk 10]
```diff
@@ -797,6 +798,7 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
 	// reset the SQL digest to make topsql work right.
 	w.sess.GetSessionVars().StmtCtx.ResetSQLDigest(job.Query)
 	err = w.sess.commit()
+	CleanupDDLReorgHandles(job, w.sessPool)
```
Comment (wjhuang2016) [inline ddl/ddl_worker.go:801]: Why do we need CleanupDDLReorgHandles here, since it would be called in HandleJobDone?

File: ddl/backfilling.go [hunk 11]
```diff
@@ -583,9 +583,10 @@ func (dc *ddlCtx) sendTasksAndWait(scheduler *backfillScheduler, totalAddedCount
 		err = dc.isReorgRunnable(reorgInfo.Job.ID)
 	}
 
+	// Update the reorg handle that has been processed.
+	err1 := reorgInfo.UpdateReorgMeta(nextKey, scheduler.sessPool)
```
Comment (mjonss) [inline ddl/backfilling.go:587]: I removed the `updateDDLReorgStartHandle` from `runReorgJob` on timeout and added it here instead.
It may change the number of transactions, but I think it is better to always save the state here, right after each batch is done (also still ignoring the error).

File: ddl/job_table.go [hunk 12]
```diff
@@ -547,7 +560,7 @@ func AddBackfillJobs(sess *session, backfillJobs []*BackfillJob) error {
 		if err != nil {
 			return err
 		}
-		_, err = sess.execute(context.Background(), sql, label)
+		_, err = se.execute(context.Background(), sql, label)
```
Comment (mjonss) [inline ddl/job_table.go:563]: @zimulala I assume it should use the new session `se` from runInTxn instead of the outer `sess` here?

File: ddl/job_table.go [hunk 13]
```diff
@@ -582,14 +595,13 @@ func GetBackfillJobsForOneEle(sess *session, batch int, excludedJobIDs []int64,
...
-	err = runInTxn(s, func(se *session) error {
-		currTime, err := GetOracleTimeWithStartTS(s)
+	err = runInTxn(sess, func(se *session) error {
+		currTime, err := GetOracleTimeWithStartTS(se)
 		if err != nil {
 			return err
 		}
 
-		bJobs, err = GetBackfillJobs(sess, BackfillTable,
+		bJobs, err = GetBackfillJobs(se, BackfillTable,
```
Comment (mjonss) [inline ddl/job_table.go:604]: @zimulala I assume it should use the new session `se` from runInTxn instead of the outer `sess` here?

File: ddl/job_table.go [hunk 14]
```diff
@@ -643,7 +654,7 @@ func GetAndMarkBackfillJobsForOneEle(sess *session, batch int, jobID int64, uuid
 			bJobs[i].InstanceID = uuid
 			bJobs[i].InstanceLease = GetLeaseGoTime(currTime, lease)
 			// TODO: batch update
-			if err = updateBackfillJob(sess, BackfillTable, bJobs[i], "get_mark_backfill_job"); err != nil {
+			if err = updateBackfillJob(se, BackfillTable, bJobs[i], "get_mark_backfill_job"); err != nil {
```
Comment (mjonss) [inline ddl/job_table.go:657]: @zimulala I assume it should use the new session `se` from runInTxn instead of the outer `sess` here?

File: ddl/job_table.go [hunk 15]
```diff
@@ -582,14 +595,13 @@ func GetBackfillJobsForOneEle(sess *session, batch int, excludedJobIDs []int64,
 
 	var err error
 	var bJobs []*BackfillJob
-	s := newSession(sess)
-	err = runInTxn(s, func(se *session) error {
-		currTime, err := GetOracleTimeWithStartTS(s)
+	err = runInTxn(sess, func(se *session) error {
+		currTime, err := GetOracleTimeWithStartTS(se)
```
Comment (mjonss) [inline ddl/job_table.go:599]: @zimulala I assume it should use the new session `se` from runInTxn instead of the outer `sess` here, or is it it intentional that it should have the timestamp from the outer `sess` session?

File: ddl/job_table.go (hunk 12 above)
Comment (zimulala) [reply ddl/job_table.go:563]: Good catch.
This code resolves conflicts several times, which I should not have noticed. My mistake, thanks ~

File: ddl/job_table.go (hunk 15 above)
Comment (zimulala) [reply ddl/job_table.go:599]: Ditto.

File: ddl/job_table.go [hunk 16]
```diff
@@ -615,14 +627,13 @@ func GetBackfillJobsForOneEle(sess *session, batch int, excludedJobIDs []int64,
...
-	s := newSession(sess)
-	err := runInTxn(s, func(se *session) error {
+	err := runInTxn(sess, func(se *session) error {
 		currTime, err := GetOracleTimeWithStartTS(se)
 		if err != nil {
 			return err
 		}
 
-		bJobs, err = GetBackfillJobs(sess, BackfillTable,
+		bJobs, err = GetBackfillJobs(se, BackfillTable,
```
[the remark this answers is not in the document]
Comment (zimulala) [reply ddl/job_table.go:636]: Ditto.

File: ddl/job_table.go [hunk 17]
```diff
@@ -460,15 +455,33 @@ func removeDDLReorgHandle(sess *session, job *model.Job, elements []*meta.Elemen
 		return nil
 	}
 	sql := fmt.Sprintf("delete from mysql.tidb_ddl_reorg where job_id = %d", job.ID)
-	_, err := sess.execute(context.Background(), sql, "remove_handle")
-	return err
+	return runInTxn(sess, func(se *session) error {
```
Comment (wjhuang2016) [inline ddl/job_table.go:458]: runInTxn may wrongly commit the previous session. There is no need to use explicit txn.

Comment (wjhuang2016) [reply ddl/job_table.go:458]: In newReorgHandler, we need a new session instead of the DDL session.

File: ddl/ddl_worker.go (hunk 10 above)
Comment (mjonss) [reply ddl/ddl_worker.go]: Thank you for the suggestion, I removed it here and only rely on the call in HandleJobDone.

File: ddl/job_table.go (hunk 17 above)
Comment (mjonss) [reply ddl/job_table.go]: Done, before calling newReorgHandler, it will take out one new session from the session pool and use for the ReorgHandler.

**Review by wjhuang2016 — APPROVED** [review]
I tested this PR in schrDDL. tidb_ddl_reorg is not write-conflict anymore.

File: executor/union_scan_test.go [hunk 18]
```diff
@@ -416,6 +417,14 @@ func TestForApplyAndUnionScan(t *testing.T) {
...
 
 func TestIssue28073(t *testing.T) {
+	var wg sync.WaitGroup
+	wg.Add(1)
+	dumpChan := make(chan struct{})
+	defer func() {
+		close(dumpChan)
+		wg.Wait()
+	}()
+	go testkit.DebugDumpOnTimeout(&wg, dumpChan, 20*time.Second)
```
Comment (tangenta) [inline executor/union_scan_test.go:427]: The timeout issue is fixed. Is it necessary to keep this?

Comment (mjonss) [reply executor/union_scan_test.go]: Not really, I just removed it from the PR. I may create a separate PR for the 'DebugDumpOnTimeout' function later on.

File: ddl/reorg.go [hunk 19]
```diff
@@ -809,6 +788,27 @@ func (r *reorgHandler) RemoveDDLReorgHandle(job *model.Job, elements []*meta.Ele
...
+	if job != nil && !job.IsFinished() && !job.IsSynced() {
+		// Job is given, but it is neither finished nor synced; do nothing
+		return
+	}
+	sctx, err := pool.get()
+	if err != nil {
+		logutil.BgLogger().Info("CleanupDDLReorgHandles get sessionctx failed", zap.Error(err))
+		return
+	}
+	defer pool.put(sctx)
```
Comment (zimulala) [inline ddl/reorg.go:802]: Could we use `w.sess.txn()`? I see we have a Txn in `HandleJobDone`(https://github.com/pingcap/tidb/pull/38738/files#diff-dfc42c5764e7e4ff9122a1db728ff1cb0dee56e72dbccefdb211018ccd444c73R698).
The current situation is a bit like this:
```
begin txn1
begin txn2
commit txn2
commit txn1
```
And `cleanDDLReorgHandles` also add a new Txn.

Comment (mjonss) [reply ddl/reorg.go:802]: Since the code have evolved a bit during my investigation and it is now only called from HandleJobDone, you are correct that we can now simply use `w.sess`, since it was just committed before the call of CleanupDDLReorgHandles.
Let me update the patch like that.

**Review by tangenta — APPROVED** [review]

File: executor/executor_test.go [hunk 20]
```diff
@@ -5565,7 +5565,7 @@ func TestAdmin(t *testing.T) {
 	tk = testkit.NewTestKit(t, store)
 	tk.MustExec("begin")
 	sess := tk.Session()
-	ddlInfo, err := ddl.GetDDLInfo(sess)
+	ddlInfo, err := ddl.GetDDLInfoWithNewTxn(sess)
```
Comment (zimulala) [inline executor/executor_test.go:5568]: Why update this function？ line5566 will begin a new txn.

Comment (mjonss) [reply executor/executor_test.go]: let me revert it back (I changed `GetDDLInfo` to `getDDLInfo` to make sure I did not miss any cases where new transactions would be needed, but that is no longer needed).

Comment (mjonss) [reply executor/executor_test.go]: Reverted.

**Review by zimulala — APPROVED** [review]
