### PR TITLE
ttl: fix potential go leak for ttl in test

### LINKED ISSUE #46948: goleak ttl/ttlworker in the planner/cascades
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
-- PASS: TestMemTableScan (2.21s)

PASS

coverage: 13.5% of statements

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 26931 in state chan receive, with github.com/pingcap/tidb/ttl/client.(*mockClient).WatchCommand.func1 on top of the stack:

goroutine 26931 [chan receive]:

github.com/pingcap/tidb/ttl/client.(*mockClient).WatchCommand.func1()

	ttl/client/command.go:435 +0x4f

created by github.com/pingcap/tidb/ttl/client.(*mockClient).WatchCommand in goroutine 26840

	ttl/client/command.go:434 +0x2e5


 Goroutine 26937 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop on top of the stack:

goroutine 26937 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop(0xc00795f400)

	ttl/ttlworker/del.go:281 +0x2e5

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc00555cf68?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26840 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*JobManager).jobLoop on top of the stack:

goroutine 26840 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*JobManager).jobLoop(0xc007723700)

	ttl/ttlworker/job_manager.go:186 +0x927

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc00613ffd0?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26838

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26932 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 26932 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc0072a9dd0)

	ttl/ttlworker/scan.go:315 +0x185

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc004f94fd0?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26933 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 26933 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc0072a9e60)

	ttl/ttlworker/scan.go:315 +0x185

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc000f39fd0?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26936 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop on top of the stack:

goroutine 26936 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop(0xc00795f380)

	ttl/ttlworker/del.go:281 +0x2e5

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc00555df68?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26939 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop on top of the stack:

goroutine 26939 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop(0xc00795f500)

	ttl/ttlworker/del.go:281 +0x2e5

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc005aa97d0?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26938 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop on top of the stack:

goroutine 26938 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop(0xc00795f480)

	ttl/ttlworker/del.go:281 +0x2e5

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc0071baee8?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26935 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 26935 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc00764c000)

	ttl/ttlworker/scan.go:315 +0x185

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc005559f68?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c


 Goroutine 26934 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 26934 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc0072a9ef0)

	ttl/ttlworker/scan.go:315 +0x185

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc0074f9768?)

	ttl/ttlworker/worker.go:134 +0x7a

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x59

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run in goroutine 26840

	util/wait_group_wrapper.go:152 +0x7c

]

--

```

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/33076/pipeline

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #46948

### What is changed and how it works?

In the previous code, the ttlJobManager is created and started in a background goroutine:

https://github.com/pingcap/tidb/blob/a7e3176f30e0dff6d993eda0ddd1b64776ad98f6/domain/domain.go#L2917-L2929

It has a probability that if a test runs very fast and `domain.Close` will be called before `do.ttlJobManager.Store(ttlJobManager) `. The ttlJobManager will not stop anymore.

In this PR, we just move ttlJobManager's create and start out of the goroutine.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: domain/domain.go [hunk 1]
```diff
@@ -995,6 +995,7 @@ func (do *Domain) Close() {
 	}
 	ttlJobManager := do.ttlJobManager.Load()
 	if ttlJobManager != nil {
+		logutil.BgLogger().Info("stop ttlJobManager")
```
Comment (hawkingrei) [inline domain/domain.go:998]:
```suggestion
		logutil.BgLogger().Info("stopping ttlJobManager")
```

**Review by hawkingrei — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
