### PR TITLE
ddl: better approach to pause or resume ddl jobs during upgrade

### LINKED ISSUE #43897: Upgrade pause all jobs failed when pause paused jobs
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. using tiup deploy a cluster with 3 tidb instance
2. create much table by sysbench `sysbench oltp_common --mysql-host=tiup-peer.testbed-endless-enable-ddl-upgrade-tiup9fghg --mysql-port=3390 --mysql-user=root --mysql-db=sbtest2 --time=600 --threads=300 --report-interval=10 --db-driver=mysql --tables=10000 --table-size=10 --create_secondary=false prepare`
3. tiup cluster upgrade ddl_upgrade v7.1.0 --pre-upgrade-script "sh /home/tidb/prescript.sh", upgrade with -with-mock-upgrade

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
upgrade cluster success
### 3. What did you see instead (Required)
1. tiup upgrade failed `Error: failed to restart: tidb-1-peer tidb-4000.service, please check the instance's log(/tiup/deploy/tidb-4000/log) for more detail.: timed out waiting for port 4000 to be started after 2m0s`
2. fatal error  for tidb and can not start
![图片](https://github.com/pingcap/tidb/assets/10184437/e94ec377-ebad-4ba8-a02c-8949d657e4bd)


### 4. What is your TiDB version? (Required)
```sql
MySQL [(none)]> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.1.0-upgrade
Edition: Community
Git Commit Hash: 63d719517832dc84cc30b393b6c96a3767c4bead
Git Branch: heads/refs/tags/v7.1.0-upgrade
UTC Build Time: 2023-05-12 11:10:27
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by dhysum**
### What problem does this PR solve?

Issue Number: close #43897

Problem Summary:
1. TiDB will try to pause jobs again if restarted during upgrade, need to omit ErrPausedDDLJob
2. Once there is error during Pause/Resume a bunch of jobs, it will fail immediately and return. Which should be continue to next job
3. There are some corner cases that jobs could not be paused during upgrade, which should not become runnable

### What is changed and how it works?

1. Would not run the jobs that could not be paused during TiDB Upgrade
2. Omit the error of `pause` during TiDB Upgrade in DDL Worker
3. Continue to pause/resume next job even error happened
4. Return `ErrPausedDDLJob` if already `paused`
5. Process the errors returned by  PauseAllJobsBySystem and ResumeAllJobsBySystem during upgrade

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
- Support `admin pause ddl jobs 3,5;`
- Support `admin resume ddl jobs 3,5;`
```

### CODE REVIEW

File: session/bootstrap.go [hunk 1]
```diff
@@ -1179,7 +1179,8 @@ func syncUpgradeState(s Session) {
 	}
 
 	for i := 0; i < retryTimes; i++ {
-		if _, err = ddl.PauseAllJobsBySystem(s); err == nil {
+		_, err = ddl.PauseAllJobsBySystem(s)
+		if err == nil || dbterror.ErrPausedDDLJob.Equal(err) {
```
Comment (zimulala) [inline session/bootstrap.go:1183]: If pause 3 jobs， the first one gets `ErrPausedDDLJob`, then other jobs all don't pause.

File: ddl/ddl_worker.go [hunk 2]
```diff
@@ -975,17 +975,49 @@ func (w *worker) runDDLJob(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int64,
...
+		return ver, err
+	} else if job.IsPausedBySystem() && !hasSysDB(job) {
+		_, err = ResumeJobsBySystem(w.sess.Session(), []int64{job.ID})
+		if err != nil {
+			logutil.BgLogger().Warn(
+				"[ddl] failed to resume user DDL by system after upgrade", zap.Stringer("job", job), zap.Error(err))
+			return ver, err
+		}
+		return ver, nil
+	}
```
Comment (zimulala) [inline ddl/ddl_worker.go:1018]: Could we abstract this into a function?

Comment (dhysum) [reply ddl/ddl_worker.go:1018]: ok, that would be better.

File: session/bootstrap.go [hunk 3]
```diff
@@ -1193,11 +1204,15 @@ func syncUpgradeState(s Session) {
...
 
 func syncNormalRunning(s Session) {
-	_, err := ddl.ResumeAllJobsBySystem(s)
+	jobErrs, err := ddl.ResumeAllJobsBySystem(s)
 	if err != nil {
 		logutil.BgLogger().Fatal("upgrade pause all jobs failed", zap.Error(err))
 	}
 
+	for _, err = range jobErrs {
+		logutil.BgLogger().Warn("[DDL] unable to resume the job, error: ", zap.Error(err))
```
Comment (zimulala) [inline session/bootstrap.go:1213]:
```suggestion
		logutil.BgLogger().Warn("[DDL] upgrade pause all jobs failed, unable to resume the job, error: ", zap.Error(err))
```

File: ddl/ddl.go [hunk 4]
```diff
@@ -1618,7 +1621,7 @@ func processAllJobs(process func(*sess.Session, *model.Job, model.AdminCommandOp
 	for {
 		var jobs []*model.Job
 		jobs, err = getJobsBySQL(ns, JobTable,
-			fmt.Sprintf("job_id >= %s order by job_id asc limit %s",
```
Comment (zimulala) [inline ddl/ddl.go:1621]: Why need to add `processing` ? How about the job is queuing?

File: ddl/ddl.go [hunk 5]
```diff
@@ -1542,19 +1548,16 @@ func processJobs(process func(*sess.Session, *model.Job, model.AdminCommandOpera
...
 			if err != nil {
 				errs[i] = err
-				break
+				continue
 			}
 
 			err = updateDDLJob2Table(ns, job, true)
 			if err != nil {
-				break
+				// unexpected error on updating the job table, should roll it back
```
Comment (zimulala) [inline ddl/ddl.go:1556]: Maybe we encounter write-conflict error(If the job is running which is likely to happen). I think it also can do it like line1550-1551.

File: ddl/ddl.go [hunk 6]
```diff
@@ -1630,11 +1633,12 @@ func processAllJobs(process func(*sess.Session, *model.Job, model.AdminCommandOp
...
 			if err != nil {
 				jobErrs[job.ID] = err
-				ns.Rollback()
-				return jobErrs, err
+				continue
 			}
+
 			err = updateDDLJob2Table(ns, job, true)
 			if err != nil {
+				// unexpected error on updating the job table, should roll it back
```
Comment (zimulala) [inline ddl/ddl.go:1641]: Ditto.

File: ddl/ddl_worker.go [hunk 7]
```diff
@@ -950,6 +950,18 @@ func (w *worker) countForError(err error, job *model.Job) error {
 	return err
 }
 
+func (w *worker) processJobPausingRequest(d *ddlCtx, job *model.Job) (err error, isRunnable bool) {
+	if job.IsPaused() {
+		logutil.Logger(w.logCtx).Debug("[ddl] paused DDL job ", zap.String("job", job.String()))
```
Comment (zimulala) [inline ddl/ddl_worker.go:955]: Why change the log  level to debug?

File: ddl/job_table.go [hunk 8]
```diff
@@ -194,28 +165,41 @@ func hasSysDB(job *model.Job) bool {
...
+		// no matter how, we would not run DDL jobs during upgrade even not paused.
+		return err, false
 	}
-	if hasSysDB(job) {
-		return nil
+
+	if job.IsPausedBySystem() && !hasSysDB(job) {
+		var errs []error
+		errs, err = ResumeJobsBySystem(sess.Session(), []int64{job.ID})
+		if len(errs) > 0 {
```
Comment (zimulala) [inline ddl/job_table.go:194]: It seems that `len(errs)` always greater than 0
`errs = make([]error, len(ids))`: https://github.com/pingcap/tidb/pull/43907/files#diff-a185df836b8926c4afe351d4def1b56d1e282c65aabe6677c2fa2c54590cc4b2R1519

File: ddl/job_table.go [hunk 9]
```diff
@@ -194,28 +165,41 @@ func hasSysDB(job *model.Job) bool {
...
 }
 
-func (d *ddl) handleUpgradingState(se *sess.Session, job *model.Job) error {
-	if !d.stateSyncer.IsUpgradingState() {
-		if !job.IsPausedBySystem() || hasSysDB(job) {
-			return nil
+func (d *ddl) processJobDuringUpgrade(sess *sess.Session, job *model.Job) (err error, isRunnable bool) {
+	if d.stateSyncer.IsUpgradingState() {
+		if hasSysDB(job) {
+			return err, false
```
Comment (zimulala) [inline ddl/job_table.go:171]: I think we need to handle this job which is means we can return true for `isRunnable`.
Besides, I think we'd better return `nil` instead of `err`.

Comment (dhysum) [reply ddl/job_table.go:171]: good one

File: ddl/job_table.go (hunk 8 above)
Comment (dhysum) [reply ddl/job_table.go:194]: good one

File: ddl/ddl.go (hunk 5 above)
Comment (dhysum) [reply ddl/ddl.go:1556]: Such kind of failures look like more serious. And the behavior  of writing to TiKV should keep the same as line 1533-1536. Also, we could handle the two returned value in different ways.

File: ddl/ddl.go (hunk 4 above)
Comment (dhysum) [reply ddl/ddl.go:1621]: good one, remove it.

File: ddl/ddl.go (hunk 6 above)
Comment (dhysum) [reply ddl/ddl.go:1641]: It looks like better to handle two different kind of failure.

File: ddl/ddl_worker.go (hunk 7 above)
Comment (dhysum) [reply ddl/ddl_worker.go:955]: It would be much since every time of polling would come to here if paused.

File: ddl/job_table.go (hunk 9 above)
Comment (dhysum) [reply ddl/job_table.go:171]: Actually, it also depends how we design the behavior. We could say that all DDL jobs should not be running during upgrade.

File: session/bootstrap.go (hunk 3 above)
Comment (dhysum) [reply session/bootstrap.go:1213]: Could not get the point. The operation here is "Resume", and why the log here is about "Pause".

Comment (zimulala) [reply session/bootstrap.go:1213]: Sorry. It seems that the log of line1209 is wrong. I want we add "upgrade resume all jobs failed" for these logs.

File: ddl/ddl.go (hunk 5 above)
Comment (zimulala) [reply ddl/ddl.go:1556]: If all (many) DDL operations are suspended, there is a risk of write-conflict error, and it is possible to try ten times and fail ten times. 
Originally, there was no exit, and it would have been easier for an interface to handle error in the same way as error. 
Or we could do something special here.

File: ddl/job_table.go [hunk 10]
```diff
@@ -194,28 +165,41 @@ func hasSysDB(job *model.Job) bool {
...
+			return errs[0], false
 		}
-		logutil.BgLogger().Info("[ddl] resume user DDL by system successful", zap.Stringer("job", job))
-		return nil
-	}
-	if job.IsPausing() {
-		return nil
+
+		// no matter how, we would not run DDL jobs during upgrade even not paused.
+		return err, false
```
Comment (zimulala) [inline ddl/job_table.go:188]: If the job is pausing, we can't do `pauseReorgWorkers`, so I think we need to add the check of `!job.IsPausedBySystem() ` in line170.

Comment (dhysum) [reply ddl/job_table.go]: pausing is kind of request, it will be turned to be 'model.JobStatePaused' in pauseReorgWorkers() in ddl worker.

Comment (dhysum) [reply ddl/job_table.go]: We may let it keep running if the error is ErrPausedDDLJob.

File: ddl/job_table.go [hunk 11]
```diff
@@ -194,28 +165,51 @@ func hasSysDB(job *model.Job) bool {
...
+			if dbterror.ErrPausedDDLJob.Equal(errs[0]) {
+				// In case of 'Pausing', we need to deliver the job to DDL
+				// worker to pause the background reorganization workers.
+				return true, nil
+			}
+			if dbterror.ErrCannotPauseDDLJob.Equal(errs[0]) {
+				// The state could be 'cancelling' or 'rollback', as well as
+				// some corner state
+				return false, nil
+			}
```
Comment (zimulala) [inline ddl/job_table.go:186]: I think will only do `job.IsPausing || hasSysDB(job)` like https://github.com/pingcap/tidb/pull/43907/files#diff-91c692cc214077acc788fcaf2f92fb40d0a6c4aef3e34e3b6ed532677dac9f13L210.
Then we needn't distinguish the error msg, and needn't do line197.

Comment (dhysum) [reply ddl/job_table.go:186]: It is not a good idea to take care of the job's state out of 'PauseJobsBySystem'. 

As the function 'PauseJobsBySystem' will do the check and pause the job accordingly, we should only check the result of it but not moving some of its logical.

As the logic you mentioned:
1. If hasSysDB(), it will continue the running
2. If ErrPausedDDLJob returned from 'PauseJobsBySystem', then the job could be 'paused' or 'pausing'. And no matter what the state is, the ddl worker will handle it accordingly. Then we don't need to do the check here.

It is about cohesion.

File: session/bootstrap.go [hunk 12]
```diff
@@ -1179,7 +1179,18 @@ func syncUpgradeState(s Session) {
 	}
 
 	for i := 0; i < retryTimes; i++ {
```
[the remark this answers is not in the document]
Comment (dhysum) [reply session/bootstrap.go:1181]: Marking it as failed as soon as possible would be a better choice so that the user will know what is going on here.

[the remark this answers is not in the document]
Comment (zimulala) [reply session/bootstrap.go:1181]: Indeed it is.
But the main reason it I  want wait for pausing successful when encountering canceling or rollbacking job(processing).

File: ddl/job_table.go (hunk 11 above)
Comment (zimulala) [reply ddl/job_table.go:186]: I means:
1. If `hasSysDB()`, it will continue the running
2. If `job.IsPausing`, it will continue the running(pausing to paused)
3. Do `PauseJobsBySystem`, if it encouters return `false, err`

Comment (dhysum) [reply ddl/job_table.go:186]: That is the same with current code.

Comment (zimulala) [reply ddl/job_table.go:186]: But we don't need to determine the error type. That can remove one `if...`

File: session/bootstrap.go [hunk 13]
```diff
@@ -1193,9 +1204,13 @@ func syncUpgradeState(s Session) {
...
 
 func syncNormalRunning(s Session) {
-	_, err := ddl.ResumeAllJobsBySystem(s)
+	jobErrs, err := ddl.ResumeAllJobsBySystem(s)
 	if err != nil {
-		logutil.BgLogger().Fatal("upgrade pause all jobs failed", zap.Error(err))
+		logutil.BgLogger().Warn("[Upgrading] unexpected error to resume all paused jobs: ", zap.Error(err))
+	}
+
+	for _, err := range jobErrs {
```
Comment (zimulala) [inline session/bootstrap.go:1212]: Consider about the case of `err == nil`?

File: ddl/job_table.go (hunk 11 above)
Comment (dhysum) [reply ddl/job_table.go:186]: Error handling is necessary when we are calling a function.

Once it returned the 'ErrPausedDDLJob', which means the job has already been 'paused' or 'pausing', we could just let it go running; otherwise, we should not run it.

We should implement the logic by calling a function and handle its return value but not moving some logic from it.

File: session/bootstrap.go (hunk 13 above)
Comment (dhysum) [reply session/bootstrap.go:1212]: It is a map.

Comment (zimulala) [reply session/bootstrap.go:1212]: Got it.

File: ddl/job_table.go [hunk 14]
```diff
@@ -194,28 +165,45 @@ func hasSysDB(job *model.Job) bool {
...
-		logutil.BgLogger().Info("[ddl] resume user DDL by system successful", zap.Stringer("job", job))
-		return nil
-	}
-	if job.IsPausing() {
-		return nil
+
+		// The job has been issued the command 'pause', which has been turned
+		// to be 'pausing' in job table, then we need to deliver it to ddl
+		// worker to turn it to be 'paused'
+		job.State = model.JobStatePausing
```
Comment (zimulala) [inline ddl/job_table.go:191]: Could we remove it?

Comment (dhysum) [reply ddl/job_table.go:191]: Sure, it just is faster to continue the running this time.

**Review by zimulala — APPROVED** [review]
LGTM

File: ddl/job_table.go [hunk 15]
```diff
@@ -194,28 +165,41 @@ func hasSysDB(job *model.Job) bool {
...
+			return true, nil
 		}
-		_, err := ResumeJobsBySystem(se.Session(), []int64{job.ID})
-		if err != nil {
-			logutil.BgLogger().Warn("[ddl] resume user DDL by system failed", zap.Stringer("job", job), zap.Error(err))
-			return err
+		var errs []error
+		// During binary upgrade, pause all running DDL jobs
+		errs, err = PauseJobsBySystem(sess.Session(), []int64{job.ID})
+		if errs != nil && errs[0] != nil {
```
Comment (zimulala) [inline ddl/job_table.go:176]:
```suggestion
		if len(errs) > 0 && errs[0] != nil {
```

Comment (dhysum) [reply ddl/job_table.go:176]: Already Changed it back to an array.  If errs not nil, its length will definitely larger than 0.

**Review by zimulala — COMMENTED** [review]
CI is failed, and do https://github.com/pingcap/tidb/pull/43982/commits/8ad4fcc62f9d35675500152bdebf8ea037d73603 can fix this issue. You can refer to it.

File: ddl/ddl.go [hunk 16]
```diff
@@ -1462,9 +1462,11 @@ func cancelRunningJob(sess *sess.Session, job *model.Job,
 // pauseRunningJob check and pause the running Job
 func pauseRunningJob(sess *sess.Session, job *model.Job,
 	byWho model.AdminCommandOperator) (err error) {
-	// It would be much better doing this filter during `getJobsBySQL`, but not now.
+	if job.IsPausing() || job.IsPaused() {
+		return dbterror.ErrPausedDDLJob.GenWithStackByArgs(job.ID)
+	}
 	if !job.IsPausable() {
-		err = dbterror.ErrCannotPauseDDLJob.GenWithStackByArgs(job.ID)
+		err = dbterror.ErrCannotPauseDDLJob.GenWithStackByArgs(job.ID, job.State.String(), job.SchemaState.String())
```
Comment (tangenta) [inline ddl/ddl.go:1469]: The message should be updated when you put more arguments to the error.

Error message:
```
ErrCannotPauseDDLJob:  mysql.Message("Job [%v] can't be paused now: %s", nil),
```

When you call `GenWithStackByArgs`:
```
fmt.Sprintf("state: %s, schema state: %s", job.State.String(), job.SchemaState.String())
```

File: ddl/ddl_worker.go [hunk 17]
```diff
@@ -818,10 +818,13 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
 	w.registerSync(job)
 
 	if runJobErr != nil {
-		// wait a while to retry again. If we don't wait here, DDL will retry this job immediately,
-		// which may act like a deadlock.
-		logutil.Logger(w.logCtx).Info("[ddl] run DDL job failed, sleeps a while then retries it.",
-			zap.Duration("waitTime", GetWaitTimeWhenErrorOccurred()), zap.Error(runJobErr))
+		// Omit the ErrPausedDDLJob
+		if !dbterror.ErrPausedDDLJob.Equal(runJobErr) {
```
Comment (tangenta) [inline ddl/ddl_worker.go:822]: Is it necessary to sleep for `ErrPausedDDLJob`?

File: ddl/ddl.go (hunk 16 above)
Comment (dhysum) [reply ddl/ddl.go:1469]: Already done that.

File: session/bootstrap.go [hunk 18]
```diff
@@ -1193,9 +1204,13 @@ func syncUpgradeState(s Session) {
...
 func syncNormalRunning(s Session) {
-	_, err := ddl.ResumeAllJobsBySystem(s)
+	jobErrs, err := ddl.ResumeAllJobsBySystem(s)
 	if err != nil {
-		logutil.BgLogger().Fatal("upgrade pause all jobs failed", zap.Error(err))
+		logutil.BgLogger().Warn("[Upgrading] unexpected error to resume all paused jobs: ", zap.Error(err))
+	}
+
+	for _, e := range jobErrs {
+		logutil.BgLogger().Warn("[Upgrading] unable to resume the job, error: ", zap.Error(e))
```
Comment (tangenta) [inline session/bootstrap.go:1213]:
```suggestion
		logutil.BgLogger().Warn("[upgrading] unexpected error to resume all paused jobs: ", zap.Error(err))
	}

	for _, e := range jobErrs {
		logutil.BgLogger().Warn("[upgrading] unable to resume the job, error: ", zap.Error(e))
```

These should be in lower case.

File: session/bootstrap.go [hunk 19]
```diff
@@ -1193,9 +1204,13 @@ func syncUpgradeState(s Session) {
...
 func syncNormalRunning(s Session) {
-	_, err := ddl.ResumeAllJobsBySystem(s)
+	jobErrs, err := ddl.ResumeAllJobsBySystem(s)
 	if err != nil {
-		logutil.BgLogger().Fatal("upgrade pause all jobs failed", zap.Error(err))
+		logutil.BgLogger().Warn("[upgrading] unexpected error to resume all paused jobs: ", zap.Error(err))
+	}
+
+	for _, e := range jobErrs {
+		logutil.BgLogger().Warn("[upgrading] unable to resume the job, error: ", zap.Error(e))
```
Comment (tangenta) [inline session/bootstrap.go:1213]: What would happen if some of the jobs cannot be resumed?

File: ddl/multi_schema_change_test.go [hunk 20]
```diff
@@ -1298,7 +1298,7 @@ func (c *cancelOnceHook) OnJobUpdated(job *model.Job) {
 	}
 	c.triggered = true
 	errs, err := ddl.CancelJobs(c.s, []int64{job.ID})
-	if errs[0] != nil {
+	if errs != nil && errs[0] != nil {
```
Comment (tangenta) [inline ddl/multi_schema_change_test.go:1301]:
```suggestion
	if len(errs) > 0 && errs[0] != nil {
```

Checking the length is less prone to error.

File: session/bootstrap.go (hunk 19 above)
Comment (dhysum) [reply session/bootstrap.go:1213]: Only 'paused' job can be resumed. If it can't be resumed, than its state could be pausing or others. If 'pausing', it will become 'paused' later on; otherwise, it will go as it is.

**Review by tangenta — APPROVED** [review]

File: ddl/multi_schema_change_test.go (hunk 20 above)
Comment (dhysum) [reply ddl/multi_schema_change_test.go:1301]: It is an array which length is always bigger than 0.

Comment (tangenta) [reply ddl/multi_schema_change_test.go:1301]: I mean if you check the length, such a restriction can be relax when you do the refactoring in the future.

**Review by hawkingrei — APPROVED** [review]

File: ddl/multi_schema_change_test.go (hunk 20 above)
Comment (dhysum) [reply ddl/multi_schema_change_test.go:1301]: good point.
