### PR TITLE
executor: fix hash join between datetime and timestamp

### LINKED ISSUE #25902: error implicit convertion between varchar and timestamp when join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table tt1 (ts timestamp);
create table tt2 (ts varchar(32));
insert into tt1 values ("2001-01-01 00:00:00");
insert into tt2 values ("2001-01-01 00:00:00");
select * from tt1 where ts in (select ts from tt2);
```

### 2. What did you expect to see? (Required)
```sql
+---------------------+
| ts                  |
+---------------------+
| 2001-01-01 00:00:00 |
+---------------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)
```sql
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

5.10 release version &  v5.1.0-alpha-372-g4e61eb149-dirty

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #25902

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by sylzd** [comment]
timestamp Hash table cannot be encoded by utc zone,  because it's not a persistent table, and used by hash join. Is that used by any other places?

**Comment by XuHuaiyu** [comment]
@wshwsh12 @tiancaiamao 
May you help to review this bug-fix PR?

**Comment by mmyj** [comment]
> @wshwsh12 @tiancaiamao
> May you help to review this bug-fix PR?

I can help to review it.

**Comment by tiancaiamao** [comment]
> @wshwsh12 @tiancaiamao
> May you help to review this bug-fix PR?

I'll take a look.

File: util/codec/codec.go [hunk 1]
```diff
@@ -330,14 +330,7 @@ func encodeHashChunkRowIdx(sc *stmtctx.StatementContext, row chunk.Row, tp *type
 	case mysql.TypeDate, mysql.TypeDatetime, mysql.TypeTimestamp:
 		flag = uintFlag
 		t := row.GetTime(idx)
-		// Encoding timestamp need to consider timezone.
```
Comment (tiancaiamao) [inline util/codec/codec.go:333]: I think here is right, the decoding process should take the timezone into consideration.

Comment (tiancaiamao) [reply util/codec/codec.go:333]: Since we do not store the timezone information in the TiKV, all timestamp data is stored as UTC.
They are converted to UTC first, and then into a uint64

The read back process should convert the uint64 to the correct timestamp considering the timezone

Comment (sylzd) [reply util/codec/codec.go:333]: > Timestamp hash table cannot be encoded by utc zone, because it's not a persistent table, and used by hash join. Is that used by any other places?

As I see, the hash table is not a persistent table, It's used to do join operator after being getted from kv and converted to the right timezone, other than store in kv.

Comment (sylzd) [reply util/codec/codec.go:333]: For instance, this sql can produce the right result, because we do not convert timezone when do join, and convert zone should be considered when it was getted from kv.
```sql
select  /*+ MERGE_JOIN(tt1, tt2) */ * from tt1 inner join tt2 on tt1.ts=tt2.ts;
```

**Comment by tiancaiamao** [comment]
Here is what we need to change:

https://github.com/pingcap/tidb/blob/cb06e116c1bfb1089c2e1df5072e889a3b7decd3/util/codec/codec.go#L333-L340


https://github.com/pingcap/tidb/blob/cb06e116c1bfb1089c2e1df5072e889a3b7decd3/util/codec/codec.go#L510-L517

Could you help us remove it in this pull request, and also add a test like that:

```
mysql> select * from tt1 where ts in (select ts from tt2);
+---------------------+
| ts                  |
+---------------------+
| 2001-01-01 00:00:00 |
+---------------------+
1 row in set (0.00 sec)

mysql> set @@session.time_zone = '+10:00';
Query OK, 0 rows affected (0.00 sec)

mysql> select * from tt1 where ts in (select ts from tt2);
Empty set (0.01 sec)
```

Bug fix should comes with a unit test to prevent regression. @sylzd

**Comment by tiancaiamao** [comment]
Explain: tikv doesn't store the time_zone information, so the timestamp is converted to UTC first before stored.
When the timestamp data is loaded into chunk, they are convert back considering the session time_zone.

```
mysql> insert into tt1 values ("2001-01-01 00:00:00");
Query OK, 1 row affected (0.00 sec)
# stored as `2000-12-31 16:00:00` in UTC

mysql> select * from tt1;
+---------------------+
| ts                  |
+---------------------+
| 2001-01-01 00:00:00 |
+---------------------+
1 row in set (0.01 sec)
# read back `2000-12-31 16:00:00` considering session time_zone=+8:00 gets `2001-01-01 00:00:00` UTC+8

mysql> set @@session.time_zone = '+10:00';
Query OK, 0 rows affected (0.00 sec)

mysql> select * from tt1;
+---------------------+
| ts                  |
+---------------------+
| 2001-01-01 02:00:00 |
+---------------------+
1 row in set (0.00 sec)
# read back `2000-12-31 16:00:00` considering session time_zone=+8:00 gets `2001-01-01 02:00:00` UTC+10
```

The bug of that issue is, the loading to chunk process had already handle the time_zone converting, so when hash join key comparing, the converting should not be done again.

https://github.com/pingcap/tidb/blob/cb06e116c1bfb1089c2e1df5072e889a3b7decd3/executor/hash_table.go#L127

File: util/codec/codec.go (hunk 1 above)
Comment (tiancaiamao) [reply util/codec/codec.go:333]: Exactly

**Comment by sylzd** [comment]
> Explain: tikv doesn't store the time_zone information, so the timestamp is converted to UTC first before stored.
> When the timestamp data is loaded into chunk, they are convert back considering the session time_zone.
> 
> ```
> mysql> insert into tt1 values ("2001-01-01 00:00:00");
> Query OK, 1 row affected (0.00 sec)
> # stored as `2000-12-31 16:00:00` in UTC
> 
> mysql> select * from tt1;
> +---------------------+
> | ts                  |
> +---------------------+
> | 2001-01-01 00:00:00 |
> +---------------------+
> 1 row in set (0.01 sec)
> # read back `2000-12-31 16:00:00` considering session time_zone=+8:00 gets `2001-01-01 00:00:00` UTC+8
> 
> mysql> set @@session.time_zone = '+10:00';
> Query OK, 0 rows affected (0.00 sec)
> 
> mysql> select * from tt1;
> +---------------------+
> | ts                  |
> +---------------------+
> | 2001-01-01 02:00:00 |
> +---------------------+
> 1 row in set (0.00 sec)
> # read back `2000-12-31 16:00:00` considering session time_zone=+8:00 gets `2001-01-01 02:00:00` UTC+10
> ```
> 
> The bug of that issue is, the loading to chunk process had already handle the time_zone converting, so when hash join key comparing, the converting should not be done again.
> 
> https://github.com/pingcap/tidb/blob/cb06e116c1bfb1089c2e1df5072e889a3b7decd3/executor/hash_table.go#L127

yes, that's what I mean~

**Review by tiancaiamao — APPROVED** [review]

**Comment by sylzd** [comment]
@mmyj  PTAL~

File: executor/join_test.go [hunk 2]
```diff
@@ -2592,3 +2592,18 @@ func (s *testSuiteJoinSerial) TestIssue20219(c *C) {
...
+	tk.MustExec("drop table if exists tt1,tt2; ")
+	tk.MustExec("create table tt1 (ts timestamp);")
+	tk.MustExec("create table tt2 (ts varchar(32));")
+	tk.MustExec("create table tt3 (ts datetime);")
+	tk.MustExec("insert into tt1 values (\"2001-01-01 00:00:00\");")
+	tk.MustExec("insert into tt2 values (\"2001-01-01 00:00:00\");")
+	tk.MustExec("insert into tt3 values (\"2001-01-01 00:00:00\");")
+	tk.MustQuery("select * from tt1 where ts in (select ts from tt2);").Check(testkit.Rows("2001-01-01 00:00:00"))
+	tk.MustQuery("select * from tt1 where ts in (select ts from tt3);").Check(testkit.Rows("2001-01-01 00:00:00"))
+	tk.MustExec("set @@session.time_zone = '+10:00';")
```
Comment (mmyj) [inline executor/join_test.go:2607]: Should we reset to `time_zone` to `+08`?

Comment (sylzd) [reply executor/join_test.go:2608]: thx, it fixed~

File: executor/join_test.go [hunk 3]
```diff
@@ -2592,3 +2592,18 @@ func (s *testSuiteJoinSerial) TestIssue20219(c *C) {
 	tk.MustQuery("select /*+ inl_join(s)*/ t.a from t left join s on t.a = s.a;").Check(testkit.Rows("i", "j"))
 	tk.MustQuery("show warnings").Check(testkit.Rows())
 }
+
+func (s *testSuiteJoinSerial) TestIssue25902(c *C) {
+	tk := testkit.NewTestKitWithInit(c, s.store)
+	tk.MustExec("drop table if exists tt1,tt2; ")
```
[the remark this answers is not in the document]
Comment (sylzd) [reply executor/join_test.go]: fixed!

**Review by mmyj — APPROVED** [review]
lgtm
