### PR TITLE
br/stream: initialize `newBase` for `doTruncateLog`.

### LINKED ISSUE #63358: br log truncate: SIGSEGV inside cleanUpFor()
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Perform `br log truncate --until`

### 2. What did you expect to see? (Required)

Truncate happens successfully.

### 3. What did you see instead (Required)

Panics with this stack trace:

```
We are going to truncate 3030 files, up to TS 2025-09-03 01:42:23.0000.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0х5848f74]

goroutine 3865 [running]:
github.com/pingcap/tidb/br/pkg/stream.MigrationExt.cleanUpFor({...}, 0x4002720fc0, 0x400084eed8)
    /.../release/tidb/br/pkg/stream/stream_netas.go:896 +0x584
github.com/pingcap/tidb/br/pkg/stream.MigrationExt.doTruncatelogs.func3()
   /.../release/tidb/br/pkg/stream/stream_metas.go:1102 +0x2c4
...
```

### 4. What is your TiDB version? (Required)

v8.5.1

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Juncen Yu <yujuncen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #63358

Problem Summary:
The `MigratedTo` field wasn't initialized, hence a failure on saving new metadata or deleting file causes a panic.

### What changed and how does it work?
This PR picked the optimization (without flags change) from #56761

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fixed a bug that may cause `log truncate` panic when failed to delete file.
```

### CODE REVIEW

File: br/pkg/glue/console_glue.go [hunk 1]
```diff
@@ -84,6 +87,21 @@ func (ops ConsoleOperations) RootFrame() Frame {
 	}
 }
 
+func PrintList[T any](ops ConsoleOperations, title string, items []T, maxItemsDisplay int) {
```
Comment (Leavrth) [inline br/pkg/glue/console_glue.go:90]: dead code?

**Review by Leavrth — APPROVED** [review]

File: br/pkg/glue/console_glue.go (hunk 1 above)
Comment (YuJuncen) [reply br/pkg/glue/console_glue.go:90]: It may be used by other picks so perhaps we can keep it?

**Review by kennytm — APPROVED** [review]
