### PR TITLE
planner, expression: fix error when using IN combined with subquery

### LINKED ISSUE #22071: error when using `IN` + subquery
## Bug Report

this bug is introduced by https://github.com/pingcap/tidb/pull/13594
### 1. Minimal reproduce step (Required)

```sql
> create table t (a int);
> select n in (1,2) from (select a in (1,2) as n from t) g;
ERROR 1105 (HY000): Can't find column Column#3 in schema Column: [test.t.a] Unique key: []
```

### 2. What did you expect to see? (Required)
execute this SQL correctly
### 3. What did you see instead (Required)
error
### 4. What is your TiDB version? (Required)
all 4.0.x versions are affected

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #22071 

### What is changed and how it works?

In #13594, we did an optimization for IN expression. In this optimization, we save the non-const args of the IN function in `baseInSig.nonConstArgs`. 
When eliminating projection, sometimes we will rewrite args of `Exprs` of `LogicalProjection`. Forgetting to consider the `nonConstArgs` at this stage caused this bug. 

Now we don't store the args, we store the indexes of the non-const args instead.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- no release note

### CODE REVIEW

**Review by winoros — COMMENTED** [review]
lgtm

File: expression/builtin_other.go [hunk 1]
```diff
@@ -159,6 +159,41 @@ type baseInSig struct {
...
 }
 
+// ReplaceColumnOfExpr replaces column of expression by another LogicalProjection.
+// This function is the same as ReplaceColumnOfExpr in rule_eliminate_projection.go and will be assigned by init() there.
+// We are doing this because import that package directly will cause dependency cycle.
+var ReplaceColumnOfExpr func(expr Expression, projExpr []Expression, schema *Schema) Expression
+
+// ReplaceColumnOfExprForIn replaces column of nonConstArgs in IN expression by another LogicalProjection.
+func ReplaceColumnOfExprForIn(sf *ScalarFunction, projExpr []Expression, schema *Schema) {
+	switch inFunc := sf.Function.(type) {
```
Comment (eurekaka) [inline expression/builtin_other.go:169]: Can we use `sf.Function.(*baseInSig)`?

File: planner/core/rule_eliminate_projection.go [hunk 2]
```diff
@@ -160,17 +161,27 @@ func (pe *projectionEliminator) eliminate(p LogicalPlan, replace map[string]*exp
...
+			return projExprs[idx]
 		}
 	case *expression.ScalarFunction:
 		for i := range v.GetArgs() {
-			v.GetArgs()[i] = ReplaceColumnOfExpr(v.GetArgs()[i], proj, schema)
+			v.GetArgs()[i] = ReplaceColumnOfExpr(v.GetArgs()[i], projExprs, schema)
+		}
+		// We have done special optimization for IN expression in PR#13594. This optimization makes us need to do the replacement
+		// for some more expressions other than builtinFunc.args
+		if v.FuncName.L == ast.In {
```
Comment (eurekaka) [inline planner/core/rule_eliminate_projection.go:183]: Can we override the `getArgs()` function for `baseInSig` to return the `nonConstArgs`?

Comment (time-and-fate) [reply planner/core/rule_eliminate_projection.go:183]: Seems we can't again.
https://github.com/pingcap/tidb/blob/3cf4214167a360fa8fd14b119a10fce68ffe9bb8/expression/builtin_other.go#L237-L241
`baseBuiltinFunc.args` is still being used so we can't return only `nonConstArgs`.
If we return `baseBuiltinFunc.args + nonConstArgs`. That will cause `getArgs()` to allocate a new slice to hold them, then we can't use the result of `getArgs()` to modify the original slices.

File: expression/builtin_other.go (hunk 1 above)
Comment (time-and-fate) [reply expression/builtin_other.go:169]: Seems we can't.
Embedding `*baseInSig` doesn't make it able to be cast to `baseInSig`.

File: planner/core/rule_eliminate_projection.go (hunk 2 above)
Comment (eurekaka) [reply planner/core/rule_eliminate_projection.go:183]: Can we introduce another interface function `setArgs` for `builtinFunc` and specially implement it for `baseInSig`? What I am concerned is that, there may be something like projection elimination in other places, or in future code changes, then this function would be ignored once again when processing its arguments, so we'd better encapsulate the arguments layer, instead of specially handle them every time.

**Review by eurekaka — COMMENTED** [review]
LGTM

**Comment by eurekaka** [comment]
@winoros please take a look at this PR again since it is a completely new solution now.

**Comment by time-and-fate** [comment]
Discussed this with winoros.
He has checked this change and is ok with this.

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
