### PR TITLE
executor: reject setting read ts to a future time

### LINKED ISSUE #25680: Don't allow reading a snapshot with the timestamp greater than the current max timestamp
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiDB can read data with a user-defined timestamp(using `tidb_snapshot` or stale-read) which may be greater than the current max timestamp in PD. It can update the max_ts in TiKV and the async-commit transaction may commit data with the version which is greater than the next timestamp in PD, so the following transactions can't read it which means the transaction isolation is broken.

### 2. What did you expect to see? (Required)

TiDB doesn't allow setting snapshot with the version which is greater than the current max version.

### 3. What did you see instead (Required)
```
mysql root@127.0.0.1:test> set @@tidb_snapshot = '2022-06-24 16:59:02';
Query OK, 0 rows affected
Time: 0.022s
```

### 4. What is your TiDB version? (Required)

v5.0.0-v5.0.2

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

Issue Number: close #25680

### What is changed and how it works?

This PR checks the read ts in two cases:

* Set by `tidb_snapshot` system variable
* Stale read

It first checks with latest local timestamp (with low cost). If the check fails, it gets a timestamp from PD to do a double check.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
- Breaking backward compatibility

### Release note 

- Do not allow setting read timestamp to a future time.

### CODE REVIEW

**Comment by sticnarf** [comment]
cc @NingLin-P 
Does the timestamp of stale read need to be checked? I don't know whether "stale read" with a future time must be supported.

**Comment by NingLin-P** [comment]
> cc @NingLin-P
> Does the timestamp of stale read need to be checked? I don't know whether "stale read" with a future time must be supported.

I think stale read need to check too, using stale read with a future time seems have no use case and benefit. /cc @nolouch

**Comment by nolouch** [comment]
> > cc @NingLin-P
> > Does the timestamp of stale read need to be checked? I don't know whether "stale read" with a future time must be supported.
> 
> I think stale read need to check too, using stale read with a future time seems have no use case and benefit. /cc @nolouch

Better to have, but I think the resolution `2s` of `GetLowResolutionTimestamp` may not suitable to stale read because stale read supports `Bound Read`, which means user want to read new data as soon as possible. or users may read data with`Now() - Interval 1 Second` although we recommend the best practice is around `Now() -  Interval 5 second`.

File: sessionctx/context.go [hunk 1]
```diff
@@ -149,3 +151,20 @@ const (
...
 	LastExecuteDDL basicCtxType = 3
 )
+
+// ValidateReadTS validates that readTS does not exceed the current timestamp
+func ValidateReadTS(ctx context.Context, sctx Context, readTS uint64) error {
+	txnScope := sctx.GetSessionVars().CheckAndGetTxnScope()
+	latestTS, err := sctx.GetStore().GetOracle().GetLowResolutionTimestamp(ctx, &oracle.Option{TxnScope: txnScope})
+	// If we fail to get latestTS or the readTS exceeds it, get a timestamp from PD to double check
+	if err != nil || readTS > latestTS {
+		currentVer, err := sctx.GetStore().CurrentVersion(txnScope)
```
Comment (nolouch) [inline sessionctx/context.go:161]: How about use `GetOracle().GetStaleTimestamp(ctx, txnScope, 0)`

File: executor/set.go [hunk 2]
```diff
@@ -159,15 +160,23 @@ func (e *SetExecutor) setSysVariable(name string, v *expression.VarAssignment) e
...
-		if err != nil {
+	if newSnapshotIsSet {
+		if err = sessionctx.ValidateReadTS(ctx, e.ctx, newSnapshotTS); err != nil {
 			fallbackOldSnapshotTS()
 			return err
 		}
+
+		// We don't check snapshot with gc safe point for read_ts
+		// Client-go will automatically check the snapshotTS with gc safe point. It's unnecessary to check gc safe point during set executor.
+		if name != variable.TiDBTxnReadTS {
```
Comment (nolouch) [inline executor/set.go:171]: There are other executors that need to be validated according to the [syntaxs](https://docs.pingcap.com/tidb/dev/as-of-timestamp#syntax), how about check it in client-go, the request must have `StaleRead` flag.

File: sessionctx/context.go (hunk 1 above)
Comment (sticnarf) [reply sessionctx/context.go:161]: Can I use `GetOracle().GetStaleTimestamp(ctx, txnScope, 0)` to replace L158, which is a fast path that does not involve an RPC?

File: executor/set.go (hunk 2 above)
Comment (sticnarf) [reply executor/set.go:171]: If possible, I want to validate it when setting the timestamp. Otherwise, it looks counter-intuitive to report it until doing actual reads.

File: sessionctx/context.go (hunk 1 above)
Comment (sticnarf) [reply sessionctx/context.go:161]: I'm afraid there is some risk. The timestamp from `GetStaleTimestamp` is calculated from the local time. If there is some clock drift, the timestamp may exceed the max ts in PD and still pass the validation. Then, it will break transactions.

File: executor/set.go (hunk 2 above)
Comment (NingLin-P) [reply executor/set.go:171]: FYI, the check of `start_ts < GC safe point` is also inside client-go

File: sessionctx/context.go (hunk 1 above)
Comment (nolouch) [reply sessionctx/context.go:161]: Does tikv/tikv#10443 already make the stale read not break a transaction in TiKV? Validate in TiDB should be pre-check and make the request fail fast. If you think that isn't a good way, maybe add metrics about how many request will validate from PD.

**Review by nolouch — COMMENTED** [review]
rest LGTM

File: sessionctx/context.go (hunk 1 above)
Comment (sticnarf) [reply sessionctx/context.go:161]: I hope to reuse it to also check for `tidb_snapshot`. It is not a stale read request, so it may still advance the `max_ts` in TiKV and break a transaction.

Anyway, it is a good idea to add metrics for it.

File: executor/set.go [hunk 3]
```diff
@@ -159,15 +160,28 @@ func (e *SetExecutor) setSysVariable(name string, v *expression.VarAssignment) e
...
+		}
 		if err != nil {
 			fallbackOldSnapshotTS()
 			return err
 		}
+
+		// We don't check snapshot with gc safe point for read_ts
+		// Client-go will automatically check the snapshotTS with gc safe point. It's unnecessary to check gc safe point during set executor.
+		if name != variable.TiDBTxnReadTS {
+			err = gcutil.ValidateSnapshot(e.ctx, newSnapshotTS)
```
Comment (youjiali1995) [inline executor/set.go:177]: How about moving it to line 165?

**Review by youjiali1995 — APPROVED** [review]

**Comment by youjiali1995** [comment]
@nolouch PTAL

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
some tests need to fix.

File: sessionctx/context.go [hunk 4]
```diff
@@ -149,3 +152,40 @@ const (
 	// LastExecuteDDL is the key for whether the session execute a ddl command last time.
 	LastExecuteDDL basicCtxType = 3
 )
+
+// ValidateSnapshotReadTS strictly validates that readTS does not exceed the PD timestamp
+func ValidateSnapshotReadTS(ctx context.Context, sctx Context, readTS uint64) error {
+	txnScope := sctx.GetSessionVars().CheckAndGetTxnScope()
```
Comment (Yisaer) [inline sessionctx/context.go:158]: Maybe we should use `oracle.GlobalTxnScope` directly?

File: sessionctx/context.go [hunk 5]
```diff
@@ -149,3 +152,40 @@ const (
...
+		if readTS > currentVer.Ver {
+			return errors.Errorf("cannot set read timestamp to a future time")
+		}
+	}
+	return nil
+}
+
+// ValidateStaleReadTS validates that readTS does not exceed the current time not strictly.
+func ValidateStaleReadTS(ctx context.Context, sctx Context, readTS uint64) error {
+	txnScope := sctx.GetSessionVars().CheckAndGetTxnScope()
```
Comment (Yisaer) [inline sessionctx/context.go:176]: ditto.

File: sessionctx/context.go (hunk 4 above)
Comment (sticnarf) [reply sessionctx/context.go:159]: Ah, yes. This looks safer.

File: sessionctx/context.go (hunk 5 above)
Comment (sticnarf) [reply sessionctx/context.go:180]: Does the check for stale read need to use global scope? This can be not strict so I guess a close PD would suffice?

**Comment by youjiali1995** [comment]
@Yisaer PTAL again, thanks!

File: sessionctx/context.go (hunk 5 above)
Comment (Yisaer) [reply sessionctx/context.go:179]: `GetStaleTimestamp` is directly visit the cache in memory, so I think it's ok to use `oracle.GlobalTxnScope`.

Comment (Yisaer) [reply sessionctx/context.go:179]: By the way, if you insist on using `txnScope` here, there should be `config.GetTxnScopeFromConfig`

**Review by Yisaer — COMMENTED** [review]
Rest LGTM

File: sessionctx/context.go (hunk 5 above)
Comment (sticnarf) [reply sessionctx/context.go]: OK, I change to use global scope. I think there's little difference.

**Comment by youjiali1995** [comment]
> @Yisaer PTAL again, thanks!

@Yisaer again...

**Review by Yisaer — APPROVED** [review]
