### PR TITLE
fix(runaway): resolve the dead channel in UpdateNewAndDoneWatch

### LINKED ISSUE #61782: dead chanel in UpdateNewAndDoneWatch
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

It started here

https://github.com/pingcap/tidb/blob/e601725d7fd0389107e9848a5f3182e05e0b9d98/pkg/domain/runaway.go#L75-L80

will insert record into channels here

https://github.com/pingcap/tidb/blob/6a12f31171dda2ef20ad4f81f6b2cd95bf13feab/pkg/resourcegroup/runaway/manager.go#L424-L426
The receive loop however is started later than the first call of `UpdateNewAndDoneWatch(RunawayRecordFlushLoop)`

https://github.com/pingcap/tidb/blob/6a12f31171dda2ef20ad4f81f6b2cd95bf13feab/pkg/resourcegroup/runaway/manager.go#L211

If the channel exceeds the maximum(1024), it blocks.

introduced by #52283

### 2. What did you expect to see? (Required)

non blocking.

### 3. What did you see instead (Required)

`runawayStartLoop` blocks forever

### 4. What is your TiDB version? (Required)

v8.1.0 and later

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #61782.

Problem Summary:

Revert #52283 and implement a simpler method to prevent error logs.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

Mannually modify `maxWatchRecordChannelSize` to 10 to ensure easier triggering.

image

Before:

image

After:

image

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Resolve the issue causing system table read/write operations related to runaways to hang after restarting TiDB instance.
```

### CODE REVIEW

**Review by okJiang — APPROVED** [review]

File: pkg/resourcegroup/tests/resource_group_test.go [hunk 1]
```diff
@@ -468,7 +460,7 @@ func TestResourceGroupRunawayFlood(t *testing.T) {
 	defer func() {
 		require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/pkg/resourcegroup/runaway/FastRunawayGC"))
 	}()
-	store, dom := testkit.CreateMockStoreAndDomain(t)
+	store, _ := testkit.CreateMockStoreAndDomain(t)
```
Comment (lance6716) [inline pkg/resourcegroup/tests/resource_group_test.go]:
```suggestion
	store := testkit.CreateMockStore(t)
```

**Comment by okJiang** [comment]
Do we need to add some tests for this issue?

File: pkg/resourcegroup/tests/resource_group_test.go [hunk 2]
```diff
@@ -337,7 +337,7 @@ func TestResourceGroupRunaway(t *testing.T) {
...
```
Comment (lance6716) [inline pkg/resourcegroup/tests/resource_group_test.go]:
```suggestion
	store := testkit.CreateMockStore(t)
```

File: pkg/resourcegroup/runaway/syncer.go [hunk 3]
```diff
@@ -45,12 +44,30 @@ func newSyncer(sysSessionPool util.SessionPool) *syncer {
...
 
+func (s *syncer) checkWatchTableExist() bool {
+	return s.checkTableExist("tidb_runaway_watch")
+}
+
+func (s *syncer) checkWatchDoneTableExist() bool {
+	return s.checkTableExist("tidb_runaway_watch_done")
+}
+
+func (s *syncer) checkTableExist(tableName string) bool {
```
Comment (lance6716) [inline pkg/resourcegroup/runaway/syncer.go]: I'm a bit worried that mixing `err != nil` with other condition will cause problem. For example, somehow `sysSessionPool` has a problem and `ExecRCRestrictedSQL` always fail. And caller will just think related table is not initialized, the functionality will not work and no log indicating the root cause.

How about return `(bool, error)` here? We still log something when there's error

Comment (xhebox) [reply pkg/resourcegroup/runaway/syncer.go]: Then we will have lots of log again as proposed in your issue? maybe adding 

`if count %= runawayLoopLogErrorIntervalCount; count == 0 {`
or
`if count > initRetryCount {`

Comment (lance6716) [reply pkg/resourcegroup/runaway/syncer.go]: We can use https://github.com/pingcap/tidb/blob/8e6d77ae274fa73225a1efd485af08509e15e8f6/pkg/util/logutil/log.go#L437-L443

And I want to express when return `(false /* found */, nil /* error */)`there should be no log, we can just silently wait the table to be created. For `(..., not-nil)` we can use above sampled logger to print the error

**Comment by JmPotato** [comment]
> Do we need to add some tests for this issue?

I have added the manual test results in the PR description, please take a look.

**Review by xhebox — APPROVED** [review]
