### PR TITLE
Lightning: support multiple PD addresses

### LINKED ISSUE #49515: Lightning : support of multiple PD addresses in lightning config file
## Enhancement
Lightning doesn't support multiple PD addresses in config file. It made to lightning to fail if that PD address is down before import is started.

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What problem does this PR solve?

Issue Number: close #49515

Problem Summary:
Lightning doesn't support multiple PD addresses in config file. It made to lightning to fail if that PD address is down before import is started.
### What changed and how does it work?
It is a simple fix as PD client already supports multiple PD addresses. We only need to parse it correctly and give to list of PD addresses while creating the PD client. 
### Check List

Tests 
- [X] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

It is tested in 6.5 and already deployed to production cluster

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [X] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
There is an easy way to add an integration test, we use `run_lightning` script file to start lightning and it can accept command line arguments. 

https://github.com/pingcap/tidb/blob/23953a7cbe82a18390f2a213777a57f48e203d18/br/tests/_utils/run_lightning#L28-L34

So we can modify any run_lightning and add a fake PD addresses in test scripts. Like change

https://github.com/pingcap/tidb/blob/23953a7cbe82a18390f2a213777a57f48e203d18/br/tests/lightning_pd_leader_switch/run.sh#L51

to 

```bash
run_lightning --backend local --enable-checkpoint=0 --pd-urls '127.0.0.1:9999,127.0.0.1:2379' &
```

File: br/pkg/lightning/config/config.go [hunk 1]
```diff
@@ -214,10 +214,7 @@ func (d *DBStore) adjust(
 		if d.Port <= 0 {
 			d.Port = int(settings.Port)
 		}
-		if len(d.PdAddr) == 0 {
-			pdAddrs := strings.Split(settings.Path, ",")
-			d.PdAddr = pdAddrs[0] // FIXME support multiple PDs once importer can.
-		}
+		d.PdAddr = settings.Path
```
Comment (lyzx2001) [inline br/pkg/lightning/config/config.go:217]: we still need to first check `if len(d.PdAddr) == 0`, then do `d.PdAddr = settings.Path`

**Review by lyzx2001 — COMMENTED** [review]
rest lgtm

**Comment by lyzx2001** [comment]
CI:
```
==================== Test output for //br/pkg/lightning/config:config_test (shard 14 of 47):
=== RUN   TestInvalidPDAddr
    config_test.go:294: 
        	Error Trace:	br/pkg/lightning/config/config_test.go:294
        	Error:      	An error is expected but got nil.
        	Test:       	TestInvalidPDAddr
--- FAIL: TestInvalidPDAddr (0.00s)
FAIL
--
```

Need to check whether the PD address is valid before creating the PD client.

**Comment by mittalrishabh** [comment]
> config_test.go

Is it a valid test case in lightning who is just the caller of PD client. It should be a test case inside PD client. PD client should fail if there is invalid address.

**Comment by lance6716** [comment]
lightning integration tests failed because when lightning starts, it tried to connect the first (dead) PD address for 2 minutes. And tests can't tolerate such a long backoff.

https://github.com/pingcap/tidb/blob/210bc420e2131753340fd7b0ac7a4039ab0847c5/br/pkg/pdutil/pd.go#L144-L161

```
[2023/12/19 15:01:44.173 +08:00] [INFO] [lightning.go:568] ["acquired keyspace name"] [keyspaceName=]
[2023/12/19 15:01:44.239 +08:00] [WARN] [pd.go:190] ["request failed, will retry later"] [url=https://127.0.0.1:9999/pd/api/v1/config/cluster-version] [retry-count=1] [error="Get \"https://127.0.0.1:9999/pd/api/v1/config/cluster-version\": dial tcp 127.0.0.1:9999: connect: connection refused"]
[2023/12/19 15:01:45.240 +08:00] [WARN] [pd.go:190] ["request failed, will retry later"] [url=https://127.0.0.1:9999/pd/api/v1/config/cluster-version] [retry-count=2] [error="Get \"https://127.0.0.1:9999/pd/api/v1/config/cluster-version\": dial tcp 127.0.0.1:9999: connect: connection refused"]
```

In future release version, PD will provide a [HTTP client](https://github.com/tikv/pd/issues/7300) which will handle the retry internally, lightning will adapt the new PD HTTP client interface and remove this retry in future PR.

So currently I think we only add a TODO in the lightning integration tests (sorry for my previous comments 😂 ), I will solve it in future. And also remind your cluster will retry a dead PD address for 2 minutes when starts.

**Comment by lyzx2001** [comment]
> > config_test.go
> 
> Is it a valid test case in lightning who is just the caller of PD client. It should be a test case inside PD client. PD client should fail if there is invalid address.

I checked and it is a valid test. Since previously the code does not support multiple PD addresses, here it first uses "," to split the addresses and take the first one to be pd address, then in this test it would detect 
https://github.com/pingcap/tidb/blob/210bc420e2131753340fd7b0ac7a4039ab0847c5/br/pkg/lightning/config/config.go#L227-L229
and return the error, which is expected by the test.

Now you have changed it to first assign `settings.Path` to `d.PdAddr`, then split the addresses later, so here this test would fail since it will not detect that `mustHaveInternalConnections && len(d.PdAddr) == 0`. So I think here you need to revise the checking process of whether pd address is valid. You can still split `settings.Path` and check whether there is at least one address that is not nil in the splitting result, and still assign `settings.Path` to `d.PdAddr`. The splitting here is purely for the checking purpose.

**Comment by mittalrishabh** [comment]
> lightning integration tests failed because when lightning starts, it tried to connect the first (dead) PD address for 2 minutes. And tests can't tolerate such a long backoff.
> 
> https://github.com/pingcap/tidb/blob/210bc420e2131753340fd7b0ac7a4039ab0847c5/br/pkg/pdutil/pd.go#L144-L161
> 
> ```
> [2023/12/19 15:01:44.173 +08:00] [INFO] [lightning.go:568] ["acquired keyspace name"] [keyspaceName=]
> [2023/12/19 15:01:44.239 +08:00] [WARN] [pd.go:190] ["request failed, will retry later"] [url=https://127.0.0.1:9999/pd/api/v1/config/cluster-version] [retry-count=1] [error="Get \"https://127.0.0.1:9999/pd/api/v1/config/cluster-version\": dial tcp 127.0.0.1:9999: connect: connection refused"]
> [2023/12/19 15:01:45.240 +08:00] [WARN] [pd.go:190] ["request failed, will retry later"] [url=https://127.0.0.1:9999/pd/api/v1/config/cluster-version] [retry-count=2] [error="Get \"https://127.0.0.1:9999/pd/api/v1/config/cluster-version\": dial tcp 127.0.0.1:9999: connect: connection refused"]
> ```
> 
> In future release version, PD will provide a [HTTP client](https://github.com/tikv/pd/issues/7300) which will handle the retry internally, lightning will adapt the new PD HTTP client interface and remove this retry in future PR.
> 
> So currently I think we only add a TODO in the lightning integration tests (don't need to add 172.0.0.1:9999, sorry for my previous comments 😂 ), I will solve it in future. And also remind your cluster will retry a dead PD address for 2 minutes when starts.

Is this test failing even without this change ?

File: br/pkg/lightning/config/config_test.go [hunk 2]
```diff
@@ -273,6 +273,7 @@ func TestInvalidSetting(t *testing.T) {
 	cfg.TikvImporter.SortedKVDir = "."
 	cfg.TiDB.DistSQLScanConcurrency = 1
 	cfg.Mydumper.SourceDir = "."
+	cfg.TiDB.PdAddr = "234.56.78.90:12345"
```
Comment (lance6716) [inline br/pkg/lightning/config/config_test.go:276]: I checked that in master branch test still passes with this line. Is it needed?

**Comment by lance6716** [comment]
> Is this test failing even without this change ?

No with the old test script lightning only see one valid PD address. Lightning will connect to it **quickly** and through PD client's peer discovery functionality it will see 3 PD servers. Then `lightning_pd_leader_switch` test will wait 45 seconds and kill the first PD, to see lightning still uses the rest PD.

But with `127.0.0.1:9999,127.0.0.1:2379` lightning will waste time to connect to the dead PD address 9999. And before it get timeout (2 minutes) and try 2379, 2379's PD is killed by test script. So lightning can't connect to any PD when starts and test fails.

File: br/pkg/lightning/config/config_test.go (hunk 2 above)
Comment (lance6716) [reply br/pkg/lightning/config/config_test.go:276]: Hi, please check if this change is needed @mittalrishabh

Comment (mittalrishabh) [reply br/pkg/lightning/config/config_test.go:276]: i think i added to fix the CI test failure. Let me try removing it.

Comment (mittalrishabh) [reply br/pkg/lightning/config/config_test.go:276]: Yes, this change is required with my changes. Otherwise CI fail. If PD address is not given than it throws invalid tidb address but test case is expecting invalid port address.

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
ptal @lyzx2001

**Review by lyzx2001 — APPROVED** [review]
LGTM
