### PR TITLE
ddl: refine error messages in unsupported column options

### LINKED ISSUE #10731: unsupported modify column %!s(ast.ColumnOptionType=12)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`CREATE TABLE `t1` (
  b char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ;

ALTER TABLE t1  MODIFY COLUMN b char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;`

2. What did you expect to see?

3. What did you see instead?

unsupported modify column %!s(ast.ColumnOptionType=12)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v3.0.0-rc.2
Git Commit Hash: 06f3f63d5a87e7f0436c0618cf524fea7172eb93
Git Branch: HEAD
UTC Build Time: 2019-05-28 12:48:52
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

I would got the error when I used COLLATE.

### LINKED ISSUE #11052: Cannot change column collation from `utf8mb4_general_ci` to `utf8mb4_general_ci`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table t (b char(1) collate utf8mb4_general_ci);
alter table t modify b char(1) character set utf8mb4 collate utf8mb4_general_ci;
```
2. What did you expect to see?
In MySQL 5.7:
```sql
Query OK (0.059 sec)
```

3. What did you see instead?
In TiDB:
```sql
Error 1105: unsupported modify collate from utf8mb4_general_ci to utf8mb4_bin
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```sql
+--------------------------------------------------------------------------+
| tidb_version()                                                           |
+--------------------------------------------------------------------------+
| Release Version: v3.0.0-rc.1-271-gf56ef0064                              |
| Git Commit Hash: f56ef00649ec388b1ac3989f8009442f3be4e299                |
| Git Branch: master                                                       |
| UTC Build Time: 2019-07-03 08:47:32                                      |
| GoVersion: go version go1.12.5 linux/amd64                               |
| Race Enabled: false                                                      |
| TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
| Check Table Before Drop: false                                           |
+--------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 

Fix #10731 and fix #11052.

### What is changed and how it works?

1.  Add more cases in `switch` in `processColumnOptions()`, avoiding the obscure error message in #10731. 

2.  `getModifiableColumnJob()` is used to build a `ActionModifyColumn` DDL job. It contains two methods:
    - `modifiable()`, check whether the FieldType of the origin column can be changed into the new column. The checks include charset, collation, types, Flen/Decimal, etc.
    - `processColumnOptions()`, set FieldType of the new column, according to `Option` in `ColumnDef`, which is filled by SQL parser.

    Obviously, we should first set the FieldType and then check it. So `processColumnOptions()` should come first.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -2512,8 +2512,13 @@ func processColumnOptions(ctx sessionctx.Context, col *table.Column, options []*
...
 			}
+		case ast.ColumnOptionCollate:
+			col.Collate = opt.StrValue
+		case ast.ColumnOptionReference:
+			return errors.Trace(errUnsupportedModifyColumn.GenWithStackByArgs("with references"))
+		case ast.ColumnOptionFulltext:
+			return errors.Trace(errUnsupportedModifyColumn.GenWithStackByArgs("with full text"))
 		default:
-			// TODO: Support other types.
 			return errors.Trace(errUnsupportedModifyColumn.GenWithStackByArgs(opt.Tp))
```
Comment (zimulala) [inline ddl/ddl_api.go]: The error message is `%!s(ast.ColumnOptionType=12)`.
It seems the type of  `opt.Tp` is `ColumnOptionType` instead of `String`. I think we need to update this code.

Comment (tangenta) [reply ddl/ddl_api.go]: The `default` clause is impossible to reach.

Comment (tangenta) [reply ddl/ddl_api.go]: Currently, the `default` clause is impossible to reach. Could we just remove it?

Comment (zimulala) [reply ddl/ddl_api.go]: If there are new options added later, is it better to have this `default`?

Comment (tangenta) [reply ddl/ddl_api.go]: Updated.

**Comment by AilinKid** [comment]
I have tried following SQL on the code, but got following error:
ERROR 1105 (HY000): unsupported modify collate from utf8mb4_bin to utf8mb4_general_ci
Maybe be we should put the `modifiable()` func first, and that's actually works.

>CREATE TABLE t6(a char(1))DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ;
>
>ALTER TABLE t6 MODIFY COLUMN a char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;

**Comment by tangenta** [comment]
@AilinKid Which TiDB version did you use?
```sql
mysql root@127.0.0.1:test> CREATE TABLE t6(a char(1))DEFAULT CHARSET=utf8mb4 COL
                           LATE=utf8mb4_general_ci ;                            
Query OK, 0 rows affected
Time: 0.014s
mysql root@127.0.0.1:test> ALTER TABLE t6 MODIFY COLUMN a char(1) CHARACTER SET 
                           utf8mb4 COLLATE utf8mb4_general_ci ;                 
Query OK, 0 rows affected
Time: 0.014s
mysql root@127.0.0.1:test> select tidb_version();                               
1 row in set
Time: 0.029s
mysql root@127.0.0.1:test> select tidb_version();                                                                                                                                                                                                             
+--------------------------------------------------------------------------+
| tidb_version()                                                           |
+--------------------------------------------------------------------------+
| Release Version: v3.0.0-rc.1-309-g34720acda                              |
| Git Commit Hash: 34720acda1eec86ff93494c8890cb2a1b4d6d478                |
| Git Branch: changing-collation                                           |
| UTC Build Time: 2019-07-10 09:12:23                                      |
| GoVersion: go version go1.12.5 linux/amd64                               |
| Race Enabled: false                                                      |
| TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
| Check Table Before Drop: false                                           |
+--------------------------------------------------------------------------+
1 row in set
Time: 0.015s
```
git log:
```bash
commit 34720acda1eec86ff93494c8890cb2a1b4d6d478 (HEAD -> changing-collation, origin/changing-collation)
Author: tangenta <tangenta@126.com>
Date:   Wed Jul 10 15:39:13 2019 +0800

    refine error message
```

**Comment by AilinKid** [comment]
> @AilinKid Which TiDB version did you use?
> 
> ```sql
> mysql root@127.0.0.1:test> CREATE TABLE t6(a char(1))DEFAULT CHARSET=utf8mb4 COL
>                            LATE=utf8mb4_general_ci ;                            
> Query OK, 0 rows affected
> Time: 0.014s
> mysql root@127.0.0.1:test> ALTER TABLE t6 MODIFY COLUMN a char(1) CHARACTER SET 
>                            utf8mb4 COLLATE utf8mb4_general_ci ;                 
> Query OK, 0 rows affected
> Time: 0.014s
> mysql root@127.0.0.1:test> select tidb_version();                               
> 1 row in set
> Time: 0.029s
> mysql root@127.0.0.1:test> select tidb_version();                                                                                                                                                                                                             
> +--------------------------------------------------------------------------+
> | tidb_version()                                                           |
> +--------------------------------------------------------------------------+
> | Release Version: v3.0.0-rc.1-309-g34720acda                              |
> | Git Commit Hash: 34720acda1eec86ff93494c8890cb2a1b4d6d478                |
> | Git Branch: changing-collation                                           |
> | UTC Build Time: 2019-07-10 09:12:23                                      |
> | GoVersion: go version go1.12.5 linux/amd64                               |
> | Race Enabled: false                                                      |
> | TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
> | Check Table Before Drop: false                                           |
> +--------------------------------------------------------------------------+
> 1 row in set
> Time: 0.015s
> ```
> 
> git log:
> 
> ```shell
> commit 34720acda1eec86ff93494c8890cb2a1b4d6d478 (HEAD -> changing-collation, origin/changing-collation)
> Author: tangenta <tangenta@126.com>
> Date:   Wed Jul 10 15:39:13 2019 +0800
> 
>     refine error message
> ```

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -2520,9 +2520,14 @@ func processColumnOptions(ctx sessionctx.Context, col *table.Column, options []*
...
+		case ast.ColumnOptionCollate:
+			col.Collate = opt.StrValue
+		case ast.ColumnOptionReference:
+			return errors.Trace(errUnsupportedModifyColumn.GenWithStackByArgs("with references"))
+		case ast.ColumnOptionFulltext:
+			return errors.Trace(errUnsupportedModifyColumn.GenWithStackByArgs("with full text"))
 		default:
-			// TODO: Support other types.
-			return errors.Trace(errUnsupportedModifyColumn.GenWithStackByArgs(opt.Tp))
+			return errors.Trace(errUnsupportedModifyColumn.GenWithStackByArgs("unknown column option type"))
```
Comment (crazycs520) [inline ddl/ddl_api.go]: Add option type value to error msg?

Comment (tangenta) [reply ddl/ddl_api.go]: Updated.

**Comment by AilinKid** [comment]
LGTM
