### PR TITLE
test: fix a leak in CampaignOwner()

### LINKED ISSUE #18050: leak in CampaignOwner()
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.625+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":92,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.652+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":93,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.679+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":94,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.703+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":95,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.731+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":96,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.758+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":97,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.787+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":98,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] {"level":"warn","ts":"2020-06-16T10:39:12.810+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c129045e-2748-4f3b-9ab3-d050bcd09c50/localhost:1806743554768154560","attempt":99,"error":"rpc error: code = Canceled desc = grpc: the client connection is closing"}
[2020-06-16T02:39:13.845Z] [2020/06/16 10:39:12.810 +08:00] [INFO] [manager.go:296] ["revoke session"] ["owner info"="[ddl] /tidb/ddl/fg/owner ownerManager e2852ce5-a041-43d8-bf5f-3698d7df9222"] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2020-06-16T02:39:13.845Z] --- FAIL: TestInfo (2.75s)
[2020-06-16T02:39:13.845Z]     leaktest.go:155: Test TestInfo check-count 50 appears to have leaked: go.etcd.io/etcd/clientv3.waitRetryBackoff(0x3c4cc60, 0xc007dfc960, 0x63, 0xc007bd34a0, 0x3, 0x3)
[2020-06-16T02:39:13.845Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/clientv3/retry_interceptor.go:267 +0xfd
[2020-06-16T02:39:13.845Z]         go.etcd.io/etcd/clientv3.(*Client).unaryClientInterceptor.func1(0x3c4cc60, 0xc007dfc960, 0x36a95b9, 0x1f, 0x346ca40, 0xc0034ec1c0, 0x3454320, 0xc0036e6160, 0xc000dcae00, 0x3749528, ...)
[2020-06-16T02:39:13.845Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/clientv3/retry_interceptor.go:49 +0x14f
[2020-06-16T02:39:13.845Z]         google.golang.org/grpc.(*ClientConn).Invoke(0xc000dcae00, 0x3c4cc60, 0xc007dfc960, 0x36a95b9, 0x1f, 0x346ca40, 0xc0034ec1c0, 0x3454320, 0xc0036e6160, 0xc007dfc9c0, ...)
[2020-06-16T02:39:13.845Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/google.golang.org/grpc@v1.26.0/call.go:35 +0x109
[2020-06-16T02:39:13.845Z]         google.golang.org/grpc.Invoke(...)
[2020-06-16T02:39:13.845Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/google.golang.org/grpc@v1.26.0/call.go:60
[2020-06-16T02:39:13.845Z]         go.etcd.io/etcd/etcdserver/etcdserverpb.(*leaseClient).LeaseRevoke(0xc0076f0058, 0x3c4cc60, 0xc007dfc960, 0xc0034ec1c0, 0xc007dfc9c0, 0x4, 0x6, 0x6, 0x125f608, 0x10)
[2020-06-16T02:39:13.845Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/etcdserver/etcdserverpb/rpc.pb.go:3801 +0xcf
[2020-06-16T02:39:13.845Z]         go.etcd.io/etcd/clientv3.(*retryLeaseClient).LeaseRevoke(0xc003fb47d0, 0x3c4cc60, 0xc007dfc960, 0xc0034ec1c0, 0x5912040, 0x3, 0x3, 0x3c4cc60, 0xc007dfc960, 0xc004815490)
[2020-06-16T02:39:13.846Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/clientv3/retry.go:148 +0xeb
[2020-06-16T02:39:13.846Z]         go.etcd.io/etcd/clientv3.(*lessor).Revoke(0xc0005903c0, 0x3c4cc60, 0xc007dfc960, 0x169372bafea52005, 0xc007dfc960, 0xc004815490, 0x0)
[2020-06-16T02:39:13.846Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/clientv3/lease.go:231 +0x92
[2020-06-16T02:39:13.846Z]         github.com/pingcap/tidb/owner.(*ownerManager).revokeSession(0xc00401e300, 0xc000304500, 0x4a, 0x169372bafea52005)
[2020-06-16T02:39:13.846Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/owner/manager.go:294 +0xaa
[2020-06-16T02:39:13.846Z]         github.com/pingcap/tidb/owner.(*ownerManager).campaignLoop(0xc00401e300, 0xc0007b03f0)
[2020-06-16T02:39:13.846Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/owner/manager.go:248 +0x10b7
[2020-06-16T02:39:13.846Z]         created by github.com/pingcap/tidb/owner.(*ownerManager).CampaignOwner
[2020-06-16T02:39:13.846Z]         	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/owner/manager.go:190 +0x312
[2020-06-16T02:39:13.846Z] FAIL
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #18050 

### What is changed and how it works?

When canceling the campaign, wait until it exits.

### Related changes
- Need to cherry-pick to the release branch

### Check List 

Tests 

Side effects

### Release note 

- No release note

### CODE REVIEW

File: owner/manager.go [hunk 1]
```diff
@@ -228,6 +232,7 @@ func (m *ownerManager) campaignLoop(etcdSession *concurrency.Session) {
 			logutil.BgLogger().Error("recover panic", zap.String("prompt", m.prompt), zap.Any("error", r), zap.String("buffer", string(buf)))
 			metrics.PanicCounter.WithLabelValues(metrics.LabelDDLOwner).Inc()
 		}
+		m.wg.Done()
```
Comment (zimulala) [inline owner/manager.go:235]: If we call `ownerManager.Cancel()`, it seems that we will call `m.wg.Done()` twice.
