### PR TITLE
expression: fix wrong result when select with collation

### LINKED ISSUE #18662: select using collation get wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table t(a varchar(10) collate utf8mb4_bin, b varchar(10) collate utf8mb4_general_ci);
insert into t (a, b) values ('a', 'A');

select * from t where field('A', a collate utf8mb4_general_ci, b) > 1;
```

### 2. What did you expect to see? (Required)
```sql
mysql> select * from t where field('A', a collate utf8mb4_general_ci, b) > 1;
Empty set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> select * from t where field('A', a collate utf8mb4_general_ci, b) > 1;
+------+------+
| a    | b    |
+------+------+
| a    | A    |
+------+------+
1 row in set (0.00 sec)
```
### 4. Affected version (Required)
master

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close #18662 

### What changed
add `newBaseBuiltinFuncWithFieldType`, this function create a new `basebuiltinFunc` without check.

### How it works
remove unnecessary mix collation check, use collation decode from `pb` directly, do not re-calculate it. `pb` does not contains coercibility, re-calculate collation will get wrong result.

Tests 

- Unit test
- Integration test

### Release note 

- fix incorrect collator when `getSignatureByPB` and remove unnecessary recover

### CODE REVIEW

File: expression/distsql_builtin.go [hunk 1]
```diff
@@ -43,11 +43,21 @@ func PbTypeToFieldType(tp *tipb.FieldType) *types.FieldType {
 }
 
 func getSignatureByPB(ctx sessionctx.Context, sigCode tipb.ScalarFuncSig, tp *tipb.FieldType, args []Expression) (f builtinFunc, e error) {
+	if ctx == nil {
+		panic("ctx should not be nil")
```
Comment (bb7133) [inline expression/distsql_builtin.go:47]: Although there are `panic` codes already in TiDB, it is better to avoid it and return an `error`, since for the end-users, `panic` will lead to a closed connection rather than a simple `error` message.

File: expression/distsql_builtin.go [hunk 2]
```diff
@@ -1132,11 +1142,6 @@ func PBToExpr(expr *tipb.Expr, tps []*types.FieldType, sc *stmtctx.StatementCont
 		return nil, err
 	}
 
-	// recover collation information
-	if collate.NewCollationEnabled() {
```
Comment (bb7133) [inline expression/distsql_builtin.go:1136]: I don't get the point here, why we need to change the code here? What caused the issue?

Comment (xiongjiwei) [reply expression/distsql_builtin.go:1136]: code here is fine. but it seems it is duplicate and circular reference, we had already set `Charset` and `collation` in `getSignatureByPB`.

File: expression/distsql_builtin.go (hunk 1 above)
Comment (xiongjiwei) [reply expression/distsql_builtin.go:47]: sure, but what error should we return, I "panic" this because the original implement will `panic` in `newBaseBuiltinFunc` if `ctx` is `nil`

Comment (wjhuang2016) [reply expression/distsql_builtin.go:47]: I think we can remove this check.

File: expression/distsql_builtin.go [hunk 3]
```diff
@@ -43,11 +43,21 @@ func PbTypeToFieldType(tp *tipb.FieldType) *types.FieldType {
...
 
 func getSignatureByPB(ctx sessionctx.Context, sigCode tipb.ScalarFuncSig, tp *tipb.FieldType, args []Expression) (f builtinFunc, e error) {
+	if ctx == nil {
+		panic("ctx should not be nil")
+	}
 	fieldTp := PbTypeToFieldType(tp)
-	base, err := newBaseBuiltinFunc(ctx, fmt.Sprintf("PBSig-%v", sigCode), args)
-	if err != nil {
-		return nil, err
+	base := baseBuiltinFunc{
```
Comment (wjhuang2016) [inline expression/distsql_builtin.go:50]: I think we can use previous code `base, err := newBaseBuiltinFunc(ctx, fmt.Sprintf("PBSig-%v", sigCode), args)`

File: expression/distsql_builtin.go (hunk 2 above)
Comment (wjhuang2016) [reply expression/distsql_builtin.go:1136]: It seems that we can remove them?

Comment (xiongjiwei) [reply expression/distsql_builtin.go:1136]: @wjhuang2016 I think it is, we had already set `charset` and `collation` correct in `getSignatureByPB` no need to set again

File: expression/builtin.go [hunk 4]
```diff
@@ -243,6 +243,26 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, funcName string, args []Ex
 	return bf, nil
 }
 
+// newBaseBuiltinFuncWithFieldType create BaseBuiltinFunc with FieldType charset and collation.
+// do not check and compute collation.
+func newBaseBuiltinFuncWithFieldType(ctx sessionctx.Context, tp *types.FieldType, args []Expression) (baseBuiltinFunc, error) {
+	if ctx == nil {
+		panic("ctx should not be nil")
+	}
```
Comment (qw4990) [inline expression/builtin.go:251]: Please return an error here for safety instead of causing a panic.

**Comment by qw4990** [comment]
Should we pick this PR to v4.0? @wjhuang2016

File: expression/builtin.go (hunk 4 above)
Comment (xiongjiwei) [reply expression/builtin.go:251]: other two function `newBaseBuiltinFunc` `newBaseBuiltinFuncWithTp` will panic if `ctx` is `nil`, should we change them too?

Comment (qw4990) [reply expression/builtin.go:251]: Yes, I prefer to change them too, thanks~

**Comment by wjhuang2016** [comment]
> Should we pick this PR to v4.0? @wjhuang2016

Yeah

**Comment by XuHuaiyu** [comment]
LGTM
