### PR TITLE
executor: ignore foreign key error in `UPDATE/INSERT/DELETE ignore`

### LINKED ISSUE #39712: delete ignore foreign key check failed
## Reproduce

```sql
CREATE TABLE t1 (a INT PRIMARY KEY);
CREATE TABLE t2 (b INT);
INSERT INTO t1 VALUES (1), (2), (5);
INSERT INTO t2 VALUES (1), (5);
ALTER TABLE t2 ADD CONSTRAINT FOREIGN KEY(b) REFERENCES t1(a);
DELETE IGNORE FROM t1;
```

The last `DELETE` statement should execute success, but failed in TiDB.

```sql
> DELETE IGNORE FROM t1;
(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`test`.`t2`, CONSTRAINT `fk_1` FOREIGN KEY (`b`) REFERENCES `t1` (`a`))')
```

## TiDB Version

master: 2ea253e3180f53e700e76137a30e4a726c9936d7

### LINKED ISSUE #56678: `INSERT IGNORE ... ON DUPLICATE UPDATE ...` doesn't omit foreign key error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table parent (id int primary key);
create table child (id int primary key, ref int, foreign key (ref) references parent(id));
insert into parent values (1), (2);
insert into child values (1, 1);
insert into child values (1, 2) on duplicate key update ref = 3;
-- error 1452
insert into child values (1, 3) on duplicate key update ref = 3;
--enable_warnings
insert ignore into child values (1, 3) on duplicate key update ref = 3;
--disable_warnings
```

### 2. What did you expect to see? (Required)

`INSERT IGNORE` statement should have no error and return a warning.

### 3. What did you see instead (Required)

`INSERT IGNORE` still gives an error.

### LINKED ISSUE #56681: `UPDATE IGNORE` doesn't omit the foreign key error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists parent, child;
create table parent (id int primary key, ref int, key(ref));
create table child (id int primary key, ref int, foreign key (ref) references parent(ref));
insert into parent values (1, 1), (2, 2);
insert into child values (1, 1);

update child set ref = 2 where id = 1;
-- error 1452
update child set ref = 3 where id = 1;
--enable_warnings
update ignore child set ref = 3 where id = 1;
--disable_warnings

-- error 1451
update parent set ref = 3 where id = 2;
--enable_warnings
update ignore parent set ref = 3 where id = 2;
--disable_warnings
```

### 2. What did you expect to see? (Required)

TiDB doesn't return error for `UPDATE IGNORE` statement.

### 3. What did you see instead (Required)

TiDB returns error.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #56678, close #56681, close #39712

Problem Summary:

In the following cases, the foreign key error should be omitted and placed in the warning:

1. `INSERT IGNORE ... ON DUPLICATE UPDATE ...`
2. `DELETE IGNORE ...`
3. `UPDATE IGNORE ...`

### What changed and how does it work?

Introduce a function `checkFKIgnoreErr` to check rows explicitly, and use this function to check each rows in these three cases.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/delete.go [hunk 1]
```diff
@@ -128,6 +132,19 @@ func (e *DeleteExec) deleteSingleTableByChunk(ctx context.Context) error {
...
+				if err != nil {
+					return err
+				}
+
+				// meets an error, skip this row.
+				if fkToBeCheckedRows[0].ignored {
+					datumRow = datumRow[:0]
+					continue
+				}
+			}
```
Comment (crazycs520) [inline pkg/executor/delete.go:147]: How about move this into `removeRow`? 
this is duplicate with #251~#263

Comment (YangKeao) [reply pkg/executor/delete.go]: I prefer to keep it outside. If we move it inside the `removeRow`, we'll need to handle the error carefully to distinguish the error, the ignored error and success.

Instead, I change the implementation of `checkFKIgnoreErr` to integrate the declaration and usage of the `fkToBeCheckedRows[0]` usage, and make it easier to understand / use:

```go
func checkFKIgnoreErr(ctx context.Context, sctx sessionctx.Context, fkChecks []*FKCheckExec, row []types.Datum) (bool, error)
```

Now, only the `row` is needed, and it'll return whether an error has been ignored, or there is an unignorable error. The usage can be simpler:

```go
			if e.ignoreErr {
				ignored, err := checkFKIgnoreErr(ctx, e.Ctx(), e.fkChecks[tbl.Meta().ID], datumRow)
				if err != nil {
					return err
				}

				// meets an error, skip this row.
				if ignored {
					datumRow = datumRow[:0]
					continue
				}
			}
```

File: pkg/executor/delete.go [hunk 2]
```diff
@@ -223,13 +238,25 @@ func (e *DeleteExec) deleteMultiTablesByChunk(ctx context.Context) error {
...
 
-func (e *DeleteExec) removeRowsInTblRowMap(tblRowMap tableRowMapType) error {
+func (e *DeleteExec) removeRowsInTblRowMap(ctx context.Context, tblRowMap tableRowMapType) error {
 	for id, rowMap := range tblRowMap {
 		var err error
 		rowMap.Range(func(h kv.Handle, val handleInfoPair) bool {
+			if e.ignoreErr {
+				ignored, err := checkFKIgnoreErr(ctx, e.Ctx(), e.fkChecks[id], val.handleVal)
+				if err != nil {
+					return false
```
Comment (crazycs520) [inline pkg/executor/delete.go:251]: If return from here, will ignore the error?

Comment (YangKeao) [reply pkg/executor/delete.go:251]: Yes. It's expected. See the implementation of `checkFKIgnoreErr` and `fkc.checkRows`. If the row breaks the foreign key constraint, a warning will be appended and the function `checkFKIgnoreErr` will return `true, nil`. If the row has a wrong format, or it meets some network issues (or other errors not related to the foreign key), it'll return the error as `false, err`.

Previously, we already have an existing implementation of `INSERT ignore`. This PR keeps the same behavior with it.

File: pkg/executor/delete.go [hunk 3]
```diff
@@ -223,13 +238,25 @@ func (e *DeleteExec) deleteMultiTablesByChunk(ctx context.Context) error {
...
+	return e.removeRowsInTblRowMap(ctx, tblRowMap)
 }
 
-func (e *DeleteExec) removeRowsInTblRowMap(tblRowMap tableRowMapType) error {
+func (e *DeleteExec) removeRowsInTblRowMap(ctx context.Context, tblRowMap tableRowMapType) error {
 	for id, rowMap := range tblRowMap {
 		var err error
 		rowMap.Range(func(h kv.Handle, val handleInfoPair) bool {
+			if e.ignoreErr {
+				ignored, err := checkFKIgnoreErr(ctx, e.Ctx(), e.fkChecks[id], val.handleVal)
```
Comment (crazycs520) [inline pkg/executor/delete.go:249]:
```suggestion
				ignored, err = checkFKIgnoreErr(ctx, e.Ctx(), e.fkChecks[id], val.handleVal)
```

Comment (YangKeao) [reply pkg/executor/delete.go]: Done.

**Review by hawkingrei — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
