### PR TITLE
ddl, parser: fix concurrent rename table

### LINKED ISSUE #32610: Set default DDL still work after rename table, which cause TiCDC fail
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

1. Set up a TiDB cluster using Tiup
 ```
tiup  playground  v5.3.0 --tag 530.1   --db 1 --kv 3 --pd 1  --ticdc 1 
```
2. Create database schrddl for test
3. Using schrddl to test TiDB
```
go get github.com/PingCAP-QE/schrddl
GO111MODULE=on go build -o ./schrddl github.com/PingCAP-QE/schrddl
./schrddl --mode=parallel  --db="schrddl"  --time=30s  --concurrency=5 --output='schrddl.out'
```
4. Check the ddl history
```
curl  http://127.0.0.1:10080/ddl/history >> ddl.job
```

### 2. What did you expect to see? (Required)
ddl jobs run normal

### 3. What did you see instead (Required)
A strange DDL sequence
```
"query": "CREATE TABLE `e71e58cd-5e43-4138-9ebd-83280727eac1` (`321c2ad3-3f26-4e8c-90fd-adedf2fd1349` DECIMAL(19,7), `e12cbd81-31a9-4f74-9b07-c460eebbd04c` CHAR(107), PRIMARY KEY (`321c2ad3-3f26-4e8c-90fd-adedf2fd1349`, `e12cbd81-31a9-4f74-9b07-c460eebbd04c`)) COMMENT 'd3ce9d00-f1a7-41d0-a8b4-aa59d0883b59' CHARACTER SET 'utf8' COLLATE 'utf8_bin'",
 "query": "ALTER TABLE `e71e58cd-5e43-4138-9ebd-83280727eac1` RENAME AS `28bcfea3-0175-486e-b2f4-dbbade6fa6cf`",
"query": "ALTER TABLE `e71e58cd-5e43-4138-9ebd-83280727eac1` ALTER `e12cbd81-31a9-4f74-9b07-c460eebbd04c` SET DEFAULT 'xu3kigyzkibqhhtcf2tt1pi5il6b81getrxk4ovr6a686m68jouu6d01nah2htf7kcn5xz3h8zl'",
```

`Set default DDL` still work after  `rename table`， but it will cause error in TiCDC because after renaming the table, the original table doesn't exists any more.

related log: [归档.zip](https://github.com/pingcap/tidb/files/8130650/default.zip)

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:31:18
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #32610

Problem Summary:
We need to check if the table is renamed before executing a DDL

### What is changed and how it works?
Add tableName to job, and check if it is changed.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: ddl/db_change_test.go [hunk 1]
```diff
@@ -1991,3 +1992,120 @@ func (s *stateChangeSuite) TestRestrainDropColumnWithIndex() {
...
+	var concurrentDDLQuery string
+	firstDDL := true
+
+	var wg sync.WaitGroup
+	var checkErr error
+	d2 := d.DDL()
+	originalCallback := d2.GetHook()
+	defer d2.SetHook(originalCallback)
+	callback := &ddl.TestDDLCallback{Do: d}
+	callback.OnJobRunBeforeExported = func(job *model.Job) {
```
Comment (zimulala) [inline ddl/db_change_test.go:2019]: Could we use `testControlParallelExecSQL` directly?

Comment (wjhuang2016) [reply ddl/db_change_test.go:2019]: It needs to make some effort to use testControlParallelExecSQL.
1. testControlParallelExecSQL relies on stateChangeSuite.
2. It doesn't fit the new concurrent DDL framework.
3. It can't promise that ddl2 is run after dd1.

File: ddl/table.go [hunk 2]
```diff
@@ -919,6 +925,7 @@ func onRenameTables(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int64, _ error
 	var err error
 	for i, oldSchemaID := range oldSchemaIDs {
 		job.TableID = tableIDs[i]
+		job.TableName = oldTableNames[i].L
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply ddl/table.go:928]: We need to check all the tables. The adding code here is almost the same as `job.TableID = tableIDs[i]`

File: ddl/ddl_api.go [hunk 3]
```diff
@@ -5383,7 +5412,7 @@ func (d *ddl) RenameTables(ctx sessionctx.Context, oldIdents, newIdents []ast.Id
 		SchemaName: schemas[1].Name.L,
 		Type:       model.ActionRenameTables,
 		BinlogInfo: &model.HistoryInfo{},
-		Args:       []interface{}{oldSchemaIDs, newSchemaIDs, tableNames, tableIDs, oldSchemaNames},
+		Args:       []interface{}{oldSchemaIDs, newSchemaIDs, tableNames, tableIDs, oldSchemaNames, oldTableNames},
```
[the remark this answers is not in the document]
Comment (wjhuang2016) [reply ddl/ddl_api.go:5415]: `oldTableNames` likes `oldSchemaNames`. It's better to put them together.

File: ddl/db_change_test.go [hunk 4]
```diff
@@ -1991,3 +1992,120 @@ func (s *stateChangeSuite) TestRestrainDropColumnWithIndex() {
...
+			wg.Add(1)
+			go func() {
+				if concurrentDDLQueryPre != "" {
+					go func() {
+						// We assume that no error, we don't want to test it.
+						tk3.MustExec(concurrentDDLQueryPre)
+					}()
+					time.Sleep(10 * time.Millisecond)
+				}
+				_, err := tk1.Exec(concurrentDDLQuery)
```
Comment (zimulala) [inline ddl/db_change_test.go:2036]: It seems that the test is not quite sure whether it started from the state of `StateNone`  `RenameTable` or after `RenameTable` was executed.

Comment (wjhuang2016) [reply ddl/db_change_test.go:2038]: Sleep is good enough for this test case. In the worse case, it won't cause the test to fail.

**Review by zimulala — APPROVED** [review]
LGTM

**Review by tangenta — APPROVED** [review]
