### PR TITLE
executor: fix distorted join probe time

### LINKED ISSUE #52222: Join probe time includes the time of sending result to channel and getting avaliable empty chunk, which makes the probe time distorted
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
In explain analyze, if a here is join operator, it will record `probe_time` which indicates how much times does the probe process takes.
```
build_hash_table:{total:4.64s, fetch:4.64s, build:0s}, probe:{concurrency:5, total:1m49.5s, max:21.9s, probe:18.9s, fetch:1m30.6s}
```
However, this probe time actually includes the time of sending results to channel and getting avaliable emtpy chunk
https://github.com/pingcap/tidb/blob/8d9e67b37dea759db0980aeddf4da967bf93e83e/pkg/executor/join.go#L1074-L1080

So if the parent operator of join is slow(like high cardinality aggregation), the probe time will be very high, which is distorted and misleading.

### PR DESCRIPTION
**Pull request by windtalker**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: close #52222

Problem Summary:

### What changed and how does it work?

### Check List

Tests <!-- At least one of them must be included. -->

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
run TPCH query 10 base on TPCH-50 dataset
Before this pr
```
|           ├─HashJoin_88(Build)                | 2882295.78  | 2865763  | root      |                                                         | time:4.93s, loops:2802, build_hash_table:{total:160.6µs, fetch:135.6µs, build:25µs}, probe:{concurrency:5, total:50.9s, max:10.2s, probe:27.9s, fetch:23s}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | inner join, equal:[eq(test.customer.c_nationkey, test.nation.n_nationkey)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 28.5 KB   | 0 Bytes |
|           │ └─HashJoin_99(Probe)              | 2882295.78  | 2865763  | root      |                                                         | time:5.18s, loops:2801, build_hash_table:{total:3.72s, fetch:2.59s, build:1.12s}, probe:{concurrency:5, total:50.9s, max:10.2s, probe:32.2s, fetch:18.7s}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | inner join, equal:[eq(test.customer.c_custkey, test.orders.o_custkey)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | 273.0 MB  | 0 Bytes |
```
The displayed probe time 27.9s for `HashJoin_88` is 27.9s and 32.2s for `HashJoin_99`
After this pr
```
|           ├─HashJoin_88(Build)                | 2882295.78  | 2865763  | root      |                                                         | time:4.78s, loops:2802, build_hash_table:{total:292.5µs, fetch:277.3µs, build:15.2µs}, probe:{concurrency:5, total:48.6s, max:9.71s, probe:3.16s, fetch and wait:45.4s}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | inner join, equal:[eq(test.customer.c_nationkey, test.nation.n_nationkey)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | 35.2 KB   | 0 Bytes |                                                                                                                                                                                                                                                                                                                                                                                                                                              
|           │ └─HashJoin_99(Probe)              | 2882295.78  | 2865763  | root      |                                                         | time:5.01s, loops:2801, build_hash_table:{total:3.62s, fetch:2.52s, build:1.11s}, probe:{concurrency:5, total:48.6s, max:9.71s, probe:7.72s, fetch and wait:40.8s}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | inner join, equal:[eq(test.customer.c_custkey, test.orders.o_custkey)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | 273.2 MB  | 0 Bytes |
```
The displayed probe time is 3.16s for `HashJoin_88` and 7.72s for `HashJoin_99` 
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > <!-- Or your custom  "No need to test" reasons -->

Side effects

- [x] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/join.go [hunk 1]
```diff
@@ -985,12 +994,14 @@ func (w *probeWorker) getNewJoinResult() (bool, *hashjoinWorkerResult) {
 }
 
 func (w *probeWorker) join2Chunk(probeSideChk *chunk.Chunk, hCtx *hashContext, joinResult *hashjoinWorkerResult,
```
Comment (XuHuaiyu) [inline pkg/executor/join.go:996]: Add a comment for `waitTime` ?

Comment (windtalker) [reply pkg/executor/join.go:999]: Done

File: pkg/executor/join.go [hunk 2]
```diff
@@ -1633,7 +1661,7 @@ func (e *hashJoinRuntimeStats) String() string {
 		buf.WriteString(execdetails.FormatDuration(time.Duration(atomic.LoadInt64(&e.maxFetchAndProbe))))
 		buf.WriteString(", probe:")
 		buf.WriteString(execdetails.FormatDuration(time.Duration(e.probe)))
-		buf.WriteString(", fetch:")
+		buf.WriteString(", fetch and wait:")
```
Comment (XuHuaiyu) [inline pkg/executor/join.go:1664]: Add a comment for what does `fetch and wait` mean?

Comment (windtalker) [reply pkg/executor/join.go:1666]: Done

**Review by XuHuaiyu — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]
