### PR TITLE
plan: make query on partition table not cacheable

### LINKED ISSUE #16364: plan cache: the range partition table's query plan is not optimal
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

prepared-plan-cache.enabled=true
```
use test;
drop table if exists employees;
CREATE TABLE employees (
    id INT NOT NULL,
    name VARCHAR(30)
)
PARTITION BY RANGE (id) (
    PARTITION p0 VALUES LESS THAN (6),
    PARTITION p1 VALUES LESS THAN (11)
);
insert into employees values(2, "dddd"), (10, "kkk");
prepare stmt from "select * from employees where id < ?";
set @a=3;
select connection_id();
execute stmt using @a;
# explain for connection id;
```

### 2. What did you expect to see?
only used partition p0
```
mysql> explain for connection 1;
+-------------------------+----------+-----------+-------------------------------+--------------------------------+
| id                      | estRows  | task      | access object                 | operator info                  |
+-------------------------+----------+-----------+-------------------------------+--------------------------------+
| TableReader_8           | 3323.33  | root      |                               | data:Selection_7               |
| └─Selection_7       | 3323.33  | cop[tikv] |                               | lt(test.employees.id, 3)       |
|   └─TableFullScan_6 | 10000.00 | cop[tikv] | table:employees, partition:p0 | keep order:false, stats:pseudo |
+-------------------------+----------+-----------+-------------------------------+--------------------------------+
3 rows in set (0.00 sec)
```

### 3. What did you see instead?
used partition p0 and p1
```
mysql> explain for connection 1;
+-----------------------------+----------+-----------+-------------------------------+--------------------------------+
| id                          | estRows  | task      | access object                 | operator info                  |
+-----------------------------+----------+-----------+-------------------------------+--------------------------------+
| Union_8                     | 16000.00 | root      |                               |                                |
| ├─TableReader_11        | 8000.00  | root      |                               | data:Selection_10              |
| │ └─Selection_10      | 8000.00  | cop[tikv] |                               | lt(cast(test.employees.id), 3) |
| │   └─TableFullScan_9 | 10000.00 | cop[tikv] | table:employees, partition:p0 | keep order:false, stats:pseudo |
| └─TableReader_14        | 8000.00  | root      |                               | data:Selection_13              |
|   └─Selection_13        | 8000.00  | cop[tikv] |                               | lt(cast(test.employees.id), 3) |
|     └─TableFullScan_12  | 10000.00 | cop[tikv] | table:employees, partition:p1 | keep order:false, stats:pseudo |
+-----------------------------+----------+-----------+-------------------------------+--------------------------------+
7 rows in set (0.06 sec)
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-rc-11-g78922a8ab
Git Commit Hash: 78922a8abef2f21e4d8990d37c6c67ac7b0eef42
Git Branch: HEAD
UTC Build Time: 2020-04-14 08:35:18
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve?

Issue Number: close #16364  

Problem Summary:
#15697 will check whether plan is a query on partition table and will pass by if is true. But there is still some problems bring by `stmtCtx.UseCache`. If a plan is `Cacheable`, `stmtCtx.UseCache` is set to `true`. So the `simpleRewriter` has different output compare with not cached plan. 

For example, in #16364. If prepare-plan-cache is on, although query on partition table is not cached, it has different plan.

not use cache:
`lt(test.employees.id, 3) `
use cache:
`lt(cast(test.employees.id), 3)`

this small change in `rewriter` cause partition pruning fail.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
add partition check in `Cacheable` function rather than `getPhysicalPlan`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- No

### CODE REVIEW

File: planner/core/cacheable_checker.go [hunk 1]
```diff
@@ -105,10 +110,27 @@ func (checker *cacheableChecker) Enter(in ast.Node) (out ast.Node, skipChildren
...
+		if checker.isPartitionTable(node) {
+			checker.cacheable = false
+			return in, true
+		}
 	}
 	return in, false
 }
 
+func (checker *cacheableChecker) isPartitionTable(tn *ast.TableName) bool {
+	tb, err := checker.schema.TableByName(tn.Schema, tn.Name)
```
Comment (tiancaiamao) [inline planner/core/cacheable_checker.go:123]: This change may have some performance impact.

**Comment by imtbkcat** [comment]
@XuHuaiyu PTAL

**Comment by tiancaiamao** [comment]
LGTM
/bench

**Comment by tiancaiamao** [comment]
PTAL @zz-jason

**Comment by imtbkcat** [comment]
it's seems this pr bring  performance impact that can not be ignore.

**Comment by tiancaiamao** [comment]
What's your opinion? @XuHuaiyu

**Comment by eurekaka** [comment]
> Have you figure out why there is a `cast` and is that evitable？
> If there is no better way, I think this one is an acceptable solution.

The `cast` is added in `getFunction` as I explained in https://github.com/pingcap/tidb/issues/16676#issuecomment-617612361.

**Comment by eurekaka** [comment]
Why would this PR incur significant performance regression? it just adds one more check for `TableName`.

File: planner/core/cacheable_checker.go (hunk 1 above)
Comment (tiancaiamao) [reply planner/core/cacheable_checker.go:123]: > Why would this PR incur significant performance regression? it just adds one more check for TableName.

Because of the check here. @eurekaka

Comment (eurekaka) [reply planner/core/cacheable_checker.go:123]: Are these 2 map lookups so expensive?

Comment (tiancaiamao) [reply planner/core/cacheable_checker.go:123]: schema.TableByName() is `O(N)` operation.
And the `cacheableChecker` itself need to handle each tableName in the AST.
