### PR TITLE
store/tikv: fix async commit amend txn failure with update statement

### LINKED ISSUE #21274: Schema change not working when an async-commit txn updates an old row
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

**Enable async commit or 1PC**

Session 1 | Session 2
---------|----------
|create table t (c1 int primary key, c2 int)|
|insert into t values (1, 1)|
|begin|
|update t set c2 = 2 where c1 = 1|
||alter table t add index k(c2)
|commit|

### 2. What did you expect to see? (Required)

Session 1 commits successfully. After that, the add index DDL of Session 2 finishes.

### 3. What did you see instead (Required)

Add index DDL hangs forever and `commit` returns error: 

```
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### 4. What is your TiDB version? (Required)

Master

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

### What problem does this PR solve?

Issue Number: close #21274

### What is changed and how it works?

1. Fixes the bug that `Op_Del` mutations in `addMutations` are failed to be stored in `memBuf`.
2.  Revert the change that `cleanUp` is not called when prewrite is not started. It is still useful to roll back pessimistic locks.

### Check List 

Tests 

- Integration test

### Release note 

- Part of the async commit feature.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
LGTM

File: session/pessimistic_test.go [hunk 1]
```diff
@@ -2025,26 +2025,37 @@ func (s *testPessimisticSuite) TestAsyncCommitWithSchemaChange(c *C) {
...
 	tk.MustExec("insert into tk values(2, 2, 2)")
-	// Add index for c2 before commit
-	tk2.MustExec("alter table tk add index k2(c2)")
+	tk.MustExec("update tk set c2 = 10 where c1 = 1")
+	ch := make(chan struct{})
+	go func() {
+		// Add index for c2 before commit
+		tk2.MustExec("alter table tk add index k2(c2)")
+		ch <- struct{}{}
+	}()
```
Comment (you06) [inline session/pessimistic_test.go:2036]: May sleep for a short duration waiting for the statement executed.

**Review by youjiali1995 — COMMENTED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]

**Review by you06 — APPROVED** [review]
LGTM

File: session/pessimistic_test.go (hunk 1 above)
Comment (sticnarf) [reply session/pessimistic_test.go:2036]: Fixed. PTAL again.

**Comment by you06** [comment]
LGTM

**Review by you06 — APPROVED** [review]
