### PR TITLE
scatter: check pending peers before scattering

### LINKED ISSUE #31034: br: after br restore, tikv used storage is not balance
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
run oltp_fun_001

### 2. What did you expect to see? (Required)
Restore finished at 18:26. Tikv used should be balance in all nodes.

### 3. What did you see instead (Required)
image

### 4. What is your TiDB version? (Required)
/ # /br -V
Release Version: v5.4.0-nightly
Git Commit Hash: 76aae0d5c594f538af62caa883c73188a44170c4
Git Branch: heads/refs/tags/v5.4.0-nightly
Go Version: go1.16.4
UTC Build Time: 2021-12-26 08:07:37
Race Enabled: false

/ # /tidb-server -V
Release Version: v5.4.0-nightly
Edition: Community
Git Commit Hash: 76aae0d5c594f538af62caa883c73188a44170c4
Git Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time: 2021-12-26 08:09:11
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

Logs and monitor can be get from minio using following testbed name.
endless-oltp--tps-542284-1-875

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Yu Juncen <yu745514916@live.com>

### What problem does this PR solve?

Issue Number: close #31034

Problem Summary:
When scattering regions, BR sometimes meets "pending" regions and fail to scatter them then. (This behavior is defined by PD, we can found them in the DEBUG log.)

This PR checks the pending status before doing scatter.

Why those pending regions exist is still in investigating, for more details, see https://github.com/tikv/pd/issues/4525 and https://github.com/pingcap/tidb/issues/31034.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix a bug that caused region unbalanced after restoring.
```

### CODE REVIEW

File: br/pkg/restore/split.go [hunk 1]
```diff
@@ -185,12 +185,20 @@ SplitRegions:
...
 }
 
-func (rs *RegionSplitter) hasRegion(ctx context.Context, regionID uint64) (bool, error) {
+func (rs *RegionSplitter) hasHealthyRegion(ctx context.Context, regionID uint64) (bool, error) {
 	regionInfo, err := rs.client.GetRegionByID(ctx, regionID)
 	if err != nil {
 		return false, errors.Trace(err)
 	}
-	return regionInfo != nil, nil
+	if len(regionInfo.PendingPeers) > 0 || len(regionInfo.DownPeers) > 0 {
```
Comment (hawkingrei) [inline br/pkg/restore/split.go:193]: This judgement is useless. ```for``` will check the length for ```PendingPeers``` and ```DownPeers```.

**Comment by hawkingrei** [comment]
LGTM

**Review by fengou1 — APPROVED** [review]

**Review by joccau — APPROVED** [review]
LGTM.
BTW,  how can we prove this fix ?
Test and get a balance cluster about regions after fix-it，different from fixing it before.

**Comment by YuJuncen** [comment]
> LGTM.
> BTW, how can we prove this fix ?
> Test and get a balance cluster about regions after fix-it，different from fixing it before.

@mayjiang0203 has tested this PR(thanks!), and the metrics that there isn't imbalance any more:
origin_img_v2_4d418b7e-d13a-4c8d-b817-fd8a9736b2cg

**Comment by YuJuncen** [comment]
Well, after this, there are only merging master operations. I guess the result would be effect for the latest commit.

image

/merge

File: br/pkg/restore/split.go [hunk 2]
```diff
@@ -185,12 +185,26 @@ SplitRegions:
...
 	}
-	return regionInfo != nil, nil
+	// the region hasn't get ready.
+	if regionInfo == nil {
+		return false, nil
+	}
+
+	// check whether the region is healthy and report.
+	for _, peer := range regionInfo.PendingPeers {
+		log.Warn("unhealthy region detected", logutil.Peer(peer), zap.String("type", "pending"))
```
Comment (3pointer) [inline br/pkg/restore/split.go:200]: What if we have lots of pending peers in cluster. this will print too many unnecessary logs. I suggest to use metrics rather than log.

Comment (YuJuncen) [reply br/pkg/restore/split.go:200]: There isn't a prometheus server pulling BR, hence the metric may lose.😢

I guess we can just set this log level to `DEBUG`.

Comment (3pointer) [reply br/pkg/restore/split.go:200]: `DEBUG` is ok for me

File: br/pkg/restore/split.go [hunk 3]
```diff
@@ -185,12 +185,27 @@ SplitRegions:
...
+	// TODO: the log may be too verbose. we should use Prometheus metrics once it get ready for BR.
+	for _, peer := range regionInfo.PendingPeers {
+		log.Debug("unhealthy region detected", logutil.Peer(peer), zap.String("type", "pending"))
+	}
+	for _, peer := range regionInfo.DownPeers {
+		log.Debug("unhealthy region detected", logutil.Peer(peer), zap.String("type", "down"))
+	}
+	// we ignore down peers for they are (normally) hard to be fixed in reasonable time.
+	// (or once there is a peer down, we may get stuck at waiting region get ready.)
+	return true, nil
```
Comment (3pointer) [inline br/pkg/restore/split.go:208]: why remove `return len(regionInfo.PendingPeers)==0, nil` 🤔

Comment (YuJuncen) [reply br/pkg/restore/split.go:208]: ... just for testing

Comment (YuJuncen) [reply br/pkg/restore/split.go:208]: I will move it back then

Comment (YuJuncen) [inline br/pkg/restore/split.go:208]:
```suggestion
	 return len(regionInfo.PendingPeers)==0, nil
```

**Comment by YuJuncen** [comment]
image
/merge
