### PR TITLE
util/ranger: add missing `Selection` for range scan from `like` on PAD SPACE column | tidb-test=pr/2251

### LINKED ISSUE #48821: Query result may be wrong when use `like` to do index range scan on PAD SPACE column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a varchar(20) collate utf8mb4_bin, index ia(a));
insert into t value('测试'),('测试  ');
select *,length(a) from t where a like '测试 %';
select *,length(a) from t where a like '测试';
```

### 2. What did you expect to see? (Required)

From mysql:
```
> select *,length(a) from t where a like '测试 %';
+----------+-----------+
| a        | length(a) |
+----------+-----------+
| 测试     |         8 |
+----------+-----------+

> select *,length(a) from t where a like '测试';
+--------+-----------+
| a      | length(a) |
+--------+-----------+
| 测试   |         6 |
+--------+-----------+
```

### 3. What did you see instead (Required)

```
> select *,length(a) from t use index () where a like '测试 %';
+----------+-----------+
| a        | length(a) |
+----------+-----------+
| 测试     |         8 |
+----------+-----------+

> select *,length(a) from t use index (ia) where a like '测试 %';
+----------+-----------+
| a        | length(a) |
+----------+-----------+
| 测试     |         6 |
| 测试     |         8 |
+----------+-----------+

> select *,length(a) from t use index () where a like '测试';
+--------+-----------+
| a      | length(a) |
+--------+-----------+
| 测试   |         6 |
+--------+-----------+

> select *,length(a) from t use index (ia) where a like '测试';
+----------+-----------+
| a        | length(a) |
+----------+-----------+
| 测试     |         6 |
| 测试     |         8 |
+----------+-----------+
```

### 4. What is your TiDB version? (Required)

From v6.0.0 to latest master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #48821 ref #48181

### What changed and how does it work?

As the title says.
And please read the comments in the code.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

**Review by winoros — APPROVED** [review]

File: pkg/util/ranger/checker.go [hunk 1]
```diff
@@ -168,11 +169,22 @@ func (c *conditionChecker) checkLikeFunc(scalar *expression.ScalarFunction) (isA
...
 	}
+	likeFuncReserve := !c.isFullLengthColumn()
+
+	// Different from `=`, trailing spaces are always significant, and can't be ignored in `like`.
+	// In tidb's implementation, for PAD SPACE collations, the trailing spaces are removed in the index key. So we are
+	// unable to distinguish 'xxx' from 'xxx   ' by a single index range scan, and we may read more data than needed by
+	// the `like` function. Therefore, a Selection is needed to filter the data.
+	// Since all collations, except for binary, implemented in tidb are PAD SPACE collations for now, we use a simple
+	// collation != binary check here.
+	if collation != charset.CollationBin {
```
Comment (chrysan) [inline pkg/util/ranger/checker.go:180]: What about make PAD SPACE as a new attribute for collation, so that we won't import bugs when a new NO PAD collation is added?

Comment (time-and-fate) [reply pkg/util/ranger/checker.go:180]: Yes. But I think it's better for SQL team to add this into collation-related packages, especially when they start to implement NO PAD collations. I added an `isPadSpaceCollation` function in #48984 since we need the same check there.
This won't cause bugs. If we use current logic when NO PAD collation is added, there will be unnecessary `Selection`, that's not perfect but won't cause bugs.
