### PR TITLE
planner: fix bindings with ignore_plan_cache_hint cannot work

### LINKED ISSUE #34596: bindings with `ignore_plan_cache_hint` cannot work
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
-- enable the plan-cache --
create table t (a int);
create binding for select * from t using select /*+ ignore_plan_cache() */ * from t;
prepare stmt from 'select * from t';
execute stmt;
execute stmt;
select @@last_plan_from_cache;
```

### 2. What did you expect to see? (Required)
The second execute-stmt cannot hit the cache since we create a binding with ignore_plan_cache() for it.

### 3. What did you see instead (Required)
It can hit the cache.

### 4. What is your TiDB version? (Required)

Master

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #34596 

Problem Summary:
In the general SQL, using hint ` /*+ ignore_plan_cache() */ ` cannot be awared by prepare/execute.

### What is changed and how it works?

Add some check in EXECUTE stage.

The switch of prepare's plan cache is open/close in PREPARE stage.But if we CREATE/DROP binding with ` /*+ ignore_plan_cache() */ ` , the switch will not change in EXECUTE stage.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by fzzf678** [comment]
/retitle planner:Fix bindings with ignore_plan_cache_hint cannot work

**Comment by fzzf678** [comment]
/retitle planner: fix bindings with ignore_plan_cache_hint cannot work

File: planner/core/common_plans.go [hunk 1]
```diff
@@ -318,7 +318,7 @@ func (e *Execute) checkPreparedPriv(ctx context.Context, sctx sessionctx.Context
 }
 
 // GetBindSQL4PlanCache used to get the bindSQL for plan cache to build the plan cache key.
-func GetBindSQL4PlanCache(sctx sessionctx.Context, preparedStmt *CachedPrepareStmt) string {
+func GetBindSQL4PlanCache(sctx sessionctx.Context, preparedStmt *CachedPrepareStmt, ignore *bool) string {
```
Comment (Reminiscent) [inline planner/core/common_plans.go:321]: Why not treat the `ignore` as the return value rather than input parameter?

File: executor/explainfor_test.go [hunk 2]
```diff
@@ -1174,6 +1174,31 @@ func TestHint4PlanCache(t *testing.T) {
 	tk.MustQuery("select @@last_plan_from_cache;").Check(testkit.Rows("0"))
 }
 
+func TestIgnorePlanCacheWithPrepare(t *testing.T) {
```
Comment (Reminiscent) [inline executor/explainfor_test.go:1177]: Please add some test cases like:
```
create binding for ... using select /*+ use_index(..) */ ..        // some useful hint
execute stmt;
select @@last_plan_from_binding; // check binding
execute stmt;
select @@last_plan_from_cache; // check the plan cache

create binding for ... using select /*+ ignore_plan_cache() */ ..
execute;
select @@last_plan_from_cache;
execute;
select @@last_plan_from_binding;
```

File: planner/core/common_plans.go (hunk 1 above)
Comment (fzzf678) [reply planner/core/common_plans.go]: thks, i'm adapting golang‘s idiomatic syntax

File: executor/explainfor_test.go [hunk 3]
```diff
@@ -1174,6 +1174,49 @@ func TestHint4PlanCache(t *testing.T) {
...
+	tk.MustQuery("select @@last_plan_from_cache;").Check(testkit.Rows("1"))
+	tk.MustQuery("execute stmt;").Check(testkit.Rows())
+	tk.MustQuery("select @@last_plan_from_binding;").Check(testkit.Rows("1"))
+
+	tk.MustExec("create binding for select * from t using select /*+ ignore_plan_cache() */ * from t;")
+	tk.MustQuery("execute stmt;").Check(testkit.Rows())
+	tk.MustQuery("select @@last_plan_from_cache;").Check(testkit.Rows("0"))
+	tk.MustQuery("execute stmt;").Check(testkit.Rows())
+	tk.MustQuery("select @@last_plan_from_binding;").Check(testkit.Rows("1"))
+
```
Comment (qw4990) [inline executor/explainfor_test.go:1202]: Please add one more test case like:
```
create binding for ... using select /*+ use_index(t, idx_a) */ ... -- remove the ignore_plan_cahce hint
execute stmt;
execute stmt;
select @@last_plan_from_cache; -- the plan cache can work again
select @@last_plan_from_binding;
```

**Review by qw4990 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]
