### PR TITLE
*: handle region error for GetMvccByEncodedKey API

### LINKED ISSUE #47807: unexpected error: There is no Write MVCC info for the schema version
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"]
- trigger a lot of load schema OPS.

img_v2_0f786210-a576-47d7-97e8-17d78c88324g

```
# rg "failed to get schema version"
tidb.log
9758:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9760:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9762:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9764:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
10034:[2023/10/19 18:11:28.173 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]

```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #47807

Problem Summary: 

### What is changed and how it works?

Before:

Related TIDB Log:

```log
# rg "failed to get schema version"
tidb.log
9758:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9760:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9762:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
9764:[2023/10/19 18:11:18.100 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
10034:[2023/10/19 18:11:28.173 +08:00] [WARN] [domain.go:195] ["failed to get schema version"] [error="There is no Write MVCC info for the schema version"] [version=40]
```

img_v2_0f786210-a576-47d7-97e8-17d78c88324g

This PR:

```log
# rg "failed to get schema version"

```

image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/executor_failpoint_test.go [hunk 1]
```diff
@@ -622,3 +624,24 @@ func TestTiKVClientReadTimeout(t *testing.T) {
...
+
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/pkg/store/mockstore/unistore/epochNotMatch", "2*return(true)"))
+	defer func() {
+		require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/pkg/store/mockstore/unistore/epochNotMatch"))
+	}()
+	resp, err := h.GetMvccByEncodedKey(key)
+	require.NoError(t, err)
+	require.NotNil(t, resp.Info)
+	require.Equal(t, 1, len(resp.Info.Writes))
+	require.Less(t, uint64(0), resp.Info.Writes[0].CommitTs)
```
Comment (cfzjywxk) [inline pkg/executor/executor_failpoint_test.go:646]: It's better to write a valid value first, then after serveral rounds of region error handling the valid `commit_ts` would also be returned.

Comment (crazycs520) [reply pkg/executor/executor_failpoint_test.go]: Great, already change the test. There is already a valid value exist, since the key is the current schema-version-diff.

**Review by zyguan — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
