### PR TITLE
server: fix flaky test TestPlanReplayerWithMultiForeignKey

### LINKED ISSUE #56735: flaky test TestPlanReplayerWithMultiForeignKey
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
     dbtestkit.go:71: 
        	Error Trace:	pkg/testkit/dbtestkit.go:71
        	            				pkg/server/handler/optimizor/plan_replayer_test.go:334
        	Error:      	Received unexpected error:
        	            	open /tmp/plan_replayer.zip: no such file or directory
        	Test:       	TestPlanReplayerWithMultiForeignKey
        	Messages:   	sql:plan replayer load "/tmp/plan_replayer.zip", args:[]
    plan_replayer_test.go:313: 
        	Error Trace:	pkg/server/handler/optimizor/plan_replayer_test.go:313
        	            				GOROOT/src/runtime/panic.go:629
        	            				GOROOT/src/testing/testing.go:1006
        	            				pkg/testkit/dbtestkit.go:71
        	            				pkg/server/handler/optimizor/plan_replayer_test.go:334
        	Error:      	Received unexpected error:
        	            	remove /tmp/plan_replayer.zip: no such file or directory
        	Test:       	TestPlanReplayerWithMultiForeignKey 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #56735 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

File: pkg/server/handler/optimizor/plan_replayer_test.go [hunk 1]
```diff
@@ -373,7 +373,7 @@ func TestPlanReplayerWithMultiForeignKey(t *testing.T) {
 	tk.MustExec("drop table planReplayer.c")
 	tk.MustExec(`SET FOREIGN_KEY_CHECKS = 1;`)
 	tk.MustExec(fmt.Sprintf(`plan replayer load "%s"`, path))
-
+	tk.MustExec("admin reload bindings")
```
Comment (zimulala) [inline pkg/server/handler/optimizor/plan_replayer_test.go:376]: Does this PR only fix the issue on line 384, and not address the `open /tmp/plan_replayer.zip: no such file or directory problem`?

Comment (hawkingrei) [reply pkg/server/handler/optimizor/plan_replayer_test.go:376]: I have fixed in https://github.com/pingcap/tidb/pull/64457
