### PR TITLE
*: inject projection for the plan pushed to TiDB

### LINKED ISSUE #19975: query cluster system table panic when order by scalar function.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
> select length(query) as l,time from information_schema.cluster_slow_query where time > "2019-12-30 22:00:00" order by abs(l) desc limit 10;
(1105, 'other error: panic when RPC server handing coprocessor, stack:interface conversion: expression.Expression is *expression.ScalarFunction, not *expression.Column')
```

image

The cause is `TopN_13` doesn't have `Projection` child then panic when executing. Related PR: https://github.com/pingcap/tidb/pull/9197

### 4. What is your TiDB version? (Required)

```sql
test> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: None                                             |
| Edition: Community                                                |
| Git Commit Hash: None                                             |
| Git Branch: None                                                  |
| UTC Build Time: None                                              |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+

```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close #19975  

Problem Summary:
The panic is caused because of that TiDB builds `topn in tidb --> topn in cop` and then inject projection for the `topn in tidb`.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Inject projection for the plan which is pushed to TiDB.

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- No release note.

### CODE REVIEW

**Review by crazycs520 — COMMENTED** [review]
LGTM

File: planner/core/rule_inject_extra_projection.go [hunk 1]
```diff
@@ -20,11 +20,11 @@ import (
 	"github.com/pingcap/tidb/sessionctx"
 )
 
-// injectExtraProjection is used to extract the expressions of specific
+// InjectExtraProjection is used to extract the expressions of specific
 // operators into a physical Projection operator and inject the Projection below
 // the operators. Thus we can accelerate the expression evaluation by eager
 // evaluation.
-func injectExtraProjection(plan PhysicalPlan) PhysicalPlan {
+func InjectExtraProjection(plan PhysicalPlan) PhysicalPlan {
```
Comment (lzmhhh123) [inline planner/core/rule_inject_extra_projection.go:27]: It is better to add some comments to explain the function is to change the cop plan for `cop[tidb]`.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
