### PR TITLE
expression: fix the issue that incorrect result for a predicate that uses the CHAR() function

### LINKED ISSUE #15986: Incorrect result for a predicate that uses the CHAR() function
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0(c0) VALUES (0);
SELECT t0.c0 FROM t0 WHERE CHAR(204355900); -- expected: {0}, actual: {}
```
Unexpectedly, the query does not fetch any rows. When negating the predicate, the query works as expected and does also not fetch any rows:

```sql
SELECT t0.c0 FROM t0 WHERE NOT CHAR(204355900); -- {}
```
Interestingly, the first query results in the following warning:

```sql
mysql> show warnings;
+---------+------+------------------------------------------+
| Level   | Code | Message                                  |
+---------+------+------------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: '.9<' |
+---------+------+------------------------------------------+
1 row in set (0.00 sec)
```
Environment:
```
mysql> SELECT tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-160-g82529c886
Git Commit Hash: 82529c886cb1cfff7810476a136acf81284bac6e
Git Branch: master
UTC Build Time: 2020-04-01 11:44:27
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```
MySQL 8.0.19 produces the expected result for this query.

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?
Issue Number: close #15986 

### What is changed and how it works?
When we use the `string` type to determine the `bool` value, the `string` type is converted to a `float` type instead of an `int` type.

### Check List 

Tests 

- Unit test
- Integration test

### CODE REVIEW

File: expression/expression.go [hunk 1]
```diff
@@ -427,12 +427,9 @@ func toBool(sc *stmtctx.StatementContext, eType types.EvalType, buf *chunk.Colum
 			if buf.IsNull(i) {
 				isZero[i] = -1
 			} else {
-				iVal, err := types.StrToInt(sc, buf.GetString(i))
+				iVal, err := types.StrToFloat(sc, buf.GetString(i))
 				if err != nil {
-					iVal, err = HandleOverflowOnSelection(sc, iVal, err)
-					if err != nil {
-						return err
-					}
```
Comment (Reminiscent) [inline expression/expression.go:435]: Function `types.StrToFloat` does not need to handle `overflow`. So the test `TestVecToBool` is unused.

**Comment by Reminiscent** [comment]
> From #15986,
> 
> > Interestingly, the first query results in the following warning:
> 
> ```
> mysql> show warnings;
> +---------+------+------------------------------------------+
> | Level   | Code | Message                                  |
> +---------+------+------------------------------------------+
> | Warning | 1292 | Truncated incorrect INTEGER value: '.9<' |
> +---------+------+------------------------------------------+
> 1 row in set (0.00 sec)
> ```
> 
> Please add some test cases to ensure there's no this type of warnings anymore.

The warning seems can not be eliminated. Because in the [implementation of TIDB](https://github.com/pingcap/tidb/blob/master/types/convert.go#L669), when the string type cannot be completely converted to the float type, it will prompt this warning. @SunRunAway  PTAL

**Comment by Reminiscent** [comment]
@qw4990 @XuHuaiyu  PTAL
