### PR TITLE
lightning: return the right error in restore engine

### LINKED ISSUE #31057: tidb-lightning return context.Canceled error when set wrong csv.header config
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run tidb-lightning with default config (csv.header = true), but source data actually don't contains header.

### 2. What did you expect to see? (Required)
Lightning should report `unknown columns in header ...`

### 3. What did you see instead (Required)
Lightning report `RequestCanceled: request context canceled\ncaused by: context canceled`

### 4. What is your TiDB version? (Required)

v5.3.0

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #31057

Problem Summary:

### What is changed and how it works?
Check and return the right error if met error

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/noop/noop.go [hunk 1]
```diff
@@ -174,16 +174,23 @@ func (r noopRow) Size() uint64 {
 func (r noopRow) ClassifyAndAppend(*kv.Rows, *verification.KVChecksum, *kv.Rows, *verification.KVChecksum) {
 }
 
-type noopWriter struct{}
+// trueStatus define a writer that do nothing.
```
Comment (gozssky) [inline br/pkg/lightning/backend/noop/noop.go:177]: Seems this comment is misplaced.

**Review by gozssky — APPROVED** [review]

**Review by kennytm — APPROVED** [review]
