### PR TITLE
planner: logically delete the bindinfo when create the new binding

### LINKED ISSUE #25842: inconsistent SQL bind caches after recreating bind with different bind_sql for a same original_sql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start 2 tidb-servers, execute create / drop binding statements on tidb-1, and observe the results of `show global bindings` on tidb-2.

This is the output on tidb-1, which is as expected.
```
mysql> create global binding for select * from t0 using select * from t0 use index(a);
Query OK, 0 rows affected (0.03 sec)

mysql> show global bindings;
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql            | Bind_sql                            | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from test . t0 | SELECT * FROM test.t0 USE INDEX (a) | test       | using  | 2021-06-30 12:57:31.121 | 2021-06-30 12:57:31.121 | utf8    | utf8_general_ci | manual |
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
1 row in set (0.00 sec)

mysql> create global binding for select * from t0 using select /*+ use_index(t0,a) */ * from t0;
Query OK, 0 rows affected (0.02 sec)

mysql> show global bindings;
+-------------------------+---------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql            | Bind_sql                                    | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+-------------------------+---------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from test . t0 | SELECT /*+ use_index(t0 a)*/ * FROM test.t0 | test       | using  | 2021-06-30 12:57:59.102 | 2021-06-30 12:57:59.102 | utf8    | utf8_general_ci | manual |
+-------------------------+---------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
1 row in set (0.00 sec)

mysql> drop global binding for select * from t0;
Query OK, 0 rows affected (0.02 sec)

mysql> show global bindings;
Empty set (0.00 sec)
```

This is the output on tidb-2:
```
-- after the first create binding executed on tidb-1
mysql> show global bindings;
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql            | Bind_sql                            | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from test . t0 | SELECT * FROM test.t0 USE INDEX (a) | test       | using  | 2021-06-30 12:57:31.121 | 2021-06-30 12:57:31.121 | utf8    | utf8_general_ci | manual |
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
1 row in set (0.00 sec)

-- after the second create binding executed on tidb-1
mysql> show global bindings;
+-------------------------+---------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql            | Bind_sql                                    | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+-------------------------+---------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from test . t0 | SELECT * FROM test.t0 USE INDEX (a)         | test       | using  | 2021-06-30 12:57:31.121 | 2021-06-30 12:57:31.121 | utf8    | utf8_general_ci | manual |
| select * from test . t0 | SELECT /*+ use_index(t0 a)*/ * FROM test.t0 | test       | using  | 2021-06-30 12:57:59.102 | 2021-06-30 12:57:59.102 | utf8    | utf8_general_ci | manual |
+-------------------------+---------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
2 rows in set (0.00 sec)

-- after the drop binding executed on tidb-1
mysql> show global bindings;
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql            | Bind_sql                            | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from test . t0 | SELECT * FROM test.t0 USE INDEX (a) | test       | using  | 2021-06-30 12:57:31.121 | 2021-06-30 12:57:31.121 | utf8    | utf8_general_ci | manual |
+-------------------------+-------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
1 row in set (0.01 sec)
```

We can see that, tidb-2 has an invalid cached bind for `use index(a)` hint.

### 2. What did you expect to see? (Required)

tidb-1 and tidb-2 have same cached bindings.

### 3. What did you see instead (Required)

tidb-2 has one more cached binding than tidb-1, which is expected to be removed.

### 4. What is your TiDB version? (Required)

4.0.12, master

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close #25842 

Problem Summary:
In this [PR](https://github.com/pingcap/tidb/pull/21349), we physically delete the bindings when we create a new binding to prevent some problems of inconsistent cache. But this method can not solve all the problems, for example [issue#25842](https://github.com/pingcap/tidb/issues/25842). So after we introduce the table lock for `mysql.bind_info` in this [PR](https://github.com/pingcap/tidb/pull/21629), we can revert the origin change.

### What is changed and how it works?

What's Changed:
Logically delete the binding when we create a new binding.

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- https://github.com/pingcap/tidb/issues/21288 We need to test this issue.

### Release note 

- No release note

### CODE REVIEW

File: bindinfo/bind_test.go [hunk 1]
```diff
@@ -1947,6 +1950,7 @@ func (s *testSuite) TestConcurrentCapture(c *C) {
 	tk.MustExec("select * from t")
 	tk.MustExec("admin capture bindings")
 	tk.MustQuery("select original_sql, source from mysql.bind_info where source != 'builtin'").Check(testkit.Rows(
+		"select * from `test` . `t` manual",
```
Comment (Reminiscent) [inline bindinfo/bind_test.go:1953]: I'm not sure whether here is expected.

**Comment by zhangjinpeng1987** [comment]
This small PR lasted for 10 days, please review it in time.

File: bindinfo/bind_test.go [hunk 2]
```diff
@@ -1043,7 +1043,7 @@ func (s *testSuite) TestBaselineDBLowerCase(c *C) {
 
 	s.cleanBindingEnv(tk)
 	// Simulate existing bindings with upper case default_db.
-	tk.MustExec("insert into mysql.bind_info values('select * from `spm` . `t`', 'select * from `spm` . `t`', 'SPM', 'using', '2000-01-01 09:00:00', '2000-01-01 09:00:00', '', '','" +
+	tk.MustExec("insert into mysql.bind_info values('select * from `spm` . `t`', 'SELECT * FROM `SPM`.`t`', 'SPM', 'using', '2000-01-01 09:00:00', '2000-01-01 09:00:00', '', '','" +
```
Comment (eurekaka) [inline bindinfo/bind_test.go:1046]: Why do we need this change?

File: bindinfo/bind_test.go [hunk 3]
```diff
@@ -1951,21 +1954,20 @@ func (s *testSuite) TestConcurrentCapture(c *C) {
...
 	tk.MustExec("drop table if exists t")
 	tk.MustExec("create table t(a int, b int)")
 	c.Assert(tk.Se.Auth(&auth.UserIdentity{Username: "root", Hostname: "%"}, nil, nil), IsTrue)
-	tk.MustExec("select * from t")
-	tk.MustExec("select * from t")
-	tk.MustExec("admin capture bindings")
-	tk.MustQuery("select original_sql, source from mysql.bind_info where source != 'builtin'").Check(testkit.Rows(
-		"select * from `test` . `t` capture",
+	tk.MustExec("create global binding for select * from t using select * from t")
+	tk.MustQuery("select original_sql, source, status from mysql.bind_info where source != 'builtin'").Check(testkit.Rows(
```
Comment (eurekaka) [inline bindinfo/bind_test.go:1968]: Better to test the capture operation here, or rename the test.

File: bindinfo/handle.go [hunk 4]
```diff
@@ -210,22 +213,34 @@ func (h *BindHandle) CreateBindRecord(sctx sessionctx.Context, record *BindRecor
 			return
 		}
 
-		sqlDigest := parser.DigestNormalized(record.OriginalSQL)
-		h.setBindRecord(sqlDigest.String(), record)
+		if oldRecord != nil {
+			h.removeBindRecord(normalizedSQL.String(), oldRecord)
+		}
+		h.appendBindRecord(normalizedSQL.String(), record)
```
Comment (eurekaka) [inline bindinfo/handle.go:219]: We can still use the `setBindRecord` which is simpler?

File: bindinfo/handle.go [hunk 5]
```diff
@@ -210,22 +213,34 @@ func (h *BindHandle) CreateBindRecord(sctx sessionctx.Context, record *BindRecor
...
+		if binding.BindSQL == "" {
+			_, err = exec.ExecuteInternal(context.TODO(), `UPDATE mysql.bind_info SET status = %?, update_time = %? WHERE original_sql = %? AND update_time < %?`,
+				deleted, updateTs, record.OriginalSQL, updateTs)
+		} else {
+			_, err = exec.ExecuteInternal(context.TODO(), `UPDATE mysql.bind_info SET status = %?, update_time = %? WHERE original_sql = %? AND update_time < %? AND bind_sql = %?`,
+				deleted, updateTs, record.OriginalSQL, updateTs, binding.BindSQL)
+		}
+		if err != nil {
+			return err
+		}
```
Comment (eurekaka) [inline bindinfo/handle.go:241]: We can use a single `update` for all the rows with same `original_sql`?

File: bindinfo/bind_test.go [hunk 6]
```diff
@@ -1882,13 +1883,15 @@ func (s *testSuite) TestReCreateBind(c *C) {
...
-	))
 	rows = tk.MustQuery("show global bindings").Rows()
 	c.Assert(len(rows), Equals, 1)
 	c.Assert(rows[0][0], Equals, "select * from `test` . `t`")
 	c.Assert(rows[0][3], Equals, "using")
+
+	rows = tk.MustQuery("select original_sql, status from mysql.bind_info").Rows()
+	c.Assert(len(rows), Equals, 2)
+	c.Assert(rows[0][1], Equals, "deleted")
+	c.Assert(rows[1][1], Equals, "using")
```
Comment (eurekaka) [inline bindinfo/bind_test.go:1894]: Why is the `builtin` row not returned by this query?

File: bindinfo/handle.go [hunk 7]
```diff
@@ -210,22 +210,24 @@ func (h *BindHandle) CreateBindRecord(sctx sessionctx.Context, record *BindRecor
...
 	if err = h.lockBindInfoTable(); err != nil {
 		return err
 	}
-	// Binding recreation should physically delete previous bindings.
-	_, err = exec.ExecuteInternal(context.TODO(), `DELETE FROM mysql.bind_info WHERE original_sql = %?`, record.OriginalSQL)
+
+	now := types.NewTime(types.FromGoTime(time.Now()), mysql.TypeTimestamp, 3)
+
+	updateTs := now.String()
+	_, err = exec.ExecuteInternal(context.TODO(), `UPDATE mysql.bind_info SET status = %?, update_time = %? WHERE original_sql = %? AND update_time < %? and status = 'using'`,
```
Comment (eurekaka) [inline bindinfo/handle.go:225]: I think we don't need the `status = 'using'` filter, e.g, for `pending verify` records, we should mark them as deleted as well?

File: bindinfo/bind_test.go [hunk 8]
```diff
@@ -1951,7 +1954,7 @@ func (s *testSuite) TestConcurrentCapture(c *C) {
 	s.cleanBindingEnv(tk)
 	// Simulate an existing binding generated by concurrent CREATE BINDING, which has not been synchronized to current tidb-server yet.
 	// Actually, it is more common to be generated by concurrent baseline capture, I use Manual just for simpler test verification.
-	tk.MustExec("insert into mysql.bind_info values('select * from `test` . `t`', 'select * from `test` . `t`', '', 'using', '2000-01-01 09:00:00', '2000-01-01 09:00:00', '', '','" +
+	tk.MustExec("insert into mysql.bind_info values('select * from `test` . `t`', 'SELECT * FROM `test`.`t`', '', 'using', '2000-01-01 09:00:00', '2000-01-01 09:00:00', '', '','" +
```
Comment (eurekaka) [inline bindinfo/bind_test.go:1957]: Unnecessary changes?

**Review by rebelice — APPROVED** [review]

**Review by eurekaka — APPROVED** [review]
