### PR TITLE
ddl: fix default decimal Flen value

### LINKED ISSUE #22034: ddl: create table with decimal(0, 0) got wrong default value
### 1. Minimal reproduce step (Required)

```mysql
mysql> create table tt(d decimal(0, 0));
Query OK, 0 rows affected (0.01 sec)

mysql> show create table tt\G
*************************** 1. row ***************************
       Table: tt
Create Table: CREATE TABLE `tt` (
  `d` decimal(0,0) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
1 row in set (0.00 sec)
```

When create table and decimal field defined use `decimal(0, 0)` should create table with `decimal(10, 0)`.

### 2. What did you expect to see? (Required)

```sql
mysql> create table tt(d decimal(0, 0));
Query OK, 0 rows affected (0.03 sec)

mysql> show create table tt\G
*************************** 1. row ***************************
       Table: tt
Create Table: CREATE TABLE `tt` (
  `d` decimal(10,0) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1919-g3e2ff1d16
Edition: Community
Git Commit Hash: 3e2ff1d16ce5a802efb28111aadcd3e12878ac3a
Git Branch: master
UTC Build Time: 2020-12-25 09:05:53
GoVersion: go1.15.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #22034 

Problem Summary:

Create table with `decimal(0, 0)` will get wrong default value for Flen.

### What is changed and how it works?

What's Changed:
When column type is `decimal(0, 0)` just set Flen to 10.

### Related changes

- No

### Check List 

Tests 

- Unit test
- Integration test

Side effects

-No

### Release note 

- ddl: fix default decimal Flen value.

### CODE REVIEW

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -992,6 +992,10 @@ func checkColumn(colDef *ast.ColumnDef) error {
 		if tp.Flen > mysql.MaxDecimalWidth {
 			return types.ErrTooBigPrecision.GenWithStackByArgs(tp.Flen, colDef.Name.Name.O, mysql.MaxDecimalWidth)
 		}
+
+		if tp.Decimal == 0 && tp.Flen == 0 {
```
Comment (wjhuang2016) [inline planner/core/preprocess.go:996]: It would be better to add some comments for it.

Comment (blacktear23) [reply planner/core/preprocess.go:997]: PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by xiongjiwei — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
