### PR TITLE
planner: show accessed partition when explain mpp query over partition table

### LINKED ISSUE #30365: when using dynamic partition prune mode, MPP query does not show accessed partition in explain results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
mysql> show create table partition_table;
+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table           | Create Table                                                                                                                                                                                                                                                                                                                                           |
+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| partition_table | CREATE TABLE `partition_table` (
  `id` int(11) DEFAULT NULL,
  `store_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`store_id`)
(PARTITION `p0` VALUES LESS THAN (6),
 PARTITION `p1` VALUES LESS THAN (11),
 PARTITION `p2` VALUES LESS THAN (16),
 PARTITION `p3` VALUES LESS THAN (21)) |
+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> explain select count(*) from partition_table where store_id < 10;
+--------------------------------+----------+-------------------+--------------------------------------------------------------------------------+---------------------------------------+
| id                             | estRows  | task              | access object                                                                  | operator info                         |
+--------------------------------+----------+-------------------+--------------------------------------------------------------------------------+---------------------------------------+
| HashAgg_19                     | 1.00     | root              |                                                                                | funcs:count(Column#6)->Column#4       |
| └─TableReader_21               | 1.00     | root              | partition pruning error[planner:1054]Unknown column 'store_id' in 'expression' | data:ExchangeSender_20                |
|   └─ExchangeSender_20          | 1.00     | batchCop[tiflash] |                                                                                | ExchangeType: PassThrough             |
|     └─HashAgg_8                | 1.00     | batchCop[tiflash] |                                                                                | funcs:count(1)->Column#6              |
|       └─Selection_18           | 3323.33  | batchCop[tiflash] |                                                                                | lt(test.partition_table.store_id, 10) |
|         └─TableFullScan_17     | 10000.00 | batchCop[tiflash] | table:partition_table                                                          | keep order:false, stats:pseudo        |
+--------------------------------+----------+-------------------+--------------------------------------------------------------------------------+---------------------------------------+
6 rows in set (0.00 sec)
```
### 2. What did you expect to see? (Required)
The access object of `TableReader_21` shows the accessed partition.
### 3. What did you see instead (Required)
partition pruning error[planner:1054]Unknown column 'store_id' in 'expression' 
### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
master@ cec4acbf5ea952a8f92c8258fce3142528f9fb1e

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #30365

Problem Summary:
As the issue described.
### What is changed and how it works?
The root cause is when convert mpp task into root task, it does not set the `PartitionInfo` in `PhysicalTableReader`.
A simple fix is to set `PartitionInfo` when convert mpp task into root task, however, since mpp task may contain `join/union/union all`, it is possible that a physical table reader contains more than 1 table scan, and just one `PartitionInfo` is not enough in this case. This pr adds `PartitionInfos` in `PhysicalTableReader`, and for mpp task, it will collect all the `PartitionInfo`s into `PhysicalTableReader.PartitionInfos`, when explain query, it will show all the access objects derived from `PhysicalTableReader.PartitionInfos`
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
show accessed partition when explain mpp query over partition table
```

### CODE REVIEW

File: executor/partition_table_test.go [hunk 1]
```diff
@@ -1726,6 +1727,36 @@ func (s *partitionTableSuite) TestAddDropPartitions(c *C) {
...
+	tk.MustExec("set @@tidb_partition_prune_mode = 'dynamic'")
+
+	tk.MustExec(`create table t(a int) partition by range(a) (
+		  partition p0 values less than (5),
+		  partition p1 values less than (10),
+		  partition p2 values less than (15))`)
+	tb := testGetTableByName(c, tk.Se, "tiflash_partition_test", "t")
+	for _, partition := range tb.Meta().GetPartitionInfo().Definitions {
+		err := domain.GetDomain(tk.Se).DDL().UpdateTableReplicaInfo(tk.Se, partition.ID, true)
+		c.Assert(err == nil, IsTrue)
```
Comment (tiancaiamao) [inline executor/partition_table_test.go:1747]: You can write this as `c.Assert(err, IsNil)`

**Review by tiancaiamao — APPROVED** [review]
