### PR TITLE
planner: do not construct index merge join when inner is partition table

### LINKED ISSUE #19408: Incorrect result when using IndexMergeJoin on partitioned tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1, t2;
create table t1  (c_int int, primary key(c_int));
create table t2  (c_int int, unique key (c_int)) partition by hash (c_int) partitions 4;
insert into t1 values (1), (2), (3), (4), (5);
insert into t2 select * from t1;
begin;
delete from t1 where c_int = 1;
select /*+ INL_MERGE_JOIN(t1,t2) */ * from t1, t2 where t1.c_int = t2.c_int;
commit;
```

### 2. What did you expect to see? (Required)

```
+-------+-------+
| c_int | c_int |
+-------+-------+
|     2 |     2 |
|     3 |     3 |
|     4 |     4 |
|     5 |     5 |
+-------+-------+
```

### 3. What did you see instead (Required)

```
+-------+-------+
| c_int | c_int |
+-------+-------+
|     4 |     4 |
|     5 |     5 |
+-------+-------+
```

<details>

```
mysql> begin;
Query OK, 0 rows affected (0.05 sec)

mysql> delete from t1 where c_int = 1;
Query OK, 1 row affected (0.04 sec)

mysql> select * from t1, t2 where t1.c_int = t2.c_int;
+-------+-------+
| c_int | c_int |
+-------+-------+
|     2 |     2 |
|     3 |     3 |
|     4 |     4 |
|     5 |     5 |
+-------+-------+
4 rows in set (0.05 sec)

mysql> explain select * from t1, t2 where t1.c_int = t2.c_int;
+-------------------------------+----------+-----------+------------------------------+------------------------------------------------------+
| id                            | estRows  | task      | access object                | operator info                                        |
+-------------------------------+----------+-----------+------------------------------+------------------------------------------------------+
| Projection_8                  | 12487.50 | root      |                              | test.t1.c_int, test.t2.c_int                         |
| └─HashJoin_27                 | 12487.50 | root      |                              | inner join, equal:[eq(test.t2.c_int, test.t1.c_int)] |
|   ├─IndexReader_29(Build)     | 9990.00  | root      | partition:all                | index:IndexFullScan_28                               |
|   │ └─IndexFullScan_28        | 9990.00  | cop[tikv] | table:t2, index:c_int(c_int) | keep order:false, stats:pseudo                       |
|   └─UnionScan_30(Probe)       | 10000.00 | root      |                              |                                                      |
|     └─TableReader_32          | 10000.00 | root      |                              | data:TableFullScan_31                                |
|       └─TableFullScan_31      | 10000.00 | cop[tikv] | table:t1                     | keep order:false, stats:pseudo                       |
+-------------------------------+----------+-----------+------------------------------+------------------------------------------------------+
7 rows in set (0.04 sec)

mysql> select /*+ INL_MERGE_JOIN(t1,t2) */ * from t1, t2 where t1.c_int = t2.c_int;
+-------+-------+
| c_int | c_int |
+-------+-------+
|     4 |     4 |
|     5 |     5 |
+-------+-------+
2 rows in set (0.05 sec)

mysql> explain select /*+ INL_MERGE_JOIN(t1,t2) */ * from t1, t2 where t1.c_int = t2.c_int;
+------------------------------+----------+-----------+------------------------------+-------------------------------------------------------------------------------------+
| id                           | estRows  | task      | access object                | operator info                                                                       |
+------------------------------+----------+-----------+------------------------------+-------------------------------------------------------------------------------------+
| IndexMergeJoin_18            | 12487.50 | root      |                              | inner join, inner:IndexReader_16, outer key:test.t1.c_int, inner key:test.t2.c_int  |
| ├─UnionScan_25(Build)        | 10000.00 | root      |                              |                                                                                     |
| │ └─TableReader_27           | 10000.00 | root      |                              | data:TableFullScan_26                                                               |
| │   └─TableFullScan_26       | 10000.00 | cop[tikv] | table:t1                     | keep order:false, stats:pseudo                                                      |
| └─IndexReader_16(Probe)      | 1.00     | root      | partition:all                | index:Selection_15                                                                  |
|   └─Selection_15             | 1.00     | cop[tikv] |                              | not(isnull(test.t2.c_int))                                                          |
|     └─IndexRangeScan_14      | 1.00     | cop[tikv] | table:t2, index:c_int(c_int) | range: decided by [eq(test.t2.c_int, test.t1.c_int)], keep order:true, stats:pseudo |
+------------------------------+----------+-----------+------------------------------+-------------------------------------------------------------------------------------+
7 rows in set (0.05 sec)

mysql> commit;
Query OK, 0 rows affected (0.05 sec)

```

</details>

### 4. What is your TiDB version? (Required)

master @ 6831e487a84c8bde625de8c73feec9e6ec02f426

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #19408 

### What is changed and how it works?

What's Changed: If the inner table is a partition table, the index merge join can't be constructed because it requires inner table to keep order.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- none.

### CODE REVIEW

File: executor/index_lookup_merge_join_test.go [hunk 1]
```diff
@@ -65,6 +65,23 @@ func (s *testSuite9) TestIssue18631(c *C) {
...
+func (s *testSuite9) TestIssue19408(c *C) {
+	tk := testkit.NewTestKitWithInit(c, s.store)
+	tk.MustExec("drop table if exists t1, t2")
+	tk.MustExec("create table t1  (c_int int, primary key(c_int))")
+	tk.MustExec("create table t2  (c_int int, unique key (c_int)) partition by hash (c_int) partitions 4")
+	tk.MustExec("insert into t1 values (1), (2), (3), (4), (5)")
+	tk.MustExec("insert into t2 select * from t1")
+	tk.MustExec("begin")
+	tk.MustExec("delete from t1 where c_int = 1")
+	tk.MustQuery("select /*+ INL_MERGE_JOIN(t1,t2) */ * from t1, t2 where t1.c_int = t2.c_int").Check(testkit.Rows(
```
Comment (SunRunAway) [inline executor/index_lookup_merge_join_test.go:77]: It'd be better to check the warning message to ensure the hint working.

**Comment by tiancaiamao** [comment]
LGTM

File: executor/index_lookup_merge_join_test.go (hunk 1 above)
Comment (lzmhhh123) [reply executor/index_lookup_merge_join_test.go]: Done.

**Comment by XuHuaiyu** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
