### PR TITLE
util/ranger: fix infinite recursion when using _tidb_rowid in DNF cond

### LINKED ISSUE #19981: TiDB quits abnormally when we using _tidb_rowid as where clause
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. `create table t1(a varchar(11), b int);`

2. insert 3 million records into table t1. b is from 0 to 2,999,999, a is random varchar with length 6.

3.  SELECT * FROM `test`.`t1`  WHERE `_tidb_rowid` IS NULL OR (`_tidb_rowid` < 974012);

### 2. What did you expect to see? (Required)
The related data can be output correctly.

### 3. What did you see instead (Required)
TiDB quits abnormally.
```sql
mysql> SELECT * FROM `test`.`t1`  WHERE `_tidb_rowid` IS NULL OR (`_tidb_rowid` < 974012) ORDER BY _tidb_rowid;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1213-g716f762d5
Edition: Community
Git Commit Hash: 716f762d5d36d65f1acd2047b6a58b1ce5720966
Git Branch: HEAD
UTC Build Time: 2020-09-13 23:30:29
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #19981 

Problem Summary:

Using _tidb_rowid in DNF conditions will cause `Selectivit()` become infinite recursion because `Selectivity()` doesn't handle _tidb_rowid column.

### What is changed and how it works?

add a check for _tidb_rowid column

### Check List 

Tests 

- Unit test

### Release note 

- no release note

### CODE REVIEW

**Review by winoros — COMMENTED** [review]
lgtm

**Comment by time-and-fate** [comment]
PTAL~ @eurekaka

File: util/ranger/detacher.go [hunk 1]
```diff
@@ -474,6 +475,12 @@ func MergeDNFItems4Col(ctx sessionctx.Context, dnfItems []expression.Expression)
 			continue
 		}
 
+		// If this column is _tidb_rowid, we can't merge it since Selectivity() doesn't handle it, or infinite recursion will happen.
+		if cols[0].ID == model.ExtraHandleID {
```
Comment (eurekaka) [inline util/ranger/detacher.go:479]: Combine this check with 473?

Comment (time-and-fate) [reply util/ranger/detacher.go]: Fixed that. Thanks.

**Review by eurekaka — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by time-and-fate** [comment]
manually cherry-picked to release-4.0 as part of https://github.com/pingcap/tidb/pull/23208
