### PR TITLE
executor: Fix mpp coordinator leak issue

### LINKED ISSUE #59703: MPP coordinator will leak when error happened before respIter is created
When NewExecutorWithRetry returns error, the mpp coordinator may have been already created inside mppExec and registered in global MPPCoordinatorManager map:
https://github.com/pingcap/tidb/blob/907eddd98afe6e927e6876a070b15f4e8e598912/pkg/executor/mpp_gather.go#L104-L108

The mpp coordinator resource will not be released even when MPPGather is closed, because mppExec will be closed only when respIter is not nil:
https://github.com/pingcap/tidb/blob/907eddd98afe6e927e6876a070b15f4e8e598912/pkg/executor/mpp_gather.go#L133-L135

### PR DESCRIPTION
**Pull request by yibin87**
### What problem does this PR solve?

Issue Number: close #59703 

Problem Summary:

Described in issue.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/mpp_gather.go [hunk 1]
```diff
@@ -102,6 +102,8 @@ func (e *MPPGather) Open(ctx context.Context) (err error) {
 	}
 	planIDs := collectPlanIDs(e.originalPlan, nil)
 	if e.mppExec, err = mpp.NewExecutorWithRetry(ctx, e.Ctx(), e.memTracker, planIDs, e.originalPlan, e.startTS, e.mppQueryID, e.is); err != nil {
+		// Ignore any errors during close process
+		_ = e.mppExec.Close()
```
Comment (guo-shaoge) [inline pkg/executor/mpp_gather.go:106]: check if `e.mppExec` is nil first?

Comment (yibin87) [reply pkg/executor/mpp_gather.go:106]: Nice, will change it

**Review by windtalker — APPROVED** [review]
lgtm

**Review by guo-shaoge — APPROVED** [review]
