### PR TITLE
*: fix tidb panic in (*memoryUsageAlarm).recordSQL

### LINKED ISSUE #58942: TiDB panic in (*memoryUsageAlarm).recordSQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2736fa4]goroutine 2180 [running]:
github.com/pingcap/tidb/util/memory.(*Tracker).MaxConsumed(...)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:406
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).recordSQL.func3(0x0?, 0x14e1684?)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:214 +0x34
sort.order2_func(...)
        /usr/local/go/src/sort/zsortfunc.go:299
sort.median_func({0x4dacba6068?, 0x44205a2620?}, 0x3, 0x6, 0x9, 0x4dacba5c88)
        /usr/local/go/src/sort/zsortfunc.go:309 +0x88
sort.choosePivot_func({0x4dacba6068?, 0x44205a2620?}, 0x40?, 0x191?)
        /usr/local/go/src/sort/zsortfunc.go:284 +0xe8
sort.pdqsort_func({0x4dacba6068?, 0x44205a2620?}, 0x0?, 0x191?, 0x4dacba5db8?)
        /usr/local/go/src/sort/zsortfunc.go:89 +0xa4
sort.Slice({0x3453ba0, 0x460a896030}, 0x1e3?)
        /usr/local/go/src/sort/slice.go:23 +0x94
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).recordSQL.func2(0x454e4f4600?)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:187 +0x6c
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).recordSQL(0x4dacba7f20, {0x4018758?, 0x401072aee0?})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:213 +0x4bc
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).doRecord(0x4dacba7f20, 0x1517230?, 0x6026780?, {0x4018758, 0x401072aee0})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:145 +0x73c
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).alarm4ExcessiveMemUsage(0x4dacba7f20, {0x4018758, 0x401072aee0})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:121 +0x390
github.com/pingcap/tidb/util/expensivequery.(*Handle).Run(0x40007168b8)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:91 +0x1b8
created by main.createServer
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:730 +0x3a8
```

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #58942

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix tidb panic in (*memoryUsageAlarm).recordSQL
```

### CODE REVIEW

File: util/expensivequery/memory_usage_alarm.go [hunk 1]
```diff
@@ -211,7 +231,9 @@ func (record *memoryUsageAlarm) recordSQL(sm util.SessionManager) {
 
 	_, err = f.WriteString("The 10 SQLs with the most memory usage for OOM analysis\n")
 	printTop10(func(i, j int) bool {
-		return pinfo[i].StmtCtx.MemTracker.MaxConsumed() > pinfo[j].StmtCtx.MemTracker.MaxConsumed()
+		i_consume := getCurrentMemoryUsage(pinfo[i].RefCountOfStmtCtx, pinfo[i].StmtCtx)
+		j_consume := getCurrentMemoryUsage(pinfo[j].RefCountOfStmtCtx, pinfo[j].StmtCtx)
+		return i_consume > j_consume
```
Comment (windtalker) [inline util/expensivequery/memory_usage_alarm.go:236]:
```suggestion
		iConsume := getCurrentMemoryUsage(pinfo[i].RefCountOfStmtCtx, pinfo[i].StmtCtx)
		jConsume := getCurrentMemoryUsage(pinfo[j].RefCountOfStmtCtx, pinfo[j].StmtCtx)
		return iConsume > jConsume
```

**Review by wshwsh12 — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]
