### PR TITLE
pkg/lightning, tests/realtikvtest: stabilize next-gen add-index tests

### LINKED ISSUE #67830: tests/realtikvtest: next-gen add-index cases can time out on split/ingest retries
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Run the next-gen real cluster shard that contains `tests/realtikvtest/addindextest`, for example:
   [pull_integration_realcluster_test_next_gen/510](https://prow.tidb.net/jenkins/job/tidbcloud/job/cloud-storage-engine/job/dedicated/job/pull_integration_realcluster_test_next_gen/510/stages/log?nodeId=435)
2. Observe `TestCreateNonUniqueIndex` in `tests/realtikvtest/addindextest`.
3. The test may spend most of its budget retrying split/ingest work and eventually hit the Go test timeout.

Local diagnosis also reproduced the slow path on a next-gen TiKV cluster:
- without forcing split before ingest, `TestCreateNonUniqueIndex` took about `276s`
- with split-before-ingest enabled in the test, the same case dropped to about `60s`

### 2. What did you expect to see? (Required)

The next-gen add-index realtikv tests should complete consistently within the shard timeout budget.

### 3. What did you see instead (Required)

`TestCreateNonUniqueIndex` can spend most of its runtime on retryable split/ingest churn and time out.

Observed signals during diagnosis included:
- repeated split/scatter retries with `EpochNotMatch`
- repeated ingest retryable errors such as `RegionNotInitialized`, `ServerIsBusy`, and `EpochNotMatch` on the slow path
- CI timeout in the next-gen shard for `TestCreateNonUniqueIndex`

Root cause summary:
- next-gen TiKV add-index ingest tests can be much slower when the ingest path does not split the target ranges up front
- the affected realtikv tests benefit from forcing split-before-ingest and from having a test hook to tune retry backoff when region-job retries do happen

### 4. What is your TiDB version? (Required)

This is a repository test failure on current `master` / next-gen CI rather than a standalone SQL reproduction with `SELECT tidb_version()` output.

Relevant code under test:
- upstream repository: `pingcap/tidb`
- failing CI example: [pull_integration_realcluster_test_next_gen/510](https://prow.tidb.net/jenkins/job/tidbcloud/job/cloud-storage-engine/job/dedicated/job/pull_integration_realcluster_test_next_gen/510/stages/log?nodeId=435)

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #67830

Problem Summary:

Next-gen `tests/realtikvtest/addindextest` cases can spend most of their runtime on split/ingest retry churn and hit the shard timeout budget. The tests need a reliable way to force split-before-ingest and to tune the region-job retry backoff used in the retry path.

### What changed and how does it work?

- add an `adjustNeedSplit` failpoint hook in the local backend so tests can force split-before-ingest
- change `adjustRegionJobRetryBackoff` to override a `time.Duration` directly, so tests can also use sub-second backoff values when needed
- add a shared `alwaysSplitAndReduceBackoff` helper in `tests/realtikvtest/addindextest` and apply it to the next-gen add-index suites
- include the corresponding Bazel metadata updates

Measured result on `TestCreateNonUniqueIndex`:
- original path without the test helper: `276.38s` test time / `279.570s` total
- after this change with the test helper enabled: `64.19s` test time / `67.432s` total

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Manual test steps:

```bash
make failpoint-enable
go test -run TestCreateNonUniqueIndex -tags=intest,deadlock,nextgen -count=1 -v ./tests/realtikvtest/addindextest
make failpoint-disable
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Tests**
  * Broadened and unified test instrumentation for index-creation scenarios (concurrent DDL, multi-schema, PiTR and failpoint-driven cases).
  * Added a shared test helper to enable faster, deterministic test paths and to adjust retry/backoff behavior for more reliable test execution.
* **Chores**
  * Tweaked test build configuration to improve test parallelism and ensure required test dependencies are included.

### CODE REVIEW

File: pkg/lightning/backend/local/local.go [hunk 1]
```diff
@@ -1089,6 +1089,7 @@ func (local *Backend) prepareAndSendJob(
 	failpoint.Inject("failToSplit", func(_ failpoint.Value) {
```
Comment (lance6716) [inline pkg/lightning/backend/local/local.go]: maybe also replace the call of `failToSplit` to `adjustNeedSplit`

File: tests/realtikvtest/addindextest/add_index_test.go [hunk 2]
```diff
@@ -35,7 +36,24 @@ func init() {
 	})
 }
 
+func enableFastAddIndexFailpoints(t *testing.T) {
```
Comment (lance6716) [inline tests/realtikvtest/addindextest/add_index_test.go:39]: Do we need some cleanup? Not sure other unit tests is also run in this testing process.

**Review by lance6716 — APPROVED** [review]

File: tests/realtikvtest/addindextest/add_index_test.go (hunk 2 above)
Comment (D3Hunter) [reply tests/realtikvtest/addindextest/add_index_test.go:39]: `testfailpoint` will cleanup when test finished

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/lightning/backend/local/local.go (hunk 1 above)
Comment (D3Hunter) [reply pkg/lightning/backend/local/local.go]: there are 2 failpoints with same name `failToSplit`, previous i thought they are co-related and cannot change alone, seems not so.
changed https://github.com/pingcap/tidb/pull/67831/commits/64ab34361f18486403b81ac79ef181a13c0a2850

**Review by Leavrth — APPROVED** [review]
