### PR TITLE
util/ranger: consider good non-point ranges from CNF item

### LINKED ISSUE #44389: Cannot build optimal range on index ab for c = 10 and (a = 'xx' or (a = 'kk' and b = 1))
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(id int, a varchar(100), b int, c int, index idx_ab(a, b));
explain select * from t where c = 10 and (a = 'xx' or (a = 'kk' and b = 1));
```

### 2. What did you expect to see? (Required)
```
mysql> explain select * from t where c = 10 and (a = 'xx' or (a = 'kk' and b = 1));
+-------------------------------+---------+-----------+-----------------------------+--------------------------------------------------------------------+
| id                            | estRows | task      | access object               | operator info                                                      |
+-------------------------------+---------+-----------+-----------------------------+--------------------------------------------------------------------+
| IndexLookUp_11                | 0.01    | root      |                             |                                                                    |
| ├─IndexRangeScan_8(Build)     | 10.10   | cop[tikv] | table:t, index:idx_ab(a, b) | range:["kk" 1,"kk" 1], ["xx","xx"], keep order:false, stats:pseudo |
| └─Selection_10(Probe)         | 0.01    | cop[tikv] |                             | eq(test.t.c, 10)                                                   |
|   └─TableRowIDScan_9          | 10.10   | cop[tikv] | table:t                     | keep order:false, stats:pseudo                                     |
+-------------------------------+---------+-----------+-----------------------------+--------------------------------------------------------------------+
4 rows in set (0.01 sec)
```

### 3. What did you see instead (Required)
```
mysql> explain select * from t where c = 10 and (a = 'xx' or (a = 'kk' and b = 1));
+----------------------------+---------+-----------+-----------------------------+------------------------------------------------------------------+
| id                         | estRows | task      | access object               | operator info                                                    |
+----------------------------+---------+-----------+-----------------------------+------------------------------------------------------------------+
| IndexLookUp_12             | 0.01    | root      |                             |                                                                  |
| ├─Selection_10(Build)      | 0.02    | cop[tikv] |                             | or(eq(test.t.a, "xx"), and(eq(test.t.a, "kk"), eq(test.t.b, 1))) |
| │ └─IndexRangeScan_8       | 20.00   | cop[tikv] | table:t, index:idx_ab(a, b) | range:["kk","kk"], ["xx","xx"], keep order:false, stats:pseudo   |
| └─Selection_11(Probe)      | 0.01    | cop[tikv] |                             | eq(test.t.c, 10)                                                 |
|   └─TableRowIDScan_9       | 0.02    | cop[tikv] | table:t                     | keep order:false, stats:pseudo                                   |
+----------------------------+---------+-----------+-----------------------------+------------------------------------------------------------------+
5 rows in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #44389

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: util/ranger/detacher.go [hunk 1]
```diff
@@ -185,19 +186,71 @@ func getPotentialEqOrInColOffset(sctx sessionctx.Context, expr expression.Expres
...
+			maxColNum = len(ran.LowVal)
+			minColNum = len(ran.LowVal)
+		} else {
+			if len(ran.LowVal) > maxColNum {
+				maxColNum = len(ran.LowVal)
+			}
+			if len(ran.LowVal) < minColNum {
+				minColNum = len(ran.LowVal)
+			}
+		}
```
Comment (time-and-fate) [inline util/ranger/detacher.go:215]: We can initiate `minColNum` with `MaxInt` and then use `Max` and `Min` to make the code simpler.

**Review by time-and-fate — APPROVED** [review]

**Review by chrysan — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
