### PR TITLE
expression: handle duration type infer in least and greatest

### LINKED ISSUE #22200: runtime error: invalid memory address or nil pointer dereference
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
SELECT LEAST(TIME'00:00:00.1', TIME'00:00:00.12') AS a
```

### 2. What did you expect to see? (Required)
OK?

### 3. What did you see instead (Required)
```
runtime error: invalid memory address or nil pointer dereference
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1968-g4bfd10cec
Edition: Community
Git Commit Hash: 4bfd10cec89dd1640c82441ac8f4939304134662
Git Branch: master
UTC Build Time: 2021-01-05 12:47:53
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by iosmanthus**
### What problem does this PR solve?

Issue Number: close #22200 

Problem Summary:

### What is changed and how it works?

This pull request compares duration as string while they are formalized which will prevent panicking while encountering a non-handled duration type infer.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- expression: handle duration type infer in least and greatest

### CODE REVIEW

File: expression/builtin_compare.go [hunk 1]
```diff
@@ -407,12 +407,14 @@ func resolveType4Extremum(args []Expression) types.EvalType {
 	if aggType.EvalType().IsStringKind() {
 		for i := range args {
 			item := args[i].GetType()
-			if types.IsTemporalWithDate(item.Tp) {
-				temporalItem = item
+			if types.IsTemporal(item.Tp) {
```
Comment (wjhuang2016) [inline expression/builtin_compare.go:410]: Please add some comments about why do we need to do it.

**Comment by wjhuang2016** [comment]
this pr:
```
mysql> SELECT LEAST(TIME'00:00:00.1', TIME'00:00:00.12000');
+-----------------------------------------------+
| LEAST(TIME'00:00:00.1', TIME'00:00:00.12000') |
+-----------------------------------------------+
| 00:00:00.1                                    |
+-----------------------------------------------+
1 row in set (0.00 sec)
```

MySQL:
```
mysql> SELECT LEAST(TIME'00:00:00.1', TIME'00:00:00.12000');
+-----------------------------------------------+
| LEAST(TIME'00:00:00.1', TIME'00:00:00.12000') |
+-----------------------------------------------+
| 00:00:00.10000                                |
+-----------------------------------------------+
1 row in set (0.01 sec)
```

Though is' ok and the same as release 4.0, it's better to make it be compatible with MySQL. If it is hard, I think that's fine.

File: expression/builtin_compare.go (hunk 1 above)
Comment (iosmanthus) [reply expression/builtin_compare.go:410]: OK.

**Comment by iosmanthus** [comment]
> this pr:
> 
> ```
> mysql> SELECT LEAST(TIME'00:00:00.1', TIME'00:00:00.12000');
> +-----------------------------------------------+
> | LEAST(TIME'00:00:00.1', TIME'00:00:00.12000') |
> +-----------------------------------------------+
> | 00:00:00.1                                    |
> +-----------------------------------------------+
> 1 row in set (0.00 sec)
> ```
> 
> MySQL:
> 
> ```
> mysql> SELECT LEAST(TIME'00:00:00.1', TIME'00:00:00.12000');
> +-----------------------------------------------+
> | LEAST(TIME'00:00:00.1', TIME'00:00:00.12000') |
> +-----------------------------------------------+
> | 00:00:00.10000                                |
> +-----------------------------------------------+
> 1 row in set (0.01 sec)
> ```
> 
> Though is' ok and the same as release 4.0, it's better to make it be compatible with MySQL. If it is hard, I think that's fine.

For now, I think we should consider the bug itself, instead of the compatibility with `MySQL`. We may fix this behaviour in another pull request.

**Comment by iosmanthus** [comment]
@wjhuang2016 @XuHuaiyu PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: expression/builtin_compare.go [hunk 2]
```diff
@@ -407,12 +407,15 @@ func resolveType4Extremum(args []Expression) types.EvalType {
 	if aggType.EvalType().IsStringKind() {
 		for i := range args {
 			item := args[i].GetType()
-			if types.IsTemporalWithDate(item.Tp) {
-				temporalItem = item
+			// Find the temporal value in the arguments but prefer DateTime value.
+			if types.IsTemporal(item.Tp) {
+				if temporalItem == nil || temporalItem.Tp == mysql.TypeDatetime {
```
Comment (wshwsh12) [inline expression/builtin_compare.go:412]: // Find the temporal value in the arguments but **prefer** DateTime value?
Should the condition be `temporalItem == nil || temporalItem.Tp != mysql.TypeDatetime`?

File: expression/builtin_compare.go [hunk 3]
```diff
@@ -469,7 +474,7 @@ func (c *greatestFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 	case types.ETDecimal:
 		sig = &builtinGreatestDecimalSig{bf}
 		sig.setPbCode(tipb.ScalarFuncSig_GreatestDecimal)
-	case types.ETString:
+	case types.ETString, types.ETDuration:
```
Comment (wshwsh12) [inline expression/builtin_compare.go:477]: tp never be types.ETDuration, because tp will be set to types.ETString in L451?

File: expression/builtin_compare.go [hunk 4]
```diff
@@ -684,10 +691,10 @@ func (c *leastFunctionClass) getFunction(ctx sessionctx.Context, args []Expressi
 	case types.ETDecimal:
 		sig = &builtinLeastDecimalSig{bf}
 		sig.setPbCode(tipb.ScalarFuncSig_LeastDecimal)
-	case types.ETString:
+	case types.ETString, types.ETDuration:
```
Comment (wshwsh12) [inline expression/builtin_compare.go:694]: ditto

File: types/etc.go [hunk 5]
```diff
@@ -89,6 +89,12 @@ func IsTemporalWithDate(tp byte) bool {
 	return IsTypeTime(tp)
 }
 
+// IsTemporal returns  a boolean indicating
+// if the tp is time type.
+func IsTemporal(tp byte) bool {
```
Comment (wshwsh12) [inline types/etc.go:94]: Use the function `IsTypeTemporal`?

**Review by wshwsh12 — COMMENTED** [review]
Rest LGTM

File: expression/builtin_compare.go (hunk 3 above)
Comment (iosmanthus) [reply expression/builtin_compare.go:477]: Done.

File: types/etc.go (hunk 5 above)
Comment (iosmanthus) [reply types/etc.go:94]: Done.

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
