### PR TITLE
planner/core: fix Wrong behavior of prepare && execute

### LINKED ISSUE #8518: Wrong behavior of prepare && execute
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
create table t1 (
  id int(11) unsigned not null primary key auto_increment,
  partner_id varchar(35) not null,
  t1_status_id int(10) unsigned
);

insert into t1 values ("1", "partner1", "10"), ("2", "partner2", "10"),
                      ("3", "partner3", "10"), ("4", "partner4", "10");

create table t2 (
  id int(11) unsigned not null default '0',
  t1_line_id int(11) unsigned not null default '0',
  article_id varchar(20),
  sequence int(11) not null default '0',
  primary key  (id,t1_line_id)
);

insert into t2 values ("1", "1", "sup", "0"), ("2", "1", "sup", "1"),
                      ("2", "2", "sup", "2"), ("2", "3", "sup", "3"),
                      ("2", "4", "imp", "4"), ("3", "1", "sup", "0"),
                      ("4", "1", "sup", "0");

create table t3 (
  id int(11) not null default '0',
  preceding_id int(11) not null default '0',
  primary key  (id,preceding_id)
);

create table t4 (
  user_id varchar(50) not null,
  article_id varchar(20) not null,
  primary key  (user_id,article_id)
);

insert into t4 values("nicke", "imp");
prepare stmt from
'select distinct t1.partner_id
from t1 left join t3 on t1.id = t3.id
     left join t1 pp on pp.id = t3.preceding_id
where
  exists (
    select *
    from t2 as pl_inner
    where pl_inner.id = t1.id
    and pl_inner.sequence <= (
      select min(sequence) from t2 pl_seqnr
      where pl_seqnr.id = t1.id
    )
    and exists (
      select * from t4
      where t4.article_id = pl_inner.article_id
      and t4.user_id = ?
    )
  )
  and t1.id = ?
group by t1.id
having count(pp.id) = 0';
set @user_id = 'nicke';
set @id = '2';
execute stmt using @user_id, @id;
```

2. What did you expect to see?

execute successfully

3. What did you see instead?

```
mysql> execute stmt using @user_id, @id;
ERROR 1146 (42S02): Table 'test.pp' doesn't exist
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master 4bcdb6d8ee7906947008603d95c543cd978b1106

Note: it should work with master branch a month ago or so.

### PR DESCRIPTION
**Pull request by hhxcc**
### What problem does this PR solve? 
Fix #8518 

### What is changed and how it works?
When prepare statement use table alias in group by clause ,
function extractTableList  will  change origin table name  in prepare stage,
so  fix it.

Tests 

 - Unit test

### CODE REVIEW

File: planner/core/prepare_test.go [hunk 1]
```diff
@@ -264,6 +264,38 @@ func (s *testPrepareSuite) TestPrepareOverMaxPreparedStmtCount(c *C) {
...
+		id int(11) not null default '0',
+		preceding_id int(11) not null default '0',
+		primary key  (id,preceding_id)
+	  );`)
+	tk.MustExec(`prepare stmt from 'SELECT DISTINCT t1.partner_id
+	FROM t1
+		LEFT JOIN t3 ON t1.id = t3.id
+		LEFT JOIN t1 pp ON pp.id = t3.preceding_id
+	GROUP BY t1.id ;'`)
+	tk.MustQuery("execute stmt").Sort().Check(testkit.Rows("partner1", "partner2", "partner3", "partner4"))
```
Comment (XuHuaiyu) [inline planner/core/prepare_test.go]: I test this with branch master, it will not fail.

Comment (hhxcc) [reply planner/core/prepare_test.go]: this my test result in branch master 
```
----------------------------------------------------------------------
FAIL: prepare_test.go:268: testPrepareSuite.TestPrepareTableAsNameOnGroupBy

prepare_test.go:296:
    tk.MustQuery("execute stmt").Sort().Check(testkit.Rows("partner1", "partner2", "partner3", "partner4"))
/Users/hao/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:183:
    tk.c.Assert(errors.ErrorStack(err), check.Equals, "", comment)
... obtained string = "" +
...     "[schema:1146]Table 'test.pp' doesn't exist\n" +
...     "github.com/pingcap/errors.AddStack\n" +
...     "\t/Users/hao/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174\n" +
...     "github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs\n" +
...     "\t/Users/hao/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190121074657-4b899f19591e/terror/terror.go:233\n" +
...     "github.com/pingcap/tidb/infoschema.(*infoSchema).TableByName\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/infoschema/infoschema.go:179\n" +
...     "github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:1987\n" +
...     "github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:144\n" +
...     "github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildJoin\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:301\n" +
...     "github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:136\n" +
...     "github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:1802\n" +
...     "github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/planbuilder.go:188\n" +
...     "github.com/pingcap/tidb/planner.Optimize\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/optimize.go:38\n" +
...     "github.com/pingcap/tidb/planner/core.(*Execute).getPhysicalPlan\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/common_plans.go:212\n" +
...     "github.com/pingcap/tidb/planner/core.(*Execute).OptimizePreparedPlan\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/common_plans.go:187\n" +
...     "github.com/pingcap/tidb/planner.Optimize\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/optimize.go:54\n" +
...     "github.com/pingcap/tidb/executor.(*Compiler).Compile\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/executor/compiler.go:49\n" +
...     "github.com/pingcap/tidb/session.(*session).execute\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/session/session.go:950\n" +
...     "github.com/pingcap/tidb/session.(*session).Execute\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/session/session.go:912\n" +
...     "github.com/pingcap/tidb/util/testkit.(*TestKit).Exec\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:137\n" +
...     "github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:182\n" +
...     "github.com/pingcap/tidb/planner/core_test.(*testPrepareSuite).TestPrepareTableAsNameOnGroupBy\n" +
...     "\t/Users/hao/go/src/github.com/pingcap/tidb/planner/core/prepare_test.go:296\n" +
...     "runtime.call32\n" +
...     "\t/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:522\n" +
...     "reflect.Value.call\n" +
...     "\t/usr/local/Cellar/go/1.11.2/libexec/src/reflect/value.go:447\n" +
...     "reflect.Value.Call\n" +
...     "\t/usr/local/Cellar/go/1.11.2/libexec/src/reflect/value.go:308\n" +
...     "github.com/pingcap/check.(*suiteRunner).forkTest.func1\n" +
...     "\t/Users/hao/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:836\n" +
...     "github.com/pingcap/check.(*suiteRunner).forkCall.func1\n" +
...     "\t/Users/hao/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:730\n" +
...     "runtime.goexit\n" +
...     "\t/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333"
... expected string = ""
... sql:execute stmt, args:[]
```

Comment (eurekaka) [reply planner/core/prepare_test.go]: The test need to specifically enable prepare plan cache, because it is disabled by default. You can reference function `TestPrepareCache` for details.

Comment (eurekaka) [reply planner/core/prepare_test.go]: @hhxcc FYI

**Comment by zz-jason** [comment]
@hhxcc Thanks for your contribution, could you help us to cherry pick this commit to the release-2.1 branch?

**Comment by hhxcc** [comment]
@zz-jason  ok,  pr  #9466
