### PR TITLE
br: prevent br from becoming ddl owner

### LINKED ISSUE #63089: Prevent br from becoming ddl owner
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. run BR restore
2. TiDB oom
3. BR becomes DDL owner

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #63089

Problem Summary:
prevent br from becoming ddl owner
### What changed and how does it work?
prevent br from becoming ddl owner
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/cmd/br/abort.go [hunk 1]
```diff
@@ -30,6 +31,9 @@ func NewAbortCommand() *cobra.Command {
 			task.LogArguments(c)
 			// disable stats otherwise takes too much memory
 			session.DisableStats4Test()
+
+			// Do not run ddl worker in BR.
+			config.GetGlobalConfig().Instance.TiDBEnableDDL.Store(false)
```
Comment (lance6716) [inline br/cmd/br/abort.go]: how about set it in main.go?

Comment (Leavrth) [reply br/cmd/br/abort.go]: Get

**Review by lance6716 — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]
