### PR TITLE
*: insert of invalid timestamp succeeded

### LINKED ISSUE #25999: execute insert statement successfully with invaild timestamp
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
MySQL [test]> show create table t2;
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                       |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| t2    | CREATE TABLE `t2` (
  `id` int(11) DEFAULT NULL,
  `time1` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> INSERT INTO t2 (id, time1) VALUES (10, TIMESTAMP '1018-12-23 00:00:00');
Query OK, 1 row affected (0.02 sec)

MySQL [test]> select * from t2;
ERROR 1292 (22007): Incorrect datetime value: '1018-12-23 00:00:00'

MySQL [test]> truncate t2;
Query OK, 0 rows affected (0.53 sec)

MySQL [test]> INSERT INTO t2 (id, time1) VALUES (10, '1018-12-23 00:00:00');
ERROR 1292 (22007): Incorrect timestamp value: '1018-12-23 00:00:00' for column 'time1' at row 1


### 2. What did you expect to see? (Required)

MySQL [test]> INSERT INTO t2 (id, time1) VALUES (10, TIMESTAMP '1018-12-23 00:00:00');
ERROR 1292 (22007): Incorrect timestamp value: '1018-12-23 00:00:00' for column 'time1' at row 1

### 3. What did you see instead (Required)
MySQL [test]> INSERT INTO t2 (id, time1) VALUES (10, TIMESTAMP '1018-12-23 00:00:00');
Query OK, 1 row affected (0.02 sec)

MySQL [test]> select * from t2;
ERROR 1292 (22007): Incorrect datetime value: '1018-12-23 00:00:00'

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

MySQL [test]> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.0.1
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 05:51:17
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> select @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #25999 

Problem Summary:
Insert succeeded with values out-of-range for Timestamp

### What is changed and how it works?
Never accept timestamp values out-of-range

What's Changed:
Check for values out-of-range

How it Works:
Now truncates and returns a warning or returns an error depending on sql_mode.

### Check List 

Tests 

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 
```release-note
Timestamp values out-of-range can no longer be inserted.
```

### CODE REVIEW

File: executor/index_lookup_join.go [hunk 1]
```diff
@@ -517,6 +517,11 @@ func (iw *innerWorker) constructLookupContent(task *lookUpJoinTask) ([]*indexJoi
 		for rowIdx := 0; rowIdx < numRows; rowIdx++ {
 			dLookUpKey, dHashKey, err := iw.constructDatumLookupKey(task, chkIdx, rowIdx)
 			if err != nil {
+				if terror.ErrorEqual(err, types.ErrWrongValue) {
+					// we ignore rows with invalid datetime
```
Comment (zimulala) [inline executor/index_lookup_join.go:521]:
```suggestion
					// We ignore rows with invalid datetime.
```

File: executor/insert_test.go [hunk 2]
```diff
@@ -336,6 +336,18 @@ func (s *testSuite3) TestInsertWrongValueForField(c *C) {
 	tk.MustExec(`create table t (a year);`)
 	_, err = tk.Exec(`insert into t values(2156);`)
 	c.Assert(err.Error(), Equals, `[types:8033]invalid year`)
+
+	tk.MustExec(`DROP TABLE IF EXISTS ts`)
+	tk.MustExec(`CREATE TABLE ts (id int DEFAULT NULL, time1 TIMESTAMP NULL DEFAULT NULL)`)
+	tk.MustExec(`SET @@sql_mode=''`)
+	tk.MustExec(`INSERT INTO ts (id, time1) VALUES (1, TIMESTAMP '1018-12-23 00:00:00')`)
+	tk.MustQuery(`SHOW WARNINGS`).Check(testkit.Rows(`Warning 1292 Incorrect timestamp value: '1018-12-23 00:00:00'`))
```
Comment (zimulala) [inline executor/insert_test.go:344]: In my MySQL8.0, I executed the above statements, it returned the warning of `Out of range`. That's not consistent with the tests.
```
mysql> SET @@sql_mode='';
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE ts (id int DEFAULT NULL, time1 TIMESTAMP NULL DEFAULT NULL);
Query OK, 0 rows affected (0.07 sec)

mysql> INSERT INTO ts (id, time1) VALUES (1, TIMESTAMP '1018-12-23 00:00:00') ;
Query OK, 1 row affected, 1 warning (0.02 sec)

mysql> show warnings;
+---------+------+------------------------------------------------+
| Level   | Code | Message                                        |
+---------+------+------------------------------------------------+
| Warning | 1264 | Out of range value for column 'time1' at row 1 |
+---------+------+------------------------------------------------+
1 row in set (0.01 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.25    |
+-----------+
1 row in set (0.01 sec)
```

File: types/datum.go [hunk 3]
```diff
@@ -1128,16 +1128,10 @@ func (d *Datum) convertToMysqlTimestamp(sc *stmtctx.StatementContext, target *Fi
 	}
 	switch d.k {
 	case KindMysqlTime:
-		// `select timestamp(cast("1000-01-02 23:59:59" as date)); ` casts usage will succeed.
-		// Alter datetime("1000-01-02 23:59:59") to timestamp will error.
-		if sc.InReorgAttribute {
```
Comment (zimulala) [inline types/datum.go:1133]: Could remove the field of `InReorgAttribute` in SC? It seems to be used only for `KindMysqlTime`.

File: executor/insert_test.go (hunk 2 above)
Comment (mjonss) [reply executor/insert_test.go:344]: Yes, TiDB handling of out-of-range differs from MySQL.
Here is an example for `int` instead of `timestamp`:
TiDB:
```sql
tidb> CREATE TABLE t1 (
  id int NOT NULL PRIMARY KEY,
  ts timestamp NULL DEFAULT NULL
);
tidb> INSERT INTO t1 (id, ts) VALUES (2147483648, TIMESTAMP '2018-12-23 00:00:00');
Query OK, 1 row affected, 1 warning (0,00 sec)
tidb> SHOW WARNINGS;
+---------+------+-----------------------------------+
| Level   | Code | Message                           |
+---------+------+-----------------------------------+
| Warning | 1690 | constant 2147483648 overflows int |
+---------+------+-----------------------------------+
1 row in set (0,00 sec)
```
MySQL:
```sql
mysql> INSERT INTO t1 (id, ts) VALUES (2147483648, TIMESTAMP '2018-12-23 00:00:00');
Query OK, 1 row affected, 1 warning (0,01 sec)
mysql> SHOW WARNINGS
+---------+------+---------------------------------------------+
| Level   | Code | Message                                     |
+---------+------+---------------------------------------------+
| Warning | 1264 | Out of range value for column 'id' at row 1 |
+---------+------+---------------------------------------------+
```

I think fixing these differences is outside of the scope for this bug. Do you want me to create a new issue for the mysql incompatibility?

File: types/datum.go (hunk 3 above)
Comment (mjonss) [reply types/datum.go:1133]: Good catch! Thank you for spotting it, I have removed it (basically this PR will replace https://github.com/pingcap/tidb/pull/26395 apart from the added tests).

File: executor/insert_test.go (hunk 2 above)
Comment (zimulala) [reply executor/insert_test.go:344]: I think we can file an issue first.

File: executor/index_lookup_join.go [hunk 4]
```diff
@@ -517,6 +517,11 @@ func (iw *innerWorker) constructLookupContent(task *lookUpJoinTask) ([]*indexJoi
 		for rowIdx := 0; rowIdx < numRows; rowIdx++ {
 			dLookUpKey, dHashKey, err := iw.constructDatumLookupKey(task, chkIdx, rowIdx)
 			if err != nil {
+				if terror.ErrorEqual(err, types.ErrWrongValue) {
```
[the remark this answers is not in the document]
Comment (mjonss) [reply executor/index_lookup_join.go:520]: This change was needed (detected) by TestIssue23609, I don't think it should have different behaviour depending on sql_mode (as I understand it, this is an equal match/lookup so if there is an invalid timestamp, it cannot find a match).

File: executor/insert_test.go (hunk 2 above)
Comment (mjonss) [reply executor/insert_test.go:344]: Issue created: https://github.com/pingcap/tidb/issues/26750

File: executor/index_lookup_join.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (zimulala) [reply executor/index_lookup_join.go:520]: Got it.

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by mjonss** [comment]
@tangenta Could you please take a look/review?

**Review by bb7133 — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
