### PR TITLE
infosync: refactor server config into dynamic and static sections

### LINKED ISSUE #58405: race when updating labels and store topology runs concurrently
## Bug Report

Please answer these questions before submitting your issue. Thanks!

Found by @lcwangchao 's great code review.

### 1. Minimal reproduce step (Required)

1. Add a test into `pkg/server/handler/tests/http_handler_test.go`.

```go
func TestSetLabelsConcurrentWithStoreTopology(t *testing.T) {
	ts := createBasicHTTPHandlerTestSuite()
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	ts.startServer(t)
	defer ts.stopServer(t)

	integration.BeforeTestExternal(t)
	cluster := integration.NewClusterV3(t, &integration.ClusterConfig{Size: 1})
	defer cluster.Terminate(t)
	client := cluster.RandClient()
	infosync.SetEtcdClient(client)

	ts.domain.InfoSyncer().Restart(ctx)
	ts.domain.InfoSyncer().RestartTopology(ctx)

	testUpdateLabels := func() {
		labels := map[string]string{}
		labels["zone"] = fmt.Sprintf("z-%v", rand.Intn(100000))
		buffer := bytes.NewBuffer([]byte{})
		require.Nil(t, json.NewEncoder(buffer).Encode(labels))
		resp, err := ts.PostStatus("/labels", "application/json", buffer)
		require.NoError(t, err)
		require.NotNil(t, resp)
		defer func() {
			require.NoError(t, resp.Body.Close())
		}()
		require.Equal(t, http.StatusOK, resp.StatusCode)
		newLabels := config.GetGlobalConfig().Labels
		require.Equal(t, newLabels, labels)
	}
	testStoreTopology := func() {
		require.NoError(t, ts.domain.InfoSyncer().StoreTopologyInfo(context.Background()))
	}

	done := make(chan struct{})
	go func() {
		for {
			select {
			case <-done:
				return
			default:
				testStoreTopology()
			}
		}
	}()
	for i := 0; i < 100; i++ {
		testUpdateLabels()
	}
	close(done)

	// reset the global variable
	config.UpdateGlobal(func(conf *config.Config) {
		conf.Labels = map[string]string{}
	})
}
```

2. Run the test with race detection.

```bash
go test ./pkg/server/handler/tests -run TestSetLabelsConcurrentWithStoreTopology -race
```

### 2. What did you expect to see? (Required)

Test pass.

### 3. What did you see instead (Required)

```
WARNING: DATA RACE
Write at 0x00c00a78ece8 by goroutine 1975:
  github.com/pingcap/tidb/pkg/domain/infosync.UpdateServerLabel()
      github.com/pingcap/tidb/pkg/domain/infosync/info.go:443 +0x33b
  github.com/pingcap/tidb/pkg/server/handler/tikvhandler.LabelHandler.ServeHTTP()
      github.com/pingcap/tidb/pkg/server/handler/tikvhandler/tikv_handler.go:2011 +0x55a
  github.com/pingcap/tidb/pkg/server/handler/tikvhandler.(*LabelHandler).ServeHTTP()
      <autogenerated>:1 +0x58
  github.com/gorilla/mux.(*Router).ServeHTTP()
      github.com/gorilla/mux@v1.8.1/mux.go:212 +0x371
  net/http.(*ServeMux).ServeHTTP()
      net/http/server.go:2747 +0x255
  github.com/pingcap/tidb/pkg/server/internal/util.CorsHandler.ServeHTTP()
      github.com/pingcap/tidb/pkg/server/internal/util/util.go:219 +0x29e
  github.com/pingcap/tidb/pkg/server/internal/util.(*CorsHandler).ServeHTTP()
      <autogenerated>:1 +0x74
  net/http.serverHandler.ServeHTTP()
      net/http/server.go:3210 +0x2a1
  net/http.(*conn).serve()
      net/http/server.go:2092 +0x12a4
  net/http.(*Server).Serve.gowrap3()
      net/http/server.go:3360 +0x4f

Previous read at 0x00c00a78ece8 by goroutine 1928:
  reflect.typedmemmove()
      runtime/mbarrier.go:225 +0x0
  reflect.copyVal()
      reflect/value.go:2048 +0x5b
  reflect.(*MapIter).Value()
      reflect/value.go:1945 +0x124
  encoding/json.mapEncoder.encode()
      encoding/json/encode.go:760 +0x61a
  encoding/json.mapEncoder.encode-fm()
      <autogenerated>:1 +0x84
  encoding/json.structEncoder.encode()
      encoding/json/encode.go:715 +0x2bd
  encoding/json.structEncoder.encode-fm()
      <autogenerated>:1 +0xe4
  encoding/json.(*encodeState).reflectValue()
      encoding/json/encode.go:322 +0x83
  encoding/json.(*encodeState).marshal()
      encoding/json/encode.go:298 +0xea
  encoding/json.Marshal()
      encoding/json/encode.go:164 +0x12b
  github.com/pingcap/tidb/pkg/domain/infosync.(*InfoSyncer).StoreTopologyInfo()
      github.com/pingcap/tidb/pkg/domain/infosync/info.go:724 +0xf5
  github.com/pingcap/tidb/pkg/server/handler/tests.TestSetLabelsConcurrentWithStoreTopology.func2()
      github.com/pingcap/tidb/pkg/server/handler/tests/http_handler_test.go:1564 +0x84
  github.com/pingcap/tidb/pkg/server/handler/tests.TestSetLabelsConcurrentWithStoreTopology.func3()
      github.com/pingcap/tidb/pkg/server/handler/tests/http_handler_test.go:1574 +0x35
```

### 4. What is your TiDB version? (Required)

nightly

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: close #58405

Problem Summary:

The labels of TiDB are stored within a static structure, meanwhile TiDB have update-label API. Before this PR, the way TiDB handles the mutations of labels have data-race risk.

### What changed and how does it work?

Refactor the `ServerInfo` into static and dynamic sections and fix the data race by atomic operations.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/domain/infosync/info.go [hunk 1]
```diff
@@ -129,23 +130,18 @@ type InfoSyncer struct {
...
-	Port           uint              `json:"listening_port"`
-	StatusPort     uint              `json:"status_port"`
-	Lease          string            `json:"lease"`
-	StartTimestamp int64             `json:"start_timestamp"`
-	Labels         map[string]string `json:"labels"`
-	// ServerID is a function, to always retrieve latest serverID from `Domain`,
-	// which will be changed on occasions such as connection to PD is restored after broken.
-	ServerIDGetter func() uint64 `json:"-"`
+	StaticServerInfo
+	DynamicServerInfo
```
Comment (lcwangchao) [inline pkg/domain/infosync/info.go:136]: Seems DynamicServerInfo is also static because its value never changes for `ServerInfo`?

File: pkg/domain/infosync/info.go [hunk 2]
```diff
@@ -1036,15 +1077,23 @@ func getInfo(ctx context.Context, etcdCli *clientv3.Client, key string, retryCnt
...
+			ID:             id,
+			IP:             cfg.AdvertiseAddress,
+			Port:           cfg.Port,
+			StatusPort:     cfg.Status.StatusPort,
+			Lease:          cfg.Lease,
+			StartTimestamp: time.Now().Unix(),
+			ServerIDGetter: serverIDGetter,
+		},
+		DynamicServerInfo: DynamicServerInfo{
+			Labels: labels,
```
Comment (lcwangchao) [inline pkg/domain/infosync/info.go:1095]: seems to use `maps.Clone` is more elegant here?

File: pkg/domain/infosync/info.go (hunk 1 above)
Comment (you06) [reply pkg/domain/infosync/info.go:136]: It's updated in [`setDynamicServerInfo`](https://github.com/pingcap/tidb/blob/fbaad4bea8d4ebcf6733b4d46d3e9d6fe4445411/pkg/domain/infosync/info.go#L1557-L1565), which replaces `InfoSyncer.info` with a new `ServerInfo`.

**Review by lcwangchao — APPROVED** [review]

**Comment by you06** [comment]
@lance6716, @time-and-fate
This PR has a refactor of server info, and change the tests in some modules, need your approve so, PTAL

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

File: pkg/domain/infosync/info.go (hunk 1 above)
Comment (lance6716) [reply pkg/domain/infosync/info.go:140]: Do you think it's better to move `StaticServerInfo` out of `atomic.Pointer[ServerInfo]`? We can let `info` become a `struct { staticServerInfo, atomic.Pointer[dynamicServerInfo] } `

Comment (you06) [reply pkg/domain/infosync/info.go:140]: The current implementation provides a simpler interface for user, just call `getLocalServerInfo` to get the entire `ServerInfo` object.

**Review by lance6716 — APPROVED** [review]
