### PR TITLE
executor: fix escape for select into outfile

### LINKED ISSUE #19517: SELECT INTO does not quote correctly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `tx` (
  `a` varbinary(20) DEFAULT NULL,
  `b` int DEFAULT NULL
);

insert into tx values ('d","e",', 3);

select * from tx into outfile '.....' FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
```

### 2. What did you expect to see? (Required)

MySQL result:

```sql
"d\",\"e\",","3"
```

### 3. What did you see instead (Required)

TiDB result:

```sql
"d","e",","3"
```

### 4. What is your TiDB version? (Required)

v4.0.4

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #19517  

Problem Summary:

SelectInto executor does not handle escape.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Added the handling, and also some more test cases.

How it Works:

Scan the field, and add escape.

### Related changes

- Need to cherry-pick to the release 4.0

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- N/A

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by breeswish** [comment]
What about other special characters like \r\n?

**Comment by ichn-hu** [comment]
> What about other special characters like \r\n?

What do you mean? If they are used as line terminator, then it will be appended, if they appeared in a string, they will probably be enclosed (otherwise, we can't do anything).

Tested in MySQL:

```
mysql> insert into tx values ('\r\n', 123);
mysql> select * from tx into outfile '/tmp/test-r-n.txt' fields enclosed by '' lines terminated by '\r\n';

ichn-arch-pc# cat test-r-n.txt 
a       1
\N      \N
\
        123
ichn-arch-pc# hexdump -c test-r-n.txt 
0000000   a  \t   1  \r  \n   \   N  \t   \   N  \r  \n   \  \r  \n  \t
0000010   1   2   3  \r  \n                                            
0000015
ichn-arch-pc# cat test-r-n-enclosed.txt 
"a"     "1"
\N      \N
"\
"       "123"
ichn-arch-pc# hexdump -c test-r-n-enclosed.txt
0000000   "   a   "  \t   "   1   "  \r  \n   \   N  \t   \   N  \r  \n
0000010   "   \  \r  \n   "  \t   "   1   2   3   "  \r  \n            
000001d
```

TiDB:

```
mysql root@localhost:test> create table tx (a varchar(30), b int);
mysql root@localhost:test> insert into tx values ('\r\n', 123);
mysql root@localhost:test> select * from tx into outfile 'tidb-r-n.txt' fields enclosed by '"' lines terminated by '\r\n';
mysql root@localhost:test> select * from tx into outfile 'tidb-r-n.txt' fields enclosed by '' lines terminated by '\r\n';
mysql root@localhost:test> select * from tx into outfile 'tidb-r-n-enclosed.txt' fields enclosed by '"' lines terminated by '\r\n';


╭─ichn@ichn-arch-pc ~/go/src/github.com/pingcap/tidb ‹fix-select-into*› 
╰─$ cat tidb-r-n.txt

        123
╭─ichn@ichn-arch-pc ~/go/src/github.com/pingcap/tidb ‹fix-select-into*› 
╰─$ hexdump -c tidb-r-n.txt
0000000  \r  \n  \t   1   2   3  \r  \n                                
0000008
╭─ichn@ichn-arch-pc ~/go/src/github.com/pingcap/tidb ‹fix-select-into*› 
╰─$ cat tidb-r-n-enclosed.txt 
"
"       "123"
╭─ichn@ichn-arch-pc ~/go/src/github.com/pingcap/tidb ‹fix-select-into*› 
╰─$ hexdump -c tidb-r-n-enclosed.txt 
0000000   "  \r  \n   "  \t   "   1   2   3   "  \r  \n                
000000c

```

**Comment by breeswish** [comment]
@ichn-hu Thank you for pointing out! Could you further verify that the results of the following statements are identical?

```sql
CREATE TABLE `tx` (
  `a` varbinary(20) DEFAULT NULL
);

insert into tx values ('d","e",');
insert into tx values (unhex("00"));
insert into tx values ("\r\n\b\Z\t");
insert into tx values (null);

select * from tx into outfile '~/1.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
```

File: executor/select_into.go [hunk 1]
```diff
@@ -82,6 +87,34 @@ func (s *SelectIntoExec) considerEncloseOpt(et types.EvalType) bool {
 		et == types.ETJson
 }
 
+func (s *SelectIntoExec) escapeField(f []byte) []byte {
+	if s.intoOpt.FieldsInfo.Escaped == 0 {
+		return f
+	}
+	s.escapeBuf = s.escapeBuf[:0]
+	escape := func() {
```
Comment (lzmhhh123) [inline executor/select_into.go:95]: Pls remove the single statement function.

**Review by lzmhhh123 — COMMENTED** [review]
Rest LGTM.

File: executor/select_into.go (hunk 1 above)
Comment (ichn-hu) [reply executor/select_into.go]: addressed

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
