### PR TITLE
dxf: include context info in the stored error

### LINKED ISSUE #60433: dxf: outer error context is removed when store to system table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

see below, only the original error is stored, we lose the error context
https://github.com/pingcap/tidb/blob/1cd39430e107d8e2da23f640b0744b170d2b2f5f/pkg/disttask/framework/storage/task_table.go#L847-L860

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #60433

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

before
```
mysql> import into t from '/Users/jujiajia/playground/lightning/single-file/test.t.1.csv';
ERROR 1292 (22007): Truncated incorrect DOUBLE value: 'a'
```

after
```
mysql> import into t from '/Users/jujiajia/playground/lightning/single-file/test.t.1.csv';
ERROR 1105 (HY000): encode kv error in file test.t.1.csv:0 at offset 273200: Truncated incorrect DOUBLE value: 'a'
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/importer/import.go [hunk 1]
```diff
@@ -1431,24 +1431,6 @@ type JobImportResult struct {
 	Warnings []contextutil.SQLWarn
 }
 
-// GetMsgFromBRError get msg from BR error.
-// TODO: add GetMsg() to errors package to replace this function.
-// see TestGetMsgFromBRError for more details.
```
Comment (lance6716) [inline pkg/executor/importer/import.go:1436]: (in my memory) I wrote `TestGetMsgFromBRError` to ensure the message prefix is stripped. Now we have `GetErrStackMsg`, we can delete that unit test

**Review by lance6716 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
