### PR TITLE
import into: exit ImportMode after import step

### LINKED ISSUE #44755: "import into" sql fail with "Coprocessor task terminated due to exceeding the deadline"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> IMPORT INTO H.t_o_shard FROM "s3://nfs/tools_test_data/t_o_shard_clustered/*.csv?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9001&force-path-style=true" with skip_rows=1;
ERROR 1105 (HY000): other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other e
mysql>
```
### 2. What did you expect to see? (Required)
sql execute successfully
### 3. What did you see instead (Required)
sql execute failed
```
2023-06-16 19:36:00 (UTC+08:00)TiDB upstream-tidb-4.upstream-tidb-peer.import-into-20t-tps-1807811-1-608.svc:4000[scheduler.go:344] ["scheduler error"] [scheduler="id: upstream-tidb-4.upstream-tidb-peer.import-into-20t-tps-1807811-1-608.svc:4000, task_id: 150005"] [error="other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline"]
2023-06-16 19:36:00 (UTC+08:00)TiDB upstream-tidb-4.upstream-tidb-peer.import-into-20t-tps-1807811-1-608.svc:4000[manager.go:299] ["failed to handle task"] [dist_task_manager=upstream-tidb-4.upstream-tidb-peer.import-into-20t-tps-1807811-1-608.svc:4000] [error="other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline"]
2023-06-16 19:36:01 (UTC+08:00)TiDB upstream-tidb-2.upstream-tidb-peer.import-into-20t-tps-1807811-1-608.svc:4000[handle.go:88] ["global task reverted"] [taskID=150005] [error="other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline; other error: Coprocessor task terminated due to exceeding the deadline"]
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #44755

Problem Summary:

### What is changed and how it works?
- exit importMode after import step, coprocessor is extremely slow if in importMode
- change default `regionSplitSize` to 192MiB which is the value we set when importing 50T data.
- change the value of `regionSplitSize` to be the same as lightning when doing `unsafeImport`

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/realtikvtest/importintotest/import_into_test.go [hunk 1]
```diff
@@ -889,25 +891,32 @@ func (s *mockGCSSuite) TestImportMode() {
 	s.Greater(intoNormalTime, intoImportTime)
 	s.checkTaskMetaRedacted(int64(jobID))
 
+	// after import step, we should not enter normal mode, i.e. we only call ToImportMode once
```
Comment (D3Hunter) [inline tests/realtikvtest/importintotest/import_into_test.go:894]:
```suggestion
	// after import step, we should enter normal mode, i.e. we only call ToImportMode once
```

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by niubell — APPROVED** [review]
