### PR TITLE
ddl, planner: support `ALTER TABLE` without use db

### LINKED ISSUE #18756: different behavior on foreign key with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

in MySQL  5.7.21

```sql
> create database db;
Query OK, 1 row affected

> create table db.t1 (c1 int primary key, c2 int);
Query OK, 0 rows affected

> create table db.t2 (c1 int primary key, c2 int);
Query OK, 0 rows affected

> alter table db.t1 add constraint fk foreign key (c2) references t2(c1);
Query OK, 0 rows affected

> show create table db.t1\G
***************************[ 1. row ]***************************
Table        | t1
Create Table | CREATE TABLE `t1` (
  `c1` int(11) NOT NULL,
  `c2` int(11) DEFAULT NULL,
  PRIMARY KEY (`c1`),
  KEY `fk` (`c2`),
  CONSTRAINT `fk` FOREIGN KEY (`c2`) REFERENCES `t2` (`c1`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

in TiDB v4.0.0 (also for master branch with git commit https://github.com/pingcap/tidb/commit/9995ad7451540461357551192399d25b9a69044c)

```sql
> create database db;
Query OK, 1 row affected

> create table db.t1 (c1 int primary key, c2 int);
Query OK, 0 rows affected

> create table db.t2 (c1 int primary key, c2 int);
Query OK, 0 rows affected

> alter table db.t1 add constraint fk foreign key (c2) references t2(c1);
(1046, 'No database selected')
```

### 2. What did you expect to see? (Required)

no error reported.

### 3. What did you see instead (Required)

`(1046, 'No database selected')`

### 4. Affected version (Required)

v4.0.0 (other versions are not tested)

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #18756 

Problem Summary: `alter table db.t1 add constraint fk foreign key (c2) references t2(c1)` without first executing `use db`,  TiDB will report `No database selected`. That is because `c2` has no schema(dbName), nor do we have a global `CurrentDB`. But mysql will try to use dbName from `db.t1`. Manually tested.

### Check List

Tests

- Unit test
- Integration test

### Release note

- allow `alter table db.t1 add constraint fk foreign key (c2) references t2(c1)` like statements without first executing `use db`

### CODE REVIEW

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -112,6 +112,8 @@ type preprocessor struct {
 	ctx  sessionctx.Context
 	err  error
 	flag preprocessorFlag
+	// a temporary schema for AlterTableStmt tablename resolving
+	tmpTs string
```
Comment (djshow832) [inline planner/core/preprocess.go:116]: What does 'Ts' mean? table schema?

File: planner/core/preprocess.go [hunk 2]
```diff
@@ -872,12 +874,14 @@ func (p *preprocessor) checkContainDotColumn(stmt *ast.CreateTableStmt) {
 
 func (p *preprocessor) handleTableName(tn *ast.TableName) {
 	if tn.Schema.L == "" {
-		currentDB := p.ctx.GetSessionVars().CurrentDB
-		if currentDB == "" {
+		if currentDB := p.ctx.GetSessionVars().CurrentDB; currentDB != "" {
+			tn.Schema = model.NewCIStr(currentDB)
+		} else if p.tmpTs != "" {
+			tn.Schema = model.NewCIStr(p.tmpTs)
+		} else {
```
Comment (djshow832) [inline planner/core/preprocess.go:881]: It doesn't check whether it's the renamed table name. It will affect all the ALTER TABLE statements. Does they all conform to this rule?

File: planner/core/preprocess.go (hunk 1 above)
Comment (xhebox) [reply planner/core/preprocess.go:116]: Yes.

File: planner/core/preprocess.go (hunk 2 above)
Comment (xhebox) [reply planner/core/preprocess.go:881]: I have verified the case of rename, and the case in the original issue. I do not know other cases.

I just checked the source code of mysql, it is of great possibility. The related code is [here](https://github.com/mysql/mysql-server/blob/f8cdce86448a211511e8a039c62580ae16cb96f5/sql/sql_db.cc), specifically the function `mysql_opt_change_db`.

Comment (xhebox) [reply planner/core/preprocess.go:881]: @djshow832 Confirmed. It is at this line https://github.com/mysql/mysql-server/blob/7d10c82196c8e45554f27c00681474a9fb86d137/sql/sql_alter.cc#L142. So it conforms to all rules.

**Comment by xhebox** [comment]
I do not remember that. I now retest it with `mysql 8.0.20`. And I can not reproduce that again. Maybe there is a mistake :(.

Foreign key works, rename/exchange partition do not work. For now, I modified it to only take effects on foreign key references.

**Review by AilinKid — COMMENTED** [review]
LGTM

File: planner/core/preprocess.go [hunk 3]
```diff
@@ -1000,6 +1000,13 @@ func (p *preprocessor) resolveAlterTableStmt(node *ast.AlterTableStmt) {
 		if spec.Tp == ast.AlterTableRenameTable {
 			p.flag |= inCreateOrDropTable
 			break
+		} else if spec.Tp == ast.AlterTableAddConstraint {
```
Comment (zimulala) [inline planner/core/preprocess.go:1003]:
```suggestion
		} else if spec.Tp == ast.AlterTableAddConstraint && spec.Constraint.Refer != nil {
```

File: planner/core/preprocess.go [hunk 4]
```diff
@@ -1000,6 +1000,13 @@ func (p *preprocessor) resolveAlterTableStmt(node *ast.AlterTableStmt) {
 		if spec.Tp == ast.AlterTableRenameTable {
 			p.flag |= inCreateOrDropTable
 			break
+		if spec.Tp == ast.AlterTableAddConstraint && spec.Constraint.Refer != nil {
+			if spec.Constraint.Refer != nil {
```
Comment (zimulala) [inline planner/core/preprocess.go:1004]: Please remove this duplicated condition.

File: planner/core/preprocess.go [hunk 5]
```diff
@@ -1000,6 +1000,13 @@ func (p *preprocessor) resolveAlterTableStmt(node *ast.AlterTableStmt) {
 		if spec.Tp == ast.AlterTableRenameTable {
 			p.flag |= inCreateOrDropTable
 			break
```
Comment (zimulala) [inline planner/core/preprocess.go:1002]: Please add `}`.

**Comment by xhebox** [comment]
@ti-srebot /run-unit-test

**Review by djshow832 — COMMENTED** [review]
It seems the code has nothing to do with `rename to` as the the description says.

**Comment by xhebox** [comment]
The description is updated.

File: planner/core/preprocess_test.go [hunk 6]
```diff
@@ -228,11 +231,14 @@ func (s *testValidatorSuite) TestValidator(c *C) {
...
-	c.Assert(err, IsNil)
 	ctx := se.(sessionctx.Context)
 	is := infoschema.MockInfoSchema([]*model.TableInfo{core.MockSignedTable()})
-	for _, tt := range tests {
+	for k, tt := range tests {
+		// the first test should be executed without selecting a database
+		if k == 1 {
+			_, err = se.Execute(context.Background(), "use test")
+			c.Assert(err, IsNil)
+		}
```
Comment (djshow832) [inline planner/core/preprocess_test.go:241]: I prefer to move the new test to a separate test case, instead of hacking it here.
Besides, 3 cases need to be tested:
1. Add constraint after `use`.
2. Add constraint without `use`.
3. Add constraint with a specified schema before the table name.

Comment (xhebox) [reply planner/core/preprocess_test.go]: It is separated. Is there any problem with the new tests?

File: planner/core/preprocess_test.go [hunk 7]
```diff
@@ -220,28 +258,23 @@ func (s *testValidatorSuite) TestValidator(c *C) {
...
+	defer testleak.AfterTest(c)()
+
+	s.runSQL(c, "ALTER TABLE test.t ADD CONSTRAINT fk FOREIGN KEY (c2) REFERENCES t (c1)", false, nil)
+
+	_, err := s.se.Execute(context.Background(), "use test")
+	c.Assert(err, IsNil)
+
+	s.runSQL(c, "ALTER TABLE test.t ADD CONSTRAINT fk FOREIGN KEY (c3) REFERENCES t (c1)", false, nil)
+
+	s.runSQL(c, "ALTER TABLE test.t ADD CONSTRAINT fk FOREIGN KEY t3(c3) REFERENCES t (c1)", false, nil)
```
Comment (djshow832) [inline planner/core/preprocess_test.go:279]: I mean, `REFERENCES test2.t(c1)`, where `test2` is another schema.

Comment (xhebox) [reply planner/core/preprocess_test.go:279]: Oh, that is a mistake.

Comment (djshow832) [reply planner/core/preprocess_test.go]: Are you sure `test2.t` exists?

Comment (xhebox) [reply planner/core/preprocess_test.go]: It seems that the underlying store is read only. Since the code here is not actually executed, but only parsed/resolved. I think it is ok to just use `test.t`.

Comment (djshow832) [reply planner/core/preprocess_test.go]: So you can't judge from the test case that whether `test` is read from `ALTER TABLE test.t` or `REFERENCES test.t(c1)`.

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by xhebox** [comment]
**Wait A Sec Before Merging**. I am still working on addressing the comment.

**Comment by zz-jason** [comment]
@xhebox it's better to backport this PR to release branches.

**Comment by tangenta** [comment]
> **Wait A Sec Before Merging**. I am still working on addressing the comment.

Ok. You can prepend a `[DNM]` message to the title. 

BTW, it is better to add some high-level integration tests.

**Comment by xhebox** [comment]
@zz-jason Sounds good. I will do it later sometime.

**Comment by djshow832** [comment]
> @zz-jason Sounds good. I will do it later sometime.

You can do it simply by adding a `needs-cherry-pick-4.0` or `needs-cherry-pick-3.0` label. The robot will cherry-pick and commit a PR.

**Comment by xhebox** [comment]
> You can do it simply by adding a label
I thought that I do not have the permission to add a label?

**Comment by xhebox** [comment]
@tangenta I think that should be tested in DDL package.

Here, this PR is just a change in preprocess. The tests here are enough.

**Review by djshow832 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
