### PR TITLE
ddl: check too long ident for partition

### LINKED ISSUE #17235: too long partition name should raise an error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
mysql root@127.0.0.1:partition_table> create table t1(a int) partition by range (a) (partition p0pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp values less than (10));
Query OK, 0 rows affected
Time: 0.009s
mysql root@127.0.0.1:partition_table> show create table t1;
+-------+--------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                           |
+-------+--------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (                                                                                    |
|       |   `a` int(11) DEFAULT NULL                                                                             |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin                                            |
|       | PARTITION BY RANGE ( `a` ) (                                                                           |
|       |   PARTITION `p0pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp` VALUES LESS THAN (10) |
|       | )                                                                                                      |
```

### 2. What did you expect to see? (Required)
``` sql
mysql root@172.16.4.131:partition_table> create table t1(a int) partition by range (a) (partition p0pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp values less than (10));
(1059, "Identifier name 'p0pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp' is too long")
```

### 4. Root Cause Analysis
We do not check the name length when creating table and altering table.

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close #17235 

Problem Summary:

### What is changed and how it works?
Check the name length of partition when create table and alter table

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 
- Raise an error if the length of the partition name exceeds 64.

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -1350,6 +1350,7 @@ func checkTableInfoValidWithStmt(ctx sessionctx.Context, tbInfo *model.TableInfo
 		return errors.Trace(err)
 	}
 	if s.Partition != nil {
+		//err := chec
```
Comment (tiancaiamao) [inline ddl/ddl_api.go:1353]: remove it

**Comment by tiancaiamao** [comment]
LGTM
/merge
