### PR TITLE
executor: force pushdown aggregate to TiKV inside `admin check table` 

### LINKED ISSUE #63492: Hash aggregation may not be pushed down to TiKV during `ADMIN CHECK TABLE`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Hard to reproduce, but it may happen. We need to prevent it.

### 2. What did you expect to see? (Required)
Hash aggregation is always pushed down to TiKV during `ADMIN CHECK TABLE`
### 3. What did you see instead (Required)
Hash aggregation may not be pushed down to TiKV during `ADMIN CHECK TABLE`
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #63492 ref #63870

Problem Summary:
The aggregate may not push down to TiKV
### What changed and how does it work?
Force pushdown aggregate to TiKV
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
force pushdown aggregate to TiKV inside admin check table
```

### CODE REVIEW

File: pkg/executor/check_table_index.go [hunk 1]
```diff
@@ -339,6 +340,45 @@ func (w *checkIndexWorker) initSessCtx(se sessionctx.Context) (restore func()) {
...
+func queryToRow(ctx context.Context, se sessionctx.Context, sql string) ([]chunk.Row, error) {
+	rs, err := se.GetSQLExecutor().ExecuteInternal(ctx, sql)
+	if err != nil {
+		return nil, err
+	}
+	row, err := sqlexec.DrainRecordSet(ctx, rs, 4096)
+	if err != nil {
+		return nil, err
+	}
+	err = rs.Close()
```
Comment (lance6716) [inline pkg/executor/check_table_index.go]: can use `DrainRecordSetAndClose` now

File: pkg/executor/check_table_index.go [hunk 2]
```diff
@@ -508,37 +549,21 @@ func (w *checkIndexWorker) HandleTask(task checkIndexTask, _ func(workerpool.Non
...
-			"select %s, %s, %s from %s use index(`%s`) where %s = 0 order by %s",
+			"select /*+ AGG_TO_COP() */ %s, %s, %s from %s use index(`%s`) where %s = 0 order by %s",
 			handleColumns, indexColumns, md5HandleAndIndexCol, tblName, idxInfo.Name, groupByKey, handleColumns)
 		tableSQL := fmt.Sprintf(
-			"select /*+ read_from_storage(tikv[%s]) */ %s, %s, %s from %s use index() where %s = 0 order by %s",
+			"select /*+ read_from_storage(tikv[%s]), AGG_TO_COP() */ %s, %s, %s from %s use index() where %s = 0 order by %s",
 			tblName, handleColumns, indexColumns, md5HandleAndIndexCol, tblName, groupByKey, handleColumns)
-
-		idxRow, err := queryToRow(se, indexSQL)
+		intest.Assert(verifyIndexSideQuery(ctx, se, indexSQL), "index side query plan is not correct: %s", indexSQL)
```
Comment (lance6716) [inline pkg/executor/check_table_index.go]: I think `AssertFunc` is better than `Assert`. `Assert` will always evaluate `verifyIndexSideQuery(ctx, se, indexSQL)` then check the boolean result even if `intest` tag is not set.

File: pkg/executor/check_table_index.go [hunk 3]
```diff
@@ -455,6 +495,7 @@ func (w *checkIndexWorker) HandleTask(task checkIndexTask, _ func(workerpool.Non
 		})
 
 		// compute index side checksum.
+		intest.Assert(verifyIndexSideQuery(ctx, se, idxQuery), "index side query plan is not correct: %s", idxQuery)
```
Comment (lance6716) [inline pkg/executor/check_table_index.go]: ditto

**Review by lance6716 — COMMENTED** [review]
rest lgtm
