### PR TITLE
sem: add `tidb_service_scope` to SEM hidden variable list

### LINKED ISSUE #62583: `tidb_service_scope` is not hidden by SEM, but it also cannot be set.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Enable SEM.
2. `set global tidb_service_scope = 'background'`
3. `select @@tidb_service_scope`.

### 2. What did you expect to see? (Required)

The SEM blocked the query, and the variable is not changed.

### 3. What did you see instead (Required)

1. **The variable has been changed**.
2. `set` returns an error because the internal SQL is blocked by SEM.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #62583

Problem Summary:

The variable `tidb_service_scope` is not controlled by SEM.

### What changed and how does it work?

Add `tidb_service_scope` to the list of SEM.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

```
mysql> set global tidb_service_scope = 'background';
ERROR 1227 (42000): Access denied; you need (at least one of) the RESTRICTED_VARIABLES_ADMIN privilege(s) for this operation
mysql> select @@tidb_service_scope;
ERROR 1227 (42000): Access denied; you need (at least one of) the RESTRICTED_VARIABLES_ADMIN privilege(s) for this operation
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

File: pkg/util/sem/sem_test.go [hunk 1]
```diff
@@ -103,6 +103,6 @@ func TestIsInvisibleSysVar(t *testing.T) {
 	assert.True(IsInvisibleSysVar(vardef.TiDBRowFormatVersion))
 	assert.True(IsInvisibleSysVar(vardef.TiDBRedactLog))
 	assert.True(IsInvisibleSysVar(vardef.TiDBTopSQLMaxTimeSeriesCount))
-	assert.True(IsInvisibleSysVar(vardef.TiDBTopSQLMaxTimeSeriesCount))
```
Comment (D3Hunter) [inline pkg/util/sem/sem_test.go:106]: why remove this one?

Comment (YangKeao) [reply pkg/util/sem/sem_test.go:106]: Because it's duplicated.  This line is same with the previous line.

**Review by xhebox — APPROVED** [review]
