### PR TITLE
executor: fix drop role not work as expected in the show result. 

### LINKED ISSUE #29655: `DROP ROLE` not work as expected in the `SHOW` result.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
CREATE ROLE `engineering`@`US`;
CREATE ROLE `engineering`@`INDIA`;
DROP ROLE engineering@INDIA;
DROP ROLE engineering@US;
SELECT user,host FROM mysql.user;

...

tidb> CREATE ROLE `engineering`@`US`;
Query OK, 0 rows affected (0.01 sec)

tidb> CREATE ROLE `engineering`@`INDIA`;
Query OK, 0 rows affected (0.00 sec)

tidb> DROP ROLE engineering@INDIA;
Query OK, 0 rows affected (0.01 sec)

tidb> DROP ROLE engineering@US;
Query OK, 0 rows affected (0.00 sec)

tidb> select user,host from mysql.user;
```

### 2. What did you expect to see? (Required)
```
+-------------+-------+
| user        | host  |
+-------------+-------+
| root        | %     |
+-------------+-------+
3 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
+-------------+-------+
| user        | host  |
+-------------+-------+
| root        | %     |
| engineering | india |
| engineering | us    |
+-------------+-------+
3 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
master&5.3

### PR DESCRIPTION
**Pull request by 7yyo**
### What problem does this PR solve?

Issue Number: close #29655

Problem Summary:

fix drop role not work as expected in the show result. 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix drop role not work as expected in the show result.
```

### CODE REVIEW

**Comment by 7yyo** [comment]
PTAL @winoros @morgo @jackysp

File: executor/simple.go [hunk 1]
```diff
@@ -1225,7 +1225,7 @@ func (e *SimpleExec) executeDropUser(ctx context.Context, s *ast.DropUserStmt) e
 
 		// begin a transaction to delete a user.
 		sql.Reset()
-		sqlexec.MustFormatSQL(sql, `DELETE FROM %n.%n WHERE Host = %? and User = %?;`, mysql.SystemDB, mysql.UserTable, user.Hostname, user.Username)
+		sqlexec.MustFormatSQL(sql, `DELETE FROM %n.%n WHERE Host = %? and User = %?;`, mysql.SystemDB, mysql.UserTable, strings.ToLower(user.Hostname), user.Username)
```
Comment (tangenta) [inline executor/simple.go:1228]: It is easy to introduce another bug if the caller of `MustFormatSQL` forgets to `Lower()` the argument.

Could you relax the case-sensitive assumption?

**Review by tangenta — APPROVED** [review]

File: executor/simple.go (hunk 1 above)
Comment (mjonss) [inline executor/simple.go:1228]: I think there might be another case in line 680:
```golang
sqlexec.MustFormatSQL(sql, `DELETE IGNORE FROM %n.%n WHERE FROM_HOST=%? and FROM_USER=%? and TO_HOST=%? and TO_USER=%?`, mysql.SystemDB, mysql.RoleEdgeTable, role.Hostname, role.Username, user.Hostname, user.Username)
```

**Review by mjonss — APPROVED** [review]
LGTM but could you also check if there are more bugs like this?

File: executor/simple.go (hunk 1 above)
Comment (7yyo) [reply executor/simple.go:1228]: I'm not sure if it needs to be modified. Because this is not the `mysql.user table`, currently, `create user` will lowercase `hostname`, so I think all SQL involving `mysql.user` `hostname` should be changed to lowercase. I'm not sure about the other tables.

I added some other modifications, please help double confirm whether it is correct, thank you.

@mjonss
