### PR TITLE
ddl: fix resuming to wrong checkpoint when failed during adding index

### LINKED ISSUE #55488: admin check failed with “Error 8223 (HY000): data inconsistency in table” after kill pd leader during adding index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、tidb_enable_dist_task='off'
2、run sysbench
3、add index for one of table
4、kill pd leader during adding index
5、admin check index when adding index finish

operatorLogs:
[2024-08-18 19:11:46] ###### start adding index
ALTER TABLE `sbtest1` ADD INDEX `index_test_1723979506277`(`c`)
[2024-08-18 19:11:46] ###### wait for ddl job finish
[2024-08-18 19:16:46] ###### ddl job finished
select job_id, db_name, table_name, job_type, create_time, start_time, end_time, state, query from information_schema.ddl_jobs where query = 'ALTER TABLE `sbtest1` ADD INDEX `index_test_1723979506277`(`c`)'
jobId: 381, job type: add index /* ingest */, state: synced
add index done, it takes: 5m0.343907361s
[2024-08-18 19:16:46] ###### start admin check
admin check index sbtest1 index_test_1723979506277

### 2. What did you expect to see? (Required)
admin check success

### 3. What did you see instead (Required)
data inconsistency after kill pd leader during adding index

admin check failed
Error 8223 (HY000): data inconsistency in table: sbtest1, index: index_test_1723979506277, handle: 53654296, index-values:"" != record-values:"handle: 53654296, values: [KindString 29259679273-41443820494-67699624372-21652956621-69679967231-62641758853-72167802605-31092810200-79525733868-93118816928]"

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.3.0
Edition: Community
Git Commit Hash: 6eba67e8a8dbc1ea9e02cc62dc0d22381364539e
Git Branch: HEAD
UTC Build Time: 2024-08-16 10:02:25
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-08-18T19:11:36.561+0800

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #55488

Problem Summary:

See https://github.com/pingcap/tidb/issues/55488#issuecomment-2296771408.

The end key in checkpoint should be "next unprocessed key" instead of "last processed key".

### What changed and how does it work?

- Remove `.Next()` for checkpoint end key when resuming.
- Add an integration test.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/ddl/backfilling.go [hunk 1]
```diff
@@ -636,12 +647,7 @@ func makeupDecodeColMap(dbName model.CIStr, t table.Table) (map[int64]decoder.Co
 	return decodeColMap, nil
 }
 
-var backfillTaskChanSize = 128
-
-// SetBackfillTaskChanSizeForTest is only used for test.
```
Comment (Benjamin2037) [inline pkg/ddl/backfilling.go:641]: Will this remove operation cause test case execution slower？

File: pkg/ddl/ingest/checkpoint.go [hunk 2]
```diff
@@ -156,9 +156,9 @@ func (s *CheckpointManager) IsKeyProcessed(end kv.Key) bool {
 	return s.localDataIsValid && len(s.flushedKeyLowWatermark) > 0 && end.Cmp(s.flushedKeyLowWatermark) <= 0
 }
 
-// LastProcessedKey finds the last processed key in checkpoint.
-// If there is no processed key, it returns nil.
-func (s *CheckpointManager) LastProcessedKey() kv.Key {
+// NextKeyToProcess finds the next unprocessed key in checkpoint.
+// If there is no such key, it returns nil.
+func (s *CheckpointManager) NextKeyToProcess() kv.Key {
```
Comment (Benjamin2037) [inline pkg/ddl/ingest/checkpoint.go:161]: Seems here only changed the name of function, why it can fix the problem?

File: pkg/ddl/backfilling_operators.go [hunk 3]
```diff
@@ -364,7 +364,7 @@ func (src *TableScanTaskSource) adjustStartKey(start, end kv.Key) (adjusted kv.K
 	if cpKey.Cmp(end) == 0 {
 		return cpKey, true
 	}
-	return cpKey.Next(), false
+	return cpKey, false
```
Comment (Benjamin2037) [inline pkg/ddl/backfilling_operators.go:367]: Here is the only difference, that cause problem, am I right?

Comment (tangenta) [reply pkg/ddl/backfilling_operators.go:367]: Yes, see https://github.com/pingcap/tidb/issues/55488#issuecomment-2296771408

File: pkg/ddl/ingest/checkpoint.go (hunk 2 above)
Comment (tangenta) [reply pkg/ddl/ingest/checkpoint.go:161]: Just made the function clearer

File: pkg/ddl/backfilling.go (hunk 1 above)
Comment (tangenta) [reply pkg/ddl/backfilling.go:641]: No, the imact is negligible.

**Review by lance6716 — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM
