### PR TITLE
fix: reflect.SliceHeader is deprecated: Use slice instead.

### LINKED ISSUE #62129: reflect.SliceHeader is deprecated: Use slice instead.
## Enhancement

fix: reflect.SliceHeader is deprecated: Use slice instead.

### PR DESCRIPTION
**Pull request by yihong0618**
follow #61952 another part

fix: reflect.SliceHeader is deprecated: Use unsafe.Slice or unsafe.SliceData instead.

Issue Number: close #62129

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/parser/charset/encoding_base.go [hunk 1]
```diff
@@ -123,12 +122,10 @@ func generateEncodingErr(name string, invalidBytes []byte) error {
 // HackSlice converts string to slice without copy.
 // Use at your own risk.
 func HackSlice(s string) (b []byte) {
```
Comment (lance6716) [inline pkg/parser/charset/encoding_base.go:124]: `nil` `[]byte` and zero length `[]byte` may have different behaviour at caller. Let's check CI

**Review by lance6716 — COMMENTED** [review]
/retest

File: pkg/parser/charset/encoding_base.go (hunk 1 above)
Comment (yihong0618) [reply pkg/parser/charset/encoding_base.go:124]: will dig it tomorrow~

**Review by lance6716 — APPROVED** [review]
please follow the bot's comment to update PR description. Correct description will not cause "do-not-merge/..." labels to be added.

**Comment by yihong0618** [comment]
> please follow the bot's comment to update PR description. Correct description will not cause "do-not-merge/..." labels to be added.

Done

**Comment by lance6716** [comment]
> [FORMAT CHECKER NOTIFICATION]
> 
> **Notice**: To remove the `do-not-merge/needs-linked-issue` label, please provide the linked issue number on one line in the PR body, for example: `Issue Number: close #123` or `Issue Number: ref #456`.
> 
> 📖 For more info, you can check the ["Contribute Code"](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue) section in the development guide.

Here's another requirement for PR description @yihong0618

**Review by hawkingrei — APPROVED** [review]
