### PR TITLE
planner: fix the issue where TiDB generates multiple plandigests for 'IN (...)'.

### LINKED ISSUE #33559: queries with the same plan have different plan_digest in information_schema.statement_summary
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (a int);
select * from t where a in (1, 2);
select * from t where a in (1, 2, 3);
use information_schema;

mysql> select plan_digest, digest_text, QUERY_SAMPLE_TEXT from STATEMENTS_SUMMARY where digest_text="select * from `t` where `a` in ( ... )";
+------------------------------------------------------------------+----------------------------------------+--------------------------------------+
| plan_digest                                                      | digest_text                            | QUERY_SAMPLE_TEXT                    |
+------------------------------------------------------------------+----------------------------------------+--------------------------------------+
| ddbf412c92228a757994b14210801d86f61eb9b510e6bc36dca75d5d4151ad02 | select * from `t` where `a` in ( ... ) | select * from t where a in (1, 2, 3) |
| 01308613e49648a4431351439f0596ce1236bc671f9ced66c04bc19b2b8b2c38 | select * from `t` where `a` in ( ... ) | select * from t where a in (1, 2)    |
+------------------------------------------------------------------+----------------------------------------+--------------------------------------+
2 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
These two queries above actually have the same plan, so they should have the same plan_digest as well.

### 3. What did you see instead (Required)
They have different plan_digests.

### 4. What is your TiDB version? (Required)

```
mysql> select version();
+-----------------------------------------------+
| version()                                     |
+-----------------------------------------------+
| 5.7.25-TiDB-v6.1.0-alpha-78-g8f8dfafc10-dirty |
+-----------------------------------------------+
1 row in set (0.00 sec)
```

### 5. Root Cause Analysis
It is caused by selection operators with different `in-list` lengths are normalized to different strings.
```
// ExplainNormalizedInfo implements Plan interface.
func (p *PhysicalSelection) ExplainNormalizedInfo() string {
	return string(expression.SortedExplainNormalizedExpressionList(p.Conditions))
}
```

### PR DESCRIPTION
**Pull request by King-Dylan**
### What problem does this PR solve?
Issue Number: close #33559 
Problem Summary:
queries with the same plan have different plan_digest in information_schema.statement_summary
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Supports generating the same plan digest for SQL IN operations with different numbers of arguments.
```

### CODE REVIEW

**Review by fixdb — COMMENTED** [review]
This patch only works for IN list where it is in predicate, but will it work for IN list in Projection? e.g.
```
select a in (1, 2, 3) from t;
```

**Review by fixdb — COMMENTED** [review]
Can we also add test case for projection?

**Comment by jackysp** [comment]
> [CLA assistant check](https://cla.pingcap.net/pingcap/tidb?pullRequest=47216) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.pingcap.net/pingcap/tidb?pullRequest=47216) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.pingcap.net/check/pingcap/tidb?pullRequest=47216) it.

Please sign it @King-Dylan

File: expression/explain.go [hunk 1]
```diff
@@ -170,6 +242,46 @@ func SortedExplainNormalizedExpressionList(exprs []Expression) []byte {
...
+func sortedExplainExpressionList4InList(exprs []Expression, normalized bool) []byte {
+	buffer := bytes.NewBufferString("")
+	exprInfos := make([]string, 0, len(exprs))
+	for _, expr := range exprs {
+		if _, ok := expr.(*ScalarFunction); ok {
+			if normalized {
+				exprInfos = append(exprInfos, expr.ExplainNormalizedInfo4InList())
+			} else {
+				exprInfos = append(exprInfos, expr.ExplainInfo4InList())
+			}
```
Comment (jackysp) [inline expression/explain.go:261]: Is it possible to embedded this part to `sortedExplainExpressionList` to avoid some duplicated code?

File: expression/explain.go [hunk 2]
```diff
@@ -170,6 +242,46 @@ func SortedExplainNormalizedExpressionList(exprs []Expression) []byte {
 	return sortedExplainExpressionList(exprs, true)
 }
 
+// SortedExplainExpressionList generates explain information for a list of expressions in order.
+// In some scenarios, the expr's order may not be stable when executing multiple times.
+// So we add a sort to make its explain result stable.
+func SortedExplainExpressionList4InList(exprs []Expression) []byte {
+	return sortedExplainExpressionList4InList(exprs, false)
+}
```
Comment (time-and-fate) [inline expression/explain.go:250]: This function is not used. Looks like it's useless?
And the same for the `normalized` parameter of `sortedExplainExpressionList4InList` and the `ExplainInfo4InList` method.

File: expression/explain.go [hunk 3]
```diff
@@ -65,6 +65,51 @@ func (expr *ScalarFunction) ExplainNormalizedInfo() string {
...
+			if normalized {
+				buffer.WriteString(arg.ExplainNormalizedInfo())
+			} else {
+				buffer.WriteString(arg.ExplainInfo())
+			}
+			buffer.WriteString(", ")
+			buffer.WriteString(expr.RetType.String())
+		}
+	default:
+		if expr.FuncName.L == ast.In {
```
Comment (time-and-fate) [inline expression/explain.go:88]: This can be a branch of the `switch ... case ...`.

File: expression/explain.go [hunk 4]
```diff
@@ -65,6 +65,51 @@ func (expr *ScalarFunction) ExplainNormalizedInfo() string {
...
+			buffer.WriteString("...")
```
Comment (time-and-fate) [inline expression/explain.go:89]: What if there is only one constant or if there are columns in the arguments? What's the expected behavior?

File: expression/explain.go (hunk 1 above)
Comment (King-Dylan) [reply expression/explain.go]: Done

File: expression/explain.go (hunk 2 above)
Comment (King-Dylan) [reply expression/explain.go]: Done

File: expression/explain.go (hunk 3 above)
Comment (King-Dylan) [reply expression/explain.go]: Done

File: expression/explain.go [hunk 5]
```diff
@@ -65,6 +65,32 @@ func (expr *ScalarFunction) ExplainNormalizedInfo() string {
 	return expr.explainInfo(true)
 }
 
+func (expr *ScalarFunction) ExplainNormalizedInfo4InList() string {
+	var buffer bytes.Buffer
+	fmt.Fprintf(&buffer, "%s(", expr.FuncName.L)
+	switch expr.FuncName.L {
+	case ast.Cast:
+		for _, arg := range expr.GetArgs() {
+			buffer.WriteString(arg.ExplainNormalizedInfo())
```
Comment (time-and-fate) [inline expression/explain.go:74]: I think we should recursively call `ExplainNormalizedInfo4InList()`.

File: expression/explain.go [hunk 6]
```diff
@@ -65,6 +65,32 @@ func (expr *ScalarFunction) ExplainNormalizedInfo() string {
...
+
+			buffer.WriteString(", ")
+			buffer.WriteString(expr.RetType.String())
+		}
+	case ast.In:
+		buffer.WriteString("...")
+	default:
+		for i, arg := range expr.GetArgs() {
+			buffer.WriteString(arg.ExplainNormalizedInfo())
```
Comment (time-and-fate) [inline expression/explain.go:83]: ditto.

File: expression/explain.go [hunk 7]
```diff
@@ -170,6 +209,27 @@ func SortedExplainNormalizedExpressionList(exprs []Expression) []byte {
...
 
+// SortedExplainNormalizedExpressionList4InList generates explain information for a list of expressions in order.
+func SortedExplainNormalizedExpressionList4InList(exprs []Expression) []byte {
+	buffer := bytes.NewBufferString("")
+	exprInfos := make([]string, 0, len(exprs))
+	for _, expr := range exprs {
+		if _, ok := expr.(*ScalarFunction); ok {
+			exprInfos = append(exprInfos, expr.ExplainNormalizedInfo4InList())
+		} else {
+			exprInfos = append(exprInfos, expr.ExplainNormalizedInfo())
```
Comment (time-and-fate) [inline expression/explain.go:220]: Looks like this branch is unnecessary. And this entire function can be merged into `sortedExplainExpressionList()`.

File: expression/explain.go (hunk 4 above)
Comment (time-and-fate) [reply expression/explain.go]: I think we can say this is proper and expected behavior. And I'm also OK with this rationale.
What I'm concerned about is that it's inconsistent with the behavior of SQL digest. Essentially there isn't an overall design for their behaviors.

File: expression/explain.go [hunk 8]
```diff
@@ -142,17 +180,26 @@ func ExplainExpressionList(exprs []Expression, schema *Schema) string {
...
+		for _, expr := range exprs {
+			exprInfos = append(exprInfos, expr.ExplainNormalizedInfo4InList())
+		}
+	} else {
+		for _, expr := range exprs {
+			if normalized {
+				exprInfos = append(exprInfos, expr.ExplainNormalizedInfo())
+			} else {
+				exprInfos = append(exprInfos, expr.ExplainInfo())
+			}
```
Comment (time-and-fate) [inline expression/explain.go:202]:
```suggestion
	for _, expr := range exprs {
		if ignoreInlist {
			exprInfos = append(exprInfos, expr.ExplainNormalizedInfo4InList())
		} else if normalized {
			exprInfos = append(exprInfos, expr.ExplainNormalizedInfo())
		} else {
			exprInfos = append(exprInfos, expr.ExplainInfo())
```

**Review by time-and-fate — COMMENTED** [review]
Others LGTM.

**Comment by jackysp** [comment]
So, I see there is finally a new system variable added in this PR. Is it necessary? If yes, it's better to add some release note info in PR description.

**Review by time-and-fate — APPROVED** [review]

**Review by chrysan — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Comment by easonn7** [comment]
/approve

A reasonable optimization for tidb_ignore_inlist_plan_digest is to exclude inlists from plan digests in most cases.
