### PR TITLE
planner: fix index join range display when executing the cached plan

### LINKED ISSUE #38269: wrong index join range display when executing the cached plan
## Enhancement

```
mysql> create table t1(a int);
Query OK, 0 rows affected (0.02 sec)

mysql> create table t2(a int, b int, c int, index idx(a, b));
Query OK, 0 rows affected (0.02 sec)

mysql> set @@tidb_enable_prepared_plan_cache=1;
Query OK, 0 rows affected (0.00 sec)

mysql> set @@tidb_enable_collect_execution_info=0;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> show processlist;
+---------------+------+-----------------+------+---------+------+------------+------------------+
| Id            | User | Host            | db   | Command | Time | State      | Info             |
+---------------+------+-----------------+------+---------+------+------------+------------------+
| 2199023255961 | root | 127.0.0.1:53931 | test | Query   |    0 | autocommit | show processlist |
+---------------+------+-----------------+------+---------+------+------------+------------------+
1 row in set (0.00 sec)

mysql> prepare stmt1 from 'select /*+ inl_join(t2) */ * from t1 join t2 on t1.a = t2.a where t2.b in (?, ?, ?)';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a = 10, @b = 20, @c = 30, @d = 40, @e = 50, @f = 60;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt1 using @a, @b, @c;
Empty set (0.01 sec)

mysql> explain for connection  2199023255961;
+---------------------------------+----------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------+
| id                              | estRows  | task      | access object             | operator info                                                                                                   |
+---------------------------------+----------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------+
| IndexJoin_12                    | 37.46    | root      |                           | inner join, inner:IndexLookUp_11, outer key:test.t1.a, inner key:test.t2.a, equal cond:eq(test.t1.a, test.t2.a) |
| ├─TableReader_24(Build)         | 9990.00  | root      |                           | data:Selection_23                                                                                               |
| │ └─Selection_23                | 9990.00  | cop[tikv] |                           | not(isnull(test.t1.a))                                                                                          |
| │   └─TableFullScan_22          | 10000.00 | cop[tikv] | table:t1                  | keep order:false, stats:pseudo                                                                                  |
| └─IndexLookUp_11(Probe)         | 0.00     | root      |                           |                                                                                                                 |
|   ├─Selection_10(Build)         | 0.00     | cop[tikv] |                           | not(isnull(test.t2.a))                                                                                          |
|   │ └─IndexRangeScan_8          | 0.00     | cop[tikv] | table:t2, index:idx(a, b) | range: decided by [eq(test.t2.a, test.t1.a) in(test.t2.b, 10, 20, 30)], keep order:false, stats:pseudo          |
|   └─TableRowIDScan_9(Probe)     | 0.00     | cop[tikv] | table:t2                  | keep order:false, stats:pseudo                                                                                  |
+---------------------------------+----------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------+
8 rows in set (0.00 sec)

mysql> execute stmt1 using @d, @e, @f;
Empty set (0.00 sec)

mysql> explain for connection  2199023255961;
+---------------------------------+----------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------+
| id                              | estRows  | task      | access object             | operator info                                                                                                   |
+---------------------------------+----------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------+
| IndexJoin_12                    | 37.46    | root      |                           | inner join, inner:IndexLookUp_11, outer key:test.t1.a, inner key:test.t2.a, equal cond:eq(test.t1.a, test.t2.a) |
| ├─TableReader_24(Build)         | 9990.00  | root      |                           | data:Selection_23                                                                                               |
| │ └─Selection_23                | 9990.00  | cop[tikv] |                           | not(isnull(test.t1.a))                                                                                          |
| │   └─TableFullScan_22          | 10000.00 | cop[tikv] | table:t1                  | keep order:false, stats:pseudo                                                                                  |
| └─IndexLookUp_11(Probe)         | 0.00     | root      |                           |                                                                                                                 |
|   ├─Selection_10(Build)         | 0.00     | cop[tikv] |                           | not(isnull(test.t2.a))                                                                                          |
|   │ └─IndexRangeScan_8          | 0.00     | cop[tikv] | table:t2, index:idx(a, b) | range: decided by [eq(test.t2.a, test.t1.a) in(test.t2.b, 10, 20, 30)], keep order:false, stats:pseudo          |
|   └─TableRowIDScan_9(Probe)     | 0.00     | cop[tikv] | table:t2                  | keep order:false, stats:pseudo                                                                                  |
+---------------------------------+----------+-----------+---------------------------+-----------------------------------------------------------------------------------------------------------------+
8 rows in set (0.00 sec)
```

When `execute stmt1 using @d, @e, @f`, the right index inner range should be `range: decided by [eq(test.t2.a, test.t1.a) in(test.t2.b, 40, 50, 60)]` rather than `range: decided by [eq(test.t2.a, test.t1.a) in(test.t2.b, 10, 20, 30)]`.

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #38269

Problem Summary:

### What is changed and how it works?

After `PhysicalIndexJoin.Ranges.Rebuild()`, generate the right `rangeInfo` and pass both `ranges` and `rangeInfo` to inner child of `PhysicalIndexJoin`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/plan_cache.go [hunk 1]
```diff
@@ -305,6 +305,26 @@ func RebuildPlan4CachedPlan(p Plan) error {
 	return rebuildRange(p)
 }
 
+func updateRange(p PhysicalPlan, ranges ranger.Ranges, rangeInfo string) error {
```
Comment (qw4990) [inline planner/core/plan_cache.go:308]: Can this function return an error? If not, should we remove the returned error?

**Review by qw4990 — APPROVED** [review]

**Review by Reminiscent — APPROVED** [review]

File: planner/core/plan_cache.go (hunk 1 above)
Comment (xuyifangreeneyes) [reply planner/core/plan_cache.go]: Updated.
