### PR TITLE
statistics: fix sync load fails after disabling lite init stats

### LINKED ISSUE #54532: inconsistency explain bewteen lite-init-stats and non-lite-init-stats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int);
insert into t values(1), (2), (3), (4), (5), (6), (7), (8), (9), (10);
explain format='brief' select * from t where a in (1, 2, 3, 4, 5, 6, 7, 8)
```

### 2. What did you expect to see? (Required)

the same result with lite-init-stats or non-lite-init-stats
```
"TableReader 0.08 root  data:Selection",
└─Selection 0.08 cop[tikv]  in(test.t.a, 1, 2, 3, 4, 5, 6, 7, 8)",
  └─TableFullScan 10.00 cop[tikv] table:t keep order:false, stats:pseudo"
```
### 3. What did you see instead (Required)

non-lite-init-stats is difference from lite-init-stats
```
"TableReader 8.00 root  data:Selection",
└─Selection 8.00 cop[tikv]  in(test.t.a, 1, 2, 3, 4, 5, 6, 7, 8)",
  └─TableFullScan 10.00 cop[tikv] table:t keep order:false, stats:pseudo"
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #54532

Problem Summary:

### What changed and how does it work?

after https://github.com/pingcap/tidb/pull/53399,  we don't load the common column's stats into the cache. so it also cannot init the infoschema in the stats structure. so it will lead the problem, which cannot sync load 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/syncload/stats_syncload.go [hunk 1]
```diff
@@ -545,14 +557,18 @@ func (s *statsSyncLoad) updateCachedItem(item model.TableItemID, colHist *statis
...
+
 		// All the objects shares the same stats version. Update it here.
 		if colHist.StatsVer != statistics.Version0 {
 			tbl.StatsVer = statistics.Version0
 		}
+		if tbl.ColAndIdxExistenceMap.IsColEmpty() {
+			for _, col := range tbleInfo.Meta().Columns {
+				tbl.ColAndIdxExistenceMap.InsertCol(col.ID, col, colHist.StatsAvailable())
+			}
+		}
```
Comment (winoros) [inline pkg/statistics/handle/syncload/stats_syncload.go:569]: Only update the column itself. Otherwise we need to read all column from `mysql.stats_histograms`.

Comment (hawkingrei) [reply pkg/statistics/handle/syncload/stats_syncload.go]: Now, it only update the column itself.

**Review by winoros — APPROVED** [review]

File: pkg/statistics/handle/syncload/stats_syncload.go [hunk 2]
```diff
@@ -545,14 +557,13 @@ func (s *statsSyncLoad) updateCachedItem(item model.TableItemID, colHist *statis
...
-		// If the column is analyzed we refresh the map for the possible change.
-		if colHist.StatsAvailable() {
-			tbl.ColAndIdxExistenceMap.InsertCol(item.ID, colHist.Info, true)
-		}
+
 		// All the objects shares the same stats version. Update it here.
 		if colHist.StatsVer != statistics.Version0 {
 			tbl.StatsVer = statistics.Version0
 		}
+		// If the column is analyzed we refresh the map for the possible change.
```
Comment (AilinKid) [inline pkg/statistics/handle/syncload/stats_syncload.go:565]: the if pre-cond comment can be removed?

**Review by AilinKid — APPROVED** [review]

File: pkg/statistics/handle/syncload/stats_syncload.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/statistics/handle/syncload/stats_syncload.go]: I have updated this comment.

**Comment by D3Hunter** [comment]
/approve

parser part lgtm
