### PR TITLE
planner: `preprocessor` add CTE recursive check when `handleTableName`

### LINKED ISSUE #34090: "references invalid table" when show columns from view
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
use test;
drop table if exists t1, t2;
drop view if exists v1;
create table t1 (a int);
insert into t1 values (0), (1), (2), (3), (4);
create table t2 (a int);
insert into t2 values (1), (2), (3), (4), (5);

create view v1 as with t1 as (
  select a from t2 where t2.a=3
  union
  select t2.a+1 from t1,t2 where t1.a=t2.a)
select * from t1;

-- show columns from another db
create database if not exists test1;
use test1;
show columns from test.v1;
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

```
ERROR 1356 (HY000): View 'test.v1' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```

### 4. What is your TiDB version? (Required)

Both 7e170850 (before https://github.com/pingcap/tidb/pull/33991) and 212a6b22 (master) have this problem.

### PR DESCRIPTION
**Pull request by likzn**
### What problem does this PR solve?

Issue Number: close #34090

Problem Summary: When we use `non recursive CTE`, if the `table name` is the same as `WITH name`.The `preprocessor` will not add schema in the table name. So we need a check judge it if it is recursive. Add schema if it is non recursive, don't add if it is recursive

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Comment by winoros** [comment]
Oh
your change caused a panic in other tests
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/46615/pipeline/

**Comment by likzn** [comment]
> Oh your change caused a panic in other tests https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/46615/pipeline/

My mistake. Fixed.

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -564,6 +581,8 @@ func (p *preprocessor) Leave(in ast.Node) (out ast.Node, ok bool) {
 		if x.Kind == ast.BRIEKindRestore {
 			p.flag &= ^inCreateOrDropTable
 		}
+	case *ast.WithClause:
+		p.preprocessWith.inWithClause = false
```
Comment (wjhuang2016) [inline planner/core/preprocess.go:585]: What happened to nested CTE, it is ok to set false if it is still in the outermost CTE?

File: planner/core/preprocess_test.go [hunk 2]
```diff
@@ -364,3 +365,30 @@ func TestLargeVarcharAutoConv(t *testing.T) {
 		require.True(t, terror.ErrorEqual(warns[i].Err, dbterror.ErrAutoConvert))
 	}
 }
+
+//TestViewWith test create VIEW as WITH when WITH name is same the with table name. Case in Non RECURSIVE/RECURSIVE
+func TestViewWith(t *testing.T) {
```
Comment (wjhuang2016) [inline planner/core/preprocess_test.go:370]: Please move these tests to exlain_test

File: planner/core/preprocess.go [hunk 3]
```diff
@@ -1430,15 +1449,27 @@ func (p *preprocessor) stmtType() string {
...
 		}
+
+		if p.preprocessWith.containsCTEName(tn.Name.L) {
+			if !p.preprocessWith.inWithClause {
+				return
+			}
+
+			if !p.ensureInfoSchema().TableExists(model.NewCIStr(currentDB), tn.Name) {
+				return
+			}
```
Comment (tangenta) [inline planner/core/preprocess.go:1465]: Why do we need to check this?

File: planner/core/preprocess.go [hunk 4]
```diff
@@ -176,6 +176,21 @@ type PreprocessExecuteISUpdate struct {
...
+	inWithClause bool //Only in ast.WithClause should judge to add schema or not when table name is the same as WITH name
+}
+
+//containsCTEName judge lowerTableName if is CTE name or not
+func (p *PreprocessWith) containsCTEName(lowerTableName string) bool {
+	if _, ok := p.name[lowerTableName]; ok {
+		return true
+	}
+	return false
+}
```
Comment (tangenta) [inline planner/core/preprocess.go:192]: Since the implementation is simple enough, we can inline this function.

File: planner/core/preprocess.go [hunk 5]
```diff
@@ -176,6 +176,21 @@ type PreprocessExecuteISUpdate struct {
 	Node                    ast.Node
 }
 
+// PreprocessWith is used to process WITH statement.Such as record CTE name、if use RECURSIVE or not
```
Comment (tangenta) [inline planner/core/preprocess.go:179]:
```suggestion
// PreprocessWith is used to record info from WITH statements like CTE name and RECURSIVE.
```

File: planner/core/preprocess.go [hunk 6]
```diff
@@ -176,6 +176,21 @@ type PreprocessExecuteISUpdate struct {
...
+type PreprocessWith struct {
+	name         map[string]interface{}
+	recursive    bool
+	inWithClause bool //Only in ast.WithClause should judge to add schema or not when table name is the same as WITH name
```
Comment (tangenta) [inline planner/core/preprocess.go:183]:
```suggestion
	inWithClause bool // Only in ast.WithClause should judge to add schema or not when table name is the same as WITH name
```

File: planner/core/preprocess_test.go [hunk 7]
```diff
@@ -364,3 +365,30 @@ func TestLargeVarcharAutoConv(t *testing.T) {
 		require.True(t, terror.ErrorEqual(warns[i].Err, dbterror.ErrAutoConvert))
 	}
 }
+
+//TestViewWith test create VIEW as WITH when WITH name is same the with table name. Case in Non RECURSIVE/RECURSIVE
```
Comment (tangenta) [inline planner/core/preprocess_test.go:369]:
```suggestion
// TestViewWith test create VIEW as WITH when WITH name is same the with table name. Case in Non RECURSIVE/RECURSIVE
```

File: planner/core/preprocess_test.go [hunk 8]
```diff
@@ -364,3 +365,30 @@ func TestLargeVarcharAutoConv(t *testing.T) {
...
+
+	privileges.SkipWithGrant = true
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t1, t2;")
+	tk.MustExec("create table t1 (a int);insert into t1 values (0), (1), (2), (3), (4);")
+	tk.MustExec("create table t2 (a int);insert into t2 values (1), (2), (3), (4), (5);")
+
+	tk.MustExec("drop view if exists v1,v2;")
+	//WITH Non RECURSIVE
```
Comment (tangenta) [inline planner/core/preprocess_test.go:383]:
```suggestion
	// WITH Non RECURSIVE
```

File: planner/core/preprocess_test.go [hunk 9]
```diff
@@ -364,3 +365,30 @@ func TestLargeVarcharAutoConv(t *testing.T) {
...
+	tk.MustExec("create view v1 as WITH t1 as (select a from t2 where t2.a=3 union select t2.a+1 from t1,t2 where t1.a=t2.a) select * from t1;")
+	//WITH RECURSIVE
```
Comment (tangenta) [inline planner/core/preprocess_test.go:385]:
```suggestion
	// WITH RECURSIVE
```

**Review by tangenta — COMMENTED** [review]
I gave some format suggestions.

**Comment by tangenta** [comment]
https://gist.github.com/tangenta/59656073b91a33f7cb0441e598da245a

@likzn I try to write a more intuitive test for the `Preprocess()`, please check if you can add it to your PR.

File: planner/core/preprocess.go (hunk 1 above)
Comment (likzn) [reply planner/core/preprocess.go:585]: I only want to judge the innermost CTE.Maybe the variable name needs to be changed.  So to nested CTE,the outermost CTE will work samel at past.

File: planner/core/preprocess.go (hunk 3 above)
Comment (likzn) [reply planner/core/preprocess.go:1465]: For some case.If the innermost `CTE name` is the same as `table name` and  the CTE is non recursive, we should add schema to the `table name`(t1).
```
create view v1 as with t1 as (
  select a from t2 where t2.a=3
  union
  select t2.a+1 from t1,t2 where t1.a=t2.a)
select * from t1;
```

File: planner/core/preprocess_test.go (hunk 9 above)
Comment (likzn) [reply planner/core/preprocess_test.go:385]: Thanks. I will format after.

File: planner/core/preprocess.go (hunk 1 above)
Comment (wjhuang2016) [reply planner/core/preprocess.go:585]: I guess this would be better.
Enter: saveInWithClause = p.preprocessWith.inWithClause
Leave: p.preprocessWith = saveInWithClause

Comment (likzn) [reply planner/core/preprocess.go:585]: Sorry, can you explain in detail. The Enter and The leave is two method.How can we use the `saveInWithClause`.
I think the below var name maybe is better
`recursive -> deepestRecursive` mean the deepest CTE is recursive or not.
`inWithClause -> inDeepestWithClause` mean if is the deepest CTE WithClause or not.

Comment (wjhuang2016) [reply planner/core/preprocess.go]: Does it work for
`with t1 as (with t11 as (select * from t)  select * from t1, t2) select * from t1;`?

Comment (likzn) [reply planner/core/preprocess.go]: Yes.It works. And i added to `cte.test`.

**Comment by tangenta** [comment]
> how can i ensure the after sql is correct

Take it easy. The reviewers will check the correctness for you.

File: cmd/explaintest/t/cte.test [hunk 10]
```diff
@@ -256,3 +256,22 @@ select * from t1 where c1 > all(with recursive cte1 as (select c1, c2 from t2 un
...
+--echo // Test CTE name is the same as table name
+use test;
+drop table if exists t1, t2;
+drop view if exists v1;
+create table t1 (a int);
+insert into t1 values (0), (1), (2), (3), (4);
+create table t2 (a int);
+insert into t2 values (1), (2), (3), (4), (5);
+with t1 as (select a from t2 where t2.a=3 union select t2.a+1 from t1,t2 where t1.a=t2.a) select * from t1 order by a desc;
+with recursive t1 as ( select a from t2 where t2.a=3 union select t2.a+1 from t1,t2 where t1.a=t2.a) select * from t1 order by a desc;
```
Comment (tangenta) [inline cmd/explaintest/t/cte.test:268]: Where is the `create view` statements?

File: planner/core/preprocess_test.go [hunk 11]
```diff
@@ -364,3 +367,72 @@ func TestLargeVarcharAutoConv(t *testing.T) {
 		require.True(t, terror.ErrorEqual(warns[i].Err, dbterror.ErrAutoConvert))
 	}
 }
+
+// TestViewWith test create VIEW as WITH when WITH name is same the with table name. Case in Non RECURSIVE/RECURSIVE
+func TestViewWith(t *testing.T) {
```
Comment (tangenta) [inline planner/core/preprocess_test.go:372]: We can remove this test after adding it to explain_test.

File: planner/core/preprocess.go (hunk 1 above)
Comment (likzn) [reply planner/core/preprocess.go]: Oh.It not work. The middle `t1` did not add schema. I need think about to resolve it. I think maybe we need modify other node to record some information to distinct where is buildClause and where is the select statement behind CTE. And maybe `p.preprocessWith.name` also need to expand, to nest CTE it will record all in together now,but we should distinct CTE in different level. Can you give me some advice.Thanks

File: cmd/explaintest/t/cte.test (hunk 10 above)
Comment (likzn) [reply cmd/explaintest/t/cte.test:268]: My forget. I will add it later. Now I find some cases not covered.I will think about to solve and fix it. And then i will add more cases into the `cte.test`

File: planner/core/preprocess.go (hunk 1 above)
Comment (wjhuang2016) [reply planner/core/preprocess.go]: When visiting a cte `t`.
If it's a recursive cte, save name `t` so that we can refer it in cte `t`.
If it's not a recursive cte, save name `t` when leaving this node.

Comment (wjhuang2016) [reply planner/core/preprocess.go]: What we need to do:
1. Rewrite withName from map to a slice.
3. When Enter a withNode, set oldWithName = withName, set withNameNew = append(withName, new cte name), and record the offset
4. If is recursive, we can use withNameNew directly.
5. If is not recursive, we can use withNameNew[:len(oldWithName)+ cte_offset]
6. When leaving a withNode, set withName = append(withName, new cte name)

Comment (wjhuang2016) [reply planner/core/preprocess.go]: The idea is that we use a stack-based method to solve it.

Comment (likzn) [reply planner/core/preprocess.go]: But maybe the withNode have multi CTE, as below case.If we `When leaving a withNode, set withName = append(withName, new cte name)`,the `qn` will add schema.
```

SELECT
	(
		WITH qn2 AS ( SELECT 3 * a AS b FROM qn ),
                 qn AS ( SELECT 10 * a AS a FROM t1 ) SELECT
		* 
	FROM
		qn2 
		LIMIT 1 
	) 
FROM
	t1;
```

Comment (wjhuang2016) [reply planner/core/preprocess.go]: Sorry， I don't get your point.

Comment (likzn) [reply planner/core/preprocess.go]: When `withNode` be visited , then it will `cte.Query.Accept(v)` and it is not recursive,so `withName` and `withNameNew[:len(oldWithName)+ cte_offset]` are all empty.Beace `withNode` not reach `leave`, it is in `subExper`. When we `handleTableName` we will think `qn` is a table not a CTE. 
https://github.com/pingcap/tidb/blob/d3a02f416aaa1eda89ce6bec2242ea8254ccfa46/parser/ast/dml.go#L1143-L1156

Comment (wjhuang2016) [reply planner/core/preprocess.go]: `it is not recursive,so withName and withNameNew[:len(oldWithName)+ cte_offset] are all empty`

When Enter a withNode, set oldWithName = withName, set withNameNew = append(withName, new cte name), and record the offset.
It's not empty.

Comment (wjhuang2016) [reply planner/core/preprocess.go]: withName: []
withNameNew: [qn2, qn].
When processing qn2, it can see [qn2], so it would report an error.

Comment (wjhuang2016) [reply planner/core/preprocess.go]: I think that would be easier:

```
func (n *WithClause) Accept(v Visitor) (Node, bool) {
	newNode, skipChildren := v.Enter(n)
	if skipChildren {
		return v.Leave(newNode)
	}

	for _, cte := range n.CTEs {
		**v.Enter(cte)**
		node, ok := cte.Query.Accept(v)
		if !ok {
			return n, false
		}
		cte.Query = node.(*SubqueryExpr)
		**v.Leave(cte)**
	}
	return v.Leave(n)
}
```

Comment (likzn) [reply planner/core/preprocess.go]: >If is recursive, we can use withNameNew directly.
If is not recursive, we can use withNameNew[:len(oldWithName)+ cte_offset]

I think when we firstly deal with `withNode`. And withNameNew:[qn2,qn],if it is recursive,we can use [qn2,qn],but if it is not recursive, i think it should be [].Otherwise it doesn't look any different

>When processing qn2, it can see [qn2], so it would report an error.

If qn2 is really a table,it should not be report an error.It need dealt as `table`
`WITH qn2 AS ( SELECT 3 * a AS b FROM qn2)` -> ``WITH qn2 AS ( SELECT 3 * a AS b FROM `test`.`qn2` )``

Comment (likzn) [reply planner/core/preprocess.go]: > I think that would be easier:
> 
> ```
> func (n *WithClause) Accept(v Visitor) (Node, bool) {
> 	newNode, skipChildren := v.Enter(n)
> 	if skipChildren {
> 		return v.Leave(newNode)
> 	}
> 
> 	for _, cte := range n.CTEs {
> 		**v.Enter(cte)**
> 		node, ok := cte.Query.Accept(v)
> 		if !ok {
> 			return n, false
> 		}
> 		cte.Query = node.(*SubqueryExpr)
> 		**v.Leave(cte)**
> 	}
> 	return v.Leave(n)
> }
> ```
It seem like a good idea.But we need care about Iterator problem.if as below order, `qn` will be missed
```
1.qn2 AS ( SELECT 3 * a AS b FROM qn ),
2.qn AS ( SELECT 10 * a AS a FROM t1 )
```

Comment (wjhuang2016) [reply planner/core/preprocess.go]: It's ok, qn2 couldn't see qn, it should return an error for this case.

Comment (likzn) [reply planner/core/preprocess.go]: This case is found by `cte.test` , i see it can work. What is the error you say,i think i miss something
https://github.com/pingcap/tidb/blob/d3a02f416aaa1eda89ce6bec2242ea8254ccfa46/cmd/explaintest/t/cte.test#L128-L132

Comment (wjhuang2016) [reply planner/core/preprocess.go]: The order is different.

**Comment by likzn** [comment]
@wjhuang2016 I pushed some changes and add some cases into the `expliantest`.PTAL if free.Thanks

**Review by wjhuang2016 — COMMENTED** [review]
I have a more simple approach, but it seems that there is another bug. I am looking into it.

**Review by wjhuang2016 — COMMENTED** [review]
+       cancel()
+       require.NoError(t, err)
+
+       snapIs, err := dom.GetSnapshotInfoSchema(snapTS)
+       require.NotNil(t, snapIs)
+       require.NoError(t, err)
+
+       // Make sure that the self schema version doesn't be changed.
+       goCtx, cancel = context.WithTimeout(context.Background(), 100*time.Millisecond)
+       err = dd.SchemaSyncer().OwnerCheckAllVersions(goCtx, is.SchemaMetaVersion())
+       cancel()
+       require.NoError(t, err)
+
+       // for GetSnapshotInfoSchema
+       currSnapTS := oracle.GoTimeToTS(time.Now())
+       currSnapIs, err := dom.GetSnapshotInfoSchema(currSnapTS)
+       require.NoError(t, err)
+       require.NotNil(t, currSnapTS)
+       require.Equal(t, is.SchemaMetaVersion(), currSnapIs.SchemaMetaVersion())
+
+       // for GetSnapshotMeta
+       dbInfo, ok := currSnapIs.SchemaByName(model.NewCIStr("test2"))
+       require.True(t, ok)
+
+       tbl, err := currSnapIs.TableByName(model.NewCIStr("test2"), model.NewCIStr("t"))
+       require.NoError(t, err)
+
+       m, err := dom.GetSnapshotMeta(snapTS)
+       require.NoError(t, err)
+
+       tblInfo1, err := m.GetTable(dbInfo.ID, tbl.Meta().ID)
+       require.True(t, meta.ErrDBNotExists.Equal(err))
+       require.Nil(t, tblInfo1)
+
+       m, err = dom.GetSnapshotMeta(currSnapTS)
+       require.NoError(t, err)
+
+       tblInfo2, err := m.GetTable(dbInfo.ID, tbl.Meta().ID)
+       require.NoError(t, err)
+       require.Equal(t, tblInfo2, tbl.Meta())
+}
+
+func TestSchemaValidator(t *testing.T) {
+       store, dom, clean := testkit.CreateMockStoreAndDomainWithSchemaLease(t, dbTestLease)
+       defer clean()
+
+       tk := testkit.NewTestKit(t, store)
+
+       dd := dom.DDL()
+       ddl.DisableTiFlashPoll(dd)
+       require.Equal(t, dbTestLease, dd.GetLease())
+
+       tk.MustExec("create table test.t(a int)")
+
+       err := dom.Reload()
+       require.NoError(t, err)
+       schemaVer := dom.InfoSchema().SchemaMetaVersion()
+       ver, err := store.CurrentVersion(kv.GlobalTxnScope)
+       require.NoError(t, err)
+
+       ts := ver.Ver
+       _, res := dom.SchemaValidator.Check(ts, schemaVer, nil)
+       require.Equal(t, domain.ResultSucc, res)
+
+       require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/domain/ErrorMockReloadFailed", `return(true)`))
+
+       err = dom.Reload()
+       require.Error(t, err)
+       _, res = dom.SchemaValidator.Check(ts, schemaVer, nil)
+       require.Equal(t, domain.ResultSucc, res)
+       time.Sleep(dbTestLease)
+
+       ver, err = store.CurrentVersion(kv.GlobalTxnScope)
+       require.NoError(t, err)
+       ts = ver.Ver
+       _, res = dom.SchemaValidator.Check(ts, schemaVer, nil)
+       require.Equal(t, domain.ResultUnknown, res)
+
+       require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/domain/ErrorMockReloadFailed"))
+       err = dom.Reload()
+       require.NoError(t, err)
+
+       _, res = dom.SchemaValidator.Check(ts, schemaVer, nil)
+       require.Equal(t, domain.ResultSucc, res)
+
+       // For schema check, it tests for getting the result of "ResultUnknown".
+       is := dom.InfoSchema()
+       schemaChecker := domain.NewSchemaChecker(dom, is.SchemaMetaVersion(), nil)
+       // Make sure it will retry one time and doesn't take a long time.
+       domain.SchemaOutOfDateRetryTimes.Store(1)
+       domain.SchemaOutOfDateRetryInterval.Store(time.Millisecond * 1)
+       dom.SchemaValidator.Stop()
+       _, err = schemaChecker.Check(uint64(123456))
+       require.EqualError(t, err, domain.ErrInfoSchemaExpired.Error())
+}
+
+func TestLogAndShowSlowLog(t *testing.T) {
+       _, dom, clean := testkit.CreateMockStoreAndDomainWithSchemaLease(t, dbTestLease)
+       defer clean()
+
+       dom.LogSlowQuery(&domain.SlowQueryInfo{SQL: "aaa", Duration: time.Second, Internal: true})
+       dom.LogSlowQuery(&domain.SlowQueryInfo{SQL: "bbb", Duration: 3 * time.Second})
+       dom.LogSlowQuery(&domain.SlowQueryInfo{SQL: "ccc", Duration: 2 * time.Second})
+       // Collecting slow queries is asynchronous, wait a while to ensure it's done.
+       time.Sleep(5 * time.Millisecond)
+
+       result := dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowTop, Count: 2})
+       require.Len(t, result, 2)
+       require.Equal(t, "bbb", result[0].SQL)
+       require.Equal(t, 3*time.Second, result[0].Duration)
+       require.Equal(t, "ccc", result[1].SQL)
+       require.Equal(t, 2*time.Second, result[1].Duration)
+
+       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowTop, Count: 2, Kind: ast.ShowSlowKindInternal})
+       require.Len(t, result, 1)
+       require.Equal(t, "aaa", result[0].SQL)
+       require.Equal(t, time.Second, result[0].Duration)
+       require.True(t, result[0].Internal)
+
+       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowTop, Count: 4, Kind: ast.ShowSlowKindAll})
+       require.Len(t, result, 3)
+       require.Equal(t, "bbb", result[0].SQL)
+       require.Equal(t, 3*time.Second, result[0].Duration)
+       require.Equal(t, "ccc", result[1].SQL)
+       require.Equal(t, 2*time.Second, result[1].Duration)
+       require.Equal(t, "aaa", result[2].SQL)
+       require.Equal(t, time.Second, result[2].Duration)
+       require.True(t, result[2].Internal)
+
+       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowRecent, Count: 2})
+       require.Len(t, result, 2)
+       require.Equal(t, "ccc", result[0].SQL)
+       require.Equal(t, 2*time.Second, result[0].Duration)
+       require.Equal(t, "bbb", result[1].SQL)
+       require.Equal(t, 3*time.Second, result[1].Duration)
+}
+
+func TestReportingMinStartTimestamp(t *testing.T) {
+       _, dom, clean := testkit.CreateMockStoreAndDomainWithSchemaLease(t, dbTestLease)
+       defer clean()
+
+       infoSyncer := dom.InfoSyncer()
+       sm := &testkit.MockSessionManager{
+               PS: make([]*util.ProcessInfo, 0),
+       }
+       infoSyncer.SetSessionManager(sm)
+       beforeTS := oracle.GoTimeToTS(time.Now())
+       infoSyncer.ReportMinStartTS(dom.Store())
+       afterTS := oracle.GoTimeToTS(time.Now())
+       require.False(t, infoSyncer.GetMinStartTS() > beforeTS && infoSyncer.GetMinStartTS() < afterTS)
+
+       now := time.Now()
+       validTS := oracle.GoTimeToLowerLimitStartTS(now.Add(time.Minute), tikv.MaxTxnTimeUse)
+       lowerLimit := oracle.GoTimeToLowerLimitStartTS(now, tikv.MaxTxnTimeUse)
+       sm.PS = []*util.ProcessInfo{
+               {CurTxnStartTS: 0},
+               {CurTxnStartTS: math.MaxUint64},
+               {CurTxnStartTS: lowerLimit},
+               {CurTxnStartTS: validTS},
+       }
+
+       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowRecent, Count: 2})
+       require.Len(t, result, 2)
+       require.Equal(t, "ccc", result[0].SQL)
+       require.Equal(t, 2*time.Second, result[0].Duration)
+       require.Equal(t, "bbb", result[1].SQL)
+       require.Equal(t, 3*time.Second, result[1].Duration)
+}
+
+func TestReportingMinStartTimestamp(t *testing.T) {
+       _, dom, clean := testkit.CreateMockStoreAndDomainWithSchemaLease(t, dbTestLease)
+       defer clean()
+
+       infoSyncer := dom.InfoSyncer()
+       sm := &testkit.MockSessionManager{
+               PS: make([]*util.ProcessInfo, 0),
+       }
+       infoSyncer.SetSessionManager(sm)
+       beforeTS := oracle.GoTimeToTS(time.Now())
+       infoSyncer.ReportMinStartTS(dom.Store())
+       afterTS := oracle.GoTimeToTS(time.Now())
+       require.False(t, infoSyncer.GetMinStartTS() > beforeTS && infoSyncer.GetMinStartTS() < afterTS)
+
+       now := time.Now()
+       validTS := oracle.GoTimeToLowerLimitStartTS(now.Add(time.Minute), tikv.MaxTxnTimeUse)
+       lowerLimit := oracle.GoTimeToLowerLimitStartTS(now, tikv.MaxTxnTimeUse)
+       sm.PS = []*util.ProcessInfo{
+               {CurTxnStartTS: 0},
+               {CurTxnStartTS: math.MaxUint64},
+               {CurTxnStartTS: lowerLimit},
+               {CurTxnStartTS: validTS},
+       }
+       infoSyncer.SetSessionManager(sm)
+       infoSyncer.ReportMinStartTS(dom.Store())
+       require.Equal(t, validTS, infoSyncer.GetMinStartTS())
+}
diff --git a/domain/domain_test.go b/domain/domain_test.go
index ff85c1074..a0fc9c49c 100644
--- a/domain/domain_test.go
+++ b/domain/domain_test.go
@@ -17,7 +17,6 @@ package domain
 import (
        "context"
        "crypto/tls"
-       "math"
        "net"
        "runtime"
        "testing"
@@ -29,20 +28,16 @@ import (
        "github.com/pingcap/tidb/ddl"
        "github.com/pingcap/tidb/domain/infosync"
        "github.com/pingcap/tidb/kv"
-       "github.com/pingcap/tidb/meta"
        "github.com/pingcap/tidb/metrics"
        "github.com/pingcap/tidb/parser/ast"
        "github.com/pingcap/tidb/parser/model"
        "github.com/pingcap/tidb/session/txninfo"
-       "github.com/pingcap/tidb/sessionctx"
        "github.com/pingcap/tidb/sessionctx/variable"
        "github.com/pingcap/tidb/store/mockstore"
        "github.com/pingcap/tidb/util"
        "github.com/pingcap/tidb/util/mock"
        dto "github.com/prometheus/client_model/go"
        "github.com/stretchr/testify/require"
-       "github.com/tikv/client-go/v2/oracle"
-       "github.com/tikv/client-go/v2/tikv"
        "go.etcd.io/etcd/tests/v3/integration"
 )

@@ -156,164 +151,17 @@ func TestInfo(t *testing.T) {
        "github.com/pingcap/tidb/util"
        "github.com/pingcap/tidb/util/mock"
        dto "github.com/prometheus/client_model/go"
        "github.com/stretchr/testify/require"
-       "github.com/tikv/client-go/v2/oracle"
-       "github.com/tikv/client-go/v2/tikv"
        "go.etcd.io/etcd/tests/v3/integration"
 )

@@ -156,164 +151,17 @@ func TestInfo(t *testing.T) {
        require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/domain/infosync/FailPlacement"))
 }

-func TestDomain(t *testing.T) {
+func TestStatWorkRecoverFromPanic(t *testing.T) {
        store, err := mockstore.NewMockStore()
        require.NoError(t, err)

        ddlLease := 80 * time.Millisecond
        dom := NewDomain(store, ddlLease, 0, 0, 0, mockFactory, nil)
-       err = dom.Init(ddlLease, sysMockFactory)
-       require.NoError(t, err)
-
-       ctx := mock.NewContext()
-       ctx.Store = dom.Store()
-       dd := dom.DDL()
-       ddl.DisableTiFlashPoll(dd)
-       require.NotNil(t, dd)
-       require.Equal(t, 80*time.Millisecond, dd.GetLease())
-
-       snapTS := oracle.GoTimeToTS(time.Now())
-       cs := &ast.CharsetOpt{
-               Chs: "utf8",
-               Col: "utf8_bin",
-       }
-       ctx.SetValue(sessionctx.QueryString, "skip")
-       err = dd.CreateSchema(ctx, model.NewCIStr("aaa"), cs, nil)
-       require.NoError(t, err)
-
-       // Test for fetchSchemasWithTables when "tables" isn't nil.
-       ctx.SetValue(sessionctx.QueryString, "skip")
-       err = dd.CreateTable(ctx, &ast.CreateTableStmt{Table: &ast.TableName{
-               Schema: model.NewCIStr("aaa"),
-               Name:   model.NewCIStr("tbl")}})
-       require.NoError(t, err)
-
-       is := dom.InfoSchema()
-       require.NotNil(t, is)
-
-       // for updating the self schema version
-       goCtx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
-       err = dd.SchemaSyncer().OwnerCheckAllVersions(goCtx, is.SchemaMetaVersion())
-       cancel()
-       require.NoError(t, err)
-
-       snapIs, err := dom.GetSnapshotInfoSchema(snapTS)
-       require.NotNil(t, snapIs)
-       require.NoError(t, err)
-
-       // Make sure that the self schema version doesn't be changed.
-       goCtx, cancel = context.WithTimeout(context.Background(), 100*time.Millisecond)
-       err = dd.SchemaSyncer().OwnerCheckAllVersions(goCtx, is.SchemaMetaVersion())
-       cancel()
-       require.NoError(t, err)
-
-       // for GetSnapshotInfoSchema
-       currSnapTS := oracle.GoTimeToTS(time.Now())
-       currSnapIs, err := dom.GetSnapshotInfoSchema(currSnapTS)
-       require.NoError(t, err)
-       require.NotNil(t, currSnapTS)
-       require.Equal(t, is.SchemaMetaVersion(), currSnapIs.SchemaMetaVersion())
-
-       // for GetSnapshotMeta
-       dbInfo, ok := currSnapIs.SchemaByName(model.NewCIStr("aaa"))
-       require.True(t, ok)
-
-       tbl, err := currSnapIs.TableByName(model.NewCIStr("aaa"), model.NewCIStr("tbl"))
-       require.NoError(t, err)
-
-       m, err := dom.GetSnapshotMeta(snapTS)
-       require.NoError(t, err)
-
-       tblInfo1, err := m.GetTable(dbInfo.ID, tbl.Meta().ID)
-       require.True(t, meta.ErrDBNotExists.Equal(err))
-       require.Nil(t, tblInfo1)
-
-       m, err = dom.GetSnapshotMeta(currSnapTS)
-       require.NoError(t, err)
-
-       tblInfo2, err := m.GetTable(dbInfo.ID, tbl.Meta().ID)
-       require.NoError(t, err)
-       require.Equal(t, tblInfo2, tbl.Meta())
-
-       // Test for tryLoadSchemaDiffs when "isTooOldSchema" is false.
-       ctx.SetValue(sessionctx.QueryString, "skip")
-       err = dd.CreateSchema(ctx, model.NewCIStr("bbb"), cs, nil)
-       require.NoError(t, err)
-
-       err = dom.Reload()
-       require.NoError(t, err)
-
-       // for schemaValidator
-       schemaVer := dom.SchemaValidator.(*schemaValidator).LatestSchemaVersion()
-       ver, err := store.CurrentVersion(kv.GlobalTxnScope)
-       require.NoError(t, err)
-
-       ts := ver.Ver
-       _, res := dom.SchemaValidator.Check(ts, schemaVer, nil)
-       require.Equal(t, ResultSucc, res)
-
-       require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/domain/ErrorMockReloadFailed", `return(true)`))
-
-       err = dom.Reload()
-       require.Error(t, err)
-       _, res = dom.SchemaValidator.Check(ts, schemaVer, nil)
-       require.Equal(t, ResultSucc, res)
-       time.Sleep(ddlLease)
-
-       ver, err = store.CurrentVersion(kv.GlobalTxnScope)
-       require.NoError(t, err)
-       ts = ver.Ver
-       _, res = dom.SchemaValidator.Check(ts, schemaVer, nil)
-       require.Equal(t, ResultUnknown, res)
-
-       require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/domain/ErrorMockReloadFailed"))
-       err = dom.Reload()
-       require.NoError(t, err)
-
-       _, res = dom.SchemaValidator.Check(ts, schemaVer, nil)
-       require.Equal(t, ResultSucc, res)
-
-       // For slow query.
-       dom.LogSlowQuery(&SlowQueryInfo{SQL: "aaa", Duration: time.Second, Internal: true})
-       dom.LogSlowQuery(&SlowQueryInfo{SQL: "bbb", Duration: 3 * time.Second})
-       dom.LogSlowQuery(&SlowQueryInfo{SQL: "ccc", Duration: 2 * time.Second})
-       // Collecting slow queries is asynchronous, wait a while to ensure it's done.
-       time.Sleep(5 * time.Millisecond)
-
-       result := dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowTop, Count: 2})
-       require.Len(t, result, 2)
-       require.Equal(t, "bbb", result[0].SQL)
-       require.Equal(t, 3*time.Second, result[0].Duration)
-       require.Equal(t, "ccc", result[1].SQL)
-       require.Equal(t, 2*time.Second, result[1].Duration)
-
-       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowTop, Count: 2, Kind: ast.ShowSlowKindInternal})
-       require.Len(t, result, 1)
-       require.Equal(t, "aaa", result[0].SQL)
-       require.Equal(t, time.Second, result[0].Duration)
-       require.True(t, result[0].Internal)
-
-       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowTop, Count: 4, Kind: ast.ShowSlowKindAll})
-       require.Len(t, result, 3)
-       require.Equal(t, "bbb", result[0].SQL)
-       require.Equal(t, 3*time.Second, result[0].Duration)
-       require.Equal(t, "ccc", result[1].SQL)
-       require.Equal(t, 2*time.Second, result[1].Duration)
-       require.Equal(t, "aaa", result[2].SQL)
-       require.Equal(t, time.Second, result[2].Duration)
-       require.True(t, result[2].Internal)
-
-       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowRecent, Count: 2})
-       require.Len(t, result, 2)
-       require.Equal(t, "ccc", result[0].SQL)
-       require.Equal(t, 2*time.Second, result[0].Duration)
-       require.Equal(t, "bbb", result[1].SQL)
-       require.Equal(t, 3*time.Second, result[1].Duration)

        metrics.PanicCounter.Reset()
        // Since the stats lease is 0 now, so create a new ticker will panic.
        // Test that they can recover from panic correctly.
-       dom.updateStatsWorker(ctx, nil)
+       dom.updateStatsWorker(mock.NewContext(), nil)
        dom.autoAnalyzeWorker(nil)
        counter := metrics.PanicCounter.WithLabelValues(metrics.LabelDomain)
        pb := &dto.Metric{}
@@ -324,46 +172,6 @@ func TestDomain(t *testing.T) {
        scope := dom.GetScope("status")
        require.Equal(t, variable.DefaultStatusVarScopeFlag, scope)

-       // For schema check, it tests for getting the result of "ResultUnknown".
-       schemaChecker := NewSchemaChecker(dom, is.SchemaMetaVersion(), nil)
-       originalRetryTime := SchemaOutOfDateRetryTimes.Load()
-       originalRetryInterval := SchemaOutOfDateRetryInterval.Load()
-       // Make sure it will retry one time and doesn't take a long time.
-       SchemaOutOfDateRetryTimes.Store(1)
-       SchemaOutOfDateRetryInterval.Store(time.Millisecond * 1)
-       require.Equal(t, 3*time.Second, result[0].Duration)
-       require.Equal(t, "ccc", result[1].SQL)
-       require.Equal(t, 2*time.Second, result[1].Duration)
-       require.Equal(t, "aaa", result[2].SQL)
-       require.Equal(t, time.Second, result[2].Duration)
-       require.True(t, result[2].Internal)
-
-       result = dom.ShowSlowQuery(&ast.ShowSlow{Tp: ast.ShowSlowRecent, Count: 2})
-       require.Len(t, result, 2)
-       require.Equal(t, "ccc", result[0].SQL)
-       require.Equal(t, 2*time.Second, result[0].Duration)
-       require.Equal(t, "bbb", result[1].SQL)
-       require.Equal(t, 3*time.Second, result[1].Duration)

        metrics.PanicCounter.Reset()
        // Since the stats lease is 0 now, so create a new ticker will panic.
        // Test that they can recover from panic correctly.
-       dom.updateStatsWorker(ctx, nil)
+       dom.updateStatsWorker(mock.NewContext(), nil)
        dom.autoAnalyzeWorker(nil)
        counter := metrics.PanicCounter.WithLabelValues(metrics.LabelDomain)
        pb := &dto.Metric{}
@@ -324,46 +172,6 @@ func TestDomain(t *testing.T) {
        scope := dom.GetScope("status")
        require.Equal(t, variable.DefaultStatusVarScopeFlag, scope)

-       // For schema check, it tests for getting the result of "ResultUnknown".
-       schemaChecker := NewSchemaChecker(dom, is.SchemaMetaVersion(), nil)
-       originalRetryTime := SchemaOutOfDateRetryTimes.Load()
-       originalRetryInterval := SchemaOutOfDateRetryInterval.Load()
-       // Make sure it will retry one time and doesn't take a long time.
-       SchemaOutOfDateRetryTimes.Store(1)
-       SchemaOutOfDateRetryInterval.Store(time.Millisecond * 1)
-       defer func() {
-               SchemaOutOfDateRetryTimes.Store(originalRetryTime)
-               SchemaOutOfDateRetryInterval.Store(originalRetryInterval)
-       }()
-       dom.SchemaValidator.Stop()
-       _, err = schemaChecker.Check(uint64(123456))
-       require.EqualError(t, err, ErrInfoSchemaExpired.Error())
-       dom.SchemaValidator.Reset()
-
-       // Test for reporting min start timestamp.
-       infoSyncer := dom.InfoSyncer()
-       sm := &mockSessionManager{
-               PS: make([]*util.ProcessInfo, 0),
-       }
-       infoSyncer.SetSessionManager(sm)
-       beforeTS := oracle.GoTimeToTS(time.Now())
-       infoSyncer.ReportMinStartTS(dom.Store())
➜  tidb git:(refine_test_for_ddl) git checkout concurrent_ddl_workspace
Switched to branch 'concurrent_ddl_workspace'
Your branch is up to date with 'wwz/concurrent_ddl_workspace'.
➜  tidb git:(concurrent_ddl_workspace) gcm
error: Your local changes to the following files would be overwritten by checkout:
	domain/domain_test.go
Please commit your changes or stash them before you switch branches.
Aborting
➜  tidb git:(concurrent_ddl_workspace) ✗ git checkout -- .
➜  tidb git:(concurrent_ddl_workspace) gcm
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 4743 commits.
  (use "git push" to publish your local commits)
➜  tidb git:(master) git checkout concurrent_ddl_workspace
error: Your local changes to the following files would be overwritten by checkout:
	ddl/db_test.go
Please commit your changes or stash them before you switch branches.
Aborting
➜  tidb git:(master) ✗ git checkout -- .
➜  tidb git:(master) git checkout concurrent_ddl_workspace
Switched to branch 'concurrent_ddl_workspace'
Your branch is up to date with 'wwz/concurrent_ddl_workspace'.
➜  tidb git:(concurrent_ddl_workspace) git checkout -- .
➜  tidb git:(concurrent_ddl_workspace) gcm
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 4743 commits.
  (use "git push" to publish your local commits)
➜  tidb git:(master) make failpoint-enable
cd tools/check; \
	GO111MODULE=on go build -o ../bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl
➜  tidb git:(master) ✗ make failpoint-disable
➜  tidb git:(master) ✗ make failpoint-enable
➜  tidb git:(master) ✗ make failpoint-disable
➜  tidb git:(master) ✗ gd
➜  tidb git:(master) ✗ make failpoint-enable
➜  tidb git:(master) ✗ make failpoint-disable
➜  tidb git:(master) ✗ gd
^[OB^[OB%
➜  tidb git:(master) ✗ git checkout -b rewrite_test_domain
Switched to a new branch 'rewrite_test_domain'
➜  tidb git:(rewrite_test_domain) ✗ gaa
➜  tidb git:(rewrite_test_domain) ✗ gcsm "done"
[rewrite_test_domain 373b08298] done
 3 files changed, 194 insertions(+), 201 deletions(-)
➜  tidb git:(rewrite_test_domain) git push origin rewrite_test_domain
Enumerating objects: 1840, done.
Counting objects: 100% (1840/1840), done.
Delta compression using up to 10 threads
Compressing objects: 100% (1195/1195), done.
Writing objects: 100% (1434/1434), 1.14 MiB | 4.42 MiB/s, done.
Total 1434 (delta 1148), reused 418 (delta 230), pack-reused 0
remote: Resolving deltas: 100% (1148/1148), completed with 373 local objects.
remote:
remote: Create a pull request for 'rewrite_test_domain' on GitHub by visiting:
remote:      https://github.com/wjhuang2016/tidb/pull/new/rewrite_test_domain
remote:
To github.com:wjhuang2016/tidb.git
 * [new branch]          rewrite_test_domain -> rewrite_test_domain
➜  tidb git:(rewrite_test_domain) gcm
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 4743 commits.
  (use "git push" to publish your local commits)
➜  tidb git:(master) git pr 34133 upstream
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (58/58), done.
remote: Total 72 (delta 58), reused 58 (delta 58), pack-reused 14
Unpacking objects: 100% (72/72), 46.07 KiB | 413.00 KiB/s, done.
From https://github.com/pingcap/tidb
 * [new ref]             refs/pull/34133/head -> pr/34133
Switched to branch 'pr/34133'
➜  tidb git:(pr/34133) make
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/tidb/parser/mysql.TiDBReleaseVersion=v6.1.0-alpha-254-g0b1f64e95-dirty" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2022-04-25 11:31:45" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=0b1f64e95b4ce5a24abf40ff8256cc0e71ab73d9" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=pr/34133" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community" ' -o bin/tidb-server tidb-server/main.go
# github.com/pingcap/tidb/planner/core
planner/core/preprocess.go:186:11: p.withNameCanUsed undefined (type *preprocessWith has no field or method withNameCanUsed)
planner/core/preprocess.go:187:25: p.withNameCanUsed undefined (type *preprocessWith has no field or method withNameCanUsed)
make: *** [server] Error 2
➜  tidb git:(pr/34133) ✗ make
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/tidb/parser/mysql.TiDBReleaseVersion=v6.1.0-alpha-254-g0b1f64e95-dirty" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2022-04-25 11:32:22" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=0b1f64e95b4ce5a24abf40ff8256cc0e71ab73d9" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=pr/34133" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community" ' -o bin/tidb-server tidb-server/main.go
Build TiDB Server successfully!
➜  tidb git:(pr/34133) ✗ cd cmd/explaintest
➜  explaintest git:(pr/34133) ✗ ./run-tests.sh -r all
extracting statistics: s
building tidb-server binary: ./explaintest_tidb-server
building portgenerator binary: ./portgenerator
building explain-test binary: ./explain_test
start tidb-server, log file: ./explain-test.out
tidb-server(PID: 80619) started
record all cases
[2022/04/25 19:34:07.481 +08:00] [FATAL] [main.go:758] ["run test"] [test=collation_misc] [error="sql:with cte as (select cast('2010-09-09' as date) a union select  '2010-09-09  ') select count(*) from cte;: run \"with cte as (select cast('2010-09-09' as date) a union select  '2010-09-09  ') select count(*) from cte;\" at line 47 err Error 1146: Table 'cd_test_latin1.cte' doesn't exist"] [errorVerbose="run \"with cte as (select cast('2010-09-09' as date) a union select  '2010-09-09  ') select count(*) from cte;\" at line 47 err Error 1146: Table 'cd_test_latin1.cte' doesn't exist\nmain.(*tester).execute\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:378\nmain.(*tester).Run\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:165
[2022/04/25 19:36:07.844 +08:00] [INFO] [cpuprofile.go:115] ["parallel cpu profiler started"]
[2022/04/25 19:36:07.844 +08:00] [INFO] [printer.go:34] ["Welcome to TiDB."] ["Release Version"=None] [Edition=Community] ["Git Commit Hash"=None] ["Git Branch"=None] ["UTC Build Time"=None] [GoVersion=go1.18] ["Race Enabled"=true] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
@                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @
"explain-test.out" 2022L, 557711B
\nmain.main\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:757\nruntime.main\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/proc.go:250\nruntime.goexit\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/asm_arm64.s:1259\nsql:with cte as (select cast('2010-09-09' as date) a union select  '2010-09-09  ') select count(*) from cte;"] [stack="main.main\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:758\nruntime.main\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/proc.go:250"]
➜  explaintest git:(pr/34133) ✗ ./run-tests.sh -r all
extracting statistics: s
building tidb-server binary: ./explaintest_tidb-server
building portgenerator binary: ./portgenerator
building explain-test binary: ./explain_test
start tidb-server, log file: ./explain-test.out
tidb-server(PID: 80810) started
record all cases
start tidb-server, log file: ./explain-test.out
tidb-server(PID: 80817) started
./run-tests.sh: line 317: 80810 Killed: 9               $tidb_server -P "$port" -status "$status" -config $config_file -store unistore -path "" > $explain_test_log 2>&1
record all cases
[mysql] 2022/04/25 19:36:31 packets.go:37: unexpected EOF
[2022/04/25 19:36:31.377 +08:00] [ERROR] [main.go:282] ["transaction is failed rollback"] [error="Error 1105: runtime error: slice bounds out of range [:1] with capacity 0"] [errorVerbose="Error 1105: runtime error: slice bounds out of range [:1] with capacity 0\ngithub.com/pingcap/errors.AddStack\n\t/Users/bba/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/Users/bba/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\nmain.(*tester).executeStmt\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:546\nmain.(*tester).executeDefault\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:279\nmain.(*tester).execute\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:358\nmain.(*tester).Run\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:165\nmain.main\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:757\nruntime.main\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/proc.go:250\nruntime.goexit\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/asm_arm64.s:1259"]
[2022/04/25 19:36:31.377 +08:00] [FATAL] [main.go:758] ["run test"] [test=cte] [error="sql:create view v1 as with t1 as (with t11 as (select * from t) select * from t1, t2) select * from t1;: run \"create view v1 as with t1 as (with t11 as (select * from t) select * from t1, t2) select * from t1;\" at line 285 err Error 1105: runtime error: slice bounds out of range [:1] with capacity 0"] [errorVerbose="run \"create view v1 as with t1 as (with t11 as (select * from t) select * from t1, t2) select * from t1;\" at line 285 err Error 1105: runtime error: slice bounds out of range [:1] with capacity 0\nmain.(*tester).execute\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:378\nmain.(*tester).Run\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:165\nmain.main\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:757\nruntime.main\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/proc.go:250\nruntime.goexit\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/asm_arm64.s:1259\nsql:create view v1 as with t1 as (with t11 as (select * from t) select * from t1, t2) select * from t1;"] [stack="main.main\n\t/Users/bba/pc/tidb/cmd/explaintest/main.go:758\nruntime.main\n\t/Users/bba/.gvm/gos/go1.18/src/runtime/proc.go:250"]
➜  explaintest git:(pr/34133) ✗ vim explain-test.out
➜  explaintest git:(pr/34133) ✗ ./run-tests.sh -r all
extracting statistics: s
building tidb-server binary: ./explaintest_tidb-server
building portgenerator binary: ./portgenerator
building explain-test binary: ./explain_test
start tidb-server, log file: ./explain-test.out
tidb-server(PID: 81368) started
record all cases
start tidb-server, log file: ./explain-test.out
tidb-server(PID: 81375) started
./run-tests.sh: line 317: 81368 Killed: 9               $tidb_server -P "$port" -status "$status" -config $config_file -store unistore -path "" > $explain_test_log 2>&1
record all cases
[2022/04/25 19:40:26.274 +08:00] [FATAL] [main.go:758] ["run test"] [test=cte] [error="sql:with recursive cte_2245 (col_8692,col_8693) AS ( select 1, col_7 from tbl_3 UNION  select col_8692 + 1,concat(col_8693, 1) from cte_2245 where col_8692 < 5 ) , cte_2246 (col_8694,col_8695,col_8696,col_8697) AS ( with recursive cte_2247 (col_8698,col_8699,col_8700,col_8701) AS ( select 1, cast(\"2\" as char(20)),3,col_8 from tbl_4 ) select col_8698,col_8699,col_8700,col_8701 from cte_2247 UNION  select col_8694 + 1,col_8695 + 1,col_8696 + 1,col_8697 + 1 from cte_2246 where col_8694 < 5 ) select * from cte_2245,cte_2246 order by col_8692,col_8693,col_8696,col_8695,col_8697,col_8694;: run \"with recursive cte_2245 (col_8692,col_8693) AS ( select 1, col_7 from tbl_3 UNION  select col_8692 + 1,concat(col_8693, 1) from cte_2245 where col_8692 < 5 ) , cte_2246 (col_8694,col_8695,co
[2022/04/25 19:43:13.897 +08:00] [INFO] [cpuprofile.go:115] ["parallel cpu profiler started"]
[2022/04/25 19:43:13.897 +08:00] [INFO] [printer.go:34] ["Welcome to TiDB."] ["Release Version"=None] [Edition=Community] ["Git Commit Hash"=None] ["Git Branch"=None] ["UTC Build Time"=None] [GoVersion=go1.18] ["Race Enabled"=true] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
@                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @                                                                                                                                                 @
"explain-test.out" 2070L, 568825B
[2022/04/25 19:43:37.674 +08:00] [INFO] [ddl.go:711] ["[ddl] DDL job is finished"] [jobID=269]
l_8696,col_8697) AS ( with recursive cte_2247 (col_8698,col_8699,col_8700,col_8701) AS ( select 1, cast(\"2\" as char(20)),3,col_8 from tbl_4 ) select col_8698,col_8699,col_8700,col_8701 from cte_2247 UNION  select col_8694 + 1,col_8695 + 1,col_8696 + 1,col_8697 + 1 from cte_2246 where col_8commit 0b1f64e95b4ce5a24abf40ff8256cc0e71ab73d9 (HEAD -> pr/34133)
Author: likzn <1020193211@qq.com>
Date:   Mon Apr 25 00:41:28 2022 +0800

    optimize code order

commit 99ce2f20a090ef69430c42d3def6dfca80e1b577
Author: likzn <1020193211@qq.com>
Date:   Mon Apr 25 00:33:31 2022 +0800

    clear code

commit a7176b7e5129ccedd11b9dfe9ddaaedd562b14d0
Author: likzn <1020193211@qq.com>
Date:   Mon Apr 25 00:25:11 2022 +0800

    fix logic && add more test

commit 3b82f2ead5975abf82033331138650677cde8cd9
Author: likzn <1020193211@qq.com>
Date:   Fri Apr 22 00:58:04 2022 +0800

    add cte case

commit a123a0c383682cd77afb26bbd7653b74ce05ea3a
Author: likzn <1020193211@qq.com>
Date:   Thu Apr 21 23:13:44 2022 +0800

    fmt && add explaintest && rename var

commit a2a5502fa95437bd805f876fa3367b5dfc868c9d
Author: likzn <1020193211@qq.com>
Date:   Thu Apr 21 08:28:28 2022 +0800

    fix get InfoSchema nil panic

commit 37acc589bb0a76f92aee37c6e5e0ad74a7b73f96
Author: likzn <1020193211@qq.com>
Date:   Thu Apr 21 00:02:20 2022 +0800

    containsCTEName not be exported

commit 3bf5bf97f019cd4d05a71474b2ed13b5a4097b30
Author: likzn <1020193211@qq.com>
Date:   Thu Apr 21 00:00:28 2022 +0800
694 < 5 ) select * from cte_2245,cte_2246 order by col_8692,col_8693,col_8696,col_8695,col_8697,col_8694;\" at line 50 err Error 1146: Table 'testdiff --git a/executor/cte_test.go b/executor/cte_test.go
index 5f68f140f..b3f6721ed 100644
--- a/executor/cte_test.go
+++ b/executor/cte_test.go
@@ -450,9 +450,9 @@ func TestCTEsInView(t *testing.T) {

        tk.MustExec("create database if not exists test1;")
        tk.MustExec("create table test.t (a int);")
-       tk.MustExec("create table test1.t (a int);")
+       //tk.MustExec("create table test1.t (a int);")
        tk.MustExec("insert into test.t values (1);")
-       tk.MustExec("insert into test1.t values (2);")
+       //tk.MustExec("insert into test1.t values (2);")

        tk.MustExec("use test;")
        tk.MustExec("create definer='root'@'localhost' view test.v as with tt as (select * from t) select * from tt;")
diff --git a/parser/ast/dml.go b/parser/ast/dml.go
index 373631642..0c1092707 100644
--- a/parser/ast/dml.go
+++ b/parser/ast/dml.go
@@ -1042,6 +1042,7 @@ type CommonTableExpression struct {
        Name        model.CIStr
        Query       *SubqueryExpr
        ColNameList []model.CIStr
+       IsRecursive bool
 }

 // Restore implement it Before using
diff --git a/planner/core/preprocess.go b/planner/core/preprocess.go
index 542d959e8..afc7aa258 100644
--- a/planner/core/preprocess.go
+++ b/planner/core/preprocess.go
@@ -114,10 +114,9 @@ func TryAddExtraLimit(ctx sessionctx.Context, node ast.StmtNode) ast.StmtNode {
 // preprocessReturn used to extract the infoschema for the tableName and the timestamp from the asof clause.
 func Preprocess(ctx sessionctx.Context, node ast.Node, preprocessOpt ...PreprocessOpt) error {
        v := preprocessor{
-               ctx:              ctx,
-               tableAliasInJoin: make([]map[string]interface{}, 0),
-               preprocessWith: preprocessWith{withNameNew: make([]*ast.WithClause, 0),
-                       withNameCanUsed: make([]*ast.WithClause, 0)},
+               ctx:                ctx,
+               tableAliasInJoin:   make([]map[string]interface{}, 0),
+               preprocessWith:     preprocessWith{withNameNew: make([]string, 0), withNameBeforeOffset: make([]int, 0)},
                staleReadProcessor: staleread.NewStaleReadProcessor(ctx),
        }
        for _, optFn := range preprocessOpt {
@@ -179,14 +178,8 @@ type PreprocessExecuteISUpdate struct {

 // preprocessWith is used to record info from WITH statements like CTE name.
 type preprocessWith struct {
-       withNameNew     []*ast.WithClause
-       withNameCanUsed []*ast.WithClause
-}
-
-func (p *preprocessWith) popWithNameCanUsedIfNotEmpty() {
-       if len(p.withNameCanUsed) > 0 {
-               p.withNameCanUsed = p.withNameCanUsed[:len(p.withNameCanUsed)-1]
-       }
+       withNameNew          []string
+       withNameBeforeOffset []int
 }

 // preprocessor is an ast.Visitor that preprocess
@@ -331,17 +324,17 @@ func (p *preprocessor) Enter(in ast.Node) (out ast.Node, skipChildren bool) {
        case *ast.GroupByClause:
                p.checkGroupBy(node)
        case *ast.WithClause:
-               p.preprocessWith.withNameNew = append(p.preprocessWith.withNameNew, node)
-       case *ast.CommonTableExpression:
-               lastWithNode := p.preprocessWith.withNameNew[len(p.preprocessWith.withNameNew)-1]
-               newCTEMap := make([]*ast.CommonTableExpression, 0)
-               for _, cte := range lastWithNode.CTEs {
-                       if cte.Name.L == node.Name.L && !lastWithNode.IsRecursive {
-                               continue
+               if node.IsRecursive {
+                       for _, cte := range node.CTEs {
+                               cte.IsRecursive = true
                        }
-                       newCTEMap = append(newCTEMap, cte)
                }
-               lastWithNode.CTEs = newCTEMap
+       case *ast.CommonTableExpression:
+               beforeOffset := len(p.preprocessWith.withNameNew)
+               p.preprocessWith.withNameBeforeOffset = append(p.preprocessWith.withNameBeforeOffset, beforeOffset)
+               if node.IsRecursive {
+                       p.preprocessWith.withNameNew = append(p.preprocessWith.withNameNew, node.Name.L)
+               }
        case *ast.BeginStmt:
                // If the begin statement was like following:
                // start transaction read only as of timestamp ....
@@ -586,37 +579,10 @@ func (p *preprocessor) Leave(in ast.Node) (out ast.Node, ok bool) {
                        p.flag &= ^inCreateOrDropTable
                }
        case *ast.CommonTableExpression:
-               lastWithNode := p.preprocessWith.withNameNew[len(p.preprocessWith.withNameNew)-1]
-               if !lastWithNode.IsRecursive {
-                       lastWithNode.CTEs = append(lastWithNode.CTEs, x)
-               }
-
-       case *ast.WithClause:
-               if len(p.preprocessWith.withNameNew) > 0 {
-                       p.preprocessWith.withNameNew =
-                               p.preprocessWith.withNameNew[:len(p.preprocessWith.withNameNew)-1]
-               }
-               p.preprocessWith.withNameCanUsed = append(p.preprocessWith.withNameCanUsed, x)
-       case *ast.SetOprSelectList:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
-       case *ast.SelectStmt:
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
-       case *ast.DeleteStmt:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
-       case *ast.SetOprStmt:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
+               beforeOffset := p.preprocessWith.withNameBeforeOffset[len(p.preprocessWith.withNameBeforeOffset)-1]
+               p.preprocessWith.withNameBeforeOffset = p.preprocessWith.withNameBeforeOffset[:len(p.preprocessWith.withNameBeforeOffset)-1]
+               p.preprocessWith.withNameNew = p.preprocessWith.withNameNew[:beforeOffset]
+               p.preprocessWith.withNameNew = append(p.preprocessWith.withNameNew, x.Name.L)
        }

        return in, p.err == nil
@@ -1485,17 +1451,8 @@ func (p *preprocessor) handleTableName(tn *ast.TableName) {
        if tn.Schema.L == "" {

                if len(p.preprocessWith.withNameNew) > 0 {
-                       with := p.preprocessWith.withNameNew[len(p.preprocessWith.withNameNew)-1]
-                       for _, cte := range with.CTEs {
-                               if cte.Name.L == tn.Name.L {
-                                       return
-                               }
-                       }
-               }
-
-               for _, with := range p.preprocessWith.withNameCanUsed {
-                       for _, cte := range with.CTEs {
-                               if cte.Name.L == tn.Name.L {
+                       for _, cte := range p.preprocessWith.withNameNew {
+                               if cte == tn.Name.L {
                                        return
                                }
                        }
(END)
diff --git a/executor/cte_test.go b/executor/cte_test.go
index 5f68f140f..b3f6721ed 100644
--- a/executor/cte_test.go
+++ b/executor/cte_test.go
@@ -450,9 +450,9 @@ func TestCTEsInView(t *testing.T) {

        tk.MustExec("create database if not exists test1;")
        tk.MustExec("create table test.t (a int);")
-       tk.MustExec("create table test1.t (a int);")
+       //tk.MustExec("create table test1.t (a int);")
        tk.MustExec("insert into test.t values (1);")
-       tk.MustExec("insert into test1.t values (2);")
+       //tk.MustExec("insert into test1.t values (2);")

        tk.MustExec("use test;")
        tk.MustExec("create definer='root'@'localhost' view test.v as with tt as (select * from t) select * from tt;")
diff --git a/parser/ast/dml.go b/parser/ast/dml.go
index 373631642..912b43347 100644
--- a/parser/ast/dml.go
+++ b/parser/ast/dml.go
-               if x.With != nil {
diff --git a/parser/ast/dml.go b/parser/ast/dml.go
index 373631642..912b43347 100644
--- a/parser/ast/dml.go
+++ b/parser/ast/dml.go
@@ -1042,6 +1042,7 @@ type CommonTableExpression struct {
        Name        model.CIStr
        Query       *SubqueryExpr
        ColNameList []model.CIStr
+       IsRecursive bool
 }

 // Restore implement it Before using
@@ -1184,6 +1185,7 @@ func (n *SelectStmt) Restore(ctx *format.RestoreCtx) error {
                }()
        }
        if !n.WithBeforeBraces && n.With != nil {
+               defer ctx.RestoreCTEFunc()()
                err := n.With.Restore(ctx)
                if err != nil {
                        return err
diff --git a/planner/core/preprocess.go b/planner/core/preprocess.go
index 542d959e8..7a09a65ea 100644
--- a/planner/core/preprocess.go
+++ b/planner/core/preprocess.go
@@ -114,10 +114,9 @@ func TryAddExtraLimit(ctx sessionctx.Context, node ast.StmtNode) ast.StmtNode {
 // preprocessReturn used to extract the infoschema for the tableName and the timestamp from the asof clause.
 func Preprocess(ctx sessionctx.Context, node ast.Node, preprocessOpt ...PreprocessOpt) error {
        v := preprocessor{
-               ctx:              ctx,
-               tableAliasInJoin: make([]map[string]interface{}, 0),
-               preprocessWith: preprocessWith{withNameNew: make([]*ast.WithClause, 0),
-                       withNameCanUsed: make([]*ast.WithClause, 0)},
+               ctx:                ctx,
+               tableAliasInJoin:   make([]map[string]interface{}, 0),
+               preprocessWith:     preprocessWith{withNameNew: make([]string, 0), withNameBeforeOffset: make([]int, 0)},
                staleReadProcessor: staleread.NewStaleReadProcessor(ctx),
        }
        for _, optFn := range preprocessOpt {
@@ -179,14 +178,8 @@ type PreprocessExecuteISUpdate struct {

 // preprocessWith is used to record info from WITH statements like CTE name.
 type preprocessWith struct {
-       withNameNew     []*ast.WithClause
-       withNameCanUsed []*ast.WithClause
-}
-
-func (p *preprocessWith) popWithNameCanUsedIfNotEmpty() {
-       if len(p.withNameCanUsed) > 0 {
-               p.withNameCanUsed = p.withNameCanUsed[:len(p.withNameCanUsed)-1]
-       }
+       withNameNew          []string
+       withNameBeforeOffset []int
 }

 // preprocessor is an ast.Visitor that preprocess
@@ -330,18 +323,21 @@ func (p *preprocessor) Enter(in ast.Node) (out ast.Node, skipChildren bool) {
                }
        case *ast.GroupByClause:
                p.checkGroupBy(node)
+       case *ast.SubqueryExpr:
+               beforeOffset := len(p.preprocessWith.withNameNew)
+               p.preprocessWith.withNameBeforeOffset = append(p.preprocessWith.withNameBeforeOffset, beforeOffset)
        case *ast.WithClause:
-               p.preprocessWith.withNameNew = append(p.preprocessWith.withNameNew, node)
-       case *ast.CommonTableExpression:
-               lastWithNode := p.preprocessWith.withNameNew[len(p.preprocessWith.withNameNew)-1]
-               newCTEMap := make([]*ast.CommonTableExpression, 0)
-               for _, cte := range lastWithNode.CTEs {
-                       if cte.Name.L == node.Name.L && !lastWithNode.IsRecursive {
-                               continue
+               if node.IsRecursive {
+                       for _, cte := range node.CTEs {
+                               cte.IsRecursive = true
                        }
-                       newCTEMap = append(newCTEMap, cte)
                }
-               lastWithNode.CTEs = newCTEMap
+       case *ast.CommonTableExpression:
+               beforeOffset := len(p.preprocessWith.withNameNew)
+               p.preprocessWith.withNameBeforeOffset = append(p.preprocessWith.withNameBeforeOffset, beforeOffset)
+               if node.IsRecursive {
+                       p.preprocessWith.withNameNew = append(p.preprocessWith.withNameNew, node.Name.L)
+               }
        case *ast.BeginStmt:
                // If the begin statement was like following:
                // start transaction read only as of timestamp ....
@@ -586,37 +582,14 @@ func (p *preprocessor) Leave(in ast.Node) (out ast.Node, ok bool) {
                        p.flag &= ^inCreateOrDropTable
                }
        case *ast.CommonTableExpression:
-               lastWithNode := p.preprocessWith.withNameNew[len(p.preprocessWith.withNameNew)-1]
-               if !lastWithNode.IsRecursive {
-                       lastWithNode.CTEs = append(lastWithNode.CTEs, x)
-               }
-
-       case *ast.WithClause:
-               if len(p.preprocessWith.withNameNew) > 0 {
-                       p.preprocessWith.withNameNew =
-                               p.preprocessWith.withNameNew[:len(p.preprocessWith.withNameNew)-1]
-               }
-               p.preprocessWith.withNameCanUsed = append(p.preprocessWith.withNameCanUsed, x)
-       case *ast.SetOprSelectList:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
-       case *ast.SelectStmt:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
-       case *ast.UpdateStmt:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
-       case *ast.DeleteStmt:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
-       case *ast.SetOprStmt:
-               if x.With != nil {
-                       p.preprocessWith.popWithNameCanUsedIfNotEmpty()
-               }
+               beforeOffset := p.preprocessWith.withNameBeforeOffset[len(p.preprocessWith.withNameBeforeOffset)-1]
+               p.preprocessWith.withNameBeforeOffset = p.preprocessWith.withNameBeforeOffset[:len(p.preprocessWith.withNameBeforeOffset)-1]
+               p.preprocessWith.withNameNew = p.preprocessWith.withNameNew[:beforeOffset]
+               p.preprocessWith.withNameNew = append(p.preprocessWith.withNameNew, x.Name.L)
+       case *ast.SubqueryExpr:
+               beforeOffset := p.preprocessWith.withNameBeforeOffset[len(p.preprocessWith.withNameBeforeOffset)-1]
+               p.preprocessWith.withNameBeforeOffset = p.preprocessWith.withNameBeforeOffset[:len(p.preprocessWith.withNameBeforeOffset)-1]
+               p.preprocessWith.withNameNew = p.preprocessWith.withNameNew[:beforeOffset]
        }

        return in, p.err == nil
@@ -1485,17 +1458,8 @@ func (p *preprocessor) handleTableName(tn *ast.TableName) {
        if tn.Schema.L == "" {

                if len(p.preprocessWith.withNameNew) > 0 {
-                       with := p.preprocessWith.withNameNew[len(p.preprocessWith.withNameNew)-1]
-                       for _, cte := range with.CTEs {
-                               if cte.Name.L == tn.Name.L {
-                                       return
-                               }
-                       }
-               }
-
-               for _, with := range p.preprocessWith.withNameCanUsed {
-                       for _, cte := range with.CTEs {
-                               if cte.Name.L == tn.Name.L {
+                       for _, cte := range p.preprocessWith.withNameNew {
+                               if cte == tn.Name.L {
                                        return
                                }
                        }
(END)

**Review by wjhuang2016 — COMMENTED** [review]
What we need to do:
1. Save and reset the cte_name when dealing a cte or subquery.
    To do that:
    I add two fields: withNameNew and withNameBeforeOffset.
    Record the length of withNameNew in withNameBeforeOffset as L.
    After leaving a cte node, reset it to [:L], and add cte's name so that it can be seem
   by the later cte.
2. fix missing defer ctx.RestoreCTEFunc()() in func (n *SelectStmt) Restore.

**Review by wjhuang2016 — COMMENTED** [review]
https://github.com/wjhuang2016/tidb/commit/91838baa72767a4be748623de4a370ea016885b3

**Comment by likzn** [comment]
> You can check my change in [wjhuang2016@91838ba](https://github.com/wjhuang2016/tidb/commit/91838baa72767a4be748623de4a370ea016885b3)

It is more clearer and simplier. The usage of `SubqueryExpr ` and `cteOffset` is very ingenious.Learned a lot.

**Comment by wjhuang2016** [comment]
> 

But the code is not tuned enough, it just shows my idea.

For example, some errors are not checked, unexpected panic.
I think you can make it better in your PR.

**Comment by likzn** [comment]
Your code is basiclly complete. I add two changes.
1.Add check to slice length to prevent panic when someone is developing but remove it in elsewhere 
2.Integrate `subexpr` and `CommonTableExpression` to together make code cleaner

File: parser/ast/dml.go [hunk 12]
```diff
@@ -1042,6 +1042,17 @@ type CommonTableExpression struct {
 	Name        model.CIStr
 	Query       *SubqueryExpr
 	ColNameList []model.CIStr
+	IsRecursive bool
+}
+
+// Restore implement it Before using
+func (c CommonTableExpression) Restore(ctx *format.RestoreCtx) error {
+	panic("implement me")
```
Comment (wjhuang2016) [inline parser/ast/dml.go:1050]: It shouldn't panic here.

File: parser/ast/dml.go [hunk 13]
```diff
@@ -1042,6 +1042,17 @@ type CommonTableExpression struct {
...
+}
+
+// Accept implement it Before using
+func (c CommonTableExpression) Accept(v Visitor) (node Node, ok bool) {
+	panic("implement me")
```
Comment (wjhuang2016) [inline parser/ast/dml.go:1055]: v.Enter(cte)
		node, ok := cte.Query.Accept(v)
		if !ok {
			return n, false
		}
		cte.Query = node.(*SubqueryExpr)
		v.Leave(cte)

File: parser/ast/dml.go (hunk 12 above)
Comment (likzn) [reply parser/ast/dml.go:1050]: What is the recommand code here, i implement it because of compile check.But is is not use in the program.And i add note on it.

File: parser/ast/dml.go (hunk 13 above)
Comment (likzn) [reply parser/ast/dml.go:1055]: cte.query is `SubqueryExpr`. I dont find the usage of CommonTableExpression `Accept ` and `store`. So I just panic to prevent someone from using it without implementing it during development

File: parser/ast/dml.go (hunk 12 above)
Comment (wjhuang2016) [reply parser/ast/dml.go:1050]: if len(cte.ColNameList) > 0 {
			ctx.WritePlain(" (")
			for j, name := range cte.ColNameList {
				if j != 0 {
					ctx.WritePlain(", ")
				}
				ctx.WriteName(name.String())
			}
			ctx.WritePlain(")")
		}
		ctx.WriteKeyWord(" AS ")
		err := cte.Query.Restore(ctx)
		if err != nil {
			return err
		}


We can move some code from (n *WithClause) Restore

File: parser/ast/dml.go (hunk 13 above)
Comment (wjhuang2016) [reply parser/ast/dml.go:1055]: cte.Query.Accept(v) -> cte.Accept(v)

File: parser/ast/dml.go (hunk 12 above)
Comment (likzn) [reply parser/ast/dml.go:1050]: Get

File: planner/core/preprocess.go [hunk 14]
```diff
@@ -564,6 +578,18 @@ func (p *preprocessor) Leave(in ast.Node) (out ast.Node, ok bool) {
 		if x.Kind == ast.BRIEKindRestore {
 			p.flag &= ^inCreateOrDropTable
 		}
+	case *ast.CommonTableExpression, *ast.SubqueryExpr:
+		lenWithNameBeforeOffset := len(p.preprocessWith.withNameBeforeOffset)
```
Comment (wjhuang2016) [inline planner/core/preprocess.go:582]: with := p.preprocessWith

make the code clean.

File: cmd/explaintest/r/cte.result [hunk 15]
```diff
@@ -730,3 +730,80 @@ c1	c2
...
+drop view if exists v1;
+create view v1 as with t1 as (with t11 as (select * from t) select * from t1, t2) select * from t1;
+use test1;
+select * from test.v1;
+b	c
+0	0
+use test;
+drop table if exists t11111;
+create table t11111 (d int);
+insert into t11111 values (1), (2), (3), (4), (5);
```
Comment (wjhuang2016) [inline cmd/explaintest/r/cte.result:774]: We should insert some values that are difference with t2

**Review by wjhuang2016 — APPROVED** [review]

**Comment by likzn** [comment]
@tangenta @winoros PTAL. Code has some change

File: bindinfo/handle.go [hunk 16]
```diff
@@ -961,8 +961,8 @@ func GenerateBindSQL(ctx context.Context, stmtNode ast.StmtNode, planHint string
 			withIdx := strings.Index(bindSQL, "WITH")
 			restoreCtx := format.NewRestoreCtx(format.RestoreStringSingleQuotes|format.RestoreSpacesAroundBinaryOperation|format.RestoreStringWithoutCharset|format.RestoreNameBackQuotes, &withSb)
 			restoreCtx.DefaultDB = defaultDB
-			err := n.With.Restore(restoreCtx)
-			if err != nil {
+			defer restoreCtx.RestoreCTEFunc()()
```
Comment (tangenta) [inline bindinfo/handle.go:964]:
```suggestion
```

We don't need to restore `CTERestorer.CTENames` here.

**Review by tangenta — APPROVED** [review]
