### PR TITLE
domain: support GC runaway record

### LINKED ISSUE #44804: `mysql.tidb_runaway_quarantined_watch` includes unactivated watches
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
as #44745 shown, tidb_runaway_quarantined_watch only keeps active quarantined queries. 

### 2. What did you expect to see? (Required)
no unactivated watches.

### 3. What did you see instead (Required)
image

### PR DESCRIPTION
**Pull request by CabinfeverB**
### What problem does this PR solve?

Issue Number: ref #43691 close #44804
As RFC shown, tidb_runaway_quarantined_watch only keeps active quarantined queries. So we should support gc.

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by CabinfeverB** [comment]
cc @nolouch
@lcwangchao Could u take a lock at the modification about ttl/cache/table.go

File: domain/domain.go [hunk 1]
```diff
@@ -1248,11 +1251,103 @@ func (do *Domain) SetOnClose(onClose func()) {
...
+				)
+			}
+		}
+	}
+}
+
 func (do *Domain) runawayRecordFlushLoop() {
 	defer util.Recover(metrics.LabelDomain, "runawayRecordFlushLoop", nil, false)
+
+	quarantineRecordGCInterval := time.Second * 15   //time.Minute * 15
```
Comment (Connor1996) [inline domain/domain.go:1341]: use const?

**Review by Connor1996 — COMMENTED** [review]
And don't forget to update doc as well

File: domain/domain.go [hunk 2]
```diff
@@ -1294,6 +1389,10 @@ func (do *Domain) runawayRecordFlushLoop() {
 			// flush as soon as possible.
 			if len(quarantineRecordCh) == 0 || len(quarantineRecords) >= flushThrehold {
 				flushQuarantineRecords()
+				if owner.IsOwner() {
```
Comment (glorv) [inline domain/domain.go:1392]: Why need gc here, don't get the point

File: domain/domain.go [hunk 3]
```diff
@@ -1302,26 +1401,34 @@ func (do *Domain) runawayRecordFlushLoop() {
 			} else if fired {
 				fired = false
 				// meet a new record, reset the timer.
-				timer.Reset(time.Second)
+				runawayRecordFluashTimer.Reset(time.Second)
+			}
+		case <-runawayRecordGCTicker.C:
+			if owner.IsOwner() {
```
Comment (glorv) [inline domain/domain.go:1407]: better to move this check into `gcSystemTable` to avoid this check everywhere

File: domain/domain.go [hunk 4]
```diff
@@ -1302,26 +1401,34 @@ func (do *Domain) runawayRecordFlushLoop() {
...
+				do.gcSystemTable("tidb_runaway_queries", "time", runawayRecordExpiredDuration)
```
Comment (glorv) [inline domain/domain.go:1408]: As `gcSystemTable` can be very slow, to avoid blocking handling other events, better spawn a new routine to do this job.

File: domain/domain.go [hunk 5]
```diff
@@ -1248,11 +1251,103 @@ func (do *Domain) SetOnClose(onClose func()) {
...
+		leftRows = make([][]types.Datum, len(rows))
+		for i, row := range rows {
+			leftRows[i] = row.GetDatumRow(tb.KeyColumnTypes)
+		}
+		if len(rows) == 0 {
+			return
+		}
+
+		for len(leftRows) > 0 {
+			maxBatch := 100
```
Comment (glorv) [inline domain/domain.go:1308]: Since the previous select is already paged, why do paging again here?

**Review by glorv — COMMENTED** [review]
Please add necessary test cases to cover the new logic

File: domain/domain.go (hunk 2 above)
Comment (CabinfeverB) [reply domain/domain.go:1392]: Because when the watch is updated, it may be a new identify, at this time, I think I can delete the old one immediately.

**Comment by CabinfeverB** [comment]
/test unit-test
--

File: domain/domain.go [hunk 6]
```diff
@@ -1248,11 +1251,116 @@ func (do *Domain) SetOnClose(onClose func()) {
 	do.onClose = onClose
 }
 
+const (
```
Comment (Connor1996) [inline domain/domain.go:1254]: move it to resource group package?

**Review by qw4990 — APPROVED** [review]
