### PR TITLE
hint: fix the problem that set var hint is invalid when create binding

### LINKED ISSUE #40570: The ```set_var``` hint is invalid when create binding
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create table 

```
create table t1 (a int, b varchar(20))
```

2. insert values 

```
insert into t1 values (1, '111111111111111')
```

3. create binding and set group_concat_max_len = 4

```
create binding for select group_concat(b) from test.t1 using select /*+ SET_VAR(group_concat_max_len = 4) */ group_concat(b) from test.t1 ;
```

### 2. What did you expect to see? (Required)

1. create binding successful
2. the result of ```select group_concat(b) from test.t1 ``` should be ```1111```

### 3. What did you see instead (Required)

Create binding failed with syntax error.

### 4. What is your TiDB version? (Required)

v6.5.0

### PR DESCRIPTION
**Pull request by elsa0520**
### What problem does this PR solve?

set var hint is invalid when create binding

Issue Number: close #40570

Problem Summary:

### What is changed and how it works?

1. After finding the binding sql, you also need to update the value of the session var
2. Only session vars with ```IsHintUpdatable:true``` set can be updated
3. When obtaining session var, you cannot directly read attributes, you need to use the function ```GetSessionFromHook```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: bindinfo/session_handle_test.go [hunk 1]
```diff
@@ -16,6 +16,7 @@ package bindinfo_test
 
 import (
 	"context"
+	"github.com/pingcap/tidb/testkit/testdata"
```
Comment (AilinKid) [inline bindinfo/session_handle_test.go:19]: group import

Comment (elsa0520) [reply bindinfo/session_handle_test.go:19]: sorry

Comment (AilinKid) [reply bindinfo/session_handle_test.go]: the error shows "try make bazel_prepare"

File: bindinfo/session_handle_test.go [hunk 2]
```diff
@@ -521,3 +522,20 @@ func TestPreparedStmt(t *testing.T) {
...
+	tk.MustExec("insert into t1 values (1, '111111111111111')")
+	tk.MustExec("insert into t1 values (2, '222222222222222')")
+	tk.MustExec("create binding for select group_concat(b) from test.t1 using select /*+ SET_VAR(group_concat_max_len = 4) */ group_concat(b) from test.t1 ;")
+	explainStrings := testdata.ConvertRowsToStrings(tk.MustQuery("select group_concat(b) from test.t1").Rows())
+	if len(explainStrings) == 1 && explainStrings[0] == "1111" {
+		t.Log("Set var in hint")
+	} else {
+		t.Log("The result is error")
+		t.Fail()
+	}
```
Comment (time-and-fate) [inline bindinfo/session_handle_test.go:540]:
```suggestion
	tk.MustQuery("select group_concat(b) from test.t1").Check(testkit.Rows("1111"))
```

**Review by time-and-fate — APPROVED** [review]

File: bindinfo/BUILD.bazel [hunk 3]
```diff
@@ -71,6 +71,7 @@ go_test(
         "//server",
         "//sessionctx/variable",
         "//testkit",
+        "//testkit/testdata",
```
Comment (time-and-fate) [inline bindinfo/BUILD.bazel:74]: I guess we don't need this change anymore.
