### PR TITLE
*: remove `StatementContext` from `CommonHandleCols` to fix a bug caused by shallow clone in plan cache

### LINKED ISSUE #61118: Instance level plan cache may cause "ERROR 8141 assertion failed" in UPDATE stmt under high concurrency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

#### Code changes

To make it reproducible without high concurrency, we need to introduce latency in the code.

https://github.com/pingcap/tidb/blob/7c0c2b16f965d7f5c16065aa28ece2a7718bff75/pkg/executor/select.go#L891-L899

Modify the code here as below:

```diff
	var sc *stmtctx.StatementContext
	if vars.TxnCtx.CouldRetry || vars.HasStatusFlag(mysql.ServerStatusCursorExists) {
		// Must construct new statement context object, the retry history need context for every statement.
		// TODO: Maybe one day we can get rid of transaction retry, then this logic can be deleted.
		sc = stmtctx.NewStmtCtx()
	} else {
		sc = vars.InitStatementContext()
	}
+	if !vars.InRestrictedSQL {
+		time.Sleep(1 * time.Second)
+	}
	sc.SetTimeZone(vars.Location())
```

The patch would make the SQL execution slow, be patient~

#### Reproduction Steps

1. Preparation

```sql
set global tidb_enable_instance_plan_cache = 1;
create table t(a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, b int, c int, primary key(a), unique key(b,c));
insert into t(b,c) value (1,1);
insert into t(b,c) value (2,2);
```

2. Trigger

We need prepare two sessions (connections) here.

In session 1:

```sql
prepare stmt from 'update t set a = NOW() where b = ? and c = ?';
set @a = 1;
execute stmt using @a, @a;
execute stmt using @a, @a;
```

In session 2:

```sql
prepare stmt from 'update t set a = NOW() where b = ? and c = ?';
set @a = 1;
```

Then execute the SQL below first in session 2, then immediately in session 1. This needs to be very fast.

```sql
execute stmt using @a, @a;
```

### 2. What did you expect to see? (Required)

No errors.

### 3. What did you see instead (Required)

```
ERROR 8141 (HY000): assertion failed: key: 7480000000000000705f720419b69d6e07000000, assertion: Exist, start_ts: 458027064388747265, existing start ts: 0, existing commit ts: 0
```

### 4. What is your TiDB version? (Required)

v8.5.0, v9.0.0-beta.1, and the latest nightly

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #61118

Problem Summary:

See the [comments](https://github.com/pingcap/tidb/issues/61118#issuecomment-2881297944) in the issue for details.

In brief, the `CommonHandleCols` contains `StatementContext`, and the `Update` operator may contain `CommonHandleCols` in `Update.TblColPosInfos`.
The `CommonHandleCols` and the `StatementContext` inside will be passed to `UpdateExec` and used during execution, which causes the bug when we reuse the plan in another session.

### What changed and how does it work?

In the issue, we mentioned replacing `StatementContext` in the `CommonHandleCols` with a `types.Context`. However, it turns out that the `warnHandler` in it is still a `StatementContext`, so this doesn't really remove it.

So, it's probably better to remove `StatementContext` from `CommonHandleCols` directly and pass it when it's needed. This rationale is also consistent with [previous refactoring](https://github.com/pingcap/tidb/issues/49491) related to the usage of `Context` in the executor.

Changes:
- `pkg/planner/util/handle_cols.go`
    - Remove `StatementContext` from `CommonHandleCols`.
    - Remove the `StatementContext` parameter for functions that construct `CommonHandlesCols`.
    - Add a `StatementContext` or `types.Context` parameter for functions that use it
- Other changes are for adapting to the new function signatures.
    - For many places in `executor/`, we need to pass a `StatementContext` now.
    - For many places in `planner/`, we don't need to pass `StatementContext` anymore.
- A test case is added in `pkg/planner/core/issuetest/planner_issue_test.go`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by time-and-fate** [comment]
/hold
Waiting for everyone to finish review

File: pkg/planner/util/handle_cols.go [hunk 1]
```diff
@@ -77,11 +77,10 @@ type CommonHandleCols struct {
 	tblInfo *model.TableInfo
 	idxInfo *model.IndexInfo
 	columns []*expression.Column
-	sc      *stmtctx.StatementContext
```
Comment (qw4990) [inline pkg/planner/util/handle_cols.go:80]: Could you also add some comments here to notify that this structure must be cross-session thread safe?

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/util/handle_cols.go (hunk 1 above)
Comment (qw4990) [reply pkg/planner/util/handle_cols.go:80]: To at least notify others the trick here via comments... and avoid them putting another non-thread-safe structures into it again.

**Review by terry1purcell — APPROVED** [review]
/lgtm

File: pkg/planner/util/handle_cols.go (hunk 1 above)
Comment (time-and-fate) [reply pkg/planner/util/handle_cols.go:80]: updated~

**Review by lcwangchao — APPROVED** [review]
