### PR TITLE
distsql: fix wrong default max allowed packet

### LINKED ISSUE #17816: P1-[4.0 bug hunting]-[SQL Plan Management]-Incorrect result when using SPACE() in a predicate
## Description
Bug Hunter issue tidb-challenge-program/bug-hunting-issue#6

---

Consider the following statements:
```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES (100000);
SELECT * FROM t0 WHERE NOT SPACE(t0.c0); -- expected: {100000}, actual: {}
```
Unexpectedly, the `SELECT` does not fetch any rows:
```
Your MySQL connection id is 1880
Server version: 5.7.25-TiDB-v4.0.0-beta.2-231-gc66320c46 TiDB Server (Apache License 2.0), MySQL 5.7 compatible

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> INSERT INTO t0 VALUES (100000);
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t0 WHERE NOT SPACE(t0.c0);
Empty set, 1 warning (0.00 sec)
```
Note that the query prints the following warning:
```
mysql> show warnings;
+---------+------+--------------------------------------------------------------------------+
| Level   | Code | Message                                                                  |
+---------+------+--------------------------------------------------------------------------+
| Warning | 1105 | Result of space() was larger than max_allowed_packet (65536) - truncated |
+---------+------+--------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
Nevertheless, I would expect the row to be fetched. This is the case when replacing the column by a constant:
```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES (100000);
SELECT * FROM t0 WHERE NOT SPACE(100000); -- {100000}
```
I checked with MySQL 8.0.19, which produces the result I would expect:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 19
Server version: 8.0.19 MySQL Community Server - GPL

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE TABLE t0(c0 INT);
Query OK, 0 rows affected (0.04 sec)

mysql> INSERT INTO t0 VALUES (100000);
Query OK, 1 row affected (0.01 sec)

mysql> SELECT * FROM t0 WHERE NOT SPACE(t0.c0);
+--------+
| c0     |
+--------+
| 100000 |
+--------+
1 row in set (0.00 sec)
```
I propose P0 as a bug level, since it matches the following description: `wrong results returned by the query, and inconsistent results returned by the SQL output`.

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #17816 

### What is changed and how it works?

What's Changed: the max allowed packet for distsql expression is not correct. Since tidb sets it as https://github.com/pingcap/tidb/blob/945f7cc4a04dd09367674b4e5d76f1602812da15/sessionctx/variable/sysvar.go#L580 67108864, distsql expression should be 67108864 consistently.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
### Release note 

- fix wrong default max allowed packet for push downed expression.

### CODE REVIEW

File: expression/distsql_builtin.go [hunk 1]
```diff
@@ -917,9 +917,9 @@ func getSignatureByPB(ctx sessionctx.Context, sigCode tipb.ScalarFuncSig, tp *ti
 	case tipb.ScalarFuncSig_CharLengthUTF8:
 		f = &builtinCharLengthUTF8Sig{base}
 	case tipb.ScalarFuncSig_Concat:
-		f = &builtinConcatSig{base, 65536}
+		f = &builtinConcatSig{base, 67108864}
```
Comment (SunRunAway) [inline expression/distsql_builtin.go:920]: Could this be a Constant, along with https://github.com/pingcap/tidb/blob/945f7cc4a04dd09367674b4e5d76f1602812da15/sessionctx/variable/sysvar.go#L580?

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
