### PR TITLE
executor: fix get var expr when session var is hex literal

### LINKED ISSUE #22949: the result of prepare is different from that of direct query
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
use test;
DROP TABLE IF EXISTS `IDT_MC10146`;
CREATE TABLE `IDT_MC10146` (
  `COL1` bit(4) DEFAULT NULL,
  `COL2` bit(4) DEFAULT NULL,
  `COL3` bit(4) DEFAULT NULL,
  KEY `U_M_COL` (`COL1`,`COL2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `IDT_MC10146` VALUES (0x0F, 0x00, 0x08);
prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
set @a=0x3135;
execute stmt using@a;
select * from IDT_MC10146 where col1 in (0x3135);
```

### 2. What did you expect to see? (Required)
```
MySQL [test]> prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
Query OK, 0 rows affected (0.001 sec)
Statement prepared

MySQL [test]> set @a=0x3135;
Query OK, 0 rows affected (0.000 sec)

MySQL [test]> execute stmt using@a;
Empty set (0.000 sec)

MySQL [test]> select * from IDT_MC10146 where col1 in (0x3135);
Empty set (0.001 sec)
```

### 3. What did you see instead (Required)
```
mysql> prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=0x3135;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using@a;
+------------+------------+------------+
| COL1       | COL2       | COL3       |
+------------+------------+------------+
| 0x0F       | 0x00       | 0x08       |
+------------+------------+------------+
1 row in set (0.00 sec)

mysql> select * from IDT_MC10146 where col1 in (0x3135);
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master 745d20aa64395916060a8f716cdecf9cad9b6957
release-5.0-rc  64994e96c38a2f963f684763a5ff7c5da701056b
release-4.0 8e683506235d2497f725c0bf23d9b0372e37905d

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #22949

Problem Summary:  

    use test;
    DROP TABLE IF EXISTS `IDT_MC10146`;
    CREATE TABLE `IDT_MC10146` (
      `COL1` bit(4) DEFAULT NULL,
      `COL2` bit(4) DEFAULT NULL,
      `COL3` bit(4) DEFAULT NULL,
      KEY `U_M_COL` (`COL1`,`COL2`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
    INSERT INTO `IDT_MC10146` VALUES (0x0F, 0x00, 0x08);
    prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
    set @a=0x3135;
    execute stmt using@a;

GetVar expr(@sess_var) return string type when session_var is hex literal(eg: @sess_var = 0x3135), which is converted to '15'. Actually we should return BinaryLiteral type, but we dont have BinaryLiteral eval type.

### What is changed and how it works?

What's Changed: 
1. When UsingVar is GetVar expr and this session var is BinaryLiteral, we convert the result of GetVar (string) back to BinaryLiteral.
2. Before rewrite IN expr to EQ expr, check if contain mutalbe variables.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test: expression.TestGetVarExprWithHexLiteral()

- Side effects: no

### Release note 

- fix get var expr when session var is hex literal

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@XuHuaiyu @qw4990  PTAL

**Comment by XuHuaiyu** [comment]
What about this test case:
``` sql
CREATE TABLE `IDT_MC10146` (   `COL1` varchar(10) DEFAULT NULL,   `COL2` bit(4) DEFAULT NULL,   `COL3` bit(4) DEFAULT NULL,   KEY `U_M_COL` (`COL1`,`COL2`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `IDT_MC10146` VALUES ('15', 0x00, 0x08);
prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
set @a=0x3135;
execute stmt using@a;
```

**Comment by guo-shaoge** [comment]
> What about this test case:
> 
> ```sql
> CREATE TABLE `IDT_MC10146` (   `COL1` varchar(10) DEFAULT NULL,   `COL2` bit(4) DEFAULT NULL,   `COL3` bit(4) DEFAULT NULL,   KEY `U_M_COL` (`COL1`,`COL2`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
> INSERT INTO `IDT_MC10146` VALUES ('15', 0x00, 0x08);
> prepare stmt from 'select * from IDT_MC10146 where col1 in (?);';
> set @a=0x3135;
> execute stmt using@a;
> ```

Added in planner/core/integration_test.go:2830

**Comment by guo-shaoge** [comment]
[This comment]( https://github.com/pingcap/tidb/issues/22949#issuecomment-796605364) record a case of mysql bug, related to this issue.

**Comment by guo-shaoge** [comment]
@qw4990 @XuHuaiyu

File: planner/core/common_plans.go [hunk 1]
```diff
@@ -187,6 +187,20 @@ type Execute struct {
 	Plan          Plan
 }
 
+// Check if result of GetVar expr is BinaryLiteral
+// Because GetVar use String to represent BinaryLiteral, here we need to convert string back to BinaryLiteral.
+func isGetVarBinaryLiteral(sctx sessionctx.Context, expr expression.Expression) bool {
+	res := false
```
Comment (eurekaka) [inline planner/core/common_plans.go:193]: The `res` looks redundant in this function, we can directly return `dt.Kind() == types.KindBinaryLiteral` of false.

File: planner/core/common_plans.go [hunk 2]
```diff
@@ -187,6 +187,20 @@ type Execute struct {
...
+	scalarFunc, ok := expr.(*expression.ScalarFunction)
+	if ok && scalarFunc.FuncName.L == ast.GetVar {
+		name := scalarFunc.GetArgs()[0].String()
```
Comment (eurekaka) [inline planner/core/common_plans.go:196]: `String()` is for printing / debugging purpose, we'd better use `EvalString()`.

File: types/field_type.go [hunk 3]
```diff
@@ -261,8 +261,8 @@ func DefaultTypeForValue(value interface{}, tp *FieldType, char string, collate
 		tp.Flag |= mysql.UnsignedFlag
 		SetBinChsClnFlag(tp)
 	case BinaryLiteral:
-		tp.Tp = mysql.TypeBit
-		tp.Flen = len(x) * 8
+		tp.Tp = mysql.TypeVarString
+		tp.Flen = len(x)
```
Comment (eurekaka) [inline types/field_type.go:265]: What does this change mean?

File: planner/core/expression_rewriter.go [hunk 4]
```diff
@@ -1375,7 +1375,8 @@ func (er *expressionRewriter) inToExpression(lLen int, not bool, tp *types.Field
 		er.ctxStackAppend(expression.NewNull(), types.EmptyName)
 		return
 	}
-	if leftEt == types.ETInt {
+	containMut := expression.ContainMutableConst(er.sctx, args)
+	if !containMut && leftEt == types.ETInt {
```
Comment (eurekaka) [inline planner/core/expression_rewriter.go:1379]: Can you please add a test case to cover this bug fix? i.e, manufacture a case to reproduce wrong query result caused by this `RefineComparedConstant` when plan cache is enabled.

File: planner/core/common_plans.go [hunk 5]
```diff
@@ -228,6 +242,13 @@ func (e *Execute) OptimizePreparedPlan(ctx context.Context, sctx sessionctx.Cont
 				return err
 			}
 			param := prepared.Params[i].(*driver.ParamMarkerExpr)
+			if isGetVarBinaryLiteral(sctx, usingVar) {
+				binVal, convErr := val.ToBytes()
+				if convErr != nil {
+					return convErr
+				}
+				val.SetBinaryLiteral(types.BinaryLiteral(binVal))
+			}
```
Comment (eurekaka) [inline planner/core/common_plans.go:251]: MySQL's behavior regarding supported user variables types is pretty confusing, according to its documentation 

> User variables can be assigned a value from a limited set of data types: integer, decimal, floating-point, binary or nonbinary string, or NULL value. Assignment of decimal and real values does not preserve the precision or scale of the value. A value of a type other than one of the permissible types is converted to a permissible type. For example, a value having a temporal or spatial data type is converted to a binary string. A value having the JSON data type is converted to a string with a character set of utf8mb4 and a collation of utf8mb4_bin.

> Hexadecimal or bit values assigned to user variables are treated as binary strings. To assign a hexadecimal or bit value as a number to a user variable, use it in numeric context. For example, add 0 or use CAST(... AS UNSIGNED):

We should treat it as string type actually.

File: planner/core/common_plans.go (hunk 1 above)
Comment (lzmhhh123) [inline planner/core/common_plans.go:193]:
```suggestion
func isGetVarBinaryLiteral(sctx sessionctx.Context, expr expression.Expression) (res bool) {
```

File: types/field_type.go [hunk 6]
```diff
@@ -261,8 +261,8 @@ func DefaultTypeForValue(value interface{}, tp *FieldType, char string, collate
 		tp.Flag |= mysql.UnsignedFlag
 		SetBinChsClnFlag(tp)
 	case BinaryLiteral:
-		tp.Tp = mysql.TypeBit
-		tp.Flen = len(x) * 8
```
Comment (lzmhhh123) [inline types/field_type.go:265]: This change is very bottomed. We'd better evaluate its effect carefully.

File: planner/core/common_plans.go (hunk 5 above)
Comment (guo-shaoge) [reply planner/core/common_plans.go:251]: This [PR](https://github.com/pingcap/tidb/pull/4415) indicates that Hex/Bit values are represented by **TypeVarString**. In TiDB when a datum is BinaryLiteray/HexLiteral/BitLiteral, the type of corresponsding Constant expr will be TypeVarString.

So here when the variable val is setted as BinaryLiteral, it's actually a VarString.(Maybe VarString is also string type?)

File: planner/core/expression_rewriter.go (hunk 4 above)
Comment (guo-shaoge) [reply planner/core/expression_rewriter.go:1386]: drop table if exists t1;
    create table t1(c1 tinyint unsigned);
    insert into t1 values(111);
    prepare stmt from 'select 1 from t1 where c1 in (?)';
    set @a = '1.1';
    execute stmt using @a;
    set @a = '111';
    execute stmt using @a;

Above case can cover this situation. Added in TestConstPropAndPPDWithCache()

File: types/field_type.go (hunk 3 above)
Comment (guo-shaoge) [reply types/field_type.go:265]: set @a = 0x3135;
    prepare stmt 'select * from t1 where col_varchar = ?';
    execute stmt using @a;

The quesction mark should be TypeVarString, otherwise when convert 0x3135(TypeBIt) to int, the result if 12597, Equal expr will return false.

File: types/field_type.go (hunk 6 above)
Comment (guo-shaoge) [reply types/field_type.go:265]: According to this [PR](https://github.com/pingcap/tidb/pull/4415), BinaryLiteral should be TypeVarString. So i think this is correct. But we do need more test to verify it's really OK.

**Comment by guo-shaoge** [comment]
@lzmhhh123 @eurekaka PTAL thx~

**Review by lzmhhh123 — APPROVED** [review]
