### PR TITLE
planner: fix no access path when TiKV read is disabled under RC isolation

### LINKED ISSUE #65059: TiFlash plan returns `No access path` error in RC isolation level
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1(a int primary key, b int);
create table t2(a int primary key, b int);
alter table t1 set tiflash replica 1;
alter table t2 set tiflash replica 1;
set tx_isolation="READ-COMMITTED";
begin;
explain select /*+ set_var(tidb_isolation_read_engines='tidb,tiflash'),set_var(tidb_enforce_mpp=on) */ * from t1 join t2 on t1.a=t2.b where t1.a in (1,2);

```

### 2. What did you expect to see? (Required)

TiFlash plan is shown without error.

### 3. What did you see instead (Required)

ERROR 1815 (HY000): Internal : No access path for table 't1' is found with 'tidb_isolation_read_engines' = 'tidb,tiflash', valid values can be 'tikv'.

### 4. What is your TiDB version? (Required)

v8.5.1

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65059

Problem Summary:

### What changed and how does it work?

Because we use RC isolation, so `isForUpdateRead` is true.

https://github.com/pingcap/tidb/blob/6540abdf82be85625cf0334ba00c1c8c1f671c1c/pkg/planner/core/planbuilder.go#L467-L469

Here will not remove the tikv path.
https://github.com/pingcap/tidb/blob/6540abdf82be85625cf0334ba00c1c8c1f671c1c/pkg/planner/core/logical_plan_builder.go#L4491-L4501

`findBestTask4LogicalDataSource` will remove the tiflash path when `isForUpdateRead` is true
https://github.com/pingcap/tidb/blob/6540abdf82be85625cf0334ba00c1c8c1f671c1c/pkg/planner/core/find_best_task.go#L1644-L1667

If this expression is not of the type "select for update" and there are no tikv replicas, even if it is set to RC, it will not cut off tiflash. However, if it is of the type "select for update," then tiflash will be cut off and it will be forced to use tikv.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by you06 — APPROVED** [review]

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -522,7 +522,7 @@ func setPreferredStoreType(ds *logicalop.DataSource, hintInfo *h.PlanHints) {
 			ds.SCtx().GetSessionVars().RaiseWarningWhenMPPEnforced("MPP mode may be blocked because you have set a hint to read table `" + hintTbl.TblName.O + "` from TiKV.")
 		}
 	}
-	if hintTbl := hintInfo.IfPreferTiFlash(alias); hintTbl != nil {
+	if hintTbl := hintInfo.IfPreferTiFlash(alias); hintTbl != nil || ds.SCtx().GetSessionVars().IsMPPEnforced() {
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go]: preferred store type better only care about user perferrence. Enfore behavior should be handle outside

**Review by qw4990 — APPROVED** [review]
