### PR TITLE
ddl: fix dynamic parameter adjustment failure in txn and local ingest mode

### LINKED ISSUE #63201: `ADMIN ALTER DDL JOBS` can't adjust the modify column job concurrency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Submit a DDL to modify the char type column to varchar, and adjust the worker concurrency through admin alter ddl jobs.

### 2. What did you expect to see? (Required)
The worker count can be adjusted.
### 3. What did you see instead (Required)
The worker count remain unchanged.
### 4. What is your TiDB version? (Required)
v8.5.3, master is broken.
v8.5.2, v8.5.1, v8.5.0 is OK.

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #63201

Problem Summary:
After https://github.com/pingcap/tidb/pull/60828, the `runReorgJob` will return periodically, this means every time we  enter the `runOneJobStep`, the `Job` is a new job, not the one pass to backfill worker, so the config in the initial `Job` can't be updated.
https://github.com/pingcap/tidb/blob/b3011b689de0a646e8d4683b37c414c0499d258a/pkg/ddl/job_worker.go#L898-L900
### What changed and how does it work?
Update config from system table in the adjust config loop.
### Check List

Tests 

- [x] Unit test
- [x] Integration test
After this pr, use `admin alter ddl jobs` can adjust `thread` `batch_size` and `max_write_speed` normally
截屏2025-09-22 16 23 55

- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/backfilling_operators.go [hunk 1]
```diff
@@ -782,6 +782,17 @@ func (w *indexIngestWorker) HandleTask(ck IndexRecordChunk, send func(IndexWrite
...
+		for {
+			stop := true
+			failpoint.Inject("mockStuckIndexIngestWorker", func(val failpoint.Value) {
+				stop = val.(bool)
+			})
+			if stop {
+				break
+			}
+		}
+	}
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go]: maybe use failpoint.InjectCall, to have less pollute to prod code

File: pkg/ddl/column.go [hunk 2]
```diff
@@ -940,7 +940,18 @@ func (w *updateColumnWorker) BackfillData(_ context.Context, handleRange reorgBa
...
+			stop := true
+			failpoint.Inject("mockStuckBackfillData", func(val failpoint.Value) {
+				//nolint:forcetypeassert
+				stop = val.(bool)
+			})
+			if stop {
+				break
+			}
+		}
+	}
```
Comment (D3Hunter) [inline pkg/ddl/column.go]: this too

File: pkg/ddl/backfilling_operators.go (hunk 1 above)
Comment (fzzf678) [reply pkg/ddl/backfilling_operators.go]: update in https://github.com/pingcap/tidb/pull/63605/commits/34803e1fb42846de583c1ec064a91628cd1198af, PTAL again

File: pkg/ddl/backfilling.go [hunk 3]
```diff
@@ -858,30 +858,34 @@ func adjustWorkerCntAndMaxWriteSpeed(ctx context.Context, pipe *operator.AsyncPi
 			return
 		case <-ticker.C:
 			failpoint.InjectCall("onUpdateJobParam")
-			maxWriteSpeed := job.ReorgMeta.GetMaxWriteSpeed()
+			if reorgInfo != nil {
```
Comment (zeminzhou) [inline pkg/ddl/backfilling.go]: Why is it checking if `the reorgInfo` is nil? It is not checked elsewhere.

Comment (fzzf678) [reply pkg/ddl/backfilling.go]: Because the upper layer  `executeAndClosePipeline` may pass `nil`, 
截屏2025-09-19 17 13 23
this goroutine is only used for local ingest add index update worker cnt, so we need check

Comment (fzzf678) [reply pkg/ddl/backfilling.go]: OOOh, i see

Comment (fzzf678) [reply pkg/ddl/backfilling.go]: update in https://github.com/pingcap/tidb/pull/63605/commits/3370636a1a9f72fe90a1ef520068e1106344a3ee, PTAL again

File: pkg/ddl/job_worker.go [hunk 4]
```diff
@@ -893,12 +893,6 @@ func (w *worker) runOneJobStep(
 							return
 						case model.JobStateDone, model.JobStateSynced:
 							return
-						case model.JobStateRunning:
```
Comment (D3Hunter) [inline pkg/ddl/job_worker.go:896]: seems we already update those settings from latest job, why not work?

Comment (fzzf678) [reply pkg/ddl/job_worker.go:896]: Because the ReorgMeta we updated is not the original one pass to the backfill worker, https://github.com/pingcap/tidb/pull/60828 make the `runReorgJob` return periodically, every time enter here, the ReorgMeta is a new one, so here becomes a invalid update.

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 5]
```diff
@@ -99,3 +103,53 @@ func TestMultiSchemaChangeTwoIndexes(t *testing.T) {
 		tk.MustExec("admin check table t;")
 	}
 }
+
+func TestAdminAlterAddIndexLocalIngestDDLJob(t *testing.T) {
```
Comment (joechenrh) [inline tests/realtikvtest/addindextest4/integration_test.go]: Seems like the difference between these three newly-added tests are the DDL and failpoint used, can we integrate them into one test?

Comment (fzzf678) [reply tests/realtikvtest/addindextest4/integration_test.go]: Putting these three test together need to execute DDL and control each's failpoint separately, it is a bit confusing and massive, I would prefer to keep these tests independent.

File: pkg/ddl/reorg.go [hunk 6]
```diff
@@ -638,6 +638,20 @@ func (r *reorgInfo) String() string {
 		"Ingest mode:" + strconv.FormatBool(isEnabled)
 }
 
+// UpdateConfigFromSysTbl updates the reorg config from system table.
+func (r *reorgInfo) UpdateConfigFromSysTbl(ctx context.Context) {
+	latestJob, err := r.jobCtx.sysTblMgr.GetJobByID(ctx, r.ID)
+	if err != nil {
+		logutil.DDLLogger().Warn("failed to get latest job from system table", zap.Int64("jobID", r.ID), zap.Error(err))
```
Comment (D3Hunter) [inline pkg/ddl/reorg.go]:
```suggestion
		logutil.DDLLogger().Warn("failed to get latest job from system table",
			zap.Int64("jobID", r.ID), zap.Error(err))
```

File: pkg/ddl/backfilling_operators.go [hunk 7]
```diff
@@ -782,6 +782,7 @@ func (w *indexIngestWorker) HandleTask(ck IndexRecordChunk, send func(IndexWrite
 	failpoint.Inject("injectPanicForIndexIngest", func() {
 		panic("mock panic")
 	})
+	failpoint.InjectCall("mockIndexIngestWorkerStuck")
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go]: you can merge previous `injectPanicForIndexIngest` into this one

File: pkg/ddl/index_change_test.go [hunk 8]
```diff
@@ -432,3 +434,51 @@ func TestAddIndexRowCountUpdate(t *testing.T) {
...
+	tk1.MustExec("insert into t values (1);")
+	ch := make(chan struct{})
+	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/ddl/mockAddIndexTxnWorkerStuck", func() {
+		<-ch
+	})
+	testfailpoint.Enable(t, "github.com/pingcap/tidb/pkg/ddl/updateProgressIntervalInMs", "return(100)")
+	wg := sync.WaitGroup{}
+	wg.Add(1)
+	go func() {
+		defer wg.Done()
```
Comment (D3Hunter) [inline pkg/ddl/index_change_test.go]: use our wait group wrapper, simplier

File: pkg/ddl/index_change_test.go [hunk 9]
```diff
@@ -432,3 +434,51 @@ func TestAddIndexRowCountUpdate(t *testing.T) {
...
+		}
+	}
+	workerCnt := 7
+	batchSize := 89
+	maxWriteSpeed := 1011
+	tk2.MustExec(fmt.Sprintf("admin alter ddl jobs %s thread = %d", jobID, workerCnt))
+	tk2.MustExec(fmt.Sprintf("admin alter ddl jobs %s batch_size = %d", jobID, batchSize))
+	tk2.MustExec(fmt.Sprintf("admin alter ddl jobs %s max_write_speed = %d", jobID, maxWriteSpeed))
+	require.Eventually(t, func() bool {
+		return realWorkerCnt == workerCnt && realBatchSize == batchSize && realMaxWriteSpeed == maxWriteSpeed
```
Comment (D3Hunter) [inline pkg/ddl/index_change_test.go]: data race

File: pkg/ddl/index_change_test.go [hunk 10]
```diff
@@ -432,3 +434,51 @@ func TestAddIndexRowCountUpdate(t *testing.T) {
 	}()
 	tk.MustExec("alter table t add index idx(c2);")
 }
+
+func TestAdminAlterAddIndexTxnDDLJob(t *testing.T) {
```
Comment (D3Hunter) [inline pkg/ddl/index_change_test.go]:
```suggestion
func TestAlterAddIndexInTxnMode(t *testing.T) {
```

File: pkg/ddl/modify_column_test.go [hunk 11]
```diff
@@ -607,3 +607,51 @@ func TestModifyColumnWithIndexesWriteConflict(t *testing.T) {
...
+	tk1.MustExec("insert into t values (1);")
+	ch := make(chan struct{})
+	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/ddl/mockUpdateColumnWorkerStuck", func() {
+		<-ch
+	})
+	testfailpoint.Enable(t, "github.com/pingcap/tidb/pkg/ddl/updateProgressIntervalInMs", "return(100)")
+	wg := sync.WaitGroup{}
+	wg.Add(1)
+	go func() {
+		defer wg.Done()
```
Comment (D3Hunter) [inline pkg/ddl/modify_column_test.go]: doitto

File: pkg/ddl/index_change_test.go [hunk 12]
```diff
@@ -432,3 +434,51 @@ func TestAddIndexRowCountUpdate(t *testing.T) {
...
+
+	jobID := ""
+	tk2 := testkit.NewTestKit(t, store)
+	for {
+		row := tk2.MustQuery("select job_id from mysql.tidb_ddl_job").Rows()
+		if len(row) == 1 {
+			jobID = row[0][0].(string)
+			break
+		}
+	}
```
Comment (D3Hunter) [inline pkg/ddl/index_change_test.go]: you can use `admin show ddl jobs 1` to get the first row

File: pkg/ddl/modify_column_test.go [hunk 13]
```diff
@@ -607,3 +607,51 @@ func TestModifyColumnWithIndexesWriteConflict(t *testing.T) {
...
+
+	jobID := ""
+	tk2 := testkit.NewTestKit(t, store)
+	for {
+		row := tk2.MustQuery("select job_id from mysql.tidb_ddl_job").Rows()
+		if len(row) == 1 {
+			jobID = row[0][0].(string)
+			break
+		}
+	}
```
Comment (D3Hunter) [inline pkg/ddl/modify_column_test.go]: doittoo

File: pkg/ddl/modify_column_test.go [hunk 14]
```diff
@@ -607,3 +607,51 @@ func TestModifyColumnWithIndexesWriteConflict(t *testing.T) {
 		"3 3 3 c",
 		"4 4 4 d"))
 }
+
+func TestAdminAlterModifyColumnDDLJob(t *testing.T) {
```
Comment (D3Hunter) [inline pkg/ddl/modify_column_test.go]: seems this test and the case in `pkg/ddl/index_change_test.go` are so similiar, maybe unified into one, with different param

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 15]
```diff
@@ -99,3 +103,53 @@ func TestMultiSchemaChangeTwoIndexes(t *testing.T) {
...
+
+	jobID := ""
+	tk2 := testkit.NewTestKit(t, store)
+	for {
+		row := tk2.MustQuery("select job_id from mysql.tidb_ddl_job").Rows()
+		if len(row) == 1 {
+			jobID = row[0][0].(string)
+			break
+		}
+	}
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest4/integration_test.go]: doitto

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 16]
```diff
@@ -99,3 +103,53 @@ func TestMultiSchemaChangeTwoIndexes(t *testing.T) {
...
+	workerCnt := 7
+	batchSize := 89
+	maxWriteSpeed := 1011
+	tk2.MustExec(fmt.Sprintf("admin alter ddl jobs %s thread = %d", jobID, workerCnt))
+	tk2.MustExec(fmt.Sprintf("admin alter ddl jobs %s batch_size = %d", jobID, batchSize))
+	tk2.MustExec(fmt.Sprintf("admin alter ddl jobs %s max_write_speed = %d", jobID, maxWriteSpeed))
+	require.Eventually(t, func() bool {
+		return realWorkerCnt == workerCnt && realBatchSize == batchSize && realMaxWriteSpeed == maxWriteSpeed
+	}, time.Second*5, time.Millisecond*100)
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest4/integration_test.go]:
```suggestion
	}, 30*time.Second, time.Millisecond*100)
```
to avoid CI slowness and cause flaky, and also change others too

File: pkg/ddl/backfilling_operators.go (hunk 7 above)
Comment (fzzf678) [reply pkg/ddl/backfilling_operators.go]: update in https://github.com/pingcap/tidb/pull/63605/commits/394c750b4e025fc140274db26eb83fd5784ea473

File: tests/realtikvtest/addindextest4/integration_test.go (hunk 15 above)
Comment (fzzf678) [reply tests/realtikvtest/addindextest4/integration_test.go]: update in https://github.com/pingcap/tidb/pull/63605/commits/ffcf67ffd1d499866613dc21b29569ca085aacb1

File: pkg/ddl/index_change_test.go (hunk 12 above)
Comment (fzzf678) [reply pkg/ddl/index_change_test.go]: Here use `admin show ddl jobs` may get the DDL job id has finished, by querying the system table can get the ddl job id we executed, wait for the previous go routine execute the ddl.

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 17]
```diff
@@ -99,3 +104,83 @@ func TestMultiSchemaChangeTwoIndexes(t *testing.T) {
...
+			checkReorgMetaFp: "github.com/pingcap/tidb/pkg/ddl/checkReorgWorkerCnt",
+			sql:              "alter table t add index idx(a)",
+			preCondition:     "set @@global.tidb_ddl_enable_fast_reorg=off",
+		},
+	}
+
+	for _, tc := range testCases {
+		if tc.preCondition != "" {
+			tk1.MustExec(tc.preCondition)
+		}
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest4/integration_test.go]: revert it back, the physical cluster is shared by all tests cases in this folder

File: tests/realtikvtest/addindextest4/integration_test.go [hunk 18]
```diff
@@ -99,3 +104,83 @@ func TestMultiSchemaChangeTwoIndexes(t *testing.T) {
...
+		},
+		{
+			stuckFp:          "github.com/pingcap/tidb/pkg/ddl/mockAddIndexTxnWorkerStuck",
+			checkReorgMetaFp: "github.com/pingcap/tidb/pkg/ddl/checkReorgWorkerCnt",
+			sql:              "alter table t add index idx(a)",
+			preCondition:     "set @@global.tidb_ddl_enable_fast_reorg=off",
+		},
+	}
+
+	for _, tc := range testCases {
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest4/integration_test.go:143]: use `t.Run()` to run with subtask, so failpoints of each case will be separated

**Review by D3Hunter — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
