### PR TITLE
br: fix region scan checker

### LINKED ISSUE #64514: BR restore failed with error "type:UNKNOWN message:\"invalid store ID 0, not found\" when simulated pd network partition or pd rolling restart
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run br restore
2、simulated pd network partition

### 2. What did you expect to see? (Required)
br restore can succeed

### 3. What did you see instead (Required)
BR restore failed with error "type:UNKNOWN message:\"invalid store ID 0, not found\"

[br.log.2025-11-14T03.40.11Z.zip](https://github.com/user-attachments/files/23574055/br.log.2025-11-14T03.40.11Z.zip)

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v9.0.0-beta.2.pre-784-gcf74287377
Edition: Community
Git Commit Hash: cf742873771db9f9c99e559b6db289a45067ef12
Git Branch: HEAD
UTC Build Time: 2025-11-11 08:42:59
GoVersion: go1.25.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Kernel Type: Classic

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #64514

Problem Summary:
the store id of region leader scanned may be 0.
### What changed and how does it work?
add region scan checker to check the leader store id after each region scan API.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
please help push PD side to accept this request https://github.com/tikv/pd/issues/8442

**Comment by okJiang** [comment]
> please help push PD side to accept this request [tikv/pd#8442](https://github.com/tikv/pd/issues/8442)

Got it. I will try

File: br/pkg/restore/split/split.go [hunk 1]
```diff
@@ -152,7 +152,7 @@ func (rs *RegionSplitter) WaitForScatterRegionsTimeout(ctx context.Context, regi
 	return leftRegions
 }
 
-func checkRegionConsistency(startKey, endKey []byte, regions []*RegionInfo) error {
+func checkRegionConsistency(startKey, endKey []byte, regions []*RegionInfo, limitted bool) error {
```
Comment (okJiang) [inline br/pkg/restore/split/split.go:158]: Can you add a comment for `limited`?

File: br/pkg/restore/split/split.go [hunk 2]
```diff
@@ -252,7 +281,7 @@ func PaginateScanRegion(
 		}
 		lastRegions = regions
 
-		if err = checkRegionConsistency(startKey, endKey, regions); err != nil {
+		if err = checkRegionConsistency(startKey, endKey, regions, false); err != nil {
```
Comment (okJiang) [inline br/pkg/restore/split/split.go:287]: How about moving this to here and not call `checkRegionConsistency`?

Image

Comment (Leavrth) [reply br/pkg/restore/split/split.go:287]: We need also check the consistency between the adjacent batches, not only the check here. Maybe this duplicate check doesn't consume too much resource?

**Review by okJiang — APPROVED** [review]
