### PR TITLE
lightning: return not-found for missing checkpoint table names in lightning-ctl

### LINKED ISSUE #67711: lightning: return not-found for checkpoint-error-ignore/destroy on missing table key
## Enhancement

`tidb-lightning-ctl` currently exits successfully when a user passes a non-existent table key to:

- `--checkpoint-error-ignore=<table>`
- `--checkpoint-error-destroy=<table>`

For example, users may pass `db.table` while checkpoint keys are stored as MySQL-quoted names like `` `db`.`table` ``. In this case, the command silently succeeds and gives no feedback that nothing matched.

### Expected behavior

For specific-table operations (not `all`):

- If the checkpoint key does not exist, return an explicit **not found** error.
- Error message should include correct examples, e.g.:
  - `--checkpoint-error-ignore='\`db\`.\`table\`'`
  - `--checkpoint-error-destroy='\`db\`.\`table\`'`
  - or `all`

### Why this is useful

This prevents silent no-op operations and helps users quickly detect wrong table-name format/input.

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #67711

Problem Summary:
`tidb-lightning-ctl` silently succeeds when users pass a non-existent table checkpoint key to `--checkpoint-error-ignore` / `--checkpoint-error-destroy` (for example `db.table` instead of `` `db`.`table` ``). This hides input mistakes and gives no feedback.

### What changed and how does it work?
- Added explicit not-found detection for specific-table operations in both checkpoint backends:
  - legacy checkpoint path (`pkg/lightning/checkpoints`)
  - import-into checkpoint path (`lightning/pkg/importinto`)
- When the target table checkpoint key does not exist, return `NotFound` with clear examples:
  - ``--checkpoint-error-ignore='`db`.`table`'``
  - ``--checkpoint-error-destroy='`db`.`table`'``
  - or `all`
- Added regression tests covering missing-table behavior for `ignore` and `destroy` in file + MySQL checkpoint managers.
- Ran `make bazel_prepare` as required after adding new top-level test cases, including generated Bazel metadata updates.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

```
➜  lightning /Users/jujiajia/.codex/worktrees/592f/tidb/bin/tidb-lightning-ctl --config test.toml --checkpoint-error-destroy='test.t'
[2026/04/13 14:47:33.128 +08:00] [INFO] [service_discovery.go:974] ["[pd] update member urls"] [old-sorted-urls="[http://downstream.host.playground:2379]"] [new-sorted-urls="[http://192.168.206.72:2379]"]
[2026/04/13 14:47:33.128 +08:00] [INFO] [service_discovery.go:993] ["[pd] switch leader"] [new-leader=http://192.168.206.72:2379] [old-leader=]
[2026/04/13 14:47:33.128 +08:00] [INFO] [service_discovery.go:498] ["[pd] init cluster id"] [cluster-id=7628131262990799288]
[2026/04/13 14:47:33.160 +08:00] [INFO] [service_discovery.go:551] ["[pd] exit member loop due to context canceled"]
[2026/04/13 14:47:33.160 +08:00] [INFO] [service_discovery.go:642] ["[pd] close service discovery client"]
[2026/04/13 14:47:33.161 +08:00] [INFO] [client.go:349] ["[pd] http client closed"] [source=lightning-ctl]
checkpoint for table test.t not found; valid examples: --checkpoint-error-ignore='`db`.`table`', --checkpoint-error-destroy='`db`.`table`', or 'all'
➜  lightning /Users/jujiajia/.codex/worktrees/592f/tidb/bin/tidb-lightning-ctl --config test.toml --checkpoint-error-ignore='test.t'
[2026/04/13 14:47:39.203 +08:00] [INFO] [service_discovery.go:974] ["[pd] update member urls"] [old-sorted-urls="[http://downstream.host.playground:2379]"] [new-sorted-urls="[http://192.168.206.72:2379]"]
[2026/04/13 14:47:39.203 +08:00] [INFO] [service_discovery.go:993] ["[pd] switch leader"] [new-leader=http://192.168.206.72:2379] [old-leader=]
[2026/04/13 14:47:39.203 +08:00] [INFO] [service_discovery.go:498] ["[pd] init cluster id"] [cluster-id=7628131262990799288]
[2026/04/13 14:47:39.205 +08:00] [INFO] [service_discovery.go:551] ["[pd] exit member loop due to context canceled"]
[2026/04/13 14:47:39.206 +08:00] [INFO] [service_discovery.go:642] ["[pd] close service discovery client"]
[2026/04/13 14:47:39.206 +08:00] [INFO] [client.go:349] ["[pd] http client closed"] [source=lightning-ctl]
checkpoint for table test.t not found; valid examples: --checkpoint-error-ignore='`db`.`table`', --checkpoint-error-destroy='`db`.`table`', or 'all'
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Lightning now returns a not-found error for `--checkpoint-error-ignore=<table>` and `--checkpoint-error-destroy=<table>` when the table checkpoint key does not exist, and the error message includes correct `` `db`.`table` `` examples.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Ignore/destroy operations now return a clear "checkpoint table not found" error that includes example checkpoint flags for guidance.
  * CLI output no longer shows a stack trace for this not-found case, so the concise message is displayed.

* **New Features**
  * Added a dedicated checkpoint-table-not-found error constructor and predicate for reliable detection.

* **Tests**
  * Added coverage for missing-table behavior across checkpoint flows and CLI formatting; tests assert NotFound errors and expected return values.

### CODE REVIEW

File: pkg/lightning/common/errors.go [hunk 1]
```diff
@@ -105,6 +105,18 @@ var (
...
+const checkpointTableNotFoundHint = "valid examples: --checkpoint-error-ignore='`db`.`table`', --checkpoint-error-destroy='`db`.`table`', or 'all'"
+
+// CheckpointTableNotFoundError returns a user-facing error for missing table checkpoints.
+func CheckpointTableNotFoundError(tableName string) error {
+	return errors.Errorf("checkpoint for table %s not found; %s", tableName, checkpointTableNotFoundHint)
+}
+
+// IsCheckpointTableNotFoundError reports whether err was produced by CheckpointTableNotFoundError.
+func IsCheckpointTableNotFoundError(err error) bool {
+	return err != nil && errors.IsNotFound(err) && strings.Contains(err.Error(), checkpointTableNotFoundHint)
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply pkg/lightning/common/errors.go]: Addressed in 3500bd0c72. Added a stable named sentinel (`ErrCheckpointTableNotFoundIdentity`) and switched `IsCheckpointTableNotFoundError` to identity-based matching (`errors.ErrorEqual`) instead of hint-text matching. Kept the hint as user-facing text in `CheckpointTableNotFoundError`, and added a regression test to ensure unrelated not-found errors with similar text are not misclassified.

File: lightning/pkg/importinto/checkpoint.go [hunk 2]
```diff
@@ -261,7 +261,11 @@ func (m *FileCheckpointManager) IgnoreError(ctx context.Context, tableName strin
 			}
 		}
 	} else {
-		if cp, ok := m.checkpoints[tableName]; ok && cp.Status == CheckpointStatusFailed {
+		cp, ok := m.checkpoints[tableName]
+		if !ok {
+			return common.CheckpointTableNotFoundError(tableName)
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply lightning/pkg/importinto/checkpoint.go]: Addressed in 3500bd0c72. Updated `CheckpointManager` interface docs for both `IgnoreError` and `DestroyError` to document table-scoped not-found semantics and `all` handling.

File: pkg/lightning/checkpoints/checkpoints.go [hunk 3]
```diff
@@ -1676,9 +1676,25 @@ func (cpdb *MySQLCheckpointsDB) IgnoreErrorCheckpoint(ctx context.Context, table
...
+			if e != nil {
+				return errors.Trace(e)
+			}
+			if affectedRows == 0 {
+				found, e := cpdb.hasTableCheckpoint(c, tx, tableName)
+				if e != nil {
+					return errors.Trace(e)
+				}
+				if !found {
+					return common.CheckpointTableNotFoundError(tableName)
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply pkg/lightning/checkpoints/checkpoints.go]: Addressed in 3500bd0c72. Added consistent API contract wording for missing table checkpoints across checkpoint-control surfaces: `pkg/lightning/checkpoints.DB` (`IgnoreErrorCheckpoint`, `DestroyErrorCheckpoint`) and both legacy/import-into wrappers in `lightning/pkg/server/checkpoint_control.go`.

File: lightning/pkg/importinto/checkpoint.go [hunk 4]
```diff
@@ -464,8 +472,24 @@ func (m *MySQLCheckpointManager) IgnoreError(ctx context.Context, tableName stri
...
-	return errors.Trace(err)
+	result, err := m.db.ExecContext(ctx, query, CheckpointStatusPending, tableName, CheckpointStatusFailed)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	affectedRows, err := result.RowsAffected()
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if affectedRows == 0 {
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply lightning/pkg/importinto/checkpoint.go:489]: Addressed in 3500bd0c72. Extracted `ensureTableCheckpointExists` in `MySQLCheckpointManager` and reused it in both `IgnoreError` and `DestroyError` single-table paths, so the checkpoint existence probing and not-found mapping are centralized.

File: lightning/pkg/server/checkpoint_control.go [hunk 5]
```diff
@@ -92,13 +92,19 @@ func (c *LegacyCheckpointControl) Remove(ctx context.Context, tableName string)
 }
 
 // IgnoreError marks failed checkpoints as pending so they can be resumed.
+// tableName accepts `all` or `db`.`table`. A table-scoped call returns
+// an error matching common.ErrCheckpointTableNotFound when the target
+// checkpoint does not exist.
```
Comment (joechenrh) [inline lightning/pkg/server/checkpoint_control.go:97]: Too many duplicated comment blocks, do we really need them at every place

File: pkg/lightning/checkpoints/checkpoints.go
Comment (joechenrh) [inline pkg/lightning/checkpoints/checkpoints.go:2058]:
```suggestion
    if targetTableName == allTables && len(targetTables) == 0 {
        return nil, common.ErrCheckpointTableNotFound.GenWithStackByArgs(targetTableName)
    }
	// Delete the checkpoints
```

Comment (D3Hunter) [reply pkg/lightning/checkpoints/checkpoints.go:2055]: no need to do this for `all`, it's possible be empty

File: lightning/pkg/server/checkpoint_control.go (hunk 5 above)
Comment (D3Hunter) [reply lightning/pkg/server/checkpoint_control.go]: Deduplicated the repeated table-name/not-found comment blocks from the concrete checkpoint-control methods and kept the shared contract on the checkpoint interfaces.

**Review by joechenrh — APPROVED** [review]

File: pkg/lightning/checkpoints/checkpoints.go [hunk 6]
```diff
@@ -1923,17 +1971,30 @@ func (cpdb *FileCheckpointsDB) IgnoreErrorCheckpoint(_ context.Context, targetTa
...
+					engineModel.Status = uint32(CheckpointStatusLoaded)
+				}
+			}
+		}
+		return errors.Trace(cpdb.save())
+	}
+
+	tableModel, ok := cpdb.checkpoints.Checkpoints[targetTableName]
+	if !ok {
+		return common.ErrCheckpointTableNotFound.GenWithStackByArgs(targetTableName)
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply pkg/lightning/checkpoints/checkpoints.go:1990]: we don't expect user to upgrade in place for existing import

**Comment by lance6716** [comment]
@D3Hunter sorry I'm busy this week. I think I don't have enough time to review if it's an urgent PR

File: lightning/pkg/importinto/checkpoint.go [hunk 7]
```diff
@@ -261,7 +264,11 @@ func (m *FileCheckpointManager) IgnoreError(ctx context.Context, tableName strin
 			}
 		}
 	} else {
-		if cp, ok := m.checkpoints[tableName]; ok && cp.Status == CheckpointStatusFailed {
+		cp, ok := m.checkpoints[tableName]
+		if !ok {
+			return common.ErrCheckpointTableNotFound.GenWithStackByArgs(tableName)
```
Comment (OliverS929) [inline lightning/pkg/importinto/checkpoint.go:269]: Is `tidb-lightning-ctl` expected to support checkpoint operations for `tikv-importer.backend = import-into`? If so, this new not-found check may expose a control-path initialization gap: `ImportIntoCheckpointControl` creates the import-into checkpoint manager but does not call `Initialize`, while the normal importer path does.

Comment (D3Hunter) [reply lightning/pkg/importinto/checkpoint.go:269]: just align the behavior, we don't change the existing logic related to `Initialize`

**Review by OliverS929 — APPROVED** [review]
