### PR TITLE
expression, types: freeze unsafe datetime warning args

### LINKED ISSUE #56311: flaky test TestIssue48756
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
     result.go:49: 
        	Error Trace:	pkg/testkit/result.go:49
        	            				pkg/executor/test/executor/executor_test.go:3002
        	Error:      	Not equal: 
        	            	expected: "[Warning 1292 Incorrect time value: '120120519090607']\n[Warning 1105 ]\n"
        	            	actual  : "[Warning 1292 Incorrect time value: '1 1:1:1.0000027']\n[Warning 1105 ]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-[Warning 1292 Incorrect time value: '120120519090607']
        	            	+[Warning 1292 Incorrect time value: '1 1:1:1.0000027']
        	            	 [Warning 1105 ]
        	Test:       	TestIssue48756
        	Messages:   	sql:show warnings, args:[] 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/56194/fast_test_tiprow/1838871558488068096#1:build-log.txt%3A3676

### LINKED ISSUE #65231: flaky test TestIssue48756
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
The test branch is the master branch, and Go 1.25 is used. （https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/pull_unit_test_next_gen/6689/）
```
executor_test.go:2539: 
        	Error Trace:	pkg/executor/test/executor/executor_test.go:2539
        	Error:      	Not equal: 
        	            	expected: "Incorrect time value: '120120519090607'"
        	            	actual  : "Incorrect time value: '201205190906077'"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-Incorrect time value: '120120519090607'
        	            	+Incorrect time value: '201205190906077'
        	Test:       	TestIssue48756/TryCopLiteWorker=1
        	Messages:   	expected error message
```

### LINKED ISSUE #66834: expression: SUBTIME warning text can be corrupted by unsafe chunk string alias reuse
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is related to flaky `TestIssue48756` reports in #56311 and #65231, but the root cause is a production diagnostics bug (warning text corruption), not SQL semantics nondeterminism.

#### CI evidence

In CI run `pull_unit_test_next_gen/runs/12299`, one failing attempt showed:
- expected: `Incorrect time value: '120120519090607'`
- actual: `Incorrect time value: '1 1:1:1.0000027'`

Same run later passed, confirming flakiness.

References:
- node 54 log: https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/pull_unit_test_next_gen/runs/12299/nodes/54/log/?start=0
- artifact: `bazel-target-output-L2163-2806.log`

#### Local reproduction (unit test with failpoint)

```bash
make failpoint-enable
pushd pkg/executor/test/executor
go test -run 'TestIssue48756/TryCopLiteWorker=0' -count=40 -tags=intest,deadlock
go test -run 'TestIssue48756/TryCopLiteWorker=1' -count=40 -tags=intest,deadlock
popd
make failpoint-disable
```

Observed warning text flipping to wrong values including:
- `Incorrect time value: '1 1:1:1.0000027'`
- `Incorrect time value: '201205190906077'`

#### Real cluster reproduction (TiUP playground)

```bash
tiup playground --mode tikv-slim --tag codex-repro --without-monitor --db 1 --kv 1 --pd 1 --port-offset 13000
```

Connected to `127.0.0.1:17000` (TiDB `v8.5.5`).

```sql
use test;
drop table if exists t;
create table t (id int, a varbinary(20), b bigint);
insert into t values
  (1, _binary '2012-05-19 09:06:07', 20120519090607),
  (1, _binary '2012-05-19 09:06:07', 20120519090607),
  (2, _binary '12012-05-19 09:06:07', 120120519090607),
  (2, _binary '12012-05-19 09:06:07', 120120519090607);
```

Loop this:

```sql
SELECT SUBTIME(BIT_OR(b), '1 1:1:1.000002') FROM t GROUP BY id ORDER BY id;
SHOW WARNINGS;
```

Observed mismatch quickly:
- iteration 102: `Incorrect time value: '1 1:1:1.0000027'`
- expected: `Incorrect time value: '120120519090607'`

Sample failing output:

```text
2012-05-18 08:05:05.999998
NULL
Warning 1292 Incorrect time value: '1 1:1:1.0000027'
```

Stress result (1000 iterations):
- 553 mismatches total
- 552 times: `Incorrect time value: '1 1:1:1.0000027'`
- 1 time: `Incorrect time value: '201205190906077'`

### 2. What did you expect to see? (Required)

`SHOW WARNINGS` should consistently report the real offending value for the row:
- `Incorrect time value: '120120519090607'`

### 3. What did you see instead (Required)

Warning message text is nondeterministic/corrupted and can show unrelated values from reused memory:
- `Incorrect time value: '1 1:1:1.0000027'`
- `Incorrect time value: '201205190906077'`

In this repro, query result rows themselves look correct; the defect is primarily diagnostics correctness.

#### Root cause analysis

1. `chunk` string access is unsafe/zero-copy:
   - `pkg/util/chunk/column.go` (`GetString` returns `string(hack.String(...))`, aliasing mutable chunk memory)
2. Vectorized `SUBTIME` path consumes those aliased strings:
   - `pkg/expression/builtin_time_vec_generated.go` (`arg0 := buf0.GetString(i)`, `arg1 := buf1.GetString(i)`)
3. String datetime subtraction appends parse warning:
   - `pkg/expression/builtin_time.go` (`strDatetimeSubDuration` -> `tc.AppendWarning(err)`)
4. Error args are stored by reference and rendered later:
   - `github.com/pingcap/errors/normalize.go` (`GenWithStackByArgs` stores args; formatting deferred)

Because chunk backing memory is reused, warning args can be overwritten before final formatting.

#### Production impact

Mainly diagnostics correctness:
1. `SHOW WARNINGS` / client warning text may be wrong or nondeterministic.
2. Troubleshooting and observability become misleading.
3. Apps parsing warning strings may mis-handle logic.
4. Potential low-grade same-statement value confusion in warning payloads.

Likely not impacting data consistency/transaction semantics/plan choice in this case.

### 4. What is your TiDB version? (Required)

Reproduced on a real TiUP playground cluster:
- TiDB `v8.5.5`
- endpoint `127.0.0.1:17000`

(Related open PR: #65577)

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #66834, close #56311, close #65231

Problem Summary:

`SUBTIME`/`ADDTIME` warning texts can become nondeterministic when the datetime input string comes from chunk-backed zero-copy memory. The warning message is formatted later, after chunk buffers may be reused, so the error argument can be corrupted and flaky tests appear as random warning values.

in https://github.com/pingcap/errors/pull/82, we support freeze string args

### What changed and how does it work?

1. Add string wrappers in `pkg/types`:
   - `types.PlainStr` for normal stable strings.
   - `types.HackedStr` for potentially aliased/unsafe strings; it implements `FreezeStr()` so `pingcap/errors` can snapshot arguments.
2. Add `types.ParseTimeWithString` and route internal datetime parse paths to accept `types.String` wrappers.
3. Update warning/error-producing datetime parse paths (`parseDatetime`, timestamp DST adjustment) to pass wrapped string args instead of raw strings.
4. Switch `strDatetimeAddDuration` and `strDatetimeSubDuration` to call `ParseTimeWithString(..., types.HackedStr(d), ...)`, so warnings generated from chunk-backed inputs are frozen.
5. Add regression test `TestStrDatetimeAddDurationFreezesWarningArg` to verify warning args do not mutate after backing buffer rewrite.
6. Bump `github.com/pingcap/errors` to `v0.11.5-0.20260310054046-9c8b3586e4b2` (includes hacked-string freezing support) and sync Bazel metadata.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Manual verification steps:

```bash
# Unit (failpoint package)
make failpoint-enable && (
  pushd pkg/expression >/dev/null
  go test -run TestStrDatetimeAddDurationFreezesWarningArg -tags=intest,deadlock
  popd >/dev/null
); rc=$?; make failpoint-disable; exit $rc

# Required for go.mod/go.sum changes
make bazel_prepare

# Repo required lint
make lint

# Real cluster verification
make server
tiup playground nightly --mode tikv-slim --tag codex-verify-errors-freeze --without-monitor --db 1 --kv 1 --pd 1 --port-offset 13000 --db.binpath ./bin/tidb-server --db.timeout 60
# Then run SQL setup and 1000-loop warning check against 127.0.0.1:17000
```

Real cluster result:
- 1000 iterations, `mismatch_count=0`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix nondeterministic `SUBTIME`/`ADDTIME` warning text caused by chunk-backed string alias reuse by freezing unsafe string arguments in datetime parse warnings.
```

## Summary by CodeRabbit

* **New Features**
  * Safer time parsing with a new string-abstraction and a string-based ParseTime API.

* **Bug Fixes**
  * Datetime-related warnings now remain stable even if input buffers are mutated.
  * Improved error reporting from background tasks to avoid lost late errors.

* **Tests**
  * Added tests to verify frozen warning arguments and updated timing/GC-related test checks.

* **Chores**
  * Updated several dependencies, including error and testing libraries.

### CODE REVIEW

File: pkg/expression/builtin_time.go [hunk 1]
```diff
@@ -4821,7 +4821,7 @@ func isDuration(str string) bool {
 
 // strDatetimeAddDuration adds duration to datetime string, returns a string value.
 func strDatetimeAddDuration(tc types.Context, d string, arg1 types.Duration) (result string, isNull bool, err error) {
-	arg0, err := types.ParseTime(tc, d, mysql.TypeDatetime, types.MaxFsp)
+	arg0, err := types.ParseTimeWithString(tc, types.HackedStr(d), mysql.TypeDatetime, types.MaxFsp)
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply pkg/expression/builtin_time.go:4824]: there are many such callings, but let's focus on those 2 in this pr, we can do others later

**Review by windtalker — APPROVED** [review]
lgtm

File: pkg/util/gctuner/memory_limit_tuner_test.go [hunk 2]
```diff
@@ -153,6 +153,7 @@ func TestIssue48741(t *testing.T) {
 		require.Eventually(t,
 			// Wait for the GC triggered by memory810mb
 			func() bool {
+				runtime.GC()
```
Comment (D3Hunter) [inline pkg/util/gctuner/memory_limit_tuner_test.go:156]: Adding `runtime.GC()` here makes this polling deterministic. After dependency updates (especially `testify` timing behavior), this test no longer always gets enough GC opportunities within the original wait window, causing flakes/timeouts even when tuner logic is correct.

File: pkg/ddl/index.go [hunk 3]
```diff
@@ -1507,7 +1507,9 @@ func (w *worker) analyzeTableInner(job *model.Job, tblInfo *model.TableInfo, dbN
 			w.ddlCtx.setAnalyzeStartTime(job.ID, time.Now())
 		}
 
-		doneCh = make(chan error)
+		// Use a buffered channel so analyze goroutine can always report an error
+		// even after caller has timed out and moved on.
+		doneCh = make(chan error, 1)
```
Comment (D3Hunter) [inline pkg/ddl/index.go:1512]: This channel is now buffered to prevent a latent goroutine leak when `AnalyzeStateRunning` times out before the async ANALYZE finishes. In that race, the caller moves on via `AnalyzeStateTimeout`, so no receiver remains on `doneCh`; an unbuffered `doneCh <- err` blocks forever, defers never run (`sessPool.Put` is skipped), and DDL shutdown can hang in `session_pool.Close()`. A size-1 buffer preserves existing semantics while guaranteeing the sender can complete and release resources.

File: br/pkg/streamhelper/advancer_test.go [hunk 4]
```diff
@@ -689,6 +689,9 @@ func TestUnregisterAfterPause(t *testing.T) {
 	c.advanceClusterTimeBy(1 * time.Minute)
 	require.Error(t, adv.OnTick(ctx), "checkpoint is lagged")
 	env.unregisterTask()
+	require.Eventually(t, func() bool {
```
Comment (D3Hunter) [inline br/pkg/streamhelper/advancer_test.go:697]: Added an explicit wait for `!adv.HasTask()` before re-adding the task so this test cannot pass `Eventually` on stale task state after the testify timing change.

**Review by Leavrth — APPROVED** [review]
