### PR TITLE
executor, types: fix skipped replace when the value is treated as the same in CI collations

### LINKED ISSUE #20840: Replace should not skip with ci collation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Set `new_collations_enabled_on_first_bootstrap` to true in config file before tidb-server bootstrapped.
```
 MySQL  127.0.0.1:4000  test  SQL > set tidb_enable_clustered_index = 0;
Query OK, 0 rows affected (0.0003 sec)
 MySQL  127.0.0.1:4000  test  SQL > create table t1 (i varchar(20) unique key) collate=utf8mb4_general_ci;
Query OK, 0 rows affected (0.0239 sec)
 MySQL  127.0.0.1:4000  test  SQL > insert into t1 values ('a');
Query OK, 1 row affected (0.0025 sec)
 MySQL  127.0.0.1:4000  test  SQL > replace into t1 values ('A');
Query OK, 2 rows affected (0.0011 sec)
 MySQL  127.0.0.1:4000  test  SQL > select * from t1;
```

### 2. What did you expect to see? (Required)
```
 MySQL  127.0.0.1:4000  test  SQL > select * from t1;
+---+
| i |
+---+
| A |
+---+
```

### 3. What did you see instead (Required)
```
 MySQL  127.0.0.1:4000  test  SQL > select * from t;
+---+
| i |
+---+
| a |
+---+
```

### 4. What is your TiDB version? (Required)
09c941fd8cec4af5bafd4d0481c26babe755bdb0

## Score

- 300

## Mentor

- @wjhuang2016

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #20840  

Problem Summary:

### What is changed and how it works?

What's Changed:
Fix skipped update when the value is treated as the same in CI collations
How it Works:
Use binary collation to compare datum.
### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

File: types/datum.go [hunk 1]
```diff
@@ -1930,7 +1930,11 @@ func EqualDatums(sc *stmtctx.StatementContext, a []Datum, b []Datum) (bool, erro
 		return false, nil
 	}
 	for i, ai := range a {
+		collation := ai.Collation()
```
Comment (bb7133) [inline types/datum.go:1933]: I'm a little surprised that `EqualDatum` is only used by `REPLACE INTO`. That's why the change here does not break anything else.

I would suggest moving `EqualDatum` to 'replace.go' and make it a private function so that `EqualDatum` will not be used in an incorrect way.

File: executor/replace_test.go [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+package executor_test
+
+import (
+	. "github.com/pingcap/check"
+	"github.com/pingcap/tidb/util/collate"
+	"github.com/pingcap/tidb/util/testkit"
+)
+
+func (s *testSerialSuite) TestIssue20849(c *C) {
```
Comment (bb7133) [inline executor/replace_test.go:22]: Can you move this to the `write_test.go`? I saw many existing tests about `REPLACE INTO` are there.

File: types/datum.go (hunk 1 above)
Comment (TszKitLo40) [reply types/datum.go:1933]: What about the tests of `EqualDatums`? Should we also move them to `write_test.go`?

Comment (TszKitLo40) [reply types/datum.go:1933]: `EqualDatums` is also used in `flamegrapth_test.go`

Comment (bb7133) [reply types/datum.go:1933]: > What about the tests of EqualDatums? Should we also move them to write_test.go?

Yes, that's reasonable if is used by `REPLACE INTO` only.

> EqualDatums is also used in flamegrapth_test.go

I think it can be replaced with `CompareDatum`?

File: executor/replace.go [hunk 3]
```diff
@@ -89,6 +91,33 @@ func (e *ReplaceExec) removeRow(ctx context.Context, txn kv.Transaction, handle
 	return false, nil
 }
 
+// EqualDatums compare if a and b contains the same datum values.
+func (e *ReplaceExec) EqualDatums(sc *stmtctx.StatementContext, a []types.Datum, b []types.Datum) (bool, error) {
```
Comment (bb7133) [inline executor/replace.go:95]: How about renaming it to, say, like `EqualDatumsIgnoreCollation` or `EqualDatumsAsBinary`, and update the comment, so that it is more straightforward to the other developers?

**Comment by bb7133** [comment]
PTAL @wjhuang2016 @jackysp @coocood

File: executor/replace.go [hunk 4]
```diff
@@ -89,6 +91,33 @@ func (e *ReplaceExec) removeRow(ctx context.Context, txn kv.Transaction, handle
...
+	if len(a) != len(b) {
+		return false, nil
+	}
+	if a == nil && b == nil {
```
Comment (coocood) [inline executor/replace.go:99]: We better not check nil for slice type because it's very common we mix the use of nil slice and not-nil zero len slice.

File: executor/replace.go [hunk 5]
```diff
@@ -89,6 +91,33 @@ func (e *ReplaceExec) removeRow(ctx context.Context, txn kv.Transaction, handle
...
+		return true, nil
+	}
+	if a == nil || b == nil {
```
Comment (coocood) [inline executor/replace.go:102]: The two nil-slice check can be simply removed.

File: executor/replace.go (hunk 3 above)
Comment (TszKitLo40) [reply executor/replace.go]: I have renamed it to `EqualDatumsAsBinary`.

**Comment by coocood** [comment]
LGTM

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
