### PR TITLE
ddl: fix unexpect fail when create expression index

### LINKED ISSUE #39784: [planner:1054]Unknown column 'test.t2.name' in 'expression'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
CREATE TABLE `t2` (
`id` int(11) NOT NULL AUTO_INCREMENT ,
`name` varchar(30) DEFAULT NULL ,
`create_time` datetime NOT NULL ,
PRIMARY KEY (`id`) ,
KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
```
create index idx_t2_name on test.t2((lower(test.t2.name)));
```

### 2. What did you expect to see? (Required)
create index success
### 3. What did you see instead (Required)
1. ["[ddl] run DDL job error"] [worker="worker 8, tp add index"] [error="[planner:1054]Unknown column 'test.t2.name' in 'expression'"]
2. can't cancel create ddl job success.
3. we could use different index name create same column again.
### 4. What is your TiDB version? (Required)
v5.2.2, v6.4.0, master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #39784 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/backfilling.go [hunk 1]
```diff
@@ -805,12 +806,21 @@ func (b *backfillScheduler) Close() {
...
 	job := reorgInfo.Job
 	totalAddedCount := job.GetRowCount()
 
 	startKey, endKey := reorgInfo.StartKey, reorgInfo.EndKey
 	sessCtx := newContext(reorgInfo.d.store)
+	m, err := sess.Txn(true)
+	if err != nil {
+		return err
+	}
+	dbInfo, err := meta.NewMeta(m).GetDatabase(job.SchemaID)
```
Comment (zimulala) [inline ddl/backfilling.go:819]: Could we put it to `onCreateIndex` which we needn't do more than once? It can be passed through `reorgInfo`. And we needn't `GetDatabase` in this background.

Comment (Defined2014) [reply ddl/backfilling.go:819]: This PR also has other problems, let me fix it.

Comment (Defined2014) [reply ddl/backfilling.go:819]: I think it should be fixed by https://github.com/pingcap/tidb/issues/39826

Comment (Defined2014) [reply ddl/backfilling.go]: Updated, opened another issue to trace rename issue, https://github.com/pingcap/tidb/issues/39826. PTAL  @zimulala

**Review by xhebox — APPROVED** [review]

**Review by zimulala — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
