### PR TITLE
planner: fix pessimistic-auto-commit not working for point plans

### LINKED ISSUE #39928: The queries in `autocommit` mode doesn't read with lock when pessimistic-auto-commit turned on
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE `sbtest3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `k` int(11) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) ,
  KEY `k_1` (`k`)
) 

-- session 1
begin;
insert into sbtest3 values(200002,111,"aaa","aaa");

-- session2
update sbtest3 set k = 222 where id = 200002;

### 2. What did you expect to see? (Required)
session2 is blocked because of lock wait.

### 3. What did you see instead (Required)
`Query OK, 0 rows affected (0.01 sec)
Rows matched: 0  Changed: 0  Warnings: 0`

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-1709-gafb5cf6-dirty
Edition: Community
Git Commit Hash: afb5cf652a2a0c383b2e36b584d5e744e012c210
Git Branch: longtail-diag
UTC Build Time: 2022-12-14 07:51:55
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

### What problem does this PR solve?

Issue Number: close #39928

Problem Summary: pessimistic-auto-commit doesn't work for point plans.

### What is changed and how it works?

check pessimistic-auto-commit config on building point plans.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/realtikvtest/pessimistictest/pessimistic_test.go [hunk 1]
```diff
@@ -3091,6 +3095,9 @@ func TestPessimisticAutoCommitTxn(t *testing.T) {
 	rows = tk.MustQuery("explain update t set i = -i").Rows()
 	explain = fmt.Sprintf("%v", rows[1])
 	require.Regexp(t, ".*SelectLock.*", explain)
+	rows = tk.MustQuery("explain update t set i = -i where i = -1").Rows()
```
Comment (cfzjywxk) [inline tests/realtikvtest/pessimistictest/pessimistic_test.go:3098]: We could also cover the batch point plans.

**Review by TonsnakeLin — APPROVED** [review]

File: tests/realtikvtest/pessimistictest/pessimistic_test.go (hunk 1 above)
Comment (zyguan) [reply tests/realtikvtest/pessimistictest/pessimistic_test.go:3102]: done

**Review by cfzjywxk — APPROVED** [review]
LGTM
