### PR TITLE
json: add json fuzz test for `json_extract` function and fix several bugs found by it | tidb-test=pr/2467

### LINKED ISSUE #37806: json float format should have extra `.0` if it's an integer
## Enhancement

Printing json `1.0` will get `1`, which is not expected. It should print `1.0`.

### LINKED ISSUE #58888: sometimes TiDB will return json float number without float point
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run the following SQL:

```
select json_extract("0.0", "$");
```

### 2. What did you expect to see? (Required)

```
mysql> select json_extract("0.0", "$");
+--------------------------+
| json_extract("0.0", "$") |
+--------------------------+
| 0.0                      |
+--------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select json_extract("0.0", "$");
+--------------------------+
| json_extract("0.0", "$") |
+--------------------------+
| 0                        |
+--------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
c199ddfcdf9e1f88a243c2b7847d8f3224446004
```

### LINKED ISSUE #58894: json float in scientific format is different with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
SELECT JSON_EXTRACT('[1E27]', '$')
```

### 2. What did you expect to see? (Required)

```
[1e27]
```

### 3. What did you see instead (Required)

```
[1e+27]
```

In `util.AppendFormatFloat`, TiDB provides a function to format a float in MySQL  compatible way. However, the json value doesn't use this function (because they actually have a little logic difference). We'd better to align the behavior between them.

### LINKED ISSUE #58895: TiDB accepts special character as json path leg, but MySQL doesn't
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
SELECT json_extract("[1E27]", "$.ѿ")
```

### 2. What did you expect to see? (Required)

```
ERROR 3143 (42000): Invalid JSON path expression. The error is around character position 4.
```

### 3. What did you see instead (Required)

```
mysql> select json_extract("[1E27]", "$.ѿ");
+--------------------------------+
| json_extract("[1E27]", "$.ѿ")  |
+--------------------------------+
| NULL                           |
+--------------------------------+
1 row in set (0.03 sec)
```

In MySQL document, it says the key name must be `ESIdentifier | doubleQuotedString`. The `doubleQuotedString` accepts special character, but `ESIdentifier` not.

### LINKED ISSUE #58896: slice bounds out of range for special json path
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select json_extract("{}", "$.\"\\0\\");
```

### 2. What did you expect to see? (Required)

```
mysql> select json_extract("{}", "$.\"\\0\\");
ERROR 3143 (42000): Invalid JSON path expression. The error is around character position 6.
```

### 3. What did you see instead (Required)

```
mysql> select json_extract("{}", "$.\"\\0\\");
ERROR 1105 (HY000): runtime error: slice bounds out of range [:7] with length 6
```

### LINKED ISSUE #58897: json key format with `\b`, `\f` is not compatible with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select json_extract("{\"\\b\":\"\"}", "$");
```

### 2. What did you expect to see? (Required)

```
mysql> select json_extract("{\"\\b\":\"\"}", "$");
+-------------------------------------+
| json_extract("{\"\\b\":\"\"}", "$") |
+-------------------------------------+
| {"\b": ""}                          |
+-------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select json_extract("{\"\\b\":\"\"}", "$");
+-------------------------------------+
| json_extract("{\"\\b\":\"\"}", "$") |
+-------------------------------------+
| {"\u0008": ""}                      |
+-------------------------------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #58897, close #58896, close #58895, close #58894, close #58888, close #37806

Problem Summary:

This PR adds a fuzz test for `json_extract` function and fix several bugs found by it.

### What changed and how does it work?

1. Add a fuzz test for `json_extract`.
2. Modify the behavior of `jsonMarshalStringTo` to specially handle the `\b` and `\f`.
3. Fix the json path parser by using `[]rune` to make sure we have correct unicode behavior.
4. Fix the scientific notation of float value.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by YangKeao** [comment]
TODO: also test these cases for TiKV.

**Comment by Defined2014** [comment]
> TODO: also test these cases with TiKV.

Integration test also run on TiKV env.

File: pkg/types/json_binary.go [hunk 1]
```diff
@@ -330,6 +330,9 @@ func (bj BinaryJSON) valEntryGet(valEntryOff int) BinaryJSON {
 
 func (bj BinaryJSON) marshalFloat64To(buf []byte) ([]byte, error) {
 	// NOTE: copied from Go standard library.
+	// TODO: this function is vary similar to `util.AppendFormatFloat`, it'd be better to unify them.
```
Comment (Defined2014) [inline pkg/types/json_binary.go:333]:
```suggestion
	// TODO: this function is very similar to `util.AppendFormatFloat`, it'd be better to unify them.
```

File: pkg/types/json_path_expr_test.go [hunk 2]
```diff
@@ -17,6 +17,7 @@ package types
 import (
 	"testing"
 
+	_ "github.com/go-sql-driver/mysql"
```
Comment (Defined2014) [inline pkg/types/json_path_expr_test.go:20]: Do we need import this library here?

File: pkg/types/json_binary.go (hunk 1 above)
Comment (YangKeao) [reply pkg/types/json_binary.go]: Fixed.

**Comment by YangKeao** [comment]
> > TODO: also test these cases with TiKV.
> 
> Integration test also run on TiKV env.

@Defined2014  For the added case, they are not pushed down to TiKV. It's possible to re-write these SQLs to push down, but I think it's better to manually check the TiKV side.

After all, TiKV side is not related to this PR. No matter whether it has these bugs or not, there will be another PR for it (in `tikv/tikv`).

File: pkg/types/json_path_expr_test.go (hunk 2 above)
Comment (YangKeao) [reply pkg/types/json_path_expr_test.go:20]: Yes. It asserts that the result between `MySQL` and tidb internal functions are the same. Without it, it cannot tell whether a result is correct.

Comment (Defined2014) [reply pkg/types/json_path_expr_test.go:20]: Should it added in `json_binary_test.go` file?

File: tests/integrationtest/r/expression/builtin.result [hunk 3]
```diff
@@ -713,7 +713,7 @@ create table tb5(a json, b bigint unsigned);
 insert into tb5 (a, b) values ('184467440737095516160', 18446744073709551615);
 select * from tb5 where cast(a as unsigned int)=b;
 a	b
-184467440737095500000	18446744073709551615
+1.844674407370955e20	18446744073709551615
```
Comment (YangKeao) [inline tests/integrationtest/r/expression/builtin.result:716]: It's not a behavior change, but I found it's not compatible with MySQL :thinking:. Record in https://github.com/pingcap/tidb/issues/58901.

File: pkg/types/json_path_expr_test.go (hunk 2 above)
Comment (YangKeao) [reply pkg/types/json_path_expr_test.go]: You are right :facepalm: . It's a mistake. I moved the tests from `json_path_expr_test.go` to `json_binary_test.go` and forgot to modify the `import`.

It's fixed now.

**Review by Defined2014 — APPROVED** [review]

File: tests/integrationtest/r/expression/issues.result [hunk 4]
```diff
@@ -1347,7 +1347,7 @@ select col, count(1) c from tx2 group by col order by c desc;
 col	c
 [922337203685477581]	5
 ["3"]	4
-[3]	3
+[3.0]	3
```
Comment (Defined2014) [inline tests/integrationtest/r/expression/issues.result:1350]: Seems it's not same on TiKV env, so `check_dev2` failed. :(

Comment (YangKeao) [reply tests/integrationtest/r/expression/issues.result:1350]: It's indeed caused by aggregation, and I think it's somehow expected. The `[3.0]` and `[3]` are aggregated into the same group, so it's expected that the `firstrow` may pick any one of them. The MySQL itself has a non-strict order:

```sql
mysql> create table tx2(j json);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into tx2 values ('[3.0]'), ('[3]');
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select j from tx2 group by j;
+-------+
| j     |
+-------+
| [3.0] |
+-------+
1 row in set (0.00 sec)

mysql> delete from tx2;
Query OK, 2 rows affected (0.00 sec)

mysql> insert into tx2 values ('[3]'), ('[3.0]');
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select j from tx2 group by j;
+------+
| j    |
+------+
| [3]  |
+------+
1 row in set (0.00 sec)
```

Previously, we also have the same issue, but the TiDB will print `3.0` as `3`, so the test didn't expose it :thinking:. Let me think whether (and how) to rewrite this test.

File: tests/integrationtest/t/expression/issues.test [hunk 5]
```diff
@@ -856,7 +856,7 @@ insert into tx2 values (json_array(922337203685477581)),(json_array(922337203685
 #
 # ordering by a JSON col is not supported in MySQL, and the order is a bit questionable in TiDB.
 # sort by count for test result stability.
-select col, count(1) c from tx2 group by col order by c desc;
+select max(cast(col as char)) j, count(1) c from tx2 group by col order by c desc;
```
Comment (YangKeao) [inline tests/integrationtest/t/expression/issues.test:859]: @Defined2014 PTAL. Now it should have a stable result.

File: tests/integrationtest/r/expression/issues.result (hunk 4 above)
Comment (YangKeao) [reply tests/integrationtest/r/expression/issues.result]: > Maybe use `--replace_regex` comment to rewrite it.

It sounds better. I'll do it.

File: tests/integrationtest/t/expression/issues.test (hunk 5 above)
Comment (YangKeao) [reply tests/integrationtest/t/expression/issues.test:859]: Revert

**Review by xhebox — APPROVED** [review]
