### PR TITLE
*: fix revoke statement for CURRENT_USER() and refine error message

### LINKED ISSUE #23850: REVOKE ALL fails on current user
## Bug Report

This was discovered by running mysql-test against TiDB. A user should have permission to revoke privileges from themselves as long as they have `CREATE USER` granted.

This fails in TiDB because `ALL` is expanded into the all privileges mask + Grant priv.

It also fails in the case that the privilege check is met (u4).

### 1. Minimal reproduce step (Required)

```
CREATE USER u1;
GRANT ALL ON *.* TO u1;
CREATE USER u2;
GRANT SELECT ON *.* to u2;
CREATE USER u3;
GRANT SELECT, CREATE USER ON *.* to u3;
CREATE USER u4;
GRANT ALL ON *.* TO u4 WITH GRANT OPTION;

$ mysql -u u1 # should work

SHOW GRANTS;
REVOKE ALL ON *.* FROM CURRENT_USER();

$ mysql -u u2 # should fail

SHOW GRANTS;
REVOKE ALL ON *.* FROM CURRENT_USER();

$ mysql -u u3 # should work

SHOW GRANTS;
REVOKE ALL ON *.* FROM CURRENT_USER();

$ mysql -u u4 # should work

SHOW GRANTS;
REVOKE ALL ON *.* FROM CURRENT_USER();
```

### 2. What did you expect to see? (Required)

```
mysql [localhost:8022] {u1} ((none)) > REVOKE ALL ON *.* FROM CURRENT_USER();
Query OK, 0 rows affected (0.00 sec)
..
mysql [localhost:8022] {u2} ((none)) > REVOKE ALL ON *.* FROM u2;
ERROR 1227 (42000): Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation
..
mysql [localhost:8022] {u3} ((none)) > REVOKE ALL ON *.* FROM CURRENT_USER();
Query OK, 0 rows affected (0.00 sec)
..
mysql [localhost:8022] {u4} ((none)) > REVOKE ALL ON *.* FROM CURRENT_USER();
Query OK, 0 rows affected (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> revoke all on *.* from current_user();
ERROR 8121 (HY000): privilege check fail

mysql> revoke all on *.* from current_user();
ERROR 8121 (HY000): privilege check fail

mysql> revoke all on *.* from current_user();
ERROR 8121 (HY000): privilege check fail

mysql> revoke all on *.* from current_user();
ERROR 1105 (HY000): Unknown user: @
```

### 4. What is your TiDB version? (Required)

```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-2561-g9c75cfa4e
Edition: Community
Git Commit Hash: 9c75cfa4e2bbb854ab90562ecec0409f84a989b0
Git Branch: master
UTC Build Time: 2021-04-02 18:50:29
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #23850   (Need to verify: The expected result is wrong?)

```
mysql> SHOW GRANTS;
+-----------------------------------------------------------+
| Grants for User                                           |
+-----------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'u4'@'%' WITH GRANT OPTION |
+-----------------------------------------------------------+
1 row in set (0.00 sec)

mysql> REVOKE ALL ON *.* FROM CURRENT_USER();
ERROR 1105 (HY000): Unknown user: @
```

Problem Summary:

The user name and host part for REVOKE ... FROM CURRENT_USER is missing.

### What is changed and how it works?

What's Changed:

Fill the user name and host part for CURRENT_USER.

How it Works:

Fix bug.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Fix 'REVOKE ... FROM CURRENT_USER()' statement. The host and username is not set for CURRENT_USER and that cause the statement fail.

### CODE REVIEW

File: privilege/privileges/privileges_test.go [hunk 1]
```diff
@@ -842,6 +842,12 @@ func (s *testPrivilegeSuite) TestRevokePrivileges(c *C) {
 	c.Assert(se.Auth(&auth.UserIdentity{Username: "hasgrant", Hostname: "localhost", AuthUsername: "hasgrant", AuthHostname: "%"}, nil, nil), IsTrue)
 	mustExec(c, se, "REVOKE SELECT ON mysql.* FROM 'withoutgrant'")
 	mustExec(c, se, "REVOKE ALL ON mysql.* FROM withoutgrant")
+
+	// For issue https://github.com/pingcap/tidb/issues/23850
+	mustExec(c, se, "CREATE USER u4")
```
Comment (bb7133) [inline privilege/privileges/privileges_test.go:847]: Could you add test cases for `u1`, `u2`, `u3` as shown in #23850?

**Comment by morgo** [comment]
> Issue Number: close #23850 (Need to verify: The expected result is wrong?)

I commented in the issue, but I got this out of the MTR tests for 8.0. I think it's fine to stay with 5.7 for now and fix it when we move to MySQL 8.0 compatibility. The current behavior is not neccessarily wrong.

I have another PR which fixes some other revoke bugs: https://github.com/pingcap/tidb/pull/23946 - the error messages are not technically MySQL compatible. I think we can create an issue after these merge and leave it for new contributors.

**Review by xhebox — APPROVED** [review]

**Comment by hi-rustin** [comment]
@xhebox  consistent failures. Could you please cancel the merge?

**Comment by xhebox** [comment]
/hold
Error message is changed, but tests are not updated, Working on it.

**Comment by tiancaiamao** [comment]
Why the CI is still using the old mysql-test branch?
