### PR TITLE
*: fix incorrect handling IterAllTables

### LINKED ISSUE #59912: IterAllTables may get wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Previously, we assumed that kv is in number order, so we split the subtask by 0-maxDBID.
But in fact, the kv is in string number. We splited the subtask in the wrong way.

### 2. What did you expect to see? (Required)
N/A

### 3. What did you see instead (Required)
N/A
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #59912

Problem Summary:
We used number order to split subtasks, which is wrong.

### What changed and how does it work?
Use string order to split subtasks.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/meta/meta.go [hunk 1]
```diff
@@ -998,21 +998,39 @@ func (m *Mutator) IterTables(dbID int64, fn func(info *model.TableInfo) error) e
...
+	// 9999999999999999999 is the max number than maxInt64 in string format.
+	batch := 9999999999999999999 / uint64(n)
+
+	for k := int64(0); k < n; k++ {
+		start := batch * uint64(k)
+		end := batch * uint64(k+1)
+
+		startStr := fmt.Sprintf("%019d", start)
+		if k == 0 {
+			startStr = "0"
```
Comment (joechenrh) [inline pkg/meta/meta.go:1013]: Why do we need to process 0 seperately

**Review by tangenta — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]
maybe consider distributions like Benford's law to output a more even KV range.
