### PR TITLE
disttask: merge transfer task/subtask

### LINKED ISSUE #50310: disttask: task will not transfer to history
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Suppose task is done(success/fail/reverted) but scheduler exists before we transter subtasks, then those subtasks are never transfered

### 2. What did you expect to see? (Required)
subtasks will be transfered to history table.
### 3. What did you see instead (Required)
subtasks kept in subtask table.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #48795 close #50310 

Problem Summary:

### What changed and how does it work?
merge transfer task and subtask.
Then call it in doCleanupTask periodically.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

File: pkg/disttask/framework/storage/task_table.go [hunk 1]
```diff
@@ -1115,8 +1115,8 @@ func (mgr *TaskManager) IsTaskCancelling(ctx context.Context, taskID int64) (boo
 	return len(rs) > 0, nil
 }
 
-// GetSubtasksForImportInto gets the subtasks for import into(show import jobs).
-func (mgr *TaskManager) GetSubtasksForImportInto(ctx context.Context, taskID int64, step proto.Step) ([]*proto.Subtask, error) {
+// GetSubtasksWithHistory gets the subtasks for import into(show import jobs).
```
Comment (ywqzzy) [inline pkg/disttask/framework/storage/task_table.go:1118]:
```suggestion
// GetSubtasksWithHistory gets the subtasks from tidb_global_task and tidb_global_task_history.
```

**Review by okJiang — APPROVED** [review]
