### PR TITLE
dml: fix the data/index inconsistency when updating partial index or using on dup key update

### LINKED ISSUE #65806: Partial Index fails to remove the index record when updating the condition column only
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (a int, b int, c int, primary key (a), key testidx(c) where b > 2);
insert into t values (1, 3, 1);
update t set b = 2 where a = 1;
```

The `UPDATE` will not remove the old partial index record.

### 2. What did you expect to see? (Required)

The old partial index record is removed and the index and data should be consistent.

### 3. What did you see instead (Required)

The data and index are not consistent.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #65806, #65819, #65823

Problem Summary:

1. If the `update` only modified the `AffectColumns` but don't touch `Columns`, it'll not remove the old partial index record.
2. `ON DUPLICATE KEY UPDATE` will also update the row when the new row actually doesn't match partial condition.
3. `ADMIN RECOVER` index will write index for all rows without considering partial index.

### What changed and how does it work?

1. Also check the `AffectColumns`. We should use a symmetry structure for both deleting and inserting for new index records.
2. Consider the condition for `ON DUPLICATE KEY UPDATE`.
3. Consider the condition for `ADMIN RECOVER`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/meta/model/index.go [hunk 1]
```diff
@@ -269,6 +269,12 @@ func (index *IndexInfo) Clone() *IndexInfo {
 	for i := range index.Columns {
 		ni.Columns[i] = index.Columns[i].Clone()
 	}
+	if index.AffectColumn != nil {
```
Comment (YangKeao) [inline pkg/meta/model/index.go:272]: Also clone the `AffectColumn`. As I know, it'll not have big issues for now (so no test), but I still added these lines to keep it clean.

File: pkg/executor/admin.go [hunk 2]
```diff
@@ -374,6 +374,18 @@ func (e *RecoverIndexExec) fetchRecoverRows(ctx context.Context, srcResult dists
 		}
 		iter := chunk.NewIterator4Chunk(e.srcChunk)
 		for row := iter.Begin(); row != iter.End(); row = iter.Next() {
+			// TODO: it's possible to push down the condition.
```
Comment (winoros) [inline pkg/executor/admin.go:388]: What does the pushdown here mean

Comment (YangKeao) [reply pkg/executor/admin.go:388]: Previously, it used a `TableScan` to read all rows to here, and then use these rows to recover the index.

It's possible to push down the partial condition into the scan request, so the TiKV can return less rows and accelerate the recovery.

File: pkg/executor/admin.go [hunk 3]
```diff
@@ -374,6 +374,18 @@ func (e *RecoverIndexExec) fetchRecoverRows(ctx context.Context, srcResult dists
...
+			if e.index.Meta().HasCondition() {
+				ok, err := e.index.MeetPartialConditionWithChunk(row)
+				if err != nil {
+					return nil, err
+				}
+				if !ok {
+					// Skip partial index not match row
+					continue
```
Comment (fzzf678) [inline pkg/executor/admin.go:398]: If all rows in one batch are skipped, the `result.scanRowCount` is `0`, the recovery process will be terminated by `backfillIndex`, the later rows won't be handled.
```
		// no more rows
		if result.scanRowCount == 0 {
			break
		}
```

Comment (fzzf678) [reply pkg/executor/admin.go:398]: Seems fixed

Comment (YangKeao) [reply pkg/executor/admin.go:398]: Got. Fixed. Now the rows ignored by partial condition will also increase the `scanRowCount`.

Comment (fzzf678) [reply pkg/executor/admin.go:398]: Seems we should also update the `result.currentHandle`

Comment (YangKeao) [reply pkg/executor/admin.go:398]: > Seems we should also update the result.currentHandle

Yes. Updated. Also added a test to show that it'll not cause infinite loop.

File: tests/integrationtest/t/table/tables.test [hunk 4]
```diff
@@ -27,4 +27,14 @@ set @@tidb_shard_allocate_step=default;
 drop table if exists t;
 create table t(a bit(32) default b'1100010001001110011000100100111');
 insert into t values ();
-select hex(a) from t;
\ No newline at end of file
+select hex(a) from t;
+
+# TestPartialIndexOnDuplicateKeyUpdateOrReplace
```
[the remark this answers is not in the document]
Comment (YangKeao) [reply tests/integrationtest/t/table/tables.test]: Done.
