### PR TITLE
server: remove prepare stmt if no retry in stmt close()

### LINKED ISSUE #20449: Prep stmt can not deallocate when receiving `COM_STMT_CLOSE`  in the transaction.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
When using Mydumper to backup TiDB, the `Prepare Statement Count` will grow very high.  I found that TiDB will not deallocate the ` Prep stmt ` when receiving `COM_STMT_CLOSE`  in the transaction.

Mydumper command ：
`/mydumper/mydumper -h 172.16.4.138 -u root -P 4000 -t 16 -o ../backup_test_mydumper_pingcap/ -r 2000 -v 3 `

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
Just like MySQL can deallocate  the ` Prep stmt ` when receiving `COM_STMT_CLOSE`  in transcation .

### 3. What did you see instead (Required)

<img width="916" alt="image" src="https://user-images.githubusercontent.com/20888467/95961823-2e23fd00-0e38-11eb-85ca-37aa83ecafbe.png">
<img width="635" alt="image" src="https://user-images.githubusercontent.com/20888467/95962033-72af9880-0e38-11eb-9087-5af24ee32168.png">

### 4. What is your TiDB version? (Required)
```sql
MySQL [sbtest]> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.19
Git Commit Hash: 7f2b1359a4829b571b1e7714088aebc216f6455a
Git Branch: heads/refs/tags/v3.0.19
UTC Build Time: 2020-09-25 06:23:33
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #20449 

Problem Summary:
Prepare statement count doesn't decrease quickly.

### What is changed and how it works?

Call RemovePreparedStmt if doesn't need to retry.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- fix a bug that the count of the prepare statement doesn't decrease properly.

### CODE REVIEW

**Review by jackysp — COMMENTED** [review]
I think we could remove the txn retry feature to make the logic more simple.
What do you think @coocood @tiancaiamao

**Comment by coocood** [comment]
> I think we could remove the txn retry feature to make the logic more simple.
> What do you think @coocood @tiancaiamao

+1

**Comment by wjhuang2016** [comment]
@jackysp @coocood @lysu PTAL

**Comment by coocood** [comment]
LGTM

**Comment by wjhuang2016** [comment]
@lysu @jackysp PTAL

File: server/driver_tidb.go [hunk 1]
```diff
@@ -149,9 +150,22 @@ func (ts *TiDBStatement) Reset() {
...
+		err := ts.ctx.DropPreparedStmt(ts.id)
+		if err != nil {
+			return err
+		}
+	} else {
+		if core.PreparedPlanCacheEnabled() {
+			preparedPointer := ts.ctx.GetSessionVars().PreparedStmts[ts.id]
+			preparedObj, ok := preparedPointer.(*core.CachedPrepareStmt)
+			if !ok {
+				return errors.Errorf("invalid CachedPrepareStmt type")
```
Comment (jackysp) [inline server/driver_tidb.go:163]: Could you use a pre-defined error for it?

**Review by jackysp — COMMENTED** [review]
rest LGTM

File: server/driver_tidb.go (hunk 1 above)
Comment (wjhuang2016) [reply server/driver_tidb.go:163]: There are 5 other usages, I think it's ok to keep it. To change all of them, it would be better to do it in another PR.

Comment (jackysp) [reply server/driver_tidb.go:163]: Ok.

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by lysu** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by lysu — COMMENTED** [review]
LGTM
