### PR TITLE
br: compatiblity of stats tables schema

### LINKED ISSUE #65362: need to update schema before rename system/stats tables if the backup schema is different from cluster schema.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. backup from the cluster 8.0
2. restore to the cluster 8.5

### 2. What did you expect to see? (Required)
the schema is updated
### 3. What did you see instead (Required)
the schema is not updated, need to use another way to update schema.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #65362

Problem Summary:
need to update schema before rename system/stats tables if the backup schema is different from cluster schema.
### What changed and how does it work?
check the schema itself instead of checking the version of cluster.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/snap_client/systable_schema_update.go [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+) error {
+	downstreamVersion := getSchemaVersionFromStatsMeta(downstreamTableInfo)
+	upstreamVersion := getSchemaVersionFromStatsMeta(upstreamTableInfo)
+	if downstreamVersion == InvalidVersion || upstreamVersion == InvalidVersion {
+		return errors.Errorf("invalid stats meta schema")
+	}
+	if downstreamVersion == upstreamVersion {
+		return nil
+	}
+	if downstreamVersion < upstreamVersion {
```
Comment (YuJuncen) [inline br/pkg/restore/snap_client/systable_schema_update.go:87]: Should we upgrade downstream to upstream version when its version is less than upstream instead of inverted?

File: br/pkg/restore/snap_client/systable_schema_update.go [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+	}
+)
+
+func getSchemaVersionFromStatsMeta(tableInfo *model.TableInfo) SchemaVersionType {
+	version := Version1
+	// version 1 -> version 2: add last_stats_histograms_version column
+	for _, columnInfo := range tableInfo.Columns {
+		if columnInfo.Name.L == "last_stats_histograms_version" {
+			version = Version2
+			break
```
Comment (YuJuncen) [inline br/pkg/restore/snap_client/systable_schema_update.go]: Consider directly `return Version2` here? Then we can `return Version1` at the end. The funciton now has less local state and can be more readable.

File: br/pkg/restore/snap_client/systable_schema_update.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/restore/snap_client/systable_schema_update.go:87]: This case is that the backup data is from high version (v8.5.5), and the restore cluster is low version (v7.5.6), so I think we can not upgrade the v7.5.6 system table schema to v8.5.5.

Comment (YuJuncen) [reply br/pkg/restore/snap_client/systable_schema_update.go:87]: LGTM
