### PR TITLE
br: use the dedicated grpc client for ingest

### LINKED ISSUE #50593: Br restore download SST throughput not stable throughout the whole restore process
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run br restore to restore a cluster of 110TB

### 2. What did you expect to see? (Required)
Download SST throughput should be use as much of the physical bandwidth as possible, and should be stable during the whole process.

### 3. What did you see instead (Required)
Download SST throughput can reach the disk throughtput limit (1200MB/s) sometime, but it is not stable enough,  there are some downgrade to 1GB or lower.
image
image

### 4. What is your TiDB version? (Required)
v7.6.0

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #50593 

Problem Summary:
slow ingest request pile up in the grpc connection, which leads to download requests blocken.
### What changed and how does it work?
use the dedicated grpc client for ingest
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/import.go [hunk 1]
```diff
@@ -113,23 +113,29 @@ type ImporterClient interface {
...
 type importClient struct {
-	mu         sync.Mutex
 	metaClient split.SplitClient
-	clients    map[uint64]import_sstpb.ImportSSTClient
-	tlsConf    *tls.Config
+	mu         sync.Mutex
+	// used for any request except the ingest reqeust
+	conns map[uint64]*grpc.ClientConn
+	// used for ingest request
+	ingestConns map[uint64]*grpc.ClientConn
```
Comment (YuJuncen) [inline br/pkg/restore/import.go:127]: Would you explain why ingest requests require isolated connections here?

File: br/pkg/restore/import.go [hunk 2]
```diff
@@ -240,12 +240,53 @@ func (ic *importClient) GetImportClient(
...
+		if err := conn.Close(); err != nil {
+			return errors.Trace(err)
+		}
+		delete(ic.conns, id)
+	}
+	for id, conn := range ic.ingestConns {
+		if err := conn.Close(); err != nil {
+			return errors.Trace(err)
+		}
+		delete(ic.ingestConns, id)
```
Comment (YuJuncen) [inline br/pkg/restore/import.go:287]: This doesn't require to acquire the lock?

File: br/pkg/restore/import.go [hunk 3]
```diff
@@ -240,12 +240,53 @@ func (ic *importClient) GetImportClient(
...
 	}
-	client = import_sstpb.NewImportSSTClient(conn)
-	ic.clients[storeID] = client
-	return client, errors.Trace(err)
+	conn, err := ic.createGrpcConn(ctx, storeID)
+	ic.conns[storeID] = conn
+	return import_sstpb.NewImportSSTClient(conn), errors.Trace(err)
+}
+
+func (ic *importClient) GetIngestClient(
```
Comment (YuJuncen) [inline br/pkg/restore/import.go:261]: Maybe extract the duplicated code to a private function like:
```go
func (ic *importClient) cachedConnectionFrom(
	ctx context.Context,
	storeID uint64,
	caches map[uint64]*grpc.ClientConn,
) (import_sstpb.ImportSSTClient, error) {
	ic.mu.Lock()
	defer ic.mu.Unlock()
	conn, ok := caches[storeID]
	if ok {
		return import_sstpb.NewImportSSTClient(conn), nil
	}
	conn, err := ic.createGrpcConn(ctx, storeID)
	caches[storeID] = conn
	return import_sstpb.NewImportSSTClient(conn), errors.Trace(err)
}
```
and delegate the two functions `Get(Ingest|Import)Client` to it.

**Review by YuJuncen — COMMENTED** [review]
rest lgtm

File: br/pkg/restore/import.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/restore/import.go:127]: It seems that the grpc connection isn't closed when br task exits.
In the BRIE via SQL, I'm worried that it would be leak.

File: br/pkg/restore/import.go [hunk 4]
```diff
@@ -240,12 +242,55 @@ func (ic *importClient) GetImportClient(
...
+	defer ic.mu.Unlock()
+	conn, ok := caches[storeID]
+	if ok {
+		return import_sstpb.NewImportSSTClient(conn), nil
 	}
-	client = import_sstpb.NewImportSSTClient(conn)
-	ic.clients[storeID] = client
-	return client, errors.Trace(err)
+	conn, err := ic.createGrpcConn(ctx, storeID)
+	caches[storeID] = conn
```
Comment (3pointer) [inline br/pkg/restore/import.go:260]: maybe not cache the connection where err != nil

**Review by 3pointer — APPROVED** [review]
