### PR TITLE
executor: fix the issue that some extracted conditions are not used in information_schema

### LINKED ISSUE #55235: `constraint_name` condition is ignored in `KEY_COLUMN_USAGE`
This issue is similar to https://github.com/pingcap/tidb/issues/55156, and is introduced in https://github.com/pingcap/tidb/pull/54333.

I'd like to introduce a better way to test these functions :thinking: . It's really easy to make mistakes by not using one of the extracted conditions.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #55235

Problem Summary:

Some conditions are just not used in the retriever of information schema tables. This PR adds a test for them, and fixes these issues. These issues are introduced in https://github.com/pingcap/tidb/pull/54333.

No matter whether an extracted condition is used in the real implementation, the parent executor will not use it to run a `SELECTION` again, and that's why these issues appear. It's hard to ensure all the conditions are used correctly, so I added a test to automatically test these lines.

### What changed and how does it work?

1. Add a test to automatically generate tables and selecting rows in the information schema to see whether the condition behaves well.
2. Fix the case when the condition has no effect.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

```release-note
Fix the issue that some SELECT conditions have no effect for some tables in the information_schema.
```

### CODE REVIEW

**Comment by YangKeao** [comment]
ref https://github.com/pingcap/tidb/pull/55162.

Similar issue I fixed before.

File: pkg/planner/core/memtable_infoschema_extractor.go [hunk 1]
```diff
@@ -59,8 +59,7 @@ var extractableColumns = map[string][]string{
 	// See infoschema.statisticsCols for full columns.
 	// Used by InfoSchemaStatisticsExtractor and setDataForStatistics.
 	infoschema.TableStatistics: {
-		_tableSchema, _tableName,
```
Comment (YangKeao) [inline pkg/planner/core/memtable_infoschema_extractor.go:62]: `infoschema.TableStatistics` doesn't have `_tableSchema` column.

Comment (YangKeao) [reply pkg/planner/core/memtable_infoschema_extractor.go:62]: I'm wrong.

**Review by tangenta — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]
