### PR TITLE
execution: Fix issue 24439 Inconsistent error with MySQL for GRANT CREATE USER ON <specific db>.*

### LINKED ISSUE #24439: Inconsistent error with MySQL for GRANT CREATE USER ON <specific db>.*
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create user testuser@localhost;
grant create user on test.* to testuser@localhost;

### 2. What did you expect to see? (Required)

mysql> create user testuser@localhost;
Query OK, 0 rows affected (0.04 sec)

mysql> grant create user on test.* to testuser@localhost;
ERROR 1221 (HY000): Incorrect usage of DB GRANT and GLOBAL PRIVILEGES

### 3. What did you see instead (Required)

tidb> create user testuser@localhost;
Query OK, 0 rows affected (0.01 sec)

tidb> grant create user on test.* to testuser@localhost;
ERROR 1054 (42S22): Unknown column 'Create_user_priv' in 'field list'

### 4. What is your TiDB version? (Required)

tidb_version(): Release Version: v4.0.0-beta.2-2806-ga6ec081b8
Edition: Community
Git Commit Hash: a6ec081b82a5357a9688a98d4d3cca35c87eab75
Git Branch: HEAD
UTC Build Time: 2021-05-06 14:56:18
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #24439

Problem Summary: fix all error info about global privilege on DB GRANT.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
grant.go

How it Works:

judge scope before do DB GRANT

### Related changes
none

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- fix error info to promote compatipatibility  of mysql.

### CODE REVIEW

**Comment by bb7133** [comment]
Thanks for your contribution!

Please add some test cases for your change.

File: executor/grant.go [hunk 1]
```diff
@@ -473,6 +473,13 @@ func (e *GrantExec) grantDBLevel(priv *ast.PrivElem, user *ast.UserSpec, interna
 	if priv.Priv == mysql.UsagePriv {
 		return nil
 	}
+	globalOnlyPrivs := mysql.Privileges{mysql.ProcessPriv, mysql.ShowDBPriv, mysql.SuperPriv, mysql.CreateUserPriv, mysql.CreateTablespacePriv, mysql.ShutdownPriv, mysql.ReloadPriv, mysql.FilePriv, mysql.ReplicationClientPriv, mysql.ReplicationSlavePriv}
```
Comment (wshwsh12) [inline executor/grant.go:476]: Could we unexplicit define globalOnlyPrivs? Use AllGlobalPrivs and AllDBPrivs to get the result?

Comment (sylzd) [reply executor/grant.go:476]: I had tried AllGlobalPrivs and AllDBPrivs，but it's not match.  globalOnlyPrivs comes from mysql document and my practice.

**Comment by morgo** [comment]
Thanks for creating the parser PR! Let's get it to merge, and then you can update this PR to reference `mysql.StaticGlobalOnlyPrivs`.

For my comment on (2), I had just meant that because there is a new feature (Dynamic privileges) the list of `StaticGlobalOnlyPrivs` is actually likely to stay unchanged in future. This is because any new global-only will naturally be a dynamic privilege instead. It is not related to this work, just an observation that the list will be static.
