### PR TITLE
statistics: internal sql must have invalid stats

### LINKED ISSUE #61601: system table wrongly trigger the async load
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Image

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #61601

Problem Summary:

### What changed and how does it work?

Internal SQL has no stats. so ```xxxxStatsIsInvailed``` must get the invalid result. so now you directly return invalid when it is a internal sql.

Another major issue is that none of our estimation processes check whether it is a memory or system database (  IsMemOrSysDB  ) or if it is in restricted SQL mode (  InRestrictedSQL  ). This can lead to potential problems in certain checks. Further investigation of the relevant code is still needed.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

before the bugfix:

Image

after the bugfix:

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/column.go [hunk 1]
```diff
@@ -150,6 +150,10 @@ func ColumnStatsIsInvalid(colStats *Column, sctx planctx.PlanContext, histColl *
 		}()
 	}
 	if sctx != nil {
+		if sctx.GetSessionVars().InRestrictedSQL {
+			inValidForCollPseudo = true
```
Comment (AilinKid) [inline pkg/statistics/column.go:154]: This var setting is meaningless cuz we are ganna return

Comment (hawkingrei) [reply pkg/statistics/column.go:154]: It is for debugtrace. but I don't know whether the debugtrace is for the internal SQL.

**Review by qw4990 — APPROVED** [review]
