### PR TITLE
ddl: unify flag processing behaviors between add/modify columns

### LINKED ISSUE #19342: Cannot alter YEAR column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists x;
create table x(c year(4) comment 'xxx');
alter table x modify c year(4) not null;
```

### 2. What did you expect to see? (Required)

Altered c to remove its coment.

### 3. What did you see instead (Required)

```
8200 - Unsupported modify column: can't change unsigned integer to signed or vice versa, Time: 0.003000s
```

Notice that according to `SHOW CREATE TABLE`, the column `c` is *NOT* unsigned:

```sql
CREATE TABLE `x` (
  `c` year(4) DEFAULT NULL COMMENT 'xxx'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

### 4. What is your TiDB version? (Required)

v4.0.4

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #19342

Problem Summary: Modify/Add column statements will go on two different path of processing column definitions. This PR unify the processing on `Flag` by using one single `processColumnFlags` function. This actually reminds that there are also some different bahaviors on column options processing which may cause troubles.

### Check List

Tests

- Unit test
- Integration test

### Release note

- process column type in a common way when add/modify columns

### CODE REVIEW

File: ddl/db_test.go [hunk 1]
```diff
@@ -4213,6 +4213,18 @@ func (s *testDBSuite4) TestIssue9100(c *C) {
...
+func (s *testSerialDBSuite) TestProcessColumnFlags(c *C) {
+	// check `processColumnFlags()`
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test_db")
+	tk.MustExec("create table t(a year(4) comment 'xxx')")
+	defer s.mustExec(tk, c, "drop table t;")
+
+	tk.MustExec("alter table t modify a year(4)")
+
+	tk.MustExec("alter table t modify a year(4) not null")
```
Comment (AilinKid) [inline ddl/db_test.go:4225]: how about adding some test about type `bit `, `varchar`, `year` and column option like `zero fill`

Comment (wjhuang2016) [reply ddl/db_test.go:4225]: Please add the case `alter table t modify a year(4) signed` and `alter table t modify a year(4) unsigned`

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: ddl/db_test.go [hunk 2]
```diff
@@ -4213,6 +4213,26 @@ func (s *testDBSuite4) TestIssue9100(c *C) {
...
+
+	tk.MustExec("alter table t modify a year(4) signed")
+
+	tk.MustExec("alter table t modify a year(4) unsigned")
+
+	tk.MustExec("alter table t modify a year(4) zerofill")
+
+	tk.MustExec("alter table t modify b year")
+
+	tk.MustExec("alter table t modify c bit")
```
Comment (djshow832) [inline ddl/db_test.go:4233]: Also check the new column type after altering.

**Review by djshow832 — COMMENTED** [review]
Please refine the release note to be more user-friendly. Release notes are also open to users, not only developers.

File: ddl/db_test.go (hunk 2 above)
Comment (xhebox) [reply ddl/db_test.go]: I only checked the flag, as this is what I really changed. Type change should have been tested somewhere else. And consistent type change is out of the scope of this PR.

**Comment by xhebox** [comment]
@ti-srebot /run-check_dev_2

**Review by djshow832 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
