### PR TITLE
ddl, types: fix int to datetime conversion to avoid useless retry

### LINKED ISSUE #24839: ddl: column type change will retry 512 time for error like `cannot convert datum from %s to type %s`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set @@tidb_enable_change_column_type=1;
drop table if exists t;
create table `t` (`a` int(10) unsigned default null);
insert into t values (1);
alter table t change column a b datetime;
```

### 2. What did you expect to see? (Required)
give me a error as soon as possible

### 3. What did you see instead (Required)
retry 512 times * 2.5 duration for 1pc sleep

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #24839 

Problem Summary: 

For the type conversion from `unsigned int` to `datetime`, a fundamental(unknown) error is returned.

The write reorganization stage of `ModifyColumn` uses `needRollbackData()` matching the error to detect whether the intermediate data should be cleaned:

```go
return kv.ErrKeyExists.Equal(err) || errCancelledDDLJob.Equal(err) || errCantDecodeRecord.Equal(err) ||
		types.ErrOverflow.Equal(err) || types.ErrDataTooLong.Equal(err) || types.ErrTruncated.Equal(err) ||
		json.ErrInvalidJSONText.Equal(err) || types.ErrBadNumber.Equal(err) || types.ErrInvalidYear.Equal(err) ||
		types.ErrWrongValue.Equal(err)
```

This is neither intuitive nor extendable. We should make it rollback **by default**, and explicitly define the errors that worth retrying instead.

### What is changed and how it works?

What's Changed:

- Fix `unsigned int` -> `datetime` error message.
- Make `ModifyColumn` rollback by default.
- Add a simple test case.

### Related changes

NA

### Check List 

Tests 

- Unit test
- Integration test

Side effects

NA

### Release note 

- No release note (since it is a sub-issue of "column type change" project)

### CODE REVIEW

File: types/time.go [hunk 1]
```diff
@@ -1835,19 +1836,20 @@ func parseDateTimeFromNum(sc *stmtctx.StatementContext, num int64) (Time, error)
 	// Check datetime type.
 	if num >= 10000101000000 {
 		t.SetType(mysql.TypeDatetime)
-		return getTime(sc, num, t.Type())
+		return getTime(sc, num, num, t.Type())
```
Comment (AilinKid) [inline types/time.go:1839]: should be same as `return getTime(sc, num, orginNum, t.Type())`

File: types/datum.go [hunk 2]
```diff
@@ -1182,6 +1182,14 @@ func (d *Datum) convertToMysqlTime(sc *stmtctx.StatementContext, target *FieldTy
 		t, err = ParseTime(sc, d.GetString(), tp, fsp)
 	case KindInt64:
 		t, err = ParseTimeFromNum(sc, d.GetInt64(), tp, fsp)
+	case KindUint64:
+		intOverflow64 := d.GetInt64() < 0
+		if intOverflow64 {
+			uNum := strconv.FormatUint(d.GetUint64(), 10)
+			t, err = ZeroDate, ErrWrongValue.GenWithStackByArgs(TimeStr, uNum)
+		} else {
+			t, err = ParseTimeFromNum(sc, d.GetInt64(), tp, fsp)
```
Comment (AilinKid) [inline types/datum.go:1191]: seems the `ParseTimeFromNum` doesn't pass the originNum parameter to inside, so why to bother to change the internal parameter.

**Review by AilinKid — COMMENTED** [review]
/rest LGTM
