### PR TITLE
ddl: disallow change auto_random default value by 'ALTER COLUMN'

### LINKED ISSUE #19350: alter table set default succeeds for auto_increment or auto_random
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` sql
mysql> create table t(a bigint auto_random, primary key(a));
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> select default(a) from t;
ERROR 1364 (HY000): Field 'a' doesn't have a default value
mysql> select default(a) from t;
ERROR 1364 (HY000): Field 'a' doesn't have a default value
mysql> ALTER TABLE t ALTER COLUMN a SET DEFAULT((1+1));
Query OK, 0 rows affected (0.01 sec)

mysql> select default(a) from t;
Empty set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #19350 

Problem Summary:

`auto_random` columns cannot have a default value.

There are 3 ways to set a default value for a column, and all of them should be disallowed:
- `CREATE TABLE`
- `ALTER TABLE MODIFY/CHANGE`
- `ALTER TABLE ALTER COLUMN SET DEFAULT`

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
- Add a check at `AlterColumn`.
- Add a simple test case.

How it Works: Omitted.

### Related changes

N/A

### Check List 

Tests 

- Unit test
- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -928,6 +928,11 @@ func containsColumnOption(colDef *ast.ColumnDef, opTp ast.ColumnOptionType) bool
 	return false
 }
 
+// IsAutoRandomColumnID returns true if the given column ID belongs to a auto_random column.
```
Comment (tangenta) [inline ddl/ddl_api.go:931]:
```suggestion
// IsAutoRandomColumnID returns true if the given column ID belongs to an auto_random column.
```

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
