### PR TITLE
server: Change zlib compression level

### LINKED ISSUE #47278: The compression ratio of TiDB is much worse than MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Use zlib compression to connect to TiDB with MySQL client or JDBC.
2. Send a 16M SQL to TiDB and TiDB returns a 16M result, e.g. `select 'aaaaaaaaa....'`.
3. Check the compressed data received and sent by TiDB.

### 2. What did you expect to see? (Required)

The compressed data from client to TiDB is about 16K, and the data from TiDB to client should be also around 16K.

### 3. What did you see instead (Required)

The data from TiDB to client is surprisingly up to 2M.

About zstd default level: the compression ratio is also worse than MySQL, but the gap is not as huge as zlib.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by dveeden**
This was `flate.HuffmanOnly` (-2) to 6 to match what MySQL does.

Note that `compress/flate` doesn't define a const for level 6.

### What problem does this PR solve?

Issue Number: close #47278 

Problem Summary:

Related: https://github.com/pingcap/tidb/pull/36780

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [x] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The compression level for zlib level was updated to match the compression level of MySQL
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: server/internal/packetio.go [hunk 1]
```diff
@@ -381,12 +381,13 @@ func (cw *compressedWriter) Flush() error {
 	// https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_compression_packet.html
 	// suggests a MIN_COMPRESS_LENGTH of 50.
 	minCompressLength := 50
+	zlibCompressDefaultLevel := 6
```
Comment (jackysp) [inline server/internal/packetio.go:384]: Why "6" here?

Comment (lance6716) [reply server/internal/packetio.go:384]: This is MySQL's choice https://github.com/pingcap/tidb/issues/47278#issuecomment-1734735799
