### PR TITLE
*: differentiate types for user variables

### LINKED ISSUE #11212: Different results of Function :=(Assign a value)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
SELECT  'x' = ( @A := 0 ) ;
```

2. What did you expect to see?

```mysql
mysql> SELECT  'x' = ( @A := 0 ) ;
+-------------------+
| 'x' = ( @A := 0 ) |
+-------------------+
|                 1 |
+-------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                           |
+---------+------+-------------------------------------------------------------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'x' |
+---------+------+-------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```mysql
mysql> SELECT  'x' = ( @A := 0 ) ;
+-------------------+
| 'x' = ( @A := 0 ) |
+-------------------+
|                 0 |
+-------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
0ea1bf0

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @lzmhhh123

### LINKED ISSUE #16820: [plan cache] cannot use point get plan when plan cache enabled
## Performance Improvement

### 1. Reproduce Steps

- step 1: start a tidb-server with mocktikv and **plan cache enabled**

- step 2: run the following statements in a connection:

```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
    a     BIGINT,
    b     VARCHAR(40),
    col3  VARCHAR(40) DEFAULT NULL,
    col4  VARCHAR(40) DEFAULT NULL,
    col5  VARCHAR(40) DEFAULT NULL,
    col6  VARCHAR(40) DEFAULT NULL,
    col7  VARCHAR(40) DEFAULT NULL,
    col8  VARCHAR(40) DEFAULT NULL,
    col9  VARCHAR(40) DEFAULT NULL,
    col10 VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (a, b)
);
INSERT INTO t1(a, b) VALUES (1, "1");
INSERT INTO t1(a, b) VALUES (1, "2");
INSERT INTO t1(a, b) VALUES (2, "1");
INSERT INTO t1(a, b) VALUES (2, "2");
INSERT INTO t1(a, b) VALUES (3, "1");
INSERT INTO t1(a, b) VALUES (3, "2");

DROP TABLE IF EXISTS t2;
CREATE TABLE t2 (
    a     BIGINT,
    b     VARCHAR(40),
    c     VARCHAR(40),
    col4  VARCHAR(40) DEFAULT NULL,
    col5  VARCHAR(40) DEFAULT NULL,
    col6  VARCHAR(40) DEFAULT NULL,
    col7  VARCHAR(40) DEFAULT NULL,
    col8  VARCHAR(40) DEFAULT NULL,
    col9  VARCHAR(40) DEFAULT NULL,
    col10 VARCHAR(40) DEFAULT NULL,
    UNIQUE KEY idx_a (a)
);
INSERT INTO t2(a, b, c) VALUES(1, "b", "c");
INSERT INTO t2(a, b, c) VALUES(2, "b", "c");
INSERT INTO t2(a, b, c) VALUES(3, "b", "c");

prepare stmt from "
    select * from t1, t2
    where t1.a = t2.a
    and t2.a = ?
    and t2.b = 'b'
    and t2.c = 'c'
";

set @a = 1;
execute stmt using @a;
execute stmt using @a;
```

The last statements is using plan cache, you can confirm that by executing `select @@last_plan_from_cache`.

### 2. What did you see instead?

The plan of the statements is:

```sql
TiDB(root@127.0.0.1:test) > explain for connection 8;
+--------------------------------------+----------+-----------+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                   | estRows  | task      | access object                 | operator info                                                                                                                                                                                                                                                             |
+--------------------------------------+----------+-----------+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_7                         | 0.01     | root      |                               | test.t1.a, test.t1.b, test.t1.col3, test.t1.col4, test.t1.col5, test.t1.col6, test.t1.col7, test.t1.col8, test.t1.col9, test.t1.col10, test.t2.a, test.t2.b, test.t2.c, test.t2.col4, test.t2.col5, test.t2.col6, test.t2.col7, test.t2.col8, test.t2.col9, test.t2.col10 |
| └─IndexMergeJoin_20                  | 0.01     | root      |                               | inner join, inner:Projection_18, outer key:test.t2.a, inner key:test.t1.a                                                                                                                                                                                                 |
|   ├─TableReader_54(Build)            | 0.01     | root      |                               | data:Selection_53                                                                                                                                                                                                                                                         |
|   │ └─Selection_53                   | 0.01     | cop[tikv] |                               | eq(cast(test.t2.a), 1), eq(test.t2.b, "b"), eq(test.t2.c, "c"), not(isnull(test.t2.a))                                                                                                                                                                                    |
|   │   └─TableFullScan_52             | 10000.00 | cop[tikv] | table:t2                      | keep order:false, stats:pseudo                                                                                                                                                                                                                                            |
|   └─Projection_18(Probe)             | 1.25     | root      |                               | test.t1.a, test.t1.b, test.t1.col3, test.t1.col4, test.t1.col5, test.t1.col6, test.t1.col7, test.t1.col8, test.t1.col9, test.t1.col10                                                                                                                                     |
|     └─IndexLookUp_17                 | 1.25     | root      |                               |                                                                                                                                                                                                                                                                           |
|       ├─Selection_16(Build)          | 1.25     | cop[tikv] |                               | eq(cast(test.t1.a), 1)                                                                                                                                                                                                                                                    |
|       │ └─IndexRangeScan_14          | 1.56     | cop[tikv] | table:t1, index:PRIMARY(a, b) | range: decided by [eq(test.t1.a, test.t2.a)], keep order:true, stats:pseudo                                                                                                                                                                                               |
|       └─TableRowIDScan_15(Probe)     | 1.25     | cop[tikv] | table:t1                      | keep order:false, stats:pseudo                                                                                                                                                                                                                                            |
+--------------------------------------+----------+-----------+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
10 rows in set (0.00 sec)
```

The plan is not a `Point_Get` plan is because of the comparison between bigint and string values results in casting bigint value to string, which can be confirmed by the operator info of `Selection_53`: `eq(cast(test.t2.a), 1)`.

But if we executing the following SQL, the query can benefit from point get:

```sql
create table t(a bigint unique key, b bigint); -- NOTE the bigint type here

TiDB(root@127.0.0.1:test) > explain select * from t where a = "1";
+-------------+---------+------+---------------------+---------------+
| id          | estRows | task | access object       | operator info |
+-------------+---------+------+---------------------+---------------+
| Point_Get_1 | 1.00    | root | table:t, index:a(a) |               |
+-------------+---------+------+---------------------+---------------+
1 row in set (0.00 sec)
```

From the user's angle, this query and the prepared query should have the same behavior: trying to convert string to int and utilize the `Point_Get` plan.

This further cause the above prepared query executes faster when the plan cache is disabled, because it can utilize the `Point_Get` plan.

### 3. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

```sh
➜ ./bin/tidb-server -V
Release Version: v4.0.0-beta.2-352-g5ede18f10
Git Commit Hash: 5ede18f10eedfe2e3690d7728dec3ffa4b0af2d5
Git Branch: master
UTC Build Time: 2020-04-25 08:41:26
GoVersion: go1.13.10
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve?

Issue Number: close #16820 , close #11212 

https://github.com/pingcap/tidb/issues/16603 and https://github.com/pingcap/tidb/issues/16362 can be closed by this PR as well.

Problem Summary:

We treated all user variables as string types, so there would be cast functions added which prevent the planner to choose better plans, such as PointGet. The problem is more frequent when plan cache is enabled.

### What is changed and how it works?

What's Changed:

Infer types for user variables, if the user variable is not set before, we treat it as string type. The behaviors reference https://dev.mysql.com/doc/refman/8.0/en/user-variables.html.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- differentiate types for user variables

### CODE REVIEW

File: executor/prepared_test.go [hunk 1]
```diff
@@ -146,16 +146,16 @@ func (s *testSuite9) TestPlanCacheClusterIndex(c *C) {
...
-	tk.MustExec("set @v1 = 2")
-	tk.MustExec("set @v2 = 2")
+	tk.MustExec("set @v1 = '2'")
+	tk.MustExec("set @v2 = '2'")
 	tk.MustQuery("execute stmt2 using @v1,@v2").Check(testkit.Rows("2 2 222"))
 	tk.MustQuery("select @@last_plan_from_cache").Check(testkit.Rows("1"))
-	tk.MustExec("set @v1 = 3")
-	tk.MustExec("set @v2 = 3")
+	tk.MustExec("set @v1 = '3'")
+	tk.MustExec("set @v2 = '3'")
```
Comment (eurekaka) [inline executor/prepared_test.go:158]: A related bug: https://github.com/pingcap/tidb/issues/19002. When the variable type and column type mismatches, point-get with plan-cache enabled would return wrong result. It should be fixed in another PR, so I modify the test cases here first, since the test purpose here is not on the type mismatch problem.

File: expression/integration_test.go [hunk 2]
```diff
@@ -5726,9 +5726,6 @@ func (s *testIntegrationSuite) TestCollation(c *C) {
 	tk.MustExec("set names utf8mb4 collate utf8mb4_general_ci")
 	tk.MustExec("set @test_collate_var = 'a'")
 	tk.MustQuery("select collation(@test_collate_var)").Check(testkit.Rows("utf8mb4_general_ci"))
-	tk.MustExec("set names utf8mb4 collate utf8mb4_general_ci")
```
[the remark this answers is not in the document]
Comment (eurekaka) [reply expression/integration_test.go:5729]: Because now `set @test_collate_var = 1` would be identified as integer type, so the collation testing on this integer type is meaningless.

**Review by winoros — COMMENTED** [review]
lgtm

File: expression/builtin_other.go [hunk 3]
```diff
@@ -673,118 +684,354 @@ func (c *setVarFunctionClass) getFunction(ctx sessionctx.Context, args []Express
...
+	datum, err := b.args[1].Eval(row)
+	isNull = datum.IsNull()
+	if isNull || err != nil {
+		return 0, isNull, err
+	}
+	res = datum.GetFloat64()
+	varName = strings.ToLower(varName)
+	sessionVars.UsersLock.Lock()
+	sessionVars.Users[varName] = datum
+	sessionVars.UsersLock.Unlock()
```
Comment (qw4990) [inline expression/builtin_other.go:770]: How about creating a new method `SetUsersVar(var, type)` on `sessionVars` for this logic, which makes it safer and more easy-to-use?

**Review by qw4990 — COMMENTED** [review]
Rest LGTM

File: expression/builtin_other.go (hunk 3 above)
Comment (eurekaka) [reply expression/builtin_other.go:770]: If the caller has no consciousness that this access should be protected by lock, then even if we wrap this logic as a function, they would not be aware of its existence?

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by lzmhhh123 — COMMENTED** [review]
MySQL 8.0.22 with plan cache and user variables:

```sql
mysql > prepare stmt from "select ?";
Query OK, 0 rows affected (0.00 sec)
Statement prepared

mysql > set @v = 1;
Query OK, 0 rows affected (0.00 sec)

mysql > execute stmt using @v;
+------+
| ?    |
+------+
|    1 |
+------+
1 row in set (0.00 sec)

mysql > set @v = "abc";
Query OK, 0 rows affected (0.00 sec)

mysql > execute stmt using @v;
+------+
| ?    |
+------+
|    0 |
+------+
1 row in set, 1 warning (0.00 sec)

mysql > show warnings;
+---------+------+------------------------------------------+
| Level   | Code | Message                                  |
+---------+------+------------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: 'abc' |
+---------+------+------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by lzmhhh123** [comment]
I think we can directly convert the user variable to the specified type in the plan cache during the evaluation. Since MySQL handled it in this way.

**Comment by eurekaka** [comment]
Aha, that's interesting. @SunRunAway @nullnotnil any thoughts?

**Comment by nullnotnil** [comment]
> Aha, that's interesting. @SunRunAway @nullnotnil any thoughts?

LGTM

**Comment by lzmhhh123** [comment]
> I think we can directly convert the user variable to the specified type in the plan cache during the evaluation. Since MySQL handled it in this way.

After the discussion, we decide to support different variable types in the plan cache. And [`c4bf6d0` (#18973)](https://github.com/pingcap/tidb/pull/18973/commits/c4bf6d06668afe2165d7f60eee2667447ddebce6) is to solve it.

**Review by qw4990 — APPROVED** [review]
