### PR TITLE
expression, types: fix Mod(%), Multiple(*), Minus(-) operators meets inconsistent 0 results.

### LINKED ISSUE #11211: Mod(%) operator meets inconsistent 0 results.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
select 0.000 % 0.11234500000000000000;
select 1.099 % 0.00000001000000000000;
```

2. What did you expect to see?

In MySQL,
```mysql
mysql> select 0.000 % 0.11234500000000000000;
+--------------------------------+
| 0.000 % 0.11234500000000000000 |
+--------------------------------+
|         0.00000000000000000000 |
+--------------------------------+
1 row in set (0.00 sec)

mysql> select 1.099 % 0.00000001000000000000;
+--------------------------------+
| 1.099 % 0.00000001000000000000 |
+--------------------------------+
|         0.00000000000000000000 |
+--------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

In TiDB,
```mysql
mysql> select 0.000 % 0.11234500000000000000;
+--------------------------------+
| 0.000 % 0.11234500000000000000 |
+--------------------------------+
|                              0 |
+--------------------------------+
1 row in set (0.00 sec)

mysql> select 1.099 % 0.00000001000000000000;
+--------------------------------+
| 1.099 % 0.00000001000000000000 |
+--------------------------------+
|         0.00000000000000000000 |
+--------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
0ea1bf0

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve? 
Fix #11211

### What is changed and how it works?
Add a method `zeroMyDecimalWithFrac()` to get the zero of MyDecimal with the specified result fraction digits

### Check List 

Tests 

 - Integration test
 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

File: types/mydecimal.go [hunk 1]
```diff
@@ -2010,7 +2010,9 @@ func doDivMod(from1, from2, to, mod *MyDecimal, fracIncr int) error {
 	}
 	if prec1 <= 0 {
 		/* short-circuit everything: from1 == 0 */
+		resultFrac := to.resultFrac
 		*to = zeroMyDecimal
+		to.resultFrac = resultFrac
```
Comment (SunRunAway) [inline types/mydecimal.go]: Please add a comment here to explain these three lines.
And it's better to add a unit test in mydecimal_test.go

**Comment by SunRunAway** [comment]
Hi, after seeing your pull request, it may have other problems with `zeroMyDecimal` like `SELECT 1.111-1.111;`

Could you take a review and fix them too?

File: types/mydecimal.go (hunk 1 above)
Comment (wjhuang2016) [reply types/mydecimal.go]: > Hi, after seeing your pull request, it may have other problems with `zeroMyDecimal` like `SELECT 1.111-1.111;`
> 
> Could you take a review and fix them too?

OK

**Comment by wjhuang2016** [comment]
> Hi, after seeing your pull request, it may have other problems with `zeroMyDecimal` like `SELECT 1.111-1.111;`
> 
> Could you take a review and fix them too?

OK

File: types/mydecimal.go (hunk 1 above)
Comment (wjhuang2016) [reply types/mydecimal.go]:
```
	for _, tc := range testCases {
		sig, err := funcs[ast.Mod].getFunction(s.ctx, s.datumsToConstants(types.MakeDatums(tc.args...)))
		c.Assert(err, IsNil)
		c.Assert(sig, NotNil)
		val, err := evalBuiltinFunc(sig, chunk.Row{})
		c.Assert(err, IsNil)
		c.Assert(val, testutil.DatumEquals, types.NewDatum(tc.expect))
	}
```
In TestArithmeticMod, `c.Assert` uses `DatumEquals`,  can it distinguish 0 from 0.0000...?

**Comment by SunRunAway** [comment]
Hi, @wjhuang2016 
Is it ok to review?

**Comment by wjhuang2016** [comment]
> Hi, @wjhuang2016
> Is it ok to review?

Yeah, I found that it's not easy to test it in unit tests, and I think the integration tests here are enough.

**Comment by wjhuang2016** [comment]
> Hi, @wjhuang2016
> Is it ok to review?

yeah

**Comment by SunRunAway** [comment]
Hi, @wjhuang2016 
Although it works as expected, could you add some tests covering cases like`(-1.11)+ (1.11)`?

**Comment by wjhuang2016** [comment]
> Hi, @wjhuang2016
> Although it works as expected, could you add some tests covering cases like`(-1.11)+ (1.11)`?

It covers `-1234.1234 + 1234.1234` and `0.000 / 0.1` now.

File: types/mydecimal.go [hunk 2]
```diff
@@ -107,6 +107,14 @@ var (
 	zeroMyDecimal = MyDecimal{}
 )
 
+// get the zero of MyDecimal with the specified result fraction digits
+func zeroMyDecimalWithFrac(frac int8) MyDecimal {
```
Comment (qw4990) [inline types/mydecimal.go]: How about generating a list of zero MyDecimals at the beginning so that we don't need to generate a MyDecimal each time.

Comment (wjhuang2016) [reply types/mydecimal.go]: I don't think it's a good idea.
What if `select 0.0000000000000000000000000000000000000000000000000000000000000000000000 % 0.1;` (70 zero after point)?
