### PR TITLE
executor: remove useless code for tidb_analyze_distsql_scan_concurrency

### LINKED ISSUE #50641: analyze_distsql_scan_concurrency is unavailable for index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

set analyze_distsql_scan_concurrency more large.

### 2. What did you expect to see? (Required)

faster
### 3. What did you see instead (Required)

slow

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #50641

Problem Summary:

### What changed and how does it work?

After #50639, we use ```tidb_analyze_distsql_scan_concurrency``` to control all the disql_scan_concurrency. so we can remove the old code.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/adapter.go [hunk 1]
```diff
@@ -513,8 +513,7 @@ func (a *ExecStmt) Exec(ctx context.Context) (_ sqlexec.RecordSet, err error) {
 		if !ok {
 			oriStats = strconv.Itoa(variable.DefBuildStatsConcurrency)
 		}
-		oriScan := sctx.GetSessionVars().DistSQLScanConcurrency()
-		oriIndex := sctx.GetSessionVars().IndexSerialScanConcurrency()
+		oriScan := sctx.GetSessionVars().AnalyzeDistSQLScanConcurrency()
```
Comment (AilinKid) [inline pkg/executor/adapter.go:516]: any comment on removing IndexSerialScanConcurrency

**Review by AilinKid — APPROVED** [review]
