### PR TITLE
ttl: fix the TTL job reports error when primary key contains a column with type `ENUM`

### LINKED ISSUE #40456: TTL task fails when primary key contains column with type `ENUM`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `208e9e88-b98f-4b81-871b-3a58b65dff99` (
  `c4c063a7-82f0-4433-929b-f25309621cc1` enum('yodk','ew','a9','qhp9','mu','6xoi','4ce','hniqm','hk','3rqb0','u70iv') NOT NULL DEFAULT 'mu',
  `909988c3-6511-40da-a79a-478251f1339e` float NOT NULL DEFAULT '1.178211',
  `created_at` timestamp DEFAULT '2015-08-31 18:44:53',
  PRIMARY KEY (`909988c3-6511-40da-a79a-478251f1339e`,`c4c063a7-82f0-4433-929b-f25309621cc1`) /*T![clustered_index] CLUSTERED */,
  KEY `5296b25d-edda-48a4-b17a-f5817f200c06` (`909988c3-6511-40da-a79a-478251f1339e`,`created_at`,`c4c063a7-82f0-4433-929b-f25309621cc1`),
  KEY `913fbc73-4643-4f95-8e04-93b40bb511df` (`c4c063a7-82f0-4433-929b-f25309621cc1`),
  KEY `25a044e6-84ec-499f-9b4e-681853dd4baf` (`c4c063a7-82f0-4433-929b-f25309621cc1`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci COMMENT='95c7b08b-a438-46df-810d-fba0767c334a' /*T![ttl] TTL=`created_at` + INTERVAL 3 SECOND */ /*T![ttl] TTL_ENABLE='ON' */ /*T![ttl] TTL_JOB_INTERVAL='1h' */
```

### 2. What did you expect to see? (Required)

No error when doing TTL job

### 3. What did you see instead (Required)

When running TTL jobs, some logs output:

img_v2_74984663-7b1e-4ece-99de-2293f45edf7g

### 4. What is your TiDB version? (Required)

v6.5.0

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #40456 

Because ttl method `FormatSQLDatum` cannot format the value with column type `ENUM` or `SET`, the delete task will report error when running. This PR fixed it.

### What is changed and how it works?

Support type `ENUM` and `SET` for `FormatSQLDatum`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
ttl: fix the TTL job reports error when primary key contains a column with type `ENUM`
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

File: ttl/sqlbuilder/sql_test.go [hunk 1]
```diff
@@ -290,13 +360,9 @@ func TestFormatSQLDatum(t *testing.T) {
...
 			s, err := sqlbuilder.FormatSQLDatum(d, &col.FieldType)
-			if c.notSupport {
-				require.Error(t, err)
-			} else {
-				require.NoError(t, err)
-				//fmt.Printf("%s: %s\n", c.ft, s)
-				tk.MustQuery("select id from t where " + colName + "=" + s).Check(testkit.Rows(rowID))
-			}
+			require.NoError(t, err)
+			//fmt.Printf("%s: %s\n", c.ft, s)
```
Comment (hawkingrei) [inline ttl/sqlbuilder/sql_test.go:364]:
```suggestion
```

**Review by hawkingrei — APPROVED** [review]
