### PR TITLE
planner: fix EXISTS subquery on cluster tables causing Column ID -1

### LINKED ISSUE #65521: EXISTS subquery on `information_schema.tiflash_replica` triggers internal error: "Column ID -1 ... not found" (PBPlanBuilder/pb_to_plan)
### 1. Minimal reproduce step (Required)

starting a titb cluster
```bash
tiup --tag mylab playground --db 1 --pd 1 --kv 3 --tiflash 1
```
create a table t1. Then execute:
```sql
ALTER TABLE t1 SET TIFLASH REPLICA 1;

SELECT CASE WHEN EXISTS(
  SELECT 1 FROM information_schema.tiflash_replica
  WHERE AVAILABLE < 1 OR PROGRESS < 1
) THEN 0 ELSE 1 END;
```

### 2. What did you expect to see? (Required)
No crash.

### 3. What did you see instead (Required)

```sql
MySQL [testdb]> SELECT CASE WHEN EXISTS(
    ->   SELECT 1 FROM information_schema.tiflash_replica
    ->   WHERE AVAILABLE < 1 OR PROGRESS < 1
    -> ) THEN 0 ELSE 1 END;
ERROR 1105 (HY000): other error: Column ID -1 of table tiflash_replica not found
github.com/pingcap/tidb/pkg/planner/core.(*PBPlanBuilder).convertColumnInfo
        /workspace/source/tidb/pkg/planner/core/pb_to_plan.go:259
github.com/pingcap/tidb/pkg/planner/core.(*PBPlanBuilder).pbToTableScan
        /workspace/source/tidb/pkg/planner/core/pb_to_plan.go:111
github.com/pingcap/tidb/pkg/planner/core.(*PBPlanBuilder).pbToPhysicalPlan
        /workspace/source/tidb/pkg/planner/core/pb_to_plan.go:66
github.com/pingcap/tidb/pkg/planner/core.(*PBPlanBu
```
tidb.log:

[err="other error: Column ID -1 of table tiflash_replica not found\ngithub.com/pingcap/tidb/pkg/planner/core.(*PBPlanBuilder).convertColumnInfo\n\t/workspace/source/tidb/pkg/planner/core/pb_to_plan.go:259\ngithub.com/pingcap/tidb/pkg/planner/core.(*PBPlanBuilder).pbToTableScan\n\t/workspace/source/tidb/pkg/planner/core/pb_to_plan.go:111\ngithub.com/pingcap/tidb/pkg/planner/core.(*PBPlanBuilder).pbToPhysicalPlan\n\t/workspace/source/tidb/pkg/planner/core/pb_to_plan.go:66\ngithub.com/pingcap/tidb/pkg/planner/core.(*PBPlanBuilder).Build\n\t/workspace/source/tidb/pkg/planner/core/pb_to_plan.go:53\ngithub.com/pingcap/tidb/pkg/executor.(*CoprocessorDAGHandler).buildDAGExecutor\n\t/workspace/source/tidb/pkg/executor/coprocessor.go:197\ngithub.com/pingcap/tidb/pkg/executor.(*CoprocessorDAGHandler).HandleRequest\n\t/workspace/source/tidb/pkg/executor/coprocessor.go:74\ngithub.com/pingcap/tidb/pkg/server.(*rpcServer).handleCopRequest\n\t/workspace/source/tidb/pkg/server/rpc_server.go:216\ngithub.com/pingcap/tidb/pkg/server.(*rpcServer).Coprocessor\n\t/workspace/source/tidb/pkg/server/rpc_server.go:105\ngithub.com/pingcap/kvproto/pkg/tikvpb._Tikv_Coprocessor_Handler\n\t/root/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20250908061600-97d984880071/pkg/tikvpb/tikvpb.pb.go:3526\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\t/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\ngithub.com/pingcap/tidb/pkg/store/copr.(*copIteratorWorker).handleCopResponse\n\t/workspace/source/tidb/pkg/store/copr/coprocessor.go:1553\ngithub.com/pingcap/tidb/pkg/store/copr.(*copIteratorWorker).handleTaskOnce\n\t/workspace/source/tidb/pkg/store/copr/coprocessor.go:1413\ngithub.com/pingcap/tidb/pkg/store/copr.(*liteCopIteratorWorker).liteSendReq\n\t/workspace/source/tidb/pkg/store/copr/coprocessor.go:1178\ngithub.com/pingcap/tidb/pkg/store/copr.(*copIterator).Next\n\t/workspace/source/tidb/pkg/store/copr/coprocessor.go:1101\ngithub.com/pingcap/tidb/pkg/distsql.(*selectResult).fetchResp\n\t/workspace/source/tidb/pkg/distsql/select_result.go:354\ngithub.com/pingcap/tidb/pkg/distsql.(*selectResult).Next\n\t/workspace/source/tidb/pkg/distsql/select_result.go:419\ngithub.com/pingcap/tidb/pkg/executor.(*tableResultHandler).nextChunk\n\t/workspace/source/tidb/pkg/executor/table_reader.go:612\ngithub.com/pingcap/tidb/pkg/executor.(*TableReaderExecutor).Next\n\t/workspace/source/tidb/pkg/executor/table_reader.go:331\ngithub.com/pingcap/tidb/pkg/executor/internal/exec.Next\n\t/workspace/source/tidb/pkg/executor/internal/exec/executor.go:456\ngithub.com/pingcap/tidb/pkg/executor.init.1.func1\n\t/workspace/source/tidb/pkg/executor/select.go:633\ngithub.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).handleExistSubquery\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:1109\ngithub.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).Enter.func4\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:571\ngithub.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).Enter.func1\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:528\ngithub.com/pingcap/tidb/pkg/planner/core.(*expressionRewriter).Enter\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:570\ngithub.com/pingcap/tidb/pkg/parser/ast.(*ExistsSubqueryExpr).Accept\n\t/workspace/source/tidb/pkg/parser/ast/expressions.go:679\ngithub.com/pingcap/tidb/pkg/parser/ast.(*WhenClause).Accept\n\t/workspace/source/tidb/pkg/parser/ast/expressions.go:256\ngithub.com/pingcap/tidb/pkg/parser/ast.(*CaseExpr).Accept\n\t/workspace/source/tidb/pkg/parser/ast/expressions.go:345\ngithub.com/pingcap/tidb/pkg/planner/core.rewriteExprNode\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:301\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).rewriteWithPreprocess\n\t/workspace/source/tidb/pkg/planner/core/expression_rewriter.go:239\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildProjection\n\t/workspace/source/tidb/pkg/planner/core/logical_plan_builder.go:1336\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildSelect\n\t/workspace/source/tidb/pkg/planner/core/logical_plan_builder.go:3931\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).Build\n\t/workspace/source/tidb/pkg/planner/core/planbuilder.go:549\ngithub.com/pingcap/tidb/pkg/planner.buildLogicalPlan\n\t/workspace/source/tidb/pkg/planner/optimize.go:576\ngithub.com/pingcap/tidb/pkg/planner.optimize\n\t/workspace/source/tidb/pkg/planner/optimize.go:493\ngithub.com/pingcap/tidb/pkg/planner.Optimize\n\t/workspace/source/tidb/pkg/planner/optimize.go:361\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile\n\t/workspace/source/tidb/pkg/executor/compiler.go:102\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\t/workspace/source/tidb/pkg/session/session.go:2112\ngithub.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt\n\t/workspace/source/tidb/pkg/server/driver_tidb.go:291\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt\n\t/workspace/source/tidb/pkg/server/conn.go:2033\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery\n\t/workspace/source/tidb/pkg/server/conn.go:1780\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\n\t/workspace/source/tidb/pkg/server/conn.go:1379\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\n\t/workspace/source/tidb/pkg/server/conn.go:1148"]

### 4. What is your TiDB version? (Required)

Release Version: v8.5.4
Edition: Community
Git Commit Hash: e4e814fdc0afe9c3a6e5e96f129d83df802ab820
Git Branch: HEAD
UTC Build Time: 2025-11-26 15:53:39
GoVersion: go1.23.12
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by eureka0928**
…rror

### What problem does this PR solve?

Issue Number: close #65521

### Problem Summary:

When running an EXISTS subquery on cluster tables like `information_schema.tiflash_replica`, the query fails with error: "Column ID -1 of table tiflash_replica not found".

**Reproduction:**
```sql
SELECT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TIFLASH_REPLICA WHERE TABLE_ID = 1);
-- Error 1105 (HY000): Column ID -1 of table tiflash_replica not found
```

The root cause is in `preferKeyColumnFromTable()` function in `pkg/planner/core/operator/logicalop/logical_datasource.go`. When an EXISTS subquery prunes all columns from a cluster table, the function incorrectly creates an `ExtraHandleID` (-1) column. This column ID doesn't exist in cluster tables (which are memory tables), causing the error when the coprocessor request is processed on the receiving TiDB node.

### What changed and how does it work?

Modified `preferKeyColumnFromTable()` to handle the case when `originColumns` is empty for cluster tables. Instead of falling through to create `ExtraHandleID` (-1), the function now creates a column from `dataSource.TableInfo.Columns[0]`.

Key changes:
1. Split the cluster table condition: `IsClusterTable() && len(originColumns) > 0` becomes `IsClusterTable()` with nested checks
2. When `originColumns` is empty for cluster tables, create a column from table metadata instead of ExtraHandleID

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix an issue where EXISTS subqueries on cluster tables like `information_schema.tiflash_replica` fail with "Column ID -1 not found" error.
```

---

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=42954461

### CODE REVIEW

**Comment by fury0928** [comment]
@windtalker @lance6716 this is ready for review

**Comment by leonace924** [comment]
Can you run /retest please?

**Comment by fury0928** [comment]
I need a bit of guidance on this PR
Thank you

**Comment by leonace924** [comment]
@lance6716 can you /retest for this?

**Comment by fury0928** [comment]
@qw4990 would you review this PR and let me know feedback?

**Comment by fury0928** [comment]
hi @lance6716 does this look good?

File: pkg/planner/core/operator/physicalop/physical_table_scan.go [hunk 1]
```diff
@@ -873,9 +874,14 @@ func extractFiltersForIndexMerge(ctx expression.PushDownContext, filters []expre
...
 	handleCols := ds.HandleCols
-	if handleCols == nil {
+	if handleCols == nil && !ds.Table.Type().IsClusterTable() {
 		handleCols = util.NewIntHandleCols(ds.NewExtraHandleSchemaCol())
 	}
+	// For cluster tables without handles, ts.HandleCols remains nil.
+	// Cluster tables don't support ExtraHandleID (-1) as they are memory tables.
+	if handleCols == nil {
+		return nil
+	}
```
Comment (fixdb) [inline pkg/planner/core/operator/physicalop/physical_table_scan.go:923]: we can optimizer it to
```go
if handleCols == nil {
    if ds.Table.Type().IsClusterTable() {
         return nil
    } else {
		......
    }
}
```

File: pkg/planner/core/find_best_task.go [hunk 2]
```diff
@@ -2088,9 +2088,18 @@ func convertToPartialTableScan(ds *logicalop.DataSource, prop *property.Physical
...
 	}
+	// For cluster tables without handles, use the first column from the schema.
+	// Cluster tables don't support ExtraHandleID (-1) as they are memory tables.
+	if handleCols == nil {
+		if len(ds.Columns) > 0 && len(ds.Schema().Columns) > 0 {
+			ts.SetSchema(expression.NewSchema(ds.Schema().Columns[0]))
+			ts.Columns = []*model.ColumnInfo{ds.Columns[0]}
+		}
+		return
+	}
```
Comment (fixdb) [inline pkg/planner/core/find_best_task.go:2213]: same here

**Review by fixdb — COMMENTED** [review]
With HandleCols now potentially nil for cluster tables, some paths still unconditionally access HandleCols.GetCol(0). For example, the CLUSTER_SLOW_QUERY optimization in task.go:1232-1238 uses tblScan.HandleCols.GetCol(0) without a nil guard. This can panic once cluster tables stop getting ExtraHandleID. Please add a guard or a fallback (e.g., first column) for cluster tables in this path.

File: pkg/planner/core/operator/physicalop/physical_table_scan.go [hunk 3]
```diff
@@ -833,7 +833,8 @@ func BuildIndexMergeTableScan(ds *logicalop.DataSource, tableFilters []expressio
 				ts.Columns = append(ts.Columns, col.ToInfo())
 			}
 		}
-	} else if !ts.Schema().Contains(ts.HandleCols.GetCol(0)) {
+	} else if ts.HandleCols != nil && !ts.Schema().Contains(ts.HandleCols.GetCol(0)) {
```
Comment (AilinKid) [inline pkg/planner/core/operator/physicalop/physical_table_scan.go:845]: currently we rely on preferKeyColumnFromTable to supple the additional handle for cluster table  without any handle cols, i think we can just also add that logic in here too. 

Otherwise, when optimizer block the column-prune-logical rule, the clusters can never have has its handle cols themselves.

Comment (AilinKid) [inline pkg/planner/core/operator/physicalop/physical_table_scan.go:845]: currently we rely on preferKeyColumnFromTable to supple the additional handle for cluster table without any handle cols, i think we can just also add that logic in here too.

Otherwise, when optimizer block the column-prune-logical rule, the clusters can never have has its handle cols themselves when its nil here.

Comment (fury0928) [reply pkg/planner/core/operator/physicalop/physical_table_scan.go:845]: I am on it right now

**Comment by eureka928** [comment]
This failure is not related to my PR. It's a flaky test in executor/stale_txn — the test does AS OF TIMESTAMP now(6) -  interval 1 microsecond which is a race condition: now(6) can return a timestamp slightly ahead of the TSO's current timestamp, causing the "cannot set read timestamp to a future time" error. This depends on clock skew between the test process and the mock TiKV, not on any planner changes.
