### PR TITLE
ddl: more test cases on `admin pause/resume`

### LINKED ISSUE #44762: DATA RACE in the TestDDLCallback
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c00bd3c768 by goroutine 27534:
  github.com/pingcap/tidb/ddl/util/callback.(*TestDDLCallback).OnGetJobBefore()
      ddl/util/callback/callback.go:145 +0x48
  github.com/pingcap/tidb/ddl.(*ddl).loadDDLJobAndRun()
      ddl/job_table.go:357 +0x3e2
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop()
      ddl/job_table.go:301 +0xc70
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop-fm()
      <autogenerated>:1 +0x39
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      util/wait_group_wrapper.go:154 +0x73
Previous write at 0x00c00bd3c768 by goroutine 48:
  ddl/pausetest/pausetest_test.TestResumeJobPositive()
      ddl/pausetest/pause_test.go:466 +0xaa8
  github.com/pingcap/tidb/session.runStmt()
      session/session.go:2400 +0x62f
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2250 +0x1405
  github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext()
      testkit/testkit.go:324 +0x8ae
  github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext()
      testkit/testkit.go:132 +0xb7
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      testkit/testkit.go:127 +0x138
  ddl/pausetest/pausetest_test.TestResumeJobPositive()
      ddl/pausetest/pause_test.go:431 +0x207
  github.com/pingcap/tidb/session.runStmt()
      session/session.go:2400 +0x62f
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2250 +0x1405
  github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext()
      testkit/testkit.go:324 +0x8ae
  github.com/pingcap/tidb/testkit.(*TestKit).MustExecWithContext()
      testkit/testkit.go:132 +0xb7
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      testkit/testkit.go:127 +0x138
  ddl/pausetest/pausetest_test.TestResumeJobPositive()
      ddl/pausetest/pause_test.go:430 +0x1e7
  github.com/pingcap/tidb/domain.(*Domain).rebuildSysVarCache()
      domain/sysvar_cache.go:146 +0x8c4
  github.com/pingcap/tidb/domain.(*Domain).LoadSysVarCacheLoop()
      domain/domain.go:1774 +0xa8
  github.com/pingcap/tidb/session.bootstrapSessionImpl()
      session/session.go:3357 +0x6e4
  github.com/pingcap/tidb/domain.(*Domain).GetSessionCache()
      domain/sysvar_cache.go:62 +0x5c
  github.com/pingcap/tidb/session.(*session).loadCommonGlobalVariablesIfNeeded()
      session/session.go:3721 +0x104
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      session/session.go:2130 +0x145
  github.com/pingcap/tidb/session.(*session).ExecuteInternal()
      session/session.go:1666 +0x31b
  github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop()
      domain/domain.go:1717 +0x130
  github.com/pingcap/tidb/session.bootstrapSessionImpl()
      session/session.go:3350 +0x687
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3271 +0xb4
  github.com/pingcap/tidb/testkit.bootstrap()
      testkit/mockstore.go:218 +0x9b
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomainWithSchemaLease()
      testkit/mockstore.go:243 +0xe9
  ddl/pausetest/pausetest_test.TestResumeJobPositive()
      ddl/pausetest/pause_test.go:400 +0x5d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1629 +0x47
Goroutine 27534 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      util/wait_group_wrapper.go:152 +0xe4
  github.com/pingcap/tidb/ddl.(*ddl).prepareWorkers4ConcurrencyDDL()
      ddl/ddl.go:756 +0x4a9
  github.com/pingcap/tidb/ddl.(*ddl).Start()
      ddl/ddl.go:782 +0x8be
  github.com/pingcap/tidb/domain.(*Domain).Init()
      domain/domain.go:1206 +0x16cc
  github.com/pingcap/tidb/session.(*domainMap).Get.func1()
      session/tidb.go:93 +0x676
  github.com/pingcap/tidb/util.RunWithRetry()
      util/misc.go:69 +0x93
  github.com/pingcap/tidb/session.(*domainMap).Get()
      session/tidb.go:79 +0x2d2
  github.com/pingcap/tidb/session.createSessionWithOpt()
      session/session.go:3578 +0x75
  github.com/pingcap/tidb/session.createSession()
      session/session.go:3570 +0x38
  github.com/pingcap/tidb/session.createSessionsImpl()
      session/session.go:3555 +0x81
  github.com/pingcap/tidb/session.createSessions()
      session/session.go:3542 +0x4b
  github.com/pingcap/tidb/session.bootstrapSessionImpl()
      session/session.go:3317 +0x3e6
  github.com/pingcap/tidb/session.BootstrapSession()
      session/session.go:3271 +0xb4
  github.com/pingcap/tidb/testkit.bootstrap()
      testkit/mockstore.go:218 +0x9b
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomainWithSchemaLease()
      testkit/mockstore.go:243 +0xe9
  ddl/pausetest/pausetest_test.TestResumeJobPositive()
      ddl/pausetest/pause_test.go:400 +0x5d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1629 +0x47
Goroutine 48 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      GOROOT/src/testing/testing.go:1576 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1906 +0xb44
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x70
  ddl/pausetest/pausetest_test.TestMain()
      ddl/pausetest/main_test.go:44 +0x45c
  main.main()
      bazel-out/k8-fastbuild/bin/ddl/pausetest/pausetest_test_/testmain.go:108 +0x5e8
================== 
```

### PR DESCRIPTION
**Pull request by dhysum**
### What problem does this PR solve?

Issue Number: close #44762

Problem Summary:
a. Add more DDL statements to test `admin pause/resume/cancel`
b. Add more cases on `admin pause/resume/cancel`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/adminpausetest/ddl_data_generation.go [hunk 1]
```diff
@@ -0,0 +1,156 @@
+// Copyright 2022 PingCAP, Inc.
```
Comment (ywqzzy) [inline ddl/adminpausetest/ddl_data_generation.go:1]: Can we move this file to other package and public the api？I think it will be very useful for testing

Comment (ywqzzy) [inline ddl/adminpausetest/ddl_data_generation.go:1]:
```suggestion
// Copyright 2023 PingCAP, Inc.
```

File: ddl/adminpausetest/ddl_stmt_cases.go [hunk 2]
```diff
@@ -0,0 +1,242 @@
+// Copyright 2022 PingCAP, Inc.
```
Comment (ywqzzy) [inline ddl/adminpausetest/ddl_stmt_cases.go:1]:
```suggestion
// Copyright 2023 PingCAP, Inc.
```

File: ddl/adminpausetest/global.go [hunk 3]
```diff
@@ -0,0 +1,54 @@
+// Copyright 2022 PingCAP, Inc.
```
Comment (ywqzzy) [inline ddl/adminpausetest/global.go:1]: ditto

File: ddl/adminpausetest/ddl_data_generation.go
Comment (tangenta) [inline ddl/adminpausetest/ddl_data_generation.go:1]: Could you move the tests to `ddl/tests`?

Comment (dhysum) [reply ddl/adminpausetest/ddl_data_generation.go:1]: It is ok to do that. The reason why the cases were moved here was that some cases took a long time to finish that it would be time out some time since it occupied some parallelism. 

I need to have some test to verify the time it costs before moving it to `ddl/tests`.

File: ddl/adminpausetest/ddl_data_generation.go (hunk 1 above)
Comment (dhysum) [reply ddl/adminpausetest/ddl_data_generation.go:1]: That would be fine.

File: ddl/ddl.go [hunk 4]
```diff
@@ -550,11 +550,11 @@ func (dc *ddlCtx) removeReorgCtx(jobID int64) {
 func (dc *ddlCtx) notifyReorgWorkerJobStateChange(job *model.Job) {
 	rc := dc.getReorgCtx(job.ID)
 	if rc == nil {
-		logutil.BgLogger().Warn("cannot find reorgCtx", zap.Int64("jobID", job.ID))
+		logutil.BgLogger().Warn("cannot find reorgCtx", zap.Int64("job ID", job.ID))
 		return
 	}
 	logutil.BgLogger().Info("[ddl] notify reorg worker the job's state",
-		zap.Int64("jobID", job.ID), zap.Int32("jobState", int32(job.State)), zap.Int("jobState", int(job.SchemaState)))
+		zap.Int64("job ID", job.ID), zap.Int32("job State", int32(job.State)), zap.Int("job State", int(job.SchemaState)))
```
Comment (hawkingrei) [inline ddl/ddl.go:557]: 1、Here has two ```job State```
2、Job state is an integer. It is hard to understand.

Comment (dhysum) [reply ddl/ddl.go]: done

**Review by hawkingrei — APPROVED** [review]

File: ddl/tests/adminpause/global.go [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+// SubStates is a slice of SchemaState.
+type SubStates = []model.SchemaState
+
+// matchTargetState is used to test whether the cancel state matches.
+func matchTargetState( /*t *testing.T, */ job *model.Job, targetState interface{}) bool {
+	switch v := targetState.(type) {
+	case model.SchemaState:
+		if job.Type == model.ActionMultiSchemaChange {
+			// msg := fmt.Sprintf("unexpected multi-schema change(sql: %s, cancel state: %s)", sql, v)
+			// require.Failf(t, msg, "use []model.SchemaState as cancel states instead")
```
Comment (tangenta) [inline ddl/tests/adminpause/global.go:42]:
```suggestion
```

File: ddl/tests/adminpause/global.go [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+			return false
+		}
+		return job.SchemaState == v
+	case SubStates: // For multi-schema change sub-jobs.
+		if job.MultiSchemaInfo == nil {
+			// msg := fmt.Sprintf("not multi-schema change(sql: %s, cancel state: %v)", sql, v)
+			// require.Failf(t, msg, "use model.SchemaState as the cancel state instead")
```
Comment (tangenta) [inline ddl/tests/adminpause/global.go:49]:
```suggestion
```

**Review by tangenta — APPROVED** [review]
