### PR TITLE
server: use Atomic.Pointer in the Server.statusServer

### LINKED ISSUE #62902: DATA RACE in the closeListener
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c000c725c8 by goroutine 324:
  github.com/pingcap/tidb/pkg/server.(*Server).closeListener()
      pkg/server/server.go:646 +0x174
  github.com/pingcap/tidb/pkg/server.(*Server).Close()
      pkg/server/server.go:671 +0xc6
  pkg/server/tests/tls/tls_test.TestStatusAPIWithTLS()
      pkg/server/tests/tls/tls_test.go:559 +0xc34
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:143 +0xa24
  fmt.Sscanf()
      GOROOT/src/fmt/scan.go:114 +0x18e
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseByteSize()
      pkg/sessionctx/variable/varsutil.go:319 +0x1d
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func264()
      pkg/sessionctx/variable/sysvar.go:1431 +0x44
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:144 +0xa94
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseSchemaCacheSize()
      pkg/sessionctx/variable/varsutil.go:551 +0x17c
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func646()
      pkg/sessionctx/variable/sysvar.go:3433 +0x67
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:144 +0xa94
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func645()
      pkg/sessionctx/variable/sysvar.go:3425 +0x52
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:287 +0x242
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:143 +0xa24
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadSysVarCacheLoop()
      pkg/domain/domain.go:1385 +0x93
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3634 +0x904
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:287 +0x242
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:143 +0xa24
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseMemoryLimit()
      pkg/sessionctx/variable/varsutil.go:288 +0x18b
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func221()
      pkg/sessionctx/variable/sysvar.go:1167 +0x56
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:144 +0xa94
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func220()
      pkg/sessionctx/variable/sysvar.go:1160 +0x52
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:287 +0x242
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:143 +0xa24
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCacheIfNeeded()
      pkg/domain/sysvar_cache.go:51 +0x1bb
  github.com/pingcap/tidb/pkg/domain.(*Domain).GetSessionCache()
      pkg/domain/sysvar_cache.go:62 +0x4a
  github.com/pingcap/tidb/pkg/session.(*session).loadCommonGlobalVariablesIfNeeded()
      pkg/session/session.go:4065 +0x2bc
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      pkg/session/session.go:2074 +0x17a
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal()
      pkg/session/session.go:1588 +0x3af
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadPrivilegeLoop()
      pkg/domain/domain.go:1308 +0x102
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3627 +0x8ab
  github.com/pingcap/tidb/pkg/session.BootstrapSession()
      pkg/session/session.go:3499 +0x2be
  github.com/pingcap/tidb/pkg/server/tests/servertestkit.CreateTidbTestSuiteWithCfg()
      pkg/server/tests/servertestkit/testkit.go:104 +0x1d3
  github.com/pingcap/tidb/pkg/server/tests/servertestkit.CreateTidbTestSuite()
      pkg/server/tests/servertestkit/testkit.go:57 +0x1fa
  pkg/server/tests/tls/tls_test.TestStatusAPIWithTLS()
      pkg/server/tests/tls/tls_test.go:518 +0x3e
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      GOROOT/src/testing/testing.go:1743 +0x44
Previous write at 0x00c000c725c8 by goroutine 14440:
  github.com/pingcap/tidb/pkg/server.(*Server).startStatusServerAndRPCServer()
      pkg/server/http_status.go:589 +0xc7b
  github.com/pingcap/tidb/pkg/server.(*Server).startHTTPServer()
      pkg/server/http_status.go:544 +0x2ca7
  github.com/pingcap/tidb/pkg/server.(*Server).startStatusHTTP.gowrap1()
      pkg/server/http_status.go:79 +0x33
Goroutine 324 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1743 +0x825
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:2168 +0x85
  testing.tRunner()
      GOROOT/src/testing/testing.go:1690 +0x226
  testing.runTests()
      GOROOT/src/testing/testing.go:2166 +0x8be
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:2034 +0xf17
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x64
  pkg/server/tests/tls/tls_test.TestMain()
      pkg/server/tests/tls/main_test.go:69 +0x102d
  main.main()
      bazel-out/k8-fastbuild/bin/pkg/server/tests/tls/tls_test_/testmain.go:150 +0x5b3
Goroutine 14440 (running) created at:
  github.com/pingcap/tidb/pkg/server.(*Server).startStatusHTTP()
      pkg/server/http_status.go:79 +0xa4
  github.com/pingcap/tidb/pkg/server.(*Server).Run()
      pkg/server/server.go:475 +0x159
  pkg/server/tests/tls/tls_test.TestStatusAPIWithTLS.func2()
      pkg/server/tests/tls/tls_test.go:544 +0x35
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #62902

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: pkg/server/server.go [hunk 1]
```diff
@@ -643,10 +643,10 @@ func (s *Server) closeListener() {
 		terror.Log(errors.Trace(err))
 		s.socket = nil
 	}
-	if s.statusServer != nil {
-		err := s.statusServer.Close()
+	if statusServer := s.statusServer.Load(); statusServer != nil {
+		err := statusServer.Close()
```
Comment (lance6716) [inline pkg/server/server.go:647]: There can be more data race like `grpcServer`. Before this change, it also set at `startStatusServerAndRPCServer` and clear at  `closeListener`. It's very similar to `statusServer`

And using atomic will leak a `statusServer` for the case `Store` runs after `Load`. I think the point is correct handling concurrent "start" and "close"
