### PR TITLE
fix: close issue #59428 to sec_to_time binary same as mysql

### LINKED ISSUE #59428: `SEC_TO_TIME` has different precision compared with MySQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

```
mysql> SELECT sec_to_time(b'1111');
+----------------------+
| sec_to_time(b'1111') |
+----------------------+
| 00:00:15             |
+----------------------+
1 row in set (0.04 sec)

mysql> SELECT sec_to_time(0x1E0);
+--------------------+
| sec_to_time(0x1E0) |
+--------------------+
| 00:08:00           |
+--------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> SELECT sec_to_time(b'1111');
+----------------------+
| sec_to_time(b'1111') |
+----------------------+
| 00:00:15.000000      |
+----------------------+
1 row in set (0.00 sec)

mysql> SELECT sec_to_time(0x1E0);
+--------------------+
| sec_to_time(0x1E0) |
+--------------------+
| 00:08:00.000000    |
+--------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by yihong0618**
This patch close issue 59428 same behavior as mysql
also add test

cc @YangKeao 

### What problem does this PR solve?

Issue Number: close #59428

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
/cc @windtalker

also ping @yihong0618 to fix merge conflict

**Comment by yihong0618** [comment]
> /cc @windtalker
> 
> also ping @yihong0618 to fix merge conflict

Done

File: pkg/expression/builtin_time.go [hunk 1]
```diff
@@ -5868,7 +5868,11 @@ func (c *secToTimeFunctionClass) getFunction(ctx BuildContext, args []Expression
 	var retFsp int
 	argType := args[0].GetType(ctx.GetEvalCtx())
 	argEvalTp := argType.EvalType()
-	if argEvalTp == types.ETString {
+
+	// to match MySQL behavior more check issue #59428
+	if IsBinaryLiteral(args[0]) {
```
Comment (windtalker) [inline pkg/expression/builtin_time.go:5873]: can you double check the behavior if the argument is not binary literal, but a binary column?

Comment (yihong0618) [reply pkg/expression/builtin_time.go:5873]: checked
image
image

same as mysql
