### PR TITLE
*: use difference port to fix UT

### LINKED ISSUE #62623: flaky test TestBackfillingSchedulerGlobalSortMode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
    backfilling_dist_scheduler_test.go:339: 
        	Error Trace:	pkg/ddl/backfilling_dist_scheduler_test.go:339
        	            				pkg/ddl/backfilling_dist_scheduler_test.go:159
        	Error:      	Received unexpected error:
        	            	listen tcp 127.0.0.1:4443: bind: address already in use
        	Test:       	TestBackfillingSchedulerGlobalSortMode
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #62623

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/backfilling_dist_scheduler_test.go [hunk 1]
```diff
@@ -293,7 +293,7 @@ func createAddIndexTask(t *testing.T,
 	useGlobalSort bool) (*proto.Task, *fakestorage.Server) {
 	var (
 		gcsHost = "127.0.0.1"
-		gcsPort = uint16(4443)
+		gcsPort = uint16(4447)
```
Comment (lance6716) [inline pkg/ddl/backfilling_dist_scheduler_test.go:296]: maybe use `freeport.GetFreePort()`

Comment (hawkingrei) [reply pkg/ddl/backfilling_dist_scheduler_test.go:296]: ts usage is different from the standard usage, and even the URI is generally different, so it may not be a good idea. The original author may need to refactor the code.

**Review by tangenta — APPROVED** [review]
