### PR TITLE
planner: fix union statements order

### LINKED ISSUE #8202: unexpected ERROR 1054 (42S22): Unknown column 'a' in 'order clause'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
SELECT * FROM (select 1 as a union all select 1 union all select 2 union select 1 union all select 2) t order by a;
```

2. What did you expect to see?
``` sql
mysql> SELECT * FROM (select 1 as a union all select 1 union all select 2 union select 1 union all select 2) t order by a;
+---+
| a |
+---+
| 1 |
| 2 |
| 2 |
+---+
3 rows in set (0.00 sec)
```

3. What did you see instead?

``` sql
tidb> SELECT * FROM (select 1 as a union all select 1 union all select 2 union select 1 union all select 2) t order by a;
ERROR 1054 (42S22): Unknown column 'a' in 'order clause'
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-rc.3-147-g379ee5b19
Git Commit Hash: 379ee5b1915a37d14e45230acf4d911c6b80d07d
Git Branch: master
UTC Build Time: 2018-11-06 03:12:11
GoVersion: go version go1.11 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by mtunique**
### What problem does this PR solve? 
Fix #8202  union statements order because union result schema info isn't correct.

### What is changed and how it works?
Because union schema is the same to its first children. [MySQL UNION Syntax](https://dev.mysql.com/doc/refman/5.7/en/union.html)

```go
func (b *PlanBuilder) buildProjection4Union(u *LogicalUnionAll) {
	unionCols := make([]*expression.Column, 0, u.children[0].Schema().Len())

	// Infer union result types by its children's schema.
	for i, col := range u.children[0].Schema().Columns {
		resultTp := col.RetType
		for j := 1; j < len(u.children); j++ {
			childTp := u.children[j].Schema().Columns[i].RetType
			resultTp = unionJoinFieldType(resultTp, childTp)
		}
		unionCols = append(unionCols, &expression.Column{
			ColName:  col.ColName,
			TblName:  col.TblName,
			RetType:  resultTp,
			UniqueID: b.ctx.GetSessionVars().AllocPlanColumnID(),
		})
	}
```
But when mix UNION ALL and UNION DISTINCT in the same query, allSelectPlans is in front of unionDistinctPlan.  When call buildUnionAll , the schema become incorrect. We should change the order, it should be same to SQL.

```go
func (b *PlanBuilder) buildUnion(union *ast.UnionStmt) (LogicalPlan, error) {
	distinctSelectPlans, allSelectPlans, err := b.divideUnionSelectPlans(union.SelectList.Selects)
	if err != nil {
		return nil, errors.Trace(err)
	}

	unionDistinctPlan := b.buildUnionAll(distinctSelectPlans)
	if unionDistinctPlan != nil {
		unionDistinctPlan = b.buildDistinct(unionDistinctPlan, unionDistinctPlan.Schema().Len())
		if len(allSelectPlans) > 0 {
			allSelectPlans = append(allSelectPlans, unionDistinctPlan)
		}
	}
	unionAllPlan := b.buildUnionAll(allSelectPlans)
```

### Check List 

Tests 

 - Unit test
Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by zz-jason** [comment]
@lysu @winoros @eurekaka PTAL

**Comment by winoros** [comment]
@mtunique 
You can use `fix issue link` grammer in your pr description so that issue can be auto closed when this pr is merged.
See https://help.github.com/articles/closing-issues-using-keywords/

File: planner/core/logical_plan_test.go [hunk 1]
```diff
@@ -1838,13 +1843,14 @@ func (s *testPlanSuite) TestUnion(c *C) {
 		plan, err := builder.Build(stmt)
 		if tt.err {
```
Comment (winoros) [inline planner/core/logical_plan_test.go]: This part can be changed directly to `c.Assert(tt.err, NotNil)`

File: planner/core/logical_plan_test.go [hunk 2]
```diff
@@ -1838,13 +1843,14 @@ func (s *testPlanSuite) TestUnion(c *C) {
...
 			c.Assert(err, NotNil)
-			return
+			continue
 		}
 		c.Assert(err, IsNil)
 		p := plan.(LogicalPlan)
 		p, err = logicalOptimize(builder.optFlag, p.(LogicalPlan))
 		c.Assert(err, IsNil)
-		c.Assert(ToString(p), Equals, tt.best, comment)
+		s := ToString(p)
```
Comment (winoros) [inline planner/core/logical_plan_test.go]: No need to change it?

Comment (mtunique) [reply planner/core/logical_plan_test.go]: Sorry, it's just for my debug. Removed.

**Comment by mtunique** [comment]
@zz-jason Maybe it's necessary.

File: planner/core/logical_plan_test.go (hunk 1 above)
Comment (mtunique) [reply planner/core/logical_plan_test.go]: When `tt.err` is false, we should ignore below code. Is it can use `c.Assert` directly?

**Comment by mtunique** [comment]
> @mtunique
> You can use `fix issue link` grammer in your pr description so that issue can be auto closed when this pr is merged.
> See https://help.github.com/articles/closing-issues-using-keywords/

Done.

**Comment by XuHuaiyu** [comment]
@mtunique 
And we should also cherry-pick this to release-2.0.

It should be noted that, the directory structure `planner/core` in master corresponds to the directory `plan` in release-2.0.

**Comment by mtunique** [comment]
> @mtunique
> And we should also cherry-pick this to release-2.0.
> 
> It should be noted that, the directory structure `planner/core` in master corresponds to the directory `plan` in release-2.0.

Done. #8318
