### PR TITLE
expression,planner: fix to preserve the precision information of a timestamp-typed column in the plan cache

### LINKED ISSUE #8615: unexpected behavior about prepare cache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

It's found in `TestPrepareCacheDeferredFunction`.
In this test, we use `time.Sleep(time.Second*1)` to test the `now()` in prepare cache works well.

But since the column is `TIMESTAMP(3)`. We don't need to sleep so long.

2. What did you expect to see?

The test works well if we sleep less than 1s.

3. What did you see instead?

The result is always `x.000s`, the information of millisecond is lost.
It happened in the following code block:
```
// Eval implements Expression interface.
func (c *Constant) Eval(_ chunk.Row) (types.Datum, error) {
	if c.DeferredExpr != nil {
		if sf, sfOK := c.DeferredExpr.(*ScalarFunction); sfOK {
			dt, err := sf.Eval(chunk.Row{})
			if err != nil {
				return c.Value, err
			}
			if dt.IsNull() {
				c.Value.SetNull()
				return c.Value, nil
			}
			retType := types.NewFieldType(c.RetType.Tp)
			if retType.Tp == mysql.TypeUnspecified {
				retType.Tp = mysql.TypeVarString
			}
			val, err := dt.ConvertTo(sf.GetCtx().GetSessionVars().StmtCtx, retType)
			if err != nil {
				return dt, err
			}
			c.Value.SetValue(val.GetValue())
		}
	}
	return c.Value, nil
}
```

After the `Eval` of sf, `dt` holds the millisecond part. But when we do
```
val, err := dt.ConvertTo(sf.GetCtx().GetSessionVars().StmtCtx, retType)
```
Millisecond is lost.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master with f72769cee45d42c31149031f121da7d05d19af90

### PR DESCRIPTION
**Pull request by dbjoa**
### What problem does this PR solve? 
Fix #8615 

### What is changed and how it works?
When cloning ``FieldType.Tp`` from the source, ``FieldType.Decimal`` should be cloned too because it can be used as ``Fsp`` in ``Timestamp`` type.

### Check List 

Tests 
 - Unit test

Code changes
 - Has exported function/method change

Side effects
 - None

Related changes
 - Need to cherry-pick to the release branch

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8619)

### CODE REVIEW

File: expression/constant.go [hunk 1]
```diff
@@ -103,6 +103,7 @@ func (c *Constant) Eval(_ chunk.Row) (types.Datum, error) {
 			if retType.Tp == mysql.TypeUnspecified {
 				retType.Tp = mysql.TypeVarString
 			}
+			retType.Decimal = c.RetType.Decimal
 			val, err := dt.ConvertTo(sf.GetCtx().GetSessionVars().StmtCtx, retType)
```
Comment (eurekaka) [inline expression/constant.go]: Why we don't directly use `c.RetType` as parameter of `ConvertTo`?

Comment (dbjoa) [reply expression/constant.go]: Thank you for the comment. I've cleaned up the PR.

File: types/field_type.go [hunk 2]
```diff
@@ -40,6 +40,15 @@ func NewFieldType(tp byte) *FieldType {
 	}
 }
 
+// CloneFieldType clones the given FieldType.
+func CloneFieldType(src *FieldType) *FieldType {
```
Comment (XuHuaiyu) [inline types/field_type.go]: Please clone all the attributes in a FieldType.

File: expression/constant.go [hunk 3]
```diff
@@ -99,11 +99,10 @@ func (c *Constant) Eval(_ chunk.Row) (types.Datum, error) {
 				c.Value.SetNull()
 				return c.Value, nil
 			}
-			retType := types.NewFieldType(c.RetType.Tp)
-			if retType.Tp == mysql.TypeUnspecified {
-				retType.Tp = mysql.TypeVarString
+			if c.RetType.Tp == mysql.TypeUnspecified {
```
Comment (XuHuaiyu) [inline expression/constant.go]: When will `c.RetType.Tp == mysql.TypeUnspecified` be true?

File: types/field_type.go (hunk 2 above)
Comment (lamxTyler) [reply types/field_type.go]: If you just want a shallow copy, the following will be easier:
```go
ft := *src
return &ft
```

File: expression/constant.go (hunk 3 above)
Comment (dbjoa) [reply expression/constant.go]: Here are the example for the case, which is the snippet in ``TestPreparedIssue7579()`` of ``tidb/executor/prepared_test.go``:     

```
create table t (a int, b int, index a_idx(a))
prepare stmt from 'select a, b from t where ? order by b asc'
set @param = true
execute stmt using @param;
```
Here, the value of the parameter ``?`` is ``mysql.TypeUnspecified``.

File: types/field_type.go (hunk 2 above)
Comment (dbjoa) [reply types/field_type.go]: @lamxTyler Thank you for the tip!

File: expression/constant.go (hunk 3 above)
Comment (zz-jason) [reply expression/constant.go]: @dbjoa Maybe it's better to do this after the `c.DeferredExpr` is constructed? For example, https://github.com/pingcap/tidb/pull/8619/files#diff-33ebff1614e7db77b69dd02c2eee26c2R1245

Comment (dbjoa) [reply expression/constant.go]: @zz-jason Thank you for the comment. However, I think that ``types.DefaultParamTypeForValue()`` might be the right place to change the parameter's return type to be ``mysql.TypeVarString`` from ``mysql.TypeUnspecified`` like the updated PR: 

https://github.com/pingcap/tidb/blob/5617f84d10ab678594041f59f0a0a89b024c9096/types/field_type.go#L129-L141

Comment (zz-jason) [reply expression/constant.go]: Oh, yeah, this is the ideal place 😄

**Comment by zz-jason** [comment]
@dbjoa Could you please help us cherry-pick this commit to release-2.1 and release-2.0?

File: types/field_type.go (hunk 2 above)
Comment (winoros) [reply types/field_type.go]: Why not let it be a member function of `FieldType`?

Comment (dbjoa) [reply types/field_type.go]: @winoros Yes, we can further refactor the function by making it to be the member function in ``parser/types/field_type.go``.  I'll handle it another PR.

**Comment by dbjoa** [comment]
@zz-jason Unfortunately, we couldn't. This is because the PR has dependency on the previous PR #8105, and release-2.1 and release-2.0 should include the previous PR.
