### PR TITLE
executor: fix setting system variables to original values failed after auto analyze

### LINKED ISSUE #37410: Master: tidb hit Incorrect argument type to variable 'tidb_build_stats_concurrency' and  'tx_isolation'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Nothing, just run workload.

### 2. What did you expect to see? (Required)
No error logs.

### 3. What did you see instead (Required)
Found two error logs in tidb, seems cause by background sqls, such as autoanalyze.

[2022/08/26 09:46:23.146 +00:00] [ERROR] [terror.go:313] ["encountered error"] [error="[variable:1232]Incorrect argument type to variable 'tidb_build_stats_concurrency'"] [stack="github.com/pingcap/tidb/parser/terror.Log\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:313\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func3\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:449\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:514\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2197\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2061\ngithub.com/pingcap/tidb/session.(*session).ExecRestrictedSQL.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1950\ngithub.com/pingcap/tidb/session.(*session).withRestrictedSQLExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1936\ngithub.com/pingcap/tidb/session.(*session).ExecRestrictedSQL\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1940\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).execRestrictedSQLWithStatsVer.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:147\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).withRestrictedSQLExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:127\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).execRestrictedSQLWithStatsVer\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:139\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).execAutoAnalyze\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/update.go:1230\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).autoAnalyzeTable\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/update.go:1139\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).HandleAutoAnalyze\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/update.go:1099\ngithub.com/pingcap/tidb/domain.(*Domain).autoAnalyzeWorker\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/domain.go:1563\ngithub.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/domain.go:1383\ngithub.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:33"]
[2022/08/26 09:46:23.146 +00:00] [ERROR] [terror.go:313] ["encountered error"] [error="[variable:1231]Variable 'tx_isolation' can't be set to the value of ''"] [stack="github.com/pingcap/tidb/parser/terror.Log\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:313\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func3\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:452\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:514\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2197\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2061\ngithub.com/pingcap/tidb/session.(*session).ExecRestrictedSQL.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1950\ngithub.com/pingcap/tidb/session.(*session).withRestrictedSQLExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1936\ngithub.com/pingcap/tidb/session.(*session).ExecRestrictedSQL\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1940\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).execRestrictedSQLWithStatsVer.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:147\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).withRestrictedSQLExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:127\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).execRestrictedSQLWithStatsVer\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:139\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).execAutoAnalyze\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/update.go:1230\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).autoAnalyzeTable\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/update.go:1139\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).HandleAutoAnalyze\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/update.go:1099\ngithub.com/pingcap/tidb/domain.(*Domain).autoAnalyzeWorker\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/domain.go:1563\ngithub.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/domain.go:1383\ngithub.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:33"]

### 4. What is your TiDB version? (Required)

/ # /tidb-server -V
Release Version: v6.2.0-alpha
Edition: Community
Git Commit Hash: 803677741353c22cce85cee05e0322a1cc41bd54
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-08-25 14:20:50
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #37410

Problem Summary:

### What is changed and how it works?
When saving original values of `TiDBBuildStatsConcurrency` and `TxnIsolation` before auto analyze, `GetSystemVar` returns empty values for both system variables in an internal session, which causes restoring original values after auto analyze failed. The pr uses `GetSessionOrGlobalSystemVar`, which would not return empty values, to replace `GetSystemVar`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Trigger auto analyze and see no error log like #37410.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/adapter.go [hunk 1]
```diff
@@ -437,10 +437,12 @@ func (a *ExecStmt) Exec(ctx context.Context) (_ sqlexec.RecordSet, err error) {
 	sctx := a.Ctx
 	ctx = util.SetSessionID(ctx, sctx.GetSessionVars().ConnectionID)
 	if _, ok := a.Plan.(*plannercore.Analyze); ok && sctx.GetSessionVars().InRestrictedSQL {
-		oriStats, _ := sctx.GetSessionVars().GetSystemVar(variable.TiDBBuildStatsConcurrency)
+		oriStats, err := sctx.GetSessionVars().GetSessionOrGlobalSystemVar(variable.TiDBBuildStatsConcurrency)
+		terror.Log(err)
```
Comment (bb7133) [inline executor/adapter.go:441]: > GetSystemVar returns empty values for both system variables in an internal session

I think we should try to avoid it, if it is not trivial to do so, we could use the default value as 'oriStats' here.

Comment (xuyifangreeneyes) [reply executor/adapter.go:441]: It seems not trivial to use the global system variable value to initialize the session system variable for internal sessions because we need the first internal session to read the global system variable value from disk. The two quick-fix ways are:
1. When `GetSystemVar` returns empty value, use the default value.
2. Use `GetSessionOrGlobalSystemVar`(use the session system variable value if it exists, otherwise use the global system variable value).
Which ways do you prefer?

Comment (xiongjiwei) [reply executor/adapter.go:441]: I think to be default value is fine

Comment (morgo) [reply executor/adapter.go:441]: defaults are safer for internal sessions. Probably outside of the scope here, but we should even consider making internal sessions only use defaults unless a variable has a special flag saying it should apply to internal sessions.

Consider the case that the user changes the Txn Isolation, Optimistic/Pessimistic locking, change in lock wait timeout etc. These could affect how statements execute quite a lot, resulting in bugs.

Comment (xuyifangreeneyes) [reply executor/adapter.go]: Changed to use default value. PTAL @xiongjiwei @morgo @bb7133

**Review by xiongjiwei — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]
