### PR TITLE
ddl: fill in original default for extra writable columns in batch insert

### LINKED ISSUE #40192: Index column offset out of bound
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
	store, dom := testkit.CreateMockStoreAndDomainWithSchemaLease(t, dbTestLease)

	tk := testkit.NewTestKit(t, store)
	tk2 := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk2.MustExec("use test")
	tk.MustExec("CREATE TABLE t (  `b7b8a741-2759-4111-a78c-66f85cad4b59` bigint(20) DEFAULT '-5604021856061349662',   `5183ba5d-7305-4e49-8859-9b0e3ca99393` float DEFAULT '1.5656552',  UNIQUE KEY `b668df57-0687-4b20-a829-790ebd5cc2bf` (`b7b8a741-2759-4111-a78c-66f85cad4b59`),  KEY `5d3a3c82-ede6-4583-8f83-28f3a8cb8777` (`b7b8a741-2759-4111-a78c-66f85cad4b59`),  KEY `23501b4f-3274-4d3f-8305-f355d4949ae6` (`b7b8a741-2759-4111-a78c-66f85cad4b59`),  KEY `4ad74ca0-1470-44e7-94bd-772dcad6fa5f` (`b7b8a741-2759-4111-a78c-66f85cad4b59`))")

	hook := &ddl.TestDDLCallback{Do: dom}
	var checkErr1, checkErr2 error
	hook.OnJobRunBeforeExported = func(job *model.Job) {
		if job.SchemaState != model.StateWriteOnly {
			return
		}
		_, checkErr1 = tk2.Exec("insert ignore into t values (1)")
		if checkErr1 != nil && strings.Contains(checkErr1.Error(), "Index column") {
			checkErr2 = checkErr1
		}
	}
	dom.DDL().SetHook(hook)
	tk.MustExec("alter table t drop column `b7b8a741-2759-4111-a78c-66f85cad4b59`")
	require.NoError(t, checkErr2)
```

### 2. What did you expect to see? (Required)
Pass

### 3. What did you see instead (Required)
Index column b7b8a741-2759-4111-a78c-66f85cad4b59 offset out of bound, offset: 1, row: [KindFloat32 1]
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #40192

Problem Summary:

When a column is in write-only state, the `INSERT ignore` statement without specifying columns doesn't fill in the origin default value. `INSERT` actually works, because it appends, see https://github.com/pingcap/tidb/blob/95f0dc547e9517ed9de31a92eb0dc3d97ab3121f/table/tables/tables.go#L798-L813

This case can also work well with unique index (if the origin default value is NULL) and NOT NULL.

It also avoids inserting more than 1 rows if the columns is NOT NULL and write-only (as the user cannot set a value for it). I doubt whether it is expected. (However, many other places depend on this behavior, and as I've tried, modifying this behavior is really scarying... I didn't touch it in this PR).

### What is changed and how it works?

Append the origin default value if there are extra write-only column.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that batch inserting data while dropping column could cause panic.
```

### CODE REVIEW

**Comment by YangKeao** [comment]
Oops, `WritableCols` doesn't filter out hidden columns. I should add a new method to return hidden and writable columns :thinking: .

**Review by wjhuang2016 — APPROVED** [review]

**Comment by YangKeao** [comment]
Oops. Cooperating with the `alter column` seems to be a problem, as it's implemented by adding a new column and removing the old one. If we ask user to insert to the removing one while it's write-only, the user will get an error (as though there are only two columns, the user will have to insert 3 :facepalm: ). That's why a lot of tests have failed.

Let me learn / think more about online DDL.

**Comment by YangKeao** [comment]
I tried to hide the changing column, then the test gives me an error: `[kv:1062]Duplicate entry '0' for key 't.PRIMARY'`

**Comment by YangKeao** [comment]
> I tried to hide the changing column, then the test gives me an error: `[kv:1062]Duplicate entry '0' for key 't.PRIMARY'`

Modifying the `.Cols()` to `.WritableCols()` in `AddRecord` fixes this problem. I'm not sure whether there are more codes which need to modify... Only tests could tell me....

File: ddl/column_test.go [hunk 1]
```diff
@@ -985,3 +985,24 @@ func TestIssue39080(t *testing.T) {
...
+	hook := &ddl.TestDDLCallback{Do: dom}
+	hook.OnJobRunBeforeExported = func(job *model.Job) {
+		if job.SchemaState != model.StateWriteOnly {
+			return
+		}
+		tk2.MustExec("insert ignore into t values (1)")
+		tk2.MustExec("insert ignore into t values (2)")
+	}
+	dom.DDL().SetHook(hook)
+	tk.MustExec("alter table t drop column `col1`")
```
Comment (zimulala) [inline ddl/column_test.go:1007]: Please add a test about `modify column`（the column has unique key）.

File: executor/batch_checker.go [hunk 2]
```diff
@@ -146,8 +146,30 @@ func getKeysNeedCheckOneRow(ctx sessionctx.Context, t table.Table, row []types.D
...
 	}
 
-	// addChangingColTimes is used to fetch values while processing "modify/change column" operation.
-	addChangingColTimes := 0
+	// extraColumns is used to fetch values while processing "add/drop/modify/change column" operation.
+	extraColumns := 0
+	for _, col := range t.WritableCols() {
+		// if there is a changing column, append the dependency column for index fetch values
+		if col.ChangeStateInfo != nil && col.State != model.StatePublic {
+			// I'm not sure why this value doesn't need to be casted
```
Comment (zimulala) [inline executor/batch_checker.go:154]: I think we need to cast the value here. Please help add it？

**Comment by zimulala** [comment]
> append default origin column value for write-only column



> > I tried to hide the changing column, then the test gives me an error: `[kv:1062]Duplicate entry '0' for key 't.PRIMARY'`
> 
> Modifying the `.Cols()` to `.WritableCols()` in `AddRecord` fixes this problem (the former one doesn't include write-only columns). I'm not sure whether there are more codes which need to be modified... Only tests could tell me....

Could you consider dropping the UK first and then the column (like a multi-schema change)? Please create an issue.

File: ddl/column_test.go (hunk 1 above)
Comment (YangKeao) [reply ddl/column_test.go]: Done. I test the `change column` before `drop column`, so that I don't need to add back the column and its index.

File: executor/batch_checker.go (hunk 2 above)
Comment (YangKeao) [reply executor/batch_checker.go]: Good. Done.

**Comment by YangKeao** [comment]
> Could you consider dropping the UK first and then the column (like a multi-schema change)? Please create an issue.

https://github.com/pingcap/tidb/issues/40342 Issue created.

**Review by zimulala — APPROVED** [review]
LGTM
