### PR TITLE
planner: handle the projection between the join group

### LINKED ISSUE #50229: planner: Projection operator leads to join order failure and leading hint cannot take effect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table a (c1 decimal(65,30), c2 int, c3 int);
create table b (c1 int, c2 int, c3 int);
create table c (c1 int, c2 int, c3 int);

explain select * from c, b, a where c.c1=a.c1 and b.c2=a.c2;
+--------------------------------------+--------------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                   | estRows      | task      | access object | operator info                                                                                                                                  |
+--------------------------------------+--------------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_14                        | 124750125.00 | root      |               | lifedata.c.c1, lifedata.c.c2, lifedata.c.c3, lifedata.b.c1, lifedata.b.c2, lifedata.b.c3, lifedata.a.c1, lifedata.a.c2, lifedata.a.c3          |
| └─HashJoin_16                        | 124750125.00 | root      |               | inner join, equal:[eq(lifedata.a.c2, lifedata.b.c2) eq(lifedata.a.c1, Column#13)]                                                              |
|   ├─TableReader_19(Build)            | 9990.00      | root      |               | data:Selection_18                                                                                                                              |
|   │ └─Selection_18                   | 9990.00      | cop[tikv] |               | not(isnull(lifedata.a.c2))                                                                                                                     |
|   │   └─TableFullScan_17             | 10000.00     | cop[tikv] | table:a       | keep order:false, stats:pseudo                                                                                                                 |
|   └─Projection_20(Probe)             | 99900000.00  | root      |               | lifedata.c.c1, lifedata.c.c2, lifedata.c.c3, lifedata.b.c1, lifedata.b.c2, lifedata.b.c3, cast(lifedata.c.c1, decimal(10,0) BINARY)->Column#13 |
|     └─Projection_21                  | 99900000.00  | root      |               | lifedata.c.c1, lifedata.c.c2, lifedata.c.c3, lifedata.b.c1, lifedata.b.c2, lifedata.b.c3                                                       |
|       └─HashJoin_23                  | 99900000.00  | root      |               | CARTESIAN inner join                                                                                                                           |
|         ├─TableReader_26(Build)      | 9990.00      | root      |               | data:Selection_25                                                                                                                              |
|         │ └─Selection_25             | 9990.00      | cop[tikv] |               | not(isnull(lifedata.b.c2))                                                                                                                     |
|         │   └─TableFullScan_24       | 10000.00     | cop[tikv] | table:b       | keep order:false, stats:pseudo                                                                                                                 |
|         └─TableReader_28(Probe)      | 10000.00     | root      |               | data:TableFullScan_27                                                                                                                          |
|           └─TableFullScan_27         | 10000.00     | cop[tikv] | table:c       | keep order:false, stats:pseudo                                                                                                                 |
+--------------------------------------+--------------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------+


explain select /*+ leading(a, b) */ * from c, b, a where c.c1=a.c1 and b.c2=a.c2;
mysql> show warnings;
+---------+------+------------------------------------------------------------------------+
| Level   | Code | Message                                                                |
+---------+------+------------------------------------------------------------------------+
| Warning | 1815 | leading hint is inapplicable, check if the leading hint table is valid |
+---------+------+------------------------------------------------------------------------+

explain select /*+ leading(a, c) */ * from c, b, a where c.c1=a.c1 and b.c2=a.c2;
mysql> show warnings;
+---------+------+------------------------------------------------------------------------+
| Level   | Code | Message                                                                |
+---------+------+------------------------------------------------------------------------+
| Warning | 1815 | leading hint is inapplicable, check if the leading hint table is valid |
+---------+------+------------------------------------------------------------------------+
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

The optimizer should choose to join `(a, c)` or `(a, b)` first, and the `leading` hint should take effect.

### 3. What did you see instead (Required)

The optimizer chose to join `(b, c)` first which leads to a CARTESIAN join, and the `leading` hint cannot take effect.

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.5.0-dirty
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: HEAD
UTC Build Time: 2024-01-09 08:54:36
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### 5. Analysis

First, this SQL is converted to `J(J(b, c), a)` at the rewrite phase, then since `a.c1` and `c.c1` have different types, and to perform `c.c1=a.c1`, the optimizer added a Projection upon `J(b, c)`, then the plan is `J(P(J(b, c)), a)`. 
In our current join reorder algorithm (which is also the place where the `leading` hint take effect), the `Projection` prevents the optimizer from falttening the 3-table join into 3 join group, and cause this issue.

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/50229

Problem Summary:
handle the projection between the join group

### What changed and how does it work?
https://docs.google.com/document/d/1x5QDc0i9ks9Jy-I2f_3_lsz3oqu1lFbcb-1h3zAD6a4

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **New Features**
  * Added a session/system toggle to let the optimizer look through projections during join reordering.

* **Improvements**
  * Enable safe projection inlining with propagation of derived-column mappings for more accurate join planning.
  * Improved join-reorder edge alignment, expression injection/reuse, fallback behavior, and schema-restoration handling.

* **Bug Fixes**
  * Invalidate cached expression hashes after in-place mutations to avoid stale comparisons.
  * Ensure recursive CTE re-optimization refreshes logical plan state.

* **Tests**
  * Added integration and unit tests for projection inlining, substitution safety, and cache invalidation.

### CODE REVIEW

File: pkg/expression/util.go [hunk 1]
```diff
@@ -600,7 +601,11 @@ func ColumnSubstituteImpl(ctx BuildContext, expr Expression, schema *Schema, new
 				} else {
 					// for grouping function recreation, use clone (meta included) instead of newFunction
 					e = v.Clone()
-					e.(*ScalarFunction).Function.getArgs()[0] = newArg
+					sf := e.(*ScalarFunction)
```
Comment (guo-shaoge) [inline pkg/expression/util.go:604]: looks like the original code didn't clean hash code after replacing its args, why ti can still work? we expect something should be wrong, right?

File: pkg/planner/core/operator/logicalop/logical_cte.go [hunk 2]
```diff
@@ -208,7 +208,7 @@ func (p *LogicalCTE) DeriveStats(_ []*property.StatsInfo, selfSchema *expression
 	}
 	if p.Cte.RecursivePartLogicalPlan != nil {
 		if p.Cte.RecursivePartPhysicalPlan == nil {
-			_, p.Cte.RecursivePartPhysicalPlan, _, err = utilfuncp.DoOptimize(context.TODO(), p.SCtx(), p.Cte.OptFlag, p.Cte.RecursivePartLogicalPlan)
+			p.Cte.RecursivePartLogicalPlan, p.Cte.RecursivePartPhysicalPlan, _, err = utilfuncp.DoOptimize(context.TODO(), p.SCtx(), p.Cte.OptFlag, p.Cte.RecursivePartLogicalPlan)
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_cte.go:222]: is this a bug for the original code path?

File: pkg/planner/core/rule_join_reorder_projection_inline.go [hunk 3]
```diff
@@ -0,0 +1,386 @@
...
+	return colExprMap
+}
+
+// outerJoinSideFiltersTouchMultipleLeaves checks whether the outer-join filters depend on more than one
+// leaf on the outer side. If so, we conservatively disable join reordering for this join node.
+//
+// When projections are inlined under the outer side, join conditions may reference derived columns that
+// are not contained in any leaf schema. We substitute those derived columns via `outerColExprMap` before
+// extracting referenced columns.
+func outerJoinSideFiltersTouchMultipleLeaves(
```
Comment (guo-shaoge) [inline pkg/planner/core/rule_join_reorder_projection_inline.go]: better put this into `pkg/planner/core/joinorder/util.go`
PS: I think this logic of this function is really odd and hard to understand, it's a targeted-fix for a specific bug, I'll remove this logic in the future.

File: pkg/planner/core/operator/logicalop/logical_cte.go (hunk 2 above)
Comment (Reminiscent) [reply pkg/planner/core/operator/logicalop/logical_cte.go:222]: Yes, I think this was an issue on the original path as well, and it is not a drive-by fix.

After supporting this feature, the problem became visible because we now need the optimized logical plan returned by `DoOptimize()` to stay aligned with the physical plan in this CTE path too. The seed part already writes back both logical and physical plans, while the recursive part used to keep only the physical plan and then still read stats/ schema from the old logical tree. So I updated the recursive branch to keep the optimized logical plan as well.

File: pkg/planner/core/rule_join_reorder_projection_inline.go (hunk 3 above)
Comment (Reminiscent) [reply pkg/planner/core/rule_join_reorder_projection_inline.go]: Agree. This helper is mainly a scope guard for the current feature.

Right now we only want to support a conservative subset of projection-inlining cases. After inlining, outer-join filters may still reference derived columns, so this helper first substitutes them through `outerColExprMap`, and then rejects cases where those filters touch multiple outer-side leaves. The goal here is to keep the current feature within a safe supported range, instead of trying to fully generalize outer-join reorder in this PR.

File: pkg/expression/util.go (hunk 1 above)
Comment (Reminiscent) [reply pkg/expression/util.go:604]: Good catch. Yes, the old code was risky here.

`ScalarFunction` caches `HashCode()` / `CanonicalHashCode()`, and `Clone()` keeps the cached canonical hash. The old code then replaced the `grouping()` argument in place without clearing the cache, so if the canonical hash had already been computed, the cloned expression could still keep the old semantic fingerprint after substitution.

It mostly did not fail before because that requires both a warmed cache and a later caller that relies on semantic-hash-based matching. This PR makes that path more important, since join-reorder-through-projection now uses canonical-hash-based expression matching / reuse. So I clear the hash caches after the rewrite and added a test for it.

**Comment by guo-shaoge** [comment]
LGTM, please address or reply all review comments from coderabbit

**Review by guo-shaoge — APPROVED** [review]

File: pkg/expression/scalar_function.go [hunk 4]
```diff
@@ -390,7 +390,7 @@ func (sf *ScalarFunction) Equal(ctx EvalContext, e Expression) bool {
 	if !sf.RetType.Equal(fun.RetType) {
 		return false
 	}
-	if sf.hashcode != nil && fun.hashcode != nil {
+	if len(sf.hashcode) > 0 && len(fun.hashcode) > 0 {
```
[the remark this answers is not in the document]
Comment (Reminiscent) [reply pkg/expression/scalar_function.go:393]: We intentionally use len(...) > 0 as the cache-validity check. After CleanHashCode(), a zero-length slice means "cache invalid", so Equal() correctly falls back to structural comparison; the added regression test covers this case.

File: pkg/expression/scalar_function.go [hunk 5]
```diff
@@ -597,6 +598,14 @@ func (sf *ScalarFunction) CanonicalHashCode() []byte {
 	return sf.canonicalhashcode
 }
 
+// CleanHashCode cleans the cached hashcode and canonical hashcode.
+// It should be called after the function is mutated in-place (e.g. rewriting args)
+// to avoid keeping stale hash keys.
+func (sf *ScalarFunction) CleanHashCode() {
+	sf.hashcode = sf.hashcode[:0]
+	sf.canonicalhashcode = sf.canonicalhashcode[:0]
```
[the remark this answers is not in the document]
Comment (Reminiscent) [reply pkg/expression/scalar_function.go:606]: This is intentional. A zero-length slice is the invalid-cache state here, and keeping the capacity avoids unnecessary reallocations when the hash is recomputed.

File: pkg/expression/scalar_function.go [hunk 6]
```diff
@@ -747,6 +756,7 @@ func (sf *ScalarFunction) Equals(other any) bool {
 // ReHashCode is used after we change the argument in place.
 func ReHashCode(sf *ScalarFunction) {
 	sf.hashcode = sf.hashcode[:0]
+	sf.canonicalhashcode = sf.canonicalhashcode[:0]
```
[the remark this answers is not in the document]
Comment (Reminiscent) [reply pkg/expression/scalar_function.go:759]: Clearing canonicalhashcode in ReHashCode() is intentional. The canonical hash is rebuilt lazily by CanonicalHashCode() when needed, so this avoids stale cache without forcing extra work on the hot path.

File: pkg/planner/core/rule_join_reorder.go [hunk 7]
```diff
@@ -600,10 +739,90 @@ func (s *baseSingleGroupJoinOrderSolver) hasOtherJoinCondition(leftPlan, rightPl
...
+	// This keeps plans smaller and allows later predicates to reuse computed columns.
+	substituted := expression.ColumnSubstitute(proj.SCtx().GetExprCtx(), expr, proj.Schema(), proj.Exprs)
+	if canReuseInjectedJoinExpr(substituted) {
+		for i, e := range proj.Exprs {
+			if expression.ExpressionsSemanticEqual(e, substituted) {
+				return proj, proj.Schema().Columns[i]
+			}
+		}
+	}
+	return proj, proj.AppendExpr(expr)
```
[the remark this answers is not in the document]
Comment (Reminiscent) [reply pkg/planner/core/rule_join_reorder.go:801]: Passing the original expr here is intentional because AppendExpr() performs the projection-schema substitution itself. We also added a unit test to verify the appended expression stays in child space for an existing projection.

File: pkg/planner/core/rule_join_reorder_dp.go [hunk 8]
```diff
@@ -293,3 +337,34 @@ func findNodeIndexInGroup(group []base.LogicalPlan, col *expression.Column) (int
...
+			return -1, err
+		}
+		if idx != firstIdx {
+			// Columns span multiple nodes - this shouldn't happen for single-table expressions
+			// (which is what canInlineProjection allows), but handle it gracefully.
+			return -1, plannererrors.ErrUnknownColumn.GenWithStackByArgs(col, "JOIN REORDER RULE: columns span multiple nodes")
+		}
+	}
+
+	return firstIdx, nil
```
[the remark this answers is not in the document]
Comment (Reminiscent) [reply pkg/planner/core/rule_join_reorder_dp.go:364]: This does not surface as a user-visible planner error. Projection inlining is best-effort here: if DP cannot classify a substituted edge, we rerun join reorder with through-projection disabled and treat the projection as an atomic leaf again.

File: pkg/planner/core/rule_join_reorder_projection_inline.go [hunk 9]
```diff
@@ -0,0 +1,386 @@
...
+				continue
+			}
+			if idx != leafIdx {
+				// Cross-leaf expression.
+				return false
+			}
+		}
+	}
+	return true
+}
```
[the remark this answers is not in the document]
Comment (Reminiscent) [reply pkg/planner/core/rule_join_reorder_projection_inline.go:217]: Fixed

File: pkg/planner/core/rule_join_reorder.go [hunk 10]
```diff
@@ -34,6 +36,48 @@ import (
...
+	// Join reorder may distribute/push down conditions during constructing the new join tree.
+	// For volatile or side-effect expressions, moving them can change evaluation times/orders
+	// thus may change query results, so we skip reordering through Selection in such cases.
+	if selection, isSelection := p.(*logicalop.LogicalSelection); isSelection && p.SCtx().GetSessionVars().TiDBOptJoinReorderThroughSel &&
+		!slices.ContainsFunc(selection.Conditions, expression.IsMutableEffectsExpr) {
+		child := selection.Children()[0]
+		if _, isChildJoin := child.(*logicalop.LogicalJoin); isChildJoin {
+			childResult := extractJoinGroup(child)
+			childResult.otherConds = append(childResult.otherConds, selection.Conditions...)
+			return childResult
```
[the remark this answers is not in the document]
Comment (Reminiscent) [reply pkg/planner/core/rule_join_reorder.go:79]: Fixed

File: pkg/planner/core/rule_join_reorder_projection_inline.go [hunk 11]
```diff
@@ -0,0 +1,217 @@
...
+	}
+
+	// Only record when projection inlining actually happens (best-effort feature).
+	proj.SCtx().GetSessionVars().RecordRelevantOptVar(vardef.TiDBOptJoinReorderThroughProj)
+
+	childResult.colExprMap = buildColExprMapForProjection(proj, childResult.colExprMap)
+	return childResult, true
+}
+
+func buildColExprMapForProjection(
```
Comment (qw4990) [inline pkg/planner/core/rule_join_reorder_projection_inline.go:66]: This function name seems complex ... please add some comments for this function.

File: pkg/planner/core/rule_join_reorder.go [hunk 12]
```diff
@@ -600,10 +734,91 @@ func (s *baseSingleGroupJoinOrderSolver) hasOtherJoinCondition(leftPlan, rightPl
...
+	// residual predicate reuse.
+	newSf := expression.NewFunctionInternal(s.ctx.GetExprCtx(), funcName, originalEdge.GetStaticType(), lCol, rCol)
+	return newSf.(*expression.ScalarFunction)
+}
+
+func canReuseInjectedJoinExpr(expr expression.Expression) bool {
+	return !expression.IsMutableEffectsExpr(expr) && !expression.CheckNonDeterministic(expr)
+}
+
+func (s *baseSingleGroupJoinOrderSolver) injectExpr(p base.LogicalPlan, expr expression.Expression) (base.LogicalPlan, *expression.Column) {
```
Comment (qw4990) [inline pkg/planner/core/rule_join_reorder.go:793]: Could you add more comments about this functions? This is a key part of this PR I think...

File: pkg/planner/core/rule_join_reorder.go [hunk 13]
```diff
@@ -34,6 +36,55 @@ import (
...
+		if _, isChildJoin := child.(*logicalop.LogicalJoin); isChildJoin {
+			childResult := extractJoinGroup(child)
+			selectionConds := selection.Conditions
+			if len(childResult.colExprMap) > 0 {
+				selectionConds = joinorder.SubstituteColsInExprs(selectionConds, childResult.colExprMap)
+			}
+			childResult.otherConds = append(childResult.otherConds, selectionConds...)
+			return childResult
+		}
+	} else if proj, isProj := p.(*logicalop.LogicalProjection); isProj && p.SCtx().GetSessionVars().TiDBOptJoinReorderThroughProj {
```
Comment (qw4990) [inline pkg/planner/core/rule_join_reorder.go:81]: Could you add a TODO comment here? If it's a double-projection pattern, this can't work, we might need to optimize this in the future...
```
Proj
    Proj
        Join
```

**Review by qw4990 — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
lgtm

**Review by terry1purcell — APPROVED** [review]
Please ensure that there is a doc PR for the variable change
