### PR TITLE
ddl: stable create expression index test

### LINKED ISSUE #29989: Unstable test TestCreateUniqueExpressionIndex
The link: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/46891/

```
[2021-11-22T03:16:48.698Z] FAIL: db_change_test.go:1868: serialTestStateChangeSuite.TestCreateUniqueExpressionIndex
[2021-11-22T03:16:48.698Z] 
[2021-11-22T03:16:48.698Z] db_change_test.go:1972:
[2021-11-22T03:16:48.698Z]     tk.MustQuery("select * from t order by a, b").Check(testkit.Rows("0 11", "1 7", "2 7", "5 7", "8 8", "11 10", "13 9"))
[2021-11-22T03:16:48.698Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:67:
[2021-11-22T03:16:48.698Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
[2021-11-22T03:16:48.698Z] ... obtained string = "" +
[2021-11-22T03:16:48.698Z] ...     "[1 7]\n" +
[2021-11-22T03:16:48.698Z] ...     "[2 7]\n" +
[2021-11-22T03:16:48.698Z] ...     "[5 7]\n" +
[2021-11-22T03:16:48.698Z] ...     "[8 8]\n" +
[2021-11-22T03:16:48.698Z] ...     "[10 10]\n" +
[2021-11-22T03:16:48.698Z] ...     "[11 10]\n" +
[2021-11-22T03:16:48.698Z] ...     "[13 9]\n" +
[2021-11-22T03:16:48.698Z] ...     "[13 11]\n"
[2021-11-22T03:16:48.698Z] ... expected string = "" +
[2021-11-22T03:16:48.698Z] ...     "[0 11]\n" +
[2021-11-22T03:16:48.698Z] ...     "[1 7]\n" +
[2021-11-22T03:16:48.698Z] ...     "[2 7]\n" +
[2021-11-22T03:16:48.698Z] ...     "[5 7]\n" +
[2021-11-22T03:16:48.698Z] ...     "[8 8]\n" +
[2021-11-22T03:16:48.698Z] ...     "[11 10]\n" +
[2021-11-22T03:16:48.698Z] ...     "[13 9]\n"
[2021-11-22T03:16:48.698Z] ... sql:select * from t order by a, b, args:[]
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #29989

If waitReorg timeout, the worker may enter writeReorg more than 2 times. 

### What is changed and how it works?

Do DML exactly twice.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: ddl/db_change_test.go [hunk 1]
```diff
@@ -1819,6 +1819,7 @@ func (s *serialTestStateChangeSuite) TestCreateExpressionIndex(c *C) {
 	stateWriteOnlySQLs := []string{"insert into t values (8, 8)", "begin pessimistic;", "insert into t select * from t", "rollback", "insert into t set b = 9", "update t set b = 7 where a = 2", "delete from t where b = 3"}
 	stateWriteReorganizationSQLs := []string{"insert into t values (10, 10)", "begin pessimistic;", "insert into t select * from t", "rollback", "insert into t set b = 11", "update t set b = 7 where a = 5", "delete from t where b = 6"}
 
+	reorgTime := 0
```
Comment (tangenta) [inline ddl/db_change_test.go:1822]:
```suggestion
    // If waitReorg timeout, the worker may enter writeReorg more than 2 times.
	reorgTime := 0
```

File: ddl/db_change_test.go [hunk 2]
```diff
@@ -1880,6 +1887,7 @@ func (s *serialTestStateChangeSuite) TestCreateUniqueExpressionIndex(c *C) {
 
 	stateDeleteOnlySQLs := []string{"insert into t values (5, 5)", "begin pessimistic;", "insert into t select * from t", "rollback", "insert into t set b = 6", "update t set b = 7 where a = 1", "delete from t where b = 4"}
 
+	reorgTime := 0
```
Comment (tangenta) [inline ddl/db_change_test.go:1890]:
```suggestion
    // If waitReorg timeout, the worker may enter writeReorg more than 2 times.
	reorgTime := 0
```

**Review by tangenta — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]
