### PR TITLE
ddl: Non clustered reorg duplicate  tidb rowid fix

### LINKED ISSUE #59680: More than one row with the same primary key when inject fault
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Deploy 5 tikv nodes, 3 pd nodes and 1 tidb node in K8S.

1. running transaction workload.
2. one thread execute: alter table table1 coalesce partition 1;
3. inject network partition.
4. Recovery before the transaction workload finish.
5. admin check table but failed.

more details can get from the following files.

[admin_check_inconsistency_8223.zip](https://github.com/user-attachments/files/18884867/admin_check_inconsistency_8223.zip)

in zip:

> - schema_and_init_data: initial schema, state and data. 
> - transaction_workload: execute concurrently.
> - ddl_sequence: DDL threads execute during transaction workload.
> - fault_injection: inject network partition.
> - logs: tidb and tikv logs.

After all workload done, table1 schema:

```sql
Mysql > show create table table1;
CREATE TABLE `table1` (
  `pkId` int DEFAULT NULL,
  `pkAttr0` int NOT NULL,
  `commonAttr0_0` varchar(10) DEFAULT NULL,
  `commonAttr1_0` double(10,2) DEFAULT NULL,
  `commonAttr2_0` double(10,2) DEFAULT NULL,
  `commonAttr3_0` decimal(10,2) DEFAULT NULL,
  `commonAttr4_0` double(10,2) DEFAULT NULL,
  PRIMARY KEY (`pkAttr0`) /*T![clustered_index] NONCLUSTERED */,
  KEY `table1index_pk` (`pkAttr0`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY KEY (`pkAttr0`) PARTITIONS 1
```

### 2. What did you expect to see? (Required)

After all workloads:

```sql
mysql> admin check table table1;
-- ok

mysql > select count(*) from table1;
+----------+
| count(*) |
+----------+
|       60 |
+----------+
1 row in set (0.01 sec)

mysql> select * from table1 order by `pkId`;
-- ok (60 rows)
```

### 3. What did you see instead (Required)

After all workloads:

```sql
mysql> admin check table table1;
-- ERROR 8223 (HY000): data inconsistency in table: table1, index: PRIMARY, handle: 3, index-values:"" != record-values:"handle: 3, values: [KindInt64 26]"

mysql > select count(*) from table1;
+----------+
| count(*) |
+----------+
|       60 |
+----------+
1 row in set (0.01 sec)


mysql> select * from table1 order by `pkId`;
+------+---------+---------------+---------------+---------------+---------------+---------------+
| pkId | pkAttr0 | commonAttr0_0 | commonAttr1_0 | commonAttr2_0 | commonAttr3_0 | commonAttr4_0 |
+------+---------+---------------+---------------+---------------+---------------+---------------+
|    0 |       3 | JgRq          |         95920 |         43560 |      88248.00 |         98193 |
|    1 |       9 | j12t          |         10690 |         42086 |      62601.00 |         43560 |
|    2 |      26 | u             |         10690 |         43560 |       7706.00 |         48231 |
|    2 |      26 | ZEp5z         |         10690 |         43560 |      82107.00 |         31888 |
|    3 |      29 | FLHo          |         43560 |         98193 |      53770.00 |         83204 |
|    4 |      39 | 4TNLwS        |         43560 |         16265 |      36410.00 |         93912 |
|    5 |      45 | K             |         10690 |         48231 |       7706.00 |         16265 |
|    6 |      62 | kKWnE         |         10690 |         16265 |       4874.00 |         95920 |
|    7 |      65 | 6             |         16265 |         95920 |      13677.00 |         31888 |
|    8 |      75 | SHDC6P        |         95920 |         95920 |      57359.00 |         98193 |
|    9 |      81 | vqxl4         |         16265 |         31888 |      14758.00 |         48231 |
|   10 |      96 | 1pOcqj        |         31888 |         31888 |      82377.00 |         93912 |
|   11 |     105 | azyMT         |         83204 |         83204 |      49523.00 |         83204 |
|   12 |     113 | b5Th          |         95920 |         95920 |      51293.00 |         95920 |
|   13 |     122 | WrsIMS        |         98193 |         98193 |      42308.00 |         98193 |
|   14 |     133 | e             |         31888 |         31888 |      52938.00 |         31888 |
|   15 |     141 | k             |         98193 |         98193 |      58418.00 |         98193 |
|   16 |     149 | T3ZnOT5       |         16265 |         16265 |      35129.00 |         16265 |
|   17 |     158 | bpWuQpg       |         10690 |         10690 |      52375.00 |         10690 |
|   18 |     170 | k             |         98193 |         98193 |      58418.00 |         98193 |
|   19 |     178 | AEMrNCH       |         43560 |         43560 |      13677.00 |         43560 |
|   20 |     183 | h5C           |         42086 |         42086 |      53083.00 |         42086 |
|   21 |     193 | jYs           |         95920 |         95920 |      58335.00 |         95920 |
|   22 |     206 | WRC           |         93912 |         93912 |      39486.00 |         93912 |
|   23 |     214 | xkZNejE       |         48231 |         48231 |      89387.00 |         48231 |
|   24 |     219 | 6LVP          |         16265 |         16265 |       8165.00 |         16265 |
|   25 |     229 | UOV3OBh       |         42086 |         42086 |      38101.00 |         42086 |
|   26 |     234 | AEMrNCH       |         43560 |         43560 |      13677.00 |         43560 |
|   27 |     246 | T3ZnOT5       |         16265 |         16265 |      35129.00 |         16265 |
|   28 |     254 | rGJ           |         16265 |         16265 |      77037.00 |         16265 |
|   29 |     269 | vglM          |         10690 |         10690 |      82645.00 |         10690 |
|   30 |     270 | uMta          |         43560 |         43560 |      79459.00 |         43560 |
|   31 |     282 | VsShWkG       |         48231 |         48231 |      38951.00 |         48231 |
|   32 |     290 | 61d           |         10690 |         10690 |       7912.00 |         10690 |
|   33 |     305 | ocLZ          |         83204 |         83204 |      72398.00 |         83204 |
|   34 |     311 | XVaPs         |         16265 |         16265 |      44323.00 |         16265 |
|   35 |     319 | j12t          |         93912 |         93912 |      57359.00 |         93912 |
|   36 |     326 | 1pOcqj        |         16265 |         16265 |       2915.00 |         16265 |
|   37 |     340 | X3            |         10690 |         10690 |      43968.00 |         10690 |
|   38 |     347 | Z6Dpd         |         43560 |         43560 |      48483.00 |         43560 |
|   39 |     355 | xkZNejE       |         48231 |         48231 |      89387.00 |         48231 |
|   40 |     366 | 6LVP          |         16265 |         16265 |       8165.00 |         16265 |
|   41 |     376 | FuKPO         |         48231 |         48231 |      23780.00 |         48231 |
|   42 |     378 | jYs           |         95920 |         95920 |      58335.00 |         95920 |
|   43 |     388 | v             |         93912 |         93912 |      81249.00 |         93912 |
|   44 |     397 | vqxl4         |         16265 |         16265 |      86415.00 |         16265 |
|   45 |     406 | o             |         43560 |         43560 |      67216.00 |         43560 |
|   46 |     414 | JgRq          |         83204 |         83204 |      24076.00 |         83204 |
|   47 |     424 | uMta          |         43560 |         43560 |      79459.00 |         43560 |
|   48 |     434 | 3LBYk         |         43560 |         43560 |       5475.00 |         43560 |
|   49 |     442 | i1uaT         |         48231 |         48231 |      54205.00 |         48231 |
|   50 |     450 | c55ZOh        |         16265 |         16265 |      52765.00 |         16265 |
|   51 |     460 | sbpu          |         31888 |         31888 |      77462.00 |         31888 |
|   52 |     470 | xR53s         |         43560 |         43560 |      88248.00 |         43560 |
|   53 |     478 | xzpfOp        |         93912 |         93912 |      98252.00 |         93912 |
|   54 |     486 | xzpfOp        |         93912 |         93912 |      98252.00 |         93912 |
|   55 |     498 | 5MrFFKP       |         93912 |         93912 |       6147.00 |         93912 |
|   56 |     506 | jYs           |         95920 |         95920 |      58335.00 |         95920 |
|   57 |     521 | MTWHV         |         98193 |         98193 |      28175.00 |         98193 |
|   58 |     528 | zU            |         98193 |         98193 |      99337.00 |         98193 |
|   59 |     535 | q5pLE         |         95920 |         95920 |      75259.00 |         95920 |
+------+---------+---------------+---------------+---------------+---------------+---------------+
61 rows in set (0.01 sec)
```

Count(*) returns 60 rows;

But select * returns 61 rows;

And we find that more than one row of columns with the same primary key (pkAttr0).

such as: pkAttr0 = 26

### 4. What is your TiDB version? (Required)

TiDB v8.5.1

```sql
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()
   |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.5.1
Edition: Community
Git Commit Hash: fea86c8e35ad4a86a5e1160701f99493c2ee547c
Git Branch: HEAD
UTC Build Time: 2025-01-16 07:38:34
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #59680

Problem Summary:
Issue is that for non-clustered, partitioned tables and REORGANIZE PARTITION (and related alters).
And possibility of EXCHANGE PARTITION, which allows duplicate _tidb_rowid's between partitions.
And the new reorganized set of partitions are not kept in-sync with the old non-reorganized partitions.

### What changed and how does it work?
Original issue was #53385. After trying both "Always generate a new _tidb_rowid", (#53770, leading to #57510) and "using AddRecord", to generate new _tidb_rowid's (#57114, leading to #59680) and having the indexes up-to-date (for the currently used set of partition), there will always be issues between the original set of partitions and the reorganized set of partitions, due to not being in sync / having the same _tidb_rowid.

This solution will make sure that if a row exists in both sets of partitions, it will always have the same _tidb_rowid.

It works like this:
During backfill, if a the currents row's tidb_rowid already exists in the new partition:
If same row (content is same as current row)
  - Skip backfilling it (since already there)
else
  - generate a new table unique _tidb_rowid and delete the current row and add it back with the new _tidb_rowid and save the same row, with the new _tidb_rowid in the new partition.

During DML:
Delete: Only delete the reorganized row if it matches both _tidb_rowid AND row content
Update: Use DELETE+INSERT (`RemoveRecord`+`AddRecord`) where DELETE is the same as above. When insert/`AddRecord` creates a new _tidb_rowid, use that newly generated id for both new and old partitions.
And INSERT: if moving between partitions in the current set of partition, then a new unique _tidb_rowid will be generated, so use that the other set of partitions as well. Else if the _tidb_rowid already exists in the other set of partitions, then generate a new _tidb_rowid and use for both sets of partitions.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fixed issues with concurrent DML during REORGANIZE PARTITION for non-clustered tables that had been EXCHANGED.
```

### CODE REVIEW

File: pkg/table/tables/partition.go [hunk 1]
```diff
@@ -1777,7 +1786,7 @@ func partitionedTableAddRecord(ctx table.MutateContext, txn kv.Transaction, t *p
 			return nil, errors.Trace(err)
 		}
 		tbl = t.getPartition(pid)
-		if !tbl.Meta().PKIsHandle && !tbl.Meta().IsCommonHandle {
+		if !tbl.Meta().HasClusteredIndex() {
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/table/tables/partition.go:1789]: Please don't suggest things that would break the code. This change is correct :)

File: pkg/table/tables/partition.go [hunk 2]
```diff
@@ -1957,53 +2039,91 @@ func partitionedTableUpdateRecord(ctx table.MutateContext, txn kv.Transaction, t
...
+				return errors.Trace(err)
+			}
+			newToKeyAndValIsSame = &same
 		}
-		if !deleteOnly {
-			tbl = t.getPartition(newTo)
-			_, err = tbl.addRecord(ctx, txn, newData, opt.GetAddRecordOpt())
+		if !*newToKeyAndValIsSame {
+			// Generate a new ID
+			newRecordHandle, err = AllocHandle(context.Background(), ctx, t)
```
Comment (Defined2014) [inline pkg/table/tables/partition.go:2104]: I have a question if we didn't alloc new handle id here just use the perious one, what will happen?

File: pkg/ddl/partition.go [hunk 3]
```diff
@@ -3826,46 +3821,91 @@ func (w *reorgPartitionWorker) BackfillData(handleRange reorgBackfillTask) (task
...
-				if err != nil {
-					return errors.Trace(err)
-				}
-
-				// Due to EXCHANGE PARTITION, the existing _tidb_rowid may collide between partitions!
-				// Generate new _tidb_rowid.
-				recordID, err := tables.AllocHandle(w.ctx, w.tblCtx, w.reorgedTbl)
-				if err != nil {
-					return errors.Trace(err)
+			if isNonClustered {
```
Comment (Defined2014) [inline pkg/ddl/partition.go:3866]: Maybe we could remove this, if `isNonClustered == false`, found always be empty.

File: pkg/table/tables/partition.go [hunk 4]
```diff
@@ -1821,31 +1830,66 @@ func (t *partitionTableWithGivenSets) GetAllPartitionIDs() []int64 {
...
 	if err != nil {
 		return errors.Trace(err)
 	}
 
-	if _, ok := t.reorganizePartitions[pid]; ok {
-		pid, err = t.locateReorgPartition(ectx.GetEvalCtx(), r)
-		if err != nil {
+	if _, ok := t.reorganizePartitions[from]; ok {
+		newFrom, err := t.locateReorgPartition(ectx.GetEvalCtx(), r)
+		if err != nil || newFrom == 0 {
```
[the remark this answers is not in the document]
Comment (Defined2014) [reply pkg/table/tables/partition.go:1870]: So need we check `from == 0` on Line1858?

File: pkg/table/tables/partition.go [hunk 5]
```diff
@@ -1821,31 +1830,66 @@ func (t *partitionTableWithGivenSets) GetAllPartitionIDs() []int64 {
...
 		if err != nil {
 			return errors.Trace(err)
 		}
+
+		if val, ok := found[string(newFromKey)]; ok {
+			same, err := dataEqRec(ctx.GetExprCtx().GetEvalCtx().Location(), t.Meta(), r, val)
+			if err != nil || !same {
+				return errors.Trace(err)
+			}
+			return t.getPartition(newFrom).RemoveRecord(ctx, txn, h, r)
```
[the remark this answers is not in the document]
Comment (Defined2014) [reply pkg/table/tables/partition.go:1891]: L1863 used `removeRecord`, seems we need change it to `RemoveRecord`

File: pkg/table/tables/partition.go (hunk 2 above)
Comment (mjonss) [reply pkg/table/tables/partition.go:2104]: Then the record in the other partition set (reorg set for <= StateWriteReorganization, original set for >= `StateDeleteReorganization`) would be overwritten. First case would mean a lost row, second case a glitch where an older transaction/tidb connection would temporarily not see old row.

File: pkg/table/tables/partition.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/table/tables/partition.go:1870]: No, since the record must be read for doing a DELETE, which means that `from` cannot be 0, it must have been read from an existing partition.

During REORGANIZE PARTITION we have two sets of partitions, currently seen partitions and "double write" partitions. Both DELETE/`RemoveRecord()` and UPDATE/`UpdateRecord()` would be called from read records from the currently seen partitions, so `from` must be `!= 0`.
When going from `StateWriteReorganization` to `StateDeleteReorganization` we are replacing the reorganized partitions to their new backfilled partitions, so then the "double write" partitions will be the old original ones, which we need to continue double writing to, in case a session still sees the previous schema state `StateWriteReorganization`.


Note:
Technically we could do DELETE without reading a row, if it would not have any indexes to be updated.

File: pkg/table/tables/partition.go [hunk 6]
```diff
@@ -1906,47 +1951,84 @@ func partitionedTableUpdateRecord(ctx table.MutateContext, txn kv.Transaction, t
...
 		}
-
-		newTo, newFrom := int64(0), int64(0)
-		if _, ok := t.reorganizePartitions[to]; ok {
-			newTo, err = t.locateReorgPartition(ectx.GetEvalCtx(), newData)
-			// There might be valid cases when errors should be accepted?
-			if err != nil {
-				return errors.Trace(err)
-			}
+		// and add record to new partition, which will also give it a new Record ID/_tikv_rowid!
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/table/tables/partition.go]: Yep, typo...

File: pkg/table/tables/partition.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/table/tables/partition.go]: Since we already created the new `table.RemoveRecordOpt` at L1855, it is better to use the `removeRecord` consistently in `(*partitionedTable) RemoveRecord`, which I just fixed thanks your review :)

File: pkg/ddl/partition.go (hunk 3 above)
Comment (mjonss) [reply pkg/ddl/partition.go]: Done, thanks for the suggestion!

**Review by Defined2014 — APPROVED** [review]

File: pkg/ddl/partition.go [hunk 7]
```diff
@@ -3826,46 +3821,88 @@ func (w *reorgPartitionWorker) BackfillData(handleRange reorgBackfillTask) (task
...
-				key = tablecodec.EncodeRecordKey(key[:tablecodec.TableSplitKeyLen+2], recordID)
+				for _, col := range w.table.WritableCols() {
+					d, ok := w.rowMap[col.ID]
+					if !ok {
+						return dbterror.ErrUnsupportedReorganizePartition.GenWithStackByArgs()
+					}
+					tmpRow[col.Offset] = d
+				}
+				// Use RemoveRecord/AddRecord to keep the indexes in-sync!
+				pt := w.table.GetPartitionedTable().GetPartition(currPartID)
```
Comment (tangenta) [inline pkg/ddl/partition.go:3891]: For a batch of `w.rowRecords`, are all `currPartID` the same?

Comment (mjonss) [reply pkg/ddl/partition.go:3891]: @tangenta yes, the copying will be done one partition at a time.
The next partition is calculated in `getNextPartitionInfo()` called by `updateReorgInfo` called by `updatePhysicalTableRow` after `w.writePhysicalTableRecord()` is done. `w.writePhysicalTableRow` will backfill all table data from one partition. `updatePhysicalTableRow` is called by `reorgPartitionDataAndIndex`.

File: pkg/table/tables/partition.go [hunk 8]
```diff
@@ -1821,31 +1830,66 @@ func (t *partitionTableWithGivenSets) GetAllPartitionIDs() []int64 {
...
-		err = tbl.removeRecord(ctx, txn, h, r, opt)
+
+		if t.Meta().HasClusteredIndex() {
+			return t.getPartition(newFrom).removeRecord(ctx, txn, h, r, opt)
+		}
+		var found map[string][]byte
+		encodedRecordID := codec.EncodeInt(nil, h.IntValue())
+		newFromKey := tablecodec.EncodeRowKey(newFrom, encodedRecordID)
+
+		found, err = txn.BatchGet(context.Background(), []kv.Key{newFromKey})
```
Comment (tangenta) [inline pkg/table/tables/partition.go:1881]: If there is only one key, maybe use `txn.Get()` is more efficient?

Comment (mjonss) [reply pkg/table/tables/partition.go:1881]: Thanks for the suggestion, I will change it to `getKeyInTxn()` that does `txn.Get()` and checks if key was found or not.

@tangenta should I try to optimize the the `txn.BatchGet()` in `partitionedTableUpdateRecord()` below as well? I would assume that the normal/hot path would be `newFrom == newTo`, so it would only be a single key, otherwise two keys.

Comment (mjonss) [reply pkg/table/tables/partition.go]: I also optimized `partitionedTableUpdateRecord()` to do `txn.Get()`/`getKeyInTxn()` instead of `txn.BatchGet()`

**Review by tangenta — APPROVED** [review]
