### PR TITLE
executor: recognize PointGet and BatchPointGet in admin check

### LINKED ISSUE #64731: `ADMIN CHECK` plan checking doesn't work because it may use `BatchPointGet` or `PointGet`.
## Enhancement

For the following function:

```go
func verifyIndexSideQuery(ctx context.Context, se sessionctx.Context, sql string) bool {
	rows, err := queryToRow(ctx, se, "explain "+sql)
	if err != nil {
		return false
	}

	isTableScan := false
	isIndexScan := false
	for _, row := range rows {
		op := row.GetString(0)
		if strings.Contains(op, "TableFullScan") {
			isTableScan = true
		} else if strings.Contains(op, "IndexFullScan") || strings.Contains(op, "IndexRangeScan") {
			// It's also possible to be index range scan if the index has condition.
			// TODO: if the planner eliminates the range in the index scan, we can remove the `IndexRangeScan` check.
			isIndexScan = true
		}
	}

	if isTableScan || !isIndexScan {
		return false
	}
	return true
}
```

It only allows `IndexFullScan` and `IndexRangeScan`. However, it may also generate `PointGet` and `BatchPointGet` plan when the column is an enum.

### PR DESCRIPTION
**Pull request by shenyv1**
### What problem does this PR solve?

Issue Number: close #64731

Problem Summary:
The verifyIndexSideQuery function didn't recognize PointGet and BatchPointGet 
as valid index access methods, causing ADMIN CHECK to fail when checking indexes 
on enum columns or unique indexes.

### What changed and how does it work?

Modified the verifyIndexSideQuery function to accept PointGet and BatchPointGet 
operators as valid index access plans, in addition to IndexFullScan and IndexRangeScan.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fixed admin check failure for enum columns with unique indexes
```

### CODE REVIEW

**Comment by lance6716** [comment]
Please consider that point get may not be a index access

```
mysql> use test
Database changed
mysql> create table t (c int key, c2 int unique key);
Query OK, 0 rows affected (0.057 sec)

mysql> insert into t values (1,1);
Query OK, 1 row affected (0.005 sec)

mysql> explain select c from t where c = 1;
+-------------+---------+------+---------------+---------------+
| id          | estRows | task | access object | operator info |
+-------------+---------+------+---------------+---------------+
| Point_Get_1 | 1.00    | root | table:t       | handle:1      |
+-------------+---------+------+---------------+---------------+
1 row in set (0.001 sec)

mysql> explain select c2 from t where c2 = 1;
+-------------+---------+------+-----------------------+---------------+
| id          | estRows | task | access object         | operator info |
+-------------+---------+------+-----------------------+---------------+
| Point_Get_1 | 1.00    | root | table:t, index:c2(c2) |               |
+-------------+---------+------+-----------------------+---------------+
1 row in set (0.001 sec)
```

**Comment by shenyv1** [comment]
@lance6716 Thank you for pointing this out! You're right.

  After analyzing the code, I found the solution:

  ## Analysis

  From `pkg/planner/core/common_plans.go:698`, regular `explain` output has 5 columns, and **access object is at 
  column 3** (0-indexed).

  From `pkg/planner/core/access/access_obj.go:52-69`, I found that the `String()` method can write two formats for
  index access:
  - `, index:xxx` for regular indexes
  - `, clustered index:xxx` for clustered indexes

  While table access only shows `table:xxx` without any index information.

  ## Proposed Fix

  ```go
  else if strings.Contains(op, "PointGet") || strings.Contains(op, "BatchPointGet") {
      if row.Len() > 3 {
          accessObject := row.GetString(3)
          // Check for " index:" to match both ", index:" and ", clustered index:"
          if strings.Contains(accessObject, " index:") {
              isIndexScan = true
          } 
      }
  }

  To avoid matching table names that contain "index", check string  " index:" instead

  Is this approach correct? 
  Thank you!

**Comment by shenyv1** [comment]
Hi @YangKeao  @wjhuang2016 , just a friendly ping! Would appreciate it if you could take a look when you have a chance. Thanks!

**Comment by wjhuang2016** [comment]
`clustered indexes` in fact is a table scan.

File: pkg/executor/check_table_index.go [hunk 1]
```diff
@@ -386,6 +386,13 @@ func verifyIndexSideQuery(ctx context.Context, se sessionctx.Context, sql string
 			// It's also possible to be index range scan if the index has condition.
 			// TODO: if the planner eliminates the range in the index scan, we can remove the `IndexRangeScan` check.
 			isIndexScan = true
+		} else if strings.Contains(op, "PointGet") || strings.Contains(op, "BatchPointGet") {
```
Comment (wjhuang2016) [inline pkg/executor/check_table_index.go:389]:
```
mysql> create table t (c int, c2 int unique key, primary key(c, c2) clustered);
Query OK, 0 rows affected (0.032 sec)

mysql> explain select c from t where (c, c2) in ( (1, 4), (2, 2));
+-------------------+---------+------+-----------------------------------------+------------------------------+
| id                | estRows | task | access object                           | operator info                |
+-------------------+---------+------+-----------------------------------------+------------------------------+
| Batch_Point_Get_1 | 2.00    | root | table:t, clustered index:PRIMARY(c, c2) | keep order:false, desc:false |
+-------------------+---------+------+-----------------------------------------+------------------------------+
1 row in set (0.002 sec)
```

It shouldn't be considered as an index path

Comment (YangKeao) [reply pkg/executor/check_table_index.go:389]: ~~Agree. It'd be better to have a `isPointGet`. And modify the following condition into:~~

```
if isTableScan || !(isIndexScan || isPointGet) {
    return false
}
```

~~For both `isIndexScan` or `isPointGet`, they should pass this function.~~

~~The behavior is actually the same with the original implementation of this PR. Adding a new variable `isPointGet` is just to make it clearer.~~

Please see the following comment. This one is wrong :facepalm:

Comment (lance6716) [reply pkg/executor/check_table_index.go:389]: > For both isIndexScan or isPointGet, they should pass this function.

I don't know the background of the issue. I guess ADMIN CHECK should compare 
a) the handle access path, and 
b) the index access path,
so we must separate point get into these two types? Treating all point get as index access path is not expected?

Comment (YangKeao) [reply pkg/executor/check_table_index.go:389]: > so we must separate point get into these two types? Treating all point get as index access path is not expected?

@lance6716 You are right! We should also check the point get / batch point get are using the index.

I think we can check it using the following condition
```go
accessObject := row.GetString(3)
if (strings.Contains(accessObject, "index") && !strings.Contains(accessObject, "clustered index")) && (strings.Contains(op, "PointGet") || strings.Contains(op, "BatchPointGet")) {
    isIndexScan = true
}
```

This condition looks quite ugly. Do you have better ideas?

Another option in my mind is to assert whether the object contains the index name: `strings.Contains(accessObject, idxName)` and the `idxName` can be passed by the caller, but it'll need a wider modification.

Comment (shenyv1) [reply pkg/executor/check_table_index.go:389]: Thank you for the review! Here is my approach:
```
} else if strings.Contains(op, "PointGet") || strings.Contains(op, "BatchPointGet") {
    if row.Len() > 3 {
        accessObject := row.GetString(3)
        if strings.Contains(accessObject, ", index:") {
            isIndexScan = true
        }
    }
}
```
Using `", index:"` will match statements like `"table:t, index:idx(col)"`, but will NOT match `"table:t, clustered index:PRIMARY(col)"` 

Do you think this approach is better?

File: pkg/executor/check_table_index.go [hunk 2]
```diff
@@ -389,7 +389,7 @@ func verifyIndexSideQuery(ctx context.Context, se sessionctx.Context, sql string
 		} else if strings.Contains(op, "PointGet") || strings.Contains(op, "BatchPointGet") {
 			if row.Len() > 3 {
 				accessObject := row.GetString(3)
-				if strings.Contains(accessObject, " index:") {
+				if strings.Contains(accessObject, ", index:") {
```
Comment (wjhuang2016) [inline pkg/executor/check_table_index.go:395]: Please add a comment to explain why adding a ',' here

**Comment by YangKeao** [comment]
For `idc-jenkins-ci-tidb/check_dev`, please follow the instruction to fix the CI:

Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents with ctrl-D as ending):
```
diff --git a/pkg/executor/test/admintest/BUILD.bazel b/pkg/executor/test/admintest/BUILD.bazel
index 1fddefbef3..192de198b8 100644
--- a/pkg/executor/test/admintest/BUILD.bazel
+++ b/pkg/executor/test/admintest/BUILD.bazel
@@ -8,7 +8,7 @@ go_test(
         "main_test.go",
     ],
     flaky = True,
-    shard_count = 26,
+    shard_count = 27,
     deps = [
         "//pkg/config",
         "//pkg/ddl",
```

If you have `bazel`, you can also run `make bazel_prepare` to update the `BUILD.bazel`. Or you could also manually modify the `shard_count` from 26 to 27 in `pkg/executor/test/admintest/BUILD.bazel`. They should have the same effect.

For `idc-jenkins-ci-tidb/mysql-test`, I guess we met an unstable test :facepalm: . Simply `/retest` should make it pass.

**Review by lance6716 — APPROVED** [review]

**Comment by YangKeao** [comment]
/retest

:angry:
