### PR TITLE
ddl: temporarily disable lossy ddl optimization

### LINKED ISSUE #64671: lossy ddl optimization may leads to wrong table stats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Introduced by https://github.com/pingcap/tidb/pull/64123, see the discussion in https://github.com/pingcap/tidb/pull/64464 for more detail.

### 2. What did you expect to see? (Required)

The stats collected by `ANALYZE TABLE` is correct after ddl.

### 3. What did you see instead (Required)

We can't guarantee the stats of column after modify column is correct in any case. For some scenarios, it may leads to wrong cardinality estimation.

### 4. What is your TiDB version? (Required)

release-8.5

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #64671, ref #63366

Problem Summary:

For optimized lossy modify column, we change the column type in place, without creating a new column. So when collecting stats after reorg, we are still using the old type to calculate histogram and topN. Thus the stats collected is invalid, and it may cause worse estimation than using pseudo stats.

### What changed and how does it work?

Currently, we disable all lossy ddl optimization, and we will reopen it again after we find a good way to solve with stats problem.

### Check List

Tests 

- [x] Unit test **skip tests related to code changes**
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test 
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by joechenrh** [comment]
/hold 
Let me think carefully if I miss something, as it's a hotfix. (But it still need to be merged today.)

**Review by fzzf678 — APPROVED** [review]

File: pkg/ddl/modify_column.go [hunk 1]
```diff
@@ -1845,20 +1818,9 @@ func noReorgDataStrict(tblInfo *model.TableInfo, oldCol, newCol *model.ColumnInf
 		return !needTruncationOrToggleSign()
 	}
 
-	oldTp := oldCol.GetType()
-	newTp := newCol.GetType()
-	// VARCHAR->CHAR, may need reorg.
-	if types.IsTypeVarchar(oldTp) && newTp == mysql.TypeString {
+	if ConvertBetweenCharAndVarchar(oldCol.GetType(), newCol.GetType()) {
```
Comment (joechenrh) [inline pkg/ddl/modify_column.go]: This change is to make `CHAR` to `VARCHAR` without index can do no reorg, revert it back too.
