### PR TITLE
expression: Add cast to ensure that the actual output type of `builtin_control` is consistent with retType | tidb-test=pr/2216

### LINKED ISSUE #44196: Incorrect query result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```SQL
CREATE TABLE t1 (c1 INT);
INSERT INTO t1 VALUES (1);
SELECT c1 FROM t1 WHERE c1 REGEXP(IFNULL(c1, 0.0)); -- actual: {1}, expected: {}
```
### 2. What did you expect to see? (Required)
SELECT returns nothing.
### 3. What did you see instead (Required)
SELECT returns 1.
### 4. What is your TiDB version? (Required)

Release Version: v7.0.0
Edition: Community
Git Commit Hash: 7376954cd868dbc44fc3015c9ef89c53749339a7
Git Branch: heads/refs/tags/v7.0.0
UTC Build Time: 2023-03-29 13:32:13
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #44196 

Problem Summary:

### What is changed and how it works?
- [newBaseBuiltinFuncWithTp](https://github.com/pingcap/tidb/blob/431d30f4809f4353dfc6462e83865407d9e077a5/expression/builtin_control.go#L758) cast args to decimal/datetime/timestampe but ignores decimal, so need a new function `newBaseBuiltinFuncWithFieldTypes`
- refine `InferType4ControlFuncs` and use `InferType4ControlFuncs` in `caseWhenFunctionClass::getFunction`

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: expression/builtin_control.go [hunk 1]
```diff
@@ -231,6 +240,15 @@ func (c *caseWhenFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 		fieldTp.SetDecimal(0)
 		types.SetBinChsClnFlag(fieldTp)
 	}
+
+	// The types of the output arguments should all be retType for the CASE WHEN function.
```
Comment (SeaRise) [inline expression/builtin_control.go:244]:
```suggestion
```

File: expression/builtin.go [hunk 2]
```diff
@@ -136,6 +136,36 @@ func newBaseBuiltinFunc(ctx sessionctx.Context, funcName string, args []Expressi
 	return bf, nil
 }
 
+func newFieldTypeForBaseBuiltinFunc(funcName string, retType types.EvalType, ec *ExprCollation) *types.FieldType {
```
Comment (windtalker) [inline expression/builtin.go:139]: maybe rename to `newReturnFieldTypeForBaseBuiltinFunc`?

File: expression/builtin_control.go [hunk 3]
```diff
@@ -231,17 +231,17 @@ func (c *caseWhenFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
...
 		types.SetBinChsClnFlag(fieldTp)
 	}
-	argTps := make([]types.EvalType, 0, l)
+	argTps := make([]*types.FieldType, 0, l)
 	for i := 0; i < l-1; i += 2 {
 		if args[i], err = wrapWithIsTrue(ctx, true, args[i], false); err != nil {
 			return nil, err
 		}
-		argTps = append(argTps, types.ETInt, tp)
+		argTps = append(argTps, args[i].GetType(), fieldTp.Clone())
```
Comment (windtalker) [inline expression/builtin_control.go:239]: The second argument should be FieldType of `int/bool` ?

File: expression/builtin_control.go [hunk 4]
```diff
@@ -553,11 +553,11 @@ func (c *ifFunctionClass) getFunction(ctx sessionctx.Context, args []Expression)
 	if err != nil {
 		return nil, err
 	}
-	bf, err := newBaseBuiltinFuncWithTp(ctx, c.funcName, args, evalTps, types.ETInt, evalTps, evalTps)
+
+	bf, err := newBaseBuiltinFuncWithFieldTypes(ctx, c.funcName, args, evalTps, args[0].GetType().Clone(), retTp.Clone(), retTp.Clone())
```
Comment (windtalker) [inline expression/builtin_control.go:557]: `args[0].GetType().Clone()` should be field type of `int/bool`?

File: planner/cascades/testdata/integration_suite_out.json [hunk 5]
```diff
@@ -393,7 +393,7 @@
         "Plan": [
           "HashAgg_18 1.00 root  funcs:sum(Column#4)->Column#3",
           "└─TableReader_19 1.00 root  data:HashAgg_20",
-          "  └─HashAgg_20 1.00 cop[tikv]  funcs:sum(cast(test.t.b, decimal(10,0) BINARY))->Column#4",
+          "  └─HashAgg_20 1.00 cop[tikv]  funcs:sum(cast(test.t.b, decimal(11,1) BINARY))->Column#4",
```
Comment (windtalker) [inline planner/cascades/testdata/integration_suite_out.json:396]: Why this is affected?

File: expression/builtin_control.go (hunk 4 above)
Comment (SeaRise) [reply expression/builtin_control.go:557]: `args[0].GetType().Clone()` must be bool type because `WrapForIsTrue` has been called previously

File: expression/builtin_control.go (hunk 3 above)
Comment (SeaRise) [reply expression/builtin_control.go:239]: `args[i].GetType()` must be bool type because `WrapForIsTrue` has been called previously

File: planner/cascades/testdata/integration_suite_out.json (hunk 5 above)
Comment (SeaRise) [reply planner/cascades/testdata/integration_suite_out.json:396]: Because the test sql is `select sum(case when a <= 0 or a > 1000 then 0.0 else b end) from t`, case when may be eliminated here.

File: expression/builtin.go (hunk 2 above)
Comment (SeaRise) [reply expression/builtin.go:139]: ok, updated.

File: tests/integrationtest/r/expression/issues.result [hunk 6]
```diff
@@ -2512,6 +2512,66 @@ select * from t where t.b < t.c;
...
+if_var
+5000.0000
+0.0002
+SELECT CASE WHEN var_fld  > 5000 THEN ( 1 / var_fld ) ELSE 5000 END case_var FROM t1;
+case_var
+5000.0000
+0.0002
+SELECT CASE var_fld  > 5000 WHEN TRUE THEN ( 1 / var_fld ) ELSE 5000 END case_var FROM t1;
+case_var
+5000.0000
```
Comment (SeaRise) [inline tests/integrationtest/r/expression/issues.result:2572]: In the original code it would be 99.9999 because 5000 would be cast to decimal(6, 4)

File: expression/builtin.go [hunk 7]
```diff
@@ -176,32 +206,70 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, funcName string, args []Ex
...
+	bf.SetCharsetAndCollation(ec.Charset, ec.Collation)
+	bf.setCollator(collate.GetCollator(ec.Collation))
+	bf.SetCoercibility(ec.Coer)
+	bf.SetRepertoire(ec.Repe)
+	// note this function must be called after wrap cast function to the args
+	adjustNullFlagForReturnType(funcName, args, bf)
+	return bf, nil
+}
+
+// newBaseBuiltinFuncWithTp creates a built-in function signature with specified field types of arguments and the return type of the function.
```
Comment (windtalker) [inline expression/builtin.go:228]:
```suggestion
// newBaseBuiltinFuncWithFieldTypes creates a built-in function signature with specified field types of arguments and the return type of the function.
```

File: expression/builtin.go [hunk 8]
```diff
@@ -176,32 +206,70 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, funcName string, args []Ex
...
+// argTps indicates the field types of the args, retType indicates the return type of the built-in function.
+func newBaseBuiltinFuncWithFieldTypes(ctx sessionctx.Context, funcName string, args []Expression, retType types.EvalType, argTps ...*types.FieldType) (bf baseBuiltinFunc, err error) {
```
Comment (windtalker) [inline expression/builtin.go:230]: Add some comments about the difference between `newBaseBuiltinFuncWithFieldTypes` and `newBaseBuiltinFuncWithTP`, and when should use `newBaseBuiltinFuncWithFieldTypes`?

File: tests/integrationtest/r/expression/issues.result (hunk 6 above)
Comment (windtalker) [reply tests/integrationtest/r/expression/issues.result:2572]: Does it mean it will be a bug in the original code?

Comment (SeaRise) [reply tests/integrationtest/r/expression/issues.result:2572]: yes, fixed in https://github.com/pingcap/tidb/pull/46786/files#diff-b881614a44394d679db8bf45934c5d7b00b1600bb70da6c9a1b71b1e1e7c0173R232-R236

File: expression/builtin.go (hunk 8 above)
Comment (SeaRise) [reply expression/builtin.go:232]: ok, added

File: expression/builtin_control.go [hunk 9]
```diff
@@ -61,47 +62,69 @@ func maxlen(lhsFlen, rhsFlen int) int {
...
 
+func setCollateAndCharsetAndFlagFromArgs(ctx sessionctx.Context, funcName string, evalType types.EvalType, resultFieldType *types.FieldType, args ...Expression) error {
+	switch funcName {
+	case ast.If, ast.Ifnull, ast.WindowFuncLead, ast.WindowFuncLag:
+		if len(args) != 2 {
+			panic("unexpected length of args for if/ifnull/lead/lag")
+		}
+		lexp, rexp := args[0], args[1]
+		lhs, rhs := lexp.GetType(), rexp.GetType()
 		if types.IsNonBinaryStr(lhs) && !types.IsBinaryStr(rhs) {
```
Comment (windtalker) [inline expression/builtin_control.go:124]: how about merge the branch of `if types.IsNonBinaryStr(lhs) && !types.IsBinaryStr(rhs) {} else if types.IsNonBinaryStr(rhs) && !types.IsBinaryStr(lhs) {}` into the following
```
if types.IsNonBinaryStr(lhs) || types.IsNonBinaryStr(rhs) {
	ec, err := CheckAndDeriveCollationFromExprs(ctx, funcName, evalType, lexp, rexp)
	if err != nil {
		return nil, err
	}
	resultFieldType.SetCollate(ec.Collation)
	resultFieldType.SetCharset(ec.Charset)
	resultFieldType.SetFlag(0)
	if (!types.IsNonBinaryStr(lhs) || mysql.HasBinaryFlag(lhs.GetFlag())) || (!types.IsNonBinaryStr(rhs) && mysql.HasBinaryFlag(rhs.GetFlag())) {
		resultFieldType.AddFlag(mysql.BinaryFlag)
	}
} 
```

File: expression/builtin_control.go [hunk 10]
```diff
@@ -127,34 +150,80 @@ func InferType4ControlFuncs(ctx sessionctx.Context, funcName string, lexp, rexp
...
+	default:
+		ec, err := CheckAndDeriveCollationFromExprs(ctx, funcName, evalType, args...)
+		if err != nil {
+			return err
+		}
+		resultFieldType.SetCollate(ec.Collation)
+		resultFieldType.SetCharset(ec.Charset)
+		resultFieldType.SetFlag(0)
+		for i := range args {
+			if !types.IsNonBinaryStr(args[i].GetType()) {
```
Comment (windtalker) [inline expression/builtin_control.go:167]: according to the law of two types, the condition of add binary flag should be `if (!types.IsNonBinaryStr(args[i].GetType()) || mysql.HasBinaryFlag(args[i].GetType().GetFlag()))`?

File: expression/builtin_control.go [hunk 11]
```diff
@@ -127,34 +150,80 @@ func InferType4ControlFuncs(ctx sessionctx.Context, funcName string, lexp, rexp
...
+		// If any of arg is NULL, result type need unset NotNullFlag.
+		tempFlag := resultFieldType.GetFlag()
+		types.SetTypeFlag(&tempFlag, mysql.NotNullFlag, false)
+		resultFieldType.SetFlag(tempFlag)
+		// If both arguments are NULL, make resulting type BINARY(0).
+		resultFieldType.SetType(mysql.TypeString)
+		resultFieldType.SetFlen(0)
+		resultFieldType.SetDecimal(0)
+		types.SetBinChsClnFlag(resultFieldType)
+	} else if len(nullFields) > 0 { // one of field is TypeNull
```
Comment (windtalker) [inline expression/builtin_control.go:208]:
```suggestion
	} else if len(nullFields) > 0 { // some of fields are TypeNull
```

File: expression/builtin_control.go [hunk 12]
```diff
@@ -127,34 +150,80 @@ func InferType4ControlFuncs(ctx sessionctx.Context, funcName string, lexp, rexp
...
+		// If any of arg is NULL, result type need unset NotNullFlag.
+		*resultFieldType = *notNullFields[0]
```
Comment (windtalker) [inline expression/builtin_control.go:210]: Whyt the resultFieldType is not `types.AggFieldType` of all input types?

Comment (SeaRise) [reply expression/builtin_control.go:210]: good catch!

File: expression/builtin.go [hunk 13]
```diff
@@ -176,32 +206,72 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, funcName string, args []Ex
...
+			args[i] = WrapWithCastAsReal(ctx, args[i])
+		case types.ETString:
+			args[i] = WrapWithCastAsString(ctx, args[i])
+			args[i] = HandleBinaryLiteral(ctx, args[i], ec, funcName)
+		case types.ETDuration:
+			args[i] = WrapWithCastAsDuration(ctx, args[i])
+		case types.ETJson:
+			args[i] = WrapWithCastAsJSON(ctx, args[i])
+		// https://github.com/pingcap/tidb/issues/44196
+		// For decimal/datetime/timestamp types, it is necessary to ensure that decimal are consistent with the output type,
```
[the remark this answers is not in the document]
Comment (SeaRise) [reply expression/builtin.go]: ok, done.

File: expression/builtin_control.go (hunk 12 above)
Comment (SeaRise) [reply expression/builtin_control.go]: done

File: expression/builtin_control.go [hunk 14]
```diff
@@ -61,47 +62,69 @@ func maxlen(lhsFlen, rhsFlen int) int {
...
-		tempFlag := resultFieldType.GetFlag()
-		types.SetTypeFlag(&tempFlag, mysql.NotNullFlag, false)
-		resultFieldType.SetFlag(tempFlag)
+		resultFlen := maxArgFlen + resultFieldType.GetDecimal() + 1 // account for -1 len fields
+		resultFieldType.SetFlenUnderLimit(resultFlen)
+	} else if evalType == types.ETString {
+		maxLen := 0
+		for i := range argTps {
+			argFlen := argTps[i].GetFlen()
+			if argFlen == types.UnspecifiedLength {
```
[the remark this answers is not in the document]
Comment (SeaRise) [reply expression/builtin_control.go:85]: ok, `UnspecifiedLength` is setten here.

File: expression/builtin_control.go (hunk 10 above)
Comment (SeaRise) [reply expression/builtin_control.go]: ok, updated.

File: expression/builtin_control.go [hunk 15]
```diff
@@ -61,47 +62,69 @@ func maxlen(lhsFlen, rhsFlen int) int {
...
-			resultFieldType.SetType(mysql.TypeString)
-			resultFieldType.SetFlen(0)
-			resultFieldType.SetDecimal(0)
-			types.SetBinChsClnFlag(resultFieldType)
+func setFlenFromArgs(evalType types.EvalType, resultFieldType *types.FieldType, argTps ...*types.FieldType) {
+	if evalType == types.ETDecimal || evalType == types.ETInt {
+		maxArgFlen := 0
+		for i := range argTps {
+			flagLen := 0
+			if !mysql.HasUnsignedFlag(argTps[i].GetFlag()) {
```
[the remark this answers is not in the document]
Comment (SeaRise) [reply expression/builtin_control.go:70]: ok, added.

File: expression/builtin_control.go (hunk 9 above)
Comment (SeaRise) [reply expression/builtin_control.go:128]: It seems that the logic of the two is different...

Comment (SeaRise) [reply expression/builtin_control.go]: ok, refined.

**Review by windtalker — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Comment by SeaRise** [comment]
/hold 
until code freezen

**Comment by CalvinNeo** [comment]
Also resolves `There is no supertype for types Decimal(44,6), Decimal(65,4) because the least supertype is Decimal(67,6)` problem.
