### PR TITLE
ddl: stabilize test TestParallelDDLBeforeRunDDLJob

### LINKED ISSUE #18226: TestParallelDDLBeforeRunDDLJob hang for 10 minutes
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```

PASS: db_test.go:3521: testDBSuite3.TestTransactionWithWriteOnlyColumn	0.037s
PASS: db_test.go:2719: testDBSuite3.TestTruncateTable	0.070s
PASS: ddl_worker_test.go:1125: testDDLSuite.TestParallelDDL	1.099s
PASS: db_partition_test.go:1231: testIntegrationSuite4.TestTruncatePartitionAndDropTable	0.289s
PASS: reorg_test.go:37: testDDLSuite.TestReorg	0.459s
PASS: reorg_test.go:170: testDDLSuite.TestReorgOwner	0.224s
PASS: ddl_worker_test.go:105: testDDLSuite.TestSchemaError	0.095s
PASS: ddl_worker_test.go:121: testDDLSuite.TestTableError	0.113s
PASS: ddl_worker_test.go:167: testDDLSuite.TestViewError	0.109s
SIGQUIT: quit
PC=0x7fff713f9882 m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x8292128, 0x82920e8, 0x7ffe00000000)
	/Users/bba/.gvm/gos/go1.13/src/runtime/sys_darwin.go:378 +0x39
runtime.semasleep(0xffffffffffffffff, 0x7ffeefbff4c0)
	/Users/bba/.gvm/gos/go1.13/src/runtime/os_darwin.go:63 +0x85
runtime.notesleep(0x8291ee8)
	/Users/bba/.gvm/gos/go1.13/src/runtime/lock_sema.go:173 +0xe0
runtime.mexit(0x7ffeefbff501)
	/Users/bba/.gvm/gos/go1.13/src/runtime/proc.go:1259 +0x21f
runtime.mstart()
	/Users/bba/.gvm/gos/go1.13/src/runtime/proc.go:1176 +0x6f

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0004fc300, 0x62ba201, 0x5, 0x63b8ca0, 0x408bad6)
	/Users/bba/.gvm/gos/go1.13/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0004fc200)
	/Users/bba/.gvm/gos/go1.13/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc0004fc200, 0xc000633d88)
	/Users/bba/.gvm/gos/go1.13/src/testing/testing.go:909 +0xc9
testing.runTests(0xc0006ee960, 0x821d140, 0x1, 0x1, 0x0)
	/Users/bba/.gvm/gos/go1.13/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc0002c2280, 0x0)
	/Users/bba/.gvm/gos/go1.13/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:140 +0x1c1

goroutine 70 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0004d80a0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:32 +0x57

goroutine 97 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0006bc580)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:173 +0x3a3
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/pkg/logutil/merge_logger.go:91 +0x80

goroutine 129 [syscall, 10 minutes]:
os/signal.signal_recv(0x4061bc6)
	/Users/bba/.gvm/gos/go1.13/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
	/Users/bba/.gvm/gos/go1.13/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/Users/bba/.gvm/gos/go1.13/src/os/signal/signal_unix.go:29 +0x41

goroutine 162 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc0000f89a8)
	/Users/bba/.gvm/gos/go1.13/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0000f89a0)
	/Users/bba/.gvm/gos/go1.13/src/sync/waitgroup.go:130 +0x64
github.com/pingcap/check.RunAll(0xc000085e78, 0x0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:129 +0x4fb
github.com/pingcap/check.TestingT(0xc0004fc300)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x471
github.com/pingcap/tidb/ddl.TestT(0xc0004fc300)
	/Users/bba/pc/tidb/ddl/ddl_test.go:106 +0x106
testing.tRunner(0xc0004fc300, 0x63b8ca0)
	/Users/bba/.gvm/gos/go1.13/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/Users/bba/.gvm/gos/go1.13/src/testing/testing.go:960 +0x350

goroutine 174 [select, 10 minutes]:
github.com/pingcap/check.(*resultTracker)._loopRoutine(0xc0006be7e0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:464 +0xdd
created by github.com/pingcap/check.(*resultTracker).start
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:444 +0x3f

goroutine 175 [select, 10 minutes]:
github.com/pingcap/check.(*suiteRunner).doRun(0xc0006be870, 0xc0006c05a0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:667 +0x143
github.com/pingcap/check.(*suiteRunner).asyncRun.func1(0xc0006be870, 0xc0000f89a0, 0xc0002d2600)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xc2
created by github.com/pingcap/check.(*suiteRunner).asyncRun
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:646 +0x154

goroutine 243 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0006d05c0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/google.golang.org/grpc@v1.26.0/balancer_conn_wrappers.go:69 +0xc2
created by google.golang.org/grpc.newCCBalancerWrapper
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/google.golang.org/grpc@v1.26.0/balancer_conn_wrappers.go:60 +0x16d

goroutine 244 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc000236b00)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/google.golang.org/grpc@v1.26.0/clientconn.go:1134 +0x40d
created by google.golang.org/grpc.(*addrConn).connect
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/google.golang.org/grpc@v1.26.0/clientconn.go:800 +0x128

goroutine 299 [select]:
github.com/pingcap/badger/epoch.(*ResourceManager).collectLoop(0xc00e5728a0, 0xc00e55b9c0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/epoch/manager.go:101 +0x10d
created by github.com/pingcap/badger/epoch.NewResourceManager
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/epoch/manager.go:79 +0xa7

goroutine 598 [select, 10 minutes]:
github.com/ngaut/unistore/tikv.(*MVCCStore).StartDeadlockDetection.func1(0xc01c305200)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/mvcc.go:1088 +0xb7
created by github.com/ngaut/unistore/tikv.(*MVCCStore).StartDeadlockDetection
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/mvcc.go:1086 +0x78

goroutine 597 [select, 2 minutes]:
github.com/ngaut/unistore/tikv.(*MVCCStore).runUpdateSafePointLoop(0xc01c305200)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/mvcc.go:1331 +0x2ba
created by github.com/ngaut/unistore/tikv.NewMVCCStore
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/mvcc.go:85 +0x263

goroutine 596 [select, 10 minutes]:
github.com/ngaut/unistore/tikv.writeLockWorker.run(0xc01deadb00, 0xc01eca6900)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/write.go:147 +0x430
created by github.com/ngaut/unistore/tikv.(*dbWriter).Open
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/write.go:205 +0xdc

goroutine 298 [select, 10 minutes]:
github.com/pingcap/badger.Open.func4(0xc0000c8748)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/db.go:326 +0x15f
created by github.com/pingcap/badger.Open
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/db.go:323 +0xd88

goroutine 280 [select, 2 minutes]:
github.com/pingcap/badger.(*DB).updateSize(0xc000532480, 0xc00f38e020)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/db.go:1025 +0x157
created by github.com/pingcap/badger.Open
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/db.go:338 +0xe5c

goroutine 348 [chan receive, 10 minutes]:
github.com/pingcap/badger.(*DB).runFlushMemTable(0xc000532480, 0xc00e55b960, 0x0, 0x0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/db.go:908 +0x197
created by github.com/pingcap/badger.Open
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/db.go:357 +0x16fe

goroutine 347 [select]:
github.com/pingcap/badger.(*levelsController).runWorker(0xc00e5ac0d0, 0xc0134e3900, 0x5fe9b00)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/levels.go:212 +0x1b6
created by github.com/pingcap/badger.(*levelsController).startCompact
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/levels.go:180 +0x93

goroutine 346 [select, 10 minutes]:
github.com/pingcap/badger.(*blobGCHandler).run(0xc013502400, 0xc0134e38e0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/blob.go:468 +0x109
created by github.com/pingcap/badger.(*blobManager).Open
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/blob.go:292 +0x61e

goroutine 480 [select, 10 minutes]:
github.com/pingcap/badger.(*writeWorker).runWriteVLog(0xc01ece63e0, 0xc01ece63a0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/writer.go:94 +0x167
created by github.com/pingcap/badger.startWriteWorker
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/writer.go:64 +0x18d

goroutine 481 [chan receive, 10 minutes, locked to thread]:
github.com/pingcap/badger.(*writeWorker).runWriteLSM(0xc01ece63e0, 0xc01ece63a0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/writer.go:141 +0x1aa
created by github.com/pingcap/badger.startWriteWorker
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/writer.go:65 +0x1b9

goroutine 538 [select]:
github.com/pingcap/tidb/store/tikv/oracle/oracles.(*pdOracle).updateTS(0xc0206f2be0, 0x686efa0, 0xc0000f8008, 0x77359400)
	/Users/bba/pc/tidb/store/tikv/oracle/oracles/pd.go:126 +0x109
created by github.com/pingcap/tidb/store/tikv/oracle/oracles.NewPdOracle
	/Users/bba/pc/tidb/store/tikv/oracle/oracles/pd.go:51 +0xca

goroutine 594 [chan receive, 10 minutes]:
github.com/pingcap/badger.(*writeWorker).runMergeLSM(0xc01ece63e0, 0xc01ece63a0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/writer.go:154 +0xba
created by github.com/pingcap/badger.startWriteWorker
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/writer.go:66 +0x1e5

goroutine 595 [select, 10 minutes]:
github.com/ngaut/unistore/tikv.writeDBWorker.run(0xc01deadaa0, 0xc01eca6900)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/write.go:95 +0x23b
created by github.com/ngaut/unistore/tikv.(*dbWriter).Open
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/write.go:198 +0x8f

goroutine 539 [select, 10 minutes]:
github.com/pingcap/tidb/store/tikv.(*RegionCache).asyncCheckAndResolveLoop(0xc01ed80e70)
	/Users/bba/pc/tidb/store/tikv/region_cache.go:303 +0xc4
created by github.com/pingcap/tidb/store/tikv.NewRegionCache
	/Users/bba/pc/tidb/store/tikv/region_cache.go:290 +0x1d7

goroutine 540 [select]:
github.com/pingcap/tidb/store/tikv.(*tikvStore).runSafePointChecker(0xc01338a900)
	/Users/bba/pc/tidb/store/tikv/kv.go:263 +0xed
created by github.com/pingcap/tidb/store/tikv.newTikvStore
	/Users/bba/pc/tidb/store/tikv/kv.go:223 +0x3e7

goroutine 1316 [select]:
github.com/pingcap/tidb/domain.(*Domain).topologySyncerKeeper(0xc0459926c0)
	/Users/bba/pc/tidb/domain/domain.go:475 +0x1d2
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/Users/bba/pc/tidb/domain/domain.go:753 +0x5b7

goroutine 1314 [select, 2 minutes]:
github.com/pingcap/tidb/domain.(*Domain).topNSlowQueryLoop(0xc0459926c0)
	/Users/bba/pc/tidb/domain/domain.go:418 +0x22d
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/Users/bba/pc/tidb/domain/domain.go:747 +0x539

goroutine 1260 [select]:
github.com/pingcap/tidb/ddl.(*worker).start(0xc047706ba0, 0xc045a65360)
	/Users/bba/pc/tidb/ddl/ddl_worker.go:147 +0x360
created by github.com/pingcap/tidb/ddl.(*ddl).Start
	/Users/bba/pc/tidb/ddl/ddl.go:338 +0x6ac

goroutine 1265 [select]:
github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop(0xc0459926c0, 0x686ef60, 0xc045818e00, 0x2faf080)
	/Users/bba/pc/tidb/domain/domain.go:506 +0x254
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/Users/bba/pc/tidb/domain/domain.go:744 +0x63f

goroutine 1258 [select, 10 minutes]:
github.com/pingcap/tidb/ddl.(*ddl).limitDDLJobs(0xc047706b40)
	/Users/bba/pc/tidb/ddl/ddl_worker.go:209 +0x310
created by github.com/pingcap/tidb/ddl.(*ddl).Start
	/Users/bba/pc/tidb/ddl/ddl.go:320 +0x2c4

goroutine 1259 [select, 10 minutes]:
github.com/pingcap/tidb/ddl.(*delRange).startEmulator(0xc047704730)
	/Users/bba/pc/tidb/ddl/delete_range.go:142 +0x130
created by github.com/pingcap/tidb/ddl.(*delRange).start
	/Users/bba/pc/tidb/ddl/delete_range.go:124 +0x7e

goroutine 1315 [select]:
github.com/pingcap/tidb/domain.(*Domain).infoSyncerKeeper(0xc0459926c0)
	/Users/bba/pc/tidb/domain/domain.go:450 +0x185
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/Users/bba/pc/tidb/domain/domain.go:750 +0x578

goroutine 1261 [select]:
github.com/pingcap/tidb/ddl.(*worker).start(0xc047706cc0, 0xc045a65360)
	/Users/bba/pc/tidb/ddl/ddl_worker.go:147 +0x360
created by github.com/pingcap/tidb/ddl.(*ddl).Start
	/Users/bba/pc/tidb/ddl/ddl.go:338 +0x6ac

goroutine 1313 [select]:
github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop.func1(0xc0459926c0)
	/Users/bba/pc/tidb/domain/domain.go:917 +0x162
created by github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop
	/Users/bba/pc/tidb/domain/domain.go:908 +0x5f

goroutine 1346 [select]:
github.com/pingcap/tidb/domain.(*Domain).handleEvolvePlanTasksLoop.func1(0xc0459926c0, 0x68b5360, 0xc04932e400)
	/Users/bba/pc/tidb/domain/domain.go:945 +0x162
created by github.com/pingcap/tidb/domain.(*Domain).handleEvolvePlanTasksLoop
	/Users/bba/pc/tidb/domain/domain.go:937 +0x73

goroutine 1406 [select, 2 minutes]:
github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop.func1(0xc0459926c0, 0xc0455cf2a0, 0x45d964b800, 0x68b5360, 0xc045761e00)
	/Users/bba/pc/tidb/domain/domain.go:853 +0x150
created by github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop
	/Users/bba/pc/tidb/domain/domain.go:844 +0x13c

goroutine 30963 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc048548e58)
	/Users/bba/.gvm/gos/go1.13/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc048548e50)
	/Users/bba/.gvm/gos/go1.13/src/sync/waitgroup.go:130 +0x64
github.com/pingcap/tidb/ddl_test.(*testStateChangeSuite).TestParallelDDLBeforeRunDDLJob(0xc0002f8410, 0xc05dc900f0)
	/Users/bba/pc/tidb/ddl/db_change_test.go:1339 +0x645
reflect.Value.call(0x6287480, 0xc0002f8410, 0x5213, 0x62b8c1a, 0x4, 0xc00bb19f18, 0x1, 0x1, 0x82b35a0, 0xc04e8cddb8, ...)
	/Users/bba/.gvm/gos/go1.13/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x6287480, 0xc0002f8410, 0x5213, 0xc04e8cdf18, 0x1, 0x1, 0x0, 0x5fad420, 0x0)
	/Users/bba/.gvm/gos/go1.13/src/reflect/value.go:321 +0xb4
github.com/pingcap/check.(*suiteRunner).forkTest.func1(0xc05dc900f0)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x5e4
github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc0006be870, 0xc05dc900f0, 0xc05ec05860)
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0xda
created by github.com/pingcap/check.(*suiteRunner).forkCall
	/Users/bba/.gvm/pkgsets/go1.13/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x233

goroutine 30996 [runnable]:
runtime.goparkunlock(...)
	/Users/bba/.gvm/gos/go1.13/src/runtime/proc.go:310
time.Sleep(0x4c4b40)
	/Users/bba/.gvm/gos/go1.13/src/runtime/time.go:105 +0x157
github.com/pingcap/tidb/ddl_test.(*testStateChangeSuite).TestParallelDDLBeforeRunDDLJob.func1(0x68b5360, 0xc08ffbba00, 0x68aa420, 0xc05c412450, 0x203001, 0x68aa420)
	/Users/bba/pc/tidb/ddl/db_change_test.go:1297 +0x9d
github.com/pingcap/tidb/ddl.(*TestInterceptor).OnGetInfoSchema(0xc02a481230, 0x68b5360, 0xc08ffbba00, 0x68aa420, 0xc05c412450, 0xc058859501, 0x20)
	/Users/bba/pc/tidb/ddl/callback_test.go:35 +0x5b
github.com/pingcap/tidb/ddl.(*ddl).GetInfoSchemaWithInterceptor(0xc047706b40, 0x68b5360, 0xc08ffbba00, 0x0, 0x0)
	/Users/bba/pc/tidb/ddl/ddl.go:403 +0x166
github.com/pingcap/tidb/ddl.(*ddl).getSchemaAndTableByIdent(0xc047706b40, 0x68b5360, 0xc08ffbba00, 0x62d90f6, 0xd, 0x62d90f6, 0xd, 0x631e826, 0xa, 0x631e826, ...)
	/Users/bba/pc/tidb/ddl/ddl_api.go:2400 +0x64
github.com/pingcap/tidb/ddl.(*ddl).AddColumn(0xc047706b40, 0x68b5360, 0xc08ffbba00, 0x62d90f6, 0xd, 0x62d90f6, 0xd, 0x631e826, 0xa, 0x631e826, ...)
	/Users/bba/pc/tidb/ddl/ddl_api.go:2528 +0xc2
github.com/pingcap/tidb/ddl.(*ddl).AlterTable(0xc047706b40, 0x68b5360, 0xc08ffbba00, 0x62d90f6, 0xd, 0x62d90f6, 0xd, 0x631e826, 0xa, 0x631e826, ...)
	/Users/bba/pc/tidb/ddl/ddl_api.go:2199 +0x10d0
github.com/pingcap/tidb/executor.(*DDLExec).executeAlterTable(0xc05ea20aa0, 0xc06afe3110, 0xc06afe3200, 0x0)
	/Users/bba/pc/tidb/executor/ddl.go:362 +0x198
github.com/pingcap/tidb/executor.(*DDLExec).Next(0xc05ea20aa0, 0x686f020, 0xc06afe3200, 0xc02a5866e0, 0x0, 0x0)
	/Users/bba/pc/tidb/executor/ddl.go:86 +0xb96
github.com/pingcap/tidb/executor.Next(0x686f020, 0xc06afe3200, 0x6878620, 0xc05ea20aa0, 0xc02a5866e0, 0x0, 0x0)
	/Users/bba/pc/tidb/executor/executor.go:267 +0x11f
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc00b853b90, 0x686f020, 0xc06afe3200, 0x6878620, 0xc05ea20aa0, 0x0, 0x0, 0x0, 0x0)
	/Users/bba/pc/tidb/executor/adapter.go:510 +0x2d6
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc00b853b90, 0x686f020, 0xc06afe3200, 0x6878620, 0xc05ea20aa0, 0x8290900, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/bba/pc/tidb/executor/adapter.go:392 +0x13a
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc00b853b90, 0x686f020, 0xc06afe3200, 0x0, 0x0, 0x0, 0x0)
	/Users/bba/pc/tidb/executor/adapter.go:360 +0x40e
github.com/pingcap/tidb/session.runStmt(0x686efa0, 0xc0000f8000, 0xc08ffbba00, 0x6878720, 0xc00b853b90, 0x0, 0x0, 0x0, 0x0)
	/Users/bba/pc/tidb/session/session.go:1201 +0x256
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc08ffbba00, 0x686efa0, 0xc0000f8000, 0x6877420, 0xc06afe3110, 0x0, 0x0, 0x0, 0x0)
	/Users/bba/pc/tidb/session/session.go:1166 +0x7d4
github.com/pingcap/tidb/session.(*session).Execute(0xc08ffbba00, 0x686efa0, 0xc0000f8000, 0x631e81a, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bba/pc/tidb/session/session.go:1079 +0x2fb
github.com/pingcap/tidb/ddl_test.(*testStateChangeSuite).TestParallelDDLBeforeRunDDLJob.func3(0xc048548e50, 0x68eaea0, 0xc08ffbba00, 0xc05dc900f0)
	/Users/bba/pc/tidb/ddl/db_change_test.go:1334 +0xd6
created by github.com/pingcap/tidb/ddl_test.(*testStateChangeSuite).TestParallelDDLBeforeRunDDLJob
	/Users/bba/pc/tidb/ddl/db_change_test.go:1330 +0x634

rax    0x104
rbx    0x2
rcx    0x7ffeefbff2e8
rdx    0xf900
rdi    0x8292128
rsi    0xf9010000fa00
rbp    0x7ffeefbff380
rsp    0x7ffeefbff2e8
r8     0x0
r9     0xa0
r10    0x0
r11    0x202
r12    0x8292128
r13    0x16
r14    0xf9010000fa00
r15    0xbf58dc0
rip    0x7fff713f9882
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
FAIL	github.com/pingcap/tidb/ddl	660.177s
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Close #18226

Problem Summary:

TestParallelDDLBeforeRunDDLJob may hang forever.

In OnGetInfoSchemaExported, there are two loops.
If the second session do `atomic.AddInt32(&sessionCnt, 1)`. Before `if atomic.LoadInt32(&sessionCnt) == 2 {`, the first session finish OnGetInfoSchemaExported and `atomic.StoreInt32(&sessionCnt, finishedCnt)`. Then the second session will block forever.

### What is changed and how it works?

Sleep a while.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

### Release note 

- No release note

### CODE REVIEW

File: ddl/db_change_test.go [hunk 1]
```diff
@@ -1324,6 +1324,8 @@ func (s *testStateChangeSuite) TestParallelDDLBeforeRunDDLJob(c *C) {
 		se.SetConnectionID(firstConnID)
 		_, err1 := se.Execute(context.Background(), "alter table test_table drop column c2")
 		c.Assert(err1, IsNil)
+		// Sleep a while to make sure the connection 1 break out the first loop.
```
Comment (zimulala) [inline ddl/db_change_test.go:1327]: I don't quite understand this comment.

Comment (wjhuang2016) [reply ddl/db_change_test.go]: Sorry, it was wrong. I had fixed it.

**Comment by bb7133** [comment]
Do we need to cherry-pick it?
