### PR TITLE
planner: projection should not push the expr that is not fully substituted

### LINKED ISSUE #35623: Runtime error: invalid memory address
### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1(c0 INT UNIQUE);
CREATE VIEW v1(c0) AS SELECT 1 FROM t1;

SELECT v1.c0 FROM v1 WHERE (true)LIKE(v1.c0); --runtime error: invalid memory address or nil pointer dereference
```

### 2. What did you expect to see? (Required)
No error information

### 3. What did you see instead (Required)
runtime error: invalid memory address or nil pointer dereference

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-159-ge0527ba27
Edition: Community
Git Commit Hash: e0527ba27c72b0a533b126fedfa025d47a209ca9
Git Branch: master
UTC Build Time: 2022-06-21 11:55:54
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore |

### LINKED ISSUE #37971: ERROR 1105 (HY000): Can't find column Column#2 in schema Column: [test.t3.c0] Unique key: []
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists t3;
CREATE TABLE t3(c0 INT, primary key(c0));
SELECT v2.c0 FROM (select 1 as c0 from t3) v2 WHERE (v2.c0)like(True);
```
### 2. What did you expect to see? (Required)
Execute success without error.

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): Can't find column Column#2 in schema Column: [test.t3.c0] Unique key: []
```
### 4. What is your TiDB version? (Required)

latest master

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #38736

close https://github.com/pingcap/tidb/issues/37971
close https://github.com/pingcap/tidb/issues/35623

Problem Summary:

### What is changed and how it works?

An expression is partly changed. And we pushed it down to join.

When join reorder, the join finds that that expression contains a column that cannot be found by any leaf of the join group. The expression is dropped. Thus the result is wrong.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/rule_predicate_push_down.go [hunk 1]
```diff
@@ -474,8 +474,8 @@ func (p *LogicalProjection) PredicatePushDown(predicates []expression.Expression
 		}
 	}
 	for _, cond := range predicates {
-		substituted, newFilter := expression.ColumnSubstitute4PPD(cond, p.Schema(), p.Exprs)
-		if substituted && !expression.HasGetSetVarFunc(newFilter) {
+		substituted, hasFailed, newFilter := expression.ColumnSubstituteImpl(cond, p.Schema(), p.Exprs, true)
```
Comment (Reminiscent) [inline planner/core/rule_predicate_push_down.go:477]: It seems we can remove the function `ColumnSubstitute4PPD`.

File: expression/integration_test.go [hunk 2]
```diff
@@ -7768,6 +7768,20 @@ func TestJSONStorageFree(t *testing.T) {
...
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("CREATE TABLE t0(c0 BOOL, c1 INT);")
+	tk.MustExec("CREATE TABLE t1 LIKE t0;")
+	tk.MustExec("CREATE definer='root'@'localhost' VIEW v0(c0) AS SELECT IS_IPV4(t0.c1) FROM t0, t1;")
+	tk.MustExec("INSERT INTO t0(c0, c1) VALUES (true, 0);")
+	tk.MustExec("INSERT INTO t1(c0, c1) VALUES (true, 2);")
+
+	// The filter is evaled as false.
+	tk.MustQuery("SELECT v0.c0 FROM v0 WHERE (v0.c0)NOT LIKE(BINARY v0.c0);").Check(testkit.Rows())
```
Comment (Reminiscent) [inline expression/integration_test.go:7782]: Please add a test cases like `(v0.c0)NOT LIKE(BINARY v0.c0) or v0.c0 > 0`. Because this test was failed before.

**Review by fixdb — APPROVED** [review]
LGTM after @Reminiscent 's comments are addressed.

**Review by Reminiscent — APPROVED** [review]

File: expression/util.go [hunk 3]
```diff
@@ -432,41 +421,43 @@ func ColumnSubstituteImpl(expr Expression, schema *Schema, newExprs []Expression
...
-					}
+				changed = false
+				copy(tmpArgForCollCheck, refExprArr.Result())
+				tmpArgForCollCheck[idx] = newFuncExpr
+				_, newColl := DeriveCollationFromExprs(v.GetCtx(), tmpArgForCollCheck...)
+				if coll == newColl {
+					changed = checkCollationStrictness(coll, newFuncExpr.GetType().GetCollate())
 				}
 			}
+			hasFail = hasFail || failed || oldChanged != changed
```
Comment (AilinKid) [inline expression/util.go:460]: since fail1Return is true
once `failed` is true, it should be returned from L447 already.
once  `oldChanged != changed` is true, it should be returned from L467 soon.

`hasFail` seems always false here below

**Review by AilinKid — COMMENTED** [review]
Rest LGTM
