### PR TITLE
lightning: support opening empty files and skip directory objects in S3

### LINKED ISSUE #31824: When an empty object is matched during import, an error will be reported.
### What did you do?

When I import on dbaas, I set object name pattern as "test.item/ "
```
[2022/01/19 09:03:20.211 +00:00] [ERROR] [lightning.go:219] ["tidb lightning encountered error"] [error="restore table `zmdb`.`zmtest` failed: InvalidRange: The requested range is not satisfiable\n\tstatus code: 416, request id: 29EX6TJXPDFG657Q, host id: ER3V8vZWQa0oNdCsgIvqGSc8UFB44R0mKj7By6hf57OAYvs0gVhsZJQuuOQp2IA9+TkIl71kdnU="] [errorVerbose="InvalidRange: The requested range is not satisfiable\n\tstatus code: 416, request id: 29EX6TJXPDFG657Q, host id: ER3V8vZWQa0oNdCsgIvqGSc8UFB44R0mKj7By6hf57OAYvs0gVhsZJQuuOQp2IA9+TkIl71kdnU=\ngithub.com/pingcap/errors.AddStack\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/juju_adaptor.go:15\ngithub.com/pingcap/tidb/br/pkg/storage.(*S3Storage).open\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/storage/s3.go:553\ngithub.com/pingcap/tidb/br/pkg/storage.(*S3Storage).Open\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/storage/s3.go:504\ngithub.com/pingcap/tidb/br/pkg/lightning/mydump.makeParquetFileRegion\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/mydump/region.go:313\ngithub.com/pingcap/tidb/br/pkg/lightning/mydump.makeSourceFileRegion\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/mydump/region.go:260\ngithub.com/pingcap/tidb/br/pkg/lightning/mydump.MakeTableRegions.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/mydump/region.go:165\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nrestore table `zmdb`.`zmtest` failed"]
```
File routine config:
```
[[mydumper.files]]
pattern = "test\.item/"
schema = "test"
table = "item"
type = "parquet"
```

### What did you expect to see?

import success

### What did you see instead?

 an error will be reported.
 "error="restore table `zmdb`.`zmtest` failed: InvalidRange: The requested range is not satisfiable\n\tstatus co"

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #31824 

Problem Summary: When an empty directory object is matched during parquet import, an error will be reported

### What is changed and how it works?
* When walking a directory in S3, skip those empty directory objects and continue
* The `Open()` in S3 now supports opening empty files, so that the behavior is the same as in local file system.
* The `Seek()` operation in S3 added a real offset check, so that negative values are not supported
* Also the integration test for Lightning S3 has been refactored, and added a test case for testing the manually configured file path pattern with empty directories.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/mydump/region.go [hunk 1]
```diff
@@ -310,13 +311,18 @@ func makeParquetFileRegion(
...
-	r, err := store.Open(ctx, dataFile.FileMeta.Path)
-	if err != nil {
-		return prevRowIdxMax, nil, errors.Trace(err)
-	}
-	numberRows, err := ReadParquetFileRowCount(ctx, store, r, dataFile.FileMeta.Path)
-	if err != nil {
-		return 0, nil, errors.Trace(err)
+	var numberRows int64 = 0
+
+	// for S3, reading an empty file will cause error, so skip reading the empty files
```
Comment (gozssky) [inline br/pkg/lightning/mydump/region.go:316]: Nit: An alternative way is to fix the issue that we can't reading an empty file from S3. In external storage, if the given file size is zero, just return an `eofReadCloser`.

Comment (glorv) [reply br/pkg/lightning/mydump/region.go:316]: I think return an `eofReadCloser` is not ok for some cases. Especially, when we treat a 'directory' as a parquet file, because an 'empty' parquet file still contains head and footer, it will cause open the parquet file fails.

File: br/pkg/lightning/mydump/region.go [hunk 2]
```diff
@@ -310,13 +311,18 @@ func makeParquetFileRegion(
...
+	if dataFile.FileMeta.FileSize > 0 {
```
Comment (glorv) [inline br/pkg/lightning/mydump/region.go:317]: I still think we should skip directory like object in cloud storage instead of writing this special logic for specific type of files. It's import to keep each external storage's behavior the same as much as we can.

Comment (dsdashun) [reply br/pkg/lightning/mydump/region.go:317]: I did a test that for parquet file importing, not only an empty directory but also an empty file in S3 will cause the error.  So any empty objects will trigger the problem, and we cannot just stick on handling empty directories.

File: br/pkg/lightning/mydump/region.go (hunk 1 above)
Comment (gozssky) [reply br/pkg/lightning/mydump/region.go:316]: Yes. This can be two different issues:

1. Skip fake directory file in S3.
2. Any implementation of external storage shouldn't return error when file is empty. 

This PR can only process issue 1.

File: br/pkg/lightning/mydump/region.go (hunk 2 above)
Comment (glorv) [reply br/pkg/lightning/mydump/region.go:317]: > I did a test that for parquet file importing, not only an empty directory but also an empty file in S3 will cause the error. So any empty objects will trigger the problem, and we cannot just stick on handling empty directories.

I think this is expected behavior. We should only exclude empty directory, but for empty file, it's the user's responsibility to exclude them by writing the right regexp if needed.

File: br/pkg/lightning/mydump/region.go (hunk 1 above)
Comment (dsdashun) [reply br/pkg/lightning/mydump/region.go:316]: > Nit: An alternative way is to fix the issue that we can't reading an empty file from S3. In external storage, if the given file size is zero, just return an `eofReadCloser`.

Currently it is hard to do that because the input parameters of `ExternalStorage.Open()` has no size information.

Comment (gozssky) [reply br/pkg/lightning/mydump/region.go:316]: You can use `S3API.HeadObject` to get the size information.

**Review by gozssky — APPROVED** [review]

**Comment by gozssky** [comment]
@dsdashun I notice that `WalkDir` may not be used only by Lightning.  To be consistent with normal file system, I also think we shouldn't skip empty file when `WalkDir`.

File: br/pkg/storage/s3.go [hunk 3]
```diff
@@ -479,6 +471,22 @@ func (rs *S3Storage) WalkDir(ctx context.Context, opt *WalkOption, fn func(strin
...
 			req.Marker = r.Key
+
+			// when walk on specify directory, the result include storage.Prefix,
+			// which can not be reuse in other API(Open/Read) directly.
+			// so we use TrimPrefix to filter Prefix for next Open/Read.
+			path := strings.TrimPrefix(*r.Key, rs.options.Prefix)
+			itemSize := *r.Size
+
+			// filter out s3's  directries items
+			if itemSize <= 0 {
```
Comment (gozssky) [inline br/pkg/storage/s3.go:482]: `WalkDir` may not be used only by Lightning. To be consistent with normal file system, I think we shouldn't skip empty file in WalkDir.

**Review by gozssky — CHANGES_REQUESTED** [review]
@dsdashun   `WalkDir` may not be used only by Lightning. To be consistent with normal file system, I think we shouldn't skip all empty objects in `WalkDir`.

For opening an empty object in S3, we can use `S3API.HeadObject` to get the size information first.

**Comment by dsdashun** [comment]
> @dsdashun `WalkDir` may not be used only by Lightning. To be consistent with normal file system, I think we shouldn't skip all empty objects in `WalkDir`.
> 
> For opening an empty object in S3, we can use `S3API.HeadObject` to get the size information first.

Hi @gozssky , I think calling S3API.HeadObject in the `Open()` operation will introduce an extra request/response overhead on the Open() operation.  And this also might add some more chances of failure for the `Open()` operation for S3.  

I still think changing the behavior in `WalkDir()` will be appropriate, because it has the data size information directly.  Would that be OK if I just skip all the empty DIRECTORY objects (that is empty objects with "/" suffix ) in `WalkDir`?

**Comment by gozssky** [comment]
@dsdashun To avoid unnecessary overhead, perhaps we can add a special check for the `InvalidRange` error and do a retry.

> Would that be OK if I just skip all the empty DIRECTORY objects (that is empty objects with "/" suffix ) in WalkDir

Agree. `ExternalStorage` acts like a filesystem. So any filename that ends with "/" is inappropriate.

File: br/pkg/storage/s3.go [hunk 4]
```diff
@@ -528,28 +536,47 @@ func (rs *S3Storage) open(
...
 		rangeOffset = aws.String(fmt.Sprintf("bytes=%d-%d", startOffset, endOffset-1))
-	} else {
+	case startOffset == 0:
+		isFullRangeRequest = true
+	default:
 		rangeOffset = aws.String(fmt.Sprintf("bytes=%d-", startOffset))
 	}
 	input.Range = rangeOffset
 	result, err := rs.svc.GetObjectWithContext(ctx, input)
+	log.L().Debug("dump S3 get object", zap.Any("request", input), zap.Any("response", result))
```
Comment (gozssky) [inline br/pkg/storage/s3.go:559]:
```suggestion
	log.L().Debug("S3 get object", zap.Any("request", input), zap.Any("response", result))
```

File: br/pkg/storage/s3.go [hunk 5]
```diff
@@ -528,28 +536,47 @@ func (rs *S3Storage) open(
...
 		return nil, RangeInfo{}, errors.Trace(err)
 	}
 
-	r, err := ParseRangeInfo(result.ContentRange)
-	if err != nil {
-		return nil, RangeInfo{}, errors.Trace(err)
+	var r RangeInfo
+	if isFullRangeRequest {
+		if result.ContentLength == nil {
+			return nil, RangeInfo{}, errors.Annotatef(berrors.ErrStorageUnknown, "open file '%s' failed. The S3 has no content length", path)
```
Comment (gozssky) [inline br/pkg/storage/s3.go:567]:
```suggestion
			return nil, RangeInfo{}, errors.Annotatef(berrors.ErrStorageUnknown, "open file '%s' failed. The S3 object has no content length", path)
```

**Review by gozssky — COMMENTED** [review]
rest LGTM

**Review by gozssky — APPROVED** [review]

File: br/pkg/storage/s3.go [hunk 6]
```diff
@@ -528,28 +536,47 @@ func (rs *S3Storage) open(
...
 		rangeOffset = aws.String(fmt.Sprintf("bytes=%d-%d", startOffset, endOffset-1))
-	} else {
+	case startOffset == 0:
+		isFullRangeRequest = true
+	default:
 		rangeOffset = aws.String(fmt.Sprintf("bytes=%d-", startOffset))
 	}
 	input.Range = rangeOffset
 	result, err := rs.svc.GetObjectWithContext(ctx, input)
+	log.L().Debug("S3 get object", zap.Any("request", input), zap.Any("response", result))
```
Comment (glorv) [inline br/pkg/storage/s3.go:559]: I think this log is useless

File: br/pkg/storage/s3.go [hunk 7]
```diff
@@ -528,28 +536,47 @@ func (rs *S3Storage) open(
...
 		return nil, RangeInfo{}, errors.Trace(err)
 	}
 
-	r, err := ParseRangeInfo(result.ContentRange)
-	if err != nil {
-		return nil, RangeInfo{}, errors.Trace(err)
+	var r RangeInfo
+	if isFullRangeRequest {
+		if result.ContentLength == nil {
+			return nil, RangeInfo{}, errors.Annotatef(berrors.ErrStorageUnknown, "open file '%s' failed. The S3 object has no content length", path)
```
Comment (glorv) [inline br/pkg/storage/s3.go:567]: This message is not correct if open zero-size file actually returns the ContentLength. BTW, we should allow open a zero-sized file and when read from it, the result should be io.EOF not berrors.ErrStorageUnknown

Comment (gozssky) [reply br/pkg/storage/s3.go:567]: We should expect `Content-Length` in response even object size is zero. Or there is no way to get the response size.

Comment (dsdashun) [reply br/pkg/storage/s3.go:574]: I've added some comments explaining that in the code.

**Review by glorv — APPROVED** [review]
