### PR TITLE
ddl: fix "wrong warning messages when running some DDL jobs"

### LINKED ISSUE #38699: ddl: wrong warning messages when running some DDL jobs.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='';
drop table if exists t; 
create table t(a int);
insert into t values (1000000000), (2000000);
alter table t modify a tinyint;
show warnings;
```

### 2. What did you expect to see? (Required)
```
tidb> drop table if exists t;
Query OK, 0 rows affected (0.02 sec)

tidb> create table t(a int);
Query OK, 0 rows affected (0.01 sec)

tidb> insert into t values (1000000000), (2000000);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

tidb> alter table t modify a tinyint;
Query OK, 0 rows affected, 2 warnings (2.53 sec)

tidb> show warnings;
+---------+------+---------------------------------------+
| Level   | Code | Message                               |
+---------+------+---------------------------------------+
| Warning | 1690 | constant 1000000000 overflows tinyint |
| Warning | 1690 | constant 2000000 overflows tinyint |
+---------+------+---------------------------------------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
tidb> drop table if exists t;
Query OK, 0 rows affected (0.02 sec)

tidb> create table t(a int);
Query OK, 0 rows affected (0.01 sec)

tidb> insert into t values (1000000000), (2000000);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

tidb> alter table t modify a tinyint;
Query OK, 0 rows affected, 2 warnings (2.53 sec)

tidb> show warnings;
+---------+------+---------------------------------------+
| Level   | Code | Message                               |
+---------+------+---------------------------------------+
| Warning | 1690 | constant 1000000000 overflows tinyint |
| Warning | 1690 | constant 1000000000 overflows tinyint |
+---------+------+---------------------------------------+
2 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

I believe it can be reproduced in all TiDB versions that support modifying the column as above.

Also, this issue should be reproduced for all other types of DDLs as long as multiple warnings might be raised.

### PR DESCRIPTION
**Pull request by wxbty**
Signed-off-by: x-shadow-man <1494445739@qq.com>

bugfix: #38699

### What problem does this PR solve?

When executing alter to change column attributes, multiple warnings display errors, and only one line is displayed when the same error is modified

Issue Number: close #38699

Problem Summary:

### What is changed and how it works?

warning info format changed

### Check List

Tests 

- [√ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/failtest/fail_db_test.go [hunk 1]
```diff
@@ -532,6 +532,32 @@ func TestModifyColumn(t *testing.T) {
...
+	//Test multi records
+	tk.MustExec("USE test")
+	tk.MustExec("set sql_mode=''")
+	tk.MustExec("DROP TABLE IF EXISTS t;")
+	tk.MustExec("CREATE TABLE t (a int)")
+	tk.MustExec("insert into t values (1000000000), (2000000)")
+	tk.MustExec("alter table t modify a tinyint")
+	result := tk.MustQuery("show warnings")
+	require.Len(t, result.Rows(), 1)
+	result.Check(testkit.Rows("Warning 1690 2 warning(s), first warning:constant 1000000000 overflows tinyint"))
```
Comment (mjonss) [inline ddl/failtest/fail_db_test.go:548]: I assume this test will be stable? Or does it need to just check that '2 warnings, ...' are a prefix of the warning, in case of the constant X is non-determistic?

**Review by mjonss — APPROVED** [review]
LGTM, with minor suggestion and question.

File: ddl/ddl.go [hunk 2]
```diff
@@ -1094,8 +1094,13 @@ func (d *ddl) DoDDLJob(ctx sessionctx.Context, job *model.Job) error {
 					logutil.BgLogger().Info("[ddl] DDL warnings doesn't match the warnings count", zap.Int64("jobID", jobID))
 				} else {
 					for key, warning := range historyJob.ReorgMeta.Warnings {
-						for j := int64(0); j < historyJob.ReorgMeta.WarningsCount[key]; j++ {
+						keyCount := historyJob.ReorgMeta.WarningsCount[key]
+						if keyCount == 1 {
 							ctx.GetSessionVars().StmtCtx.AppendWarning(warning)
+						} else {
+							newMsg := fmt.Sprintf("%d warning(s), first warning:"+warning.GetMsg(), keyCount)
```
[the remark this answers is not in the document]
Comment (wxbty) [reply ddl/ddl.go]: ok

File: ddl/failtest/fail_db_test.go (hunk 1 above)
Comment (wxbty) [reply ddl/failtest/fail_db_test.go]: ok

**Comment by Defined2014** [comment]
@wxbty Seems you should update two test cases.
`TestModifyColumnTypeWhenInterception` and `TestModifyColumnTypeWithWarnings`

**Comment by wxbty** [comment]
> TestModifyColumnTypeWithWarnings

thx,  TestModifyColumnTypeWhenInterception seems to fail on master

**Comment by Defined2014** [comment]
The error msg

```
[2022/11/16 14:08:19.957 +08:00] [INFO] [callback_test.go:107] ["on job updated"] [job="ID:78, Type:modify column, State:done, SchemaState:public, SchemaID:2, TableID:76, RowCount:4096, ArgLen:2, start time: 2022-11-16 14:08:19.473 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:437407947076665345"]
[2022/11/16 14:08:19.973 +08:00] [INFO] [delete_range.go:109] ["[ddl] add job into delete-range table"] [jobID=78] [jobType="modify column"]
[2022/11/16 14:08:19.974 +08:00] [INFO] [ddl_worker.go:632] ["[ddl] finish DDL job"] [worker="worker 267, tp add index"] [job="ID:78, Type:modify column, State:synced, SchemaState:public, SchemaID:2, TableID:76, RowCount:4096, ArgLen:2, start time: 2022-11-16 14:08:19.473 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:437407947076665345"]
[2022/11/16 14:08:19.977 +08:00] [INFO] [callback_test.go:107] ["on job updated"] [job="ID:78, Type:modify column, State:synced, SchemaState:public, SchemaID:2, TableID:76, RowCount:4096, ArgLen:2, start time: 2022-11-16 14:08:19.473 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:437407947076665345"]
[2022/11/16 14:08:19.982 +08:00] [INFO] [ddl.go:1110] ["[ddl] DDL job is finished"] [jobID=78]
[2022/11/16 14:08:19.982 +08:00] [INFO] [callback_test.go:66] ["performing DDL change, must reload"]
    modify_column_test.go:898: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/6938/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/modify_column_test.go:898
        	Error:      	"[[Warning 1292 4096 warnings with this error code, first warning: Truncated incorrect DECIMAL value: '11.22']]" should have 4096 item(s), but has 1
        	Test:       	TestModifyColumnTypeWhenInterception
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 269, tp add index"] ["take time"=1.491µs]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 270, tp add index"] ["take time"=1.054µs]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 271, tp add index"] ["take time"=899ns]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 272, tp add index"] ["take time"=892ns]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 273, tp add index"] ["take time"=1.071µs]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 274, tp add index"] ["take time"=1.002µs]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 265, tp add index"] ["take time"=931ns]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 266, tp add index"] ["take time"=893ns]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 267, tp add index"] ["take time"=1.008µs]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 268, tp add index"] ["take time"=829ns]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 264, tp general"] ["take time"=1.066µs]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 262, tp general"] ["take time"=377ns]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 263, tp add index"] ["take time"=252ns]
[2022/11/16 14:08:19.984 +08:00] [INFO] [delete_range.go:148] ["[ddl] closing delRange"]
[2022/11/16 14:08:19.984 +08:00] [INFO] [session_pool.go:94] ["[ddl] closing sessionPool"]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl.go:815] ["[ddl] DDL closed"] [ID=195c88d3-e504-485f-80a8-5c6020e67a8d] ["take time"=1.956832ms]
[2022/11/16 14:08:19.984 +08:00] [INFO] [ddl.go:639] ["[ddl] stop DDL"] [ID=195c88d3-e504-485f-80a8-5c6020e67a8d]
[2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1095] ["closestReplicaReadCheckLoop exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:743] ["loadSchemaInLoop exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1617] ["dumpFileGcChecker exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1332] ["LoadSysVarCacheLoop exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1282] ["loadPrivilegeInLoop exited."]
[2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1457] ["handleEvolvePlanTasksLoop exited."]
[2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:1413] ["globalBindHandleWorkerLoop exited."]
[2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:608] ["topologySyncerKeeper exited."]
[2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:560] ["infoSyncerKeeper exited."]
[2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:585] ["globalConfigSyncerKeeper exited."]
[2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:531] ["topNSlowQueryLoop exited."]
[2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:871] ["domain closed"] ["take time"=2.393879ms]
[2022/11/16 14:08:19.996 +08:00] [INFO] [db.go:567] ["Closing database"]
[2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:592] ["Memtable flushed"]
[2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:596] ["Compaction finished"]
[2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:615] ["BlobManager finished"]
[2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:619] ["ResourceManager finished"]
[2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:625] ["Waiting for closer"]
--- FAIL: TestModifyColumnTypeWhenInterception (4.84s)
```

```
[2022/11/16 14:06:49.552 +08:00] [INFO] [ddl.go:1110] ["[ddl] DDL job is finished"] [jobID=78]
[2022/11/16 14:06:49.552 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
    result.go:49: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/6696/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/result.go:49
        	            				/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/6696/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/modify_column_test.go:816
        	Error:      	Not equal: 
        	            	expected: "[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n"
        	            	actual  : "[Warning 1292 4 warnings with this error code, first warning: Truncated incorrect DECIMAL value: '111.22']\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,5 +1,2 @@
        	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
        	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
        	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
        	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
        	            	+[Warning 1292 4 warnings with this error code, first warning: Truncated incorrect DECIMAL value: '111.22']
        	            	 
        	Test:       	TestModifyColumnTypeWithWarnings
        	Messages:   	sql:show warnings, args:[]
[2022/11/16 14:06:49.554 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 266, tp add index"] ["take time"=1.625µs]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 267, tp add index"] ["take time"=2.03µs]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 268, tp add index"] ["take time"=974ns]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 269, tp add index"] ["take time"=982ns]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 270, tp add index"] ["take time"=1.191µs]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 271, tp add index"] ["take time"=1.165µs]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 272, tp add index"] ["take time"=1.033µs]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 273, tp add index"] ["take time"=902ns]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 274, tp add index"] ["take time"=1.557µs]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 265, tp add index"] ["take time"=916ns]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 264, tp general"] ["take time"=1.018µs]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 262, tp general"] ["take time"=417ns]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 263, tp add index"] ["take time"=649ns]
[2022/11/16 14:06:49.555 +08:00] [INFO] [delete_range.go:148] ["[ddl] closing delRange"]
[2022/11/16 14:06:49.555 +08:00] [INFO] [session_pool.go:94] ["[ddl] closing sessionPool"]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl.go:815] ["[ddl] DDL closed"] [ID=562290da-0f7a-450e-82f1-094d5f9a3023] ["take time"=2.849804ms]
[2022/11/16 14:06:49.555 +08:00] [INFO] [ddl.go:639] ["[ddl] stop DDL"] [ID=562290da-0f7a-450e-82f1-094d5f9a3023]
[2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:1095] ["closestReplicaReadCheckLoop exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:743] ["loadSchemaInLoop exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:1617] ["dumpFileGcChecker exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
[2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:1332] ["LoadSysVarCacheLoop exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:1282] ["loadPrivilegeInLoop exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:1457] ["handleEvolvePlanTasksLoop exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:1413] ["globalBindHandleWorkerLoop exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:608] ["topologySyncerKeeper exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:560] ["infoSyncerKeeper exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:585] ["globalConfigSyncerKeeper exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:531] ["topNSlowQueryLoop exited."]
[2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:871] ["domain closed"] ["take time"=3.297455ms]
[2022/11/16 14:06:49.560 +08:00] [INFO] [db.go:567] ["Closing database"]
[2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:592] ["Memtable flushed"]
[2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:596] ["Compaction finished"]
[2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:615] ["BlobManager finished"]
[2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:619] ["ResourceManager finished"]
[2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:625] ["Waiting for closer"]
--- FAIL: TestModifyColumnTypeWithWarnings (4.49s)
```

**Comment by wxbty** [comment]
> The error msg
> 
> ```
> [2022/11/16 14:08:19.957 +08:00] [INFO] [callback_test.go:107] ["on job updated"] [job="ID:78, Type:modify column, State:done, SchemaState:public, SchemaID:2, TableID:76, RowCount:4096, ArgLen:2, start time: 2022-11-16 14:08:19.473 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:437407947076665345"]
> [2022/11/16 14:08:19.973 +08:00] [INFO] [delete_range.go:109] ["[ddl] add job into delete-range table"] [jobID=78] [jobType="modify column"]
> [2022/11/16 14:08:19.974 +08:00] [INFO] [ddl_worker.go:632] ["[ddl] finish DDL job"] [worker="worker 267, tp add index"] [job="ID:78, Type:modify column, State:synced, SchemaState:public, SchemaID:2, TableID:76, RowCount:4096, ArgLen:2, start time: 2022-11-16 14:08:19.473 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:437407947076665345"]
> [2022/11/16 14:08:19.977 +08:00] [INFO] [callback_test.go:107] ["on job updated"] [job="ID:78, Type:modify column, State:synced, SchemaState:public, SchemaID:2, TableID:76, RowCount:4096, ArgLen:2, start time: 2022-11-16 14:08:19.473 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:437407947076665345"]
> [2022/11/16 14:08:19.982 +08:00] [INFO] [ddl.go:1110] ["[ddl] DDL job is finished"] [jobID=78]
> [2022/11/16 14:08:19.982 +08:00] [INFO] [callback_test.go:66] ["performing DDL change, must reload"]
>     modify_column_test.go:898: 
>         	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/6938/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/modify_column_test.go:898
>         	Error:      	"[[Warning 1292 4096 warnings with this error code, first warning: Truncated incorrect DECIMAL value: '11.22']]" should have 4096 item(s), but has 1
>         	Test:       	TestModifyColumnTypeWhenInterception
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 269, tp add index"] ["take time"=1.491µs]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 270, tp add index"] ["take time"=1.054µs]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 271, tp add index"] ["take time"=899ns]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 272, tp add index"] ["take time"=892ns]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 273, tp add index"] ["take time"=1.071µs]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 274, tp add index"] ["take time"=1.002µs]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 265, tp add index"] ["take time"=931ns]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 266, tp add index"] ["take time"=893ns]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 267, tp add index"] ["take time"=1.008µs]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 268, tp add index"] ["take time"=829ns]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 264, tp general"] ["take time"=1.066µs]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 262, tp general"] ["take time"=377ns]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 263, tp add index"] ["take time"=252ns]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [delete_range.go:148] ["[ddl] closing delRange"]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [session_pool.go:94] ["[ddl] closing sessionPool"]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl.go:815] ["[ddl] DDL closed"] [ID=195c88d3-e504-485f-80a8-5c6020e67a8d] ["take time"=1.956832ms]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [ddl.go:639] ["[ddl] stop DDL"] [ID=195c88d3-e504-485f-80a8-5c6020e67a8d]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1095] ["closestReplicaReadCheckLoop exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:743] ["loadSchemaInLoop exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1617] ["dumpFileGcChecker exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1332] ["LoadSysVarCacheLoop exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1282] ["loadPrivilegeInLoop exited."]
> [2022/11/16 14:08:19.984 +08:00] [INFO] [domain.go:1457] ["handleEvolvePlanTasksLoop exited."]
> [2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:1413] ["globalBindHandleWorkerLoop exited."]
> [2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:608] ["topologySyncerKeeper exited."]
> [2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:560] ["infoSyncerKeeper exited."]
> [2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:585] ["globalConfigSyncerKeeper exited."]
> [2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:531] ["topNSlowQueryLoop exited."]
> [2022/11/16 14:08:19.985 +08:00] [INFO] [domain.go:871] ["domain closed"] ["take time"=2.393879ms]
> [2022/11/16 14:08:19.996 +08:00] [INFO] [db.go:567] ["Closing database"]
> [2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:592] ["Memtable flushed"]
> [2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:596] ["Compaction finished"]
> [2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:615] ["BlobManager finished"]
> [2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:619] ["ResourceManager finished"]
> [2022/11/16 14:08:20.002 +08:00] [INFO] [db.go:625] ["Waiting for closer"]
> --- FAIL: TestModifyColumnTypeWhenInterception (4.84s)
> ```
> 
> ```
> [2022/11/16 14:06:49.552 +08:00] [INFO] [ddl.go:1110] ["[ddl] DDL job is finished"] [jobID=78]
> [2022/11/16 14:06:49.552 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
>     result.go:49: 
>         	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/6696/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/result.go:49
>         	            				/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/linux-sandbox/6696/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/modify_column_test.go:816
>         	Error:      	Not equal: 
>         	            	expected: "[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n[Warning 1292 Truncated incorrect DECIMAL value: '111.22']\n"
>         	            	actual  : "[Warning 1292 4 warnings with this error code, first warning: Truncated incorrect DECIMAL value: '111.22']\n"
>         	            	
>         	            	Diff:
>         	            	--- Expected
>         	            	+++ Actual
>         	            	@@ -1,5 +1,2 @@
>         	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
>         	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
>         	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
>         	            	-[Warning 1292 Truncated incorrect DECIMAL value: '111.22']
>         	            	+[Warning 1292 4 warnings with this error code, first warning: Truncated incorrect DECIMAL value: '111.22']
>         	            	 
>         	Test:       	TestModifyColumnTypeWithWarnings
>         	Messages:   	sql:show warnings, args:[]
> [2022/11/16 14:06:49.554 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 266, tp add index"] ["take time"=1.625µs]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 267, tp add index"] ["take time"=2.03µs]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 268, tp add index"] ["take time"=974ns]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 269, tp add index"] ["take time"=982ns]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 270, tp add index"] ["take time"=1.191µs]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 271, tp add index"] ["take time"=1.165µs]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 272, tp add index"] ["take time"=1.033µs]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 273, tp add index"] ["take time"=902ns]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 274, tp add index"] ["take time"=1.557µs]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 265, tp add index"] ["take time"=916ns]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 264, tp general"] ["take time"=1.018µs]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 262, tp general"] ["take time"=417ns]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 263, tp add index"] ["take time"=649ns]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [delete_range.go:148] ["[ddl] closing delRange"]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [session_pool.go:94] ["[ddl] closing sessionPool"]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl.go:815] ["[ddl] DDL closed"] [ID=562290da-0f7a-450e-82f1-094d5f9a3023] ["take time"=2.849804ms]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [ddl.go:639] ["[ddl] stop DDL"] [ID=562290da-0f7a-450e-82f1-094d5f9a3023]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:1095] ["closestReplicaReadCheckLoop exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:743] ["loadSchemaInLoop exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:1617] ["dumpFileGcChecker exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [handle_hist.go:175] ["SubLoadWorker exited."]
> [2022/11/16 14:06:49.555 +08:00] [INFO] [domain.go:1332] ["LoadSysVarCacheLoop exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:1282] ["loadPrivilegeInLoop exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:1457] ["handleEvolvePlanTasksLoop exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:1413] ["globalBindHandleWorkerLoop exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:608] ["topologySyncerKeeper exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:560] ["infoSyncerKeeper exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:585] ["globalConfigSyncerKeeper exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:531] ["topNSlowQueryLoop exited."]
> [2022/11/16 14:06:49.556 +08:00] [INFO] [domain.go:871] ["domain closed"] ["take time"=3.297455ms]
> [2022/11/16 14:06:49.560 +08:00] [INFO] [db.go:567] ["Closing database"]
> [2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:592] ["Memtable flushed"]
> [2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:596] ["Compaction finished"]
> [2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:615] ["BlobManager finished"]
> [2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:619] ["ResourceManager finished"]
> [2022/11/16 14:06:49.561 +08:00] [INFO] [db.go:625] ["Waiting for closer"]
> --- FAIL: TestModifyColumnTypeWithWarnings (4.49s)
> ```


Some modifications have been made, but the problem now is that the TestModifyColumnTypeWhenInterception testcase originally failed to run in the master, showing job.RowCount=4096, which is not equal to middleWarningsCount. This testcase is judged by warn count, which is always equal to 1 now. Is it unnecessary and can be removed?


[2022/11/16 15:06:55.461 +08:00] [INFO] [ddl.go:1110] ["[ddl] DDL job is finished"] [jobID=78]
[2022/11/16 15:06:55.461 +08:00] [INFO] [callback_test.go:66] ["performing DDL change, must reload"]
    modify_column_test.go:889: 
        	Error Trace:	/Users/zcy/IdeaProjects/tidb/ddl/modify_column_test.go:889
        	Error:      	Should be true
        	Test:       	TestModifyColumnTypeWhenInterception
[2022/11/16 15:06:55.462 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
[2022/11/16 15:06:55.462 +08:00] [INFO] [ddl_worker.go:165] ["[ddl] DDL worker closed"] [worker="worker 10, tp add index"] ["take time"=458ns]

File: ddl/modify_column_test.go [hunk 3]
```diff
@@ -895,5 +890,5 @@ func TestModifyColumnTypeWhenInterception(t *testing.T) {
 	require.True(t, checkMiddleAddedCount)
 
 	res := tk.MustQuery("show warnings")
-	require.Len(t, res.Rows(), count)
+	require.Len(t, res.Rows(), 1)
```
Comment (Defined2014) [inline ddl/modify_column_test.go:893]: Maybe we could check the warning msg which contains warnings count.

Comment (wxbty) [reply ddl/modify_column_test.go]: checkMiddleAddedCount can't pass the check in the master branch, and it's useless now, so I deleted it

**Review by Defined2014 — APPROVED** [review]
