### PR TITLE
*: modify topsql variable should check RESTRICTED_VARIABLES_ADMIN privilege when sem is enabled

### LINKED ISSUE #32663: topsql: modify/show topsql variable should check RESTRICTED_VARIABLES_ADMIN privilege when sem is enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When TiDB `enable-sem` is true, modify the following variable need check `RESTRICTED_VARIABLES_ADMIN` privilege.

```sql
tidb_top_sql_max_time_series_count
tidb_top_sql_max_meta_count
``` 

### 4. What is your TiDB version? (Required)

```
e8be77848d8586ad25b61f8b522b581c3b76760f
```

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #32663

### Check List

Tests 

- [x] Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@breeswish @morgo PTAL

File: util/sem/sem_test.go [hunk 1]
```diff
@@ -103,4 +103,6 @@ func TestIsInvisibleSysVar(t *testing.T) {
 	assert.True(IsInvisibleSysVar(variable.TiDBRowFormatVersion))
 	assert.True(IsInvisibleSysVar(variable.TiDBRedactLog))
 	assert.True(IsInvisibleSysVar(variable.TiDBSlowLogMasking))
+	assert.True(IsInvisibleSysVar(variable.TiDBTopSQLMaxTimeSeriesCount))
+	assert.True(IsInvisibleSysVar(variable.TiDBTopSQLMaxTimeSeriesCount))
```
Comment (breeswish) [inline util/sem/sem_test.go:107]: I think "enable Top SQL" should also be checked. @SunRunAway PTAL

File: util/sem/sem.go [hunk 2]
```diff
@@ -155,7 +155,9 @@ func IsInvisibleSysVar(varNameInLower string) bool {
 		variable.TiDBMemoryUsageAlarmRatio,
 		variable.TiDBRedactLog,
 		variable.TiDBRestrictedReadOnly,
-		variable.TiDBSlowLogMasking:
+		variable.TiDBSlowLogMasking,
```
Comment (breeswish) [inline util/sem/sem.go:158]: Is it an idiom that for variables that cannot be changed without RESTRICTED_VARIABLES_ADMIN they should be hidden? @morgo PTAL

Comment (morgo) [reply util/sem/sem.go:158]: Currently yes. There are two problems:

* Some of these variables can reveal metadata (filesystem paths, hostnames etc).
* In the original design the PM wanted reading the variable to be an error, but there are no cases where MySQL would error on reading a variable, so that behavior makes compatibility weird.

So that is why the behavior of SEM is to hide the variables, even though for the server we are discontinuing the use of "hidden" variables.

**Review by morgo — APPROVED** [review]
