### PR TITLE
lightning: add PK to internal tables

### LINKED ISSUE #57479: lightning's internal table does not have PK so can't work with sql_require_primary_key=ON
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

turn on `sql_require_primary_key` and run lightning

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

lightning will create some internal tables, and failed with error `Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.` This is because these tables have no PK

### 4. What is your TiDB version? (Required)

all version

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #57479

Problem Summary:

### What changed and how does it work?

manually cherry-pick https://github.com/pingcap/tidb/pull/57480

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]
LGTM for BR

File: br/pkg/lightning/errormanager/errormanager.go [hunk 1]
```diff
@@ -40,13 +40,14 @@ const (
 		CREATE SCHEMA IF NOT EXISTS %s;
 	`
 
-	syntaxErrorTableName = "syntax_error_v1"
-	typeErrorTableName   = "type_error_v1"
+	syntaxErrorTableName = "syntax_error_v2"
+	typeErrorTableName   = "type_error_v2"
 	// ConflictErrorTableName is the table name for duplicate detection.
-	ConflictErrorTableName = "conflict_error_v1"
+	ConflictErrorTableName = "conflict_error_v1_2"
```
Comment (lance6716) [inline br/pkg/lightning/errormanager/errormanager.go:46]: Because the table structure diverse with master branch, it's not the same as `conflict_error_v4`. So I use `conflict_error_v1_2` here

**Review by Benjamin2037 — APPROVED** [review]
LGTM
