### PR TITLE
planner: consider OtherConds in MergeJoin cost formula

### LINKED ISSUE #57691: Merge Join's row count estimation doesn't consider the case that the join key degenerates to other condition
## Enhancement
For example, if we have table `t(a int, b int, key a)`. And the SQL `select ... from t t1 join t t2 on t1.a=t2.a and t1.b=t1.b`. To use merge join, we'll only regard `a` as the join key and the `t1.b=t2.b` will become a normal filter after we finish the join key matching.
Image
Image

But, from the picture, you can see that the row count estimation and the cost calculation don't consider such a case.

### LINKED ISSUE #62917: planner: MergeJoin cost formula should consider OtherCond
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1 (id int, a int, b int, c int, primary key(id, a));
create table t2 (id int, a int, b int, c int, primary key(id, a));
```

```
mysql> explain format='verbose' select /*+ merge_join(t1, t2) */ * from t1 join t2 on t1.id=t2.id and t1.a>t2.a;
+-----------------------------+----------+------------+-----------+---------------+--------------------------------------------------------------------------------------------+
| id                          | estRows  | estCost    | task      | access object | operator info                                                                              |
+-----------------------------+----------+------------+-----------+---------------+--------------------------------------------------------------------------------------------+
| MergeJoin_10                | 12500.00 | 999100.00  | root      |               | inner join, left key:test.t1.id, right key:test.t2.id, other cond:gt(test.t1.a, test.t2.a) |
| ├─TableReader_15(Build)     | 10000.00 | 494560.00  | root      |               | data:TableFullScan_14                                                                      |
| │ └─TableFullScan_14        | 10000.00 | 4884000.00 | cop[tikv] | table:t2      | keep order:true, stats:pseudo                                                              |
| └─TableReader_13(Probe)     | 10000.00 | 494560.00  | root      |               | data:TableFullScan_12                                                                      |
|   └─TableFullScan_12        | 10000.00 | 4884000.00 | cop[tikv] | table:t1      | keep order:true, stats:pseudo                                                              |
+-----------------------------+----------+------------+-----------+---------------+--------------------------------------------------------------------------------------------+
5 rows in set (0.002 sec)

mysql> explain format='verbose' select /*+ merge_join(t1, t2) */ * from t1 join t2 on t1.id=t2.id;
+-----------------------------+----------+------------+-----------+---------------+-------------------------------------------------------+
| id                          | estRows  | estCost    | task      | access object | operator info                                         |
+-----------------------------+----------+------------+-----------+---------------+-------------------------------------------------------+
| MergeJoin_10                | 12500.00 | 999100.00  | root      |               | inner join, left key:test.t1.id, right key:test.t2.id |
| ├─TableReader_15(Build)     | 10000.00 | 494560.00  | root      |               | data:TableFullScan_14                                 |
| │ └─TableFullScan_14        | 10000.00 | 4884000.00 | cop[tikv] | table:t2      | keep order:true, stats:pseudo                         |
| └─TableReader_13(Probe)     | 10000.00 | 494560.00  | root      |               | data:TableFullScan_12                                 |
|   └─TableFullScan_12        | 10000.00 | 4884000.00 | cop[tikv] | table:t1      | keep order:true, stats:pseudo                         |
+-----------------------------+----------+------------+-----------+---------------+-------------------------------------------------------+
5 rows in set (0.001 sec)
```

### 2. What did you expect to see? (Required)
The first plan's cost should be larger than the second's.

### 3. What did you see instead (Required)

They have the same cost.

### 4. What is your TiDB version? (Required)

```
 8.0.11-TiDB-v9.0.0-beta.2.pre-302-gd08f914ff1
```

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #62917, close #57691

Problem Summary:

### What changed and how does it work?

Please see the case below, the first plan's cost should be larger than the second one, but now they are the same.
The reason is that we forget to consider the cost of `MergeJoin.OtherConds` in our MergeJoin cost formula, this PR is going to fix this problem.
image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/plan_cost_ver2.go [hunk 1]
```diff
@@ -646,9 +646,10 @@ func getPlanCostVer24PhysicalMergeJoin(pp base.PhysicalPlan, taskType property.T
 	cpuFactor := getTaskCPUFactorVer2(p, taskType)
 
 	filterCost := costusage.SumCostVer2(filterCostVer2(option, leftRows, p.LeftConditions, cpuFactor),
-		filterCostVer2(option, rightRows, p.RightConditions, cpuFactor))
+		filterCostVer2(option, rightRows, p.RightConditions, cpuFactor),
+		filterCostVer2(option, leftRows+rightRows, p.OtherConditions, cpuFactor)) // OtherConditions are applied to both sides
 	groupCost := costusage.SumCostVer2(groupCostVer2(option, leftRows, cols2Exprs(p.LeftJoinKeys), cpuFactor),
-		groupCostVer2(option, rightRows, cols2Exprs(p.LeftJoinKeys), cpuFactor))
+		groupCostVer2(option, rightRows, cols2Exprs(p.RightJoinKeys), cpuFactor))
```
Comment (qw4990) [inline pkg/planner/core/plan_cost_ver2.go:652]: `LeftJoinKeys` should be same with `RightJoinKeys`, so this change should not cause any changes.

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]
