### PR TITLE
coprocessor: fix performance regression when execute DML with lite-cop-worker meet region error

### LINKED ISSUE #58658: performance regression when execute bulk DML with lite-cop-worker
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Image

### 4. What is your TiDB version? (Required)

nightly: a6cd5e7dc9f5b9336f7dc06f13f83300aebf5810

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #58658

Problem Summary:

### What changed and how does it work?

Before this PR:

image

This PR:

image

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/store/copr/coprocessor.go [hunk 1]
```diff
@@ -1110,10 +1110,18 @@ func (it *copIterator) Next(ctx context.Context) (kv.ResultSubset, error) {
 	failpoint.InjectCall("CtxCancelBeforeReceive", ctx)
 	if it.liteWorker != nil {
 		resp = it.liteWorker.liteSendReq(ctx, it)
+		// after lite handle 1 task, reset tryCopLiteWorker to 0 to make future request can reuse copLiteWorker.
+		it.liteWorker.tryCopLiteWorker.Store(0)
```
Comment (cfzjywxk) [inline pkg/store/copr/coprocessor.go:1114]: If this operation is **designed to be performed only once**, it is best to use CAS operations. This approach makes the code more robust, eliminating the need to consider the side-effects of additional settings being applied.

**Review by zyguan — APPROVED** [review]

File: pkg/store/copr/coprocessor.go (hunk 1 above)
Comment (crazycs520) [reply pkg/store/copr/coprocessor.go]: done.

**Review by cfzjywxk — APPROVED** [review]
