### PR TITLE
planner: fix a bug when pushing streamAgg down

### LINKED ISSUE #40857: IndexLookUpExecutor got panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `263b2d5c-986d-4458-864b-b6b2d89387e4` (
  `c67143a0-a8c8-471f-b1e0-f418cc6321eb` mediumint(9) DEFAULT '-4747160',
  `54e46aad-e21c-49ff-b28a-72defacde844` year(4) NOT NULL DEFAULT '2075',
  `e71c6ef8-68c4-4d76-b6aa-edcb278d5644` double DEFAULT '1.1559030660251948',
  `1308c586-a669-4d1c-b59d-14a324a15f6d` enum('wbv4','eli','d8ym','m3gsx','lz7td','o','d1k7l','y1x','xcxq','bj','n7') DEFAULT 'xcxq',
  `48ad39ce-e61b-4afb-a096-d555fc6de442` int(11) DEFAULT '255080866',
  `c62add10-e17f-4c8f-a3e1-220d4c972b87` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`54e46aad-e21c-49ff-b28a-72defacde844`) /*T![clustered_index] CLUSTERED */,
  KEY `8876a554-c88c-4fa6-86a0-a49f475f00a2` (`54e46aad-e21c-49ff-b28a-72defacde844`),
  KEY `e2a4c927-c4fb-49bb-9740-0e202ba73ad7` (`54e46aad-e21c-49ff-b28a-72defacde844`),
  UNIQUE KEY `bf2aa2b8-247b-4742-9b73-a7c182068846` (`54e46aad-e21c-49ff-b28a-72defacde844`),
  UNIQUE KEY `66fa4367-79da-4cc3-8696-6640239a5abe` (`e71c6ef8-68c4-4d76-b6aa-edcb278d5644`),
  UNIQUE KEY `ce5b6a42-045d-48ba-9069-402dbe5c039a` (`54e46aad-e21c-49ff-b28a-72defacde844`,`e71c6ef8-68c4-4d76-b6aa-edcb278d5644`,`1308c586-a669-4d1c-b59d-14a324a15f6d`),
  KEY `4096b35b-98eb-43c0-916e-c7d93e5ae03d` (`54e46aad-e21c-49ff-b28a-72defacde844`,`1308c586-a669-4d1c-b59d-14a324a15f6d`,`e71c6ef8-68c4-4d76-b6aa-edcb278d5644`),
  KEY `b14587ce-407c-4d03-952d-e64ec2c40c7f` (`1308c586-a669-4d1c-b59d-14a324a15f6d`),
  KEY `b5eea074-f908-4fcc-bcf7-d0d6f17e95e5` (`54e46aad-e21c-49ff-b28a-72defacde844`,`e71c6ef8-68c4-4d76-b6aa-edcb278d5644`),
  KEY `c4d86d54-091c-4307-957b-b164c9652b7f` (`c62add10-e17f-4c8f-a3e1-220d4c972b87`,`1308c586-a669-4d1c-b59d-14a324a15f6d`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

insert into `263b2d5c-986d-4458-864b-b6b2d89387e4` values ( -4747160, 2075, 722.5719203870632, 'xcxq', 1576824797
, 1);

select   /*+ agg_to_cop() stream_agg() */  bit_or( `263b2d5c-986d-4458-864b-b6b2d89387e4`.`48ad39ce-e61b-4afb-a096-d555fc6de442` ) as r0 , group_concat(   `263b2d5c-986d-4458-864b-b6b2d89387e4`.`48ad39ce-e61b-4afb-a096-d555fc6de442`
order by `263b2d5c-986d-4458-864b-b6b2d89387e4`.`48ad39ce-e61b-4afb-a096-d555fc6de442` ) as r1 from `263b2d5c-986d-4458-864b-b6b2d89387e4` where not( `263b2d5c-986d-4458-864b-b6b2d89387e4`.`c67143a0-a8c8-471f-b1e0-f418cc6321eb` between -7862876 and -3976555 ) and `263b2d5c-986d-4458-864b-b6b2d89387e4`.`e71c6ef8-68c4-4d76-b6aa-edcb278d5644` in ( select `c62add10-e17f-4c8f-a3e1-220d4c972b87` from `263b2d5c-986d-4458-864b-b6b2d89387e4` where not( `263b2d5c-986d-4458-864b-b6b2d89387e4`.`c62add10-e17f-4c8f-a3e1-220d4c972b87` <> 1 ) and not( `263b2d5c-986d-4458-864b-b6b2d89387e4`.`e71c6ef8-68c4-4d76-b6aa-edcb278d5644` in ( 9263.749352636818 ) ) ) group by `263b2d5c-986d-4458-864b-b6b2d89387e4`.`c67143a0-a8c8-471f-b1e0-f418cc6321eb`;

```
### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
``` SQL
recover="runtime error: index out of range [2] with length 1"] [stack="github.com/pingcap/tidb/executor.(*tableWorker).pickAndExecTask.func1\n\t/Users/bba/pc/tidb/executor/distsql.go:1041\nruntime.gopanic\n\t/Users/bba/.gvm/gos/go1.19/src/runtime/panic.go:884\nruntime.goPanicIndex\n\t/Users/bba/.gvm/gos/go1.19/src/runtime/panic.go:113\ngithub.com/pingcap/tidb/util/chunk.Row.IsNull\n\t/Users/bba/pc/tidb/util/chunk/row.go:218\ngithub.com/pingcap/tidb/util/chunk.Row.GetDatumWithBuffer\n\t/Users/bba/pc/tidb/util/chunk/row.go:150\ngithub.com/pingcap/tidb/util/chunk.Row.GetDatum\n\t/Users/bba/pc/tidb/util/chunk/row.go:133\ngithub.com/pingcap/tidb/executor.(*IndexLookUpExecutor).getHandle\n\t/Users/bba/pc/tidb/executor/distsql.go:1086\ngithub.com/pingcap/tidb/executor.(*tableWorker).executeTask\n\t/Users/bba/pc/tidb/executor/distsql.go:1345\ngithub.com/pingcap/tidb/executor.(*tableWorker).pickAndExecTask\n\t/Users/bba/pc/tidb/executor/distsql.go:1058\ngithub.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker.func1\n\t/Users/bba/pc/tidb/executor/distsql.go:691
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Dousir9**
### What problem does this PR solve?

Issue Number: close #40857 

**Problem Summary:**
minimal reproduce process:

```sql
CREATE TABLE t (
  c1 mediumint(9) DEFAULT '-4747160',
  c2 year(4) NOT NULL DEFAULT '2075',
  c3 double DEFAULT '1.1559030660251948',
  c4 enum('wbv4','eli','d8ym','m3gsx','lz7td','o','d1k7l','y1x','xcxq','bj','n7') DEFAULT 'xcxq',
  c5 int(11) DEFAULT '255080866',
  c6 tinyint(1) DEFAULT '1',
  PRIMARY KEY (c2),
  KEY `c4d86d54-091c-4307-957b-b164c9652b7f` (c6,c4)
);

insert into t values (-4747160, 2075, 722.5719203870632, 'xcxq', 1576824797, 1);

select   /*+ stream_agg() */  bit_or( t.c5 ) as r0 from t 
where t.c3 in ( select c6 from t where not( t.c6 <> 1 ) and not( t.c3 in ( 9263.749352636818 ) ) ) 
group by t.c1;
```

The following plan will introduce this panic:

```sql
mysql> explain select   /*+ stream_agg() */  bit_or( t.c5 ) as r0 from t  where t.c3 in ( select c6 from t where not( t.c6 <> 1 ) and not( t.c3 in ( 9263.749352636818 ) ) )  group by t.c1;
+--------------------------------------------+----------+-----------+-------------------------------------------------------------+----------------------------------------------------------+
| id                                         | estRows  | task      | access object                                               | operator info                                            |
+--------------------------------------------+----------+-----------+-------------------------------------------------------------+----------------------------------------------------------+
| StreamAgg_17                               | 6.66     | root      |                                                             | group by:test.t.c1, funcs:bit_or(test.t.c5)->Column#13   |
| └─Sort_52                                  | 6.66     | root      |                                                             | test.t.c1                                                |
|   └─HashJoin_21                            | 6.66     | root      |                                                             | inner join, equal:[eq(Column#14, test.t.c3)]             |
|     ├─Projection_22(Build)                 | 5.33     | root      |                                                             | cast(test.t.c6, double BINARY)->Column#14                |
|     │ └─StreamAgg_43                       | 5.33     | root      |                                                             | group by:test.t.c6, funcs:firstrow(test.t.c6)->test.t.c6 |
|     │   └─IndexLookUp_44                   | 5.33     | root      |                                                             |                                                          |
|     │     ├─IndexRangeScan_40(Build)       | 10.00    | cop[tikv] | table:t, index:c4d86d54-091c-4307-957b-b164c9652b7f(c6, c4) | range:[1,1], keep order:true, stats:pseudo               |
|     │     └─StreamAgg_29(Probe)            | 5.33     | cop[tikv] |                                                             | group by:test.t.c6,                                      |
|     │       └─Selection_42                 | 6.66     | cop[tikv] |                                                             | ne(test.t.c3, 9263.749352636818)                         |
|     │         └─TableRowIDScan_41          | 10.00    | cop[tikv] | table:t                                                     | keep order:false, stats:pseudo                           |
|     └─TableReader_51(Probe)                | 10000.00 | root      |                                                             | data:TableFullScan_50                                    |
|       └─TableFullScan_50                   | 10000.00 | cop[tikv] | table:t                                                     | keep order:false, stats:pseudo                           |
+--------------------------------------------+----------+-----------+-------------------------------------------------------------+----------------------------------------------------------+
12 rows in set (0.00 sec)
```

**What happend:**
In indexLookUp, the `handles`(row id) fetched from index is originally ordered by index, when `keepOrder` is true, we will save the order of `handles` in `indexOrder`, and then `tableWorker` will use `handles` to rescan table to obtain rows. If `keepOrder` is true, the `tableWorker` will restore the rows to the original order through `indexOrder`. When restoring, we need to extract the `handle` from the row. In the above plan, the `agg` is pushed down, and its schma only contains `c6` and does not contain the `handle` , but the executor thinks that the `handle` is in the third column of the row, resulting in "index out of range [2]".

### What is changed and how it works?
The reason for the above error is that streamAgg was pushed down to double read when `keepOrder` was true. I looked through the historical PRs and found that @winoros solved this problem in [PR#12443](https://github.com/pingcap/tidb/pull/12443): if the original order of index needs to be maintained during double read (Call this situation doubleReadWithOrderReserved), we will prevent the optimizer from pushing streamagg down to double read. PR#12443 uses `extraHandleCol` to determine whether the current situation is doubleReadWithOrderReserved. At that time, if `extraHandleCol != nil`, then it must be the case of doubleReadWithOrderReserved.

But then [PR#18054](https://github.com/pingcap/tidb/pull/18054)  added `!ds.tableInfo.IsCommonHandle`, which caused `extraHandleCol` may be `nil` in the case of doubleReadWithOrderReserved, so we can’t use `extraHandleCol`, we can use `(cop.indexPlan != nil && cop.tablePlan != nil && cop.keepOrder)` to represent this situation .

```go
PR#18054:
- if cop.tablePlan != nil {
+ if cop.tablePlan != nil && !ds.tableInfo.IsCommonHandle {
  	col, isNew := cop.tablePlan.(*PhysicalTableScan).appendExtraHandleCol(ds)
  	cop.extraHandleCol = col
  	// ...
  }
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Dousir9** [comment]
The check-issue-triage-complete fails, @wjhuang2016 could you help me to fix it, thanks.

**Comment by Dousir9** [comment]
It looks like there is something wrong with `TestRcTSOCmdCountForTextSQLExecuteNormal`, [PR41155](https://github.com/pingcap/tidb/pull/41155) and [PR#41151](https://github.com/pingcap/tidb/pull/41151) also fail this test, the master branch also fails this test.

**Comment by Dousir9** [comment]
It looks like there is something wrong with CI.

**Review by winoros — APPROVED** [review]

File: planner/core/task.go [hunk 1]
```diff
@@ -1748,9 +1750,8 @@ func (p *PhysicalStreamAgg) attach2Task(tasks ...task) task {
 	t := tasks[0].copy()
 	if cop, ok := t.(*copTask); ok {
 		// We should not push agg down across double read, since the data of second read is ordered by handle instead of index.
-		// The `extraHandleCol` is added if the double read needs to keep order. So we just use it to decided
-		// whether the following plan is double read with order reserved.
-		if cop.extraHandleCol != nil || len(cop.rootTaskConds) > 0 {
+		// We use doubleReadWithOrderReserved to decided whether the following plan is double read with order reserved.
+		if cop.doubleReadWithOrderReserved || len(cop.rootTaskConds) > 0 {
```
Comment (fixdb) [inline planner/core/task.go:1754]: Maybe I am too conservative on adding new fields to CopTask, but can we use `(cop.indexPlan != nil && cop.tablePlan != nil && cop.keepOrder)` to represent `doubleReadWithOrderReserved`, instead of adding this field to CopTask?

**Comment by fixdb** [comment]
What if there is indexMerge and the IndexMerge keeps order? Is that possible?

File: planner/core/task.go (hunk 1 above)
Comment (Dousir9) [reply planner/core/task.go:1754]: Yeah, i think it works.

**Comment by Dousir9** [comment]
> What if there is indexMerge and the IndexMerge keeps order? Is that possible?

I think it it impossible, because the handles fetched by indexs will be unioned.

**Review by fixdb — APPROVED** [review]
LGTM, thanks for contributing!
