### PR TITLE
planner: fix wrongly skip plan cache with predicate simplification | tidb-test=pr/2526 

### LINKED ISSUE #61513: wrongly skip plan cache with
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #61513

Problem Summary:

### What changed and how does it work?

In the original code, if you perform predicate simplification, it will skip the plan cache. However, based on the test case examples, if the predicate does not contain any placeholders, there is actually no need to skip the plan cache.

We use ```MaybeOverOptimized4PlanCache``` to rightly implement it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: fix wrongly skip plan cache with predicate simplification

修复错误的跳过 plan cache，当进行谓词简化
```

### CODE REVIEW

File: pkg/expression/util.go [hunk 1]
```diff
@@ -1556,6 +1556,12 @@ func MaybeOverOptimized4PlanCache(ctx BuildContext, exprs []Expression) bool {
 	return containMutableConst(ctx.GetEvalCtx(), exprs)
 }
 
+// MaybeOverOptimized4PlanCacheForMultiExpression is the same as MaybeOverOptimized4PlanCache,
+// but it accepts multiple expressions as input.
+func MaybeOverOptimized4PlanCacheForMultiExpression(ctx BuildContext, exprs ...Expression) bool {
```
Comment (hawkingrei) [inline pkg/expression/util.go:1561]: ```MaybeOverOptimized4PlanCacheForMultiExpression``` can replace `MaybeOverOptimized4PlanCache`. But this PR is for bugfix. I don't want to change too many.

**Review by AilinKid — APPROVED** [review]
LGTM

File: pkg/planner/core/rule_predicate_simplification.go [hunk 2]
```diff
@@ -396,7 +412,7 @@ func processCondition(sctx base.PlanContext, condition expression.Expression) (e
 		condition, applied = shortCircuitANDORLogicalConstants(sctx, condition, false)
 	}
 
-	if applied {
+	if applied && expression.MaybeOverOptimized4PlanCacheForMultiExpression(sctx.GetExprCtx(), condition) {
```
Comment (time-and-fate) [inline pkg/planner/core/rule_predicate_simplification.go]: When it comes to here, the `condition` may already be changed, I think we need to do this check before `shortCircuitANDORLogicalConstants`.

Comment (hawkingrei) [reply pkg/planner/core/rule_predicate_simplification.go]: Updated

**Review by windtalker — COMMENTED** [review]
maybe add a test for this?

**Comment by windtalker** [comment]
> maybe add a test for this?

seems there is already test in tidb-test repo
