### PR TITLE
ddl: Increase ddl unit test speed

### LINKED ISSUE #41216: ddl: run unit test is too slow
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Using `make testpkg pkg=ddl` will take too much time and always timeout at some test case. 
After dig into the code create a new TestKit will take more than 1 second.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #41216

Problem Summary:
make test or make ut is too slow, sometimes timeout after 10min

### What is changed and how it works?

Update some ticker and wait time to shorten the wait time for unit test.

1. domain.Reload should notify `mdlCheckLoop`
2. DDL's job dispatch loop should decrease sleep time when owner or waiting check. (In test case, isOwner will return false sometimes after create the testkit.)

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @wjhuang2016 @zimulala

**Comment by hawkingrei** [comment]
> /ok-to-test

It is unnecessary for you. It is for pingcap's staff members to allow contributors to run CI tasks for safety factors. Now you can run tasks by yourself.

File: domain/domain.go [hunk 1]
```diff
@@ -711,78 +712,86 @@ func (do *Domain) refreshMDLCheckTableInfo() {
 }
 
 func (do *Domain) mdlCheckLoop() {
-	ticker := time.Tick(time.Millisecond * 50)
+	var ticker <-chan time.Time
+	if intest.InTest {
```
Comment (blacktear23) [inline domain/domain.go:716]: If we provide a notify after MDL updated is change the tick duration in test required? @hawkingrei

**Review by tangenta — APPROVED** [review]

File: domain/domain.go (hunk 1 above)
Comment (hawkingrei) [reply domain/domain.go:716]: I think it is possible to implement it.

**Review by hawkingrei — APPROVED** [review]

File: ddl/job_table.go [hunk 2]
```diff
@@ -174,15 +175,24 @@ func (d *ddl) startDispatchLoop() {
 	if d.etcdCli != nil {
 		notifyDDLJobByEtcdCh = d.etcdCli.Watch(d.ctx, addingDDLJobConcurrent)
 	}
-	ticker := time.NewTicker(1 * time.Second)
+	var ticker *time.Ticker
+	if intest.InTest {
```
Comment (zimulala) [inline ddl/job_table.go:179]: Personally, I think it is ugly to introduce `inTest` into the code, should it be directly used as a variable, such as xxxInterval, and then directly change this variable for testing, rather than into the real code

Comment (blacktear23) [reply ddl/job_table.go:179]: Agreed. And by the way, why sleep for 1 second? Why not some formula with some variables like `nn * TTL`

Comment (zimulala) [reply ddl/job_table.go:179]: The original code is https://github.com/pingcap/tidb/blob/release-6.4/ddl/ddl_worker.go#L182. Fine-tuning may have been done to support parallel DDL. I think it should be similar to the original logic implementation, which has some association with TTL (lease).

File: domain/domain.go [hunk 3]
```diff
@@ -711,78 +712,86 @@ func (do *Domain) refreshMDLCheckTableInfo() {
...
+		ticker = time.Tick(time.Millisecond * 2)
+	} else {
+		ticker = time.Tick(time.Millisecond * 50)
```
Comment (zimulala) [inline domain/domain.go:719]: Should we do the same here? (Add a variable.)

RestLGTM

Comment (blacktear23) [reply domain/domain.go:719]: Yes, sure.

**Review by zimulala — APPROVED** [review]

**Comment by blacktear23** [comment]
Is anyone has any idea about why the unit-test always fail?

File: ddl/job_table.go [hunk 4]
```diff
@@ -37,17 +37,26 @@ import (
...
-	addingBackfillJob      = "/tidb/ddl/add_backfill_job"
+	addingDDLJobConcurrent      = "/tidb/ddl/add_ddl_job_general"
+	addingBackfillJob           = "/tidb/ddl/add_backfill_job"
+	dispatchLoopWaitingDuration = 1 * time.Second
 )
 
+func init() {
+	// In test the wait duration can be reduced to make test case run faster
+	if intest.InTest {
+		dispatchLoopWaitingDuration = 2 * time.Millisecond
```
Comment (blacktear23) [inline ddl/job_table.go:56]: Seems this change may break executor's stale txn tests

Comment (blacktear23) [reply ddl/job_table.go]: I change it higher see if it will fix the tests
