### PR TITLE
lightning: not set pos to end if fail to `ReadUntil`

### LINKED ISSUE #40034: lightning: error offset exceed range of file
lightning report: 
```
tidb lightning encountered error: [Lightning:Restore:ErrEncodeKV]encode kv error in file db.test.1.csv:0 at offset 45: syntax error: unterminated quoted field
```
But the file contains only 45 byte:
```
 File: /home/test_imp/db.test.1.csv
  Size: 45        	Blocks: 8          IO Block: 4096   regular file
Device: fd02h/64770d	Inode: 15213592    Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-12-19 15:39:36.257455006 +0800
Modify: 2022-12-19 15:40:06.684149942 +0800
Change: 2022-12-19 15:40:06.684149942 +0800
 Birth: -
```
The index exceeds the range and thus, the error log output nothing:
```
[2022/12/19 15:39:36.348 +08:00] [ERROR] [parser.go:208] ["syntax error"] [pos=45] [content=]
```

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: close #40034 

Problem Summary:

### What is changed and how it works?
- not set pos to end
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/mydump/csv_parser.go [hunk 1]
```diff
@@ -341,7 +342,7 @@ func (parser *CSVParser) readUntil(chars *byteSet) ([]byte, byte, error) {
 			if err == nil {
 				err = io.EOF
 			}
-			parser.pos += int64(len(buf))
+			// parser.pos += int64(len(buf))
```
Comment (gozssky) [inline br/pkg/lightning/mydump/csv_parser.go:345]: This changed the semantics of `pos`. `pos` means the current file offset. Since we have read to the end, the pos should be set to the end offset.

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go:345]: just a test. I didn't change it here.

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go:345]: This demand is from import on cloud. We are trying to use the offset reported in the syntax error to show the content in users' files. However, in an unterminated quote error, the offset always exceeds the range of the file. So I am about to return the position to the previous one.

If we meet an error, setting back the `pos` seems safe because we will never use it again.

Comment (gozssky) [reply br/pkg/lightning/mydump/csv_parser.go:345]: > However, in an unterminated quote error, the offset always exceeds the range of the file.

Why does offset exceed the range of the file?  The end offset is also a valid offset.

It's hard to tell which pos is the starting point of syntax error. Suppose we have a line of data: `a,b,c,"xxxxx`
It's obvious that it has an unterminated quote error. But what is the right pos of syntax error? Is it the start pos of `"xxxx` or the end pos of this line? In my opinion, the end pos is not a wrong answer, because everything is still valid until the end.

I'm not sure how you use the syntax error pos. If you just want to print content near the error, you can print the content around the pos. e.g When pos is 1000, print content[800:1200].

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go:345]: We tend to present the starting point of the unterminated quote (i.e., the first quote). Because users should fix the data files and import them again, acknowledging the starting point would be better than telling them the end offset of the whole file, which is a bit meaningless.

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go:345]: > Why does offset exceed the range of the file? The end offset is also a valid offset.

It is the position of EOF (e.g., the size of the file is 35 bytes, then the end of the offset is 35).

File: br/pkg/lightning/mydump/csv_parser.go [hunk 2]
```diff
@@ -447,9 +448,17 @@ outside:
...
-		err = parser.replaceEOF(err, errUnterminatedQuotedField)
 		if err != nil {
+			if errors.Cause(err) == io.EOF {
+				// return the position of quote to the caller.
+				// because we return an error here, the parser won't
+				// use the `pos` again, so it's safe to modify it here.
+				parser.pos = prevPos - 1
+				err = parser.replaceEOF(err, errUnterminatedQuotedField)
+			}
+			parser.Logger.Error("err content", zap.ByteString("content", content))
```
Comment (gozssky) [inline br/pkg/lightning/mydump/csv_parser.go:461]:
```suggestion
```

Comment (gozssky) [reply br/pkg/lightning/mydump/csv_parser.go:461]: Already logged in `logSyntaxError`.

**Review by gozssky — COMMENTED** [review]
Rest LGTM.

File: br/pkg/lightning/mydump/csv_parser.go (hunk 2 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go:461]: No, it won't be logged in `logSyntaError`:
```
[2023/01/05 22:32:09.314 +08:00] [ERROR] [parser.go:208] ["syntax error"] [pos=30] [content=]
[2023/01/05 22:32:09.314 +08:00] [ERROR] [csv_parser.go:461] ["err content"] [content=",7,8\n"]
```
The reason is that `parser.buf` has already been set to nil and only points to the content if the parser doesn't meet error.
```golang
for {
		buf = append(buf, parser.buf...)
		parser.buf = nil
		if err := parser.readBlock(); err != nil || len(parser.buf) == 0 {
			if err == nil {
				err = io.EOF
			}
			parser.pos += int64(len(buf))
			return buf, 0, errors.Trace(err)
		}
                 index := IndexAnyByte(parser.buf, chars)
		if index >= 0 {
			buf = append(buf, parser.buf[:index]...)
			parser.buf = parser.buf[index:]
			parser.pos += int64(len(buf))
			return buf, parser.buf[0], nil
		}
```

Comment (gozssky) [reply br/pkg/lightning/mydump/csv_parser.go:461]: Could we let `logSyntaError` print the content instead of a new log which looks a little confusing?

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go:461]: What about set `parser.buf = buf` if we meet an EOF error?

Comment (gozssky) [reply br/pkg/lightning/mydump/csv_parser.go:461]: > What about set `parser.buf = buf` if we meet an EOF error?

LGTM

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go]: 66f141f

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go]: 5a55279

File: br/pkg/lightning/mydump/csv_parser.go [hunk 3]
```diff
@@ -342,6 +343,7 @@ func (parser *CSVParser) readUntil(chars *byteSet) ([]byte, byte, error) {
 				err = io.EOF
 			}
 			parser.pos += int64(len(buf))
+			log.L().Info("size of buf", zap.Int("size", len(buf)))
```
Comment (lance6716) [inline br/pkg/lightning/mydump/csv_parser.go:346]:
```suggestion
			log.L().Debug("size of buf", zap.Int("size", len(buf)))
```

Not sure in most cases we care about this log

File: br/tests/lightning_csv/run.sh [hunk 4]
```diff
@@ -41,3 +41,9 @@ for BACKEND in tidb local; do
   check_not_contains 'id:'
 
 done
+
+run_lightning --backend local -d "tests/$TEST_NAME/errData" --log-file "$TEST_DIR/lightning-err.log"
+# err content presented
+grep ",7,8" "$TEST_DIR/lightning-err.log"
+# pos should not set to end
+grep "[\"syntax error\"] [pos=30]" "$TEST_DIR/lightning-err.log"
```
Comment (lance6716) [inline br/tests/lightning_csv/run.sh:49]: how to use the value 30? seems the quote is at offset 22

File: br/pkg/lightning/mydump/csv_parser.go (hunk 3 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go:346]: Sry. I just forget to cancel this line (it's served for test: https://github.com/pingcap/tidb/issues/40400)

File: br/tests/lightning_csv/run.sh (hunk 4 above)
Comment (buchuitoudegou) [reply br/tests/lightning_csv/run.sh:49]: Same as above, I changed the test file and forgot to change test script😭

File: br/pkg/lightning/mydump/csv_parser.go (hunk 3 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/csv_parser.go]: 5fd6c58ac

File: br/tests/lightning_csv/run.sh (hunk 4 above)
Comment (buchuitoudegou) [reply br/tests/lightning_csv/run.sh]: 5fd6c58ac

**Comment by lance6716** [comment]
lgtm

wait the result of BR CI

**Comment by lance6716** [comment]
@buchuitoudegou please fix CI (lightning exit code not zero)

**Comment by buchuitoudegou** [comment]
aborted...
/run-integration-br-test

**Comment by buchuitoudegou** [comment]
@lance6716 @gozssky PTAL again. The CI has passed.

**Review by gozssky — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
