### PR TITLE
planner: fix wrong `DATE/DATETIME` comparison in `BETWEEN` function

### LINKED ISSUE #9764: Wrong `DATE/DATETIME` comparison in `BETWEEN` function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t1 (f1 date, f2 datetime, f3 timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
insert into t1 values('2001-01-01','2001-01-01 01:01:01','2001-01-01 01:01:01');
select f2 from t1 where '2001-04-10 12:34:56' between f2 and '01-05-01';
```

2. What did you expect to see?
In Mysql
```
mysql> create table t1 (f1 date, f2 datetime, f3 timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t1 values('2001-01-01','2001-01-01 01:01:01','2001-01-01 01:01:01');
Query OK, 1 row affected (0.00 sec)

mysql> select f2 from t1 where '2001-04-10 12:34:56' between f2 and '01-05-01';
+---------------------+
| f2                  |
+---------------------+
| 2001-01-01 01:01:01 |
+---------------------+
1 row in set (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> create table t1 (f1 date, f2 datetime, f3 timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values('2001-01-01','2001-01-01 01:01:01','2001-01-01 01:01:01');
Query OK, 1 row affected (0.00 sec)

mysql> select f2 from t1 where '2001-04-10 12:34:56' between f2 and '01-05-01';
Empty set (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-227-g06183393e-dirty
Git Commit Hash: 06183393ed536aa248248b72d4bf9f5010947f66
Git Branch: master
UTC Build Time: 2019-03-15 08:22:53
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by erjiaqing**
### What problem does this PR solve? 

Fix #9764 

### What is changed and how it works?

Add converts in `betweenToExpression` when `GetCmpTp4MinMax` returns DateTime type. The behavior should be same as MySQL 8.0 now.

In mysql, If all values are string-like (string & datetime) and contains datetime, then values are converted to datetime.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

### CODE REVIEW

File: planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -1259,11 +1259,29 @@ func (er *expressionRewriter) betweenToExpression(v *ast.BetweenExpr) {
 	if er.err != nil {
 		return
 	}
+
+	expr, lexp, rexp := er.ctxStack[stkLen-3], er.ctxStack[stkLen-2], er.ctxStack[stkLen-1]
+
+	if expression.AggCmpType(expr.GetType(), lexp.GetType(), rexp.GetType()) == types.ETString {
```
Comment (qw4990) [inline planner/core/expression_rewriter.go]: How about add some comments for further maintain like `from MySQL Item_func_between::resolve_type`.
