### PR TITLE
executor: tiny refactor code to improve CheckTableExec

### LINKED ISSUE #32294: DATA RACE in the TestCheckFailReport
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c001990800 by goroutine 59:
  github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).SetStatusFlag()
      /go/tidb/sessionctx/variable/session.go:1470 +0x4f8
  github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).SetInTxn()
      /go/tidb/sessionctx/variable/session.go:1481 +0x4c3
  github.com/pingcap/tidb/session.(*session).RollbackTxn()
      /go/tidb/session/session.go:984 +0x49d
  github.com/pingcap/tidb/session.autoCommitAfterStmt()
      /go/tidb/session/tidb.go:261 +0x365
  github.com/pingcap/tidb/session.finishStmt()
      /go/tidb/session/tidb.go:238 +0x3ab
  github.com/pingcap/tidb/session.runStmt()
      /go/tidb/session/session.go:1993 +0x95d
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      /go/tidb/session/session.go:1859 +0xdb3
  github.com/pingcap/tidb/session.(*session).Execute()
      /go/tidb/session/session.go:1513 +0x4b9
  github.com/pingcap/tidb/testkit.(*AsyncTestKit).Exec()
      /go/tidb/testkit/asynctestkit.go:142 +0x168
  github.com/pingcap/tidb/executor_test.TestCheckFailReport.func5()
      /go/tidb/executor/admin_test.go:1234 +0x6a4
  github.com/pingcap/tidb/executor_test.TestCheckFailReport()
      /go/tidb/executor/admin_test.go:1248 +0x369
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous read at 0x00c001990800 by goroutine 94:
  github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).GetStatusFlag()
      /go/tidb/sessionctx/variable/session.go:1475 +0x324
  github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).InTxn()
      /go/tidb/sessionctx/variable/session.go:1489 +0x318
  github.com/pingcap/tidb/session.(*session).GetInfoSchema()
      /go/tidb/session/session.go:3377 +0x2ea
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderBase()
      /go/tidb/executor/builder.go:4027 +0x393
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderFromHandles()
      /go/tidb/executor/builder.go:4056 +0x264
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).buildTableReader()
      /go/tidb/executor/distsql.go:672 +0xa7c
  github.com/pingcap/tidb/executor.(*tableWorker).executeTask()
      /go/tidb/executor/distsql.go:1272 +0x95
  github.com/pingcap/tidb/executor.(*tableWorker).pickAndExecTask()
      /go/tidb/executor/distsql.go:1018 +0x28b
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker.func1()
      /go/tidb/executor/distsql.go:645 +0xe4
Goroutine 59 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      /go/tidb/testkit/testmain/wrapper.go:28 +0x42
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/executor_test.TestMain()
      /go/tidb/executor/main_test.go:64 +0x785
  main.main()
      _testmain.go:955 +0x264
Goroutine 94 (running) created at:
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker()
      /go/tidb/executor/distsql.go:643 +0xe8
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startWorkers()
      /go/tidb/executor/distsql.go:504 +0x119
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).Next()
      /go/tidb/executor/distsql.go:716 +0x10d
  github.com/pingcap/tidb/executor.Next()
      /go/tidb/executor/executor.go:286 +0x58f
  github.com/pingcap/tidb/executor.(*CheckTableExec).checkIndexHandle()
      /go/tidb/executor/executor.go:728 +0x20a
  github.com/pingcap/tidb/executor.(*CheckTableExec).Next.func2.1()
      /go/tidb/executor/executor.go:786 +0xbd
  github.com/pingcap/tidb/util.WithRecovery()
      /go/tidb/util/misc.go:100 +0x77
  github.com/pingcap/tidb/executor.(*CheckTableExec).Next.func2()
      /go/tidb/executor/executor.go:785 +0x14b
  github.com/pingcap/tidb/executor.(*CheckTableExec).Next·dwrap·42()
      /go/tidb/executor/executor.go:791 +0x47
==================
==================
WARNING: DATA RACE
Write at 0x00c001990898 by goroutine 59:
  github.com/pingcap/tidb/executor.ResetContextOfStmt()
      /go/tidb/executor/executor.go:1882 +0x2c1e
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      /go/tidb/session/session.go:1810 +0x3c4
  github.com/pingcap/tidb/session.(*session).Execute()
      /go/tidb/session/session.go:1513 +0x4b9
  github.com/pingcap/tidb/testkit.(*AsyncTestKit).Exec()
      /go/tidb/testkit/asynctestkit.go:142 +0x168
  github.com/pingcap/tidb/testkit.(*AsyncTestKit).MustExec()
      /go/tidb/testkit/asynctestkit.go:174 +0xb7
  github.com/pingcap/tidb/executor_test.(*inconsistencyTestKit).rebuild()
      /go/tidb/executor/admin_test.go:989 +0xa4
  github.com/pingcap/tidb/executor_test.TestCheckFailReport.func5·dwrap·3()
      /go/tidb/executor/admin_test.go:1224 +0x39
  github.com/pingcap/tidb/executor_test.TestCheckFailReport.func5()
      /go/tidb/executor/admin_test.go:1248 +0xb5f
  github.com/pingcap/tidb/executor_test.TestCheckFailReport()
      /go/tidb/executor/admin_test.go:1248 +0x369
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous read at 0x00c001990898 by goroutine 94:
  github.com/pingcap/tidb/executor.(*tableWorker).compareData()
      /go/tidb/executor/distsql.go:1216 +0xc1e
  github.com/pingcap/tidb/executor.(*tableWorker).executeTask()
      /go/tidb/executor/distsql.go:1280 +0x524
  github.com/pingcap/tidb/executor.(*tableWorker).pickAndExecTask()
      /go/tidb/executor/distsql.go:1018 +0x28b
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker.func1()
      /go/tidb/executor/distsql.go:645 +0xe4
Goroutine 59 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      /go/tidb/testkit/testmain/wrapper.go:28 +0x42
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/executor_test.TestMain()
      /go/tidb/executor/main_test.go:64 +0x785
  main.main()
      _testmain.go:955 +0x264
Goroutine 94 (running) created at:
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker()
      /go/tidb/executor/distsql.go:643 +0xe8
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startWorkers()
      /go/tidb/executor/distsql.go:504 +0x119
  github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).Next()
      /go/tidb/executor/distsql.go:716 +0x10d
  github.com/pingcap/tidb/executor.Next()
      /go/tidb/executor/executor.go:286 +0x58f
  github.com/pingcap/tidb/executor.(*CheckTableExec).checkIndexHandle()
      /go/tidb/executor/executor.go:728 +0x20a
  github.com/pingcap/tidb/executor.(*CheckTableExec).Next.func2.1()
      /go/tidb/executor/executor.go:786 +0xbd
  github.com/pingcap/tidb/util.WithRecovery()
      /go/tidb/util/misc.go:100 +0x77
  github.com/pingcap/tidb/executor.(*CheckTableExec).Next.func2()
      /go/tidb/executor/executor.go:785 +0x14b
  github.com/pingcap/tidb/executor.(*CheckTableExec).Next·dwrap·42()
      /go/tidb/executor/executor.go:791 +0x47
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #32294

Problem Summary:
1、When ```Close``` ```CheckTableExec```, it will stop all the goroutine.
2、When ```checkIndexHandle``` meet error. it will stop all the goroutine created by ```CheckTableExec```.
3、no wait for WaitGroup for a long time.
4、fix data race.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code
          use old test cases.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: executor/executor.go [hunk 1]
```diff
@@ -791,32 +787,43 @@ func (e *CheckTableExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
-					logutil.Logger(ctx).Info("check index handle failed", zap.Error(err1))
+				for {
+					if fail := failure.Load(); fail {
+						return
+					}
+					select {
+					case src := <-taskCh:
+						err1 := e.checkIndexHandle(ctx, src)
+						if err1 != nil {
+							failure.Store(true)
```
Comment (zimulala) [inline executor/executor.go:808]: Why not return directly?

File: executor/executor.go [hunk 2]
```diff
@@ -742,19 +744,13 @@ func (e *CheckTableExec) checkIndexHandle(ctx context.Context, src *IndexLookUpE
...
 			break
 		}
 		if chk.NumRows() == 0 {
 			break
 		}
-
-		select {
-		case <-e.exitCh:
-			return nil
-		default:
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply executor/executor.go:754]: if keeping it, we will have two placements to check whether it can exit or not and it will check the status too frequently. so I think it is more reasonable that it is removed.

File: executor/executor.go (hunk 1 above)
Comment (hawkingrei) [reply executor/executor.go:808]: I forget it. Fixed.

File: executor/executor.go [hunk 3]
```diff
@@ -797,32 +793,51 @@ func (e *CheckTableExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
-	for i := range e.srcs {
-		wg.Add(1)
-		go func(num int) {
-			defer wg.Done()
+	if len(e.srcs) == 1 {
+		err := e.checkIndexHandle(ctx, e.srcs[0])
+		if err != nil {
+			return errors.Trace(err)
+		}
+		return nil
```
Comment (tiancaiamao) [inline executor/executor.go:801]: Hint: `return e.checkIndexHandle(ctx, e.srcs[0])` save several lines of code

**Review by tiancaiamao — APPROVED** [review]

File: executor/executor.go (hunk 3 above)
Comment (hawkingrei) [reply executor/executor.go]: Thank. fixed

**Review by guo-shaoge — APPROVED** [review]

File: executor/executor.go [hunk 4]
```diff
@@ -797,32 +793,47 @@ func (e *CheckTableExec) Next(ctx context.Context, req *chunk.Chunk) error {
...
+					}
+					select {
+					case src := <-taskCh:
+						err1 := e.checkIndexHandle(ctx, src)
+						if err1 != nil {
+							failure.Store(true)
+							logutil.Logger(ctx).Info("check index handle failed", zap.Error(err1))
+							return
+						}
+					case <-e.exitCh:
```
Comment (wshwsh12) [inline executor/executor.go:821]: Can this guarantee CheckTableExec exit in time when panic happening?
`select` stmt will pick a chan randomly.. So after `close(e.exitCh)`, it also has the possibility to pick the `taskCh` and runs checkIndexHandle?

Comment (hawkingrei) [reply executor/executor.go:821]: I think it is a common resource release. ```Close``` just make them exciting. it is possible that pick the taskCh and runs checkIndexHandle. but my aim is to that it can be exited as soon as possible.
