### PR TITLE
ddl: convert hexLit to stringLit in enum and set default value.

### LINKED ISSUE #18977: Can't create latin1 enum
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql root@127.0.0.1:test> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
```

### 2. What did you expect to see? (Required)
```
mysql root@127.0.0.1:test> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
Query OK, 0 rows affected
Time: 0.024s
mysql root@127.0.0.1:test> show create table t1
+-------+----------------------------------------------+
| Table | Create Table                                 |
+-------+----------------------------------------------+
| t1    | CREATE TABLE `t1` (                          |
|       |   `a` enum('ä','1','2') NOT NULL DEFAULT 'ä' |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=latin1       |
+-------+----------------------------------------------+
1 row in set
Time: 0.016s
```

### 3. What did you see instead (Required)
```
mysql root@127.0.0.1:test> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 28 near "0xE4, \'1\', \'2\') not null default 0xE4) character set latin1" ')
```

### 4. Affected version (Required)

```
mysql root@127.0.0.1:test> select tidb_version()
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-888-g4645c6582                     |
| Edition: Community                                                |
| Git Commit Hash: 4645c6582d7d57ae256b1bd7a1c18476c56b4d3c         |
| Git Branch: master                                                |
| UTC Build Time: 2020-08-04 07:06:10                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
1 row in set
Time: 0.015s
```

### PR DESCRIPTION
**Pull request by tangwz**
### What problem does this PR solve?

Issue Number: close #18977 

Problem Summary:

```
mysql> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;                                                                
(1067, "Invalid default value for 'a'")
```

### What is changed and how it works?

What's Changed:

When the datum kind is mysql.TypeEnum, the value should be stored as a string instead of an integer number.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- None

### Release note 

- fix cannot create enum and set column if its default value is hexLit

### CODE REVIEW

**Review by tangenta — COMMENTED** [review]
Could you please add a test case?

**Comment by tangwz** [comment]
```
mysql> show create table t11;
+-------+---------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                    |
+-------+---------------------------------------------------------------------------------------------------------------------------------+
| t11   | CREATE TABLE `t11` (
  `a` enum('�','1','2') NOT NULL DEFAULT '�'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin     |
+-------+---------------------------------------------------------------------------------------------------------------------------------+
```

@tangenta  This is a unknown character how can I test this?

**Comment by xiongjiwei** [comment]
> This is an unknown character how can I test this?

```sql
mysql> create table t1 (a enum(0xE4, '1', '2') not null default 0xE4) character set latin1;
Query OK, 0 rows affected (0.07 sec)

mysql> show create table t1;
+-------+-----------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                              |
+-------+-----------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `a` enum('ä','1','2') NOT NULL DEFAULT 'ä'
) ENGINE=InnoDB DEFAULT CHARSET=latin1   |
+-------+-----------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

@tangwz it should not be an unknown character for charset `latin1`

**Comment by tangwz** [comment]
@tangenta @xiongjiwei PTAL.

Thanks.

**Comment by xiongjiwei** [comment]
we actually do not support latin1 character which codepoint greater than `0x7f`.
In MySQL
```sql
mysql> select _latin1 0x80;
+--------------+
| _latin1 0x80 |
+--------------+
| €            |
+--------------+
1 row in set (0.00 sec)
```

in tidb
```sql
mysql> select _latin1 0x80;
+--------------+
| _latin1 0x80 |
+--------------+
| �             |
+--------------+
1 row in set (0.01 sec)
```

**Comment by tangwz** [comment]
> we actually do not support latin1 character which codepoint greater than `0x7f`.
> In MySQL
> 
> ```sql
> mysql> select _latin1 0x80;
> +--------------+
> | _latin1 0x80 |
> +--------------+
> | €            |
> +--------------+
> 1 row in set (0.00 sec)
> ```
> 
> in tidb
> 
> ```sql
> mysql> select _latin1 0x80;
> +--------------+
> | _latin1 0x80 |
> +--------------+
> | �             |
> +--------------+
> 1 row in set (0.01 sec)
> ```

Understan. I change to use `0x61` for the unit test. You can see my new commit: `create table t (a enum(0x61, '1', '2') not null default 0x61) character set latin1`

**Comment by xiongjiwei** [comment]
what about mysql.TypeSet

**Comment by tangwz** [comment]
> what about mysql.TypeSet

I think this PR just fix `mysql.TypeEnum`. If we want to fix `TypeSet` too, we can fix it in the followup PR.

**Comment by xiongjiwei** [comment]
> If we want to fix TypeSet too, we can fix it in the followup PR.

I prefer to fix `TypeSet` in this PR and refine the PR title.

**Comment by tangwz** [comment]
> > If we want to fix TypeSet too, we can fix it in the followup PR.
> 
> I prefer to fix `TypeSet` in this PR and refine the PR title.

PTAL.

**Comment by xiongjiwei** [comment]
PR title: convert hexLit to stringLit in `enum` and `set` default value
Release note: fix cannot create enum and set column if its default value is hexLit

**Comment by xiongjiwei** [comment]
LGTM.  btw, the PR title is still incorrect

**Comment by xiongjiwei** [comment]
LGTM

**Comment by xiongjiwei** [comment]
btw, the PR title is still incorrect

**Comment by tangwz** [comment]
@tangenta PTAL.

File: ddl/db_integration_test.go [hunk 1]
```diff
@@ -2510,3 +2510,15 @@ func (s *testIntegrationSuite3) TestIssue20490(c *C) {
 
 	tk.MustQuery("select b from issue20490 order by a;").Check(testkit.Rows("1", "1", "<nil>"))
 }
+
+// TestDefaultValueIsLatin1 for issue #18977
+func (s *testIntegrationSuite3) TestDefaultValueIsLatin1(c *C) {
```
Comment (xiongjiwei) [inline ddl/db_integration_test.go:2515]: I think this bug does not affect only charset latin1 but many other charset. e.g. `utf8mb4`, can you please test it?

**Comment by tangwz** [comment]
@xiongjiwei PTAL

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by xiongjiwei** [comment]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM
