### PR TITLE
expression, types: fix unexpected result from TIME() when fsp digits > 6

### LINKED ISSUE #20995: expression: unexpected result from TIME() when fsp digits > 6
## Bug Report

It seems that TiDB will report an error when fsp digits is greater than 6, but MySQL will round it to the nearest 6-digit fsp number.

### 1. Minimal reproduce step (Required)

```sql
SELECT TIME(0.1234567);
```

### 2. What did you expect to see? (Required)
```
+-----------------+
| time(0.1234567) |
+-----------------+
| 00:00:00.123457 |
+-----------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): Invalid fsp 7
```

### 4. What is your TiDB version? (Required)

master branch

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #20995 

Problem Summary:

### What is changed and how it works?

What's Changed:
fix unexpected result from TIME() when fsp digits > 6
How it Works:
if fsp digits > 6, fsp digits is set to  `MaxFsp`.
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 
- Integration test

### Release note 

- No release note

### CODE REVIEW

File: types/fsp.go [hunk 1]
```diff
@@ -38,8 +38,10 @@ func CheckFsp(fsp int) (int8, error) {
 	if fsp == int(UnspecifiedFsp) {
 		return DefaultFsp, nil
 	}
-	if fsp < int(MinFsp) || fsp > int(MaxFsp) {
+	if fsp < int(MinFsp) {
```
Comment (XuHuaiyu) [inline types/fsp.go:41]: Have you checked all the functions which invoke CheckFsp to make sure that they are all compatible with MySQL?

Comment (TszKitLo40) [reply types/fsp.go:41]: Yes, I haven't found any compatible problems yet.

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @lzmhhh123 

tidb-test PR: https://github.com/pingcap/tidb-test/pull/1128

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
