### PR TITLE
expression: refine invalid char error msg for string conversion

### LINKED ISSUE #30444: The error msg is not same as MySQL when concat with a illegal character
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
drop table if exists t;
create table t (a char(20) charset gbk);
insert into t values ('a'), ('一二三');
select concat(a, 0x3fff) from t;
```

### 2. What did you expect to see? (Required)

```
mysql> select concat(a, 0x3fff) from t;
ERROR 3854 (HY000): Cannot convert string '?\xFF' from binary to gbk
```

### 3. What did you see instead (Required)

```
mysql> select concat(a, 0x3fff) from t;
ERROR 3854 (HY000): Cannot convert string '3FFF' from binary to gbk
```

### 4. What is your TiDB version? (Required)
```
mysql> SELECT tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0-alpha-320-g313108539
Edition: Community
Git Commit Hash: 313108539861daca0cae7e5816019a8cf3479762
Git Branch: master
UTC Build Time: 2021-12-06 10:05:51
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #30444

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by xiongjiwei — APPROVED** [review]

File: expression/builtin_convert_charset.go [hunk 1]
```diff
@@ -334,3 +337,20 @@ func isLegacyCharset(chs string) bool {
 	}
 	return false
 }
+
```
Comment (Defined2014) [inline expression/builtin_convert_charset.go:340]: Please add a test like 
``` sql
mysql> select concat(convert('a' using gbk), 0x3fff) from t;
ERROR 3854 (HY000): Cannot convert string '?\xFF' from binary to gbk
```

**Review by Defined2014 — APPROVED** [review]
