### PR TITLE
Optimizer: Fix null filtering logic for IN list

### LINKED ISSUE #49476: Unexpected Results of IN expression With NATURAL RIGHT JOIN
### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 BOOLEAN);
INSERT INTO t0 (c0) VALUES (0);

SELECT * FROM t1 NATURAL RIGHT JOIN t0; -- 0
SELECT (false IN (t1.c0, t0.c0)) FROM t1 NATURAL RIGHT JOIN t0; -- 1
SELECT * FROM t1 NATURAL RIGHT JOIN t0 WHERE (false IN (t1.c0, t0.c0));
-- Expected: 0
-- Actual: Empty set
```

### 2. What did you expect to see? (Required)

The third `SELECT` returns an empty set, which is surprising: If the result of second query is 1 (`TRUE`), the value of the `IN` expression should be `1`, and thus the third query should return `0`.

Not sure if the issue is related to https://github.com/pingcap/tidb/issues/49108

### 4. What is your TiDB version? (Required)

```
Release Version: v7.6.0-alpha
Edition: Community
Git Commit Hash: 918df0ae50568ebc54bd6d89f2d9a49bc9b79b06
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2023-12-14 04:15:47
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
```

### PR DESCRIPTION
**Pull request by ghazalfamilyusa**
### What problem does this PR solve?

Issue Number: close #49476

### Problem Summary:

Incorrect outer to inner join conversion for some cases of IN list incorrectly treated as null filtering.
An example in https://github.com/pingcap/tidb/issues/49476 

CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 BOOLEAN);
INSERT INTO t0 (c0) VALUES (0);

SELECT * FROM t1 NATURAL RIGHT JOIN t0; -- 0
SELECT (false IN (t1.c0, t0.c0)) FROM t1 NATURAL RIGHT JOIN t0; -- 1
SELECT * FROM t1 NATURAL RIGHT JOIN t0 WHERE (false IN (t1.c0, t0.c0));
-- Expected: 0
-- Actual: Empty set

The problem is in the constant folding logic when it is used to evaluate null rejection logic.
The logic is risky and just fills in constant 1 for non-inner side. In the example above the IN list becomes 
false in (null,1) which is false (null filter is true). 

### What changed and how does it work?
Fix done at the top level code for null filtering logic used in outer to inner. The fix use the OR logic instead of IN list.
For example, alse IN (t1.c0, t0.c0)) is checked for nullability using (false = t1.c0) or (false = t0.c0) which is not null filter. 
Also, this PR consolidates the null rejection code from outer to inner code and the general utility code. This includes cleans up of previous special cases.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

**Comment by winoros** [comment]
I got the idea!

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/util/null_misc.go [hunk 1]
```diff
@@ -18,76 +18,98 @@ import (
...
 	return false
 }
 
-// isNullRejectedSpecially handles some null-rejected cases specially, since the current in
-// EvaluateExprWithNull is too strict for some cases, e.g. #49616.
-func isNullRejectedSpecially(ctx context.PlanContext, schema *expression.Schema, expr expression.Expression) bool {
-	return specialNullRejectedCase1(ctx, schema, expr) // only 1 case now
+// isNullRejectedInList checks null filter for IN list using OR logic.
+// Reason is that null filtering through evaluation by isNullRejectedSimpleExpr
+// has problems with IN list.
```
Comment (qw4990) [inline pkg/planner/util/null_misc.go:45]: Better to add a case here to explain why we have to treat IN-LIST as OR here. The rest LGTM!

Comment (qw4990) [reply pkg/planner/util/null_misc.go:45]: So if the in-list contains a column from the non-inner side, then it can never pass the NF check.

File: pkg/planner/util/null_misc.go [hunk 2]
```diff
@@ -18,76 +18,98 @@ import (
...
+	default:
+		return isNullRejectedSimpleExpr(ctx, innerSchema, predicate)
 	}
-	orFunc := isFunc(expr, ast.LogicOr)
-	if orFunc == nil {
+}
+
+// isNullRejectedSimpleExpr check whether a condition is null-rejected
+// A condition would be null-rejected in one of following cases:
+// If it is a predicate containing a reference to an inner table that evaluates to UNKNOWN or FALSE
```
Comment (AilinKid) [inline pkg/planner/util/null_misc.go:97]: i think the comment should be refined as well, "inner table" has no ideas with

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

**Review by AilinKid — APPROVED** [review]

File: pkg/planner/util/null_misc.go (hunk 1 above)
Comment (ghazalfamilyusa) [reply pkg/planner/util/null_misc.go:45]: The explanation for this case is shown above and in the issue. I guess you guys think it is better to add it in the code. Added that to the comment.

File: pkg/planner/util/null_misc.go (hunk 2 above)
Comment (ghazalfamilyusa) [reply pkg/planner/util/null_misc.go:97]: added explanation to inner table as "null producing side"
