### PR TITLE
datum: check len(s) before calculating and checking runeCount

### LINKED ISSUE #53942: Save unnecessary `RuneCountInString`
## Enhancement
`RuneCountInString` can be unexpectedly time-consuming for certain workloads. Since the number of runes must be smaller than or equal to the length of the string, we can fast check the length first. Only calculate the number of runes when necessary.
image

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #53942

Problem Summary:

`RuneCountInString` can be unexpectedly time-consuming for certain workloads. Since the number of runes must be smaller than or equal to the length of the string, we can fast check the length first. Only calculate the number of runes when necessary.

Before:
```
go test -run=^$ -bench=BenchmarkInsertIntoSelect -benchmem -benchtime=100x
     100	 136332696 ns/op	106229159 B/op	  507278 allocs/op
```

This PR:
```
go test -run=^$ -bench=BenchmarkInsertIntoSelect -benchmem -benchtime=100x
     100	 123812334 ns/op	106041608 B/op	  506652 allocs/op
```

### Check List

Tests 

- [x] Unit test: already covered by existing cases and benchmarks
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/types/datum.go [hunk 1]
```diff
@@ -1157,9 +1162,15 @@ func ProduceStrWithSpecifiedTp(s string, tp *FieldType, ctx Context, padZero boo
 			trimed := strings.TrimRight(overflowed, " \t\n\r")
 			if len(trimed) == 0 && !IsBinaryStr(tp) && IsTypeChar(tp.GetType()) {
 				if tp.GetType() == mysql.TypeVarchar {
+					if needRecalculateLen {
```
Comment (cfzjywxk) [inline pkg/types/datum.go:1165]: Maybe
```
if !LenCalculated {
   ...
}
```
is better as the `characterLen` is not set in the short path.

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by zyguan — APPROVED** [review]
