### PR TITLE
resourcegroup/runaway: switch watch syncer to time-based cursor

### LINKED ISSUE #67754: runaway watch syncer can permanently miss new watches under multi-TiDB AUTO_ID_CACHE
### 1. Minimal reproduce step (Required)

On a cluster with 2 or more TiDB nodes (TiUP Playground is enough):

1. Start the cluster and exercise any path that causes a handful of `QUERY WATCH ADD` inserts into `mysql.tidb_runaway_watch` (e.g. create a resource group, add a few seed watches; or let an auto-quarantine fire a few times). This advances the watch syncer's `watch` checkpoint into one TiDB instance's `AUTO_ID_CACHE` segment.
2. From a client connected to one TiDB node, bulk-issue `QUERY WATCH ADD RESOURCE GROUP rg_bulk ACTION KILL SQL TEXT EXACT TO '...'` ~300 times against the same resource group.
3. Wait more than 20 seconds (≫ `watchSyncInterval = 1s`).
4. Compare the persisted state with the in-memory view:

```sql
SELECT COUNT(*) FROM mysql.tidb_runaway_watch           WHERE resource_group_name='rg_bulk';
SELECT COUNT(*) FROM information_schema.runaway_watches WHERE resource_group_name='rg_bulk';
SELECT MIN(id), MAX(id) FROM mysql.tidb_runaway_watch   WHERE resource_group_name='rg_bulk';
```

and on both TiDB nodes' status ports:

```
curl -s http://<tidb>:<status_port>/metrics | grep runaway_syncer
```

### 2. What did you expect to see? (Required)

All 300 new watches propagate into every TiDB node's in-memory `RunawayManager.watchList` within a few syncer ticks, i.e. `information_schema.runaway_watches` on every node should report 300 rows for `rg_bulk` and the `KILL` action should be enforced cluster-wide.

### 3. What did you see instead (Required)

- `mysql.tidb_runaway_watch` contains 300 rows for `rg_bulk` — persisted correctly.
- `information_schema.runaway_watches` returns **0** for `rg_bulk` on every TiDB node (including the node that received the `QUERY WATCH ADD` statements), and stays at 0 indefinitely.
- The watches never take effect — the `KILL` action is not enforced.
- `tidb_server_runaway_syncer_checkpoint{type="watch"}` is **stuck** at a value strictly greater than `MAX(id)` of the newly inserted rows (sampled value `60001` while the new rows' id range was `[30005, 30304]`, observed unchanged across 10 consecutive 2-second samples on both nodes).
- `tidb_server_runaway_syncer_total{result="ok",type="sync"}` increments normally (once per second per node); `tidb_server_runaway_syncer_total{result="error",type="sync"}` stays at 0.
- `tidb.log` on both nodes contains no warn/error/panic related to runaway watch.

i.e. the syncer looks completely healthy by every external signal, but the rows are never loaded.

### 4. What is your TiDB version? (Required)

```
Release Version: v8.5.5-20260403-6c7aaa0
Edition:         Community
Git Commit Hash: 6c7aaa0c8d548cdfaa2c99e216337752de48009f
Git Branch:      release-8.5-20260323-v8.5.5
```

Code path inspection suggests `master` and all currently-shipping release branches that use the id-cursor watch syncer are affected; only verified on `release-8.5` at the commit above.

---

## Root cause

The watch syncer at `pkg/resourcegroup/runaway/syncer.go` uses a monotonically-advancing `id` cursor:

```go
// simplified
SELECT * FROM mysql.tidb_runaway_watch WHERE id > ? ORDER BY id LIMIT 256
...
if push && len(rs) > 0 {
    reader.CheckPoint = rs[len(rs)-1].GetInt64(0)
}
```

This assumes `mysql.tidb_runaway_watch.id` (`BIGINT AUTO_INCREMENT PRIMARY KEY`) is **globally monotonically increasing** across all inserts. That assumption does not hold in a multi-TiDB deployment.

With TiDB's default `AUTO_ID_CACHE` (30000), each TiDB instance reserves a disjoint id range from the id allocator. Different instances — and the same instance across restarts — consume different ranges independently, so a later insert on one node can be assigned an id numerically **smaller** than an earlier insert on another node.

Once the syncer checkpoint has advanced into one node's high range (e.g. `60001`), any subsequent `QUERY WATCH ADD` whose id falls in a lower segment (e.g. `30005–30304`) is permanently filtered out by `id > 60001`. Because `len(rs) == 0` on every subsequent tick:

- `result="ok"` counter still ticks (the `SELECT` itself succeeds);
- `result="error"` stays 0;
- the normal path has no INFO-level log, so nothing is emitted;
- `rm.AddWatch` is never called, so `watchList` on every node never receives those rows.

This is indistinguishable from a correctly-functioning syncer via metrics and logs unless one knows to compare `syncer_checkpoint{type="watch"}` against `MAX(id)` in the system table.

## Impact

- `QUERY WATCH ADD` can become silently ineffective cluster-wide, with no signal from any external health channel (metrics, logs).
- Cross-node watch propagation loses its durability guarantee whenever auto-id cache segment ordering does not match insert ordering — which is a race condition inherent to multi-TiDB deployments, not an edge case.
- Because `information_schema.runaway_watches` reads from the in-memory `RunawayManager.watchList` (see `setDataFromRunawayWatches` in `pkg/executor/infoschema_reader.go`), operators cannot detect the divergence from SQL either.

## Suggested fix

Two directions, either one resolves it. **Direction 1 is preferred.**

**Direction 1 — switch the syncer cursor from `id` to `start_time`.**
`#67352` has already added `idx_start_time` on `mysql.tidb_runaway_watch` and `idx_done_time` on `mysql.tidb_runaway_watch_done`. Using `start_time` as the cursor:

- aligns with those new indexes (presumably their intended consumer),
- uses a value assigned by TiDB itself (`time.Now()`) at watch creation, so it is effectively monotonic per node and close-to-monotonic globally (bounded by NTP / TSO skew),
- admits a small overlap tolerance (`WHERE start_time >= checkpoint - epsilon`) plus client-side dedup to survive residual clock skew, and
- leaves `id` free to keep its `AUTO_ID_CACHE` performance properties.

**Direction 2 — force `AUTO_ID_CACHE 1` on the two system tables.**
Modify the bootstrap / upgrade DDL for `mysql.tidb_runaway_watch` and `mysql.tidb_runaway_watch_done` to use `AUTO_ID_CACHE 1`, restoring globally monotonic id allocation at the cost of a PD round-trip per insert. Smallest change, but measurably worse throughput for `QUERY WATCH ADD`.

## Related latent issue (same file)

While auditing the syncer, a separate non-blocking bug surfaced in `getRunawayWatchRecord`:

```go
for _, r := range rs {
    if err := r.GetTime(2).GoTime(...); err != nil { continue } // silently drop
    ...
    ret = append(ret, qr)
}
if push && len(rs) > 0 {
    reader.CheckPoint = rs[len(rs)-1].GetInt64(0) // advances based on rs, not ret
}
```

combined with the outer `if len(records) < watchSyncBatchLimit { break }`: a batch where every row fails time parsing would silently advance the cursor past the tail and abandon those rows with zero signal. Not the trigger for the bug reported above (that case has empty `rs`, not "populated `rs` + all-parse-failures"), but the asymmetry is latent and worth fixing in the same PR.

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #67754

Problem Summary:

The runaway watch syncer paginates `mysql.tidb_runaway_watch(_done)` by `id`. In a multi-TiDB cluster, `AUTO_ID_CACHE` hands each TiDB instance a disjoint auto-id range, so a newer row can have an `id` smaller than another instance's cursor and be permanently skipped.

### What changed and how does it work?

- Replace the `id` cursor with a time cursor (`start_time` / `done_time`). Each sync scans the half-open window `[CheckPoint, UpperBound)` where `UpperBound = time.Now().UTC()` is captured before the read.
- Cap each scan at `LIMIT 2048` to bound memory on the first scan from `NullTime` (and after long pauses). On a full batch, `CheckPoint` advances to the last row's key-column time so the next 1-second cycle resumes from there; `AddWatch` / `removeWatch` de-duplicate at the `>=` boundary.
- On a partial batch, `CheckPoint` advances to `UpperBound - 3s` so rows whose commit-TS becomes visible slightly later are still re-inspected on the next cycle.
- Guard against livelock when a full batch shares one microsecond-precision timestamp: fall back to `UpperBound - 3s`. A `TODO` documents the (currently non-realistic) row-skip trade-off of this fallback.
- Skip the historical `watch_done` full-table scan on the first sync by seeding `deletionWatchReader.CheckPoint` from the watch reader's `UpperBound - 3s`. Rows that move from `watch` to `watch_done` during the first sync are covered by the overlap window.
- Isolate point-query paths (`getWatchRecordByID`, `getWatchRecordByGroup`) from sync-cursor state: `readQuarantineRecords` no longer mutates `lastScanKeyTime`. Only `scanNewRecordsInRange` advances the cursor, so manual `RemoveRunawayWatch` calls cannot perturb checkpoint advancement.
- Extract `decodeQuarantineRecord` as a pure helper and drive decoding with per-table column-index maps (`quarantineColumns`), so the two tables' differing column layouts don't leak into the decode logic.
- Align the `tidb_server_runaway_syncer_checkpoint` metric + Grafana panel with time-based semantics (Unix ms), and return `0` when the checkpoint is still `time.Time{}` to avoid the `-62135596800000` Y-axis spike.

> **Note on NextGen:** The metric/Grafana panel changes in this PR do **not** exist on the NextGen branch, so no corresponding NextGen panel changes are required — the NextGen branch is intentionally left untouched for this PR.

### Check List

Tests 

- [x] Unit test
- [x] Manual test (add detailed scripts or steps below)

Manual verification:

Cluster: TiUP playground with two TiDB nodes (A and B), default `AUTO_ID_CACHE`. Base `v8.5.5` is booted first, then upgraded in place to this PR's `tidb-server`.

End-to-end upgrade suite

- Boot `v8.5.5` cleanly; before upgrade, create the test database, tables, two resource groups, and three seed watches.
- After upgrade, `mysql.tidb` `schema_version` reaches the expected value and both new runaway indexes exist; restarting on the new binary keeps `schema_version` unchanged (no double-migration).
- `QUERY WATCH ADD` issued on A appears on B within one sync cycle; `QUERY WATCH REMOVE <id>` issued on A is also gone from B.
- A SQL matching a seed watch (created before upgrade) is still killed with error `8254` after upgrade.
- `ALTER RESOURCE GROUP ... QUERY_LIMIT = ()` clears the runaway rules but does **not** delete pre-existing watches; the existing watch keeps killing matching SQL.
- A slow query is auto-identified, automatically promoted to a watch, propagates to B and starts quarantining matching SQL there, then expires when its TTL is up.
- Hitting the same watch many times collapses to a single row in `mysql.tidb_runaway_queries` with `repeats ≥ 3`, instead of one row per hit.
- Bulk-add several hundred watches; both nodes' caches see all of them. Then bulk `QUERY WATCH REMOVE` all of them; both nodes' `mysql.tidb_runaway_watch_done` catches up and the live cache drains to 0.
- One `QUERY WATCH ADD` with a unique text bumps `information_schema.runaway_watches` by exactly `+1` on each node (no double-count, no miss).
- Scrape Prometheus on both nodes; every runaway syncer / flusher metric family exists and was actually incremented during the run.
- A short burst of watches makes the flusher fire at least once with zero increase on its error counter.
- No `FATAL` / `panic` / `runaway flush error` lines in either TiDB log, and the bulk-insert table behind the test resource group is fully drained on disk.

Concurrency / pagination stress

- Insert a row on A and immediately `SELECT` it on B as a storage commit-to-visible latency baseline; this is **not** the cache-propagation metric (see the dedicated cache-latency case below).
- Many concurrent `QUERY WATCH ADD` calls from both nodes with all-unique keys. Both nodes end up with the same set of watch IDs, zero drops, zero duplicates.
- Concurrent ADDs that intentionally include duplicate watch names. Storage transiently shows more rows than distinct names (confirming no insert-time dedup), then the `staleQuarantineRecord` cleanup pipeline converges back to one row per name within the documented ≤ 5 s budget.
- A adds watches while B removes them concurrently; final `tidb_runaway_watch_done` row counts match on both nodes, with zero orphan `record_id` and zero duplicate done rows.
- Pre-seed a batch of watches, then mass-`REMOVE` from both nodes with intentional overlap. The benign "no runaway watch" return is classified separately from real failures; both nodes' `watch_done` reaches the expected count.
- After the chaos above, `watch` and `watch_done` row counts on A equal those on B.
- Cache-propagation latency, end to end: time from `QUERY WATCH ADD` on A until a matching SQL on B is actually killed with error `8254`.
- Burst-insert hundreds of watches that share the **same** microsecond `start_time`. All of them must end up enforced on B — directly proves the new time cursor doesn't drop rows whose timestamps collide.
- On an empty cluster, insert thousands of watches in one go, more than two pages of the syncer's per-scan `LIMIT 2048`. Both nodes' caches must converge to the full set, and SQL probes at the first row, both page boundaries, and the last row are all killed.
- Same scale on the REMOVE side: thousands of `QUERY WATCH REMOVE` calls land in `tidb_runaway_watch_done` on both nodes with zero orphans and zero duplicate done rows.

Key invariants observed

- Under default `AUTO_ID_CACHE`, a watch created on A is enforced on B (error `8254`) within roughly the `1 s` sync cycle, and a `watch → watch_done` migration is removed from the peer's cache with no leftover entry.
- The `tidb_server_runaway_syncer_checkpoint` Grafana panel now reports a Unix ms value, returning `0` before any sync runs — the Y-axis no longer spikes to `-62135596800000`.

image

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix an issue where a runaway watch created on one TiDB instance could permanently fail to propagate to other TiDB instances in a cluster that uses the default `AUTO_ID_CACHE`, because the runaway watch syncer paginated `mysql.tidb_runaway_watch` / `mysql.tidb_runaway_watch_done` by an auto-increment id whose ranges are disjoint across instances.
```

### CODE REVIEW

**Comment by JmPotato** [comment]
Pushed f73ff6b addressing the four CodeRabbit findings. Summary of decisions:

**[#1, Critical — `manager.go:449-474` infinite-loop on full boundary-dedup'd batch]** — Won't fix.
The original guard was removed in f76e2906fd with the rationale that the stall precondition (`watchSyncBatchLimit` rows sharing a single microsecond `start_time` / `done_time`) is unreachable: timestamps come from `time.Now()` per record, so `>=256` rows at the same microsecond implies `~256M` inserts/sec on `mysql.tidb_runaway_watch`, which the storage layer cannot sustain. Re-adding the guard to defend against this path inflates reviewable surface area for no observable benefit, so we prefer to keep `doSync` minimal and rely on the `rawCount < watchSyncBatchLimit` break.

**[#2, Major — `syncer.go:89-95` clock-skew comment]** — Addressed, but by deleting the whole Limitations block rather than rewording it. Same rationale as #1: both items (clock skew, same-microsecond saturation) describe practically-impossible states, and documenting them didn't pay for itself.

**[#3, Major — `syncer.go:165` boundary dedup pollutes ad-hoc lookups]** — Fixed. `processWatchRows` / `processWatchDoneRows` now guard the `seenAtBoundary` check and the `trackBoundary` bookkeeping behind `if push`, so `getWatchRecordByID` / `getWatchRecordByGroup` (both `push=false`) return rows even when the id has already been emitted by the sync loop, and they perform no state mutation. Added `TestProcessWatchRowsNonPushBypassesBoundaryDedup` to pin the invariant for both watch and watch_done variants.

**[#4, Major — `syncer.go:190-215` partial parse advances cursor]** — Won't fix.
`mysql.tidb_runaway_watch(_done)` is written exclusively by TiDB's own insert path with strict column validation; a row whose cursor column parses but whose `end_time` / `start_time` does not would only occur under storage-level corruption. Deferring `trackBoundary` until after full parse makes that case louder (the cursor stalls) but introduces a real regression mode — every subsequent syncer tick would refetch and re-fail on the same bad row, blocking propagation of genuinely-new watches on all other instances until an operator intervenes. The current behavior (advance past corrupt rows) degrades gracefully; adding a log for the partial-parse path would be observability for a code path that cannot be reached, so we're leaving it out.

File: pkg/resourcegroup/runaway/syncer.go [hunk 1]
```diff
@@ -178,8 +177,12 @@ func getRunawayWatchRecord(sysSessionPool util.SessionPool, reader *systemTableR
...
 		ret = append(ret, qr)
 	}
-	if push && len(rs) > 0 {
-		reader.CheckPoint = rs[len(rs)-1].GetInt64(0)
+	// If at leaset one record is found from the current checkpoint with push enabled,
+	// advance the checkpoint to now to ensure the next scan will get the latest records.
+	// Add a negative offset to leave some buffer for slower TiDB instances that may write
+	// records after the checkpoint has advanced.
+	if push && len(ret) > 0 {
+		reader.CheckPoint = now.Add(-3 * watchSyncInterval)
```
Comment (rleungx) [inline pkg/resourcegroup/runaway/syncer.go]: What if the query is executed slowly (>3s)? Will the record be lost?

File: pkg/resourcegroup/runaway/syncer.go [hunk 2]
```diff
@@ -261,10 +333,11 @@ func (r *systemTableReader) genSelectStmt() (string, []any) {
 	builder.WriteString(r.TableName)
 	builder.WriteString(" where ")
 	builder.WriteString(r.KeyCol)
-	builder.WriteString(" > %? order by ")
+	builder.WriteString(" >= %? and ")
+	builder.WriteString(r.KeyCol)
+	builder.WriteString(" < %? order by ")
 	builder.WriteString(r.KeyCol)
-	builder.WriteString(" limit %?")
```
Comment (YuhaoZhang00) [inline pkg/resourcegroup/runaway/syncer.go:266]: `LIMIT` is dropped, meaning the materialized result size is only bounded by the `[CheckPoint, UpperBound)` window width. Whenever CheckPoint lags far behind wall-clock (fresh syncer, restart, long pause), one scan pulls the entire lag window into memory at once. Worth a safety LIMIT?

Comment (JmPotato) [reply pkg/resourcegroup/runaway/syncer.go:266]: Yes, this is a known regression in the current PR.

After evaluation, the only significant risk appears to be the `watch_done` system table. Since it currently lacks a GC mechanism for data, it will grow indefinitely.

I have already opened a separate issue for this problem, which can be handled independently after this PR. https://github.com/pingcap/tidb/issues/67772

File: pkg/metrics/grafana/tidb_resource_control.json [hunk 3]
```diff
@@ -3414,7 +3414,7 @@
                "dashes": false,
                "datasource": "${DS_TEST-CLUSTER}",
                "decimals": 0,
-               "description": "The current checkpoint (last synced record ID) of runaway syncer for watch and watch_done tables.",
+               "description": "The current lower-bound checkpoint of runaway syncer, expressed as Unix milliseconds of the next scan window for start_time (watch) or done_time (watch_done). A value of 0 means no checkpoint has been established yet.",
```
Comment (rleungx) [inline pkg/metrics/grafana/tidb_resource_control.json:3417]: Do we also need to change .jsonnet?

File: pkg/resourcegroup/runaway/syncer.go [hunk 4]
```diff
@@ -122,112 +216,90 @@ func (s *syncer) checkTableExist(tableName ast.CIStr) bool {
...
+// the paginated scan in genSelectStmt.
 type systemTableReader struct {
-	TableName  string
-	KeyCol     string
-	CheckPoint int64
+	TableName     string
+	KeyCol        string
+	RecordColumns quarantineColumns
+	CheckPoint    time.Time
+	UpperBound    time.Time
```
Comment (YuhaoZhang00) [inline pkg/resourcegroup/runaway/syncer.go:334]: Style nit (non-blocking):  `UpperBound` is per-call state, it's set and consumed within one `scanNewRecordsInRange` call, only living on the struct so the zero-arg `genSelectStmt` method can read it.

Consider a local variable in `scanNewRecordsInRange` passed as a parameter to `genSelectStmt`.

File: pkg/resourcegroup/runaway/manager.go [hunk 5]
```diff
@@ -427,42 +427,58 @@ func (rm *Manager) UpdateNewAndDoneWatch() error {
...
+	// On the first sync (startup), skip the historical watch_done full-table
+	// scan. The in-memory watch list was empty before loading from the watch
+	// table above, and records already moved to watch_done are absent from the
+	// watch table (handleRunawayWatchDone moves them atomically in a single
+	// transaction), so scanning historical watch_done rows would only produce
+	// no-op removeWatch calls. The overlap window covers concurrent moves that
+	// commit between the watch snapshot and the done scan.
+	if rm.runawaySyncer.deletionWatchReader.CheckPoint.Equal(NullTime) {
+		rm.runawaySyncer.deletionWatchReader.CheckPoint =
+			rm.runawaySyncer.newWatchReader.UpperBound.Add(-watchSyncOverlap)
```
Comment (YuhaoZhang00) [inline pkg/resourcegroup/runaway/manager.go:467]: why not using `rm.runawaySyncer.newWatchReader.CheckPoint` since `Upperbound = Checkpoint + watchSyncOverlap`?

Comment (JmPotato) [reply pkg/resourcegroup/runaway/manager.go:467]: The primary reason is to provide a bit of a buffer to account for any insertion operations that might occur during startup. This ensures the system can read those newly inserted results.

Whether this is actually necessary is certainly debatable, but I don't think it would be a problem if we didn't have that extra margin.

File: pkg/resourcegroup/runaway/syncer.go [hunk 6]
```diff
@@ -38,8 +38,20 @@ const (
...
-	// watchSyncBatchLimit is the max number of rows fetched per sync query.
-	watchSyncBatchLimit = 256
+	// watchSyncOverlap is how far back CheckPoint rewinds from the captured
+	// UpperBound after a non-empty scan, so the next scan re-inspects the
+	// tail of the previous window. It budgets the lag between "now" on this
+	// syncer node and the moment a row with `start_time ≈ now` becomes
+	// visible to a subsequent snapshot read (commit/read-TS delay and
+	// wall-clock skew). De-duplication across the overlap is handled by
+	// `AddWatch` in memory.
+	watchSyncOverlap = 3 * watchSyncInterval
```
Comment (rleungx) [inline pkg/resourcegroup/runaway/syncer.go:46]: Is 3s enough?

Comment (JmPotato) [reply pkg/resourcegroup/runaway/syncer.go:46]: This value is an empirical number with no explanatory comments in the original code. Since we haven't conducted systematic testing to determine the specific optimal setting, I believe we should keep the original value for now.

We can reconsider adjusting it—either increasing or decreasing it—if we encounter real-world scenarios where it actually causes issues.

File: pkg/resourcegroup/runaway/manager.go [hunk 7]
```diff
@@ -427,42 +427,58 @@ func (rm *Manager) UpdateNewAndDoneWatch() error {
...
+	}
+	return float64(checkpoint.UnixMilli())
+}
+
 // doSync performs the actual sync work for watch and watch_done tables.
 func (rm *Manager) doSync() error {
 	if !rm.runawaySyncer.checkWatchTableExist() {
 		return nil
 	}
-	for {
```
Comment (YuhaoZhang00) [inline pkg/resourcegroup/runaway/manager.go:440]: Removing the `for{}` loop means that the new `doSync` only syncs one batch (2048 records) per cycle (1s). In cold-start scenario, draining `N` backlogged rows now takes `N/2048` seconds. Please validate if this performance regression is acceptable.

Comment (JmPotato) [reply pkg/resourcegroup/runaway/manager.go:440]: Initially, I implemented a for loop. However, once I saw the `maxWatchListCap=10000` parameter, I realized that in the worst-case scenario, catching up with all the records would only take about five seconds.

Instead of using a for loop within a single tick to execute a potentially blocking task, I believe it would be much simpler to spread the workload across time slices. This approach makes the entire process smoother and avoids any potential blocking issues.

File: pkg/resourcegroup/runaway/manager.go (hunk 5 above)
Comment (YuhaoZhang00) [reply pkg/resourcegroup/runaway/manager.go:467]: I agree. The "UpperBound" variable kinda acts as a snapshot (of the timestamp before insertion operations) here.

**Review by YuhaoZhang00 — APPROVED** [review]

File: pkg/resourcegroup/runaway/syncer.go [hunk 8]
```diff
@@ -122,115 +224,174 @@ func (s *syncer) checkTableExist(tableName ast.CIStr) bool {
...
+		// resumes from there (with `>=`, the boundary row will be re-read
+		// and de-duplicated).
+		//
+		// If lastScanKeyTime is not strictly after CheckPoint, all rows in
+		// the batch share the same key-column timestamp (microsecond-
+		// precision collision on insert). Fall through to the UpperBound-
+		// based advancement to avoid a livelock that re-reads the same page
+		// every cycle.
+		//
+		// TODO: this same-key fallback can silently skip rows whose key is
```
Comment (rleungx) [inline pkg/resourcegroup/runaway/syncer.go]: It seems that we still have a possibility of losing the record?

Comment (JmPotato) [reply pkg/resourcegroup/runaway/syncer.go]: On the same-timestamp fallback in `scanNewRecordsInRange`: I think the probability of actually hitting it in production is essentially zero.

**Timestamp source.** Both `start_time` and `done_time` come from per-row `time.Now()` captured in Go (`manager.go:263` for quarantine, `record.go:182` for done), never from a server-side `NOW(6)` shared across a batch. Schema precision is `DATETIME(6)` / `TIMESTAMP(6)` = 1 µs.

**Collision rate.** Triggering the fallback requires ≥2048 records sharing the exact same microsecond. Per-node insert throughput is bounded by `quarantineChan` (1024 buffer) + 1s flush ≈ 1k/s/node. Even a 100-node cluster bursting at ~10⁵ rows/s spreads over 10⁶ µs buckets — expected ~0.1 row/µs. Hitting 2048 in one µs would require a sustained ~2×10⁹ rows/s, which isn't physically reachable. Cross-node clock skew makes it less likely still.

**Even if it fires, loss requires a second condition.** When the fallback advances `CheckPoint` to `UpperBound - watchSyncOverlap`, any colliding-µs `T` within the 3s overlap window is still re-read on the next tick (and de-duped by `recordKey` in `AddWatch`/`removeWatch`). Loss only happens if `T < UpperBound - 3s`, which in practice means someone manually ran `INSERT ... SELECT ..., NOW(6) FROM ...` against `mysql.tidb_runaway_watch` to backfill thousands of rows at once — an operator action outside the product's own write paths.

Given the existing `TODO` already documents this as an accepted trade-off, I'd prefer to keep the current shape. The cleaner fix (composite `(time, id)` cursor with `ORDER BY start_time, id`) would touch all read paths and tests for a scenario that can't arise organically.

**Review by XuHuaiyu — APPROVED** [review]
The metrics part modification LGTM

**Review by rleungx — APPROVED** [review]

File: pkg/resourcegroup/runaway/syncer.go [hunk 9]
```diff
@@ -116,159 +201,184 @@ func (s *syncer) checkTableExist(tableName ast.CIStr) bool {
...
+		} else {
+			reader.CheckPoint = reader.UpperBound.Add(-watchSyncOverlap)
 		}
-		ret = append(ret, qr)
+	case len(records) > 0:
+		reader.CheckPoint = reader.UpperBound.Add(-watchSyncOverlap)
 	}
-	if push && len(rs) > 0 {
-		reader.CheckPoint = rs[len(rs)-1].GetInt64(0)
+	return records, nil
```
[the remark this answers is not in the document]
Comment (JmPotato) [reply pkg/resourcegroup/runaway/syncer.go:272]: This can't actually happen in either table:

- `tidb_runaway_watch`: `KeyColIdx == watchColStartTime == watchRecordColumns.StartTime`. `decodeQuarantineRecord` already validates the same column via the same `r.GetTime(cols.StartTime).GoTime(time.UTC)` call, so if the decode succeeds the key-col parse cannot fail. They're the identical call on the identical column.
- `tidb_runaway_watch_done`: `done_time` is written by TiDB itself in `handleRunawayWatchDone` using `time.Now()`, and the column is `NOT NULL` per DDL. Making `GoTime()` fail would require on-disk corruption, which is outside the threat model for this syncer.

Even in the hypothetical stale case, the existing `reader.lastScanKeyTime.After(reader.CheckPoint)` guard absorbs it: a previous full-batch already advanced `CheckPoint` to that stale `lastScanKeyTime`, so `After` returns `false` and we fall back to `UpperBound - overlap`. Resetting at the top would add noise for a path we can't reach — skipping the defensive reset to keep the invariant readable.

File: pkg/resourcegroup/runaway/syncer.go [hunk 10]
```diff
@@ -116,159 +201,184 @@ func (s *syncer) checkTableExist(tableName ast.CIStr) bool {
...
+// reader scan state — only scanNewRecordsInRange advances the sync cursor.
+func (s *syncer) readQuarantineRecords(
+	reader *systemTableReader,
+	genFn sqlGenFn,
+) ([]*QuarantineRecord, error) {
+	sql, params := genFn()
+	rows, err := ExecRCRestrictedSQL(s.sysSessionPool, sql, params)
+	if err != nil {
+		return nil, err
+	}
```
[the remark this answers is not in the document]
Comment (JmPotato) [reply pkg/resourcegroup/runaway/syncer.go:285]: Same conclusion as the sibling thread: the key-col parse cannot fail independently of `decodeQuarantineRecord` in practice.

- `tidb_runaway_watch`: `KeyColIdx` is `watchColStartTime`, which is literally the same column `decodeQuarantineRecord` already parsed via `r.GetTime(cols.StartTime).GoTime(time.UTC)`. A second call on the same column can't diverge.
- `tidb_runaway_watch_done`: `done_time` is written by TiDB itself (`handleRunawayWatchDone` with `time.Now()`) and is `NOT NULL` per DDL. A parse failure would require data corruption, not a code path we need to guard.

Treating a theoretically-unreachable key-col parse failure as "skip the row" would add a branch (and a test case) for a condition that can't happen given the invariants above, so I'd rather keep the code reading straight-through.
