### PR TITLE
planner: fix the wrong cost formula for MPP net cost

### LINKED ISSUE #30103: The formula of calculating net cost for TiFlash plans is not aligned with TiKV plans'
## Enhancement
In `copTask.convertToRootTaskImpl`, we can see the formula of calculating net cost for TiKV plans is `est-row * row-size * net-factor`, while in `mppTask.convertToRootTaskImpl` the formula for TiFlash plans is `est-row * net-factor` where the `row-size` is lost.
That would let the cost of TiFlash plans be always relatively lower than TiKV plans', which can cause some wrong plans.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #30103

Problem Summary: planner: fix the wrong cost formula for MPP net cost

### What is changed and how it works?

The original MPP net cost formula doesn't consider `rowSize/rowWidth`, this PR fixes it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
planner: fix the wrong cost formula for MPP net cost
```

### CODE REVIEW

File: planner/core/task.go [hunk 1]
```diff
@@ -2374,15 +2386,17 @@ func (t *mppTask) convertToRootTaskImpl(ctx sessionctx.Context) *rootTask {
...
+	rowSize := math.Max(collectRowSizeFromMPPPlan(t.p), 1) // use 1 as lower-bound for safety
 
-	cst := t.cst + t.count()*ctx.GetSessionVars().GetNetworkFactor(nil)
-	p.cost = cst / p.ctx.GetSessionVars().CopTiFlashConcurrencyFactor
+	cst := t.cst + t.count()*rowSize*ctx.GetSessionVars().GetNetworkFactor(nil)
+	cst /= p.ctx.GetSessionVars().CopTiFlashConcurrencyFactor
+	p.cost = cst
 	if p.ctx.GetSessionVars().IsMPPEnforced() {
-		p.cost = cst / 1000000000
+		cst /= 1000000000
```
Comment (Reminiscent) [inline planner/core/task.go:2395]: Should the `p.cost /= 1000000000` at the same time(like the previous)?

**Review by Reminiscent — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]

File: planner/core/task.go (hunk 1 above)
Comment (qw4990) [reply planner/core/task.go:2390]: I think we don't need to change `p.cost` here since `cst` is the one that used to be compared with other plan costs so we have to change it to make the planner choose this plan.
Keeping `p.cost` unchanged here can let us know the real cost of the plan when using `explain format=verbose`, and the new test `TestRowSizeInMPP` relies on this.
