### PR TITLE
br: fix pitr with filter drop db issue and adjust tests

### LINKED ISSUE #62486: br: add table filter to current int test
## Enhancement

For existing pitr test in the repo, we could add a table filter to it and test to enhance the test cases

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #62486 #62528

Problem Summary:

### What changed and how does it work?

Add a isRefreshMeta field in DDL schema diff. For table drop, if initiated by refreshMeta, don't check TiKV for old tableInfo as it doesn't make sense to BR case, and it will error out due to DB key not existed.
 
Add table filter to `br_pitr` int test
remove a few tests from `br_table_filter` as it has been tested in the comprehensive DDL tests. Removing those to reduce the test running time on CI
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

File: pkg/meta/model/job.go [hunk 1]
```diff
@@ -1129,6 +1129,8 @@ type SchemaDiff struct {
 	// ReadTableFromMeta is set to avoid the diff is too large to be saved in SchemaDiff.
 	// infoschema should read latest meta directly.
 	ReadTableFromMeta bool `json:"read_table_from_meta,omitempty"`
+	// IsRefreshMeta is set to true only when this diff is initiated by refreshMeta DDL that's only used by BR
+	IsRefreshMeta bool `json:"is_refresh_meta,omitempty"`
```
Comment (D3Hunter) [inline pkg/meta/model/job.go]:
```suggestion
	IsRefreshMeta bool `json:"-"`
```
it shouldn't be stored

Comment (Tristan1900) [reply pkg/meta/model/job.go]: you are right! good catch

**Comment by D3Hunter** [comment]
/approve

ddl part lgtm

**Review by 3pointer — APPROVED** [review]
