### PR TITLE
planner: disallow multi-updates on primary key

### LINKED ISSUE #20594: MySQL doesn't allow mutliple updates on primary key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` mysql
drop table if exists t;
create table t (a int, b int, primary key (a, b));
insert into t (1, 2);
update t t1, t t2 set t1.a=t1.a+10, t2.b=t2.b+10;
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

In MySQL 8.0.19

``` mysql
mysql> update t t1, t t2 set t1.a=t1.a+10, t2.b=t2.b+10;
ERROR 1706 (HY000): Primary key/partition key update is not allowed since the table is updated both as 't1' and 't2'.
```

### 3. What did you see instead (Required)

``` mysql
mysql> update t t1, t t2 set t1.a=t1.a+10, t2.b=t2.b+10;
Query OK, 2 rows affected (0.00 sec)
Rows matched: 2  Changed: 2  Warnings: 0
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

``` mysql
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1407-ge30220099
Edition: Community
Git Commit Hash: e302200999045d81b19d08d5ec240d3438674abb
Git Branch: master
UTC Build Time: 2020-10-22 11:32:06
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #20594  

Problem Summary:

MySQL doesn't allow multi-updates on primary key (i.e. updating primary key of the same table with different alias), but TiDB does.

### What is changed and how it works?

- Check for updates on primary keys and detect for multi-updates conflict.

### Related changes

- Need to cherry-pick to the release branch 3.0, 4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Disallow multi-updates on primary key

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -3635,13 +3635,37 @@ func checkUpdateList(ctx sessionctx.Context, tblID2table map[int64]table.Table,
...
 				return ErrUnknownColumn.GenWithStackByArgs(col.Name, clauseMsg[fieldList])
 			}
+			// Check multi-updates for primary key,
+			// see https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html#error_er_multi_update_key_conflict
+			if !flags[i] {
+				continue
+			}
+			if pk != nil {
+				for _, pkCol := range pk.Columns {
+					if col.ID == tbl.Cols()[pkCol.Offset].ID {
```
Comment (lzmhhh123) [inline planner/core/logical_plan_builder.go:3655]: We can pre-store all the PK column id to a map.

**Comment by lzmhhh123** [comment]
@dyzsr Could you check the test `check-dev`. Maybe the error definition is not satisfied rules.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -3734,13 +3734,38 @@ func checkUpdateList(ctx sessionctx.Context, tblID2table map[int64]table.Table,
 	if err != nil {
 		return err
 	}
+	isPKUpdated := make(map[int64]model.CIStr)
```
Comment (tiancaiamao) [inline planner/core/logical_plan_builder.go:3737]: The newly added logic makes this function difficult to understand.
I bet I can't understand it after 3 months.

From the `updt.TblColPosInfos`, we have the tables and columns to be updated.

```
t1          c2 c4 c6 ...
t2           c1  c2 c5 c7 ...
...
```

and what we want to prevent is this case:
t1 and t2 are actually the joinings of the same table `t`,
and they both want to update the `c2` column, which is a primary key.

So, how about handling it like this?
Step1: find out the common columns  in `the updt.TblColPosInfos`
       This can be done by sort using `table id + column id` and deduplicate
Step2: is the common column the primary key?
      If so, return the error

Comment (dyzsr) [reply planner/core/logical_plan_builder.go:3737]: Sort + deduplicate may not be suitable for primary key of multiple columns. As shown in the following cases:
``` mysql
create table t (a int, b int, c int, primary key(a,c));
update t set t.a=10, t.c=20; # reporting error
update t m, t n set m.a=10, m.b=20, n.c=30; # not reporting error
```
It would be more complicated to distinguish primary keys from different table alias.

File: planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -3734,13 +3734,29 @@ func checkUpdateList(ctx sessionctx.Context, tblID2table map[int64]table.Table,
...
 		for i, col := range tbl.WritableCols() {
 			if flags[i] && col.State != model.StatePublic {
 				return ErrUnknownColumn.GenWithStackByArgs(col.Name, clauseMsg[fieldList])
 			}
+			// Check for multi-updates on primary key,
+			// see https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html#error_er_multi_update_key_conflict
+			if !flags[i] {
+				continue
+			}
+			if col.IsPKHandleColumn(tbl.Meta()) || col.IsCommonHandleColumn(tbl.Meta()) {
```
Comment (tiancaiamao) [inline planner/core/logical_plan_builder.go:3751]: Maybe we can also check the partition key here, or leave it to another PR, as the PR title says "disallow multi-updates on primary key"

**Comment by tiancaiamao** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
