### PR TITLE
planner: enhance partition prune when comparing partition key with constant of different types

### LINKED ISSUE #59123: planner: partition prune not work when partition key has a different type with constant
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
create table t(a int, b int, c int) partition by range(a) (
    partition p1 values less than (100),
    partition p2 values less than (200),
    partition pm values less than (MAXVALUE));
analyze table t;
explain select * from t where a between "123" and "199";
```

### 2. What did you expect to see? (Required)
unnecessary partitions would be pruned, like MySQL result:
```
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | t     | p2         | ALL  | NULL          | NULL | NULL    | NULL |    1 |   100.00 | Using where |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+-------------+
```

### 3. What did you see instead (Required)
All partitions would be visited. 
If the number of partitions are large(e.g., in our online DB, a table has more than 2000+ partititions)，the select performance is really poor.
```
+-------------------------+----------+-----------+---------------+--------------------------------------------------------------------------------+
| id                      | estRows  | task      | access object | operator info                                                                  |
+-------------------------+----------+-----------+---------------+--------------------------------------------------------------------------------+
| TableReader_7           | 8000.00  | root      | partition:all | data:Selection_6                                                               |
| └─Selection_6           | 8000.00  | cop[tikv] |               | ge(cast(test.t.a, double BINARY), 123), le(cast(test.t.a, double BINARY), 199) |
|   └─TableFullScan_5     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo                                                 |
+-------------------------+----------+-----------+---------------+--------------------------------------------------------------------------------+
```

### 4. What is your TiDB version? (Required)
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v9.0.0-alpha-158-gba79f5078d-dirty
Edition: Community
Git Commit Hash: ba79f5078dddfca69ec720d66ee54f96c51e47b6
Git Branch: master
UTC Build Time: 2025-01-22 08:18:45
GoVersion: go1.23.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by L-maple**
…ant of different types

### What problem does this PR solve?

Issue Number: close #59123

Problem Summary:

### What changed and how does it work?
SQL is a weak type language, and users always ignore constant types when comparing partition key.
When try to prune partitions, try more types of constant. For now, we should consider real and decimal, which are regularly used.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by L-maple** [comment]
@Defined2014 Hi，I find a problem incompatible with MySQL. Could you help me review the PR please?

File: pkg/planner/core/rule_partition_processor.go [hunk 1]
```diff
@@ -1626,11 +1647,37 @@ func (p *rangePruner) extractDataForPrune(sctx base.PlanContext, expr expression
...
+	} else if evalType == types.ETDecimal {
+		d, isNull, err := constExpr.EvalDecimal(sctx.GetExprCtx().GetEvalCtx(), chunk.Row{})
+		if err != nil {
+			return ret, false
+		}
+		f, err := d.ToFloat64()
+		if err != nil {
+			return ret, false
+		}
+		if err == nil && !isNull {
```
Comment (mjonss) [inline pkg/planner/core/rule_partition_processor.go:1675]: From linting/nogo, you should be able to reproduce these errors with `make bazel_lint`:
```
nogo: errors found by nogo during build-time code analysis:
pkg/planner/core/rule_partition_processor.go:1675:10: tautological condition: nil == nil (nilness)
pkg/planner/core/rule_partition_processor.go:1680:9: empty-block: this block is empty, you can remove it (revive)
saving suggested fixes:
some suggested fixes are invalid or have conflicts with other fixes:
	ignoring suggested fixes from analyzer "nilness" at pkg/planner/core/rule_partition_processor.go:1675:10
	ignoring suggested fixes from analyzer "revive" at pkg/planner/core/rule_partition_processor.go:1680:9
please apply other fixes and rerun the build.
```

File: pkg/planner/core/rule_partition_processor.go [hunk 2]
```diff
@@ -1626,11 +1647,37 @@ func (p *rangePruner) extractDataForPrune(sctx base.PlanContext, expr expression
...
+			ret.c = int64(f)
+			ret.unsigned = mysql.HasUnsignedFlag(constExpr.GetType(sctx.GetExprCtx().GetEvalCtx()).GetFlag())
+			return ret, true
+		}
+	} else {
```
Comment (mjonss) [inline pkg/planner/core/rule_partition_processor.go:1680]: See above :)

**Review by mjonss — COMMENTED** [review]
Will this work also with RANGE COLUMNS partitioning and non numeric data types?

File: pkg/planner/core/rule_partition_processor.go (hunk 1 above)
Comment (L-maple) [reply pkg/planner/core/rule_partition_processor.go:1675]: ok

**Comment by wuhuizuo** [comment]
/retest

a new trigger command to refresh issue triage status.

**Review by mjonss — COMMENTED** [review]
Please check the integration tests and fix this one:
```
% cd tests/integrationtest
% ./run-tests.sh -s ../../bin/tidb-server -t planner/core/casetest/partition/partition_pruner
```
You can probably just record the new output with:
```
./run-tests.sh -s ../../bin/tidb-server -r planner/core/casetest/partition/partition_pruner
```

File: pkg/planner/core/rule_partition_processor.go [hunk 3]
```diff
@@ -1621,11 +1642,36 @@ func (p *rangePruner) extractDataForPrune(sctx base.PlanContext, expr expression
 		// If the partition expression is col, use constExpr.
 		constExpr = con
 	}
-	c, isNull, err := constExpr.EvalInt(sctx.GetExprCtx().GetEvalCtx(), chunk.Row{})
-	if err == nil && !isNull {
-		ret.c = c
-		ret.unsigned = mysql.HasUnsignedFlag(constExpr.GetType(sctx.GetExprCtx().GetEvalCtx()).GetFlag())
-		return ret, true
+	evalType := constExpr.GetType(sctx.GetExprCtx().GetEvalCtx()).EvalType()
```
[the remark this answers is not in the document]
Comment (L-maple) [reply pkg/planner/core/rule_partition_processor.go:1645]: oh, switch stmt is more elegant, I would use it.

File: pkg/planner/core/rule_partition_processor.go [hunk 4]
```diff
@@ -1588,10 +1588,23 @@ func (p *rangePruner) extractDataForPrune(sctx base.PlanContext, expr expression
...
-	} else if arg0, ok := op.GetArgs()[1].(*expression.Column); ok && arg0.ID == p.col.ID {
-		if arg1, ok := op.GetArgs()[0].(*expression.Constant); ok {
+	} else if arg1, ok := op.GetArgs()[1].(*expression.Column); ok && arg1.ID == p.col.ID {
+		if arg0, ok := op.GetArgs()[0].(*expression.Constant); ok {
 			ret.op = opposite(ret.op)
-			col, con = arg0, arg1
+			col, con = arg1, arg0
+		}
+	} else if sarg0, ok := op.GetArgs()[0].(*expression.ScalarFunction); ok && sarg0.FuncName.L == ast.Cast {
+		if arg0, ok := sarg0.GetArgs()[0].(*expression.Column); ok && arg0.ID == p.col.ID {
```
[the remark this answers is not in the document]
Comment (L-maple) [reply pkg/planner/core/rule_partition_processor.go:1597]: @mjonss I checked the `BuildCastFunctionWithCheck` func, in this func castAsXXXFunctionClass has checked the minArgs/maxArgs(both are 1), so for ast.Cast ScalarFunction, len(sarg0.GetArgs()) should be one.

File: pkg/planner/core/rule_partition_processor.go [hunk 5]
```diff
@@ -1588,10 +1588,23 @@ func (p *rangePruner) extractDataForPrune(sctx base.PlanContext, expr expression
...
+			if arg1, ok := op.GetArgs()[1].(*expression.Constant); ok {
+				col, con = arg0, arg1
+			}
+		}
+	} else if sarg1, ok := op.GetArgs()[1].(*expression.ScalarFunction); ok && sarg1.FuncName.L == ast.Cast {
+		if arg1, ok := sarg1.GetArgs()[0].(*expression.Column); ok && arg1.ID == p.col.ID {
```
[the remark this answers is not in the document]
Comment (L-maple) [reply pkg/planner/core/rule_partition_processor.go:1603]: the comment above

File: pkg/planner/core/integration_test.go [hunk 6]
```diff
@@ -175,6 +175,196 @@ func TestPartitionPruningForEQ(t *testing.T) {
...
+	// MySQL explain:
+	//+----+-------------+--------+------------+------+---------------+------+---------+------+------+----------+-------------+
+	//| id | select_type | table  | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra       |
+	//+----+-------------+--------+------------+------+---------------+------+---------+------+------+----------+-------------+
+	//|  1 | SIMPLE      | t_hash | p1         | ALL  | NULL          | NULL | NULL    | NULL |    1 |   100.00 | Using where |
+	//+----+-------------+--------+------------+------+---------------+------+---------+------+------+----------+-------------+
+
+	// case 4: range columns partition
+	tk.MustExec(`CREATE TABLE t_range_col(a int, b int)
+		PARTITION BY RANGE COLUMNS(a) (
```
Comment (mjonss) [inline pkg/planner/core/integration_test.go:295]: I would use a different datatype if testing COLUMNS partitioning, since that is the main usage (apart from partitioning on multiple columns, which is not as useful).

**Review by mjonss — APPROVED** [review]
LGTM, thank you for your contribution and good work!

**Comment by L-maple** [comment]
> Please check the integration tests and fix this one:
> 
> ```
> % cd tests/integrationtest
> % ./run-tests.sh -s ../../bin/tidb-server -t planner/core/casetest/partition/partition_pruner
> ```
> 
> You can probably just record the new output with:
> 
> ```
> ./run-tests.sh -s ../../bin/tidb-server -r planner/core/casetest/partition/partition_pruner
> ```

@mjonss Hi, I update partition_pruner.result file using the command, but integration test still fails. Is there any other problems?

**Comment by L-maple** [comment]
@mjonss @Defined2014 It seems fast_test_tiprow fails because of bazel. How should I update tidb bazel file?

**Comment by Defined2014** [comment]
> @mjonss @Defined2014 It seems fast_test_tiprow fails because of bazel. How should I update tidb bazel file?

cc @hawkingrei

File: pkg/planner/core/rule_partition_processor.go [hunk 7]
```diff
@@ -1621,11 +1642,37 @@ func (p *rangePruner) extractDataForPrune(sctx base.PlanContext, expr expression
...
+		c, isNull, err := constExpr.EvalInt(sctx.GetExprCtx().GetEvalCtx(), chunk.Row{})
+		if err == nil && !isNull {
+			ret.c = c
+			ret.unsigned = mysql.HasUnsignedFlag(constExpr.GetType(sctx.GetExprCtx().GetEvalCtx()).GetFlag())
+			return ret, true
+		}
+	case types.ETReal:
+		f, isNull, err := constExpr.EvalReal(sctx.GetExprCtx().GetEvalCtx(), chunk.Row{})
+		c := int64(f)
+		if err == nil && !isNull {
```
Comment (Defined2014) [inline pkg/planner/core/rule_partition_processor.go:1657]: This `if` branch is same in three switch-case branch. Maybe we could do it out of the switch statement.

Comment (L-maple) [reply pkg/planner/core/rule_partition_processor.go:1657]: ok, I revise it.

Comment (L-maple) [reply pkg/planner/core/rule_partition_processor.go:1655]: done

Comment (Defined2014) [reply pkg/planner/core/rule_partition_processor.go:1655]: I think we need to add a default branch
```go
    default:
            return ret, false
```

Comment (L-maple) [reply pkg/planner/core/rule_partition_processor.go:1655]: oh yes, I add it. Thanks!

**Review by Defined2014 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Comment by windtalker** [comment]
Theoretically speaking, if we have an extra function upon the partition column, it is not safe to do the partition prune, for example: if the filter is
`func(partition_col) = 1`
actually, we can't do partition prune for general function. 
More specific speaking, if the partition is a range partition, then we can do partition prune only if func is `order-preserving`, and clearly, `cast` is not `order-preserving`, and this will cause error result, https://github.com/pingcap/tidb/issues/62754 is an example. 
And a more simple example is
```
mysql> create table t_partition(a char(10)) partition by range columns(a) (PARTITION P0 VALUES LESS THAN ('b'), PARTITION P4 VALUES LESS THAN ('c'), PARTITION PMX VALUES LESS THAN (MAXVALUE));
Query OK, 0 rows affected (0.03 sec)

mysql> create table t_normal(a char(10));
Query OK, 0 rows affected (0.03 sec)
mysql> insert into t_partition values('a'),('b'),('c');
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> insert into t_normal values('a'),('b'),('c');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0
mysql> explain select * from t_partition where a = 0;
+-------------------------+---------+-----------+-------------------+------------------------------------------------+
| id                      | estRows | task      | access object     | operator info                                  |
+-------------------------+---------+-----------+-------------------+------------------------------------------------+
| TableReader_7           | 2.40    | root      | partition:PMX     | data:Selection_6                               |
| └─Selection_6           | 2.40    | cop[tikv] |                   | eq(cast(test.t_partition.a, double BINARY), 0) |
|   └─TableFullScan_5     | 3.00    | cop[tikv] | table:t_partition | keep order:false, stats:pseudo                 |
+-------------------------+---------+-----------+-------------------+------------------------------------------------+
3 rows in set, 3 warnings (0.01 sec)

mysql>  select * from t_partition where a = 0;
+------+
| a    |
+------+
| c    |
+------+
1 row in set, 3 warnings (0.00 sec)
mysql> explain select * from t_normal where a = 0;
+-------------------------+---------+-----------+----------------+---------------------------------------------+
| id                      | estRows | task      | access object  | operator info                               |
+-------------------------+---------+-----------+----------------+---------------------------------------------+
| TableReader_7           | 2.40    | root      |                | data:Selection_6                            |
| └─Selection_6           | 2.40    | cop[tikv] |                | eq(cast(test.t_normal.a, double BINARY), 0) |
|   └─TableFullScan_5     | 3.00    | cop[tikv] | table:t_normal | keep order:false, stats:pseudo              |
+-------------------------+---------+-----------+----------------+---------------------------------------------+
3 rows in set (0.00 sec)

mysql>  select * from t_normal where a = 0;
+------+
| a    |
+------+
| a    |
| b    |
| c    |
+------+
3 rows in set, 3 warnings (0.00 sec)
```

**Comment by windtalker** [comment]
I suggest we should revert this pr first, and if we still want to do similar optimization, we need a more rigorous implementation @hawkingrei @fixdb cc @L-maple
