### PR TITLE
planner: fix plan cache not working caused by type difference

### LINKED ISSUE #22952: The value of last_plan_from_cache is not expected
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
set the `prepared-plan-cache` true
```sql
create table t(a int);
insert into t values(1),(2),(3);
prepare stmt from 'select json_valid(?) from t';
set @a='{}';
execute stmt using @a;
set @a='test';
execute stmt using @a;
select @@last_plan_from_cache;
```

### 2. What did you expect to see? (Required)
1
### 3. What did you see instead (Required)
0
### 4. What is your TiDB version? (Required)
Release Version: v4.0.0-beta.2-2190-g5e832ed80
Edition: Community
Git Commit Hash: 5e832ed80a65c49c32be2043db9373863e66f66d
Git Branch: master
UTC Build Time: 2021-02-25 11:43:02
GoVersion: go1.15.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #22952

Note: Changes in this PR assume that different Flen and Decimal of user variables won't cause a different plan.

Problem Summary:

If you set `@m = 20, @n = 200`.
The FieldType for m and n will be different. The flen of m will be 2 and the flen of n will be 3. Like this:
image

Because of the mechanism introduced in https://github.com/pingcap/tidb/pull/18973, this will unnecessarily make this plan cache unusable.

Another problem is that the `SimpleLRUCache`'s `Put(key, value)` method is only effective when it's a new `key`, which means you can't use `Put()` to update an existing key-value.

### What is changed and how it works?

Only require tp, charset, and collate to be matched when verifying if a plan cache is valid.

Change (*SimpleLRUCache).Put to an override style.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- no release note.

### CODE REVIEW

File: planner/core/cache.go [hunk 1]
```diff
@@ -147,12 +147,18 @@ func NewPSTMTPlanCacheKey(sessionVars *variable.SessionVars, pstmtID uint32, sch
...
 // Equal compares FieldSlice with []*types.FieldType
+// Currently this is only used in plan cache to invalidate cache when types of variables are different.
 func (s FieldSlice) Equal(tps []*types.FieldType) bool {
 	if len(s) != len(tps) {
 		return false
 	}
 	for i := range tps {
-		if !s[i].Equal(tps[i]) {
+		// We only use part of logic of `func (ft *FieldType) Equal(other *FieldType)` here because (1) only numeric and
+		// string types will show up here, and (2) we don't need flen and decimal to be matched exactly to use plan cache
```
Comment (eurekaka) [inline planner/core/cache.go:157]: IMHO, this assumption is pretty fragile. Consider this case:

```
MySQL [test]> create table t(a varchar(20), b int, index ia(a(4)));
Query OK, 0 rows affected (0.12 sec)

MySQL [test]> explain select * from t use index(ia) where a = 'xx';
+-------------------------------+---------+-----------+----------------------+---------------------------------------------------+
| id                            | estRows | task      | access object        | operator info                                     |
+-------------------------------+---------+-----------+----------------------+---------------------------------------------------+
| IndexLookUp_8                 | 10.00   | root      |                      |                                                   |
| ├─IndexRangeScan_5(Build)     | 10.00   | cop[tikv] | table:t, index:ia(a) | range:["xx","xx"], keep order:false, stats:pseudo |
| └─Selection_7(Probe)          | 10.00   | cop[tikv] |                      | eq(test.t.a, "xx")                                |
|   └─TableRowIDScan_6          | 10.00   | cop[tikv] | table:t              | keep order:false, stats:pseudo                    |
+-------------------------------+---------+-----------+----------------------+---------------------------------------------------+
4 rows in set (0.00 sec)
```

If we apply an optimization in the future to check the length of the constant string and decide if we need to keep the `Selection_7`, then this cached plan may return wrong results if we reuse it.

For this case, we can check `curr_flen <= cached_flen` to avoid potential bugs, but I am not sure if there are other possibilities that our plan may be dependent on the `flen` / `decimal` of the constants.

Comment (zz-jason) [reply planner/core/cache.go:157]: it's better to use another function to perform this special `equal` validation for plan cache.

**Review by eurekaka — APPROVED** [review]
/LGTM

**Review by winoros — APPROVED** [review]

File: planner/core/cache.go (hunk 1 above)
Comment (time-and-fate) [reply planner/core/cache.go:157]: After discussion, we decide to leave behind the prefix index case mentioned above for now.
Because in `getPhysicalPlan`, we don't know exactly how will a user variable be used. It might be inside a filter expression or part of a range.
If now we want to prevent the case, we can expect that we'll need to implement something like "find if this user variable is used on some indexes in this plan", which is complicated.
It will be easier just not to cache that plan when we implemented this optimization someday.
Also, I added some comments to clarify this.
