### PR TITLE
util, executor: fix analyze stmts be killed unexpectedly

### LINKED ISSUE #41825: analyze is killed unexpected
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
If one analyze stmt is killed by the global memory controller, the following analyze stmts on the same connection will be killed immediately.
We can reproduce this problem by modifying the unit test: TestGlobalMemoryControlForAnalyze
``` diff
diff --git a/executor/analyzetest/analyze_test.go b/executor/analyzetest/analyze_test.go
index 843200fea6..810a3014d1 100644
--- a/executor/analyzetest/analyze_test.go
+++ b/executor/analyzetest/analyze_test.go
@@ -3087,13 +3087,14 @@ func TestGlobalMemoryControlForAnalyze(t *testing.T) {
        sql := "analyze table t with 1.0 samplerate;" // Need about 100MB
        require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/util/memory/ReadMemStats", `return(536870912)`))
        require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/executor/mockAnalyzeMergeWorkerSlowConsume", `return(100)`))
-       defer func() {
-               require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/util/memory/ReadMemStats"))
-               require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/executor/mockAnalyzeMergeWorkerSlowConsume"))
-       }()
        _, err := tk0.Exec(sql)
        require.True(t, strings.Contains(err.Error(), "Out Of Memory Quota!"))
        runtime.GC()
+       require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/util/memory/ReadMemStats"))
+       require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/executor/mockAnalyzeMergeWorkerSlowConsume"))
+
+       _, err = tk0.Exec(sql)
+       require.NoError(t, err)
 }

```

### 2. What did you expect to see? (Required)
TestGlobalMemoryControlForAnalyze passed

### 3. What did you see instead (Required)
TestGlobalMemoryControlForAnalyze failed

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: close #41825 

Problem Summary:

### What is changed and how it works?
https://github.com/pingcap/tidb/pull/39372 add an if-check for Tracker.Detach to avoid problems when the tracker is labeled by LabelForMemDB. But it does not take the label LableForAnalyzeMemory into consideration.
Thus the NeedKilled flag will not be set to false after one analyze stmt is killed. And the following analyze statements on this connection will be killed immediately 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the problem that analyze statement be killed unexpectedly.
```

### CODE REVIEW

**Review by xuyifangreeneyes — APPROVED** [review]

File: executor/analyzetest/analyze_test.go [hunk 1]
```diff
@@ -3087,13 +3087,13 @@ func TestGlobalMemoryControlForAnalyze(t *testing.T) {
...
-	defer func() {
-		require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/util/memory/ReadMemStats"))
-		require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/executor/mockAnalyzeMergeWorkerSlowConsume"))
-	}()
 	_, err := tk0.Exec(sql)
 	require.True(t, strings.Contains(err.Error(), "Out Of Memory Quota!"))
 	runtime.GC()
+	require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/util/memory/ReadMemStats"))
+	require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/executor/mockAnalyzeMergeWorkerSlowConsume"))
+	_, err = tk0.Exec(sql)
```
Comment (hawkingrei) [inline executor/analyzetest/analyze_test.go:3095]:
```
tk0.MustExec(sql)
```

**Review by wshwsh12 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
