### PR TITLE
ddl: inherit placement rules from the parent

### LINKED ISSUE #20669: ddl: altering placement rules misreports ErrBuildRuleList
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> create table t1(id int primary key) partition by hash(id) partitions 2;
Query OK, 0 rows affected (0.09 sec)

mysql> alter table t1 alter partition p1 alter placement policy constraints='{"+zone=bj,+zone=sh":2,"-zone=gz":1}' role=follower;
```

### 2. What did you expect to see? (Required)

It should not report an error, as `alter` is transformed to `add` and it's legal to add 3 followers.

### 3. What did you see instead (Required)

```
ERROR 1105 (HY000): failed to notify PD the placement rules: "[PD:placement:ErrBuildRuleList]build rule list failed, needs at least one leader or voter for range {7480000000000000FF4900000000000000F8, 7480000000000000FF4A00000000000000F8}"
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by xhebox**
Signed-off-by: xhe <xw897002528@gmail.com>

### What problem does this PR solve?

Issue Number: close #20669

Problem Summary: Root cause is summarized here https://github.com/pingcap/tidb/issues/20669#issuecomment-726603408. This PR, when retrieving rule bundles for a partition, will fallback to rule bundles from table/schema and the one from PD. And dropping partitions will simply drop the bundles, truncating partitions just rename bundles. They does not modify rules of bundles, so it is ok to just handle `AlterTableAlterPartition` statements.

Note that it breaks the RFC[2020-06-24-placement-rules-in-sql.md]:

> Once the placement rules on a database or a partitioned table are changed, the inherited placement rules are also updated, but others are kept.

That is somewhat tricky and needs more discussion.

`d.AlterTablePartition` is renamed to `d.AlterTableAlterPartition` to distinguish it from `ast.AlterTablePartition`.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Run the example of the original issue.

### Release note 

- No release note

### CODE REVIEW

**Review by djshow832 — COMMENTED** [review]
Add some test cases.

File: infoschema/infoschema.go [hunk 1]
```diff
@@ -416,3 +416,21 @@ func (is *infoSchema) RuleBundles() map[string]*placement.Bundle {
...
+// If the default bundle is unavailable, an empty bundle with an GroupID(ids[0]) is returned.
+func GetBundle(h InfoSchema, ids []int64) *placement.Bundle {
+	for _, id := range ids {
+		b, ok := h.BundleByName(placement.GroupID(id))
+		if ok {
+			return b.Clone()
+		}
+	}
+
+	b, ok := h.BundleByName("pd")
```
Comment (djshow832) [inline infoschema/infoschema.go:430]: Define a constant in the `placement` package.

Comment (xhebox) [reply infoschema/infoschema.go]: Done, if the name is OK.

File: infoschema/infoschema.go [hunk 2]
```diff
@@ -416,3 +416,30 @@ func (is *infoSchema) RuleBundles() map[string]*placement.Bundle {
...
+
+	b, ok := h.BundleByName(placement.PDBundleID)
+	if ok {
+		b = b.Clone()
+		newRules := b.Rules[:0]
+		for _, rule := range b.Rules {
+			if rule.StartKeyHex == "" && rule.EndKeyHex == "" {
+				newRules = append(newRules, rule)
+			}
+		}
```
Comment (djshow832) [inline infoschema/infoschema.go:439]:
```suggestion
		newRules := b.Rules[:0]
		for _, rule := range b.Rules {
			if rule.StartKeyHex == "" && rule.EndKeyHex == "" {
				newRules = append(newRules, rule.Clone())
			}
		}
```

**Review by djshow832 — COMMENTED** [review]
LGTM

File: infoschema/infoschema.go [hunk 3]
```diff
@@ -416,3 +416,29 @@ func (is *infoSchema) RuleBundles() map[string]*placement.Bundle {
...
+		if ok {
+			return b.Clone()
+		}
+	}
+
+	b, ok := h.BundleByName(placement.PDBundleID)
+	if ok {
+		newRules := b.Rules[:0]
+		for _, rule := range b.Rules {
+			if rule.StartKeyHex == "" && rule.EndKeyHex == "" {
```
Comment (AilinKid) [inline infoschema/infoschema.go:435]: what does it(startKeyHex equal to "") meaning?

File: ddl/placement/const.go [hunk 4]
```diff
@@ -13,9 +13,12 @@
 
 package placement
 
-// BundleIDPrefix is the bundle prefix of all rules from TiDB_DDL statements.
+// BundleIDPrefix is the bundle prefix of all rule bundles from TiDB_DDL statements.
 const BundleIDPrefix = "TiDB_DDL_"
 
+// PDBundleID is the bundle name of pd, the default bundle for all regions.
```
Comment (AilinKid) [inline ddl/placement/const.go:19]: how about enclosing them with a single const ()

File: infoschema/infoschema.go (hunk 3 above)
Comment (xhebox) [reply infoschema/infoschema.go:435]: Empty keyrange, or applicable to all regions/partitions.

File: ddl/placement/const.go (hunk 4 above)
Comment (xhebox) [reply ddl/placement/const.go]: Good.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
