### PR TITLE
planner, CTE, view: Fix default inline CTE which contains orderby/limit/distinct and inside of view | tidb-test=pr/2415

### LINKED ISSUE #56582: The CTE inside of view can't determine whether it can be inlined
## Bug Report

If the CTE is inside of view, optimizer can't determine whether it can be inlined by rule "The CTE is consumed only once. It can be inlined by default."

### 1. Minimal reproduce step (Required)

1. create view with cte1, cte2, cte3. The consumer count of CTE1  is 2, So it could not be inlined.
```
create view test_multi_consumer_cte as 
with cte1 as (select a from test), 
cte2 as (select a from cte1 where a=1), 
cte3 as (select cte1.a from cte1 join cte2 where cte1.a=2) 
select * from cte3;
```

2. query table
```
mysql> explain select * from test_multi_consumer_cte;
+------------------------------+----------+-----------+---------------+--------------------------------+
| id                           | estRows  | task      | access object | operator info                  |
+------------------------------+----------+-----------+---------------+--------------------------------+
| HashJoin_38                  | 100.00   | root      |               | CARTESIAN inner join           |
| ├─TableReader_45(Build)      | 10.00    | root      |               | data:Selection_44              |
| │ └─Selection_44             | 10.00    | cop[tikv] |               | eq(test.test.a, 1)             |
| │   └─TableFullScan_43       | 10000.00 | cop[tikv] | table:test    | keep order:false, stats:pseudo |
| └─TableReader_42(Probe)      | 10.00    | root      |               | data:Selection_41              |
|   └─Selection_41             | 10.00    | cop[tikv] |               | eq(test.test.a, 2)             |
|     └─TableFullScan_40       | 10000.00 | cop[tikv] | table:test    | keep order:false, stats:pseudo |
+------------------------------+----------+-----------+---------------+--------------------------------+
7 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

The behavior should be seem as the query view **directly**

```
+---------------------------------+----------+-----------+---------------+--------------------------------------------+
| id                              | estRows  | task      | access object | operator info                              |
+---------------------------------+----------+-----------+---------------+--------------------------------------------+
| HashJoin_32                     | 256.00   | root      |               | CARTESIAN inner join                       |
| ├─Selection_36(Build)           | 16.00    | root      |               | eq(test.test.a, 1)                         |
| │ └─CTEFullScan_37              | 20.00    | root      | CTE:cte1      | data:CTE_0                                 |
| └─Selection_34(Probe)           | 16.00    | root      |               | eq(test.test.a, 2)                         |
|   └─CTEFullScan_35              | 20.00    | root      | CTE:cte1      | data:CTE_0                                 |
| CTE_0                           | 20.00    | root      |               | Non-Recursive CTE                          |
| └─TableReader_29(Seed Part)     | 20.00    | root      |               | data:Selection_28                          |
|   └─Selection_28                | 20.00    | cop[tikv] |               | or(eq(test.test.a, 2), eq(test.test.a, 1)) |
|     └─TableFullScan_27          | 10000.00 | cop[tikv] | table:test    | keep order:false, stats:pseudo             |
+---------------------------------+----------+-----------+---------------+--------------------------------------------+
9 rows in set (0.01 sec)
```

### 3. What did you see instead (Required)

The CTE1 is inlined which is incorrect , because it is consumed by CTE2 and CTE3. 
The consumer count of CTE1 should be 2 more than 1. So it could not be inlined be default.

### 4. What is your TiDB version? (Required)

v8.1

### LINKED ISSUE #56603: Parsing CTE error with "doesn't yet support 'ORDER BY / LIMIT / SELECT DISTINCT in recursive query block"
## Bug Report

The CTE contain DISTINCT keyword could not be inlined by default when the CTE is referenced by recursive query block of another CTE.

### 1. Minimal reproduce step (Required)

```
create table test(a int);

explain 
WITH RECURSIVE 
CTE (x) AS (SELECT distinct a FROM test) ,
CTE1(x) AS (SELECT a FROM test UNION ALL select CTE.x from CTE join CTE1 on CTE.x=CTE1.x) 
SELECT * FROM CTE1;

```

### 2. What did you expect to see? (Required)

CTE is not inlined.

```
+-----------------------------------+----------+-----------+---------------+----------------------------------------------------------------+
| id                                | estRows  | task      | access object | operator info                                                  |
+-----------------------------------+----------+-----------+---------------+----------------------------------------------------------------+
| CTEFullScan_42                    | 18000.00 | root      | CTE:cte1      | data:CTE_1                                                     |
| CTE_1                             | 18000.00 | root      |               | Recursive CTE                                                  |
| ├─TableReader_22(Seed Part)       | 10000.00 | root      |               | data:TableFullScan_21                                          |
| │ └─TableFullScan_21              | 10000.00 | cop[tikv] | table:test    | keep order:false, stats:pseudo                                 |
| └─HashJoin_36(Recursive Part)     | 8000.00  | root      |               | inner join, equal:[eq(test.test.a, test.test.a)]               |
|   ├─Selection_37(Build)           | 6400.00  | root      |               | not(isnull(test.test.a))                                       |
|   │ └─CTEFullScan_38              | 8000.00  | root      | CTE:cte       | data:CTE_0                                                     |
|   └─Selection_39(Probe)           | 8000.00  | root      |               | not(isnull(test.test.a))                                       |
|     └─CTETable_40                 | 10000.00 | root      |               | Scan on CTE_1                                                  |
| CTE_0                             | 8000.00  | root      |               | Non-Recursive CTE                                              |
| └─HashAgg_29(Seed Part)           | 8000.00  | root      |               | group by:test.test.a, funcs:firstrow(test.test.a)->test.test.a |
|   └─TableReader_30                | 8000.00  | root      |               | data:HashAgg_25                                                |
|     └─HashAgg_25                  | 8000.00  | cop[tikv] |               | group by:test.test.a,                                          |
|       └─TableFullScan_28          | 10000.00 | cop[tikv] | table:test    | keep order:false, stats:pseudo                                 |
+-----------------------------------+----------+-----------+---------------+----------------------------------------------------------------+
14 rows in set (5.94 sec)
```

### 3. What did you see instead (Required)

ERROR 1235 (42000): This version of TiDB doesn't yet support 'ORDER BY / LIMIT / SELECT DISTINCT in recursive query block of Common Table Expression'

### 4. What is your TiDB version? (Required)

after v6.5.10 (include)

### PR DESCRIPTION
**Pull request by elsa0520**
### What problem does this PR solve?

Issue Number: close #56603, close #56582

Problem Summary:

### What changed and how does it work?

1. If the CTE contain orderby/limit/distinct and CTE is referenced by another CTE recursive part, it cannot be inlined . Related issue #56603
2. If the CTE inside of view, the consumerCount of CTE cannot be updated because the view skip the preprocessor phase in during optimizer, it also cannot judge the inline or not. So the CTE inside of view will always be not inlined. Related issue  #56582

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
修复错误的 inline CTE，如果 CTE 包含 orderby/limit/distinct 子句并且被另外一个 CTE 的 recursive part 所引用。
同时去除对 view 中的 CTE 进行是否默认 inline 的优化。
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -4287,13 +4299,22 @@ func (b *PlanBuilder) computeCTEInlineFlag(cte *cteInfo) {
...
 				fmt.Sprintf("Recursive CTE %s can not be inlined by merge() or tidb_opt_force_inline_cte.", cte.def.Name))
 		}
-	} else if cte.containAggOrWindow && b.buildingRecursivePartForCTE {
+		cte.isInline = false
+	} else if cte.containRecursiveForbiddenOperator && b.buildingRecursivePartForCTE {
 		if cte.forceInlineByHintOrVar {
 			b.ctx.GetSessionVars().StmtCtx.AppendWarning(plannererrors.ErrCTERecursiveForbidsAggregation.FastGenByArgs(cte.def.Name))
 		}
-	} else if cte.consumerCount > 1 {
+		cte.isInline = false
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go:4307]: cte.isInline is the only the variable declared here and used here, we can use a temporary variable rather than a member variable inside cte?

Comment (AilinKid) [reply pkg/planner/core/logical_plan_builder.go:4307]: which means this function will return a bool back to the caller

**Review by AilinKid — COMMENTED** [review]
REST LGTM

File: pkg/planner/core/logical_plan_builder.go (hunk 1 above)
Comment (elsa0520) [reply pkg/planner/core/logical_plan_builder.go:4307]: It is used by buildSequence fuction so I cannot just return a bool to the caller

```
func (b *PlanBuilder) tryToBuildSequence(ctes []*cteInfo, p base.LogicalPlan) base.LogicalPlan {
	if !b.ctx.GetSessionVars().EnableMPPSharedCTEExecution {
		return p
	}
	for i := len(ctes) - 1; i >= 0; i-- {
		if !ctes[i].nonRecursive {
			return p
		}
		if ctes[i].isInline || ctes[i].cteClass == nil {
			ctes = append(ctes[:i], ctes[i+1:]...)
		}
	}
```

**Review by AilinKid — APPROVED** [review]

**Comment by bb7133** [comment]
Hi @elsa0520 , thanks for this fix. Please notice that we always use English on Github, please try to avoid Chinese for the release note.
