### PR TITLE
 expression: function `format` incompatible 

### LINKED ISSUE #8796: function `format` incompatible with MySQL for round up
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

In TiDB:
```
mysql> select format(1.123456, 4);
+---------------------+
| format(1.123456, 4) |
+---------------------+
| 1.1234              |
+---------------------+
1 row in set (0.00 sec)
```

2. What did you expect to see?

In MySQL:

```
mysql> select format(1.123456, 4);
+---------------------+
| format(1.123456, 4) |
+---------------------+
| 1.1235              |
+---------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

Different function result regarding round up.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-rc.3-347-ga7907ed
Git Commit Hash: a7907ede7a9a740953b0c753b5b2b7add5b55195
Git Branch: master
UTC Build Time: 2018-12-24 11:14:34
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by tender-boluo**
### What problem does this PR solve? 

Fixed #8796 

### What is changed and how it works?
Changed the function `evalString` in `expression/builtin_string.go` 
### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: expression/builtin_string.go [hunk 1]
```diff
@@ -3019,6 +3019,54 @@ func (b *builtinFormatSig) evalString(row chunk.Row) (string, bool, error) {
...
+		if err != nil {
+			return "", isNull, err
+		}
+		if len(x2) > digit {
+			t := []byte(x2)
+			carry := false
+			if t[digit] >= '5' {
+				carry = true
+			}
+			if carry == true {
```
Comment (eurekaka) [inline expression/builtin_string.go]: Use `carry` directly since it is bool type?

File: expression/builtin_string.go [hunk 2]
```diff
@@ -3019,6 +3019,54 @@ func (b *builtinFormatSig) evalString(row chunk.Row) (string, bool, error) {
...
+				for i := digit - 1; i >= 0; i-- {
+					if t[i] == '9' && carry == true {
+						t[i] = '0'
+						carry = true
+					} else if carry == true {
+						t[i] = t[i] + 1
+						carry = false
```
Comment (eurekaka) [inline expression/builtin_string.go]: Put `carry` check in the for loop, so we can break the loop once `carry` is changed to false?

File: expression/builtin_string.go [hunk 3]
```diff
@@ -3019,6 +3019,54 @@ func (b *builtinFormatSig) evalString(row chunk.Row) (string, bool, error) {
...
+			x2 = string(t)
+			t = []byte(x1)
+			if carry == true {
+				for i := len(x1) - 1; i >= 0; i-- {
+					if t[i] == '9' && carry == true {
+						t[i] = '0'
+						carry = true
+					} else if carry == true {
+						t[i] = t[i] + 1
+						carry = false
```
Comment (eurekaka) [inline expression/builtin_string.go]: ditto

File: expression/builtin_string.go [hunk 4]
```diff
@@ -3019,6 +3019,54 @@ func (b *builtinFormatSig) evalString(row chunk.Row) (string, bool, error) {
 	if isNull || err != nil {
 		return "", isNull, err
 	}
+	if strings.Contains(x, ".") {
```
Comment (eurekaka) [inline expression/builtin_string.go]: Please wrap up this code snippet into a single function, and call it in `evalNumDecArgsForFormat`, because `builtinFormatWithLocaleSig::evalString` need this round up as well.

File: expression/builtin_string.go [hunk 5]
```diff
@@ -2970,9 +2970,76 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
 	dStr := strconv.FormatInt(d, 10)
+	xStr, err = roundingNum(xStr, dStr)
+	if err != nil {
+		return "", "", isNull, err
+	}
 	return xStr, dStr, false, nil
 }
 
+func roundingNum(xStr, dStr string) (string, error) {
+
```
[the remark this answers is not in the document]
Comment (tender-boluo) [reply expression/builtin_string.go]: Would you think  the name which is `roundingNum` is enough?
I want to think a better name , but I can not.

File: expression/builtin_string.go [hunk 6]
```diff
@@ -2970,9 +2970,76 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
+				for i := digit - 1; i >= 0; i-- {
+					if t[i] == '9' && carry == true {
+						t[i] = '0'
+						carry = true
+					} else if carry == true {
+						t[i] = t[i] + 1
+						carry = false
+						break
+					}
+				}
```
[the remark this answers is not in the document]
Comment (tender-boluo) [reply expression/builtin_string.go]: Cool!!!
Simple enough!
Why I can not write this EXCITING code!

File: expression/builtin_string.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (eurekaka) [reply expression/builtin_string.go]: How about `roundFormatArgs()`?

File: expression/builtin_string.go [hunk 7]
```diff
@@ -2970,9 +2970,76 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
+	if err != nil {
+		return "", "", isNull, err
+	}
 	return xStr, dStr, false, nil
 }
 
+func roundingNum(xStr, dStr string) (string, error) {
+	if strings.Contains(xStr, ".") {
+		sign := false
+		// xStr can not has '+' prefix now.
```
Comment (eurekaka) [inline expression/builtin_string.go]:
```suggestion
		// xStr cannot have '+' prefix now.
```

File: expression/builtin_string.go [hunk 8]
```diff
@@ -2970,9 +2970,76 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
+		// It is built in `evalNumDecArgsFormat` after evaluating `Evalxxx` method.
+		if strings.HasPrefix(xStr, "-") {
+			xStr = strings.Trim(xStr, "-")
+			sign = true
+		}
+		if strings.HasPrefix(xStr, "+") {
```
Comment (eurekaka) [inline expression/builtin_string.go]: I think we don't need this check now, the comment above is enough.

File: expression/builtin_string.go [hunk 9]
```diff
@@ -2970,9 +2970,76 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
+		if err != nil {
+			return "", err
+		}
+		if len(x2) > digit {
+			t := []byte(x2)
+			carry := false
+			if t[digit] >= '5' {
+				carry = true
+			}
+			if carry {
```
Comment (eurekaka) [inline expression/builtin_string.go]: We don't need this `if carry` check either? because the for loop already checks this condition.

File: expression/builtin_string.go [hunk 10]
```diff
@@ -2970,9 +2970,76 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
+						t[i] = '0'
+					} else {
+						t[i] = t[i] + 1
+						carry = false
+					}
+				}
+			}
+			x2 = string(t)
+			t = []byte(x1)
+			if carry {
```
Comment (eurekaka) [inline expression/builtin_string.go]: Ditto

File: expression/builtin_string.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (tender-boluo) [reply expression/builtin_string.go]: Bravo!

File: expression/builtin_string.go (hunk 8 above)
Comment (tender-boluo) [reply expression/builtin_string.go]: Really? I think this will make code move strong.

File: expression/builtin_string.go (hunk 9 above)
Comment (tender-boluo) [reply expression/builtin_string.go]: Sorry for my mistake.

File: expression/builtin_string.go [hunk 11]
```diff
@@ -2970,9 +2970,72 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
 	}
 	dStr := strconv.FormatInt(d, 10)
+	xStr, err = roundFormatArgs(xStr, dStr)
+	if err != nil {
+		return "", "", isNull, err
+	}
 	return xStr, dStr, false, nil
 }
 
+func roundFormatArgs(xStr, dStr string) (string, error) {
```
Comment (qw4990) [inline expression/builtin_string.go]: Why don't you just use `d` as its parameter.

Comment (tender-boluo) [reply expression/builtin_string.go]: It mean `digit_string`.
And `dstr` can keep in line with the previous ones.

Comment (qw4990) [reply expression/builtin_string.go]: emm.. What I mean is that why don't you use `digit int`.
Then `evalNumDecArgsForFormat` can just deliver its local variable `d` to `roundFormatArgs `.
And `roundFormatArgs` doesn't have to `Atoi` it again.

File: expression/builtin_string.go (hunk 8 above)
Comment (zz-jason) [reply expression/builtin_string.go]: @tender-boluo Looks like this is a redundant check? Could you remove it? Because it impact the performance.

File: expression/builtin_string.go [hunk 12]
```diff
@@ -2969,10 +2969,70 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
+			xStr = strings.Trim(xStr, "-")
+			sign = true
+		}
+		if strings.HasPrefix(xStr, "+") {
+			return "", errors.Errorf("xStr can not has `+` prefix")
+		}
+
+		xArr := strings.Split(xStr, ".")
+		x1 := xArr[0]
+		x2 := xArr[1]
```
Comment (zz-jason) [inline expression/builtin_string.go]: how about:
```
s/x1/integerPart/
s/x2/decimalPart/
```

File: expression/builtin_string.go [hunk 13]
```diff
@@ -2969,10 +2969,70 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
 	}
+	xStr, err = roundFormatArgs(xStr, int(d))
+	if err != nil {
+		return "", "", isNull, err
+	}
 	dStr := strconv.FormatInt(d, 10)
 	return xStr, dStr, false, nil
 }
 
+func roundFormatArgs(xStr string, digit int) (string, error) {
```
Comment (zz-jason) [inline expression/builtin_string.go]: s/digit/maxNumDecimals/?

File: expression/builtin_string.go [hunk 14]
```diff
@@ -2969,10 +2969,70 @@ func evalNumDecArgsForFormat(f builtinFunc, row chunk.Row) (string, string, bool
...
+	if strings.Contains(xStr, ".") {
```
Comment (zz-jason) [inline expression/builtin_string.go]: how about:
```go
if !strings.Contains(xStr, ".") {
	return xStr, nil
}

// round the decimals if necessary
...
```

**Comment by zz-jason** [comment]
@tender-boluo Thanks for your contribution! Could you help us to cherry pick this commit to release-2.1 and release-2.0?

**Comment by tender-boluo** [comment]
Definitely yes!
It is my pleasure.

**Comment by tender-boluo** [comment]
I am sorry to you @zz-jason .
At beginning , I think this request is easy.
But when I cherry-pick to 2.0(2.1) , and solve the conflict, change the function parameters.
I find I can not make all tests passed.
The error is miscellaneous and I can not solve it at now.
I think it is a little hard to me and I have not enough time to do it.

Could you please assign it to others first, I think I will enjoy my holidays.
If others solve it, It is a good learning opportunity for me.
If it still need to solve this problem in the future, I am happy to solve it again when I have time to do it.

There is [what I try]( https://github.com/tender-boluo/tidb/commits/9182-cherry-pick-to-2.0), but cannot work well  :(
At last but not least , happy Chinese new year to all.

**Comment by zz-jason** [comment]
@tender-boluo Okay, I'll try to cherry-pick this commit. Happy Chinese New Year! Have a nice holiday!
