### PR TITLE
planner: ban `rule_generate_column_substitute` when `column`'s…

### LINKED ISSUE #16020: SELECT on table with generated column causes a server panic
Consider the following statements:

```sql
CREATE TABLE t0(c0 CHAR AS (c1) UNIQUE, c1 INT);
INSERT INTO t0(c1) VALUES (0), (1);
SELECT * FROM t0; -- connection running loop panic
```
Unexpectedly, the `SELECT` causes a server panic:

```
[2020/04/02 14:13:50.265 +02:00] [ERROR] [conn.go:659] ["connection running loop panic"] [conn=291] [lastSQL="SELECT * FROM t0"] [err="runtime error: index out of range [8] with length 2"] [stack="goroutine 15844882 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x2cfbf40, 0xc0138695c0, 0xc010f16ea0)\n\t/tidb/server/conn.go:657 +0xee\npanic(0x27debc0, 0xc00d2623c0)\n\t/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0x0, 0x2d121a0, 0xc001e905a0, 0xc0147bb238, 0x2cfbf40, 0xc0138695c0, 0xc010f16ea0)\n\t/tidb/server/conn.go:1350 +0x597\npanic(0x27debc0, 0xc00d2623c0)\n\t/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/util/chunk.(*Column).GetInt64(...)\n\t/tidb/util/chunk/column.go:503\ngithub.com/pingcap/tidb/util/chunk.Row.GetInt64(...)\n\t/tidb/util/chunk/row.go:50\ngithub.com/pingcap/tidb/server.dumpTextRow(0xc013d12000, 0x4, 0x400, 0xc014b62b50, 0x2, 0x2, 0xc001e905f0, 0x1, 0xc013d12000, 0xc, ...)\n\t/tidb/server/util.go:280 +0x195c\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc010f16ea0, 0x2cfbf40, 0xc0138695c0, 0x2d121a0, 0xc001e905a0, 0xb700, 0x27c6820, 0xc001e905a0)\n\t/tidb/server/conn.go:1420 +0x2e7\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc010f16ea0, 0x2cfbf40, 0xc0138695c0, 0x2d121a0, 0xc001e905a0, 0xc000002900, 0x0, 0x0, 0x0)\n\t/tidb/server/conn.go:1363 +0x206\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc010f16ea0, 0x2cfbf40, 0xc0138695c0, 0xc00d262181, 0x10, 0x0, 0x0)\n\t/tidb/server/conn.go:1271 +0x209\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc010f16ea0, 0x2cfbf40, 0xc0138695c0, 0xc00d262181, 0x11, 0x10, 0x0, 0x0)\n\t/tidb/server/conn.go:898 +0x5e2\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc010f16ea0, 0x2cfbf40, 0xc0138695c0)\n\t/tidb/server/conn.go:712 +0x27c\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc000a89810, 0xc010f16ea0)\n\t/tidb/server/server.go:415 +0xaf9\ncreated by github.com/pingcap/tidb/server.(*Server).Run\n\t/tidb/server/server.go:333 +0x709\n"]
```

Environment:
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_Version()                                                                                                                                                                                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-167-gaa7ef9c46
Git Commit Hash: aa7ef9c46435bb20d42fa0badcf09fc16f9609a9
Git Branch: master
UTC Build Time: 2020-04-02 09:15:47
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by LittleFall**
### What problem does this PR solve?

Close #16020

### What is changed and how it works?

Consider this query:

```sql
USE test;
DROP TABLE IF EXISTS t0;
CREATE TABLE t0(c0 CHAR AS (c1) UNIQUE, c1 INT);
INSERT INTO t0(c1) VALUES (1),(2);
SELECT * FROM t0; -- connection running loop panic
```

Because of the rule of generated column substitute, this query will consider `c1` and `c0` equal.

The query plan will project `c0` to `c0, c0`.

```sql
+-------------------------+----------+-----------+------------------------+--------------------------------+
| id                      | estRows  | task      | access object          | operator info                  |
+-------------------------+----------+-----------+------------------------+--------------------------------+
| Projection_3            | 10000.00 | root      |                        | test.t0.c0, test.t0.c0         |
| └─IndexReader_7         | 10000.00 | root      |                        | index:IndexFullScan_6          |
|   └─IndexFullScan_6     | 10000.00 | cop[tikv] | table:t0, index:c0(c0) | keep order:false, stats:pseudo |
+-------------------------+----------+-----------+------------------------+--------------------------------+
```

When output, the data in the column of c1 in the chunk is only two bytes, but because the type is int64, it will get 8 bytes at a time, which causing panic.

The solution in this pr is that when the type of a indexed virtual generated column and its expression type are different, the rule of generated column substitute is banned.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

Fix `rule_generate_column_substitute` bug.

### CODE REVIEW

File: planner/core/rule_generate_column_substitute.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func collectGenerateColumn(lp LogicalPlan, exprToColumn ExprColumnMap) {
 			if colInfo.IsGenerated() && !colInfo.GeneratedStored {
 				s := ds.schema.Columns
 				col := expression.ColInfo2Col(s, colInfo)
-				if col != nil {
+				if col != nil && col.GetType().EvalType() == col.VirtualExpr.GetType().EvalType() {
```
Comment (wjhuang2016) [inline planner/core/rule_generate_column_substitute.go:65]: Try `col.GetType().Equal(col.VirtualExpr.GetType())`
The `EvalType` is not accurate.

Comment (LittleFall) [reply planner/core/rule_generate_column_substitute.go]: It seems `Equal` is too strict to make most of `explain_generate_column_substitute.test` pass.

Comment (winoros) [reply planner/core/rule_generate_column_substitute.go]: @wjhuang2016  For the case `CREATE TABLE t0(c0 CHAR AS (c1) UNIQUE, c1 INT);`. Should we treat `c0` as the `cast(c1 as char)` instead of `c1` to avoid this issue?

File: planner/core/rule_generate_column_substitute.go [hunk 2]
```diff
@@ -55,7 +55,7 @@ func getSubstitutableType(colType *types.FieldType) int {
 }
 
 func checkSubstitutability(c1, c2 *types.FieldType) bool {
-	if getSubstitutableType(c1) == getSubstitutableType(c2) && c1.Decimal == c2.Decimal {
+	if getSubstitutableType(c1) == getSubstitutableType(c2) && c1.Decimal == c2.Decimal && c1.Collate == c2.Collate {
 		return true
 	}
 	return false
```
Comment (Deardrops) [inline planner/core/rule_generate_column_substitute.go]:
```suggestion
	return getSubstitutableType(c1) == getSubstitutableType(c2) &&
		c1.Decimal == c2.Decimal &&
		c1.Collate == c2.Collate
```

Comment (LittleFall) [reply planner/core/rule_generate_column_substitute.go]: Fixed.

(I don't konw why I can't click `commit suggestion` button.)

**Comment by LittleFall** [comment]
After we set the type judgment standard to the same chunk storage method, the panic problem has been solved. 

However, we found that other attributes of `FieldType` than Tp also need to be considered. 

Too loose judgment standards will lead to unexpected data truncation, and too tight judgment standards such as `FieldType.Euqal` will cause the generated column replacement rules to become invalid.

The current judgment standard is:
1. `Tp` are all integer types or equal
2. `Decimal` equal
3. `Charset` equal
4. `Collate` equal
5. The `unsignedFlag` in the `Flag` is equal
6. `Elems` are equal in length and content

It differs from `FieldType.Euqal` as follows:
1. Do not check `Flen`
2. Do not check tp for integer types

Integer types include: mysql.TypeTiny, mysql.TypeShort, mysql.TypeInt24, mysql.TypeLong, mysql.TypeLonglong

Because integer types are stored in chunks as 64-bit integers, and the original type and conversion type are checked at the same time when inserted, there is no problem with type conversion.

Check the correctness of `Flen` for all types:
1. Value
- BIT: Two checks will be performed.
- BOOL: flen is always 1.
- TINYINT, SMALLINT, MEDIUMINT, INTEGER, BIGINT: tidb doesn't have zerofill, flen is invalid.
- FLOAT, DOUBLE: The flen of the floating point number in tidb is only used to distinguish float/double.
- DECIMAL: Two checks will be performed.
2. Date and time
- DATE: Setting flen is not supported
- TIME, DATETIME, TIMESTAMP: optional attributes will be applied to decimal instead of flen
- YEAR: flen is always 4
3. String
- CHAR, VARCHAR, TEXT, BINARY, VARBINARY: will be checked twice
- TINYTEXT, MEDIUMTEXT, LONGTEXT, TINYBLOB, BLOB, MEDIUMBLOB, LONGBLOB, ENUM, SET: flen is not supported
4. JSON: No flen
