### PR TITLE
br: add option to test encryption for all br int tests

### LINKED ISSUE #56433: br: add option to enable local encryption for all integration tests
## Enhancement

Add option to enable local encryption for all integration tests for regression testing

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #56433

Problem Summary:

### What changed and how does it work?

```
1. Add option to enable full/log backup restore encryption for all integration tests
2. Validate files are actually encrypted by reading sst files and validate its magic number footer and read log files and validate its Zstd compression format. Encrypted files should be a random blob and not able to identify any structured format   
```
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/tests/utils.go [hunk 1]
```diff
@@ -0,0 +1,207 @@
...
+)
+
+const (
+	cmdValidateBackupFiles = "validateBackupFiles"
+	extSST                 = ".sst"
+	extLOG                 = ".log"
+)
+
+func main() {
+	if len(os.Args) < 2 {
```
Comment (YuJuncen) [inline br/tests/utils.go:24]: You may use [`cobra.Command`](https://pkg.go.dev/github.com/spf13/cobra#Command) instead of manually parse the command.

File: br/tests/utils.go [hunk 2]
```diff
@@ -0,0 +1,207 @@
...
+	return checkCompressionAndEncryption(storagePath, *encryptionArg)
+}
+
+func parseCommand(cmd string) (string, bool) {
+	args := strings.Fields(cmd)
+	hasBackupOrRestore := false
+	storagePath := ""
+
+	for i, arg := range args {
+		if arg == "backup" || arg == "restore" {
```
Comment (YuJuncen) [inline br/tests/utils.go:77]: Perhaps verifying backup is enough? As restore in fact contributes nothing to the files to be checked.

File: br/tests/utils.go [hunk 3]
```diff
@@ -0,0 +1,207 @@
...
+			hasBackupOrRestore = true
+		}
+		if arg == "-s" && i+1 < len(args) && strings.HasPrefix(args[i+1], "local://") {
```
Comment (YuJuncen) [inline br/tests/utils.go:80]: Maybe also handle `--storage`?

File: tests/_utils/run_br [hunk 4]
```diff
@@ -20,4 +20,4 @@ br.test -test.coverprofile="$COV_DIR/cov.$TEST_NAME.$$.out.log" DEVEL "$@" \
     -L "info" \
     --ca "$TEST_DIR/certs/ca.pem" \
     --cert "$TEST_DIR/certs/br.pem" \
-    --key "$TEST_DIR/certs/br.key"
+    --key "$TEST_DIR/certs/br.key" \
```
Comment (YuJuncen) [inline tests/_utils/run_br:23]: Maybe keep the empty line at the end of file.

File: br/tests/run.sh [hunk 5]
```diff
@@ -48,6 +48,24 @@ start_services $@
...
+# generate local disk master key file to enable local encryption
+MASTER_KEY_DIR="$TEST_DIR/master_key"
+mkdir -p "$MASTER_KEY_DIR"
+openssl rand -hex 32 > "$MASTER_KEY_DIR/master.key"
+MASTER_KEY_PATH="local:///$MASTER_KEY_DIR/master.key"
+
+ENCRYPTION_ARGS="--crypter.method aes128-ctr --crypter.key 0123456789abcdef0123456789abcdef --master-key-crypter-method AES256-CTR --master-key $MASTER_KEY_PATH"
+
+# plaintext data key
+#ENCRYPTION_ARGS="--crypter.method aes128-ctr --crypter.key 0123456789abcdef0123456789abcdef --log.crypter.method AES256-CTR --log.crypter.key 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
```
Comment (YuJuncen) [inline br/tests/run.sh:65]: Maybe remove this if it isn't needed.

**Review by YuJuncen — COMMENTED** [review]
rest lgtm

File: br/tests/utils.go (hunk 1 above)
Comment (Tristan1900) [reply br/tests/utils.go:24]: gotcha

File: br/tests/utils.go (hunk 2 above)
Comment (Tristan1900) [reply br/tests/utils.go:77]: I should add a comment for the code here.
For the full backup we can check the storage encryption status once the command is complete since it's a blocking call, but for log backup I believe we need some extra logic to wait for it to generate some files. So my approach is to verify log backup files before doing restore, making sure the files are actually encrypted. Let me know what you think!

File: tests/_utils/run_br (hunk 4 above)
Comment (Tristan1900) [reply tests/_utils/run_br:23]: right, I added logic and later removed, need to revert it

File: br/tests/run.sh (hunk 5 above)
Comment (Tristan1900) [reply br/tests/run.sh:65]: this is sort of a placeholder if we want to test the plaintext case, we can uncomment it and run the test. The entire tests will be run as needed, not by default for every commit per discussion with Brian, but I don't think it will hurt if we just enable encryption by default, let me know your thoughts.!

**Comment by purelind** [comment]
Please wait for this PR https://github.com/pingcap/tidb/pull/51126 to be merged first.

File: br/tests/run.sh (hunk 5 above)
Comment (YuJuncen) [reply br/tests/run.sh:65]: Perhaps add some hints about when and hot to use it(Say, `# If you want to specify a plaintext data key, uncomment and modify this.? Or it looks pretty like temporary code during developing...

File: br/tests/utils.go (hunk 2 above)
Comment (YuJuncen) [reply br/tests/utils.go]: LGTM

**Review by YuJuncen — APPROVED** [review]

File: br/tests/run.sh (hunk 5 above)
Comment (Tristan1900) [reply br/tests/run.sh:65]: sounds good!

**Review by BornChanger — APPROVED** [review]
