### PR TITLE
ddl: Regenerating AutoIDs for _tidb_rowid during Reorganize Partition

### LINKED ISSUE #53385: Will lose rows after execute `remove partitioning` on a partition table with `exchange partition`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (id int not null, store_id int not null )  partition by range (store_id) (partition p0 values less than (6), partition p1 values less than (11), partition p2 values less than (16), partition p3 values less than (21) );
create table t1(id int not null, store_id int not null);
insert into t values (1, 1);
insert into t values (2, 17);
insert into t1 values (0, 18);
alter table t exchange partition p3 with table t1;
alter table t remove partitioning;
select * from t;
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t;
+----+----------+
| id | store_id |
+----+----------+
|  1 |        1 |
|  0 |       18 |
+----+----------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t;
+----+----------+
| id | store_id |
+----+----------+
|  0 |       18 |
+----+----------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.2.0-alpha-192-g397a460dd0
Edition: Community
Git Commit Hash: 397a460dd067986d585d71a729a51b9e77a4c7ac
Git Branch: master
UTC Build Time: 2024-05-20 06:27:50
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.04 sec)
```

<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

When EXCHANGE PARTITION is used, the _tidb_rowid from the exchanged table, may conflict with rows in other partitions, which can collide during REORGANIZE PARTITION or REMOVE PARTITIONING since they keep the _tidb_rowid but will be placed in the same physical partition/table.

Solution:
Generate new _tidb_rowid for each row during the data reorganization phase.

Issue Number: close #53385

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/partition.go [hunk 1]
```diff
@@ -3374,9 +3374,35 @@ func (w *reorgPartitionWorker) fetchRowColVals(txn kv.Transaction, taskRange reo
...
+			var newKey kv.Key
+			if w.reorgedTbl.Meta().PKIsHandle || w.reorgedTbl.Meta().IsCommonHandle {
+				pid := p.GetPhysicalID()
+				newKey = tablecodec.EncodeTablePrefix(pid)
+				newKey = append(newKey, recordKey[len(newKey):]...)
+			} else {
+				// Non-clustered table / not unique _tidb_rowid for the whole table
+				// Generate new _tidb_rowid if exists.
+				// Due to EXCHANGE PARTITION, the existing _tidb_rowid may collide between partitions!
+				stmtCtx := w.sessCtx.GetSessionVars().StmtCtx
```
Comment (Defined2014) [inline pkg/ddl/partition.go:3386]: I'm not sure, will this cause data races between different reorg workers?

Comment (mjonss) [reply pkg/ddl/partition.go:3386]: I think each worker `w` should have its own context and session vars, and which will be used as a cache for the worker, and get globally allocated ids from `tables.AllocHandleIDs()` which is protected by a lock.

Anyway to verify/test this?

**Review by Defined2014 — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM
