### PR TITLE
executor, session, sessionctx: fix the error message of read-only variable is corrupted

### LINKED ISSUE #21944: The error message of read-only variable is corrupted
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
mysql> set @@tidb_current_ts=1;
ERROR 1621 (HY000): %s variable '%s' is read-only. Use SET %s to assign the value
```

### 2. What did you expect to see? (Required)
```mysql
mysql> set @@version='123';
ERROR 1238 (HY000): Variable 'version' is a read only variable
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #21944  

Problem Summary:

### What is changed and how it works?

What's Changed:
fix the error message of read-only variable is corrupted
How it Works:
format the error message when read-only variable is set

### Check List 

Tests 
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by TszKitLo40** [comment]
PTAL @bb7133

**Comment by morgo** [comment]
LGTM

File: session/session_test.go [hunk 1]
```diff
@@ -3804,3 +3804,9 @@ func (s *testSessionSerialSuite) TestDefaultWeekFormat(c *C) {
 	tk2 := testkit.NewTestKitWithInit(c, s.store)
 	tk2.MustQuery("select week('2020-02-02'), @@default_week_format, week('2020-02-02');").Check(testkit.Rows("6 4 6"))
 }
+
+func (s *testSessionSerialSuite) TestIssue21944(c *C) {
+	tk1 := testkit.NewTestKitWithInit(c, s.store)
+	_, err := tk1.Exec("set @@tidb_current_ts=1;")
+	c.Assert(err.Error(), Equals, "[variable:1621]tidb_current_ts variable 'tidb_current_ts' is read-only. Use SET tidb_current_ts to assign the value")
```
Comment (SunRunAway) [inline session/session_test.go:3811]: This is different from the expected error message described in https://github.com/pingcap/tidb/issues/21944

File: sessionctx/variable/session.go [hunk 2]
```diff
@@ -1432,7 +1432,7 @@ func (s *SessionVars) SetSystemVar(name string, val string) error {
 	case TiDBDMLBatchSize:
 		s.DMLBatchSize = int(tidbOptInt64(val, DefOptCorrelationExpFactor))
 	case TiDBCurrentTS, TiDBLastTxnInfo, TiDBConfig:
-		return ErrReadOnly
+		return ErrReadOnly.GenWithStackByArgs(name, name, name)
```
Comment (morgo) [inline sessionctx/variable/session.go:1435]: Is it possible to remove the `case`, and instead set the `ReadOnly: true` property of each of these sysvars? i.e. see the example in https://github.com/pingcap/tidb/issues/21943#issuecomment-749646780

By moving all sysVar validation to the struct, it makes it easier for plugins to be first class citizens.

**Comment by TszKitLo40** [comment]
PTAL @SunRunAway @morgo

File: sessionctx/variable/sysvar.go [hunk 3]
```diff
@@ -1012,7 +1012,7 @@ var defaultSysVars = []*SysVar{
 	{Scope: ScopeSession, Name: TiDBBatchDelete, Value: BoolToOnOff(DefBatchDelete), Type: TypeBool},
 	{Scope: ScopeSession, Name: TiDBBatchCommit, Value: BoolToOnOff(DefBatchCommit), Type: TypeBool},
 	{Scope: ScopeGlobal | ScopeSession, Name: TiDBDMLBatchSize, Value: strconv.Itoa(DefDMLBatchSize), Type: TypeUnsigned, MinValue: 0, MaxValue: math.MaxUint64},
-	{Scope: ScopeSession, Name: TiDBCurrentTS, Value: strconv.Itoa(DefCurretTS)},
+	{Scope: ScopeSession, Name: TiDBCurrentTS, Value: strconv.Itoa(DefCurretTS), ReadOnly: true},
```
Comment (morgo) [inline sessionctx/variable/sysvar.go:1015]: The sysvars `TiDBConfig` also needs the `ReadOnly` property set, since the `switch` statement that containts it has been removed. It looks like it is already correct with `TiDBLastTxnInfo`.

File: sessionctx/variable/sysvar.go [hunk 4]
```diff
@@ -107,7 +107,7 @@ type SysVar struct {
 func (sv *SysVar) ValidateFromType(vars *SessionVars, value string, scope ScopeFlag) (string, error) {
 	// Some sysvars are read-only. Attempting to set should always fail.
 	if sv.ReadOnly || sv.Scope == ScopeNone {
-		return value, ErrReadOnly.GenWithStackByArgs(sv.Name)
+		return value, errors.Errorf("Variable '%s' is a read only variable", sv.Name)
```
Comment (morgo) [inline sessionctx/variable/sysvar.go:110]: The errors.Errorf will change the error code to the "unspecified" value. I tested this in MySQL, and the expected error code is 1238:

```sql
mysql [localhost:8022] {msandbox} (test) > set global version_comment = '1234';
ERROR 1238 (HY000): Variable 'version_comment' is a read only variable
```

I believe this should return the correct code:
```suggestion
		return value, ErrIncorrectScope.GenWithStackByArgs(sv.Name, "read only")
```
(please test it)

Comment (TszKitLo40) [reply sessionctx/variable/sysvar.go]: I have tested it and the error should be `ErrIncorrectScope` and fixed the tests.

**Comment by morgo** [comment]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
