### PR TITLE
*: fix a data race on TestConnExecutionTimeout

### LINKED ISSUE #35922: Data race on server TestConnExecutionTimeout function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
make failpoint-enable
cd server
go test -race  -run TestConnExecutionTimeout
```

### 2. What did you expect to see? (Required)

No data race

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c005377768 by goroutine 7:
  github.com/pingcap/tidb/executor.ResetContextOfStmt()
      /home/genius/project/src/github.com/pingcap/tidb/executor/executor.go:1986 +0x2f6f
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      /home/genius/project/src/github.com/pingcap/tidb/session/session.go:1912 +0x384
  github.com/pingcap/tidb/testkit.(*TestKit).Exec()
      /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:218 +0x714
  github.com/pingcap/tidb/testkit.(*TestKit).MustExec()
      /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:92 +0x99
  github.com/pingcap/tidb/server.TestConnExecutionTimeout()
      /home/genius/project/src/github.com/pingcap/tidb/server/conn_test.go:728 +0x9c9
  github.com/pingcap/failpoint.(*Failpoint).Enable()
      /home/genius/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20220423142525-ae43b7f4e5c3/failpoint.go:54 +0x44
  github.com/pingcap/failpoint.(*Failpoints).Enable()
      /home/genius/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20220423142525-ae43b7f4e5c3/failpoints.go:105 +0x276
  github.com/pingcap/failpoint.Enable()
      /home/genius/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20220423142525-ae43b7f4e5c3/failpoints.go:222 +0xb1
  github.com/pingcap/tidb/server.TestConnExecutionTimeout()
      /home/genius/project/src/github.com/pingcap/tidb/server/conn_test.go:688 +0xb2
  testing.tRunner()
      /home/genius/project/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/genius/project/go/src/testing/testing.go:1486 +0x47

Previous read at 0x00c005377768 by goroutine 130:
  github.com/pingcap/tidb/server.killConn()
      /home/genius/project/src/github.com/pingcap/tidb/server/server.go:724 +0x11d
  github.com/pingcap/tidb/server.(*Server).Kill()
      /home/genius/project/src/github.com/pingcap/tidb/server/server.go:703 +0x41a
  github.com/pingcap/tidb/util/expensivequery.(*Handle).Run()
      /home/genius/project/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:76 +0x7e2
  github.com/pingcap/tidb/server.TestConnExecutionTimeout.func2()
      /home/genius/project/src/github.com/pingcap/tidb/server/conn_test.go:716 +0x39

Goroutine 7 (running) created at:
  testing.(*T).Run()
      /home/genius/project/go/src/testing/testing.go:1486 +0x724
  testing.runTests.func1()
      /home/genius/project/go/src/testing/testing.go:1839 +0x99
  testing.tRunner()
      /home/genius/project/go/src/testing/testing.go:1439 +0x213
  testing.runTests()
      /home/genius/project/go/src/testing/testing.go:1837 +0x7e4
  testing.(*M).Run()
      /home/genius/project/go/src/testing/testing.go:1719 +0xa71
  go.uber.org/goleak.VerifyTestMain()
      /home/genius/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/server.TestMain()
      /home/genius/project/src/github.com/pingcap/tidb/server/main_test.go:73 +0xd84
  main.main()
      _testmain.go:197 +0x317

Goroutine 130 (running) created at:
  github.com/pingcap/tidb/server.TestConnExecutionTimeout()
      /home/genius/project/src/github.com/pingcap/tidb/server/conn_test.go:716 +0x7f9
  github.com/pingcap/failpoint.(*Failpoint).Enable()
      /home/genius/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20220423142525-ae43b7f4e5c3/failpoint.go:54 +0x44
  github.com/pingcap/failpoint.(*Failpoints).Enable()
      /home/genius/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20220423142525-ae43b7f4e5c3/failpoints.go:105 +0x276
  github.com/pingcap/failpoint.Enable()
      /home/genius/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20220423142525-ae43b7f4e5c3/failpoints.go:222 +0xb1
  github.com/pingcap/tidb/server.TestConnExecutionTimeout()
      /home/genius/project/src/github.com/pingcap/tidb/server/conn_test.go:688 +0xb2
  testing.tRunner()
      /home/genius/project/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/genius/project/go/src/testing/testing.go:1486 +0x47
==================
```

### 4. What is your TiDB version? (Required)

master  e50b9430fc650ce4629ead05186272ffedf014c8

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #35922

Problem Summary:

### What is changed and how it works?

This data race is introduced by https://github.com/pingcap/tidb/pull/35803/ 

There are two problems in that commit:
- data race between the been-killed session groutine and the Kill() invoker goroutine 
- background expensive query handler might kill long running DDL mistakenly

What's done in pr/35803 is that it add a check in the `Kill()` function,
and from the stmtctx if it's found to be executing DDL, the kill is changed to `CancelDDL`.

But this is not thread-safe ... check the stmtctx for it's state is not precise, 
because the stmtctx might be constantly changing...
The been-killed session update it's stmtctx and then data race from the checking process.

In this commit, to avoid the data race, I change the logic to "just set the kill flag, and let the callee do the cancel operation"

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

```
make failpoint-enable
cd server
go test -race  -run TestConnExecutionTimeout
```

No data race any more.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/ddl.go [hunk 1]
```diff
@@ -797,6 +799,27 @@ func (d *ddl) DoDDLJob(ctx sessionctx.Context, job *model.Job) error {
 			return context.Canceled
 		}
 
+		// If the connection being killed, we need to CANCEL the DDL job.
+		if atomic.LoadUint32(&sessVars.Killed) == 1 {
+			if sessVars.StmtCtx.DDLJobID != 0 {
```
Comment (xhebox) [inline ddl/ddl.go:804]: If we do killing in DDL, then can we just use `jobID` instead of `StmtCtx`?

Comment (tiancaiamao) [reply ddl/ddl.go:804]: This operation is intend to avoid repeating the `CancelDDL` calling.
`sessVars.StmtCtx.DDLJobID = 0` means maybe we have executed `CancelDDL` already.

Comment (xhebox) [reply ddl/ddl.go:804]: Got

**Review by xhebox — APPROVED** [review]

**Comment by morgo** [comment]
LGTM, thanks for fixing!

**Comment by tiancaiamao** [comment]
/hold

I need to investigate why collation test failed

**Comment by hawkingrei** [comment]
@tiancaiamao  It meets a new data race in the tidb server.

https://github.com/pingcap/tidb/issues/35979
