### PR TITLE
executor,store/copr: fix index merge, distsql request's key ranges should be sorted

### LINKED ISSUE #36632: index merge dead loop when paging is used
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[outfile.txt](https://github.com/pingcap/tidb/files/9199246/outfile.txt)
```
mysql -h 127.0.0.1 -u root -P 4000 -A test < outfile.txt
```

```
select/*+ use_index_merge(t_alias) */ * from IDT_MULTI15921STROBJSTROBJ t_alias where
    col3 <= "821:19:48" and
    (col3 <= "821:19:48" or
	  col1 in ("OFJHCEKCQGT:MXI7P3[YO4N0DF=2XJWJ4Z9Z;HQ8TMUTZV8YLQAHWJ4BDZHR3A",
		   "PXWTHJ?R]P=`Y",
		   "M5=T5FLQEZMPZAXH]4G:TSYYYVQ7O@4S6C3N8WPFKSP;SRD6VW@94BBH8XCT",
		   "P]I52Y46F?@RMOOF6;FWDTO`7FIT]R:]ELHD[CNLDSHC7FPBYOOJXLZSBV^5C^AAF6J5BCKE4V9==@H=4C]GMZXPNM",
		   "M@V^`^8I",
		   "QLDIOY[Y:JZR@OL__I^@FBO=O_?WOOR:2BE:QJC",
		   "M@HGGFM43C7",
		   "@M`IHSJQ8HBTGOS`=VW]QBMLVWN`SP;E>EEXYKV1POHTOJQPGCPVR=TYZMGWABUQR07J8U::W4",
		   "N`ZN4P@9T[JW;FR6=FA4WP@APNPG[XQVIK4]F]2>EC>JEIOXC``;;?OHP",
		   "^YSQT0]V@9TFN>^WB6G?NG@S8>VYOM;BSC@<BCQ6"));
```

### 2. What did you expect to see? (Required)

No error, get the query result

### 3. What did you see instead (Required)

This query never finish, a dead loop happen.

### 4. What is your TiDB version? (Required)

master e39ef4cae80f7001b269e934a3dc9312fb0c8477

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #36632

Problem Summary:

### What is changed and how it works?

The key range for distsql request should be sorted!
Because locate region for the key ranges use a binary search pattern.

### Check List

Tests 

- [ ] Unit test
- [X] Integration test

This bug is found by our integration test.

- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: store/copr/coprocessor.go [hunk 1]
```diff
@@ -70,6 +71,11 @@ type CopClient struct {
 
 // Send builds the request and gets the coprocessor iterator response.
 func (c *CopClient) Send(ctx context.Context, req *kv.Request, variables interface{}, option *kv.ClientSendOption) kv.Response {
+	if config.CheckTableBeforeDrop && !checkKeyRangeSorted(req.KeyRanges) {
```
Comment (wshwsh12) [inline store/copr/coprocessor.go:74]: Why we need check CheckTableBeforeDrop?

File: store/copr/coprocessor.go [hunk 2]
```diff
@@ -1360,3 +1366,21 @@ func isolationLevelToPB(level kv.IsoLevel) kvrpcpb.IsolationLevel {
 		return kvrpcpb.IsolationLevel_SI
 	}
 }
+
+func checkKeyRangeSorted(keyRanges []kv.KeyRange) bool {
```
Comment (hawkingrei) [inline store/copr/coprocessor.go:1370]: We can use this [function](https://pkg.go.dev/golang.org/x/exp/slices#IsSortedFunc) to simple code.

File: store/copr/coprocessor.go (hunk 1 above)
Comment (tiancaiamao) [reply store/copr/coprocessor.go:74]: The flag `config.CheckTableBeforeDrop`  is always false, unless you build tidb-server with:

```
WITH_CHECK=1 make server
```

It's really hard to ensure this assumption, but if I always check it, the performance cost is unacceptable.
So do it when build with WITH_CHECK

File: store/copr/coprocessor.go (hunk 2 above)
Comment (tiancaiamao) [reply store/copr/coprocessor.go]: Done

File: store/copr/coprocessor.go [hunk 3]
```diff
@@ -70,6 +71,18 @@ type CopClient struct {
 
 // Send builds the request and gets the coprocessor iterator response.
 func (c *CopClient) Send(ctx context.Context, req *kv.Request, variables interface{}, option *kv.ClientSendOption) kv.Response {
+	if slices.IsSortedFunc(req.KeyRanges, func(i, j kv.KeyRange) bool {
```
Comment (hawkingrei) [inline store/copr/coprocessor.go:74]: There are two different less functions for the KeyRanges?

**Comment by tiancaiamao** [comment]
Verified in the integration test, now just keep the fixing part.
PTAL @hawkingrei @wshwsh12 @XuHuaiyu

File: executor/distsql_test.go [hunk 4]
```diff
@@ -581,3 +582,49 @@ func TestAdaptiveClosestRead(t *testing.T) {
 	// 2 IndexScan with cost 19/56, 2 TableReader with cost 32.5/65.
 	checkMetrics("select/* +USE_INDEX_MERGE(t) */ id from t use index(`idx_v_s1`) use index(idx_s2) where (s1 < 3 and v > 0) or s2 = 3;", 3, 1)
 }
+
+func TestCoprocessorPagingReqKeyRangeSorted(t *testing.T) {
```
Comment (tiancaiamao) [inline executor/distsql_test.go:586]: The added test can only cover (literally) the added code.
It can't prevent regression in the future when code changes.

**Review by XuHuaiyu — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]
