### PR TITLE
Lightning: Make sure we are using default block size of 16KB if user does not specify one.

### LINKED ISSUE #59947: lightning OOM during write/ingest to TiKV when import large mount of data
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

the issue happened in two cases, one 2TB data, another 12TB data, both are using v8.1.2 version. current guess of the root cause is that pebble might have some bug, causes memory usage burst, and OOM, as the time window is very short, and pebble might allocate memory using CGO, we hasn't got any useful heap profile.
and we found that in v8.1.1 we have upgrade pebble to v1.1 in https://github.com/pingcap/tidb/commit/888a58b0064b060a136332c583e08ac2a6199fd4 since v8.1.1. so we try import the same data using v7.5.5, and it success.

we found a pebble OOM issue https://github.com/cockroachdb/pebble/issues/3039, it might related

so the trigger condition might include
- import large data set, say 2T. (we have tested with smaller data-set, say several hundreds of GB, no such issue)
- using version >= v8.1.1 which have upgraded pebble

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
oom on ingest
### 4. What is your TiDB version? (Required)
v8.1.2

### PR DESCRIPTION
**Pull request by OliverS929**
### What problem does this PR solve?

Issue Number: close #59947

Problem Summary:
Make we are using a sufficient default block size. Ref https://github.com/pingcap/tidb/pull/49514

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  > To test the specific issue addressed in this PR, I used a ~1.4TB dataset consisting mostly of duplicate data. Before the fix, memory usage spiked during the ingest phase due to the large index metadata loaded by Pebble, causing OOM kills on a 16c64g VM. With the fix, memory consumption remained stable, staying below 17GB and leading to no disastrous memory spikes.
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Benjamin2037** [comment]
Please make sure add enough test case to avoid regression later.

File: pkg/lightning/backend/local/engine.go [hunk 1]
```diff
@@ -1397,7 +1400,14 @@ func (w *Writer) addSST(ctx context.Context, meta *sstMeta) error {
 
 func (w *Writer) createSSTWriter() (*sstWriter, error) {
 	path := filepath.Join(w.engine.sstDir, uuid.New().String()+".sst")
-	writer, err := newSSTWriter(path, w.engine.config.BlockSize)
+
+	blockSize := w.engine.config.BlockSize
+	// Logic to check the block size we are using is at least 16KB.
+	if blockSize <= 0 {
```
Comment (lance6716) [inline pkg/lightning/backend/local/engine.go:1406]: as the title said, should you change it to

```
blockSize = max(blockSize, DefaultBlockSize)
```

?

**Review by lance6716 — APPROVED** [review]

File: pkg/lightning/backend/local/engine_test.go [hunk 2]
```diff
@@ -240,3 +241,35 @@ func TestIterOutputHasUniqueMemorySpace(t *testing.T) {
 	// after iter closed, the memory buffer of iter goes to pool
 	require.Greater(t, pool.TotalSize(), int64(0))
 }
+
+func TestCreateSSTWriterDefaultBlockSize(t *testing.T) {
```
Comment (Benjamin2037) [inline pkg/lightning/backend/local/engine_test.go:245]: Please add comment for testcase

File: pkg/lightning/backend/local/engine.go [hunk 3]
```diff
@@ -59,6 +59,9 @@ var (
 	normalIterStartKey = []byte{1}
 )
 
+// DefaultBlockSize ensures we are using a block size larger than 16KB, whereas 4KB is the default block size of Pebble.
```
Comment (Benjamin2037) [inline pkg/lightning/backend/local/engine.go:62]: Can we also explain why 4KB pebble default value is not a good choice? and what problem will it cause?

File: lightning/pkg/importer/table_import.go [hunk 4]
```diff
@@ -669,6 +669,7 @@ func (tr *TableImporter) preprocessEngine(
 		dataEngineCfg.Local.Compact = true
 		dataEngineCfg.Local.CompactConcurrency = 4
 		dataEngineCfg.Local.CompactThreshold = local.CompactionUpperThreshold
+		dataEngineCfg.Local.BlockSize = int(rc.cfg.TikvImporter.BlockSize)
```
Comment (D3Hunter) [inline lightning/pkg/importer/table_import.go:672]: move it to above, here is a conditional branch
```
	dataEngineCfg := &backend.EngineConfig{
		TableInfo: tr.tableInfo,
	}
```

File: pkg/lightning/backend/local/engine.go [hunk 5]
```diff
@@ -59,6 +59,9 @@ var (
...
+var DefaultBlockSize = 16 * 1024
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/engine.go:63]: define it inside `config.go` like others

**Review by D3Hunter — COMMENTED** [review]
can you write the detail of `manual test`?

File: pkg/lightning/backend/local/engine.go [hunk 6]
```diff
@@ -1423,6 +1426,12 @@ func newSSTWriter(path string, blockSize int) (*sstable.Writer, error) {
 	if err != nil {
 		return nil, errors.Trace(err)
 	}
+
+	// Logic to check the block size we are using is 16KB by default.
+	if blockSize <= 0 {
```
Comment (Benjamin2037) [inline pkg/lightning/backend/local/engine.go:1431]: Should we also check even this blocksize set, we still has risk to OOM?

**Comment by OliverS929** [comment]
> can you write the detail of `manual test`?

Sure, I can provide a brief overview of the dataset size and test structure. However, I’m concerned that sharing further details in this PR might not be appropriate, as they could involve confidential information related to specific customer use cases.

File: pkg/lightning/backend/local/engine_test.go [hunk 7]
```diff
@@ -240,3 +242,36 @@ func TestIterOutputHasUniqueMemorySpace(t *testing.T) {
...
+	require.NoError(t, err)
+	require.NotNil(t, sstWriter)
+
+	// blockSize is a private field of sstWriter.writer, so we use reflection to access the private field blockSize
+	writerValue := reflect.ValueOf(sstWriter.writer).Elem()
+	blockSizeField := writerValue.FieldByName("blockSize")
+	require.True(t, blockSizeField.IsValid(), "blockSize field should be valid")
+	require.Equal(t, config.DefaultBlockSize, int(blockSizeField.Int()))
+
+	// Clean up
```
Comment (Benjamin2037) [inline pkg/lightning/backend/local/engine_test.go:274]: why above comment withnot upper case，here the comment with upper case start？please make consistency.

**Comment by D3Hunter** [comment]
> > can you write the detail of `manual test`?
> 
> Sure, I can provide a brief overview of the dataset size and test structure. However, I’m concerned that sharing further details in this PR might not be appropriate, as they could involve confidential information related to specific customer use cases.

you can ignore the customer part, just describe the steps and results from tech point of view

File: pkg/lightning/backend/local/engine.go [hunk 8]
```diff
@@ -1423,6 +1423,16 @@ func newSSTWriter(path string, blockSize int) (*sstable.Writer, error) {
...
 		return nil, errors.Trace(err)
 	}
+
+	// Logic to ensure the default block size is set to 16KB.
+	// If a smaller block size is used (e.g., 4KB, the default for Pebble),
+	// a single large SST file may generate a disproportionately large index block,
+	// potentially causing a memory spike and leading to an Out of Memory (OOM) scenario.
+	// If the user specifies a smaller block size, respect their choice.
+	if blockSize <= 0 {
+		blockSize = config.DefaultBlockSize
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/engine.go:1433]: can you also replace the literal inside `NewConfig`, `BlockSize:               16 * 1024,`

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

**Comment by OliverS929** [comment]
> > > can you write the detail of `manual test`?
> > 
> > 
> > Sure, I can provide a brief overview of the dataset size and test structure. However, I’m concerned that sharing further details in this PR might not be appropriate, as they could involve confidential information related to specific customer use cases.
> 
> you can ignore the customer part, just describe the steps and results from tech point of view

Sure. To test the specific issue addressed in this PR, I used a ~1.4TB dataset consisting mostly of duplicate data. Before the fix, memory usage spiked during the ingest phase due to the large index metadata loaded by Pebble, causing OOM kills on a 16c64g VM. With the fix, memory consumption remained stable, staying below 17GB and leading to no disastrous memory spikes.

**Review by wjhuang2016 — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
> > > > can you write the detail of `manual test`?
> > > 
> > > 
> > > Sure, I can provide a brief overview of the dataset size and test structure. However, I’m concerned that sharing further details in this PR might not be appropriate, as they could involve confidential information related to specific customer use cases.
> > 
> > 
> > you can ignore the customer part, just describe the steps and results from tech point of view
> 
> Sure. To test the specific issue addressed in this PR, I used a ~1.4TB dataset consisting mostly of duplicate data. Before the fix, memory usage spiked during the ingest phase due to the large index metadata loaded by Pebble, causing OOM kills on a 16c64g VM. With the fix, memory consumption remained stable, staying below 17GB and leading to no disastrous memory spikes.

please add it to the PR description, under `[ ] manual test` section

**Comment by Benjamin2037** [comment]
Please remember  add integration test.

**Comment by OliverS929** [comment]
> > > > > can you write the detail of `manual test`?
> > > > 
> > > > 
> > > > Sure, I can provide a brief overview of the dataset size and test structure. However, I’m concerned that sharing further details in this PR might not be appropriate, as they could involve confidential information related to specific customer use cases.
> > > 
> > > 
> > > you can ignore the customer part, just describe the steps and results from tech point of view
> > 
> > 
> > Sure. To test the specific issue addressed in this PR, I used a ~1.4TB dataset consisting mostly of duplicate data. Before the fix, memory usage spiked during the ingest phase due to the large index metadata loaded by Pebble, causing OOM kills on a 16c64g VM. With the fix, memory consumption remained stable, staying below 17GB and leading to no disastrous memory spikes.
> 
> please add it to the PR description, under `[ ] manual test` section

Done.
