### PR TITLE
disttask: fix scope can't set different value

### LINKED ISSUE #52441: disttask: support multiple access point natively
## Enhancement
For cloud we want to support multiple access endpoints, each of it will have a different `tidb_service_scope`. Apps might connect to different endpoint, dist task submitted from different endpoint should not interference with each other:
1. We want subtasks run on nodes with the same `tidb_service_scope` as the node which submits the job.
2. Make [tidb_enable_dist_task](https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_dist_task-new-in-v710) default to true.

although we separate the tasks from tidb side, the pd/tikv is still shared by all endpoints and affects each other.

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #52441 

Problem Summary:

### What changed and how does it work?
1. Make tidb_service_scope can be set to different values.
2. add target scope for each tasks
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/session/bootstrap.go [hunk 1]
```diff
@@ -3073,6 +3080,14 @@ func upgradeToVer195(s sessiontypes.Session, ver int64) {
 	doReentrantDDL(s, DropMySQLIndexUsageTable)
 }
 
+func upgradeToVer196(s sessiontypes.Session, ver int64) {
+	if ver >= version196 {
+		return
+	}
+
+	doReentrantDDL(s, "ALTER TABLE mysql.tidb_global_task ADD COLUMN target_scope VARCHAR(256);")
```
Comment (D3Hunter) [inline pkg/session/bootstrap.go:3088]: history table？

File: pkg/disttask/framework/handle/handle_test.go [hunk 2]
```diff
@@ -48,7 +48,7 @@ func TestHandle(t *testing.T) {
 	storage.SetTaskManager(mgr)
 
 	// no scheduler registered
-	task, err := handle.SubmitTask(ctx, "1", proto.TaskTypeExample, 2, proto.EmptyMeta)
+	task, err := handle.SubmitTask(ctx, "1", proto.TaskTypeExample, 2, "", proto.EmptyMeta)
```
Comment (Benjamin2037) [inline pkg/disttask/framework/handle/handle_test.go:51]: Do we have some test cases for others tidb-service-scope values for example "test1" etc.

Comment (ywqzzy) [reply pkg/disttask/framework/handle/handle_test.go:51]: In TestTargetScope, we generate random test cases when trigger ci.

File: pkg/disttask/framework/proto/task.go [hunk 3]
```diff
@@ -93,6 +93,9 @@ type TaskBase struct {
 	// Concurrency controls the max resource usage of the task, i.e. the max number
 	// of slots the task can use on each node.
 	Concurrency int
+	// TargetScope indicates that the task should be running on tidb nodes which
+	// contain the tidb_service_scope=TargetScope label.
```
Comment (D3Hunter) [inline pkg/disttask/framework/proto/task.go:97]:
```suggestion
	// contain the tidb_service_scope=TargetScope label.
	// to compatible with previous version, if it's "" or "background", the task try run on nodes of "background" scope,
	// if there is no such nodes, will try nodes of "" scope
```

File: pkg/disttask/framework/scheduler/nodes.go [hunk 4]
```diff
@@ -116,50 +117,82 @@ func (nm *NodeManager) maintainLiveNodes(ctx context.Context, taskMgr TaskManage
...
+		if node.Role == "background" {
+			haveBackground = true
+		}
+	}
+
+	for _, node := range nodes {
+		if haveOther {
+			if node.Role == targetScope {
+				nodeIDs = append(nodeIDs, node.ID)
+			}
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/nodes.go:184]: if `haveOther=true` and `targetScope=""`, we will always enter this branch

**Review by D3Hunter — COMMENTED** [review]
24/52

File: cmd/tidb-server/main.go [hunk 5]
```diff
@@ -677,14 +677,12 @@ func overrideConfig(cfg *config.Config, fset *flag.FlagSet) {
...
 	if actualFlags[nmTiDBServiceScope] {
-		scope, ok := distroleutil.ToTiDBServiceScope(*serviceScope)
-		if !ok {
-			err := fmt.Errorf("incorrect value: `%s`. %s options: %s",
-				*serviceScope,
-				nmTiDBServiceScope, `"", background`)
+		if servicescope.IsValidServiceScope(*serviceScope) {
+			cfg.Instance.TiDBServiceScope = *serviceScope
+		} else {
+			err = fmt.Errorf("the tidb-service-scope value '%s' is invalid. It must be 64 characters or fewer and consist only of letters (a-z, A-Z), numbers (0-9), hyphens (-), and underscores (_)", *serviceScope)
```
Comment (Benjamin2037) [inline cmd/tidb-server/main.go:683]: When you limit value length, you should sync with @frank945946？and also need to change the doc to mention it.

File: pkg/disttask/framework/scheduler/nodes.go (hunk 4 above)
Comment (ywqzzy) [reply pkg/disttask/framework/scheduler/nodes.go:184]: nodes with  node1="", node2="", node3="xxx", targetScope="",  filterByScope return node1, node2

File: pkg/disttask/framework/scheduler/nodes_test.go [hunk 6]
```diff
@@ -97,24 +97,93 @@ func TestMaintainManagedNodes(t *testing.T) {
...
+		},
+		{
+			nodes:         []proto.ManagedNode{mockManagedNode("1", "1"), mockManagedNode("2", ""), mockManagedNode("3", "background")},
+			targetScope:   "",
+			expectedNodes: []string{"2"},
+		},
+	}
+
+	for _, cas := range cases {
+		require.Equal(t, cas.expectedNodes, filterByScope(cas.nodes, cas.targetScope))
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/nodes_test.go:187]:
```suggestion
	for i, cas := range cases {
		t.Run(fmt.Sprintf("case-%d", i), func(t *testing.T) {
			require.Equal(t, cas.expectedNodes, filterByScope(cas.nodes, cas.targetScope))
		})
```

File: pkg/disttask/framework/scheduler/nodes.go (hunk 4 above)
Comment (D3Hunter) [reply pkg/disttask/framework/scheduler/nodes.go:184]: for this case, it should return `3`
```
nodes:         []proto.ManagedNode{mockManagedNode("1", "1"), mockManagedNode("2", ""), mockManagedNode("3", "background")},
targetScope:   "",
```

File: pkg/disttask/importinto/mock/import_mock.go [hunk 7]
```diff
@@ -13,7 +13,7 @@ import (
 	context "context"
 	reflect "reflect"
 
-	"github.com/pingcap/tidb/pkg/lightning/backend"
+	backend "github.com/pingcap/tidb/pkg/lightning/backend"
```
Comment (D3Hunter) [inline pkg/disttask/importinto/mock/import_mock.go:16]: can be reverted?

File: pkg/session/bootstrap.go [hunk 8]
```diff
@@ -3073,6 +3081,15 @@ func upgradeToVer195(s sessiontypes.Session, ver int64) {
...
```
Comment (D3Hunter) [inline pkg/session/bootstrap.go:3089]: should add it after `step`, below too

File: pkg/sessionctx/variable/sysvar.go [hunk 9]
```diff
@@ -3136,11 +3136,10 @@ var defaultSysVars = []*SysVar{
 	},
 	{Scope: ScopeInstance, Name: TiDBServiceScope, Value: "", Type: TypeStr,
 		Validation: func(_ *SessionVars, normalizedValue string, originalValue string, _ ScopeFlag) (string, error) {
-			_, ok := distroleutil.ToTiDBServiceScope(originalValue)
-			if !ok {
-				err := fmt.Errorf("incorrect value: `%s`. %s options: %s",
+			if !servicescope.IsValidServiceScope(originalValue) {
+				err := fmt.Errorf("incorrect value: `%s`. %s. It must be 64 characters or fewer and consist only of letters (a-z, A-Z), numbers (0-9), hyphens (-), and underscores (_)",
```
Comment (D3Hunter) [inline pkg/sessionctx/variable/sysvar.go:3140]: change to `CheckServiceScope` which returns error if not valid? so we can reuse the message as in main.go

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/session/bootstrap.go [hunk 10]
```diff
@@ -583,6 +583,7 @@ const (
 		meta LONGBLOB,
 		concurrency INT(11),
 		step INT(11),
+		target_scope VARCHAR(256),
```
Comment (D3Hunter) [inline pkg/session/bootstrap.go:586]:
```suggestion
		target_scope VARCHAR(256) default "",
```
for previous version tasks set it to "", to avoid check IsNull in Row2Task

File: pkg/session/bootstrap.go [hunk 11]
```diff
@@ -603,6 +604,7 @@ const (
...
```
Comment (D3Hunter) [inline pkg/session/bootstrap.go:607]: need change this too

**Review by D3Hunter — APPROVED** [review]
rest lgtm

File: pkg/util/servicescope/scope.go [hunk 12]
```diff
@@ -0,0 +1,29 @@
...
+package servicescope
+
+import (
+	"fmt"
+	"regexp"
+)
+
+// CheckServiceScope check if the tidb-service-scope set by users is valid.
+func CheckServiceScope(scope string) error {
+	re := regexp.MustCompile(`^[a-zA-Z0-9_-]{0,64}$`)
```
Comment (tangenta) [inline pkg/util/servicescope/scope.go:24]: Maybe move this to a global variable and initialize it in `init()`?

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by YuJuncen — APPROVED** [review]
