### PR TITLE
br: make log command visible in cli

### LINKED ISSUE #50927: br: expose log command in br -h output
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run br clp with help
`br -h`

### 2. What did you expect to see? (Required)

Available commands section contains log command.

### 3. What did you see instead (Required)

img_v3_027l_b9dd80db-b142-4f3d-830a-2b420bba52fg

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by RidRisR**
### What problem does this PR solve?

Issue Number: close #50927 

Problem Summary:

The command was set `hidden`, now it has been set visible.

### Check List

Tests 
- [x] Manual test (add detailed scripts or steps below)
image

  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Now the candidate command "log" in br is visible in help.
```

### CODE REVIEW

**Comment by BornChanger** [comment]
@RidRisR please paste your screen shots of your manual testing.

**Comment by RidRisR** [comment]
> @RidRisR please paste your screen shots of your manual testing and also fill the release notes.



> @RidRisR please paste your screen shots of your manual testing and also fill the release notes.

done

**Review by BornChanger — APPROVED** [review]

File: br/cmd/br/stream.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func NewStreamCommand() *cobra.Command {
 		command.Root().HelpFunc()(command, strings)
 	})
 
-	command.Hidden = true
+	command.Hidden = false
```
Comment (YuJuncen) [inline br/cmd/br/stream.go:60]: It seems the default value is `false`?

**Review by YuJuncen — APPROVED** [review]
