### PR TITLE
stats: Correctly set stats version after running ANALYZE

### LINKED ISSUE #64400: After running ANALYZE, the stats version of the table is still 0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```go
func TestAutoAnalyzeAfterAnalyzeVersionChange(t *testing.T) {
	store, dom := testkit.CreateMockStoreAndDomain(t)
	tk := testkit.NewTestKit(t, store)
	h := dom.StatsHandle()

	// Trigger the sync load by query.
	// set lease > 0 to trigger on-demand stats load.
	h.SetLease(time.Millisecond)
	// Set analyze version to 1.
	tk.MustExec("set @@tidb_analyze_version = 1")
	tk.MustExec("use test")
	tk.MustExec("create table t (a int, b int, index idx(a));")
	tk.MustExec("insert into t values (1, 2);")
	tk.MustExec("analyze table t")
	tbl, err := dom.InfoSchema().TableByName(context.Background(), ast.NewCIStr("test"), ast.NewCIStr("t"))
	require.NoError(t, err)
	tableInfo := tbl.Meta()
	statsTbl := h.GetPhysicalTableStats(tableInfo.ID, tableInfo)
	require.NotZero(t, statsTbl.LastAnalyzeVersion)
	require.Equal(t, 0, statsTbl.StatsVer)
}
```
### 2. What did you expect to see? (Required)
The stats version is 1.

### 3. What did you see instead (Required)
The stats version is 0.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #64400

Problem Summary:
If there were no index or columns then the statistics version was not set on the table. Also if there were no statistics when dropping the statistics, it does not reset the statistics version to 0.

### What changed and how does it work?
Always set the version on load, and only reset to 0 if there were statistics, but all was zero

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/storage/read.go [hunk 1]
```diff
@@ -563,23 +565,30 @@ func TableStatsFromStorage(sctx sessionctx.Context, snapshot uint64, tableInfo *
 		}
 	}
 	// If DROP STATS executes, we need to reset the stats version to 0.
+	// Only reset if we actually have columns/indices in the table. If all stats were skipped
+	// due to lazy loading, we should keep the StatsVer that was set from the storage row.
 	if table.StatsVer != statistics.Version0 {
```
Comment (0xPoe) [inline pkg/statistics/handle/storage/read.go]: I am not sure when this situation would occur. When would we see the table’s stats version being non zero while all column and index stats versions are zero? I am not sure if we actually have any cases where this condition can be triggered. I think we may need to assert that this code path is reachable after executing drop stats.

Comment (0xPoe) [reply pkg/statistics/handle/storage/read.go]: I see — this would happen when the stats are already in memory, and after dropping the stats we should set the version to zero.

Comment (0xPoe) [reply pkg/statistics/handle/storage/read.go]: I checked that this logic has been covered by other tests. So resolved the conversation here.

File: pkg/statistics/handle/storage/read.go [hunk 2]
```diff
@@ -563,23 +565,30 @@ func TableStatsFromStorage(sctx sessionctx.Context, snapshot uint64, tableInfo *
 		}
 	}
 	// If DROP STATS executes, we need to reset the stats version to 0.
```
Comment (0xPoe) [inline pkg/statistics/handle/storage/read.go:570]: Not sure if it is worth moving this drop stats handling into a separate function and giving this behavior a clear name.

Comment (mjonss) [reply pkg/statistics/handle/storage/read.go:570]: Since it is not reused, and modifying the `table` object directly and then using the modified object when calling and returning the result of another function (`ExtendedStatsFromStorage`) with yet another copy of `table` object, I find it would only remove a very small amount of cognitive overload when reading the function, and no performance benefit, so I don't think it is worth to move out this logic to a separate function.
