### PR TITLE
ddl/ingest: create new local backend if necessary

### LINKED ISSUE #44044: add index row count is inaccurate in `ADMIN SHOW`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a cluster and create partition table
2. add index with txn mode
3. upgrade the cluster
4. show ddl job info to check the rowcount

### 3. What did you see instead (Required)
1. rowcount may be smaller than the previous view
```sql
MySQL [(none)]> admin show ddl jobs;
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME           | JOB_TYPE                         | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE   |
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
|    224 | rtdb    | t                    | add index /* txn */              | write reorganization |        88 |      154 |    898319 | 2023-05-22 11:07:47 | 

MySQL [(none)]> admin show ddl jobs;
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME           | JOB_TYPE                         | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE   |
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
|    224 | rtdb    | t                    | add index /* txn */              | write reorganization |        88 |      154 |    728796 | 2023-05-22 11:07:47 | 2023-05-22 11:07:47 | NULL                | running |


MySQL [(none)]> admin show ddl jobs;
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME           | JOB_TYPE                         | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE   |
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
|    224 | rtdb    | t                    | add index /* txn */              | write reorganization |        88 |      154 |    806927 | 2023-05-22 11:07:47 | 2023-05-22 11:07:47 | NULL                | running |

MySQL [(none)]> admin show ddl jobs;
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME           | JOB_TYPE                         | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE   |
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
|    224 | rtdb    | t                    | add index /* txn */              | write reorganization |        88 |      154 |    867855 | 2023-05-22 11:07:47 | 2023-05-22 11:07:47 | NULL                | running |

MySQL [(none)]> admin show ddl jobs;
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME           | JOB_TYPE                         | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE   |
+--------+---------+----------------------+----------------------------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------+
|    224 | rtdb    | t                    | add index /* txn */              | write reorganization |        88 |      154 |    672906 | 2023-05-22 11:07:47 | 2023-05-22 11:07:47 | NULL                | running |

```
2. after index is added, the rowcount is different with actually row count.
```sql
MySQL [rtdb]> select count(1) from t;
+----------+
| count(1) |
+----------+
| 10000800 |
+----------+

MySQL [(none)]> admin show ddl jobs 50;
+--------+---------+------------------------------------------+----------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME                               | JOB_TYPE                         | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+---------+------------------------------------------+----------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
|    224 | rtdb    | t                                        | add index /* txn */              | public       |        88 |      154 |    613382 | 2023-05-22 11:07:47 | 2023-05-22 11:07:47 | 2023-05-22 11:30:58 | synced |
```
### 4. What is your TiDB version? (Required)
55bac2963911af0fbd506f776a33e1d2337c7843

### LINKED ISSUE #44137: add index fail for "too many sst files are ingesting"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

add index
flashback to the time before add index 
during flashback inject tidb failure and tikv-pd lantency

### 2. What did you expect to see? (Required)
add index successfully
### 3. What did you see instead (Required)
add index fail 
[2023/05/23 23:11:34.790 +00:00] [WARN] [index.go:1020] ["[ddl] run add index job failed, convert job to rollback"] [job="ID:291, Type:add index, State:running, SchemaState:write reorganization, SchemaID:89, TableID:109, RowCount:10000000, ArgLen:6, start time: 2023-05-23 22:29:45.107 +0000 UTC, Err:[Lightning:KV:ServerIsBusy]too many sst files are ingesting, ErrCount:1, SnapshotVersion:441681441038270473, UniqueWarnings:0"] [error="[ddl:8214]Cancelled DDL job"]
### 4. What is your TiDB version? (Required)

7.1.0

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #44137, close #44044

Problem Summary:

See https://github.com/pingcap/tidb/issues/44137#issuecomment-1560583438.

### What is changed and how it works?

If there is no writers in engine, it means the local backend is closed. 

- Reopen the local backend before retrying adding index.
- Skip deleting SST files that belong to a running DDL job.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: ddl/index.go [hunk 1]
```diff
@@ -777,8 +777,11 @@ func cleanupSortPath(currentJobID int64) error {
 			logutil.BgLogger().Warn("[ddl-ingest] cannot cleanup sort path", zap.Error(err))
 			continue
 		}
-		// For now, there is only one task using ingest at the same time,
-		// so we can remove all the temp data of the previous jobs.
+		if _, ok := ingest.LitBackCtxMgr.Load(jobID); ok {
```
Comment (zimulala) [inline ddl/index.go:780]: Do we need to add a log?

**Review by zimulala — APPROVED** [review]
