### PR TITLE
br: save pitr id map if table mysql.tidb_pitr_id_map does not exist

### LINKED ISSUE #60706: table `mysql.tidb_pitr_id_map` does not exist if high version(v8.5) br restore point to low version(v7.5) cluster
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. prepare a v7.5 cluster
2. br:v8.5 restore point ...

### 2. What did you expect to see? (Required)

success

### 3. What did you see instead (Required)
table `mysql.tidb_pitr_id_map` does not exist.

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #60706

Problem Summary:
table `mysql.tidb_pitr_id_map` does not exist.
### What changed and how does it work?
1. if `--checkpoint-storage` is specified, save/load pitr id map in/from `{checkpoint-storage}/pitr-id-maps`.
2. otherwise, if the cluster has table `mysql.tidb_pitr_id_map`, save/load pitr id map in/from table `mysql.tidb_pitr_id_map`.
3. otherwise save/load pitr id map in/from `{log-backup-storage}/pitr-id-maps`.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/log_client/id_map.go [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+}
+
+func (rc *LogClient) loadSchemasMap(
+	ctx context.Context,
+	restoredTS uint64,
+	logCheckpointMetaManager checkpoint.LogMetaManagerT,
+) ([]*backuppb.PitrDBMap, error) {
+	if checkpointStorage := rc.tryGetCheckpointStorage(logCheckpointMetaManager); checkpointStorage != nil {
+		log.Info("checkpoint storage is specified, load pitr id map from the checkpoint storage.")
+		dbMaps, err := rc.loadSchemasMapFromStorage(ctx, checkpointStorage, restoredTS)
```
Comment (3pointer) [inline br/pkg/restore/log_client/id_map.go:135]: should fallback here when got error?

Comment (3pointer) [reply br/pkg/restore/log_client/id_map.go:135]: Which one is better, if specify checkpoint storage but got error, fallback to table or report error?

What if user first time restore without checkpoint storage, and try start from checkpoint with a new parameter checkpoint storage?

**Review by 3pointer — APPROVED** [review]

File: br/pkg/restore/log_client/id_map.go (hunk 1 above)
Comment (3pointer) [reply br/pkg/restore/log_client/id_map.go:135]: After talk with @Leavrth , we could do the check in another PR, to avoid a kind of ABA problem

File: br/pkg/restore/log_client/id_map.go [hunk 2]
```diff
@@ -0,0 +1,212 @@
...
+	"github.com/pingcap/tidb/br/pkg/checkpoint"
+	"github.com/pingcap/tidb/br/pkg/metautil"
+	"github.com/pingcap/tidb/br/pkg/storage"
+	"github.com/pingcap/tidb/br/pkg/stream"
+	"github.com/pingcap/tidb/pkg/kv"
+	"github.com/pingcap/tidb/pkg/parser/ast"
+	"go.uber.org/zap"
+)
+
+const PITRIdMapBlockSize int = 524288
```
Comment (BornChanger) [inline br/pkg/restore/log_client/id_map.go:34]: may i know how is the size determined?

Comment (Leavrth) [reply br/pkg/restore/log_client/id_map.go:34]: 524288 = 512 * 1024 KiB

Comment (BornChanger) [reply br/pkg/restore/log_client/id_map.go:34]: please add some description here and the table ddl statement.

**Review by BornChanger — APPROVED** [review]
