### PR TITLE
ddl: DROP GLOBAL TEMPORARY TABLE should fail on normal tables

### LINKED ISSUE #25595: `DROP GLOBAL TEMPORARY TABLE` should fail on normal tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> create table tb2(id int);
Query OK, 0 rows affected (0.08 sec)

mysql> drop global temporary table tb2;
Query OK, 0 rows affected (0.21 sec)

### 2. What did you expect to see? (Required)

An error reports.

### 3. What did you see instead (Required)

Succeed.

### 4. What is your TiDB version? (Required)

master.

### PR DESCRIPTION
**Pull request by Howie59**
Signed-off-by: lihaowei <haoweili35@gmail.com>

### What problem does this PR solve?

Issue Number: close #25595 

### What is changed and how it works?

Proposal: [temporary table](https://github.com/pingcap/tidb/issues/24169)

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Review by bb7133 — COMMENTED** [review]
LGTM

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -835,7 +835,7 @@ func (p *preprocessor) checkDropSequenceGrammar(stmt *ast.DropSequenceStmt) {
 func (p *preprocessor) checkDropTableGrammar(stmt *ast.DropTableStmt) {
 	p.checkDropTableNames(stmt.Tables)
 	enableNoopFuncs := p.ctx.GetSessionVars().EnableNoopFuncs
-	if stmt.TemporaryKeyword == ast.TemporaryLocal && !enableNoopFuncs {
+	if stmt.TemporaryKeyword != ast.TemporaryNone && !enableNoopFuncs {
```
Comment (djshow832) [inline planner/core/preprocess.go:838]: No, dropping global temporary tables is fine for `DROP GLOBAL TEMPORARY TABLE ...`.
E.g.
```sql
create global temporary table temp(id int) on commit delete rows;
drop global temporary table temp;   # fine
```

File: planner/core/preprocess.go [hunk 2]
```diff
@@ -833,12 +833,27 @@ func (p *preprocessor) checkDropSequenceGrammar(stmt *ast.DropSequenceStmt) {
 }
 
 func (p *preprocessor) checkDropTableGrammar(stmt *ast.DropTableStmt) {
-	p.checkDropTableNames(stmt.Tables)
+	currentDB := model.NewCIStr(p.ctx.GetSessionVars().CurrentDB)
 	enableNoopFuncs := p.ctx.GetSessionVars().EnableNoopFuncs
-	if stmt.TemporaryKeyword == ast.TemporaryLocal && !enableNoopFuncs {
-		p.err = expression.ErrFunctionsNoopImpl.GenWithStackByArgs("DROP TEMPORARY TABLE")
-		return
+	for _, t := range stmt.Tables {
```
Comment (djshow832) [inline planner/core/preprocess.go:838]: Do this only when `stmt.TemporaryKeyword != ast.TemporaryNone`, so that it doesn't affect the original logic.

File: planner/core/preprocess.go [hunk 3]
```diff
@@ -833,12 +833,27 @@ func (p *preprocessor) checkDropSequenceGrammar(stmt *ast.DropSequenceStmt) {
...
+		if t.Schema.String() != "" {
+			currentDB = t.Schema
+		}
+		tableInfo, err := p.ensureInfoSchema().TableByName(currentDB, t.Name)
+		if err != nil {
+			p.err = err
+			return
+		}
+		if stmt.TemporaryKeyword != ast.TemporaryNone && !enableNoopFuncs && tableInfo.Meta().TempTableType == model.TempTableNone {
+			p.err = expression.ErrFunctionsNoopImpl.GenWithStackByArgs("DROP TEMPORARY TABLE")
```
Comment (djshow832) [inline planner/core/preprocess.go:852]: Report another error for this issue. Dropping global temporary tables is not a noop function.

File: planner/core/preprocess.go [hunk 4]
```diff
@@ -833,12 +833,34 @@ func (p *preprocessor) checkDropSequenceGrammar(stmt *ast.DropSequenceStmt) {
...
+		}
+		if t.Schema.String() != "" {
+			currentDB = t.Schema
+		}
+		tableInfo, err := p.ensureInfoSchema().TableByName(currentDB, t.Name)
+		if err != nil {
+			p.err = err
+			return
+		}
+		if tableInfo.Meta().TempTableType == model.TempTableNone {
```
Comment (djshow832) [inline planner/core/preprocess.go:858]: What if it's local?

File: planner/core/preprocess.go [hunk 5]
```diff
@@ -833,12 +833,34 @@ func (p *preprocessor) checkDropSequenceGrammar(stmt *ast.DropSequenceStmt) {
 }
 
 func (p *preprocessor) checkDropTableGrammar(stmt *ast.DropTableStmt) {
-	p.checkDropTableNames(stmt.Tables)
 	enableNoopFuncs := p.ctx.GetSessionVars().EnableNoopFuncs
 	if stmt.TemporaryKeyword == ast.TemporaryLocal && !enableNoopFuncs {
 		p.err = expression.ErrFunctionsNoopImpl.GenWithStackByArgs("DROP TEMPORARY TABLE")
 		return
 	}
+	currentDB := model.NewCIStr(p.ctx.GetSessionVars().CurrentDB)
```
Comment (djshow832) [inline planner/core/preprocess.go:841]: This can also be moved down.

File: planner/core/preprocess.go [hunk 6]
```diff
@@ -833,12 +833,34 @@ func (p *preprocessor) checkDropSequenceGrammar(stmt *ast.DropSequenceStmt) {
...
+		if t.Schema.String() != "" {
+			currentDB = t.Schema
+		}
+		tableInfo, err := p.ensureInfoSchema().TableByName(currentDB, t.Name)
+		if err != nil {
+			p.err = err
+			return
+		}
+		if tableInfo.Meta().TempTableType == model.TempTableNone {
+			p.err = ErrOptOnTemporaryTable.GenWithStackByArgs("drop temporary table")
```
Comment (djshow832) [inline planner/core/preprocess.go:859]: What will the error message be? `drop temporary table is unsupported on temporary tables`?

Comment (Howie59) [reply planner/core/preprocess.go:859]: yes, do we need to change the words?

File: planner/core/preprocess.go (hunk 4 above)
Comment (Howie59) [reply planner/core/preprocess.go:858]: do we need 2 report err when temp table type is local?

File: planner/core/preprocess.go (hunk 6 above)
Comment (djshow832) [reply planner/core/preprocess.go:859]: We need another error message. This error message is not suitable for this case.

File: planner/core/preprocess.go [hunk 7]
```diff
@@ -839,6 +839,29 @@ func (p *preprocessor) checkDropTableGrammar(stmt *ast.DropTableStmt) {
...
+	}
+	currentDB := model.NewCIStr(p.ctx.GetSessionVars().CurrentDB)
+	for _, t := range stmt.Tables {
+		if isIncorrectName(t.Name.String()) {
+			p.err = ddl.ErrWrongTableName.GenWithStackByArgs(t.Name.String())
+			return
+		}
+		if t.Schema.String() != "" {
+			currentDB = t.Schema
+		}
```
Comment (djshow832) [inline planner/core/preprocess.go:853]: Provide a test case to cover this.

File: planner/core/preprocess_test.go [hunk 8]
```diff
@@ -337,3 +337,28 @@ func (s *testValidatorSuite) TestForeignKey(c *C) {
...
+	}
+	for _, execSQL := range execSQLList {
+		_, err := s.se.Execute(ctx, execSQL)
+		c.Assert(err, IsNil)
+	}
+	s.is = s.dom.InfoSchema()
+	s.runSQL(c, "drop global temporary table tb;", false, core.ErrDropTableOnTemporaryTable)
+	s.runSQL(c, "drop global temporary table temp", false, nil)
+	s.runSQL(c, "drop global temporary table test.tb;", false, core.ErrDropTableOnTemporaryTable)
+	s.runSQL(c, "drop global temporary table test.temp", false, nil)
```
Comment (djshow832) [inline planner/core/preprocess_test.go:363]: But it's already dropped.

Comment (Howie59) [reply planner/core/preprocess_test.go]: oh, my mistake...

**Review by djshow832 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
It seems some tests panic and the CI never finish ... I'm not sure is it related to this change or our master branch is unstable

**Comment by tiancaiamao** [comment]
ref https://github.com/pingcap/tidb/pull/25724
