### PR TITLE
planner: improve skyline pruning

### LINKED ISSUE #26017: planner: redundant sort when making sql plan
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int, b int, c int, d int, index idx_a_b_c(a, b, c));
explain select a, b, c from t where a > 3 and b = 4 order by a, c;
```

### 2. What did you expect to see? (Required)
`idx_a_b_c` matches the physical property that `order by a, c` asks and no sort is needed. Here is the plan made by MySQL
```
mysql> explain select a, b, c from t where a > 3 and b = 4 order by a, c;
+----+-------------+-------+------------+-------+---------------+-----------+---------+------+------+----------+--------------------------+
| id | select_type | table | partitions | type  | possible_keys | key       | key_len | ref  | rows | filtered | Extra                    |
+----+-------------+-------+------------+-------+---------------+-----------+---------+------+------+----------+--------------------------+
|  1 | SIMPLE      | t     | NULL       | index | idx_a_b_c     | idx_a_b_c | 15      | NULL |    1 |   100.00 | Using where; Using index |
+----+-------------+-------+------------+-------+---------------+-----------+---------+------+------+----------+--------------------------+
1 row in set, 1 warning (0.01 sec)
```

### 3. What did you see instead (Required)
The plan made by TiDB has redundant sort.
```
mysql> explain select a, b, c from t where a > 3 and b = 4 order by a, c;
+----------------------------+---------+-----------+-----------------------------------+------------------------------------------------+
| id                         | estRows | task      | access object                     | operator info                                  |
+----------------------------+---------+-----------+-----------------------------------+------------------------------------------------+
| Sort_5                     | 3.33    | root      |                                   | test.t.a, test.t.c                             |
| └─IndexReader_10           | 3.33    | root      |                                   | index:Selection_9                              |
|   └─Selection_9            | 3.33    | cop[tikv] |                                   | eq(test.t.b, 4)                                |
|     └─IndexRangeScan_8     | 3333.33 | cop[tikv] | table:t, index:idx_a_b_c(a, b, c) | range:(3,+inf], keep order:false, stats:pseudo |
+----------------------------+---------+-----------+-----------------------------------+------------------------------------------------+
4 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.2.0-alpha-222-g297a90dde
Edition: Community
Git Commit Hash: 297a90dde2018c53bc38b08605c4460ce4ccdbc6
Git Branch: master
UTC Build Time: 2021-07-07 05:52:03
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)
```

### LINKED ISSUE #26320: Refine the skyline pruning

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

closes #26320 

### What is changed and how it works?

What's Changed & How it Works:

1. When comparing whether double scan is needed, if both paths need double scan, we further compare the column set of `IndexFilters`, if the column set of  path A is the subset of that of path B, then path B has less table rows to access than path A, so path B is better than path A on the factor. If there is no subset relation, then the two paths are incomparable.
2. For the `isMatchProp` factor, 
```
create table t(a int, b int, c int, d int, index idx_a_b_c(a, b, c));
explain select a, b, c from t where a > 3 and b = 4 order by a, c;
```
`idx_a_b_c` actually matches the order `a, c` since `b = 4` is constant. This pr takes the situation into consideration. (ps: this pr can also close #26017)

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
- [x] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- improve skyline pruning rules

### CODE REVIEW

File: planner/core/find_best_task.go [hunk 1]
```diff
@@ -474,52 +488,60 @@ func compareCandidates(lhs, rhs *candidatePath) int {
...
+				if path.EqualCols == nil || !path.EqualCols[i] {
 					break
 				}
 			}
+			if !found {
+				isMatchProp = false
+				break
+			}
 		}
 	}
```
Comment (qw4990) [inline planner/core/find_best_task.go:528]: Could you please add an example in the comments for this piece of code?

**Review by time-and-fate — COMMENTED** [review]
A bad case:
```sql
create table t(a int, b int, c int, d int, index i(a,b,c));
explain select a,b,c from t where (a=1 and b=1 and c=1) or (a=1 and b=1 and c=2) order by c;
```
```
+--------------------------+---------+-----------+---------------------------+-----------------------------------------------------+
| id                       | estRows | task      | access object             | operator info                                       |
+--------------------------+---------+-----------+---------------------------+-----------------------------------------------------+
| Sort_5                   | 0.03    | root      |                           | test.t.c                                            |
| └─IndexReader_9          | 0.03    | root      |                           | index:IndexRangeScan_8                              |
|   └─IndexRangeScan_8     | 0.03    | cop[tikv] | table:t, index:i(a, b, c) | range:[1 1 1,1 1 2], keep order:false, stats:pseudo |
+--------------------------+---------+-----------+---------------------------+-----------------------------------------------------+

```
It's because the `EqualCols` is not calculated correctly.
Seems like we also need to handle the `pointRes` case in `detachCNFCondAndBuildRangeForIndex` and the DNF case in `detachCondAndBuildRangeForCols`.

File: util/ranger/detacher.go [hunk 2]
```diff
@@ -619,6 +710,9 @@ type DetachRangeResult struct {
 	AccessConds []expression.Expression
 	// RemainedConds is the filter conditions which should be kept after access.
 	RemainedConds []expression.Expression
+	// ColumnValues records the constant column values for all index columns.
+	// For the ith column, if it is evaluated as constant, ColumnValues[i] is its value. Otherwise ColumnValues[i] is nil.
+	ColumnValues []*valueInfo
 	// EqCondCount is the number of equal conditions extracted.
 	EqCondCount int
```
Comment (winoros) [inline util/ranger/detacher.go:717]: This var can be deleted now?

Comment (xuyifangreeneyes) [reply util/ranger/detacher.go:722]: There is slight difference between how `ColumnValues` and `EqCondCount` are calculated. For example,
```
mysql> create table t2(a int, b int, c int, d int, index idx_a_b_c_d(a, b, c, d));
Query OK, 0 rows affected (0.01 sec)

mysql> explain select * from t2 where ((a = 1 and b = 1 and d < 3) or (a = 1 and b = 1 and d > 6)) and c = 3 order by d;
+---------------------------+---------+-----------+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                        | estRows | task      | access object                           | operator info                                                                                                                                        |
+---------------------------+---------+-----------+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexReader_14            | 0.00    | root      |                                         | index:Selection_13                                                                                                                                   |
| └─Selection_13            | 0.00    | cop[tikv] |                                         | eq(test.t2.c, 3), or(and(eq(test.t2.a, 1), and(eq(test.t2.b, 1), lt(test.t2.d, 3))), and(eq(test.t2.a, 1), and(eq(test.t2.b, 1), gt(test.t2.d, 6)))) |
|   └─IndexRangeScan_12     | 10.00   | cop[tikv] | table:t2, index:idx_a_b_c_d(a, b, c, d) | range:[1,1], keep order:true, stats:pseudo                                                                                                           |
+---------------------------+---------+-----------+-----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
```
In the case, `ColumnValues` detect `a, b, c` are constant columns while `EqCondCount` only detect `a` is a constant column. Do we need to improve it in this pr or unify `ColumnValues` and `EqCondCount` in another pr?

Comment (winoros) [reply util/ranger/detacher.go:722]: I think we can improve it later, not in this PR. What's your opinion? @qw4990 @time-and-fate

File: planner/core/find_best_task.go [hunk 3]
```diff
@@ -450,18 +451,31 @@ func compareBool(l, r bool) int {
...
 
+func compareIndexBack(lhs, rhs *candidatePath) (int, bool) {
+	result := compareBool(lhs.isSingleScan, rhs.isSingleScan)
+	if result == 0 && !lhs.isSingleScan {
+		// if both lhs and rhs need to access table after IndexScan, we use the set of columns that occurred in IndexFilters
+		// to compare how many table rows will be accessed.
+		return compareColumnSet(lhs.indexFiltersColSet, rhs.indexFiltersColSet)
+	}
+	return result, true
+}
```
Comment (qw4990) [inline planner/core/find_best_task.go:462]: Is there any test case that can cover this rule?

File: planner/core/find_best_task.go [hunk 4]
```diff
@@ -473,52 +487,70 @@ func compareCandidates(lhs, rhs *candidatePath) int {
...
+		for _, sortItem := range prop.SortItems {
+			found := false
+			for ; i < len(path.IdxCols); i++ {
+				if path.IdxColLens[i] == types.UnspecifiedLength && sortItem.Col.Equal(nil, path.IdxCols[i]) {
+					found = true
+					i++
 					break
-				} else if i >= path.EqCondCount {
+				}
+				if path.ConstCols == nil || !path.ConstCols[i] {
```
Comment (qw4990) [inline planner/core/find_best_task.go:528]: How about adding one more condition `|| i >= len(path.ConstCols) ||` for safety?

File: planner/core/find_best_task.go (hunk 3 above)
Comment (xuyifangreeneyes) [reply planner/core/find_best_task.go:462]: Yes. https://github.com/xuyifangreeneyes/tidb/blob/116e60b8ad38f7ebfa5ea68b09e87054723a9394/planner/core/logical_plan_test.go#L1703-L1710 In the two cases `f_g` is better than `f` due to this rule.

File: util/ranger/detacher.go (hunk 2 above)
Comment (time-and-fate) [reply util/ranger/detacher.go:722]: I think it's OK to improve it later.

File: util/ranger/detacher.go [hunk 5]
```diff
@@ -240,7 +237,21 @@ func extractIndexPointRangesForCNF(sctx sessionctx.Context, conds []expression.E
...
+	if lhs == nil {
+		lhs = make([]*valueInfo, numCols)
+	}
+	if rhs != nil {
+		for i, valInfo := range lhs {
+			if valInfo == nil && rhs[i] != nil {
+				lhs[i] = rhs[i]
+			}
+		}
+	}
```
Comment (time-and-fate) [inline util/ranger/detacher.go:253]: When both `lhs` and `rhs` are `nil`, it will return a slice of `nil`. Is this expected?

File: util/ranger/detacher.go [hunk 6]
```diff
@@ -562,26 +604,46 @@ func (d *rangeDetacher) detachDNFCondAndBuildRangeForIndex(condition *expression
...
+						sameVale, err := isSameValue(d.sctx.GetSessionVars().StmtCtx, valInfo, res.ColumnValues[j])
+						if err != nil {
+							return nil, nil, nil, false, errors.Trace(err)
+						}
+						if !sameVale {
+							columnValues[j] = nil
+						}
+					}
+				}
+			}
```
[the remark this answers is not in the document]
Comment (time-and-fate) [reply util/ranger/detacher.go:646]: Also, seems `sameVale` is a typo.

[the remark this answers is not in the document]
Comment (xuyifangreeneyes) [reply util/ranger/detacher.go:646]: Yes, it is simpler but it may miss some constant columns. Here is a case:
```
create table t(a int, b int, c int, d int, index idx_a_b_c_d(a, b, c, d));
select * from t where (a = 3 and b < 1 and c = 4) or (a = 3 and b > 5 and c = 4) order by b, d;
```
In the case, `totalRanges` is `[3 -inf,3 1), (3 5,3 +inf]` while both `a` and `c` are constant.

File: util/ranger/detacher.go [hunk 7]
```diff
@@ -185,43 +185,40 @@ func getPotentialEqOrInColOffset(expr expression.Expression, cols []*expression.
...
-		origColNum := colSets.Len()
-		if origColNum == 0 {
+		if colSets.Len() == 0 {
 			continue
 		}
-		if l := len(cols); origColNum > l {
-			origColNum = l
-		}
-		currCols := cols[:origColNum]
-		currLengths := lengths[:origColNum]
```
[the remark this answers is not in the document]
Comment (xuyifangreeneyes) [reply util/ranger/detacher.go:206]: Before the pr, we only need to extract point ranges from `cond`. Hence if `cond` has `origColNum`, we only need to consider whether the first `origColNum` columns of the index are constant. After the pr, we want to detect every constant column of the index (not only the first several columns). For example,
```
create table t2(a int, b int, c int, d int, index idx_a_b_c_d(a, b, c, d));
select * from t2 where ((a = 1 and b = 1 and d < 3) or (a = 1 and b = 1 and d > 6)) and c = 3 order by d;
```
In the case, when we deal with `c = 3`, `origColNum` is `1`. If we keep those lines, `currCols` and `currLengths` only include column `a` and we cannot detect `c = 3`.

File: util/ranger/detacher.go (hunk 5 above)
Comment (xuyifangreeneyes) [reply util/ranger/detacher.go:253]: Yes, a slice of `nil` means no column is constant. But we can just return `nil` if both `lhs` and `rhs` are `nil`, which avoids `make`.

File: util/ranger/detacher.go [hunk 8]
```diff
@@ -240,7 +237,21 @@ func extractIndexPointRangesForCNF(sctx sessionctx.Context, conds []expression.E
 	if r != nil {
 		r.IsDNFCond = false
 	}
-	return r, offset, nil
+	return r, offset, columnValues, nil
+}
+
+func unionColumnValues(lhs, rhs []*valueInfo, numCols int) []*valueInfo {
```
Comment (time-and-fate) [inline util/ranger/detacher.go:243]: Now the `numCols` should have become useless.

**Review by time-and-fate — APPROVED** [review]
LGTM. The logic in the `util/ranger` is quite complicated though.

**Review by winoros — APPROVED** [review]
