### PR TITLE
*: global memory controller should not kill session whose mem less than limit_sess_min_size

### LINKED ISSUE #42662: query killed by global memory controller unexpectedly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Global memory controller killed a query successfully on the connection 8733482432075924065
BP6SSjoL1U

2. But all the new queries sent to this connection are killed
BRRhJeLE9u

I guess the NeedKill signal was not set to false on this connection.

### 4. What is your TiDB version? (Required)

 ["Release Version"=v6.5.0-20230228] [Edition=Enterprise] ["Git Commit Hash"=58fcf7b58ad717b61c3deeff0764f3a47246c5ed] ["Git Branch"=heads/refs/tags/v6.5.0-20230228] ["UTC Build Time"="2023-02-28 11:07:46"] [GoVersion=go1.19.5] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=6.2.0-alpha]

### LINKED ISSUE #42664: query with memory usage 0 be killed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Queries with memory usage less than 128MB would be recorded be global memory controller.
2. But when tidb_server_memory_limit is reached, the memory usage of the query may be less than 128MB
3. We do not need to kill such queries.
image

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve?

Issue Number: 
close #42662
close #42664  

Problem Summary:
As the description mentioned here:
https://github.com/pingcap/tidb/issues/42662#issuecomment-1491405794

### What is changed and how it works?
1. Reset NeekKill flag even error is thrown during the planner phase or executor.Open phase
2. Do not kill the session whose memory usage is less than tidb_server_memory_limit_sess_min_size

### Check List

Tests 

- [ ] Unit test
- [x] Integration test

If we run the same test on master branch, the following error will be thrown:
```
    testkit.go:157: 
        	Error Trace:	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/testkit/testkit.go:157
        	            				/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/testkit/testkit.go:150
        	            				/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor_test.go:6521
        	Error:      	Received unexpected error:
        	            	Out Of Memory Quota![conn=12345]
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).openExecutor.func1
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/adapter.go:1188
        	            	runtime.gopanic
        	            		/Users/xuhuaiyu/.gvm/gos/go1.20/src/runtime/panic.go:884
        	            	github.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/memory/action.go:149
        	            	github.com/pingcap/tidb/util/memory.(*Tracker).Consume.func2
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/memory/tracker.go:450
        	            	github.com/pingcap/tidb/util/memory.(*Tracker).Consume
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/memory/tracker.go:462
        	            	github.com/pingcap/tidb/executor.(*HashAggExec).initForParallelExec
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/aggregate.go:395
        	            	github.com/pingcap/tidb/executor.(*HashAggExec).Open
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/aggregate.go:321
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).openExecutor
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/adapter.go:1192
        	            	github.com/pingcap/tidb/executor.(*ExecStmt).Exec
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/adapter.go:527
        	            	github.com/pingcap/tidb/session.runStmt
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/session/session.go:2343
        	            	github.com/pingcap/tidb/session.(*session).ExecuteStmt
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/session/session.go:2200
        	            	github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/testkit/testkit.go:325
        	            	github.com/pingcap/tidb/testkit.(*TestKit).MustQueryWithContext
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/testkit/testkit.go:156
        	            	github.com/pingcap/tidb/testkit.(*TestKit).MustQuery
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/testkit/testkit.go:150
        	            	github.com/pingcap/tidb/executor_test.TestIssue42662
        	            		/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor_test.go:6521
        	            	testing.tRunner
        	            		/Users/xuhuaiyu/.gvm/gos/go1.20/src/testing/testing.go:1576
        	            	runtime.goexit
        	            		/Users/xuhuaiyu/.gvm/gos/go1.20/src/runtime/asm_amd64.s:1598
        	Test:       	TestIssue42662
        	Messages:   	sql:select count(*) from t1, args:[]

```

- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the problem that global memory controller kill the sqls whose memory usage are less than tidb_server_memory_limit_sess_min_size defined.
```

### CODE REVIEW

File: util/servermemorylimit/servermemorylimit.go [hunk 1]
```diff
@@ -115,14 +125,25 @@ func killSessIfNeeded(s *sessionToBeKilled, bt uint64, sm util.SessionManager) {
...
 	}
+	limitSessMinSize := memory.ServerMemoryLimitSessMinSize.Load()
 	if instanceStats.HeapInuse > bt {
 		t := memory.MemUsageTop1Tracker.Load()
 		if t != nil {
-			if info, ok := sm.GetProcessInfo(t.SessionID); ok {
+			memUsage := t.BytesConsumed()
+			// If the memory usage of the top1 session is less than tidb_server_memory_limit_sess_min_size, we do not need to kill it.
+			if uint64(memUsage) < limitSessMinSize {
+				memory.MemUsageTop1Tracker.CompareAndSwap(t, nil)
```
Comment (chrysan) [inline util/servermemorylimit/servermemorylimit.go:144]: If CompareAndSwap fails, it means the Top1Tracker is another tracker now, but we will skip the check and kill in this round, right?

Comment (chrysan) [reply util/servermemorylimit/servermemorylimit.go:144]: It looks OK, I see the interval is 100 ms.

**Review by chrysan — APPROVED** [review]

File: executor/executor_test.go [hunk 2]
```diff
@@ -6481,3 +6481,46 @@ from ssci right join csci on (ssci.customer_sk=csci.customer_sk
                                and ssci.item_sk = csci.item_sk)
 limit 100;`)
 }
+
+func TestIssue42662(t *testing.T) {
```
Comment (hawkingrei) [inline executor/executor_test.go:6485]: Because too many test cases are in the executor. Please move it into ```executor/issuetest```. 

on the other hand, ```TestIssuexxxx``` makes people wonder what exactly has been repaired.

**Review by hawkingrei — APPROVED** [review]
