### PR TITLE
executor: Change log level to `Warning` in the `Close` of join

### LINKED ISSUE #62652: Change log level to `Warning` in the `Close` of join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #62652

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/join/hash_join_v1.go [hunk 1]
```diff
@@ -146,8 +146,8 @@ func (e *HashJoinV1Exec) Close() error {
 		util.WithRecovery(func() {
 			err := e.RowContainer.Close()
 			if err != nil {
-				logutil.BgLogger().Error("RowContainer encounters error",
-					zap.Error(err),
+				logutil.BgLogger().Warn("RowContainer encounters unexpected behaviour",
+					zap.String("info", err.Error()),
```
Comment (hawkingrei) [inline pkg/executor/join/hash_join_v1.go]:
```suggestion
					zap.Error(err),
```

**Review by XuHuaiyu — APPROVED** [review]
