### PR TITLE
expression: Short cut expr vec bug

### LINKED ISSUE #17725: expression: short-cut expressions cause unnecessary warnings, which even causes errors in update statements.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> use test;
Database changed
mysql> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert t values (1);
Query OK, 1 row affected (0.01 sec)

mysql> select case when a=1 then 1 else 1/(a-1) end from t;
+---------------------------------------+
| case when a=1 then 1 else 1/(a-1) end |
+---------------------------------------+
|                                     1 |
+---------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)

mysql> select if(a=1,1,1/(a-1)) from t;
+-------------------+
| if(a=1,1,1/(a-1)) |
+-------------------+
|                 1 |
+-------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)

 select ifnull(1,1/0);
+---------------+
| ifnull(1,1/0) |
+---------------+
|             1 |
+---------------+
1 row in set, 1 warning (0.00 sec)

select case  when 1/1 then 1/1 when 1/0 then 1/0 end;
+-----------------------------------------------+
| case  when 1/1 then 1/1 when 1/0 then 1/0 end |
+-----------------------------------------------+
|                                        1.0000 |
+-----------------------------------------------+
1 row in set, 2 warnings (0.01 sec)

```

We may also handle AND and OR.
```
mysql> select 0 and 1/0;
+-----------+
| 0 and 1/0 |
+-----------+
|         0 |
+-----------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```

```
mysql> select COALESCE(1, 1/0);
+------------------+
| COALESCE(1, 1/0) |
+------------------+
|                1 |
+------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```

```
mysql> select * from t0;
+------+
| c0   |
+------+
|    0 |
|    1 |
+------+
2 rows in set (0.00 sec)

mysql> select interval(t0.c0, -1,0,1,2,1/0) from t0;
+-------------------------------+
| interval(t0.c0, -1,0,1,2,1/0) |
+-------------------------------+
|                             2 |
|                             5 |
+-------------------------------+
2 rows in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```
### 2. What did you expect to see? (Required)
no warnings like in MySQL
### 3. What did you see instead (Required)
a warning
### 4. Affected version (Required)

v4.0.0

### 5. Root Cause Analysis
1. Bug from the vectorization run all execution paths,
2. constant folding folds all paths.

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close #17725

Problem Summary: fallback vectorization to scalar execution when error/warnings happen.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

- solve vectorization bug from and/or/COALESCE due to short cut

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
I think we can modify the vectorized function to:

- x OR y: if x[i] = 0, evaluate y[i], else skip y[i]
- x AND y: if x[i] = 1, evaluate y[i], else skip y[i]

**Comment by fzhedu** [comment]
> I think we can modify the vectorized function to:
> 
> * x OR y: if x[i] = 0, evaluate y[i], else skip y[i]
> * x AND y: if x[i] = 1, evaluate y[i], else skip y[i]

This would be more complex.
1. this way does not change the fact that vectorization should evaluate every arg.
2.it indeed adds an additional loop to  check x[i] == 0/1 ? before y[i], but not shortcut the execution like in the scalar execution.

**Comment by zz-jason** [comment]
> > I think we can modify the vectorized function to:
> > 
> > * x OR y: if x[i] = 0, evaluate y[i], else skip y[i]
> > * x AND y: if x[i] = 1, evaluate y[i], else skip y[i]
> 
> This would be more complex.
> 
> 1. this way does not change the fact that vectorization should evaluate every arg.
>    2.it indeed adds an additional loop to  check x[i] == 0/1 ? before y[i], but not shortcut the execution like in the scalar execution.

We can firstly evaluate the x vector, then evaluate each scalar value on y[i] based on the result of x[i].

BTW, how other vectorized databases handles these kinds of expressions?

**Comment by fzhedu** [comment]
> > > I think we can modify the vectorized function to:
> > > 
> > > * x OR y: if x[i] = 0, evaluate y[i], else skip y[i]
> > > * x AND y: if x[i] = 1, evaluate y[i], else skip y[i]
> > 
> > 
> > This would be more complex.
> > 
> > 1. this way does not change the fact that vectorization should evaluate every arg.
> >    2.it indeed adds an additional loop to  check x[i] == 0/1 ? before y[i], but not shortcut the execution like in the scalar execution.
> 
> We can firstly evaluate the x vector, then evaluate each scalar value on y[i] based on the result of x[i].
> 
> BTW, how other vectorized databases handles these kinds of expressions?

In formal vectiorzation, each arg should be executed in vectorization.
y maybe other complex functions, not just a constant or a column, it is better to vectorize each arg. Once erros/warnings happen (rarely happen), falls back to the scalar execution.

**Comment by zz-jason** [comment]
to summarize, there are two methods in the above to handle short circuit for `x AND y`:

1. evaluate all the arguments to get vector x and y, if not all the values in x are 0, fallback to the row-based execution method.
2. evaluate the vector x firstly, conditionally evaluate y[i] based on the value of x[i].

IMO, the performance of the second method is better than the first method in most cases, where not all the values in the vector x are 0.

**Comment by fzhedu** [comment]
> to summarize, there are two methods in the above to handle short circuit for `x AND y`:
> 
> 1. evaluate all the arguments to get vector x and y, if not all the values in x are 0, fallback to the row-based execution method.
> 2. evaluate the vector x firstly, conditionally evaluate y[i] based on the value of x[i].
> 
> IMO, the performance of the second method is better than the first method in most cases, where not all the values in the vector x are 0.
> 
> So I prefer the second method. It achieves the short circuit and the performance is not sacrificed much compared with the old vectorized method.

It depends.
x and y if y = (a*b>C) such complex sub expressions, and x has certain 0s, taking the vectorization would better.

**Comment by zz-jason** [comment]
Would you like to construct some expression cases and do the performance benchmarks on both methods? It's hard to decide to use which one without any benchmark result.

**Comment by SunRunAway** [comment]
> Would you like to construct some expression cases and do the performance benchmarks on both methods? It's hard to decide to use which one without any benchmark result.

Hi, @zz-jason 
I suggest dividing this issue into 2 steps.
1. First, use method 1 to fix this bug as a workaround.
2. Then make a further plan to reconstruct the vectorized expression framework by method 2 in the future for performance improvement.

**Comment by zz-jason** [comment]
I think method 1 and 2 are both workarounds, the difference is which workaround can have better performance. It's not hard to implement method 2 and do some benchmarks IMO.

**Comment by SunRunAway** [comment]
Method 2 needs to involve the selection vector into all the signatures of the vectorized expression framework. It may take plenty of time. It's better to create another issue and have a good design.
In the meantime, the existing bug should not be left in the release version so I think the workaround of this PR should be merged ASAP.

**Comment by zz-jason** [comment]
> Method 2 needs to involve the selection vector into all the signatures of the vectorized expression framework.

No need to. We can combine the usage of `evalXXX` and `VecEvalXXX` in this workaround.

**Comment by SunRunAway** [comment]
> > Method 2 needs to involve the selection vector into all the signatures of the vectorized expression framework.
> 
> No need to. We can combine the usage of `evalXXX` and `VecEvalXXX` in this workaround.

That's an even more complex workaround. And I think this could be a new performance issue since this improvement exiting before whenever this bug happens. Even more, I think it's still not worth involving another complex workaround since we have a better idea which uses the selection vector to do short circuit.

> It's not that urgent to fix this issue since it only affects the warning messages.

DML queries treat it as an error.
```mysql
mysql> update t set a=1 and 1/0;
ERROR 1365 (22012): Division by 0
```

**Comment by zz-jason** [comment]
If there is an error in the DML statements, the DML queries won't execute successfully, thus the data correctness and consistency can be guaranteed. So I think it's not that urgent.

Though both methods are workarounds, I think it's important to reduce the performance regression.

File: expression/generator/compare_vec.go [hunk 1]
```diff
@@ -171,7 +171,47 @@ func (b *builtin{{ .compare.CompareName }}{{ .type.TypeName }}Sig) vectorized()
...
+			result.AppendNull()
+			continue
+		}
+		result.Append{{ .type.TypeNameInColumn }}(res)
+	}
+	{{ end -}}
+	return nil
+}
+
+{{ if .type.Fixed }}
```
Comment (SunRunAway) [inline expression/generator/compare_vec.go:214]: Miss the `else` path.

Comment (fzhedu) [reply expression/generator/compare_vec.go:214]: correspond to line:245

Comment (fzhedu) [reply expression/generator/compare_vec.go:214]: updated

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by zz-jason — DISMISSED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by qw4990 — COMMENTED** [review]
@fzhedu please fix conflicts.

**Review by SunRunAway — APPROVED** [review]
