### PR TITLE
importinto: fix flaky test TestAutoDetectFileType

### LINKED ISSUE #64106: Unstable test TestAutoDetectFileType
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
=== NAME  TestImportInto
    testkit.go:171: 
        	Error Trace:	pkg/testkit/testkit.go:171
        	            				pkg/testkit/testkit.go:156
        	            				tests/realtikvtest/importintotest4/cloud_sdk_test.go:253
        	Error:      	Received unexpected error:
        	            	[schema:8258]Table t is in mode Import
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext
        	            		pkg/testkit/testkit.go:439
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext
        	            		pkg/testkit/testkit.go:168
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec
        	            		pkg/testkit/testkit.go:156
        	            	tests/realtikvtest/importintotest4/importintotest4_test.(*mockGCSSuite).TestAutoDetectFileType
        	            		tests/realtikvtest/importintotest4/cloud_sdk_test.go:253
        	            	reflect.Value.call
        	            		GOROOT/src/reflect/value.go:584
        	            	reflect.Value.Call
        	            		GOROOT/src/reflect/value.go:368
        	            	github.com/stretchr/testify/suite.Run.func1
        	            		external/com_github_stretchr_testify/suite/suite.go:202
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1690
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1700
        	Test:       	TestImportInto
        	Messages:   	sql:DROP TABLE auto_detect.t;, [], error stack [schema:8258]Table t is in mode Import
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext
        	            		pkg/testkit/testkit.go:439
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext
        	            		pkg/testkit/testkit.go:168
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec
        	            		pkg/testkit/testkit.go:156
        	            	tests/realtikvtest/importintotest4/importintotest4_test.(*mockGCSSuite).TestAutoDetectFileType
        	            		tests/realtikvtest/importintotest4/cloud_sdk_test.go:253
        	            	reflect.Value.call
        	            		GOROOT/src/reflect/value.go:584
        	            	reflect.Value.Call
        	            		GOROOT/src/reflect/value.go:368
        	            	github.com/stretchr/testify/suite.Run.func1
        	            		external/com_github_stretchr_testify/suite/suite.go:202
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1690
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1700
=== NAME  TestImportInto/TestAutoDetectFileType
    testing.go:1577: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestImportInto/TestAutoDetectFileType (18.69s)
```

### 4. What is your TiDB version? (Required)

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/42670/pipeline/548/

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #64106

Problem Summary:

### What changed and how does it work?
wait cleanup done, so table mode is switched back
### Check List

Tests 

- [ ] Unit test
- [x] Integration test. **fixing existing ones**
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tests/realtikvtest/importintotest4/cloud_sdk_test.go [hunk 1]
```diff
@@ -249,6 +258,15 @@ func (s *mockGCSSuite) TestAutoDetectFileType() {
...
 		s.Require().ErrorContains(err, nc.wantSubstr)
+		s.T().Logf("the task id is %d", storage.TestLastTaskID.Load())
+		// wait cleanup done, so the table mode is switched back to normal
+		// Note: the first case doesn't submit the task, so no task id, but it's
+		// ok to call GetTaskByID with non-existing id, it will just return
+		// ErrTaskNotFound immediately.
+		s.Eventually(func() bool {
+			_, err2 := taskMgr.GetTaskByID(ctx, storage.TestLastTaskID.Load())
+			return goerrors.Is(err2, storage.ErrTaskNotFound)
+		}, 30*time.Second, 100*time.Millisecond)
```
Comment (zimulala) [inline tests/realtikvtest/importintotest4/cloud_sdk_test.go:269]: Is this duration(30*time.Second) too long? In the extreme case, the entire CI test directly reports a timeout without reporting any errors for this test, resulting in uncertainty about which test has exceeded the time limit and reported an error.

File: tests/realtikvtest/importintotest4/cloud_sdk_test.go [hunk 2]
```diff
@@ -238,6 +243,10 @@ func (s *mockGCSSuite) TestAutoDetectFileType() {
 		{objectName: "csv_as_sql.sql", options: "", wantSubstr: "encode kv erro"},
```
Comment (joechenrh) [inline tests/realtikvtest/importintotest4/cloud_sdk_test.go]:
```suggestion
		{objectName: "csv_as_sql.sql", options: "", wantSubstr: "encode kv error"},
```

**Review by joechenrh — APPROVED** [review]

File: tests/realtikvtest/importintotest4/cloud_sdk_test.go (hunk 1 above)
Comment (D3Hunter) [reply tests/realtikvtest/importintotest4/cloud_sdk_test.go:269]: reducing this interval will cause the case prone to flaky when the resource on CI is on heavy load, especially when releasing

> the entire CI test directly reports a timeout without reporting any errors for this test, resulting in uncertainty about which test has exceeded the time limit and reported an error.

i don't think we have such issue here, from my experience, it mostly report "Condition never satisfied"

Comment (zimulala) [reply tests/realtikvtest/importintotest4/cloud_sdk_test.go:269]: I just think 30 seconds is quite a long time. 
Additionally, this package bazel has set a time limit of 300 seconds. If multiple tests reach 30 seconds, it could easily cause the entire CI test to timeout. I feel that what we are talking about is not a timeout issue.
However, such tests that take more than 30 seconds might be rather low in quality.

**Review by zimulala — APPROVED** [review]
