### PR TITLE
sem, privilege: fix the issue that some privileges cannot be limited

### LINKED ISSUE #64159: SEMv2 failed to limit many privileges
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use the following config:

```
{
...
  "restricted_privileges": [
    "Drop",
    "Config",
    "File",
    "Shutdown",
    "BACKUP_ADMIN",
    "RESTORE_ADMIN",
    "PLACEMENT_ADMIN"
  ],
...
}
```

```
mysql> use test;
Database changed
mysql> CREATE USER 'u1'@'%' IDENTIFIED BY 'password';
Query OK, 0 rows affected (0.01 sec)
mysql> grant drop on *.* to u1@'%';
Query OK, 0 rows affected (0.01 sec)
```

### 2. What did you expect to see? (Required)

Cannot grant `Drop`.

### 3. What did you see instead (Required)

Grant `Drop` successfully.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #64159 

Problem Summary:

### What changed and how does it work?

1. Turn the privilege into upper case before passing it to SEM.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/planbuilder.go [hunk 1]
```diff
@@ -3887,8 +3887,8 @@ func collectVisitInfoFromRevokeStmt(ctx context.Context, sctx base.PlanContext,
 	var allPrivs []mysql.PrivilegeType
 	for _, item := range stmt.Privs {
 		if semv2.IsEnabled() {
-			if (len(item.Name) > 0 && semv2.IsRestrictedPrivilege(item.Name)) ||
-				(len(item.Name) == 0 && semv2.IsRestrictedPrivilege(item.Priv.String())) {
+			if (len(item.Name) > 0 && semv2.IsRestrictedPrivilege(strings.ToUpper(item.Name))) ||
```
Comment (lance6716) [inline pkg/planner/core/planbuilder.go:3909]: maybe inside `IsRestrictedPrivilege` add an intest assertion that make sure the argument is in uppercase

**Comment by lance6716** [comment]
```
--- FAIL: TestIsRestrictedPrivilege (0.00s)
panic: assert failed, privilege name must be uppercase [recovered]
	panic: assert failed, privilege name must be uppercase
```

File: pkg/privilege/privileges/privileges_test.go [hunk 2]
```diff
@@ -2230,16 +2231,19 @@ func TestGrantOptionWithSEMv2(t *testing.T) {
...
 	rootTk.MustExec("GRANT SYSTEM_VARIABLES_ADMIN, FILE ON *.* TO varuser2 WITH GRANT OPTION")
 	rootTk.MustExec("GRANT RESTRICTED_PRIV_ADMIN ON *.* TO varuser3")
 	rootTk.MustExec("GRANT RESTRICTED_PRIV_ADMIN ON *.* TO varuser4")
 	rootTk.MustExec("GRANT SYSTEM_VARIABLES_ADMIN, FILE ON *.* TO varuser4 WITH GRANT OPTION")
+	rootTk.MustExec("GRANT SYSTEM_VARIABLES_ADMIN, DROP ON *.* TO varuser5 WITH GRANT OPTION")
 
-	// SYSTEM_VARIABLES_ADMIN is not restricted, FILE is restricted.
+	// SYSTEM_VARIABLES_ADMIN is not restricted, FILE and Drop are restricted.
 	defer sem.SwitchToSEMForTest(t, sem.V2)()
+	semv2.AddRestrictedPrivilegesForTest("Drop")
```
Comment (lance6716) [inline pkg/privilege/privileges/privileges_test.go:2246]: Also add a cleanup function, just in case that another unit test TestXXX will rely on the default values and can only reveal the problem when both run TestGrantOptionWithSEMv2 and TestXXX

Comment (YangKeao) [reply pkg/privilege/privileges/privileges_test.go:2246]: Done :laughing:
