### PR TITLE
planner: non-deterministic expression can not be pushed down throught the join | tidb-test=pr/2662 

### LINKED ISSUE #65486: planner: predicates that should not be pushed down are pushed down, causing semantic changes in query results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t1(a int, b int);
create table t2(a int, b int);
explain select * from t1 join t2 on t1.a = t2.a where rand() > 0.5;
```

### 2. What did you expect to see? (Required)
In postgres, the filter will be done after the join finshed.
```
yanchengpeng=# create table t1(a int, b int);
CREATE TABLE
yanchengpeng=# create table t2(a int, b int);
CREATE TABLE
yanchengpeng=# explain select * from t1 join t2 on t1.a = t2.a where random() > 0.5;
                            QUERY PLAN                            
------------------------------------------------------------------
 Merge Join  (cost=317.01..839.07 rows=8513 width=16)
   Merge Cond: (t1.a = t2.a)
   Join Filter: (random() > '0.5'::double precision)
   ->  Sort  (cost=158.51..164.16 rows=2260 width=8)
         Sort Key: t1.a
         ->  Seq Scan on t1  (cost=0.00..32.60 rows=2260 width=8)
   ->  Sort  (cost=158.51..164.16 rows=2260 width=8)
         Sort Key: t2.a
         ->  Seq Scan on t2  (cost=0.00..32.60 rows=2260 width=8)
(9 行记录)

```

### 3. What did you see instead (Required)
```
mysql> create table t1(a int, b int);
Query OK, 0 rows affected (0.01 sec)

mysql> create table t2(a int, b int);
Query OK, 0 rows affected (0.02 sec)

mysql> explain select * from t1 join t2 on t1.a = t2.a where rand() > 0.5;
+--------------------------------+----------+-----------+---------------+----------------------------------------------+
| id                             | estRows  | task      | access object | operator info                                |
+--------------------------------+----------+-----------+---------------+----------------------------------------------+
| HashJoin_25                    | 9990.00  | root      |               | inner join, equal:[eq(test.t1.a, test.t2.a)] |
| ├─Selection_37(Build)          | 7992.00  | root      |               | gt(rand(), 0.5)                              |
| │ └─TableReader_40             | 9990.00  | root      |               | data:Selection_39                            |
| │   └─Selection_39             | 9990.00  | cop[tikv] |               | not(isnull(test.t2.a))                       |
| │     └─TableFullScan_38       | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo               |
| └─Selection_29(Probe)          | 7992.00  | root      |               | gt(rand(), 0.5)                              |
|   └─TableReader_32             | 9990.00  | root      |               | data:Selection_31                            |
|     └─Selection_31             | 9990.00  | cop[tikv] |               | not(isnull(test.t1.a))                       |
|       └─TableFullScan_30       | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo               |
+--------------------------------+----------+-----------+---------------+----------------------------------------------+
9 rows in set, 10 warnings (0.00 sec)
```

some predicates are not safe for pushdown, but are currently not handled and still get pushed down, which can change evaluation semantics and lead to incorrect results; this has been observed with non-deterministic functions like RAND(), and similar issues may also affect side-effect functions (e.g. sequence functions) and therefore require special handling.

### 4. What is your TiDB version? (Required)

lastest master

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65486 

Problem Summary:

### What changed and how does it work?

non-deterministic expression can not be pushed down throught the join

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 1]
```diff
@@ -1472,6 +1472,10 @@ func (p *LogicalJoin) ExtractOnCondition(
 					}
 				}
 			}
+			if expression.CheckNonDeterministic(expr) {
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: Why put this check here?
It means it depends on `len(binop.GetArgs()) == 2` being true first.

Comment (guo-shaoge) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Also, after join reorder, this non-deterministic condition could be pushdown as `leftCond/rightCond`.

https://github.com/pingcap/tidb/blob/c6b0d302537a2edc21246ec6202a99995fb4e4fd/pkg/planner/core/rule_join_reorder.go#L693
Check the above function, there is no check for non-deterministic condition when makeing new joins. So I think only checking here is not enough?

Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Only literal expressions of non-deterministic conditions cannot be pushed down to left/right conditions; `a=rand()` is still acceptable, but constant propagation cannot be applied to it.

**Review by guo-shaoge — APPROVED** [review]

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 2]
```diff
@@ -1477,6 +1477,13 @@ func (p *LogicalJoin) ExtractOnCondition(
 		// `columns` may be empty, if the condition is like `correlated_column op constant`, or `constant`,
 		// push this kind of constant condition down according to join type.
 		if len(columns) == 0 {
+			// The IsMutableEffectsExpr check is primarily designed to prevent mutable expressions
+			// like rand() > 0.5 from being pushed down; instead, such expressions should remain
+			// in other conditions.
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go:1482]: You can add comment like:
And checking `len(columns) == 0` first is to let filter like `rand() > tbl.col` to be able pushdown as left/right condition

Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go:1482]: OK
