### PR TITLE
topsql: fix issue of topsql failed catch the running SQL when topsql is enabled in execution

### LINKED ISSUE #33859: topsql failed catch the running SQL when Top SQL is enabled in execution
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create table `t1` and insert into 10000000 rows data.
2. Execute following SQLs in client-A and client-B at same time:

```sql
select count(*),sum(a+b),sum(b+d),sum(c+d*2), sum(d*2+a*b), avg(a*b*d), avg(b*c), avg(c*d),avg(a*b*d), avg(2*b*c), avg(3*c*d), sum(a*b*c), sum(b*d) from t1;
```

```sql
select count(*) from t1 as t0 join t1 as t1 on t0.a != t1.a;
```

3. enable TopSQL during the upper SQL execution:

```sql
set @@global.tidb_enable_top_sql=1;
```

### 2. What did you expect to see? (Required)

TopSQL should catch the running SQL when Top SQL is enabled in execution.

### 3. What did you see instead (Required)

topsql failed catch the running SQL when Top SQL is enabled in execution.

### 4. What is your TiDB version? (Required)

```sql
0d7602eb6551c9a53732be4da37d6ac2f22e375d (HEAD -> master, origin/master)
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #33859

Problem Summary:

Fix issue of topsql failed catch the running SQL when topsql is enabled in execution

### What is changed and how it works?

Always attach the SQL and Plan information whether TopSQL is enabled.

#### Sysbench test

Machine:  AWS c4.4xlarge, 16 cpu core, 32G memory.
Topology: 1*TiDB, 1*TiKV, 1*PD

Disable TopSQL(threads=300) | QPS in This PR | QPS in Master | Impact(%)
-- | -- | -- | --
Point-Get | 37396 | 37642 | 0.6535253175
Read-Only | 19108 | 19343 | 1.214909786

Enable TopSQL(threads=300) | QPS in This PR | QPS in Master | Impact(%)
-- | -- | -- | --
Point-Get | 34671 | 34643 | -0.08082440897
Read-Only | 17701 | 17682 | -0.1074539079

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

1. Create table `t1` and insert into 10000000 rows data.

2. Mock some normal OLTP load by [loadgen](https://github.com/crazycs520/loadgen):

```shell
bin/loadgen payload normal-oltp --rows=1000000
```

3. Execute following SQLs in client-A and client-B at same:

```sql
select count(*),sum(a+b),sum(b+d),sum(c+d*2), sum(d*2+a*b), avg(a*b*d), avg(b*c), avg(c*d),avg(a*b*d), avg(2*b*c), avg(3*c*d), sum(a*b*c), sum(b*d) from t1;
```

```sql
select count(*) from t1 as t0 join t1 as t1 on t0.a != t1.a;
```

4. enable TopSQL during the upper SQL execution:

```sql
set @@global.tidb_enable_top_sql=1;
```

5. Check the TopSQL data.

TiDB: 

image

TiKV

image

Side effects

- [x] Performance regression: Consumes more CPU

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix issue of TopSQL failed to catch the running SQL when TopSQL is enabled in execution.
```

### CODE REVIEW

**Comment by breeswish** [comment]
1. Please update the release note to correctly refactor the bug fix.
2. Please add automated tests to avoid regression.

File: distsql/request_builder.go [hunk 1]
```diff
@@ -307,8 +308,11 @@ func (builder *RequestBuilder) SetFromInfoSchema(pis interface{}) *RequestBuilde
 
 // SetResourceGroupTagger sets the request resource group tagger.
 func (builder *RequestBuilder) SetResourceGroupTagger(sc *stmtctx.StatementContext) *RequestBuilder {
-	if topsqlstate.TopSQLEnabled() {
-		builder.Request.ResourceGroupTagger = sc.GetResourceGroupTagger()
+	tagger := sc.GetResourceGroupTagger()
+	builder.Request.ResourceGroupTagger = func(req *tikvrpc.Request) {
+		if topsqlstate.TopSQLEnabled() {
+			tagger(req)
```
Comment (breeswish) [inline distsql/request_builder.go:314]: This might miss the case that there are long running TiKV requests?

File: executor/adapter.go [hunk 2]
```diff
@@ -1337,17 +1337,45 @@ func (a *ExecStmt) GetTextToLog() string {
...
-		sqlDigest, planDigest := a.getSQLPlanDigest()
-		stats.OnExecutionBegin(sqlDigest, planDigest)
+	if planDigest != nil {
+		planDigestByte = planDigest.Bytes()
+	}
+	stats := a.Ctx.GetStmtStats()
+	if !topsqlstate.TopSQLEnabled() {
+		if isFastPlan(a.Plan) {
+			return ctx
+		}
```
Comment (breeswish) [inline executor/adapter.go:1356]: What if a single point get causes high CPU usage at TiKV side?

File: distsql/request_builder.go (hunk 1 above)
Comment (crazycs520) [reply distsql/request_builder.go:314]: yes. But normally 1 RPC requests shouldn't run too long,

Comment (crazycs520) [reply distsql/request_builder.go:314]: After TopSQL is enabled, the subsequent RPC request will contain the tag.

File: executor/adapter.go (hunk 2 above)
Comment (breeswish) [reply executor/adapter.go:1356]: I do worry about the assumption here. Scanning tombstones, or other similar things like a lot of MVCC versions is an expected behavior. It is not a bug. It just happens rarely.

**Comment by breeswish** [comment]
The benchmark result looks wired. In the benchmark you performed, even without this PR there are no notable performance impact when Top SQL is enabled. Could you perform the benchmark under the scenario that we can really observe 10% performance regressions? I'm afraid that only in these scenarios we can really know how this PR impacts performance.

**Comment by crazycs520** [comment]
> The benchmark result looks wired. In the benchmark you performed, even without this PR there are no notable performance impact when Top SQL is enabled. Could you perform the benchmark under the scenario that we can really observe 10% performance regressions? I'm afraid that only in these scenarios we can really know how this PR impacts performance.


There is a notable performance impact when Top SQL is enabled:

Master | Enable TopSQL | Disable TopSQL | Impact
-- | -- | -- | --
Point-Get | 34643 | 37642 | 7.967164338
Read-Only | 17682 | 19343 | 8.587085767
  |   |   |  
This PR | Enable TopSQL | Disable TopSQL | Impact
Point-Get | 34671 | 37396 | 7.286875602
Read-Only | 17701 | 19108 | 7.363407997

File: executor/adapter.go [hunk 3]
```diff
@@ -1337,17 +1337,45 @@ func (a *ExecStmt) GetTextToLog() string {
...
-	if stats := a.Ctx.GetStmtStats(); stats != nil && topsqlstate.TopSQLEnabled() {
-		sqlDigest, planDigest := a.getSQLPlanDigest()
-		stats.OnExecutionBegin(sqlDigest, planDigest)
+	if planDigest != nil {
+		planDigestByte = planDigest.Bytes()
+	}
+	stats := a.Ctx.GetStmtStats()
+	if !topsqlstate.TopSQLEnabled() {
+		if isFastPlan(a.Plan) {
+			return ctx
```
Comment (zhongzc) [inline executor/adapter.go:1355]: explanation/comment needed

File: executor/executor.go [hunk 4]
```diff
@@ -299,6 +300,9 @@ func Next(ctx context.Context, e Executor, req *chunk.Chunk) error {
 	if trace.IsEnabled() {
 		defer trace.StartRegion(ctx, fmt.Sprintf("%T.Next", e)).End()
 	}
+	if topsqlstate.TopSQLEnabled() && sessVars.StmtCtx.IsSQLAndPlanRegistered.CAS(false, true) {
+		registerSQLAndPlanInExecForTopSQL(sessVars)
+	}
```
Comment (zhongzc) [inline executor/executor.go:305]:
```suggestion
	if topsqlstate.TopSQLEnabled() {
		registerSQLAndPlanInExecForTopSQL(sessVars)
	}
```

Comment (zhongzc) [reply executor/executor.go:305]: explanation/comment needed

Comment (crazycs520) [reply executor/executor.go:305]: why?

File: server/tidb_test.go [hunk 5]
```diff
@@ -1293,6 +1294,80 @@ func TestPessimisticInsertSelectForUpdate(t *testing.T) {
...
+				time.Sleep(2 * time.Millisecond)
+				topsqlstate.EnableTopSQL()
+				atomic.StoreInt64(&needEnableTopSQL, 0)
+			}
+			time.Sleep(time.Millisecond)
+		}
+	}()
+	execFn := func(db *sql.DB) {
+		dbt := testkit.NewDBTestKit(t, db)
+		atomic.StoreInt64(&needEnableTopSQL, 1)
```
Comment (zhongzc) [inline server/tidb_test.go:1357]: why enable topsql in such a complicated way?

File: session/session.go [hunk 6]
```diff
@@ -1590,7 +1590,8 @@ func (s *session) ParseWithParams(ctx context.Context, sql string, args ...inter
 		if digest != nil {
 			// Reset the goroutine label when internal sql execute finish.
 			// Specifically reset in ExecRestrictedStmt function.
-			topsql.AttachSQLInfo(ctx, normalized, digest, "", nil, s.sessionVars.InRestrictedSQL)
+			s.sessionVars.StmtCtx.IsSQLRegistered.Store(true)
+			topsql.AttachSQLInfo(ctx, normalized, digest, s.sessionVars.InRestrictedSQL)
```
Comment (zhongzc) [inline session/session.go:1594]: why is here still a `topsqlstate.TopSQLEnabled()`?

File: util/topsql/stmtstats/kv_exec_count.go [hunk 7]
```diff
@@ -49,6 +50,9 @@ type KvExecCounter struct {
 // the TiKV dimension.
 func (c *KvExecCounter) RPCInterceptor() interceptor.RPCInterceptor {
 	return func(next interceptor.RPCInterceptorFunc) interceptor.RPCInterceptorFunc {
+		if !topsqlstate.TopSQLEnabled() {
```
Comment (zhongzc) [inline util/topsql/stmtstats/kv_exec_count.go:53]: How if
```suggestion
                return func(target string, req *tikvrpc.Request) (*tikvrpc.Response, error) {
			if !topsqlstate.TopSQLEnabled() {
			    c.mark(target)
			}
			return next(target, req)
		}
```

File: util/topsql/topsql.go [hunk 8]
```diff
@@ -79,25 +79,33 @@ func Close() {
...
+// AttachSQLInfo attach the sql information into Top SQL and register the SQL meta information.
+func AttachSQLInfo(ctx context.Context, normalizedSQL string, sqlDigest *parser.Digest, isInternal bool) context.Context {
+	if sqlDigest == nil || len(sqlDigest.Bytes()) == 0 {
+		return ctx
 	}
+	sqlDigestBytes := sqlDigest.Bytes()
+	ctx = collector.CtxWithSQLDigest(ctx, sqlDigestBytes)
+	pprof.SetGoroutineLabels(ctx)
+
+	linkSQLTextWithDigest(sqlDigestBytes, normalizedSQL, isInternal)
```
Comment (zhongzc) [inline util/topsql/topsql.go:107]: duplicated with RegisterSQL?

File: server/tidb_test.go (hunk 5 above)
Comment (crazycs520) [reply server/tidb_test.go:1357]: Any advice? Since I need to enable topsql when the SQL in execution.

File: session/session.go (hunk 6 above)
Comment (crazycs520) [reply session/session.go:1594]: No need to attach SQL info here, since later will always attach the SQL and plan information.

File: util/topsql/topsql.go (hunk 8 above)
Comment (crazycs520) [reply util/topsql/topsql.go:107]: No, if this function is called, then `RegisterSQL` won't be call anymore.

File: util/topsql/stmtstats/kv_exec_count.go (hunk 7 above)
Comment (crazycs520) [reply util/topsql/stmtstats/kv_exec_count.go]: I prefer the original, since when topsql is disabled, there will one less function call.

File: server/tidb_test.go (hunk 5 above)
Comment (breeswish) [reply server/tidb_test.go:1357]: Our propose is to catch requests that is not tagged. How about bypassing the Top SQL layer at all and only check these request tags?

Comment (crazycs520) [reply server/tidb_test.go:1354]: This PR propose is to catch the running SQL when topsql is enabled in execution.
Check request not tagged is already checked by https://github.com/pingcap/tidb/pull/33623

File: distsql/request_builder.go [hunk 9]
```diff
@@ -307,9 +306,7 @@ func (builder *RequestBuilder) SetFromInfoSchema(pis interface{}) *RequestBuilde
 
 // SetResourceGroupTagger sets the request resource group tagger.
 func (builder *RequestBuilder) SetResourceGroupTagger(sc *stmtctx.StatementContext) *RequestBuilder {
```
Comment (breeswish) [inline distsql/request_builder.go:308]: A better API design should be `SetResourceGroupTagger(resourceGroupTagger)`

cc @mornyx

File: executor/adapter.go [hunk 10]
```diff
@@ -1337,17 +1337,48 @@ func (a *ExecStmt) GetTextToLog() string {
...
-	if stats := a.Ctx.GetStmtStats(); stats != nil && topsqlstate.TopSQLEnabled() {
-		sqlDigest, planDigest := a.getSQLPlanDigest()
-		stats.OnExecutionBegin(sqlDigest, planDigest)
+	if planDigest != nil {
+		planDigestByte = planDigest.Bytes()
+	}
+	stats := a.Ctx.GetStmtStats()
+	if !topsqlstate.TopSQLEnabled() {
+		// Fast plan means the SQL will run very fast, and won't consume too much CPU.
+		// So no need to attach SQL and plan info to catch those running SQL.
```
Comment (breeswish) [inline executor/adapter.go:1355]: better to explain that we are doing this for performance consideration. We do not drop them because they are fast. We drop them because they impact performance and drop them does not cause notable accuracy issue.

File: executor/adapter.go [hunk 11]
```diff
@@ -1337,17 +1337,48 @@ func (a *ExecStmt) GetTextToLog() string {
 	return sql
 }
 
-func (a *ExecStmt) observeStmtBeginForTopSQL() {
+func (a *ExecStmt) observeStmtBeginForTopSQL(ctx context.Context) context.Context {
```
Comment (breeswish) [inline executor/adapter.go:1340]: Note (no need to change in this PR): a better API design should be a hook framework for statement begin and statement finish events, instead of something xxxForTopSQL. (The observer pattern)

cc @mornyx @zhongzc

File: executor/adapter.go [hunk 12]
```diff
@@ -1337,17 +1337,48 @@ func (a *ExecStmt) GetTextToLog() string {
...
+	}
+
+	if stats != nil {
+		stats.OnExecutionBegin(sqlDigestByte, planDigestByte)
 		// This is a special logic prepared for TiKV's SQLExecCount.
-		vars.StmtCtx.KvExecCounter = stats.CreateKvExecCounter(sqlDigest, planDigest)
+		sc.KvExecCounter = stats.CreateKvExecCounter(sqlDigestByte, planDigestByte)
+	}
+
+	isSQLRegistered := sc.IsSQLRegistered.Load()
```
Comment (breeswish) [inline executor/adapter.go:1372]: I'm not sure, but the relationship looks wired. Could you confirm are there better paths?

The current path is:

ExecStatement -> SessionVars -> StatementCtx -> IsSQLRegistered

So, for example, is it possible to be:

ExecStatement -> IsSQLRegistered?

File: executor/adapter.go [hunk 13]
```diff
@@ -1337,17 +1337,48 @@ func (a *ExecStmt) GetTextToLog() string {
...
+		// Fast plan means the SQL will run very fast, and won't consume too much CPU.
+		// So no need to attach SQL and plan info to catch those running SQL.
+		if isFastPlan(a.Plan) {
+			return ctx
+		}
+		// Always attach the SQL and plan info uses to catch the running SQL when Top SQL is enabled in execution.
+		if stats != nil {
+			sc.KvExecCounter = stats.CreateKvExecCounter(sqlDigestByte, planDigestByte)
+		}
+		return topsql.AttachSQLAndPlanInfo(ctx, sqlDigest, planDigest)
```
Comment (breeswish) [inline executor/adapter.go:1363]: `OnExecutionBegin` will be skipped executed after this return?

File: distsql/request_builder.go (hunk 9 above)
Comment (mornyx) [reply distsql/request_builder.go:308]: LGTM, the declaration of this method can be simplified now.

File: executor/adapter.go (hunk 13 above)
Comment (crazycs520) [reply executor/adapter.go:1363]: Yes, since it has a performance impact when TopSQL is disabled.

Comment (breeswish) [reply executor/adapter.go:1363]: Looks like there are potential performance improvements here @mornyx @zhongzc

Comment (crazycs520) [reply executor/adapter.go:1363]: In my sysbench point-get test, `OnExecutionBegin` and `OnExecutionFinished` have around %3 QPS impact.

Comment (mornyx) [reply executor/adapter.go:1363]: Here is the previous implementation:
```go
func (a *ExecStmt) observeStmtBeginForTopSQL() {
	vars := a.Ctx.GetSessionVars()
	if vars == nil {
		return
	}
	if stats := a.Ctx.GetStmtStats(); stats != nil && topsqlstate.TopSQLEnabled() {
		sqlDigest, planDigest := a.getSQLPlanDigest()
		stats.OnExecutionBegin(sqlDigest, planDigest)
		// This is a special logic prepared for TiKV's SQLExecCount.
		vars.StmtCtx.KvExecCounter = stats.CreateKvExecCounter(sqlDigest, planDigest)
	}
}
```
Note `if stats := a.Ctx.GetStmtStats(); stats != nil && topsqlstate.TopSQLEnabled()`. This means that the overhead of `OnExecutionBegin()` does not exist before when TopSQL is not enabled.

Comment (mornyx) [reply executor/adapter.go:1363]: By the way, when TopSQL is enabled, I think the overhead of `OnExecutionBegin()` is mostly about **lock**. I think we can consider learning `nanolog`'s lock-free-buffer pattern to optimize performance here.

Comment (breeswish) [reply executor/adapter.go:1363]: How about let's shard the lock into N? It should be very easy to implement and effectively enough to verify the lock cost.

Comment (mornyx) [reply executor/adapter.go:1363]: > How about let's shard the lock into N? It should be very easy to implement and effectively enough to verify the lock cost.

Can do a test, I think it will work. Since the session is serial, the only scenario where lock contention occurs is the collection of background goroutine. So in theory, segmented locks can effectively reduce the possibility of sessions being blocked by background goroutine.

Comment (zhongzc) [reply executor/adapter.go:1363]: Not from lock. I tried to remove all locks previously and find the performance impact was not reduced much.

Comment (mornyx) [reply executor/adapter.go:1363]: > Not from lock. I tried to remove all locks previously and found the performance impact was not reduced much.

This seems a bit strange, the logic of `OnExecutionBegin` is very simple (get an item from the map, then increment it). This shouldn't cause a 3% QPS regression...

Comment (zhongzc) [reply executor/adapter.go:1363]: map-assign and map-access have become the main cause. A more complicated lock implementation will introduce extra overhead and worse performance.

Comment (breeswish) [reply executor/adapter.go:1363]: why would a single map-assign and access cause this kind of drop? It doesn't make sense.

File: executor/adapter.go [hunk 14]
```diff
@@ -332,17 +332,19 @@ func (a *ExecStmt) RebuildPlan(ctx context.Context) (int64, error) {
...
-	normalizedPlan, planDigest := getPlanDigest(a.Ctx, a.Plan)
-	if len(normalizedPlan) == 0 {
-		return ctx
+	switch p.(type) {
+	case *plannercore.PointGetPlan:
+		return true
+	case *plannercore.PhysicalTableDual:
+		return true
+	case *plannercore.Set:
+		return true
```
Comment (breeswish) [inline executor/adapter.go:345]: Supply sample SQL as a comment

**Comment by crazycs520** [comment]
The latest sysbench result is here:

Machine:  AWS c4.4xlarge, 16 cpu core, 32G memory.
Topology: 1*TiDB, 1*TiKV, 1*PD

Disable TopSQL(threads=300) | QPS in This PR | QPS in Master | Impact
-- | -- | -- | --
Point-Get | 37034 | 37169 | 0.3632058974
Read-Only | 18921 | 19274 | 1.831482827


Enable TopSQL(threads=300) | QPS in This PR | QPS in Master | Impact
-- | -- | -- | --
Point-Get | 34915.5 | 34765 | -0.432906659
Read-Only | 18463 | 18513 | 0.270080484

**Review by zhongzc — APPROVED** [review]

File: executor/executor.go [hunk 15]
```diff
@@ -1797,8 +1801,8 @@ func ResetContextOfStmt(ctx sessionctx.Context, s ast.StmtNode) (err error) {
 			goCtx = pprof.WithLabels(goCtx, pprof.Labels("sql", util.QueryStrForLog(prepareStmt.NormalizedSQL)))
 			pprof.SetGoroutineLabels(goCtx)
 		}
-		if topsqlstate.TopSQLEnabled() && prepareStmt.SQLDigest != nil {
-			topsql.AttachSQLInfo(goCtx, prepareStmt.NormalizedSQL, prepareStmt.SQLDigest, "", nil, vars.InRestrictedSQL)
+		if prepareStmt.SQLDigest != nil {
+			AttachSQLInfoForTopSQL(goCtx, sc, prepareStmt.NormalizedSQL, prepareStmt.SQLDigest, vars.InRestrictedSQL)
```
Comment (mornyx) [inline executor/executor.go:1805]: Why not use the returned `context.Context` here?

**Review by mornyx — COMMENTED** [review]
The rest LGTM

File: executor/executor.go (hunk 15 above)
Comment (crazycs520) [reply executor/executor.go:1805]: Since `context.Context` won't be returned outside, And it's ok to not use the `context.Context`.

**Review by mornyx — APPROVED** [review]

File: executor/adapter.go [hunk 16]
```diff
@@ -332,17 +332,25 @@ func (a *ExecStmt) RebuildPlan(ctx context.Context) (int64, error) {
 	return a.InfoSchema.SchemaMetaVersion(), nil
 }
 
-func (a *ExecStmt) setPlanLabelForTopSQL(ctx context.Context) context.Context {
-	if !topsqlstate.TopSQLEnabled() {
-		return ctx
+func isFastPlan(p plannercore.Plan) bool {
```
Comment (breeswish) [inline executor/adapter.go:335]: Is it possible to have some unit tests to ensure that isFastPlan is indeed working for these type of SQLs you give in the comment?

File: util/topsql/topsql.go [hunk 17]
```diff
@@ -107,7 +115,31 @@ func AttachSQLInfo(ctx context.Context, normalizedSQL string, sqlDigest *parser.
...
-				logutil.BgLogger().Info("attach SQL info", zap.String("sql", normalizedSQL), zap.Bool("has-plan", len(normalizedPlan) > 0))
+				logutil.BgLogger().Info("attach SQL info", zap.String("sql", normalizedSQL))
+			}
+		}
+	})
+	return ctx
+}
+
+// AttachSQLAndPlanInfo attach the sql and plan information into Top SQL
+func AttachSQLAndPlanInfo(ctx context.Context, sqlDigest *parser.Digest, planDigest *parser.Digest) context.Context {
```
Comment (breeswish) [inline util/topsql/topsql.go:126]: Why `linkSQLTextWithDigest` is called in `AttachSQLInfo` but is not called in `AttachSQLAndPlanInfo`?

File: sessionctx/stmtctx/stmtctx.go [hunk 18]
```diff
@@ -243,6 +243,11 @@ type StatementContext struct {
 
 	// RCCheckTS indicates the current read-consistency read select statement will use `RCCheckTS` path.
 	RCCheckTS bool
+
+	// IsSQLRegistered uses to indicate whether the SQL has been registered for TopSQL.
+	IsSQLRegistered atomic2.Bool
+	// IsSQLAndPlanRegistered uses to indicate whether the SQL and plan has been registered for TopSQL.
+	IsSQLAndPlanRegistered atomic2.Bool
```
Comment (breeswish) [inline sessionctx/stmtctx/stmtctx.go:250]: Will it happen that `IsSQLAndPlanRegistered == true` while `IsSQLRegistered == false`?

**Review by breeswish — COMMENTED** [review]
I feel like I'm very easy to make mistakes when reviewing this PR, or coding based on this PR. There are too many similar concepts located in different packages served for similar purposes. There is no clear boundary about the functionalities. It is not a good experience and can be a bed of future bugs.

File: sessionctx/stmtctx/stmtctx.go (hunk 18 above)
Comment (crazycs520) [reply sessionctx/stmtctx/stmtctx.go:250]: It will happen, but it doesn't matter, the code can make sure if `IsSQLAndPlanRegistered ` is true, then the `SQL` and `plan` must be registerd.

File: util/topsql/topsql.go (hunk 17 above)
Comment (crazycs520) [reply util/topsql/topsql.go:126]: Maybe rename the function `AttachSQLInfo ` to `AttachAndRegisterSQLInfo` is better.

Since when topsql is disabled, when calling `AttachSQLAndPlanInfo` but not register SQL/Plan info for getting better performance.

**Review by mornyx — APPROVED** [review]

**Comment by crazycs520** [comment]
@ti-chi-bot

**Comment by crazycs520** [comment]
@ti-chi-bot
/merge

**Comment by crazycs520** [comment]
@ti-chi-bot

**Review by mornyx — APPROVED** [review]

**Review by zhongzc — APPROVED** [review]

**Review by mornyx — APPROVED** [review]

**Review by breeswish — APPROVED** [review]
A green approval on behalf of the bot.
