### PR TITLE
txn: fix retry with non autocommit

### LINKED ISSUE #22874: txn: non autocommit mode transaction retry will get incorrect result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```

drop table if exists t;
CREATE TABLE `t` (  `pk` varchar(50) NOT NULL,  `c1` varchar(50) DEFAULT NULL,  `c2` varchar(50) DEFAULT NULL,  
KEY `k1` (`c1`,`c2`),  PRIMARY KEY (`pk`));
insert into t values('1', '10', '100');
--

// start a non autocommit mode transaction.
// use the bug branch code to do the following SQL, force the commit fail and retry.
// https://github.com/cfzjywxk/tidb/tree/debug_branch


set set tidb_disable_txn_auto_retry = 0;
set autocommit = 0;
// trigger auto retry for this transaction.
update t set c1 = 11 where pk = '1';
update t set c2 = 101 where pk = '1';
commit;
```

### 2. What did you expect to see? (Required)
- admin check table t will return success.
- correct row data written.

### 3. What did you see instead (Required)
- admin check table report error.
- incorrect row data written.

### 4. What is your TiDB version? (Required)
release-4.0 branch `631dbfdc3215a6c448b3e50ed57952f072681cb3` commit hash

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #22874 

Problem Summary:
The txn retry for non autocommit mode does not set flag correctly like `mysql.ServerStatusInTrans`.

### What is changed and how it works?

What's Changed:
- ~~Try to make transaction activiation use the same logic for common and retrying transactions.~~
- ~~Make multiple transaction activiation interfaces use the same inner activiation logic, avoid maintaining duplicate codes.(There is still some refactor work need to do for this part, these transaction interfaces are diffuicult to distinguish and use).~~
- ~~There are three different transaction activiation interfaces, `NewTxn`, `txn.Txn(true)`, `initTxnWithStartTS`, and they have some their own initilizing logic.~~
- Above issues will be recorded as refactor tasks in the future, to lower the changing risk in release branch.
- Add flag for the multiple statments transaction retry path.

How it Works:

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- Fix the issue that transaction retry with non-autocommit mode may write incorrect data.

### CODE REVIEW

File: session/session.go [hunk 1]
```diff
@@ -2257,6 +2250,7 @@ func (s *session) InitTxnWithStartTS(startTS uint64) error {
 	if err != nil {
 		return err
 	}
+	s.initTxn()
```
Comment (cfzjywxk) [inline session/session.go:2253]: Will this bring some side effects?

Comment (jackysp) [reply session/session.go:2253]: PTAL @tiancaiamao , thx!

**Comment by cfzjywxk** [comment]
Or shold we just change it back to use `PrepareTxnCtx` before retry instead of `NewTxn`. 
For the panic issue #21284, we just add a validation check for txn and use it if it's valid at [L593](https://github.com/pingcap/tidb/blob/release-4.0/session/txn.go#L593), to solve the panic issue.
This will reduce the change size lower the change risk.

@coocood @lysu @youjiali1995 @wjhuang2016 @jackysp

**Comment by youjiali1995** [comment]
> Or shold we just change it back to use `PrepareTxnCtx` before retry instead of `NewTxn`.
> For the panic issue #21284, we just add a validation check for txn and use it if it's valid at [L593](https://github.com/pingcap/tidb/blob/release-4.0/session/txn.go#L593), to solve the panic issue.
> This will reduce the change size lower the change risk.
> 
> @coocood @lysu @youjiali1995 @wjhuang2016 @jackysp

Agree with it. We can merge changes of this PR to master.

**Comment by coocood** [comment]
> Or shold we just change it back to use `PrepareTxnCtx` before retry instead of `NewTxn`.
> For the panic issue #21284, we just add a validation check for txn and use it if it's valid at [L593](https://github.com/pingcap/tidb/blob/release-4.0/session/txn.go#L593), to solve the panic issue.
> This will reduce the change size lower the change risk.
> 
> @coocood @lysu @youjiali1995 @wjhuang2016 @jackysp

+1

**Comment by jackysp** [comment]
> Or shold we just change it back to use `PrepareTxnCtx` before retry instead of `NewTxn`.
> For the panic issue #21284, we just add a validation check for txn and use it if it's valid at [L593](https://github.com/pingcap/tidb/blob/release-4.0/session/txn.go#L593), to solve the panic issue.
> This will reduce the change size lower the change risk.
> 
> @coocood @lysu @youjiali1995 @wjhuang2016 @jackysp

The `set` statement should be retried in the same transaction with other history statements. If it is the first statement of the history and the session only prepared a transaction but didn't active it, the `set` statement may make the retry results not as expected. e.g.

```sql
set autocommit = 0;
select * from t;
set @a=@@tidb_current_ts;
update t set startts = @a where xxx;
commit;
```

File: session/session.go (hunk 1 above)
Comment (cfzjywxk) [reply session/session.go]: To lower the risk, changes to `NewTxn` and `initTxnWithStartTS` are removed.

**Comment by coocood** [comment]
LGTM

File: session/session.go [hunk 2]
```diff
@@ -670,6 +670,15 @@ func (s *session) retry(ctx context.Context, maxCnt uint) (err error) {
 					s.sessionVars.TxnCtx.IsPessimistic = true
 				}
 			}
+			// Complete the missing settings using `NewTxn` compared with lazy activation `txn.Txn(true)`.
+			// More refactors are needed in the future to make the inner logic of transaction activation
+			// interfaces the same.
+			if s.sessionVars.TxnCtx.IsPessimistic {
```
Comment (jackysp) [inline session/session.go:676]: I think pessimistic transactions could not retry.

Comment (cfzjywxk) [reply session/session.go:676]: It's used to decide the retrying mode using optimistic or pessimistic mode, the retryable condition is not affected by this. Or do you mean if the pessimsitic mode retrying has failed, the retry should abort?

**Review by AilinKid — COMMENTED** [review]
LGTM

File: session/session.go [hunk 3]
```diff
@@ -664,11 +664,8 @@ func (s *session) retry(ctx context.Context, maxCnt uint) (err error) {
 			if err != nil {
 				return err
 			}
-			pessTxnConf := config.GetGlobalConfig().PessimisticTxn
-			if pessTxnConf.Enable {
-				if s.sessionVars.TxnMode == ast.Pessimistic {
-					s.sessionVars.TxnCtx.IsPessimistic = true
-				}
+			if !s.sessionVars.IsAutocommit() {
+				s.sessionVars.SetStatusFlag(mysql.ServerStatusInTrans, true)
```
Comment (youjiali1995) [inline session/session.go:668]: I think it should be set even if `autocommit` is on. For example, if the transaction is committed by `set autocommit = 1`, the `mysql.ServerStatusInTrans` flag won't be set and the point-get executor still reads data from the store's snapshot.

Comment (cfzjywxk) [reply session/session.go:668]: Thanks for the reminding, I'll add test cases to cover such path.

**Review by jackysp — COMMENTED** [review]
LGTM

**Review by youjiali1995 — COMMENTED** [review]
/lgtm
