### PR TITLE
log-backup: filter out unnecessary metadata files

### LINKED ISSUE #36648: br OOM during PiTR restore & log truncate
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run br log truncate

### 2. What did you expect to see? (Required)
1. BR log truncate should succeed

### 3. What did you see instead (Required)
1. Br log truncate fails due to OOM

image

image

### 4. What is your TiDB version? (Required)
6.2.0

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

Issue Number: close #36648

Problem Summary:
Even we are going to truncate / restore a subset of all logs, the current implementation would try to read all metadata.
This may lead to OOM when there are too many meta files.

### What is changed and how it works?
After this PR, when we executing `restore point` or `log truncate`, we would filter out metadata that is obviously should not be considered. They are:
For `restore point`: `MinTS > RestoreTS || MaxTS < ShiftedStartTS`
For `log truncate`: `MinTS > UntilTS`

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)
image
image

The image above shows the different memory usage between restoring full log and restoring a subset of log.

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

File: br/pkg/restore/stream_metas.go [hunk 1]
```diff
@@ -25,8 +26,7 @@ type StreamMetadataSet struct {
 	BeforeDoWriteBack func(path string, last, current *backuppb.Metadata) (skip bool)
 }
 
-// LoadFrom loads data from an external storage into the stream metadata set.
-func (ms *StreamMetadataSet) LoadFrom(ctx context.Context, s storage.ExternalStorage) error {
+func (ms *StreamMetadataSet) LoadUntil(ctx context.Context, s storage.ExternalStorage, until uint64) error {
```
Comment (3pointer) [inline br/pkg/restore/stream_metas.go:29]: you can add some comments

**Review by 3pointer — APPROVED** [review]
rest LGTM
