### PR TITLE
test: fix data race of Kill

### LINKED ISSUE #27822: data race in `executor_test.(*mockSessionManager2).Kill()`
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
[2021-09-06T02:30:20.970Z] WARNING: DATA RACE
[2021-09-06T02:30:20.970Z] Write at 0x00c04216beb8 by goroutine 620:
[2021-09-06T02:30:20.970Z]   github.com/pingcap/tidb/executor_test.(*mockSessionManager2).Kill()
[2021-09-06T02:30:20.970Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/prepared_test.go:160 +0x44
[2021-09-06T02:30:20.970Z]   github.com/pingcap/tidb/util/expensivequery.(*Handle).Run()
[2021-09-06T02:30:20.970Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:75 +0x2ce
[2021-09-06T02:30:20.970Z] 
[2021-09-06T02:30:20.970Z] Previous read at 0x00c04216beb8 by goroutine 686:
[2021-09-06T02:30:20.970Z]   github.com/pingcap/tidb/executor_test.(*testSuite12).TestPreparedStmtWithHint()
[2021-09-06T02:30:20.970Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/prepared_test.go:196 +0x524
[2021-09-06T02:30:20.970Z]   runtime.call16()
[2021-09-06T02:30:20.970Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-09-06T02:30:20.970Z]   reflect.Value.Call()
[2021-09-06T02:30:20.970Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3b
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-09-06T02:30:20.970Z] 
[2021-09-06T02:30:20.970Z] Goroutine 620 (running) created at:
[2021-09-06T02:30:20.970Z]   github.com/pingcap/tidb/executor_test.(*testSuite12).TestPreparedStmtWithHint()
[2021-09-06T02:30:20.970Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/prepared_test.go:193 +0x404
[2021-09-06T02:30:20.970Z]   runtime.call16()
[2021-09-06T02:30:20.970Z]       /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
[2021-09-06T02:30:20.970Z]   reflect.Value.Call()
[2021-09-06T02:30:20.970Z]       /usr/local/go/src/reflect/value.go:337 +0xd8
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3b
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11d
[2021-09-06T02:30:20.970Z] 
[2021-09-06T02:30:20.970Z] Goroutine 686 (running) created at:
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).forkCall()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4cc
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).forkTest()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1c4
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).doRun()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x144
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.(*suiteRunner).run()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0x144
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.Run()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x5a
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.RunAll()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:136 +0x968
[2021-09-06T02:30:20.970Z]   github.com/pingcap/check.TestingT()
[2021-09-06T02:30:20.970Z]       /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x756
[2021-09-06T02:30:20.970Z]   github.com/pingcap/tidb/executor_test.TestT()
[2021-09-06T02:30:20.970Z]       /home/jenkins/agent/workspace/tidb-unit-test-nightly/go/src/github.com/pingcap/tidb/executor/executor_test.go:109 +0x335
[2021-09-06T02:30:20.970Z]   testing.tRunner()
[2021-09-06T02:30:20.970Z]       /usr/local/go/src/testing/testing.go:1193 +0x202
[2021-09-06T02:30:20.970Z] ==================
```

### 1. Minimal reproduce step (Required)

in ci https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb-unit-test-nightly/runs/10245/nodes/104/steps/269/log/?start=0

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #27822 

Problem Summary:

### What is changed and how it works?

memory order is not guaranteed, use channel for sync 

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Check List 

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

File: executor/prepared_test.go [hunk 1]
```diff
@@ -157,7 +158,7 @@ func (sm *mockSessionManager2) GetProcessInfo(id uint64) (pi *util.ProcessInfo,
 	return
 }
 func (sm *mockSessionManager2) Kill(connectionID uint64, query bool) {
-	sm.killed = true
```
Comment (tiancaiamao) [inline executor/prepared_test.go:160]: I suspect the root cause is that the kill command is send more than one time.
Because if the `killed` is not set, the query will not exit (assume the test logic is correct).
So set `killed` = true happens before the query execution.
and query execution happens before check `killed` flag, (obviously they are in the same goroutine)
... that mean line 196 check `killed` flag should happens before the set `killed` operation...

From the above deduction, checking flag and setting flag operation have the happens before relationship, they happen in different time and should data race.

The kill command execute twice is more likely to be the root reason.

Comment (tiancaiamao) [reply executor/prepared_test.go:160]: Assume the `Kill()` is executed more than once, change to channel may cause the kill operation block, and goroutine leak in the test.

How about changing to the atomic way?

Comment (ichn-hu) [reply executor/prepared_test.go:160]: I see, it is indeed possible for Kill to be executed more than once, I changed it to use atomic.

**Comment by ichn-hu** [comment]
@tiancaiamao @wjhuang2016 PTAL

**Review by ngaut — APPROVED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]
