### PR TITLE
store: return right error when to get non-200 http code from pd

### LINKED ISSUE #37983: return wrong error when TIDB GET http://{}:{}/tables/{}/{}/disk-usage
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

GET http://{}:{}/tables/{}/{}/disk-usage

### 2. What did you expect to see? (Required)

return 200.

### 3. What did you see instead (Required)

Response Status: 400
Response Content: b'invalid character r looking for beginning of value'

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #37983

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tiancaiamao — APPROVED** [review]

File: store/helper/helper.go [hunk 1]
```diff
@@ -1001,7 +1001,9 @@ func (h *Helper) GetPDRegionStats(tableID int64, stats *PDRegionStats, noIndexSt
 			logutil.BgLogger().Error("err", zap.Error(err))
 		}
 	}()
-
+	if resp.StatusCode != http.StatusOK {
+		return errors.New("GetPDRegionStats returns error")
+	}
```
Comment (xhebox) [inline store/helper/helper.go:1006]: Just a suggestion, we can read the body to returrn more verbose error.

Comment (hawkingrei) [reply store/helper/helper.go:1006]: I have a plan to implement a better HTTP framework to unite the usage like these cases.

Comment (hawkingrei) [reply store/helper/helper.go:1006]: I maybe improve this for this PR.

Comment (hawkingrei) [reply store/helper/helper.go:1010]: @xhebox PTAL

**Review by tiancaiamao — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
