### PR TITLE
*: insert/update or explain should not trigger table cache condition

### LINKED ISSUE #29528: randomly receive signal SIGSEGV in `executor` test
### 1. Minimal reproduce step (Required)

Randomly in ci `tidb_ghpr_check_2`

### 2. What did you expect to see? (Required)

At least no signal SIGSEGV

### 3. What did you see instead (Required)

Receive signal SIGSEGV

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/43743/pipeline
```
[2021-11-06T12:51:29.308Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-11-06T12:51:29.308Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x3568d72]
[2021-11-06T12:51:29.308Z] 
[2021-11-06T12:51:29.308Z] goroutine 19551 [running]:
[2021-11-06T12:51:29.308Z] github.com/pingcap/tidb/session.(*LazyTxn).StartTS(0xc08c522a10, 0xc09110a7c8)
[2021-11-06T12:51:29.308Z] 	<autogenerated>:1 +0x32
[2021-11-06T12:51:29.308Z] github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1(0x7f72c00681f8, 0xc090b92f00, 0xc000ab04e0, 0x48a7fe0, 0xc08c522a10)
[2021-11-06T12:51:29.308Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4163 +0x38
[2021-11-06T12:51:29.308Z] created by github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource
[2021-11-06T12:51:29.308Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4162 +0x2525
[2021-11-06T12:51:29.308Z] FAIL	github.com/pingcap/tidb/executor	4.885s
```
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/43740/pipeline/
```
[2021-11-06T11:25:20.737Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x35685f2]
[2021-11-06T11:25:20.737Z] 
[2021-11-06T11:25:20.737Z] goroutine 18877 [running]:
[2021-11-06T11:25:20.737Z] github.com/pingcap/tidb/session.(*LazyTxn).StartTS(0xc08a3a1810, 0xc07844efc8)
[2021-11-06T11:25:20.737Z] 	<autogenerated>:1 +0x32
[2021-11-06T11:25:20.737Z] github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1(0x7f00bd9a4220, 0xc09352b540, 0xc000530680, 0x48a7c80, 0xc08a3a1810)
[2021-11-06T11:25:20.737Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4163 +0x38
[2021-11-06T11:25:20.737Z] created by github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource
[2021-11-06T11:25:20.737Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4162 +0x2525
[2021-11-06T11:25:20.737Z] FAIL	github.com/pingcap/tidb/executor	4.718s
```
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/43745/pipeline
```
[2021-11-06T13:05:44.124Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-11-06T13:05:44.124Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x3568d72]
[2021-11-06T13:05:44.124Z] 
[2021-11-06T13:05:44.124Z] goroutine 20594 [running]:
[2021-11-06T13:05:44.124Z] github.com/pingcap/tidb/session.(*LazyTxn).StartTS(0xc00961a210, 0xc004993140)
[2021-11-06T13:05:44.124Z] 	<autogenerated>:1 +0x32
[2021-11-06T13:05:44.124Z] github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1(0x7fd6001aac68, 0xc05a972640, 0xc07ce7a1a0, 0x48a7fe0, 0xc00961a210)
[2021-11-06T13:05:44.124Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4163 +0x38
[2021-11-06T13:05:44.124Z] created by github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource
[2021-11-06T13:05:44.124Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4162 +0x2525
[2021-11-06T13:05:44.124Z] FAIL	github.com/pingcap/tidb/executor	5.559s
```

### 4. What is your TiDB version? (Required)

master, commit e897ba12ad1a080096d3b4af1e90e4177fd1ea9d

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?
Close #29528.

Problem Summary:

A tiny fix after https://github.com/pingcap/tidb/pull/29184

```
mysql> explain select * from t;
+-----------------------+---------+-----------+---------------+--------------------------------+
| id                    | estRows | task      | access object | operator info                  |
+-----------------------+---------+-----------+---------------+--------------------------------+
| TableReader_5         | 1.00    | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-----------------------+---------+-----------+---------------+--------------------------------+
2 rows in set (0.00 sec)

mysql> explain select * from t;
+-------------------------+---------+-----------+---------------+--------------------------------+
| id                      | estRows | task      | access object | operator info                  |
+-------------------------+---------+-----------+---------------+--------------------------------+
| UnionScan_5             | 1.00    | root      |               |                                |
| └─TableReader_7         | 1.00    | root      |               | data:TableFullScan_6           |
|   └─TableFullScan_6     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-------------------------+---------+-----------+---------------+--------------------------------+
3 rows in set (0.00 sec)
```

The explain query shouldn't trigger the cache table condition, because explain doesn't mean execute the query.

```
mysql> explain update t set c = c + 1 where id > 3;
+----------------------------+---------+-----------+---------------+------------------------------------------------+
| id                         | estRows | task      | access object | operator info                                  |
+----------------------------+---------+-----------+---------------+------------------------------------------------+
| Update_5                   | N/A     | root      |               | N/A                                            |
| └─UnionScan_7              | 1.00    | root      |               | gt(test.t.id, 3)                               |
|   └─TableReader_9          | 1.00    | root      |               | data:TableRangeScan_8                          |
|     └─TableRangeScan_8     | 1.00    | cop[tikv] | table:t       | range:(3,+inf], keep order:false, stats:pseudo |
+----------------------------+---------+-----------+---------------+------------------------------------------------+
4 rows in set (0.00 sec)

mysql> explain delete from t where id > 6;
+----------------------------+---------+-----------+---------------+------------------------------------------------+
| id                         | estRows | task      | access object | operator info                                  |
+----------------------------+---------+-----------+---------------+------------------------------------------------+
| Delete_5                   | N/A     | root      |               | N/A                                            |
| └─UnionScan_7              | 1.00    | root      |               | gt(test.t.id, 6)                               |
|   └─TableReader_9          | 1.00    | root      |               | data:TableRangeScan_8                          |
|     └─TableRangeScan_8     | 1.00    | cop[tikv] | table:t       | range:(6,+inf], keep order:false, stats:pseudo |
+----------------------------+---------+-----------+---------------+------------------------------------------------+
4 rows in set (0.00 sec)
```

Insert/Delete/Update should not trigger cache table condition too.
Because they are write operation, if  `UpdateLockForRead` add the read lock, the write operation will wait for the lock to expire.

### What is changed and how it works?

- if the operation is write, or explain, do not notify the table to update the read meta lock and load cache data
- defer panic to avoid the whole TiDB process exit
- make the test more stable

Check the `UnionScan` executor in the  explain result is not a stable way to check whether the table cache is used by the query. Because the the notification is in another goroutine, when it runs is undetermined.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

Not bug fix of released feature.

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -4160,9 +4160,15 @@ func (b *PlanBuilder) buildDataSource(ctx context.Context, tn *ast.TableName, as
 			result = us
 		} else {
 			go func() {
-				err := cachedTable.UpdateLockForRead(b.ctx, txn.StartTS())
-				if err != nil {
-					log.Warn("Update Lock Info Error")
+				defer func() {
+					if r := recover(); r != nil {
```
Comment (lcwangchao) [inline planner/core/logical_plan_builder.go:4164]: some logging?

**Comment by lcwangchao** [comment]
Rest LGTM

**Comment by tiancaiamao** [comment]
Unstable test https://github.com/pingcap/tidb/issues/28206

```
[2021-11-05T01:57:54.227Z] ----------------------------------------------------------------------
[2021-11-05T01:57:54.227Z] FAIL: db_partition_test.go:2956: testIntegrationSuite5.TestDropSchemaWithPartitionTable
[2021-11-05T01:57:54.227Z] 
[2021-11-05T01:57:54.227Z] db_partition_test.go:3006:
[2021-11-05T01:57:54.227Z]     c.Assert(recordsNum, Equals, 0)
[2021-11-05T01:57:54.227Z] ... obtained int = 4
[2021-11-05T01:57:54.227Z] ... expected int = 0
[2021-11-05T01:57:54.227Z] 
```

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (tiancaiamao) [reply planner/core/logical_plan_builder.go:4164]: Here will be re-designed in the following PRs.
Whether it success of fail do not affect the other part, so the log is useless and introduce misconception for the user.

I add this recover because if no recover here, the whole TiDB exit which is bad.
The actual cause of the panic is another bug of here: https://github.com/pingcap/tidb/blob/1b5b44047c6643e428798c332583d387256ba151/table/tables/cache.go#L62

This code assume the caller of `loadDataFromOriginalTable` inside a txn, if not, `sctx.Txn(true)` panic
I'll refactor the code and fix it in the following PRs, but for now, just recover and don't make TiDB panic

@lcwangchao

**Review by lcwangchao — APPROVED** [review]

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (AilinKid) [reply planner/core/logical_plan_builder.go:4164]: upset on: @tiancaiamao L4149 shows b.ctx is already in a txn, why UpdateLockForRead is not?

**Comment by AilinKid** [comment]
> Unstable test #28206
> 
> ```
> [2021-11-05T01:57:54.227Z] ----------------------------------------------------------------------
> [2021-11-05T01:57:54.227Z] FAIL: db_partition_test.go:2956: testIntegrationSuite5.TestDropSchemaWithPartitionTable
> [2021-11-05T01:57:54.227Z] 
> [2021-11-05T01:57:54.227Z] db_partition_test.go:3006:
> [2021-11-05T01:57:54.227Z]     c.Assert(recordsNum, Equals, 0)
> [2021-11-05T01:57:54.227Z] ... obtained int = 4
> [2021-11-05T01:57:54.227Z] ... expected int = 0
> [2021-11-05T01:57:54.227Z] 
> ```

your mention is in the wrong PR

**Comment by tiancaiamao** [comment]
> > Unstable test #28206
> > ```
> > [2021-11-05T01:57:54.227Z] ----------------------------------------------------------------------
> > [2021-11-05T01:57:54.227Z] FAIL: db_partition_test.go:2956: testIntegrationSuite5.TestDropSchemaWithPartitionTable
> > [2021-11-05T01:57:54.227Z] 
> > [2021-11-05T01:57:54.227Z] db_partition_test.go:3006:
> > [2021-11-05T01:57:54.227Z]     c.Assert(recordsNum, Equals, 0)
> > [2021-11-05T01:57:54.227Z] ... obtained int = 4
> > [2021-11-05T01:57:54.227Z] ... expected int = 0
> > [2021-11-05T01:57:54.227Z] 
> > ```
> 
> your mention is in the wrong PR

Nope, I mean check_dev_2 is unstable and cause this PR fail, so I re-run it.  @AilinKid 
And the failed case is already tracked in issue #28206... I fix that issue now that I come across it.

**Comment by tiancaiamao** [comment]
This PR fix a unstable case and the panic looks like that:

image

@AilinKid

**Comment by unconsolable** [comment]
close #29528

**Comment by unconsolable** [comment]
Please add close issue https://github.com/pingcap/tidb/issues/29528, thanks.

**Review by tangenta — APPROVED** [review]
