### PR TITLE
ddl: fix create list partition bug and add more test

### LINKED ISSUE #21397: create list partition with wrong value should return error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (a varchar(2)) partition by list columns (a) (partition p0 values in ('abc'));
```

### 2. What did you expect to see? (Required)

```sql
(1654, 'Partition column values of incorrect type')
```

### 3. What did you see instead (Required)

```sql
> create table t (a varchar(2)) partition by list columns (a) (partition p0 values in ('abc'));
Query OK, 0 rows affected
Time: 0.068s
```

### 4. What is your TiDB version? (Required)

```sql
> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1678-g59b8e7597                    |
| Edition: Community                                                |
| Git Commit Hash: 59b8e7597b5f88b5eafa07340ecd2a70e939be5e         |
| Git Branch: master                                                |
| UTC Build Time: 2020-11-30 13:28:57                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #21399: create list partition return wrong error message
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (id float) partition by list columns (id) (partition p0 values in (1));
```

### 2. What did you expect to see? (Required)

```sql
(1659, "Field 'id' is of a not allowed type for this type of partitioning")
```

### 3. What did you see instead (Required)

```sql
(1654, 'Partition column values of incorrect type')

```

### 4. What is your TiDB version? (Required)

```sql
> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1679-g8e8e54833                    |
| Edition: Community                                                |
| Git Commit Hash: 8e8e548337b29676b4a92eedbf5a2661f9499590         |
| Git Branch: fix-metric-json                                       |
| UTC Build Time: 2020-11-30 13:43:17                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

close #21397
close #21399
### Related changes

- N/A

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- N/A

### CODE REVIEW

File: ddl/partition.go [hunk 1]
```diff
@@ -334,9 +335,11 @@ func buildTablePartitionInfo(ctx sessionctx.Context, s *ast.PartitionOptions, tb
 		for _, cn := range s.ColumnNames {
 			pi.Columns = append(pi.Columns, cn.Name)
 		}
+		if err := checkColumnsPartitionType(tbInfo); err != nil {
```
Comment (xiongjiwei) [inline ddl/partition.go:338]: if we `checkColumnsPartitionType` here, we can remove the same check in function `checkPartitionByRange` and `checkPartitionByList`

**Comment by crazycs520** [comment]
@xiongjiwei @tiancaiamao @wjhuang2016 PTAL

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -5171,6 +5154,12 @@ func checkColumnsTypeAndValuesMatch(ctx sessionctx.Context, meta *model.TableInf
 	// partition p0 values less than (expr)
 	// check the type of cols[i] and expr is consistent.
 	colNames := meta.Partition.Columns
+	originalValue := ctx.GetSessionVars().StmtCtx.InInsertStmt
+	defer func() {
+		ctx.GetSessionVars().StmtCtx.InInsertStmt = originalValue
+	}()
+	// See ShouldClipToZero function, set InInsertStmt flag to true to detect overflow.
+	ctx.GetSessionVars().StmtCtx.InInsertStmt = true
```
Comment (wjhuang2016) [inline ddl/ddl_api.go:5162]: I think it's better to modify ShouldClipToZero(). Use TruncateAsWarning to decide it.

File: ddl/partition.go (hunk 1 above)
Comment (crazycs520) [reply ddl/partition.go:338]: great, done.

File: ddl/ddl_api.go (hunk 2 above)
Comment (crazycs520) [reply ddl/ddl_api.go]: Great, catch, done.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by crazycs520** [comment]
@wjhuang2016 @xiongjiwei PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

File: executor/executor.go [hunk 3]
```diff
@@ -1640,7 +1640,10 @@ func ResetContextOfStmt(ctx sessionctx.Context, s ast.StmtNode) (err error) {
 		sc.AllowInvalidDate = vars.SQLMode.HasAllowInvalidDatesMode()
 		sc.IgnoreZeroInDate = !vars.SQLMode.HasNoZeroInDateMode() || !vars.SQLMode.HasNoZeroDateMode() || !vars.StrictSQLMode || stmt.IgnoreErr || sc.AllowInvalidDate
 		sc.Priority = stmt.Priority
-	case *ast.CreateTableStmt, *ast.AlterTableStmt:
+	case *ast.CreateTableStmt:
+		// Make sure the sql_mode is strict when checking column default value.
+		sc.InCreateTableStmt = true
+	case *ast.AlterTableStmt:
```
Comment (xiongjiwei) [inline executor/executor.go:1646]: `alter table ... add partition` will also call `checkColumnsTypeAndValuesMatch`. should we consider that?

File: ddl/ddl_api.go [hunk 4]
```diff
@@ -5227,6 +5210,10 @@ func checkColumnsTypeAndValuesMatch(ctx sessionctx.Context, meta *model.TableInf
 				return ErrWrongTypeColumnValue.GenWithStackByArgs()
 			}
 		}
+		_, err = val.ConvertTo(ctx.GetSessionVars().StmtCtx, &colInfo.FieldType)
```
Comment (xiongjiwei) [inline ddl/ddl_api.go:5213]: seems `L5188` to `L5190` can be removed

File: executor/executor.go (hunk 3 above)
Comment (crazycs520) [reply executor/executor.go:1646]: Great catch, let me see see.

File: ddl/ddl_api.go (hunk 4 above)
Comment (crazycs520) [reply ddl/ddl_api.go]: great catch, done.

**Comment by crazycs520** [comment]
@xiongjiwei PTAL

**Comment by xiongjiwei** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
