### PR TITLE
table: fix zero date in different sqlmode

### LINKED ISSUE #19892: different behaviour of NO_ZERO_DATE with mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

The [`NO_ZERO_DATE`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date) define as below:

> The NO_ZERO_DATE mode affects whether the server permits '0000-00-00' as a valid date. Its effect also depends on whether strict SQL mode is enabled.
> If this mode is not enabled, '0000-00-00' is permitted and inserts produce no warning.
>
>If this mode is enabled, '0000-00-00' is permitted and inserts produce a warning.
>
> If this mode and strict mode are enabled, '0000-00-00' is not permitted and inserts produce an error, unless IGNORE is given as well. For INSERT IGNORE and UPDATE IGNORE, '0000-00-00' is permitted and inserts produce a warning.

BUT, in TiDB's implemention, the SQL mode doesn't work.

### 1. Minimal reproduce step (Required)

```sql
create table dd(i datetime)
insert into dd('0000-00-00')
```

### 2. What did you expect to see? (Required)

in MySQL 8.0

```sql
mysql admin@127.0.0.1:app> create table dd(i datetime);
Query OK, 0 rows affected
Time: 0.114s

-- sql_mode to none
mysql admin@127.0.0.1:app> show variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+
1 row in set
Time: 0.031s
mysql admin@127.0.0.1:app> show global variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+

mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s


-- set to NO_ZERO_DATE
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE';
Query OK, 0 rows affected
Time: 0.002s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.008s
mysql admin@127.0.0.1:app> show warnings;
+---------+------+--------------------------------------------+
| Level   | Code | Message                                    |
+---------+------+--------------------------------------------+
| Warning | 1264 | Out of range value for column 'i' at row 1 |
+---------+------+--------------------------------------------+
1 row in set
Time: 0.041s

-- set to NO_ZERO_DATE,STRICT_TRANS_TABLES
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE,STRICT_TRANS_TABLES';
Query OK, 0 rows affected
Time: 0.003s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
(1292, "Incorrect datetime value: '0000-00-00' for column 'i' at row 1")
mysql admin@127.0.0.1:app> show warnings;
+-------+------+----------------------------------------------------------------+
| Level | Code | Message                                                        |
+-------+------+----------------------------------------------------------------+
| Error | 1292 | Incorrect datetime value: '0000-00-00' for column 'i' at row 1 |
+-------+------+----------------------------------------------------------------+
```

### 3. What did you see instead (Required)

```sql
mysql admin@127.0.0.1:app> create table dd(i datetime);
Query OK, 0 rows affected
Time: 0.114s

-- sql_mode to none
mysql admin@127.0.0.1:app> show variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+
1 row in set
Time: 0.031s
mysql admin@127.0.0.1:app> show global variables like 'sql_mode';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_mode      |       |
+---------------+-------+

mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s

-- set to NO_ZERO_DATE
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE';
Query OK, 1 rows affected
Time: 0.002s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s

-- set to NO_ZERO_DATE,STRICT_TRANS_TABLES
mysql admin@127.0.0.1:app> set sql_mode='NO_ZERO_DATE,STRICT_TRANS_TABLES';
Query OK, 0 rows affected
Time: 0.003s
mysql admin@127.0.0.1:app> insert into dd values ('0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql admin@127.0.0.1:app> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
0 rows in set
Time: 0.021s
```

### 4. What is your TiDB version? (Required)

```sql
mysql root@127.0.0.1:(none)> select tidb_version() \G;
***************************[ 1. row ]***************************
tidb_version() | Release Version: v4.0.0-beta.2-1165-g726341146-dirty
Edition: Community
Git Commit Hash: 726341146b99485335a195b16a803b95e4875228
Git Branch: master
UTC Build Time: 2020-09-08 01:55:13
GoVersion: go1.14.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

1 row in set
Time: 0.009s
```

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve?

Issue Number: close #19892, #19634

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

- The same behavior of `NO_ZERO_DATE` and `NO_ZERO_IN_DATE` to MySQL's in INSERT/UPDATE statement

### CODE REVIEW

**Comment by 9547** [comment]
@qw4990 PTAL, and curious, why this test case failed, seems not related to my pr? If I've missed something, please let me know.

```bash
[2020-09-24T17:15:23.120Z] PASS: session_test.go:1573: testSessionSuite3.TestISColumns	0.005s

[2020-09-24T17:15:23.376Z] panic: runtime error: invalid memory address or nil pointer dereference

[2020-09-24T17:15:23.376Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2acfdf2]

[2020-09-24T17:15:23.376Z] 

[2020-09-24T17:15:23.376Z] goroutine 5416 [running]:

[2020-09-24T17:15:23.376Z] github.com/pingcap/tidb/util/execdetails.(*BasicRuntimeStats).GetTime(...)

[2020-09-24T17:15:23.376Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:555

[2020-09-24T17:15:23.376Z] github.com/pingcap/tidb/executor.(*insertRuntimeStat).String(0xc01085d500, 0x3acaa40, 0xc0107b9920)

[2020-09-24T17:15:23.376Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/insert_common.go:1072 +0x1d2

[2020-09-24T17:15:23.376Z] github.com/pingcap/tidb/util/execdetails.(*RootRuntimeStats).String(0xc00f769920, 0x1, 0xc00f769920)

[2020-09-24T17:15:23.376Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:530 +0x235

[2020-09-24T17:15:23.376Z] github.com/pingcap/tidb/planner/core.getRuntimeInfo(0x3b0f9e0, 0xc00ebc8780, 0x3af92a0, 0xc01066a180, 0xc010861260, 0xc010861230, 0x203004, 0x203004, 0x203004, 0xc010861170, ...)

[2020-09-24T17:15:23.376Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/common_plans.go:1069 +0x38b

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/planner/core.(*planEncoder).encodePlan(0xc00e2bcde0, 0x3af92a0, 0xc01066a180, 0x1, 0x0)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:64 +0xaa

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/planner/core.(*planEncoder).encodePlanTree(0xc00e2bcde0, 0x3af92a0, 0xc01066a180, 0x0, 0x2)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:58 +0x84

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/planner/core.EncodePlan(0x3af92a0, 0xc01066a180, 0x0, 0x0)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/encode.go:52 +0x123

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/executor.getPlanTree(0x3af92a0, 0xc01066a180, 0x3af92a0, 0xc01066a180)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:955 +0x87

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/executor.(*ExecStmt).LogSlowQuery(0xc00f589c30, 0x5d3047314c8000b, 0x3ac0000)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:899 +0x456

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt(0xc00f589c30, 0x5d3047314c8000b, 0xc00ebc0000)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:810 +0xeb

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/session.runStmt(0x3ac7f00, 0xc000062070, 0xc00ebc8780, 0x3ae6680, 0xc00f589c30, 0x0, 0x0, 0x3a6c260, 0xc01085d420)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1235 +0x446

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc00ebc8780, 0x3ac7f00, 0xc000062070, 0x3ad1000, 0xc00f599a00, 0x0, 0x0, 0x0, 0x0)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1171 +0x7b9

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/util/testkit.(*TestKit).Exec(0xc00f94bf88, 0x357dfcb, 0x24, 0x0, 0x0, 0x0, 0xc00f74e758, 0x12523b2, 0xc00e1df5d0, 0xc00f74e780)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x215

[2020-09-24T17:15:23.377Z] github.com/pingcap/tidb/session_test.(*testSessionSuite2).TestErrorRollback.func1(0xc00f6e94c0, 0xc00eb9cff0, 0xc0007fea80, 0x14)

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session_test.go:300 +0x180

[2020-09-24T17:15:23.377Z] created by github.com/pingcap/tidb/session_test.(*testSessionSuite2).TestErrorRollback

[2020-09-24T17:15:23.377Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session_test.go:295 +0x1d9

[2020-09-24T17:15:23.377Z] exit status 2

[2020-09-24T17:15:23.377Z] FAIL	github.com/pingcap/tidb/session	4.716s
```

File: expression/integration_test.go [hunk 1]
```diff
@@ -7378,3 +7378,109 @@ func (s *testIntegrationSuite) TestIssue11645(c *C) {
...
+		{
+			tk.MustExec("TRUNCATE TABLE dd")
+			tk.MustExec("INSERT INTO dd(b) values('0000-00-00')")
+			tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect datetime value: '0000-00-00 00:00:00'"))
+			tk.MustQuery("SELECT b FROM dd").Check(testkit.Rows("0000-00-00 00:00:00"))
+
+			tk.MustExec("TRUNCATE TABLE dd")
+			tk.MustExec("INSERT INTO dd(a) values('2000-10-01')")
+			tk.MustExec("UPDATE dd SET a = '0000-00-00'")
+			// tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect date value: '0000-00-00'"))
```
Comment (rebelice) [inline expression/integration_test.go:7414]: Could you tell me why comment it here？

File: table/column.go [hunk 2]
```diff
@@ -191,6 +191,35 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
...
+				zeroV, zeroT = types.ZeroDatetime, types.DateTimeStr
+			}
+
+			// FIXME: as in MySQL 8.0's implement, warning message is `types.ErrWarnDataOutOfRange`,
+			// but this error message need a `rowIdx` argument, in this context, the `rowIdx` is missing.
+			// And refactor this function seems too complicated, so we set the warning message the same to error's.
+			sc.AppendWarning(types.ErrWrongValue.GenWithStackByArgs(zeroT, tm.String()))
+			return types.NewDatum(zeroV), nil
+		}
+		return casted, nil
```
Comment (rebelice) [inline table/column.go:220]: Can we return here? It seems to skip charset check.

File: expression/integration_test.go (hunk 1 above)
Comment (9547) [reply expression/integration_test.go:7414]: Seems there was two identical warning messages , but I have no idea why that happened

File: table/column.go (hunk 2 above)
Comment (9547) [reply table/column.go:220]: Good idea, the date string  should also be checked the charset

File: expression/integration_test.go (hunk 1 above)
Comment (lance6716) [reply expression/integration_test.go:7528]: maybe it's to check insert and update both generating a warning

**Review by lance6716 — COMMENTED** [review]
good work

File: expression/integration_test.go (hunk 1 above)
Comment (9547) [reply expression/integration_test.go:7528]: But the insert stmt is valid, no warnings should generated

Comment (lance6716) [reply expression/integration_test.go:7528]: > But the insert stmt is valid, no warnings should generated

i mean line 7521

Comment (lance6716) [reply expression/integration_test.go:7528]: line 7521

Comment (lance6716) [reply expression/integration_test.go:7528]: i mean line 7521 and 7527 should both be checked

Comment (9547) [reply expression/integration_test.go:7528]: thanks for the advice, and is there any way to clear warnings before an stmt executing.

Comment (9547) [reply expression/integration_test.go:7528]: Seems the warning messages are automatically deleted after a valid STMT executed, IMO, line 7521's warning will not affect this line.

Comment (lance6716) [reply expression/integration_test.go:7528]: seems our communication is misleading 🤣 i mean this line shouldn't be commented as it could check above update generated a warning. and maybe you say that it generated two identical warnings? that's an unexpected behaviour, maybe some bug in code

Comment (9547) [reply expression/integration_test.go:7528]: :joy: sorry for the misunderstanding. In my local tests, the warning count maybe 1 or 2. currently, rebase from the master branch and remove the comment, the local test seems passed.  Push it up to see the CI passed or not.

Comment (9547) [reply expression/integration_test.go:7528]: It's passed 🎉

**Comment by lance6716** [comment]
PTAL @rebelice @lzmhhh123

File: table/column.go [hunk 3]
```diff
@@ -191,6 +191,34 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
 		truncateTrailingSpaces(&casted)
 	}
 
+	if (sc.InInsertStmt || sc.InUpdateStmt) && !casted.IsNull() && (col.Tp == mysql.TypeDate || col.Tp == mysql.TypeDatetime) {
```
Comment (rebelice) [inline table/column.go:194]: I think we should also consider `mysql.TypeTimestamp`.

File: table/column.go [hunk 4]
```diff
@@ -191,6 +191,34 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
...
+		mode := ctx.GetSessionVars().SQLMode
+		ignoreErr := sc.DupKeyAsWarning
+
+		if (mode.HasNoZeroDateMode() && tm.IsZero()) ||
+			(mode.HasNoZeroInDateMode() && tm.Year() > 0 && (tm.Month() == 0 || tm.Day() == 0)) {
+			if mode.HasStrictMode() && !ignoreErr {
+				return casted, types.ErrWrongValue.GenWithStackByArgs(types.DateTimeStr, tm.String())
+			}
+			var (
+				zeroV interface{}
```
Comment (rebelice) [inline table/column.go:205]: Could you please use `types.Time` instead of `interface{}`?

File: expression/integration_test.go [hunk 5]
```diff
@@ -7492,3 +7492,108 @@ func (s *testIntegrationSuite) TestIssue20180(c *C) {
...
+			tk.MustExec("INSERT IGNORE INTO dd(b) VALUES ('0000-00-00')")
+			tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect datetime value: '0000-00-00 00:00:00'"))
+			tk.MustQuery("SELECT b FROM dd").Check(testkit.Rows("0000-00-00 00:00:00"))
+
+			tk.MustExec("TRUNCATE TABLE dd")
+			tk.MustExec("INSERT INTO dd(b) values('2000-10-01')")
+			tk.MustGetErrMsg("UPDATE dd SET b = '0000-00-00'", "[types:1292]Incorrect datetime value: '0000-00-00 00:00:00'")
+			tk.MustExec("UPDATE IGNORE dd SET b = '0000-00-00'")
+			// FIXME: has two warning rows
+			// tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect datetime value: '0000-00-00 00:00:00'"))
```
Comment (rebelice) [inline expression/integration_test.go:7545]: The reason for the two warnings is that the executor calls `CastValue` twice during the `Update`. But this has nothing to do with your modification. You can use `tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect datetime value: '0000-00-00 00:00:00'", "Warning 1292 Incorrect datetime value: '0000-00-00 00:00:00'"))` here to indicate that there is indeed Two lines of errors, then create a new issue with two lines of errors.

File: table/column.go (hunk 3 above)
Comment (9547) [reply table/column.go]: Thanks, added.

File: table/column.go (hunk 4 above)
Comment (9547) [reply table/column.go]: +1

File: expression/integration_test.go (hunk 5 above)
Comment (9547) [reply expression/integration_test.go]: > The reason for the two warnings is that the executor calls CastValue twice during the Update

Thanks for your advice. In `UPDATE` execute, it does exist twice. 

eg: the exec trace of `UPDATE dd SET b = '0000-00-00'` as below:

1: cast from `types.KindString` to `mysql.TypeDatetime`;
2. cast from `types.KindMysqlTime` to `mysql.TypeDatetime`;

```bash
# the first CastValue
# cast from `types.KindString` to `mysql.TypeDatetime`

 0  0x0000000001ff4afb in github.com/pingcap/tidb/table.CastValue
    at ./table/column.go:168
 1  0x0000000002aaba49 in github.com/pingcap/tidb/executor.(*UpdateExec).fastComposeNewRow
    at ./executor/update.go:232
 2  0x0000000002acf1c6 in github.com/pingcap/tidb/executor.(*UpdateExec).fastComposeNewRow-fm
    at ./executor/update.go:215
 3  0x0000000002aaab6a in github.com/pingcap/tidb/executor.(*UpdateExec).updateRows
    at ./executor/update.go:185
 4  0x0000000002aaa74c in github.com/pingcap/tidb/executor.(*UpdateExec).Next
    at ./executor/update.go:134
    ......

# the second CastValue
# cast from `types.KindMysqlTime` to `mysql.TypeDatetime`;

(dlv) bt
 0  0x0000000001ff4afb in github.com/pingcap/tidb/table.CastValue
    at ./table/column.go:168
 1  0x0000000002ab0243 in github.com/pingcap/tidb/executor.updateRecord
    at ./executor/write.go:77
 2  0x0000000002aaa30a in github.com/pingcap/tidb/executor.(*UpdateExec).exec
    at ./executor/update.go:104
 3  0x0000000002aaac51 in github.com/pingcap/tidb/executor.(*UpdateExec).updateRows
    at ./executor/update.go:189
 4  0x0000000002aaa74c in github.com/pingcap/tidb/executor.(*UpdateExec).Next
    at ./executor/update.go:134

 5  0x00000000029c3039 in github.com/pingcap/tidb/executor.Next
    at ./executor/executor.go:268
```

IMO, we can ignore the warning message in the second cast operation.

**Comment by 9547** [comment]
@rebelice Sorry for the late reply, please have a look again

**Review by rebelice — COMMENTED** [review]
LGTM

**Comment by lzmhhh123** [comment]
@ichn-hu Please help to review this PR.

File: table/column.go [hunk 6]
```diff
@@ -177,10 +177,46 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
...
+			case mysql.TypeDate:
+				zeroV, zeroT = types.ZeroDate, types.DateStr
+			case mysql.TypeDatetime:
+				zeroV, zeroT = types.ZeroDatetime, types.DateTimeStr
+			case mysql.TypeTimestamp:
+				zeroV, zeroT = types.ZeroTimestamp, types.TimestampStr
+			}
+
+			innerErr := types.ErrWrongValue.GenWithStackByArgs(zeroT, val.GetString())
+			ignoreErr := sc.DupKeyAsWarning
```
Comment (ichn-hu) [inline table/column.go:205]: Why use DupKeyAsWarning for ignore error? I think here it is not about dup key, but zero date?

**Review by ichn-hu — COMMENTED** [review]
Rest LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ichn-hu — DISMISSED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by 9547** [comment]
> /merge

Please merge again

File: table/column.go (hunk 6 above)
Comment (9547) [reply table/column.go:205]: Because the value of `sc.DupKeyAsWarning` is the original value of ignoreError: https://github.com/pingcap/tidb/blob/43a5bb47977fc7952a8aaedffe0154e6918bf4ad/executor/executor.go#L1601-L1615

**Comment by lzmhhh123** [comment]
@9547 could you figure out why this test failed?

```
[2020-11-19T03:35:39.398Z] [2020/11/19 11:35:34.224 +08:00] [ERROR] [misc.go:168] ["syntax error"] [error="line 1 column 21 near \"\"users\"  WHERE (name = ?) ORDER BY \"users\".\"id\" ASC LIMIT 1\" "]
```

**Comment by nullnotnil** [comment]
@9547 @lzmhhh123 I can take a look at this tomorrow. I think the common-test has some dependencies on invalid dates.

**Comment by 9547** [comment]
> @9547 @lzmhhh123 I can take a look at this tomorrow. I think the common-test has some dependencies on invalid dates.

Seems is a test case from https://github.com/pingcap/tidb-test, which is a privacy project, could you please help me check if there is a problem with the test code over there. Also curious about the panic and FAIL testcase:

```bash
[2020-11-19T03:35:39.398Z] panic: runtime error: index out of range [0] with length 0 [recovered]

[2020-11-19T03:35:39.398Z] 	panic: runtime error: index out of range [0] with length 0

[2020-11-19T03:35:39.398Z] 

[2020-11-19T03:35:39.398Z] goroutine 271 [running]:

[2020-11-19T03:35:39.398Z] testing.tRunner.func1(0xc0005f7500)

[2020-11-19T03:35:39.398Z] 	/usr/local/go/src/testing/testing.go:874 +0x3a3

[2020-11-19T03:35:39.398Z] panic(0xa505a0, 0xc000458280)

[2020-11-19T03:35:39.398Z] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2

[2020-11-19T03:35:39.398Z] github.com/pingcap/tidb-test/gorm_test/gorm_test.TestOrderAndPluck(0xc0005f7500)

[2020-11-19T03:35:39.398Z] 	/home/jenkins/agent/workspace/tidb_ghpr_common_test/go/src/github.com/pingcap/tidb-test/gorm_test/gorm/query_test.go:265 +0xdbb

[2020-11-19T03:35:39.398Z] testing.tRunner(0xc0005f7500, 0xab47f8)

[2020-11-19T03:35:39.398Z] 	/usr/local/go/src/testing/testing.go:909 +0xc9

[2020-11-19T03:35:39.398Z] created by testing.(*T).Run

[2020-11-19T03:35:39.398Z] 	/usr/local/go/src/testing/testing.go:960 +0x350

[2020-11-19T03:35:39.398Z] exit status 2

[2020-11-19T03:35:39.398Z] FAIL	github.com/pingcap/tidb-test/gorm_test/gorm	2.185s
```

**Comment by nullnotnil** [comment]
The reason for the breakage is that the gorm v1 test converts a `nil` value to the MySQL zero date (`0000-00-00`) and inserts full rows as sql. i.e.:

```
        user1 := User{Name: "OrderPluckUser1", Age: 1}
        user2 := User{Name: "OrderPluckUser2", Age: 10}
        user3 := User{Name: "OrderPluckUser3", Age: 20}
        DB.Save(&user1).Save(&user2).Save(&user3)
``

The `DB.Save` fails because the following SQL is produced:

```
INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`,`created_at`,`updated_at`,`billing_address_id`,`shipping_address_id`,`latitude`,`company_id`,`role`,`password_hash`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) [arguments: (1, 0, OrderPluckUser1, 0000-00-00, 2020-11-19 20:30:18.98764, 2020-11-19 20:30:18.98764, NULL, 0, 0, 0, , NULL)];
```

This has been reported as https://github.com/go-sql-driver/mysql/pull/346 ; so it is not a problem specific to this PR or TiDB.

I thought about setting a default `birthday`, which would get around this specific issue. But then there is the problem where there is another zero date on a table which uses this to signify a `deleted_at` date:

```
INSERT INTO `addresses` (`address1`,`address2`,`post`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?) [arguments: (Billing Address pluck_user3, , , 2020-11-19 20:30:17.882469, 2020-11-19 20:30:17.882469, 0000-00-00)];
```

It is not logical to set the `deleted_at` date to a default value, so my current plan is to disable the zero_date SQL mode in the gorm test.

**Comment by nullnotnil** [comment]
@9547 I found a bug in the implementation. It looks like `NO_ZERO_DATE` can not be turned off correctly. Here is a testcase:
```sql
DROP TABLE IF EXISTS users;
CREATE TABLE `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `age` bigint(20) DEFAULT NULL,
  `user_num` bigint(20) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `birthday` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `billing_address_id` bigint(20) DEFAULT NULL,
  `shipping_address_id` bigint(20) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `company_id` bigint(20) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `password_hash` varbinary(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

SET sql_mode=DEFAULT;
SHOW VARIABLES like 'sql_mode';
INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
SET sql_mode=REPLACE(@@sql_mode,'NO_ZERO_DATE', '');
SHOW VARIABLES like 'sql_mode';
INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
```

The output from MySQL 8.0.22:
```sql
mysql [localhost:8022] {msandbox} (test) > DROP TABLE IF EXISTS users;
Query OK, 0 rows affected (0.00 sec)

mysql [localhost:8022] {msandbox} (test) > CREATE TABLE `users` (
    ->   `id` bigint(20) NOT NULL AUTO_INCREMENT,
    ->   `age` bigint(20) DEFAULT NULL,
    ->   `user_num` bigint(20) DEFAULT NULL,
    ->   `name` varchar(255) DEFAULT NULL,
    ->   `birthday` timestamp NULL DEFAULT NULL,
    ->   `created_at` timestamp NULL DEFAULT NULL,
    ->   `updated_at` timestamp NULL DEFAULT NULL,
    ->   `billing_address_id` bigint(20) DEFAULT NULL,
    ->   `shipping_address_id` bigint(20) DEFAULT NULL,
    ->   `latitude` double DEFAULT NULL,
    ->   `company_id` bigint(20) DEFAULT NULL,
    ->   `role` varchar(255) DEFAULT NULL,
    ->   `password_hash` varbinary(255) DEFAULT NULL,
    ->   PRIMARY KEY (`id`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
Query OK, 0 rows affected, 6 warnings (0.01 sec)

mysql [localhost:8022] {msandbox} (test) > 
mysql [localhost:8022] {msandbox} (test) > SET sql_mode=DEFAULT;
Query OK, 0 rows affected (0.00 sec)

mysql [localhost:8022] {msandbox} (test) > SHOW VARIABLES like 'sql_mode';
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql [localhost:8022] {msandbox} (test) > INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
ERROR 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'birthday' at row 1
mysql [localhost:8022] {msandbox} (test) > SET sql_mode=REPLACE(@@sql_mode,'NO_ZERO_DATE', '');
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql [localhost:8022] {msandbox} (test) > SHOW VARIABLES like 'sql_mode';
+---------------+----------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                    |
+---------------+----------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------+----------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql [localhost:8022] {msandbox} (test) > INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
Query OK, 1 row affected (0.00 sec)
```

The output from TiDB (this branch):
```sql
mysql> DROP TABLE IF EXISTS users;
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE TABLE `users` (
    ->   `id` bigint(20) NOT NULL AUTO_INCREMENT,
    ->   `age` bigint(20) DEFAULT NULL,
    ->   `user_num` bigint(20) DEFAULT NULL,
    ->   `name` varchar(255) DEFAULT NULL,
    ->   `birthday` timestamp NULL DEFAULT NULL,
    ->   `created_at` timestamp NULL DEFAULT NULL,
    ->   `updated_at` timestamp NULL DEFAULT NULL,
    ->   `billing_address_id` bigint(20) DEFAULT NULL,
    ->   `shipping_address_id` bigint(20) DEFAULT NULL,
    ->   `latitude` double DEFAULT NULL,
    ->   `company_id` bigint(20) DEFAULT NULL,
    ->   `role` varchar(255) DEFAULT NULL,
    ->   `password_hash` varbinary(255) DEFAULT NULL,
    ->   PRIMARY KEY (`id`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> SET sql_mode=DEFAULT;
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES like 'sql_mode';
+---------------+--------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                        |
+---------------+--------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+--------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
ERROR 1292 (22007): Incorrect timestamp value: '0000-00-00' for column 'birthday' at row 1
mysql> SET sql_mode=REPLACE(@@sql_mode,'NO_ZERO_DATE', '');
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES like 'sql_mode';
+---------------+--------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                        |
+---------------+--------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+--------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
ERROR 1292 (22007): Incorrect timestamp value: '0000-00-00' for column 'birthday' at row 1
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1602-g5646bc763
Edition: Community
Git Commit Hash: 5646bc76340015780f94cd725db5f330f85ad922
Git Branch: fix/no-zero-date-sqlmode
UTC Build Time: 2020-11-19 20:24:50
GoVersion: go1.13.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

```

**Comment by 9547** [comment]
@nullnotnil Thanks for your help, seems the default sql_mode is different in TiDB ad MySQL:

**MySQL**

It has `NO_ZERO_IN_DATE,NO_ZERO_DATE` in default:

```sql
mysql [localhost:8022] {msandbox} (test) > SET sql_mode=DEFAULT;
Query OK, 0 rows affected (0.00 sec)

mysql [localhost:8022] {msandbox} (test) > SHOW VARIABLES like 'sql_mode';
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

**TiDB**

It doesn't has `NO_ZERO_IN_DATE,NO_ZERO_DATE` in default:

```sql
mysql> SET sql_mode=DEFAULT;
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES like 'sql_mode';
+---------------+--------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                        |
+---------------+--------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+--------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by 9547** [comment]
@nullnotnil Just curious about the default sql_mode of your tidb missing `NO_ZERO_IN_DATE,NO_ZERO_DATE`, the definition of `DEFAULT` is the same as MySQL, https://github.com/pingcap/parser/blob/9d7d64259a5c5a461f423bb8aed982c0a6ca2a68/mysql/const.go#L493

```go
// DefaultSQLMode for GLOBAL_VARIABLES
const DefaultSQLMode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

And in my local dev, it's ok:

```sql
mysql root@127.0.0.1:(none)> show variables like 'sql_mode';
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                     |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+

1 row in set
Time: 0.065s
mysql root@127.0.0.1:(none)> set sql_mode=DEFAULT;
Query OK, 0 rows affected
Time: 0.002s
mysql root@127.0.0.1:(none)> show variables like 'sql_mode';
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                     |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+

1 row in set
Time: 0.010s
mysql root@127.0.0.1:(none)>
mysql root@127.0.0.1:(none)> select tidb_version() \G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v4.0.0-beta.2-1596-g43a5bb479
Edition: Community
Git Commit Hash: 43a5bb47977fc7952a8aaedffe0154e6918bf4ad
Git Branch: fix/no-zero-date-sqlmode
UTC Build Time: 2020-11-19 22:29:54
GoVersion: go1.15.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

Please let me know if I'm missing anything.

**Comment by nullnotnil** [comment]
@9547 it looks like there might be a different bug where setting `DEFAULT` is setting it to the `GLOBAL` value incorrectly (which I've changed). I'll have to take a look at it. Here is a simpler test to avoid that, which can still reproduce the issue:

```sql
DROP TABLE IF EXISTS users;
CREATE TABLE `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `age` bigint(20) DEFAULT NULL,
  `user_num` bigint(20) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `birthday` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `billing_address_id` bigint(20) DEFAULT NULL,
  `shipping_address_id` bigint(20) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `company_id` bigint(20) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `password_hash` varbinary(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

SET sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";
SHOW VARIABLES like 'sql_mode';
INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
SET sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";
SHOW VARIABLES like 'sql_mode';
INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');

..

mysql> SET sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES like 'sql_mode';
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                     |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.02 sec)

mysql> INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
ERROR 1292 (22007): Incorrect timestamp value: '0000-00-00' for column 'birthday' at row 1
mysql> SET sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES like 'sql_mode';
+---------------+------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                        |
+---------------+------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
ERROR 1292 (22007): Incorrect timestamp value: '0000-00-00' for column 'birthday' at row 1
```

**Comment by 9547** [comment]
@nullnotnil Thanks for the reproduce testcase, I've known what the problem it is, it's casued by `STRICT_TRANS_TABLES` sql_mode, And will be fixed later today.

**Comment by nullnotnil** [comment]
@9547 it looks there is a test failure:
```
[2020-11-20T00:06:10.822Z] 

[2020-11-20T00:06:10.822Z] ----------------------------------------------------------------------

[2020-11-20T00:06:10.822Z] FAIL: integration_test.go:7732: testIntegrationSuite.TestIssue19892

[2020-11-20T00:06:10.822Z] 

[2020-11-20T00:06:10.822Z] integration_test.go:7755:

[2020-11-20T00:06:10.822Z]     tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect timestamp value: '0000-00-00 20:00:00'"))

[2020-11-20T00:06:10.822Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:63:

[2020-11-20T00:06:10.822Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)

[2020-11-20T00:06:10.822Z] ... obtained string = ""

[2020-11-20T00:06:10.822Z] ... expected string = "[Warning 1292 Incorrect timestamp value: '0000-00-00 20:00:00']\n"

[2020-11-20T00:06:10.822Z] ... sql:SHOW WARNINGS, args:[]

[2020-11-20T00:06:10.822Z] 

[2020-11-20T00:06:10.822Z] 

[2020-11-20T00:06:10.822Z] ----------------------------------------------------------------------
```

I think I've fixed the issue in the `tidb-test` suite. You can test it with the command `/run-all-tests tidb-test=pr/1109`.

File: expression/integration_test.go [hunk 7]
```diff
@@ -7728,3 +7728,209 @@ func (s *testIntegrationSerialSuite) TestIssue20608(c *C) {
...
+		{
+			tk.MustExec("TRUNCATE TABLE dd")
+			tk.MustGetErrMsg("INSERT INTO dd(c) VALUES ('0000-00-00 20:00:00')", "[table:1292]Incorrect timestamp value: '0000-00-00 20:00:00' for column 'c' at row 1")
+			tk.MustExec("INSERT IGNORE INTO dd(c) VALUES ('0000-00-00 20:00:00')")
+			tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect timestamp value: '0000-00-00 20:00:00'"))
+			tk.MustQuery("SELECT c FROM dd").Check(testkit.Rows("0000-00-00 00:00:00"))
+
+			tk.MustExec("TRUNCATE TABLE dd")
+			tk.MustExec("INSERT INTO dd(b) values('2000-10-01')")
+			tk.MustGetErrMsg("UPDATE dd SET b = '0000-00-00'", "[types:1292]Incorrect datetime value: '0000-00-00'")
```
Comment (blacktear23) [inline expression/integration_test.go:7795]: The error message should like: [types:1292]Incorrect date value: '0000-00-00' for column 'b' at row 1

**Comment by 9547** [comment]
> @9547 it looks there is a test failure:
> 
> ```
> 
> [2020-11-20T00:06:10.822Z] 
> 
> 
> 
> [2020-11-20T00:06:10.822Z] ----------------------------------------------------------------------
> 
> 
> 
> [2020-11-20T00:06:10.822Z] FAIL: integration_test.go:7732: testIntegrationSuite.TestIssue19892
> 
> 
> 
> [2020-11-20T00:06:10.822Z] 
> 
> 
> 
> [2020-11-20T00:06:10.822Z] integration_test.go:7755:
> 
> 
> 
> [2020-11-20T00:06:10.822Z]     tk.MustQuery("SHOW WARNINGS").Check(testkit.Rows("Warning 1292 Incorrect timestamp value: '0000-00-00 20:00:00'"))
> 
> 
> 
> [2020-11-20T00:06:10.822Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:63:
> 
> 
> 
> [2020-11-20T00:06:10.822Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
> 
> 
> 
> [2020-11-20T00:06:10.822Z] ... obtained string = ""
> 
> 
> 
> [2020-11-20T00:06:10.822Z] ... expected string = "[Warning 1292 Incorrect timestamp value: '0000-00-00 20:00:00']\n"
> 
> 
> 
> [2020-11-20T00:06:10.822Z] ... sql:SHOW WARNINGS, args:[]
> 
> 
> 
> [2020-11-20T00:06:10.822Z] 
> 
> 
> 
> [2020-11-20T00:06:10.822Z] 
> 
> 
> 
> [2020-11-20T00:06:10.822Z] ----------------------------------------------------------------------
> 
> ```
> 
> 
> 
> I think I've fixed the issue in the `tidb-test` suite. You can test it with the command `/run-all-tests tidb-test=pr/1109`.

Thanks for your help. I'll have a look at it tonight

**Comment by 9547** [comment]
@nullnotnil I've fixed it 


```sql
mysql root@localhost:test> CREATE TABLE `users` (
                       ->    `id` bigint(20) NOT NULL AUTO_INCREMENT,
                       ->    `age` bigint(20) DEFAULT NULL,
                       ->    `user_num` bigint(20) DEFAULT NULL,
                       ->    `name` varchar(255) DEFAULT NULL,
                       ->    `birthday` timestamp NULL DEFAULT NULL,
                       ->    `created_at` timestamp NULL DEFAULT NULL,
                       ->    `updated_at` timestamp NULL DEFAULT NULL,
                       ->    `billing_address_id` bigint(20) DEFAULT NULL,
                       ->    `shipping_address_id` bigint(20) DEFAULT NULL,
                       ->    `latitude` double DEFAULT NULL,
                       ->    `company_id` bigint(20) DEFAULT NULL,
                       ->    `role` varchar(255) DEFAULT NULL,
                       ->    `password_hash` varbinary(255) DEFAULT NULL,
                       ->    PRIMARY KEY (`id`)
                       ->  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
                       ->
                       ->  SET sql_mode=DEFAULT;
                       ->  SHOW VARIABLES like 'sql_mode';
Query OK, 0 rows affected
Time: 0.017s

Query OK, 0 rows affected
Time: 0.001s

+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                     |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+

1 row in set
Time: 0.051s
mysql root@localhost:test> INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
(1292, "Incorrect timestamp value: '0000-00-00' for column 'birthday' at row 1")
mysql root@localhost:test> SET sql_mode=REPLACE(@@sql_mode,'NO_ZERO_DATE', '');
                       ->  SHOW VARIABLES like 'sql_mode';
Query OK, 0 rows affected
Time: 0.001s

+---------------+------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                        |
+---------------+------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+------------------------------------------------------------------------------------------------------------------------------+

1 row in set
Time: 0.009s
mysql root@localhost:test> INSERT INTO `users` (`age`,`user_num`,`name`,`birthday`) VALUES (1, 0, 'OrderPluckUser1', '0000-00-00');
Query OK, 1 row affected
Time: 0.005s
mysql root@localhost:test> show warnings;
+-------+------+---------+
| Level | Code | Message |
+-------+------+---------+
```

The `Timestamp` is a little different to `Datetime/Date`'s behavior in MySQL8.0, see as below: 

  | NZD | NZD\|ST | ELSE | ELSE\|ST
-- | -- | -- | -- | --
0000-00-01 | Success + Warning | Error | Success + Warning | ERROR
0000-00-00 | Success + Warning | Error | Success | Success

* **NZD**: NO_ZERO_DATE_MODE
* **ST**: STRICT_TRANS_TABLES
* **ELSE**: empty or NO_ZERO_IN_DATE_MODE

File: expression/integration_test.go (hunk 7 above)
Comment (9547) [reply expression/integration_test.go:7794]: IMO, this error is returned from `table.CastValue` function https://github.com/pingcap/tidb/blob/bec1cc01b506ea94b86e105e8126de1d208b6bfa/table/column.go#L168 

Seems we didn't the row index of thie datum. If I've missed anything, please let me know it.

File: table/column.go [hunk 8]
```diff
@@ -177,10 +177,84 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
 		if err1 != nil {
 			logutil.BgLogger().Warn("Datum ToString failed", zap.Stringer("Datum", val), zap.Error(err1))
 		}
-		err = sc.HandleTruncate(types.ErrTruncatedWrongVal.GenWithStackByArgs(col.FieldType.CompactStr(), str))
-	} else {
-		err = sc.HandleTruncate(err)
+		err = types.ErrTruncatedWrongVal.GenWithStackByArgs(col.FieldType.CompactStr(), str)
+	} else if (sc.InInsertStmt || sc.InUpdateStmt) && !casted.IsNull() &&
+		(val.Kind() != types.KindMysqlTime || !val.GetMysqlTime().IsZero()) &&
```
Comment (blacktear23) [inline table/column.go:182]: what about extract below code into a function?

Comment (9547) [reply table/column.go:182]: May I ask whether this piece of code https://github.com/pingcap/tidb/blob/bec1cc01b506ea94b86e105e8126de1d208b6bfa/table/column.go#L183-L254 should be included with a function? At present, there is a lot of code to handle Datetime in this part, and putting it in `CastValue` will affect the main logic. 

Good idea, I can put it into a function such as `castDatetime()`.

Comment (blacktear23) [reply table/column.go:182]: yes, the code that you added can be put into a function, so we can make CastValue function more readable.

**Comment by nullnotnil** [comment]
> /run-common-test tidb-test=pr/1109
> /run-integration-common-test tidb-test=pr/1109

Hmm.. I don't think my fix for the gorm test is working correctly. It worked locally, but depended on the mysql command line client. I will take a look at it tomorrow.

**Comment by lzmhhh123** [comment]
> > /run-common-test tidb-test=pr/1109
> > /run-integration-common-test tidb-test=pr/1109
> 
> Hmm.. I don't think my fix for the gorm test is working correctly. It worked locally, but depended on the mysql command line client. I will take a look at it tomorrow.

OK. In the badest case, we can add a rand DateTime for each inserted row.

**Comment by nullnotnil** [comment]
> OK. In the worst case, we can add a rand DateTime for each inserted row.

That was my initial plan, but the zero date is used on a table which uses this to signify a `deleted_at` date:

```
INSERT INTO `addresses` (`address1`,`address2`,`post`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?) [arguments: (Billing Address pluck_user3, , , 2020-11-19 20:30:17.882469, 2020-11-19 20:30:17.882469, 0000-00-00)];
```

I would have to create a special valid date to replace this, which is not ideal. In anycase, the gorm test is now passing with an expicit sql mode.

**Comment by nullnotnil** [comment]
There were more broken tests than I first noticed:
- Gorm test  (fixed in pr/1109)
- JDBC test (fixed in pr/1109)
- mysql_test (should be fixed in https://github.com/pingcap/mysql-tester/pull/9 )

**Comment by 9547** [comment]
@nullnotnil Is there anything I need to fix first, or I can help?

**Comment by nullnotnil** [comment]
> @nullnotnil Is there anything I need to fix first, or I can help?

It's okay. I took another look at it, and I think I will fix the mysql_test cases that break and close https://github.com/pingcap/mysql-tester/pull/9 . It doesn't look as bad as I thought - give me a few hours :-)

**Comment by nullnotnil** [comment]
I don't think that we should cherry-pick this into the release branch (v4.0). Given that the regression test suite is breaking in a few places, there are likely apps that are depending on this without knowing it. It is better to have them discover the issue when upgrading to the next major release.

**Comment by lzmhhh123** [comment]
> I don't think that we should cherry-pick this into the release branch (v4.0). Given that the regression test suite is breaking in a few places, there are likely apps that are depending on this without knowing it. It is better to have them discover the issue when upgrading to the next major release.

OK, I agree.

**Review by lzmhhh123 — APPROVED** [review]
