### PR TITLE
planner: plan cache always check scheme valid in RC isolation level

### LINKED ISSUE #34447: query result is incorrect when execute prepared statement in RC isolation with plan cache enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
func TestPlanCacheWithRCWhenInfoSchemaChange(t *testing.T) {
	orgEnable := plannercore.PreparedPlanCacheEnabled()
	defer func() {
		plannercore.SetPreparedPlanCache(orgEnable)
	}()
	plannercore.SetPreparedPlanCache(true)

	store, clean := createStorage(t)
	defer clean()
	tk1 := testkit.NewTestKit(t, store)
	tk1.MustExec("use test")
	tk1.MustExec("create table t1(id int primary key, c int, index ic (c))")
	tk1.MustExec("prepare s from 'select /*+use_index(t1, ic)*/ * from t1 where 1'")
	tk1.MustExec("set tx_isolation='READ-COMMITTED'")
	tk1.MustExec("begin pessimistic")
	tk1.MustQuery("execute s").Check(testkit.Rows())

	tk2 := testkit.NewTestKit(t, store)
	tk2.MustExec("use test")
	tk2.MustExec("alter table t1 drop index ic")
	tk2.MustExec("insert into t1 values(1, 0)")

        // This assert will fail and the actual result is empty
	tk1.MustQuery("execute s").Check(testkit.Rows("1 0"))
}
```

### 2. What did you expect to see? (Required)

The test case will pass

### 3. What did you see instead (Required)

Test test case failed

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by you06**
Signed-off-by: you06 <you1474600@gmail.com>

### What problem does this PR solve?

Issue Number: close #34447

Problem Summary:

### What is changed and how it works?

Plan cache always checks if the schema is stale in the RC isolation level because it should guarantee the index still exist in the latest schema.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/optimize.go [hunk 1]
```diff
@@ -73,7 +73,14 @@ func GetExecuteForUpdateReadIS(node ast.Node, sctx sessionctx.Context) infoschem
 			execID = vars.PreparedStmtNameToID[execStmt.Name]
 		}
 		if preparedPointer, ok := vars.PreparedStmts[execID]; ok {
-			if preparedObj, ok := preparedPointer.(*core.CachedPrepareStmt); ok && preparedObj.ForUpdateRead {
+			// RC isolation level or statement with for-update read need to check if the schema is changed
+			// before use the cached plan.
+			checkSchema := vars.IsIsolation(ast.ReadCommitted)
```
Comment (lcwangchao) [inline planner/optimize.go:78]: Should prepare/execute in binary protocol be considerate too?

**Comment by you06** [comment]
This fix handles the prepared statements which use the latest schema in `OptimizePreparedPlan`. However, it updates the schema in a tricky way, the schema is changed in `OptimizePreparedPlan`, to guarantee the plan optimization and execution using the same schema, this fix syncs the schema before building executors.

**Comment by you06** [comment]
@qw4990 PTAL

File: planner/optimize.go (hunk 1 above)
Comment (qw4990) [reply planner/optimize.go]: Yes, here is the code path:
image

File: planner/core/common_plans.go [hunk 2]
```diff
@@ -235,6 +240,18 @@ func (e *Execute) OptimizePreparedPlan(ctx context.Context, sctx sessionctx.Cont
...
+	checkLatestSchema := preparedObj.ForUpdateRead || vars.IsIsolation(ast.ReadCommitted)
+	checkLatestSchema = checkLatestSchema && vars.ConnectionID > 0
+	if checkLatestSchema {
+		is = domain.GetDomain(sctx).InfoSchema()
+		is = temptable.AttachLocalTemporaryTableInfoSchema(sctx, is)
+		txnManager := sessiontxn.GetTxnManager(sctx)
+		if p, isOK := txnManager.GetContextProvider().(*legacy.SimpleTxnContextProvider); isOK {
+			p.InfoSchema = is
+		}
+	}
```
Comment (qw4990) [inline planner/core/common_plans.go]: Would this check affect the performance? I'm not sure whether the operation of getting the current `information-schema` is heavy or not.

Comment (you06) [reply planner/core/common_plans.go]: Getting the current schema will not affect performance because it actually loads from the cache.

**Review by qw4990 — APPROVED** [review]

**Comment by you06** [comment]
@lcwangchao I change this patch by updating the latest schema for the required statements before optimizing, PTAL again.

File: session/session.go [hunk 3]
```diff
@@ -2374,7 +2374,7 @@ func (s *session) ExecutePreparedStmt(ctx context.Context, stmtID uint32, args [
 		if err != nil {
 			return nil, err
 		}
-	} else if preparedStmt.ForUpdateRead {
+	} else if s.sessionVars.IsIsolation(ast.ReadCommitted) || preparedStmt.ForUpdateRead {
 		is = domain.GetDomain(s).InfoSchema()
```
Comment (lcwangchao) [inline session/session.go:2378]: Here we should use `temptable.AttachLocalTemporaryTableInfoSchema` to wrap the infoschema because temporary tables may exist in session

**Review by lcwangchao — COMMENTED** [review]
Rest LGTM

**Review by lcwangchao — APPROVED** [review]
