### PR TITLE
table: fix issue of get default value from column when column doesn't have default value | tidb-test=pr/2305

### LINKED ISSUE #50043: assertion failed when inserting some rows
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
create table tf8f605ff ( col_30 boolean ,col_31 decimal ( 37 , 17 )    default 957.79 ,col_32 time   not null , unique key idx_6 ( col_32 ,col_30 ,col_31 ) ,unique key idx_7 ( col_31 ,col_32 ,col_30 ) ,unique key idx_8 ( col_31 ,col_32 ,col_30 ) ) charset gbk collate gbk_bin;
alter table tf8f605ff add column col_59 tinyint  unsigned not null;
alter table tf8f605ff alter column col_31 drop default;
alter table tf8f605ff add unique key idx_25 ( col_30 );
INSERT INTO `tf8f605ff` VALUES (0,NULL,'12:09:39',128), (1,211.00000000000000000,'10:44:41',76);
insert ignore into tf8f605ff  values ( 0,0.71,'17:42:07.00',2 ) ,( 1,5207.803,'05:05:08.00',42 ) ,( 1,8.755,'16:53:49.00',19 ) ,( 0,0.81,'14:08:29.00',208 ) on duplicate key update col_31 = 8438.3418, col_59 = 61, col_32 = '00:35:59.00', col_30 = 0;
```

### 2. What did you expect to see? (Required)
No error

### 3. What did you see instead (Required)
``` SQL
mysql> insert ignore into tf8f605ff  values ( 0,0.71,'17:42:07.00',2 ) ,( 1,5207.803,'05:05:08.00',42 ) ,( 1,8.755,'16:53:49.00',19 ) ,( 0,0.81,'14:08:29.00',208 ) on duplicate key update col_31 = 8438.3418, col_59 = 61, col_32 = '00:35:59.00', col_30 = 0;
ERROR 8141 (HY000): assertion failed: key: 7480000000000005125f69800000000000000107800027d117be5e000380000000000000000625118000000000000000000000000000000000, assertion: Exist, start_ts: 446766707530006528, existing start ts: 0, existing commit ts: 0
```
### 4. What is your TiDB version? (Required)
33480e8c8d8874811a5362767c81d40c9a057cb6

### LINKED ISSUE #51324: default value of column with no default value behavior is not compatible with mysql 8.0.29
## Bug Report

I found this issue when investigating #50043

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (id int key, a int, b enum('a', 'b'));
alter table t alter column a drop default;
alter table t alter column b drop default;
insert ignore into t set id = 4;
show warnings;
insert ignore into t set id = 6, a = DEFAULT, b = DEFAULT;
show warnings;
```

### 2. What did you expect to see? (Required)

From MySQL 8.0.29

the `show warnings` result should be:

```sql
> show warnings;
+---------+------+----------------------------------------+
| Level   | Code | Message                                |
+---------+------+----------------------------------------+
| Warning | 1364 | Field 'a' doesn't have a default value |
+---------+------+----------------------------------------+
```

And the table data should be:

```sql
> select * from t;
+----+--------+--------+
| id | a      | b      |
+----+--------+--------+
| 4  | <null> | <null> |
| 6  | <null> | <null> |
+----+--------+--------+
```

### 3. What did you see instead (Required)

the `show warnings` result is:

```sql
> show warnings;
+---------+------+---------------------------+
| Level   | Code | Message                   |
+---------+------+---------------------------+
| Warning | 1048 | Column 'a' cannot be null |
+---------+------+---------------------------+
```

And the table data is:

```sql
> select * from t;
+----+---+--------+
| id | a | b      |
+----+---+--------+
| 4  | 0 | <null> |
| 6  | 0 | <null> |
+----+---+--------+
```

### 4. What is your TiDB version? (Required)

```sql
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v8.0.0-alpha-301-g1438892b9f-dirty       |
| Edition: Community                                        |
| Git Commit Hash: 1438892b9fed5efc6fae8df8d44c239368ced262 |
| Git Branch: master                                        |
| UTC Build Time: 2024-02-26 09:58:28                       |
| GoVersion: go1.21.5                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: unistore                                           |
+-----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #50043, close #51324

Problem Summary: 
- fix issue #50043 that get wrong default value when column doesn't have default value.
- fix issue of  #51324 that default value of column with no default value behavior is not compatible with mysql 8.0.29

### What changed and how does it work?

This PR reverts some changes introduced by #35072 and use another way to check `ErrNoDefaultValue` before insert.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@wjhuang2016 @lcwangchao @Defined2014 @bb7133 PTAL

File: pkg/table/column.go [hunk 1]
```diff
@@ -624,8 +624,13 @@ func getColDefaultValue(ctx expression.BuildContext, col *model.ColumnInfo, defa
 }
 
 func getColDefaultValueFromNil(ctx expression.BuildContext, col *model.ColumnInfo, args *getColOriginDefaultValue) (types.Datum, error) {
-	if !mysql.HasNotNullFlag(col.GetFlag()) && !mysql.HasNoDefaultValueFlag(col.GetFlag()) {
-		return types.Datum{}, nil
+	if !mysql.HasNotNullFlag(col.GetFlag()) {
+		if !mysql.HasNoDefaultValueFlag(col.GetFlag()) ||
+			(col.GetDefaultValue() == nil && col.GetOriginDefaultValue() == nil) {
+			// In CanSkip function(in table/tables pkg), if column's default value is nil, and the column value is NULL too,
+			// then the column value can be skipped and won't encode to row value.
```
Comment (crazycs520) [inline pkg/table/column.go:631]: Maybe we need to check HasNoDefaultValueFlag in the `CanSkip` function too?

But this fix is still needed, otherwise, the same write in the old version will also have this problem.

**Comment by crazycs520** [comment]
@tangenta @zimulala @tiancaiamao PTAL

**Review by zimulala — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]

File: pkg/table/column.go (hunk 1 above)
Comment (lcwangchao) [reply pkg/table/column.go:635]: Seems this fix should only affect `GetColOriginDefaultValue` (nil is from `OringinDefaultValue`), can we change the bool to `isOriginalDefaultValueNil` ?

**Comment by crazycs520** [comment]
> /hold , Since I may found other bug.

Ok to review now, and fix another issue #51324.

**Review by Defined2014 — APPROVED** [review]
Please update mysql-test

File: pkg/table/column.go [hunk 2]
```diff
@@ -536,6 +536,24 @@ func GetColOriginDefaultValueWithoutStrictSQLMode(ctx sessionctx.Context, col *m
 	})
 }
 
+// CheckNoDefaultValueForInsert checks if the column has no default value before insert data.
+// CheckNoDefaultValueForInsert extrats the check logic from getColDefaultValueFromNil,
+// since getColDefaultValueFromNil function is public path and both read/write and other places use it.
+// But CheckNoDefaultValueForInsert logic should only check before insert.
+func CheckNoDefaultValueForInsert(ctx expression.BuildContext, col *model.ColumnInfo) error {
```
Comment (lcwangchao) [inline pkg/table/column.go:543]: You can use `errctx.Context` as the input argument. Seems this function does not need to build any expression

File: pkg/table/column.go [hunk 3]
```diff
@@ -624,7 +642,7 @@ func getColDefaultValue(ctx expression.BuildContext, col *model.ColumnInfo, defa
 }
 
 func getColDefaultValueFromNil(ctx expression.BuildContext, col *model.ColumnInfo, args *getColOriginDefaultValue) (types.Datum, error) {
-	if !mysql.HasNotNullFlag(col.GetFlag()) && !mysql.HasNoDefaultValueFlag(col.GetFlag()) {
+	if !mysql.HasNotNullFlag(col.GetFlag()) {
```
Comment (lcwangchao) [inline pkg/table/column.go:645]: seems line 633 always return true after this change

**Review by lcwangchao — APPROVED** [review]

File: pkg/table/column.go (hunk 3 above)
Comment (crazycs520) [reply pkg/table/column.go:645]: nice catch, done.

File: pkg/table/column.go (hunk 2 above)
Comment (crazycs520) [reply pkg/table/column.go]: nice catch, done.

File: pkg/table/column.go [hunk 4]
```diff
@@ -624,22 +642,19 @@ func getColDefaultValue(ctx expression.BuildContext, col *model.ColumnInfo, defa
...
 		return types.Datum{}, nil
 	}
 	if col.GetType() == mysql.TypeEnum {
 		// For enum type, if no default value and not null is set,
```
Comment (zimulala) [inline pkg/table/column.go:649]: Do we need to update this comment?

File: pkg/table/column.go [hunk 5]
```diff
@@ -624,22 +642,19 @@ func getColDefaultValue(ctx expression.BuildContext, col *model.ColumnInfo, defa
 }
 
 func getColDefaultValueFromNil(ctx expression.BuildContext, col *model.ColumnInfo, args *getColOriginDefaultValue) (types.Datum, error) {
-	if !mysql.HasNotNullFlag(col.GetFlag()) && !mysql.HasNoDefaultValueFlag(col.GetFlag()) {
```
Comment (zimulala) [inline pkg/table/column.go:627]: Will this change affect reading? Because the PR handles the insert operation, the read operation lacks the judgment logic.

File: pkg/table/column.go [hunk 6]
```diff
@@ -536,6 +537,23 @@ func GetColOriginDefaultValueWithoutStrictSQLMode(ctx expression.BuildContext, c
 	})
 }
 
+// CheckNoDefaultValueForInsert checks if the column has no default value before insert data.
+// CheckNoDefaultValueForInsert extrats the check logic from getColDefaultValueFromNil,
+// since getColDefaultValueFromNil function is public path and both read/write and other places use it.
+// But CheckNoDefaultValueForInsert logic should only check before insert.
+func CheckNoDefaultValueForInsert(sc *stmtctx.StatementContext, col *model.ColumnInfo) error {
+	if mysql.HasNoDefaultValueFlag(col.GetFlag()) && !col.DefaultIsExpr && col.GetDefaultValue() == nil && col.GetType() != mysql.TypeEnum {
```
Comment (zimulala) [inline pkg/table/column.go:545]: Do we need to check "col.GetOriginDefaultValue() == nil"? May be we can add a test for "alter table ... add column".

File: pkg/table/column.go (hunk 5 above)
Comment (crazycs520) [reply pkg/table/column.go:627]: Yes. My goal is to make `HasNoDefaultValueFlag` not affect the reading. I think `HasNoDefaultValueFlag` check should only check when insert, and not check when read operation.

`HasNoDefaultValueFlag` judgment logic here is introduced by #35072, and with this judgment logic, will cause bug in issue #51324 .

File: pkg/table/column.go (hunk 4 above)
Comment (crazycs520) [reply pkg/table/column.go:649]: No, this comment is right. I just reverts some changes that introduced in #35072.

File: pkg/table/column.go (hunk 6 above)
Comment (crazycs520) [reply pkg/table/column.go:545]: I'm not sure about this, since this function logic is extracted from getColDefaultValueFromNil, and the original check don't check `col.GetOriginDefaultValue() == nil`.

Comment (crazycs520) [reply pkg/table/column.go:545]: Already add a test for it.

Comment (tiancaiamao) [reply pkg/table/column.go:545]: `&& col.GetType() != mysql.TypeEnum`
enum type seems special, why?

Comment (tiancaiamao) [reply pkg/table/column.go:545]: Get it!
 https://github.com/pingcap/tidb/pull/51309/files#diff-5bd22e23c06e1720146774f77761fe2f910d693465e39ac954c94e5f5f3bf4c6R649

**Review by zimulala — APPROVED** [review]
