### PR TITLE
planner: apply ordering ratio to tablerangescan | tidb-test=pr/2527

### LINKED ISSUE #61540: Optimizer chose tablerangescan with order rather than indexrangescan
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
CREATE TABLE `t1` (
  `a` int,
  `b` int,
  `c` int,
  Primary KEY `iba` (`a`, `b`),
  KEY `iac` (`a`, `c`)
);

set @@cte_max_recursion_depth=10000000;
INSERT INTO t1 (a, b, c)
SELECT mod(a, 80) AS a, a as b, mod(a, 100) AS c
FROM (
    WITH RECURSIVE x AS (
        SELECT 1 AS a
        UNION ALL
        SELECT a + 1 AS a
        FROM x
        WHERE a < 1000000
    )
    SELECT a
    FROM x
) AS subquery;

update t1 set a = 6 where a < 6;

analyze table t1;
```
### 2. What did you expect to see? (Required)
```
tidb> explain analyze select * from t1 use index (iac) where a = 6 and c = 66 order by b limit 10000;
+---------------------------+---------+---------+-----------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------+---------+
| id                        | estRows | actRows | task      | access object             | execution info                                                                                                                                                                                                                                                                                                | operator info                       | memory  | disk    |
+---------------------------+---------+---------+-----------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------+---------+
| TopN_10                   | 2496.69 | 2500    | root      |                           | time:23.6ms, open:389.7µs, close:30.8µs, loops:4, RU:9.33                                                                                                                                                                                                                                                     | test.t1.b, offset:0, count:10000    | 89.0 KB | 0 Bytes |
| └─IndexReader_19          | 2496.69 | 2500    | root      |                           | time:20.6ms, open:293µs, close:28.7µs, loops:5, cop_task: {num: 5, max: 9.71ms, min: 705.3µs, avg: 3.98ms, p95: 9.71ms, tot_proc: 18ms, copr_cache_hit_ratio: 0.00, build_task_duration: 186.1µs, max_distsql_concurrency: 1}, fetch_resp_duration: 19.9ms, rpc_info:{Cop:{num_rpc:5, total_time:19.8ms}}     | index:IndexRangeScan_18             | 39.2 KB | N/A     |
|   └─IndexRangeScan_18     | 2496.69 | 2500    | cop[tikv] | table:t1, index:iac(a, c) | tikv_task:{proc max:9.55ms, min:678.4µs, avg: 3.92ms, p80:9.55ms, p95:9.55ms, iters:0, tasks:5}, time_detail: {total_process_time: 18ms}                                                                                                                                                                      | range:[6 66,6 66], keep order:false | N/A     | N/A     |
+---------------------------+---------+---------+-----------+---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+---------+---------+
```
### 3. What did you see instead (Required)
```
tidb> explain analyze select * from t1 where a = 6 and c = 66 order by b limit 10000;

+-------------------------------+----------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+---------+------+
| id                            | estRows  | actRows | task      | access object | execution info                                                                                                                                                                                                                                                                                         | operator info                | memory  | disk |
+-------------------------------+----------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+---------+------+
| Limit_12                      | 2496.69  | 2500    | root      |               | time:78.3ms, open:50.4µs, close:7.33µs, loops:4, RU:28.66                                                                                                                                                                                                                                              | offset:0, count:10000        | N/A     | N/A  |
| └─TableReader_23              | 2496.69  | 2500    | root      |               | time:78.2ms, open:45.3µs, close:6.83µs, loops:4, cop_task: {num: 5, max: 27.7ms, min: 9.2ms, avg: 15.6ms, p95: 27.7ms, tot_proc: 76ms, copr_cache_hit_ratio: 0.00, build_task_duration: 28µs, max_distsql_concurrency: 1}, fetch_resp_duration: 78.1ms, rpc_info:{Cop:{num_rpc:5, total_time:78ms}}    | data:Limit_22                | 39.2 KB | N/A  |
|   └─Limit_22                  | 2496.69  | 2500    | cop[tikv] |               | tikv_task:{proc max:27.7ms, min:9.18ms, avg: 15.6ms, p80:27.7ms, p95:27.7ms, iters:0, tasks:5}, time_detail: {total_process_time: 76ms}                                                                                                                                                                | offset:0, count:10000        | N/A     | N/A  |
|     └─Selection_21            | 2496.69  | 2500    | cop[tikv] |               | tikv_task:{proc max:27.7ms, min:9.18ms, avg: 15.6ms, p80:27.7ms, p95:27.7ms, iters:0, tasks:5}                                                                                                                                                                                                         | eq(test.t1.c, 66)            | N/A     | N/A  |
|       └─TableRangeScan_20     | 87288.63 | 2500    | cop[tikv] | table:t1      | tikv_task:{proc max:27.7ms, min:9.18ms, avg: 15.6ms, p80:27.7ms, p95:27.7ms, iters:0, tasks:5}                                                                                                                                                                                                         | range:[6,6], keep order:true | N/A     | N/A  |
+-------------------------------+----------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+---------+------+
```
### 4. What is your TiDB version? (Required)

Current (master)

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #61540 

Problem Summary:

### What changed and how does it work?

Similar to other PRs that have utilized tidb_opt_ordering_index_selectivity_ratio - this PR will allow this variable to adjust the estimated rows for an ordering plan estimate for the following:
- table range scan - where the table range scan provides order,
- there are other filters that are not part of the PK. 
- The query also includes limit.

There is risk to the optimizer's estimate that it may underestimate "when" the rows will be found in the order provided, but match the filters that occur outside of that ordering plan. 

Two other use cases that were previously addressed include 
- order provided by an index, but filtering occurs on columns for the same table that are not matching in the index.
- order provided by an index, but filtering occurs on tables after the leading table in a join.

This PR extends this logic when the ordering is provided by an table range scan.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/plan_cost_ver2.go [hunk 1]
```diff
@@ -529,11 +529,14 @@ func getPlanCostVer24PhysicalTopN(pp base.PhysicalPlan, taskType property.TaskTy
 	}
 
 	rows := max(MinNumRows, getCardinality(p.Children()[0], option.CostFlag))
-	n := max(1, float64(p.Count+p.Offset))
-	if n > 10000 {
-		// It's only used to prevent some extreme cases, e.g. `select * from t order by a limit 18446744073709551615`.
-		// For normal cases, considering that `rows` may be under-estimated, better to keep `n` unchanged.
-		n = min(n, rows)
+	n := max(MinNumRows, float64(p.Count+p.Offset))
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/plan_cost_ver2.go:533]: Variable is reused from other scenarios

File: pkg/planner/cardinality/cross_estimation.go [hunk 2]
```diff
@@ -60,6 +60,16 @@ func AdjustRowCountForTableScanByLimit(sctx planctx.PlanContext,
...
+		// if orderRatio is enabled, we use it to recognize that we must scan more rows to find the first row.
+		orderRatio := sctx.GetSessionVars().OptOrderingIdxSelRatio
+		// Record the variable usage for explain explore.
+		sctx.GetSessionVars().RecordRelevantOptVar(vardef.TiDBOptOrderingIdxSelRatio)
+		if orderRatio > 0 {
+			rowCount += max(0, (path.CountAfterAccess-rowCount)) * orderRatio
+		}
+	}
 	return rowCount
 }
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/cardinality/cross_estimation.go]: I will consider this in a general refactor PR.

File: pkg/planner/core/plan_cost_ver2.go [hunk 3]
```diff
@@ -529,11 +529,14 @@ func getPlanCostVer24PhysicalTopN(pp base.PhysicalPlan, taskType property.TaskTy
...
+	if n > 100 {
+		// `rows` may be under-estimated. We need to adjust 'n' to ensure we keep a reasonable value.
+		if rows < float64(p.Offset) {
+			n = rows + float64(p.Offset)
+		} else {
+			n = max(min(n, rows), 100) // set a minimum of 100 to avoid too low n
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/plan_cost_ver2.go]: In next commit

File: pkg/planner/cardinality/cross_estimation.go [hunk 4]
```diff
@@ -60,6 +60,16 @@ func AdjustRowCountForTableScanByLimit(sctx planctx.PlanContext,
...
 		}
 	}
+
+	if isMatchProp && path.CountAfterAccess > rowCount {
+		// if orderRatio is enabled, we use it to recognize that we must scan more rows to find the first row.
+		orderRatio := sctx.GetSessionVars().OptOrderingIdxSelRatio
+		// Record the variable usage for explain explore.
+		sctx.GetSessionVars().RecordRelevantOptVar(vardef.TiDBOptOrderingIdxSelRatio)
+		if orderRatio > 0 {
+			rowCount += max(0, (path.CountAfterAccess-rowCount)) * orderRatio
```
Comment (fixdb) [inline pkg/planner/cardinality/cross_estimation.go]: `rowCount += max(0, path.CountAfterAccess - rowCount) * orderRatio`

File: pkg/planner/core/find_best_task.go [hunk 5]
```diff
@@ -3392,10 +3392,11 @@ func getOriginalPhysicalTableScan(ds *logicalop.DataSource, prop *property.Physi
 	ts.SetSchema(ds.Schema().Clone())
 	rowCount := path.CountAfterAccess
 	// Add an arbitrary tolerance factor to account for comparison with floating point
-	if (prop.ExpectedCnt + cost.ToleranceFactor) < ds.StatsInfo().RowCount {
+	if (prop.ExpectedCnt+cost.ToleranceFactor) < ds.StatsInfo().RowCount ||
```
Comment (fixdb) [inline pkg/planner/core/find_best_task.go]: nit: `prop.ExpectedCnt + cost.ToleranceFactor`

File: pkg/planner/core/find_best_task.go [hunk 6]
```diff
@@ -3392,10 +3392,11 @@ func getOriginalPhysicalTableScan(ds *logicalop.DataSource, prop *property.Physi
...
+		(isMatchProp && min(ds.StatsInfo().RowCount, prop.ExpectedCnt) < rowCount && len(path.AccessConds) > 0) {
```
Comment (hawkingrei) [inline pkg/planner/core/find_best_task.go]: ```ds.StatsInfo().RowCount``` can be placed above the if statement.

It will look like this.
```
rowCount := ds.StatsInfo().RowCount

if (xxx < rowCount) || min(rowcount, prop.ExpectedCnt) {
```

File: pkg/planner/cardinality/cross_estimation.go (hunk 4 above)
Comment (terry1purcell) [reply pkg/planner/cardinality/cross_estimation.go]: When attempting to format the code as suggested here - VsCode will automatically rewrite this to remove the blank spaces again.

File: pkg/planner/core/find_best_task.go (hunk 6 above)
Comment (terry1purcell) [reply pkg/planner/core/find_best_task.go]: Done - in next commit

File: pkg/planner/core/find_best_task.go (hunk 5 above)
Comment (terry1purcell) [reply pkg/planner/core/find_best_task.go]: Removing spaces is an automatic rewrite that VsCode is making - can't determine how to disable it (despite searching for a solution)

**Review by elsa0520 — APPROVED** [review]
LGTM
