### PR TITLE
planner: fix wrongly identify the changes in the expression and skip the plan cache

### LINKED ISSUE #64263: plan cache can't work after update to v8.5.3
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `table_A` (
  `column_1` bigint(20) unsigned NOT NULL,
  `column_2` int(10) unsigned NOT NULL,
  `column_3` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `column_4` int(10) unsigned NOT NULL,
  `column_5` text COLLATE utf8mb4_general_ci DEFAULT NULL,
  `column_6` datetime NOT NULL,
  PRIMARY KEY (`column_1`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_4_6` (`column_4`, `column_6`),
  KEY `idx_4` (`column_4`),
  KEY `idx_6` (`column_6`),
  KEY `idx_4_3_2` (`column_4`, `column_3`, `column_2`),
  KEY `idx_3_2` (`column_3`, `column_2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


SET global tidb_opt_fix_control = "44830:ON";
SET tidb_opt_fix_control = "44830:ON";
SET GLOBAL tidb_enable_non_prepared_plan_cache=ON;
SET tidb_enable_non_prepared_plan_cache=ON;


SELECT
  `column_1`,
  `column_2`,
  `column_3`,
  `column_4`,
  `column_5`,
  `column_6`
FROM
  `table_A`
WHERE
  `column_3` = "M 5 9 2 9 2 5 4 6 8 4 9"
  AND (
    `column_2` IN (1)
    OR `column_4` = 121092106
  )
ORDER BY
  `column_6` DESC,
  `column_1` DESC
LIMIT
  1000;
```

### 2. What did you expect to see? (Required)
```
mysql> SELECT @@last_plan_from_cache;
+------------------------+
| @@last_plan_from_cache |
+------------------------+
|                      1 |
+------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> SELECT @@last_plan_from_cache;
+------------------------+
| @@last_plan_from_cache |
+------------------------+
|                      0 |
+------------------------+
1 row in set (0.00 sec)

there is warning: 
```
Image

### 4. What is your TiDB version? (Required)

853 and master

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #64263 

Problem Summary:

### What changed and how does it work?

The issue was triggered by https://github.com/pingcap/tidb/pull/56136 , The original logic would cause any two OR expressions and a scalar function to skip the plan cache, regardless of whether an expression transformation occurs.

This PR introduces the correct logic to skip the plan cache only after a transformation has occurred.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/explainfor_test.go [hunk 1]
```diff
@@ -500,7 +500,7 @@ func TestIssue28259(t *testing.T) {
 	tk.MustExec("set @a=2, @b=1, @c=1;")
 	tk.MustQuery("execute stmt using @a,@b,@c;").Check(testkit.Rows())
 	// Plan cache skipped due to OR simplification
```
Comment (hawkingrei) [inline pkg/executor/explainfor_test.go]:
```suggestion
	// Plan cache should not be skipped because the OR simplification has not been performed.
```

File: pkg/planner/core/rule/rule_predicate_simplification.go [hunk 2]
```diff
@@ -337,12 +337,12 @@ func comparisonPred(predType predicateType) predicateType {
 // updateOrPredicate simplifies OR predicates by dropping OR predicates if they are empty.
 // It is applied for this pattern: P AND (P1 OR P2 ... OR Pn)
 // Pi is removed if P & Pi is false/empty.
-func updateOrPredicate(ctx base.PlanContext, orPredicateList expression.Expression, scalarPredicatePtr expression.Expression) expression.Expression {
+func updateOrPredicate(ctx base.PlanContext, orPredicateList expression.Expression, scalarPredicatePtr expression.Expression) (expression.Expression, bool) {
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_predicate_simplification.go:343]: Please add some comments to explain what the second returned value means.

Comment (hawkingrei) [reply pkg/planner/core/rule/rule_predicate_simplification.go:343]: I have added the comment.

**Comment by hawkingrei** [comment]
@henrybw PTAL
