### PR TITLE
lightning: fix check disk quota routine block when some engine is importing

### LINKED ISSUE #44867: lightning disk quota block on check engine size while some engine is importing
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- import with disk quota
- just before disk quota checker tries to getEngineFileSize, some engine lock itself and tries to do import
- disk quota checker blockes on getEngineFileSize, and other engine keeps writing data into disk, and cause disk used too much
  - in one test, disk_quota=80g, but since quota checker blockes for 34m, the actual disk usage is 2.2T

### 2. What did you expect to see? (Required)
- checker keeps running even when some engine start import and ensure disk quota

### 3. What did you see instead (Required)
- checker blockes and disk quota exceeded too much.
### 4. What is your TiDB version? (Required)
current master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #44867

Problem Summary:

### What is changed and how it works?
- make pebble db a atomic reference to avoid lock when check disk quota

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix check disk quota routine block when some engine is importing
```

### CODE REVIEW

**Comment by D3Hunter** [comment]
hold until lightning integration test finished

**Review by GMHDBJD — APPROVED** [review]
LGTM

File: br/pkg/lightning/backend/local/engine.go [hunk 1]
```diff
@@ -157,14 +157,19 @@ func (e *Engine) setError(err error) {
...
 
+func (e *Engine) getDB() *pebble.DB {
+	return e.db.Load()
+}
+
 // Close closes the engine and release all resources.
 func (e *Engine) Close() error {
 	e.logger.Debug("closing local engine", zap.Stringer("engine", e.UUID), zap.Stack("stack"))
-	if e.db == nil {
+	db := e.getDB()
```
Comment (lance6716) [inline br/pkg/lightning/backend/local/engine.go:167]: maybe db := e.db.Swap(nil)

**Review by lance6716 — APPROVED** [review]

**Comment by D3Hunter** [comment]
ci pass https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/12633/pipeline
