### PR TITLE
parser,ddl: Add warning for ZEROFILL and improve display width warning

### LINKED ISSUE #46753: Warning for ZEROFILL
## Bug Report

As MySQL is giving a deprecation warning for the `ZEROFILL` attribute, we should probably do the same.

See:
- https://github.com/pingcap/tidb/pull/46651#discussion_r1318319781

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #46753 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The `ZEROFILL` attribute for integer types has been deprecated.
The warning for the use of deprecated integer display width has been improved.
```

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -768,11 +768,33 @@ func buildColumnsAndConstraints(
 	colMap := make(map[string]*table.Column, len(colDefs))
 
 	for i, colDef := range colDefs {
+		if field_types.TiDBStrictIntegerDisplayWidth {
+			switch colDef.Tp.GetType() {
+			case mysql.TypeTiny:
+				// No warning for BOOL-like tinyint(1)
+				if colDef.Tp.GetFlen() > -1 && colDef.Tp.GetFlen() != 1 {
```
Comment (mjonss) [inline ddl/ddl_api.go:775]: Please use `colDef.Tp.GetFlen() != UnspecifiedLength` instead of `> -1` Or are there other cases using negative length other than UnspecifiedLength?

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -768,11 +768,33 @@ func buildColumnsAndConstraints(
...
+					ctx.GetSessionVars().StmtCtx.AppendWarning(
+						dbterror.ErrWarnDeprecatedIntegerDisplayWidth.GenWithStackByArgs(),
+					)
+				}
+			case mysql.TypeShort, mysql.TypeInt24, mysql.TypeLong, mysql.TypeLonglong:
+				if colDef.Tp.GetFlen() > -1 {
```
Comment (mjonss) [inline ddl/ddl_api.go:781]: Ditto

**Review by mjonss — APPROVED** [review]
LGTM, just a recommendation of using UnspecifiedLength constant instead of the magic number -1.

**Comment by dveeden** [comment]
> LGTM, just a recommendation of using UnspecifiedLength constant instead of the magic number -1.

Done

**Review by wjhuang2016 — APPROVED** [review]

**Comment by easonn7** [comment]
/approve

There is no sysvar change.
