### PR TITLE
ddl: use package-level logger which preset "category" field

### LINKED ISSUE #52883: Wrong package level logger initialization timing
in https://github.com/pingcap/tidb/pull/52645 I added a package level logger

https://github.com/pingcap/tidb/blob/e8c397ff93ff55da30e553b77bd1a25f6b841510/pkg/ddl/ingest/env.go#L32

But when the variable is set, `logutil.BgLogger()` is not initialized yet. It prints to stdout instead

```
$ k logs tc-tidb-0 | more
start tidb-server ...
/tidb-server --store=tikv --advertise-address=xxx --host=0.0.0.0 --path=tc-pd:2379 --config=/etc/tidb/tidb.toml

[2024/04/25 09:30:59.400 +08:00] [INFO] [env.go:103] ["the ingest sorted directory"] [category=ddl-ingest] ["data path"=/tmp/tidb/tmp_ddl-4000]
[2024/04/25 09:30:59.400 +08:00] [INFO] [env.go:76] ["init global ingest backend environment finished"] [category=ddl-ingest] ["memory limitation"=17179869184] ["disk usage info"="disk usage: 336493137920/467794132992, backend usage: 0"] ["max open file number"=1073741816] ["lightning is initialized"=true]
[2024/04/25 09:31:06.145 +08:00] [INFO] [local.go:682] ["multi ingest support"] [category=ddl-ingest]
[2024/04/25 09:31:06.146 +08:00] [INFO] [local.go:704] ["TiKV server side free space check is enabled, so lightning will turn it off"] [category=ddl-ingest]
[2024/04/25 09:42:06.984 +08:00] [INFO] [local.go:682] ["multi ingest support"] [category=ddl-ingest]
```

we should set them after https://github.com/pingcap/tidb/blob/e8c397ff93ff55da30e553b77bd1a25f6b841510/cmd/tidb-server/main.go#L873-L880

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #52883

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

```
$ tiup playground nightly --tiflash 0 --without-monitor --db.binpath ~/Projects/tidb/bin/tidb-server
```

check log

image
image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ingest/env.go [hunk 1]
```diff
@@ -22,14 +22,14 @@ import (
...
-	"github.com/pingcap/tidb/pkg/util/logutil"
 	"github.com/pingcap/tidb/pkg/util/memory"
 	"github.com/pingcap/tidb/pkg/util/size"
 	"go.uber.org/zap"
 )
 
 var (
-	litLogger = logutil.BgLogger().With(zap.String(logutil.LogFieldCategory, "ddl-ingest"))
+	// LitLogger is the package-level logger.
+	LitLogger = zap.NewNop()
```
Comment (D3Hunter) [inline pkg/ddl/ingest/env.go:32]: leave previous value? so we can see logs in test

File: pkg/ddl/syncer/syncer.go [hunk 2]
```diff
@@ -50,6 +49,9 @@ const (
 )
 
 var (
+	// Logger is the package-level logger. It will be initialized with a field
+	// `zap.String(logutil.LogFieldCategory, "ddl")`.
+	Logger = zap.NewNop()
```
Comment (D3Hunter) [inline pkg/ddl/syncer/syncer.go:54]: here too

**Review by D3Hunter — APPROVED** [review]
rest lgtm

File: pkg/ddl/ingest/env.go (hunk 1 above)
Comment (zimulala) [inline pkg/ddl/ingest/env.go:32]: Ditto.

Comment (lance6716) [reply pkg/ddl/ingest/env.go:32]: In fact I think printing all message of passed unit test is useless, makes me hard to locate the log of failed tests. I'll try to initialize these logger to https://pkg.go.dev/go.uber.org/zap/zaptest#NewLogger

Comment (lance6716) [reply pkg/ddl/ingest/env.go:32]: > > leave previous value? so we can see logs in test
> 
> In fact I think printing all message of passed unit test is useless, makes me hard to locate the log of failed tests. I'll try to initialize these logger to https://pkg.go.dev/go.uber.org/zap/zaptest#NewLogger

I'll revert to previous values, it's hard to write a helper function and use it once to get `testing.T` for `zaptest.NewLogger`

Comment (lance6716) [reply pkg/ddl/ingest/env.go:32]: I found https://github.com/pingcap/tidb/blob/master/pkg/statistics/handle/logutil/logutil.go 

Do you think this style is good? The `SamplerLogger` can also replace our manually down-sample logging logic

https://github.com/pingcap/tidb/blob/e8c397ff93ff55da30e553b77bd1a25f6b841510/pkg/ddl/backfilling.go#L279-L280

cc @D3Hunter @zimulala

Comment (D3Hunter) [reply pkg/ddl/ingest/env.go:32]: > > leave previous value? so we can see logs in test
> 
> In fact I think printing all message of passed unit test is useless, makes me hard to locate the log of failed tests. I'll try to initialize these logger to https://pkg.go.dev/go.uber.org/zap/zaptest#NewLogger

if the test is flaky, it might help, especially for cases that only trigger on some timeline, such as DXF

Comment (lance6716) [reply pkg/ddl/ingest/env.go:32]: `zaptest.NewLogger` will print the content when test failed, or use `go test -v`.

**Review by Benjamin2037 — APPROVED** [review]
LGTM
