### PR TITLE
planner: Skyline pruning to include equals within DNF

### LINKED ISSUE #62955: Optimizer will choose index scan for IN, but tablescan for OR
## Bug Report

The optimizer will choose a tablefullscan rather than indexscan when a query is coded as "col = ? OR col = ?", when the equivalent query written as an IN predicate (col IN (?, ?) will choose an indexscan.

Additional details include:
- table has no statistics (pseudo stats).
- "OR" condition has all conditions as consecutive (such as col = 1 OR col = 2), alternatively there are non-consecutive OR equal predicates, and the total exceeds 20 predicates.

### 1. Minimal reproduce step (Required)

CREATE TABLE `t1` (
  `a` int,
  `b` int,
  `c` int,
  KEY `ia` (`a`)
);

NOTE: There are no statistics on the table (pseudo stats), and no data inserted. This is to ensure that the optimizer's estimates use pseudo stats.

You may need to disable auto-analyze:
```
tidb> set @@global.tidb_enable_auto_analyze=OFF;
Query OK, 0 rows affected (0.01 sec)
```

### 2. What did you expect to see? (Required)

For 2 values - index scan:
```
tidb> explain select * from t7 where a in (1,2);
+-------------------------------+---------+-----------+-----------------------+----------------------------------------------------+
| id                            | estRows | task      | access object         | operator info                                      |
+-------------------------------+---------+-----------+-----------------------+----------------------------------------------------+
| IndexLookUp_8                 | 20.00   | root      |                       |                                                    |
| ├─IndexRangeScan_6(Build)     | 20.00   | cop[tikv] | table:t7, index:ia(a) | range:[1,1], [2,2], keep order:false, stats:pseudo |
| └─TableRowIDScan_7(Probe)     | 20.00   | cop[tikv] | table:t7              | keep order:false, stats:pseudo                     |
+-------------------------------+---------+-----------+-----------------------+----------------------------------------------------+
```

For 20 values - index scan:
```
tidb> explain select * from t1 where a in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20);
+-------------------------------+---------+-----------+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows | task      | access object         | operator info                                                                                                                                                                                          |
+-------------------------------+---------+-----------+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_8                 | 200.00  | root      |                       |                                                                                                                                                                                                        |
| ├─IndexRangeScan_6(Build)     | 200.00  | cop[tikv] | table:t1, index:ia(a) | range:[1,1], [2,2], [3,3], [4,4], [5,5], [6,6], [7,7], [8,8], [9,9], [10,10], [11,11], [12,12], [13,13], [14,14], [15,15], [16,16], [17,17], [18,18], [19,19], [20,20], keep order:false, stats:pseudo |
| └─TableRowIDScan_7(Probe)     | 200.00  | cop[tikv] | table:t1              | keep order:false, stats:pseudo                                                                                                                                                                         |
+-------------------------------+---------+-----------+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

For "OR" predicates, I expected to see the same result as IN (above). This is true if the "OR" values are NOT consecutive (use "a = 1 or a = 3" for first example here) UNTIL we reach 20 values.

Here is 2 consecutive values as OR - chose tablefullscan rather than index scan:
```
tidb> explain select * from t7 where a = 1 or a = 2;
+-------------------------+----------+-----------+---------------+----------------------------------------+
| id                      | estRows  | task      | access object | operator info                          |
+-------------------------+----------+-----------+---------------+----------------------------------------+
| TableReader_8           | 250.00   | root      |               | data:Selection_7                       |
| └─Selection_7           | 250.00   | cop[tikv] |               | or(eq(test.t7.a, 1), eq(test.t7.a, 2)) |
|   └─TableFullScan_6     | 10000.00 | cop[tikv] | table:t7      | keep order:false, stats:pseudo         |
+-------------------------+----------+-----------+---------------+----------------------------------------+
```
Here are 20 non-consecutive values as OR - chose tablefullscan rather than index scan:
```
tidb> explain select * from t1 where a = 1 or a = 3 or a = 5 or a = 7 or a = 9 or a = 11 or a = 13 or a = 15 or a = 17 or a = 19 or a = 21 or a = 23 or a = 25 or a = 27 or a = 29 or a = 31 or a = 33 or a = 35 or a = 37 or a = 39;
+-------------------------+----------+-----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                      | estRows  | task      | access object | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------------------+----------+-----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TableReader_8           | 200.00   | root      |               | data:Selection_7                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| └─Selection_7           | 200.00   | cop[tikv] |               | or(or(or(or(eq(test.t1.a, 1), eq(test.t1.a, 3)), or(eq(test.t1.a, 5), or(eq(test.t1.a, 7), eq(test.t1.a, 9)))), or(or(eq(test.t1.a, 11), eq(test.t1.a, 13)), or(eq(test.t1.a, 15), or(eq(test.t1.a, 17), eq(test.t1.a, 19))))), or(or(or(eq(test.t1.a, 21), eq(test.t1.a, 23)), or(eq(test.t1.a, 25), or(eq(test.t1.a, 27), eq(test.t1.a, 29)))), or(or(eq(test.t1.a, 31), eq(test.t1.a, 33)), or(eq(test.t1.a, 35), or(eq(test.t1.a, 37), eq(test.t1.a, 39)))))) |
|   └─TableFullScan_6     | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------------------------+----------+-----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set (2.07 sec)
```

### 4. What is your TiDB version? (Required)

Master branch (9.0)

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #62955 

Problem Summary:

### What changed and how does it work?

Enhance skyline pruning to treat "DNF conditions that ONLY contain equal predicates" the same as IN predicates. That means, "COL = 1 OR COL = 3 OR COL = 5" is treated the same as "COL IN (1, 3, 5)".

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/find_best_task.go [hunk 1]
```diff
@@ -1619,6 +1620,31 @@ func skylinePruning(ds *logicalop.DataSource, prop *property.PhysicalProperty) [
 	return candidates
 }
 
+// hasOnlyEqualPredicatesInDNF checks if all access conditions in DNF form are equal predicates
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/find_best_task.go:1631]: Will correct comment using a simplified version in next commit.

File: pkg/planner/core/find_best_task.go [hunk 2]
```diff
@@ -1627,6 +1628,60 @@ func skylinePruning(ds *logicalop.DataSource, prop *property.PhysicalProperty) [
...
+func (c *candidatePath) hasOnlyEqualPredicatesInDNF() bool {
+	// Exit if this isn't a DNF condition or has no access conditions
+	if !c.path.IsDNFCond || len(c.path.AccessConds) == 0 {
+		return false
+	}
+	// If the minimum number of access conditions required for DNF is more than 1, then each OR condition
+	// must have at least 1 equal predicates to satisfy the DNF requirement. Return true.
+	if c.path.MinAccessCondsForDNFCond > 1 {
```
Comment (Tristan1900) [inline pkg/planner/core/find_best_task.go:1639]: this shortcut might not be expected since I tweaked your test and get the following

```
result = tk.MustQuery("explain format='brief' select * from t where (a > 1 and b > 0) or (a > 2 and b < 5)")
require.Contains(t, result.Rows()[0][0], "IndexLookUp")
```
```
2025/08/14 15:01:45 IndexLookUp 2666.67 root  
├─Selection(Build) 2666.67 cop[tikv]  or(and(gt(test.t.a, 1), gt(test.t.b, 0)), and(gt(test.t.a, 2), lt(test.t.b, 5)))
│ └─IndexRangeScan 3333.33 cop[tikv] table:t, index:idx_a_b(a, b) range:(1,+inf], keep order:false, stats:pseudo
└─TableRowIDScan(Probe) 2666.67 cop[tikv] table:t keep order:false, stats:pseudo
```

File: pkg/planner/core/casetest/plan_test.go [hunk 3]
```diff
@@ -107,6 +107,50 @@ func TestPreferRangeScan(t *testing.T) {
...
+	result = tk.MustQuery("explain format='brief' select * from t where (a = 1 and b > 0) or (a = 2 and b < 5)")
+	require.Contains(t, result.Rows()[0][0], "IndexLookUp")
+
+	// DNF with NOT operators - should not prefer IndexLookUp
+	// This should fall back to TableReader since NOT operators don't qualify
+	result = tk.MustQuery("explain format='brief' select * from t where (a = 1 and b = 1) or not (a = 2 and b = 2)")
+	require.Contains(t, result.Rows()[0][0], "TableReader")
+
+	// DNF with mixed predicates - should not prefer IndexLookUp
+	// This should fall back to TableReader since it contains non-equal predicates
```
Comment (Tristan1900) [inline pkg/planner/core/casetest/plan_test.go:138]: nit: I tried to make a = 6 but keep a >= 2 and it results in indexLookUp, looks like containing non-equal predicates does not necessarily result in TableReader

Comment (terry1purcell) [reply pkg/planner/core/casetest/plan_test.go:138]: I ran the following query through debugger:
explain format='brief' select * from t where (a >= 2 and b <= 3) or (a = 6 and b < 6);
I confirmed that the code does return "false" for isDNFOnlyEquals. So this query is still choosing index scan based upon cost, and not because of this new code.
If you change the query to remove the predicates on b, the code also returns false - but the plan chose TableReader/TableFullScan.
explain format='brief' select * from t where (a >= 2) or (a = 6);

File: pkg/planner/core/find_best_task.go [hunk 4]
```diff
@@ -1609,7 +1609,8 @@ func skylinePruning(ds *logicalop.DataSource, prop *property.PhysicalProperty) [
 			if !c.path.IsFullScanRange(ds.TableInfo) {
 				// Preference plans with equals/IN predicates or where there is more filtering in the index than against the table
 				indexFilters := c.path.EqOrInCondCount > 0 || len(c.path.TableFilters) < len(c.path.IndexFilters)
-				if preferMerge || (indexFilters && (prop.IsSortItemEmpty() || c.isMatchProp)) {
+				isDNFOnlyEquals := ds.TableInfo.GetPartitionInfo() == nil && c.hasOnlyEqualPredicatesInDNF()
```
Comment (mjonss) [inline pkg/planner/core/find_best_task.go]: Just curious, why only non-partitioned tables?

Comment (terry1purcell) [reply pkg/planner/core/find_best_task.go]: Initially it was to reduce scope - including the assumption that partitioned tables should have statistics. Since this code is most likely to be triggered only for pseudo stats objects. But it is inconsistent with the other checks that don't have such a limitation. I will retest without this restriction.

Comment (terry1purcell) [reply pkg/planner/core/find_best_task.go]: In the latest commit - this restriction is removed.
