### PR TITLE
autoid_service,owner: change autoid service's etcd lease to 10s

### LINKED ISSUE #46454: When autoid service panic unexpected, the recovering time is a bit too long
## Enhancement

When autoid service leader panic, the follower need to wait the lease timeout to take over the leader's role.
The lease is 60s, which is a bit too long...

For DDL service, it's also 60s, and it's the default value https://pkg.go.dev/go.etcd.io/etcd/clientv3/concurrency#WithTTL
DDL is offline service, so 60s is tolerable.
But autoid allocating is online service, the custome may not expect it take so long to recover.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #46454

Problem Summary:

### What is changed and how it works?

Change the lease value from 60s to 10s
When autoid service panic unexpectedly, it wait lease timeout to elect a new leader to recover the service.
60s is a bit too long.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]

File: autoid_service/autoid.go [hunk 1]
```diff
@@ -280,7 +280,7 @@ func New(selfAddr string, etcdAddr []string, store kv.Storage, tlsConfig *tls.Co
 
 func newWithCli(selfAddr string, cli *clientv3.Client, store kv.Storage) *Service {
 	l := owner.NewOwnerManager(context.Background(), cli, "autoid", selfAddr, autoIDLeaderPath)
-	err := l.CampaignOwner()
+	err := l.CampaignOwner(10)
```
Comment (hawkingrei) [inline autoid_service/autoid.go:283]: We can add some commnet here. ```10``` means that autoid service's etcd lease is 10s.

Comment (tiancaiamao) [reply autoid_service/autoid.go:283]: Done @hawkingrei

**Review by hawkingrei — APPROVED** [review]

**Comment by dulao5** [comment]
I devised a test method for this scenario, which proved to be as expected.

## Expected effect
- When the autoid owner job crashes, the recovery time of OLTP (insert) is optimized from around 60s to 10s
- DDL owner job crash, DDL recovery time is not affected (60s or so)

## Verification method
- Modify sysbench, use AUTO_CACHE_ID = 1 option when creating tables
- Verify OLTP (insert) scenarios with sysbench oltp_insert
- Use the shell to send one ddl statement per second to verify the ddl job scenario
- Use v7.1.1 and nightly(7.4-nightly) respectively, start multiple tidb processes with tiup playground,  use `kill -9` to kill the tidb process where the owner job is located to confirm the recovery time.

## Verification results
✅ as expected

  | v7.1.1 (current status) | v7.4-alpha-nightly | results
-- | -- | -- | --
OLTP (insert) recovery time | 82s | 85s | ✅ unchanged
DDL recovery time | 52s | 10s | ✅ been sped up

## Details

* OLTP (insert) recovery time -- before


* OLTP (insert) recovery time -- after




* DDL recovery time -- before


* DDL recovery time -- after
