### PR TITLE
ddl: move file management into litBackendCtxMgr 

### LINKED ISSUE #52639: wrong order of checking fast DDL available and cleanup
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/6660de735649946b1d39a4a433cdda817d51de25/pkg/ddl/index.go#L792-L798

if the free space is less than 10% we will always fail on CheckAvailable, no chance to run cleanupSortPath

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #52639

Problem Summary:

### What changed and how does it work?

as title, litBackendCtxMgr should have more functionality.

This is a prepare PR to allow parallel ingest reorg in release-8.1

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ingest/backend_mgr.go [hunk 1]
```diff
@@ -106,31 +133,106 @@ func (m *litBackendCtxMgr) Register(
 	if !ok {
 		return nil, genBackendAllocMemFailedErr(ctx, m.memRoot, jobID)
 	}
-	cfg, err := genConfig(ctx, m.memRoot, jobID, unique, resourceGroupName)
+	cfg, err := genConfig(ctx, m.encodeJobSortPath(jobID), m.memRoot, unique, resourceGroupName)
```
Comment (D3Hunter) [inline pkg/ddl/ingest/backend_mgr.go:136]: i suggest one day we remove dependency on lightning.Config, and depends on local.BackendConfig directly

Comment (lance6716) [reply pkg/ddl/ingest/backend_mgr.go:136]: `litBackendCtx` still uses `*lightning.Config`, I'll leave it for future PR

**Review by tangenta — APPROVED** [review]
