### PR TITLE
expression: refine invalid char error msg for string conversion

### LINKED ISSUE #56706: Error message: Unexpected line break
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `PK_MULTI_COL_4820` (
  `COL1` binary(10) NOT NULL,
  `COL2` char(1) NOT NULL,
  `COL3` mediumint(45) NOT NULL,
  PRIMARY KEY (`COL1`(5),`COL2`,`COL3`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `UIDXM` (`COL1`(5),`COL2`),
  UNIQUE KEY `UIDX` (`COL2`),
  KEY `IDX3` (`COL3`),
  KEY `IDXM` (`COL3`,`COL2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
select max(col1), min(col1), count(col1), max(col2), min(col2), count(col2), count(1), count(*) from PK_MULTI_COL_4820 where col2 in (0xFF1C320A347AACB924E9, 0xFF1C320A347AACB924E9, 0xFF1C320A347AACB924E9) group by col1, col2;
```

### 2. What did you expect to see? (Required)
Error messages are displayed on one line
This is `mysql` return:
`ERROR 3854 (HY000): Cannot convert string '\xFF\x1C2\x0A4z...' from binary to utf8mb4`

### 3. What did you see instead (Required)
It looks like TiDB interprets a character as a line break
```
mysql> select max(col1), min(col1), count(col1), max(col2), min(col2), count(col2), count(1), count(*) from PK_MULTI_COL_4820 where col2 in (0xFF1C320A347AACB924E9, 0xFF1C320A347AACB924E9, 0xFF1C320A347AACB924E9) group by col1, col2;
ERROR 3854 (HY000): Cannot convert string '\xFF2
4z...' from binary to utf8mb4
```

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: 1832b2728d7ae494684bdeb32b4af0a5a927bf89
Git Branch: HEAD
UTC Build Time: 2024-10-15 03:47:37
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #56706

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/builtin_convert_charset.go [hunk 1]
```diff
@@ -382,8 +382,10 @@ func formatInvalidChars(src []byte) string {
 			sb.WriteString("...")
 			break
 		}
-		if src[i] > unicode.MaxASCII {
-			sb.WriteString(fmt.Sprintf("\\x%X", src[i]))
+		if src[i] > unicode.MaxASCII || src[i] < ' ' {
```
Comment (Defined2014) [inline pkg/expression/builtin_convert_charset.go:385]: Let it same as MySQL

**Review by zimulala — APPROVED** [review]
LGTM

**Review by tangenta — APPROVED** [review]
