### PR TITLE
executor,ddl: update auto_random_base in 'show create table' after insertion

### LINKED ISSUE #17456: update auto_random_base in 'show create table' after insertion
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (a bigint primary key auto_random(5), b int unique key auto_increment) auto_random_base = 100, auto_increment = 100;
insert into t values (1000);
show create table t;
```

### 2. What did you expect to see? (Required)

The `AUTO_RANDOM_BASE` part should be updated to a larger value:
```
+-------+--------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                         |
+-------+--------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (                                                                                                                   |
|       |   `a` bigint(20) NOT NULL /*T![auto_rand] AUTO_RANDOM(5) */,                                                                         |
|       |   `b` int(11) NOT NULL AUTO_INCREMENT,                                                                                               |
|       |   PRIMARY KEY (`a`),                                                                                                                 |
|       |   UNIQUE KEY `b` (`b`)                                                                                                               |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin  AUTO_INCREMENT=2000100 /*T![auto_rand_base] AUTO_RANDOM_BASE=2000100 */ |
+-------+--------------------------------------------------------------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

`AUTO_RANDOM_BASE` is still 100.

```
+-------+---------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                    |
+-------+---------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (                                                                                                              |
|       |   `a` bigint(20) NOT NULL /*T![auto_rand] AUTO_RANDOM(5) */,                                                                    |
|       |   `b` int(11) NOT NULL AUTO_INCREMENT,                                                                                          |
|       |   PRIMARY KEY (`a`),                                                                                                            |
|       |   UNIQUE KEY `b` (`b`)                                                                                                          |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2000100 /*T![auto_rand_base] AUTO_RANDOM_BASE=100 */ |
+-------+---------------------------------------------------------------------------------------------------------------------------------+
```

### 4. Affected version (Required)

master, v4.0.0, v3.1.0

### 5. Root Cause Analysis

When `show create table` is executed, `AUTO_RANDOM_BASE` part should be filled with the value pull from meta key, instead of `TableInfo.AutoRandID`.

### PR DESCRIPTION
**Pull request by Rustin-Liu**
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

### What problem does this PR solve?

Issue Number: close #17456。

Problem Summary:

### What is changed and how it works?

What's Changed:

Use Allocator.NextGlobalAutoID() as auto_random_base.

How it Works:

Use Allocator.NextGlobalAutoID() as auto_random_base.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

None

### Release note 
- update auto_random_base in 'show create table' after insertion

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
@ti-srebot /run-all-tests

File: executor/show_test.go [hunk 1]
```diff
@@ -808,6 +808,35 @@ func (s *testAutoRandomSuite) TestAutoIdCache(c *C) {
 	))
 }
 
+func (s *testAutoRandomSuite) TestAutoRandomBase(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
```
Comment (tangenta) [inline executor/show_test.go:812]: To keep it stable, it is better to initialize the test (like other tests in `testAutoRandomSuite`):
```go
testutil.ConfigTestUtils.SetupAutoRandomTestConfig()
defer testutil.ConfigTestUtils.RestoreAutoRandomTestConfig()
```

(If you would like to help improve, these patterns can be put into `SetupTest()` and `TeardownTest()`.

Comment (Rustin-Liu) [reply executor/show_test.go:812]: Added. Maybe I can send another PR to improve it.

File: executor/show_test.go [hunk 2]
```diff
@@ -808,6 +808,38 @@ func (s *testAutoRandomSuite) TestAutoIdCache(c *C) {
...
+
+	tk.MustExec("insert into t(`a`) values (1000)")
+	tk.MustQuery("show create table t").Check(testutil.RowsWithSep("|",
+		""+
+			"t CREATE TABLE `t` (\n"+
+			"  `a` bigint(20) NOT NULL /*T![auto_rand] AUTO_RANDOM(5) */,\n"+
+			"  `b` int(11) NOT NULL AUTO_INCREMENT,\n"+
+			"  PRIMARY KEY (`a`),\n"+
+			"  UNIQUE KEY `b` (`b`)\n"+
+			") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2000100 /*T![auto_rand_base] AUTO_RANDOM_BASE=6001 */",
```
Comment (AilinKid) [inline executor/show_test.go:839]: autoid step is a dynamic value between [30000, 2000000], you better use `mockAutoIDChange` to use the fixed autoid step.

Comment (tangenta) [reply executor/show_test.go:839]: @AilinKid Does "Dynamic" mean that the step is calculated by the allocation speed? Why can it pass the test every time?

Comment (Rustin-Liu) [reply executor/show_test.go:839]: @AilinKid  I also have this question.

File: executor/show_test.go (hunk 1 above)
Comment (Rustin-Liu) [reply executor/show_test.go:811]: Refactored.

File: executor/show_test.go (hunk 2 above)
Comment (Rustin-Liu) [reply executor/show_test.go]: Fail point added.

**Comment by Rustin-Liu** [comment]
@ti-srebot /run-all-tests

**Comment by Rustin-Liu** [comment]
@ti-srebot /run-all-tests

**Comment by Rustin-Liu** [comment]
@tangenta @AilinKid I don't know why the CI is broken and it seems that I can't get the details of the failed test. Could you please take a look?

**Comment by tangenta** [comment]
/run-unit-test
It is an irrelevant data race problem.

<details><summary>Data Race Log</summary>

```
[2020-06-30T06:18:14.920Z] ==================

[2020-06-30T06:18:14.920Z] WARNING: DATA RACE

[2020-06-30T06:18:14.920Z] Write at 0x00c0536087c0 by goroutine 830:

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/statistics.(*QueryFeedback).Update()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/feedback.go:189 +0x6f4

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/distsql.(*selectResult).fetchResp()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/select_result.go:137 +0x3a0

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/distsql.(*selectResult).Next()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/select_result.go:153 +0x2b3

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*tableResultHandler).nextChunk()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:286 +0xaa

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*TableReaderExecutor).Next()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:166 +0x21e

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).fetchBuildSideRows()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:261 +0x23c

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable.func1()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:679 +0x65

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/util.WithRecovery()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:95 +0x68

[2020-06-30T06:18:14.920Z] 

[2020-06-30T06:18:14.920Z] Previous read at 0x00c0536087c0 by goroutine 528:

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/statistics/handle.(*SessionStatsCollector).StoreQueryFeedback()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/update.go:180 +0x84

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/session.(*session).StoreQueryFeedback()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:347 +0x495

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*TableReaderExecutor).Close()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:189 +0x114

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:171 +0xad

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).Close()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:148 +0x4a7

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*DeleteExec).Close()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/delete.go:223 +0x78

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor.func1()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:506 +0x3e

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:512 +0x3b9

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4708 +0xdd2

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.920Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.920Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4700 +0xbb5

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*SortExec).Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/sort.go:129 +0xa6f

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.insertRowsFromSelect()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/insert_common.go:412 +0xa77

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ReplaceExec).Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/replace.go:216 +0xac

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4692 +0xa06

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*SortExec).Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/sort.go:129 +0xa6f

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.insertRowsFromSelect()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/insert_common.go:412 +0xa77

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*InsertExec).Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/insert.go:265 +0xac

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4690 +0x8fc

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4685 +0x74d

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4683 +0x643

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4681 +0x5d5

[2020-06-30T06:18:14.921Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.921Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4680 +0x59e

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4679 +0x567

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4662 +0x184

[2020-06-30T06:18:14.922Z]   runtime.call32()

[2020-06-30T06:18:14.922Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-06-30T06:18:14.922Z]   reflect.Value.Call()

[2020-06-30T06:18:14.922Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-06-30T06:18:14.922Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-06-30T06:18:14.922Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-06-30T06:18:14.922Z] 

[2020-06-30T06:18:14.922Z] Goroutine 830 (running) created at:

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:678 +0x221

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).Next.func1()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:644 +0x53

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/util.WithRecovery()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:95 +0x68

[2020-06-30T06:18:14.922Z] 

[2020-06-30T06:18:14.922Z] Goroutine 528 (running) created at:

[2020-06-30T06:18:14.922Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-06-30T06:18:14.922Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-06-30T06:18:14.922Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-06-30T06:18:14.922Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7

[2020-06-30T06:18:14.922Z] ==================

[2020-06-30T06:18:14.922Z] ==================

[2020-06-30T06:18:14.922Z] WARNING: DATA RACE

[2020-06-30T06:18:14.922Z] Write at 0x00c081701908 by goroutine 528:

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.ResetContextOfStmt()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1653 +0xe1d

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1138 +0x1f1

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:206 +0x91

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4710 +0xe09

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4700 +0xbb5

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*SortExec).Next()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/sort.go:129 +0xa6f

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.insertRowsFromSelect()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/insert_common.go:412 +0xa77

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*ReplaceExec).Next()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/replace.go:216 +0xac

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4692 +0xa06

[2020-06-30T06:18:14.922Z]   github.com/pingcap/tidb/executor.(*SortExec).Next()

[2020-06-30T06:18:14.922Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/sort.go:129 +0xa6f

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.insertRowsFromSelect()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/insert_common.go:412 +0xa77

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*InsertExec).Next()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/insert.go:265 +0xac

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4690 +0x8fc

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4685 +0x74d

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:510 +0x38e

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:392 +0x1a2

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:360 +0x3f6

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/session.runStmt()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1201 +0x2c1

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/session.(*session).ExecuteStmt()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1166 +0xa6f

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:160 +0x2ee

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4683 +0x643

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4681 +0x5d5

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4680 +0x59e

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4679 +0x567

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor_test.(*testSuite).TestOOMPanicAction()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor_test.go:4662 +0x184

[2020-06-30T06:18:14.923Z]   runtime.call32()

[2020-06-30T06:18:14.923Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-06-30T06:18:14.923Z]   reflect.Value.Call()

[2020-06-30T06:18:14.923Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-06-30T06:18:14.923Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-06-30T06:18:14.923Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-06-30T06:18:14.923Z] 

[2020-06-30T06:18:14.923Z] Previous read at 0x00c081701908 by goroutine 830:

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/distsql.(*selectResult).fetchResp()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/select_result.go:131 +0x849

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/distsql.(*selectResult).Next()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/select_result.go:153 +0x2b3

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*tableResultHandler).nextChunk()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:286 +0xaa

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*TableReaderExecutor).Next()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/table_reader.go:166 +0x21e

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.Next()

[2020-06-30T06:18:14.923Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:267 +0x167

[2020-06-30T06:18:14.923Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).fetchBuildSideRows()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:261 +0x23c

[2020-06-30T06:18:14.924Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable.func1()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:679 +0x65

[2020-06-30T06:18:14.924Z]   github.com/pingcap/tidb/util.WithRecovery()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:95 +0x68

[2020-06-30T06:18:14.924Z] 

[2020-06-30T06:18:14.924Z] Goroutine 528 (running) created at:

[2020-06-30T06:18:14.924Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-06-30T06:18:14.924Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-06-30T06:18:14.924Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-06-30T06:18:14.924Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7

[2020-06-30T06:18:14.924Z] 

[2020-06-30T06:18:14.924Z] Goroutine 830 (running) created at:

[2020-06-30T06:18:14.924Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndBuildHashTable()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:678 +0x221

[2020-06-30T06:18:14.924Z]   github.com/pingcap/tidb/executor.(*HashJoinExec).Next.func1()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/join.go:644 +0x53

[2020-06-30T06:18:14.924Z]   github.com/pingcap/tidb/util.WithRecovery()

[2020-06-30T06:18:14.924Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:95 +0x68

[2020-06-30T06:18:14.924Z] ==================
```

</details>

**Comment by AilinKid** [comment]
> /run-unit-test
> It is an irrelevant data race problem.
> 
> Data Race Log

seems no problem with this PR

**Comment by Rustin-Liu** [comment]
@ti-srebot /run-all-tests

**Comment by AilinKid** [comment]
@Rustin-Liu you can write directly to the cherry-pick pr to resolving the confilcts, which will do our a favor

**Comment by Rustin-Liu** [comment]
@AilinKid  I will resolve it tonight.
