### PR TITLE
expression: fix wrong result of greatest/least(mixed unsigned/signed int)

### LINKED ISSUE #30101: Wrong result for greatest when args are unsigned bigint
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table t1;
    create table t1(c1 bigint unsigned, c2 bigint unsigned);
    insert into t1 values(9223372036854775808, 9223372036854775809);
    select greatest(c1, c2) from t1;

### 2. What did you expect to see? (Required)

    mysql> select greatest(c1, c2) from t2;
    +---------------------+
    | greatest(c1, c2)    |
    +---------------------+
    | 9223372036854775808 |
    +---------------------+
    1 row in set (0.01 sec)
### 3. What did you see instead (Required)

    mysql> select greatest(c1, c2) from t1;
    +----------------------+
    | greatest(c1, c2)     |
    +----------------------+
    | -9223372036854775807 |
    +----------------------+
    1 row in set (0.01 sec)
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #30101

Problem Summary:

unsigned flag lost when building function.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix wrong result of greatest/least Function.
```

### CODE REVIEW

File: expression/builtin_compare.go [hunk 1]
```diff
@@ -745,6 +752,14 @@ func (c *leastFunctionClass) getFunction(ctx sessionctx.Context, args []Expressi
 	}
 	switch tp {
 	case types.ETInt:
+		// default unsigned, if one field is signed, return signed result
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:755]: Can we extract a common function for greatest/least? There are too many duplicated codes

Comment (sylzd) [reply expression/builtin_compare.go:755]: I can try, but I am not sure if it is better, the reason is:

1. greatest/least are two fixed features, little possibility to extend the similar function
2. in this issue: greatest/least shows the different logic
3. every function has an independent class, it little weird to merge two functions into one

btw, if we really should do it, I can do this in the next pr, since the issue is a bug fix?

File: expression/builtin_compare.go [hunk 2]
```diff
@@ -478,6 +478,14 @@ func (c *greatestFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 	}
 	switch tp {
 	case types.ETInt:
+		// adjust unsigned flag
+		greastInitUnsignedFlag := false
+		if isEqualsInitUnsigned(greastInitUnsignedFlag, args) {
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:483]:
```suggestion
		if isEqualsInitUnsignedFlag(greastInitUnsignedFlag, args) {
```

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
@sylzd Please add a release for this commit

**Review by guo-shaoge — APPROVED** [review]
