### PR TITLE
table-filter: optimize table pattern message and unit tests

### LINKED ISSUE #36163: optimize error message when table pattern is wrong in table-filter to make it more clearly
## Enhancement
optimize error message when table pattern is wrong in table-filter to make it more clear and fix unit tests.

### PR DESCRIPTION
**Pull request by niubell**
### What problem does this PR solve?

Issue Number: close #36163 

Problem Summary:

### Check List

Tests 

- [ ] Unit test

Side effects

Documentation

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: util/table-filter/parser.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ func (p *tableRulesParser) parse(line string, canImport bool) error {
 		return err
 	}
 	if len(line) == 0 {
-		return p.errorf("missing table pattern")
+		return p.errorf("wrong table pattern")
```
Comment (buchuitoudegou) [inline util/table-filter/parser.go:61]: Currently, the dataflow-service uses `missing table pattern` as key words to identify the pattern error. Maybe we should note it in case the DFS's unexpected malfunctioning.

**Review by buchuitoudegou — APPROVED** [review]
rest lgtm

**Review by D3Hunter — APPROVED** [review]
