### PR TITLE
br: fix version compatibility

### LINKED ISSUE #62707: fix br version compatibility
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
9.0 br run on the 7.5 cluster

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
fail
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #62707

Problem Summary:
br 9.x is not compatible with cluster 7.x
### What changed and how does it work?
update version checker and check the table `mysql.tidb_restore_registry`.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/registry/registration.go [hunk 1]
```diff
@@ -214,10 +218,19 @@ func NewRestoreRegistry(g glue.Glue, dom *domain.Domain) (*Registry, error) {
 	if err != nil {
 		return nil, errors.Trace(err)
 	}
+	tableExists := true
+	_, err = dom.InfoSchema().TableByName(ctx, ast.NewCIStr(RestoreRegistryDBName), ast.NewCIStr(RestoreRegistryTableName))
+	if err != nil {
+		if !infoschema.ErrTableNotExists.Equal(err) {
```
Comment (Tristan1900) [inline br/pkg/registry/registration.go:224]: should we use err.Is() which is is standard errors package, it can auto unwrap if this error is wrapped with other error

**Review by Tristan1900 — APPROVED** [review]

File: br/pkg/registry/registration.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/registry/registration.go:224]: `infoschema.ErrTableNotExists.Equal` is widely used to handle the error from the interface `TableByName` in TiDB repository. Maybe it is enough to only use `Equal`.

**Review by 3pointer — APPROVED** [review]
