### PR TITLE
lightning: fix for only route schema case

### LINKED ISSUE #33381: Lightning: import to wrong db name with some route rules
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

test file and config to reproduce this is here :[test-lighning-route.zip](https://github.com/pingcap/tidb/files/8338860/test-lighning-route.zip)

dumped data from dumping

```bash
├── dumped_data
│   ├── metadata
│   ├── webui-schema-create.sql
│   └── webui.t1-schema.sql
├── tidb-lightning.log
└── webui.toml
```

task.toml
```toml
[lightning]
file = "tidb-lightning.log"
level = "info"

[tikv-importer]
backend = "tidb"

[mydumper]
data-source-dir = "./dumped_data"

[tidb]
host = "127.0.0.1"
password = "123456"
port = 3307
user = "root"

[[routes]]
schema-pattern = "webui"
target-schema = "webui_test"

```

### 2. What did you expect to see? (Required)

i want to route db: `webui` to `webui_test` and keep table names 

### 3. What did you see instead (Required)

lightning two db  webui and webui_test 

```bash
MySQL root@127.0.0.1:(none)> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| dm_meta            |
| mysql              |
| performance_schema |
| sys                |
| webui              |
| webui_test         |
+--------------------+
```

### 4. What is your TiDB version? (Required)

```
❯ tidb-lightning -V
Release Version: v6.1.0-alpha-38-g6d0185585-dirty
Git Commit Hash: 6d01855856aac61e0829f73ed8a47be6add45321
Git Branch: master
Go Version: go1.18
UTC Build Time: 2022-03-24 05:41:35
Race Enabled: false
```

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #33381

Problem Summary:

### What is changed and how it works?

trigger route even there is no table or view to import

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
closed 
Duplicate of https://github.com/pingcap/tidb/pull/33399

**Review by buchuitoudegou — APPROVED** [review]
lgtm

**Comment by gozssky** [comment]
There are some bugs in previous implementation.

Line 378 is not effective because dbInfo is not a pointer.

https://github.com/pingcap/tidb/blob/b37b3b1afcd44b8251fa3b9e8f7a3193b27b82a8/br/pkg/lightning/mydump/loader.go#L375-L378

tableDatas don't increase the reference count before routing.
https://github.com/pingcap/tidb/blob/b37b3b1afcd44b8251fa3b9e8f7a3193b27b82a8/br/pkg/lightning/mydump/loader.go#L413-L415

File: br/pkg/lightning/mydump/loader.go [hunk 1]
```diff
@@ -422,6 +423,10 @@ func (s *mdLoaderSetup) route() error {
 			remainingSchemas = append(remainingSchemas, info)
 		}
 	}
+	// if there are no tables in the exported data, we still need route s.dbSchemas(remainingSchemas)
+	if err := run(remainingSchemas); err != nil {
+		return errors.Trace(err)
+	}
```
Comment (gozssky) [inline br/pkg/lightning/mydump/loader.go:429]: Suppose we have db1 and two table route rules:
1. db1 -> db2
2. db2 -> db3

This may cause that db1 is recursively routed to db3 while table data is only routed once.

File: br/pkg/lightning/mydump/loader.go [hunk 2]
```diff
@@ -422,6 +423,10 @@ func (s *mdLoaderSetup) route() error {
 			remainingSchemas = append(remainingSchemas, info)
 		}
 	}
+	// if there are no tables in the exported data, we still need route s.dbSchemas(remainingSchemas)
+	if err := run(remainingSchemas); err != nil {
```
Comment (buchuitoudegou) [inline br/pkg/lightning/mydump/loader.go:427]: `knownDBNames[web].count` is larger than 0 because its count equals `1 + COUNT(table_schema_file) + COUNT(table_data_file) + COUNT(table_view_schema)`, where `1` is the database schema file.

In the situation where `COUNT(table_data_file)==0`, `knownDBNames[web].count -= COUNT(table_schema_file)` and gets `1` because the database schema file is not routed. Maybe u can try routing `dbSchemas` (just my hypothesis...)

`remainingSchemas` is the result of routing. Processing it again does lead to the problem @gozssky mentioned.

FYI: https://github.com/pingcap/tidb/blob/b2cef4e8783a06a416348cc7a85b321ae0486fda/br/pkg/lightning/mydump/loader.go#L364-L369

Comment (Ehco1996) [reply br/pkg/lightning/mydump/loader.go:427]: thanks I'll look in detail

File: br/pkg/lightning/mydump/loader.go [hunk 3]
```diff
@@ -357,64 +357,67 @@ func (s *mdLoaderSetup) route() error {
 
 	type dbInfo struct {
 		fileMeta SourceFileMeta
-		count    int
+		count    int // means file count(db/table/view schema and table data)
```
Comment (gozssky) [inline br/pkg/lightning/mydump/loader.go:360]: Is it easy to add a test for `count`?

Comment (Ehco1996) [reply br/pkg/lightning/mydump/loader.go:360]: dbInfo is a internal struct, so it is difficult to unit test this when the `MDLoader` interface is not changed, do you have any good suggestions?

Comment (gozssky) [reply br/pkg/lightning/mydump/loader.go:360]: In previous implementation, count may be negative. Can we add check for this in code?  Perhaps panic when it is negative.

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/loader.go:360]: What about adding test case for `route`? For instance, u can specify the number of `db-schema-file`, `table-schema-file`, `sql-file`, and `view-schema-file`, and the rules of routing, including setting schema only, setting both schemas and tables, etc, and finally check if the `s.dbSchemas` meets your expectation. (Lots of test cases to do😭)

Comment (Ehco1996) [reply br/pkg/lightning/mydump/loader.go:361]: add a db count check in https://github.com/pingcap/tidb/pull/33484/commits/e5a127ccf66c82f0a9ddf51ecdb541252fbf27e5

> What about adding test case for route
most case is testd in TestRouter, adding a separate test for `route` seems repetitive?

File: br/pkg/lightning/mydump/loader.go [hunk 4]
```diff
@@ -417,6 +418,13 @@ func (s *mdLoaderSetup) route() error {
 		return errors.Trace(err)
 	}
 
+	// check count in knownDBNames should always greater than 0, this will not happen if there are no bugs in the code
+	for dbName, info := range knownDBNames {
+		if info.count < 0 {
+			return common.ErrTableRoute.GenWithStack(fmt.Sprintf("dbName: %s route count less than 0", dbName))
```
Comment (gozssky) [inline br/pkg/lightning/mydump/loader.go:424]: `GenWithStack` accepts format string and arguments.

BTW,  this loop can be merged into next loop, both of them are reading the count.

Comment (gozssky) [reply br/pkg/lightning/mydump/loader.go:424]: Could you optimize the error message for user readable?

Comment (Ehco1996) [reply br/pkg/lightning/mydump/loader.go]: fixed in https://github.com/pingcap/tidb/pull/33484/commits/4c58c60b46fafffc5d20452f70189e1b8befb07d

**Review by gozssky — APPROVED** [review]

**Comment by Ehco1996** [comment]
seems buchuitoudegou not have  permission 😂 patl @D3Hunter

File: br/pkg/lightning/mydump/loader.go [hunk 5]
```diff
@@ -357,73 +357,77 @@ func (s *mdLoaderSetup) route() error {
...
+				oldInfo := knownDBNames[rawDB]
 				oldInfo.count--
-				knownDBNames[info.TableName.Schema] = oldInfo
-
-				newInfo, ok := knownDBNames[dbName]
-				newInfo.count++
+				newInfo, ok := knownDBNames[targetDB]
 				if !ok {
-					newInfo.fileMeta = oldInfo.fileMeta
+					newInfo = &dbInfo{fileMeta: oldInfo.fileMeta, count: 1}
```
Comment (D3Hunter) [inline br/pkg/lightning/mydump/loader.go:392]: if we're routing schema, count should be zero, but it seems ok.

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: br/pkg/lightning/mydump/loader.go [hunk 6]
```diff
@@ -357,73 +357,77 @@ func (s *mdLoaderSetup) route() error {
...
+		knownDBNames[info.TableName.Schema] = &dbInfo{
 			fileMeta: info.FileMeta,
 			count:    1,
 		}
 	}
 	for _, info := range s.tableSchemas {
-		dbInfo := knownDBNames[info.TableName.Schema]
-		dbInfo.count++
-		knownDBNames[info.TableName.Schema] = dbInfo
+		knownDBNames[info.TableName.Schema].count++
```
[the remark this answers is not in the document]
Comment (Ehco1996) [reply br/pkg/lightning/mydump/loader.go:371]: There is no such possibility, That is not a file structure that meets the import criteria

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
> flag provided but not defined: -check.p

ut failed with this error, see this error in my pr too

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44606/pipeline

**Comment by Ehco1996** [comment]
> 

yes seems CI is unsteable now

**Comment by purelind** [comment]
### TiDB MergeCI notify
CI Name | Result | Duration | Compare with Parent commit
------------ | ------------- | ------------- | -------------
