### PR TITLE
expression: replace equal condition by true when to constant propagation | tidb-test=pr/2625 

### LINKED ISSUE #64216: cannot simplify the predicate
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE t1 (a int PRIMARY KEY, b int);
CREATE TABLE t2 (a int PRIMARY KEY, b int);

EXPLAIN FORMAT='brief' SELECT STRAIGHT_JOIN * FROM t1 LEFT JOIN t2 ON t1.a = t2.a WHERE t1.a = t2.a OR t1.a = t2.b;
```

### 2. What did you expect to see? (Required)

In Mysql

```
+----------------------------------------------------------------------------------------------------+
| EXPLAIN                                                                                            |
+----------------------------------------------------------------------------------------------------+
| -> Nested loop inner join  (cost=0.7 rows=1) (actual time=0.172..0.172 rows=0 loops=1)             |
|     -> Table scan on t1  (cost=0.35 rows=1) (actual time=0.161..0.161 rows=0 loops=1)              |
|     -> Single-row index lookup on t2 using PRIMARY (a = t1.a)  (cost=0.35 rows=1) (never executed) |
+----------------------------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

```
EXPLAIN FORMAT='brief' SELECT STRAIGHT_JOIN * FROM t1 LEFT JOIN t2 ON t1.a = t2.a WHERE t1.a = t2.a OR t1.a = t2.b;
id	estRows	task	access object	operator info
MergeJoin	3.84	root		inner join, left key:join_outer.t1.a, right key:join_outer.t2.a, other cond:or(eq(join_outer.t1.a, join_outer.t2.a), eq(join_outer.t1.a, join_outer.t2.b))
├─TableReader(Build)	3.84	root		data:Selection
│ └─Selection	3.84	cop[tikv]		or(eq(join_outer.t2.a, join_outer.t2.a), eq(join_outer.t2.a, join_outer.t2.b))
│   └─TableFullScan	4.00	cop[tikv]	table:t2	keep order:true
└─TableReader(Probe)	9.00	root		data:TableFullScan
  └─TableFullScan	9.00	cop[tikv]	table:t1	keep order:true
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #64216 

Problem Summary:

### What changed and how does it work?

There are three scenarios here.

```
a = b and (a=b or c=d) => a=b and (a=b or c=d) and (a=a or c=d)
a = b and a in (b, c, d) => a = b and a in (b, c, d) and a in (a, c ,d)
a = b and b = c and c = d and a = d => a = b and b = c and c = d // remove a=d
```

In the previous implementation, we only passed through constant values to create a new expression. However, what we actually need is to directly replace the equivalent conditions in the expression with true, in order to avoid generating unnecessary expressions.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/constant_propagation.go [hunk 1]
```diff
@@ -348,12 +413,21 @@ func (s *propConstSolver) propagateColumnEQ() {
...
 				rID := s.getColID(rCol)
-				s.unionSet.Union(lID, rID)
 				visited[i] = true
+				if s.unionSet.FindRoot(lID) != s.unionSet.FindRoot(rID) {
+					// Add the equality relation to unionSet
+					// if it has been added, we don't need to process it again.
+					// It will be deleted in the replaceEqCondtionWithTrueitionsWithConstants
+					s.unionSet.Union(lID, rID)
+				} else if lID != rID {
+					s.conditions[i] = &Constant{
```
Comment (AilinKid) [inline pkg/expression/constant_propagation.go:424]: here means LID and RID is already in the union set(the equiv relationship is catched, so we can safely convert this EQ(LID, RID) to be a true)

what i concern here is that, next time, if we wanna do the constant prop one more time, we should build the union set from these condition slice again, while may we still be able to catch the equiv relation ship between LID and RID?

Comment (AilinKid) [reply pkg/expression/constant_propagation.go:424]: looks like we only substitute for appended condition, yes ok.

Comment (hawkingrei) [reply pkg/expression/constant_propagation.go:424]: ```Unionset```  can capture any equivalence relations of the inferred type. for example,

```
a = b, b = c, c = d, d = e 
```

We get ```a = e ``` by the ```unionset```.

Comment (hawkingrei) [reply pkg/expression/constant_propagation.go:424]: Actually, it doesn't affect the logic here, since all equivalence relations are preserved, and only the redundant equivalence relations are eliminated.
