### PR TITLE
storage: support parallel write for gcs

### LINKED ISSUE #48443: google cloud storage can't use parallel write
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
google cloud storage can't use parallel write, so the performance is poor. It's about 20~40MB/s.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #48443

Problem Summary:

### What changed and how does it work?

integrate https://github.com/liqiuqing/gcsmpu

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: br/pkg/lightning/backend/external/engine.go [hunk 1]
```diff
@@ -293,6 +294,8 @@ func (e *Engine) LoadIngestData(
 	regionRanges []common.Range,
 	outCh chan<- common.DataAndRange,
 ) error {
+	// TODO(lance6716): just try to avoid OOM 😭
```
Comment (Benjamin2037) [inline br/pkg/lightning/backend/external/engine.go:297]: Could we remove this emoj？
```suggestion
	// TODO(lance6716): just try to avoid OOM
```

Comment (lance6716) [reply br/pkg/lightning/backend/external/engine.go]: https://github.com/pingcap/tidb/pull/49545/commits/8c2a27c84f26ce9d2b82de5cf4fb88f552dcd3a7

deleted these lines, because they didn't prevent OOM

File: br/pkg/lightning/backend/external/writer.go [hunk 2]
```diff
@@ -509,9 +472,61 @@ func (w *Writer) flushKVs(ctx context.Context, fromClose bool) (err error) {
...
+		return "", "", err
+	}
+	err = dataWriter.Close(ctx)
+	if err != nil {
+		return "", "", err
+	}
+	err = statWriter.Close(ctx)
+	if err != nil {
+		return "", "", err
+	}
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/external/writer.go:515]: close them even on previous err path?

Comment (lance6716) [reply br/pkg/lightning/backend/external/writer.go:515]: OK, `close` means creating the file in object storage, but I think it's more reasonable for other backends

File: br/pkg/storage/gcs.go [hunk 3]
```diff
@@ -272,12 +273,29 @@ func (s *GCSStorage) URI() string {
...
+	mockGCS := intest.InTest && strings.Contains(s.gcs.GetEndpoint(), "127.0.0.1")
+	if wo == nil || wo.Concurrency <= 1 || mockGCS {
+		object := s.objectName(name)
+		wc := s.bucket.Object(object).NewWriter(ctx)
+		wc.StorageClass = s.gcs.StorageClass
+		wc.PredefinedACL = s.gcs.PredefinedAcl
+		return newFlushStorageWriter(wc, &emptyFlusher{}, wc), nil
+	}
+	uri := s.objectName(name)
+	// 5 MB is the minimum part size for GCS.
```
Comment (Benjamin2037) [inline br/pkg/storage/gcs.go:287]:
```suggestion
	// 5MB is the minimum part size for GCS.
```
