### PR TITLE
planner: fix query range partition table got wrong result and TiDB panic

### LINKED ISSUE #22898: query range partition table got wrong result and TiDB panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE NT_RP3763 (COL1 TINYINT(8) SIGNED COMMENT "NUMERIC NO INDEX" DEFAULT 41,COL2 VARCHAR(20),COL3 DATETIME,COL4 BIGINT,COL5 FLOAT) PARTITION BY RANGE (COL1 * COL3) (PARTITION P0 VALUES LESS THAN (0),PARTITION P1 VALUES LESS THAN (10),PARTITION P2 VALUES LESS THAN (20),PARTITION P3 VALUES LESS THAN (30),PARTITION P4 VALUES LESS THAN (40),PARTITION P5 VALUES LESS THAN (50),PARTITION PMX VALUES LESS THAN MAXVALUE);
insert into NT_RP3763 (COL1,COL2,COL3,COL4,COL5) values(-82,"夐齏醕皆磹漋甓崘潮嵙燷渏艂朼洛炷鉢儝鱈肇","5748\-06\-26\ 20:48:49",-3133527360541070260,-2.624880003397658e+38); 
insert into NT_RP3763 (COL1,COL2,COL3,COL4,COL5) values(48,"簖鹩筈匹眜赖泽騈爷詵赺玡婙Ɇ郝鮙廛賙疼舢","7228\-12\-13\ 02:59:54",-6181009269190017937,2.7731105531290494e+38); 
select * from `NT_RP3763` where `COL1` in (10, 48, -82);
select * from `NT_RP3763` where `COL1` in (48);
```

### 2. What did you expect to see? (Required)
query successfully 
```sql
mysql test> select * from `NT_RP3763` where `COL1` in (10, 48, -82);
+------+------------------------------------------+---------------------+----------------------+--------------+
| COL1 | COL2                                     | COL3                | COL4                 | COL5         |
+------+------------------------------------------+---------------------+----------------------+--------------+
| -82  | 夐齏醕皆磹漋甓崘潮嵙燷渏艂朼洛炷鉢儝鱈肇 | 5748-06-26 20:48:49 | -3133527360541070260 | -2.62488e+38 |
| 48   | 簖鹩筈匹眜赖泽騈爷詵赺玡婙Ɇ郝鮙廛賙疼舢  | 7228-12-13 02:59:54 | -6181009269190017937 |  2.77311e+38 |
+------+------------------------------------------+---------------------+----------------------+--------------+

2 rows in set
Time: 0.259s
mysql test> select * from `NT_RP3763` where `COL1` in (48);
+------+-----------------------------------------+---------------------+----------------------+-------------+
| COL1 | COL2                                    | COL3                | COL4                 | COL5        |
+------+-----------------------------------------+---------------------+----------------------+-------------+
| 48   | 簖鹩筈匹眜赖泽騈爷詵赺玡婙Ɇ郝鮙廛賙疼舢 | 7228-12-13 02:59:54 | -6181009269190017937 | 2.77311e+38 |
+------+-----------------------------------------+---------------------+----------------------+-------------+

1 row in set
Time: 0.054s
mysql test> select * from `NT_RP3763` where `COL1` in (-82);
+------+------------------------------------------+---------------------+----------------------+--------------+
| COL1 | COL2                                     | COL3                | COL4                 | COL5         |
+------+------------------------------------------+---------------------+----------------------+--------------+
| -82  | 夐齏醕皆磹漋甓崘潮嵙燷渏艂朼洛炷鉢儝鱈肇 | 5748-06-26 20:48:49 | -3133527360541070260 | -2.62488e+38 |
+------+------------------------------------------+---------------------+----------------------+--------------+

```
### 3. What did you see instead (Required)
the results is incorrect and tidb panic
```sql
mysql root@127.0.0.1:test> select * from `NT_RP3763` where `COL1` in (10, 48, -82);
+------+------------------------------------------+---------------------+----------------------+--------------+
| COL1 | COL2                                     | COL3                | COL4                 | COL5         |
+------+------------------------------------------+---------------------+----------------------+--------------+
| -82  | 夐齏醕皆磹漋甓崘潮嵙燷渏艂朼洛炷鉢儝鱈肇 | 5748-06-26 20:48:49 | -3133527360541070260 | -2.62488e+38 |
+------+------------------------------------------+---------------------+----------------------+--------------+

1 row in set
Time: 0.011s
mysql test> select * from `NT_RP3763` where `COL1` in (48);
(1105, 'runtime error: invalid memory address or nil pointer dereference')
mysql test> select * from `NT_RP3763` where `COL1` in (-82);
Reconnecting...
(1105, 'runtime error: invalid memory address or nil pointer dereference')
```
### 4. What is your TiDB version? (Required)

master d6a2b9a3 and 5.0-rc 760c7d1e

### PR DESCRIPTION
**Pull request by TszKitLo40**
Signed-off-by: alfredlu <wslzj40@gmail.com>

### What problem does this PR solve?

Issue Number: close #22898  

Problem Summary:

### What is changed and how it works?

What's Changed:
fix query range partition table got wrong result and TiDB panic
How it Works:

1. The panic reason is the same reason in [#22396](https://github.com/pingcap/tidb/issues/22396), and I fix it the same with it.

2. The funcition `makePartitionByFnCol` is expected to return only 1 args, so if there are more than 2 columns, we should not prune.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by xiongjiwei** [comment]
it will conflict with that PR 🤣. we only need one to close the two issues

**Comment by TszKitLo40** [comment]
> it will conflict with that PR 🤣. we only need one to close the two issues
Maybe we can merge that PR first, and this PR is used to fix the second problem.

File: planner/core/rule_partition_processor.go [hunk 1]
```diff
@@ -758,6 +758,9 @@ func makePartitionByFnCol(sctx sessionctx.Context, columns []*expression.Column,
 		fn = raw
 		args := fn.GetArgs()
 		if len(args) > 0 {
+			if expression.ExtractColumnSet(args).Len() > 1 {
```
Comment (tiancaiamao) [inline planner/core/rule_partition_processor.go:761]: This may be not quite true.
In `add(col, const)`,  it's still a monotonous function, but in `add(col1, col2)`, this one is not.
And the code is not quite readable because the reader (or as a reviewer, me) does not know why without knowing issue #22898 

Maybe we can move line 769 to 759 to check monotonous immediately?
```
fn = raw
monotonous = getMonotoneMode(raw.FuncName.L)
if monotonous == monotoneModeInvalid {
    return ...
}
```

**Review by tiancaiamao — COMMENTED** [review]
Sorry for the late review, I didn't realize the severity of this bug.

File: planner/core/rule_partition_processor.go (hunk 1 above)
Comment (TszKitLo40) [reply planner/core/rule_partition_processor.go]: I have moved it, PTAL.

File: cmd/explaintest/r/partition_pruning.result [hunk 2]
```diff
@@ -2391,12 +2391,12 @@ partition p2 values less than (255)
 insert into t1 select A.a + 10*B.a from t0 A, t0 B;
 explain format = 'brief' select * from t1 where a between 10 and 13;
 id	estRows	task	access object	operator info
-TableReader	250.00	root	partition:all	data:Selection
+TableReader	250.00	root	partition:p0	data:Selection
 └─Selection	250.00	cop[tikv]		ge(test.t1.a, 10), le(test.t1.a, 13)
   └─TableFullScan	10000.00	cop[tikv]	table:t1	keep order:false, stats:pseudo
 explain format = 'brief' select * from t1 where a between 10 and 10+33;
 id	estRows	task	access object	operator info
-TableReader	250.00	root	partition:all	data:Selection
```
Comment (tiancaiamao) [inline cmd/explaintest/r/partition_pruning.result:2399]: MySQL can not handle this one, but TiDB can.

File: cmd/explaintest/r/partition_pruning.result [hunk 3]
```diff
@@ -2276,7 +2276,7 @@ TableReader	250.00	root	partition:dual	data:Selection
   └─TableFullScan	10000.00	cop[tikv]	table:t1	keep order:false, stats:pseudo
 explain format = 'brief' select * from t2 where a > 0xFE AND a <= 0xFF;
 id	estRows	task	access object	operator info
-TableReader	250.00	root	partition:all	data:Selection
+TableReader	250.00	root	partition:dual	data:Selection
```
Comment (crazycs520) [inline cmd/explaintest/r/partition_pruning.result:2279]: ? It's shouldn't be `dual` here.

File: planner/core/rule_partition_processor.go [hunk 4]
```diff
@@ -742,28 +742,42 @@ func makePartitionByFnCol(sctx sessionctx.Context, columns []*expression.Column,
...
+			if arg1, ok1 := args[0].(*expression.Column); ok1 {
+				if _, ok2 := args[1].(*expression.Constant); ok2 {
+					if raw.FuncName.L == ast.Div {
+						monotonous = monotoneModeNonStrict
+					} else {
+						monotonous = monotoneModeStrict
+					}
+					return arg1, raw, monotonous, nil
+				}
+			}
```
Comment (crazycs520) [inline planner/core/rule_partition_processor.go:769]: Why add those codes?  And there is no test for it?

File: cmd/explaintest/r/partition_pruning.result (hunk 3 above)
Comment (tiancaiamao) [reply cmd/explaintest/r/partition_pruning.result:2279]: This is the same with MySQL's behavior:

```
create table t2 (a int)	create table t2 (a int)
partition by range(a+0) (	partition by range(a+0) (
partition p0 values less than (64),	partition p0 values less than (64),
partition p1 values less than (128),	partition p1 values less than (128),
partition p2 values less than (255)	partition p2 values less than (255)
);
```

partition by (a + 0),  a > 0xFE AND a <= 0xFF, the only possible value is 0xFF(255), there is no partition for it, so the result is `dual`

File: planner/core/rule_partition_processor.go (hunk 4 above)
Comment (tiancaiamao) [reply planner/core/rule_partition_processor.go:769]: There are already test codes that cover the case.

In the beginning, this PR means to fix `partition by range (col1 + col2)`, but if we simply disable `col1 + col2` we will also disable `partition by range (col + const)`.

In the test code, some cases use `partition by range (a + 0)`, so this change is used to make those cases happy.

`col1 + col2`:  fail to do partition pruning
`col + const`:  can be pruned.

Comment (crazycs520) [reply planner/core/rule_partition_processor.go:769]: How about:
```go
diff --git a/planner/core/rule_partition_processor.go b/planner/core/rule_partition_processor.go
index 107d2f29f..b80969eee 100644
--- a/planner/core/rule_partition_processor.go
+++ b/planner/core/rule_partition_processor.go
@@ -755,18 +755,6 @@ func makePartitionByFnCol(sctx sessionctx.Context, columns []*expression.Column,
                                        }
                                }
                        }
-               case ast.Plus, ast.Minus, ast.Mul, ast.Div:
-                       // partition by (col op const) where op in [+ - * /]
-                       if arg1, ok1 := args[0].(*expression.Column); ok1 {
-                               if _, ok2 := args[1].(*expression.Constant); ok2 {
-                                       if raw.FuncName.L == ast.Div {
-                                               monotonous = monotoneModeNonStrict
-                                       } else {
-                                               monotonous = monotoneModeStrict
-                                       }
-                                       return arg1, raw, monotonous, nil
-                               }
-                       }
                default:
                        fn = raw
                        monotonous = getMonotoneMode(raw.FuncName.L)
@@ -915,6 +903,10 @@ var monotoneIncFuncs = map[string]monotoneMode{
        ast.Year:          monotoneModeNonStrict,
        ast.ToDays:        monotoneModeNonStrict,
        ast.UnixTimestamp: monotoneModeStrict,
+       ast.Plus:          monotoneModeStrict,
+       ast.Minus:         monotoneModeStrict,
+       ast.Mul:           monotoneModeStrict,
+       ast.Div:           monotoneModeNonStrict,
 }

 func getMonotoneMode(fnName string) monotoneMode {
```

Comment (tiancaiamao) [reply planner/core/rule_partition_processor.go]: Done

**Review by wjhuang2016 — APPROVED** [review]
