### PR TITLE
Makefile: add --race flag for tool/bin/ut to support race test

### LINKED ISSUE #33745: Track for race test failed cases
## Enhancement

```
make race 1>a.log 2>b.log
```

- [ ] #33746
- [ ] #33747
- [ ] #33748
- [ ] #33749
- [ ] #33750
- [ ] #33751
- [ ] #33701
- [ ] #33753
- [ ] #33754
- [ ] #33755
- [ ] #33756
- [ ] #33757
- [ ] #33758
- [x] #33759
- [ ] #33760
- [ ] #33761
- [ ] #33762
- [ ] #33764
- [ ] #32846
- [ ] #33766
- [ ] #33030
- [ ] #33193
- [ ] #32846 TestPartitionTableIndexJoinIndexLookUp
- [ ] #33262

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #33745

Problem Summary:

Make `make race` work in the new test running mode

### What is changed and how it works?

Add --race flag for tool/bin/ut and update the Makefile to use it.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

`make race`

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: tools/check/ut.go [hunk 1]
```diff
@@ -397,9 +400,23 @@ func handleFlags(flag string) string {
 	return res
 }
 
+func handleRaceFlag() (found bool) {
```
Comment (Defined2014) [inline tools/check/ut.go:403]: Combine `handleFlags` and `handleRaceFlag` is better. Like add an int param for `handleFlags` to figure out how many args for this flag.

Comment (tiancaiamao) [reply tools/check/ut.go:403]: When the params are complex enough, I'd refactor the code to introduce some more complex packages like `flags`
But I think I can still bear with the complexity.
Any way, it's just used as a quick and dirty script.

**Review by Defined2014 — APPROVED** [review]
