### PR TITLE
*: adjusts the merge sort overlap threshold/merge sort file count step based on concurrency 

### LINKED ISSUE #60951: Index addition is blocked during memory acquisition in the global sort process
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
We found that the real memory acquired is greater than expected during reading. However, we can't reproduce it for now.

### 2. What did you expect to see? (Required)
Add index success
### 3. What did you see instead (Required)
Add index stuck.
### 4. What is your TiDB version? (Required)
v8.5.1

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #60951

Problem Summary:
If the concurrency is less than 8, the memory used may be less than the real requirement.
By adjusting the threshold, we can reduce the actual memory requirement due to lower statistical bias. 

### What changed and how does it work?
	set the threshold to 250*concurrency
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix a global sort bug that may be blocked in CPU: Memory = 1:2 machine 
```

### CODE REVIEW

File: pkg/disttask/importinto/scheduler.go [hunk 1]
```diff
@@ -361,6 +361,7 @@ func (sch *importScheduler) OnNextSubtasksBatch(
 		NextTaskStep:         nextStep,
 		ExecuteNodesCnt:      len(execIDs),
 		Store:                sch.store,
+		ThreadCnt:            8,
```
Comment (D3Hunter) [inline pkg/disttask/importinto/scheduler.go]: this is prod code, why fix it to 8?

File: pkg/lightning/backend/external/writer.go [hunk 2]
```diff
@@ -68,6 +69,33 @@ const (
...
+// So we lower the threshold here if concurrency too low.
+func GetAdjustedMergeSortOverlapThreshold(concurrency int) int64 {
+	intest.Assert(concurrency > 0, "concurrency must be greater than 0, got %d", concurrency)
+	if concurrency < 4 {
+		return 250
+	} else if concurrency < 8 {
+		return 1000
+	} else {
+		return mergeSortOverlapThreshold
+	}
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer.go]: 4000 is the one we used for 16c, so 250 per core, maybe just calculate it by `250 * concurrency`, more smooth

File: pkg/lightning/backend/external/writer.go [hunk 3]
```diff
@@ -68,6 +69,33 @@ const (
...
+	intest.Assert(concurrency > 0, "concurrency must be greater than 0, got %d", concurrency)
+	if concurrency < 4 {
+		return 250
+	} else if concurrency < 8 {
+		return 1000
+	} else {
+		return MergeSortFileCountStep
+	}
+}
+
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer.go]: seems the same as above

File: pkg/disttask/importinto/scheduler.go (hunk 1 above)
Comment (wjhuang2016) [reply pkg/disttask/importinto/scheduler.go]: By mistake

File: pkg/lightning/backend/external/writer.go [hunk 4]
```diff
@@ -68,6 +69,37 @@ const (
...
+// GetAdjustedMergeSortOverlapThreshold adjusts the merge sort overlap threshold based on concurrency.
+// The bigger the threshold, the bigger the statistical bias. In CPU:Memory = 1:2 machine, if the concurrency
+// is less than 8, the memory can be used to load data is small, and may get blocked by the memory limiter.
+// So we lower the threshold here if concurrency too low.
+func GetAdjustedMergeSortOverlapThreshold(concurrency int) int64 {
+	intest.Assert(concurrency > 0, "concurrency must be greater than 0, got %d", concurrency)
+	if concurrency > 16 {
+		return maxMergeSortOverlapThreshold
+	}
+	if concurrency < 0 {
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer.go]:
```suggestion
	if concurrency <= 0 {
```
for prod code, i think it's not possible

File: pkg/lightning/backend/external/writer.go [hunk 5]
```diff
@@ -68,6 +69,37 @@ const (
...
+		// Even though we check it use intest.Assert, it may still goto here in the produce environment.
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer.go]:
```suggestion
		// Even though we check it use intest.Assert, it may still goto here in the prod environment.
```

File: pkg/lightning/backend/external/writer.go [hunk 6]
```diff
@@ -68,6 +69,37 @@ const (
...
+		logutil.BgLogger().Error("concurrency is less than 0, set to 1", zap.Int("concurrency", concurrency))
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer.go]:
```suggestion
		logutil.BgLogger().Error("concurrency is less than or equal to 0, set to 1", zap.Int("concurrency", concurrency))
```

File: pkg/lightning/backend/external/writer.go [hunk 7]
```diff
@@ -68,6 +69,37 @@ const (
...
+	if concurrency > 16 {
+		return MaxMergeSortFileCountStep
+	}
+	if concurrency < 0 {
+		// Even though we check it use intest.Assert, it may still goto here in the produce environment.
+		logutil.BgLogger().Error("concurrency is less than 0, set to 1", zap.Int("concurrency", concurrency))
+		concurrency = 1
+	}
+	return 250 * concurrency
+}
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer.go]: if we must have 2 methods, please abstract the common code part

File: pkg/lightning/backend/external/writer_test.go [hunk 8]
```diff
@@ -835,3 +835,45 @@ func doTestWriterOnDupRemove(t *testing.T, testingOneFile bool, getWriter func(s
...
+		{32, 4000},
+	}
+	for _, tt := range tests {
+		if got := GetAdjustedMergeSortOverlapThreshold(tt.concurrency); got != tt.want {
+			t.Errorf("GetAdjustedMergeSortOverlapThreshold() = %v, want %v", got, tt.want)
+		}
+	}
+}
+
+func TestGetAdjustedMergeSortFileCountStep(t *testing.T) {
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer_test.go]: since their impl is the same now, maybe merge the cases with above one

**Review by D3Hunter — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
