### PR TITLE
expression: fix handling of zero month/day in DATE function

### LINKED ISSUE #59417: Shouldn't allow zero month in datetime string
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run `SELECT DATE('2024-00-15');`.

### 2. What did you expect to see? (Required)

```
mysql> SELECT DATE('2024-00-15');
+--------------------+
| DATE('2024-00-15') |
+--------------------+
| NULL               |
+--------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+----------------------------------------+
| Level   | Code | Message                                |
+---------+------+----------------------------------------+
| Warning | 1292 | Incorrect datetime value: '2024-00-15' |
+---------+------+----------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> SELECT DATE('2024-00-15');
+--------------------+
| DATE('2024-00-15') |
+--------------------+
| 2024-00-15         |
+--------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by cryo-zd**
### What problem does this PR solve?

Issue Number: close #59417 

This PR fix the handling of zero month/day in DATE function so that tidb could return NULL and Warnings when sql_mode [NO_ZERO_IN_DATE](https://dev.mysql.com/doc/refman/8.4/en/sql-mode.html#sqlmode_no_zero_in_date) is set as what MySQL does.

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by cryo-zd** [comment]
> Does the vectorized version have the same issue?

Yes, tried to fix it in the latest commit.

File: pkg/expression/builtin_time.go [hunk 1]
```diff
@@ -310,6 +310,10 @@ func (b *builtinDateSig) evalTime(ctx EvalContext, row chunk.Row) (types.Time, b
 	if expr.IsZero() && sqlMode(ctx).HasNoZeroDateMode() {
 		return types.ZeroTime, true, handleInvalidTimeError(ctx, types.ErrWrongValue.GenWithStackByArgs(types.DateTimeStr, expr.String()))
 	}
+	// for issue 59417, should return NULL when month or day is zero and sql_mode contains NO_ZERO_IN_DATE
+	if expr.Year() != 0 && expr.InvalidZero() && sqlMode(ctx).HasNoZeroInDateMode() {
```
Comment (windtalker) [inline pkg/expression/builtin_time.go]: why need to check `expr.Year() != 0`?

File: pkg/expression/builtin_time_vec.go [hunk 2]
```diff
@@ -99,10 +99,19 @@ func (b *builtinDateSig) vecEvalTime(ctx EvalContext, input *chunk.Chunk, result
 				return err
 			}
 			result.SetNull(i, true)
-		} else {
-			times[i].SetCoreTime(types.FromDate(times[i].Year(), times[i].Month(), times[i].Day(), 0, 0, 0, 0))
-			times[i].SetType(mysql.TypeDate)
+			continue
 		}
+		// for issue 59417, should return NULL when month or day is zero and sql_mode contains NO_ZERO_IN_DATE
+		if times[i].Year() != 0 && times[i].InvalidZero() && sqlMode(ctx).HasNoZeroInDateMode() {
```
Comment (windtalker) [inline pkg/expression/builtin_time_vec.go]: Ditto

File: pkg/expression/builtin_time.go (hunk 1 above)
Comment (cryo-zd) [reply pkg/expression/builtin_time.go]: > The [NO_ZERO_IN_DATE](https://dev.mysql.com/doc/refman/8.4/en/sql-mode.html#sqlmode_no_zero_in_date) mode affects whether the server permits dates in which the year part is nonzero but the month or day part is 0.

Given the description above, I think we had better check `Year != 0`. If not checked, the output of the following scenarios would be different from MySQL (which also makes the local 'make test' failed):
<details> 
<summary>Tidb ( if not check Year != 0)</summary>
<pre><code>
mysql> set @@sql_mode = 'NO_ZERO_IN_DATE';
Query OK, 0 rows affected (0.00 sec)

mysql> select date(0);
+---------+
| date(0) |
+---------+
| NULL    |
+---------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------+
| Level   | Code | Message                                         |
+---------+------+-------------------------------------------------+
| Warning | 1292 | Incorrect datetime value: '0000-00-00 00:00:00' |
+---------+------+-------------------------------------------------+
1 row in set (0.01 sec)

mysql> select date('0000-00-00');
+--------------------+
| date('0000-00-00') |
+--------------------+
| NULL               |
+--------------------+
1 row in set, 1 warning (3.05 sec)

mysql> show warnings;
+---------+------+--------------------------------------------------------+
| Level   | Code | Message                                                |
+---------+------+--------------------------------------------------------+
| Warning | 1292 | Incorrect datetime value: '0000-00-00 00:00:00.000000' |
+---------+------+--------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select @@sql_mode;
+-----------------+
| @@sql_mode      |
+-----------------+
| NO_ZERO_IN_DATE |
+-----------------+
1 row in set (0.00 sec)
</code></pre>

</details>

<details>
<summary> MySQL </summary>

<pre><code>

mysql> set @@sql_mode = 'NO_ZERO_IN_DATE';
Query OK, 0 rows affected, 1 warning (0.08 sec)

mysql> select date(0);
+------------+
| date(0)    |
+------------+
| 0000-00-00 |
+------------+
1 row in set (0.01 sec)

mysql> select date('0000-00-00');
+--------------------+
| date('0000-00-00') |
+--------------------+
| 0000-00-00         |
+--------------------+
1 row in set (0.00 sec)

mysql> select @@sql_mode;
+-----------------+
| @@sql_mode      |
+-----------------+
| NO_ZERO_IN_DATE |
+-----------------+
1 row in set (0.03 sec)

mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.4.4     |
+-----------+
1 row in set (0.03 sec)
</code></pre>

</details>

**Review by zanmato1984 — APPROVED** [review]
LGTM

Thanks for fixing this!

File: pkg/expression/builtin_time.go (hunk 1 above)
Comment (windtalker) [reply pkg/expression/builtin_time.go]: How about use `!expr.IsZero()` instead of `expr.Year() != 0`, because `select date('0000-00-01');` should also return NULL

Comment (cryo-zd) [reply pkg/expression/builtin_time.go]: Done, and cover `date('0000-00-01')` in test.

**Review by windtalker — APPROVED** [review]
lgtm
