### PR TITLE
pkg/ddl: support partition-column type change whitelist

### LINKED ISSUE #66971: shorten partition column type makes logical partition routing inconsistent with physical row placement.
## Bug Report

LIST COLUMNS partition key is shortened in non-strict mode. 'abx' is truncated to 'ab', but rows are not repartitioned. This can make logical partition routing inconsistent with physical row placement.

### 1. Minimal reproduce step (Required)

set sql_mode = '';
drop table if exists t_merge_list;

create table t_merge_list (
  a varchar(3)
) partition by list columns(a) (
  partition p0 values in ("ab"),
  partition p1 values in (default)
);

insert into t_merge_list values ("ab"), ("abx");

-- before truncate, in different partitions.
select * from t_merge_list partition(p0); -- ab
select * from t_merge_list partition(p1); -- abx

-- new data type length is 2，and value "ab" length in partition definition is also 2.
alter table t_merge_list modify a varchar(2);

show warnings;
-- Warning 1265 Data truncated for column 'a', value is 'abx'

-- show results
select * from t_merge_list partition(p0); -- ab
select * from t_merge_list partition(p1); -- ab

-- the last query result is weild
select count(*) from t_merge_list where a='ab';

### 2. What did you expect to see? (Required)
2

### 3. What did you see instead (Required)
1

### 4. What is your TiDB version? (Required)
tidb> select version();
+------------------------------------------------+
| version()                                      |
+------------------------------------------------+
| 8.0.11-TiDB-v9.0.0-beta.2.pre-1340-g827d53dfda |
+------------------------------------------------+
1 row in set (0.006 sec)

### LINKED ISSUE #66972: increase partition column type makes logical partition routing inconsistent with physical row placement.
## Bug Report

After BINARY(2) -> BINARY(3), zero-padding changes hash results (CRC32(c)%2). TiDB does not migrate existing rows across partitions, so physical partition placement may no longer match the new key-to-partition mapping.

### 1. Minimal reproduce step (Required)

DROP TABLE IF EXISTS t_key_bin;

CREATE TABLE t_key_bin (
  c BINARY(2) NOT NULL
)
PARTITION BY KEY(c) PARTITIONS 2;

INSERT INTO t_key_bin VALUES ('A'), ('Q');

-- before modify type, 2 records map to different partitions (see CRC32(c)%2）
SELECT c, CRC32(c) AS crc, CRC32(c) % 2 AS part_idx FROM t_key_bin;
-- | 0x5100 | 3799613162 |        0 |
-- | 0x4100 | 2830855355 |        1 |

ALTER TABLE t_key_bin MODIFY COLUMN c BINARY(3) NOT NULL;

- after modify type, 2 records map to the same partitions (see CRC32(c)%2）, although they are in different partitions in physical.
SELECT c, CRC32(c) AS crc, CRC32(c) % 2 AS part_idx FROM t_key_bin;

### 2. What did you expect to see? (Required)
-- | 0x410000 | 2384019173 |        1 |
-- | 0x510000 | 2453642645 |        1 |

### 3. What did you see instead (Required)
throws errors or do cross partition migration

### 4. What is your TiDB version? (Required)
tidb> select version();
+------------------------------------------------+
| version()                                      |
+------------------------------------------------+
| 8.0.11-TiDB-v9.0.0-beta.2.pre-1340-g827d53dfda |
+------------------------------------------------+
1 row in set (0.006 sec)

### PR DESCRIPTION
**Pull request by expxiaoli**
### What problem does this PR solve?

Issue Number: close #66971, close #66972

Problem Summary:

`ALTER TABLE ... MODIFY/CHANGE COLUMN` on partition columns is too permissive in some cases today.
TiDB may allow a partition-column type change even when the new type changes partition routing semantics, while existing rows are not repartitioned.
This can make logical partition routing inconsistent with physical row placement.

The reported cases include:
- shortening a `LIST COLUMNS` partition column in non-strict mode, where value truncation changes the logical partition key
- enlarging a `KEY` partition column such as `BINARY(2) -> BINARY(3)`, where the partition hash result changes after zero-padding changes

This PR fixes the problem by replacing the overly broad behavior with a whitelist of safe partition-column changes.

### What changed and how does it work?

1. Add a whitelist-based compatibility gate for partition-column modify/change
   - Add partition-column checks in `pkg/ddl/modify_column.go`.
   - Keep renaming a partition column rejected.
   - Keep `EvalType`, charset, and collation unchanged.
   - Allow default-only and comment-only changes.
   - Reject `NULL -> NOT NULL`, while still allowing `NOT NULL -> NULL`.
   - Allow only documented safe type changes for each partitioning form:
     - `KEY` partition: integer widening, `CHAR` / `VARCHAR` / `VARBINARY` length extension, and `ENUM` / `SET` tail append
     - `RANGE/LIST COLUMNS` partition: integer widening, `DATETIME` / `TIME` fractional-seconds precision extension, and `CHAR` / `VARCHAR` / `VARBINARY` length extension
     - `RANGE/LIST/HASH` partition with no function: allow integer widening only
     - `RANGE/LIST/HASH` partition with expression: allow only documented safe cases for `TO_DAYS` and `EXTRACT`; reject `UNIX_TIMESTAMP` and other unsupported functions

2. Keep partition metadata validation and regression coverage aligned with the new rules
   - Rebuild and validate partition definitions after the whitelist check as a final safety net.
   - Add regression tests in `pkg/ddl/tests/partition/db_partition_test.go` for allowed and rejected cases across key, range/list columns, range/list/hash no-function partitions, and range/list/hash expression partitions.
   - Add tests for nullability changes and default/comment-only changes on partition columns.
   - Update DDL docs to describe the partition-column compatibility gate and clarify that these cases still go through `model.ActionModifyColumn`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix unsafe partition-column type changes by restricting `MODIFY/CHANGE COLUMN` to a whitelist of safe cases for partitioned tables.
```

## Summary by CodeRabbit

* **Documentation**
  * Clarified partition-column MODIFY/CHANGE rules with an explicit whitelist by partition form (KEY, RANGE/LIST, expression), rejects partition-column renames, explains compatibility checks, revalidation flow, and notes ALTER … MODIFY/CHANGE on partition columns is handled outside the partition‑DDL job family.

* **Tests**
  * Added a partition regression suite covering allowed/rejected type/flag changes, nullability/default/comment rules, expression‑partition pruning checks, plan/EXPLAIN assertion helpers, and a reminder to keep the whitelist and regression matrix in sync.

### CODE REVIEW

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 1]
```diff
@@ -3258,6 +3313,568 @@ func TestModifyColumnPartitionedTableListAndKeyPartition(t *testing.T) {
...
+			a datetime not null,
+			v int
+		) partition by range (to_days(a) + year(a)) (
+			partition p0 values less than (to_days('2024-03-01') + 2024),
+			partition p1 values less than (to_days('2024-06-01') + 2024),
+			partition pmax values less than (maxvalue)
+		)`)
+		tk.MustGetErrCode(`alter table t_expr_combo_other modify column a datetime(3) not null`, errno.ErrUnsupportedDDLOperation)
+	})
+}
```
[the remark this answers is not in the document]
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: agree

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 2]
```diff
@@ -3258,6 +3313,568 @@ func TestModifyColumnPartitionedTableListAndKeyPartition(t *testing.T) {
...
+		tk.MustExec(`create table t_expr_nullable_ok (
+				a datetime not null,
+				v int
+			) partition by range (to_days(a)) (
+				partition p0 values less than (to_days('2024-01-10')),
+				partition p1 values less than (maxvalue)
+			)`)
+		tk.MustExec(`insert into t_expr_nullable_ok values ('2024-01-01 00:00:00',1)`)
+		tk.MustExec(`alter table t_expr_nullable_ok modify column a datetime null`)
+		tk.MustExec(`admin check table t_expr_nullable_ok`)
```
[the remark this answers is not in the document]
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: agree

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 3]
```diff
@@ -3258,6 +3313,597 @@ func TestModifyColumnPartitionedTableListAndKeyPartition(t *testing.T) {
...
+		tk.MustExec("drop table if exists t_key_wl_str")
+		tk.MustExec(`create table t_key_wl_str (
+			a varchar(8),
+			b int
+		) partition by key(a) partitions 3`)
+		tk.MustExec(`insert into t_key_wl_str values ('a',1),('bbb',2),('cccc',3)`)
+		tk.MustExec(`alter table t_key_wl_str modify column a varchar(32)`)
+		tk.MustExec(`admin check table t_key_wl_str`)
+		tk.MustQuery(`select count(*) from t_key_wl_str where a in ('a','bbb','cccc')`).Check(testkit.Rows("3"))
+	})
```
[the remark this answers is not in the document]
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: agree

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 4]
```diff
@@ -3258,6 +3313,597 @@ func TestModifyColumnPartitionedTableListAndKeyPartition(t *testing.T) {
...
+		)`)
+		tk.MustExec(`insert into t_expr_extract values ('00:00:10',1),('00:00:40',2)`)
+		beforeExtract := tk.MustQuery(`explain format='brief' select * from t_expr_extract where tm = '00:00:10'`).Rows()
+		require.True(t, hasPartitionInPlan(beforeExtract, "p0"), "before modify extract should prune p0")
+		tk.MustExec(`alter table t_expr_extract modify column tm time(3)`)
+		afterExtract := tk.MustQuery(`explain format='brief' select * from t_expr_extract where tm = '00:00:10'`).Rows()
+		require.True(t, hasPartitionInPlan(afterExtract, "p0"), "after modify extract should still prune p0")
+		tk.MustExec(`set session tidb_enable_fast_table_check = off`)
+		tk.MustExec(`admin check table t_expr_extract`)
+	})
```
[the remark this answers is not in the document]
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: agree

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 5]
```diff
@@ -3258,6 +3313,614 @@ func TestModifyColumnPartitionedTableListAndKeyPartition(t *testing.T) {
...
+		tk.MustExec(`create table t_list_cols_wl_bin (
+			a binary(2),
+			b int
+		) partition by list columns(a) (
+			partition p0 values in ('aa'),
+			partition p1 values in ('bb')
+		)`)
+		tk.MustExec(`insert into t_list_cols_wl_bin values ('aa',1),('bb',2)`)
+		tk.MustGetErrCode(`alter table t_list_cols_wl_bin modify column a binary(3)`, errno.ErrUnsupportedDDLOperation)
+	})
```
[the remark this answers is not in the document]
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: agree. I will update code.

File: pkg/ddl/modify_column.go [hunk 6]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
 }
 
+func isAllowedPartitionColumnFlagChange(oldFlag, newFlag uint) bool {
+	if oldFlag == newFlag {
+		return true
+	}
+	// Reject NULL -> NOT NULL for partition columns.
+	if !mysql.HasNotNullFlag(oldFlag) && mysql.HasNotNullFlag(newFlag) {
+		return false
+	}
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Is this not covered below?
```suggestion
```

File: pkg/ddl/modify_column.go [hunk 7]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+func checkPartitionColumnTypeChangeWhitelist(tblInfo *model.TableInfo, col, newCol *model.ColumnInfo) error {
+	// No real type change, so allow it.
+	// Example: modify column a int -> int.
+	if !isPartitionColumnTypeChanged(col, newCol) {
+		return nil
+	}
+
+	pi := tblInfo.GetPartitionInfo()
+	// Not a partition table, so this whitelist does not apply.
+	// Example: create table t(a int).
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: I think this comment can be removed, there are so many checks for `pi` that it is understood that it means it is not a partitioned table.
```suggestion
```

File: pkg/ddl/modify_column.go [hunk 8]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	if pi == nil {
+		return nil
+	}
+
+	switch pi.Type {
+	case ast.PartitionTypeKey:
+		// KEY partition.
+		// Example: PARTITION BY KEY(id) PARTITIONS 4.
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: I think `ast.PartitionTypeKey` is clear enough
```suggestion
```

File: pkg/ddl/modify_column.go [hunk 9]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		if isAllowedTypeChangeForKeyPartition(col, newCol) {
+			return nil
+		}
+		return partitionTypeChangeNotAllowedErr()
+	case ast.PartitionTypeRange, ast.PartitionTypeList:
+		if len(pi.Columns) > 0 {
+			// RANGE/LIST COLUMNS partition.
+			// Example: PARTITION BY RANGE COLUMNS(dt) (...).
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: No need for an example
```suggestion
```

File: pkg/ddl/modify_column.go [hunk 10]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		return checkTypeChangeForExprBasedPartition(pi.Expr, col, newCol)
+	case ast.PartitionTypeHash:
+		if len(pi.Columns) > 0 {
+			// "HASH partition metadata has a column list" cannot happen
+			// from CREATE TABLE syntax in TiDB.
+			// Normal DDL path should never reach here.
+			return dbterror.ErrUnsupportedModifyColumn.GenWithStackByArgs(
+				"unexpected HASH partition metadata with column list",
+			)
+		}
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Since this should never happen, I think it is enough with intest.Assert()
```suggestion
		intest.Assert(len(pi.Columns) == 0, "HASH partitioning does not support COLUMNS, is table metadata corrupted?")
```

Comment (mjonss) [reply pkg/ddl/modify_column.go]: An alternative is to rearrange the logic, so that `PartitionTypeHash` is together with `ast.PartitionTypeRange, ast.PartitionTypeList` and simply add an `intest.Assert(pi.Type != ast.PartitionTypeHash, "HASH partitioning does not support COLUMNS, is the table metadata corrupted?")`

File: pkg/ddl/modify_column.go [hunk 11]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	case ast.Extract:
+		return partitionExprColumnUsageKindExtract
+	case ast.UnixTimestamp:
+		// UNIX_TIMESTAMP is treated as unsupported here.
+		// In partition expr checks, UNIX_TIMESTAMP only accepts TIMESTAMP columns.
+		// Other types (for example VARCHAR/CHAR/DATETIME) are rejected there.
+		// But TIMESTAMP is not an allowed partition-column type in
+		// isColTypeAllowedAsPartitioningCol when modifying type.
+		// So partition-column type change with UNIX_TIMESTAMP should always reject.
+		return partitionExprColumnUsageKindUnsupported
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: I'm not really seeing why UNIX_TIMESTAMP could not be accepted? 
`isColTypeAllowedAsPartitioningCol` is only used for COLUMNS partitioning, where expressions are not allowed anyway?

File: pkg/ddl/modify_column.go [hunk 12]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		// Example: PARTITION BY HASH (a + 1) PARTITIONS 4.
+		return checkTypeChangeForExprBasedPartition(pi.Expr, col, newCol)
+	default:
+		// Any other partition type is not handled here.
+		return partitionTypeChangeNotAllowedErr()
+	}
+}
+
+func checkTypeChangeForExprBasedPartition(partExpr string, col, newCol *model.ColumnInfo) error {
+	usageKinds, err := collectPartitionExprColumnUsageKinds(partExpr, col.Name.L)
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: If we never care about the returned error, why not change `collectPartitionExprColumnUsageKinds()` to only return `usageKinds = nil` if not OK?

File: pkg/ddl/modify_column.go [hunk 13]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	return sel.Fields.Fields[0].Expr, nil
+}
+
+func isAllowedTypeChangeForKeyPartition(col, newCol *model.ColumnInfo) bool {
+	if isIntegerTypeWidening(col, newCol) {
+		return true
+	}
+	if isAllowedStringLengthExtensionForKind(col, newCol, partitionStringKindChar) ||
+		isAllowedStringLengthExtensionForKind(col, newCol, partitionStringKindVarchar) ||
+		isAllowedStringLengthExtensionForKind(col, newCol, partitionStringKindVarbinary) {
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Since this pattern is repeated also below in `isAllowedTypeChangeForRangeListColumnsPartition()`, could we move the check for `partitionStringKindChar`, `partitionStringKindVarchar` and `partitionStringKindVarbinary` into `isAllowedTypeChangeForRangeListColumnsPartition()` directly?

File: pkg/ddl/modify_column.go [hunk 14]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+}
+
+func isAllowedStringLengthExtensionForKind(col, newCol *model.ColumnInfo, kind partitionStringKind) bool {
+	if getPartitionStringKind(&col.FieldType) != kind || getPartitionStringKind(&newCol.FieldType) != kind {
+		return false
+	}
+	if col.GetFlen() <= 0 || newCol.GetFlen() <= 0 {
+		return false
+	}
+	return newCol.GetFlen() > col.GetFlen()
```
Comment (mjonss) [inline pkg/ddl/modify_column.go:1753]: Should we not also support same length?
```suggestion
	return newCol.GetFlen() >= col.GetFlen()
```

File: pkg/ddl/modify_column.go [hunk 15]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	case mysql.TypeInt24:
+		return 2
+	case mysql.TypeLong:
+		return 3
+	case mysql.TypeLonglong:
+		return 4
+	default:
+		return -1
+	}
+}
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Maybe reuse something existing like this?
```suggestion
func isIntegerTypeWideningOrEqual(col, newCol *model.ColumnInfo) bool {
	if !mysql.IsIntegerType(col.GetType()) || !mysql.IsIntegerType(newCol.GetType()) {
		return false
	}
	return mysql.DefaultLengthOfMysqlTypes[newCol.GetType()] >= mysql.DefaultLengthOfMysqlTypes[col.GetType()]
}
```

File: pkg/ddl/modify_column.go [hunk 16]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+
+func isAllowedStringLengthExtensionForKind(col, newCol *model.ColumnInfo, kind partitionStringKind) bool {
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Maybe simplify the code and replace this function with something like:
```golang
// isStringLengthExtension returns true if both columns are the same string/binary
// type (char, varchar, varbinary) and the new column has a strictly larger flen.
// Note: fixed-length BINARY is excluded to match MySQL behavior.
func isStringLengthExtension(col, newCol *model.ColumnInfo) bool {
	oldTp := col.GetType()
	newTp := newCol.GetType()
	switch {
	case oldTp == mysql.TypeString && newTp == mysql.TypeString:
		// CHAR, but not BINARY (fixed-length binary is not allowed to extend).
		if types.IsBinaryStr(&col.FieldType) {
			return false
		}
	case oldTp == newTp && (oldTp == mysql.TypeVarchar || oldTp == mysql.TypeVarString):
		// VARCHAR or VARBINARY — both text and binary variants are allowed.
	default:
		return false
	}
	return col.GetFlen() > 0 && newCol.GetFlen() >= col.GetFlen()
}
```

Which would also get rid of the `partitionStringKind` type and related code.

File: pkg/ddl/modify_column.go [hunk 17]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+func isTimeFspExtended(col, newCol *model.ColumnInfo) bool {
+	if col.GetType() != newCol.GetType() {
+		return false
+	}
+	if col.GetType() != mysql.TypeDuration &&
+		col.GetType() != mysql.TypeDatetime &&
+		col.GetType() != mysql.TypeTimestamp {
+		return false
+	}
+	return newCol.GetDecimal() > col.GetDecimal()
```
Comment (mjonss) [inline pkg/ddl/modify_column.go:1764]: Should we support same length as well?

```suggestion
	return newCol.GetDecimal() >= col.GetDecimal()
```

File: pkg/ddl/modify_column.go [hunk 18]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	default:
+		return false
+	}
+}
+
+func isIntLengthDecreasing(col, newCol *model.ColumnInfo) bool {
+	return mysql.IsIntegerType(col.GetType()) &&
+		mysql.IsIntegerType(newCol.GetType()) &&
+		newCol.GetFlen() < col.GetFlen()
+}
```
Comment (mjonss) [inline pkg/ddl/modify_column.go:1781]: Please do not use `col.GetFlen()` for storage size comparison of integers, it is effectively the deprecated Display length. The comments are a bit wrong for the `flen` in the `FieldType` struct, since I think it uses `defaultLengthAndDecimal[]` map for setting `flen` (which is returned from `GetFlen()`.

Since there are a `isIntegerTypeWidening`, maybe use `!isIntegerTypeWidening()` instead?
```suggestion
```

File: pkg/ddl/modify_column.go [hunk 19]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+
+func classifyPartitionExprFuncUsage(fc *ast.FuncCallExpr) partitionExprColumnUsageKind {
+	// Known funcs use fixed kinds.
+	// Other funcs are unsupported now.
+	switch fc.FnName.L {
+	case ast.ToDays:
+		return partitionExprColumnUsageKindToDays
+	case ast.Extract:
+		return partitionExprColumnUsageKindExtract
+	case ast.UnixTimestamp:
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Please change this to `default`, but keep the comment, since everything else than the above `ToDays` and `Extract` should be unsupported?

File: pkg/ddl/modify_column.go [hunk 20]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		// Example: "(TO_DAYS(a))" keeps kind "to_days" for "a".
+		collectPartitionExprColumnUsageKindsFromExpr(v.Expr, targetColumn, currentKind, usageKinds)
+	case *ast.BinaryOperationExpr:
+		// Visit both sides for exprs like "a + b".
+		collectPartitionExprColumnUsageKindsFromExpr(v.L, targetColumn, currentKind, usageKinds)
+		collectPartitionExprColumnUsageKindsFromExpr(v.R, targetColumn, currentKind, usageKinds)
+	case *ast.UnaryOperationExpr:
+		// Visit unary expr like "-a".
+		collectPartitionExprColumnUsageKindsFromExpr(v.V, targetColumn, currentKind, usageKinds)
+	}
```
Comment (mjonss) [inline pkg/ddl/modify_column.go:1664]: What if there is an expression type not listed here? Should we have a `default` that simply return partitionExprColumnUsageKindUnsupported to be safe?

File: pkg/ddl/modify_column.go [hunk 21]
```diff
@@ -1533,6 +1522,363 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	usageKinds := make(map[partitionExprColumnUsageKind]struct{})
+	collectPartitionExprColumnUsageKindsFromExpr(expr, targetColumn, partitionExprColumnUsageKindNoFunc, usageKinds)
+	return usageKinds, nil
+}
+
+func collectPartitionExprColumnUsageKindsFromExpr(
+	expr ast.ExprNode,
+	targetColumn string,
+	currentKind partitionExprColumnUsageKind,
+	usageKinds map[partitionExprColumnUsageKind]struct{},
```
Comment (mjonss) [inline pkg/ddl/modify_column.go:1631]: (No need to fix) This is a very special case where it is not actually a call-by-value, but instead closer to call-by-reference. Meaning we can actually skip returning the resulting usageKinds map. A subtle detail that is easy to get confused by :) But is does skip the normal golang pattern of `workingValue = func(workingValue)`.

**Review by mjonss — COMMENTED** [review]
In general it looks good, but it can be simplified a bit I think. I have some suggestions in my comments below.

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 22]
```diff
@@ -3258,6 +3315,635 @@ func TestModifyColumnPartitionedTableListAndKeyPartition(t *testing.T) {
 	})
 }
 
+func TestModifyColumnPartitionedTableKeyPartitionWhitelist(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+
+	t.Run("int widening", func(t *testing.T) {
```
Comment (mjonss) [inline pkg/ddl/tests/partition/db_partition_test.go]: I don't think there we need to run everything as separate subtests, probably better without subtests, and maybe looping over same pattern with different alters/table structures.

File: pkg/ddl/modify_column.go (hunk 11 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: I prefer to keep UNIX_TIMESTAMP logic. The comment is not clear, it should be changed to this:
// Do not allow UNIX_TIMESTAMP here.
// In UNIX_TIMESTAMP, it only accepts TIMESTAMP input, 
// but in MODIFY/CHANGE COLUMN the new type is checked by checkPartitionColumnModifiable, and TIMESTAMP does not pass that check. 
// So no type change can be allowed here.

File: pkg/ddl/tests/partition/db_partition_test.go (hunk 22 above)
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: I’d like to keep the subtests here. The current subtests make each case more isolated and make failures easier to find.

File: pkg/ddl/modify_column.go (hunk 14 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go:1753]: I’d like to keep `>` here.

The no-op cases are already handled earlier by `isPartitionColumnTypeChanged()`, so this helper only needs to check real extension. Using `>` also matches the helper name better.

File: pkg/ddl/modify_column.go (hunk 6 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree. I will remove duplicated logic later.

File: pkg/ddl/modify_column.go (hunk 7 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree. I will remove comment later.

File: pkg/ddl/modify_column.go (hunk 8 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree. I will remove comment later.

File: pkg/ddl/modify_column.go (hunk 9 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree. I will remove this line comment later.

File: pkg/ddl/modify_column.go (hunk 10 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: I’d like to keep the runtime error here.

`intest.Assert()` is off in normal builds. If I keep only the assert, we lose the runtime guard outside tests.

Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: I will rearrange the logic as you suggest. PartitionTypeHash together with ast.PartitionTypeRange, ast.PartitionTypeList will make code simpler.

File: pkg/ddl/modify_column.go (hunk 12 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree, returning `nil` usageKinds is enough here. I will update code later.

File: pkg/ddl/modify_column.go (hunk 20 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go:1664]: Agree. "default -> unsupported" is good safeguard. I will update code later.

File: pkg/ddl/modify_column.go (hunk 13 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree, it will make code simpler. I will update code later.

File: pkg/ddl/tests/partition/db_partition_test.go (hunk 22 above)
Comment (mjonss) [reply pkg/ddl/tests/partition/db_partition_test.go]: Finding a failing test can also be achieved by having the proper comment in `MustExec()` and `MustQuery()`, the issue here is that there are so much duplicated code, so it increases the maintenance load, like if something is enhanced, then the rest may fall behind etc.

It is also hard to find if something is tested or not, compare:
```
boiler plate line
boiler plate line
boiler plate line
actual line to test
boiler plate line
boiler plate line
....
boiler plate line
boiler plate line
boiler plate line
Similar line but with slight change
boiler plate line
boiler plate line
....
```

with:
```
tests := {
  actual line to test,
  Similar line but with slight change,
  ....
}
for _, t in range tests {
  boiler plate line
  boiler plate line
  boiler plate line
  t
  boiler plate line
  boiler plate line
}
```

Here you know that all things will be tested in the same way (not need to compare all the boiler code around it), easy to add a test or even modify the test for all cases at the same time.

Comment (mjonss) [reply pkg/ddl/tests/partition/db_partition_test.go]: Also maybe consider to put these modify column tests to its own test file?

File: pkg/ddl/modify_column.go (hunk 15 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree. mysql.DefaultLengthOfMysqlTypes is better. I will update code later.

File: pkg/ddl/modify_column.go (hunk 16 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go]: Agree. This fix could remove partitionStringKind type. I will update code later.

File: pkg/ddl/modify_column.go (hunk 17 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go:1764]: I’d like to keep > here.

The no-op cases are already handled earlier by isPartitionColumnTypeChanged(), so this helper only needs to check real extension. Using > also matches the helper name better.

File: pkg/ddl/modify_column.go (hunk 18 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go:1781]: I will use ```mysql.DefaultLengthOfMysqlTypes``` to implement isIntLengthDecreasing method.
Besides,  I will keep ```isIntLengthDecreasing``` method here. ```isIntLengthDecreasing()``` does not equal to ```!isIntegerTypeWidening()``` because non-integer type will make ```isIntegerTypeWidening()``` return false.

File: pkg/ddl/modify_column.go (hunk 21 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go:1631]: Yes, The map is used as an accumulator and is updated in place, so it does not need to return it, even though Go still passes the map by value.

**Review by expxiaoli — COMMENTED** [review]
Hi @mjonss, here is a short summary of my replies:

I agree most of your comments, and will update code as your suggestion.

Besides, I want to keep the current behavior:
- `UNIX_TIMESTAMP`: I want to keep it unsupported here. I will change the comment to make this clearer.
- Runtime error for the unexpected HASH+COLUMNS case: I want to keep the runtime error. `intest.Assert()` is off in normal builds, so keeping only the assert would remove the runtime guard outside tests.
- Strict `>` in the extension helpers: I want to keep `>`, not `>=`. The no-op cases are already handled earlier by `isPartitionColumnTypeChanged()`, so these helpers only need to check real extension.
- `isIntLengthDecreasing()`: I want to keep this method. It is not the same as `!isIntegerTypeWidening()`, because non-integer types also make `isIntegerTypeWidening()` return false. This method will be reimplemented with ```mysql.DefaultLengthOfMysqlTypes```

One more small note:
- I will fix the very similar cases to loop over same pattern with different alters/table structures.

File: pkg/ddl/tests/partition/db_partition_test.go (hunk 22 above)
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: Thanks, I agree there is too much repeated test code here. Using a few small helpers will make these new whitelist tests easier to read and maintain.

I will fix the very similar cases to loop over same pattern with different alters/table structures like this:

```
	successCases := []successCase{
		{
			name:      "int widening",
			tableName: "t_key_wl_int",
			createSQL: `create table t_key_wl_int (
				a tinyint,
				b int
			) partition by key(a) partitions 3`,
			setupSQLs: []string{
				`insert into t_key_wl_int values (1,10),(2,20),(3,30)`,
			},
			alterSQL:         `alter table t_key_wl_int modify column a int`,
			checkSQL:         `select count(*) from t_key_wl_int`,
			checkRows:        []string{"3"}
		},
		{
			name:      "string widening",
			tableName: "t_key_wl_str",
			createSQL: `create table t_key_wl_str (
				a varchar(8),
				b int
			) partition by key(a) partitions 3`,
			setupSQLs: []string{
				`insert into t_key_wl_str values ('a',1),('bbb',2),('cccc',3)`,
			},
			alterSQL:         `alter table t_key_wl_str modify column a varchar(32)`,
			checkSQL:         `select count(*) from t_key_wl_str where a in ('a','bbb','cccc')`,
			checkRows:        []string{"3"}
		},
        ...
}
for _, tc := range successCases {
		t.Run(tc.name, func(t *testing.T) {
			tk := newPartitionTestKit(t, store)
			preparePartitionAlterCase(tk, tc.tableName, tc.createSQL, tc.setupSQLs...)
			tk.MustExec(tc.alterSQL)
			adminCheckPartitionTable(tk, tc.tableName)
			tk.MustQuery(tc.checkSQL).Check(testkit.Rows(tc.checkRows...))
		})
	}
```

Comment (mjonss) [reply pkg/ddl/tests/partition/db_partition_test.go]: Please move the new tests into a new file, like pkg/ddl/tests/partition/modify_column_test.go

File: docs/agents/ddl/07-modify-column.md [hunk 23]
```diff
@@ -52,6 +52,69 @@ Special-case: `VARCHAR` → `CHAR` may start as `ModifyTypePrecheck` and then 
...
+## Partition-column compatibility gate
+
+`ALTER TABLE ... MODIFY/CHANGE COLUMN` on a partition column is still handled by
+`model.ActionModifyColumn`; it does **not** become a partition-specific DDL job.
+What changes is that TiDB applies an extra compatibility gate before the modify
+can proceed:
+
+- Precheck path: `pkg/ddl/modify_column.go:checkModifyColumn` →
+`checkPartitionColumnModifiable`
+- Owner-side post-check: `pkg/ddl/modify_column.go:postCheckPartitionModifiableColumn`
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: I would not say it is a 'post' check, since it is done before the actual execution of the ddl, from the ddl queue according to the `job`.

When the ddl statement is sent from the client, there are some checks done (ok to say they are pre-check, but it is not very specific) and if everything passes, it will queue a ddl `job` into the global ddl queue, and wait for it to be executed.

Then the ddl 'Owner' will eventually dequeue the `job` and now there might been some changes to the table, since it was queued, due to other jobs that were already in the queue, so another set of checks needs to be done (and this time there cannot be any more changes to the table). A post-check would indicate that it is done **after** something, and this check is still done **before** execution.

Would it be possible to simply use the same function for both your current pre- and post-check? Are there anything that should only be checked in one of the places?

So maybe rename postCheckPartitionModifiableColumn to checkPartitionModifiableColumn and use in both places if possible?

File: docs/agents/ddl/07-modify-column.md [hunk 24]
```diff
@@ -1,6 +1,6 @@
 # Modify Column Deep Dive (type change, nullability, online reorg)
 
-This doc focuses on **`model.ActionModifyColumn`**, covering `ALTER TABLE ... MODIFY COLUMN`, `ALTER TABLE ... CHANGE COLUMN`, and `ALTER TABLE ... RENAME COLUMN` (implemented as a special case of modify-column).
+This doc focuses on `**model.ActionModifyColumn**`, covering `ALTER TABLE ... MODIFY COLUMN`, `ALTER TABLE ... CHANGE COLUMN`, and `ALTER TABLE ... RENAME COLUMN` (implemented as a special case of modify-column).
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: Why this change? I actually think it will render wrong after your change.
```suggestion
This doc focuses on **`model.ActionModifyColumn`**, covering `ALTER TABLE ... MODIFY COLUMN`, `ALTER TABLE ... CHANGE COLUMN`, and `ALTER TABLE ... RENAME COLUMN` (implemented as a special case of modify-column).
```

File: docs/agents/ddl/07-modify-column.md [hunk 25]
```diff
@@ -52,6 +52,69 @@ Special-case: `VARCHAR` → `CHAR` may start as `ModifyTypePrecheck` and then 
...
+- `EvalType`, charset, and collation must stay unchanged.
+- Flag changes are narrowly scoped:
+  - `NULL -> NOT NULL` is rejected.
+  - `NOT NULL -> NULL` is allowed.
+  - default-only and comment-only changes are allowed.
+
+After the whitelist check passes, TiDB still rebuilds partition definitions from
+generated partition metadata (`AppendPartitionInfo` +
+`buildPartitionDefinitionsInfo`). This is the final safety net that catches
+partition-definition values that no longer match the modified column type.
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: So it rebuilds and ... which is the final safety net? Maybe re-word it? 
```suggestion
After the whitelist check passes, TiDB still rebuilds partition definitions from
generated partition metadata (`AppendPartitionInfo` +
`buildPartitionDefinitionsInfo`),
which also includes several different checks and verifications.
This is the final safety net that catches partition-definition values
that no longer match the modified column type.
```

File: docs/agents/ddl/07-modify-column.md [hunk 26]
```diff
@@ -52,6 +52,69 @@ Special-case: `VARCHAR` → `CHAR` may start as `ModifyTypePrecheck` and then 
...
+
+The whitelist itself lives in
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: (nitpick) The word 'whitelist' could be seen as offensive language, see https://dev.mysql.com/blog-archive/mysql-terminology-updates/
Maybe consider use Alllowlist instead?

File: docs/agents/ddl/07-modify-column.md [hunk 27]
```diff
@@ -52,6 +52,69 @@ Special-case: `VARCHAR` → `CHAR` may start as `ModifyTypePrecheck` and then 
...
+
+The expression-partition classification is per **target-column usage path**, not
+just by the root expression. For example, `TO_DAYS(a) + UNIX_TIMESTAMP(b)` may
+still allow modifying `a`, while changes to `b` remain rejected.
+
+This gate decides whether the modify is allowed at all. If it is allowed,
+partitioned tables still follow the normal modify-column flow, and
+`getModifyColumnType` still conservatively routes partitioned tables to
+`ModifyTypeReorg`.
+
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: I wonder if this is a bit too verbose for agents? Too much would eat the context size, and the source code is the original anyway, maybe consider to be more concise ?

File: docs/agents/ddl/07-modify-column.md [hunk 28]
```diff
@@ -163,10 +226,13 @@ Tests (good starting points):
 - `pkg/ddl/modify_column_test.go`
 - `pkg/ddl/column_modify_test.go`
 - `pkg/ddl/column_change_test.go`
+- `pkg/ddl/tests/partition/db_partition_test.go` (partition-column whitelist,
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: When moving the tests to a separate file pkg/ddl/tests/partition/modify_column_test.go, please update this as well.

File: pkg/ddl/tests/partition/db_partition_test.go [hunk 29]
```diff
@@ -3212,6 +3214,171 @@ func TestModifyColumnPartitionedTableGlobalIndexConsistency(t *testing.T) {
...
+func checkPartitionColumnMeta(tk *testkit.TestKit, tableName, columnName, expected string) {
+	tk.MustQuery(fmt.Sprintf(`select column_default, is_nullable, column_comment
+		from information_schema.columns
+		where table_schema='test' and table_name='%s' and column_name='%s'`, tableName, columnName)).
+		Check(testkit.Rows(expected))
+}
+
+func assertExactPrunedPartitions(t *testing.T, tk *testkit.TestKit, sql string, partitions ...string) {
+	rows := tk.MustQuery(sql).Rows()
+	require.True(t, hasExactPartitionsInPlan(rows, partitions...), "expected exact partitions %v for query: %s", partitions, sql)
```
Comment (mjonss) [inline pkg/ddl/tests/partition/db_partition_test.go]: Could `tk.MustPartition()` or `tk.UsedPartitions()` be used instead?

File: docs/agents/ddl/07-modify-column.md (hunk 23 above)
Comment (expxiaoli) [reply docs/agents/ddl/07-modify-column.md]: Good point. I would like to update docs wording to `owner-side recheck`.
But I prefer NOT to rename `postCheckPartitionModifiableColumn` in this PR, because this PR only adds allowlist checks and does not change the call flow.

File: docs/agents/ddl/07-modify-column.md (hunk 24 above)
Comment (expxiaoli) [reply docs/agents/ddl/07-modify-column.md]: Agree. I will update doc later.

File: docs/agents/ddl/07-modify-column.md (hunk 25 above)
Comment (expxiaoli) [reply docs/agents/ddl/07-modify-column.md]: Agree. I will update doc later.

File: docs/agents/ddl/07-modify-column.md (hunk 26 above)
Comment (expxiaoli) [reply docs/agents/ddl/07-modify-column.md]: Good catch. Allowlist is better than whitelist. I will rename it both in code and doc.

File: pkg/ddl/tests/partition/db_partition_test.go (hunk 22 above)
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: Agree. db_partition_test.go is too long. I will move new tests to a new file.

File: docs/agents/ddl/07-modify-column.md (hunk 28 above)
Comment (expxiaoli) [reply docs/agents/ddl/07-modify-column.md]: No problem. I will update this after I move new tests to a new file

File: pkg/ddl/tests/partition/db_partition_test.go (hunk 29 above)
Comment (expxiaoli) [reply pkg/ddl/tests/partition/db_partition_test.go]: Agree. tk.MustPartition() could satisfy test requirement. I will use tk.MustPartition() later.

File: docs/agents/ddl/07-modify-column.md (hunk 27 above)
Comment (expxiaoli) [reply docs/agents/ddl/07-modify-column.md]: Sure. I will make it more concise.

File: docs/agents/ddl/07-modify-column.md [hunk 30]
```diff
@@ -52,6 +52,58 @@ Special-case: `VARCHAR` → `CHAR` may start as `ModifyTypePrecheck` and then 
...
+## Partition-column compatibility gate
+
+`ALTER TABLE ... MODIFY/CHANGE COLUMN` on a partition column is still handled by
+`model.ActionModifyColumn`; it does **not** become a partition-specific DDL job.
+What changes is that TiDB applies an extra compatibility gate before the modify
+can proceed:
+
+- Precheck path: `pkg/ddl/modify_column.go:checkModifyColumn` →
+`checkPartitionColumnModifiable`
+- Owner-side recheck: `pkg/ddl/modify_column.go:postCheckPartitionModifiableColumn`
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: Function is renamed, so this needs to be updated.

File: pkg/ddl/tests/partition/modify_column_test.go [hunk 31]
```diff
@@ -0,0 +1,941 @@
...
+				a varchar(8),
+				b int
+			) partition by key(a) partitions 3`,
+			setupSQLs: []string{`insert into t_key_wl_str values ('a',1),('bbb',2),('cccc',3)`},
+			alterSQL:  `alter table t_key_wl_str modify column a varchar(32)`,
+			checkSQL:  `select count(*) from t_key_wl_str where a in ('a','bbb','cccc')`,
+			checkRows: []string{"3"},
+		},
+		{
+			name:      "enum tail append",
```
Comment (mjonss) [inline pkg/ddl/tests/partition/modify_column_test.go:351]: Could you also add a negative test, that would fail if the existing values are not preserved with their existing order?

File: pkg/ddl/modify_column.go [hunk 32]
```diff
@@ -1533,6 +1514,295 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+			}
+			if isAllowedTypeChangeForRangeListColumnsPartition(col, newCol) {
+				return nil
+			}
+			return partitionTypeChangeNotAllowedErr()
+		}
+		return checkTypeChangeForExprBasedPartition(pi.Expr, col, newCol)
+	default:
+		return partitionTypeChangeNotAllowedErr()
+	}
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: (nitpick) You could also have it like:
```suggestion
	}
	return partitionTypeChangeNotAllowedErr()
```

File: pkg/ddl/modify_column.go [hunk 33]
```diff
@@ -1533,6 +1514,295 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		return
+	default:
+		usageKinds[partitionExprColumnUsageKindUnsupported] = struct{}{}
+	}
+}
+
+func mergePartitionExprUsageKind(parentKind, funcKind partitionExprColumnUsageKind) partitionExprColumnUsageKind {
+	// Keep unsupported once it appears in parent path or current func.
+	// Example: FLOOR(TO_DAYS(a)) -> "a" stays unsupported.
+	if parentKind == partitionExprColumnUsageKindUnsupported || funcKind == partitionExprColumnUsageKindUnsupported {
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: If funcKind is not changed, why not just return it as-is?

```suggestion
	if parentKind == partitionExprColumnUsageKindUnsupported {
```

File: pkg/ddl/modify_column.go [hunk 34]
```diff
@@ -1533,6 +1514,295 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		return true
+	}
+	if isStringLengthExtension(col, newCol) {
+		return true
+	}
+	return false
+}
+
+func isAllowedTypeChangeForNoFuncExprPartition(col, newCol *model.ColumnInfo) bool {
+	return isIntegerTypeWidening(col, newCol)
```
Comment (mjonss) [inline pkg/ddl/modify_column.go:1700]: Should we also check enum here?

File: pkg/ddl/modify_column.go [hunk 35]
```diff
@@ -1533,6 +1514,295 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		col.GetType() != mysql.TypeDatetime &&
+		col.GetType() != mysql.TypeTimestamp {
+		return false
+	}
+	return newCol.GetDecimal() > col.GetDecimal()
+}
+
+func isEnumSetTailAppend(col, newCol *model.ColumnInfo) bool {
+	switch col.GetType() {
+	case mysql.TypeEnum, mysql.TypeSet:
```
Comment (mjonss) [inline pkg/ddl/modify_column.go:1769]: Do we support `TypeSet`?

File: pkg/ddl/modify_column.go [hunk 36]
```diff
@@ -1533,6 +1514,295 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	return newCol.GetFlen() > col.GetFlen()
+}
+
+func isTimeFspExtended(col, newCol *model.ColumnInfo) bool {
+	if col.GetType() != newCol.GetType() {
+		return false
+	}
+	if col.GetType() != mysql.TypeDuration &&
+		col.GetType() != mysql.TypeDatetime &&
+		col.GetType() != mysql.TypeTimestamp {
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Where do we support `TypeTimestamp` in this PR? I though we only can support it through UNIX_TIMESTAMP, which is blocked?

File: pkg/ddl/tests/partition/modify_column_test.go [hunk 37]
```diff
@@ -0,0 +1,941 @@
...
+	tk.MustContainErrMsg("insert into t_global_idx values (100,1,30)", "Duplicate entry '30'")
+	tk.MustExec("insert into t_global_idx values (100,100,100)")
+	tk.MustQuery("select count(*) from t_global_idx").Check(testkit.Rows("5"))
+}
+
+func newPartitionTestKit(t *testing.T, store kv.Storage) *testkit.TestKit {
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	return tk
+}
```
Comment (mjonss) [inline pkg/ddl/tests/partition/modify_column_test.go]: This is not specific for partitioning (which the name suggests), and a very small optimization, maybe consider simply use two lines, as most other tests do?
```suggestion
```

File: pkg/ddl/tests/partition/modify_column_test.go [hunk 38]
```diff
@@ -0,0 +1,941 @@
...
+	verify     func(t *testing.T, tk *testkit.TestKit)
+}
+
+func runPartitionAlterSuccessCase(t *testing.T, store kv.Storage, tc partitionAlterSuccessCase) {
+	tk := newPartitionTestKit(t, store)
+	preparePartitionAlterCase(tk, tc.tableName, tc.createSQL, tc.setupSQLs...)
+	for _, sql := range tc.sessionSQL {
+		tk.MustExec(sql)
+	}
+	tk.MustExec(tc.alterSQL)
```
Comment (mjonss) [inline pkg/ddl/tests/partition/modify_column_test.go]: So these lines basically just runs these sql statements through tk.MustExec()?
DROP TABLE IF EXISTS tc.tableName
tc.createSQL
tc.setupSQLs...
tc.sessionSQL...
tc.alterSQL

And then checks the table?

(Curious question, if you disagree, just ignore it) Why not just have all these in a simple string array all together?

File: pkg/ddl/modify_column.go [hunk 39]
```diff
@@ -1533,6 +1514,295 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		// TIMESTAMP does not pass that check. So no partition-column type change
+		// can be allowed here.
+		return partitionExprColumnUsageKindUnsupported
+	default:
+		return partitionExprColumnUsageKindUnsupported
+	}
+}
+
+func collectPartitionExprColumnUsageKinds(partExpr, targetColumn string) map[partitionExprColumnUsageKind]struct{} {
+	expr, err := parsePartitionExpr(partExpr)
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Maybe reuse a function instead?
```suggestion
	expr, err := generatedexpr.ParseExpression(partExpr)
```

File: pkg/ddl/modify_column.go [hunk 40]
```diff
@@ -1533,6 +1514,295 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	if len(stmt) != 1 {
+		return nil, errors.New("unexpected partition expression statement count")
+	}
+	sel, ok := stmt[0].(*ast.SelectStmt)
+	if !ok || sel.Fields == nil || len(sel.Fields.Fields) != 1 {
+		return nil, errors.New("unexpected partition expression AST")
+	}
+	return sel.Fields.Fields[0].Expr, nil
+}
+
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Could this be replaced by: `generatedexpr.ParseExpression(partExpr)` ?

```suggestion
```

**Review by mjonss — COMMENTED** [review]
Some more suggestions

File: pkg/ddl/modify_column.go (hunk 34 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go:1700]: We do not check enum here.

According to [doc](https://pingcap.feishu.cn/wiki/PFTBwXcYniyGM8kwSZccozRgn8e#share-VeeddJm39o8BeVx6hEIcN6Afnrb), for Range/List/Hash Partitioning with no expression scenario, type change only includes integer widening. Besides, [checkPartitionFuncType ](https://github.com/pingcap/tidb/blob/master/pkg/ddl/partition.go#L1829) method and [EvalType](https://github.com/pingcap/tidb/blob/master/pkg/parser/types/field_type.go#L419) method only allows integer, bit and year type as partition function return type (no func is specific case for partition function)

File: pkg/ddl/modify_column.go (hunk 35 above)
Comment (expxiaoli) [reply pkg/ddl/modify_column.go:1769]: Yes, Both TypeEnum and TypeSet are supported. see [isValidKeyPartitionColType](https://github.com/pingcap/tidb/blob/master/pkg/ddl/partition.go#L743) and [EvalType](https://github.com/pingcap/tidb/blob/master/pkg/ddl/partition.go#L743)

File: pkg/ddl/tests/partition/modify_column_test.go (hunk 38 above)
Comment (expxiaoli) [reply pkg/ddl/tests/partition/modify_column_test.go]: Yes, I think your suggestion makes sense. 
I will fix to `preSQLs []string` + `alterSQL string`. It also keeps the ALTER explicit, because the success runner uses `MustExec`, the reject runner uses `MustGetErrCode`, and the verify runner may use either one and then run extra checks.

**Review by fzzf678 — APPROVED** [review]

File: pkg/ddl/modify_column.go [hunk 41]
```diff
@@ -1533,6 +1515,275 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+func classifyPartitionExprFuncUsage(fc *ast.FuncCallExpr) partitionExprColumnUsageKind {
+	// Known funcs use fixed kinds.
+	// Other funcs are unsupported now.
+	switch fc.FnName.L {
+	case ast.ToDays:
+		return partitionExprColumnUsageKindToDays
+	case ast.Extract:
+		return partitionExprColumnUsageKindExtract
+	case ast.UnixTimestamp:
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: `ast.UnixTimestamp` case in classifyPartitionExprFuncUsage appears unreachable.

If the following is correct, please remove this `case ast.UnixTimestamp`.

pkg/ddl/modify_column.go:1602-1608 explicitly rejects UNIX_TIMESTAMP and justifies it with: "UNIX_TIMESTAMP only accepts TIMESTAMP input, but MODIFY/CHANGE COLUMN revalidates the new type through isColTypeAllowedAsPartitioningCol, and TIMESTAMP does not pass that check."

Claude verified that logic:

checkPartitionColumnModifiable at modify_column.go:1465 calls isColTypeAllowedAsPartitioningCol before checkPartitionColumnTypeChangeAllowlist.
isColTypeAllowedAsPartitioningCol (partition.go:752) omits TypeTimestamp for non-KEY partitions.
The test t_expr_unix (modify_column_test.go:952) confirms the earlier check fires with ErrFieldTypeNotAllowedAsPartitionField, not the allowlist error.
So the explicit case falls through to default anyway. Please remove it (default handles it), if you really want to keep the comment (which is then not really related to the function) please have that including in the `default:` case.

File: pkg/ddl/modify_column.go [hunk 42]
```diff
@@ -1533,6 +1515,275 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+	usageKinds := collectPartitionExprColumnUsageKinds(partExpr, col.Name.L)
+	if usageKinds == nil {
+		return partitionTypeChangeNotAllowedErr()
+	}
+	if _, hasUnsupported := usageKinds[partitionExprColumnUsageKindUnsupported]; hasUnsupported {
+		return partitionTypeChangeNotAllowedErr()
+	}
+	if _, hasNoFunc := usageKinds[partitionExprColumnUsageKindNoFunc]; hasNoFunc {
+		if !isAllowedTypeChangeForNoFuncExprPartition(col, newCol) {
+			if isIntLengthDecreasing(col, newCol) {
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Not sure we need this extra check/code only for a slightly more specific error message? I suggest to remove `isIntLengthDecreasing()` call and function, `partitionTypeChangeNotAllowedErr()` is good enough I think.

File: pkg/ddl/modify_column.go [hunk 43]
```diff
@@ -1533,6 +1515,275 @@ func checkPartitionColumnModifiable(sctx sessionctx.Context, tblInfo *model.Tabl
...
+		(col.GetType() == mysql.TypeDuration || col.GetType() == mysql.TypeDatetime)
+}
+
+func isPartitionColumnTypeChanged(col, newCol *model.ColumnInfo) bool {
+	if col.GetType() != newCol.GetType() {
+		return true
+	}
+	if col.GetFlen() != newCol.GetFlen() {
+		return true
+	}
```
Comment (mjonss) [inline pkg/ddl/modify_column.go]: Is this intentional? This is only display lenght, that should not impact integer storage size right as an example?

File: pkg/ddl/tests/partition/modify_column_test.go (hunk 31 above)
Comment (mjonss) [reply pkg/ddl/tests/partition/modify_column_test.go:366]: Done in `enum reorder rejected`

File: docs/agents/ddl/07-modify-column.md [hunk 44]
```diff
@@ -52,6 +52,57 @@ Special-case: `VARCHAR` → `CHAR` may start as `ModifyTypePrecheck` and then 
...
+## Partition-column compatibility gate
+
+`ALTER TABLE ... MODIFY/CHANGE COLUMN` on a partition column is still handled by
+`model.ActionModifyColumn`; it does **not** become a partition-specific DDL job.
+What changes is that TiDB applies an extra compatibility gate before the modify
+can proceed:
+
+- Precheck path: `pkg/ddl/modify_column.go:preCheckPartitionModifiableColumn`
+- Owner-side recheck: `pkg/ddl/modify_column.go:reCheckPartitionModifiableColumn`
+
```
Comment (mjonss) [inline docs/agents/ddl/07-modify-column.md]: In general I think this whole section is a bit too verbose, for example these two lines are not needed, since on line 90 it says which function implements it (the code is the source of truth.

**Review by mjonss — APPROVED** [review]
LGTM, with some suggestions, I will add a `do-not-merge` so you have time to look into my suggestions, feel free to remove the label when done.
