### PR TITLE
loaddata: fix inconsistent MySQL error

### LINKED ISSUE #43555: load data does not display the column name when the data is too long for column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t1(id char(1),id1 int);
$     cat a.csv
1
2
3
4
5
6
7.1
8
9
1.1
1.2

mysql> LOAD DATA LOCAL INFILE '/home/tidb/wangxj/a.csv' INTO TABLE test.t;
Query OK, 11 rows affected, 3 warnings (0.03 sec)
Records: 11  Deleted: 0  Skipped: 0  Warnings: 3

mysql> show warnings;
+---------+------+----------------------------------------+
| Level   | Code | Message                                |
+---------+------+----------------------------------------+
| Warning | 1406 | Data Too Long, field len 1, data len 3 |
| Warning | 1406 | Data Too Long, field len 1, data len 3 |
| Warning | 1406 | Data Too Long, field len 1, data len 3 |
+---------+------+----------------------------------------+
3 rows in set (0.00 sec)

```

### 2. What did you expect to see? (Required)
When importing data using load data encounters data too long for column, the column name of the data too long is printed.

For example,when I executed it in MySQL, show warnings showed the column with the data too long and the specific number of rows.
image

### 3. What did you see instead (Required)
image

### 4. What is your TiDB version? (Required)
master
mysql> select version();
+--------------------------+
| version()                |
+--------------------------+
| 8.0.11-TiDB-v7.2.0-alpha |
+--------------------------+

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #43555

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: executor/insert_common.go [hunk 1]
```diff
@@ -547,15 +565,29 @@ func (e *InsertValues) doBatchInsert(ctx context.Context) error {
...
+		if err = e.handleErr(e.insertColumns[i], &vals[i], int(e.rowCount), err); err != nil {
 			return nil, err
 		}
 
 		offset := e.insertColumns[i].Offset
 		row[offset] = casted
 		hasValue[offset] = true
+
+		if e.ctx.GetSessionVars().StmtCtx.InLoadDataStmt {
+			if newWarnings := sc.TruncateWarnings(warnCnt); len(newWarnings) > 0 {
```
Comment (D3Hunter) [inline executor/insert_common.go:583]: on which case we need to handle existing warnings?

File: executor/test/loadremotetest/error_test.go [hunk 2]
```diff
@@ -262,3 +262,39 @@ func (s *mockGCSSuite) TestDataError() {
...
+
+	s.tk.MustQuery("SHOW WARNINGS;").Check(testkit.Rows(
+		"Warning 1261 Row 1 doesn't contain data for all columns",
+		"Warning 1261 Row 2 doesn't contain data for all columns",
+		"Warning 1265 Data truncated for column 'id' at row 2"))
+	s.tk.MustQuery("SELECT * FROM t;").Check(testkit.Rows(
+		"6 <nil>",
+		"7 <nil>"))
+
+	err = s.tk.ExecToErr(fmt.Sprintf(`LOAD DATA INFILE 'gs://test-csv/43555.csv?endpoint=%s'
```
Comment (D3Hunter) [inline executor/test/loadremotetest/error_test.go:297]: does this warning happen when we use `set id=7.1`?

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: executor/insert_common.go (hunk 1 above)
Comment (lance6716) [reply executor/insert_common.go:583]: to fix 43555, we need to rewrite the warnings

Comment (lance6716) [reply executor/insert_common.go:583]: I copied from https://github.com/pingcap/tidb/blob/cd834eec65c54fdae2869adc2d76f3f8f7868042/executor/insert.go#L415-L422

File: executor/test/loadremotetest/error_test.go (hunk 2 above)
Comment (lance6716) [reply executor/test/loadremotetest/error_test.go:297]: the SQL does not use IGNORE INTO, so it will become an error. I want to check that the warnings path and error path are both covered.

Comment (lance6716) [reply executor/test/loadremotetest/error_test.go:297]: https://github.com/pingcap/tidb/pull/44167/commits/fbbd07de214a878afe0ccb97a0d6f3d51c7aa051
