### PR TITLE
variable: support tidb_schema_cache_size reasonable range

### LINKED ISSUE #54034: tidb_schema_cache_size max support value is wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> set @@global.tidb_schema_cache_size=10737418240;
Query OK, 0 rows affected, 1 warning (0.05 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------------+
| Level   | Code | Message                                                         |
+---------+------+-----------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect tidb_schema_cache_size value: '10737418240' |
+---------+------+-----------------------------------------------------------------+
1 row in set (0.07 sec)

mysql> select @@global.tidb_schema_cache_size;
+---------------------------------+
| @@global.tidb_schema_cache_size |
+---------------------------------+
| 2147483647                      |
+---------------------------------+
1 row in set (0.06 sec)

```
### 2. What did you expect to see? (Required)
The Range is [0, 9223372036854775807] based the dock https://docs.pingcap.com/tidb/dev/system-variables#tidb_schema_cache_size-new-in-v800
### 4. What is your TiDB version? (Required)

Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 6cf8776242fbfe0b922488357867ca5244e7b8fa
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-13 11:49:48
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by lilinghai**
### What problem does this PR solve?

Issue Number: close #54034

Problem Summary:

### What changed and how does it work?

The value range is 0 and [536870912, 9223372036854775807] in bytes. The size format with the units "KB|MB|GB|TB" is supported.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/sessionctx/variable/sysvar_test.go [hunk 1]
```diff
@@ -1671,3 +1671,99 @@ func TestSetEnableColumnTrackingAndPersistAnalyzeOptions(t *testing.T) {
...
+		val      string
+		maxValue uint64 = math.MaxInt64
+	)
+	// Test tidb_schema_cache_size
+	schemaCacheSize := GetSysVar(TiDBSchemaCacheSize)
+	// Check default value
+	require.Equal(t, schemaCacheSize.Value, strconv.Itoa(DefTiDBSchemaCacheSize))
+
+	// MinValue is 512 MB
+	err = mock.SetGlobalSysVar(context.Background(), TiDBSchemaCacheSize, strconv.FormatUint(100*mb, 10))
```
Comment (wjhuang2016) [inline pkg/sessionctx/variable/sysvar_test.go:1692]: Please test 512MB-1 and MaxValue + 1

File: pkg/sessionctx/variable/tidb_vars.go [hunk 2]
```diff
@@ -1595,7 +1596,8 @@ var (
 	IgnoreInlistPlanDigest    = atomic.NewBool(DefTiDBIgnoreInlistPlanDigest)
 	TxnEntrySizeLimit         = atomic.NewUint64(DefTiDBTxnEntrySizeLimit)
 
-	SchemaCacheSize = atomic.NewInt64(DefTiDBSchemaCacheSize)
+	SchemaCacheSize           = atomic.NewUint64(DefTiDBSchemaCacheSize)
+	SchemaCacheSizeOriginText = atomic.NewString(strconv.Itoa(DefTiDBSchemaCacheSize))
```
Comment (wjhuang2016) [inline pkg/sessionctx/variable/tidb_vars.go:1600]: We can get the text from SchemaCacheSize like we have done for TiDBServerMemoryLimitSessMinSize

File: pkg/sessionctx/variable/sysvar_test.go (hunk 1 above)
Comment (lilinghai) [reply pkg/sessionctx/variable/sysvar_test.go:1652]: added

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/sessionctx/variable/varsutil.go [hunk 3]
```diff
@@ -587,3 +588,25 @@ func ParseAnalyzeSkipColumnTypes(val string) map[string]struct{} {
...
+			normalizedStr = "512MB"
+		}
+		if err == nil && byteSize > math.MaxInt64 {
+			s.StmtCtx.AppendWarning(ErrTruncatedWrongValue.FastGenByArgs(TiDBSchemaCacheSize, originalValue))
+			byteSize = math.MaxInt64
+			normalizedStr = strconv.Itoa(math.MaxInt64)
+		}
+	}()
+
+	bt, str := parseByteSize(normalizedValue)
```
Comment (lance6716) [inline pkg/sessionctx/variable/varsutil.go:606]: i prefer we use "github.com/docker/go-units".FromHumanSize or "github.com/docker/go-units".RAMInBytes.

Comment (lilinghai) [reply pkg/sessionctx/variable/varsutil.go]: Refined

File: pkg/infoschema/infoschema_test.go [hunk 4]
```diff
@@ -953,13 +953,13 @@ func TestEnableInfoSchemaV2(t *testing.T) {
...
 	tk.MustQuery("select @@global.tidb_schema_cache_size").Check(testkit.Rows("0"))
-	require.Equal(t, variable.SchemaCacheSize.Load(), int64(0))
+	require.Equal(t, variable.SchemaCacheSize.Load(), uint64(0))
 
 	// Modify it.
-	tk.MustExec("set @@global.tidb_schema_cache_size = 1024")
-	tk.MustQuery("select @@global.tidb_schema_cache_size").Check(testkit.Rows("1024"))
-	tk.MustQuery("select @@tidb_schema_cache_size").Check(testkit.Rows("1024"))
-	require.Equal(t, variable.SchemaCacheSize.Load(), int64(1024))
+	tk.MustExec("set @@global.tidb_schema_cache_size = 1073741824")
```
Comment (lance6716) [inline pkg/infoschema/infoschema_test.go:959]: Please check if there's test cases like "10MB"

File: pkg/sessionctx/variable/varsutil.go [hunk 5]
```diff
@@ -587,3 +589,24 @@ func ParseAnalyzeSkipColumnTypes(val string) map[string]struct{} {
 	}
 	return skipTypes
 }
+
+func parseSchemaCacheSize(s *SessionVars, normalizedValue string, originalValue string) (byteSize uint64, normalizedStr string, err error) {
+	defer func() {
+		if err == nil && byteSize > 0 && byteSize < (512<<20) {
+			s.StmtCtx.AppendWarning(ErrTruncatedWrongValue.FastGenByArgs(TiDBSchemaCacheSize, originalValue))
+			byteSize = 512 << 20
+			normalizedStr = "512MB"
```
Comment (lance6716) [inline pkg/sessionctx/variable/varsutil.go:598]: In fact this is MiB not MB.

And since we already imported the units package, we can use 

```
byteSize = 512 * units.MiB
```

File: pkg/sessionctx/variable/varsutil.go [hunk 6]
```diff
@@ -587,3 +589,24 @@ func ParseAnalyzeSkipColumnTypes(val string) map[string]struct{} {
...
+		}
+		if err == nil && byteSize > math.MaxInt64 {
+			s.StmtCtx.AppendWarning(ErrTruncatedWrongValue.FastGenByArgs(TiDBSchemaCacheSize, originalValue))
+			byteSize = math.MaxInt64
+			normalizedStr = strconv.Itoa(math.MaxInt64)
```
Comment (lance6716) [inline pkg/sessionctx/variable/varsutil.go:603]: what's the rule that we display a number or a human reabable string?

File: pkg/sessionctx/variable/varsutil.go [hunk 7]
```diff
@@ -587,3 +589,24 @@ func ParseAnalyzeSkipColumnTypes(val string) map[string]struct{} {
...
+		}
+	}()
+	res, err := units.RAMInBytes(normalizedValue)
+	if err != nil {
+		return 0, "", ErrTruncatedWrongValue.GenWithStackByArgs(TiDBSchemaCacheSize, originalValue)
+	}
+	bt := uint64(res)
```
Comment (lance6716) [inline pkg/sessionctx/variable/varsutil.go:610]: the type of `res` is int64. I'm not sure if line 600 will really happen. Please also add a unit test to cover it.

File: pkg/infoschema/infoschema_test.go (hunk 4 above)
Comment (lilinghai) [reply pkg/infoschema/infoschema_test.go:959]: it the pkg/sessionctx/variable/sysvar_test.go we add 10KB test

File: pkg/sessionctx/variable/varsutil.go (hunk 5 above)
Comment (lilinghai) [reply pkg/sessionctx/variable/varsutil.go:598]: fixed

File: pkg/sessionctx/variable/varsutil.go (hunk 6 above)
Comment (lilinghai) [reply pkg/sessionctx/variable/varsutil.go:603]: display what the user set. for example if user set 1073741824 we display the number of 1073741824. if user set 10GB we display 10GB

File: pkg/sessionctx/variable/varsutil.go (hunk 7 above)
Comment (lilinghai) [reply pkg/sessionctx/variable/varsutil.go:610]: The `RAMInBytes` func will use `strconv.ParseFloat` func to parse the size, it may return negative numbers(res) and then uint64(res) will be larger than math.MaxInt64, so we check it.
There is a ut in `pkg/sessionctx/variable/sysvar_test.go` and we test `math.MaxInt64+1`

File: pkg/sessionctx/variable/sysvar_test.go [hunk 8]
```diff
@@ -1631,3 +1631,113 @@ func TestTiDBLowResTSOUpdateInterval(t *testing.T) {
...
+	val, err = mock.GetGlobalSysVar(TiDBSchemaCacheSize)
+	require.NoError(t, err)
+	require.Equal(t, "512MB", val)
+
+	// test MaxValue+1
+	err = mock.SetGlobalSysVar(context.Background(), TiDBSchemaCacheSize, strconv.FormatUint(maxValue+1, 10))
+	require.NoError(t, err)
+	val, err = mock.GetGlobalSysVar(TiDBSchemaCacheSize)
+	require.NoError(t, err)
+	require.Equal(t, strconv.FormatUint(maxValue, 10), val)
```
Comment (lance6716) [inline pkg/sessionctx/variable/sysvar_test.go:1677]: strange I can't pass this test case in macOS M1

```
    sysvar_test.go:1677: 
        	Error Trace:	/Users/lance6716/Projects/tidb/pkg/sessionctx/variable/sysvar_test.go:1677
        	Error:      	Not equal: 
        	            	expected: "9223372036854775807"
        	            	actual  : "9223372036854775808"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-9223372036854775807
        	            	+9223372036854775808
        	Test:       	TestTiDBSchemaCacheSize
--- FAIL: TestTiDBSchemaCacheSize (0.00s)
```

seems the overflow behaviour is platform specific

https://go.dev/ref/spec#Conversions then search for "Conversions between numeric types"

> In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

I think it's safer to check overflow first, but I don't find a easy way to implement it using `units.RAMInBytes` 😂 Sorry for my suggestion. Now I recommend to revert to our `parseByteSize`

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: pkg/sessionctx/variable/sysvar_test.go (hunk 8 above)
Comment (lilinghai) [reply pkg/sessionctx/variable/sysvar_test.go:1677]: Anaway, thank you for your review. I have also learned that handling floats with `RAMInBytes` carries some risk of overflow. I reverted to our `parseByteSize`.

**Review by lance6716 — APPROVED** [review]
