### PR TITLE
 executor: fix point get -1 return max.uInt64 value

### LINKED ISSUE #10056: bigint unsigned select problem
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "root@tcp(127.0.0.1:4000)/test")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	db.Exec("CREATE TABLE IF NOT Exists `t1` (`id` bigint(20) UNSIGNED NOT NULL, PRIMARY KEY (`id`) )")
	db.Exec("insert into t1 values (18446744073709551615)")

	var i = ^uint64(0)

	rows, err := db.Query("select id from t1 where id=?", i)
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	var r uint64
	for rows.Next() {
		rows.Scan(&r)
		fmt.Printf("GOT: %d \n", r)
	}

	rows, err = db.Query("select id from t1 where id=?", -1)
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		rows.Scan(&r)
		fmt.Printf("GOT: %d \n", r)
	}
}

```
2. What did you expect to see?

run against MySQL it returns

```
GOT: 18446744073709551615
```

3. What did you see instead?

run agains TiDB it returns:

```
GOT: 18446744073709551615
GOT: 18446744073709551615
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v3.0.0-beta.1-68-ge48b258f9
Git Commit Hash: e48b258f9226ed8d4e6147154afb26ab7d8c59b2
Git Branch: master
UTC Build Time: 2019-04-04 05:05:01
GoVersion: go version go1.12.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

related issue:  https://github.com/go-sql-driver/mysql/pull/838

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve? 

fixes #10056.

### What is changed and how it works?

this question only occurred in prepare + point-select, in normal query optimize will collapse condition a = -100 to none if a is unsigned and got a TableDual in this case, but point-get some different code path, and plan cache also need be take care(we can not cache a TableDual and want it be a real table in later  input). 

so here, we keep unsigned info in PointGetPlan and generate a "done=true" PointGetExecutor if give a negative parameter.

### Check List 

Tests 

 - Unit test

Code changes

 - implement change

Side effects

 - N/A

Related changes

 - N/A

relate question https://github.com/pingcap/tidb/issues/10111 but not easy to fix that and plan to fix them when we solve the string-cast question in plan-cache

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/10113)

### CODE REVIEW

File: executor/point_get.go [hunk 1]
```diff
@@ -44,6 +44,7 @@ func (b *executorBuilder) buildPointGet(p *plannercore.PointGetPlan) Executor {
 		idxVals: p.IndexValues,
 		handle:  p.Handle,
 		startTS: startTS,
+		done:    p.UnsignedHandle && p.Handle < 0,
```
Comment (winoros) [inline executor/point_get.go]: What's this?

File: planner/core/point_get_plan_test.go [hunk 2]
```diff
@@ -136,4 +141,13 @@ func (s *testPointGetSuite) TestPointGetPlanCache(c *C) {
 	counter.Write(pb)
 	hit = pb.GetCounter().GetValue()
 	c.Check(hit, Equals, float64(2))
+	tk.MustExec("insert into t (a, b, c) values (18446744073709551615, 4, 4)")
+	tk.MustExec("set @p1=-1")
+	tk.MustExec("set @p2=1")
+	tk.MustExec(`prepare stmt7 from "select a from t where a = ?"`)
+	tk.MustQuery("execute stmt7 using @p1").Check(testkit.Rows())
+	tk.MustQuery("execute stmt7 using @p2").Check(testkit.Rows("1"))
```
Comment (eurekaka) [inline planner/core/point_get_plan_test.go]: This test case cannot test `PointGet` plan actually? the plan generated using `@p1` is table_scan + selection, not point get, so `@p2` actually reuses this table_scan + selection plan?

Comment (lysu) [reply planner/core/point_get_plan_test.go]: @eurekaka oh...... this logic is magic...

> This test case cannot test PointGet plan actually? the plan generated using @p1 is table_scan + selection, not point get, so @p2 actually reuses this table_scan + selection plan?

In my test this can use point-get in two executes, because prepare use `?` instead of `-1` or `1`, so `getNameValuePair` can handle `ParramMarkExpr`, then prepare success a point-get and execute as point-get.

```
mysql> show create table t1;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                               |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `a` bigint(20) NOT NULL,
  `b` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> explain select * from t1 where a = -1;                                                                                                                                                                                                                                                                     +-------------------+-------+------+---------------------------------------------------------+
| id                | count | task | operator info                                           |
+-------------------+-------+------+---------------------------------------------------------+
| TableReader_6     | 1.00  | root | data:TableScan_5                                        |
| └─TableScan_5     | 1.00  | cop  | table:t1, range:[-1,-1], keep order:false, stats:pseudo |
+-------------------+-------+------+---------------------------------------------------------+
2 rows in set (0.01 sec)

mysql> prepare st from "explain select * from t1 where a = ?";
Query OK, 0 rows affected (0.00 sec)

mysql> set @x=-1;
Query OK, 0 rows affected (0.00 sec)

mysql> execute st using @x;                                                                                                                                                                                                                                                                                    
+-------------+-------+------+---------------------+
| id          | count | task | operator info       |
+-------------+-------+------+---------------------+
| Point_Get_1 | 1.00  | root | table:t1, handle:-1 |
+-------------+-------+------+---------------------+
1 row in set (0.00 sec)
```
> same as the first case, but handle column is int64, would the second execute report error?

so for this case:

> same as the first case, but handle column is int64, would the second execute report error?

maybe luck is just fine

> handle column is unsigned, if the first execute is pk = 1, and the second execute is like pk = 18446744073709551615, since we are using int64 as handle type in PointGet, would the second execute cause overflow and wrong result?

will ok for both use point-get plan, but there are another question, we keep param as string datum and try to cast it to int64, so will got a overflow question, it seems not easy to fix so it take another issue in here https://github.com/pingcap/tidb/issues/10111.

:rofl:  it's very stranger -1 cannot use plan cache, and prepare and normal query use different plan..

File: executor/point_get.go (hunk 1 above)
Comment (lysu) [reply executor/point_get.go]: this make `PointGetExecutor`'s Next return no result, we cannot use tabledual,  this just like tabedual, and no need add more flag- -

File: planner/core/point_get_plan_test.go (hunk 2 above)
Comment (eurekaka) [reply planner/core/point_get_plan_test.go]: I think the root cause of these problems is that we are using int64 to store the handle in PointGet, while it can be unsigned.

**Comment by XuHuaiyu** [comment]
Can we add a bool flag called `isHandleUnsigned` to mark whether the `Handle` used in PointGetPlan is unsigned? 
And we can check this flag to decide whether to use `uint64(Handle)` when we want to use it.

**Comment by jackysp** [comment]
Please resolve the conflicts, @lysu .

**Comment by lysu** [comment]
@XuHuaiyu we have [UnsignedHandle](https://github.com/pingcap/tidb/blob/e92d4b691487aaba8a12322028fe710f1918a5e0/planner/core/point_get_plan.go#L44) to mark it in pointGetPlann :D

**Comment by XuHuaiyu** [comment]
@lysu Should this commit be cherry-picked to release-2.1?
