### PR TITLE
adapter, txn: Move aggressive locking controlling logic to handlePessimisticXXX functions to avoid some potential misuses

### LINKED ISSUE #41724: Some tests panics when running all tests with tidb_pessimistic_txn_aggressive_locking globally enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Change the default value of variable `tidb_pessimistic_txn_aggressive_locking` to true in the code, then run all unit tests

### 2. What did you expect to see? (Required)

Everything goes well.

### 3. What did you see instead (Required)

Some test cases fails:

```
Error 1105: Trying to start aggressive locking while it's already started
```

After some investigation, it's found to be caused by not exiting aggressive locking after executing the previous statement in the transaction.

For example, `TestRcTSOCmdCountForPrepareExecuteExtra` panics because TiDB's `ast.IsReadOnly` regards a select statement with a select-for-update subquery to be readonly (which is wrong). This causes `StmtCommit` or `StmtRollback` (which are responsible to exit aggressive locking if it's active) not invoked after finishing the statement.

`show_profile` in mysql-test panics in a similar way, but it's not successfully reproduced.

This means exiting aggressive locking in `StmtCommit` or `StmtRollback` is a bad idea since TiDB has complicated and even maybe incorrect logic to determine whether `StmtCommit` or `StmtRollback` needs to be called after finishing a statement. We'd better exit aggressive locking within `handlePessimisticDML` and `handlePessimisticSelectForUpdate`, which is also the place that enters aggressive locking. 

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

Issue Number: close #41724 

Problem Summary:

### What is changed and how it works?

This PR moves invokations of aggressive locking starting/retrying/exiting to single functions (`handlePessimisticDML` and `handlePessimisticSelectForUpdate`). These two functions will enter aggressive locking if needed, and exit aggressive locking when it returns. Previously we exits aggressive locking in `StmtCommit` and `StmtRollback`. However in issue #41724 we founds that sometimes TiDB doesn't evaluate the condition to call `StmtCommit`/`StmtRollback` correctly, causing the aggressive locking state leak to the next statement. This PR avoids this leaking by exiting aggressive locking within the function that starts the aggressive locking.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that sometimes query fails when `tidb_pessimistic_txn_aggressive_locking` is enabled and prepare-execute is used on `select ... (select ... for update)` statements (select statements with select-for-update subquery).
```

### CODE REVIEW

File: sessiontxn/interface.go [hunk 1]
```diff
@@ -137,8 +137,14 @@ type TxnContextProvider interface {
 	// OnStmtStart is the hook that should be called when a new statement started
 	OnStmtStart(ctx context.Context, node ast.StmtNode) error
 	// OnHandlePessimisticStmtStart is the hook that should be called when starts handling a pessimistic DML or
-	// a pessimistic select-for-update statements.
+	// a pessimistic select-for-update statement.
 	OnHandlePessimisticStmtStart(ctx context.Context) error
+	// OnPessimisticLockError is the hook that should be called when lock error happens during a pessimistic DML or
+	// select-for-update statement.
+	OnPessimisticLockError(ctx context.Context, lockErr error) error
```
Comment (cfzjywxk) [inline sessiontxn/interface.go:144]: `OnStmtErrorForNextAction` has some logic about handling `StmtErrAfterPessimisticLock`, could we merge these logic together so we could avoid adding a new interface.

**Review by ekexium — APPROVED** [review]

File: sessiontxn/interface.go (hunk 1 above)
Comment (MyonKeminta) [reply sessiontxn/interface.go:144]: That makes sense and looks safe to use. I didn't notice that.

File: sessiontxn/interface.go [hunk 2]
```diff
@@ -137,8 +137,14 @@ type TxnContextProvider interface {
...
+	// OnHandlePessimisticStmtEnd is the hook that should be called when finishes handling a pessimistic DML or
+	// select-for-update statement.
+	OnHandlePessimisticStmtEnd(ctx context.Context, isSuccessful bool) error
```
[the remark this answers is not in the document]
Comment (MyonKeminta) [reply sessiontxn/interface.go:147]: I actually want to emphasize their difference with `OnStmtStart` etc, but, ok

File: sessiontxn/isolation/repeatable_read.go [hunk 3]
```diff
@@ -234,7 +234,11 @@ func notNeedGetLatestTSFromPD(plan plannercore.Plan, inLockOrWriteStmt bool) boo
 	return false
 }
 
-func (p *PessimisticRRTxnContextProvider) handleAfterPessimisticLockError(lockErr error) (sessiontxn.StmtErrorAction, error) {
+func (p *PessimisticRRTxnContextProvider) handleAfterPessimisticLockError(ctx context.Context, lockErr error) (sessiontxn.StmtErrorAction, error) {
+	if err := p.retryAggressiveLockingIfNeeded(ctx); err != nil {
+		return sessiontxn.ErrorAction(err)
+	}
```
Comment (cfzjywxk) [inline sessiontxn/isolation/repeatable_read.go:240]: Is `txn.retryAggressiveLockingIfNeeded` necessary for the other two pathes that error would be returned? If not should we move this part to L255-L268?

Comment (MyonKeminta) [reply sessiontxn/isolation/repeatable_read.go:240]: Ah yes, I missed that. It's only needed in retrying cases. And I just noticed that for single-statement-deadlock cases, we should exit aggressive locking mode, otherwise it will still keep the lock that's blocking the other transaction.

File: sessiontxn/isolation/readcommitted.go [hunk 4]
```diff
@@ -237,6 +242,9 @@ func (p *PessimisticRCTxnContextProvider) handleAfterPessimisticLockError(lockEr
 	}
```
Comment (cfzjywxk) [inline sessiontxn/isolation/readcommitted.go:242]: Should we call the `CancelAggressiveLocking` for the last else branch?
```
if deadlock, ok := errors.Cause(lockErr).(*tikverr.ErrDeadlock); ok && deadlock.IsRetryable {
} else if terror.ErrorEqual(kv.ErrWriteConflict, lockErr) {
} else {
  // This branch.
}
```

Comment (MyonKeminta) [reply sessiontxn/isolation/readcommitted.go:242]: The final `else` branch will not set `retryable = true` thus the function will finally return error. Cancelling here looks not necessary.

**Review by cfzjywxk — APPROVED** [review]

**Comment by MyonKeminta** [comment]
@ekexium There's some change to the code. Could you take a look again?

**Comment by MyonKeminta** [comment]
emmmm
/merge

**Comment by ekexium** [comment]
> @ekexium There's some change to the code. Could you take a look again?

LGTM
