### PR TITLE
util/collate: fix the issue that '�'(\uFFFD) was treated as invalid sequence

### LINKED ISSUE #64144: WEIGHT_STRING of U+FFFD collate utf8mb4_general_ci is changed between v8.5.2 and v8.5.3, leading to silent data-index inconsistency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Start a tagged playground running v8.5.2 

```sh
tiup playground v8.5.2 --db 1 --kv 1 --pd 1 --tiflash 0 --without-monitor -T revert61972
```

2. Create a table with a utf8mb4_general_ci collation index, insert an entry with U+FFFD

```sql
create table test.a (id bigint primary key, name varchar(10) collate utf8mb4_general_ci, key(name));
insert into test.a values (1, 'A�B');
select weight_string(name) from test.a;
-- 0x0041FFFD0042
```

3. Upgrade the playground to v8.5.3

```sh
# Ctrl+C
tiup playground v8.5.3 --db 1 --kv 1 --pd 1 --tiflash 0 --without-monitor -T revert61972
```

4. Check the WEIGHT_STRING. Note that everything after the U+FFFD is truncated.

```sql
select name, weight_string(name) from test.a where id = 1;
-- 'A�B', 0x0041
```

5. Note that the index cannot be used to look up the affected row

```sql
select * from a where name = (select name from a where id = 1);
-- Empty set
```

6. Note that deleting the row leads to Error 8141.

```sql
delete from test.a where id = 1;
-- ERROR 8141 (HY000): assertion failed: key: 74800000000000006e5f698000000000000001010041000000000000f9038000000000000001, assertion: Exist, start_ts: 461786157551976449, existing start ts: 0, existing commit ts: 0
```

7. Note that ADMIN CHECK TABLE is unable to detect any problem.

```sql
admin check table a;
-- Query OK, 0 rows affected
```

### 3. What did you see instead (Required)

Everything after step 4 are unexpected.

### 4. What is your TiDB version? (Required)

v8.5.2 → v8.5.3

### PR DESCRIPTION
**Pull request by bb7133**
### What problem does this PR solve?

Issue Number: close #64144

Problem Summary:

### What changed and how does it work?

To be added

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - The steps described in #64144, I tried both '�' and a "real invalid byte sequence".
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- NA

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that '�'(\uFFFD) is incorrectly treated as a invalid sequence
```

### CODE REVIEW

**Comment by lance6716** [comment]
(I just fixed another problem with \uFFFD, maybe some common idea? https://github.com/pingcap/tidb/pull/63936)

File: pkg/util/collate/collate.go [hunk 1]
```diff
@@ -362,6 +364,36 @@ func CollationToProto(c string) int32 {
...
+		// See https://pkg.go.dev/unicode/utf8#DecodeRune for more details.
+		// Here we check both the size and rune to distinguish between invalid byte sequence and valid '�'.
+		invalid1 := r1 == utf8.RuneError && r1Len == 1
+		invalid2 := r2 == utf8.RuneError && r2Len == 1
+		if invalid1 || invalid2 {
+			return 0
+		}
+
+		ai = ai + r1Len
+		bi = bi + r2Len
```
Comment (kennytm) [inline pkg/util/collate/collate.go]:
```suggestion
		ai += r1Len
		bi += r2Len
```

File: pkg/util/collate/collate.go [hunk 2]
```diff
@@ -362,6 +364,36 @@ func CollationToProto(c string) int32 {
...
+
+		cmp := int(keyFunc(r1)) - int(keyFunc(r2))
+		if cmp != 0 {
+			return sign(cmp)
+		}
+	}
+	return sign((len(a) - ai) - (len(b) - bi))
```
Comment (kennytm) [inline pkg/util/collate/collate.go]: why don't we use [`cmp.Compare`](https://pkg.go.dev/cmp@go1.25.3#Compare) for these 🤔 

```suggestion
		cmp := cmp.Compare(keyFunc(r1), keyFunc(r2))
		if cmp != 0 {
			return cmp
		}
	}
	return cmp.Compare(len(a) - ai, len(b) - bi)
```

File: pkg/util/collate/collate.go [hunk 3]
```diff
@@ -362,6 +364,36 @@ func CollationToProto(c string) int32 {
...
+func compareCommon(a, b string, keyFunc func(rune) uint32) int {
+	a = truncateTailingSpace(a)
+	b = truncateTailingSpace(b)
+
+	r1, r2 := rune(0), rune(0)
+	ai, bi := 0, 0
+	r1Len, r2Len := 0, 0
+	for ai < len(a) && bi < len(b) {
+		r1, r1Len = utf8.DecodeRune(hack.Slice(a[ai:]))
+		r2, r2Len = utf8.DecodeRune(hack.Slice(b[bi:]))
```
Comment (kennytm) [inline pkg/util/collate/collate.go]:
```suggestion
		r1, r1Len = utf8.DecodeRuneInString(a[ai:])
		r2, r2Len = utf8.DecodeRuneInString(b[bi:])
```

**Review by kennytm — COMMENTED** [review]
LGTM aside from some minor style changes

File: pkg/util/collate/collate.go (hunk 2 above)
Comment (bb7133) [reply pkg/util/collate/collate.go]: Nice catch, thanks!

**Comment by bb7133** [comment]
Addressed, PTAL @kennytm

**Review by kennytm — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
