### PR TITLE
expression: fix runtime error integer divide by zero

### LINKED ISSUE #17181: exprssion: unexpected behaviour of TRUNCATE
## Bug Report

Current `TRUNCATE` implementation ignores the situation whose second argument is a uint.

### 1. What did you do?
```sql
create table t (a bigint unsigned);
insert into t values (18446744073709551615);
select truncate(42, a) from t;
```

### 2. What did you expect to see?
In MySQL 8.0:
```sql
mysql root@127.0.0.1:test> select truncate(42, a) from t;
+-------------------+
|   truncate(42, a) |
|-------------------|
|                42 |
+-------------------+
```

### 3. What did you see instead?
In TiDB:
```sql
mysql root@127.0.0.1:test> select truncate(42, a) from t;
+-------------------+
|   truncate(42, a) |
|-------------------|
|                40 |
+-------------------+
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master

### LINKED ISSUE #19390: runtime error: integer divide by zero
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
select truncate(1, -9223372036854775808);
select truncate(1, -2147483648);
```

### 2. What did you expect to see? (Required)
`0,0`
### 3. What did you see instead (Required)
one of them is runtime error, depend on 32 or 64 bit machine
### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1049-g8336190b6
Edition: Community
Git Commit Hash: 8336190b61b8a43554a69e5398f9d11e84d877d1
Git Branch: master
UTC Build Time: 2020-08-24 06:02:03
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close #19390, close #17181

### What is changed and how it works?

What's Changed:
- consider unsigned flag in `TRUNCATE`
- return `0` directly if negative number is too large

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix a runtime error in `TRUNCATE`

### CODE REVIEW

File: expression/builtin_math.go [hunk 1]
```diff
@@ -1975,6 +1978,10 @@ func (b *builtinTruncateIntSig) evalInt(row chunk.Row) (int64, bool, error) {
 	if d >= 0 {
 		return x, false, nil
 	}
+	// math.Pow10(d) == INF if d > 308
```
Comment (wjhuang2016) [inline expression/builtin_math.go:1981]: Better add a case for d=308.

Comment (xiongjiwei) [reply expression/builtin_math.go:1981]: new test was added, positive number do not run here. I add -308, -307 and -309

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: expression/builtin_math.go [hunk 2]
```diff
@@ -1975,6 +1978,10 @@ func (b *builtinTruncateIntSig) evalInt(row chunk.Row) (int64, bool, error) {
...
+	if d < -308 {
```
Comment (SunRunAway) [inline expression/builtin_math.go:1982]: Is it better using [`math.IsInf`](https://golang.org/pkg/math/#IsInf) for this judgement?

Comment (xiongjiwei) [reply expression/builtin_math.go:1982]: I think not, this `if` is used for avoid the situation `-(-9223372036854775808)=-9223372036854775808`(64bit os) or 
`-(-2147483648)=-2147483648`(32bit os).  and `math.Pow10(-d)==INF` if `d < -308`,so, we can return `0` directly

Comment (SunRunAway) [reply expression/builtin_math.go:1982]: `math.IsInf` can be used to judge whether `math.Pow10(-d) is `INF`, see

```go
shiftFloat := math.Pow10(int(-d))
if math.IsInf(shiftFloat) {
    return 0, false, nil
}
shift := int64(shift)
```

Comment (xiongjiwei) [reply expression/builtin_math.go:1982]: the problem is not about `INF`, `math.Pow10(int(-d))=0` if `d=int.MIN_VALUE`, it cause `divide by zero` error. since `int.MIN_VALUE` is different in different os (64bit or 32bit), I make a judgement `d<-308`. we can remove this `if` statement if go can do this
```go
if d==int.MIN_VALUE {
    return 0, false, nil
}
```

Comment (SunRunAway) [reply expression/builtin_math.go:1982]: Thanks for your explanation. LGTM.

**Review by SunRunAway — DISMISSED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: expression/builtin_math.go (hunk 2 above)
Comment (SunRunAway) [reply expression/builtin_math.go:1982]: Would this help?
```go
if (mathutil.IntBits == 64 && d == math.MinInt64) || d == math.MinInt32)
```

Comment (xiongjiwei) [reply expression/builtin_math.go:1982]: that is great, we can use 
```go
if d == mathutil.MinInt {
	return 0, false, nil
}
```

Comment (xiongjiwei) [reply expression/builtin_math.go]: updated

**Review by SunRunAway — APPROVED** [review]
