### PR TITLE
tools/bin/ut: support generate JUnit format test report

### LINKED ISSUE #30822: Make CI great again!
## Enhancement

The unstable CI has been a hinder to our daily development. Sometimes we have to run it again and again, and again ... to merge a PR.
It takes a very long time to run the CI and if a unstable test fails, all the time are wasted.

There are many bad decisions we made in the past:

- To make it run faster, we use a wrong way to parallel
- Auto re-run to amend for the unstable test cases
- No timeout limitation on a single unit test
- High coupling of the code and running environment
- Multiple teams to maintain CI thus the unclear responsbilities

Let's review it one by one.

We use a wrong way to parallel. Some test cases are not side effect free, for example:

- the enable and disable of the failpoint
- modification of the configuration
- change of the global variable in a single process.
- etc...

If the test cases with side effect run parallelly with others, it could cause some test fail unexpectedly. 
When they're in a single OS process, make them parallel is not a big deal.
Parallel make the CI run a bit faster but when some test fail, it takes us a lot of time to investigate the root cause.

We employ auto re-run using the CI bot to amend for the unstable tests. IMHO, this is another failure.
The auto re-run tend to make us ignore the unstable cases. See https://github.com/pingcap/tidb/issues/25899
As time goes on, there are more and more unstable test cases. And test cases almost fail randomly!
Later, if someone file a PR and run all test pass without retry, maybe he would think: WOW, today I'm so lucky~

Back to the point of parallel, why we want to make the test parallel? we want it to run faster because it's slow.
So why it's slow? because we're adding more and more test cases.
Well, I found many code are poorly writen. Some test cases call `sleep()` at will, and a single test case may run even more than 120s! 
The problem is, there was no timeout limitation on it, so I added one.
However, the timeout makes the CI more unstable https://github.com/pingcap/tidb/issues/26717

Parallel requires more machine resource and with retrying, that can eat up all the machine resources! 
The high load of the CI environment makes the test cases more likely to fail.
The situation comes from bad to worse.

So high coupling of the code and running environment makes the running time of a single test case undecidable.
Timeout limitation on a single unit test doesn't work well.
I can see the test case always finish within 3s in my own computer, but that's not the truth in the CI environment.

========================

### What's the solution?

- [X] Step1: remove all the in-process parallel [#30692](https://github.com/pingcap/tidb/pull/30692)
- [x] Step2: Add back parallel by run a single test case in a isolated OS process [#30828](https://github.com/pingcap/tidb/issues/30828)
    - [x]     polish of the tool ut, exit code, output log etc
    - [x]     fix some failed test cases
    - [ ]     limit the timeout for a single test case
    - [x] #31885
    - [x] #31893

- [ ] Step3: Make a bootstraped store snapshot to avoid `Bootstrap()` in every single test

For step2, we can specify the test case by the name manually:

```
go test -run TextXXX
```

And we can run different test cases parallely, each with its own OS process, so the code is isolated without side effect.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #30822

Problem Summary:

In the old CI script, we support generate the JUnit format test report

https://github.com/pingcap/tidb/blob/453535600f6016b4faae3158277f92013f111a85/Makefile#L142-L143

Before we can replace the old script with the new one, `make ut` should support this feature.

### What is changed and how it works?

Support `--junitfile xxx` flags for `make ut`, the test report will be generated in the JUnit file format, compatibility with the old script.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

```
make ut X='run tablecodec --junitfile xxx'
cat xxx
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
        <testsuite tests="19" failures="0" time="0.000000" name="github.com/pingcap/tidb/tablecodec">
                <properties>
                        <property name="go.version" value="go1.16.8 linux/amd64"></property>
                </properties>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestCutPrefix" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestPrefix" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestRecordKey" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestRange" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestUntouchedIndexKValue" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestDecodeAutoIDMeta" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestError" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestRowCodec" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestTimeCodec" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestDecodeBadDecical" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestTableCodecInvalid" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestCutRow" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestDecodeIndexKey" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestCutKey" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestUnflattenDatums" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestTableCodec" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestIndexKey" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestCutKeyNew" time=""></testcase>
                <testcase classname="github.com/pingcap/tidb/tablecodec" name="TestDecodeColumnValue" time=""></testcase>
        </testsuite>
</testsuites>
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: tools/check/ut.go [hunk 1]
```diff
@@ -436,39 +457,98 @@ func listPackages() ([]string, error) {
...
+				cases = make([]JUnitTestCase, 0, 10)
+			}
+			cases = append(cases, res.JUnitTestCase)
+			pkgs[res.Classname] = cases
+			durations[res.Classname] = durations[res.Classname] + res.d
+		}
+	}
+
+	suites := JUnitTestSuites{}
+	// Turn every package resuts to a suite.
```
Comment (tangenta) [inline tools/check/ut.go:527]:
```suggestion
	// Turn every package result to a suite.
```

**Review by tangenta — APPROVED** [review]
