### PR TITLE
executor: fix sort result for batch-point-get by unsigned pk

### LINKED ISSUE #20100: unexpected results returned by `BatchPointGet`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (
    id bigint(20) unsigned,
    primary key(id)
);

insert into t values (8738875760185212610);
insert into t values (9814441339970117597);

select id from t where id in (8738875760185212610, 9814441339970117597) order by id;
```

### 2. What did you expect to see? (Required)
```
mysql> select id from t where id in (8738875760185212610, 9814441339970117597) order by id;
+---------------------+
| id                  |
+---------------------+
| 8738875760185212610 |
| 9814441339970117597 |
+---------------------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select id from t where id in (8738875760185212610, 9814441339970117597) order by id;
+---------------------+
| id                  |
+---------------------+
| 9814441339970117597 |
| 8738875760185212610 |
+---------------------+
2 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
mysql> select version();
+-------------------------------------------------+
| version()                                       |
+-------------------------------------------------+
| 5.7.25-TiDB-v4.0.0-beta.2-1253-g0e4b809ca-dirty |
+-------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: close #20100 

Problem Summary:

batch point sort handle before batch-get but didn't take care handle maybe uint

### What is changed and how it works?

What's Changed, How it Works:

sort as uint when it's unsigned pk

### Related changes

- Need to cherry-pick to the release branch 4.0 

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- fix sort result for max unsigned int in batch-point-get

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/20108)

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

File: executor/batch_point_get.go [hunk 1]
```diff
@@ -251,11 +252,16 @@ func (e *BatchPointGetExec) initialize(ctx context.Context) error {
 			failpoint.InjectContext(ctx, "batchPointGetRepeatableReadTest-step2", nil)
 		})
 	} else if e.keepOrder {
+		unsignedPK := e.tblInfo.PKIsHandle && mysql.HasUnsignedFlag(e.tblInfo.GetPkColInfo().Flag)
 		sort.Slice(e.handles, func(i int, j int) bool {
+			compare := e.handles[i].Compare
+			if unsignedPK {
+				compare = kv.UintHandleComparator(e.handles[i].(kv.IntHandle)).Compare
+			}
```
Comment (lzmhhh123) [inline executor/batch_point_get.go:260]: Could we move the compare function out of sort.Slice?

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
