### PR TITLE
ddl: save and restore auto_random id when rename table

### LINKED ISSUE #18211: rename auto_random table lead to duplicate entry
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (a bigint auto_random primary key);
insert into t values ();
...  -- repeat 100 times
insert into t values ();
alter table t rename to newdb.t;
alter table newdb.t rename to t;
insert into t values ();
...  -- repeat 100 times BANG!
insert into t values ();
```

### 2. What did you expect to see? (Required)

Query Ok.

### 3. What did you see instead (Required)

```console
Error: Duplicate entry 'xxxxx' for key 'PRIMARY'
```

### 4. Affected version (Required)

master, v3.1.0, v4.0.0

### 5. Root Cause Analysis

`auto_random` ID should be kept when renaming tables.

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #18211 

Problem Summary: 

`auto_random` ID should be kept when renaming tables.

### What is changed and how it works?

What's Changed:

- Save and restore `auto_random` ID in `onRenameTable()`.
- Add a test for renaming `auto_random` table

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- fix duplicate entry when renaming `auto_random` tables.

### CODE REVIEW

File: executor/ddl_test.go [hunk 1]
```diff
@@ -933,14 +935,35 @@ func (s *testAutoRandomSuite) TestAutoRandomBitsData(c *C) {
...
-	for _, h := range allHandles {
+	for _, h := range extractAllHandles() {
 		signBitUnused = signBitUnused && (h > 0)
 	}
 	// Sign bit should be used for shard.
 	c.Assert(signBitUnused, IsFalse)
-	tk.MustExec("drop table t")
+	tk.MustExec("drop table t;")
+
+	// Test rename rename table does not affect incremental part of auto_random ID.
```
Comment (tangenta) [inline executor/ddl_test.go:946]:
```suggestion
	// Test rename table does not affect incremental part of auto_random ID.
```
