### PR TITLE
s3: add Content-MD5 header in S3Uploader for compatibility options

### LINKED ISSUE #65331: [tidb-x] add index blocked after simulated s3 network partition or latency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、enable global sort and dxf
2、run sysbench
3、add index for one table
4、simulated s3 network partition or latency last for 3mins
5、recovery fault

### 2. What did you expect to see? (Required)
add index can succeed after fault recover

### 3. What did you see instead (Required)
add index blocked after simulated s3 network partition or latency (the state is always running)

[tidb (8).log.zip](https://github.com/user-attachments/files/24382189/tidb.8.log.zip)

Image

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v9.0.0-beta.2.pre-977-gcf4647e
Edition: Enterprise
Git Commit Hash: cf4647ed8024d91f743906541b86492906ccaa05
Git Branch: HEAD
UTC Build Time: 2025-12-29 13:20:09
GoVersion: go1.25.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Enterprise Extension Commit Hash: dc633aae52eb11b4e3549e3a7ef5b0ed14e159b1
Kernel Type: Next Generation
2025-12-30T07:04:31.787+0800

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #65331

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
tested on KS3, before this PR when cleanup import jobs we meet error. after this PR there is no such error.
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/objstore/s3store/s3.go [hunk 1]
```diff
@@ -744,7 +749,11 @@ func PutAndDeleteObjectCheck(ctx context.Context, svc S3API, options *backuppb.S
 	}()
 	// when no permission, aws returns err with code "AccessDenied"
 	input := buildPutObjectInput(options, file, []byte("check"))
-	_, err = svc.PutObject(ctx, input)
+	var optFns []func(*s3.Options)
+	if options.Provider != "" && options.Provider != "aws" {
```
Comment (D3Hunter) [inline pkg/objstore/s3store/s3.go]: please merge master, we can also check through `s3Compatible` now

**Comment by D3Hunter** [comment]
refer https://github.com/pingcap/tidb/issues/62541
