### PR TITLE
executor: fix TempDir permissions bug

### LINKED ISSUE #16694: When using TempDir, it does not deal with multi-user permissions and the folders used may not be unique
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

* Execute `./tidb-server` under user `foo`, and then exit.
* Then execute `./tidb-server` under the user `bar`.

### 2. What did you expect to see?

* Successfully started TiDB

### 3. What did you see instead?

```
[bar@localhost ~]$ ./tidb-server
Failed to acquire exclusive lock on the temporary storage dir(/tmp/tidb/NDAwMC8xMDA4MA==/tmp-storage). Error detail: {open /tmp/tidb/NDAwMC8xMDA4MA==/tmp-storage/_dir.lock: permission denied}

# Additional bug: This line of log format is wrong.

# Try to delete the relevant folder
[bar@localhost ~]$ sudo rm -rf /tmp/tidb/NDAwMC8xMDA4MA==

[bar@localhost ~]$ ./tidb-server
[2020/04/22 00:01:34.866 -04:00] [FATAL] [terror.go:348] ["unexpected error"] [error="mkdir /tmp/tidb/NDAwMC8xMDA4MA==: permission denied"] [stack="github.com/pingcap/log.Fatal\n\t/home/hundundm/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/global.go:59\ngithub.com/pingcap/parser/terror.MustNil\n\t/home/hundundm/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200413043052-ef80f4de418c/terror/terror.go:348\nmain.initializeTempDir\n\t/home/hundundm/workspace/tidb/tidb-server/main.go:207\nmain.main\n\t/home/hundundm/workspace/tidb/tidb-server/main.go:171\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:203"]


# Try to change the permissions of the folder
[bar@localhost ~]$ sudo chmod 777 /tmp/tidb

[bar@localhost ~]$ ./tidb-server
[2020/04/22 00:02:51.186 -04:00] [INFO] [printer.go:41] ["Welcome to TiDB."] ["Release Version"=v4.0.0-beta.2-308-ga9091029b] ["Git Commit Hash"=a9091029b84ad013513ca50f49a117fdb865e8d2] ["Git Branch"=master] ["UTC Build Time"="2020-04-22 03:46:18"] [GoVersion=go1.13.1] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
[2020/04/22 00:02:51.186 -04:00] [INFO] [printer.go:54] ["loaded config"] [config="{\"host\":\"0.0.0.0\",\"advertise-address\":\"0.0.0.0\",\"port\":4000,\"cors\":\"\",\"store\":\"mocktikv\",\"path\":\"/tmp/tidb\",\"socket\":\"\",\"lease\":\"45s\",\"run-ddl\":true,\"split-table\":true,\"token-limit\":1000,\"oom-use-tmp-storage\":true,\"tmp-storage-path\":\"/tmp/tidb/NDAwMC8xMDA4MA==/tmp-storage\",\"oom-action\":\"cancel\",\"mem-quota-query\":1073741824,\"tmp-storage-quota\":-1,\"enable-streaming\":false,\"enable-batch-dml\":false,\"lower-case-table-names\":2,\"server-version\":\"\",\"log\":{\"level\":\"info\",\"format\":\"text\",\"disable-timestamp\":null,\"enable-timestamp\":null,\"disable-error-stack\":null,\"enable-error-stack\":null,\"file\":{\"filename\":\"\",\"max-size\":300,\"max-days\":0,\"max-backups\":0},\"enable-slow-log\":true,\"slow-query-file\":\"tidb-slow.log\",\"slow-threshold\":300,\"expensive-threshold\":10000,\"query-log-max-len\":4096,\"record-plan-in-slow-log\":1},\"security\":{\"skip-grant-table\":false,\"ssl-ca\":\"\",\"ssl-cert\":\"\",\"ssl-key\":\"\",\"require-secure-transport\":false,\"cluster-ssl-ca\":\"\",\"cluster-ssl-cert\":\"\",\"cluster-ssl-key\":\"\",\"cluster-verify-cn\":null},\"status\":{\"status-host\":\"0.0.0.0\",\"metrics-addr\":\"\",\"status-port\":10080,\"metrics-interval\":15,\"report-status\":true,\"record-db-qps\":false},\"performance\":{\"max-procs\":0,\"max-memory\":0,\"stats-lease\":\"3s\",\"stmt-count-limit\":5000,\"feedback-probability\":0.05,\"query-feedback-limit\":1024,\"pseudo-estimate-ratio\":0.8,\"force-priority\":\"NO_PRIORITY\",\"bind-info-lease\":\"3s\",\"txn-total-size-limit\":104857600,\"tcp-keep-alive\":true,\"cross-join\":true,\"run-auto-analyze\":true},\"prepared-plan-cache\":{\"enabled\":false,\"capacity\":100,\"memory-guard-ratio\":0.1},\"opentracing\":{\"enable\":false,\"rpc-metrics\":false,\"sampler\":{\"type\":\"const\",\"param\":1,\"sampling-server-url\":\"\",\"max-operations\":0,\"sampling-refresh-interval\":0},\"reporter\":{\"queue-size\":0,\"buffer-flush-interval\":0,\"log-spans\":false,\"local-agent-host-port\":\"\"}},\"proxy-protocol\":{\"networks\":\"\",\"header-timeout\":5},\"tikv-client\":{\"grpc-connection-count\":4,\"grpc-keepalive-time\":10,\"grpc-keepalive-timeout\":3,\"commit-timeout\":\"41s\",\"max-batch-size\":128,\"overload-threshold\":200,\"max-batch-wait-time\":0,\"batch-wait-size\":8,\"enable-chunk-rpc\":true,\"region-cache-ttl\":600,\"store-limit\":0,\"copr-cache\":{\"enabled\":false,\"capacity-mb\":0,\"admission-max-result-mb\":0,\"admission-min-process-ms\":0}},\"binlog\":{\"enable\":false,\"ignore-error\":false,\"write-timeout\":\"15s\",\"binlog-socket\":\"\",\"strategy\":\"range\"},\"compatible-kill-query\":false,\"plugin\":{\"dir\":\"\",\"load\":\"\"},\"pessimistic-txn\":{\"enable\":true,\"max-retry-count\":256},\"check-mb4-value-in-utf8\":true,\"max-index-length\":3072,\"alter-primary-key\":false,\"treat-old-version-utf8-as-utf8mb4\":true,\"enable-table-lock\":false,\"delay-clean-table-lock\":0,\"split-region-max-num\":1000,\"stmt-summary\":{\"enable\":true,\"enable-internal-query\":false,\"max-stmt-count\":200,\"max-sql-length\":4096,\"refresh-interval\":1800,\"history-size\":24},\"repair-mode\":false,\"repair-table-list\":[],\"isolation-read\":{\"engines\":[\"tikv\",\"tiflash\",\"tidb\"]},\"max-server-connections\":0,\"new_collations_enabled_on_first_bootstrap\":false,\"experimental\":{\"allow-auto-random\":false,\"allow-expression-index\":false},\"enable-collect-execution-info\":false}"]
[2020/04/22 00:02:51.187 -04:00] [INFO] [main.go:341] ["disable Prometheus push client"]
[2020/04/22 00:02:51.187 -04:00] [INFO] [store.go:68] ["new store"] [path=mocktikv:///tmp/tidb]
[2020/04/22 00:02:51.187 -04:00] [WARN] [store.go:76] ["new store with retry failed"] [error="open /tmp/tidb/LOCK: permission denied"]
[2020/04/22 00:02:51.187 -04:00] [INFO] [systime_mon.go:25] ["start system time monitor"]
[2020/04/22 00:02:51.187 -04:00] [FATAL] [terror.go:348] ["unexpected error"] [error="open /tmp/tidb/LOCK: permission denied"] [stack="github.com/pingcap/log.Fatal\n\t/home/hundundm/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200117041106-d28c14d3b1cd/global.go:59\ngithub.com/pingcap/parser/terror.MustNil\n\t/home/hundundm/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200413043052-ef80f4de418c/terror/terror.go:348\nmain.createStoreAndDomain\n\t/home/hundundm/workspace/tidb/tidb-server/main.go:293\nmain.main\n\t/home/hundundm/workspace/tidb/tidb-server/main.go:181\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:203"]
```

### 4. What caused this bug?

* We should not use `/tmp` directly, we should use `os.TempDir()`
* When we created the `/tmp/tidb` directory, the code used was `os.MkdirAll(tempDir, 0755)`. This directory can only be accessed by the creator and root
  * Maybe we need to use `0777` to create `/tmp/tidb` and then use `0755` to create the remaining directories.
  * I think a more reasonable solution is to use `/<os.TempDir()>/<os.Getuid()>_tidb` as a prefix. TiKV used this [solution](https://github.com/tikv/tikv/pull/7470) when resolving similar [issue](https://github.com/tikv/tikv/issues/7462).
* One used subdirectory is `/tmp/tidb/<Base64(Port_StatusPort)>`, this directory is not unique. Different tidb can listen to addresses on the same port but different hostnames(like 127.0.0.1:4000/10080 and 172.16.5.1:4000/10080).
  * Since StatusHttp does not allow repeated listening, we can use `/<os.TempDir()>/<os.Getuid()>_tidb/<AdvertiseAddress_StatusPort>`
  * We can also use `ioutil.TempDir("", "oom-use-tmp-storage")` directly

The related default config is `path` (mockkv) and `oom-use-tmp-storage`(#15203).

### 5. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
./tidb-server -V
Release Version: v4.0.0-beta.2-308-ga9091029b
Git Commit Hash: a9091029b84ad013513ca50f49a117fdb865e8d2
Git Branch: master
UTC Build Time: 2020-04-22 03:46:18
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by hsqlu**
Signed-off-by: Qiannan Lyu <lvqiannan@gmail.com>

### What problem does this PR solve?

Issue Number: close #16694 

Problem Summary: 

### What is changed and how it works?

What's Changed: Changed the default oom use temp storage directory.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

run tidb under current user.

```
➜  tidb git:(bugfix-executor-16694) ./bin/tidb-server 
....
[2020/04/26 13:19:59.923 +12:00] [INFO] [delete_range.go:133] ["[ddl] start delRange emulator"]
[2020/04/26 13:19:59.929 +12:00] [INFO] [domain.go:144] ["full load InfoSchema success"] [usedSchemaVersion=0] [neededSchemaVersion=22] ["start time"=5.210194ms]
[2020/04/26 13:19:59.929 +12:00] [INFO] [domain.go:368] ["full load and reset schema validator"]
[2020/04/26 13:19:59.953 +12:00] [INFO] [server.go:235] ["server is running MySQL protocol"] [addr=0.0.0.0:4000]
[2020/04/26 13:19:59.953 +12:00] [INFO] [http_status.go:81] ["for status and metrics report"] ["listening on addr"=0.0.0.0:10080]
[2020/04/26 13:19:59.954 +12:00] [INFO] [domain.go:1044] ["init stats info time"] ["take time"=1.085873ms]

```

Fail to run again by the same user.
```
➜  tidb git:(bugfix-executor-16694) ./bin/tidb-server 
The current temporary storage dir(/var/folders/sy/0hb_gmbx087c36vy31vj398h0000gn/T/501_tidb/NDAwMC8xMDA4MA==/tmp-storage) has been occupied by another instance, check tmp-storage-path config and make sure they are different.%   
```

Change to another user

```
➜  tidb git:(bugfix-executor-16694) su - mina            
Password:
mina@Qiannan-MBP tidb % ./bin/tidb-server
[2020/04/26 13:25:35.069 +12:00] [INFO] [printer.go:41] ["Welcome to TiDB."] ["Release Version"=v4.0.0-beta.2-353-g6c951dd79] ["Git Commit Hash"=6c951dd792786193c1e596868193c49e3ee13de2] ["Git Branch"=bugfix-executor-16694] ["UTC Build Time"="2020-04-26 01:19:36"] [GoVersion=go1.13.5] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
[2020/04/26 13:25:35.070 +12:00] [INFO] [printer.go:54] ["loaded config"] [config="{\"host\":\"0.0.0.0\",\"advertise-address\":\"0.0.0.0\",\"port\":4000,\"cors\":\"\",\"store\":\"mocktikv\",\"path\":\"/tmp/tidb\",\"socket\":\"\",\"lease\":\"45s\",\"run-ddl\":true,\"split-table\":true,\"token-limit\":1000,\"oom-use-tmp-storage\":true,\"tmp-storage-path\":\"/tmp/502_tidb/NDAwMC8xMDA4MA==/tmp-storage\",\"oom-action\":\"cancel\",\"mem-quota-query\":1073741824,\"tmp-storage-quota\":-1,\"enable-streaming\":false,\"enable-batch-dml\":false,\"lower-case-table-names\":2,\"server-version\":\"\",\"log\":{\"level\":\"info\",\"format\":\"text\",\"disable-timestamp\":null,\"enable-timestamp\":null,\"disable-error-stack\":null,\"enable-error-stack\":null,\"file\":{\"filename\":\"\",\"max-size\":300,\"max-days\":0,\"max-backups\":0},\"enable-slow-log\":true,\"slow-query-file\":\"tidb-slow.log\",\"slow-threshold\":300,\"expensive-threshold\":10000,\"query-log-max-len\":4096,\"record-plan-in-slow-log\":1},\"security\":{\"skip-grant-table\":false,\"ssl-ca\":\"\",\"ssl-cert\":\"\",\"ssl-key\":\"\",\"require-secure-transport\":false,\"cluster-ssl-ca\":\"\",\"cluster-ssl-cert\":\"\",\"cluster-ssl-key\":\"\",\"cluster-verify-cn\":null},\"status\":{\"status-host\":\"0.0.0.0\",\"metrics-addr\":\"\",\"status-port\":10080,\"metrics-interval\":15,\"report-status\":true,\"record-db-qps\":false},\"performance\":{\"max-procs\":0,\"max-memory\":0,\"stats-lease\":\"3s\",\"stmt-count-limit\":5000,\"feedback-probability\":0.05,\"query-feedback-limit\":1024,\"pseudo-estimate-ratio\":0.8,\"force-priority\":\"NO_PRIORITY\",\"bind-info-lease\":\"3s\",\"txn-total-size-limit\":104857600,\"tcp-keep-alive\":true,\"cross-join\":true,\"run-auto-analyze\":true,\"agg-push-down-join\":false,\"committer-concurrency\":16,\"max-txn-ttl\":600000},\"prepared-plan-cache\":{\"enabled\":false,\"capacity\":100,\"memory-guard-ratio\":0.1},\"opentracing\":{\"enable\":false,\"rpc-metrics\":false,\"sampler\":{\"type\":\"const\",\"param\":1,\"sampling-server-url\":\"\",\"max-operations\":0,\"sampling-refresh-interval\":0},\"reporter\":{\"queue-size\":0,\"buffer-flush-interval\":0,\"log-spans\":false,\"local-agent-host-port\":\"\"}},\"proxy-protocol\":{\"networks\":\"\",\"header-timeout\":5},\"tikv-client\":{\"grpc-connection-count\":4,\"grpc-keepalive-time\":10,\"grpc-keepalive-timeout\":3,\"commit-timeout\":\"41s\",\"max-batch-size\":128,\"overload-threshold\":200,\"max-batch-wait-time\":0,\"batch-wait-size\":8,\"enable-chunk-rpc\":true,\"region-cache-ttl\":600,\"store-limit\":0,\"copr-cache\":{\"enabled\":true,\"capacity-mb\":1000,\"admission-max-result-mb\":10,\"admission-min-process-ms\":5}},\"binlog\":{\"enable\":false,\"ignore-error\":false,\"write-timeout\":\"15s\",\"binlog-socket\":\"\",\"strategy\":\"range\"},\"compatible-kill-query\":false,\"plugin\":{\"dir\":\"\",\"load\":\"\"},\"pessimistic-txn\":{\"enable\":true,\"max-retry-count\":256},\"check-mb4-value-in-utf8\":true,\"max-index-length\":3072,\"alter-primary-key\":false,\"treat-old-version-utf8-as-utf8mb4\":true,\"enable-table-lock\":false,\"delay-clean-table-lock\":0,\"split-region-max-num\":1000,\"stmt-summary\":{\"enable\":true,\"enable-internal-query\":false,\"max-stmt-count\":200,\"max-sql-length\":4096,\"refresh-interval\":1800,\"history-size\":24},\"repair-mode\":false,\"repair-table-list\":[],\"isolation-read\":{\"engines\":[\"tikv\",\"tiflash\",\"tidb\"]},\"max-server-connections\":0,\"new_collations_enabled_on_first_bootstrap\":false,\"experimental\":{\"allow-auto-random\":false,\"allow-expression-index\":false},\"enable-collect-execution-info\":false}"]
[2020/04/26 13:25:35.070 +12:00] [INFO] [main.go:341] ["disable Prometheus push client"]
[2020/04/26 13:25:35.070 +12:00] [INFO] [store.go:68] ["new store"] [path=mocktikv:///tmp/tidb]
[2020/04/26 13:25:35.070 +12:00] [INFO] [systime_mon.go:25] ["start system time monitor"]

```

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -143,7 +144,7 @@ func (c *Config) UpdateTempStoragePath() {
 
 func encodeDefTempStorageDir(port, statusPort uint) string {
 	dirName := base64.URLEncoding.EncodeToString([]byte(fmt.Sprintf("%v/%v", port, statusPort)))
```
Comment (SunRunAway) [inline config/config.go:146]: It's better to add host here, because different tidb can listen to addresses on the same port but different hostnames(like 127.0.0.1:4000/10080 and 172.16.5.1:4000/10080).
```suggestion
	dirName := base64.URLEncoding.EncodeToString([]byte(fmt.Sprintf("%v:%v/%v:%v", host, port, statusHost, statusPort)))
```

File: config/config.go [hunk 2]
```diff
@@ -143,7 +144,7 @@ func (c *Config) UpdateTempStoragePath() {
...
-	return filepath.Join(os.TempDir(), "tidb", dirName, "tmp-storage")
+	return filepath.Join(os.TempDir(), strconv.Itoa(os.Getuid())+"_tidb", dirName, "tmp-storage")
```
Comment (SunRunAway) [inline config/config.go:147]: `os.Getuid()` returns -1 on Windows, see https://golang.org/pkg/os/#Getuid. An alternative try is `os/user.Current()`, and it's better to add a test case for `encodeDefTempStorageDir` and cover it in both platform.

**Comment by SunRunAway** [comment]
Need to update documentation after this PR gets merged.

**Comment by hsqlu** [comment]
@SunRunAway  PTAL

**Comment by SunRunAway** [comment]
Hi, @hsqlu Almost LGTM.
Would you like to fix the error message problem, see https://github.com/pingcap/tidb/issues/16694#issuecomment-617756688

**Comment by hsqlu** [comment]
@SunRunAway fixed. PTAL

File: config/config.go [hunk 3]
```diff
@@ -137,13 +138,20 @@ type Config struct {
...
 	}
 }
 
-func encodeDefTempStorageDir(port, statusPort uint) string {
-	dirName := base64.URLEncoding.EncodeToString([]byte(fmt.Sprintf("%v/%v", port, statusPort)))
-	return filepath.Join(os.TempDir(), "tidb", dirName, "tmp-storage")
+func encodeDefTempStorageDir(host, statusHost string, port, statusPort uint) string {
+	dirName := base64.URLEncoding.EncodeToString([]byte(fmt.Sprintf("%v:%v/%v:%v", host, port, statusHost, statusPort)))
+	var osUID string
+	currentUser, err := user.Current()
```
Comment (HunDunDM) [inline config/config.go:148]: Would it be better to use `os.Getuid()`?

Comment (hsqlu) [reply config/config.go:148]: os.Getuid() will return -1 on window, that's why changed it to os/user.

Comment (hsqlu) [reply config/config.go:154]: @HunDunDM PTAL.

**Comment by zz-jason** [comment]
@SunRunAway do we need to cherry-pick this PR to release-4.0?

**Comment by SunRunAway** [comment]
Hi @hsqlu ,
Would you like to help update the documentation on https://github.com/pingcap/docs-cn and https://github.com/pingcap/docs?

**Comment by hsqlu** [comment]
> Hi @hsqlu ,
> Would you like to help update the documentation on https://github.com/pingcap/docs-cn and https://github.com/pingcap/docs?

Sure, I can do it
