### PR TITLE
planner: fix that vector index output empty result when pk is non-int type

### LINKED ISSUE #57627: vector index on clutstered non-int pk table might output empty result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `chunks_1_backup` (
  `id` char(32) NOT NULL,
  `hash` varchar(64) NOT NULL,
  `text` text DEFAULT NULL,
  `meta` json DEFAULT NULL,
  `embedding` vector(1536) DEFAULT NULL COMMENT 'hnsw(distance=cosine)',
  `document_id` int DEFAULT NULL,
  `relations` json DEFAULT NULL,
  `source_uri` varchar(512) DEFAULT NULL,
  `index_status` enum('NOT_STARTED','PENDING','RUNNING','COMPLETED','FAILED') NOT NULL,
  `index_result` text DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_1` (`document_id`),
  KEY `ix_chunks_1_id` (`id`),
  VECTOR INDEX `vec_idx_embedding`((VEC_COSINE_DISTANCE(`embedding`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

Insert some data.

Run SQL like `select ... from chunks_1_backup order by VEC_COSINE_DISTANCE(embedding, const) limit 10`

### 2. What did you expect to see? (Required)

Should output valid result.

### 3. What did you see instead (Required)

empty result.

### 4. What is your TiDB version? (Required)

current master

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #57627 

Problem Summary:

### What changed and how does it work?

When pk is clustered and non-int, the full range should be `[MinNotNull, MaxValue]`. But it's `[MinInt64, MaxInt64]` currently. So it will output an empty result.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/find_best_task.go [hunk 1]
```diff
@@ -761,6 +761,19 @@ func compareCandidates(sctx base.PlanContext, prop *property.PhysicalProperty, l
...
+		}
+		if ds.TableInfo.Columns[path.Index.Columns[0].Offset].ID != prop.VectorProp.Column.ID {
+			return false
+		}
+
+		if model.IndexableFnNameToDistanceMetric[prop.VectorProp.DistanceFnName.L] != path.Index.VectorInfo.DistanceMetric {
+			return false
+		}
+		return true
+	}
```
Comment (winoros) [inline pkg/planner/core/find_best_task.go:776]: I changed it to the highest priority.
Because when for the vector index path, the `IsIntHandlePath` can also be true. We need to use a new way to check the real pk path.

File: pkg/planner/core/planbuilder.go [hunk 2]
```diff
@@ -1191,15 +1191,19 @@ func getPossibleAccessPaths(ctx base.PlanContext, tableHints *hint.PlanHints, in
...
 				}
 			}
-			path := &util.AccessPath{Index: index}
 			if index.VectorInfo != nil {
 				// Because the value of `TiFlashReplica.Available` changes as the user modify replica, it is not ideal if the state of index changes accordingly.
 				// So the current way to use the vector indexes is to require the TiFlash Replica to be available.
 				if !tblInfo.TiFlashReplica.Available {
 					continue
 				}
+				path := genTiFlashPath(tblInfo)
```
Comment (zimulala) [inline pkg/planner/core/planbuilder.go:1200]: I feel that the original logic is different here set up "tablePath. IsCommonHandlePath = true". What does this setting do?  Why is the original logic not needed？

Comment (winoros) [reply pkg/planner/core/planbuilder.go:1202]: A normal index will create the index's ranges.
But the vector index still uses the table range. So we need to correctly set the pk type. So it can generate the correct table range.
For int pk, it will use `[MinInt64, MaxInt64`] as full range. But for other cases, `[MinNotNull, MaxValue]` will be full range.

Comment (AilinKid) [reply pkg/planner/core/planbuilder.go:1202]: image
i think if we don't set it here, we will step into here right? which will derive a int range for common handle tiflash path

File: pkg/planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -5502,7 +5502,10 @@ func (b *PlanBuilder) buildUpdate(ctx context.Context, update *ast.UpdateStmt) (
 		if dbName == "" {
 			dbName = b.ctx.GetSessionVars().CurrentDB
 		}
-		b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SelectPriv, dbName, t.Name.L, "", nil)
+		// Avoid adding CTE table to the SELECT privilege list, maybe we have better way to do this?
+		if _, ok := b.nameMapCTE[t.Name.L]; !ok {
+			b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SelectPriv, dbName, t.Name.L, "", nil)
+		}
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go:5508]: why should we need this for? any direct effect from the issue?

**Review by AilinKid — APPROVED** [review]

**Review by breezewish — APPROVED** [review]
