### PR TITLE
ddl: do change column data when binary to binary with different length

### LINKED ISSUE #3644: `length` result is wrong after modify column length
## Description
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
create table t(a int, b binary(22));
insert into t set b='test';
alter table t modify b binary(33);
insert into t set b='test1';
select length(b) from t;
```

2. What did you expect to see?
```
+-----------+
| length(b) |
+-----------+
|        33 |
|        33 |
+-----------+
```

3. What did you see instead?
```
+-----------+
| length(b) |
+-----------+
|        22 |
|        33 |
+-----------+
```

4. What version of TiDB are you using (`tidb-server -V`)?

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by LENSHOOD**
### What problem does this PR solve?

Issue Number: close #3644 

Problem Summary:
1. Column change with binary to binary should be disallowed when `tidb_enable_change_column_type = 0`
2. When modify column from binary to binary with flag `tidb_enable_change_column_type = 1`, then no matter the new binary length is great or less than the original one, change column data should be performed.

### What is changed and how it works?
What's Changed:
1. Need reorg when alter binary - binary with different length.
2. Change column data when alter binary - binary with different length.

### Check List 

Tests 
- Integration test

### Release note 

- Change column data when alter binary to binary with different length

### CODE REVIEW

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

**Review by wjhuang2016 — COMMENTED** [review]
we plan to remove tidb_enable_change_column_type, after the column type change is GA, we can support it directly.

**Comment by LENSHOOD** [comment]
> we plan to remove tidb_enable_change_column_type, after the column type change is GA, we can support it directly.

right, then the only difference would be need to do reorg when `binary` expand.

File: ddl/column.go [hunk 1]
```diff
@@ -708,6 +708,11 @@ func needChangeColumnData(oldCol, newCol *model.ColumnInfo) bool {
 			return isElemsChangedToModifyColumn(oldCol.Elems, newCol.Elems)
 		case mysql.TypeTiny, mysql.TypeShort, mysql.TypeInt24, mysql.TypeLong, mysql.TypeLonglong:
 			return toUnsigned != originUnsigned
+		case mysql.TypeString:
```
Comment (AilinKid) [inline ddl/column.go:711]: Maybe it isn't limited to TypeString?
should the below be right?
```
default:
    types.IsString(colDef.Tp.Tp) && mysql.HasBinaryFlag(colDef.Tp.Flag)
    ...
```

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -3547,8 +3547,16 @@ func needReorgToChange(origin *types.FieldType, to *types.FieldType) (needOreg b
...
 
-	if toFlen > 0 && toFlen < originFlen {
-		return true, fmt.Sprintf("length %d is less than origin %d", toFlen, originFlen)
+	if toFlen > 0 && toFlen != originFlen {
+		if toFlen < originFlen {
+			return true, fmt.Sprintf("length %d is less than origin %d", toFlen, originFlen)
+		}
+
+		// Due to the behavior of padding \x00 at binary type, we need to reorg when binary length changed
+		isBinaryChar := func(tp *types.FieldType) bool { return tp.Tp == mysql.TypeString && mysql.HasBinaryFlag(tp.Flag) }
```
Comment (AilinKid) [inline ddl/ddl_api.go:3556]: ditto:  types.IsString(colDef.Tp.Tp) && mysql.HasBinaryFlag(colDef.Tp.Flag)

File: ddl/db_test.go [hunk 3]
```diff
@@ -4096,21 +4096,57 @@ func (s *testSerialDBSuite) TestModifyColumnBetweenStringTypes(c *C) {
...
+
+	// binary to binary
+	tk.MustExec("drop table if exists tt;")
+	tk.MustExec("create table tt (a binary(10));")
+	tk.MustExec("insert into tt values ('111'),('10000');")
+	tk.MustGetErrMsg("alter table tt change a a binary(5);", "[types:1406]Data Too Long, field len 5, data len 10")
+	mb := getModifyColumn(c, s.s.(sessionctx.Context), "test", "tt", "a", false)
+	c.Assert(mb.FieldType.Flen, Equals, 10)
+	tk.MustQuery("select * from tt").Check(testkit.Rows("111\x00\x00\x00\x00\x00\x00\x00", "10000\x00\x00\x00\x00\x00"))
+	tk.MustGetErrMsg("alter table tt change a a binary(4);", "[types:1406]Data Too Long, field len 4, data len 10")
```
Comment (AilinKid) [inline ddl/db_test.go:4126]: we can add more tests, for example, blob type which is also binary string; char type too.

File: ddl/column.go (hunk 1 above)
Comment (AilinKid) [reply ddl/column.go:711]: sorry, I'm wrong, I found that MySQL won't change the length for blob/text/char/varchar, seems only for binary(x)?

Comment (AilinKid) [reply ddl/column.go:711]: I think you can use this condition for if statement: 
refer it in castvalue function:
if tp.Tp == mysql.TypeString && IsBinaryStr(tp) && len(s) < flen && padZero {

File: ddl/db_test.go (hunk 3 above)
Comment (AilinKid) [reply ddl/db_test.go:4126]: mysql> alter table t modify b char(55) binary;
Query OK, 0 rows affected, 1 warning (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 1

However, in MySQL the length won't change during alter `binary(22)` to `char(33) binary`

Comment (LENSHOOD) [reply ddl/db_test.go:4126]: This behavior of MySQL is reasonable. 

`char(33) binary` defines the collation to "_bin", the ordering/comparison behavior may changed, but `char` alway right-padded with spaces to the specified length according to [here](https://dev.mysql.com/doc/refman/8.0/en/char.html).  So length is not influenced by collation. (BTW, `char(33) binary` become ambiguous since MySQL 8.0 [provide two `_bin` collations to `utf8mb4`](https://dev.mysql.com/doc/refman/8.0/en/string-type-syntax.html))

For the `char` type, the retrieved value would keep the trailing spaces only if ` SQL_MODE contains PAD_CHAR_TO_FULL_LENGTH`, which is disable at default. That's why `Length()` result not changed. (On the contrary, `binary` padding with 0x00 and always keep the padding bytes at retrieve, so the 0x00 can be count at `Length()`)

If we add `PAD_CHAR_TO_FULL_LENGTH` to sql_mode,  execute `alter table t modify b char(33) binary;`, we can get `length = 33`.

---
But when it comes to TiDB, column change to different charset still unsupported now. So I think maybe it's better to add such tests along with the feature development.

File: ddl/column.go (hunk 1 above)
Comment (LENSHOOD) [reply ddl/column.go:711]: Yes, `IsBinaryStr(tp)` seems more clear in semantic.

File: ddl/column.go [hunk 4]
```diff
@@ -708,6 +708,11 @@ func needChangeColumnData(oldCol, newCol *model.ColumnInfo) bool {
...
+			// Due to the behavior of padding \x00 at binary type, always change column data when binary length changed
+			if types.IsBinaryStr(&oldCol.FieldType) {
```
Comment (wjhuang2016) [inline ddl/column.go:713]: varbinary doesn't have padding \x00

**Comment by wjhuang2016** [comment]
@LENSHOOD Could you update this PR?

**Comment by LENSHOOD** [comment]
> @LENSHOOD Could you update this PR?

I've missed your last comment about "varbinary" !
Sorry about that.

Anyway, varbinary doesn't have to add padding, indeed. 

But due to the varbinary 's `FieldType.Tp == 15 (TypeVarchar)` and binary's `FieldType.Tp == 0xfe (TypeString)`, so check varbinary will never goes into the `if types.IsBinaryStr(&oldCol.FieldType) {...` logic. 

(am I understand you comment correctly?)

**Comment by wjhuang2016** [comment]
> > @LENSHOOD Could you update this PR?
> 
> I've missed your last comment about "varbinary" !
> Sorry about that.
> 
> Anyway, varbinary doesn't have to add padding, indeed.
> 
> But due to the varbinary 's `FieldType.Tp == 15 (TypeVarchar)` and binary's `FieldType.Tp == 0xfe (TypeString)`, so check varbinary will never goes into the `if types.IsBinaryStr(&oldCol.FieldType) {...` logic.
> 
> (am I understand you comment correctly?)

Okay, I check it and it's expected.

**Review by wjhuang2016 — APPROVED** [review]

File: ddl/db_test.go (hunk 3 above)
Comment (AilinKid) [reply ddl/db_test.go:4240]: Every Impressive, thanks LENSHOOD

**Review by AilinKid — APPROVED** [review]
LGTM

**Comment by AilinKid** [comment]
Since it's not a critical bug, or user requirements, we will not cherry-pick it release 5.1

**Comment by LENSHOOD** [comment]
@AilinKid @wjhuang2016 
Thanks for review!

**Comment by zhouqiang-cl** [comment]
This pr break integration tests https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/5633/
```
"run test [alter_table1] err: sql:SELECT HEX(s) FROM t1;: failed to run query \n\"SELECT HEX(s) FROM t1;\" \n around line 169, \nwe need(51):\nSELECT HEX(s) FROM t1;\nHEX(s)\n7465737400000000\nSELE\nbut got(51):\nSELECT HEX(s) FROM t1;\nHEX(s)\n74657374000000000000\n\n"
```

**Comment by LENSHOOD** [comment]
> This pr break integration tests https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/5633/
> 
> ```
> "run test [alter_table1] err: sql:SELECT HEX(s) FROM t1;: failed to run query \n\"SELECT HEX(s) FROM t1;\" \n around line 169, \nwe need(51):\nSELECT HEX(s) FROM t1;\nHEX(s)\n7465737400000000\nSELE\nbut got(51):\nSELECT HEX(s) FROM t1;\nHEX(s)\n74657374000000000000\n\n"
> ```

Sorry, I cannot access the repo `tidb_ghpr_common_test`, so I may not able to find out what's going on with the error.😅
