### PR TITLE
br: increase the sleep time in the `waitForSend` function

### LINKED ISSUE #41210: flaky test TestRewriteRules
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
    batcher_test.go:326: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/execroot/__main__/bazel-out/k8-fastbuild/bin/br/pkg/restore/restore_test_/restore_test.runfiles/__main__/br/pkg/restore/batcher_test.go:326
        	Error:      	Should be true
        	Test:       	TestRewriteRules
```

### PR DESCRIPTION
**Pull request by Dousir9**
### What problem does this PR solve?

Issue Number: close #41210 

Problem Summary:

### What is changed and how it works?
When `Batcher.Len` reaches the threshold, it will call `asyncSend`, then call `Send` in `sendWorker`, and then call `RestoreBatch` to append `*ranges.RewriteRules` to `sender.rewriteRules`, the whole process may not be completed within 10ms, forming a flaky test(`require.True(t, sender.HasRewriteRuleOfKey("a"))` should be true, but false), so we need to increase the sleep time in the `waitForSend` function.
Note: `waitForSend` is only used for test.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Dousir9** [comment]
Please left the /ok-to-test command, thanks.

**Review by 3pointer — APPROVED** [review]

File: br/pkg/restore/batcher_test.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func (sender *drySender) Close() {
 }
 
 func waitForSend() {
-	time.Sleep(10 * time.Millisecond)
+	time.Sleep(50 * time.Millisecond)
```
Comment (hawkingrei) [inline br/pkg/restore/batcher_test.go:52]: Do we need to set 50ms in the production and set 10ms in the test？ I am afraid that Too long timeout will affect CI.

Comment (hawkingrei) [reply br/pkg/restore/batcher_test.go:52]: @3pointer @lance6716 PTAL

Comment (Dousir9) [reply br/pkg/restore/batcher_test.go:52]: @hawkingrei The `waitForSend` will be called 4 times in total, compared with the cost of unit-test failure, I think the cost of increasing the sleep time is relatively small, but maybe we can double the sleep time, that is, 20ms.

Comment (Dousir9) [reply br/pkg/restore/batcher_test.go:52]: The `waitForSend` is only used for test.

**Review by YuJuncen — APPROVED** [review]
LGTM
