### PR TITLE
txn: fix `invalid transaction` error when doing stale read in RC isolation level

### LINKED ISSUE #30872: Stale read failed for read-committed isolation when autocommit=0
## Bug Report

Stale read failed for read-committed isolation

### 1. Minimal reproduce step (Required)

```
drop table if exists t1;
create table t1(id int primary key);
set tx_isolation = 'READ-COMMITTED';
set autocommit=0;
select * from t1 as of timestamp now() where id=1;
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t1 as of timestamp now() where id=1;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t1 as of timestamp now() where id=1;
ERROR 8024 (HY000): invalid transaction
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #30872

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix `invalid transaction` error when doing stale read in RC isolation level
```

### CODE REVIEW

File: executor/builder.go [hunk 1]
```diff
@@ -122,6 +122,7 @@ func newExecutorBuilder(ctx sessionctx.Context, is infoschema.InfoSchema, ti *Te
 		ctx:              ctx,
 		is:               is,
 		Ti:               ti,
+		snapshotTSCached: isStaleness,
```
Comment (MyonKeminta) [inline executor/builder.go:125]: I didn't understand. Where is the `snapshotTS` set in this case?

Comment (lcwangchao) [reply executor/builder.go:125]: for stale read `snapshotTS` is set when `executorBuilder` is constructed

Comment (lcwangchao) [reply executor/builder.go:125]: just under this line

**Review by Yisaer — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
