### PR TITLE
statistics: fix data race and error handling in stats load

### LINKED ISSUE #31237: DATA RACE in the ```statistics/handle```
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
WARNING: DATA RACE
Write at 0x00c00626b190 by goroutine 103:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:355 +0x0
  github.com/pingcap/tidb/statistics/handle.(*Handle).SyncWaitStatsLoad.func1()
      /go/tidb/statistics/handle/handle_hist.go:75 +0x6e
  github.com/pingcap/tidb/statistics/handle.(*Handle).SyncWaitStatsLoad()
      /go/tidb/statistics/handle/handle_hist.go:93 +0x45f
  github.com/pingcap/tidb/planner/core.SyncWaitStatsLoad()
      /go/tidb/planner/core/plan_stats.go:96 +0xe4
  github.com/pingcap/tidb/planner/core.syncWaitStatsLoadPoint.optimize()
      /go/tidb/planner/core/plan_stats.go:60 +0x97
  github.com/pingcap/tidb/planner/core.(*syncWaitStatsLoadPoint).optimize()
      <autogenerated>:1 +0x7c
  github.com/pingcap/tidb/planner/core.logicalOptimize()
      /go/tidb/planner/core/optimizer.go:429 +0x517
  github.com/pingcap/tidb/planner/core.DoOptimize()
      /go/tidb/planner/core/optimizer.go:273 +0xe9
  github.com/pingcap/tidb/planner.optimize()
      /go/tidb/planner/optimize.go:380 +0xb48
  github.com/pingcap/tidb/planner.Optimize()
      /go/tidb/planner/optimize.go:210 +0xa13
  github.com/pingcap/tidb/planner/core_test.(*testPlanStatsSuite).TestPlanStatsLoad()
      /go/tidb/planner/core/plan_stats_test.go:214 +0xd5e
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:625 +0x48
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xa54
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x12b
Previous read at 0x00c00626b190 by goroutine 219:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:158 +0x0
  github.com/pingcap/tidb/statistics/handle.(*Handle).finishWorking()
      /go/tidb/statistics/handle/handle_hist.go:372 +0x204
  github.com/pingcap/tidb/statistics/handle.(*Handle).handleOneTask()
      /go/tidb/statistics/handle/handle_hist.go:209 +0x6b1
  github.com/pingcap/tidb/statistics/handle.(*Handle).SubLoadWorker()
      /go/tidb/statistics/handle/handle_hist.go:151 +0x184
  github.com/pingcap/tidb/domain.(*Domain).StartLoadStatsSubWorkers·dwrap·22()
      /go/tidb/domain/domain.go:1305 +0x71
Goroutine 103 (running) created at:
  github.com/pingcap/check.(*suiteRunner).forkCall()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x5e4
  github.com/pingcap/check.(*suiteRunner).forkTest()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x164
  github.com/pingcap/check.(*suiteRunner).doRun()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x1fa
  github.com/pingcap/check.(*suiteRunner).run()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0xe5
  github.com/pingcap/check.Run()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x49
  github.com/pingcap/check.RunAll()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:113 +0x757
  github.com/pingcap/check.TestingT()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x664
  github.com/pingcap/tidb/planner/core.TestT()
      /go/tidb/planner/core/logical_plan_test.go:47 +0x44
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Goroutine 219 (running) created at:
  github.com/pingcap/tidb/domain.(*Domain).StartLoadStatsSubWorkers()
      /go/tidb/domain/domain.go:1305 +0x298
  github.com/pingcap/tidb/session.BootstrapSession()
      /go/tidb/session/session.go:2720 +0xd84
  github.com/pingcap/tidb/planner/core_test.newStoreWithBootstrap()
      /go/tidb/planner/core/cbo_test.go:618 +0x76
  github.com/pingcap/tidb/planner/core_test.(*testPlanStatsSuite).TestPlanStatsLoad()
      /go/tidb/planner/core/plan_stats_test.go:50 +0x79
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:625 +0x48
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:339 +0xd7
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xa54
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/prow/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x12b 
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by chrysan**
### What problem does this PR solve?

Issue Number: close #31237 

Problem Summary:
This is targeted to fix the data race of writing & closing resultCh and incorrect error handling when paniked in finishWorking:
[2021-12-31T07:38:58.006Z] [2021/12/31 15:28:48.957 +08:00] [ERROR] [handle_hist.go:172] ["stats loading panicked"] [stack="goroutine 4028 [running]:\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).handleOneTask.func1()\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle_hist.go:170 +0xa9\npanic(0x3c3f3c0, 0x4607ad0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).finishWorking(0xc02ec24b40, 0x3d, 0x4)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle_hist.go:372 +0x106\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).handleOneTask(0xc02ec24b40, 0xc04fd5df58, 0x7fc65c59dcf8, 0xc02e0df800, 0xc02d5310e0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle_hist.go:209 +0x6d4\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).SubLoadWorker(0xc02ec24b40, 0x46f2848, 0xc02e0df800, 0xc02d5310e0, 0xc02e4a6488)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle_hist.go:151 +0x125\ncreated by github.com/pingcap/tidb/domain.(*Domain).StartLoadStatsSubWorkers\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:1305 +0x12b\n"]

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: statistics/handle/handle_hist.go [hunk 1]
```diff
@@ -147,70 +148,78 @@ func (h *Handle) SubLoadWorker(ctx sessionctx.Context, exit chan struct{}, exitW
...
 				continue
 			}
 		}
 	}
 }
 
-// handleOneTask handles one column task.
-func (h *Handle) handleOneTask(readerCtx *statsReaderContext, ctx sqlexec.RestrictedSQLExecutor, exit chan struct{}) (err error) {
+// HandleOneTask handles one column task.
+func (h *Handle) HandleOneTask(lastTask *NeededColumnTask, readerCtx *StatsReaderContext, ctx sqlexec.RestrictedSQLExecutor, exit chan struct{}) (task *NeededColumnTask, err error) {
```
Comment (winoros) [inline statistics/handle/handle_hist.go:168]: We can add some comments about the `lastTask`

File: statistics/handle/handle_hist.go [hunk 2]
```diff
@@ -147,70 +148,78 @@ func (h *Handle) SubLoadWorker(ctx sessionctx.Context, exit chan struct{}, exitW
...
-		if err != errExit {
-			logutil.BgLogger().Error("Fail to drain task for stats loading.", zap.Error(err))
+	if lastTask == nil {
+		task, err = h.drainColTask(exit)
+		if err != nil {
+			if err != errExit {
+				logutil.BgLogger().Error("Fail to drain task for stats loading.", zap.Error(err))
+			}
+			return task, err
 		}
```
Comment (winoros) [inline statistics/handle/handle_hist.go:186]: The `drainColTask` would not meet the case that both error and task is not nil?

File: statistics/handle/handle_hist.go [hunk 3]
```diff
@@ -330,6 +345,22 @@ func (h *Handle) writeToChanWithTimeout(taskCh chan *NeededColumnTask, task *Nee
...
+// writeToResultChan safe-writes with panic-recover so one write-fail will not have big impact.
+func (h *Handle) writeToResultChan(resultCh chan model.TableColumnID, rs model.TableColumnID) {
+	defer func() {
+		if r := recover(); r != nil {
+			buf := make([]byte, 4096)
+			stackSize := runtime.Stack(buf, false)
+			buf = buf[:stackSize]
+			logutil.BgLogger().Error("writeToResultChan panicked", zap.Any("error", r), zap.String("stack", string(buf)))
+		}
+	}()
```
Comment (winoros) [inline statistics/handle/handle_hist.go:357]: What kinds of panic will be caught here?

File: statistics/handle/handle_hist.go [hunk 4]
```diff
@@ -353,24 +384,29 @@ func (h *Handle) updateCachedColumn(col model.TableColumnID, colHist *statistics
 func (h *Handle) setWorking(col model.TableColumnID, resultCh chan model.TableColumnID) bool {
 	h.StatsLoad.Lock()
 	defer h.StatsLoad.Unlock()
-	chList, ok := h.StatsLoad.workingColMap[col]
+	chList, ok := h.StatsLoad.WorkingColMap[col]
 	if ok {
-		h.StatsLoad.workingColMap[col] = append(chList, resultCh)
+		if chList[0] == resultCh {
+			return true
+		}
```
Comment (winoros) [inline statistics/handle/handle_hist.go:391]: Why we added this checking?

File: statistics/handle/handle_hist.go [hunk 5]
```diff
@@ -54,7 +55,7 @@ func (h *Handle) SendLoadRequests(sc *stmtctx.StatementContext, neededColumns []
 	}
 	sc.StatsLoad.Timeout = timeout
 	sc.StatsLoad.NeededColumns = missingColumns
-	sc.StatsLoad.ResultCh = make(chan model.TableColumnID, len(neededColumns))
+	sc.StatsLoad.ResultCh = make(chan model.TableColumnID, len(missingColumns))
```
[the remark this answers is not in the document]
Comment (chrysan) [reply statistics/handle/handle_hist.go:58]: No, len(missingColumns) could be smaller than len(neededColumns) if the data of column is already there in statsCache.

File: statistics/handle/handle_hist.go [hunk 6]
```diff
@@ -147,70 +148,78 @@ func (h *Handle) SubLoadWorker(ctx sessionctx.Context, exit chan struct{}, exitW
...
-		err := h.handleOneTask(readerCtx, ctx.(sqlexec.RestrictedSQLExecutor), exit)
+		task, err := h.HandleOneTask(lastTask, readerCtx, ctx.(sqlexec.RestrictedSQLExecutor), exit)
+		lastTask = task
 		if err != nil {
 			switch err {
 			case errExit:
 				return
 			default:
-				time.Sleep(10 * time.Millisecond)
+				time.Sleep(h.Lease() / 10)
```
[the remark this answers is not in the document]
Comment (chrysan) [reply statistics/handle/handle_hist.go:160]: Yes... there's no any criteria for setting this time...just to remove hard-coded time and align with lease. And I think usually some connection retry time should be larger than 10ms...

File: statistics/handle/handle_hist.go (hunk 1 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:168]: Will do it.

File: statistics/handle/handle_hist.go (hunk 2 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:186]: The implementation of drainColTask promises that it will not return a task together with error. Let me add more comments.

File: statistics/handle/handle_hist.go (hunk 3 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:357]: Since channel closing is removed, I think no. But still add recover here in case any accident which is out of our understanding about go channel... Because we are writing to multiple resultCh of multiple SQLs at the same time, panic of one should not impact others.

File: statistics/handle/handle_hist.go (hunk 4 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:391]: The worker taking the loading work is at the head of the list, should not append duplicatedly. If append duplicatedly, there will be duplicated messages in resultCh.

File: statistics/handle/handle_hist.go (hunk 1 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:169]: Done

File: statistics/handle/handle_hist.go (hunk 2 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:187]: Done

File: statistics/handle/handle_hist.go (hunk 4 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go]: Add a comment here.

**Review by winoros — APPROVED** [review]

File: statistics/handle/handle_hist_test.go [hunk 7]
```diff
@@ -66,54 +67,56 @@ func (s *testLoadHistSuite) TestConcurrentLoadHist(c *C) {
...
-		s.do.StatsHandle().SetLease(oriLease)
+		dom.StatsHandle().SetLease(oriLease)
 	}()
 	testKit.MustExec("analyze table t")
 
-	is := s.do.InfoSchema()
+	is := dom.InfoSchema()
 	tbl, err := is.TableByName(model.NewCIStr("test"), model.NewCIStr("t"))
-	c.Assert(err, IsNil)
+	require.Nil(t, err)
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:98]: use ```require.NoError```

File: statistics/handle/handle_hist_test.go [hunk 8]
```diff
@@ -15,49 +15,50 @@
...
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:52]: use ```require.NoError```.

File: statistics/handle/handle_hist_test.go [hunk 9]
```diff
@@ -124,5 +127,114 @@ func (s *testLoadHistSuite) TestConcurrentLoadHistTimeout(c *C) {
...
+	oriLease := dom.StatsHandle().Lease()
+	dom.StatsHandle().SetLease(1)
+	defer func() {
+		dom.StatsHandle().SetLease(oriLease)
+	}()
+	testKit.MustExec("analyze table t")
+
+	is := dom.InfoSchema()
+	tbl, err := is.TableByName(model.NewCIStr("test"), model.NewCIStr("t"))
+	require.Nil(t, err)
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:158]: Ditto

File: statistics/handle/handle_hist_test.go [hunk 10]
```diff
@@ -124,5 +127,114 @@ func (s *testLoadHistSuite) TestConcurrentLoadHistTimeout(c *C) {
...
+		h.SendLoadRequests(stmtCtx1, neededColumns, timeout)
+		stmtCtx2 := &stmtctx.StatementContext{}
+		h.SendLoadRequests(stmtCtx2, neededColumns, timeout)
+
+		readerCtx := &handle.StatsReaderContext{}
+		exitCh := make(chan struct{})
+		require.NoError(t, failpoint.Enable(fp.failPath, fp.inTerms))
+
+		task1, err1 := h.HandleOneTask(nil, readerCtx, testKit.Session().(sqlexec.RestrictedSQLExecutor), exitCh)
+		require.NotNil(t, err1)
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:205]: Ditto

File: statistics/handle/handle_hist_test.go [hunk 11]
```diff
@@ -124,5 +127,114 @@ func (s *testLoadHistSuite) TestConcurrentLoadHistTimeout(c *C) {
...
+		require.NotNil(t, task1)
+		list, ok := h.StatsLoad.WorkingColMap[neededColumns[0]]
+		require.True(t, ok)
+		require.Equal(t, 1, len(list))
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:209]: use ```require.Len```

File: statistics/handle/handle_hist_test.go [hunk 12]
```diff
@@ -124,5 +127,114 @@ func (s *testLoadHistSuite) TestConcurrentLoadHistTimeout(c *C) {
...
+		require.Equal(t, stmtCtx1.StatsLoad.ResultCh, list[0])
+
+		task2, err2 := h.HandleOneTask(nil, readerCtx, testKit.Session().(sqlexec.RestrictedSQLExecutor), exitCh)
+		require.Nil(t, err2)
+		require.Nil(t, task2)
+		list, ok = h.StatsLoad.WorkingColMap[neededColumns[0]]
+		require.True(t, ok)
+		require.Equal(t, 2, len(list))
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:217]: Ditto

File: statistics/handle/handle_hist_test.go [hunk 13]
```diff
@@ -124,5 +127,114 @@ func (s *testLoadHistSuite) TestConcurrentLoadHistTimeout(c *C) {
...
+		require.Equal(t, stmtCtx2.StatsLoad.ResultCh, list[1])
+
+		require.NoError(t, failpoint.Disable(fp.failPath))
+		task3, err3 := h.HandleOneTask(task1, readerCtx, testKit.Session().(sqlexec.RestrictedSQLExecutor), exitCh)
+		require.Nil(t, err3)
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:222]: Ditto

File: statistics/handle/handle_hist_test.go [hunk 14]
```diff
@@ -124,5 +127,114 @@ func (s *testLoadHistSuite) TestConcurrentLoadHistTimeout(c *C) {
...
+		require.Nil(t, task3)
+
+		require.Equal(t, 1, len(stmtCtx1.StatsLoad.ResultCh))
+		require.Equal(t, 1, len(stmtCtx2.StatsLoad.ResultCh))
```
Comment (hawkingrei) [inline statistics/handle/handle_hist_test.go:226]: Ditto

Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

File: statistics/handle/handle_hist_test.go (hunk 13 above)
Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

File: statistics/handle/handle_hist_test.go (hunk 12 above)
Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

File: statistics/handle/handle_hist_test.go (hunk 11 above)
Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

File: statistics/handle/handle_hist_test.go (hunk 10 above)
Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

File: statistics/handle/handle_hist_test.go (hunk 9 above)
Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

File: statistics/handle/handle_hist_test.go (hunk 8 above)
Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

File: statistics/handle/handle_hist_test.go (hunk 7 above)
Comment (chrysan) [reply statistics/handle/handle_hist_test.go]: Done

**Comment by hawkingrei** [comment]
@xuyifangreeneyes @qw4990 PTAL

File: planner/core/plan_stats_test.go [hunk 15]
```diff
@@ -43,7 +43,7 @@ func TestPlanStatsLoad(t *testing.T) {
 	tk.MustExec("drop table if exists t")
 	tk.MustExec("set @@session.tidb_analyze_version=2")
 	tk.MustExec("set @@session.tidb_partition_prune_mode = 'static'")
-	tk.MustExec("set @@session.tidb_stats_load_sync_wait =9999999")
```
Comment (xuyifangreeneyes) [inline planner/core/plan_stats_test.go:46]: Why do we modify the value? Does that mean the loading time is usually less than 1 min in the test cases so `60000` is enough.

Comment (chrysan) [reply planner/core/plan_stats_test.go:46]: Yes, if there's anything wrong, waiting for 60s is enough to fail this sql.

File: statistics/handle/handle_hist.go [hunk 16]
```diff
@@ -147,70 +148,79 @@ func (h *Handle) SubLoadWorker(ctx sessionctx.Context, exit chan struct{}, exitW
...
 				continue
 			}
 		}
 	}
 }
 
-// handleOneTask handles one column task.
-func (h *Handle) handleOneTask(readerCtx *statsReaderContext, ctx sqlexec.RestrictedSQLExecutor, exit chan struct{}) (err error) {
+// HandleOneTask handles one column task.
+func (h *Handle) HandleOneTask(lastTask *NeededColumnTask, readerCtx *StatsReaderContext, ctx sqlexec.RestrictedSQLExecutor, exit chan struct{}) (task *NeededColumnTask, err error) {
```
Comment (xuyifangreeneyes) [inline statistics/handle/handle_hist.go:169]: Maybe we can also comment here that the first return value is the current failed task and will be nil if the current task is finished successfully.

File: statistics/handle/handle_hist.go [hunk 17]
```diff
@@ -330,6 +346,22 @@ func (h *Handle) writeToChanWithTimeout(taskCh chan *NeededColumnTask, task *Nee
...
+		if r := recover(); r != nil {
+			buf := make([]byte, 4096)
+			stackSize := runtime.Stack(buf, false)
+			buf = buf[:stackSize]
+			logutil.BgLogger().Error("writeToResultChan panicked", zap.Any("error", r), zap.String("stack", string(buf)))
+		}
+	}()
+	select {
+	case resultCh <- rs:
+	default:
```
Comment (xuyifangreeneyes) [inline statistics/handle/handle_hist.go:361]: Here we make the sending non-blocking. Do we try to avoid certain blocking case? The result channel seems have enough buffer.

File: statistics/handle/handle_hist.go [hunk 18]
```diff
@@ -353,24 +385,29 @@ func (h *Handle) updateCachedColumn(col model.TableColumnID, colHist *statistics
 func (h *Handle) setWorking(col model.TableColumnID, resultCh chan model.TableColumnID) bool {
 	h.StatsLoad.Lock()
 	defer h.StatsLoad.Unlock()
-	chList, ok := h.StatsLoad.workingColMap[col]
+	chList, ok := h.StatsLoad.WorkingColMap[col]
 	if ok {
-		h.StatsLoad.workingColMap[col] = append(chList, resultCh)
+		if chList[0] == resultCh {
+			return true // just return for duplicate setWorking
```
Comment (xuyifangreeneyes) [inline statistics/handle/handle_hist.go:391]: Here is to handle the case when reading column stats failed in the last task and the subLoadWorker tries it again? (Corresponding to the old line 202 `h.StatsLoad.NeededColumnsCh <- task` is deleted) 

So we can make sure that `col` in `WorkingColMap` is set by the current subLoadWorker when handling the last task rather than some other subLoadWorker which might also load `col`'s stats, right?

Comment (chrysan) [reply statistics/handle/handle_hist.go:391]: yes

File: statistics/handle/handle_hist.go (hunk 17 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:361]: The result channel seems have enough buffer.  -- yes, but sending in a safe way so that it won't impact other sqls' tasks if any edge case is missed.

File: statistics/handle/handle_hist.go (hunk 16 above)
Comment (chrysan) [reply statistics/handle/handle_hist.go:169]: OK

**Review by xuyifangreeneyes — APPROVED** [review]
LGTM
