### PR TITLE
sessiontxn/staleread: don't overwrite StaleTSOProvider for single statement

### LINKED ISSUE #65090: NOW() returns different values in one SQL statement with stale read
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond )
    ->   union 
    -> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond );
+-------------------+----------------------------------------------------+
| source_table_name | hashed_source_table_name                           |
+-------------------+----------------------------------------------------+
| Databricks        | 0x7C78967C78967C7896                               |
| PingCAP           | 0x144653144653144653                               |
+-------------------+----------------------------------------------------+
2 rows in set (0.00 sec)
mysql> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond )
    ->   union 
    -> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond );
ERROR 8135 (HY000): can not set different time in the as of
mysql> 
mysql> 
mysql> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond )
    ->   union 
    -> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond );
ERROR 8135 (HY000): can not set different time in the as of
mysql> 
mysql> 
mysql> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond )
    ->   union 
    -> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond );
ERROR 8135 (HY000): can not set different time in the as of
mysql> 
mysql> 
mysql> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond )
    ->   union 
    -> SELECT * from test
    ->   as of timestamp ( now(3)- interval 1000 second_microsecond );
+-------------------+----------------------------------------------------+
| source_table_name | hashed_source_table_name                           |
+-------------------+----------------------------------------------------+
| Databricks        | 0x7C78967C78967C7896                               |
| PingCAP           | 0x144653144653144653                               |
+-------------------+----------------------------------------------------+
2 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
NOW() returns a constant time that indicates the time at which the statement began to execute. (Within a stored function or trigger, [NOW()](https://dev.mysql.com/doc/refman/8.4/en/date-and-time-functions.html#function_now) returns the time at which the function or triggering statement began to execute.)

### 3. What did you see instead (Required)
NOW() returns different values in one SQL statement with stale read

### 4. What is your TiDB version? (Required)
Both v7 and v8

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: close #65090

Problem Summary:

### What changed and how does it work?

`CalculateAsOfTsExpr` may be called multi times when there are multi select-as-of-timestamp statements in one SQL, multi TSO providers can break the consistent requirement.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

I reran the tests described in the issue and the unexpected error never appears with this PR.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/sessionctx/stmtctx/stmtctx.go [hunk 1]
```diff
@@ -1195,6 +1195,9 @@ func (sc *StatementContext) DetachMemDiskTracker() {
 func (sc *StatementContext) SetStaleTSOProvider(eval func() (uint64, error)) {
 	sc.StaleTSOProvider.Lock()
 	defer sc.StaleTSOProvider.Unlock()
+	if sc.StaleTSOProvider.eval != nil {
```
Comment (lcwangchao) [inline pkg/sessionctx/stmtctx/stmtctx.go:1198]: I think it's better to provide another method, `IsStableTSOProvideSet.` and the outside checks the return value to determine wether to reset it?

The implicit skip may cause some misunderstand of its semantics

Comment (you06) [reply pkg/sessionctx/stmtctx/stmtctx.go:1198]: Consider this order, check it outside(out of mutex) may set the TSO Prodiver doubel times:

1. thread1: `IsStableTSOProvideSet` returns `false`.
2. thread2: `IsStableTSOProvideSet` returns `false`.
3. thread1: call `SetStaleTSOProvider(...)`.
4. thread2: call `SetStaleTSOProvider(...)`.

If you think checking inside the function is too vague, I can rename the function to `SetStaleTSOProviderIfNotExist`.

**Review by lcwangchao — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]
