### PR TITLE
expression:truncate decimal value instead of return error

### LINKED ISSUE #11333: Data Truncated when `select 0.0000000000000000000000...000;`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`select 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;`

2. What did you expect to see?
In MySQL 8.0.15
```
mysql> select 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
+---------------------------------------------------------------------------------------------+
| 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 |
+---------------------------------------------------------------------------------------------+
|                  0.000000000000000000000000000000000000000000000000000000000000000000000000 |
+---------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
mysql> select 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;              
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 98 near "0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"decimal literal: [types:1265]Data Truncated
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
master

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

### PR DESCRIPTION
**Pull request by Win-Man**
### What problem does this PR solve?

Issue Number: close #11333 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:
Return `nil` instead of `ErrTruncated` when parse decimal value from string.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
```
select 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
```

Side effects
- 

### Release note 

- No release note

### CODE REVIEW

File: expression/integration_test.go [hunk 1]
```diff
@@ -8257,3 +8257,11 @@ func (s *testIntegrationSuite) TestIssue12205(c *C) {
 	tk.MustQuery("show warnings;").Check(
 		testkit.Rows("Warning 1292 Truncated incorrect time value: '18446744072635875000'"))
 }
+
+func (s *testIntegrationSuite) TestIssue11333(c *C) {
+	defer s.cleanEnv(c)
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustQuery(`select 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;`).Check(testkit.Rows("0.000000000000000000000000000000000000000000000000000000000000000000000000"))
```
Comment (XuHuaiyu) [inline expression/integration_test.go:8264]: What about the behavior in `Insert` statement?

Comment (Win-Man) [reply expression/integration_test.go:8264]: The value will truncated decided by  `D` of `decimal(M,D)`.
```
mysql> create table t(col1 decimal);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values(0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000);
Query OK, 1 row affected (0.01 sec)

mysql> select * from t;
+------+
| col1 |
+------+
|    0 |
+------+
1 row in set (0.01 sec)

mysql> show create table t;
+-------+--------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                       |
+-------+--------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `col1` decimal(10,0) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+--------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> create table t1(col1 decimal(65,30));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values(0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000);
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+----------------------------------+
| col1                             |
+----------------------------------+
| 0.000000000000000000000000000000 |
+----------------------------------+
1 row in set (0.00 sec)
```

The behavior is same with `MySQL-8.0.19`. Before this pr, tidb will throw an error.
```
mysql> create table t(col1 decimal);
Query OK, 0 rows affected (0.14 sec)

mysql> insert into t values(0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 112 near "0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)"decimal literal: [types:1265]Data truncated for column '%s' at row %d
```

Comment (XuHuaiyu) [reply expression/integration_test.go:8264]: It'll be nice to add these cases.

Comment (Win-Man) [reply expression/integration_test.go:8264]: OK, I will add these cases later.

File: types/mydecimal.go [hunk 2]
```diff
@@ -432,6 +432,9 @@ func (d *MyDecimal) FromString(str []byte) error {
 	wordsInt, wordsFrac, err := fixWordCntError(wordsInt, wordsFrac)
 	if err != nil {
 		digitsFrac = wordsFrac * digitsPerWord
+		if err == ErrTruncated {
```
Comment (lzmhhh123) [inline types/mydecimal.go:435]: The truncated error should not be ignored here. There is an example:

```sql
err = sc.HandleTruncate(res.FromString([]byte(val)))
```

we'd better handle it out of this function.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Review by lzmhhh123 — APPROVED** [review]
