### PR TITLE
br/restore: fail fast when meeting some error during restoration

### LINKED ISSUE #42157: Restore: BR should fast fail when encountering some fatal errors
## Enhancement
For now, BR would stall for a long time when the thread pool is heavy loaded. The principle just be like [this playground](https://go.dev/play/p/zpEWQZKDSaI).

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

Issue Number: close #42157

Problem Summary:
As the issue has described, after encountered an error, we still try to fire new requests to the thread pool.

### What is changed and how it works?
This PR would give up issuing new requests to the thread pool when there are failed tasks.

### Check List

Tests 

- [ ] (Almost) No code
This PR is really hard to test: perhaps we need to figure out a effective way to mock the `restore.Client`.
If you want to verify these changes, you may need to make a environment where download fail very slow. In our case, that is all S3 requests from TiKV has been rejected by a firewall just DROP TCP packets(also not send some RST packet). 

### Release note

```release-note
Fixed a problem that made BR looks like be stuck when there are some network issues.
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

File: br/pkg/restore/client.go [hunk 1]
```diff
@@ -1206,6 +1215,12 @@ func (rc *Client) RestoreSSTFiles(
 		)
 		return errors.Trace(err)
 	}
+	// Once the parent context canceled and there is no task running in the errgroup,
+	// we may break the for loop without error in the errgroup. (Will this happen?)
+	// At that time, return the error in the context here.
+	if err := ectx.Err(); err != nil {
```
Comment (3pointer) [inline br/pkg/restore/client.go:1221]: I'm not understand when will this error happen. what if we just return nil?

Comment (YuJuncen) [reply br/pkg/restore/client.go:1221]: > what if we just return nil?
The user may get some confusing error message.

**Review by 3pointer — APPROVED** [review]

**Comment by YuJuncen** [comment]
tests/realtikvtest/brietest/backup_restore_test.go:43
Error:      	Received unexpected error:
[schema:1050]Table 'br.t1' already exists
🤔

**Comment by YuJuncen** [comment]
It seems the two failed BRIE tests covers all cases... For saving time, let merge it.
/merge
