### PR TITLE
statistics: fix stack overflow when use DNF expr immediately after add column

### LINKED ISSUE #22134: Using 'select .. where ... in' cause stack overflow
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (a int);
select * from t;
alter table t add column b timestamp;
select * from t where b in ('2000-01-01', '2000-01-02');
```

To reproduce the error, one may need to run the script multiple times.

### 2. What did you expect to see? (Required)

Query OK.

### 3. What did you see instead (Required)

```console
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

Log:
```console
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc02ffe03a0 stack=[0xc02ffe0000, 0xc04ffe0000]
fatal error: stack overflow
```

<details>

```
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc02ffe03a0 stack=[0xc02ffe0000, 0xc04ffe0000]
fatal error: stack overflow

runtime stack:
runtime.throw(0x3946ee3, 0xe)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1067 +0x78d
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:449 +0x8f

goroutine 554 [running]:
runtime.heapBitsSetType(0xc020fff180, 0x20, 0x20, 0x381c7c0)
	/usr/local/go/src/runtime/mbitmap.go:911 +0xaa5 fp=0xc02ffe03b0 sp=0xc02ffe03a8 pc=0x12b3de5
runtime.mallocgc(0x20, 0x381c7c0, 0x1, 0xc020fdfa9c)
	/usr/local/go/src/runtime/malloc.go:1090 +0x5a5 fp=0xc02ffe0450 sp=0xc02ffe03b0 pc=0x12aa2e5
runtime.makeslicecopy(0x381c7c0, 0x2, 0x2, 0xc02ffe0678, 0x5750600)
	/usr/local/go/src/runtime/slice.go:61 +0x125 fp=0xc02ffe04a0 sp=0xc02ffe0450 pc=0x12ebc05
github.com/pingcap/tidb/expression.newFunctionImpl(0x3e411e0, 0xc00fa16400, 0x1, 0x392d1d0, 0x2, 0xc021004480, 0xc02ffe0678, 0x2, 0x2, 0xc02ffe05f8, ...)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/expression/scalar_function.go:204 +0x1a5 fp=0xc02ffe0580 sp=0xc02ffe04a0 pc=0x20941c5
github.com/pingcap/tidb/expression.NewFunction(...)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/expression/scalar_function.go:244
github.com/pingcap/tidb/expression.NewFunctionInternal(0x3e411e0, 0xc00fa16400, 0x392d1d0, 0x2, 0xc021004480, 0xc02ffe0678, 0x2, 0x2, 0xc00fe5ca50, 0x3519da0)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/expression/scalar_function.go:259 +0x96 fp=0xc02ffe0608 sp=0xc02ffe0580 pc=0x2094bb6
github.com/pingcap/tidb/expression.composeConditionWithBinaryOp(0x3e411e0, 0xc00fa16400, 0xc020fff160, 0x2, 0x2, 0x392d1d0, 0x2, 0x2, 0x8)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/expression/expression.go:683 +0x245 fp=0xc02ffe06a8 sp=0xc02ffe0608 pc=0x208d025
github.com/pingcap/tidb/expression.ComposeDNFCondition(...)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/expression/expression.go:697
github.com/pingcap/tidb/util/ranger.MergeDNFItems4Col(0x3e411e0, 0xc00fa16400, 0xc020fff120, 0x2, 0x2, 0x2, 0x0, 0xc021000a00)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/util/ranger/detacher.go:735 +0x32d fp=0xc02ffe0958 sp=0xc02ffe06a8 pc=0x237484d
github.com/pingcap/tidb/statistics.(*HistColl).Selectivity(0xc00fa73380, 0x3e411e0, 0xc00fa16400, 0xc0210009e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x2, ...)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/statistics/selectivity.go:302 +0x12ad fp=0xc02ffe0e18 sp=0xc02ffe0958 pc=0x23ac3ed
github.com/pingcap/tidb/statistics.(*HistColl).Selectivity(0xc00fa73380, 0x3e411e0, 0xc00fa16400, 0xc021000980, 0x1, 0x1, 0x0, 0x0, 0x0, 0x2, ...)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/statistics/selectivity.go:321 +0x1471 fp=0xc02ffe12d8 sp=0xc02ffe0e18 pc=0x23ac5b1
github.com/pingcap/tidb/statistics.(*HistColl).Selectivity(0xc00fa73380, 0x3e411e0, 0xc00fa16400, 0xc021000920, 0x1, 0x1, 0x0, 0x0, 0x0, 0x2, ...)
	/home/tangenta/gopath/src/github.com/pingcap/tidb/statistics/selectivity.go:321 +0x1471 fp=0xc02ffe1798 sp=0xc02ffe12d8 pc=0x23ac5b1
github.com/pingcap/tidb/statistics.(*HistColl).Selectivity(0xc00fa73380, 0x3e411e0, 0xc00fa16400, 0xc0210008c0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x2, ...)
```

</details>

### 4. What is your TiDB version? (Required)

master `857e3da6ebc17d1c17e4f150fa21c6c474456f1a`

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #22134

Problem Summary:

After ADD COLUMN operation, stats may not be updated immediately so it doesn't contain the new column.
In this case, conditions containing this column can't be handled in `Selectivity()`.
But in https://github.com/pingcap/tidb/pull/18741, when handling DNF condition, we used a recursive method and overlooked this possibility.

### What is changed and how it works?

We added 2 checks.
1. Check if the column in this DNF condition is indeed in the stats.
2. Check if the DNF conditions contain more than 1 column.

Only when both of them satisfied should we recursively call `Selectivity()` to handle this condition.

Each check should fix this issue respectively, but I think it's better to have both of them to prevent some unexpected cases.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- no release note.

### CODE REVIEW

File: statistics/selectivity_test.go [hunk 1]
```diff
@@ -728,6 +728,12 @@ func (s *testStatsSuite) TestDNFCondSelectivity(c *C) {
 
 	// Test issue 19981
 	testKit.MustExec("select * from t where _tidb_rowid is null or _tidb_rowid > 7")
+
+	// Test issue 22134
+	// Information about column n will not be in stats immediately after this SQL executed.
+	// If we don't have a check against this, DNF condition could lead to infinite recursion in Selectivity().
+	testKit.MustExec("alter table t add column n timestamp;")
+	testKit.MustExec("select * from t where n = '2000-01-01' or n = '2000-01-02';")
```
Comment (qw4990) [inline statistics/selectivity_test.go:736]: This test seems meaningless since I add these two lines on the Master branch in local without your fixing logic and I can pass this test.
Please add another test case.

File: statistics/selectivity.go [hunk 2]
```diff
@@ -298,8 +299,20 @@ func (coll *HistColl) Selectivity(ctx sessionctx.Context, exprs []expression.Exp
...
+			cols := expression.ExtractColumns(scalarCond)
+			for i := range cols {
+				if _, ok := coll.Columns[cols[i].UniqueID]; !ok {
+					continue OUTER
+				}
+			}
+
 			dnfItems := expression.FlattenDNFConditions(scalarCond)
 			dnfItems = ranger.MergeDNFItems4Col(ctx, dnfItems)
+			// If the conditions only contains a single column, we won't handle them.
```
Comment (eurekaka) [inline statistics/selectivity.go:312]:
```suggestion
			// If the conditions only contain a single column, we won't handle them.
```

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
Should we pick this to v5.0 and v4.0?

**Review by tangenta — COMMENTED** [review]
LGTM

**Comment by tangenta** [comment]
> After ADD COLUMN operation, stats may not be updated immediately so it doesn't contain the new column.

Is it possible to make the stats update immediately after DDL? As a preliminary idea, there are 2 steps to implement it:
1. Change `Handle.ddlEventCh` to a synchronized channel.
2. Update table stat during `loadInfoSchema`.

However, this may impact the DDL performance. WDYT? @AilinKid @wjhuang2016

**Review by eurekaka — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by wjhuang2016** [comment]
> > After ADD COLUMN operation, stats may not be updated immediately so it doesn't contain the new column.
> 
> Is it possible to make the stats update immediately after DDL? As a preliminary idea, there are 2 steps to implement it:
> 
> 1. Change `Handle.ddlEventCh` to a synchronized channel.
> 2. Update table stat during `loadInfoSchema`.
> 
> However, this may impact the DDL performance. WDYT? @AilinKid @wjhuang2016

It's not necessary to wait for that?

**Comment by time-and-fate** [comment]
manually cherry-picked to release-4.0 as part of https://github.com/pingcap/tidb/pull/23208
