### PR TITLE
planner: not use the latest schema when plan-cache is off

### LINKED ISSUE #30940: QPS drop to zero when add column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
oltp_fun_002
1、run sysbench
2、add column for all tables
sysbench --mysql-user=root --db-driver=mysql --time=0 --report-interval=10 --mysql-db=test --mysql-host=tc-tidb.endless-oltp--tps-512791-1-934 --mysql-port=4000 --threads=512 --tables=32 --table-size=10000000 --mysql-ignore-errors=2013,1213,1105,8028,9007 --rand-type=pareto oltp_read_write run

### 2. What did you expect to see? (Required)
qps can not drop to zero

### 3. What did you see instead (Required)
QPS drop to zero
xPLeCuNpPo
image
middle_img_v2_5dba459f-8cf9-434a-b27c-59de5382776g

### 4. What is your TiDB version? (Required)
 # ./tidb-server -V
Release Version: v5.0.6
Edition: Community
Git Commit Hash: 181b4c280dfad2da8fe8e52d76436b8ad06e90ae
Git Branch: heads/refs/tags/v5.0.6
UTC Build Time: 2021-12-21 09:10:51
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by you06**
Signed-off-by: you06 <you1474600@gmail.com>

### What problem does this PR solve?

Issue Number: close #30940

Problem Summary:

### What is changed and how it works?

Execute statements may use different schemas in building plan and execution, this issue is fixed in master by #26759, but hard to cherry-pick to 5.0 branch. Since plan cache is an experimental feature in 5.0, this PR skips fetching the latest schema for non-plan-cache statements.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix a bug that concurrent DML and DDL may cause panic.
```

### CODE REVIEW

**Comment by you06** [comment]
@xhebox PTAL

**Review by xhebox — APPROVED** [review]

**Comment by you06** [comment]
@bb7133 @wjhuang2016 PTAL

File: planner/optimize.go [hunk 1]
```diff
@@ -243,7 +243,8 @@ func optimize(ctx context.Context, sctx sessionctx.Context, node ast.Node, is in
 			execID = sctx.GetSessionVars().PreparedStmtNameToID[execPlan.Name]
 		}
 		if preparedPointer, ok := sctx.GetSessionVars().PreparedStmts[execID]; ok {
-			if preparedObj, ok := preparedPointer.(*core.CachedPrepareStmt); ok && preparedObj.ForUpdateRead {
+			if preparedObj, ok := preparedPointer.(*core.CachedPrepareStmt); ok && preparedObj.ForUpdateRead &&
```
Comment (bb7133) [inline planner/optimize.go:246]: Please add a comment here.

**Comment by bb7133** [comment]
Please add a test case for this change.

**Comment by bb7133** [comment]
PTAL @qw4990 @cfzjywxk

**Review by AilinKid — COMMENTED** [review]
LGTM

File: planner/optimize.go [hunk 2]
```diff
@@ -16,6 +16,7 @@ package planner
 import (
 	"context"
 	"fmt"
+	"github.com/pingcap/failpoint"
```
Comment (cfzjywxk) [inline planner/optimize.go:19]: format.

We've got too many release versions to maintain...

**Review by bb7133 — COMMENTED** [review]
LGTM

**Review by bb7133 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
