### PR TITLE
telemetry: fix that test fail to run on apple M1

### LINKED ISSUE #24979: telemetry_test fail to run on apple M1
### 1. Minimal reproduce step (Required)

run the test on m1, you will find this error.

```
telemetry_test.go:112:
    c.Assert(jsonParsed.ExistsP("hostExtra.cpuFlags"), Equals, true)
... obtained bool = false
... expected bool = true

```

### 2. What did you expect to see? (Required)
 
It should run successfully.

### 4. What is your TiDB version? (Required)

master branch

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #24979 

Problem Summary:

### What is changed and how it works?

Apple M1 doesn't contain CpuInfo. if it is, this unit test will be skipped.

### Check List 

Tests 

- [x] Unit test

### Release note 

```release-note
NONE
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

File: telemetry/telemetry_test.go [hunk 1]
```diff
@@ -75,7 +75,10 @@ func TestPreview(t *testing.T) {
 	jsonParsed, err := gabs.ParseJSON([]byte(r))
 	require.NoError(t, err)
 	require.Equal(t, trackingID, jsonParsed.Path("trackingId").Data().(string))
-	require.True(t, jsonParsed.ExistsP("hostExtra.cpuFlags"))
+	// Apple M1 doesn't contain cpuFlags
+	if runtime.GOARCH != "arm" && runtime.GOOS != "darwin" {
```
Comment (tisonkun) [inline telemetry/telemetry_test.go:79]: @hawkingrei @xiongjiwei @bb7133 is this condition correct? I think it skip the test even if on Apple Intel or any other ARM arch os.

Comment (hawkingrei) [reply telemetry/telemetry_test.go:79]: fixed in https://github.com/pingcap/tidb/pull/26826
