### PR TITLE
br: modify tables that should be altered auto id or random id

### LINKED ISSUE #33596: br: incremental restore should rebase auto increment id even table exists;
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create table with _tidb_rowid. 
```
CREATE TABLE `d` (
  `o_id` int(11) NOT NULL,
  `w_id` int(11) NOT NULL,
  PRIMARY KEY (`o_id`,`w_id`)
```
2. do a full backup with this table.
3. insert more than 30000 rows data.
4. do an incremental backup with this table.

5. do a full restore with this table in restore cluster.
6. do an incremental restore with this table.
7. insert some data.

### 2. What did you expect to see? (Required)
insert succeed.
### 3. What did you see instead (Required)
Duplicate entry '30001' for key 'PRIMARY'
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by WangLe1321**
### What problem does this PR solve?

Issue Number: close #33596

Problem Summary:

### What is changed and how it works?

We modify tables that should be altered auto_increment or auto_random_base. Tables existed in restored cluster or created by executing ddl job all should be altered during incremental restoration.

As long as we alter auto_increment or auto_random_base in restored table, we can insert records successfully.

### Check List

Tests 

- [x] Unit test
- [x] Manual test (add detailed scripts or steps below)
    1. create an empty table `a`, `b`, `c`, `d`, `e` (NEXT_GLOBAL_ROW_ID is 1).
    2. insert a few records into `b`, `c`, `d`(NEXT_GLOBAL_ROW_ID is 30001).
    3. do a full backup.
    4. truncate table `b`, `c`, drop table `d`, rename table `e` to `e1`.
    5. insert a few records into `a`, `b`, `e1` via one TiDB instance (NEXT_GLOBAL_ROW_ID is 30001).
    6. do an incremental backup.
    7. do a full restoration to restored cluster.
    8. do an incremental restoration to restored cluster.
    9. insert a few records into `a`, `b`, `c`, `d`, `e` successfully, which is the correct result. In this situation, `a` is the table changed NEXT_GLOBAL_ROW_ID, `b` is the table truncated, `c` is the table truncated and changed NEXT_GLOBAL_ROW_ID, `d` is the table dropped, `e1` is the table renamed and changed NEXT_GLOBAL_ROW_ID.

### Release note

```release-note
Fix a bug of duplicate primary key when insert record into table after incremental restoration.
```

### CODE REVIEW

**Comment by WangLe1321** [comment]
cc @3pointer

File: br/pkg/restore/client.go [hunk 1]
```diff
@@ -1348,6 +1354,7 @@ func (rc *Client) IsSkipCreateSQL() bool {
 // 2. create table/create and rename table: the first create table will lock down the id cache.
 // because we cannot create onExistReplace table.
 // so the final create DDL with the correct auto increment/random id won't be executed.
+// Deprecated
```
Comment (3pointer) [inline br/pkg/restore/client.go:1357]: we can remove this function directly, since there no other caller depend on this function.

**Comment by 3pointer** [comment]
I think we need another test case to cover this change.
A test case make sure the former code not work, and this code works.

**Comment by joccau** [comment]
Rest LGTM.
Should  test more scenes  in backup and incremental backup by Manual test.
Like truncate table/create and rename table with auto_increment ID.

File: br/tests/br_incremental/run.sh [hunk 2]
```diff
@@ -48,12 +56,17 @@ if [ "${row_count_full}" != "${row_count_ori_full}" ];then
...
+run_br restore db --db $DB -s "local://$TEST_DIR/$DB/inc" --pd $PD_ADDR
 row_count_inc=$(run_sql "SELECT COUNT(*) FROM $DB.$TABLE;" | awk '/COUNT/{print $2}')
 # check full restore
 if [ "${row_count_inc}" != "${row_count_ori_inc}" ];then
     echo "TEST: [$TEST_NAME] incremental restore fail on database $DB"
     exit 1
 fi
 
+# check inserting records with auto increment id after incremental restore
+for i in $(seq $ROW_COUNT); do
```
Comment (3pointer) [inline br/tests/br_incremental/run.sh:68]: I doubt that 10 rows can cover this case.
maybe we should use some sql like `select max(_tidb_rowid) from a` to check tidb_rowid is expected after insertion.🤔

**Review by 3pointer — APPROVED** [review]
Rest LGTM

File: br/tests/br_incremental/run.sh [hunk 3]
```diff
@@ -17,29 +17,37 @@
...
 TABLE="usertable"
+AUTO_ID_TABLE="a"
+ROW_COUNT=10
 
 run_sql "CREATE DATABASE $DB;"
 
 go-ycsb load mysql -P tests/$TEST_NAME/workload -p mysql.host=$TIDB_IP -p mysql.port=$TIDB_PORT -p mysql.user=root -p mysql.db=$DB
 row_count_ori_full=$(run_sql "SELECT COUNT(*) FROM $DB.$TABLE;" | awk '/COUNT/{print $2}')
 
+run_sql "CREATE TABLE IF NOT EXISTS ${DB}.${AUTO_ID_TABLE} (c1 INT);"
```
Comment (joccau) [inline br/tests/br_incremental/run.sh:28]:
```suggestion
run_sql "CREATE TABLE IF NOT EXISTS ${DB}.${AUTO_ID_TABLE} (id int PRIMARY KEY AUTO_INCREMENT, c1 int);"
```

Comment (joccau) [reply br/tests/br_incremental/run.sh:28]: This case should test table with auto_increment key.

**Review by joccau — APPROVED** [review]
LGTM
