### PR TITLE
types: fix CASE WHEN wrong result when prepare value is NULL

### LINKED ISSUE #62564: `CASE WHEN` returns different result in prepared statement and normal query
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The following query contains two equivalent queries, one is a normal SELECT query, and another one is a prepared statement. However, they have different results. The normal SELECT query returns 1 row, but the prepared statement returns an empty result.

```
CREATE TABLE t0(c0 DECIMAL);
INSERT INTO t0 VALUES (0);
SELECT * FROM t0 WHERE CAST((CASE t0.c0 WHEN t0.c0 THEN CAST(t0.c0 AS TIME) ELSE NULL END ) AS DATE);
SET @b = NULL;
PREPARE prepare_query FROM 'SELECT * FROM t0 WHERE CAST((CASE t0.c0 WHEN t0.c0 THEN CAST(t0.c0 AS TIME) ELSE ? END ) AS DATE)';
EXECUTE prepare_query USING @b;
```

### 2. What did you expect to see? (Required)

These two queries have the same result.

### 3. What did you see instead (Required)

These two queries have different results.

### 4. What is your TiDB version? (Required)

tidb_version()
Release Version: v9.0.0-beta.2.pre-149-g96f5396\nEdition: Community\nGit Commit Hash: 96f5396be12ae6c5bf440bd22b1e0bec532aff9e\nGit Branch: HEAD\nUTC Build Time: 2025-07-21 20:48:44\nGoVersion: go1.23.11\nRace Enabled: false\nCheck Table Before Drop: false\nStore: tikv\nKernel Type: Classic

### PR DESCRIPTION
**Pull request by yihong0618**
### What problem does this PR solve?

This patch close 62564 by fixing the case when prepare NULL value when case when
prepare, and do not break the json value ref #54145

Issue Number: close #62564

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/casetest/tiflash_predicate_push_down_test.go [hunk 1]
```diff
@@ -139,3 +139,29 @@ func TestInvertedIndex(t *testing.T) {
 		compareStringSlice(t, normalizedPlanRows, output[i].Plan)
 	}
 }
+
+func TestCaseWhenPreparedStatementBug(t *testing.T) {
```
Comment (Lloyd-Pottiger) [inline pkg/planner/core/casetest/tiflash_predicate_push_down_test.go]: This file contains unit tests which related to tiflash late materialization and inverted index. The bug you fixed is not related to those features, so move this unit test to another file?

Comment (yihong0618) [reply pkg/planner/core/casetest/tiflash_predicate_push_down_test.go]: OK will do it,

Comment (yihong0618) [reply pkg/planner/core/casetest/tiflash_predicate_push_down_test.go]: FIxed

File: pkg/planner/core/casetest/integration_test.go [hunk 2]
```diff
@@ -536,3 +536,29 @@ func TestIssue56915(t *testing.T) {
...
+	tk.MustExec("SET @b = NULL;")
+	tk.MustExec("PREPARE prepare_query FROM 'SELECT * FROM t0 WHERE CAST((CASE t0.c0 WHEN t0.c0 THEN CAST(t0.c0 AS TIME) ELSE ? END ) AS DATE)';")
+	preparedResult := tk.MustQuery("EXECUTE prepare_query USING @b;")
+	t.Logf("Prepared statement result: %v", preparedResult.Rows())
+
+	tk.MustExec("PREPARE prepare_case FROM 'SELECT CAST((CASE t0.c0 WHEN t0.c0 THEN CAST(t0.c0 AS TIME) ELSE ? END ) AS DATE) FROM t0';")
+	preparedCaseResult := tk.MustQuery("EXECUTE prepare_case USING @b;")
+	t.Logf("Prepared CASE result: %v", preparedCaseResult.Rows())
+
+	require.Equal(t, len(normalResult.Rows()), len(preparedResult.Rows()), "Results should have the same number of rows")
```
Comment (YangKeao) [inline pkg/planner/core/casetest/integration_test.go]: Is it possible to move the test to `tests/integrationtest/t/planner/core/casetest/integration.test`? We have moved all "simple" tests there to accelerate the test.

Add the SQLs to the `tests/integrationtest/t/planner/core/casetest/integration.test` and run `./run-tests.sh -s ../../bin/tidb-server -r planner/core/casetest/integration`, it'll update the `tests/integrationtest/r/planner/core/casetest/integration.result`.

**Review by YangKeao — COMMENTED** [review]
Rest LGTM

File: pkg/planner/core/casetest/integration_test.go (hunk 2 above)
Comment (yihong0618) [reply pkg/planner/core/casetest/integration_test.go]: of course will try

**Comment by hawkingrei** [comment]
/hold

waiting for the other's approve

File: pkg/planner/core/casetest/integration_test.go (hunk 2 above)
Comment (yihong0618) [reply pkg/planner/core/casetest/integration_test.go]: Done
