### PR TITLE
expression: avoid copying the hashcode to prevent forgetting to update the hashcode when updating the expression later

### LINKED ISSUE #62121: Expression's hashcode cannnot be upated when we update the expression context after
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

We know that each expression has a cache for its hash code. However, if we update the hash code and then modify the content of the expression without rehashing in time, we may get incorrect results.

Image

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #62121

Problem Summary:

### What changed and how does it work?

We know that each expression has a cache for its hash code. However, if we update the hash code and then modify the content of the expression without rehashing in time, we may get incorrect results.

so now we refrain from copying the hashcode to prevent forgetting to update the hashcode when updating the expression later

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/scalar_function.go [hunk 1]
```diff
@@ -564,8 +577,21 @@ func (sf *ScalarFunction) EvalVectorFloat32(ctx EvalContext, row chunk.Row) (typ
...
+				if bytes.Equal(sf.hashcode, copyhashcode) {
+					return true
+				}
+				logutil.BgLogger().Error("hashcode not equal", zap.String("last_stack_trace", sf.testStackTrace.String()))
+				return false
+			}, "HashCode should not change after ReHashCode is called")
+		}
 		return sf.hashcode
 	}
+	sf.testStackTrace = intest.NewTestStackTrace()
```
Comment (AilinKid) [inline pkg/expression/scalar_function.go]: this is not intest assignment, which means each sf will fetch its stack info, which could be a burden. (ref: no_stack_info_error)

File: pkg/expression/scalar_function.go [hunk 2]
```diff
@@ -564,8 +577,21 @@ func (sf *ScalarFunction) EvalVectorFloat32(ctx EvalContext, row chunk.Row) (typ
 // HashCode implements Expression interface.
 func (sf *ScalarFunction) HashCode() []byte {
 	if len(sf.hashcode) > 0 {
+		if intest.InTest {
+			copyhashcode := make([]byte, len(sf.hashcode))
```
Comment (AilinKid) [inline pkg/expression/scalar_function.go:562]: and i didn't get what problem we are gonna solving. 
i think the main problem is Rehashing when the expression is changed?

Comment (hawkingrei) [reply pkg/expression/scalar_function.go:562]: Yes, so we need to find who update the expression and forget to rehash.

**Review by qw4990 — APPROVED** [review]
