### PR TITLE
executor: fix autoid doesn't handle float, double type and tiny cleanup

### LINKED ISSUE #11109: Autoid value is incorrect when field type is float or double
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
use test;
create table t1(id int primary key, n float auto_increment, key I_n(n));
create table t2(id int primary key, n double auto_increment, key I_n(n));
```

```
insert into t1 values(1, 1);
insert into t2 values(1, 1);
insert into t2(id) values(2);
```

2. What did you expect to see?
```
mysql> select * from t1;
+----+---+
| id | n |
+----+---+
|  1 | 1 |
+----+---+
1 row in set (0.00 sec)
```

```
mysql> select * from t2;
+----+---+
| id | n |
+----+---+
|  1 | 1 |
|  2 | 2 |
+----+---+
2 rows in set (0.00 sec)
```

3. What did you see instead?
```
mysql> select * from t1;
+----+------+
| id | n    |
+----+------+
|  1 |    0 |
+----+------+
1 row in set (0.00 sec)
```

```
mysql> select * from t2;
+----+-----------------------+
| id | n                     |
+----+-----------------------+
|  1 |                     1 |
|  2 | 4.6071824188000174e18 |
+----+-----------------------+
2 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
./tidb-server -V

Release Version: v3.0.0-rc.1-290-g21d2590ac
Git Commit Hash: 21d2590ac37bf53e5e687b8a341d50105ddbffe8
Git Branch: master
UTC Build Time: 2019-07-06 12:56:31
GoVersion: go version go1.12.6 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by nange**
### What problem does this PR solve? 
Fixes #11109 

### What is changed and how it works?
modify the ```adjustAutoIncrementDatum``` method logic,  handle the float and double scenario.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by crazycs520** [comment]
@tiancaiamao @lysu PTAL

File: executor/insert_common.go [hunk 1]
```diff
@@ -531,6 +525,22 @@ func (e *InsertValues) adjustAutoIncrementDatum(d types.Datum, hasValue bool, c
...
+	var recordID int64
+
+	switch target.Tp {
+	case mysql.TypeFloat, mysql.TypeDouble:
+		f := d.GetFloat64()
+		recordID = int64(f)
+	case mysql.TypeTiny, mysql.TypeShort, mysql.TypeInt24, mysql.TypeLong, mysql.TypeLonglong:
+		recordID = d.GetInt64()
+	default:
+		panic("should never happen")
```
Comment (lzmhhh123) [inline executor/insert_common.go]: No panic. Pls return an error instead.

File: executor/insert_common.go [hunk 2]
```diff
@@ -488,12 +488,7 @@ func (e *InsertValues) adjustAutoIncrementDatum(d types.Datum, hasValue bool, c
 		d.SetNull()
 	}
 	if !d.IsNull() {
-		sc := e.ctx.GetSessionVars().StmtCtx
```
Comment (winkyao) [inline executor/insert_common.go]: you should not remove these codes, need to convert it to the field type of the column.

Comment (nange) [reply executor/insert_common.go]: The converting is duplicate which has been done in: https://github.com/pingcap/tidb/blob/master/executor/insert_common.go#L252

**Comment by nange** [comment]
There's another case the pr doesn't handle. eg: update stmt.  I would like to mark the pr to "WIP".  And more test case should add also.

File: executor/insert_common.go (hunk 1 above)
Comment (nange) [reply executor/insert_common.go]: done

**Comment by nange** [comment]
@winkyao @lzmhhh123 please review again, thanks.

**Comment by imtbkcat** [comment]
PTAL @winkyao

**Comment by imtbkcat** [comment]
PTAL @crazycs520 @lzmhhh123

File: executor/insert_test.go [hunk 3]
```diff
@@ -287,6 +287,231 @@ func (s *testSuite3) TestAllowInvalidDates(c *C) {
...
+		},
+		{
+			`insert into t4(id, n) values(5, 5.5)`,
+			`select * from t4 where id = 5`,
+			testkit.Rows(`5 5.5`),
+		},
+		{
+			`insert into t4(id) values(6)`,
+			`select * from t4 where id = 6`,
+			testkit.Rows(`6 6`),
```
Comment (zimulala) [inline executor/insert_test.go]: It isn't compatible with MySQL5.7, the result of MySQL is as follows:
```
mysql> select * from t4 where id = 6;
+----+---+
| id | n |
+----+---+
|  6 | 7 |
+----+---+
1 row in set (0.01 sec)
```

Comment (nange) [reply executor/insert_test.go]: @zimulala fixed! thank you! 
BTW, the update behavior is the same as MySQL5.8, but is not the same as MySQL5.7.  I think the behavior of MySQL5.8 is expected to me.
