### PR TITLE
br: fix restore metakv without default cf files

### LINKED ISSUE #46578: cannot restore the metakv when there are only write cf files
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start log backup
2.`create table test.t(id int);`
3. `insert into test.t values (1)`
4. do snapshot backup
5. insert into test.t with 30000 rows
6. restore to another cluster

### 2. What did you expect to see? (Required)
the next_rowid shoule be 60001, and there are 30002 rows in the table `test.t`.
### 3. What did you see instead (Required)
the next_rowid is 30001, and there are 30002 rows in the table `test.t`.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #46578 

Problem Summary:
when there are only write cf metakv files, the metakv won't be restored.
### What is changed and how it works?
restore the metakv when there are only write cf metakv files.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]

File: br/pkg/restore/client_test.go [hunk 1]
```diff
@@ -648,78 +648,277 @@ func MockEmptySchemasReplace() *stream.SchemasReplace {
...
+				batchCount++
+				require.Equal(t, 1, len(files))
+				require.Equal(t, stream.DefaultCF, cf)
+				if batchCount == 1 {
+					require.Equal(t, uint64(100), files[0].MinTs)
+					require.Equal(t, uint64(110), filterTS)
+					return nil, nil
+				} else {
+					require.Equal(t, 0, len(entries))
+				}
```
Comment (BornChanger) [inline br/pkg/restore/client_test.go:846]:
```suggestion
				}
				
				require.Equal(t, 0, len(entries))
```

File: br/pkg/restore/client_test.go [hunk 2]
```diff
@@ -648,78 +648,277 @@ func MockEmptySchemasReplace() *stream.SchemasReplace {
...
```
Comment (BornChanger) [inline br/pkg/restore/client_test.go:914]:
```suggestion
				}
				
				require.Equal(t, 0, len(entries))
				
```

**Review by 3pointer — APPROVED** [review]
