### PR TITLE
executor, planner: fix indexLookUp with static pruning

### LINKED ISSUE #44123: data inconsistency is reported when query with for update clause
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `ccf0ed15` (
  `f9e69bc7` bigint(20) DEFAULT '1112823069779687543',
  `d33b6c1b` decimal(41,16) DEFAULT '5518242590970756357909774.8550717763805231',
  `56231d4d` set('35','pi','dqurb','yita3','kczu','a','t8','4d','bh4qs','lk9a','75k') DEFAULT '35,pi,kczu,a,t8,4d,bh4qs,75k',
  UNIQUE KEY `d2200701` (`d33b6c1b`,`f9e69bc7`),
  UNIQUE KEY `9efc4c6b` (`f9e69bc7`),
  KEY `8a590049` (`56231d4d`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci COMMENT='46791f67'
PARTITION BY HASH (`f9e69bc7`) PARTITIONS 5;
INSERT INTO `ccf0ed15` VALUES
(-7801043551743108407,4626.1410000000000000,'yita3'),
(5755921862464422919,0.4787000000000000,'dqurb'),
(6818225316668061803,5800.0000000000000000,'35'),
(1112823069779687543,5518242590970756357909774.8550717763805231,'dqurb'),
(3823184061824785364,31.7690000000000000,'bh4qs'),
(6741424187029746717,7264.0000000000000000,'pi'),
(7056863346120328265,17.5560000000000000,'dqurb'),
(5552107058771389209,7444.4900000000000000,'a');

select  /*+ use_index_merge( `ccf0ed15` ) */   `ccf0ed15`.`56231d4d` as r0 from `ccf0ed15`    order by r0 limit 82 for update;
``` 

### 2. What did you expect to see? (Required)
No error

### 3. What did you see instead (Required)
``` SQL
mysql> select  /*+ use_index_merge( `ccf0ed15` ) */   `ccf0ed15`.`56231d4d` as r0 from `ccf0ed15`    order by r0 limit 82 for update;
ERROR 8133 (HY000): data inconsistency in table: ccf0ed15, index: 8a590049, index-count:2 != record-count:1
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #44123 

Problem Summary: The root case is we asked one more column which is `model.ExtraPhysTblID` in indexReq. When `resp.EncodeType = EncodeType_TypeDefault`, it can't handle it correctly.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

File: executor/builder.go [hunk 1]
```diff
@@ -3882,6 +3882,21 @@ func buildIndexReq(ctx sessionctx.Context, columns []*model.IndexColumn, handleL
 	return indexReq, err
 }
 
+func needExtraCol(is *plannercore.PhysicalIndexScan) bool {
```
Comment (hawkingrei) [inline executor/builder.go:3885]: It can be a member function of ```plannercore.PhysicalIndexScan```.

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
