### PR TITLE
*: change default charset and collation from 'utf8 utf8_bin' to 'utf8mb4 utf8mb4_bin'

### LINKED ISSUE #7920: Change default charset and collation from utf8 to utf8mb4
TiDB default charset is utf8 and collation is utf8_bin, in some cases, if the Unicode string length is more than 3 bytes(4 bytes), insert this string into a column with utf8 charset will report error like:

```
ERROR 1366 (HY000): Incorrect string value: '\xF0\xA4\x8B\xAE' for column 'v' at row 1
```

Maybe we should consider to change TiDB default charset from utf8 to utf8mb4?

@morgo what's your opinion？

### PR DESCRIPTION
**Pull request by winkyao**
### What problem does this PR solve? 

fix #7920.

Change TiDB default charset and collation to "utf8mb4 utf8mb4_bin", TiDB treat all the data as utf8mb4 actually, but the previous default charset is "utf8", insert the 4 bytes unicode string into TiDB will be ok, but if we use mysqldump to restore the data back into mysql, the charset will be utf8, and it will report an error `ERROR 1366 (HY000): Incorrect string value: '\xF0\xA4\x8B\xAE' for column 'v' at row 1`.

### how it works?

1. change `mysql.DefaultCharset` from `UTF8Charset` to `UTF8MB4Charset`.
2. change `mysql.DefaultCollationName` from `UTF8DefaultCollation` to `UTF8MB4DefaultCollation`.
3. Find all places that used `charset.CharsetUTF8` and `CollationUTF8`, modify them to `charset.CharsetUTF8MB4` or `mysql.DefaultCharset`.

Then fix corresponding test cases.

### Check List 

Tests 

 - exits test cases

Code changes

 - Has exported variable/fields change

Related changes

 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

File: types/field_type.go [hunk 1]
```diff
@@ -365,8 +365,8 @@ func DefaultTypeForValue(value interface{}, tp *FieldType) {
 		// TODO: tp.Flen should be len(x) * 3 (max bytes length of CharsetUTF8)
 		tp.Flen = len(x)
 		tp.Decimal = UnspecifiedLength
-		tp.Charset = mysql.DefaultCharset
-		tp.Collate = mysql.DefaultCollationName
+		tp.Charset = charset.CharsetUTF8MB4
```
Comment (shenli) [inline types/field_type.go]: Can we use GetDefaultCharsetAndCollate?

Comment (gregwebs) [reply types/field_type.go]: This change makes sense to me for this PR. My PR will change it back though :)

**Comment by winkyao** [comment]
@shenli  PTAL

**Comment by winkyao** [comment]
The ci will be fixed after https://github.com/pingcap/parser/pull/13 merged.

File: expression/aggregation/descriptor.go [hunk 2]
```diff
@@ -334,8 +334,8 @@ func (a *AggFuncDesc) typeInfer4Avg(ctx sessionctx.Context) {
 
 func (a *AggFuncDesc) typeInfer4GroupConcat(ctx sessionctx.Context) {
 	a.RetTp = types.NewFieldType(mysql.TypeVarString)
-	a.RetTp.Charset = charset.CharsetUTF8
-	a.RetTp.Collate = charset.CollationUTF8
+	a.RetTp.Charset = charset.CharsetUTF8MB4
+	a.RetTp.Collate = charset.CollationUTF8MB4
```
Comment (zz-jason) [inline expression/aggregation/descriptor.go]: s/charset.CharsetUTF8MB4/mysql.DefaultCharset/
s/charset.CollationUTF8MB4/mysql.DefaultCollationName/

Comment (zz-jason) [reply expression/aggregation/descriptor.go]: or: `charset.GetDefaultCharsetAndCollate()`

File: expression/builtin.go [hunk 3]
```diff
@@ -141,15 +141,15 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, args []Expression, retType
...
+			Charset: mysql.DefaultCharset,
+			Collate: mysql.DefaultCollationName,
 			Flag:    mysql.BinaryFlag,
 		}
 	}
 	if mysql.HasBinaryFlag(fieldType.Flag) && fieldType.Tp != mysql.TypeJSON {
 		fieldType.Charset, fieldType.Collate = charset.CharsetBin, charset.CollationBin
 	} else {
-		fieldType.Charset, fieldType.Collate = charset.CharsetUTF8, charset.CharsetUTF8
+		fieldType.Charset, fieldType.Collate = mysql.DefaultCharset, mysql.DefaultCollationName
```
Comment (zz-jason) [inline expression/builtin.go]: how about: `charset.GetDefaultCharsetAndCollate()`

File: expression/builtin.go [hunk 4]
```diff
@@ -199,7 +199,7 @@ func (b *baseBuiltinFunc) getRetTp() *types.FieldType {
 			b.tp.Tp = mysql.TypeMediumBlob
 		}
 		if len(b.tp.Charset) <= 0 {
-			b.tp.Charset, b.tp.Collate = charset.CharsetUTF8, charset.CollationUTF8
+			b.tp.Charset, b.tp.Collate = mysql.DefaultCharset, mysql.DefaultCollationName
```
Comment (zz-jason) [inline expression/builtin.go]: ditto

File: expression/builtin_cast.go [hunk 5]
```diff
@@ -1804,8 +1804,8 @@ func WrapWithCastAsJSON(ctx sessionctx.Context, expr Expression) Expression {
 		Tp:      mysql.TypeJSON,
 		Flen:    12582912, // FIXME: Here the Flen is not trusted.
 		Decimal: 0,
-		Charset: charset.CharsetUTF8,
-		Collate: charset.CollationUTF8,
+		Charset: charset.CharsetUTF8MB4,
+		Collate: charset.CollationUTF8MB4,
```
Comment (zz-jason) [inline expression/builtin_cast.go]: ditto

File: expression/builtin_cast.go [hunk 6]
```diff
@@ -1741,7 +1741,7 @@ func WrapWithCastAsString(ctx sessionctx.Context, expr Expression) Expression {
 		argLen = mysql.MaxIntWidth
 	}
 	tp := types.NewFieldType(mysql.TypeVarString)
-	tp.Charset, tp.Collate = charset.CharsetUTF8, charset.CollationUTF8
+	tp.Charset, tp.Collate = charset.CharsetUTF8MB4, charset.CollationUTF8MB4
```
Comment (zz-jason) [inline expression/builtin_cast.go]: ditto

File: expression/builtin.go [hunk 7]
```diff
@@ -141,15 +141,15 @@ func newBaseBuiltinFuncWithTp(ctx sessionctx.Context, args []Expression, retType
 			Tp:      mysql.TypeJSON,
 			Flen:    mysql.MaxBlobWidth,
 			Decimal: 0,
-			Charset: charset.CharsetUTF8,
-			Collate: charset.CollationUTF8,
+			Charset: mysql.DefaultCharset,
+			Collate: mysql.DefaultCollationName,
```
Comment (crazycs520) [inline expression/builtin.go]: why not `charset.CollationUTF8MB4`

File: expression/builtin.go (hunk 3 above)
Comment (crazycs520) [inline expression/builtin.go]: ditto

File: expression/builtin.go (hunk 4 above)
Comment (crazycs520) [inline expression/builtin.go]: ditto

File: expression/builtin_control.go [hunk 8]
```diff
@@ -81,19 +81,19 @@ func inferType4ControlFuncs(lhs, rhs *types.FieldType) *types.FieldType {
...
-			resultFieldType.Charset, resultFieldType.Collate, resultFieldType.Flag = charset.CharsetUTF8, charset.CollationUTF8, 0
+			resultFieldType.Charset, resultFieldType.Collate, resultFieldType.Flag = charset.CharsetUTF8MB4, charset.CollationUTF8MB4, 0
 			if mysql.HasBinaryFlag(rhs.Flag) || !types.IsNonBinaryStr(lhs) {
 				resultFieldType.Flag |= mysql.BinaryFlag
 			}
 		} else if types.IsBinaryStr(lhs) || types.IsBinaryStr(rhs) || !evalType.IsStringKind() {
 			types.SetBinChsClnFlag(resultFieldType)
 		} else {
-			resultFieldType.Charset, resultFieldType.Collate, resultFieldType.Flag = charset.CharsetUTF8, charset.CollationUTF8, 0
+			resultFieldType.Charset, resultFieldType.Collate, resultFieldType.Flag = mysql.DefaultCharset, mysql.DefaultCollationName, 0
```
Comment (crazycs520) [inline expression/builtin_control.go]: ditto

File: expression/builtin_control.go [hunk 9]
```diff
@@ -164,7 +164,7 @@ func (c *caseWhenFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 	}
 	fieldTp.Decimal, fieldTp.Flen = decimal, flen
 	if fieldTp.EvalType().IsStringKind() && !isBinaryStr {
-		fieldTp.Charset, fieldTp.Collate = mysql.DefaultCharset, mysql.DefaultCollationName
+		fieldTp.Charset, fieldTp.Collate = charset.CharsetUTF8MB4, charset.CollationUTF8MB4
```
Comment (crazycs520) [inline expression/builtin_control.go]: /cc @XuHuaiyu , use `mysql.DefaultCharset` or `charset.CharsetUTF8MB4`?

**Comment by winkyao** [comment]
@zz-jason @crazycs520 PTAL

File: expression/builtin_control.go (hunk 9 above)
Comment (zz-jason) [reply expression/builtin_control.go]: @XuHuaiyu, `DefaultCharset` is better. It hides the implementation details, once we change the default charset again, the code modification can be minimized.

File: executor/show.go [hunk 10]
```diff
@@ -618,7 +618,7 @@ func (e *ShowExec) fetchShowCreateTable() error {
 	buf.WriteString(") ENGINE=InnoDB")
 	charsetName := tb.Meta().Charset
 	if len(charsetName) == 0 {
-		charsetName = charset.CharsetUTF8
+		charsetName = charset.CharsetUTF8MB4
```
Comment (zz-jason) [inline executor/show.go]: s/charset.CharsetUTF8MB4/mysql.DefaultCharset/

File: expression/builtin_control.go [hunk 11]
```diff
@@ -81,19 +81,19 @@ func inferType4ControlFuncs(lhs, rhs *types.FieldType) *types.FieldType {
 			}
 		}
 		if types.IsNonBinaryStr(lhs) && !types.IsBinaryStr(rhs) {
-			resultFieldType.Charset, resultFieldType.Collate, resultFieldType.Flag = charset.CharsetUTF8, charset.CollationUTF8, 0
+			resultFieldType.Charset, resultFieldType.Collate, resultFieldType.Flag = charset.CharsetUTF8MB4, charset.CollationUTF8MB4, 0
```
Comment (zz-jason) [inline expression/builtin_control.go]: use `mysql.DefaultCharset, mysql.DefaultCollationName` instead.

File: planner/core/planbuilder.go [hunk 12]
```diff
@@ -839,8 +840,8 @@ func buildColumn(tableName, name string, tp byte, size int) *expression.Column {
 	cs, cl := types.DefaultCharsetForType(tp)
 	flag := mysql.UnsignedFlag
 	if tp == mysql.TypeVarchar || tp == mysql.TypeBlob {
-		cs = mysql.DefaultCharset
-		cl = mysql.DefaultCollationName
+		cs = charset.CharsetUTF8MB4
+		cl = charset.CollationUTF8MB4
```
Comment (zz-jason) [inline planner/core/planbuilder.go]: `cs, cl = charset.GetDefaultCharsetAndCollate()`

File: infoschema/tables.go [hunk 13]
```diff
@@ -82,8 +82,8 @@ func buildColumnInfo(tableName string, col columnInfo) *model.ColumnInfo {
 	mCollation := charset.CharsetBin
 	mFlag := mysql.UnsignedFlag
 	if col.tp == mysql.TypeVarchar || col.tp == mysql.TypeBlob {
-		mCharset = mysql.DefaultCharset
-		mCollation = mysql.DefaultCollationName
+		mCharset = charset.CharsetUTF8MB4
+		mCollation = charset.CollationUTF8MB4
```
Comment (zz-jason) [inline infoschema/tables.go]: `charset.GetDefaultCharsetAndCollate()`

File: expression/builtin_control.go (hunk 9 above)
Comment (winkyao) [reply expression/builtin_control.go]: no, this place should be utf8mb4, if we did not set the charset, it can be default charset, but in here, it should definitely be utf8mb4.

File: infoschema/tables.go (hunk 13 above)
Comment (winkyao) [reply infoschema/tables.go]: here should be definitely utf8mb4

File: planner/core/planbuilder.go (hunk 12 above)
Comment (winkyao) [reply planner/core/planbuilder.go]: ditto

File: server/server.go [hunk 14]
```diff
@@ -153,6 +153,7 @@ func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
 	var err error
 	if cfg.Socket != "" {
 		if s.listener, err = net.Listen("unix", cfg.Socket); err == nil {
+			// job.SnapshotVer == 0 means
```
Comment (crazycs520) [inline server/server.go]: ?
