### PR TITLE
types: fix issue that we can insert negative value to unsinged float column sometimes

### LINKED ISSUE #47945: we can insert negative value to unsinged float column sometimes
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table tf(a float(1, 0) unsigned);
set sql_mode='';
insert into tf values("-100");
select * from tf;
```

### 2. What did you expect to see? (Required)

In MySQL, the inserted value should be zero:

```
mysql> select * from tf;
+------+
| a    |
+------+
|    0 |
+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

A negative value is inserted in TiDB:

```
mysql> select * from tf;
+------+
| a    |
+------+
|   -9 |
+------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master, But I think it affect all versions.

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #47945

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix issue that we can insert negative value to unsinged float column sometimes
```

### CODE REVIEW

File: pkg/types/datum.go [hunk 1]
```diff
@@ -1012,9 +1012,6 @@ func ProduceFloatWithSpecifiedTp(f float64, target *FieldType, sc *stmtctx.State
 	// If no D is set, we will handle it like origin float whether M is set or not.
 	if target.GetFlen() != UnspecifiedLength && target.GetDecimal() != UnspecifiedLength {
 		f, err = TruncateFloat(f, target.GetFlen(), target.GetDecimal())
-		if err = sc.HandleOverflow(err, err); err != nil {
```
Comment (lcwangchao) [inline pkg/types/datum.go:1015]: `HandleOverflow` seems useless now, because in cast expr like `cast("1" as float(2, 1))` , `target.GetDecimal()` always return `UnspecifiedLength` ...

Comment (lcwangchao) [reply pkg/types/datum.go:1015]: In mysql cast to float with decimal will fail:

```
mysql> select cast("1" as float(1, 0));
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', 0))' at line 1
```

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
