### PR TITLE
br: support update gc ratio threshold for concurrent log restore

### LINKED ISSUE #61973: br full restore failed based on checkpoint
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、br restore
2、restore br pod during br restore
3、rerun br restore

### 2. What did you expect to see? (Required)
br restore can succeed

### 3. What did you see instead (Required)
br full restore failed based on checkpoint
`Detail BR log in /tmp/br.log.2025-06-24T12.58.44Z 
[2025/06/24 12:58:45.021 +00:00] [INFO] [collector.go:77] ["DataBase Restore failed summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0]
Error: task with ID 2000001 already exists and is running: [BR:Common:ErrInvalidArgument]invalid argument`

Image

### 4. What is your TiDB version? (Required)
sh-5.1# ./br -V
Release Version: v9.0.0-beta.1.pre-991-g22fe893
Git Commit Hash: 22fe893c88d3c51de74f20af9584d3bae7613be6
Git Branch: HEAD
Go Version: go1.23.10
UTC Build Time: 2025-06-24 11:54:49
Race Enabled: false

### LINKED ISSUE #61984: concurrent restore tasks should not reset `gc.ratio-threshold` if there is still any running restore task
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 4. What is your TiDB version? (Required)
9.0

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #61984 close #61973

Problem Summary:
concurrent restore tasks should not reset `gc.ratio-threshold` if there is still any running restore task
### What changed and how does it work?
use TXN to make sure the `gc.ratio-threshold` is set correctly
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/registry/registration.go [hunk 1]
```diff
@@ -261,12 +267,26 @@ func (r *Registry) ResumeOrCreateRegistration(ctx context.Context, info Registra
 		zap.Bool("is_restored_ts_user_specified", isRestoredTSUserSpecified))
 
 	var taskID uint64
+	var waitIDs []uint64
 
 	err = r.executeInTransaction(ctx, func(ctx context.Context, execCtx sqlexec.RestrictedSQLExecutor,
 		sessionOpts []sqlexec.OptionFuncAlias) error {
+		// find the tasks with dropping status
+		lookupSQL := fmt.Sprintf(selectDroppingStatusTasksSQLTemplate, RestoreRegistryDBName, RestoreRegistryTableName)
```
Comment (Tristan1900) [inline br/pkg/registry/registration.go]: we probably need to SELECT id, status FROM restore_registry FOR UPDATE; to lock every row and then look for dropping rows, so that it doesn't happen when we try to look for dropping row and a running row becomes dropping and we missed int

File: br/pkg/registry/registration.go [hunk 2]
```diff
@@ -282,7 +311,7 @@ func (r *Registry) ResumeOrCreateRegistration(ctx context.Context, info Registra
 			}
 
 			// if task exists and is running, return error
```
Comment (BornChanger) [inline br/pkg/registry/registration.go]:
```suggestion
			// if task exists and is running or resetting, return error
```

File: br/pkg/registry/registration.go [hunk 3]
```diff
@@ -131,6 +156,8 @@ const (
 	TaskStatusRunning TaskStatus = "running"
 	// TaskStatusPaused indicates the task is temporarily stopped
 	TaskStatusPaused TaskStatus = "paused"
+	// TaskStatusResetting indicates the task is prepared to reset configuration
```
Comment (Tristan1900) [inline br/pkg/registry/registration.go]:
```suggestion
	// TaskStatusResetting indicates the task is prepared to reset cluster configuration back before finishing.
```

File: br/pkg/registry/registration.go [hunk 4]
```diff
@@ -88,39 +90,62 @@ const (
...
+	// The process<1> is [3] [4] and the process<2> is [3] [4]
+	// If readTs<1>[4] < commitTs<2>[3] (<1>[4] can get process<2>),
+	//   readTs<2>[4] > commitTs<2>[3] > readTs<1>[4] > commitTs<1>[3] so <2>[4] cannot get process<1>
+	//
+
+	// selectResettingStatusTasksSQLTemplate is the SQL template for finding tasks with resetting status
+	selectResettingStatusTasksSQLTemplate = `SELECT id FROM %s.%s WHERE status = 'resetting'`
+
+	// selectLeftTasksSQLTemplate is the SQL template for finding the left tasks of the tasks whose IDs are given
+	selectLeftTasksSQLTemplate = `SELECT id FROM %s.%s WHERE id in (%s) AND status = 'resetting'`
```
Comment (Tristan1900) [inline br/pkg/registry/registration.go]:
```suggestion
	selectRemainingResettingTasksSQLTemplate = `SELECT id FROM %s.%s WHERE id in (%s) AND status = 'resetting'`
```
```suggestion
	selectLeftTasksSQLTemplate = `SELECT id FROM %s.%s WHERE id in (%s) AND status = 'resetting'`
```

File: br/pkg/registry/registration.go [hunk 5]
```diff
@@ -802,3 +836,57 @@ func (r *Registry) transitionStaleTaskToPaused(ctx context.Context, taskID uint6
...
+			)
+			if err != nil {
+				return errors.Trace(err)
+			}
+			if len(rows) == 0 {
+				break
+			}
+			leftId := rows[0].GetUint64(0)
+			log.Info("wait for the task finishing resetting", zap.Uint64("task id", leftId))
+			time.Sleep(5 * time.Second)
```
Comment (Tristan1900) [inline br/pkg/registry/registration.go:874]: let's perhaps give this waiting loop a max timeout, the resetting shouldn't be too long but just in case we don't want to stuck here waiting forever, what do you think?

**Review by Tristan1900 — COMMENTED** [review]
rest lgtm!

File: br/pkg/task/stream.go [hunk 6]
```diff
@@ -1562,9 +1566,12 @@ func restoreStream(
 			oldGCRatio = utils.DefaultGcRatioVal
 		}
 		log.Info("start to restore gc", zap.String("ratio", oldGCRatio))
-		if err := restoreGCFunc(oldGCRatio); err != nil {
-			log.Error("failed to restore gc", zap.Error(err))
-		}
+		err = cfg.RestoreRegistry.GlobalOperationAfterSetResettingStatus(ctx, cfg.RestoreID, func() error {
+			if err := restoreGCFunc(oldGCRatio); err != nil {
+				log.Error("failed to restore gc", zap.Error(err))
```
Comment (3pointer) [inline br/pkg/task/stream.go:1571]: should we expose this error, since it's not easy to debug?

File: br/pkg/registry/registration.go [hunk 7]
```diff
@@ -281,8 +313,8 @@ func (r *Registry) ResumeOrCreateRegistration(ctx context.Context, info Registra
 				return errors.New("invalid task ID: got 0 from lookup")
 			}
 
-			// if task exists and is running, return error
-			if status == string(TaskStatusRunning) {
+			// if task exists and is running or resetting, return error
+			if status == string(TaskStatusRunning) || status == string(TaskStatusResetting) {
```
Comment (3pointer) [inline br/pkg/registry/registration.go:318]: if this time restore come from checkpoint. 
And last time the restore was OOMed.

What will happen here?

will the taskStatus still be running or resetting?

File: br/pkg/registry/registration.go [hunk 8]
```diff
@@ -88,39 +90,65 @@ const (
...
 		AND with_sys_table = %%?
 		AND cmd = %%?
-		AND restored_ts != %%?
-		AND status IN ('running', 'paused')
 		ORDER BY id DESC
 		LIMIT 1`
 
+	// The following is a complete SQLs process to update configuration:
+	// [1] INSERT INTO the task with status = 'running'
+	// [2] waitIDs = $(SELECT id WHERE status = 'resetting')
```
Comment (3pointer) [inline br/pkg/registry/registration.go:112]: Let's say there is one restore task put `resetting` status which **happen after** collect waitIDs. 

OperationAfterWaitIDs will not wait all tasks? right?

File: br/pkg/registry/registration.go (hunk 7 above)
Comment (Leavrth) [reply br/pkg/registry/registration.go:318]: We will change the status to `paused` in the `resolveRestoreTS` at first.

File: br/pkg/registry/registration.go (hunk 8 above)
Comment (Leavrth) [reply br/pkg/registry/registration.go:112]: Yes.
If the task A's `put resetting commitTs` is larger than the task B's `waitID readTs`, so that the `put resetting commitTs` must be also larger than `insert new task with status running commitTs`. Therefore, task A must see the task B is running status and then task A will skip resetting `ratio-threshold`.

Comment (3pointer) [reply br/pkg/registry/registration.go:112]: Consider there exists 2 tasks(A/B)

If task B not wait task A and task A will skip resetting ratio-threshold.

but task A will put itself to resetting too?

if it does. how does task B be aware of it should not skip resetting too?(there is not running task when B exists)

File: br/pkg/registry/registration.go [hunk 9]
```diff
@@ -802,3 +839,62 @@ func (r *Registry) transitionStaleTaskToPaused(ctx context.Context, taskID uint6
...
+	execCtx := r.se.GetSessionCtx().GetRestrictedSQLExecutor()
+	ctx = kv.WithInternalSourceType(ctx, kv.InternalTxnBR)
+	lookupSQL := fmt.Sprintf(selectAnyUnfinishedTaskSQLTemplate, RestoreRegistryDBName, RestoreRegistryTableName)
+	rows, _, err := execCtx.ExecRestrictedSQL(ctx, nil, lookupSQL)
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if len(rows) == 0 {
+		return fn()
+	}
```
Comment (3pointer) [inline br/pkg/registry/registration.go:900]: add a log here, to check whether this restore has skipped reset.

**Review by 3pointer — APPROVED** [review]
rest LGTM
