### PR TITLE
*: lock row keys during merging back from temp index

### LINKED ISSUE #39929: Pessimistic lock not found during adding index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

It is not easy to reproduce because it requires the retry of a prewrite request.

<table>
  <tr>
   <td>Row
   </td>
   <td>Index
   </td>
   <td>Temp Index
   </td>
   <td>Index state
   </td>
   <td>Txn 1: DDL
   </td>
   <td>Txn 2: pessimistic
   </td>
   <td>Txn 0: DML
   </td>
  </tr>
  <tr>
   <td>1
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>write-only
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>update a = 2 where id = 1
   </td>
  </tr>
  <tr>
   <td>2
   </td>
   <td>
   </td>
   <td>1d, 2
   </td>
   <td>write-only
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>2
   </td>
   <td>
   </td>
   <td>1d, 2
   </td>
   <td>Write-reorg
<p>
backfill
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>2
   </td>
   <td>2
   </td>
   <td>1d, 2
   </td>
   <td>Write-reorg
<p>
merge
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>2
   </td>
   <td>2
   </td>
   <td>1d, 2
   </td>
   <td>Write-reorg
<p>
merge
   </td>
   <td>
   </td>
   <td>Begin
<p>
Update a = 3 where id = 1
<p>
(2 -> 3)
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>2
   </td>
   <td>2
   </td>
   <td>1d, 2
   </td>
   <td>Write-reorg
<p>
merge
   </td>
   <td>Begin
<p>
Read temp index and write index
<p>
(1d, 2)
<p>
commit
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>2
   </td>
   <td><del>1</del>
<p>
2
   </td>
   <td>1d, 2
   </td>
   <td>Write-reorg
<p>
merge
   </td>
   <td>
   </td>
   <td>commit
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>3
   </td>
   <td><del>1</del>
<p>
2
<p>
<del>2</del>
<p>
3
<p>
For pessimistic txn, write conflicts are converted to “pessimistic lock not found”
   </td>
   <td>1d, 2d, 3
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
</table>

Note: "1d" means a DML txn deletes the index key "1", it is converted to "1 -> deleted" and only stored by the temp index.

### 2. What did you expect to see? (Required)

The DDL should be blocked by the pessimistic lock.

### 3. What did you see instead (Required)

The DDL and DML successfully executed.

### 4. What is your TiDB version? (Required)

bb50e33509

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #39929

Problem Summary:

The problem is that a pessimistic txn never locks a non-unique index key, and then the DDL merge worker only writes to the index key. These two txns are not aware of each other. For details, see #39929.

### What is changed and how it works?

- Lock the row keys when merging back from the temp index.
- Add the temp index value format:
  - `[delete_flag] [handle] [temp_key_ver]`
  - `[normal_flag] [origin_index_value] [temp_key_ver]`
- Add a unit test for temp index value codec and a integration test for key locking.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by ekexium — APPROVED** [review]

File: table/tables/index.go [hunk 1]
```diff
@@ -228,9 +227,9 @@ func (c *index) Create(sctx sessionctx.Context, txn kv.Transaction, indexedValue
 	}
 	if err != nil || len(value) == 0 {
 		lazyCheck := sctx.GetSessionVars().LazyCheckKeyNotExists() && err != nil
-		var needPresumeKey tempIndexKeyState
```
Comment (Benjamin2037) [inline table/tables/index.go:231]: Why here need TempIndexKeyState public outside of the package?

File: ddl/index_merge_tmp_test.go [hunk 2]
```diff
@@ -376,3 +377,68 @@ func TestAddIndexMergeIndexUpdateOnDeleteOnly(t *testing.T) {
...
+	tk2.MustExec("use test")
+	tk.MustExec(`CREATE TABLE t (id int primary key, a int);`)
+	tk.MustExec(`INSERT INTO t VALUES (1, 1);`)
+
+	// Force onCreateIndex use the txn-merge process.
+	ingest.LitInitialized = false
+	tk.MustExec("set @@global.tidb_ddl_enable_fast_reorg = 1;")
+	tk.MustExec("set @@global.tidb_enable_mutation_checker = 1;")
+	tk.MustExec("set @@global.tidb_txn_assertion_level = 'STRICT';")
+	tk.MustExec("set @@global.tidb_enable_metadata_lock = 0;")
```
[the remark this answers is not in the document]
Comment (tangenta) [reply ddl/index_merge_tmp_test.go:395]: DDL will be blocked by MDL definitely if we activate a txn in `tk2`.

File: table/tables/index.go (hunk 1 above)
Comment (tangenta) [reply table/tables/index.go:231]: Because exported functions should not have the unexported return type.

```
func KeyExistInTempIndex(ctx context.Context, txn kv.Transaction, key kv.Key, distinct bool, h kv.Handle, IsCommonHandle bool) (tempIndexKeyState, kv.Handle, error) {
```

**Review by Benjamin2037 — APPROVED** [review]
LGTM
