### PR TITLE
planner, statistics: skip internal column IDs in async stats load queue

### LINKED ISSUE #64504: Unexpected log: load stats for `column = -1`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Run the cluster and try to check the logs.

```log
2025-11-13 20:02:56	 [2025/11/13 19:02:56.199 +00:00] [INFO] [read.go:699] ["Column information not found, possibly due to column being dropped"] [category=stats] [sampled=] [tableID=37543] [columnID=-1]
```

### 2. What did you expect to see? (Required)

No load would happen for columnID = -1.

### 3. What did you see instead (Required)
It happens.

### 4. What is your TiDB version? (Required)

master,v8.5

### PR DESCRIPTION
**Pull request by pinkbit256**
### What problem does this PR solve?

Issue Number: close #64504

Problem Summary:
`_tidb_rowid` uses an internal column ID (`-1`) and does not have persisted column histogram metadata. Under async stats loading, this internal ID could be inserted into the needed-items queue, and the load path later emitted noisy logs such as `columnID=-1`.

### What changed and how does it work?
- Added source filtering for internal column IDs in `statistics.ColumnStatsIsInvalid` so `cid <= 0` is not inserted into `AsyncLoadHistogramNeededItems`.
- Added defensive filtering in `loadNeededColumnHistograms` to skip `col.ID <= 0` early, while still deleting the queue item via `defer`.
- Added planner-side source filtering in `CollectColumnStatsUsage` to skip pseudo/internal columns (`col.ID <= 0`) when collecting predicate/histogram-needed columns.
- Added regression tests:
  - `TestColumnStatsIsInvalidSkipsInternalColumnID`
  - `TestLoadNeededHistogramsSkipsInternalColumnID`
  - Added `_tidb_rowid` case in `TestCollectHistNeededColumns` to assert no stats-load columns are collected.
- Ran `make bazel_lint_changed`, which updated `pkg/statistics/handle/storage/BUILD.bazel` shard count.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Validation commands:
- `make failpoint-enable && (cd pkg/statistics/handle/storage && go test -run 'TestColumnStatsIsInvalidSkipsInternalColumnID|TestLoadNeededHistogramsSkipsInternalColumnID' -tags=intest,deadlock) && make failpoint-disable`
- `make failpoint-enable && (cd pkg/statistics/handle/storage && go test -run 'TestLoadStats|TestLoadNonExistentIndexStats|TestColumnStatsIsInvalidSkipsInternalColumnID|TestLoadNeededHistogramsSkipsInternalColumnID' -tags=intest,deadlock) && make failpoint-disable`
- `make failpoint-enable && (cd pkg/planner/core/rule && go test -run 'TestCollectHistNeededColumns' -tags=intest,deadlock) && make failpoint-disable`
- `make bazel_lint_changed`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed incorrect inclusion of internal pseudo columns in statistics collection and asynchronous histogram loading, preventing unnecessary processing and potential errors when internal columns lack complete metadata.

* **Tests**
  * Added test coverage for statistics operations involving internal column identifiers.

### CODE REVIEW

**Comment by pinkbit256** [comment]
Hi, @0xPoe Can you help with reviewing the pr. Thank you!

File: pkg/statistics/column.go [hunk 1]
```diff
@@ -142,6 +142,8 @@ func ColumnStatsIsInvalid(colStats *Column, sctx planctx.PlanContext, histColl *
 		stmtctx := sctx.GetSessionVars().StmtCtx
 		if (colStats == nil || !colStats.IsStatsInitialized() || colStats.IsLoadNeeded()) &&
 			stmtctx != nil &&
+			// Internal pseudo columns (for example, _tidb_rowid with ID -1) don't have persisted column stats.
```
Comment (0xPoe) [inline pkg/statistics/column.go:145]: I suggest we move this out as a named variable, for example: `nonInternalIDs = cid > 0` or something with better name, and place the comment above the variable.

File: pkg/statistics/handle/storage/read_test.go [hunk 2]
```diff
@@ -146,3 +147,58 @@ func TestLoadNonExistentIndexStats(t *testing.T) {
...
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t(a int)")
+
+	table, err := dom.InfoSchema().TableByName(context.Background(), ast.NewCIStr("test"), ast.NewCIStr("t"))
+	require.NoError(t, err)
+	tableInfo := table.Meta()
+	h := dom.StatsHandle()
+	// Make sure this table exists in stats cache so the old path would touch session context.
+	h.GetPhysicalTableStats(tableInfo.ID, tableInfo)
```
Comment (0xPoe) [inline pkg/statistics/handle/storage/read_test.go:182]: It seems we don't check the return value here.

File: pkg/statistics/handle/storage/read_test.go [hunk 3]
```diff
@@ -146,3 +147,58 @@ func TestLoadNonExistentIndexStats(t *testing.T) {
...
+
+	rowIDItem := model.TableItemID{
```
Comment (0xPoe) [inline pkg/statistics/handle/storage/read_test.go:184]: Why is it called rowIDItem?

**Review by 0xPoe — COMMENTED** [review]
I think overall it is good. 

Thank you. 

I also found some issues during the code review. However, I think we can move them to separate issues.

https://github.com/pingcap/tidb/issues/67912

https://github.com/pingcap/tidb/issues/67913

File: pkg/statistics/handle/storage/read_test.go [hunk 4]
```diff
@@ -146,3 +147,60 @@ func TestLoadNonExistentIndexStats(t *testing.T) {
...
+	tk.MustExec("create table t(a int)")
+
+	table, err := dom.InfoSchema().TableByName(context.Background(), ast.NewCIStr("test"), ast.NewCIStr("t"))
+	require.NoError(t, err)
+	tableInfo := table.Meta()
+	h := dom.StatsHandle()
+	// Make sure this table exists in stats cache so the old path would touch session context.
+	statsTbl := h.GetPhysicalTableStats(tableInfo.ID, tableInfo)
+	require.NotNil(t, statsTbl)
+	require.Equal(t, tableInfo.ID, statsTbl.PhysicalID)
```
Comment (0xPoe) [inline pkg/statistics/handle/storage/read_test.go:218]: Does this test really trigger the async load, given that the data has no table inserted and has also never been analyzed?

**Review by 0xPoe — COMMENTED** [review]
Thanks!

File: pkg/statistics/handle/storage/read_test.go [hunk 5]
```diff
@@ -146,3 +147,95 @@ func TestLoadNonExistentIndexStats(t *testing.T) {
...
+	tk.MustExec("set @@tidb_stats_load_sync_wait = 0")
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t(a int, b int)")
+	tk.MustExec("insert into t value(1,1), (2,2);")
+	h := dom.StatsHandle()
+	tk.MustExec("flush stats_delta *.*")
+	require.NoError(t, h.Update(context.Background(), dom.InfoSchema()))
+	tk.MustExec("analyze table t")
+	tk.MustExec("set tidb_opt_objective='determinate';")
```
Comment (0xPoe) [inline pkg/statistics/handle/storage/read_test.go]: Why do we need this?

**Review by 0xPoe — COMMENTED** [review]
rest LGTM

Thanks!

**Review by 0xPoe — APPROVED** [review]
Thanks! :shipit: 

/cc @henrybw

**Review by henrybw — APPROVED** [review]
Thanks! LGTM.

In the future, it would be nice if we could consolidate these internal column ID checks (`if col.ID <= 0`, etc.) into one place (like a public function in pkg/column/ddl.go), rather than having multiple checks that repeat the same logic. That way, there would only be one source of truth for the definition of a non-internal column ID.

But this is just a minor suggestion that is not in the scope of this PR. This PR seems fine as-is.
