### PR TITLE
*: fix bug that broadcast join/MPP not compatible with clustered index

### LINKED ISSUE #21659: Broadcast join/MPP return empty result when query involves clustered index table.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. load tpch lineitem table with clustered index on
2. run query
```
select
    count(*) as numwait
from
    lineitem l1 use index()
where
    l1.l_receiptdate > l1.l_commitdate
    and exists (
        select
            *
        from
            lineitem l2 use index()
        where
            l2.l_orderkey = l1.l_orderkey
            and l2.l_suppkey <> l1.l_suppkey
    )
```
using broadcast join or MPP execution.

### 2. What did you expect to see? (Required)
query returns correct result.

### 3. What did you see instead (Required)
query returns 0.

### 4. What is your TiDB version? (Required)

tidb master commit hash 052d7169553ef7c12e5204cde80c09a9303527aa

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #21659 

Problem Summary:
as the issue described.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

When convert table ranges to key range in broadcast global read/MPP, use `IsCommonHandle` to convert the ranges correctly. Also refine the code to avoid misusing `distsql.TableRangesToKVRanges` in the future.

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by hanfei1991 — COMMENTED** [review]
LGTM

File: distsql/request_builder.go [hunk 1]
```diff
@@ -255,13 +245,23 @@ func (builder *RequestBuilder) SetTiDBServerID(serverID uint64) *RequestBuilder
...
+// TableHandleRangesToKVRanges convert table handle ranges to "KeyRanges" for multiple tables.
+func TableHandleRangesToKVRanges(sc *stmtctx.StatementContext, tid []int64, isCommonHandle bool, ranges []*ranger.Range, fb *statistics.QueryFeedback) ([]kv.KeyRange, error) {
+	if !isCommonHandle {
+		return tablesRangesToKVRanges(tid, ranges, fb), nil
+	}
+	return CommonHandleRangesToKVRanges(sc, tid, ranges)
+}
+
 // TableRangesToKVRanges converts table ranges to "KeyRange".
+// Note this function should not be exported, but currently
```
Comment (XuHuaiyu) [inline distsql/request_builder.go:257]: Use the Deprecated label?
Deprecated: Note this xx

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
