### PR TITLE
planner: support the plan cache aware of bindings

### LINKED ISSUE #29539: The Prepare Plancache and binding compatibility issues
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)
When the Prepare Plancache function is enabled, when the user uses Binding to bind the execution plan, if the bound SQL is cached by Plancache, the Binding cannot be performed.

Therefore, Binding is required to take precedence over Plancache.
### 4. What is your TiDB version? (Required)
5.3.0

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close #29539

Problem Summary:
When we cache a plan, the binding can not change the cached plan.

### What is changed and how it works?
Add the `bindSQL` to the plan cache key. So when we change the binding, we can use the new plan rather than the cached plan.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: sessionctx/stmtctx/stmtctx.go [hunk 1]
```diff
@@ -153,6 +153,9 @@ type StatementContext struct {
 		normalized string
 		digest     *parser.Digest
 	}
+	// BindSQL used to construct the key for plan cache. It records the binding used by the stmt.
+	// If the binding is not used by the stmt, the value is empty
+	BindSQL string
```
Comment (qw4990) [inline sessionctx/stmtctx/stmtctx.go:158]: How about just using bind-hints here instead of the whole bind-sql?

File: bindinfo/bind_serial_test.go [hunk 2]
```diff
@@ -78,13 +187,32 @@ func TestBindingSymbolList(t *testing.T) {
 	require.Equal(t, "t:ia", tk.Session().GetSessionVars().StmtCtx.IndexNames[0])
 	require.True(t, tk.MustUseIndex("select a, b from t where a = 3 limit 1, 100", "ia(a)"))
 
+	tk.MustExec("prepare stmt1 from 'select a, b from t where a = 3 limit 1, 100';")
```
Comment (qw4990) [inline bindinfo/bind_serial_test.go:190]: Please add one more separate test for this feature like `TestPrepareCacheWithBinding`.

File: bindinfo/bind_serial_test.go [hunk 3]
```diff
@@ -26,10 +28,300 @@ import (
...
+
+	tk.MustExec("execute stmt6;")
+	require.Equal(t, "t2:idx_c", tk.Session().GetSessionVars().StmtCtx.IndexNames[0])
+	tkProcess = tk.Session().ShowProcess()
+	ps = []*util.ProcessInfo{tkProcess}
+	tk.Session().SetSessionManager(&mockSessionManager1{PS: ps})
+	res = tk.MustQuery("explain for connection " + strconv.FormatUint(tkProcess.ID, 10))
+	require.True(t, tk.MustUseIndex4ExplainFor(res, "idx_c(c)"), res.Rows())
+
+	// TestExplain
```
Comment (qw4990) [inline bindinfo/bind_serial_test.go:228]: Please add one more test of using hints to control index selection in this section.

**Review by qw4990 — APPROVED** [review]

**Review by time-and-fate — APPROVED** [review]
