### PR TITLE
expression: add linear search for the interval function

### LINKED ISSUE #18525: INTERVAL function returns incorrect results & wrong warning
### 1. Minimal reproduce step (Required)

````
drop table if exists t1;
create table t1 (col0 BLOB, col1 CHAR(74), col2 DATE UNIQUE);
insert into t1 values ('l', '7a34bc7d-6786-461b-92d3-fd0a6cd88f39', '1000-01-03');
insert into t1 values ('l', NULL, '1000-01-04');
insert into t1 values ('b', NULL, '1000-01-02');

-- result incorrect
select INTERVAL( ( CONVERT( -11752 USING utf8 ) ), 6558853612195285496, `col1`) from t1;

drop table t1;
````

### 2. What did you expect to see? (Required)

````
mysql> select INTERVAL( ( CONVERT( -11752 USING utf8 ) ), 6558853612195285496, `col1`) from t1;
+--------------------------------------------------------------------------+
| INTERVAL( ( CONVERT( -11752 USING utf8 ) ), 6558853612195285496, `col1`) |
+--------------------------------------------------------------------------+
|                                                                        0 |
|                                                                        0 |
|                                                                        0 |
+--------------------------------------------------------------------------+
3 rows in set (0.00 sec)
````

### 3. What did you see instead (Required)

````
mysql> select INTERVAL( ( CONVERT( -11752 USING utf8 ) ), 6558853612195285496, `col1`) from t1;
+--------------------------------------------------------------------------+
| INTERVAL( ( CONVERT( -11752 USING utf8 ) ), 6558853612195285496, `col1`) |
+--------------------------------------------------------------------------+
|                                                                        0 |
|                                                                        2 |
|                                                                        2 |
+--------------------------------------------------------------------------+
3 rows in set, 1 warning (0.00 sec)


mysql> show warnings;
+---------+------+-------------------------------------------------------------------------+
| Level   | Code | Message                                                                 |
+---------+------+-------------------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect FLOAT value: '7a34bc7d-6786-461b-92d3-fd0a6cd88f39' |
+---------+------+-------------------------------------------------------------------------+
1 row in set (0.00 sec)
````

### 4. Affected version (Required)

````
commit a9177fe846bf2638261f64514ab4ebd0155cc60c (HEAD -> master, origin/master, origin/HEAD)
Author: Boqin Qin <bobbqqin@bupt.edu.cn>
Date:   Mon Jul 6 19:28:12 2020 +0800
````

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #18525 

Problem Summary:  due to the binary search algorithm for the `interval` function we currently employed can't handle NULL values correctly, it caused different result from MySQL. After research the MySQL's implementation for this function, I figured out that MySQL uses linear search if there is a `NULL` argument, therefore I added this functionality to our `interval` function.

### What is changed and how it works?

What's Changed: linear search is added for `interval` functions.

How it Works: we use linear search instead of binary search if any of the argument might be NULL.

### Related changes

- Need to cherry-pick to the 4.0 and 3.0.

### Check List 

Tests 

- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- No release note.

### CODE REVIEW

**Comment by ichn-hu** [comment]
@XuHuaiyu Hi Huaiyu~ PTAL~

**Comment by ichn-hu** [comment]
@SunRunAway PTAL as well~

**Comment by ichn-hu** [comment]
@XuHuaiyu @SunRunAway friendly ping~

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Comment by SunRunAway** [comment]
You can try to fix the coprocessor version.

**Comment by ichn-hu** [comment]
@XuHuaiyu PTAL

File: expression/builtin_compare_test.go [hunk 1]
```diff
@@ -250,6 +255,9 @@ func (s *testEvaluatorSuite) TestIntervalFunc(c *C) {
 		}
 		v, err := evalBuiltinFunc(f, chunk.Row{})
 		c.Assert(err, IsNil)
+		if v.GetInt64() != t.ret {
+			fmt.Println(i, t)
```
Comment (XuHuaiyu) [inline expression/builtin_compare_test.go:259]: What's this for?

File: expression/builtin_compare.go [hunk 2]
```diff
@@ -855,17 +864,18 @@ func (c *intervalFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 	}
 	var sig builtinFunc
 	if allInt {
-		sig = &builtinIntervalIntSig{bf}
+		sig = &builtinIntervalIntSig{bf, hasNullable}
 		sig.setPbCode(tipb.ScalarFuncSig_IntervalInt)
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:868]: We need to add new pbcode for the sigs when hasNullable is true.
And we can use the new pbcode [here](https://github.com/pingcap/tidb/pull/19543/files#diff-8fae0b14f3eaaced7305742a19673d50R227) to check.

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
