### PR TITLE
*: fix auto analyze worker crash when killed by global memory limit

### LINKED ISSUE #39947: auto analyze worker crashed when killed by global memory limit
## Bug Report
auto analyze worker panicked and did not recover when killed by global memory limit

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. set global memory limit to 6G
2. consume 5G long-existing memory
3. trigger an auto analyze who consumes 1G and appears as the top 1 memory consumer

### 2. What did you expect to see? (Required)
auto analyze got killed, but triggered next time

### 3. What did you see instead (Required)
auto analyze got killed, but never got triggered again

### 4. What is your TiDB version? (Required)
v6.5

### PR DESCRIPTION
**Pull request by chrysan**
### What problem does this PR solve?

Issue Number: close #39947 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: executor/executor.go [hunk 1]
```diff
@@ -1975,7 +1975,7 @@ func ResetContextOfStmt(ctx sessionctx.Context, s ast.StmtNode) (err error) {
 	if _, ok := s.(*ast.AnalyzeTableStmt); ok {
 		sc.InitMemTracker(memory.LabelForAnalyzeMemory, -1)
 		vars.MemTracker.SetBytesLimit(-1)
-		vars.MemTracker.AttachTo(GlobalAnalyzeMemoryTracker)
+		sc.MemTracker.AttachTo(GlobalAnalyzeMemoryTracker)
```
Comment (xuyifangreeneyes) [inline executor/executor.go:1978]: The normal tracker chain is `stmt tracker -> session tracker -> global tracker`. Here we change it to `stmt tracker -> global analyze tracker -> global tracker`. I am not sure whether it has some unexpected impact. cc @XuHuaiyu

**Review by wshwsh12 — APPROVED** [review]

File: executor/executor.go (hunk 1 above)
Comment (chrysan) [reply executor/executor.go]: We must attach stmt tracker to session tracker, so that global-mem-limit can see manual analyze as top1 consumer from session manager. 
While session manager cannot see auto-analyze which is run from a background shared session pool, will handle it in another PR.

Comment (chrysan) [reply executor/executor.go]: https://github.com/pingcap/tidb/pull/39978
