### PR TITLE
txn: update table delta map when really lock keys

### LINKED ISSUE #20975: Unexpected "Information schema is changed" when commits
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### 2. What did you expect to see? (Required)
Commit successfully.
### 3. What did you see instead (Required)
Information schema is changed during the execution of the statement
### 4. What is your TiDB version? (Required)

4.0 master

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #20975

Problem Summary:

```sql
mysql> drop table t2, t1;
Query OK, 0 rows affected (0.04 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> update t1 set a=a;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0

/* session 2 */ mysql> create table t2(a int);
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```
### What is changed and how it works?

What's Changed:
Update missing table ID to table delta map when there has key locked. And skip SchemaChecker when table delta map is empty.

### Related changes

- No

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- txn: Fix missing table delta map track when query has locks.

### CODE REVIEW

**Comment by blacktear23** [comment]
@cfzjywxk PTAL

File: executor/batch_point_get.go [hunk 1]
```diff
@@ -313,6 +317,14 @@ func (e *BatchPointGetExec) initialize(ctx context.Context) error {
 		if err != nil {
 			return err
 		}
+		if hasKeys {
```
Comment (cfzjywxk) [inline executor/batch_point_get.go:320]: Non RC isolation level needs to update the delta map too in code block L270-L283.

File: session/session.go [hunk 2]
```diff
@@ -437,8 +437,11 @@ func (s *session) doCommit(ctx context.Context) error {
 	for id := range relatedPhysicalTables {
 		physicalTableIDs = append(physicalTableIDs, id)
 	}
-	// Set this option for 2 phase commit to validate schema lease.
-	s.txn.SetOption(kv.SchemaChecker, domain.NewSchemaChecker(domain.GetDomain(s), s.sessionVars.TxnCtx.SchemaVersion, physicalTableIDs))
+	// If table delta is empty means no changes for any table. So do not need SchemaChecker.
+	if len(physicalTableIDs) > 0 {
```
Comment (cfzjywxk) [inline session/session.go:441]: This is not needed by now as there is txn dirty check in the commit phase, and it's a bit risky to change it in the release branch.

File: executor/executor.go [hunk 3]
```diff
@@ -192,6 +192,11 @@ func (e *baseExecutor) Next(ctx context.Context, req *chunk.Chunk) error {
 	return nil
 }
 
+func (e *baseExecutor) updateDeltaForTableID(id int64) {
```
Comment (cfzjywxk) [inline executor/executor.go:195]: Mutex is needed in `UpdateDeltaForTable`.

**Comment by cfzjywxk** [comment]
@you06 @MyonKeminta PTAL

**Comment by blacktear23** [comment]
@cfzjywxk Shall we cherry-pick it to master?

File: executor/batch_point_get.go (hunk 1 above)
Comment (blacktear23) [reply executor/batch_point_get.go:325]: Updated PTAL

File: executor/batch_point_get.go [hunk 4]
```diff
@@ -264,6 +264,7 @@ func (e *BatchPointGetExec) initialize(ctx context.Context) error {
 		keys[i] = key
 	}
 
+	hasKeys := false
```
Comment (cfzjywxk) [inline executor/batch_point_get.go:267]: Maybe `hasKeysToLock` is better.

File: executor/batch_point_get.go [hunk 5]
```diff
@@ -273,6 +274,9 @@ func (e *BatchPointGetExec) initialize(ctx context.Context) error {
 		for _, idxKey := range indexKeys {
 			// lock the non-exist index key, using len(val) in case BatchGet result contains some zero len entries
 			if val := handleVals[string(idxKey)]; len(val) == 0 {
+				if !hasKeys {
+					hasKeys = true
+				}
```
Comment (cfzjywxk) [inline executor/batch_point_get.go:279]: The flag should be set under `if len(lockKeys) > 0` before or after L283 , currently if all index correspond handle keys do exist the flag will not be set.

File: executor/batch_point_get.go [hunk 6]
```diff
@@ -304,14 +308,27 @@ func (e *BatchPointGetExec) initialize(ctx context.Context) error {
...
 			existKeys = append(existKeys, key)
 		}
 	}
 	// Lock exists keys only for Read Committed Isolation.
-	if e.lock && rc {
-		err = e.lockKeys(ctx, existKeys)
-		if err != nil {
-			return err
+	if e.lock {
+		if rc {
```
Comment (cfzjywxk) [inline executor/batch_point_get.go:319]: We could set the `hasKeys` flag by the condition `if len(existKeys) > 0` before or after the `lockkeys` function call for the RC isolation level.

File: executor/executor_test.go [hunk 7]
```diff
@@ -6508,3 +6508,152 @@ func (s *testSuite) TestTxnRetry(c *C) {
...
+	tk2.MustExec("create table t2(a int)")
+	tk1.MustExec("commit")
+
+	tk1.MustExec("begin pessimistic")
+	tk1.MustExec("select * from t1 where id=1 for update")
+	tk2.MustExec("drop table t2")
+	tk1.MustExec("commit")
+}
+
+func (s *testSuite) TestIssue20975SelectForUpdateBatchPointGet(c *C) {
```
Comment (cfzjywxk) [inline executor/executor_test.go:6557]: We need to add some cases for `pointGetExec` and `batchPointGetExec`
- Isolation is default RR(SI).
- Using non-handle unique keys.
- The correspond handle keys do not exist.
These unique keys should be locked and thus these lock only transactions will get schema check during 2pc.

File: executor/executor.go (hunk 3 above)
Comment (you06) [reply executor/executor.go:195]: There is already mutex inside `txnCtx.UpdateDeltaForTable`.

**Comment by blacktear23** [comment]
@cfzjywxk PTAL

File: executor/executor_test.go [hunk 8]
```diff
@@ -6508,3 +6508,223 @@ func (s *testSuite) TestTxnRetry(c *C) {
 	tk.MustExec("commit")
 	tk.MustQuery("select * from t").Check(testkit.Rows("10"))
 }
+
+func issue20975Prepare(c *C, store kv.Storage) (*testkit.TestKit, *testkit.TestKit) {
```
Comment (jackysp) [inline executor/executor_test.go:6512]: It is better to `set tidb_enable_amend_pessimistic_txn = 0` in this function. The default value maybe change in future.

**Comment by you06** [comment]
The schema check will be skipped here because the ddl lease is 0s.
https://github.com/pingcap/tidb/blob/e3b62d8c9b59db35d119574893614849c37bb449/domain/schema_validator.go#L224-L226

**Comment by blacktear23** [comment]
> The schema check will be skipped here because the ddl lease is 0s.
> https://github.com/pingcap/tidb/blob/e3b62d8c9b59db35d119574893614849c37bb449/domain/schema_validator.go#L224-L226

Is this has some problem? For tidb server the lease time should be 45s in configuration file. So seems this check always fails.

**Comment by you06** [comment]
> > The schema check will be skipped here because the ddl lease is 0s.
> > https://github.com/pingcap/tidb/blob/e3b62d8c9b59db35d119574893614849c37bb449/domain/schema_validator.go#L224-L226
> 
> Is this has some problem? For tidb server the lease time should be 45s in configuration file. So seems this check always fails.

I think the problem comes here

https://github.com/pingcap/tidb/blob/e3b62d8c9b59db35d119574893614849c37bb449/executor/executor_test.go#L165

**Comment by cfzjywxk** [comment]
Maybe we could move the test cases to `pessimistic_test.go` and the lease is not zero.

**Comment by blacktear23** [comment]
> Maybe we could move the test cases to `pessimistic_test.go` and the lease is not zero.

Good idea.

**Comment by blacktear23** [comment]
> > > The schema check will be skipped here because the ddl lease is 0s.
> > > https://github.com/pingcap/tidb/blob/e3b62d8c9b59db35d119574893614849c37bb449/domain/schema_validator.go#L224-L226
> > 
> > 
> > Is this has some problem? For tidb server the lease time should be 45s in configuration file. So seems this check always fails.
> 
> I think the problem comes here
> 
> https://github.com/pingcap/tidb/blob/e3b62d8c9b59db35d119574893614849c37bb449/executor/executor_test.go#L165

Why those test case set lease to zero?

**Comment by you06** [comment]
No idea why changing default lease value, it does pollutes the test environment.

**Comment by you06** [comment]
There need to be tests for RC isolation level, rest LGTM

File: executor/executor.go [hunk 9]
```diff
@@ -926,7 +931,22 @@ func (e *SelectLockExec) Next(ctx context.Context, req *chunk.Chunk) error {
 		lockWaitTime = kv.LockNoWait
 	}
 
-	return doLockKeys(ctx, e.ctx, newLockCtx(e.ctx.GetSessionVars(), lockWaitTime), e.keys...)
+	err = doLockKeys(ctx, e.ctx, newLockCtx(e.ctx.GetSessionVars(), lockWaitTime), e.keys...)
+	if err == nil && len(e.keys) > 0 {
```
Comment (cfzjywxk) [inline executor/executor.go:935]: Since `tblID2Handle` will not change during execution, it's better to do the update one time instead of every `Next` call.

**Comment by cfzjywxk** [comment]
@lysu @jackysp PTAL

**Review by jackysp — COMMENTED** [review]
LGTM

**Comment by lysu** [comment]
LGTM

**Comment by lysu** [comment]
@you06 PTAL

**Comment by cfzjywxk** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by blacktear23** [comment]
@cfzjywxk shall we cherry-pick it to master?
