### PR TITLE
ddl: fix issue when add foreign key ddl job

### LINKED ISSUE #38168: add foreign key constrain need validation
## Dev Task 

add validate when do add foreign key ddl job.

This is a sub task of https://github.com/pingcap/tidb/issues/36982

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #38168

Problem Summary:  Add more check when add foreign key ddl job.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/foreign_key.go [hunk 1]
```diff
@@ -645,6 +647,68 @@ func checkAddForeignKeyValidInOwner(d *ddlCtx, t *meta.Meta, job *model.Job, sch
 	err = checkAddForeignKeyValid(is, schema, tbInfo, fk, fkCheck)
 	if err != nil {
 		job.State = model.JobStateCancelled
+		return errors.Trace(err)
 	}
-	return errors.Trace(err)
+	// TODO(crazycs520): fix me. we need to do multi-schema change when add foreign key constraint.
```
Comment (lcwangchao) [inline ddl/foreign_key.go:652]: You mean multiple state change?

**Review by lcwangchao — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
