### PR TITLE
meta,structure: modify structure hash API to avoid conflict on auto table ID key

### LINKED ISSUE #25197: allocHandleIDs conflicts very heavy when there are lots of tables in one database
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. creating 8192 tables for sysbench:
  sysbench --tables=8192 --table-size=0 --threads=32 --auto-inc=false oltp_insert prepare
2. run oltp_insert for these tables:
  sysbench --tables=8192 --table-size=0 --threads=1024 --auto-inc=false oltp_insert run

### 2. What did you expect to see? (Required)
`sysbench run` run stablely.

### 3. What did you see instead (Required)
TPS is very low, less than 10. And many error logs in TiDB:
```
[2021/06/04 14:48:00.375 +08:00] [INFO] [prewrite.go:261] ["prewrite encounters lock"] [session=985] [lock="key: 6d44423a3533000000fc0000000000000048, primary: 6d44423a3533000000fc0000000000000048, txnStartTS: 425404472942919752, lockForUpdateTS:0, minCommitTs:425404472942919753, ttl: 3371, type: Put, UseAsyncCommit: false"]
```

### 4. What is your TiDB version? (Required)
master.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #25197

Problem Summary:

**Insert into different tables should not conflict on the table meta key**, but it does!

`GenAutoTableID()` use the structure `HInc` API, that API is not scalable because the hash structure maintain a meta key to store the hash table size.

### What is changed and how it works?

What's Changed:

Provide a `IgnoreHashMeta` option for the structure API.

How it Works:

If `IgnoreHashMeta` is called, the structure API will ignore the hash related things.
That means `HLen` API is not available any more with this option.

TiDB do not use `HLen`, so it's set to get rid of the meta key conflict.

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

### Release note 

- Fix table meta key conflict for concurrent connections visiting different tables. **Downgrade after this change might be problematic.**

### CODE REVIEW

File: structure/hash.go [hunk 1]
```diff
@@ -145,6 +156,11 @@ func (t *TxStructure) updateHash(key []byte, field []byte, fn func(oldValue []by
 
 // HLen gets the number of fields in a hash.
 func (t *TxStructure) HLen(key []byte) (int64, error) {
+	if t.ignoreHashMeta {
```
Comment (hicqu) [inline structure/hash.go:159]: If TiDB doesn't use `HLen`, how about remove all logic about it?

Comment (hicqu) [reply structure/hash.go:159]: I worry that someone could call `HLen` in future.

**Comment by hicqu** [comment]
Rest LGTM. Thank you very much! I can continue my test based on it.

File: structure/hash.go (hunk 1 above)
Comment (tiancaiamao) [reply structure/hash.go:159]: `HLen` API is reasonable, you can find the structure package provides API similar to Redis, and Redis also has [HLen](https://www.tutorialspoint.com/redis/hashes_hlen.htm).
This package design is general, it can be used by outside projects.
I think it is better to provide an option instead of limit its ability to TiDB only.

Comment (tiancaiamao) [reply structure/hash.go:159]: Without this PR, it means whether you use `HLen` or not, you pay for the cost.
With this PR, it means you can choose to pay for exactly what you want.
If you wipe out `HLen`, it means this functionality is missing, you don't have choice.

I prefer providing flexible, and let them do their choices.

**Review by hicqu — APPROVED** [review]

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]

File: structure/hash.go [hunk 2]
```diff
@@ -127,6 +134,10 @@ func (t *TxStructure) updateHash(key []byte, field []byte, fn func(oldValue []by
 		return errors.Trace(err)
 	}
 
+	if t.ignoreHashMeta {
```
Comment (djshow832) [inline structure/hash.go:137]: When TiDB downgrades to an older version that reads and writes hash meta, but now the hash meta is all wrong, what will happen?

Comment (tiancaiamao) [reply structure/hash.go:137]: It doesn't matter, even in the downgrade case the data is wrong, old TiDB never use those data.

**Comment by disksing** [comment]
Why not remove HLen directly? Do `meta` have users other than TiDB?

**Comment by tiancaiamao** [comment]
Since so many of you dislike the `HLen` API, I remove it. @hicqu  @disksing 

PTAL @AilinKid @djshow832

File: structure/hash.go [hunk 3]
```diff
@@ -127,48 +112,20 @@ func (t *TxStructure) updateHash(key []byte, field []byte, fn func(oldValue []by
...
 		return ErrWriteOnSnapshot
 	}
-	metaKey := t.encodeHashMetaKey(key)
-	meta, err := t.loadHashMeta(metaKey)
-	if err != nil || meta.IsEmpty() {
-		return errors.Trace(err)
-	}
 
-	var value []byte
+	// var value []byte
```
Comment (xhebox) [inline structure/hash.go:124]: Maybe just remove this line?

File: structure/structure.go [hunk 4]
```diff
@@ -42,7 +42,8 @@ func NewStructure(reader kv.Retriever, readWriter kv.RetrieverMutator, prefix []
 // TxStructure supports some simple data structures like string, hash, list, etc... and
 // you can use these in a transaction.
 type TxStructure struct {
-	reader     kv.Retriever
-	readWriter kv.RetrieverMutator
-	prefix     []byte
+	reader         kv.Retriever
+	readWriter     kv.RetrieverMutator
+	prefix         []byte
+	ignoreHashMeta bool
```
Comment (xhebox) [inline structure/structure.go:48]: And remove `ignoreHashMeta`?

**Review by xhebox — COMMENTED** [review]
Rest LGTM

File: structure/hash.go (hunk 2 above)
Comment (djshow832) [reply structure/hash.go]: I don't think so. For example, `HDel` checks meta hash, and if `meta.IsEmpty()`, it will report an error.

File: structure/structure.go (hunk 4 above)
Comment (tiancaiamao) [reply structure/structure.go]: Done

File: structure/hash.go (hunk 3 above)
Comment (tiancaiamao) [reply structure/hash.go]: Done

File: structure/hash.go (hunk 2 above)
Comment (tiancaiamao) [reply structure/hash.go]: So we can highlight the downgrade compatibility? there are many new feature, if TiDB upgrade and use the new feature, then downgrade, there will be a problem. Any suggestion?

**Comment by sticnarf** [comment]
@tiancaiamao Need this PR be picked to release branches?
