### PR TITLE
expression, executor: allow insert strings with overflowed trailing spaces

### LINKED ISSUE #10392: Incompatible with MySQL 8.0 about insert over length string into `CHAR` column
## Description
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
➜  ~ tidiff 'select @@sql_mode'
MySQL(127.0.0.1:3306)> select @@sql_mode
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.002 sec)

TiDB(127.0.0.1:4000)> select @@sql_mode
+--------------------------------------------+
| @@sql_mode                                 |
+--------------------------------------------+
| STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set (0.003 sec)

➜  ~ tidiff 'create table vctt (v varchar(4), c char(4))'
MySQL(127.0.0.1:3306)> create table vctt (v varchar(4), c char(4))
Query OK (0.006 sec)

TiDB(127.0.0.1:4000)> create table vctt (v varchar(4), c char(4))
Query OK (0.007 sec)

➜  ~ tidiff 'insert into vctt values ("ab  ", "ab   ")'
MySQL(127.0.0.1:3306)> insert into vctt values ("ab  ", "ab   ")
Query OK (0.003 sec)

TiDB(127.0.0.1:4000)> insert into vctt values ("ab  ", "ab   ")
Error 1406: Data too long for column 'c' at row 1

➜  ~ tidiff 'select * from vctt'
MySQL(127.0.0.1:3306)> select * from vctt
+-----------+
| v    | c  |
+-----------+
| ab   | ab |
+-----------+
1 row in set (0.001 sec)

TiDB(127.0.0.1:4000)> select * from vctt
0 row in set (0.107 sec)
```

2. What did you expect to see?

Truncate over length string successfully.

3. What did you see instead?

Got error `Error 1406: Data too long for column 'c' at row 1`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                            |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.8-24-g7b36cdfb6-dirty
Git Commit Hash: 7b36cdfb6e8a4c279fc360ed79cf1c499b553688
Git Branch: failpoint-2.1
UTC Build Time: 2019-04-30 08:26:17
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```




## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @XuHuaiyu

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #10392 

Problem Summary:

For now, TiDB will complain with error if string inserted are longer than `varchar` or `char`'s lenght constraint with trailing spaces, however, as in MySQL's doc

> For VARCHAR columns, trailing spaces in excess of the column length are truncated prior to insertion and a warning is generated, regardless of the SQL mode in use. For CHAR columns, truncation of excess trailing spaces from inserted values is performed silently regardless of the SQL mode.

https://dev.mysql.com/doc/refman/8.0/en/char.html

### What is changed and how it works?

Make overflowed trailing spaces trimed, and report warning for `varchar`.

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- Need to cherry-pick to the release branch 4.0, 3.0.

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: types/datum.go [hunk 1]
```diff
@@ -972,13 +974,27 @@ func ProduceStrWithSpecifiedTp(s string, tp *FieldType, sc *stmtctx.StatementCon
...
-			err = ErrDataTooLong.GenWithStack("Data Too Long, field len %d, data len %d", flen, len(s))
+			characterLen = len(s)
+			overflowed = s[flen:]
 			s = truncateStr(s, flen)
-		} else if tp.Tp == mysql.TypeString && IsBinaryStr(tp) && len(s) < flen && padZero {
+		}
+
+		if len(overflowed) != 0 {
+			trimed := strings.TrimRight(overflowed, " \t\n\r")
+			if len(trimed) == 0 && ((tp.Tp == mysql.TypeVarchar && !IsBinaryStr(tp)) || (tp.Tp == mysql.TypeString && !IsBinaryStr(tp))) {
```
Comment (wshwsh12) [inline types/datum.go:988]: if len(trimed) == 0 && !IsBinaryStr(tp) && IsTypeChar(tp) {....}    is enough?

**Review by wshwsh12 — COMMENTED** [review]
Rest LGTM

File: types/datum.go (hunk 1 above)
Comment (ichn-hu) [reply types/datum.go:988]: Sure~

**Comment by ichn-hu** [comment]
@wshwsh12 PTALA

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Comment by ichn-hu** [comment]
@XuHuaiyu I picked up the original issue, please reward again.

**Comment by ichn-hu** [comment]
@XuHuaiyu PTAL

**Comment by ichn-hu** [comment]
@XuHuaiyu Friendly ping~

File: types/datum.go [hunk 2]
```diff
@@ -952,10 +952,12 @@ func (d *Datum) convertToString(sc *stmtctx.StatementContext, target *FieldType)
 func ProduceStrWithSpecifiedTp(s string, tp *FieldType, sc *stmtctx.StatementContext, padZero bool) (_ string, err error) {
 	flen, chs := tp.Flen, tp.Charset
 	if flen >= 0 {
+		var overflowed string
```
Comment (XuHuaiyu) [inline types/datum.go:955]: add a comment for this

File: executor/insert_test.go [hunk 3]
```diff
@@ -1500,6 +1500,20 @@ func (s *testSerialSuite) TestIssue20768(c *C) {
...
+func (s *testSuite9) TestIssue10402(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("create table vctt (v varchar(4), c char(4))")
+	tk.MustExec("insert into vctt values ('ab  ', 'ab   ')")
+	tk.MustQuery("select * from vctt").Check(testkit.Rows("ab   ab"))
+	tk.MustExec("delete from vctt")
+	tk.Se.GetSessionVars().StmtCtx.SetWarnings(nil)
+	tk.MustExec("insert into vctt values ('ab\\n\\n\\n', 'ab\\n\\n\\n'), ('ab\\t\\t\\t', 'ab\\t\\t\\t'), ('ab    ', 'ab    '), ('ab\\r\\r\\r', 'ab\\r\\r\\r')")
+	c.Check(tk.Se.GetSessionVars().StmtCtx.WarningCount(), Equals, uint16(4))
```
Comment (XuHuaiyu) [inline executor/insert_test.go:1512]: Can we check the result of `show warnings`?

**Comment by ichn-hu** [comment]
@XuHuaiyu PTALA

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
