### PR TITLE
executor: fix pointGet and batchPointGet for global index

### LINKED ISSUE #47513: pointGet and batchPointGet for global index has wrong plan
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
enable-global-index = true in config.

```SQL
use test;
CREATE TABLE t ( a int, b int, c int default 0)
						PARTITION BY RANGE (a) (
		PARTITION p0 VALUES LESS THAN (10),
		PARTITION p1 VALUES LESS THAN (20),
		PARTITION p2 VALUES LESS THAN (30),
		PARTITION p3 VALUES LESS THAN (40));
INSERT INTO t(a, b) values(1, 1), (2, 2), (3, 3), (15, 15), (25, 25), (35, 35);
ALTER TABLE t ADD UNIQUE INDEX idx(b);
ANALYZE TABLE t;
select * from t use index(idx) where b in (15, 25, 35);  -- panic
explain select * from t use index(idx) where b = 15;
```
### 2. What did you expect to see? (Required)
* batchPointGet for global index should not panic;
* pointGet for global index should go PointGetPlan, as this is more efficient than indexReader/indexScan;

### 3. What did you see instead (Required)
* batchPointGet panic, meets "unique index must include all partition columns"
* pointGet goes indexReader/indexLookUp
<img width="959" alt="image" src="https://github.com/pingcap/tidb/assets/20724552/c93e713f-6c65-41af-849a-c29bb390b0c5">


### 4. What is your TiDB version? (Required)
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.5.0-alpha-44-ga01db41bd5
Edition: Community
Git Commit Hash: a01db41bd51a94816de4027dc42732d1a2307b96
Git Branch: HEAD
UTC Build Time: 2023-10-10 07:17:08
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by L-maple**
### What problem does this PR solve?

Issue Number: close #47513

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by mjonss** [comment]
@L-maple Hi, we just merged a PR to change the code layout in the repository, 47123, could you please merge latest master and resolve possible conflicts?

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -1940,6 +2015,10 @@ func getColumnPosInIndex(idx *model.IndexInfo, colName *model.CIStr) int {
 			return i
 		}
 	}
+
+	if idx.Global {
+		return -1
```
Comment (mjonss) [inline planner/core/point_get_plan.go:2020]: Could we use a named constant instead of the anonymous `-1` to clarify what it means?

**Review by mjonss — COMMENTED** [review]
Have you considered to separate the two issues into separate PRs, they seems unrelated?

File: planner/core/point_get_plan.go (hunk 1 above)
Comment (L-maple) [reply planner/core/point_get_plan.go]: resolved

File: pkg/planner/core/point_get_plan.go [hunk 2]
```diff
@@ -1157,6 +1160,64 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
 	return nil
 }
 
+func checkGlobalIndexForPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, pairs []nameValuePair, check bool) *PointGetPlan {
+	tblName, tblAlias := getSingleTableNameAndAlias(selStmt.From)
```
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go:1164]: Cannot these be provided as arguments, since they are done already in the calling function?

File: pkg/planner/core/point_get_plan.go [hunk 3]
```diff
@@ -1157,6 +1160,64 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
...
+	for _, idxInfo := range tbl.Indices {
+		if !idxInfo.Unique || idxInfo.State != model.StatePublic || idxInfo.Invisible || idxInfo.MVIndex ||
+			!indexIsAvailableByHints(idxInfo, tblName.IndexHints) {
+			continue
+		}
+		if !idxInfo.Global {
+			continue
+		}
+		idxValues, idxConstant, colsFieldType := getIndexValues(idxInfo, pairs)
+		if idxValues == nil {
```
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go:1196]: Safer to check `len(idxValues) == 0`

File: pkg/planner/core/point_get_plan.go [hunk 4]
```diff
@@ -1157,6 +1160,64 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
...
+				logutil.BgLogger().Warn("get information schema failed", zap.Error(err))
+				return nil
+			}
+		}
+		if check {
+			if latestIndex, ok := latestIndexes[idxInfo.ID]; !ok || latestIndex.State != model.StatePublic {
+				continue
+			}
+		}
+		p := newPointGetPlan(ctx, dbName, schema, tbl, names)
```
Comment (mjonss) [inline pkg/planner/core/point_get_plan.go:1211]: Should we also handle the explicit partition selection somewhere? Like `SELECT * FROM t partition(p1) where unique_key = 3` (see tblName.PartitionNames)

**Review by mjonss — COMMENTED** [review]
Looks good, please also check `TestTruncatePartitionWithGlobalIndex` which seems to be failing after this PR.

File: pkg/planner/core/point_get_plan.go (hunk 2 above)
Comment (L-maple) [reply pkg/planner/core/point_get_plan.go:1164]: I considered these be provideed as arguments, but the disadvantage is arguments are too many. I don't think too many arguments is good. 
@mjonss , what's your advice？If you think these arguments should not be done secondly in this PR, I will refactor this.

File: pkg/planner/core/point_get_plan.go (hunk 4 above)
Comment (L-maple) [reply pkg/planner/core/point_get_plan.go:1211]: Thanks for your remind! 
I will check the tblName.PartitionNames, the function will return nil if len(tblName.PartitionNames) > 0.

Comment (L-maple) [reply pkg/planner/core/point_get_plan.go:1215]: I check it in this method.

File: pkg/executor/point_get_test.go [hunk 5]
```diff
@@ -429,3 +429,71 @@ func TestWithTiDBSnapshot(t *testing.T) {
 
 	tk.MustQuery("select * from xx").Check(testkit.Rows("1", "7"))
 }
+
+func TestPointGetIssue25167(t *testing.T) {
```
Comment (Defined2014) [inline pkg/executor/point_get_test.go:433]: Remove it, already moved to `tests/integrationtest`

File: pkg/executor/point_get_test.go [hunk 6]
```diff
@@ -429,3 +429,71 @@ func TestWithTiDBSnapshot(t *testing.T) {
...
+	defer func() {
+		tk.MustExec("drop table if exists t")
+	}()
+	time.Sleep(50 * time.Millisecond)
+	tk.MustExec("set @a=(select current_timestamp(3))")
+	tk.MustExec("insert into t values (1)")
+	tk.MustQuery("select * from t as of timestamp @a where a = 1").Check(testkit.Rows())
+}
+
+func TestPointGetIssue40194(t *testing.T) {
```
Comment (Defined2014) [inline pkg/executor/point_get_test.go:448]: ditto

**Review by mjonss — APPROVED** [review]
LGTM, just some minor suggestions.

File: pkg/planner/core/point_get_plan.go [hunk 7]
```diff
@@ -1157,6 +1160,68 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
...
+	var err error
+
+	for _, idxInfo := range tbl.Indices {
+		if !idxInfo.Unique || idxInfo.State != model.StatePublic || idxInfo.Invisible || idxInfo.MVIndex ||
+			!indexIsAvailableByHints(idxInfo, tblName.IndexHints) {
+			continue
+		}
+		if !idxInfo.Global {
+			continue
+		}
```
[the remark this answers is not in the document]
Comment (L-maple) [reply pkg/planner/core/point_get_plan.go]: resolved

File: pkg/planner/core/point_get_plan.go [hunk 8]
```diff
@@ -1157,6 +1160,68 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
...
 }
 
+func checkGlobalIndexForPointGetPlan(ctx sessionctx.Context, tblName *ast.TableName, tblAlias model.CIStr, fields []*ast.SelectField, pairs []nameValuePair, check bool) *PointGetPlan {
+	// when partitions are specified or some partition is in ddl, not use point get plan for global index.
+	//// partitions are specified in select stmt.
+	if len(tblName.PartitionNames) > 0 {
+		return nil
+	}
+	tbl := tblName.TableInfo
+	//// some partition is in ddl.
```
[the remark this answers is not in the document]
Comment (L-maple) [reply pkg/planner/core/point_get_plan.go]: resolved

File: pkg/planner/core/point_get_plan.go [hunk 9]
```diff
@@ -1157,6 +1160,68 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
 	return nil
 }
 
+func checkGlobalIndexForPointGetPlan(ctx sessionctx.Context, tblName *ast.TableName, tblAlias model.CIStr, fields []*ast.SelectField, pairs []nameValuePair, check bool) *PointGetPlan {
+	// when partitions are specified or some partition is in ddl, not use point get plan for global index.
+	//// partitions are specified in select stmt.
+	if len(tblName.PartitionNames) > 0 {
```
[the remark this answers is not in the document]
Comment (L-maple) [reply pkg/planner/core/point_get_plan.go:1167]: resolved

**Comment by L-maple** [comment]
@Defined2014 @tiancaiamao Hi, this PR is opened for a long time, is there any problems?

File: pkg/executor/point_get_test.go [hunk 10]
```diff
@@ -429,3 +429,39 @@ func TestWithTiDBSnapshot(t *testing.T) {
 
 	tk.MustQuery("select * from xx").Check(testkit.Rows("1", "7"))
 }
+
+func TestGlobalIndexPointGet(t *testing.T) {
+	defer config.RestoreFunc()()
+	config.UpdateGlobal(func(conf *config.Config) {
```
Comment (Defined2014) [inline pkg/executor/point_get_test.go:435]: The config is deleted, you could use session variable `tidb_enable_global_index` instead.

File: pkg/planner/core/initialize.go [hunk 11]
```diff
@@ -556,6 +556,9 @@ func (p *BatchPointGetPlan) Init(ctx sessionctx.Context, stats *property.StatsIn
 		d      types.Datum
 	)
 
+	if p.PartitionColPos == GlobalWithoutColumnPos {
+		return p
+	}
```
Comment (Defined2014) [inline pkg/planner/core/initialize.go:561]:
```suggestion
	}

```

File: pkg/planner/core/point_get_plan.go [hunk 12]
```diff
@@ -1157,6 +1160,66 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
 	return nil
 }
 
+func checkGlobalIndexForPointGetPlan(ctx sessionctx.Context, tblName *ast.TableName, tblAlias model.CIStr, fields []*ast.SelectField, pairs []nameValuePair, check bool) *PointGetPlan {
```
Comment (Defined2014) [inline pkg/planner/core/point_get_plan.go:1163]: Why not just use code in `tryPointGetPlan`? Many lines are same as `tryPointGetPlan` function.

Maybe we only need L1167-L1181.

**Review by Defined2014 — COMMENTED** [review]
Need update `tests/integrationtest/r/executor/partition/global_index.result` by

```
cd tests/integrationtest/
./run-tests.sh -r executor/partition/global_index
```

File: pkg/planner/core/point_get_plan.go (hunk 12 above)
Comment (Defined2014) [reply pkg/planner/core/point_get_plan.go:1163]: How about this one? @L-maple

File: pkg/planner/core/point_get_plan.go [hunk 13]
```diff
@@ -1100,16 +1103,45 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
...
+	if globalIndexCheck {
+		// when partitions are specified or some partition is in ddl, not use point get plan for global index.
+		// TODO: Add partition ID filter for Global Index Point Get.
+		// partitions are specified in select stmt.
+		if len(tblName.PartitionNames) > 0 {
+			return nil
+		}
+		tbl := tblName.TableInfo
+		// some partition is in ddl.
+		if tbl == nil ||
```
Comment (Defined2014) [inline pkg/planner/core/point_get_plan.go:1121]:
```suggestion
		// some partition is in ddl.
		if tblName.TableInfo == nil ||
```

**Review by Defined2014 — APPROVED** [review]
