### PR TITLE
expression: fix type infer for tidb's builtin compare(least and greatest)

### LINKED ISSUE #9765: `LEAST` and `GREATEST` are not compatible with Mysql
## Description
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select least(cast('01-01-01' as date), '01-01-02');
select greatest(cast('01-01-01' as date), '01-01-02');
select least(cast('01-01-01' as date), '01-01-02') + 0;
select greatest(cast('01-01-01' as date), '01-01-02') + 0;
select least(cast('01-01-01' as datetime), '01-01-02') + 0;
select cast(least(cast('01-01-01' as datetime), '01-01-02') as signed);
select cast(least(cast('01-01-01' as datetime), '01-01-02') as decimal(16,2));
```

2. What did you expect to see?
In Mysql
```
mysql> select least(cast('01-01-01' as date), '01-01-02');
+---------------------------------------------+
| least(cast('01-01-01' as date), '01-01-02') |
+---------------------------------------------+
| 2001-01-01                                  |
+---------------------------------------------+
1 row in set (0.00 sec)

mysql> select greatest(cast('01-01-01' as date), '01-01-02');
+------------------------------------------------+
| greatest(cast('01-01-01' as date), '01-01-02') |
+------------------------------------------------+
| 01-01-02                                       |
+------------------------------------------------+
1 row in set (0.00 sec)

mysql> select least(cast('01-01-01' as date), '01-01-02') + 0;
+-------------------------------------------------+
| least(cast('01-01-01' as date), '01-01-02') + 0 |
+-------------------------------------------------+
|                                        20010101 |
+-------------------------------------------------+
1 row in set (0.00 sec)

mysql> select greatest(cast('01-01-01' as date), '01-01-02') + 0;
+----------------------------------------------------+
| greatest(cast('01-01-01' as date), '01-01-02') + 0 |
+----------------------------------------------------+
|                                           20010102 |
+----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select least(cast('01-01-01' as datetime), '01-01-02') + 0;
+-----------------------------------------------------+
| least(cast('01-01-01' as datetime), '01-01-02') + 0 |
+-----------------------------------------------------+
|                                      20010101000000 |
+-----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select cast(least(cast('01-01-01' as datetime), '01-01-02') as signed);
+-----------------------------------------------------------------+
| cast(least(cast('01-01-01' as datetime), '01-01-02') as signed) |
+-----------------------------------------------------------------+
|                                                  20010101000000 |
+-----------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select cast(least(cast('01-01-01' as datetime), '01-01-02') as decimal(16,2));
+------------------------------------------------------------------------+
| cast(least(cast('01-01-01' as datetime), '01-01-02') as decimal(16,2)) |
+------------------------------------------------------------------------+
|                                                      20010101000000.00 |
+------------------------------------------------------------------------+
1 row in set (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> select least(cast('01-01-01' as date), '01-01-02');
+---------------------------------------------+
| least(cast('01-01-01' as date), '01-01-02') |
+---------------------------------------------+
| 2001-01-01 00:00:00                         |
+---------------------------------------------+
1 row in set (0.00 sec)

mysql> select greatest(cast('01-01-01' as date), '01-01-02');
+------------------------------------------------+
| greatest(cast('01-01-01' as date), '01-01-02') |
+------------------------------------------------+
| 2001-01-02 00:00:00                            |
+------------------------------------------------+
1 row in set (0.00 sec)

mysql> select least(cast('01-01-01' as date), '01-01-02') + 0;
+-------------------------------------------------+
| least(cast('01-01-01' as date), '01-01-02') + 0 |
+-------------------------------------------------+
|                                            2001 |
+-------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select greatest(cast('01-01-01' as date), '01-01-02') + 0;
+----------------------------------------------------+
| greatest(cast('01-01-01' as date), '01-01-02') + 0 |
+----------------------------------------------------+
|                                               2001 |
+----------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select least(cast('01-01-01' as datetime), '01-01-02') + 0;
+-----------------------------------------------------+
| least(cast('01-01-01' as datetime), '01-01-02') + 0 |
+-----------------------------------------------------+
|                                                2001 |
+-----------------------------------------------------+
1 row in set, 1 warning (0.01 sec)

mysql> select cast(least(cast('01-01-01' as datetime), '01-01-02') as signed);
+-----------------------------------------------------------------+
| cast(least(cast('01-01-01' as datetime), '01-01-02') as signed) |
+-----------------------------------------------------------------+
|                                                            2001 |
+-----------------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select cast(least(cast('01-01-01' as datetime), '01-01-02') as decimal(16,2));
+------------------------------------------------------------------------+
| cast(least(cast('01-01-01' as datetime), '01-01-02') as decimal(16,2)) |
+------------------------------------------------------------------------+
|                                                                2001.00 |
+------------------------------------------------------------------------+
1 row in set (0.01 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-227-g06183393e-dirty
Git Commit Hash: 06183393ed536aa248248b72d4bf9f5010947f66
Git Branch: master
UTC Build Time: 2019-03-15 08:22:53
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```




## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @XuHuaiyu

### LINKED ISSUE #17994: Incompatible behaviour of least() and greatest() functions with MySQL
### 1. Minimal reproduce step (Required)

```sql
drop table t;
create table t (int_type int, str_type char(255), datetime_type datetime);
insert into t values (12345, "invalid_time", "2020-01-01");
select int_type, str_type, datetime_type from t;
select least(int_type, str_type, datetime_type) from t;
select least(int_type, str_type) from t;
select least(int_type, datetime_type) from t;
select least(str_type, datetime_type) from t;
select greatest(int_type, str_type, datetime_type) from t;
select greatest(int_type, str_type) from t;
select greatest(int_type, datetime_type) from t;
select greatest(str_type, datetime_type) from t;
```

I tried these queries on MySQL and TiDB respectively.

### 2. What did you expect to see? (Required)

mysql  Ver 8.0.19 for osx10.15 on x86_64 (Homebrew)

In MySQL:

```sql
+----------+--------------+---------------------+
| int_type | str_type     | datetime_type       |
+----------+--------------+---------------------+
|    12345 | invalid_time | 2020-01-01 00:00:00 |
+----------+--------------+---------------------+
1 row in set (0.00 sec)

+------------------------------------------+
| least(int_type, str_type, datetime_type) |
+------------------------------------------+
| 12345                                    |
+------------------------------------------+
1 row in set, 2 warnings (0.00 sec)

Warning (Code 1292): Incorrect datetime value: '12345' for column 'datetime_type' at row 1
Warning (Code 1292): Incorrect datetime value: 'invalid_time' for column 'datetime_type' at row 1
+---------------------------+
| least(int_type, str_type) |
+---------------------------+
| 12345                     |
+---------------------------+
1 row in set (0.00 sec)

+--------------------------------+
| least(int_type, datetime_type) |
+--------------------------------+
| 12345                          |
+--------------------------------+
1 row in set, 1 warning (0.01 sec)

Warning (Code 1292): Incorrect datetime value: '12345' for column 'datetime_type' at row 1
+--------------------------------+
| least(str_type, datetime_type) |
+--------------------------------+
| 2020-01-01 00:00:00            |
+--------------------------------+
1 row in set, 1 warning (0.00 sec)

Warning (Code 1292): Incorrect datetime value: 'invalid_time' for column 'datetime_type' at row 1
+---------------------------------------------+
| greatest(int_type, str_type, datetime_type) |
+---------------------------------------------+
| 2020-01-01 00:00:00.000000                  |
+---------------------------------------------+
1 row in set, 2 warnings (0.00 sec)

Warning (Code 1292): Incorrect datetime value: '12345' for column 'datetime_type' at row 1
Warning (Code 1292): Incorrect datetime value: 'invalid_time' for column 'datetime_type' at row 1
+------------------------------+
| greatest(int_type, str_type) |
+------------------------------+
| invalid_time                 |
+------------------------------+
1 row in set (0.00 sec)

+-----------------------------------+
| greatest(int_type, datetime_type) |
+-----------------------------------+
| 2020-01-01 00:00:00               |
+-----------------------------------+
1 row in set, 1 warning (0.00 sec)

Warning (Code 1292): Incorrect datetime value: '12345' for column 'datetime_type' at row 1
+-----------------------------------+
| greatest(str_type, datetime_type) |
+-----------------------------------+
| 2020-01-01 00:00:00.000000        |
+-----------------------------------+
1 row in set, 1 warning (0.00 sec)

Warning (Code 1292): Incorrect datetime value: 'invalid_time' for column 'datetime_type' at row 1
```

### 3. What did you see instead (Required)

In TiDB:

```sql
mysql> source /Users/jmpotato/test.sql
Query OK, 0 rows affected (0.03 sec)

Query OK, 0 rows affected (0.02 sec)

Query OK, 1 row affected (0.01 sec)

+----------+--------------+---------------------+
| int_type | str_type     | datetime_type       |
+----------+--------------+---------------------+
|    12345 | invalid_time | 2020-01-01 00:00:00 |
+----------+--------------+---------------------+
1 row in set (0.00 sec)

+------------------------------------------+
| least(int_type, str_type, datetime_type) |
+------------------------------------------+
|                                        0 |
+------------------------------------------+
1 row in set, 1 warning (0.00 sec)

+---------------------------+
| least(int_type, str_type) |
+---------------------------+
|                         0 |
+---------------------------+
1 row in set, 1 warning (0.00 sec)

+--------------------------------+
| least(int_type, datetime_type) |
+--------------------------------+
|                          12345 |
+--------------------------------+
1 row in set (0.00 sec)

+--------------------------------+
| least(str_type, datetime_type) |
+--------------------------------+
| invalid_time                   |
+--------------------------------+
1 row in set, 1 warning (0.00 sec)

+---------------------------------------------+
| greatest(int_type, str_type, datetime_type) |
+---------------------------------------------+
|                              20200101000000 |
+---------------------------------------------+
1 row in set, 1 warning (0.00 sec)

+------------------------------+
| greatest(int_type, str_type) |
+------------------------------+
|                        12345 |
+------------------------------+
1 row in set, 1 warning (0.01 sec)

+-----------------------------------+
| greatest(int_type, datetime_type) |
+-----------------------------------+
|                    20200101000000 |
+-----------------------------------+
1 row in set (0.00 sec)

+-----------------------------------+
| greatest(str_type, datetime_type) |
+-----------------------------------+
| 2020-01-01 00:00:00               |
+-----------------------------------+
1 row in set, 1 warning (0.00 sec)
```

### 4. Affected version (Required)

```
+ TiDB version:
Release Version: v4.0.0-beta.2-624-g4e74d4039-dirty
Edition: Community
Git Commit Hash: 4e74d40392e9b81f2a90cbc2f7777fd35f87b2e7
Git Branch: master
UTC Build Time: 2020-06-12 02:31:49
GoVersion: go1.14.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 900

## Mentor
 * @lzmhhh123

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: 
close #17994 
close #9765 

Problem Summary:

### What is changed and how it works?

What's Changed:
This pull request migrates some MySQL type merge rules to make TiDB's type infer rules more MySQL compatible.

How it Works:
This pull request port https://github.com/mysql/mysql-server/blob/ee4455a33b10f1b1886044322e4893f587b319ed/sql%2Fitem_func.cc#L3470 to infer the result type of `least/greatest`

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- expression: fix type infer for TiDB's builtin compare(least and greatest)

### CODE REVIEW

File: types/field_type.go [hunk 1]
```diff
@@ -1258,6 +1262,49 @@ var fieldTypeMergeRules = [fieldTypeNum][fieldTypeNum]byte{
 	},
 }
 
+const (
+	InvalidResult byte = 0 /** not valid for UDFs */
```
Comment (breeswish) [inline types/field_type.go:1266]: Maybe you need to define a new type for these constants?

File: types/field_type.go [hunk 2]
```diff
@@ -1258,6 +1262,49 @@ var fieldTypeMergeRules = [fieldTypeNum][fieldTypeNum]byte{
...
+	StringResult  byte = 1 /** char * */
+	RealResult    byte = 2 /** double */
+	IntResult     byte = 3 /** long long */
+	RowResult     byte = 4 /** not valid for UDFs */
```
Comment (breeswish) [inline types/field_type.go:1270]: Unused?

File: types/field_type.go [hunk 3]
```diff
@@ -1258,6 +1262,49 @@ var fieldTypeMergeRules = [fieldTypeNum][fieldTypeNum]byte{
...
+	DecimalResult byte = 5 /** char *, to be converted to/from a decimal */
```
Comment (breeswish) [inline types/field_type.go:1271]: There is no `char *` in TiDB?

File: types/field_type.go [hunk 4]
```diff
@@ -1258,6 +1262,49 @@ var fieldTypeMergeRules = [fieldTypeNum][fieldTypeNum]byte{
...
+	IntResult, IntResult,
+	// mysql.TypeDate         mysql.TypeTime
+	StringResult, StringResult,
+	// mysql.TypeDateTime     mysql.TypeYear
+	StringResult, IntResult,
+	// mysql.TypeNewDate      mysql.TypeVarchar
+	StringResult, StringResult,
+	// mysql.TypeBit          mysql.TypeInvalid
+	IntResult, InvalidResult,
+	// Unused entries: <17>-<242>
```
Comment (breeswish) [inline types/field_type.go:1293]: In previous definitions, the matrix order is TypeBit, <16>-<244>, TypeJSON, ...

In this implementation, the order is TypeBit, TypeInvalid, <17>-<242>, TypeBool, TypeJSON

Will there be problems?

File: planner/core/expression_test.go [hunk 5]
```diff
@@ -71,7 +71,7 @@ func (s *testExpressionSuite) TestBetween(c *C) {
 		{exprStr: "1 between 2 and 3", resultStr: "0"},
 		{exprStr: "1 not between 2 and 3", resultStr: "1"},
 		{exprStr: "'2001-04-10 12:34:56' between cast('2001-01-01 01:01:01' as datetime) and '01-05-01'", resultStr: "1"},
-		{exprStr: "20010410123456 between cast('2001-01-01 01:01:01' as datetime) and 010501", resultStr: "0"},
+		{exprStr: "20010410123456 between cast('2001-01-01 01:01:01' as datetime) and 010501", resultStr: "1"},
```
Comment (breeswish) [inline planner/core/expression_test.go:74]: MySQL result is 0?

**Comment by SunRunAway** [comment]
@iosmanthus Should it be cherry-picked into release-3.0 and release-4.0?

**Comment by iosmanthus** [comment]
@lzmhhh123 @breeswish PTAL

File: expression/builtin_compare.go [hunk 6]
```diff
@@ -796,32 +870,35 @@ func (b *builtinLeastTimeSig) Clone() builtinFunc {
...
 			if err = handleInvalidTimeError(b.ctx, err); err != nil {
 				return v, true, err
-			} else if !findInvalidTime {
-				res = v
-				findInvalidTime = true
 			}
+		} else {
+			v = t.String()
+		}
+		if i == 0 || strings.Compare(v, strRes) < 0 {
```
Comment (breeswish) [inline expression/builtin_compare.go:890]: Remember to fix at TiKV side as well

**Comment by breeswish** [comment]
@iosmanthus You may need to create PR to fix tests.

**Comment by iosmanthus** [comment]
> @iosmanthus You may need to create PR to fix tests.

https://github.com/pingcap/tidb-test/pull/1116

**Comment by iosmanthus** [comment]
@lzmhhh123  @breeswish PTAL

File: expression/builtin_compare.go [hunk 7]
```diff
@@ -592,30 +653,39 @@ func (b *builtinGreatestTimeSig) Clone() builtinFunc {
 
 // evalString evals a builtinGreatestTimeSig.
 // See http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#function_greatest
-func (b *builtinGreatestTimeSig) evalString(row chunk.Row) (_ string, isNull bool, err error) {
+func (b *builtinGreatestTimeSig) evalString(row chunk.Row) (res string, isNull bool, err error) {
```
Comment (lzmhhh123) [inline expression/builtin_compare.go:656]: Should we also modify `vecEvalString`?

File: expression/builtin_compare.go [hunk 8]
```diff
@@ -796,32 +870,35 @@ func (b *builtinLeastTimeSig) Clone() builtinFunc {
 // See http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#functionleast
 func (b *builtinLeastTimeSig) evalString(row chunk.Row) (res string, isNull bool, err error) {
```
Comment (lzmhhh123) [inline expression/builtin_compare.go:871]: Ditto.

**Review by lzmhhh123 — COMMENTED** [review]
Rest LGTM

**Comment by wjhuang2016** [comment]
@iosmanthus Please resolve the conflict.

**Comment by iosmanthus** [comment]
@lzmhhh123 @breeswish PTAL

File: expression/builtin_compare.go (hunk 8 above)
Comment (iosmanthus) [reply expression/builtin_compare.go:871]: Done

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: expression/builtin_compare.go [hunk 9]
```diff
@@ -382,38 +383,94 @@ func temporalWithDateAsNumEvalType(argTp *types.FieldType) (argEvalType types.Ev
 	return
 }
 
-// GetCmpTp4MinMax gets compare type for GREATEST and LEAST and BETWEEN
-func GetCmpTp4MinMax(args []Expression) (argTp types.EvalType) {
-	datetimeFound, isAllStr := false, true
-	cmpEvalType, isStr, isTemporalWithDate := temporalWithDateAsNumEvalType(args[0].GetType())
-	if !isStr {
-		isAllStr = false
+func aggregateType(args []Expression) *types.FieldType {
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:386]: Is this dup with https://github.com/pingcap/tidb/blob/master/types/field_type.go#L67

File: expression/builtin_compare.go [hunk 10]
```diff
@@ -382,38 +383,94 @@ func temporalWithDateAsNumEvalType(argTp *types.FieldType) (argEvalType types.Ev
...
+
+	return cmpTp
+}
+
+// ResolveType4Extremum gets compare type for GREATEST and LEAST and BETWEEN (mainly for datetime).
+func ResolveType4Extremum(args []Expression) types.EvalType {
+	aggType := aggregateType(args)
+
+	var temporalItem *types.FieldType
+	if types.ResultMergeType(aggType.Tp) == types.ETString {
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:460]: Useless ResultMergeType?
aggType.EvalType is enough

File: expression/builtin_compare.go [hunk 11]
```diff
@@ -382,38 +383,94 @@ func temporalWithDateAsNumEvalType(argTp *types.FieldType) (argEvalType types.Ev
...
-		argTp = types.ETString
 	}
-	if isAllStr && datetimeFound {
-		argTp = types.ETDatetime
+
+	return cmpTp
+}
+
+// ResolveType4Extremum gets compare type for GREATEST and LEAST and BETWEEN (mainly for datetime).
+func ResolveType4Extremum(args []Expression) types.EvalType {
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:456]: no need to export this function

File: expression/errors.go [hunk 12]
```diff
@@ -82,3 +82,18 @@ func handleDivisionByZeroError(ctx sessionctx.Context) error {
...
 	return nil
 }
+
+// unsupportedJSONComparison reports warnings while there is a JSON type in least/greatest function's arguments
+func unsupportedJSONComparison(ctx sessionctx.Context, args []Expression) {
+	for _, arg := range args {
+		tp := arg.GetType().Tp
+		if types.ResultMergeType(tp) == types.ETString && tp == pmysql.TypeJSON {
+			ctx.GetSessionVars().StmtCtx.AppendWarning(
+				dbterror.ClassExpression.NewStdErr(
```
Comment (XuHuaiyu) [inline expression/errors.go:92]: move this definition to line 53

File: expression/errors.go [hunk 13]
```diff
@@ -82,3 +82,18 @@ func handleDivisionByZeroError(ctx sessionctx.Context) error {
 	sc.AppendWarning(ErrDivisionByZero)
 	return nil
 }
+
+// unsupportedJSONComparison reports warnings while there is a JSON type in least/greatest function's arguments
+func unsupportedJSONComparison(ctx sessionctx.Context, args []Expression) {
```
Comment (XuHuaiyu) [inline expression/errors.go:87]: move this function to builtin_compare.go

File: expression/builtin_compare.go [hunk 14]
```diff
@@ -796,32 +870,35 @@ func (b *builtinLeastTimeSig) Clone() builtinFunc {
 // See http://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#functionleast
 func (b *builtinLeastTimeSig) evalString(row chunk.Row) (res string, isNull bool, err error) {
 	var (
-		v string
-		t types.Time
+		strRes  string
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:873]: add comments for these two fields

File: expression/builtin_compare_test.go [hunk 15]
```diff
@@ -283,23 +283,23 @@ func (s *testEvaluatorSuite) TestGreatestLeastFuncs(c *C) {
 		},
 		{
 			[]interface{}{"123a", "b", "c", 12},
-			float64(123), float64(0), false, false,
+			"c", "12", false, false,
```
Comment (XuHuaiyu) [inline expression/builtin_compare_test.go:286]: This not compatible with MySQL

File: expression/builtin_compare_test.go [hunk 16]
```diff
@@ -283,23 +283,23 @@ func (s *testEvaluatorSuite) TestGreatestLeastFuncs(c *C) {
...
 		},
 		{
 			[]interface{}{tm, 123},
-			curTimeInt, int64(123), false, false,
+			curTimeString, "123", false, false,
 		},
 		{
 			[]interface{}{tm, "invalid_time_1", "invalid_time_2", tmWithFsp},
-			curTimeWithFspString, "invalid_time_1", false, false,
+			curTimeWithFspString, curTimeString, false, false,
```
Comment (XuHuaiyu) [inline expression/builtin_compare_test.go:298]: This is not compatible with mysql

File: expression/builtin_compare_test.go (hunk 15 above)
Comment (breeswish) [reply expression/builtin_compare_test.go:286]: I tried it with MySQL 8 and looks good?

```
mysql> select greatest("123a", "b", "c", 12);
--------------
select greatest("123a", "b", "c", 12)
--------------

+--------------------------------+
| greatest("123a", "b", "c", 12) |
+--------------------------------+
| c                              |
+--------------------------------+
1 row in set (0.00 sec)

mysql> select least("123a", "b", "c", 12);
--------------
select least("123a", "b", "c", 12)
--------------

+-----------------------------+
| least("123a", "b", "c", 12) |
+-----------------------------+
| 12                          |
+-----------------------------+
1 row in set (0.00 sec)

mysql> select version();
--------------
select version()
--------------

+-----------+
| version() |
+-----------+
| 8.0.19    |
+-----------+
1 row in set (0.00 sec)
```

Comment (XuHuaiyu) [reply expression/builtin_compare_test.go:286]: Got it.
I tested it in 5.0.7.

**Comment by XuHuaiyu** [comment]
@iosmanthus Please address the comments

File: expression/builtin_compare.go (hunk 10 above)
Comment (iosmanthus) [reply expression/builtin_compare.go:460]: `EvalType()` returns the evaluated type of the `FieldType` instead of the result merge type which will convert a `Datetime` into a string result instead of the `ETDatetime`.

Comment (iosmanthus) [reply expression/builtin_compare.go:460]: In another word, `ResultMergeType` converts all types into 4 basic result types: `ETInt`, `ETReal`, `ETDecimal`, `ETString`.

File: expression/builtin_compare.go (hunk 11 above)
Comment (iosmanthus) [reply expression/builtin_compare.go:456]: Done.

File: expression/errors.go (hunk 12 above)
Comment (iosmanthus) [reply expression/errors.go:92]: Done.

File: expression/errors.go (hunk 13 above)
Comment (iosmanthus) [reply expression/errors.go:87]: Done.

File: expression/builtin_compare_test.go (hunk 16 above)
Comment (iosmanthus) [reply expression/builtin_compare_test.go:298]: Ditto, comments about the compatibility are added.

File: expression/builtin_compare.go (hunk 14 above)
Comment (iosmanthus) [reply expression/builtin_compare.go:873]: Done.

**Comment by iosmanthus** [comment]
@XuHuaiyu PTAL

File: expression/builtin_compare.go (hunk 10 above)
Comment (XuHuaiyu) [reply expression/builtin_compare.go:423]: I think we do not need this, we can check whether the `ETType == ETDatetime || ETType == ETString || ...`

File: expression/builtin_compare.go [hunk 17]
```diff
@@ -382,38 +383,68 @@ func temporalWithDateAsNumEvalType(argTp *types.FieldType) (argEvalType types.Ev
...
-	if isAllStr && datetimeFound {
-		argTp = types.ETDatetime
+	return aggType.EvalType()
+}
+
+// unsupportedJSONComparison reports warnings while there is a JSON type in least/greatest function's arguments
+func unsupportedJSONComparison(ctx sessionctx.Context, args []Expression) {
+	for _, arg := range args {
+		tp := arg.GetType().Tp
+		if types.ResultMergeType(tp) == types.ETString && tp == mysql.TypeJSON {
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:443]: `types.ResultMergeType(tp) == types.ETString` is useless?

Comment (iosmanthus) [reply expression/builtin_compare.go:443]: Yes. In MySQL, there is a variant of result types, named `ROW_RESULT` which represents a row instead of a type of constant.

Comment (iosmanthus) [reply expression/builtin_compare.go]: Done.

File: expression/builtin_compare.go [hunk 18]
```diff
@@ -382,38 +383,68 @@ func temporalWithDateAsNumEvalType(argTp *types.FieldType) (argEvalType types.Ev
...
+	return cmpTp
+}
+
+// resolveType4Extremum gets compare type for GREATEST and LEAST and BETWEEN (mainly for datetime).
+func resolveType4Extremum(args []Expression) types.EvalType {
+	aggType := aggregateType(args)
+
+	var temporalItem *types.FieldType
+	aggType.EvalType()
+	if types.ResultMergeType(aggType.Tp) == types.ETString {
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:423]: we can check whether the `ETType == ETDatetime || ETType == ETString || ...` instead of using ResultMergeType here.

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]
