### PR TITLE
ddl: fix drop table show errors

### LINKED ISSUE #25069: show errors is incorrectly a noop statement
## Bug Report

Found via the testsuite - this statement could be used by users or applications, and is not safe to noop.

### 1. Minimal reproduce step (Required)

```sql
drop table idontexist;
show errors;
```

### 2. What did you expect to see? (Required)

```sql
mysql [localhost:8024] {msandbox} (test) > drop table idontexist;
ERROR 1051 (42S02): Unknown table 'test.idontexist'
mysql [localhost:8024] {msandbox} (test) > show errors;
+-------+------+---------------------------------+
| Level | Code | Message                         |
+-------+------+---------------------------------+
| Error | 1051 | Unknown table 'test.idontexist' |
+-------+------+---------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```sql
mysql> drop table idontexist;
ERROR 1051 (42S02): Unknown table 'test.idontexist'
mysql> show errors;
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.1.0-alpha-87-g0158f71cd-dirty
Edition: Community
Git Commit Hash: 0158f71cda6ccbbd382c6e8759904234baca259c
Git Branch: master
UTC Build Time: 2021-06-01 18:35:21
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve?

Issue Number: close #25069

Problem Summary:

drop table show error is not compatible with MySQL

### What is changed and how it works?

What's Changed:

append error if the table does not exist when drop table

How it Works:

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

File: executor/ddl.go [hunk 1]
```diff
@@ -348,6 +348,13 @@ func (e *DDLExec) dropTableObject(objects []*ast.TableName, obt objectType, ifEx
 		}
 	}
 	if len(notExistTables) > 0 && !ifExists {
+		for _, table := range notExistTables {
+			if obt == sequenceObject {
+				e.ctx.GetSessionVars().StmtCtx.AppendError(infoschema.ErrSequenceDropExists.GenWithStackByArgs(table))
```
Comment (xiongjiwei) [inline executor/ddl.go:353]: I do not think it is a good idea to append the error here, when an error happens, it should be shown in `show errors` not only this error.

Comment (xiongjiwei) [reply executor/ddl.go:353]: I mean, all the errors. So it is better to append the error before it returns to the client

Comment (b41sh) [reply executor/ddl.go:353]: do you mean append all errors in one error message?

Comment (xiongjiwei) [reply executor/ddl.go:353]: no, I mean something like https://github.com/pingcap/tidb/blob/dffba2195600883b62231f51676b7bbd7d3b5a17/session/session.go#L1294-L1297

then we can handle all the errors, not only the `unknown table`. 
such as 
```sql
mysql> create table t(a int);
ERROR 1050 (42S01): Table 't' already exists
mysql> show errors;
+-------+------+--------------------------+
| Level | Code | Message                  |
+-------+------+--------------------------+
| Error | 1050 | Table 't' already exists |
+-------+------+--------------------------+
1 row in set (0.00 sec)
```

Comment (b41sh) [reply executor/ddl.go]: ok, I add `AppendError` in `func runStmt`, I'm not sure if this is the right place
PTAL @xiongjiwei

Comment (xiongjiwei) [reply executor/ddl.go]: Thanks! the function `session.ExecuteStmt` calls `runStmt` and the error is recorded in some function which calls `session.ExecuteStmt` (see above). it may lead to redundant error in `show errors`. I think only append the error in `runStmt` and remove others will be better.(I have not check it carefully)
BTW, can you please add some tests?

Comment (b41sh) [reply executor/ddl.go]: ok, I will modify it.

Comment (b41sh) [reply executor/ddl.go]: I have added some tests, PTAL @xiongjiwei

**Review by morgo — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
