### PR TITLE
br: stop log when full restore failed

### LINKED ISSUE #51572: too many logs when full restore failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. full restore with `coarse-grained` and failed to ingest at last

### 2. What did you expect to see? (Required)
1. gracefully exits
### 3. What did you see instead (Required)
1. too many logs print
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #51572

Problem Summary:
too many logs when full restore failed
### What changed and how does it work?
stop log when error context canceled
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Leavrth** [comment]
```Go
pdclient := mgr.GetPDClient()
cctx, cancel := context.WithCancel(ctx)
cancel()
_, _, err = pdclient.GetTS(cctx)
require.Equal(t, context.Canceled, errors.Cause(err))  // pass 
require.NoError(t, err)  // Received unexpected error:
        	         //   context canceled
```
It is not grpc context cancel error, so we can retry the grpc context cancel error in pd backoff

File: br/pkg/utils/backoff.go [hunk 1]
```diff
@@ -220,14 +220,6 @@ type pdReqBackoffer struct {
 	maxDelayTime time.Duration
 }
 
-func NewPDReqBackoffer() Backoffer {
```
Comment (3pointer) [inline br/pkg/utils/backoff.go:223]: I'm afraid we cannot simply take it away. some tests rely on the behavior of this backoffer and it may looks like "stuck" when retry too many times on some scenarios.

**Review by 3pointer — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
