### PR TITLE
ddl, session: set charset and coordinate collation 

### LINKED ISSUE #20209: charset and collation for view is not handle properly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set @@character_set_client=utf8mb4;
set @@collation_connection=utf8_bin;
mysql> CREATE VIEW tx AS SELECT   1 AS `id`;
ERROR 1115 (42000): Unknown character set: 'utf8mb4'
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?
close #20209

when set `character_set_connect`, `collation_connect` will set to be relate collation. same to `character_set_database`  `character_set_server`, vice versa

### Check List 

Tests 

- Unit test

### Release note 

- fix a bug that some coordinate system value is invalid

### CODE REVIEW

File: sessionctx/variable/session.go [hunk 1]
```diff
@@ -1466,26 +1466,48 @@ func (s *SessionVars) SetSystemVar(name string, val string) error {
...
+		}
+		switch name {
+		case CollationConnection:
+			s.systems[CollationConnection] = coll.Name
+			s.systems[CharacterSetConnection] = coll.CharsetName
+		case CollationDatabase:
+			s.systems[CollationDatabase] = coll.Name
+			s.systems[CharsetDatabase] = coll.CharsetName
+		case CollationServer:
+			s.systems[CollationDatabase] = coll.Name
```
Comment (wjhuang2016) [inline sessionctx/variable/session.go:1482]: CollationServer ?

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: sessionctx/variable/session.go (hunk 1 above)
Comment (xiongjiwei) [reply sessionctx/variable/session.go]: updated

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Review by wjhuang2016 — APPROVED** [review]
