### PR TITLE
ddl: add partition should not take table information

### LINKED ISSUE #19596: Illegal alter table input breaks the partition table totally
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (
  a int
) partition by range(a) (
  partition p0 values less than (1)
);

alter table t add partition (partition p1 values less than (a));

select * from t;
```

### 2. What did you expect to see? (Required)

Throw error when executing alter table.

### 3. What did you see instead (Required)

TiDB connection is crashed when executing alter table.

TiDB respond `ERROR 1105 (HY000): strconv.ParseInt: parsing "`a`": invalid syntax` when selecting from this table after that.

### 4. What is your TiDB version? (Required)

v4.0.4

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close #19596 

Problem Summary:
`alter table t add partition (partition p1 values less than (a));` will pass partition check if `a` is column of table `t`

### What is changed and how it works?

- use empty table info in `ParseSimpleExprWithTableInfo`

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

- fix an issue that unexpect sucess partition alter

### CODE REVIEW

**Review by bb7133 — COMMENTED** [review]
LGTM

File: expression/integration_test.go [hunk 1]
```diff
@@ -7127,3 +7127,14 @@ func (s *testIntegrationSuite) TestIssue19504(c *C) {
...
+
+func (s *testIntegrationSuite) TestIssue19596(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t;")
+	tk.MustExec("create table t (a int) partition by range(a) (PARTITION p0 VALUES LESS THAN (10));")
+	tk.MustGetErrMsg("alter table t add partition (partition p1 values less than (a));", "[ddl:1659]Field '`a`' is of a not allowed type for this type of partitioning")
+	tk.MustQuery("select * from t;")
+	tk.MustExec("drop table if exists t;")
+	tk.MustGetErrMsg("create table t (a int) partition by range(a) (PARTITION p0 VALUES LESS THAN (a));", "[ddl:1659]Field '`a`' is of a not allowed type for this type of partitioning")
```
Comment (tangenta) [inline expression/integration_test.go:7139]: This error code/message seems not compatible with MySQL:
```sql
create table t (
  a int
) partition by range(a) (
  partition p0 values less than (1)
);

alter table t add partition (partition p1 values less than (a));
```

```console
(1054, "Unknown column 'a' in 'partition function'")
```

Comment (xiongjiwei) [reply expression/integration_test.go]: it return error msg `[expression:1054]Unknown column 'a' in 'expression'` now, it is returned by `simpleRewriter`

File: ddl/partition.go [hunk 2]
```diff
@@ -761,18 +761,20 @@ func checkCreatePartitionValue(ctx sessionctx.Context, tblInfo *model.TableInfo)
...
 
-		if e, err1 := expression.ParseSimpleExprWithTableInfo(ctx, str, tblInfo); err1 == nil {
+		if e, err1 := expression.ParseSimpleExprWithTableInfo(ctx, str, &model.TableInfo{}); err1 == nil {
 			res, isNull, err2 := e.EvalInt(ctx, chunk.Row{})
 			if err2 == nil && !isNull {
 				return uint64(res), true, nil
 			}
+		} else {
+			return 0, false, err1
 		}
```
Comment (zimulala) [inline ddl/partition.go:778]: Could we change this code as follows:
```
e, err1 := expression.ParseSimpleExprWithTableInfo(ctx, str, &model.TableInfo{});
if  err1 != nil {
	return 0, false, err1
}
res, isNull, err2 := e.EvalInt(ctx, chunk.Row{})
if err2 == nil && !isNull {
	return uint64(res), true, nil
}
```

**Review by zimulala — DISMISSED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Comment by zimulala** [comment]
@xiongjiwei 
Please fix conflicting.

**Comment by xiongjiwei** [comment]
> @xiongjiwei
> Please fix conflicting.

@zimulala updated

**Review by zimulala — APPROVED** [review]
