### PR TITLE
executor: fix goroutine leak in querying slow log

### LINKED ISSUE #32656: Goroutine leak in `slowQueryRetriever.parseSlowLog`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

goroutine 221431 [chan send, 9 minutes]:
github.com/pingcap/tidb/executor.(*slowQueryRetriever).parseSlowLog(0xc09392b480, 0x4038470, 0xc09b4dc360, 0x407eb58, 0xc092c7ae00, 0xc13d6ddf50, 0x40)
/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/slow_query.go:451 +0x23e
github.com/pingcap/tidb/executor.(*slowQueryRetriever).parseDataForSlowLog(0xc09392b480, 0x4038470, 0xc09b4dc360, 0x407eb58, 0xc092c7ae00)
/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/slow_query.go:191 +0x1d1
created by github.com/pingcap/tidb/executor.(*slowQueryRetriever).initializeAsyncParsing
/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/slow_query.go:1045 +0x98

### 2. What did you expect to see? (Required)

No leak

### 3. What did you see instead (Required)

When `dataForSlowLog ` is cancelled, `parseSlowLog` stucks at `e.taskList <- t` for 9 minutes.

https://github.com/pingcap/tidb/pull/27471 just fixed https://github.com/pingcap/tidb/blob/v5.2.3/executor/slow_query.go#L435 , but there's another leak in https://github.com/pingcap/tidb/blob/v5.2.3/executor/slow_query.go#L451 .

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by djshow832**
### What problem does this PR solve?

Issue Number: close #32656

Problem Summary:

goroutine leaks in `parseSlowLog` when the query is canceled.

### What is changed and how it works?

Check context when waiting for the channel.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: executor/slow_query.go [hunk 1]
```diff
@@ -447,14 +447,25 @@ func (e *slowQueryRetriever) parseSlowLog(ctx context.Context, sctx sessionctx.C
...
 			start := offset
-			wg.Add(1)
 			ch <- 1
-			e.taskList <- t
+			select {
+			case <-ctx.Done():
+				return
+			case e.taskList <- t:
+			}
+			wg.Add(1)
```
Comment (hawkingrei) [inline executor/slow_query.go:468]: ```wg``` can use ```util.WaitGroupWrapper```. so it can simple this code.

```
wg.Run(func {
      result, err := e.parseLog(ctx, sctx, log, start)
      ....
})
```

it is never forgotten to write ```wg.Add``` and ```wg.Done```.

**Review by crazycs520 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
