### PR TITLE
planner/core: Key partitioning uses an column index, which did not match value pairs in fast plan

### LINKED ISSUE #50206: Runtime error index out of range for Key partitioned table when partitioning column is not the first column.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (b varchar(255), a int primary key nonclustered, key (b)) partition by key(a) partitions 3;
insert into t values ('Ab', 1),('abc',2),('BC',3),('AC',4),('BA',5),('cda',6);
analyze table t;
select * from t where a = 2;
```

### 2. What did you expect to see? (Required)
Success
### 3. What did you see instead (Required)
```sql
tidb> create table t (b varchar(255), a int primary key nonclustered, key (b)) partition by key(a) partitions 3;
Query OK, 0 rows affected (0.13 sec)

tidb> insert into t values ('Ab', 1),('abc',2),('BC',3),('AC',4),('BA',5),('cda',6);
Query OK, 6 rows affected (0.02 sec)
Records: 6  Duplicates: 0  Warnings: 0

tidb> analyze table t;
Query OK, 0 rows affected, 6 warnings (0.29 sec)

tidb> select * from t where a = 2;
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1

```
### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v7.5.0
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-24 08:50:14
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #50206

Problem Summary:
The column index was set to the second column, but in Fast Plan the value pairs is always the first one, so it needed to be adjusted for Key Partitioned tables.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/point_get_plan.go [hunk 1]
```diff
@@ -1909,9 +1909,22 @@ func getPartitionDef(ctx sessionctx.Context, tbl *model.TableInfo, pairs []nameV
 	case model.PartitionTypeKey:
 		// The key partition table supports FastPlan when it contains only one partition column
 		if len(pi.Columns) == 1 {
+			// We need to change the partition column index!
+			partCols, _ := partitionExpr.GetPartColumnsForKeyPartition(schema.Columns)
+			if len(partCols) != 1 {
+				return nil, 0, 0, false
+			}
+			pe := &tables.ForKeyPruning{KeyPartCols: partCols}
+			colName := ""
```
Comment (Defined2014) [inline pkg/planner/core/point_get_plan.go:1918]: How about use `pe.KeyPartCols[0].OrigName` instead the for loop? I think they are same (not 100% sure about this).

Comment (mjonss) [reply pkg/planner/core/point_get_plan.go]: Thanks for the suggestion, I updated the code.

**Review by Defined2014 — APPROVED** [review]
Please run `make bazel` to update bazel related files.

**Review by tiancaiamao — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
