### PR TITLE
topsql: fix a possible race

### LINKED ISSUE #60646: Missing topsql error logs
## Bug Report

https://github.com/pingcap/tidb/blob/4e7928851464f78756b6645e052972d16859fe26/pkg/util/topsql/reporter/pubsub.go#L111-L149

there should be one error log corresponding to one `reporter_metrics`. But it is observed on the cloud env that only two log entries are found for hundreds of errors.

I doubt it is a race cond

### 2. What did you expect to see? (Required)

Equal amount of log entries and metrics.

### 4. What is your TiDB version? (Required)

v8.1.2

### PR DESCRIPTION
**Pull request by xhebox**
Issue Number: close #60646 

Problem Summary: as title, use `WithCancelCause` to return error.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/util/topsql/reporter/pubsub.go [hunk 1]
```diff
@@ -129,6 +131,8 @@ func (ds *pubSubDataSink) run() error {
 			// In order to clean up resources as quickly as possible, we let that closure run in an individual goroutine,
 			// and wait for timeout here.
 			<-ctx.Done()
+			// useless, it is called to prevent linter error
```
Comment (Defined2014) [inline pkg/util/topsql/reporter/pubsub.go:134]: How about change `ctx, rcancel := context.WithDeadline(ds.ctx, task.deadline)` to `ctx, _ := context.WithDeadline(ds.ctx, task.deadline)`? The lint will report error or not?

Comment (xhebox) [reply pkg/util/topsql/reporter/pubsub.go:134]: Yes, and I don't want it ignore this file completely. Or do you think that is better?

Comment (Defined2014) [reply pkg/util/topsql/reporter/pubsub.go:134]: Maybe use `defer rcanel()` in Line 113 instead.

**Review by Defined2014 — APPROVED** [review]

File: pkg/util/topsql/reporter/pubsub.go (hunk 1 above)
Comment (xhebox) [reply pkg/util/topsql/reporter/pubsub.go:134]: It is not in a function, but in a loop. I think it will spawn infinite number of deferred goroutines as long as there is no failure.

**Review by hawkingrei — APPROVED** [review]
