### PR TITLE
ttl: add integration test with random fault session for TTL

### LINKED ISSUE #58107: TTL `getSession` function may return unexpected result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The function `getSession` returns a session and an error. It's expected to return either `session` or an `error`. However, it's possible that both of them are `nil`, because the `Close()` function may overwrite the `err` return value.

### 2. What did you expect to see? (Required)

At least one of `session` and `err` are not `nil`.

### 3. What did you see instead (Required)

Both of them are `nil` if the session is error.

### LINKED ISSUE #58109: If a TTL job is cancelled, the `last_job_finish_time` is incorrect.
The first assert `intest.Assert(se.GetSessionVars().Location().String() == now.Location().String())` in `job.finish` is never true when `job.finish` is called from `rescheduleJobs`  (but our tests didn't cover it yet). It's because in `rescheduleJobs` the `now` is in `GlobalTimeZone` (`Asia/Shanghai` in my case), and the `se.GetSessionVars().Location().String()` is always `UTC`.

It'll not be a big issue as the job is scheduled according to the start time, but the wrong finish time is still confusing for users.

### LINKED ISSUE #58411: add fuzzy test for concurrent running TTL job manager
## Enhancement

The E2E test for TTL runs really slow. By modifying some internal variables (through failpoint), we can make it much faster. Meanwhile, we can also simulate the fault situation for TTL job managers.

Let me add such kind of tests 😃 .

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #58411

### What changed and how does it work?

1. Add two tests related to TTL. One of them is the test with randomly faulty session, which cannot execute the SQL.
2. Fix the bug that the result of `getSession` is unexpected in some situation.
3. Fix the bug that the `last_job_finish_time` is not in correct TZ when the job is cancelled.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by YangKeao** [comment]
/hold

It's not stable yet.

File: pkg/ttl/ttlworker/job_manager_integration_test.go [hunk 1]
```diff
@@ -1614,3 +1621,225 @@ func TestJobHeartBeatFailNotBlockOthers(t *testing.T) {
...
+
+func TestJobManagerWithFault(t *testing.T) {
+	boostJobScheduleForTest(t)
+
+	store, dom := testkit.CreateMockStoreAndDomain(t)
+	waitAndStopTTLManager(t, dom)
+	tk := testkit.NewTestKit(t, store)
+
+	managerCount := 5
+	testDuration := 10 * time.Second
```
Comment (YangKeao) [inline pkg/ttl/ttlworker/job_manager_integration_test.go:1743]: TODO: don't run it in CI as it'll need a long time. In my laptop it'll need 500ms for each round. It seems that it's quite unstable (but I still don't know why, investigating) in CI.

Run it nightly, and for at least 10 minutes.

File: pkg/ttl/ttlworker/job_manager.go [hunk 2]
```diff
@@ -572,12 +572,14 @@ j:
...
-func (m *JobManager) rescheduleJobs(se session.Session, now time.Time) {
+func (m *JobManager) rescheduleJobs(se session.Session, nowInSessionTz time.Time) {
+	var now time.Time
 	tz, err := se.GlobalTimeZone(m.ctx)
 	if err != nil {
 		terror.Log(err)
+		now = nowInSessionTz
 	} else {
-		now = now.In(tz)
+		now = nowInSessionTz.In(tz)
```
Comment (lcwangchao) [inline pkg/ttl/ttlworker/job_manager.go:582]: Is `now` only used to determine the time window? If so, I think we can change `now` => `nowInGlobalTz`.

For `readyForLockHBTimeoutJobTables` and `lockHBTimeoutJob`, seems it should use the now with session timezone?

File: pkg/ttl/ttlworker/job_manager_integration_test.go (hunk 1 above)
Comment (lcwangchao) [reply pkg/ttl/ttlworker/job_manager_integration_test.go:1743]: We can just add a `t.Skip` here

File: pkg/ttl/ttlworker/session.go [hunk 3]
```diff
@@ -87,7 +87,7 @@ func getSession(pool util.SessionPool) (session.Session, error) {
 	originalIsolationReadEngines, restoreIsolationReadEngines := "", false
 
 	se := session.NewSession(sctx, exec, func(se session.Session) {
-		_, err = se.ExecuteSQL(context.Background(), fmt.Sprintf("set tidb_retry_limit=%d", originalRetryLimit))
+		_, err := se.ExecuteSQL(context.Background(), fmt.Sprintf("set tidb_retry_limit=%d", originalRetryLimit))
```
Comment (lcwangchao) [inline pkg/ttl/ttlworker/session.go:90]: It's better to schedule a new PR to fix it. Though it rarely happens, but I think we should cherry-pick it to the previous versions to avoid potential panics here.

Comment (YangKeao) [reply pkg/ttl/ttlworker/session.go:90]: Yeah! I'll submit a new PR to fix the two bugs (and cherry-pick them back to release version), and leave this PR only related to test.

**Comment by YangKeao** [comment]
ref https://github.com/pingcap/tidb/pull/58166

File: pkg/ttl/ttlworker/session_integration_test.go [hunk 4]
```diff
@@ -97,19 +118,12 @@ func (s *sessionWithFault) ExecuteInternal(ctx context.Context, sql string, args
 }
 
 func (s *sessionWithFault) shouldFault(sql string) bool {
-	if s.fault.Load() == nil {
-		return false
-	}
-
-	// as a fault implementation may have side-effect, we should always call it before checking the SQL.
-	shouldFault := (*s.fault.Load()).shouldFault()
```
Comment (YangKeao) [inline pkg/ttl/ttlworker/session_integration_test.go:105]: When `s.fault.Load() != nil`, the `*s.fault` can still be a nil interface.

File: pkg/ttl/ttlworker/job_manager_integration_test.go [hunk 5]
```diff
@@ -1619,3 +1621,184 @@ func TestJobHeartBeatFailNotBlockOthers(t *testing.T) {
...
+	}
+
+	type managerWithPool struct {
+		m    *ttlworker.JobManager
+		pool util.SessionPool
+	}
+	managers := make([]managerWithPool, 0, managerCount)
+	for i := 0; i < managerCount; i++ {
+		pool := wrapPoolForTest(dom.SysSessionPool())
+		// defer pool.AssertNoSessionInUse(t)
```
Comment (lcwangchao) [inline pkg/ttl/ttlworker/job_manager_integration_test.go:1687]: useless comment?

File: pkg/ttl/ttlworker/session_integration_test.go (hunk 4 above)
Comment (lcwangchao) [reply pkg/ttl/ttlworker/session_integration_test.go:105]: Can we modify setFault?

```
func (f *faultSessionPool) setFault(ft fault) {
	if ft == nil {
		f.fault.Store(nil)
	}
	f.fault.Store(&ft)
}
```

**Review by lcwangchao — APPROVED** [review]

**Comment by YangKeao** [comment]
/hold

wait for https://github.com/pingcap/tidb/issues/58421

**Review by wjhuang2016 — APPROVED** [review]
