### PR TITLE
external: make global sort `common.Range` unencoded

### LINKED ISSUE #51910: Adding unique index with global sort gets stuck
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set global tidb_cloud_storage_uri = 'xx';
set global tidb_enable_dist_task = on;
alter table xx add unique index idx(xxx);
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

DDL stuck.

### 4. What is your TiDB version? (Required)

af897798

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #51910

Problem Summary:

Previously, start key / end key of `common.Range` is NOT encoded for local engine, but encoded for external engine. This will cause external engine generates a wrong range, and no data will be ingest to TiKV: 

https://github.com/pingcap/tidb/blob/bdc64e572b11db63f5f4cb17d7d4fa83f6261db2/br/pkg/lightning/backend/local/local.go#L1010-L1014

https://github.com/pingcap/tidb/blob/bdc64e572b11db63f5f4cb17d7d4fa83f6261db2/br/pkg/lightning/backend/external/engine.go#L513-L527

If `keyRange.Start` is encoded, `m.firstAndLastKeyIndex` will encode it again. Thus, these keys are encoded twice.

### What changed and how does it work?

After this PR, we will follow the conventions as below:

For both local and external engines,
- the data on s3 is encoded
- the statistical data on s3 is encoded
- all `common.Range` are not encoded.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/external/engine.go [hunk 1]
```diff
@@ -402,7 +404,28 @@ func (e *Engine) ID() string {
 
 // GetKeyRange implements common.Engine.
 func (e *Engine) GetKeyRange() (startKey []byte, endKey []byte, err error) {
-	return e.startKey, e.endKey, nil
+	return DecodeKeyRangeWithAdapter(e.keyAdapter, e.startKey, e.endKey)
+}
+
+// DecodeKeyRangeWithAdapter decodes start key and end key.
+func DecodeKeyRangeWithAdapter(adapter common.KeyAdapter, start, end []byte) ([]byte, []byte, error) {
+	first, err := adapter.Decode(nil, start)
```
Comment (lance6716) [inline br/pkg/lightning/backend/external/engine.go:412]: in current naming convention, we have variable name pairs like start/end (end is exclusive), first/last (last is inclusive), min/max (max is inclusive). We should still use start/end in this function

File: br/pkg/lightning/backend/external/engine.go [hunk 2]
```diff
@@ -402,7 +404,28 @@ func (e *Engine) ID() string {
...
+	last := end
+	if end[len(end)-1] == 0 {
+		// e.endKey is exclusive, we need to truncate the trailing zero before decoding.
+		last = end[:len(end)-1]
+	}
+	last, err = adapter.Decode(nil, last)
+	if err != nil {
+		return nil, nil, err
+	}
+	newEnd := make([]byte, 0, len(last)+1)
```
Comment (lance6716) [inline br/pkg/lightning/backend/external/engine.go:425]: like Key.Next(), we can 

```golang
	buf := make([]byte, len(k)+1)
	copy(buf, k)
	return buf
```

File: br/pkg/lightning/backend/external/engine.go [hunk 3]
```diff
@@ -402,7 +404,28 @@ func (e *Engine) ID() string {
...
+}
+
+// DecodeKeyRangeWithAdapter decodes start key and end key.
+func DecodeKeyRangeWithAdapter(adapter common.KeyAdapter, start, end []byte) ([]byte, []byte, error) {
+	first, err := adapter.Decode(nil, start)
+	if err != nil {
+		return nil, nil, err
+	}
+	last := end
+	if end[len(end)-1] == 0 {
```
Comment (lance6716) [inline br/pkg/lightning/backend/external/engine.go:417]: I can improve the comments to explain that it's safe to only check the last byte is `0`

File: br/pkg/lightning/backend/external/util.go [hunk 4]
```diff
@@ -64,9 +63,7 @@ func seekPropsOffsets(
 	for i := range offsetsPerFile {
 		offsetsPerFile[i] = make([]uint64, len(starts))
 	}
-	// Record first key if it is smaller than first key of "starts" key argument for
-	// each file, and check all files afterward.
-	firstKeyTooSmallCheckers := make([]kv.Key, len(paths))
+
```
Comment (lance6716) [inline br/pkg/lightning/backend/external/util.go:66]: also need to fix the unit tests and change the comments of seekPropsOffsets

Comment (lance6716) [reply br/pkg/lightning/backend/external/util.go:66]:
```diff
diff --git a/br/pkg/lightning/backend/external/util.go b/br/pkg/lightning/backend/external/util.go
index d880ca04e9..2ee8d9942b 100644
--- a/br/pkg/lightning/backend/external/util.go
+++ b/br/pkg/lightning/backend/external/util.go
@@ -40,11 +40,6 @@ import (
 // file reader, read, parse and skip few smaller keys, and then locate the needed
 // data.
 //
-// To avoid potential data loss, it also checks at least one statistic file has a
-// key larger than or equal to the start key. If not, we are afraid that some
-// paths are missing, and the data between [start key, min(first key of
-// statistic files)) are lost.
-//
 // Caller can specify multiple ascending keys and seekPropsOffsets will return
 // the offsets list per file for each key.
 func seekPropsOffsets(
diff --git a/br/pkg/lightning/backend/external/util_test.go b/br/pkg/lightning/backend/external/util_test.go
index 1800a27d23..163d908a2e 100644
--- a/br/pkg/lightning/backend/external/util_test.go
+++ b/br/pkg/lightning/backend/external/util_test.go
@@ -87,15 +87,17 @@ func TestSeekPropsOffsets(t *testing.T) {
 	require.NoError(t, err)
 	require.Equal(t, [][]uint64{{10, 20}, {30, 20}}, got)
 
-	_, err = seekPropsOffsets(ctx, []kv.Key{[]byte("key0")}, []string{file1, file2}, store)
-	require.ErrorContains(t, err, "start key 6b657930 is too small for stat files [/test1 /test2]")
+	got, err = seekPropsOffsets(ctx, []kv.Key{[]byte("key0")}, []string{file1, file2}, store)
+	require.NoError(t, err)
+	require.Equal(t, [][]uint64{{0, 0}}, got)
 
 	got, err = seekPropsOffsets(ctx, []kv.Key{[]byte("key1")}, []string{file1, file2}, store)
 	require.NoError(t, err)
 	require.Equal(t, [][]uint64{{10, 0}}, got)
 
-	_, err = seekPropsOffsets(ctx, []kv.Key{[]byte("key0"), []byte("key1")}, []string{file1, file2}, store)
-	require.ErrorContains(t, err, "start key 6b657930 is too small for stat files [/test1 /test2]")
+	got, err = seekPropsOffsets(ctx, []kv.Key{[]byte("key0"), []byte("key1")}, []string{file1, file2}, store)
+	require.NoError(t, err)
+	require.Equal(t, [][]uint64{{0, 0}, {10, 0}}, got)
 
 	got, err = seekPropsOffsets(ctx, []kv.Key{[]byte("key999")}, []string{file1, file2}, store)
 	require.NoError(t, err)
```

File: br/pkg/lightning/backend/external/engine.go (hunk 3 above)
Comment (lance6716) [reply br/pkg/lightning/backend/external/engine.go:417]:
```
	// when duplicate detection feature is disabled, the end key comes from
	// codec.EncodeBytes or Key.Next(). We can check the the last byte to tell them
	// apart because codec.EncodeBytes will always put non-zero byte at the end.
	//
	// when duplicate detection feature is enabled, the end key comes from
	// DupDetectKeyAdapter.Encode or key.Next(). We try to decode it and check the
	// error.
```

Seems this check is not correct :joy:

**Review by lance6716 — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by YuJuncen — APPROVED** [review]
