### PR TITLE
ddl: fix runnable ingest job checking

### LINKED ISSUE #52475: TiDB unexpected exit with "MANIFEST set current failed: open /tmp/tidb/tmp_ddl-4000/xxx/duplicates/temporary.000001.dbtmp: no such file or directory"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

check out to https://github.com/pingcap/tidb/pull/52467 and run `TestFirstLitSlowStart`

### 2. What did you expect to see? (Required)

not exit

### 3. What did you see instead (Required)

image

### 4. What is your TiDB version? (Required)

bug timeline:

```
1. ddl pick job 100
|\
| 2. job 100 start to create the lightning local backend. Now pebble DB passed the mkdir check
3. somehow ddl owner is resigned, the resign callback reset the runningJobs
4. ddl becomes owner again, and pick job 101, cleanup all duplicate directory which is less than 101
| 5. job 100 pebble DB writes the necessary files, found work direcctory is missing and call log.Fatal
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #52475

Problem Summary: see #52475

### What changed and how does it work?

- Remove `MarkJobProcessing` and `RetireOwnerHook`. 
- Record the running ingest job in `runningJobs`.
- Cleanup `unfinished jobs` when ddl owner is acquired.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/job_table.go [hunk 1]
```diff
@@ -292,6 +281,16 @@ func (d *ddl) startDispatchLoop() {
...
+		failpoint.Inject("ownerResignAfterDispatchLoopCheck", func() {
+			if ingest.ResignOwnerForTest.Load() {
+				err2 := d.ownerManager.ResignOwner(context.Background())
+				if err2 != nil {
+					logutil.BgLogger().Info("resign meet error", zap.Error(err2))
+				}
+				time.Sleep(500 * time.Millisecond)
+				ingest.ResignOwnerForTest.Store(false)
+			}
+		})
```
Comment (ywqzzy) [inline pkg/ddl/job_table.go:293]: The test is useless for now.

File: pkg/ddl/ddl.go [hunk 2]
```diff
@@ -831,6 +831,7 @@ func (d *ddl) Start(ctxPool *pools.ResourcePool) error {
 		if err != nil {
 			logutil.BgLogger().Error("error when getting the ddl history count", zap.Error(err))
 		}
+		d.runningJobs.clear()
```
Comment (lance6716) [inline pkg/ddl/ddl.go:834]: Now we reuse the `startDispatchLoop` to initiate the `runningJobs`, by relying on the deterministic order from `order by processing desc, job_id` and add the jobs one by one. 

Considering the case that the former DDL owner marked wrong jobs as running, like
100 (running), 101 (pending), 102 (running wrongly). The correct state should be (running, pending, pending) then (finished, running, pending). I slightly prefer the new DDL owner re-compute the running jobs instead of reuse the persistent state from persistent table.

**Review by lance6716 — COMMENTED** [review]
I'll try to use some channels to make the test more stable

File: pkg/ddl/ddl.go (hunk 2 above)
Comment (ywqzzy) [reply pkg/ddl/ddl.go:834]: “Considering the case that the former DDL owner marked wrong jobs as running, like
100 (running), 101 (pending), 102 (running wrongly).”
How come？

**Review by lance6716 — APPROVED** [review]

File: pkg/ddl/ddl.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/ddl.go:834]: > “Considering the case that the former DDL owner marked wrong jobs as running, like 100 (running), 101 (pending), 102 (running wrongly).” How come？

The old owner uses the code before this PR, and marked 102 as running

**Review by ywqzzy — APPROVED** [review]
