### PR TITLE
executor, statistics: flush pending stats delta before analyze

### LINKED ISSUE #22934: statistics: inaccurate modify-count/row-count after analyzing a table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int, b int);
insert into t values(1,1),(3,3),(4,4),(2,2),(5,5);
analyze table t ;
show stats_meta where table_name = 't'; // modify_count, row_count = 0, 5
// wait 2 minutes
show stats_meta where table_name = 't'; // modify_count, row_count = 5, 10
```

### 2. What did you expect to see? (Required)
These two `show stats_meta` statements should have the same result.

### 3. What did you see instead (Required)
They have different results.

### 4. What is your TiDB version? (Required)

```
Master
```
### 5. The Root cause of this problem.
Background: at the end of an insert statement, TiDB records the number of new-inserted rows as `StatsDelta` which will be updated into `ModifiedCount` and `RowCount` later by a background goroutine.

The Root Cause: when the analyze-table statement is processed, the `StatsDelta` generated by the previous insert statement has not been handled. When the analyze-table statement finished, we got `ModifyCount, RowCount = 0, 5`. And later when TiDB dealt with `StatsDelta`, the five rows were count again, and then we got `ModifyCount, RowCount = 5, 10`.

https://github.com/pingcap/tidb/issues/15779 has the same root cause.

### 6. How to solve this problem.
We should abandon all `StatsDelta` whose generated-time is before the time of the last analyze-statement.
Here is another test:
```
func (s *statsSerialSuite) TestWrongModifyRowcount(c *C) {
	defer cleanEnv(c, s.store, s.do)
	tk := testkit.NewTestKit(c, s.store)
	tk.MustExec("use test")
	tk.MustExec("create table t(a int, b int)")
	tk.MustExec("insert into t values(1,1),(3,3),(4,4),(2,2),(5,5)")
	tk.MustExec("analyze table t")
	rs := tk.MustQuery("show stats_meta where table_name = 't'").Rows()
	for _, r := range rs {
		fmt.Println("--->>> ", r)
	}

	c.Assert(s.do.StatsHandle().DumpStatsDeltaToKV(handle.DumpAll), IsNil)
	c.Assert(s.do.StatsHandle().Update(s.do.InfoSchema()), IsNil)
	rs = tk.MustQuery("show stats_meta where table_name = 't'").Rows()
	for _, r := range rs {
		fmt.Println("--->>> ", r)
	}
}
```

### PR DESCRIPTION
**Pull request by 0xPoe**
### What problem does this PR solve?

Issue Number: close #22934

Problem Summary:
`ANALYZE TABLE` can leave stale per-instance stats deltas pending, so a later cluster stats-delta flush may double count `mysql.stats_meta.count` and `modify_count`.

### What changed and how does it work?
- Add a regression test that reproduces the stale remote stats-delta behavior.
- Flush pending cluster stats deltas for analyzed tables before ANALYZE captures the v2 base count / modify_count used when saving stats.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a bug where `ANALYZE TABLE` could double count `mysql.stats_meta.count` and `modify_count` after a delayed cluster stats-delta flush.
```

## Summary by CodeRabbit

**Bug Fixes**
- Enhanced statistics accuracy during table analysis operations by ensuring pending statistics changes are properly handled before analysis begins. This improves the reliability of statistics-based query optimization.

### CODE REVIEW

File: pkg/executor/builder.go [hunk 1]
```diff
@@ -3312,6 +3312,10 @@ func (b *executorBuilder) buildAnalyze(v *plannercore.Analyze) exec.Executor {
 	if b.ctx.GetSessionVars().InRestrictedSQL {
 		autoAnalyze = "auto "
 	}
+	if err := flushStatsDeltaForAnalyze(kv.WithInternalSourceType(context.Background(), kv.InternalTxnStats), b.ctx, v); err != nil {
+		b.err = err
+		return nil
+	}
```
[the remark this answers is not in the document]
Comment (0xPoe) [reply pkg/executor/builder.go:3322]: Added a TODO for it.

[the remark this answers is not in the document]
Comment (0xPoe) [reply pkg/executor/builder.go:3322]: Create a one.

File: pkg/executor/builder.go [hunk 2]
```diff
@@ -3312,6 +3312,14 @@ func (b *executorBuilder) buildAnalyze(v *plannercore.Analyze) exec.Executor {
 	if b.ctx.GetSessionVars().InRestrictedSQL {
 		autoAnalyze = "auto "
 	}
+	// buildAnalyzeSamplingPushdown reads base count / modify_count from mysql.stats_meta
+	// while constructing column analyze tasks. Flush pending deltas first so the base
+	// values include pre-analyze changes and later delta dumps cannot double count them.
+	// TODO: Determine whether context.Background is appropriate here; if not, use the proper statement context.
```
Comment (0xPoe) [inline pkg/executor/builder.go:3318]: The reason I leave it as a TODO is that we also use context.Background() somewhere within buildAnalyzeSamplingPushdown. I would prefer to rethink this and fix them together.

File: pkg/executor/analyze.go [hunk 3]
```diff
@@ -87,6 +89,158 @@ const (
...
+// flushStatsDeltaForAnalyze flushes pending stats deltas for the tables whose column-analyze
+// tasks will capture base count / modify_count from mysql.stats_meta. Without this, a stale
+// pre-analyze delta can be applied later and double count rows or modifications.
+func flushStatsDeltaForAnalyze(ctx context.Context, sctx sessionctx.Context, plan *core.Analyze) error {
+	flushObjects := collectStatsDeltaFlushObjectsForAnalyze(plan)
+	if len(flushObjects) == 0 {
+		return nil
+	}
+
+	// HACK: Mock-store tests do not start TiDB RPC by default. In single-node tests,
```
Comment (0xPoe) [inline pkg/executor/analyze.go]: Not sure if you have a better idea for this. This is what I can come up with now.

File: pkg/statistics/handle/storage/gc_test.go [hunk 4]
```diff
@@ -89,11 +89,13 @@ func TestGCPartition(t *testing.T) {
 
 		testKit.MustExec("drop table t")
 		require.Nil(t, h.GCStats(dom.InfoSchema(), ddlLease))
-		testKit.MustQuery("select count(*) from mysql.stats_meta").Check(testkit.Rows("2"))
+		testKit.MustQuery("select count(*) from mysql.stats_meta").Check(testkit.Rows("3"))
 		testKit.MustQuery("select count(*) from mysql.stats_histograms").Check(testkit.Rows("0"))
 		testKit.MustQuery("select count(*) from mysql.stats_buckets").Check(testkit.Rows("0"))
+		// FIXME(#68076): The remaining row is the logical table's meta-only stats row. The
```
Comment (0xPoe) [inline pkg/statistics/handle/storage/gc_test.go:95]: Leave the fix for me at: https://github.com/pingcap/tidb/issues/68076

File: pkg/executor/builder.go (hunk 2 above)
Comment (0xPoe) [reply pkg/executor/builder.go:3318]: Track the issue at https://github.com/pingcap/tidb/issues/68074.

**Review by 0xPoe — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback)

- [x] Code compiles successfully

- [x] Unit tests added

- [x] No AI-generated elegant nonsense in PR.

- [x] Bazel files updated

- [x] Comments added where necessary

- [x] PR title and description updated

- [x] Documentation PR created (or confirmed not needed)

- [x] PR size is reasonable


/cc @terry1purcell @qw4990 @henrybw

File: pkg/executor/analyze.go (hunk 3 above)
Comment (henrybw) [reply pkg/executor/analyze.go]: Do you know if `broadcast()` has a fast path for the query that's getting sent to the local node? Or does the node that is calling `broadcast()` send an RPC to itself? (From what I can tell, I think the node that calls `broadcast()` sends an RPC to itself, but I'm not 100% sure.)

One idea would be to refactor this to include a fast path for the local node to call `executeFlushStatsDelta()` directly, rather than calling `broadcast()`, which (if `broadcast()` doesn't skip the roundtrip for the local node) would save a network hop in production. Then, this single-node detection logic could be used to only conditionally `broadcast()` when there is more than 1 node in the cluster topology.

Functionally it would be the same mechanism, but it turns the "hack" into a "fast path optimization". 🙂

**Review by henrybw — APPROVED** [review]
I think this is fine as-is: the "hack" is only for the testing path, and while there's a potential optimization I can see from improving it, I don't think it warrants blocking approval of this PR.

File: pkg/executor/analyze.go (hunk 3 above)
Comment (0xPoe) [reply pkg/executor/analyze.go]: > Do you know if `broadcast()` has a fast path for the query that's getting sent to the local node? Or does the node that is calling `broadcast()` send an RPC to itself? (From what I can tell, I think the node that calls `broadcast()` sends an RPC to itself, but I'm not 100% sure.)

Yes, I think you are correct. We do send the message to itself.

Comment (0xPoe) [reply pkg/executor/analyze.go]: > One idea would be to refactor this to include a fast path for the local node to call `executeFlushStatsDelta()` directly, rather than calling `broadcast()`, which (if `broadcast()` doesn't skip the roundtrip for the local node) would save a network hop in production. Then, this single-node detection logic could be used to only conditionally `broadcast()` when there is more than 1 node in the cluster topology.

Do you mean we should do it in flushStatsDeltaForAnalyze or in broadcast? If we implement this in flushStatsDeltaForAnalyze, do you mean we should always do it separately for the local node and conditionally broadcast to other nodes?

**Review by terry1purcell — APPROVED** [review]

File: pkg/executor/analyze.go (hunk 3 above)
Comment (henrybw) [reply pkg/executor/analyze.go]: > Do you mean we should do it in flushStatsDeltaForAnalyze or in broadcast? If we implement this in flushStatsDeltaForAnalyze, do you mean we should always do it separately for the local node and conditionally broadcast to other nodes?

Yeah, my idea was to implement this in `flushStatsDeltaForAnalyze` specifically, and always do it separately for the local node and conditionally broadcast only if there are multiple nodes in the cluster.

That said, now that you mention it, it would be nice if we could improve `broadcast` so that it didn't have to send an RPC message to itself. However, I'm not sure how feasible that is (plus it would be a larger project, out of scope for this at least). It would be nice if we improve that at some point in the future, though.

File: pkg/executor/analyze_utils_test.go [hunk 5]
```diff
@@ -27,3 +28,27 @@ func TestGetAnalyzePanicErr(t *testing.T) {
 	errMsg := fmt.Sprintf("%s", getAnalyzePanicErr(exeerrors.ErrMemoryExceedForQuery.GenWithStackByArgs(123)))
 	require.NotContains(t, errMsg, `%!(EXTRA`)
 }
+
+func TestCollectStatsDeltaFlushObjectsForAnalyzeDottedNames(t *testing.T) {
+	plan := &core.Analyze{
+		ColTasks: []core.AnalyzeColumnsTask{
+			// Quoted identifiers may contain dots. These first two targets both
+			// stringify to "a.b.c" if db and table names are joined with ".".
```
Comment (henrybw) [inline pkg/executor/analyze_utils_test.go:37]: Aha, tricky!

**Review by henrybw — APPROVED** [review]

**Review by 0xPoe — COMMENTED** [review]
/unhold

What I changed after the review is that some of the next-gen tests will leave the server IP as "", which causes the CI to fail when flushing the stats delta during auto-analyze.

So, I enhanced the check code path to avoid this issue.
