### PR TITLE
br: skip incomplete metakv

### LINKED ISSUE #61728: PiTR fail, error: the default cf kv is lost when there is its write cf kv
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. do PiTR on cluster B , which use cluster A‘s snapshot and log
2. after cluster B PiTR table filter success, do PiTR on cluster C which use cluster B's snapshot and log

### 2. What did you expect to see? (Required)
PiTR on cluster C failed, error msg like: 
`[ERROR] [restore.go:76] ["failed to restore"] [error="cannot restore the table(Id=2002902) because it is log restored(at 458679524451156942) before snapshot backup(at 458606073366971518). Please respecify the filter that does not contain the table or replace with a newer snapshot backup."]`

### 3. What did you see instead (Required)
PiTR on cluster C failed, error msg:
`[ERROR] [restore.go:76] ["failed to restore"] [error="the default cf kv is lost when there is its write cf kv(db id:2000512, table id:2000461, value UMCA0OfV5eGuBg==)"]`

### 4. What is your TiDB version? (Required)

Release Version: v8.5.0-20250609-a850b6f
Edition: Community
Git Commit Hash: a850b6f2634ee51c32b2ab8623c78035186e1278
Git Branch: heads/refs/tags/v8.5.0-20250609-a850b6f
UTC Build Time: 2025-06-09 02:24:01
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### LINKED ISSUE #61731: PiTR still fail after respecify the filter that does not contain the table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. do PiTR on cluster B , which use cluster A‘s snapshot and log
2. after cluster B PiTR table filter success, do PiTR on cluster C which use cluster B‘s log and  use `--filter=!=sbtest*.*` to exclude  data from cluster A

### 2. What did you expect to see? (Required)
pitr success

### 3. What did you see instead (Required)
pitr fail
`[ERROR] [restore.go:76] ["failed to restore"] [error="cannot restore the table(Id=2002902) because it is log restored(at 458679524451156942) before snapshot backup(at 458606073366971518). Please respecify the filter that does not contain the table or replace with a newer snapshot backup."]`

### 4. What is your TiDB version? (Required)

Release Version: v8.5.0-20250609-a850b6f
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/a850b6f2634ee51c32b2ab8623c78035186e1278
Git Branch: heads/refs/tags/v8.5.0-20250609-a850b6f
UTC Build Time: 2025-06-09 02:24:01
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #61728 close #61731

Problem Summary:
the incomplete metakv cannot be restored
### What changed and how does it work?
skip the incomplete metakv
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/restore/misc.go [hunk 1]
```diff
@@ -198,28 +208,40 @@ func CheckTableTrackerContainsTableIDsFromBlocklistFiles(
...
 				return errors.Errorf(
 					"cannot restore the table(Id=%d, name=%s at %d) because it is log restored(at %d) before snapshot backup(at %d). "+
 						"Please respecify the filter that does not contain the table or replace with a newer snapshot backup.",
-					tableId, tableNameByTableID(tableId), restoredTs, restoreCommitTs, startTs)
+					tableId, tableNameByTableId(tableId), restoredTs, restoreCommitTs, startTs)
 			}
 			// the meta kv may not be backed by log restore
-			if checkTableIDLost(tableId) {
+			if checkTableIdLost(tableId) {
+				log.Warn("the table is lost in the log backup storage, so that it can not be restored.", zap.Int64("table id", tableId))
```
Comment (Tristan1900) [inline br/pkg/restore/misc.go:229]: maybe use Info level? as this is expected, and maybe rephrase the log message, I feel like it might be a bit concerning to see this log if people don't have context

File: br/pkg/restore/misc.go [hunk 2]
```diff
@@ -198,28 +208,40 @@ func CheckTableTrackerContainsTableIDsFromBlocklistFiles(
...
-					"cannot restore the table(Id=%d) because it is log restored(at %d) before snapshot backup(at %d). "+
-						"Please respecify the filter that does not contain the table or replace with a newer snapshot backup.",
-					tableId, restoreCommitTs, startTs,
-				)
+					"cannot restore the database(Id=%d, name %s at %d) because it is log restored(at %d) before snapshot backup(at %d). "+
+						"Please respecify the filter that does not contain the database or replace with a newer snapshot backup.",
+					dbId, dbNameByDbId(dbId), restoredTs, restoreCommitTs, startTs)
+			}
+			// the meta kv may not be backed by log restore
+			if checkDBIdlost(dbId) {
```
Comment (Tristan1900) [inline br/pkg/restore/misc.go:240]: actually do we need this check since it can lost for a reason? how about just keep the tracker check

File: br/pkg/restore/misc.go [hunk 3]
```diff
@@ -62,8 +62,12 @@ type LogRestoreTableIDsBlocklistFile struct {
 	// SnapshotBackupTs records the BackupTS of the PITR restore. Any PITR restore from the log backup of the cluster, whose restoredTS
 	// is less than it, can ignore the restore table IDs blocklist recorded in the file.
 	SnapshotBackupTs uint64 `protobuf:"varint,2,opt,name=snapshot_backup_ts,proto3"`
-	// TableIDs records the table IDs blocklist of the cluster running the log backup task.
+	// RewriteTs records the rewritten timestamp of the meta kvs in this PITR restore.
+	RewriteTs uint64 `protobuf:"varint,6,opt,name=rewrite_ts,proto3"`
```
Comment (Tristan1900) [inline br/pkg/restore/misc.go:66]: hmm, what's the difference between `RewriteTs` and  `RestoreCommitTs `

Comment (Leavrth) [reply br/pkg/restore/misc.go:66]: `RestoreCommitTs` > `RewriteTs`
Therefore, `RestoreCommitTs` is newer than the timestamp of any kv that is restored by log restore.

File: br/pkg/stream/table_mapping.go [hunk 4]
```diff
@@ -482,17 +487,18 @@ func (tm *TableMappingManager) parseTableValueAndUpdateIdMappingForWriteCf(
...
-	log.Error("default cf kv is lost when processing write cf kv for table",
+	log.Warn("default cf kv is lost when processing write cf kv for table",
 		zap.Int64("db-id", dbId),
 		zap.Int64("table-id", tableId),
 		zap.Uint64("start-ts", startTs),
 		zap.Uint64("commit-ts", commitTs),
 		zap.String("value", base64.StdEncoding.EncodeToString(value)),
 		zap.Int("temp-default-kv-table-map-size", len(tm.tempDefaultKVTableMap)))
-	return errors.Errorf(
+	tm.noDefaultKVErrorMap[commitTs] = errors.Errorf(
```
Comment (3pointer) [inline br/pkg/stream/table_mapping.go:497]: why this error can be cleaned?

File: br/pkg/restore/misc.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/restore/misc.go:229]: Maybe the tableId is included in the `--filter`, and the user want to restore it. However, finally it is not restored.

**Review by 3pointer — APPROVED** [review]

**Comment by Tristan1900** [comment]
/lgtm
/hold
for one unaddressed comment
