### PR TITLE
*: fix data race caused by analyzeStatus.

### LINKED ISSUE #15510: Data race in `TestForAnalyzeStatus`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
[2020-03-20T02:57:28.670Z] WARNING: DATA RACE

[2020-03-20T02:57:28.670Z] Read at 0x00c00d759b78 by goroutine 666:

[2020-03-20T02:57:28.670Z]   github.com/pingcap/tidb/statistics.GetAllAnalyzeJobs.func1()

[2020-03-20T02:57:28.670Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:89 +0x94

[2020-03-20T02:57:28.670Z]   sort.insertionSort_func()

[2020-03-20T02:57:28.670Z]       /usr/local/go/src/sort/zfuncversion.go:12 +0xbb

[2020-03-20T02:57:28.670Z]   sort.quickSort_func()

[2020-03-20T02:57:28.670Z]       /usr/local/go/src/sort/zfuncversion.go:158 +0x205

[2020-03-20T02:57:28.670Z]   sort.Slice()

[2020-03-20T02:57:28.670Z]       /usr/local/go/src/sort/slice.go:17 +0x11e

[2020-03-20T02:57:28.670Z]   github.com/pingcap/tidb/statistics.GetAllAnalyzeJobs()

[2020-03-20T02:57:28.670Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:89 +0x3bf

[2020-03-20T02:57:28.670Z]   github.com/pingcap/tidb/executor.dataForAnalyzeStatusHelper()

[2020-03-20T02:57:28.670Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:1281 +0xc2

[2020-03-20T02:57:28.670Z]   github.com/pingcap/tidb/executor.(*memtableRetriever).retrieve()

[2020-03-20T02:57:28.670Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:1307 +0x103d

[2020-03-20T02:57:28.670Z]   github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:110 +0x6fe

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:216 +0x167

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor.(*SelectionExec).Next()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1170 +0x6e5

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:216 +0x167

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:126 +0x110

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/session.GetRows4Test()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:338 +0x35a

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/session.ResultSetToStringSlice()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:356 +0xb8

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResultWithCtx()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:287 +0xa8

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:282 +0x4e4

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:520 +0x7ad

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:513 +0x62c

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:494 +0x166

[2020-03-20T02:57:28.671Z]   runtime.call32()

[2020-03-20T02:57:28.671Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-03-20T02:57:28.671Z]   reflect.Value.Call()

[2020-03-20T02:57:28.671Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-03-20T02:57:28.671Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-03-20T02:57:28.671Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-03-20T02:57:28.671Z] 

[2020-03-20T02:57:28.671Z] Previous write at 0x00c00d759b78 by goroutine 659:

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/statistics.(*AnalyzeJob).Start()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:99 +0xf6

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor.(*AnalyzeExec).analyzeWorker()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze.go:190 +0x133

[2020-03-20T02:57:28.671Z] 

[2020-03-20T02:57:28.671Z] Goroutine 666 (running) created at:

[2020-03-20T02:57:28.671Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-03-20T02:57:28.671Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-03-20T02:57:28.671Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-03-20T02:57:28.671Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7

[2020-03-20T02:57:28.671Z] 

[2020-03-20T02:57:28.671Z] Goroutine 659 (running) created at:

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor.(*AnalyzeExec).Next()

[2020-03-20T02:57:28.671Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze.go:86 +0x1b0

[2020-03-20T02:57:28.671Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:216 +0x167

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:516 +0x38e

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:395 +0x1a2

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:363 +0x3bc

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/session.runStmt()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:281 +0x36d

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/session.(*session).executeStatement()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1035 +0x112

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/session.(*session).execute()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1138 +0xb29

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/session.(*session).Execute()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1074 +0xee

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:144 +0x103

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:182 +0x91

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).testAnalyzeIncremental()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:372 +0x11e

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).testAnalyzeIncremental()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:371 +0xe7

[2020-03-20T02:57:28.672Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).TestAnalyzeIncremental()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:358 +0x127

[2020-03-20T02:57:28.672Z]   runtime.call32()

[2020-03-20T02:57:28.672Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-03-20T02:57:28.672Z]   reflect.Value.Call()

[2020-03-20T02:57:28.672Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-03-20T02:57:28.672Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-03-20T02:57:28.672Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-03-20T02:57:28.672Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master

### LINKED ISSUE #15521: bug: data race
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
data race occur 
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/28246/pipeline 

```
[2020-03-20T02:50:36.248Z] PASS: admin_test.go:500: testSuite5.TestAdminCheckTableFailed	2.793s

[2020-03-20T02:50:36.248Z] ==================

[2020-03-20T02:50:36.248Z] WARNING: DATA RACE

[2020-03-20T02:50:36.248Z] Read at 0x00c01db8b0c8 by goroutine 551:

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/statistics.GetAllAnalyzeJobs.func1()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:89 +0x12a

[2020-03-20T02:50:36.248Z]   sort.quickSort_func()

[2020-03-20T02:50:36.248Z]       /usr/local/go/src/sort/zfuncversion.go:154 +0x1c7

[2020-03-20T02:50:36.248Z]   sort.Slice()

[2020-03-20T02:50:36.248Z]       /usr/local/go/src/sort/slice.go:17 +0x11e

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/statistics.GetAllAnalyzeJobs()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:89 +0x3bf

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor.dataForAnalyzeStatusHelper()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:1281 +0xc2

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor.(*memtableRetriever).retrieve()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:1307 +0x103d

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:110 +0x6fe

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:216 +0x167

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor.(*SelectionExec).Next()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1170 +0x6e5

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:216 +0x167

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:126 +0x110

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/session.GetRows4Test()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:338 +0x35a

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/session.ResultSetToStringSlice()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:356 +0xb8

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).ResultSetToResultWithCtx()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:287 +0xa8

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:282 +0x4e4

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:520 +0x7ad

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:513 +0x62c

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestForAnalyzeStatus()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:494 +0x166

[2020-03-20T02:50:36.248Z]   runtime.call32()

[2020-03-20T02:50:36.248Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-03-20T02:50:36.248Z]   reflect.Value.Call()

[2020-03-20T02:50:36.248Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-03-20T02:50:36.248Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-03-20T02:50:36.248Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-03-20T02:50:36.248Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-03-20T02:50:36.248Z] 

[2020-03-20T02:50:36.248Z] Previous write at 0x00c01db8b0c8 by goroutine 355:

[2020-03-20T02:50:36.248Z]   github.com/pingcap/tidb/statistics.(*AnalyzeJob).Finish()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:119 +0xc4

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor.(*AnalyzeExec).Next()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze.go:121 +0x810

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor.Next()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:216 +0x167

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:516 +0x38e

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:395 +0x1a2

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor.(*ExecStmt).Exec()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:363 +0x3bc

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/session.runStmt()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:281 +0x36d

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/session.(*session).executeStatement()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1035 +0x112

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/session.(*session).execute()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1138 +0xb29

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/session.(*session).Execute()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1074 +0xee

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:144 +0x103

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:182 +0x91

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).testAnalyzeIncremental()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:375 +0x229

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).testAnalyzeIncremental()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:371 +0xe7

[2020-03-20T02:50:36.249Z]   github.com/pingcap/tidb/executor_test.(*testSuite1).TestAnalyzeIncremental()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:358 +0x127

[2020-03-20T02:50:36.249Z]   runtime.call32()

[2020-03-20T02:50:36.249Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-03-20T02:50:36.249Z]   reflect.Value.Call()

[2020-03-20T02:50:36.249Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-03-20T02:50:36.249Z] 

[2020-03-20T02:50:36.249Z] Goroutine 551 (running) created at:

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7

[2020-03-20T02:50:36.249Z] 

[2020-03-20T02:50:36.249Z] Goroutine 355 (running) created at:

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a

[2020-03-20T02:50:36.249Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2020-03-20T02:50:36.249Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7

[2020-03-20T02:50:36.249Z] ==================

[2020-03-20T02:50:36.249Z] PASS: infoschema_reader_test.go:489: testInfoschemaTableSuite.TestForAnalyzeStatus	2.003s

[2020-03-20T02:50:36.249Z] PASS: infoschema_reader_test.go:524: testInfoschemaTableSuite.TestForServersInfo	0.004s

[2
```

### PR DESCRIPTION
**Pull request by reafans**
### What problem does this PR solve?

Issue Number: close #15510，close #15521 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
The global variable `analyzeStatus ` which not be locked in `analyze_jobs.go:89` caused data race among the UT.
Now locked it.

### CODE REVIEW

**Comment by reafans** [comment]
@SunRunAway, PTAL, it also have a race in `sort.Slice(jobs, func(i int, j int) bool { return jobs[i].updateTime.Before(jobs[j].updateTime) })` because it only lock the analyzeStatus, and the `*AnalyzeJob.updateTime` in it also can be changed, so i add the lock when get the `updateTime`.

File: statistics/analyze_jobs.go [hunk 1]
```diff
@@ -80,13 +80,13 @@ func ClearHistoryJobs() {
 // GetAllAnalyzeJobs gets all analyze jobs.
 func GetAllAnalyzeJobs() []*AnalyzeJob {
 	analyzeStatus.Lock()
+	defer analyzeStatus.Unlock()
```
Comment (SunRunAway) [inline statistics/analyze_jobs.go]: Thus, this change is not necessary.

Comment (reafans) [reply statistics/analyze_jobs.go]: em...., i think it is also useful, because the jobs in `analyzeStatus` be appended in this func，which need a lock to prevent other operation change the `analyzeStatus`.

Comment (SunRunAway) [reply statistics/analyze_jobs.go]: But the sort operation need not in the critical section

Comment (reafans) [reply statistics/analyze_jobs.go]: got it, addressed comment, @SunRunAway PTAL
