### PR TITLE
executor: kill tableReader for each connection correctly

### LINKED ISSUE #18057: executor: avoid goroutine leak in TableReader along with memory leak
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The [source code](https://github.com/pingcap/tidb/blob/ddcc89dc793fbc89852071702996ea212c342efb/store/tikv/coprocessor.go#L529) only generates go routines, but not handle errors if some exceptions happens.
To to reproduce this issue using failpoint.

On the other hand, if the main thread is cancelled, those generated goroutines should stop correctly.

detail problems:

- [ ] TableReader->Next() is blocked, how to stop the execution once cancel the query manually?
- [ ] When call TableReader->Close(), how to stop coprocessor workers?
- [ ] When coprocessor workes panic, how to cancel the query correctly?
- [ ] what about IndexReader?

### 2. What did you expect to see? (Required)
all goroutine stops and return errors.

### 3. What did you see instead (Required)
other goroutine runs normally and occupy many memory .

### 4. Affected version (Required)
v4.0.x, v3

### 5. Root Cause Analysis
lack handing exceptions.

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: close a part of #18057 

Problem Summary:
The tableReader in the coprocessor may retry many times to read regions, druing which, it cannot be aware of the cancelation from client. It may take much of memory for a long time. 

### What is changed and how it works?

Proposal: detect `Killed` to stop the goroutine.

What's Changed: should not use `CompareAndSwap` to change the `Killed` before Close(), because many runninig goroutines should detect the `Killed`.

How it Works: the TableReader the detect the `killed` in every loop.
The query may not exit quickly, because the query do some close work.

### Check List 

Tests 

- Integration test 
- Manual test (add detailed scripts or steps below)
test on mocktikv:
```
step1. explain analyze select * from lineitem;
step2. kill tidb sessionID on another client;
to see the connection is cancelled.
```
similarly test on TiFlash is ok.

### Release note 

- To speed up canceling a query

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -532,7 +535,7 @@ func (s *Server) getTLSConfig() *tls.Config {
 
 func killConn(conn *clientConn) {
 	sessVars := conn.ctx.GetSessionVars()
-	atomic.CompareAndSwapUint32(&sessVars.Killed, 0, 1)
+	atomic.StoreUint32(&sessVars.Killed, 1)
```
Comment (qw4990) [inline server/server.go:538]: Is there some tricky reason that we use `CAS` instead of `Store` here at the begging? Please help us to confirm this. @tiancaiamao

Comment (tiancaiamao) [reply server/server.go:538]: Exception handling is a hard.

If we use `CAS`, exception handling is the same as error handling:
- one of the goroutine detect kill (CAS), it return an error
- the error is throw to the main loop
- the main loop handle worker's Close

This processing is exactly the same as the error handling, when one of the worker get an error.

Exception handling is much difficult than error handling.
- The the worker and main loop does not know when the exception happen
- Every worker has to handle the exception
- The exception handle is tricky, should the worker kill itself or report error to the main loop and let it kill worker? Will the Close repeat message repeat and Close multiple times?

File: store/tikv/region_request.go [hunk 2]
```diff
@@ -217,7 +221,18 @@ func (s *RegionRequestSender) SendReqCtx(
 		if err != nil {
 			return nil, nil, errors.Trace(err)
 		}
+
+		// recheck whether the session/query is killed during the Next()
+		if bo.vars != nil && bo.vars.Killed != nil && atomic.LoadUint32(bo.vars.Killed) == 1 {
```
Comment (tiancaiamao) [inline store/tikv/region_request.go:226]: Maybe the only change necessary is to check `CAS(killed)` here?
And another question is, why backoff does not check it.

**Comment by tiancaiamao** [comment]
I've find the real cause.

**Comment by tiancaiamao** [comment]
The problem is that current implementation do not really support "cancel" something.
The cancel is implemented by by caller to set the `Killed` flag and let the callee to inspect it.
If the callee is block on network sending, it has no change to detect `Killed`.

The callee may block on the network for a long time, because in the rpc error scenario,
send request timeout is not accumulated into the backoff duration.

https://github.com/pingcap/tidb/pull/17135/files#diff-deb6c7bcc2ba593559c11d2e92f8d8dcR56

I do not have any better ideas to fix those issues eithor, so this commit LGTM

File: server/server.go [hunk 3]
```diff
@@ -400,6 +400,9 @@ func (s *Server) onConn(conn *clientConn) {
 	if plugin.IsEnable(plugin.Audit) {
 		sessionVars.ConnectionInfo = conn.connectInfo()
 	}
+	type vars struct {
+		killed *uint32
+	}
```
Comment (qw4990) [inline server/server.go:405]: These lines are unnecessary, so how about removing them?

Comment (fzhedu) [reply server/server.go:405]: > These lines are unnecessary, so how about removing them?

ok, I will remove in my next PR.
