### PR TITLE
executor: fix float data accuracy

### LINKED ISSUE #20066: Compatibility: FLOAT data accuracy
## Description

```
DROP TABLE IF EXISTS t_5_1_1_1_float;
CREATE TABLE t_5_1_1_1_float ( col1 FLOAT, col2 FLOAT(10,2), col3 DOUBLE, col4 DOUBLE(10,2), col5 DECIMAL, col6  DECIMAL(10,2) ) ;
INSERT INTO t_5_1_1_1_float VALUES (-3.402823466E+38, -34028234.66, -1.7976931348623157E+308, -17976921.34, -9999999999, -99999999.99);
SELECT * FROM t_5_1_1_1_float;
```
TiDB presents a different result set, I assume it's the FLOAT accuracy issue, PTAL

TiDB 4.0.5
```
mysql> SELECT * FROM t_5_1_1_1_float;
+---------------+--------------+-------------------------+--------------+-------------+--------------+
| col1          | col2         | col3                    | col4         | col5        | col6         |
+---------------+--------------+-------------------------+--------------+-------------+--------------+
| -3.4028235e38 | -34028236.00 | -1.7976931348623157e308 | -17976921.34 | -9999999999 | -99999999.99 |
+---------------+--------------+-------------------------+--------------+-------------+--------------+
1 row in set (0.00 sec)
```

MySQL 5.7.29
```
mysql> SELECT * FROM t_5_1_1_1_float;
+-------------+--------------+-------------------------+--------------+-------------+--------------+
| col1        | col2         | col3                    | col4         | col5        | col6         |
+-------------+--------------+-------------------------+--------------+-------------+--------------+
| -3.40282e38 | -34028236.00 | -1.7976931348623157e308 | -17976921.34 | -9999999999 | -99999999.99 |
+-------------+--------------+-------------------------+--------------+-------------+--------------+
1 row in set (0.00 sec)
```

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by Win-Man**
### What problem does this PR solve?

Issue Number: close #20066 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Change the `appendFormatFloat` function in `server/util.go`.

How it Works:
Maintain the same accuracy as MySQL when without specifying the default accuracy, and remove extrac `0` in out result.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

File: server/util_test.go [hunk 1]
```diff
@@ -341,6 +341,24 @@ func (s *testUtilSuite) TestAppendFormatFloat(c *C) {
 			-1,
 			64,
 		},
+		{
+			-340282346638528860000000000000000000000,
+			"-3.40282e38",
+			-1,
```
Comment (SunRunAway) [inline server/util_test.go:347]: Please add more cases for `prec==-1`

Comment (Win-Man) [reply server/util_test.go:347]: Done

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
