### PR TITLE
expression: handle hybrid field types for where clause

### LINKED ISSUE #12201: ERROR 1105 (HY000): expected integer
## Bug Report

MySQL

```
mysql> SELECT DISTINCT BIT_OR( '11:34:28.039509' ) AS field1 FROM `table1000_int_autoinc` WHERE CASE ( `col_char_255_key` >> -9218868437227405312 ) WHEN ( ( SUBTIME( '2016-02-13', `col_set` ) ) < 'k' ) THEN `col_enum` END GROUP BY ROW_COUNT();
--------------
SELECT DISTINCT BIT_OR( '11:34:28.039509' ) AS field1 FROM `table1000_int_autoinc` WHERE CASE ( `col_char_255_key` >> -9218868437227405312 ) WHEN ( ( SUBTIME( '2016-02-13', `col_set` ) ) < 'k' ) THEN `col_enum` END GROUP BY ROW_COUNT()
--------------

Empty set, 2456 warnings (0.01 sec)
```

TiDB

```
mysql> SELECT DISTINCT BIT_OR( '11:34:28.039509' ) AS field1 FROM `table1000_int_autoinc` WHERE CASE ( `col_char_255_key` >> -9218868437227405312 ) WHEN ( ( SUBTIME( '2016-02-13', `col_set` ) ) < 'k' ) THEN `col_enum` END GROUP BY ROW_COUNT();
--------------
SELECT DISTINCT BIT_OR( '11:34:28.039509' ) AS field1 FROM `table1000_int_autoinc` WHERE CASE ( `col_char_255_key` >> -9218868437227405312 ) WHEN ( ( SUBTIME( '2016-02-13', `col_set` ) ) < 'k' ) THEN `col_enum` END GROUP BY ROW_COUNT()
--------------

ERROR 1105 (HY000): expected integer
```
## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #12201 

### What is changed and how it works?

What's Changed: add handling for hybrid data types when evaluate bool

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

### Release note 

- No release note.

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -7142,3 +7142,12 @@ func (s *testSuite) Test15492(c *C) {
...
 	tk.MustQuery("select a + 1 as field1, a as field2 from t order by field1, field2 limit 2").Check(testkit.Rows("2 1", "3 2"))
 }
+
+func (s *testSuite) Test12201(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists e")
+	tk.MustExec("create table e (e enum('a', 'b'))")
+	tk.MustExec("insert into e values ('a')")
+	tk.MustExec("select * from e where case 1 when 0 then e end")
```
Comment (wjhuang2016) [inline executor/executor_test.go:7152]: Please check the result.

Comment (XuHuaiyu) [reply executor/executor_test.go:7152]: Test case for set and bit is also needed

Comment (ichn-hu) [reply executor/executor_test.go:7152]: Test for set and bit is at here: https://github.com/pingcap/tidb/pull/20221/files

**Comment by ichn-hu** [comment]
@XuHuaiyu @wjhuang2016 PTAL

File: executor/executor_test.go [hunk 2]
```diff
@@ -7142,3 +7142,12 @@ func (s *testSuite) Test15492(c *C) {
...
 	tk.MustQuery("select a + 1 as field1, a as field2 from t order by field1, field2 limit 2").Check(testkit.Rows("2 1", "3 2"))
 }
+
+func (s *testSuite) Test12201(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists e")
+	tk.MustExec("create table e (e enum('a', 'b'))")
+	tk.MustExec("insert into e values ('a')")
+	tk.MustQuery("select * from e where case 1 when 0 then e end").Check(testkit.Rows())
```
Comment (wjhuang2016) [inline executor/executor_test.go:7152]:
```
insert into e values ('a'), ('b');
select * from e where case 1 when 1 then e end;
select * from e where case e when 1 then e end;
select * from e where case 1 when e then e end;
```
This test is too weak to test modification. It would be better to add the above tests.

Comment (wjhuang2016) [reply executor/executor_test.go:7152]: Besides, please test `set` and `bit` too.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: executor/executor_test.go (hunk 2 above)
Comment (ichn-hu) [reply executor/executor_test.go:7152]: Sure, thanks!

Comment (ichn-hu) [reply executor/executor_test.go:7152]: Addressed

**Comment by ichn-hu** [comment]
@wjhuang2016 comment addressed, PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
