### PR TITLE
br: recursive split batch create table when restore failure on batch create table

### LINKED ISSUE #39029: br fail to restore due to entry too large
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

restore a dataset with 50k tables as below

```
tiup br:v6.1.1 restore db --db=bank50k --pd xxx --storage xxx   --s3.endpoint xxx --send-credentials-to-tikv=true --check-requirements=false
```

### 2. What did you expect to see? (Required)

```
[2022/11/09 17:24:53.607 +08:00] [WARN] [glue.go:199] ["batch create table from tidb failure"] [error="[kv:8025]entry too large, the max entry size is 6291456, the size of data is 7314276"] [errorVerbose="[kv:8025]entry too large, the max entry size is 6291456, the size of data is 7314276\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tidb/ddl.(*ddl).DoDDLJob\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/ddl/ddl.go:704\ngithub.com/pingcap/tidb/ddl.(*ddl).BatchCreateTableWithInfo\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/ddl/ddl_api.go:2451\ngithub.com/pingcap/tidb/br/pkg/gluetidb.(*tidbSession).CreateTables\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/gluetidb/glue.go:194\ngithub.com/pingcap/tidb/br/pkg/restore.(*DB).CreateTables\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/db.go:292\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).createTables\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:609\ngithub.com/pingcap/tidb/br/pkg/restore.(*Client).createTablesInWorkerPool.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:799\ngithub.com/pingcap/tidb/br/pkg/utils.(*WorkerPool).ApplyWithIDInErrorGroup.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/utils/worker.go:82\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:74\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]
[2022/11/09 17:24:53.607 +08:00] [ERROR] [client.go:806] ["create tables fail"] [stack="github.com/pingcap/tidb/br/pkg/restore.(*Client).createTablesInWorkerPool.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/restore/client.go:806\ngithub.com/pingcap/tidb/br/pkg/utils.(*WorkerPool).ApplyWithIDInErrorGroup.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/utils/worker.go:82\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:74"]
```

### 3. What did you see instead (Required)
restore error and br not completed

### 4. What is your TiDB version? (Required)
br and tidb are both v6.1.1

### PR DESCRIPTION
**Pull request by fengou1**
### What problem does this PR solve?

Issue Number: close #39029

Problem Summary:
restore failure when the batch size of create tables' schema large than the raft entry size (6MB).

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/gluetidb/glue.go [hunk 1]
```diff
@@ -203,13 +203,33 @@ func (gs *tidbSession) CreatePlacementPolicy(ctx context.Context, policy *model.
 	return d.CreatePlacementPolicyWithInfo(gs.se, policy, ddl.OnExistIgnore)
 }
 
+// SplitBatchCreateTable provide a way to split batch into small batch when batch size is large than 6 MB.
+// The raft entry has limit size of 6 MB, a batch of CreateTables may hit this limitation
+// TODO: shall query string be set for each split batch create, it looks does not matter if we set once for all.
+func (gs *tidbSession) SplitBatchCreateTable(schema model.CIStr, info []*model.TableInfo, l int, r int, cs ...ddl.CreateTableWithInfoConfigurier) error {
```
Comment (YuJuncen) [inline br/pkg/gluetidb/glue.go:209]: In fact we can make subranges of slices fast, perhaps consider remove the `l` and `r` arguments, and:
```go
if err := BatchCreateTable(info); isEntryTooLarge(err) {
  if len(info) == 1 { return err }
  mid := len(info) / 2
  if err := BatchCreateTable(info[:mid]); err != nil { return err }
  if err := BatchCreateTable(info[mid:]); err != nil { return err }
  return nil
}
```

**Review by YuJuncen — COMMENTED** [review]
rest lgtm

File: br/pkg/gluetidb/glue.go (hunk 1 above)
Comment (fengou1) [reply br/pkg/gluetidb/glue.go]: fix in [2e0df43](https://github.com/pingcap/tidb/pull/39829/commits/2e0df43482cc4bd06cabe36cbcec643dd5840709)

**Review by YuJuncen — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]
