### PR TITLE
privilege: fix wrong result of `SHOW GRANTS`

### LINKED ISSUE #17794: P2-[4.0-bug-hunting]-[ Role-Based Access Control]-Show grants is not accurate
Bug Hunter issue tidb-challenge-program/bug-hunting-issue#29

---

## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
CREATE USER 'root'@'127.0.%' IDENTIFIED BY 'notroot';
```

Login as:
```
mysql -uroot -pnotroot
```

### 2. What did you expect to see?

This should work, since in MySQL a user is the combination of user + host. However, the `SHOW GRANTS` should show only usage:

```
mysql> show grants;
+----------------------------------------+
| Grants for root@127.0.%                |
+----------------------------------------+
| GRANT USAGE ON *.* TO `root`@`127.0.%` |
+----------------------------------------+
1 row in set (0.00 sec)

```

### 3. What did you see instead?

This is probably a stretch to be a P1, but the criteria is not quite clear. Show grants is showing privileges for "the other root", but at least trying a command fails as expected:

```
mysql> show grants;
+-------------------------------------------------------------------+
| Grants for User                                                   |
+-------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.%' WITH GRANT OPTION |
+-------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select user,host,authentication_string from mysql.user where user='root';
ERROR 1142 (42000): SELECT command denied to user 'root'@'127.0.%' for table 'user'
```

This is unlikely to be a privilege escalation (at first I thought it was), but it does make debugging harder if the diagnostic commands do not consider both user + host.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-290-ga0c740784
Git Commit Hash: a0c7407846fbc84f939afbc091f2db54f48c1bfa
Git Branch: master
UTC Build Time: 2020-04-17 04:04:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve?

Issue Number: close #17794  

Problem Summary:
If a user share a common prefix of wildcard host name like `%` and `127.0.0.1`. `showGrants` will regard them as same host name. So when you show grants of `root@127.0.%`, TiDB will gather `root@%`, `root@127.%` and `root@127.0.%` and print the sum privilege of these user.

### What is changed and how it works?

What's Changed:
Because parameter in `privilege.showGrant` is `AuthHostname`. We can use string match to check host match directly rather than compare wildcard.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- None

### Release note 

- Fix wrong result of `SHOW GRANTS`

### CODE REVIEW

File: privilege/privileges/cache.go [hunk 1]
```diff
@@ -1019,7 +1019,7 @@ func (p *MySQLPrivilege) showGrants(user, host string, roles []*auth.RoleIdentit
 	}
 	var g string
 	for _, record := range p.User {
-		if record.baseRecord.match(user, host) {
+		if user == record.User && host == record.Host {
```
Comment (qw4990) [inline privilege/privileges/cache.go:1022]: How about creating a new function for this match, for example `record.baseRecord.completeMatch()`?

**Comment by tiancaiamao** [comment]
LGTM

File: privilege/privileges/cache.go [hunk 2]
```diff
@@ -1019,7 +1023,7 @@ func (p *MySQLPrivilege) showGrants(user, host string, roles []*auth.RoleIdentit
...
```
Comment (qw4990) [inline privilege/privileges/cache.go:1026]: Why not use `record.fullyMatch` here?

Comment (imtbkcat) [reply privilege/privileges/cache.go]: PTAL @qw4990

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
