### PR TITLE
br/lightning: don't make NextMajorVersion() crash if ReleaseVersion is not a semver

### LINKED ISSUE #29185: Lightning: Crashes if built without git tags
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Clone the tidb repo directory, without any tags
2. `make build_lightning`
3. `bin/tidb-lightning --help`

### 2. What did you expect to see? (Required)

Lightning's help page.

### 3. What did you see instead (Required)

```
panic: b7ed87d is not in dotted-tri format

goroutine 1 [running]:
github.com/coreos/go-semver/semver.Must(...)
        /go/pkg/mod/github.com/coreos/go-semver@v0.3.0/semver/semver.go:65
github.com/coreos/go-semver/semver.New(0xc00089a980, 0x7, 0xc00089a980)

        /go/pkg/mod/github.com/coreos/go-semver@v0.3.0/semver/semver.go:49 +0x77
github.com/pingcap/tidb/br/pkg/version.NextMajorVersion(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/tidb/br/pkg/version/version.go:35 +0x70
github.com/pingcap/tidb/br/pkg/lightning/backend/importer.init()
        /data/tidb/br/pkg/lightning/backend/importer/importer.go:53 +0x145
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Issue Number: close #29185

Problem Summary:

### What is changed and how it works?

If `build.ReleaseVersion` cannot be parsed as a semver just assume it is built from source without tag information and make `NextMajorVersion()` return `MaxInt64.0.0-nightly`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
    * run `./tidb-lightning` after applying the patch.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

(it's a bug-fix ok but only affects custom-built code so doesn't need a release note ok)

### CODE REVIEW

File: br/pkg/version/version.go [hunk 1]
```diff
@@ -32,7 +33,11 @@ var (
 
 // NextMajorVersion returns the next major version.
 func NextMajorVersion() semver.Version {
-	nextMajorVersion := semver.New(removeVAndHash(build.ReleaseVersion))
+	nextMajorVersion, err := semver.NewVersion(removeVAndHash(build.ReleaseVersion))
+	if err != nil {
+		// build.ReleaseVersion is unknown, assuming infinitely-new nightly version.
+		return semver.Version{Major: math.MaxInt64, PreRelease: "nightly"}
```
Comment (glorv) [inline br/pkg/version/version.go:39]:
```suggestion
		return semver.Version{PreRelease: "nightly"}
```
I think we should make next version to 0 so it will fail all the version check.

**Review by glorv — COMMENTED** [review]
rest LGTM

File: br/pkg/version/version.go (hunk 1 above)
Comment (glorv) [reply br/pkg/version/version.go:39]: BTW, shall we output a `WARN` log here

**Review by glorv — APPROVED** [review]
