### PR TITLE
planner: handle double NOT in outer join

### LINKED ISSUE #65937: Checksum mismatch after NOT NOT rewrite in LEFT JOIN ON condition
### What did you do?

Run two semantically equivalent queries (EET rewrite: `double_not` on a `LEFT JOIN ... ON` condition). The queries return the same row count but different checksum.

**Query A (expected):**
```sql
SELECT 85.11 AS c0, t0.p1 AS c1, '2024-01-02 12:28:00' AS c2
FROM t0
RIGHT JOIN t1 ON (t0.k0 = t1.k0)
JOIN t3 ON (t0.k0 = t3.k0)
LEFT JOIN t2 ON (t0.k0 = t2.k0)
LEFT JOIN t4 ON (t0.k0 = t4.k0)
WHERE (t0.k0 <=> t3.k0)
ORDER BY (t3.d0 - t2.k1) DESC, t1.d0 DESC
LIMIT 13;
```

**Query B (actual):**
```sql
SELECT 85.11 AS `c0`, `t0`.`p1` AS `c1`, _UTF8MB4'2024-01-02 12:28:00' AS `c2`
FROM (((`t0` RIGHT JOIN `t1` ON (`t0`.`k0` = `t1`.`k0`))
        JOIN `t3` ON (`t0`.`k0` = `t3`.`k0`))
       LEFT JOIN `t2` ON NOT NOT (`t0`.`k0` = `t2`.`k0`))
      LEFT JOIN `t4` ON (`t0`.`k0` = `t4`.`k0`)
WHERE (`t0`.`k0` <=> `t3`.`k0`)
ORDER BY (`t3`.`d0` - `t2`.`k1`) DESC, `t1`.`d0` DESC
LIMIT 13;
```

Both are wrapped by a signature query:
```sql
SELECT COUNT(*) AS cnt,
       IFNULL(BIT_XOR(CRC32(CONCAT_WS('#', q.c0, q.c1, q.c2))), 0) AS checksum
FROM (
  -- Query A or Query B
) q;
```

### What did you expect?

Same checksum for Query A and Query B.

Observed:
- Query A: `cnt=13 checksum=1659694367`
- Query B: `cnt=13 checksum=2631927963`

### What did you see instead?

Checksum mismatch with identical row count. The difference appears after rewriting the `LEFT JOIN t2 ON (t0.k0 = t2.k0)` predicate to `LEFT JOIN t2 ON NOT NOT (t0.k0 = t2.k0)`.

### How to reproduce

1) Apply schema
<details>
<summary>schema.sql</summary>

```sql
SET FOREIGN_KEY_CHECKS=0;
DROP VIEW IF EXISTS v4;
DROP VIEW IF EXISTS v3;
DROP VIEW IF EXISTS v2;
DROP VIEW IF EXISTS v1;
DROP VIEW IF EXISTS v0;
DROP TABLE IF EXISTS t4;
DROP TABLE IF EXISTS t3;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t0;
CREATE TABLE `t0` (
  `id` bigint NOT NULL,
  `k0` int NOT NULL,
  `k1` int NOT NULL,
  `k2` varchar(64) NOT NULL,
  `k3` varchar(64) NOT NULL,
  `p0` double NOT NULL,
  `p1` bigint NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_k1_3` (`k1`),
  KEY `idx_k3_10` (`k3`),
  KEY `idx_k0_11` (`k0`),
  KEY `idx_p1_26` (`p1`),
  KEY `idx_id_27` (`id`),
  KEY `idx_p0_31` (`p0`),
  KEY `idx_k2_32` (`k2`),
  KEY `idx_k2_k1_36` (`k2`,`k1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `t1` (
  `id` bigint NOT NULL,
  `k0` int NOT NULL,
  `d0` varchar(64) NOT NULL,
  `d1` varchar(64) NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_d0_0` (`d0`),
  KEY `idx_id_5` (`id`),
  KEY `idx_k0_9` (`k0`),
  KEY `idx_d1_20` (`d1`),
  KEY `idx_d0_d1_k0_28` (`d0`,`d1`,`k0`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `t2` (
  `id` bigint NOT NULL,
  `k1` int NOT NULL,
  `k0` int NOT NULL,
  `d0` float NOT NULL,
  `d1` float NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_id_7` (`id`),
  KEY `idx_k1_d1_k0_29` (`k1`,`d1`,`k0`),
  KEY `idx_k1_30` (`k1`),
  KEY `idx_d0_33` (`d0`),
  KEY `idx_k0_34` (`k0`),
  KEY `idx_d0_k0_35` (`d0`,`k0`),
  KEY `idx_d1_35` (`d1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `t3` (
  `id` bigint NOT NULL,
  `k2` varchar(64) NOT NULL,
  `k0` int NOT NULL,
  `d0` decimal(12,2) NOT NULL,
  `d1` date NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_id_12` (`id`),
  KEY `idx_d1_16` (`d1`),
  KEY `idx_d0_21` (`d0`),
  KEY `idx_k2_25` (`k2`),
  KEY `idx_k0_29` (`k0`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `t4` (
  `id` bigint NOT NULL,
  `k3` varchar(64) NOT NULL,
  `k0` int NOT NULL,
  `d0` date NOT NULL,
  `d1` bigint NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_k0_k3_d0_1` (`k0`,`k3`,`d0`),
  KEY `idx_id_1` (`id`),
  KEY `idx_d0_4` (`d0`),
  KEY `idx_k3_6` (`k3`),
  KEY `idx_d1_18` (`d1`),
  KEY `idx_k0_22` (`k0`),
  KEY `idx_d1_k3_d0_33` (`d1`,`k3`,`d0`),
  KEY `idx_d1_k3_36` (`d1`,`k3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v0` (`c0`, `c1`) AS SELECT DISTINCT (`t4`.`k0`+`t2`.`d1`) AS `c0`,(`t0`.`p0`+`t0`.`k1`) AS `c1` FROM (`t0` LEFT JOIN `t2` ON (`t0`.`k0`=`t2`.`k0`)) RIGHT JOIN `t4` ON (`t0`.`k0`=`t4`.`k0`) WHERE NOT EXISTS (SELECT COUNT(1) AS `cnt` FROM `t1` WHERE (`t1`.`k0`=`t0`.`k0`)) ORDER BY (`t0`.`p0`+`t0`.`k1`) DESC;

CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v1` (`cnt`, `sum1`) AS SELECT COUNT(1) AS `cnt`,SUM(`t3`.`d0`) AS `sum1` FROM ((((`t4` RIGHT JOIN `v0` ON (1=0)) LEFT JOIN `t1` ON (`t4`.`k0`=`t1`.`k0`)) LEFT JOIN `t0` ON (`t4`.`k0`=`t0`.`k0`)) RIGHT JOIN `t2` ON (`t0`.`k0`=`t2`.`k0`)) RIGHT JOIN `t3` ON (`t0`.`k0`=`t3`.`k0`) WHERE NOT (`t4`.`k0` IN (40)) ORDER BY COUNT(1);

CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v2` (`cnt`, `sum1`) AS SELECT COUNT(1) AS `cnt`,SUM(`t3`.`d0`) AS `sum1` FROM (((`t0` RIGHT JOIN `t4` ON (`t0`.`k0`=`t4`.`k0`)) RIGHT JOIN `t3` ON (`t0`.`k0`=`t3`.`k0`)) JOIN `t2` ON (`t0`.`k0`=`t2`.`k0`)) JOIN `t1` ON (`t0`.`k0`=`t1`.`k0`) WHERE (`t0`.`k0`<`t4`.`k0`);

CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v3` (`cnt`, `sum1`) AS SELECT DISTINCT COUNT(1) AS `cnt`,SUM(`t3`.`d0`) AS `sum1` FROM ((`t0` LEFT JOIN `t4` ON (`t0`.`k0`=`t4`.`k0`)) RIGHT JOIN `t3` ON (`t0`.`k0`=`t3`.`k0`)) JOIN `t2` ON (`t0`.`k0`=`t2`.`k0`) WHERE EXISTS (SELECT COUNT(1) AS `cnt` FROM `t0` WHERE (`t0`.`k2`=`t0`.`k2`)) ORDER BY COUNT(1);

CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `v4` (`cnt`, `sum1`) AS SELECT COUNT(1) AS `cnt`,SUM(`t3`.`d0`) AS `sum1` FROM (((`t0` JOIN `t4` ON (`t0`.`k0`=`t4`.`k0`)) JOIN `t3` ON (`t0`.`k0`=`t3`.`k0`)) JOIN `t2` ON (`t0`.`k0`=`t2`.`k0`)) LEFT JOIN `t1` ON (`t0`.`k0`=`t1`.`k0`) WHERE ((`t4`.`k0`>`t1`.`k0`) OR NOT (`t4`.`k0` IN (85,46)));

SET FOREIGN_KEY_CHECKS=1;

```

</details>

2) Load data
<details>
<summary>inserts.sql</summary>

```sql
INSERT INTO `t0` (`id`, `k0`, `k1`, `k2`, `k3`, `p0`, `p1`) VALUES (1, -9, -27, 's289', 's527', 65.61, 226), (2, -9, -58, 's777', 's140', 27.08, 410), (3, 13, -58, 's29', 's922', 18.55, 397), (4, -14, 91, 's679', 's712', 83.21, 689), (5, 27, -54, 's125', 's175', 71.48, 487), (6, -14, -58, 's495', 's175', 65.91, 74), (7, 54, -32, 's679', 's922', 55.67, 945), (8, -14, -27, 's378', 's175', 23.44, 370), (9, -14, 37, 's29', 's712', 84.03, 483), (10, 27, -32, 's58', 's712', 52.16, 830), (11, -9, 37, 's215', 's935', 86.02, 245), (12, -9, -52, 's289', 's922', 96.35, 283), (13, 0, -32, 's289', 's922', 33.95, 688), (14, 13, 64, 's29', 's140', 13.58, 193), (15, -14, -27, 's594', 's175', 77.31, 843), (16, 13, 91, 's679', 's922', 60.03, 628), (17, 54, -52, 's29', 's935', 0.06, 228), (18, -81, 79, 's29', 's175', 84.01, 829), (19, 73, -54, 's58', 's935', 61.11, 862), (20, -81, 37, 's378', 's922', 19.22, 521), (21, 54, 91, 's29', 's140', 75.92, 604), (22, 0, 91, 's777', 's846', 93.46, 140), (23, -4, 91, 's495', 's935', 39.82, 876), (24, -81, 37, 's378', 's846', 79.69, 147), (25, -4, 79, 's378', 's846', 88.49, 408), (26, -38, 91, 's58', 's846', 61.98, 195), (27, -9, -54, 's215', 's140', 25.91, 585), (28, -9, -58, 's125', 's712', 19.29, 967), (29, -38, -27, 's495', 's911', 72.43, 259), (30, 54, 91, 's378', 's224', 42.37, 193), (31, -9, -54, 's777', 's712', 84.14, 651), (32, -4, -27, 's289', 's527', 81.66, 905), (33, -14, 91, 's215', 's140', 17.72, 593), (34, -14, -58, 's215', 's140', 48.18, 757), (35, 0, 78, 's495', 's612', 89.19, 352), (36, -9, 37, 's125', 's911', 15.12, 175), (37, -4, -58, 's125', 's612', 20.86, 636), (38, 0, -32, 's289', 's224', 14.69, 62), (39, -9, 79, 's378', 's922', 45.09, 251), (40, 54, -27, 's594', 's612', 30.83, 835), (41, 73, 37, 's29', 's846', 30.49, 20), (42, -38, -32, 's777', 's140', 10.94, 553), (43, -4, 64, 's289', 's935', 26.66, 510), (44, 73, 37, 's777', 's935', 44.43, 44), (45, -14, 91, 's125', 's922', 73.67, 291), (46, -9, -52, 's777', 's140', 73.97, 324), (47, 0, -32, 's289', 's911', 99.14, 342), (48, -4, -52, 's679', 's935', 69.31, 66), (49, -38, -52, 's495', 's911', 90.82, 695), (50, 73, -54, 's495', 's612', 52.85, 425);
INSERT INTO `t0` (`id`, `k0`, `k1`, `k2`, `k3`, `p0`, `p1`) VALUES (51, -38, 79, 's679', 's846', 44.51, 345), (52, 13, -54, 's378', 's224', 24.11, 291), (53, -4, 91, 's594', 's846', 54.83, 639), (54, -14, -27, 's594', 's911', 35.66, 225), (55, -38, -32, 's594', 's175', 88.21, 747), (56, -38, -54, 's289', 's612', 24.24, 585), (57, -9, 78, 's679', 's140', 28.78, 522), (58, -81, -58, 's215', 's224', 28.87, 841), (59, -4, -27, 's215', 's846', 43.16, 509), (60, 0, -54, 's495', 's712', 19.62, 680), (61, 13, -54, 's679', 's140', 81.05, 144), (62, 27, -32, 's215', 's224', 52.72, 3), (63, -38, 91, 's679', 's911', 51, 795), (64, -4, -54, 's125', 's935', 0.99, 780), (65, -14, -58, 's215', 's911', 62.31, 109), (66, 0, 37, 's679', 's224', 87.66, 326), (67, 0, 91, 's679', 's935', 99.13, 981), (68, -9, -27, 's679', 's527', 44.97, 819), (69, 27, -52, 's29', 's527', 64.03, 714), (70, 0, -52, 's125', 's712', 77.01, 78), (71, -14, -52, 's29', 's612', 48.55, 508), (72, -4, -52, 's125', 's935', 48.06, 483), (73, -14, -27, 's215', 's175', 98.5, 369), (74, -81, 64, 's29', 's175', 76.78, 231), (75, 13, -32, 's495', 's175', 45.42, 533), (76, 54, -32, 's777', 's527', 31.71, 42), (77, 13, 91, 's58', 's140', 44.97, 775), (78, -38, -58, 's215', 's712', 26.16, 908), (79, 27, -52, 's215', 's140', 47.09, 875), (80, -14, 79, 's495', 's712', 19.44, 7);
INSERT INTO `t1` (`id`, `k0`, `d0`, `d1`) VALUES (6, 0, 's379', 's160'), (8, 73, 's75', 's142'), (1, -9, 's765', 's91'), (3, -14, 's395', 's547'), (7, -81, 's150', 's61'), (9, -4, 's760', 's821'), (10, -38, 's678', 's336'), (2, 13, 's224', 's3'), (4, 27, 's908', 's594'), (5, 54, 's928', 's377');
INSERT INTO `t2` (`id`, `k1`, `k0`, `d0`, `d1`) VALUES (4, -54, -38, 64.32, 63.41), (7, -52, -4, 69.61, 27.66), (8, 64, -81, 24.79, 15.65), (9, 79, 13, 3.23, 96.18), (10, 78, -81, 10.41, 10.81), (5, -32, -81, 59.7, 3.91), (6, 37, -38, 7.68, 71.71), (1, -27, 0, 47.32, 21.09), (2, -58, 54, 52.65, 80.37), (3, 91, -38, 26.1, 52.01);
INSERT INTO `t3` (`id`, `k2`, `k0`, `d0`, `d1`) VALUES (1, 's289', -81, 42.01, '2024-08-07'), (3, 's29', 13, 87.17, '2024-11-10'), (7, 's378', -14, 30.2, '2024-01-22'), (10, 's594', -4, 81.94, '2024-10-16'), (2, 's777', 0, 44.24, '2024-04-19'), (4, 's679', 0, 4.38, '2024-01-07'), (5, 's125', 0, 12.67, '2024-08-17'), (6, 's495', 27, 20.09, '2024-05-07'), (8, 's58', -4, 93.8, '2024-02-14'), (9, 's215', 54, 35.8, '2024-02-22');
INSERT INTO `t4` (`id`, `k3`, `k0`, `d0`, `d1`) VALUES (3, 's922', 73, '2024-02-07', 881), (4, 's712', 54, '2024-03-21', 287), (5, 's175', 73, '2024-10-16', 439), (7, 's846', -81, '2024-03-18', 625), (9, 's224', -4, '2024-08-06', 396), (10, 's612', 27, '2024-09-03', 427), (1, 's527', -81, '2024-10-22', 678), (2, 's140', -81, '2024-06-18', 67), (6, 's935', -81, '2024-09-13', 76), (8, 's911', 73, '2024-11-17', 812);

```

</details>

3) Run Query A and Query B through the signature wrapper and compare checksums.

### TiDB version

```
Release Version: v9.0.0-beta.2.pre-1157-gfb1a575b45
Edition: Community
Git Commit Hash: fb1a575b455365a37660540f9c5ea652cc9c44ee
Git Branch: HEAD
UTC Build Time: 2026-01-30 11:51:58
GoVersion: go1.25.6
Store: tikv
Kernel Type: Classic
```

### EXPLAIN (Query A)
<details>
<summary>expected_explain</summary>

```
Projection_26	1.00	root		Column#37, cast(Column#38, decimal(22,0) BINARY)->Column#39
└─StreamAgg_32	1.00	root		funcs:count(1)->Column#37, funcs:bit_xor(Column#56)->Column#38
  └─Projection_146	13.00	root		crc32(concat_ws(#, cast(Column#32, var_string(9)), cast(shiro_fuzz.t0.p1, var_string(20)), Column#33))->Column#56
    └─Projection_136	13.00	root		85.11->Column#32, shiro_fuzz.t0.p1, 2024-01-02 12:28:00->Column#33
      └─Projection_144	13.00	root		shiro_fuzz.t0.p1
        └─TopN_140	13.00	root		Column#55:desc, shiro_fuzz.t1.d0:desc, offset:0, count:13
          └─Projection_145	16.25	root		shiro_fuzz.t0.p1, shiro_fuzz.t1.d0, shiro_fuzz.t3.d0, shiro_fuzz.t2.k1, minus(shiro_fuzz.t3.d0, cast(shiro_fuzz.t2.k1, decimal(10,0) BINARY))->Column#55
            └─HashJoin_48	16.25	root		left outer join, left side:Projection_142, equal:[eq(shiro_fuzz.t0.k0, shiro_fuzz.t4.k0)]
              ├─IndexReader_131(Build)	10.00	root		index:IndexFullScan_130
              │ └─IndexFullScan_130	10.00	cop[tikv]	table:t4, index:idx_k0_22(k0)	keep order:false
              └─Projection_142(Probe)	13.00	root		shiro_fuzz.t0.k0, shiro_fuzz.t0.p1, shiro_fuzz.t1.d0, shiro_fuzz.t3.d0, shiro_fuzz.t2.k1
                └─TopN_52	13.00	root		Column#54:desc, shiro_fuzz.t1.d0:desc, offset:0, count:13
                  └─Projection_143	80.00	root		shiro_fuzz.t0.k0, shiro_fuzz.t0.p1, shiro_fuzz.t1.d0, shiro_fuzz.t3.d0, shiro_fuzz.t2.k1, minus(shiro_fuzz.t3.d0, cast(shiro_fuzz.t2.k1, decimal(10,0) BINARY))->Column#54
                    └─HashJoin_64	80.00	root		left outer join, left side:HashJoin_66, equal:[eq(shiro_fuzz.t0.k0, shiro_fuzz.t2.k0)]
                      ├─IndexReader_123(Build)	10.00	root		index:IndexFullScan_122
                      │ └─IndexFullScan_122	10.00	cop[tikv]	table:t2, index:idx_k1_d1_k0_29(k1, d1, k0)	keep order:false
                      └─HashJoin_66(Probe)	64.00	root		inner join, equal:[eq(shiro_fuzz.t0.k0, shiro_fuzz.t3.k0) nulleq(shiro_fuzz.t0.k0, shiro_fuzz.t3.k0)]
                        ├─TableReader_116(Build)	8.00	root		data:Selection_115
                        │ └─Selection_115	8.00	cop[tikv]		nulleq(shiro_fuzz.t3.k0, shiro_fuzz.t3.k0)
                        │   └─TableFullScan_114	10.00	cop[tikv]	table:t3	keep order:false
                        └─Projection_68(Probe)	64.00	root		shiro_fuzz.t0.k0, shiro_fuzz.t0.p1, shiro_fuzz.t1.d0
                          └─HashJoin_85	64.00	root		inner join, equal:[eq(shiro_fuzz.t1.k0, shiro_fuzz.t0.k0)]
                            ├─TableReader_98(Build)	8.00	root		data:Selection_97
                            │ └─Selection_97	8.00	cop[tikv]		nulleq(shiro_fuzz.t1.k0, shiro_fuzz.t1.k0)
                            │   └─TableFullScan_96	10.00	cop[tikv]	table:t1	keep order:false
                            └─TableReader_112(Probe)	64.00	root		data:Selection_111
                              └─Selection_111	64.00	cop[tikv]		nulleq(shiro_fuzz.t0.k0, shiro_fuzz.t0.k0)
                                └─TableFullScan_110	80.00	cop[tikv]	table:t0	keep order:false

```

</details>

### EXPLAIN (Query B)
<details>
<summary>actual_explain</summary>

```
Projection_24	1.00	root		Column#37, cast(Column#38, decimal(22,0) BINARY)->Column#39
└─StreamAgg_30	1.00	root		funcs:count(1)->Column#37, funcs:bit_xor(Column#55)->Column#38
  └─Projection_137	13.00	root		crc32(concat_ws(#, cast(Column#32, var_string(9)), cast(shiro_fuzz.t0.p1, var_string(20)), Column#33))->Column#55
    └─Projection_127	13.00	root		85.11->Column#32, shiro_fuzz.t0.p1, 2024-01-02 12:28:00->Column#33
      └─Projection_135	13.00	root		shiro_fuzz.t0.p1
        └─TopN_131	13.00	root		Column#54:desc, shiro_fuzz.t1.d0:desc, offset:0, count:13
          └─Projection_136	16.25	root		shiro_fuzz.t0.p1, shiro_fuzz.t1.d0, shiro_fuzz.t3.d0, shiro_fuzz.t2.k1, minus(shiro_fuzz.t3.d0, cast(shiro_fuzz.t2.k1, decimal(10,0) BINARY))->Column#54
            └─HashJoin_46	16.25	root		left outer join, left side:Projection_133, equal:[eq(shiro_fuzz.t0.k0, shiro_fuzz.t4.k0)]
              ├─IndexReader_122(Build)	10.00	root		index:IndexFullScan_121
              │ └─IndexFullScan_121	10.00	cop[tikv]	table:t4, index:idx_k0_22(k0)	keep order:false
              └─Projection_133(Probe)	13.00	root		shiro_fuzz.t0.k0, shiro_fuzz.t0.p1, shiro_fuzz.t1.d0, shiro_fuzz.t3.d0, shiro_fuzz.t2.k1
                └─TopN_50	13.00	root		Column#53:desc, shiro_fuzz.t1.d0:desc, offset:0, count:13
                  └─Projection_134	640.00	root		shiro_fuzz.t0.k0, shiro_fuzz.t0.p1, shiro_fuzz.t1.d0, shiro_fuzz.t3.d0, shiro_fuzz.t2.k1, minus(shiro_fuzz.t3.d0, cast(shiro_fuzz.t2.k1, decimal(10,0) BINARY))->Column#53
                    └─HashJoin_59	640.00	root		CARTESIAN left outer join, left side:HashJoin_61, other cond:not(not(eq(shiro_fuzz.t0.k0, shiro_fuzz.t2.k0)))
                      ├─IndexReader_115(Build)	10.00	root		index:IndexFullScan_114
                      │ └─IndexFullScan_114	10.00	cop[tikv]	table:t2, index:idx_k1_d1_k0_29(k1, d1, k0)	keep order:false
                      └─HashJoin_61(Probe)	64.00	root		inner join, equal:[eq(shiro_fuzz.t0.k0, shiro_fuzz.t3.k0) nulleq(shiro_fuzz.t0.k0, shiro_fuzz.t3.k0)]
                        ├─TableReader_111(Build)	8.00	root		data:Selection_110
                        │ └─Selection_110	8.00	cop[tikv]		nulleq(shiro_fuzz.t3.k0, shiro_fuzz.t3.k0)
                        │   └─TableFullScan_109	10.00	cop[tikv]	table:t3	keep order:false
                        └─Projection_63(Probe)	64.00	root		shiro_fuzz.t0.k0, shiro_fuzz.t0.p1, shiro_fuzz.t1.d0
                          └─HashJoin_80	64.00	root		inner join, equal:[eq(shiro_fuzz.t1.k0, shiro_fuzz.t0.k0)]
                            ├─TableReader_93(Build)	8.00	root		data:Selection_92
                            │ └─Selection_92	8.00	cop[tikv]		nulleq(shiro_fuzz.t1.k0, shiro_fuzz.t1.k0)
                            │   └─TableFullScan_91	10.00	cop[tikv]	table:t1	keep order:false
                            └─TableReader_107(Probe)	64.00	root		data:Selection_106
                              └─Selection_106	64.00	cop[tikv]		nulleq(shiro_fuzz.t0.k0, shiro_fuzz.t0.k0)
                                └─TableFullScan_105	80.00	cop[tikv]	table:t0	keep order:false

```

</details>

### Additional info

- Oracle: EET (Equivalent Expression Transformation), rewrite: `double_not`
- Case directory: `case_0001_019c129f-2d96-7e5b-b946-16ac38bdca98`
- Seed: `1769838802340518000`

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65937

Problem Summary:
- Double NOT in outer join ON conditions stayed as other cond and could lead to cartesian-like joins.

### What changed and how does it work?
- Normalize outer join OtherConditions by applying PushDownNot when UnaryNot is present.
- Add predicate pushdown cases for double NOT left/right/semi joins and record plan + result.
- Add integration test case in planner/core/issuetest to validate checksum parity.
- Document optimizer/test experience in docs and update skills guidance.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/util.go [hunk 1]
```diff
@@ -1069,6 +1069,16 @@ func pushNotAcrossExpr(ctx BuildContext, expr Expression, not bool) (_ Expressio
 	if f, ok := expr.(*ScalarFunction); ok {
 		switch f.FuncName.L {
 		case ast.UnaryNot:
+			if childNot, ok := f.GetArgs()[0].(*ScalarFunction); ok && childNot.FuncName.L == ast.UnaryNot {
```
Comment (AilinKid) [inline pkg/expression/util.go]: this part is not necessary to change, the old logic here can cover

Comment (hawkingrei) [reply pkg/expression/util.go]: Great, I have removed this part.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 2]
```diff
@@ -265,6 +268,30 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	if len(p.OtherConditions) == 0 {
+		return
+	}
+	// Outer join ON conditions are not simplified through predicate pushdown.
+	// Normalize only double NOT here to avoid cartesian joins caused by other conditions.
+	if !containsUnaryNot(p.OtherConditions) {
+		return
+	}
+	exprCtx := p.SCtx().GetExprCtx()
+	for i := range p.OtherConditions {
```
Comment (windtalker) [inline pkg/planner/core/operator/logicalop/logical_join.go:278]: Looks like if only one of `p.OtherConditions` contains unary not, all the expression in `p.OtherConditions` will call `expression.PushDownNot`, it seems not necessary to me.

Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go:278]: I have refactored it.
