### PR TITLE
br: resume task that only differs in RestoredTS

### LINKED ISSUE #61578: After br node oom and restart restore task, restore failed and prompt:'task with ID 1 already exists and is running'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
1. The br node with smaller CPU and memory starts a large data restore task, forcing the br oom
2. Expand the capacity of the br node and restart restore task

### 2. What did you expect to see? (Required)
restore success

### 3. What did you see instead (Required)
Restore failed! 
The task in `mysql.tidb_restore_registry` is still in running mode.

> mysql> select * from mysql.tidb_restore_registry;
> +----+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------+-------------+---------------------+----------------+---------+--------------+----------------------------+----------------------------+
> | id | filter_strings                                                                                                                                                                                                                                                                      | filter_hash                      | start_ts | restored_ts | upstream_cluster_id | with_sys_table | status  | cmd          | task_start_time            | last_heartbeat_time        |
> +----+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------+-------------+---------------------+----------------+---------+--------------+----------------------------+----------------------------+
> |  1 | *.*!__TiDB_BR_Temporary_*.*!mysql.*mysql.bind_infomysql.usermysql.dbmysql.tables_privmysql.columns_privmysql.global_privmysql.global_grantsmysql.default_rolesmysql.role_edges!sys.*!INFORMATION_SCHEMA.*!PERFORMANCE_SCHEMA.*!METRICS_SCHEMA.*!INSPECTION_SCHEMA.* | 2688546865cf9b7f4c35bebfdfc7e5e5 |        0 |           0 | 7506060340338442365 |              1 | running | Full Restore | 2025-06-09 03:23:34.652232 | 2025-06-09 03:23:34.660559 |
> +----+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------+-------------+---------------------+----------------+---------+--------------+----------------------------+----------------------------+

`[2025/06/09 03:33:28.025 +00:00] [ERROR] [main.go:38] ["br failed"] [error="task with ID 1 already exists and is running: [BR:Common:ErrInvalidArgument]invalid argument"] [errorVerbose="[BR:Common:ErrInvalidArgument]invalid argument\ntask with ID 1 already exists and is running\ngithub.com/pingcap/tidb/br/pkg/registry.(*Registry).ResumeOrCreateRegistration.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/registry/registration.go:233\ngithub.com/pingcap/tidb/br/pkg/registry.(*Registry).executeInTransaction\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/registry/registration.go:178\ngithub.com/pingcap/tidb/br/pkg/registry.(*Registry).ResumeOrCreateRegistration\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/registry/registration.go:210\ngithub.com/pingcap/tidb/br/pkg/task.RegisterRestoreIfNeeded\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/stream.go:2148\ngithub.com/pingcap/tidb/br/pkg/task.runSnapshotRestore\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/restore.go:1162\ngithub.com/pingcap/tidb/br/pkg/task.RunRestore\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/restore.go:938\nmain.runRestoreCommand\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/restore.go:75\nmain.newFullRestoreCommand.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/restore.go:181\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"] [stack="main.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/main.go:38\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"]`


### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
Release Version: v8.5.0-20250609-a850b6f
Edition: Community
Git Commit Hash: a850b6f2634ee51c32b2ab8623c78035186e1278
Git Branch: heads/refs/tags/v8.5.0-20250609-a850b6f
UTC Build Time: 2025-06-09 02:24:01
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #61578

Problem Summary:

### What changed and how does it work?

Increase the usability for the latest parallel restore feature
User often retry restore without specifying restoredTS, it will result in an error that might be confusing to user. Now we will auto detect such cases and potentially reuse task by doing following things:
1. if user specify a restoredTS, we will directly use that ts
2. if not, we will try to find the task that only differs in restoredTS in the registry.
2.1 if the task if pasued, use the restoreTS in this task and try to resume it (in transaction will make sure task has not changed)
2.2 if task is running, it could potentially be a orphan task, we wait for 5 minutes to see if its heartbeat changed, if not we pause it, use its restoreTS and goes to the normal flow of resuming it. If heartbeat changed, we directly go to the next step and will bail out because filter matches.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

File: br/pkg/registry/registration.go [hunk 1]
```diff
@@ -498,3 +540,171 @@ func (r *Registry) StopHeartbeatManager() {
 		log.Info("stopped heartbeat manager for restore task")
 	}
 }
+
+// CleanupStaleRunningTasks removes tasks that are marked as "running" but haven't sent heartbeats
+// within the stale threshold. It performs a double-check by waiting and verifying heartbeats haven't updated.
+func (r *Registry) CleanupStaleRunningTasks(ctx context.Context) error {
+	log.Info("starting cleanup of stale running tasks")
+
+	execCtx := r.se.GetSessionCtx().GetRestrictedSQLExecutor()
```
Comment (BornChanger) [inline br/pkg/registry/registration.go:571]: is it a standalone ctx? cc @Leavrth

File: br/pkg/registry/registration.go [hunk 2]
```diff
@@ -195,6 +226,17 @@ func (r *Registry) executeInTransaction(ctx context.Context, fn func(context.Con
 // ResumeOrCreateRegistration first looks for an existing registration with the given parameters.
 // If found and paused, it tries to resume it. Otherwise, it creates a new registration.
 func (r *Registry) ResumeOrCreateRegistration(ctx context.Context, info RegistrationInfo) (uint64, error) {
+	// check for tasks with same parameters except restoredTS (common PiTR auto-detection issue)
+	if err := r.checkForAutoRestoredTSConflict(ctx, info); err != nil {
+		return 0, err
+	}
+
+	// clean up stale tasks first
+	if err := r.CleanupStaleRunningTasks(ctx); err != nil {
```
Comment (BornChanger) [inline br/pkg/registry/registration.go]: can we make a seperated goroutine to clean up the stale task? otherwise, the main routine could be blocked to more than 5 minutes

File: br/pkg/registry/registration.go (hunk 1 above)
Comment (Tristan1900) [reply br/pkg/registry/registration.go:571]: it's the registry dedicated session

File: br/pkg/task/restore.go [hunk 3]
```diff
@@ -951,6 +956,7 @@ func RunRestore(c context.Context, g glue.Glue, cmdName string, cfg *RestoreConf
 	// unregister restore task
 	failpoint.Inject("fail-at-end-of-restore", func() {
 		log.Info("failpoint fail-at-end-of-restore injected, failing at the end of restore task")
+		log.Info("previous error", zap.Error(restoreErr))
```
Comment (3pointer) [inline br/pkg/task/restore.go]: maybe make these 2 logs in one line.

File: br/pkg/checkpoint/storage.go [hunk 4]
```diff
@@ -346,3 +346,47 @@ func dropCheckpointTables(
 	}
 	return nil
 }
+
+// RemoveAllCheckpointDataForRestoreID removes all table-based checkpoint data for a given restore ID
+// by dropping the entire checkpoint databases. Each restore task uses dedicated databases with the
+// restore ID as a suffix, so we can safely drop the entire database.
+func RemoveAllCheckpointDataForRestoreID(ctx context.Context, se glue.Session, restoreID uint64) error {
```
Comment (3pointer) [inline br/pkg/checkpoint/storage.go]: what's the usage of this function?

**Review by 3pointer — COMMENTED** [review]
rest LGTM

File: br/pkg/checkpoint/storage.go (hunk 4 above)
Comment (Tristan1900) [reply br/pkg/checkpoint/storage.go]: I thought it removed this method. good call.

File: br/pkg/registry/registration.go (hunk 2 above)
Comment (Tristan1900) [reply br/pkg/registry/registration.go]: discussed offline. This part of logic has been removed. However, the new resume logic also needs to block for 5 mins but that's necessary since it needs to decide whether to reuse the restore id or not.
