### PR TITLE
table: fix the issue that the default value for `BIT` column is wrong | tidb-test=pr/2424

### LINKED ISSUE #57301: The binary literal default value is not handled correctly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
func TestBitDefaultValue(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("create table t(a bit(32) default b'1100010001001110011000100100111')")
	tk.MustExec("insert into t values ()")
	tk.MustQuery("select hex(a) from t").Check(testkit.Rows("62273127"))
}
```

It's because `b'1100010001001110011000100100111'` is converted to `"b'1'"`, and then casted to `1`.

### 2. What did you expect to see? (Required)

The test passed

### 3. What did you see instead (Required)

The test failed

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.4.0-this-is-a-placeholder
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #57301, close https://github.com/pingcap/tidb/issues/57312

Problem Summary:

1. The `CREATE TABLE` statement didn't assert whether the default value for `BIT` is valid.
2. The default value for `BIT` column is casted multiple times and may cause unexpected behavior.

### What changed and how does it work?

1. Revert part of #21310
2. Validate the length of `BIT` default value.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by YangKeao** [comment]
/hold

I'm solving another issue #57312

File: pkg/executor/test/writetest/write_test.go [hunk 1]
```diff
@@ -248,7 +248,7 @@ func TestIssue18681(t *testing.T) {
 	}()
 	sc.SetTypeFlags(oldTypeFlags.WithIgnoreTruncateErr(true))
 	tests := []testCase{
-		{[]byte("true\tfalse\t0\t1\n"), []string{"1|0|0|1"}, "Records: 1  Deleted: 0  Skipped: 0  Warnings: 0"},
+		{[]byte("true\tfalse\t0\t1\tb'1'\tb'1'\n"), []string{"1|1|1|1|1100010001001110011000100100111|1"}, "Records: 1  Deleted: 0  Skipped: 0  Warnings: 5"},
```
Comment (YangKeao) [inline pkg/executor/test/writetest/write_test.go:251]: As I've tested, the `LOAD DATA` in MySQL (both 5.6 and 8.0) also doesn't convert `"false"` to `0`. I don't know why it's originally implemented (in https://github.com/pingcap/tidb/pull/21310) as this.

**Review by wjhuang2016 — APPROVED** [review]
