### PR TITLE
ddl, executor: handle original default value after changing column

### LINKED ISSUE #24951: Updating date  return an error after  conversion `timestamp` to `date`
## Bug Report

Please answer these questions before submitting your issue. Thanks!
TiDB need to `set set global tidb_enable_change_column_type = 1;`

### 1. Minimal reproduce step (Required)

```
drop table tbl_41;
create table tbl_41 (col timestamp default '1971-06-09' not null);
alter table tbl_41 modify column col date not null;
update tbl_41 set col = '2002-12-31';
```

### 2. What did you expect to see? (Required)
`Query OK, 0 rows affected (0.00 sec)`

### 3. What did you see instead (Required)
`ERROR 1292 (22007): Incorrect date value: '0000-00-00'`

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-2957-g4000975ad
Edition: Community
Git Commit Hash: 4000975ad1785fbc4c0e5175407e8486c0cef763
Git Branch: master
```

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close #24951, #25186, #25183 

Problem Summary

- Fix the issue of "Updating date returns an error after or during conversion `timestamp` to `date`".
- Make `TestChangingColOriginDefaultValue` meaningful.

### What is changed and how it works?

How it Works:

- Set the `OriginDefaultValue` back after finishing `changing column type`.
- Make `update stmt's` plan in `TestChangingColOriginDefaultValue` is `point get`.

### Check List 

Tests 

- Unit test

### Release note 

- Fix update date returning an error after or during conversion `timestamp` to `date`.

### CODE REVIEW

File: ddl/column_type_change_test.go [hunk 1]
```diff
@@ -1599,6 +1600,31 @@ func (s *testColumnTypeChangeSuite) TestColumnTypeChangeFromJsonToOthers(c *C) {
...
 }
 
+func (s *testColumnTypeChangeSuite) TestUpdateDataAfterChangeTimestampToDate(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	// Enable column change variable.
+	tk.Se.GetSessionVars().EnableChangeColumnType = true
+	defer func() {
+		tk.Se.GetSessionVars().EnableChangeColumnType = false
+	}()
```
Comment (tangenta) [inline ddl/column_type_change_test.go:1610]: We don't need to reset it because each test is run in a new testkit.

Comment (AilinKid) [reply ddl/column_type_change_test.go:1610]: +1

File: ddl/column.go [hunk 2]
```diff
@@ -1076,6 +1076,9 @@ func (w *worker) doModifyColumnTypeWithData(
 		changingColumnUniqueName := changingCol.Name
 		changingCol.Name = colName
 		changingCol.ChangeStateInfo = nil
+		if err = changingCol.SetOriginDefaultValue(nil); err != nil {
```
Comment (AilinKid) [inline ddl/column.go:1079]: great! should comment here? original default value is no longer used after CTC because all of it have been casted to real row.

File: ddl/column.go [hunk 3]
```diff
@@ -861,7 +861,7 @@ func (w *worker) onModifyColumn(d *ddlCtx, t *meta.Meta, job *model.Job) (ver in
 		// Since column type change is implemented as adding a new column then substituting the old one.
 		// Case exists when update-where statement fetch a NULL for not-null column without any default data,
 		// it will errors.
-		// So we set zero original default value here to prevent this error. besides, in insert & update records,
+		// So we set zero original default value here to prevent this error. Besides, in insert & update records,
```
Comment (AilinKid) [inline ddl/column.go:864]: For line 867, I think we should use this logic
```
prior 1: if new col has its default value, using it as the origin-default value.
prior 2: if old col has its origin-default value, use it as the origin-default value.
prior 3: use the zero value (partial logic in `generateOriginDefaultValue`) 
```

Comment (AilinKid) [reply ddl/column.go:864]: Otherwise, issue 24951's update statement if happens in write-only / write-reorg state, it may have the same error

Comment (zimulala) [reply ddl/column.go:864]: This logic after I told you, I've tried (TestChangingColOriginDefaultValueAfterAddCol) there will be no problem, so there is no change, do you have any repetition of the case?

Comment (zimulala) [reply ddl/column.go:864]: Well, it's probably the type of columns in the test that caused the problem

**Review by AilinKid — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
