### PR TITLE
executor: fix goroutine leak when reading cache table with tiflash storage is designated

### LINKED ISSUE #63329: Goroutine and memory leak with cached table and TiFlash replica
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
mysql> create table t1(a int, b int, c int);
Query OK, 0 rows affected (0.04 sec)

mysql> create table t2(x int, y int, z int);
Query OK, 0 rows affected (0.03 sec)

mysql> alter table t1 set tiflash replica 2;
Query OK, 0 rows affected (0.06 sec)

mysql> alter table t2 set tiflash replica 2;
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t1 values(1, 1, 1),(2,2,2);
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> insert into t2 values(1, 1, 1),(2,2,2);
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> alter table t1 cache;
Query OK, 0 rows affected (0.05 sec)

mysql> alter table t2 cache;
Query OK, 0 rows affected (0.05 sec)

mysql> explain select /*+ READ_FROM_STORAGE(tiflash[t1], tiflash[t2]) */ * from t1 join t2 on t1.a=t2.x;
+----------------------------------+---------+--------------+---------------+----------------------------------------------------------+
| id                               | estRows | task         | access object | operator info                                            |
+----------------------------------+---------+--------------+---------------+----------------------------------------------------------+
| HashJoin_10                      | 2.50    | root         |               | inner join, equal:[eq(test.t1.a, test.t2.x)]             |
| ├─UnionScan_17(Build)            | 2.00    | root         |               | not(isnull(test.t2.x))                                   |
| │ └─TableReader_21               | 2.00    | root         |               | MppVersion: 2, data:ExchangeSender_20                    |
| │   └─ExchangeSender_20          | 2.00    | mpp[tiflash] |               | ExchangeType: PassThrough                                |
| │     └─Selection_19             | 2.00    | mpp[tiflash] |               | not(isnull(test.t2.x))                                   |
| │       └─TableFullScan_18       | 2.00    | mpp[tiflash] | table:t2      | pushed down filter:empty, keep order:false, stats:pseudo |
| └─UnionScan_12(Probe)            | 2.00    | root         |               | not(isnull(test.t1.a))                                   |
|   └─TableReader_16               | 2.00    | root         |               | MppVersion: 2, data:ExchangeSender_15                    |
|     └─ExchangeSender_15          | 2.00    | mpp[tiflash] |               | ExchangeType: PassThrough                                |
|       └─Selection_14             | 2.00    | mpp[tiflash] |               | not(isnull(test.t1.a))                                   |
|         └─TableFullScan_13       | 2.00    | mpp[tiflash] | table:t1      | pushed down filter:empty, keep order:false, stats:pseudo |
+----------------------------------+---------+--------------+---------------+----------------------------------------------------------+
11 rows in set (0.00 sec)

// Run 100 times
mysql> select /*+ READ_FROM_STORAGE(tiflash[t1], tiflash[t2]) */ * from t1 join t2 on t1.a=t2.x;
+------+------+------+------+------+------+
| a    | b    | c    | x    | y    | z    |
+------+------+------+------+------+------+
|    1 |    1 |    1 |    1 |    1 |    1 |
|    2 |    2 |    2 |    2 |    2 |    2 |
+------+------+------+------+------+------+
2 rows in set (0.01 sec)
```

### 2. What did you expect to see? (Required)
The goroutine and memory usage can eventually recover.

### 3. What did you see instead (Required)
The goroutine and memory usage keep growing during queries and never recover.

Image

Image
From goroutine profiling, we can see that many goroutines are related to this query.

```
goroutine profile: total 978
196 @ 0x100dc6f88 0x100da0f9c 0x1014a69dc 0x100dd0814
# labels: {"plan_digest":"823559ee093a61b59d499fcd9f8315d6552cf1c042f7c8e76bc2d1b900dd19bb", "sql_digest":"11546935e66009544858688a5035c3232046e0143a814d78f3a74f811360d459"}
#	0x1014a69db	google.golang.org/grpc.newClientStreamWithParams.func4+0x8b	/Users/pingcap/go/pkg/mod/google.golang.org/grpc@v1.63.2/stream.go:392

196 @ 0x100dc6f88 0x100da0f9c 0x103f82854 0x103f85064 0x103f839b8 0x103f82f48 0x103f8261c 0x100dd0814
# labels: {"plan_digest":"823559ee093a61b59d499fcd9f8315d6552cf1c042f7c8e76bc2d1b900dd19bb", "sql_digest":"11546935e66009544858688a5035c3232046e0143a814d78f3a74f811360d459"}
#	0x103f82853	github.com/pingcap/tidb/pkg/executor/internal/mpp.(*localMppCoordinator).sendToRespCh+0x103		/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-w2tsl-build-binaries/source/tidb/pkg/executor/internal/mpp/local_mpp_coordinator.go:406
#	0x103f85063	github.com/pingcap/tidb/pkg/executor/internal/mpp.(*localMppCoordinator).handleMPPStreamResponse+0x713	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-w2tsl-build-binaries/source/tidb/pkg/executor/internal/mpp/local_mpp_coordinator.go:672
#	0x103f839b7	github.com/pingcap/tidb/pkg/executor/internal/mpp.(*localMppCoordinator).receiveResults+0x117		/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-w2tsl-build-binaries/source/tidb/pkg/executor/internal/mpp/local_mpp_coordinator.go:518
#	0x103f82f47	github.com/pingcap/tidb/pkg/executor/internal/mpp.(*localMppCoordinator).handleDispatchReq+0x417	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-w2tsl-build-binaries/source/tidb/pkg/executor/internal/mpp/local_mpp_coordinator.go:471
#	0x103f8261b	github.com/pingcap/tidb/pkg/executor/internal/mpp.(*localMppCoordinator).dispatchAll.func2+0x5b		/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-w2tsl-build-binaries/source/tidb/pkg/executor/internal/mpp/local_mpp_coordinator.go:376

196 @ 0x100dc6f88 0x100da1fd8 0x100da1fb5 0x100dc8b1c 0x100de5364 0x103f824fc 0x100dd0814
# labels: {"plan_digest":"823559ee093a61b59d499fcd9f8315d6552cf1c042f7c8e76bc2d1b900dd19bb", "sql_digest":"11546935e66009544858688a5035c3232046e0143a814d78f3a74f811360d459"}
#	0x100dc8b1b	sync.runtime_Semacquire+0x2b									/Users/pingcap/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/runtime/sema.go:71
#	0x100de5363	sync.(*WaitGroup).Wait+0x73									/Users/pingcap/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/sync/waitgroup.go:118
#	0x103f824fb	github.com/pingcap/tidb/pkg/executor/internal/mpp.(*localMppCoordinator).dispatchAll+0x2fb	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-w2tsl-build-binaries/source/tidb/pkg/executor/internal/mpp/local_mpp_coordinator.go:379

30 @ 0x100dc6f88 0x100da0f9c 0x1013b4c04 0x100dd0814
#	0x1013b4c03	google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run+0xc3	/Users/pingcap/go/pkg/mod/google.golang.org/grpc@v1.63.2/internal/grpcsync/callback_serializer.go:76

24 @ 0x100dc6f88 0x100da0f9c 0x1013b4c04 0x100dd0814
# labels: {"plan_digest":"823559ee093a61b59d499fcd9f8315d6552cf1c042f7c8e76bc2d1b900dd19bb", "sql_digest":"11546935e66009544858688a5035c3232046e0143a814d78f3a74f811360d459"}
#	0x1013b4c03	google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run+0xc3	/Users/pingcap/go/pkg/mod/google.golang.org/grpc@v1.63.2/internal/grpcsync/callback_serializer.go:76
```

### 4. What is your TiDB version? (Required)
v8.5.2

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #63329

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that goroutine will be leaked when reading cache table with tiflash storage is designated
```

### CODE REVIEW

File: pkg/executor/mpp_gather.go [hunk 1]
```diff
@@ -129,6 +128,9 @@ func (e *MPPGather) Next(ctx context.Context, chk *chunk.Chunk) error {
 // Close and release the used resources.
 func (e *MPPGather) Close() error {
 	if e.dummy {
+		if e.respIter != nil {
+			return errors.Trace(errors.New("e.respIter != nil when e.dummy is set"))
```
Comment (windtalker) [inline pkg/executor/mpp_gather.go:133]: even if return error, you should still close the `e.respIter`?

Comment (xzhangxian1008) [reply pkg/executor/mpp_gather.go:133]: > even if return error, you should still close the `e.respIter`?

okk, I will add it.
