### PR TITLE
planner: trigger stats load on a column in determinate mode to make sure analyze row count is available

### LINKED ISSUE #48257: TableFullScan uses pseudo stats in determinate mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Create a table without indexes, and insert some rows of data. Wait a minute and analyze the table.

```
mysql> show stats_meta;
+---------+------------+----------------+---------------------+--------------+-----------+
| Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
+---------+------------+----------------+---------------------+--------------+-----------+
| test    | test       |                | 2023-11-03 10:07:27 |            0 |      2048 |
+---------+------------+----------------+---------------------+--------------+-----------+
1 row in set (0.00 sec)

mysql> explain select * from test;
+-----------------------+---------+-----------+---------------+----------------------+
| id                    | estRows | task      | access object | operator info        |
+-----------------------+---------+-----------+---------------+----------------------+
| TableReader_5         | 2048.00 | root      |               | data:TableFullScan_4 |
| └─TableFullScan_4     | 2048.00 | cop[tikv] | table:test    | keep order:false     |
+-----------------------+---------+-----------+---------------+----------------------+
2 rows in set (0.00 sec)

mysql> set tidb_opt_objective='determinate';
Query OK, 0 rows affected (0.00 sec)

mysql> explain select * from test;
+-----------------------+----------+-----------+---------------+--------------------------------+
| id                    | estRows  | task      | access object | operator info                  |
+-----------------------+----------+-----------+---------------+--------------------------------+
| TableReader_5         | 10000.00 | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4     | 10000.00 | cop[tikv] | table:test    | keep order:false, stats:pseudo |
+-----------------------+----------+-----------+---------------+--------------------------------+
2 rows in set (0.00 sec)
```
### 2. What did you expect to see? (Required)

In both modes, the TableFullScan has the correct row count.

### 3. What did you see instead (Required)

In determinate mode, the TableFullScan has a row count of 10000.

### 4. What is your TiDB version? (Required)

v7.6.0-alpha-nightly-20231101

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close  #48257

Problem Summary:

Currently, if there are no predicates on one table, no stats loading will be triggered.
But in the determinate mode, if there are no full-loaded stats on this table, we are unable to get the "analyze row count".
This won't be a problem in most times, but it may cause a problem if it's joined with other tables.

### What changed and how does it work?

In the determinate mode, if:
1. no sync stats loading is triggered on a table, and
2. there are no full-loaded stats on this table

then we arbitrarily choose one column to trigger stats loading.

This is implemented in `collectPredicateColumnsPoint` while effective in both sync/async load modes.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/plan_stats.go [hunk 1]
```diff
@@ -39,24 +40,83 @@ func (collectPredicateColumnsPoint) optimize(_ context.Context, plan LogicalPlan
...
+			if colStats := tblStats.Columns[col.ID]; colStats != nil {
+				// Choose the first column we meet to trigger stats loading.
+				if colToTriggerLoad == nil && colStats.IsStatsInitialized() {
+					colToTriggerLoad = &model.TableItemID{TableID: int64(physicalTblID), ID: col.ID, IsIndex: false}
+				}
+				// If any stats are already full loaded, we don't need to trigger stats loading on this table.
+				if colStats.IsFullLoad() {
+					colToTriggerLoad = nil
+					break
+				}
```
Comment (winoros) [inline pkg/planner/core/plan_stats.go:95]: Do we need to check it here since we have the check `physTblIDsWithNeededCols.Has(physicalTblID)`?

File: pkg/planner/core/collect_column_stats_usage.go [hunk 2]
```diff
@@ -159,6 +167,10 @@ func (c *columnStatsUsageCollector) collectPredicateColumnsForUnionAll(p *Logica
 }
 
 func (c *columnStatsUsageCollector) addHistNeededColumns(ds *DataSource) {
+	c.visitedPhysTblIDs.Insert(int(ds.physicalTableID))
```
Comment (winoros) [inline pkg/planner/core/collect_column_stats_usage.go:170]: If we insert the id into the map after the line178 and check `if len(columns) == 0 then add it to the map`. We don't need the struct `physTblIDsWithNeededCols` in the `plan_stats.go`'s `optimize()`?

Comment (time-and-fate) [reply pkg/planner/core/collect_column_stats_usage.go:170]: Yes.
But personally, I tend to output information for possibly more general usage and keep the "determinate mode" specific logic out of this collector.

File: pkg/planner/core/plan_stats.go (hunk 1 above)
Comment (time-and-fate) [reply pkg/planner/core/plan_stats.go:95]: They are different.
`physTblIDsWithNeededCols.Has(physicalTblID)` means we will trigger sync loading on some columns for this table now, no matter if there are already some usable stats.
`colStats.IsFullLoad()` means we already have some column stats that can be used and also implies that these stats are not needed by the predicates.

**Review by winoros — APPROVED** [review]
