### PR TITLE
executor: fix update ignore still report dup-key error in statement retry

### LINKED ISSUE #54489: The `update ignore` may still report dup-key error when retry
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This unit test fails

```golang
func TestUpdateRowRetryAndThenDupKey(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewSteppedTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("create table t(id int primary key, u int unique)")
	tk.MustExec("insert into t values(1, 1)")

	// session 1 update u=2 for id=1 and halt before executor first runs.
	tk.SetBreakPoints(sessiontxn.BreakPointBeforeExecutorFirstRun)
	tk.SteppedMustExec("update ignore t set u = 2 where id = 1").
		ExpectStopOnBreakPoint(sessiontxn.BreakPointBeforeExecutorFirstRun)

	// session 2  insert a new row (2, 2) to make the unique key conflict.
	tk2 := testkit.NewTestKit(t, store)
	tk2.MustExec("use test")
	tk2.MustExec("insert into t values(2, 2)")

	// Continue the execution of session1, it should meet an optimistic conflict and retry.
	// The second execution is still failed because of the unique key conflict.
	// But the `update ignore` statement should not give any error.
	tk.Continue().ExpectStopOnBreakPoint(sessiontxn.BreakPointBeforeExecutorFirstRun)
	tk.Continue().ExpectIdle()
	// Should only a dup-key warning and the row 1 is not updated.
	tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1062 Duplicate entry '2' for key 't.u'"))
	tk.MustQuery("select * from t order by id").Check(testkit.Rows("1 1", "2 2"))
}
```

### 2. What did you expect to see? (Required)

The test should pass.

### 3. What did you see instead (Required)

The test fails with error:

```
        	Error:      	Received unexpected error:
        	            	[kv:1062]Duplicate entry '2' for key 't.u'
```

### LINKED ISSUE #54492: optimistic transaction does not respect `tidb_constraint_check_in_place`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(id int primary key, u int unique);
insert into t values (1, 1), (2, 2);
set @@tidb_constraint_check_in_place=0;
begin optimistic;
update t set u=2 where id=1;
```

### 2. What did you expect to see? (Required)

update should not report any error in optimistic transaction because `tidb_constraint_check_in_place` is off

### 3. What did you see instead (Required)

```
> update t set u=2 where id=1;
(1062, "Duplicate entry '2' for key 't.u'")
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #54489

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix some dup-key cases in UpdateRecord
```

### CODE REVIEW

File: pkg/table/tables/tables.go [hunk 1]
```diff
@@ -576,21 +576,9 @@ func (t *TableCommon) UpdateRecord(ctx context.Context, sctx table.MutateContext
...
-		sessVars.PresumeKeyNotExists = savePresumeKeyNotExist
-		if err != nil {
-			return err
-		}
-	} else {
-		err = t.rebuildIndices(sctx, txn, h, touched, oldData, newData, table.WithCtx(ctx))
-		if err != nil {
-			return err
-		}
+	err = t.rebuildIndices(sctx, txn, h, touched, oldData, newData, table.WithCtx(ctx))
```
Comment (ekexium) [inline pkg/table/tables/tables.go:579]: Why change these lines? The test still passes if these lines are unchanged.

Comment (lcwangchao) [reply pkg/table/tables/tables.go:579]: Because this code is unnecessary now. The current `LazyCheckKeyNotExists` is:

```
func (s *SessionVars) LazyCheckKeyNotExists() bool {
	if s.StmtCtx.ErrGroupLevel(errctx.ErrGroupDupKey) != errctx.LevelError {
		// This branch means we are in `insert/update ignore`.
		// The executor will handle the dup-key error and ignore it in executor,
		// so we must check the dup-key error in place to make sure the executor can get the error.
		return false
	}
	return s.PresumeKeyNotExists || (s.TxnCtx != nil && s.TxnCtx.IsPessimistic)
}
```

You can see that if `sessVars.TxnCtx.IsPessimistic` is true, `s.PresumeKeyNotExists || (s.TxnCtx != nil && s.TxnCtx.IsPessimistic)` will always return true, we do not need to set `PresumeKeyNotExists`.

**Review by ekexium — COMMENTED** [review]
Consider a pessimistic txn, constraint_check_in_place=off, and error level is LevelWarn. In original code `LazyCheckKeyNotExists` will return true, in this PR it will return false, right?

Besides, `s.PresumeKeyNotExists` only makes the reasoning more complex. Since it's only set in one place, I think we should consider removing it.

**Comment by lcwangchao** [comment]
> Consider a pessimistic txn, constraint_check_in_place=off, and error level is LevelWarn. In original code `LazyCheckKeyNotExists` will return true, in this PR it will return false, right? If we let the original value of `vars.PresumeKeyNotExists` be `!vars.ConstraintCheckInPlace` we will have the table:
> 
> InTxn	constraint_check_in_place	mode	levelError	master, lazy?	PR, lazy?	Equivalent
> FALSE	FALSE	opt	FALSE	TRUE	FALSE	FALSE
> FALSE	FALSE	opt	TRUE	TRUE	TRUE	TRUE
> FALSE	FALSE	pes	FALSE	TRUE	FALSE	FALSE
> FALSE	FALSE	pes	TRUE	TRUE	TRUE	TRUE
> FALSE	TRUE	opt	FALSE	FALSE	FALSE	TRUE
> FALSE	TRUE	opt	TRUE	FALSE	FALSE	TRUE
> FALSE	TRUE	pes	FALSE	FALSE	FALSE	TRUE
> FALSE	TRUE	pes	TRUE	TRUE	TRUE	TRUE
> TRUE	FALSE	opt	FALSE	TRUE	FALSE	FALSE
> TRUE	FALSE	opt	TRUE	TRUE	TRUE	TRUE
> TRUE	FALSE	pes	FALSE	TRUE	FALSE	FALSE
> TRUE	FALSE	pes	TRUE	TRUE	TRUE	TRUE
> TRUE	TRUE	opt	FALSE	FALSE	FALSE	TRUE
> TRUE	TRUE	opt	TRUE	FALSE	FALSE	TRUE
> TRUE	TRUE	pes	FALSE	FALSE	FALSE	TRUE
> TRUE	TRUE	pes	TRUE	TRUE	TRUE	TRUE
> Besides, `s.PresumeKeyNotExists` only makes the reasoning more complex. Since it's only set in one place, I think we should consider removing it.

This PR only changes `LazyCheckKeyNotExists` in the pessimistic mode. In optimistic mode, it's return value is affected by `PresumeKeyNotExists`. In the update statement, it is not set anyway, so this PR does not change the return value here. In the insert statement, it only changes the return value when error level is `LevelWarn`, however, this only happens in `insert ignore`. The `LazyCheckKeyNotExists` is not used because `BatchCheck` is set to true...

Yes, I think `PresumeKeyNotExists` is boring and we should remove it. But I think we should also remove `LazyCheckKeyNotExists` and use a new option `WithDupKeyCheckMode` (default is checkInPlace) to indicate it. Each scene should compute the DupKeyCheckMode separately.

**Comment by ekexium** [comment]
So the correctness of this fix depends on how upper layer uses it. I suggest that we make `LazyCheckKeyNotExists` unchanged for optimistic transactions, instead of depending on the callers. It seems a more safer approach.

File: pkg/table/tables/tables.go (hunk 1 above)
Comment (lcwangchao) [reply pkg/table/tables/tables.go:579]: reverted diffs in `LazyCheckKeyNotExists` can also fix this bug...

**Review by ekexium — COMMENTED** [review]
Have you verified https://github.com/pingcap/tidb/issues/20484? Seems the part was introduced to solve that issue.

**Comment by lcwangchao** [comment]
> Have you verified #20484? Seems the part was introduced to solve that issue.

Seems it is trying to make a lazy check for update... But I don't understand this PR, if a transaction is pessimistic and the statement is not `update ignore`, `LazyCheckKeyNotExists` should always return true. If the statement is `update ignore`, this bug will occur...

**Review by tiancaiamao — APPROVED** [review]
The current master branch does not work as expected.
If there is no `begin`, the expected behavior is that `index.Create`  does not need tikvSnapshotGet to check unique key exist or not.  
1WkBxs4akW

If there is a begin, both master branch and this PR don't use `tikvSnapshotGet` under `index.Create`:

QpFEM3wbyh


This PR does not make thing change, and it simplify the logic, so LGTM
As for why the current master branch does not work as expected, we can take a separate thread to trace...

File: pkg/table/tables/tables.go (hunk 1 above)
Comment (jackysp) [reply pkg/table/tables/tables.go:579]: ‌‌Let's go back to the original place. The purpose of `tidb_constraint_check_in_place` is only to make the lazy unique index check for insert effective. Historically, only inserts had a lazy unique index check. `tidb_constraint_check_in_place` was actually designed to remove this exclusive check for inserts, so that all statements execute consistent in-place checks. Therefore, update statements have never had a lazy check. So even if `tidb_constraint_check_in_place` is off, updates should still report an error. @lcwangchao @ekexium

Comment (jackysp) [reply pkg/table/tables/tables.go:579]: As for why the name was designed this way, that was the product manager's decision at the time. However, I don't think it's necessary to make updates lazy check as well. The reason insert needs lazy check is because it performs more efficiently during bulk load. Bulk loading should rarely involve updates, right?

Comment (jackysp) [reply pkg/table/tables/tables.go:579]: If you want the update to also perform a lazy check, handling it only at https://github.com/pingcap/tidb/blob/08147e7e2586b1db7162ad9c2dfc134b5a5f6b43/pkg/table/tables/tables.go#L579-L589 is not enough. It also requires the 2PC phase to first check for unique constraints like insert before committing. This way, for https://github.com/pingcap/tidb/issues/54489, there will be no retry during an update; instead, a duplicate entry error reported by TiKV will be received.

**Review by cfzjywxk — APPROVED** [review]
It's difficult to verify the correctness for all the combinations of optimistic/pessimistic mods and check in-place or not directly.

We may need to file a refactor and test coverage task to clarify the related code path, especially the `optimistic mode` would be deprecated in the future. It could be also considered as one of the sub-tasks of the deprecation.
/cc @lcwangchao @ekexium
