### PR TITLE
executor: fix a bug of update with outer join

### LINKED ISSUE #7176: update table left join with an auto_increment column table failure
1. What did you do?

```
create table a (k int, v int);
create table b (xid int auto_increment, k int, v int, primary key(xid));
insert into a (1, 1);

 update a left join b on a.k = b.k set a.v = 2;
```

2. What did you expect to see?

update success

3. What did you see instead?

```
ERROR 1105 (HY000): Column 'xid' cannot be null
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.0.5

### PR DESCRIPTION
**Pull request by lysu**
## What have you changed? (mandatory)

fixes #7176

#### question

fix update table with outer join, mainly fix two question

- a left join b, update a's columns, b should not change or error
- a left join b, update b's columns, and b has rows matched, they will be updated
- a left join b, update b's columns, and b no matched, b should not insert or any other action

more cases  can be seen in new unit test

#### change

- build the join physical plan will mark `right table` columns
- during updated record will check the previous mark and check if all data is null is null filled by join
- ignore update and check for these filled null columns 

## What is the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

-  unit tests
- integration tests
- manual tests?

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR need to be added to the release notes? (mandatory)

Yes

```
fix a bug of update with outer join
```

## Refer to a related PR or issue link (optional)

#7176

## Add a few positive/negative examples (optional)

in testcase

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/7177)

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -2913,9 +2913,51 @@ func (s *testSuite) TestUnsignedDecimalOverflow(c *C) {
...
+	tk.MustExec("create table t3(id int auto_increment, k int, v int, primary key(id))")
+	tk.MustExec("insert into t1 values (1, 0)")
+
+	// test auto_increment & none-null column in right table of update left join.
+	tk.MustExec("update t1 left join t3 on t1.k = t3.k set t1.v = 1")
+	tk.MustQuery("select k, v from t1").Check(testkit.Rows("1 1"))
+	tk.MustQuery("select id, k, v from t3").Check(testkit.Rows())
+
+	// test left join and right no records but update no records part.
+	tk.MustExec("update t1 left join t2 on t1.k = t2.k set t1.v = t2.v, t2.v = 3") // exchange to t2.v = 3, t1.v = t2.v..will got a bug.
```
Comment (lysu) [inline executor/executor_test.go]: exchange `t1.v = t2.v, t2.v = 3` to `t2.v = 3, t1.v = t2.v` will be fix later - -

File: expression/column.go [hunk 2]
```diff
@@ -140,6 +140,12 @@ func (col *CorrelatedColumn) ResolveIndices(_ *Schema) Expression {
 func (col *CorrelatedColumn) resolveIndices(_ *Schema) {
 }
 
+// ColumnIdentifier represents a identifier of column.
+type ColumnIdentifier struct {
```
Comment (winoros) [inline expression/column.go]: Can you wait for this merged?
https://github.com/pingcap/tidb/pull/7157

File: expression/schema.go [hunk 3]
```diff
@@ -37,7 +37,8 @@ type Schema struct {
 	Columns []*Column
 	Keys    []KeyInfo
 	// TblID2Handle stores the tables' handle column information if we need handle in execution phase.
-	TblID2Handle map[int64][]*Column
+	TblID2Handle  map[int64][]*Column
+	ReplenishCols map[ColumnIdentifier]struct{}
```
Comment (winoros) [inline expression/schema.go]: Can this set maintained by `INSERT` or `UPDATE` instead of in schema?

File: expression/column.go (hunk 2 above)
Comment (lysu) [reply expression/column.go]: @winoros should #7157 cherry-pick to 2.0.6~?

Comment (winoros) [reply expression/column.go]: The answer might be `no` for now.

File: executor/write.go [hunk 4]
```diff
@@ -82,8 +83,15 @@ func updateRecord(ctx sessionctx.Context, h int64, oldData, newData []types.Datu
...
+
+		oldDataNull := oldData[i].IsNull()
+
+		if checkReplenish && oldDataAllNull && !oldDataNull {
+			oldDataAllNull = false
+		}
+
 		// Rebase auto increment id if the field is changed.
-		if mysql.HasAutoIncrementFlag(col.Flag) {
+		if mysql.HasAutoIncrementFlag(col.Flag) && !(checkReplenish && oldDataAllNull) {
```
Comment (jackysp) [inline executor/write.go]: I think it is acceptable, but the root cause is not this. It seems MySQL sets the auto-id and checks NULL for it just before writing the row. It is much later than TiDB. Maybe someday we should refactor TiDB's implement.

**Comment by lysu** [comment]
PTAL @XuHuaiyu @winoros  thx~

File: executor/update.go [hunk 5]
```diff
@@ -35,10 +35,11 @@ type UpdateExec struct {
...
 
-	rows        [][]types.Datum // The rows fetched from TableExec.
-	newRowsData [][]types.Datum // The new values to be set.
-	fetched     bool
-	cursor      int
+	rows         [][]types.Datum // The rows fetched from TableExec.
+	newRowsData  [][]types.Datum // The new values to be set.
+	fetched      bool
+	cursor       int
+	replenishTbl map[string]ColumnIndexRange
```
Comment (XuHuaiyu) [inline executor/update.go]: comment for this attribute

File: executor/builder.go [hunk 6]
```diff
@@ -1204,15 +1204,86 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
 	}
 	return updateExec
 }
 
+// ColumnIndexRange represents an index range in datum rows.
+type ColumnIndexRange struct {
+	start, end int
+}
+
+// resolveReplenishTbl resolve sub-join's replenish column info.
```
Comment (XuHuaiyu) [inline executor/builder.go]: We need a more detailed comment for this function.

File: executor/update.go [hunk 7]
```diff
@@ -163,6 +165,10 @@ func (e *UpdateExec) handleErr(colName model.CIStr, rowIdx int, err error) error
 func (e *UpdateExec) composeNewRow(rowIdx int, oldRow []types.Datum) ([]types.Datum, error) {
 	newRowData := types.CopyRow(oldRow)
 	for _, assign := range e.OrderedList {
+		colRange, isReplenish := e.replenishTbl[assign.Col.DBName.O+"-"+assign.Col.TblName.O]
```
Comment (coocood) [inline executor/update.go]: Is it an optimization? 
Can we remove this?

File: executor/write.go [hunk 8]
```diff
@@ -53,14 +53,15 @@ const (
 //     4. lastInsertID (uint64) : the lastInsertID should be set by the newData.
 //     5. err (error) : error in the update.
 func updateRecord(ctx sessionctx.Context, h int64, oldData, newData []types.Datum, modified []bool, t table.Table,
-	onDup bool) (bool, bool, int64, uint64, error) {
+	onDup, checkReplenish bool) (bool, bool, int64, uint64, error) {
```
Comment (coocood) [inline executor/write.go]: Can we move the check out of `updateRecord`?
This method is too complex already.

File: executor/update.go (hunk 5 above)
Comment (coocood) [inline executor/update.go]: We can use `*expression.Column` as the key of the map.

File: executor/write.go (hunk 8 above)
Comment (lysu) [reply executor/write.go]: Done~

File: executor/update.go (hunk 7 above)
Comment (lysu) [reply executor/update.go]: mum..no..it's a bugfix not optimize, remove this will cause https://github.com/pingcap/tidb/pull/7177/files#diff-6d9a596d0d155b4342a598ba359efc8bR2985 failure

File: executor/executor_test.go [hunk 9]
```diff
@@ -2959,3 +2959,66 @@ func (s *testSuite) TestUnionAutoSignedCast(c *C) {
...
+	tk.MustExec("create table t5(k int, v int, primary key(k))")
+	tk.MustExec("insert into t1 values (1, 0)")
+	tk.MustExec("insert into t4 values (3, 3)")
+
+	// test auto_increment & none-null column in right table of update left join.
+	tk.MustExec("update t1 left join t3 on t1.k = t3.k set t1.v = 1")
+	tk.MustQuery("select k, v from t1").Check(testkit.Rows("1 1"))
+	tk.MustQuery("select id, k, v from t3").Check(testkit.Rows())
+
+	// test left join and right no records but update no records part.
```
Comment (lilin90) [inline executor/executor_test.go]: -> test left join and the case that the right table has no matching record but has updated the right table columns

File: executor/executor_test.go [hunk 10]
```diff
@@ -2959,3 +2959,66 @@ func (s *testSuite) TestUnionAutoSignedCast(c *C) {
...
+	tk.MustExec("update t1 left join t2 on t1.k = t2.k set t1.v = t2.v, t2.v = 3")
+	tk.MustQuery("select k, v from t1").Check(testkit.Rows("1 <nil>"))
+	tk.MustQuery("select k, v from t2").Check(testkit.Rows())
+
+	// test set right table and ref right old value in left one.
```
Comment (lilin90) [inline executor/executor_test.go]: -> test the case that the update operation in the left table references data in the right table while data of the right table columns is modified

File: executor/executor_test.go [hunk 11]
```diff
@@ -2959,3 +2959,66 @@ func (s *testSuite) TestUnionAutoSignedCast(c *C) {
...
+	tk.MustExec("update t1 left join t2 on t1.k = t2.k set t2.v = 3, t1.v = t2.v")
+	tk.MustQuery("select k, v from t1").Check(testkit.Rows("1 <nil>"))
+	tk.MustQuery("select k, v from t2").Check(testkit.Rows())
+
+	// test right join and left no records but update no records part.
```
Comment (lilin90) [inline executor/executor_test.go]: -> test right join and the case that the left table has no matching record but has updated the left table columns

File: executor/executor_test.go [hunk 12]
```diff
@@ -2959,3 +2959,66 @@ func (s *testSuite) TestUnionAutoSignedCast(c *C) {
...
+	tk.MustExec("update t2 right join t1 on t2.k = t1.k set t2.v = 4, t1.v = 0")
+	tk.MustQuery("select k, v from t1").Check(testkit.Rows("1 0"))
+	tk.MustQuery("select k, v from t2").Check(testkit.Rows())
+
+	// test left + right join update
```
Comment (lilin90) [inline executor/executor_test.go]: -> test the case of right join and left join at the same time

File: executor/executor_test.go [hunk 13]
```diff
@@ -2959,3 +2959,66 @@ func (s *testSuite) TestUnionAutoSignedCast(c *C) {
...
+	tk.MustExec("update t1 left join t2 on t1.k = t2.k right join t4 on t4.k = t2.k set t1.v = 4, t2.v = 4, t4.v = 4")
+	tk.MustQuery("select k, v from t1").Check(testkit.Rows("1 0"))
+	tk.MustQuery("select k, v from t2").Check(testkit.Rows())
+	tk.MustQuery("select k, v from t4").Check(testkit.Rows("3 4"))
+
+	// test left join and update right data.
```
Comment (lilin90) [inline executor/executor_test.go]: -> test normal left join and the case that the right table has matching rows

File: executor/executor_test.go [hunk 14]
```diff
@@ -2959,3 +2959,66 @@ func (s *testSuite) TestUnionAutoSignedCast(c *C) {
...
+	tk.MustExec("insert t2 values (1, 10)")
+	tk.MustExec("update t1 left join t2 on t1.k = t2.k set t2.v = 11")
+	tk.MustQuery("select k, v from t2").Check(testkit.Rows("1 11"))
+
+	// test join same table multiple times, update right record and not insert no exists record.
```
Comment (lilin90) [inline executor/executor_test.go]: -> test the case of continuously joining the same table and updating the unmatching records

File: executor/executor_test.go [hunk 15]
```diff
@@ -2959,3 +2959,66 @@ func (s *testSuite) TestUnionAutoSignedCast(c *C) {
...
+	tk.MustExec("update t1 t11 left join t2 on t11.k = t2.k left join t1 t12 on t2.v = t12.k set t12.v = 233, t11.v = 111")
+	tk.MustQuery("select k, v from t1").Check(testkit.Rows("1 111"))
+	tk.MustQuery("select k, v from t2").Check(testkit.Rows("1 11"))
+
+	// test left join and left all null record's update.
```
Comment (lilin90) [inline executor/executor_test.go]: -> test the left join case that the left table has records but all records are null

Comment (lysu) [reply executor/executor_test.go]: thanks very much, ^ ^ I will address them.

File: executor/analyze.go [hunk 16]
```diff
@@ -72,7 +72,7 @@ func (e *AnalyzeExec) Next(ctx context.Context, chk *chunk.Chunk) error {
 		result := <-resultCh
 		if result.Err != nil {
 			err = result.Err
-			if errors.Trace(err) == analyzeWorkerPanic {
```
Comment (lysu) [inline executor/analyze.go]:
```
CGO_ENABLED=0 revive -formatter friendly -config revive.toml $(go list ./...| grep -vE "vendor")
  ✘  error-naming  error var analyzeWorkerPanic should have name of the form errFoo  
  /home/robi/Code/go/src/github.com/pingcap/tidb/executor/analyze.go:119:5

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  error-naming  
```

File: executor/builder.go [hunk 17]
```diff
@@ -1236,15 +1236,79 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+	var cols2Handle Columns2Handle
+	for tblID, handleCols := range schema.TblID2Handle {
+		tbl := tblID2Table[tblID]
+		for _, handleCol := range handleCols {
+			offset := getTableOffset(schema, handleCol)
+			end := offset + len(tbl.WritableCols())
+			cols2Handle = append(cols2Handle, Columns2HandleEntry{offset, end, handleCol.Index})
+		}
+	}
+	sort.Sort(cols2Handle)
```
Comment (winoros) [inline executor/builder.go]: Do we need to sort them?

Comment (lysu) [reply executor/builder.go]: for later find at https://github.com/pingcap/tidb/pull/7177/files/d67a05e0fcf141855ede1651256e10a85f41cf0f#diff-badfcd30d7596a08cd207b8e6ae778e6R1284 we need sorted, and for-loop TblID2Handle doesn't make sure order o o?

File: executor/builder.go [hunk 18]
```diff
@@ -1236,15 +1236,79 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+		tblID2table:    tblID2table,
+		columns2Handle: columns2Handle,
 	}
 	return updateExec
 }
 
+// Columns2HandleEntry represents an mapper from column index to handle index.
+type Columns2HandleEntry struct {
+	start, end int
+	handleIdx  int
```
Comment (zz-jason) [inline executor/builder.go]: How about:
- s/handleIndex/handleOrdinal/
- s/Columns2HandleEntry/cols2Handle/
- s/Columns2Handle/cols2HandleSlice/


We can use the word "ordinal" to replace "index" to avoid misunderstanding.

File: executor/builder.go [hunk 19]
```diff
@@ -1236,15 +1236,79 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+		baseExecutor:   newBaseExecutor(b.ctx, nil, v.ExplainID(), selExec),
+		SelectExec:     selExec,
+		OrderedList:    v.OrderedList,
+		tblID2table:    tblID2table,
+		columns2Handle: columns2Handle,
 	}
 	return updateExec
 }
 
+// Columns2HandleEntry represents an mapper from column index to handle index.
```
Comment (zz-jason) [inline executor/builder.go]: how about:
```go
// Columns2HandleEntry maps a consecutive columns to a handle column.
type Columns2HandleEntry struct {
    start, end    int32 // Represent the ordinal range [start, end) of the consecutive columns.
    handleOrdinal int32 // Represents the ordinal of the handle column.
}
```

And it seems that `start` is always equal to `handleIdx`, do we need to store `handleIdx`?

File: executor/builder.go [hunk 20]
```diff
@@ -1236,15 +1236,79 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+// c must be sorted using sort.Sort.
+func (c Columns2Handle) findHandle(colIndex int) (int, bool) {
+	if c == nil || len(c) == 0 {
+		return 0, false
+	}
+	biggerOne := sort.Search(len(c), func(i int) bool { return c[i].start > colIndex })
+	if biggerOne == 0 {
+		return 0, false
+	}
+	if c[biggerOne-1].start <= colIndex && colIndex < c[biggerOne-1].end {
```
Comment (zz-jason) [inline executor/builder.go]: I think here `c[biggerOne-1].start <= colIndex` is guaranteed to be true, we only need to check `colIndex < c[biggerOne-1].end`

File: executor/builder.go [hunk 21]
```diff
@@ -1236,15 +1236,79 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+func (c Columns2Handle) Less(i, j int) bool {
+	if c[i].start == c[j].start {
+		return c[i].end < c[i].end
+	}
+	return c[i].start < c[j].start
+}
+
+// findHandle finds the range hit by given column index.
+// c must be sorted using sort.Sort.
+func (c Columns2Handle) findHandle(colIndex int) (int, bool) {
```
Comment (zz-jason) [inline executor/builder.go]: how about `s/colIndex/colOrdinal/` or `s/colIndex/ordinal/` ?

File: executor/builder.go [hunk 22]
```diff
@@ -1236,15 +1236,79 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+// let ranges first sorted by `start` increasing order, and then sorted by `end` increasing order if `start` are equal.
+func (c Columns2Handle) Less(i, j int) bool {
+	if c[i].start == c[j].start {
+		return c[i].end < c[i].end
+	}
+	return c[i].start < c[j].start
+}
+
+// findHandle finds the range hit by given column index.
+// c must be sorted using sort.Sort.
```
Comment (zz-jason) [inline executor/builder.go]: How about simplify the comment to "findHandle finds the ordinal of the corresponding handle column."? Since the slice is sorted when created, there is no need to specify the `sorted` preconditions.

File: executor/update.go [hunk 23]
```diff
@@ -62,6 +63,11 @@ func (e *UpdateExec) exec(schema *expression.Schema) ([]types.Datum, error) {
 		for _, col := range cols {
 			offset := getTableOffset(schema, col)
 			end := offset + len(tbl.WritableCols())
+			handleDatum := row[col.Index]
+			// handleDatum is nil only when outer join fill no matched columns.
```
Comment (zz-jason) [inline executor/update.go]: How about wrapping a function to check whether we can update the current record:
```go
// canNotUpdate checks the handle of a record to decide whether that record
// can not be updated. The handle is NULL only when it is the inner side of an
// outer join: the outer row can not match any inner rows, and in this scenario
// the inner handle field is filled with a NULL value.
//
// This fixes: https://github.com/pingcap/tidb/issues/7176.
func (e *UpdateExec) canNotUpdate(handle types.Datum) bool {
    return handle.IsNull()
}
```

File: executor/builder.go [hunk 24]
```diff
@@ -1236,15 +1236,79 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+
+// Len implements sort.Interface#Swap.
+func (c Columns2Handle) Swap(i, j int) {
+	c[i], c[j] = c[j], c[i]
+}
+
+// Len implements sort.Interface#Less.
+// let ranges first sorted by `start` increasing order, and then sorted by `end` increasing order if `start` are equal.
+func (c Columns2Handle) Less(i, j int) bool {
+	if c[i].start == c[j].start {
```
Comment (zz-jason) [inline executor/builder.go]: This situation should never happen?

File: executor/builder.go (hunk 19 above)
Comment (lysu) [reply executor/builder.go]: `handleOrdinal` may equal to `start` or `end` o.o?

if table without the primary key, the handle will be `end`
if table with the primary key, the handle will be  primary definition index, e.g. `create table t5(v int, k int, primary key(k))`, will be start=1, end=3, handle=2

File: executor/builder.go (hunk 24 above)
Comment (lysu) [reply executor/builder.go]: I'm not very sure about this...so add this protection.... 23333

File: executor/builder.go (hunk 19 above)
Comment (zz-jason) [reply executor/builder.go]: If so, I think to use getTableOffset to decide the begin offset of a table is wrong:
```go
199 func getTableOffset(schema *expression.Schema, handleCol *expression.Column) int {
200     for i, col := range schema.Columns {
201         if col.DBName.L == handleCol.DBName.L && col.TblName.L == handleCol.TblName.L {
202             return i
203         }
204     }
205     panic("Couldn't get column information when do update/delete")
206 }
```

File: executor/builder.go [hunk 25]
```diff
@@ -1236,15 +1236,75 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+	return len(c)
+}
+
+// Len implements sort.Interface#Swap.
+func (c cols2HandleSlice) Swap(i, j int) {
+	c[i], c[j] = c[j], c[i]
+}
+
+// Len implements sort.Interface#Less.
+// let ranges first sorted by `start` increasing order, and then sorted by `end` increasing order if `start` are equal.
```
Comment (zz-jason) [inline executor/builder.go]: the comments need to be updated :smile:

File: executor/builder.go [hunk 26]
```diff
@@ -1236,15 +1236,75 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+		OrderedList:    v.OrderedList,
+		tblID2table:    tblID2table,
+		columns2Handle: columns2Handle,
 	}
 	return updateExec
 }
 
+// cols2Handle represents an mapper from column index to handle index.
+type cols2Handle struct {
+	start, end    int // Represent the ordinal range [start, end) of the consecutive columns.
```
Comment (zz-jason) [inline executor/builder.go]: how about `int32`?

Comment (lysu) [reply executor/builder.go]: why?

Comment (lysu) [reply executor/builder.go]: ok, I know fixed...

File: executor/builder.go (hunk 19 above)
Comment (lysu) [reply executor/builder.go]: from this three logic:

https://github.com/lysu/tidb/blob/44a2ad7f0f65e5c5ea3dab0f20a34fe5a357e58a/plan/logical_plan_builder.go#L1817

https://github.com/lysu/tidb/blob/44a2ad7f0f65e5c5ea3dab0f20a34fe5a357e58a/plan/point_get_plan.go#L260

https://github.com/lysu/tidb/blob/44a2ad7f0f65e5c5ea3dab0f20a34fe5a357e58a/plan/find_best_task.go#L312

handle in `[start, end]`.....

for `getTableOffset`..it will works if schema.Columns is order by columns group that grouped by table...  e.g.  `|t1.x, t1.y| t2.z, t2,u|`....

this logic is same to https://github.com/lysu/tidb/blob/e5922f4ff012e748bb51bd7e854fe02a9813fd93/executor/update.go#L45 update#exec

File: executor/builder.go [hunk 27]
```diff
@@ -1236,15 +1236,74 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+	}
+	if ordinal < c[biggerOne-1].end {
+		return c[biggerOne-1].handleOrdinal, true
+	}
+	return 0, false
+}
+
+// buildColumns2Handle build columns to handle mapping.
+func buildColumns2Handle(schema *expression.Schema, tblID2Table map[int64]table.Table) cols2HandleSlice {
+	if len(schema.TblID2Handle) < 2 {
```
Comment (XuHuaiyu) [inline executor/builder.go]: 1. We need a comment for this check.
2. Any test case covers this?

**Comment by zz-jason** [comment]
@XuHuaiyu PTAL

File: executor/builder.go [hunk 28]
```diff
@@ -1236,15 +1236,74 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+func (c cols2HandleSlice) Less(i, j int) bool {
+	return c[i].start < c[j].start
+}
+
+// findHandle finds the ordinal of the corresponding handle column.
+func (c cols2HandleSlice) findHandle(ordinal int32) (int32, bool) {
+	if c == nil || len(c) == 0 {
+		return 0, false
+	}
+	biggerOne := sort.Search(len(c), func(i int) bool { return c[i].start > ordinal })
```
Comment (XuHuaiyu) [inline executor/builder.go]: We need a comment for biggerOne.

File: executor/builder.go [hunk 29]
```diff
@@ -1236,15 +1236,74 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+	if biggerOne == 0 {
+		return 0, false
+	}
+	if ordinal < c[biggerOne-1].end {
```
Comment (XuHuaiyu) [inline executor/builder.go]: Will this always be true if we reach here?

File: executor/builder.go [hunk 30]
```diff
@@ -1236,15 +1236,74 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+		return c[biggerOne-1].handleOrdinal, true
+	}
+	return 0, false
+}
+
+// buildColumns2Handle build columns to handle mapping.
```
Comment (XuHuaiyu) [inline executor/builder.go]: s/ build/ builds

File: executor/update.go [hunk 31]
```diff
@@ -35,10 +35,11 @@ type UpdateExec struct {
...
 
-	rows        [][]types.Datum // The rows fetched from TableExec.
-	newRowsData [][]types.Datum // The new values to be set.
-	fetched     bool
-	cursor      int
+	rows           [][]types.Datum // The rows fetched from TableExec.
+	newRowsData    [][]types.Datum // The new values to be set.
+	fetched        bool
+	cursor         int
+	columns2Handle cols2HandleSlice
```
Comment (XuHuaiyu) [inline executor/update.go]: we need a comment for this attribute.

File: executor/builder.go (hunk 29 above)
Comment (lysu) [reply executor/builder.go]: for now ...it's true...previous maybe no...- - fixed~

File: executor/builder.go (hunk 27 above)
Comment (lysu) [reply executor/builder.go]: old case tested this...for `update single table update t set x =1 where y = 1`

...but I had added one in executor_test TestUpdateJoin~

File: executor/builder.go [hunk 32]
```diff
@@ -1236,15 +1236,74 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+}
+
+// Len implements sort.Interface#Less.
+func (c cols2HandleSlice) Less(i, j int) bool {
+	return c[i].start < c[j].start
+}
+
+// findHandle finds the ordinal of the corresponding handle column.
+func (c cols2HandleSlice) findHandle(ordinal int32) (int32, bool) {
+	if c == nil || len(c) == 0 {
```
[the remark this answers is not in the document]
Comment (lysu) [reply executor/builder.go]: receiver is slice(point), so it's ok

File: executor/builder.go [hunk 33]
```diff
@@ -1236,15 +1236,74 @@ func (b *executorBuilder) buildUpdate(v *plan.Update) Executor {
...
+		OrderedList:    v.OrderedList,
+		tblID2table:    tblID2table,
+		columns2Handle: columns2Handle,
 	}
 	return updateExec
 }
 
+// cols2Handle represents an mapper from column index to handle index.
+type cols2Handle struct {
+	start, end    int32 // Represent the ordinal range [start, end) of the consecutive columns.
```
Comment (XuHuaiyu) [inline executor/builder.go]: Put the comment on the top line of the attribute, since it's a complete sentence

Comment (lysu) [reply executor/builder.go]: done
