### PR TITLE
executor: fix hint not working in prepared statement

### LINKED ISSUE #18535: hint doesn't work in prepare stmt
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
prepare stmt from "select /*+ max_execution_time(100) */ sleep(1)";
execute stmt;
select /*+ max_execution_time(100) */ sleep(1);
```

### 2. What did you expect to see? (Required)
in mysql  8.0.17
```
mysql> prepare stmt from "select /*+ max_execution_time(100) */ sleep(1)";
Query OK, 0 rows affected (0.00 sec)
Statement prepared

mysql> execute stmt;
+----------+
| sleep(1) |
+----------+
|        1 |
+----------+
1 row in set (0.10 sec)

mysql> select /*+ max_execution_time(100) */ sleep(1);
+----------+
| sleep(1) |
+----------+
|        1 |
+----------+
1 row in set (0.10 sec)
```
### 3. What did you see instead (Required)
```
mysql> prepare stmt from "select /*+ max_execution_time(100) */ sleep(1)";
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt;
select /*+ max_execution_time(100) */ sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.01 sec)

mysql> select /*+ max_execution_time(100) */ sleep(1);
+----------+
| sleep(1) |
+----------+
|        1 |
+----------+
1 row in set (0.16 sec)
```
### 4. Affected version (Required)
```
Release Version: v4.0.2-23-g89e34b707
Edition: Community
Git Commit Hash: 89e34b707fdfeb1bcac5b3ecd13f5614bd2f0291
Git Branch: release-4.0
UTC Build Time: 2020-07-14 03:01:17
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #18535 

Problem Summary: in `optimize`, `sessVars.StmtCtx.StmtHints` will be overwrite in a defered function at returning, but if the executed statement is a prepared statement, the hint will be eclipsed, causeing the hint being invalid.

### What is changed and how it works?

What's Changed:

How it Works:

removed the overwrite.

### Related changes

- Need to cherry-pick to the 4.0

### Check List 

Tests 

- Unit test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: executor/prepared_test.go [hunk 1]
```diff
@@ -104,6 +104,25 @@ func (s *testSuite1) TestPrepareStmtAfterIsolationReadChange(c *C) {
 	c.Assert(tk.Se.GetSessionVars().PreparedStmts[1].(*plannercore.CachedPrepareStmt).NormalizedPlan, Equals, "")
 }
 
+func (s *testSuite9) TestPreparedStmtWithHint(c *C) {
+	// see https://github.com/pingcap/tidb/issues/18535
+	store, dom, err := newStoreWithBootstrap()
```
Comment (lzmhhh123) [inline executor/prepared_test.go:109]: No need to new store.

File: executor/prepared_test.go [hunk 2]
```diff
@@ -104,6 +104,14 @@ func (s *testSuite1) TestPrepareStmtAfterIsolationReadChange(c *C) {
 	c.Assert(tk.Se.GetSessionVars().PreparedStmts[1].(*plannercore.CachedPrepareStmt).NormalizedPlan, Equals, "")
 }
 
+func (s *testSuite9) TestPreparedStmtWithHint(c *C) {
+	// see https://github.com/pingcap/tidb/issues/18535
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("prepare stmt from \"select /*+ max_execution_time(100) */ sleep(1)\"")
+	tk.MustQuery("execute stmt").Check(testkit.Rows("1")) // hint should work and interrupt the sleep execution
```
Comment (wshwsh12) [inline executor/prepared_test.go:112]: The test failed in CI.

File: executor/prepared_test.go (hunk 1 above)
Comment (ichn-hu) [reply executor/prepared_test.go:146]: I originally deleted it, however it turns out that I need to use a new `domain`, I created it again.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Comment by ichn-hu** [comment]
@wshwsh12 PTAL

File: executor/prepared_test.go [hunk 3]
```diff
@@ -104,6 +109,64 @@ func (s *testSuite1) TestPrepareStmtAfterIsolationReadChange(c *C) {
...
+	}
+	_, err = se.Execute(context.Background(), "prepare stmt from \"select /*+ max_execution_time(100) */ sleep(10)\"")
+	c.Assert(err, IsNil)
+	se.SetSessionManager(sm)
+	go dom.ExpensiveQueryHandle().SetSessionManager(sm).Run()
+	rs, err := se.Execute(context.Background(), "execute stmt")
+	c.Check(err, IsNil)
+	tk := testkit.NewTestKit(c, store)
+	tk.ResultSetToResult(rs[0], Commentf("%v", rs)).Check(testkit.Rows("1"))
+	c.Check(sm.killed, Equals, true)
```
Comment (wshwsh12) [inline executor/prepared_test.go:167]: Nitpick: 
1. I think we should separate init resources and test.
```
tk := testkit.NewTestKit(c, store)
se.SetSessionManager(sm)
go dom.ExpensiveQueryHandle().SetSessionManager(sm).Run()
.....
se.Execute....
tk.ResultSetToResult....
```
2.  Why not use tk.MustExec, tk.MustQuery?

File: planner/optimize.go [hunk 4]
```diff
@@ -106,13 +106,10 @@ func Optimize(ctx context.Context, sctx sessionctx.Context, node ast.Node, is in
...
-	defer func() {
-		sessVars.StmtCtx.StmtHints = stmtHints
-		for _, warn := range warns {
-			sctx.GetSessionVars().StmtCtx.AppendWarning(warn)
-		}
-	}()
 	sessVars.StmtCtx.StmtHints = stmtHints
+	for _, warn := range warns {
+		sctx.GetSessionVars().StmtCtx.AppendWarning(warn)
+	}
```
Comment (wshwsh12) [inline planner/optimize.go:112]: Maybe the warns will be appended twice? Should clear warns after appending?

**Review by wshwsh12 — COMMENTED** [review]
Almost LGTM

File: executor/prepared_test.go [hunk 5]
```diff
@@ -14,14 +14,19 @@
...
+	"context"
+	"crypto/tls"
 	"fmt"
 	"strings"
+	"sync/atomic"
 
 	. "github.com/pingcap/check"
 	"github.com/pingcap/parser/auth"
 	"github.com/pingcap/parser/model"
+
```
[the remark this answers is not in the document]
Comment (ichn-hu) [reply executor/prepared_test.go:26]: It is wrongly sorted by my IDE, fixed now.

File: executor/prepared_test.go (hunk 3 above)
Comment (ichn-hu) [reply executor/prepared_test.go]: I'll try using tk.MustExec, however for seperat init resources and test, I guess you mean we should put the declaration of the mockSessionManager at another place, but it is only used specifically here as a helper structure, I don't see a better place. Therefore I would like to leave it here, and if it is used in another place in the future, we could then refactoring it.

File: planner/optimize.go (hunk 4 above)
Comment (ichn-hu) [reply planner/optimize.go:112]: Sure~

**Review by wshwsh12 — COMMENTED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
