### PR TITLE
config: add tcp4only for lvs whitelist!

### LINKED ISSUE #21551: Whitelist not working in lvs
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. add: lvs_ip -> tidb_ip
2. connect: mysql -h lvs_ip -uroot
3. output:
Access denied for user 'lvs_test'@'lvs_ip'

### 2. What did you expect to see? (Required)
white list like user@[allow_ip] work.

### 4. What is your TiDB version? (Required)
v4.0.8

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #21551

Problem Summary:
make "lvs_test"@"allow_ip" can work in lvs.

### What is changed and how it works?

What's Changed:
tidb/server/server.go: add "tcp4" mode
tidb/config/config.go: add "enable-tcp4-only" option

How it Works:
After loading module `toa` in RealServer of lvs, "tcp4" protocal can Read the tcp header and parse the real client IP.

Reference: https://www.jianshu.com/p/e770a11481e9

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

All Tests Above passed.

Side effects

Nothing!

### Release note 
- Add enable-tcp4-only config for whitelist client ip through lvs.

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -176,6 +176,8 @@ type Config struct {
 	// where M is the element literal length and w is the number of bytes required for the maximum-length character in the character set.
 	// See https://dev.mysql.com/doc/refman/8.0/en/string-type-syntax.html for more details.
 	EnableEnumLengthLimit bool `toml:"enable-enum-length-limit" json:"enable-enum-length-limit"`
```
Comment (XuHuaiyu) [inline config/config.go:178]: Is it seems that this config is not **ONLY** used for lvs?
enable-->enables

**Comment by bb7133** [comment]
PTAL @morgo

File: config/config.go (hunk 1 above)
Comment (sylzd) [reply config/config.go:178]: 1. yes, but that is a reason why user need it. 
2. enable --> enables: fixed.

**Comment by sylzd** [comment]
I did not change **`TestAsyncCommitWithSchemaChange`**  why this test can not pass...

**Comment by sylzd** [comment]
PTAL @morgo

**Comment by sylzd** [comment]
> I did not change **`TestAsyncCommitWithSchemaChange`** why this test can not pass...

Related to #21563

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by morgo** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
