### PR TITLE
planner, ddl: convert large varchar for create table in non-strict mode

### LINKED ISSUE #30328: Create table with column length is too big : Mysql is converting VARBINARY to BLOB and VARCHAR to TEXT , Tidb is resulting error.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
SET sql_mode = ‘NO_ENGINE_SUBSTITUTION’;
drop table if exists t1;
CREATE TABLE t1( a varbinary(70000), b varchar(70000000));
desc t1;
```
### 2. What did you expect to see? (Required)
```sql
mysql> CREATE TABLE t1( a varbinary(70000), b varchar(70000000));
Query OK, 0 rows affected, 2 warnings (0.01 sec)

mysql> desc t1;
+-------+------------+------+-----+---------+-------+
| Field | Type       | Null | Key | Default | Extra |
+-------+------------+------+-----+---------+-------+
| a     | mediumblob | YES  |     | NULL    |       |
| b     | longtext   | YES  |     | NULL    |       |
+-------+------------+------+-----+---------+-------+
2 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> CREATE TABLE t1( a varbinary(70000), b varchar(70000000));
ERROR 1074 (42000): Column length too big for column 'a' (max = 65535); use BLOB or TEXT instead
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-11-29 16:57:51
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #30328 

Problem Summary:

### What is changed and how it works?
- In non strict mode, auto convert varchar with large length to TEXT or BLOB, and append warnings.
- Fix a nil pointer dereference in test case due to changes.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by unconsolable** [comment]
/cc @sylzd @djshow832 
PTAL, thanks.

**Comment by unconsolable** [comment]
Seems it fails on `unit-test` related with https://github.com/pingcap/tidb/issues/31966
```
[2022-01-26T05:07:12.353Z] === Failed
[2022-01-26T05:07:12.354Z] === FAIL: domain TestDomain (unknown)
....
[2022-01-26T05:07:15.912Z] coverage: 39.4% of statements
[2022-01-26T05:07:15.912Z] panic: test timed out after 10m0s
```

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -566,10 +566,25 @@ func buildColumnAndConstraint(
 	if err != nil {
 		return nil, nil, errors.Trace(err)
 	}
-
 	if err := setCharsetCollationFlenDecimal(colDef.Tp, chs, coll); err != nil {
 		return nil, nil, errors.Trace(err)
 	}
+	// Some column checks are performed before convert, so varchar auto convert is checked here, see issue #30328
```
Comment (djshow832) [inline ddl/ddl_api.go:572]: Why check and revert it here? Is it possible to only check and convert in `preprocessor.checkCreateTableGrammar`?

File: planner/core/preprocess_test.go [hunk 2]
```diff
@@ -364,3 +364,27 @@ func (s *testValidatorSuite) TestDropGlobalTempTable(c *C) {
...
+func (s *testValidatorSuite) TestLargeVarcharAutoConv(c *C) {
+	_, err := s.se.Execute(context.Background(), "use test")
+	c.Assert(err, IsNil)
+	s.runSQL(c, "CREATE TABLE t1(a varbinary(70000), b varchar(70000000))", false,
+		errors.New("[types:1074]Column length too big for column 'a' (max = 65535); use BLOB or TEXT instead"))
+
+	_, err = s.se.Execute(context.Background(), "SET sql_mode = 'NO_ENGINE_SUBSTITUTION'")
+	c.Assert(err, IsNil)
+	s.runSQL(c, "CREATE TABLE t1(a varbinary(70000), b varchar(70000000));", false, nil)
+	s.runSQL(c, "CREATE TABLE t1(a varbinary(70000), b varchar(70000000) charset utf8mb4);", false, nil)
```
Comment (djshow832) [inline planner/core/preprocess_test.go:378]: Please also test `alter table`.

File: ddl/ddl_api.go (hunk 1 above)
Comment (unconsolable) [reply ddl/ddl_api.go:572]: Because in some situations charset of the column is not resolved in `preprocessor.checkCreateTableGrammar`. For example `CREATE TABLE t1(a varbinary(70000), b varchar(70000000));`, the charset and collation of `b` is resolved in func `buildColumnAndConstraint`.

File: planner/core/preprocess_test.go (hunk 2 above)
Comment (unconsolable) [reply planner/core/preprocess_test.go:378]: Resolved.

File: ddl/ddl_api.go (hunk 1 above)
Comment (djshow832) [reply ddl/ddl_api.go]: Then is it possible to only add the code in `buildColumnAndConstraint`?

Comment (unconsolable) [reply ddl/ddl_api.go]: IMHO it is not possible to do so. `buildColumnAndConstraint` builds `table.Column` from `ast.ColumnDef`, and it is called from `(*ddl).CreateTable`, while `(*ddl).getModifiableColumnJob` builds `model.Job` from `ast.AlterTableSpec`, which is called in `(*ddl).ChangeColumn` and `(*ddl).ModifyColumn`.

File: planner/core/preprocess_test.go [hunk 3]
```diff
@@ -341,3 +341,29 @@ func TestErrKeyPart0(t *testing.T) {
...
+	warnCnt := tk.Session().GetSessionVars().StmtCtx.WarningCount()
+	// It is only 3. For the first stmt, ddl will append a warning for column b
+	require.Equal(t, uint16(3), warnCnt)
+	warns := tk.Session().GetSessionVars().StmtCtx.GetWarnings()
+	for i := range warns {
+		require.True(t, terror.ErrorEqual(warns[i].Err, ddl.ErrAutoConvert))
+	}
+
+	tk.Session().GetSessionVars().StmtCtx.SetWarnings(warns[:0])
+	tk.MustExec("SET sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'")
```
Comment (djshow832) [inline planner/core/preprocess_test.go:368]: The session will be destroyed after the test case so I don't think you need to restore it.

**Review by djshow832 — COMMENTED** [review]
Rest LGTM

File: planner/core/preprocess_test.go (hunk 3 above)
Comment (unconsolable) [reply planner/core/preprocess_test.go]: Resolved.

**Review by djshow832 — APPROVED** [review]

File: ddl/ddl_api.go [hunk 4]
```diff
@@ -4354,6 +4357,10 @@ func (d *ddl) getModifiableColumnJob(ctx context.Context, sctx sessionctx.Contex
 		return nil, errors.Trace(err)
 	}
 
+	if err = checkTooBigFieldLengthAndTryAutoConvert(&newCol.FieldType, newCol.Name.O, sctx.GetSessionVars()); err != nil {
```
Comment (zimulala) [inline ddl/ddl_api.go:4360]: Could we put it to `setCharsetCollationFlenDecimal`? Then we needn't call it in two places, and we can do `adjustBlobTypesFlen` in one function.

File: planner/core/preprocess.go [hunk 5]
```diff
@@ -1759,3 +1763,18 @@ func (p *preprocessor) initTxnContextProviderIfNecessary(node ast.Node) {
 		InfoSchema: p.ensureInfoSchema(),
 	})
 }
+
+func (p *preprocessor) tryAutoConvert(colDef *ast.ColumnDef) bool {
+	sessVars := p.ctx.GetSessionVars()
+	if !sessVars.SQLMode.HasStrictMode() && colDef.Tp.Tp == mysql.TypeVarchar &&
+		colDef.Tp.Charset != "" {
+		colDef.Tp.Tp = mysql.TypeBlob
```
Comment (zimulala) [inline planner/core/preprocess.go:1771]: It seems that we can remove this line. I pass `TestLargeVarcharAutoConv` after remove it.

File: planner/core/preprocess.go [hunk 6]
```diff
@@ -1759,3 +1763,18 @@ func (p *preprocessor) initTxnContextProviderIfNecessary(node ast.Node) {
 		InfoSchema: p.ensureInfoSchema(),
 	})
 }
+
+func (p *preprocessor) tryAutoConvert(colDef *ast.ColumnDef) bool {
+	sessVars := p.ctx.GetSessionVars()
+	if !sessVars.SQLMode.HasStrictMode() && colDef.Tp.Tp == mysql.TypeVarchar &&
+		colDef.Tp.Charset != "" {
```
Comment (zimulala) [inline planner/core/preprocess.go:1770]: Why do we need `colDef.Tp.Charset != ""` here?  Could we add a test?

File: planner/core/preprocess.go (hunk 5 above)
Comment (unconsolable) [reply planner/core/preprocess.go:1771]: I thought that sometimes charset can not resolved until `ddl.CreateTable`, so I add a check here. But I found this https://github.com/pingcap/tidb/blob/e389170624e227068213f523b7bed837ae3d95b1/planner/core/preprocess.go#L1254-L1260
So I think `colDef.Tp.Charset != "" ` can be removed now, but strict mode and column type may still need to be checked.

File: planner/core/preprocess.go (hunk 6 above)
Comment (unconsolable) [reply planner/core/preprocess.go:1770]: It may not be needed and can be removed. See also https://github.com/pingcap/tidb/pull/31974#discussion_r814436827

File: planner/core/preprocess.go (hunk 5 above)
Comment (zimulala) [reply planner/core/preprocess.go:1771]: Is there a misunderstanding here? I mean to remove `coldef.tp.tp = mysql.typeblob`

File: planner/core/preprocess.go [hunk 7]
```diff
@@ -1759,3 +1763,18 @@ func (p *preprocessor) initTxnContextProviderIfNecessary(node ast.Node) {
 		InfoSchema: p.ensureInfoSchema(),
 	})
 }
+
+func (p *preprocessor) tryAutoConvert(colDef *ast.ColumnDef) bool {
```
[the remark this answers is not in the document]
Comment (unconsolable) [reply planner/core/preprocess.go]: Resolved, thanks.

File: ddl/ddl_api.go (hunk 4 above)
Comment (unconsolable) [reply ddl/ddl_api.go]: Resolved, thanks.

File: planner/core/preprocess.go (hunk 5 above)
Comment (unconsolable) [reply planner/core/preprocess.go:1770]: Sorry for the misunderstanding. IMHO it may not be removed. 
```
mysql> create table i30328_1(a varbinary(70000), b varchar(70000000));
Query OK, 0 rows affected, 3 warnings (0.01 sec)

mysql> show warnings;
+---------+------+----------------------------------------------+
| Level   | Code | Message                                      |
+---------+------+----------------------------------------------+
| Warning | 1246 | Converting column 'a' from VARBINARY to BLOB |
| Warning | 1246 | Converting column 'a' from VARBINARY to BLOB |
| Warning | 1246 | Converting column 'b' from VARCHAR to TEXT   |
+---------+------+----------------------------------------------+
3 rows in set (0.00 sec)
```
If `colDef.Tp.Tp = mysql.TypeBlob` is removed, type convertion is not performed during preprocess stage, so convertion will happen and warning will be throw again in `checkTooBigFieldLengthAndTryAutoConvert`.

Comment (zimulala) [reply planner/core/preprocess.go:1770]: Is there a test for this scenario? I can pass the test when I delete this line. If there is no test please help to make up.

Comment (unconsolable) [reply planner/core/preprocess.go:1770]: Yes, it is `(*testDBSuite5).TestTooBigFieldLengthAutoConvert` in `ddl/db_test.go`
If this line is removed, it will error as follows:
```
db_test.go:7833:
    tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1246 Converting column 'a' from VARBINARY to BLOB", "Warning 1246 Converting column 'b' from VARCHAR to TEXT"))
/home/chen/tidb/util/testkit/testkit.go:67:
    res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
... obtained string = "" +
...     "[Warning 1246 Converting column 'a' from VARBINARY to BLOB]\n" +
...     "[Warning 1246 Converting column 'a' from VARBINARY to BLOB]\n" +
...     "[Warning 1246 Converting column 'b' from VARCHAR to TEXT]\n"
... expected string = "" +
...     "[Warning 1246 Converting column 'a' from VARBINARY to BLOB]\n" +
...     "[Warning 1246 Converting column 'b' from VARCHAR to TEXT]\n"
... sql:show warnings, args:[]

```

**Review by zimulala — APPROVED** [review]
LGTM
