### PR TITLE
planner: bound the max out of range estimate | tidb-test=pr/2672

### LINKED ISSUE #65294: index time range got a over-estimation compared with v7.5.3
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> plan replayer load '/Users/tailingxiang/Downloads/replayer_4sl0h-c6Ucp4ioSjQFJ4Vw==_1766724135378196957.zip';
Query OK, 0 rows affected (0.203 sec)

mysql> explain format="verbose" SELECT  * FROM db.table WHERE col_time >= '2025-12-22 04:00:00' AND col_time < '2025-12-22 05:00:00';
+-------------------------------+----------+--------------+-----------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows  | estCost      | task      | access object                                                | operator info                                                                                                                                                                          |
+-------------------------------+----------+--------------+-----------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_8                 | 52187.58 | 103350518.05 | root      |                                                              |                                                                                                                                                                                        |
| ├─IndexRangeScan_6(Build)     | 52187.58 | 10620171.98  | cop[tikv] | table:table, index:index(col_time)                           | range:[2025-12-22 04:00:00,2025-12-22 05:00:00), keep order:false, stats:partial[uk_id:allEvicted, idx_session:allEvicted, idx_item:allEvicted...(more: 3 allEvicted)]                 |
| └─TableRowIDScan_7(Probe)     | 52187.58 | 19511254.35  | cop[tikv] | table:table                                                  | keep order:false, stats:partial[uk_id:allEvicted, idx_session:allEvicted, idx_item:allEvicted...(more: 3 allEvicted)]                                                                    |
+-------------------------------+----------+--------------+-----------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set, 1 warning (0.007 sec)

mysql> select version();
+--------------------------+
| version()                |
+--------------------------+
| 8.0.11-TiDB-v7.5.3-dirty |
+--------------------------+
1 row in set (0.005 sec)

mysql> plan replayer load '/Users/tailingxiang/Downloads/replayer_4sl0h-c6Ucp4ioSjQFJ4Vw==_1766724135378196957.zip';
Query OK, 0 rows affected (0.203 sec)

mysql> explain format="verbose" SELECT  * FROM db.table WHERE col_time >= '2025-12-22 04:00:00' AND col_time < '2025-12-22 05:00:00';
+--------------------------------+-------------+----------------+-----------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                             | estRows     | estCost        | task      | access object                                                | operator info                                                                                                                                                                                      |
+--------------------------------+-------------+----------------+-----------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_11                 | 10091419.40 | 19826583302.42 | root      |                                                              |                                                                                                                                                                                                    |
| ├─IndexRangeScan_9(Build)      | 10091419.40 | 2053603847.90  | cop[tikv] | table:table, index:index(col_time)                           | range:[2025-12-22 04:00:00,2025-12-22 05:00:00), keep order:false, stats:partial[uk_id:unInitialized, idx_session:unInitialized, idx_item:unInitialized...(more: 2 unInitialized)]               |
| └─TableRowIDScan_10(Probe)     | 10091419.40 | 4319016330.25  | cop[tikv] | table:table                                                  | keep order:false, stats:partial[uk_id:unInitialized, idx_session:unInitialized, idx_item:unInitialized...(more: 2 unInitialized)]                                                                  |
+--------------------------------+-------------+----------------+-----------+--------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set, 1 warning (0.006 sec)

mysql> select version();
+-----------------------------------------------------+
| version()                                           |
+-----------------------------------------------------+
| 8.0.11-TiDB-v8.5.4-nextgen.202510.0-263-g704d4c88f0 |
+-----------------------------------------------------+
1 row in set (0.000 sec)
```

### 2. What did you expect to see? (Required)
next gen have some over estimation of index time range, not sure it's intended or not. while the actually is quite lower then expected

Image

### 3. What did you see instead (Required)
normal estimation as before, pls feel free to reach me to get the replayer

### 4. What is your TiDB version? (Required)

next-gen & master

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #65294 

Problem Summary:

### What changed and how does it work?

Refactor and attempt to simplify the (complex) out of range estimation. The key problem exposed by issue #65294 was that the MaxEst can be unbounded even if the predicate itself is bounded.

The most critical part of this PR to resolve this issue is this code:
```
if maxTotalPercent > 0 {
	// Always apply maxTotalPercent to maxAddedRows to limit scaling when the predicate has an upper bound
	maxAddedRows *= maxTotalPercent
}
```

This is the 4th in a series of PRs related to out-of-range estimation in an attempt to break up the complex PR:
https://github.com/pingcap/tidb/pull/64486

There are at least 2 more PRs that will complete to remaining enhancements in the larger PR.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by terry1purcell** [comment]
> * **P2 Issue 1: tidb_opt_risk_range_skew_ratio applied twice can over-reduce estimates**
>   
>   * The session variable influences out-of-range estimation in two places: (1) it replaces the default 0.5 multiplier to form base estRows, and (2) it's used again as the blend factor in CalculateSkewRatioCounts. Small non-zero values (e.g., 0.1) can produce a smaller final estimate than the default (skewRatio=0), risking underestimation and plan regressions when users tune this parameter.
>   * Evidence: pkg/statistics/histogram.go:1214-1254
> * **P2 Issue 2: Unsigned column empty ranges can return non-zero estimates**
>   
>   * For unsigned columns, logically empty ranges like [MinNotNull, 0) (e.g., unsigned_col < 0) collapse to zero-width after clamping negative values to 0, but OutOfRangeRowCount returns oneValue instead of 0. This inflates selectivity estimates for impossible predicates.
>   * Evidence: unsigned clamp at pkg/statistics/histogram.go:1157; zero-width handling at :1185; forced lower bound at :1253

Latest 2 commits address both concerns.

File: pkg/statistics/histogram.go [hunk 1]
```diff
@@ -1173,25 +1187,56 @@ func (hg *Histogram) OutOfRangeRowCount(
 	boundL := histL - histWidth
 	boundR := histR + histWidth
 
+	// Step 7: Calculate the width of the predicate
+	// TODO: If predWidth == 0, it may be because the common prefix is too large.
+	// In future - out of range for equal predicates should also use this logic
+	// for consistency. We need to handle both "equal" and "large common prefix".
+	predWidth := r - l
+	if predWidth < 0 {
+		// This should never happen.
```
Comment (0xPoe) [inline pkg/statistics/histogram.go:1196]:
```suggestion
		// This should never happen.
		intest.Assert(false, "Right bound should not be less than left bound")

```

**Comment by terry1purcell** [comment]
/unhold

Added the recommended commit
