### PR TITLE
planner: keep covering indexes for read-only tables in update join | tidb-test=pr/2706 

### LINKED ISSUE #59876: Covering indexes do not work in update joins
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE a (
  id int(11) not NULL,
  bal decimal(10,4) DEFAULT NULL,
  bal2 float DEFAULT NULL,
  primary KEY  (id) NONCLUSTERED
) ;

CREATE TABLE b (
  id int(11) NOT NULL,
  bal decimal(18,4)  ,
  bal2 decimal(18,1) DEFAULT NULL,
  PRIMARY KEY (id) NONCLUSTERED 
  ,key idx2(id, bal)
);

explain
update /*+ inl_join(b) use_index(b,idx2) */ a 
join b on a.id = b.id 
set a.bal = b.bal; 

### 2. What did you expect to see? (Required)
when table a join table b,  just access the index idx2 of table b，without the need for a table lookup. 

### 3. What did you see instead (Required)
id                              |estRows |task     |access object               |operator info                                                                                                  |
--------------------------------+--------+---------+----------------------------+---------------------------------------------------------------------------------------------------------------+
Update_6                        |N/A     |root     |                            |N/A                                                                                                            |
└─Projection_7                  |12500.00|root     |                            |test.a.id, test.a.bal, test.a.bal2, test.a._tidb_rowid, test.b.id, test.b.bal, test.b.bal2, test.b._tidb_rowid |
  └─IndexJoin_12                |12500.00|root     |                            |inner join, inner:IndexLookUp_11, outer key:test.a.id, inner key:test.b.id, equal cond:eq(test.a.id, test.b.id)|
    ├─TableReader_32(Build)     |10000.00|root     |                            |data:TableFullScan_31                                                                                          |
    │ └─TableFullScan_31        |10000.00|cop[tikv]|table:a                     |keep order:false, stats:pseudo                                                                                 |
    └─IndexLookUp_11(Probe)     |12500.00|root     |                            |                                                                                                               |
      ├─IndexRangeScan_9(Build) |12500.00|cop[tikv]|table:b, index:idx2(id, bal)|range: decided by [eq(test.b.id, test.a.id)], keep order:false, stats:pseudo                                   |
      └─TableRowIDScan_10(Probe)|12500.00|cop[tikv]|table:b                     |keep order:false, stats:pseudo                                                                                 |

### 4. What is your TiDB version? (Required)
Release Version: v7.5.3
Edition: Community
Git Commit Hash: 70bfd90035cc81e80d78b4f1f76ca4baef8a5756
Git Branch: HEAD
UTC Build Time: 2024-07-31 13:17:12
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #59876

Problem Summary:

`UPDATE ... JOIN` freezes the join output before optimization and disables projection elimination for the update sub-plan. Before this change, the frozen projection kept the full mixed row for every joined table, including read-only source tables. That polluted the required column set with extra writable columns and row handles, so a covering index on the read-only side could not stay as `IndexReader`.

### What changed and how does it work?

- identify which joined tables are actually updated after `buildUpdateLists()`
- prune the frozen update projection so that it keeps:
  - full writable-column ranges and handle columns only for updated tables
  - assignment-source columns collected in `StmtCtx.ColRefFromUpdatePlan`
- drop handle metadata for read-only tables before building `TblColPosInfos`
- add exact-plan regression coverage for both the covering and non-covering `UPDATE ... JOIN` cases
- add a planner note with the verified root cause, fix boundary, and validation command

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix an issue where `UPDATE ... JOIN` could force a lookup on a read-only joined table even when the chosen index covered all required columns.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * UPDATE ... JOIN now prefers covering indexes and avoids unnecessary table lookups when inputs are read-only, improving update plan selection and performance.

* **Documentation**
  * Added a detailed note explaining UPDATE ... JOIN behavior with covering indexes, symptom, root-cause analysis, and validation steps.

* **Tests**
  * Added regression tests covering multiple UPDATE ... JOIN scenarios to verify index-join plan shapes, alias handling, and rowid paths.

### CODE REVIEW

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -5408,6 +5408,120 @@ func buildColumns2HandleWithWrtiableColumns(
 	return cols2Handles, nil
 }
 
+func collectUpdatedTblColPosInfosForUpdate(
```
Comment (winoros) [inline pkg/planner/core/logical_plan_builder.go]: This helper block is carrying more contract than the current comments make obvious. The pruning here must stay alias/range-scoped for self-joins, it must use `schema.ColumnIndex(assign.Col)` before `ResolveIndices()`, and it must treat handle columns such as `_tidb_rowid` via the `HandleCols` fallback. Without spelling those invariants out here, this is easy to "simplify" later back into the broken behavior. Please add a short block comment above this helper group (or above `collectUpdatedTblColPosInfosForUpdate`) that captures these constraints and why they matter for `UPDATE ... JOIN`.

File: docs/note/planner/update_join_covering_index_notes.md [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+- Keep referenced source columns from assignment expressions via `StmtCtx.ColRefFromUpdatePlan`.
+- Drop handle metadata for read-only aliases before building `TblColPosInfos` for the final update
+  executor.
+
+This keeps the update executor layout intact for target tables, while allowing read-only joined
+tables to stay on covering indexes.
+
+### Regression Coverage
+
+Two cases were added to `pkg/planner/core/issuetest/planner_issue_test.go`:
```
Comment (winoros) [inline docs/note/planner/update_join_covering_index_notes.md]: nit: This section says "Two cases were added", but it actually lists four cases and still misses the `_tidb_rowid` regression case covered in `planner_issue_test.go`. Please sync the note with the actual test coverage so future readers can understand the full fix boundary from the doc alone.

File: pkg/planner/core/logical_plan_builder.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: Added a short block comment above `collectUpdatedTblColPosInfosForUpdate` to pin the three invariants here: alias/range-scoped matching for self-joins, `schema.ColumnIndex(assign.Col)` before `ResolveIndices()`, and the `HandleCols` fallback for handle assignments such as `_tidb_rowid`.

File: docs/note/planner/update_join_covering_index_notes.md (hunk 2 above)
Comment (hawkingrei) [reply docs/note/planner/update_join_covering_index_notes.md]: Synced the note with the actual regression boundary. The coverage section now lists the five planner regression shapes covered in `planner_issue_test.go`, including the `_tidb_rowid` / `HandleCols` case under `tidb_opt_write_row_id = 1`.

File: pkg/planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -5408,6 +5408,135 @@ func buildColumns2HandleWithWrtiableColumns(
 	return cols2Handles, nil
 }
 
+// UPDATE ... JOIN pruning must correctly identify which joined table alias each SET target belongs
```
Comment (winoros) [inline pkg/planner/core/logical_plan_builder.go]: begin with the function name

File: pkg/planner/core/logical_plan_builder.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: Updated in 729e2e2af60. I kept the invariant summary, but rewrote the block comment to start with `collectUpdatedTblColPosInfosForUpdate` so the contract is explicit and the comment follows the usual function-doc style. Marking this thread resolved.

File: pkg/planner/core/logical_plan_builder.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: Updated in 729e2e2af60. The helper comment now begins with `collectUpdatedTblColPosInfosForUpdate` and keeps the alias/range/handle invariants in the body. Marking this thread resolved.

File: docs/note/planner/update_join_covering_index_notes.md (hunk 2 above)
Comment (hawkingrei) [reply docs/note/planner/update_join_covering_index_notes.md]: The note is already synced with the actual regression boundary, including the `_tidb_rowid` / `HandleCols` case. I am resolving this leftover thread as well so the review state matches the current doc.

File: pkg/planner/core/logical_plan_builder.go [hunk 4]
```diff
@@ -5728,14 +5880,10 @@ func (b *PlanBuilder) buildUpdate(ctx context.Context, update *ast.UpdateStmt) (
 	if err != nil {
 		return nil, err
 	}
-	tblID2Handle, err := resolveIndicesForTblID2Handle(b.handleHelper.tailMap(), updt.SelectPlan.Schema())
+	tblID2Handle, err = resolveIndicesForTblID2Handle(tblID2Handle, updt.SelectPlan.Schema())
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go]: why call it double times, L5842

File: pkg/planner/core/logical_plan_builder.go [hunk 5]
```diff
@@ -5710,6 +5838,30 @@ func (b *PlanBuilder) buildUpdate(ctx context.Context, update *ast.UpdateStmt) (
...
+	if err != nil {
+		return nil, err
+	}
+	// Materialize table metadata for writable-column layout reconstruction.
+	tblID2table := make(map[int64]table.Table, len(tblID2Handle))
+	for id := range tblID2Handle {
+		tblID2table[id], _ = b.is.TableByID(ctx, id)
+	}
+	// Rebuild alias/range-scoped writable-column ranges from the frozen update input.
+	cols2Handles, err := buildColumns2HandleWithWrtiableColumns(p.OutputNames(), tblID2Handle, tblID2table)
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go]: ditto in L5887, can we merge them together?

File: pkg/planner/core/logical_plan_builder.go [hunk 6]
```diff
@@ -5421,6 +5421,134 @@ func buildColumns2HandleWithWrtiableColumns(
...
+func (b *PlanBuilder) buildProjectionForUpdateRequiredCols(
+	p base.LogicalPlan,
+	updatedTblColPosInfos physicalop.TblColPosInfoSlice,
+) base.LogicalPlan {
+	if len(updatedTblColPosInfos) == 0 {
+		return p
+	}
+	// UPDATE needs the full writable row layout only for updated aliases/ranges. Read-only join
+	// inputs can be pruned down to assignment-source columns so covering indexes remain available.
+	nonPruned := bitset.New(uint(p.Schema().Len()))
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go]: use fastIntSet

File: pkg/planner/core/logical_plan_builder.go (hunk 5 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: Addressed in the same cleanup commit `dc9f43fca87`.

I did not merge the two phases into one because they are still consuming different schemas before and after pruning/optimization, but I did merge the repeated rebuild logic itself. Both the frozen input path and the final executor path now call the same `buildUpdateTblColPosInfos(...)` helper, which keeps the two-stage semantics but removes the duplicated plumbing.

File: pkg/planner/core/logical_plan_builder.go (hunk 6 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: I kept `map[int]struct{}` for now.

This patch is only trying to remove the duplicated two-stage handle/layout rebuild logic; I did not want to mix an extra container change into the same follow-up. `FastIntSet` is reasonable here, but I would prefer to do it as a separate tiny cleanup if we still want that after this readability pass.

File: pkg/planner/core/logical_plan_builder.go (hunk 4 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: Updated in `dc9f43fca87`.

The two calls stay on purpose because they are for two different schemas/stages:
- the frozen pre-optimize update input, where we identify the updated aliases/ranges and decide the projection pruning;
- the final optimized update input, where we rebuild `updt.TblColPosInfos` for the executor-facing schema.

What I simplified here is the duplicated `resolveIndicesForTblID2Handle + buildColumns2HandleWithWrtiableColumns` path: both stages now go through `buildUpdateTblColPosInfos(...)`, so the split is explicit without duplicating the low-level steps.

File: pkg/planner/core/logical_plan_builder.go (hunk 6 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: Updated in `37f654869a4`.

I kept `bitset` for the `nonPruned` column bitmap, but switched `updatedTblIdxes` to `intset.FastIntSet` here. That set is only tracking a small deduplicated group of updated table-range indexes, and `FastIntSet` lets us keep the ascending replay order directly via `ForEach()` without the extra map+sort step.

File: pkg/planner/core/logical_plan_builder.go [hunk 7]
```diff
@@ -5421,6 +5421,148 @@ func buildColumns2HandleWithWrtiableColumns(
...
+	cols2Handles physicalop.TblColPosInfoSlice,
+) (physicalop.TblColPosInfoSlice, error) {
+	if len(cols2Handles) == 0 {
+		// Virtual/system tables without writable row handles must still reject UPDATE
+		// instead of building a no-target update plan.
+		return nil, plannererrors.ErrPrivilegeCheckFail.GenWithStackByArgs("UPDATE")
+	}
+	updatedTblIdxes := intset.NewFastIntSet()
+	for _, assign := range orderedList {
+		colOrdinal := schema.ColumnIndex(assign.Col)
```
Comment (winoros) [inline pkg/planner/core/logical_plan_builder.go]: Seems that there're three term to explain one thing. `Ordinal`, `idx`/`index` and `pos`.
I think we can eliminate one. Align the `ordinal` with  `idx`/`index` or `pos`.

File: pkg/planner/core/logical_plan_builder.go
Comment (winoros) [inline pkg/planner/core/logical_plan_builder.go:5726]: There's already a projection.
Are they duplicated?

Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go:5726]: Yes, I have refactor code. we can reuse this projection.

File: pkg/planner/core/logical_plan_builder.go (hunk 7 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go]: Done
