### PR TITLE
executor: fix hash join analyze statistic when spill is triggered

### LINKED ISSUE #58571: Hash join statistic is incorrect when spill is triggered
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Trigger spill in hash join.

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

correct statistic

### 3. What did you see instead (Required)

```
+------------------------------------+--------------+-----------+-----------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+
| id                                 | estRows      | actRows   | task      | access object  | execution info | operator info | memory   | disk    |
+------------------------------------+--------------+-----------+-----------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+
| Sort_10                            | 1.00         | 5         | root      |                | time:1m15.8s, open:657.4µs, close:29.5µs, loops:2, RU:1199689.70                                                                                                                                                                                                                                                                         | test.orders.o_orderpriority                                                                                                               | 1.21 KB  | 0 Bytes |
| └─Projection_12                    | 1.00         | 5         | root      |                | time:1m15.8s, open:645.4µs, close:28.6µs, loops:5, Concurrency:OFF | test.orders.o_orderpriority, Column#26                                                                                                    | 34.0 KB  | N/A     |
|   └─HashAgg_13                     | 1.00         | 5         | root      |                | time:1m15.8s, open:641.8µs, close:27µs, loops:5, partial_worker:{wall_time:1m15.813126507s, concurrency:5, task_num:2588, tot_wait:6m18.325465785s, tot_exec:611.285923ms, tot_time:6m19.065554441s, max:1m15.813112828s, p95:1m15.813112828s}, final_worker:{wall_time:1m15.813146976s, concurrency:5, task_num:21, tot_wait:16.761µs, tot_exec:13.302µs, tot_time:6m19.065664816s, max:1m15.813135023s, p95:1m15.813135023s}                                             | group by:test.orders.o_orderpriority, funcs:count(1)->Column#26, funcs:firstrow(test.orders.o_orderpriority)->test.orders.o_orderpriority | 481.9 KB | 0 Bytes |
|     └─HashJoin_26                  | 2281928.20   | 2574425   | root      |                | time:1m15.8s, open:585.6µs, close:24.4µs, loops:2589, build_hash_table:{total:160.9ms, fetch:-7.013241164s, build:7.51s}, probe:{concurrency:5, total:3m25s, max:40.5s, probe:3.09s, fetch and wait:3m21.9s, probe_collision:19336081}                                                                                                                                                                                                                                     | semi join, left side:TableReader_29, equal:[eq(test.orders.o_orderkey, test.lineitem.l_orderkey)]                                         | 1.00 GB  | 9.45 GB |                                                                                                                                                       
|       ├─TableReader_32(Build)      | 240004648.80 | 189670348 | root      |                | time:17.3s, open:425.7µs, close:3.61µs, loops:184597, cop_task: {num: 5628, max: 309.5ms, min: 268.9µs, avg: 58.1ms, p95: 143.3ms, max_proc_keys: 80864, p95_proc_keys: 79840, tot_proc: 5m15.4s, tot_wait: 747.8ms, copr_cache_hit_ratio: 0.00, build_task_duration: 383.2µs, max_distsql_concurrency: 15}, rpc_info:{Cop:{num_rpc:5628, total_time:5m26.7s}}                                                                                                             | data:Selection_31 | 18.5 MB  | N/A     |                                                                                                                                                       
|       │ └─Selection_31             | 240004648.80 | 189670348 | cop[tikv] |                | tikv_task:{proc max:0s, min:0s, avg: 54.1ms, p80:78ms, p95:133ms, iters:315458, tasks:5628}, scan_detail: {total_process_keys: 299982707, total_process_keys_size: 58990940562, total_keys: 299988321, get_snapshot_time: 403.4ms, rocksdb: {key_skipped_count: 299982707, block: {cache_hit_count: 1883561}}}, time_detail: {total_process_time: 5m15.4s, total_suspend_time: 1.11s, total_wait_time: 747.8ms, total_kv_read_wall_time: 4m37.7s, tikv_wall_time: 5m18.8s} | lt(test.lineitem.l_commitdate, test.lineitem.l_receiptdate)                                                                               | N/A      | N/A     |                                                                                                                                                       
|       │   └─TableFullScan_30       | 300005811.00 | 300005811 | cop[tikv] | table:lineitem | tikv_task:{proc max:0s, min:0s, avg: 49.4ms, p80:71.6ms, p95:121.7ms, iters:315458, tasks:5628}                                                                                                                                                                                                                                                                                                                                                                            | keep order:false | N/A      | N/A     |
|       └─TableReader_29(Probe)      | 2852410.25   | 2807525   | root      |                | time:4.4s, open:143.5µs, close:15.2µs, loops:2734, cop_task: {num: 395, max: 1.04s, min: 214.8µs, avg: 150.6ms, p95: 658.5ms, max_proc_keys: 879577, p95_proc_keys: 871392, tot_proc: 59s, tot_wait: 54.9ms, copr_cache_hit_ratio: 0.21, build_task_duration: 81.4µs, max_distsql_concurrency: 15}, rpc_info:{Cop:{num_rpc:395, total_time:59.5s}}                                                                                                                         | data:Selection_28 | 2.08 MB  | N/A     |                                                                                                                                                       
|         └─Selection_28             | 2852410.25   | 2807525   | cop[tikv] |                | tikv_task:{proc max:1.02s, min:1ms, avg: 151.1ms, p80:291ms, p95:652ms, iters:74858, tasks:395}, scan_detail: {total_process_keys: 74173248, total_process_keys_size: 11266342171, total_keys: 74173559, get_snapshot_time: 39.4ms, rocksdb: {key_skipped_count: 74173248, block: {cache_hit_count: 376619}}}, time_detail: {total_process_time: 59s, total_suspend_time: 115.9ms, total_wait_time: 54.9ms, total_kv_read_wall_time: 54.6s, tikv_wall_time: 59.2s}         | ge(test.orders.o_orderdate, 1995-01-01 00:00:00.000000), lt(test.orders.o_orderdate, 1995-04-01 00:00:00.000000)                          | N/A      | N/A     |                                                                                                                                                       
|           └─TableFullScan_27       | 75000000.00  | 75000000  | cop[tikv] | table:orders   | tikv_task:{proc max:970ms, min:1ms, avg: 141.5ms, p80:275ms, p95:611ms, iters:74858, tasks:395} | keep order:false                                                                                                                          | N/A      | N/A     |                                                                                                                                                       
+------------------------------------+--------------+-----------+-----------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------+----------+---------+
10 rows in set (1 min 15.82 sec)
```

### 4. What is your TiDB version? (Required)

nightly(9b70321)

<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by xzhangxian1008**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

```
mysql> explain analyze select o_orderkey, o_comment, exists (select 1 from lineitem where lineitem.l_suppkey = orders.o_custkey and lineitem.l_comment = orders.o_comment and lineitem.l_comment = orders.o_comment and lineitem.l_extendedprice > orders.o_totalprice and length(lineitem.l_comment) < 20 and length(orders.o_comment) < 20) from orders;
+------------------------------+-------------+----------+-----------+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
| id                           | estRows     | actRows  | task      | access object  | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                   | operator info                                                                                                                                                                                                                                                                                                                                                 | memory    | disk    |
+------------------------------+-------------+----------+-----------+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
| HashJoin_9                   | 15000000.00 | 15000000 | root      |                | time:10.3s, open:162.6µs, close:25.9µs, loops:14672, RU:238741.11, build_hash_table:{total:7.73s, fetch:4.59s, build:204.2ms}, probe:{concurrency:5, total:10s, max:10s, probe:541.7ms, fetch and wait:9.48s, probe_collision:13992}                                                                                                                                                                                                                             | left outer semi join, left side:TableReader_11, equal:[eq(tpch10.orders.o_custkey, tpch10.lineitem.l_suppkey) eq(tpch10.orders.o_comment, tpch10.lineitem.l_comment) eq(tpch10.orders.o_comment, tpch10.lineitem.l_comment)], left cond:[lt(length(tpch10.orders.o_comment), 20)], other cond:gt(tpch10.lineitem.l_extendedprice, tpch10.orders.o_totalprice) | 1017.2 MB | 1.87 GB |
| ├─TableReader_14(Build)      | 47988841.60 | 17639868 | root      |                | time:3.43s, open:78.2µs, close:3.31µs, loops:17170, cop_task: {num: 732, max: 263.9ms, min: 204.7µs, avg: 76.5ms, p95: 185.9ms, max_proc_keys: 172000, p95_proc_keys: 170976, tot_proc: 54.3s, tot_wait: 71ms, copr_cache_hit_ratio: 0.04, build_task_duration: 47.1µs, max_distsql_concurrency: 15}, rpc_info:{Cop:{num_rpc:732, total_time:56s}}                                                                                                               | data:Selection_13                                                                                                                                                                                                                                                                                                                                             | 54.1 MB   | N/A     |
| │ └─Selection_13             | 47988841.60 | 17639868 | cop[tikv] |                | tikv_task:{proc max:246ms, min:0s, avg: 71.2ms, p80:140ms, p95:176ms, iters:61536, tasks:732}, scan_detail: {total_process_keys: 59905028, total_process_keys_size: 11747187529, total_keys: 59905732, get_snapshot_time: 41.6ms, rocksdb: {key_skipped_count: 59905028, block: {cache_hit_count: 374326}}}, time_detail: {total_process_time: 54.3s, total_suspend_time: 135.4ms, total_wait_time: 71ms, total_kv_read_wall_time: 47.5s, tikv_wall_time: 54.6s} | lt(length(tpch10.lineitem.l_comment), 20)                                                                                                                                                                                                                                                                                                                     | N/A       | N/A     |
| │   └─TableFullScan_12       | 59986052.00 | 59986052 | cop[tikv] | table:lineitem | tikv_task:{proc max:230ms, min:0s, avg: 65ms, p80:128ms, p95:161ms, iters:61536, tasks:732}                                                                                                                                                                                                                                                                                                                                                                      | keep order:false                                                                                                                                                                                                                                                                                                                                              | N/A       | N/A     |
| └─TableReader_11(Probe)      | 15000000.00 | 15000000 | root      |                | time:1.65s, open:73.5µs, close:15.2µs, loops:14668, cop_task: {num: 379, max: 235.5ms, min: 263.1µs, avg: 56.5ms, p95: 135.2ms, max_proc_keys: 50144, p95_proc_keys: 50144, tot_proc: 18.8s, tot_wait: 49.2ms, copr_cache_hit_ratio: 0.07, build_task_duration: 24.8µs, max_distsql_concurrency: 10}, rpc_info:{Cop:{num_rpc:379, total_time:21.4s}}                                                                                                             | data:TableFullScan_10                                                                                                                                                                                                                                                                                                                                         | 21.5 MB   | N/A     |
|   └─TableFullScan_10         | 15000000.00 | 15000000 | cop[tikv] | table:orders   | tikv_task:{proc max:168ms, min:0s, avg: 40.4ms, p80:53ms, p95:95ms, iters:16165, tasks:379}, scan_detail: {total_process_keys: 14932192, total_process_keys_size: 2267443679, total_keys: 14932546, get_snapshot_time: 16.8ms, rocksdb: {key_skipped_count: 14932192, block: {cache_hit_count: 77583}}}, time_detail: {total_process_time: 18.8s, total_suspend_time: 63.9ms, total_wait_time: 49.2ms, total_kv_read_wall_time: 15.2s, tikv_wall_time: 19s}      | keep order:false                                                                                                                                                                                                                                                                                                                                              | N/A       | N/A     |
+------------------------------+-------------+----------+-----------+----------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
6 rows in set (10.32 sec)
```

Issue Number: close #58571


Problem Summary:

### What changed and how does it work?

### Check List

Tests <!-- At least one of them must be included. -->

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > <!-- Or your custom  "No need to test" reasons -->

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/join/hash_join_stats.go [hunk 1]
```diff
@@ -0,0 +1,261 @@
...
+	maxProbe          int64
+	maxFetchAndProbe  int64
+
+	maxPartitionDataForCurrentRound  int64
+	maxBuildHashTableForCurrentRound int64
+	maxProbeForCurrentRound          int64
+	maxFetchAndProbeForCurrentRound  int64
+}
+
+func setMaxValue(addr *int64, currentValue int64) {
```
Comment (windtalker) [inline pkg/executor/join/hash_join_stats.go:145]: I think `setMaxFetchAndProbeTime` can be replaced by this function?

File: pkg/executor/join/hash_join_stats.go [hunk 2]
```diff
@@ -0,0 +1,261 @@
...
+
+func (e *hashJoinRuntimeStatsV2) String() string {
+	buf := bytes.NewBuffer(make([]byte, 0, 128))
+	if e.fetchAndBuildHashTable > 0 {
+		buf.WriteString("build_hash_table:{total:")
+		buf.WriteString(execdetails.FormatDuration(time.Duration(e.fetchAndBuildHashTable)))
+		buf.WriteString(", fetch:")
+		buf.WriteString(execdetails.FormatDuration(time.Duration(int64(e.fetchAndBuildHashTable) - e.maxBuildHashTable - e.maxPartitionData)))
+		buf.WriteString(", build:")
+		buf.WriteString(execdetails.FormatDuration(time.Duration(e.maxBuildHashTable)))
```
Comment (windtalker) [inline pkg/executor/join/hash_join_stats.go:198]: I think for current version, you can use `maxBuildHashTable + maxPartitionData` as the build time.

File: pkg/executor/join/hash_join_v2.go [hunk 3]
```diff
@@ -957,10 +966,7 @@ func (w *ProbeWorkerV2) runJoinWorker() {
 	if w.HashJoinCtx.stats != nil {
 		start := time.Now()
 		defer func() {
-			t := time.Since(start)
```
Comment (windtalker) [inline pkg/executor/join/hash_join_v2.go:960]: why not let `runJoinWorker` take `start` as its argument as `restoreAndProbe`

File: pkg/executor/join/hash_join_stats.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/executor/join/hash_join_stats.go:133]: > I think `setMaxFetchAndProbeTime` can be replaced by this function?

done

File: pkg/executor/join/hash_join_stats.go (hunk 2 above)
Comment (xzhangxian1008) [reply pkg/executor/join/hash_join_stats.go]: > I think for current version, you can use `maxBuildHashTable + maxPartitionData` as the build time.

done

File: pkg/executor/join/hash_join_v2.go (hunk 3 above)
Comment (xzhangxian1008) [reply pkg/executor/join/hash_join_v2.go:960]: > why not let `runJoinWorker` take `start` as its argument as `restoreAndProbe`

done

**Review by windtalker — APPROVED** [review]
lgtm

**Review by yibin87 — APPROVED** [review]
Others LGTM
