### PR TITLE
util/ranger: don't merge consecutive ranges when building ranges for cnf item

### LINKED ISSUE #41572: Optimal ranges cannot be built in some case
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t(id int, a varchar(100), b int, c int, index idx_ab(a, b));
explain select id, c from t use index (idx_ab) where ((a = 't' and b = 1) or (a = 't' and b = 2) or (a = 'w' and b = 0)) and c != 0;
```

### 2. What did you expect to see? (Required)
```
mysql> explain select id, c from t use index (idx_ab) where ((a = 't' and b = 1) or (a = 't' and b = 2) or (a = 'w' and b = 0)) and c != 0;
+---------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------------------------------------+
| id                              | estRows | task      | access object               | operator info                                                                     |
+---------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------------------------------------+
| Projection_4                    | 0.20    | root      |                             | test.t.id, test.t.c                                                               |
| └─IndexLookUp_8                 | 0.20    | root      |                             |                                                                                   |
|   ├─IndexRangeScan_5(Build)     | 0.30    | cop[tikv] | table:t, index:idx_ab(a, b) | range:["t" 1,"t" 2], ["w" 0,"w" 0], keep order:false, stats:pseudo |
|   └─Selection_7(Probe)          | 0.20    | cop[tikv] |                             | ne(test.t.c, 0)                                                                   |
|     └─TableRowIDScan_6          | 0.30    | cop[tikv] | table:t                     | keep order:false, stats:pseudo                                                    |
+---------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------------------------------------+
5 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> explain select id, c from t use index (idx_ab) where ((a = 't' and b = 1) or (a = 't' and b = 2) or (a = 'w' and b = 0)) and c != 0;
+------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| id                           | estRows | task      | access object               | operator info                                                                                                                     |
+------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Projection_4                 | 0.20    | root      |                             | test.t.id, test.t.c                                                                                                               |
| └─IndexLookUp_9              | 0.20    | root      |                             |                                                                                                                                   |
|   ├─Selection_7(Build)       | 0.20    | cop[tikv] |                             | or(and(eq(test.t.a, "t"), eq(test.t.b, 1)), or(and(eq(test.t.a, "t"), eq(test.t.b, 2)), and(eq(test.t.a, "w"), eq(test.t.b, 0)))) |
|   │ └─IndexRangeScan_5       | 20.00   | cop[tikv] | table:t, index:idx_ab(a, b) | range:["t","t"], ["w","w"], keep order:false, stats:pseudo                                                                        |
|   └─Selection_8(Probe)       | 0.20    | cop[tikv] |                             | ne(test.t.c, 0)                                                                                                                   |
|     └─TableRowIDScan_6       | 0.20    | cop[tikv] | table:t                     | keep order:false, stats:pseudo                                                                                                    |
+------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
6 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #41572 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

File: util/ranger/ranger_test.go [hunk 1]
```diff
@@ -1000,6 +1000,33 @@ func TestCompIndexMultiColDNF2(t *testing.T) {
...
+	}
+	rangerSuiteData.LoadTestCases(t, &input, &output)
+	for i, tt := range input {
+		testdata.OnRecord(func() {
+			output[i].SQL = tt
+			output[i].Plan = testdata.ConvertRowsToStrings(testKit.MustQuery("explain " + tt).Rows())
+			output[i].Result = testdata.ConvertRowsToStrings(testKit.MustQuery(tt).Rows())
+		})
+		testKit.MustQuery("explain " + tt).Check(testkit.Rows(output[i].Plan...))
+		testKit.MustQuery(tt).Check(testkit.Rows(output[i].Result...))
```
Comment (time-and-fate) [inline util/ranger/ranger_test.go:1026]: Sort the query result to make the test stable.

**Review by time-and-fate — APPROVED** [review]

File: util/ranger/ranger_test.go (hunk 1 above)
Comment (xuyifangreeneyes) [reply util/ranger/ranger_test.go]: Fixed.

**Review by hawkingrei — APPROVED** [review]
