### PR TITLE
br: add restore stats config

### LINKED ISSUE #50568: stats is not restored if --checksum=false
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. run be restore to restore a backup with stats, specify parameters --checksum=false

### 2. What did you expect to see? (Required)
br should restore stats if there is stats in backup, no matter --checksum = true or false.

### 3. What did you see instead (Required)
stats is not restored if --checksum = false

### 4. What is your TiDB version? (Required)
v7.6.0

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #50568

Problem Summary:
BR cannot load statistic data when it doesn't do checksum
### What changed and how does it work?
add new parameter `load-stats` for load stats
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
add `load-stats` parameter to enable br to skip restore statistic data.
```

### CODE REVIEW

File: br/pkg/task/common.go [hunk 1]
```diff
@@ -274,6 +276,7 @@ func DefineCommonFlags(flags *pflag.FlagSet) {
 
 	flags.Uint64(flagRateLimit, unlimited, "The rate limit of the task, MB/s per node")
 	flags.Bool(flagChecksum, true, "Run checksum at end of task")
+	flags.Bool(flagLoadStats, true, "Run load stats at end of task")
```
Comment (YuJuncen) [inline br/pkg/task/common.go:279]: You may need to add this in the expected config in `TestDefaultRestore`.

**Review by YuJuncen — APPROVED** [review]
lgtm

**Review by 3pointer — APPROVED** [review]
