### PR TITLE
planner: refactor buildPhysicalIndexLookUpReader for admin check

### LINKED ISSUE #19091: `admin check table` reports 'data is corrupted' when using clustered index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set @@tidb_enable_clustered_index=1;
drop table if exists t;
-- init
create table t ( c_int int, c_str varchar(40), c_datetime datetime, c_timestamp timestamp, c_double double, c_decimal decimal(12, 6) , primary key(c_int, c_str) , key(c_int), key(c_datetime));
insert into t values (1, 'great hermann', '2020-05-14 18:23:55', '2020-04-10 17:16:43', 96.921865, 7.211);
admin check table t; -- Data is corrupted, missing data for NOT NULL column
```

### 2. What did you expect to see? (Required)

No error should be reported by `admin check table`

### 3. What did you see instead (Required)

```
mysql> admin check table t;
ERROR 1105 (HY000): [components/tidb_query_vec_executors/src/table_scan_executor.rs:371]: Data is corrupted, missing data for NOT NULL column (offset = 0)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-921-gb75a30fda
Edition: Community
Git Commit Hash: b75a30fda8eef5962e2fde1c6254ff02f330fd21
Git Branch: master
UTC Build Time: 2020-08-09 02:54:26
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #19091 

Problem Summary:
Normally, the TiKV decoder assumes there are no duplicate columns in the plan schema. However, in the case of the common handle columns with secondary index covered, it is possible to have duplicate columns during 'admin check table'.

We need to deduplicate these columns.

### What is changed and how it works?

What's Changed:
- Refactor `buildPhysicalIndexLookUpReader` for better readability.
- Deduplicate table scan schema columns.

How it Works: Omitted.

### Related changes

N/A

### Check List 

Tests 

This issue only occurs when the storage is TiKV(store=tikv).

- Manual test (add detailed scripts or steps below)
```sql
tiup playground --tiflash 0 --db.binpath ./tidb-server --kv 1 --kv.binpath ./tikv-server

# connect with MySQL client
set @@tidb_enable_clustered_index=1;
drop table if exists t;
-- init
create table t ( c_int int, c_str varchar(40), c_datetime datetime, c_timestamp timestamp, c_double double, c_decimal decimal(12, 6) , primary key(c_int, c_str) , key(c_int), key(c_datetime));
insert into t values (1, 'great hermann', '2020-05-14 18:23:55', '2020-04-10 17:16:43', 96.921865, 7.211);
admin check table t;
```

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: planner/core/planbuilder.go [hunk 1]
```diff
@@ -1151,100 +1151,161 @@ func FindColumnInfoByID(colInfos []*model.ColumnInfo, id int64) *model.ColumnInf
...
-		pkOffsets = pkOffsets[:0]
-		pk := tables.FindPrimaryIndex(tblInfo)
-		commonHandleCols, _ = expression.IndexInfo2Cols(tblInfo.Columns, fullExprCols.Columns, pk)
-		for _, c := range commonHandleCols {
-			ts.schema.Append(c)
-		}
-		for _, c := range tables.TryGetCommonPkColumns(tbl) {
-			ts.Columns = append(ts.Columns, c.ColumnInfo)
+	switch {
+	case hasCommonCols:
```
Comment (coocood) [inline planner/core/planbuilder.go:1183]: Why not use `if`?

**Comment by coocood** [comment]
LGTM

**Review by crazycs520 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
