### PR TITLE
planner: fill missing origin table name for `DEFAULT()` function

### LINKED ISSUE #12471: Unexpect error when use `default` function in expression of generated column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table t1(a int default 9, b int as (default(a)));
insert into t1 values(1, default);
select * from t1;
```

2. What did you expect to see?
image

3. What did you see instead?
image

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v4.0.0-alpha-341-g0df9bb7b8-dirty
```

### PR DESCRIPTION
**Pull request by Deardrops**
### What problem does this PR solve? 
Fix #12471, #13189, #13390

### What is changed and how it works?

The reason why we get the unexpect error `Field (a) doesn't have a default value` is that we missing the origin table name when rewrite the expression contains `DEFAULT()` function.

In detail, when we assign value to column `a` by `set a = default(b)`, TiDB will rewrite the assignment expression `default(b)`. When it execute to `evalDefaultExpr`, It will do some check:

https://github.com/pingcap/tidb/blob/41ac571d7b0e333f7b8fc061726b598eddb3825c/planner/core/expression_rewriter.go#L1508-L1514

If the `OrigTblName` in `logicalplan.Schema` is empty, TiDB think the column 
 name referenced by `DEFAULT()` function is not a real column name (it's an `AsName`), so it throw the error `Field (a) doesn't have a default value`.

To resolve this issue, we should fill the missing origin table name when build the logicPlan, after that, rewrite the assignment expression.

Another issue is TiDB cannot get the column name of subquery's subquery (#13390).To resolve this issue, we should keep the original table name of the subquery as far as possible. When `buildResultNode()`, if the `origTableName` in logic plan is not empty, we should keep it. otherwise, we should replace the empty `origTableName` by the `tableName`.

### Check List 

Tests 

 - Integration test

Side effects

 - Possible performance regression

### CODE REVIEW

**Comment by winoros** [comment]
In TiDB
```
mysql> show create table t1;
+-------+-------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                |
+-------+-------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `f1` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
mysql> select default(f1) from (select * from (select * from (select 1) f1) f1) f1;
ERROR 1054 (42S22): Unknown column 'f1' in 'field list'
mysql> select default(f1) from (select * from (select * from (select 1 as f1) t1) t1) t1;
+-------------+
| default(f1) |
+-------------+
|        NULL |
+-------------+
1 row in set (0.00 sec)

mysql> select default(f2) from (select * from (select * from (select 1 as f2) t1) t1) t1;
ERROR 1054 (42S22): Unknown column 'f2' in 'field_list'
mysql> select f2 from (select * from (select * from (select 1 as f2) t1) t1) t1;
+----+
| f2 |
+----+
|  1 |
+----+
1 row in set (0.00 sec)
```

In MySQL
```
mysql> select default(c1) from (select * from (select * from (select 1 as c1) t1) t1) t1;
+-------------+
| default(c1) |
+-------------+
|           0 |
+-------------+
1 row in set (0.00 sec)
mysql> select default(c2) from (select * from (select * from (select 1 as c2) t1) t1) t1;
+-------------+
| default(c2) |
+-------------+
|           0 |
+-------------+
1 row in set (0.00 sec)
```

**Comment by winoros** [comment]
Also, if there's a table `create table t2(f1 int(11) default 11);`
And you run `select default(f1) from (select * from (select * from (select * from t2) t1) t1) t1;`
In TiDB, it would be `NULL` while MySQL is `1`.

**Comment by Deardrops** [comment]
This PR need more discussion, The time is not ripe. So we close it.

**Comment by Deardrops** [comment]
This PR need more discussion, The time is not ripe. So we close it.

**Comment by Deardrops** [comment]
```sql
create table t2(f1 int(11) default 11);
select default(f1) from (select * from t2) t1; # <-- 11
select default(f1) from (select * from (select * from t2) t1 ) t1; # <-- Error 1146: Table 'test.t1' doesn't exist
```

**Comment by XuHuaiyu** [comment]
@Deardrops Is this PR ready to be reviewed?

**Comment by Deardrops** [comment]
> @Deardrops Is this PR ready to be reviewed?

Sorry, I'm still working on adding more test. Removing the `PTAL` label.

**Comment by Deardrops** [comment]
@XuHuaiyu @winoros This PR is ready for review now, PTAL

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -193,7 +193,9 @@ func (b *PlanBuilder) buildResultSetNode(ctx context.Context, node ast.ResultSet
 			if name.Hidden {
 				continue
 			}
-			name.OrigTblName = name.TblName
+			if name.OrigTblName.L == "" {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go]: Do we really need this if branch?
I think if the resultSet is a virtual table. We don't need set the original table name.

Comment (winoros) [inline planner/core/logical_plan_builder.go]: If we set it here.
Still use `create table t4(a int default 4)`.
We would get `select default(a) from (select a from (select 1 as a) t4) t4;`'s result is `4` instead of `0`.

Comment (winoros) [reply planner/core/logical_plan_builder.go]:
```
mysql> select default(a) from (select a from (select 1 as a) t3) t4;
Field   1:  `default(a)`
Catalog:    `def`
Database:   ``
Table:      `t3`
Org_table:  ``
Type:       LONG
Collation:  binary (63)
Length:     1
Max_length: 1
Decimals:   0
Flags:      NOT_NULL NUM
```
In MySQL, it also doesn't set it if it's a virtual table.
It makes sense.

Comment (Deardrops) [reply planner/core/logical_plan_builder.go]: @winoros Comment addressed, PTAL

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -189,11 +189,19 @@ func (b *PlanBuilder) buildResultSetNode(ctx context.Context, node ast.ResultSet
 			return nil, err
 		}
 
+		_, isVirtualTable := p.(*LogicalProjection)
 		for _, name := range p.OutputNames() {
 			if name.Hidden {
 				continue
 			}
-			name.OrigTblName = name.TblName
+			if !isVirtualTable {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go]: I think we just don't change the original table name here is okay?

Comment (Deardrops) [reply planner/core/logical_plan_builder.go]: @winoros Comment addressed, PTAL

File: planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -687,19 +686,23 @@ func (b *PlanBuilder) buildSelection(ctx context.Context, p LogicalPlan, where a
 
 // buildProjectionFieldNameFromColumns builds the field name, table name and database name when field expression is a column reference.
 func (b *PlanBuilder) buildProjectionFieldNameFromColumns(origField *ast.SelectField, colNameField *ast.ColumnNameExpr, name *types.FieldName) (colName, origColName, tblName, origTblName, dbName model.CIStr) {
-	origColName, tblName, dbName = colNameField.Name.Name, colNameField.Name.Table, colNameField.Name.Schema
-	if origField.AsName.L != "" {
-		colName = origField.AsName
+	origTblName, dbName = name.OrigTblName, name.DBName
+	if name.OrigColName.L == "" {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go]: if we set original column here https://github.com/pingcap/tidb/pull/https://github.com/pingcap/tidb/blob/3ebc09631dbc700100f1c30617878f7c6c46c888/planner/core/logical_plan_builder.go#diff-5f46fc7e65bc1be2746caf2464f58d13L616
do we still need this if branch here?

Comment (Deardrops) [reply planner/core/logical_plan_builder.go]: @winoros comment addressed, PTAL

Comment (Deardrops) [reply planner/core/logical_plan_builder.go]: Yes, `ColumnInfos2ColumnsAndNames` function is called when build insert plan, while
`buildProjectionFieldNameFromColumns` function is called when build select plan.
if we do not set `OrigTblName` in `ColumnInfos2ColumnsAndNames`, this SQL will throw an error:
```
create table t1(a int primary key, b int default 20, c int default 30);
insert into t1 set a = 1, b = default(c); # <--[table:1364]Field 'c' doesn't have a default value
```

**Comment by Deardrops** [comment]
@winoros thanks~
