### PR TITLE
statistics: BinarySearchRemoveVal should use decoded val instead of encoded

### LINKED ISSUE #59130: wrong stats of TestIssues24349
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Image

Looking into column `b`'s stats:
- partition `p0`: TopN: (3, 3). Hist: one bucket  [2, 2] with count = 1
- partition `p1`: TopN: (2, 3), Hist: empty
- partition `p2`: TopN: (1, 2), Hist: two buckets [1, 3] with count = 2 and repeat = 1, [4, 4] with count = 1 and repeat = 1

After fixing the global TopN, it is now 2 with 4 as its occurrence (local TopN of `p1` and one single bucket from `p0`).

Remained buckets(TopN also treat as bucket)
- [3, 3] count = 4, repeat = 4 (local TopN from `p0` plus 1 from `p2`'s bucket [1, 3]'s repeat)
- [1, 1] count = 2, repeat = 2
- [1, 3] count = 1, repeat = 0
- [4, 4] count = 1, repeat = 1

After merging them to get the global histogram, we should get one bucket [1, 4] with count = 8 and repeat = 1.
But in the current test result, we have

Image
The count is ***10***.

### 4. What is your TiDB version? (Required)

master.

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #59130 

Problem Summary:

### What changed and how does it work?

The function used the wrong val as its parameter.
As a result, when the column is not string type. The function `BinaryRemoveVal` actually removes nothing.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
修复合并全局统计信息时，直方图构造结果可能变大的问题
Fix the issue that the global histogram might be larger than expected when merging partition table's global statistics.
```

### CODE REVIEW

File: pkg/statistics/histogram_test.go [hunk 1]
```diff
@@ -712,21 +712,3 @@ func generateData(t *testing.T) *Histogram {
...
-	require.Equal(t, data1, data2)
-	ctx := mock.NewContext()
-	sc := ctx.GetSessionVars().StmtCtx
-	b, err := codec.EncodeKey(sc.TimeZone(), nil, types.NewIntDatum(150))
-	require.NoError(t, err)
-	tmp := TopNMeta{
-		Encoded: b,
-		Count:   2,
-	}
-	data1.RemoveVals([]TopNMeta{tmp})
```
Comment (winoros) [inline pkg/statistics/histogram_test.go:729]: The `RemoveVals` is actually the wrong one. 
But, now that it is only used in stats v1.
I decide not to change it.

**Review by hawkingrei — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

File: pkg/statistics/histogram_test.go (hunk 1 above)
Comment (AilinKid) [reply pkg/statistics/histogram_test.go:729]: decide to remove it?
