### PR TITLE
executor: fix unstable TestCoprocessorOOMAction

### LINKED ISSUE #19677: executor_test.go:testSuite.TestCoprocessorOOMAction failed
executor_test.go:testSuite.TestCoprocessorOOMAction

```
[2020-09-01T11:39:26.714Z] ----------------------------------------------------------------------
[2020-09-01T11:39:26.714Z] FAIL: executor_test.go:6270: testSuite.TestCoprocessorOOMAction
[2020-09-01T11:39:26.714Z]
[2020-09-01T11:39:26.714Z] executor_test.go:6293:
[2020-09-01T11:39:26.714Z]     tk.MustQuery("select * from t5").Sort().Check(testkit.Rows(expect...))
[2020-09-01T11:39:26.714Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:312:
[2020-09-01T11:39:26.714Z]     tk.c.Check(err, check.IsNil, comment)
[2020-09-01T11:39:26.714Z] ... value *errors.fundamental = Out Of Memory Quota![conn_id=172] ("Out Of Memory Quota![conn_id=172]")
[2020-09-01T11:39:26.714Z] ... sql:select * from t5, args:[]
```

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/47585/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/49014/display/redirect

### LINKED ISSUE #20171: test: TestCoprocessorOOMAction unstable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/52307/pipeline/

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve?

Issue Number: close #19677 

For asserting OOMAction in `TestCoprocessorOOMAction`, the testcase for the non keep-order is unstable as the `quota` might be not enough to support the whole query processing.

What's Changed:
Mock the consume data to make `TestCoprocessorOOMAction` stable.

How it Works:

- Unit test

Side effects

### Release note 

* No release note

### CODE REVIEW

**Comment by Yisaer** [comment]
@wshwsh12 @XuHuaiyu  PTAL

**Review by wshwsh12 — COMMENTED** [review]
lgtm

File: store/tikv/coprocessor.go [hunk 1]
```diff
@@ -570,8 +570,8 @@ func (it *copIterator) open(ctx context.Context) {
 		sendRate: it.sendRate,
 	}
 	taskSender.respChan = it.respChan
-	go taskSender.run()
 	it.actionOnExceed.setEnabled(true)
+	go taskSender.run()
 }
```
Comment (Yisaer) [inline store/tikv/coprocessor.go:575]: We should enable action before sending task, otherwise the worker may meet OOM Action when rateLimitAction haven't been enabled.

**Comment by XuHuaiyu** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
