### PR TITLE
planner: fix LogicalPlans that contain Window Function are ambiguous 

### LINKED ISSUE #22852: LogicalPlans that contain Window Function are ambiguous
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. add test case in `planner/cascades/transformation_rules_test.go`. The number of iterations can be greater than 100 :
```
func (s *testTransformationRuleSuite) TestWindowLogicalPlan(c *C) {
	s.optimizer.ResetTransformationRules(map[memo.Operand][]Transformation{
		memo.OperandProjection: {
			NewRuleMergeAdjacentProjection(),
			NewRuleEliminateProjection(),
		},
	})
	defer func() {
		s.optimizer.ResetTransformationRules(DefaultRuleBatches...)
	}()
	input := "select a, max(a) over(), sum(a) over() from t"
	output1 := "DataScan(t)->Projection->Projection->Window(max(test.t.a)->Column#15)->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#16)->Projection"
	output2 := "DataScan(t)->Projection->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#15)->Projection->Window(max(test.t.a)->Column#16)->Projection"
	hasOut1 := false
	hasOut2 := false
	for i := 0; i < 100; i++ {
		stmt, err := s.ParseOneStmt(input, "", "")
		c.Assert(err, IsNil)
		p, _, err := plannercore.BuildLogicalPlan(context.Background(), s.sctx, stmt, s.is)
		str := plannercore.ToString(p)
		if str == output1{
			hasOut1 = true
		}
		if str == output2{
			hasOut2 = true
		}
	}
	fmt.Println(hasOut1, hasOut2)
}
```
2. execute `go test -check.f "testTransformationRuleSuite.TestWindowLogicalPlan"`  in path `planner/cascades`

### 2. What did you expect to see? (Required)
sql `select a, max(a) over(), sum(a) over() from t` should be built into only one LogicalPlan.
> go test -check.f "testTransformationRuleSuite.TestWindowLogicalPlan"
> false true
> PASS: transformation_rules_test.go:528: testTransformationRuleSuite.TestWindowLogicalPlan       0.011s
> OK: 1 passed
> PASS
> ok      github.com/pingcap/tidb/planner/cascades        0.132s
### 3. What did you see instead (Required)
sql `select a, max(a) over(), sum(a) over() from t`  is built into two different LogicalPlans.
> go test -check.f "testTransformationRuleSuite.TestWindowLogicalPlan"
> true true
> PASS: transformation_rules_test.go:528: testTransformationRuleSuite.TestWindowLogicalPlan       0.011s
> OK: 1 passed
> PASS
> ok      github.com/pingcap/tidb/planner/cascades        0.132s
### 4. What is your TiDB version? (Required)
code in branch master.

### PR DESCRIPTION
**Pull request by An-DJ**
### What problem does this PR solve?

Issue Number: close #22852

Problem Summary:

### What is changed and how it works?

Proposal: update file `planner\cascades\logical_plan_builder.go`

What's Changed: 
make `PlanBuilder.buildWindowFunctions()` build window function into only one LogicalPlan.

function `logical_plan_builder.go/sortWindowSpecs()` is used to sorts window specifications to reduce `Sort` operator in future. But the order of it are ambiguous because `map` is not guaranteed in order.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
add test case in planner/cascades/transformation_rules_test.go :
```
func (s *testTransformationRuleSuite) TestWindowLogicalPlan(c *C) {
	s.optimizer.ResetTransformationRules(map[memo.Operand][]Transformation{
		memo.OperandProjection: {
			NewRuleMergeAdjacentProjection(),
			NewRuleEliminateProjection(),
		},
	})
	defer func() {
		s.optimizer.ResetTransformationRules(DefaultRuleBatches...)
	}()
	input := "select a, max(a) over(), sum(a) over() from t"
	output1 := "DataScan(t)->Projection->Projection->Window(max(test.t.a)->Column#15)->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#16)->Projection"
	output2 := "DataScan(t)->Projection->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#15)->Projection->Window(max(test.t.a)->Column#16)->Projection"
	hasOut1 := false
	hasOut2 := false
	for i := 0; i < 100; i++ {
		stmt, err := s.ParseOneStmt(input, "", "")
		c.Assert(err, IsNil)
		p, _, err := plannercore.BuildLogicalPlan(context.Background(), s.sctx, stmt, s.is)
		str := plannercore.ToString(p)
		if str == output1{
			hasOut1 = true
		}
		if str == output2{
			hasOut2 = true
		}
	}
	fmt.Println(hasOut1, hasOut2)
}
```
Execute `go test -check.f "testTransformationRuleSuite.TestWindowLogicalPlan" in path planner/cascades`. The output must be
> go test -check.f "testTransformationRuleSuite.TestWindowLogicalPlan"
> false true
> PASS: transformation_rules_test.go:528: testTransformationRuleSuite.TestWindowLogicalPlan 0.011s
> OK: 1 passed
> PASS
> ok github.com/pingcap/tidb/planner/cascades 0.132s

### Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by An-DJ** [comment]
This bug does not involve cascades. It could be more concise like this:
```
func (s *testTransformationRuleSuite) TestWindowLogicalPlan(c *C) {
	input := "select a, max(a) over(), sum(a) over() from t"
	output1 := "DataScan(t)->Projection->Projection->Window(max(test.t.a)->Column#15)->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#16)->Projection"
	output2 := "DataScan(t)->Projection->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#15)->Projection->Window(max(test.t.a)->Column#16)->Projection"
	hasOut1 := false
	hasOut2 := false
	for i := 0; i < 100; i++ {
		stmt, err := s.ParseOneStmt(input, "", "")
		c.Assert(err, IsNil)
		p, _, err := plannercore.BuildLogicalPlan(context.Background(), s.sctx, stmt, s.is)
		str := plannercore.ToString(p)
		if str == output1{
			hasOut1 = true
		}
		if str == output2{
			hasOut2 = true
		}
	}
	fmt.Println(hasOut1, hasOut2)
}
```

**Comment by An-DJ** [comment]
how is it going? @hanfei1991

**Review by winoros — COMMENTED** [review]
could you add some tests, others LGTM

**Review by winoros — COMMENTED** [review]
could you add some tests, others LGTM

**Comment by An-DJ** [comment]
> could you add some tests, others LGTM

ok,

**Comment by An-DJ** [comment]
> could you add some tests, others LGTM

I add unit tests to test whether WindowLogicalPlan is ambiguous just now. The ambiguous logical plan which contains window function can usually be found in 100 iterations.

before:
```
~ go test -check.f "testPlanSuite.TestWindowLogicalPlanAmbiguous"

----------------------------------------------------------------------
FAIL: logical_plan_test.go:1749: testPlanSuite.TestWindowLogicalPlanAmbiguous

logical_plan_test.go:1761:
    c.Assert(planString, Equals, ToString(p))
... obtained string = "DataScan(t)->Projection->Projection->Window(max(test.t.a)->Column#15)->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#16)->Projection"
... expected string = "DataScan(t)->Projection->Projection->Window(sum(cast(test.t.a, decimal(65,0) BINARY))->Column#15)->Projection->Window(max(test.t.a)->Column#16)->Projection"

OOPS: 0 passed, 1 FAILED
--- FAIL: TestT (0.01s)
FAIL
exit status 1
FAIL    github.com/pingcap/tidb/planner/core    0.149s
```
after:
```
~ go test -check.f "testPlanSuite.TestWindowLogicalPlanAmbiguous"
PASS: logical_plan_test.go:1749: testPlanSuite.TestWindowLogicalPlanAmbiguous   0.008s
OK: 1 passed
PASS
ok      github.com/pingcap/tidb/planner/core    0.142s
```

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -5111,10 +5111,10 @@ type windowFuncs struct {
 
 // sortWindowSpecs sorts the window specifications by reversed alphabetical order, then we could add less `Sort` operator
 // in physical plan because the window functions with the same partition by and order by clause will be at near places.
-func sortWindowSpecs(groupedFuncs map[*ast.WindowSpec][]*ast.WindowFuncExpr) []windowFuncs {
+func sortWindowSpecs(groupedFuncs map[*ast.WindowSpec][]*ast.WindowFuncExpr, orderedSpec []*ast.WindowSpec) []windowFuncs {
 	windows := make([]windowFuncs, 0, len(groupedFuncs))
-	for spec, funcs := range groupedFuncs {
-		windows = append(windows, windowFuncs{spec, funcs})
+	for _, spec := range orderedSpec {
+		windows = append(windows, windowFuncs{spec, groupedFuncs[spec]})
```
Comment (eurekaka) [inline planner/core/logical_plan_builder.go:5117]: Can we just modify https://github.com/pingcap/tidb/pull/22853/files#diff-3b47fd3bf2c33ae3a03037a65ed39df33a4ae73debe9cf6f5bb2f397508061a0R5121 to make this order stable?

Comment (An-DJ) [reply planner/core/logical_plan_builder.go:5117]: > Can we just modify https://github.com/pingcap/tidb/pull/22853/files#diff-3b47fd3bf2c33ae3a03037a65ed39df33a4ae73debe9cf6f5bb2f397508061a0R5121 to make this order stable?

@eurekaka The previous author wanted to use `sort.SliceStable` to sort spec stably. If 2 specs are the same, the order is the only which relies on input order of the 2. Unfortunately, the input order cannot be guaranteed because of the `map` implementation in `Golang`.

Comment (An-DJ) [reply planner/core/logical_plan_builder.go:5117]: @eurekaka U can check unit test case below for more details.

**Review by eurekaka — APPROVED** [review]
/lgtm
