### PR TITLE
executor: fix mysql_insert_id() for "INSERT .. ON DUPLICATE KEY" statement

### LINKED ISSUE #55965: mysql_insert_id() incompatible between tidb and mysql
### 1. Minimal reproduce step (Required)

```go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/go-sql-driver/mysql"
)

func executeSQL(db *sql.DB, sql string) sql.Result {

	result, err := db.Exec(sql)
	if err != nil {
		log.Fatal("Error executing query:", err)
	}
	return result
}

func insertRow(db *sql.DB, a, b int) int {

	insertQuery := "INSERT INTO tb (a, b) VALUES (?, ?) ON DUPLICATE KEY UPDATE b = VALUES(b)"
	result, err := db.Exec(insertQuery, a, b)
	if err != nil {
		log.Fatal("Error executing insert query:", err)
	}

	// Get the last inserted ID
	lastInsertId, err := result.LastInsertId()
	if err != nil {
		log.Fatalf("Error fetching LastInsertId: %v", err)
	}

	return int(lastInsertId)
}

func main() {
	// Define the MySQL connection string
	dsn := "root@tcp(127.0.0.1:4000)/test"
    //dsn := "root@tcp(127.0.0.1:3306)/test"

	// Open a connection to the database
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("Error opening database connection: %v", err)
	}
	defer db.Close()

	// Test the connection
	err = db.Ping()
	if err != nil {
		log.Fatalf("Error connecting to the database: %v", err)
	}

	_ = executeSQL(db, "drop table if exists tb")

	_ = executeSQL(db, "create table tb(pk int primary key auto_increment, a int, b int, unique(a))")

	lastInsertId := insertRow(db, 1, 1)
	fmt.Printf("Last inserted ID: %d\n", lastInsertId)

	lastInsertId = insertRow(db, 2, 2)
	fmt.Printf("Last inserted ID: %d\n", lastInsertId)

	lastInsertId = insertRow(db, 1, 2)
	fmt.Printf("Last inserted ID: %d\n", lastInsertId)

}


// tiup playground v7.5.1:
// Last inserted ID: 1
// Last inserted ID: 2
// Last inserted ID: 0

// MySQL v8.0.23:
// Last inserted ID: 1
// Last inserted ID: 2
// Last inserted ID: 1
```

### 2. What did you expect to see? (Required)

The code should return same result from mysql and tidb

### 3. What did you see instead (Required)

// tiup playground v7.5.1:
// Last inserted ID: 1
// Last inserted ID: 2
// Last inserted ID: 0

// MySQL v8.0.23:
// Last inserted ID: 1
// Last inserted ID: 2
// Last inserted ID: 1

### 4. What is your TiDB version? (Required)

```sql
mysql> select @@version;
+--------------------+
| @@version          |
+--------------------+
| 8.0.11-TiDB-v7.5.1 |
+--------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #55965 

Problem Summary:

### What changed and how does it work?

Handle the value correctly for `mysql_insert_id()` when duplicate update happen in the "INSERT .. ON DUPLICATED UPDATE"  statement.

In the code internally, we use `InsertID` when the value auto increment column is specified explicitly.
And use `LastInsertID` when the value of  auto increment column is auto generated.

```
	// PrevLastInsertID is the last insert ID of previous statement.
	PrevLastInsertID uint64
	// LastInsertID is the auto-generated ID in the current statement.
	LastInsertID uint64
	// InsertID is the given insert ID of an auto_increment column.
	InsertID uint64
```

The different between `mysql_insert_id()` and `LAST_INSERT_ID()` is that the former get its value either from auto generated or explicitly specified, while the later just update the value in the auto generated cases.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

See the steps descriped in the issue

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/insert.go [hunk 1]
```diff
@@ -478,6 +483,13 @@ func (e *InsertExec) doDupRowUpdate(ctx context.Context, handle kv.Handle, oldRo
 	if err != nil {
 		return err
 	}
+
+	if autoColIdx >= 0 && e.Ctx().GetSessionVars().StmtCtx.AffectedRows() > 0 {
```
Comment (lcwangchao) [inline pkg/executor/insert.go:487]: Why use `e.Ctx().GetSessionVars().StmtCtx.AffectedRows() > 0` ?

Comment (tiancaiamao) [reply pkg/executor/insert.go:487]: Table tb with data:
pk  a   b
1   1   1

Execute this statement:
insert into tb (a, b) values (1, 2)  on duplicate key update b = 1

mysql_insert_id() should be 0 rather than 1, 
that is why we need check AffectedRows() > 0

**Review by jackysp — APPROVED** [review]
LGTM

**Review by lcwangchao — APPROVED** [review]
