### PR TITLE
planner: push necessary predicates without virtual column down through UnionScan

### LINKED ISSUE #54870: planner: can't push down predicates with generated columns down through UnionScan
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t (
    ->     id int,
    ->     `deleted_at` datetime(3) NOT NULL DEFAULT '1970-01-01 01:00:01.000',
    ->     `is_deleted` tinyint(1) GENERATED ALWAYS AS ((`deleted_at` > _utf8mb4'1970-01-01 01:00:01.000')) VIRTUAL NOT NULL,
    ->     key k(id, is_deleted)
    -> );
Query OK, 0 rows affected (0.02 sec)

mysql> 
mysql> begin;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t (id, deleted_at) values (1, now());
Query OK, 1 row affected (0.00 sec)

mysql> explain select 1 from t where id=1 and is_deleted=true;
+------------------------------+----------+-----------+----------------------------------+--------------------------------------------+
| id                           | estRows  | task      | access object                    | operator info                              |
+------------------------------+----------+-----------+----------------------------------+--------------------------------------------+
| Projection_5                 | 8000.00  | root      |                                  | 1->Column#5                                |
| └─Selection_6                | 8000.00  | root      |                                  | eq(test.t.id, 1), eq(test.t.is_deleted, 1) |
|   └─UnionScan_7              | 10000.00 | root      |                                  |                                            |
|     └─IndexReader_12         | 10000.00 | root      |                                  | index:IndexFullScan_11                     |
|       └─IndexFullScan_11     | 10000.00 | cop[tikv] | table:t, index:k(id, is_deleted) | keep order:false, stats:pseudo             |
+------------------------------+----------+-----------+----------------------------------+--------------------------------------------+
5 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

The plan should use `IndexRangeScan`.

### 3. What did you see instead (Required)

`IndexFullScan`

### 4. What is your TiDB version? (Required)

47179ae14d6bb7947d8857b4e8c91212bce999aa

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #54870

Problem Summary: planner: push necessary predicates without virtual column down through UnionScan

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/integration_test.go [hunk 1]
```diff
@@ -2237,6 +2237,20 @@ func TestIssue54213(t *testing.T) {
...
+	tk := testkit.NewTestKit(t, store)
+
+	tk.MustExec("use test")
+	tk.MustExec(`create table t (id int,
+deleted_at datetime(3) NOT NULL DEFAULT '1970-01-01 01:00:01.000',
+is_deleted tinyint(1) GENERATED ALWAYS AS ((deleted_at > _utf8mb4'1970-01-01 01:00:01.000')) VIRTUAL NOT NULL,
+key k(id, is_deleted))`)
+	tk.MustExec(`begin`)
+	tk.MustExec(`insert into t (id, deleted_at) values (1, now())`)
+	tk.MustHavePlan(`select 1 from t where id=1 and is_deleted=true`, "IndexRangeScan")
```
Comment (AilinKid) [inline pkg/planner/core/integration_test.go:2251]: Does this txn need to be rolled back or committed here?

**Review by AilinKid — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
