### PR TITLE
planner, executor, parser: implement scoped FLUSH STATS_DELTA

### LINKED ISSUE #66888: Support object-scoped FLUSH STATS_DELTA with REFRESH STATS privilege semantics
## Enhancement

`FLUSH STATS_DELTA` currently inherits the generic `FLUSH -> RELOAD` privilege check. That is unreasonable.

We should support explicit object scopes for `FLUSH STATS_DELTA`, aligned with `REFRESH STATS`, so users can flush pending deltas only for objects they are allowed to operate on.

Suggested permission rules:
- `FLUSH STATS_DELTA db.tbl`: require `SELECT` on `db.tbl`
- `FLUSH STATS_DELTA db.*`: require `SELECT` on `db`
- `FLUSH STATS_DELTA *.*`: require global `SELECT`

What needs to be done:
- extend parser/AST to accept explicit objects for `FLUSH STATS_DELTA`
- add planner privilege derivation for object-scoped `FLUSH STATS_DELTA` instead of inheriting generic `FLUSH -> RELOAD`
- limit delta flushing in executor/stats handle to the requested scope
- add regression tests for privilege checks and scoped flush behavior

### PR DESCRIPTION
**Pull request by 0xPoe**
### What problem does this PR solve?

Issue Number: close #66888

Problem Summary:
Complete scoped `FLUSH STATS_DELTA` after #67728 by adding scoped privilege checks and scoped delta flushing.

### What changed and how does it work?

- derive `SELECT` privileges for `FLUSH STATS_DELTA db.tbl`, `db.*`, and `*.*`
- fill the default DB and deduplicate scoped objects like `REFRESH STATS`
- flush only the requested table / schema / global scope
- expand partitioned tables to physical partition IDs
- support remote execution for `FLUSH STATS_DELTA ... CLUSTER`
- add regression tests for privilege checks and scoped flush behavior

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/release-notes-style-guide.html) to write a quality release note.

```release-note
`FLUSH STATS_DELTA` now enforces scoped `SELECT` privileges and flushes only the requested table or schema, including partitioned tables.
```

## Summary by CodeRabbit

* **New Features**
  * FLUSH STATS DELTA supports targeted flushing for table, database, and global scopes, with partition-aware targeting and deduplication (global overrides narrower selectors).

* **Bug Fixes / Improvements**
  * Improved validation, clearer error/logging for invalid scopes, restore/broadcast, and stricter privilege enforcement; bare-table calls now require a default database.

* **Tests**
  * Expanded tests covering scoped behavior, privilege scenarios, deduplication, restore formatting, and bare-table error handling.

### CODE REVIEW

File: pkg/planner/core/planbuilder.go [hunk 1]
```diff
@@ -3671,6 +3671,14 @@ func (b *PlanBuilder) buildSimple(ctx context.Context, node ast.StmtNode) (base.
 
 	switch raw := node.(type) {
 	case *ast.FlushStmt:
+		if raw.Tp == ast.FlushStatsDelta {
```
Comment (0xPoe) [inline pkg/planner/core/planbuilder.go:3674]: I think it is a bit awkward to include it in the flush statement. Perhaps we should consider adding FlushStatsDeltaStmt. I would appreciate some input on this. I don't have strong opinions, but I do feel it is awkward.

If we want to add a dedicated one, I think we can do it in the next PR to avoid making this PR too big.

**Review by 0xPoe — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback)

- [x] Code compiles successfully

- [x] Unit tests added

- [x] No AI-generated elegant nonsense in PR.

- [x] Bazel files updated

- [x] Comments added where necessary

- [x] PR title and description updated

- [x] Documentation PR created (or confirmed not needed)

- [x] PR size is reasonable


/cc @qw4990 @henrybw

**Review by terry1purcell — APPROVED** [review]

File: pkg/planner/core/planbuilder.go (hunk 1 above)
Comment (henrybw) [reply pkg/planner/core/planbuilder.go:3674]: Definitely agree that we shouldn't expand scope for this PR, and just keep FlushStatsDelta as part of FlushStmt for now.

I don't have a strong opinion either, but I do think that, if we want to add a separate FlushStatsDeltaStmt, we should strongly consider adding new stmt nodes for the other flush statement types as well. The other types are meaningfully different enough in the executor implementation that I think it would make sense for them to have their own stmt nodes.

Basically, I think we should either leave FlushStmt as one statement, or split it up and remove the subtypes entirely. I'd like to avoid a "hybrid" situation where most statement types are in FlushStmt, but StatsDelta has its own special FlushStatsDeltaStmt: we should pick one way to keep things consistent.

**Review by henrybw — APPROVED** [review]
This makes sense. LGTM

**Review by Benjamin2037 — APPROVED** [review]
LGTM
