### PR TITLE
br: fix Log Backup unexpected paused when adding a already long-running task

### LINKED ISSUE #53561: Log Backup being paused due to a false positive in the automatic lag check.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start a log backup
2. wait for 48h(the default lag check threshold)
3. restart tidb advancer(or other scenarios that make advancer owner changed)

### 2. What did you expect to see? (Required)
a normal log backup status.
### 3. What did you see instead (Required)
log backup paused by chance.

(The chance is the lastCheckpoint cannot be updated in time before checking. e.g. regions has a hole will make lastCheckpoint skip update this time and wait for next tick. )

### 4. What is your TiDB version? (Required)
v6.5.9/v7.1.5/v8.1.0/master

### PR DESCRIPTION
**Pull request by RidRisR**
### What problem does this PR solve?

Issue Number: close #53561

Problem Summary:

### What changed and how does it work?

Now, advancer will sync checkpoint with pd when adding a new task

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix Log Backup unexpected paused when adding a long-run task
```

### CODE REVIEW

File: br/pkg/streamhelper/advancer.go [hunk 1]
```diff
@@ -424,7 +424,15 @@ func (c *CheckpointAdvancer) onTaskEvent(ctx context.Context, e TaskEvent) error
 		c.task = e.Info
 		c.taskRange = spans.Collapse(len(e.Ranges), func(i int) kv.KeyRange { return e.Ranges[i] })
 		c.setCheckpoints(spans.Sorted(spans.NewFullWith(e.Ranges, 0)))
-		c.lastCheckpoint = newCheckpointWithTS(e.Info.StartTs)
+		globalCheckpointTs, ok := c.env.GetGlobalCheckpointForTask(ctx, c.task.Name)
+		if ok != nil {
+			log.Warn("Advancer failed to get global checkpoint")
+			globalCheckpointTs = 0
```
Comment (3pointer) [inline br/pkg/streamhelper/advancer.go:430]: Once fail to get global checkpoint here. the task may very easy to stop. can we retry for this error here? with `utils.Retry`

File: br/pkg/streamhelper/advancer.go [hunk 2]
```diff
@@ -424,7 +424,15 @@ func (c *CheckpointAdvancer) onTaskEvent(ctx context.Context, e TaskEvent) error
...
+		}
+		if globalCheckpointTs < c.task.StartTs {
+			globalCheckpointTs = c.task.StartTs
+		}
+		c.lastCheckpoint = newCheckpointWithTS(globalCheckpointTs)
 		p, err := c.env.BlockGCUntil(ctx, c.task.StartTs)
```
Comment (3pointer) [inline br/pkg/streamhelper/advancer.go:436]: This BlockGCUntil should be `globalCheckpointTS` too.

File: br/pkg/streamhelper/advancer.go (hunk 1 above)
Comment (YuJuncen) [reply br/pkg/streamhelper/advancer.go:430]: I guess we can directly return error here?

Comment (RidRisR) [reply br/pkg/streamhelper/advancer.go]: > Once fail to get global checkpoint here. the task may very easy to stop. can we retry for this error here? with `utils.Retry`

added

File: br/pkg/streamhelper/advancer.go (hunk 2 above)
Comment (RidRisR) [reply br/pkg/streamhelper/advancer.go]: done

File: br/pkg/streamhelper/advancer.go [hunk 3]
```diff
@@ -424,8 +443,12 @@ func (c *CheckpointAdvancer) onTaskEvent(ctx context.Context, e TaskEvent) error
 		c.task = e.Info
 		c.taskRange = spans.Collapse(len(e.Ranges), func(i int) kv.KeyRange { return e.Ranges[i] })
 		c.setCheckpoints(spans.Sorted(spans.NewFullWith(e.Ranges, 0)))
-		c.lastCheckpoint = newCheckpointWithTS(e.Info.StartTs)
-		p, err := c.env.BlockGCUntil(ctx, c.task.StartTs)
+		globalCheckpointTs, err := c.GetGlobalCheckpointWithRetry(ctx, 3, 100*time.Millisecond)
```
Comment (BornChanger) [inline br/pkg/streamhelper/advancer.go:446]: How is 3*100ms determined for retry duration?

Comment (RidRisR) [reply br/pkg/streamhelper/advancer.go:446]: Just arbitrary，maybe we need a exponential backoff time?

Comment (YuJuncen) [reply br/pkg/streamhelper/advancer.go:446]: I will preferring directly return this error, we may add a test case to verify this case.

File: br/pkg/streamhelper/advancer_test.go [hunk 4]
```diff
@@ -570,6 +570,28 @@ func TestUnregisterAfterPause(t *testing.T) {
...
+	adv.UpdateConfigWith(func(c *config.Config) {
+		c.CheckPointLagLimit = 1 * time.Minute
+	})
+	c.advanceClusterTimeBy(5 * time.Minute)
+	c.advanceCheckpointBy(0 * time.Minute)
+	env.advanceCheckpointBy(5 * time.Minute)
+	adv.StartTaskListener(ctx)
+	require.NoError(t, adv.OnTick(ctx))
+	require.NoError(t, adv.OnTick(ctx))
+	require.NoError(t, adv.OnTick(ctx))
```
Comment (YuJuncen) [inline br/pkg/streamhelper/advancer_test.go:592]: Could you add some comments about how these tree `OnTick`s verify the task wasn't paused?

**Review by YuJuncen — APPROVED** [review]
rest lgtm

File: br/pkg/streamhelper/advancer_test.go (hunk 4 above)
Comment (RidRisR) [reply br/pkg/streamhelper/advancer_test.go:592]: The first time is to check there is no error before update global checkpoint
The second time is to check there is no error after update global checkpoint
The third time is redundant to check if there is any other unveiled problems

**Review by Leavrth — APPROVED** [review]

File: br/pkg/streamhelper/advancer.go [hunk 5]
```diff
@@ -424,8 +424,17 @@ func (c *CheckpointAdvancer) onTaskEvent(ctx context.Context, e TaskEvent) error
...
 		c.taskRange = spans.Collapse(len(e.Ranges), func(i int) kv.KeyRange { return e.Ranges[i] })
 		c.setCheckpoints(spans.Sorted(spans.NewFullWith(e.Ranges, 0)))
-		c.lastCheckpoint = newCheckpointWithTS(e.Info.StartTs)
-		p, err := c.env.BlockGCUntil(ctx, c.task.StartTs)
+		globalCheckpointTs, err := c.env.GetGlobalCheckpointForTask(ctx, e.Name)
+		if globalCheckpointTs < c.task.StartTs {
+			globalCheckpointTs = c.task.StartTs
+		}
+		log.Info("get global checkpoint", zap.Uint64("checkpoint", globalCheckpointTs))
+		if err != nil {
```
Comment (3pointer) [inline br/pkg/streamhelper/advancer.go:432]: prefer move this error check to L427

**Review by 3pointer — APPROVED** [review]

File: br/pkg/streamhelper/advancer.go (hunk 5 above)
Comment (BornChanger) [reply br/pkg/streamhelper/advancer.go:428]: fixed
