### PR TITLE
types: fix incompatible result of `DATE_ADD()`

### LINKED ISSUE #11645: Result of DATE_ADD function is different from mysql.(string INTERVAL)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR);
```

2. What did you expect to see?

```
mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND);
+--------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND) |
+--------------------------------------------------------+
| 2007-03-28 22:08:25.800000                             |
+--------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY);
+-----------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY) |
+-----------------------------------------------------+
| 2007-03-26 22:08:28                                 |
+-----------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR) |
+------------------------------------------------------+
| 2007-03-28 20:08:28                                  |
+------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:26                                     |
+---------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY) |
+------------------------------------------------------+
| 2007-03-26 22:08:28                                  |
+------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR);
+-------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR) |
+-------------------------------------------------------+
| 2007-03-28 20:08:28                                   |
+-------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

3. What did you see instead?
```
mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND);
+--------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND) |
+--------------------------------------------------------+
| 2007-03-28 22:08:26.200000                             |
+--------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY);
+-----------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY) |
+-----------------------------------------------------+
| 2007-03-30 22:08:28                                 |
+-----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR) |
+------------------------------------------------------+
| 2007-03-29 00:08:28                                  |
+------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:25.980000                              |
+---------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY) |
+------------------------------------------------------+
| 2007-03-30 22:08:28                                  |
+------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR);
+-------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR) |
+-------------------------------------------------------+
| 2007-03-29 00:08:28                                   |
+-------------------------------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
| Release Version: v3.0.0-rc.1-350-gdb4546028
Git Commit Hash: db454602801fea40b098fb5942576c3cd89dfebc
Git Branch: master
UTC Build Time: 2019-07-18 10:52:29
GoVersion: go version go1.12.6 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+----------------------------------
```

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @wshwsh12

### PR DESCRIPTION
**Pull request by markjenny**
### What problem does this PR solve?

Issue Number: close #11645  

Problem Summary:
The SQL `select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);` is incorrect.

### What is changed and how it works?

What's Changed:
change the parse of  the fraction part number. 

How it Works:
```
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:26                                     |
+---------------------------------------------------------+
```
### Release note

- Fix the result of SQL `select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND)` to be same with the MySQL; 

### Check List 

Tests 

- Unit test

Side effects
Nothing.

### CODE REVIEW

**Comment by markjenny** [comment]
@XuHuaiyu PTAL

File: types/time.go [hunk 1]
```diff
@@ -1965,13 +1965,15 @@ func parseSingleTimeValue(unit string, format string, strictCheck bool) (int64,
 	lf := len(format) - 1
 	// Has fraction part
 	if decimalPointPos < lf {
-		if lf-decimalPointPos >= 6 {
+		dvPre := oneToSixDigitRegex.FindString(format[decimalPointPos+1:]) // the numberical prefix of the fraction part
```
Comment (ichn-hu) [inline types/time.go:1968]: Perhaps you don't need to use the regrex here, just check if the decimal part has `-` as prefix would be sufficient.

Comment (markjenny) [reply types/time.go:1968]: But it is also useless in TiDB when facing these cases below:
```
MySQL [(none)]> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.+2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.+2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:25.980000                              |
+---------------------------------------------------------+
1 row in set (0.01 sec)

MySQL [(none)]> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.*2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.*2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:28                                     |
+---------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

MySQL [(none)]> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2./2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2./2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:28                                     |
+---------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.a2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.a2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:26                                     |
+---------------------------------------------------------+
1 row in set (0.03 sec)
```
And using the MySQL, the results are :
```
mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.+2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.+2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:26                                     |
+---------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.*2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.*2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:26                                     |
+---------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2./2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2./2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:26                                     |
+---------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [(none)]> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.a2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.a2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:28                                     |
+---------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

From the comparsion, we can find the rule of MySQL‘s behavior. MySQL get the numberical prefix of the fraction part. The fraction part is zero if the valid prefix is not found.

Comment (markjenny) [reply types/time.go:1968]: @ichn-hu PTAL

Comment (ichn-hu) [reply types/time.go:1968]: Cool, that make sense.

**Review by ichn-hu — DISMISSED** [review]
LGTM

**Comment by markjenny** [comment]
@XuHuaiyu PTAL

**Comment by markjenny** [comment]
@XuHuaiyu PTAL

**Review by zz-jason — COMMENTED** [review]
@markjenny could you add all the failed cases in https://github.com/pingcap/tidb/issues/11645 to the test?

**Comment by markjenny** [comment]
> @markjenny could you add all the failed cases in #11645 to the test?

@zz-jason I have added the failed cases in #11645. PTAL

**Review by wshwsh12 — COMMENTED** [review]
Good Job.  Almost LGTM.
1. Please take a look to (s *testIntegrationSuite) TestDatetimeMicrosecond (file expression/integration_test.go) and uncomment the test refer to issue #11645 
2. Please also add the test cases refer to your comment https://github.com/pingcap/tidb/pull/19880/files#r487512835.

**Comment by markjenny** [comment]
> Good Job. Almost LGTM.
> 
> 1. Please take a look to (s *testIntegrationSuite) TestDatetimeMicrosecond (file expression/integration_test.go L5217) and uncomment the test refer to issue #11645
> 2. Please also add the test cases refer to your comment https://github.com/pingcap/tidb/pull/19880/files#r487512835.

@wshwsh12 PTAL. The commit id is e59b291f3f6cba433f6288b0f5ad0937b18cd583.

**Comment by wshwsh12** [comment]
@markjenny  Please fix the git commits.....  It is too difficult to review this pr now.
Maybe you should use `git merge` command instead of `git rebase`.

**Comment by markjenny** [comment]
> @markjenny Please fix the git commits..... It is too difficult to review this pr now.
> Maybe you should use `git merge` command instead of `git rebase`.

I am so sorry about that. I fixed the git commit now.  @wshwsh12 PTAL.

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
