### PR TITLE
ddl: fix create partition table error under NO_UNSIGNED_SUBTRACTION

### LINKED ISSUE #24880: create partition table error while using `'NO_UNSIGNED_SUBTRACTION` sql mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
PARTITION p0 VALUES LESS THAN (-5),
PARTITION p1 VALUES LESS THAN (0),
PARTITION p2 VALUES LESS THAN (5),
PARTITION p3 VALUES LESS THAN (10),
PARTITION p4 VALUES LESS THAN (MAXVALUE)
);
```

### 2. What did you expect to see? (Required)
create table successfully 
### 3. What did you see instead (Required)
```sql
MySQL root@127.0.0.1:test> SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
                       ->  CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
                       ->  PARTITION p0 VALUES LESS THAN (-5),
                       ->  PARTITION p1 VALUES LESS THAN (0),
                       ->  PARTITION p2 VALUES LESS THAN (5),
                       ->  PARTITION p3 VALUES LESS THAN (10),
                       ->  PARTITION p4 VALUES LESS THAN (MAXVALUE)
                       ->  );
Query OK, 0 rows affected
Time: 0.002s
(1563, 'Partition constant is out of partition function domain')
```
### 4. What is your TiDB version? (Required)

master: 8c25a0074a62e6ebffe50ac765b269 
v4.0.12
v5.0.1

### PR DESCRIPTION
**Pull request by zhuo-zhi**
### What problem does this PR solve?

Issue Number: close #24880, related to #24150  

Problem Summary:

- create partition table error while using 'NO_UNSIGNED_SUBTRACTION…

### What is changed and how it works?

What's Changed:

- Change some logic in some check functions when creating partition tables.

How it Works:

- Consider session's SQLMode during correctness check when creating partition tables.
- But the current insert behavior is not the same as MySQL. This needs to be fixed afterwards.

### Check List 

Tests 

- Unit test

Side effects

- N/A

### Release note 

- ddl: fix create partition table error under NO_UNSIGNED_SUBTRACTION

### CODE REVIEW

File: table/tables/partition_test.go [hunk 1]
```diff
@@ -447,6 +447,25 @@ func (ts *testSuite) TestCreatePartitionTableNotSupport(c *C) {
...
+	tk.MustExec("SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';")
+	_, err := tk.Exec(`CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
+						PARTITION p0 VALUES LESS THAN (-5),
+						PARTITION p1 VALUES LESS THAN (0),
+						PARTITION p2 VALUES LESS THAN (5),
+						PARTITION p3 VALUES LESS THAN (10),
+						PARTITION p4 VALUES LESS THAN (MAXVALUE)
+						);`)
+	c.Assert(err, IsNil)
+	// currently not support insert records whose partition value is negative
```
Comment (xiongjiwei) [inline table/tables/partition_test.go:464]: I don't know why it is not supported, can you please explain a little while?

File: table/tables/partition_test.go [hunk 2]
```diff
@@ -447,6 +447,25 @@ func (ts *testSuite) TestCreatePartitionTableNotSupport(c *C) {
 	c.Assert(ddl.ErrPartitionFunctionIsNotAllowed.Equal(err), IsTrue)
 }
 
+// issue 24880
+func (ts *testSuite) TestRangePartitionUnderNoUnsignedSub(c *C) {
+	tk := testkit.NewTestKitWithInit(c, ts.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists tu;")
+	tk.MustExec("SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';")
+	_, err := tk.Exec(`CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
```
Comment (xiongjiwei) [inline table/tables/partition_test.go:456]: we can use `tk.MustExec` as above

File: table/tables/partition_test.go [hunk 3]
```diff
@@ -447,6 +447,25 @@ func (ts *testSuite) TestCreatePartitionTableNotSupport(c *C) {
...
+						PARTITION p0 VALUES LESS THAN (-5),
+						PARTITION p1 VALUES LESS THAN (0),
+						PARTITION p2 VALUES LESS THAN (5),
+						PARTITION p3 VALUES LESS THAN (10),
+						PARTITION p4 VALUES LESS THAN (MAXVALUE)
+						);`)
+	c.Assert(err, IsNil)
+	// currently not support insert records whose partition value is negative
+	_, err = tk.Exec(("insert into tu values (0);"))
```
Comment (xiongjiwei) [inline table/tables/partition_test.go:465]: can you please also insert a big unsigned value?

**Review by xiongjiwei — COMMENTED** [review]
can you please add a test about insert

**Review by qw4990 — APPROVED** [review]
LGTM, please address Jiwei's comments.

**Comment by qw4990** [comment]
oh... I have no privilege to approve it, PTAL @wjhuang2016

File: table/tables/partition_test.go (hunk 1 above)
Comment (zhuo-zhi) [reply table/tables/partition_test.go:464]: Currently the partition expression used to locate partitions uses a mock context instead of the current context, and thus it cannot do unsigned subtraction producing negative results under NO_UNSIGNED_SUBTRACTION SQLMode. See [source code](https://github.com/pingcap/tidb/blob/master/table/tables/partition.go#L116).

File: table/tables/partition_test.go (hunk 2 above)
Comment (zhuo-zhi) [reply table/tables/partition_test.go]: Update in the new commit.

File: table/tables/partition_test.go (hunk 3 above)
Comment (zhuo-zhi) [reply table/tables/partition_test.go]: Update in the new commit.

Comment (xiongjiwei) [reply table/tables/partition_test.go]: a value greater than `bigint signed` but less than `bigint unsigned` is expected.

Comment (zhuo-zhi) [reply table/tables/partition_test.go]: Update in the new commit.

File: table/tables/partition_test.go [hunk 4]
```diff
@@ -447,6 +447,31 @@ func (ts *testSuite) TestCreatePartitionTableNotSupport(c *C) {
 	c.Assert(ddl.ErrPartitionFunctionIsNotAllowed.Equal(err), IsTrue)
 }
 
+// issue 24880
+func (ts *testSuite) TestRangePartitionUnderNoUnsignedSub(c *C) {
+	tk := testkit.NewTestKitWithInit(c, ts.store)
```
Comment (wjhuang2016) [inline table/tables/partition_test.go:452]: We‘d better check `create table like` too.

File: table/tables/partition_test.go [hunk 5]
```diff
@@ -470,6 +470,23 @@ func (ts *testSuite) TestRangePartitionUnderNoUnsignedSub(c *C) {
 	// MySQL will not support c1 value bigger than 9223372036854775817 in this case
 	_, err = tk.Exec(("insert into tu values (cast(18446744073709551615 as unsigned));"))
 	c.Assert(err, IsNil)
+	_, err = tk.Exec(("insert into tu values (cast(18446744073709551616 as unsigned));"))
+	c.Assert(err, NotNil)
+
+	// test `create table like`
+	tk.MustExec(`CREATE TABLE tu2 like tu;`)
```
Comment (wjhuang2016) [inline table/tables/partition_test.go:477]: MySQL:
``` sql
mysql> SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE tu2 like tu;
Query OK, 0 rows affected (0.02 sec)

mysql> SET @@sql_mode='';
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE tu2 like tu;
ERROR 1563 (HY000): Partition constant is out of partition function domain
```

Sorry, I don't think you get my point. I want to ask you to test if `NO_UNSIGNED_SUBTRACTION
` affects `create table like`. To test it, you also need to set the `sql_mode` back.

Comment (zhuo-zhi) [reply table/tables/partition_test.go:477]: TiDB's `create table like` will [bypass partition table checks](https://github.com/pingcap/tidb/blob/master/ddl/ddl_api.go#L1593), and can successfully create the above table no matter which SQLMode it is in. This behaves different with MySQL. Should this be fixed in this pr?

File: table/tables/partition_test.go [hunk 6]
```diff
@@ -447,6 +447,48 @@ func (ts *testSuite) TestCreatePartitionTableNotSupport(c *C) {
...
+	tk.MustExec("SET @@sql_mode='NO_UNSIGNED_SUBTRACTION';")
+	tk.MustExec(`CREATE TABLE tu (c1 BIGINT UNSIGNED) PARTITION BY RANGE(c1 - 10) (
+				PARTITION p0 VALUES LESS THAN (-5),
+				PARTITION p1 VALUES LESS THAN (0),
+				PARTITION p2 VALUES LESS THAN (5),
+				PARTITION p3 VALUES LESS THAN (10),
+				PARTITION p4 VALUES LESS THAN (MAXVALUE)
+				);`)
+	// currently not support insert records whose partition value is negative
+	_, err := tk.Exec(("insert into tu values (0);"))
```
Comment (xiongjiwei) [inline table/tables/partition_test.go:464]: a suggestion: we can use `MustGetErrCode` or `MustGetErrMsg` to make the test more understandable

Comment (zhuo-zhi) [reply table/tables/partition_test.go:464]: Thanks for the suggestion! Update in the new commit.

File: table/tables/partition_test.go (hunk 5 above)
Comment (zhuo-zhi) [reply table/tables/partition_test.go:477]: Also update this test in the new commit.

**Review by xiongjiwei — APPROVED** [review]

**Comment by qw4990** [comment]
PTAL @wjhuang2016

**Review by wjhuang2016 — APPROVED** [review]
