### PR TITLE
ddl: fix issue of add foreign key too slow in big table

### LINKED ISSUE #40111: Add foreign key too slow in big table
## Reproduce

Prepare
```sql
create table t1(id int auto_increment key, pid int);
insert into t1 () values (),(),(),(),(),(),(),();
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
insert into t1 (pid) select pid from t1;
update t1 set pid=id;
```

Then add foreign key, the following execution will be very slow:

```sql
test> alter table t1 add foreign key (pid) references t1(id);
Query OK, 0 rows affected
Time: 189.097s
```

## Version
```sql
***************************[ 1. row ]***************************
tidb_version() | Release Version: v6.6.0-alpha-63-g4adce4cded
Edition: Community
Git Commit Hash: 4adce4cded1da88d1958467881dea50b21745588
Git Branch: master
UTC Build Time: 2022-12-22 10:02:30
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

Issue Number: close #40111

Problem Summary: fix issue of add foreign key too slow in big table.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/fktest/foreign_key_test.go [hunk 1]
```diff
@@ -1591,3 +1592,19 @@ func TestTestMultiSchemaAddForeignKey(t *testing.T) {
 	tk.MustExec("create table t2 (a int, b int, index idx0(a,b), index idx1(a), index idx2(b));")
 	tk.MustExec("alter table t2 drop index idx1, add foreign key (a) references t1(id), add foreign key (b) references t1(id)")
 }
+
+func TestAddForeignKeyInBigTable(t *testing.T) {
+	store, _ := testkit.CreateMockStoreAndDomain(t)
```
Comment (hawkingrei) [inline ddl/fktest/foreign_key_test.go:1597]:
```suggestion
	store := testkit.CreateMockStore(t)
```

**Review by winoros — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]
