### PR TITLE
parser: redact azure/azblob url

### LINKED ISSUE #65275: azure url is not redacted
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Import data from azure.

### 2. What did you expect to see? (Required)

`SHOW IMPORT JOBS` return redacted url

### 3. What did you see instead (Required)

Return original url

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #65275

Problem Summary:

Found when doing manual check for #65261, we don't redact the sas-token for azure.

### What changed and how does it work?

Redact import url like S3.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/parser/ast/misc_test.go [hunk 1]
```diff
@@ -372,6 +372,9 @@ func TestRedactURL(t *testing.T) {
 		// underline
 		{args{"s3://bucket/file?access_key=123"}, "s3://bucket/file?access_key=xxxxxx"},
 		{args{"s3://bucket/file?secret_access_key=123"}, "s3://bucket/file?secret_access_key=xxxxxx"},
+		{args{"azure://bucket/file?sas-token=123"}, "azure://bucket/file?sas-token=xxxxxx"},
+		{args{"azblob://bucket/file?sas-token=123"}, "azblob://bucket/file?sas-token=xxxxxx"},
+		{args{"azure://bucket/file?account-name=test&sas_token=123"}, "azure://bucket/file?account-name=test&sas_token=xxxxxx"},
```
Comment (D3Hunter) [inline pkg/parser/ast/misc_test.go]: URL uses map to store args, so the order might change and flaky

Comment (joechenrh) [reply pkg/parser/ast/misc_test.go]: go 1.25.5 has the logic of sorting key before generating url. I've added comment for this.

https://github.com/golang/go/blob/fefb02adf45c4bcc879bd406a8d61f2a292c26a9/src/net/url/url.go#L1033
