### PR TITLE
disttask: fix potential block on DXF scheduler

### LINKED ISSUE #59944: Unexpcted blocked scheduler in DXF if doCleanupTask takes long time
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
	sm.schedulerWG.RunWithLog(func() {
		defer func() {
			scheduler.Close()
			sm.delScheduler(task.ID)
			if allocateSlots {
				sm.slotMgr.unReserve(basicTask, reservedExecID)
			}
			handle.NotifyTaskChange()
			sm.logger.Info("task scheduler exit", zap.Int64("task-id", task.ID))
		}()
		metrics.UpdateMetricsForRunTask(task)
		scheduler.ScheduleTask()
		sm.finishCh <- struct{}{}
	})
```
finishCh may be blocked. If more than 2x concurrency tasks are put into finishCh and it still can handle any result. New task would be blocked because no slot is available.

### 2. What did you expect to see? (Required)
N/A
### 3. What did you see instead (Required)
N/A
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #59944

Problem Summary:
The channel receiver may not receive, then send a signal to the channel, which may get blocked.

### What changed and how does it work?
Use select-default to discard the signal.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix potential block on DXF scheduler
```

### CODE REVIEW

File: tests/realtikvtest/addindextest1/disttask_test.go [hunk 1]
```diff
@@ -462,3 +463,38 @@ func TestAddIndexScheduleAway(t *testing.T) {
 	tk.MustExec("alter table t add index idx(b);")
 	require.NotEqual(t, int64(0), jobID.Load())
 }
+
+func TestAddIndexDistCleanUpBlock(t *testing.T) {
+	proto.MaxConcurrentTask = 1
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/pkg/util/cpu/mockNumCpu", `return(1)`))
+	t.Cleanup(func() {
+		require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/pkg/util/cpu/mockNumCpu"))
+	})
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest1/disttask_test.go:472]:
```suggestion
	testfailpoint.Enable(t, "github.com/pingcap/tidb/pkg/util/cpu/mockNumCpu", `return(1)`))
```

**Review by D3Hunter — APPROVED** [review]
rest lgtm

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
here's the check_dev CI message

```
Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents with ctrl-D as ending):
diff --git a/tests/realtikvtest/addindextest1/BUILD.bazel b/tests/realtikvtest/addindextest1/BUILD.bazel
index 3dbc2b8e2b..37587e6f60 100644
--- a/tests/realtikvtest/addindextest1/BUILD.bazel
+++ b/tests/realtikvtest/addindextest1/BUILD.bazel
@@ -11,6 +11,7 @@ go_test(
     deps = [
         "//pkg/config",
         "//pkg/ddl/ingest",
+        "//pkg/disttask/framework/proto",
         "//pkg/disttask/framework/storage",
         "//pkg/disttask/framework/taskexecutor",
         "//pkg/errno",

```

@wjhuang2016
