### PR TITLE
*: fix InContainer check for cgroup v2

### LINKED ISSUE #51668: InContainer fails to check on a GCP pod
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[root@tc-tidb-0 /]# cat /proc/1/cgroup
0::/
[root@tc-tidb-0 /]# cat /proc/1/mountinfo
2849 2619 0:283 / / rw,relatime master:665 - overlay overlay rw,lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/195/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/194/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/193/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/192/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/191/fs,upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/218/fs,workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/218/work
2850 2849 0:285 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
2851 2849 0:286 / /dev rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
2852 2851 0:287 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
2853 2851 0:258 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
2854 2849 0:263 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro
2855 2854 0:25 / /sys/fs/cgroup ro,nosuid,nodev,noexec,relatime - cgroup2 cgroup rw
2856 2849 0:248 / /etc/podinfo ro,relatime - tmpfs tmpfs rw,size=60145236k
2857 2849 8:1 /var/lib/kubelet/pods/abf065ee-34b7-46d7-8264-0bece3d7e8e7/volumes/kubernetes.io~configmap/config /etc/tidb ro,relatime - ext4 /dev/sda1 rw,commit=30
2858 2849 8:1 /var/lib/kubelet/pods/abf065ee-34b7-46d7-8264-0bece3d7e8e7/etc-hosts /etc/hosts rw,relatime - ext4 /dev/sda1 rw,commit=30
2859 2851 8:1 /var/lib/kubelet/pods/abf065ee-34b7-46d7-8264-0bece3d7e8e7/containers/tidb/dd4a6152 /dev/termination-log rw,relatime - ext4 /dev/sda1 rw,commit=30
2860 2849 8:1 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/f1a400276ec5a94230956bdb3f022982bb230e587cc0d78d59c7c4fe5cf445a6/hostname /etc/hostname rw,nosuid,nodev,relatime - ext4 /dev/sda1 rw,commit=30
2861 2849 8:1 /var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/f1a400276ec5a94230956bdb3f022982bb230e587cc0d78d59c7c4fe5cf445a6/resolv.conf /etc/resolv.conf rw,nosuid,nodev,relatime - ext4 /dev/sda1 rw,commit=30
2862 2851 0:255 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
2863 2849 8:1 /var/lib/kubelet/pods/abf065ee-34b7-46d7-8264-0bece3d7e8e7/volumes/kubernetes.io~configmap/startup-script /usr/local/bin ro,relatime - ext4 /dev/sda1 rw,commit=30
2864 2849 8:16 / /var/lib/tidb/log rw,relatime - ext4 /dev/sdb rw
2865 2849 0:249 / /run/secrets/kubernetes.io/serviceaccount ro,relatime - tmpfs tmpfs rw,size=60145236k
2620 2850 0:285 /bus /proc/bus ro,nosuid,nodev,noexec,relatime - proc proc rw
2621 2850 0:285 /fs /proc/fs ro,nosuid,nodev,noexec,relatime - proc proc rw
2622 2850 0:285 /irq /proc/irq ro,nosuid,nodev,noexec,relatime - proc proc rw
2623 2850 0:285 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
2624 2850 0:285 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
2625 2850 0:288 / /proc/acpi ro,relatime - tmpfs tmpfs ro
2626 2850 0:286 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
2627 2850 0:286 /null /proc/keys rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
2628 2850 0:286 /null /proc/timer_list rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
2629 2850 0:289 / /proc/scsi ro,relatime - tmpfs tmpfs ro
2630 2854 0:290 / /sys/firmware ro,relatime - tmpfs tmpfs ro
```

### 2. What did you expect to see? (Required)
true
and log contains `use cgroup memory hook because TiDB is in the container`
### 3. What did you see instead (Required)
false
logs contains this
```
2024-03-11 13:36:26 (UTC+08:00)TiDB tc-tidb-0.tc-tidb-peer.gsort-import-gcp-tps-7500323-1-546.svc:4000[meminfo.go:196] ["use physical memory hook"] [cgroupMemorySize=68719476736] [physicalMemorySize=67536244736]
```
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #51668

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
before
```
[2024/03/11 09:54:43.469 +00:00] [INFO] [meminfo.go:196] ["use physical memory hook"] [cgroupMemorySize=68719476736] [physicalMemorySize=67536244736]
```
after
```
[2024/03/11 12:36:07.807 +00:00] [INFO] [meminfo.go:179] ["use cgroup memory hook because TiDB is in the container"]
[2024/03/11 12:36:07.808 +00:00] [INFO] [printer.go:47] ["Welcome to TiDB."] ["Release Version"=v7.5.0-incontainer2gcp] [Edition=Community] ["Git Commit Hash"=6bf81524079e80de19be644fc0ca43e1f98e0019] ["Git Branch"=heads/refs/tags/v7.5.0-incontainer2gcp] ["UTC Build Time"="2024-03-11 12:26:20"] [GoVersion=go1.21.6] ["Race Enabled"=false] ["Check Table Before Drop"=false]
```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/util/cgroup/cgroup_cpu_linux.go [hunk 1]
```diff
@@ -74,24 +74,34 @@ func inContainer(path string) bool {
...
 		lines := strings.Split(string(v), "\n")
 		for _, line := range lines {
 			v := strings.Split(line, " ")
-			// check mount point is on overlay or not.
-			// v[4] means `mount point`, v[8] means `filesystem type`.
+			// check mount point is on overlay or not, v[8] means `filesystem type`.
 			// see details from https://man7.org/linux/man-pages/man5/proc.5.html
-			if len(v) >= 8 && v[4] == "\\" && v[8] == "overlay" {
+			// TODO: enhance this check, as overlay is not the only storage driver for container.
+			if len(v) > 8 && v[8] == "overlay" {
```
Comment (hawkingrei) [inline pkg/util/cgroup/cgroup_cpu_linux.go:104]: You need to add tests for it.

Comment (D3Hunter) [reply pkg/util/cgroup/cgroup_cpu_linux.go:104]: manually testing

Comment (D3Hunter) [reply pkg/util/cgroup/cgroup_cpu_linux.go:94]: updated in pr desc

**Review by Defined2014 — APPROVED** [review]

**Comment by D3Hunter** [comment]
/hold

i will test it again manually, as the logic changed

**Comment by D3Hunter** [comment]
test again
```
2024-03-12 12:05:22 (UTC+08:00)TiDB tc-tidb-0.tc-tidb-peer.gsort-import-gcp-tps-7470320-1-17.svc:4000[meminfo.go:179] ["use cgroup memory hook because TiDB is in the container"]
```

**Review by hawkingrei — APPROVED** [review]
