### PR TITLE
domain, executor: add the missing debug trace for manual plan replayer

### LINKED ISSUE #44599: debug trace is missing for manual plan replayer
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run a `plan replayer dump explain select xxx` statement and download the plan replayer zip file.

### 2. What did you expect to see? (Required)

There is `debug_trace.json` in the zip file.

### 3. What did you see instead (Required)

There is no `debug_trace.json` in the zip file.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #44599 

Problem Summary:

A careless mistake during the development of the debug trace.

### What is changed and how it works?

- `DebugTrace` is changed to a slice.
- In `dumpExplain`, `OptimizerDebugTrace` is collected for every statement.
- In `dumpDebugTrace`, each `DebugTrace` is output to a single file.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: domain/plan_replayer_dump.go [hunk 1]
```diff
@@ -846,14 +849,24 @@ func getRows(ctx context.Context, rs sqlexec.RecordSet) ([]chunk.Row, error) {
...
+	return nil
+}
+
+func dumpOneDebugTrace(w io.Writer, debugTrace interface{}) error {
+	jsonEncoder := json.NewEncoder(w)
 	// If we do not set this to false, ">", "<", "&"... will be escaped to "\u003c","\u003e", "\u0026"...
 	jsonEncoder.SetEscapeHTML(false)
-	err = jsonEncoder.Encode(debugTrace)
+	err := jsonEncoder.Encode(debugTrace)
 	return err
```
Comment (hawkingrei) [inline domain/plan_replayer_dump.go:871]:
```suggestion
	return jsonEncoder.Encode(debugTrace)
```

**Review by hawkingrei — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
