### PR TITLE
expression, executor: fix runtime panic in WEIGHT_STRING function when the length of binary is too large

### LINKED ISSUE #22201: runtime error: makeslice: cap out of range
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
SELECT HEX(WEIGHT_STRING('ab' AS BINARY(1000000000000000000)));
```

### 2. What did you expect to see? (Required)
OK.

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): runtime error: makeslice: cap out of range
```
### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1968-g4bfd10cec
Edition: Community
Git Commit Hash: 4bfd10cec89dd1640c82441ac8f4939304134662
Git Branch: master
UTC Build Time: 2021-01-05 12:47:53
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #22201 

Problem Summary:

### What is changed and how it works?

What's Changed:
fix runtime panic in WEIGHT_STRING function when the length of binary is too large
How it Works:
[mysql](https://github.com/mysql/mysql-server/blob/8.0/sql/item_strfunc.cc#L3432)

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Fix runtime panic in WEIGHT_STRING function when the length of binary/char is too large

### CODE REVIEW

File: expression/builtin_string.go [hunk 1]
```diff
@@ -3951,6 +3951,16 @@ func (b *builtinWeightStringSig) evalString(row chunk.Row) (string, bool, error)
 			b.ctx.GetSessionVars().StmtCtx.AppendWarning(errTruncatedWrongValue.GenWithStackByArgs(tpInfo, str))
 			str = str[:b.length]
 		} else if b.length > lenStr {
+			sc := b.ctx.GetSessionVars().StmtCtx
+			valStr, _ := b.ctx.GetSessionVars().GetSystemVar(variable.MaxAllowedPacket)
```
Comment (wshwsh12) [inline expression/builtin_string.go:3955]: We should save maxAllowedPacket in Sig and set it in getFunction. (see  builtinRepeatSig)

Comment (TszKitLo40) [reply expression/builtin_string.go]: OK, I have done this.

File: executor/executor_test.go [hunk 2]
```diff
@@ -7562,3 +7562,9 @@ func (s *testSuite) TestIssue22231(c *C) {
 	tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1292 Truncated incorrect datetime value: '2020-05-28 23:59:59 00:00:00'"))
 	tk.MustExec("drop table if exists t_issue_22231")
 }
+
+func (s *testSuite) TestIssue22201(c *C) {
+	tk := testkit.NewTestKitWithInit(c, s.store)
+	tk.MustQuery("SELECT HEX(WEIGHT_STRING('ab' AS BINARY(1000000000000000000)));").Check(testkit.Rows("<nil>"))
+	tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1301 Result of cast_as_binary() was larger than max_allowed_packet (67108864) - truncated"))
```
Comment (wjhuang2016) [inline executor/executor_test.go:7569]: MySQL:
```
Result of weight_string() was larger than max_allowed_packet (67108864) - truncated
```

Comment (TszKitLo40) [reply executor/executor_test.go:7569]: In MySQL8, it is 
`Result of cast_as_binary() was larger than max_allowed_packet (67108864) - truncated`

Comment (wjhuang2016) [reply executor/executor_test.go:7569]: Please check this :
```
mysql> SELECT HEX(WEIGHT_STRING('ab' AS char(1000000000000000000)));
+-------------------------------------------------------+
| HEX(WEIGHT_STRING('ab' AS char(1000000000000000000))) |
+-------------------------------------------------------+
| NULL                                                  |
+-------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                             |
+---------+------+-------------------------------------------------------------------------------------+
| Warning | 1301 | Result of weight_string() was larger than max_allowed_packet (67108864) - truncated |
+---------+------+-------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

Comment (TszKitLo40) [reply executor/executor_test.go:7569]: I use MySQL  8.0.21, and the warning is `Result of cast_as_binary() was larger than max_allowed_packet (67108864) - truncated`.

Comment (TszKitLo40) [reply executor/executor_test.go:7569]: The sql of this issue is `"SELECT HEX(WEIGHT_STRING('ab' AS BINARY(1000000000000000000)))`.

Comment (wjhuang2016) [reply executor/executor_test.go:7569]: `SELECT HEX(WEIGHT_STRING('ab' AS char(1000000000000000000)));` also casues `makeslice: cap out of range`.

Comment (TszKitLo40) [reply executor/executor_test.go:7569]: OK, I have fixed it, PTAL.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
