### PR TITLE
executor, util/memory: keep global analyze memory usage non-negative

### LINKED ISSUE #65502: analyze: global analyze memory in-use metric can become negative (Analyze v2)
### 1. Minimal reproduce step (Required)
1. Create a table with large TEXT rows (to stress sampling collector memory).
2. Set analyze v2 and limit concurrency to increase chance of cleanup reordering:
   - `set @@tidb_analyze_version=2;`
   - `set @@tidb_build_sampling_stats_concurrency=1;`
3. Run:
   - `analyze table <tbl> with 1.0 samplerate;`

(Optionally) enable internal check/assert to catch the invariant violation:
- build/test with `--tags=intest`, or
- `export GO_FAILPOINTS="/enableInternalCheck=return(true)"` (with failpoint-enabled build)

### 2. What did you expect to see? (Required)
Global analyze memory usage (label: `LabelForGlobalAnalyzeMemory`, metric: `analyze/inuse`) should never be negative.

### 3. What did you see instead (Required)
The in-use value can become temporarily negative during Analyze v2 execution (observed via metrics / internal check).

### 4. Root cause analysis (Optional)
In `AnalyzeColumnsExecV2.subBuildWorker`, buffered consume/release are deferred in a way that may apply `Release` before `Consume` (because multiple defers execute LIFO),
causing transient negative `bytesConsumed` for the global analyze memory tracker.

### 5. Proposed fix (Optional)
- Ensure buffered `Consume` is applied before buffered `Release` in worker cleanup.
- Add an internal invariant check for `LabelForGlobalAnalyzeMemory`.
- Add regression test for Analyze v2 to avoid future regressions.

### 6. Affected versions (Optional)
master

### 7. Related PR (Optional)
- #65503

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #65502

Problem Summary:
Global analyze memory "in-use" can temporarily become negative during Analyze v2 due to cleanup order, which may lead to confusing metrics and violates invariants in internal-check builds.

### What changed and how does it work?
- Adjust AnalyzeColumnsExecV2 worker cleanup so buffered Consume is applied before buffered Release.
- Add an internal assertion to ensure `LabelForGlobalAnalyzeMemory` (in-use) is never negative.
- Add a regression test for Analyze v2 memory usage invariant.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/analyze_col_v2.go [hunk 1]
```diff
@@ -684,8 +684,10 @@ func (e *AnalyzeColumnsExecV2) subBuildWorker(resultCh chan error, taskCh chan *
 	colLen := len(e.colsInfo)
 	bufferedMemSize := int64(0)
 	bufferedReleaseSize := int64(0)
-	defer e.memTracker.Consume(bufferedMemSize)
-	defer e.memTracker.Release(bufferedReleaseSize)
```
Comment (D3Hunter) [inline pkg/executor/analyze_col_v2.go:688]: in this version, we always consume 0 and release 0, as arguments of defer is computed before defer function called

**Comment by wjhuang2016** [comment]
Addressed the review comment from @D3Hunter: the worker cleanup now uses a deferred closure so `bufferedMemSize`/`bufferedReleaseSize` are evaluated at defer execution time (not at defer registration time), and we execute Consume before Release to avoid transient negative in-use values.

File: pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go [hunk 2]
```diff
@@ -214,3 +214,31 @@ func TestMemQuotaAnalyze2(t *testing.T) {
...
+	}()
+	executor.GlobalAnalyzeMemoryTracker.ReplaceBytesUsed(0)
+
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("set @@tidb_analyze_version=2")
+	tk.MustExec("set @@tidb_build_sampling_stats_concurrency=1")
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t_mem_usage")
+	tk.MustExec("create table t_mem_usage(a text collate utf8mb4_general_ci)")
+	tk.MustExec("insert into t_mem_usage values (repeat('a', 32000))")
```
Comment (winoros) [inline pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go]: Analyze relies on the `MaxSampleValueLength` to skip big values when building stats.
Currently, this var is `32767`. But we may change it because other databases usually set this value to 1k or so.

So we can add an `intest.Assert(MaxSampleValueLength > 32000)` to ensure that the inserted values will affect the stats collection.

File: pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go [hunk 3]
```diff
@@ -214,3 +214,31 @@ func TestMemQuotaAnalyze2(t *testing.T) {
...
+		}
+	}()
+	executor.GlobalAnalyzeMemoryTracker.ReplaceBytesUsed(0)
+
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("set @@tidb_analyze_version=2")
+	tk.MustExec("set @@tidb_build_sampling_stats_concurrency=1")
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t_mem_usage")
+	tk.MustExec("create table t_mem_usage(a text collate utf8mb4_general_ci)")
```
Comment (winoros) [inline pkg/executor/test/analyzetest/memorycontrol/memory_control_test.go:242]: We can
1. Change the type to `varchar` or 
2. Do an explicit set for the var `tidb_analyze_skip_column_types` to ensure that we will not skip the text type when building stats.
