### PR TITLE
lightning: skip restore table when source files are empty

### LINKED ISSUE #28144: Lightning: lightning_metadata not deleted after import exit successfully
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- Create a new tidb cluster
- Enable tidb_enable_list_partition on Tidb
- Import list partition test data (1.5k tables) 
   data source: s3://nfs/tools_test_data/list_partition_1.5k?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9000&force-path-style=true
- After lightning import, check tidb whether lightning_metadata database was deleted.

### 2. What did you expect to see? (Required)
lightning_metadata database should be deleted.

### 3. What did you see instead (Required)
lightning_metadata not deleted through lightning import was successful.

Lightning log: 
tidb lightning exit
2021-09-16T14:35:44.012Z        INFO    host/host.go:41 Execute command finished        {"command": "/tidb-lightning \"-tidb-port\" \"4000\" \"-tidb-user\" \"root\" \"-tidb-password\" \"\" \"-backend\" \"local\" \"-sorted-kv-dir\" \"/tmp/sorted-kv-dir\" \"-d\" \"s3://nfs/tools_test_data/list_partition_1.5k?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9000&force-path-style=true\" \"-pd-urls\" \"upstream-pd.brie-acceptance-long-time-demo-9trtr.svc:2379\" \"-tidb-host\" \"upstream-tidb.brie-acceptance-
long-time-demo-9trtr.svc\"", "execute duration": "37m33.076334571s"}

lightning_metadata

### 4. What is your TiDB version? (Required)
/ # ./tidb-lightning -V
Release Version: v5.2.0-nightly
Git Commit Hash: b839744d09bf805f5a9daa61e8b52d9ba2e9a8df
Git Branch: heads/refs/tags/v5.2.0-nightly
Go Version: go1.16.4
UTC Build Time: 2021-09-17 01:40:14
Race Enabled: false

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #28144

Problem Summary:

### What is changed and how it works?
Skip restore table when there are no source files.

### Check List 

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
Fix the bug that lightning may not clean up metadata schema when some of the import contains no source files.
```

### CODE REVIEW

**Comment by gozssky** [comment]
There are at least four special judgments(include this PR) for empty source table 😂, can we unify them in one place?

File: br/pkg/lightning/restore/restore.go [hunk 1]
```diff
@@ -1349,6 +1349,9 @@ func (rc *Controller) restoreTables(ctx context.Context) error {
 			if err != nil {
 				return errors.Trace(err)
 			}
+			if cp.Status < checkpoints.CheckpointStatusAllWritten && len(tableMeta.DataFiles) == 0 {
```
Comment (gozssky) [inline br/pkg/lightning/restore/restore.go:1352]: Why `cp.Status < checkpoints.CheckpointStatusAllWritten` is needed here?

Comment (glorv) [reply br/pkg/lightning/restore/restore.go:1352]: If `cp.Status >= CheckpointStatusAllWritten` then the restore process has no relation with the source files anymore, so we may allow it to continue even if we find there are no source files. Maybe there are situations that the source files are corrupted, the import phase can still go on.😅

**Review by gozssky — APPROVED** [review]

File: br/pkg/lightning/restore/restore.go (hunk 1 above)
Comment (ngaut) [reply br/pkg/lightning/restore/restore.go:1352]: Comparing statue is wired. Status is not a clear name, Rename it to stage or something similar would be more clear.

**Comment by glorv** [comment]
@kennytm PTAL

**Comment by kennytm** [comment]
o_O

**Comment by kennytm** [comment]
one of the `lightning_parquet lightning_partitioned-table lightning_restore lightning_routes lightning_row-format-v2` tests failed.

**Comment by glorv** [comment]
> the new test failed.
> 
> https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/10068/pipeline/102
> 
> ```
> [2022-02-15T07:45:40.787Z] *************************** 1. row ***************************
> 
> [2022-02-15T07:45:40.787Z] Database: lightning_metadata
> 
> [2022-02-15T07:45:40.787Z] TEST FAILED: OUTPUT CONTAINS 'Database: lightning_metadata'
> 
> [2022-02-15T07:45:40.787Z] ____________________________________
> 
> [2022-02-15T07:45:40.787Z] [Tue Feb 15 15:45:39 CST 2022] Executing SQL: SHOW DATABASES like 'lightning_metadata';
> 
> [2022-02-15T07:45:40.787Z] *************************** 1. row ***************************
> 
> [2022-02-15T07:45:40.787Z] Database: lightning_metadata
> 
> [2022-02-15T07:45:40.787Z] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

Fixed. Since we don't support incremental restore for importer backend, I just from the case for `importer` in `lightning_incremental`.

**Review by kennytm — APPROVED** [review]
