### PR TITLE
br: fix lightning split large csv file error and adjust s3 seek result

### LINKED ISSUE #27763: Lightning: DBaaS import csv fails with InvalidRange if CSV file size is about 256MB when strict-format is true
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
On DBaaS, try to import csv from S3, S3 bucket files like below:
[root@centos76_vm ~]# du -shl /minio/fubin/dbgen/xxx/*
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000000.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000001.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000002.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000003.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000004.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000005.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000006.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000007.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000008.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000009.csv
4.0K    /minio/fubin/dbgen/aaaa/aaaa.bbbb-schema.sql
4.0K    /minio/fubin/dbgen/aaaa/aaaa-schema-create.sql
4.0K    /minio/fubin/dbgen/aaaa/metadata

### 2. What did you expect to see? (Required)
Import should succeed

### 3. What did you see instead (Required)
Import failed.

### 4. What is your TiDB version? (Required)
Lightning: 5.2.0
[release-version=v5.2.0] [git-hash=05d2210647d6a1503a8d772477e43b14a024f609] [git-branch=heads/refs/tags/v5.2.0] [go-version=go1.16.4]

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?
Fix the bug that lightning split large csv file may failed if the file size if slightly bigger the `region-split-size` and the csv has header.

close #27763

### What is changed and how it works?
- If the backend if s3, when the seek position >= file size, the seek will succeed and the reader will be replaced with a reader that always returns `io.EOF`
- Add a check in lightning `makeTableRegions`, after preprocess the header line, if the remain file is smaller than `region-split-size`, directly return the result with 1 region.

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

Documentation

### Release note 

```release-note
Fix the bug that import from s3 may fail if the csv file size is similar to region-split-size(default is 256MiB)
```

### CODE REVIEW

File: br/pkg/storage/s3.go [hunk 1]
```diff
@@ -666,6 +677,18 @@ func (r *s3ObjectReader) Seek(offset int64, whence int) (int64, error) {
...
+		// because s3's GetObject interface doesn't allow get a range that matches zero length data,
+		// so if the position is out of range, we need to always return io.EOF after the seek operation.
+
+		// close current read and open a new one which target offset
+		if err := r.reader.Close(); err != nil {
+			log.L().Warn("close s3 reader failed, will ignore this error", logutil.ShortError(err))
+		}
+
+		r.reader = eofReader{}
+		return r.rangeInfo.Size, nil
```
Comment (gozssky) [inline br/pkg/storage/s3.go:691]: `r.pos` need to be updated in case subsequent  seeks. Also, should we return `realOffset` rather than `r.rangeInfo.Size`? I didn't find any specifications for this behavior, but returning `realOffset` is more consistent with linux filesystem.

File: br/pkg/lightning/mydump/region.go [hunk 2]
```diff
@@ -268,7 +268,7 @@ func makeSourceFileRegion(
 	}
 	// If a csv file is overlarge, we need to split it into multiple regions.
 	// Note: We can only split a csv file whose format is strict.
-	if isCsvFile && dataFileSize > int64(cfg.Mydumper.MaxRegionSize) && cfg.Mydumper.StrictFormat {
+	if isCsvFile && cfg.Mydumper.StrictFormat && dataFileSize > int64(cfg.Mydumper.MaxRegionSize)*11/10 {
```
Comment (gozssky) [inline br/pkg/lightning/mydump/region.go:271]: What happens if the file size if slightly bigger the `int64(cfg.Mydumper.MaxRegionSize)*11/10`? 🤣

Comment (glorv) [reply br/pkg/lightning/mydump/region.go:271]: Then the file will be split by `cfg.Mydumper.MaxRegionSize`, so the second chunk size is about 1/10 * cfg.Mydumper.MaxRegionSize.

Comment (gozssky) [reply br/pkg/lightning/mydump/region.go:271]: If the file size is slightly bigger the `int64(cfg.Mydumper.MaxRegionSize)* 2`, the third chunk size is very small, will this be a problem?

Comment (glorv) [reply br/pkg/lightning/mydump/region.go:271]: Not a big problem. The common case is that the data export tool (like dumpling or mydumper) set the exported file size with `cfg.Mydumper.MaxRegionSize`, but the output file size might be slightly bigger or smaller， so we can avoid split a lot of small chunks.

Comment (kennytm) [reply br/pkg/lightning/mydump/region.go:271]: make that 11/10 a named constant...

Comment (glorv) [reply br/pkg/lightning/mydump/region.go:274]: It will make the code a bit ugly because 11/10 is a float. I add a code comment to explain why the threshold need to be increased

File: br/pkg/storage/s3.go (hunk 1 above)
Comment (glorv) [reply br/pkg/storage/s3.go]: Fixed. I think we should return real position which is `r.rangeInfo.Size`, since the behavior isn't the same as linux fs. fs implement `ReaderWriter` and allow to write to a position that is larger that the current end and leave the file with a hole. But here we don't. Though there is no much difference.

**Review by gozssky — APPROVED** [review]

File: br/pkg/lightning/mydump/region.go (hunk 2 above)
Comment (kennytm) [reply br/pkg/lightning/mydump/region.go:274]: you can make "10" a constant and set the upper limit to `MaxRegionSize + MaxRegionSize/10`.

File: br/pkg/lightning/mydump/region.go [hunk 3]
```diff
@@ -30,7 +30,11 @@ import (
 	"go.uber.org/zap"
 )
 
-const tableRegionSizeWarningThreshold int64 = 1024 * 1024 * 1024
+const (
+	tableRegionSizeWarningThreshold int64 = 1024 * 1024 * 1024
+	// the increment ration of large CSV file size threshold by `region-split-size`
```
Comment (kennytm) [inline br/pkg/lightning/mydump/region.go:35]:
```suggestion
	// the increment ratio of large CSV file size threshold by `region-split-size`
```

**Review by kennytm — APPROVED** [review]
rest LGTM
