### PR TITLE
*: prevent cursor read from being cancelled by GC

### LINKED ISSUE #39447: The start tso in prepare statements does not calculated by GC safe point
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```java
    public static void main(String args[]) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://127.0.0.1:4000/test?useServerPrepStmts=true&rewriteBatchedStatements=true&useCursorFetch=true&defaultFetchSize=48", "root", "");
            Statement select = con.createStatement();
            PreparedStatement stmt1 = con.prepareStatement("insert into t1 values (?)");

            ResultSet rs = select.executeQuery("select * from t");
            while (rs.next()) {
                String i = rs.getString(1);
                System.out.println("i: " + i);
                stmt1.setString(1, i);
                stmt1.execute();
                Thread.sleep(10000);
            }

            rs.close();
            select.close();

            stmt1.close();

            Statement select1 = con.createStatement();
            ResultSet rs1 = select1.executeQuery("select * from t1");
            while (rs1.next()) {
                String i = rs1.getString(1);
                System.out.println("j: " + i);
            }
            rs1.close();
            select1.close();

            con.createStatement().execute("truncate table t1");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
```

When the thread is sleeping, run `select * from information_schema.processlist` to check out the TxnStart of the above session.

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

```
mysql> select * from information_schema.processlist;                                                                                                                                                                                                                                                               
+---------------------+------+-----------------------+------+---------+------+------------+----------------------------------------------+------------------------------------------------------------------+------+------+----------------------------------------+                                               
| ID                  | USER | HOST                  | DB   | COMMAND | TIME | STATE      | INFO                                         | DIGEST                                                           | MEM  | DISK | TxnStart                               |                                               
+---------------------+------+-----------------------+------+---------+------+------------+----------------------------------------------+------------------------------------------------------------------+------+------+----------------------------------------+                                               
| 4354866490457981331 | root | 172.16.120.219:52332  | test | Query   |    0 | autocommit | select * from information_schema.processlist | 4b5e7cdd5d3ed84d6c1a6d56403a3d512554b534313caf296268abdec1c9ea99 |    0 |    0 |                                        |                                               
| 4354866490457981335 | root | 114.248.173.229:42914 | test | Sleep   |    3 | autocommit | NULL                                         | e5796985ccafe2f71126ed6c0ac939ffa015a8c0744a24b7aee6d587103fd2f7 |    0 |    0 | 11-29 12:47:10.984(437701110919069699) |                                               
+---------------------+------+-----------------------+------+---------+------+------------+----------------------------------------------+------------------------------------------------------------------+------+------+----------------------------------------+  
```

### 3. What did you see instead (Required)

```
mysql> select * from information_schema.processlist;                                                                                                                                                                                                                                                               
+---------------------+------+-----------------------+------+---------+------+------------+----------------------------------------------+------------------------------------------------------------------+------+------+----------+                                                                             
| ID                  | USER | HOST                  | DB   | COMMAND | TIME | STATE      | INFO                                         | DIGEST                                                           | MEM  | DISK | TxnStart |                                                                             
+---------------------+------+-----------------------+------+---------+------+------------+----------------------------------------------+------------------------------------------------------------------+------+------+----------+                                                                             
| 2389247563250271241 | root | 172.16.120.219:45030  | test | Query   |    0 | autocommit | select * from information_schema.processlist | 4b5e7cdd5d3ed84d6c1a6d56403a3d512554b534313caf296268abdec1c9ea99 |    0 |    0 |          |                                                                             
| 2389247563250271245 | root | 114.248.173.229:57526 | test | Sleep   |   40 | autocommit | NULL                                         | e5796985ccafe2f71126ed6c0ac939ffa015a8c0744a24b7aee6d587103fd2f7 |    0 |    0 |          |                                                                             
+---------------------+------+-----------------------+------+---------+------+------------+----------------------------------------------+------------------------------------------------------------------+------+------+----------+                                                                             
2 rows in set (0.00 sec) 
```

### 4. What is your TiDB version? (Required)

v6.1.2
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

### What problem does this PR solve?

Issue Number: close #39447

Problem Summary: 

Cursor read might be cancelled by GC since min-start-ts is calculated by `min([s.ProcessInfo.CurTxnStartTS for s in all sessions])` however the `CurTxnStartTS` will be reset once fetch returned.

### What is changed and how it works?

1. Let each session hold a list of pretected timestamps.
2. Let session manager calculate the min-start-ts (considering protected timestamps).
3. When start to do cursor read, hold the start-ts until the result set gets close.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: sessionctx/variable/session.go [hunk 1]
```diff
@@ -1328,6 +1328,12 @@ type SessionVars struct {
 
 	// Resource group name
 	ResourceGroupName string
+
+	// protectedTSList holds a list of timestamps that should delay GC.
+	protectedTSList struct {
```
Comment (cfzjywxk) [inline sessionctx/variable/session.go:1333]: Is it possible to store `protectedTSList` in `ProcessInfo`, so the calculation source of GC safepoint always comes from the session `ProcessInfo` struct.

File: server/server.go [hunk 2]
```diff
@@ -970,3 +970,43 @@ func (s *Server) KillNonFlashbackClusterConn() {
 		s.Kill(id, false)
 	}
 }
+
+// GetMinStartTS implements SessionManager interface.
+func (s *Server) GetMinStartTS(lowerBound uint64) (ts uint64) {
+	// sys processes
```
Comment (TonsnakeLin) [inline server/server.go:976]: We may not pass this parameter `lowerBound` and get the min TS from all sessions. You already judge the TS returned with  `startTSLowerLimit` at https://github.com/pingcap/tidb/pull/39950/files#diff-d19169611c4613e5d3f09dc49da1c5d99bc6c7adb90a4b2ebbd75ac869806f50R705

Comment (zyguan) [reply server/server.go:976]: No, it should the minimum start-ts that greater than lowerBound, not the minimum start-ts of all.

File: sessionctx/variable/session.go (hunk 1 above)
Comment (zyguan) [reply sessionctx/variable/session.go:1333]: The protected ts list has the same lifetime as the session, however there are multiple processes during that session. So, we may let each process info within the same session hold a reference to the same ts list.

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Comment by TonsnakeLin** [comment]
There are two problems proposed by #39447. The first is the value of the field `TxnStart`  is empty when executing `select * from information_schema.processlist`. The second one is that gc safe point is not prevented by the executing query which gets data from TiDB using cursor mode of prepare protocol.

In fact, The [code ](https://github.com/pingcap/tidb/blob/master/server/conn_stmt.go#L332) has taken the first problem into account, but It can't resolve #39447 because it sleeps too long between every fetch. IMO, the workload proposed in #39447 is a very bad way, I can't find any scenes for sleeping so long time in production environment. I think the first problem is not worth so much effort to solve.

The second problem is that gc safe point is not prevented by fetching data using cursor. I think we should only add a little code as bellow at https://github.com/pingcap/tidb/blob/master/session/session.go#L1570.
`	if (command != mysql.ComSleep && !UseCursorMode()) || s.GetSessionVars().InTxn() {
		curTxnStartTS = s.sessionVars.TxnCtx.StartTS
	}
`

File: server/server.go (hunk 2 above)
Comment (TonsnakeLin) [reply server/server.go:976]: got it

**Comment by zyguan** [comment]
> The second problem is that gc safe point is not prevented by fetching data using cursor. I think we should only add a little code as bellow at https://github.com/pingcap/tidb/blob/master/session/session.go#L1570. ` if (command != mysql.ComSleep && !UseCursorMode()) || s.GetSessionVars().InTxn() { curTxnStartTS = s.sessionVars.TxnCtx.StartTS } `

No, user can hold multiple cursors same time, a single `curTxnStartTs` is not enough to solve it. The issue #39447 has metioned it.

File: server/server.go [hunk 3]
```diff
@@ -970,3 +970,37 @@ func (s *Server) KillNonFlashbackClusterConn() {
...
+			if thisTS := client.ctx.ShowProcess().GetMinStartTS(lowerBound); thisTS > lowerBound && (thisTS < ts || ts == 0) {
+				ts = thisTS
+			}
+		}
+	}()
+	// internal sessions
+	func() {
+		s.sessionMapMutex.Lock()
+		defer s.sessionMapMutex.Unlock()
+		analyzeProcID := util.GetAutoAnalyzeProcID(s.ServerID)
```
Comment (jackysp) [inline server/server.go:998]: I think it is unnecessary now because the analyze-statement will not be affected by GC after v6.2.0. Maybe it is helpful for v6.1?

Comment (zyguan) [reply server/server.go:998]: I think `analyzeProcID` is used to exclude analyze proc [here](https://github.com/pingcap/tidb/pull/39950/files#diff-78f42ba40d0f10b08c73b7e6bb8376f398e249c963cf549e89591d6b6826b9a4R1000). I just copy the logic of [GetInternalSessionStartTSList](https://github.com/pingcap/tidb/blob/97a9e63d789ea5bace36b82526ea105a1ac65891/server/server.go#L896-L910) here to:
1. let the session manager export a method for calculating the min-start-ts of all sessions (instead of calculating it in `InfoSyncer.ReportMinStartTS`).
2. avoid allocating slices for process info and internal start ts.

Comment (jackysp) [reply server/server.go:998]: Ok.

**Review by jackysp — APPROVED** [review]
LGTM
