### PR TITLE
plan, parser: fix the wrong result of the `UNION` statement

### LINKED ISSUE #6731: Diff result with mysql for statement with `union` and `union all`
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
create table t(a int, b int, c int);
insert into t values (1,2,3);
select * from t union select * from t union all select * from t;
```
2. What did you expect to see?

```sql
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    1 |    2 |    3 |
|    1 |    2 |    3 |
+------+------+------+
```

3. What did you see instead?

```sql
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    1 |    2 |    3 |
+------+------+------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master

### PR DESCRIPTION
**Pull request by lysu**
tidb diff result with mysql when mix use union and union-all

fix #6731

## What have you changed? (mandatory)

- modify parser to tag every selectStmt under unionStmt with `UnionDistinct` flag 
- let plan builder to last last union-distinct as pivot
- build a distinct plan use element before pivot, and make it as child of no distinct plan use element after pivot

so, it will work like https://dev.mysql.com/doc/refman/5.7/en/union.html

> You can mix UNION ALL and UNION DISTINCT in the same query. Mixed UNION types are treated such that a DISTINCT union overrides any ALL union to its left. A DISTINCT union can be produced explicitly by using UNION DISTINCT or implicitly by using UNION with no following DISTINCT or ALL keyword.

## What are the type of the changes (mandatory)?

Bug Fix

## How has this PR been tested (mandatory)?

- manual tested
- unit test in logical_plan_test.go
- integration test in executor_test.go

## Does this PR affect documentation (docs/docs-cn) update? (optional)

No, it make behaviour like mysql

## Refer to a related PR or issue link (optional)

https://github.com/pingcap/tidb/issues/6731

## Add a few positive/negative examples (optional)

see #6731

### CODE REVIEW

File: ast/dml.go [hunk 1]
```diff
@@ -476,6 +476,8 @@ type SelectStmt struct {
 	LockTp SelectLockType
 	// TableHints represents the table level Optimizer Hint for join type
 	TableHints []*TableOptimizerHint
+	// UnionDistinct is mark flag that previous union is distinct
+	UnionDistinct bool
```
Comment (zz-jason) [inline ast/dml.go]: s/UnionDistinct/HasUnionDistinct/?

File: plan/logical_plan_builder.go [hunk 2]
```diff
@@ -680,19 +711,57 @@ func (b *planBuilder) buildUnion(union *ast.UnionStmt) LogicalPlan {
...
 	}
-	return p
+	b.buildProjection4Union(u)
+	var p LogicalPlan = u
+	return &p
+}
+
+func findDistinctPivot(union *ast.UnionStmt) int {
+	distinctPivot := len(union.SelectList.Selects)
+	if union.Distinct {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: how about:
```go
if !union.Distinct
    return 0
}
```

File: plan/logical_plan_builder.go [hunk 3]
```diff
@@ -680,19 +711,57 @@ func (b *planBuilder) buildUnion(union *ast.UnionStmt) LogicalPlan {
...
+		for distinctPivot > 0 { // 0 must be false
+			if union.SelectList.Selects[distinctPivot-1].UnionDistinct {
+				break
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: can we `return distinctPivot` here?

File: plan/logical_plan_builder.go [hunk 4]
```diff
@@ -668,10 +668,41 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	}
+
+	if union.Limit != nil {
+		p = b.buildLimit(p, union.Limit)
+	}
+
+	return p
+}
+
+func (b *planBuilder) buildUnionDistinct(unionStmt *ast.UnionStmt, distinctPivot int) *LogicalPlan {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: we can just make the return value to be `LogicalPlan`.

File: plan/logical_plan_builder.go [hunk 5]
```diff
@@ -680,19 +711,57 @@ func (b *planBuilder) buildUnion(union *ast.UnionStmt) LogicalPlan {
...
-
 	b.buildProjection4Union(u)
 	var p LogicalPlan = u
-	if union.Distinct {
-		p = b.buildDistinct(u, u.Schema().Len())
+	p = b.buildDistinct(u, u.Schema().Len())
+	return &p
+}
+
+func (b *planBuilder) buildUnionAll(unionDistinct *LogicalPlan, unionStmt *ast.UnionStmt, distinctPivot int) *LogicalPlan {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: ditto

File: plan/logical_plan_builder.go [hunk 6]
```diff
@@ -680,19 +711,57 @@ func (b *planBuilder) buildUnion(union *ast.UnionStmt) LogicalPlan {
...
+	u.children = make([]LogicalPlan, unionAllCount)
+	i := 0
+	j := distinctPivot
+	for j < len(unionStmt.SelectList.Selects) {
+		u.children[i] = b.buildSelect(unionStmt.SelectList.Selects[j])
+		if b.err != nil {
+			return nil
+		}
+		if u.children[i].Schema().Len() != u.children[0].Schema().Len() {
+			b.err = errors.New("The used SELECT statements have a different number of columns")
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: use `mysql.ErrWrongNumberOfColumnsInSelect` instead

File: plan/logical_plan_builder.go [hunk 7]
```diff
@@ -680,19 +711,57 @@ func (b *planBuilder) buildUnion(union *ast.UnionStmt) LogicalPlan {
 			return nil
 		}
 	}
-
 	b.buildProjection4Union(u)
 	var p LogicalPlan = u
-	if union.Distinct {
-		p = b.buildDistinct(u, u.Schema().Len())
+	p = b.buildDistinct(u, u.Schema().Len())
+	return &p
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: why remove the building of `order by` and `limit`?

File: plan/logical_plan_test.go [hunk 8]
```diff
@@ -1428,6 +1428,49 @@ func checkVisitInfo(c *C, v1, v2 []visitInfo, comment CommentInterface) {
...
+func (s *testPlanSuite) TestUnion(c *C) {
+	defer func() {
+		testleak.AfterTest(c)()
+	}()
+	tests := []struct {
+		sql  string
+		best string
+	}{
+		{
+			sql:  "select a from t union select a from t",
```
Comment (zz-jason) [inline plan/logical_plan_test.go]: It is recommended to add these tests into the `explain-test`.

File: plan/logical_plan_builder.go [hunk 9]
```diff
@@ -680,19 +711,57 @@ func (b *planBuilder) buildUnion(union *ast.UnionStmt) LogicalPlan {
...
-	return p
+	b.buildProjection4Union(u)
+	var p LogicalPlan = u
+	return &p
+}
+
+func findDistinctPivot(union *ast.UnionStmt) int {
+	distinctPivot := len(union.SelectList.Selects)
+	if union.Distinct {
+		for distinctPivot > 0 { // 0 must be false
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: for ; distinctPivot > 0; distinctPivot{
}

File: plan/logical_plan_builder.go (hunk 5 above)
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: we can just use unionStmt.SelectList.Selects as input parameter.

File: plan/logical_plan_builder.go [hunk 10]
```diff
@@ -680,19 +711,57 @@ func (b *planBuilder) buildUnion(union *ast.UnionStmt) LogicalPlan {
...
 	b.buildProjection4Union(u)
 	var p LogicalPlan = u
-	if union.Distinct {
-		p = b.buildDistinct(u, u.Schema().Len())
+	p = b.buildDistinct(u, u.Schema().Len())
+	return &p
+}
+
+func (b *planBuilder) buildUnionAll(unionDistinct *LogicalPlan, unionStmt *ast.UnionStmt, distinctPivot int) *LogicalPlan {
+	if distinctPivot == len(unionStmt.SelectList.Selects) {
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: extract `len(unionStmt.SelectList.Selects)` as selectsLen so it can be reused.

**Comment by coocood** [comment]
@lysu 
There is a lot of duplicate code in `buildUnionDistinct` and `buildUnionAll`.
How about we build the children in this method, then extract the distinct children to build distinct?

File: ast/dml.go (hunk 1 above)
Comment (lysu) [reply ast/dml.go]: Finally, I use `IsAfterUnionDistinct` to indicates whether it's a stmt after "union distinct" one

**Comment by lysu** [comment]
PTAL @coocood @zz-jason @XuHuaiyu @lamxTyler thx~

**Comment by coocood** [comment]
@lysu How about we build children first, then split the children to build union?

File: plan/logical_plan_builder.go [hunk 11]
```diff
@@ -668,31 +668,76 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	}
 	u := LogicalUnionAll{}.init(b.ctx)
-	u.children = make([]LogicalPlan, len(union.SelectList.Selects))
-	for i, sel := range union.SelectList.Selects {
-		u.children[i] = b.buildSelect(sel)
+	childLen := len(selects)
+	if subPlan != nil {
+		childLen = childLen + 1
+	}
+	u.children = make([]LogicalPlan, childLen)
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: Remove line 717~720
u.children = make([]LogicalPlan, 0, len(selects)+1)

File: plan/logical_plan_builder.go [hunk 12]
```diff
@@ -668,31 +668,76 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	i := 0
+	for ; i < len(selects); i++ {
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: for _, select := range selectes {
    u.children = append(u.children, b.buildSelect(select))
}

File: plan/logical_plan_builder.go [hunk 13]
```diff
@@ -668,31 +668,76 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
-
-	b.buildProjection4Union(u)
-	var p LogicalPlan = u
-	if union.Distinct {
-		p = b.buildDistinct(u, u.Schema().Len())
-	}
-	if union.OrderBy != nil {
-		p = b.buildSort(p, union.OrderBy.Items, nil)
+	if subPlan != nil {
+		u.children[i] = subPlan
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: ditto
u.children = append(...)

File: plan/logical_plan_builder.go [hunk 14]
```diff
@@ -668,31 +668,76 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	}
+	if union.Limit != nil {
+		unionPlan = b.buildLimit(unionPlan, union.Limit)
+	}
+	return unionPlan
+}
+
+// classifyByDistinct to divide selects into union-all and union-distinct slices.
+// https://dev.mysql.com/doc/refman/5.7/en/union.html
+func classifyByDistinct(selects []*ast.SelectStmt) (unionDistinct []*ast.SelectStmt, unionAll []*ast.SelectStmt) {
```
[the remark this answers is not in the document]
Comment (lysu) [reply plan/logical_plan_builder.go]: It is not `resolve`(to find a solution to a problem) but `classify`(
to put people or things into particular groups according to the features that they have)

File: plan/logical_plan_builder.go (hunk 11 above)
Comment (lysu) [reply plan/logical_plan_builder.go]: make(type, 0, n + 1), still waste 1, but for clear I am agree that.

Comment (zhexuany) [reply plan/logical_plan_builder.go]: What do you mean by saying "hate 1 if no sub plan"? `make([]LogicalPlan, 0, len(selects)+1)` only update the capacity.

Comment (lysu) [reply plan/logical_plan_builder.go]: @zhexuany `make([]int, 0, n+1)`'s has more memory footprint than `make([]int, 0, n)`.
u may try `ulimit -Sv 2000000` then go build and run `a := make([]int, 0, math.MaxInt32);a = a;time.Sleep(time.Hour * 1)` to check.

but In this case I use +1 after last commit.

**Comment by lysu** [comment]
hello @coocood @zz-jason @XuHuaiyu @lamxTyler PTAL again thx~

**Comment by lysu** [comment]
hello @coocood @zz-jason @XuHuaiyu @lamxTyler PTAL again thx~

**Comment by lysu** [comment]
hello @coocood @zz-jason @XuHuaiyu @lamxTyler PTAL, and need any change??

File: plan/logical_plan_builder.go [hunk 15]
```diff
@@ -668,31 +668,86 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
 	}
 	if union.Limit != nil {
-		p = b.buildLimit(p, union.Limit)
+		unionPlan = b.buildLimit(unionPlan, union.Limit)
 	}
-	return p
+	return unionPlan
+}
+
+// resolveUnionSelectPlans to resolve union's select stmts to logical plans.
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: s/ to resolve/ resolves

File: plan/logical_plan_builder.go [hunk 16]
```diff
@@ -668,31 +668,86 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+// and divide result plans into "union-distinct" and "union-all" parts.
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: s/ divide/ divides
and it seems, `divideUnionSelectPlans` is better than `resolveUnionSelectPlans` ^_^

File: plan/logical_plan_builder.go [hunk 17]
```diff
@@ -668,31 +668,86 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	unionDistinctPlan := b.buildSubUnion(distinctSelectPlans)
+	if b.err != nil {
+		return nil
 	}
+
+	if unionDistinctPlan != nil {
+		unionDistinctPlan = b.buildDistinct(unionDistinctPlan, unionDistinctPlan.Schema().Len())
+	}
+
+	if unionDistinctPlan != nil && allSelectPlans != nil && len(allSelectPlans) != 0 {
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: put this check in line 683.

File: plan/logical_plan_builder.go [hunk 18]
```diff
@@ -668,31 +668,86 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+// resolveUnionSelectPlans to resolve union's select stmts to logical plans.
+// and divide result plans into "union-distinct" and "union-all" parts.
+// divide rule ref: https://dev.mysql.com/doc/refman/5.7/en/union.html
+// "Mixed UNION types are treated such that a DISTINCT union overrides any ALL union to its left."
+func (b *planBuilder) resolveUnionSelectPlans(selects []*ast.SelectStmt) (distinctSelects []LogicalPlan, allSelects []LogicalPlan) {
+	if selects == nil || len(selects) == 0 {
+		return nil, nil
+	}
+	firstUnionAllIdx, columnNums := 0, -1
+	children := make([]LogicalPlan, len(selects), len(selects)+1) // preserve one for later distinct-all append
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: 1. put this comment upon this line
2. The last slot is reserved for appending `distinct union` outside this function.

File: plan/logical_plan_builder.go [hunk 19]
```diff
@@ -668,31 +668,86 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+			b.err = ErrWrongNumberOfColumnsInSelect.GenByArgs()
+			return nil, nil
+		}
+		children[i] = selectPlan
+	}
+	return children[:firstUnionAllIdx], children[firstUnionAllIdx:]
+}
+
+func (b *planBuilder) buildSubUnion(children []LogicalPlan) LogicalPlan {
+	if children == nil || len(children) == 0 {
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: When will this check be true?

File: plan/logical_plan_builder.go [hunk 20]
```diff
@@ -668,31 +668,86 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	if b.err != nil {
+		return nil
+	}
+
+	var unionPlan LogicalPlan
+	if unionAllPlan != nil {
+		unionPlan = unionAllPlan
+	} else if unionDistinctPlan != nil {
+		unionPlan = unionDistinctPlan
+	} else {
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: Will the else branch happen?
Can we this if-else to:
``` go
if unionAllPlan != nil {
	return unionAllPlan
} 
return unionDistinctPlan
```

Comment (lysu) [reply plan/logical_plan_builder.go]: in first version, else will happen, but now we check `b.err` to fail fast return, so it never happen, I will remove that~

File: plan/logical_plan_builder.go (hunk 19 above)
Comment (lysu) [reply plan/logical_plan_builder.go]: children will keep nil, but len==0 when all `union-all` or all `union-distinct`, so we will remove nil check.

**Comment by lysu** [comment]
@XuHuaiyu PTAL~ thx

File: plan/logical_plan_builder.go [hunk 21]
```diff
@@ -668,31 +668,79 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	// The last slot is reserved for appending distinct union outside this function.
+	children := make([]LogicalPlan, len(selects), len(selects)+1)
+	for i := len(selects) - 1; i >= 0; i-- {
+		stmt := selects[i]
+		if firstUnionAllIdx == 0 && stmt.IsAfterUnionDistinct {
+			firstUnionAllIdx = i + 1
+		}
+		selectPlan := b.buildSelect(stmt)
+		if b.err != nil {
+			return nil, nil
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: set `b.err = errors.Trace(b.err)` before return

File: plan/logical_plan_builder.go [hunk 22]
```diff
@@ -668,31 +668,79 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+}
+
+// divideUnionSelectPlans resolves union's select stmts to logical plans.
+// and divide result plans into "union-distinct" and "union-all" parts.
+// divide rule ref: https://dev.mysql.com/doc/refman/5.7/en/union.html
+// "Mixed UNION types are treated such that a DISTINCT union overrides any ALL union to its left."
+func (b *planBuilder) divideUnionSelectPlans(selects []*ast.SelectStmt) (distinctSelects []LogicalPlan, allSelects []LogicalPlan) {
+	firstUnionAllIdx, columnNums := 0, -1
+	// The last slot is reserved for appending distinct union outside this function.
+	children := make([]LogicalPlan, len(selects), len(selects)+1)
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: can we just `children := make([]LogicalPlan, len(selects))`?

File: plan/logical_plan_builder.go [hunk 23]
```diff
@@ -668,31 +668,79 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+	}
+
+	unionDistinctPlan := b.buildSubUnion(distinctSelectPlans)
+	if b.err != nil {
+		return nil
+	}
+
+	if unionDistinctPlan != nil {
+		unionDistinctPlan = b.buildDistinct(unionDistinctPlan, unionDistinctPlan.Schema().Len())
+		if allSelectPlans != nil && len(allSelectPlans) != 0 {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: can be replaced with `len(allSelectPlans) > 0`

File: plan/logical_plan_builder.go [hunk 24]
```diff
@@ -668,31 +668,79 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
-			b.err = errors.New("The used SELECT statements have a different number of columns")
-			return nil
+	distinctSelectPlans, allSelectPlans := b.divideUnionSelectPlans(union.SelectList.Selects)
+	if b.err != nil {
+		return nil
+	}
+
+	unionDistinctPlan := b.buildSubUnion(distinctSelectPlans)
+	if b.err != nil {
+		return nil
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: set `b.err = errors.Trace(b.err)` before `return`.

File: plan/logical_plan_builder.go [hunk 25]
```diff
@@ -668,31 +668,79 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
 		}
 	}
 
-	b.buildProjection4Union(u)
-	var p LogicalPlan = u
-	if union.Distinct {
-		p = b.buildDistinct(u, u.Schema().Len())
+	unionAllPlan := b.buildSubUnion(allSelectPlans)
+	if b.err != nil {
+		return nil
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: ditto

File: plan/logical_plan_builder.go [hunk 26]
```diff
@@ -668,31 +668,79 @@ func (b *planBuilder) buildProjection4Union(u *LogicalUnionAll) {
...
+			b.err = ErrWrongNumberOfColumnsInSelect.GenByArgs()
+			return nil, nil
+		}
+		children[i] = selectPlan
+	}
+	return children[:firstUnionAllIdx], children[firstUnionAllIdx:]
+}
+
+func (b *planBuilder) buildSubUnion(subPlan []LogicalPlan) LogicalPlan {
+	if len(subPlan) == 0 {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: maybe check this before calling `buildSubUnion` is more readable and can remove some duplicated check in `buildUnion`?

File: plan/logical_plan_builder.go (hunk 22 above)
Comment (lysu) [reply plan/logical_plan_builder.go]: we can, but `+1` in here is by design~

this function will build 2 slices(first one for need union-distinct, later one for need union-all).
and we reserved +1 capacity here, because later we will build union-all plan children plan by concat union-distinct slice with a optional union-distinct plan.
if we aren't use `len(selects)` here, later `append()` will over capacity and make do some expand.

File: plan/logical_plan_builder.go (hunk 26 above)
Comment (lysu) [reply plan/logical_plan_builder.go]: `buildSubUnion` will be call multiple place and different context, move it out will break encapsulation of buildSubUnion，and make `buildUnion` too many detail and harder to read as i think~

**Comment by zz-jason** [comment]
I think we need to cherry pick this patch to release 2.0. @lysu
