### PR TITLE
planner: fix prepared plan cache checker for CTE names

### LINKED ISSUE #66351: prepared plan cache skips CTE statement with find table test.cte failed
### 1. Bug Description

A prepared statement that contains a CTE is skipped by prepared plan cache.

TiDB emits the warning below:

```text
skip prepared plan-cache: find table test.cte failed: [schema:1146]Table 'test.cte' doesn't exist
```

### 2. Minimal Reproduction

<details>
<summary>Apply schema</summary>

```sql
DROP TABLE IF EXISTS v2;
CREATE TABLE v2 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    group_name VARCHAR(50),
    sum1 INT NOT NULL COMMENT 'group sum value',
    cnt INT NOT NULL COMMENT 'group count',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sum1 ON v2(sum1);
CREATE INDEX idx_cnt ON v2(cnt);
```

</details>

Run the query:

```sql
SET @@tidb_enable_prepared_plan_cache = 1;

PREPARE stmt FROM 'WITH cte AS (
    SELECT sum1 AS c0, cnt AS c1
    FROM v2
    WHERE sum1 = 100
)
SELECT c1
FROM cte
WHERE c1 = 5';

EXECUTE stmt;
EXECUTE stmt;
SHOW WARNINGS;
SELECT @@last_plan_from_cache;
```

### 3. Expected Behavior

- No warning about missing table `test.cte`.
- The second `EXECUTE stmt` should be cacheable and hit prepared plan cache (`@@last_plan_from_cache = 1`).

### 4. Actual Behavior

`SHOW WARNINGS` includes:

| Level | Code | Message |
| --- | --- | --- |
| Warning | 1105 | skip prepared plan-cache: find table test.cte failed: [schema:1146]Table 'test.cte' doesn't exist |

`@@last_plan_from_cache` stays `0`.

### 5. Impact

Prepared statements using CTE cannot benefit from prepared plan cache, which can hurt repeated-query latency/throughput.

### 6. Environment

- TiDB version: (please fill exact version)
- Deployment: (please fill, e.g. local / TiUP / TiDB Cloud)
- OS: (please fill)

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #66351

Problem Summary:
Prepared statements containing CTEs are incorrectly marked as uncacheable by the prepared plan cache checker with warning:
`skip prepared plan-cache: find table <db>.cte failed`.
The checker treats CTE names as physical tables and looks them up in InfoSchema.

### What changed and how does it work?
- Track CTE visibility scope in `cacheableChecker` while traversing AST nodes.
- Skip physical table lookup in `checkTableCacheable` path when a `TableName` is a visible CTE reference.
- Add regression test for issue #66351 to verify:
  - no warning at `PREPARE`
  - second `EXECUTE` hits prepared plan cache (`@@last_plan_from_cache = 1`).

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix prepared plan cache checker to correctly handle CTE table names.
```

### CODE REVIEW

File: pkg/planner/core/plan_cacheable_checker.go [hunk 1]
```diff
@@ -165,6 +176,10 @@ func (checker *cacheableChecker) Enter(in ast.Node) (out ast.Node, skipChildren
 		}
 	case *ast.TableName:
 		if checker.schema != nil {
+			if node.Schema.L == "" && slices.Contains(checker.cteCanUsed, node.Name.L) {
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/plan_cacheable_checker.go:182]: Good catch, thanks. I fixed this by adding query-block-level CTE scope push/pop (for SelectStmt / SetOprStmt / SetOprSelectList when With != nil) so CTE names defined in a derived table do not leak to outer traversal. I also added a regression in TestCacheable with a derived-table WITH case (`select * from (with t1 as (...) select * from t1) dt, t1`) to ensure the outer `t1` is still checked as a physical table.

File: pkg/planner/core/plan_cacheable_checker.go [hunk 2]
```diff
@@ -113,13 +134,17 @@ func (checker *cacheableChecker) Enter(in ast.Node) (out ast.Node, skipChildren
...
+		return in, checker.skipForSubqueryDisabled()
+	case *ast.CommonTableExpression:
+		checker.cteOffset = append(checker.cteOffset, len(checker.cteCanUsed))
+		if node.IsRecursive {
+			checker.cteCanUsed = append(checker.cteCanUsed, node.Name.L)
 		}
 		return in, false
+	case *ast.SubqueryExpr:
+		checker.cteOffset = append(checker.cteOffset, len(checker.cteCanUsed))
+		return in, checker.skipForSubqueryDisabled()
```
Comment (winoros) [inline pkg/planner/core/plan_cacheable_checker.go:136]: I think we don't need this.
e.g.
Image
The `*ast.CommonTableExpression` is the definition of one CTE. There's no need to maintain the stack when we enter/leave it.

Comment (hawkingrei) [reply pkg/planner/core/plan_cacheable_checker.go:136]: I have updated.

File: pkg/planner/core/plan_cacheable_checker.go [hunk 3]
```diff
@@ -84,11 +87,21 @@ type cacheableChecker struct {
 
 	sumInListLen int // the accumulated number of elements in all in-lists
 	maxNumParam  int
+	// cteCanUsed tracks CTE names visible at current traversal point.
+	cteCanUsed []string
+	// cteOffset stores stack offsets for restoring cteCanUsed in Leave for CTE/subquery scopes.
+	cteOffset []int
```
Comment (winoros) [inline pkg/planner/core/plan_cacheable_checker.go]: unused now

Comment (hawkingrei) [reply pkg/planner/core/plan_cacheable_checker.go]: Removed.

**Review by winoros — DISMISSED** [review]

File: pkg/planner/core/plan_cacheable_checker.go [hunk 4]
```diff
@@ -113,13 +126,17 @@ func (checker *cacheableChecker) Enter(in ast.Node) (out ast.Node, skipChildren
...
-			checker.cacheable = false
-			checker.reason = "query has sub-queries is un-cacheable"
-			return in, true
+	case *ast.ExistsSubqueryExpr:
+		return in, checker.skipForSubqueryDisabled()
+	case *ast.CommonTableExpression:
+		checker.cteOffset = append(checker.cteOffset, len(checker.cteCanUsed))
+		if node.IsRecursive {
+			checker.cteCanUsed = append(checker.cteCanUsed, node.Name.L)
 		}
```
Comment (winoros) [inline pkg/planner/core/plan_cacheable_checker.go:133]: Only keep this maintenance and remove the stack helper

Comment (winoros) [reply pkg/planner/core/plan_cacheable_checker.go:133]: I've given you a diff offline.

Comment (hawkingrei) [reply pkg/planner/core/plan_cacheable_checker.go:133]: Completed.

File: pkg/planner/core/plan_cacheable_checker.go [hunk 5]
```diff
@@ -113,13 +123,15 @@ func (checker *cacheableChecker) Enter(in ast.Node) (out ast.Node, skipChildren
...
-	case *ast.ExistsSubqueryExpr, *ast.SubqueryExpr:
-		if !checker.sctx.GetSessionVars().EnablePlanCacheForSubquery {
-			checker.cacheable = false
-			checker.reason = "query has sub-queries is un-cacheable"
-			return in, true
+	case *ast.ExistsSubqueryExpr:
+		return in, checker.skipForSubqueryDisabled()
+	case *ast.CommonTableExpression:
+		if node.IsRecursive {
+			checker.cteCanUsed = append(checker.cteCanUsed, node.Name.L)
```
Comment (winoros) [inline pkg/planner/core/plan_cacheable_checker.go:132]: Add comments for the place we append things to the stack.

File: pkg/planner/core/plan_cacheable_checker.go [hunk 6]
```diff
@@ -174,11 +190,40 @@ func (checker *cacheableChecker) Enter(in ast.Node) (out ast.Node, skipChildren
...
+	return false
+}
+
 // Leave implements Visitor interface.
 func (checker *cacheableChecker) Leave(in ast.Node) (out ast.Node, ok bool) {
+	switch node := in.(type) {
+	case *ast.CommonTableExpression:
+		if !node.IsRecursive {
+			checker.cteCanUsed = append(checker.cteCanUsed, node.Name.L)
+		}
```
Comment (winoros) [inline pkg/planner/core/plan_cacheable_checker.go:211]: and here

File: pkg/planner/core/plan_cacheable_checker.go (hunk 5 above)
Comment (hawkingrei) [reply pkg/planner/core/plan_cacheable_checker.go:132]: I added comments.

File: pkg/planner/core/plan_cacheable_checker.go (hunk 6 above)
Comment (hawkingrei) [reply pkg/planner/core/plan_cacheable_checker.go:211]: I added comments.
