### PR TITLE
global sort: lower memLimit and other memory control change

### LINKED ISSUE #49829: tidb oom when import into with global sort and inject some fault during import into running
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb（8c/16g）
1、tidb_enable_dist_task='on' and enable global sort
2、run import into
3、inject some fault 

oom when run this three cases

1、kill one of tikv during import into
tidb-1 oom at 2023-12-26 18:51:12
image

2、inject network partition between one of tikv  and other pods
tidb-1 oom at 2023-12-26 20:20:49
image

3、inject network latency 50ms between one of tikv and other pods
tidb-0 oom at 2023-12-27 00:04:25
image

### 2. What did you expect to see? (Required)
no oom

### 3. What did you see instead (Required)
oom when inject some fault

some logs：
[endless-ha-test-import-into-tps-5341375-1-16.zip](https://github.com/pingcap/tidb/files/13776082/endless-ha-test-import-into-tps-5341375-1-16.zip)

[2023/12/26 18:51:00.375 +08:00] [WARN] [servermemorylimit.go:180] ["global memory controller tries to kill the top1 memory consumer, but no one larger than tidb_server_memory_limit_sess_min_size is found"] [tidb_server_memory_limit_sess_min_size=134217728]
[2023/12/26 18:51:00.532 +08:00] [INFO] [byte_reader.go:281] ["switch reader mode"] ["use concurrent mode"=true]
[2023/12/26 18:51:00.550 +08:00] [INFO] [byte_reader.go:281] ["switch reader mode"] ["use concurrent mode"=true]
[2023/12/26 18:51:01.218 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:01.759 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=2] [dropBytes=131634267] [curBufIdx=0]
[2023/12/26 18:51:01.927 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.052 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=2] [dropBytes=131427273] [curBufIdx=0]
[2023/12/26 18:51:02.072 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.105 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.155 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.172 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.175 +08:00] [WARN] [memoryusagealarm.go:215] ["tidb-server has the risk of OOM because of memory usage grows too fast. Running SQLs and heap profile will be recorded in record path"] ["is tidb_server_memory_limit set"=true] [tidb_server_memory_limit=13743895280] ["tidb-server memory usage"=14009146768] [memory-usage-alarm-ratio=0.7] ["record path"=/var/lib/tidb/log/oom_record]
[2023/12/26 18:51:02.232 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=2] [dropBytes=69018582] [curBufIdx=0]
[2023/12/26 18:51:02.310 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.341 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=2] [dropBytes=131634267] [curBufIdx=0]
[2023/12/26 18:51:02.367 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.431 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=2] [dropBytes=6713388] [curBufIdx=0]
[2023/12/26 18:51:02.451 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:02.618 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=2] [dropBytes=131737764] [curBufIdx=0]
[2023/12/26 18:51:02.684 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=2] [dropBytes=131530770] [curBufIdx=0]
[2023/12/26 18:51:04.278 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:04.845 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]
[2023/12/26 18:51:05.420 +08:00] [INFO] [byte_reader.go:321] ["drop data in closeConcurrentReader"] [reloadCnt=3] [dropBytes=0] [curBufIdx=1]

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.6.0-alpha
Edition: Community
Git Commit Hash: 07e9ece9107536fad2d5df7664809350f0ce0a4a
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2023-12-25 11:44:42
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2023-12-26T18:31:05.717+0800

### LINKED ISSUE #50753: 20T GCS IMPORT INTO test OOM

### LINKED ISSUE #50755: 20T IMPORT INTO test failed because `http2: client connection force closed via ClientConn.Close` error

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #49829 close #50753 close #50755
Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test

Pass a 20T test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/external/engine.go [hunk 1]
```diff
@@ -121,7 +125,7 @@ type Engine struct {
 	importedKVCount *atomic.Int64
 }
 
-const memLimit = 16 * 1024 * 1024 * 1024
+const memLimit = 12 * 1024 * 1024 * 1024
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/external/engine.go:128]:
```suggestion
const memLimit = 12 * units.GiB
```

File: br/pkg/lightning/backend/local/localhelper.go [hunk 2]
```diff
@@ -410,10 +410,8 @@ func (local *Backend) BatchSplitRegions(
 			// Wait for a while until the regions successfully splits.
 			ok, err2 := local.hasRegion(ctx, region.Region.Id)
 			if !ok || err2 != nil {
-				if err2 == nil {
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/local/localhelper.go:413]: why remove this branch?

File: br/pkg/membuf/limiter.go [hunk 3]
```diff
@@ -56,6 +57,10 @@ func (l *Limiter) Release(n int) {
 	l.mu.Lock()
 
 	l.limit += n
+	if l.limit > l.initLimit {
+		panic("limit overflow")
+	}
```
Comment (D3Hunter) [inline br/pkg/membuf/limiter.go:62]: when will this happen? can we use other way to handle it, log?

File: br/pkg/lightning/backend/local/localhelper.go (hunk 2 above)
Comment (lance6716) [reply br/pkg/lightning/backend/local/localhelper.go:413]: it will print lots of log, each line for one region, so I removed this branch. For `err2 == nil` case we still can get the total failed number of regions in line 428

File: br/pkg/membuf/limiter.go (hunk 3 above)
Comment (lance6716) [reply br/pkg/membuf/limiter.go:62]: I want to fail fast to debug the problem

Comment (lance6716) [reply br/pkg/membuf/limiter.go:62]: This should not happen, I just suspect a memory problem is caused by it.

Comment (D3Hunter) [reply br/pkg/membuf/limiter.go:62]: can we change it to a log with stack, i think it's not a good idea to add panic explicitly for a daemon program except in initialization code

File: br/pkg/lightning/backend/external/byte_reader.go [hunk 4]
```diff
@@ -29,7 +29,7 @@ import (
 var (
 	// ConcurrentReaderBufferSizePerConc is the buffer size for concurrent reader per
 	// concurrency.
-	ConcurrentReaderBufferSizePerConc = int(4 * size.MB)
+	ConcurrentReaderBufferSizePerConc = int(2 * size.MB)
```
Comment (wjhuang2016) [inline br/pkg/lightning/backend/external/byte_reader.go:32]: Will it affect the performance?

Comment (lance6716) [reply br/pkg/lightning/backend/external/byte_reader.go:32]: In current way of using membuf.Pool, `ConcurrentReaderBufferSizePerConc `must be changed otherwise the ingest step will OOM. And 20T test shows the performance has no drop. I will test about more cases and use two pools of different sizes in future PR.

**Review by tangenta — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]
