### PR TITLE
ddl: prevent 'TEXT' columns without key length from being used in index

### LINKED ISSUE #23488: Text column can be used in index without key length
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (k varchar(10) primary key, v int);
alter table t change column k k tinytext;
show create table t;
```

### 2. What did you expect to see? (Required)

`alter table ...` should failed with `1170, "BLOB/TEXT column 'k' used in key specification without a key length"`

### 3. What did you see instead (Required)

All statements succeeded. `show create table t` prints as following
```sql
CREATE TABLE `t` (
  `k` tinytext NOT NULL,
  `v` int(11) DEFAULT NULL,
  PRIMARY KEY (`k`) /*T![clustered_index] NONCLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

Note that the `CREATE TABLE ...` statement will be rejected by both tidb and mysql. It may affect some backup/restore tools.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by thinkinnight**
### What problem does this PR solve?

Issue Number: close #23488

Problem Summary:

### What is changed and how it works?

Proposal: [Text column can be used in index without key length #23488](https://github.com/pingcap/tidb/issues/23488)

What's Changed:
- Add 1 function checkIndexInModifiableColumn in index.go, refer to checkIndexColumn.
- Add 1 function checkIndexInModifiableColumns in ddl_api.go.
- Add function call to checkIndexInModifiableColumns in checkColumnWithIndexConstraint in ddl_api.go.

How it Works:
As checkIndexColumn already done the check functions during createTable, so we can reuse the logic during alterTable.

### Check List

Tests

- Unit test
- As the function checkColumnWithIndexConstraint is also called by ModifyColumn, but as I donot know much about SQL. I only add TestChangeColumn for the unit test, but donot add TestModifyColumn, so if anyone can give the test scanrio, it would be good.

### Release note
- No release note.

### CODE REVIEW

File: ddl/index.go [hunk 1]
```diff
@@ -131,6 +131,54 @@ func checkIndexPrefixLength(columns []*model.ColumnInfo, idxColumns []*model.Ind
 	return nil
 }
 
+//The function is same as function checkIndexColumn, but the parameter is model.IndexColumn but not ast.IndexPartSpecification.
+func checkIndexInModifiableColumn(col *model.ColumnInfo, ic *model.IndexColumn) error {
```
Comment (tangenta) [inline ddl/index.go:135]: Could you please unify these two functions with 
```go
func checkIndex(col *model.ColumnInfo, prefixLen int)
```
to comply with the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)?

File: ddl/db_test.go [hunk 2]
```diff
@@ -2360,6 +2360,12 @@ func (s *testDBSuite4) TestChangeColumn(c *C) {
 	s.mustExec(tk, c, "alter table t3 add column a bigint")
 	sql = "alter table t3 change aa a bigint"
 	tk.MustGetErrCode(sql, errno.ErrDupFieldName)
+	//Bug fix on issue 23488
```
Comment (tangenta) [inline ddl/db_test.go:2363]:
```suggestion
	// https://github.com/pingcap/tidb/issues/23488
```

Comment (thinkinnight) [reply ddl/db_test.go]: doen

File: ddl/index.go (hunk 1 above)
Comment (thinkinnight) [reply ddl/index.go]: good suggestion, change as suggestion.

File: ddl/index.go [hunk 3]
```diff
@@ -131,12 +131,12 @@ func checkIndexPrefixLength(columns []*model.ColumnInfo, idxColumns []*model.Ind
...
 }
 
-func checkIndexColumn(col *model.ColumnInfo, ic *ast.IndexPartSpecification) error {
+func checkIndexColumn(col *model.ColumnInfo, columnLen int, columnName model.CIStr) error {
 	if col.Flen == 0 && (types.IsTypeChar(col.FieldType.Tp) || types.IsTypeVarchar(col.FieldType.Tp)) {
 		if col.GeneratedExprString != "" {
 			return errors.Trace(errWrongKeyColumnFunctionalIndex.GenWithStackByArgs(col.GeneratedExprString))
 		}
-		return errors.Trace(errWrongKeyColumn.GenWithStackByArgs(ic.Column.Name))
+		return errors.Trace(errWrongKeyColumn.GenWithStackByArgs(columnName))
```
Comment (tangenta) [inline ddl/index.go:139]: I believe we can use the name from `col *model.ColumnInfo`. Could you please check if it is possible?

Comment (thinkinnight) [reply ddl/index.go:139]: col is the table column, and columnName is from ic which is for index column, so it cannot be used from col. I have changed the parameter name to be more clear.

File: ddl/db_test.go [hunk 4]
```diff
@@ -2360,6 +2360,12 @@ func (s *testDBSuite4) TestChangeColumn(c *C) {
 	s.mustExec(tk, c, "alter table t3 add column a bigint")
 	sql = "alter table t3 change aa a bigint"
 	tk.MustGetErrCode(sql, errno.ErrDupFieldName)
+	// https://github.com/pingcap/tidb/issues/23488
+	s.mustExec(tk, c, "drop table if exists t5")
+	s.mustExec(tk, c, "create table t5 (k varchar(10) primary key, v int)")
+	sql = "alter table t5 change column k k tinytext;"
+	tk.MustGetErrCode(sql, mysql.ErrBlobKeyWithoutLength)
+	tk.MustExec("drop table t5")
```
Comment (wjhuang2016) [inline ddl/db_test.go:2368]: Please add the test that "if there is a prefix index on the varchar column, then we can change it to text".

File: ddl/index.go (hunk 3 above)
Comment (tangenta) [reply ddl/index.go]: There is no difference between "index column name" and "table column name". At the time calling this function, their names are equal to each other.

File: ddl/db_test.go (hunk 4 above)
Comment (thinkinnight) [reply ddl/db_test.go:2376]: @wjhuang2016 as I am new to go-lang, after I add the test code, I only cd ddl and use `go test` now, but the result seems have some fails, I want to run TestChangeColumn() only, and can you tell me how to run the UT usually when add some test code? Thanks!

File: ddl/index.go (hunk 3 above)
Comment (thinkinnight) [reply ddl/index.go]: @tangenta Yes, I've checked the code and find the name is the same, but about the length, it seems we cannot remove, so I will remove 1 parameter.

File: ddl/db_test.go (hunk 4 above)
Comment (tangenta) [reply ddl/db_test.go:2376]:
```bash
go test -v github.com/pingcap/tidb/ddl -check.f TestChangeColumn
```

Comment (thinkinnight) [reply ddl/db_test.go:2376]: @tangenta Thanks, after I run the UT, I found that you checkin some code yesterday, which pervent the conversion from varchar to non-varchar, which makes my UT code useless but check your scanrio.
And about the test scanrio @wjhuang2016 suggested ("if there is a prefix index on the varchar column, then we can change it to text"), it will pass in MySQL. But will fail in TiDB now with your checkin.
MySQL:
image

TiDB:
image

And also for #23488 , also TiDB behavior is different from MySQL
MySQL
image

TiDB
image

Could you please help to check?
Thanks!

File: ddl/db_test.go [hunk 5]
```diff
@@ -2340,6 +2340,14 @@ func (s *testDBSuite4) TestChangeColumn(c *C) {
 	c.Assert(hasNotNull, IsFalse)
 	// for enum
 	s.mustExec(tk, c, "alter table t3 add column en enum('a', 'b', 'c') not null default 'a'")
+	// https://github.com/pingcap/tidb/issues/23488
+	// if there is a prefix index on the varchar column, then we can change it to text
+	s.mustExec(tk, c, "drop table if exists t")
+	s.mustExec(tk, c, "create table t (k varchar(10), v int, INDEX(k(7)));")
```
Comment (tangenta) [inline ddl/db_test.go:2346]:
```suggestion
	s.mustExec(tk, c, "create table t (k char(10), v int, INDEX(k(7)));")
```
The conversion between varchar and non-varchar types has been forbidden in https://github.com/pingcap/tidb/pull/23688...

We can use `char` here instead for the test.

File: ddl/db_test.go [hunk 6]
```diff
@@ -2360,6 +2368,18 @@ func (s *testDBSuite4) TestChangeColumn(c *C) {
 	s.mustExec(tk, c, "alter table t3 add column a bigint")
 	sql = "alter table t3 change aa a bigint"
 	tk.MustGetErrCode(sql, errno.ErrDupFieldName)
+	// https://github.com/pingcap/tidb/issues/23488
+	s.mustExec(tk, c, "drop table if exists t5")
+	s.mustExec(tk, c, "create table t5 (k varchar(10) primary key, v int)")
```
Comment (tangenta) [inline ddl/db_test.go:2373]:
```suggestion
	s.mustExec(tk, c, "create table t5 (k char(10) primary key, v int)")
```

File: ddl/db_test.go [hunk 7]
```diff
@@ -2360,6 +2368,18 @@ func (s *testDBSuite4) TestChangeColumn(c *C) {
...
+	sql = "alter table t5 change column k k tinytext;"
+	tk.MustGetErrCode(sql, mysql.ErrBlobKeyWithoutLength)
+	tk.MustExec("drop table t5")
+
+	s.mustExec(tk, c, "drop table if exists t5")
+	s.mustExec(tk, c, "create table t (k varchar(10), v int, INDEX(k))")
```
Comment (tangenta) [inline ddl/db_test.go:2379]:
```suggestion
	s.mustExec(tk, c, "create table t (k char(10), v int, INDEX(k))")
```

**Comment by tangenta** [comment]
Rest LGTM

File: ddl/db_test.go (hunk 7 above)
Comment (thinkinnight) [reply ddl/db_test.go]: Thanks, now all passed.

File: ddl/db_test.go (hunk 6 above)
Comment (thinkinnight) [reply ddl/db_test.go]: Thanks, now all passed.

File: ddl/db_test.go (hunk 5 above)
Comment (thinkinnight) [reply ddl/db_test.go]: Thanks, now all passed.
