### PR TITLE
expression: `PropagateType` should never let orignal data overflow

### LINKED ISSUE #52672: "Data truncated for column '%s' at row %d"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists PK_PRECISION10063;
CREATE TABLE `PK_PRECISION10063` (
  `COL1` decimal(55,0) NOT NULL,
  `COL2` varchar(20) DEFAULT NULL,
  `COL4` datetime DEFAULT NULL,
  `COL3` bigint(20) DEFAULT NULL,
  `COL5` float DEFAULT NULL,
  PRIMARY KEY (`COL1`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into `PK_PRECISION10063` (`COL1`) values (8320145330174776428);

select col1, tan(col1) from PK_PRECISION10063 where tan(col1) < tan(9021874879467600608071521900001091070693729763119983979);

```

### 2. What did you expect to see? (Required)
```sql
[16:55:05]MySQL root:test> select col1, tan(col1) from PK_PRECISION10063 where tan(col1) < tan(9021874879467600608071521900001091070693729763119983979);
+---------------------+---------------------+
| col1                | tan(col1)           |
+---------------------+---------------------+
| 8320145330174776428 | 0.06084016242886609 |
+---------------------+---------------------+
```
### 3. What did you see instead (Required)
```sql
[16:54:19]TiDB root:test> select col1, tan(col1) from PK_PRECISION10063 where tan(col1) < tan(9021874879467600608071521900001091070693729763119983979);
(1265, "Data truncated for column '%s' at row %d")
```
### 4. What is your TiDB version? (Required)
v8.1.0

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #52672

Problem Summary:

### What changed and how does it work?
When propagate type in https://github.com/pingcap/tidb/blob/b6435d1fb1293b94da1eec310925061d75b93f77/pkg/expression/expression.go#L1192 
make sure that the original data is never be overflow under new type.
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by XuHuaiyu — APPROVED** [review]

File: pkg/expression/expression.go [hunk 1]
```diff
@@ -1214,6 +1215,21 @@ func PropagateType(evalType types.EvalType, args ...Expression) {
 				if newDecimal > mysql.MaxDecimalScale {
 					newDecimal = mysql.MaxDecimalScale
 				}
+				if oldFlen-oldDecimal > newFlen-newDecimal {
+					// the input data should never be overflow under the new type
+					if newDecimal > oldDecimal {
+						// if the target decimal part is large then the original decimal part, we try to extend
```
Comment (guo-shaoge) [inline pkg/expression/expression.go:1221]:
```suggestion
						// if the target decimal part is large than the original decimal part, we try to extend
```

Comment (guo-shaoge) [inline pkg/expression/expression.go:1221]:
```suggestion
						// if the target decimal part is larger than the original decimal part, we try to extend
```

**Review by guo-shaoge — APPROVED** [review]
