### PR TITLE
planner: limit pushdown shouldn't be affected by tidb_opt_limit_push_down_threshold | tidb-test=pr/2601

### LINKED ISSUE #63370: Limit doesn't pushdown to tikv automatically
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
drop table if exists t1;
create table t1(c1 int, c2 int, key(c1));
set @@cte_max_recursion_depth = 10000;
insert into t1 with recursive cte1 as (select 1 cola, 1 colb union all select cola+1 as cola, colb+1 as colb from cte1 limit 5000) select * from cte1;
analyze table t1;
explain select * from t1 order by c1 limit 200;
```

### 2. What did you expect to see? (Required)
limit pushdown to tikv:
```
TiDB root@127.0.0.1:test> explain select * from t1 order by c1 limit 200;
+------------------------------+---------+-----------+------------------------+-------------------------------------+
| id                           | estRows | task      | access object          | operator info                       |
+------------------------------+---------+-----------+------------------------+-------------------------------------+
| Projection_24                | 200.00  | root      |                        | test.t1.c1, test.t1.c2              |
| └─IndexLookUp_23             | 200.00  | root      |                        | limit embedded(offset:0, count:200) |
|   ├─Limit_22(Build)          | 200.00  | cop[tikv] |                        | offset:0, count:200                 |
|   │ └─IndexFullScan_20       | 200.00  | cop[tikv] | table:t1, index:c1(c1) | keep order:true                     |
|   └─TableRowIDScan_21(Probe) | 200.00  | cop[tikv] | table:t1               | keep order:false                    |
+------------------------------+---------+-----------+------------------------+-------------------------------------+
5 rows in set
```
### 3. What did you see instead (Required)
limit didn't pushdown to tikv:
```
TiDB root@127.0.0.1:test> explain select * from t1 order by c1 limit 200;
+--------------------------------+---------+-----------+------------------------+------------------------+
| id                             | estRows | task      | access object          | operator info          |
+--------------------------------+---------+-----------+------------------------+------------------------+
| Limit_14                       | 200.00  | root      |                        | offset:0, count:200    |
| └─Projection_29                | 200.00  | root      |                        | test.t1.c1, test.t1.c2 |
|   └─IndexLookUp_28             | 200.00  | root      |                        |                        |
|     ├─IndexFullScan_26(Build)  | 200.00  | cop[tikv] | table:t1, index:c1(c1) | keep order:true        |
|     └─TableRowIDScan_27(Probe) | 200.00  | cop[tikv] | table:t1               | keep order:false       |
+--------------------------------+---------+-----------+------------------------+------------------------+
5 rows in set
```
### 4. What is your TiDB version? (Required)

```
TiDB root@127.0.0.1:test> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v9.0.0-beta.2.pre-415-g9bcae5eff7        |
| Edition: Community                                        |
| Git Commit Hash: 9bcae5eff736a6a6fb230c7865787f9bd85aa652 |
| Git Branch: master                                        |
| UTC Build Time: 2025-09-04 03:31:53                       |
| GoVersion: go1.24.5                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: unistore                                           |
| Kernel Type: Classic                                      |
+-----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #63370

Problem Summary: 
Limit pushdown shouldn’t be affected by `tidb_opt_limit_push_down_threshold`, so at first glance this description looks a bit strange.
In practice, limit pushdown should always happen since it has no side effects.
Therefore, `tidb_opt_limit_push_down_threshold` only impacts TopN pushdown, not limit pushdown.
(PS: The variable name is misleading and should probably be renamed to tidb_opt_topn_push_down_threshold.)

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: limit pushdown shouldn't be affected by tidb_opt_limit_push_down_threshold
```

### CODE REVIEW

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/core/exhaust_physical_plans.go [hunk 1]
```diff
@@ -2884,14 +2884,22 @@ func exhaustPhysicalPlans4LogicalProjection(super base.LogicalPlan, prop *proper
 	return ret, true, nil
 }
 
-func pushLimitOrTopNForcibly(p base.LogicalPlan) (meetThreshold bool, preferPushDown bool) {
+func pushLimitOrTopNForcibly(p base.LogicalPlan, pp base.PhysicalPlan) (meetThreshold bool, preferPushDown bool) {
 	switch lp := p.(type) {
```
Comment (qw4990) [inline pkg/planner/core/exhaust_physical_plans.go:2888]: It seems like we don't need `p base.LogicalPlan` since if `p` is `TopN`, then `pp` is definitely `TopN`.
So it seems like we can simplify this code to:
```
func pushLimitOrTopNForcibly(pp base.PhysicalPlan) (meetThreshold bool, preferPushDown bool) {
    switch lp := pp.(type) {
        case *TopN:
        case *Limit:
    }
}
```

Comment (guo-shaoge) [reply pkg/planner/core/exhaust_physical_plans.go:2888]: Still need `lp` to get `Count/Offset` and `PreferLimitToCop`

File: pkg/planner/core/exhaust_physical_plans.go [hunk 2]
```diff
@@ -2884,21 +2884,29 @@ func exhaustPhysicalPlans4LogicalProjection(super base.LogicalPlan, prop *proper
 	return ret, true, nil
 }
 
-func pushLimitOrTopNForcibly(p base.LogicalPlan) (meetThreshold bool, preferPushDown bool) {
```
Comment (guo-shaoge) [inline pkg/planner/core/exhaust_physical_plans.go:2887]: I changed the return value order, because in original code, the return statement is:`return preferPushDown, meetThreshold`, which is different with the function declaration!

**Review by hawkingrei — APPROVED** [review]
