### PR TITLE
executor: fix show global variables return session variables also

### LINKED ISSUE #18517: `show global variables` statement returns session variables also
## Development Task
The `show global variables` statement should only return global variables, but it returns all session variables now, which may confuse the user:
```
mysql> show global Variables like "tidb_mem_quota_topn";
+---------------------+-------------+
| Variable_name       | Value       |
+---------------------+-------------+
| tidb_mem_quota_topn | 34359738368 |
+---------------------+-------------+
1 row in set (0.01 sec)

mysql> show  Variables like "tidb_mem_quota_topn";
+---------------------+-------------+
| Variable_name       | Value       |
+---------------------+-------------+
| tidb_mem_quota_topn | 34359738368 |
+---------------------+-------------+
1 row in set (0.02 sec)

```

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by erwadba**
### What problem does this PR solve?

Issue Number: close #18517

Problem Summary: To fix show global variables statement return session variables.

### What is changed and how it works?

What's Changed:
Rewrite the function fetchShowVariables() to distinguish global var from session var.
How it Works:

### Related changes

n/a

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)
```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-993-g18b4e2b1a-dirty
Edition: Community
Git Commit Hash: 18b4e2b1a106d19db590da4af741e22ed08a5bf1
Git Branch: showvar
UTC Build Time: 2020-08-20 08:16:31
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.04 sec)

mysql>  show global Variables like "tidb_mem_quota_topn";
Empty set (0.15 sec)

mysql> show  Variables like "tidb_mem_quota_topn";
+---------------------+-------------+
| Variable_name       | Value       |
+---------------------+-------------+
| tidb_mem_quota_topn | 34359738368 |
+---------------------+-------------+
1 row in set (0.01 sec)

mysql>

```
Side effects

n/a

### Release note 

- fix show global variables return session variables also

### CODE REVIEW

**Comment by erwadba** [comment]
@fzhedu  PTAL

**Comment by erwadba** [comment]
@ti-srebot /run-all-test

**Comment by erwadba** [comment]
@ti-srebot /run-all-tests

**Comment by erwadba** [comment]
@ti-srebot  /rebuild

**Comment by erwadba** [comment]
@ti-srebot /run-all-tests

**Comment by erwadba** [comment]
@ti-srebot /run-common-test

**Comment by erwadba** [comment]
@ti-srebot   /run-all-tests

**Comment by erwadba** [comment]
@qw4990   PTAL

File: executor/show.go [hunk 1]
```diff
@@ -644,44 +644,28 @@ func (e *ShowExec) fetchShowMasterStatus() error {
...
-			unreachedVars = append(unreachedVars, v.Name)
-			continue
-		}
-		e.appendRow([]interface{}{v.Name, value})
-	}
-	if len(unreachedVars) != 0 {
-		systemVars, err := sessionVars.GlobalVarsAccessor.GetAllSysVars()
-		if err != nil {
-			return errors.Trace(err)
+	if !e.GlobalScope {
```
Comment (zz-jason) [inline executor/show.go:650]: to improve the code readability, how about:

```go
if e.GlobalScope {
	// collect global scope variables
	...
	return nil
}

// collect session scope variables
...
return nil
```

Comment (erwadba) [reply executor/show.go:650]: Handled.

**Comment by erwadba** [comment]
@ti-srebot /run-all-tests

**Comment by erwadba** [comment]
@ti-srebot  /run-unit-test

**Comment by erwadba** [comment]
@zz-jason PTAL

File: executor/show_test.go [hunk 2]
```diff
@@ -1001,3 +1002,28 @@ func (s *testSerialSuite1) TestShowCreateTableWithIntegerDisplayLengthWarnings(c
...
+
+func (s *testSuite5) TestShowVar(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	var showSQL string
+	for _, v := range variable.SysVars {
+		if v.Scope != variable.ScopeNone && v.Scope != variable.ScopeGlobal|variable.ScopeSession {
+			if v.Scope == variable.ScopeGlobal {
+				showSQL = "show variables like '" + v.Name + "'"
+				res := tk.MustQuery(showSQL)
+				c.Check(res.Rows(), HasLen, 0)
```
Comment (SunRunAway) [inline executor/show_test.go:1014]: See that example, https://github.com/pingcap/tidb/issues/18517#issuecomment-657743046
The global-only variable should be shown in `show session variables`

File: executor/show_test.go [hunk 3]
```diff
@@ -1001,3 +1002,28 @@ func (s *testSerialSuite1) TestShowCreateTableWithIntegerDisplayLengthWarnings(c
 		"  `e` bigint DEFAULT NULL\n" +
 		") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"))
 }
+
+func (s *testSuite5) TestShowVar(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	var showSQL string
+	for _, v := range variable.SysVars {
+		if v.Scope != variable.ScopeNone && v.Scope != variable.ScopeGlobal|variable.ScopeSession {
```
Comment (SunRunAway) [inline executor/show_test.go:1010]: Please add cases for variables with `ScopeGlobal | ScopeSession` or `ScopeNone`.

File: executor/show_test.go (hunk 2 above)
Comment (erwadba) [reply executor/show_test.go]: Handled.

File: executor/show_test.go (hunk 3 above)
Comment (erwadba) [reply executor/show_test.go]: Done.

**Comment by erwadba** [comment]
@ti-srebot /run-all-tests

**Comment by erwadba** [comment]
PTAL @SunRunAway

**Comment by erwadba** [comment]
@SunRunAway  PTAL

File: executor/show_test.go [hunk 4]
```diff
@@ -1001,3 +1002,26 @@ func (s *testSerialSuite1) TestShowCreateTableWithIntegerDisplayLengthWarnings(c
 		"  `e` bigint DEFAULT NULL\n" +
 		") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"))
 }
+
+func (s *testSuite5) TestShowVar(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	var showSQL string
+	for _, v := range variable.SysVars {
+		// When ScopeSession only. `show global variables` must return empty.
+		if v.Scope != variable.ScopeNone && v.Scope != variable.ScopeGlobal|variable.ScopeSession && v.Scope == variable.ScopeSession {
```
Comment (SunRunAway) [inline executor/show_test.go:1011]:
```suggestion
		if v.Scope == variable.ScopeSession {
```

**Comment by erwadba** [comment]
@ti-srebot /rebuild

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Comment by erwadba** [comment]
@zz-jason PTAL

File: executor/show.go [hunk 5]
```diff
@@ -647,45 +647,35 @@ func (e *ShowExec) fetchShowMasterStatus() error {
...
-	if len(unreachedVars) != 0 {
-		systemVars, err := sessionVars.GlobalVarsAccessor.GetAllSysVars()
-		if err != nil {
+
+	// Collect session scope variables,
+	// If it is a session only variable, use the default value defined in code,
+	//   otherwise, fetch the value from table `mysql.Global_Variables`.
+	for _, v := range variable.SysVars {
+		value, err = variable.GetSessionSystemVar(sessionVars, v.Name)
+		if err != err {
```
Comment (rebelice) [inline executor/show.go:675]: Should this need to be `err != nil` ?

**Review by rebelice — CHANGES_REQUESTED** [review]
The rest LGTM.

File: executor/show.go (hunk 5 above)
Comment (erwadba) [reply executor/show.go]: Ooh, it's my mistake. Thx.

**Review by rebelice — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by qw4990** [comment]
@erwadba Please pick the issue again.

**Comment by qw4990** [comment]
> /pick-up

Please comment `/pick-up` in this issue(https://github.com/pingcap/tidb/issues/18517).

**Comment by erwadba** [comment]
picked

**Comment by qw4990** [comment]
It's merged. Thanks for your contribution :D @erwadba
