### PR TITLE
executor : fix Revoke role from current_user results error

### LINKED ISSUE #33144: Revoke role from current_user results error.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create role r1;
grant r1 to current_user();
revoke r1 from current_user();
drop role r1;
```

### 2. What did you expect to see? (Required)
```sql
mysql> create role r1;
Query OK, 0 rows affected (0.01 sec)

mysql> grant r1 to current_user();
Query OK, 0 rows affected (0.00 sec)

mysql> revoke r1 from current_user();
Query OK, 0 rows affected (0.00 sec)

mysql> drop role r1;
Query OK, 0 rows affected (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> create role r1;
Query OK, 0 rows affected (0.01 sec)

mysql> grant r1 to current_user();
Query OK, 0 rows affected (0.00 sec)

mysql> revoke r1 from current_user();
ERROR 1396 (HY000): Operation REVOKE ROLE failed for @
mysql> drop role r1;
Query OK, 0 rows affected (0.01 sec)
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v6.0.0-alpha-62-g15ddcd085
Edition: Community
Git Commit Hash: 15ddcd085a8be0f97c1b5ce1e5397369c3061372
Git Branch: master
UTC Build Time: 2022-03-15 15:49:18
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by bob34007**
### What problem does this PR solve?

Issue Number: close #33144

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/simple.go [hunk 1]
```diff
@@ -641,8 +641,22 @@ func (e *SimpleExec) executeReleaseSavepoint(s *ast.ReleaseSavepointStmt) error
 	return nil
 }
 
+func (e *SimpleExec) setCurrentUser(users []*auth.UserIdentity) {
+	sessionVars := e.ctx.GetSessionVars()
+	for i, user := range users {
```
Comment (TonsnakeLin) [inline executor/simple.go:646]: Do you want to find the current user and set it with current session?
Why not break if find it?

File: executor/simpletest/simple_test.go [hunk 2]
```diff
@@ -466,6 +466,21 @@ func inTxn(ctx sessionctx.Context) bool {
 	return (ctx.GetSessionVars().Status & mysql.ServerStatusInTrans) > 0
 }
 
+func TestIssue33144(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	//Create role
+	tk.MustExec("create role 'r1' ;")
```
Comment (TonsnakeLin) [inline executor/simpletest/simple_test.go:473]: remove ";"

Comment (bob34007) [reply executor/simpletest/simple_test.go:474]: done

File: executor/simple.go (hunk 1 above)
Comment (bob34007) [reply executor/simple.go:649]: In order to prevent an error when calling current_user multiple times, such as "revoke 'r1' from current_user(),current_user() ;" . Test cases for this scenario have been added.

**Comment by TonsnakeLin** [comment]
LGTM.

**Comment by bob34007** [comment]
@jackysp @tiancaiamao @hawkingrei

**Review by jackysp — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]
