### PR TITLE
server: return a default flen when unspecified

### LINKED ISSUE #34901: Nested cast() clause outputs zero length
### 1. Minimal reproduce step (Required)

First open a mysql client with option `--column-type-info`, such as `mysql --comments --column-type-info --host 127.0.0.1 --port 3306 -u root -p`.

Then by executing a statement with nested `CAST()`, such as `select cast(cast(1 as binary) as binary);`, it can be found that the length field is wrong.

### 2. What did you expect to see? (Required)

```mysql
mysql> select cast(cast(1 as binary) as binary);
Field   1:  `cast(cast(1 as binary) as binary)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  binary (63)
Length:     2
Max_length: 1
Decimals:   31
Flags:      BINARY


+----------------------------------------------------------------------+
| cast(cast(1 as binary) as binary)                                    |
+----------------------------------------------------------------------+
| 0x31                                                                 |
+----------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```mysql
mysql> select cast(cast(1 as binary) as binary);
Field   1:  `cast(cast(1 as binary) as binary)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  binary (63)
Length:     0
Max_length: 1
Decimals:   31
Flags:      NOT_NULL BINARY


+----------------------------------------------------------------------+
| cast(cast(1 as binary) as binary)                                    |
+----------------------------------------------------------------------+
| 0x31                                                                 |
+----------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```mysql
| Release Version: v6.1.0-alpha-490-g9d0d45981
Edition: Community
Git Commit Hash: 9d0d459816705e60205d074f3183c8773086e2b0
Git Branch: master
UTC Build Time: 2022-05-23 14:59:53
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### LINKED ISSUE #60503: incompatible with mysql in column-type-info
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table testfield (f0 int,f1 double,primary key (f0));
insert into testfield values (1,1.1);
insert into testfield values (2,2.2);

TiDB
[tidb@k8s-master tmp]$ mysql  --column-type-info -u root  -P 4000   -h [127.0.0.1](http://127.0.0.1/)  -A -p123123
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 585115960
Server version: 8.0.11-TiDB-v7.1.8-5.1 TiDB Server (Apache License 2.0) Enterprise Edition, MySQL 8.0 compatible

Copyright (c) 2000, 2025, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use test
Database changedmysql> select cast(f1 as char),f1 from testfield;
Field   1:  `cast(f1 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
**Length:     0**
Max_length: 4
Decimals:   31
Flags:      

Field   2:  `f1`
Catalog:    `def`
Database:   `test`
Table:      `testfield`
Org_table:  `testfield`
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     12
Max_length: 4
Decimals:   2
Flags:      NUM 

MySQL：
[tidb@k8s-master tmp]$ mysql  --column-type-info -u root     -h [127.0.0.1](http://127.0.0.1/)  -A -p123123
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 26
Server version: 8.4.4 MySQL Community Server - GPL

Copyright (c) 2000, 2025, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use test;
Database changed
mysql> select cast(f1 as char),f1 from testfield;
Field   1:  `cast(f1 as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
**Length:     48**
Max_length: 4
Decimals:   31
Flags:      

Field   2:  `f1`
Catalog:    `def`
Database:   `test`
Table:      `testfield`
Org_table:  `testfield`
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     12
Max_length: 4
Decimals:   2
Flags:      NUM 

+------------------+------+
| cast(f1 as char) | f1   |
+------------------+------+
| 1.10             | 1.10 |
| 2.20             | 2.20 |
+------------------+------+
2 rows in set (0.00 sec)

mysql>

### 2. What did you expect to see? (Required)
Compatible with MySQL

### 3. What did you see instead (Required)
incompatible with MySQL

### 4. What is your TiDB version? (Required)
v8.5.1

+------------------------+
| version()              |
+------------------------+
| 8.0.11-TiDB-v7.1.8-5.1 |
+------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #60503 , close #34901

Problem Summary:  MySQL will always output a usable column-type-info length in the returned packet, so do we. While we cannot output the same flen as mysql, we can return a non-zero length, at least.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix that tidb will return zero in the column type info of mysql protocol when flen unspecified
```

### CODE REVIEW

**Review by bb7133 — APPROVED** [review]
LGTM

File: pkg/server/driver_tidb_test.go [hunk 1]
```diff
@@ -95,4 +95,47 @@ func TestConvertColumnInfo(t *testing.T) {
...
+				FieldType: ftb.Build(),
+				Comment:   "column a is the first column in table dual",
+			},
+			ColumnAsName: ast.NewCIStr("a"),
+			TableAsName:  ast.NewCIStr("dual"),
+			DBName:       ast.NewCIStr("test"),
+		}
+		colInfo = column.ConvertColumnInfo(&resultField)
+		expectedLen, _ := mysql.GetDefaultFieldLengthAndDecimal(tp)
+		require.NotEqual(t, colInfo.ColumnLength, uint32(expectedLen))
```
Comment (lance6716) [inline pkg/server/driver_tidb_test.go:139]: the PR description says "we can return a non-zero length, at least." so here we can also check `require.NotZero`

BTW why the check is `NotEqual`? I think it should be equal to default field length

Comment (xhebox) [reply pkg/server/driver_tidb_test.go:139]: Nice! I'll fix this.

Comment (xhebox) [reply pkg/server/driver_tidb_test.go:139]: I've modified the code a bit. I did found a bug. Thanks, PTAL.

**Review by lance6716 — APPROVED** [review]
