### PR TITLE
lightning: fix an incorrect metric

### LINKED ISSUE #51947: incorrect rate in grafana
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

image

### 2. What did you expect to see? (Required)
The rate shouldn't be so large.
### 3. What did you see instead (Required)
25.6GiB/s
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #51947

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/external/reader.go [hunk 1]
```diff
@@ -63,6 +63,8 @@ func readAllData(
 		task.End(zap.ErrorLevel, err)
 	}()
 
+	output.size = 0
```
Comment (lance6716) [inline br/pkg/lightning/backend/external/reader.go:66]: better to move to ⬇️
https://github.com/pingcap/tidb/blob/bd17acde8cc3684a349d208ff8f4ee2ac6fef1ba/br/pkg/lightning/backend/external/engine.go#L326-L329

resetting these fields in one place

**Review by ywqzzy — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
