### PR TITLE
plan: use the literal value as column name in SELECT when it is NULL of STRING

### LINKED ISSUE #3686: The field of `select 'a' from t1;` is wrong
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
create table t1(a int);
insert into t1 value(1);
select 'a' from t1;
```

2. What did you expect to see?
```
+---+
| a |
+---+
| a |
+---+
```

3. What did you see instead?
```
+------+
| 'a'  |
+------+
| a    |
+------+
```

4. What version of TiDB are you using (`tidb-server -V`)?

### LINKED ISSUE #4053: select null
MySQL:

```
mysql> select null;
+------+
| NULL |
+------+
| NULL |
+------+
1 row in set (0.00 sec)
```

TiDB:

```
mysql> select null;
+------+
| null |
+------+
| NULL |
+------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by breeswish**
Fix #3686 
Fix #4053

According to MySQL source code:

- When sending field meta data, the field name comes from `columns_list`: https://github.com/mysql/mysql-server/blob/5.7/sql/sql_executor.cc#L104 . https://github.com/mysql/mysql-server/blob/5.7/sql/sql_executor.cc#L145
- `columns_list` is generated in parser token `select_item`: https://github.com/mysql/mysql-server/blob/5.7/sql/sql_yacc.yy#L9204
- In `PTI_expr_with_alias::itemize`, after `expr->itemize`:
  - if `expr` does not have a name, [expression text is used as the name](https://github.com/mysql/mysql-server/blob/5.7/sql/parse_tree_items.cc#L209)
  - [finally expr name will be used as item name](https://github.com/mysql/mysql-server/blob/5.7/sql/parse_tree_items.cc#L212)

When executing `select 'a'`, `expr` is `PTI_text_literal_text_string`, which `expr->itemize` [copies its content as the name](https://github.com/mysql/mysql-server/blob/5.7/sql/item.h#L3642) so that the column name becomes `a`.

For other kind of `expr`:

- [Item_null -> NULL](https://github.com/mysql/mysql-server/blob/5.7/sql/item.h#L3057)
- [Item_int, Item_uint, Item_decimal, Item_float -> the str when constructing](https://github.com/mysql/mysql-server/blob/5.7/sql/item.cc#L3276)

### CODE REVIEW

**Comment by breeswish** [comment]
@zimulala @hanfei1991 PTAL, thanks

**Comment by breeswish** [comment]
@zz-jason @zimulala @hanfei1991 @XuHuaiyu  PTAL, thanks~

File: plan/logical_plan_builder.go [hunk 1]
```diff
@@ -442,8 +442,21 @@ func (b *planBuilder) buildProjection(p LogicalPlan, fields []*ast.SelectField,
...
-					colName = model.NewCIStr(innerExpr.Text())
+				if valueExpr, ok := innerExpr.(*ast.ValueExpr); ok {
+					switch valueExpr.Kind() {
+					case types.KindString:
+						// See #3686
+						colName = model.NewCIStr(valueExpr.GetString())
+					case types.KindNull:
+						// See #3686
+						colName = model.NewCIStr("NULL")
+					default:
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: any test for this branch?

File: executor/executor_test.go [hunk 2]
```diff
@@ -284,6 +284,84 @@ func (s *testSuite) TestSelectBackslashN(c *C) {
 	c.Check(fields[0].Column.Name.O, Equals, `\N`)
 }
 
+// Issue #3686
```
Comment (zz-jason) [inline executor/executor_test.go]: 1. better to remove this comment, since issue 3686 describes only string literal
2. add test for `'\\n'`

File: plan/logical_plan_builder.go (hunk 1 above)
Comment (breeswish) [inline plan/logical_plan_builder.go]: For KindNull: executor_test.go @ Line 288
For KindDefault: this is the original behavior. I think new tests are not needed.

**Comment by breeswish** [comment]
Update:

When copying string literal content as the column name, [some kind of leading characters are trimmed](https://github.com/mysql/mysql-server/blob/5.7/sql/item.cc#L1143). New commits reflects this behavior.

**Comment by breeswish** [comment]
@zz-jason @zimulala @hanfei1991 @XuHuaiyu PTAL again, thanks!

**Comment by XuHuaiyu** [comment]
well done, LGTM

File: plan/logical_plan_builder.go [hunk 3]
```diff
@@ -442,17 +485,25 @@ func (b *planBuilder) buildProjection(p LogicalPlan, fields []*ast.SelectField,
...
 			} else {
 				innerExpr := getInnerFromParentheses(field.Expr)
-				if _, ok := innerExpr.(*ast.ValueExpr); ok && innerExpr.Text() != "" {
-					colName = model.NewCIStr(innerExpr.Text())
-				} else {
-					//Change column name \N to NULL, just when original sql contains \N column
-					fieldText := field.Text()
-					if fieldText == "\\N" {
-						fieldText = "NULL"
+				if valueExpr, ok := innerExpr.(*ast.ValueExpr); ok {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: the logic of setting `colName` and `tblName` is complex enough to be extracted to an individual function

File: plan/logical_plan_builder.go [hunk 4]
```diff
@@ -409,6 +411,47 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
+	unicode.Me,
+	// _MY_NMR
+	unicode.Nd,
+	unicode.Nl,
+	unicode.No,
+}
+
+func isNotGraph(r rune) bool {
+	return !unicode.IsOneOf(graphRange, r)
+}
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: move function `isNotGraph` and variable `graphRange` to package `mysql`

**Comment by breeswish** [comment]
@XuHuaiyu @zz-jason Done. PTAL.

File: plan/logical_plan_builder.go [hunk 5]
```diff
@@ -411,45 +411,50 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
-	unicode.Lo,
-	unicode.Nl,
-	unicode.Mn,
-	unicode.Mc,
-	unicode.Me,
-	// _MY_NMR
-	unicode.Nd,
-	unicode.Nl,
-	unicode.No,
+func buildFieldNameForColumns(field *ast.SelectField, c *expression.Column) (colName model.CIStr, tblName model.CIStr) {
```
Comment (XuHuaiyu) [inline plan/logical_plan_builder.go]: add comments for the two new functions.

File: plan/logical_plan_builder.go [hunk 6]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
+		tblName = c.TblName
+	}
+	return
+}
+
+// buildProjectionFieldNameForExpressions builds the field name when field expression is a normal expression.
+func (b *planBuilder) buildProjectionFieldNameForExpressions(field *ast.SelectField) (colName model.CIStr) {
+	if agg, ok := field.Expr.(*ast.AggregateFuncExpr); ok && agg.F == ast.AggFuncFirstRow {
+		// When the query is select t.a from t group by a; The Column Name should be a but not t.a;
+		colName = agg.Args[0].(*ast.ColumnNameExpr).Name.Name
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: return colName here `return agg.Args[0].(*ast.ColumnNameExpr).Name.Name` and remove the `else` statement next line

File: plan/logical_plan_builder.go [hunk 7]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
+	} else {
+		// Other kind of (normal) expressions.
+		innerExpr := getInnerFromParentheses(field.Expr)
+
+		// Expression is a value literal.
+		if valueExpr, ok := innerExpr.(*ast.ValueExpr); ok {
+			switch valueExpr.Kind() {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]:
```go
if valueExpr, ok := innerExpr.(*ast.ValueExpr); ok {
    switch valueExpr.Kind() {
    case types.KindString:
        return ...
    case types.KindNull:
        return ...
    }
    if innerExpr.Text() != "" {
        return ...
    }
    return ...
}
return ...
```

File: plan/logical_plan_builder.go [hunk 8]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
 	return selection
 }
 
+// buildProjectionFieldNameForColumns builds the field name and the table name when field expression is a column reference.
+func (b *planBuilder) buildProjectionFieldNameForColumns(field *ast.SelectField, c *expression.Column) (colName model.CIStr, tblName model.CIStr) {
+	if astCol, ok := getInnerFromParentheses(field.Expr).(*ast.ColumnNameExpr); ok {
+		colName = astCol.Name.Name
+		tblName = astCol.Name.Table
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: return here `return astCol.Name.Name, astCol.Name.Table` and remove the `else` statement next line

File: plan/logical_plan_builder.go [hunk 9]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
+	} else {
+		colName = c.ColName
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: `return c.ColName, c.TblName`

File: plan/logical_plan_builder.go [hunk 10]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
+		} else {
+			// Remove special comment code for field part, see issue #3739 for detail.
+			colName = model.NewCIStr(parser.SpecFieldPattern.ReplaceAllStringFunc(field.Text(), parser.TrimComment))
+		}
+	}
+	return
+}
+
+// buildProjectionField builds the field object according to SelectField in projection.
+func (b *planBuilder) buildProjectionField(field *ast.SelectField, fieldAsExpr expression.Expression) *expression.Column {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: 1. add the `Projection`'s id and the field position as the first or last parameters of this function
2. s/fieldAsExpr/expr/

```go
func (b *planBuilder) buildProjectionField(id string, position int, field *ast.SelectField, expr expression.Expression) *expression.Column {
```

File: plan/logical_plan_builder.go [hunk 11]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
+		// Field is a column reference.
+		colName, tblName = b.buildProjectionFieldNameForColumns(field, c)
+	} else {
+		// Other: field is an expression.
+		colName = b.buildProjectionFieldNameForExpressions(field)
+	}
+	return &expression.Column{
+		TblName: tblName,
+		ColName: colName,
+		RetType: fieldAsExpr.GetType(),
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: add another two fields:
```go
FromID: id
Position: position
```

File: plan/logical_plan_builder.go [hunk 12]
```diff
@@ -423,45 +493,10 @@ func (b *planBuilder) buildProjection(p LogicalPlan, fields []*ast.SelectField,
...
-			}
-		}
-		col := &expression.Column{
-			FromID:  proj.id,
-			TblName: tblName,
-			ColName: colName,
-			RetType: newExpr.GetType(),
-		}
+
+		col := b.buildProjectionField(field, newExpr)
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: 1. `schema.Append(b.buildProjectionField(proj.id, schema.Len()+1, field, newExpr))`
2. remove line 498, 503, 504

File: plan/logical_plan_builder.go [hunk 13]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
 	return selection
 }
 
+// buildProjectionFieldNameForColumns builds the field name and the table name when field expression is a column reference.
+func (b *planBuilder) buildProjectionFieldNameForColumns(field *ast.SelectField, c *expression.Column) (colName model.CIStr, tblName model.CIStr) {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: s/For/From/

File: plan/logical_plan_builder.go [hunk 14]
```diff
@@ -409,6 +411,74 @@ func (b *planBuilder) buildSelection(p LogicalPlan, where ast.ExprNode, AggMappe
...
+		tblName = astCol.Name.Table
+	} else {
+		colName = c.ColName
+		tblName = c.TblName
+	}
+	return
+}
+
+// buildProjectionFieldNameForExpressions builds the field name when field expression is a normal expression.
+func (b *planBuilder) buildProjectionFieldNameForExpressions(field *ast.SelectField) (colName model.CIStr) {
```
Comment (zz-jason) [inline plan/logical_plan_builder.go]: s/For/From/
