### PR TITLE
dxf/importinto: Reset table mode on task done

### LINKED ISSUE #66879: flaky test TestImportSDK
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

met a different error https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_check2/runs/51882/nodes/110/log/?start=0
```
    sdk_test.go:157: 
        	Error Trace:	tests/realtikvtest/importintotest/sdk_test.go:157
        	Error:      	Received unexpected error:
        	            	[schema:8258]Table t is in mode Import
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/importsdk.(*jobManager).SubmitJob
        	            		pkg/importsdk/job_manager.go:53
        	            	tests/realtikvtest/importintotest/importintotest_test.(*mockGCSSuite).TestImportSDK
        	            		tests/realtikvtest/importintotest/sdk_test.go:156
        	            	reflect.Value.call
        	            		GOROOT/src/reflect/value.go:581
        	            	reflect.Value.Call
        	            		GOROOT/src/reflect/value.go:365
        	            	github.com/stretchr/testify/suite.Run.func1
        	            		external/com_github_stretchr_testify/suite/suite.go:196
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1934
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1693
        	Test:       	TestImportInto/TestImportSDK
```

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #66879, refer #61199

Problem Summary:
Flaky realtikv test `TestImportInto/TestImportSDK`: after `CANCEL IMPORT JOB`, table mode may still be `Import` until async cleanup, so the next `IMPORT INTO` can fail with `[schema:8258] Table t is in mode Import`.

### What changed and how does it work?
- Try to reset table mode back to `Normal` in import scheduler `OnDone` (classic kernel). Cleanup routine remains a fallback.
- Add a unit test to cover cancel path resetting table mode.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Table mode now resets to Normal earlier during import cleanup so tables are returned to normal use immediately after an import completes or is cancelled.

* **Tests**
  * Added tests to verify table mode is reset to Normal after import completion/cancellation to prevent regressions.

* **Chores**
  * Adjusted existing import test expectations to reflect the new timing of mode reset.

### CODE REVIEW

File: pkg/dxf/importinto/scheduler.go [hunk 1]
```diff
@@ -453,6 +456,8 @@ func (sch *importScheduler) OnDone(ctx context.Context, _ storage.TaskHandle, ta
 	if err != nil {
 		return errors.Trace(err)
 	}
+	// Reset table mode earlier than scheduler cleanup. Cleanup routine remains a fallback.
+	sch.switchTableMode2NormalMode(ctx, taskMeta, logger)
```
[the remark this answers is not in the document]
Comment (GMHDBJD) [reply pkg/dxf/importinto/scheduler.go]: Done. OnDone now returns error when resetting table mode fails (except DB/table not exists) so the scheduler will retry instead of succeeding early.

[the remark this answers is not in the document]
Comment (GMHDBJD) [reply pkg/dxf/importinto/scheduler.go:459]: No, we don't return an error; it's compatible with the original behavior.

File: pkg/dxf/importinto/scheduler.go [hunk 2]
```diff
@@ -466,6 +471,35 @@ func (sch *importScheduler) OnDone(ctx context.Context, _ storage.TaskHandle, ta
...
+	if taskMeta == nil || taskMeta.Plan.DBID == 0 || taskMeta.Plan.TableInfo == nil || taskMeta.Plan.TableInfo.ID == 0 {
+		return
+	}
+	err := sch.WithNewTxn(ctx, func(se sessionctx.Context) error {
+		return ddl.AlterTableMode(domain.GetDomain(se).DDLExecutor(), se,
+			model.TableModeNormal, taskMeta.Plan.DBID, taskMeta.Plan.TableInfo.ID)
+	})
+	if err != nil {
+		// If the table is not found, it means the table has been either dropped or truncated.
+		// In such cases, the table mode has already been reset to normal, so we can ignore this error.
```
Comment (D3Hunter) [inline pkg/dxf/importinto/scheduler.go]: since we have switch the mode to import during submit the task, drop/truncate is not allowed, so shouldn't meet such error
so i think it's ok to remove this branch, just print a warning

**Comment by D3Hunter** [comment]
/hold

wait fixing comments

File: pkg/dxf/importinto/scheduler.go (hunk 2 above)
Comment (joechenrh) [reply pkg/dxf/importinto/scheduler.go]: +1

Comment (GMHDBJD) [reply pkg/dxf/importinto/scheduler.go]: Done. Removed the table/db-not-exists special branch here and now always just logs a warning (with err + dbID/tableID).
