### PR TITLE
planner, table: optimize the list column partition pruner for range query

### LINKED ISSUE #22144: optimize the list partition pruner for range query,
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduction step (Required)

For the list partition table:
```sql
set @@session.tidb_enable_table_partition = nightly;
create table t (id int) partition by list  (id) (
	    partition p0 values in (1,2),
	    partition p1 values in (3,4),
	    partition p3 values in (5,null)
	);
```

Currently, range query can't prune partition:

```sql
test> desc select * from t where id < 3;
+------------------------+----------+-----------+-----------------------+--------------------------------+
| id                     | estRows  | task      | access object         | operator info                  |
+------------------------+----------+-----------+-----------------------+--------------------------------+
| PartitionUnion_9       | 9970.00  | root      |                       |                                |
| ├─TableReader_12       | 3323.33  | root      |                       | data:Selection_11              |
| │ └─Selection_11       | 3323.33  | cop[tikv] |                       | lt(test.t.id, 3)               |
| │   └─TableFullScan_10 | 10000.00 | cop[tikv] | table:t, partition:p0 | keep order:false, stats:pseudo |
| ├─TableReader_15       | 3323.33  | root      |                       | data:Selection_14              |
| │ └─Selection_14       | 3323.33  | cop[tikv] |                       | lt(test.t.id, 3)               |
| │   └─TableFullScan_13 | 10000.00 | cop[tikv] | table:t, partition:p1 | keep order:false, stats:pseudo |
| └─TableReader_18       | 3323.33  | root      |                       | data:Selection_17              |
|   └─Selection_17       | 3323.33  | cop[tikv] |                       | lt(test.t.id, 3)               |
|     └─TableFullScan_16 | 10000.00 | cop[tikv] | table:t, partition:p3 | keep order:false, stats:pseudo |
+------------------------+----------+-----------+-----------------------+--------------------------------+
```

But actually,  we can use `id < 3` to do partition prune, since only partition `p0` contain the value that `id<3`. The expected result is:

```sql
test> desc select * from t where id < 3;
+------------------------+----------+-----------+-----------------------+--------------------------------+
| id                     | estRows  | task      | access object         | operator info                  |
+------------------------+----------+-----------+-----------------------+--------------------------------+
| PartitionUnion_9       | 9970.00  | root      |                       |                                |
| ├─TableReader_12       | 3323.33  | root      |                       | data:Selection_11              |
|   └─Selection_11       | 3323.33  | cop[tikv] |                       | lt(test.t.id, 3)               |
|     └─TableFullScan_10 | 10000.00 | cop[tikv] | table:t, partition:p0 | keep order:false, stats:pseudo |
+------------------------+----------+-----------+-----------------------+--------------------------------+
```

### Idea

Use a `BTree` to store the all list partition values, for range query, traversal the range to find the partition in this range.

Samely, `the list column partition` can also use this optimization.

### 4. What is your TiDB version? (Required)

```sql
test> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1948-g9cb4fb38d                    |
| Edition: Community                                                |
| Git Commit Hash: 9cb4fb38d844204b7acba35f1784405c86476dbc         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-04 03:34:31                               |
| GoVersion: go1.15.6                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #22144 

Problem Summary:

### What is changed and how it works?

What's Changed:
optimize the list column partition pruner for range query
How it Works:
Use btree to locate the partitions for range query.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

File: planner/core/rule_partition_processor.go [hunk 1]
```diff
@@ -444,7 +444,18 @@ func (l *listPartitionPruner) findUsedListPartitions(conds []expression.Expressi
 			}
 			used[partitionIdx] = struct{}{}
 		} else {
-			return l.fullRange, nil
+			lvalue, _, err := pruneExpr.EvalInt(l.ctx, chunk.MutRowFromDatums(r.LowVal).ToRow())
```
Comment (crazycs520) [inline planner/core/rule_partition_processor.go:447]:
```suggestion
			if len(r.HighVal) != len(exprCols) {
				// For the list partition, if the first argument is null,
				// then the list partition expression should also be null.
				return l.fullRange, nil
			}
			lvalue, _, err := pruneExpr.EvalInt(l.ctx, chunk.MutRowFromDatums(r.LowVal).ToRow())
```

File: table/tables/partition.go [hunk 2]
```diff
@@ -714,6 +748,40 @@ func (lp *ForListPruning) locateListColumnsPartitionByRow(ctx sessionctx.Context
 	return location[0].PartIdx, nil
 }
 
+func (lp *ForListPruning) buildSortedListPartition(ctx sessionctx.Context, tblInfo *model.TableInfo,
```
Comment (crazycs520) [inline table/tables/partition.go:751]: How about put build `btree` logic into `buildListPartitionValueMap` and rename it. there are a lot of duplicate code here.

File: planner/core/rule_partition_processor.go [hunk 3]
```diff
@@ -444,7 +464,33 @@ func (l *listPartitionPruner) findUsedListPartitions(conds []expression.Expressi
 			}
 			used[partitionIdx] = struct{}{}
 		} else {
-			return l.fullRange, nil
+			if len(r.HighVal) != len(exprCols) || r.IsFullRange() {
+				return l.fullRange, nil
+			}
+			if r.LowVal[0].Kind() == types.KindMinNotNull {
+				r.LowVal[0] = types.GetMinValue(exprCols[0].GetType())
```
Comment (crazycs520) [inline planner/core/rule_partition_processor.go:471]:
```suggestion
				r.LowVal[0] = types.GetMinValue(pruneExpr.GetType())
```

Should use the expression `RetType` instead of the column type.

File: planner/core/rule_partition_processor.go [hunk 4]
```diff
@@ -444,7 +464,33 @@ func (l *listPartitionPruner) findUsedListPartitions(conds []expression.Expressi
...
+			}
+			if r.HighVal[0].Kind() == types.KindMaxValue {
+				r.HighVal[0] = types.GetMaxValue(exprCols[0].GetType())
```
Comment (crazycs520) [inline planner/core/rule_partition_processor.go:474]: ditto.

File: planner/core/rule_partition_processor.go [hunk 5]
```diff
@@ -444,7 +464,33 @@ func (l *listPartitionPruner) findUsedListPartitions(conds []expression.Expressi
...
+			rvalue, isRNull, err := pruneExpr.EvalInt(l.ctx, chunk.MutRowFromDatums(r.HighVal).ToRow())
+			if err != nil {
+				return nil, err
+			}
+			if r.LowExclude {
+				lvalue++
+			}
+			if !r.HighExclude {
+				rvalue++
+			}
```
Comment (crazycs520) [inline planner/core/rule_partition_processor.go:489]: How about move those logic into `l.listPrune.LocateRange`?

**Comment by crazycs520** [comment]
@tiancaiamao @lysu @XuHuaiyu PTAL

File: table/tables/partition.go [hunk 6]
```diff
@@ -714,9 +772,26 @@ func (lp *ForListPruning) locateListColumnsPartitionByRow(ctx sessionctx.Context
 	return location[0].PartIdx, nil
 }
 
-// buildListPartitionValueMap builds list columns partition value map for the specified column.
+// LocateRange locates partition range by the column range
+func (lp *ForListPruning) LocateRange(lowVal int64, isLowNull bool, highVal int64, isHighNull bool) []int {
```
Comment (crazycs520) [inline table/tables/partition.go:776]: I am a little worried about correctness, so I prefer adding a unit test for this function.

I already add a unit test in my local:

1. change the methos interface to:
```go
// LocateRange locates partition range by the column range
func (lp *ForListPruning) LocateRange(ctx sessionctx.Context, r *ranger.Range) ([]int, error) {
	if r.LowVal[0].Kind() == types.KindMinNotNull {
		r.LowVal[0] = types.GetMinValue(lp.PruneExpr.GetType())
	}
	if r.HighVal[0].Kind() == types.KindMaxValue {
		r.HighVal[0] = types.GetMaxValue(lp.PruneExpr.GetType())
	}
	lowVal, isLowNull, err := lp.PruneExpr.EvalInt(ctx, chunk.MutRowFromDatums(r.LowVal).ToRow())
	if err != nil {
		return nil, err
	}
	highVal, isHighNull, err := lp.PruneExpr.EvalInt(ctx, chunk.MutRowFromDatums(r.HighVal).ToRow())
	if err != nil {
		return nil, err
	}
	if r.LowExclude {
		lowVal++
	}
	if !r.HighExclude {
		highVal++
	}
	partitionIdxes := make([]int, 0, lp.sorted.Len())
	if isLowNull {
		partitionIdxes = append(partitionIdxes, lp.nullPartitionIdx)
	}
	if isHighNull {
		partitionIdxes = append(partitionIdxes, lp.nullPartitionIdx)
	}
	lp.sorted.AscendRange(newBtreeSearchItem(lowVal), newBtreeSearchItem(highVal), func(item btree.Item) bool {
		partitionIdxes = append(partitionIdxes, item.(*btreeItem).partitionIdx)
		return true
	})
	return partitionIdxes, nil
}
```

2. put below unit test in `table/tables/partition_test.go`:

```go
// partitionTable is for those tables which implement partition.
type partitionTable interface {
	PartitionExpr() (*tables.PartitionExpr, error)
}

func (ts *testSuite) TestListPartitionRangePrune(c *C) {
	tk := testkit.NewTestKitWithInit(c, ts.store)
	tk.MustExec("use test")
	tk.MustExec("drop tables if exists t1")
	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
	tk.MustExec(`create table t1 (id int, a int, b int) partition by list ( a ) (partition p0 values in (1,2,3,4,5), partition p1 values in (6,7,8,9,10), partition p2 values in (null));`)
	tb, err := ts.dom.InfoSchema().TableByName(model.NewCIStr("test"), model.NewCIStr("t1"))
	c.Assert(err, IsNil)
	partExpr, err := tb.(partitionTable).PartitionExpr()
	c.Assert(err, IsNil)
	cases := []struct {
		r      ranger.Range
		result []int
	}{
		{
			r:      ranger.Range{LowVal: types.MakeDatums(0), HighVal: types.MakeDatums(1)},
			result: []int{0},
		},
		{
			r:      ranger.Range{LowVal: types.MakeDatums(0), HighVal: types.MakeDatums(6)},
			result: []int{0, 0, 0, 0, 0, 1}, // need deduplicate the result, the expect should be {0,1}
		},
		{
			r:      ranger.Range{LowVal: []types.Datum{types.MinNotNullDatum()}, HighVal: []types.Datum{types.MaxValueDatum()}},
			result: []int{0, 0, 0, 0, 0, 1, 1, 1, 1, 1}, // need deduplicate the result, the expect should be {0,1}
		},
		{
			r:      ranger.Range{LowVal: types.MakeDatums(nil), HighVal: []types.Datum{types.MaxValueDatum()}},
			result: []int{2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1}, // need deduplicate the result, the expect should be {0,1,2}
		},
		{
			r:      ranger.Range{LowVal: types.MakeDatums(nil), HighVal: []types.Datum{types.MaxValueDatum()}},
			result: []int{2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1}, // need deduplicate the result, the expect should be {0,1,2}
		},
		{
			r:      ranger.Range{LowVal: types.MakeDatums(nil), HighVal: types.MakeDatums(nil)},
			result: []int{2, 2}, // need deduplicate the result, the expect should be {2}
		},
	}

	for _, ca := range cases {
		ret, err := partExpr.ForListPruning.LocateRange(tk.Se, &ca.r)
		c.Assert(err, IsNil)
		c.Assert(ret, DeepEquals, ca.result)
	}
}
```

File: planner/core/rule_partition_processor.go (hunk 3 above)
Comment (crazycs520) [reply planner/core/rule_partition_processor.go:471]: Oh no, ignore this, my fault.

File: planner/core/rule_partition_processor.go (hunk 5 above)
Comment (TszKitLo40) [reply planner/core/rule_partition_processor.go:489]: It seems that there is no `ctx` in `l.listPrune`.

File: table/tables/partition.go (hunk 6 above)
Comment (TszKitLo40) [reply table/tables/partition.go]: Done

File: table/tables/partition_test.go [hunk 7]
```diff
@@ -530,3 +536,51 @@ func (ts *testSuite) TestIssue21574(c *C) {
...
+		r      ranger.Range
+		result []int
+	}{
+		{
+			r:      ranger.Range{LowVal: types.MakeDatums(0), HighVal: types.MakeDatums(1)},
+			result: []int{0},
+		},
+		{
+			r:      ranger.Range{LowVal: types.MakeDatums(0), HighVal: types.MakeDatums(6)},
+			result: []int{0, 0, 0, 0, 0, 1}, // need deduplicate the result, the expect should be {0,1}
```
Comment (crazycs520) [inline table/tables/partition_test.go:560]: As the comment said, the expected result should be `{0,1}`

Comment (TszKitLo40) [reply table/tables/partition_test.go:560]: Do you mean this test should fail? And the correct result should be '{0,1}' and Maybe something wrong now ?

File: table/tables/partition.go [hunk 8]
```diff
@@ -714,9 +772,46 @@ func (lp *ForListPruning) locateListColumnsPartitionByRow(ctx sessionctx.Context
...
+		r.LowVal[0] = types.GetMinValue(lp.PruneExpr.GetType())
+	}
+	if r.HighVal[0].Kind() == types.KindMaxValue {
+		r.HighVal[0] = types.GetMaxValue(lp.PruneExpr.GetType())
+	}
+	lowVal, isLowNull, err := lp.PruneExpr.EvalInt(ctx, chunk.MutRowFromDatums(r.LowVal).ToRow())
+	if err != nil {
+		return nil, err
+	}
+	highVal, isHighNull, err := lp.PruneExpr.EvalInt(ctx, chunk.MutRowFromDatums(r.HighVal).ToRow())
```
Comment (crazycs520) [inline table/tables/partition.go:787]: Need to constrain function type, just same like range partition.

Because,  `lowValue < col < highValue` , doean't means  `fn(lowValue) < fn(col) < fn(highValue)`.

Such as the partition expression is `0 - a`; and the query condition is `1 < a < 3`, 
`fn(1) < fn(a) < fn(3)` => `-1 < fn(a) < -3` is not right.

Comment (crazycs520) [reply table/tables/partition.go:787]: I think this change will be a much big, beter to pull another PR to do range prune optimization for list partition, this PR can only for list columns partition.

Comment (TszKitLo40) [reply table/tables/partition.go:787]: It seems that it is easier that this PR for list partition, and pull another PR to do range prune optimization for list partition. Because I can reset to the commit for list partition.

Comment (TszKitLo40) [reply table/tables/partition.go]: I have remove the code which is related to list partition, PTAL

File: planner/core/testdata/partition_pruner_in.json [hunk 9]
```diff
@@ -254,6 +254,7 @@
         "SQL": "select * from t1 where id = 1 and a=1",
         "Pruner": "t1: p0"
       },
+      // For ranges
```
Comment (crazycs520) [inline planner/core/testdata/partition_pruner_in.json:257]: Should move to line 314?

File: planner/core/rule_partition_processor.go [hunk 10]
```diff
@@ -370,7 +370,27 @@ func (l *listPartitionPruner) locateColumnPartitionsByCondition(cond expression.
 				helper.Union(location)
 			}
 		} else {
-			return nil, true, nil
+			if r.LowVal[0].Kind() == types.KindMinNotNull {
+				r.LowVal[0] = types.GetMinValue(colPrune.ExprCol.GetType())
+			}
+			if r.HighVal[0].Kind() == types.KindMaxValue {
+				r.HighVal[0] = types.GetMaxValue(colPrune.ExprCol.GetType())
+			}
```
Comment (crazycs520) [inline planner/core/rule_partition_processor.go:378]: Please put those logical into function `colPrune.LocateRanges`.

Comment (crazycs520) [reply planner/core/rule_partition_processor.go:378]: And the do some refactor for this function:

```go
func (l *listPartitionPruner) locateColumnPartitionsByCondition(cond expression.Expression, colPrune *tables.ForListColumnPruning) (tables.ListPartitionLocation, bool, error) {
	ranges, err := l.detachCondAndBuildRange([]expression.Expression{cond}, colPrune.ExprCol)
	if err != nil {
		return nil, false, err
	}

	sc := l.ctx.GetSessionVars().StmtCtx
	helper := tables.NewListPartitionLocationHelper()
	for _, r := range ranges {
		if len(r.LowVal) != 1 || len(r.HighVal) != 1 {
			return nil, true, nil
		}
		var locations []tables.ListPartitionLocation
		if r.IsPointNullable(sc) {
			location, err := colPrune.LocatePartition(sc, r.HighVal[0])
			if err != nil {
				return nil, false, err
			}
			locations = []tables.ListPartitionLocation{location}
		} else {
			locations, err = colPrune.LocateRanges(sc, r)
			if err != nil {
				return nil, false, nil
			}
		}
		for _, location := range locations {
			if len(l.partitionNames) > 0 {
				for _, pg := range location {
					if l.findByName(l.partitionNames, l.pi.Definitions[pg.PartIdx].Name.L) {
						helper.UnionPartitionGroup(pg)
					}
				}
			} else {
				helper.Union(location)
			}
		}
	}
	return helper.GetLocation(), false, nil
}
```

**Review by crazycs520 — COMMENTED** [review]
REST LGTM

**Comment by crazycs520** [comment]
@tiancaiamao @lysu PTAL

File: planner/core/rule_partition_processor.go [hunk 11]
```diff
@@ -392,14 +392,23 @@ func (l *listPartitionPruner) locateColumnPartitionsByCondition(cond expression.
...
-			if len(r.HighVal) != 1 {
-				return nil, true, nil
-			}
 			location, err := colPrune.LocatePartition(sc, r.HighVal[0])
 			if err != nil {
 				return nil, false, err
 			}
+			locations = []tables.ListPartitionLocation{location}
+		} else {
+			locations, err = colPrune.LocateRanges(sc, r)
```
Comment (tiancaiamao) [inline planner/core/rule_partition_processor.go:406]: The PR title says it's for list partition, but here it's for list column partition?

File: table/tables/partition.go [hunk 12]
```diff
@@ -783,6 +816,38 @@ func (lp *ForListColumnPruning) LocatePartition(sc *stmtctx.StatementContext, v
...
 }
 
+// LocateRanges locates partition ranges by the column range
+func (lp *ForListColumnPruning) LocateRanges(sc *stmtctx.StatementContext, r *ranger.Range) ([]ListPartitionLocation, error) {
+	if r.LowVal[0].Kind() == types.KindMinNotNull {
+		r.LowVal[0] = types.GetMinValue(lp.ExprCol.GetType())
+	}
+	if r.HighVal[0].Kind() == types.KindMaxValue {
+		r.HighVal[0] = types.GetMaxValue(lp.ExprCol.GetType())
+	}
```
Comment (tiancaiamao) [inline table/tables/partition.go:826]: Call this function modify the parameter `r` ?
This side effect is not good. How about:

```
if rowVal.Kind() == types.KindMinNotNull {
	lowVal = types.GetMinValue(lp.ExprCol.GetType())
}
if highVal.Kind() == types.KindMaxValue {
	highVal = types.GetMaxValue(lp.ExprCol.GetType())
}
```

File: table/tables/partition.go [hunk 13]
```diff
@@ -783,6 +816,38 @@ func (lp *ForListColumnPruning) LocatePartition(sc *stmtctx.StatementContext, v
...
+
+	if r.LowExclude {
+		lowKey = kv.Key(lowKey).PrefixNext()
+	}
+	if !r.HighExclude {
+		highKey = kv.Key(highKey).PrefixNext()
+	}
+
+	locations := make([]ListPartitionLocation, 0, lp.sorted.Len())
+	lp.sorted.AscendRange(newBtreeListColumnSearchItem(string(lowKey)), newBtreeListColumnSearchItem(string(highKey)), func(item btree.Item) bool {
```
Comment (tiancaiamao) [inline table/tables/partition.go:844]: `string(lowKey)` will cause allocation here, maybe you can give https://github.com/pingcap/tidb/blob/master/util/hack/hack.go#L27 a try?

```
string(hack.String(lowKey))
```

File: planner/core/rule_partition_processor.go (hunk 11 above)
Comment (TszKitLo40) [reply planner/core/rule_partition_processor.go:406]: I have changed the title.

Comment (TszKitLo40) [reply planner/core/rule_partition_processor.go:406]: This column is just for list column partition

File: table/tables/partition.go (hunk 12 above)
Comment (TszKitLo40) [reply table/tables/partition.go]: done

File: table/tables/partition.go (hunk 13 above)
Comment (TszKitLo40) [reply table/tables/partition.go]: done
