### PR TITLE
ddl: determine whether to use merge sort by each index separately

### LINKED ISSUE #52004: Multi-schema adding index should not trigger merge step
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Add multiple indexes for 1TB sysbench table, for example

```sql
alter table sbtest1 
  add index idx_p(pad),
  add index idx_k(k),
  add index idx_c(c);
```

### 2. What did you expect to see? (Required)

TiDB should not run merge sort because the dataset is not large enough.

### 3. What did you see instead (Required)

TiDB run merge sort step.

img_v3_0296_5456d25a-ebc2-42e4-855b-5d3f8e82b21g

It may take more than 100% time to complete.

### 4. What is your TiDB version? (Required)

69c26ae8a

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #52004

Problem Summary:

Before this PR, when TiDB adds multiple indexes with global sort, merge sort step is determined by external file count of ALL indexes. For example, the threshold is 4000, there are 3 indexes with 3000 files respectively, then there are 9000(>4000) files. Merge sort step will be executed. However, merge sort is not necessary in this case, because the records from different indexes are not overlap.

### What changed and how does it work?

- Use file count from each index to determine whether use merge sort.
- Refine a error message and add a test case.
- Use average row size to determine reader count for ingest mode.
- Increase system session pool from 128 to 512, because readers could increase a lot and block session allocation.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/backfilling_scheduler.go [hunk 1]
```diff
@@ -329,18 +331,37 @@ type ingestBackfillScheduler struct {
...
 
+func estimateAvgRowSize(tbl table.PhysicalTable) int {
+	size := 0
+	for _, col := range tbl.Meta().Columns {
+		ft := col.FieldType
+		storeLen := ft.StorageLength()
+		if storeLen != types.VarStorageLen {
+			size += storeLen
+		} else {
+			if types.IsString(ft.GetType()) {
```
Comment (Benjamin2037) [inline pkg/ddl/backfilling_scheduler.go:356]: will the Json and blob be treated as char type？What is the return length of them.

File: pkg/ddl/backfilling_scheduler.go [hunk 2]
```diff
@@ -501,15 +524,21 @@ func (b *ingestBackfillScheduler) createCopReqSenderPool() (*copReqSenderPool, e
...
-func expectedIngestWorkerCnt() (readerCnt, writerCnt int) {
+func expectedIngestWorkerCnt(avgRowSize int) (readerCnt, writerCnt int) {
 	workerCnt := int(variable.GetDDLReorgWorkerCounter())
-	readerCnt = min(workerCnt/2, maxBackfillWorkerSize)
-	readerCnt = max(readerCnt, 1)
-	writerCnt = min(workerCnt/2+2, maxBackfillWorkerSize)
+	readerRatio := []float64{0.5, 1, 2, 4, 8}
+	rowSize := []int{200, 500, 1000, 3000, 5000}
+	for i, s := range rowSize {
+		if avgRowSize <= s {
```
Comment (Benjamin2037) [inline pkg/ddl/backfilling_scheduler.go:536]: how about when avgRowSize > 5000, reader and writer cnt?

File: pkg/ddl/backfilling_scheduler.go [hunk 3]
```diff
@@ -501,15 +524,21 @@ func (b *ingestBackfillScheduler) createCopReqSenderPool() (*copReqSenderPool, e
...
+			readerCnt = int(float64(workerCnt) * readerRatio[i])
+			writerCnt = workerCnt
```
Comment (Benjamin2037) [inline pkg/ddl/backfilling_scheduler.go:538]: also. < 200, the writerCnt need +2 otherwise, I remeber the performance will degrade bigger than 10%

Comment (tangenta) [reply pkg/ddl/backfilling_scheduler.go:538]: I prefer to make it simple and easy to predict.

File: pkg/domain/domain.go [hunk 4]
```diff
@@ -1175,7 +1175,7 @@ func (do *Domain) Init(
 	sysFac := func() (pools.Resource, error) {
 		return sysExecutorFactory(do)
 	}
-	sysCtxPool := pools.NewResourcePool(sysFac, 128, 128, resourceIdleTimeout)
+	sysCtxPool := pools.NewResourcePool(sysFac, 512, 512, resourceIdleTimeout)
```
Comment (Benjamin2037) [inline pkg/domain/domain.go:1178]: What 128 to 512 mean?

File: pkg/ddl/backfilling_scheduler.go (hunk 3 above)
Comment (Benjamin2037) [reply pkg/ddl/backfilling_scheduler.go:528]: OK, let's see the perf testing result.

**Review by Benjamin2037 — APPROVED** [review]
rest LGTM

File: pkg/ddl/backfilling_dist_scheduler.go [hunk 5]
```diff
@@ -466,32 +466,42 @@ func generateMergePlan(
...
+	if allSkip {
 		logger.Info("skip merge sort")
 		return nil, nil
 	}
 
-	// generate merge sort plan.
-	dataFiles := make([]string, 0, 1000)
+	metaArr := make([][]byte, 0, 16)
 	for i, g := range kvMetaGroups {
+		dataFiles := make([]string, 0, 1000)
```
Comment (ywqzzy) [inline pkg/ddl/backfilling_dist_scheduler.go:504]: Why not generate subtasks for each index that really needs merge sort？

Comment (tangenta) [reply pkg/ddl/backfilling_dist_scheduler.go:504]: If we do this, in step 3, we need to scan subtasks meta from both step 2 and step 1.

**Review by wjhuang2016 — APPROVED** [review]
