### PR TITLE
ttl: fix ut failure after using advanced session

### LINKED ISSUE #61175: Daily long-run unit test failed in `TestParallelLockNewTask`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
make ut-long
```

### 2. What did you expect to see? (Required)

Test passed.

### 3. What did you see instead (Required)

Test failed.

```
[2025/05/19 16:57:17.196 +08:00] [INFO] [task_manager_integration_test.go:116] ["lock new task with error"] [error="task is already scheduled"] [errorVerbose="task is already scheduled\ngithub.com/pingcap/tidb/pkg/ttl/ttlworker.init\n\t<autogenerated>:1\nruntime.doInit1\n\t/usr/local/go/src/runtime/proc.go:7350\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:7317\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:254\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1223\ngithub.com/pingcap/tidb/pkg/ttl/ttlworker.(*taskManager).lockScanTask.func1\n\t/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager.go:421\ngithub.com/pingcap/tidb/pkg/ttl/session.(*session).RunInTxn\n\t/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/session/session.go:169\ngithub.com/pingcap/tidb/pkg/ttl/ttlworker.(*taskManager).lockScanTask\n\t/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager.go:408\ngithub.com/pingcap/tidb/pkg/ttl/ttlworker.(*taskManager).LockScanTask\n\t/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager_test.go:47\ngithub.com/pingcap/tidb/pkg/ttl/ttlworker_test.TestParallelLockNewTask.func1\n\t/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager_integration_test.go:108\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1223"]
panic: assert failed

goroutine 99378 [running]:
github.com/pingcap/tidb/pkg/util/intest.doPanic(...)
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/util/intest/assert_common.go:58
github.com/pingcap/tidb/pkg/util/intest.doAssert(...)
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/util/intest/assert_common.go:30
github.com/pingcap/tidb/pkg/util/intest.Assert(...)
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/util/intest/assert.go:25
github.com/pingcap/tidb/pkg/ttl/ttlworker.(*taskManager).lockScanTask.func1()
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager.go:450 +0xfe4
github.com/pingcap/tidb/pkg/ttl/session.(*session).RunInTxn(0xc0260fec60, {0x1096068d0, 0xc02633e6f0}, 0xc0248f83c0, 0x1)
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/session/session.go:169 +0x2f8
github.com/pingcap/tidb/pkg/ttl/ttlworker.(*taskManager).lockScanTask(0xc0248cec80, {0x109630f98, 0xc0260fec60}, 0xc02477b950, {0xc02633e5a0?, 0xc023ca09f0?, 0xc000258f50?})
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager.go:408 +0x31c
github.com/pingcap/tidb/pkg/ttl/ttlworker.(*taskManager).LockScanTask(...)
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager_test.go:47
github.com/pingcap/tidb/pkg/ttl/ttlworker_test.TestParallelLockNewTask.func1()
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager_integration_test.go:108 +0x300
created by github.com/pingcap/tidb/pkg/ttl/ttlworker_test.TestParallelLockNewTask in goroutine 87
	/Users/yangkeao/Projects/github.com/YangKeao/tidb/master/pkg/ttl/ttlworker/task_manager_integration_test.go:100 +0xa3c
^Cmake: *** [ut-long] Interrupt: 2
```

### 4. What is your TiDB version? (Required)

```
2dce92429d784d75c94146638c3ac1e437e859c8
```

Thanks for @purelind to report this issue 👍

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #61175

Problem Summary:

1. Timeout error for session in long tests.
2. Fail in `ResetSctxForTest` because the owner is nil.

Both of them are not likely to occur in production environment. For the second issue, it'll occur only when the `SET @@time_zone = ...` failed.

### What changed and how does it work?

1. Don't call `.Close()` in `withSession`.
4. Extend the timeout of a session for test.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

File: pkg/timer/tablestore/sql_test.go [hunk 1]
```diff
@@ -737,11 +736,10 @@ func TestWithSession(t *testing.T) {
 		sctx.On("ExecuteInternal", matchCtx, "SET @@time_zone=%?", mock.Anything).
 			Return(nil, errors.New("SET tz error")).
 			Once()
-		sctx.On("Close").Once()
 		mockCb1.MethodCalled("cb1", se)
 		return nil
 	}))
-	require.True(t, pool.se.IsInternalClosed())
+	require.True(t, pool.se.IsAvoidReuse())
```
Comment (YangKeao) [inline pkg/timer/tablestore/sql_test.go:742]: This behavior is guarded by a test. I'm not sure why it should close internally inside the `withSession` 🤔 . @lcwangchao PTAL.

**Comment by lance6716** [comment]
Can you explain more details about why `SET @@time_zone = ...` will fail?

**Comment by YangKeao** [comment]
> Can you explain more details about why `SET @@time_zone = ...` will fail?

@lance6716  It is not likely to happen in the real life. It failed because we mock the failure in test 🤦 . In some random tests, some of the sessions used by TTL will randomly return error for any SQLs to test that TiDB TTL feature is strong enough to work in this scenario.

File: pkg/timer/tablestore/sql_test.go (hunk 1 above)
Comment (lcwangchao) [reply pkg/timer/tablestore/sql_test.go:742]: I think `withSession` think `pool.Put` will discard a closed session without using it. But in a test mock pool, it may not. It's better to use `AvoidToResuse` than `Close`

**Review by lcwangchao — APPROVED** [review]
