### PR TITLE
Makefile,tools: make CI great again!

### LINKED ISSUE #30822: Make CI great again!
## Enhancement

The unstable CI has been a hinder to our daily development. Sometimes we have to run it again and again, and again ... to merge a PR.
It takes a very long time to run the CI and if a unstable test fails, all the time are wasted.

There are many bad decisions we made in the past:

- To make it run faster, we use a wrong way to parallel
- Auto re-run to amend for the unstable test cases
- No timeout limitation on a single unit test
- High coupling of the code and running environment
- Multiple teams to maintain CI thus the unclear responsbilities

Let's review it one by one.

We use a wrong way to parallel. Some test cases are not side effect free, for example:

- the enable and disable of the failpoint
- modification of the configuration
- change of the global variable in a single process.
- etc...

If the test cases with side effect run parallelly with others, it could cause some test fail unexpectedly. 
When they're in a single OS process, make them parallel is not a big deal.
Parallel make the CI run a bit faster but when some test fail, it takes us a lot of time to investigate the root cause.

We employ auto re-run using the CI bot to amend for the unstable tests. IMHO, this is another failure.
The auto re-run tend to make us ignore the unstable cases. See https://github.com/pingcap/tidb/issues/25899
As time goes on, there are more and more unstable test cases. And test cases almost fail randomly!
Later, if someone file a PR and run all test pass without retry, maybe he would think: WOW, today I'm so lucky~

Back to the point of parallel, why we want to make the test parallel? we want it to run faster because it's slow.
So why it's slow? because we're adding more and more test cases.
Well, I found many code are poorly writen. Some test cases call `sleep()` at will, and a single test case may run even more than 120s! 
The problem is, there was no timeout limitation on it, so I added one.
However, the timeout makes the CI more unstable https://github.com/pingcap/tidb/issues/26717

Parallel requires more machine resource and with retrying, that can eat up all the machine resources! 
The high load of the CI environment makes the test cases more likely to fail.
The situation comes from bad to worse.

So high coupling of the code and running environment makes the running time of a single test case undecidable.
Timeout limitation on a single unit test doesn't work well.
I can see the test case always finish within 3s in my own computer, but that's not the truth in the CI environment.

========================

### What's the solution?

- [X] Step1: remove all the in-process parallel [#30692](https://github.com/pingcap/tidb/pull/30692)
- [x] Step2: Add back parallel by run a single test case in a isolated OS process [#30828](https://github.com/pingcap/tidb/issues/30828)
    - [x]     polish of the tool ut, exit code, output log etc
    - [x]     fix some failed test cases
    - [ ]     limit the timeout for a single test case
    - [x] #31885
    - [x] #31893

- [ ] Step3: Make a bootstraped store snapshot to avoid `Bootstrap()` in every single test

For step2, we can specify the test case by the name manually:

```
go test -run TextXXX
```

And we can run different test cases parallely, each with its own OS process, so the code is isolated without side effect.

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #30822

Problem Summary:

In https://github.com/pingcap/tidb/pull/30692 the `Parallel()` is removed from the test cases.
But I still wish the tests can run faster.
This is a new way to run the tests parallelly.

```
cd pkg // some package, for example session
go test -c // generate the test binary file pkg.test
./pkg.test -test.run TestXXX // run a single test case
```

The last step choose one test case to run, and if we do it for several test cases at the same time, 
the test cases run parallelly, isolated in different OS process!

I provide a tool for it -- ut

### What is changed and how it works?

Run all unit tests:

```
make ut
or ./toos/bin/ut
or ./tools/bin/ut run
```

List all the packages:

```
make ut X=list
or ./tools/bin/ut list
```

List test cases in a specified package:

```
make ut X='list executor'
or ./tools/bin/ut list executor
```

```
$ make ut X='list tablecodec'
tools/bin/ut list tablecodec;
TestBenchDaily
TestTableCodec
TestTableCodecInvalid
TestRowCodec
TestDecodeColumnValue
TestUnflattenDatums
TestTimeCodec
TestCutRow
TestCutKeyNew
TestCutKey
TestDecodeBadDecical
TestIndexKey
TestRecordKey
TestPrefix
TestDecodeIndexKey
TestCutPrefix
TestRange
TestDecodeAutoIDMeta
TestError
TestUntouchedIndexKValue
```

Run all tests in a package, it's useful when you just change on package and want to verify your changes.

```
make ut X='run planner/core'
or ./tools/bin/ut run session
```

Run a specified test function.

```
make ut X='run session testPessimisticSuite.TestPointGetKeyLock'
or ./tools/bin/ut run session testPessimisticSuite.TestPointGetKeyLock
```

This is useful when the CI tell you a function failed, and you want to verify it -- just that function.

How it works?

If `numactl` is available, I'll bind each process to one CPU.
When running the test function, flag `-test.cpu=1` is set.

I tried a worker-pool model, N workers, and N = number of CPU, but if `-test.cpu` is not set, every Go test process would think they can use the MAXPROCS, and the load is too high.
I also tried N workers and N = numa core, and  for a test case, let the MAXPROCS to be CPUs per numa core. This setting can't full utilize the CPU resource.
The observation is that the logic for one test case is sequential, it just need one CPU.

Since we run parallel now, the CI runs faster than before, on my desktop computer (AMD Ryzen 7 PRO 4750G, 8 core 16 CPU):

```
$ time make ut
223.825 secs

$ time make gotest
362.825 secs
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
In this commit, I don't use it to replace the default one.
Because there are more things to do, it's better to do it step by step.

- polish of the tool ut, exit code, output log etc.
- limit the timeout for a single test case
- handling the coverage.txt
- integration with the CI script

File: .gitignore [hunk 1]
```diff
@@ -6,6 +6,7 @@ coverage.out
 *.iml
 *.swp
 *.log
+*.test
```
Comment (bb7133) [inline .gitignore:9]: It's better to keep '*.test' out of ignore list, we have some test files in `cmd/explaintest`.

File: tools/check/ut.go [hunk 2]
```diff
@@ -0,0 +1,529 @@
...
+		case "run":
+			cmdRun(os.Args[2:]...)
+		default:
+			usage()
+		}
+	}
+}
+
+func listTestCases(pkg string, tasks []task) ([]task, error) {
+	xxx, err := listNewTestCases(pkg)
```
Comment (bb7133) [inline tools/check/ut.go:292]: Please rename the `xxx`

File: tools/check/ut.go [hunk 3]
```diff
@@ -0,0 +1,529 @@
...
+		if strings.HasPrefix(pkg, ignore) {
+			return true
+		}
+	}
+	return false
+}
+
+func buildTestBinary(pkg string) error {
+	// go test -c
+	cmd := exec.Command("go", "test", "-c", "-vet", "off")
```
Comment (bb7133) [inline tools/check/ut.go:412]: We now have a plan to introduce `gotestsum`: https://github.com/pingcap/tidb/pull/29848

It should be considered together @tangenta

File: tools/check/ut.go [hunk 4]
```diff
@@ -0,0 +1,529 @@
...
+
+const modulePath = "github.com/pingcap/tidb"
+
+type task struct {
+	pkg  string
+	test string
+	old  bool
+}
+
+var P = runtime.NumCPU()
```
Comment (hawkingrei) [inline tools/check/ut.go:68]: If your program runs in the docker, ```NumCPU``` will get the CPU num of your hosts. You should use ```"go.uber.org/automaxprocs/maxprocs"``` to get the real CPU num in the docker.

File: .gitignore (hunk 1 above)
Comment (tiancaiamao) [reply .gitignore:9]: I have checked, this will not ignore the files in directory `cmd/explaintest`, just the file whose name ended with `.test`

File: tools/check/ut.go (hunk 3 above)
Comment (tiancaiamao) [reply tools/check/ut.go:412]: The `ut` tool introduced in this PR will not replace the old CI pipeline immediately, there many works to do before make it ready, including the coverage.

File: tools/check/ut.go (hunk 4 above)
Comment (tiancaiamao) [reply tools/check/ut.go]: Done

File: tools/check/ut.go (hunk 2 above)
Comment (tiancaiamao) [reply tools/check/ut.go]: Done

**Comment by tiancaiamao** [comment]
PTAL @bb7133 @hawkingrei

**Comment by tiancaiamao** [comment]
PTAL @bb7133 @hawkingrei

**Review by hawkingrei — APPROVED** [review]
LGTM

File: .gitignore (hunk 1 above)
Comment (bb7133) [reply .gitignore:9]: But we do have `.test` files: https://github.com/pingcap/tidb/tree/master/cmd/explaintest/t

File: tools/check/ut.go (hunk 3 above)
Comment (bb7133) [reply tools/check/ut.go:417]: Got it.

File: tools/check/ut.go [hunk 5]
```diff
@@ -0,0 +1,534 @@
...
+
+// run test cases of a single package
+ut run $package $test
+
+// build all test package
+ut build
+
+// build a test package
+ut build xxx`
+	fmt.Println(msg)
```
Comment (bb7133) [inline tools/check/ut.go:60]: How about printing them to `stderr`?

File: .gitignore (hunk 1 above)
Comment (tiancaiamao) [reply .gitignore:9]: Oh, I see...

Comment (tiancaiamao) [reply .gitignore:9]: Done ... renamed to *.test.bin

File: tools/check/ut.go (hunk 5 above)
Comment (tiancaiamao) [reply tools/check/ut.go:60]: It's not handled in this PR...
Things to be done in the following PRs including:

> polish of the tool ut, exit code, output log etc

**Review by bb7133 — APPROVED** [review]
