### PR TITLE
server: use max_allowed_packet to limit the packet size.

### LINKED ISSUE #31422: max_allowed_packet length is set to 1024 but its not working for string length.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set global max_allowed_packet=100;
set global net_buffer_length=100;  # change session
select @@net_buffer_length, @@max_allowed_packet;
SELECT length("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") as len;

```
### 2. What did you expect to see? (Required)
```sql
mysql> select @@net_buffer_length, @@max_allowed_packet;
+---------------------+----------------------+
| @@net_buffer_length | @@max_allowed_packet |
+---------------------+----------------------+
|                1024 |                 1024 |
+---------------------+----------------------+
1 row in set (0.00 sec)

mysql> SELECT length("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") as len;
ERROR 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes
```
### 3. What did you see instead (Required)
```sql
mysql> select @@net_buffer_length, @@max_allowed_packet;
+---------------------+----------------------+
| @@net_buffer_length | @@max_allowed_packet |
+---------------------+----------------------+
| 100                 |                 1024 |
+---------------------+----------------------+
1 row in set (0.00 sec)

mysql> SELECT length("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") as len;
+------+
| len  |
+------+
| 1024 |
+------+
1 row in set (0.00 sec)

```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.5.0-alpha-21-g722303bca-dirty
Edition: Community
Git Commit Hash: 722303bca8d279ff7c9d87e942095d320499f47e
Git Branch: master
UTC Build Time: 2022-01-05 19:11:01
GoVersion: go1.16.9
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

```

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #31422

Problem Summary:

The `max_allowed_packet` exists but did not work on previous versions.

### What is changed and how it works?

1. truncate the value of `max_allowed_packet` if it is not a multiple of 1024
2. report an error if the accumulated length of a packet is longer than `max_allowed_packet`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that system variable `max_allowed_packet` does not work.
```

### CODE REVIEW

**Review by dveeden — APPROVED** [review]

File: sessionctx/variable/variable.go [hunk 1]
```diff
@@ -188,6 +188,18 @@ func (sv *SysVar) GetSessionFromHook(s *SessionVars) (string, error) {
...
+		u, err := strconv.ParseUint(val, 10, 64)
+		if err != nil {
+			return errors.Trace(err)
+		}
+		// The value should be a multiple of 1024; nonmultiples are rounded down to the nearest multiple.
+		if u%1024 != 0 {
+			s.StmtCtx.AppendWarning(ErrTruncatedWrongValue.GenWithStackByArgs(MaxAllowedPacket, val))
+			u = (u / 1024) * 1024
+			val = strconv.FormatUint(u, 10)
+		}
```
Comment (mjonss) [inline sessionctx/variable/variable.go:201]: Please create a function and reuse the same code here and in SetGlobalSysVar.

**Review by mjonss — APPROVED** [review]
LGTM, but if possible please create a function for reuse code instead of copy/paste (see comment in `SetSessionFromHook`

File: server/conn.go [hunk 2]
```diff
@@ -394,7 +394,19 @@ func (cc *clientConn) writeInitialHandshake(ctx context.Context) error {
 }
 
 func (cc *clientConn) readPacket() ([]byte, error) {
-	return cc.pkt.readPacket()
+	// Default MaxAllowedPacket is 16MB.
```
Comment (bb7133) [inline server/conn.go:397]: It should be `64MB` according to:

* https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet
* https://github.com/pingcap/tidb/blob/69f664ae051c21e0edc48fcc5556f19fe4465a9a/sessionctx/variable/sysvar.go#L845

Although we have:

> The default [max_allowed_packet](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet) value built in to the client library is 1GB, but individual client programs might override this. For example, [mysql](https://dev.mysql.com/doc/refman/8.0/en/mysql.html) and [mysqldump](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html) have defaults of 16MB and 24MB, respectively.

The default of `16MB` is set by the `mysql` client.

Comment (bb7133) [reply server/conn.go:397]: Also, please define a constant named like `DefMaxAllowedPacket` here: https://github.com/pingcap/tidb/blob/69f664ae051c21e0edc48fcc5556f19fe4465a9a/sessionctx/variable/tidb_vars.go/#L673

And use this constant for the default values.

File: session/session_test.go [hunk 3]
```diff
@@ -644,6 +644,10 @@ func testTxnLazyInitialize(s *testSessionSuite, c *C, isPessimistic bool) {
 func (s *testSessionSuite) TestGlobalVarAccessor(c *C) {
 	varName := "max_allowed_packet"
 	varValue := "67108864" // This is the default value for max_allowed_packet
```
Comment (bb7133) [inline session/session_test.go:646]: Please change it according to https://github.com/pingcap/tidb/pull/33651#discussion_r841070585

File: server/packetio_test.go [hunk 4]
```diff
@@ -57,7 +57,8 @@ func TestPacketIORead(t *testing.T) {
 	// Test read one packet
 	brc := newBufferedReadConn(&bytesConn{inBuffer})
 	pkt := newPacketIO(brc)
-	bytes, err := pkt.readPacket()
+	var defMaxAllowedPacket uint64 = 67108864
```
Comment (bb7133) [inline server/packetio_test.go:60]: Please update it according to https://github.com/pingcap/tidb/pull/33651#discussion_r841070585

File: sessionctx/variable/variable.go [hunk 5]
```diff
@@ -188,6 +189,11 @@ func (sv *SysVar) GetSessionFromHook(s *SessionVars) (string, error) {
 
 // SetSessionFromHook calls the SetSession func if it exists.
 func (sv *SysVar) SetSessionFromHook(s *SessionVars, val string) error {
+	if sv.Name == MaxAllowedPacket {
```
Comment (bb7133) [inline sessionctx/variable/variable.go:192]: Please move the code snippet as the `SetSession()` function of [`MaxAllowedPacket`](https://github.com/pingcap/tidb/blob/69f664ae051c21e0edc48fcc5556f19fe4465a9a/sessionctx/variable/sysvar.go#L845)

File: sessionctx/variable/variable.go [hunk 6]
```diff
@@ -585,6 +591,21 @@ func init() {
 	}
 }
 
+// TruncateMaxAllowedPacket is used to truncate the value of max_allowed_packet to be a multiple of 1024,
+// nonmultiples are rounded down to the nearest multiple.
+func TruncateMaxAllowedPacket(sctx *stmtctx.StatementContext, val *string) error {
```
Comment (bb7133) [inline sessionctx/variable/variable.go:596]: IMHO it's better to define the function as:

```
func TruncateMaxAllowedPacket(sctx *stmtctx.StatementContext, val string) (uint, error)
```
For 2 reasons:

1. The 'side effect'(modification of income parameter) can be avoided.
2. You don't need to parse a string and convert the integer back to string.

File: server/conn.go [hunk 7]
```diff
@@ -394,7 +394,19 @@ func (cc *clientConn) writeInitialHandshake(ctx context.Context) error {
...
+	maxAllowedPacket := uint64(16777216)
+	var err error
+	if cc.ctx != nil {
+		if valStr, _ := cc.ctx.GetSessionVars().GetSystemVar(variable.MaxAllowedPacket); len(valStr) > 0 {
```
Comment (bb7133) [inline server/conn.go:401]: I believe that there will be a tiny performance regression if we have a short-read only workload like `point-get`. But it's not easy to avoid parsing `valStr` here.

We can think treat it as an enhancement in the future.

File: sessionctx/variable/variable.go (hunk 5 above)
Comment (CbcWestwolf) [reply sessionctx/variable/variable.go:192]: If the code snippet is moved to `SetSession()`, the truncation of `val` would be invalid in `SetSessionFromHook`, so the statement [`s.systems[sv.Name] = val`](https://github.com/pingcap/tidb/blob/69f664ae051c21e0edc48fcc5556f19fe4465a9a/sessionctx/variable/variable.go#L202) would set back the un-truncated value.

Comment (bb7133) [reply sessionctx/variable/variable.go:192]: I see.

It is a concern for me that we have an explicit `if` for `MaxAllowedPacket`, I think those codes should be `SysVar`-specific rather than defined in `SetSessionFromHook`.

@morgo Do you have any suggestion?

File: server/conn.go (hunk 7 above)
Comment (morgo) [reply server/conn.go:401]: FWIW, the current way other variables avoid parsing the `valStr` is by using a Getter/Setter like this:

https://github.com/pingcap/tidb/blob/8dc1f6b0926e0bf26f38109fceec7992c878cdde/sessionctx/variable/sysvar.go#L212-L221

We mostly do this for instance scoped variables, but we can technically cache a global like this too.

File: session/session.go [hunk 8]
```diff
@@ -1340,6 +1340,13 @@ func (s *session) SetGlobalSysVar(name, value string) (err error) {
 	if value, err = sv.Validate(s.sessionVars, value, variable.ScopeGlobal); err != nil {
 		return err
 	}
+	if name == variable.MaxAllowedPacket {
+		u, err := variable.TruncateMaxAllowedPacket(s.sessionVars.StmtCtx, value)
+		if err != nil {
+			return err
+		}
+		value = strconv.FormatUint(u, 10)
+	}
```
Comment (morgo) [inline session/session.go:1349]: Can this be moved to the validation func? The validation func should be able to check if Scope == ScopeGlobal.

File: sessionctx/variable/variable.go (hunk 5 above)
Comment (morgo) [reply sessionctx/variable/variable.go:192]: Yeah, I would like to move it to the sysvar as well.

Sorry, I'm not sure I understand the problem yet. Can you do the truncation in the `Validation()` func? (it should be able to change values if required in validation)

File: executor/set_test.go [hunk 9]
```diff
@@ -601,6 +601,16 @@ func TestSetVar(t *testing.T) {
...
+
+	// the value of max_allowed_packet should be a multiple of 1024
+	tk.MustExec("set @@global.max_allowed_packet=16385")
+	tk.MustQuery("show warnings").Check(testkit.RowsWithSep("|", "Warning|1292|Truncated incorrect max_allowed_packet value: '16385'"))
+	result := tk.MustQuery("select @@global.max_allowed_packet;")
+	result.Check(testkit.Rows("16384"))
+	tk.MustExec("set @@max_allowed_packet=2047")
+	tk.MustQuery("show warnings").Check(testkit.RowsWithSep("|", "Warning|1292|Truncated incorrect max_allowed_packet value: '2047'"))
+	result = tk.MustQuery("select @@max_allowed_packet;")
+	result.Check(testkit.Rows("1024"))
```
Comment (bb7133) [inline executor/set_test.go:613]: Please add a test case for `set @@global.max_allowed_packet=0`(the result should be `1024`).

Also, I noticed that MySQL gives the following warning for `set @@global.max_allowed_packet=0`:

```
mysql> show warnings;
+---------+------+-------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                   |
+---------+------+-------------------------------------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect max_allowed_packet value: '0'                                         |
| Warning | 1708 | The value of 'max_allowed_packet' should be no less than the value of 'net_buffer_length' |
+---------+------+-------------------------------------------------------------------------------------------+
```
However, `net_buffer_length` is a no-op variable in TiDB, so I don't think this warning is necessary so we don't have to add the extra warning check for it. /cc @morgo

Comment (morgo) [reply executor/set_test.go:613]: I agree it's not necessary to add the warning.

File: server/conn.go [hunk 10]
```diff
@@ -1075,6 +1080,11 @@ func (cc *clientConn) Run(ctx context.Context) {
 							zap.Error(err),
 						)
 					}
+				} else if errors.ErrorEqual(err, errNetPacketTooLarge) {
+					err := cc.writeError(ctx, err)
```
Comment (bb7133) [inline server/conn.go:1084]: Some weird behavior I encountered:
```
tidb> set @@max_allowed_packet=0;
tidb> CREATE TABLE WALLET(user_id int, currency_id int, amount int, expiry_time DATETIME, is_lifetime int, pack_id int, sub_org_id int);
```
Then(see attached sql.txt):
```
tidb> source sql.txt
```
* MySQL:
```
mysql> source sql.txt
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    15
Current database: *** NONE ***

ERROR 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes
mysql> source sql.txt
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    16
Current database: *** NONE ***

ERROR 1153 (08S01): Got a packet bigger than 'max_allowed_packet' bytes
```

This PR:
```
tidb> source sql.txt
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    431
Current database: test

ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    433
Current database: test

ERROR 2006 (HY000): MySQL server has gone away
tidb> source sql.txt
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    435
Current database: test

ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    437
Current database: test

ERROR 2006 (HY000): MySQL server has gone away
```
However, if I set a breakpoint right here, and 'continue' when the debugger paused here, the result of TiDB is exactly the same with MySQL.

Comment (bb7133) [reply server/conn.go:1084]: [sql.txt](https://github.com/pingcap/tidb/files/8465258/sql.txt)

Comment (bb7133) [reply server/conn.go:1084]: I see, it is related to the `auto-tls`[https://docs.pingcap.com/tidb/dev/tidb-configuration-file#auto-tls] configuration, if it is set to `true`, the error message is `ERROR 2006 (HY000): MySQL server has gone away`.

File: server/packetio.go [hunk 11]
```diff
@@ -76,7 +77,8 @@ func (p *packetIO) setReadTimeout(timeout time.Duration) {
 	p.readTimeout = timeout
 }
 
-func (p *packetIO) readOnePacket() ([]byte, error) {
+// maxAllowedPacket is the maximum size of one packet. accumulatedLength count the length of received data totally.
+func (p *packetIO) readOnePacket(maxAllowedPacket uint64, accumulatedLength uint64) ([]byte, error) {
```
Comment (bb7133) [inline server/packetio.go:81]: How about making `maxAllowedPacket` and `accumulatedLength` the member fields of `packetIO`, just like `readTimeout`?

So that we do not need to change the signature of `readOnePacket`.

**Review by bb7133 — APPROVED** [review]
LGTM

**Comment by tiancaiamao** [comment]
`max_allowed_packet` is the max allowed packet size of **a packet**, not the accumulated size of the all received data. @CbcWestwolf 

See https://dev.mysql.com/doc/refman/8.0/en/packet-too-large.html
