### PR TITLE
executor: fix data race for chunk resource channel in index merge join

### LINKED ISSUE #18196: data race in index_lookup_merge_join.go
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2020-06-24T05:41:39.836Z] WARNING: DATA RACE

[2020-06-24T05:41:39.836Z] Read at 0x00c05d13ca30 by goroutine 68:

[2020-06-24T05:41:39.836Z]   runtime.chansend()

[2020-06-24T05:41:39.836Z]       /usr/local/go/src/runtime/chan.go:142 +0x0

[2020-06-24T05:41:39.836Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).doMergeJoin.func1()

[2020-06-24T05:41:39.836Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:535 +0x344

[2020-06-24T05:41:39.836Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).doMergeJoin()

[2020-06-24T05:41:39.836Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:591 +0x99f

[2020-06-24T05:41:39.836Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).handleTask()

[2020-06-24T05:41:39.836Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:500 +0xc33

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor.(*innerMergeWorker).run()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:420 +0x28d

[2020-06-24T05:41:39.837Z] 

[2020-06-24T05:41:39.837Z] Previous write at 0x00c05d13ca30 by goroutine 758:

[2020-06-24T05:41:39.837Z]   runtime.closechan()

[2020-06-24T05:41:39.837Z]       /usr/local/go/src/runtime/chan.go:334 +0x0

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor.(*IndexLookUpMergeJoin).Close()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join.go:715 +0xef

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:171 +0xad

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor.(*LimitExec).Close()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:1058 +0x6c

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor.(*baseExecutor).Close()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:171 +0xad

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Close()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:317 +0x24e

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor.(*recordSet).Close()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:151 +0x59

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/session.(*execStmtResult).Close()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1246 +0x7b

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustExec()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:209 +0x426

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:46 +0x469

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:36 +0x2b1

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:35 +0x27a

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_merge_join_test.go:34 +0x243

[2020-06-24T05:41:39.837Z]   github.com/pingcap/failpoint.parseTerm()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:148 +0x24d

[2020-06-24T05:41:39.837Z]   github.com/pingcap/failpoint.parse()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:125 +0xb4

[2020-06-24T05:41:39.837Z]   github.com/pingcap/failpoint.newTerms()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/terms.go:97 +0x6a

[2020-06-24T05:41:39.837Z]   github.com/pingcap/failpoint.(*Failpoint).Enable()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoint.go:53 +0x53

[2020-06-24T05:41:39.837Z]   github.com/pingcap/failpoint.(*Failpoints).Enable()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:104 +0x160

[2020-06-24T05:41:39.837Z]   github.com/pingcap/tidb/executor_test.(*testSuite9).TestIssue18068()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/failpoint@v0.0.0-20200603062251-b230c36c413c/failpoints.go:224 +0x79

[2020-06-24T05:41:39.837Z]   runtime.call32()

[2020-06-24T05:41:39.837Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-06-24T05:41:39.837Z]   reflect.Value.Call()

[2020-06-24T05:41:39.837Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-06-24T05:41:39.837Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-06-24T05:41:39.837Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-06-24T05:41:39.837Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
```

### 4. Affected version (Required)

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/40963/pipeline
seen in https://github.com/pingcap/tidb/pull/18180

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #18196

Problem Summary: as the title says.

### What is changed and how it works?

How it Works: add a variable to control it.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- fix data race for chunk resource channel in index merge join

### CODE REVIEW

File: executor/index_lookup_merge_join.go [hunk 1]
```diff
@@ -531,7 +537,7 @@ func (imw *innerMergeWorker) doMergeJoin(ctx context.Context, task *lookUpMergeJ
 			case <-ctx.Done():
 				return
 			}
-		} else {
+		} else if !imw.lookup.isClosed.Load().(bool) {
```
Comment (SunRunAway) [inline executor/index_lookup_merge_join.go:540]: It still has potentiality to panic,

1. execute line 540
2. `close(e.joinChkResourceCh[i])`
3. execute line 541
