### PR TITLE
expression: fix BIT type columns are not padded with left zeros

### LINKED ISSUE #25506: `BIT` type columns are not padded with left zeros
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists tbl_3, tbl_23;
create table tbl_3 (col_15 bit(20));
insert into tbl_3 values (65535);
insert into tbl_3 values (255);
create table tbl_23 like tbl_3;
(select col_15 from tbl_23) union all (select col_15 from tbl_3 for update);
```

### 2. What did you expect to see? (Required)

MySQL:
```
+----------------+
| col_15         |
+----------------+
| 0x00FFFF       |
| 0x0000FF       |
+----------------+
```

### 3. What did you see instead (Required)

TiDB:
```
+----------------+
| col_15         |
+----------------+
| 0xFFFF         |
| 0xFF           |
+----------------+
```

### 4. What is your TiDB version? (Required)

master 
```
commit efc774aa5f9745359c5fe206aaafda768b1b0632 (upstream/master)
Author: ZhuoZhi <517770911@qq.com>
Date:   Wed Jun 16 15:12:37 2021 +0800

    planner: check filter condition in func convertToPartialTableScan (#25294)
```

### PR DESCRIPTION
**Pull request by zhaoxugang**
### What problem does this PR solve?

Issue Number: close #25506 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- fix BIT type columns are not padded with left zeros

### CODE REVIEW

**Comment by zhaoxugang** [comment]
@wshwsh12 PTAL

**Review by wshwsh12 — COMMENTED** [review]
Thank you for your contribution.   I am glad to review your code.

Here are some suggestions about this pr:
1. I have some nitpick comments, and please address.
2. We also need modify the behavior in function `executeToInt` for non-vec calculation. We can set set `tidb_enable_vectorized_expression = off;` to use non-vec calculation, and it also gets wrong result.

Rest LGTM. Good job.:heart:

**Comment by zhaoxugang** [comment]
> Thank you for your contribution. I am glad to review your code.
> 
> Here are some suggestions about this pr:
> 
> 1. I have some nitpick comments, and please address.
> 2. We also need modify the behavior in function `executeToInt` for non-vec calculation. We can set set `tidb_enable_vectorized_expression = off;` to use non-vec calculation, and it also gets wrong result.
> 
> Rest LGTM. Good job.❤️

done

File: expression/chunk_executor.go [hunk 1]
```diff
@@ -125,11 +125,12 @@ func evalOneVec(ctx sessionctx.Context, expr Expression, input *chunk.Chunk, out
 			i64s := result.Int64s()
 			buf := chunk.NewColumn(ft, input.NumRows())
 			buf.ReserveBytes(input.NumRows())
+			byteSize := (ft.Flen + 7) >> 3
```
Comment (mmyj) [inline expression/chunk_executor.go:128]: Could anyone explain to me why we use `byteSize := (ft.Flen + 7) >> 3` here?

Comment (mmyj) [reply expression/chunk_executor.go:128]: And I find two other places using `(ft.Flen + 7) >> 3` also. Should we add a comment for it? Maybe there are people who don’t understand it, just like me.

Comment (zhaoxugang) [reply expression/chunk_executor.go:128]: In bit Type, Flen represents the number of bits, byteSize := (ft.Flen + 7) >> 3 is to convert the number of bits to the number of bytes.@mmyj

Comment (mmyj) [reply expression/chunk_executor.go:128]: Thank you for your explain, and what is the effect of `(+7)>>3`?

Comment (zhaoxugang) [reply expression/chunk_executor.go:128]: >> 3 is the same as dividing by 8,
+7 is to prevent the number of bits that cannot be divisible by 8 causing the resulting bytes space is not enough to store the original data
for example if ft.Flen = 23，23/8 = 2, it's 16 bytes is not enough to store 20 bytes,but (23+7)/8 = 3,it's ok @mmyj

File: expression/chunk_executor.go [hunk 2]
```diff
@@ -262,7 +263,9 @@ func executeToInt(ctx sessionctx.Context, expr Expression, fieldType *types.Fiel
 		return nil
 	}
 	if fieldType.Tp == mysql.TypeBit {
-		output.AppendBytes(colID, types.NewBinaryLiteralFromUint(uint64(res), -1))
+		ft := expr.GetType()
+		byteSize := (ft.Flen + 7) >> 3
```
Comment (wshwsh12) [inline expression/chunk_executor.go:267]:
```suggestion
		byteSize := (fieldType.Flen + 7) >> 3
```

**Review by wshwsh12 — APPROVED** [review]
LGTM

File: expression/chunk_executor.go (hunk 1 above)
Comment (mmyj) [reply expression/chunk_executor.go:128]: Thanks

**Comment by mmyj** [comment]
LGTM

**Review by mmyj — APPROVED** [review]
LGTM
