### PR TITLE
executor: fix unexpected results when do index merge join on outer join

### LINKED ISSUE #20571: delete unrelated column has different results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use test;
source [test.txt](https://github.com/pingcap/tidb/files/5415891/test.txt);
SELECT count(*) from table_400_ascii_ascii_bin_undef_1 t1 left join table_300_latin1_latin1_bin_undef_2 t2 on t1. `col_smallint_key_unsigned` = t2. `col_smallint_key_unsigned` and t1. `col_bigint_key_signed` < 9143449222791010176 where t1. `col_tinyint_key_unsigned` != -322  order by t1.pk, t2.pk;
alter table table_300_latin1_latin1_bin_undef_2 drop column `col_bigint_key_unsigned`;
select sleep(60);
SELECT count(*) from table_400_ascii_ascii_bin_undef_1 t1 left join table_300_latin1_latin1_bin_undef_2 t2 on t1. `col_smallint_key_unsigned` = t2. `col_smallint_key_unsigned` and t1. `col_bigint_key_signed` < 9143449222791010176 where t1. `col_tinyint_key_unsigned` != -322  order by t1.pk, t2.pk;

### 2. What did you expect to see? (Required)
```
mysql> SELECT count(*) from table_400_ascii_ascii_bin_undef_1 t1 left join table_300_latin1_latin1_bin_undef_2 t2 on t1. `col_smallint_key_unsigned` = t2. `col_smallint_key_unsigned` and t1. `col_bigint_key_signed` < 9143449222791010176 where t1. `col_tinyint_key_unsigned` != -322  order by t1.pk, t2.pk;
+----------+
| count(*) |
+----------+
|    24424 |
+----------+
1 row in set (0.00 sec)

mysql> alter table table_300_latin1_latin1_bin_undef_2 drop column `col_bigint_key_unsigned`;
Query OK, 0 rows affected (0.02 sec)

mysql> select sleep(60);

+-----------+
| sleep(60) |
+-----------+
|         0 |
+-----------+
1 row in set (1 min 0.01 sec)

mysql> SELECT count(*) from table_400_ascii_ascii_bin_undef_1 t1 left join table_300_latin1_latin1_bin_undef_2 t2 on t1. `col_smallint_key_unsigned` = t2. `col_smallint_key_unsigned` and t1. `col_bigint_key_signed` < 9143449222791010176 where t1. `col_tinyint_key_unsigned` != -322  order by t1.pk, t2.pk;
+----------+
| count(*) |
+----------+
|    24424 |
+----------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> SELECT count(*) from table_400_ascii_ascii_bin_undef_1 t1 left join table_300_latin1_latin1_bin_undef_2 t2 on t1. `col_smallint_key_unsigned` = t2. `col_smallint_key_unsigned` and t1. `col_bigint_key_signed` < 9143449222791010176 where t1. `col_tinyint_key_unsigned` != -322  order by t1.pk, t2.pk;
+----------+
| count(*) |
+----------+
|    31756 |
+----------+
1 row in set (0.00 sec)

mysql> alter table table_300_latin1_latin1_bin_undef_2 drop column `col_bigint_key_unsigned`;
Query OK, 0 rows affected (0.02 sec)

mysql> select sleep(60);

+-----------+
| sleep(60) |
+-----------+
|         0 |
+-----------+
1 row in set (1 min 0.01 sec)

mysql> SELECT count(*) from table_400_ascii_ascii_bin_undef_1 t1 left join table_300_latin1_latin1_bin_undef_2 t2 on t1. `col_smallint_key_unsigned` = t2. `col_smallint_key_unsigned` and t1. `col_bigint_key_signed` < 9143449222791010176 where t1. `col_tinyint_key_unsigned` != -322  order by t1.pk, t2.pk;
+----------+
| count(*) |
+----------+
|    24424 |
+----------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

master 2f067c054255a7452e32f341b7407a4dd071fb9f and release-4.0 dced64d5cb108782b4bdc47e6338184c939972a2

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #20571, close https://github.com/pingcap/tidb/issues/20953

### What is changed and how it works?

How it Works: filter outer rows in do merge join

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- fix unexpected results when do merge join on outer join

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
please write the integration test to `tidb-test`.

**Comment by wjhuang2016** [comment]
Could you make the PR description more clearer? What's the root cause?

File: executor/index_lookup_merge_join.go [hunk 1]
```diff
@@ -558,6 +558,9 @@ func (imw *innerMergeWorker) doMergeJoin(ctx context.Context, task *lookUpMergeJ
 		hasMatch, hasNull, cmpResult := false, false, initCmpResult
 		// If it has iterated out all inner rows and the inner rows with same key is empty,
 		// that means the outer row needn't match any inner rows.
+		if task.outerMatch != nil && !task.outerMatch[outerIdx.ChkIdx][outerIdx.RowIdx] {
```
Comment (XuHuaiyu) [inline executor/index_lookup_merge_join.go:561]: Do we need to put this check to line 567?
The comment above this check is incompatible

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
