### PR TITLE
partition: reorganized the execution order of partition table update operators

### LINKED ISSUE #49998: executor: global index has correct problem when insert
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```SQL
use test;
CREATE TABLE tbl_51 (
		col_334 mediumint(9) NOT NULL DEFAULT '-3217641',
		col_335 mediumint(8) unsigned NOT NULL DEFAULT '2002468',
		col_336 enum('alice','bob','charlie','david') COLLATE utf8_general_ci NOT NULL DEFAULT 'alice',
		PRIMARY KEY (col_334,col_336,col_335) /*T![clustered_index] CLUSTERED */,
		UNIQUE KEY idx_116 (col_334,col_335),
		UNIQUE KEY idx_117 (col_336,col_334),
		UNIQUE KEY idx_118 (col_336)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
		PARTITION BY HASH( col_334 )
		PARTITIONS 6;
insert into tbl_51 values(-3112969,3273861,'charlie'),(-3040776,4159759,'charlie');

```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
duplicate key error

### 3. What did you see instead (Required)
<img width="372" alt="image" src="https://github.com/pingcap/tidb/assets/20724552/3e44dd9b-c416-428d-8da3-3c95d487ae0a">


### 4. What is your TiDB version? (Required)
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.6.0-alpha-629-g89fc4403f3-dirty
Edition: Community
Git Commit Hash: 89fc4403f3a05d59a6793bf1965dc2281e3fb29f
Git Branch: local/fix_global_index_under_clustered_index
UTC Build Time: 2024-01-03 03:27:27
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
<!-- Paste the output of SELECT tidb_version() -->

### LINKED ISSUE #52380: Could insert duplicate values into a unique index with global index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set tidb_enable_global_index=true;
CREATE TABLE `t` (
  `a` int(11) NOT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `idx1` (`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY HASH (`a`) PARTITIONS 5;

begin;
insert into t values (1, 2, 3);
insert into t values (2, 2, 3);
```

### 2. What did you expect to see? (Required)

```
mysql> insert into t values (2, 2, 3);
ERROR 1062 (23000): Duplicate entry '2' for key 't.idx1'
```

### 3. What did you see instead (Required)

insert success

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.0.0-alpha-719-gc7d4c9cebb
Edition: Community
Git Commit Hash: c7d4c9cebb207bf5bf4dd4e532c44fe9ad753774
Git Branch: master
UTC Build Time: 2024-04-07 08:23:01
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #52380, close #49998

Problem Summary: As `updateRecord`, we should remove record first and use `memBuffer.Staging()` to restore it when we meet errors in add records.

Ref code link
https://github.com/pingcap/tidb/blob/510f44f5c0bf1b6c50e6be6f55c4e61decf337ce/pkg/executor/write.go#L165-L195

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/table/tables/index.go [hunk 1]
```diff
@@ -355,15 +354,6 @@ func (c *index) Create(sctx table.MutateContext, txn kv.Transaction, indexedValu
 			}
 			continue
 		}
-		if c.idxInfo.Global && len(value) != 0 && !bytes.Equal(value, idxVal) {
```
Comment (Defined2014) [inline pkg/table/tables/index.go:358]: Added by https://github.com/pingcap/tidb/pull/42311. After change the update operators, no need this code anymore.

File: pkg/table/tables/partition.go [hunk 2]
```diff
@@ -1766,21 +1766,31 @@ func partitionedTableUpdateRecord(gctx context.Context, ctx table.MutateContext,
...
+		defer func() {
+			// NOTICE: Don't create a new `err` in this branch.
+			if err == nil {
+				memBuffer.Release(sh)
+			} else {
+				memBuffer.Cleanup(sh)
+			}
+		}()
+
 		err = t.GetPartition(from).RemoveRecord(ctx, h, currData)
```
Comment (Defined2014) [inline pkg/table/tables/partition.go:1784]: As `updateRecord`, remove record first.

File: pkg/table/tables/partition.go [hunk 3]
```diff
@@ -1801,17 +1811,16 @@ func partitionedTableUpdateRecord(gctx context.Context, ctx table.MutateContext,
 			tbl := t.GetPartition(newTo)
 			return tbl.UpdateRecord(gctx, ctx, h, currData, newData, touched)
```
Comment (mjonss) [inline pkg/table/tables/partition.go:1812]: What happens if an error is returned here? Will the deferred function still do the right thing?

**Review by zimulala — APPROVED** [review]
LGTM

File: pkg/table/tables/partition.go (hunk 3 above)
Comment (Defined2014) [reply pkg/table/tables/partition.go]: Updated

**Comment by Defined2014** [comment]
> @Defined2014 I assume this will also close #49998 ?

Yes, linked.

File: pkg/table/tables/partition.go [hunk 4]
```diff
@@ -1763,24 +1763,27 @@ func partitionedTableUpdateRecord(gctx context.Context, ctx table.MutateContext,
...
+		return errors.Trace(err)
+	}
+	memBuffer := txn.GetMemBuffer()
+	sh := memBuffer.Staging()
+	defer memBuffer.Cleanup(sh)
+
 	// The old and new data locate in different partitions.
 	// Remove record from old partition and add record to new partition.
 	if from != to {
-		_, err = t.GetPartition(to).AddRecord(ctx, newData)
```
Comment (tiancaiamao) [inline pkg/table/tables/partition.go:1769]: Why the old code does not get duplicate key error in this AddRecord operation?

Comment (Defined2014) [reply pkg/table/tables/partition.go:1769]: Because the deleted code https://github.com/pingcap/tidb/pull/52442/files#r1557015648

**Review by tiancaiamao — APPROVED** [review]

**Review by mjonss — APPROVED** [review]
LGTM
