### PR TITLE
executor: sync deletable columns to binlog when remove record

### LINKED ISSUE #53133: report error "EncodeRow error: data and columnID count not match" when deleting a row during add column DDL job with binlog open
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I wrote a test to reproduce it:

https://github.com/lcwangchao/tidb/commit/f4346604bddaa4633db05c8b8ad29a43148655f9

It has some conditions:

1. Add column job
2. Binlog enabled
3. Before new column state to public, delete a row

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

```
        	Error:      	Received unexpected error:
        	            	EncodeRow error: data and columnID count not match 3 vs 2
        	            	github.com/pingcap/tidb/pkg/tablecodec.EncodeOldRow
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #53133

Problem Summary:

Previously, when TiDB writes delete records to binlog, column count of schema and data mismatch. This is because only public columns are selected, while data includes all deletable columns.

### What changed and how does it work?

Make schema use all deletable columns.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
  1. deploy two TiDB clusters, and start pump & drainer.
  2. modify upstream TiDB code:
  ```diff
  diff --git a/pkg/config/config.toml.example b/pkg/config/config.toml.example
  index c1438a9e85..b73828367d 100644
  --- a/pkg/config/config.toml.example
  +++ b/pkg/config/config.toml.example
  @@ -416,7 +416,7 @@ capacity-mb = 1000.0
   # enable to write binlog.
   # NOTE: If binlog is enabled with Kafka (e.g. arbiter cluster),
   # txn-total-size-limit should be less than 1073741824(1G) because this is the maximum size that can be handled by Kafka.
  -enable = false
  +enable = true
   
   # WriteTimeout specifies how long it will wait for writing binlog to pump.
   write-timeout = "15s"
  diff --git a/pkg/ddl/column.go b/pkg/ddl/column.go
  index 206b64d513..1727ba4c44 100644
  --- a/pkg/ddl/column.go
  +++ b/pkg/ddl/column.go
  @@ -173,6 +173,7 @@ func onAddColumn(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int64, err error)
                  // reorganization -> public
                  // Adjust table column offset.
                  failpoint.InjectCall("onAddColumnStateWriteReorg")
  +               time.Sleep(20 * time.Second)
                  offset, err := LocateOffsetToMove(columnInfo.Offset, pos, tblInfo)
                  if err != nil {
                          return ver, errors.Trace(err)
  ```
  3. execute SQL at upstream:
  ```
  -- session 1
  CREATE TABLE `t` (
    `a` int(11) DEFAULT NULL,
    `b` int(11) DEFAULT NULL,
    `c` int(11) DEFAULT NULL,
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
  insert into t values (1, 1, 1), (2, 2, 2), (3, 3, 3);
  alter table t add column d int default 3;
  ```
  ```
  -- session 2
  delete from t where a = 1;
  ```
  4. execute SQL at downstream:
  ```
  mysql> select * from t;
  +------+------+------+------+
  | a    | b    | c    | d    |
  +------+------+------+------+
  |    3 |    3 |    3 |    3 |
  |    2 |    2 |    2 |    3 |
  +------+------+------+------+
  2 rows in set (0.00 sec)
  ```
  Even if we synchronize a 4-columns row to binlog, drainer can handle it correctly by decoding necessary(public) columns:
  https://github.com/pingcap/tidb-binlog/blob/6fba4f883a0c6c7e0d68b3b8aef1a53d9454b273/drainer/translator/mysql.go#L88-L90
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/table/tables/tables.go [hunk 1]
```diff
@@ -1403,6 +1399,21 @@ func (t *TableCommon) RemoveRecord(ctx table.MutateContext, h kv.Handle, r []typ
...
 }
 
+func projectPublicColData(t *TableCommon, deletableData []types.Datum) (publicData []types.Datum, colIDs []int64) {
+	publicColLen := len(t.Cols())
+	publicData = make([]types.Datum, 0, publicColLen)
+	colIDs = make([]int64, 0, publicColLen+1)
+	deletableCols := t.DeletableCols()
+	for i, d := range deletableData {
+		dCol := deletableCols[i]
+		if dCol.State == model.StatePublic {
```
[the remark this answers is not in the document]
Comment (tangenta) [reply pkg/table/tables/tables.go:1409]: For lossy modifying a column, it consists of two steps:

1. add a hidden column
2. drop the old column

Since DDL is only synced when the job state is done, the hidden column does not exists in downstream.

File: pkg/table/tables/tables.go [hunk 2]
```diff
@@ -1368,7 +1368,7 @@ func (t *TableCommon) RemoveRecord(ctx table.MutateContext, h kv.Handle, r []typ
 	memBuffer.Release(sh)
 
 	if shouldWriteBinlog(ctx.GetSessionVars(), t.meta) {
-		cols := t.Cols()
+		cols := t.DeletableCols()
```
Comment (tangenta) [inline pkg/table/tables/tables.go:1371]: Consistent with https://github.com/pingcap/tidb/blob/afd23434dc558f00514dd7cc0295807002b69e16/pkg/planner/core/logical_plan_builder.go#L4893-L4895

Comment (D3Hunter) [reply pkg/table/tables/tables.go:1371]: when `add column` this list will contain the new column that `binlog` does not know now, can binlog handle it?

Comment (tangenta) [reply pkg/table/tables/tables.go:1371]: Drainer can handle it correctly by only decoding necessary(public) columns:
https://github.com/pingcap/tidb-binlog/blob/6fba4f883a0c6c7e0d68b3b8aef1a53d9454b273/drainer/translator/mysql.go#L88-L90

**Review by D3Hunter — APPROVED** [review]
