### PR TITLE
util/ranger: use different full range for pk, not-null col and normal col when range fallback happens

### LINKED ISSUE #37760: wrong query result when tidb_opt_range_max_size = 1
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
use test;
create table t(a int primary key);
insert into t values (2), (4), (6);
set @@tidb_opt_range_max_size = 1;
select * from t where a;
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t where a;
+---+
| a |
+---+
| 2 |
| 4 |
| 6 |
+---+
3 rows in set, 1 warning (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select * from t where a;
Empty set, 1 warning (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0-1544-g12ae85f32
Edition: Community
Git Commit Hash: 12ae85f32b11ba4ed5ed9ec111cb6777d860e3ac
Git Branch: master
UTC Build Time: 2022-09-12 03:51:47
GoVersion: go1.18.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #37760

Problem Summary:

### What is changed and how it works?
When column range fallback happens:
1. For primary key, use `FullIntRange`.
2. For not-null column, use `FullNotNullRange`.
3. For other column, use `FullRange`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/integration_test.go [hunk 1]
```diff
@@ -7297,3 +7297,15 @@ func TestPlanCacheForTableRangeFallback(t *testing.T) {
...
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t(a int primary key)")
+	tk.MustExec("insert into t values (2), (4), (6)")
+	tk.MustExec("set @@tidb_opt_range_max_size=1")
+	tk.MustQuery("select * from t where a").Check(testkit.Rows("2", "4", "6"))
+	tk.MustQuery("show warnings").Check(testkit.Rows("Warning 1105 Memory capacity of 1 bytes for 'tidb_opt_range_max_size' exceeded when building ranges. Less accurate ranges such as full range are chosen"))
+}
```
Comment (Yisaer) [inline planner/core/integration_test.go:7311]: I think the testcase should cover `pk` / `non-null` columns / other columns.

**Review by Yisaer — APPROVED** [review]
