### PR TITLE
*: Support for caching_sha2_password authentication

### LINKED ISSUE #9411: Support for caching_sha2_password
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Windows 10
libmysql 8.0.4-3 installed via vcpkg
Visual Studio 2017

```C
// MysqlTest.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <mysql/mysql.h>

int main()
{
	MYSQL mysql;

	mysql_init(&mysql);
	mysql_options(&mysql, MYSQL_SET_CHARSET_NAME, "utf8");
	if (!mysql_real_connect(&mysql, "127.0.0.1", "root", "", "information_schema", 4000, NULL, 0))
	{
		fprintf(stderr, "Failed to connect to database: Error: %s\n",
			mysql_error(&mysql));
		return 1;
	}
	else
	{
		printf("success!\n");
		return 0;
	}
}
```

build/run an example C client that uses libmysql to connect to database.  I actually started out trying to use Rust with Diesel but boiled the problem down to using the C library.

2. What did you expect to see?

"success!"

especially since DataGrip (JDBC driver) and mysql cli can connect and work fine.

3. What did you see instead?

"Failed to connect to database: Error: Unknown MySQL error"

TiDB had no errors it its log.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

deployed via docker-compose (https://github.com/pingcap/tidb-docker-compose)

Release Version: v3.0.0-beta-27-g6398788
Git Commit Hash: 6398788f6bb722d29d06b754e3d1d61d02a3090e
Git Branch: master
UTC Build Time: 2019-01-31 08:42:28
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #9411 

Problem Summary:
- `mysql_native_password` uses the SHA1 hash algorithm which is not future proof
- Migrating users that use `caching_sha2_password` from MySQL to TiDB doesn't work

### What is changed and how it works?

What this does:
- Check the `plugin` column of the `mysql.user` table.
- Based on the plugin from the user record and the plugin the client
  sent we may need to switch the authentication plugin to match the
  one from the user record
- For accounts with `caching_sha2_password` send the "fast
  authentication failed" response to trigger full authentication.
- call `auth.CheckShaPassword` to validate the user.

Implemented functionality:
- Full authentication with `caching_sha2_password` over TLS
- The `default_authentication_plugin` variable
- `CREATE USER... IDENTIFIED WITH 'caching_sha2_password'...`

Missing functionality:
- Support for the RSA public key request packet & response
- Support for RSA key based secret exchange
- Fast authentication (validate against cached entry)

### Related changes

- Requires https://github.com/pingcap/parser/pull/1236
- https://github.com/pingcap/tidb/pull/24141 makes testing
  of this easier, but this is not required.

Tests 

- Manual test (add detailed scripts or steps below)
- Unit tests

Create users with:
- `mysql_native_password`
- `caching_sha2_password`
- An empty password

Try to authenticate with all of them.

Side effects

- Unknown

### Release note 

- Support for `caching_sha2_password` authentication

### CODE REVIEW

**Comment by dveeden** [comment]
cc @morgo @bb7133

File: server/conn.go [hunk 1]
```diff
@@ -643,27 +646,63 @@ func (cc *clientConn) readOptionalSSLRequestAndHandshakeResponse(ctx context.Con
...
+		resp.Auth = newAuth
+	}
+
+	switch resp.AuthPlugin {
+	case mysql.AuthCachingSha2Password:
+		resp.Auth, err = cc.authSha(ctx)
+	case mysql.AuthNativePassword:
+	default:
+		return errors.New("Unknown auth plugin")
+	}
```
Comment (morgo) [inline server/conn.go:669]: You could potentially use an `authSwitchRequest` (from deleted code above) if the plugin is unknown. The downside is that this is hard to test.

File: privilege/privileges/privileges.go [hunk 2]
```diff
@@ -161,6 +161,33 @@ func (p *UserPrivileges) RequestVerificationWithUser(db, table, column string, p
 	return mysqlPriv.RequestVerification(roles, user.Username, user.Hostname, db, table, column, priv)
 }
 
+func (p *UserPrivileges) isValidHash(record *UserRecord) bool {
+	pwd := record.AuthenticationString
+	if len(pwd) == 0 {
```
Comment (morgo) [inline privilege/privileges/privileges.go:166]: AFAIK there are some linters which prefer checking an empty string as `pwd == ""`. It's not currently enforced in our linter suite but may be in future.

File: server/conn.go [hunk 3]
```diff
@@ -715,6 +763,34 @@ func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
 	return nil
 }
 
+func (cc *clientConn) checkAuthPlugin(ctx context.Context, authPlugin *string) ([]byte, error) {
+	// Open a context unless this was done before.
+	if cc.ctx == nil {
+		cc.openSession()
+	}
+
+	host, _, err := cc.PeerHost("")
```
Comment (morgo) [inline server/conn.go:772]: Is this intentional? The peer host should be known at this point.

File: server/conn.go [hunk 4]
```diff
@@ -715,6 +763,34 @@ func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
...
+	} else if (cc.authPlugin != userplugin) || (cc.authPlugin != *authPlugin) {
+		authData, err := cc.authSwitchRequest(ctx, userplugin)
+		if err != nil {
+			return nil, err
+		}
+		*authPlugin = userplugin
+		return authData, nil
+	} else {
+		*authPlugin = userplugin
+	}
```
Comment (morgo) [inline server/conn.go:790]: The linter should warn that this else branch should be removed, since the previous if / else if both return.

File: server/conn.go (hunk 1 above)
Comment (dveeden) [reply server/conn.go:669]: If the client presents an authentication plugin that doesn't match the plugin used by the server `checkAuthPlugin` will do the `authSwitchRequest` so I don't think this code will be reached during normal operation. It may be reached if someone bypasses the `GRANT`/`REVOKE` etc and changes `mysql.user` directly.

File: server/conn.go [hunk 5]
```diff
@@ -693,6 +744,15 @@ func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
 	if err = cc.server.checkConnectionCount(); err != nil {
 		return err
 	}
+	return nil
+}
+
+func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
+	// Open a context unless this was done before.
+	if cc.ctx == nil {
+		cc.openSession()
```
Comment (tiancaiamao) [inline server/conn.go:753]: error is ignored?

File: session/session.go [hunk 6]
```diff
@@ -144,6 +144,7 @@ type Session interface {
 	Close()
 	Auth(user *auth.UserIdentity, auth []byte, salt []byte) bool
```
Comment (tiancaiamao) [inline session/session.go:146]: Please add some test code for this change.
I understand that unit test may not be a perfect match for this scenario, at least you can  `insert .. into mysql.user` to mock some data, and cover the auth utility?

File: server/conn.go [hunk 7]
```diff
@@ -693,6 +744,15 @@ func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
 	if err = cc.server.checkConnectionCount(); err != nil {
 		return err
 	}
+	return nil
+}
+
+func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
```
Comment (tiancaiamao) [inline server/conn.go:750]: If open session success, but do auth fails, will there be a potential resource leak?

File: server/conn.go [hunk 8]
```diff
@@ -715,6 +775,32 @@ func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
 	return nil
 }
 
+func (cc *clientConn) checkAuthPlugin(ctx context.Context, authPlugin *string) ([]byte, error) {
```
Comment (tiancaiamao) [inline server/conn.go:778]: So, there are:
1. the default auth plugin (we set in the initial handshake packet)
2. the user's auth plugin, which stores in mysql.user authentication related column
3. the auth plugin from the client response packet

Which one is which? I'm a bit confused.

Pass *string as both input and output of a function is an idiom in C.
Go support multiple return, you don't need to do that.

**Comment by dveeden** [comment]
I found an issue: For both `SET PASSWORD...` and `ALTER USER ... IDENTIFIED BY...` for users with `caching_sha2_password` operations fail as the password string contains non UTF-8. For `executeCreateUser` this was fixed by adding `set session tidb_skip_utf8_check=ON` but I wasn't able to set this variable for `executeSetPwd` or `executeAlterUser`

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/parser/pull/1236 is merged, you can update the parser

**Comment by tiancaiamao** [comment]
@dveeden  B.T.W, if you change the parser and the change is not merged yet, you can still test the tidb code:

```
go mod edit -replace github.com/pingcap/parser=github.com/your-repo/parser@your-branch
```

See https://github.com/pingcap/parser/blob/master/docs/update-parser-for-tidb.md

**Review by morgo — APPROVED** [review]

File: server/conn.go [hunk 9]
```diff
@@ -715,6 +785,35 @@ func (cc *clientConn) openSessionAndDoAuth(authData []byte) error {
...
+	// Open a context unless this was done before.
+	if cc.ctx == nil {
+		err := cc.openSession()
+		if err != nil {
+			return nil, err
+		}
+	}
+
+	userplugin, err := cc.ctx.AuthPluginForUser(&auth.UserIdentity{Username: cc.user, Hostname: cc.peerHost})
```
Comment (tiancaiamao) [inline server/conn.go:797]: This is far too complex and beyond my comprehension. Could you refactor the code a bit for readability?

Comment (tiancaiamao) [reply server/conn.go:797]:
```
// step1, there is a variable for the auth plugin from the respond;                                                                                                                                                
//        there is a variable for the user plugin from mysql.user table                                                                                                                                            
//        there is a variable for the default auth plugin                                                                                                                                                          
// we can assign a default value for them if they are empty                                                                                                                                                        
                                                                                                                                                                                                                   
userPlugin = AuthPluginForUser()                                                                                                                                                                                   
if userPlugin = "" {                                                                                                                                                                                               
    userPlugin = default                                                                                                                                                                                           
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
respPlugin = resp.AuthPlugin                                                                                                                                                                                       
if respPlugin == "" {                                                                                                                                                                                              
    respPlugin = default                                                                                                                                                                                           
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
// step2, what we really care is the user plugin should be the same with the response plugin, am I right?                                                                                                              
// They are not empty after step1                                                                                                                                                                                  
                                                                                                                                                                                                                   
if userPlugin != respPlugin {                                                                                                                                                                                      
    resp.Auth = authSwitchRequest(userPlugin)                                                                                                                                                                      
}

// step3, auth data is now resp.Auth, and auth plugin is userPlugin    
```

File: server/conn.go [hunk 10]
```diff
@@ -202,11 +204,11 @@ func (cc *clientConn) String() string {
 // other than mysql_native_password. The server is allowed to ask
 // the client to switch, so lets ask for mysql_native_password
 // https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::AuthSwitchRequest
-func (cc *clientConn) authSwitchRequest(ctx context.Context) ([]byte, error) {
-	enclen := 1 + len(mysql.AuthNativePassword) + 1 + len(cc.salt) + 1
+func (cc *clientConn) authSwitchRequest(ctx context.Context, plugin string) ([]byte, error) {
```
[the remark this answers is not in the document]
Comment (dveeden) [reply server/conn.go:209]: done

File: server/conn.go (hunk 9 above)
Comment (dveeden) [reply server/conn.go:800]: I've updated this, could you check it again?

File: session/session.go (hunk 6 above)
Comment (dveeden) [reply session/session.go:148]: I've added `TestAuthPluginForUser` for this.

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
```
[2021-06-22T01:52:47.527Z] ----------------------------------------------------------------------
[2021-06-22T01:52:47.527Z] FAIL: tidb_test.go:858: tidbTestSuite.TestClientWithCollation
[2021-06-22T01:52:47.527Z] 
[2021-06-22T01:52:47.527Z] tidb_test.go:860:
[2021-06-22T01:52:47.527Z]     ts.runTestClientWithCollation(c)
[2021-06-22T01:52:47.527Z] server_test.go:347:
[2021-06-22T01:52:47.527Z]     t.Assert(collation, Equals, "utf8mb4_general_ci")
[2021-06-22T01:52:47.527Z] ... obtained string = "utf8mb4_bin"
[2021-06-22T01:52:47.527Z] ... expected string = "utf8mb4_general_ci"
[2021-06-22T01:52:47.527Z] 

[2021-06-22T01:52:47.594Z] ----------------------------------------------------------------------
[2021-06-22T01:52:47.594Z] FAIL: tidb_test.go:392: tidbTestSuite.TestMultiStatements
[2021-06-22T01:52:47.594Z] 
[2021-06-22T01:52:47.594Z] tidb_test.go:395:
[2021-06-22T01:52:47.594Z]     ts.runTestMultiStatements(c)
[2021-06-22T01:52:47.594Z] server_test.go:205:
[2021-06-22T01:52:47.594Z]     dbt.Assert(err, IsNil, Commentf("Exec %s", query))
[2021-06-22T01:52:47.594Z] ... value *mysql.MySQLError = &mysql.MySQLError{Number:0x1fc2, Message:"client has multi-statement capability disabled. Run SET GLOBAL tidb_multi_statement_mode='ON' after you understand the security risk"} ("Error 8130: client has multi-statement capability disabled. Run SET GLOBAL tidb_multi_statement_mode='ON' after you understand the security risk")
[2021-06-22T01:52:47.594Z] ... Exec UPDATE test SET value = 3 WHERE id = 1; UPDATE test SET value = 4 WHERE id = 1; UPDATE test SET value = 5 WHERE id = 1;
```

CI is failing, would you like to take a look?  @dveeden 
To run a single test case, those commands would be helpful:

```
make failpoint-enable
cd server
go test -check.f TestMultiStatements
```

**Comment by dveeden** [comment]
> ```
> [2021-06-22T01:52:47.527Z] ----------------------------------------------------------------------
> [2021-06-22T01:52:47.527Z] FAIL: tidb_test.go:858: tidbTestSuite.TestClientWithCollation
> [2021-06-22T01:52:47.527Z] 
> [2021-06-22T01:52:47.527Z] tidb_test.go:860:
> [2021-06-22T01:52:47.527Z]     ts.runTestClientWithCollation(c)
> [2021-06-22T01:52:47.527Z] server_test.go:347:
> [2021-06-22T01:52:47.527Z]     t.Assert(collation, Equals, "utf8mb4_general_ci")
> [2021-06-22T01:52:47.527Z] ... obtained string = "utf8mb4_bin"
> [2021-06-22T01:52:47.527Z] ... expected string = "utf8mb4_general_ci"
> [2021-06-22T01:52:47.527Z] 
> 
> [2021-06-22T01:52:47.594Z] ----------------------------------------------------------------------
> [2021-06-22T01:52:47.594Z] FAIL: tidb_test.go:392: tidbTestSuite.TestMultiStatements
> [2021-06-22T01:52:47.594Z] 
> [2021-06-22T01:52:47.594Z] tidb_test.go:395:
> [2021-06-22T01:52:47.594Z]     ts.runTestMultiStatements(c)
> [2021-06-22T01:52:47.594Z] server_test.go:205:
> [2021-06-22T01:52:47.594Z]     dbt.Assert(err, IsNil, Commentf("Exec %s", query))
> [2021-06-22T01:52:47.594Z] ... value *mysql.MySQLError = &mysql.MySQLError{Number:0x1fc2, Message:"client has multi-statement capability disabled. Run SET GLOBAL tidb_multi_statement_mode='ON' after you understand the security risk"} ("Error 8130: client has multi-statement capability disabled. Run SET GLOBAL tidb_multi_statement_mode='ON' after you understand the security risk")
> [2021-06-22T01:52:47.594Z] ... Exec UPDATE test SET value = 3 WHERE id = 1; UPDATE test SET value = 4 WHERE id = 1; UPDATE test SET value = 5 WHERE id = 1;
> ```
> 
> CI is failing, would you like to take a look? @dveeden
> To run a single test case, those commands would be helpful:
> 
> ```
> make failpoint-enable
> cd server
> go test -check.f TestMultiStatements
> ```

In `openSession` there is this:
```go
cc.ctx, err = cc.server.driver.OpenCtx(cc.connectionID, cc.capability, cc.collation, cc.dbname, tlsStatePtr)
```

And as now the session is needed to get the value of `variable.DefaultAuthPlugin` to send the server greeting the session is opened before we have set `cc.collation` based on the client response. I've fixed this by closing the session/ctx again.

https://github.com/pingcap/tidb/pull/24991/files#diff-412615e1c1d4c6ae11a7885a11c879778bf401e0967c9c13c4b9dfd1f13ed29aR369-R375

File: server/conn.go [hunk 11]
```diff
@@ -348,9 +353,29 @@ func (cc *clientConn) writeInitialHandshake(ctx context.Context) error {
...
+	cc.authPlugin = defAuthPlugin
+	data = append(data, []byte(defAuthPlugin)...)
+
+	// Close the session to force this to be re-opened after we parse the response. This is needed
+	// to ensure we use the collation and client flags from the response for the session.
+	err = cc.ctx.Close()
+	if err != nil {
+		return err
+	}
+	cc.ctx = nil
```
Comment (tiancaiamao) [inline server/conn.go:375]: Just a hint: open a new session may need to load the global variables (maybe not true when they're cached), and do it once again could slow down the connection speed.

**Review by tiancaiamao — APPROVED** [review]

**Comment by tiancaiamao** [comment]
@morgo would you like to take another look? or I'll merge this one.

File: server/conn.go (hunk 11 above)
Comment (morgo) [reply server/conn.go:375]: I agree with your comment.

The cache is improved with sysvar cache, but it is still expensive. The current code will re-run validation on all of the sysvars. This can be improved though: in future we can cache the validated values in the sysvar cache, and when a session is initialized just copy the sysvar cache map to it.

The complicated case will be eliminating the need to call the 'init functions' (i.e. calling `sv.SetSession()` so that `s.VarXXX` is set.) I think we can remove a lot of `SetSession()` funcs by adding something like `sv.ToBool()`, `sv.ToUint64()`.

**Comment by morgo** [comment]
> @morgo would you like to take another look? or I'll merge this one.

It LGTM. There are some known issues with improving fast connection/disconnection rate, but these are existing.

We should suggest the QA team have scenario testing for it because it will affect connectors like php and perl. Issues like https://github.com/pingcap/tidb/issues/24326 could also be discovered quicker.

File: server/conn.go (hunk 11 above)
Comment (jackysp) [reply server/conn.go:375]: Indeed, creating a new session for handshake is relatively heavy, indirectly leading to the occurrence of https://github.com/pingcap/tidb/issues/44502.
