### PR TITLE
planner: disallow multi-updates on primary key (#20603)

### LINKED ISSUE #20594: MySQL doesn't allow mutliple updates on primary key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` mysql
drop table if exists t;
create table t (a int, b int, primary key (a, b));
insert into t (1, 2);
update t t1, t t2 set t1.a=t1.a+10, t2.b=t2.b+10;
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

In MySQL 8.0.19

``` mysql
mysql> update t t1, t t2 set t1.a=t1.a+10, t2.b=t2.b+10;
ERROR 1706 (HY000): Primary key/partition key update is not allowed since the table is updated both as 't1' and 't2'.
```

### 3. What did you see instead (Required)

``` mysql
mysql> update t t1, t t2 set t1.a=t1.a+10, t2.b=t2.b+10;
Query OK, 2 rows affected (0.00 sec)
Rows matched: 2  Changed: 2  Warnings: 0
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

``` mysql
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1407-ge30220099
Edition: Community
Git Commit Hash: e302200999045d81b19d08d5ec240d3438674abb
Git Branch: master
UTC Build Time: 2020-10-22 11:32:06
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #20603 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #20594  

Problem Summary:

MySQL doesn't allow multi-updates on primary key (i.e. updating primary key of the same table with different alias), but TiDB does.

### What is changed and how it works?

- Check for updates on primary keys and detect for multi-updates conflict.

### Related changes

- Need to cherry-pick to the release branch 3.0, 4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Disallow multi-updates on primary key

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -3559,13 +3559,52 @@ func checkUpdateList(ctx sessionctx.Context, tblID2table map[int64]table.Table,
...
 		for i, col := range tbl.WritableCols() {
 			if flags[i] && col.State != model.StatePublic {
 				return ErrUnknownColumn.GenWithStackByArgs(col.Name, clauseMsg[fieldList])
 			}
+			// Check for multi-updates on primary key,
+			// see https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html#error_er_multi_update_key_conflict
+			if !flags[i] {
+				continue
+			}
+			if col.IsPKHandleColumn(tbl.Meta()) || pkColumnsMap[content.TblID][col.ID] {
```
Comment (tiancaiamao) [inline planner/core/logical_plan_builder.go:3599]: Why constructing a temporary map `pkColumnsMap` to check whether `col` is primary key?
Could `col.Primary` work the same way as `pkColumnsMap[content.TblID][col.ID]` here?

Comment (dyzsr) [reply planner/core/logical_plan_builder.go:3599]: My mistake. Using `mysql.HasPriKeyFlag` is enough, and I think #20603 should also change to this. Do I have to create another PR for it?

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (tiancaiamao) [reply planner/core/logical_plan_builder.go]: Yes, of course.
Don't hesitate to improve the code quality, even tiny changes.

**Comment by tiancaiamao** [comment]
LGTM

**Review by tiancaiamao — APPROVED** [review]

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (dyzsr) [reply planner/core/logical_plan_builder.go]: Sure, I've put this change into https://github.com/pingcap/tidb/pull/20493. It may take longer time to review.

**Review by tiancaiamao — APPROVED** [review]
