### PR TITLE
planner: fix the fail when we compare multi fields in the subquery

### LINKED ISSUE #13551: Compare multi fields with subquery fail
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
CREATE TABLE t1(c1 int, c2 int);
CREATE TABLE t2(c1 int, c2 int);
INSERT INTO t1(`c1`, `c2`) VALUES(2, 4);
INSERT INTO t2(`c1`, `c2`) VALUES(2, 4);
SELECT * FROM t2 WHERE (SELECT c1, c2 FROM t2 LIMIT 1) = ANY (SELECT c1, c2 FROM t1);
```

2. What did you expect to see?

* MySQL 8.0

```
mysql> CREATE TABLE t1(c1 int, c2 int);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t2(c1 int, c2 int);
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO t1(`c1`, `c2`) VALUES(2, 4);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t2(`c1`, `c2`) VALUES(2, 4);
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t2 WHERE (SELECT c1, c2 FROM t2 LIMIT 1) = ANY (SELECT c1, c2 FROM t1);
+------+------+
| c1   | c2   |
+------+------+
|    2 |    4 |
+------+------+
1 row in set (0.00 sec)
```

3. What did you see instead?

* TiDB

```
mysql> CREATE TABLE t1(c1 int, c2 int);
Query OK, 0 rows affected (0.08 sec)

mysql> CREATE TABLE t2(c1 int, c2 int);
Query OK, 0 rows affected (0.09 sec)

mysql> INSERT INTO t1(`c1`, `c2`) VALUES(2, 4);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t2(`c1`, `c2`) VALUES(2, 4);
Query OK, 1 row affected (0.01 sec)

mysql> SELECT * FROM t2 WHERE (SELECT c1, c2 FROM t2 LIMIT 1) = ANY (SELECT c1, c2 FROM t1);
ERROR 1241 (21000): Operand should contain 1 column(s)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v4.0.0-alpha-882-gf73cd98cc
Git Commit Hash: f73cd98ccee3346ad820a8ba81ea1e38add677f8
Git Branch: master
UTC Build Time: 2019-11-18 04:38:40
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### LINKED ISSUE #21674: Wrong result when we compare field with zero value in subquery
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1(c1 int, c2 int);
CREATE TABLE t2(c1 int, c2 int);
INSERT INTO t1(`c1`, `c2`) VALUES(0, 0);
INSERT INTO t2(`c1`, `c2`) VALUES(0, 0);
SELECT * FROM t2 WHERE (SELECT c1 FROM t2 LIMIT 1) = ANY (SELECT c1 FROM t1);
```

### 2. What did you expect to see? (Required)
```
mysql> DROP TABLE IF EXISTS t1, t2;
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t1(c1 int, c2 int);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t2(c1 int, c2 int);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t1(`c1`, `c2`) VALUES(0, 0);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t2(`c1`, `c2`) VALUES(0, 0);
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t2 WHERE (SELECT c1 FROM t2 LIMIT 1) = ANY (SELECT c1 FROM t1);
+------+------+
| c1   | c2   |
+------+------+
|    0 |    0 |
+------+------+
1 row in set (0.01 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.20    |
+-----------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> DROP TABLE IF EXISTS t1, t2;
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE t1(c1 int, c2 int);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t2(c1 int, c2 int);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1(`c1`, `c2`) VALUES(0, 0);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t2(`c1`, `c2`) VALUES(0, 0);
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t2 WHERE (SELECT c1 FROM t2 LIMIT 1) = ANY (SELECT c1 FROM t1);
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)
Latest master `39d8fcc71b6d83a96defcbeafaf2c076583a8328`

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close #13551  close #21674 

Problem Summary:
When we use `(SELECT c1, c2 FROM t2 LIMIT 1) = ANY (SELECT c1, c2 FROM t1)` in the `where` statement, the `expressionRewrite.ctxStack` will store the result value of `SELECT c1, c2 FROM t2 LIMIT 1`.  So in issue#21674, when the value of c1 is zero, the plan will be convert to `tableDual`.

### What is changed and how it works?
So, we should set `expressionRewrite.asScalar = true` like [`handleInSubquery`](https://github.com/pingcap/tidb/blob/master/planner/core/expression_rewriter.go#L822-L824) function. It will use the parent expression's last column from the schema to represents whether the condition is matched(https://github.com/pingcap/tidb/blob/master/planner/core/expression_rewriter.go#L558-L561).

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix the fail when we compare multi fields in the subquery

### CODE REVIEW

**Comment by Reminiscent** [comment]
label sig/planner, type/bug-fix

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -538,6 +539,7 @@ func (er *expressionRewriter) handleCompareSubquery(ctx context.Context, v *ast.
 		} else if v.Op == opcode.NE {
 			if v.All {
 				// `a != all(subq)` will be rewriten as `a not in (subq)`.
+				er.asScalar = true
```
Comment (XuHuaiyu) [inline planner/core/expression_rewriter.go:542]: The test case does not cover this?

**Comment by Reminiscent** [comment]
@XuHuaiyu Update.PTAL!

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
