### PR TITLE
*: refactor encoding and uniform usages

### LINKED ISSUE #29685: builtin func char() has different result between MySQL when value is illegal UTF8 character
## Bug Report

builtin func char() has different result between MySQL when value is illegal UTF8 character

### 1. Minimal reproduce step (Required)
```
select char(123456 using utf8);
show warnings;
```
### 2. What did you expect to see? (Required)
```
mysql> select char(123456 using utf8);
+-------------------------+
| char(123456 using utf8) |
+-------------------------+
| NULL                    |
+-------------------------+
1 row in set, 2 warnings (0.00 sec)
mysql> show warnings;
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                     |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 3719 | 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous. |
| Warning | 1300 | Invalid utf8mb3 character string: 'E240'                                                                                                                                    |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)
```
mysql> select char(123456 using utf8);
+-------------------------+
| char(123456 using utf8) |
+-------------------------+
| �@                      |
+-------------------------+
1 row in set (0.01 sec)
mysql> show warnings;
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
mysql> SELECT tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.2.0-alpha-2186-g2bdebedfc
Edition: Community
Git Commit Hash: 2bdebedfc042e340c7826d0ac96f635f3949a8b3
Git Branch: master
UTC Build Time: 2021-11-11 05:47:41
GoVersion: go1.16.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #30362: Tidb uhhex() results are conflicting with mysql( 5.7 and 8.0) when  collation_database =gbk_chinese_ci
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1;
SET NAMES utf8;
SET collation_database =gbk_chinese_ci;
CREATE TABLE t1 (code  VARCHAR(4),a VARCHAR(4));
INSERT INTO `t1` (code) VALUES ('C29F'),('CC91'),('D697'),('8020'),('CCA0'),('D2B1'),('DFAB'),('DCB0');
UPDATE IGNORE t1 SET a=unhex(code) ORDER BY code;
SELECT COUNT(*) FROM t1 WHERE a <> '';
```

### 2. What did you expect to see? (Required)
```sql
--mysql 5.7
mysql> SELECT COUNT(*) FROM t1 WHERE a <> '';
+----------+
| COUNT(*) |
+----------+
|        8 |
+----------+
1 row in set (0.00 sec)
--mysql 8.0
mysql> SELECT COUNT(*) FROM t1 WHERE a <> '';
+----------+
| COUNT(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> SELECT COUNT(*) FROM t1 WHERE a <> '';
+----------+
| COUNT(*) |
+----------+
|        7 |
+----------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-11-29 16:57:51
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### LINKED ISSUE #30429: It raises the error of  Invalid latin1 character string
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a varchar(20))CHARSET=binary;
create table t2(a varchar(20) )CHARSET=latin1;
insert into t values('😉');
insert into t2 values('😉');
select count(*) from t join t2 on t.a=t2.a; 
```
### 2. What did you expect to see? (Required)
error when insert or successful when select
### 3. What did you see instead (Required)
ERROR 1300 (HY000): Invalid latin1 character string: 'F09F9889'
### 4. What is your TiDB version? (Required)

Release Version: v5.4.0-alpha-278-ga04601477
Edition: Community
Git Commit Hash: a04601477600b6804d7a4a2bd31a923bed7817c7
Git Branch: master
UTC Build Time: 2021-12-01 03:36:18
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: 

close #30429
close #29685
close #30362

Problem Summary:

### What is changed and how it works?

Encoding:
- `Encoding` is changed to an interface. Implementations includes `EncodingUTF8`, `EncodingASCII`, `EncodingLatin1`, `EncodingBin` and `EncodingGBK`.
- `StringValidator` is merged to `Encoding`. `Encoding.Validate` is the new interface.
- `NewEncoding()` is renamed to `FindEncoding()` since there is no memory allocation anymore.
- One more value `nSrc` is returned from `Encode`/`Decode` to indicate how many source bytes are consumed. This is useful in truncation.

Binary Literal Handling:
- The built-in functions are classified into 3 kinds of `funcProp`(function property):
  - `funcPropNone`: No property. The arguments are not specially handled.
  - `funcPropBinAware`: The function depends on the binary representation of its string arguments. It will wrap each argument with `to_binary()`.
  - `funcPropAuto`: There are mulitple string arguments. Implicit cast can happen. It will wrap `to_binary()` or `from_binary()` according to charsets.
- All the string-related functions are considered.

Built-in functions:
- Invalid string characters are handled properly.
- builtinCharSig(`char()`): it only returns null for invalid strings when the SQL mode is strict.
- builtinConvertSig(`convert()`): it reuses the charset.Encoding.
- builtinBitLengthSig(`bit_length()`): the special encoding is implemented through warping `to_binary()`.
- builtinOrdSig(`ord()`): it fallbacks to using the first byte instead of returning encoding error for invalid strings.
- Encoding field is removed from `lowerFunctionClass` and `upperFunctionClass` without performance loss.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Defined2014** [comment]
I think this PR cloud close https://github.com/pingcap/tidb/issues/29685. Maybe we could add those tests in test codes.

**Comment by bb7133** [comment]
Is this PR WIP?

Also, please have a brief introduction to the refactors.

**Comment by Defined2014** [comment]
> Is this PR WIP?
> 
> Also, please have a brief introduction to the refactors.

Add one more linked issue https://github.com/pingcap/tidb/issues/30362#issuecomment-985361781.

This PR also will close #30362

**Comment by tangenta** [comment]
> Is this PR WIP?
> 
> Also, please have a brief introduction to the refactors.

@bb7133 Yes. It is WIP because I am still struggling with the failed tests. I will add the PR description as soon as possible.

File: expression/builtin_string_test.go [hunk 1]
```diff
@@ -1429,15 +1430,15 @@ func TestBitLength(t *testing.T) {
 }
 
 func TestChar(t *testing.T) {
-	t.Parallel()
```
Comment (Defined2014) [inline expression/builtin_string_test.go:1432]: We have `expression/builtin_string_serial_test.go`, so not sure where this test case should be after delete `t.Parallel()` :(

File: parser/charset/encoding_ascii.go [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+
+// Peek implements Encoding interface.
+func (e *EncodingASCII) Peek(src []byte) []byte {
+	if len(src) == 0 {
+		return src
+	}
+	return src[:1]
+}
+
+func (e *EncodingASCII) Validate(dest, src []byte) (result []byte, nSrc int, ok bool) {
```
Comment (Defined2014) [inline parser/charset/encoding_ascii.go:56]: A bit weird in func name `Validate`.
At first sight, I thought it was just for testing whether `[]byte` is legal or not. But it also provides transfor ability. Maybe split it to `validate` and `transform` is better?

Comment (tangenta) [reply parser/charset/encoding_ascii.go:56]: How about changing its name to `EncodeAndDecode`?

Comment (Defined2014) [reply parser/charset/encoding_ascii.go:56]: `TryReplaceInvalidChars` is much easier to understand.

Comment (tangenta) [reply parser/charset/encoding_ascii.go]: Updated. I add the function `ReplaceIllegal` to the interface. Now `Validate` only tests whether `[]byte` is legal.

File: table/column.go [hunk 3]
```diff
@@ -314,48 +314,59 @@ func CastValue(ctx sessionctx.Context, val types.Datum, col *model.ColumnInfo, r
...
+	}
+	// from_binary: convert the binary to utf8.
+	if origin.Collation() == charset.CharsetBin {
+		src := casted.GetBytes()
+		encBytes, nSrc, err := enc.Decode(nil, src)
+		if err != nil {
+			var err1 error
+			// Remove the trailing invalid characters.
+			encBytes, _, err1 = enc.Decode(encBytes, src[:nSrc])
+			skipErr(err1)
```
Comment (Defined2014) [inline table/column.go:351]: I think we don't need `skipErr` function.

How about the implementation below?
`encBytes, _, _ = enc.Decode(encBytes, src[:nSrc])`

Comment (tangenta) [reply table/column.go:351]: I remember the linter complains that "the error is not handled". Maybe we can improve the interface...

Comment (Defined2014) [reply table/column.go:351]: I tyied it on my computer with `make lint` and `make check-static`. But no errors were found

File: parser/charset/encoding_base.go [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+
+var errInvalidCharacterString = terror.ClassParser.NewStd(mysql.ErrInvalidCharacterString)
+
+// EncodingBase defines some generic functions.
+type EncodingBase struct {
+	enc encoding.Encoding
+}
+
+// Validate checks whether bytes are valid in current charset.
+func (b EncodingBase) Validate(src []byte) (nSrc int, ok bool) {
```
Comment (Defined2014) [inline parser/charset/encoding_base.go:33]: A question here, not sure is this a good way.
Why we need `EncodingBase` type here? It has some overlap with `EncodingUTF8`. Maybe we can move the UTF8 implementation here?

File: expression/builtin_convert_charset.go [hunk 5]
```diff
@@ -256,26 +256,97 @@ func BuildFromBinaryFunction(ctx sessionctx.Context, expr Expression, tp *types.
 	return FoldConstant(res)
 }
 
+type funcProp int8
+
+const (
+	funcPropNone funcProp = iota
```
Comment (xiongjiwei) [inline expression/builtin_convert_charset.go:262]: if the `funcPropNone` means do nothing, why not remove it.

File: expression/builtin_convert_charset.go [hunk 6]
```diff
@@ -256,26 +256,97 @@ func BuildFromBinaryFunction(ctx sessionctx.Context, expr Expression, tp *types.
...
+		return BuildToBinaryFunction(ctx, expr)
+	case funcPropAuto:
+		if argChs != charset.CharsetBin && dstChs == charset.CharsetBin {
+			if isLegacyCharset(argChs) {
+				return expr
+			}
 			return BuildToBinaryFunction(ctx, expr)
-		} else if ec.Charset != charset.CharsetBin && expr.GetType().Charset == charset.CharsetBin {
+		} else if argChs == charset.CharsetBin && dstChs != charset.CharsetBin {
+			if ctx.GetSessionVars().SkipUTF8Check && isLegacyCharset(dstChs) {
```
Comment (xiongjiwei) [inline expression/builtin_convert_charset.go:335]: `SkipUTF8Check` is only used when insert data, why we should consider this variable?

Comment (xiongjiwei) [reply expression/builtin_convert_charset.go:335]: LegacyCharset should also wrap with `frombinary` for example 
```sql
mysql> select concat(0x91, 'a' collate utf8mb4_bin);
ERROR 3854 (HY000): Cannot convert string '\x91' from binary to utf8mb4
```

File: expression/builtin_string.go [hunk 7]
```diff
@@ -2327,12 +2319,7 @@ func (b *builtinBitLengthSig) evalInt(row chunk.Row) (int64, bool, error) {
 	if isNull || err != nil {
 		return 0, isNull, err
 	}
-	argTp := b.args[0].GetType()
-	dBytes, err := charset.NewEncoding(argTp.Charset).Encode(nil, hack.Slice(val))
-	if err != nil {
-		return 0, isNull, err
-	}
-	return int64(len(dBytes) * 8), false, nil
+	return int64(len(val) * 8), false, nil
```
Comment (xiongjiwei) [inline expression/builtin_string.go:2322]: Is it does not affect by the charset?

File: expression/builtin_convert_charset.go (hunk 5 above)
Comment (tangenta) [reply expression/builtin_convert_charset.go:262]: These functions are listed there to show that they have been considered.

File: expression/builtin_string.go (hunk 7 above)
Comment (tangenta) [reply expression/builtin_string.go:2322]: It has been wrapped by `to_binary()`. The `val` here is the correct charset.

**Review by Defined2014 — APPROVED** [review]

File: planner/core/integration_test.go [hunk 8]
```diff
@@ -4987,7 +4987,7 @@ func (s *testIntegrationSuite) TestIssue30094(c *C) {
 	))
 	tk.MustQuery(`explain format = 'brief' select * from t30094 where  concat(a,'1') = _binary 0xe59388e59388e59388 collate binary and concat(a,'1') = _binary 0xe598bfe598bfe598bf collate binary;`).Check(testkit.Rows(
 		"TableReader 8000.00 root  data:Selection",
-		"└─Selection 8000.00 cop[tikv]  eq(to_binary(concat(test.t30094.a, \"1\")), \"0xe59388e59388e59388\"), eq(to_binary(concat(test.t30094.a, \"1\")), \"0xe598bfe598bfe598bf\")",
+		"└─Selection 8000.00 cop[tikv]  eq(concat(test.t30094.a, \"1\"), \"0xe59388e59388e59388\"), eq(concat(test.t30094.a, \"1\"), \"0xe598bfe598bfe598bf\")",
```
[the remark this answers is not in the document]
Comment (tangenta) [reply planner/core/integration_test.go:4990]: Because utf8/latin1/binary/ascii charsets are not wrapped with to_binary.

**Review by zimulala — COMMENTED** [review]
How about the case as follows(I tested it locally):
```
tidb> set names gbk;
Query OK, 0 rows affected (0.00 sec)
tidb>  create table t(a varchar(2550))CHARACTER SET utf8mb4;
Query OK, 0 rows affected (0.02 sec)
tidb> insert into t values("哈");
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 25 near ""鍝?)"
tidb> insert into t values("一");
Query OK, 1 row affected (0.01 sec)
```

File: server/util.go [hunk 9]
```diff
@@ -341,24 +343,30 @@ func (d *resultEncoder) columnTypeInfoCharsetID(info *ColumnInfo) uint16 {
...
+// Note that the result should be consumed immediately.
 func (d *resultEncoder) encodeMeta(src []byte) []byte {
 	return d.encodeWith(src, d.encoding)
 }
 
+// encodeData encodes bytes for row data.
+// Note that the result should be consumed immediately.
 func (d *resultEncoder) encodeData(src []byte) []byte {
-	if d.isNull || d.isBinary {
+	if d.isNull || d.isBinary || d.dataIsBinary {
```
Comment (Defined2014) [inline server/util.go:355]: This will cause some unexpect problems 😭, we should delete it. Like https://github.com/pingcap/tidb/issues/30690

**Review by Defined2014 — CHANGES_REQUESTED** [review]

**Comment by tangenta** [comment]
> How about the case as follows(I tested it locally):
> 
> ```
> tidb> set names gbk;
> Query OK, 0 rows affected (0.00 sec)
> tidb>  create table t(a varchar(2550))CHARACTER SET utf8mb4;
> Query OK, 0 rows affected (0.02 sec)
> tidb> insert into t values("哈");
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 25 near ""鍝?)"
> tidb> insert into t values("一");
> Query OK, 1 row affected (0.01 sec)
> ```

@zimulala OK. We can't transform the whole SQL because the quote(`'`) is incorrectly decoded. We need another PR to fix this problem in the parser.

**Comment by xiongjiwei** [comment]
> How about the case as follows(I tested it locally):
> 
> ```
> tidb> set names gbk;
> Query OK, 0 rows affected (0.00 sec)
> tidb>  create table t(a varchar(2550))CHARACTER SET utf8mb4;
> Query OK, 0 rows affected (0.02 sec)
> tidb> insert into t values("哈");
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 25 near ""鍝?)"
> tidb> insert into t values("一");
> Query OK, 1 row affected (0.01 sec)
> ```

we already have the issue

File: server/util.go (hunk 9 above)
Comment (tangenta) [reply server/util.go:355]: I find that the @@character_set_client is not considered when the column is binary(`blob`) type.

MySQL:
```sql
drop table if exists t;
create table t(a blob(100));
set character_set_connection = 'gbk';
set character_set_client = 'gbk';
set character_set_results = 'gbk';
insert into t values ("你好");
select hex(a) from t;
```
```
+--------------+
| hex(a)       |
+--------------+
| E4BDA0E5A5BD |
+--------------+
```

Comment (Defined2014) [reply server/util.go:355]: Try this:
```
drop table if exists t;
create table t(a blob(100));
set character_set_client = 'gbk';
insert into t values ("你好");
select hex(a) from t;
```

MySQL will ignore the transform when `connection` and `client` are `gbk` which not same as TiDB does.

File: parser/charset/encoding_ascii.go [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+	}
+	return e.encodingBase.Transform(dest, src, op)
+}
+
+func (e *encodingASCII) Foreach(src []byte, op Op, fn func(from, to []byte, ok bool) bool) {
+	for i, w := 0, 0; i < len(src); i += w {
+		w = 1
+		ok := true
+		if src[i] > go_unicode.MaxASCII {
+			w = len(EncodingUTF8Impl.Peek(src[i:]))
```
Comment (xiongjiwei) [inline parser/charset/encoding_ascii.go:59]: why `EncodingUTF8Impl.Peek`?

File: expression/collation.go [hunk 11]
```diff
@@ -311,7 +311,11 @@ func safeConvert(ctx sessionctx.Context, ec *ExprCollation, args ...Expression)
 			if err != nil {
 				return false
 			}
-			if !isNull && !isValidString(str, ec.Charset) {
+			if isNull {
+				continue
+			}
+			enc := charset.FindEncoding(ec.Charset)
```
Comment (xiongjiwei) [inline expression/collation.go:317]: can be moved out of the loop

File: parser/charset/encoding_gbk.go [hunk 12]
```diff
@@ -0,0 +1,88 @@
...
+
+// Name implements Encoding interface.
+func (e *encodingGBK) Name() string {
+	return CharsetGBK
+}
+
+// Peek implements Encoding interface.
+func (e *encodingGBK) Peek(src []byte) []byte {
+	charLen := 2
+	if len(src) == 0 || src[0] < 0x80 {
```
Comment (xiongjiwei) [inline parser/charset/encoding_gbk.go:43]: seems 0x80 in golang lib is also a single byte

File: parser/charset/encoding_table.go [hunk 13]
```diff
@@ -14,40 +14,27 @@
...
-
-	"github.com/cznic/mathutil"
 	"golang.org/x/text/encoding"
 	"golang.org/x/text/encoding/charmap"
 	"golang.org/x/text/encoding/japanese"
 	"golang.org/x/text/encoding/korean"
 	"golang.org/x/text/encoding/simplifiedchinese"
 	"golang.org/x/text/encoding/traditionalchinese"
 	"golang.org/x/text/encoding/unicode"
+	"strings"
```
Comment (xiongjiwei) [inline parser/charset/encoding_table.go:24]: fmt

File: parser/charset/encoding_utf8.go [hunk 14]
```diff
@@ -0,0 +1,109 @@
...
+
+// Name implements Encoding interface.
+func (e *encodingUTF8) Name() string {
+	return CharsetUTF8MB4
+}
+
+// Peek implements Encoding interface.
+func (e *encodingUTF8) Peek(src []byte) []byte {
+	nextLen := 4
+	if len(src) == 0 || src[0] < 0x80 {
```
Comment (xiongjiwei) [inline parser/charset/encoding_utf8.go:52]: if `len(src) == 0` it will panic at L62

File: parser/charset/encoding_ascii.go (hunk 10 above)
Comment (tangenta) [reply parser/charset/encoding_ascii.go:64]: Because I am trying to make it compatible with MySQL:

```sql
set @@sql_mode = '';
drop table if exists t;
create table t (a char(10) charset ascii);
insert into t values ('😊');
select * from t;
```

```
mysql> select * from t;
+------+
| a    |
+------+
| ?    |
+------+
1 row in set (0.00 sec)
```

Note there is only one `?`.

File: parser/charset/encoding_gbk.go (hunk 12 above)
Comment (tangenta) [reply parser/charset/encoding_gbk.go:48]: Then it will not be compatible with MySQL in some cases.

File: parser/charset/encoding_ascii.go (hunk 10 above)
Comment (xiongjiwei) [reply parser/charset/encoding_ascii.go:64]: if set `character_set_client=ascii`
```sql
mysql> insert into t values ('😊');
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> select * from t;
+------+
| a    |
+------+
| ???? |
+------+
1 row in set (0.00 sec)
```

File: parser/charset/encoding_gbk.go (hunk 12 above)
Comment (Defined2014) [reply parser/charset/encoding_gbk.go:48]: Same question here. Maybe we should change it to 0x81.

Comment (xiongjiwei) [reply parser/charset/encoding_gbk.go:48]: just keep it as original, this pr is too big.😢

Comment (tangenta) [reply parser/charset/encoding_gbk.go:48]: @Defined2014 The difference can be more huge than we expected:

If we change it to 0x81, `一二三` is decoded to `涓€浜屼笁` instead of `涓?簩涓?`. The latter is compatible with MySQL.

https://github.com/pingcap/tidb/blob/b4df7ca4dcc4a851a1a04d4348dee2b153618a7b/parser/charset/encoding_test.go#L45-L58

File: server/util.go (hunk 9 above)
Comment (Defined2014) [reply server/util.go:381]: Found you update your PR to solve blob problem, but it's not only for `blob`, try this:
```mysql
create table t (b blob, d json);
insert into t values ('你好', '{"测试": "你好"}');
select * from t;
```

So my question is why we need `dataIsBinary` here?

Comment (tangenta) [reply server/util.go:381]: Because the default value for `@@character_set_client` is `utf8mb4`. Note that the validation for utf8 encoding has been added, we need to identify which column is binary data and use `EncodingBinary` to skip this validation.

File: expression/integration_test.go [hunk 15]
```diff
@@ -813,6 +812,27 @@ func TestStringBuiltin(t *testing.T) {
 		"-38.04620119 38.04620115 -38.04620119,38.04620115"))
 }
 
+func TestInvalidStrings(t *testing.T) {
+	t.Parallel()
```
Comment (xiongjiwei) [inline expression/integration_test.go:816]: no parallel

File: server/util.go (hunk 9 above)
Comment (Defined2014) [reply server/util.go:381]: This PR is too big, we can fix it in the next PR.
Please reopen the issue #30690 after this PR merged. @tangenta

**Review by xiongjiwei — APPROVED** [review]

**Review by Defined2014 — APPROVED** [review]
