### PR TITLE
statistics: dump FMSketch to KV only for partition table with dynamic prune mode

### LINKED ISSUE #24401: Write FM Sketch data to KV even if the table isn't partition table or in static partition prune mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
create table t(a int, index(a));
insert into t values (1), (2), (3);
analyze table t;
select * from mysql.stats_fm_sketch;
```

### 2. What did you expect to see? (Required)

Empty set.

### 3. What did you see instead (Required)

```
+----------+----------+---------+------------------------------------+
| table_id | is_index | hist_id | value                              |
+----------+----------+---------+------------------------------------+
|       53 |        0 |       1 | �񎇹Ȫ�!������՚����������                         |
|       53 |        1 |       1 | ��������"눭�����O�ֻ�����▒                        |
+----------+----------+---------+------------------------------------+
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2751-ga1d4d9d02
Edition: Community
Git Commit Hash: a1d4d9d02843c50c1c8c67f58597ca61b77a2bac
Git Branch: HEAD
UTC Build Time: 2021-04-30 10:04:16
GoVersion: go1.16.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve?

Issue Number: close #24401 

Problem Summary:

### What is changed and how it works?

What's Changed:

We only dump FMSketch to KV for partition table with dynamic prune mode.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- statistics: dump FMSketch to KV only for partition table with dynamic prune mode

### CODE REVIEW

File: statistics/handle/handle.go [hunk 1]
```diff
@@ -952,7 +952,7 @@ func (h *Handle) extendedStatsFromStorage(reader *statsReader, table *statistics
 }
 
 // SaveStatsToStorage saves the stats to storage.
-func (h *Handle) SaveStatsToStorage(tableID int64, count int64, isIndex int, hg *statistics.Histogram, cms *statistics.CMSketch, topN *statistics.TopN, fms *statistics.FMSketch, statsVersion int, isAnalyzed int64) (err error) {
+func (h *Handle) SaveStatsToStorage(tableID int64, count int64, isIndex int, hg *statistics.Histogram, cms *statistics.CMSketch, topN *statistics.TopN, fms *statistics.FMSketch, statsVersion int, isAnalyzed int64, isPartition bool, dynamicPrune bool) (err error) {
```
Comment (qw4990) [inline statistics/handle/handle.go:955]: How about combining these two variables into one `needGlobalStats` = `dynamicPrune && isPartition`?

Comment (qw4990) [reply statistics/handle/handle.go:955]: Ignore this, using two variables is OK.

File: statistics/handle/handle_test.go [hunk 2]
```diff
@@ -2375,33 +2375,33 @@ func (s *testStatsSuite) TestIndexFMSketch(c *C) {
 		tk.MustExec("analyze table t")
 		rs := tk.MustQuery(fmt.Sprintf("select value from mysql.stats_fm_sketch")).Rows()
 		c.Assert(len(rs), Equals, rows)
+		totNDV := int64(0)
```
Comment (qw4990) [inline statistics/handle/handle_test.go:2378]: It seems `totNDV` is not used.

File: statistics/handle/handle_test.go [hunk 3]
```diff
@@ -2375,33 +2375,33 @@ func (s *testStatsSuite) TestIndexFMSketch(c *C) {
...
 	}
 
 	tk.MustExec("set @@tidb_enable_clustered_index=OFF")
-	tk.MustExec("create table t(a int, key(a))")
+	tk.MustExec("create table t(a int, key(a)) partition by hash(a) partitions 3")
 	tk.MustExec("insert into t values (1), (2), (2), (3)")
-	checkNDV(2, 3)
-	tk.MustExec("insert into t values (4), (5)")
-	checkNDV(2, 5)
+	checkNDV(6, 1)
```
Comment (qw4990) [inline statistics/handle/handle_test.go:2390]: Should it be (6, 3) since there are 3 distinct values 1/2/3?

File: statistics/handle/handle.go (hunk 1 above)
Comment (time-and-fate) [reply statistics/handle/handle.go:955]: Why? :rofl:  The only usage is the `isPartition && dynamicPrune`

**Comment by time-and-fate** [comment]
Seems `TestDuplicateFMSketch` and `TestDuplicateFMSketch` failed because we didn't enable dynamic pruning in them.

File: statistics/handle/handle_test.go (hunk 3 above)
Comment (time-and-fate) [reply statistics/handle/handle_test.go:2390]: From the `checkNDV()`, this should mean there are 6 fm sketch and 1 distinct value for each fm sketch.

File: statistics/handle/handle.go (hunk 1 above)
Comment (rebelice) [reply statistics/handle/handle.go]: updated

File: statistics/handle/handle_test.go [hunk 4]
```diff
@@ -2802,3 +2802,33 @@ func (s *testSerialStatsSuite) TestIssues24349(c *C) {
...
+	// normal table with dynamic prune mode
+	testKit.MustExec("set @@tidb_partition_prune_mode='dynamic'")
+	defer testKit.MustExec("set @@tidb_partition_prune_mode='static'")
+	testKit.MustExec("analyze table t")
+	testKit.MustQuery("select * from mysql.stats_fm_sketch").Check(testkit.Rows())
+
+	// partition table with dynamic prune mode
+	testKit.MustExec("analyze table tp")
+	rows := testKit.MustQuery("select * from mysql.stats_fm_sketch").Rows()
+	c.Assert(len(rows), Greater, 0)
```
[the remark this answers is not in the document]
Comment (rebelice) [reply statistics/handle/handle_test.go]: updated

**Comment by qw4990** [comment]
@time-and-fate PTAL

**Review by time-and-fate — APPROVED** [review]
/lgtm
