### PR TITLE
types: fix datetime lower part overflow check

### LINKED ISSUE #11329: DATETIME's behaviour is different from mysql.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
select DATE_ADD('1000-01-01 00:00:00',INTERVAL -2 HOUR);
select DATE_ADD('1000-01-01 00:00:00',INTERVAL -200 HOUR);
select DATE_ADD('0001-01-01 00:00:00',INTERVAL -2 HOUR);
select DATE_ADD('0001-01-01 00:00:00',INTERVAL -25 HOUR);
select DATE_ADD('0001-01-01 00:00:00',INTERVAL -8784 HOUR);
select DATE_ADD('0001-01-01 00:00:00',INTERVAL -8785 HOUR);
```

2. What did you expect to see?

```
mysql> select DATE_ADD('1000-01-01 00:00:00',INTERVAL -2 HOUR);
+--------------------------------------------------+
| DATE_ADD('1000-01-01 00:00:00',INTERVAL -2 HOUR) |
+--------------------------------------------------+
| 0999-12-31 22:00:00                              |
+--------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('1000-01-01 00:00:00',INTERVAL -200 HOUR);
+----------------------------------------------------+
| DATE_ADD('1000-01-01 00:00:00',INTERVAL -200 HOUR) |
+----------------------------------------------------+
| 0999-12-23 16:00:00                                |
+----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -2 HOUR);
+--------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -2 HOUR) |
+--------------------------------------------------+
| 0000-00-00 22:00:00                              |
+--------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -25 HOUR);
+---------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -25 HOUR) |
+---------------------------------------------------+
| 0000-00-00 23:00:00                               |
+---------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -8784 HOUR);
+-----------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -8784 HOUR) |
+-----------------------------------------------------+
| 0000-00-00 00:00:00                                 |
+-----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -8785 HOUR);
+-----------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -8785 HOUR) |
+-----------------------------------------------------+
| NULL                                                |
+-----------------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

3. What did you see instead?

```
mysql> select DATE_ADD('1000-01-01 00:00:00',INTERVAL -2 HOUR);
+--------------------------------------------------+
| DATE_ADD('1000-01-01 00:00:00',INTERVAL -2 HOUR) |
+--------------------------------------------------+
| NULL                                             |
+--------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('1000-01-01 00:00:00',INTERVAL -200 HOUR);
+----------------------------------------------------+
| DATE_ADD('1000-01-01 00:00:00',INTERVAL -200 HOUR) |
+----------------------------------------------------+
| NULL                                               |
+----------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -2 HOUR);
+--------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -2 HOUR) |
+--------------------------------------------------+
| NULL                                             |
+--------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -25 HOUR);
+---------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -25 HOUR) |
+---------------------------------------------------+
| NULL                                              |
+---------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -8784 HOUR);
+-----------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -8784 HOUR) |
+-----------------------------------------------------+
| NULL                                                |
+-----------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('0001-01-01 00:00:00',INTERVAL -8785 HOUR);
+-----------------------------------------------------+
| DATE_ADD('0001-01-01 00:00:00',INTERVAL -8785 HOUR) |
+-----------------------------------------------------+
| NULL                                                |
+-----------------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
| Release Version: v3.0.0-rc.1-356-g5aef053c1
Git Commit Hash: 5aef053c163524aa167e6bb4ddabd0671a75e712
Git Branch: master
UTC Build Time: 2019-07-19 01:42:00
GoVersion: go version go1.12.6 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
```

### LINKED ISSUE #11645: Result of DATE_ADD function is different from mysql.(string INTERVAL)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY);
select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR);
```

2. What did you expect to see?

```
mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND);
+--------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND) |
+--------------------------------------------------------+
| 2007-03-28 22:08:25.800000                             |
+--------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY);
+-----------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY) |
+-----------------------------------------------------+
| 2007-03-26 22:08:28                                 |
+-----------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR) |
+------------------------------------------------------+
| 2007-03-28 20:08:28                                  |
+------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:26                                     |
+---------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY) |
+------------------------------------------------------+
| 2007-03-26 22:08:28                                  |
+------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR);
+-------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR) |
+-------------------------------------------------------+
| 2007-03-28 20:08:28                                   |
+-------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

3. What did you see instead?
```
mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND);
+--------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" SECOND) |
+--------------------------------------------------------+
| 2007-03-28 22:08:26.200000                             |
+--------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY);
+-----------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" DAY) |
+-----------------------------------------------------+
| 2007-03-30 22:08:28                                 |
+-----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.2" HOUR) |
+------------------------------------------------------+
| 2007-03-29 00:08:28                                  |
+------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND);
+---------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" SECOND) |
+---------------------------------------------------------+
| 2007-03-28 22:08:25.980000                              |
+---------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY);
+------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" DAY) |
+------------------------------------------------------+
| 2007-03-30 22:08:28                                  |
+------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR);
+-------------------------------------------------------+
| DATE_ADD('2007-03-28 22:08:28',INTERVAL "-2.-2" HOUR) |
+-------------------------------------------------------+
| 2007-03-29 00:08:28                                   |
+-------------------------------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
| Release Version: v3.0.0-rc.1-350-gdb4546028
Git Commit Hash: db454602801fea40b098fb5942576c3cd89dfebc
Git Branch: master
UTC Build Time: 2019-07-18 10:52:29
GoVersion: go version go1.12.6 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+----------------------------------
```

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @wshwsh12

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve?

Issue Number: close #11329  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

1. set  `types.MinDateTime` to `0001-01-01 00:00:00`

    https://github.com/pingcap/tidb/blob/2836011470f1dbc2e0f1352ae3eb9ed28bb35dba/types/time.go#L135

    ref to golang's `time` struct minimum value [time.IsZero()](https://golang.org/pkg/time/#Time.IsZero)

    > IsZero reports whether t represents the zero time instant, January 1, year 1, 00:00:00 UTC.

2. rewrite the `Date` part if `time.Date()` overflowed, such as:

    ```go
    package main

    import (
        "fmt"
        "time"
    )

    func main() {
        t := time.Date(1, 0, 0, 22, 0, 0, 0, time.UTC)
        fmt.Printf("Go launched at %s and year is %d\n", t, t.Year())
    }    
    ```

    output as:
    `Go launched at 0000-11-30 22:00:00 +0000 UTC and year is 0`

     In this scenario, we return the `types.Time` directly

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- Fix the different result of DateTime if year < 1000 from mysql.(string Interval)

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
It seems the test is not passed. Please recheck the test.

File: expression/builtin_time.go [hunk 1]
```diff
@@ -2867,6 +2867,13 @@ func (du *baseDateArithmitical) add(ctx sessionctx.Context, date types.Time, int
 		date.SetFsp(6)
 	}
 
+	// fix https://github.com/pingcap/tidb/issues/11329
+	if goTime.Year() == 0 {
```
Comment (9547) [inline expression/builtin_time.go:2871]: should be `goTime.Year() == 0` or `goTime.Year() <= 0`

**Comment by 9547** [comment]
> It seems the test is not passed. Please recheck the test.

PTAL

File: expression/integration_test.go [hunk 2]
```diff
@@ -7279,3 +7276,18 @@ func (s *testIntegrationSuite) TestIssue19596(c *C) {
...
+	tk.MustQuery(`SELECT DATE_ADD('1000-01-01 00:00:00', INTERVAL -2 HOUR);`).Check(testkit.Rows("0999-12-31 22:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('1000-01-01 00:00:00', INTERVAL -200 HOUR);`).Check(testkit.Rows("0999-12-23 16:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-01 00:00:00', INTERVAL -2 HOUR);`).Check(testkit.Rows("0000-00-00 22:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-01 00:00:00', INTERVAL -25 HOUR);`).Check(testkit.Rows("0000-00-00 23:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-01 00:00:00', INTERVAL -8784 HOUR);`).Check(testkit.Rows("0000-00-00 00:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-01 00:00:00', INTERVAL -8785 HOUR);`).Check(testkit.Rows("<nil>"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-02 00:00:00', INTERVAL -2 HOUR);`).Check(testkit.Rows("0001-01-01 22:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-02 00:00:00', INTERVAL -24 HOUR);`).Check(testkit.Rows("0001-01-01 00:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-02 00:00:00', INTERVAL -25 HOUR);`).Check(testkit.Rows("0000-00-00 23:00:00"))
+	tk.MustQuery(`SELECT DATE_ADD('0001-01-02 00:00:00', INTERVAL -8785 HOUR);`).Check(testkit.Rows("0000-00-00 23:00:00"))
```
Comment (lzmhhh123) [inline expression/integration_test.go:7292]: Should this test be NULL? As the issue mentioned the mysql result.

Comment (9547) [reply expression/integration_test.go:7292]: MySQL's result is this case line 7288(the base date is different)

```
tk.MustQuery(`SELECT DATE_ADD('0001-01-01 00:00:00', INTERVAL -8785 HOUR);`).Check(testkit.Rows("<nil>"))
```

File: expression/integration_test.go [hunk 3]
```diff
@@ -7298,6 +7295,21 @@ func (s *testIntegrationSuite) TestIssue19596(c *C) {
 	tk.MustGetErrMsg("create table t (a int) partition by range(a) (PARTITION p0 VALUES LESS THAN (a));", "[expression:1054]Unknown column 'a' in 'expression'")
 }
 
+func (s *testIntegrationSerialSuite) TestIssue11645(c *C) {
```
Comment (wshwsh12) [inline expression/integration_test.go:7298]: I think using parallel test is enough....

File: expression/builtin_time.go [hunk 4]
```diff
@@ -2867,6 +2867,13 @@ func (du *baseDateArithmitical) add(ctx sessionctx.Context, date types.Time, int
...
+		hour, minute, second := goTime.Clock()
+		date.SetCoreTime(types.FromDate(0, 0, 0, hour, minute, second, goTime.Nanosecond()<<3))
```
Comment (wshwsh12) [inline expression/builtin_time.go:2873]: `goTime.Nanosecond()<<3`  ?  Should it be `goTime.Nanosecond()/1000`?

File: expression/builtin_time.go [hunk 5]
```diff
@@ -2928,6 +2935,13 @@ func (du *baseDateArithmitical) sub(ctx sessionctx.Context, date types.Time, int
...
```
Comment (wshwsh12) [inline expression/builtin_time.go:2941]: Ditto.

File: expression/builtin_time.go (hunk 4 above)
Comment (9547) [reply expression/builtin_time.go:2873]: I think they have same result, and bitwise operations are faster than divide.

File: expression/integration_test.go (hunk 3 above)
Comment (9547) [reply expression/integration_test.go:7298]: Thanks for the advise.

File: expression/builtin_time.go (hunk 4 above)
Comment (wshwsh12) [reply expression/builtin_time.go:2873]: `goTime.Nanosecond()<<3` means  `goTime.Nanosecond()*8`

Comment (9547) [reply expression/builtin_time.go:2873]: Sorry, It's my mistake, I'll fix it right now.

**Comment by 9547** [comment]
@wsabc01 PTAL

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
