### PR TITLE
planner: fix incorrect range for prefix index range scan

### LINKED ISSUE #22032: got incorrect result when using prefix index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
create table t (a varchar(50), index idx_a(a(2)));
insert into t values ('aaa');
select * from t use index (idx_a) where a > 'aa';
```

### 2. What did you expect to see? (Required)
```
+------+
| a    |
+------+
| aaa  |
+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
tidb> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1918-g27071f14d
Edition: Community
Git Commit Hash: 27071f14d796492e50bed6729fa07d30ee9d57f2
Git Branch: master
UTC Build Time: 2020-12-25 08:41:27
GoVersion: go1.15.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

PS:
```
tidb> explain select * from t use index (idx_a) where a > 'aa';
+-------------------------------+---------+-----------+-------------------------+---------------------------------------------------+
| id                            | estRows | task      | access object           | operator info                                     |
+-------------------------------+---------+-----------+-------------------------+---------------------------------------------------+
| IndexLookUp_8                 | 3333.33 | root      |                         |                                                   |
| ├─IndexRangeScan_5(Build)     | 3333.33 | cop[tikv] | table:t, index:idx_a(a) | range:("aa",+inf], keep order:false, stats:pseudo |
| └─Selection_7(Probe)          | 3333.33 | cop[tikv] |                         | gt(test.t.a, "aa")                                |
|   └─TableRowIDScan_6          | 3333.33 | cop[tikv] | table:t                 | keep order:false, stats:pseudo                    |
+-------------------------------+---------+-----------+-------------------------+---------------------------------------------------+
```
For `IndexRangeScan_5`, since it is prefix index, the range should be `["aa",+inf]`.

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #22032 

Problem Summary:
Range is incorrect for prefix index range scan in some cases. 

### What is changed and how it works?

What's Changed:
If the length of the last column of the range's `LowVal` is equal to the prefix length, the range's `LowExclude` should be set false.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix incorrect range for prefix index range scan

### CODE REVIEW

File: util/ranger/ranger_test.go [hunk 1]
```diff
@@ -582,7 +582,7 @@ create table t(
 			exprStr:     `d < "你好" || d > "你好"`,
 			accessConds: "[or(lt(test.t.d, 你好), gt(test.t.d, 你好))]",
 			filterConds: "[or(lt(test.t.d, 你好), gt(test.t.d, 你好))]",
-			resultStr:   "[[-inf,\"你好\") (\"你好\",+inf]]",
+			resultStr:   "[[-inf,+inf]]",
```
Comment (Reminiscent) [inline util/ranger/ranger_test.go:585]: It seems not correct here?

Comment (xuyifangreeneyes) [reply util/ranger/ranger_test.go:585]: For example, `"你好吗"` satisfies `d < "你好" || d > "你好"` but its prefix `"你好"` is not included by `[-inf,\"你好\") (\"你好\",+inf]`

**Comment by xuyifangreeneyes** [comment]
@Reminiscent @lzmhhh123 PTAL

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by winoros — APPROVED** [review]
lgtm

File: util/ranger/ranger_test.go (hunk 1 above)
Comment (AilinKid) [reply util/ranger/ranger_test.go:585]: general speaking: "你好".nextPrefix() will skip the "你好吗"
