### PR TITLE
br: retry to flush checkpoint

### LINKED ISSUE #56394: br restore failed when kill one of tikv or kill pd leader
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run br restore
2、kill one of tikv or kill pd leader or injection br network partition
3、br restore failed

### 2. What did you expect to see? (Required)
br restore success

### 3. What did you see instead (Required)
br restore failed

### 4. What is your TiDB version? (Required)

./tidb-server -V
 Release Version: v8.4.0-alpha
Edition: Community
Git Commit Hash: f399e91cf873e21a8a5f8c9a74578cb76d20fd86
Git Branch: heads/refs/tags/v8.4.0-alpha
UTC Build Time: 2024-09-26 11:46:59
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-09-27T12:56:14.855+0800

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #56394 

Problem Summary:
flush checkpoint need retry
### What changed and how does it work?
add retry logical when flush checkpoint
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/checkpoint/checkpoint.go [hunk 1]
```diff
@@ -305,12 +307,79 @@ func (r *CheckpointRunner[K, V]) setLock(ctx context.Context, errCh chan error)
...
+		lastIdx := len(f.incompleteMetas) - 1
+		if err := r.doFlush(ctx, f.incompleteMetas[lastIdx]); err != nil {
+			log.Warn("failed to flush checkpoint data", zap.Error(err))
+			return
+		}
+		f.incompleteMetas = f.incompleteMetas[:lastIdx]
+	} else if len(f.incompleteChecksums) > 0 {
+		lastIdx := len(f.incompleteChecksums) - 1
+		if err := r.doChecksumFlush(ctx, f.incompleteChecksums[lastIdx]); err != nil {
+			log.Warn("failed to flush checkpoint data", zap.Error(err))
```
Comment (3pointer) [inline br/pkg/checkpoint/checkpoint.go:347]:
```suggestion
			log.Warn("failed to flush checkpoint checksum", zap.Error(err))
```

it's better to have some other log, because we only doing flushOneIncomplete in retry.

**Review by 3pointer — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
Rest LGTM.
/hold for unfinished comments. Fell free to unhold it when you are ready.

File: br/pkg/checkpoint/checkpoint.go [hunk 2]
```diff
@@ -305,12 +307,79 @@ func (r *CheckpointRunner[K, V]) setLock(ctx context.Context, errCh chan error)
...
+}
+
+func (f *flusher[K, V]) flushOneIncomplete(ctx context.Context, r *CheckpointRunner[K, V]) {
+	if len(f.incompleteMetas) > 0 {
+		lastIdx := len(f.incompleteMetas) - 1
+		if err := r.doFlush(ctx, f.incompleteMetas[lastIdx]); err != nil {
+			log.Warn("failed to flush checkpoint data", zap.Error(err))
+			return
+		}
+		f.incompleteMetas = f.incompleteMetas[:lastIdx]
```
[the remark this answers is not in the document]
Comment (Leavrth) [reply br/pkg/checkpoint/checkpoint.go:344]: done

File: br/pkg/checkpoint/checkpoint.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/checkpoint/checkpoint.go]: done
