### PR TITLE
planner: make pushdown limit use its child schema

### LINKED ISSUE #20801: Select generated column with limit failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (a int, b int as (a + 1));
insert into t(a) values (1);
select b from t limit 1;
```

### 2. What did you expect to see? (Required)

```console
+------+
| b    |
+------+
|    2 |
+------+
```

### 3. What did you see instead (Required)
```console
ERROR 1105 (HY000): Can't find column test.t.a in schema Column: [test.t.b] Unique key: []
```

### 4. What is your TiDB version? (Required)

master
```
commit 4e58f329b1428d8d863266eab6c6fbb6fda34d8f (HEAD, upstream/master)
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #20801 

Problem Summary:

### What is changed and how it works?

make pushdown limit use its child schema.
Then if we update the physicalTableScan's schema, then the tableReader's schema is updated as well.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

File: planner/core/task.go [hunk 1]
```diff
@@ -835,6 +835,8 @@ func (p *PhysicalLimit) attach2Task(tasks ...task) task {
 			stats := deriveLimitStats(childProfile, float64(newCount))
 			pushedDownLimit := PhysicalLimit{Count: newCount}.Init(p.ctx, stats, p.blockOffset)
 			cop = attachPlan2Task(pushedDownLimit, cop).(*copTask)
+			// Don't use clone() so that Limit and its children share the same schema. Otherwise the virtual generated column may not be resolved right.
+			pushedDownLimit.SetSchema(pushedDownLimit.children[0].Schema())
```
Comment (tangenta) [inline planner/core/task.go:839]: `PhysicalLimit` inherits its child schema in the old implementation. I think the problem is that `ExpandVirtualColumns` of `TableScan` happens **AFTER** inheritance.

Inheritance: 
https://github.com/pingcap/tidb/blob/369c12f779f8e990f38af6a158be1d702aef4922/planner/core/task.go#L718

ExpandVirtualColumn:
https://github.com/pingcap/tidb/blob/369c12f779f8e990f38af6a158be1d702aef4922/planner/core/task.go#L730

Comment (wjhuang2016) [reply planner/core/task.go:839]: ExpandVirtualColumns of TableScan happens AFTER inheritance.

It is. So let them share the same schema.

**Review by tangenta — COMMENTED** [review]
LGTM

**Review by winoros — APPROVED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
