### PR TITLE
planner: correct plan when scan tidb related cluster table with KeepOrder

### LINKED ISSUE #51723: Return out of order results for query `cluster_slow_query` with order by
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tiup playground nightly --db 2 --tiflash 0
mysql --comments --host 127.0.0.1 --port 4000 -uroot --local-infile=1 -e "use test;create table t(a int); insert into t values (1);"
mysql --comments --host 127.0.0.1 --port 4000 -uroot --local-infile=1 -e "use test;select sleep(1.1) from t;"
mysql --comments --host 127.0.0.1 --port 4001 -uroot --local-infile=1 -e "use test;select sleep(1.1) from t;"
mysql --comments --host 127.0.0.1 --port 4001 -uroot --local-infile=1 -e "use test;select sleep(1.1) from t;"
mysql --comments --host 127.0.0.1 --port 4000 -uroot --local-infile=1 -e "use test;select sleep(1.1) from t;"
mysql --comments --host 127.0.0.1 --port 4001 -uroot --local-infile=1 -e "select time from information_schema.cluster_slow_query order by time;"
```

### 2. What did you expect to see? (Required)

return values are ordered.

### 3. What did you see instead (Required)

sometimes the results are out of order.

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.0.0-alpha-435-gb55c855142
Edition: Community
Git Commit Hash: b55c8551421852bae33af671fa1bfc3f605bb494
Git Branch: HEAD
UTC Build Time: 2024-03-08 07:11:55
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #51723

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/find_best_task.go [hunk 1]
```diff
@@ -2597,6 +2597,10 @@ func convertToTableScan(ds *logicalop.DataSource, prop *property.PhysicalPropert
 	var task base.Task = copTask
 	if candidate.isMatchProp {
 		copTask.keepOrder = true
+		if ds.Table.Type().IsClusterTable() {
```
Comment (AilinKid) [inline pkg/planner/core/find_best_task.go:2600]: we can directly to modify the variable of isMatchProp in
image

Comment (Defined2014) [reply pkg/planner/core/find_best_task.go]: Done

File: pkg/planner/core/find_best_task.go [hunk 2]
```diff
@@ -761,6 +761,10 @@ func compareCandidates(sctx base.PlanContext, prop *property.PhysicalProperty, l
 }
 
 func isMatchProp(ds *logicalop.DataSource, path *util.AccessPath, prop *property.PhysicalProperty) bool {
+	if ds.Table.Type().IsClusterTable() {
```
Comment (AilinKid) [inline pkg/planner/core/find_best_task.go:764]: && !prop.IsSortItemEmpty()

Comment (Defined2014) [reply pkg/planner/core/find_best_task.go]: Done

File: pkg/planner/core/task.go [hunk 3]
```diff
@@ -1089,14 +1090,84 @@ func (p *PhysicalTopN) canPushDownToTiFlash(mppTask *MppTask) bool {
...
+	copTsk.tablePlan, err = copTsk.tablePlan.Clone(p.SCtx())
+	if err != nil {
+		return nil, false
+	}
+	finalTblScanPlan := copTsk.tablePlan
+	for len(finalTblScanPlan.Children()) > 0 {
+		selOnTblScan, _ = finalTblScanPlan.(*PhysicalSelection)
+		finalTblScanPlan = finalTblScanPlan.Children()[0]
+	}
+	tblScan = finalTblScanPlan.(*PhysicalTableScan)
```
Comment (AilinKid) [inline pkg/planner/core/task.go:1119]: check the succ of the assert, or L1122 may panic?
image
this code from pic should do the same, but it didn't >.<!

File: pkg/planner/core/task.go [hunk 4]
```diff
@@ -1089,14 +1090,84 @@ func (p *PhysicalTopN) canPushDownToTiFlash(mppTask *MppTask) bool {
...
+
+	// Check the table is `CLUSTER_SLOW_QUERY` or not.
+	if tblScan.Table.Name.O != infoschema.ClusterTableSlowLog {
```
Comment (AilinKid) [inline pkg/planner/core/task.go:1122]: should we just lift the limitation for all cluster table?
like do `ds.Table.Type().IsClusterTable()`
why tp is only in is.Table  😂
image

File: pkg/planner/core/task.go [hunk 5]
```diff
@@ -1089,14 +1090,84 @@ func (p *PhysicalTopN) canPushDownToTiFlash(mppTask *MppTask) bool {
...
+		return nil, false
+	}
+
+	colsProp, ok := GetPropByOrderByItems(p.ByItems)
+	if !ok {
+		return nil, false
+	}
+	if len(colsProp.SortItems) != 1 || !colsProp.SortItems[0].Col.Equal(p.SCtx().GetExprCtx().GetEvalCtx(), tblScan.HandleCols.GetCol(0)) {
```
Comment (AilinKid) [inline pkg/planner/core/task.go:1130]: what if the cluster pk contain 2 col which can satisfy the two sort item?

File: pkg/planner/core/task.go [hunk 6]
```diff
@@ -1089,14 +1090,84 @@ func (p *PhysicalTopN) canPushDownToTiFlash(mppTask *MppTask) bool {
...
+// Attach2Task implements the PhysicalPlan interface.
 func (p *PhysicalTopN) Attach2Task(tasks ...base.Task) base.Task {
 	t := tasks[0].Copy()
 	cols := make([]*expression.Column, 0, len(p.ByItems))
 	for _, item := range p.ByItems {
 		cols = append(cols, expression.ExtractColumns(item.Expr)...)
 	}
 	needPushDown := len(cols) > 0
+	if copTask, ok := t.(*CopTask); ok && needPushDown && len(copTask.rootTaskConds) == 0 {
+		newTask, changed := p.pushPartialTopNDownToTiDBCop(copTask)
```
Comment (AilinKid) [inline pkg/planner/core/task.go:1166]: i think your target case is small branch of L1191,  how about changing the func signature as below
```
![image](https://github.com/user-attachments/assets/a40b4eba-5320-4ba2-94df-5224c770b5f3)
```
when we get the pushed topN below, the sort may be satisfied by source, then the returned value is a bare limit, if not the returned value is a splitted topN

**Review by AilinKid — APPROVED** [review]

**Review by winoros — APPROVED** [review]
