### PR TITLE
planner/core: fix partition selection on PointGet/BatchPointGet

### LINKED ISSUE #19141: PointGet/BatchPointGet will break partition selection
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (c_int int, primary key (c_int)) partition by hash ( c_int ) partitions 4;
insert into t values (1), (2), (3), (4);
select * from t partition (p0); -- only 4 is in p0
select * from t partition (p0) where c_int = 1;
update t partition (p0) set c_int = -c_int where c_int in (2, 3);
select * from t;
```

### 2. What did you expect to see? (Required)

Partition selection should prevent all rows in other partitions from being selected in any situation.

### 3. What did you see instead (Required)

```
mysql> select * from t partition (p0);
+-------+
| c_int |
+-------+
|     4 |
+-------+
1 row in set (0.05 sec)

mysql> select * from t partition (p0) where c_int = 1;
+-------+
| c_int |
+-------+
|     1 |
+-------+
1 row in set (0.05 sec)

mysql> update t partition (p0) set c_int = -c_int where c_int in (2, 3);
Query OK, 2 rows affected (0.05 sec)
Rows matched: 2  Changed: 2  Warnings: 0

mysql> select * from t;
+-------+
| c_int |
+-------+
|     4 |
|    -2 |
|     1 |
|    -3 |
+-------+
4 rows in set (0.06 sec)

```

### 4. What is your TiDB version? (Required)

master @ 8978773f5e3d43a100550e6babea9904a99e5938
release-4.0 @ 3948c7ba7b5d4a081abf2162b791ab67fe650882

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #19141

Problem Summary:

PointGet/BatchPointGet on the hash partition table does not take partition selection grammar into consideration.

### What is changed and how it works?

What's Changed:

How it Works:

* consider partition selection for PointGet
* do not use BatchPointGet when partition selection exists

### Related changes

This PR is on the 4.0 branch, I will file another one to fix the master.

### Check List 

Tests 

- Unit test

### Release note 

-   Fix bug PointGet and BatchPointGet do not consider partition selection grammar and get incorrect results.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @coocood @imtbkcat

**Comment by coocood** [comment]
LGTM

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -749,6 +764,16 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt) *PointGetP
 	return nil
 }
 
+func partitionNameInSet(name model.CIStr, pnames []model.CIStr) bool {
```
Comment (ngaut) [inline planner/core/point_get_plan.go:767]: Is there a performance issue when the partition count is large, For example: 65535.

Comment (tiancaiamao) [reply planner/core/point_get_plan.go:767]: This name slice is not all the partitions of a table.
It's just the selected ones:
```
select * from t partition (p0,p1,p2) ...
```

A sane person would not write a SQL like this:

```
select * from t partition (p0,p1,p2....p65535) ...
```

File: planner/core/point_get_plan_test.go [hunk 2]
```diff
@@ -429,3 +429,22 @@ func (s *testPointGetSuite) TestBatchPointGetPartition(c *C) {
 	tk.MustExec("delete from t where (a,b) in ((1,1),(2,2),(3,3),(4,4))")
 	tk.MustQuery("select * from t where (a, b) in ((1, 1), (2, 2), (3, 3), (4, 4))").Check(testkit.Rows())
 }
+
+func (s *testPointGetSuite) TestIssue19141(c *C) {
```
Comment (SunRunAway) [inline planner/core/point_get_plan_test.go:433]: Should this case be ported back to master branch?

Comment (tiancaiamao) [reply planner/core/point_get_plan_test.go:433]: Sure!
