### PR TITLE
expression: fixed json type for truncate

### LINKED ISSUE #13044: Lost connection when using builtin function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
mysql> select truncate(json_array(), 1);
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

2. What did you expect to see?

Return a value or an error.

3. What did you see instead?

Go routine panic and lost connect.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v4.0.0-alpha-663-g7b27cfb60
Git Commit Hash: 7b27cfb60ffd8d26dad9d176edc8a386769ee4b6
Git Branch: master
UTC Build Time: 2019-10-30 12:10:27
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ekalinin**
### What problem does this PR solve? 

Fixes #13044 

### What is changed and how it works?

```
tidb> select truncate(json_array(), 1), truncate("cascasc", -1), truncate("12.3333", -1);
+---------------------------+-------------------------+-------------------------+
| truncate(json_array(), 1) | truncate("cascasc", -1) | truncate("12.3333", -1) |
+---------------------------+-------------------------+-------------------------+
|                         0 |                       0 |                      10 |
+---------------------------+-------------------------+-------------------------+
1 row in set, 1 warning (0.00 sec)
```

the same output has mysql (v5.7):

```
| truncate(json_array(), 1) | truncate("cascasc", -1) | truncate("12.34567", -1) |
| ------------------------- | ----------------------- | ------------------------ |
| 0                         | 0                       | 10                       |
```

[View on DB Fiddle](https://www.db-fiddle.com/f/cwJ9RzRkSW2wk5xp4xbq6z/1)

### Check List 

Tests 

 - Integration test

### CODE REVIEW

File: expression/builtin_math.go [hunk 1]
```diff
@@ -1743,6 +1743,10 @@ func (c *truncateFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 	if argTp == types.ETTimestamp || argTp == types.ETDatetime || argTp == types.ETDuration || argTp == types.ETString {
 		argTp = types.ETReal
 	}
+	// MySQL compatibility
+	if argTp == types.ETJson {
+		argTp = types.ETInt
+	}
```
Comment (wshwsh12) [inline expression/builtin_math.go]: I was really curious why the Type is `ETInt` instead of `ETReal`. And I run the SQL in my local MySQL 5.7.26 and MySQL 8.0.17. It gets an interesting result.
```
mysql> select truncate(json_array(), 1), truncate("cascasc", -1), truncate("12.3333", -1);
+---------------------------+-------------------------+-------------------------+
| truncate(json_array(), 1) | truncate("cascasc", -1) | truncate("12.3333", -1) |
+---------------------------+-------------------------+-------------------------+
|                       0.0 |                       0 |                      10 |
+---------------------------+-------------------------+-------------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------------------+
| Level   | Code | Message                                                               |
+---------+------+-----------------------------------------------------------------------+
| Warning | 3156 | Invalid JSON value for CAST to DOUBLE from column json_array at row 1 |
| Warning | 1292 | Truncated incorrect DOUBLE value: 'cascasc'                           |
+---------+------+-----------------------------------------------------------------------+
2 rows in set (0.00 sec)
```
And it seems that the function cast json to double ?

Comment (ekalinin) [reply expression/builtin_math.go]: Fixed. For all types with `IsStringKind`, returns real type.

File: expression/builtin_math.go [hunk 2]
```diff
@@ -1796,7 +1796,9 @@ func (c *truncateFunctionClass) getFunction(ctx sessionctx.Context, args []Expre
 	case types.ETDecimal:
 		sig = &builtinTruncateDecimalSig{bf}
 		sig.setPbCode(tipb.ScalarFuncSig_TruncateDecimal)
-	}
+	default:
+		return nil, errIncorrectArgs.GenWithStackByArgs("truncate")
```
Comment (wshwsh12) [inline expression/builtin_math.go]: s/ truncate /Unsupport type in truncateFunctionClass
