### PR TITLE
test: stabilize `TestAuditPluginRetrying`

### LINKED ISSUE #65222: flaky test TestAuditPluginRetrying
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
The test branch is the master branch, and Go 1.25 is used. （https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/46866/）
```
tidb_test.go:3721: 
        	Error Trace:	pkg/server/tests/commontest/tidb_test.go:3721
        	            				pkg/server/internal/testserverclient/server_client.go:150
        	            				pkg/server/tests/commontest/tidb_test.go:3685
        	Error:      	Not equal: 
        	            	expected: 500
        	            	actual  : 499
        	Test:       	TestAuditPluginRetrying
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #65222

Problem Summary:

- `require.Eventually` with the predicate "we observed more audit events than issued statements" checks `len(testResults) > concurrency`, which only becomes true if at least one statement was retried (extra audit events).
- Before the change, `testResults` was a shared slice appended by many server goroutines (audit callbacks) while the test goroutine concurrently reset/read it, with no synchronization. Under load this can lose/corrupt entries, so `len(testResults)` can stay <= `concurrency` even if retries happened.

### What changed and how does it work?

- The change makes `testResults` thread-safe (mutex + snapshot helpers), and also removes DB usage patterns that make the loop less reliable: it switches from `Conn().QueryContext()` (no `Rows`/`Conn` close, error asserts in goroutines) to `db.ExecContext()` with a sized pool (`SetMaxOpenConns`/`SetMaxIdleConns`) and collects errors back in the main goroutine.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/server/tests/commontest/tidb_test.go [hunk 1]
```diff
@@ -3675,7 +3693,9 @@ func TestAuditPluginRetrying(t *testing.T) {
 			audit.retrying = retrying.(bool)
 		}
 		audit.sql = sctx.StmtCtx.OriginalSQL
+		testResultsMu.Lock()
 		testResults = append(testResults, audit)
```
Comment (lance6716) [inline pkg/server/tests/commontest/tidb_test.go]: Maybe also add a closure like `resetTestResults`?
