### PR TITLE
planner: avoid pushing TopN to probe side for virtual columns

### LINKED ISSUE #67981: TopN is incorrectly pushed to IndexLookUp probe side for ORDER BY virtual generated column on expression index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When a virtual column `g` is equivalent to an expression index expression, but the query selects a column that requires a table lookup, TiDB will push down the TopN in IndexLookUp's probing/table-side errors. Because the build/index process does not maintain order, `LIMIT 1` will be premature, resulting in the returned rows not corresponding to the globally minimum/maximum `g`.
```sql
  CREATE TABLE t_bug (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    s VARCHAR(20),
    g VARCHAR(20) GENERATED ALWAYS AS (lower(s)) VIRTUAL,
    KEY idx_exp_lower ((lower(s)))
  );
  INSERT INTO t_bug(s) VALUES ('B'),('a');
mysql> explain SELECT * FROM t_bug    WHERE lower(s) >= 'a'   ORDER BY g   LIMIT 1;
+------------------------------------+---------+-----------+----------------------------------------------+--------------------------------------------------+
| id                                 | estRows | task      | access object                                | operator info                                    |
+------------------------------------+---------+-----------+----------------------------------------------+--------------------------------------------------+
| Projection_8                       | 1.00    | root      |                                              | test.t_bug.id, test.t_bug.s, test.t_bug.g        |
| └─TopN_10                          | 1.00    | root      |                                              | test.t_bug.g, offset:0, count:1                  |
|   └─IndexLookUp_22                 | 1.00    | root      |                                              |                                                  |
|     ├─IndexRangeScan_19(Build)     | 2.00    | cop[tikv] | table:t_bug, index:idx_exp_lower(lower(`s`)) | range:["a",+inf], keep order:false, stats:pseudo |
|     └─TopN_21(Probe)               | 1.00    | cop[tikv] |                                              | test.t_bug.g, offset:0, count:1                  |
|       └─TableRowIDScan_20          | 2.00    | cop[tikv] | table:t_bug                                  | keep order:false, stats:pseudo                   |
+------------------------------------+---------+-----------+----------------------------------------------+--------------------------------------------------+
6 rows in set (0.04 sec)

mysql> SELECT * FROM t_bug    WHERE lower(s) >= 'a'   ORDER BY g   LIMIT 1;
+----+------+------+
| id | s    | g    |
+----+------+------+
|  1 | B    | b    |
+----+------+------+
1 row in set (0.04 sec)
```
### 2. What did you expect to see? (Required)
 2, a, a
### 3. What did you see instead (Required)
1, B, b
### 4. What is your TiDB version? (Required)

Release Version: v9.0.0-beta.2.pre-1598-g874ff3792e
Edition: Community
Git Commit Hash: 874ff3792e7e0f51068547f90cefc1acbfed7232
Git Branch: HEAD
UTC Build Time: 2026-04-22 02:24:07
GoVersion: go1.25.8
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Kernel Type: Classic

### PR DESCRIPTION
**Pull request by lilinghai**
### What problem does this PR solve?

Issue Number: close #67981

Problem Summary:

`TopN` could be incorrectly pushed to the `IndexLookUp` probe side when `ORDER BY`
references a virtual generated column backed by an expression index. In that
shape, the probe-side partial `TopN` may stop too early and return wrong rows.

### What changed and how does it work?

This change keeps `TopN` at the root when an `IndexLookUp` would otherwise push
it to the table/probe side and the `ORDER BY` items reference a virtual
generated column from the table-side schema.

It also adds a regression test for issue `#67981` that checks the full
`plan_tree` output and verifies the query result.

Tests:

- `./tools/check/failpoint-go-test.sh pkg/planner/core -run TestVirtualExprPushDown -count=1`
- `make lint`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix incorrect results caused by pushing TopN to the IndexLookUp probe side when
ordering by a virtual generated column backed by an expression index.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed incorrect results and ordering when TOP N is combined with virtual generated columns and index-lookups; queries now return correct rows and preserve global ordering.

* **Tests**
  * Added regression tests that verify forced-index plans and LIMIT behavior with virtual generated columns, ensuring correct access paths and returned rows.

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/planner/core/integration_test.go [hunk 1]
```diff
@@ -1941,6 +1941,22 @@ func TestVirtualExprPushDown(t *testing.T) {
 		require.NotEmpty(t, plan)
 		tk.MustQuery("select g from t_force_idx force index (idx_exp_i) where (i + 1) >= 1 order by g limit 1;").Check(testkit.Rows("2"))
 
+		tk.MustExec("drop table if exists t_bug")
+		tk.MustExec(`create table t_bug (
+			id bigint primary key auto_increment,
+			s varchar(20),
+			g varchar(20) generated always as (lower(s)) virtual,
+			key idx_exp_lower ((lower(s)))
```
Comment (winoros) [inline pkg/planner/core/integration_test.go:1950]: Seems that we need a test case for `key idx(g)`

Comment (lilinghai) [reply pkg/planner/core/integration_test.go:1950]: added and it is expected.

**Review by winoros — APPROVED** [review]
