### PR TITLE
expression: adjust int constant when compare with year type

### LINKED ISSUE #20305: Comparison result is incorrect between year column and int constant
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

``` mysql
create table t2 (a year(4));
insert into t2 values(69);
select * from t2 where a <= 69;
```

### 2. What did you expect to see? (Required)

In mysql 8.0

``` mysql
mysql> select * from t2 where a <= 69;
+------+
| a    |
+------+
| 2069 |
+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

``` mysql
mysql> select * from t2 where a <= 69;
Empty set (0.00 sec)

mysql> explain select * from t2 where a <= 69;
+-------------------------+---------+-----------+---------------+--------------------------------+
| id                      | estRows | task      | access object | operator info                  |
+-------------------------+---------+-----------+---------------+--------------------------------+
| TableReader_7           | 1.00    | root      |               | data:Selection_6               |
| └─Selection_6           | 1.00    | cop[tikv] |               | le(test.t2.a, 69)              |
|   └─TableFullScan_5     | 3.00    | cop[tikv] | table:t2      | keep order:false, stats:pseudo |
+-------------------------+---------+-----------+---------------+--------------------------------+
3 rows in set (0.00 sec)
```

`69` should be adjusted to `2069`.

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

``` mysql
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

## Score

- 600

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #20305 

Problem Summary: when we compare int with year type, and the int could be interpret as year, it should be adjusted.

Note, this change does not work when int is stored as a column, because MySQL does not support this as well.

```
CREATE TABLE `t3` (`y` year DEFAULT NULL, `a` int DEFAULT NULL);
INSERT INTO `t3` VALUES (2069, 70), (2010, 11), (2155, 2156), (2069, 69);
SELECT * FROM `t3` where y <= a;
```

MySQL produces

```
mysql> SELECT * FROM `t3` where y <= a;
+------+------+
| y    | a    |
+------+------+
| 2155 | 2156 |
+------+------+
```

### What is changed and how it works?

What's Changed: add adjust in args refinement.

### Related changes

- Need to cherry-pick to the release branch 4.0, 3.0.

### Check List 

Tests 

- Integration test

### Release note 

- No release note

### CODE REVIEW

**Comment by ichn-hu** [comment]
@lzmhhh123 PTALA

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Comment by ichn-hu** [comment]
@qw4990 PTAL

File: util/ranger/ranger_test.go [hunk 1]
```diff
@@ -1370,14 +1371,14 @@ func (s *testRangerSuite) TestIndexRangeForYear(c *C) {
 		{
 			indexPos:    0,
 			exprStr:     `a not in (1, 2, 70)`,
-			accessConds: "[not(in(test.t.a, 1, 2, 70))]",
+			accessConds: "[not(in(test.t.a, 1, 2, 70))]", // this is in accordance with MySQL, MySQL won't interpret 70 here as 1970
```
Comment (SunRunAway) [inline util/ranger/ranger_test.go:1374]: Please add another test for `a = 1 or a = 2 or a = 70`.
cc @winoros

File: executor/executor_test.go [hunk 2]
```diff
@@ -6866,6 +6866,15 @@ func (s *testSuite) TestIssue19667(c *C) {
 	tk.MustQuery(`SELECT DATE_ADD(a, INTERVAL 1 SECOND) FROM t`).Check(testkit.Rows("1988-04-17 02:00:00"))
 }
 
+func (s *testSuite) TestIssue20305(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t2 (a year(4))")
+	tk.MustExec("insert into t2 values(69)")
+	tk.MustQuery("select * from t2 where a <= 69").Check(testkit.Rows("2069"))
```
Comment (SunRunAway) [inline executor/executor_test.go:6875]: Please add another regression for int in columns.

**Comment by ichn-hu** [comment]
@SunRunAway PTALA

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
