### PR TITLE
lightning: Change how the ID of `taskCfg.TaskID` is generated

### LINKED ISSUE #55384: lightning might report "verify allocator base failed. local..." using parallel import and they have same task id
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

suppose we are using 2 instances to do parallel import, if they start at same time, their task ID will be the same as we use current time as the id, but we expect 2, it might fail when allocating row ids.
https://github.com/pingcap/tidb/blob/7e9f85320d7614047c8441256803bb5120622a81/lightning/pkg/server/lightning.go#L359

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
fail
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by ei-sugimoto**
### What problem does this PR solve?

If lightning was used in parallel, the function could report an error because the task ID used the current time to generate the ID.

Issue Number: close #55384

Problem Summary:

### What changed and how does it work?
- using hashed uuid

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
Hi, please merge master branch. We have fixed a lightning CI failure in last commits.

**Comment by ei-sugimoto** [comment]
> Hi, please merge master branch. We have fixed a lightning CI failure in last commits.

Does that mean that the changes I made didn't cause the integration tests to fail?

**Comment by D3Hunter** [comment]
> Details

seems integration test fail repeatably, please fix them

**Comment by ei-sugimoto** [comment]
Why does the pull-lightning-integration-test fail? was it affected by my code I modified ?

**Comment by ei-sugimoto** [comment]
> > Details
> 
> seems integration test fail repeatably, please fix them

I fixed them . Please review :)

File: lightning/pkg/server/lightning.go [hunk 1]
```diff
@@ -356,7 +356,8 @@ func (l *Lightning) RunOnceWithOptions(taskCtx context.Context, taskCfg *config.
 		return err
 	}
 
-	taskCfg.TaskID = time.Now().UnixNano()
+	taskCfg.TaskID = int64(uuid.New().ID())
```
Comment (lance6716) [inline lightning/pkg/server/lightning.go:359]: I see `uuid.New` just read some random bytes from `rand.Reader`, and `.ID()` only uses the first 4 bytes. We can directly use https://pkg.go.dev/math/rand#Int63 I think.

File: lightning/pkg/server/lightning.go [hunk 2]
```diff
@@ -27,6 +27,7 @@ import (
 	"encoding/pem"
 	"fmt"
 	"io"
+	mathrand "math/rand"
```
Comment (lance6716) [inline lightning/pkg/server/lightning.go:30]: I suggest we use "crypto/ rand". Because the issue wants to avoid that if two lightning have same `time.Now().UnixNano()` they will have the same ID. Now if math/rand is initialized by the same `time.Now().UnixNano()` they still have the same ID.

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
ptal @D3Hunter

**Review by D3Hunter — APPROVED** [review]
