### PR TITLE
server: use failpoint rather than real error in test `TestCursorFetchErrorInFetch`

### LINKED ISSUE #47029: flaky test `TestCursorFetchErrorInFetch` in `server` pkg
## Bug Report

<details><summary><h3>Flaky runs happened 49 times between "2023-09-09" AND "2023-09-16"<h3></summary>

- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33366/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33358/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33312/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33304/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33302/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33299/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33295/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33293/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33291/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33290/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33252/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33249/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33240/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33206/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33202/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33180/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33164/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33157/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33147/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33142/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33118/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33074/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33071/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33058/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33051/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33048/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33020/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32999/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32964/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32961/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32927/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32924/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32915/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32906/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32904/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32899/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32896/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32882/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32875/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32851/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32842/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32834/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32758/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32757/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32750/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32749/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32698/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32697/)
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32673/)

</details>

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #47029

Problem Summary:

In the original test, I closed the file used by row containers, and expected it to give an error. However, it seems to be unstable, and cannot be used on Mac OS. I turned to use `failpoint` to give a more stable error.

Actually, I'm not very sure whether this PR will fix the flacky test, because I still don't know the root cause of it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/conn_stmt_test.go [hunk 1]
```diff
@@ -334,25 +328,9 @@ func TestCursorFetchErrorInFetch(t *testing.T) {
...
-			fd, err := strconv.Atoi(filepath.Base(path))
-			require.NoError(t, err)
-			require.NoError(t, syscall.Close(fd))
-		}
-		return nil
-	})
-
-	// it'll get "bad file descriptor", as it has been closed in the test.
-	require.Error(t, c.Dispatch(ctx, appendUint32(appendUint32([]byte{mysql.ComStmtFetch}, uint32(stmt.ID())), 1024)))
+	failpoint.Enable("github.com/pingcap/tidb/pkg/util/chunk/get-chunk-error", "return(true)")
```
Comment (hawkingrei) [inline pkg/server/conn_stmt_test.go:331]: require.NoError(t, failpoint.XXXX)

File: pkg/server/conn_stmt_test.go [hunk 2]
```diff
@@ -334,25 +328,9 @@ func TestCursorFetchErrorInFetch(t *testing.T) {
...
+	defer failpoint.Disable("github.com/pingcap/tidb/pkg/util/chunk/get-chunk-error")
```
Comment (hawkingrei) [inline pkg/server/conn_stmt_test.go:332]: Ditto

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
