### PR TITLE
hint: fix panic when query block not found in prepare statement

### LINKED ISSUE #46817: Prepare statement panic when query block not found in hint
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table t (i int);
prepare stmt from 'with a as (select /*+ qb_name(qb1) */ * from t)  select /*+ leading(@qb1)*/ * from a;'
```

### 2. What did you expect to see? (Required)
No panic

### 3. What did you see instead (Required)
SQL panic
```
github.com/pingcap/tidb/server.(*clientConn).Run.func1
    /Users/yusp/work/tidb/server/conn.go:1090
runtime.gopanic
    /usr/local/go/src/runtime/panic.go:914
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1
    /Users/yusp/work/tidb/executor/adapter.go:453
runtime.gopanic
    /usr/local/go/src/runtime/panic.go:914
runtime.panicmem
    /usr/local/go/src/runtime/panic.go:261
runtime.sigpanic
    /usr/local/go/src/runtime/signal_unix.go:861
github.com/pingcap/tidb/util/hint.(*BlockHintProcessor).GetCurrentStmtHints
    /Users/yusp/work/tidb/util/hint/hint_processor.go:599
github.com/pingcap/tidb/planner/core.(*PlanBuilder).pushTableHints
    /Users/yusp/work/tidb/planner/core/logical_plan_builder.go:3578
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect
    /Users/yusp/work/tidb/planner/core/logical_plan_builder.go:3823
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build
    /Users/yusp/work/tidb/planner/core/planbuilder.go:804
github.com/pingcap/tidb/planner/core.GeneratePlanCacheStmtWithAST
    /Users/yusp/work/tidb/planner/core/plan_cache_utils.go:141
github.com/pingcap/tidb/executor.(*PrepareExec).Next
    /Users/yusp/work/tidb/executor/prepared.go:120
github.com/pingcap/tidb/executor.Next
    /Users/yusp/work/tidb/executor/executor.go:328
github.com/pingcap/tidb/executor.(*ExecStmt).next
    /Users/yusp/work/tidb/executor/adapter.go:1154
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
    /Users/yusp/work/tidb/executor/adapter.go:927
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
    /Users/yusp/work/tidb/executor/adapter.go:776
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
    /Users/yusp/work/tidb/executor/adapter.go:571
github.com/pingcap/tidb/session.runStmt
    /Users/yusp/work/tidb/session/session.go:2373
github.com/pingcap/tidb/session.(*session).ExecuteStmt
    /Users/yusp/work/tidb/session/session.go:2237
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt
    /Users/yusp/work/tidb/server/driver_tidb.go:252
github.com/pingcap/tidb/server.(*clientConn).handleStmt
    /Users/yusp/work/tidb/server/conn.go:2122
github.com/pingcap/tidb/server.(*clientConn).handleQuery
    /Users/yusp/work/tidb/server/conn.go:1972
github.com/pingcap/tidb/server.(*clientConn).dispatch
    /Users/yusp/work/tidb/server/conn.go:1403
github.com/pingcap/tidb/server.(*clientConn).Run
    /Users/yusp/work/tidb/server/conn.go:1152
github.com/pingcap/tidb/server.(*Server).onConn
    /Users/yusp/work/tidb/server/server.go:648
```

### 4. What is your TiDB version? (Required)
d3d30f5f556e826ae5ec2d25c8d8fd6b9412e72a and v6.5.3

### PR DESCRIPTION
**Pull request by jackysp**
### What problem does this PR solve?

Issue Number: close #46817

Problem Summary:

### What is changed and how it works?
Fix it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/prepared_test.go [hunk 1]
```diff
@@ -98,6 +98,19 @@ func TestPreparedStmtWithHint(t *testing.T) {
 	tk.MustQuery("execute stmt").Check(testkit.Rows("1"))
 }
 
+func TestPreparedCTEStmtWithHint(t *testing.T) {
```
Comment (hawkingrei) [inline executor/prepared_test.go:101]: I think it can be appended into ```TestPreparedStmtWithHint```. We find that it takes too much time for the test to start. So we suggest adding the new cases to the old ones.

Comment (jackysp) [reply executor/prepared_test.go:101]: haha, OK

Comment (jackysp) [reply executor/prepared_test.go]: Addressed, PTAL

**Review by zimulala — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]
