### PR TITLE
planner: ignore anonymous index while tiflash replica is available

### LINKED ISSUE #20893: `explain format='hint'`'s ouput is not recoverable.
## Description
## Bug Report


### 1. Minimal reproduce step (Required)
Create a cluster that contains one `TiFlash` node.

```sql
> create table t(a int, index idx(a))
> ALTER TABLE t SET TIFLASH REPLICA 1

> explain select /*+ read_from_storage(tiflash[t]) */ * from t;
+-------------------+----------+--------------+---------------+--------------------------------+
| id                | estRows  | task         | access object | operator info                  |
+-------------------+----------+--------------+---------------+--------------------------------+
| TableReader_5     | 10000.00 | root         |               | data:TableFullScan_4           |
| └─TableFullScan_4 | 10000.00 | cop[tiflash] | table:t       | keep order:false, stats:pseudo |
+-------------------+----------+--------------+---------------+--------------------------------+


> explain format='hint' select /*+ read_from_storage(tiflash[t]) */ * from t;
+-------------------------------------------------------------------------------------------------------------------+
| hint                                                                                                              |
+-------------------------------------------------------------------------------------------------------------------+
| use_index(@`sel_1` `test`.`t` ), read_from_storage(@`sel_1` tiflash[`test`.`t`]), read_from_storage(tiflash[`t`]) |
+-------------------------------------------------------------------------------------------------------------------+

> /* use this output hint to construct another hint */

> explain select /*+ use_index(@`sel_1` `test`.`t` ), read_from_storage(@`sel_1` tiflash[`test`.`t`]), read_from_storage(tiflash[`t`]) */ * from t;

+-------------------+----------+-----------+---------------+--------------------------------+
| id                | estRows  | task      | access object | operator info                  |
+-------------------+----------+-----------+---------------+--------------------------------+
| TableReader_5     | 10000.00 | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4 | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-------------------+----------+-----------+---------------+--------------------------------+
```

And here is the warnings:
```sql
+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                                                                  |
+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1815 | No available path for table test.t with the store type tiflash of the hint /*+ read_from_storage */, please check the status of the table replica and variable value of tidb_isolation_read_engines(map[0:{} 1:{} 2:{}]) |
| Warning | 1815 | There are no matching table names for (t) in optimizer hint /*+ READ_FROM_STORAGE(tiflash[t, t]) */. Maybe you can use the table alias name                                                                              |
+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

### 2. What did you expect to see? (Required)

```sql
> explain select /*+ use_index(@`sel_1` `test`.`t` ), read_from_storage(@`sel_1` tiflash[`test`.`t`]), read_from_storage(tiflash[`t`]) */ * from t;
+-------------------+----------+--------------+---------------+--------------------------------+
| id                | estRows  | task         | access object | operator info                  |
+-------------------+----------+--------------+---------------+--------------------------------+
| TableReader_5     | 10000.00 | root         |               | data:TableFullScan_4           |
| └─TableFullScan_4 | 10000.00 | cop[tiflash] | table:t       | keep order:false, stats:pseudo |
+-------------------+----------+--------------+---------------+--------------------------------+
```

### 3. What did you see instead (Required)

```sql
> explain select /*+ use_index(@`sel_1` `test`.`t` ), read_from_storage(@`sel_1` tiflash[`test`.`t`]), read_from_storage(tiflash[`t`]) */ * from t;

+-------------------+----------+-----------+---------------+--------------------------------+
| id                | estRows  | task      | access object | operator info                  |
+-------------------+----------+-----------+---------------+--------------------------------+
| TableReader_5     | 10000.00 | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4 | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-------------------+----------+-----------+---------------+--------------------------------+
```

### 4. What is your TiDB version? (Required)

`Master`

## SIG slack channel

[#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: close #20893 

Problem Summary:

### What is changed and how it works?

This pull request ignore anonymous index hint while tiflash hint is available.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- planner: ignore anonymous index while tiflash replica is available

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: planner/core/plan_test.go [hunk 1]
```diff
@@ -385,6 +385,33 @@ func (s *testPlanNormalize) TestExplainFormatHint(c *C) {
 		"use_index(@`sel_2` `test`.`t2` `idx_c2`), hash_agg(@`sel_2`), use_index(@`sel_1` `test`.`t1` `idx_c2`), hash_agg(@`sel_1`)"))
 }
 
+func (s *testPlanNormalize) TestHintRecoverable(c *C) {
```
Comment (breeswish) [inline planner/core/plan_test.go:388]: This only tests whether a plan containing TiFlash is recoverable. Would you like to update the name?

File: planner/core/planbuilder.go [hunk 2]
```diff
@@ -910,7 +912,8 @@ func getPossibleAccessPaths(ctx sessionctx.Context, tableHints *tableHintInfo, i
 		// It is syntactically valid to omit index_list for USE INDEX, which means “use no indexes”.
 		// Omitting index_list for FORCE INDEX or IGNORE INDEX is a syntax error.
 		// See https://dev.mysql.com/doc/refman/8.0/en/index-hints.html.
-		if hint.IndexNames == nil && hint.HintType != ast.HintIgnore {
+		if hint.IndexNames == nil && (hint.HintType == ast.HintForce ||
+			(hint.HintType == ast.HintUse && !(tableHints != nil && len(tableHints.tiflashTables) > 0))) {
```
Comment (eurekaka) [inline planner/core/planbuilder.go:916]: We should make `explain format = 'hint'` return correct result, i.e, no `use_index(@`sel_1` `test`.`t` )` in the hint, instead of handling this invalid input hint?

File: planner/core/plan_test.go (hunk 1 above)
Comment (iosmanthus) [reply planner/core/plan_test.go:388]: OK.

**Comment by breeswish** [comment]
@iosmanthus PTAL about the comments, thanks

File: planner/core/planbuilder.go (hunk 2 above)
Comment (iosmanthus) [reply planner/core/planbuilder.go:927]: Good idea, I will have a try on this solution.

Comment (iosmanthus) [reply planner/core/planbuilder.go:927]: A potential difficulty of this way is that lots of tests will be broken.

Comment (eurekaka) [reply planner/core/planbuilder.go:927]: Why? only the result of `explain format = 'hint'` for tiflash plan would change?

**Comment by iosmanthus** [comment]
@eurekaka PTAL! THX!

File: planner/core/plan_test.go [hunk 3]
```diff
@@ -433,6 +433,33 @@ func (s *testPlanNormalize) TestExplainFormatHint(c *C) {
...
+	for _, tblInfo := range db.Tables {
+		if tblInfo.Name.L == "t" {
+			tblInfo.TiFlashReplica = &model.TiFlashReplicaInfo{
+				Count:     1,
+				Available: true,
+			}
+		}
+	}
+
+	rows := tk.MustQuery("explain select * from t").Rows()
```
Comment (breeswish) [inline planner/core/plan_test.go:455]: Considering now you are hiding the hint for TiFlash, maybe you should test against the hint text?

Comment (iosmanthus) [reply planner/core/plan_test.go:455]: OK.

**Comment by iosmanthus** [comment]
@eurekaka PTAL

**Review by eurekaka — APPROVED** [review]
/lgtm
