### PR TITLE
planner: fix cannot binding for deleting multi table with alias 

### LINKED ISSUE #56726: ERROR 1109 when create global binding for delete statement with subquery
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> use test;
Database changed
mysql> create table t1(id int);
Query OK, 0 rows affected (0.09 sec)

mysql> create table t2(id int);
Query OK, 0 rows affected (0.10 sec)

mysql> delete tt1 from t1 tt1,(select max(id) id from t2)tt2 where tt1.id<=tt2.id;
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> create global binding for
    -> delete tt1 from t1 tt1,(select max(id) id from t2)tt2 where tt1.id<=tt2.id
    -> using
    -> delete /*+ MAX_EXECUTION_TIME(10)*/ tt1 from t1 tt1,(select max(id) id from t2)tt2 where tt1.id<=tt2.id;
ERROR 1109 (42S02): Unknown table 'tt1' in MULTI DELETE
mysql> 
```
### 2. What did you expect to see? (Required)
NO ERROR
### 3. What did you see instead (Required)
ERROR 1109
### 4. What is your TiDB version? (Required)
```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.5.11
Edition: Community
Git Commit Hash: 3f2073261bf9f454c3c677d76d120c6ab40ca05c
Git Branch: HEAD
UTC Build Time: 2024-09-18 04:07:03
GoVersion: go1.19.13
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #56726 

Problem Summary:

### What changed and how does it work?

```delete tt1 from t1 tt1,(select max(id) id from t2)tt2 where tt1.id<=tt2.id```
```delete tt1``` will be transfer to ```delete current_database.t1``` in default when to deal with the statsment in the ```create binding```.
 because ```tt1``` cannot be used as alias in delete statement.
 so we have to set ```tt1``` as alias by aliasChecker.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix cannot binding for deleting multi table with alias

修复无法为带别名的多表删除进行 binding 的问题
```

### CODE REVIEW

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -5875,6 +5875,9 @@ func IsDefaultExprSameColumn(names types.NameSlice, node ast.ExprNode) bool {
 }
 
 func (b *PlanBuilder) buildDelete(ctx context.Context, ds *ast.DeleteStmt) (base.Plan, error) {
+	if !b.ctx.GetSessionVars().InRestrictedSQL {
+		fmt.Println("wwz")
+	}
```
Comment (qw4990) [inline pkg/planner/core/logical_plan_builder.go:5880]: Should remove this.

Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go:5880]: it still is in the WIP

File: pkg/planner/core/preprocess.go [hunk 2]
```diff
@@ -1991,3 +1993,56 @@ func (p *preprocessor) skipLockMDL() bool {
...
+		}
+		// 2. check the Tables to tag the alias
+		if deleteStmt.Tables != nil && deleteStmt.Tables.Tables != nil {
+			for _, table := range deleteStmt.Tables.Tables {
+				if table.Schema.String() != "" {
+					continue
+				}
+				for _, alias := range aliases {
+					if table.Name.L == alias.L {
+						table.IsAlias = true
```
Comment (qw4990) [inline pkg/planner/core/preprocess.go:2024]: Should `break` after setting this.

Comment (hawkingrei) [reply pkg/planner/core/preprocess.go:2026]: Done

File: pkg/parser/ast/dml.go [hunk 3]
```diff
@@ -281,7 +281,8 @@ type TableName struct {
 	PartitionNames []model.CIStr
 	TableSample    *TableSample
 	// AS OF is used to see the data as it was at a specific point in time.
-	AsOf *AsOfClause
+	AsOf    *AsOfClause
+	IsAlias bool
```
Comment (qw4990) [inline pkg/parser/ast/dml.go:285]: Better add some comments and examples for this field.

Comment (hawkingrei) [reply pkg/parser/ast/dml.go:289]: have updated.

File: pkg/planner/core/preprocess.go [hunk 4]
```diff
@@ -1991,3 +1993,59 @@ func (p *preprocessor) skipLockMDL() bool {
 	// skip lock mdl for ANALYZE statement.
 	return p.flag&inImportInto > 0 || p.flag&inAnalyze > 0
 }
+
+// aliasChecker is used to check the alias of the table in delete statement.
+//
+//	for example: delete tt1 from t1 tt1,(select max(id) id from t2)tt2 where tt1.id<=tt2.id
+//	  `delete tt1```` will be transfer to `delete current_database.t1` in default.
```
Comment (tangenta) [inline pkg/planner/core/preprocess.go:2000]:
```suggestion
//	  `delete tt1` will be transfer to `delete current_database.t1` in default.
```

**Review by tangenta — APPROVED** [review]
