### PR TITLE
ddl: add `addingDefinition` field for adding partition replica check

### LINKED ISSUE #18496: DDL: the query to the new added partition which is in it's replica process
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1: make a table with tiflash replica availble
2: add the new table partition to it
3: query to the new added partition

### 2. What did you expect to see? (Required)
the finish of adding partiton DDL should take tiflash replica check into consideration.

### 3. What did you see instead (Required)
None

### 5. Root Cause Analysis
the finish of adding partiton DDL doesn't take tiflash replica check into consideration.

### PR DESCRIPTION
**Pull request by AilinKid**
Signed-off-by: AilinKid <314806019@qq.com>

### What problem does this PR solve?

Issue Number: close #18496 

Problem Summary: 
It is reported that if a table is in tiflash replica mode and it's available state is `true`, the new added partition will cause query block because the new added partition hasn't been replicated completely.

That's why we wanna add a mid state for adding partiton. In the delete-only state, the `DDL` owner will check for the new added partition's replica info. Once it is completed, then make it public.

### What is changed and how it works?

What's Changed:
1:  add a mid state (delete only for add partiton)
2:  add the rollback logic for add partition 

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Breaking backward compatibility

### Release note 

- add delete only state for add partition replica check
- this pr will cause compatibility problem, when do DDL action in rolling upgrade

### CODE REVIEW

**Comment by solotzg** [comment]
Is there any log for middle state changing?

**Comment by JaySon-Huang** [comment]
@AilinKid  You can also close this earlier issue: https://github.com/pingcap/tidb/issues/18275

**Comment by AilinKid** [comment]
> @AilinKid You can also close this earlier issue: #18275

thx, got

**Comment by AilinKid** [comment]
> Is there any log for middle state changing?

yes we did, https://github.com/pingcap/tidb/pull/18495/files#diff-71209e5c7ffc793d7bf8779373b48098R1009

**Comment by solotzg** [comment]
> > Is there any log for middle state changing?
> 
> yes we did, `logutil.Logger(ctx).Info("[ddl] partition replica check failed", zap.Time("check time", time.Now()))`
> every time it check failed, it will wait 1/2 lease ( 5 second / 2 ) to recheck, user can cancel it by `admin cancel ddl job id` if thinking it costs too much time...

How can we know whether a partition is in middle state? I can't get useful information from log.

**Comment by AilinKid** [comment]
> > > Is there any log for middle state changing?
> > 
> > 
> > yes we did, `logutil.Logger(ctx).Info("[ddl] partition replica check failed", zap.Time("check time", time.Now()))`
> > every time it check failed, it will wait 1/2 lease ( 5 second / 2 ) to recheck, user can cancel it by `admin cancel ddl job id` if thinking it costs too much time...
> 
> How can we know whether a partition is in middle state? I can't get useful information from log.

good, I will add it

File: ddl/table.go [hunk 1]
```diff
@@ -1002,18 +1009,43 @@ func checkPartitionReplica(partDefPointers []*model.PartitionDefinition, d *ddlC
 				job.State = model.JobStateCancelled
 				return needWait, errors.Trace(err)
 			}
-			if len(regionState.PendingPeers) == 0 && len(regionState.Meta.Peers) > 0 {
+			tiFlashPeerCount := checkTiFlashPeerStore(stores, regionState.Meta.Peers)
```
Comment (zimulala) [inline ddl/table.go:1012]: s/tiFlashPeerCount/tiflashPeerCount ?

File: ddl/table.go [hunk 2]
```diff
@@ -14,13 +14,18 @@
 package ddl
 
 import (
+	"context"
 	"fmt"
+
+	"go.uber.org/zap"
```
Comment (zimulala) [inline ddl/table.go:20]: Please put it in the right place.

File: ddl/table.go [hunk 3]
```diff
@@ -948,56 +957,192 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+			if tiFlashPeerCount > 0 {
+				continue
+			} else {
+				needWait = true
+				logutil.Logger(ctx).Info("[ddl] partition replica check failed in delete-only ddl state", zap.Int64("pid", pd.ID), zap.Uint64("wait region ID", region.Id), zap.Uint64("tiflash peer nums", tiFlashPeerCount), zap.Time("check time", time.Now()))
+				return needWait, nil
+			}
+		}
 	}
+	logutil.Logger(ctx).Info("[ddl] partition replica checks ok in delete-only ddl state")
```
Comment (zimulala) [inline ddl/table.go:1024]: s/ddl/DDL

**Comment by AilinKid** [comment]
@PTAL @djshow832 @tangenta

File: ddl/table.go [hunk 4]
```diff
@@ -948,56 +956,191 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+				return needWait, errors.Trace(err)
+			}
+			tiflashPeerCount := checkTiFlashPeerStore(stores, regionState.Meta.Peers)
+			// It's unnecessary to wait all tiflash peer to be replicated.
+			// Here only make sure that tiflash peer count > 0 (at least one).
+			if tiflashPeerCount > 0 {
+				continue
+			}
+			needWait = true
+			logutil.Logger(ctx).Info("[DDL] partition replica check failed in delete-only ddl state", zap.Int64("pid", pd.ID), zap.Uint64("wait region ID", region.Id), zap.Uint64("tiflash peer nums", tiflashPeerCount), zap.Time("check time", time.Now()))
```
Comment (zimulala) [inline ddl/table.go:1018]:
```suggestion
			logutil.BgLogger().Info("[ddl] partition replicas check failed in delete-only DDL state", zap.Int64("pID", pd.ID), zap.Uint64("wait region ID", region.Id), zap.Uint64("tiflash peer nums", tiflashPeerCount), zap.Time("check time", time.Now()))
```

File: ddl/table.go [hunk 5]
```diff
@@ -948,56 +956,191 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+			return needWait, nil
+		}
 	}
+	logutil.Logger(ctx).Info("[DDL] partition replica checks ok in delete-only ddl state")
```
Comment (zimulala) [inline ddl/table.go:1022]:
```suggestion
	logutil.BgLogger().Info("[ddl] partition replicas check ok in delete-only DDL state")
```

File: ddl/table.go [hunk 6]
```diff
@@ -948,56 +956,191 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+		ver, err = updateVersionAndTableInfoWithCheck(t, job, tblInfo, originalState != partDefPointers[0].State)
+	case model.StateDeleteOnly:
+		// delete only -> public
+		// Here need do some tiflash replica complement check.
+		if tblInfo.TiFlashReplica != nil && tblInfo.TiFlashReplica.Available {
+			// For available state, the new added partition should wait it's replica to
+			// be finished. Otherwise the query to this partition will be blocked.
+			needWait, err := checkPartitionReplica(partDefPointers, d, job)
+			if err != nil {
+				return ver, err
```
Comment (zimulala) [inline ddl/table.go:1103]: Please add a trace to this error.

File: ddl/table.go [hunk 7]
```diff
@@ -948,56 +956,191 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
 
-	err = checkAddPartitionValue(tblInfo, partInfo)
-	if err != nil {
-		job.State = model.JobStateCancelled
-		return ver, errors.Trace(err)
+func checkTiFlashPeerStore(stores []*metapb.Store, peers []*metapb.Peer) (tiFlashPeerCount uint64) {
+	for _, peer := range peers {
+		for _, store := range stores {
+			if peer.StoreId == store.Id && storeHasEngineTiFlashLabel(store) {
+				tiFlashPeerCount++
```
Comment (zimulala) [inline ddl/table.go:1030]: We only need to check if one store has tiflash label？Then we can remove the check of https://github.com/pingcap/tidb/pull/18495/files#diff-71209e5c7ffc793d7bf8779373b48098R1014 and reduce traversal.

File: ddl/table.go [hunk 8]
```diff
@@ -948,56 +956,191 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+			// For available state, the new added partition should wait it's replica to
+			// be finished. Otherwise the query to this partition will be blocked.
+			needWait, err := checkPartitionReplica(partDefPointers, d, job)
+			if err != nil {
+				return ver, err
+			}
+			if needWait {
+				// The new added partition hasn't been replicated.
+				// Do nothing to the job this time, wait next worker round.
+				time.Sleep(tiFlashCheckTiDBHttpAPIInterval / 2)
```
Comment (zimulala) [inline ddl/table.go:1108]: If we need to do `tiFlashCheckTiDBHttpAPIInterval / 2`, why not set `tiFlashCheckTiDBHttpAPIInterval=2500ms` directly?

File: ddl/table.go [hunk 9]
```diff
@@ -948,56 +956,191 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
 	}
-	err = checkAddPartitionTooManyPartitions(uint64(len(tblInfo.Partition.Definitions) + len(partInfo.Definitions)))
-	if err != nil {
-		job.State = model.JobStateCancelled
-		return ver, errors.Trace(err)
+	for _, pd := range partDefPointers {
+		startKey, endKey := tablecodec.GetTableHandleKeyRange(pd.ID)
+		regions, _, err := pdCli.ScanRegions(ctx, startKey, endKey, -1)
+		if err != nil {
+			job.State = model.JobStateCancelled
```
Comment (zimulala) [inline ddl/table.go:1000]: If we cancel this job here, it seems this partition is added and the schema state is delete-only. I think we need roll back.

File: ddl/rollingback.go [hunk 10]
```diff
@@ -237,11 +237,26 @@ func rollingbackAddIndex(w *worker, d *ddlCtx, t *meta.Meta, job *model.Job, isP
...
+	// partDefPointers' len = 0 means the job hasn't reached the delete-only state.
+	if len(partDefPointers) == 0 {
+		job.State = model.JobStateCancelled
+		return ver, errCancelledDDLJob
+	}
+	partNames := make([]string, 0, len(partDefPointers))
+	for _, pd := range partDefPointers {
+		partNames = append(partNames, pd.Name.L)
+	}
+	job.Args = []interface{}{partNames}
```
Comment (zimulala) [inline ddl/rollingback.go:254]: I  think we need to rollback the `tableInfo`.

File: ddl/partition.go [hunk 11]
```diff
@@ -131,6 +131,8 @@ func buildHashPartitionDefinitions(ctx sessionctx.Context, s *ast.CreateTableStm
 			defs[i].Name = def.Name
 			defs[i].Comment, _ = def.Comment()
 		}
+		// For create table statement, the created partition definition in tableInfo should be with public state.
+		defs[i].State = model.StatePublic
```
[the remark this answers is not in the document]
Comment (AilinKid) [reply ddl/partition.go:135]: when build table with columns, the column state will be set to public, onCreateTable only care for the tableInfo's state change is ok.  Refer ddl_api.297L

[the remark this answers is not in the document]
Comment (zimulala) [reply ddl/partition.go:135]: Got it.

File: ddl/table.go [hunk 12]
```diff
@@ -948,56 +956,191 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
 	if err != nil {
 		job.State = model.JobStateCancelled
-		return ver, errors.Trace(err)
+		return nil, nil, nil, errors.Trace(err)
+	}
+	partDefPointers := make([]*model.PartitionDefinition, 0, len(partInfo.Definitions))
+	for _, pd := range partInfo.Definitions {
+		partitionDefInMeta := tblInfo.FindPartitionDefinitionByName(pd.Name.L)
+		if partitionDefInMeta != nil {
+			if partitionDefInMeta.State == model.StatePublic {
```
[the remark this answers is not in the document]
Comment (AilinKid) [reply ddl/table.go:975]: good catch

File: ddl/table.go (hunk 9 above)
Comment (AilinKid) [reply ddl/table.go]: I has add `convertAddTablePartitionJob2RollbackJob` to change the job state to rollingback. This func will change the job's args and next round it will fall into the drop partiton process.

File: ddl/rollingback.go (hunk 10 above)
Comment (AilinKid) [reply ddl/rollingback.go:254]: the drop partition action will be done later

File: ddl/table.go [hunk 13]
```diff
@@ -948,56 +956,189 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
-		job.State = model.JobStateCancelled
-		return ver, errors.Trace(err)
+	for _, pd := range partDefPointers {
+		startKey, endKey := tablecodec.GetTableHandleKeyRange(pd.ID)
+		regions, _, err := pdCli.ScanRegions(ctx, startKey, endKey, -1)
+		if err != nil {
+			return needWait, errors.Trace(err)
+		}
+		// For every region in the partition, if it has some corresponding peers and
+		// no pending peers, that means the replication has completed.
```
Comment (djshow832) [inline ddl/table.go:1002]: Why not query it from tableinfo?

File: server/http_handler.go [hunk 14]
```diff
@@ -713,6 +713,7 @@ type tableFlashReplicaInfo struct {
 	ReplicaCount   uint64   `json:"replica_count"`
 	LocationLabels []string `json:"location_labels"`
 	Available      bool     `json:"available"`
+	Priority       bool     `json:"priority"`
```
Comment (djshow832) [inline server/http_handler.go:716]: Where is it used?

File: ddl/rollingback.go [hunk 15]
```diff
@@ -236,12 +236,31 @@ func rollingbackAddIndex(w *worker, d *ddlCtx, t *meta.Meta, job *model.Job, isP
...
+	// partDefPointers' len = 0 means the job hasn't reached the delete-only state.
+	if len(partDefPointers) == 0 {
+		job.State = model.JobStateCancelled
+		return ver, errors.Trace(otherwiseErr)
+	}
+	partNames := make([]string, 0, len(partDefPointers))
+	for _, pd := range partDefPointers {
+		partNames = append(partNames, pd.Name.L)
+	}
+	job.Args = []interface{}{partNames}
```
[the remark this answers is not in the document]
Comment (AilinKid) [reply ddl/rollingback.go:254]: It's much clear than it before...

File: server/http_handler.go (hunk 14 above)
Comment (AilinKid) [reply server/http_handler.go]: addressed

File: ddl/table.go (hunk 13 above)
Comment (AilinKid) [reply ddl/table.go:1002]: fiflash state machine is same to tikv state machine, they will report to PD

File: ddl/table.go [hunk 16]
```diff
@@ -14,13 +14,16 @@
 package ddl
```
Comment (djshow832) [inline ddl/table.go:14]: The privileges of so many files are changed.

File: ddl/table.go [hunk 17]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
 	if err != nil {
 		job.State = model.JobStateCancelled
-		return ver, errors.Trace(err)
+		return nil, nil, nil, errors.Trace(err)
+	}
+	partDefPointers := make([]*model.PartitionDefinition, 0, len(partInfo.Definitions))
+	for _, pd := range partInfo.Definitions {
+		partitionDefInMeta := tblInfo.FindPartitionDefinitionByName(pd.Name.L)
+		if partitionDefInMeta != nil {
+			if partitionDefInMeta.State == model.StatePublic {
```
Comment (djshow832) [inline ddl/table.go:975]: What if it is trying to rollback and one partition is in public?

File: ddl/table.go [hunk 18]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+		if label.Key == "engine" && label.Value == "tiflash" {
+			return true
+		}
 	}
+	return false
+}
 
-	updatePartitionInfo(partInfo, tblInfo)
-	ver, err = updateVersionAndTableInfo(t, job, tblInfo, true)
+// TODO: It may have the issue when two clients concurrently add partitions to a table.
```
Comment (djshow832) [inline ddl/table.go:1043]: DDL is serial, why would it happen?

File: ddl/table.go [hunk 19]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+func onAddTablePartition(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int64, _ error) {
```
Comment (djshow832) [inline ddl/table.go:1044]: I think it should be moved to `partition.go`.

File: ddl/table.go [hunk 20]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+		err = checkAddPartitionNameUnique(tblInfo, partInfo)
+		if err != nil {
+			job.State = model.JobStateCancelled
+			return ver, errors.Trace(err)
+		}
+		partDefPointers = updatePartitionInfo(partInfo, tblInfo)
+	}
+
+	originalState := partDefPointers[0].State
+	switch partDefPointers[0].State {
```
Comment (djshow832) [inline ddl/table.go:1083]: Why not check `job.SchemaState`?

File: ddl/table.go [hunk 21]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+				// Do nothing to the job this time, wait next worker round.
+				time.Sleep(tiflashCheckTiDBHttpAPIHalfInterval)
+				return ver, nil
+			}
+		}
+
+		// For normal table, change the state to public directly.
+		for _, pdDef := range partDefPointers {
+			pdDef.State = model.StatePublic
+		}
```
Comment (djshow832) [inline ddl/table.go:1113]: What about `job.State`?

File: ddl/table.go [hunk 22]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
 	parInfo.Definitions = make([]model.PartitionDefinition, 0, len(newDefs)+len(oldDefs))
 	parInfo.Definitions = append(parInfo.Definitions, oldDefs...)
 	parInfo.Definitions = append(parInfo.Definitions, newDefs...)
 	tblInfo.Partition.Definitions = parInfo.Definitions
+	partDefPointers := make([]*model.PartitionDefinition, 0, len(partitionInfo.Definitions))
+	for _, pdAdded := range partitionInfo.Definitions {
+		pdInMetaPointer := tblInfo.FindPartitionDefinitionByName(pdAdded.Name.L)
+		partDefPointers = append(partDefPointers, pdInMetaPointer)
+	}
+	return partDefPointers
```
Comment (djshow832) [inline ddl/table.go:1140]: This part should be moved out of the function. It has nothing to do with updating partition information.

File: ddl/table.go (hunk 18 above)
Comment (AilinKid) [reply ddl/table.go:1043]: It is not my code

File: ddl/table.go (hunk 21 above)
Comment (AilinKid) [reply ddl/table.go:1113]: job state change in `FinishTableJob`

File: ddl/table.go (hunk 22 above)
Comment (AilinKid) [reply ddl/table.go:1140]: It is convinent to return those new added partion pointer in the tableInfo.

File: ddl/table.go (hunk 20 above)
Comment (AilinKid) [reply ddl/table.go:1083]: they are the same state

File: ddl/table.go (hunk 17 above)
Comment (AilinKid) [reply ddl/table.go:975]: if one is public
1: you job is cancelled early in ddl_api check.
2: It has passed the early check and waited int the queue, in this interval, the same name partition has been added to public. So when this job get its turn to run, it's will failed here and cancelled directly. No rollback logic.

File: ddl/table.go (hunk 16 above)
Comment (AilinKid) [reply ddl/table.go:14]: I don't change anything

File: ddl/table.go (hunk 19 above)
Comment (AilinKid) [reply ddl/table.go:1044]: it's same as what it was

File: ddl/table.go (hunk 18 above)
Comment (djshow832) [reply ddl/table.go:1043]: Is this comment right?

File: ddl/table.go (hunk 19 above)
Comment (djshow832) [reply ddl/table.go:1044]: But it should be moved.

File: ddl/table.go (hunk 22 above)
Comment (djshow832) [reply ddl/table.go:1140]: This reason doesn't make sense.

File: ddl/table.go [hunk 23]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+			}
+			// Collect the partition definition pointer in tableInfo for future state change.
+			partDefPointers = append(partDefPointers, partitionDefInMeta)
+		}
 	}
+	return tblInfo, partInfo, partDefPointers, nil
+}
 
-	tblInfo, err := getTableInfoAndCancelFaultJob(t, job, job.SchemaID)
+func checkPartitionReplica(partDefPointers []*model.PartitionDefinition, d *ddlCtx, job *model.Job) (needWait bool, err error) {
```
Comment (crazycs520) [inline ddl/table.go:988]: `job` parameter is useless?

File: ddl/table.go [hunk 24]
```diff
@@ -948,56 +956,188 @@ func updateVersionAndTableInfo(t *meta.Meta, job *model.Job, tblInfo *model.Tabl
...
+		// none -> delete only
+		job.SchemaState = model.StateDeleteOnly
+		for _, pdDef := range partDefPointers {
+			pdDef.State = model.StateDeleteOnly
+		}
+		ver, err = updateVersionAndTableInfoWithCheck(t, job, tblInfo, originalState != partDefPointers[0].State)
+	case model.StateDeleteOnly:
+		// delete only -> public
+		// Here need do some tiflash replica complement check.
+		if tblInfo.TiFlashReplica != nil && tblInfo.TiFlashReplica.Available {
```
Comment (crazycs520) [inline ddl/table.go:1094]: Samely, if `tblInfo.TiFlashReplica == nil || tblInfo.TiFlashReplica.Available == false`, then the `delete-only` state is redandent? May be you can add a TODO here to optimize this later?

File: ddl/partition.go [hunk 25]
```diff
@@ -155,6 +157,8 @@ func buildRangePartitionDefinitions(ctx sessionctx.Context, s *ast.CreateTableSt
 			piDef.LessThan = append(piDef.LessThan, buf.String())
 			buf.Reset()
 		}
+		// For create table statement, the created partition definition in tableInfo should be with public state.
+		piDef.State = model.StatePublic
```
Comment (crazycs520) [inline ddl/partition.go:161]: Currently even if the partition state is `delete-only`, the partition is also visible to user and the user can insert to it;

here is an example:

1. execute `alter table t add partition (partition p2 values less than (30));` in session 1;

2. in session 2:

```sql
test> show create table t;
+-------+-------------------------------------------------------------+
| Table | Create Table                                                |
+-------+-------------------------------------------------------------+
| t     | CREATE TABLE `t` (                                          |
|       |   `a` bigint(64) DEFAULT NULL,                              |
|       |   `b` bigint(64) DEFAULT NULL,                              |
|       |   KEY `idx` (`a`,`b`)                                       |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
|       | PARTITION BY RANGE ( `a` ) (                                |
|       |   PARTITION `p0` VALUES LESS THAN (3),                      |
|       |   PARTITION `p1` VALUES LESS THAN (6),                      |
|       |   PARTITION `p2` VALUES LESS THAN (30) # p2 should not be visible                     |
|       | )                                                           |
+-------+-------------------------------------------------------------+
1 row in set
Time: 0.011s
test> insert into t values (7,7); # should be faild.
Query OK, 1 row affected
Time: 0.002s
test> admin show ddl jobs;  # as you can see, the add partition job does not finish, but is is already visible to the user.
+--------+---------+------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE      | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | START_TIME          | END_TIME            | STATE   |
+--------+---------+------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------+
| 74     | test    | t          | add partition | delete only  | 1         | 67       | 0         | 2020-07-24 20:24:24 | <null>              | running |
...
```

Comment (AilinKid) [reply ddl/partition.go:161]: yes，we have noticed that, in the same issue above, Song Lingyu has done the hidden work https://github.com/pingcap/tidb/pull/18585

File: ddl/table.go (hunk 24 above)
Comment (AilinKid) [reply ddl/table.go:1094]: Yes, good, nice catch~

File: ddl/partition.go (hunk 25 above)
Comment (crazycs520) [reply ddl/partition.go:161]: BTW, instead of add`state` in `model.PartitionDefinition`, I prefer to add a `AddingDefinitions` in `model.PartitionInfo`. 

Maintain the partition state is a mental burden, if I forgot to check the partition status, It may cause a bug.

File: ddl/table.go (hunk 23 above)
Comment (AilinKid) [reply ddl/table.go]: good catch

File: ddl/partition.go (hunk 25 above)
Comment (AilinKid) [reply ddl/partition.go:387]: Nice idea, some way like the column change, the related column!
How about let it be now? @imtbkcat what do you think, does check cost it too much?

File: ddl/table.go (hunk 19 above)
Comment (AilinKid) [reply ddl/table.go]: addressed

File: ddl/table.go (hunk 18 above)
Comment (AilinKid) [reply ddl/table.go]: removed

File: ddl/table.go (hunk 22 above)
Comment (AilinKid) [reply ddl/table.go]: I think it's ok here

File: ddl/partition.go (hunk 25 above)
Comment (crazycs520) [reply ddl/partition.go:387]: @zimulala @bb7133 How about you?

Comment (AilinKid) [reply ddl/partition.go:387]: Argument:
if we add `addingDefinitions`, that two ways:
1: let ddl add partition write directly to this field, and return. then wait for tiflash HTTP post to move it to `normalDefinition`.  shortage: DDL finish doesn't mean the partition is ready
2: let ddl add partition write to this field at the first stage, then check PD for whether the tiflash replica is ok then move it to `normalDefinition`, at last return the ddl.  shortage: this way still need two-stage(without state change) to do this, quite like what this PR looks like, just eliminating the state change and using `addingDefinition`.

File: ddl/table.go [hunk 26]
```diff
@@ -1091,10 +1091,11 @@ func onAddTablePartition(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int64, _
 	case model.StateDeleteOnly:
 		// delete only -> public
 		// Here need do some tiflash replica complement check.
+		// Todo: if a table is with no TiFlashReplica or it is not available, the delete-only state can be eliminated.
```
Comment (zimulala) [inline ddl/table.go]:
```suggestion
		// TODO: If a table is with no TiFlashReplica or it is not available, the delete-only state can be eliminated.
```

File: ddl/partition.go (hunk 25 above)
Comment (djshow832) [reply ddl/partition.go:387]: I agree with @crazycs520

File: ddl/table.go [hunk 27]
```diff
@@ -30,12 +33,17 @@ import (
...
+	"github.com/pingcap/tidb/store/tikv"
 	"github.com/pingcap/tidb/table"
 	"github.com/pingcap/tidb/table/tables"
 	"github.com/pingcap/tidb/tablecodec"
 	"github.com/pingcap/tidb/util/gcutil"
+	"github.com/pingcap/tidb/util/logutil"
+	"go.uber.org/zap"
 )
 
+const tiflashCheckTiDBHttpAPIHalfInterval = 2500 * time.Millisecond
```
[the remark this answers is not in the document]
Comment (AilinKid) [reply ddl/table.go]: thx

File: ddl/partition.go (hunk 25 above)
Comment (crazycs520) [reply ddl/partition.go:387]: I prefer this
> 2: let ddl add partition write to this field at the first stage, then check PD for whether the tiflash replica is ok then move it to normalDefinition, at last return the ddl. shortage: this way still need two-stage(without state change) to do this, quite like what this PR looks like, just eliminating the state change and using addingDefinition.

File: ddl/ddl_worker_test.go [hunk 28]
```diff
@@ -604,6 +612,9 @@ func (s *testDDLSuite) TestCancelJob(c *C) {
 		}
 		// This hook only valid for the related test job.
 		// This is use to avoid parallel test fail.
+		if job.SchemaState == model.StateReplicaOnly {
+			fmt.Println(1)
```
Comment (crazycs520) [inline ddl/ddl_worker_test.go:616]: ?

Comment (AilinKid) [reply ddl/ddl_worker_test.go:616]: sorry，it's for debugging

File: ddl/partition.go [hunk 29]
```diff
@@ -33,16 +36,239 @@ import (
...
+
+	tblInfo, partInfo, addingDefinitions, err := checkAddPartition(t, job)
+	if err != nil {
+		return ver, err
+	}
+
+	// addingDefinition's len is 0 meaning the job is in the initial state of add partition.
+	// Here should use partInfo from job directly and do some check action.
+	if len(addingDefinitions) == 0 {
+		err = checkAddPartitionTooManyPartitions(uint64(len(tblInfo.Partition.Definitions) + len(partInfo.Definitions)))
```
Comment (crazycs520) [inline ddl/partition.go:89]: move line 89 ~ 105 after line 111, simply use `job.SchemaState == model.StateNone` to instead of the initial state of add partition?

File: ddl/partition.go [hunk 30]
```diff
@@ -33,16 +36,239 @@ import (
...
+	tblInfo.Partition.AddingDefinitions = append(tblInfo.Partition.AddingDefinitions, newDefs...)
+}
+
+// rollbackAddingPartitionInfo remove the `addingDefinitions` in the tableInfo.
+func rollbackAddingPartitionInfo(tblInfo *model.TableInfo) []int64 {
+	physicalTableIDs := make([]int64, 0, len(tblInfo.Partition.AddingDefinitions))
+	for _, one := range tblInfo.Partition.AddingDefinitions {
+		physicalTableIDs = append(physicalTableIDs, one.ID)
+	}
+	tblInfo.Partition.AddingDefinitions = tblInfo.Partition.AddingDefinitions[:0]
```
Comment (crazycs520) [inline ddl/partition.go:178]:
```suggestion
	tblInfo.Partition.AddingDefinitions = nil
```

File: ddl/partition.go [hunk 31]
```diff
@@ -33,16 +36,239 @@ import (
...
+
+// updatePartitionInfo merge `addingDefinitions` into `Definitions` in the tableInfo.
+func updatePartitionInfo(tblInfo *model.TableInfo) {
+	parInfo := &model.PartitionInfo{}
+	oldDefs, newDefs := tblInfo.Partition.Definitions, tblInfo.Partition.AddingDefinitions
+	parInfo.Definitions = make([]model.PartitionDefinition, 0, len(newDefs)+len(oldDefs))
+	parInfo.Definitions = append(parInfo.Definitions, oldDefs...)
+	parInfo.Definitions = append(parInfo.Definitions, newDefs...)
+	tblInfo.Partition.Definitions = parInfo.Definitions
+	tblInfo.Partition.AddingDefinitions = tblInfo.Partition.AddingDefinitions[:0]
```
Comment (crazycs520) [inline ddl/partition.go:162]:
```suggestion
	tblInfo.Partition.AddingDefinitions = nil
```

File: ddl/partition.go (hunk 29 above)
Comment (AilinKid) [reply ddl/partition.go:89]: good

**Comment by solotzg** [comment]
lgtm

File: go.mod [hunk 32]
```diff
@@ -66,3 +66,5 @@ require (
 )
 
 go 1.13
+
+replace github.com/pingcap/parser => github.com/ailinkid/parser v0.0.0-20200727081704-30ae78e3ace2
```
Comment (solotzg) [inline go.mod:70]: Fix this. This pr should be picked into release-4.0.

Comment (AilinKid) [reply go.mod:70]: ok

File: ddl/partition.go [hunk 33]
```diff
@@ -33,16 +36,236 @@ import (
...
+				return needWait, errors.Trace(err)
+			}
+			tiflashPeerAtLeastOne := checkTiFlashPeerStoreAtLeastOne(stores, regionState.Meta.Peers)
+			// It's unnecessary to wait all tiflash peer to be replicated.
+			// Here only make sure that tiflash peer count > 0 (at least one).
+			if tiflashPeerAtLeastOne {
+				continue
+			}
+			needWait = true
+			logutil.BgLogger().Info("[ddl] partition replicas check failed in delete-only DDL state", zap.Int64("pID", pd.ID), zap.Uint64("wait region ID", region.Id), zap.Bool("tiflash peer at least one", tiflashPeerAtLeastOne), zap.Time("check time", time.Now()))
```
Comment (djshow832) [inline ddl/partition.go:241]:
```suggestion
			logutil.BgLogger().Info("[ddl] partition replicas check failed in replica-only DDL state", zap.Int64("pID", pd.ID), zap.Uint64("wait region ID", region.Id), zap.Bool("tiflash peer at least one", tiflashPeerAtLeastOne), zap.Time("check time", time.Now()))
```

File: ddl/partition.go [hunk 34]
```diff
@@ -33,16 +36,236 @@ import (
...
+			return needWait, nil
+		}
+	}
+	logutil.BgLogger().Info("[ddl] partition replicas check ok in delete-only DDL state")
```
Comment (djshow832) [inline ddl/partition.go:245]:
```suggestion
	logutil.BgLogger().Info("[ddl] partition replicas check ok in replica-only DDL state")
```

File: ddl/db_test.go [hunk 35]
```diff
@@ -1291,6 +1291,8 @@ func (s *testDBSuite1) TestCancelAddTableAndDropTablePartition(c *C) {
 	}{
 		{model.ActionAddTablePartition, model.JobStateNone, model.StateNone, true},
 		{model.ActionDropTablePartition, model.JobStateNone, model.StateNone, true},
+		// Add table partition now can be cancelled in DeleteOnly state.
```
Comment (djshow832) [inline ddl/db_test.go:1294]:
```suggestion
		// Add table partition now can be cancelled in ReplicaOnly state.
```

File: ddl/rollingback.go [hunk 36]
```diff
@@ -236,12 +236,31 @@ func rollingbackAddIndex(w *worker, d *ddlCtx, t *meta.Meta, job *model.Job, isP
 	return
 }
 
-func rollingbackAddTablePartition(t *meta.Meta, job *model.Job) (ver int64, err error) {
-	_, err = getTableInfoAndCancelFaultJob(t, job, job.SchemaID)
+func convertAddTablePartitionJob2RollbackJob(t *meta.Meta, job *model.Job, otherwiseErr error) (ver int64, err error) {
+	job.State = model.JobStateRollingback
+	tblInfo, _, addingDefinitions, err := checkAddPartition(t, job)
```
Comment (zimulala) [inline ddl/rollingback.go:241]: When `convertAddTablePartitionJob2RollbackJob` is called in `onAddTablePartition`, I think we needn't to call `checkAddPartition `.

Comment (AilinKid) [reply ddl/rollingback.go]: great！addressed
