### PR TITLE
br: skip update stats cache for br

### LINKED ISSUE #47596: it's too slow for br to update stats cache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. snapshot restore (10x tables with 100 partition for each)

### 2. What did you expect to see? (Required)
quickly done.
### 3. What did you see instead (Required)
too slow
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #47596 

Problem Summary:
it's too slow for br to update stats cache. Besides, we can skip it.
### What is changed and how it works?
Skip it
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Skip update stats cache of the br client to speed up the snapshot restore.
```

### CODE REVIEW

**Review by BornChanger — APPROVED** [review]
Please add explanation in the release notes of restore.

File: statistics/handle/dump.go [hunk 1]
```diff
@@ -282,6 +282,9 @@ func (h *Handle) LoadStatsFromJSON(ctx context.Context, is infoschema.InfoSchema
 			}
 		}
 	}
+	if skipUpdate {
+		return nil
+	}
```
Comment (YuJuncen) [inline statistics/handle/dump.go:287]: I will prefer just extract all the codes before to a function (Say, `LoadStatsFromJSONNoUpdate`), and call this function at the origin `LoadStatsFromJSON`. So the new function signature can be kept unchanged hence there is no need to modify so lines...

Comment (Leavrth) [reply statistics/handle/dump.go:287]: LGTM

**Review by YuJuncen — APPROVED** [review]
