### PR TITLE
executor: solve bug of copy joined tuples after inline projection

### LINKED ISSUE #15316: planner: Pushing down conditions error for outer joins
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
CREATE TABLE `W` (
  `col_varchar_10_latin1_not_null` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_varchar_1024_utf8_not_null` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `col_varchar_1024_utf8_key` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `col_varchar_1024_latin1_key` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `col_int_not_null` int(11) NOT NULL,
  `col_varchar_1024_latin1_not_null_key` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_varchar_1024_latin1` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `col_varchar_10_utf8_not_null` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `col_varchar_1024_latin1_not_null` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_varchar_10_latin1_not_null_key` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_int_key` int(11) DEFAULT NULL,
  `col_varchar_10_utf8_not_null_key` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `col_varchar_1024_utf8_not_null_key` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `col_varchar_1024_utf8` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `col_varchar_10_utf8` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `col_varchar_10_utf8_key` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_varchar_10_latin1_key` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `col_int_not_null_key` int(11) NOT NULL,
  `col_varchar_10_latin1` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `col_int` int(11) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_varchar_1024_utf8_key` (`col_varchar_1024_utf8_key`(333)),
  KEY `col_varchar_1024_latin1_key` (`col_varchar_1024_latin1_key`(1000)),
  KEY `col_varchar_1024_latin1_not_null_key` (`col_varchar_1024_latin1_not_null_key`(1000)),
  KEY `col_varchar_10_latin1_not_null_key` (`col_varchar_10_latin1_not_null_key`),
  KEY `col_int_key` (`col_int_key`),
  KEY `col_varchar_10_utf8_not_null_key` (`col_varchar_10_utf8_not_null_key`),
  KEY `col_varchar_1024_utf8_not_null_key` (`col_varchar_1024_utf8_not_null_key`(333)),
  KEY `col_varchar_10_utf8_key` (`col_varchar_10_utf8_key`),
  KEY `col_varchar_10_latin1_key` (`col_varchar_10_latin1_key`),
  KEY `col_int_not_null_key` (`col_int_not_null_key`)
) ENGINE=MyISAM AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `W` WRITE;
/*!40000 ALTER TABLE `W` DISABLE KEYS */;
INSERT INTO `W` VALUES ('k','v','u','y',7,'t','g','y','j','w',NULL,'s','m','b','f',NULL,1,'z',0,'r',4);
INSERT INTO `W` VALUES ('n','k','p',NULL,6,'e',NULL,'x','z','o',0,'k','j','a','w',NULL,2,'j',9,'p',3);
INSERT INTO `W` VALUES ('w','w','j','m',2,'t','a','g','w','r',2,'x','f','y','e','o',3,'x',9,'w',2);
INSERT INTO `W` VALUES ('u','z','a','g',7,'m','p','d','e','y',NULL,'x','z',NULL,NULL,NULL,4,'y',8,'x',5);
INSERT INTO `W` VALUES ('h','z','u','i',3,'z','z','r','g','s',2,'x','e','t',NULL,'j',5,'o',8,'x',8);
INSERT INTO `W` VALUES ('g','z',NULL,NULL,2,'y','f','v','u','t',7,'f','x','v',NULL,'j',6,'l',9,'u',6);
INSERT INTO `W` VALUES ('d','k','v',NULL,8,'w','v','q','q','u',5,'j','s','z','q','j',7,'g',0,'r',0);
INSERT INTO `W` VALUES ('y','i','j','c',2,'s','q','c','l','d',4,'j','j','w','m',NULL,8,'u',9,'a',7);
INSERT INTO `W` VALUES ('d','n','x','v',8,'q','q','s','j','y',9,'z','k','c','t',NULL,9,'d',7,'h',4);
INSERT INTO `W` VALUES ('e','n',NULL,'g',3,'e','q','d','g','y',4,'n','l','c','g',NULL,10,'a',4,NULL,7);
INSERT INTO `W` VALUES ('m','g','r','n',2,'c','w','n','e','s',NULL,'k','r','s',NULL,'h',11,'m',1,'c',0);
INSERT INTO `W` VALUES ('s','h','b','b',9,'l','p','z','q','r',0,'d','r','p','n','e',12,'m',6,'l',NULL);
INSERT INTO `W` VALUES ('g','o',NULL,'a',3,'t','n','a','n','g',3,'j','p','n','q','a',13,'e',0,'v',8);
INSERT INTO `W` VALUES ('x','s','i','z',5,'s','m','c','r','a',6,'l','x','s','q',NULL,14,'s',5,'y',7);
INSERT INTO `W` VALUES ('f','v','c','p',8,'b','j','r','v','d',1,'e','m',NULL,'p','n',15,NULL,6,'i',NULL);
INSERT INTO `W` VALUES ('x','m','i','y',0,'i','i','i','m','u',NULL,'v','q','g','r',NULL,16,NULL,6,'g',2);
INSERT INTO `W` VALUES ('n','c','l',NULL,0,'n','t','t','y','s',7,'t','y','a','l','g',17,'h',1,'c',9);
INSERT INTO `W` VALUES ('d','d','b',NULL,1,'z','c','m','y','l',8,'l','d','r','j','z',18,NULL,5,'i',7);
INSERT INTO `W` VALUES ('f','f','o','u',7,'b','r','x','x','z',NULL,'f','e','g','s','b',19,'o',3,'w',0);
INSERT INTO `W` VALUES ('h','s','g','j',6,'a','w','g','o','f',NULL,'t','h','h','c','k',20,'e',8,'x',NULL);
INSERT INTO `W` VALUES ('o','g',NULL,'p',5,'f','x','g','g','t',8,'i','m',NULL,'e',NULL,21,'o',9,'k',7);
INSERT INTO `W` VALUES ('o','i','x','v',0,'h','k','b','o','d',2,'k','g',NULL,'l','g',22,NULL,4,NULL,1);

CREATE TABLE `L` (
  `col_varchar_10_latin1` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `col_int_not_null` int(11) NOT NULL,
  `col_varchar_1024_latin1_not_null_key` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_varchar_10_latin1_not_null` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_varchar_10_latin1_not_null_key` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_varchar_1024_latin1_key` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `col_varchar_10_utf8_key` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `col_varchar_10_utf8` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `col_varchar_1024_utf8` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `col_varchar_1024_latin1` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `col_varchar_10_utf8_not_null` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `col_int_not_null_key` int(11) NOT NULL,
  `col_int_key` int(11) DEFAULT NULL,
  `col_varchar_1024_utf8_not_null_key` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_varchar_1024_utf8_key` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `col_int` int(11) DEFAULT NULL,
  `col_varchar_10_utf8_not_null_key` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `col_varchar_1024_utf8_not_null` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `col_varchar_1024_latin1_not_null` varchar(1024) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `col_varchar_10_latin1_key` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_varchar_1024_latin1_not_null_key` (`col_varchar_1024_latin1_not_null_key`),
  KEY `col_varchar_10_latin1_not_null_key` (`col_varchar_10_latin1_not_null_key`),
  KEY `col_varchar_1024_latin1_key` (`col_varchar_1024_latin1_key`),
  KEY `col_varchar_10_utf8_key` (`col_varchar_10_utf8_key`),
  KEY `col_int_not_null_key` (`col_int_not_null_key`),
  KEY `col_int_key` (`col_int_key`),
  KEY `col_varchar_1024_utf8_not_null_key` (`col_varchar_1024_utf8_not_null_key`),
  KEY `col_varchar_1024_utf8_key` (`col_varchar_1024_utf8_key`),
  KEY `col_varchar_10_utf8_not_null_key` (`col_varchar_10_utf8_not_null_key`),
  KEY `col_varchar_10_latin1_key` (`col_varchar_10_latin1_key`)
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `L` VALUES ('j',3,'i','j','u','x','s','c','r',NULL,'o',1,3,'f',1,NULL,8,'i','a','i','w');
INSERT INTO `L` VALUES (NULL,8,'x','b','j','w','a',NULL,'f','b','b',9,3,'g',2,'f',NULL,'k','k','h',NULL);
INSERT INTO `L` VALUES ('q',2,'v','r','o',NULL,NULL,'m',NULL,'t','x',2,1,'n',3,NULL,8,'z','k','g','x');
INSERT INTO `L` VALUES (NULL,1,'f','x','b','l',NULL,'a','j',NULL,'d',5,NULL,'v',4,'v',0,'j','w','e',NULL);
INSERT INTO `L` VALUES (NULL,4,'z','h','n','m','b','n','k','m','w',4,NULL,'o',5,'e',NULL,'s','m','o',NULL);
INSERT INTO `L` VALUES ('t',2,'k','x','k','k','s','h',NULL,'l','t',0,5,'r',6,'v',9,'x','r','o','p');
INSERT INTO `L` VALUES ('y',2,'e','m','r','d','q','y','l','l','s',7,NULL,'b',7,'s',2,'j','r','f',NULL);
INSERT INTO `L` VALUES ('e',5,'t','h','k',NULL,NULL,'w','r','o','b',7,NULL,'b',8,'b',1,'i','n','f','m');
INSERT INTO `L` VALUES (NULL,6,'v','f','a','v','b','y','z','z','z',3,4,'a',9,'g',NULL,'f','i','y','m');
INSERT INTO `L` VALUES ('h',7,'z','w','l',NULL,'n','t','n','d','d',5,8,'v',10,'p',3,'w','o','p','m');
INSERT INTO `L` VALUES ('q',1,'j','n','v','v','y','q','w','w','p',0,5,'a',11,'k',NULL,'d','c','k','m');
INSERT INTO `L` VALUES ('w',9,'x','m','v',NULL,'q',NULL,'d','a','s',3,9,'q',12,'p',NULL,'t','h','x',NULL);
INSERT INTO `L` VALUES ('u',6,'h','s','k',NULL,NULL,'f','s','q','d',2,NULL,'i',13,'p',3,'z','p','q','z');
INSERT INTO `L` VALUES ('l',9,'r','s','e','u','b','z',NULL,'l','s',7,1,'r',14,'p',1,'a','y','f','j');
INSERT INTO `L` VALUES (NULL,7,'r','y','q','t',NULL,'a','x','m','i',8,9,'c',15,'c',7,'c','z','o','o');
INSERT INTO `L` VALUES ('c',0,'y','v','p','c','v',NULL,'k','q','e',1,5,'o',16,'d',NULL,'e','b','t','y');
INSERT INTO `L` VALUES ('e',9,'r','s','i','n','s','v','f','i','x',3,7,'e',17,'p',7,'p','n','m',NULL);
INSERT INTO `L` VALUES ('s',4,'c','j','s','j','j','t','f','t','r',2,1,'n',18,NULL,1,'p','f','u',NULL);
INSERT INTO `L` VALUES ('g',5,'t','j','b',NULL,'b','x','c','v','l',8,8,'a',19,NULL,0,'x','c','m','g');
INSERT INTO `L` VALUES ('p',6,'d','x','d','i','x','u','n','g','p',9,4,'h',20,NULL,6,'t','h','a',NULL);
INSERT INTO `L` VALUES ('s',0,'d','a','c','s','l',NULL,'k',NULL,'g',4,6,'m',21,'l',7,'b','q','a','s');
INSERT INTO `L` VALUES ('b',6,'i','c','d','l','a','o','a','x','l',8,8,'j',22,'u',9,'n','h','p','h');
INSERT INTO `L` VALUES ('u',1,'e','l','d','c','p','r','c',NULL,'j',4,1,'s',23,'f',3,'p','h','u','k');
INSERT INTO `L` VALUES ('g',8,'v','z','i','z','v',NULL,NULL,NULL,'f',3,2,'e',24,'a',7,'m','o','x','e');
INSERT INTO `L` VALUES ('u',1,'h','n','c',NULL,'c','z',NULL,NULL,'i',8,2,'t',25,'s',NULL,'z','g','l','c');
INSERT INTO `L` VALUES ('w',7,'e','y','v','b','w','d',NULL,'h','e',5,9,'h',26,'v',9,'q','e','n','x');
INSERT INTO `L` VALUES ('k',6,'t','d','z','t','o','d','a',NULL,'k',0,0,'n',27,'r',2,'v','s','g','g');
INSERT INTO `L` VALUES ('t',4,'j','q','v',NULL,NULL,'g','m','v','h',0,NULL,'l',28,'h',8,'r','h','q',NULL);
INSERT INTO `L` VALUES ('j',9,'a','e','x',NULL,'h','k','s','g','a',4,9,'l',29,'x',9,'a','g','f',NULL);
INSERT INTO `L` VALUES (NULL,4,'y','u','n','m','p','p','i','r','n',0,0,'z',30,'i',7,'g','y','c','t');
INSERT INTO `L` VALUES ('g',5,'s','b','h','a','y','g','g','j','u',3,8,'u',31,'h',5,'n','l','x','c');
INSERT INTO `L` VALUES ('j',0,'m','w','j','u','t','n','v','y','v',2,NULL,'z',32,'l',7,'y','t','n','j');
INSERT INTO `L` VALUES ('g',9,'t','n','q','h','w',NULL,'e',NULL,'d',4,6,'d',33,'t',NULL,'d','g','u','l');
INSERT INTO `L` VALUES ('u',0,'m','t','i','r','i',NULL,'k','r','o',4,6,'p',34,NULL,4,'j','l','k',NULL);
INSERT INTO `L` VALUES (NULL,1,'g','n','y',NULL,'g',NULL,'k','r','m',9,0,'g',35,'y',8,'n','c','a','i');
INSERT INTO `L` VALUES ('h',2,'e','m','h','q','z',NULL,'u','m','p',2,4,'x',36,NULL,1,'y','r','w','d');
INSERT INTO `L` VALUES ('x',0,'c','y','j','m','a','a','a',NULL,'m',3,8,'f',37,'d',1,'u','g','u','r');
INSERT INTO `L` VALUES ('r',7,'e','k','a','s',NULL,'s','t','f','k',2,6,'d',38,'x',NULL,'f','y','d','n');
INSERT INTO `L` VALUES ('t',0,'n','y','c','j',NULL,NULL,'x','c','e',3,5,'t',39,'t',7,'i','o','y','v');
INSERT INTO `L` VALUES ('x',0,'e','w','u',NULL,'k',NULL,NULL,'d','o',1,NULL,'m',40,'s',NULL,'y','h','m','h');
INSERT INTO `L` VALUES ('v',0,'l','o','n','l','u','n','p',NULL,'a',7,1,'j',41,'k',7,'k','m','q','e');
INSERT INTO `L` VALUES (NULL,9,'m','r','k','t','x','q','d','y','o',3,0,'e',42,'k',6,'p','i','t','l');
INSERT INTO `L` VALUES ('m',4,'n','y','c',NULL,'z','w','y',NULL,'j',8,6,'e',43,'i',NULL,'f','i','p','m');
INSERT INTO `L` VALUES ('i',8,'u','b','e','w','d','b','p','o','a',9,3,'a',44,'t',NULL,'o','d','o','g');
INSERT INTO `L` VALUES ('p',4,'k','r','u',NULL,'i',NULL,'p','d','b',9,8,'u',45,NULL,7,'z','a','a',NULL);
INSERT INTO `L` VALUES ('s',8,'i','l','k',NULL,'f',NULL,NULL,'z','a',0,8,'a',46,NULL,5,'e','d','k','e');
INSERT INTO `L` VALUES (NULL,7,'n','i','i','z',NULL,'f','o','j','r',2,8,'h',47,'l',NULL,'y','z','j','q');
INSERT INTO `L` VALUES (NULL,3,'e','z','x','q','g','b','o','c','u',3,1,'v',48,'d',1,'h','w','q',NULL);
INSERT INTO `L` VALUES ('u',7,'l','x','f','c','u',NULL,NULL,'w','i',2,2,'h',49,NULL,NULL,'j','c','v','g');
INSERT INTO `L` VALUES ('a',5,'c','z','k',NULL,NULL,'z','f','s','q',4,5,'a',50,'v',NULL,'c','r','f',NULL);
INSERT INTO `L` VALUES ('v',8,'n','d','q',NULL,NULL,'l','k',NULL,'r',7,8,'a',51,'z',NULL,'t','d','h',NULL);
INSERT INTO `L` VALUES ('c',8,'p','p','q','g','r','v','q','l','e',4,2,'g',52,NULL,6,'p','g','w','e');
INSERT INTO `L` VALUES ('t',1,'m','b','h','o',NULL,'j',NULL,'g','e',7,7,'r',53,'l',5,'j','d','p','k');
INSERT INTO `L` VALUES ('b',2,'i','u','v','a','e','n','p','y','g',0,NULL,'y',54,'k',4,'t','p','t','b');
INSERT INTO `L` VALUES ('r',1,'c','t','y','i','y',NULL,NULL,NULL,'b',7,1,'d',55,'s',4,'s','a','u',NULL);
INSERT INTO `L` VALUES ('x',1,'t','x','j','x','s','h',NULL,'f','m',6,4,'r',56,'d',7,'y','q','m',NULL);
INSERT INTO `L` VALUES ('q',8,'r','p','s','v','h',NULL,'u','x','a',8,7,'r',57,'e',NULL,'e','z','f','r');
INSERT INTO `L` VALUES ('c',0,'r','w','q','z','v',NULL,'c',NULL,'v',1,2,'y',58,'e',9,'e','f','n','j');
INSERT INTO `L` VALUES ('f',6,'e','p','t',NULL,NULL,'t','b','a','v',2,2,'k',59,'e',1,'d','n','d','t');
INSERT INTO `L` VALUES ('j',0,'b','t','s','j','y',NULL,'s','w','d',0,5,'y',60,'e',3,'q','q','i',NULL);
INSERT INTO `L` VALUES ('n',3,'u','r','r','b','w','r','r','i','y',2,9,'x',61,'g',9,'r','w','s','w');
INSERT INTO `L` VALUES ('v',3,'a','x','o','g','k','n','m','i','q',4,9,'p',62,'h',2,'q','w','b','m');
INSERT INTO `L` VALUES (NULL,5,'j','o','l','o','c','b',NULL,'a','k',0,3,'k',63,'f',NULL,'p','r','e',NULL);
INSERT INTO `L` VALUES (NULL,8,'c','t','y','a','m','u','r',NULL,'n',8,2,'a',64,'z',NULL,'l','o','g','y');
INSERT INTO `L` VALUES (NULL,5,'e','k','l','x','f','y','z','d','b',0,4,'k',65,NULL,5,'o','y','y',NULL);
INSERT INTO `L` VALUES ('k',2,'i','k','f',NULL,'c','j','w','w','e',8,2,'m',66,'z',2,'u','l','k','k');
INSERT INTO `L` VALUES ('w',9,'u','q','q','h','q','l','l','r','m',6,NULL,'v',67,'k',4,'e','j','m','s');
INSERT INTO `L` VALUES ('o',2,'p','w','x','o','q','x','l','d','x',2,NULL,'m',68,NULL,3,'z','k','v','c');
INSERT INTO `L` VALUES ('l',0,'o','d','r','z','s','w','i','j','b',2,6,'o',69,'n',1,'b','r','u','m');
INSERT INTO `L` VALUES ('s',4,'d','a','l',NULL,'p','x',NULL,'z','o',7,9,'g',70,'k',2,'b','e','e','k');

```
```
SELECT STRAIGHT_JOIN  table2 . `pk` AS field1 , table2 . `pk` AS field2 , table2 . `col_int` AS field3 FROM  L AS table1  LEFT OUTER JOIN W AS table2 ON  table1 . `col_varchar_10_latin1_key` =  table2 . `col_varchar_10_latin1_key`  WHERE ( ( ( table1 . `pk` != 8 OR table1 . `pk` < table1 . `col_int` ) AND table1 . `pk` <> 9 ) AND table1 . `pk` >= table2 . `pk` )   ORDER BY field1,field2, field3  ;
```

2. What did you expect to see?
from Mysql
```
+--------+--------+--------+
| field1 | field2 | field3 |
+--------+--------+--------+
|      1 |      1 |      4 |
|      2 |      2 |      3 |
|      2 |      2 |      3 |
|      2 |      2 |      3 |
|      3 |      3 |      2 |
|      3 |      3 |      2 |
|      4 |      4 |      5 |
|      4 |      4 |      5 |
|      5 |      5 |      8 |
|      6 |      6 |      6 |
|      6 |      6 |      6 |
|      7 |      7 |      0 |
|      7 |      7 |      0 |
|      7 |      7 |      0 |
|      7 |      7 |      0 |
|      9 |      9 |      4 |
|     11 |     11 |      0 |
|     11 |     11 |      0 |
|     11 |     11 |      0 |
|     11 |     11 |      0 |
|     12 |     12 |   NULL |
|     12 |     12 |   NULL |
|     12 |     12 |   NULL |
|     13 |     13 |      8 |
|     13 |     13 |      8 |
|     13 |     13 |      8 |
|     13 |     13 |      8 |
|     14 |     14 |      7 |
|     14 |     14 |      7 |
|     17 |     17 |      9 |
|     17 |     17 |      9 |
|     20 |     20 |   NULL |
|     20 |     20 |   NULL |
|     20 |     20 |   NULL |
|     20 |     20 |   NULL |
+--------+--------+--------+

```

3. What did you see instead?

```
+--------+--------+--------+
| field1 | field2 | field3 |
+--------+--------+--------+
|      1 |      1 |      4 |
|      2 |      2 |      3 |
|      2 |      2 |      3 |
|      2 |      2 |      3 |
|      3 |      3 |      2 |
|      3 |      3 |      2 |
|      4 |      4 |      5 |
|      4 |      4 |      5 |
|      5 |      5 |      8 |
|      6 |      6 |      6 |
|      6 |      6 |      6 |
|      7 |      7 |      0 |
|      7 |      7 |      0 |
|      7 |      7 |      0 |
|      7 |      7 |      0 |
|      9 |      9 |      4 |
|     11 |     11 |      0 |
|     11 |     11 |      0 |
|     11 |     11 |      0 |
|     11 |     11 |      0 |
|     12 |     12 |      0 |
|     12 |     12 |      0 |
|     12 |     12 |      0 |
|     13 |     13 |      8 |
|     13 |     13 |      8 |
|     13 |     13 |      8 |
|     13 |     13 |      8 |
|     14 |     14 |      7 |
|     14 |     14 |      7 |
|     17 |     17 |      9 |
|     17 |     17 |      9 |
|     20 |     20 |      0 |
|     20 |     20 |      0 |
|     20 |     20 |      0 |
|     20 |     20 |      0 |
+--------+--------+--------+
```
```
+----------------------------------+---------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                               | estRows | task      | operator info                                                                                                                                                   |
+----------------------------------+---------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sort_7                           | 27.47   | root      | randgen_test.w.pk:asc, randgen_test.w.pk:asc, randgen_test.w.col_int:asc                                                                                        |
| └─Projection_9                   | 27.47   | root      | randgen_test.w.pk, randgen_test.w.pk, randgen_test.w.col_int                                                                                                    |
|   └─HashLeftJoin_39              | 27.47   | root      | inner join, equal:[eq(randgen_test.l.col_varchar_10_latin1_key, randgen_test.w.col_varchar_10_latin1_key)], other cond:ge(randgen_test.l.pk, randgen_test.w.pk) |
|     ├─TableReader_59(Build)      | 21.98   | root      | data:Selection_58                                                                                                                                               |
|     │ └─Selection_58             | 21.98   | cop[tikv] | not(isnull(randgen_test.w.col_varchar_10_latin1_key))                                                                                                           |
|     │   └─TableFullScan_57       | 22.00   | cop[tikv] | table:table2, keep order:false, stats:pseudo                                                                                                                    |
|     └─TableReader_51(Probe)      | 25.84   | root      | data:Selection_50                                                                                                                                               |
|       └─Selection_50             | 25.84   | cop[tikv] | not(isnull(randgen_test.l.col_varchar_10_latin1_key)), or(ne(randgen_test.l.pk, 8), lt(randgen_test.l.pk, randgen_test.l.col_int))                              |
|         └─TableRangeScan_49      | 46.67   | cop[tikv] | table:table1, range:[-inf,9), (9,+inf], keep order:false, stats:pseudo                                                                                          |
+----------------------------------+---------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

### PR DESCRIPTION
**Pull request by fzhedu**
### What problem does this PR solve?

Issue Number: 
close #15316 
close https://github.com/pingcap/tidb/issues/15313 
close https://github.com/pingcap/tidb/issues/15312 
close https://github.com/pingcap/tidb/issues/15302 
close https://github.com/pingcap/tidb/issues/15299

Problem Summary: after taking inline projection, the outer part of a jointed rows may be pruned, so it cannot directly use  `chunk.CopySelectedJoinRowsWithSameOuterRows()`.

### What is changed and how it works?

What's Changed:  change the `chunk.CopySelectedJoinRowsWithSameOuterRows()` to solve the cases without outers.

How it Works:  correctly copy inner part, and ignore the outer part.

### Check List 

Tests 

- Unit test

### CODE REVIEW

File: executor/joiner.go [hunk 1]
```diff
@@ -261,7 +261,7 @@ func (j *baseJoiner) filter(
 			innerColOffset, outerColOffset = len(lUsed), 0
 		}
 	}
-	return chunk.CopySelectedJoinRowsWithSameOuterRows(input, innerColOffset, outerColOffset, j.selected, output)
```
Comment (XuHuaiyu) [inline executor/joiner.go]: I think we can keep this function here because it's effective.
We can add a check logic to determine whether we need to append the inner cols or outer cols.

Comment (fzhedu) [reply executor/joiner.go]: `chunk.CopySelectedJoinRowsWithSameOuterRows()`  just is more efficient in microbenchmark, but it makes little improvement when run real SQLs, especially on large datasets.

Here, I wonder how to keep the build/probe with used columns in accordance? This accordance decides whether the outer part of joined rows are the same or not.

File: executor/join_test.go [hunk 2]
```diff
@@ -1889,3 +1889,20 @@ func (s *testSuiteJoinSerial) TestOuterMatchStatusIssue14742(c *C) {
 		"2 1",
 	))
 }
+
+func (s *testSuiteJoinSerial) TestInlineProjection4HashJoinIssue15316(c *C) {
```
Comment (SunRunAway) [inline executor/join_test.go]: This case needn't stay in `testSuiteJoinSerial`

File: executor/joiner.go [hunk 3]
```diff
@@ -259,9 +260,14 @@ func (j *baseJoiner) filter(
...
 			innerColOffset, outerColOffset = len(lUsed), 0
+			// the same outers are pruned, remaining the different inners
+			if innerColOffset-outerColOffset == 0 {
+				prunedOuters = true
+			}
 		}
+
 	}
-	return chunk.CopySelectedJoinRowsWithSameOuterRows(input, innerColOffset, outerColOffset, j.selected, output)
+	return chunk.CopySelectedJoinRowsWithSameOuterRows(input, innerColOffset, outerColOffset, j.selected, output, prunedOuters)
```
Comment (SunRunAway) [inline executor/joiner.go]: `prunedOuters` seems to be confused to readers. How about explicitly send `innerColLen` and `outerColLen` as arguments.

File: util/chunk/chunk_util_test.go [hunk 4]
```diff
@@ -61,7 +61,7 @@ func TestCopySelectedJoinRows(t *testing.T) {
 	}
 	// batch copy
```
Comment (SunRunAway) [inline util/chunk/chunk_util_test.go]: We should add a test case covering this situation here.

File: executor/join_test.go [hunk 5]
```diff
@@ -1889,3 +1889,20 @@ func (s *testSuiteJoinSerial) TestOuterMatchStatusIssue14742(c *C) {
...
+	tk.MustExec("insert into S values (0,1,2),(0,1,null),(0,1,2);")
+	tk.MustExec("insert into T values (0,10,2),(0,10,null),(1,10,2);")
+	tk.MustQuery("select T.a,T.a,T.c from S join T on T.a = S.a where S.b<T.b order by T.a,T.c;").Check(testkit.Rows(
+		"0 0 <nil>",
+		"0 0 <nil>",
+		"0 0 <nil>",
+		"0 0 2",
+		"0 0 2",
+		"0 0 2",
+	))
```
Comment (SunRunAway) [inline executor/join_test.go]: Do we need to check the explain result to ensure that outer table is right table?

File: executor/join_test.go [hunk 6]
```diff
@@ -1889,3 +1889,20 @@ func (s *testSuiteJoinSerial) TestOuterMatchStatusIssue14742(c *C) {
...
 }
+
+func (s *testSuiteJoinSerial) TestInlineProjection4HashJoinIssue15316(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("create table S (a int not null, b int, c int);")
+	tk.MustExec("create table T (a int not null, b int, c int);")
+	tk.MustExec("insert into S values (0,1,2),(0,1,null),(0,1,2);")
+	tk.MustExec("insert into T values (0,10,2),(0,10,null),(1,10,2);")
+	tk.MustQuery("select T.a,T.a,T.c from S join T on T.a = S.a where S.b<T.b order by T.a,T.c;").Check(testkit.Rows(
```
Comment (SunRunAway) [inline executor/join_test.go]: How about using Right Outer Join?

Comment (fzhedu) [reply executor/join_test.go]: It will be converted to inner join even using Right Outer join.

File: executor/joiner.go (hunk 3 above)
Comment (fzhedu) [reply executor/joiner.go]: This corner case happens when:
(1) j.outerIsRight is false
(2) innerColOff and outerColOff are 0
These two factors will prune the same outer parts. This result cannot be achieved by taking `innerColLen` and `outerColLen`. Maintaining these two parameters are more complex than only one parameter. The `prunedOuters` specifies the special case when the joined tuple without outer parts.

File: executor/join_test.go (hunk 2 above)
Comment (fzhedu) [reply executor/join_test.go]: updated the test which still needs the `testSuiteJoinSerial`

File: executor/join_test.go (hunk 6 above)
Comment (fzhedu) [reply executor/join_test.go]: we update the test and there should be Hashleftjoin

File: executor/join_test.go (hunk 5 above)
Comment (fzhedu) [reply executor/join_test.go]: ok

File: util/chunk/chunk_util_test.go (hunk 4 above)
Comment (fzhedu) [reply util/chunk/chunk_util_test.go]: done

File: util/chunk/chunk_util_test.go [hunk 7]
```diff
@@ -61,7 +61,33 @@ func TestCopySelectedJoinRows(t *testing.T) {
...
+	for i := range selected {
+		if selected[i] {
+			numSelected++
+		}
+	}
+	if dstChk2.numVirtualRows != numSelected || dstChk2.NumRows() != numSelected {
+		t.Fatal(dstChk2.numVirtualRows, dstChk2.NumRows(), numSelected)
+	}
+}
+func TestCopySelectedJoinRowsWithoutSameOuters(t *testing.T) {
```
Comment (SunRunAway) [inline util/chunk/chunk_util_test.go]: Please keep an empty line between functions/methods

Comment (fzhedu) [reply util/chunk/chunk_util_test.go]: ok

File: executor/joiner.go [hunk 8]
```diff
@@ -241,6 +241,7 @@ func (j *baseJoiner) filter(
 	}
 	// Batch copies selected rows to output chunk.
 	innerColOffset, outerColOffset := 0, input.NumCols()-outerColsLen
+	innerColLen, outerColLen := input.NumCols()-outerColsLen, outerColsLen
```
Comment (SunRunAway) [inline executor/joiner.go]: Could `outerColLen` and `outerColsLen` be the same?

Comment (fzhedu) [reply executor/joiner.go]: ok
