### PR TITLE
*:  Support Failed-Login Tracking and Temporary Account Locking

### LINKED ISSUE #38938: Support Failed-Login Tracking and Temporary Account Locking
https://dev.mysql.com/doc/refman/8.0/en/password-management.html#failed-login-tracking

### PR DESCRIPTION
**Pull request by lastincisor**
### What problem does this PR solve?

Issue Number: close #38938 

Problem Summary:

### What is changed and how it works?

Most of the feature is the same as MySQL's, except that:

- A server restart, accounts not reset
- Execution of FLUSH PRIVILEGES. (Starting the server with --skip-grant-tables,  failed-login tracking is working. 
    In this case, the first execution of FLUSH PRIVILEGES accounts not reset.)

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note

Support failed-login tracking and temporary account locking for users with `FAILED_LOGIN_ATTEMPTS` and/or `PASSWORD_LOCK_TIME`

```

### CODE REVIEW

File: privilege/privileges/privileges.go [hunk 1]
```diff
@@ -355,6 +355,91 @@ func checkAuthTokenClaims(claims map[string]interface{}, record *UserRecord, tok
...
+	record := mysqlPriv.matchUser(user, host)
+	if record == nil {
+		logutil.BgLogger().Error("get authUser privilege record fail",
+			zap.String("authUser", user), zap.String("authHost", host))
+		ErrAccessDenied.FastGenByArgs(user, host)
+		return false
+	}
+	failedLoginAttempts := record.FailedLoginAttempts
+	passwordLockTime := record.PasswordLockTime
+	if failedLoginAttempts == 0 && passwordLockTime == 0 {
```
Comment (keeplearning20221) [inline privilege/privileges/privileges.go:402]: failedLoginAttempts == 0 || passwordLockTime == 0

File: session/session.go [hunk 2]
```diff
@@ -2598,8 +2599,38 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+	if connVerifErr != nil {
+		if enableAutoLock {
+			if strings.Index(connVerifErr.Error(), "decode") != -1 || strings.Index(connVerifErr.Error(), "caching_sha2_password") != -1 || strings.Index(connVerifErr.Error(), "socket") != -1 || strings.Index(connVerifErr.Error(), "Access denied") != -1 {
+				failedLogin(s, authUser.Username, authUser.Hostname)
+			}
+		}
+		return connVerifErr
+	} else {
+		if enableAutoLock {
+			passwordLockingJson := pm.BuildPasswordLockingJsonByRecord(authUser.Username, authUser.Hostname, false, 0)
```
Comment (keeplearning20221) [inline session/session.go:2624]: 加一个校验，校验是否在加锁状态下，防止出现缓存更新不及时导致锁失效的场景

File: session/session.go [hunk 3]
```diff
@@ -2608,6 +2639,160 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+			}
+			failedLoginCount := attributesInt64Parser(userAttributesJson, "$.Password_locking.failed_login_count")
+			if lockTime != -1 {
+				userAttr.FailedLoginCount = failedLoginCount
+			}
+			autoLockedLastChanged := attributesTimeUnixParser(userAttributesJson, "$.Password_locking.auto_locked_last_changed")
+			if lockTime != -1 {
+				userAttr.AutoLockedLastChanged = autoLockedLastChanged
+			}
+			autoAccountLock, parserErr := attributesBoolParser(userAttributesJson, "$.Password_locking.auto_account_locked")
```
Comment (keeplearning20221) [inline session/session.go:2764]: parserErr 这个异常不处理了吗？

File: session/session.go [hunk 4]
```diff
@@ -2608,6 +2639,160 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+func getFailedLoginCount(s *session, user string, host string) privilege.UserAttributes {
+	userAttr := privilege.UserAttributes{}
+	ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+	_, err := s.ExecuteInternal(ctx, "BEGIN PESSIMISTIC")
+	if err != nil {
+		return userAttr
+	}
+	rs, err := s.ExecuteInternal(ctx, `SELECT user_attributes from mysql.user WHERE USER = %? AND HOST = %? for update`, user, host)
+	if err != nil {
+		return userAttr
```
Comment (keeplearning20221) [inline session/session.go:2732]: 这里的err 要传递出去报错

File: session/session.go [hunk 5]
```diff
@@ -2608,6 +2639,160 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+		sqlexec.MustFormatSQL(sql, "UPDATE %n.%n SET ", mysql.SystemDB, mysql.UserTable)
+		for i, f := range fields {
+			sqlexec.MustFormatSQL(sql, f.expr, f.value)
+			if i < len(fields)-1 {
+				sqlexec.MustFormatSQL(sql, ",")
+			}
+		}
+		sqlexec.MustFormatSQL(sql, " WHERE Host=%? and User=%?;", host, user)
+		ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+		_, err := s.ExecuteInternal(ctx, sql.String())
```
Comment (keeplearning20221) [inline session/session.go:2660]: 验证一下没有mysql user表操作权限用户登录是否有问题

File: privilege/privileges/privileges.go [hunk 6]
```diff
@@ -451,9 +536,12 @@ func (p *UserPrivileges) ConnectionVerification(user *auth.UserIdentity, authUse
 		logutil.BgLogger().Error(fmt.Sprintf("Access denied for authUser '%s'@'%s'. Account is locked.", authUser, authHost))
 		return errAccountHasBeenLocked.FastGenByArgs(user.Username, user.Hostname)
 	}
+	return nil
+}
 
+func (p *UserPrivileges) AuthSuccess(authUser, authHost string) error {
```
Comment (keeplearning20221) [inline privilege/privileges/privileges.go:542]: 这个return 有什么特别的意义吗？

File: executor/simple.go [hunk 7]
```diff
@@ -1099,8 +1120,37 @@ func (e *SimpleExec) executeAlterUser(ctx context.Context, s *ast.AlterUserStmt)
...
 			fields = append(fields, alterField{"account_locked=%?", lockAccount})
+			if lockAccount == "N" {
+				newAttributesStr := fmt.Sprintf("{\"Password_locking\": {\"auto_account_locked\": \"%s\",\"failed_login_count\": %d,\"auto_locked_last_changed\": \"%s\"}}",
+					lockAccount, 0, time.Now().Format(time.UnixDate))
+				fields = append(fields, alterField{"user_attributes=json_merge_patch(coalesce(user_attributes, '{}'), %?)", newAttributesStr})
+			}
+		}
+		if failedLoginAttempts != 0 && passwordLockTime != 0 {
+			lock := "N"
+			if lockAccount == "Y" {
```
Comment (keeplearning20221) [inline executor/simple.go:1131]: image
边界保护一下

File: executor/simple.go [hunk 8]
```diff
@@ -976,6 +991,12 @@ func (e *SimpleExec) executeAlterUser(ctx context.Context, s *ast.AlterUserStmt)
 			} else if s.PasswordOrLockOptions[i].Type == ast.Unlock {
 				lockAccount = "N"
 				break
+			} else if s.PasswordOrLockOptions[i].Type == ast.FailedLoginAttempts {
+				failedLoginAttempts = s.PasswordOrLockOptions[i].Count
```
Comment (keeplearning20221) [inline executor/simple.go:995]: create user test FAILED_LOGIN_ATTEMPTS 3 PASSWORD_LOCK_TIME 2 ACCOUNT LOCK; 这个场景看一下

Comment (lastincisor) [reply executor/simple.go:995]: CREATE USER [IF NOT EXISTS]
    user [auth_option] [, user [auth_option]] ...
    DEFAULT ROLE role [, role ] ...
    [REQUIRE {NONE | tls_option [[AND] tls_option] ...}]
    [WITH resource_option [resource_option] ...]
    [password_option | lock_option] ...
    [COMMENT 'comment_string' | ATTRIBUTE 'json_object']
password_option 与 lock_option 是并列的

Comment (keeplearning20221) [reply executor/simple.go:995]: image

File: executor/simple.go [hunk 9]
```diff
@@ -1099,6 +1120,39 @@ func (e *SimpleExec) executeAlterUser(ctx context.Context, s *ast.AlterUserStmt)
 
 		if len(lockAccount) != 0 {
 			fields = append(fields, alterField{"account_locked=%?", lockAccount})
+			if lockAccount == "N" {
+				newAttributesStr := fmt.Sprintf("{\"Password_locking\": {\"auto_account_locked\": \"%s\",\"failed_login_count\": %d,\"auto_locked_last_changed\": \"%s\"}}",
+					lockAccount, 0, time.Now().Format(time.UnixDate))
+				fields = append(fields, alterField{"user_attributes=json_merge_patch(coalesce(user_attributes, '{}'), %?)", newAttributesStr})
+			}
+		}
+		if failedLoginAttempts > 32767 || failedLoginAttempts < 0 || passwordLockTime > 32767 || passwordLockTime < -1 {
```
Comment (keeplearning20221) [inline executor/simple.go:1129]: mysql 常见异常处理方式，大于最大调整到最大

File: privilege/privileges/cache.go [hunk 10]
```diff
@@ -683,6 +695,78 @@ func (p *MySQLPrivilege) decodeUserTableRow(row chunk.Row, fs []*ast.ResultField
...
+			if err != nil {
+				return err
+			}
+			if failedLoginAttemptsBJ, found := bj.Extract([]types.JSONPathExpression{failedloginPathExpr}); found {
+				failedLoginAttempts, err := failedLoginAttemptsBJ.Unquote()
+				if err != nil {
+					return err
+				}
+				value.FailedLoginAttempts, err = strconv.ParseInt(failedLoginAttempts, 10, 64)
+				if err != nil {
```
Comment (keeplearning20221) [inline privilege/privileges/cache.go:708]: 这边的边界也保护一下，表无法组织用户修改成非法值

File: privilege/privileges/cache.go [hunk 11]
```diff
@@ -683,6 +695,78 @@ func (p *MySQLPrivilege) decodeUserTableRow(row chunk.Row, fs []*ast.ResultField
...
+			autoLockedLastChangedExpr, err := types.ParseJSONPathExpr("$.Password_locking.auto_locked_last_changed")
+			if err != nil {
+				return err
+			}
+			if autoLockedLastChangedBJ, found := bj.Extract([]types.JSONPathExpression{autoLockedLastChangedExpr}); found {
+				autoLockedLastChangedTime, err := autoLockedLastChangedBJ.Unquote()
+				if err != nil {
+					return err
+				}
+				t, _ := time.ParseInLocation(time.UnixDate, autoLockedLastChangedTime, time.Local)
```
Comment (keeplearning20221) [inline privilege/privileges/cache.go:767]: 这个时间字符串不一定合法

File: session/session.go [hunk 12]
```diff
@@ -2598,16 +2599,222 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+		passwordLockTimeDays, autoAccountLocked, failedLoginCount)
+	if err := s.passwordLocking(user, host, newAttributesStr); err != nil {
+		return err
+	}
+	return nil
+}
+
+func failedLogin(s *session, user string, host string) error {
+	userAttr, getErr := getFailedLoginCount(s, user, host)
+	if getErr != nil {
```
Comment (keeplearning20221) [inline session/session.go:2806]: 回滚begin

File: session/session.go [hunk 13]
```diff
@@ -2598,16 +2599,222 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+		}
+	}
+	return false, nil
+}
+
+func failedLoginTrackingCommit(s *session) error {
+	ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+	_, err := s.ExecuteInternal(ctx, "COMMIT")
+	if err != nil {
+		_, err = s.ExecuteInternal(ctx, "ROLLBACK")
```
Comment (keeplearning20221) [inline session/session.go:2719]: 上面的err 被 rollback的err覆盖了

File: privilege/privileges/privileges.go [hunk 14]
```diff
@@ -355,6 +355,98 @@ func checkAuthTokenClaims(claims map[string]interface{}, record *UserRecord, tok
...
+	}
+	mysqlPriv := p.Handle.Get()
+	record := mysqlPriv.matchUser(user, host)
+	if record == nil {
+		logutil.BgLogger().Error("get authUser privilege record fail",
+			zap.String("authUser", user), zap.String("authHost", host))
+		ErrAccessDenied.FastGenByArgs(user, host)
+		return ""
+	}
+	if record.FailedLoginCount == 0 {
```
Comment (keeplearning20221) [inline privilege/privileges/privileges.go:426]: 缓存中的失败次数不准要查表

File: executor/simple.go [hunk 15]
```diff
@@ -1099,6 +1132,49 @@ func (e *SimpleExec) executeAlterUser(ctx context.Context, s *ast.AlterUserStmt)
...
+			}
+			if passwordLockTime < -1 {
+				failedLoginAttempts = -1
+			}
+			newAttributesStr := fmt.Sprintf("{\"Password_locking\": {\"failed_login_attempts\": %d,\"password_lock_time_days\": %d,\"auto_account_locked\": \"%s\",\"failed_login_count\": %d,\"auto_locked_last_changed\": \"%s\"}}",
+				failedLoginAttempts, passwordLockTime, lock, 0, time.Now().Format(time.UnixDate))
+			fields = append(fields, alterField{"user_attributes=json_merge_patch(coalesce(user_attributes, '{}'), %?)", newAttributesStr})
+		} else if failedLoginAttempts == 0 && passwordLockTime != 0 {
+			lock := "N"
+			if lockAccount == "Y" {
```
Comment (keeplearning20221) [inline executor/simple.go:1164]: user_attributes 中的lock只被failed_login_attempts影响吧，lockAccount依旧只控制Account_locked

File: session/session.go [hunk 16]
```diff
@@ -2598,16 +2598,147 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
 }
 
+func (s *session) passwordLocking(user string, host string, newAttributesStr string) error {
+	type alterField struct {
+		expr  string
+		value string
+	}
+	var fields []alterField
+	fields = append(fields, alterField{"user_attributes=json_merge_patch(coalesce(user_attributes, '{}'), %?)", newAttributesStr})
+	if len(fields) > 0 {
```
Comment (keeplearning20221) [inline session/session.go:2648]: fields 恒为1 就不需要循环了吧

File: privilege/privileges/privileges.go [hunk 17]
```diff
@@ -772,3 +866,104 @@ func init() {
...
+
+func PasswordLockingInt64Parser(userAttributesJson types.BinaryJSON, pathExpr string) (int64, error) {
+	jsonPath, err := types.ParseJSONPathExpr(pathExpr)
+	if err != nil {
+		return -1, err
+	}
+	if BJ, found := userAttributesJson.Extract([]types.JSONPathExpression{jsonPath}); found {
+		return BJ.GetInt64(), nil
+	}
+	return -1, err
```
Comment (bob34007) [inline privilege/privileges/privileges.go:952]: need return not found error

File: privilege/privileges/privileges.go [hunk 18]
```diff
@@ -772,3 +866,104 @@ func init() {
...
+	}
+	if BJ, found := userAttributesJson.Extract([]types.JSONPathExpression{jsonPath}); found {
+		value, BJErr := BJ.Unquote()
+		if BJErr != nil {
+			return -1, err
+		}
+		t, _ := time.ParseInLocation(time.UnixDate, value, time.Local)
+		return t.Unix(), nil
+	}
+	return -1, err
```
Comment (bob34007) [inline privilege/privileges/privileges.go:968]: need return not found

File: privilege/privileges/privileges.go [hunk 19]
```diff
@@ -772,3 +866,104 @@ func init() {
...
+	jsonPath, err := types.ParseJSONPathExpr(pathExpr)
+	if err != nil {
+		return -1, err
+	}
+	if BJ, found := userAttributesJson.Extract([]types.JSONPathExpression{jsonPath}); found {
+		value, BJErr := BJ.Unquote()
+		if BJErr != nil {
+			return -1, err
+		}
+		t, _ := time.ParseInLocation(time.UnixDate, value, time.Local)
```
Comment (bob34007) [inline privilege/privileges/privileges.go:965]: need deal error

File: privilege/privileges/privileges.go [hunk 20]
```diff
@@ -772,3 +866,104 @@ func init() {
...
+
+func PasswordLockingBoolParser(userAttributesJson types.BinaryJSON, pathExpr string) (bool, error) {
+	jsonPath, err := types.ParseJSONPathExpr(pathExpr)
+	if err != nil {
+		return false, err
+	}
+	if BJ, found := userAttributesJson.Extract([]types.JSONPathExpression{jsonPath}); found {
+		value, BJErr := BJ.Unquote()
+		if BJErr != nil {
+			return false, err
```
Comment (bob34007) [inline privilege/privileges/privileges.go:979]: return BJErr

File: privilege/privileges/privileges.go [hunk 21]
```diff
@@ -772,3 +866,104 @@ func init() {
...
+		}
+		if value == "Y" {
+			return true, nil
+		} else {
+			return false, nil
+		}
+	}
+	return false, nil
```
Comment (bob34007) [inline privilege/privileges/privileges.go:987]: need return not found error

File: privilege/privileges/privileges.go [hunk 22]
```diff
@@ -772,3 +866,104 @@ func init() {
...
+		return false, err
+	}
+	if BJ, found := userAttributesJson.Extract([]types.JSONPathExpression{jsonPath}); found {
+		value, BJErr := BJ.Unquote()
+		if BJErr != nil {
+			return false, err
+		}
+		if value == "Y" {
+			return true, nil
+		} else {
```
Comment (bob34007) [inline privilege/privileges/privileges.go:983]: need to consider scenarios that are not N

File: session/session.go [hunk 23]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+	}
+	req := rs.NewChunk(nil)
+	iter := chunk.NewIterator4Chunk(req)
+	for {
+		rsErr := rs.Next(ctx, req)
+		if rsErr != nil {
+			return passwordLocking, rsErr
+		}
+		if req.NumRows() == 0 {
+			return passwordLocking, rsErr
```
Comment (keeplearning20221) [inline session/session.go:2739]: rsErr 为nil 读取失败错误没有处理，需要新建错误信息

File: session/session.go [hunk 24]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+
+func authFailedTracking(s *session, user string, host string) error {
+	passwordLocking, getErr := getFailedLoginCount(s, user, host)
+	if getErr != nil {
+		if rollBackErr := failedLoginTrackingRollback(s); rollBackErr != nil {
+			return rollBackErr
+		}
+		return getErr
+	}
+	if err := userAutoAccountLocked(s, user, host, passwordLocking.FailedLoginCount+1, passwordLocking.FailedLoginAttempts, passwordLocking.PasswordLockTimeDays); err != nil {
```
Comment (keeplearning20221) [inline session/session.go:2667]: rollback 事务

File: session/session.go [hunk 25]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+		return err
+	}
+	return nil
+}
+
+func failedLoginTrackingRollback(s *session) error {
+	ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+	_, err := s.ExecuteInternal(ctx, "ROLLBACK")
+	if err != nil {
+		return err
```
Comment (keeplearning20221) [inline session/session.go:2715]: 直接return err 就好

File: executor/simple.go [hunk 26]
```diff
@@ -1099,6 +1133,37 @@ func (e *SimpleExec) executeAlterUser(ctx context.Context, s *ast.AlterUserStmt)
...
+			if passwordLockTime > 32767 {
+				passwordLockTime = 32767
+			}
+			if passwordLockTime < -1 {
+				failedLoginAttempts = -1
+			}
+			newAttributesStr := fmt.Sprintf("{\"Password_locking\": {\"failed_login_attempts\": %d,\"password_lock_time_days\": %d,\"auto_account_locked\": \"%s\",\"failed_login_count\": %d,\"auto_locked_last_changed\": \"%s\"}}",
+				failedLoginAttempts, passwordLockTime, "N", 0, time.Now().Format(time.UnixDate))
+			fields = append(fields, alterField{"user_attributes=json_merge_patch(coalesce(user_attributes, '{}'), %?)", newAttributesStr})
+		} else if failedLoginAttempts == 0 && passwordLockTime != 0 {
```
Comment (keeplearning20221) [inline executor/simple.go:1159]: 测试一下 alter user test FAILED_LOGIN_ATTEMPTS 0 PASSWORD_LOCK_TIME 0 这个场景

File: executor/simple.go [hunk 27]
```diff
@@ -1099,6 +1138,37 @@ func (e *SimpleExec) executeAlterUser(ctx context.Context, s *ast.AlterUserStmt)
...
+			}
+			if failedLoginAttempts < 0 {
+				failedLoginAttempts = 0
+			}
+			if passwordLockTime > 32767 {
+				passwordLockTime = 32767
+			}
+			if passwordLockTime < -1 {
+				failedLoginAttempts = -1
+			}
```
Comment (keeplearning20221) [inline executor/simple.go:1160]: alter user test FAILED_LOGIN_ATTEMPTS 32768；
alter user test PASSWORD_LOCK_TIME 32768；

File: session/session.go [hunk 28]
```diff
@@ -2598,16 +2598,169 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+		sqlexec.MustFormatSQL(sql, "UPDATE %n.%n SET ", mysql.SystemDB, mysql.UserTable)
+		sqlexec.MustFormatSQL(sql, "user_attributes=json_merge_patch(coalesce(user_attributes, '{}'), %?)", newAttributesStr)
+		sqlexec.MustFormatSQL(sql, " WHERE Host=%? and User=%?;", host, user)
+		ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+		_, err := s.ExecuteInternal(ctx, sql.String())
+		if err != nil {
+			return err
+		}
+	}
+	domain.GetDomain(s).NotifyUpdatePrivilege()
```
Comment (keeplearning20221) [inline session/session.go:2694]: 先提交再通知，不然他们可能会查不到

File: privilege/privileges/privileges.go [hunk 29]
```diff
@@ -772,3 +866,115 @@ func init() {
...
+	jsonPath, err := types.ParseJSONPathExpr(pathExpr)
+	if err != nil {
+		return -1, err
+	}
+	if BJ, found := userAttributesJson.Extract([]types.JSONPathExpression{jsonPath}); found {
+		return BJ.GetInt64(), nil
+	} else {
+		return 0, nil
+	}
+	return -1, err
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go]:
```suggestion
	}
	return 0, nil
```

File: privilege/privileges/privileges.go [hunk 30]
```diff
@@ -772,3 +866,115 @@ func init() {
...
+		}
+		t, timeErr := time.ParseInLocation(time.UnixDate, value, time.Local)
+		if timeErr != nil {
+			return -1, timeErr
+		}
+		return t.Unix(), nil
+	} else {
+		return 0, nil
+	}
+	return -1, err
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go]:
```suggestion
	}
	return 0, nil
```

File: privilege/privileges/privileges.go [hunk 31]
```diff
@@ -772,3 +866,115 @@ func init() {
...
+}
+
+func PasswordLockingBoolParser(userAttributesJson types.BinaryJSON, pathExpr string) (bool, error) {
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go]:
```suggestion
func passwordLockingBoolParser(userAttributesJson types.BinaryJSON, pathExpr string) (bool, error) {
```

File: privilege/privileges/privileges.go [hunk 32]
```diff
@@ -772,3 +866,115 @@ func init() {
...
+			return true, nil
+		} else if value == "N" {
+			return false, nil
+		} else {
+			return false, nil
+		}
+	} else {
+		return false, nil
+	}
+	return false, nil
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:973]: DITTO

File: session/session.go [hunk 33]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+	if enableAutoLock {
+		passwordLockingJson, verErr := pm.VerificationAccountAutoLock(authUser.Username, authUser.Hostname)
+		if verErr != nil {
+			return verErr
+		}
+		if passwordLockingJson != "" {
+			if lockErr := s.passwordLocking(authUser.Username, authUser.Hostname, passwordLockingJson); lockErr != nil {
+				return lockErr
+			}
+			domain.GetDomain(s).NotifyUpdatePrivilege()
```
Comment (CbcWestwolf) [inline session/session.go:2611]: Please handle the error here

File: session/session.go [hunk 34]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+		}
+	}
+	connVerifErr := pm.ConnectionVerification(user, authUser.Username, authUser.Hostname, authentication, salt, s.sessionVars.TLSConnectionState)
+	if connVerifErr != nil {
+		if enableAutoLock {
+			if strings.Index(connVerifErr.Error(), "decode") != -1 || strings.Index(connVerifErr.Error(), "caching_sha2_password") != -1 || strings.Index(connVerifErr.Error(), "socket") != -1 || strings.Index(connVerifErr.Error(), "Access denied") != -1 {
```
Comment (CbcWestwolf) [inline session/session.go]: It is better not to use the error message for the condition branch.

File: session/session.go [hunk 35]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+	passwordLockingJson := pm.BuildSuccessPasswordLockingJson(user, host, passwordLocking.FailedLoginCount)
+	if passwordLockingJson != "" {
+		if lockingErr := s.passwordLocking(user, host, passwordLockingJson); lockingErr != nil {
+			return lockingErr
+		}
+	}
+	if commitErr := failedLoginTrackingCommit(s); commitErr != nil {
+		return commitErr
+	}
+	domain.GetDomain(s).NotifyUpdatePrivilege()
```
Comment (CbcWestwolf) [inline session/session.go]: DITTO

File: session/session.go [hunk 36]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+}
+
+func (s *session) passwordLocking(user string, host string, newAttributesStr string) error {
+	type alterField struct {
+		expr  string
+		value string
+	}
+	var fields []alterField
+	fields = append(fields, alterField{"user_attributes=json_merge_patch(coalesce(user_attributes, '{}'), %?)", newAttributesStr})
+	if len(fields) > 0 {
```
Comment (CbcWestwolf) [inline session/session.go:2678]: The condition in `if` statement is always true

File: session/session.go [hunk 37]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+			}
+		}
+	}
+	return passwordLocking, nil
+}
+
+func userAutoAccountLocked(s *session, user string, host string, failedLoginCount int64, userFailedLoginAttempts int64, passwordLockTimeDays int64) error {
+	autoAccountLocked := false
+	if failedLoginCount < userFailedLoginAttempts {
+		autoAccountLocked = false
```
Comment (CbcWestwolf) [inline session/session.go]: Redundant assignment

File: session/session.go [hunk 38]
```diff
@@ -2598,16 +2598,172 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+	} else if failedLoginCount >= userFailedLoginAttempts {
+		autoAccountLocked = true
+	}
+	pm := privilege.GetPrivilegeManager(s)
+	newAttributesStr := pm.BuildPasswordLockingJson(userFailedLoginAttempts,
+		passwordLockTimeDays, autoAccountLocked, failedLoginCount)
+	if err := s.passwordLocking(user, host, newAttributesStr); err != nil {
+		return err
+	}
+	return nil
```
Comment (CbcWestwolf) [inline session/session.go]:
```suggestion
	err := s.passwordLocking(user, host, newAttributesStr)
	return err
```

File: executor/simpletest/simple_test.go [hunk 39]
```diff
@@ -880,6 +884,111 @@ func TestUser(t *testing.T) {
...
 
+func TestFailedLoginTracking(t *testing.T) {
+	//store := testkit.CreateMockStore(t)
+	//tk := testkit.NewTestKit(t, store)
+	//tk.MustExec(fmt.Sprintf("create database if not exists %s;", mysql.SystemDB))
+	//tk.MustExec(session.CreateUserTable)
+	//tk.MustExec(session.CreateDBPrivTable)
+	//tk.MustExec(session.CreateTablePrivTable)
+	//tk.MustExec(session.CreateColumnPrivTable)
+
```
Comment (CbcWestwolf) [inline executor/simpletest/simple_test.go:895]:
```suggestion
```
Please remove such unused commented code.

File: executor/simpletest/simple_test.go [hunk 40]
```diff
@@ -880,6 +884,111 @@ func TestUser(t *testing.T) {
...
+	checkAuthUser(t, tk, "u6", 1)
+	require.NoError(t, tk.Session().Auth(&auth.UserIdentity{Username: "u6", Hostname: "localhost"}, nil, nil))
+	require.Error(t, tk.Session().Auth(&auth.UserIdentity{Username: "u4", Hostname: "localhost"}, nil, nil))
+	require.Error(t, tk.Session().Auth(&auth.UserIdentity{Username: "u4", Hostname: "localhost"}, nil, nil))
+	require.Error(t, tk.Session().Auth(&auth.UserIdentity{Username: "u4", Hostname: "localhost"}, nil, nil))
+	require.Error(t, tk.Session().Auth(&auth.UserIdentity{Username: "u4", Hostname: "localhost"}, nil, nil))
+
+	//checkAuthUser(t, tk, "u6", 0)
+	//checkAuthUser(t, tk, "u4", 4)
+
```
Comment (CbcWestwolf) [inline executor/simpletest/simple_test.go:922]:
```suggestion
```

File: executor/simpletest/simple_test.go [hunk 41]
```diff
@@ -880,6 +884,111 @@ func TestUser(t *testing.T) {
...
+}
+
+func encodePassword(password string) []byte {
+	pwd := auth.EncodePassword(password)
+	hpwd, err := auth.DecodePassword(pwd)
+	if err != nil {
+
+	}
```
Comment (CbcWestwolf) [inline executor/simpletest/simple_test.go:930]:
```suggestion
	hpwd, _ := auth.DecodePassword(pwd)
```

File: executor/simpletest/simple_test.go [hunk 42]
```diff
@@ -880,6 +884,96 @@ func TestUser(t *testing.T) {
...
+	checkUser(t, resBuff.String(), failedLoginAttempts, passwordLockTimeDays)
+}
+
+func checkUser(t *testing.T, rs string, failedLoginAttempts int64, passwordLockTimeDays int64) {
+	var ua []userAttributes
+	if err := json.Unmarshal([]byte(rs), &ua); err == nil {
+		require.True(t, ua[0].PasswordLocking.FailedLoginAttempts == failedLoginAttempts)
+		require.True(t, ua[0].PasswordLocking.PasswordLockTimeDays == passwordLockTimeDays)
+	} else {
+		fmt.Println(err)
```
Comment (CbcWestwolf) [inline executor/simpletest/simple_test.go:941]: Please return the error, receive the error in the `TestXXX` function, and use `require.NoError(t, err)` to make sure that no error happens. Like
```go
err = alterAndCheck(xxx)
require.NoError(t, err)
```

File: executor/simpletest/simple_test.go [hunk 43]
```diff
@@ -880,6 +884,96 @@ func TestUser(t *testing.T) {
...
+	}
+}
+
+func checkAuthUser(t *testing.T, tk *testkit.TestKit, user string, failedLoginCount int64) {
+	userAttributesSQL := selectSQL(user)
+	resBuff := bytes.NewBufferString("")
+	rs := tk.MustQuery(userAttributesSQL)
+	for _, row := range rs.Rows() {
+		_, _ = fmt.Fprintf(resBuff, "%s\n", row)
```
Comment (CbcWestwolf) [inline executor/simpletest/simple_test.go:950]: Receive the error here, and return the error if it is not `nil`

File: executor/simpletest/simple_test.go [hunk 44]
```diff
@@ -880,6 +884,96 @@ func TestUser(t *testing.T) {
...
+	}
+	var ua []userAttributes
+	if err := json.Unmarshal([]byte(resBuff.String()), &ua); err == nil {
```
Comment (CbcWestwolf) [inline executor/simpletest/simple_test.go:953]: DITTO

File: privilege/privilege.go [hunk 45]
```diff
@@ -29,71 +29,89 @@ func (k keyType) String() string {
 	return "privilege-key"
 }
 
-// Manager is the interface for providing privilege related operations.
-type Manager interface {
-	// ShowGrants shows granted privileges for user.
-	ShowGrants(ctx sessionctx.Context, user *auth.UserIdentity, roles []*auth.RoleIdentity) ([]string, error)
+type (
+	// Manager is the interface for providing privilege related operations.
+	Manager interface {
```
Comment (CbcWestwolf) [inline privilege/privilege.go:34]: Why do we need this change?

File: executor/show.go [hunk 46]
```diff
@@ -1521,6 +1522,16 @@ func (e *ShowExec) fetchShowCreateUser(ctx context.Context) error {
 		tokenIssuer = " token_issuer " + tokenIssuer
 	}
 
+	failedLoginAttempts := rows[0].GetString(4)
+	if len(failedLoginAttempts) > 0 {
+		failedLoginAttempts = " FAILED_LOGIN_ATTEMPTS " + failedLoginAttempts
+	}
+
+	passwordLockTimeDays := rows[0].GetString(5)
+	if len(passwordLockTimeDays) > 0 {
```
Comment (keeplearning20221) [inline executor/show.go:1531]: -1 处理一下

File: privilege/privileges/privileges.go [hunk 47]
```diff
@@ -772,3 +869,106 @@ func init() {
...
+	AutoAccountLocked     bool
+	AutoLockedLastChanged int64
+	FailedLoginAttempts   int64
+}
+
+// PasswordLockingParser parser PasswordLocking info
+func (passwordLocking *PasswordLocking) PasswordLockingParser(passwordLockingJSON types.BinaryJSON) error {
+	failedLoginAttempts, parserErr := PasswordLockingInt64Parser(passwordLockingJSON, "$.Password_locking.failed_login_attempts")
+	if parserErr != nil {
+		return parserErr
```
Comment (keeplearning20221) [inline privilege/privileges/privileges.go:886]: 这里要忽略掉not find 的错误，并给其设置上默认值

File: privilege/privileges/privileges_test.go [hunk 48]
```diff
@@ -2963,3 +2965,163 @@ func TestIssue37488(t *testing.T) {
...
+		if autoAccountLocked != "" {
+			require.True(t, ua[0].PasswordLocking.AutoAccountLocked == autoAccountLocked)
+		}
+	} else {
+		require.NoError(t, err)
+	}
+}
+
+func selectSQL(user string) string {
+	userAttributesSQL := "SELECT user_attributes from mysql.user WHERE USER = 'REUSER' AND HOST = 'localhost' for update"
```
Comment (keeplearning20221) [inline privilege/privileges/privileges_test.go:3113]: 为什么不使用sql := new(strings.Builder)
	beforeDate := getValidTime(sctx, passwordReuse)
	sqlexec.MustFormatSQL(sql, `SELECT count(*) FROM %n.%n WHERE User=%? AND Host=%? AND Password = %? AND Password_timestamp >= %?;`,
		mysql.SystemDB, mysql.PasswordHistoryTable, userDetail.user, strings.ToLower(userDetail.host), userDetail.pwd, beforeDate)
这种方式拼接字符串

File: session/session.go (hunk 24 above)
Comment (keeplearning20221) [reply session/session.go:2663]: 这里报错需要将select for update 回滚掉，防止锁残留

File: privilege/privileges/cache.go [hunk 49]
```diff
@@ -96,12 +96,17 @@ type baseRecord struct {
...
+	Privileges            mysql.PrivilegeType
+	AccountLocked         bool // A role record when this field is true
+	AuthPlugin            string
+	AuthTokenIssuer       string
+	Email                 string
+	FailedLoginAttempts   int64
+	PasswordLockTime      int64
+	AutoAccountLocked     bool
+	FailedLoginCount      int64
+	AutoLockedLastChanged int64
```
[the remark this answers is not in the document]
Comment (keeplearning20221) [reply privilege/privileges/cache.go]: done

File: privilege/privileges/errors.go [hunk 50]
```diff
@@ -21,9 +21,20 @@ import (
...
+	errInvalidPrivilegeType                               = dbterror.ClassPrivilege.NewStd(mysql.ErrInvalidPrivilegeType)
+	ErrNonexistingGrant                                   = dbterror.ClassPrivilege.NewStd(mysql.ErrNonexistingGrant)
+	errLoadPrivilege                                      = dbterror.ClassPrivilege.NewStd(mysql.ErrLoadPrivilege)
+	ErrAccessDenied                                       = dbterror.ClassPrivilege.NewStd(mysql.ErrAccessDenied)
+	errAccountHasBeenLocked                               = dbterror.ClassPrivilege.NewStd(mysql.ErrAccountHasBeenLocked)
+	ErUserAccessDeniedForUserAccountBlockedByPasswordLock = dbterror.ClassPrivilege.NewStd(mysql.ErUserAccessDeniedForUserAccountBlockedByPasswordLock)
 )
+
+// ErrUserPasswordFailed is used to Verify password failed
+// ErrUserPasswordFailed compatible mysql error. Use s to include mysql errors
```
Comment (CbcWestwolf) [inline privilege/privileges/errors.go:33]:
```suggestion
// ErrUserPasswordFailed is used to indicate that ConnectionVerification fails due to wrong password.
// The field `s` is used to include the wrong message.
```

**Review by keeplearning20221 — APPROVED** [review]

**Review by xiongjiwei — COMMENTED** [review]
please also add some tests for the new syntax

**Comment by lastincisor** [comment]
> please also add some tests for the new syntax

https://github.com/pingcap/tidb/pull/39322/files#diff-da35f363914eee6e0eb28eb786c6d85b798bea57595ed4692e3bc8a0f1c0da3aR887
this is  new syntax test case

**Review by CbcWestwolf — APPROVED** [review]

File: session/session.go [hunk 51]
```diff
@@ -2604,16 +2604,194 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+func authSuccessClearCount(s *session, user string, host string) error {
+	passwordLocking, getErr := getFailedLoginCount(s, user, host)
+	if getErr != nil {
+		if rollBackErr := failedLoginTrackingRollback(s); rollBackErr != nil {
+			return rollBackErr
+		}
+		return getErr
+	}
+	if passwordLocking.AutoAccountLocked {
+		if passwordLocking.PasswordLockTimeDays == -1 {
```
Comment (bb7133) [inline session/session.go:2659]: Why we don't have a `ROLLBACK`(`failedLoginTrackingRollback`) here?

Comment (keeplearning20221) [reply session/session.go:2659]: for unlock or rollback begin

File: privilege/privilege.go [hunk 52]
```diff
@@ -58,10 +58,26 @@ type Manager interface {
 	// RequestDynamicVerificationWithUser verifies a DYNAMIC privilege for a specific user.
 	RequestDynamicVerificationWithUser(privName string, grantable bool, user *auth.UserIdentity) bool
 
+	// VerifyAccountAutoLock Verification Account Auto Lock
```
Comment (bb7133) [inline privilege/privilege.go:61]: The comment here does not make sense...could you improve it?

File: session/session.go (hunk 51 above)
Comment (keeplearning20221) [reply session/session.go:2659]: The login failed session ended, but for safety it should be added

File: session/session.go [hunk 53]
```diff
@@ -2604,16 +2604,194 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+func failedLoginTrackingRollback(s *session) error {
+	ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+	_, err := s.ExecuteInternal(ctx, "ROLLBACK")
+	return err
+}
+
+func getFailedLoginCount(s *session, user string, host string) (privileges.PasswordLocking, error) {
+	passwordLocking := privileges.PasswordLocking{}
+	ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+	_, err := s.ExecuteInternal(ctx, "BEGIN PESSIMISTIC")
```
Comment (bb7133) [inline session/session.go:2739]: Here we start an explicit transaction, but the 'COMMIT'/'ROLLBACK' code is placed in a lot of other places.

My concern is the code is vulnerable, could you improve it with something like:

```
Execute('BEGIN PESSIMISITC')
...
err, ... := authSuccessClearCount() / authFailedTracking()
if err == nil {
    Execute('COMMIT')
} else {
    Execute('ROLLBACK')
}
```
Is this possible?

Comment (keeplearning20221) [reply session/session.go]: done

File: privilege/privilege.go (hunk 52 above)
Comment (keeplearning20221) [reply privilege/privilege.go:61]: done

File: session/session.go (hunk 51 above)
Comment (keeplearning20221) [reply session/session.go:2670]: done

File: executor/simple.go [hunk 54]
```diff
@@ -820,85 +810,230 @@ func (e *SimpleExec) executeRollback(s *ast.RollbackStmt) error {
...
+		passwordLockingArray = append(passwordLockingArray, fmt.Sprintf("\"password_lock_time_days\": %d", info.passwordLockTime))
+	}
+	if len(passwordLockingArray) > 0 {
+		return fmt.Sprintf("\"Password_locking\": {%s}", strings.Join(passwordLockingArray, ","))
+	}
+	return ""
+}
+
+func readUserAttributes(ctx context.Context, sqlExecutor sqlexec.SQLExecutor, name string, host string, pLO *passwordOrLockOptionsInfo) (*alterUserPasswordLocking, error) {
+	alterUserInfo := &alterUserPasswordLocking{0, 0, false, false, false}
```
Comment (CbcWestwolf) [inline executor/simple.go:957]: Let's improve the code readability like
```go
	alterUserInfo := &alterUserPasswordLocking{
		failedLoginAttempts:  0, 
		passwordLockTime:   0, 
		failedLoginAttemptsNotFound: false, 
		passwordLockTimeChangeNotFound: false, 
		commentIsNull: false,
	}
```

File: executor/simple.go [hunk 55]
```diff
@@ -820,85 +810,230 @@ func (e *SimpleExec) executeRollback(s *ast.RollbackStmt) error {
...
-	return variable.TiDBOptOn(validatePwdEnable)
+	rows, err := sqlexec.DrainRecordSet(ctx, recordSet, 3)
+	if err != nil {
+		return nil, err
+	}
+
+	if pLO.failedLoginAttemptsChange {
+		alterUserInfo.failedLoginAttempts = pLO.failedLoginAttempts
+	} else {
+		FailedLoginAttempts := rows[0].GetString(0)
```
Comment (CbcWestwolf) [inline executor/simple.go:973]: Local variables should start with lower-case, since upper- or lower-case can used to specify public or private in Golang.

File: executor/simple.go [hunk 56]
```diff
@@ -820,85 +810,230 @@ func (e *SimpleExec) executeRollback(s *ast.RollbackStmt) error {
...
+		} else {
+			alterUserInfo.failedLoginAttempts = 0
+			alterUserInfo.failedLoginAttemptsNotFound = true
+		}
+	}
+
+	if pLO.passwordLockTimeChange {
+		alterUserInfo.passwordLockTime = pLO.passwordLockTime
+	} else {
+		PasswordLockTime := rows[0].GetString(1)
```
Comment (CbcWestwolf) [inline executor/simple.go:993]: ditto

File: executor/simple.go [hunk 57]
```diff
@@ -820,85 +810,230 @@ func (e *SimpleExec) executeRollback(s *ast.RollbackStmt) error {
...
+	}
+	if len(rows[0].GetString(2)) > 0 {
+		alterUserInfo.commentIsNull = false
+	} else {
+		alterUserInfo.commentIsNull = true
+	}
+	return alterUserInfo, nil
+}
+
+// deleteFailedLogin If FailedLoginAttempts = 0 and PasswordLockTime = 0 delete Password_locking info
```
Comment (CbcWestwolf) [inline executor/simple.go:1017]: ditto

File: executor/simple.go [hunk 58]
```diff
@@ -953,22 +1093,27 @@ func (e *SimpleExec) executeCreateUser(ctx context.Context, s *ast.CreateUserStm
...
 	}
-
 	sql := new(strings.Builder)
 	sqlPasswordHistory := new(strings.Builder)
 	passwordInit := true
 	// Get changed user password reuse info.
-	savePasswdHistory := whetherSavePasswordHistory(passwdlockinfo)
-	sqlTemplate := "INSERT INTO %n.%n (Host, User, authentication_string, plugin, user_attributes, Account_locked, Token_issuer, Password_expired, Password_lifetime, Password_reuse_time, Password_reuse_history) VALUES "
+	savePasswdHistory := whetherSavePasswordHistory(plInfo)
+	sqlTemplate := "INSERT INTO %n.%n (Host, User, authentication_string, plugin, user_attributes, Account_locked, Token_issuer, Password_expired, Password_lifetime,  Password_reuse_time, Password_reuse_history) VALUES "
```
Comment (CbcWestwolf) [inline executor/simple.go:1116]:
```suggestion
	sqlTemplate := "INSERT INTO %n.%n (Host, User, authentication_string, plugin, user_attributes, Account_locked, Token_issuer, Password_expired, Password_lifetime, Password_reuse_time, Password_reuse_history) VALUES "
```

File: privilege/privilege.go [hunk 59]
```diff
@@ -57,10 +57,26 @@ type Manager interface {
 	// RequestDynamicVerificationWithUser verifies a DYNAMIC privilege for a specific user.
 	RequestDynamicVerificationWithUser(privName string, grantable bool, user *auth.UserIdentity) bool
 
+	// VerifyAccountAutoLock automatically unlock when the time comes.
+	VerifyAccountAutoLock(user string, host string) (string, error)
+
+	// IsAccountAutoLockEnabled Verify whether the account enable Failed-Login Tracking and Temporary Account Locking.
```
Comment (CbcWestwolf) [inline privilege/privilege.go:63]:
```suggestion
	// IsAccountAutoLockEnabled verifies whether the account has enabled Failed-Login Tracking and Temporary Account Locking.
```

File: privilege/privilege.go [hunk 60]
```diff
@@ -57,10 +57,26 @@ type Manager interface {
...
+	IsAccountAutoLockEnabled(user string, host string) bool
+
+	// BuildPasswordLockingJSON Build PasswordLocking Json
```
Comment (CbcWestwolf) [inline privilege/privilege.go:66]:
```suggestion
	// BuildPasswordLockingJSON builds PasswordLocking JSON string.
```

File: privilege/privilege.go [hunk 61]
```diff
@@ -57,10 +57,26 @@ type Manager interface {
...
+	BuildPasswordLockingJSON(failedLoginAttempts int64,
+		passwordLockTimeDays int64, autoAccountLocked string, failedLoginCount int64, autoLockedLastChanged string) string
+
+	// BuildSuccessPasswordLockingJSON Build Success PasswordLocking Json
```
Comment (CbcWestwolf) [inline privilege/privilege.go:70]:
```suggestion
	// BuildSuccessPasswordLockingJSON builds success PasswordLocking JSON string.
```

File: privilege/privilege.go [hunk 62]
```diff
@@ -57,10 +57,26 @@ type Manager interface {
...
+	BuildSuccessPasswordLockingJSON(failedLoginAttempts, passwordLockTimeDays int64) string
+
 	// ConnectionVerification verifies user privilege for connection.
 	// Requires exact match on user name and host name.
 	ConnectionVerification(user *auth.UserIdentity, authUser, authHost string, auth, salt []byte, sessionVars *variable.SessionVars) error
 
+	// AuthSuccess Auth Success state
```
Comment (CbcWestwolf) [inline privilege/privilege.go:77]:
```suggestion
	// AuthSuccess records auth success state
```

File: privilege/privileges/privileges.go [hunk 63]
```diff
@@ -462,11 +553,11 @@ func (p *UserPrivileges) ConnectionVerification(user *auth.UserIdentity, authUse
 			hpwd, err := auth.DecodePassword(pwd)
 			if err != nil {
 				logutil.BgLogger().Error("decode password string failed", zap.Error(err))
-				return ErrAccessDenied.FastGenByArgs(user.Username, user.Hostname, hasPassword)
+				return &ErrUserPasswordFailed{ErrAccessDenied.FastGenByArgs(user.Username, user.Hostname, hasPassword)}
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:556]: Please add the following comment in the next line of `switch record.AuthPlugin {`
```go
// NOTE: If the checking of the password fails, please return the error wrap by ErrUserPasswordFailed.
```

File: privilege/privileges/privileges.go [hunk 64]
```diff
@@ -505,15 +596,19 @@ func (p *UserPrivileges) ConnectionVerification(user *auth.UserIdentity, authUse
...
-	p.user = authUser
-	p.host = record.Host
 	if sandBoxMode {
 		return &ErrInSandBoxMode{}
 	}
 	return nil
 }
 
+// AuthSuccess implements the Manager interface.
+// Auth Success state
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:606]: Please use a complete sentence to make the comment clear.

File: privilege/privileges/privileges.go [hunk 65]
```diff
@@ -829,3 +924,116 @@ func init() {
 	extension.RegisterDynamicPrivilege = RegisterDynamicPrivilege
 	extension.RemoveDynamicPrivilege = RemoveDynamicPrivilege
 }
+
+// PasswordLocking user PasswordLocking info
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:928]: DITTO

Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:928]:
```suggestion
// PasswordLocking records information about failed-login tracking and temporary account locking.
```

File: privilege/privileges/privileges.go [hunk 66]
```diff
@@ -829,3 +924,116 @@ func init() {
...
+type PasswordLocking struct {
+	FailedLoginCount      int64
+	PasswordLockTimeDays  int64
+	AutoAccountLocked     bool
+	AutoLockedLastChanged int64
+	FailedLoginAttempts   int64
+}
+
+// PasswordLockingParser parser PasswordLocking info
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:937]:
```suggestion
// PasswordLockingParser parses information about PasswordLocking.
```

File: privilege/privileges/privileges.go [hunk 67]
```diff
@@ -829,3 +924,116 @@ func init() {
...
+
+	passwordLocking.AutoAccountLocked, found, parserErr =
+		PasswordLockingBoolParser(passwordLockingJSON, "$.Password_locking.auto_account_locked")
+	if parserErr != nil && found {
+		return parserErr
+	}
+	return nil
+}
+
+// PasswordLockingInt64Parser parser Int64 PasswordLocking info
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:991]: DITTO

File: privilege/privileges/privileges.go [hunk 68]
```diff
@@ -829,3 +924,116 @@ func init() {
...
+	if err != nil {
+		return 0, true, err
+	}
+	if BJ, found := passwordLockingJSON.Extract([]types.JSONPathExpression{jsonPath}); found {
+		return BJ.GetInt64(), true, nil
+	}
+	return 0, false, fmt.Errorf("user_attributes not found by `%s`", jsonPath)
+}
+
+// PasswordLockingTimeUnixParser parser TimeUnix PasswordLocking info
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:1003]: DITTO

File: privilege/privileges/privileges.go [hunk 69]
```diff
@@ -829,3 +924,116 @@ func init() {
...
+		t, timeErr := time.ParseInLocation(time.UnixDate, value, time.Local)
+		if timeErr != nil {
+			return -1, true, timeErr
+		}
+		return t.Unix(), true, nil
+	}
+	return 0, false, fmt.Errorf("user_attributes not found by `%s`", jsonPath)
+}
+
+// PasswordLockingBoolParser parser Bool PasswordLocking info
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges.go:1023]: DITTO

File: session/session.go [hunk 70]
```diff
@@ -2621,22 +2621,215 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
 	if err != nil {
 		return privileges.ErrAccessDenied.FastGenByArgs(user.Username, user.Hostname, hasPassword)
 	}
-	if err := pm.ConnectionVerification(user, authUser.Username, authUser.Hostname, authentication, salt, s.sessionVars); err != nil {
+	//Check whether continuous login failure is enabled to lock the account.
+	//If enabled, determine whether to unlock the account and notify TiDB to update the cache
```
Comment (CbcWestwolf) [inline session/session.go:2625]:
```suggestion
	// Check whether continuous login failure is enabled to lock the account.
	// If enabled, determine whether to unlock the account and notify TiDB to update the cache
```

File: privilege/privileges/privileges.go (hunk 63 above)
Comment (keeplearning20221) [reply privilege/privileges/privileges.go:559]: done

File: privilege/privileges/privileges.go (hunk 64 above)
Comment (keeplearning20221) [reply privilege/privileges/privileges.go]: done

File: session/session.go [hunk 71]
```diff
@@ -2621,22 +2622,298 @@ func (s *session) Auth(user *auth.UserIdentity, authentication, salt []byte) err
...
+	if err != nil {
+		return err
+	}
+	return nil
+}
+func failedLoginTrackingBegin(s *session) error {
+	ctx := kv.WithInternalSourceType(context.Background(), kv.InternalTxnPrivilege)
+	_, err := s.ExecuteInternal(ctx, "BEGIN PESSIMISTIC")
+	if err != nil {
+		if rollBackErr := failedLoginTrackingRollback(s); rollBackErr != nil {
```
Comment (bb7133) [inline session/session.go:2823]: You don't need to make a 'ROLLBACK' here, since the begin of transaction failed.

File: privilege/privilege.go [hunk 72]
```diff
@@ -57,10 +57,23 @@ type Manager interface {
 	// RequestDynamicVerificationWithUser verifies a DYNAMIC privilege for a specific user.
 	RequestDynamicVerificationWithUser(privName string, grantable bool, user *auth.UserIdentity) bool
 
+	// IsAccountAutoLockEnabled verifies whether the account has enabled Failed-Login Tracking and Temporary Account Locking.
+	IsAccountAutoLockEnabled(user string, host string) bool
+
+	// BuildPasswordLockingJSON builds PasswordLocking JSON string.
+	BuildPasswordLockingJSON(failedLoginAttempts int64,
```
Comment (bb7133) [inline privilege/privilege.go:64]: Is `BuildPasswordLockingJSON` and `BuildSuccessPasswordLockingJSON` required for `Manager` interface? Could we turn it to a package function instead of interface function?

File: executor/simpletest/simple_test.go [hunk 73]
```diff
@@ -1343,3 +1528,152 @@ func TestUserAlterUser(t *testing.T) {
...
+
+	rootTK.MustExec(`Alter user test1  account unlock `)
+	rootTK.MustQuery(sql.String()).Check(testkit.Rows(`<nil> <nil> <nil> <nil> {"comment": "test2"}`))
+	rootTK.MustExec(`Alter user test1  FAILED_LOGIN_ATTEMPTS 4 `)
+	rootTK.MustQuery(sql.String()).Check(testkit.Rows(`4 <nil> <nil> 0 {"comment": "test2"}`))
+	rootTK.MustExec(`Alter user test1  account unlock `)
+	rootTK.MustQuery(sql.String()).Check(testkit.Rows(`4 "N" 0 0 {"comment": "test2"}`))
+}
+
+func TestMixPasswordPolicy(t *testing.T) {
```
Comment (CbcWestwolf) [inline executor/simpletest/simple_test.go:1606]: `TestPasswordManagement`

File: privilege/privileges/privileges_test.go [hunk 74]
```diff
@@ -3104,3 +3108,578 @@ func TestPasswordExpireWithSandBoxMode(t *testing.T) {
 	require.NoError(t, err)
 	require.False(t, tk.Session().InSandBoxMode())
 }
+
+func TestFailedLoginTrackingCheckError(t *testing.T) {
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges_test.go:3112]: `TestFailedLoginTracking`

File: privilege/privileges/privileges_test.go [hunk 75]
```diff
@@ -3104,3 +3108,578 @@ func TestPasswordExpireWithSandBoxMode(t *testing.T) {
...
+	err = tk.Session().Auth(&auth.UserIdentity{Username: "testu4", Hostname: "localhost"}, sha1Password("password"), nil)
+	require.True(t, strings.Contains(err.Error(), "Access denied for user 'testu4'@'localhost' (using password: YES)"))
+	checkAuthUser(t, tk, "testu4", 0, "")
+	tk.MustExec("CREATE USER 'testu5'@'localhost' IDENTIFIED BY 'testu5' FAILED_LOGIN_ATTEMPTS 0 PASSWORD_LOCK_TIME 0")
+	err = tk.Session().Auth(&auth.UserIdentity{Username: "testu5", Hostname: "localhost"}, sha1Password("password"), nil)
+	require.True(t, strings.Contains(err.Error(), "Access denied for user 'testu5'@'localhost' (using password: YES)"))
+	tk.MustQuery("select user_attributes from mysql.user where user= 'testu5' and host = 'localhost'").Check(testkit.Rows("{\"resource_group\": \"default\"}"))
+}
+
+func TestFailedLoginTrackingWithSpecifiedUserUserAttributes(t *testing.T) {
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges_test.go:3160]: `TestFailedLoginTracking`

File: privilege/privileges/privileges_test.go [hunk 76]
```diff
@@ -3104,3 +3108,578 @@ func TestPasswordExpireWithSandBoxMode(t *testing.T) {
...
+		sha1Password("password"), nil))
+	checkUserUserAttributes(tk, "testu12", "localhost", "2 \"Y\" 2 1 {\"comment\": \"testcomment\"}")
+	tk.MustExec("alter user testu12@'localhost' FAILED_LOGIN_ATTEMPTS 0")
+	checkUserUserAttributes(tk, "testu12", "localhost", "0 \"Y\" 2 1 {\"comment\": \"testcomment\"}")
+	sk4 := testkit.NewTestKit(t, store)
+	require.NoError(t, sk4.Session().Auth(&auth.UserIdentity{Username: "testu12", Hostname: "localhost"},
+		nil, nil))
+}
+
+func TestFailedLoginTrackingAlterUser(t *testing.T) {
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges_test.go:3304]: `TestFailedLoginTrackingAlterUser` in `simple_test.go`

File: privilege/privileges/privileges_test.go [hunk 77]
```diff
@@ -3104,3 +3108,578 @@ func TestPasswordExpireWithSandBoxMode(t *testing.T) {
...
+	createAndCheck(tk, "CREATE USER 'testu1'@'localhost' IDENTIFIED BY '' FAILED_LOGIN_ATTEMPTS 1 PASSWORD_LOCK_TIME 1",
+		"{\"Password_locking\": {\"failed_login_attempts\": 1, \"password_lock_time_days\": 1}, \"resource_group\": \"default\"}", "testu1")
+	require.NoError(t, tk.Session().Auth(&auth.UserIdentity{Username: "testu1", Hostname: "localhost"}, nil, nil))
+	// Specify FAILED_LOGIN_ATTEMPTS and PASSWORD_LOCK_TIME attributes when creating user ,
+	// Check user privileges  after successful login.
+	tk.MustQuery(`show grants`).Check(testkit.Rows("GRANT USAGE ON *.* TO 'testu1'@'localhost'"))
+	tk.MustQuery(`select user()`).Check(testkit.Rows("testu1@localhost"))
+}
+
+func TestFailedLoginTracking(t *testing.T) {
```
Comment (CbcWestwolf) [inline privilege/privileges/privileges_test.go:3431]: `TestFailedLoginTracking`

**Review by bb7133 — APPROVED** [review]
LGTM
