### PR TITLE
*: fix a bug caused by the wrong collation setting which leads to the wrong result of collation function

### LINKED ISSUE #17115: select collation(user()) get wrong result.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
mysql> select collation(user());

+-------------------+
| collation(user()) |
+-------------------+
|                   |
+-------------------+
1 row in set (0.00 sec)

```

besides:

```
mysql> select collation(compress('abc'));
+--------------------------------------------------------+
| collation(compress('abc'))                             |
+--------------------------------------------------------+
| 0x62696E617279                                         |
+--------------------------------------------------------+
1 row in set (0.00 sec)
```

These results are all wrong.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #17115 

Problem Summary:
1. We didn't set `collation_connection` if the collate is illegal.
2. The result collation of `collation` function shouldn't use the argument's collation, or it will lead to unreadable binary output if the collation is `binary`. 

### What is changed and how it works?

1. set the collation to default collation according to the charset if it's illegal.  
2. Set the result collation to `collation_connection` for `collation` function.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

### Release note 
- Fix a bug caused by the wrong collation setting which leads to the wrong result of collation function.

### CODE REVIEW

File: sessionctx/variable/session.go [hunk 1]
```diff
@@ -1245,7 +1246,25 @@ func (s *SessionVars) SetSystemVar(name string, val string) error {
 		s.MetricSchemaRangeDuration = tidbOptInt64(val, DefTiDBMetricSchemaRangeDuration)
 	case CollationConnection, CollationDatabase, CollationServer:
 		if _, err := collate.GetCollationByName(val); err != nil {
-			return errors.Trace(err)
+			var ok bool
+			var charsetVal string
+			var err2 error
+			if name == CollationConnection {
```
Comment (bb7133) [inline sessionctx/variable/session.go:1252]: Using a `switch`?

Comment (wjhuang2016) [reply sessionctx/variable/session.go:1252]: Double `switch` makes the code complicated.
I think it's fine since there are only three branches. If four, then I will use `switch`

File: sessionctx/variable/session.go [hunk 2]
```diff
@@ -1245,7 +1246,25 @@ func (s *SessionVars) SetSystemVar(name string, val string) error {
 		s.MetricSchemaRangeDuration = tidbOptInt64(val, DefTiDBMetricSchemaRangeDuration)
 	case CollationConnection, CollationDatabase, CollationServer:
 		if _, err := collate.GetCollationByName(val); err != nil {
```
Comment (qw4990) [inline sessionctx/variable/session.go:1248]: If this collation is invalid, MySQL returns an error instead of using the default collation of current charset.
```
mysql> set collation_connection='23';
ERROR 1273 (HY000): Unknown collation: '23'
```
