### PR TITLE
lightning: only retry on retryable error on import engine

### LINKED ISSUE #33446: Lightning retry too much when tikv storage is full
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Use lightning to import 60K tables to tidb cluster, TiKV space was full during import process 

### 2. What did you expect to see? (Required)
1. Lightning should fail quickly when tikv doesn't have enough space.

### 3. What did you see instead (Required)
1. Lightning keep retrying for different tables for over 16 hours, before I have to manually stop it.

```
[root@zhengrong-24 lightning]# grep "The available disk of TiKV" tidb-lightning.log |grep 105.44 |head
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.971 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=0]
[2022/03/23 23:01:27.972 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=1]
[2022/03/23 23:01:27.972 +08:00] [WARN] [local.go:1153] ["write to tikv failed"] [error="The available disk of TiKV (172.16.105.44:50160) only left 392774759219, and capacity is 3937351139065"] [retry=1]
[root@zhengrong-24 lightning]#
[root@zhengrong-24 lightning]#
[root@zhengrong-24 lightning]# grep "The available disk of TiKV" tidb-lightning.log |grep 105.44 |tail
[2022/03/24 16:28:05.357 +08:00] [ERROR] [restore.go:168] [-] [table=`Abetting_0`.`15unit_8_game_bets_all_analysis`] [status=imported] [error="[277a6aea-8948-5a38-ae13-b38e88c9a1ca] import reach max retry 3 and still failed: The available disk of TiKV (172.16.105.44:50160) only left 392452636672, and capacity is 3937351139065; The available disk of TiKV (172.16.105.44:50160) only left 392452636672, and capacity is 3937351139065"]
[2022/03/24 16:28:05.357 +08:00] [ERROR] [restore.go:168] [-] [table=`Abetting_0`.`14unit_0_game_bets_game_tag_analysis_1`] [status=imported] [error="[19832b46-1e76-5c2a-bfd9-1151f2234e9b] import reach max retry 3 and still failed: The available disk of TiKV (172.16.105.44:50160) only left 392452636672, and capacity is 3937351139065; The available disk of TiKV (172.16.105.44:50160) only left 392452636672, and capacity is 3937351139065"]
[2022/03/24 16:28:05.357 +08:00] [ERROR] [restore.go:168] [-] [table=`Abetting_0`.`12unit_2_game_bets_game_tag_analysis_2`] [status=imported] [error="[b414cffd-bcea-5e8b-a60f-fe0ed241c148] import reach max retry 3 and still failed: The available disk of TiKV (172.16.105.44:50160) only left 392452636672, and capacity is 3937351139065; The available disk of TiKV (172.16.105.44:50160) only left 392452636672, and capacity is 3937351139065"]

```
### 4. What is your TiDB version? (Required)
[root@zhengrong-24 lightning]# ./tidb-lightning -V
Release Version: v6.0.0
Git Commit Hash: e130e522904106ecf9815fdb3aaccad68dcb5ee0
Git Branch: heads/refs/tags/v6.0.0
Go Version: go1.18
UTC Build Time: 2022-03-18 07:34:51
Race Enabled: false

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #33446

Problem Summary:

### What is changed and how it works?
as title

- this pr only fail fast on error of one table, other tables will continue. in this case should we progress as much as possible?

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - restore one table 20g into tikv with 10g space.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fail fast on non-retryable error during import engine
```

### CODE REVIEW

**Comment by gozssky** [comment]
> /cc @gozssky @lance6716 @dsdashun ptal

@D3Hunter  This PR is still in draft status. It is ready for review?

**Comment by D3Hunter** [comment]
ready now, add an integration test.

ping @gozssky @lance6716

**Review by gozssky — COMMENTED** [review]
rest LGTM

**Comment by gozssky** [comment]
Unit test failed
```
[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44585/pipeline#step-73-log-239)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44585/pipeline#step-73-log-240)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44585/pipeline#step-73-log-241)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44585/pipeline#step-73-log-242)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44585/pipeline#step-73-log-243)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/44585/pipeline#step-73-log-244)[2022-04-11T12:13:08.223Z] === Failed

[2022-04-11T12:13:08.223Z] === FAIL: br/pkg/lightning/backend TestImportFailedRecovered (0.00s)

[2022-04-11T12:13:08.223Z]     backend_test.go:300: 

[2022-04-11T12:13:08.223Z]         	Error Trace:	backend_test.go:300

[2022-04-11T12:13:08.223Z]         	Error:      	Received unexpected error:

[2022-04-11T12:13:08.223Z]         	            	fake recoverable import error

[2022-04-11T12:13:08.223Z]         	            	github.com/pingcap/tidb/br/pkg/lightning/backend_test.TestImportFailedRecovered
```

File: br/tests/lightning_fail_fast_on_nonretry_err/run.sh [hunk 1]
```diff
@@ -0,0 +1,24 @@
+#!/bin/sh
+
+set -eu
+
+run_sql 'DROP DATABASE IF EXISTS csv'
+
+out_file_name="$TEST_DIR/sql_res.$TEST_NAME.txt"
+export GO_FAILPOINTS="github.com/pingcap/tidb/br/pkg/lightning/backend/local/WriteToTiKVNotEnoughDiskSpace=return(true)"
+start_time=$(date +'%s')
+run_lightning --backend local > $out_file_name 2>&1 || true
```
Comment (dsdashun) [inline br/tests/lightning_fail_fast_on_nonretry_err/run.sh:10]: I think the `|| true` is not necessary.  Instead we can check if the return code is 0, it is not expected and exit early.

File: br/tests/lightning_fail_fast_on_nonretry_err/run.sh [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+export GO_FAILPOINTS=""
+check_contains "The available disk of TiKV"
+used_time=$(($(date +'%s') - $start_time))
+echo "time used to run lightning ${used_time}s"
+# writeAndIngestByRanges will retry for at least 810s on retryable error
+if [ $used_time -ge 60 ]; then
```
Comment (dsdashun) [inline br/tests/lightning_fail_fast_on_nonretry_err/run.sh:16]: Running a lightning with 810s is too long.  Consider use the `timeout` command.  In this way we even don't need to collect the start time and end time
```bash
timeout 30 run_lightning --backend local > "$out_file_name" 2>&1
lightning_exit_code=$?
case "$lightning_exit_code" in
    0)
        echo "lightning exits normally, but we expect it exit with an abnormal exit code" >&2
        exit 1
        ;;
    124)
        echo "lightning running too long, seems like it doesn't fail fast" >&2
        exit 1
        ;;
esac
```

File: br/tests/lightning_fail_fast_on_nonretry_err/run.sh [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+  echo "lightning failed to fail fast"
+  exit 1
+fi
+
+run_sql 'SELECT count(*) FROM csv.threads'
```
Comment (dsdashun) [inline br/tests/lightning_fail_fast_on_nonretry_err/run.sh:21]: If run_sql returns error, should exit here.  Otherwise the next `check_contains` will exit normally and the whole test will pass

File: br/tests/lightning_fail_fast_on_nonretry_err/run.sh [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+set -eu
+
+run_sql 'DROP DATABASE IF EXISTS csv'
+
+out_file_name="$TEST_DIR/sql_res.$TEST_NAME.txt"
+export GO_FAILPOINTS="github.com/pingcap/tidb/br/pkg/lightning/backend/local/WriteToTiKVNotEnoughDiskSpace=return(true)"
+start_time=$(date +'%s')
+run_lightning --backend local > $out_file_name 2>&1 || true
+export GO_FAILPOINTS=""
+check_contains "The available disk of TiKV"
```
Comment (dsdashun) [inline br/tests/lightning_fail_fast_on_nonretry_err/run.sh:12]: If `check_contains` fails, it should exit immediately with an error code

Comment (gozssky) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:12]: `set -eu` has been set at the beginning, so it will exit immediately if check_contains fails.

Comment (dsdashun) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:12]: OK.  Then I understand why appending a `|| true` at the `run_lightning` command

**Review by gozssky — APPROVED** [review]

**Comment by D3Hunter** [comment]
ping @lance6716

File: br/tests/lightning_fail_fast_on_nonretry_err/run.sh (hunk 3 above)
Comment (D3Hunter) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:21]: check https://github.com/pingcap/tidb/pull/33794#discussion_r849020070

File: br/tests/lightning_fail_fast_on_nonretry_err/run.sh (hunk 1 above)
Comment (D3Hunter) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:10]: check https://github.com/pingcap/tidb/pull/33794#discussion_r849020070

File: br/tests/lightning_fail_fast_on_nonretry_err/run.sh (hunk 2 above)
Comment (D3Hunter) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:16]: should not happen in this case since the error is not retryable now.

Comment (dsdashun) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:16]: Right, currently the timeout won't happen.  I just consider in the future, if someone changes the Lightning behavior unexpectedly, making the Lightning not fail fast for this test, the timeout mechanism can prevent the Lightning from running too long.

Comment (D3Hunter) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:16]: mac don't has `timeout`(may need to install using brew)

will not change it, the case will fail in CI anyway, and the whole CI takes more than 30m, so we can wait.

Comment (dsdashun) [reply br/tests/lightning_fail_fast_on_nonretry_err/run.sh:16]: OK.  Got it

**Review by dsdashun — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
ping @lance6716

**Review by lance6716 — APPROVED** [review]

**Comment by D3Hunter** [comment]
@lance6716 please help with merge
