### PR TITLE
globalsort: skip retry when context has error

### LINKED ISSUE #58826: global sort should not bother to retry when context has error
## Bug Report

https://github.com/pingcap/tidb/blob/448e302b39bd204855aa894abbc4776425f2b06f/pkg/lightning/backend/external/writer.go#L464-L473

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #58826

Problem Summary:

### What changed and how does it work?

just a log improvement

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/backend/external/writer.go [hunk 1]
```diff
@@ -463,7 +463,7 @@ func (w *Writer) flushKVs(ctx context.Context, fromClose bool) (err error) {
 	var dataFile, statFile string
 	for i := 0; i < flushKVsRetryTimes; i++ {
 		dataFile, statFile, err = w.flushSortedKVs(ctx)
-		if err == nil {
+		if err == nil || ctx.Err() != nil {
```
Comment (Benjamin2037) [inline pkg/lightning/backend/external/writer.go:466]: Normally, Can we know which errors that ctx may occur during global sort period? Dose all of them can cause tasks return?

**Review by D3Hunter — APPROVED** [review]

File: pkg/lightning/backend/external/writer.go (hunk 1 above)
Comment (lance6716) [reply pkg/lightning/backend/external/writer.go:466]: here I didn't want to check error. I check that user context is canceled (although the interface is `ctx.Err()`). When context is canceled, this for loop will run `flushKVsRetryTimes` times but immediately `flushSortedKVs` will return because of `ctx.Err()`, and below log line will be printed unnecessarily.

**Review by joccau — APPROVED** [review]
