### PR TITLE
server: fix deadlock when call `killNonFlashbackConn`

### LINKED ISSUE #38862: tidb deadlock during flashback with workload
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. stop all tiflash nodes in cluster
2. run flashback

### 2. What did you expect to see? (Required)
flashback successfully 

### 3. What did you see instead (Required)
tidb can't access
tidb down

### 4. What is your TiDB version? (Required)

Release Version: v6.4.0-alpha-210-g8db7c3b30-dirty
Edition: Community
Git Commit Hash: 8db7c3b30e9a65652eb809f2f8ef303c424f260e
Git Branch: master
UTC Build Time: 2022-11-03 01:42:35
GoVersion: go1.19

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #38862

Problem Summary:

1. update client-go to fix https://github.com/tikv/tikv/issues/13675
2. fix deadlock for `killNonFlashbackConn`, it require the read lock at https://github.com/pingcap/tidb/blob/5ee578c21b3e632aed3df26e22bcc47ad8a23f70/server/server.go#L946, then try to get read lock in `s.Kill()` func, if another write lock require in between, like close/create conn, it will deadlock forever.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```
use tpcc workload, then execute flashback, no deadlock anymore.
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -943,21 +943,25 @@ func (s *Server) CheckOldRunningTxn(job2ver map[int64]int64, job2ids map[int64]s
 
 // KillNonFlashbackClusterConn implements SessionManager interface.
 func (s *Server) KillNonFlashbackClusterConn() {
+	connIDs := make([]uint64, 0)
```
Comment (zimulala) [inline server/server.go:946]: Maybe we can do `connIDs := make([]uint64, 0, len(s.clients))`

**Review by zimulala — APPROVED** [review]
Rest LGTM

**Review by hawkingrei — APPROVED** [review]

**Review by dveeden — APPROVED** [review]
