### PR TITLE
ddl: Fix Global Index consistency during some ALTER PARTITION states.

### LINKED ISSUE #63870: TestMultiSchemaPartitionByGlobalIndex failed after disabling `tidb_enable_fast_table_check` in test
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Set `tidb_enable_fast_table_check` to 0 in test `TestMultiSchemaPartitionByGlobalIndex`
### 2. What did you expect to see? (Required)
Test pass 
### 3. What did you see instead (Required)
Test fail
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #63870

Problem Summary:
1) During `ALTER TABLE t REORGANIZE PARTITION` the global index was rebuild and would miss entries that should have been inserted during the DDL states `StateDeleteReorganization` and `StatePublic`.

2) And during `ALTER TABLE t TRUNCATE PARTITION` when the global index was cleared from entries from the truncated partitions, there were no check if the deleted entries belonged to the truncated partition, or if they were new, overwritten, entries from new transactions on other partitions, resulting in deleting the already up-to-date entries, making the global index inconsistent.

### What changed and how does it work?
1) Used the simplified `DDLChangedIndex` map for checking if the index was new and should use the new table id, instead of the index state.

2) When cleaning up global index entries from truncated/dropped partitions first check that the entries are coming from that partition, as well as lock those entries that are to be deleted.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
During some Partitioning DDLs and concurrent writes, in some conditions global indexes could be left inconsistent.
```

### CODE REVIEW

File: pkg/ddl/index.go [hunk 1]
```diff
@@ -3364,13 +3364,52 @@ func (w *cleanUpIndexWorker) BackfillData(_ context.Context, handleRange reorgBa
...
+					if partHandle.PartitionID != handleRange.physicalTable.GetPhysicalID() {
+						continue
+					}
+				}
+				// Lock the global index entry, to prevent deleting something that is concurrently added.
+				err = txn.LockKeys(ctx, lockCtx, allKeys[i])
+				if err != nil {
+					return errors.Trace(err)
+				}
+			}
```
Comment (mjonss) [inline pkg/ddl/index.go:3408]: Fix for ALTER TABLE t TRUNCATE PARTITION, where the Global Index Cleanup can remove entries from the truncated partition, that been overwritten by user transactions during `StateDeleteReorganization`.

Code is similar to `(w *reorgPartitionWorker) BackfillData()`.

File: pkg/table/tables/index.go [hunk 2]
```diff
@@ -82,11 +82,13 @@ func (c *index) TableMeta() *model.TableInfo {
...
 		pi := c.tblInfo.GetPartitionInfo()
-		if pi.NewTableID != 0 && c.idxInfo.State != model.StatePublic {
-			idxTblID = pi.NewTableID
-		} else {
-			idxTblID = c.tblInfo.ID
+		if pi != nil && pi.NewTableID != 0 {
+			isNew, ok := pi.DDLChangedIndex[c.idxInfo.ID]
+			if ok && isNew {
+				idxTblID = pi.NewTableID
+			}
```
Comment (mjonss) [inline pkg/table/tables/index.go:91]: Fix for ALTER TABLE t REORGANIZE PARTITION, where global index entries were not added to the new global index, in PartitionInfo `StatePublic` and `StateDeleteReorg` (different from index State!).
