### PR TITLE
ddl, disttask: add scan-region check before dispatch subtasks

### LINKED ISSUE #50895: data inconsistency in table after upgrade cluster v7.5.0 to nightly with dist task add index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a 7.5.0 cluster
    2. set global tidb_ddl_enable_fast_reorg=1; set global tidb_enable_dist_task=1
    3. do add index
    4. duraing add index, upgrade the cluster to nightly (c76fe3ff97d89d773300a4ef03753fff4e3)
    5. check the add index ddl jobs

### 2. What did you expect to see? (Required)
add index success and admin check index success
### 3. What did you see instead (Required)
```sql
Error 8223 (HY000): data inconsistency in table: sbtest1, index: idxc, handle: 3638162, index-values:"" != record-values:"handle: 3
638162, values: [KindString 57802534654-92849495096-76700988535-10378989958-21593928040-21624571867-11827492765-27178917465-96771938022-517
64534826 KindString 78352395649-41653856744-14528110070-99012720503-38484627267]"
```
for more information, you can find from [here](https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7330357576361643363?from=1706728640&to=1706735840)
### 4. What is your TiDB version? (Required)
v7.5.0 -> nightly (c76fe3ff97d89d773300a4ef03753fff4e3)

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #50895

Problem Summary: See https://github.com/pingcap/tidb/issues/50895#issuecomment-1958889520

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/backfilling_dist_scheduler.go [hunk 1]
```diff
@@ -279,40 +286,62 @@ func generateNonPartitionPlan(
...
-	for i := 0; i < len(recordRegionMetas); i += regionBatch {
-		end := i + regionBatch
-		if end > len(recordRegionMetas) {
-			end = len(recordRegionMetas)
-		}
-		batch := recordRegionMetas[i:end]
-		subTaskMeta := &BackfillSubTaskMeta{
-			RowStart: batch[0].StartKey(),
-			RowEnd:   batch[len(batch)-1].EndKey(),
+	backoffer := backoff.NewExponential(scanRegionBackoffBase, 2, scanRegionBackoffMax)
```
Comment (ywqzzy) [inline pkg/ddl/backfilling_dist_scheduler.go:290]: Can we use handle.RunWithRetry?

**Review by Benjamin2037 — APPROVED** [review]
LGTM
