### PR TITLE
br: fix debug decode backupmeta

### LINKED ISSUE #56296: `br debug decode` is useless when the backupmeta file got split.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Generate a full backup locally `br backup full -s '/tmp/testbr`
2. Decode the backupmeta file `br debug decode -s '/tmp/testbr`

### 2. What did you expect to see? (Required)

The entire content of the backupmeta can be readable in JSON

### 3. What did you see instead (Required)

We can only see the main `backupmeta.json` is referring to the split-off files:

```json
{
  "ddls": [],
  "cluster_id": 7418281098110393269,
  "cluster_version": "8.1.0",
  "br_version": "«snip»",
  "version": 1,
  "file_index": {
    "meta_files": [
      {
        "name": "backupmeta.datafile.000000001",
        "sha256": "2XIqo5osORmCTs0fWf0T59xYI98i6nZ/5IdqYwNQmF0=",
        "size": 4623
      }
    ]
  },
  "end_version": 452789007127937031,
  "schema_index": {
    "meta_files": [
      {
        "name": "backupmeta.schema.000000002",
        "sha256": "p2CbZh4isJ7lRdFWDoa/rQEYsV+0jr/v2KzX0JT2GeE=",
        "size": 290142
      }
    ]
  },
  "new_collations_enabled": "True",
  "backup_size": 401424
}
```

and the split-off files are *not* decoded into JSON:

```console
$ ls -aF1 /tmp/testbr
./
../
1/
backup.lock
backupmeta
backupmeta.datafile.000000001
backupmeta.json
backupmeta.schema.000000002
checkpoints/
```

### 4. What is your TiDB version? (Required)

checked on v8.1.0, master.

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #56296

Problem Summary:
We can only see the main `backupmeta.json`.
### What changed and how does it work?
decode the meta file and stats file.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

```
$ ls -aF1 /tmp/testbr
./
../
1/
backup.lock
backupmeta
backupmeta.datafile.000000001
backupmeta.schema.000000002
backupmeta.schema.stats.000000110
jsons/

$ ls -aF1 /tmp/testbr/jsons
./
../
backupmeta.datafile.000000001.json
backupmeta.json
backupmeta.schema.000000002.json
backupmeta.schema.stats.000000110.json
```

```
backupmeta.datafile.000000001.json

{
  "data_files": [
    {
      "name":"..",
      "sha256":"lu4KiCseT0M6dG2gghZXDwD5WOUOqDMhYKcLHMuDYGA=",
      "start_key":"..",
      "end_key":"..",
      "end_version":452625823236882437,
      "crc64xor":17088955387164552884,
      "total_kvs":1,
      "total_bytes":47,
      "cf":"write",
      "size":1673,
      "cipher_iv":..,
    },
    ...
  ],
}
```

```
backupmeta.schema.000000002.json

{
  "schemas":[
    {
      "db": ..,
      "table": ..,
      "crc64xor":4505190652257934775,
      "total_kvs":32,
      "total_bytes":3031,
    },
    ...
  ],
}
```

```
backupmeta.schema.stats.000000110.json

{
  "blocks":[
    {
      "physical_id":110,
      "json_table": ..,
    },
}
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

File: br/pkg/metautil/debug.go [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+	ctx context.Context,
+	s storage.ExternalStorage,
+	cipher *backuppb.CipherInfo,
+	metaIndex *backuppb.MetaFile,
+) error {
+	if metaIndex == nil {
+		return nil
+	}
+	eg, ectx := errgroup.WithContext(ctx)
+	workers := tidbutil.NewWorkerPool(8, "download files workers")
```
Comment (BornChanger) [inline br/pkg/metautil/debug.go:90]: is it possible to make the pool size configurable or at least move 8 to constant definition section in l33.

**Review by YuJuncen — APPROVED** [review]
