### PR TITLE
ddl: fix unexpected duplicate entry error when adding unique index

### LINKED ISSUE #56161: adding unique index reports "duplicate entry" unexpectedly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Start a workload that contains DMLs(like `REPLACE INTO`) on the target table.
2. Add a unique index.

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

Duplicate entry '?' for key 'idx'

### 4. What is your TiDB version? (Required)

c13eb90fcf0e

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #56161

Problem Summary: when merge-temp-index workers check duplicate index keys, they use `BatchGet()` to get index KV from the origin index and record them as a map. However, this map is not updated while handling temp index records, there may be a false-positive detection.

For example, we have `{key_1 -> handle_1, key_2 -> handle_2}`. If there is a temp index record like `key_1 -> handle_3`, then there is a duplicate key. 

In this issue, we have two temp index records:

```
key_1 -> handle_1(deleted)
key_1 -> handle_2
```

The first record passes the check because a delete operation cannot cause a duplicate key. The second record fails the check because `handle_2 != handle_1`, even if `handle_1` is deleted in the previous operation.

### What changed and how does it work?

Maintain the map while handling, and remove the delete keys if necessary.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/ddl/index_merge_tmp.go [hunk 1]
```diff
@@ -49,44 +49,54 @@ func (w *mergeIndexWorker) batchCheckTemporaryUniqueKey(
...
 		}
 	}
 	return nil
 }
 
-func checkTempIndexKey(txn kv.Transaction, tmpRec *temporaryIndexRecord, originIdxVal []byte, tblInfo table.Table) error {
+// checkTempIndexKey determines whether there is a duplicated index key entry according to value of temp index.
+// For non-delete temp record, if the index values mismatch, it is duplicated.
+// For delete temp record, we decode the handle from the origin index value and temp index value.
+//   - if the handles matche, we can delete the index key.
```
Comment (lance6716) [inline pkg/ddl/index_merge_tmp.go:78]:
```suggestion
//   - if the handle matches, we can delete the index key.
```

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]
