### PR TITLE
ddl: fill correct involved schemainfo for 'flashback table' and 'flashback schema'

### LINKED ISSUE #54134: flaky test TestParallelFlashbackTable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
    db_change_failpoints_test.go:160: 
        	Error Trace:	pkg/ddl/db_change_failpoints_test.go:160
        	            				pkg/ddl/db_change_test.go:1414
        	            				pkg/ddl/db_change_failpoints_test.go:169
        	Error:      	Received unexpected error:
        	            	[schema:1050]Table 't_flashback2' already exists
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:178
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).DoDDLJob
        	            		pkg/ddl/ddl.go:1323
        	            	github.com/pingcap/tidb/pkg/ddl.(*ddl).RecoverTable
        	            		pkg/ddl/ddl_api.go:3252
        	            	github.com/pingcap/tidb/pkg/executor.(*DDLExec).executeFlashbackTable
        	            		pkg/executor/ddl.go:595
        	            	github.com/pingcap/tidb/pkg/executor.(*DDLExec).Next
        	            		pkg/executor/ddl.go:179
        	            	github.com/pingcap/tidb/pkg/executor/internal/exec.Next
        	            		pkg/executor/internal/exec/executor.go:410
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next
        	            		pkg/executor/adapter.go:1238
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor
        	            		pkg/executor/adapter.go:987
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay
        	            		pkg/executor/adapter.go:821
        	            	github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec
        	            		pkg/executor/adapter.go:585
        	            	github.com/pingcap/tidb/pkg/session.runStmt
        	            		pkg/session/session.go:2289
        	            	github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt
        	            		pkg/session/session.go:2150
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext
        	            		pkg/testkit/testkit.go:383
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).Exec
        	            		pkg/testkit/testkit.go:356
        	            	github.com/pingcap/tidb/pkg/ddl_test.testControlParallelExecSQL.func1
        	            		pkg/ddl/db_change_test.go:1399
        	            	github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1
        	            		pkg/util/wait_group_wrapper.go:157
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
        	Test:       	TestParallelFlashbackTable
```

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #54134, ref #53246

Problem Summary:

### What changed and how does it work?
- fill correct involved schemainfo for 'flashback table' and 'flashback schema'. this issue is not exposed as before this pr, general DDL only have 1 worker, so the second flashback cannot be run, but after https://github.com/pingcap/tidb/pull/54041, general DDL can be run in parallel

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

existing `TestParallelFlashbackTable` should cover the case, so will not add new one. by add some sleep to make sure those 2 sql run in parallel, the case will fail before this pr, but ok after

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ddl_api.go [hunk 1]
```diff
@@ -695,17 +695,24 @@ func (d *ddl) DropSchema(ctx sessionctx.Context, stmt *ast.DropDatabaseStmt) (er
 }
 
 func (d *ddl) RecoverSchema(ctx sessionctx.Context, recoverSchemaInfo *RecoverSchemaInfo) error {
+	involvedSchemas := []model.InvolvingSchemaInfo{{
+		Database: recoverSchemaInfo.Name.L,
+		Table:    model.InvolvingAll,
+	}}
+	if recoverSchemaInfo.OldSchemaName.L != recoverSchemaInfo.DBInfo.Name.L {
```
Comment (lance6716) [inline pkg/ddl/ddl_api.go:702]:
```suggestion
	if recoverSchemaInfo.OldSchemaName.L != recoverSchemaInfo.Name.L {
```

I found it suprise why where are three values `recoverSchemaInfo.Name.L` `recoverSchemaInfo.DBInfo.Name.L` `recoverSchemaInfo.OldSchemaName.L` then I see it's embedded member. 😂 just avoid confusion

**Review by lance6716 — APPROVED** [review]

File: pkg/ddl/ddl_api.go (hunk 1 above)
Comment (D3Hunter) [reply pkg/ddl/ddl_api.go:702]: unify to `recoverSchemaInfo.DBInfo.Name.L` https://github.com/pingcap/tidb/pull/54141/commits/c1ef87ffcb8c434457f7106e8c4103509f2a9607

**Review by tangenta — APPROVED** [review]
