### PR TITLE
*: caller can use a fixed TS for fast reorg

### LINKED ISSUE #46986: For lightning external engine (global sort), engine TS should keep same after subtask failover
## Enhancement

like local engine, the TS is saved in local engine's metadata, we should also let subtask metadata determine the TS.

### LINKED ISSUE #49233: ddl: fast reorg of index may cause duplicate entry error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

image
image
image

### 2. What did you expect to see? (Required)
Look, we did add a unique index with ddl job id as 1131, while at 02.19 ddl owner has changed, and resume the checkpoint at same time, consequently leading duplicate entry error at 02.21

### 3. What did you see instead (Required)
no duplicate error (since user has checked with their data)

### 4. What is your TiDB version? (Required)

master, 7.1.1

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #49233 close #46986

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

```
GOCACHE=/tmp/failpoint-cache go build -o bin/tidb-server-failpoint -toolexec failpoint-toolexec ./cmd/tidb-server

tiup playground nightly --tiflash 0 --without-monitor --db 0

rm /tmp/tidb-{0,1}.log

GO_FAILPOINTS="github.com/pingcap/tidb/pkg/ddl/ingest/resignAfterFlush=return();github.com/pingcap/tidb/pkg/ddl/ingest/checkpointLoopExit=return();github.com/pingcap/tidb/pkg/ddl/ingest/forceSyncFlagForTest=return();github.com/pingcap/tidb/pkg/ddl/ownerResignAfterDispatchLoopCheck=return()" ./bin/tidb-server-failpoint -P 4000 --store=tikv --host=127.0.0.1 --status=10080 --path=127.0.0.1:2379 --log-file=/tmp/tidb-0.log

mysql --comments --host 127.0.0.1 --port 4000 -u root -e "set @@global.tidb_enable_dist_task = 0;set @@global.tidb_ddl_reorg_worker_cnt = 1;create table test.t(c int primary key, c2 int);split table test.t between (0) and (10000) regions 10;insert into test.t values (1,1), (3000, 3000), (6000, 6000);"

./bin/tidb-server-failpoint -P 4001 --store=tikv --host=127.0.0.1 --status=10081 --path=127.0.0.1:2379 --log-file=/tmp/tidb-1.log

mysql --comments --host 127.0.0.1 --port 4001 -u root -e "alter table test.t add unique index idx(c2);"
```

before

image

after

image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/backfilling_dist_scheduler.go [hunk 1]
```diff
@@ -446,6 +457,7 @@ func splitSubtaskMetaForOneKVMetaGroup(
 			DataFiles:      dataFiles,
 			StatFiles:      statFiles,
 			RangeSplitKeys: rangeSplitKeys,
+			TS:             ts,
```
Comment (tangenta) [inline pkg/ddl/backfilling_dist_scheduler.go:460]: For DXF, if we use the same TS, is there any chance that two keys are conflicts but they cannot be detected by `CollectRemoteDupRows`?

File: pkg/lightning/backend/local/engine_mgr.go [hunk 2]
```diff
@@ -426,12 +433,6 @@ func (em *engineManager) resetEngine(ctx context.Context, engineUUID uuid.UUID)
 		if err = em.allocateTSIfNotExists(ctx, localEngine); err != nil {
 			return errors.Trace(err)
 		}
-		failpoint.Inject("mockAllocateTSErr", func() {
-			// mock generate timestamp error when reset engine.
-			localEngine.TS = 0
-			mockGRPCErr, _ := status.FromError(errors.Errorf("mock generate timestamp error"))
-			failpoint.Return(errors.Trace(mockGRPCErr.Err()))
-		})
```
Comment (tangenta) [inline pkg/lightning/backend/local/engine_mgr.go:434]: Why remove this?

File: pkg/ddl/backfilling_dist_scheduler.go (hunk 1 above)
Comment (lance6716) [reply pkg/ddl/backfilling_dist_scheduler.go:460]: It's unlikely because two same keys are adjacent in global sort files, and they will be included in one subtask because start/end key of subtask can not separate them.

File: pkg/lightning/backend/local/engine_mgr.go (hunk 2 above)
Comment (lance6716) [reply pkg/lightning/backend/local/engine_mgr.go:434]: Oh I should let caller pass-in a TS, and skip this `allocateTSIfNotExists`

Comment (lance6716) [reply pkg/lightning/backend/local/engine_mgr.go:434]: https://github.com/pingcap/tidb/pull/52993/commits/8f94822663611acec74a5dad928deddc2f7533fa

**Review by tangenta — APPROVED** [review]

File: pkg/lightning/backend/local/engine_mgr.go [hunk 3]
```diff
@@ -298,7 +302,10 @@ func (em *engineManager) closeEngine(
 		if err != nil {
 			return err
 		}
-		ts := oracle.ComposeTS(physical, logical)
+		ts := cfg.TS
+		if ts == 0 {
+			ts = oracle.ComposeTS(physical, logical)
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/engine_mgr.go:307]: we can skip GetTS if ts != 0

File: pkg/lightning/backend/backend.go [hunk 4]
```diff
@@ -89,6 +89,9 @@ type EngineConfig struct {
 	// KeepSortDir indicates whether to keep the temporary sort directory
 	// when opening the engine, instead of removing it.
 	KeepSortDir bool
+	// TS is the preset timestamp of data in the engine. When it's 0, the used TS
+	// will be set lazily.
```
Comment (D3Hunter) [inline pkg/lightning/backend/backend.go:93]:
```suggestion
	// will be set lazily.
	// only used in global sort now
```

File: pkg/ddl/ingest/checkpoint.go [hunk 5]
```diff
@@ -298,6 +314,7 @@ type ReorgCheckpoint struct {
 	PhysicalID int64  `json:"physical_id"`
 	StartKey   kv.Key `json:"start_key"`
 	EndKey     kv.Key `json:"end_key"`
+	TS         uint64 `json:"ts"`
```
Comment (D3Hunter) [inline pkg/ddl/ingest/checkpoint.go:317]:
```suggestion
	// TS of next engine ingest.
	TS         uint64 `json:"ts"`
```

File: pkg/ddl/ingest/checkpoint.go [hunk 6]
```diff
@@ -438,3 +480,35 @@ func (s *CheckpointManager) updateCheckpointLoop() {
...
+	// wait updateCheckpointLoop to finish checkpoint update.
+	select {
+	case <-finishCh:
+	case <-s.ctx.Done():
+		return s.ctx.Err()
+	}
+	return nil
+}
+
+func (s *CheckpointManager) refreshTS() (uint64, error) {
```
Comment (D3Hunter) [inline pkg/ddl/ingest/checkpoint.go:504]:
```suggestion
func (s *CheckpointManager) refreshTSAndUpdateCP() (uint64, error) {
```
the refreshTS part is same as in `resumeOrInitCheckpoint`

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/lightning/backend/backend.go (hunk 4 above)
Comment (lance6716) [reply pkg/lightning/backend/backend.go:93]: it's also used in `generateLocalEngineConfig` in local fast reorg of DDL

**Review by D3Hunter — APPROVED** [review]
