### PR TITLE
charset(gb18030): input can contain ReplacementChar

### LINKED ISSUE #63933: can't insert unicode replacement character encoded by gb18030
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tiup playground nightly --tiflash 0 --without-monitor 
```

```golang
package main

import (
	"context"
	"database/sql"
	"encoding/hex"

	"github.com/go-sql-driver/mysql"
	_ "github.com/go-sql-driver/mysql"
)

func checkErr(e error) {
	if e != nil {
		panic(e)
	}
}

func main() {
	ctx := context.Background()
	cfg := mysql.NewConfig()
	cfg.User = "root"
	cfg.Addr = "127.0.0.1:4000"
	cfg.DBName = "test"
	c, err := mysql.NewConnector(cfg)
	checkErr(err)
	db := sql.OpenDB(c)

	db.Exec("DROP TABLE IF EXISTS t")
	_, err = db.Exec("CREATE TABLE t (c VARCHAR(300)) CHARACTER SET utf8mb4")
	checkErr(err)

	conn, err := db.Conn(ctx)
	checkErr(err)
	_, err = conn.ExecContext(ctx, "SET NAMES gb18030")
	checkErr(err)
	stmt, err := conn.PrepareContext(ctx, "INSERT INTO t VALUES (?)")
	checkErr(err)

	data, err := hex.DecodeString("B0B2")
	checkErr(err)
	_, err = stmt.Exec(data)
	checkErr(err)

	data, err = hex.DecodeString("B0B28431A437308431A43732")
	checkErr(err)
	_, err = stmt.Exec(data)
	checkErr(err)
}
```

### 2. What did you expect to see? (Required)

(change port to 3306 to test MySQL behaviour)

```
mysql> select * from t;
+-------------+
| c           |
+-------------+
| 安          |
| 安�0�2      |
+-------------+
2 rows in set (0.001 sec)
```

### 3. What did you see instead (Required)

```
panic: Error 1366 (HY000): Incorrect string value '\xB0' for column 'c'
```

```
mysql> select * from t;
+------+
| c    |
+------+
| 安   |
+------+
1 row in set (0.004 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v9.0.0-beta.2.pre-339-g78eadf2080
Edition: Community
Git Commit Hash: 78eadf20801cee122e18eb449498b9b790f04e96
Git Branch: HEAD
UTC Build Time: 2025-08-18 06:50:15
GoVersion: go1.23.12
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Kernel Type: Classic
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #63933

Problem Summary:

### What changed and how does it work?

before this PR, if the decoded value starts with unicode replacement character `\uFFFD` it will be treated as error. However, it's a legal input that input is another charset and really encodes `\uFFFD`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

checked with the demo code in linked issue 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/parser/charset/encoding_gb18030.go [hunk 1]
```diff
@@ -123,10 +123,26 @@ func NewCustomGB18030Decoder() *encoding.Decoder {
 	return customGB18030{}.NewDecoder()
 }
 
+type runeErrorMaybeInputTransformer interface {
+	runeErrorIsLastInput() bool
+}
+
+type runeErrorMaybeInputWrapper struct {
+	*encoding.Decoder
+}
```
Comment (kennytm) [inline pkg/parser/charset/encoding_gb18030.go]: what does this type do? seems used nowhere

Comment (lance6716) [reply pkg/parser/charset/encoding_gb18030.go]: https://github.com/pingcap/tidb/pull/63936/commits/e1bf2998d21ba7218b0f08d7e4a6255c00499eef

**Comment by kennytm** [comment]
can you add a test case for `0x84, 0x31, 0xa4, 0x37, 0x81` i.e. one U+FFFD followed by an actual error

File: pkg/parser/charset/encoding_test.go [hunk 2]
```diff
@@ -196,13 +196,15 @@ func TestEncodingGB18030(t *testing.T) {
...
+		{"\xb0\xb2", "安", true},
 		// rune error is encoded to gb18030, we must decode as-is and report no error
 		{
-			string([]byte{0xb0, 0xb2, 0x84, 0x31, 0xa4, 0x37, 0x30, 0x84, 0x31, 0xa4, 0x37, 0x32}),
+			"\xb0\xb2\x84\x31\xa4\x37\x30\x84\x31\xa4\x37\x32",
 			"安\ufffd0\ufffd2",
 			true,
 		},
+		// check encoded rune error and invalid data together
+		{"\x80\x84\x31\xa4\x37\x80\x84\x31\xa4\x37", "?\ufffd?\ufffd", false},
```
Comment (kennytm) [inline pkg/parser/charset/encoding_test.go:207]: no i specifically said "one FFFD followed by an error", not "an error followed by FFFD etc"

Comment (lance6716) [reply pkg/parser/charset/encoding_test.go:207]: https://github.com/pingcap/tidb/pull/63936/commits/4c8c76ee540b400cbe223ef5a1534681202caab8

**Review by tangenta — APPROVED** [review]
