### PR TITLE
planner: add missing `CanExprsPushDown` checks when generating IndexMerge path for `or`

### LINKED ISSUE #41273: Inconsistent result of the same queries, related to index merge, null
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `87f3b2f7` (
  `12db5ecc` set('nwbk','r5','1ad3u','van','ir1z','y','9m','f1','z','e6yd','wfev') NOT NULL DEFAULT 'ir1z,f1,e6yd',
  `0a968b42` enum('soo2','4s4j','qi9om','8ue','i71o','qon','3','3feh','6o1i','5yebx','d') NOT NULL DEFAULT '8ue',
  `af528200` varchar(66) DEFAULT '13mdezixgcn',
  PRIMARY KEY (`12db5ecc`,`0a968b42`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `e521f911` (`0a968b42`),
  KEY `17d3c2c4` (`12db5ecc`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin COMMENT='9302fd19';

INSERT INTO `87f3b2f7` VALUES('ir1z,f1,e6yd','i71o','13mdezixgcn'),('ir1z,f1,e6yd','d','13mdezixgcn'),('nwbk','8ue','13mdezixgcn');

select     trim( `87f3b2f7`.`12db5ecc` ) as r0 , var_samp( `87f3b2f7`.`0a968b42` ) as r1 from `87f3b2f7` where `87f3b2f7`.`12db5ecc` between 'e6yd' and 'z' or `87f3b2f7`.`0a968b42` <> '8ue' group by `87f3b2f7`.`12db5ecc`  order by r0,r1;

select  /*+ use_index_merge( `87f3b2f7` ) */ /*+ agg_to_cop() stream_agg() */  trim( `87f3b2f7`.`12db5ecc` ) as r0 , var_samp( `87f3b2f7`.`0a968b42` ) as r1 from `87f3b2f7` where `87f3b2f7`.`12db5ecc` between 'e6yd' and 'z' or `87f3b2f7`.`0a968b42` <> '8ue' group by `87f3b2f7`.`12db5ecc`  order by r0,r1;

```

### 2. What did you expect to see? (Required)
Two queries got the same results.
### 3. What did you see instead (Required)
``` SQL
mysql> select  /*+ use_index_merge( `87f3b2f7` ) */ /*+ agg_to_cop() stream_agg() */  trim( `87f3b2f7`.`12db5ecc` ) as r0 , var_samp( `87f3b2f7`.`0a968b42` ) as r1 from `87f3b2f7` where `87f3b2f7`.`12db5ecc` between 'e6yd' and 'z' or `87f3b2f7`.`0a968b42` <> '8ue' group by `87f3b2f7`.`12db5ecc`  order by r0,r1;
+--------------+------+
| r0           | r1   |
+--------------+------+
| ir1z,f1,e6yd |   18 |
+--------------+------+
1 row in set (0.01 sec)

mysql> select     trim( `87f3b2f7`.`12db5ecc` ) as r0 , var_samp( `87f3b2f7`.`0a968b42` ) as r1 from `87f3b2f7` where `87f3b2f7`.`12db5ecc` between 'e6yd' and 'z' or `87f3b2f7`.`0a968b42` <> '8ue' group by `87f3b2f7`.`12db5ecc`  order by r0,r1;
+--------------+------+
| r0           | r1   |
+--------------+------+
| ir1z,f1,e6yd |   18 |
| nwbk         | NULL |
+--------------+------+
2 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
master

### LINKED ISSUE #41293: index merge got wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `c2b87b4e` (
  `7d83ef7c` double DEFAULT '1.663803102055177',
  `7cabceba` set('os','me','n6t','d','p7','ai','2hts','0','j33yx','2k','y') DEFAULT 'os,me,n6t,0,y',
  `93b472a8` tinyint(4) DEFAULT '-115',
  `598ce136` set('eujoh','0ny','i5','qhzj','6nut','f','c82rq','i13l','t2gv','i','0') DEFAULT 'eujoh,0ny,qhzj,f,c82rq,t2gv,i,0',
  `38092777` float DEFAULT '1.7303925',
  KEY `207991a6` (`7d83ef7c`,`93b472a8`),
  KEY `eda4fc8a` (`7d83ef7c`),
  KEY `4aca75dc` (`7cabceba`),
  KEY `473811b5` (`93b472a8`),
  KEY `e11e954c` (`598ce136`),
  KEY `7016a347` (`93b472a8`,`7cabceba`),
  KEY `65cdc839` (`598ce136`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin /*T! SHARD_ROW_ID_BITS=6 */ COMMENT='4076571c';

INSERT INTO `c2b87b4e` VALUES (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'c82rq',7896.913), (1609.217822723485,'d',-109,'0',3225.4304), (1609.217822723485,'d',-109,'0ny',2654.9243), (1609.217822723485,'d',-109,'c82rq',NULL), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',5638.71), (1609.217822723485,'d',-109,'6nut',1305.846), (1609.217822723485,'d',-109,'6nut',143.02635), (1609.217822723485,'d',-109,'6nut',3176.9207), (1609.217822723485,'d',-109,'6nut',1.7303925), (1609.217822723485,'d',-109,'c82rq',9444.325), (5364.0973229331175,'j33yx',-107,NULL,4724.1025), (1609.217822723485,'d',-109,'f',3683.1667), (1609.217822723485,'d',-109,'0ny',4718.6187), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',5708.5044), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (2696.974142687824,'d',-40,'0',1.7303925), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'qhzj',598.6983), (1609.217822723485,'d',-109,'f',9319.082), (1609.217822723485,'d',-109,'eujoh',3091.5088), (1609.217822723485,'d',-109,'i5',7759.6816), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',990.95374), (1609.217822723485,'d',-109,'6nut',1482.077), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'qhzj',6924.8604), (1609.217822723485,'d',-109,'6nut',614.1022), (1609.217822723485,'d',-109,'6nut',9491.7), (1609.217822723485,'d',-109,'t2gv',2365.1626), (1609.217822723485,'d',-109,'6nut',1021.16693), (6801.635763729652,'me',-115,'t2gv',1.7303925), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'c82rq',8647.832), (1609.217822723485,'d',-109,'eujoh',3219.7595), (1609.217822723485,'d',-109,'0',9907.7705), (1609.217822723485,'d',-109,'6nut',7910.752), (1609.217822723485,'d',-109,'6nut',2225.922), (1609.217822723485,'d',-109,'6nut',276.25302), (1609.217822723485,'d',-109,'6nut',826.02734), (435.7165360703686,'0',-100,NULL,1428.476), (1609.217822723485,'d',-109,'i5',7998.759), (1609.217822723485,'d',-109,'eujoh',7487.266), (7050.011747806327,'2hts',123,NULL,3761.7837), (1609.217822723485,'d',-109,'i5',8635.771);

select  /*+ use_index_merge( `c2b87b4e` ) */   `c2b87b4e`.`7d83ef7c` as r0 , `c2b87b4e`.`7cabceba` as r1 , `c2b87b4e`.`7d83ef7c`
 as r2 from `c2b87b4e` where `c2b87b4e`.`598ce136` = '0' or not( `c2b87b4e`.`7cabceba` between 'me' and 'y' );

select  `c2b87b4e`.`7d83ef7c` as r0 , `c2b87b4e`.`7cabceba` as r1 , `c2b87b4e`.`7d83ef7c` as r2 from `c2b87b4e` where `c2b87b4e`.`598ce136` = '0' or not( `c2b87b4e`.`7cabceba` between 'me' and 'y' );
```

### 2. What did you expect to see? (Required)

Two queries got the same results.

### 3. What did you see instead (Required)
``` SQL

mysql>  select  /*+ use_index_merge( `c2b87b4e` ) */   `c2b87b4e`.`7d83ef7c` as r0 , `c2b87b4e`.`7cabceba` as r1 , `c2b87b4e`.`7d83ef7c` as r2 from `c2b87b4e` where `c2b87b4e`.`598ce136` = '0' or not( `c2b87b4e`.`7cabceba` between 'me' and 'y' );
+-------------------+------+-------------------+
| r0                | r1   | r2                |
+-------------------+------+-------------------+
| 1609.217822723485 | d    | 1609.217822723485 |
| 2696.974142687824 | d    | 2696.974142687824 |
| 1609.217822723485 | d    | 1609.217822723485 |
+-------------------+------+-------------------+
3 rows in set (0.01 sec)

mysql>  select   `c2b87b4e`.`7d83ef7c` as r0 , `c2b87b4e`.`7cabceba` as r1 , `c2b87b4e`.`7d83ef7c` as r2 from `c2b87b4e`;
+--------------------+-------+--------------------+
| r0                 | r1    | r2                 |
+--------------------+-------+--------------------+
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
| 5364.0973229331175 | j33yx | 5364.0973229331175 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  2696.974142687824 | d     |  2696.974142687824 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  6801.635763729652 | me    |  6801.635763729652 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  435.7165360703686 | 0     |  435.7165360703686 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  1609.217822723485 | d     |  1609.217822723485 |
|  7050.011747806327 | 2hts  |  7050.011747806327 |
|  1609.217822723485 | d     |  1609.217822723485 |
+--------------------+-------+--------------------+
67 rows in set, 1 warning (0.00 sec)

```

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #41273 close #41293

Problem Summary:

This bug is introduced by #30341.

This case is related to the `SET` type mainly. We don't support pushing down the `SET` type now. `util/ranger` also can't correctly handle expressions on `SET` column. So it requires these expressions be blocked in advance. After #30341, such expressions can reach `util/ranger` without the `CanExprsPushDown` check.

### What is changed and how it works?

Add a `CanExprsPushDown` check before using an expression to build an IndexMerge partial path.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/indexmerge_path.go [hunk 1]
```diff
@@ -109,11 +109,28 @@ func (ds *DataSource) generateIndexMergeOrPaths(filters []expression.Expression)
...
 		for _, item := range dnfItems {
 			cnfItems := expression.SplitCNFItems(item)
-			itemPaths := ds.accessPathsForConds(cnfItems, usedIndexCount)
+
+			pushedDownCNFItems := make([]expression.Expression, 0, len(cnfItems))
+			for _, cnfItem := range cnfItems {
+				if expression.CanExprsPushDown(ds.ctx.GetSessionVars().StmtCtx,
+					[]expression.Expression{cnfItem},
+					ds.ctx.GetClient(),
+					kv.TiKV,
```
Comment (fixdb) [inline planner/core/indexmerge_path.go:125]: Nit: remove `,`

**Review by fixdb — APPROVED** [review]
+1

File: planner/core/indexmerge_path.go (hunk 1 above)
Comment (time-and-fate) [reply planner/core/indexmerge_path.go:125]: This `,` is required by golang.

**Review by qw4990 — APPROVED** [review]

File: planner/core/integration_test.go [hunk 2]
```diff
@@ -8431,3 +8431,24 @@ func TestIssue40285(t *testing.T) {
...
+    	c varchar(66) DEFAULT '13mdezixgcn',
+    	PRIMARY KEY (a,b) /*T![clustered_index] CLUSTERED */,
+    	UNIQUE KEY ib(b),
+    	KEY ia(a)
+    )ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;`)
+	tk.MustExec("INSERT INTO t VALUES('ir1z,f1,e6yd','i71o','13mdezixgcn'),('ir1z,f1,e6yd','d','13mdezixgcn'),('nwbk','8ue','13mdezixgcn');")
+	expectedRes := []string{"ir1z,f1,e6yd d 13mdezixgcn", "ir1z,f1,e6yd i71o 13mdezixgcn", "nwbk 8ue 13mdezixgcn"}
+	tk.MustQuery("select * from t where a between 'e6yd' and 'z' or b <> '8ue';").Sort().Check(testkit.Rows(expectedRes...))
+	tk.MustQuery("select /*+ use_index_merge(t) */ * from t where a between 'e6yd' and 'z' or b <> '8ue';").Sort().Check(testkit.Rows(expectedRes...))
+	// For now tidb doesn't support push set type to TiKV, and column a is a set type, so we shouldn't generate a IndexMerge path.
```
Comment (guo-shaoge) [inline planner/core/integration_test.go:8452]: Do we need add some log or warning to indicate why cannot use index merge ?

Comment (guo-shaoge) [reply planner/core/integration_test.go:8452]: Rest lgtm

Comment (time-and-fate) [reply planner/core/integration_test.go:8452]: It would print a general warning "IndexMerge is inapplicable" like other cases when we failed to generate an IndexMerge path.

Comment (time-and-fate) [reply planner/core/integration_test.go:8452]: It would be better if it could print the particular reason. But we also don't print the reason in other cases, so I think it's unnecessary to add it in this PR.

Comment (guo-shaoge) [reply planner/core/integration_test.go:8452]: ok
