### PR TITLE
planner, executor: fix wrong result in index merge join.

### LINKED ISSUE #13177: Wrong result when substr in index merge join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
tidb(localhost:4000) > create table t1(a varchar(20), b int, c int);
Query OK, 0 rows affected (0.01 sec)

tidb(localhost:4000) > create table t2(a varchar(20), b int, c int, primary key(a, b));
Query OK, 0 rows affected (0.01 sec)

tidb(localhost:4000) > insert into t1 values("abcd", 1, 1), ("bacd", 2, 2), ("cbad", 3, 3);
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

tidb(localhost:4000) > insert into t2 values("bcd", 1, 1), ("acd", 2, 2), ("bad", 3, 3);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

tidb(localhost:4000) > desc select /*+ tidb_inlj(t1, t2) */ * from t1 join t2 on substr(t1.a, 2, 4) = t2.a and t1.b = t2.b where t1.c between 1 and 5;                                                                                                           [13/1996]
+------------------------------+-------+-----------+------------------------------------------------------------------------------------------------------------+
| id                           | count | task      | operator info                                                                                              |
+------------------------------+-------+-----------+------------------------------------------------------------------------------------------------------------+
| Projection_7                 | 3.00  | root      | Column#1, Column#2, Column#3, Column#5, Column#6, Column#7                                                 |
| └─IndexJoin_11               | 3.00  | root      | inner join, inner:IndexLookUp_10, outer key:Column#2, Column#15, inner key:Column#6, Column#5              |
|   ├─Projection_20            | 3.00  | root      | Column#1, Column#2, Column#3, substr(Column#1, 2, 4)                                                       |
|   │ └─TableReader_23         | 3.00  | root      | data:Selection_22                                                                                          |
|   │   └─Selection_22         | 3.00  | cop[tikv] | ge(Column#3, 1), le(Column#3, 5), not(isnull(Column#2))                                                    |
|   │     └─TableScan_21       | 3.00  | cop[tikv] | table:t1, range:[-inf,+inf], keep order:false                                                              |
|   └─IndexLookUp_10           | 1.00  | root      |                                                                                                            |
|     ├─IndexScan_8            | 1.00  | cop[tikv] | table:t2, index:a, b, range: decided by [eq(Column#5, Column#15) eq(Column#6, Column#2)], keep order:false |
|     └─TableScan_9            | 1.00  | cop[tikv] | table:t2, keep order:false                                                                                 |
+------------------------------+-------+-----------+------------------------------------------------------------------------------------------------------------+
9 rows in set (0.01 sec)

tidb(localhost:4000) > desc select /*+ tidb_inlj(t1, t2) */ t1.* from t1 join t2 on substr(t1.a, 2, 4) = t2.a and t1.b = t2.b where t1.c between 1 and 5;
+------------------------------+-------+-----------+-----------------------------------------------------------------------------------------------------------+
| id                           | count | task      | operator info                                                                                             |
+------------------------------+-------+-----------+-----------------------------------------------------------------------------------------------------------+
| Projection_7                 | 3.00  | root      | Column#1, Column#2, Column#3                                                                              |
| └─IndexMergeJoin_14          | 3.00  | root      | inner join, inner:IndexReader_12, outer key:Column#2, Column#12, inner key:Column#6, Column#5             |
|   ├─Projection_17            | 3.00  | root      | Column#1, Column#2, Column#3, substr(Column#1, 2, 4)                                                      |
|   │ └─TableReader_20         | 3.00  | root      | data:Selection_19                                                                                         |
|   │   └─Selection_19         | 3.00  | cop[tikv] | ge(Column#3, 1), le(Column#3, 5), not(isnull(Column#2))                                                   |
|   │     └─TableScan_18       | 3.00  | cop[tikv] | table:t1, range:[-inf,+inf], keep order:false                                                             |
|   └─IndexReader_12           | 1.00  | root      | index:IndexScan_11                                                                                        |
|     └─IndexScan_11           | 1.00  | cop[tikv] | table:t2, index:a, b, range: decided by [eq(Column#5, Column#12) eq(Column#6, Column#2)], keep order:true |
+------------------------------+-------+-----------+-----------------------------------------------------------------------------------------------------------+
8 rows in set (0.01 sec)

tidb(localhost:4000) > select /*+ tidb_inlj(t1, t2) */ * from t1 join t2 on substr(t1.a, 2, 4) = t2.a and t1.b = t2.b where t1.c between 1 and 5;
+------+------+------+-----+---+------+
| a    | b    | c    | a   | b | c    |
+------+------+------+-----+---+------+
| abcd |    1 |    1 | bcd | 1 |    1 |
| bacd |    2 |    2 | acd | 2 |    2 |
| cbad |    3 |    3 | bad | 3 |    3 |
+------+------+------+-----+---+------+
3 rows in set (0.00 sec)

tidb(localhost:4000) > select /*+ tidb_inlj(t1, t2) */ t1.* from t1 join t2 on substr(t1.a, 2, 4) = t2.a and t1.b = t2.b where t1.c between 1 and 5;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| bacd |    2 |    2 |
| cbad |    3 |    3 |
+------+------+------+
2 rows in set (0.01 sec)
```

2. What did you expect to see?
```sql
tidb(localhost:4000) > select /*+ tidb_inlj(t1, t2) */ t1.* from t1 join t2 on substr(t1.a, 2, 4) = t2.a and t1.b = t2.b where t1.c between 1 and 5;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| abcd |    1 |    1 |
| bacd |    2 |    2 |
| cbad |    3 |    3 |
+------+------+------+
2 rows in set (0.01 sec)
```


3. What did you see instead?
```sql
tidb(localhost:4000) > select /*+ tidb_inlj(t1, t2) */ t1.* from t1 join t2 on substr(t1.a, 2, 4) = t2.a and t1.b = t2.b where t1.c between 1 and 5;
+------+------+------+
| a    | b    | c    |
+------+------+------+
| bacd |    2 |    2 |
| cbad |    3 |    3 |
+------+------+------+
2 rows in set (0.01 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```sql
tidb(localhost:4000) > select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-alpha-729-ga28fc711d
Git Commit Hash: a28fc711d738676abf873955054a01222095602b
Git Branch: HEAD
UTC Build Time: 2019-11-06 03:03:50
GoVersion: go version go1.13 darwin/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve? 
fix #13177 

### What is changed and how it works?
The outer order should keep same with the inner index. So all the order checks should consider the difference between join key offset and index offset.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity

### CODE REVIEW

File: planner/core/physical_plans.go [hunk 1]
```diff
@@ -295,6 +295,8 @@ type PhysicalIndexJoin struct {
 type PhysicalIndexMergeJoin struct {
 	PhysicalIndexJoin
 
+	// IdxOff2KeyOff maps the offsets in index to the offsets in join key.
+	IdxOff2KeyOff map[int]int
```
Comment (lamxTyler) [inline planner/core/physical_plans.go]: Can it be an array like `KeyOff2IdxOff`?

File: executor/index_lookup_merge_join.go [hunk 2]
```diff
@@ -423,8 +424,10 @@ func (imw *innerMergeWorker) handleTask(ctx context.Context, task *lookUpMergeJo
 		sort.Slice(task.outerOrderIdx, func(i, j int) bool {
 			idxI, idxJ := task.outerOrderIdx[i], task.outerOrderIdx[j]
 			rowI, rowJ := task.outerResult.GetRow(idxI), task.outerResult.GetRow(idxJ)
-			for id, joinKey := range imw.outerMergeCtx.joinKeys {
-				cmp, _, err := imw.outerMergeCtx.compareFuncs[id](imw.ctx, joinKey, joinKey, rowI, rowJ)
+			for idxOff := range imw.joinKeys {
```
Comment (lamxTyler) [inline executor/index_lookup_merge_join.go]: It makes me confusion here: Why we loop over the join keys but get index offset? What about just loop over the `idxOff2KeyOff` after making it an array?

File: planner/core/testdata/plan_suite_out.json [hunk 3]
```diff
@@ -463,7 +463,7 @@
       },
       {
         "SQL": "select /*+ TIDB_INLJ(t1, t2) */ * from t t1 join t t2 on t1.d=t2.d and t2.c = 1",
-        "Best": "IndexMergeJoin{TableReader(Table(t))->IndexLookUp(Index(t.c_d_e)[[NULL,+inf]], Table(t))}(Column#4,Column#16)"
+        "Best": "IndexJoin{TableReader(Table(t))->IndexLookUp(Index(t.c_d_e)[[NULL,+inf]], Table(t))}(Column#4,Column#16)"
```
[the remark this answers is not in the document]
Comment (lzmhhh123) [reply planner/core/testdata/plan_suite_out.json]: Because the conditions for generating the index merge join plan are changed.

File: planner/core/exhaust_physical_plans.go [hunk 4]
```diff
@@ -399,12 +399,27 @@ func (p *LogicalJoin) constructIndexMergeJoin(
 		if hasPrefixCol {
 			continue
 		}
+		// If join keys is not prefix of inner index. The order of merge join can't be granted.
+		// So index merge join can't be constructed in this case
+		idxOff2KeyOff := make([]int, len(join.OuterJoinKeys))
```
Comment (winoros) [inline planner/core/exhaust_physical_plans.go]: I think you can directly pass `helper.idxOff2KeyOff` to `constructIndexMergeJoin`?

Comment (lzmhhh123) [reply planner/core/exhaust_physical_plans.go]: We can't do this or in other words. It's hard to do this. The `constructIndexMergeJoin` is also used for "inner is `TableScan`" without `helper`. And for other sides, the `idxOff2KeyOff` is not consistent with `helper.idxOff2KeyOff`. It doesn't have the value `-1`.

File: planner/core/exhaust_physical_plans.go [hunk 5]
```diff
@@ -399,12 +399,27 @@ func (p *LogicalJoin) constructIndexMergeJoin(
...
+		isKeyPrefixIndex := true
```
[the remark this answers is not in the document]
Comment (lzmhhh123) [reply planner/core/exhaust_physical_plans.go]: Oh, yes. It can keep the order. I'll try to fix it.

File: planner/core/exhaust_physical_plans.go [hunk 6]
```diff
@@ -399,12 +400,25 @@ func (p *LogicalJoin) constructIndexMergeJoin(
 		if hasPrefixCol {
 			continue
 		}
+
+		keyOff2KeyOffOrderByIdx := make([]int, len(join.OuterJoinKeys))
```
Comment (winoros) [inline planner/core/exhaust_physical_plans.go]: Add some comment here

Comment (lzmhhh123) [reply planner/core/exhaust_physical_plans.go]: Done

File: executor/join_test.go [hunk 7]
```diff
@@ -1599,9 +1599,9 @@ func (s *testSuiteJoin1) TestIssue13177(c *C) {
 	tk.MustExec("insert into t1 values(\"abcd\", 1, 1), (\"bacd\", 2, 2), (\"cbad\", 3, 3)")
 	tk.MustExec("insert into t2 values(\"bcd\", 1, 1), (\"acd\", 2, 2), (\"bad\", 3, 3)")
 	tk.MustQuery("select /*+ inl_merge_join(t1, t2) */ * from t1 join t2 on substr(t1.a, 2, 4) = t2.a and t1.b = t2.b where t1.c between 1 and 5").Check(testkit.Rows(
-		"abcd 1 1 bcd 1 1",
 		"bacd 2 2 acd 2 2",
 		"cbad 3 3 bad 3 3",
+		"abcd 1 1 bcd 1 1",
```
Comment (winoros) [inline executor/join_test.go]: why this line changed?

Comment (lzmhhh123) [reply executor/join_test.go]: It keeps order for column `acd bad bcd` instead of `abcd bacd cbad`. The reason why previous CI could be accepted is that I use `tidb_inl` to choose an index join before and after **Huaiyu**'s PR, the `tidb_inl` can't choose the index merge join.

Comment (winoros) [reply executor/join_test.go]: Will this result be stable enough?

Comment (lzmhhh123) [reply executor/join_test.go]: Always stable, index merge join keeps outer order.
