### PR TITLE
planner: fix the issue that binding cannot work when sql_select_limit is enabled 

### LINKED ISSUE #27949: planner: binding cannot work when `sql_select_limit` is enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (a int, b int, key(b));
explain select * from t where b=1;
create global binding for select * from t where b=1 using select * from t ignore index(b) where b=1;

mysql> explain select * from t where b=1;
+-------------------------+----------+-----------+---------------+--------------------------------+
| id                      | estRows  | task      | access object | operator info                  |
+-------------------------+----------+-----------+---------------+--------------------------------+
| TableReader_7           | 10.00    | root      |               | data:Selection_6               |
| └─Selection_6           | 10.00    | cop[tikv] |               | eq(test.t.b, 1)                |
|   └─TableFullScan_5     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-------------------------+----------+-----------+---------------+--------------------------------+
3 rows in set (0.00 sec)

mysql> 
mysql> set @@sql_select_limit=100;
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> explain select * from t where b=1;
+--------------------------------+---------+-----------+---------------------+---------------------------------------------+
| id                             | estRows | task      | access object       | operator info                               |
+--------------------------------+---------+-----------+---------------------+---------------------------------------------+
| IndexLookUp_17                 | 10.00   | root      |                     | limit embedded(offset:0, count:100)         |
| ├─Limit_16(Build)              | 10.00   | cop[tikv] |                     | offset:0, count:100                         |
| │ └─IndexRangeScan_14          | 10.00   | cop[tikv] | table:t, index:b(b) | range:[1,1], keep order:false, stats:pseudo |
| └─TableRowIDScan_15(Probe)     | 10.00   | cop[tikv] | table:t             | keep order:false, stats:pseudo              |
+--------------------------------+---------+-----------+---------------------+---------------------------------------------+
4 rows in set (0.00 sec)
```

The binding is not working after setting `sql_select_limit`.

### 2. What did you expect to see? (Required)
The binding can work.

### 3. What did you see instead (Required)
The binding is not working.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #27949 

Problem Summary: planner: fix the issue that binding cannot work when `sql_select_limit` is enabled

### What is changed and how it works?

TiDB uses the AST of a query to find its corresponding binding records, but when `sql_select_limit` is enabled, an extra Limit node is inserted upon the AST, and then the changed AST cannot match the original binding record.

This PR just adjusts orders of these two operations, which moves the operation of adding the extra Limit to the front of finding binding records.

### Check List 

Tests 

- [x] Unit test

### Release note 

```release-note
planner: fix the issue that binding cannot work when `sql_select_limit` is enabled
```

### CODE REVIEW

File: planner/optimize.go [hunk 1]
```diff
@@ -99,11 +99,34 @@ func GetExecuteForUpdateReadIS(node ast.Node, sctx sessionctx.Context) infoschem
...
+	}
+	return bindRecord, scope, true
+}
+
 // Optimize does optimization and creates a Plan.
 // The node must be prepared first.
 func Optimize(ctx context.Context, sctx sessionctx.Context, node ast.Node, is infoschema.InfoSchema) (plannercore.Plan, types.NameSlice, error) {
 	sessVars := sctx.GetSessionVars()
 
+	bindRecord, scope, useBinding := matchSQLBinding(node, sctx)
```
Comment (Reminiscent) [inline planner/optimize.go:124]: Maybe we can extract the `stmtNode` from the `matchSQLBinding`. And pass the `stmtNode` to `matchSQLBinding` for less change. But now is OK.

Comment (Reminiscent) [inline planner/optimize.go:124]: If we perform binding lookup operations in advance, binding can also control `PointGet/ BatchPointGet` plans at this time, and corresponding tests need to be added.

Comment (Reminiscent) [inline planner/optimize.go:124]: Maybe we should put this part behind the [codes](https://github.com/pingcap/tidb/blob/fec2938c1379270bf9939822c1abfe3d7244c174/planner/optimize.go#L107-L128) for less change.

File: planner/core/integration_test.go [hunk 2]
```diff
@@ -4707,6 +4707,26 @@ func (s *testIntegrationSuite) TestIssue27797(c *C) {
 	result.Check(testkit.Rows("<nil>"))
 }
 
+func (s *testIntegrationSuite) TestIssue27949(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t27949")
+	tk.MustExec("create table t27949 (a int, b int, key(b))")
+	tk.MustQuery("explain select * from t27949 where b=1").Check(testkit.Rows("IndexLookUp_10 10.00 root  ",
```
Comment (Reminiscent) [inline planner/core/integration_test.go:4715]: Maybe we can use `explain format = 'brief'` to test. And can use `select @@last_plan_from_binding` to check whether the plan use the binding.

**Review by Reminiscent — APPROVED** [review]

**Review by winoros — APPROVED** [review]
