### PR TITLE
ddl: send result chunks to writers after scan task complete

### LINKED ISSUE #62008: Partial import during adding index may block GC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Add index for a large table, partial import takes a long time:

```
[INFO] [backend.go:229] ["do a partial import data into the storage"] [category=ddl-ingest]
```

### 2. What did you expect to see? (Required)

No warning.

### 3. What did you see instead (Required)

There are lots of warnings in log:

```
[txn.go:99] ["An internal transaction running by internal session lasts long time"] [time=12h15m11.5s]
```

### 4. What is your TiDB version? (Required)

a268223

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #62008

Problem Summary: See https://github.com/pingcap/tidb/issues/62008#issuecomment-3004819982

### What changed and how does it work?

Send index result chunks to the writers after scanning the whole read task. It may increase the memory usage when reading index, but it is still constrained by the reader concurrency.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/lightning/backend/local/local.go [hunk 1]
```diff
@@ -1218,6 +1218,7 @@ func (local *Backend) ImportEngine(
 		zap.Int64("size", lfTotalSize))
 
 	failpoint.Inject("ReadyForImportEngine", func() {})
+	failpoint.InjectCall("duringBackendImportEngine")
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/local.go]: can we reuse previous failpoint?

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/lightning/backend/local/local.go [hunk 2]
```diff
@@ -1217,8 +1217,7 @@ func (local *Backend) ImportEngine(
 		zap.Int64("count", lfLength),
 		zap.Int64("size", lfTotalSize))
 
-	failpoint.Inject("ReadyForImportEngine", func() {})
-	failpoint.InjectCall("duringBackendImportEngine")
+	failpoint.InjectCall("ReadyForImportEngine")
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/local.go:1220]: ReadyForImportEngine is used in lightning integration test, seems we cannot merge them😓

Comment (D3Hunter) [reply pkg/lightning/backend/local/local.go:1220]: but the CI still passes 😓

Comment (tangenta) [reply pkg/lightning/backend/local/local.go:1220]: It is OK to use failpoint term (like "sleep" or "panic") for `InjectCall`.

Comment (D3Hunter) [reply pkg/lightning/backend/local/local.go:1220]: ok, it's run in the `eval` part
