### PR TITLE
executor, conn: wait for the goroutine in preprocessLoadDataLocal to finish before step to next query

### LINKED ISSUE #62673: `LOAD DATA LOCAL INFILE` will cause race condition in buffered connection, and cause panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Start a `LOAD DATA LOCAL INFILE`, and use a lot of memory.
2. The query is killed. Then there are two goroutines reading the same connection: one for the session, one for reading the infile (which is not killed after the query is killed).
3. The internal connection buffer cannot manage the memory well, so it may panic. The error will be like: `panic: runtime error: slice bounds out of range`

### 2. What did you expect to see? (Required)

TiDB doesn't panic.

### 3. What did you see instead (Required)

TiDB paniced and restarted.

### 4. What is your TiDB version? (Required)

8.1. But I think it affects all existing versions until now (312226f869d56922135e1c177cac6c90319c3134)

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #62673 

Problem Summary:

The current implementation of `LOAD DATA ... INFILE ...` doesn't wait for the background goroutine (which is used to continuously read file data from client) to stop. Therefore, if the `LOAD DATA` statement meets any error, it's possible that the connection has two reading goroutines:

1. Expect to read the file data.
2. Expect to read the next command.

Then there will be a data race in the internal buffer, and cause deadlock or panic. The user reported a panic but in my testcase it'd be easier to reproduce deadlock (but theoritically all possible, maybe related to the error position).

### What changed and how does it work?

Also create a `WaitGroup` to wait for this goroutine to finish before stepping to the next statement.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that if the `LOAD DATA ... INFILE ...` meets error, it may cause panic or deadlock.
```

### CODE REVIEW

File: pkg/server/tests/commontest/tidb_test.go [hunk 1]
```diff
@@ -3534,3 +3534,38 @@ func TestCloseConnForUndeterminedError(t *testing.T) {
...
+			err := os.WriteFile(filePath, fmt.Appendf(nil, "%d\n", i), os.ModePerm)
+			require.NoError(t, err)
+		}
+
+		conn, err := dbt.GetDB().Conn(ctx)
+		require.NoError(t, err)
+
+		testserverclient.MustExec(ctx, t, conn, "create table t (a int)")
+
+		err = failpoint.Enable("github.com/pingcap/tidb/pkg/executor/InCommitWork", "panic(\"mock panic\")")
```
Comment (lance6716) [inline pkg/server/tests/commontest/tidb_test.go]: 1. we have `testfailpoint` package to simplify these lines
2. Why this is panic? The effect of panic is not clear, maybe `sleep` is better

Comment (YangKeao) [reply pkg/server/tests/commontest/tidb_test.go]: > we have testfailpoint package to simplify these lines

Thanks! Modified.

> Why this is panic? The effect of panic is not clear, maybe sleep is better

Because this issue will occur when `(w *commitWorker) commitWork` returns an error. 

I agree that the `panic` is not clear. I've modified it into:

```go
failpoint.Inject("CommitWorkError", func(_ failpoint.Value) {
	failpoint.Return(errors.New("mock commit work error"))
})
```

**Comment by lance6716** [comment]
```
pkg/executor/test/loaddatatest/load_data_test.go:46:54: cannot use (func(_ string) (r io.ReadCloser, err error) literal) (value of type func(_ string) (r io.ReadCloser, err error)) as executor.LoadDataReaderBuilder value in variable declaration
```
