### PR TITLE
planner: increase tablescan cost for high risk scenarios | tidb-test=pr/2399

### LINKED ISSUE #56012: optimizer picks wrong driving table in nested loop join
### 1. Minimal reproduce step (Required)

```sql
mysql> show create table d\G
*************************** 1. row ***************************
       Table: d
Create Table: CREATE TABLE `d` (
  `a` bigint(20) unsigned NOT NULL,
  `object_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `b` longblob DEFAULT NULL,
  `c` int(11) unsigned NOT NULL,
  PRIMARY KEY (`object_id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1242984075789489121 /*T![auto_id_cache] AUTO_ID_CACHE=1 */
1 row in set (0.00 sec)

mysql> show create table i\G
*************************** 1. row ***************************
       Table: i
Create Table: CREATE TABLE `i` (
  `object_id` bigint(20) unsigned NOT NULL,
  `b` bigint(20) DEFAULT NULL,
  `a` varbinary(767) DEFAULT NULL,
  `c` bigint(20) DEFAULT NULL,
  `d` varbinary(767) DEFAULT NULL,
  `e` int(11) unsigned NOT NULL,
  PRIMARY KEY (`object_id`) /*T![clustered_index] CLUSTERED */,
  KEY `a` (`a`,`object_id`),
  KEY `b` (`d`,`object_id`),
  UNIQUE KEY `c` (`c`,`b`),
  KEY `d` (`c`,`b`,`object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
1 row in set (0.00 sec)

explain SELECT
  d.*
FROM
  i 
  LEFT JOIN d ON i.`object_id` = d.`object_id`
WHERE
  i.`a` = 0xaaa
ORDER BY
  i.`object_id`
LIMIT
  20;

```

### 2. What did you expect to see? (Required)

Execution plan should use index nested loop join on table `d` because there is a where predicate on an indexed column on table `i`.

### 3. What did you see instead (Required)
```sql
mysql> explain SELECT
    ->   d.*
    -> FROM
    ->   i 
    ->   LEFT JOIN d ON i.`object_id` = d.`object_id`
    -> WHERE
    ->   i.`a` = 0xaaa
    -> ORDER BY
    ->   i.`object_id`
    -> LIMIT
    ->   20;
+-----------------------------------+---------+-----------+--------------------------------+------------------------------------------------------------------------+
| id                                | estRows | task      | access object                  | operator info                                                          |
+-----------------------------------+---------+-----------+--------------------------------+------------------------------------------------------------------------+
| Projection_12                     | 0.00    | root      |                                | test.d.a, test.d.object_id, test.d.b, test.d.c                         |
| └─Limit_19                        | 0.00    | root      |                                | offset:0, count:20                                                     |
|   └─MergeJoin_56                  | 0.00    | root      |                                | left outer join, left key:test.i.object_id, right key:test.d.object_id |
|     ├─TableReader_44(Build)       | 36.00   | root      |                                | data:TableFullScan_43                                                  |
|     │ └─TableFullScan_43          | 36.00   | cop[tikv] | table:d                        | keep order:true                                                        |
|     └─Limit_35(Probe)             | 0.00    | root      |                                | offset:0, count:20                                                     |
|       └─IndexReader_42            | 0.00    | root      |                                | index:Limit_41                                                         |
|         └─Limit_41                | 0.00    | cop[tikv] |                                | offset:0, count:20                                                     |
|           └─IndexRangeScan_40     | 0.00    | cop[tikv] | table:i, index:a(a, object_id) | range:["\n\xaa","\n\xaa"], keep order:true                             |
+-----------------------------------+---------+-----------+--------------------------------+------------------------------------------------------------------------+
9 rows in set (0.01 sec)

mysql> explain SELECT /*+ inl_join(d) */
    ->   d.*
    -> FROM
    ->   i 
    ->   LEFT JOIN d ON i.`object_id` = d.`object_id`
    -> WHERE
    ->   i.`a` = 0xaaa
    -> ORDER BY
    ->   i.`object_id`
    -> LIMIT
    ->   20;
+-------------------------------------+---------+-----------+--------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                  | estRows | task      | access object                  | operator info                                                                                                                                    |
+-------------------------------------+---------+-----------+--------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_12                       | 0.00    | root      |                                | test.d.a, test.d.object_id, test.d.b, test.d.c                                                                                                   |
| └─Limit_19                          | 0.00    | root      |                                | offset:0, count:20                                                                                                                               |
|   └─IndexJoin_46                    | 0.00    | root      |                                | left outer join, inner:TableReader_43, outer key:test.i.object_id, inner key:test.d.object_id, equal cond:eq(test.i.object_id, test.d.object_id) |
|     ├─Limit_54(Build)               | 0.00    | root      |                                | offset:0, count:20                                                                                                                               |
|     │ └─IndexReader_59              | 0.00    | root      |                                | index:Limit_58                                                                                                                                   |
|     │   └─Limit_58                  | 0.00    | cop[tikv] |                                | offset:0, count:20                                                                                                                               |
|     │     └─IndexRangeScan_38       | 0.00    | cop[tikv] | table:i, index:a(a, object_id) | range:["\n\xaa","\n\xaa"], keep order:true                                                                                                       |
|     └─TableReader_43(Probe)         | 0.00    | root      |                                | data:TableRangeScan_42                                                                                                                           |
|       └─TableRangeScan_42           | 0.00    | cop[tikv] | table:d                        | range: decided by [test.i.object_id], keep order:false                                                                                           |
+-------------------------------------+---------+-----------+--------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
9 rows in set (0.01 sec)

```
### 4. What is your TiDB version? (Required)

mysql> select @@version;
+--------------------+
| @@version          |
+--------------------+
| 8.0.11-TiDB-v7.5.1 |
+--------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #56012

Problem Summary:

### What changed and how does it work?

Add a cost penalty to table scan if we encounter a scenario where a table scan may be risky or we should be preferencing away from table scan.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/plan_cost_ver2.go [hunk 1]
```diff
@@ -141,6 +141,10 @@ func (p *PhysicalTableScan) GetPlanCostVer2(taskType property.TaskType, option *
 	// give TiFlash a start-up cost to let the optimizer prefers to use TiKV to process small table scans.
 	if p.StoreType == kv.TiFlash {
 		p.PlanCostVer2 = costusage.SumCostVer2(p.PlanCostVer2, scanCostVer2(option, 10000, rowSize, scanFactor))
+	} else if !p.isChildOfIndexLookUp && (p.SCtx().GetSessionVars().GetAllowPreferRangeScan() && (p.tblColHists.Pseudo || p.tblColHists.RealtimeCount < 1)) || p.tblColHists.ModifyCount > p.tblColHists.RealtimeCount {
```
Comment (ngaut) [inline pkg/planner/core/plan_cost_ver2.go:144]: The function GetPlanCostVer2 is quite complicated, hard to maintain. And There some some places we can further optimize. Such as remove magic numbers, something like this would be more clear.
```go
const (
    MinRowSize             = 2.0
    TiFlashStartupRowPenalty = 10000
    MaxPenaltyRowCount     = 1000
)

// GetPlanCostVer2 returns the plan-cost of this sub-plan, which is:
// plan-cost = rows * log2(row-size) * scan-factor
// log2(row-size) is from experiments.
func (p *PhysicalTableScan) GetPlanCostVer2(taskType property.TaskType, option *optimizetrace.PlanCostOption) (costusage.CostVer2, error) {
    if p.PlanCostInit && !hasCostFlag(option.CostFlag, costusage.CostFlagRecalculate) {
        return p.PlanCostVer2, nil
    }

    rows := getCardinality(p, option.CostFlag)
    
    var columns []Column
    if p.StoreType == kv.TiKV {
        columns = p.tblCols
    } else { // TiFlash
        columns = p.schema.Columns
    }
    rowSize := getAvgRowSize(p.StatsInfo(), columns)
    // Ensure rowSize has a reasonable minimum value to avoid underestimation
    rowSize = math.Max(rowSize, MinRowSize)
    
    scanFactor := getTaskScanFactorVer2(p, p.StoreType, taskType)
    p.PlanCostVer2 = scanCostVer2(option, rows, rowSize, scanFactor)

    // Apply TiFlash startup cost to prefer TiKV for small table scans
    if p.StoreType == kv.TiFlash {
        p.PlanCostVer2 = costusage.SumCostVer2(p.PlanCostVer2, scanCostVer2(option, TiFlashStartupRowPenalty, rowSize, scanFactor))
    } else {
        sessionVars := p.SCtx().GetSessionVars()
        allowPreferRangeScan := sessionVars.GetAllowPreferRangeScan()
        tblColHists := p.tblColHists

        preferRangeScanCondition := allowPreferRangeScan && (tblColHists.Pseudo || tblColHists.RealtimeCount < 1)
        hasHighModifyCount := tblColHists.ModifyCount > tblColHists.RealtimeCount
        shouldApplyPenalty := !p.isChildOfIndexLookUp && (preferRangeScanCondition || hasHighModifyCount)

        if shouldApplyPenalty {
            newRowCount := math.Min(MaxPenaltyRowCount, math.Max(float64(tblColHists.ModifyCount), float64(tblColHists.RealtimeCount)))
            p.PlanCostVer2 = costusage.SumCostVer2(p.PlanCostVer2, scanCostVer2(option, newRowCount, rowSize, scanFactor))
        }
    }

    p.PlanCostInit = true
    return p.PlanCostVer2, nil
}

```

File: pkg/planner/core/plan_cost_ver2.go [hunk 2]
```diff
@@ -127,20 +136,38 @@ func (p *PhysicalTableScan) GetPlanCostVer2(taskType property.TaskType, option *
...
+		sessionVars := p.SCtx().GetSessionVars()
+		allowPreferRangeScan := sessionVars.GetAllowPreferRangeScan()
+		tblColHists := p.tblColHists
+
+		preferRangeScanCondition := allowPreferRangeScan && (tblColHists.Pseudo || tblColHists.RealtimeCount < 1)
+		hasHighModifyCount := tblColHists.ModifyCount > tblColHists.RealtimeCount
+		hasLowEstimate := rows > 1 && int64(rows) < tblColHists.RealtimeCount && int64(rows) <= tblColHists.ModifyCount
+		shouldApplyPenalty := !p.isChildOfIndexLookUp && (preferRangeScanCondition || hasHighModifyCount || hasLowEstimate)
+
+		if shouldApplyPenalty {
```
Comment (qw4990) [inline pkg/planner/core/plan_cost_ver2.go:167]: Better to add some comments for this, and add https://github.com/pingcap/tidb/issues/56012 as an unit test.

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/core/plan_cost_ver2.go [hunk 3]
```diff
@@ -127,20 +136,41 @@ func (p *PhysicalTableScan) GetPlanCostVer2(taskType property.TaskType, option *
...
+		allowPreferRangeScan := sessionVars.GetAllowPreferRangeScan()
+		tblColHists := p.tblColHists
+
+		// preferRangeScan check here is same as in skylinePruning
+		preferRangeScanCondition := allowPreferRangeScan && (tblColHists.Pseudo || tblColHists.RealtimeCount < 1)
+		// hasHighModifyCount tracks the high risk of a tablescan where auto-analyze had not yet updated the table row count
+		hasHighModifyCount := tblColHists.ModifyCount > tblColHists.RealtimeCount
+		// hasLowEstimate is a check to capture a unique customer case where modifyCount is used for tablescan estimate (but it not adequately understood why)
+		hasLowEstimate := rows > 1 && int64(rows) < tblColHists.RealtimeCount && int64(rows) <= tblColHists.ModifyCount
+		shouldApplyPenalty := !p.isChildOfIndexLookUp && (preferRangeScanCondition || hasHighModifyCount || hasLowEstimate)
```
Comment (winoros) [inline pkg/planner/core/plan_cost_ver2.go:168]: We can add a check about `ranger.HasFullRange` to solve some changed tests.

**Review by time-and-fate — APPROVED** [review]

File: pkg/executor/test/fktest/foreign_key_test.go [hunk 4]
```diff
@@ -1680,7 +1680,7 @@ func TestForeignKeyOnUpdateCascade(t *testing.T) {
 			tk.MustExec("update t1 set a=101 where id = 1")
 			tk.MustExec("insert into t2 (id, a, b, name) values (1, 1, 1, 'a')")
 			tk.MustExec("update t1 set b=102 where id = 2")
-			tk.MustQuery("select * from t1").Check(testkit.Rows("1 101 1", "2 1 102"))
+			tk.MustQuery("select * from t1").Check(testkit.Rows("2 1 102", "1 101 1"))
```
Comment (mjonss) [inline pkg/executor/test/fktest/foreign_key_test.go:1683]: To make the test result stable, without require ORDER BY, just add `.Sort()`
```suggestion
			tk.MustQuery("select * from t1").Sort().Check(testkit.Rows("1 101 1", "2 1 102"))
```
