### PR TITLE
ddl: use original column name in duplicate column error

### LINKED ISSUE #9285: Error message about "create table" is not same with MYSQL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Exec SQL 
```sql
 create table tt( charID varchar(10), charID varchar(10) charset utf8mb4 );
```

2. What did you expect to see?

```SQL
mysql>  create table tt( charID varchar(10), charID varchar(10) charset utf8mb4 );
ERROR 1060 (42S21): Duplicate column name 'charID'
mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.7.25-0ubuntu0.18.04.2 |
+-------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```sql
TiDB>  create table tt( charID varchar(10), charID varchar(10) charset utf8mb4 );
ERROR 1060 (42S21): Duplicate column name 'charid'
TiDB> select version();
+----------------------------------------------+
| version()                                    |
+----------------------------------------------+
| 5.7.10-TiDB-v2.1.0-rc.3-528-g98c22dd2d-dirty |
+----------------------------------------------+
1 row in set (0.01 sec)

```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```SQL
TiDB> select tidb_version() \G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-528-g98c22dd2d-dirty
Git Commit Hash: 98c22dd2d5bd91c8b63c8866a717d31054d25ca6
Git Branch: TiDB-2866
UTC Build Time: 2019-02-12 09:12:22
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)

```

### PR DESCRIPTION
**Pull request by u5surf**
### What problem does this PR solve? 
fix #9285 

### Check List 

 - Unit test
OK, I checked following
https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md#run-test
 - Integration test
What is integration tests ? and how can I ?
 - Manual test (add detailed scripts or steps below)
```
$mysql -u root -P 4000 -h 127.0.0.1
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7.10-TiDB-v3.0.0-beta-52-g55da8ad9f MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| INFORMATION_SCHEMA |
| PERFORMANCE_SCHEMA |
| mysql              |
| test               |
+--------------------+
4 rows in set (0.00 sec)

mysql> use test;
Database changed
mysql> show tables;
Empty set (0.00 sec)

mysql> create table tt( ID123 int , ID123 int );
ERROR 1060 (42S21): Duplicate column name 'ID123'
mysql> create table tt( charID varchar(10) , charID varchar(10) charset utf8mb4);
ERROR 1060 (42S21): Duplicate column name 'charID'
mysql> create table tt( WHYNOTUPPER char , WHYNOTUPPER int);
ERROR 1060 (42S21): Duplicate column name 'WHYNOTUPPER'
mysql>
```

Code changes

 - Has exported function/method change
no
 - Has exported variable/fields change
no
 - Has interface methods change
no
 - Has persistent data change
no

Side effects
 - Possible performance regression
probably no
 - Increased code complexity
no
 - Breaking backward compatibility
no

Related changes

 - Need to cherry-pick to the release branch
nothing
 - Need to update the documentation
nothing
 - Need to update the `tidb-ansible` repository
?
 - Need to be included in the release note
probably nothing??

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -630,17 +630,21 @@ func checkColumnValueConstraint(col *table.Column) error {
 func checkDuplicateColumn(cols []interface{}) error {
 	colNames := set.StringSet{}
 	var nameLower string
+	var nameOriginal string
```
Comment (zz-jason) [inline ddl/ddl_api.go]: how about using `model.CIStr` to replace these two variables? for example:
```go
colName := model.NewCIStr("")
for _, col := range cols {
	switch x := col.(type) {
	case *ast.ColumnDef:
		colName = x.Name.Name
	case model.CIStr:
		colName = x
	default:
		colName.O, colName.L = "", ""
	}
}
```

**Comment by u5surf** [comment]
i fixed  `TestFieldCase` to check column name case strictly.

before:(if column name  includes bigcase character as `Field`)
```
PASS: column_test.go:844: testColumnSuite.TestDropColumn	0.192s

----------------------------------------------------------------------
FAIL: column_test.go:960: testColumnSuite.TestFieldCase

column_test.go:975:
    c.Assert(err.Error(), Equals, infoschema.ErrColumnExists.GenWithStackByArgs("Field").Error())
... obtained string = "[schema:1060]Duplicate column name 'field'"
... expected string = "[schema:1060]Duplicate column name 'Field'"


----------------------------------------------------------------------
```
after: fixed
```
ok  	github.com/pingcap/tidb/config	0.022s	coverage: 18.9% of statements
ok  	github.com/pingcap/tidb/ddl	48.576s	coverage: 78.6% of statements
```

**Comment by zz-jason** [comment]
LGTM

**Comment by zz-jason** [comment]
@u5surf Please cherry pick this commit to release 2.1 and release 2.0 branches.
