### PR TITLE
server: return results of ongoing queries when graceful shutdown

### LINKED ISSUE #19663: Got `Query execution was interrupted` when graceful shutdown
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
create table t(a int);
select 1 from t where (select sleep(3)) ;
```

During the sleeping, kill(sig terminate) the tidb-server

### 2. What did you expect to see? (Required)

```
Empty set (3.01 sec)
```
And after the result returned, the server exits gracefully.

### 3. What did you see instead (Required)

```
ERROR 1317 (70100): Query execution was interrupted
```
## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve?

Issue Number: close #19663 

Problem Summary:

Got `Query execution was interrupted` when graceful shutdown

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Should not return `ErrQueryInterrupted` when server state is `connStatusWaitShutdown`. Results of ongoing queries should be returned successfully when graceful shutdown.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Add an e2e test:

master:
```bash
$ make
cd /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb && \
	CGO_ENABLED=1 GO111MODULE=on go build  -tags codes -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v4.0.0-beta.2-1669-gb3f8be7d3" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2020-11-30 09:26:36" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=b3f8be7d3c9a719d043f41db14b62d259a79ecb2" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=master" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community"' -o /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb/tests/graceshutdown/bin/tidb-server tidb-server/main.go
Build TiDB Server successfully!
$ ./run-tests.sh
INFO[0000] starting tidb: bin/tidb-server --store=mocktikv --path=/tmp/tidb_gracefulshutdown/mocktikv -P=5501 --status=8500 --log-file=/tmp/tidb_gracefulshutdown/tidb5501.log 
INFO[0000] connect to server 127.0.0.1:5501 ok          
INFO[0001] service "tidb" Interrupt                     

----------------------------------------------------------------------
FAIL: graceshutdown_test.go:113: TestGracefulShutdownSuite.TestGracefulShutdown

graceshutdown_test.go:144:
    c.Assert(err, IsNil)
... value *mysql.MySQLError = &mysql.MySQLError{Number:0x525, Message:"Query execution was interrupted"} ("Error 1317: Query execution was interrupted")

OOPS: 0 passed, 1 FAILED
--- FAIL: TestGracefulShutdown (3.54s)
FAIL
exit status 1
FAIL	graceshutdown	3.557s
```

This branch:
```
$ make
cd /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb && \
	CGO_ENABLED=1 GO111MODULE=on go build  -tags codes -ldflags '-X "github.com/pingcap/parser/mysql.TiDBReleaseVersion=v4.0.0-beta.2-1671-g77e9fc4ad" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2020-11-30 09:21:36" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=77e9fc4ada3d6266f7d8e8702574f4c8d261e794" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=issue19663" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community"' -o /Users/sunrunaway/code/gopath/src/github.com/pingcap/tidb/tests/graceshutdown/bin/tidb-server tidb-server/main.go
Build TiDB Server successfully!
$ ./run-tests.sh
INFO[0000] starting tidb: bin/tidb-server --store=mocktikv --path=/tmp/tidb_gracefulshutdown/mocktikv -P=5501 --status=8500 --log-file=/tmp/tidb_gracefulshutdown/tidb5501.log 
INFO[0000] connect to server 127.0.0.1:5501 ok          
INFO[0001] service "tidb" Interrupt                                          
PASS: graceshutdown_test.go:113: TestGracefulShutdownSuite.TestGracefulShutdown	3.538s
OK: 1 passed
PASS
ok  	graceshutdown	3.549s
```

### Release note 

- return results of ongoing queries when graceful shutdown.

### CODE REVIEW

**Comment by SunRunAway** [comment]
Should cherry-pick to release-4.0 and release-3.0 manually.

File: server/server.go [hunk 1]
```diff
@@ -486,9 +486,6 @@ func (s *Server) ShowProcessList() map[uint64]*util.ProcessInfo {
 	defer s.rwlock.RUnlock()
 	rs := make(map[uint64]*util.ProcessInfo, len(s.clients))
 	for _, client := range s.clients {
-		if atomic.LoadInt32(&client.status) == connStatusWaitShutdown {
-			continue
```
Comment (tiancaiamao) [inline server/server.go:490]: Somebody once complained that he use `kill tidb connection XXX`, but could still see the session in `show processlist`.
Here is a fix for him.

**Review by tiancaiamao — COMMENTED** [review]
> Results of ongoing queries should be returned successfully when graceful shutdown.

~~This may affect the correctness! we can either return a full of data with success, or an error.
When the query is interrupted, we can not be sure the integrity of the data.~~

File: server/server.go (hunk 1 above)
Comment (SunRunAway) [reply server/server.go:490]: I think it should stay in `processlist` because it is really running and not fully closed. Maybe we can show a `closing` state for hime.

**Comment by tiancaiamao** [comment]
What I mean has nothing to do with 'connection reset by peer'.
We **should** return 100 lines, but we returns 50 lines, and we tell the client OK, that's not acceptable.

We **should** return 100 lines, but we can't guarantee the integrity of these data, so we return Interrupted error, that's more reasonable.

**Comment by tiancaiamao** [comment]
Graceful shutdown does not set the `Killed` flag, so the data are fully drained.
 (Even the `Killed` flag is set, the `Next()` function will return an error).
We can ensure the integrity of the data, so it does not involve correctness issue.

From the client's point of view, when the server enter graceful shutdown mode, it's better for the ongoing connection to reply a success before it's closed, rather than replying a interrupted error and close.
So after the change, the behavior is more reasonable.

**Comment by tiancaiamao** [comment]
LGTM

**Review by zz-jason — COMMENTED** [review]
how about adding some tests?

File: server/conn.go [hunk 2]
```diff
@@ -689,7 +689,10 @@ func (cc *clientConn) Run(ctx context.Context) {
 	// The client connection would detect the events when it fails to change status
 	// by CAS operation, it would then take some actions accordingly.
 	for {
-		if !atomic.CompareAndSwapInt32(&cc.status, connStatusDispatching, connStatusReading) {
+		if !atomic.CompareAndSwapInt32(&cc.status, connStatusDispatching, connStatusReading) ||
+			// The judge below will not be hit by all means,
```
[the remark this answers is not in the document]
Comment (qw4990) [reply server/conn.go:693]: PTAL @SunRunAway

**Review by qw4990 — COMMENTED** [review]
Almost LGTM, Please add some tests.

**Comment by SunRunAway** [comment]
@zz-jason @qw4990 An e2e test is added and the results are appended in PR description. PTAL again, thanks.

**Review by zz-jason — COMMENTED** [review]
can we move the contents in `tests/graceshutdown/.gitignore` to `.gitignore`?

File: tests/graceshutdown/graceshutdown_test.go [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+		err = db.Ping()
+		if err == nil {
+			break
+		}
+		log.Warnf("ping addr %v failed, retry count %d err %v", addr, i, err)
+
+		db.Close()
+		time.Sleep(sleepTime)
+		sleepTime += sleepTime
+	}
```
Comment (qw4990) [inline tests/graceshutdown/graceshutdown_test.go:102]: What's the purpose of this loop?

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by SunRunAway** [comment]
> can we move the contents in `tests/graceshutdown/.gitignore` to `.gitignore`?

I prefer keeping it in `tests/graceshutdown/` so this directory is a complete and independent component.
