### PR TITLE
*: support error handling for distributed adding index

### LINKED ISSUE #42436: The "add index" operation is block when dist-reorg is enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set @@global.tidb_ddl_distribute_reorg = on;
create table t(a int, b int);
alter table t add index idx(a);
```

### 2. What did you expect to see? (Required)
This "add index" operation executes normally.

### 3. What did you see instead (Required)
This operation is blocked.
The error log：` ["[ddl] runBackfillJobs error"] [error="[ddl:8247]Ingest failed: ingest engine not found"]`

### 4. What is your TiDB version? (Required)

master, after the PR: https://github.com/pingcap/tidb/pull/42115
```
Release Version: v6.7.0-alpha-347-g3f8b0ccd81-dirty
Edition: Community
Git Commit Hash: 3f8b0ccd81374a27a466db2e934737503905b30c
Git Branch: master
UTC Build Time: 2023-03-21 07:22:27
```

### LINKED ISSUE #43029: support error handling

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #43029, close #42436
Problem Summary:
This PR supports error handling for distributed adding index.
It 
1. modify the task tables in distribute framework, adding the error field.
2. adjust the framework to record the subtask's error.
3. do unsafeImport when finishing a partition when adding an index.
4. check the remote duplicate key if it's the unique index.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/scheduler.go [hunk 1]
```diff
@@ -182,19 +184,27 @@ func (b *backfillSchedulerHandle) SplitSubtask(_ context.Context, subtask []byte
...
+		return nil, err
+	}
 	return nil, consumer.getResult()
 }
 
 // CleanupSubtaskExecEnv implements the Scheduler interface.
 func (b *backfillSchedulerHandle) CleanupSubtaskExecEnv(context.Context) error {
 	logutil.BgLogger().Info("[ddl] lightning cleanup subtask exec env")
 
-	err := b.bc.FinishImport(b.index.ID, b.index.Unique, b.ptbl)
```
Comment (Benjamin2037) [inline ddl/scheduler.go:193]: Must call finishImport to close engine and backend correctly before scheduler finished one step of the global task, otherwise, it will still be leak.

Comment (wjhuang2016) [reply ddl/scheduler.go:193]: engine is closed by Unregister()

File: ddl/ingest/backend.go [hunk 2]
```diff
@@ -38,6 +38,8 @@ type BackendCtx interface {
 	Register(jobID, indexID int64, schemaName, tableName string) (Engine, error)
 	Unregister(jobID, indexID int64)
 
+	CollectRemoteDuplicateRows(indexID int64, tbl table.Table) error
+	UnsafeImportAndReset(ctx context.Context, indexID int64, regionSplitSize, regionSplitKeys int64) error
```
Comment (tangenta) [inline ddl/ingest/backend.go:42]: Remove this method since it is unused.

File: session/bootstrap.go [hunk 3]
```diff
@@ -857,11 +858,13 @@ const (
...
 	// This will only happens when we upgrade a cluster before 7.1.
 	version141 = 141
+	// version 141 add column `error` to `mysql.tidb_global_task` and `mysql.tidb_background_subtask`
+	version142 = 142
 )
 
 // currentBootstrapVersion is defined as a variable, so we can modify its value for testing.
 // please make sure this is the largest version
-var currentBootstrapVersion int64 = version140
+var currentBootstrapVersion int64 = version141
```
Comment (tangenta) [inline session/bootstrap.go:867]:
```suggestion
var currentBootstrapVersion int64 = version142
```

File: ddl/index.go [hunk 4]
```diff
@@ -662,7 +662,7 @@ func (w *worker) onCreateIndex(d *ddlCtx, t *meta.Meta, job *model.Job, isPK boo
 		job.SnapshotVer = 0
 		job.SchemaState = model.StateWriteReorganization
 
-		if job.MultiSchemaInfo == nil {
+		if job.MultiSchemaInfo == nil && tblInfo.GetPartitionInfo() != nil {
```
Comment (Benjamin2037) [inline ddl/index.go:665]: Why not let MultiSchemaChange go with distributed execution? @tangenta we need support with several adding indexes in one statement.

Comment (wjhuang2016) [reply ddl/index.go:665]: I don't change the behavior. Which is the same as before.

Comment (tangenta) [reply ddl/index.go:665]: If we have considered it in the test plan, supporting multi-schema change is fine.

File: ddl/ingest/backend.go [hunk 5]
```diff
@@ -100,6 +125,8 @@ func (bc *litBackendCtx) FinishImport(indexID int64, unique bool, tbl table.Tabl
 	return nil
 }
 
+const importThreshold = 0.85
+
```
Comment (tangenta) [inline ddl/ingest/backend.go:129]:
```suggestion
```

**Review by tangenta — COMMENTED** [review]
Rest LGTM

File: ddl/index.go (hunk 4 above)
Comment (Benjamin2037) [reply ddl/index.go:665]: Yes, it is better include all add index subjob could go distributed way.

File: ddl/index.go [hunk 6]
```diff
@@ -1760,8 +1760,24 @@ func (w *worker) addPhysicalTableIndex(t table.PhysicalTable, reorgInfo *reorgIn
...
 	// TODO: Support typeAddIndexMergeTmpWorker.
 	if reorgInfo.Job.ReorgMeta.IsDistReorg && !reorgInfo.mergingTmpIdx {
-		if t.Meta().Partition != nil && reorgInfo.ReorgMeta.ReorgTp == model.ReorgTypeLitMerge {
-			return executeDistGlobalTask(reorgInfo)
+		if reorgInfo.ReorgMeta.ReorgTp == model.ReorgTypeLitMerge {
+			err := executeDistGlobalTask(reorgInfo)
+			if err != nil {
+				return err
+			}
+			indexInfo := model.FindIndexInfoByID(t.Meta().Indices, reorgInfo.currElement.ID)
```
Comment (Benjamin2037) [inline ddl/index.go:1768]: What is the usage of line 1764 to 1780 code block?

Comment (Benjamin2037) [reply ddl/index.go:1768]: I think, so far we do not real run subtask, right? then line 1772 to 1779 can be removed?

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by tangenta — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]

**Review by XuHuaiyu — APPROVED** [review]
