### PR TITLE
executor: fix The JSON Data can not import to TiDB correctly by `load data`

### LINKED ISSUE #20136: The JSON Data can not import to TiDB correctly by `load data`
## Description
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
While using the `load data` statement to load the CSV file inculd JSON, it can not import the data to TiDB correctly. Just like the file following.
```shell
> cat load_json.csv
"aaa"
"{""itemRangeType"":0,""itemContainType"":0,""shopRangeType"":0}"
"{""itemRangeType"":0,""itemContainType"":0,""shopRangeType"":1,""shopJson"":""[{\""id\"":\""A1234\"",\""shopName\"":\""AAAAAA\""}]""}"
"{""itemRangeType"":0,""itemContainType"":0,""shopRangeType"":1,""shopJson"":""[{\""id\"":\""A1234\"",\""shopName\"":\""AAAAAA\""}]""}"
```


### 2. What did you expect to see? (Required)
Just like MySQL can load data correctly.
```sql
mysql> select version();
+-----------+
| version() |
+-----------+
| 5.7.31    |
+-----------+
1 row in set (0.07 sec)

mysql> drop table if exists load_json;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE `load_json` ( `aaa` VARCHAR ( 2000 ) );
Query OK, 0 rows affected (0.08 sec)

mysql> load data local infile '/data/load_json.csv' ignore  into table load_json columns terminated by ',' enclosed by '"' escaped by '' ignore 1 lines (`aaa`);
Query OK, 2 rows affected (0.07 sec)
Records: 2  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from load_json;
+---------------------------------------------------------------------------------------------------------------------+
| aaa                                                                                                                 |
+---------------------------------------------------------------------------------------------------------------------+
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":0}                                                           |
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":1,"shopJson":"[{\"id\":\"A1234\",\"shopName\":\"AAAAAA\"}]"} |
+---------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.09 sec)

```
### 3. What did you see instead (Required)
```sql
mysql> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                             |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.5
Edition: Community
Git Commit Hash: 9c1c21270001a0084dcb5d842c50e1fbea5d1fa8
Git Branch: heads/refs/tags/v4.0.5
UTC Build Time: 2020-08-28 10:07:42
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.10 sec)

mysql> drop table if exists load_json;
Query OK, 0 rows affected (0.19 sec)

mysql> CREATE TABLE `load_json` ( `aaa` VARCHAR ( 2000 ) );
Query OK, 0 rows affected (0.07 sec)

mysql> load data local infile '/data/load_json.csv' ignore  into table load_json columns terminated by ',' enclosed by '"' escaped by '' ignore 1 lines (`aaa`);
Query OK, 2 rows affected (0.01 sec)
Records: 2  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from load_json; 
+----------------------------------------------------------------------------------------+
| aaa                                                                                    |
+----------------------------------------------------------------------------------------+
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":0}                              |
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":1,"shopJson":"[{""id"":""A1234" | 
+----------------------------------------------------------------------------------------+
2 rows in set (0.10 sec)
```
### 4. What is your TiDB version? (Required)
```
Release Version: v4.0.5
Edition: Community
Git Commit Hash: 9c1c21270001a0084dcb5d842c50e1fbea5d1fa8
Git Branch: heads/refs/tags/v4.0.5
UTC Build Time: 2020-08-28 10:07:42
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```
<!-- Paste the output of SELECT tidb_version() -->


## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 900

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by pengdaqian2020**
### What problem does this PR solve?

Issue Number: close #20136 

Problem Summary:

### What is changed and how it works?

What's Changed:

change load data reader

How it Works:

load data will consistent with mysql

### Check List

Tests

- Manual test (add detailed scripts or steps below)
```
> cat load_json.csv
"aaa"
"{""itemRangeType"":0,""itemContainType"":0,""shopRangeType"":0}"
"{""itemRangeType"":0,""itemContainType"":0,""shopRangeType"":1,""shopJson"":""[{\""id\"":\""A1234\"",\""shopName\"":\""AAAAAA\""}]""}"
"{""itemRangeType"":0,""itemContainType"":0,""shopRangeType"":1,""shopJson"":""[{\""id\"":\""A1234\"",\""shopName\"":\""AAAAAA\""}]""}"

mysql> drop table if exists load_json;
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> CREATE TABLE `load_json` ( `aaa` VARCHAR ( 2000 ) );
Query OK, 0 rows affected (0.00 sec)

mysql> load data local infile '/data/load_json.csv' ignore  into table load_json columns terminated by ',' enclosed by '"' escaped by '' ignore 1 lines (`aaa`); 
Query OK, 3 rows affected (0.01 sec)
Records: 3  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from load_json; 
+---------------------------------------------------------------------------------------------------------------------+
| aaa                                                                                                                 |
+---------------------------------------------------------------------------------------------------------------------+
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":0}                                                           |
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":1,"shopJson":"[{\"id\":\"A1234\",\"shopName\":\"AAAAAA\"}]"} |
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":1,"shopJson":"[{\"id\":\"A1234\",\"shopName\":\"AAAAAA\"}]"} |
+---------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)
```
Side effects

- Performance regression
    - Consumes more CPU
No
    - Consumes more MEM
No
- Breaking backward compatibility
No
### Release note

- fix The JSON Data can not import to TiDB correctly by `load data`

### CODE REVIEW

**Comment by pengdaqian2020** [comment]
I have test on mysql.
```
> cat /data/load_json.csv
"n","str","value"
"1","a string","100.20"
"2","a string containing a , comma","102.20"
"3","a string containing a \" quote","102.20"
"4","a string containing a \", quote and comma","102.20"

mysql> select version();
+-----------+
| version() |
+-----------+
| 5.7.31    |
+-----------+
1 row in set (0.00 sec)

mysql> use test;
Database changed
mysql> drop table if exists load_json;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE `load_json` ( `n` VARCHAR (2000), `str` VARCHAR (2000), `value` VARCHAR (2000) );
Query OK, 0 rows affected (0.01 sec)

mysql> load data local infile '/data/load_json.csv' ignore  into table load_json columns terminated by ',' enclosed by '"' escaped by '' ignore 1 lines ;
Query OK, 4 rows affected, 1 warning (0.00 sec)
Records: 4  Deleted: 0  Skipped: 0  Warnings: 1

mysql> select * from load_json; 
+------+--------------------------------+-------------------+
| n    | str                            | value             |
+------+--------------------------------+-------------------+
| 1    | a string                       | 100.20            |
| 2    | a string containing a , comma  | 102.20            |
| 3    | a string containing a \" quote | 102.20            |
| 4    | a string containing a \        |  quote and comma" |
+------+--------------------------------+-------------------+
4 rows in set (0.00 sec)
```

It seems that the test should like this

**Comment by pengdaqian2020** [comment]
@lzmhhh123 PLTA

File: executor/load_data.go [hunk 1]
```diff
@@ -750,7 +750,20 @@ func (w *fieldWriter) GetField() (bool, field) {
 			flag, ch = w.getChar()
 			if flag {
 				w.OutputBuf = append(w.OutputBuf, '\\')
-				w.OutputBuf = append(w.OutputBuf, ch)
+				if ch == w.enclosedChar {
```
Comment (lzmhhh123) [inline executor/load_data.go:753]: It's not a correct fix. The `load data` statement in issue uses `ESCAPED BY ''`. It means the statement doesn't do any escape. The correct fix is to fully support `ESCAPED BY`.

Comment (lzmhhh123) [reply executor/load_data.go:753]: Could you test some cases without `ESCAPED BY ''`?

Comment (pengdaqian2020) [reply executor/load_data.go:753]: In this case without `ESCAPED BY ''` the result is same
```
mysql> load data local infile '/data/load_json.csv' ignore  into table load_json columns terminated by ',' enclosed by '"'  ignore 1 lines (`aaa`);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from load_json; 
+---------------------------------------------------------------------------------------------------------------------+
| aaa                                                                                                                 |
+---------------------------------------------------------------------------------------------------------------------+
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":0}                                                           |
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":1,"shopJson":"[{\"id\":\"A1234\",\"shopName\":\"AAAAAA\"}]"} |
| {"itemRangeType":0,"itemContainType":0,"shopRangeType":1,"shopJson":"[{\"id\":\"A1234\",\"shopName\":\"AAAAAA\"}]"} |
+---------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

**Comment by ichn-hu** [comment]
@pengdaqian2020 why don't you add the test into the test suite?

**Comment by pengdaqian2020** [comment]
> @pengdaqian2020 why don't you add the test into the test suite?

Done.

**Review by ichn-hu — APPROVED** [review]
LGTM

**Comment by pengdaqian2020** [comment]
@SunRunAway PLAT

**Review by lzmhhh123 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
