### PR TITLE
lightning: optimize region split check logic

### LINKED ISSUE #30018: TiKV stores contains more than 1000 empty regions respectively after one importing, which blocks the next import
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Lauch a T3 TiDB Cloud cluster
2. Import TPCC 5000 warehouse data from s3://dbaas-benchmark-2/tpcc5k-parquet/
3. import sysbench data from s3://dbaas-benchmark-1/sysbench-table16-10m-parquet/

### 2. What did you expect to see? (Required)
All the dataset was imported successfully.

### 3. What did you see instead (Required)
image

The error message was too long that the most important part wasn't show on the console. The user just didn't know what's going wrong and got confused.

Log:
```
[2021/11/22 11:51:06.094 +00:00] [ERROR] [lightning.go:219] ["tidb lightning encountered error"] [error="tidb-lightning check failed. Please fix the failed check(s):\n Source csv files size is proper;\ncheckpoints are valid;\ntable schemas are valid;\nCluster is available;\nLightning has the correct storage permission;\nlocal disk resources are rich, estimate sorted data size 18.45GiB, local available is 2.953TiB;\nCluster available is rich, available is 2.153TiB, we need 55.34GiB;\nTiKV stores (5, 1, 4) contains more than 1000 empty regions respectively, which will greatly affect the import speed and success rate;\nCluster region distribution is balanced"] [errorVerbose="tidb-lightning check failed. Please fix the failed check(s):\n Source csv files size is proper;\ncheckpoints are valid;\ntable schemas are valid;\nCluster is available;\nLightning has the correct storage permission;\nlocal disk resources are rich, estimate sorted data size 18.45GiB, local available is 2.953TiB;\nCluster available is rich, available is 2.153TiB, we need 55.34GiB;\nTiKV stores (5, 1, 4) contains more than 1000 empty regions respectively, which will greatly affect the import speed and success rate;\nCluster region distribution is balanced\ngithub.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).preCheckRequirements\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/restore.go:1929\ngithub.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/restore.go:446\ngithub.com/pingcap/tidb/br/pkg/lightning.(*Lightning).run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/lightning.go:331\ngithub.com/pingcap/tidb/br/pkg/lightning.(*Lightning).RunServer\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/lightning.go:216\nmain.main.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/tidb-lightning/main.go:80\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/tidb-lightning/main.go:87\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]
```

### 4. What is your TiDB version? (Required)

Lightning version 5.3.0
```
| Release Version: v5.2.1
Edition: Community
Git Commit Hash: cd8fb24c5f7ebd9d479ed228bb41848bd5e97445
Git Branch: heads/refs/tags/v5.2.1
UTC Build Time: 2021-09-08 02:32:56
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #30018

Problem Summary: After tidb-lightning importing, there are a lot of empty region in tidb, and these regions won't automatically merge until 1h later.

### What is changed and how it works?
- Decreate default region max-keys from 1_440_000 to 1_280_000.
- Compact the SSTs before ingest into pebble event if the data size is smaller so lightning can estimate region range better in this case.

Analysis:

In the current implementation, lightning will ingest a SST file into one region with at most 1440k kvs or 128MiB(with default region-split-size) in size. 1440k is the region auto split threshold that will cause tikv auto split.

With some data set, because lightning can accurately estimate the region range, so the kvs in a region range  slightly exceeds the key count threshold, then lightning will ingest these keys into two region, one with 1440k kvs and another small region this pd will treat it as empty region. Thus after lightning import, the bigger region will cause tidb auto-split. Due to pd's region merge row, pd will prevent one of the new split region and the nearly empty region merging before 1h later.

Test result:
Before this PR, after lightning import there are a lot of empty region in grafana and tikv logs contains 1k+ log with following pattern:
```
[2021/11/29 21:47:16.871 +08:00] [INFO] [split_check.rs:289] ["update approximate size and keys with accurate value"] [keys=1440000] [size=132480000] [region_id=12554]
```

After this pr:

There are still empty regions after lightning import, but these regions can be merge in a few minutes. There are no region auto-split after import.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
 - See PR description
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
 - Because we force tirgger compact even if the data set is relatively small (< 100GB), this will cause more CPU consume though is overhead is small. 
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Avoid tikv trigger auto region split by lower the ingest kv count threshold 
```

### CODE REVIEW

File: br/pkg/lightning/backend/local/local.go [hunk 1]
```diff
@@ -782,7 +783,12 @@ func (local *local) WriteToTiKV(
 	size := int64(0)
 	totalCount := int64(0)
 	firstLoop := true
-	regionMaxSize := regionSplitSize * 4 / 3
+	// if region-split-size <= 96MiB, we bump the threshold a bit to avoid too many retry split
+	// because the range-properties is not 100% accurate
```
Comment (gozssky) [inline br/pkg/lightning/backend/local/local.go:787]: Can we desrease `defaultPropSizeIndexDistance` to get more accurate results? Since it doesn't cost too much memory.

**Review by gozssky — APPROVED** [review]

File: br/pkg/lightning/backend/local/local.go (hunk 1 above)
Comment (glorv) [reply br/pkg/lightning/backend/local/local.go:787]: I have tested smaller value 1MiB/10000, but there is no much difference. Maybe we can do deeper investigation to know the root reason.😅

**Review by kennytm — APPROVED** [review]
