### PR TITLE
executor: fix unstable test TestPointGetForTemporaryTable

### LINKED ISSUE #54702: TestPointGetForTemporaryTable timed out after 5m0s
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
 [2024/07/17 12:55:00.445 +00:00] [INFO] [store_cache.go:1058] ["store health status changed"] [storeID=1] [isSlow=true] [healthDetail="{ ClientSideSlowScore: 100, TiKVSideSlowScore: 0 }"]
[2024/07/17 12:55:02.415 +00:00] [INFO] [region_request.go:968] ["throwing pseudo region error due to no replica available"] [req-ts=451207665072209921] [req-type=Get] [region="{ region id: 2, ver: 1, confVer: 1 }"] [replica-read-type=leader] [stale-read=false] [request-sender="{rpcError:<nil>, replicaSelector: replicaSelectorV2{replicaReadType: leader, attempts: 11, cacheRegionIsValid: false, replicaStatus: [peer: 3, store: 1, isEpochStale: false, attempts: 10, attempts_time: 133.8µs, replica-epoch: 0, store-epoch: 0, store-state: resolved, store-liveness-state: reachable]}}"] [total-round-stats="{total-backoff: 4m15.2s, total-backoff-times: 39}"] [current-round-stats="{time: 1m13s, backoff: 1m12.9s, timeout: 30s, req-max-exec-timeout: 30s, retry-times: 10}"]
[2024/07/17 12:55:30.329 +00:00] [INFO] [store_cache.go:1058] ["store health status changed"] [storeID=1] [isSlow=false] [healthDetail="{ ClientSideSlowScore: 1, TiKVSideSlowScore: 0 }"]
[2024/07/17 12:55:30.339 +00:00] [INFO] [store_cache.go:1058] ["store health status changed"] [storeID=1] [isSlow=true] [healthDetail="{ ClientSideSlowScore: 100, TiKVSideSlowScore: 0 }"]
panic: test timed out after 5m0s
running tests:
	TestPointGetForTemporaryTable (5m0s)
goroutine 11736 [running]:
testing.(*M).startAlarm.func1() 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/54673/fast_test_tiprow/1813554170221826048#1:build-log.txt%3A2013

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #54702

Problem Summary:

### What changed and how does it work?

The test tests temporary table does not visit network. But when infoschema v2 is used, table by name also visit network. 
So the test is not appliabl to infoschema v2, just skip it in that case.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/batch_point_get_test.go [hunk 1]
```diff
@@ -201,17 +202,24 @@ func TestCacheSnapShot(t *testing.T) {
 }
 
 func TestPointGetForTemporaryTable(t *testing.T) {
-	store := testkit.CreateMockStore(t)
+	store, dom := testkit.CreateMockStoreAndDomain(t)
 
 	tk := testkit.NewTestKit(t, store)
 	tk.MustExec("use test")
+
+
```
Comment (hawkingrei) [inline pkg/executor/batch_point_get_test.go:210]:
```suggestion

```

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]
