### PR TITLE
ddl: fix create table like would not split regions on TiKV

### LINKED ISSUE #14881: create table like will not split regions on TiKV
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
mysql> create table test1 (id int, data varchar(100));
mysql> create table test2 like test1;
```

2. What did you expect to see?
There are two batch split command executed in TiKV.

3. What did you see instead?
It just split once.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
All are 2.1.18.

### PR DESCRIPTION
**Pull request by reafans**
### What problem does this PR solve? 
Fix #14881

### What is changed and how it works?
1. Remove `CreateTableWithLike()` and move the logic from `CreateTableWithLike()` to `CreateTable()`.
2. Make `create table`  and `create table like` share the `split region logic`.

MockTikv could not split region, so test split region in TiDB cluster.

**1. Test split region when create table like:**
```
mysql root@127.0.0.1:test> create table t1(i int);                                                                                                                                                          
Query OK, 0 rows affected
Time: 0.128s

on PD cmd：
[2020/03/05 19:28:21.914 +08:00] [INFO] [cluster_worker.go:213] ["region batch split, generate new regions"] [region-id=2] [origin="id:44 start_key:\"7480000000000000FF2B00000000000000F8\" end_key:\"7480000000000000FF2D00000000000000F8\" region_epoch:<conf_ver:1 version:22 > peers:<id:45 store_id:1 >"] [total=1]
[2020/03/05 19:28:21.915 +08:00] [INFO] [cluster.go:440] ["region Version changed"] [region-id=2] [detail="StartKey Changed:{7480000000000000FF2B00000000000000F8} -> {7480000000000000FF2D00000000000000F8}, EndKey:{}"] [old-version=21] [new-version=22]

no TiKV cmd：
[2020/03/05 19:28:21.900 +08:00] [INFO] [peer.rs:315] ["on split"] [split_keys="key 7480000000000000FF2D00000000000000F8"] [peer_id=3] [region_id=2]
[2020/03/05 19:28:21.901 +08:00] [INFO] [pd.rs:438] ["try to batch split region"] [region="id: 2 start_key: 7480000000000000FF2B00000000000000F8 region_epoch { conf_ver: 1 version: 21 } peers { id: 3 store_id: 1 }"] [new_region_ids="[new_region_id: 44 new_peer_ids: 45]"] [region_id=2]
[2020/03/05 19:28:21.905 +08:00] [INFO] [apply.rs:1100] ["execute admin command"] [command="cmd_type: BatchSplit splits { requests { split_key: 7480000000000000FF2D00000000000000F8 new_region_id: 44 new_peer_ids: 45 } right_derive: true }"] [index=54] [term=7] [peer_id=3] [region_id=2]
[2020/03/05 19:28:21.906 +08:00] [INFO] [apply.rs:1684] ["split region"] [keys="key 7480000000000000FF2D00000000000000F8"] [region="id: 2 start_key: 7480000000000000FF2B00000000000000F8 region_epoch { conf_ver: 1 version: 21 } peers { id: 3 store_id: 1 }"] [peer_id=3] [region_id=2]
[2020/03/05 19:28:21.913 +08:00] [INFO] [peer.rs:1507] ["notify pd with split"] [split_count=2] [peer_id=3] [region_id=2]


mysql root@127.0.0.1:test> create table t2 like t1;                                                                                                                                                         
Query OK, 0 rows affected
Time: 0.122s

on PD cmd：
[2020/03/05 19:28:52.849 +08:00] [INFO] [cluster.go:440] ["region Version changed"] [region-id=2] [detail="StartKey Changed:{7480000000000000FF2D00000000000000F8} -> {7480000000000000FF2F00000000000000F8}, EndKey:{}"] [old-version=22] [new-version=23]
[2020/03/05 19:28:52.849 +08:00] [INFO] [cluster_worker.go:213] ["region batch split, generate new regions"] [region-id=2] [origin="id:46 start_key:\"7480000000000000FF2D00000000000000F8\" end_key:\"7480000000000000FF2F00000000000000F8\" region_epoch:<conf_ver:1 version:23 > peers:<id:47 store_id:1 >"] [total=1]

no TiKV cmd：
[2020/03/05 19:28:52.821 +08:00] [INFO] [peer.rs:315] ["on split"] [split_keys="key 7480000000000000FF2F00000000000000F8"] [peer_id=3] [region_id=2]
[2020/03/05 19:28:52.822 +08:00] [INFO] [peer.rs:2587] ["epoch changed, retry later"] [epoch="conf_ver: 1 version: 21"] [prev_epoch="conf_ver: 1 version: 22"] [peer_id=3] [region_id=2]
[2020/03/05 19:28:52.826 +08:00] [INFO] [peer.rs:315] ["on split"] [split_keys="key 7480000000000000FF2F00000000000000F8"] [peer_id=3] [region_id=2]
[2020/03/05 19:28:52.828 +08:00] [INFO] [pd.rs:438] ["try to batch split region"] [region="id: 2 start_key: 7480000000000000FF2D00000000000000F8 region_epoch { conf_ver: 1 version: 22 } peers { id: 3 store_id: 1 }"] [new_region_ids="[new_region_id: 46 new_peer_ids: 47]"] [region_id=2]
[2020/03/05 19:28:52.832 +08:00] [INFO] [apply.rs:1100] ["execute admin command"] [command="cmd_type: BatchSplit splits { requests { split_key: 7480000000000000FF2F00000000000000F8 new_region_id: 46 new_peer_ids: 47 } right_derive: true }"] [index=55] [term=7] [peer_id=3] [region_id=2]
[2020/03/05 19:28:52.833 +08:00] [INFO] [apply.rs:1684] ["split region"] [keys="key 7480000000000000FF2F00000000000000F8"] [region="id: 2 start_key: 7480000000000000FF2D00000000000000F8 region_epoch { conf_ver: 1 version: 22 } peers { id: 3 store_id: 1 }"] [peer_id=3] [region_id=2]
[2020/03/05 19:28:52.849 +08:00] [INFO] [peer.rs:1507] ["notify pd with split"] [split_count=2] [peer_id=3] [region_id=2]
```

**2. Test pre_split_region when create table like:**
```
mysql> create table t (a int, b int,index idx1(a)) shard_row_id_bits = 4 pre_split_regions=2;
Query OK, 0 rows affected (0.01 sec)
mysql root@127.0.0.1:INFORMATION_SCHEMA> select `REGION_ID`,`DB_NAME`,`TABLE_NAME`,`INDEX_NAME` from TIKV_REGION_STATUS where `DB_NAME` = 'test'and `TABLE_NAME` = 't';                                     
+-------------+-----------+--------------+--------------+
| REGION_ID   | DB_NAME   | TABLE_NAME   | INDEX_NAME   |
|-------------+-----------+--------------+--------------|
| 50          | test      | t            | <null>       |
| 52          | test      | t            | <null>       |
| 48          | test      | t            | idx1         |
| 48          | test      | t            | <null>       |
| 2           | test      | t            | <null>       |
+-------------+-----------+--------------+--------------+
5 rows in set
Time: 0.035s


mysql root@127.0.0.1:(none)> create table test.t3 like test.t;                                                                                                                                              
Query OK, 0 rows affected
Time: 0.115s
mysql root@127.0.0.1:(none)> select `REGION_ID`,`DB_NAME`,`TABLE_NAME`,`INDEX_NAME` from information_schema.TIKV_REGION_STATUS where `DB_NAME` = 'test'and `TABLE_NAME` = 't3';                             
+-------------+-----------+--------------+--------------+
| REGION_ID   | DB_NAME   | TABLE_NAME   | INDEX_NAME   |
|-------------+-----------+--------------+--------------|
| 68          | test      | t3           | <null>       |
| 66          | test      | t3           | <null>       |
| 2           | test      | t3           | <null>       |
| 64          | test      | t3           | idx1         |
| 64          | test      | t3           | <null>       |
+-------------+-----------+--------------+--------------+
5 rows in set
Time: 0.038s
```
### Check List 

Tests 
 - Integration test

### CODE REVIEW

File: ddl/ddl.go [hunk 1]
```diff
@@ -257,7 +257,6 @@ type DDL interface {
 	DropSchema(ctx sessionctx.Context, schema model.CIStr) error
 	CreateTable(ctx sessionctx.Context, stmt *ast.CreateTableStmt) error
 	CreateView(ctx sessionctx.Context, stmt *ast.CreateViewStmt) error
-	CreateTableWithLike(ctx sessionctx.Context, ident, referIdent ast.Ident, ifNotExists bool) error
```
Comment (tangenta) [inline ddl/ddl.go]: Will this interface change break other codebases?

Comment (reafans) [reply ddl/ddl.go]: This interface only implemented by ddl struct, and the `func (d *ddl) CreateTableWithLike(ctx sessionctx.Context, ident, referIdent ast.Ident, ifNotExists bool) error` has been deleted, so it would not break other codebases.

**Comment by reafans** [comment]
> Can you add a test case to verify that it will split and scatter?

File: ddl/table_split_test.go [hunk 2]
```diff
@@ -64,6 +64,22 @@ func (s *testDDLTableSplitSuite) TestTableSplit(c *C) {
 	for _, def := range pi.Definitions {
 		checkRegionStartWithTableID(c, def.ID, store.(kvStore))
 	}
+
+	// test split region when create table like
+	tk.MustExec("create table t1(i int)")
```
Comment (djshow832) [inline ddl/table_split_test.go]: Try to add `pre_split_regions 2`.

File: ddl/table_split_test.go [hunk 3]
```diff
@@ -64,6 +64,22 @@ func (s *testDDLTableSplitSuite) TestTableSplit(c *C) {
...
+	tk.MustExec("create table t2 like t1")
+	t2, err := infoSchema.TableByName(model.NewCIStr("mysql"), model.NewCIStr("tidb"))
```
Comment (tangenta) [inline ddl/table_split_test.go]: Why is it `mysql.tidb`?

File: ddl/table_split_test.go (hunk 2 above)
Comment (reafans) [reply ddl/table_split_test.go]: add test in the front of this page

File: ddl/table_split_test.go (hunk 3 above)
Comment (reafans) [reply ddl/table_split_test.go]: This test is useless, I remove it and add the new test in the front of this page

File: ddl/ddl_api.go [hunk 4]
```diff
@@ -1348,6 +1289,9 @@ func buildTableInfoWithLike(ident ast.Ident, referTblInfo *model.TableInfo) mode
 	tblInfo.Name = ident.Name
 	tblInfo.AutoIncID = 0
 	tblInfo.ForeignKeys = nil
+	tblInfo.PKIsHandle = referTblInfo.PKIsHandle
+	tblInfo.ShardRowIDBits = referTblInfo.ShardRowIDBits
+	tblInfo.PreSplitRegions = referTblInfo.PreSplitRegions
```
Comment (crazycs520) [inline ddl/ddl_api.go]: line #1292 ~ 1294 is redundant?

File: ddl/serial_test.go [hunk 5]
```diff
@@ -338,6 +338,25 @@ func (s *testSerialSuite) TestCreateTableWithLike(c *C) {
 	tk.MustExec("create table ctwl_db1.pt1 like ctwl_db.pt1;")
 	tk.MustQuery("select * from ctwl_db1.pt1").Check(testkit.Rows())
 
+	// for pre_split_table
```
Comment (crazycs520) [inline ddl/serial_test.go]: The test doesn't test this PR, the master branch can pass this test too.

Comment (crazycs520) [reply ddl/serial_test.go]: You may need test like `TestShowTableRegion`.

File: ddl/ddl_api.go (hunk 4 above)
Comment (reafans) [reply ddl/ddl_api.go]: Yes. Removed.

File: ddl/serial_test.go (hunk 5 above)
Comment (reafans) [reply ddl/serial_test.go]: Add test show table region
