### PR TITLE
session: fix bug user privileges change after upgrade from 4.0.11 to 5.0

### LINKED ISSUE #23387: v4.0.11 upgrade to v5.0.0, user privileges changed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create user quatest with create privi on v4.0.11
MySQL [(none)]> create user qatest;grant Create on *.* to qatest;
Query OK, 0 rows affected (0.03 sec)
2. upgrade to v5.0.0
3. check user privileges

### 2. What did you expect to see? (Required)
MySQL [(none)]> show grants for qatest;
+-------------------------------------+
| Grants for qatest@%                 |
+-------------------------------------+
| GRANT Create ON *.* TO 'qatest'@'%' |
+-------------------------------------+
1 row in set (0.00 sec)

### 3. What did you see instead (Required)

MySQL [(none)]> show grants for qatest;
+--------------------------------------------------------------------------+
| Grants for qatest@%                                                      |
+--------------------------------------------------------------------------+
| GRANT Create,REPLICATION CLIENT,REPLICATION SLAVE ON *.* TO 'qatest'@'%' |
+--------------------------------------------------------------------------+
1 row in set (0.00 sec)

### 4. What is your TiDB version? (Required)

MySQL [test]> SELECT tidb_version() ;
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                     |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.0.0
Edition: Community
Git Commit Hash: 46f5f217725ea1d29a584c790f830d7c8d85d885
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-03-15 06:21:59
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]>

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #23387

Problem Summary:

https://github.com/pingcap/tidb/pull/21856/ introduce the problem, it adds `Repl_slave_priv` to all existing users while it should just do that for the root user.

### What is changed and how it works?

What's Changed:

Just assign the newly introduced privileges to the root user, rather than all existing users.

How it Works:

Make the behavior more acceptable when upgrading.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

I try to do the unit test but failed. 
I thought I can use the initial versioned data, and upgrade the version one by one.
But the upgrading process failed, which means when we upgrade a very old TiDB cluster to the newest one, it may not succeed.

```
+func (s *testBootstrapSuite) TestAddPrivilegeColumn(c *C) {
+       // For issue https://github.com/pingcap/tidb/issues/23387
+       store, err := mockstore.NewMockStore()
+       c.Assert(err, IsNil)
+       defer store.Close()
+
+       se, err := createSession(store)
+       c.Assert(err, IsNil)
+       se.SetValue(sessionctx.Initing, true)
+       bootstrapToV1(se)
+       se.ClearValue(sessionctx.Initing)
+
+       // upgradeToCurrentBootstrapVersion(se, 33)
+
+
+       // se1, err := CreateSession4Test(store)
+       // mustExecSQL(c, se1, "use test")
+       // mustExecSQL(c, se1, "create user 'qatest'")
+       // mustExecSQL(c, se1, "grant Create on *.* to qatest")
+
+
+       // upgradeToCurrentBootstrapVersion(se, 44)
+       // upgradeToCurrentBootstrapVersion(se, 55)
+
+       // rs := mustExecSQL(c, se1, "show grants for qatest")
+       // _, err = ResultSetToStringSlice(context.Background(), se1, rs)
+       // c.Assert(err, IsNil)
+       // tk.c.Check(errors.ErrorStack(err), check.Equals, "", comment)
+       // return &Result{rows: sRows, c: tk.c, comment: comment}
+
+       upgradeToCurrentBootstrapVersion(se, 67)
+}
+
+func bootstrapToV1(s Session) {
+       const (
+               // CreateUserTable is the SQL statement creates User table in system db.
+               CreateUserTableV1 = `CREATE TABLE if not exists mysql.user (
+               Host                    CHAR(64),
+               User                    CHAR(16),
+               Password                CHAR(41),
+               Select_priv             ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Insert_priv             ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Update_priv             ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Delete_priv             ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Create_priv             ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Drop_priv               ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Grant_priv              ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Alter_priv              ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Show_db_priv            ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Execute_priv            ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Index_priv              ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               Create_user_priv        ENUM('N','Y') NOT NULL  DEFAULT 'N',
+               PRIMARY KEY (Host, User));`
+               // CreateDBPrivTable is the SQL statement creates DB scope privilege table in system db.
+               CreateDBPrivTableV1 = `CREATE TABLE if not exists mysql.db (
+               Host            CHAR(60),
+               DB              CHAR(64),
+               User            CHAR(16),
+               Select_priv     ENUM('N','Y') Not Null  DEFAULT 'N',
+               Insert_priv     ENUM('N','Y') Not Null  DEFAULT 'N',
+               Update_priv     ENUM('N','Y') Not Null  DEFAULT 'N',
+               Delete_priv     ENUM('N','Y') Not Null  DEFAULT 'N',
+               Create_priv     ENUM('N','Y') Not Null  DEFAULT 'N',
+               Drop_priv       ENUM('N','Y') Not Null  DEFAULT 'N',
+               Grant_priv      ENUM('N','Y') Not Null  DEFAULT 'N',
+               Index_priv      ENUM('N','Y') Not Null  DEFAULT 'N',
+               Alter_priv      ENUM('N','Y') Not Null  DEFAULT 'N',
+               Execute_priv    ENUM('N','Y') Not Null  DEFAULT 'N',
+               PRIMARY KEY (Host, DB, User));`
+               // CreateTablePrivTable is the SQL statement creates table scope privilege table in system db.
+               CreateTablePrivTableV1 = `CREATE TABLE if not exists mysql.tables_priv (
+               Host            CHAR(60),
+               DB              CHAR(64),
+               User            CHAR(16),
+               Table_name      CHAR(64),
+               Grantor         CHAR(77),
+               Timestamp       Timestamp DEFAULT CURRENT_TIMESTAMP,
+               Table_priv      SET('Select','Insert','Update','Delete','Create','Drop','Grant', 'Index','Alter'),
+               Column_priv     SET('Select','Insert','Update'),
+               PRIMARY KEY (Host, DB, User, Table_name));`
+               // CreateColumnPrivTable is the SQL statement creates column scope privilege table in system db.
+               CreateColumnPrivTableV1 = `CREATE TABLE if not exists mysql.columns_priv(
+               Host            CHAR(60),
+               DB              CHAR(64),
+               User            CHAR(16),
+               Table_name      CHAR(64),
+               Column_name     CHAR(64),
+               Timestamp       Timestamp DEFAULT CURRENT_TIMESTAMP,
+               Column_priv     SET('Select','Insert','Update'),
+               PRIMARY KEY (Host, DB, User, Table_name, Column_name));`
+               // CreateGloablVariablesTable is the SQL statement creates global variable table in system db.
+               // TODO: MySQL puts GLOBAL_VARIABLES table in INFORMATION_SCHEMA db.
+               // INFORMATION_SCHEMA is a virtual db in TiDB. So we put this table in system db.
+               // Maybe we will put it back to INFORMATION_SCHEMA.
+               CreateGloablVariablesTableV1 = `CREATE TABLE if not exists mysql.GLOBAL_VARIABLES(
+               VARIABLE_NAME  VARCHAR(64) Not Null PRIMARY KEY,
+               VARIABLE_VALUE VARCHAR(1024) DEFAULT Null);`
+               // CreateTiDBTable is the SQL statement creates a table in system db.
+               // This table is a key-value struct contains some information used by TiDB.
+               // Currently we only put bootstrapped in it which indicates if the system is already bootstrapped.
+               CreateTiDBTableV1 = `CREATE TABLE if not exists mysql.tidb(
+               VARIABLE_NAME  VARCHAR(64) Not Null PRIMARY KEY,
+               VARIABLE_VALUE VARCHAR(1024) DEFAULT Null,
+               COMMENT VARCHAR(1024));`
+
+               // CreateHelpTopic is the SQL statement creates help_topic table in system db.
+               // See: https://dev.mysql.com/doc/refman/5.5/en/system-database.html#system-database-help-tables
+               CreateHelpTopicV1 = `CREATE TABLE if not exists mysql.help_topic (
+               help_topic_id int(10) unsigned NOT NULL,
+               name char(64) NOT NULL,
+               help_category_id smallint(5) unsigned NOT NULL,
+               description text NOT NULL,
+               example text NOT NULL,
+               url text NOT NULL,
+               PRIMARY KEY (help_topic_id),
+               UNIQUE KEY name (name)
+               ) ENGINE=InnoDB DEFAULT CHARSET=utf8 STATS_PERSISTENT=0 COMMENT='help topics';`
+       )
+
+       mustExecute(s, "CREATE DATABASE IF NOT EXISTS test")
+       mustExecute(s, fmt.Sprintf("CREATE DATABASE IF NOT EXISTS %s;", mysql.SystemDB))
+       mustExecute(s, CreateUserTableV1)
+       mustExecute(s, CreateDBPrivTableV1)
+       mustExecute(s, CreateTablePrivTableV1)
+       mustExecute(s, CreateColumnPrivTableV1)
+       mustExecute(s, CreateGloablVariablesTableV1)
+       mustExecute(s, CreateTiDBTableV1)
+       mustExecute(s, CreateHelpTopicV1)
+
+       mustExecute(s, "BEGIN")
+       mustExecute(s, `INSERT INTO mysql.user VALUES ("%", "root", "", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y", "Y")`)
+       mustExecute(s, `INSERT INTO mysql.tidb VALUES('bootstrapped', 'True', 'Bootstrap flag. Do not delete.')`)
+       mustExecute(s, "COMMIT")
+}
```

[log.txt](https://github.com/pingcap/tidb/files/6162639/log.txt)

Side effects

This just fix the code, if a user upgrades his cluster and meets the bug, he have to fix the data manually.

### Release note 

- Fix a bug when upgrading from 4.X to 5.0, the existing users obtain `REPLICATION CLIENT` and `REPLICATION` privileges unexpectedly.

### CODE REVIEW

**Review by zz-jason — COMMENTED** [review]
could you add some tests?

**Comment by tiancaiamao** [comment]
> could you add some tests?

Done

File: session/bootstrap.go [hunk 1]
```diff
@@ -477,11 +477,14 @@ const (
...
 	// version67 restore all SQL bindings.
 	version67 = 67
-
-	// please make sure this is the largest version
-	currentBootstrapVersion = version67
 )
 
+// currentBootstrapVersion is modified to a function so we can hook its value for testing.
+// please make sure this is the largest version
+var currentBootstrapVersion = func() int64 {
```
Comment (djshow832) [inline session/bootstrap.go:484]: Why not define it as a non-const variable?

Comment (xhebox) [inline session/bootstrap.go:484]: Can not we use failpoint instead of making it a variable? It is always bad to have global variables.

File: session/bootstrap.go [hunk 2]
```diff
@@ -1443,7 +1446,7 @@ func upgradeToVer64(s Session, ver int64) {
 	}
 	doReentrantDDL(s, "ALTER TABLE mysql.user ADD COLUMN `Repl_slave_priv` ENUM('N','Y') CHARACTER SET utf8 NOT NULL DEFAULT 'N' AFTER `Execute_priv`", infoschema.ErrColumnExists)
 	doReentrantDDL(s, "ALTER TABLE mysql.user ADD COLUMN `Repl_client_priv` ENUM('N','Y') CHARACTER SET utf8 NOT NULL DEFAULT 'N' AFTER `Repl_slave_priv`", infoschema.ErrColumnExists)
-	mustExecute(s, "UPDATE HIGH_PRIORITY mysql.user SET Repl_slave_priv='Y',Repl_client_priv='Y'")
+	mustExecute(s, "UPDATE HIGH_PRIORITY mysql.user SET Repl_slave_priv='Y',Repl_client_priv='Y' where Super_priv='Y'")
```
Comment (djshow832) [inline session/bootstrap.go:1449]: Do any operations rely on these privileges? I'm afraid it will break compatibility if you shrink the privilege.

**Review by xhebox — COMMENTED** [review]
Rest LGTM

File: session/bootstrap.go (hunk 2 above)
Comment (xhebox) [reply session/bootstrap.go:1449]: I think the description has clarified the case: 

>  it adds Repl_slave_priv to all existing users while it should just do that for the root user.

File: session/bootstrap.go (hunk 1 above)
Comment (zimulala) [reply session/bootstrap.go:484]: PTAL @tiancaiamao

File: session/bootstrap.go [hunk 3]
```diff
@@ -477,11 +477,12 @@ const (
 	version66 = 66
 	// version67 restore all SQL bindings.
 	version67 = 67
-
-	// please make sure this is the largest version
-	currentBootstrapVersion = version67
 )
 
+// currentBootstrapVersion is defined as a variable, so we can modify its value for testing.
+// please make sure this is the largest version
```
Comment (zimulala) [inline session/bootstrap.go:483]:
```suggestion
// Please make sure this is the largest version.
```

File: session/bootstrap.go (hunk 1 above)
Comment (tiancaiamao) [reply session/bootstrap.go]: Done
