### PR TITLE
tests: improve timing robustness in TestStaleReadAllCombinations

### LINKED ISSUE #63271: flaky test TestStaleReadAllCombinations
```
=== NAME  TestStaleReadAllCombinations
    result.go:49: 
        	Error Trace:	pkg/testkit/result.go:49
        	            				tests/realtikvtest/txntest/stale_read_test.go:1717
        	Error:      	Not equal: 
        	            	expected: "[1 10]\n"
        	            	actual  : "[1 10]\n[2 20]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,3 @@
        	            	 [1 10]
        	            	+[2 20]
        	            	 
        	Test:       	TestStaleReadAllCombinations
        	Messages:   	sql:select * from t, args:[]
=== NAME  TestStaleReadAllCombinations/with_multiple_labels/closest-adaptive/tidb_read_staleness
    testing.go:1577: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestStaleReadAllCombinations/with_multiple_labels/closest-adaptive/tidb_read_staleness (0.00s)
```

https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_check2/runs/39527/nodes/106/steps/662/log/?start=0

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #63271

Problem Summary:

The `TestStaleReadAllCombinations/tidb_read_staleness` test case is flaky under high CI load due to tight timing constraints.

### What changed and how does it work?

**Changes made:**

1. Relax the time constraints
2. Reorder cases, to run `tidb_read_staleness` cases first 

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory  
- [ ] Breaking backward compatibility

Documentation
- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: tests/realtikvtest/txntest/stale_read_test.go [hunk 1]
```diff
@@ -1508,20 +1508,20 @@ func TestStaleReadAllCombinations(t *testing.T) {
 
 	// Insert row #1
 	tk.MustExec("insert into t values (1, 10)")
-	time.Sleep(1000 * time.Millisecond)
-	firstTime := time.Now().Add(-500 * time.Millisecond)
+	time.Sleep(3000 * time.Millisecond)                   // Increased from 1s to 3s for better timing separation
+	firstTime := time.Now().Add(-1500 * time.Millisecond) // Adjusted offset
```
Comment (you06) [inline tests/realtikvtest/txntest/stale_read_test.go]: What about calculating the ts from PD tso?

```suggestion
	ts, err := tk.Session().GetStore().GetOracle().GetTimestamp(context.Background(), &oracle.Option{})
	require.NoError(t, err)
	firstTime := oracle.GetTimeFromTS(ts).Add(-1500 * time.Millisecond) // Adjusted offset
```

File: tests/realtikvtest/txntest/stale_read_test.go [hunk 2]
```diff
@@ -1508,20 +1508,20 @@ func TestStaleReadAllCombinations(t *testing.T) {
...
 
-	time.Sleep(1000 * time.Millisecond)
+	time.Sleep(3000 * time.Millisecond) // Increased from 1s to 3s
 	// Insert row #2
 	tk.MustExec("insert into t values (2, 20)")
 	row2CreatedTime := time.Now()
-	time.Sleep(1000 * time.Millisecond)
-	secondTime := time.Now().Add(-500 * time.Millisecond)
+	time.Sleep(3000 * time.Millisecond)                    // Increased from 1s to 3s
+	secondTime := time.Now().Add(-1500 * time.Millisecond) // Adjusted offset
```
Comment (you06) [inline tests/realtikvtest/txntest/stale_read_test.go]: Ditto.

```suggestion
	ts, err = tk.Session().GetStore().GetOracle().GetTimestamp(context.Background(), &oracle.Option{})
	require.NoError(t, err)
	secondTime := oracle.GetTimeFromTS(ts).Add(-1500 * time.Millisecond) // Adjusted offset
```

File: tests/realtikvtest/txntest/stale_read_test.go [hunk 3]
```diff
@@ -1534,7 +1534,9 @@ func TestStaleReadAllCombinations(t *testing.T) {
 			name: "tidb_read_staleness",
 			setup: func() {
 				row2CreatedElapsed := int(time.Since(row2CreatedTime).Seconds())
-				staleness := row2CreatedElapsed + 1 // The time `now - staleness(second)` is between row1 and row2.
+				// Ensure sufficient buffer: with 3s sleep intervals, elapsed should be ~3s
+				// Adding 2s buffer ensures stale read is safely before row2 insertion
+				staleness := row2CreatedElapsed + 2
```
Comment (you06) [inline tests/realtikvtest/txntest/stale_read_test.go:1547]: And get the `row2CreatedElapsed` from PD tso.

File: tests/realtikvtest/txntest/stale_read_test.go [hunk 4]
```diff
@@ -1508,20 +1508,20 @@ func TestStaleReadAllCombinations(t *testing.T) {
 
 	// Insert row #1
 	tk.MustExec("insert into t values (1, 10)")
-	time.Sleep(1000 * time.Millisecond)
-	firstTime := time.Now().Add(-500 * time.Millisecond)
+	time.Sleep(3000 * time.Millisecond)                   // Increased from 1s to 3s for better timing separation
```
Comment (lance6716) [inline tests/realtikvtest/txntest/stale_read_test.go]: can we use failpoint to add some hook, to make sure async actions are done?

**Comment by ekexium** [comment]
Looks like stale read tests are stabilized now in CI. Close this for now. Reconsider these change when needed

**Comment by ekexium** [comment]
I guess the key is not about timing, but slow executions of so many permutations affecting `tidb_read_staleness` tests. I put them first. cc @you06 @lance6716

File: tests/realtikvtest/txntest/stale_read_test.go [hunk 5]
```diff
@@ -1508,20 +1509,24 @@ func TestStaleReadAllCombinations(t *testing.T) {
...
 	// Insert row #1
 	tk.MustExec("insert into t values (1, 10)")
-	time.Sleep(1000 * time.Millisecond)
-	firstTime := time.Now().Add(-500 * time.Millisecond)
-	// Retrieve current TSO from store's Oracle instead of @@tidb_current_ts.
-	externalTS, err := store.GetOracle().GetTimestamp(context.Background(), &oracle.Option{})
-	if err != nil {
-		t.Fatalf("failed to get TSO: %v", err)
-	}
+	time.Sleep(3000 * time.Millisecond) // Increased from 1s to 3s for better timing separation
```
Comment (MyonKeminta) [inline tests/realtikvtest/txntest/stale_read_test.go:1512]: Is the purpose to ensure the `firstTime` to be after the insertion? How about using `tidb_last_txn_info` to get the commit ts of the insertion, and wait until the current ts - the gap exceed the commit ts? I guess in this way we won't need to use up the 3s when the test environment is stable enough.
