### PR TITLE
executor: fix retChk = nil in index_merge_reader

### LINKED ISSUE #46005: tidb panic for "IndexMergeProcessWorker: runtime error: invalid memory address or nil pointer dereference"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

steps please see in :
[utf-go-clustered-index-panic.log](https://github.com/pingcap/tidb/files/12319665/utf-go-clustered-index-panic.log)

### 2. What did you expect to see? (Required)
no panic
### 3. What did you see instead (Required)
```
[2023/08/10 20:54:12.065 +00:00] [ERROR] [index_merge_reader.go:884] ["IndexMergeProcessWorker: runtime error: invalid memory address or nil pointer dereference"] [conn=2636120476]
[2023/08/10 20:54:12.065 +00:00] [ERROR] [misc.go:91] ["panic in the recoverable goroutine"] [r="\"invalid memory address or nil pointer dereference\""] ["stack trace"="[github.com/pingcap/tidb/util.WithRecovery.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/misc.go:93\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime](http://github.com/pingcap/tidb/util.WithRecovery.func1/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/misc.go:93/nruntime.gopanic/n/t/usr/local/go/src/runtime/panic.go:914/nruntime.panicmem/n/t/usr/local/go/src/runtime/panic.go:261/nruntime.sigpanic/n/t/usr/local/go/src/runtime)
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #46005

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]

File: executor/index_merge_reader.go [hunk 1]
```diff
@@ -665,7 +665,11 @@ func (w *partialTableWorker) getRetTpsForTableScan() []*types.FieldType {
 func (w *partialTableWorker) extractTaskHandles(ctx context.Context, chk *chunk.Chunk, handleCols plannercore.HandleCols) (
 	handles []kv.Handle, retChk *chunk.Chunk, err error) {
 	handles = make([]kv.Handle, 0, w.batchSize)
+	if len(w.byItems) != 0 {
+		retChk = chunk.NewChunkWithCapacity(w.getRetTpsForTableScan(), w.batchSize)
+	}
 	var memUsage int64
+	var i int
```
Comment (XuHuaiyu) [inline executor/index_merge_reader.go:672]: i -> chunkRowOffset ?

Comment (Defined2014) [reply executor/index_merge_reader.go]: Done.

**Review by XuHuaiyu — APPROVED** [review]
