### PR TITLE
ddl: fix rename index for expression indexes

### LINKED ISSUE #51431: rename index forgot to rename the virtual generated column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t(j json);
Query OK, 0 rows affected (0.78 sec)

mysql> alter table t add index idx1((cast(j as char(10) array)));
Query OK, 0 rows affected (3.24 sec)

mysql> alter table t rename index idx1 to idx2;
Query OK, 0 rows affected (0.73 sec)

mysql> alter table t add index idx1((cast(j as char(10) array)));
ERROR 1060 (42S21): Duplicate column name '_V$_idx1_0'

mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                         |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `j` json DEFAULT NULL,
  KEY `idx2` ((cast(`j` as char(10) array)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.20 sec)
```

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #51431

Problem Summary:
Rename the virtual generated column when rename idx.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

File: pkg/ddl/index.go [hunk 1]
```diff
@@ -2563,3 +2565,11 @@ func renameIndexes(tblInfo *model.TableInfo, from, to model.CIStr) {
 		}
 	}
 }
+
+func renameHiddenColumns(tblInfo *model.TableInfo, from, to model.CIStr) {
+	for _, col := range tblInfo.Columns {
+		if strings.Contains(col.Name.O, fmt.Sprintf("%s_%s", expressionIndexPrefix, from)) {
```
Comment (zimulala) [inline pkg/ddl/index.go:2571]: How about `abc_V$_idx1_0`? Do we need to update this check like `getChangingIndexOriginName`?

**Review by zimulala — COMMENTED** [review]
Do we need to update this PR's title? This PR like to fix rename index for expression indexes.

**Review by zimulala — APPROVED** [review]

File: pkg/ddl/index.go [hunk 2]
```diff
@@ -2563,3 +2565,12 @@ func renameIndexes(tblInfo *model.TableInfo, from, to model.CIStr) {
...
 }
+
+func renameHiddenColumns(tblInfo *model.TableInfo, from, to model.CIStr) {
+	for _, col := range tblInfo.Columns {
+		if getExpressionIndexOriginName(col) == from.O {
+			col.Name.L = strings.Replace(col.Name.L, from.L, to.L, 1)
+			col.Name.O = strings.Replace(col.Name.O, from.O, to.O, 1)
+		}
+	}
+}
```
Comment (tangenta) [inline pkg/ddl/index.go:2576]: Maybe use `Column.Hidden` to filter hidden columns, otherwise it may cause unexpected behavior if there is a column name contains only one char like `_`, `V` or `$`.

**Review by tangenta — APPROVED** [review]
