### PR TITLE
plan: support `?` in Order By / Group By / Limit Offset clauses

### LINKED ISSUE #8153: wrong behavior when enabling prepare-cache in stmt `order by ?`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
create table t1 (a int, b int);
insert into t1 (a,b) values (2,8),(1,9),(3,7);

# Will order by index
prepare stmt from "select * from t1 order by ?";
set @a=1;
execute stmt using @a;
set @a=2;
execute stmt using @a;
deallocate prepare stmt;
```

2. What did you expect to see?

The results are ordered by column.

3. What did you see instead?

Results are unordered.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master dd65caac3122a7b75617c5a065889469c4301f0b

### PR DESCRIPTION
**Pull request by dbjoa**
### What problem does this PR solve? 
Fix #8153 

### What is changed and how it works?
 * Modify ``parser.ByItem`` to support ``ast.ParamMarkerExpr``
 * The prepared statements having parameters in ``OrderByClause`` or ``GroupByClause`` aren't cached

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has persistent data change (i.e., ``parser``)

Side effects

 - No

Related changes

 - Need to update the ``parser`` repository (i.e., the parser PR [#27](https://github.com/pingcap/parser/pull/27))

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8206)

### CODE REVIEW

**Comment by zz-jason** [comment]
@dbjoa Would you file another PR to make this `order by` statement cacheable?

File: planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -943,10 +943,38 @@ func (er *expressionRewriter) isNullToExpression(v *ast.IsNullExpr) {
...
+		if isPos && pos > 0 && pos <= int64(er.schema.Len()) {
+			er.ctxStack = er.ctxStack[:stkLen-1]
+			er.ctxStack = append(er.ctxStack, er.schema.Columns[pos-1])
+			return
+		}
+		er.err = ErrUnknownColumn.GenWithStackByArgs(strconv.Itoa(int(pos)), clauseMsg[er.b.curClause])
+	}
+	if val, ok := v.N.(*driver.ParamMarkerExpr); ok {
+		if len(er.ctx.GetSessionVars().PreparedParams) == 0 {
+			return
```
[the remark this answers is not in the document]
Comment (dbjoa) [reply planner/core/expression_rewriter.go]: We don't need to handle the error message because the codes should handle the ``null`` parameters given without an error as done in MySQL. 

Here is the case:
https://github.com/pingcap/tidb/blob/48131040bbd592aaa10d66f8cee668c1c813e7f6/executor/prepared_test.go#L588-L590

**Comment by dbjoa** [comment]
@zz-jason Yes, I would.

**Comment by dbjoa** [comment]
@zz-jason How can we run the CI test (i.e., ``run-all-tests``) based on the parser [PR #20](https://github.com/pingcap/parser/pull/20) ?

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -1169,14 +1169,24 @@ func (g *gbyResolver) Leave(inNode ast.Node) (ast.Node, bool) {
...
+		var isPos bool
+		if val, ok := v.N.(*driver.ValueExpr); ok {
+			pos, isPos = val.GetValue().(int64)
+			if isPos && (pos < 1 || pos > int64(len(g.fields))) {
+				g.err = errors.Errorf("Unknown column '%d' in 'group statement'", pos)
+			}
+		}
+		if !isPos {
+			g.err = errors.Errorf("Unknown column '%+v' in 'group statement'", v.N.Text())
+		}
```
Comment (eurekaka) [inline planner/core/logical_plan_builder.go]: MySQL and TiDB now are consistent for raising no error in this case:
```
mysql> prepare stmt from 'select ?, sum(a) from t group by ?';
Query OK, 0 rows affected (0.00 sec)
Statement prepared
```
would this change break the consistency?

File: planner/core/expression_rewriter.go [hunk 3]
```diff
@@ -943,10 +943,38 @@ func (er *expressionRewriter) isNullToExpression(v *ast.IsNullExpr) {
...
+		}
+		if param, err := expression.GetParamExpression(er.ctx, val, er.useCache()); err == nil {
```
Comment (eurekaka) [inline planner/core/expression_rewriter.go]: `GetParamExpression` has already been called in `expressionRewriter::Leave` for `ParamMarkerExpr`? so there should be a `Constant` on `er.CtxStack` that we can pop out and use here, thus we don't need to call `GetParamExpression` again?
I did no experimental verification since this branch cannot compile on my laptop due to the parser change.

File: planner/core/expression_rewriter.go [hunk 4]
```diff
@@ -943,10 +943,38 @@ func (er *expressionRewriter) isNullToExpression(v *ast.IsNullExpr) {
...
+			if con, ok := param.(*expression.Constant); ok {
+				str, isNull, err := con.EvalString(er.ctx, chunk.Row{})
```
Comment (eurekaka) [inline planner/core/expression_rewriter.go]: Can we use `Constant::EvalInt` here?

Comment (dbjoa) [reply planner/core/expression_rewriter.go]: We can't. This is because``Constant::EvalInt`` does not return an error when trying to convert a non numeric string (e..g., ``"##"``). That is, for example, it returns ``0`` without an error when converting ``"##"``.

File: planner/core/expression_rewriter.go (hunk 3 above)
Comment (dbjoa) [reply planner/core/expression_rewriter.go]: Thank you for the detailed comment. The updated PR should use ``Constant`` on ``er.ctxStack``.

File: planner/core/logical_plan_builder.go (hunk 2 above)
Comment (dbjoa) [reply planner/core/logical_plan_builder.go]: Thank you for the error case. I'll come back after fixing the issue.

**Comment by tiancaiamao** [comment]
Hi, @dbjoa
https://github.com/pingcap/parser/pull/20 broke the CI
The root problem is that, update TiDB and parser should be together, we didn't do it well during the migration to Go module.

Here I add some instructions on how to update parser for TiDB:
https://github.com/pingcap/parser/pull/23

You can follow that.
Any suggestions are welcome, thanks.

**Comment by dbjoa** [comment]
@eurekaka 
Would you let me know the schema and queries of the failed CI tests?

**Comment by eurekaka** [comment]
@dbjoa the log indicates it is the newly added case that fails:
```
FAIL: prepared_test.go:571: testSuite.TestPreparedIssue8153

prepared_test.go:602:
    c.Assert(err.Error(), Equals, "[planner:1054]Unknown column '?' in 'order clause'")
... obtained string = "[planner:1054]Unknown column '3' in 'order clause'"
... expected string = "[planner:1054]Unknown column '?' in 'order clause'"
```

**Comment by dbjoa** [comment]
run-all-tests

File: planner/core/logical_plan_builder.go [hunk 5]
```diff
@@ -1560,13 +1572,27 @@ func (b *PlanBuilder) resolveGbyExprs(p LogicalPlan, gby *ast.GroupByClause, fie
 	}
 	for _, item := range gby.Items {
 		resolver.inExpr = false
-		retExpr, _ := item.Expr.Accept(resolver)
+		var retExpr ast.Node
+		inPrepare := (len(b.ctx.GetSessionVars().PreparedParams) == 0)
```
Comment (winoros) [inline planner/core/logical_plan_builder.go]: Actually `notInPrepare`?

File: planner/core/logical_plan_builder.go [hunk 6]
```diff
@@ -1560,13 +1572,27 @@ func (b *PlanBuilder) resolveGbyExprs(p LogicalPlan, gby *ast.GroupByClause, fie
...
+		if param, ok := item.Expr.(*driver.ParamMarkerExpr); ok && !inPrepare {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go]: Will there be one case that `!ok && inPrepare` or `ok && inPrepare` is true?

File: planner/core/logical_plan_builder.go (hunk 5 above)
Comment (dbjoa) [reply planner/core/logical_plan_builder.go]: Yes!

Comment (dbjoa) [reply planner/core/logical_plan_builder.go]: ``inPrepare`` should let us know whether or not the logical plan is built by ``PrepareExec.Next()``. However, the current impl. may not work correctly if a prepared statement has no parameters. The updated PR will address the issue.

File: planner/core/logical_plan_builder.go (hunk 6 above)
Comment (dbjoa) [reply planner/core/logical_plan_builder.go]: Thank you for your detailed comments. The condition should be fixed. The updated PR will address the issue.

File: planner/core/expression_rewriter.go [hunk 7]
```diff
@@ -941,10 +941,26 @@ func (er *expressionRewriter) isNullToExpression(v *ast.IsNullExpr) {
...
 
 func (er *expressionRewriter) positionToScalarFunc(v *ast.PositionExpr) {
-	if v.N > 0 && v.N <= er.schema.Len() {
-		er.ctxStack = append(er.ctxStack, er.schema.Columns[v.N-1])
+	pos := v.N
+	str := strconv.Itoa(pos)
+	stkLen := len(er.ctxStack)
+	if v.P != nil {
+		val := er.ctxStack[stkLen-1]
+		intNum, isNull, err := expression.GetIntFromConstant(er.ctx, val)
```
Comment (zz-jason) [inline planner/core/expression_rewriter.go]: how about to handle `err` immediately after this function call?
```go
if err != nil {
	// handle err
}
er.ctxStack = er.ctxStack[:stkLen-1]
if isNull {
	// handle NULL position
}
// update pos, str
```

File: planner/core/expression_rewriter.go [hunk 8]
```diff
@@ -941,10 +941,26 @@ func (er *expressionRewriter) isNullToExpression(v *ast.IsNullExpr) {
 }
 
 func (er *expressionRewriter) positionToScalarFunc(v *ast.PositionExpr) {
-	if v.N > 0 && v.N <= er.schema.Len() {
-		er.ctxStack = append(er.ctxStack, er.schema.Columns[v.N-1])
+	pos := v.N
+	str := strconv.Itoa(pos)
+	stkLen := len(er.ctxStack)
```
Comment (zz-jason) [inline planner/core/expression_rewriter.go]: unused variable?

File: planner/core/logical_plan_builder.go [hunk 9]
```diff
@@ -821,6 +821,21 @@ func (b *PlanBuilder) buildSort(p LogicalPlan, byItems []*ast.ByItem, aggMapper
...
 	exprs := make([]*ByItems, 0, len(byItems))
 	for _, item := range byItems {
+		switch x := item.Expr.(type) {
+		case *driver.ParamMarkerExpr:
+			if b.ctx.GetSessionVars().InPrepare {
+				continue
+			}
+			newItem, isNull, err := expression.ParamToByItemNode(b.ctx, x)
+			if err != nil {
+				err := errors.Errorf("Unknown column '%+v' in 'order clause'", "?")
```
Comment (zz-jason) [inline planner/core/logical_plan_builder.go]: use `ErrUnknownColumn.GenWithStackByArgs()`

File: planner/core/logical_plan_builder.go [hunk 10]
```diff
@@ -1559,14 +1574,37 @@ func (b *PlanBuilder) resolveGbyExprs(p LogicalPlan, gby *ast.GroupByClause, fie
...
+		var retExpr ast.Node
+		switch x := item.Expr.(type) {
+		case *driver.ParamMarkerExpr:
+			hasParam = true
+			if b.ctx.GetSessionVars().InPrepare {
+				continue
+			}
+			newItem, isNull, err := expression.ParamToByItemNode(b.ctx, x)
+			if err != nil {
+				err := errors.Errorf("Unknown column '%+v' in 'group statement'", "?")
```
Comment (zz-jason) [inline planner/core/logical_plan_builder.go]: ditto

File: expression/util.go [hunk 11]
```diff
@@ -526,3 +527,57 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
...
 }
+
+// ParamToByItemNode generate ByItem node from ParamMarkerExpr.
+func ParamToByItemNode(ctx sessionctx.Context, v *driver.ParamMarkerExpr) (*ast.ByItem, bool, error) {
+	value, err := GetParamExpression(ctx, v)
+	if err != nil {
+		return nil, true, errors.Trace(err)
+	}
+	str, isNull, err := GetStringFromConstant(ctx, value)
+	if err != nil {
```
Comment (zz-jason) [inline expression/util.go]:
```go
if err != nil || isNull {
	return "", true, errors.Trace(err)
}
```

File: expression/util.go [hunk 12]
```diff
@@ -526,3 +527,57 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
...
+		return nil, true, errors.Trace(err)
+	}
+	if isNull {
+		return nil, true, nil
+	}
+	pos, err := strconv.Atoi(str)
```
Comment (zz-jason) [inline expression/util.go]:
```go
if err != nil {
	// handle err
}
// construct new ByItem and return
```

File: expression/util.go [hunk 13]
```diff
@@ -526,3 +527,57 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
...
+
+// GetStringFromConstant gets a string value from the Constant expression.
+func GetStringFromConstant(ctx sessionctx.Context, value Expression) (string, bool, error) {
+	con, ok := value.(*Constant)
+	if !ok {
+		err := errors.Errorf("Not a Constant expression %+v", value)
+		return "", true, errors.Trace(err)
+	}
+	str, isNull, err := con.EvalString(ctx, chunk.Row{})
+	if err != nil {
```
Comment (zz-jason) [inline expression/util.go]: ditto

File: expression/util.go [hunk 14]
```diff
@@ -526,3 +527,57 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
...
+	if isNull {
+		return "", true, nil
+	}
+	return str, false, nil
+}
+
+// GetIntFromConstant gets an interger value from the Constant expression.
+func GetIntFromConstant(ctx sessionctx.Context, value Expression) (int, bool, error) {
+	str, isNull, err := GetStringFromConstant(ctx, value)
+	if err != nil {
```
Comment (zz-jason) [inline expression/util.go]: ditto

File: expression/util.go [hunk 15]
```diff
@@ -526,3 +527,57 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
...
 	return value, nil
 }
+
+// ParamToByItemNode generate ByItem node from ParamMarkerExpr.
+func ParamToByItemNode(ctx sessionctx.Context, v *driver.ParamMarkerExpr) (*ast.ByItem, bool, error) {
+	value, err := GetParamExpression(ctx, v)
+	if err != nil {
+		return nil, true, errors.Trace(err)
+	}
+	str, isNull, err := GetStringFromConstant(ctx, value)
```
Comment (zz-jason) [inline expression/util.go]: How about using `GetIntFromConstant()` directly? Seems the following code logic is the same with that function.

File: expression/simple_rewriter.go [hunk 16]
```diff
@@ -151,7 +151,7 @@ func (sr *simpleRewriter) Leave(originInNode ast.Node) (retNode ast.Node, ok boo
 		}
 	case *driver.ParamMarkerExpr:
 		var value Expression
-		value, sr.err = GetParamExpression(sr.ctx, v, sr.useCache())
+		value, sr.err = GetParamExpression(sr.ctx, v)
```
[the remark this answers is not in the document]
Comment (dbjoa) [reply expression/simple_rewriter.go]: Sure, the PR has changed the same function in ``planner/core/expression_rewriter.go`` too:

https://github.com/pingcap/tidb/blob/aa6eff14f8c1fcbbba8cbf729df51ec275d98b6c/planner/core/expression_rewriter.go#L759

File: planner/core/expression_rewriter.go (hunk 7 above)
Comment (dbjoa) [reply planner/core/expression_rewriter.go]: If we change the code as you mentioned, the error message setting code (i.e., ``er.err = ErrUnknownColumn.GenWithStackByArgs(str, clauseMsg[er.b.curClause])``) will be duplicated in the both places: (1) the return error checking (i.e., ``err != nil``) and (2) the range error checking of ``pos``.

Comment (zz-jason) [reply planner/core/expression_rewriter.go]: > the return error checking
do you mean this line: https://github.com/pingcap/tidb/pull/8206/files#diff-33ebff1614e7db77b69dd02c2eee26c2R960

Comment (dbjoa) [reply planner/core/expression_rewriter.go]: yes.

File: planner/core/expression_rewriter.go (hunk 8 above)
Comment (dbjoa) [reply planner/core/expression_rewriter.go]: The updated PR should relocate ``stkLen``.

File: planner/core/logical_plan_builder.go (hunk 9 above)
Comment (dbjoa) [reply planner/core/logical_plan_builder.go]: The updated PR should address the comment.

File: planner/core/logical_plan_builder.go (hunk 10 above)
Comment (dbjoa) [reply planner/core/logical_plan_builder.go]: The updated PR should address the comment.

File: expression/util.go (hunk 11 above)
Comment (dbjoa) [reply expression/util.go]: The updated PR should tiny up the codes.

File: expression/util.go (hunk 12 above)
Comment (dbjoa) [reply expression/util.go]: The updated PR should tiny up the codes.

File: expression/util.go (hunk 13 above)
Comment (dbjoa) [reply expression/util.go]: The updated PR should tiny up the codes.

File: expression/util.go (hunk 14 above)
Comment (dbjoa) [reply expression/util.go]: The updated PR should tiny up the codes.

File: expression/util.go (hunk 15 above)
Comment (dbjoa) [reply expression/util.go]: Thank you for the suggestions. The updated PR should tiny up the codes.

File: expression/util.go [hunk 17]
```diff
@@ -526,3 +527,44 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
...
+func ParamToByItemNode(ctx sessionctx.Context, v *driver.ParamMarkerExpr) (*ast.ByItem, bool, error) {
+	value, err := GetParamExpression(ctx, v)
+	if err != nil {
+		return nil, true, errors.Trace(err)
+	}
+	pos, isNull, err := GetIntFromConstant(ctx, value)
+	if err != nil || isNull {
+		return nil, true, errors.Trace(err)
+	}
+	byItem := &ast.ByItem{Expr: &ast.PositionExpr{N: pos, P: v}}
```
[the remark this answers is not in the document]
Comment (dbjoa) [reply expression/util.go]: Yes, we should because we don't cache the plan having the parameterized ``ORDER BY`` clause.

File: expression/util.go (hunk 14 above)
Comment (dbjoa) [reply expression/util.go]: Thank you for the correction. I've updated the PR.

File: expression/util.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (zz-jason) [reply expression/util.go]: I come up with another idea. How about don't calculate `N`, just construct a deferred function in `P`? Thus we don't need to modify this function when we support plan cache for these statements?

[the remark this answers is not in the document]
Comment (dbjoa) [reply expression/util.go]: How about to handle it as another PR?

[the remark this answers is not in the document]
Comment (dbjoa) [reply expression/util.go]: Unfortunately, we can't now. Sorry for the confusion. To produce the same error message like MySQL, we should know that a parameterized position is out of range. ``P`` indicates that a position is parameterized. Here are the test case:

https://github.com/pingcap/tidb/blob/fe31c7405df2df85fa9d9aba7037090379242341/executor/prepared_test.go#L728-L730

[the remark this answers is not in the document]
Comment (zz-jason) [reply expression/util.go]: If so, calculating `N` in here is not needed, because the calculated value is never used. Can we remove this calculation process? i.e. remove the function call of `GetParamExpression()` and `GetIntFromConstant()`.

File: planner/core/logical_plan_builder.go [hunk 18]
```diff
@@ -824,6 +824,21 @@ func (b *PlanBuilder) buildSort(p LogicalPlan, byItems []*ast.ByItem, aggMapper
 	sort := LogicalSort{}.Init(b.ctx)
 	exprs := make([]*ByItems, 0, len(byItems))
 	for _, item := range byItems {
+		switch x := item.Expr.(type) {
```
Comment (eurekaka) [inline planner/core/logical_plan_builder.go]: Hmm, I prefer not adding this special conversion at this place, this looks pretty ad-hoc.

IMHO, this conversion should be encapsulated as part of `expressionRewriter` logically. We can pass in a flag like `inByClause` to `expressionRewriter` here, or in `resolveGbyExprs`, then this flag would work as context information of expression rewriting just like other fields in `expressionRewriter`, so when we are traversing the AST tree and meeting a `ParamMarkerExpr` in `expressionRewriter`, we check this flag to decide whether we should return a normal `Constant` or apply the above depicted logic of this patch.

Also, by encapsulating this logic into `expressionRewriter`, we can avoid redundant code for different kinds of `BY ?` clauses, including the `PARTITION BY ?` of upcoming window function.

File: expression/util.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (dbjoa) [reply expression/util.go]: @eurekaka 
``P`` can be a ``ValueExpr`` or ``Constant`` expression because its type is ``ExprNode``.  ``UseCache`` only indicates that ``P`` can be deferred constant or not. That is, we can't decide that ``P`` is set to ``nil`` depending on ``UseCache``.

File: executor/prepared.go [hunk 19]
```diff
@@ -97,6 +97,10 @@ func NewPrepareExec(ctx sessionctx.Context, is infoschema.InfoSchema, sqlTxt str
 // Next implements the Executor Next interface.
 func (e *PrepareExec) Next(ctx context.Context, chk *chunk.Chunk) error {
 	vars := e.ctx.GetSessionVars()
+	vars.InPrepare = true
```
[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: It might be another clean-up issue. How about we treat it as another PR?

[the remark this answers is not in the document]
Comment (eurekaka) [reply executor/prepared.go]: It is up to your choice. I prefer this because the one line change can remove all `InPrepare` changes in this patch.

[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: @eurekaka I don't think so. Since the value of the parameter can be ``nil``, we couldn't know that we are in the in-prepare stage depending on the value.

[the remark this answers is not in the document]
Comment (eurekaka) [reply executor/prepared.go]: Why must we know that we are in the "in-prepare" stage as long as we set the parameters to null? why prepare should be special in this case?

**Comment by dbjoa** [comment]
> @zz-jason Would you please let me know the failed CI error cases?

I've fixed the CI errors. Please forget my ask.

File: executor/prepared.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: @eurekaka 
This is because ``plannercore.BuildLogicalPlan`` is called whenever ``prepare {stmt_id} from '{stmt}'`` statements are issued. Here, ``plannercore.BuildLogicalPlan`` executes ``{stmt}`` in the ``prepare`` context with no given parameter values. It is different to the case, ``execute {stmt_id}``.  Here, ``execute {stmt_id}`` can be issued with no given parameter values. The former should not care if the parameter values are given, but the latter should care. Thus, we should distinguish each case to handle each statement correctly.   

https://github.com/pingcap/tidb/blob/4bcdb6d8ee7906947008603d95c543cd978b1106/executor/prepared.go#L167

[the remark this answers is not in the document]
Comment (eurekaka) [reply executor/prepared.go]: > Here, plannercore.BuildLogicalPlan builds a logical plan for the {stmt} in the prepare context with no given parameter values.

All `ParamMarkerExpr` in `{stmt}` is filled with integer 0 before `BuildLogicalPlan`.
```
    // We try to build the real statement of preparedStmt.
    for i := range prepared.Params {
        prepared.Params[i].(*driver.ParamMarkerExpr).Datum = types.NewIntDatum(0)
    }
```

> The former should not care if the parameter values are given, but the latter should care.

They all do care in current implementation at least. `prepare` is not a special case for `BuildLogicalPlan`.

[the remark this answers is not in the document]
Comment (eurekaka) [reply executor/prepared.go]: > For the former case, we can set the default parameter value as nil (i.e.,prepared.Params[i].(*driver.ParamMarkerExpr).Datum.SetNull(). But it causes other side effects.

That's why I suggest setting default parameter value as empty string, because user variable is string type:
prepared.Params[i].(*driver.ParamMarkerExpr).Datum = **types.NewStringDatum("")**

[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: Got it! The updated PR should address the issue.

[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: @eurekaka 
Are the CI errors related with changing of the default parameter value?

[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: @eurekaka, Should we revert the latest change?

[the remark this answers is not in the document]
Comment (eurekaka) [reply executor/prepared.go]: It is related. You can revert the latest change then, I can find out why it fails using https://github.com/pingcap/tidb/pull/8535. Sorry for the misleading here.

[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: @eurekaka You're welcome.  I've reverted the latest changes.

[the remark this answers is not in the document]
Comment (dbjoa) [reply executor/prepared.go]: Thank you for the analysis!

File: expression/util.go [hunk 20]
```diff
@@ -511,7 +511,8 @@ func DatumToConstant(d types.Datum, tp byte) *Constant {
 }
 
 // GetParamExpression generate a getparam function expression.
-func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCache bool) (Expression, error) {
+func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr) (Expression, error) {
+	useCache := ctx.GetSessionVars().StmtCtx.UseCache
```
Comment (winoros) [inline expression/util.go]: useCache is always false since in `cacheable_checker.go` we set cacheable to false when there's ParamMarker in order by, group by and limit?

Comment (dbjoa) [reply expression/util.go]: Yes. Since ``expression.GetParamExpression()`` is used commonly, ``useCache`` must be checked for each statement:
https://github.com/pingcap/tidb/blob/497fa925756716a6937d767713cb86f3b6ef90fe/planner/core/expression_rewriter.go#L757-L763

Comment (winoros) [reply expression/util.go]: Ok, got it.

File: expression/util.go [hunk 21]
```diff
@@ -526,3 +527,55 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
...
+}
+
+// PosFromPositionExpr generates a position value from PositionExpr.
+func PosFromPositionExpr(ctx sessionctx.Context, v *ast.PositionExpr) (int, bool, error) {
+	if v.P == nil {
+		return v.N, false, nil
+	}
+	value, err := GetParamExpression(ctx, v.P.(*driver.ParamMarkerExpr))
+	if err != nil {
+		return 0, true, errors.Trace(err)
```
Comment (winoros) [inline expression/util.go]: Once it's traced, we don't need to trace it anymore.
So here we can just return err.

Comment (dbjoa) [reply expression/util.go]: Thank you for your detailed comments. The updated PR will address the issue.

File: expression/util.go [hunk 22]
```diff
@@ -526,3 +527,55 @@ func GetParamExpression(ctx sessionctx.Context, v *driver.ParamMarkerExpr, useCa
 	}
 	return value, nil
 }
+
+// ConvertToByItemExpr rewrites ByItem.ExprNode to a proper ExprNode.
+func ConvertToByItemExpr(n ast.Node) ast.Node {
```
[the remark this answers is not in the document]
Comment (dbjoa) [reply expression/util.go]: In order to do that, we must add a checking logic of ``driver.ParamMarkerExpr`` typed node before calling ``ConstructPositionExpr``.  Hence, IMHO, the current impl. might be simpler than your suggestions.

[the remark this answers is not in the document]
Comment (zz-jason) [reply expression/util.go]:
```
[jianzhang.zj:~/opt/gopath/src/github.com/pingcap/tidb] git:(cloud-pi/fix-the-issue-8153 ✔)
➜ ag -w ConvertToByItemExpr
planner/core/logical_plan_builder.go
827:            newNode := expression.ConvertToByItemExpr(inNode)
1207:           newNode := expression.ConvertToByItemExpr(inNode)

expression/util.go
531:// ConvertToByItemExpr rewrites ByItem.ExprNode to a proper ExprNode.
532:func ConvertToByItemExpr(n ast.Node) ast.Node {
```

These are all the appearance of `ConvertToByItemExpr`, and as you can see in the function caller, the input parameter is guaranteed to be `driver.ParamMarkerExpr`

[the remark this answers is not in the document]
Comment (dbjoa) [reply expression/util.go]: Got it!
