### PR TITLE
planner: add new logical rule for constant propagation | tidb-test=pr/2209

### LINKED ISSUE #15082: constant is not propagated into subquery.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t (a int, b int, c int, primary key(a, b));
insert t values (1, 1, 1), (2, 2, 2), (3, 3, 3);
create table s (a int, b int, c int, primary key(a, b));
insert s values (1, 1, 1), (2, 2, 2), (3, 3, 3);
explain select t.a, t.b, (select sum(c) from s where s.a = t.a) from t where t.a = 2;
```

2. What did you expect to see?
The explain result should be the same as
```
explain select t.a, t.b, (select sum(c) from s where s.a = 2) from t where t.a = 2;

+---------------------------+-------+-----------+------------------------------------------------------------------+
| id                        | count | task      | operator info                                                    |
+---------------------------+-------+-----------+------------------------------------------------------------------+
| Projection_41             | 0.00  | root      | test.t.a, test.t.b, 2->Column#20                                 |
| └─IndexReader_43          | 0.00  | root      | index:IndexRangeScan_42                                          |
|   └─IndexRangeScan_42     | 0.00  | cop[tikv] | table:t, index:a, b, range:[2,2], keep order:false, stats:pseudo |
+---------------------------+-------+-----------+------------------------------------------------------------------+
```

3. What did you see instead?
```
| StreamAgg_15                           | 1.00  | root      | group by:Column#26, Column#27, funcs:firstrow(Column#23)->test.t.a, funcs:firstrow(Column#24)->test.t.b, funcs:sum(Column#25)->Column#9 |
| └─Projection_56                        | 0.00  | root      | test.t.a, test.t.b, cast(test.s.c, decimal(65,0) BINARY)->Column#25, test.t.a, test.t.b                                                 |
|   └─IndexMergeJoin_51                  | 0.00  | root      | left outer join, inner:Projection_49, outer key:test.t.a, inner key:test.s.a                                                            |
|     ├─IndexReader_55(Build)            | 0.00  | root      | index:IndexRangeScan_54                                                                                                                 |
|     │ └─IndexRangeScan_54              | 0.00  | cop[tikv] | table:t, index:a, b, range:[2,2], keep order:true, stats:pseudo                                                                         |
|     └─Projection_49(Probe)             | 1.25  | root      | test.s.a, test.s.c                                                                                                                      |
|       └─IndexLookUp_48                 | 1.25  | root      |                                                                                                                                         |
|         ├─IndexRangeScan_46(Build)     | 1.25  | cop[tikv] | table:s, index:a, b, range: decided by [eq(test.s.a, test.t.a)], keep order:true, stats:pseudo                                          |
|         └─TableRowIDScan_47(Probe)     | 1.25  | cop[tikv] | table:s, keep order:false, stats:pseudo
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by elsa0520**
### What problem does this PR solve?

This new logical rule of constant propagation is meanly used for `subquery` in From List
For example: select * from t, (select * from s where s.id >1) tmp where t.id = s.id

Fixed #15082

Issue Number: close #15082

Problem Summary:

### What is changed and how it works?
 WIP

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/rule_constant_propagation.go [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+// It mainly used for the sub query in FromList and propagated the constant predicate
+// from sub query to outer query.
+// In the future, it will support propagate constant in WhereClause and SelectList.
+//
+// Example 1:
+// Query: select * from t, (select * from s where s.id>1) tmp where t.id=tmp.id
+// Optimized: select * from t, (select * from s where s.id>1) tmp where t.id=tmp.id and tmp.id>1
+//
+// MatchCondition:
+// 1. The tree pattern must satisfy function 'xxx'
```
Comment (qw4990) [inline planner/core/rule_constant_propagation.go:35]: What's 'xxx'

Comment (elsa0520) [reply planner/core/rule_constant_propagation.go]: Changed

File: planner/core/plan.go [hunk 2]
```diff
@@ -282,6 +282,12 @@ type LogicalPlan interface {
 	// predicateSimplification consolidates different predcicates on a column and its equivalence classes.
 	predicateSimplification(opt *logicalOptimizeOp) LogicalPlan
 
+	// constantPropagation generate new constant predicate according to column equivalence relation
+	constantPropagation(parentPlan LogicalPlan, currentChildIdx int, opt *logicalOptimizeOp) (newRoot LogicalPlan)
+
+	// recursiveGetConstantPredicates recursive find constant predicate, used for the constant propagation rule
+	recursiveFindAndPullUpConstantPredicates() []expression.Expression
```
Comment (qw4990) [inline planner/core/plan.go:289]: Since these 2 methods are only used for this rule, so how about implementing them as 2 pure statistics functions like `constantPropagation(currentPlan, parentPlan LogicalPlan, currentChildIdx int, opt *logicalOptimizeOp) (newRoot LogicalPlan)` on `rule_constant_propagation.go`? 
There are already too many methods attached on `LogicalPlan`, which makes it hard to maintain...

File: planner/core/rule_constant_propagation.go [hunk 3]
```diff
@@ -0,0 +1,284 @@
...
+			continue
+		}
+		clonePredicate := predicate.Clone()
+		ResolveExprAndReplace(clonePredicate, replace)
+		result = append(result, clonePredicate)
+	}
+	return result
+}
+
+// validComparePredicate checks if the predicate is an expression like [column '>'|'>='|'<'|'<='|'=' constant].
```
Comment (qw4990) [inline planner/core/rule_constant_propagation.go:227]: Should we support "IN" as well?

File: planner/core/rule_constant_propagation.go [hunk 4]
```diff
@@ -0,0 +1,284 @@
...
+                                             +-----------^--------------+
+                                                         |
+                                                         |
+                                                    +----+--------+
+                                                    | currentPlan |
+                                                    +-------------+
+*/
+// If the currentPlan at the top of query plan, return new root plan (selection)
+// Else return nil
+func addCandidateSelection(currentPlan LogicalPlan, currentChildIdx int, parentPlan LogicalPlan,
```
Comment (qw4990) [inline planner/core/rule_constant_propagation.go:268]: And then to let the `rule_predicate_push_down` push these new predicted down through the `join`?

Comment (elsa0520) [reply planner/core/rule_constant_propagation.go:268]: Yes

File: planner/core/rule_constant_propagation.go (hunk 3 above)
Comment (elsa0520) [reply planner/core/rule_constant_propagation.go:227]: IN I feel it is also possible. However, the customer does not use IN currently. I wonder if we can add it when a customer needs it.

File: planner/core/plan.go (hunk 2 above)
Comment (elsa0520) [reply planner/core/plan.go:289]: There is a lot of logic in the rule that needs to be recursively implemented layer by layer. 
Different logical plans will have different logic. I feel that abstracting it into an interface is more cohesive at the architectural level.
BTW, a base class can inherit multiple interfaces. For example, the interface of statistics, and the interface of different rules. But I don't know if golang can support it.

**Review by qw4990 — APPROVED** [review]

File: planner/core/rule_constant_propagation.go [hunk 5]
```diff
@@ -0,0 +1,284 @@
...
+	var getConstantPredicateFromRight bool
+	switch logicalJoin.JoinType {
+	case LeftOuterJoin:
+		getConstantPredicateFromLeft = true
+	case RightOuterJoin:
+		getConstantPredicateFromRight = true
+	case InnerJoin:
+		getConstantPredicateFromLeft = true
+		getConstantPredicateFromRight = true
+	default:
```
Comment (fixdb) [inline planner/core/rule_constant_propagation.go:156]: Can this rule apply on SemiJoin?

Comment (elsa0520) [reply planner/core/rule_constant_propagation.go:156]: Yes. But should we add it now, or wait for a little bit later when there is user requirement?

Comment (fixdb) [reply planner/core/rule_constant_propagation.go:156]: Hmm, we can add it later.

Comment (elsa0520) [reply planner/core/rule_constant_propagation.go:156]: OK

File: planner/core/testdata/rule_constant_propagation_suite_out.json [hunk 6]
```diff
@@ -0,0 +1,243 @@
...
+      },
+      {
+        "SQL": "explain select * from t, (select id, count(name) from s where s.id>1 group by id) tmp where t.id=tmp.id; -- can't, constant propagation can't through the aggregation node",
+        "Output": [
+          "Projection_11 3333.33 root  test.t.id, test.t.name, test.s.id, Column#7",
+          "└─Projection_12 3333.33 root  test.t.id, test.t.name, Column#7, test.s.id",
+          "  └─HashJoin_14 3333.33 root  inner join, equal:[eq(test.s.id, test.t.id)]",
+          "    ├─HashAgg_20(Build) 2666.67 root  group by:test.s.id, funcs:count(Column#8)->Column#7, funcs:firstrow(test.s.id)->test.s.id",
+          "    │ └─TableReader_21 2666.67 root  data:HashAgg_15",
+          "    │   └─HashAgg_15 2666.67 cop[tikv]  group by:test.s.id, funcs:count(test.s.name)->Column#8",
```
Comment (AilinKid) [inline planner/core/testdata/rule_constant_propagation_suite_out.json:169]: group by id should be work?  the condition can be throw out from group by items

File: planner/core/testdata/rule_constant_propagation_suite_out.json [hunk 7]
```diff
@@ -0,0 +1,243 @@
...
+          "    │     └─Selection_19 3333.33 cop[tikv]  gt(test.s.id, 1), not(isnull(test.s.id))",
+          "    │       └─TableFullScan_18 10000.00 cop[tikv] table:s keep order:false, stats:pseudo",
+          "    └─TableReader_27(Probe) 9990.00 root  data:Selection_26",
+          "      └─Selection_26 9990.00 cop[tikv]  not(isnull(test.t.id))",
+          "        └─TableFullScan_25 10000.00 cop[tikv] table:t keep order:false, stats:pseudo"
+        ]
+      },
+      {
+        "SQL": "explain select * from t, (select id from s where s.id>1 order by id limit 2) tmp where t.id=tmp.id; -- can't, constant propagation can't through the sort node",
+        "Output": [
```
Comment (AilinKid) [inline planner/core/testdata/rule_constant_propagation_suite_out.json:179]: sort shouldn't affect the selection condition be pulled up?

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

File: planner/core/logical_plan_builder.go [hunk 8]
```diff
@@ -523,6 +523,7 @@ func (b *PlanBuilder) buildResultSetNode(ctx context.Context, node ast.ResultSet
 		case *ast.SelectStmt:
 			ci := b.prepareCTECheckForSubQuery()
 			defer resetCTECheckForSubQuery(ci)
+			b.optFlag = b.optFlag | flagConstantPropagation
```
[the remark this answers is not in the document]
Comment (fixdb) [reply planner/core/logical_plan_builder.go:526]: We'd better restrict it to Filter or Join only, right?

[the remark this answers is not in the document]
Comment (elsa0520) [reply planner/core/logical_plan_builder.go:526]: We always do this if the query has subquery in From list. Isn’t putting it here?

File: planner/core/testdata/rule_constant_propagation_suite_out.json (hunk 6 above)
Comment (elsa0520) [reply planner/core/testdata/rule_constant_propagation_suite_out.json:169]: Yes. But this time I don't support it. Because more business scenarios do not need to through agg. However, I have already designed the interface. If we need it later, we can just implement an interface directly.

File: planner/core/testdata/rule_constant_propagation_suite_out.json (hunk 7 above)
Comment (elsa0520) [reply planner/core/testdata/rule_constant_propagation_suite_out.json:179]: Yes. But this time I don't support it. Because more business scenarios do not need to through agg. However, I have already designed the interface. If we need it later, we can just implement an interface directly.

File: planner/core/rule_constant_propagation.go [hunk 9]
```diff
@@ -0,0 +1,284 @@
...
+	}
+	if len(candidateConstantPredicates) == 0 {
+		return
+	}
+
+	// step2: add selection above of LogicalJoin
+	return addCandidateSelection(logicalJoin, currentChildIdx, parentPlan, candidateConstantPredicates, opt)
+}
+
+func (*baseLogicalPlan) recursiveFindAndPullUpConstantPredicates() []expression.Expression {
```
Comment (fixdb) [inline planner/core/rule_constant_propagation.go:174]: `pullUpConstantPredicates` is good enough.

**Review by fixdb — APPROVED** [review]
+1
