### PR TITLE
parser: decode the binary literal value in enum or set

### LINKED ISSUE #30740: index out of range when create gbk charset enum column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a enum('a', 0x91) charset gbk);
```

### 2. What did you expect to see? (Required)

`no panic`

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #30740

Problem Summary:

```sql
create table t(a enum('a', 0x91) charset gbk);
```
```consosle
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
```

Previously, the binary literal like `0x91` is not correctly decoded to the corresponding column charset. Thus a invalid utf-8 string value is passed to TiDB. It panic during `decodeRune` at line 299:

https://github.com/pingcap/tidb/blob/daf525a17eeecb2ad9fa8bd3198e20987d13204c/util/collate/collate.go#L290-L301

### What is changed and how it works?

Decode the binary string literal to column charset.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: ddl/integration_test.go [hunk 1]
```diff
@@ -59,3 +59,24 @@ func TestDefaultValueIsBinaryString(t *testing.T) {
...
+	store, clean := testkit.CreateMockStore(t)
+	defer clean()
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test;")
+	// The value 0x91 should not cause panic.
+	tk.MustExec("create table t(a enum('a', 0x91) charset gbk);")
+	tk.MustExec("insert into t values (1), (2);")                 // Use 1-base index to locate the value.
+	tk.MustQuery("select a from t;").Check(testkit.Rows("a", "")) // 0x91 is truncate.
+	tk.MustExec("drop table t;")
+	tk.MustGetErrMsg("create table t(a set('a', 0x91, '') charset gbk);",
```
Comment (Defined2014) [inline ddl/integration_test.go:76]: It's not same as MySQL. Although MySQL behaves strangely.
```mysql
mysql> create table t(a set('a', 0x91, '') charset gbk);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values (1), (2), (3);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from t;
+------+
| a    |
+------+
| a    |
|      |
| a,   |
+------+
3 rows in set (0.00 sec)
```

Comment (tangenta) [reply ddl/integration_test.go:76]: I believe this is a bug in MySQL because the result of `show create table` should success:

```sql
mysql> create table t (a set('a', 0x91, '') charset gbk);
Query OK, 0 rows affected (0.05 sec)

mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                     |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` set('a','','') CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> drop table t;
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE `t` (
    ->   `a` set('a','','') CHARACTER SET gbk COLLATE gbk_chinese_ci DEFAULT NULL
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ERROR 1291 (HY000): Column 'a' has duplicated value '' in SET
```

**Review by Defined2014 — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
LGTM
