### PR TITLE
external store: use separate ctx for GCS clients

### LINKED ISSUE #60155: Any GCS Storage operation authenticating using external account (workload identity federation) will fail with "context canceled"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Create a credentials JSON file with the following content:

```json
{
	"type":"external_account",
	"audience":"//iam.googleapis.com/projects/1234567890123/locations/global/workloadIdentityPools/my-pool/providers/my-provider",
	"subject_token_type":"urn:ietf:params:oauth:token-type:access_token",
	"credential_source":{"url":"http://127.0.0.1:12345/"}
}
```

2. Starts an HTTP server at `127.0.0.1:12345`

```sh
python3 -m http 12345
```

3. Start a tiup playground and run BR backup using that credentials file.

```sh
tiup playground nightly --tiflash 0 --without-monitor
bin/br backup db --db test -s 'gcs://dummy/prefix' --gcs.credentials-file ./1.json --log-file -
```

### 2. What did you expect to see? (Required)

The backup failed because the credentials is invalid:

```
Error: error occurred when checking backupmeta file: 
  Get "https://storage.googleapis.com/storage/v1/b/dummy/o/prefix%2Fbackupmeta?alt=json&prettyPrint=false&projection=full": 
    oauth2/google: status code 400: 
      {"error":"invalid_target","error_description":"The target service indicated by the \"audience\" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist."}
```

### 3. What did you see instead (Required)

The request got outright canceled

```
Error: error occurred when checking backupmeta file: 
  Get "https://storage.googleapis.com/storage/v1/b/dummy/o/prefix%2Fbackupmeta?alt=json&prettyPrint=false&projection=full": 
    oauth2/google/externalaccount: invalid response when retrieving subject token: 
      Get "http://127.0.0.1:12345/": 
        context canceled
```

The stack trace is useless.

```
[2025/03/19 01:56:48.658 +08:00] [ERROR] [backup.go:58] ["failed to backup"] [error="error occurred when checking backupmeta file: Get \"https://storage.googleapis.com/storage/v1/b/dummy/o/prefix%2Fbackupmeta?alt=json&prettyPrint=false&projection=full\": oauth2/google/externalaccount: invalid response when retrieving subject token: Get \"http://127.0.0.1:12345/\": context canceled"] [errorVerbose="Get \"https://storage.googleapis.com/storage/v1/b/dummy/o/prefix%2Fbackupmeta?alt=json&prettyPrint=false&projection=full\": oauth2/google/externalaccount: invalid response when retrieving subject token: Get \"http://127.0.0.1:12345/\": context canceled
github.com/pingcap/errors.AddStack
	/Users/pingcap/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178
github.com/pingcap/errors.Trace
	/Users/pingcap/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/juju_adaptor.go:15
github.com/pingcap/tidb/br/pkg/storage.(*GCSStorage).FileExists
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/pkg/storage/gcs.go:199
github.com/pingcap/tidb/br/pkg/backup.(*Client).SetStorageAndCheckNotInUse
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/pkg/backup/client.go:502
github.com/pingcap/tidb/br/pkg/task.RunBackup
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/pkg/task/backup.go:451
main.runBackupCommand
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/cmd/br/backup.go:57
main.newDBBackupCommand.func1
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/cmd/br/backup.go:164
github.com/spf13/cobra.(*Command).execute
	/Users/pingcap/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/pingcap/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	/Users/pingcap/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/cmd/br/main.go:36
runtime.main
	/usr/local/go1.23/src/runtime/proc.go:272
runtime.goexit
	/usr/local/go1.23/src/runtime/asm_arm64.s:1223
error occurred when checking backupmeta file"] [stack="main.runBackupCommand
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/cmd/br/backup.go:58
main.newDBBackupCommand.func1
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/cmd/br/backup.go:164
github.com/spf13/cobra.(*Command).execute
	/Users/pingcap/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/pingcap/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	/Users/pingcap/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	/Users/pingcap/workspace/bp-tidb-release-darwin-arm64-swnhn-build-binaries/source/tidb/br/cmd/br/main.go:36
runtime.main
	/usr/local/go1.23/src/runtime/proc.go:272"]
```

### 4. What is your TiDB version? (Required)

master, also v8.5.1

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #60155

Problem Summary:

### What changed and how does it work?

see original issue for more information

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

File: br/pkg/storage/gcs.go [hunk 1]
```diff
@@ -447,39 +449,66 @@ skipHandleCred:
...
+// Close.
 func (s *GCSStorage) Reset(ctx context.Context) error {
 	logutil.Logger(ctx).Info("resetting gcs storage")
 
-	for _, client := range s.clients {
-		_ = client.Close()
-	}
+	s.cancelAndCloseGCSClients()
+
+	clientCtx, clientCancel := context.WithCancel(context.Background())
```
Comment (D3Hunter) [inline br/pkg/storage/gcs.go:459]: use `ctx` as parent context?

Comment (lance6716) [reply br/pkg/storage/gcs.go:459]: as reference https://go.dev/blog/context-and-structs in the linked issue said, I don't want to let function argument `ctx` control the client's lifetime.

Comment (D3Hunter) [reply br/pkg/storage/gcs.go:459]: https://go.dev/blog/context-and-structs the advice is good, but practically, we have to store `ctx` inside sometimes, especially those structs encapsulates network related stuffs, a common scenario:
- in most cases, `Close` function from `io.Closer` doesn't accept parameters, but we need to close some network resources that need a `context`, if you don't store it, you have to pass a background or a ctx with timeline, while both might not close in a way we want: `we want the network resources closed for as long as it takes if the parent ctx is not cancelled`
- many thrid part librarys stores context inside struct, such as etcd client, it forces us to store one too

I think we have to separate two thing:
- store context inside struct
- make methods or APIs of the struct have the first param a `context`, we have kept this rule in many cases.

cc @kennytm

Comment (D3Hunter) [reply br/pkg/storage/gcs.go:459]: a quick search of GoLang source code, seems they don't honor their own rule
image

File: br/pkg/storage/gcs.go [hunk 2]
```diff
@@ -447,39 +449,66 @@ skipHandleCred:
...
-				return errors.Trace(err)
+				firstErr.CompareAndSwap(nil, err)
+				clientCancel()
+				return
 			}
 			client.SetRetry(storage.WithErrorFunc(shouldRetry), storage.WithPolicy(storage.RetryAlways))
 			s.clients[i] = client
-			return nil
 		})
 	}
```
Comment (D3Hunter) [inline br/pkg/storage/gcs.go:484]: maybe this one
```go
	s.clients = make([]*storage.Client, 0, gcsClientCnt)
	wg := util.WaitGroupWrapper{}
	cliCh := make(chan *storage.Client)
	wg.RunWithLog(func() {
		for range gcsClientCnt {
			select {
			case cli := <-cliCh:
				s.clients = append(s.clients, cli)
			case <-ctx.Done():
				clientCancel()
				return
			}
		}
	})
	firstErr := atomic.NewError(nil)
	for range gcsClientCnt {
		wg.RunWithLog(func() {
			client, err := storage.NewClient(clientCtx, s.clientOps...)
			if err != nil {
				firstErr.CompareAndSwap(nil, err)
				clientCancel()
				return
			}
			client.SetRetry(storage.WithErrorFunc(shouldRetry), storage.WithPolicy(storage.RetryAlways))
			select {
			case cliCh <- client:
			case <-clientCtx.Done():
			}
		})
	}
```

**Review by D3Hunter — APPROVED** [review]
rest lgtm

**Comment by D3Hunter** [comment]
/hold

feel free to unhold

File: br/pkg/storage/gcs.go (hunk 2 above)
Comment (lance6716) [reply br/pkg/storage/gcs.go:484]: @D3Hunter I didn't get your point. Do you want to avoid the ugly code? ⬇️

```
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-done:
		case <-ctx.Done():
			clientCancel()
		}
	}()
```

Comment (D3Hunter) [reply br/pkg/storage/gcs.go]: yes, the `done` channel is not needed, and I want the routine managed by waitGroup
