### PR TITLE
infoschema: make information_schema.columns copyable

### LINKED ISSUE #42030: The data of information_schema.columns can not be fully copied
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.19.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> create table cc like information_schema.columns;
Query OK, 0 rows affected (0.03 sec)

mysql> insert into cc select * from information_schema.columns;
ERROR 1406 (22001): Data Too Long, field len 30, data len 45
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
TiDB can be inserted the data correctly.
### 3. What did you see instead (Required)
Return the error. "Data Too Long, field len 30, data len 45"
### 4. What is your TiDB version? (Required)
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.19.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #42030

Problem Summary: see #42030.

### What is changed and how it works?

Change the data type length from `30` to `45`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by zimulala — APPROVED** [review]
LGTM

**Review by xhebox — APPROVED** [review]

File: executor/infoschema_reader_test.go [hunk 1]
```diff
@@ -869,6 +869,14 @@ func TestNullColumns(t *testing.T) {
 		Check(testkit.Rows("def test v_test type 1 <nil> YES binary 0 0 <nil> <nil> <nil> <nil> <nil> binary(0)   select,insert,update,references  "))
 }
 
+func TestColumnsCopyable(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("create table cc like information_schema.columns;")
+	tk.MustExec("insert into cc select * from information_schema.columns;")
```
Comment (hawkingrei) [inline executor/infoschema_reader_test.go:877]: This test case is too small. so the startup of this test case will take longer than this test. I suggest it can merge this test case into ```TestCreateTableWithLike```.

**Review by hawkingrei — APPROVED** [review]
