### PR TITLE
planner: fix privileges for `select for update` stmt

### LINKED ISSUE #60468: The permission check of `SELECT ... FOR UPDATE` is incompatible with MySQL
## Bug Report

The permission check of `SELECT ... FOR UPDATE` is incompatible with MySQL.

### 1. Minimal reproduce step

```sql
-- login with user 'root'
DROP DATABASE IF EXISTS test; 
CREATE DATABASE test;
USE test;
DROP TABLE IF EXISTS t;
CREATE TABLE t (x INT);
INSERT INTO t VALUES (100);

DROP USER IF EXISTS foo; 
CREATE USER foo;
GRANT SELECT ON *.* TO foo;


-- login with user 'foo'
USE test;
SELECT * FROM t FOR UPDATE;
```

### 2. What did you expect to see?
In MySQL:

```
ERROR 1142 (42000): 

SELECT with locking clause command denied to user 'foo'@'172.17.0.1' for table 't'
```

It is because that the `SELECT ... FOR UPDATE` statement in MySQL needs `UPDATE` or `DELETE` privilege on the table.

### 3. What did you see instead?
In TiDB: 

```
mysql> SELECT * FROM t FOR UPDATE;

+------+
| x    |
+------+
|  100 |
+------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version?

docker image `pingcap/tidb:nightly`:

```
Release Version: v9.0.0-beta.1.pre-533-g671534a
Edition: Community
Git Commit Hash: 671534a755e5ac3fbb5b515cc15f4d54142e6810
Git Branch: HEAD
UTC Build Time: 2025-04-09 14:12:27
GoVersion: go1.23.8
Race Enabled: false
Check Table Before Drop: false
Store: unistore
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #60468

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -3835,13 +3835,33 @@ func (b *PlanBuilder) buildSelect(ctx context.Context, sel *ast.SelectStmt) (p b
...
+		}
+		for _, tName := range tableList {
 			// CTE has no *model.HintedTable, we need to skip it.
 			tNameW := b.resolveCtx.GetTableName(tName)
 			if tNameW == nil {
 				continue
 			}
-			b.ctx.GetSessionVars().StmtCtx.LockTableIDs[tNameW.TableInfo.ID] = struct{}{}
+			if isExplicitSetTablesNames {
+				b.ctx.GetSessionVars().StmtCtx.LockTableIDs[tNameW.TableInfo.ID] = struct{}{}
```
Comment (lance6716) [inline pkg/planner/core/logical_plan_builder.go:3854]: Can you add comment to explain why we don't need to update `LockTableIDs` for implicit SELECT FOR UPDATE? I didn't understand this logic 😂

Comment (Defined2014) [reply pkg/planner/core/logical_plan_builder.go:3854]: It's for the stmt like `select * from t, t1 where t.a = t1.a for update of t` which only locks table `t` instead of all tables. I will add it into comments.

Comment (lance6716) [reply pkg/planner/core/logical_plan_builder.go:3856]: I didn't find where the locking of "(instead of) all tables" happens. 😂  It's deleted as the old line 3844

Comment (Defined2014) [reply pkg/planner/core/logical_plan_builder.go:3856]: If `LockTableIDs` map is empty, it will lock all records from all tables. Besides, it will only lock the metioned in `of` part.

**Review by hawkingrei — APPROVED** [review]
