### PR TITLE
planner: check view recursion when building source from view

### LINKED ISSUE #20368: Stack overflow with view recursion
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table a (a int);
create view b as select * from a;
create view c as select * from b;
drop table a;
rename table c to a;
select * from a;
```

### 2. What did you expect to see? (Required)

On MySQL 8.0:

```
ERROR 1462 (HY000): `test`.`a` contains view recursion
```

### 3. What did you see instead (Required)

<details><summary>The TiDB server crashed with stack overflow involving `(*PlanBuilder).BuildDataSourceFromView`</summary>

```
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc03a602488 stack=[0xc03a600000, 0xc05a600000]
fatal error: stack overflow

runtime stack:
runtime.throw(0x273f2ea, 0xe)
        c:/go/src/runtime/panic.go:1116 +0x79
runtime.newstack()
        c:/go/src/runtime/stack.go:1034 +0x6dc
runtime.morestack()
        c:/go/src/runtime/asm_amd64.s:449 +0x97

goroutine 5785 [running]:
github.com/pingcap/parser.yyParse(0x2cf6d40, 0xc01412fbe8, 0xc01412fba0, 0x13)
        $GOPATH/pkg/mod/github.com/pingcap/parser@v0.0.0-20200929032957-9678b2b7cefb/parser.go:9994 +0x789e9 fp=0xc03a602498 sp=0xc03a602490 pc=0xc2dc29
github.com/pingcap/parser.(*Parser).Parse(0xc01412fba0, 0xc0103d20f0, 0x25, 0x272d5d5, 0x7, 0x2737345, 0xb, 0xc03a6025c0, 0xc2ddd3, 0x27ef8aa, ...)
        $GOPATH/pkg/mod/github.com/pingcap/parser@v0.0.0-20200929032957-9678b2b7cefb/yy_parser.go:124 +0x182 fp=0xc03a602540 sp=0xc03a602498 pc=0xc2dfc2
github.com/pingcap/parser.(*Parser).ParseOneStmt(0xc01412fba0, 0xc0103d20f0, 0x25, 0x272d5d5, 0x7, 0x2737345, 0xb, 0x0, 0x0, 0x0, ...)
        $GOPATH/pkg/mod/github.com/pingcap/parser@v0.0.0-20200929032957-9678b2b7cefb/yy_parser.go:148 +0x95 fp=0xc03a6025d0 sp=0xc03a602540 pc=0xc2e515
github.com/pingcap/tidb/planner/core.(*PlanBuilder).BuildDataSourceFromView(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0xc02964df74, 0x4, 0xc02964df74, 0x4, 0xc0100c0600, 0x1, 0x2d39a00, ...)
        ./tidb/planner/core/logical_plan_builder.go:3243 +0x1a3 fp=0xc03a602808 sp=0xc03a6025d0 pc=0x15e56b3
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0xc0141a62c0, 0xc01bff0620, 0x0, 0x0, 0x0, 0x0)
        ./tidb/planner/core/logical_plan_builder.go:2908 +0x395 fp=0xc03a603120 sp=0xc03a602808 pc=0x15e0565
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0x2cf8cc0, 0xc01bff0600, 0x0, 0x0, 0x0, 0x0)
        ./tidb/planner/core/logical_plan_builder.go:279 +0x77f fp=0xc03a603320 sp=0xc03a603120 pc=0x15c398f
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildJoin(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0xc01415b000, 0x0, 0x0, 0x0, 0x0)
        ./tidb/planner/core/logical_plan_builder.go:604 +0xe8f fp=0xc03a603738 sp=0xc03a603320 pc=0x15c84ef
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0x2cf7f80, 0xc01415b000, 0x0, 0xc000032000, 0x25600a0, 0x24fa520)
        ./tidb/planner/core/logical_plan_builder.go:270 +0xa1f fp=0xc03a603938 sp=0xc03a603738 pc=0x15c3c2f
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0xc01410d860, 0x0, 0x0, 0x0, 0x0)
        ./tidb/planner/core/logical_plan_builder.go:2667 +0x214 fp=0xc03a603ca0 sp=0xc03a603938 pc=0x15de204
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0x2cf8780, 0xc01410d860, 0x2737345, 0xb, 0x2cffc00, 0xc01410d860)
        ./tidb/planner/core/planbuilder.go:593 +0xb77 fp=0xc03a603d30 sp=0xc03a603ca0 pc=0x161f0b7
github.com/pingcap/tidb/planner/core.(*PlanBuilder).BuildDataSourceFromView(0xc0101dab40, 0x2cf6980, 0xc0105878c0, 0xc02964df6c, 0x4, 0xc02964df6c, 0x4, 0xc00fe66780, 0x1, 0x2d39a00, ...)
        ./tidb/planner/core/logical_plan_builder.go:3249 +0x29a fp=0xc03a603f68 sp=0xc03a603d30 pc=0x15e57aa
...additional frames elided...
created by github.com/pingcap/tidb/server.(*Server).Run
        ./tidb/server/server.go:339 +0x710
```

</details>

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1340-g462a53f79
Edition: Community
Git Commit Hash: 462a53f79a0b995435b53e91a65e41555e1c10fb
Git Branch: master
UTC Build Time: 2020-10-09 07:41:39
GoVersion: go1.14.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by francis0407**
### What problem does this PR solve?

Issue Number: close #20368 

Problem Summary:

```
create table a (a int);
create view b as select * from a;
create view c as select * from b;
drop table a;
rename table c to a;
select * from a;
```
TiDB server crashed with stack overflow when building source from recursive view.

### What is changed and how it works?

What's Changed:

1. Add a stack to record the views which are on building. 
2. Replace the error `ErrNoSuchTable` with `ErrViewRecursive`

How it Works:
1. When we build source from view, we check if the view has already been on the build stack. If so, the view is defined recursively, and we return an `ErrViewRecursive` error.
2. If the view is not on the stack, we push it the stack, and pop it after building.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Breaking backward compatibility. This PR makes the error message compatible with MySQL.

### Release note 

- fix stack overflow when building recursive view.

### CODE REVIEW

File: executor/ddl_test.go [hunk 1]
```diff
@@ -273,11 +273,24 @@ func (s *testSuite6) TestCreateView(c *C) {
 	tk.MustExec("create definer='root'@'localhost' view v_nested as select * from test_v_nested")
 	tk.MustExec("create definer='root'@'localhost' view v_nested2 as select * from v_nested")
 	_, err = tk.Exec("create or replace definer='root'@'localhost' view v_nested as select * from v_nested2")
-	c.Assert(terror.ErrorEqual(err, plannercore.ErrNoSuchTable), IsTrue)
+	c.Assert(terror.ErrorEqual(err, plannercore.ErrViewRecursive), IsTrue)
```
Comment (XuHuaiyu) [inline executor/ddl_test.go:276]: It seems that this error message is not compatible with MySQL

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -3237,6 +3236,20 @@ func (b *PlanBuilder) buildMemTable(_ context.Context, dbName model.CIStr, table
 
 // BuildDataSourceFromView is used to build LogicalPlan from view
 func (b *PlanBuilder) BuildDataSourceFromView(ctx context.Context, dbName model.CIStr, tableInfo *model.TableInfo) (LogicalPlan, error) {
+	viewFullName := dbName.L + "." + tableInfo.Name.L
```
Comment (XuHuaiyu) [inline planner/core/logical_plan_builder.go:3239]: Can we extract these code block as in individual function like `checkRecrusiveView`?

**Comment by francis0407** [comment]
The test failed due to https://github.com/pingcap/tidb/issues/20596

File: executor/ddl_test.go (hunk 1 above)
Comment (francis0407) [reply executor/ddl_test.go]: fixed

File: planner/core/logical_plan_builder.go (hunk 2 above)
Comment (francis0407) [reply planner/core/logical_plan_builder.go]: addressed, PTAL

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @wshwsh12

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
