### PR TITLE
expression: fix some failed tests in local env

### LINKED ISSUE #50953: TestTidbParseTso failed in local envrionment
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run `TestTidbParseTso`

### 2. What did you expect to see? (Required)

pass

### 3. What did you see instead (Required)

```
    builtin_time_test.go:3050: 
        	Error Trace:	/Users/wangchao/Code/pingcap/tidb/pkg/expression/builtin_time_test.go:3050
        	Error:      	Not equal: 
        	            	expected: "2018-11-20 09:53:04.877000"
        	            	actual  : "2018-11-20 17:53:04.877000"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #50953

Problem Summary:

See issue. The failed test is caused by PR: #50530. In this PR, we unified the code to read the timezone info from `stmtctx.TimeZone`. In product environment, `sc.TimeZone` should be the same with `sessionVars.TimeZone`, but in some test cases, not all of them are set to a same value. So the some tests failed.

The reason why verify check success is because the remote machine is using UTC as the system timezone, but in local environment, it is not.

### What changed and how does it work?

1. Both set timezone to session variable and statement context in some tests.
2. For `createContext` in `expression.main_test.go`, we set the location to `UTC+11` to make the default time zone different with most CI and dev envrioments.
3. Add an assert in `location` method in `expression/context.go` to check these timezone info are all the same

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/builtin_time_test.go [hunk 1]
```diff
@@ -874,6 +874,7 @@ func TestNowAndUTCTimestamp(t *testing.T) {
 	// Test that "timestamp" and "time_zone" variable may affect the result of Now() builtin function.
 	err := ctx.GetSessionVars().SetSystemVar("time_zone", "+00:00")
 	require.NoError(t, err)
+	ctx.GetSessionVars().StmtCtx.SetTimeZone(ctx.GetSessionVars().TimeZone)
```
Comment (bb7133) [inline pkg/expression/builtin_time_test.go:877]: Is it redundant to `SetSystemVar()` and immediately `GetSystemVar()` for `"time_zone"`? I mean, why not just using `ctx.GetSessionVars().StmtCtx.SetTimeZone("+00:00")`?

Comment (lcwangchao) [reply pkg/expression/builtin_time_test.go:877]: Because "+00:00" is not a `*time.Location` format.

Comment (bb7133) [reply pkg/expression/builtin_time_test.go:877]: > Because "+00:00" is not a `*time.Location` format.

I don't think format is important... why so not just using `ctx.GetSessionVars().StmtCtx.SetTimeZone(time.UTC)`?

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
lgtm

File: pkg/table/column_test.go [hunk 2]
```diff
@@ -412,8 +419,9 @@ func TestGetDefaultValue(t *testing.T) {
 		{
 			&model.ColumnInfo{
 				FieldType:          tp3,
-				OriginDefaultValue: timestampValue.String(),
-				DefaultValue:       timestampValue.String(),
+				OriginDefaultValue: timestampValueUTC.String(),
+				DefaultValue:       timestampValueUTC.String(),
+				Version:            model.ColumnInfoVersion2,
```
Comment (lcwangchao) [inline pkg/table/column_test.go:424]: As the comments:

https://github.com/pingcap/tidb/blob/e528b6819e0969b415d5db746473b31f6edb5773/pkg/parser/model/model.go#L123-L129


We should set the version to 2 and use the UTC as the timezone for the timestamp field's default value

**Review by XuHuaiyu — APPROVED** [review]

**Review by zimulala — APPROVED** [review]
