### PR TITLE
executor: fix bug of read information_schema.columns

### LINKED ISSUE #15527: tables_test.go:testTableSuite.TestStmtSummaryTable failed
tables_test.go:testTableSuite.TestStmtSummaryTable

Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/28308/display/redirect

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?
fix #15527

```sql
[2020-07-13T06:10:50.139Z] ----------------------------------------------------------------------
[2020-07-13T06:10:50.139Z] FAIL: tables_test.go:901: testTableSuite.TestStmtSummaryTable
[2020-07-13T06:10:50.139Z] 
[2020-07-13T06:10:50.139Z] tables_test.go:906:
[2020-07-13T06:10:50.139Z]     tk.MustQuery("select column_comment from information_schema.columns " +
[2020-07-13T06:10:50.139Z]         "where table_name='STATEMENTS_SUMMARY' and column_name='STMT_TYPE'",
[2020-07-13T06:10:50.139Z]     ).Check(testkit.Rows("Statement type"))
[2020-07-13T06:10:50.139Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:62:
[2020-07-13T06:10:50.139Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
[2020-07-13T06:10:50.139Z] ... obtained string = "" +
[2020-07-13T06:10:50.139Z] ...     "[Statement type]\n" +
[2020-07-13T06:10:50.139Z] ...     "[Statement type]\n"
[2020-07-13T06:10:50.139Z] ... expected string = "[Statement type]\n"
[2020-07-13T06:10:50.139Z] ... sql:select column_comment from information_schema.columns where table_name='STATEMENTS_SUMMARY' and column_name='STMT_TYPE', args:[]
[2020-07-13T06:10:50.139Z] 
[2020-07-13T06:10:50.139Z] 
[2020-07-13T06:10:50.139Z] ----------------------------------------------------------------------
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
- No code

Side effects

- No

### Release note 

- No

### CODE REVIEW

File: executor/infoschema_reader.go [hunk 1]
```diff
@@ -539,13 +539,14 @@ func (e *hugeMemTableRetriever) setDataForColumns(ctx sessionctx.Context) error
...
 		schema := e.dbs[e.dbsIdx]
-		for ; e.tblIdx < len(schema.Tables); e.tblIdx++ {
+		for e.tblIdx < len(schema.Tables) {
 			table := schema.Tables[e.tblIdx]
 			if checker != nil && !checker.RequestVerification(ctx.GetSessionVars().ActiveRoles, schema.Name.L, table.Name.L, "", mysql.AllPrivMask) {
 				continue
 			}
 
 			e.dataForColumnsInTable(schema, table)
+			e.tblIdx++
```
Comment (crazycs520) [inline executor/infoschema_reader.go:549]: Should `e.tblIdx++` here, otherwise, in the next iterate round, the table in `e.tblIdx` will output again, make some duplicate rows.

**Comment by crazycs520** [comment]
No need cherry-pick.
