### PR TITLE
ddl: fix unexpected concurrency exceed quota during adding index

### LINKED ISSUE #47164: distributed add index failed, concurrency quota exceeded
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Create a table with more than 16 partitions.
Add index when `tidb_enable_dist_task = 1`

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

```
Test:       	TestAddIndexDistBasic
        	Messages:   	sql:alter table t add index idx(a);, [], error stack [ddl:8247]Ingest failed: concurrency quota exceeded
```

### 4. What is your TiDB version? (Required)

3ccd09e6

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #47164

Problem Summary:

`BackendCtx.Register` reocrd the concurrency. If it exceeds 16, an error will be reported.

### What is changed and how it works?

Reset this counter every time a subtask is finished.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/backfilling_read_index.go [hunk 1]
```diff
@@ -144,6 +144,10 @@ func (r *readIndexExecutor) RunSubtask(ctx context.Context, subtask *proto.Subta
 		return err
 	}
 
+	// TODO(tangenta): when we support running subtasks concurrently,
+	// we should ignore "concurrency quota exceeded" error if possible.
+	r.bc.ResetWorkers(r.job.ID, r.index.ID)
```
Comment (okJiang) [inline ddl/backfilling_read_index.go:149]: Do other executor need reset workers?

Comment (tangenta) [reply ddl/backfilling_read_index.go:149]: No, you can search `BackendCtx.Register`, there are only two usages:

1. `ingestBackfillScheduler.createWorker()`, we already reset the worker count when the import job complete.
2. `readIndexExecutor.RunSubtask()` here.

File: ddl/backfilling_read_index.go [hunk 2]
```diff
@@ -144,6 +144,10 @@ func (r *readIndexExecutor) RunSubtask(ctx context.Context, subtask *proto.Subta
 		return err
 	}
 
+	// TODO(tangenta): when we support running subtasks concurrently,
```
Comment (Benjamin2037) [inline ddl/backfilling_read_index.go:147]:
```suggestion
```

File: ddl/backfilling_read_index.go (hunk 1 above)
Comment (Benjamin2037) [inline ddl/backfilling_read_index.go:149]: will import into share this change？

**Review by okJiang — APPROVED** [review]
