### PR TITLE
session, com_stmt: store and restore the params for cursor fetch

### LINKED ISSUE #40094: create multiple cursor will cause panic
## Bug Report

ref: https://github.com/pingcap/tidb/issues/39148#issuecomment-1361100969

### 1. Minimal reproduce step (Required)

Run with `mysql-connector-java`:

```java
public class Example {
    public static void main(String[] args) throws SQLException, InterruptedException {
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:4000/test?useCursorFetch=true&useServerPrepStmts=true&useSSL=false", "root", "");

        conn.setAutoCommit(false); // must set

        conn.prepareStatement("drop table if exists t").execute();
        conn.prepareStatement("create table t (id int auto_increment primary key, id_2 int)").execute();
        conn.prepareStatement("insert into t values (1,1)").execute();
        conn.prepareStatement("insert into t values (2,2)").execute();

        // submit a statement with more arguments:
        PreparedStatement statement1 = conn.prepareStatement("" +
                "select * " +
                "from " +
                "t " +
                "where id = ? and id_2 = ?");
        statement1.setFetchSize(500);
        statement1.setInt(1, 1);
        statement1.setInt(2, 2);
        ResultSet rs_1 = statement1.executeQuery();

        // submit a statement with less arguments:
        PreparedStatement statement2 = conn.prepareStatement("" +
                "select * " +
                "from " +
                "t " +
                "where (id = ?)");
        statement2.setFetchSize(500);
        statement2.setInt(1, 1);
        ResultSet rs_2 = statement2.executeQuery();

        // fetch the result from the first argument
        while (rs_1.next()) {
            int result = rs_1.getInt(1);

            System.out.println(result);
        }

        conn.close();

    }
}
```

### 2. What did you expect to see? (Required)

Returns error, or print the result 1.

### 3. What did you see instead (Required)

tidb server panic.

### 4. What is your TiDB version? (Required)

Tested with master and 6.3

I'm afraid any existing version of TiDB has this problem.

### LINKED ISSUE #40322: Lost metric for AutoID allocation when auto_id_cache set to 1
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use `tiup playground` to start an cluster,  create a db and  a table:
```
mysql> create database sbtest;
Query OK, 0 rows affected (0.19 sec)

mysql> CREATE TABLE sbtest1 (
    ->   id int(11) NOT NULL AUTO_INCREMENT,
    ->   k int(11) NOT NULL DEFAULT '0',
    ->   c char(120) NOT NULL DEFAULT '',
    ->   pad char(60) NOT NULL DEFAULT '',
    ->   PRIMARY KEY (id) /*T![clustered_index] CLUSTERED */,
    ->   KEY k_1 (k)
    -> ) auto_id_cache = 1;
Query OK, 0 rows affected (0.15 sec)
```

use sysbench to do a test:
```
sysbench oltp_insert run --mysql-host=[127.0.0.1](http://127.0.0.1/) --mysql-port=4000 --mysql-user=root  --db-driver=mysql --mysql-db=sbtest --threads=50 --time=1200 --report-interval=10 --tables=1 --table-size=10000000 --mysql-password=
```

### 2. What did you expect to see? (Required)
Could find AutoID allocation metrics on dashboard.

### 3. What did you see instead (Required)

The metrics of AutoID is empty.

image

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:42:38
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)

```

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #40094 

Problem Summary:

TiDB cannot handle concurrently running statements. This PR stores and restores the params.

### What is changed and how it works?

Store and restore the prepared params in session

### Check List

Tests

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

The following JDBC codes run without panic:

```java
import java.sql.*;

public class Example {
    public static void main(String[] args) throws SQLException, InterruptedException {
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:4000/test?useCursorFetch=true&useServerPrepStmts=true&useSSL=false", "root", "");

        conn.setAutoCommit(false); // must set

        conn.prepareStatement("drop table if exists t").execute();
        conn.prepareStatement("create table t (id int auto_increment primary key, id_2 int)").execute();
        conn.prepareStatement("insert into t values (1,1)").execute();
        conn.prepareStatement("insert into t values (2,2)").execute();

        // submit a statement with more arguments:
        PreparedStatement statement1 = conn.prepareStatement("" +
                "select * " +
                "from " +
                "t " +
                "where id = ? and id_2 = ?");
        statement1.setFetchSize(500);
        statement1.setInt(1, 1);
        statement1.setInt(2, 2);
        ResultSet rs_1 = statement1.executeQuery();

        // submit a statement with less arguments:
        PreparedStatement statement2 = conn.prepareStatement("" +
                "select * " +
                "from " +
                "t " +
                "where (id = ?)");
        statement2.setFetchSize(500);
        statement2.setInt(1, 1);
        ResultSet rs_2 = statement2.executeQuery();

        // fetch the result from the first argument
        while (rs_1.next()) {
            int result = rs_1.getInt(1);

            System.out.println(result);
        }
        while (rs_2.next()) {
            int result = rs_2.getInt(1);

            System.out.println(result);
        }

        statement1.close();
        statement2.close();
        conn.commit();
        conn.close();

    }
}
```

### Release note

```release-note
Fix the issue that the prepared params are lost while executing another statement between EXECUTE and FETCH command.
```

### CODE REVIEW

File: server/driver_tidb.go [hunk 1]
```diff
@@ -155,6 +156,16 @@ func (ts *TiDBStatement) Reset() {
...
 
+// StoreStmtCtx implements PreparedStatement StoreStmtCtx method
+func (ts *TiDBStatement) StoreStmtCtx(stmtCtx *stmtctx.StatementContext) {
+	ts.stmtCtx = stmtCtx
+}
+
+// GetStmtCtx implements PreparedStatement GetStmtCtx method
+func (ts *TiDBStatement) GetStmtCtx() *stmtctx.StatementContext {
+	return ts.stmtCtx
+}
```
Comment (tiancaiamao) [inline server/driver_tidb.go:167]: So StmtCtx should be heap allocated...
Currently it's reused

See session/session.go:ExecuteStmt
executor/executor.go:ResetContextOfStmt
sessionctx/variable/session.go:InitStatementContext

@YangKeao

**Review by tiancaiamao — APPROVED** [review]
It makes the specific case better, though not a complete fix for the whole related problem.

**Review by bb7133 — APPROVED** [review]
LGTM
