### PR TITLE
executor: fix issue of explain for connection can't show the last query plan

### LINKED ISSUE #21235: explain for connection shows incorrect empty result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
select connection_id(); -- which is 2199023255563 in my case
drop table if exists t1;
create table t1 (id int unsigned not null auto_increment primary key, t text, index(t(8)));
insert into t1 (t) values (md5('a')),(md5('b'));
select * from t1 where t='0cc175b9c0f1b6a831c399e269772661' or t='92eb5ffee6ae2fec3ad71c777531578f';

explain for connection 2199023255563; -- the id of the current conection
```

### 2. What did you expect to see? (Required)

the execution plan of the current connection, not an empty result.

### 3. What did you see instead (Required)

```sql
TiDB(root@127.0.0.1:test) > explain for connection 2199023255563;
Query OK, 0 rows affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```sql
TiDB(root@127.0.0.1:test) > select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1606-gfbaab3ecb
Edition: Community
Git Commit Hash: fbaab3ecb60ad0524c22d3fb5532ebc00bc19d91
Git Branch: master
UTC Build Time: 2020-11-21 02:52:10
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

close #21235 

This bug is imported by https://github.com/pingcap/tidb/pull/19296.

As the title said, here is an example:

```sql
test> select connection_id();
+---------------------+
| connection_id()     |
+---------------------+
| 5235610488678645763 |
+---------------------+
1 row in set
Time: 0.011s
test> select * from t where a=1;
+---+---+
| a | b |
+---+---+
| 1 | 1 |
+---+---+
1 row in set
Time: 0.012s
test> explain for connection 5235610488678645763;
+-------------+---------+---------+------+---------------+----------------------------------------------------------------+---------------+--------+------+
| id          | estRows | actRows | task | access object | execution info                                                 | operator info | memory | disk |
+-------------+---------+---------+------+---------------+----------------------------------------------------------------+---------------+--------+------+
| Point_Get_1 | 1.00    | 1       | root | table:t       | time:884.141µs, loops:2, Get:{num_rpc:1, total_time:510.211µs} | handle:1      | N/A    | N/A  |
+-------------+---------+---------+------+---------------+----------------------------------------------------------------+---------------+--------+------+
```

### What is changed and how it works?

1. Keep saving last valid plan when the connection is sleeping.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- fix issue of explain for connection can't show the last query plan/

### CODE REVIEW

**Comment by crazycs520** [comment]
@SunRunAway @qw4990 PTAL

**Review by SunRunAway — COMMENTED** [review]
LGTM

File: server/server_test.go [hunk 1]
```diff
@@ -1058,6 +1058,28 @@ func (cli *testServerClient) runTestConcurrentUpdate(c *C) {
...
+		c.Assert(err, IsNil)
+		c.Assert(rows.Close(), IsNil)
+		dbt.mustQuery("select * from t where a=1")
+		rows = dbt.mustQuery("explain for connection " + strconv.Itoa(int(connID)))
+		c.Assert(rows.Next(), IsTrue)
+		row := make([]string, 9)
+		err = rows.Scan(&row[0], &row[1], &row[2], &row[3], &row[4], &row[5], &row[6], &row[7], &row[8])
+		c.Assert(err, IsNil)
+		c.Assert(strings.Join(row, ","), Matches, "Point_Get_1,1.00,1,root,table:t,time.*loop.*handle:1.*")
+		c.Assert(rows.Close(), IsNil)
```
Comment (AilinKid) [inline server/server_test.go:1079]: how to mock the `mysql.ComSleep` command in cli?

Comment (crazycs520) [reply server/server_test.go:1079]: When the query execution finishes, the connection will automatically call `SetProcessInfo` with the `mysql.ComSleep` command.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Review by AilinKid — APPROVED** [review]
LGTM
