### PR TITLE
ranger: fix incorrect enum range for xxx_ci collation

### LINKED ISSUE #24530: enum type query result is incorrect  while using `xxx_ci` collation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `PK_MULTI_COL2001STROBJSTROBJ` (  `COL2` enum('A','B','C','D') COLLATE utf8_general_ci NOT NULL,  `COL3` decimal(37,6) NOT NULL,  PRIMARY KEY (`COL2`,`COL3`) /*T![clustered_index] CLUSTERED */) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

insert into `PK_MULTI_COL2001STROBJSTROBJ` values ('A', 10), ('A', 11), ('B', 20);
select * from `PK_MULTI_COL2001STROBJSTROBJ` where col2 = 'a';
select * from `PK_MULTI_COL2001STROBJSTROBJ` where col2 = 'B';
```

### 2. What did you expect to see? (Required)
```sql
MySQL > select * from `PK_MULTI_COL2001STROBJSTROBJ` where col2 = 'a';
+------+-----------+
| COL2 | COL3      |
+------+-----------+
| A    | 10.000000 |
| A    | 11.000000 |
+------+-----------+
```
### 3. What did you see instead (Required)
```sql
MySQL r> select * from `PK_MULTI_COL2001STROBJSTROBJ` where col2 = 'a';
+------+------+
| COL2 | COL3 |
+------+------+

```

### 4. What is your TiDB version? (Required)
```sql
tidb_version() | Release Version: v4.0.0-beta.2-2791-g207ce344c-dirty
Edition: Community
Git Commit Hash: 207ce344cbb044ffb1b2681f1ba320a154979f6d
Git Branch: master
UTC Build Time: 2021-05-02 15:24:42
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close #24530

### What is changed and how it works?

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix incorrect enum range for xxx_ci collation

### CODE REVIEW

File: util/ranger/points.go [hunk 1]
```diff
@@ -449,19 +451,27 @@ func handleBoundCol(ft *types.FieldType, val types.Datum, op string) (types.Datu
...
 		res = append(res, &point{value: d, excl: false, start: true})
 		res = append(res, &point{value: d, excl: false, start: false})
 	}
 
-	tmpEnum := types.Enum{}
 	for i := range ft.Elems {
+		tmpEnum := types.Enum{}
 		tmpEnum.Name = ft.Elems[i]
 		tmpEnum.Value = uint64(i) + 1
 		d := types.NewMysqlEnumDatum(tmpEnum)
```
Comment (wshwsh12) [inline util/ranger/points.go:465]: Use d := types.NewCollateMysqlEnumDatum(tmpEnum, ft.Collate) directly is ok?

Comment (wshwsh12) [reply util/ranger/points.go:465]: The collation info has been saved in field type.. I think..

**Review by winoros — APPROVED** [review]
