### PR TITLE
expression: fix wrong behavior for IF(not_int, *, *)

### LINKED ISSUE #11601: wrong results when IF function along with float argument
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
SELECT  IF(0.1, 1, 2) FROM t1;
2. What did you expect to see?
+---------------+
| IF(0.1, 1, 2) |
+---------------+
|             1 |
+---------------+
1 row in set (0.00 sec)

3. What did you see instead?
+---------------+
| IF(0.1, 1, 2) |
+---------------+
|             2 |
+---------------+
1 row in set (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: None
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: None
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 

fix #11601 

### What is changed and how it works?
original issue was cause by using `types.ETInt` for arg0 rounding float to int. This PR using `wrapWithIsTrue` of `isTrueOrFalseFunctionClass` to handle different types correctly convert to int.

### Check List 

Tests 

 - Unit test
   - add cases whose args close to 0.0

Code changes

Side effects

Related changes

Release note

### CODE REVIEW

**Comment by lance6716** [comment]
How to correct `builtin_vec_control_generated.go`, I run `go generate` in `expression/generator` got 
```
can't load package: package .: build constraints exclude all Go files in /Users/lance/Projects/go/src/github.com/pingcap/tidb/expression/generator
```

**Comment by lance6716** [comment]
https://github.com/pingcap/tidb/pull/15016/files#diff-74ed6c0ecbced728d157e3f1adfd3c72R475 added "cast to real" op needs to change some testcases. Is that OK?

File: expression/builtin_control.go [hunk 1]
```diff
@@ -472,7 +472,13 @@ func (c *ifFunctionClass) getFunction(ctx sessionctx.Context, args []Expression)
 	}
 	retTp := InferType4ControlFuncs(args[1].GetType(), args[2].GetType())
 	evalTps := retTp.EvalType()
-	bf := newBaseBuiltinFuncWithTp(ctx, args, evalTps, types.ETInt, evalTps, evalTps)
+	var arg0Tp types.EvalType
+	if args[0].GetType().EvalType() == types.ETReal {
+		arg0Tp = types.ETReal
+	} else {
+		arg0Tp = types.ETInt
```
Comment (SunRunAway) [inline expression/builtin_control.go]: Perhaps we should consider other types of `args[0]`?

For example,
`SELECT IF(cast(0.1 as decimal(1, 1)), 1, 2);`

Comment (lance6716) [reply expression/builtin_control.go]: i'm going to cast every type to `ETReal` and use `EvalReal` / `VecEvalReal` since didn't find a good way to handle strings like "0.1". But I could not generate `builtin_control_vec_generated.go`, what's the right step to do this?

Comment (SunRunAway) [reply expression/builtin_control.go]: You can take a look at `isTrueOrFalseFunctionClass`.
If a function call is `if(XXX, YYY, YYY)`, one suggestion is to wrap a `builtinXXXIsTrueSig`  into `builtinIfYYYSig`.

```go
func (c *ifFunctionClass) getFunction() {
    firstParamFunc := isTrueOrFalseFunctionClass{}.getFunction(ctx, args[:1])
    return &builtinIfYYYSig{bf, firstParamFunc}
}
```

Then in `builtinIfYYYSig`, `firstParamFunc.evalInt` can be called to judgment the boolean result of XXX.

**Comment by SunRunAway** [comment]
A separated PR is OK, likewise.

**Comment by lance6716** [comment]
`caseWhenFunction` is more complicated, I prefer another PR.

**Comment by lance6716** [comment]
A very similar PR is #15309, please take a glance after reviewing this PR 😄
