### PR TITLE
planner: only users with SUPER or CONNECTION_ADMIN privilege can kill auto analyze

### LINKED ISSUE #33058: users without privilege can kill auto analyze
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Create user u1 and don't give u1 any privilege.
2. Login in as u1 in one connection.
3. Login in as root to trigger auto analyze in another connection.
4. Use u1 to execute `kill tidb 1` to kill auto analyze.

### 2. What did you expect to see? (Required)
u1 failed to kill auto analyze since it doesn't has SUPER privilege.

### 3. What did you see instead (Required)
u1 killed auto analyze successfully.

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
### What problem does this PR solve?

Issue Number: close #33058

Problem Summary:
Users without privilege can kill auto analyze.

### What is changed and how it works?
Only users with SUPER or CONNECTION_ADMIN privilege can kill auto analyze

### Check List

Tests 
- [ ] Unit test
- [x] Integration test(Since tests in tidb repo usually use mockSessionManager rather than the real Server, I put the testcase in https://github.com/pingcap/automated-tests/pull/999)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: planner/core/planbuilder.go [hunk 1]
```diff
@@ -3081,6 +3081,10 @@ func (b *PlanBuilder) buildSimple(ctx context.Context, node ast.StmtNode) (Plan,
 					b.visitInfo = appendDynamicVisitInfo(b.visitInfo, "CONNECTION_ADMIN", false, err)
 					b.visitInfo = appendVisitInfoIsRestrictedUser(b.visitInfo, b.ctx, &auth.UserIdentity{Username: pi.User, Hostname: pi.Host}, "RESTRICTED_CONNECTION_ADMIN")
 				}
+			} else if raw.ConnectionID == util2.GetAutoAnalyzeProcID() {
+				// Only the users with the SUPER privilege can kill auto analyze.
+				err := ErrSpecificAccessDenied.GenWithStackByArgs("SUPER")
+				b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SuperPriv, "", "", "", err)
```
Comment (morgo) [inline planner/core/planbuilder.go:3087]: Historically `PROCESS` privilege is required to kill connections that belong to other users. MySQL 8.0 changes this to requiring `CONNECTION_ADMIN`: https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_connection-admin

This helps avoid the problem that super is overloaded (it is used by too many features, which makes it less secure).

Comment (xuyifangreeneyes) [reply planner/core/planbuilder.go]: Fixed.

**Review by morgo — APPROVED** [review]

**Review by jackysp — APPROVED** [review]
LGTM
