### PR TITLE
lightning: fix epoch-not-match not retryable

### LINKED ISSUE #34172: Lightning parallel import fails due to "epoch not match"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
This issue is found in daily CI.
Launch 2 lightning instance to import data in parallel

### 2. What did you expect to see? (Required)
parallel Lighting should succeed.

### 3. What did you see instead (Required)
Parallel import fails due to "epoch not match"

```
[root@centos76_vm ~]# tail -n 30 /home/logs/lightning.log.2022-04-22T08.35.11Z
[2022/04/22 08:36:55.759 +00:00] [INFO] [localhelper.go:90] ["split and scatter region"] [minKey=7480000000000002FF9E5F728000000003FF3334C10000000000FA] [maxKey=7480000000000002FF9E5F72FF00000006FF40E7D10000000000FA] [retry=0]
[2022/04/22 08:36:55.759 +00:00] [INFO] [localhelper.go:109] ["paginate scan regions"] [count=1] [start=7480000000000002FF9E5F728000000003FF3334C10000000000FA] [end=7480000000000002FF9E5F72FF00000006FF40E7D10000000000FA]
[2022/04/22 08:36:55.759 +00:00] [INFO] [localhelper.go:117] ["paginate scan region finished"] [minKey=7480000000000002FF9E5F728000000003FF3334C10000000000FA] [maxKey=7480000000000002FF9E5F72FF00000006FF40E7D10000000000FA] [regions=1]
[2022/04/22 08:36:56.773 +00:00] [INFO] [split_client.go:480] ["checking whether need to scatter"] [store=3] [max-replica=3]
[2022/04/22 08:36:56.777 +00:00] [INFO] [localhelper.go:241] ["batch split region"] [region_id=3561] [keys=9] [firstKey="dIAAAAAAAAKeX3KAAAAAAzM0wQ=="] [end="dIAAAAAAAAKeX3L/AAAABkDn0Q=="]
[2022/04/22 08:36:56.779 +00:00] [INFO] [localhelper.go:320] ["waiting for scattering regions done"] [skipped_keys=0] [regions=9] [take=1.420409ms]
[2022/04/22 08:37:00.598 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3601,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72F600000003FF85C2830000000000FA,endKey=7480000000000002FF9E5F72FF00000006FF40E7D00000000000FA,UUID=80b874ee-6c92-467e-85c7-7dd1b591d446}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3601,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72F600000003FF85C2830000000000FA,endKey=7480000000000002FF9E5F72FF00000006FF40E7D00000000000FA,UUID=80b874ee-6c92-467e-85c7-7dd1b591d446}\"]"] [region="{ID=3601,startKey=7480000000000002FF9E5F72F600000003FF85C2830000000000FA,endKey=7480000000000002FF9E5F72FF00000006FF40E7D10000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3602 store_id:1 ,id:3603 store_id:4 ,id:3604 store_id:5 \"}"] [leader="id:3604 store_id:5 "]
[2022/04/22 08:37:01.374 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3581,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72A100000005FF7382B70000000000FA,endKey=7480000000000002FF9E5F72B200000005FF1F97D40000000000FA,UUID=c5c50c92-7d0f-4192-8501-e3f4fdd81566}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3581,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72A100000005FF7382B70000000000FA,endKey=7480000000000002FF9E5F72B200000005FF1F97D40000000000FA,UUID=c5c50c92-7d0f-4192-8501-e3f4fdd81566}\"]"] [region="{ID=3581,startKey=7480000000000002FF9E5F72A100000005FF7382B70000000000FA,endKey=7480000000000002FF9E5F72B200000005FF1F98710000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3582 store_id:1 ,id:3583 store_id:4 ,id:3584 store_id:5 \"}"] [leader="id:3584 store_id:5 "]
[2022/04/22 08:37:01.490 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3589,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72C300000004FFA694870000000000FA,endKey=7480000000000002FF9E5F72D400000004FF52ACE90000000000FA,UUID=860bd7a4-ad62-4893-a8ac-e6e9d8b087b1}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3589,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72C300000004FFA694870000000000FA,endKey=7480000000000002FF9E5F72D400000004FF52ACE90000000000FA,UUID=860bd7a4-ad62-4893-a8ac-e6e9d8b087b1}\"]"] [region="{ID=3589,startKey=7480000000000002FF9E5F72C300000004FFA694870000000000FA,endKey=7480000000000002FF9E5F72D400000004FF52AD690000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3590 store_id:1 ,id:3591 store_id:4 ,id:3592 store_id:5 \"}"] [leader="id:3591 store_id:4 "]
[2022/04/22 08:37:01.822 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3585,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72B200000005FF1F98710000000000FA,endKey=7480000000000002FF9E5F72C300000004FFA693720000000000FA,UUID=735cb2b3-28ff-4720-b060-13e30b3799c5}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3585,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72B200000005FF1F98710000000000FA,endKey=7480000000000002FF9E5F72C300000004FFA693720000000000FA,UUID=735cb2b3-28ff-4720-b060-13e30b3799c5}\"]"] [region="{ID=3585,startKey=7480000000000002FF9E5F72B200000005FF1F98710000000000FA,endKey=7480000000000002FF9E5F72C300000004FFA694870000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3586 store_id:1 ,id:3587 store_id:4 ,id:3588 store_id:5 \"}"] [leader="id:3586 store_id:1 "]
[2022/04/22 08:37:01.867 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3593,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72D400000004FF52AD690000000000FA,endKey=7480000000000002FF9E5F72E500000003FFD976130000000000FA,UUID=ef173e62-2a0c-4a58-b6dc-cf6d25d8aae5}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3593,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72D400000004FF52AD690000000000FA,endKey=7480000000000002FF9E5F72E500000003FFD976130000000000FA,UUID=ef173e62-2a0c-4a58-b6dc-cf6d25d8aae5}\"]"] [region="{ID=3593,startKey=7480000000000002FF9E5F72D400000004FF52AD690000000000FA,endKey=7480000000000002FF9E5F72E500000003FFD976160000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3594 store_id:1 ,id:3595 store_id:4 ,id:3596 store_id:5 \"}"] [leader="id:3594 store_id:1 "]
[2022/04/22 08:37:01.909 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3573,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F728000000003FF3334C10000000000FA,endKey=7480000000000002FF9E5F729000000005FFECCD130000000000FA,UUID=329cc488-0c78-4766-b84c-4870f28bff36}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3573,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F728000000003FF3334C10000000000FA,endKey=7480000000000002FF9E5F729000000005FFECCD130000000000FA,UUID=329cc488-0c78-4766-b84c-4870f28bff36}\"]"] [region="{ID=3573,startKey=7480000000000002FF9E5F728000000003FF3334C10000000000FA,endKey=7480000000000002FF9E5F729000000005FFECCD180000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3574 store_id:1 ,id:3575 store_id:4 ,id:3576 store_id:5 \"}"] [leader="id:3575 store_id:4 "]
[2022/04/22 08:37:02.012 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3597,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72E500000003FFD976160000000000FA,endKey=7480000000000002FF9E5F72F600000003FF85C25A0000000000FA,UUID=e2fc3196-71b6-4e4c-b01c-84636bcccec6}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3597,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F72E500000003FFD976160000000000FA,endKey=7480000000000002FF9E5F72F600000003FF85C25A0000000000FA,UUID=e2fc3196-71b6-4e4c-b01c-84636bcccec6}\"]"] [region="{ID=3597,startKey=7480000000000002FF9E5F72E500000003FFD976160000000000FA,endKey=7480000000000002FF9E5F72F600000003FF85C2830000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3598 store_id:1 ,id:3599 store_id:4 ,id:3600 store_id:5 \"}"] [leader="id:3599 store_id:4 "]
[2022/04/22 08:37:02.329 +00:00] [WARN] [local.go:1228] ["ingest failed noretry"] [error="epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [sstMetas="[\"{CF=default,endKeyExclusive=false,CRC32=0,length=0,regionID=3577,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F729000000005FFECCD180000000000FA,endKey=7480000000000002FF9E5F72A100000005FF73821B0000000000FA,UUID=ab629358-0cee-4ff6-9193-1702e128b4a9}\",\"{CF=write,endKeyExclusive=false,CRC32=0,length=0,regionID=3577,regionEpoch=\\\"conf_ver:5 version:442 \\\",startKey=7480000000000002FF9E5F729000000005FFECCD180000000000FA,endKey=7480000000000002FF9E5F72A100000005FF73821B0000000000FA,UUID=ab629358-0cee-4ff6-9193-1702e128b4a9}\"]"] [region="{ID=3577,startKey=7480000000000002FF9E5F729000000005FFECCD180000000000FA,endKey=7480000000000002FF9E5F72A100000005FF7382B70000000000FA,epoch=\"conf_ver:5 version:442 \",peers=\"id:3578 store_id:1 ,id:3579 store_id:4 ,id:3580 store_id:5 \"}"] [leader="id:3580 store_id:5 "]
[2022/04/22 08:37:02.329 +00:00] [ERROR] [local.go:1383] ["write and ingest engine failed"] [error="epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.329 +00:00] [ERROR] [backend.go:455] ["import failed"] [engineTag=`testdb`.`testtable`:0] [engineUUID=9d392ff0-44dc-5766-9c5c-c530d8bfcfb4] [retryCnt=0] [takeTime=6.570377275s] [error="epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.329 +00:00] [ERROR] [table_restore.go:934] ["import and cleanup engine failed"] [engineTag=`testdb`.`testtable`:0] [engineUUID=9d392ff0-44dc-5766-9c5c-c530d8bfcfb4] [takeTime=6.57602638s] [error="epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.329 +00:00] [ERROR] [table_restore.go:335] ["import whole table failed"] [table=`testdb`.`testtable`] [takeTime=45.894312222s] [error="epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.329 +00:00] [ERROR] [restore.go:1460] ["restore table failed"] [table=`testdb`.`testtable`] [takeTime=45.903736347s] [error="[Lightning:Restore:ErrRestoreTable]restore table `testdb`.`testtable` failed: epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.332 +00:00] [INFO] [meta_manager.go:876] ["unfinished task found"] [task_id=1650616511900997925] [status=schedule_set]
[2022/04/22 08:37:02.335 +00:00] [INFO] [meta_manager.go:910] ["check all task finish status"] [task_finished=true] [all_finished=false] [switch_back=false]
[2022/04/22 08:37:02.335 +00:00] [INFO] [restore.go:1235] ["cancel periodic actions"] [do=false]
[2022/04/22 08:37:02.335 +00:00] [INFO] [pd.go:448] ["exit pause scheduler and configs successful"]
[2022/04/22 08:37:02.335 +00:00] [ERROR] [restore.go:1425] ["restore all tables data failed"] [takeTime=45.921552143s] [error="[Lightning:Restore:ErrRestoreTable]restore table `testdb`.`testtable` failed: epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.335 +00:00] [INFO] [restore.go:1104] ["everything imported, stopping periodic actions"]
[2022/04/22 08:37:02.337 +00:00] [ERROR] [restore.go:435] ["run failed"] [step=4] [error="[Lightning:Restore:ErrRestoreTable]restore table `testdb`.`testtable` failed: epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.337 +00:00] [ERROR] [restore.go:446] ["the whole procedure failed"] [takeTime=47.173067615s] [error="[Lightning:Restore:ErrRestoreTable]restore table `testdb`.`testtable` failed: epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.337 +00:00] [ERROR] [restore.go:166] ["tables failed to be imported"] [count=1]
[2022/04/22 08:37:02.337 +00:00] [ERROR] [restore.go:168] [-] [table=`testdb`.`testtable`] [status=imported] [error="epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"]
[2022/04/22 08:37:02.397 +00:00] [ERROR] [main.go:103] ["tidb lightning encountered error stack info"] [error="[Lightning:Restore:ErrRestoreTable]restore table `testdb`.`testtable` failed: epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442"] [errorVerbose="[Lightning:Restore:ErrRestoreTable]restore table `testdb`.`testtable` failed: epoch not match: EpochNotMatch current epoch of region 3601 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3581 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3589 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3585 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3593 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3573 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3597 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442; epoch not match: EpochNotMatch current epoch of region 3577 is conf_ver: 5 version: 443, but you sent conf_ver: 5 version: 442\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tidb/br/pkg/lightning/common.NormalizeOrWrapErr\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/common/errors.go:207\ngithub.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables.func6\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/restore.go:1459\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"]

```

### 4. What is your TiDB version? (Required)
[release-version=v6.1.0-nightly] [git-hash=a798e78328d9c26eb47c006b787b1539783a28a8] [git-branch=heads/refs/tags/v6.1.0-nightly]

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #34172

Problem Summary:
- on import engine phase, we retry only on retryable error in #33794, and we list all retryable errors as a list(previously, we have a branch which take all unknown errors as retryable), but some errors from tikv is also retryable, we add them in this pr
- there maybe some errors which are retryable, but doesn't in the list, will refine when we find them.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/common/errors.go [hunk 1]
```diff
@@ -89,6 +89,15 @@ var (
 	ErrTableIsChecksuming = errors.Normalize("table '%s' is checksuming", errors.RFCCodeText("Lightning:Restore:ErrTableIsChecksuming"))
 )
 
+var (
```
Comment (gozssky) [inline br/pkg/lightning/common/errors.go:92]: Please merge with the last `var` block. Some errors have the same scope.

File: br/pkg/lightning/backend/local/local.go [hunk 2]
```diff
@@ -1789,14 +1789,18 @@ func (local *local) isIngestRetryable(
 		if newRegion != nil {
 			retryTy = retryWrite
 		}
-		return retryTy, newRegion, errors.Errorf("epoch not match: %s", errPb.GetMessage())
+		return retryTy, newRegion, errors.Annotate(common.ErrKVEpochNotMatch, errPb.GetMessage())
```
Comment (gozssky) [inline br/pkg/lightning/backend/local/local.go:1792]: It's better to use `common.ErrKVEpochNotMatch.GenWithStackXXX` instead of `errors.Anotate` for better readability. See https://github.com/pingcap/tidb/issues/32133 for more details.

File: br/pkg/lightning/backend/local/local.go [hunk 3]
```diff
@@ -1789,14 +1789,18 @@ func (local *local) isIngestRetryable(
...
 		// TODO: we should change 'Raft raft: proposal dropped' to a error type like 'NotLeader'
 		newRegion, err = getRegion()
 		if err != nil {
 			return retryNone, nil, errors.Trace(err)
 		}
 		return retryWrite, newRegion, errors.New(errPb.GetMessage())
+	case errPb.ServerIsBusy != nil:
+		return retryNone, nil, errors.Annotate(common.ErrKVServerIsBusy, errPb.GetMessage())
+	case errPb.RegionNotFound != nil:
+		return retryNone, nil, errors.Annotate(common.ErrKVRegionNotFound, errPb.GetMessage())
```
Comment (gozssky) [inline br/pkg/lightning/backend/local/local.go:1803]: Does it mean we don't retry for `ServerIsBusy` and `RegionNotFound`?

Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1803]: those two are copies of below
```golang
return retryNone, nil, errors.Errorf("non-retryable error: %s", resp.GetError().GetMessage())
```
just to give them a unique error code

File: br/pkg/lightning/backend/local/local.go (hunk 2 above)
Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1792]: `common.ErrKVEpochNotMatch.GenWithStackXXX` will clone the current error, then we cannot check it using the defined error in `IsRetryableError`.

File: br/pkg/lightning/backend/local/local.go (hunk 3 above)
Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1803]: > Does it mean we don't retry for `ServerIsBusy` and `RegionNotFound`?

will retry

File: br/pkg/lightning/backend/local/local.go (hunk 2 above)
Comment (gozssky) [reply br/pkg/lightning/backend/local/local.go:1792]: Use this function to check.
https://github.com/pingcap/tidb/blob/db07c2e0c80d745bdf3030826bdad7fd29da8f9e/br/pkg/errors/errors.go#L10

File: br/pkg/lightning/common/errors.go [hunk 4]
```diff
@@ -87,6 +87,13 @@ var (
 	ErrAllocTableRowIDs   = errors.Normalize("allocate table row id error", errors.RFCCodeText("Lightning:Restore:ErrAllocTableRowIDs"))
 	ErrInvalidMetaStatus  = errors.Normalize("invalid meta status: '%s'", errors.RFCCodeText("Lightning:Restore:ErrInvalidMetaStatus"))
 	ErrTableIsChecksuming = errors.Normalize("table '%s' is checksuming", errors.RFCCodeText("Lightning:Restore:ErrTableIsChecksuming"))
+
+	// TODO: BR has similar errors, but it contains BR inside, maybe merge them later
+
+	ErrKVEpochNotMatch  = errors.Normalize("epoch not match", errors.RFCCodeText("Lightning:KV:EpochNotMatch"))
+	ErrKVNotLeader      = errors.Normalize("not leader", errors.RFCCodeText("Lightning:KV:NotLeader"))
+	ErrKVServerIsBusy   = errors.Normalize("server is busy", errors.RFCCodeText("Lightning:KV:ServerIsBusy"))
+	ErrKVRegionNotFound = errors.Normalize("region not found", errors.RFCCodeText("Lightning:KV:RegionNotFound"))
```
Comment (gozssky) [inline br/pkg/lightning/common/errors.go:96]: Move these lines after `Lightning:KV:ErrCheckMultiIngest`.

File: br/pkg/lightning/common/retry_test.go [hunk 5]
```diff
@@ -25,6 +38,13 @@ func TestIsRetryableError(t *testing.T) {
 	require.False(t, IsRetryableError(&net.DNSError{}))
 	require.True(t, IsRetryableError(&net.DNSError{IsTimeout: true}))
 
+	// kv errors
+	require.True(t, IsRetryableError(ErrKVNotLeader))
+	require.True(t, IsRetryableError(ErrKVNotLeader.GenWithStack("test")))
+	require.True(t, IsRetryableError(ErrKVEpochNotMatch))
+	require.True(t, IsRetryableError(ErrKVServerIsBusy))
+	require.True(t, IsRetryableError(ErrKVRegionNotFound))
```
Comment (gozssky) [inline br/pkg/lightning/common/retry_test.go:46]: Add test cases for generated errors like `ErrKVRegionNotFound.GenWithStackXXX`.

**Review by gozssky — COMMENTED** [review]
Rest LGTM.

**Review by gozssky — APPROVED** [review]

**Comment by D3Hunter** [comment]
ping @lance6716 @dsdashun

**Review by dsdashun — APPROVED** [review]
LGTM

File: br/pkg/lightning/backend/local/local.go (hunk 3 above)
Comment (lance6716) [reply br/pkg/lightning/backend/local/local.go]: Seems inside this function there's retry level of "Write+Injest", "Injest", and in the caller there's "ScanRegion+Write+Injest". Maybe we can refine them later

**Review by lance6716 — APPROVED** [review]
