### PR TITLE
tablecodec: support decode common handle bytes to strings

### LINKED ISSUE #18946: clustered index: confusing error message
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
use test;
drop table if exists t;
set tidb_enable_clustered_index=1;
create table t(a char(20), b int, primary key(a));
insert into t values("aa", 1), ("bb", 1);
insert into t values("aa", 2);
```

### 2. What did you expect to see? (Required)
```
mysql> insert into t values("aa", 1), ("bb", 1);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> insert into t values("aa", 2);
ERROR 1062 (23000): Duplicate entry 'aa' for key 'PRIMARY'
```

### 3. What did you see instead (Required)
```
mysql> insert into t values("aa", 1), ("bb", 1);
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> insert into t values("aa", 2);
ERROR 1062 (23000): Duplicate entry '-9123904717448019968' for key 'PRIMARY'
```
### 4. Affected version (Required)

```
Release Version: v4.0.0-beta.2-872-g03003538d
Edition: Community
Git Commit Hash: 03003538d1d7a1762e02fc62365e4832f9df4dd7
Git Branch: master
UTC Build Time: 2020-08-03 03:22:57
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #18946

Problem Summary: 

The original implementation only supported int handle in the error message. When it encountered a common handle, a wrong value is decoded.

### What is changed and how it works?

What's Changed:

- Extract the index values decoding snippet to `DecodeValuesBytesToStrings`.
- Add a simple test `TestClusterIndexInsertOnDuplicateKey`.

How it Works: Omitted.

### Related changes

N/A

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

File: tablecodec/tablecodec.go [hunk 1]
```diff
@@ -127,13 +127,16 @@ func DecodeRecordKey(key kv.Key) (tableID int64, handle kv.Handle, err error) {
 	}
 
 	key = key[recordPrefixSepLength:]
-	var intHandle int64
-	key, intHandle, err = codec.DecodeInt(key)
+	if len(key) == 8 {
+		var intHandle int64
+		key, intHandle, err = codec.DecodeInt(key)
```
Comment (lzmhhh123) [inline tablecodec/tablecodec.go:132]: Not handle error here.
