### PR TITLE
planner: add batch_point_get access object

### LINKED ISSUE #32815: Explain for Batch_Point_Get does not include partition information in access object
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (a int primary key, b int, key (b)) partition by hash(a) (partition P0, partition p1, partition P2);
insert into t values (1,1),(2,2),(3,3);
analyze table t;
set @@tidb_partition_prune_mode = 'static';
explain select * from t where a IN (1,2);
explain select * from t where a = 1 OR a = 2;
set @@tidb_partition_prune_mode = 'dynamic';
explain select * from t where a IN (1,2);
explain select * from t where a = 1 OR a = 2;

```

### 2. What did you expect to see? (Required)
```
tidb> create table t (a int primary key, b int, key (b)) partition by hash(a) (partition P0, partition p1, partition P2);
Query OK, 0 rows affected (0,01 sec)

tidb> insert into t values (1,1),(2,2),(3,3);
Query OK, 3 rows affected (0,00 sec)
Records: 3  Duplicates: 0  Warnings: 0

tidb> analyze table t;
Query OK, 0 rows affected, 3 warnings (0,03 sec)

tidb> set @@tidb_partition_prune_mode = 'static';
Query OK, 0 rows affected (0,00 sec)

tidb> explain select * from t where a IN (1,2);
+-------------------+---------+------+---------------+--------------------------------------------+
| id                | estRows | task | access object | operator info                              |
+-------------------+---------+------+---------------+--------------------------------------------+
| Batch_Point_Get_1 | 2.00    | root | table:t partition:p1,P2      | handle:[1 2], keep order:false, desc:false |
+-------------------+---------+------+---------------+--------------------------------------------+
1 row in set (0,00 sec)

tidb> explain select * from t where a = 1 OR a = 2;
+--------------------------+---------+------+---------------+--------------------------------------------+
| id                       | estRows | task | access object | operator info                              |
+--------------------------+---------+------+---------------+--------------------------------------------+
| PartitionUnion_9         | 2.00    | root |               |                                            |
| ├─Batch_Point_Get_10     | 1.00    | root | table:t partition:p1      | handle:[1 2], keep order:false, desc:false |
| └─Batch_Point_Get_11     | 1.00    | root | table:t partition:P2      | handle:[1 2], keep order:false, desc:false |
+--------------------------+---------+------+---------------+--------------------------------------------+
3 rows in set (0,00 sec)

tidb> set @@tidb_partition_prune_mode = 'dynamic';
Query OK, 0 rows affected (0,00 sec)

tidb> explain select * from t where a IN (1,2);
+-------------------+---------+------+---------------+--------------------------------------------+
| id                | estRows | task | access object | operator info                              |
+-------------------+---------+------+---------------+--------------------------------------------+
| Batch_Point_Get_1 | 2.00    | root | table:t partition:p1,P2      | handle:[1 2], keep order:false, desc:false |
+-------------------+---------+------+---------------+--------------------------------------------+
1 row in set (0,00 sec)

tidb> explain select * from t where a = 1 OR a = 2;
+------------------------+---------+-----------+-----------------+----------------------------------------------------+
| id                     | estRows | task      | access object   | operator info                                      |
+------------------------+---------+-----------+-----------------+----------------------------------------------------+
| TableReader_6          | 2.00    | root      | partition:p1,P2 | data:TableRangeScan_5                              |
| └─TableRangeScan_5     | 2.00    | cop[tikv] | table:t         | range:[1,1], [2,2], keep order:false, stats:pseudo |
+------------------------+---------+-----------+-----------------+----------------------------------------------------+
2 rows in set (0,00 sec)

```
### 3. What did you see instead (Required)
```
tidb> create table t (a int primary key, b int, key (b)) partition by hash(a) (partition P0, partition p1, partition P2);
Query OK, 0 rows affected (0,01 sec)

tidb> insert into t values (1,1),(2,2),(3,3);
Query OK, 3 rows affected (0,00 sec)
Records: 3  Duplicates: 0  Warnings: 0

tidb> analyze table t;
Query OK, 0 rows affected, 3 warnings (0,03 sec)

tidb> set @@tidb_partition_prune_mode = 'static';
Query OK, 0 rows affected (0,00 sec)

tidb> explain select * from t where a IN (1,2);
+-------------------+---------+------+---------------+--------------------------------------------+
| id                | estRows | task | access object | operator info                              |
+-------------------+---------+------+---------------+--------------------------------------------+
| Batch_Point_Get_1 | 2.00    | root | table:t       | handle:[1 2], keep order:false, desc:false |
+-------------------+---------+------+---------------+--------------------------------------------+
1 row in set (0,00 sec)

tidb> explain select * from t where a = 1 OR a = 2;
+--------------------------+---------+------+---------------+--------------------------------------------+
| id                       | estRows | task | access object | operator info                              |
+--------------------------+---------+------+---------------+--------------------------------------------+
| PartitionUnion_9         | 2.00    | root |               |                                            |
| ├─Batch_Point_Get_10     | 1.00    | root | table:t       | handle:[1 2], keep order:false, desc:false |
| └─Batch_Point_Get_11     | 1.00    | root | table:t       | handle:[1 2], keep order:false, desc:false |
+--------------------------+---------+------+---------------+--------------------------------------------+
3 rows in set (0,00 sec)

tidb> set @@tidb_partition_prune_mode = 'dynamic';
Query OK, 0 rows affected (0,00 sec)

tidb> explain select * from t where a IN (1,2);
+-------------------+---------+------+---------------+--------------------------------------------+
| id                | estRows | task | access object | operator info                              |
+-------------------+---------+------+---------------+--------------------------------------------+
| Batch_Point_Get_1 | 2.00    | root | table:t       | handle:[1 2], keep order:false, desc:false |
+-------------------+---------+------+---------------+--------------------------------------------+
1 row in set (0,00 sec)

tidb> explain select * from t where a = 1 OR a = 2;
+------------------------+---------+-----------+-----------------+----------------------------------------------------+
| id                     | estRows | task      | access object   | operator info                                      |
+------------------------+---------+-----------+-----------------+----------------------------------------------------+
| TableReader_6          | 2.00    | root      | partition:p1,P2 | data:TableRangeScan_5                              |
| └─TableRangeScan_5     | 2.00    | cop[tikv] | table:t         | range:[1,1], [2,2], keep order:false, stats:pseudo |
+------------------------+---------+-----------+-----------------+----------------------------------------------------+
2 rows in set (0,00 sec)

```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.5.0-alpha-489-g493eb45c75
Edition: Community
Git Commit Hash: 493eb45c75a8f9687d5bf9185e5e167aadc81012
Git Branch: master
UTC Build Time: 2022-03-04 00:14:01
GoVersion: go1.17
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ymkzpx**
### What problem does this PR solve?

Issue Number: close #32815

Problem Summary:

above.

### Check List

- [x] Unit test

Side effects

- [x] Performance regression: Consumes more CPU
- [x] Performance regression: Consumes more Memory

### Release note

```release-note
None.
```

### CODE REVIEW

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -600,13 +618,38 @@ func newBatchPointGetPlan(
...
+				if isTableDual {
+					return nil
+				}
+				if tmpPartitionDefinition != nil {
+					partitionInfos = append(partitionInfos, tmpPartitionDefinition)
+				}
+			}
 		}
+
+		sort.SliceStable(partitionInfos, func(i, j int) bool {
```
Comment (bb7133) [inline planner/core/point_get_plan.go:633]: I don't think we need stable sort here, but it doesn't take much difference.

File: planner/core/point_get_plan.go [hunk 2]
```diff
@@ -600,13 +618,38 @@ func newBatchPointGetPlan(
...
+			return partitionInfos[i].ID < partitionInfos[j].ID
```
Comment (mjonss) [inline planner/core/point_get_plan.go:634]: So this would sort by partition-id (or "global table id"), which would not be as expected, it would most likely be in the order of creation, so if one have done some partition management, like `EXCHANGE PARTITION` the order could be non-expected. Like:
```
create table tt (a int);
create table tp (a int) partition by range (a) (partition p1 values less than (1000000), partition p2 values less than (2000000));
-- Now it would show the partitions in order p1,p2
alter table tp exchange partition p2 with table tt;
-- Now it would show the partitions in order p2,p1
```
I would expect the order to be the same as when listing the partitions shown in `SHOW CREATE TABLE`.

File: planner/core/point_get_plan_test.go [hunk 3]
```diff
@@ -662,45 +662,94 @@ func TestBatchPointGetPartition(t *testing.T) {
...
+
+	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
+	tk.MustExec("drop table if exists t0")
+	tk.MustExec("CREATE TABLE t0 (id int, name int) PARTITION BY LIST COLUMNS(id) (" +
+		"partition p0 values IN (1, 2), " +
+		"partition p1 values IN (3, 4), " +
+		"partition p3 values IN (5))")
+	tk.MustExec("insert into t0 values(1, 1), (2, 2), (3, 3), (4, 4)")
+	// can't hit BatchPointGet, because not hash partition.
+	tk.MustQuery("explain select * from t0 where id in (1, 3)")
```
Comment (mjonss) [inline planner/core/point_get_plan_test.go:730]: Why not also checking the output? Also maybe use `explain format='brief'`?

File: planner/core/point_get_plan_test.go [hunk 4]
```diff
@@ -662,45 +662,94 @@ func TestBatchPointGetPartition(t *testing.T) {
...
+
+	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
+	tk.MustExec("drop table if exists t1")
+	tk.MustExec("CREATE TABLE t1 (id int, name int) PARTITION BY LIST COLUMNS(id,name) (" +
+		"partition p0 values IN ((1, 1),(2, 2)), " +
+		"partition p1 values IN ((3, 3),(4, 4)), " +
+		"partition p3 values IN ((5, 5)))")
+	tk.MustExec("insert into t1 values(1, 1), (2, 2), (3, 3), (4, 4)")
+	// can't hit BatchPointGet, because not hash partition.
+	tk.MustQuery("explain select * from t1 where (id, name) in ((1, 1), (3, 3))")
```
Comment (mjonss) [inline planner/core/point_get_plan_test.go:740]: Same as above, please also check the output.

File: planner/core/point_get_plan_test.go [hunk 5]
```diff
@@ -662,45 +662,94 @@ func TestBatchPointGetPartition(t *testing.T) {
...
+
+	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
+	tk.MustExec("drop table if exists t2")
+	tk.MustExec("CREATE TABLE t2 (id int, name varchar(10)) PARTITION BY LIST COLUMNS(id,name) (" +
+		"partition p0 values IN ((1,'a'),(2,'b')), " +
+		"partition p1 values IN ((3,'c'),(4,'d')), " +
+		"partition p3 values IN ((5,'e')))")
+	tk.MustExec("insert into t2 values(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')")
+	// can't hit BatchPointGet, because not hash partition.
+	tk.MustQuery("explain select * from t2 where (id, name) in ((1, 'a'), (3, 'c'))")
```
Comment (mjonss) [inline planner/core/point_get_plan_test.go:750]: Same as above, please also check the output.

File: planner/core/point_get_plan_test.go [hunk 6]
```diff
@@ -662,45 +662,94 @@ func TestBatchPointGetPartition(t *testing.T) {
...
+		"Batch_Point_Get_1 3.00 root table:t, partition:p1,p2, index:b(b) keep order:false, desc:false"))
+
+	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
+	tk.MustExec("drop table if exists t0")
+	tk.MustExec("CREATE TABLE t0 (id int, name int) PARTITION BY LIST COLUMNS(id) (" +
+		"partition p0 values IN (1, 2), " +
+		"partition p1 values IN (3, 4), " +
+		"partition p3 values IN (5))")
+	tk.MustExec("insert into t0 values(1, 1), (2, 2), (3, 3), (4, 4)")
+	// can't hit BatchPointGet, because not hash partition.
```
Comment (mjonss) [inline planner/core/point_get_plan_test.go:729]: Sorry for my curiosity, but why is only hash partitioning supported by BatchPointGet?

**Review by mjonss — COMMENTED** [review]
LGTM, with a couple of questions and suggestions. I will approve after those are answered.

**Review by bb7133 — APPROVED** [review]
LGTM

File: planner/core/point_get_plan_test.go [hunk 7]
```diff
@@ -662,45 +662,100 @@ func TestBatchPointGetPartition(t *testing.T) {
...
+	tk.MustExec("create table t(a int, b int, UNIQUE KEY (b)) PARTITION BY HASH(b) PARTITIONS 4")
+	tk.MustExec("insert into t values(1, 1), (2, 2), (3, 3), (4, 4)")
+	tk.MustQuery("explain select * from t where b in (1, 2)").Check(testkit.Rows(
+		"Batch_Point_Get_1 2.00 root table:t, partition:p1,p2, index:b(b) keep order:false, desc:false"))
+	tk.MustQuery("explain select * from t where b in (1, 2, 1)").Check(testkit.Rows(
+		"Batch_Point_Get_1 3.00 root table:t, partition:p1,p2, index:b(b) keep order:false, desc:false"))
+
+	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
+	tk.MustExec("drop table if exists t0")
+	tk.MustExec("CREATE TABLE t0 (id int, name int) PARTITION BY LIST COLUMNS(id) (" +
```
Comment (mjonss) [inline planner/core/point_get_plan_test.go:724]: Should there not be a Primary Key (or Unique Key) here, to make it possible to use PointGet?

Also maybe just use `name_id` as second column name, since `name` indicates some character type?

File: planner/core/point_get_plan_test.go [hunk 8]
```diff
@@ -662,45 +662,100 @@ func TestBatchPointGetPartition(t *testing.T) {
...
+		"partition p3 values IN (5))")
+	tk.MustExec("insert into t0 values(1, 1), (2, 2), (3, 3), (4, 4)")
+	tk.MustQuery("explain format='brief' select * from t0 where id in (1, 3)").Check(testkit.Rows(
+		"TableReader 20.00 root partition:p0,p1 data:Selection]\n" +
+			"[└─Selection 20.00 cop[tikv]  in(test.t0.id, 1, 3)]\n" +
+			"[  └─TableFullScan 10000.00 cop[tikv] table:t0 keep order:false, stats:pseudo"))
+
+	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
+	tk.MustExec("drop table if exists t1")
+	tk.MustExec("CREATE TABLE t1 (id int, name int) PARTITION BY LIST COLUMNS(id,name) (" +
```
Comment (mjonss) [inline planner/core/point_get_plan_test.go:736]: Same here (name -> name_id + PK/Unique key)?

File: planner/core/point_get_plan_test.go [hunk 9]
```diff
@@ -662,45 +662,100 @@ func TestBatchPointGetPartition(t *testing.T) {
...
+		"partition p3 values IN ((5, 5)))")
+	tk.MustExec("insert into t1 values(1, 1), (2, 2), (3, 3), (4, 4)")
+	tk.MustQuery("explain format='brief' select * from t1 where (id, name) in ((1, 1), (3, 3))").Check(testkit.Rows("" +
+		"TableReader 0.02 root partition:p0,p1 data:Selection]\n" +
+		"[└─Selection 0.02 cop[tikv]  or(and(eq(test.t1.id, 1), eq(test.t1.name, 1)), and(eq(test.t1.id, 3), eq(test.t1.name, 3)))]\n" +
+		"[  └─TableFullScan 10000.00 cop[tikv] table:t1 keep order:false, stats:pseudo"))
+
+	tk.MustExec("set @@session.tidb_enable_list_partition = ON")
+	tk.MustExec("drop table if exists t2")
+	tk.MustExec("CREATE TABLE t2 (id int, name varchar(10)) PARTITION BY LIST COLUMNS(id,name) (" +
```
Comment (mjonss) [inline planner/core/point_get_plan_test.go:748]: PK/Unique key here for actually checking point get?

**Review by mjonss — APPROVED** [review]
LGTM, with some suggested improvements to the tests.
