### PR TITLE
sessionctx/variable: allow -1 value of executor's variables if rollback from master branch

### LINKED ISSUE #18910: tidb-server can not start when downgrading from master to v4.0.x
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://asktug.com/t/topic/36334

### 2. What did you expect to see? (Required)
The tidb-server can start successfully.

### 3. What did you see instead (Required)
tidb-server can not start

### 5. Root Cause Analysis
 https://github.com/pingcap/tidb/issues/15428

### LINKED ISSUE #20124: Rollback from master to v4.0.X got Variable 'tidb_index_lookup_concurrency' can't be set to the value of '-1'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. set up a v4.0.X cluster, start tidb-server
2. upgrade to master version(the future v5.0.0), restart tidb-server
3. rollback to the original v4.0.X version, restart tidb-server

### 2. What did you expect to see? (Required)

tidb-server starts normally.

### 3. What did you see instead (Required)

It gets the error message Variable 'tidb_index_lookup_concurrency' can't be set to the value of '-1' and fails to start.
```
[2020/09/21 18:36:57.305 +08:00] [FATAL] [terror.go:348] ["unexpected error"] [error="[variable:1231]Variable 'tidb_index_lookup_concurrency' can't be set to the value of '-1'"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200921023559-ba9921b82da3/terror/terror.go:348\nmain.createStoreAndDomain\n\t/Users/sunrunaway/Code/gopath/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/Users/sunrunaway/Code/gopath/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/Cellar/go/1.15.1/libexec/src/runtime/proc.go:204"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/Users/sunrunaway/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200921023559-ba9921b82da3/terror/terror.go:348\nmain.createStoreAndDomain\n\t/Users/sunrunaway/Code/gopath/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/Users/sunrunaway/Code/gopath/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/Cellar/go/1.15.1/libexec/src/runtime/proc.go:204"]
```

### 4. What is your TiDB version? (Required)

v4.0.6

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve?

Issue Number: close #20124, close #18910 

Problem Summary:

see #20124

### What is changed and how it works?

In https://github.com/pingcap/tidb/issues/15428, we incorporate several variables controlling executors' concurrency into `tidb_executor_concurrency` and make the old default to -1. 
After that change, when rollback from master to v4.0.X, v4.0.X cannot accept -1 of these variables.

Proposal: [xxx](url) 

What's Changed:

Allow -1 for these values.

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

### Release note 

- No release note

### CODE REVIEW

File: sessionctx/variable/varsutil.go [hunk 1]
```diff
@@ -591,10 +610,15 @@ func ValidateSetSystemVar(vars *SessionVars, name string, value string, scope Sc
...
 		TiDBQueryLogMaxLen,
 		TiDBEvolvePlanTaskMaxTime:
-		_, err := strconv.ParseInt(value, 10, 64)
+		v, err := strconv.ParseInt(value, 10, 64)
 		if err != nil {
 			return value, ErrWrongValueForVar.GenWithStackByArgs(name)
 		}
+		// These code are for compatibility of future v5.0.0 version.
+		// When rollback from master(future v5.0.0) version, the default value of these variables are -1
+		if v == -1 && name == TiDBProjectionConcurrency {
```
Comment (zz-jason) [inline sessionctx/variable/varsutil.go:619]: why only specially handle `TiDBProjectionConcurrency` in this condition?

Comment (SunRunAway) [reply sessionctx/variable/varsutil.go:619]: See https://github.com/pingcap/tidb/issues/15428#issuecomment-655595216

Comment (zz-jason) [reply sessionctx/variable/varsutil.go:619]: sorry, I still can not understand why not need to handle other variables.

Comment (zz-jason) [reply sessionctx/variable/varsutil.go:619]: how about moving this to `if v == -1`?

**Review by zz-jason — COMMENTED** [review]
LGTM

**Comment by SunRunAway** [comment]
@XuHuaiyu PTAL

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
