### PR TITLE
server: fix potential goroutine leak when kill connection

### LINKED ISSUE #13050: potential goroutine leak when kill connection
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

In https://github.com/pingcap/tidb/blob/7bfa896/server/conn.go#L1152-L1155, result set is not closed when the connection is released.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

7bfa896

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve? 

Fix #13050
### Check List 

Tests 

 - Unit test (covered by TestShutDown)

Code changes

 - None

Side effects

 - None

Related changes

 - None

Release note

 - None

### CODE REVIEW

File: server/conn.go [hunk 1]
```diff
@@ -1143,21 +1143,23 @@ func (cc *clientConn) handleLoadStats(ctx context.Context, loadStatsInfo *execut
...
 func (cc *clientConn) handleQuery(ctx context.Context, sql string) (err error) {
-	rs, err := cc.ctx.Execute(ctx, sql)
+	rss, err := cc.ctx.Execute(ctx, sql)
 	if err != nil {
 		metrics.ExecuteErrorCounter.WithLabelValues(metrics.ExecuteErrorToLabel(err)).Inc()
 		return err
 	}
 	status := atomic.LoadInt32(&cc.status)
-	if rs != nil && (status == connStatusShutdown || status == connStatusWaitShutdown) {
-		killConn(cc)
```
Comment (SunRunAway) [inline server/conn.go]: Here it need not to `killConn` again

**Comment by SunRunAway** [comment]
@lysu I've updated test, now it can be covered by `TestShutDown`.

**Comment by tiancaiamao** [comment]
LGTM
