### PR TITLE
stmtctx: remove OverflowAsWarning flag

### LINKED ISSUE #49137: `INSERT` should also ignore `ErrOverflow` if the `SQL_MODE` is not strict
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (d int);
set sql_mode='';
insert into t values (cast('123121241241242515521525215525' as unsigned));
```

### 2. What did you expect to see? (Required)

A warning

### 3. What did you see instead (Required)

ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '123121241241242515521525215525'

TiDB uses `OverflowAsWarning` to control the behavior. However, it's not set for `INSERT` statement.

### LINKED ISSUE #49143: `ErrOverflow` should be allowed in `DELETE` and `UPDATE` statement if the `sql_mode` is not strict
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set sql_mode='';
create table t (id char(255));
insert into t values ('12312323112312312331212331212312331221');
delete from t where cast(id as unsigned) = 1;
update t set id = '1' where cast(id as unsigned) = 1;
```

### 2. What did you expect to see? (Required)

A warning.

### 3. What did you see instead (Required)

```
mysql> delete from t where cast(id as unsigned) = 1;
ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '12312323112312312331212331212312331221'
mysql> update t set id = '1' where cast(id as unsigned) = 1;
ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '12312323112312312331212331212312331221'
```

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #49143, close #49137

Problem Summary:

The difference between `OverflowAsWarning` and `TruncatedAsWarning` doesn't actually exist. The existing difference are all incompatible with MySQL.

**I suggest to read https://github.com/pingcap/tidb/issues/49141#issuecomment-1838583457. It gives a clearer explanation on why this PR is right.**

### What changed and how does it work?

This PR removes `OverflowAsWarning` and handle them through `HandleError`. Actually `HandleError` and `HandleTruncate` are the same (and `HandleTruncate` will be removed in this or next week). As we provided `HandleErrorWithAlias`, it's more appropriate for this PR.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that in non-strict SQL_MODE, overflow error is not regarded as warning in UPDATE, DELETE and INSERT statement.
```

### CODE REVIEW

File: br/pkg/lightning/backend/kv/session.go [hunk 1]
```diff
@@ -315,7 +313,6 @@ func NewSession(options *encode.SessionOptions, logger log.Logger) *Session {
 		}
 	}
 	vars.StmtCtx.SetTimeZone(vars.Location())
-	vars.StmtCtx.SetTypeFlags(types.StrictFlags)
```
Comment (YangKeao) [inline br/pkg/lightning/backend/kv/session.go:318]: This line is introduced in https://github.com/pingcap/tidb/pull/47842. I think it's a bug, right? @lcwangchao Please confirm.

**Review by lance6716 — COMMENTED** [review]
/approve

for lightning part I'll check the integration test results

File: pkg/ddl/backfilling_scheduler.go [hunk 2]
```diff
@@ -196,7 +195,6 @@ func restoreSessCtx(sessCtx sessionctx.Context) func(sessCtx sessionctx.Context)
 		timezone = &tz
 	}
 	badNullAsWarn := sv.StmtCtx.BadNullAsWarning
-	overflowAsWarn := sv.StmtCtx.OverflowAsWarning
```
Comment (zimulala) [inline pkg/ddl/backfilling_scheduler.go:199]: Here we remove `OverflowAsWarning`, do we need to add `WithTruncateAsWarning`?

Comment (YangKeao) [reply pkg/ddl/backfilling_scheduler.go:199]: `WithTruncateAsWarning` is part of `typeFlags`. Here we restored the `typeFlags`, so it's fine to just remove `OverflowAsWarning`.

File: br/pkg/lightning/backend/kv/session.go (hunk 1 above)
Comment (lcwangchao) [reply br/pkg/lightning/backend/kv/session.go:318]: Seems to be a mistake, but introduced in previous PR: #47543 . In #47543 it overrides the type context settings before it...

**Review by tiancaiamao — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]
lgtm

**Review by windtalker — APPROVED** [review]
LGTM

**Review by zimulala — APPROVED** [review]
