### PR TITLE
planner: fix index merge handle columns

### LINKED ISSUE #65791: Can't find _tidb_rowid in schema Column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[plan_replayer.zip](https://github.com/user-attachments/files/24838010/plan_replayer.zip)

```
SELECT (1) AS `cnt`,
        (1) AS `sum1`,
        `t3`.`d0` AS `g1`
FROM ((`t0`
JOIN `t2`
    ON (`t0`.`k1`=`t2`.`k1`))
JOIN `t1 `
    ON (`t0`.`k0`=`t1`.`k0`))
JOIN `t3`
    ON (`t0`.`k2`=`t3`.`k2`)
WHERE ((`t0`.`k0` IN (65))
        OR (`t0`.`k2` IN (_UTF8MB4'2024-01-25')))
```
### 2. What did you expect to see? (Required)

fail to run 

```
(1105, "Can't find column shiro_fuzz_r1.t0._tidb_rowid in schema Column: [shiro_fuzz_r1.t0.k0,shiro_fuzz_r1.t0.k1,shiro_fuzz_r1.t0.k2,shiro_fuzz_r1.t0.id] PKOrUK: [] NullableUK: []")
```
### 3. What did you see instead (Required)

success、

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65791 

Problem Summary:

Fix a planner error where IndexMerge on PK handle tables could reference _tidb_rowid, causing schema resolve failure.

### What changed and how does it work?

- Use PK handle column (or common handle) instead of _tidb_rowid when building handle columns for IndexMerge double-read paths.
- Add a regression test reproducing the error without plan replayer and validating the query result.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix IndexMerge on PK handle tables to avoid resolving `_tidb_rowid` in schema.
```

## Release Notes

* **Bug Fixes**
  * Resolved an issue with index merge query optimization that incorrectly handled column selection for tables with clustered primary keys and common handles.

* **Tests**
  * Added regression test for index merge queries with OR predicates on clustered tables.

* **Documentation**
  * Updated planner documentation with notes on index merge handle column selection improvements.

### CODE REVIEW

File: pkg/planner/core/operator/physicalop/physical_index_scan.go [hunk 1]
```diff
@@ -404,16 +404,38 @@ func (p *PhysicalIndexScan) InitSchema(idxExprCols []*expression.Column, isDoubl
...
-					UniqueID: p.SCtx().GetSessionVars().AllocPlanColumnID(),
-					OrigName: model.ExtraHandleName.O,
-				})
+				// Prefer PK handle when available to avoid introducing ExtraHandleID (_tidb_rowid).
+				var handleCol *expression.Column
+				if p.Table.PKIsHandle {
+					handleCol = p.PkIsHandleCol
+					if handleCol == nil {
+						if pkInfo := p.Table.GetPkColInfo(); pkInfo != nil {
+							handleCol = expression.ColInfo2Col(p.DataSourceSchema.Columns, pkInfo)
```
Comment (AilinKid) [inline pkg/planner/core/operator/physicalop/physical_index_scan.go]: // dataSourceSchema is the original schema of DataSource. The schema of index scan in KV and index reader in TiDB
	// will be different. The schema of index scan will decode all columns of index but the TiDB only need some of them.
	DataSourceSchema *expression.Schema `plan-cache-clone:"shallow"`

this schema is the original one, shouldn't be pruned, which means id column should be found here, can you find where prune the id in DataSourceSchema?

Comment (hawkingrei) [reply pkg/planner/core/operator/physicalop/physical_index_scan.go]: OK, I have refactored the code.

File: pkg/planner/core/operator/physicalop/physical_index_scan.go [hunk 2]
```diff
@@ -385,9 +385,17 @@ func (p *PhysicalIndexScan) InitSchema(idxExprCols []*expression.Column, isDoubl
...
 			if (mysql.HasPriKeyFlag(col.GetFlag()) && p.Table.PKIsHandle) || col.ID == model.ExtraHandleID {
-				indexCols = append(indexCols, p.DataSourceSchema.Columns[i])
+				handleCol := expression.ColInfo2Col(p.DataSourceSchema.Columns, col)
+				if handleCol == nil {
+					handleCol = &expression.Column{
+						ID:       col.ID,
+						RetType:  &col.FieldType,
+						UniqueID: p.SCtx().GetSessionVars().AllocPlanColumnID(),
+					}
+				}
```
Comment (AilinKid) [inline pkg/planner/core/operator/physicalop/physical_index_scan.go:394]:
```suggestion
	assert handle !=nil
```
DataSourceSchema have every thing we want, actually
