### PR TITLE
statistics: add Destroy method and handle session recycling

### LINKED ISSUE #59524: release the internal session which may meet error like #54022
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

like the analysis in #54022, the internal session may not be released after it meets some error.

the pull that intended to fix that issue only removed the error found in the issue. but the unrealised behavior is not changed.

### PR DESCRIPTION
**Pull request by Rustin170506**
### What problem does this PR solve?

Issue Number: close #59524 close https://github.com/pingcap/tidb/issues/59560

Problem Summary:

### What changed and how does it work?

ref https://github.com/pingcap/tidb/pull/59522

This is an alternative API design to solve the problem. I believe explicitly using destroy instead of exposing implementation details is a better approach to fix it.

I also added more logs to help us inspect error cases.

Note: This PR doesn’t address the root cause of the issues; it only ensures that we don’t encounter OOM problems. We still need to figure out why we’re running into this kind of stats loading.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that the internal session used by statistics may not be released and cause possible memory leak.
修复统计信息在使用的内部会话在遇到错误时可能没有被释放的问题，该问题可能导致内存泄漏。
```

### CODE REVIEW

**Comment by Rustin170506** [comment]
Tested locally:

```log
[2025/02/14 18:03:16.597 +08:00] [WARN] [domain.go:2619] ["load histograms failed"] [error="not implemented"] [errorVerbose="not implemented\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).LoadNeededHistograms.func1\n\t/Users/rustin/code/tidb/pkg/statistics/handle/storage/stats_read_writer.go:225\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.WrapTxn\n\t/Users/rustin/code/tidb/pkg/statistics/handle/util/util.go:207\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx\n\t/Users/rustin/code/tidb/pkg/statistics/handle/util/util.go:105\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).LoadNeededHistograms\n\t/Users/rustin/code/tidb/pkg/statistics/handle/storage/stats_read_writer.go:223\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).asyncLoadHistogram\n\t/Users/rustin/code/tidb/pkg/domain/domain.go:2617\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1\n\t/Users/rustin/code/tidb/pkg/util/wait_group_wrapper.go:103\nruntime.goexit\n\t/opt/homebrew/Cellar/go/1.23.6/libexec/src/runtime/asm_arm64.s:1223"]
```

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

File: pkg/statistics/handle/util/util.go [hunk 1]
```diff
@@ -76,20 +76,23 @@ var (
...
 	se, err := pool.Get()
 	if err != nil {
-		return err
+		return errors.Trace(err)
 	}
 	defer func() {
 		if err == nil { // only recycle when no error
 			pool.Put(se)
+		} else {
+			// Note: Otherwise, the session will be leaked.
```
Comment (winoros) [inline pkg/statistics/handle/util/util.go:89]: i think we can add a intest.Assert here, if all errors are unexpected

Comment (Rustin170506) [reply pkg/statistics/handle/util/util.go:89]: I guess we may have some mock errors here.

Comment (Rustin170506) [reply pkg/statistics/handle/util/util.go:89]: Some test cases are affected by this assertion, so I removed it and kept only this one.
[`ca7c82f` (#59546)](https://github.com/pingcap/tidb/pull/59546/commits/ca7c82f35daa8ac5c69970aa5e6edd8d7ae3a340)

**Review by tangenta — APPROVED** [review]

File: pkg/statistics/handle/util/util.go (hunk 1 above)
Comment (bb7133) [reply pkg/statistics/handle/util/util.go:89]: We have other 'put back' codes like https://github.com/pingcap/tidb/blob/72a1145688e5c4cab368a75875cb9eb704b3583e/pkg/statistics/handle/bootstrap.go#L342-L346, I think it's better to handle them as well.

Comment (Rustin170506) [reply pkg/statistics/handle/util/util.go:89]: Updated.

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by Rustin170506 — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Comment by Rustin170506** [comment]
/hold

Wait for more reviewers from other teams.

File: pkg/util/session_pool.go [hunk 2]
```diff
@@ -29,6 +29,13 @@ type SessionPool interface {
 	Close()
 }
 
+// DestroyableSessionPool is a session pool that can destroy the session resource.
+// If the caller meets an error when using the session, it can destroy the session.
+type DestroyableSessionPool interface {
```
Comment (qw4990) [inline pkg/util/session_pool.go:34]: How about adding "StoreInternalSession" and "DeleteInternalSession" as an exampling here? Otherwise it's hard to understand why we have to manually destroy sessions if error...

**Review by qw4990 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

File: pkg/util/session_pool.go (hunk 2 above)
Comment (Rustin170506) [reply pkg/util/session_pool.go:35]: Added.

File: pkg/domain/domain.go [hunk 3]
```diff
@@ -158,8 +158,10 @@ type Domain struct {
 	m               syncutil.Mutex
 	SchemaValidator SchemaValidator
 	schemaLease     time.Duration
-	sysSessionPool  util.SessionPool
-	exit            chan struct{}
+	// Note: If you no longer need the session, you must call Destroy to release it.
+	// Otherwise, the session will be leaked. Because there is a strong reference from the session to the domain.
```
Comment (time-and-fate) [inline pkg/domain/domain.go:162]: > Because there is a strong reference from the session to the domain.

Should be "from the domain to the session"?

**Review by time-and-fate — APPROVED** [review]

File: pkg/domain/domain.go (hunk 3 above)
Comment (Rustin170506) [reply pkg/domain/domain.go:162]: Oops!

**Review by winoros — APPROVED** [review]
