### PR TITLE
planner: fix name ambiguous check when building natural join without filter

### LINKED ISSUE #32044: ambiguous column in join condition is not resulting error in tidb
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1,t2,t3,t4;
create table t1 (c int, b int);
create table t2 (a int, b int);
create table t3 (b int, c int);
create table t4 (y int, c int);

select * from t1 natural join (t3 cross join t4);
select * from (t3 cross join t4) natural join t1;
select * from (t1 join t2 on t1.b=t2.b) natural join (t3 natural join t4);
select * from  (t3 natural join t4) natural join (t1 join t2 on t1.b=t2.b);
```
### 2. What did you expect to see? (Required)
```sql
mysql> select * from t1 natural join (t3 cross join t4);
ERROR 1052 (23000): Column 'c' in from clause is ambiguous
mysql> select * from (t3 cross join t4) natural join t1;
ERROR 1052 (23000): Column 'c' in from clause is ambiguous
mysql> select * from (t1 join t2 on t1.b=t2.b) natural join (t3 natural join t4);
ERROR 1052 (23000): Column 'b' in from clause is ambiguous
mysql> select * from  (t3 natural join t4) natural join (t1 join t2 on t1.b=t2.b);
ERROR 1052 (23000): Column 'b' in from clause is ambiguous
```
### 3. What did you see instead (Required)
```
mysql> 
mysql> select * from t1 natural join (t3 cross join t4);
Empty set (0.00 sec)

mysql> select * from (t3 cross join t4) natural join t1;
Empty set (0.00 sec)

mysql> select * from (t1 join t2 on t1.b=t2.b) natural join (t3 natural join t4);
Empty set (0.00 sec)

mysql> select * from  (t3 natural join t4) natural join (t1 join t2 on t1.b=t2.b);
Empty set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.5.0-alpha-168-g23f7e51ae
Edition: Community
Git Commit Hash: 23f7e51ae01287fa7f811e1462d8987e4d7727a4
Git Branch: master
UTC Build Time: 2022-01-27 17:39:21
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by AilinKid**
Signed-off-by: AilinKid <314806019@qq.com>

### What problem does this PR solve?

Issue Number: close #32044

Problem Summary:

### What is changed and how it works?
natural join without a filter may find their common columns from both sides first.
then, for every common column, we need to make sure that there is exactly one column matches the name for each side.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: fix name ambiguous check when building natural join without filter
```

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -903,6 +903,60 @@ func (b *PlanBuilder) coalesceCommonColumns(p *LogicalJoin, leftPlan, rightPlan
 		if err != nil {
 			return err
 		}
+	} else {
+		// Even with no using filter, we still should check the checkAmbiguous name before we try to find the common column from both side.
+		// (t3 cross join t4) natural join t1
+		//  t1 natural join (t3 cross join t4)
+		// t3 and t4 may generate the same name column from cross join.
+		// for every common column of natural join, the name from right or left should be exactly one.
+		checkAmbiguous := func(lnames, rnames types.NameSlice) error {
```
Comment (time-and-fate) [inline planner/core/logical_plan_builder.go:912]: I think we don't need to make it a separate function here because we don't reuse this logic.

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -903,6 +903,60 @@ func (b *PlanBuilder) coalesceCommonColumns(p *LogicalJoin, leftPlan, rightPlan
...
+			// step1: find the common names first
```
Comment (time-and-fate) [inline planner/core/logical_plan_builder.go:913]: Where is "step2"? 🤣

File: planner/core/logical_plan_builder.go (hunk 1 above)
Comment (AilinKid) [reply planner/core/logical_plan_builder.go:912]: make sense

File: planner/core/logical_plan_builder.go [hunk 3]
```diff
@@ -911,6 +911,52 @@ func (b *PlanBuilder) coalesceCommonColumns(p *LogicalJoin, leftPlan, rightPlan
...
+		for _, name := range lNames {
+			// Natural join should ignore _tidb_rowid
+			if name.ColName.L == "_tidb_rowid" {
+				continue
+			}
+			// record left map
+			if cnt, ok := lNameMap[name.ColName.L]; ok {
+				lNameMap[name.ColName.L] = cnt + 1
+			} else {
+				lNameMap[name.ColName.L] = 1
```
Comment (xhebox) [inline planner/core/logical_plan_builder.go:932]: What about `map["v"] = map["v"] + 1`? If it is not in the map, the default value of `int` will be returned, i.e. 0.

Since int is not a pointer, I think there is no need to use `v, ok := map...` and check `ok`.

File: planner/core/logical_plan_builder.go [hunk 4]
```diff
@@ -911,6 +911,52 @@ func (b *PlanBuilder) coalesceCommonColumns(p *LogicalJoin, leftPlan, rightPlan
...
+				rNameMap[name.ColName.L] = cnt + 1
+			} else {
+				rNameMap[name.ColName.L] = 1
+			}
+			// check left map
+			if cnt, ok := lNameMap[name.ColName.L]; ok {
+				if cnt > 1 {
+					return ErrAmbiguous.GenWithStackByArgs(name.ColName.L, "from clause")
+				}
+				commonNames = append(commonNames, name.ColName.L)
```
Comment (time-and-fate) [inline planner/core/logical_plan_builder.go:951]: Seems we can also check "the right map" here, and don't need to maintain the `commonNames`.

**Review by AilinKid — COMMENTED** [review]
/retest

**Review by hawkingrei — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]

**Review by AilinKid — COMMENTED** [review]
/retest

File: pkg/planner/core/logical_plan_builder.go [hunk 5]
```diff
@@ -1152,6 +1152,52 @@ func (b *PlanBuilder) coalesceCommonColumns(p *LogicalJoin, leftPlan, rightPlan
...
+			// record right map
+			if cnt, ok := rNameMap[name.ColName.L]; ok {
+				rNameMap[name.ColName.L] = cnt + 1
+			} else {
+				rNameMap[name.ColName.L] = 1
+			}
+			// check left map
+			if cnt, ok := lNameMap[name.ColName.L]; ok {
+				if cnt > 1 {
+					return ErrAmbiguous.GenWithStackByArgs(name.ColName.L, "from clause")
```
Comment (hawkingrei) [inline pkg/planner/core/logical_plan_builder.go:1190]: ```ErrAmbiguous``` shoud be ```plannererrors.ErrAmbiguous```. ```ErrAmbiguous``` have been moved into ```pkg/util/dbterror/plannererrors```.

Comment (AilinKid) [reply pkg/planner/core/logical_plan_builder.go:1190]: make sense
