### PR TITLE
planner: Adjust risk assessment for plan choice | tidb-test=pr/2628

### LINKED ISSUE #64378: plan change after upgrade from v7.5.3 to next-gen
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> plan replayer load 'replayer_GMufz2jjBkCiRS4inm58eQ==_1762503468006331052.zip';                                                                                                                                             
Query OK, 0 rows affected, 3 warnings (0.215 sec)

explain...
```

### 2. What did you expect to see? (Required)
```
mysql> explain xxx;
+---------------------------------+---------+-----------+------------------------------+
| id                              | estRows | task      | access object                |
+---------------------------------+---------+-----------+------------------------------+
| Projection_8                    | 1.00    | root      |                              |
| └─TopN_11                       | 1.00    | root      |                              |
|   └─IndexLookUp_26              | 1.00    | root      |                              |
|     ├─Selection_23(Build)       | 1.00    | cop[tikv] |                              |
|     │ └─IndexRangeScan_21       | 3675.97 | cop[tikv] | table:T, index: a(a, b, c, d) |
|     └─TopN_25(Probe)            | 1.00    | cop[tikv] |                              |
|       └─Selection_24            | 1.00    | cop[tikv] |                              |
|         └─TableRowIDScan_22     | 1.00    | cop[tikv] | table:T                      |
+---------------------------------+---------+-----------+------------------------------+
8 rows in set (0.007 sec)

```

### 3. What did you see instead (Required)
```
+---------------------------------+---------+-----------+----------------------------------------------------------------------------------------------+
| id                              | estRows | task      | access object                                                                                |
+---------------------------------+---------+-----------+----------------------------------------------------------------------------------------------+
| Projection_8                    | 1.00    | root      |                                                                                              |
| └─TopN_11                       | 1.00    | root      |                                                                                              |
|   └─IndexLookUp_26              | 1.00    | root      |                                                                                              |
|     ├─Selection_19(Build)       | 1599.30 | cop[tikv] |                                                                                              |
|     │ └─IndexRangeScan_17       | 1599.30 | cop[tikv] | table:T, index:b(a, b, c, d, e) |
|     └─TopN_25(Probe)            | 1.00    | cop[tikv] |                                                                                              |
|       └─Selection_20            | 1.00    | cop[tikv] |                                                                                              |
|         └─TableRowIDScan_18     | 1599.30 | cop[tikv] | table:T                                                                                      |
+---------------------------------+---------+-----------+----------------------------------------------------------------------------------------------+
8 rows in set (0.009 sec)

```

### 4. What is your TiDB version? (Required)

next-gen & master

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #64378

Problem Summary:

### What changed and how does it work?

compareCandidates logic in skylinePruning now includes a riskFactor - to identify higher risk indexes, and use other metrics to counteract that high risk. This issue (64378) exposed that accessConds does not differentiate equal vs range predicates. The prior check that utilizes totalSum < -1 or > 1 was changed to instead check predicateResult (which does include EqOrInCondCount).

A 2nd issue was found and resolved in this PR. A prior PR (https://github.com/pingcap/tidb/pull/63349) added the "risk" assessment to compareCandidates logic - and it changed the behavior of "comparable1" && "comparable2". The prior behavior exited if either was false. PR 63349 allowed the risk assessment if both were false - but allowed the code to drop through if only 1 was false. This was inconsistent with the prior compareCandidates logic.

This new PR changes the !comparable2/!comparable2 to an OR.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/logical_plans_test.go [hunk 1]
```diff
@@ -1996,7 +1996,7 @@ func TestSkylinePruning(t *testing.T) {
 		},
 		{
 			sql:    "select * from t where d = 1 and f > 1 and g > 1 order by c, e",
-			result: "PRIMARY_KEY,c_d_e,f_g",
+			result: "PRIMARY_KEY,c_d_e,g,f_g",
```
Comment (qw4990) [inline pkg/planner/core/logical_plans_test.go:1999]: Make sense, we can't guarantee `f_g` can outperform `g` since we can apply `g>1` directly on `g` and maybe scan less data than using `f>1` scanning on `f_g`.

File: pkg/planner/core/find_best_task.go [hunk 2]
```diff
@@ -905,16 +906,19 @@ func compareCandidates(sctx base.PlanContext, statsTbl *statistics.Table, prop *
...
+	if !comparable1 || !comparable2 {
+		// These aren't comparable - meaning that they have different combinations of columns in
+		// the access conditions or filters.
+		// One or more predicates could carry high risk - so we want to compare that risk and other
+		// metrics to see if we can determine a clear winner.
+		// The 2 key metrics here are riskResult and predicateResult.
+		// - riskResult tells us which candidate has lower risk
+		// - predicateResult already includes risk - we need ">1" or "<-1" to counteract the risk factor.
+		// "DidNotLose" and totalSum are also factored in to ensure that the winner is better overall."
+		if riskResult > 0 && leftDidNotLose && totalSum >= 0 && predicateResult > 1 {
```
Comment (qw4990) [inline pkg/planner/core/find_best_task.go:918]: So we add this new condition `predicateResult > 1` to make this decision more "conservative".

File: pkg/planner/core/logical_plans_test.go (hunk 1 above)
Comment (AilinKid) [reply pkg/planner/core/logical_plans_test.go:1999]: make sense

File: pkg/planner/core/find_best_task.go (hunk 2 above)
Comment (terry1purcell) [reply pkg/planner/core/find_best_task.go:918]: Yes. The "riskResult" is already included in the "predicateResult" - and the reason for that is - I want to "collate" multiple criteria into 1. So a "loser" on risk could still win if the other 2 criteria mean it is a "win", and the reverse. What that means is - if riskResult > 0, I need one of the other 2 criteria to result in predicateResult > 1 (that is - the only way that predicateResult > 1 is if 2 of the 3 criteria are > 0 and the other is >= 0. Ultimately yes - this is to limit the scope of this preferencing - since it is new in master/TiDB X branch.
