### PR TITLE
ddl: fix `modify column` behavior about primary / unique key

### LINKED ISSUE #3613: `modify/change column` doesn't  affect the primary key
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
mysql> create table t(a int, primary key (a));
mysql> alter table t modify column a bigint;
```

2. What did you expect to see?

Return an unsupported error.

3. What did you see instead?
 ```
show create table t;

+-------+--------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                           |
+-------+--------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` bigint(21) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+-------+--------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by breeswish**
- Clean up some useless options in ddl.
- When primary key / unique key is not specified in `MODIFY COLUMN`, the behavior should be "keep original constraint"
- When primary key / unique key is specified in `MODIFY COLUMN`, the behavior should be "add new constraint according to spec" (and errors should be thrown because we don't support such operation now)
- Allow keeping AUTO_INCREMENT flag in `MODIFY COLUMN` (dropping is allowed already)
- Show more specific error when trying to set AUTO_INCREMENT flag when it is not set previously

Fix #3613, #3692

### CODE REVIEW

**Comment by breeswish** [comment]
PTAL @zimulala

**Comment by shenli** [comment]
Is this the same with MySQL?

> When primary key / unique key is not specified in MODIFY COLUMN, the behavior should be "keep original constraint"

**Comment by breeswish** [comment]
@shenli Yes.

According to https://dev.mysql.com/doc/refman/5.7/en/alter-table.html

> When you use CHANGE or MODIFY, column_definition must include the data type and all attributes that should apply to the new column, other than index attributes such as PRIMARY KEY or UNIQUE

However I cannot find official documentation about the behavior of MySQL when supplying PRIMARY KEY / UNIQUE and it is inferred from real world MySQL behavior now.

File: ast/ddl.go [hunk 1]
```diff
@@ -234,10 +234,6 @@ const (
 	ColumnOptionNotNull
 	ColumnOptionAutoIncrement
 	ColumnOptionDefaultValue
-	ColumnOptionUniq
```
Comment (shenli) [inline ast/ddl.go]: These is not used?

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -1089,6 +1075,10 @@ func setDefaultAndComment(ctx context.Context, col *table.Column, options []*ast
 			col.Flag |= mysql.NotNullFlag
 		case ast.ColumnOptionNull:
 			col.Flag &= ^uint(mysql.NotNullFlag)
+		case ast.ColumnOptionAutoIncrement:
```
Comment (shenli) [inline ddl/ddl_api.go]: Do we support alter table modify column with auto_increment option? @zimulala

File: ddl/ddl_api.go [hunk 3]
```diff
@@ -1162,6 +1157,20 @@ func (d *ddl) getModifiableColumnJob(ctx context.Context, ident ast.Ident, origi
 	if err := setDefaultAndComment(ctx, newCol, spec.NewColumn.Options); err != nil {
 		return nil, errors.Trace(err)
 	}
+
+	// copy index related options to the new spec
+	indexFlags := col.FieldType.Flag & (mysql.PriKeyFlag | mysql.UniqueKeyFlag | mysql.MultipleKeyFlag)
```
Comment (shenli) [inline ddl/ddl_api.go]: Consider auto_increment flag?

File: ast/ddl.go (hunk 1 above)
Comment (breeswish) [inline ast/ddl.go]: Yes, unused according to my whole-project searching... Seems that those constants were moved to constraints. For safety I suggest to take a look since I may not fully understand the architecture.

File: ddl/ddl_api.go (hunk 3 above)
Comment (breeswish) [inline ddl/ddl_api.go]: If auto_increment flag is missing in MODIFY COLUMN, the flag should be removed from the new column. Thus it is not copied.

File: ddl/ddl_api.go (hunk 2 above)
Comment (breeswish) [inline ddl/ddl_api.go]: Currently only allow keeping or dropping auto_increment flag. Set new flag [is not allowed](https://github.com/pingcap/tidb/pull/3748/files#diff-edfa54cbe2fdb418f0a77bd0ec4a56f2R1171).

**Comment by shenli** [comment]
LGTM
@zimulala PTAL

**Comment by shenli** [comment]
@hicqu PTAL

File: ddl/ddl_api.go [hunk 4]
```diff
@@ -1138,7 +1128,11 @@ func (d *ddl) getModifiableColumnJob(ctx context.Context, ident ast.Ident, origi
 	if col == nil {
 		return nil, infoschema.ErrColumnNotExists.GenByArgs(originalColName, ident.Name)
 	}
-	if spec.Constraint != nil || spec.NewColumn.Tp == nil {
+
+	// constraints in the new column means adding new constraints. Errors should thrown,
+	// which will be done by `setDefaultAndComment` later.
+
```
Comment (zimulala) [inline ddl/ddl_api.go]: Remove this blank line.

File: ddl/ddl_api.go [hunk 5]
```diff
@@ -1162,6 +1157,20 @@ func (d *ddl) getModifiableColumnJob(ctx context.Context, ident ast.Ident, origi
 	if err := setDefaultAndComment(ctx, newCol, spec.NewColumn.Options); err != nil {
 		return nil, errors.Trace(err)
 	}
+
+	// copy index related options to the new spec
+	indexFlags := col.FieldType.Flag & (mysql.PriKeyFlag | mysql.UniqueKeyFlag | mysql.MultipleKeyFlag)
+	newCol.FieldType.Flag |= indexFlags
+	if mysql.HasPriKeyFlag(col.FieldType.Flag) {
+		newCol.FieldType.Flag |= mysql.NotNullFlag
+		// TODO: if user explicitly set NULL, we should throw error ErrPrimaryCantHaveNull
```
Comment (zimulala) [inline ddl/ddl_api.go]: s/if/If
Add `.` at the end of a line.

File: ddl/ddl_api.go [hunk 6]
```diff
@@ -1162,6 +1157,20 @@ func (d *ddl) getModifiableColumnJob(ctx context.Context, ident ast.Ident, origi
...
+	}
+
+	// We don't support modifying column from not_auto_increment to auto_increment
```
Comment (zimulala) [inline ddl/ddl_api.go]: Ditto.

File: executor/ddl_test.go [hunk 7]
```diff
@@ -206,6 +207,46 @@ func (s *testSuite) TestAlterTableModifyColumn(c *C) {
 	createSQL := result.Rows()[0][1]
 	expected := "CREATE TABLE `mc` (\n  `c1` bigint(21) DEFAULT NULL,\n  `c2` text DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"
 	c.Assert(createSQL, Equals, expected)
+
+	// add constraints via change / modify column is not allowed, should throw error
+	tk.MustExec("drop table if exists mc")
+	tk.MustExec("create table mc(a int key, b int, c int)")
+	_, err = tk.Exec("alter table mc modify column a int key") // adds a new primary key
+	c.Assert(err, NotNil)
+	_, err = tk.Exec("alter table mc modify column b int key") // adds a new primary key
```
Comment (zimulala) [inline executor/ddl_test.go]: This test case is the same as line 214.

File: executor/ddl_test.go [hunk 8]
```diff
@@ -206,6 +207,46 @@ func (s *testSuite) TestAlterTableModifyColumn(c *C) {
 	createSQL := result.Rows()[0][1]
 	expected := "CREATE TABLE `mc` (\n  `c1` bigint(21) DEFAULT NULL,\n  `c2` text DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin"
 	c.Assert(createSQL, Equals, expected)
+
+	// add constraints via change / modify column is not allowed, should throw error
```
Comment (zimulala) [inline executor/ddl_test.go]: Move these tests to the package of `ddl`. It relates to the unit test coverage.

**Comment by breeswish** [comment]
@zimulala Done~

**Comment by zimulala** [comment]
LGTM 
Good job!
