### PR TITLE
ddl, errno: fix expression index allows row function

### LINKED ISSUE #18150: TiDB expression index allows row function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> CREATE TABLE t (j JSON, KEY k (((j,j))));
Query OK, 0 rows affected (0.01 sec)
```
In MySQL:
```
mysql> CREATE TABLE t (j JSON, KEY k (((j,j))));
ERROR 3800 (HY000): Expression of functional index 'k' cannot refer to a row value.
```
## Score
50

## SIG Slack Channel
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)
* @wjhuang2016 

## Recommended Skills
* DDL

## Learning Materials
N/A

### PR DESCRIPTION
**Pull request by wangggong**
Signed-off-by: wangggong <793160615@qq.com>

### What problem does this PR solve?

Issue Number: close #18150 

Problem Summary:

### What is changed and how it works?

What's Changed: ddl, errno

How it works: change error code when create invalid expression column or create invalid expression index.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- Change error code when create invalid expression column or create invalid expression index.

### CODE REVIEW

File: ddl/generated_column.go [hunk 1]
```diff
@@ -228,6 +228,7 @@ func checkModifyGeneratedColumn(tbl table.Table, oldCol, newCol *table.Column, n
 type illegalFunctionChecker struct {
 	hasIllegalFunc bool
 	hasAggFunc     bool
+	hasRowVal      bool // hasRowVal checks whether the functional index refers to a row value
```
Comment (wjhuang2016) [inline ddl/generated_column.go:231]: Note: generated column doesn't allow row function too.

Comment (wangggong) [reply ddl/generated_column.go:231]: OK, thx. Will the error message of generated column be the same as generated index?

Comment (wjhuang2016) [reply ddl/generated_column.go:231]: No， you can check it yourself.

Comment (wangggong) [reply ddl/generated_column.go:231]: done

PS: add an errno according to MySQL 8.0. Where should I sync the added errno? 'Cause I noticed that there are also errno list in `pingcap/parser` repo; I'm not sure if the sync is needed, and if there is other repo with the errno list.

File: ddl/generated_column.go [hunk 2]
```diff
@@ -267,6 +271,27 @@ func checkIllegalFn4GeneratedColumn(colName string, expr ast.ExprNode) error {
 	if c.hasAggFunc {
 		return ErrInvalidGroupFuncUse
 	}
+	if c.hasRowVal {
+		return ErrGeneratedColumnRowValueIsNotAllowed.GenWithStackByArgs(colName)
+	}
+	return nil
+}
+
+func checkIllegalFn4GeneratedIndex(idxName string, expr ast.ExprNode) error {
```
Comment (wjhuang2016) [inline ddl/generated_column.go:280]: It's better to combine two functions into one. Their logics are same, except for the error message.

Comment (wangggong) [reply ddl/generated_column.go]: done

File: ddl/generated_column.go [hunk 3]
```diff
@@ -259,38 +259,35 @@ func (c *illegalFunctionChecker) Leave(inNode ast.Node) (node ast.Node, ok bool)
...
-	}
-	return nil
-}
+const (
+	typeColumn = "column"
+	typeIndex  = "index"
+)
 
-func checkIllegalFn4GeneratedIndex(idxName string, expr ast.ExprNode) error {
+func checkIllegalFn4Generated(name, _type string, expr ast.ExprNode) error {
```
Comment (wjhuang2016) [inline ddl/generated_column.go:267]: using a boolean is enough here. 
If you want to use an explicit name, first, the type should be enum instead of string. Second, the name should not start with '_'.

Comment (wangggong) [reply ddl/generated_column.go]: done

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by wjhuang2016** [comment]
@tangenta @djshow832 PTAL

**Comment by djshow832** [comment]
Please modify the PR title and description. @wangggong 
PR title should begin with a package name.
All items in PR description should update.

**Comment by wangggong** [comment]
> Please modify the PR title and description. @wangggong
> PR title should begin with a package name.
> All items in PR description should update.

@djshow832 done

**Comment by djshow832** [comment]
> > Please modify the PR title and description. @wangggong
> > PR title should begin with a package name.
> > All items in PR description should update.
> 
> @djshow832 done

PR description is not updated, including `Check List` and `Release Note`.

File: ddl/db_integration_test.go [hunk 4]
```diff
@@ -2173,8 +2177,8 @@ func (s *testIntegrationSuite7) TestCreateExpressionIndexError(c *C) {
 	tk.MustExec("drop table if exists t;")
 	tk.MustExec("create table t (a int, b real);")
 	tk.MustGetErrCode("alter table t add primary key ((a+b));", errno.ErrFunctionalIndexPrimaryKey)
-	tk.MustGetErrCode("alter table t add index ((rand()));", errno.ErrGeneratedColumnFunctionIsNotAllowed)
-	tk.MustGetErrCode("alter table t add index ((now()+1));", errno.ErrGeneratedColumnFunctionIsNotAllowed)
+	tk.MustGetErrCode("alter table t add index ((rand()));", errno.ErrFunctionalIndexFunctionIsNotAllowed)
+	tk.MustGetErrCode("alter table t add index ((now()+1));", errno.ErrFunctionalIndexFunctionIsNotAllowed)
```
Comment (djshow832) [inline ddl/db_integration_test.go:2181]: Are these functions allowed in generated columns? Please add similar tests for generated columns.

**Comment by wangggong** [comment]
> > > Please modify the PR title and description. @wangggong
> > > PR title should begin with a package name.
> > > All items in PR description should update.
> > 
> > 
> > @djshow832 done
> 
> PR description is not updated, including `Check List` and `Release Note`.

@djshow832 done

Simply add some comment in PR description.

File: ddl/db_integration_test.go (hunk 4 above)
Comment (wangggong) [reply ddl/db_integration_test.go:2181]: Yes, in test TestSqlFunctionsInGeneratedColumns (https://github.com/pingcap/tidb/blob/bcf9ffe3f6dfedeb969ac768b532ac006c5e95bc/ddl/db_integration_test.go#L2048) there are some cases for generated columns. Thus similar tests for generated functional indexes are just added.

**Review by djshow832 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by djshow832** [comment]
Please pick up the issue again. It's outdated. @wangggong

**Comment by wangggong** [comment]
> Please pick up the issue again. It's outdated. @wangggong

@wjhuang2016 done

BTW, is there any document for the challenge program?

**Comment by wjhuang2016** [comment]
> > Please pick up the issue again. It's outdated. @wangggong
> 
> @wjhuang2016 done
> 
> BTW, is there any document for the challenge program?

You can follow PingCAP's Wechat 公众号.
