### PR TITLE
executor: handle missing timestamp value for load data

### LINKED ISSUE #10504: Load the imported data into the database, timestamp column, TiDB and MySQL behavior inconsistent
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

$ cat a.csv
2019-02-01 00:00:00

load data local infile "/data1/a.csv" into table test_table1;

Table structure：
MySQL [lianxi]> show create table test_table1 \G
*************************** 1. row ***************************
       Table: test_table1
Create Table: CREATE TABLE `test_table1` (
  `stime` datetime DEFAULT NULL COMMENT '时间',
  `id` bigint(20) DEFAULT NULL COMMENT '编号',
  `zone` varchar(100) DEFAULT NULL COMMENT '地区',
  `cnt` bigint(20) DEFAULT NULL COMMENT '次数',
  `updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated1` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated2` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_id` (`id`),
  KEY `idx_zone` (`zone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='测试表';

2. What did you expect to see?

MySQL [lianxi]> select * from test_table1 where stime='2019-02-01 00:00:00';
+---------------------+------+------+------+---------+---------------------+---------------------+
| stime               | id   | zone | cnt  | updated | updated1            | updated2            |
+---------------------+------+------+------+---------+---------------------+---------------------+
| 2019-02-01 00:00:00 | NULL | NULL | NULL | NULL    | 2019-05-15 19:41:02 | 2019-05-15 19:41:02 |
+---------------------+------+------+------+---------+---------------------+---------------------+

3. What did you see instead?

MySQL [test]> select * from test_table1 where stime='2019-02-01 00:00:00';
+---------------------+------+------+------+---------+---------------------+---------------------+
| stime               | id   | zone | cnt  | updated | updated1            | updated2            |
+---------------------+------+------+------+---------+---------------------+---------------------+
| 2019-02-01 00:00:00 | NULL | NULL | NULL | NULL    | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
+---------------------+------+------+------+---------+---------------------+---------------------+

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.1.8
Git Commit Hash: 9a2d2da372947a50a02f9b9238a49f2db7ab9971
Git Branch: HEAD
UTC Build Time: 2019-04-12 07:48:47
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
fix #10504 
`LOAD DATA` has different behavior with MySQL when handling missing timestamp/datetime value.

For example:
If we create a table:
```
create table t_default(id int, t timestamp null);
load data local infile "~/1.csv" into table t_default;
```
```
// 1.csv
12
```
The result for MySQL and TiDB are same:
```
mysql> select * from t_default;
+------+------+
| id   | t    |
+------+------+
|   12 | NULL |
+------+------+
1 row in set (0.00 sec)
```
But if `t` is `NOT NULL`, things are different.
```
create table t_default(id int, t timestamp not null default current_timestamp);
load data local infile "~/1.csv" into table t_default;
```
TiDB:
```
mysql> select * from t_default;
+------+---------------------+
| id   | t                   |
+------+---------------------+
|   12 | 0000-00-00 00:00:00 |
+------+---------------------+
1 row in set (0.00 sec)
```
MySQL:
```
mysql> select * from test.t_default;
+------+---------------------+
| id   | t                   |
+------+---------------------+
|   12 | 2019-07-05 13:27:05 |
+------+---------------------+
1 row in set (0.00 sec)
```
### What is changed and how it works?
Add check for missing timestamp columns when insert load data.
If these columns have `NOT NULL` flag, set them to `CURRENT_TIMESTAMP`.

### Check List 

Tests 

 - Unit test

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by imtbkcat** [comment]
@crazycs520 test case will be added right now.

File: executor/load_data.go [hunk 1]
```diff
@@ -282,8 +282,16 @@ func (e *LoadDataInfo) SetMessage() {
 }
 
 func (e *LoadDataInfo) colsToRow(cols []field) []types.Datum {
+	totalCols := e.Table.Cols()
 	for i := 0; i < len(e.row); i++ {
 		if i >= len(cols) {
+			// If some columns is missing and their type is time and has not null flag, they should be set as current time.
+			if totalCols[i].Tp == mysql.TypeTimestamp || totalCols[i].Tp == mysql.TypeDate || totalCols[i].Tp == mysql.TypeDatetime {
```
Comment (jackysp) [inline executor/load_data.go]: It is better to use `IsTypeTime`.

**Comment by imtbkcat** [comment]
PTAL @crazycs520

**Comment by jackysp** [comment]
PTAL @crazycs520
