### PR TITLE
expression: do not report error when got unknown locale

### LINKED ISSUE #11206: Results of function FORMAT is different from MySQL.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
SELECT FORMAT(12332.2, 2, 'de_DE'); show warnings;
SELECT FORMAT(12332.2, 2, 'xxxxx'); show warnings;
```

2. What did you expect to see?

```mysql
mysql> SELECT FORMAT(12332.2, 2, 'de_DE'); show warnings;
+-----------------------------+
| FORMAT(12332.2, 2, 'de_DE') |
+-----------------------------+
| 12.332,20                   |
+-----------------------------+
1 row in set (0.00 sec)

Empty set (0.00 sec)

mysql> SELECT FORMAT(12332.2, 2, 'xxxxx'); show warnings;
+-----------------------------+
| FORMAT(12332.2, 2, 'xxxxx') |
+-----------------------------+
| 12,332.20                   |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)

+---------+------+-------------------------+
| Level   | Code | Message                 |
+---------+------+-------------------------+
| Warning | 1649 | Unknown locale: 'xxxxx' |
+---------+------+-------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```mysql
mysql> SELECT FORMAT(12332.2, 2, 'de_DE'); show warnings;
ERROR 1105 (HY000): not support for the specific locale
Empty set (0.00 sec)

mysql> SELECT FORMAT(12332.2, 2, 'xxxxx'); show warnings;
ERROR 1105 (HY000): not support for the specific locale
Empty set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
8c20289c7

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @XuHuaiyu

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close #11206

### What is changed and how it works?

What's Changed:

How it Works:

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- do not report error when got unknown locale in format function.

### CODE REVIEW

File: expression/builtin_string.go [hunk 1]
```diff
@@ -3372,6 +3372,11 @@ func (b *builtinFormatWithLocaleSig) evalString(row chunk.Row) (string, bool, er
 		b.ctx.GetSessionVars().StmtCtx.AppendWarning(errUnknownLocale.GenWithStackByArgs("NULL"))
 		locale = "en_US"
 	}
+	// TODO: support other locales.
+	if locale != "en_US" {
```
Comment (morgo) [inline expression/builtin_string.go:3376]: I think there should be some normalization for case ( `strings.EqualFold(locale, "en_US")` etc) . In this branch:
```sql
mysql> SELECT FORMAT(12341.22,2, 'en_us');
+-----------------------------+
| FORMAT(12341.22,2, 'en_us') |
+-----------------------------+
| 12,341.22                   |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------+
| Level   | Code | Message                 |
+---------+------+-------------------------+
| Warning | 1649 | Unknown locale: 'en_us' |
+---------+------+-------------------------+
1 row in set (0.00 sec)
```

Versus in MySQL it will match with lower case without a warning:
```sql
mysql [localhost:5731] {msandbox} ((none)) > SELECT FORMAT(12341.22,2, 'en_US');
+-----------------------------+
| FORMAT(12341.22,2, 'en_US') |
+-----------------------------+
| 12,341.22                   |
+-----------------------------+
1 row in set (0.00 sec)

mysql [localhost:5731] {msandbox} ((none)) > SELECT FORMAT(12341.22,2, 'en_AA');
+-----------------------------+
| FORMAT(12341.22,2, 'en_AA') |
+-----------------------------+
| 12,341.22                   |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)

mysql [localhost:5731] {msandbox} ((none)) > SELECT FORMAT(12341.22,2, 'en_us');
+-----------------------------+
| FORMAT(12341.22,2, 'en_us') |
+-----------------------------+
| 12,341.22                   |
+-----------------------------+
1 row in set (0.00 sec)

```

**Review by wjhuang2016 — COMMENTED** [review]
vecEvalString() also need to modify.

File: expression/builtin_string_vec.go [hunk 2]
```diff
@@ -2916,6 +2916,10 @@ func formatReal(sctx sessionctx.Context, xBuf *chunk.Column, dInt64s []int64, re
 		} else {
 			locale = localeBuf.GetString(i)
 		}
+		if strings.EqualFold(locale, "en_US") { // TODO: support other locales.
```
Comment (wjhuang2016) [inline expression/builtin_string_vec.go]: formatDecimal() too.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by morgo** [comment]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
