### PR TITLE
executor: fix issue that update ignore stmt return error when meet incorrect timestamp value error

### LINKED ISSUE #50308: should not return error when updating timestamp to an overflowed value with 'ignore'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
> create table t(t timestamp);
> insert into t values("2000-01-01");
> update ignore t set t=cast("2099-01-01" as date);
> select * from t;
```

### 2. What did you expect to see? (Required)

```
mysql> update ignore t set t=cast("2099-01-01" as date);
Query OK, 1 row affected, 1 warning (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 1

mysql> select * from t;
+---------------------+
| t                   |
+---------------------+
| 0000-00-00 00:00:00 |
+---------------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```
mysql> update ignore t set t=cast("2099-01-01" as date);
ERROR 1292 (22007): Incorrect timestamp value: '2099-01-01'
mysql> select * from t;
+---------------------+
| t                   |
+---------------------+
| 2000-01-01 00:00:00 |
+---------------------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #50308

Problem Summary: As title said, see more detail in issue #50308

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/update.go [hunk 1]
```diff
@@ -351,7 +351,10 @@ func (*UpdateExec) handleErr(colName model.CIStr, rowIdx int, err error) error {
 	if types.ErrOverflow.Equal(err) {
 		return types.ErrWarnDataOutOfRange.GenWithStackByArgs(colName.O, rowIdx+1)
 	}
-
+	if types.ErrTruncatedWrongVal.Equal(err) && col != nil && col.ColumnInfo != nil && col.ColumnInfo.GetType() == mysql.TypeTimestamp {
+		ec := e.Ctx().GetSessionVars().StmtCtx.ErrCtx()
+		return errors.AddStack(ec.HandleErrorWithAlias(kv.ErrKeyExists, err, err))
```
Comment (crazycs520) [inline pkg/executor/update.go:356]: Related error handling logic in Insert statement: 
https://github.com/pingcap/tidb/blob/47179ae14d6bb7947d8857b4e8c91212bce999aa/pkg/executor/insert_common.go#L324-L328

I've added error type and column type checking to avoid mishandling other errors here.

**Comment by crazycs520** [comment]
@lcwangchao @cfzjywxk PTAL

**Review by lcwangchao — APPROVED** [review]

File: pkg/executor/update.go [hunk 2]
```diff
@@ -351,7 +351,10 @@ func (*UpdateExec) handleErr(colName model.CIStr, rowIdx int, err error) error {
 	if types.ErrOverflow.Equal(err) {
 		return types.ErrWarnDataOutOfRange.GenWithStackByArgs(colName.O, rowIdx+1)
 	}
-
+	if types.ErrTruncatedWrongVal.Equal(err) && col != nil && col.ColumnInfo != nil && col.ColumnInfo.GetType() == mysql.TypeTimestamp {
```
Comment (cfzjywxk) [inline pkg/executor/update.go:354]: So the condition here allowed to be igmored is "timestamp column && truncated value", right?
Is this condition check consistent with MySQL behaviour?

Comment (crazycs520) [reply pkg/executor/update.go:354]: Yes, this is compatible with MySQL, except for the error message.

**MySQL 8.0.29 **

```sql
mysql> create table t(t timestamp);
Query OK, 0 rows affected (0.09 sec)

mysql> insert into t values("2000-01-01");
Query OK, 1 row affected (0.00 sec)

mysql> update ignore t set t=cast("2099-01-01" as date);
Query OK, 1 row affected, 1 warning (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 1

mysql> show warnings;
+---------+------+--------------------------------------------+
| Level   | Code | Message                                    |
+---------+------+--------------------------------------------+
| Warning | 1264 | Out of range value for column 't' at row 1 |
+---------+------+--------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t;
+---------------------+
| t                   |
+---------------------+
| 0000-00-00 00:00:00 |
+---------------------+
1 row in set (0.00 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.29    |
+-----------+
```

**This PR**

```sql
mysql> create table t(t timestamp);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values("2000-01-01");
Query OK, 1 row affected (0.00 sec)

mysql> update ignore t set t=cast("2099-01-01" as date);
Query OK, 1 row affected, 1 warning (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 1

mysql> show warnings;
+---------+------+-----------------------------------------+
| Level   | Code | Message                                 |
+---------+------+-----------------------------------------+
| Warning | 1292 | Incorrect timestamp value: '2099-01-01' |
+---------+------+-----------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t;
+---------------------+
| t                   |
+---------------------+
| 0000-00-00 00:00:00 |
+---------------------+
1 row in set (0.00 sec)

mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.2.0-alpha-675-g38a5139c3e
Edition: Community
Git Commit Hash: 38a5139c3eae82d3e2ea5f82f6ea89ceeabb505f
Git Branch: fix-50308
UTC Build Time: 2024-07-30 09:04:16
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Review by cfzjywxk — APPROVED** [review]
LGTM
