### PR TITLE
planner: log the reason why the sample-rate is chosen when analyzing table

### LINKED ISSUE #45936: planner: log the reason why the sample-rate is chosen when analyzing table
## Enhancement
The optimizer chose the wrong sample rate to analyze a big table and then caused TiDB OOM, but now we cannot know why this wrong sample rate is chosen from the log.
It's better to log the reason why the sample rate is chosen for this table when analyzing:
image

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #45936

Problem Summary: planner: log the reason why the sample-rate is chosen when analyzing table

### What is changed and how it works?

planner: log the reason why the sample-rate is chosen when analyzing table

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/analyze.go [hunk 1]
```diff
@@ -594,7 +594,8 @@ func finishJobWithLog(sctx sessionctx.Context, job *statistics.AnalyzeJob, analy
 			zap.String("job info", job.JobInfo),
 			zap.Time("start time", job.StartTime),
 			zap.Time("end time", job.EndTime),
-			zap.String("cost", job.EndTime.Sub(job.StartTime).String()))
+			zap.String("cost", job.EndTime.Sub(job.StartTime).String()),
```
Comment (hawkingrei) [inline executor/analyze.go:597]:
```suggestion
			zap.Duration("cost", job.EndTime.Sub(job.StartTime)),
```

Comment (qw4990) [reply executor/analyze.go:597]: Let me fix it in the next PR. I'm afraid this change will bring lots of test failures...

File: executor/builder.go [hunk 2]
```diff
@@ -2804,11 +2809,11 @@ func (b *executorBuilder) getAdjustedSampleRate(task plannercore.AnalyzeColumnsT
 	approxiCount, hasPD := b.getApproximateTableCountFromStorage(tid, task)
 	// If there's no stats meta and no pd, return the default rate.
 	if statsTbl == nil && !hasPD {
-		return defaultRate
+		return defaultRate, fmt.Sprintf("statsTbl is nil and no pd info, use the default-rate=%v", defaultRate)
 	}
 	// If the count in stats_meta is still 0 and there's no information from pd side, we scan all rows.
 	if statsTbl.RealtimeCount == 0 && !hasPD {
-		return 1
+		return 1, fmt.Sprintf("statsTbl.RealtimeCount is 0 and no pd info, use sample-rate=1")
```
Comment (winoros) [inline executor/builder.go:2816]:
```suggestion
		return 1, fmt.Sprintf("Tidb assumes that the table is empty, use sample-rate=1")
```

File: executor/builder.go [hunk 3]
```diff
@@ -2817,15 +2822,17 @@ func (b *executorBuilder) getAdjustedSampleRate(task plannercore.AnalyzeColumnsT
...
 		// Confirmed by TiKV side, the experience error rate of the approximate count is about 20%.
 		// So we increase the number to 150000 to reduce this error rate.
-		return math.Min(1, 150000/approxiCount)
+		sampleRate = math.Min(1, 150000/approxiCount)
+		return sampleRate, fmt.Sprintf("statsTbl.RealtimeCount is too small, use min(1, 15000/%v) as the sample-rate=%v", approxiCount, sampleRate)
 	}
 	// If we don't go into the above if branch and we still detect the count is zero. Return 1 to prevent the dividing zero.
 	if statsTbl.RealtimeCount == 0 {
-		return 1
+		return 1, fmt.Sprintf("statsTbl.RealtimeCount is 0, use sample-rate=1")
```
Comment (winoros) [inline executor/builder.go:2830]:
```suggestion
		return 1, fmt.Sprintf("TiDB assumes that the table is empty, use sample-rate=1")
```

**Review by chrysan — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
