### PR TITLE
*: make auto-analyze concurrency configurable

### LINKED ISSUE #37183: auto-analyze is slow due to hardcoded concurrency 1
## Enhancement
auto-analyze concurrency is now hardcoded to be 1 which causes auto-analyze runs too slowly and may fail due to exceeding gc-life-time at versions before v6.2
https://github.com/pingcap/tidb/blob/3507a720aad16aa225f72c4d8b8d740aaba0a6d4/executor/adapter.go#L120-L135

### PR DESCRIPTION
**Pull request by chrysan**
### What problem does this PR solve?

Issue Number: close #37183 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xuyifangreeneyes — APPROVED** [review]

File: sessionctx/variable/tidb_vars.go [hunk 1]
```diff
@@ -1020,6 +1024,8 @@ const (
 	MaxDDLReorgBatchSize           int32  = 10240
 	MinDDLReorgBatchSize           int32  = 32
 	MinExpensiveQueryTimeThreshold uint64 = 10 // 10s
+	DefAutoBuildStatsConcurrency                   = 1
+	DefTiDBSysProcScanConcurrency                  = 1
```
Comment (jackysp) [inline sessionctx/variable/tidb_vars.go:1028]: Why is one of the default value names with `TiDB`, but another one without it?

File: executor/adapter.go [hunk 2]
```diff
@@ -441,9 +442,19 @@ func (a *ExecStmt) Exec(ctx context.Context) (_ sqlexec.RecordSet, err error) {
...
+		if err1 == nil {
+			terror.Log(sctx.GetSessionVars().SetSystemVar(variable.TiDBBuildStatsConcurrency, autoConcurrency))
+		}
+		sVal, err2 := sctx.GetSessionVars().GetSessionOrGlobalSystemVar(variable.TiDBSysProcScanConcurrency)
+		terror.Log(err2)
+		if err2 == nil {
+			concurrency, err3 := strconv.ParseInt(sVal, 10, 64)
+			terror.Log(err3)
+			sctx.GetSessionVars().SetDistSQLScanConcurrency(int(concurrency))
+			sctx.GetSessionVars().SetIndexSerialScanConcurrency(int(concurrency))
```
Comment (jackysp) [inline executor/adapter.go:456]: So it is one variable to control two others, it may make the users a little confused.

File: sessionctx/variable/tidb_vars.go (hunk 1 above)
Comment (chrysan) [reply sessionctx/variable/tidb_vars.go]: Update the name.

File: executor/adapter.go (hunk 2 above)
Comment (chrysan) [reply executor/adapter.go]: Updated. IndexSerialScanConcurrency is not commonly used in analyze v2, skip it this time.

**Review by qw4990 — APPROVED** [review]
