### PR TITLE
encoding: skip utf8 charset validation in some cases

### LINKED ISSUE #31014: PR #30288 results in 5.4%-10% performance regression in read-heavy workloads
## Bug Report

PR #30288 results in 5.4%-10% performance regression in read-heavy workloads

### 1. Minimal reproduce step (Required)

1. Deploy a cluster with nightly version
2. Turn on Prepare plan cache
2. Run sysbench oltp_read_only or other read-heavy workloads

### 3. What did you see instead (Required)

The performance of workloads drops 5.4%-10% compared with their baseline.
You can take commit 755553660e6036ead13d1f0aa271eaf59d939fbd as baseline.

### 4. What is your TiDB version? (Required)

commit 4dc385ce8b7a3b194462e76670f89483de5884b7

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #31014

Problem Summary:

I suspect that the utf8 validation in common code path is the main reason to cause performance regression, even if a faster version `utf8.Valid()` is used.

### What is changed and how it works?

This PR tries to reduce the string validation as less as possible.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: parser/charset/encoding.go [hunk 1]
```diff
@@ -29,6 +29,16 @@ func IsSupportedEncoding(charset string) bool {
 	return ok
 }
 
+// FindEncodingUTF8AsNoop finds the encoding according to charset
+// except that utf-8 is treated as binary encoding.
+func FindEncodingUTF8AsNoop(charset string) Encoding {
```
Comment (bb7133) [inline parser/charset/encoding.go:34]: 1. Please add a test case for this function.
2. The comment is still confusing to me at least, what is the case when "utf-8 is treated as binary encoding"?

Comment (tangenta) [reply parser/charset/encoding.go:34]: 1. I think the logic here is simple enough...?
2. Binary encoding is a noop encoding. Different from utf-8 encoding, it means all the methods are trivial, including `Transform()`, `IsValid()` and others. The cost should be O(1) for these operations. I am trying to avoid string validation(before parsing or writing result to client) to see if there is any improvement.

Comment (bb7133) [reply parser/charset/encoding.go:34]: > Binary encoding is a noop encoding. Different from utf-8 encoding, it means all the methods are trivial, including Transform(), IsValid() and others. The cost should be O(1) for these operations. I am trying to avoid string validation(before parsing or writing result to client) to see if there is any improvement.

Thanks! I think this can be added to the comment in some way...

@Yui-Song Could you try to validate the result using your benchmark?

Comment (Yui-Song) [reply parser/charset/encoding.go:34]: > > Binary encoding is a noop encoding. Different from utf-8 encoding, it means all the methods are trivial, including Transform(), IsValid() and others. The cost should be O(1) for these operations. I am trying to avoid string validation(before parsing or writing result to client) to see if there is any improvement.
> 
> Thanks! I think this can be added to the comment in some way...
> 
> @Yui-Song Could you try to validate the result using your benchmark?
I have told @tangenta how to validate it easily with Benchbot, a platform provided by QA team to do benchmarks. All the benchmarks the Perf Team run daily could be run with it.

Comment (bb7133) [reply parser/charset/encoding.go:34]: @Yui-Song  For the benchmark today, could you share the profiling files for both https://github.com/pingcap/tidb/commit/755553660e6036ead13d1f0aa271eaf59d939fbd and this commit?

**Review by Defined2014 — APPROVED** [review]

**Comment by Defined2014** [comment]
Could you add some performance result?

**Comment by tangenta** [comment]
@bb7133 @Defined2014 I have compared the performance between e3c56b75(the commit before #30288) and 4f8a0413d(this PR). Here is the result:

```
bench_start_time        bench_type      thread      tps_tpm     commit_hash
2021-12-28 15:39:24     shenma          200         5639        4f8a0413d39
2021-12-28 14:34:23     shenma          200         5570        e3c56b75eae
```

I think the performance regression have been solved by this PR.

**Review by xiongjiwei — APPROVED** [review]
