### PR TITLE
importinto: optimize write ingest step and fix oom

### LINKED ISSUE #47643: external engine oom on loadIngestData
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
import 32g data using global sort on a 4c8g node

backend worker concurrency is 32, range data loader concurrency is `min(int(MergeSortOverlapThreshold) / len(e.dataFiles), 8)`，write&ingest worker concurrency is fixed as 32, external engine might load too many data into memory

image

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #47572, close #47643

Problem Summary:

### What is changed and how it works?
- add option checkHotspot to allow read each file using single reader.
- adjust concurrency of LoadIngestData depends on number of data-files when we disable checkHotspot, after this, we can have more concurrency to load ingest data.
- send loaded ingestData immediately to reduce memory usage, now we can hold at most 1 DataAndRange per LoadIngestData routine
- adjust WorkerConcurrency for import-into on global-sort based on thread-cnt to avoid oom see https://github.com/pingcap/tidb/issues/47643
- display total file size in IEC unit
- refine logs

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - NOTE: below test all set this:
```
set global tidb_server_memory_limit_gc_trigger=0.99;
set global tidb_server_memory_limit='88%';
```
  - test a add-index case of 100M rows(sbtest1) using 1 node and global-sort, this pr takes 5 min 30.47 (5 min 38.94 on master). **KS3 speed is not that stable, the speed varies a little.**
  - test import-into of 150G using 1 node and global-sort, this pr takes 26m (45m on master)
  - test import-into on 1T 1 node and global-sort, success
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/external/engine.go [hunk 1]
```diff
@@ -228,38 +265,49 @@ func (e *Engine) loadIngestData(
 		if bytes.Compare(k, end) >= 0 {
 			break
 		}
-		if largeRegion && size > LargeRegionSplitDataThreshold {
+		// as we keep KV data in memory, to avoid OOM, we only keep at most 1
+		// DataAndRange for each loadIngestData and regionJobWorker routine(channel
+		// is unbuffered).
+		if size > LargeRegionSplitDataThreshold {
+			readRateHist.Observe(float64(size) / 1024.0 / 1024.0 / time.Since(batchStartTs).Seconds())
+			readDurHist.Observe(time.Since(batchStartTs).Seconds())
```
Comment (wjhuang2016) [inline br/pkg/lightning/backend/external/engine.go:273]: The duration may not be correct. We can ignore the time during sendFn().

**Review by lance6716 — APPROVED** [review]
please address existing comments

**Review by wjhuang2016 — APPROVED** [review]
