### PR TITLE
log-backup: added more robust error handling for log backup advancer

### LINKED ISSUE #41082: log-backup: cannot observe new tasks when there are some errors in the etcd
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
During log backup enabled, make the etcd client meet some watch errors.

### 2. What did you expect to see? (Required)
Log backup runs as expected.

### 3. What did you see instead (Required)
The log backup advancer exits, and cannot get the add task events.
According to the goroutine dump, we found the etcd wather goroutines are exited.

### 4. What is your TiDB version? (Required)
v6.5.0

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: hillium <yujuncen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #41082 

Problem Summary:
When etcd client closes the channel, the current implementation would trivially exit without retry.

### What is changed and how it works?
This PR make the etcd adapter send an error response when the channel is about to be closed.
It also added some logs so we can meet the real error of closing.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fixed a bug that may cause PITR stop advancing the progress when connection to PD is changed.
```

### CODE REVIEW

File: br/pkg/streamhelper/advancer_cliext.go [hunk 1]
```diff
@@ -118,33 +123,42 @@ func (t AdvancerExt) startListen(ctx context.Context, rev int64, ch chan<- TaskE
 		}
 		return true
 	}
+	collectRemaining := func() {
+		for {
+			select {
+			case resp, ok := <-c:
+				if !ok {
```
Comment (3pointer) [inline br/pkg/streamhelper/advancer_cliext.go:130]: also add a log here

**Review by Leavrth — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
