### PR TITLE
executor, privileges: fix privilege check fail for `CREATE USER` and `DROP USER`

### LINKED ISSUE #9111: CREATE USER/DROP USER privilege check is incorrect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
# as root
CREATE USER u1;
grant create user on *.* to u1;

# mysql -uu1
CREATE USER u2;
DROP USER u2;
```

2. What did you expect to see?

MySQL 5.7:
```
mysql [localhost] {u1} ((none)) > CREATE USER u2;
Query OK, 0 rows affected (0.00 sec)

mysql [localhost] {u1} ((none)) > DROP USER u2;
Query OK, 0 rows affected (0.00 sec)
```

3. What did you see instead?

TiDB:
```
mysql> CREATE USER u2;
ERROR 1105 (HY000): privilege check fail
mysql> DROP USER u2;
ERROR 1396 (HY000): Operation DROP USER failed for u2@%
mysql> SHOW GRANTS;
+--------------------------------------+
| Grants for User                      |
+--------------------------------------+
| GRANT Create User ON *.* TO 'u1'@'%' |
+--------------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-490-g5f8265a8f-dirty
Git Commit Hash: 5f8265a8f9bebc6d61c18d1e7c0aabb493ef2c41
Git Branch: usevisitinfo
UTC Build Time: 2019-01-18 02:28:38
GoVersion: go version go1.11.4 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by imtbkcat**
### What problem does this PR solve? 
fix #9111 

### What is changed and how it works?
This problem was caused by using `ctx.Execute(sql)` to modify system privilege table. If user do not have privilege to insert or date to `mysql.User`, SQL execution will fail user had `CREATE USER` privilege.

Using system session to execute sql to modify `mysql.User` will fix this problem.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: planner/core/logical_plan_test.go [hunk 1]
```diff
@@ -1712,18 +1712,6 @@ func (s *testPlanSuite) TestVisitInfo(c *C) {
 				{mysql.IndexPriv, "test", "t", "", nil},
 			},
 		},
-		{
```
Comment (tiancaiamao) [inline planner/core/logical_plan_test.go]: Why this is removed?

File: planner/core/planbuilder.go [hunk 2]
```diff
@@ -1334,22 +1334,6 @@ func (b *PlanBuilder) buildSimple(node ast.StmtNode) (Plan, error) {
 	p := &Simple{Statement: node}
 
 	switch raw := node.(type) {
-	case *ast.CreateUserStmt:
```
Comment (tiancaiamao) [inline planner/core/planbuilder.go]: ditto

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
PTAL @lysu
