### PR TITLE
planner: align index range estimation with index columns

### LINKED ISSUE #66291: runtime error: index out of range under concurrent query + add/drop index
## Bug Report

TiDB intermittently returns a runtime panic-style error during concurrent query execution and index add/drop DDL on the same tables:

```text
ERROR 1105 (HY000): runtime error: index out of range [2] with length 2
```

I can reproduce this reliably with a small stress script.

### 1) Download repro assets

Assets (schema, data, repro script):
- Gist: https://gist.github.com/hawkingrei/32fa638c335bc1a12174895cb41b7ca2
- `schema.sql`: https://gist.githubusercontent.com/hawkingrei/32fa638c335bc1a12174895cb41b7ca2/raw/0b55b7b834e646d8c2e68017e89d556cea53bf2a/case_0008_schema.sql
- `inserts.sql`: https://gist.githubusercontent.com/hawkingrei/32fa638c335bc1a12174895cb41b7ca2/raw/cc1bd2e36d5fd954b4c0dc281c327b341bdad0cf/case_0008_inserts.sql
- `repro.sh`: https://gist.githubusercontent.com/hawkingrei/32fa638c335bc1a12174895cb41b7ca2/raw/d2634f60a11e1219a875e24956ba052d488dbe35/repro.sh

```bash
mkdir -p /tmp/tidb-case-0008 && cd /tmp/tidb-case-0008
curl -LO https://gist.githubusercontent.com/hawkingrei/32fa638c335bc1a12174895cb41b7ca2/raw/0b55b7b834e646d8c2e68017e89d556cea53bf2a/case_0008_schema.sql
curl -LO https://gist.githubusercontent.com/hawkingrei/32fa638c335bc1a12174895cb41b7ca2/raw/cc1bd2e36d5fd954b4c0dc281c327b341bdad0cf/case_0008_inserts.sql
curl -LO https://gist.githubusercontent.com/hawkingrei/32fa638c335bc1a12174895cb41b7ca2/raw/d2634f60a11e1219a875e24956ba052d488dbe35/repro.sh
chmod +x repro.sh
```

### 2) Apply schema/load data

<details>
<summary>Apply schema and load data (large SQL)</summary>

```bash
mysql --comments --host 127.0.0.1 --port 4000 -u root -e "DROP DATABASE IF EXISTS tidb_issue_repro_case_0008; CREATE DATABASE tidb_issue_repro_case_0008;"
mysql --comments --host 127.0.0.1 --port 4000 -u root -D tidb_issue_repro_case_0008 < case_0008_schema.sql
mysql --comments --host 127.0.0.1 --port 4000 -u root -D tidb_issue_repro_case_0008 -e "SET SESSION FOREIGN_KEY_CHECKS=0;"
mysql --comments --host 127.0.0.1 --port 4000 -u root -D tidb_issue_repro_case_0008 < case_0008_inserts.sql
mysql --comments --host 127.0.0.1 --port 4000 -u root -D tidb_issue_repro_case_0008 -e "SET SESSION FOREIGN_KEY_CHECKS=1;"
```

</details>

### 3) Run stress repro

```bash
bash repro.sh
```

This script runs concurrently:
- query workers executing the same SELECT repeatedly
- a DDL worker doing add/drop index loops:
  - `ALTER TABLE t3 ADD/DROP INDEX idx_tmp_meta_a (c1,c0)`
  - `ALTER TABLE t5 ADD/DROP INDEX idx_tmp_meta_b (c1,c3)`

## Run the query

```sql
SELECT t3.id AS t0_id, t5.id AS t1_id
FROM (
  SELECT t3.id AS id, t3.c0 AS c0, t3.c1 AS c1, t3.c2 AS c2, t3.c3 AS c3
  FROM t3
  WHERE (t3.c1 = 's26')
) AS t3
JOIN (
  SELECT t5.id AS id, t5.c0 AS c0, t5.c1 AS c1, t5.c2 AS c2, t5.c3 AS c3
  FROM t5
  WHERE (t5.id = 120)
) AS t5
  ON ((t3.id = t5.id) AND (t5.c1 = 99))
WHERE (((t5.c3 = 84) AND (t3.c2 = '2023-08-08 22:19:45')) AND (t3.c0 = '2024-02-18 02:32:31'));
```

## Actual Behavior

Intermittent failures (often quickly under DDL+query concurrency):

```text
ERROR 1105 (HY000) at line 1: runtime error: index out of range [2] with length 2
```

Sample hit log:

```text
HIT query worker=2 iter=97
HIT query worker=4 iter=96
HIT query worker=6 iter=97
HIT query worker=1 iter=95
ERROR 1105 (HY000) at line 1: runtime error: index out of range [2] with length 2
...
HIT ddl-after-add cycle=1
ERROR 1105 (HY000) at line 1: runtime error: index out of range [2] with length 2
```

## Expected Behavior

No runtime out-of-range panic. Query should execute normally (returning rows or empty set), regardless of concurrent index add/drop operations.

## Additional Observation

The same query is hard to reproduce in a single-thread no-DDL loop (for example, 1000 loops with no DDL produced no hit in my environment), but reproduces with concurrent DDL index churn.

## Environment

```text
Release Version: v9.0.0-beta.2.pre-1244-g2f9776e8e7
Edition: Community
Git Commit Hash: 2f9776e8e7b252a1b14237e9a071bb1fa4ceac99
Git Branch: HEAD
UTC Build Time: 2026-02-14 20:59:24
GoVersion: go1.25.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Kernel Type: Classic
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #66291

Problem Summary:

Under query + DDL interleaving (`ADD/DROP INDEX` loop with concurrent `SELECT`), TiDB may panic with:

`runtime error: index out of range [2] with length 2`

The analysis remains the same:

- For non-unique index paths, execution ranges may include an appended handle dimension.
- Row-count estimation still uses index-definition columns.
- In the partial-stats path (`index stats invalid + column stats available`), iterating by range dimension can read past the estimation-column slice and panic.

This is also why the panic is not deterministic: it requires a specific optimizer/estimation-path combination and timing window.

### What changed and how does it work?

The fix keeps the same root-cause analysis but uses a simpler implementation path:

- Keep estimation columns as index-definition columns (`indexCols`).
- Build execution ranges once as before.
- If range width is larger than `len(indexCols)` (appended handle present), prune each range to the first `len(indexCols)` dimensions for estimation.
- Call `GetRowCountByIndexRanges(estimateRanges, indexCols)` with the pruned view.

Compared with the earlier rebuild-based idea, this avoids a second estimation-only range build from conditions, reduces implementation complexity, and keeps estimation behavior comparable with previous baselines.

Files:

- `pkg/planner/core/stats.go`
- `pkg/planner/cardinality/selectivity_test.go`

Regression test added:

- `TestIndexRangeEstimationWithAppendedHandleColumn`
  - non-unique index + PK handle scenario,
  - missing index stats + available column stats,
  - verifies `EXPLAIN` on index path does not panic.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Test commands:

```bash
go test ./pkg/planner/cardinality -run TestIndexRangeEstimationWithAppendedHandleColumn --tags=intest -count=1

make failpoint-enable && (
  pushd pkg/planner/core/casetest/planstats >/dev/null
  go test -run 'TestPartialStatsInExplain/off' --tags=intest -count=1
  rc=$?
  popd >/dev/null
  make failpoint-disable
  exit $rc
)
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix a planner panic caused by index-range dimension mismatch when non-unique index paths append handle columns during cardinality estimation under query/DDL interleaving.
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
Addressed the two review comments in commit dbb85a1f2a0:

1. CountAfterAccess estimation now uses the same column slice as range detachment (`path.IdxCols`) when calling `GetRowCountByIndexRanges`, so handle-predicate selectivity is preserved.
2. Removed the extra range rebuild path, so there is no unnecessary second detach anymore.

Also updated notes and PR description to match the final implementation.

/test check-dev
/test check-dev2

File: pkg/planner/core/stats.go [hunk 1]
```diff
@@ -419,7 +419,23 @@ func detachCondAndBuildRangeForPath(
 	if len(indexCols) > len(path.Index.Columns) { // remove clustered primary key if it has been added to path.IdxCols
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/stats.go]: Good point. I tried the direct `path.IdxCols` estimation path first, but it introduced a planner regression in `TestPartialStatsInExplain/off` (plan shape/row-count changes in the partial-stats branch).

To keep this fix minimal and regression-safe, the final change keeps estimation on index-definition columns (`indexCols`) and only rebuilds an estimation-only range view when execution ranges carry appended handle dimensions. This removes the panic while preserving baseline estimation behavior.

I agree handle-predicate selectivity recovery can be explored as a follow-up optimization, but I did not include it in this bugfix to avoid further plan instability.

File: pkg/planner/core/stats.go [hunk 2]
```diff
@@ -419,7 +419,23 @@ func detachCondAndBuildRangeForPath(
...
 		indexCols = indexCols[0:len(path.Index.Columns)]
 	}
-	count, err := cardinality.GetRowCountByIndexRanges(sctx, histColl, path.Index.ID, path.Ranges, indexCols)
+	estimateRanges := path.Ranges
+	if len(indexCols) < len(path.IdxCols) {
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/stats.go:425]: Thanks, addressed in the latest commit (9cbd2381049).

I now gate the rebuild by actual range width, not only by column-slice length:
- keep `indexCols` as estimation columns;
- check each `path.Ranges` width (`LowVal`/`HighVal`) against `len(indexCols)`;
- rebuild `estimateRanges` only when an appended handle dimension is actually present in ranges.

So we no longer pay an unnecessary second detach when ranges are already index-width aligned.

**Comment by hawkingrei** [comment]
@pantheon-bot review

File: docs/note/planner/rule/rule_ai_notes.md [hunk 3]
```diff
@@ -45,3 +45,43 @@ Test and verification:
...
+- Fix at the source invariant instead of adding defensive checks in lower-level cardinality code.
+- Keep row-count estimation on index-definition columns (`indexCols`) to preserve existing plan-estimation behavior.
+- In `pkg/planner/core/stats.go`, when execution ranges carry appended handle dimensions, rebuild an `estimateRanges` view using `indexCols` only, then call `GetRowCountByIndexRanges` with `(estimateRanges, indexCols)`.
+- This removes range/column dimension mismatch without changing the baseline estimation column set.
+
+Test and verification:
+- Add regression test `TestIndexRangeEstimationWithAppendedHandleColumn` in `pkg/planner/cardinality/selectivity_test.go`.
+- The test uses a non-unique index + PK handle shape and mocked stats (`missing index stats + available column stats`) and verifies `EXPLAIN` does not panic.
+- Reference command:
+  - `GOROOT=/Users/weizhenwang/.gvm/gos/go1.25.7 GOPATH=/Users/weizhenwang/go GOMODCACHE=/Users/weizhenwang/go/pkg/mod GOCACHE=/Users/weizhenwang/Library/Caches/go-build /Users/weizhenwang/.gvm/gos/go1.25.7/bin/go test ./pkg/planner/cardinality -run TestIndexRangeEstimationWithAppendedHandleColumn --tags=intest -count=1`
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply docs/note/planner/rule/rule_ai_notes.md]: Thanks for the suggestion. Updated in commit aaff0180d05: the note now uses the portable command `go test ./pkg/planner/cardinality -run TestIndexRangeEstimationWithAppendedHandleColumn --tags=intest -count=1` and removes local absolute paths and env overrides.

File: pkg/planner/core/stats.go [hunk 4]
```diff
@@ -416,10 +416,36 @@ func detachCondAndBuildRangeForPath(
 		}
 	}
 	indexCols := path.IdxCols
-	if len(indexCols) > len(path.Index.Columns) { // remove clustered primary key if it has been added to path.IdxCols
+	if len(indexCols) > len(path.Index.Columns) {
+		// Trim appended handle dimensions and keep only real index-definition columns for stats estimation.
 		indexCols = indexCols[0:len(path.Index.Columns)]
 	}
```
Comment (winoros) [inline pkg/planner/core/stats.go:423]: If we prepare two kinds of slices here, do we need to rebuild the range?

Comment (hawkingrei) [reply pkg/planner/core/stats.go:423]: No, I have refactored this code. Now, we try to prune the origin range into estimate range.

File: pkg/planner/core/stats.go [hunk 5]
```diff
@@ -416,14 +417,54 @@ func detachCondAndBuildRangeForPath(
...
+	estimateRanges := make([]*ranger.Range, 0, len(ranges))
+	for _, ran := range ranges {
+		newRange := &ranger.Range{
+			LowVal:      make([]types.Datum, 0, keepColCnt),
+			HighVal:     make([]types.Datum, 0, keepColCnt),
+			Collators:   make([]collate.Collator, 0, keepColCnt),
+			LowExclude:  ran.LowExclude,
+			HighExclude: ran.HighExclude,
+		}
+		for _, ran := range ranges {
```
Comment (AilinKid) [inline pkg/planner/core/stats.go]: why loop ranges double times？dupliated with L448？

**Review by AilinKid — APPROVED** [review]

File: pkg/planner/core/stats.go (hunk 5 above)
Comment (hawkingrei) [reply pkg/planner/core/stats.go]: I have remove the second loop.
