### PR TITLE
util,executor: Fix incorrect execution info issue of pessimistic lock error

### LINKED ISSUE #59356: execution info in plan is wrong when encounters a pessimistic lock error and then retries execution
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepare:

```sql
create table t (id bigint, b int, unique index(id));
```

Execute the following two SQL statements simultaneously in 2 session:

```sql
begin;
insert into t values (1,1) on duplicate key update b=b+1;
select sleep(1);
commit;
```

Then you will see a slow log like the following:


<img width="2635" alt="Image" src="https://github.com/user-attachments/assets/ea19e1c4-0219-49d4-86e7-ee417a05c43e" />

the plan is:

```sql

| id       | estRows | estCost | actRows | task | access object | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | operator info | memory    | disk  |
| Insert_1 | 0.00    | 0.00    | 0       | root |               | total_time:2.03s, total_open:19.8µs, total_close:4.25µs, loops:7, prepare: 2.02s, check_insert: {total_time: 9.42ms, mem_insert_time: 113.7µs, prefetch: 9.31ms, rpc:{BatchGet:{num_rpc:5, total_time:1.79ms},ResolveLock:{num_rpc:1, total_time:7.42ms}, time_detail: {total_kv_read_wall_time: 429µs, tikv_wall_time: 585µs}, resolve_lock_time:7.42ms, scan_detail: {total_process_keys: 4, total_process_keys_size: 170, total_keys: 12, get_snapshot_time: 62µs, rocksdb: {key_skipped_count: 8, block: {}}}}}, lock_keys: {time:287.3µs, region:1, keys:2, slowest_rpc: {total: 0.000s, region_id: 16, store: 127.0.0.1:20160, time_detail: {tikv_wall_time: 112.2µs}, scan_detail: {get_snapshot_time: 18.7µs, rocksdb: {key_skipped_count: 9, block: {}}}, }, lock_rpc:261.375µs, rpc_count:1} | N/A           | 144 Bytes | N/A   |
```

Related slow log:

```log
# Time: 2025-02-10T13:23:28.275639+08:00
# Txn_start_ts: 455911671651893252
# User@Host: root[root] @ 127.0.0.1 [127.0.0.1]
# Conn_ID: 4271898648
# Exec_retry_time: 1.004038917 Exec_retry_count: 1
# Query_time: 1.013477084
# Parse_time: 0
# Compile_time: 0.000092084
# Rewrite_time: 0.000027042
# Optimize_time: 0.000064625
# Wait_TS: 0
# LockKeys_time: 1.012846
# DB: test
# Is_internal: false
# Digest: df2024ca5c53ee304fc0bac7c12b441005286a1242483273339166ebe112ec94
# Mem_max: 8336
# Prepared: false
# Plan_from_cache: false
# Plan_from_binding: false
# Has_more_results: false
# KV_total: 1.021116583
# PD_total: 0
# Backoff_total: 0
# Unpacked_bytes_sent_tikv_total: 2015
# Unpacked_bytes_received_tikv_total: 1505
# Unpacked_bytes_sent_tikv_cross_zone: 0
# Unpacked_bytes_received_tikv_cross_zone: 0
# Unpacked_bytes_sent_tiflash_total: 0
# Unpacked_bytes_received_tiflash_total: 0
# Unpacked_bytes_sent_tiflash_cross_zone: 0
# Unpacked_bytes_received_tiflash_cross_zone: 0
# Write_sql_response_total: 0
# Result_rows: 0
# Succ: true
# IsExplicitTxn: true
# IsSyncStatsFailed: false
# Plan: tidb_decode_plan('sAaIMAkyN18xCTAJMAlOL0EJMAl0b3RhbF90aW1lOjIuMDNzLCAJEihvcGVuOjE5LjjCtRUUJGNsb3NlOjQuMjUFFaBsb29wczo3LCBwcmVwYXJlOiAyLjAycywgY2hlY2tfaW5zZXJ0OiB7dBljLCA5LjQybXMsIG1lbQ0hCXwUIDExMy43BVcccHJlZmV0Y2gBLQQzMQEtSHJwYzp7QmF0Y2hHZXQ6e251bV8BEwA1EawFvkgxLjc5bXN9LFJlc29sdmVMb2NrGSsAMTIrAAA3BYUIfSwgATkYX2RldGFpbBWoKGt2X3JlYWRfd2FsLRgMIDQyOQWaDHRpa3YuGAAENTghCQx9LCByCXQQX2xvY2sJjgljFCwgc2Nhbj5iADhwcm9jZXNzX2tleXM6IDQRmy4XACRfc2l6ZTogMTcwER4JLTgxMiwgZ2V0X3NuYXBzaG8xPQQ2MgWggHJvY2tzZGI6IHtrZXlfc2tpcHBlZF9jb3VudDogOCwgYgGgDDoge30BAQQsIAEODVgAeyEKFDoyODcuMwlKEGVnaW9uITcFeCQyLCBzbG93ZXN0JXkAICnTJDogMC4wMDBzLCAJLyxfaWQ6IDE2LCBzdG9BDjQxMjcuMC4wLjE6MjAxNgHKBGltLm8BOk4BDDExMi4ByAB9PjYBSvEABDE4TS1y8wAAOTLzAAQsIBH0QT0UMjYxLjM3IcAALEFgLSZAMX0JMTQ0IEJ5dGVzCU4vQQo=')
# Binary_plan: tidb_decode_binary_plan('ugaoCrUGCghJbnNlcnRfMTgBQAFSA04vQVpCdG90YWxfdGltZToyLjAzcywgdAUSKG9wZW46MTkuOMK1FRQkY2xvc2U6NC4yNQUVgGxvb3BzOjditQNwcmVwYXJlOiAyLjAycywgY2hlY2tfaQVuCDogex1kLCA5LjQybXMsIG1lbQ0hCX0UIDExMy43BVgccHJlZmV0Y2gBLQQzMQEtSHJwYzp7QmF0Y2hHZXQ6e251bV8BEwQ1LA2tBb9IMS43OW1zfSxSZXNvbHZlTG9jaxkrADEyKwAANwWFCH0sIAE5GF9kZXRhaWwVqChrdl9yZWFkX3dhbC0ZDCA0MjkFmgx0aWt2LhgABDU4IQoMfSwgcgl0EF9sb2NrCY4JYxQsIHNjYW4+YgA4cHJvY2Vzc19rZXlzOiA0EZsuFwAkX3NpemU6IDE3MBEeCS04MTIsIGdldF9zbmFwc2hvMT0ENjIFoIByb2Nrc2RiOiB7a2V5X3NraXBwZWRfY291bnQ6IDgsIGIBoAw6IHt9AQEIYpUCAQ8NWQB7IQsUOjI4Ny4zCUsQZWdpb24hOAV5JDIsIHNsb3dlc3Qlei3UJDogMC4wMDBzLCAJLyxfaWQ6IDE2LCBzdG9BDzQxMjcuMC4wLjE6MjAxNgHLBGltLnABOk8BDDExMi4ByQB9PjcBSvIABDE4TS5y9AAAOTL0ABAsIH0sIAX0QT4UMjYxLjM3IcEALEFhLSdEMX1wkAF4////////////ARgB')
# Resource_group: default
# Request_unit_read: 2.377593994140625
# Request_unit_write: 5.1
 insert into t values (1,1) on duplicate key update b=b+1;
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

### 3. What did you see instead (Required)

The slow query total `Query_time` is 1.013477084s, but in the plan execution info, `total_time:2.03s` is wrong.

BTW, from the execution plan and the slow logs, it is hard to quickly know that this slow query is caused by waiting for the lock and not by the database slowing down, so it is recommended to refine the runtime stats for the lock 


### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->


```sql
> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v9.0.0-alpha-225-gd7a8b679ad             |
| Edition: Community                                        |
| Git Commit Hash: d7a8b679ad730794a46086f387c510e9d67cc692 |
| Git Branch: master                                        |
| UTC Build Time: 2025-02-10 05:12:05                       |
| GoVersion: go1.23.6                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by yibin87**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: close #59356 

Problem Summary:
In #54004, some stats' clone operations are removed. However, the removal of clone operation in RegisterStats function introduced new issue:
https://github.com/pingcap/tidb/blob/d13e52ed6e22cc5789bed7c64c861578cd2ed55b/pkg/util/execdetails/execdetails.go#L1462 
Because, for insert operator's stats, it keeps a pointer to the BasicRuntimeStats which is unique for all executors with the same executor_id. For issue 59356, tidb first tries the insert executor, but fails with write conflicts,registering the executor stats in close function. Then it retries, using a new insert executor, while still has a pointer to the registered BasicRuntimeStats. Finally, when the new insert executor closes, it register the stats also, triggering the BasicRuntimeStats' merge operation which now is actually a self-merge operation. It leads to the double-calculated execution time issue.
Besides, when retries happen, we reset the collected exec details in statement context, which will drop the execution details for failed tries. 

### What changed and how does it work?
1. Don't actually clone and merge BasicRuntimeStats inside InsertRuntimeStat
2. Don't reset exec details when reseting statement context for retrying.

### Check List

Tests <!-- At least one of them must be included. -->

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Manually started two sessions and execute queries in #59356, confirmed the insert executor's execution time is correct and the lock_keys details are displayed:
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 	id      	task	estRows	operator info	actRows	execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	memory   	disk
	Insert_1	root	0      	N/A          	0      	total_time:982ms, total_open:5.21µs, total_close:2.58µs, loops:4, prepare: 981.1ms, check_insert: {total_time: 903.2µs, mem_insert_time: 72.2µs, prefetch: 831µs, rpc:{BatchGet:{num_rpc:4, total_time:765.1µs}, time_detail: {total_kv_read_wall_time: 229.4µs, tikv_wall_time: 274.9µs}, scan_detail: {total_process_keys: 4, total_process_keys_size: 170, total_keys: 5, get_snapshot_time: 40.8µs, rocksdb: {key_skipped_count: 1, block: {}}}}}, lock_keys: {time:981ms, region:2, keys:4, slowest_rpc: {total: 0.000s, region_id: 16, store: 127.0.0.1:20160, time_detail: {tikv_wall_time: 52.2µs}, scan_detail: {get_snapshot_time: 8.33µs, rocksdb: {delete_skipped_count: 2, key_skipped_count: 5, block: {}}}, }, lock_rpc:980.877749ms, rpc_count:2, retry_count:1}	144 Bytes	N/A |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > <!-- Or your custom  "No need to test" reasons -->

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that insert operator's execution time may be incorrect when retrying pessimistic locks.
```

### CODE REVIEW

File: pkg/util/execdetails/execdetails.go [hunk 1]
```diff
@@ -1542,15 +1542,8 @@ func (e *BasicRuntimeStats) GetActRows() int64 {
...
-	result := &BasicRuntimeStats{}
-	result.executorCount.Store(e.executorCount.Load())
-	result.loop.Store(e.loop.Load())
-	result.consume.Store(e.consume.Load())
-	result.open.Store(e.open.Load())
-	result.close.Store(e.close.Load())
-	result.rows.Store(e.rows.Load())
-	return result
+func (*BasicRuntimeStats) Clone() RuntimeStats {
+	panic("BasicRuntimeStats should not implement Clone function")
```
Comment (crazycs520) [inline pkg/util/execdetails/execdetails.go:1546]: This looks a little strange, and it's too exaggerated to panic.

Comment (yibin87) [reply pkg/util/execdetails/execdetails.go:1546]: Actually, it is dangerous to clone BasicRuntimeStats, since it is unique for executors with the same executor id. Add panic here to avoid such operations.

File: pkg/util/execdetails/execdetails.go [hunk 2]
```diff
@@ -1542,15 +1542,8 @@ func (e *BasicRuntimeStats) GetActRows() int64 {
...
-func (e *BasicRuntimeStats) Clone() RuntimeStats {
-	result := &BasicRuntimeStats{}
-	result.executorCount.Store(e.executorCount.Load())
-	result.loop.Store(e.loop.Load())
-	result.consume.Store(e.consume.Load())
-	result.open.Store(e.open.Load())
-	result.close.Store(e.close.Load())
-	result.rows.Store(e.rows.Load())
-	return result
+func (*BasicRuntimeStats) Clone() RuntimeStats {
```
Comment (XuHuaiyu) [inline pkg/util/execdetails/execdetails.go:1545]: It'll be better to add a comment for why clone should not be invoked for this func.

Comment (yibin87) [reply pkg/util/execdetails/execdetails.go:1547]: Ok, add it.

**Review by XuHuaiyu — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
