### PR TITLE
lightning: when lightning exits while processing the task, it should return 1

### LINKED ISSUE #53384: should not return zero when lightning exits while processing the task
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start tidb cluster
2. start lightning server
3. send task to lightning server
4. send `SIGINT` to lightning server

### 2. What did you expect to see? (Required)
lightnng server exit with status 1

### 3. What did you see instead (Required)
lightnng server exit with status 0

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by zeminzhou**
### What problem does this PR solve?

Issue Number: close #53384 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. start tidb cluster
2. start lightning server
3. send import task to lightning server
4. send `SIGINT` to lightning server
5. lightning server exit with error code 1
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: lightning/cmd/tidb-lightning/main.go [hunk 1]
```diff
@@ -99,7 +99,9 @@ func main() {
 	finished := true
 	if common.IsContextCanceledError(err) {
 		err = nil
-		finished = false
+		if app.TaskCanceled() {
```
Comment (lance6716) [inline lightning/cmd/tidb-lightning/main.go:102]: I see lightning CI failed. To reduce behaviour change, you can check it's ServerMode

Comment (zeminzhou) [reply lightning/cmd/tidb-lightning/main.go:102]: It was fixed, thanks! PTAL~

Comment (lance6716) [reply lightning/cmd/tidb-lightning/main.go:102]: For non-server mode it's a compatibility change. I need to ask PM about it tomorrow. It may break user's script.

Comment (D3Hunter) [reply lightning/cmd/tidb-lightning/main.go:102]: anything affected by current behavior of lightning? any workaround?

Comment (zeminzhou) [reply lightning/cmd/tidb-lightning/main.go:102]: In cloud, when k8s' job controller wants to schedule lightning pod to other node, job controller will send `SIGINT` to lightning pod. Because lightning pod returns 0, job controller think the job is done and will not schedule it.

Comment (zeminzhou) [reply lightning/cmd/tidb-lightning/main.go:102]: I added compatibility with the previous non-server mode. /cc @lance6716

**Review by lance6716 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
there's no test, so i unchecked `unit test`
