### PR TITLE
global_sort: fix incorrect write speed metrics in merge-sort step

### LINKED ISSUE #62870: Merge sort speed metrics is inaccurate in grafana
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
When adding index with dxf, the merge sort metrics is inaccurate. The write speed and read speed don't match the k8s monitor.  The reason is that s3 uploader uploads in multi parts,  when we call the upload interface, it only writes to the buffer memory and does not wait until the data is actually uploaded. 
https://github.com/fzzf678/tidb/blob/35785746b2aeccd7aec807a7170326db62e23180/pkg/lightning/backend/external/onefile_writer.go#L247
Current implementations mostly count the write speed in memory. But the real upload is done in the background, it's hard to get the real upload speed, maybe we can estimate it by counting the upload speed over a period of time.

Image
Image

Image

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #62870

Problem Summary:

### What changed and how does it work?

The _Write to Cloud Storage Rate_ panel shows the speed of writing data to cloud storage.
For the read index step, this works well because the speed is measured each time a file is written; files are small and many writers upload in parallel, so we can get many speed, this is also why a histogram metric is used.
However, in the merge sort step, many small files are merged into larger ones. The merging process is streaming, so the speed cannot be measured accurately in the same way, the previous https://github.com/pingcap/tidb/pull/60971 is incorrect. Therefore, we need a counter metric to record the written bytes and calculate the speed in a while.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
After this pr, the written speed in _Write to Cloud Storage Rate_ and k8s are close, 129MiB/s vs 137MiB/s
截屏2025-08-12 14 47 17
截屏2025-08-12 14 47 36
Read speed:
截屏2025-08-12 16 13 06
截屏2025-08-12 16 12 49

And for the cluster, this pr can also works:
截屏2025-08-13 18 35 10
截屏2025-08-13 18 40 23
截屏2025-08-13 18 37 23

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/backend/external/onefile_writer.go [hunk 1]
```diff
@@ -257,10 +256,11 @@ func (w *OneFileWriter) doWriteRow(ctx context.Context, idxKey, idxVal []byte) e
 	}
 	w.totalCnt += 1
 	w.totalSize += uint64(keyLen + len(idxVal))
-	writeDuration := time.Since(writeStartTime)
-	metrics.GlobalSortWriteToCloudStorageDuration.WithLabelValues("merge_sort_write").Observe(writeDuration.Seconds())
-	metrics.GlobalSortWriteToCloudStorageRate.WithLabelValues("merge_sort_write").
-		Observe(float64(length) / 1024.0 / 1024.0 / writeDuration.Seconds())
+	w.writtenBytes += int64(length)
+	if w.writtenBytes >= 16*units.MiB {
+		metrics.MergeSortWriteBytes.Add(float64(w.writtenBytes))
```
Comment (joechenrh) [inline pkg/lightning/backend/external/onefile_writer.go:261]: I've added a label value for written bytes in `mergeOverlappingFilesInternal`, maybe duplicated?🤔
https://github.com/pingcap/tidb/blob/342a4c89a8ee65dc947d9c9e16a7e4ed28cb698b/pkg/ddl/backfilling_merge_sort.go#L95-L107
The difference is that the previous one is a per-task counter, here is a global counter.

**Review by joechenrh — APPROVED** [review]

**Comment by fzzf678** [comment]
@XuHuaiyu @zimulala please help take a look

**Comment by fzzf678** [comment]
> Do we need to update the tidb_with_keyspace_name.json in metrics/nextgengrafana?

update in https://github.com/pingcap/tidb/pull/62847/commits/6454e39b61893f583a86113208f029d5f713975b, PTAL again

**Review by XuHuaiyu — APPROVED** [review]
