### PR TITLE
planner: check DROP privilege for TRUNCATE PARTITION statement (#64024)

### LINKED ISSUE #64024: Privileges for TRUNCATE PARTITION and DROP PARTITION are inconsistent
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
-- connect as root
CREATE DATABASE test;
CREATE TABLE test.t1 (
    id INT,
    year_col INT
)
PARTITION BY RANGE (year_col) (
    PARTITION p0 VALUES LESS THAN (1991),
    PARTITION p1 VALUES LESS THAN (1995),
    PARTITION p2 VALUES LESS THAN (1999),
    PARTITION p3 VALUES LESS THAN (2003),
    PARTITION p4 VALUES LESS THAN (2007)
);
INSERT INTO test.t1 VALUES (100, 100);
CREATE USER foo;
GRANT ALTER ON test.t1 TO foo;

-- connect as foo
ALTER TABLE test.t1 TRUNCATE PARTITION p0;
ALTER TABLE test.t1 DROP PARTITION p0;
```
### 2. What did you expect to see? (Required)
When the user `foo` only has `ALTER` privilege on `t1`:
```
MySQL [(none)]> ALTER TABLE test.t1 TRUNCATE PARTITION p0;
ERROR 1142 (42000): DROP command denied to user 'foo'@'%' for table 't1'

MySQL [(none)]> ALTER TABLE test.t1 DROP PARTITION p0;
ERROR 1142 (42000): DROP command denied to user 'foo'@'%' for table 't1'
```
Since TiDB is compatible with MySQL, and MySQL requires `DROP` privilege for both `TRUNCATE PARTITION` and `DROP PARTITION`, TiDB is expected to require `DROP` privilege for these two commands as well.

### 3. What did you see instead (Required)
When the user `foo` only has `ALTER` privilege on `t1`:
```
MySQL [(none)]> ALTER TABLE test.t1 TRUNCATE PARTITION p0;
Query OK, 0 rows affected (0.021 sec)

MySQL [(none)]> ALTER TABLE test.t1 DROP PARTITION p0;
ERROR 1142 (42000): DROP command denied to user 'foo'@'%' for table 't1'
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v9.0.0-beta.1
Edition: Community
Git Commit Hash: 7aff918dcbfa6facf2adef9ade9961c40f217421
Git Branch: HEAD
UTC Build Time: 2025-03-24 09:09:55
GoVersion: go1.23.7
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

### PR DESCRIPTION
**Pull request by jjshanks**
### What problem does this PR solve?

Issue Number: close #64024

Problem Summary:

ALTER TABLE TRUNCATE PARTITION and ALTER TABLE DROP PARTITION have inconsistent privilege requirements. Currently, TRUNCATE PARTITION only requires ALTER privilege, while DROP PARTITION correctly requires DROP privilege. This is inconsistent with MySQL behavior, where both operations require DROP privilege since they both perform destructive data operations.

### What changed and how does it work?

Added privilege checking for ALTER TABLE TRUNCATE PARTITION to require DROP privilege, making it consistent with DROP PARTITION.

Changes:
- pkg/planner/core/planbuilder.go: Added a new else if branch in buildDDL() to check for ast.AlterTableTruncatePartition and enforce DROP privilege requirement, mirroring the existing logic for ast.AlterTableDropPartition
- tests/integrationtest/t/privilege/privileges.test: Added integration test to verify that both TRUNCATE PARTITION and DROP PARTITION require DROP privilege

How it works:
When the planner encounters an ALTER TABLE TRUNCATE PARTITION statement, it now builds visitInfo with mysql.DropPriv requirement, generating a "DROP command denied" error if the user lacks the privilege.

### Check List

Tests 

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

This is a breaking change for users who currently rely on TRUNCATE PARTITION working with only ALTER privilege. They will now need DROP privilege.

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

Users who previously could truncate partitions with only ALTER privilege now need DROP privilege

Improves MySQL compatibility by aligning privilege requirements

### Release note

```release-note
Fix: `ALTER TABLE TRUNCATE PARTITION` now correctly requires `DROP` privilege, consistent with MySQL and `DROP PARTITION` behavior. Previously, it incorrectly allowed the operation with only `ALTER` privilege.
```

### CODE REVIEW

File: pkg/planner/core/planbuilder.go [hunk 1]
```diff
@@ -5335,6 +5335,13 @@ func (b *PlanBuilder) buildDDL(ctx context.Context, node ast.DDLNode) (base.Plan
 				}
 				b.visitInfo = appendVisitInfo(b.visitInfo, mysql.DropPriv, v.Table.Schema.L,
 					v.Table.Name.L, "", authErr)
+			} else if spec.Tp == ast.AlterTableTruncatePartition {
+				if b.ctx.GetSessionVars().User != nil {
+					authErr = plannererrors.ErrTableaccessDenied.GenWithStackByArgs("DROP", b.ctx.GetSessionVars().User.AuthUsername,
+						b.ctx.GetSessionVars().User.AuthHostname, v.Table.Name.L)
+				}
+				b.visitInfo = appendVisitInfo(b.visitInfo, mysql.DropPriv, v.Table.Schema.L,
+					v.Table.Name.L, "", authErr)
```
Comment (D3Hunter) [inline pkg/planner/core/planbuilder.go]: they can share the same branch as previous `spec.Tp == ast.AlterTableDropPartition`, it's the same

Comment (jjshanks) [reply pkg/planner/core/planbuilder.go]: Good catch, was a bit to laser focused

**Comment by lance6716** [comment]
please help to triage the issue. Not sure it should be cherrypicked
cc @D3Hunter @King-Dylan

**Review by YangKeao — APPROVED** [review]
LGTM
