### PR TITLE
executor: return proper error for LOAD DATA with AUTO_RANDOM column

### LINKED ISSUE #65585: Bad error message `runtime error: index out of range [0] with length 0` when using `LOAD DATA LOCAL INFILE` to a table with `AUTO_RANDOM` column without `allow_auto_random_explicit_insert`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<sub>(internal reference: TCID-12317 = TCOC-4672)</sub>

```sh
echo '1,2' > /tmp/a.csv
mysql -u root -h 127.0.0.1 -P 4000 --local-infile
```
```sql
use test;
create table a (a bigint primary key auto_random(5), b int);
load data local infile '/tmp/a.csv' into table a fields terminated by ',';
```

### 2. What did you expect to see? (Required)

```
ERROR 8216 (HY000): Invalid auto random: Explicit insertion on auto_random column is disabled. Try to set @@allow_auto_random_explicit_insert = true.
```

### 3. What did you see instead (Required)

```
ERROR 1105 (HY000): runtime error: index out of range [0] with length 0
```

### 4. What is your TiDB version? (Required)

v8.5.4

### PR DESCRIPTION
**Pull request by Milad93R**
### What problem does this PR solve?

Issue Number: close #65585

Problem Summary: When using `LOAD DATA LOCAL INFILE` on a table with `AUTO_RANDOM` column while `allow_auto_random_explicit_insert` is disabled, TiDB returns a runtime panic (`index out of range [0] with length 0`) instead of the expected error 8216.

### What changed and how does it work?

Added a check in `parserData2TableData()` to detect `ErrInvalidAutoRandom` and return it as a real error instead of treating it as a warning. Previously, the error was converted to a warning in non-restrictive mode, and a nil row was returned, which later caused a panic when looking up the index.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix LOAD DATA LOCAL INFILE to return proper error 8216 when inserting explicit values into AUTO_RANDOM column with allow_auto_random_explicit_insert disabled, instead of a runtime panic.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * LOAD DATA now correctly returns an error when explicit values are supplied for AUTO_RANDOM columns without permission, instead of falling back to a warning.

* **Tests**
  * Added a test validating the AUTO_RANDOM explicit-insert error for LOAD DATA.

* **Chores**
  * Updated test configuration to adjust sharding for the load-data test suite.

### CODE REVIEW

**Comment by joechenrh** [comment]
~~`IMPORT INTO` can import the file successfully 🤔~~
Oh, it doesn't check `allow_auto_random_explicit_insert`

**Comment by lance6716** [comment]
CI failed:

```
Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents with ctrl-D as ending):
diff --git a/pkg/executor/test/loaddatatest/BUILD.bazel b/pkg/executor/test/loaddatatest/BUILD.bazel
index 88853b38ca..a9a029c3ef 100644
--- a/pkg/executor/test/loaddatatest/BUILD.bazel
+++ b/pkg/executor/test/loaddatatest/BUILD.bazel
@@ -9,7 +9,7 @@ go_test(
     ],
     flaky = True,
     race = "on",
-    shard_count = 12,
+    shard_count = 13,
     deps = [
         "//pkg/config",
         "//pkg/executor",

```

File: pkg/executor/load_data.go
Comment (lance6716) [inline pkg/executor/load_data.go]: I found this issue is caused by this TODO which I left some years ago 😢 

@joechenrh Do you think we should open another PR, to let caller skip `nil` row?

File: pkg/executor/test/loaddatatest/load_data_test.go [hunk 1]
```diff
@@ -495,3 +495,39 @@ func TestFix56408(t *testing.T) {
...
+			return reader, nil
+		},
+		Wg: &sync.WaitGroup{},
+	}
+	ctx.SetValue(executor.LoadDataReaderBuilderKey, readerBuilder)
+
+	// This should return error 8216, not a runtime panic
+	err := tk.ExecToErr("load data local infile '/tmp/test.csv' into table t_auto_random fields terminated by ','")
+	require.Error(t, err)
+	require.Contains(t, err.Error(), "auto_random")
```
Comment (lance6716) [inline pkg/executor/test/loaddatatest/load_data_test.go]: you can cast the error like other test cases

```
	terr = errors.Cause(err).(*terror.Error)
	require.Equal(t, errors.ErrCode(errno.WarnDataTruncated), terr.Code())
```

**Review by lance6716 — APPROVED** [review]

File: pkg/executor/load_data.go
Comment (joechenrh) [reply pkg/executor/load_data.go]: I'm wondering when we will reach L591 after this PR. Maybe we should return `newRow, nil` for restrictive data interpretation error 🤔?

Comment (lance6716) [reply pkg/executor/load_data.go]: `newRow` may still have mismatched length. Maybe a row of NULL?

**Comment by Milad93R** [comment]
C:/Program Files/Git/retest-required

**Comment by Milad93R** [comment]
C:/Program Files/Git/test unit-test

File: pkg/executor/load_data.go [hunk 2]
```diff
@@ -578,6 +579,12 @@ func (w *encodeWorker) parserData2TableData(
 	// a new row buffer will be allocated in getRow
 	newRow, err := w.getRow(ctx, row)
 	if err != nil {
+		// ErrInvalidAutoRandom should always be returned as a real error,
+		// not treated as a warning, because returning nil row causes panic
+		// when looking up index. See https://github.com/pingcap/tidb/issues/65585
+		if dbterror.ErrInvalidAutoRandom.Equal(err) {
+			return nil, err
+		}
```
Comment (kennytm) [inline pkg/executor/load_data.go:590]: :thinking: feels strange to only special case for the ErrInvalidAutoRandom

i think we should always `return nil, err` regardless of error type in strict mode, and discard the row in IGNORE mode

@joechenrh why is the current behavior like this :confused:

Comment (joechenrh) [reply pkg/executor/load_data.go:590]: > why is the current behavior like this

😵‍💫 I don't know about this part
