### PR TITLE
executor: add a `scannedKeys` in `indexWorker`, let pushLimited supports partition table

### LINKED ISSUE #32516: sub select LIMIT does not work as expected with dynamic partition prune mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE pt (
  `id` bigint(20) DEFAULT NULL,
  a int,
  KEY (a))
PARTITION BY RANGE(id)
(PARTITION p1 VALUES LESS THAN (4),
 PARTITION p2 VALUES LESS THAN (8),
 PARTITION p3 VALUES LESS THAN (12),
 PARTITION p4 VALUES LESS THAN (MAXVALUE));
insert into pt values (1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(11,11),(12,12),(13,13),(14,14),(15,15),(16,16);
SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t;
EXPLAIN SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t;
```

I would expect it to only count 2 rows due to the `LIMIT 2`, but it gives 8 (2 from each partition?)

### 2. What did you expect to see? (Required)

```
--------------
SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t
--------------

+----------+
| COUNT(*) |
+----------+
|        2 |
+----------+
1 row in set (0,00 sec)

--------------
EXPLAIN SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t
--------------

+----------------------------------+---------+-----------+----------------------+----------------------------------------------+
| id                               | estRows | task      | access object        | operator info                                |
+----------------------------------+---------+-----------+----------------------+----------------------------------------------+
| StreamAgg_11                     | 1.00    | root      |                      | funcs:count(1)->Column#4                     |
| └─IndexLookUp_27                 | 2.00    | root      | partition:all        | limit embedded(offset:0, count:2)            |
|   ├─Limit_26(Build)              | 2.00    | cop[tikv] |                      | offset:0, count:2                            |
|   │ └─IndexRangeScan_18          | 2.00    | cop[tikv] | table:pt, index:a(a) | range:[1,15], keep order:false, stats:pseudo |
|   └─TableRowIDScan_19(Probe)     | 2.00    | cop[tikv] | table:pt             | keep order:false, stats:pseudo               |
+----------------------------------+---------+-----------+----------------------+----------------------------------------------+
5 rows in set (0,00 sec)
```

### 3. What did you see instead (Required)

```
--------------
SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t
--------------

+----------+
| COUNT(*) |
+----------+
|        8 |
+----------+
1 row in set (0,00 sec)

--------------
EXPLAIN SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t
--------------

+----------------------------------+---------+-----------+----------------------+----------------------------------------------+
| id                               | estRows | task      | access object        | operator info                                |
+----------------------------------+---------+-----------+----------------------+----------------------------------------------+
| StreamAgg_11                     | 1.00    | root      |                      | funcs:count(1)->Column#4                     |
| └─IndexLookUp_27                 | 2.00    | root      | partition:all        | limit embedded(offset:0, count:2)            |
|   ├─Limit_26(Build)              | 2.00    | cop[tikv] |                      | offset:0, count:2                            |
|   │ └─IndexRangeScan_18          | 2.00    | cop[tikv] | table:pt, index:a(a) | range:[1,15], keep order:false, stats:pseudo |
|   └─TableRowIDScan_19(Probe)     | 2.00    | cop[tikv] | table:pt             | keep order:false, stats:pseudo               |
+----------------------------------+---------+-----------+----------------------+----------------------------------------------+
5 rows in set (0,00 sec)
```

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v5.5.0-alpha
Edition: Community
Git Commit Hash: 171a35486036e8ea5b168c2d4d29f4639df1611d
Git Branch: heads/refs/tags/v5.5.0-alpha
UTC Build Time: 2022-02-20 14:52:57
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #32516

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
add a scannedKeys in indexWorker, let pushLimited supports partition table
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @mjonss @chrysan @Arenatlx @ xuyifangreeneyes
PTAL

**Comment by Defined2014** [comment]
/cc @mjonss @chrysan @arenatlx @xuyifangreeneyes
PTAL

**Comment by Defined2014** [comment]
/cc @Reminiscent @rebelice
PTAL

File: planner/core/integration_partition_test.go [hunk 1]
```diff
@@ -1136,3 +1136,31 @@ func TestIssue27532(t *testing.T) {
...
+		"  a int," +
+		"  KEY (a))" +
+		"PARTITION BY RANGE(id)" +
+		"(PARTITION p1 VALUES LESS THAN (4)," +
+		" PARTITION p2 VALUES LESS THAN (8)," +
+		" PARTITION p3 VALUES LESS THAN (12)," +
+		" PARTITION p4 VALUES LESS THAN (MAXVALUE));")
+	tk.MustExec("insert into pt values (1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(11,11),(12,12),(13,13),(14,14),(15,15),(16,16);")
+	tk.MustQuery("SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t;").Check(testkit.Rows("2"))
+	tk.MustQuery("EXPLAIN SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2;").Check(testkit.Rows(
```
Comment (xuyifangreeneyes) [inline planner/core/integration_partition_test.go:1160]: Maybe we can use `explain format = 'brief' select ...` here. In this way, plan IDs don't appear(`Limit_9` -> `Limit`). Some Changes in planner may change plan IDs but don't change the plan itself. We don't need to modify explain results in the test cases if we use brief mode.

File: planner/core/task.go [hunk 2]
```diff
@@ -1256,6 +1257,13 @@ func (p *PhysicalLimit) sinkIntoIndexLookUp(t task) bool {
 	if !isTableScan {
 		return false
 	}
+	// We can't sink Limit into IndexLookUpReader when it scans a partition table in dynamic prune mode
+	// https://github.com/pingcap/tidb/issues/32516
+	if table, ok := p.ctx.GetInfoSchema().(infoschema.InfoSchema).TableByID(ts.Table.ID); ok {
```
Comment (xuyifangreeneyes) [inline planner/core/task.go:1262]: It seems that `GetInfoSchema` is deprecated. Can we use  `TxnManager.GetTxnInfoSchema` instead?

**Review by xuyifangreeneyes — COMMENTED** [review]
rest LGTM

**Review by xuyifangreeneyes — APPROVED** [review]

File: planner/core/task.go [hunk 3]
```diff
@@ -1256,6 +1256,11 @@ func (p *PhysicalLimit) sinkIntoIndexLookUp(t task) bool {
 	if !isTableScan {
 		return false
 	}
+	// We can't sink Limit into IndexLookUpReader when it scans a partition table in dynamic prune mode
+	// https://github.com/pingcap/tidb/issues/32516
+	if p.ctx.GetSessionVars().UseDynamicPartitionPrune() && ts.Table.Partition != nil {
```
Comment (mjonss) [inline planner/core/task.go:1261]:
```suggestion
	if ts.Table.Partition != nil && !ts.isPartition {
```
the ts.isPartition should be set if the table is using static prune mode

File: planner/core/integration_partition_test.go [hunk 4]
```diff
@@ -1136,3 +1136,31 @@ func TestIssue27532(t *testing.T) {
...
+
+func TestIssue32516(t *testing.T) {
+	store, clean := testkit.CreateMockStore(t)
+	defer clean()
+
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("create database issue_32516")
+	defer tk.MustExec(`drop database issue_32516`)
+	tk.MustExec("use issue_32516")
+	tk.MustExec("set @@tidb_partition_prune_mode=dynamic;")
```
Comment (mjonss) [inline planner/core/integration_partition_test.go:1148]:
```suggestion
	tk.MustExec("set @@tidb_partition_prune_mode=dynamic")
```

File: planner/core/integration_partition_test.go [hunk 5]
```diff
@@ -1136,3 +1136,31 @@ func TestIssue27532(t *testing.T) {
...
+	tk.MustExec("CREATE TABLE pt (" +
+		"  `id` bigint(20) DEFAULT NULL," +
+		"  a int," +
+		"  KEY (a))" +
+		"PARTITION BY RANGE(id)" +
+		"(PARTITION p1 VALUES LESS THAN (4)," +
+		" PARTITION p2 VALUES LESS THAN (8)," +
+		" PARTITION p3 VALUES LESS THAN (12)," +
+		" PARTITION p4 VALUES LESS THAN (MAXVALUE));")
```
Comment (mjonss) [inline planner/core/integration_partition_test.go:1157]:
```suggestion
		" PARTITION p4 VALUES LESS THAN (MAXVALUE))")
```

File: planner/core/integration_partition_test.go [hunk 6]
```diff
@@ -1136,3 +1136,31 @@ func TestIssue27532(t *testing.T) {
...
+	tk.MustExec("insert into pt values (1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(11,11),(12,12),(13,13),(14,14),(15,15),(16,16);")
```
Comment (mjonss) [inline planner/core/integration_partition_test.go:1158]:
```suggestion
	tk.MustExec("insert into pt values (1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(11,11),(12,12),(13,13),(14,14),(15,15),(16,16)")
```

File: planner/core/integration_partition_test.go [hunk 7]
```diff
@@ -1136,3 +1136,31 @@ func TestIssue27532(t *testing.T) {
...
+	tk.MustQuery("SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t;").Check(testkit.Rows("2"))
+	tk.MustQuery("EXPLAIN format='brief' SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2;").Check(testkit.Rows(
```
Comment (mjonss) [inline planner/core/integration_partition_test.go:1160]:
```suggestion
	tk.MustQuery("SELECT COUNT(*) FROM (SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2) as t").Check(testkit.Rows("2"))
	tk.MustQuery("EXPLAIN format='brief' SELECT * FROM pt WHERE a BETWEEN 1 AND 15 LIMIT 2").Check(testkit.Rows(
```

**Review by mjonss — COMMENTED** [review]
When running under static prune mode the `explain` contains:
`├─IndexLookUp 2.00 root  limit embedded(offset:0, count:2)`
Does that mean that IndexLookUp should have an internal Limit implementation that could be used too?

File: planner/core/task.go [hunk 8]
```diff
@@ -1256,6 +1256,11 @@ func (p *PhysicalLimit) sinkIntoIndexLookUp(t task) bool {
 	if !isTableScan {
 		return false
 	}
+	// We can't sink Limit into IndexLookUpReader when it scans a partition table in dynamic prune mode
+	// https://github.com/pingcap/tidb/issues/32516
```
Comment (lcwangchao) [inline planner/core/task.go:1260]: I think it is just a quick fix? I think the root cause is that `IndexLookUpExecutor` cannot handle limit push down for partitioned table correctly. I just read the related code found `IndexLookUpExecutor` is doing limit in `indexWorker.extractTaskHandles`:

https://github.com/pingcap/tidb/blob/cc789d078b44d3ab41fd907e784c2e8acf242fad/executor/distsql.go#L907-L909

However for partitioned table, it may have more than one `indexWorker` .

Comment (lcwangchao) [reply planner/core/task.go:1260]: Maybe the best way is move the limit works out of indexWorker

Comment (Defined2014) [reply planner/core/task.go:1260]: Maybe one question here. If we have more than one indexWorkers, how to deal with the `offset` in PushedLimit. I have no idea about it.

**Comment by Defined2014** [comment]
/cc @pingcap/tidb-sql-engine 
PTAL

File: executor/distsql_test.go [hunk 9]
```diff
@@ -316,6 +316,9 @@ func TestPartitionTableIndexLookUpReader(t *testing.T) {
 	tk.MustQuery("select * from t where a>=1 and a<15 order by a").Check(testkit.Rows("1 1", "2 2", "11 11", "12 12"))
 	tk.MustQuery("select * from t where a>=1 and a<15 order by a limit 1").Check(testkit.Rows("1 1"))
 	tk.MustQuery("select * from t where a>=1 and a<15 order by a limit 3").Check(testkit.Rows("1 1", "2 2", "11 11"))
+	tk.MustQuery("select * from t where a>=1 and a<15 limit 3").Check(testkit.Rows("1 1", "2 2", "11 11"))
+	tk.MustQuery("select * from t where a between 1 and 15 limit 3").Check(testkit.Rows("1 1", "2 2", "11 11"))
+	tk.MustQuery("select * from t where a between 1 and 15 limit 3 offset 1").Check(testkit.Rows("2 2", "11 11", "12 12"))
```
Comment (mjonss) [inline executor/distsql_test.go:321]: Will IndexLookupReader always sort the rows, or can these test be instable, due to the rows can be out-of-order or even that "12 12" could be returned instead of "1 1" or "2 2" due to the partitions may be read in parallel?

**Review by mjonss — APPROVED** [review]
LGTM, I only have a question about the stability of the test.

File: executor/distsql_test.go (hunk 9 above)
Comment (Defined2014) [reply executor/distsql_test.go:321]: IndexWorker not work in parallel to deal with the partition table right now. So it always works well.
https://github.com/pingcap/tidb/pull/32548/files#diff-d73d3a1acc55230180db0c3b4fbd89bead84e15845062549e20ec9e810a283b9L591

**Review by zimulala — APPROVED** [review]
LGTM
