### PR TITLE
expression: correct the erroneous scalar function equivalence check

### LINKED ISSUE #53726: `select distinct` produces unexpected result
### 1. Minimal reproduce step (Required)
```sql
create table t1 (c1 int primary key);
insert into t1 (c1) values (575932053), (-258025139);

SELECT DISTINCT
  cast(c1 as decimal) as c3,
  cast(c1 as signed) as c4
FROM t1;
```

### 2. What did you expect to see? (Required)
The two columns should be same, in MySQL:
```
mysql> SELECT DISTINCT 
    ->   cast(c1 as decimal) as c3,
    ->   cast(c1 as signed) as c4
    -> FROM t1;
+------------+------------+
| c3         | c4         |
+------------+------------+
| -258025139 | -258025139 |
|  575932053 |  575932053 |
+------------+------------+
2 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
But TiDB outputs strange number.
```
mysql> SELECT DISTINCT 
    ->   cast(c1 as decimal) as c3,
    ->   cast(c1 as signed) as c4
    -> FROM t1;
+------------+---------------------+
| c3         | c4                  |
+------------+---------------------+
| -258025139 | 1108209533567631369 |
|  575932053 |                   0 |
+------------+---------------------+
2 rows in set (0.01 sec)
```
After removing `distinct`, the result is correct:
```
mysql> SELECT
    ->   cast(c1 as decimal) as c3,
    ->   cast(c1 as signed) as c4
    -> FROM t1;
+------------+------------+
| c3         | c4         |
+------------+------------+
| -258025139 | -258025139 |
|  575932053 |  575932053 |
+------------+------------+
2 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```
Release Version: v8.1.0
Edition: Community
Git Commit Hash: 945d07c5d5c7a1ae212f6013adfb187f2de24b23
Git Branch: HEAD
UTC Build Time: 2024-05-21 03:51:57
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```
topology:

distributed.yaml:
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 10.0.2.31

tidb_servers:
  - host: 10.0.2.21

tikv_servers:
  - host: 10.0.2.11
  - host: 10.0.2.12
  - host: 10.0.2.13

monitoring_servers:
  - host: 10.0.2.8

grafana_servers:
  - host: 10.0.2.8

alertmanager_servers:
  - host: 10.0.2.8

tiflash_servers:
  - host: 10.0.2.32
```

### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in TiDB that may lead to database logic error.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #53726

Problem Summary:

### What changed and how does it work?

when planer call ```RemoveUnnecessaryFirstRow```. it will check the expression between ```Agg``` and ```GroupBy```. but it doesn't check the return type. so it get wrong unnecessary ```FirstRow```.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/scalar_function.go [hunk 1]
```diff
@@ -365,6 +365,9 @@ func (sf *ScalarFunction) Equal(ctx EvalContext, e Expression) bool {
 	if sf.FuncName.L != fun.FuncName.L {
 		return false
 	}
+	if sf.GetType(ctx) != fun.GetType(ctx) {
```
Comment (qw4990) [inline pkg/expression/scalar_function.go:368]: Can we compare *FieldType directly?

Comment (hawkingrei) [reply pkg/expression/scalar_function.go]: Yes, I have updated.

**Review by wshwsh12 — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

File: pkg/expression/scalar_function.go [hunk 2]
```diff
@@ -365,6 +365,9 @@ func (sf *ScalarFunction) Equal(ctx EvalContext, e Expression) bool {
 	if sf.FuncName.L != fun.FuncName.L {
 		return false
 	}
+	if sf.RetType != fun.RetType {
```
Comment (qw4990) [inline pkg/expression/scalar_function.go:368]: Can we compare 2 pointers directly?

**Review by qw4990 — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
