### PR TITLE
planner: the expression field name disappears when there's window function

### LINKED ISSUE #9639: The field name become empty when there's window function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
create table t(a int);
insert into t values(1);
select 1+1, row_number() over() from t;
```

2. What did you expect to see?

The names of two fields should be `1+1` and `row_number() over()`.

3. What did you see instead?

The name of first field become empty.

```
+------+---------------------+
|      | row_number() over() |
+------+---------------------+
|    2 |                   1 |
+------+---------------------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master 0bec639074e978593bf087e0074429f0b74e6d8c

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve? 

To fix #9639 

### What is changed and how it works?

The final projection field name depends on the rewriting result. After we build first projection, all expression's output become column. Then we get empty name of the expression field.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -672,11 +672,15 @@ func (b *PlanBuilder) buildProjection(p LogicalPlan, fields []*ast.SelectField,
 				expr = p.Schema().Columns[i]
 			}
 			proj.Exprs = append(proj.Exprs, expr)
-			col, err := b.buildProjectionField(proj.id, schema.Len()+1, field, expr)
-			if err != nil {
-				return nil, 0, errors.Trace(err)
+			if isWindowFuncField {
```
Comment (lamxTyler) [inline planner/core/logical_plan_builder.go]: What about merge it with the upper `if`?

File: executor/executor_test.go [hunk 2]
```diff
@@ -2001,10 +2001,22 @@ func (s *testSuite) TestColumnName(c *C) {
...
+	// Test issue https://github.com/pingcap/tidb/issues/9639 .
+	// Both window function and expression appear in final result field.
+	tk.MustExec("set @@tidb_enable_window_function = 1")
+	rs, err = tk.Exec("select 1+1, row_number() over() num from t")
+	c.Check(err, IsNil)
+	fields = rs.Fields()
+	c.Assert(fields[0].Column.Name.L, Equals, "1+1")
+	c.Assert(fields[0].ColumnAsName.L, Equals, "1+1")
+	c.Assert(fields[1].Column.Name.L, Equals, "num")
+	c.Assert(fields[1].ColumnAsName.L, Equals, "num")
```
Comment (eurekaka) [inline executor/executor_test.go]: Close the `rs` please, previously we found leak test failure caused by not closing result set.
