### PR TITLE
executor: optimize analyze column memory usage

### LINKED ISSUE #64423: Analyze a small table costs a lot of memory
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
# adjust the variables in order to insert success
set session tidb_mem_quota_query = 1073741824 * 3;
SET SESSION cte_max_recursion_depth = 200000;

# create table with 109 column
CREATE TABLE `analyze_sim_table` (
  `col1` varchar(32) NOT NULL,
  `col2` varchar(8) NOT NULL,
  `col3` varchar(9) NOT NULL,
  `col4` varchar(4) DEFAULT NULL,
  `col5` varchar(4) DEFAULT NULL,
  `col6` varchar(10) DEFAULT NULL,
  `col7` varchar(10) DEFAULT NULL,
  `col8` varchar(10) DEFAULT NULL,
  `col9` varchar(30) DEFAULT NULL,
  `col10` varchar(256) DEFAULT NULL,
  `col11` varchar(30) DEFAULT NULL,
  `col12` varchar(256) DEFAULT NULL,
  `col13` varchar(32) DEFAULT NULL,
  `col14` varchar(20) DEFAULT NULL,
  `col15` varchar(50) DEFAULT NULL,
  `col16` varchar(50) DEFAULT NULL,
  `col17` varchar(20) DEFAULT NULL,
  `col18` varchar(32) DEFAULT NULL,
  `col19` varchar(1) DEFAULT NULL,
  `col20` varchar(17) DEFAULT NULL,
  `col21` varchar(17) DEFAULT NULL,
  `col22` varchar(20) DEFAULT NULL,
  `col23` varchar(1024) DEFAULT NULL,
  `col24` varchar(1024) DEFAULT NULL,
  `col25` varchar(32) DEFAULT NULL,
  `col26` varchar(256) DEFAULT NULL,
  `col27` varchar(256) DEFAULT NULL,
  `col28` varchar(32) DEFAULT NULL,
  `col29` varchar(30) DEFAULT NULL,
  `col30` varchar(400) DEFAULT NULL,
  `col31` varchar(4) DEFAULT NULL,
  `col32` varchar(200) DEFAULT NULL,
  `col33` varchar(2) DEFAULT NULL,
  `col34` varchar(30) DEFAULT NULL,
  `col35` varchar(20) DEFAULT NULL,
  `col36` varchar(12) DEFAULT NULL,
  `col37` varchar(2) DEFAULT NULL,
  `col38` varchar(30) DEFAULT NULL,
  `col39` varchar(16) DEFAULT NULL,
  `col40` varchar(20) DEFAULT NULL,
  `col41` varchar(2) DEFAULT NULL,
  `col42` varchar(8) DEFAULT NULL,
  `col43` varchar(500) DEFAULT NULL,
  `col44` varchar(14) DEFAULT NULL,
  `col45` varchar(14) DEFAULT NULL,
  `col46` varchar(32) DEFAULT NULL,
  `col47` varchar(14) DEFAULT NULL,
  `col48` varchar(10) DEFAULT NULL,
  `col49` varchar(500) DEFAULT NULL,
  `col50` varchar(12) DEFAULT NULL,
  `col51` varchar(8) DEFAULT NULL,
  `col52` varchar(20) DEFAULT NULL,
  `col53` varchar(32) DEFAULT NULL,
  `col54` varchar(100) DEFAULT NULL,
  `col55` varchar(128) DEFAULT NULL,
  `col56` varchar(6) DEFAULT NULL,
  `col57` varchar(32) DEFAULT NULL,
  `col58` varchar(14) DEFAULT NULL,
  `col59` varchar(32) DEFAULT NULL,
  `col60` varchar(64) DEFAULT NULL,
  `col61` text DEFAULT NULL,
  `col62` varchar(1024) DEFAULT NULL,
  `col63` varchar(32) DEFAULT NULL,
  `col64` varchar(32) DEFAULT NULL,
  `col65` varchar(10) DEFAULT NULL,
  `col66` varchar(14) DEFAULT NULL,
  `col67` varchar(1024) DEFAULT NULL,
  `col68` varchar(32) DEFAULT NULL,
  `col69` varchar(30) DEFAULT NULL,
  `col70` varchar(2) DEFAULT NULL,
  `col71` varchar(50) DEFAULT NULL,
  `col72` varchar(14) DEFAULT NULL,
  `col73` varchar(100) DEFAULT NULL,
  `col74` varchar(40) DEFAULT NULL,
  `col75` varchar(8) DEFAULT NULL,
  `col76` varchar(2) DEFAULT NULL,
  `col77` varchar(2) DEFAULT NULL,
  `col78` varchar(2) DEFAULT NULL,
  `col79` varchar(32) DEFAULT NULL,
  `col80` varchar(8) DEFAULT NULL,
  `col81` varchar(10) DEFAULT NULL,
  `col82` varchar(50) DEFAULT NULL,
  `col83` text DEFAULT NULL,
  `col84` varchar(512) DEFAULT NULL,
  `col85` varchar(20) DEFAULT NULL,
  `col86` varchar(64) DEFAULT NULL,
  `col87` varchar(64) DEFAULT NULL,
  `col88` varchar(20) DEFAULT NULL,
  `col89` varchar(16) DEFAULT NULL,
  `col90` varchar(64) DEFAULT NULL,
  `col91` varchar(16) DEFAULT NULL,
  `col92` varchar(1024) DEFAULT NULL,
  `col93` varchar(32) DEFAULT NULL,
  `col94` varchar(32) DEFAULT NULL,
  `col95` varchar(100) DEFAULT NULL,
  `col96` varchar(2) DEFAULT NULL,
  `col97` varchar(4) DEFAULT NULL,
  `col98` text DEFAULT NULL,
  `col99` varchar(64) DEFAULT NULL,
  `col100` varchar(128) DEFAULT NULL,
  `col101` varchar(512) DEFAULT NULL,
  `col102` varchar(20) DEFAULT NULL,
  `col103` varchar(2) DEFAULT NULL,
  `col104` varchar(20) DEFAULT NULL,
  `col105` varchar(3) DEFAULT NULL,
  `col106` varchar(12) DEFAULT NULL,
  `col107` varchar(32) DEFAULT NULL,
  `col108` longtext DEFAULT NULL,
  `col109` text DEFAULT NULL,
  PRIMARY KEY (`col1`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

# insert 160,000 rows
INSERT INTO `analyze_sim_table` (
  `col1`, `col2`, `col3`, `col9`, `col22`, `col23`, `col61`, `col83`
)
WITH RECURSIVE seq (n) AS (
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM seq WHERE n < 160000
)
SELECT
  CONCAT('sim_txn_', LPAD(n, 20, '0')),          -- col1
  '20251110',                                    -- col2
  '183000000',                                   -- col3
  CONCAT('MERCHANT_', LPAD( (n % 1000) + 1, 3, '0')), -- col9
  '10000',                                       -- col22
  LPAD('order-body-data', 200, 'x'),             -- col23
  LPAD('reserved-field-data', 200, 'y'),         -- col61
  LPAD('bill-list-data', 120, 'z')               -- col83
FROM seq;

# check the row numbers
select count(*) from analyze_sim_table;


# show the metadata
# it may needs to execute many times to guarantee the metadata has been updated. Otherwise the analyze may use the 1 sample rate
select table_name,TABLE_ROWS,sum(DATA_LENGTH)/1024/1024/1024 GB from information_schema.tables where table_name='analyze_sim_table' group by table_name,TABLE_ROWS;

# execute analyze
analyze table analyze_sim_table;
```

### 2. What did you expect to see? (Required)
The table is small, it only has 80MB data. The analyze statement should cost less memory.

### 3. What did you see instead (Required)
The table is small, it only has 80MB data. But the analyze statement costs more than 2GB memory.

```
mysql> select count(*) from analyze_sim_table;
+----------+
| count(*) |
+----------+
|   160000 |
+----------+
1 row in set (0.06 sec)

mysql> select table_name,TABLE_ROWS,sum(DATA_LENGTH)/1024/1024/1024 GB from information_schema.tables where table_name='analyze_sim_table' group by table_name,TABLE_ROWS;
+-------------------+------------+----------------+
| table_name        | TABLE_ROWS | GB             |
+-------------------+------------+----------------+
| analyze_sim_table |     160000 | 0.088363885880 |
+-------------------+------------+----------------+
1 row in set (0.00 sec)

mysql> analyze table analyze_sim_table;
Query OK, 0 rows affected, 1 warning (2.21 sec)

mysql> show warnings;
+-------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level | Code | Message                                                                                                                                                           |
+-------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Note  | 1105 | Analyze use auto adjusted sample rate 0.687500 for table test.analyze_sim_table, reason to use this rate is "use min(1, 110000/160000) as the sample-rate=0.6875" |
+-------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

check the memory cost in the dashboard:
Image

### 4. What is your TiDB version? (Required)

v7.5.6, but the latest master is the same

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #64423

Problem Summary: As https://github.com/pingcap/tidb/issues/64423#issuecomment-3685627435 said, the memory reduced from 2.7G to 2.1G. It's not a big improvement. But for an order-of-magnitude improvement in memory footprint, we’d need to optmize the Datum structure, which involves significant effort and risk.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

memory reduced from 2.76G to 2.1G. Check: https://github.com/pingcap/tidb/issues/64423#issuecomment-3685627435

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/analyze_col_v2.go [hunk 1]
```diff
@@ -788,13 +787,10 @@ workLoop:
 							continue workLoop
 						}
 					}
+					tmp := types.NewBytesDatum(b)
 					sampleItems = append(sampleItems, &statistics.SampleItem{
-						Value: types.NewBytesDatum(b),
+						Value: &tmp,
```
Comment (guo-shaoge) [inline pkg/executor/analyze_col_v2.go]: I need reconsider if we can use pointer here.
Because the for loop reuse slice `b`, and `NewBytesDatum` only shallow copy the slice into `tmp` datum

File: pkg/statistics/sample.go [hunk 2]
```diff
@@ -100,7 +100,11 @@ func (c *SampleCollector) MergeSampleCollector(sc *stmtctx.StatementContext, rc
 		terror.Log(errors.Trace(err))
 	}
 	for _, item := range rc.Samples {
-		err := c.collect(sc, item.Value)
+		if item.Value == nil {
+			terror.Log(errors.Errorf("sample item value is nil"))
+			continue
+		}
```
Comment (0xPoe) [inline pkg/statistics/sample.go:121]: Should we add `intest.Assert` here?

File: pkg/executor/analyze_col_v2.go [hunk 3]
```diff
@@ -732,13 +732,12 @@ workLoop:
 						e.memTracker.BufferedConsume(&bufferedMemSize, deltaSize)
 					}
 					sampleItems = append(sampleItems, &statistics.SampleItem{
-						Value:   val,
+						Value:   &val,
```
Comment (0xPoe) [inline pkg/executor/analyze_col_v2.go:748]: Where do we track the memory of this value?

File: pkg/statistics/sample.go [hunk 4]
```diff
@@ -48,7 +48,7 @@ type SampleItem struct {
 	Ordinal int
 }
 
-// EmptySampleItemSize is the size of empty SampleItem, 96 = 72 (datum) + 8 (int) + 16.
+// EmptySampleItemSize is the size of an empty SampleItem on 64-bit platforms: 32 = 8 (Value pointer) + 16 (Handle interface) + 8 (Ordinal int).
 const EmptySampleItemSize = int64(unsafe.Sizeof(SampleItem{}))
 
 // CopySampleItems returns a deep copy of SampleItem slice.
```
[the remark this answers is not in the document]
Comment (0xPoe) [reply pkg/statistics/sample.go:55]: @guo-shaoge I think it makes a good point. Although we don't really update the value.

File: pkg/statistics/builder.go [hunk 5]
```diff
@@ -454,7 +457,10 @@ func BuildHistAndTopN(
 		if numTopN == 0 {
 			continue
 		}
-		sampleBytes, err := getComparedBytes(samples[i].Value)
+		if samples[i].Value == nil {
```
Comment (0xPoe) [inline pkg/statistics/builder.go:463]: Perhaps we could also include `intest.Assert` here?

File: pkg/statistics/builder.go [hunk 6]
```diff
@@ -434,7 +434,10 @@ func BuildHistAndTopN(
 		return cmp.Compare(a.Count, b.Count) // min-heap: smaller counts at root
 	})
 
-	cur, err := getComparedBytes(samples[0].Value)
+	if samples[0].Value == nil {
```
Comment (0xPoe) [inline pkg/statistics/builder.go:439]: Perhaps we could also include `intest.Assert` here?

File: pkg/executor/analyze_col_v2.go (hunk 3 above)
Comment (0xPoe) [reply pkg/executor/analyze_col_v2.go:748]: I suppose in FromProto?

Comment (guo-shaoge) [reply pkg/executor/analyze_col_v2.go:748]: +1

File: pkg/executor/analyze_col_v2.go [hunk 7]
```diff
@@ -696,6 +690,21 @@ workLoop:
 			if !ok {
 				break workLoop
 			}
+			bufferedMemSize := int64(0)
```
Comment (0xPoe) [inline pkg/executor/analyze_col_v2.go]:
```suggestion
			// Track per-task allocations: currentBufferedMemSize is pending charges to the tracker,
			// totalBuffered accumulates bytes that become part of collector.MemSize.
			currentBufferedMemSize := int64(0)
```

File: pkg/executor/analyze_col_v2.go [hunk 8]
```diff
@@ -788,14 +797,17 @@ workLoop:
 							continue workLoop
 						}
 					}
+					if len(b) > 8 {
```
Comment (0xPoe) [inline pkg/executor/analyze_col_v2.go]: Maybe we could use `cap` here.

File: pkg/statistics/sample.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (0xPoe) [reply pkg/statistics/sample.go:55]: Oh, I meant we should update the comments here. Doing a deep copy may increase memory usage.

**Review by 0xPoe — APPROVED** [review]
rest LGTM 

Approve in advance.
