### PR TITLE
executor: fix 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' may return multiple lines (history jobs) with same job id

### LINKED ISSUE #39233: executor of 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' may return multiple lines (history jobs) with same job id
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

ref https://github.com/pingcap/tiflow/issues/7513

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
```
[2022-11-02T05:17:53.729Z] [Wed Nov  2 13:17:53 CST 2022] Executing SQL: ADMIN SHOW DDL JOB QUERIES LIMIT 10 OFFSET 0
[2022-11-02T05:17:53.729Z] *************************** 1. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 615
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `n` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 2. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 615
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `n` INT(4) NOT NULL DEFAULT '0'
```
### 4. What is your TiDB version? (Required)

```
Release Version: v6.2.0-alpha-1185-g50425f8d0
```

### PR DESCRIPTION
**Pull request by lyzx2001**
### What problem does this PR solve?

Issue Number: close #39233 

Problem Summary:
Executor of 'ADMIN SHOW DDL JOB QUERIES LIMIT m OFFSET n' may return multiple lines (history jobs) with the same job id when this operation happens at the same time with new DDLs being executed.

### What is changed and how it works?
Maintain a map with its key storing job id that has been appended.
Each time before appending the newly read job from history jobs, first check whether the job id exists in the map's key. If exists, the cursor will search for 1 more next job. If not exists, the current job id and the according query will be appended to `req`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -5609,6 +5609,13 @@ func TestAdmin(t *testing.T) {
 	result.Check(testkit.Rows(fmt.Sprintf("%d %s", historyJobs[3].ID, historyJobs[3].Query), fmt.Sprintf("%d %s", historyJobs[4].ID, historyJobs[4].Query)))
 	result = tk.MustQuery(`admin show ddl job queries limit 3 offset 2`)
 	result.Check(testkit.Rows(fmt.Sprintf("%d %s", historyJobs[2].ID, historyJobs[2].Query), fmt.Sprintf("%d %s", historyJobs[3].ID, historyJobs[3].Query), fmt.Sprintf("%d %s", historyJobs[4].ID, historyJobs[4].Query)))
+	// check situations when `admin show ddl job queries limit 3 offset 2` happens at the same time with new DDLs being executed
+	go func() {
```
Comment (lance6716) [inline executor/executor_test.go:5613]: this goroutine most probably runs before next DDL queries in line 5617~5618, because if line 5617~5618 runs, the ddl query list will have two new records at the front so `admin show ddl job queries limit 3 offset 2` will see the 0~2nd of `historyJobs`. Now the check of 2~4th is passed which is a wrong test

you can start two goroutine, one for repeatly drop+create table, the other one for checking the result set of `admin show ddl job queries limit 3 offset 2` has no duplication. Don't forget to use sync.WaitGroup to wait them exit

**Comment by lance6716** [comment]
ping @lyzx2001 please remember to finish this PR at your convenience

**Comment by lyzx2001** [comment]
A potential bug occurs occasionally:

```
[2022/12/27 21:05:16.396 +08:00] [INFO] [ddl.go:1011] ["[ddl] start DDL job"] [job="ID:94, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:93, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.395 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="create table admin_test6 (c1 int, c2 int, c3 int default 1, index (c1))"]
[2022/12/27 21:05:16.396 +08:00] [INFO] [ddl_worker.go:314] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:94, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:93, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.395 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "] [table=true]
[2022/12/27 21:05:16.400 +08:00] [INFO] [ddl_worker.go:1172] ["[ddl] run DDL job"] [worker="worker 7, tp general"] [job="ID:94, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:93, RowCount:0, ArgLen:0, start time: 2022-12-27 21:05:16.395 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.403 +08:00] [INFO] [domain.go:196] ["diff load InfoSchema success"] [currentSchemaVersion=48] [neededSchemaVersion=49] ["start time"=131.459µs] [phyTblIDs="[93]"] [actionTypes="[3]"]
[2022/12/27 21:05:16.434 +08:00] [INFO] [domain.go:728] ["mdl gets lock, update to owner"] [jobID=94] [version=49]
[2022/12/27 21:05:16.435 +08:00] [INFO] [ddl_worker.go:1381] ["[ddl] wait latest schema version changed(get the metadata lock if tidb_enable_metadata_lock is true)"] [ver=49] ["take time"=32.218916ms] [job="ID:94, Type:create table, State:done, SchemaState:public, SchemaID:2, TableID:93, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.395 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.439 +08:00] [INFO] [ddl_worker.go:644] ["[ddl] finish DDL job"] [worker="worker 7, tp general"] [job="ID:94, Type:create table, State:synced, SchemaState:public, SchemaID:2, TableID:93, RowCount:0, ArgLen:0, start time: 2022-12-27 21:05:16.395 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.442 +08:00] [INFO] [ddl.go:1109] ["[ddl] DDL job is finished"] [jobID=94]
[2022/12/27 21:05:16.442 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
[2022/12/27 21:05:16.443 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=49] [cur_db=test] [sql="drop table if exists admin_test7"] [user=]
[2022/12/27 21:05:16.443 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=49] [cur_db=test] [sql="create table admin_test7 (c1 int, c2 int, c3 int default 1, index (c1))"] [user=]
[2022/12/27 21:05:16.446 +08:00] [INFO] [ddl_worker.go:314] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:96, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:95, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.444 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "] [table=true]
[2022/12/27 21:05:16.446 +08:00] [INFO] [ddl.go:1011] ["[ddl] start DDL job"] [job="ID:96, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:95, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.444 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="create table admin_test7 (c1 int, c2 int, c3 int default 1, index (c1))"]
[2022/12/27 21:05:16.450 +08:00] [INFO] [ddl_worker.go:1172] ["[ddl] run DDL job"] [worker="worker 7, tp general"] [job="ID:96, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:95, RowCount:0, ArgLen:0, start time: 2022-12-27 21:05:16.444 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.452 +08:00] [INFO] [domain.go:196] ["diff load InfoSchema success"] [currentSchemaVersion=49] [neededSchemaVersion=50] ["start time"=135.476µs] [phyTblIDs="[95]"] [actionTypes="[3]"]
[2022/12/27 21:05:16.484 +08:00] [INFO] [domain.go:728] ["mdl gets lock, update to owner"] [jobID=96] [version=50]
[2022/12/27 21:05:16.486 +08:00] [INFO] [ddl_worker.go:1381] ["[ddl] wait latest schema version changed(get the metadata lock if tidb_enable_metadata_lock is true)"] [ver=50] ["take time"=34.110819ms] [job="ID:96, Type:create table, State:done, SchemaState:public, SchemaID:2, TableID:95, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.444 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.490 +08:00] [INFO] [ddl_worker.go:644] ["[ddl] finish DDL job"] [worker="worker 7, tp general"] [job="ID:96, Type:create table, State:synced, SchemaState:public, SchemaID:2, TableID:95, RowCount:0, ArgLen:0, start time: 2022-12-27 21:05:16.444 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.493 +08:00] [INFO] [ddl.go:1109] ["[ddl] DDL job is finished"] [jobID=96]
[2022/12/27 21:05:16.493 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
[2022/12/27 21:05:16.493 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=50] [cur_db=test] [sql="drop table if exists admin_test8"] [user=]
[2022/12/27 21:05:16.494 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=50] [cur_db=test] [sql="create table admin_test8 (c1 int, c2 int, c3 int default 1, index (c1))"] [user=]
[2022/12/27 21:05:16.496 +08:00] [INFO] [ddl_worker.go:314] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:98, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:97, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.495 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "] [table=true]
[2022/12/27 21:05:16.496 +08:00] [INFO] [ddl.go:1011] ["[ddl] start DDL job"] [job="ID:98, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:97, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.495 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="create table admin_test8 (c1 int, c2 int, c3 int default 1, index (c1))"]
[2022/12/27 21:05:16.500 +08:00] [INFO] [ddl_worker.go:1172] ["[ddl] run DDL job"] [worker="worker 7, tp general"] [job="ID:98, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:97, RowCount:0, ArgLen:0, start time: 2022-12-27 21:05:16.495 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.502 +08:00] [INFO] [domain.go:196] ["diff load InfoSchema success"] [currentSchemaVersion=50] [neededSchemaVersion=51] ["start time"=127.399µs] [phyTblIDs="[97]"] [actionTypes="[3]"]
[2022/12/27 21:05:16.534 +08:00] [INFO] [domain.go:728] ["mdl gets lock, update to owner"] [jobID=98] [version=51]
[2022/12/27 21:05:16.536 +08:00] [INFO] [ddl_worker.go:1381] ["[ddl] wait latest schema version changed(get the metadata lock if tidb_enable_metadata_lock is true)"] [ver=51] ["take time"=34.52975ms] [job="ID:98, Type:create table, State:done, SchemaState:public, SchemaID:2, TableID:97, RowCount:0, ArgLen:2, start time: 2022-12-27 21:05:16.495 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.545 +08:00] [INFO] [ddl_worker.go:644] ["[ddl] finish DDL job"] [worker="worker 7, tp general"] [job="ID:98, Type:create table, State:synced, SchemaState:public, SchemaID:2, TableID:97, RowCount:0, ArgLen:0, start time: 2022-12-27 21:05:16.495 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:05:16.547 +08:00] [INFO] [ddl.go:1109] ["[ddl] DDL job is finished"] [jobID=98]
[2022/12/27 21:05:16.548 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x61313d2]

goroutine 15592 [running]:
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()
	/Users/apple/Desktop/go/tidb/executor/adapter.go:440 +0x3b3
panic({0x6f60500, 0xa347510})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/pingcap/tidb/planner/core.NormalizeFlatPlan(0xc0049fd798?)
	/Users/apple/Desktop/go/tidb/planner/core/encode.go:265 +0x52
github.com/pingcap/tidb/executor.getPlanDigest(0xc0049fd798)
	/Users/apple/Desktop/go/tidb/executor/adapter.go:1651 +0x53
github.com/pingcap/tidb/executor.(*ExecStmt).observeStmtBeginForTopSQL(0xc008698960, {0x7dc7770, 0xc004afeb70})
	/Users/apple/Desktop/go/tidb/executor/adapter.go:1840 +0x90
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc008698960, {0x7dc7770, 0xc004afeb70})
	/Users/apple/Desktop/go/tidb/executor/adapter.go:505 +0x705
github.com/pingcap/tidb/session.runStmt({0x7dc7700, 0xc00005a100}, 0xc0060db400, {0x7dd96e0, 0xc008698960?})
	/Users/apple/Desktop/go/tidb/session/session.go:2360 +0x565
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc0060db400, {0x7dc7700, 0xc00005a100}, {0x7ddf830?, 0xc008698870})
	/Users/apple/Desktop/go/tidb/session/session.go:2224 +0xaed
github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext(0xc0059b2500, {0x7dc7700, 0xc00005a100}, {0x7550757, 0x2b}, {0x0, 0x0, 0x0})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:321 +0x71a
github.com/pingcap/tidb/testkit.(*TestKit).MustQueryWithContext(0xc0059b2500, {0x7dc7700, 0xc00005a100}, {0x7550757, 0x2b}, {0x0, 0x0, 0x0})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:153 +0x145
github.com/pingcap/tidb/testkit.(*TestKit).MustQuery(0xc000bb06b0?, {0x7550757?, 0x0?}, {0x0?, 0x0?, 0xc000bb06a0?})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:147 +0x8d
github.com/pingcap/tidb/executor_test.TestAdmin.func3()
	/Users/apple/Desktop/go/tidb/executor/executor_test.go:5649 +0x93
created by github.com/pingcap/tidb/executor_test.TestAdmin
	/Users/apple/Desktop/go/tidb/executor/executor_test.go:5645 +0x20b0


Process finished with the exit code 1
```

**Comment by lyzx2001** [comment]
A potential bug occurs occasionally:
```
[2022/12/27 21:30:13.536 +08:00] [INFO] [ddl_worker.go:314] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:94, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:93, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.535 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "] [table=true]
[2022/12/27 21:30:13.536 +08:00] [INFO] [ddl.go:1011] ["[ddl] start DDL job"] [job="ID:94, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:93, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.535 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="create table admin_test6 (c1 int, c2 int, c3 int default 1, index (c1))"]
[2022/12/27 21:30:13.540 +08:00] [INFO] [ddl_worker.go:1172] ["[ddl] run DDL job"] [worker="worker 7, tp general"] [job="ID:94, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:93, RowCount:0, ArgLen:0, start time: 2022-12-27 21:30:13.535 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.543 +08:00] [INFO] [domain.go:196] ["diff load InfoSchema success"] [currentSchemaVersion=48] [neededSchemaVersion=49] ["start time"=316.33µs] [phyTblIDs="[93]"] [actionTypes="[3]"]
[2022/12/27 21:30:13.575 +08:00] [INFO] [domain.go:728] ["mdl gets lock, update to owner"] [jobID=94] [version=49]
[2022/12/27 21:30:13.577 +08:00] [INFO] [ddl_worker.go:1381] ["[ddl] wait latest schema version changed(get the metadata lock if tidb_enable_metadata_lock is true)"] [ver=49] ["take time"=34.084008ms] [job="ID:94, Type:create table, State:done, SchemaState:public, SchemaID:2, TableID:93, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.535 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.582 +08:00] [INFO] [ddl_worker.go:644] ["[ddl] finish DDL job"] [worker="worker 7, tp general"] [job="ID:94, Type:create table, State:synced, SchemaState:public, SchemaID:2, TableID:93, RowCount:0, ArgLen:0, start time: 2022-12-27 21:30:13.535 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.583 +08:00] [INFO] [ddl.go:1109] ["[ddl] DDL job is finished"] [jobID=94]
[2022/12/27 21:30:13.583 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
[2022/12/27 21:30:13.584 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=49] [cur_db=test] [sql="drop table if exists admin_test7"] [user=]
[2022/12/27 21:30:13.584 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=49] [cur_db=test] [sql="create table admin_test7 (c1 int, c2 int, c3 int default 1, index (c1))"] [user=]
[2022/12/27 21:30:13.586 +08:00] [INFO] [ddl_worker.go:314] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:96, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:95, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.585 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "] [table=true]
[2022/12/27 21:30:13.586 +08:00] [INFO] [ddl.go:1011] ["[ddl] start DDL job"] [job="ID:96, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:95, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.585 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="create table admin_test7 (c1 int, c2 int, c3 int default 1, index (c1))"]
[2022/12/27 21:30:13.591 +08:00] [INFO] [ddl_worker.go:1172] ["[ddl] run DDL job"] [worker="worker 7, tp general"] [job="ID:96, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:95, RowCount:0, ArgLen:0, start time: 2022-12-27 21:30:13.585 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.594 +08:00] [INFO] [domain.go:196] ["diff load InfoSchema success"] [currentSchemaVersion=49] [neededSchemaVersion=50] ["start time"=246.253µs] [phyTblIDs="[95]"] [actionTypes="[3]"]
[2022/12/27 21:30:13.625 +08:00] [INFO] [domain.go:728] ["mdl gets lock, update to owner"] [jobID=96] [version=50]
[2022/12/27 21:30:13.626 +08:00] [INFO] [ddl_worker.go:1381] ["[ddl] wait latest schema version changed(get the metadata lock if tidb_enable_metadata_lock is true)"] [ver=50] ["take time"=32.281766ms] [job="ID:96, Type:create table, State:done, SchemaState:public, SchemaID:2, TableID:95, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.585 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.630 +08:00] [INFO] [ddl_worker.go:644] ["[ddl] finish DDL job"] [worker="worker 7, tp general"] [job="ID:96, Type:create table, State:synced, SchemaState:public, SchemaID:2, TableID:95, RowCount:0, ArgLen:0, start time: 2022-12-27 21:30:13.585 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.631 +08:00] [INFO] [ddl.go:1109] ["[ddl] DDL job is finished"] [jobID=96]
[2022/12/27 21:30:13.631 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
[2022/12/27 21:30:13.632 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=50] [cur_db=test] [sql="drop table if exists admin_test8"] [user=]
[2022/12/27 21:30:13.632 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=50] [cur_db=test] [sql="create table admin_test8 (c1 int, c2 int, c3 int default 1, index (c1))"] [user=]
[2022/12/27 21:30:13.634 +08:00] [INFO] [ddl_worker.go:314] ["[ddl] add DDL jobs"] ["batch count"=1] [jobs="ID:98, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:97, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.633 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0; "] [table=true]
[2022/12/27 21:30:13.634 +08:00] [INFO] [ddl.go:1011] ["[ddl] start DDL job"] [job="ID:98, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:97, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.633 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"] [query="create table admin_test8 (c1 int, c2 int, c3 int default 1, index (c1))"]
[2022/12/27 21:30:13.638 +08:00] [INFO] [ddl_worker.go:1172] ["[ddl] run DDL job"] [worker="worker 7, tp general"] [job="ID:98, Type:create table, State:queueing, SchemaState:none, SchemaID:2, TableID:97, RowCount:0, ArgLen:0, start time: 2022-12-27 21:30:13.633 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.640 +08:00] [INFO] [domain.go:196] ["diff load InfoSchema success"] [currentSchemaVersion=50] [neededSchemaVersion=51] ["start time"=123.515µs] [phyTblIDs="[97]"] [actionTypes="[3]"]
[2022/12/27 21:30:13.675 +08:00] [INFO] [domain.go:728] ["mdl gets lock, update to owner"] [jobID=98] [version=51]
[2022/12/27 21:30:13.676 +08:00] [INFO] [ddl_worker.go:1381] ["[ddl] wait latest schema version changed(get the metadata lock if tidb_enable_metadata_lock is true)"] [ver=51] ["take time"=36.162007ms] [job="ID:98, Type:create table, State:done, SchemaState:public, SchemaID:2, TableID:97, RowCount:0, ArgLen:2, start time: 2022-12-27 21:30:13.633 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.680 +08:00] [INFO] [ddl_worker.go:644] ["[ddl] finish DDL job"] [worker="worker 7, tp general"] [job="ID:98, Type:create table, State:synced, SchemaState:public, SchemaID:2, TableID:97, RowCount:0, ArgLen:0, start time: 2022-12-27 21:30:13.633 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0"]
[2022/12/27 21:30:13.682 +08:00] [INFO] [ddl.go:1109] ["[ddl] DDL job is finished"] [jobID=98]
[2022/12/27 21:30:13.682 +08:00] [INFO] [callback.go:121] ["performing DDL change, must reload"]
[2022/12/27 21:30:13.689 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=51] [cur_db=test] [sql="drop table if exists admin_test9"] [user=]
[2022/12/27 21:30:13.689 +08:00] [INFO] [session.go:3766] ["CRUCIAL OPERATION"] [conn=2] [schemaVersion=51] [cur_db=test] [sql="create table admin_test9 (c1 int, c2 int, c3 int default 1, index (c1))"] [user=]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6131092]

goroutine 15536 [running]:
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()
	/Users/apple/Desktop/go/tidb/executor/adapter.go:440 +0x3b3
panic({0x6f60320, 0xa347510})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/pingcap/tidb/planner/core.NormalizeFlatPlan(0xc0063ee798?)
	/Users/apple/Desktop/go/tidb/planner/core/encode.go:265 +0x52
github.com/pingcap/tidb/executor.getPlanDigest(0xc0063ee798)
	/Users/apple/Desktop/go/tidb/executor/adapter.go:1651 +0x53
github.com/pingcap/tidb/executor.(*ExecStmt).observeStmtBeginForTopSQL(0xc0063b5950, {0x7dc7670, 0xc00676f680})
	/Users/apple/Desktop/go/tidb/executor/adapter.go:1840 +0x90
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc0063b5950, {0x7dc7670, 0xc00676f680})
	/Users/apple/Desktop/go/tidb/executor/adapter.go:505 +0x705
github.com/pingcap/tidb/session.runStmt({0x7dc7600, 0xc00005a100}, 0xc006572a00, {0x7dd95e0, 0xc0063b5950?})
	/Users/apple/Desktop/go/tidb/session/session.go:2360 +0x565
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc006572a00, {0x7dc7600, 0xc00005a100}, {0x7ddf730?, 0xc0063b5860})
	/Users/apple/Desktop/go/tidb/session/session.go:2224 +0xaed
github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext(0xc0063e4780, {0x7dc7600, 0xc00005a100}, {0x7550678, 0x2b}, {0x0, 0x0, 0x0})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:321 +0x71a
github.com/pingcap/tidb/testkit.(*TestKit).MustQueryWithContext(0xc0063e4780, {0x7dc7600, 0xc00005a100}, {0x7550678, 0x2b}, {0x0, 0x0, 0x0})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:153 +0x145
github.com/pingcap/tidb/testkit.(*TestKit).MustQuery(0xc0067018c0?, {0x7550678?, 0xc000462f28?}, {0x0?, 0xc0065354a0?, 0x4052b8f?})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:147 +0x8d
github.com/pingcap/tidb/executor_test.TestAdmin.func3()
	/Users/apple/Desktop/go/tidb/executor/executor_test.go:5648 +0xe7
created by github.com/pingcap/tidb/executor_test.TestAdmin
	/Users/apple/Desktop/go/tidb/executor/executor_test.go:5644 +0x20ec


Process finished with the exit code 1
```

File: executor/executor.go [hunk 2]
```diff
@@ -765,10 +765,23 @@ func (e *ShowDDLJobQueriesWithRangeExec) Next(ctx context.Context, req *chunk.Ch
...
+	appendedJobID := make(map[int64]struct{})
+	i := e.cursor
+	for {
 		if i >= int(e.offset) && i < int(e.offset+e.limit) {
-			req.AppendString(0, strconv.FormatInt(e.jobs[i].ID, 10))
-			req.AppendString(1, e.jobs[i].Query)
+			// check whether the job has been read
+			// for situations when this operation happens at the same time with new DDLs being executed
+			if _, ok := appendedJobID[e.jobs[i].ID]; ok {
+				numCurBatch++
```
Comment (lance6716) [inline executor/executor.go:775]: I prefer this variable not be incremented after assignment. It means in this `Next` invocation how many rows should be written. We can use another variable to count how many rows we have written.

Or we can filter the duplicated job at `Open`

Also seems ShowDDLJobQueriesExec also have this problem, please also fix it

File: executor/executor_test.go [hunk 3]
```diff
@@ -5630,6 +5630,39 @@ func TestAdmin(t *testing.T) {
...
+		defer wg.Done()
+		for i := 0; i < 10; i++ {
+			result = tk.MustQuery(`admin show ddl job queries limit 3 offset 2`)
+			rows := result.Rows()
+			rowIDs := make(map[string]struct{})
+			for _, row := range rows {
+				rowID := fmt.Sprintf("%v", row[0])
+				if _, ok := rowIDs[rowID]; ok {
+					flag = false
+					break
```
Comment (lance6716) [inline executor/executor_test.go:5655]:
```suggestion
					return
```

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: executor/executor.go (hunk 2 above)
Comment (lyzx2001) [reply executor/executor.go:775]: Here `numCurBatch` indeed means in this `Next` invocation how many rows should be written, instead of the number of rows we have written.
Line 774 is the situation where the newly retrieved job ID has already been in the key of map `appendedJobID`, which means we have retrieved a duplicate history job (due to the execution of new DDLs at the same time), so the handling method is to ignore this current line and increase `numCurBatch` by 1 to retrieve one more line in order to make the length of `req` conform to the number of rows that should be written. `i` is the variable that serve as the local cursor and keep count of how many rows we have written.
And in `Next` of `ShowDDLJobQueriesExec` there seems to be no increasing `numCurBatch`.

File: executor/executor_test.go (hunk 3 above)
Comment (lyzx2001) [reply executor/executor_test.go]: Here I intended to cause error and fail the test if we encounter this situation. If we use `return` here, will the test result in "test failed" when we encounter this situation? I'm not quite sure

File: executor/executor.go (hunk 2 above)
Comment (lance6716) [reply executor/executor.go:775]: > so the handling method is to ignore this current line and increase `numCurBatch` by 1

This breaks the definition. If we skip writing a row, "how many rows should be written" is not changed, but in current code we act like we did write the row and increase `numCurBatch`. In other words, take the ending condition of loop as `written == numCurBatch`, when a row is skipped we should neither increase `written` and `numCurBatch`. 

Another way to code is decrease `numCurBatch` by 1 after written a row, and the loop ends when `numCurBatch == 0`

`ShowDDLJobQueriesExec` may also have duplicated job in `e.jobs`, I think it may output a row twice.

File: executor/executor_test.go (hunk 3 above)
Comment (lance6716) [reply executor/executor_test.go]: `flag` should not be deleted.

File: executor/executor.go (hunk 2 above)
Comment (lyzx2001) [reply executor/executor.go]: Modified. Here I use a variable `numOfRowsToWrite` to keep track of how many rows that we still need to write.

File: executor/executor.go [hunk 4]
```diff
@@ -691,9 +691,19 @@ func (e *ShowDDLJobQueriesExec) Next(ctx context.Context, req *chunk.Chunk) erro
...
+		appendedJobID := make(map[int64]struct{})
+		for {
+			_, ok := appendedJobID[e.jobs[i].ID]
+			if id == e.jobs[i].ID && !ok {
+				appendedJobID[e.jobs[i].ID] = struct{}{}
 				req.AppendString(0, e.jobs[i].Query)
+				numOfRowsToWrite--
+			}
+			i++
+			if i >= len(e.jobs) || numOfRowsToWrite == 0 {
```
Comment (lance6716) [inline executor/executor.go:705]: `numCurBatch` does not have same meaning as in `ShowDDLJobQueriesWithRangeExec`, it's a batch size of cursor loop, not the amount we should write in this `Next` invocation. If we breaks here, e.cursor will be forwarded while some matched rows are not output

File: executor/executor.go [hunk 5]
```diff
@@ -765,10 +775,26 @@ func (e *ShowDDLJobQueriesWithRangeExec) Next(ctx context.Context, req *chunk.Ch
 		return nil
 	}
 	numCurBatch := mathutil.Min(req.Capacity(), len(e.jobs)-e.cursor)
-	for i := e.cursor; i < e.cursor+numCurBatch; i++ {
-		if i >= int(e.offset) && i < int(e.offset+e.limit) {
-			req.AppendString(0, strconv.FormatInt(e.jobs[i].ID, 10))
-			req.AppendString(1, e.jobs[i].Query)
+	numOfRowsToWrite := numCurBatch
```
Comment (lance6716) [inline executor/executor.go:778]: now this logic is too long and readability is also not good. 

`ShowDDLJobQueriesExec` is different with `ShowDDLJobQueriesWithRangeExec`, `ShowDDLJobQueriesExec` chooses to loop a batch of rows multiple times to match `jobIDs`, so the batch size is needed to control loop granularity. `ShowDDLJobQueriesWithRangeExec` will only access once for each row, seems we can directly let `e.cursor++` and `numCurBatch--`, no need to use `i` and `numOfRowsToWrite` to keep original values

Comment (lyzx2001) [reply executor/executor.go:778]: If we directly let `e.cursor++` and `numCurBatch--`, `e.cursor` will not end up the same as when we use `numOfRowsToWrite` and `e.cursor += numCurBatch`. When we detect duplicate jobs, we need to `i++` to set the local cursor forward to check the next job, but in this case `numCurBatch` should not decrease 1 since we did not write this line. So if we directly use `e.cursor` to be `i`, when `numCurBatch` reaches 0, `e.cursor` will end up larger than it should be, which should be the original `e.cursor` plus original `numCurBatch`. Then the next query will get the wrong `e.cursor`.

Comment (lyzx2001) [reply executor/executor.go:776]: This is the code of `Next` I modified according to this suggestion, I would like to make sure that I understand you right

```
// Next implements the Executor Next interface.
func (e *ShowDDLJobQueriesWithRangeExec) Next(ctx context.Context, req *chunk.Chunk) error {
	req.GrowAndReset(e.maxChunkSize)
	if e.cursor >= len(e.jobs) {
		return nil
	}
	if int(e.limit) > len(e.jobs) {
		return nil
	}
	numCurBatch := mathutil.Min(req.Capacity(), len(e.jobs)-e.cursor)
	appendedJobID := make(map[int64]struct{})
	if e.cursor < int(e.offset) {
		e.cursor = int(e.offset)
	}
	for {
		// check whether the job has been read
		// for situations when this operation happens at the same time with new DDLs being executed
		if _, ok := appendedJobID[e.jobs[e.cursor].ID]; !ok {
			appendedJobID[e.jobs[e.cursor].ID] = struct{}{}
			req.AppendString(0, strconv.FormatInt(e.jobs[e.cursor].ID, 10))
			req.AppendString(1, e.jobs[e.cursor].Query)
			numCurBatch--
		}
		e.cursor++
		if e.cursor >= int(e.offset+e.limit) || e.cursor >= len(e.jobs) || numCurBatch == 0 {
			break
		}
	}
	return nil
}
```

Comment (lance6716) [reply executor/executor.go:776]: The new code is easier to understand, and sorry I just found other problems that I didn't realise in previous review 😂 :

`appendedJobID` is reset to a new variable after `Next` invocation is finished, so it can't deduplicate result in different `Next`, considering the caller will use Open-Next-Next(multiple times)-Close to get full result.

And as you says the skipped rows will cause the relation of `e.cursor`, `numCurBatch` and other variables a bit messy. Now I prefer we do the deduplication in `Open`

```
	e.jobs = append(e.jobs, jobs...)
	e.jobs = append(e.jobs, historyJobs...) <- change it to skip duplicate jobs
```

So when it goes to `Next`, we can directly start to write e.jobs[e.offset:e.offset+e.limit] in `Next` until the input chunk is full.

File: executor/executor.go [hunk 6]
```diff
@@ -674,8 +674,21 @@ func (e *ShowDDLJobQueriesExec) Open(ctx context.Context) error {
 		return err
 	}
 
-	e.jobs = append(e.jobs, jobs...)
-	e.jobs = append(e.jobs, historyJobs...)
+	appendedJobID := make(map[int64]struct{})
+	// deduplicate job results
+	// for situations when this operation happens at the same time with new DDLs being executed
```
Comment (lance6716) [inline executor/executor.go:679]: the reason of duplication I think is jobs may finish between `ddl.GetAllDDLJobs` and `ddl.GetLastNHistoryDDLJobs`, so we will see it in both pending DDL and finished DDL. No need to check duplication for `jobs` from `ddl.GetAllDDLJobs`

File: executor/executor.go [hunk 7]
```diff
@@ -764,11 +790,16 @@ func (e *ShowDDLJobQueriesWithRangeExec) Next(ctx context.Context, req *chunk.Ch
 	if int(e.limit) > len(e.jobs) {
 		return nil
 	}
+	if e.cursor < int(e.offset) {
+		e.cursor = int(e.offset)
```
Comment (lance6716) [inline executor/executor.go:794]: we can set e.cursor in `Open`, `Open` is called only once

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: executor/executor.go (hunk 6 above)
Comment (lyzx2001) [reply executor/executor.go:679]: I tried to not check duplication for `jobs` from `ddl.GetAllDDLJobs`, but sometimes may result in this error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6130472]

goroutine 15610 [running]:
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()
	/Users/apple/Desktop/go/tidb/executor/adapter.go:440 +0x3b3
panic({0x6f5fea0, 0xa347510})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/pingcap/tidb/planner/core.NormalizeFlatPlan(0xc004400798?)
	/Users/apple/Desktop/go/tidb/planner/core/encode.go:265 +0x52
github.com/pingcap/tidb/executor.getPlanDigest(0xc004400798)
	/Users/apple/Desktop/go/tidb/executor/adapter.go:1651 +0x53
github.com/pingcap/tidb/executor.(*ExecStmt).observeStmtBeginForTopSQL(0xc0071733b0, {0x7dc7390, 0xc007742270})
	/Users/apple/Desktop/go/tidb/executor/adapter.go:1840 +0x90
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc0071733b0, {0x7dc7390, 0xc007742270})
	/Users/apple/Desktop/go/tidb/executor/adapter.go:505 +0x705
github.com/pingcap/tidb/session.runStmt({0x7dc7320, 0xc00019c008}, 0xc000804c80, {0x7dd9300, 0xc0071733b0?})
	/Users/apple/Desktop/go/tidb/session/session.go:2360 +0x565
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc000804c80, {0x7dc7320, 0xc00019c008}, {0x7ddf450?, 0xc0071732c0})
	/Users/apple/Desktop/go/tidb/session/session.go:2224 +0xaed
github.com/pingcap/tidb/testkit.(*TestKit).ExecWithContext(0xc0042f14a0, {0x7dc7320, 0xc00019c008}, {0x74f5c14, 0x1d}, {0x0, 0x0, 0x0})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:321 +0x71a
github.com/pingcap/tidb/testkit.(*TestKit).MustQueryWithContext(0xc0042f14a0, {0x7dc7320, 0xc00019c008}, {0x74f5c14, 0x1d}, {0x0, 0x0, 0x0})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:153 +0x145
github.com/pingcap/tidb/testkit.(*TestKit).MustQuery(0xc005e5dce0?, {0x74f5c14?, 0xc000a96628?}, {0x0?, 0x5ef9dd5?, 0x7dafbd0?})
	/Users/apple/Desktop/go/tidb/testkit/testkit.go:147 +0x8d
github.com/pingcap/tidb/executor_test.TestAdmin.func3()
	/Users/apple/Desktop/go/tidb/executor/executor_test.go:5650 +0xd1
created by github.com/pingcap/tidb/executor_test.TestAdmin
	/Users/apple/Desktop/go/tidb/executor/executor_test.go:5646 +0x201b


Process finished with the exit code 1
```

I guess there may still exist duplication for `jobs` from `ddl.GetAllDDLJobs` for some reason?

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
the failed CI is recorded in https://github.com/pingcap/tidb/issues/40206

/cc @lichunzhu @hawkingrei

**Comment by lance6716** [comment]
ptal @lichunzhu @hawkingrei

**Review by lichunzhu — APPROVED** [review]
