### PR TITLE
types: fix `decodeEscapedUnicode` func work with `surrogate pair`

### LINKED ISSUE #61091: Got runtime error when lookup special characters on json field
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `model_fields_nullablejsonmodel` (   `id` int NOT NULL AUTO_INCREMENT,   `value` json DEFAULT NULL,   `value_custom` json DEFAULT NULL,   PRIMARY KEY (`id`)  ,   CONSTRAINT `model_fields_nullablejsonmodel_chk_1` CHECK ((json_valid(`value`))),   CONSTRAINT `model_fields_nullablejsonmodel_chk_2` CHECK ((json_valid(`value_custom`))) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `model_fields_nullablejsonmodel` (`value`, `value_custom`) VALUES ('{\"CONTROL\": \"some value\", \"single\'\": \"some value\", \"dollar$\": \"some value\", \"dot.dot\": \"some value\", \"with space\": \"some value\", \"back\\\\slash\": \"some value\", \"question?mark\": \"some value\", \"user@name\": \"some value\", \"emo\\ud83e\\udd21\'ji\": \"some value\", \"com,ma\": \"some value\", \"curly{{{brace}}}s\": \"some value\", \"escape\\uffff\'seq\'\\uffffue\\uffff\'nce\": \"some value\"}', NULL);

SELECT `model_fields_nullablejsonmodel`.`id`, `model_fields_nullablejsonmodel`.`value`, `model_fields_nullablejsonmodel`.`value_custom` FROM `model_fields_nullablejsonmodel` WHERE JSON_CONTAINS_PATH(`model_fields_nullablejsonmodel`.`value`, 'one', '$."emo\\ud83e\\udd21\'ji"');
```

<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)

MySQL 8
```
mysql> SELECT `model_fields_nullablejsonmodel`.`id`, `model_fields_nullablejsonmodel`.`value`, `model_fields_nullablejsonmodel`.`value_custom` FROM `model_fields_nullablejsonmodel` WHERE JSON_CONTAINS_PATH(`model_fields_nullablejsonmodel`.`value`, 'one', '$."emo\\ud83e\\udd21\'ji"');
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| id    | value                                                                                                                                                                                                                                                                                                                                                      | value_custom |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| 30001 | {"com,ma": "some value", "CONTROL": "some value", "dollar$": "some value", "dot.dot": "some value", "single'": "some value", "user@name": "some value", "back\\slash": "some value", "emo🤡'ji": "some value", "with space": "some value", "question?mark": "some value", "curly{{{brace}}}s": "some value", "escape￿'seq'￿ue￿'nce": "some value"}           | NULL         |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
MySQL [django_tests]> SELECT `model_fields_nullablejsonmodel`.`id`, `model_fields_nullablejsonmodel`.`value`, `model_fields_nullablejsonmodel`.`value_custom` FROM `model_fields_nullablejsonmodel` WHERE JSON_CONTAINS_PATH(`model_fields_nullablejsonmodel`.`value`, 'one', '$."emo\\ud83e\\udd21\'ji"');
ERROR 1105 (HY000): runtime error: slice bounds out of range [:-1]
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
Release Version: v8.5.1
Edition: Community
Git Commit Hash: fea86c8e35ad4a86a5e1160701f99493c2ee547c
Git Branch: HEAD
UTC Build Time: 2025-01-16 07:38:34
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

raise from https://github.com/django/django/blob/stable/5.2.x/tests/model_fields/test_jsonfield.py#L839

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #61091

Problem Summary: For some special charactesrs, such like some emoji, it uses two `\\uxxxx` to present. The `decodeEscapedUnicode` func didn't deal with it correctly before. This PR fix it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by YangKeao** [comment]
Do we also need to modify TiKV/TiFlash?

**Review by YangKeao — APPROVED** [review]

**Comment by Defined2014** [comment]
> Do we also need to modify TiKV/TiFlash?

I think so. The related functions https://github.com/tikv/tikv/blob/d241ebe469d2c9ce8f84801517414c55f5ce05a2/components/tidb_query_datatype/src/codec/mysql/json/json_unquote.rs#L86

File: pkg/types/json_binary_functions.go [hunk 1]
```diff
@@ -134,6 +135,16 @@ func unquoteJSONString(s string) (string, error) {
 				}
 				char, size, err := decodeEscapedUnicode(hack.Slice(s[i+1 : i+5]))
 				if err != nil {
+					// For `surrogate pair`, it uses two `\\uxxx` to encode a character.
+					if size < 0 && len(s) >= i+10 && s[i+5] == '\\' && s[i+6] == 'u' {
```
Comment (lance6716) [inline pkg/types/json_binary_functions.go:139]: `size < 0` is not clear to me. I think the surrogate pair is triggered only when "invalid unicode" happens? Maybe use a specialized return value or error class to check this case.

File: pkg/types/json_binary_functions.go [hunk 2]
```diff
@@ -134,6 +135,16 @@ func unquoteJSONString(s string) (string, error) {
...
+						char, size, err = decodeEscapedUnicode(append(hack.Slice(s[i+1:i+5]), hack.Slice(s[i+7:i+11])...))
```
Comment (lance6716) [inline pkg/types/json_binary_functions.go:140]: seems `append` will modify `s`'s underlying array, I'm not sure if it will cause some problems after caller returns.

File: pkg/types/json_binary_functions.go [hunk 3]
```diff
@@ -153,15 +164,21 @@ func unquoteJSONString(s string) (string, error) {
 // According RFC 3629, the max length of utf8 characters is 4 bytes.
 // And MySQL use 4 bytes to represent the unicode which must be in [0, 65536).
 func decodeEscapedUnicode(s []byte) (char [4]byte, size int, err error) {
-	size, err = hex.Decode(char[0:2], s)
-	if err != nil || size != 2 {
-		// The unicode must can be represented in 2 bytes.
+	size, err = hex.Decode(char[0:4], s)
+	if err != nil || (size != 2 && size != 4) {
```
Comment (lance6716) [inline pkg/types/json_binary_functions.go:168]: when `(size != 2 && size != 4)` happens, `err` is nil, caller's check about `err == nil` will go wrong. I think we should return an error here?

**Review by lance6716 — COMMENTED** [review]
nit: also add unit tests of the new logic at `unquoteJSONString` layer. And check some illegal values will not cause panic. And also check special runes like `\uFFFD` works well

**Review by lance6716 — APPROVED** [review]
