### PR TITLE
lightning: sample files and pre-allocate rowID before restoring chunk

### LINKED ISSUE #28776: [lightning] Estimate rowid might overflow when import data and auto fill int column.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
This issue was created according to ONCALL-3504

Using lightning to import data, before lightning import, create the schema in TiDB manually and adding an extra column: `id_auto_incr` int(11) NOT NULL AUTO_INCREMENT, during import, lightning will estimate the rowid and auto fill this column (as this column doesn't exists in data source), and rowid might overflow in some cases and result in data inconsistency.

### 2. What did you expect to see? (Required)
Lightning import should be successful and data consistency should be ensured.

### 3. What did you see instead (Required)
Lighting import failed with checksum mistch.

### 4. What is your TiDB version? (Required)
Lightning: 4.0.14

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: close #28776 

Problem Summary:

Currently, Lightning pre-allocates rowIDs for each row when populating chunks according to data file sizes. But it occurs that estimates of rowID are now conservatively too large so that Lightning usually pre-allocates a large number of rowIDs, which significantly exceeds what we need. This issue may result in:
1. if the number of rows is relatively close to the maximum of the data type of its `auto_increment` field, Lightning is likely to allocate rowIDs that exceed this limit. (e.g. `2^31` rows of data may probably have `2^32` rowIDs, which exceeds the range of `int32` if the `auto_increment` field is `int32`)
2. Too much space of rowID is wasted because of over-estimate.

### What is changed and how it works?
In this pr, I'm about to:
1. sample rows from data files and do a better estimation.
2. re-allocate ids when they are run out (due to bad estimation)
3. early stop when the rowID overflows

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by buchuitoudegou** [comment]
/cc @gozssky @D3Hunter @Ehco1996 

PTAL

File: br/pkg/lightning/mydump/region.go [hunk 1]
```diff
@@ -271,6 +272,10 @@ func makeSourceFileRegion(
 	if !isCsvFile {
 		divisor += 2
 	}
+	sizePerRow, err := SampleAndGetAvgRowSize(&fi, cfg, ioWorkers, store)
```
Comment (gozssky) [inline br/pkg/lightning/mydump/region.go:275]: `sizePerRow` is not a precise value. What if the number of rows exceeds the row id range?

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/region.go:275]: Still WIP, PTAL https://github.com/buchuitoudegou/tidb/commit/e5a9e5d6651bd41948e54a74eb873a5e6abd8b7f

Should I combine them into one or file another PR.

Comment (gozssky) [reply br/pkg/lightning/mydump/region.go:275]: Don't put it in another PR. Otherwise, this PR may introduce correctness issues.

Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/region.go:275]: Will cherry-pick to this PR later.

**Comment by buchuitoudegou** [comment]
ptal @gozssky

File: br/pkg/lightning/backend/kv/sql2kv.go [hunk 2]
```diff
@@ -542,3 +542,16 @@ func (kvs *KvPairs) Clear() Rows {
 	kvs.pairs = kvs.pairs[:0]
 	return kvs
 }
+
+func (kvs *KvPairs) GetRowIDToKv() map[int64][]*common.KvPair {
```
Comment (gozssky) [inline br/pkg/lightning/backend/kv/sql2kv.go:546]: It seems this method is not used.

File: br/pkg/lightning/restore/restore.go [hunk 3]
```diff
@@ -2142,13 +2149,24 @@ type deliverResult struct {
 	err      error
 }
 
+func (cr *chunkRestore) adjustRowID(rowID *int64) {
```
Comment (gozssky) [inline br/pkg/lightning/restore/restore.go:2152]: It's better to pass by value that passes an int64 value and returns an int64 value.

File: br/pkg/lightning/restore/table_restore.go [hunk 4]
```diff
@@ -1012,3 +1019,11 @@ func estimateCompactionThreshold(cp *checkpoints.TableCheckpoint, factor int64)
 
 	return threshold
 }
+
+func (tr *TableRestore) allocateRowIDs() (int64, int64) {
+	tr.rowIDLock.Lock()
+	defer tr.rowIDLock.Unlock()
+	newBase := tr.curMaxRowID + 1
+	tr.curMaxRowID += defaultNewAllocIDCnt
+	return newBase, tr.curMaxRowID
```
Comment (gozssky) [inline br/pkg/lightning/restore/table_restore.go:1028]: We should also consider parallel import. Please refer https://github.com/pingcap/tidb/blob/d8be8edbe11c5602c40c96fc8254b6ab13c035c8/br/pkg/lightning/restore/meta_manager.go#L80.

File: br/pkg/lightning/restore/table_restore.go [hunk 5]
```diff
@@ -45,6 +45,8 @@ import (
 	"go.uber.org/zap"
 )
 
+const defaultNewAllocIDCnt = 100000
```
Comment (gozssky) [inline br/pkg/lightning/restore/table_restore.go:48]: Can we sample again for the rest chunk? Instead of using a fixed value. 

Another way may be to record the average row size while reading the chunk.

File: br/pkg/lightning/restore/table_restore.go (hunk 4 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/restore/table_restore.go:1028]: Does parallel import here mean restoring tables from different lightning instances so I'm supposed to read pre-allocated ID from checkpoints before allocating them?

Comment (gozssky) [reply br/pkg/lightning/restore/table_restore.go:1028]: In parallel import, we should ensure different instances use different row id.

**Comment by buchuitoudegou** [comment]
ptal @gozssky

File: br/pkg/lightning/backend/local/engine.go [hunk 6]
```diff
@@ -1034,6 +1062,29 @@ func (w *Writer) appendRowsSorted(kvs []common.KvPair) error {
...
+		if kvs[i].RowID > kvs[i-1].RowID+1 && sliceIdx == -1 {
+			// rowID leap, probably re-alloc id
+			// should write to different sst
+			sliceIdx = i
+		}
+		if i == len(kvs)-1 {
+			w.prevRowID = kvs[i].RowID
+		}
+	}
+	if sliceIdx > 0 {
```
Comment (gozssky) [inline br/pkg/lightning/backend/local/engine.go:1076]: In theory, there may be multiple leap points.

File: br/pkg/lightning/mydump/region.go [hunk 7]
```diff
@@ -302,6 +312,53 @@ func makeSourceFileRegion(
...
+	store storage.ExternalStorage,
+) (int64, error) {
+	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+	defer cancel()
+	reader, err := store.Open(ctx, fileInfo.FileMeta.Path)
+	if err != nil {
+		return 0, nil
+	}
+	var parser Parser
+	switch fileInfo.FileMeta.Type {
```
Comment (gozssky) [inline br/pkg/lightning/mydump/region.go:328]: We should handle all possible file types here.

File: br/pkg/lightning/restore/meta_manager.go [hunk 8]
```diff
@@ -160,6 +161,59 @@ func parseMetaStatus(s string) (metaStatus, error) {
...
+			ctx,
+			fmt.Sprintf("SELECT row_id_max from %s WHERE table_id = ? FOR UPDATE", m.tableName),
+			m.tr.tableInfo.ID,
+		)
+		if err != nil {
+			return errors.Trace(err)
+		}
+		defer rows.Close()
+		var query string
+		for rows.Next() {
```
Comment (gozssky) [inline br/pkg/lightning/restore/meta_manager.go:193]: Does the query match multiple rows?

File: br/pkg/lightning/restore/meta_manager.go [hunk 9]
```diff
@@ -1031,6 +1085,10 @@ func (m noopTableMetaMgr) InitTableMeta(ctx context.Context) error {
 	return nil
 }
 
+func (m noopTableMetaMgr) ReAllocTableRowIDs(ctx context.Context, _ int64) (int64, int64, error) {
+	return 0, 0, nil
```
Comment (gozssky) [inline br/pkg/lightning/restore/meta_manager.go:1089]: It seems this shouldn't be a noop implemention.

File: br/tests/lightning_realloc_id/config.toml [hunk 10]
```diff
@@ -0,0 +1,3 @@
+[tikv-importer]
+incremental-import = true
```
Comment (gozssky) [inline br/tests/lightning_realloc_id/config.toml:2]: Please add a test for  `incremental-import = false`.

File: br/pkg/lightning/mydump/region.go (hunk 7 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/region.go:328]: Do we solely support 3 types of source files:
1. csv
2. sql
3. parquet

What else should I handle?

Comment (gozssky) [reply br/pkg/lightning/mydump/region.go:328]: It should be no more. It's better to return an error for unknown file types.

Comment (gozssky) [reply br/pkg/lightning/mydump/region.go:328]: Compared to csv, sql and parquet have some subtle differences. Please check whether we can apply the algorithm to them.

File: br/pkg/lightning/restore/meta_manager.go (hunk 9 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/restore/meta_manager.go:1089]: As I concern, `noopTableMetaMgr` is used as long as Lightning is not `local + incremental`. In this sense, Lightning merely allocates rowID from its own memory and needn't reconcile with other instances. So, for `noopTableMetaMgr`, simply returning 0 is trivial and feasible.

What did you suggest to be here?

File: br/pkg/lightning/mydump/region.go (hunk 7 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/mydump/region.go:328]: parquet files won't be sampled in this way. They have provisioned an accurate number of lines.

FYI: https://github.com/pingcap/tidb/blob/0f85650aa43cb60a77ce507e02203db45584e914/br/pkg/lightning/mydump/region.go#L307-L335

I'll handle the unexpected file types then.

File: br/pkg/lightning/restore/meta_manager.go (hunk 9 above)
Comment (gozssky) [reply br/pkg/lightning/restore/meta_manager.go:1089]: > allocates rowID from its own memory

We can do this in this method, so that we don't care about the actual implementation on the caller side.

Comment (buchuitoudegou) [reply br/pkg/lightning/restore/meta_manager.go:1089]: > We can do this in this method, so that we don't care about the actual implementation on the caller side.

It's hard to do so because `noopTableMetaMgr` is somehow a "placeholder" having no idea about the context of the table restoring procedure. If we utilize this contextless structure, we have to:
1. let `singleMgrBuilder` be no longer contextless
2. maintain restoring information in `noopTableMetaMgr` (for which, this struct will not be "noop" anymore)

It's good to have a global metadata manager though, I think we should be more circumspect about it and do this change in another PR (to make thing clearer). Maybe I just leave a TODO and file an issue now?

File: br/pkg/lightning/restore/meta_manager.go [hunk 11]
```diff
@@ -160,6 +161,53 @@ func parseMetaStatus(s string) (metaStatus, error) {
...
+	err = exec.Exec(ctx, "enable pessimistic transaction", "SET SESSION tidb_txn_mode = 'pessimistic';")
+	if err != nil {
+		return 0, 0, errors.Annotate(err, "enable pessimistic transaction failed")
+	}
+	var (
+		newRowIDBase int64
+		newRowIDMax  int64
+	)
+	err = exec.Transact(ctx, "realloc table rowID", func(ctx context.Context, tx *sql.Tx) error {
+		rows, err := tx.QueryContext(
```
Comment (gozssky) [inline br/pkg/lightning/restore/meta_manager.go:183]:
```suggestion
		rows, err := tx.QueryRowContext(
```

File: br/pkg/lightning/restore/meta_manager.go [hunk 12]
```diff
@@ -78,6 +78,7 @@ func (b *dbMetaMgrBuilder) TableMetaMgr(tr *TableRestore) tableMetaMgr {
 type tableMetaMgr interface {
 	InitTableMeta(ctx context.Context) error
 	AllocTableRowIDs(ctx context.Context, rawRowIDMax int64) (*verify.KVChecksum, int64, error)
+	ReallocTableRowIDs(ctx context.Context, newRowIDCount int64) (int64, int64, error)
```
Comment (gozssky) [inline br/pkg/lightning/restore/meta_manager.go:81]: Please add more comments for this method, since `noopTableMetaMgr` doesn't really implement it.

File: br/pkg/lightning/restore/meta_manager.go (hunk 9 above)
Comment (gozssky) [reply br/pkg/lightning/restore/meta_manager.go:1083]: Yes, it's needed.

File: br/pkg/lightning/restore/meta_manager.go (hunk 12 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/restore/meta_manager.go:83]: [4b5b415](https://github.com/pingcap/tidb/pull/34288/commits/4b5b4155917d93ec5564b870412ac07075fb438d)

**Comment by buchuitoudegou** [comment]
ptal @gozssky

File: br/pkg/lightning/restore/meta_manager.go [hunk 13]
```diff
@@ -78,6 +78,8 @@ func (b *dbMetaMgrBuilder) TableMetaMgr(tr *TableRestore) tableMetaMgr {
 type tableMetaMgr interface {
 	InitTableMeta(ctx context.Context) error
 	AllocTableRowIDs(ctx context.Context, rawRowIDMax int64) (*verify.KVChecksum, int64, error)
+	// re-allocate rowIDs across lightning instances
+	// only parallel import needs this
```
Comment (gozssky) [inline br/pkg/lightning/restore/meta_manager.go:82]: Could add more comments to explain the return value? BTW, comments should begin with the method name.

**Review by gozssky — COMMENTED** [review]
rest LGTM

File: br/pkg/lightning/restore/meta_manager.go (hunk 13 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/restore/meta_manager.go]: 4df0f47

**Comment by gozssky** [comment]
@D3Hunter @dsdashun PTAL

File: br/pkg/lightning/restore/restore.go [hunk 14]
```diff
@@ -2137,13 +2150,45 @@ type deliverResult struct {
 	err      error
 }
 
+func (cr *chunkRestore) adjustRowID(rowID int64, rc *Controller) (int64, error) {
+	if rowID > cr.originalRowIDMax {
```
Comment (D3Hunter) [inline br/pkg/lightning/restore/restore.go:2154]: we can return on `rowID <= cr.originalRowIDMax` to reduce indent level.

can we use curRowIDBase and curRowIDMax to replace originalRowIDMax?

File: br/pkg/lightning/restore/restore.go [hunk 15]
```diff
@@ -2137,13 +2150,45 @@ type deliverResult struct {
...
+		if cr.curRowIDBase == 0 || cr.curRowIDBase > cr.curRowIDMax {
```
Comment (D3Hunter) [inline br/pkg/lightning/restore/restore.go:2155]: the allowed rowid range is [base, max]? maybe add some comments on the field declare part.

**Review by D3Hunter — COMMENTED** [review]
will review test later.

File: br/pkg/lightning/restore/restore.go (hunk 14 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/restore/restore.go:2154]: I don't suppose so. The parser will allocate rowID incrementally based on the original rowID base (rather than `curRowIDBase`) and thus, despite re-allocating a new chunk of IDs, the rowID produced then may still be smaller than `curRowIDBase` but larger than `originalRowIDMax`.

**Review by D3Hunter — COMMENTED** [review]
lgtm

**Review by D3Hunter — APPROVED** [review]

File: br/pkg/lightning/backend/local/engine.go [hunk 16]
```diff
@@ -1034,7 +1061,33 @@ func (w *Writer) appendRowsSorted(kvs []common.KvPair) error {
 		}
 		kvs = newKvs
 	}
-	return w.writer.writeKVs(kvs)
+	tempKvs := make([]common.KvPair, 0)
+	tempKvs = append(tempKvs, kvs[0])
```
Comment (gozssky) [inline br/pkg/lightning/backend/local/engine.go:1065]: It's unnecessary to use a `tempKvs` here. We record the start kv index and make slice of the original kvs. 

`appendRows` is on the critical path, so it's worth avoiding unnecessary allocations.

File: br/pkg/lightning/mydump/region.go [hunk 17]
```diff
@@ -302,6 +312,56 @@ func makeSourceFileRegion(
...
+		}
+		parser, err = NewCSVParser(&cfg.Mydumper.CSV, reader, int64(cfg.Mydumper.ReadBlockSize), ioWorkers, hasHeader, charsetConvertor)
+		if err != nil {
+			return 0, err
+		}
+	case SourceTypeSQL:
+		parser = NewChunkParser(cfg.TiDB.SQLMode, reader, int64(cfg.Mydumper.ReadBlockSize), ioWorkers)
+	default:
+		err = errors.New("unknown source type")
+		return 0, errors.Annotatef(err, "source file %s is none of csv, sql, or parquet file", fileInfo.FileMeta.Path)
```
Comment (gozssky) [inline br/pkg/lightning/mydump/region.go:343]: Use `errors.Errorf()` instead.

File: br/pkg/lightning/restore/meta_manager.go [hunk 18]
```diff
@@ -78,6 +78,9 @@ func (b *dbMetaMgrBuilder) TableMetaMgr(tr *TableRestore) tableMetaMgr {
 type tableMetaMgr interface {
 	InitTableMeta(ctx context.Context) error
 	AllocTableRowIDs(ctx context.Context, rawRowIDMax int64) (*verify.KVChecksum, int64, error)
+	// ReallocTableRowIDs: re-allocate rowIDs across lightning instances. only parallel import needs this
+	// returns: prevMaxRowID, newlyAllocatedMaxRowID, error
```
Comment (gozssky) [inline br/pkg/lightning/restore/meta_manager.go:82]:
```suggestion
	// ReallocTableRowIDs reallocates the row IDs of a table.
	// It returns new rowIDBase and maxRowID or any error it encounters.
	// Note that noopTableMetaMgr has a noop implementation of this function.
	// If maxRowID is 0, caller should maintain rowIDBase and maxRowID itself.
```

File: br/pkg/lightning/restore/table_restore.go [hunk 19]
```diff
@@ -1021,3 +1026,31 @@ func estimateCompactionThreshold(cp *checkpoints.TableCheckpoint, factor int64)
...
 }
+
+func (tr *TableRestore) allocateRowIDs(newRowCount int64, rc *Controller) (int64, int64, error) {
+	tr.rowIDLock.Lock()
+	defer tr.rowIDLock.Unlock()
+	metaMgr := rc.metaMgrBuilder.TableMetaMgr(tr)
+	// try to re-allocate from downstream
+	// if we are using parallel import, rowID should be reconciled globally.
+	// Otherwise, this function will simply return 0.
+	preRowIDMax, newRowIDMax, err := metaMgr.ReallocTableRowIDs(context.Background(), newRowCount)
```
Comment (gozssky) [inline br/pkg/lightning/restore/table_restore.go:1037]:
```suggestion
	newRowIDBase, newRowIDMax, err := metaMgr.ReallocTableRowIDs(context.Background(), newRowCount)
```

File: br/pkg/lightning/restore/restore.go [hunk 20]
```diff
@@ -2023,9 +2026,16 @@ func (rc *Controller) DataCheck(ctx context.Context) error {
...
+	parser           mydump.Parser
+	index            int
+	chunk            *checkpoints.ChunkCheckpoint
+	originalRowIDMax int64
+	curRowIDBase     int64
+	curRowIDMax      int64
+	tableRestore     *TableRestore
+
+	rowCount   int
+	avgRowSize int
```
Comment (gozssky) [inline br/pkg/lightning/restore/restore.go:2038]: Recording total size instead would be more accurate.

File: br/pkg/lightning/restore/table_restore.go (hunk 19 above)
Comment (buchuitoudegou) [reply br/pkg/lightning/restore/table_restore.go:1037]: ReallocTableRowIDs returns the previous maximum rowID though (caller has to +1 by itself). Perhaps I will make it return the new rowID base.

**Comment by buchuitoudegou** [comment]
ptal @gozssky

**Comment by buchuitoudegou** [comment]
ptal @gozssky

File: br/pkg/lightning/backend/kv/sql2kv.go [hunk 21]
```diff
@@ -445,6 +445,56 @@ func isPKCol(colInfo *model.ColumnInfo) bool {
...
+			return rowID > math.MaxInt8
+		}
+		return rowID > math.MaxUint8
+	// BIGINT
+	case mysql.TypeLonglong:
+		if !isUnsigned {
+			return rowID > math.MaxInt64
+		}
+		// impossible for rowID exceeding MaxUint64
+		return uint64(rowID) > math.MaxUint64
```
Comment (gozssky) [inline br/pkg/lightning/backend/kv/sql2kv.go:481]:
```suggestion
```

**Review by gozssky — APPROVED** [review]
