### PR TITLE
executor: fix load data losing connection when batch_dml_size is set

### LINKED ISSUE #22540: load data with auto-random may panic if too many rows
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Prepare a CSV file with more than 60000 rows.
Create a table with auto-random.
Use the load statement to load the data.

### 2. What did you expect to see? (Required)
Load data successfully.

### 3. What did you see instead (Required)

ERROR 2013 (HY000) at line 1: Lost connection to MySQL server during query
### 4. What is your TiDB version? (Required)
4.0.4

Root cause:
When load executes, there are two parts. processStream() produces the data. CommitWork() commit the data.
They use the same txn. Between CommitWork() committing the txn and start a new txn. processStream() may use the invalid txn to get the auto-random value, then the get empty data return an error. But we take the error as a warning:
image
Finally, when using the data, tidb-server panics.

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: Fix  #22540 

Problem Summary: 
When tidb_dml_batch_size is a relatively small(eg: 128/64), load data into a table which has a auto_random column may got lost connection error. 

### What is changed and how it works?

What's Changed:
1. add InsertValues::isLoadData member
2. add InsertValues::txnInUse (a mutex) member
3. lock txnInUse when commit routine needs to refresh txn ctx
4. lock txnInUse when process stream routine needs to generate auto random value

How it Works:

load data use two routine:
1. process stream routine: parse file and generate batch insert task
2. commit routine: read task from channel and do commit

Commit routine will invalid txn after task is committed. And before generate a new txn, process stream routine may use that invalid txn to generate audo random value. So we add a lock to protect txn, make sure process stream routine use a valid txn.

### Related changes
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
  - TestLoadDataAutoRandom
- Manual test (add detailed scripts or steps below)
  1. generate csv files(5W rows)
  2. set @@session.tidb_dml_batch_size = 128;
  3. drop table if exists t;
  4. create table t(c1 bigint auto_random primary key, c2 bigint, c3 bigint);
  5. load data local infile %q into table t (c2, c3);
- No code

Side effects

- Performance regression
    - add a lock when commit task and generate auto random, may got lock conflict and slow down load data performance.

### Release note 

- fix load data lost connection error on tables with auto_random column

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@wshwsh12

**Comment by guo-shaoge** [comment]
@AilinKid

File: server/server_test.go [hunk 1]
```diff
@@ -520,6 +520,44 @@ func (cli *testServerClient) prepareLoadDataFile(c *C, path string, rows ...stri
...
+		config.AllowAllFiles = true
+		config.Params = map[string]string{"sql_mode": "''"}
+	}, "load_data_batch_dml", func(dbt *DBTest) {
+		// Set batch size, and check if load data got a invalid txn error.
+		dbt.mustExec("set @@session.tidb_dml_batch_size = 128")
+		dbt.mustExec("drop table if exists t")
+		dbt.mustExec("create table t(c1 bigint auto_random primary key, c2 bigint, c3 bigint)")
+		dbt.mustExec(fmt.Sprintf("load data local infile %q into table t (c2, c3)", path))
+		rows := dbt.mustQuery("select count(*) from t")
+		cli.checkRows(c, rows, "50000")
```
Comment (XuHuaiyu) [inline server/server_test.go:557]: We also need to check the correctness of the data.

Maybe we can use `select bit_xor(c1), bit_xor(c2), bit_xor(c3) from t`

File: server/tidb_test.go [hunk 2]
```diff
@@ -162,6 +162,10 @@ func (ts *tidbTestSerialSuite) TestLoadDataListPartition(c *C) {
 	ts.runTestLoadDataForListColumnPartition2(c)
 }
 
+func (ts *tidbTestSerialSuite) TestLoadDataBatchDML(c *C) {
```
Comment (XuHuaiyu) [inline server/tidb_test.go:165]: Add a comment for this test, e.g.
``` go
// fix issue22540
```

**Review by AilinKid — COMMENTED** [review]
LGTM

File: server/tidb_test.go (hunk 2 above)
Comment (guo-shaoge) [reply server/tidb_test.go]: done

File: server/server_test.go (hunk 1 above)
Comment (guo-shaoge) [reply server/server_test.go:569]: done. (only c2 and c3 is verified. Because c1 is auto_random column, no way to know its value)

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by XuHuaiyu** [comment]
Have we tested the performance regression?
