### PR TITLE
Cascades optimizer: handle warning messages for inapplicable hints properly

### LINKED ISSUE #62736: Cascades Planner: Warning messages are lost when hints are inapplicable
## Bug Report

This issue was discovered while refactoring [TestIssue37520](https://github1s.com/pingcap/tidb/blob/v9.0.0-beta.2.pre/pkg/planner/core/casetest/physicalplantest/physical_plan_test.go#L219).

When a hint is inapplicable, the optimizer in cascades mode can't properly pass through the warning messages.

### 1. Minimal reproduce step (Required)
run test  [TestIssue37520](https://github1s.com/pingcap/tidb/blob/v9.0.0-beta.2.pre/pkg/planner/core/casetest/physicalplantest/physical_plan_test.go#L219) with cascades mode on.

### 2. What did you expect to see? (Required)
```
mysql> explain select /*+ inl_join(t2) */ a, (select b from t1 where t1.a = t2.b) from t2;
+-----------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------+
| id                          | estRows  | task      | access object | operator info                                                               |
+-----------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------+
| HashJoin_18                 | 12500.00 | root      |               | left outer join, left side:TableReader_21, equal:[eq(test.t2.b, test.t1.a)] |
| ├─TableReader_25(Build)     | 10000.00 | root      |               | data:TableFullScan_24                                                       |
| │ └─TableFullScan_24        | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                              |
| └─TableReader_21(Probe)     | 10000.00 | root      |               | data:TableFullScan_20                                                       |
|   └─TableFullScan_20        | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                              |
+-----------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------+
5 rows in set, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+----------------------------------------------------------------------------+
| Level   | Code | Message                                                                    |
+---------+------+----------------------------------------------------------------------------+
| Warning | 1815 | Optimizer Hint /*+ INL_JOIN(t2) */ or /*+ TIDB_INLJ(t2) */ is inapplicable |
+---------+------+----------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

### 3. What did you see instead (Required)
```
mysql> set session tidb_enable_cascades_planner=on;
Query OK, 0 rows affected (0.01 sec)


mysql> explain select /*+ inl_join(t2) */ a, (select b from t1 where t1.a = t2.b) from t2;
+-----------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------+
| id                          | estRows  | task      | access object | operator info                                                               |
+-----------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------+
| HashJoin_18                 | 12500.00 | root      |               | left outer join, left side:TableReader_21, equal:[eq(test.t2.b, test.t1.a)] |
| ├─TableReader_25(Build)     | 10000.00 | root      |               | data:TableFullScan_24                                                       |
| │ └─TableFullScan_24        | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                              |
| └─TableReader_21(Probe)     | 10000.00 | root      |               | data:TableFullScan_20                                                       |
|   └─TableFullScan_20        | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                              |
+-----------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------+
5 rows in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by King-Dylan**
### What problem does this PR solve?

Issue Number: close #62736, ref #62328

Problem Summary:
When a hint is inapplicable, the optimizer in cascades mode can't properly pass through the warning messages.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/cascades/impl/impl_and_cost.go [hunk 1]
```diff
@@ -117,6 +117,12 @@ func ImplementMemoAndCost(rootGroup *memo.Group, planCounter *base.PlanCounterTp
 		}
 		return nil, 0, plannererrors.ErrInternal.GenWithStackByArgs(errMsg)
 	}
+
+	// collect the warnings from task.
+	if warnings := task.GetWarnings(); len(warnings) > 0 {
```
Comment (AilinKid) [inline pkg/planner/cascades/impl/impl_and_cost.go]: we can make interface clean.
actually the the first version of task warnings mechanism has the method, then i remove it instead with
image

Comment (AilinKid) [reply pkg/planner/cascades/impl/impl_and_cost.go]: because the final task we got from optimization must be a root task

**Review by AilinKid — APPROVED** [review]
