### PR TITLE
ddl: trim enum and set trailing spaces automatically

### LINKED ISSUE #18949: mysql compatibility: tidb does not trim enum spaces automatically
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql root@127.0.0.1:test> create table t (a enum(' 1 '))
Query OK, 0 rows affected
Time: 0.004s
```

### 2. What did you expect to see? (Required)
On MySQL:
```
mysql root@127.0.0.1:test> show create table t
+-------+--------------------------------------------------------------------+
| Table | Create Table                                                       |
+-------+--------------------------------------------------------------------+
| t     | CREATE TABLE `t` (                                                 |
|       |   `a` enum(' 1') DEFAULT NULL                                      |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+--------------------------------------------------------------------+
1 row in set
Time: 0.016s
```

### 3. What did you see instead (Required)
On TiDB:
```
mysql root@127.0.0.1:test> show create table t
+-------+-------------------------------------------------------------+
| Table | Create Table                                                |
+-------+-------------------------------------------------------------+
| t     | CREATE TABLE `t` (                                          |
|       |   `a` enum(' 1 ') DEFAULT NULL                              |
|       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------+
1 row in set
Time: 0.014s
```

### 4. Affected version (Required)

```
mysql root@127.0.0.1:test> select tidb_version()
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-878-g6cf50d3f8                     |
| Edition: Community                                                |
| Git Commit Hash: 6cf50d3f898cadf3e74adaa6c12ab0e671bd9104         |
| Git Branch: master                                                |
| UTC Build Time: 2020-08-03 10:10:23                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
1 row in set
Time: 0.014s
```

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

Issue Number: close #18949 
PR in parser https://github.com/pingcap/parser/pull/1006

### What is changed and how it works?

- update parser

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

- fix a bug that tidb does not trim enum spaces automatically

### CODE REVIEW

File: expression/integration_test.go [hunk 1]
```diff
@@ -7113,3 +7113,19 @@ func (s *testIntegrationSerialSuite) TestIssue17063(c *C) {
...
+
+func (s *testIntegrationSerialSuite) TestIssue18949(c *C) {
+	collate.SetNewCollationEnabledForTest(true)
+	defer collate.SetNewCollationEnabledForTest(false)
+
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec(`use test;`)
+	tk.MustExec(`drop table if exists t;`)
+	tk.MustExec(`create table t(a enum('1 ', '1\t', ' 1 '), b set('1 ', '1\t', ' 1 '));`)
+	tk.MustQuery("show create table t").Check(
```
Comment (wjhuang2016) [inline expression/integration_test.go:7125]: We have better use `c.Assert(result, Matches, "regex_pattern")` style. If we change the other part in `show create table`, we don't need to modify this test again.

Comment (xiongjiwei) [reply expression/integration_test.go]: updated

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -616,6 +616,14 @@ func columnDefToCol(ctx sessionctx.Context, offset int, colDef *ast.ColumnDef, o
...
 		col.Flag |= mysql.ZerofillFlag
 	}
+	// Trailing spaces are automatically deleted from SET/ENUM member values in the table definition when a table is created.
+	// https://dev.mysql.com/doc/refman/8.0/en/enum.html#enum-literals
+	// https://dev.mysql.com/doc/refman/8.0/en/set.html
+	if col.Tp == mysql.TypeEnum || col.Tp == mysql.TypeSet {
+		for i := range col.Elems {
+			col.Elems[i] = collate.TruncateTailingSpace(col.Elems[i])
+		}
+	}
```
Comment (zimulala) [inline ddl/ddl_api.go:626]: Do we need to do this logic in `processColumnOptions` which use in `alter table... change column ...`？
We can add the test of `alter table t change a aa enum('1 ', '1\t', ' 1 ');`  to `TestIssue18949`.

Comment (xiongjiwei) [reply ddl/ddl_api.go:626]: you are right, it is better trim trailing spaces in parser. I going to revert this PR.   This PR should only add tests for it

**Comment by wjhuang2016** [comment]
PTAL https://github.com/pingcap/tidb/issues/19697

**Review by zimulala — APPROVED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Comment by tangenta** [comment]
@xiongjiwei Please update the parser dependency and resolve the conflict, we need to merge this PR ASAP.

**Comment by xiongjiwei** [comment]
@tangenta PTAL

**Review by tangenta — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
