### PR TITLE
executor: set handle changed when col gets auto-updated

### LINKED ISSUE #44565: `ON UPDATE CURRENT_TIMESTAMP` may lead to data inconsistency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* t */ drop table if exists t;
-- t >> 0 rows affected
/* t */ create table t (id int, val int, updated_at timestamp(0) not null default current_timestamp(0) on update current_timestamp(0), primary key (id, updated_at), key idx_updated_at (updated_at));
-- t >> 0 rows affected
/* t */ insert into t values (1, 10, '2023-06-10 22:30:00');
-- t >> 1 rows affected
/* t */ update t force index(primary) set val = 11 where updated_at = '2023-06-10 22:30:00';
-- t >> 1 rows affected
/* t */ admin check table t;
-- t >> E8134: data inconsistency in table: t, index: idx_updated_at, col: updated_at, handle: "{1, 1851072800110936064}", index-values:"KindMysqlTime 2023-06-10 22:33:27" != record-values:"KindMysqlTime 2023-06-10 22:30:00", compare err:<nil>
```

### 2. What did you expect to see? (Required)

No error reported by admin-check.

### 3. What did you see instead (Required)

Found data inconsistency.

### 4. What is your TiDB version? (Required)

v6.5.1, also affects master and all other versions.

### PR DESCRIPTION
**Pull request by zyguan**
### What problem does this PR solve?

Issue Number: close #44565

Problem Summary: We didn't set `handleChanged` properly when a on-update-now column gets updated automatically and it's also a pk column, which leads to #44565 .

### What is changed and how it works?

Set `handleChanged` properly in that case.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/write.go [hunk 1]
```diff
@@ -147,6 +147,11 @@ func updateRecord(ctx context.Context, sctx sessionctx.Context, h kv.Handle, old
 			if v, err := expression.GetTimeValue(sctx, strings.ToUpper(ast.CurrentTimestamp), col.GetType(), col.GetDecimal(), nil); err == nil {
 				newData[i] = v
 				modified[i] = true
+				// Only a TIMESTAMP and DATETIME column can be automatically updated, so it cannot be PKIsHandle.
```
Comment (cfzjywxk) [inline executor/write.go:150]: Maybe we could add an assertion here?

**Review by cfzjywxk — APPROVED** [review]
LGTM

File: executor/write.go [hunk 2]
```diff
@@ -147,6 +147,14 @@ func updateRecord(ctx context.Context, sctx sessionctx.Context, h kv.Handle, old
 			if v, err := expression.GetTimeValue(sctx, strings.ToUpper(ast.CurrentTimestamp), col.GetType(), col.GetDecimal(), nil); err == nil {
 				newData[i] = v
 				modified[i] = true
+				// Only TIMESTAMP and DATETIME columns can be automatically updated, so it cannot be PKIsHandle.
+				// Ref: https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html
+				if col.IsPKHandleColumn(t.Meta()) {
+					panic("on-update-now col should never be pk-is-handle")
```
Comment (cfzjywxk) [inline executor/write.go:153]: Or return an error to the upper layer and reject such kind of usage.

**Review by crazycs520 — APPROVED** [review]
