### PR TITLE
planner: store the hints of session variable

### LINKED ISSUE #45812: Some hints do not take effect for cached plan
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Prepare sysbench table with 1,000,000 rows.

```sql
mysql> prepare stmt from 'select /*+ MAX_EXECUTION_TIME(1) */ sum(id) from sbtest1';
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt;
mysql> execute stmt; -- run it two times
```

### 2. What did you expect to see? (Required)

```sql
mysql> execute stmt;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
mysql> execute stmt;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
```

### 3. What did you see instead (Required)

```sql
mysql> execute stmt;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded
mysql> execute stmt;
+--------------+
| sum(id)      |
+--------------+
| 501229432608 |
+--------------+
1 row in set (0.34 sec)
```

The second time executing this statament, the hint `/*+ MAX_EXECUTION_TIME(1) */ ` do not take effect.

### 4. What is your TiDB version? (Required)

```
Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 522a00840385dfa43509a3af2bc79e6ff50252a8
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-03 14:26:07
GoVersion: go1.20.7
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by you06**
### What problem does this PR solve?

Issue Number: close #45812

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/plan_cache.go [hunk 1]
```diff
@@ -285,6 +285,7 @@ func getCachedPlan(sctx sessionctx.Context, isNonPrepared bool, cacheKey kvcache
 		core_metrics.GetPlanCacheHitCounter(isNonPrepared).Inc()
 	}
 	stmtCtx.SetPlanDigest(stmt.NormalizedPlan, stmt.PlanDigest)
+	stmtCtx.StmtHints = cachedVal.sessVarHints
```
Comment (qw4990) [inline planner/core/plan_cache.go:288]: The `PointGet` short path function `getCachedPointPlan` should be updated as well.

File: session/test/vars/vars_test.go [hunk 2]
```diff
@@ -604,3 +605,63 @@ func TestGetSysVariables(t *testing.T) {
...
+			hint: "RESOURCE_GROUP(rg1)",
+			check: func(stmtHint *stmtctx.StmtHints) {
+				require.True(t, stmtHint.HasResourceGroup)
+				require.Equal(t, "rg1", stmtHint.ResourceGroup)
+			},
+		},
+	}
+
+	for i, check := range hintChecks {
+		tk.MustExec(fmt.Sprintf("prepare stmt%d from 'select /*+ %s */ * from t'", i, check.hint))
```
Comment (qw4990) [inline session/test/vars/vars_test.go:661]: Please add one more test case for the `PointGet` plan.

File: planner/core/plan_cache_utils.go [hunk 3]
```diff
@@ -383,7 +386,7 @@ func (v *PlanCacheValue) MemoryUsage() (sum int64) {
 
 // NewPlanCacheValue creates a SQLCacheValue.
 func NewPlanCacheValue(plan Plan, names []*types.FieldName, srcMap map[*model.TableInfo]bool,
-	matchOpts *utilpc.PlanCacheMatchOpts) *PlanCacheValue {
+	matchOpts *utilpc.PlanCacheMatchOpts, sessVarHints stmtctx.StmtHints) *PlanCacheValue {
```
Comment (time-and-fate) [inline planner/core/plan_cache_utils.go:389]: Looks like we should use a pointer here.

File: planner/core/plan_cache.go (hunk 1 above)
Comment (you06) [reply planner/core/plan_cache.go]: Fixed.

File: session/test/vars/vars_test.go (hunk 2 above)
Comment (you06) [reply session/test/vars/vars_test.go:662]: Done

File: planner/core/plan_cache_utils.go (hunk 3 above)
Comment (you06) [reply planner/core/plan_cache_utils.go]: I clone it because take address may cause the cached stmt hints reset from somewhere unknown.

Comment (time-and-fate) [reply planner/core/plan_cache_utils.go]: Yes. A clone is needed, `stmtctx` will be shared across statements in a session, therefore `stmtctx.StmtHints` will be shared since it's an embedded struct as a value.

**Review by time-and-fate — COMMENTED** [review]
If I understand it correctly,  we can use pointers in the return value of `Clone()`, in `struct PlanCacheValue`, and in `struct PointGetPlan`. This should avoid some unnecessary copies.

**Comment by you06** [comment]
@time-and-fate updated with a pointer.

**Review by time-and-fate — APPROVED** [review]
