### PR TITLE
executor, statistics: avoid analyze hang on save error

### LINKED ISSUE #65915: `ANALYZE` statement freezes if `SaveAnalyzeResultToStorage` meets error when analyzeing partitioned table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a int, b int, c int, d int, e int, f int, g int) partition by hash(a) partitions 4096;
analyze table t;
```

### 2. What did you expect to see? (Required)

Analyze success finally.

### 3. What did you see instead (Required)

Analyze statement freezes forever, and can't be `KILL`ed.

```sql
select * from mysql.analyze_jobs;
```
```
+------+---------------------+--------------+------------+----------------+--------------------------------------------------------------------+----------------+---------------------+---------------------+---------+-------------------------------------------------------------------+----------------+------------+
| id   | update_time         | table_schema | table_name | partition_name | job_info                                                           | processed_rows | start_time          | end_time            | state   | fail_reason                                                       | instance       | process_id |
+------+---------------------+--------------+------------+----------------+--------------------------------------------------------------------+----------------+---------------------+---------------------+---------+-------------------------------------------------------------------+----------------+------------+
|    1 | 2026-01-29 20:13:05 | test         | t          | p0             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | 2026-01-29 20:13:05 | failed  | [tikv:1205]Lock wait timeout exceeded; try restarting transaction | 127.0.0.1:4000 |       NULL |
|    2 | 2026-01-29 20:13:05 | test         | t          | p1             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | 2026-01-29 20:13:05 | failed  | [tikv:1205]Lock wait timeout exceeded; try restarting transaction | 127.0.0.1:4000 |       NULL |
|    3 | 2026-01-29 20:12:15 | test         | t          | p2             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | NULL                | running | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|    4 | 2026-01-29 20:12:15 | test         | t          | p3             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | NULL                | running | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|    5 | 2026-01-29 20:12:15 | test         | t          | p4             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | NULL                | running | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|    6 | 2026-01-29 20:12:15 | test         | t          | p5             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | NULL                | running | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|    7 | 2026-01-29 20:12:15 | test         | t          | p6             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | NULL                | running | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|    8 | 2026-01-29 20:12:15 | test         | t          | p7             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | 2026-01-29 20:12:15 | NULL                | running | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|    9 | 2026-01-29 20:11:36 | test         | t          | p8             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | NULL                | NULL                | pending | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|   10 | 2026-01-29 20:11:36 | test         | t          | p9             | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | NULL                | NULL                | pending | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
|   11 | 2026-01-29 20:11:36 | test         | t          | p10            | analyze table all columns with 256 buckets, 100 topn, 1 samplerate |              0 | NULL                | NULL                | pending | NULL                                                              | 127.0.0.1:4000 | 2141192198 |
....
```

### 4. What is your TiDB version? (Required)

v8.5.4, master

### PR DESCRIPTION
**Pull request by 0xPoe**
### What problem does this PR solve?

Issue Number: close #65915

Problem Summary:
ANALYZE on heavily partitioned tables can hang when saving stats fails (for example, lock wait timeout), because save workers exit early and analyze workers block on result channels.

### What changed and how does it work?
- Add a failpoint to simulate save errors and a unit test that asserts ANALYZE returns an error instead of hanging.
- Keep analyze save workers draining results after a save failure while reporting the first error.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Unit test:
- `make failpoint-enable && ( pushd pkg/executor >/dev/null; go test -run TestAnalyzeSaveResultErrorDoesNotHang --tags=intest; rc=$?; popd >/dev/null; make failpoint-disable; exit $rc )`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a potential ANALYZE hang when saving statistics fails on partitioned tables.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Enhanced error handling in analyze operations to ensure stability and proper behavior during storage save failures.
  * Improved handling of system interrupt scenarios to maintain operation continuity and error reporting.

* **Tests**
  * Added comprehensive test coverage for analyze operations under storage failure conditions.
  * Added tests to validate analyze operation behavior during system interrupt scenarios and verify proper signal handling.

### CODE REVIEW

File: pkg/executor/analyze_worker.go [hunk 1]
```diff
@@ -44,30 +45,46 @@ func newAnalyzeSaveStatsWorker(
 }
 
 func (worker *analyzeSaveStatsWorker) run(ctx context.Context, statsHandle *handle.Handle, analyzeSnapshot bool) {
+	errReported := false
+	var drainErr error
```
Comment (0xPoe) [inline pkg/executor/analyze_worker.go:59]: Trick: This error is used solely for handling the kill signal. This allows us to attempt saving the statistics of other partitions, even if the previous partition encountered an error while saving the result. I believe this is acceptable because, prior to this fix, we often ended up in this situation: the analyze command failed, but the statistics were partially stored. Therefore, I think this fix won't worsen the situation.

Comment (0xPoe) [reply pkg/executor/analyze_worker.go:59]: I have added it as code comment: https://github.com/pingcap/tidb/pull/66169/changes/8b13c992dd7c14f330b8eecbf870bbf88817f195

File: pkg/executor/analyze_worker.go [hunk 2]
```diff
@@ -44,30 +45,49 @@ func newAnalyzeSaveStatsWorker(
...
 			logutil.BgLogger().Error("analyze save stats worker panicked", zap.Any("recover", r), zap.Stack("stack"))
-			worker.errCh <- getAnalyzePanicErr(r)
+			if !errReported {
+				worker.errCh <- getAnalyzePanicErr(r)
+				errReported = true
+			}
 		}
 	}()
 	for results := range worker.resultsCh {
+		if drainErr != nil {
```
Comment (time-and-fate) [inline pkg/executor/analyze_worker.go:70]: I think we need some comments to explain that the kill signal will trigger the "drain mode" and the behavior of the "drain mode".

File: pkg/executor/analyze_worker.go [hunk 3]
```diff
@@ -44,30 +45,49 @@ func newAnalyzeSaveStatsWorker(
 }
 
 func (worker *analyzeSaveStatsWorker) run(ctx context.Context, statsHandle *handle.Handle, analyzeSnapshot bool) {
+	errReported := false
```
Comment (time-and-fate) [inline pkg/executor/analyze_worker.go:55]: We use this variable to make sure each worker sends one error at most, right? I think we need some comments.

File: pkg/executor/analyze_worker.go [hunk 4]
```diff
@@ -44,30 +45,49 @@ func newAnalyzeSaveStatsWorker(
...
+	// switch to drain mode, so we can still try to persist stats for later
+	// partitions. ANALYZE may already end up with partially persisted stats.
+	var drainErr error
 	defer func() {
 		if r := recover(); r != nil {
 			logutil.BgLogger().Error("analyze save stats worker panicked", zap.Any("recover", r), zap.Stack("stack"))
-			worker.errCh <- getAnalyzePanicErr(r)
+			if !errReported {
+				worker.errCh <- getAnalyzePanicErr(r)
+				errReported = true
```
Comment (henrybw) [inline pkg/executor/analyze_worker.go]: Nit: Since this is in a deferred function, setting `errReported` here shouldn't have any effect.

File: pkg/executor/analyze_worker.go (hunk 3 above)
Comment (henrybw) [inline pkg/executor/analyze_worker.go:55]: I'm wondering if this is really necessary. The caller, `handleResultsErrorWithConcurrency`, is able to handle receiving multiple errors from the error channel: it just dedupes and joins them into one error. Plus, `drainErr` is guaranteed to only be sent once (because of the `if drainErr != nil` block).

If we send all errors to the channel rather than only the first one, is that too noisy?

**Review by henrybw — APPROVED** [review]

File: pkg/executor/analyze_worker.go (hunk 3 above)
Comment (0xPoe) [reply pkg/executor/analyze_worker.go:55]: I think the reason is that this is a bounded channel. If we have too many partitions and each partition reports one error, the channel will become full. We can only drain this channel when all workers have finished, but a full channel will block the workers. Therefore, I believe this could cause another hang in some cases.

**Comment by 0xPoe** [comment]
> if a worker encounters an actual save error (not draining), would it be possible for it to kill the other workers? Either by sending an error or using the SQL killer?

Sending another error through the channel may create more chaos, and using the SQL killer might be confusing. One possible solution is to pass a context and cancel it once we encounter an error. However, the challenge lies in determining how and who will respond to cancel this context. The fundamental issue is that the caller only handles errors after all results have been sent and processed. But during this process, the error may be reported, allowing us to stop and cancel the entire workflow.

File: pkg/executor/analyze_worker.go (hunk 2 above)
Comment (0xPoe) [reply pkg/executor/analyze_worker.go:70]: Added in https://github.com/pingcap/tidb/pull/66169/changes/07fe17022e612e69d42ef52fc62eb47bcc1e5977

File: pkg/executor/analyze_worker.go (hunk 3 above)
Comment (0xPoe) [reply pkg/executor/analyze_worker.go:55]: Added in https://github.com/pingcap/tidb/pull/66169/changes/07fe17022e612e69d42ef52fc62eb47bcc1e5977
