### PR TITLE
test: stabilize TestClusterIndexShowTableRegion

### LINKED ISSUE #18778: executor_test.go:testSplitTable.TestClusterIndexShowTableRegion failed
executor_test.go:testSplitTable.TestClusterIndexShowTableRegion

```
[2020-07-24T08:53:02.120Z] ----------------------------------------------------------------------
[2020-07-24T08:53:02.120Z] FAIL: executor_test.go:4349: testSplitTable.TestClusterIndexShowTableRegion
[2020-07-24T08:53:02.120Z]
[2020-07-24T08:53:02.120Z] executor_test.go:4371:
[2020-07-24T08:53:02.120Z]     // Check the region start key is int64.
[2020-07-24T08:53:02.120Z]     c.Assert(rows[0][1], Matches, fmt.Sprintf("t_%d_", tbl.Meta().ID))
[2020-07-24T08:53:02.120Z] ... value string = "t_47_5f7203800000000000000183800000000000"
[2020-07-24T08:53:02.120Z] ... regex string = "t_50_"
[2020-07-24T08:53:02.120Z]
```

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/42622/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/42675/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/42672/display/redirect
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/43848/display/redirect

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #18778 

Problem Summary:

A patch for #18721: To make sure a region is split for a newly created table, the global variable `tidb_scatter_region` should be set to `1`.

### What is changed and how it works?

What's Changed:
Add `set global tidb_scatter_region = 1` before testing `show table regions`.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- No release note

### CODE REVIEW

File: executor/executor_test.go [hunk 1]
```diff
@@ -4395,6 +4395,7 @@ func (s *testSplitTable) TestClusterIndexSplitTableIntegration(c *C) {
 func (s *testSplitTable) TestClusterIndexShowTableRegion(c *C) {
 	tk := testkit.NewTestKit(c, s.store)
 	atomic.StoreUint32(&ddl.EnableSplitTableRegion, 1)
+	tk.MustExec("set global tidb_scatter_region = 1")
```
Comment (djshow832) [inline executor/executor_test.go:4398]: Will it affect other test cases? How about defer setting it back?

Comment (tangenta) [reply executor/executor_test.go:4398]: The test suite `testSplitTable` is serial and expected `tidb_scatter_region == 1`, it won't affect other test cases.

Comment (AilinKid) [reply executor/executor_test.go:4398]: should use defer set it back to 0? otherwise it will take effect int following Testxxx in `testSplitTable Suite` or that's what you exactly want.

Comment (tangenta) [reply executor/executor_test.go:4398]: It will take effect on the following tests. But it does not matter.
