### PR TITLE
linter: Recover() must be directly called by defer

### LINKED ISSUE #44191: add linter to avoid incorrect usage of tidbutil.Recover
## Enhancement

It is the wrong usage. it is unable to get recover info.
```
defer func() {
   tidbutil.Recover(xxxx)
}()
```

Here is the right usage.

```
defer tidbutil.Recover(xxxx)
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #44191

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

```
compilepkg: nogo: errors found by nogo during build-time code analysis:

util/topsql/collector/cpu.go:107:3: Recover() should be directly called by defer (recover)
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: build/linter/etcdconfig/analyzer.go [hunk 1]
```diff
@@ -38,17 +39,7 @@ const (
 // Adapted from https://github.com/mdempsky/unconvert/blob/beb68d938016d2dec1d1b078054f4d3db25f97be/unconvert.go#L371-L414.
```
Comment (lance6716) [inline build/linter/etcdconfig/analyzer.go:39]:
```suggestion
```

**Review by wjhuang2016 — APPROVED** [review]
