### PR TITLE
 planner: not pruning column used by union scan condition

### LINKED ISSUE #21607: Aggregation on table with absurdity selection in transaction reports 'column not found'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t (a int, b int);
begin;
insert into t values (1, 2);
select count(*) from t where b = 1 and b in (3);
```
```console
ERROR 1105 (HY000): Can't find column test.t.b in schema Column: [test.t._tidb_rowid] Unique key: []
```

More test cases:
```sql
set @@tidb_enable_clustered_index = 1;
drop table if exists t;
create table t (a char(2), b int, primary key (a));
begin;
insert into t values ('1', 2);
select count(*) from t where b = 1 and b in (3);
```
```console
ERROR 1105 (HY000): Can't find column test.t.b in schema Column: [test.t.a] Unique key: [[test.t.a]]
```

```sql
set @@tidb_enable_clustered_index = 0;
drop table if exists t;
create table t (a char(2), b int, primary key (a));
begin;
insert into t values ('1', 2);
select count(*) from t where b = 1 and b in (3);
```
```console
ERROR 1105 (HY000): Can't find column test.t.b in schema Column: [test.t._tidb_rowid] Unique key: []
```

### 2. What did you expect to see? (Required)

```console
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```console
ERROR 1105 (HY000)
```

### 4. What is your TiDB version? (Required)

master `8eaca0ecd4a70ead77c7bb02dd8f038b7c65033e`

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #21607 

Problem Summary:

```sql
drop table if exists t;
create table t (a int, b int);
begin;
insert into t values (1, 2);
select count(*) from t where b = 1 and b in (3);
```
```console
ERROR 1105 (HY000): Can't find column test.t.b in schema Column: [test.t._tidb_rowid] Unique key: []
```

Copy from https://github.com/pingcap/tidb/issues/21607#issuecomment-741659275:

> - Absurdity conditions like `where b = 1 and b in (3)` build a `TableDual` operand with schema `[_tidb_rowid]`.
> - When the optimizer resolves indices, `PhysicalUnionScan` also resolves the indices of columns in the condition (it is `[b]`). 
> 
> Since the column `b` is not found in schema `[_tidb_rowid]`, an error is reported.
> ```console
> ERROR 1105 (HY000): Can't find column test.t.b in schema Column: [test.t._tidb_rowid] Unique key: []
> ```

The schema of `TableDual`(`[_tidb_rowid]`) is inheritated from `DataSource`. When `pddSolver` do predicate-push-down optimization, condition `where b = 1 and b in (3)` is optimized to `0` by `PropagateConstant`. Thus, the `columnPruner` prunes column `b` further. Finally, the schema of `DataSource` becomes `[_tidb_rowid]`.

### What is changed and how it works?

This PR extract the columns in the condition of `LogicalUnionScan` and prevent them from pruning. In this way, the schema of `TableDual` will be `[_tidb_rowid, b]`.

Alternative solutions:
 - Remove unused columns in `UnionScan` condition. We can do `PropagateConstant` on the conditions of `UnionScan`, but this will change the explain info and break a lot of tests.

What's Changed: Omitted.

How it Works: Omitted.

### Related changes

N/A

### Check List 

Tests 

- Unit test
- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: planner/core/rule_column_pruning.go [hunk 1]
```diff
@@ -219,6 +219,8 @@ func (p *LogicalUnionScan) PruneColumns(parentUsedCols []*expression.Column) err
 	for i := 0; i < p.handleCols.NumCols(); i++ {
 		parentUsedCols = append(parentUsedCols, p.handleCols.GetCol(i))
 	}
+	condCols := expression.ExtractColumnsFromExpressions(nil, p.conditions, nil)
```
Comment (wjhuang2016) [inline planner/core/rule_column_pruning.go:222]: Could you test the generated column?

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
