### PR TITLE
executor: fix race when collecting telemetry info of batch copr

### LINKED ISSUE #41412: data race when building executor
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_mysql_test/detail/ghpr_mysql_test/15018/pipeline/

### 2. What did you expect to see? (Required)

No race detected.

### 3. What did you see instead (Required)

```log
WARNING: DATA RACE

Write at 0x00c0388895d9 by goroutine 867628:
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildIndexLookUpReaderForIndexJoin()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/builder.go:4472 +0x11d
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/builder.go:4114 +0xa84
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/builder.go:4103 +0x328
  github.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:690 +0x128
  github.com/pingcap/tidb/executor.(*innerWorker).handleTask()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:528 +0x1a4
  github.com/pingcap/tidb/executor.(*innerWorker).run()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:502 +0x1be
  github.com/pingcap/tidb/executor.(*IndexLookUpJoin).startWorkers.func2()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:193 +0x64

Previous write at 0x00c0388895d9 by goroutine 867631:
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildIndexLookUpReaderForIndexJoin()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/builder.go:4472 +0x11d
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/builder.go:4114 +0xa84
  github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/builder.go:4103 +0x328
  github.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:690 +0x128
  github.com/pingcap/tidb/executor.(*innerWorker).handleTask()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:528 +0x1a4
  github.com/pingcap/tidb/executor.(*innerWorker).run()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:502 +0x1be
  github.com/pingcap/tidb/executor.(*IndexLookUpJoin).startWorkers.func2()
      /home/jenkins/agent/workspace/pingcap/tidb/ghpr_mysql_test/tidb/executor/index_lookup_join.go:193 +0x64
```

### 4. What is your TiDB version? (Required)

0b6ccdcc7dce784cbd263778b31982334c18a9ff

### PR DESCRIPTION
**Pull request by you06**
Signed-off-by: you06 <you1474600@gmail.com>

### What problem does this PR solve?

Issue Number: close #41412

Problem Summary:

### What is changed and how it works?

The build function may be called concurrently when building executors on probe side, use an atomic variable to avoid data race

```bssh
» go test -race ./executor/issuetest -run TestIssueRaceWhenBuildingExecutorConcurrently --tags=intest
ok      github.com/pingcap/tidb/executor/issuetest      15.110s
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the data race of store batch coprocessor telemetry stats.
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: executor/index_lookup_merge_join_test.go [hunk 1]
```diff
@@ -226,3 +226,16 @@ func TestIssue24473AndIssue25669(t *testing.T) {
 	tk.MustQuery("SELECT /*+ inl_merge_join (t2,t3) */ t2.a,t3.a FROM x t2 inner join x t3 on t2.a = t3.a;").Sort().Check(
 		testkit.Rows("b b", "x x", "x x", "x x", "x x", "y y"))
 }
+
+func TestIssue41412(t *testing.T) {
```
Comment (hawkingrei) [inline executor/index_lookup_merge_join_test.go:230]: Please move it into ```issuetest``` or give this case a readable name.

**Review by cfzjywxk — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
