### PR TITLE
planner: fix wrong index merge selection (#22825)

### LINKED ISSUE #22807: index merge is not used as expected
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table index_testing(
id int not null,
c1 varchar(255),
c2 varchar(255),
c3 varchar(255),
c4 varchar(255),
aid bigint,
created_at timestamp,
primary key (id)
);create index aid_c1 on index_testing(aid,c1);
create index aid_c2 on index_testing(aid,c2);
create index aid_c3 on index_testing(aid,c3);
create index aid_c4 on index_testing(aid,c4);
create index testing_created on index_testing(created_at);
set @@tidb_enable_index_merge="ON";
desc select /*+ USE_INDEX_MERGE(index_testing, aid_c1, aid_c2) */ * from index_testing where (aid = 1 and c1="aaa") or (aid = 2 and c2="bbb");
+-------------------------------+---------+-----------+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows | task      | access object                              | operator info                                                                                                                                  |
+-------------------------------+---------+-----------+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_11                | 8.08    | root      |                                            |                                                                                                                                                |
| ├─IndexRangeScan_8(Build)     | 10.10   | cop[tikv] | table:index_testing, index:aid_c1(aid, c1) | range:[1 "aaa",1 "aaa"], [2,2], keep order:false, stats:pseudo                                                                                 |
| └─Selection_10(Probe)         | 8.08    | cop[tikv] |                                            | or(and(eq(test.index_testing.aid, 1), eq(test.index_testing.c1, "aaa")), and(eq(test.index_testing.aid, 2), eq(test.index_testing.c2, "bbb"))) |
|   └─TableRowIDScan_9          | 10.10   | cop[tikv] | table:index_testing                        | keep order:false, stats:pseudo                                                                                                                 |
+-------------------------------+---------+-----------+--------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+
4 rows in set, 1 warning (0.00 sec)
```
### 2. What did you expect to see? (Required)
index merge is used.
### 3. What did you see instead (Required)
indexLookUp
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #22825 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/22924
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/22924:release-4.0-806097c2e529
```

---

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #22807 

Problem Summary:

Previously we chose the index with the most columns, which is not accurate. We should use the index with the minimal estimated row count.

### What is changed and how it works?

Choose the index with the minimal estimated row count for index merge.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- fix wrong index merge selection

### CODE REVIEW

**Review by winoros — APPROVED** [review]

File: planner/core/stats.go [hunk 1]
```diff
@@ -437,26 +448,22 @@ func (ds *DataSource) accessPathsForConds(conditions []expression.Expression, us
...
-		if current > maxCols {
-			maxColsIndex = i
-			maxCols = current
+	minEstRowIndex := 0
+	minEstRow := math.MaxFloat64
+	for i := 0; i < len(indexAccessPaths); i++ {
+		rc := indexAccessPaths[i].CountAfterAccess
+		if rc < minEstRow {
+			minEstRowIndex = i
+			minEstRow = rc
```
Comment (eurekaka) [inline planner/core/stats.go:463]: Shall we cherry-pick the full changes of https://github.com/pingcap/tidb/pull/23141 to this PR? otherwise the code / behavior may be different on 4.0 / master then.

Comment (wjhuang2016) [reply planner/core/stats.go:463]: Ok, but the explain test is wrong, do you have any idea?
