### PR TITLE
expression: handle invalid argument for addtime and subtime function 

### LINKED ISSUE #12342: different result addtime with two string arguments.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
select addtime('1', 'xxcvadfgasd');
select addtime('xxcvadfgasd', '1');
```

2. What did you expect to see?

```mysql
mysql> select addtime('1', 'xxcvadfgasd');
+-----------------------------+
| addtime('1', 'xxcvadfgasd') |
+-----------------------------+
| 00:00:01                    |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------+
| Level   | Code | Message                                       |
+---------+------+-----------------------------------------------+
| Warning | 1292 | Truncated incorrect time value: 'xxcvadfgasd' |
+---------+------+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> select addtime('xxcvadfgasd', '1');
+-----------------------------+
| addtime('xxcvadfgasd', '1') |
+-----------------------------+
| 00:00:01                    |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------+
| Level   | Code | Message                                       |
+---------+------+-----------------------------------------------+
| Warning | 1292 | Truncated incorrect time value: 'xxcvadfgasd' |
+---------+------+-----------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```mysql
mysql> select addtime('1', 'xxcvadfgasd');
+-----------------------------+
| addtime('1', 'xxcvadfgasd') |
+-----------------------------+
| NULL                        |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------+
| Level   | Code | Message                                       |
+---------+------+-----------------------------------------------+
| Warning | 1292 | Truncated incorrect time value: 'xxcvadfgasd' |
+---------+------+-----------------------------------------------+
1 row in set (0.00 sec)

mysql> select addtime('xxcvadfgasd', '1');
ERROR 1292 (22007): Incorrect datetime value: 'xxcvadfgasd'
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

e98a869205cecf480e5ceb973fb7548e70a7d4ec

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @SunRunAway

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #12342 

Problem Summary:
Didn't handle the error for the second argument.

### What is changed and how it works?

If the second argument is invalid, use `NULL` instead of returning an error.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- handle invalid argument for addtime and subtime function

### CODE REVIEW

File: expression/builtin_time.go [hunk 1]
```diff
@@ -5084,21 +5084,22 @@ func isDuration(str string) bool {
 }
 
 // strDatetimeAddDuration adds duration to datetime string, returns a string value.
-func strDatetimeAddDuration(sc *stmtctx.StatementContext, d string, arg1 types.Duration) (string, error) {
+func strDatetimeAddDuration(sc *stmtctx.StatementContext, d string, arg1 types.Duration) (string, bool, error) {
 	arg0, err := types.ParseTime(sc, d, mysql.TypeDatetime, types.MaxFsp)
 	if err != nil {
-		return "", err
+		sc.AppendWarning(err)
```
Comment (XuHuaiyu) [inline expression/builtin_time.go:5090]: Why don't we check the sql_mode to decide whether to return an error or a warning?

e.g. sc.HandleTruncate

File: expression/builtin_time.go [hunk 2]
```diff
@@ -5084,21 +5084,22 @@ func isDuration(str string) bool {
 }
 
 // strDatetimeAddDuration adds duration to datetime string, returns a string value.
-func strDatetimeAddDuration(sc *stmtctx.StatementContext, d string, arg1 types.Duration) (string, error) {
+func strDatetimeAddDuration(sc *stmtctx.StatementContext, d string, arg1 types.Duration) (string, bool, error) {
```
Comment (ichn-hu) [inline expression/builtin_time.go:5087]: perhaps using a named return value can be more clear, say `isNull` for bool.

File: expression/builtin_time.go [hunk 3]
```diff
@@ -5119,14 +5120,15 @@ func strDurationAddDuration(sc *stmtctx.StatementContext, d string, arg1 types.D
 }
 
 // strDatetimeSubDuration subtracts duration from datetime string, returns a string value.
-func strDatetimeSubDuration(sc *stmtctx.StatementContext, d string, arg1 types.Duration) (string, error) {
+func strDatetimeSubDuration(sc *stmtctx.StatementContext, d string, arg1 types.Duration) (string, bool, error) {
```
Comment (ichn-hu) [inline expression/builtin_time.go:5123]: ditto.

**Review by ichn-hu — APPROVED** [review]
LGTM

File: expression/builtin_time.go (hunk 1 above)
Comment (wjhuang2016) [reply expression/builtin_time.go:5090]: Even in the strict mode, MySQL returns a warning.

Comment (XuHuaiyu) [reply expression/builtin_time.go:5090]: Add a comment for it?

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by XuHuaiyu** [comment]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
