### PR TITLE
ddl notifier: use pessimistic txn and fix updating memory state too early

### LINKED ISSUE #59055: DDL notifier does not guarantee delivery when internal SQL failed to COMMIT
## Bug Report

https://github.com/pingcap/tidb/blob/c34a6b69f66ed080bfd4938ae51e134fc70b917d/pkg/ddl/notifier/subscribe.go#L275-L296

If `handler` runs without error, DDL notifier marks the in-memory structure `change` as processed in line 295. However the `handler` may still fail in line 277 when commits. The `change` uses the same SQL transaction so the wrong processed state is not persisted, but the memory state of `change` is used afterward and causes problems

https://github.com/pingcap/tidb/blob/c34a6b69f66ed080bfd4938ae51e134fc70b917d/pkg/ddl/notifier/subscribe.go#L233-L244

### 1. Minimal reproduce step (Required)

Will add UT in fix PR

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #59055

Problem Summary:

### What changed and how does it work?

in pessimistic txn, errors can be found earlier, such as when execute the SQL. So handler can see the error and process it. Otherwise the error is reported when COMMIT, and in current handler interface it can't be proccessed

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/notifier/subscribe.go [hunk 1]
```diff
@@ -268,15 +268,20 @@ func (n *DDLNotifier) processEventForHandler(
 	if (change.processedByFlag & (1 << handlerID)) != 0 {
 		return nil
 	}
+	newFlag := change.processedByFlag | (1 << handlerID)
 
-	if err = session.Begin(ctx); err != nil {
+	if err = session.BeginPessimistic(ctx); err != nil {
```
Comment (D3Hunter) [inline pkg/ddl/notifier/subscribe.go:273]: what's the target issue of using pessimistic txn ?

Comment (lance6716) [reply pkg/ddl/notifier/subscribe.go:273]: in pessimistic txn, errors can be found earlier, such as when execute the SQL. So handler can see the error and process it. Otherwise the error is reported when COMMIT, and in current handler interface it can't be proccessed

Comment (D3Hunter) [reply pkg/ddl/notifier/subscribe.go:273]: > in pessimistic txn, errors can be found earlier

if there is no check about `affected rows`, there is no error actually in pessimistic txn

Comment (lance6716) [reply pkg/ddl/notifier/subscribe.go:273]: The original problem is handler uses the txn to insert some duplicate rows. In optimistic txn, there's no error after execute the INSERT. Using pessimistic txn handler can see "duplicate entry" error. https://github.com/pingcap/tidb/pull/58980 is related

**Review by D3Hunter — APPROVED** [review]

File: pkg/ddl/notifier/subscribe.go (hunk 1 above)
Comment (lance6716) [reply pkg/ddl/notifier/subscribe.go:273]: I also checked the affected rows in https://github.com/pingcap/tidb/pull/59157/commits/bef13bf134d125a8db59f82a0f91e629052d7eda . It's revealed by old UT after switching to pessimistic txn.

File: pkg/ddl/notifier/store.go [hunk 2]
```diff
@@ -87,17 +88,28 @@ func (t *tableStore) UpdateProcessed(
 	se *sess.Session,
 	ddlJobID int64,
 	multiSchemaChangeID int64,
-	processedBy uint64,
+	oldProcessedBy uint64,
+	newProcessedBy uint64,
 ) error {
 	sql := fmt.Sprintf(`
 		UPDATE %s.%s
```
Comment (Rustin170506) [inline pkg/ddl/notifier/store.go:95]: I’m not sure under the repeatable read isolation (snapshot isolation) whether TiDB guarantees that we can get the current processed_by_flag instead of the snapshot value.

**Review by Rustin170506 — APPROVED** [review]
I will help test this patch along with [my changes](https://github.com/pingcap/tidb/pull/58980) in our test infrastructure.

So let’s hold off on this PR until I finish the testing.

/hold

File: pkg/ddl/notifier/store.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/notifier/store.go:95]: > get the current processed_by_flag 

I'm not clear about your meaning. `oldProcessedBy` is read from another SQL session (`sess4List`), and here the processing SQL session uses WHERE processed_by_flag = `oldProcessedBy` and affected rows to check if the value has been changed

Comment (Rustin170506) [reply pkg/ddl/notifier/store.go:95]: Oh, I see, they are in a different session.

Comment (Rustin170506) [reply pkg/ddl/notifier/store.go:95]: Thank you!

**Comment by Rustin170506** [comment]
Tested in the test infra:

We don't meet the duplicate key error anymore:
image

Also no records in the system table:

```sql
mysql> select * from mysql.tidb_ddl_notifier;
Empty set (0.05 sec)

```

**Comment by Rustin170506** [comment]
/unhold 

Tested in https://github.com/pingcap/tidb/pull/59157#issuecomment-2614262450

**Comment by Rustin170506** [comment]
/unhold

The reasons behind these commits are:
1. [`c7a8985` (#59157)](https://github.com/pingcap/tidb/pull/59157/commits/c7a8985e19aead514bfc9f0e8d508112491dd46b) If we handle the DDL events correctly, the analyze rate will be determined by the stats' row count instead of the default value. However, since DDL handling is asynchronous, it may sometimes succeed before the analysis and sometimes after.
2. [`e2cd37f` (#59157)](https://github.com/pingcap/tidb/pull/59157/commits/e2cd37f60c2845bc289beadb58218dfe52cfd256) If we don't handle the DDL event, the analyze process will not analyze the `val` column because it is neither a predicate column nor an index column, causing the status to be missing(nil). However, if we do handle the DDL event, we will know that this column hasn't been analyzed yet, meaning it is uninitialized. There is still a race condition between the analyze process and DDL event handling.
