### PR TITLE
ddl: retry modify column reorg on transient errors

### LINKED ISSUE #67254: modify/change column during upgrade from v8.4.0 to v8.5.6-pre may rollback unexpectedly after upgrade
### 1. Minimal reproduce path from TCMS

This issue comes from TCMS plan execution `8104364`:
- Plan execution: https://tcms.pingcap.net/dashboard/executions/plan/8104364
- Failed case: `modify-column-duraing-upgrade-cluster`
- Case execution id: `19045869`
- Main log: https://tcms.pingcap.net/api/v1/artifact-files/ks3/logs/2026-03-18/plan-exec-8104364-re0/plan-exec-8104364-re0-case-1680130-3-3043981435/main.log
- Plan definition: `upgrade-with-ddlv8.4.0-v8.5.6-pre@v8.5.6`

Effective parameters from the plan:
- source version: `v8.4.0`
- target version: `v8.5.6-pre`
- tiup mirror: `staging`

### 2. Reproduction steps

The testcase logic is equivalent to:

1. Deploy a TiUP cluster with 3 TiDB + 3 TiKV on `v8.4.0`.
2. Restore the `sbtest1` database.
3. Concurrently run these DDLs:
   - `alter table sbtest1.sbtest1 modify column c varchar(130);`
   - `alter table sbtest1.sbtest4 modify column c varchar(120);`
   - `alter table sbtest1.sbtest2 modify column c varchar(130);`
   - `alter table sbtest1.sbtest5 modify column c varchar(120);`
   - `alter table sbtest1.sbtest7 change column c d varchar(130);`
   - `alter table sbtest1.sbtest8 change column c d varchar(130);`
   - `alter table sbtest1.sbtest9 change column c d varchar(130);`
   - `alter table sbtest1.sbtest10 change column c d varchar(130);`
4. Wait about 30 seconds while some modify/change-column jobs are still running.
5. Upgrade the cluster from `v8.4.0` to `v8.5.6-pre`.
6. Query DDL history with:

```sql
admin show ddl jobs 1000
where db_name in ('sbtest1')
  and job_type like '%modify column%'
  and create_time >= '<case start time>';
```

7. Wait until the DDL jobs finish.

### 3. Expected behavior

After the upgrade completes, all those modify/change-column jobs should finish as `synced`.

### 4. Actual behavior

The cluster upgrade itself succeeded, but one historical DDL job finished as `rollback done` instead of `synced`.

From testcase log:

- upgrade completed successfully around `2026-03-19 04:51:33 +08:00`
- then validation found this DDL job:
  - `job_id=261`
  - `db_name=sbtest1`
  - `table_name=sbtest10`
  - `job_type=modify column`
  - `state=rollback done`

The testcase failed with:

```text
ddl info is {jobId:261 dbName:sbtest1 tableName:sbtest10 jobType:modify column ... state:rollback done comments:}
Expected
    <string>: rollback done
to equal
    <string>: synced
```

### 5. Why this looks like product behavior instead of infra/test issue

This does not look like a TCMS / test-infra failure:
- the cluster upgrade itself succeeded
- post-upgrade DDL history was readable
- the failure happened in testcase validation because one modify-column job ended in `rollback done`

The corresponding testcase assertion is in `endless/testcase/upgrade/enable_ddl/ddl.go`, where finished jobs are expected to be `synced`.

### 6. Environment / build info from testcase log

The upgraded cluster reported:
- Release Version: `v8.5.6`
- Git Commit Hash: `ee2d9935416d17516842379e143ce354b7074c0f`
- UTC Build Time: `2026-03-18 12:07:40`
- GoVersion: `go1.25.5`
- Store: `tikv`

The upgrade target passed into the testcase was `v8.5.6-pre`.

### 7. Source code path of the testcase

For reference, the corresponding endless testcase is:
- `testcase/upgrade/enable_ddl/enable_ddl_test.go`
- `It("should success while there are some modify column ddl running", ...)`

The testcase:
- restores `sbtest1`
- starts 8 concurrent modify/change-column DDLs
- waits 30 seconds
- upgrades from `v8.4.0` to `v8.5.6-pre`
- checks whether all resulting jobs are `synced`

### 8. Possible related history

This symptom looks similar to previous modify-column upgrade compatibility issues, for example:
- #63895
- #63901
- #63940
- #62780

I cannot confirm from the public repo whether build commit `ee2d9935416d17516842379e143ce354b7074c0f` contains those fixes, but the observed behavior looks very similar: a modify/change-column job created before upgrade may unexpectedly end as `rollback done` after upgrade.

### PR DESCRIPTION
**Pull request by fzzf678**
### What problem does this PR solve?

Issue Number: close #67254

Problem Summary:

- During rolling restart/upgrade (e.g. PD restart), modify column reorg may fail with transient PD region scan errors like "All returned regions have no leaders" and the DDL job gets converted to rollback.
- We also need to avoid retry loops on deterministic data conversion errors during modify column reorg.

### What changed and how does it work?

- Introduce a switch to control whether unknown reorg errors are retryable.
- Keep add index behavior unchanged (unknown errors are still retryable), while modify column uses a stricter policy (unknown errors are not retryable).
- Treat "All returned regions have no leaders" as a retryable transient error.
- Add a regression test to ensure modify column retries loadTableRanges failures instead of rolling back.

Ref: pingcap/tidb#67277 (release-8.5 backport).

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

Test command(s):

- go test -tags=intest ./pkg/expression/integration_test -run TestFixedVector -count=1
- ./tools/check/failpoint-go-test.sh pkg/ddl -run TestModifyColumnLoadTableRangeError -count=1

## Summary by CodeRabbit

* **Bug Fixes**
  * Enhanced DDL retry classification so callers can control how unknown errors are treated and avoid unnecessary rollbacks during modify-column reorganization.
  * Recognize an additional TiKV/PD retryable condition ("All returned regions have no leaders") and treat early region-load failures as retryable.

* **Tests**
  * Added a regression test validating modify-column reorganization under injected range/load failures.

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

File: pkg/ddl/modify_column_test.go [hunk 1]
```diff
@@ -1490,3 +1490,25 @@ func TestStatsAfterModifyColumn(t *testing.T) {
...
 	}
 }
+
+func TestModifyColumnLoadTableRangeError(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("drop database if exists modifycol;")
+	tk.MustExec("create database modifycol;")
+	tk.MustExec("use modifycol;")
+	tk.MustExec(`set global tidb_enable_dist_task=off;`)
```
Comment (fzzf678) [inline pkg/ddl/modify_column_test.go]:
```suggestion
	tk.MustExec("use modifycol;")
```
