### PR TITLE
ddl: fix placement rules compatibility with tiflash

### LINKED ISSUE #22171: ddl: placement rules in SQL is not compatible with TiFlash
## Bug Report

When PD schedules a partition to tiflash, TiFlash will validate the keyrange if there is a `_r` suffix.

But placement rules are not compatible with the old `set tiflash replica` syntax too, so we should forbid using +engine=tiflash, and should add -engine=tiflash to every rule to avoid schedules to tiflash instance.

### 1. Minimal reproduce step (Required)

1. `tiup playground` with at lease 3 tikv instances.
2. add a random placement rule with the label `+engine=tiflash`. E.g `alter table t alter partition p0 add placement policy role=follower replicas=1 constraints='["+engine=tiflash"]'`.

1. `tiup playground` with at lease 3 tikv instances.
2. `alter table t set tiflash replica 3`
3. `alter table t alter partition p0 add placement policy role=follower replicas=1 constraints='["+engine=tiflash"]'`.

### 2. What did you expect to see? (Required)

The first example should work fine. In the 2nd example, 3 should fail.

### 3. What did you see instead (Required)

TiFlash crashed.

### 4. What is your TiDB version? (Required)

Newest nightly.

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue: close #22171

Problem Summary: When PD scheduels a partition to tiflash, TiFlash will validate the keyrange if there is a `_r` suffix. Using GenTableRecordPrefix instead of GenTablePrefix can fix this problem.

But placement rules are not compatible with the old `set tiflash replica` syntax, so the second commit simply forbids using `+engine=tiflash`, and will add `-engine=tiflash` to every rule to avoid scheduels to tiflash instance. Maybe that will be reverted in the future.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

```
set global tidb_enable_alter_placement=on;
drop table if exists test.t1;
create table test.t1 (a int) partition by hash(a) partitions 2;
alter table test.t1 alter partition p1 alter placement policy CONSTRAINTS='["+engine=tiflash"]' ROLE=follower REPLICAS=1;
(8234, 'Invalid placement policy \'alter placement policy constraints=\'["+engine=tiflash"]\' role=follower replicas=1\': unsupported label constraint \'+engine=tiflash\'')
```

### Release note 

- Forbid adding tiflash replica by placement rules in SQL

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -5822,15 +5822,20 @@ func (d *ddl) AlterTableAlterPartition(ctx sessionctx.Context, ident ast.Ident,
...
 	for i, rule := range bundle.Rules {
 		// merge all empty constraints
 		if len(rule.LabelConstraints) == 0 {
 			extraCnt[rule.Role] += rule.Count
 			continue
 		}
+		rule.LabelConstraints = append(rule.LabelConstraints, placement.LabelConstraint{
+			Op:     placement.NotIn,
+			Key:    "engine",
+			Values: []string{"tiflash"},
```
Comment (djshow832) [inline ddl/ddl_api.go:5837]: Define them as constants and replace other occurrences of "engine" and "tiflash" with the constants.

**Review by djshow832 — COMMENTED** [review]
Add some cases to `placement_sql_test.go` to test if the placement rules generated by SQL are right in these scenarios:
1. Whether the placement rules all contain "-engine=tiflash".
2. When the user also defines "-engine=tiflash", the placement rules should only contain one "-engine=tiflash" constraint.
3. `CONSTRAINTS='{"+zone=bj":1}' REPLICAS=2`, the extra count should also contain "-engine=tiflash" constraint. (Maybe?)

File: ddl/ddl_api.go (hunk 1 above)
Comment (xhebox) [reply ddl/ddl_api.go:5837]: 2. Duplication has been handled by label check PR.
1&3. yeah, It seems 3 did not count.

**Comment by xhebox** [comment]
> Add some cases to placement_sql_test.go to test if the placement rules generated by SQL are right in these scenarios.
@djshow832 I can not add tests in `placement_sql_test.go`. Mock test wont update rule cache. Putting it into `placement_rule_test.go` needs too many modifications. I would like to leave it to automated-test.

File: ddl/placement/const.go [hunk 2]
```diff
@@ -33,6 +33,14 @@ const (
...
+	// DCLabelKey indicates the key of label which represents the dc for Store.
+	// FIXME: currently we assumes "zone" is the dcLabel key in Store
+	DCLabelKey = "zone"
+	// EngineLabelKey is the label that indicates the backend of store instance:
+	// tikv or tiflash. TiFlash instance will contain a label of 'engine: tiflash'.
+	EngineLabelKey = "engine"
+	// EngineLabelTiFlash is the label value, which a TiFlash instance will have with
+	// a label key of EngineLabelKey.
+	EngineLabelTiFlash = "tiflash"
+)
```
Comment (djshow832) [inline ddl/placement/const.go:46]: I mean, some other places also use "engine" and "tiflash", especially the code relevant to `set tiflash replica`. This would make duplicates.

Comment (xhebox) [reply ddl/placement/const.go:46]: Done

**Review by djshow832 — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
Please create an issue for this problem.

**Review by wjhuang2016 — COMMENTED** [review]
`The first commit fixed that.` It is not convenient for a reviewer to find your first commit. 
You can write: "Using `GenTableRecordPrefix` instead of `GenTablePrefix` can fix this problem." 
Besides, is there any test for this change?

File: ddl/ddl_api.go [hunk 3]
```diff
@@ -5822,15 +5822,20 @@ func (d *ddl) AlterTableAlterPartition(ctx sessionctx.Context, ident ast.Ident,
...
+	startKey := hex.EncodeToString(codec.EncodeBytes(nil, tablecodec.GenTableRecordPrefix(partitionID)))
+	endKey := hex.EncodeToString(codec.EncodeBytes(nil, tablecodec.GenTableRecordPrefix(partitionID+1)))
 	newRules := bundle.Rules[:0]
 	for i, rule := range bundle.Rules {
 		// merge all empty constraints
 		if len(rule.LabelConstraints) == 0 {
 			extraCnt[rule.Role] += rule.Count
 			continue
 		}
+		rule.LabelConstraints = append(rule.LabelConstraints, placement.LabelConstraint{
```
Comment (wjhuang2016) [inline ddl/ddl_api.go:5834]: Please add a comment about why we need to append a constraint.

**Comment by xhebox** [comment]
@wjhuang2016 I will try if `TestDDLCallback` can test it. The problem is that rule cache will not refresh without a working PD.

**Comment by wjhuang2016** [comment]
> @wjhuang2016 I will try if `TestDDLCallback` can test it. The problem is that rule cache will not refresh without a working PD.

You can do a manual test. Start a cluster to test it.

**Comment by xhebox** [comment]
> You can do a manual test. Start a cluster to test it.
Manual test is already done, of course.

File: ddl/ddl_api.go (hunk 3 above)
Comment (xhebox) [reply ddl/ddl_api.go:5837]: Added.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
