### PR TITLE
execute: don't transform charset in internal sql

### LINKED ISSUE #30789: `drop user` failed when `set names gbk`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set names gbk;
create user '测';
drop user '测';

create user '一';
drop user '一';
```

### 2. What did you expect to see? (Required)
`No error`

### 3. What did you see instead (Required)
Failed
```
ERROR 1396 (HY000): Operation DROP USER failed for 娴?@%
```

### 4. What is your TiDB version? (Required)

There are two problems:
* https://github.com/pingcap/tidb/issues/30565
* https://github.com/pingcap/tidb/blob/master/executor/simple.go#L1359-L1370, Transform '测' -> '娴?' -> 0xE5A8B43F ('濞?')

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #30789

Problem Summary: TiDB only supports UTF8 charset internal and `ParseWithParam` only used to process TiDB’s own sql statements, so we should ignore the `client charset` and `client collation`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: session/session.go [hunk 1]
```diff
@@ -1469,21 +1469,13 @@ func (s *session) ParseWithParams(ctx context.Context, sql string, args ...inter
 		}
 	}
 
-	internal := s.isInternal()
```
Comment (xiongjiwei) [inline session/session.go:1472]: so, this means there will be **NO** user SQL run here?

Comment (Defined2014) [reply session/session.go:1472]: Yes. But after discuss with @xhebox, for scalability, I will add an interface called `ParseWithParamsInternal`.

Comment (tangenta) [reply session/session.go:1472]: What is the purpose to introduce `ParseWithParamsInternal`? How is it different from `ParseWithParams`?

**Review by tangenta — APPROVED** [review]

File: session/session.go (hunk 1 above)
Comment (Defined2014) [reply session/session.go]: `Parse()` is deprecated, it will be insteaded by `ParseWithParams` which should have ability to deal with users' SQLs. So add `ParseWithParamsInternal` to process internal SQLs. @tangenta
