### PR TITLE
expression: preserve negative-zero semantics in pushdown

### LINKED ISSUE #67236: Bug in ATAN2 Function Behavior with IS NULL Condition When PRIMARY KEY is Present
## Bug Report

This case demonstrates a potential bug related to the behavior of the ATAN2 function when used with IS NULL, depending on the presence of a PRIMARY KEY on the c0 column. In Query 1, a table t0 is created with a PRIMARY KEY on the c0 column, and the ATAN2 function returns a result as expected. In Query 2, the same table is created without the PRIMARY KEY, but the query returns an empty set, despite using the same ATAN2 function and conditions. The only difference between the two queries is the presence of the PRIMARY KEY constraint on c0 in Query 1. Since the primary key should not affect the result of the query, the different outcomes suggest an inconsistency and point to a potential bug.


### 1. Minimal reproduce step (Required)


```sql
-- query 1
DROP TABLE IF EXISTS t0;
CREATE TABLE t0 (c0 double, PRIMARY KEY (c0));
INSERT INTO t0 VALUES (1);
SELECT c0 FROM t0 WHERE 
ATAN2(((t0.c0) IS NULL), (- ('a'))) ;



-- query 2
DROP TABLE IF EXISTS t0;
CREATE TABLE t0 (c0 double);
INSERT INTO t0 VALUES (1);
SELECT c0 FROM t0 WHERE 
ATAN2(((t0.c0) IS NULL), (- ('a'))) ;
```

### 2. What did you expect to see? (Required)
Return the same result

### 3. What did you see instead (Required)
```sql
-- result 1
+----+
| c0 |
+----+
|  1 |
+----+
1 row in set, 1 warning (0.01 sec)
-- result 2
Empty set, 1 warning (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_Version()                                                                                                                                                                                                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.5.5
Edition: Community
Git Commit Hash: 1fa258b833ff113883beeba40bc130be7ce66610
Git Branch: HEAD
UTC Build Time: 2026-03-12 08:34:59
GoVersion: go1.25.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #67236

Problem Summary:

`atan2((t0.c0 is null), -('a'))` can return different results for the same row shape depending on
whether `c0` is a primary key. The difference comes from pushdown encoding normalizing `-0` to
`+0`, which changes the sign-sensitive behavior of `atan2`.

### What changed and how does it work?

- Stop pushing down float constants whose value is negative zero, because the protobuf constant
  encoding path uses mem-comparable float encoding and loses the sign bit.
- Add a pushdown-layer regression in `TestPushDownSwitcher` to ensure `ATAN2(column, -0)` stays at
  root while `ATAN2(column, +0)` remains pushdown-able.
- Add an integration regression in `TestExprPushdownBlacklist` to verify PK and non-PK tables now
  return the same result for the issue query.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented incorrect normalization of negative-zero float values so math functions (e.g., atan2) handle -0 distinctly.

* **Tests**
  * Added unit tests verifying pushdown behavior with negative-zero vs positive-zero float constants.
  * Added integration test ensuring consistent query results across table key configurations for related expressions.

### CODE REVIEW

File: pkg/expression/expr_to_pb.go [hunk 1]
```diff
@@ -137,9 +138,19 @@ func (pc *PbConverter) encodeDatum(ft *types.FieldType, d types.Datum) (tipb.Exp
 		tp = tipb.ExprType_Bytes
 		val = d.GetBytes()
 	case types.KindFloat32:
+		if d.GetFloat64() == 0 && math.Signbit(d.GetFloat64()) {
```
Comment (windtalker) [inline pkg/expression/expr_to_pb.go:141]: In my understanding most code path will first use this `ExprToPB` to check if an expression can be push down, and if not, it will not pushdown the expr. However, since this `encodeDatum` is a very low level function, I'm not sure if there any code path can skip the check stage, just call `encodeDatum` in the `expr to pb` or `plan to pb` stage, if that code path exists, then the error will cause the whole query fail, and I think this is not the expected behavior because the query should not fail just because it use `-0`

Comment (hawkingrei) [reply pkg/expression/expr_to_pb.go:141]: Good point. I checked the relevant callers again after the follow-up.

This change only makes negative-zero float constants fall into the existing "not pushable" path in `ExprToPB()`: `encodeDatum()` returns `ok=false`, then `conOrCorColToPBExpr()` returns `nil`.

For the normal planner flow, that still stays on the pushdown-selection boundary instead of becoming a new query error path:
- `canExprPushDown()` already treats `pc.conOrCorColToPBExpr(expr) == nil` as "cannot push" for constants.
- The common pushdown gates (`CanExprsPushDown` / `PushDownExprs`) are what selection/projection/agg use before building PB, so expressions involving `-0` stay at root rather than being pushed.

There are also existing `ExpressionsToPBList` / `ProjectionExpressionsToPBList` callers in the later plan-to-PB stage, and those do upgrade `ExprToPB() == nil` to an internal error. But that contract already existed before this patch for any unpushable expression. This patch does not introduce a new failure mechanism there; it only adds negative-zero float constants into the pre-existing non-pushable set. In other words, if a path skipped the pushdown gate and directly assumed PB conversion must succeed, it was already relying on that stronger invariant before this change.

The regression tests here are intended to cover that safety boundary as well: the unit test checks `atan2(..., -0)` is not converted to PB while `+0` still is, and the integration test checks the query still returns `1` consistently for both PK and non-PK layouts instead of diverging or failing.
