### PR TITLE
executor, statistics: release analyze collector memory eagerly

### LINKED ISSUE #64423: Analyze a small table costs a lot of memory
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
# adjust the variables in order to insert success
set session tidb_mem_quota_query = 1073741824 * 3;
SET SESSION cte_max_recursion_depth = 200000;

# create table with 109 column
CREATE TABLE `analyze_sim_table` (
  `col1` varchar(32) NOT NULL,
  `col2` varchar(8) NOT NULL,
  `col3` varchar(9) NOT NULL,
  `col4` varchar(4) DEFAULT NULL,
  `col5` varchar(4) DEFAULT NULL,
  `col6` varchar(10) DEFAULT NULL,
  `col7` varchar(10) DEFAULT NULL,
  `col8` varchar(10) DEFAULT NULL,
  `col9` varchar(30) DEFAULT NULL,
  `col10` varchar(256) DEFAULT NULL,
  `col11` varchar(30) DEFAULT NULL,
  `col12` varchar(256) DEFAULT NULL,
  `col13` varchar(32) DEFAULT NULL,
  `col14` varchar(20) DEFAULT NULL,
  `col15` varchar(50) DEFAULT NULL,
  `col16` varchar(50) DEFAULT NULL,
  `col17` varchar(20) DEFAULT NULL,
  `col18` varchar(32) DEFAULT NULL,
  `col19` varchar(1) DEFAULT NULL,
  `col20` varchar(17) DEFAULT NULL,
  `col21` varchar(17) DEFAULT NULL,
  `col22` varchar(20) DEFAULT NULL,
  `col23` varchar(1024) DEFAULT NULL,
  `col24` varchar(1024) DEFAULT NULL,
  `col25` varchar(32) DEFAULT NULL,
  `col26` varchar(256) DEFAULT NULL,
  `col27` varchar(256) DEFAULT NULL,
  `col28` varchar(32) DEFAULT NULL,
  `col29` varchar(30) DEFAULT NULL,
  `col30` varchar(400) DEFAULT NULL,
  `col31` varchar(4) DEFAULT NULL,
  `col32` varchar(200) DEFAULT NULL,
  `col33` varchar(2) DEFAULT NULL,
  `col34` varchar(30) DEFAULT NULL,
  `col35` varchar(20) DEFAULT NULL,
  `col36` varchar(12) DEFAULT NULL,
  `col37` varchar(2) DEFAULT NULL,
  `col38` varchar(30) DEFAULT NULL,
  `col39` varchar(16) DEFAULT NULL,
  `col40` varchar(20) DEFAULT NULL,
  `col41` varchar(2) DEFAULT NULL,
  `col42` varchar(8) DEFAULT NULL,
  `col43` varchar(500) DEFAULT NULL,
  `col44` varchar(14) DEFAULT NULL,
  `col45` varchar(14) DEFAULT NULL,
  `col46` varchar(32) DEFAULT NULL,
  `col47` varchar(14) DEFAULT NULL,
  `col48` varchar(10) DEFAULT NULL,
  `col49` varchar(500) DEFAULT NULL,
  `col50` varchar(12) DEFAULT NULL,
  `col51` varchar(8) DEFAULT NULL,
  `col52` varchar(20) DEFAULT NULL,
  `col53` varchar(32) DEFAULT NULL,
  `col54` varchar(100) DEFAULT NULL,
  `col55` varchar(128) DEFAULT NULL,
  `col56` varchar(6) DEFAULT NULL,
  `col57` varchar(32) DEFAULT NULL,
  `col58` varchar(14) DEFAULT NULL,
  `col59` varchar(32) DEFAULT NULL,
  `col60` varchar(64) DEFAULT NULL,
  `col61` text DEFAULT NULL,
  `col62` varchar(1024) DEFAULT NULL,
  `col63` varchar(32) DEFAULT NULL,
  `col64` varchar(32) DEFAULT NULL,
  `col65` varchar(10) DEFAULT NULL,
  `col66` varchar(14) DEFAULT NULL,
  `col67` varchar(1024) DEFAULT NULL,
  `col68` varchar(32) DEFAULT NULL,
  `col69` varchar(30) DEFAULT NULL,
  `col70` varchar(2) DEFAULT NULL,
  `col71` varchar(50) DEFAULT NULL,
  `col72` varchar(14) DEFAULT NULL,
  `col73` varchar(100) DEFAULT NULL,
  `col74` varchar(40) DEFAULT NULL,
  `col75` varchar(8) DEFAULT NULL,
  `col76` varchar(2) DEFAULT NULL,
  `col77` varchar(2) DEFAULT NULL,
  `col78` varchar(2) DEFAULT NULL,
  `col79` varchar(32) DEFAULT NULL,
  `col80` varchar(8) DEFAULT NULL,
  `col81` varchar(10) DEFAULT NULL,
  `col82` varchar(50) DEFAULT NULL,
  `col83` text DEFAULT NULL,
  `col84` varchar(512) DEFAULT NULL,
  `col85` varchar(20) DEFAULT NULL,
  `col86` varchar(64) DEFAULT NULL,
  `col87` varchar(64) DEFAULT NULL,
  `col88` varchar(20) DEFAULT NULL,
  `col89` varchar(16) DEFAULT NULL,
  `col90` varchar(64) DEFAULT NULL,
  `col91` varchar(16) DEFAULT NULL,
  `col92` varchar(1024) DEFAULT NULL,
  `col93` varchar(32) DEFAULT NULL,
  `col94` varchar(32) DEFAULT NULL,
  `col95` varchar(100) DEFAULT NULL,
  `col96` varchar(2) DEFAULT NULL,
  `col97` varchar(4) DEFAULT NULL,
  `col98` text DEFAULT NULL,
  `col99` varchar(64) DEFAULT NULL,
  `col100` varchar(128) DEFAULT NULL,
  `col101` varchar(512) DEFAULT NULL,
  `col102` varchar(20) DEFAULT NULL,
  `col103` varchar(2) DEFAULT NULL,
  `col104` varchar(20) DEFAULT NULL,
  `col105` varchar(3) DEFAULT NULL,
  `col106` varchar(12) DEFAULT NULL,
  `col107` varchar(32) DEFAULT NULL,
  `col108` longtext DEFAULT NULL,
  `col109` text DEFAULT NULL,
  PRIMARY KEY (`col1`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

# insert 160,000 rows
INSERT INTO `analyze_sim_table` (
  `col1`, `col2`, `col3`, `col9`, `col22`, `col23`, `col61`, `col83`
)
WITH RECURSIVE seq (n) AS (
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM seq WHERE n < 160000
)
SELECT
  CONCAT('sim_txn_', LPAD(n, 20, '0')),          -- col1
  '20251110',                                    -- col2
  '183000000',                                   -- col3
  CONCAT('MERCHANT_', LPAD( (n % 1000) + 1, 3, '0')), -- col9
  '10000',                                       -- col22
  LPAD('order-body-data', 200, 'x'),             -- col23
  LPAD('reserved-field-data', 200, 'y'),         -- col61
  LPAD('bill-list-data', 120, 'z')               -- col83
FROM seq;

# check the row numbers
select count(*) from analyze_sim_table;


# show the metadata
# it may needs to execute many times to guarantee the metadata has been updated. Otherwise the analyze may use the 1 sample rate
select table_name,TABLE_ROWS,sum(DATA_LENGTH)/1024/1024/1024 GB from information_schema.tables where table_name='analyze_sim_table' group by table_name,TABLE_ROWS;

# execute analyze
analyze table analyze_sim_table;
```

### 2. What did you expect to see? (Required)
The table is small, it only has 80MB data. The analyze statement should cost less memory.

### 3. What did you see instead (Required)
The table is small, it only has 80MB data. But the analyze statement costs more than 2GB memory.

```
mysql> select count(*) from analyze_sim_table;
+----------+
| count(*) |
+----------+
|   160000 |
+----------+
1 row in set (0.06 sec)

mysql> select table_name,TABLE_ROWS,sum(DATA_LENGTH)/1024/1024/1024 GB from information_schema.tables where table_name='analyze_sim_table' group by table_name,TABLE_ROWS;
+-------------------+------------+----------------+
| table_name        | TABLE_ROWS | GB             |
+-------------------+------------+----------------+
| analyze_sim_table |     160000 | 0.088363885880 |
+-------------------+------------+----------------+
1 row in set (0.00 sec)

mysql> analyze table analyze_sim_table;
Query OK, 0 rows affected, 1 warning (2.21 sec)

mysql> show warnings;
+-------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level | Code | Message                                                                                                                                                           |
+-------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Note  | 1105 | Analyze use auto adjusted sample rate 0.687500 for table test.analyze_sim_table, reason to use this rate is "use min(1, 110000/160000) as the sample-rate=0.6875" |
+-------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

check the memory cost in the dashboard:
Image

### 4. What is your TiDB version? (Required)

v7.5.6, but the latest master is the same

### PR DESCRIPTION
**Pull request by 0xPoe**
### What problem does this PR solve?

Issue Number: close #64423

Problem Summary:

After extended stats was removed, analyze no longer needs to retain column `SampleCollector`s until the end of the build flow. The obsolete retention path keeps sampled values alive longer than necessary and inflates analyze memory usage.

### What changed and how does it work?

Release column collector memory immediately after histogram / TopN materialization in analyze v1/v2, and add a regression test for the v2 release timing.

The removed `collectors[task.slicePos] = collector` assignment was only keeping column collectors alive for later use. After extended stats removal, nothing consumes those collectors anymore, so retaining them only delays reclaiming sampled values until the end of analyze.

With a table that contains 100 columns and 70 million rows, I have the following test result:
Before the change(max: 9.05GB, avg: 3.95GB): 
image
After the change(max: 7.51GB, avg: 2.71):
image

- Max: 9.05GB → 7.51GB, reduced by 17.0%
- Avg: 3.95GB → 2.71GB, reduced by 31.4%

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Manual test

- Ran nightly TiUP Playground with baseline / patched `tidb-server` binaries.
- Loaded a wide `TEXT` sampling workload and compared `/debug/pprof/heap` during `ANALYZE`.
- Heap growth delta dropped from `291,804,016` bytes to `5,823,696` bytes.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Chores**
  * Improved memory cleanup during column statistics analysis so per-column collectors are released earlier, reducing memory retention.
* **Tests**
  * Added a test that verifies immediate release of column-collector memory during analysis to ensure the cleanup behavior.

### CODE REVIEW

File: pkg/executor/analyze_col_v2.go [hunk 1]
```diff
@@ -808,13 +798,13 @@ workLoop:
...
-			}
 			releaseCollectorMemory := func() {
-				if !task.isColumn {
-					e.memTracker.Release(collector.MemSize)
-				}
+				collectorMemSize := collector.MemSize
+				failpoint.InjectCall("analyzeSamplingBuildBeforeReleaseCollectorMemory", collectorMemSize, e.memTracker.BytesConsumed())
+				intest.Assert(collectorMemSize >= 0, "collector memory size should be non-negative")
+				e.memTracker.Release(collectorMemSize)
+				collector.Destroy()
```
Comment (guo-shaoge) [inline pkg/executor/analyze_col_v2.go:806]: why not just setting `collector` to nil directly?

Comment (0xPoe) [reply pkg/executor/analyze_col_v2.go:806]: This is a local variable, so I guess it doesn't matter.
