### PR TITLE
*: use errctx to handle divide zero error

### LINKED ISSUE #50031: When `ERROR_FOR_DIVISION_BY_ZERO` not set, we still get a warning when dividing zero
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
-- strict but ERROR_FOR_DIVISION_BY_ZERO not set
> set @@sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';
> select 1/0;
> show warnings;
```

### 2. What did you expect to see? (Required)

Should be no warning

In MySQL:

```
mysql> select 1/0;
+------+
| 1/0  |
+------+
| NULL |
+------+
1 row in set (0.00 sec)

mysql> show warnings;
Empty set (0.01 sec)
```

### 3. What did you see instead (Required)

```
mysql> select 1/0;
+------+
| 1/0  |
+------+
| NULL |
+------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

### LINKED ISSUE #50041: use errctx to handle divide zero error
## Enhancement

see description in PR: #50042

We are moving error handle settings from `stmtctx` to `errctx`, this is the issue for error when dividing a zero value.

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #50041

### What changed and how does it work?

use errctx to handle divide zero error

- Delete `StatementContext.DividedByZeroAsWarning` and use the error group `ErrDivisionByZero` to mark the error handle level.
- Delete `StatementContext.InReorg` because it is useless now.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by lcwangchao** [comment]
/hold

wait #5007 merged first

File: pkg/ddl/backfilling_scheduler.go [hunk 1]
```diff
@@ -163,10 +164,14 @@ func initSessCtx(
 	if err := setSessCtxLocation(sessCtx, tzLocation); err != nil {
 		return errors.Trace(err)
 	}
-	sessCtx.GetSessionVars().StmtCtx.InReorg = true
 	sessCtx.GetSessionVars().StmtCtx.SetTimeZone(sessCtx.GetSessionVars().Location())
 	sessCtx.GetSessionVars().StmtCtx.BadNullAsWarning = !sqlMode.HasStrictMode()
-	sessCtx.GetSessionVars().StmtCtx.DividedByZeroAsWarning = !sqlMode.HasStrictMode()
+
+	ec := sessCtx.GetSessionVars().StmtCtx.ErrCtx()
+	errLevels := ec.LevelMap()
```
Comment (tangenta) [inline pkg/ddl/backfilling_scheduler.go:171]: Maybe replace with `(sc *StatementContext) ErrLevels()`?

File: pkg/executor/executor.go [hunk 2]
```diff
@@ -2248,9 +2258,15 @@ func ResetContextOfStmt(ctx sessionctx.Context, s ast.StmtNode) (err error) {
 // ResetUpdateStmtCtx resets statement context for UpdateStmt.
 func ResetUpdateStmtCtx(sc *stmtctx.StatementContext, stmt *ast.UpdateStmt, vars *variable.SessionVars) {
 	sc.InUpdateStmt = true
+	ec := sc.ErrCtx()
+	errLevels := ec.LevelMap()
```
Comment (tangenta) [inline pkg/executor/executor.go:2262]: Ditto

**Review by tangenta — COMMENTED** [review]
Rest LGTM

**Review by tangenta — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]
