### PR TITLE
tables: fix insert ignore on duplicate with dup prefix 2nd index

### LINKED ISSUE #25809: clustered string primary with dup prefixed uk, insert ignore ... on duplicate key update return wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `tbl_16` (
  `col_70` varbinary(444) NOT NULL DEFAULT 'bezhs',
  PRIMARY KEY (`col_70`) clustered,
  UNIQUE KEY `idx_22` (`col_70`(1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
 insert into tbl_16 values('lldcxiyfjrqzgj');
 insert ignore into tbl_16 values ( 'lalozlkdosasfklmflo' ) on duplicate key update col_70 = 'lyhohxtby';
```
### 2. What did you expect to see? (Required)

mysql>  insert ignore into tbl_16 values ( 'lalozlkdosasfklmflo' ) on duplicate key update col_70 = 'lyhohxtby';
Query OK, 2 rows affected (0.00 sec)

```
mysql> select * from tbl_16;
+-----------+
| col_70    |
+-----------+
| lyhohxtby |
+-----------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

only occur in 5.0-release, master is the same as expected

```
mysql>  insert ignore into tbl_16 values ( 'lalozlkdosasfklmflo' ) on duplicate key update col_70 = 'lyhohxtby';
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> select * from tbl_16;
+----------------+
| col_70         |
+----------------+
| lldcxiyfjrqzgj |
+----------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.0.2-40-g64b7ecd
Edition: Community
Git Commit Hash: 64b7ecd7938a69c34169cd4edc3055544f51e423
Git Branch: HEAD
UTC Build Time: 2021-06-25 18:24:59
GoVersion: go1.13.7
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: close #25809

Problem Summary:

now it relies on `modified` array to decide whether skip modified index dup check after duplicate updated.

but when clustered primary key  has same column with secondary index,and the column is prefix, changed in table doesn't indicate it be change in index.

### What is changed and how it works?

What's Changed, How it Works:

truncate datum to index length and re-check modified for prefix column

### Related changes

- Need to cherry-pick to the release branch 4.0, 3.0

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- Fix the wrong result after "insert ignore on duplicate update" in the secondary index has the same column in primary key but has prefix length

### CODE REVIEW

File: table/tables/tables.go [hunk 1]
```diff
@@ -1480,20 +1481,39 @@ func CheckHandleOrUniqueKeyExistForUpdateIgnoreOrInsertOnDupIgnore(ctx context.C
...
-		shouldSkipIgnoreCheck := func(idx table.Index) bool {
+		shouldSkipIgnoreCheck := func(idx table.Index) (bool, error) {
 			if !IsIndexWritable(idx) || !idx.Meta().Unique || (t.Meta().IsCommonHandle && idx.Meta().Primary) {
-				return true
+				return true, nil
 			}
 			for _, c := range idx.Meta().Columns {
 				if modified[c.Offset] {
-					return false
+					if c.Length != types.UnspecifiedLength && (newRow[c.Offset].Kind() == types.KindString || newRow[c.Offset].Kind() == types.KindBytes) {
```
Comment (cfzjywxk) [inline table/tables/tables.go:1490]: Besides `KindString` the Will other prefix index column types need similar process like this?

Comment (jackysp) [reply table/tables/tables.go:1490]: Agree, feel that there may still be problems later, but this type of SQL execution is rare, so it may okay for this release branch.

**Review by jackysp — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]
/lgtm

**Comment by tisonkun** [comment]
@lysu shall we pick this PR to master? It is interesting we first fix the issue on a release branch.

**Comment by lysu** [comment]
> @lysu shall we pick this PR to master? It is interesting we first fix the issue on a release branch.
> 
> FOUND: [#25809 (comment)](https://github.com/pingcap/tidb/issues/25809#issuecomment-871120905)

hi just as https://github.com/pingcap/tidb/issues/25809#issuecomment-871120905 said, the master branch use a different mechanism and doesn't has this bug
