### PR TITLE
ddl: allow altering auto_increment to a large number

### LINKED ISSUE #19238: alter auto_increment sql not work.
## Bug Report

Found that when auto_increment is unsigned, and alter auto_increment is larger than math.MaxInt64, it's not work well. see details below.

### 1. Minimal reproduce step (Required)
1. ```CREATE TABLE `autoid` (`auto_inc_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, UNIQUE KEY `auto_inc_id` (`auto_inc_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;```
2. ```alter table `autoid` auto_increment = 12345678901234567890;```
3. ```insert into `autoid` values ();```
4. ```select * from `autoid`;```

### 2. What did you expect to see? (Required)
```
mysql> select * from autoid;
+-----------------------+
| auto_inc_id           |
+-----------------------+
|   12345678901234567890|
+-----------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select * from autoid;
+-------------+
| auto_inc_id |
+-------------+
|           1 |
+-------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.3
Edition: Community
Git Commit Hash: 0529b1b493e46aae71bbe34cbe24515a2eb1b47c
Git Branch: heads/refs/tags/v4.0.3
UTC Build Time: 2020-07-24 12:06:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #19238 

Problem Summary:

The comparison between `auto_id` should be uint64-wised.

### What is changed and how it works?

What's Changed: Omitted.

How it Works: Omitted.

### Related changes

N/A

### Check List 

Tests 

- Unit test
- Integration test

Side effects

N/A

### Release note 

- No release note

### CODE REVIEW

File: ddl/db_integration_test.go [hunk 1]
```diff
@@ -2383,16 +2383,26 @@ func (s *testIntegrationSuite5) TestDropColumnsWithMultiIndex(c *C) {
...
 	tk.MustExec("create table t (a bigint primary key) auto_increment = 10;")
 	tk.MustExec("alter table t auto_increment = 10;")
+	tk.MustExec("alter table t auto_increment = 12345678901234567890;")
+
+	// Rebase the auto_inc allocator to a large integer should work.
+	tk.MustExec("drop table t;")
+	tk.MustExec("create table t (a bigint unsigned auto_increment, unique key idx(a));")
+	tk.MustExec("alter table t auto_increment = 12345678901234567890;")
+	tk.MustExec("insert into t values ();")
+	tk.MustQuery("select * from t;").Check(testkit.Rows("12345678901234567890"))
```
Comment (zimulala) [inline ddl/db_integration_test.go:2407]: How about the case as follows:
```
mysql> create table t (a bigint unsigned auto_increment, unique key idx(a));
Query OK, 0 rows affected (0.01 sec)
mysql> alter table t auto_increment = 18446744073709551614;
Query OK, 0 rows affected (0.00 sec)
mysql>  insert into t values ();
ERROR 1467 (HY000): Failed to read auto-increment value from storage engine
``

Comment (tangenta) [reply ddl/db_integration_test.go:2414]: Updated.

Comment (tangenta) [reply ddl/db_integration_test.go:2414]: Oh. I remember why this should be an error.

> 	// In TiDB : _tidb_rowid will also consume the autoID when the auto_increment column is not the primary key.
	// Using the MaxUint64 and MaxInt64 as the autoID upper limit like MySQL will cause _tidb_rowid allocation fail here.

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -2372,7 +2372,7 @@ func (d *ddl) RebaseAutoID(ctx sessionctx.Context, ident ast.Ident, newBase int6
 		// If the user sends SQL `alter table t1 auto_increment = 100` to TiDB-B,
 		// and TiDB-B finds 100 < 30001 but returns without any handling,
 		// then TiDB-A may still allocate 99 for auto_increment column. This doesn't make sense for the user.
-		newBase = mathutil.MaxInt64(newBase, autoID)
+		newBase = int64(mathutil.MaxUint64(uint64(newBase), uint64(autoID)))
```
Comment (djshow832) [inline ddl/ddl_api.go:2375]: `newBase` is still an `int64`? What if the column is `bigint unsigned`?

Comment (tangenta) [reply ddl/ddl_api.go:2375]: We can use a negative `int64` number to represent a large `uint64` number. It will be casted to `uint64` in `rebase()`/`alloc()`.

**Review by djshow832 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
