### PR TITLE
planner: add more checks when pushing TopN down

### LINKED ISSUE #41355: Wrong result of topn for generated column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
drop table t1;
CREATE TABLE `t1` (
  `c1` varchar(100) DEFAULT NULL,
  `c2` varchar(100) GENERATED ALWAYS AS (lower(`c1`)) VIRTUAL
);
alter table t1 set tiflash replica 1;
insert into t1(c1) values('a'), ('e'), ('b'), ('c'), ('d'), ('e'), ('x'), ('y'), ('a'), ('b');
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
```
MySQL [test]> select * from t1 order by c2 limit 2;
+------+------+
| c1   | c2   |
+------+------+
| a    | a    |
| a    | a    |
+------+------+
2 rows in set (0.001 sec)
```
### 3. What did you see instead (Required)
```
MySQL [test]> set tidb_isolation_read_engines = 'tikv';
Query OK, 0 rows affected (0.000 sec)

MySQL [test]> select * from t1 order by c2 limit 2;
+------+------+
| c1   | c2   |
+------+------+
| a    | a    |
| e    | e    |
+------+------+
2 rows in set (0.001 sec)

MySQL [test]> set tidb_isolation_read_engines = 'tiflash';
Query OK, 0 rows affected (0.000 sec)

MySQL [test]> select * from t1 order by c2 limit 2;
+------+------+
| c1   | c2   |
+------+------+
| a    | a    |
| e    | e    |
+------+------+
2 rows in set (0.010 sec)
```
### 4. What is your TiDB version? (Required)
```
MySQL [test]> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.5.0
Edition: Community
Git Commit Hash: 77776e17159e9c6faf6aeedf3085a7a2524d3205
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-05 13:50:22
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by Dousir9**
### What problem does this PR solve?

Issue Number: close #41355 

Problem Summary:

### What is changed and how it works?
1. TopN should not be pushed down to TiFlash/TiKV if `TopN.ByItems` contains virtually generated columns.
2. The "virtually generated column" push down is not supported now, we need to add test cases to cover: TopN, Projection, Selection.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Dousir9** [comment]
@guo-shaoge The check-issue-triage-complete fails, could you help me to resolve it? thanks.

File: planner/core/task.go [hunk 1]
```diff
@@ -955,14 +946,61 @@ func (p *PhysicalTopN) canPushToIndexPlan(indexPlan PhysicalPlan, byItemCols []*
...
+	}
+	if p.containVirtualColumn(copTask) {
+		return false
+	}
+	return true
+}
+
+// canPushDownToTiFlash checks whether this topN can be pushed down to TiFlash.
+func (p *PhysicalTopN) canPushDownToTiFlash() bool {
+	return !p.canExpressionConvertedToPB(kv.TiFlash)
```
Comment (qw4990) [inline planner/core/task.go:993]: Should be `p.canExpressionConvertedToPB(kv.TiFlash)` here instead of `!p.canExpressionConvertedToPB(kv.TiFlash)`? Please correct me if I understand it wrongly...

File: planner/core/task.go [hunk 2]
```diff
@@ -955,14 +946,61 @@ func (p *PhysicalTopN) canPushToIndexPlan(indexPlan PhysicalPlan, byItemCols []*
...
+	exprs := make([]expression.Expression, 0, len(p.ByItems))
+	for _, item := range p.ByItems {
+		exprs = append(exprs, item.Expr)
+	}
+	return expression.CanExprsPushDown(p.ctx.GetSessionVars().StmtCtx, exprs, p.ctx.GetClient(), storeTp)
+}
+
+// containVirtualColumn checks whether TopN.ByItems contains virtual generated columns.
+func (p *PhysicalTopN) containVirtualColumn(copTask *copTask) bool {
+	tCols := copTask.tablePlan.Schema().Columns
```
Comment (qw4990) [inline planner/core/task.go:960]: It seems we don't need to pass this `copTask` here? Can we just use `p.Children()[0].Schema().Columns`?

File: planner/core/task.go (hunk 1 above)
Comment (Dousir9) [reply planner/core/task.go:993]: oh! I copied it from `canPushDownToTiKV`, let me correct it !

File: planner/core/task.go (hunk 2 above)
Comment (qw4990) [reply planner/core/task.go:960]: PTAL @Dousir9

File: planner/core/task.go [hunk 3]
```diff
@@ -955,14 +946,61 @@ func (p *PhysicalTopN) canPushToIndexPlan(indexPlan PhysicalPlan, byItemCols []*
...
+	}
+	if p.containVirtualColumn(copTask) {
+		return false
+	}
+	return true
+}
+
+// canPushDownToTiFlash checks whether this topN can be pushed down to TiFlash.
+func (p *PhysicalTopN) canPushDownToTiFlash() bool {
+	return p.canExpressionConvertedToPB(kv.TiFlash)
```
Comment (guo-shaoge) [inline planner/core/task.go:993]: Why doen't check if contain virtual column for tiflash?

File: planner/core/task.go [hunk 4]
```diff
@@ -955,14 +946,61 @@ func (p *PhysicalTopN) canPushToIndexPlan(indexPlan PhysicalPlan, byItemCols []*
...
+}
+
 func (p *PhysicalTopN) attach2Task(tasks ...task) task {
```
Comment (guo-shaoge) [inline planner/core/task.go:996]: Just a question(may not related to this pr): do we have test cases to make sure other operatores(like Selection, Projection etc) using virtual column will not pushdown to tiflash/tikv.

**Comment by guo-shaoge** [comment]
> @guo-shaoge The check-issue-triage-complete fails, could you help me to resolve it? thanks.

Done

File: planner/core/task.go [hunk 5]
```diff
@@ -955,14 +946,61 @@ func (p *PhysicalTopN) canPushToIndexPlan(indexPlan PhysicalPlan, byItemCols []*
...
+// containVirtualColumn checks whether TopN.ByItems contains virtual generated columns.
+func (p *PhysicalTopN) containVirtualColumn(copTask *copTask) bool {
+	tCols := copTask.tablePlan.Schema().Columns
+	for _, by := range p.ByItems {
+		cols := expression.ExtractColumns(by.Expr)
+		for _, col := range cols {
+			if col.VirtualExpr != nil {
+				for _, tCol := range tCols {
+					// A column with ID > 0 indicates that the column can be resolved by data source.
+					if tCol.ID > 0 && tCol.ID == col.ID && tCol.VirtualExpr != nil {
```
Comment (guo-shaoge) [inline planner/core/task.go:967]: Is it necessary to check `tCol.VirtualExpr`? How do you think? @qw4990

File: planner/core/integration_test.go [hunk 6]
```diff
@@ -8431,3 +8431,13 @@ func TestIssue40285(t *testing.T) {
...
 }
+
+// https://github.com/pingcap/tidb/issues/41355
+func TestIssue41355(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t1; CREATE TABLE `t1` (`c1` varchar(100) DEFAULT NULL, `c2` varchar(100) GENERATED ALWAYS AS (lower(`c1`)) VIRTUAL);")
+	tk.MustExec("insert into t1(c1) values('a'), ('e'), ('b'), ('c'), ('d'), ('e'), ('x'), ('y'), ('a'), ('b');")
+	tk.MustQuery("select * from t1 order by c2 limit 2;").Check(testkit.Rows("a a", "a a"))
```
Comment (guo-shaoge) [inline planner/core/integration_test.go:8462]: Please also check: `TopN` should not pushdown tiflash. 
You can:
1. set tidb_isolation_read_engines = 'tiflash';
2. add tiflash replica. Check https://github.com/pingcap/tidb/blob/master/planner/core/integration_test.go#L427 as example.
3. run `explain select * from t1 order by c2 limit 2;`, and TopN should not pushdown to tiflash.

**Comment by Dousir9** [comment]
@hawkingrei Could you help me to left a /ok-to-test command, thanks ~

**Comment by Dousir9** [comment]
> /ok-to-test

Thanks.

File: planner/core/task.go (hunk 4 above)
Comment (AilinKid) [reply planner/core/task.go:999]: make sense, can we just add the virtual column check in `columnToPBExpr <- ExpressionToPBExpr` which in unified judgement of all Operator/Expression about whether they can be pushd down to kv to tiflash

Comment (AilinKid) [reply planner/core/task.go:999]: which also will reduce/simplify your code here I think

File: planner/core/task.go [hunk 7]
```diff
@@ -955,14 +946,64 @@ func (p *PhysicalTopN) canPushToIndexPlan(indexPlan PhysicalPlan, byItemCols []*
...
+
+// canPushDownToTiFlash checks whether this topN can be pushed down to TiFlash.
+func (p *PhysicalTopN) canPushDownToTiFlash(mppTask *mppTask) bool {
+	if !p.canExpressionConvertedToPB(kv.TiFlash) {
+		return false
+	}
+	if p.containVirtualColumn(mppTask.plan().Schema().Columns) {
+		return false
+	}
+	return true
```
Comment (AilinKid) [inline planner/core/task.go:996]: >Just a question(may not related to this pr): do we have test cases to make sure other operatores(like Selection, Projection etc) using virtual column will not pushdown to tiflash/tikv.

make sense, can we just add the virtual column check in columnToPBExpr <- ExpressionToPBExpr which in unified judgement of all Operator/Expression about whether they can be pushd down to kv to tiflash

which also will reduce/simplify your code here I think

Comment (AilinKid) [reply planner/core/task.go:996]: diff --git a/expression/expr_to_pb.go b/expression/expr_to_pb.go
index a9a29868b9..347dabb8b3 100644
--- a/expression/expr_to_pb.go
+++ b/expression/expr_to_pb.go
@@ -198,6 +198,9 @@ func (pc PbConverter) columnToPBExpr(column *Column) *tipb.Expr {
                        return nil
                }
        }
+       if column.VirtualExpr != nil {
+               return nil
+       }

Comment (AilinKid) [reply planner/core/task.go:996]: And plus your test code, that also works

**Review by qw4990 — APPROVED** [review]

**Review by chrysan — APPROVED** [review]
