### PR TITLE
planner, statistics: fix the inconsistent est when table has no stats

### LINKED ISSUE #52426: Inconsistent row count estimation between lite stats init and non-lite init when table has no stats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create a small table and insert some rows
```
create table t(a int);
insert into t values(1), (2), (3), (4), (5), (6), (7), (8), (9), (10);
```

Wait for a while after the stats delta is updated.
image

Then run `explain select * from t where a in (1, 2, 3, 4, 5, 6,7,8)` with and without setting `lite-init-stats` in config to false(default is true).

### 2. What did you expect to see? (Required)

Estimation is the same, both is `0.08` while the full scan is `10`. (0.08 = 10 * 1/1000 * 8)

### 3. What did you see instead (Required)

The lite init got 
image
8 = 10 * 0.8(defaultSelectivityFactor)

### 4. What is your TiDB version? (Required)
current master.

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #52426 

Problem Summary:

### What changed and how does it work?

The `Selectivity` needs a memory obj to trigger the pseudo estimation.

We add one.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/storage/read.go [hunk 1]
```diff
@@ -572,7 +572,9 @@ func CleanFakeItemsForShowHistInFlights(statsCache statstypes.StatsCache) int {
 		if item.IsIndex {
 			_, loadNeeded = tbl.IndexIsLoadNeeded(item.ID)
 		} else {
-			_, loadNeeded = tbl.ColumnIsLoadNeeded(item.ID, true)
```
Comment (winoros) [inline pkg/statistics/handle/storage/read.go:575]: We keep the async load unchanged. Wait for later patch to handle it.

**Review by hawkingrei — APPROVED** [review]

File: pkg/planner/core/collect_column_stats_usage.go [hunk 2]
```diff
@@ -195,11 +195,21 @@ func (c *columnStatsUsageCollector) addHistNeededColumns(ds *DataSource) {
 	colIDSet := intset.NewFastIntSet()
 
 	for _, col := range columns {
+		// If the column is plan-generated one, Skip it.
```
Comment (time-and-fate) [inline pkg/planner/core/collect_column_stats_usage.go:198]: What does "plan-generated" mean?

File: pkg/planner/core/collect_column_stats_usage.go [hunk 3]
```diff
@@ -195,11 +195,21 @@ func (c *columnStatsUsageCollector) addHistNeededColumns(ds *DataSource) {
...
+		// TODO: we may need to consider the ExtraHandle.
+		if col.ID < 0 {
+			continue
+		}
 		tblColID := model.TableItemID{TableID: ds.physicalTableID, ID: col.ID, IsIndex: false}
 		colIDSet.Insert(int(col.ID))
 		c.histNeededCols[tblColID] = true
 	}
 	for _, col := range ds.Columns {
+		// If the column is plan-generated one, Skip it.
```
Comment (time-and-fate) [inline pkg/planner/core/collect_column_stats_usage.go:208]: ditto.

File: pkg/statistics/table.go [hunk 4]
```diff
@@ -629,25 +629,37 @@ func (t *Table) GetStatsHealthy() (int64, bool) {
 // The Column should be visible in the table and really has analyzed statistics in the stroage.
 // Also, if the stats has been loaded into the memory, we also don't need to load it.
 // We return the Column together with the checking result, to avoid accessing the map multiple times.
-func (t *Table) ColumnIsLoadNeeded(id int64, fullLoad bool) (*Column, bool) {
+// The first bool is whether we have it in memory. The second bool is whether this column has stats or not.
```
Comment (time-and-fate) [inline pkg/statistics/table.go:632]: I think "has stats" is a bit ambiguous.
```suggestion
// The first bool is whether we have it in memory. The second bool is whether this column has stats in the system table or not.
```

File: pkg/statistics/table.go [hunk 5]
```diff
@@ -629,25 +629,37 @@ func (t *Table) GetStatsHealthy() (int64, bool) {
...
 	hasAnalyzed := t.ColAndIdxExistenceMap.HasAnalyzed(id, false)
 
-	// If it's not analyzed yet. Don't need to load it.
+	// If it's not analyzed yet.
 	if !hasAnalyzed {
-		return nil, false
+		// If we don't have it in memory, we create a fake hist for pseudo estimation.
+		if !ok {
+			// If we don't have this column. We skip it.
+			// It's something ridiculous. But it's possible that the stats don't have some ColumnInfo.
```
Comment (time-and-fate) [inline pkg/statistics/table.go:645]: So this means this column has stats but doesn't have `ColumnInfo`.
In what case would this happen?

File: pkg/statistics/table.go [hunk 6]
```diff
@@ -629,25 +629,37 @@ func (t *Table) GetStatsHealthy() (int64, bool) {
...
+		return nil, false, false
+	}
 	col, ok := t.Columns[id]
 	hasAnalyzed := t.ColAndIdxExistenceMap.HasAnalyzed(id, false)
 
-	// If it's not analyzed yet. Don't need to load it.
+	// If it's not analyzed yet.
 	if !hasAnalyzed {
-		return nil, false
+		// If we don't have it in memory, we create a fake hist for pseudo estimation.
```
Comment (time-and-fate) [inline pkg/statistics/table.go:642]:
```suggestion
		// If we don't have it in memory, we create a fake hist for pseudo estimation (see handleOneItemTask()).
```

File: pkg/planner/core/collect_column_stats_usage.go (hunk 2 above)
Comment (winoros) [reply pkg/planner/core/collect_column_stats_usage.go:198]: Such that ID=-1 means ExtraHandleCol

File: pkg/statistics/table.go (hunk 5 above)
Comment (winoros) [reply pkg/statistics/table.go:645]: Such that `alter table add column` ddl event is not handled by the StatsHandle. Currently, the statistis.Table is initialized by the stats. not by the model.TableInfo

**Review by time-and-fate — APPROVED** [review]
