### PR TITLE
*: fix wrong result when to concurrency merge global stats 

### LINKED ISSUE #48713: raise illegal bucket order while to merge global stats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create a partition table.

run ``` analyze table ``` for it.

### 3. What did you see instead (Required)

```
[2023/11/19 02:38:46.806 +08:00] [WARN] [global_stats_async.go:295] ["dealHistogramAndTopN failed"] [error="illegal bucket order"] [category=stats]
[2023/11/19 02:38:46.806 +08:00] [WARN] [analyze_global_stats.go:97] ["merge global stats failed"] [info="merge global stats for db0ios.table0ios columns"] [error="illegal bucket order"] [tableID=1261936]
[2023/11/19 23:03:04.065 +08:00] [WARN] [global_stats_async.go:295] ["dealHistogramAndTopN failed"] [error="illegal bucket order"] [category=stats]
[2023/11/19 23:03:04.065 +08:00] [WARN] [analyze_global_stats.go:97] ["merge global stats failed"] [info="merge global stats for db0ios.table0ios's index primary"] [error="illegal bucket order"] [tableID=1261936]
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #48713

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -497,7 +497,7 @@ bazel_test: failpoint-enable bazel_prepare
 
 
 bazel_coverage_test: failpoint-enable bazel_ci_simple_prepare
-	bazel $(BAZEL_GLOBAL_CONFIG) --nohome_rc coverage $(BAZEL_CMD_CONFIG) --jobs=35 --build_tests_only --test_keep_going=false \
+	bazel $(BAZEL_GLOBAL_CONFIG) --nohome_rc coverage -k $(BAZEL_CMD_CONFIG) --jobs=35 --build_tests_only --test_keep_going=false \
```
Comment (elsa0520) [inline Makefile:500]: What's this used for ?

File: pkg/statistics/handle/globalstats/merge_worker.go [hunk 2]
```diff
@@ -79,33 +83,24 @@ func NewTopnStatsMergeTask(start, end int) *TopnStatsMergeTask {
...
 		checkTopNs := worker.statsWrapper.AllTopN[start:end]
 		allTopNs := worker.statsWrapper.AllTopN
 		allHists := worker.statsWrapper.AllHg
 		resp := &TopnStatsMergeResponse{}
-		if statistics.CheckEmptyTopNs(checkTopNs) {
-			worker.respCh <- resp
-			return
-		}
+
 		partNum := len(allTopNs)
```
Comment (hawkingrei) [inline pkg/statistics/handle/globalstats/merge_worker.go:99]: BUG 1:

It should check all tops. but here is to check the part. it will create a bug.

File: pkg/statistics/handle/globalstats/merge_worker.go [hunk 3]
```diff
@@ -118,12 +113,15 @@ func (worker *topnStatsMergeWorker) Run(timeZone *time.Location, isIndex bool,
 			}
 			for _, val := range topN.TopN {
 				encodedVal := hack.String(val.Encoded)
-				_, exists := counter[encodedVal]
-				counter[encodedVal] += float64(val.Count)
+				worker.mu.Lock()
+				_, exists := worker.counter[encodedVal]
+				worker.counter[encodedVal] += float64(val.Count)
 				if exists {
```
Comment (hawkingrei) [inline pkg/statistics/handle/globalstats/merge_worker.go:119]: BUG 2

it should merge the global counter.

Comment (hawkingrei) [reply pkg/statistics/handle/globalstats/merge_worker.go:119]: BUG 3 

and it will create wrong result from ```BinarySearchRemoveVal```. it will remove it second.

File: Makefile (hunk 1 above)
Comment (hawkingrei) [reply Makefile:500]: it is used to make CI continue to run since it meet errors. it will revert before merging.

File: pkg/sessionctx/variable/tidb_vars.go [hunk 4]
```diff
@@ -1361,7 +1361,7 @@ const (
 	DefTiDBOptRangeMaxSize                       = 64 * int64(size.MB) // 64 MB
 	DefTiDBCostModelVer                          = 2
 	DefTiDBServerMemoryLimitSessMinSize          = 128 << 20
-	DefTiDBMergePartitionStatsConcurrency        = 1
+	DefTiDBMergePartitionStatsConcurrency        = 2
```
Comment (elsa0520) [inline pkg/sessionctx/variable/tidb_vars.go:1364]: Add a todo comment to change it back 1 (This is a temp value just for test concurrency partition stats)

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]

File: pkg/sessionctx/variable/tidb_vars.go (hunk 4 above)
Comment (hawkingrei) [reply pkg/sessionctx/variable/tidb_vars.go]: I have been reverted.
