### PR TITLE
store/tikv: fix misuse of PD client's GetStore

### LINKED ISSUE #23676: TiDB wrongly uses PD client's GetStore which may result in dead loops
## Bug Report

When TiDB meets the `StoreNotMatch` error, it will resolve the store through PD client's `GetStore()`:
- If the store is deleted or a tombstone, regions on this store are all invalidated. 

However, TiDB wrongly uses the PD client's `GetStore()`:
https://github.com/pingcap/tidb/blob/a8a52c0175b91ffab369ddeb1c6b642ce1b76cf2/store/tikv/region_cache.go#L1775-L1793

TiDB assumes it returns nil if the store is not found. In fact, if the store is a tombstone, it returns nil; if the store is not found, it returns an error. https://github.com/tikv/pd/blob/bc63de897afa69cfcc5828f45431fe3999fed4b3/client/client.go#L1159-L1168
```go
func handleStoreResponse(resp *pdpb.GetStoreResponse) (*metapb.Store, error) {
	store := resp.GetStore()
	if store == nil {
		return nil, errors.New("[pd] store field in rpc response not set")
	}
	if store.GetState() == metapb.StoreState_Tombstone {
		return nil, nil
	}
	return store, nil
}
```

So https://github.com/pingcap/tidb/issues/22907 is not resolved.

### PR DESCRIPTION
**Pull request by longfangsong**
Signed-off-by: longfangsong <longfangsong@icloud.com>

### What problem does this PR solve?

Issue Number: close #23676

Problem Summary:

- TiDB wrongly uses the PD client's `GetStore()`, which may result in dead loops. 
- `store.State` isn't changed if it becomes a tombstone

### What is changed and how it works?

What's Changed: 

Skip the early-return `if` branch  when "load Store from PD success but pd didn't found the store"

How it Works:

By checking the error message. This is a quick and dirty solution. A better solution (which needs to change the pdClient, and maybe the whole way of our error handling process) needs more discussion.

### Related changes

- Need to cherry-pick to the release branch
  Needs to cherry-pick to 5.0.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

File: store/tikv/region_cache.go [hunk 1]
```diff
@@ -1778,16 +1778,20 @@ func (s *Store) reResolve(c *RegionCache) (bool, error) {
...
-	if err != nil {
+	// when the error is "[pd] store field in rpc response not set",
+	// it means load Store from PD success but pd didn't found the store
+	// so this error should be handled by next `if` instead of here
+	if err != nil && err.Error() != "[pd] store field in rpc response not set" {
 		logutil.BgLogger().Error("loadStore from PD failed", zap.Uint64("id", s.storeID), zap.Error(err))
 		// we cannot do backoff in reResolve loop but try check other store and wait tick.
 		return false, err
 	}
-	if store == nil || store.State == metapb.StoreState_Tombstone {
```
Comment (longfangsong) [inline store/tikv/region_cache.go:1786]: if the store's `State == metapb.StoreState_Tombstone`, `store` variable here will always be `nil`.

File: store/tikv/region_cache.go [hunk 2]
```diff
@@ -1768,6 +1770,13 @@ func (s *Store) initResolve(bo *Backoffer, c *RegionCache) (addr string, err err
 	}
 }
 
+// A quick and dirty solution to found whether an err is caused by StoreNotFound.
+// todo: A better solution, maybe some err-code based error handling?
+func isStoreNotFoundError(err error) bool {
+	return err.Error() == "[pd] store field in rpc response not set" ||
+		(strings.Contains(err.Error(), "invalid store ID") && strings.Contains(err.Error(), "not found"))
```
Comment (youjiali1995) [inline store/tikv/region_cache.go:1777]:
```suggestion
	return strings.Contains(err.Error(), "invalid store ID") && strings.Contains(err.Error(), "not found")
```

Comment (youjiali1995) [reply store/tikv/region_cache.go:1777]: Confirmed with PD members. `"[pd] store field in rpc response not set"` may happen when the leader of PD is changed.

File: store/tikv/region_cache.go [hunk 3]
```diff
@@ -1778,16 +1787,20 @@ func (s *Store) reResolve(c *RegionCache) (bool, error) {
 	} else {
 		metrics.RegionCacheCounterWithGetStoreOK.Inc()
 	}
-	if err != nil {
+	// `err` here can mean "load Store from PD failed" or "store not found"
+	// if load Store from PD is successful but pd didn't found the store
```
Comment (youjiali1995) [inline store/tikv/region_cache.go:1791]:
```suggestion
	// If load Store from PD is successful but PD didn't find the store
```

**Comment by youjiali1995** [comment]
Seems the root cause of https://github.com/pingcap/tidb/issues/22907 is not this PR. Nevertheless, this PR fixes some problems.

**Review by MyonKeminta — COMMENTED** [review]
LGTM

**Review by MyonKeminta — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Comment by zhangjinpeng1987** [comment]
Should we pick this fix to 5.0?

**Comment by youjiali1995** [comment]
> Should we pick this fix to 5.0?

@zhangjinpeng1987 No. Even though TiDB wrongly uses it, TiDB works well with no issues.
