### PR TITLE
expression, planner: fix ambiguous column name in overflow error message

### LINKED ISSUE #17993: Ambiguous warning when multiply result out of range
## Bug Report

It should return a clear error message regarding the original expression.

### 1. Minimal reproduce step (Required)

````
drop table if exists t5;
create table t5 (col0 CHAR(204), col1 VARBINARY(105), col2 TIMESTAMP, col3 TEXT, col4 FLOAT, col5 INT, col6 DOUBLE, col7 BIGINT, col8 BINARY(166), col9 DATETIME);
insert into t5 values ('73d6f787-e7d5-4238-97a2-fe789e18c2fd', '1101001', '1970-01-04 00:00:01', 'x', '86.5241691045369', '-0', '261.3998105809103', '-9223372036854775807', '100111', '1000-01-02 00:00:00');
create index dlzae on t5 (col7, col2);
SELECT col3 from t5 where t5.col7 * ABS(-9223372036854775807) ;
````

### 2. What did you expect to see? (Required)

Clear error message about the `out of range`.

```` MySQL 5.7
mysql> SELECT col3 from t5 where t5.col7 * ABS(-9223372036807) ;
ERROR 1690 (22003): BIGINT value is out of range in '(`test`.`t5`.`col7` * <cache>(abs(-(9223372036807))))'
````

### 3. What did you see instead (Required)

What is `Column#0`?

````
mysql> SELECT col3 from t5 where t5.col7 * ABS(-9223372036854775807) ;
ERROR 1690 (22003): BIGINT value is out of range in '(Column#0 * 9223372036854775807)'
````

### 4. Affected version (Required)

````
commit 4e74d40392e9b81f2a90cbc2f7777fd35f87b2e7 (HEAD -> master, origin/master, origin/HEAD)
Author: Arenatlx <ailinsilence4@gmail.com>
Date:   Fri Jun 12 16:58:00 2020 +0800
````

### PR DESCRIPTION
**Pull request by minleejae**
### What problem does this PR solve?

Issue Number: close #17993

Problem Summary:
When an arithmetic overflow occurs, the error message displays "Column#N" instead of the actual column name, making it difficult for users to identify which column caused the issue.

**Before:**
```sql
mysql> SELECT col3 from t5 where t5.col7 * ABS(-9223372036854775807);
ERROR 1690 (22003): BIGINT value is out of range in '(Column#0 * 9223372036854775807)'
```

**After:**
```sql
mysql> SELECT col3 from t5 where t5.col7 * ABS(-9223372036854775807);
ERROR 1690 (22003): BIGINT value is out of range in '(t5.col7 * 9223372036854775807)'
```

### What changed and how does it work?

The root cause is that the `OrigName` field of `Column` struct was not being set in certain code paths:

1. **`expression_rewriter.go`**: In the `toColumn()` function, when a column is resolved from table metadata directly (fallback path when `planCtx == nil`), the `OrigName` was not set.

2. **`task.go`**: In the `appendExpr()` function used for MPP projection columns, the `OrigName` was not set for newly created columns.

This fix ensures `OrigName` is properly set in both locations, so error messages display meaningful column names.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that overflow error messages display "Column#N" instead of the actual column name, improving error message clarity for debugging.
```

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
/ok-to-test

**Comment by lance6716** [comment]
Hi @minleejae you can see `TestIssue59877` is failed in CI. The output format is changed which is not acceptable to me. Please limit the change scopr of your PR.

**Comment by minleejae** [comment]
Hi @lance6716 I've removed the `task.go` changes that were causing the `TestIssue59877` failure.
The fix now only modifies `expression_rewriter.go` to set `OrigName` in the fallback path.

File: pkg/planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -2556,8 +2556,12 @@ func (er *expressionRewriter) toColumn(v *ast.ColumnName) {
 			er.err = plannererrors.ErrUnknownColumn.GenWithStackByArgs(v.Name, clauseMsg[er.clause()])
 			return
 		}
-		er.ctxStackAppend(&expression.Column{RetType: &colInfo.FieldType, ID: colInfo.ID, UniqueID: colInfo.ID},
-			&types.FieldName{ColName: v.Name})
+		er.ctxStackAppend(&expression.Column{
+			RetType:  &colInfo.FieldType,
+			ID:       colInfo.ID,
+			UniqueID: colInfo.ID,
+			OrigName: fmt.Sprintf("%s.%s", er.sourceTable.Name.L, colInfo.Name.L),
```
Comment (windtalker) [inline pkg/planner/core/expression_rewriter.go:2563]: what about the case that the column is a derived column? For example
```
SELECT col3 from t5 where (t5.col7 + t5.col2) * ABS(-9223372036854775807);
```

Comment (minleejae) [reply pkg/planner/core/expression_rewriter.go:2563]: @windtalker 
Added a subtest `DerivedColumn` to cover this case. The derived expression `(col1 + col2)` is a `ScalarFunction`, which recursively calls `StringWithCtx()` on its child columns, so the column names display correctly.

**Review by windtalker — APPROVED** [review]
lgtm
