### PR TITLE
executor: fix the projection upon the indexLookUp in indexLookUpJoin can't get result.

### LINKED ISSUE #12785: Wrong result for index merge join when using projection upon the indexlookup
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Wrong result for index merge join when using projection upon the indexlookup.
(Hint: I wil try to find a SQL that don't need to change the cost model , and also trigger  the bug. )
```
use test;
drop table if exists t1, t2;
create table t1(a int, b date, c float, primary key(a, b));
create table t2(a int primary key);
insert into t1 values(1, '2017-11-29', 2.2);
insert into t2 values(1);
select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
```
2. What did you expect to see?
```
tidb> select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
+---+------------+------+---+
| a | b          | c    | a |
+---+------------+------+---+
| 1 | 2017-11-29 |  2.2 | 1 |
+---+------------+------+---+
1 row in set (0.01 sec)
```

3. What did you see instead?

I change the cost model , and focus to use index merge join.

```
tidb> select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
Empty set (0.00 sec)

tidb> desc analyze select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+------------------------------------------------------+-----------+
| id                       | count | task      | operator info                                                                                   | execution info                                       | memory    |
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+------------------------------------------------------+-----------+
| IndexMergeJoin_25        | 1.00  | root      | inner join, inner:Projection_23, outer key:Column#5, inner key:Column#1                         | time:546.102µs, loops:2, rows:0                      | 745 Bytes |
| ├─Projection_23          | 1.00  | root      | Column#1, Column#2, Column#3                                                                    | time:73.202µs, loops:1, rows:0                       | N/A       |
| │ └─IndexLookUp_22       | 1.00  | root      |                                                                                                 | time:72.229µs, loops:1, rows:0                       | 0 Bytes   |
| │   ├─IndexScan_20       | 1.00  | cop[tikv] | table:t1, index:a, b, range: decided by [eq(Column#1, Column#5)], keep order:true, stats:pseudo | time:0s, loops:0, rows:0                             | N/A       |
| │   └─TableScan_21       | 1.00  | cop[tikv] | table:t1, keep order:false, stats:pseudo                                                        | time:0s, loops:0, rows:0                             | N/A       |
| └─TableReader_29         | 1.00  | root      | data:TableScan_28                                                                               | time:108.032µs, loops:2, rows:1, rpc time:136.84µs   | 127 Bytes |
|   └─TableScan_28         | 1.00  | cop[tikv] | table:t2, range:[-inf,+inf], keep order:false, stats:pseudo                                     | time:73.076µs, loops:2, rows:1                       | N/A       |
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+------------------------------------------------------+-----------+
7 rows in set (0.00 sec)

```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master - e168fd93f

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve? 

Fixes #12785 

In `buildProjectionForIndexJoin` function, it calls `ProjectionExec.Open()` and recursive calls `IndexLookUpExecutor.Open()`. In this function, IndexLookUp will re-calculate `kvRanges`  using `e.ranges`. 
In this case, `e.ranges` is not initiated and will build a empty range.

### What is changed and how it works?

Only init `ProjectExec` and don't recursive init childExec. 
The childExec will be initiated in other `buildxxxForIndexJoin` function.

### Check List 

Tests 

 - Unit test
 - Integration test
-  Manual test

1. Change the cost model to choose IndexMergeJoin.
2. Run the following SQL in master and this pr.
```
use test;
drop table if exists t1, t2;
create table t1(a int, b date, c float, primary key(a, b));
create table t2(a int primary key);
insert into t1 values(1, '2017-11-29', 2.2);
insert into t2 values(1);
select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
```
2.1 In master,
```
tidb> select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
Empty set (0.00 sec)

tidb> desc analyze select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+------------------------------------------------------+-----------+
| id                       | count | task      | operator info                                                                                   | execution info                                       | memory    |
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+------------------------------------------------------+-----------+
| IndexMergeJoin_25        | 1.00  | root      | inner join, inner:Projection_23, outer key:Column#5, inner key:Column#1                         | time:546.102µs, loops:2, rows:0                      | 745 Bytes |
| ├─Projection_23          | 1.00  | root      | Column#1, Column#2, Column#3                                                                    | time:73.202µs, loops:1, rows:0                       | N/A       |
| │ └─IndexLookUp_22       | 1.00  | root      |                                                                                                 | time:72.229µs, loops:1, rows:0                       | 0 Bytes   |
| │   ├─IndexScan_20       | 1.00  | cop[tikv] | table:t1, index:a, b, range: decided by [eq(Column#1, Column#5)], keep order:true, stats:pseudo | time:0s, loops:0, rows:0                             | N/A       |
| │   └─TableScan_21       | 1.00  | cop[tikv] | table:t1, keep order:false, stats:pseudo                                                        | time:0s, loops:0, rows:0                             | N/A       |
| └─TableReader_29         | 1.00  | root      | data:TableScan_28                                                                               | time:108.032µs, loops:2, rows:1, rpc time:136.84µs   | 127 Bytes |
|   └─TableScan_28         | 1.00  | cop[tikv] | table:t2, range:[-inf,+inf], keep order:false, stats:pseudo                                     | time:73.076µs, loops:2, rows:1                       | N/A       |
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+------------------------------------------------------+-----------+
7 rows in set (0.00 sec)
```

2.2 In this pr,

```
tidb> select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
+---+------------+------+---+
| a | b          | c    | a |
+---+------------+------+---+
| 1 | 2017-11-29 |  2.2 | 1 |
+---+------------+------+---+
1 row in set (0.01 sec)

tidb> desc analyze select /*+ TIDB_INLJ(t1) */ * from t1 join t2 on t1.a=t2.a;
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------+---------------+
| id                       | count | task      | operator info                                                                                   | execution info                                        | memory        |
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------+---------------+
| IndexMergeJoin_25        | 1.00  | root      | inner join, inner:Projection_23, outer key:Column#5, inner key:Column#1                         | time:2.865241ms, loops:4, rows:2                      | 745 Bytes     |
| ├─Projection_23          | 1.00  | root      | Column#1, Column#2, Column#3                                                                    | time:502.299µs, loops:2, rows:1                       | N/A           |
| │ └─IndexLookUp_22       | 1.00  | root      |                                                                                                 | time:497.121µs, loops:2, rows:1, rpc time:123.668µs   | 9.73046875 KB |
| │   ├─IndexScan_20       | 1.00  | cop[tikv] | table:t1, index:a, b, range: decided by [eq(Column#1, Column#5)], keep order:true, stats:pseudo | time:49.991µs, loops:2, rows:1                        | N/A           |
| │   └─TableScan_21       | 1.00  | cop[tikv] | table:t1, keep order:false, stats:pseudo                                                        | time:35.144µs, loops:2, rows:1                        | N/A           |
| └─TableReader_29         | 1.00  | root      | data:TableScan_28                                                                               | time:454.372µs, loops:2, rows:1, rpc time:1.558265ms  | 127 Bytes     |
|   └─TableScan_28         | 1.00  | cop[tikv] | table:t2, range:[-inf,+inf], keep order:false, stats:pseudo                                     | time:216.994µs, loops:2, rows:1                       | N/A           |
+--------------------------+-------+-----------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------+---------------+
7 rows in set (0.00 sec)
```

Code changes

Side effects

 - Increased code complexity

Related changes

Release note

### CODE REVIEW

File: executor/projection.go [hunk 1]
```diff
@@ -77,6 +77,13 @@ func (e *ProjectionExec) Open(ctx context.Context) error {
 	if err := e.baseExecutor.Open(ctx); err != nil {
 		return err
 	}
+	return e.open(ctx)
+}
+
+func (e *ProjectionExec) open(ctx context.Context) error {
+	// We have to initialize execution resources in here instead of in function "Open",
```
Comment (XuHuaiyu) [inline executor/projection.go]: This comment is unnecessary.

File: executor/builder.go [hunk 2]
```diff
@@ -2230,7 +2230,7 @@ func (builder *dataReaderBuilder) buildProjectionForIndexJoin(ctx context.Contex
 	if int64(v.StatsCount()) < int64(builder.ctx.GetSessionVars().MaxChunkSize) {
 		e.numWorkers = 0
 	}
-	err = e.Open(ctx)
+	err = e.open(ctx)
```
Comment (XuHuaiyu) [inline executor/builder.go]: Can we try to refine the test case in the issue, and ensure IndexMergeJoin can be chosen?
