### PR TITLE
session: add upgrade policy for analyze distsql concurrency

### LINKED ISSUE #65423: tidb_analyze_disql_scan_concurrency may slow down manual analyze for upgraded cluster
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When we are in a cluster whose version is no greater than v7.5, the concurrency setting of its manual analyze is controlled by the `tidb_distsql_scan_concurrency`, whose default value is 15.

We introduced the new var `tidb_analyze_distsql_scan_concurrency` later in v7.6 and set its default value as 4.

So if an old cluster upgrades to a version no lower than v7.6, its analyze's scan concurrency may change from `tidb_distsql_scan_concurrency` to the new var `tidb_analyze_distsql_scan_concurrency`. The user will feel that the analyze becomes slower than before and need fix it by hand.

### 4. What is your TiDB version? (Required)

v8.5.5, v8.1.2, master

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/65423

Problem Summary:

### What changed and how does it work?

When the cluster upgrades from a version that doesn't have `tidb_analyze_distsql_scan_concurrency`, TiDB will set its default value to the current global value of `tidb_distsql_scan_concurrency` to avoid performance degradation.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Chores**
  * Bumped cluster bootstrap version to 256 and added upgrade logic to ensure analyze distsql scan concurrency is preserved during upgrades from 7.5→8.5.
  * Adjusted test sharding configuration.

* **Tests**
  * Added upgrade test covering analyze distsql scan concurrency migration.
  * Updated an existing system-table test expectation to match the new bootstrap version.

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/session/test/bootstraptest/bootstrap_upgrade_test.go [hunk 1]
```diff
@@ -1178,3 +1179,53 @@ func TestUpgradeWithAnalyzeColumnOptions(t *testing.T) {
...
+func TestAnalyzeDistsqlConcurrencyByUpgrade760To850(t *testing.T) {
+	if kerneltype.IsNextGen() {
+		t.Skip("Skip this case because there is no upgrade in the first release of next-gen kernel")
+	}
+	ctx := context.Background()
+	store, dom := session.CreateStoreAndBootstrap(t)
+	defer func() { require.NoError(t, store.Close()) }()
+
+	// Upgrade from 7.6.0 to 8.5+ or above.
+	ver760 := 190
```
Comment (0xPoe) [inline pkg/session/test/bootstraptest/bootstrap_upgrade_test.go]:
```suggestion
	// Upgrade from 7.5.0 to 8.5+ or above.
	ver760 := 180
```

The current Bootstrap Version for v7.6.0 is version 182. We introduced TiDB Analyze Dist SQL Scan Concurrency in v7.6.0. Should we test it starting from v7.5.0?

Comment (0xPoe) [reply pkg/session/test/bootstraptest/bootstrap_upgrade_test.go]: Please update the name of the test function as well.

**Review by 0xPoe — APPROVED** [review]
Thanks! :shipit: 

/hold 

https://github.com/pingcap/tidb/pull/65424/changes#r2699068509

**Review by yudongusa — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
