### PR TITLE
statistics, config: rightly deal with innodb_lock_wait_timeout when to load stats

### LINKED ISSUE #65634: large plan replayer will raise the `Lock wait timeout exceeded`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

plan replayer load the partition table which has many partition (more than 1000)

### 3. What did you see instead (Required)

"plan replayer load './plan_replayer1121.zip';\" at line 4 err Error 1205 (HY000): Lock wait timeout exceeded; try restarting transaction"

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65634

Problem Summary:

load large plan replayer (for example, plan replayer testing). You will see this error log.

```
[2026/01/19 15:34:53.818 +08:00] [WARN] [conn.go:1215] ["command dispatched failed"] [conn=2650800358] [session_alias=] [connInfo="id:2650800358, addr:127.0.0.1:37854 status:10, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="plan replayer load './replayer/partition/xxxx/plan_replayer1121.zip'"] [txn_mode=PESSIMISTIC] [timestamp=463682415160721420] [err="[tikv:1205]Lock wait timeout exceeded; try restarting transaction\ngithub.com/pingcap/errors.Trace\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20250523034308-74f78ae071ee/juju_adaptor.go:15\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.finishTransaction\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:71\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.WrapTxn.func1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:195\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.WrapTxn\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:198\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1.1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:95\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext.func1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:519\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).OwnerWithSctx\n\t/workspace/source/tidb/pkg/session/syssession/session.go:278\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext\n\t/workspace/source/tidb/pkg/session/syssession/session.go:518\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:83\ngithub.com/pingcap/tidb/pkg/session/syssession.(*AdvancedSessionPool).WithSession\n\t/workspace/source/tidb/pkg/session/syssession/pool.go:274\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:82\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).SaveColOrIdxStatsToStorage\n\t/workspace/source/tidb/pkg/statistics/handle/storage/stats_read_writer.go:213\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).loadStatsFromJSON.func1\n\t/workspace/source/tidb/pkg/statistics/handle/storage/stats_read_writer.go:677\ngithub.com/pingcap/tidb/pkg/statistics.(*HistColl).ForEachColumnImmutable\n\t/workspace/source/tidb/pkg/statistics/table.go:333\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).loadStatsFromJSON\n\t/workspace/source/tidb/pkg/statistics/handle/storage/stats_read_writer.go:673\ngithub.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsReadWriter).LoadStatsFromJSONConcurrently.func1\n\t/workspace/source/tidb/pkg/statistics/handle/storage/stats_read_writer.go:595\ngithub.com/tiancaiamao/gp.workerLoop\n\t/root/go/pkg/mod/github.com/tiancaiamao/gp@v0.0.0-20221230034425-4025bc8a4d4a/gp.go:72\ngithub.com/tiancaiamao/gp.worker\n\t/root/go/pkg/mod/github.com/tiancaiamao/gp@v0.0.0-20221230034425-4025bc8a4d4a/gp.go:51\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1693"]
```
### What changed and how does it work?

1. plan replayer cannot load innodb_lock_wait_timeout
2. when loading stats, we use global innodb_lock_wait_timeout into internal sql.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

test it with plan replayer testing.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/util/config/config.go [hunk 1]
```diff
@@ -27,6 +27,10 @@ import (
 	"go.uber.org/zap"
 )
 
+var ignoredSystemVariablesForPlanReplayerLoad = map[string]struct{}{
+	"innodb_lock_wait_timeout": {}, // It is unncessary to load this variable for plan replayer.
```
Comment (time-and-fate) [inline pkg/util/config/config.go]: We can use `vardef.InnodbLockWaitTimeout`.

Comment (time-and-fate) [reply pkg/util/config/config.go]: > unncessary

typo

**Review by time-and-fate — APPROVED** [review]

File: pkg/util/config/config.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/util/config/config.go]: OK, I have updated.

File: pkg/util/config/config.go [hunk 2]
```diff
@@ -27,6 +27,10 @@ import (
 	"go.uber.org/zap"
 )
 
+var ignoredSystemVariablesForPlanReplayerLoad = map[string]struct{}{
+	vardef.InnodbLockWaitTimeout: {}, // It is unnecessary to load this variable for plan replayer.
+}
+
 // LoadConfig loads system variables from a toml reader. it is only for plan replayer and test.
 func LoadConfig(ctx sessionctx.Context, v io.ReadCloser) (unLoadVars []string, err error) {
```
Comment (mjonss) [inline pkg/util/config/config.go]: Could we rename this to `LoadConfigForPlanReplayer` instead of having a generic name not specifying that it should not be used anywhere else?

**Review by mjonss — APPROVED** [review]
Please consider renaming LoadConfig to LoadConfigForPlanReplayer, so it is more clear to not be used in any other context.

File: pkg/util/config/config.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/util/config/config.go]: I have renamed it.
