### PR TITLE
types: refine JSON conversion, throw err when object/array convert to integer/float/decimal

### LINKED ISSUE #21362: The behavior of conversion from JSON object/array to integer/float is incompatible with MySQL
## Development Task
In current TiDB implementation, the conversion from JSON object/array to integer/float is simply set to 0 with no error or warning:
``` sql
drop table if exists test_json;
create table test_json (a json, i int);
insert into test_json values('{"key": 1}', 1);
insert into test_json(`i`) select a from test_json;
```

output:
``` shell
mysql> select * from test_json;
+------------+------+
| a          | i    |
+------------+------+
| {"key": 1} |    1 |
| NULL       |    0 |
+------------+------+
2 rows in set (0.00 sec)
```

On the contrary, MySQL will get error:
``` shell
mysql> insert into test_json(`i`) select a from test_json;
ERROR 3156 (22018): Invalid JSON value for CAST to INTEGER from column a at row 2
```

The float conversion will get same result.

We better return an error or waning when cast json object/array to integer/float. 

Some related repo maybe influenced since the convert function is a low level logic. Such repo like: tikv(push down expr), copr test, common test, etc.

### PR DESCRIPTION
**Pull request by LENSHOOD**
### What problem does this PR solve?

Issue Number: close #21362

Problem Summary:
TiDB implementation get incompatible result with MySQL when convert JSON object/array to integer/float/decimal.

MySQL will get `Invalid JSON value...` error while TiDB return 0.

### What is changed and how it works?
What's Changed:
1. Throw data truncate error when convert object/array to integer/float/decimal.
2. Wrap the error as warning when `TruncateAsWarning` is `true`.
3. According to MySQL, the JSON literal `null` convert to numbers will also get err, but TiDB treat `null` as `0` seems more properly. Therefore, I kept the `null` conversion logic.

### Related changes
1. some integration tests need to be updated
2. push down expr may need to be updated

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- types: refine JSON conversion, throw err when object/array convert to integer/float/decimal

### CODE REVIEW

**Comment by LENSHOOD** [comment]
@ti-srebot /run-all-tests

File: types/convert_test.go [hunk 1]
```diff
@@ -281,6 +281,14 @@ func (s *testTypeConvertSuite) TestConvertType(c *C) {
 	c.Assert(err, IsNil)
 	_, err = Convert(bj2, ft)
 	c.Assert(err, NotNil)
+	bj3, err := json.ParseBinaryFromString("{\"key\": 99}")
+	c.Assert(err, IsNil)
+	_, err = Convert(bj3, ft)
+	c.Assert(err, NotNil)
+	bj4, err := json.ParseBinaryFromString("[99 00 01]")
+	c.Assert(err, NotNil)
```
Comment (AilinKid) [inline types/convert_test.go:289]: if parse errors, it's meaningless to covert bj4?
```
bj4, err := json.ParseBinaryFromString("[99,0,1]")
c.Assert(err, IsNil)
```

Comment (LENSHOOD) [reply types/convert_test.go:289]: Fixing...

**Review by AilinKid — COMMENTED** [review]
LGTM

**Comment by LENSHOOD** [comment]
Related tikv-pr: https://github.com/tikv/tikv/pull/9320

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
