### PR TITLE
executor: return an error when updating TiDB instances' config items by `set config`

### LINKED ISSUE #17097: return an error when updating TiDB instances' config items by `set config`
## Development Task
When users want to use `set config tidb ...` to update TiDB instances' config, an error `TiDB doesn't support to change configs online, please use SQL variables` will be returned.
But if we specify a TiDB instance address, there is no error:
```
mysql> set config '127.0.0.1:4000' log.level='warn';
Query OK, 0 rows affected (0.00 sec)
```
We should return an error in this case.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #17097 

Problem Summary: return an error when updating TiDB instances' config items by `set config`

### What is changed and how it works?
If the target instance is TiDB, return an error.

### Check List 

Tests 

- Unit test

### Release note 
- return an error when updating TiDB instances' config items by `set config`

### CODE REVIEW

File: executor/set_config.go [hunk 1]
```diff
@@ -101,8 +101,10 @@ func (s *SetConfigExec) Next(ctx context.Context, req *chunk.Chunk) error {
 			url = fmt.Sprintf("%s://%s%s", util.InternalHTTPSchema(), serverInfo.StatusAddr, pdapi.Config)
 		case "tikv":
 			url = fmt.Sprintf("%s://%s/config", util.InternalHTTPSchema(), serverInfo.StatusAddr)
+		case "tidb":
+			return errors.Errorf("TiDB doesn't support to change configs online, please use SQL variables")
```
Comment (zz-jason) [inline executor/set_config.go:105]: `s/TiDB/tidb-server/` is more specific.
