### PR TITLE
ddl: fix some unit test funcion that can't run independently

### LINKED ISSUE #31085: run single test TestRenameTables fails
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
make failpoint-enable;
cd ddl;
go test -run TestRenameTables 
```

### 2. What did you expect to see? (Required)

Success

### 3. What did you see instead (Required)

```
--- FAIL: TestRenameTables (0.63s)
    table_test.go:43:
                Error Trace:    table_test.go:43
                                                        table_test.go:370
                Error:          Received unexpected error:
                                [ddl:-1]failed to notify PD the placement rules: infoSyncer is not initialized
                                github.com/pingcap/errors.AddStack
                                        /home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/errors.go:174
                                github.com/pingcap/errors.Trace
                                        /home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/juju_adaptor.go:15
                                github.com/pingcap/tidb/ddl.(*ddl).doDDLJob
                                        /home/genius/project/src/github.com/pingcap/tidb/ddl/ddl.go:627
                                github.com/pingcap/tidb/ddl.testCreateTableT
                                        /home/genius/project/src/github.com/pingcap/tidb/ddl/table_test.go:42
                                github.com/pingcap/tidb/ddl.TestRenameTables
                                        /home/genius/project/src/github.com/pingcap/tidb/ddl/table_test.go:370
                                testing.tRunner
                                        /home/genius/project/go/src/testing/testing.go:1193
                                runtime.goexit
                                        /home/genius/project/go/src/runtime/asm_amd64.s:1371
                Test:           TestRenameTables
FAIL
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #31085

Problem Summary:

Some test cases can't run independently:

```
make ut X='run ddl TestRenameTables'
```

or 

```
make failpoint-enable;
cd ddl;
go test -run TestRenameTables
```

It reports an error "[ddl:-1]failed to notify PD the placement rules: infoSyncer is not initialized"

### What is changed and how it works?

When the test case run with others, the global variable is initialized by other test cases

https://github.com/pingcap/tidb/blob/61d13b561c46839b589858c02399c95c891a08df/domain/infosync/info.go#L168-L170

This is a workaround to make it possible to run the single test case.

Modification on `tools/check/ut.go` is unrelated to this fix, it just make the output easier for debugging.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by tiancaiamao** [comment]
It's for https://github.com/pingcap/tidb/issues/30822

File: ddl/partition_test.go [hunk 1]
```diff
@@ -25,7 +25,8 @@ import (
 	"github.com/stretchr/testify/require"
 )
 
-func TestDropAndTruncatePartition(t *testing.T) {
+func ExportTestDropAndTruncatePartition(t *testing.T) {
+
```
Comment (hawkingrei) [inline ddl/partition_test.go:29]: Please remove this empty line.

**Review by hawkingrei — CHANGES_REQUESTED** [review]
Please remove this empty line

File: ddl/partition_test.go (hunk 1 above)
Comment (tiancaiamao) [reply ddl/partition_test.go]: Done

**Review by hawkingrei — APPROVED** [review]

File: tools/check/ut.go [hunk 2]
```diff
@@ -359,12 +367,12 @@ func (n *numa) runTestCase(pkg string, fn string, old bool) error {
 		cmd = n.testCommand(exe, fn, old)
 	}
 	cmd.Dir = path.Join(workDir, pkg)
-	_, err := cmd.CombinedOutput()
-	if err != nil {
-		// fmt.Println("run test case error", pkg, fn, string(output))
-		return err
+	cmd.Stdout = &res.output
```
Comment (bb7133) [inline tools/check/ut.go:370]: Is this related to your PR description? Please add a comment why you want to handle `Stdout` & `Stderr` here.

Comment (tiancaiamao) [reply tools/check/ut.go:370]: > Modification on tools/check/ut.go is unrelated to this fix, it just make the output easier for debugging.

Comment (tiancaiamao) [reply tools/check/ut.go:370]: In the past, the stdout/stderr of the test result is ignored, so it's not convenient to debug
The tool `ut` is still evolving, before one day it can be made in to default CI pipeline.

**Review by bb7133 — APPROVED** [review]
LGTM
