### PR TITLE
expression: return null for empty time format

### LINKED ISSUE #59445: `TIME_FORMAT` should return `NULL` for empty format
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

```
mysql> SELECT TIME_FORMAT('12:34:56', '');
+-----------------------------+
| TIME_FORMAT('12:34:56', '') |
+-----------------------------+
| NULL                        |
+-----------------------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```
mysql> SELECT TIME_FORMAT('12:34:56', '');
+-----------------------------+
| TIME_FORMAT('12:34:56', '') |
+-----------------------------+
|                             |
+-----------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #59445

Problem Summary:

`TIME_FORMAT(expr, format)` should return `NULL` when `format` is an empty string.

### What changed and how does it work?

- Return `NULL` early in `builtinTimeFormatSig.evalString` when the format string is empty.
- Add a regression case in `TestTimeFormat` for `TIME_FORMAT('12:34:56', '')`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Validation:

- `bazel test //pkg/expression:expression_test --test_sharding_strategy=disabled --test_arg=-test.run=^TestTimeFormat$ --test_arg=-test.v --test_output=streamed`
- `make lint`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix `TIME_FORMAT(expr, '')` to return `NULL`.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Time formatting now correctly returns NULL when given an empty format string, including in vectorized evaluation paths.

* **Tests**
  * Added unit and vectorized tests asserting TimeFormat yields NULL for an empty format string and verifying correct non-NULL formatting for valid patterns to prevent regressions.

### CODE REVIEW

File: pkg/expression/builtin_time.go [hunk 1]
```diff
@@ -6477,6 +6477,9 @@ func (b *builtinTimeFormatSig) evalString(ctx EvalContext, row chunk.Row) (strin
 	if err != nil || isNull {
 		return "", isNull, err
 	}
+	if len(formatMask) == 0 {
+		return "", true, nil
+	}
```
Comment (windtalker) [inline pkg/expression/builtin_time.go:6482]: what about the vec version?

Comment (hawkingrei) [reply pkg/expression/builtin_time.go:6482]: Good catch. I fixed the vectorized path as well and added a dedicated vectorized regression test in 187e8d8751.
