### PR TITLE
ddl: optimize temp index worker in highly conflicting case

### LINKED ISSUE #61433: Fast reorg create index is stuck at the stage of merging temp index, and the ddl job fails after retries
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set global tidb_ddl_enable_fast_reorg = on; -- turn off dxf after 8.5 at the same time
```
And add index with workload, the workload is updating the column related to the index col frequently. In the merge temp index stage, there will be los of `write conflict` in log. And after the ddl job reach the maximum retry count, ddl job will faild.

```
CREATE TABLE `t` (
  `a` varchar(64) NOT NULL , 
  `b` varchar(64) NOT NULL , 
  `c` varchar(64) DEFAULT NULL,
  `d` bigint(20) NOT NULL,
  `e` int(11) NOT NULL,
  `f` bigint(20) NOT NULL,
  `g` varchar(128) NOT NULL,
  `h` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `i` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`a`,`b`)
);

alter table t add index(b, f);

-- workload like this 
INSERT INTO
  `t` (
    `a`,
    `b`,
    `c`,
    `d`,
    `e`,
    `f`,
    `g`
  )
VALUES
  (...) ON DUPLICATE KEY 
UPDATE
  `a` = VALUES (`a`),
  `b` = VALUES (`b`),
  `c` = VALUES (`c`),
  `d` = VALUES(`d`),
  `e` = VALUES(`e`),
  `f` = VALUES (`f`),
  `g` = VALUES (`g`);
```

### 2. What did you expect to see? (Required)
Add index success
### 3. What did you see instead (Required)
Add index reatch the max error limit and failed.
```
Execute: Write conflict, txnStartTS=458282835105808427, conflictStartTS=458282835118915588, conflictCommitTS=0, key=????, reason=Optimistic [try again later].
```
### 4. What is your TiDB version? (Required)
v7.5.6

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #61433

Problem Summary:

When there are lots of conflicts between DDL internal txn and DML txn, temp index worker can hardly make any progress.

### What changed and how does it work?

- Remove the `LockKeys` in DDL internal txn from merge index worker.
  - if both DDL txn and DML txn modify the same index key, there will be a conflict and DDL txn will retry. (after [#62387](https://github.com/pingcap/tidb/pull/62387))
  - if DDL txn modifies the index key, DML txn only modifies the row key, there will be no conflict anymore (this is the key improvement).
- Delete temp index records after applying them to the original index to eliminate reentrant cost.
- Reduce the batch count of DDL txn when suffering frequent conflicts.
- Add metrics to monitor the progress of merging temp index:
  - `tidb_ddl_temp_index_write`: the counter of writing to temp index (single write).
  - `tidb_ddl_temp_index_double_write`: the counter of writing to temp index (double write).
  - `tidb_ddl_temp_index_scan`: the counter of scanned temp index value records.
  - `tidb_ddl_temp_index_merge`: the counter of merged temp index value records.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by D3Hunter — APPROVED** [review]

File: pkg/ddl/index_merge_tmp.go [hunk 1]
```diff
@@ -172,71 +174,101 @@ func (w *mergeIndexWorker) setCurrentIndexForRange(taskRange *reorgBackfillTask)
...
+			if err != nil {
+				return errors.Trace(err)
 			}
+			taskCtx.nextKey = nextKey
+			taskCtx.done = taskDone
 
-			// Lock the corresponding row keys so that it doesn't modify the index KVs
-			// that are changing by a pessimistic transaction.
-			rowKey := tablecodec.EncodeRecordKey(w.table.RecordPrefix(), idxRecord.handle)
-			err := txn.LockKeys(context.Background(), new(kv.LockCtx), rowKey)
```
Comment (cfzjywxk) [inline pkg/ddl/index_merge_tmp.go:218]: Is it risky to remove locking row key for all back fill cases?

File: pkg/ddl/index_merge_tmp.go [hunk 2]
```diff
@@ -292,6 +325,7 @@ func (w *mergeIndexWorker) fetchTempIndexVals(
 				return false, err
 			}
 
+			*scannedCnt += len(tempIdxVal)
```
Comment (zimulala) [inline pkg/ddl/index_merge_tmp.go:328]: Is this variable unused？

File: pkg/ddl/index_merge_tmp.go [hunk 3]
```diff
@@ -172,71 +174,101 @@ func (w *mergeIndexWorker) setCurrentIndexForRange(taskRange *reorgBackfillTask)
...
+					zap.Error(err))
+				continue
 			}
-			taskCtx.addedCount++
+			return taskCtx, errors.Trace(err)
 		}
-		return nil
-	})
+		if attempts <= 1 {
+			w.batchCnt = min(int(vardef.GetDDLReorgBatchSize()), w.batchCnt*2)
```
Comment (zimulala) [inline pkg/ddl/index_merge_tmp.go]: If attempts <= 1, it follows the original logic. So, can this assignment be moved before the for loop, and could the condition check be removed?"​

File: pkg/ddl/index_merge_tmp.go (hunk 1 above)
Comment (zimulala) [reply pkg/ddl/index_merge_tmp.go:218]: This PR(https://github.com/pingcap/tidb/pull/39936) adds `LockKeys`. Is it being removed here because the related issues have been resolved?
Additionally, the PR description doesn't seem to mention removing the `LockKeys`.

File: pkg/ddl/index_merge_tmp.go (hunk 3 above)
Comment (tangenta) [reply pkg/ddl/index_merge_tmp.go]: I prefer to put here so it is close to `w.batchCnt /= 2` logic. It indicates that we will multiply by two in each iteration if we encountered a lot of conflicts previously.

Comment (zimulala) [reply pkg/ddl/index_merge_tmp.go]: There was no `--` operation in this attempt, so `<=1` was the first attempt, and there was no need to revert to the original value the first time

File: pkg/ddl/index_merge_tmp.go (hunk 1 above)
Comment (zimulala) [reply pkg/ddl/index_merge_tmp.go:218]: I see the reason has been updated in the PR description. If you can, please briefly describe the manual testing
