### PR TITLE
util: fix unstable test in the TestNotifyErrorWaitGroupWrapper

### LINKED ISSUE #33062: Unstable test in the TestNotifyErrorWaitGroupWrapper
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c0001d0768 by goroutine 82:
  runtime.raceread()
      <autogenerated>:1 +0x24
  github.com/pingcap/tidb/util.(*NotifyErrorWaitGroupWrapper).Run()
      /go/tidb/util/wait_group_wrapper.go:76 +0x3c
  github.com/pingcap/tidb/util.TestNotifyErrorWaitGroupWrapper()
      /go/tidb/util/wait_group_wrapper_test.go:58 +0x151
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Previous write at 0x00c0001d0768 by goroutine 83:
  runtime.racewrite()
      <autogenerated>:1 +0x24
  github.com/pingcap/tidb/util.(*NotifyErrorWaitGroupWrapper).Run.func1.1()
      /go/tidb/util/wait_group_wrapper.go:82 +0x58
  github.com/pingcap/tidb/util.(*NotifyErrorWaitGroupWrapper).Run.func1()
      /go/tidb/util/wait_group_wrapper.go:87 +0xa9
  github.com/pingcap/tidb/util.(*NotifyErrorWaitGroupWrapper).Run·dwrap·4()
      /go/tidb/util/wait_group_wrapper.go:87 +0x47
Goroutine 82 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/util.TestMain()
      /go/tidb/util/main_test.go:26 +0x44
  main.main()
      _testmain.go:77 +0x264
Goroutine 83 (finished) created at:
  github.com/pingcap/tidb/util.(*NotifyErrorWaitGroupWrapper).Run()
      /go/tidb/util/wait_group_wrapper.go:78 +0x171
  github.com/pingcap/tidb/util.TestNotifyErrorWaitGroupWrapper()
      /go/tidb/util/wait_group_wrapper_test.go:58 +0x151
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
    wait_group_wrapper_test.go:63: 
        	Error Trace:	wait_group_wrapper_test.go:63
        	Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 2
        	Test:       	TestNotifyErrorWaitGroupWrapper
    testing.go:1152: race detected during execution of test 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

```NotifyErrorWaitGroupWrapper``` should use the Multi-Producers scene. if producers work in a short time. the Wait will make the program early finish.

Issue Number: close #33062

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: util/wait_group_wrapper_test.go [hunk 1]
```diff
@@ -56,6 +57,7 @@ func TestNotifyErrorWaitGroupWrapper(t *testing.T) {
 	var wg = NewNotifyErrorWaitGroupWrapper(errCh)
```
Comment (tiancaiamao) [inline util/wait_group_wrapper_test.go:57]: This abstraction is poor designed, error prone, and make the use get stuck easily!
I'd suggest just remove it.

Comment (hawkingrei) [reply util/wait_group_wrapper_test.go:57]: I think so. it is used in the analysis executor. so I think it may be suitable for their use.

**Review by tiancaiamao — APPROVED** [review]

File: executor/analyze.go [hunk 2]
```diff
@@ -2351,3 +2351,36 @@ func (w *analyzeResultsNotifyWaitGroupWrapper) Run(exec func()) {
 		exec()
 	}(old)
 }
+
+// notifyErrorWaitGroupWrapper is a wrapper for sync.WaitGroup
+type notifyErrorWaitGroupWrapper struct {
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply executor/analyze.go:2359]: Done

File: executor/analyze.go [hunk 3]
```diff
@@ -2338,7 +2341,39 @@ func NewAnalyzeResultsNotifyWaitGroupWrapper(notify chan *statistics.AnalyzeResu
...
+
+// newNotifyErrorWaitGroupWrapper is to create notifyErrorWaitGroupWrapper
+func newNotifyErrorWaitGroupWrapper(notify chan error) *notifyErrorWaitGroupWrapper {
+	return &notifyErrorWaitGroupWrapper{
+		notify: notify,
+		cnt:    *atomicutil.NewUint64(0),
+	}
+}
+
+// Run runs a function in a goroutine, adds 1 to WaitGroup
```
Comment (Defined2014) [inline executor/analyze.go:2373]: delete `adds 1 to WaitGroup`

File: executor/analyze.go [hunk 4]
```diff
@@ -2338,7 +2341,39 @@ func NewAnalyzeResultsNotifyWaitGroupWrapper(notify chan *statistics.AnalyzeResu
 // and calls done when function returns. Please DO NOT use panic
```
Comment (Defined2014) [inline executor/analyze.go:2341]: delete adds 1 to WaitGroup

Comment (hawkingrei) [reply executor/analyze.go]: Done

File: executor/analyze.go (hunk 3 above)
Comment (hawkingrei) [reply executor/analyze.go]: Done
