### PR TITLE
planner: consider connection collation when reusing cached plans

### LINKED ISSUE #47008: some  SQL result is not the same when enable/disable plancache
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In a session without plancache

```sql
set @@tidb_enable_prepared_plan_cache=0;
set @@time_zone='UTC';
set @@collation_connection='utf8_general_ci';
prepare s from 'select DATE_FORMAT("2020-01-01","%W") = "wednesday"';
execute s; -- output 1
set @@collation_connection='utf8_bin';
execute s; -- output 0
```

In a session with plancache

```sql
set @@tidb_enable_prepared_plan_cache=1;
set @@time_zone='UTC';
set @@collation_connection='utf8_general_ci';
prepare s from 'select DATE_FORMAT("2020-01-01","%W") = "wednesday"';
execute s; -- output 1
set @@collation_connection='utf8_bin';
execute s; -- output 1
```

### 2. What did you expect to see? (Required)

The second execute should output a same value not matter `tidb_enable_prepared_plan_cache` is on or off

### 3. What did you see instead (Required)

The output of the second execute is not the same for different `tidb_enable_prepared_plan_cache` value

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #47008

Problem Summary: planner: consider connection collation when reusing cached plans

### What is changed and how it works?

planner: consider connection collation when reusing cached plans

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: planner/core/plan_cache_utils_test.go [hunk 1]
```diff
@@ -1,57 +0,0 @@
-// Copyright 2018 PingCAP, Inc.
```
Comment (qw4990) [inline planner/core/plan_cache_utils_test.go:1]: This test is useless.

**Review by AilinKid — APPROVED** [review]
