### PR TITLE
executor, sessiontxn/isolation: fix max_execution_time to include TSO wait time

### LINKED ISSUE #64406: Enhancement: Start max_execution_timeout timer before buildExecutor() so TSO wait is included
## Enhancement
Now, max_execution_time starts when we set process info during the executor phase (executor/adapter.go: (*ExecStmt).Exec → pi.SetProcessInfo(sql, time.Now(), cmd, maxExecutionTime)), [refer](https://github.com/pingcap/tidb/blob/master/pkg/executor/adapter.go#L643-L663).

Although, TSO fetching is initiated asynchronously (GetTimestampAsync created during Optimize, after parse/compile), the blocking wait happens later in Exec during executor construction still exists:

Exec
  → buildExecutor()
    → b.build(a.Plan) → (e.g., buildPointGet)
      → b.getSnapshot() → GetSnapshotWithStmtReadTS()
        → getStmtTS() → stmtTSFuture.Wait()  

Because the timer starts after buildExecutor(), the time spent waiting on stmtTSFuture.Wait() is not counted. This causes:
- Timeout control that does not reflect end-to-end latency under PD/TSO pressure.
- ProcessList/observability underreporting perceived latency.
- User confusion when a “slow” query doesn’t time out.

### PR DESCRIPTION
**Pull request by King-Dylan**
### What problem does this PR solve?

Issue Number: close #64406

Problem Summary:
Because the timer starts after buildExecutor(), the time spent waiting on stmtTSFuture.Wait() is not counted. If, in some cases, we wait a long time for TSO, the max_execution_timeout parameter will appear to have no effect.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix an issue where the max_execution_time parameter did not include the time spent waiting for TSO, which could make the limit ineffective when TSO allocation is slow.
```

### CODE REVIEW

**Comment by bb7133** [comment]
The code change LGTM, but please add a proper 'Release Note' in the PR description.

File: pkg/sessiontxn/isolation/base.go [hunk 1]
```diff
@@ -687,6 +692,22 @@ func (f funcFuture) Wait() (uint64, error) {
 	return f()
 }
 
+// delayedOracleFuture wraps an oracle.Future to inject delay before Wait() for testing
+type delayedOracleFuture struct {
```
Comment (zimulala) [inline pkg/sessiontxn/isolation/base.go]: The `delayedOracleFuture` wrapper introduces test-only logic into the production path, adding an extra indirection for every TSO fetch.

A cleaner approach might be to inject the failpoint directly at the `Wait()` call site in `ActivateTxn()`, instead of wrapping the entire oracle. This would keep the production code simpler and better isolate test-only behavior. The code is as follows:
```
func (p *baseTxnContextProvider) ActivateTxn() (kv.Transaction, error) {
    // ...
    txnFuture := p.sctx.GetPreparedTxnFuture()
    
    // Inject delay before TSO wait for testing maxExecutionTime
    failpoint.Inject("injectTSOWaitDelay", func(val failpoint.Value) {
        if delayMs, ok := val.(int); ok {
            time.Sleep(time.Duration(delayMs) * time.Millisecond)
        }
    })
    
    txn, err := txnFuture.Wait(p.ctx, p.sctx)
    // ...
}
```

File: pkg/executor/adapter_test.go [hunk 2]
```diff
@@ -540,3 +540,88 @@ func BenchmarkCheckSlowLogRulesPreAlloc(b *testing.B) {
...
+			description:      "TSO wait time (800ms) should be included, total < 1000ms",
+		},
+		{
+			name:             "TSO delay 1200ms, timeout 500ms - should timeout",
+			tsoDelayMs:       1200,
+			maxExecutionTime: 500,
+			expectTimeout:    true,
+			description:      "TSO wait time (1200ms) exceeds timeout (500ms)",
+		},
+	}
```
Comment (zimulala) [inline pkg/executor/adapter_test.go:580]: The test may be flaky in CI due to:
1. Long execution time: Total sleep time is 300+800+1200 = 2.3s, which could be slower under CI load.
2. Tight margins: The case {tsoDelayMs: 800, maxExecutionTime: 1000} has only 200ms headroom, which may not be enough when CI is under heavy load.

Suggestion: Reduce sleep times and increase the gap between delay and timeout:
```
testCases := []struct {
    // ...
}{
    {
        name:             "no timeout - TSO delay within limit",
        tsoDelayMs:       50,
        maxExecutionTime: 500,  // 450ms headroom
        expectTimeout:    false,
    },
    {
        name:             "timeout - TSO delay exceeds limit", 
        tsoDelayMs:       200,
        maxExecutionTime: 50,   // clear 150ms gap
        expectTimeout:    true,
    },
}
```

**Review by zimulala — APPROVED** [review]
