### PR TITLE
executor: fix batchPoint for partition table with duplicate rows

### LINKED ISSUE #46779: The subquery IN returns an error result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
`CREATE TABLE `in_test` (
  `id` bigint(20) unsigned NOT NULL ,
  `name` varchar(45) NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `inx_name` (`name`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin 
PARTITION BY HASH (`id`) PARTITIONS 128; `

`insert into in_test(id,name) 
values(6700402571,'张三'),(1624923463,'李四'),(5837848666,'王五'),(6542259574,'赵六');`

`select id,
       `name`
from `in_test`
where id in
      (1624923463, 1624923463, 5837848666, 5837848666, 6700402571, 6700402571, 6542259574,6542259574);`
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
`id               |estRows|actRows|task|access object                            |execution info                                                                                                                                                                                                            |operator info                                                                                                                 |memory|disk|
-----------------+-------+-------+----+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+------+----+
Batch_Point_Get_1|8.00   |4      |root|table:in_test, partition:p11,p71,p90,p118|time:2.66ms, loops:2, BatchGet:{num_rpc:4, total_time:6.66ms}, tikv_wall_time: 1.48ms, scan_detail: {total_process_keys: 4, total_process_keys_size: 256, total_keys: 4, get_snapshot_time: 217.9µs, rocksdb: {block: {}}}|handle:[1624923463 1624923463 5837848666 5837848666 6700402571 6700402571 6542259574 6542259574], keep order:false, desc:false|N/A   |N/A |`

### 3. What did you see instead (Required)
`id               |estRows|actRows|task|access object                            |execution info                                                                                                                                                                                                                                             |operator info                                                                                                                 |memory|disk|
-----------------+-------+-------+----+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+------+----+
Batch_Point_Get_1|8.00   |1      |root|table:in_test, partition:p11,p71,p90,p118|time:918.7µs, loops:2, RU:0.500977, BatchGet:{num_rpc:2, total_time:1.58ms}, tikv_wall_time: 988.5µs, scan_detail: {total_process_keys: 1, total_process_keys_size: 64, total_keys: 4, get_snapshot_time: 617.1µs, rocksdb: {block: {cache_hit_count: 25}}}|handle:[1624923463 1624923463 5837848666 5837848666 6700402571 6700402571 6542259574 6542259574], keep order:false, desc:false|N/A   |N/A |`

### 4. What is your TiDB version? (Required)
7.1.1 / 7.1.0
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #46779 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/builder.go [hunk 1]
```diff
@@ -5226,16 +5226,24 @@ func (b *executorBuilder) buildBatchPointGet(plan *plannercore.BatchPointGetPlan
 		// `SELECT a FROM t WHERE a IN (1, 1, 2, 1, 2)` should not return duplicated rows
 		handles := make([]kv.Handle, 0, len(plan.Handles))
 		dedup := kv.NewHandleMap()
+		// Used for clear paritionIDs of duplicated rows.
+		dupPartPos := 0
 		if plan.IndexInfo == nil {
-			for _, handle := range plan.Handles {
+			dupPartID := len(plan.PartitionIDs) >= len(plan.Handles)
```
Comment (Defined2014) [inline executor/builder.go:5232]: Why need check `>=` here?

Comment (Defined2014) [reply executor/builder.go:5232]: Maybe check `len(plan.PartitionIDs) == 0` is enough.

Comment (jiyfhust) [reply executor/builder.go:5232]: > Why need check `>=` here?

Just ignore it，because i'm not sure if "len(plan.PartitionIDs) > 0" is enough.

File: executor/batch_point_get_test.go [hunk 2]
```diff
@@ -370,3 +370,24 @@ func TestPointGetForTemporaryTable(t *testing.T) {
...
+	tk.MustQuery("select * from t1 where id in (1, 1, 11)").Sort().Check(testkit.Rows("1 a", "11 b"))
+	tk.MustQuery("select * from t1 where id in (1, 11, 11, 21)").Sort().Check(testkit.Rows("1 a", "11 b", "21 c"))
+
+	tk.MustExec("drop table if exists t2")
+	tk.MustExec(`CREATE TABLE t2 (id int, c varchar(128), primary key (id)) partition by range (id)(
+		partition p0 values less than (10), 
+		partition p1 values less than (20), 
+		partition p2 values less than (30));`)
+	tk.MustExec(`insert into t2 values (1, "a"), (11, "b"), (21, "c")`)
+	tk.MustQuery("select * from t2 where id in (1, 1, 11)").Sort().Check(testkit.Rows("1 a", "11 b"))
```
[the remark this answers is not in the document]
Comment (jiyfhust) [reply executor/batch_point_get_test.go:391]: @Defined2014 what is "hasPlan" mean? is it sql Hints?

[the remark this answers is not in the document]
Comment (Defined2014) [reply executor/batch_point_get_test.go:391]: Like
```
require.True(t, tk.HasPlan("xxxx", "xxx"))
```

**Review by mjonss — APPROVED** [review]
