### PR TITLE
util/chunk: fix slice out of bound panic

### LINKED ISSUE #7953: meet slice bounds out of range
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
cd util/chunk 
go test -bench .

2. What did you expect to see?
It should give me a benchmark result. 

3. What did you see instead?
```
0 allocs/op
panic: runtime error: slice bounds out of range

goroutine 167 [running]:
github.com/pingcap/tidb/util/chunk.(*Codec).encodeColumn(0xc000041f20, 0xc000232000, 0x0, 0x83c4, 0xc00010a070, 0x83c4, 0xc000041ea0, 0x10da789)
	/Users/zhexuany/repo/go/src/github.com/pingcap/tidb/util/chunk/codec.go:70 +0x488
github.com/pingcap/tidb/util/chunk.(*Codec).Encode(0xc000128f20, 0xc000041f38, 0x2000, 0xc00011e000, 0x2000)
	/Users/zhexuany/repo/go/src/github.com/pingcap/tidb/util/chunk/codec.go:45 +0xa6
github.com/pingcap/tidb/util/chunk.BenchmarkEncodeChunk(0xc00007e4e0)
	/Users/zhexuany/repo/go/src/github.com/pingcap/tidb/util/chunk/codec_test.go:99 +0x27b
testing.(*B).runN(0xc00007e4e0, 0x1)
	/usr/local/Cellar/go/1.11.1/libexec/src/testing/benchmark.go:141 +0xb2
testing.(*B).run1.func1(0xc00007e4e0)
	/usr/local/Cellar/go/1.11.1/libexec/src/testing/benchmark.go:214 +0x5a
created by testing.(*B).run1
	/usr/local/Cellar/go/1.11.1/libexec/src/testing/benchmark.go:207 +0x7d
exit status 2
FAIL	github.com/pingcap/tidb/util/chunk	49.441s
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
b22bfb55300120fd7cdd0d99a9b0315afaaed733

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve?

Issue Number: close #7953 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
* No release note

### CODE REVIEW

**Review by Reminiscent — COMMENTED** [review]
Could you please add some test cases?

**Comment by 9547** [comment]
@Reminiscent Thanks for the advice, test case was added, PTAL

**Review by Reminiscent — COMMENTED** [review]
LGTM

**Comment by 9547** [comment]
@nullnotnil PTAL

**Comment by nullnotnil** [comment]
LGTM, but sorry I'm not a reviewer :-)

**Comment by Reminiscent** [comment]
@XuHuaiyu Please help merge. Thanks!

File: util/chunk/codec.go [hunk 1]
```diff
@@ -64,7 +64,7 @@ func (c *Codec) encodeColumn(buffer []byte, col *Column) []byte {
 	}
 
 	// encode offsets.
-	if !col.isFixed() {
+	if !col.isFixed() && len(col.offsets) > 0 {
```
Comment (wshwsh12) [inline util/chunk/codec.go:67]: I think it is a bug in Benchmark code, not codec. We shouldn't add the condition to the if conditon..  otherwise the decode function MAY BE wrong... 

Of cource, if col.isFixed() is false, len(col.offsets) must be bigger than 0 !!! 
(Or any sql can trigger the bug?

The root reason is the benchmark code create Column object manually, not calling NewColumn(), so that we only update the benchmark code is ok?

Comment (9547) [reply util/chunk/codec.go]: Thanks for your advice, reverted and fix the benchmark code, PTAL.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by wjhuang2016** [comment]
@wshwsh12 PTAL

**Review by wshwsh12 — COMMENTED** [review]
LGTM
