### PR TITLE
expression: fix `reverse` function on `bit type column`

### LINKED ISSUE #49566: query gets 'runtime error: index out of range' and no error stack in the tidb log
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `tl67c6ff48` (
  `col_4_1` timestamp NULL DEFAULT NULL,
  `col_5` bit(37) NOT NULL,
  UNIQUE KEY `idx_1` (`col_5`,`col_4_1`),
  UNIQUE KEY `idx_2` (`col_4_1`,`col_5`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `tl67c6ff48` VALUES ('2006-10-20 00:00:00',x'13e677d4b1'), ('2033-05-05 00:00:00',x'05d3a46d88'), ('1977-06-24 00:00:00',x'04dba3570c'), ('2025-05-14 00:00:00',x'0ed284dfee'), ('2009-04-29 00:00:00',x'12657141bf'), ('2002-05-12 00:00:00',x'101f239415'), ('1983-04-25 00:00:00',x'1ce8daeaa5'), ('2001-05-14 00:00:00',x'1363f05cd5'), ('2000-07-19 00:00:00',x'0d81cc3a76'), ('1981-08-10 00:00:00',x'0dffb7b521'), ('1970-07-23 00:00:00',x'009094e78f'), ('2007-04-07 00:00:00',x'1bb8e87620'), ('1973-02-26 00:00:00',x'175ecaca68'), ('2022-04-19 00:00:00',x'1af1a92543'), ('2027-09-20 00:00:00',x'16ae61d000'), ('2016-04-26 00:00:00',x'14a5e285e5'), ('2025-04-14 00:00:00',x'0765e5ab35'), ('1980-01-05 00:00:00',x'164f0cb832'), ('1999-10-03 00:00:00',x'0647364cd6'), ('2018-12-13 00:00:00',x'14f7dbc182'), ('2025-05-06 00:00:00',x'165ce4e544'), ('2003-06-07 00:00:00',x'0a55af03c4'), ('2012-05-28 00:00:00',x'0f3e47d446'), ('1996-08-20 00:00:00',x'1dda39bfaa');

select reverse(col_5 ) as r1  from tl67c6ff48  order by r1;
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
``` SQL
mysql> select reverse(col_5 ) as r1  from tl67c6ff48  order by r1;
ERROR 1105 (HY000): runtime error: index out of range [5] with length 5
```

Note: there is no error stack in the tidb log, so I think it's a new bug.
### 4. What is your TiDB version? (Required)
nightly-a7260ff598ce0e7c0a77367e84ec265f91b8073e

### LINKED ISSUE #50850: query gets 'encoding failed' using distinct and elt function
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `tl4fd484a9` (
  `col_8` double NOT NULL DEFAULT '8101.804333035654',
  `col_9` bigint(20) unsigned DEFAULT NULL,
  `col_10` bit(8) DEFAULT NULL,
  `col_11` bit(42) DEFAULT NULL,
  UNIQUE KEY `idx_4` (`col_9`),
  UNIQUE KEY `idx_5` (`col_9`),
  UNIQUE KEY `idx_6` (`col_9`,`col_10`,`col_8`),
  UNIQUE KEY `idx_7` (`col_9`,`col_8`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
PARTITION BY HASH (`col_9`) PARTITIONS 2;

INSERT INTO `tl4fd484a9` VALUES (23.007995724948362,9223372036854775808,x'd5',x'036bda736b9f'), (2591.3122474206766,5752943349156553245,NULL,x'02b77969361c'), (4479.317291827713,15055294211639017111,x'aa',x'01eee6f9a4a3'), (7628.938897170623,7496567757002745451,x'eb',x'0287ad3ecd13'), (8347.197576995819,6203659976161826151,x'18',x'01d6475a8df2'), (8710.54054998306,8514535559911610148,x'e2',x'03f899c130b2'), (1195.077740002609,3436186226464611422,x'50',x'0093ab260f48'), (1013.7500694146422,7471092280998844033,x'dd',x'03939af0ec85'), (5521.611017775993,16394145724846312682,x'61',x'01c06f356d0a'), (8587.461307265945,1885935207250807462,x'60',x'035a03c4dff2'), (7650.576352691503,14483491971408231742,x'91',x'02c6eaea03a1'), (2851.908224583381,15373714602380758326,NULL,x'00b8a992625f'), (5204.233883775764,12245754788232558702,x'8c',x'005b42a9761e'), (711.5713246022093,9223372036854775807,x'15',x'03ce7c19cc28'), (6700.8257413585525,11960899368204480686,x'5a',x'01a07ebf627f'), (3715.8911161876927,16717915239921191114,x'19',x'0183db6da03f'), (5588.550656466107,3324080768693532255,x'69',x'029bfa03f27e'), (6736.377121180751,4102219363823857377,x'34',x'02389972a4bc'), (5010.654821363877,1,x'01',x'012d8efdb99d'), (2555.2202292511456,NULL,x'27',x'02a09857f11c'), (6513.333951893525,7297996079516535344,x'ff',x'00123dbb5766'), (7211.133912898516,16059815461817714863,x'88',x'000000000000'), (3223.450063930532,10556257816865671061,x'76',x'035575eb3736'), (5934.213444452291,3506157312092400137,x'2f',x'0099bb76950a'), (5613.036187642952,13165727662517512195,x'01',x'01ffb1103861'), (161.42937173636415,NULL,x'3f',x'032eedd972eb'), (8632.659024782468,16757755969895857419,x'5d',NULL), (7047.649466854864,14821390344080511959,x'a6',x'0012a171b473'), (7442.306955199656,12094326225722438418,x'12',x'000000000000'), (1795.1199576186712,1328447598647750078,x'2d',x'0325b495eba1'), (7467.011217133958,9561095661261955906,x'01',x'011834544fb1'), (2972.7118048537704,18446744073709551615,x'b1',x'01977242631c'), (3161.6599685270917,7911534160713813860,x'37',x'03782feb0295'), (9546.629394674586,17028252544791959939,x'ff',x'01d73fa1f0fa'), (2306.9705216860984,1630137914052885313,x'31',x'005d59426708'), (7601.530447792593,6986807871336145185,x'd5',x'016998085258'), (7058.842877388801,8570807740729504101,x'a5',x'0112cc74569e'), (615.6011553350702,11897798906906134285,x'34',x'03d135a573c2'), (3801.6115898094317,11678651343133193774,x'3a',x'009f3c65f2c5'), (6779.239615471537,2484649041714012147,x'65',x'03b9cba6820d');

SELECT DISTINCT ELT(2, `tl4fd484a9`.`col_8`, `tl4fd484a9`.`col_10`) AS `r0` FROM `tl4fd484a9`;
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
``` SQL
mysql> SELECT DISTINCT ELT(2, `tl4fd484a9`.`col_8`, `tl4fd484a9`.`col_10`) AS `r0` FROM `tl4fd484a9`;
ERROR 1105 (HY000): encoding failed
```
### 4. What is your TiDB version? (Required)
4e416993cc65b4da6786a7ce859b2ab99e5bba15

### LINKED ISSUE #50855: query gets the 'invalid input value' error using distinct
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `td880ed5c` (
  `col_64` int(10) unsigned NOT NULL DEFAULT '1786987428',
  `col_65` date DEFAULT '2000-06-23',
  `col_66` bit(34) NOT NULL,
  `col_67` bit(45) NOT NULL DEFAULT b'110110100011111000110011111010101111001111111',
  `col_68` timestamp NOT NULL DEFAULT '1978-09-10 00:00:00',
  `col_69` datetime NOT NULL,
  PRIMARY KEY (`col_64`,`col_66`,`col_68`) /*T![clustered_index] NONCLUSTERED */,
  UNIQUE KEY `idx_20` (`col_64`,`col_68`,`col_67`),
  UNIQUE KEY `idx_21` (`col_64`,`col_67`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
PARTITION BY HASH (`col_64`) PARTITIONS 5;

INSERT INTO `td880ed5c` VALUES (578629008,'2004-02-25',x'01ca56bae5',x'1181e3f5eb87','2031-09-27 00:00:00','2003-08-10 00:00:00'), (3839858149,'2004-02-25',x'01ca56bae5',x'1181e3f5eb87','2004-05-19 00:00:00','2003-08-10 00:00:00'), (986835820,'2004-02-25',x'01ca56bae5',x'1181e3f5eb87','1980-07-02 00:00:00','2003-08-10 00:00:00'), (261076256,'2004-02-25',x'01ca56bae5',x'1181e3f5eb87','2022-03-19 00:00:00','2003-08-10 00:00:00'), (2919688946,'2005-09-17',x'01ca56bae5',x'1181e3f5eb87','2004-05-19 00:00:00','2003-08-10 00:00:00'), (1384945489,'1977-09-16',x'01ca56bae5',x'1181e3f5eb87','1975-02-09 00:00:00','2003-08-10 00:00:00'), (337709001,'1987-12-23',x'01ca56bae5',x'1181e3f5eb87','1970-01-28 00:00:00','2003-08-10 00:00:00'), (210024554,'2024-02-11',x'01ca56bae5',x'1181e3f5eb87','1971-12-08 00:00:00','2003-08-10 00:00:00'), (1037545552,'2021-01-05',x'01ca56bae5',x'1181e3f5eb87','2031-09-26 00:00:00','2003-08-10 00:00:00'), (3528521392,'2035-08-14',x'01ca56bae5',x'1181e3f5eb87','2004-05-19 00:00:00','2003-08-10 00:00:00'), (380854997,'1989-07-27',x'0317b6a819',x'108998d7b78e','2010-04-05 00:00:00','1976-02-03 00:00:00'), (2418657738,'1989-11-14',x'0096728efe',x'000000000000','2004-05-19 00:00:00','1979-05-28 00:00:00'), (3772008620,'1986-06-17',x'0118dad9b2',x'09b0e5368c40','2004-05-19 00:00:00','1988-07-14 00:00:00'), (23805426,'2009-06-16',x'007bdbe821',x'1d7355948576','2029-03-07 00:00:00','1991-04-19 00:00:00'), (3316670611,'2004-12-09',x'01a968eba1',x'1bb0271f09ae','2004-05-19 00:00:00','2031-12-19 00:00:00'), (970863828,'1986-11-23',x'02f16b6322',x'0381fa7829f3','2000-01-28 00:00:00','2011-05-20 00:00:00'), (684334029,'1972-06-29',x'0335f84c7d',x'000000000000','1996-11-28 00:00:00','2001-12-17 00:00:00'), (2,'1989-02-18',x'01a54eac88',x'1e753d9e5a68','2025-11-30 00:00:00','2018-05-28 00:00:00'), (902388330,'2013-06-02',x'03cdd6d237',x'0ea94a15f067','2009-03-18 00:00:00','2017-05-03 00:00:00'), (2011313927,'1997-10-27',x'03cb5eecc7',x'034d097c0c27','2004-05-19 00:00:00','1976-10-01 00:00:00'), (2134534959,'2031-01-17',x'01705e5355',x'12db99b7911d','2004-05-19 00:00:00','1974-11-02 00:00:00'), (1900645116,'2009-06-22',x'021ac27c7a',x'09c47d7de115','2004-05-19 00:00:00','2031-11-11 00:00:00'), (2312394105,'2036-04-06',x'02fdce1dc7',x'000000000000','2004-05-19 00:00:00','2028-11-15 00:00:00'), (3627903068,'1988-11-28',x'0316769a86',x'000000000000','2004-05-19 00:00:00','2001-09-18 00:00:00'), (4068944662,'1997-05-27',x'00b7b9ba8b',x'09a1441d083c','2004-05-19 00:00:00','2001-11-05 00:00:00'), (3323167528,'2022-10-01',x'00d1dc9a8f',x'0b73575ff062','2004-05-19 00:00:00','2031-10-27 00:00:00'), (1700850903,'1979-08-19',x'00ceb49159',x'177aad71c84f','1990-12-26 00:00:00','2002-04-05 00:00:00'), (2147483648,'1982-05-21',x'03f4be40c6',x'000000000000','2004-05-19 00:00:00','2011-01-05 00:00:00'), (2831323145,'2021-06-08',x'01b55f579c',x'0b245632380e','2004-05-19 00:00:00','1974-05-05 00:00:00'), (3007143316,'2012-07-13',x'034f4c3b23',x'1d8d721fdd0f','2004-05-19 00:00:00','1973-11-23 00:00:00'), (2147483648,'1987-01-26',x'0244d051e7',x'1e58767a9954','2004-05-19 00:00:00','2001-05-31 00:00:00'), (24564169,'1988-03-24',x'00c007aaf2',x'0e7a2f96f815','2006-03-05 00:00:00','2000-05-16 00:00:00'), (2160743184,'2026-05-12',x'02ac99da30',x'1ceb1b3996fe','2004-05-19 00:00:00','2029-02-19 00:00:00'), (809621108,'2024-09-30',x'026acb8a28',x'058b613b6088','2031-10-19 00:00:00','1974-12-15 00:00:00'), (2781746953,NULL,x'007603277c',x'116de4426b1e','2004-05-19 00:00:00','1996-06-26 00:00:00'), (3992045312,'2031-05-01',x'0011eeba62',x'1b45c7ea7e88','2004-05-19 00:00:00','2009-04-14 00:00:00'), (777718768,'2019-12-31',x'01d8c8a81d',x'0583ec4e17df','1983-08-27 00:00:00','1970-04-15 00:00:00'), (3411225539,'2029-09-14',x'022ff6f257',x'199e3df35678','1976-10-09 00:00:00','2031-05-07 00:00:00');

SELECT  DISTINCT `td880ed5c`.`col_67` AS `r0`,`td880ed5c`.`col_65` AS `r1`,REVERSE(`td880ed5c`.`col_67`) AS `r2`,`td880ed5c`.`col_67` AS `r3`,`td880ed5c`.`col_67` AS `r4` FROM `td880ed5c` WHERE NOT (`td880ed5c`.`col_69` IN ('1998-01-19','1978-05-29','2035-11-14','2004-04-20'));
```

### 2. What did you expect to see? (Required)

No error
### 3. What did you see instead (Required)

``` SQL
mysql> SELECT  DISTINCT `td880ed5c`.`col_67` AS `r0`,`td880ed5c`.`col_65` AS `r1`,REVERSE(`td880ed5c`.`col_67`) AS `r2`,`td880ed5c`.`col_67` AS `r3`,`td880ed5c`.`col_67` AS `r4` FROM `td880ed5c` WHERE NOT (`td880ed5c`.`col_69` IN ('1998-01-19','1978-05-29','2035-11-14','2004-04-20'));
ERROR 1105 (HY000): invalid input value: Utf8Error { valid_up_to: 1, error_len: Some(1) }
```
### 4. What is your TiDB version? (Required)
4e416993cc65b4da6786a7ce859b2ab99e5bba15

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #49566,  close #50850, close #50855

Problem Summary:

### What changed and how does it work?

1. Call [Coercibility](https://github.com/pingcap/tidb/blob/9b0fd9ea299266da70456f6e6077ed14bd191cfc/pkg/expression/collation.go#L373C16-L373C16)
2. Above will set default [Coercibility](https://github.com/pingcap/tidb/blob/9b0fd9ea299266da70456f6e6077ed14bd191cfc/pkg/expression/column.go#L710C2-L710C2)
3. Check `CoercibilityNumeric `  and reset [Collation ](https://github.com/pingcap/tidb/blob/9b0fd9ea299266da70456f6e6077ed14bd191cfc/pkg/expression/collation.go#L313C51-L313C51)
4. Then [IsBinaryStr](https://github.com/pingcap/tidb/blob/9b0fd9ea299266da70456f6e6077ed14bd191cfc/pkg/expression/builtin_string.go#L771) will return false, error occurs.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by jiyfhust** [comment]
Could you take a look at this pr? Thx. @YangKeao @lcwangchao

File: pkg/expression/builtin_string.go [hunk 1]
```diff
@@ -768,7 +772,7 @@ func (c *reverseFunctionClass) getFunction(ctx sessionctx.Context, args []Expres
 	bf.tp.SetFlen(args[0].GetType().GetFlen())
 	addBinFlag(bf.tp)
 	var sig builtinFunc
-	if types.IsBinaryStr(argTp) {
+	if types.IsBinaryStr(argTp) || bitColumnArgs {
```
Comment (YangKeao) [inline pkg/expression/builtin_string.go:775]: What about replacing `bitColumnArgs` with `types.IsTypeBit(argTp)` here?

Comment (YangKeao) [reply pkg/expression/builtin_string.go:775]: The `bit` type can appear not only in column, but also through expression right? For example, `cast(xxx as bit(37))`. We should also cover these cases in this PR, so using the `argTp` sounds simpler.

Comment (jiyfhust) [reply pkg/expression/builtin_string.go]: updated. https://github.com/pingcap/tidb/pull/50146/commits/62c0cc332fe6ce34cceb1cb6327a25fb567897bd

File: pkg/expression/builtin_string.go [hunk 2]
```diff
@@ -759,6 +759,7 @@ func (c *reverseFunctionClass) getFunction(ctx sessionctx.Context, args []Expres
 	if err := c.verifyArgs(args); err != nil {
 		return nil, err
 	}
+	bitTypeFlag := types.IsTypeBit(args[0].GetType())
 	bf, err := newBaseBuiltinFuncWithTp(ctx, c.funcName, args, types.ETString, types.ETString)
```
Comment (YangKeao) [inline pkg/expression/builtin_string.go:763]: I noticed that the returned collation should be `binary`. You can check with `--column-type-info` argument in `mysql` cli.

Run the SQLs in the issue, we'll get:

MySQL Result:

```
mysql> select reverse(col_5 ) as r1  from tl67c6ff48  order by r1;
Field   1:  `r1`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  binary (63)
Length:     37
Max_length: 5
Decimals:   31
Flags:      BINARY 


+--------------+
| r1           |
+--------------+
| 0x00D061AE16 |
| 0x0C57A3DB04 |
| 0x1594231F10 |
| 0x2076E8B81B |
| 0x21B5B7FF0D |
| 0x32B80C4F16 |
| 0x35ABE56507 |
| 0x4325A9F11A |
| 0x44E5E45C16 |
| 0x46D4473E0F |
| 0x68CACA5E17 |
| 0x763ACC810D |
| 0x82C1DBF714 |
| 0x886DA4D305 |
| 0x8FE7949000 |
| 0xA5EADAE81C |
| 0xAABF39DA1D |
| 0xB1D477E613 |
| 0xBF41716512 |
| 0xC403AF550A |
| 0xD55CF06313 |
| 0xD64C364706 |
| 0xE585E2A514 |
| 0xEEDF84D20E |
+--------------+
24 rows in set (0.00 sec)
```

Your PR result:

```
mysql> select reverse(col_5 ) as r1  from tl67c6ff48  order by r1;
Field   1:  `r1`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
Length:     20
Max_length: 5
Decimals:   31
Flags:      


+-------+
| r1    |
+-------+
|  a   |
| 
  W   |
| #  |
|  v |
    |
| 2
   O  |
| 5e   |
| U
   |
| C%   |
| D\   |
| FG>  |
| h^   |
| m    |
|      |
  |:́
|      |
| 9    |
| 甐    |
| w    |
| \c   |
| L6G  |
| Aqe  |
|      |
| ߄    |
+-------+
24 rows in set (0.08 sec)
```

Maybe a better way to solve this issue is to use `binary` collation, then the issue is automatically solved (and we don't need to handle `bitTypeFlag` specially, as it'll be matched by `types.IsBinaryStr`. This issue not only affects `reverse`, it also affects other functions like `concat`: `select concat(col_5, '1') from tl67c6ff48;` will have `binary` collation on MySQL, and will be `utf8mb4_bin` on TiDB.

One fix of this problem is to set collation to `binary` in `inferCollation` like `JSON` type (which sets collation to `utf8mb4_bin`. For example:

```
	if types.IsTypeBit(exprs[0].GetType()) {
		dstCharset, dstCollation = charset.CharsetBin, charset.CollationBin
	}
...
...
		if types.IsTypeBit(arg.GetType()) {
			argCharset, argCharset = charset.CharsetBin, charset.CollationBin
		}
```

`deriveCoercibilityForColumn` also needs to be modified. It should return `CoercibilityImplicit` when the type is `BIT`. You can test/check this behavior with `select COERCIBILITY(...)`. After these two modification, the `reverse` and `concat` should work fine.

Comment (jiyfhust) [reply pkg/expression/builtin_string.go:763]: > One fix of this problem is to set collation to `binary` in `inferCollation` like `JSON` type (which sets collation to `utf8mb4_bin`. For example:
> 
> ```
> 	if types.IsTypeBit(exprs[0].GetType()) {
> 		dstCharset, dstCollation = charset.CharsetBin, charset.CollationBin
> 	}
> ...
> ...
> 		if types.IsTypeBit(arg.GetType()) {
> 			argCharset, argCharset = charset.CharsetBin, charset.CollationBin
> 		}
> ```
> 
> `deriveCoercibilityForColumn` also needs to be modified. It should return `CoercibilityImplicit` when the type is `BIT`. You can test/check this behavior with `select COERCIBILITY(...)`. After these two modification, the `reverse` and `concat` should work fine.

With this, it will make the return column type showed by `--column-type-info` compatible with mysql.

Comment (jiyfhust) [reply pkg/expression/builtin_string.go:763]: I updated as you suggestion by https://github.com/pingcap/tidb/pull/50146/commits/b166a84bbf878bff1a90d8769a370a477168ec58.

Comment (YangKeao) [reply pkg/expression/builtin_string.go:763]: > @YangKeao I tested it can't work if fixed it just as above.

You are right, the collation of the return type of `cast` function is still `utf8mb4_bin`. This PR looks good to me. Thank you 🍻 .

File: pkg/expression/collation.go [hunk 3]
```diff
@@ -384,6 +388,8 @@ func inferCollation(exprs ...Expression) *ExprCollation {
 		// see details https://github.com/pingcap/tidb/issues/31320#issuecomment-1010599311
 		if arg.GetType().EvalType() == types.ETJson {
 			argCharset, argCollation = charset.CharsetUTF8MB4, charset.CollationUTF8MB4
+		} else if types.IsTypeBit(arg.GetType()) {
+			argCharset, argCharset = charset.CharsetBin, charset.CollationBin
```
Comment (YangKeao) [inline pkg/expression/collation.go:392]: Typo: `argCharset, argCharset ` -> `argCharset, argCollation `

Comment (jiyfhust) [reply pkg/expression/collation.go]: updated.

**Review by YangKeao — APPROVED** [review]
LGTM

File: pkg/expression/builtin_string.go [hunk 4]
```diff
@@ -758,6 +758,7 @@ func (c *reverseFunctionClass) getFunction(ctx BuildContext, args []Expression)
 	if err := c.verifyArgs(args); err != nil {
 		return nil, err
 	}
+	bitTypeFlag := types.IsTypeBit(args[0].GetType())
```
Comment (YangKeao) [inline pkg/expression/builtin_string.go:761]: Sorry. I have another proposal 🤦 . It turns out that the type implicit conversion is really a chaos. We have more issues for `BIT`, see: https://github.com/pingcap/tidb/issues/50855 and https://github.com/pingcap/tidb/issues/50850 .

The problem is that: implicitly casting a `BIT` value to string should give `binary` charset/collation, and explicitly selecting `cast(bit_col as char)` will produce a normal string with default collation/charset. Given these information, I proposed to modify `WrapWithCastAsString` by adding the following lines:

```go

	// Implicitly casting BIT to string will make it a binary
	if exprTp.GetType() == mysql.TypeBit {
		tp.SetCharset(charset.CharsetBin)
		tp.SetCollate(charset.CollationBin)
	}
```

With this modification, the `bitTypeFlag` here is not needed and it may also fix https://github.com/pingcap/tidb/issues/50855 and https://github.com/pingcap/tidb/issues/50850 🤔 (I'm not sure). If so, please add some tests for them.

Also cc @zanmato1984 PTAL

Comment (jiyfhust) [reply pkg/expression/builtin_string.go:761]: Get, i will test it as you suggestions.

Comment (jiyfhust) [reply pkg/expression/builtin_string.go]: > here is not needed and it may also fix #50855 and #50850 🤔 (I'm not sure). If so, please add some tests for them.

@YangKeao The results is as you expected, I tested it can solve the other issure too.

File: tests/integrationtest/t/expression/builtin.test [hunk 5]
```diff
@@ -1560,3 +1560,17 @@ SELECT RELEASE_LOCK('test_lock1');
 SELECT RELEASE_LOCK('test_lock3');
 SELECT RELEASE_ALL_LOCKS();
 
+# Issue #49566
+drop table if exists t;
+create table t (col bit(37) NOT NULL);
+insert into t (col) values(x'05d3a46d88'), (x'04dba3570c'), (x'0ed284dfee'), (x'12657141bf');
+select hex(col), hex(reverse(col)) from t order by reverse(col);
+drop table if exists t2;
```
Comment (bb7133) [inline tests/integrationtest/t/expression/builtin.test:1568]: Could you add explicit comment for #50850 & #50855? Thanks.

Comment (jiyfhust) [reply tests/integrationtest/t/expression/builtin.test:1569]: Done.

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Comment by zanmato1984** [comment]
@jiyfhust Thanks for your contribution!
