### PR TITLE
planner: fix wrong column calculation in ColumnPruning for LogicalUnionAll

### LINKED ISSUE #10341: Unexpected ambiguous error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table DocumentUnion (
    name varchar(255) not null,
    parent_name varchar(255),
    xsize integer,
    primary key (name)
) engine=InnoDB;

create table FolderUnion (
    name varchar(255) not null,
    parent_name varchar(255),
    primary key (name)
) engine=InnoDB;

create table SymbolicLinkUnion (
   name varchar(255) not null,
    parent_name varchar(255),
    target_name varchar(255) not null,
    primary key (name)
) engine=InnoDB;

SELECT this_.name           AS name1_1_3_, 
       this_.parent_name    AS parent_n2_1_3_, 
       this_.xsize          AS xsize1_0_3_, 
       this_.target_name    AS target_n1_3_3_, 
       this_.clazz_         AS clazz_3_, 
       folder2_.name        AS name1_1_0_, 
       folder2_.parent_name AS parent_n2_1_0_, 
       folder3_.name        AS name1_1_1_, 
       folder3_.parent_name AS parent_n2_1_1_, 
       file4_.name          AS name1_1_2_, 
       file4_.parent_name   AS parent_n2_1_2_, 
       file4_.xsize         AS xsize1_0_2_, 
       file4_.target_name   AS target_n1_3_2_, 
       file4_.clazz_        AS clazz_2_ 
FROM   (SELECT name, 
               parent_name, 
               NULL AS xsize, 
               NULL AS target_name, 
               1    AS clazz_ 
        FROM   folderunion 
        UNION ALL 
        SELECT name, 
               parent_name, 
               xsize, 
               NULL AS target_name, 
               2    AS clazz_ 
        FROM   documentunion 
        UNION ALL 
        SELECT name, 
               parent_name, 
               NULL AS xsize, 
               target_name, 
               3    AS clazz_ 
        FROM   symboliclinkunion) this_ 
       LEFT OUTER JOIN folderunion folder2_ 
                    ON this_.parent_name = folder2_.name 
       LEFT OUTER JOIN folderunion folder3_ 
                    ON folder2_.parent_name = folder3_.name 
       LEFT OUTER JOIN (SELECT name, 
                               parent_name, 
                               NULL AS xsize, 
                               NULL AS target_name, 
                               1    AS clazz_ 
                        FROM   folderunion 
                        UNION ALL 
                        SELECT name, 
                               parent_name, 
                               xsize, 
                               NULL AS target_name, 
                               2    AS clazz_ 
                        FROM   documentunion 
                        UNION ALL 
                        SELECT name, 
                               parent_name, 
                               NULL AS xsize, 
                               target_name, 
                               3    AS clazz_ 
                        FROM   symboliclinkunion) file4_ 
                    ON this_.target_name = file4_.name; 
```

2. What did you expect to see?

`Empty set (0.01 sec)`

3. What did you see instead?

`ERROR 1105 (HY000): Column folder2_.name is ambiguous`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v3.0.0-beta.1-167-g5f0346216
Git Commit Hash: 5f03462166c976ca2a229f00b8ae5e2c6c102fbd
Git Branch: master
UTC Build Time: 2019-05-05 04:43:36
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by erjiaqing**
### What problem does this PR solve? 

Fix #10341

### What is changed and how it works?

Wrongly used Children()[0].Schema().Columns in ColumnPruning for LogicalUnionAll.

ColumnPruning for LogicalUnionAll calculate its own Columns instead of use Childres's, which will lead to wrong column names.

For column name in LogicalUnionAll contains table name (AsName in ast), but logicalProjection does not and should not contain table name.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: planner/core/rule_column_pruning.go [hunk 1]
```diff
@@ -166,14 +166,19 @@ func (p *LogicalUnionAll) PruneColumns(parentUsedCols []*expression.Column) erro
 	if !hasBeenUsed {
 		parentUsedCols = make([]*expression.Column, len(p.schema.Columns))
 		copy(parentUsedCols, p.schema.Columns)
+	} else {
+		for i := len(used) - 1; i >= 0; i-- {
```
Comment (eurekaka) [inline planner/core/rule_column_pruning.go]: Add a comment here to inform that we do not directly use schema of children[0] because the column name may be changed?
