### PR TITLE
test: try to stablize scan test

### LINKED ISSUE #19076: scan_test.go:testScanSuite.TestScan failed
scan_test.go:testScanSuite.TestScan

```
[2020-08-07T03:26:57.316Z] ----------------------------------------------------------------------
[2020-08-07T03:26:57.316Z] FAIL: scan_test.go:65: testScanSuite.TestScan
[2020-08-07T03:26:57.316Z]
[2020-08-07T03:26:57.316Z] scan_test.go:110:
[2020-08-07T03:26:57.316Z]     check(c, scan, rowNum, false)
[2020-08-07T03:26:57.316Z] scan_test.go:69:
[2020-08-07T03:26:57.316Z]     c.Assert([]byte(k), BytesEquals, encodeKey(s.prefix, s08d("key", i)))
[2020-08-07T03:26:57.316Z] ... bytes_one []uint8 = []byte{0x73, 0x65, 0x65, 0x6b, 0x5f, 0x31, 0x35, 0x39, 0xff, 0x36, 0x37, 0x37, 0x30, 0x36, 0x37, 0x34, 0x5f, 0xff, 0x6b, 0x65, 0x79, 0x30, 0x30, 0x30, 0x30, 0x30, 0xff, 0x34, 0x32, 0x35, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfa}
[2020-08-07T03:26:57.316Z] ... bytes_two []uint8 = []byte{0x73, 0x65, 0x65, 0x6b, 0x5f, 0x31, 0x35, 0x39, 0xff, 0x36, 0x37, 0x37, 0x30, 0x36, 0x37, 0x34, 0x5f, 0xff, 0x6b, 0x65, 0x79, 0x30, 0x30, 0x30, 0x30, 0x30, 0xff, 0x33, 0x37, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfa}
[2020-08-07T03:26:57.316Z]
```

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/45604/display/redirect

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #19076 

Problem Summary:

### What is changed and how it works?

What's Changed:
Try to stabilize the scan test, this is possibly a debug try, may not solve it.

How it Works:

### Check List 

Tests 

- Unit test

Side effects

### CODE REVIEW

**Comment by cfzjywxk** [comment]
Seems scan_test case will still fail...

**Comment by cfzjywxk** [comment]
From the debug log

```
["obtained key"=74315f727365656bff5f31353937373435ff3339315f6b657930ff3030303033383600fe] 
["obtained val"=76616c7565333836] 
[      expected=74315f727365656bff5f31353937373435ff3339315f6b657930ff3030303033373900fe]
```

The expected key index is 379, but the obtained value from scan iterator is 386.

**Comment by cfzjywxk** [comment]
> /run-all-tests

Some unrelated failure...

File: store/tikv/scan_test.go [hunk 1]
```diff
@@ -40,6 +42,10 @@ func (s *testScanSuite) SetUpSuite(c *C) {
 	s.store = NewTestStore(c).(*tikvStore)
 	s.recordPrefix = tablecodec.GenTableRecordPrefix(1)
 	s.rowNums = append(s.rowNums, 1, scanBatchSize, scanBatchSize+1, scanBatchSize*3)
+	ctx := context.Background()
+	// Avoid using async commit logic.
+	ctx = context.WithValue(ctx, sessionctx.ConnID, uint64(0))
```
Comment (lysu) [inline store/tikv/scan_test.go:47]: maybe old `context.Backgroud` also cannot step into async commit logic too - -?

Comment (cfzjywxk) [reply store/tikv/scan_test.go:47]: eh...  Maybe I need another way to skip `async` logic.

**Review by coocood — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
