### PR TITLE
ddl: fix drop last visible column

### LINKED ISSUE #20315: Can drop the last column if expression index exists
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
mysql> CREATE TABLE t(x INT, KEY((1+1)));
Query OK, 0 rows affected (0.00 sec)

mysql> ALTER TABLE t DROP COLUMN x;
Query OK, 0 rows affected (0.01 sec)
```

### 2. What did you expect to see? (Required)
``` sql
mysql> CREATE TABLE t(x INT, KEY((1+1)));
Query OK, 0 rows affected (0.01 sec)

mysql> ALTER TABLE t DROP COLUMN x;
ERROR 1113 (42000): A table must have at least 1 column
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve?

Issue Number: close #20315 

Problem Summary:

### What is changed and how it works?

What's Changed:
return error when the last visible column is dropped

How it Works:
check visible columns count

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix drop last visible column

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -4904,6 +4904,15 @@ func isDroppableColumn(tblInfo *model.TableInfo, colName model.CIStr) error {
 		return ErrCantRemoveAllFields.GenWithStack("can't drop only column %s in table %s",
 			colName, tblInfo.Name)
 	}
+	visibleColumCnt := 0
+	for _, column := range tblInfo.Columns {
+		if !column.Hidden {
+			visibleColumCnt++
+		}
+	}
+	if visibleColumCnt == 1 {
```
Comment (wjhuang2016) [inline ddl/ddl_api.go:4913]: What if `alter table t drop column a, drop column b`?

Comment (b41sh) [reply ddl/ddl_api.go:4913]: drop multiple columns is not checked correctly, I will fix it.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by b41sh** [comment]
@bb7133  PTAL

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -3258,6 +3266,20 @@ func checkIsDroppableColumn(ctx sessionctx.Context, t table.Table, spec *ast.Alt
...
+	visibleColumCnt := 0
+	for _, column := range tblInfo.Columns {
+		if !column.Hidden {
+			visibleColumCnt++
+		}
+	}
+	if visibleColumCnt == columnCnt {
+		return ErrTableMustHaveColumns
+	}
+	return nil
```
Comment (xiongjiwei) [inline ddl/ddl_api.go:3280]: how about 
```go
for _, column := range tblInfo.Columns {
	if !column.Hidden {
		visibleColumCnt++
	}
    if visibleColumCnt > columnCnt  {
        reutrn nil
    }
}
return ErrTableMustHaveColumns
```

Comment (b41sh) [reply ddl/ddl_api.go]: good idea, This can reduce the number of cycles
done

**Comment by xiongjiwei** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by xhebox — APPROVED** [review]
LGTM
