### PR TITLE
planner: fix data race in the TestInlineProjection4HashJoinIssue15316

### LINKED ISSUE #37009: DATA RACE in the TestInlineProjection4HashJoinIssue15316
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Read at 0x00000a63ec7c by goroutine 9488:
  github.com/pingcap/tidb/planner/core.(*LogicalJoin).getHashJoins()
      /go/tidb/planner/core/exhaust_physical_plans.go:398 +0x206
  github.com/pingcap/tidb/planner/core.(*LogicalJoin).exhaustPhysicalPlans()
      /go/tidb/planner/core/exhaust_physical_plans.go:1834 +0x804
  github.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask()
      /go/tidb/planner/core/find_best_task.go:402 +0x5f5
  github.com/pingcap/tidb/planner/core.(*LogicalJoin).findBestTask()
      <autogenerated>:1 +0x65
  github.com/pingcap/tidb/planner/core.(*baseLogicalPlan).enumeratePhysicalPlans4Task()
      /go/tidb/planner/core/find_best_task.go:223 +0x8e9
  github.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask()
      /go/tidb/planner/core/find_best_task.go:442 +0x91e
  github.com/pingcap/tidb/planner/core.(*LogicalSort).findBestTask()
      <autogenerated>:1 +0x64
  github.com/pingcap/tidb/planner/core.(*baseLogicalPlan).enumeratePhysicalPlans4Task()
      /go/tidb/planner/core/find_best_task.go:223 +0x8e9
  github.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask()
      /go/tidb/planner/core/find_best_task.go:442 +0x91e
  github.com/pingcap/tidb/planner/core.(*LogicalProjection).findBestTask()
      <autogenerated>:1 +0x65
  github.com/pingcap/tidb/planner/core.physicalOptimize()
      /go/tidb/planner/core/optimizer.go:646 +0x488
  github.com/pingcap/tidb/planner/core.DoOptimize()
      /go/tidb/planner/core/optimizer.go:294 +0x2a4
  github.com/pingcap/tidb/planner.optimize()
      /go/tidb/planner/optimize.go:354 +0xd0c
  github.com/pingcap/tidb/planner.Optimize()
      /go/tidb/planner/optimize.go:205 +0x1016
  github.com/pingcap/tidb/executor.(*Compiler).Compile()
      /go/tidb/executor/compiler.go:80 +0x6d8
  github.com/pingcap/tidb/session.(*session).ExecuteStmt()
      /go/tidb/session/session.go:1978 +0x7d4
  github.com/pingcap/tidb/session.(*session).ExecuteInternal()
      /go/tidb/session/session.go:1512 +0x471
  github.com/pingcap/tidb/ddl.(*session).execute()
      /go/tidb/ddl/ddl.go:1643 +0x1ee
  github.com/pingcap/tidb/ddl.(*ddl).getJob()
      /go/tidb/ddl/job_table.go:98 +0x1aa
  github.com/pingcap/tidb/ddl.(*ddl).getReorgJob()
      /go/tidb/ddl/job_table.go:146 +0x69
  github.com/pingcap/tidb/ddl.(*ddl).getReorgJob-fm()
      <autogenerated>:1 +0x44
  github.com/pingcap/tidb/ddl.(*ddl).loadDDLJobAndRun()
      /go/tidb/ddl/job_table.go:204 +0x41d
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop()
      /go/tidb/ddl/job_table.go:189 +0xb05
  github.com/pingcap/tidb/ddl.(*ddl).startDispatchLoop-fm()
      <autogenerated>:1 +0x39
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      /go/tidb/util/wait_group_wrapper.go:33 +0x73
Previous write at 0x00000a63ec7c by goroutine 81:
  github.com/pingcap/tidb/executor_test.TestInlineProjection4HashJoinIssue15316.func1()
      /go/tidb/executor/join_test.go:2266 +0x29
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:476 +0x32
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47
Goroutine 9488 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      /go/tidb/util/wait_group_wrapper.go:31 +0xe4
  github.com/pingcap/tidb/ddl.(*ddl).prepareWorkers4ConcurrencyDDL()
      /go/tidb/ddl/ddl.go:624 +0x45e
  github.com/pingcap/tidb/ddl.(*ddl).Start()
      /go/tidb/ddl/ddl.go:660 +0x5f4
  github.com/pingcap/tidb/domain.(*Domain).Init()
      /go/tidb/domain/domain.go:887 +0x134c
  github.com/pingcap/tidb/session.(*domainMap).Get.func1()
      /go/tidb/session/tidb.go:85 +0x6c4
  github.com/pingcap/tidb/util.RunWithRetry()
      /go/tidb/util/misc.go:69 +0x93
  github.com/pingcap/tidb/session.(*domainMap).Get()
      /go/tidb/session/tidb.go:68 +0x258
  github.com/pingcap/tidb/session.createSessionWithOpt()
      /go/tidb/session/session.go:2838 +0x75
  github.com/pingcap/tidb/session.createSession()
      /go/tidb/session/session.go:2834 +0x84
  github.com/pingcap/tidb/session.createSessions()
      /go/tidb/session/session.go:2823 +0x6e
  github.com/pingcap/tidb/session.BootstrapSession()
      /go/tidb/session/session.go:2701 +0x317
  github.com/pingcap/tidb/testkit.bootstrap()
      /go/tidb/testkit/mockstore.go:69 +0x8c
  github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain()
      /go/tidb/testkit/mockstore.go:63 +0x10f
  github.com/pingcap/tidb/testkit.CreateMockStore()
      /go/tidb/testkit/mockstore.go:55 +0x356
  github.com/pingcap/tidb/executor_test.TestInlineProjection4HashJoinIssue15316()
      /go/tidb/executor/join_test.go:2267 +0x89
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47
Goroutine 81 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1726 +0xa84
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      /go/tidb/testkit/testmain/wrapper.go:27 +0x42
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/executor_test.TestMain()
      /go/tidb/executor/main_test.go:69 +0xad3
  main.main()
      _testmain.go:2385 +0x404
================== 
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #37009

Problem Summary:

### Check List

Tests 

- [x] Unit test

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/exhaust_physical_plans.go [hunk 1]
```diff
@@ -1327,11 +1328,12 @@ loopOtherConds:
 }
 
 // removeUselessEqAndInFunc removes the useless eq/in conditions. It's designed for the following case:
-//   t1 join t2 on t1.a=t2.a and t1.c=t2.c where t1.b > t2.b-10 and t1.b < t2.b+10 there's index(a, b, c) on t1.
```
Comment (hawkingrei) [inline planner/core/exhaust_physical_plans.go:1330]: I think it is related to go1.19's gofmt.

**Review by xhebox — APPROVED** [review]

**Review by AilinKid — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]
