### PR TITLE
expression:  error information is inconsistent with MySQL about date or time literal

### LINKED ISSUE #25610: expression: error information is inconsistent with MySQL about date or time literal
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql>  select time '2012-12-121';
mysql> select date '2012-12-121';
```

### 2. What did you expect to see? (Required)
```
mysql>  select time '2012-12-121';
ERROR 1525 (HY000): Incorrect TIME value: '2012-12-121'
mysql> select date '2012-12-121';
ERROR 1525 (HY000): Incorrect DATE value: '2012-12-121'
```
### 3. What did you see instead (Required)
```
mysql> select time '2012-12-121';
ERROR 1292 (22007): Incorrect datetime value: '2012-12-121'
mysql> select date '2012-12-121';
ERROR 1292 (22007): Incorrect datetime value: '2012-12-121'
```
### 4. What is your TiDB version? (Required)

Master branch

### PR DESCRIPTION
**Pull request by yuqi1129**
### What problem does this PR solve?

Issue Number: close #25610 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Change Error message when convert liternal string to date/time such as 
`select date 'xxx';`

How it Works:

please see to code
### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- `No release note`

### CODE REVIEW

File: expression/builtin_time.go [hunk 1]
```diff
@@ -326,7 +326,7 @@ func (c *dateLiteralFunctionClass) getFunction(ctx sessionctx.Context, args []Ex
 	}
 	str := dt.GetString()
 	if !datePattern.MatchString(str) {
-		return nil, types.ErrWrongValue.GenWithStackByArgs(types.DateTimeStr, str)
+		return nil, types.ErrWrongValue.GenWithStackByArgs(strings.ToUpper(types.DateStr), str)
```
Comment (wshwsh12) [inline expression/builtin_time.go:329]:
```suggestion
		return nil, types.ErrWrongValue.GenWithStackByArgs(types.DateStr, str)
```

Comment (wshwsh12) [reply expression/builtin_time.go:329]: I think there are two problems in this issue:
1. error information returns wrong date type
2. data type strings is typed in lowercase

For the first problem, modify the returned date type is ok.
For the second problem, I think we should modify the const strings (e.g. types.DateStr), instead of using strings.ToUpper in some places. Because there are many usage of the error const string.  But I think we shouldn't modify this, it will change many error message.

**Review by wshwsh12 — COMMENTED** [review]
Thanks for your contribution.

File: expression/builtin_time.go (hunk 1 above)
Comment (yuqi1129) [reply expression/builtin_time.go:329]: Thanks for your kind comment. You mean there is no need to pay more attention to the case inconsistency between `date` and `DATE`, and lower case is just OK temporarily.

Correct me if i'm wrong, ths

Comment (ichn-hu) [reply expression/builtin_time.go:329]: @yuqi1129 I agree with @wshwsh12 , as long as we provide enough information in the error message, there is no need to make it exact the same with MySQL.

Comment (yuqi1129) [reply expression/builtin_time.go:329]: ok, i will update the PR as you two suggested, thanks

File: expression/builtin_time.go [hunk 2]
```diff
@@ -357,10 +357,10 @@ func (b *builtinDateLiteralSig) Clone() builtinFunc {
 func (b *builtinDateLiteralSig) evalTime(row chunk.Row) (types.Time, bool, error) {
```
Comment (wshwsh12) [inline expression/builtin_time.go:357]: The error information in vecEvalTime (vectorized implementation) also need to be update.

Comment (yuqi1129) [reply expression/builtin_time.go:357]: Done

**Review by wshwsh12 — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]
