### PR TITLE
*: support user defined variable and SET clause in LOAD DATA statement

### LINKED ISSUE #16617: server: set clause in load data will not take effect and tidb does not report error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
CREATE TABLE `i3` (
  `c1` int(11) DEFAULT NULL,
  `c2` int(11) DEFAULT NULL
)

cat data 
1,100
2,100

mysql> LOAD DATA LOCAL INFILE '/data' INTO TABLE i3 FIELDS TERMINATED BY ',' ENCLOSED BY '' LINES TERMINATED BY '\n'(c1, @val) set c2=cast(@val as signed);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from i3;                                                               
+------+------+
| c1   | c2   |
+------+------+
|    1 | NULL |
|    2 | NULL |
+------+------+
2 rows in set (0.00 sec)
```

### 2. What did you expect to see?

```
mysql> select * from i3;
+------+------+
| c1   | c2   |
+------+------+
|    1 |  100 |
|    2 |  100 |
+------+------+
2 rows in set (0.00 sec)

```

### 3. What did you see instead?

```
mysql> select * from i3;                                                               
+------+------+
| c1   | c2   |
+------+------+
|    1 | NULL |
|    2 | NULL |
+------+------+
2 rows in set (0.00 sec)
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Release Version: v4.0.0-rc

### PR DESCRIPTION
**Pull request by gentcys**
According to [MySQL Manual](https://dev.mysql.com/doc/refman/8.0/en/load-data.html) `LOAD DATA` statement support user defined variable and SET cluase.
And To keep up the pace with [pingcap/parser](https://github.com/pingcap/parser) which has already got a [PR](https://github.com/pingcap/parser/pull/288) to implement it long days ago.

### What problem does this PR solve?

Issue Number: close #16617, #11941 

Problem Summary: User defined variables and `SET` clause didn't work well in `LOAD DATA` statement.

### What is changed and how it works?

What's Changed: 
Inside `executor/load_data.go` add a new struct `FieldMapping` consists table column or user defined variable.

How it Works:
>  By default, when no column list is provided at the end of the `LOAD DATA` statement, input lines are expected to contain a field for each table column. If you want to load only some of a table's columns, specify a column list.
[MySQL Manual](https://dev.mysql.com/doc/refman/8.0/en/load-data.html)

### Check List 

Tests 

- Integration test

### Release note 

- Support mixed specification of table column and user variable in `LOAD DATA` statement.
- `SET` clause support input field preprocessing in `LOAD DATA` statement.

### CODE REVIEW

File: server/server_test.go [hunk 1]
```diff
@@ -838,6 +838,144 @@ func (cli *testServerClient) runTestLoadData(c *C, server *Server) {
...
+	c.Assert(err, IsNil)
+
+	cli.runTestsOnNewDB(c, func(config *mysql.Config) {
+		config.AllowAllFiles = true
+		config.Params = map[string]string{"sql_mode": "''"}
+	}, "LoadData", func(dbt *DBTest) {
+		dbt.mustExec("drop table if exists pn")
+		dbt.mustExec("create table pn (c1 int, c2 int, c3 int)")
+		dbt.mustExec("set @@tidb_dml_batch_size = 1")
+		_, err1 := dbt.db.Exec(`load data local infile '/tmp/load_data_test.csv' into table pn FIELDS TERMINATED BY ',' (c1, @dummy)`)
```
Comment (lysu) [inline server/server_test.go:908]: @gentcys hi, please help fix CI, it seems this test paniced

```
[2020/07/28 12:05:45.934 +08:00] [ERROR] [conn.go:1109] ["process routine panicked"] [conn=10] [r={}] [stack="github.com/pingcap/tidb/server.processStream.func1\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:1111\nruntime.gopanic\n\t/home/robi/Runtime/go/src/runtime/panic.go:679\nruntime.goPanicIndex\n\t/home/robi/Runtime/go/src/runtime/panic.go:75\ngithub.com/pingcap/tidb/executor.(*InsertValues).getRow\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/executor/insert_common.go:477\ngithub.com/pingcap/tidb/executor.(*LoadDataInfo).colsToRow\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/executor/load_data.go:596\ngithub.com/pingcap/tidb/executor.(*LoadDataInfo).InsertData\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/executor/load_data.go:516\ngithub.com/pingcap/tidb/server.insertDataWithCommit\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:1083\ngithub.com/pingcap/tidb/server.processStream\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:1144"]
```

you also can reproduce it in local machine by running those commands in shell:

1. `make failpoint-enable`
2. `go test ./server --check.f=TestLoadData`

Comment (lysu) [inline server/server_test.go:908]: @gentcys hi, please help fix CI, it seems this test paniced

```
[2020/07/28 12:05:45.934 +08:00] [ERROR] [conn.go:1109] ["process routine panicked"] [conn=10] [r={}] [stack="github.com/pingcap/tidb/server.processStream.func1\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:1111\nruntime.gopanic\n\t/home/robi/Runtime/go/src/runtime/panic.go:679\nruntime.goPanicIndex\n\t/home/robi/Runtime/go/src/runtime/panic.go:75\ngithub.com/pingcap/tidb/executor.(*InsertValues).getRow\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/executor/insert_common.go:477\ngithub.com/pingcap/tidb/executor.(*LoadDataInfo).colsToRow\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/executor/load_data.go:596\ngithub.com/pingcap/tidb/executor.(*LoadDataInfo).InsertData\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/executor/load_data.go:516\ngithub.com/pingcap/tidb/server.insertDataWithCommit\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:1083\ngithub.com/pingcap/tidb/server.processStream\n\t/home/robi/Code/go/src/github.com/pingcap/tidb/server/conn.go:1144"]
```

you also can reproduce it in local machine by running those commands in shell:

1. `make failpoint-enable`
2. `go test ./server --check.f=TestLoadData`

thanks~

Comment (gentcys) [reply server/server_test.go:908]: @lysu i've pushed a new commit to fix it.

File: server/server_test.go [hunk 2]
```diff
@@ -838,6 +838,144 @@ func (cli *testServerClient) runTestLoadData(c *C, server *Server) {
...
+	c.Assert(err, IsNil)
+
+	cli.runTestsOnNewDB(c, func(config *mysql.Config) {
+		config.AllowAllFiles = true
+		config.Params = map[string]string{"sql_mode": "''"}
+	}, "LoadData", func(dbt *DBTest) {
+		dbt.mustExec("drop table if exists pn")
+		dbt.mustExec("create table pn (c1 int, c2 int, c3 int)")
+		dbt.mustExec("set @@tidb_dml_batch_size = 1")
+		_, err1 := dbt.db.Exec(`load data local infile '/tmp/load_data_test.csv' into table pn FIELDS TERMINATED BY ',' (c1, @val1, @val2) SET c2 = CAST(@val1 AS UNSIGNED), c3 = @val2 * 100`)
```
Comment (lysu) [inline server/server_test.go:955]: this test case seems to be a failure after change SQL as

```
load data local infile '/tmp/load_data_test.csv' into table pn FIELDS TERMINATED BY ',' (c1, @val1, @val2) SET c3 = @val2 * 100, c2 = CAST(@val1 AS UNSIGNED)
```
just reorder `SET c2 = CAST(@val1 AS UNSIGNED), c3 = @val2 * 100` to `SET c3 = @val2 * 100, c2 = CAST(@val1 AS UNSIGNED)`


maybe we should take more care about  column order in `(e *LoadDataInfo) colsToRow` (include FieldMappings and ColumnAssignments)

Comment (gentcys) [reply server/server_test.go]: This problem occurs because i use real table columns instead of the specified columns as `insertColumns []*table.Column` when the length of `ColumnsAndUserVars []*ast.ColumnNameOrUserVar` is same as real table columns' length

File: executor/load_data.go [hunk 3]
```diff
@@ -461,32 +554,54 @@ func (e *LoadDataInfo) SetMessage() {
...
+			row = append(row, types.NewDatum(nil))
 			continue
 		}
+
+		var val types.Datum
 		// The field with only "\N" in it is handled as NULL in the csv file.
 		// See http://dev.mysql.com/doc/refman/5.7/en/load-data.html
 		if cols[i].maybeNull && string(cols[i].str) == "N" {
-			e.row[i].SetNull()
+			val = types.NewDatum(nil)
```
Comment (cfzjywxk) [inline executor/load_data.go:574]: Is it possible that if condition result is like `i >= len(cols) && e.FieldMappings[i].Column == nil` and using `i` to visit `cols` or `ColumnsAndUserVars` is not safe? Maybe we could do some refactor to make `colsToRow` function more clear and easy to maintain, like 
```
for each column 
    if the value exists in `csv` data
    else if the value from user variable calculation
    else use the default value or null value
return this new row
```

Comment (gentcys) [reply executor/load_data.go]: Thanks for your comment!
It's unsafe to access elements in `ColumnsAndUserVars` here, i fixed it and refactored input values preprocessing inside the for loop.

File: server/server_test.go [hunk 4]
```diff
@@ -838,6 +838,144 @@ func (cli *testServerClient) runTestLoadData(c *C, server *Server) {
...
+	c.Assert(err, IsNil)
+
+	cli.runTestsOnNewDB(c, func(config *mysql.Config) {
+		config.AllowAllFiles = true
+		config.Params = map[string]string{"sql_mode": "''"}
+	}, "LoadData", func(dbt *DBTest) {
+		dbt.mustExec("drop table if exists pn")
+		dbt.mustExec("create table pn (c1 int, c2 int, c3 int)")
+		dbt.mustExec("set @@tidb_dml_batch_size = 1")
+		_, err1 := dbt.db.Exec(`load data local infile '/tmp/load_data_test.csv' into table pn FIELDS TERMINATED BY ',' (c1, @val1, @val2) SET c3 = @val2 * 100, c2 = CAST(@val1 AS UNSIGNED)`)
```
Comment (cfzjywxk) [inline server/server_test.go:955]: Could we add a test case like using c1 both in the target columns and the `SET` clause and verify the results, thanks.

Comment (gentcys) [reply server/server_test.go:955]: It will check if there are duplicate specified columns at `executor/load_data.go#179` just like in insert statement.

**Comment by gentcys** [comment]
@cfzjywxk @lysu all tests passed on my laptop. How should i fix failed tests runs by CI?

**Comment by cfzjywxk** [comment]
> @cfzjywxk @lysu all tests passed on my laptop. How should i fix failed tests runs by CI?

Seems the failure is irrelevant with this PR, it's caused by some unstable tests, sorry for that, we'll try to fix them soon.

**Comment by cfzjywxk** [comment]
> /run-integration-common-test

```
level=fatal msg="run test [update] err: sql:SELECT * FROM t2 order by colD, colE;: failed to run query \n\"SELECT * FROM t2 order by colD, colE;\" \n around line 61, \nwe need(234):\nWarning 1062: Duplicate entry '3-4433-10005-496' for key 'PRIMARY'\nWarning 1062: Duplicate entry '3-4433-10005-497' for key 'PRIMARY'\nWarning 1062: Duplicate entry '3-4433-10005-495' for key 'PRIMARY'\nWarning 1062: Duplicate entry '3-\nbut got(234):\nSELECT * FROM t2 order by colD
```

A known test case not fixed yet. Could we squash and merge @lysu?

**Comment by lysu** [comment]
@cfzjywxk surely~
@gentcys Thanks for your contribution :smile:

**Comment by gentcys** [comment]
@lysu My pleasure.

**Comment by cfzjywxk** [comment]
> @cfzjywxk surely~
> @gentcys Thanks for your contribution 😄

@gentcys Thanks for your contribution, we have interests group for each module.
https://github.com/pingcap/tidb-map/blob/master/maps/contribution-map.md#sig---special-interest-group
You could join any interest groups for discussing and designing~

**Comment by gentcys** [comment]
@cfzjywxk Thanks!
TiDB is a great repo to learn.
I want to explore more in `Exec` module right now, maybe others in the future.
