### PR TITLE
planner: fix correlated aggregates which should be evaluated in outer query

### LINKED ISSUE #17748: P1-[4.0 bug hunting]-[Aggregate Fcuntion]-`group_concat` incompatible with MySQL
Bug Hunter issue tidb-challenge-program/bug-hunting-issue#78

---

## Bug Report

### 1. What did you do?

````
drop table if exists t1, t2;

create table t1 (a int, b int);
create table t2 (m int, n int);
insert into t1 values (2,2), (2,2), (3,3), (3,3), (3,3), (4,4);
insert into t2 values (1,11), (2,22), (3,32), (4,44), (4,44);
set @@sql_mode='TRADITIONAL';

select count(*) c, a,
 ( select group_concat(count(a)) from t2 where m = a )
 from t1 group by a;
````

### 2. What did you expect to see?
````
mysql> select count(*) c, a,
    ->  ( select group_concat(count(a)) from t2 where m = a )
    ->  from t1 group by a;
+---+------+-------------------------------------------------------+
| c | a    | ( select group_concat(count(a)) from t2 where m = a ) |
+---+------+-------------------------------------------------------+
| 2 |    2 | 2                                                     |
| 3 |    3 | 3                                                     |
| 1 |    4 | 1,1                                                   |
+---+------+-------------------------------------------------------+
3 rows in set (0.00 sec)
````

### 3. What did you see instead?

````
mysql> select count(*) c, a,
    ->  ( select group_concat(count(a)) from t2 where m = a )
    ->  from t1 group by a;
ERROR 1111 (HY000): Invalid use of group function
````

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

````
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: None
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
````

Reproducible on master branch:
````
commit 2efab88a59499ea3934c8c1eba7b695cf24b9d29 (HEAD -> master, origin/master, origin/HEAD)
Author: Wenxuan <hi@breeswish.org>
Date:   Fri May 15 21:53:32 2020 +0800
````

### LINKED ISSUE #18350: wrong result when evaluating correlated aggregate functions
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
CREATE TABLE tab(i INT); 
CREATE TABLE tab2(j INT); 

insert into tab values(1),(2),(3);
insert into tab2 values(1),(2),(3),(15);

SELECT m.i, 
       (SELECT COUNT(n.j) 
           FROM tab2 WHERE j=15) AS o 
    FROM tab m, tab2 n GROUP BY 1 order by m.i;
```

### 2. What did you expect to see? (Required)
``` sql
mysql> SELECT m.i,
         (SELECT COUNT(n.j)
             FROM tab2 WHERE j=15) AS o
      FROM tab m, tab2 n GROUP BY 1 order by m.i;
+------+------+
| i    | o    |
+------+------+
|    1 |    4 |
|    2 |    4 |
|    3 |    4 |
+------+------+
3 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
``` sql
tidb> SELECT m.i,
         (SELECT COUNT(n.j)
             FROM tab2 WHERE j=15) AS o
      FROM tab m, tab2 n GROUP BY 1 order by m.i;
+------+---+
| i    | o |
+------+---+
|    1 | 1 |
|    2 | 1 |
|    3 | 1 |
+------+---+
3 rows in set (0.00 sec)
```

### 4. Affected version (Required)

all the versions

### 5. Root Cause Analysis

TiDB does not handle correlated aggregate in subqueries correctly. I do not find any references from MySQL official manual, but [this doc](https://www.ibm.com/support/knowledgecenter/SSGU8G_12.1.0/com.ibm.sqls.doc/ids_sqs_2115.htm) can be referred.
## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 900

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #18350, close #17748 

Problem Summary:

- Some correlated aggregate (belonging to outer query) should be evaluated in outer query instead of in subquery.

``` mysql
# These aggregates should be evaluated in outer query
select (select count(a)) from t;
select (select count(n.a) from t limit 1) from t n;
select (select 1 from t where count(n.a) > 1 limit 1) from t n;
select (select 1 from t order by count(n.a) limit 1) from t n;
select (select 1 from t having count(n.a) > 1 limit 1) from t n;
select (select cnt from (select count(a) as cnt) n) from t;

# These aggregates should be evaluated in sub-query
select (select count(a + n.a) from t) from t n;
select (select count(a) from t) from t n;
```

- Cannot handle nested aggregates.

``` mysql
select (select sum(count(a))) from t; # report "invalid group function use"
```

### What is changed and how it works?

What's Changed:

- Add a procedure `resolveCorrelatedAggregates` before `buildAggregation` to collect correlated aggregates from sub-queries.
- Add cache for `ResultSetNode` to avoid rebuilding plans.
- Add `correlatedAggMap` for sub-queries to build correct plans.

How it Works:

1. For example, we have

``` mysql
create table t (a int, b int);
```

2. Start from query:

``` mysql
select (select count(n.a) from t limit 1) from t n;
```

3. Inside `b.resolveCorrelatedAggregates`, `count(n.a)` will be recognized as correlated aggregate since column `n.a` is from outer schema (from table `n` instead of `t`). So `count(n.a)` is collected and returned to outer `buildSelect`, now the query is like:

``` mysql
select (select count(n.a) from t limit 1), count(n.a) as `sel_subq_agg_1` from t n;
```

4. Inside `b.buildAggregation`, a correlated column for `sel_subq_agg_1` will be created and added to `b.correlatedAggMap`. Then `b.buildProjection` will build plan for sub-query `(select count(n.a) from t) limit 1`.

5. The sub-query will recognize `count(n.a)` as correlated aggregate and skip it the process of building aggregate plan. Then inside `b.buildProjection` of the sub-query, `count(n.a)` will be rewritten as a correlated column to `sel_subq_agg_1`, now the query is like:

``` mysql
select (select CorrelatedColumn{`sel_subq_agg_1`} from t limit 1), count(n.a) as `sel_subq_agg_1` from t n;
```

6. Finally we get the correct query plan.

### Related changes

- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- Fix correlated aggregates which should be evaluated in outer query instead of in subqueries.
- Support nested aggregate in subqueries (correlated aggregates inside normal aggregate).

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -1993,6 +2046,31 @@ func (b *PlanBuilder) extractAggFuncs(fields []*ast.SelectField) ([]*ast.Aggrega
 	return aggList, totalAggMapper
 }
 
+func (b *PlanBuilder) splitOuterAggFuncs(ctx context.Context, p LogicalPlan, aggFuncs []*ast.AggregateFuncExpr) (
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:2049]: All the places that call it don't need the first return value. Could we remove it?

File: planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -2038,6 +2116,180 @@ func (b *PlanBuilder) resolveWindowFunction(sel *ast.SelectStmt, p LogicalPlan)
...
+	// correlatedAggFuncs stores aggregate functions which belong to outer query
+	correlatedAggFuncs []*ast.AggregateFuncExpr
+}
+
+// Enter implements Visitor interface.
+func (r *correlatedAggregateResolver) Enter(n ast.Node) (ast.Node, bool) {
+	switch v := n.(type) {
+	case *ast.SelectStmt:
+		if r.outerPlan != nil {
+			outerSchema := r.outerPlan.Schema().Clone()
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:2136]: Why clone here? It should only be used for finding column?

File: planner/core/util.go [hunk 3]
```diff
@@ -30,7 +30,8 @@ import (
 // AggregateFuncExtractor visits Expr tree.
 // It converts ColunmNameExpr to AggregateFuncExpr and collects AggregateFuncExpr.
```
Comment (winoros) [inline planner/core/util.go:31]: Add comments about why it skips the correlated agg

File: planner/core/logical_plan_builder.go [hunk 4]
```diff
@@ -2038,6 +2116,180 @@ func (b *PlanBuilder) resolveWindowFunction(sel *ast.SelectStmt, p LogicalPlan)
...
+			r.b.outerSchemas = append(r.b.outerSchemas, outerSchema)
+			r.b.outerNames = append(r.b.outerNames, r.outerPlan.OutputNames())
+		}
+		r.err = r.resolveSelect(v)
+		return n, true
+	}
+	return n, false
+}
+
+func (r *correlatedAggregateResolver) resolveSelect(sel *ast.SelectStmt) (err error) {
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:2146]: Write some comments for this large method
And since we need to collect them before building the real plan. So we visit the stmt here first?

File: planner/core/logical_plan_builder.go [hunk 5]
```diff
@@ -2038,6 +2116,180 @@ func (b *PlanBuilder) resolveWindowFunction(sel *ast.SelectStmt, p LogicalPlan)
...
+	useCache, err := r.collectFromTableRefs(r.ctx, sel.From)
+	if err != nil {
+		return err
+	}
+	// we cannot use cache if there are correlated aggregates inside FROM clause,
+	// since the plan we are building now is not correct and need to be rebuild later.
+	p, err := r.b.buildTableRefs(r.ctx, sel.From, useCache)
```
Comment (winoros) [inline planner/core/logical_plan_builder.go:2153]: We actually can only visit the AST to know the correlated ones. But build a plan here for simplifying the logic of the codes?

Comment (dyzsr) [reply planner/core/logical_plan_builder.go:2153]: I thought it would be quite complex to extract correlated columns from AST without building plan, especially when there's subquery in the FROM clause. Do you have any suggestion on doing that?

File: planner/core/logical_plan_builder.go (hunk 4 above)
Comment (dyzsr) [reply planner/core/logical_plan_builder.go:2146]: Yes. we have to visit select stmt inside subquery first. And this method is similar to buildSelect.

**Comment by dyzsr** [comment]
PTAL @winoros

**Review by winoros — COMMENTED** [review]
lgtm

File: planner/core/logical_plan_builder.go [hunk 6]
```diff
@@ -267,6 +279,38 @@ func (b *PlanBuilder) buildAggregation(ctx context.Context, p LogicalPlan, aggFu
 	return plan4Agg, aggIndexMap, nil
 }
 
+func (b *PlanBuilder) buildTableRefsWithoutCache(ctx context.Context, from *ast.TableRefsClause) (p LogicalPlan, err error) {
```
Comment (lzmhhh123) [inline planner/core/logical_plan_builder.go:282]: WithoutCache is useless.

File: planner/core/logical_plan_builder.go [hunk 7]
```diff
@@ -2094,15 +2170,217 @@ func (b *PlanBuilder) resolveWindowFunction(sel *ast.SelectStmt, p LogicalPlan)
...
+		}
+		correlatedAggList = append(correlatedAggList, resolver.correlatedAggFuncs...)
+	}
+	correlatedAggMap := make(map[*ast.AggregateFuncExpr]int)
+	for _, aggFunc := range correlatedAggList {
+		correlatedAggMap[aggFunc] = len(sel.Fields.Fields)
+		sel.Fields.Fields = append(sel.Fields.Fields, &ast.SelectField{
+			Auxiliary: true,
+			Expr:      aggFunc,
+			AsName:    model.NewCIStr(fmt.Sprintf("sel_subq_agg_%d", len(sel.Fields.Fields))),
```
Comment (lzmhhh123) [inline planner/core/logical_plan_builder.go:2368]: Is the `AsName` consistent with MySQL?

**Review by lzmhhh123 — COMMENTED** [review]
Rest LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
