### PR TITLE
infoschema: avoid panic when updating infoschema v2 btree conflicts

### LINKED ISSUE #58712: TiDB crash for concurrently multiple writes are not allowed when lighting/br import
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

lightning/br import million tables
a tidb crash
```
[2025/01/05 07:33:09.177 +00:00] [ERROR] [misc.go:116] ["panic in the recoverable goroutine"] [label=domain] [funcInfo=loadSchemaInLoop] [r="concurrently multiple writes are not allowed"] [stack="github.com/pingcap/tidb/pkg/util.Recover\n\t/workspace/source/tidb/pkg/util/misc.go:120\nruntime.gopanic\n\t/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/runtime/panic.go:785\ngithub.com/pingcap/tidb/pkg/infoschema.btreeSet[...]\n\t/workspace/source/tidb/pkg/infoschema/infoschema_v2.go:88\ngithub.com/pingcap/tidb/pkg/infoschema.(*Data).add\n\t/workspace/source/tidb/pkg/infoschema/infoschema_v2.go:227\ngithub.com/pingcap/tidb/pkg/infoschema.(*Builder).addTable\n\t/workspace/source/tidb/pkg/infoschema/builder.go:991\ngithub.com/pingcap/tidb/pkg/infoschema.applyCreateTable\n\t/workspace/source/tidb/pkg/infoschema/builder.go:702\ngithub.com/pingcap/tidb/pkg/infoschema.(*Builder).applyTableUpdateV2\n\t/workspace/source/tidb/pkg/infoschema/infoschema_v2.go:1405\ngithub.com/pingcap/tidb/pkg/infoschema.applyTableUpdate\n\t/workspace/source/tidb/pkg/infoschema/infoschema_v2.go:1266\ngithub.com/pingcap/tidb/pkg/infoschema.applyDefaultAction\n\t/workspace/source/tidb/pkg/infoschema/builder.go:320\ngithub.com/pingcap/tidb/pkg/infoschema.(*Builder).ApplyDiff\n\t/workspace/source/tidb/pkg/infoschema/builder.go:105\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).tryLoadSchemaDiffs\n\t/workspace/source/tidb/pkg/domain/domain.go:645\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).loadInfoSchema\n\t/workspace/source/tidb/pkg/domain/domain.go:349\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).Reload\n\t/workspace/source/tidb/pkg/domain/domain.go:786\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).loadSchemaInLoop\n\t/workspace/source/tidb/pkg/domain/domain.go:1149\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).Start.func2\n\t/workspace/source/tidb/pkg/domain/domain.go:1534\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1\n\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:103"]
```
### 4. What is your TiDB version? (Required)

Release Version: v9.0.0-alpha-48-g76e0fcdfb4
Edition: Community
Git Commit Hash: 76e0fcdfb42b013c397cac4738927e28dc1ecd8c
Git Branch: HEAD
UTC Build Time: 2025-01-05 03:05:58
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #58712

Problem Summary:

### What changed and how does it work?

I check the code again.
If Reload() is thread-safe, the possible write conflict should come from `GCOldVersion()`

In this commit, I avoid the panic and add more logs for it.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No need to test
  > - [X] I checked and no code files have been changed.
  > 

This kind of case is really difficult to test, this is a *guess* at the best of my effort.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/infoschema/infoschema_v2.go [hunk 1]
```diff
@@ -77,15 +79,17 @@ type versionAndTimestamp struct {
...
-	if !succ {
-		panic("concurrently multiple writes are not allowed")
+	succ := false
+	for !succ {
+		var t *btree.BTreeG[T] = ptr.Load()
+		t2 := t.Clone()
+		t2.ReplaceOrInsert(item)
+		succ = ptr.CompareAndSwap(t, t2)
+		if !succ {
+			logutil.BgLogger().Info("infoschema v2 btree concurrently multiple writes detected, this should be rare")
```
Comment (D3Hunter) [inline pkg/infoschema/infoschema_v2.go:91]: is it frequent, maybe use SampleLogger, see SampleLoggerFactory


below too

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/infoschema/infoschema_v2.go (hunk 1 above)
Comment (tiancaiamao) [reply pkg/infoschema/infoschema_v2.go:91]: From @lilinghai 's report, the is rare. 
And the gcOldVersion() check interval is 1min, and the check not always trigger a real gcOldVersion(), and even it is triggered, it may not always trigger the concurrent write.
@D3Hunter

**Review by D3Hunter — APPROVED** [review]
