### PR TITLE
backend: ensure engine cleanup to be executed

### LINKED ISSUE #64101: add index with local sort opens a file that does not exist, and then retry keeps reporting already locked error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run workload
2、add index for one table
3、add index failed with error

{"namespace":"next-gen-tps-7968072-1-693","pod":"tc2-tidb-0","log":"2025-10-21T22:05:58.13056032+08:00 stderr F 2025/10/21 14:05:58 background error: creating object 5653992: open /tmp/tidb/tmp_ddl-4000/8501/b22cbf00-17b1-5bec-ba3f-fabb7a3e46e1/5653992.sst: no such file or directory","container":"tidb"}

4、cancel add index

### 2. What did you expect to see? (Required)
should not keeps reporting already locked error 

### 3. What did you see instead (Required)
add index with local sort opens a file that does not exist, and then retry keeps reporting already locked error

{"namespace":"next-gen-tps-7968072-1-693","filename":"/localpath/pvc-f98f710e-266d-45c8-9e6a-e4bbb8174c6b_next-gen-tps-7968072-1-693_tidb-log-tc2-tidb-1/tidb.log","log":"[task_executor.go:470] [\"run subtask failed\"] [keyspaceName=SYSTEM] [task-id=1] [task-key=keyspace_a/ddl/backfill/8501] [subtaskID=2] [step=read-index] [takeTime=4.664703ms] [error=\"lock held by current process\"] [errorVerbose=\"lock held by current process\\n(1) attached stack trace\\n  -- stack trace:\\n  \| github.com/cockroachdb/pebble/vfs.defaultFS.Lock\\n  \| \\t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/vfs/file_lock_unix.go:50\\n  \| github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).Lock\\n  \| \\t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/vfs/disk_health.go:679\\n  \| github.com/cockroachdb/pebble.LockDirectory\\n  \| \\t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/open.go:1068\\n  \| github.com/cockroachdb/pebble.Open\\n  \| \\t/root/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.4-0.20250120151818-5dd133a1e6fb/open.go:116\\n  \| github.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngineDB\\n  \| \\t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:230\\n  \| github.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngine\\n  \| \\t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:236\\n  \| github.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).OpenEngine\\n  \| \\t/workspace/source/tidb/pkg/lightning/backend/local/local.go:833\\n  \| github.com/pingcap/tidb/pkg/lightning/backend.EngineManager.OpenEngine\\n  \| \\t/workspace/source/tidb/pkg/lightning/backend/backend.go:271\\n  \| github.com/pingcap/tidb/pkg/ddl/ingest.(*litBackendCtx).Register\\n  \| \\t/workspace/source/tidb/pkg/ddl/ingest/engine_mgr.go:62\\n  \| github.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).buildLocalStorePipeline\\n  \| \\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:358\\n  \| github.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).runLocalPipeline\\n  \| \\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:160\\n  \| github.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).RunSubtask\\n  \| \\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:206\\n  \| github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask.func1\\n  \| \\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:466\\n  \| github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask\\n  \| \\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:467\\n  \| github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).Run\\n  \| \\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:344\\n  \| github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).startTaskExecutor.func2\\n  \| \\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/manager.go:345\\n  \| github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1\\n  \| \\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:181\\n  \| runtime.goexit\\n  \| \\t/usr/local/go/src/runtime/asm_amd64.s:1700\\nWraps: (2) lock held by current process\\nError types: (1) *withstack.withStack (2) *errutil.leafError\\ngithub.com/pingcap/errors.Trace\\n\\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20250523034308-74f78ae071ee/juju_adaptor.go:15\\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngineDB\\n\\t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:231\\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*engineManager).openEngine\\n\\t/workspace/source/tidb/pkg/lightning/backend/local/engine_mgr.go:236\\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).OpenEngine\\n\\t/workspace/source/tidb/pkg/lightning/backend/local/local.go:833\\ngithub.com/pingcap/tidb/pkg/lightning/backend.EngineManager.OpenEngine\\n\\t/workspace/source/tidb/pkg/lightning/backend/backend.go:271\\ngithub.com/pingcap/tidb/pkg/ddl/ingest.(*litBackendCtx).Register\\n\\t/workspace/source/tidb/pkg/ddl/ingest/engine_mgr.go:62\\ngithub.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).buildLocalStorePipeline\\n\\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:358\\ngithub.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).runLocalPipeline\\n\\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:160\\ngithub.com/pingcap/tidb/pkg/ddl.(*readIndexStepExecutor).RunSubtask\\n\\t/workspace/source/tidb/pkg/ddl/backfilling_read_index.go:206\\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask.func1\\n\\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:466\\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).runSubtask\\n\\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:467\\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*BaseTaskExecutor).Run\\n\\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/task_executor.go:344\\ngithub.com/pingcap/tidb/pkg/disttask/framework/taskexecutor.(*Manager).startTaskExecutor.func2\\n\\t/workspace/source/tidb/pkg/disttask/framework/taskexecutor/manager.go:345\\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1\\n\\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:181\\nruntime.goexit\\n\\t/usr/local/go/src/runtime/asm_amd64.s:1700\"]","pod":"tc2-tidb-1","container":"tidb","level":"INFO"}

### 4. What is your TiDB version? (Required)

Edition: Enterprise
Git Commit Hash: e4f8ba94a22af000a54686a0d06254f8f2c6b0f5
Git Branch: HEAD
UTC Build Time: 2025-10-15 12:19:55
GoVersion: go1.23.12
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Enterprise Extension Commit Hash: dc633aae52eb11b4e3549e3a7ef5b0ed14e159b1
Kernel Type: Next Generation |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.15 sec)

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #64101

Problem Summary:

### What changed and how does it work?

Move cleanup code to a defer function, to call `CleanupEngine` even if the engine fails to close.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ingest/engine.go [hunk 1]
```diff
@@ -111,9 +112,18 @@ func (ei *engineInfo) Close(cleanup bool) {
 	indexEngine := ei.openedEngine
 	closedEngine, err := indexEngine.Close(ei.ctx)
 	if err != nil {
-		logutil.Logger(ei.ctx).Error(LitErrCloseEngineErr, zap.Error(err),
-			zap.Int64("job ID", ei.jobID), zap.Int64("index ID", ei.indexID))
-		return
+		if errors.ErrorEqual(err, context.Canceled) {
+			closedEngine, err = indexEngine.Close(context.Background())
```
Comment (D3Hunter) [inline pkg/ddl/ingest/engine.go]: it calls `backend.CloseEngine` which doesn't really close the engine, it actually  stop write to this engine, so the underlying pebble db is still open, we need to use `cleanupEngine` to close the pebble db to release the lock

File: tests/realtikvtest/addindextest3/ingest_test.go [hunk 2]
```diff
@@ -505,6 +508,46 @@ func TestAddIndexAdvanceWatermarkFailed(t *testing.T) {
...
 }
 
+func TestAddIndexTempDirDataRemoved(t *testing.T) {
+	if kerneltype.IsNextGen() {
+		t.Skip("next-gen doesn't use local backend")
+	}
+	tempDir := t.TempDir()
+	config.UpdateGlobal(func(conf *config.Config) {
+		conf.TempDir = tempDir
+	})
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest3/ingest_test.go:519]: maybe revert it back, multiple case might be run in same process in serial
