### PR TITLE
planner: set an lower-bound for NDV used in out-of-range estimation for EQ conditions when the Histogram is empty | tidb-test=pr/2623

### LINKED ISSUE #64137: planner: consider empty histogram and newly emerging values in out-of-range estimation for EQ conditions more properly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

Use SQLs below to prepare data:
```
create table t (status int, key s(status));
insert into t values (1);
insert into t values (2);
insert into t values (null);
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
insert into t select * from t;
-- restart TiDB to flush stats delta
analyze table t;

insert into t select * from t limit 30000;
-- restart TiDB to flush stats delta
```

Then use SQLs below to reproduce this issue:
```
explain analyze select * from t where status=999;
+------------------------+----------+---------+-----------+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| id                     | estRows  | actRows | task      | access object            | execution info                                                                                                                                                                                                                                                                          | operator info                     | memory    | disk |
+------------------------+----------+---------+-----------+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| IndexReader_7          | 15000.00 | 0       | root      |                          | time:1.55ms, open:35µs, close:3.38µs, loops:1, RU:0.81, cop_task: {num: 1, max: 1.49ms, proc_keys: 0, tot_proc: 1ms, copr_cache_hit_ratio: 0.00, build_task_duration: 24.7µs, max_distsql_concurrency: 1}, fetch_resp_duration: 1.5ms, rpc_info:{Cop:{num_rpc:1, total_time:1.49ms}}    | index:IndexRangeScan_6            | 194 Bytes | N/A  |
| └─IndexRangeScan_6     | 15000.00 | 0       | cop[tikv] | table:t, index:s(status) | tikv_task:{time:1.48ms, loops:0}, time_detail: {total_process_time: 1ms}                                                                                                                                                                                                                | range:[999,999], keep order:false | N/A       | N/A  |
+------------------------+----------+---------+-----------+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
```

In the above query we can see the estimation error is huge `15000 vs. 0`. 
The estimation result should be close to `0` since according to `TopN` (see the result below), we should know there is no data whose `status` is `0`, and we should keep the same data distribution given by the `TopN` when estimating for `status=999`.

```
mysql> show stats_topn;
+---------+------------+----------------+-------------+----------+-------+-------+
| Db_name | Table_name | Partition_name | Column_name | Is_index | Value | Count |
+---------+------------+----------------+-------------+----------+-------+-------+
| test    | t          |                | status      |        0 | 1     | 32768 |
| test    | t          |                | status      |        0 | 2     | 32768 |
+---------+------------+----------------+-------------+----------+-------+-------+
```

The problem here is that when doing out-of-range estimation for EQ conditions like `status=999`, given that `999` can't hit any `TopN` values and `Hist` is empty (`Hist.NotNullCount() == 0`), we should know `999` is a newly emerging value in our stats, but we still assume it appears in `Hist` and use the formula `newRows / histNDV` to estimate it.
<img width="982" height="532" alt="Image" src="https://github.com/user-attachments/assets/173f810c-c1ea-42d4-8696-91189e62d31a" />

One possible fix might be fall back to use a driven NDV using sqrt instead of the original NDV from `Hist`:

<img width="900" height="252" alt="Image" src="https://github.com/user-attachments/assets/d4c7163a-2d11-4bb7-ba65-a8c32948f69e" />

```
mysql> explain analyze select * from t where status=999;
+------------------------+---------+---------+-----------+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| id                     | estRows | actRows | task      | access object            | execution info                                                                                                                                                                                                                                                                      | operator info                     | memory    | disk |
+------------------------+---------+---------+-----------+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| IndexReader_7          | 109.31  | 0       | root      |                          | time:284.2µs, open:53.6µs, close:9.13µs, loops:1, RU:0.48, cop_task: {num: 1, max: 175.6µs, proc_keys: 0, copr_cache_hit_ratio: 0.00, build_task_duration: 16.5µs, max_distsql_concurrency: 1}, fetch_resp_duration: 204.2µs, rpc_info:{Cop:{num_rpc:1, total_time:145.8µs}}        | index:IndexRangeScan_6            | 190 Bytes | N/A  |
| └─IndexRangeScan_6     | 109.31  | 0       | cop[tikv] | table:t, index:s(status) | tikv_task:{time:108.2µs, loops:0}                                                                                                                                                                                                                                                   | range:[999,999], keep order:false | N/A       | N/A  |
+------------------------+---------+---------+-----------+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
```

### 2. What did you expect to see? (Required)
The estimation error should be smaller.

### 3. What did you see instead (Required)
A large estimation error `15000 vs. 0`.

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
Master

### PR DESCRIPTION
**Pull request by qw4990**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: close #64137

Problem Summary: planner: consider empty histogram and newly emerging values in out-of-range estimation for EQ conditions more properly

### What changed and how does it work?

See https://github.com/pingcap/tidb/issues/64137 for more details.

Hard to create a stable and graceful test case for this issue, so I tested it locally and here is the result:


```
Before This PR:
+------------------------+----------+---------+-----------+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| id                     | estRows  | actRows | task      | access object            | execution info                                                                                                                                                                                                                                                                          | operator info                     | memory    | disk |
+------------------------+----------+---------+-----------+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| IndexReader_7          | 15000.00 | 0       | root      |                          | time:1.55ms, open:35µs, close:3.38µs, loops:1, RU:0.81, cop_task: {num: 1, max: 1.49ms, proc_keys: 0, tot_proc: 1ms, copr_cache_hit_ratio: 0.00, build_task_duration: 24.7µs, max_distsql_concurrency: 1}, fetch_resp_duration: 1.5ms, rpc_info:{Cop:{num_rpc:1, total_time:1.49ms}}    | index:IndexRangeScan_6            | 194 Bytes | N/A  |
| └─IndexRangeScan_6     | 15000.00 | 0       | cop[tikv] | table:t, index:s(status) | tikv_task:{time:1.48ms, loops:0}, time_detail: {total_process_time: 1ms}                                                                                                                                                                                                                | range:[999,999], keep order:false | N/A       | N/A  |
+------------------------+----------+---------+-----------+--------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+

After this PR:
+------------------------+---------+---------+-----------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| id                     | estRows | actRows | task      | access object            | execution info                                                                                                                                                                                                                                                                   | operator info                     | memory    | disk |
+------------------------+---------+---------+-----------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| IndexReader_7          | 109.31  | 0       | root      |                          | time:953.6µs, open:11.2µs, close:2.38µs, loops:1, RU:0.48, cop_task: {num: 1, max: 924.8µs, proc_keys: 0, copr_cache_hit_ratio: 0.00, build_task_duration: 7µs, max_distsql_concurrency: 1}, fetch_resp_duration: 929.9µs, rpc_info:{Cop:{num_rpc:1, total_time:919.7µs}}        | index:IndexRangeScan_6            | 190 Bytes | N/A  |
| └─IndexRangeScan_6     | 109.31  | 0       | cop[tikv] | table:t, index:s(status) | tikv_task:{time:914.7µs, loops:0}                                                                                                                                                                                                                                                | range:[999,999], keep order:false | N/A       | N/A  |
+------------------------+---------+---------+-----------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+

```

### Check List

Tests <!-- At least one of them must be included. -->

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > <!-- Or your custom  "No need to test" reasons -->

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/cardinality/selectivity.go [hunk 1]
```diff
@@ -1172,7 +1172,8 @@ func outOfRangeEQSelectivity(sctx planctx.PlanContext, ndv, realtimeRowCount, co
 
 // outOfRangeFullNDV estimates the number of qualified rows when the topN represents all NDV values
 // and the searched value does not appear in the topN
-func outOfRangeFullNDV(ndv, origRowCount, notNullCount, realtimeRowCount, increaseFactor float64, modifyCount int64) (result float64) {
+func outOfRangeFullNDV(ndv, origRowCount, notNullCount, realtimeRowCount, increaseFactor float64,
+	modifyCount int64, emptyHist bool) (result float64) {
 	// If the table hasn't been modified, it's safe to return 0.
 	if modifyCount == 0 {
```
Comment (0xPoe) [inline pkg/planner/cardinality/selectivity.go:1178]: Off topic: I’m curious if this is really safe, because we might have a delayed modify count here.

**Review by 0xPoe — COMMENTED** [review]
Looks reasonable to me. Do we need to add a test case for it?
Thanks!

**Comment by qw4990** [comment]
I added more comments and test cases, PTAL @0xPoe @terry1purcell @elsa0520

File: pkg/planner/cardinality/selectivity.go [hunk 2]
```diff
@@ -1189,14 +1189,21 @@ func outOfRangeFullNDV(ndv, origRowCount, notNullCount, realtimeRowCount, increa
...
 		// the caller of the function
 		ndv *= increaseFactor
 	}
+	// If topN represents all NDV values, the NDV should be relatively small.
+	// Small NDV could cause extremely inaccurate result, use `outOfRangeBetweenRate` to smooth the result.
+	// For example, TopN = {(value:1, rows: 10000), (2, 10000), (3, 10000)} and newRows = 15000, we should assume most
+	// newly added rows are 1, 2 or 3. Then for an out-of-range estimation like `where col=9999`, the result should be
+	// close to 0, but if we still use the original NDV, the result could be extremely large: 15000/3 = 5000.
+	// See #64137 for a concrete example.
+	ndv = max(ndv, float64(outOfRangeBetweenRate)) // avoid inaccurate estimate caused by small NDV
```
Comment (AilinKid) [inline pkg/planner/cardinality/selectivity.go:1207]: so the issue case ndv is max(2, 100) = and get 100 here

Comment (qw4990) [reply pkg/planner/cardinality/selectivity.go:1207]: Yes, and actually this is what we did before, here we just keep the same behavior: use `outOfRangeBetweenRate` as the lower-bound of NDV for out-of-range estimation
image

**Review by terry1purcell — APPROVED** [review]

File: pkg/planner/cardinality/selectivity.go (hunk 1 above)
Comment (terry1purcell) [reply pkg/planner/cardinality/selectivity.go:1178]: The plan is to resolve this in a follow up PR - similar to how the "out of range" for range predicates accounts for modifyCount == 0. The equals and range versions of this code can be merged in a later PR.
