### PR TITLE
ttl, domain: setup a customized session pool with stats collector

### LINKED ISSUE #40109: ttl deletion is not recorded in the stats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE t1(id int, id_2 int, t timestamp, PRIMARY KEY (id, id_2)) TTL=`t` + INTERVAL 1 DAY
```

Insert 10000 rows，6667 of them expired. After a period of time，run `SHOW STATS_META`  to check whether the stats is updated.

### 2. What did you expect to see? (Required)

Auto analyze should be triggered

### 3. What did you see instead (Required)

It's not updated, `Modify_count` is also not updated.

```
MySQL [test]> SHOW STATS_META;
+---------+------------+----------------+---------------------+--------------+-----------+
| Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
+---------+------------+----------------+---------------------+--------------+-----------+
| test    | t1         |                | 2022-12-22 16:03:34 |            0 |     10000 |
+---------+------------+----------------+---------------------+--------------+-----------+
1 row in set (0.001 sec)
```

### 4. What is your TiDB version? (Required)

Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: fc3f04b7b6a471449933b86b3eaa9d1d4bd6a02e
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2022-12-21 14:38:34
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #40109

Problem Summary:

The table stats are not updated after ttl job.

### What is changed and how it works?

Construct a new session pool with stats collector attached.

The `do.sysSessionPool` cannot have stats collector attached, because the stats handler are also using the session in this session pool, which obviously should not be collected (or it will result in endless recursive).

### Check List

Tests

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that ttl deletion is not recorded in the statistics information.
```

### CODE REVIEW

File: session/session.go [hunk 1]
```diff
@@ -3521,7 +3525,10 @@ func createSessionWithOpt(store kv.Storage, opt *Opt) (*session, error) {
 // We need this because when we start DDL in Domain, the DDL need a session
 // to change some system tables. But at that time, we have been already in
 // a lock context, which cause we can't call createSession directly.
-func CreateSessionWithDomain(store kv.Storage, dom *domain.Domain) (*session, error) {
+// attachStatsCollector indicates whether attach the stats collector on the
+// dom to the created session. The DDL session is not attached with a stats
+// collector, while others (e.g. TTL) are.
+func CreateSessionWithDomain(store kv.Storage, dom *domain.Domain, attachStatsCollector bool) (*session, error) {
```
Comment (YangKeao) [inline session/session.go:3531]: Attaching the collector to ddl will make a lot of tests (about analyze) flaky, so I add an option to avoid attaching the collector to the session excepts ttl.

**Review by lcwangchao — APPROVED** [review]

File: session/session.go (hunk 1 above)
Comment (xhebox) [reply session/session.go:3531]: From what I am reviewed, I think API can be better:

1. Use`attachStatsCollector(*session) *session` to avoid API changes
2. Use `opts ... func(*session)` to make it more flexible

**Review by xhebox — COMMENTED** [review]
LGTM

**Comment by YangKeao** [comment]
@xhebox 

> Use `attachStatsCollector(*session) *session` to avoid API changes: local changes to TTL only

Do you mean to attach the stats collector in the ttl session pool in ttl/session pkg? If the `AttachStatsCollector` is exported, I think I can add two function `AttachStatsCollector` and `DettachStatsCollector`, and then TTL could use `do.sysSessionPool` with these two functions (and the newly created session pool is not needed). Do you think it's good?

(It's a little weird that your comment cannot be replied :man_facepalming:  )

**Comment by xhebox** [comment]
> @xhebox
> 
> > Use `attachStatsCollector(*session) *session` to avoid API changes: local changes to TTL only
> 
> Do you mean to attach the stats collector in the ttl session pool in ttl/session pkg? If the `AttachStatsCollector` is exported, I think I can add two function `AttachStatsCollector` and `DettachStatsCollector`, and then TTL could use `do.sysSessionPool` with these two functions (and the newly created session pool is not needed). Do you think it's good?
> 
> (It's a little weird that your comment cannot be replied 🤦‍♂️ )

Yep, I think two options are both good. The comment is a reply to your comment, you can reply it there.

**Comment by YangKeao** [comment]
PTAL @xhebox

File: ttl/ttlworker/job_manager_integration_test.go [hunk 2]
```diff
@@ -123,3 +124,58 @@ func TestFinishJob(t *testing.T) {
 
 	tk.MustQuery("select table_id, last_job_summary from mysql.tidb_ttl_table_status").Check(testkit.Rows("2 {\"total_rows\":0,\"success_rows\":0,\"error_rows\":0,\"total_scan_task\":1,\"scheduled_scan_task\":0,\"finished_scan_task\":0,\"scan_task_err\":\"\\\"'an error message contains both single and double quote'\\\"\"}"))
 }
+
+func TestTTLAutoAnalyze(t *testing.T) {
+	ttlworker.SetResizeWorkersInterval(time.Second)
+	ttlworker.SetUpdateInfoSchemaCacheInterval(time.Second)
+	ttlworker.SetUpdateTTLTableStatusCacheInterval(time.Second)
```
Comment (xhebox) [inline ttl/ttlworker/job_manager_integration_test.go:131]: I think it can be done by `failpoint.Enable('xxxx', 'return(time.Second)')`

**Review by xhebox — APPROVED** [review]
LGTM, one more suggestion

File: ttl/ttlworker/job_manager_integration_test.go (hunk 2 above)
Comment (YangKeao) [reply ttl/ttlworker/job_manager_integration_test.go:131]: Cool. Let me try

Comment (YangKeao) [reply ttl/ttlworker/job_manager_integration_test.go]: Done.

A little problem is that the failpoint cannot parse `time.Second`, I used `1000000000` instead :cry: .

Comment (xhebox) [reply ttl/ttlworker/job_manager_integration_test.go]: @YangKeao Maybe `fmt.Sprintf("return(%d)", time.Second)`, or just `return("1s")`?

Comment (YangKeao) [reply ttl/ttlworker/job_manager_integration_test.go]: Done. PTAL @xhebox
