### PR TITLE
ddl: fix duplicate inforSchema information of rename tables

### LINKED ISSUE #47064: rename tables causes duplicated row in information_schema.columns
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
create table t1(a int);
create table t2(a int);
create table t3(a int);
create database test1;
rename table test.t1 to test1.t1, test.t2 to test1.t2, test.t3 to test1.t3;
select column_name from information_schema.columns where table_name = 't1';
```

### 2. What did you expect to see? (Required)

``` 
+-------------+
| column_name |
+-------------+
| a           |
+-------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
+-------------+
| column_name |
+-------------+
| a           |
| a           |
+-------------+
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #47064

Problem Summary:

### What is changed and how it works?

it seems lead to ApplyDiff twice for the first table of rename table list.

https://github.com/pingcap/tidb/blob/4bd39b5fd712f06b1c4594418a88ee1740f6f1aa/ddl/ddl_worker.go#L1381C2-L1381C2

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/ddl_worker.go [hunk 1]
```diff
@@ -1377,9 +1377,12 @@ func updateSchemaVersion(d *ddlCtx, t *meta.Meta, job *model.Job, multiInfos ...
 		if err != nil {
 			return 0, errors.Trace(err)
 		}
-		affects := make([]*model.AffectedOption, len(newSchemaIDs))
+		affects := make([]*model.AffectedOption, len(newSchemaIDs)-1)
 		for i, newSchemaID := range newSchemaIDs {
-			affects[i] = &model.AffectedOption{
+			if i == 0 {
```
Comment (wjhuang2016) [inline ddl/ddl_worker.go:1382]: Please add a comment for it.

Comment (jiyfhust) [reply ddl/ddl_worker.go:1383]: Done.

**Review by wjhuang2016 — APPROVED** [review]

File: ddl/ddl_worker.go [hunk 2]
```diff
@@ -1377,9 +1377,13 @@ func updateSchemaVersion(d *ddlCtx, t *meta.Meta, job *model.Job, multiInfos ...
 		if err != nil {
 			return 0, errors.Trace(err)
 		}
-		affects := make([]*model.AffectedOption, len(newSchemaIDs))
+		affects := make([]*model.AffectedOption, len(newSchemaIDs)-1)
 		for i, newSchemaID := range newSchemaIDs {
-			affects[i] = &model.AffectedOption{
+			// Do not add the first table to AffectedOpts. Related issue tidb#47064.
+			if i == 0 {
```
Comment (zimulala) [inline ddl/ddl_worker.go:1383]: Could we not change these codes and remove line1393-1295 to fix it?

Comment (zimulala) [reply ddl/ddl_worker.go:1383]: I think it can be fixed, but it does have potential r risks. We may need to remove "applyTableUpdate" like "applyCreateTables" for safety.

Or we can do this according to your PR first, and then do unification.

Comment (jiyfhust) [reply ddl/ddl_worker.go:1383]: I think we can `do unification` later and i'm pleased to do that. We can choose the second method fisrt, because it is a simple and reliable way to fix the problem.

**Review by zimulala — APPROVED** [review]
LGTM

File: ddl/ddl_worker.go (hunk 2 above)
Comment (zimulala) [reply ddl/ddl_worker.go:1383]: Yes. We can fix the bug first. 
Thank you very much for the follow-up help to unify this logic.
