### PR TITLE
expression: fix compatibility of extract day_time unit functions

### LINKED ISSUE #9716: Function `extract` is incompatible with Mysql
## Description
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select extract(DAY_MINUTE FROM "01 23:45:56.89");
select extract(DAY_HOUR FROM "01 23:45:56.89");
select extract(DAY_MICROSECOND FROM "01 23:45:56.89");
select extract(DAY_SECOND FROM "01 23:45:56.89");
```

2. What did you expect to see?
In Mysql
```
mysql> select extract(DAY_MINUTE FROM "01 23:45:56.89");
+-------------------------------------------+
| extract(DAY_MINUTE FROM "01 23:45:56.89") |
+-------------------------------------------+
|                                      4745 |
+-------------------------------------------+
1 row in set (0.00 sec)

mysql> select extract(DAY_HOUR FROM "01 23:45:56.89");
+-----------------------------------------+
| extract(DAY_HOUR FROM "01 23:45:56.89") |
+-----------------------------------------+
|                                      47 |
+-----------------------------------------+
1 row in set (0.00 sec)

mysql> select extract(DAY_MICROSECOND FROM "01 23:45:56.89");
+------------------------------------------------+
| extract(DAY_MICROSECOND FROM "01 23:45:56.89") |
+------------------------------------------------+
|                                   474556890000 |
+------------------------------------------------+
1 row in set (0.00 sec)

mysql> select extract(DAY_SECOND FROM "01 23:45:56.89");
+-------------------------------------------+
| extract(DAY_SECOND FROM "01 23:45:56.89") |
+-------------------------------------------+
|                                    474556 |
+-------------------------------------------+
1 row in set (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> select extract(DAY_MINUTE FROM "01 23:45:56.89");
+-------------------------------------------+
| extract(DAY_MINUTE FROM "01 23:45:56.89") |
+-------------------------------------------+
|                                      NULL |
+-------------------------------------------+
1 row in set, 1 warning (0.01 sec)

mysql> select extract(DAY_HOUR FROM "01 23:45:56.89");
+-----------------------------------------+
| extract(DAY_HOUR FROM "01 23:45:56.89") |
+-----------------------------------------+
|                                    NULL |
+-----------------------------------------+
1 row in set, 1 warning (0.00 sec)
+----------------------------------------+
1 row in set (0.00 sec)

mysql> select extract(DAY_MICROSECOND FROM "01 23:45:56.89");
+------------------------------------------------+
| extract(DAY_MICROSECOND FROM "01 23:45:56.89") |
+------------------------------------------------+
|                                           NULL |
+------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select extract(DAY_SECOND FROM "01 23:45:56.89");
+-------------------------------------------+
| extract(DAY_SECOND FROM "01 23:45:56.89") |
+-------------------------------------------+
|                                      NULL |
+-------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-212-g0681b8125
Git Commit Hash: 0681b8125080045ee0d4747ce61923164c6f2dd1
Git Branch: master
UTC Build Time: 2019-03-14 04:39:19
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```



## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @XuHuaiyu

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close #9716 

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- fix the compatibility of extract day_time unit functions

### CODE REVIEW

**Comment by lzmhhh123** [comment]
./run-all-tests

**Review by ichn-hu — APPROVED** [review]
LGTM

File: types/time.go [hunk 1]
```diff
@@ -2175,6 +2175,14 @@ func ExtractDurationNum(d *Duration, unit string) (int64, error) {
 		return int64(d.Hour())*10000 + int64(d.Minute())*100 + int64(d.Second()), nil
 	case "HOUR_MINUTE":
 		return int64(d.Hour())*100 + int64(d.Minute()), nil
+	case "DAY_MICROSECOND":
```
Comment (XuHuaiyu) [inline types/time.go:2178]: Add some test in `ExtractDurationNum `

Comment (lzmhhh123) [reply types/time.go:2178]: `select extract(day_second from "01 12:12:12")` arrives here.

**Review by XuHuaiyu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
