### PR TITLE
*: use model.CIStr in infoschema v2 to handle case insensitive

### LINKED ISSUE #55421: all values ​​of the TABLE_SCHEMA column of INFORMATION_SCHEMA.TIFLASH_REPLICA are converted to lowercase
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create database 0000__TWPlanReadFromTiflash_BLPLBV ;
use 0000__TWPlanReadFromTiflash_BLPLBV ;
create table t(a int, b int, c int, index idx(a, b));
insert into t values(1,2,3), (4,5,6);
alter table t set tiflash replica 1;
select count(*) from INFORMATION_SCHEMA.TIFLASH_REPLICA where AVAILABLE = 1 and TABLE_NAME='t' and TABLE_SCHEMA='0000__TWPlanReadFromTiflash_BLPLBV';

### 2. What did you expect to see? (Required)
+----------+
| count(*) |
+----------+
|        1 |
+----------+

### 3. What did you see instead (Required)
+----------+
| count(*) |
+----------+
|        0 |
+----------+

All values ​​of the TABLE_SCHEMA column of INFORMATION_SCHEMA.TIFLASH_REPLICA are converted to lowercase: 
image

### 4. What is your TiDB version? (Required)

Release Version: v8.3.0-alpha
Edition: Community
Git Commit Hash: 6499137a0c620ec801b887b3a0bfc4355a143042
Git Branch: heads/refs/tags/v8.3.0-alpha
UTC Build Time: 2024-08-14 11:47:11
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #55421

Problem Summary:

### What changed and how does it work?

Use model.CIStr in infoschema v2.
Currently, most of the code use case insensitive to compare to string, and use original string for display.

### Check List

Tests 

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/infoschema/builder.go [hunk 1]
```diff
@@ -954,9 +954,9 @@ func (b *Builder) createSchemaTablesForDB(di *model.DBInfo, tableFromMeta tableF
 	if b.enableV2 {
 		for name, id := range di.TableName2ID {
```
Comment (lance6716) [inline pkg/infoschema/builder.go:955]: I checked the assignment of `di.TableName2ID`, the value comes from `meta.GetAllNameToIDAndTheMustLoadedTableInfo`. And in that function the table name is matched by `L:` regexp. Should we match for `O:` instead? Otherwise `tableName: model.NewCIStr(name),` is still always lowercased

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: pkg/infoschema/builder.go (hunk 1 above)
Comment (tiancaiamao) [reply pkg/infoschema/builder.go:955]: Good point. We should change to `O:` match

**Review by lance6716 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
