### PR TITLE
disttask: distribute merge sort subtasks to all available nodes

### LINKED ISSUE #60375: import into merge stage is extremely slow for large datasets due to suboptimal resource usage
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. datesize 8T with about 48 billion rows
2. DXF is enabled
3. import into xxx from s3:xxx

### 2. What did you expect to see? (Required)
The merge phase should be optimized to make full use of all available TiDB resources
### 3. What did you see instead (Required)
Only 2 subtasks were allocated, and while one finishes the merge step quickly, the other takes nearly 2 hours.
[next-step=merge-sort] [subtask-count=2]
Image
Image

### 4. What is your TiDB version? (Required)

v8.5.1

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #60375

Problem Summary:

Merge sort subtasks are not distributed to all available nodes properly.

### What changed and how does it work?

Calculate the average file count for each node, and distribute the last batch to all nodes.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  Before this PR:
  ```
  +-----------------+----------+--------------+--------------+---------------+-------+
  | step            | duration | min_duration | max_duration | avg_duration  | count |
  +-----------------+----------+--------------+--------------+---------------+-------+
  | 0. total        | 00:07:13 | NULL         | NULL         | NULL          |     8 |
  | 1. read index   | 00:05:55 | 00:05:43     | 00:05:55     | 00:05:50.6667 |     3 |
  | 2. merge sort   | 00:00:42 | 00:00:08     | 00:00:42     | 00:00:25.0000 |     2 |
  | 3. write&ingest | 00:00:34 | 00:00:33     | 00:00:34     | 00:00:33.6667 |     3 |
  +-----------------+----------+--------------+--------------+---------------+-------+
  4 rows in set (0.02 sec)
  +-----------------+----------+--------------+--------------+---------------+-------+
  | step            | duration | min_duration | max_duration | avg_duration  | count |
  +-----------------+----------+--------------+--------------+---------------+-------+
  | 0. total        | 00:07:17 | NULL         | NULL         | NULL          |     8 |
  | 1. read index   | 00:05:54 | 00:05:35     | 00:05:54     | 00:05:47.3333 |     3 |
  | 2. merge sort   | 00:00:44 | 00:00:08     | 00:00:44     | 00:00:26.0000 |     2 |
  | 3. write&ingest | 00:00:38 | 00:00:29     | 00:00:38     | 00:00:32.6667 |     3 |
  +-----------------+----------+--------------+--------------+---------------+-------+
  4 rows in set (0.17 sec)
  ```
  After this PR:
  ```
  +-----------------+----------+--------------+--------------+---------------+-------+
  | step            | duration | min_duration | max_duration | avg_duration  | count |
  +-----------------+----------+--------------+--------------+---------------+-------+
  | 0. total        | 00:07:30 | NULL         | NULL         | NULL          |     9 |
  | 1. read index   | 00:06:37 | 00:06:32     | 00:06:37     | 00:06:35.3333 |     3 |
  | 2. merge sort   | 00:00:17 | 00:00:15     | 00:00:15     | 00:00:15.0000 |     3 |
  | 3. write&ingest | 00:00:34 | 00:00:33     | 00:00:33     | 00:00:33.0000 |     3 |
  +-----------------+----------+--------------+--------------+---------------+-------+
  4 rows in set (0.03 sec)
  +-----------------+----------+--------------+--------------+---------------+-------+
  | step            | duration | min_duration | max_duration | avg_duration  | count |
  +-----------------+----------+--------------+--------------+---------------+-------+
  | 0. total        | 00:06:40 | NULL         | NULL         | NULL          |     9 |
  | 1. read index   | 00:05:49 | 00:05:35     | 00:05:49     | 00:05:44.0000 |     3 |
  | 2. merge sort   | 00:00:15 | 00:00:14     | 00:00:15     | 00:00:14.3333 |     3 |
  | 3. write&ingest | 00:00:34 | 00:00:34     | 00:00:34     | 00:00:34.0000 |     3 |
  +-----------------+----------+--------------+--------------+---------------+-------+
  4 rows in set (0.03 sec)
  ```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/scheduler/nodes_test.go [hunk 1]
```diff
@@ -189,3 +189,39 @@ func TestFilterByScope(t *testing.T) {
...
+	SplitItemsEvenlyToWorkers(items, 3, 10, func(sub []struct{}) {
+		results = append(results, sub)
+	})
+	require.Len(t, results, 6)
+	require.Len(t, results[0], 10)
+	require.Len(t, results[1], 10)
+	require.Len(t, results[2], 10)
+	require.Len(t, results[3], 1)
+	require.Len(t, results[4], 1)
+	require.Len(t, results[5], 1)
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/nodes_test.go:217]: maybe make it `11/11/11`

File: pkg/disttask/framework/scheduler/nodes.go
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/nodes.go:1]: maybe move to `planner` pkg

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/disttask/framework/scheduler/nodes.go [hunk 2]
```diff
@@ -185,3 +185,30 @@ func filterByScope(nodes []proto.ManagedNode, targetScope string) []string {
...
+	items []T,
+	workerCnt int,
+	defaultStep int,
+	handleOneBatch func([]T),
+) {
+	itemLen := len(items)
+	step := defaultStep
+	if workerCnt > 0 {
+		avgItemsPerWorker := (itemLen + workerCnt - 1) / workerCnt // ceiling division
+		step = min(step, avgItemsPerWorker)
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/nodes.go:200]: we need a lower limit for the `step` to make sure one round of `merge-sort` step works for large data

File: pkg/disttask/framework/scheduler/nodes.go [hunk 3]
```diff
@@ -185,3 +185,30 @@ func filterByScope(nodes []proto.ManagedNode, targetScope string) []string {
...
+// SplitItemsEvenlyToWorkers split the items into batches that is suitble to be handled by `workerCnt` workers.
+func SplitItemsEvenlyToWorkers[T any](
+	items []T,
+	workerCnt int,
+	defaultStep int,
+	handleOneBatch func([]T),
+) {
+	itemLen := len(items)
+	step := defaultStep
+	if workerCnt > 0 {
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/nodes.go:198]: can you consider reuse `mathutil.Divide2Batches`, you can calculate how many subtasks to generate first, then use this method

File: pkg/disttask/framework/scheduler/nodes.go [hunk 4]
```diff
@@ -185,3 +185,30 @@ func filterByScope(nodes []proto.ManagedNode, targetScope string) []string {
...
 	return nodeIDs
 }
+
+// SplitItemsEvenlyToWorkers split the items into batches that is suitble to be handled by `workerCnt` workers.
+func SplitItemsEvenlyToWorkers[T any](
+	items []T,
+	workerCnt int,
+	defaultStep int,
+	handleOneBatch func([]T),
+) {
```
Comment (D3Hunter) [inline pkg/disttask/framework/scheduler/nodes.go:195]: I prefer to make this func only handles `split the items into some batches`, i.e., this function should return `[][]T` out, and let outer logic call `handleOneBatch`

**Comment by D3Hunter** [comment]
current merge-sort will also split the input files into different group and parallel merge them, we need to consider this when split subtask, I think we better have a design for this too, to make sure one round merge-sort works for large data set with large number tidb nodes

File: pkg/disttask/framework/scheduler/nodes.go
Comment (Benjamin2037) [reply pkg/disttask/framework/scheduler/nodes.go:1]: it may not be a good planner, our current scheduler has no relative thing with planner.  Even later, we handle query-related execution, two phases planner is better way, IMO.

File: pkg/lightning/backend/external/writer.go [hunk 5]
```diff
@@ -57,6 +57,9 @@ var (
 	MergeSortOverlapThreshold int64 = 4000
 	// MergeSortFileCountStep is the step of file count when we split the sorted kv files.
 	MergeSortFileCountStep = 4000
+	// MergeSortMergeFactor assumes each merge sort subtask generates 16 files.
+	// To make sure the files count after merge sort is less than threshold, we should set a lower limit for each subtask.
+	MergeSortMergeFactor = int(MergeSortOverlapThreshold) / 16
```
Comment (fzzf678) [inline pkg/lightning/backend/external/writer.go:62]: When the subtask concurrency is less than or equal to 16,  each merge sort subtask will generate 16 files as most. But if the subtask concurrency is greater than 16, eg: 32, each merge sort subtask will generate 32 files as most. Maybe we should also consider this situation?

**Review by fzzf678 — APPROVED** [review]
rest LGTM

File: pkg/util/mathutil/math.go [hunk 6]
```diff
@@ -110,3 +110,31 @@ func Divide2Batches(total, batches int) []int {
...
+	batchSizes := Divide2BatchSizes(len(items), batches)
+	result := make([][]T, 0, batches)
+	start := 0
+	for start < len(items) {
+		for i := 0; i < len(batchSizes); i++ {
+			if batchSizes[i] == 0 {
+				// if current batch is 0, all the rest should be 0
+				break
+			}
+			count := min(batchSizes[i], maxBatchCnt)
```
Comment (D3Hunter) [inline pkg/util/mathutil/math.go:133]: can we consider `maxBatchCnt` when calculating the number of batches we want to split? `Divide2BatchSizes` already done the work to split, we don't need to split it again here

File: pkg/lightning/backend/external/writer.go (hunk 5 above)
Comment (D3Hunter) [reply pkg/lightning/backend/external/writer.go:62]: what about import-into?

> each merge sort subtask will generate 32 files as most.

we should consider concurrency when calculating the number of files assigned to each subtask

File: pkg/ddl/backfilling_dist_scheduler.go [hunk 7]
```diff
@@ -615,16 +617,15 @@ func generateMergePlan(
 		if i < len(eleIDs) {
 			eleID = []int64{eleIDs[i]}
 		}
-		start := 0
-		step := external.MergeSortFileCountStep
-		for start < len(dataFiles) {
-			end := min(start+step, len(dataFiles))
+		minFilesPerBatch := len(dataFiles) / external.MergeSortMergeFactor
+		maxFilesPerBatch := external.MergeSortFileCountStep
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_dist_scheduler.go:621]:
```suggestion
		minFilesPerSubtask := len(dataFiles) / external.MergeSortMergeFactor
		maxFilesPerSubtask := external.MergeSortFileCountStep
```

File: pkg/lightning/backend/external/writer.go [hunk 8]
```diff
@@ -57,6 +57,9 @@ var (
 	MergeSortOverlapThreshold int64 = 4000
 	// MergeSortFileCountStep is the step of file count when we split the sorted kv files.
 	MergeSortFileCountStep = 4000
+	// MergeSortMergeFactor assumes each merge sort subtask generates 16 files.
+	// To make sure the files count after merge sort is less than threshold, we should set a lower limit for each subtask.
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/writer.go:61]:
```suggestion
	// To make sure the files count after merge sort is less than threshold, we should set a lower limit for each subtask.
	// it also determines the max number of subtasks can be splitted.
```

File: pkg/util/mathutil/math.go [hunk 9]
```diff
@@ -110,3 +110,31 @@ func Divide2Batches(total, batches int) []int {
 	}
 	return result
 }
+
+// Divide2Batches divies 'items' into 'batches', and returns the items in each batch.
+// The size of each batch is determined by Divide2BatchSizes.
+func Divide2Batches[T any](items []T, batches int, minBatchCnt, maxBatchCnt int) [][]T {
```
Comment (D3Hunter) [inline pkg/util/mathutil/math.go:116]:
```suggestion
func Divide2Batches[T any](items []T, batches int, minBatchSize, maxBatchSize int) [][]T {
```

File: pkg/util/mathutil/math.go [hunk 10]
```diff
@@ -110,3 +110,31 @@ func Divide2Batches(total, batches int) []int {
...
+	if minBatchCnt > 0 {
+		maxBatches := len(items) / minBatchCnt
+		batches = min(batches, maxBatches)
+	}
+	batchSizes := Divide2BatchSizes(len(items), batches)
+	result := make([][]T, 0, batches)
+	start := 0
+	for start < len(items) {
+		for i := 0; i < len(batchSizes); i++ {
+			if batchSizes[i] == 0 {
```
Comment (D3Hunter) [inline pkg/util/mathutil/math.go:129]: Divide2BatchSizes won't generate batch of size 0

File: pkg/util/mathutil/math.go (hunk 9 above)
Comment (D3Hunter) [inline pkg/util/mathutil/math.go:116]: please move to `external` pkg, it's our algorithm to generate sizes of subtasks for global sort, not that general

File: pkg/lightning/backend/external/util_test.go [hunk 11]
```diff
@@ -642,3 +642,43 @@ func TestRemoveDuplicatesMoreThan2(t *testing.T) {
...
+	items = []string{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"}
+	result, err = DivideMergeSortDataFiles(items, 5, 0)
+	require.NoError(t, err)
+	require.EqualValues(t, [][]string{{"1", "2", "3"}, {"4", "5"}, {"6", "7"}, {"8", "9"}, {"10", "11"}}, result)
+}
+
+func TestDivideMergeSortDataFilesSubtaskCount(t *testing.T) {
+	const Concurrency = 16
+	for _, nodeCount := range []int{1, 3, 7, 16, 30, 60, 97} {
+		for _, fileCount := range []int{3000, 4000, 40000, 400000, 712345, 1000000} {
```
Comment (D3Hunter) [inline pkg/lightning/backend/external/util_test.go:671]:
```suggestion
	for _, fileCount := range []int{3000, 4000, 40000, 400000, 712345, 1000000} {
		for _, nodeCount := range []int{1, 3, 7, 16, 30, 60, 97} {
```
the result is better to compare when we use file count as first dimension

**Review by D3Hunter — COMMENTED** [review]
can we have a larger case to test without `force merge`, i want to see how it out perform and will it affect ingest step as we might have more out files from merge-sort now

File: pkg/lightning/backend/external/util.go [hunk 12]
```diff
@@ -528,3 +529,42 @@ func doRemoveDuplicates[E any](
...
+	// adjust node cnt for remainder files to avoid having too much target files.
+	adjustNodeCnt := nodeCnt
+	maxTargetFilesPerSubtask := max(MergeSortMaxSubtaskTargetFiles, mergeConc)
+	for (rounds*nodeCnt*maxTargetFilesPerSubtask)+(adjustNodeCnt*maxTargetFilesPerSubtask) > int(MergeSortOverlapThreshold) {
+		adjustNodeCnt--
+		if adjustNodeCnt == 0 {
+			return nil, errors.Errorf("too many files to sort, dataFiles=%d, nodeCnt=%d", dataFilesCnt, nodeCnt)
+		}
+	}
+	sizes := mathutil.Divide2Batches(remainder, adjustNodeCnt)
```
[the remark this answers is not in the document]
Comment (tangenta) [reply pkg/lightning/backend/external/util.go:566]: `remainder/minimalFileCount` is OK. Using ceiling division will cause actual files less than `minimalFileCount`.

**Review by D3Hunter — APPROVED** [review]
