### PR TITLE
distsql: do not merge unconsumed CopStats if not belong to user sessions

### LINKED ISSUE #51928: runtime error: invalid memory address or nil pointer dereference by merge unconsumedCopStats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
    analyze_test.go:1874: 

        	Error Trace:	pkg/executor/test/analyzetest/analyze_test.go:1874

        	            				pkg/executor/test/analyzetest/analyze_test.go:2027

        	            				pkg/executor/test/analyzetest/analyze_test.go:2030

        	Error:      	Not equal: 

        	            	expected: "[executor:1317]Query execution was interrupted"

        	            	actual  : "runtime error: invalid memory address or nil pointer dereference"

        	            	

        	            	Diff:

        	            	--- Expected

        	            	+++ Actual

        	            	@@ -1 +1 @@

        	            	-[executor:1317]Query execution was interrupted

        	            	+runtime error: invalid memory address or nil pointer dereference

        	Test:       	TestKillAutoAnalyzeIndex

        	Messages:   	kill running analyze job
```

### LINKED ISSUE #51951: Panic in the TestVerifyChecksum
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7df2d15]
goroutine 33670 [running]:
github.com/pingcap/tidb/pkg/distsql.(*selectResult).Close(0xc009ae8380)
	pkg/distsql/select_result.go:610 +0x175
github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).handleChecksumRequest.func1()
	pkg/executor/checksum.go:159 +0x29
github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).handleChecksumRequest(0xc0063f8960, 0xc008f6aa80?)
	pkg/executor/checksum.go:170 +0x3e5
github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).checksumWorker(0xc00a23cc40?, 0xc0000324d0?, 0xc007bb6fb0?)
	pkg/executor/checksum.go:144 +0xa7
created by github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).Open in goroutine 223
	pkg/executor/checksum.go:64 +0x105
================================================================================
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/51916/fast_test_tiprow/1770373340058357760#1:build-log.txt%3A2591

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve?

Issue Number: close #51928 close #51951

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

File: pkg/distsql/select_result.go [hunk 1]
```diff
@@ -603,11 +603,13 @@ func (r *selectResult) Close() error {
 	if respSize > 0 {
 		r.memConsume(-respSize)
 	}
-	if unconsumed, ok := r.resp.(copr.HasUnconsumedCopRuntimeStats); ok && unconsumed != nil {
-		unconsumedCopStats := unconsumed.CollectUnconsumedCopRuntimeStats()
-		for _, copStats := range unconsumedCopStats {
-			_ = r.updateCopRuntimeStats(context.Background(), copStats, time.Duration(0))
-			r.ctx.GetSessionVars().StmtCtx.MergeExecDetails(&copStats.ExecDetails, nil)
+	if r.ctx != nil {
```
Comment (you06) [inline pkg/distsql/select_result.go:606]: If `r.ctx == nil`, L624 also panics.

Comment (jiyfhust) [reply pkg/distsql/select_result.go:606]: May there is some relationship between `r.stats != nil` and `r.ctx != nil`, because L624 is not new introduced and not sure if it ever paniced before.

Comment (jiyfhust) [reply pkg/distsql/select_result.go:606]: Add  judgement `r.ctx != nil` to check it by https://github.com/pingcap/tidb/pull/51950/commits/8e0d4ccd7c2ae0022907d0b74763e89c3472462c.

Comment (you06) [reply pkg/distsql/select_result.go:606]: I see, both ctx and stats are not set for check sum requests.

**Review by you06 — APPROVED** [review]

**Comment by jiyfhust** [comment]
> please assign [cfzjywxk](https://github.com/cfzjywxk) for approval.

PTAL @cfzjywxk

**Review by cfzjywxk — APPROVED** [review]
