### PR TITLE
planner: check readEngines when building plan for index hint

### LINKED ISSUE #15494: tidb_isolation_read_engines='tiflash',  select using index doesn't work as expect
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
create table t(a int, index idx(a));
ALTER TABLE t SET TIFLASH REPLICA 1;
set @@session.tidb_isolation_read_engines='tiflash';
select * from t use index(idx);
```
### 2. What did you expect to see?
```
mysql> select * from t use index(idx);
Empty set (0.06 sec)
```

### 3. What did you see instead?
```
mysql> select * from t use index(idx);
ERROR 1815 (HY000): Internal : Can not find access path matching 'tidb_isolation_read_engines'(value: 'tiflash') and tidb-server config isolation-read(engines: '[tikv tiflash tidb]'). Available values are 'tikv'.
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
| Release Version: v4.0.0-beta.1-412-gd2ef363
Git Commit Hash: d2ef363ad1363c02bbaa749ebb954cfc990ab131
Git Branch: HEAD
UTC Build Time: 2020-03-16 05:49:26
GoVersion: go1.13.7
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #15494 

Problem Summary: `set @@session.tidb_isolation_read_engines='tiflash'; ` and use index can't get correct error information.

### What is changed and how it works?

What's Changed: Check ReadEngines whether has TiKV when building an indexScan.

How it Works:

### Related changes

- Need to cherry-pick to the release branch 4.0

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
```
mysql> drop table t;
Query OK, 0 rows affected (0.19 sec)

mysql> create table t(a int, index idx(a));
Query OK, 0 rows affected (0.07 sec)

mysql> ALTER TABLE t SET TIFLASH REPLICA 1;
Query OK, 0 rows affected (0.07 sec)

mysql> set @@session.tidb_isolation_read_engines='tiflash';
Query OK, 0 rows affected (0.00 sec)

mysql> select * from t use index(idx);
ERROR 1176 (42000): Key 'idx' doesn't exist in table 't'
mysql> select /*+ use_index(t, idx)*/ * from t;
Empty set, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+--------------------------------------+
| Level   | Code | Message                              |
+---------+------+--------------------------------------+
| Warning | 1176 | Key 'idx' doesn't exist in table 't' |
+---------+------+--------------------------------------+
1 row in set (0.00 sec)

mysql> desc select /*+ use_index(t, idx)*/ * from t;
+-----------------------+----------+--------------+-----------------------------------------+
| id                    | estRows  | task         | operator info                           |
+-----------------------+----------+--------------+-----------------------------------------+
| TableReader_5         | 10000.00 | root         | data:TableFullScan_4                    |
| └─TableFullScan_4     | 10000.00 | cop[tiflash] | table:t, keep order:false, stats:pseudo |
+-----------------------+----------+--------------+-----------------------------------------+
2 rows in set, 1 warning (0.00 sec)

```
Side effects

### CODE REVIEW

File: planner/core/planbuilder.go [hunk 1]
```diff
@@ -652,6 +652,21 @@ func (b *PlanBuilder) detectSelectWindow(sel *ast.SelectStmt) bool {
 	return false
 }
 
+func checkReadEngineHasTiKV(ctx sessionctx.Context) bool {
+	cfgIsolationEngines := set.StringSet{}
+	for _, engine := range config.GetGlobalConfig().IsolationRead.Engines {
```
Comment (lzmhhh123) [inline planner/core/planbuilder.go]: We don't need to check config. Since the session variable is inited by it.

File: planner/core/planbuilder.go [hunk 2]
```diff
@@ -723,6 +738,9 @@ func (b *PlanBuilder) getPossibleAccessPaths(indexHints []*ast.IndexHint, tbl ta
 		}
 		for _, idxName := range hint.IndexNames {
 			path := getPathByIndexName(publicPaths, idxName, tblInfo)
+			if !checkReadEngineHasTiKV(b.ctx) {
```
Comment (lzmhhh123) [inline planner/core/planbuilder.go]: There may be multiple warnings here when meeting many index names. We'd better extract the separate logic for isolation check.

File: planner/core/planbuilder.go [hunk 3]
```diff
@@ -652,6 +652,21 @@ func (b *PlanBuilder) detectSelectWindow(sel *ast.SelectStmt) bool {
 	return false
 }
 
+func checkReadEngineHasTiKV(ctx sessionctx.Context) bool {
+	cfgIsolationEngines := set.StringSet{}
```
Comment (winoros) [inline planner/core/planbuilder.go]: Why this map should be inited everytime we call the function?

File: planner/core/planbuilder.go (hunk 1 above)
Comment (wshwsh12) [reply planner/core/planbuilder.go]: I see the function `filterPathByIsolationRead` also check it.

File: planner/core/planbuilder.go (hunk 2 above)
Comment (wshwsh12) [reply planner/core/planbuilder.go]: Addressed.

File: planner/core/planbuilder.go (hunk 1 above)
Comment (lzmhhh123) [reply planner/core/planbuilder.go]: The new code doesn't check.

Comment (wshwsh12) [reply planner/core/planbuilder.go]: Addressed.

**Comment by winoros** [comment]
Why labeled `WIP`?

**Comment by wshwsh12** [comment]
> Why labeled `WIP`?

Add some ut ing

File: planner/core/planbuilder.go [hunk 4]
```diff
@@ -655,6 +655,12 @@ func (b *PlanBuilder) detectSelectWindow(sel *ast.SelectStmt) bool {
 	return false
 }
 
+func checkReadEngineHasTiKV(ctx sessionctx.Context) bool {
+	isolationReadEngines := ctx.GetSessionVars().GetIsolationReadEngines()
+	_, ok := isolationReadEngines[kv.TiKV]
+	return ok
+}
+
```
Comment (lzmhhh123) [inline planner/core/planbuilder.go]: We can delete this function, and add change judge code like:
```
if _, containTiKV := ctx.GetSessionVars().GetIsolationReadEngines()[kv.TiKV]; !containTiKV {
	...
}
```
