### PR TITLE
server: fix the length metadata of decimal column returned to client

### LINKED ISSUE #5246: Incorrect decimal precision/length
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
CREATE TABLE `decimals` (
  `a` decimal(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
```

add `--column-type-info` flag to MySQL/TiDB client

```
mysql> select * from decimals;
```

2. What did you expect to see?
```
mysql> select * from decimals;
Field   1:  `a`
Catalog:    `def`
Database:   `test1`
Table:      `decimals`
Org_table:  `decimals`
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     21
Max_length: 21
Decimals:   0
Flags:      NOT_NULL NO_DEFAULT_VALUE NUM


+-----------------------+
| a                     |
+-----------------------+
|  10000000000000000000 |
| -10000000000000000000 |
|                100000 |
|                     1 |
+-----------------------+
4 rows in set (0.00 sec)
```

3. What did you see instead?
```
mysql> select * from decimals;
Field   1:  `a`
Catalog:    `def`
Database:   `test`
Table:      `decimals`
Org_table:  `decimals`
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     80
Max_length: 21
Decimals:   0
Flags:      NOT_NULL BINARY NO_DEFAULT_VALUE NUM


+-----------------------+
| a                     |
+-----------------------+
|  10000000000000000000 |
| -10000000000000000000 |
|                100000 |
|                     1 |
+-----------------------+
4 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V`)?
```
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v1.1.0-alpha-172-ga5cd7cd6
Git Commit Hash: a5cd7cd68aaab9472694c2ad1e9ae77173302275
Git Branch: fix_datum_decimal
UTC Build Time: 2017-11-28 07:52:04 |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
JFYI, It has nothing to do with tidb-version, I have tried various versions.

The incorrect length will result in getting wrong precision when using JDBC and other connectors.

### PR DESCRIPTION
**Pull request by XuHuaiyu**
fix #5246 
PTAL @zz-jason @birdstorm

### CODE REVIEW

File: session.go [hunk 1]
```diff
@@ -596,6 +596,7 @@ func (s *session) getExecRet(ctx context.Context, sql string) (string, error) {
 
 // GetGlobalSysVar implements GlobalVarAccessor.GetGlobalSysVar interface.
 func (s *session) GetGlobalSysVar(name string) (string, error) {
+	log.Warning("again")
```
Comment (zimulala) [inline session.go]: Remove this debug log.

**Comment by shenli** [comment]
LGTM
