### PR TITLE
*: fix a bug that wrong index data on prefixed clustered index  (#23742)

### LINKED ISSUE #23707: insert on char(n) prefix primary key with new collation lead to inconsistent
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. setup up 2 tidb instances with new collation on
2. execute following sql on upstream
   ```sql
   create table t (k char(20), v int, primary key (k(4)) /*T![clustered_index] clustered */, key (k)) collate utf8mb4_general_ci;
   insert into t values ('01234', 1), ('12345', 2), ('23456', 1);
   ```
3. backup the table and restore it to downstream
4. do admin check table on downstream

### 2. What did you expect to see? (Required)

No error reported.

### 3. What did you see instead (Required)

```
> admin check table t;
(1105, 'col k, handle &kv.CommonHandle{encoded:[]uint8{0x1, 0x0, 0x30, 0x0, 0x31, 0x0, 0x32, 0x0, 0x33, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf7}, colEndOffsets:[]uint16{0x13}}, index:types.Datum{k:0x5, decimal:0x0, length:0x0, i:0, collation:"utf8mb4_general_ci", b:[]uint8{0x30, 0x31, 0x32, 0x33}, x:interface {}(nil)} != record:types.Datum{k:0x5, decimal:0x0, length:0x0, i:0, collation:"utf8mb4_general_ci", b:[]uint8{0x30, 0x31, 0x32, 0x33, 0x34}, x:interface {}(nil)}')
```

### 4. What is your TiDB version? (Required)

release-5.0 (09a4c57d00175ae3ff9c900d5fb67f6757c58181)
br@86407e1

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #23742 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tidb repo:
git pr https://github.com/pingcap/tidb/pull/23783
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tidb.git pr/23783:release-5.0-9dfc786c4c22
```

---

### What problem does this PR solve?

Issue Number: close #23707 

Problem Summary:

If we create an index on the column which has been prefixed indexed by the clustered index, the restored data is truncated.
Then indexReader would read the wrong truncated data.

### What is changed and how it works?

Save the data with max length.
Says that primary key(a (8)),
For index t(a), don't truncate the value.
For index t(a(9)), truncate to a(9).
For index t(a(7)), truncate to a(8).

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- fix a bug that wrong index data on prefixed clustered index

### CODE REVIEW

File: expression/integration_test.go [hunk 1]
```diff
@@ -8937,3 +8937,29 @@ func (s *testIntegrationSuite) TestIssue23623(c *C) {
 	tk.MustExec("insert into t1 values(-2147483648), (-2147483648), (null);")
 	tk.MustQuery("select count(*) from t1 where c1 > (select sum(c1) from t1);").Check(testkit.Rows("2"))
 }
+<<<<<<< HEAD
```
Comment (qw4990) [inline expression/integration_test.go:8940]: Please resolve conflicts @wjhuang2016
