### PR TITLE
util/codec: Fix analyze table for partitioned table with datetime column and version 1 (#34228)

### LINKED ISSUE #34228: analyze table report error when usingd dynamic partition_prun_mode
version:v5.2.3
 analyze table report error when usingd dynamic partition_prun_mode
mysql> set @@session.tidb_partition_prune_mode = ‘static’;
Query OK, 0 rows affected (0.00 sec)

mysql> analyze table oracle_cb_metric_dbtime;
Query OK, 0 rows affected (13.97 sec)

mysql> set @@session.tidb_partition_prune_mode = ‘dynamic’;
Query OK, 0 rows affected (0.00 sec)

mysql> analyze table oracle_cb_metric_dbtime;
ERROR 1105 (HY000): invalid encoded key flag 9
mysql> set @@session.tidb_partition_prune_mode = ‘static’;
Query OK, 0 rows affected (0.00 sec)

mysql> analyze table oracle_cb_metric_dbtime;
Query OK, 0 rows affected (14.06 sec)

mysql> set @@session.tidb_partition_prune_mode = ‘dynamic’;
Query OK, 0 rows affected (0.00 sec)

mysql> analyze table oracle_cb_metric_dbtime;
ERROR 1105 (HY000): invalid encoded key flag 9
mysql>

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #34228 

Problem Summary:

### What is changed and how it works?
In some cases datetime is stored as Uvarint instead of Uint

### Check List

Tests 

- [ ] Unit test
- [X] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fixed issue where `ANALYZE TABLE` would fail for partitioned table with datetime column and using tidb_analyze_version = 1
```

### CODE REVIEW

File: util/codec/codec.go [hunk 1]
```diff
@@ -870,27 +870,31 @@ func DecodeAsDateTime(b []byte, tp byte, loc *time.Location) (remain []byte, d t
...
+			err = t.ConvertTimeZone(time.UTC, loc)
+			if err != nil {
+				return b, d, err
+			}
+		}
+		d.SetMysqlTime(t)
+	}
 	if err != nil {
 		return b, d, errors.Trace(err)
 	}
```
Comment (hawkingrei) [inline util/codec/codec.go:900]:
```
if err == nil {
  ...
} else {
  return b, d, errors.Trace(err)
}
```

Comment (mjonss) [reply util/codec/codec.go:891]: Thanks, I updated the code, but used something like the below instead:
```
if err != nil {
  return b, d, errors.Trace(err)
}
... // continue with the logic
```

**Review by Yisaer — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]
