### PR TITLE
errctx, types, sessionctx: avoid memory allocation in `HandleError` and reduce allocation in creation of statement context

### LINKED ISSUE #49277: Use interface rather than closure in `*ctx` to remove memory allocation
## Enhancement

Using function pointer (actually a closure of struct method) will generate unexpected memory allocation, and harm the speed. Here is a little example to show the mechanism:

```go
package main

type NoAlloc struct{ count int}

func (n *NoAlloc) fn() { n.count += 1 }

type iNoAlloc interface{ fn() }

func (n *NoAlloc) Fast() iNoAlloc {
    return n
}

func (n *NoAlloc) Slow() func() {
    return n.fn
}

func (n *NoAlloc) AlsoSlow() func() {
    return func() {
        n.fn()
    }
}

func main() {
	
}
```

You can explore these codes on https://godbolt.org/z/r19b1fz1c. You can find that the `func (n *NoAlloc) Slow()` will call `runtime.newobject`. Now `.ErrCtx()` uses the similar pattern, and will make the `HandleError` very slow. We can solve it by passing the interface.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #49277

Problem Summary:

We use a function closure to represent the function used to append warning, which actually creates a struct on heap to store the closure. A smaller example can be found in #49277 . Here I try to use an interface to remove this memory allocation.

### What changed and how does it work?

Use an interface rather than the closure to reduce the memory allocation.

Before:

```
BenchmarkErrCtx
BenchmarkErrCtx-16    	32070070	        35.62 ns/op
PASS
```

After:

```
BenchmarkErrCtx
BenchmarkErrCtx-16    	165152647	         7.261 ns/op
PASS
```

It doesn't allocate heap memory anymore, which will be even more helpful when the GC pressure is heavy.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lcwangchao — APPROVED** [review]

File: pkg/errctx/context.go [hunk 1]
```diff
@@ -60,14 +61,14 @@ func (ctx *Context) WithErrGroupLevel(eg ErrGroup, l Level) Context {
 
 // appendWarning appends the error to warning. If the inner `appendWarningFn` is nil, do nothing.
 func (ctx *Context) appendWarning(err error) {
-	intest.Assert(ctx.appendWarningFn != nil)
-	if fn := ctx.appendWarningFn; fn != nil {
+	intest.Assert(ctx.warnHandler != nil)
+	if w := ctx.warnHandler; w != nil {
 		// appendWarningFn should always not be nil, check fn != nil here to just make code safe.
```
Comment (tangenta) [inline pkg/errctx/context.go:66]:
```suggestion
		// warnHandler should always not be nil, check fn != nil here to just make code safe.
```

Comment (YangKeao) [reply pkg/errctx/context.go]: Fixed.

**Review by tangenta — APPROVED** [review]

**Comment by YangKeao** [comment]
The profile of `BenchmarkErrCtx`

Before:

image

After:

image
