### PR TITLE
Planner: Run full partition pruning if convertToPointGet converted keys to SortKey

### LINKED ISSUE #59827: Wrong Ranges for partition pruning
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```mysql
DROP TABLE IF EXISTS t;
CREATE TABLE `t` (
  `a` varchar(150) NOT NULL,
  `b` varchar(100) NOT NULL,
  `c` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`a`,`b`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
PARTITION BY LIST COLUMNS(`b`)
(PARTITION `p0` VALUES IN ('0'),
 PARTITION `p1` VALUES IN ('1'),
 PARTITION `p2` VALUES IN ('2'));

explain analyze select * from t where a = 'b' and b = '2';
explain analyze select * from t where a = 'b' and (b = '2');
```

https://github.com/pingcap/tidb/blob/75695928b955564835e1284dcdc2c7785cfe1d67/pkg/executor/point_get.go#L58-L65

Here a safe guard is added by #49161, trying to prune and see if it succeeded.

But when there is a pair of `()`, it will not go through the fast path, falling back to findbesttask.

In the slow path, before partition pruning processor rule, the juding paths is already generated by https://github.com/pingcap/tidb/blob/75695928b955564835e1284dcdc2c7785cfe1d67/pkg/planner/core/stats.go#L385-L417 ，which is using `DetachCondAndBuildRangeForIndex`.

While it should be processed by the pruning processor, and use `DetachCondAndBuildRangeForPartition` like https://github.com/pingcap/tidb/blob/75695928b955564835e1284dcdc2c7785cfe1d67/pkg/planner/core/rule_partition_processor.go#L737-L751.

This eventually leads to the failure of that safety guard, returning `table dual` instead.

### 2. What did you expect to see? (Required)
Both pruning results the same

### 3. What did you see instead (Required)
Different pruning results (with bad result as well, no rows would be found)
```mysql
tidb> explain analyze select * from t where a = 'b' and b = '2';
+-------------+---------+---------+------+------------------------------------------------------+----------------------------------------------------------------------------------------------+---------------+--------+------+
| id          | estRows | actRows | task | access object                                        | execution info                                                                               | operator info | memory | disk |
+-------------+---------+---------+------+------------------------------------------------------+----------------------------------------------------------------------------------------------+---------------+--------+------+
| Point_Get_1 | 1.00    | 0       | root | table:t, partition:p2, clustered index:PRIMARY(a, b) | time:35µs, open:375ns, close:1.96µs, loops:1, RU:0.47, Get:{num_rpc:1, total_time:6.42µs} |               | N/A    | N/A  |
+-------------+---------+---------+------+------------------------------------------------------+----------------------------------------------------------------------------------------------+---------------+--------+------+
1 row in set (0.00 sec)

tidb> explain analyze select * from t where a = 'b' and (b = '2');
+-------------+---------+---------+------+--------------------------------------------------------+--------------------------------------------------------+---------------+--------+------+
| id          | estRows | actRows | task | access object                                          | execution info                                         | operator info | memory | disk |
+-------------+---------+---------+------+--------------------------------------------------------+--------------------------------------------------------+---------------+--------+------+
| Point_Get_5 | 1.00    | 0       | root | table:t, partition:dual, clustered index:PRIMARY(a, b) | time:1.33µs, open:83ns, close:250ns, loops:1, RU:0.00 |               | N/A    | N/A  |
+-------------+---------+---------+------+--------------------------------------------------------+--------------------------------------------------------+---------------+--------+------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

v8.5.1, but should affect all version after v8.0

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #59827

Problem Summary:
When PointGetPlan is created by `convertToPointGet`, the `IndexValues` comes from the Range optimizer, and if any of the LIST/RANGE COLUMNS has a non-binary collation, they conditions values are converted to SortKey, which does not work with the LIST/RANGE COLUMNS partitioning pruning code, since they will unconditionally convert it again to SortKey, which may fail finding a matching partition.

NOTE: This only affects PointGet, since BatchPointGet is not supported yet.

### What changed and how does it work?
If the IndexValues are already converted, run the normal partition pruning code on the conditions, to find the matching partition.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Partition Pruning could fail and choose 'TableDual', i.e. no matching partition, in case the optimizer could convert the query to PointGet (if not using the FastPlan) and any LIST COLUMNS or RANGE COLUMNS had non-binary collation.
```

### CODE REVIEW

**Comment by mjonss** [comment]
KEY partitioning does not seem to be affected, since it is using [`val.ToHashKey()`](https://github.com/pingcap/tidb/blob/cca5361a8e56c9ff52eed2fe668dd4c72f31a51f/pkg/table/tables/partition.go#L358) which is using the value's collation, meaning that if it already is converted to binary SortKey, it will get the same hash/key partition as if it is a non-converted values with the original collation, which will be converted in `val.ToHashKey()`

**Comment by mjonss** [comment]
This PR also fixes other issues.

Like using `plan_cache_partition_table_test.go:309: seed: 1741359028167964000` on https://github.com/pingcap/tidb/pull/59918/commits/5bb1b5c9d364024a8a472011e23627783d40b791 with the following patch (i.e. disable this fix):
```diff
diff --git a/pkg/planner/core/point_get_plan.go b/pkg/planner/core/point_get_plan.go
index 030fd88139..671522f454 100644
--- a/pkg/planner/core/point_get_plan.go
+++ b/pkg/planner/core/point_get_plan.go
@@ -348,6 +348,9 @@ func (p *PointGetPlan) LoadTableStats(ctx sessionctx.Context) {
 // error
 // TODO: Also supporting BatchPointGet? Problem is that partition ID must be mapped to handle/IndexValue.
 func needsPartitionPruning(sctx sessionctx.Context, tblInfo *model.TableInfo, pt table.PartitionedTable, dbName string, indexInfo *model.IndexInfo, indexCols []*expression.Column, indexValues []types.Datum, conds []expression.Expression, partitionNames []ast.CIStr) ([]int, bool, error) {
+       if tblInfo != nil {
+               return nil, false, nil
+       }
        for i := range indexValues {
                if tblInfo.Columns[indexInfo.Columns[i].Offset].FieldType.EvalType() != types.ETString ||
                        indexValues[i].Collation() == tblInfo.Columns[indexInfo.Columns[i].Offset].GetCollate() {
```

I get this stack trace:
```
--- FAIL: TestPartitionVarcharFullCover (0.41s)
panic: runtime error: index out of range [2] with length 2 [recovered]
	panic: runtime error: index out of range [2] with length 2 [recovered]
	panic: runtime error: index out of range [2] with length 2

goroutine 32 [running]:
testing.tRunner.func1.2({0x10966d180, 0x1400839a408})
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/testing/testing.go:1632 +0x1bc
testing.tRunner.func1()
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/testing/testing.go:1635 +0x334
panic({0x10966d180?, 0x1400839a408?})
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/runtime/panic.go:785 +0x124
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec.func1()
	/pkg/executor/adapter.go:491 +0x428
panic({0x10966d180?, 0x1400839a408?})
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/runtime/panic.go:785 +0x124
github.com/pingcap/tidb/pkg/util/collate.decodeRune({0x1400839a108?, 0x140086b9090?}, 0x14006317308?)
	/pkg/util/collate/collate.go:307 +0x15c
github.com/pingcap/tidb/pkg/util/collate.(*unicode0900AICICollator).Compare(0x1400839a348?, {0x1400839a108, 0x2}, {0x10ce5dcc0, 0x1})
	/pkg/util/collate/unicode_0900_ai_ci_generated.go:47 +0x2a8
github.com/pingcap/tidb/pkg/types.CompareString({0x1400839a108, 0x2}, {0x10ce5dcc0, 0x1}, {0x1400839a348?, 0x14000800008?})
	/pkg/types/compare.go:86 +0x58
github.com/pingcap/tidb/pkg/expression.CompareStringWithCollationInfo({0x109a6c920, 0x1400160fe20}, {0x109ab6718?, 0x14007362420?}, {0x109ab6a58, 0x14008fded80}, {0x140086b9090?, 0x14006317420?}, {0x140086b9090?, 0x1400611de00?}, ...)
	/pkg/expression/builtin_compare.go:3430 +0xf8
github.com/pingcap/tidb/pkg/expression.(*builtinLTStringSig).evalInt(0x109a6c868?, {0x109a6c920?, 0x1400160fe20?}, {0x140086b9090?, 0x140063174d8?})
	/pkg/expression/builtin_compare.go:2267 +0x7c
github.com/pingcap/tidb/pkg/expression.(*ScalarFunction).EvalInt(0x14007dcfe30, {0x109a6c868?, 0x1400611de00?}, {0x140086b9090?, 0x0?})
	/pkg/expression/scalar_function.go:499 +0x7c
github.com/pingcap/tidb/pkg/table/tables.(*partitionedTable).locateRangeColumnPartition.func1(0x1)
	/pkg/table/tables/partition.go:1505 +0x158
sort.Search(0x14008fe4370?, 0x14006317658)
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/sort/search.go:65 +0x48
github.com/pingcap/tidb/pkg/table/tables.(*partitionedTable).locateRangeColumnPartition(0x140063176f8?, {0x109a6c868, 0x1400611de00}, 0x140001e1f80?, {0x140001e0b60, 0x3, 0x3})
	/pkg/table/tables/partition.go:1503 +0x128
github.com/pingcap/tidb/pkg/table/tables.(*partitionedTable).locatePartitionCommon(0x14008fe41e0, {0x109a6c868?, 0x1400611de00?}, 0x10ee41878?, 0x10?, 0x10?, 0x72?, {0x140001e0b60?, 0x140070d9a10?, 0x0?})
	/pkg/table/tables/partition.go:1420 +0x58
github.com/pingcap/tidb/pkg/table/tables.(*partitionedTable).locatePartitionIdx(0x14006317868?, {0x109a6c868?, 0x1400611de00?}, {0x140001e0b60?, 0x10d1ae001?, 0x72?})
	/pkg/table/tables/partition.go:1460 +0x7c
github.com/pingcap/tidb/pkg/table/tables.(*partitionedTable).GetPartitionIdxByRow(0x140017fcf80?, {0x109a6c868?, 0x1400611de00?}, {0x140001e0b60?, 0x0?, 0x0?})
	/pkg/table/tables/partition.go:1691 +0x28
github.com/pingcap/tidb/pkg/planner/core.(*PointGetPlan).PrunePartitions(0x1400b2b9a40, {0x109ab9400, 0x14006986a08})
	/pkg/planner/core/point_get_plan.go:483 +0x904
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildPointGet(0x1400737a700, 0x1400b2b9a40)
	/pkg/executor/point_get.go:58 +0x98
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0x10c5f25b0?, {0x109a53140?, 0x1400b2b9a40})
	/pkg/executor/builder.go:197 +0xf78
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildSelection(0x1400737a700, 0x140001e09a0)
	/pkg/executor/builder.go:2041 +0x68
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0x10c5f25f0?, {0x109a529c0?, 0x140001e09a0})
	/pkg/executor/builder.go:273 +0x900
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildProjection(0x1400737a700, 0x140001e08c0)
	/pkg/executor/builder.go:2089 +0x68
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0x109ab9400?, {0x109a52a40?, 0x140001e08c0})
	/pkg/executor/builder.go:279 +0xa54
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).buildExecutor(0x140001e0a80)
	/pkg/executor/adapter.go:1230 +0x150
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec(0x140001e0a80, {0x109a23a68, 0x1400681a570})
	/pkg/executor/adapter.go:571 +0x7a8
github.com/pingcap/tidb/pkg/session.runStmt({0x109a23890?, 0x10d1ae088?}, 0x14006986a08, {0x109a41e38, 0x140001e0a80})
	/pkg/session/session.go:2305 +0x274
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt(0x14006986a08, {0x109a23890?, 0x10d1ae088?}, {0x109a3e4b8, 0x140012e88c0})
	/pkg/session/session.go:2167 +0xc60
github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext(0x1400679a460, {0x109a23890, 0x10d1ae088}, {0x14008c4c8d0, 0x2a}, {0x0, 0x0, 0x0})
	/pkg/testkit/testkit.go:425 +0x744
github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQueryWithContext(0x1400679a460, {0x109a23890, 0x10d1ae088}, {0x14008c4c8d0, 0x2a}, {0x0, 0x0, 0x0})
	/pkg/testkit/testkit.go:240 +0xc8
github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQuery(0x1400679a460, {0x14008c4c8d0, 0x2a}, {0x0, 0x0, 0x0})
	/pkg/testkit/testkit.go:176 +0x8c
github.com/pingcap/tidb/pkg/planner/core_test.preparedStmtPointGet(0x1400138e340, {0x14005e10008, 0x3e8, 0x0?}, 0x1400679a460, {{0x14006319c30, 0x3, 0x3}, {0x14006319f48, 0x1, ...}, ...}, ...)
	/pkg/planner/core/plan_cache_partition_table_test.go:588 +0x474
github.com/pingcap/tidb/pkg/planner/core_test.testPartitionFullCover(0x1400138e340, {0x14006319ce0, 0x5, 0x10a98bd93?}, {0x14006319c60, 0x2, 0x140000d7c58?}, 0x1)
	/pkg/planner/core/plan_cache_partition_table_test.go:426 +0xa74
github.com/pingcap/tidb/pkg/planner/core_test.TestPartitionVarcharFullCover(0x1400138e340?)
	/pkg/planner/core/plan_cache_partition_table_test.go:489 +0x328
testing.tRunner(0x1400138e340, 0x1099c7eb0)
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/testing/testing.go:1690 +0xe4
created by testing.(*T).Run in goroutine 1
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.darwin-arm64/src/testing/testing.go:1743 +0x314
```

File: pkg/planner/core/point_get_plan.go [hunk 1]
```diff
@@ -339,16 +339,70 @@ func (p *PointGetPlan) LoadTableStats(ctx sessionctx.Context) {
...
 
+// needsPartitionPruning checks if IndexValues can be used by GetPartitionIdxByRow() or if they have already been
+// converted to SortKey and would need GetPartitionIdxByRow() to be refactored to work, since it will unconditionally
+// convert it again.
+// Returns:
+// Matching partition
+// if done Partition pruning (else not needed, can use GetPartitionIdxByRow() instead)
+// error
+// TODO: Also supporting BatchPointGet? Problem is that partition ID must be mapped to handle/IndexValue.
+func needsPartitionPruning(sctx sessionctx.Context, tblInfo *model.TableInfo, pt table.PartitionedTable, dbName string, indexInfo *model.IndexInfo, indexCols []*expression.Column, indexValues []types.Datum, conds []expression.Expression, partitionNames []ast.CIStr) ([]int, bool, error) {
```
[the remark this answers is not in the document]
Comment (mjonss) [reply pkg/planner/core/point_get_plan.go:350]: This should always be the same, I see no need to validate it.

**Review by Defined2014 — APPROVED** [review]

File: pkg/planner/core/point_get_plan.go [hunk 2]
```diff
@@ -370,23 +424,46 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) bool {
...
 	if !p.SCtx().GetSessionVars().StmtCtx.UseCache() &&
 		p.PartitionIdx != nil {
-		return false
+		return false, nil
 	}
 	is := sessiontxn.GetTxnManager(sctx).GetTxnInfoSchema()
 	tbl, ok := is.TableByID(context.Background(), p.TblInfo.ID)
 	if tbl == nil || !ok {
 		// Can this happen?
 		intest.Assert(false)
```
Comment (qw4990) [inline pkg/planner/core/point_get_plan.go:433]: It seems like this Assert can be removed since now we'll return an error in this case.

File: pkg/planner/core/point_get_plan.go [hunk 3]
```diff
@@ -370,23 +424,46 @@ func (p *PointGetPlan) PrunePartitions(sctx sessionctx.Context) bool {
...
-		return false
+		return false, errors.Errorf("table %d not found", p.TblInfo.ID)
 	}
 	pt := tbl.GetPartitionedTable()
 	if pt == nil {
 		// Can this happen?
 		intest.Assert(false)
```
Comment (qw4990) [inline pkg/planner/core/point_get_plan.go:439]: Same as above, this assert should be removed.

File: pkg/planner/core/point_get_plan.go [hunk 4]
```diff
@@ -339,16 +339,70 @@ func (p *PointGetPlan) LoadTableStats(ctx sessionctx.Context) {
...
+			OrigColName: tblCol.Name,
+		})
+		if !found {
+			tblCols = append(tblCols, &expression.Column{
+				ID:       tblCol.ID,
+				OrigName: tblCol.Name.O,
+				RetType:  tblCol.FieldType.Clone(),
+			})
+		}
+	}
```
Comment (qw4990) [inline pkg/planner/core/point_get_plan.go:387]: Is this operations common for partitioning tables? If Yes, could we wrap this operation as a separate function in `partition_prune.go`?

Comment (mjonss) [reply pkg/planner/core/point_get_plan.go:387]: I tried using [`ColumnInfos2ColumnsAndNames()`](https://github.com/pingcap/tidb/blob/9d1dd4d3b0ff3dfae044ae6d4e300d64cd6adbdb/pkg/expression/expression.go#L1080) but there were [test failures](https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/28841/pipeline). So I'm keeping this code for now.

**Review by qw4990 — APPROVED** [review]
