### PR TITLE
global sort: fix inner retry doesn't reset collector

### LINKED ISSUE #52884: global sort IMPORT INTO deadlock due to large tasks
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

found by QA automatic test

### 2. What did you expect to see? (Required)

not deadlock

### 3. What did you see instead (Required)

```
[2024/04/25 12:24:43.369 +08:00] [INFO] [local.go:1318] ["start import engine"] [category=ddl-ingest] [uuid=a55d695a-5464-5ab9-bde5-ef29d87c2f79] ["region ranges"=1061] [count=0] [size=107374182400]
...
[2024/04/25 12:28:42.762 +08:00] [WARN] [local.go:1022] ["There is no pairs in range"] [category=ddl-ingest] [start=7480000000000001505F72800000000024155B] [end=7480000000000001505F72800000000022F0F9]
...
[2024/04/25 12:28:42.762 +08:00] [INFO] [reader.go:42] ["read all data start"]
...
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/a0510df6-1444-4c98-a1e6-6702b82afe91_stat/3] [startOffset=110431299] [endOffset=1345667994] [expectedConc=148] [concurrency=148]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/36c7dc76-b8ca-48ef-bb96-4387a8f47a7f_stat/2] [startOffset=1103174523] [endOffset=1608653871] [expectedConc=61] [concurrency=61]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/36c7dc76-b8ca-48ef-bb96-4387a8f47a7f_stat/3] [startOffset=0] [endOffset=522556353] [expectedConc=63] [concurrency=63]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/b8b9688f-5f10-4a06-9916-e354ba88edbc_stat/2] [startOffset=74000355] [endOffset=1309237050] [expectedConc=148] [concurrency=148]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/d7a98445-a276-4efb-a5f3-185f59cd9dc9_stat/2] [startOffset=280062882] [endOffset=1514161110] [expectedConc=148] [concurrency=148]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/de504840-c3cc-4fd0-a5be-7984fbb45cb4_stat/2] [startOffset=144585309] [endOffset=1514264607] [expectedConc=164] [concurrency=164]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/77a72fd2-34a7-496a-8d25-861f7905d239_stat/2] [startOffset=74000355] [endOffset=1309237050] [expectedConc=148] [concurrency=148]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/ef3ac2e5-9070-4102-8dc7-f9269cf0b3da_stat/3] [startOffset=110431299] [endOffset=1345667994] [expectedConc=148] [concurrency=148]
[2024/04/25 12:28:43.059 +08:00] [INFO] [engine.go:248] ["found hotspot file in getFilesReadConcurrency"] [filename=90002/30032/data/46a2d628-8d0c-4699-8c3b-159aab328f65_stat/2] [startOffset=278924415] [endOffset=1353637263] [expectedConc=129] [concurrency=129]
```

in global sort, there should not be "There is no pairs in range" case. And "read all data start" shows we are going to read very large data, which is also not expected

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #52884

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/backend/external/writer.go [hunk 1]
```diff
@@ -536,6 +535,7 @@ func (w *Writer) flushSortedKVs(ctx context.Context) (string, string, error) {
 			_ = statWriter.Close(ctx)
 		}
 	}()
+	w.rc.reset()
```
Comment (lance6716) [inline pkg/lightning/backend/external/writer.go:538]: the fix is here

**Review by D3Hunter — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM
