### PR TITLE
planner: fix HashAgg cannot pushdown to tiflash_compute

### LINKED ISSUE #40717: HashAgg cannot pushdown to tiflash_compute node for static pruning partition table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Deploy cluster in disaggregated-tiflash mode(check [example config topo](https://github.com/guo-shaoge/tiflash/blob/disaggregated_tiflash_deploy/etc/disaggregated_tiflash.yaml))
  1.1. Set tidb.toml `disaggregated-tiflash` as true.
  1.2. Set tiflash config: `flash.disaggregated_mode` as `tiflash_compute` or `tiflash_storage`
4. Force use `static pruning` for partition table: `set @@tidb_partition_prune_mode = 'static';` (because in dynamic mode, HashAgg can be pushdown to tiflash_compute node.)
5. Create table and run query as following:
```
drop table if exists t1;
create table t1(c1 int, c2 int) partition by hash(c1) partitions 3;
alter table t1 set tiflash replica 1;
set @@tidb_isolation_read_engines = 'tiflash';
explain select count(1) from t1; 
```

### 2. What did you expect to see? (Required)
HashAgg can push down to tiflash_compute.

```
MySQL [test]> explain select count(1) from t1;
+----------------------------------+----------+-------------------+------------------------+----------------------------------+
| id                               | estRows  | task              | access object          | operator info                    |
+----------------------------------+----------+-------------------+------------------------+----------------------------------+
| HashAgg_17                       | 1.00     | root              |                        | funcs:count(Column#5)->Column#4  |
| └─PartitionUnion_18              | 3.00     | root              |                        |                                  |
|   ├─StreamAgg_33                 | 1.00     | root              |                        | funcs:count(Column#7)->Column#5  |
|   │ └─TableReader_34             | 1.00     | root              |                        | data:StreamAgg_24                |
|   │   └─StreamAgg_24             | 1.00     | batchCop[tiflash] |                        | funcs:count(1)->Column#7         |
|   │     └─TableFullScan_32       | 10000.00 | batchCop[tiflash] | table:t1, partition:p0 | keep order:false, stats:pseudo   |
|   ├─StreamAgg_50                 | 1.00     | root              |                        | funcs:count(Column#9)->Column#5  |
|   │ └─TableReader_51             | 1.00     | root              |                        | data:StreamAgg_41                |
|   │   └─StreamAgg_41             | 1.00     | batchCop[tiflash] |                        | funcs:count(1)->Column#9         |
|   │     └─TableFullScan_49       | 10000.00 | batchCop[tiflash] | table:t1, partition:p1 | keep order:false, stats:pseudo   |
|   └─StreamAgg_67                 | 1.00     | root              |                        | funcs:count(Column#11)->Column#5 |
|     └─TableReader_68             | 1.00     | root              |                        | data:StreamAgg_58                |
|       └─StreamAgg_58             | 1.00     | batchCop[tiflash] |                        | funcs:count(1)->Column#11        |
|         └─TableFullScan_66       | 10000.00 | batchCop[tiflash] | table:t1, partition:p2 | keep order:false, stats:pseudo   |
+----------------------------------+----------+-------------------+------------------------+----------------------------------+
14 rows in set, 1 warning (0.002 sec)
```

### 3. What did you see instead (Required)
HashAgg didn't push down to tiflash_compute.

```
MySQL [test]> explain select count(1) from t1;
+----------------------------------+----------+--------------+------------------------+---------------------------------+
| id                               | estRows  | task         | access object          | operator info                   |
+----------------------------------+----------+--------------+------------------------+---------------------------------+
| HashAgg_17                       | 1.00     | root         |                        | funcs:count(Column#5)->Column#4 |
| └─PartitionUnion_18              | 3.00     | root         |                        |                                 |
|   ├─HashAgg_22                   | 1.00     | root         |                        | funcs:count(1)->Column#5        |
|   │ └─TableReader_34             | 10000.00 | root         |                        | data:ExchangeSender_33          |
|   │   └─ExchangeSender_33        | 10000.00 | mpp[tiflash] |                        | ExchangeType: PassThrough       |
|   │     └─TableFullScan_32       | 10000.00 | mpp[tiflash] | table:t1, partition:p0 | keep order:false, stats:pseudo  |
|   ├─HashAgg_47                   | 1.00     | root         |                        | funcs:count(1)->Column#5        |
|   │ └─TableReader_59             | 10000.00 | root         |                        | data:ExchangeSender_58          |
|   │   └─ExchangeSender_58        | 10000.00 | mpp[tiflash] |                        | ExchangeType: PassThrough       |
|   │     └─TableFullScan_57       | 10000.00 | mpp[tiflash] | table:t1, partition:p1 | keep order:false, stats:pseudo  |
|   └─HashAgg_72                   | 1.00     | root         |                        | funcs:count(1)->Column#5        |
|     └─TableReader_84             | 10000.00 | root         |                        | data:ExchangeSender_83          |
|       └─ExchangeSender_83        | 10000.00 | mpp[tiflash] |                        | ExchangeType: PassThrough       |
|         └─TableFullScan_82       | 10000.00 | mpp[tiflash] | table:t1, partition:p2 | keep order:false, stats:pseudo  |
+----------------------------------+----------+--------------+------------------------+---------------------------------+
14 rows in set, 1 warning (0.003 sec)
```
### 4. What is your TiDB version? (Required)
v6.6.0-alpha

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #40717

Problem Summary:
Why HashAgg(for static pruning partition table) cannot pushdown to tiflash_compute node in disaggregated mode:
1. In non-disaggregated-tiflash mode, for static pruning partition table, only `cop` and `batchCop` is allowed.
2. In disaggregated-tiflash mode, we deprecated `cop` and `batchCop`.
3. In code [here](https://github.com/pingcap/tidb/blob/master/planner/core/find_best_task.go#L2024), we return invalidTask when `prop.TaskTp` is `MPPTaskType`. So cannot generate mpp HashAgg.

### What is changed and how it works?
1. Enable generate mppTask of HashAgg(or other operators) even for static pruning partition table in disaggregated-mode [here](https://github.com/pingcap/tidb/pull/40828/files#diff-f603dfc91719f7335c1d0ee9a59824d0d47ad43946271ea798827c7c3564c0b2R2025)
2. Disable `PartitionUnion` to pushdown to tiflash explicitly. Because tiflash doesn't support `PartitionUnion`.
3. Refine agg func mode when insert `firstrow` in rule_aggregation_pushdow.go, because tilfash check [here](https://github.com/pingcap/tiflash/blob/master/dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp#L61) 
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -717,11 +715,6 @@ func (ds *DataSource) setPreferredStoreType(hintInfo *tableHintInfo) {
 }
 
 func isTiFlashComputeNodeAvailable(ctx sessionctx.Context) bool {
```
Comment (hawkingrei) [inline planner/core/logical_plan_builder.go:717]: It is always true. Can we use a const variable?

Comment (guo-shaoge) [reply planner/core/logical_plan_builder.go]: Delete `isTiFlashComputeNodeAvailable`. Will check tilfash_compute when dispatch task instead of explain.

File: planner/core/planbuilder.go [hunk 2]
```diff
@@ -1464,20 +1462,7 @@ func filterPathByIsolationRead(ctx sessionctx.Context, paths []*util.AccessPath,
...
-		failpoint.Inject("testDisaggregatedTiFlashQuery", func(val failpoint.Value) {
-			// Ignore check if tiflash_compute node number.
-			// After we support disaggregated tiflash in test framework, can delete this failpoint.
-			shouldPruneTiFlashCompute = val.(bool)
-		})
-		if shouldPruneTiFlashCompute {
-			outputComputeNodeErrMsg = true
-		}
-		if (!exists && paths[i].StoreType != kv.TiDB) || shouldPruneTiFlashCompute {
+		if _, ok := isolationReadEngines[paths[i].StoreType]; !ok && paths[i].StoreType != kv.TiDB {
```
Comment (guo-shaoge) [inline planner/core/planbuilder.go:1465]: Revert to original code(https://github.com/pingcap/tidb/pull/33535/files#diff-eaf58bd971f17f156e1423b286ac4b2a6434e1b434caa42f2ccea25f8e2ed83bL1403), because better to check tiflash_compute nodes when dispatch task instead of explain.

File: planner/core/task.go [hunk 3]
```diff
@@ -1161,6 +1161,14 @@ func (p *PhysicalUnionAll) attach2MppTasks(tasks ...task) task {
 }
 
 func (p *PhysicalUnionAll) attach2Task(tasks ...task) task {
+	for _, t := range tasks {
+		if _, ok := t.(*mppTask); ok && p.TP() == plancodec.TypePartitionUnion {
+			// In attach2MppTasks(), will attach Union to mppTask directly.
+			// But PartitionUnion cannot pushdown to tiflash, so disable PartitionUnion pushdown to tiflash explicitly.
+			// TODO: Let mppTask convertToRootTask instead of return invalidTask directly.
```
Comment (windtalker) [inline planner/core/task.go:1168]: I'm a little confused about the change and the TODO here, if the goal is to `Let mppTask convertToRootTask instead of return invalidTask directly`, seems just delete the following code is enough?
https://github.com/pingcap/tidb/blob/fd5e67581b5a43a1a7d2cbdb8c345678502f9f03/planner/core/task.go#L1164-L1168

File: planner/core/task.go [hunk 4]
```diff
@@ -1820,6 +1828,10 @@ func (p *PhysicalHashAgg) attach2TaskForMpp(tasks ...task) task {
 	}
 	switch p.MppRunMode {
 	case Mpp1Phase:
+		// TiFlash will check if agg func mode are all same. Otherwise will give error.
+		if !aggFuncModeSame(p) {
```
Comment (windtalker) [inline planner/core/task.go:1832]: In which case that the agg func mode in the same aggregation will be different?

File: planner/core/task.go (hunk 3 above)
Comment (guo-shaoge) [reply planner/core/task.go:1168]: The goal is to explicitly disable `PartitionUnion` attach to mppTask.
But this code(return invalidTask immediately) will ignore letting childTask to convert to rootTask, then attach PartitionUnoin to converted rootTask. So i added this todo.

File: planner/core/task.go (hunk 4 above)
Comment (guo-shaoge) [reply planner/core/task.go:1832]: In [rule_aggregatoin_pushdown.go](https://github.com/pingcap/tidb/blob/master/planner/core/rule_aggregation_push_down.go#L404), will add `firstrow(CompleteMode)`, but other agg funcs are PartionMode.

Comment (guo-shaoge) [reply planner/core/task.go]: Make `firstrow` as `Partial1Mode` [here](https://github.com/pingcap/tidb/pull/40828/files#diff-e404d5c17cb93070fc630bc941121e103d5739b70b62e06df93d6a8861315684R408)

File: planner/core/task.go (hunk 3 above)
Comment (guo-shaoge) [reply planner/core/task.go:1168]: Comments refined.

File: planner/core/task.go [hunk 5]
```diff
@@ -1161,6 +1161,14 @@ func (p *PhysicalUnionAll) attach2MppTasks(tasks ...task) task {
...
 func (p *PhysicalUnionAll) attach2Task(tasks ...task) task {
+	for _, t := range tasks {
+		if _, ok := t.(*mppTask); ok && p.TP() == plancodec.TypePartitionUnion {
+			// In attach2MppTasks(), will attach PhysicalUnion to mppTask directly.
+			// But PartitionUnion cannot pushdown to tiflash, so here disable PartitionUnion pushdown to tiflash explicitly.
+			// For now, return invalidTask immediately, we can refine this by letting childTask of PartitionUnion convert to rootTask.
+			return invalidTask
+		}
+	}
 	for _, t := range tasks {
```
Comment (windtalker) [inline planner/core/task.go:1172]: I think we can merge to two `for loop`?

Comment (guo-shaoge) [reply planner/core/task.go]: Done

File: planner/core/testdata/plan_suite_out.json [hunk 6]
```diff
@@ -7501,5 +7501,104 @@
...
+        "Plan": [
+          "Limit 1.00 root  offset:0, count:79",
+          "└─Sort 1.00 root  Column#11, Column#12, Column#13, Column#14",
+          "  └─HashAgg 1.00 root  funcs:avg(distinct Column#89)->Column#11, funcs:min(Column#90)->Column#12, funcs:sum(distinct Column#91)->Column#13, funcs:max(Column#92)->Column#14",
+          "    └─Projection 7100.44 root  cast(test.tbl_15.col_96, decimal(10,0) UNSIGNED BINARY)->Column#89, Column#15, cast(test.tbl_15.col_91, decimal(3,0) UNSIGNED BINARY)->Column#91, Column#16",
+          "      └─PartitionUnion 7100.44 root  ",
+          "        ├─TableReader 1775.11 root  data:ExchangeSender",
+          "        │ └─ExchangeSender 1775.11 mpp[tiflash]  ExchangeType: PassThrough",
+          "        │   └─HashAgg 1775.11 mpp[tiflash]  group by:test.tbl_15.col_91, test.tbl_15.col_96, funcs:firstrow(test.tbl_15.col_96)->test.tbl_15.col_96, funcs:min(Column#18)->Column#15, funcs:firstrow(test.tbl_15.col_91)->test.tbl_15.col_91, funcs:max(Column#20)->Column#16, funcs:firstrow(test.tbl_15.col_96)->test.tbl_15.col_96, funcs:firstrow(test.tbl_15.col_91)->test.tbl_15.col_91",
```
Comment (windtalker) [inline planner/core/testdata/plan_suite_out.json:7518]: It actually generates a 3 stage aggregation, is it the expected behavior?

**Review by windtalker — APPROVED** [review]
LGTM

File: planner/core/planbuilder.go (hunk 2 above)
Comment (xuyifangreeneyes) [reply planner/core/planbuilder.go:1464]: So if there is no compute node when dispatching tasks, an error will be thrown?

**Review by xuyifangreeneyes — APPROVED** [review]
