### PR TITLE
ddl: fix wrong format of duplicate entry error message

### LINKED ISSUE #53004: duplicate error message for ADD UNIQUE INDEX has wrong format
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When follow the manual test steps of https://github.com/pingcap/tidb/pull/52993

### 2. What did you expect to see? (Required)

```
ERROR 1062 (23000) at line 1: Duplicate entry '1' for key 't.idx'
```

### 3. What did you see instead (Required)

```
ERROR 1062 (23000) at line 1: Duplicate entry '[1]' for key 't.idx'
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #53004

Problem Summary:

### What changed and how does it work?

besides fixing the issue, this PR also refine the BackendCtx interface:
- add comments to explain methods will be called in local or global-sort use case
- When unregister all engines, run collect remote duplicate error

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/ingest/engine_mgr.go [hunk 1]
```diff
@@ -101,19 +101,31 @@ func (bc *litBackendCtx) Register(indexIDs []int64, uniques []bool, tblInfo *mod
...
+func (bc *litBackendCtx) FinishAndUnregisterEngines() error {
 	bc.unregisterMu.Lock()
 	defer bc.unregisterMu.Unlock()
 
 	if len(bc.engines) == 0 {
-		return
+		return nil
 	}
 	numIdx := int64(len(bc.engines))
+	uniqueIdx := make([]int64, 0, numIdx)
```
Comment (tangenta) [inline pkg/ddl/ingest/engine_mgr.go:113]: Is it necessary to use a separate slice?

Comment (lance6716) [reply pkg/ddl/ingest/engine_mgr.go:113]: Do you mean we call `collectRemoteDuplicateRows` inside the `	for _, ei := range bc.engines {` loop?

File: pkg/ddl/ingest/backend.go [hunk 2]
```diff
@@ -124,9 +136,10 @@ func (bc *litBackendCtx) handleErrorAfterCollectRemoteDuplicateRows(
 				return errors.Trace(tikv.ErrKeyExists)
 			}
 			indexName := tErr.Args()[1]
-			valueStr := tErr.Args()[2]
+			//nolint: forcetypeassert
+			valueStr := tErr.Args()[2].([]string)
 
-			return errors.Trace(tikv.ErrKeyExists.FastGenByArgs(valueStr, indexName))
+			return errors.Trace(tikv.ErrKeyExists.FastGenByArgs(strings.Join(valueStr, "-"), indexName))
```
Comment (D3Hunter) [inline pkg/ddl/ingest/backend.go:142]:
```suggestion
			// same as MySQL, use dash to separate values.
			return errors.Trace(tikv.ErrKeyExists.FastGenByArgs(strings.Join(valueStr, "-"), indexName))
```

**Review by D3Hunter — APPROVED** [review]

File: pkg/ddl/ingest/backend.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/ingest/backend.go:142]: I'll encapsulate a function for generating `ErrKeyExists`

File: pkg/ddl/ingest/engine_mgr.go (hunk 1 above)
Comment (tangenta) [reply pkg/ddl/ingest/engine_mgr.go:113]: Or use another `for _, ei := range bc.engines` after cleaning.

File: pkg/ddl/ingest/backend.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/ingest/backend.go:142]: > I'll encapsulate a function for generating ErrKeyExists

I'll do it in a separate PR, because it's related to many components, and there's another bug to be fixed...

And I plan not to add this comment, after the next PR it will be more clear.

File: pkg/ddl/ingest/engine_mgr.go (hunk 1 above)
Comment (lance6716) [reply pkg/ddl/ingest/engine_mgr.go]: https://github.com/pingcap/tidb/pull/54382/commits/ab2bccdf1ec0fa51a5aa3c1dcf95efd39698ee42

Comment (lance6716) [reply pkg/ddl/ingest/engine_mgr.go]: https://github.com/pingcap/tidb/pull/54382/commits/7f13fdf98d875bacb3aa85f2e9ad002dcaabaac8

previous commit is wrong...

File: pkg/ddl/ingest/backend.go (hunk 2 above)
Comment (lance6716) [reply pkg/ddl/ingest/backend.go]: https://github.com/pingcap/tidb/pull/54382/commits/eb097bed669a55a22a295f8b341e7b3dc0649a01

**Review by tangenta — APPROVED** [review]
