### PR TITLE
br: ignore restore pd and gc if SkipPauseGCAndScheduler is on

### LINKED ISSUE #44182: br:  ebs snaptshot backup panic if SkipPauseGCAndScheduler is on
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`backup full --type=aws-ebs --volume-file=/var/lib/br-bin/csb_backup.json --operator-paused-gc-and-scheduler=true --pd=restore-db-a-pd.backup-a:2379 --send-credentials-to-tikv=false --storage=s3://xxxx --s3.region=yyy --s3.provider=aws`

### 2. What did you expect to see? (Required)

backup succeeded

### 3. What did you see instead (Required)

BR clp panic

`I0525 09:38:32.972481       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [backup_ebs.go:219] ["snapshot started, restore schedule"]
I0525 09:38:32.972579       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [tso_client.go:134] ["closing tso client"]
I0525 09:38:32.972687       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [tso_dispatcher.go:375] ["[tso] stop fetching the pending tso requests due to context canceled"] [dc-location=global]
I0525 09:38:32.972775       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [tso_dispatcher.go:311] ["[tso] exit tso dispatcher"] [dc-location=global]
I0525 09:38:32.972874       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [tso_dispatcher.go:162] ["exit tso requests cancel loop"]
I0525 09:38:32.972968       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [tso_dispatcher.go:214] ["exit tso dispatcher loop"]
I0525 09:38:32.973071       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [tso_client.go:139] ["close tso client"]
I0525 09:38:32.973157       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [tso_client.go:150] ["tso client is closed"]
I0525 09:38:32.973263       9 backup.go:292] [2023/05/25 09:38:32.972 +00:00] [INFO] [pd_service_discovery.go:250] ["[pd] close pd service discovery client"]
I0525 09:38:32.973369       9 backup.go:292] [2023/05/25 09:38:32.973 +00:00] [INFO] [pd.go:210] ["closed pd http client"]
I0525 09:38:32.973739       9 backup.go:292] [2023/05/25 09:38:32.973 +00:00] [INFO] [tso_client.go:134] ["closing tso client"]
I0525 09:38:32.973954       9 backup.go:292] [2023/05/25 09:38:32.973 +00:00] [INFO] [tso_dispatcher.go:214] ["exit tso dispatcher loop"]
I0525 09:38:32.974156       9 backup.go:292] [2023/05/25 09:38:32.973 +00:00] [INFO] [tso_dispatcher.go:162] ["exit tso requests cancel loop"]
I0525 09:38:32.974323       9 backup.go:292] [2023/05/25 09:38:32.973 +00:00] [INFO] [tso_dispatcher.go:375] ["[tso] stop fetching the pending tso requests due to context canceled"] [dc-location=global]
I0525 09:38:32.974742       9 backup.go:292] [2023/05/25 09:38:32.974 +00:00] [INFO] [tso_dispatcher.go:311] ["[tso] exit tso dispatcher"] [dc-location=global]
I0525 09:38:32.975018       9 backup.go:292] [2023/05/25 09:38:32.974 +00:00] [INFO] [tso_client.go:139] ["close tso client"]
I0525 09:38:32.975140       9 backup.go:292] [2023/05/25 09:38:32.974 +00:00] [INFO] [tso_client.go:150] ["tso client is closed"]
I0525 09:38:32.975283       9 backup.go:292] [2023/05/25 09:38:32.974 +00:00] [INFO] [pd_service_discovery.go:250] ["[pd] close pd service discovery client"]
I0525 09:38:32.975301       9 backup.go:292] [2023/05/25 09:38:32.974 +00:00] [INFO] [collector.go:268] ["EBS backup failed, please check the log for details."]
I0525 09:38:32.981380       9 backup.go:292]
I0525 09:38:32.981426       9 backup.go:299] panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a33831]

goroutine 1 [running]:
[github.com/pingcap/tidb/br/pkg/task.RunBackupEBS](http://github.com/pingcap/tidb/br/pkg/task.RunBackupEBS)({0x6212770, 0xc000101900}, {0x62295a8?, 0x9067330?}, 0xc0001aee00)
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/task/backup_ebs.go:220](http://github.com/pingcap/br/br/pkg/task/backup_ebs.go:220) +0x10b1
main.runBackupCommand(0xc000bd8600, {0x59729f7, 0xb})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:41](http://github.com/pingcap/br/br/cmd/br/backup.go:41) +0x209
main.newFullBackupCommand.func1(0xc000bd8600?, {0xc000bd6680?, 0x8?, 0x8?})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:143](http://github.com/pingcap/br/br/cmd/br/backup.go:143) +0x25
[github.com/spf13/cobra.(*Command).execute](http://github.com/spf13/cobra.(*Command).execute)(0xc000bd8600, {0xc000126030, 0x8, 0x8})
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:916](http://github.com/spf13/cobra@v1.6.1/command.go:916) +0x862
[github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:1044](http://github.com/spf13/cobra@v1.6.1/command.go:1044) +0x3bd
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:968](http://github.com/spf13/cobra@v1.6.1/command.go:968)
main.main()
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/main.go:58](http://github.com/pingcap/br/br/cmd/br/main.go:58) +0x35c
E0525 09:38:32.981574       9 manager.go:345] backup cluster backup-a/fed-backup-20220525-3-dataplane-a data failed, err: cluster backup-a/fed-backup-20220525-3-dataplane-a, wait pipe message failed, errMsg panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a33831]

goroutine 1 [running]:
[github.com/pingcap/tidb/br/pkg/task.RunBackupEBS](http://github.com/pingcap/tidb/br/pkg/task.RunBackupEBS)({0x6212770, 0xc000101900}, {0x62295a8?, 0x9067330?}, 0xc0001aee00)
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/task/backup_ebs.go:220](http://github.com/pingcap/br/br/pkg/task/backup_ebs.go:220) +0x10b1
main.runBackupCommand(0xc000bd8600, {0x59729f7, 0xb})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:41](http://github.com/pingcap/br/br/cmd/br/backup.go:41) +0x209
main.newFullBackupCommand.func1(0xc000bd8600?, {0xc000bd6680?, 0x8?, 0x8?})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:143](http://github.com/pingcap/br/br/cmd/br/backup.go:143) +0x25
[github.com/spf13/cobra.(*Command).execute](http://github.com/spf13/cobra.(*Command).execute)(0xc000bd8600, {0xc000126030, 0x8, 0x8})
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:916](http://github.com/spf13/cobra@v1.6.1/command.go:916) +0x862
[github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:1044](http://github.com/spf13/cobra@v1.6.1/command.go:1044) +0x3bd
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:968](http://github.com/spf13/cobra@v1.6.1/command.go:968)
main.main()
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/main.go:58](http://github.com/pingcap/br/br/cmd/br/main.go:58) +0x35c
, err: exit status 2
I0525 09:38:32.991658       9 backup_status_updater.go:123] Backup: [backup-a/fed-backup-20220525-3-dataplane-a] updated successfully
error: cluster backup-a/fed-backup-20220525-3-dataplane-a, wait pipe message failed, errMsg panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a33831]

goroutine 1 [running]:
[github.com/pingcap/tidb/br/pkg/task.RunBackupEBS](http://github.com/pingcap/tidb/br/pkg/task.RunBackupEBS)({0x6212770, 0xc000101900}, {0x62295a8?, 0x9067330?}, 0xc0001aee00)
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/task/backup_ebs.go:220](http://github.com/pingcap/br/br/pkg/task/backup_ebs.go:220) +0x10b1
main.runBackupCommand(0xc000bd8600, {0x59729f7, 0xb})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:41](http://github.com/pingcap/br/br/cmd/br/backup.go:41) +0x209
main.newFullBackupCommand.func1(0xc000bd8600?, {0xc000bd6680?, 0x8?, 0x8?})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:143](http://github.com/pingcap/br/br/cmd/br/backup.go:143) +0x25
[github.com/spf13/cobra.(*Command).execute](http://github.com/spf13/cobra.(*Command).execute)(0xc000bd8600, {0xc000126030, 0x8, 0x8})
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:916](http://github.com/spf13/cobra@v1.6.1/command.go:916) +0x862
[github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:1044](http://github.com/spf13/cobra@v1.6.1/command.go:1044) +0x3bd
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:968](http://github.com/spf13/cobra@v1.6.1/command.go:968)
main.main()
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/main.go:58](http://github.com/pingcap/br/br/cmd/br/main.go:58) +0x35c
, err: exit status 2`

### 4. What is your TiDB version? (Required)

nightly

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Issue Number: close #44182 

Problem Summary:

### What is changed and how it works?

When `operator-paused-gc-and-scheduler=true` is set for ebs snapshot full backup, PD and GC restore function is not set but is invoked erroneously, and it caused a panic as below.  We need to avoid invoke the restore function when `SkipPauseGCAndScheduler` is turned on.

`I0525 09:38:32.981380       9 backup.go:292]
I0525 09:38:32.981426       9 backup.go:299] panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a33831]

goroutine 1 [running]:
[github.com/pingcap/tidb/br/pkg/task.RunBackupEBS](http://github.com/pingcap/tidb/br/pkg/task.RunBackupEBS)({0x6212770, 0xc000101900}, {0x62295a8?, 0x9067330?}, 0xc0001aee00)
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/task/backup_ebs.go:220](http://github.com/pingcap/br/br/pkg/task/backup_ebs.go:220) +0x10b1
main.runBackupCommand(0xc000bd8600, {0x59729f7, 0xb})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:41](http://github.com/pingcap/br/br/cmd/br/backup.go:41) +0x209
main.newFullBackupCommand.func1(0xc000bd8600?, {0xc000bd6680?, 0x8?, 0x8?})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/cmd/br/backup.go:143](http://github.com/pingcap/br/br/cmd/br/backup.go:143) +0x25
[github.com/spf13/cobra.(*Command).execute](http://github.com/spf13/cobra.(*Command).execute)(0xc000bd8600, {0xc000126030, 0x8, 0x8})
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:916](http://github.com/spf13/cobra@v1.6.1/command.go:916) +0x862
[github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300)](http://github.com/spf13/cobra.(*Command).ExecuteC(0xc00078c300))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:1044](http://github.com/spf13/cobra@v1.6.1/command.go:1044) +0x3bd
[github.com/spf13/cobra.(*Command).Execute(...)](http://github.com/spf13/cobra.(*Command).Execute(...))
	/go/pkg/mod/[github.com/spf13/cobra@v1.6.1/command.go:968](http://github.com/spf13/cobra@v1.6.1/command.go:968)
main.main()`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
Use the EBS snapshot backup operator to verify the panic is gone.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/task/backup_ebs.go [hunk 1]
```diff
@@ -216,12 +216,14 @@ func RunBackupEBS(c context.Context, g glue.Glue, cfg *BackupConfig) error {
 			return errors.Trace(err)
 		}
 
-		log.Info("snapshot started, restore schedule")
-		if restoreE := restoreFunc(ctx); restoreE != nil {
-			log.Warn("failed to restore removed schedulers, you may need to restore them manually", zap.Error(restoreE))
-		} else {
-			// Clear the restore func, so we won't execute it many times.
-			restoreFunc = nil
+		if !cfg.SkipPauseGCAndScheduler {
```
Comment (YuJuncen) [inline br/pkg/task/backup_ebs.go:219]: Perhaps directly `if restoreFunc != nil`

**Review by YuJuncen — APPROVED** [review]
