### PR TITLE
test: fix the flaky test TestAuditPluginRetrying

### LINKED ISSUE #65113: Fix the flaky test `TestAuditPluginRetrying`
## Enhancement

This test is not stable, let me fix it 🍻

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #65113

Problem Summary:

### What changed and how does it work?

Add an internal retry for the trigger of `retry` mechanism. Sometimes we are too lucky to actually trigger the retry.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Use the following command to execute this test for multiple times:

```
go test -failfast -timeout 300000s  -run 'TestAuditPluginRetrying' -count=1000 -v ./pkg/server/tests/commontest
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/tests/commontest/tidb_test.go [hunk 1]
```diff
@@ -3692,23 +3692,28 @@ func TestAuditPluginRetrying(t *testing.T) {
...
+			var wg sync.WaitGroup
+			for range concurrency {
+				wg.Add(1)
+				conn, err := db.Conn(context.Background())
 				require.NoError(t, err)
-			}()
-		}
-		wg.Wait()
+				go func() {
+					defer wg.Done()
```
Comment (lance6716) [inline pkg/server/tests/commontest/tidb_test.go]: note that we can use https://pkg.go.dev/sync#WaitGroup.Go now. Don't need to write wg.Add, go func(), defer wg.Done()

Comment (YangKeao) [reply pkg/server/tests/commontest/tidb_test.go]: Done. I've modified all usage of `wg.Add(..)` in this test into `wg.Go()`.

File: pkg/server/tests/commontest/tidb_test.go [hunk 2]
```diff
@@ -3745,9 +3748,8 @@ func TestAuditPluginRetrying(t *testing.T) {
 
 		testResults = testResults[:0]
 		var wg sync.WaitGroup
-		wg.Add(2)
 		// Transaction 1
-		go func() {
+		wg.Go(func() {
 			defer wg.Done()
```
Comment (lance6716) [inline pkg/server/tests/commontest/tidb_test.go]: I remember it wil internally call `wg.Done()`. so we should not repeat it. (please check source code)

Comment (YangKeao) [reply pkg/server/tests/commontest/tidb_test.go]: Yeah. It's a mistake by myself. I've deleted the `wg.Done()` for previous function but forgot this one :facepalm: .

**Review by hawkingrei — APPROVED** [review]
