### PR TITLE
ddl: add the `not` expression check when creating a partition table

### LINKED ISSUE #17808: P1-[4.0 bug hunting]-[SQL Plan Management]-Server panic for NATURAL LEFT JOIN on partitioned table
Bug Hunter issue tidb-challenge-program/bug-hunting-issue#14

---

Consider the following statements:

```sql
CREATE TABLE t0(c0 NUMERIC PRIMARY KEY);
CREATE TABLE t1(c0 INT) PARTITION BY HASH(NOT c0) PARTITIONS 2;
SELECT * FROM t1 NATURAL LEFT JOIN t0; -- ERROR 2013 (HY000): Lost connection to MySQL server during query
```
When executing these statements, the connection to the server drops:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.7.25-TiDB- TiDB Server (Apache License 2.0), MySQL 5.7 compatible

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE TABLE t0(c0 NUMERIC PRIMARY KEY);
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE t1(c0 INT) PARTITION BY HASH(NOT c0) PARTITIONS 2;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT * FROM t1 NATURAL LEFT JOIN t0;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
The server logs the following stack trace:
```
[2020/04/15 10:31:31.971 +02:00] [ERROR] [conn.go:658] ["connection running loop panic"] [conn=5] [lastSQL="SELECT * FROM t1 NATURAL LEFT JOIN t0"] [err="runtime error: index out of range [-1]"] [stack="goroutine 5125 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x2cdd5e0, 0xc0112f40f0, 0xc0016735f0)\n\t/tidb-4.0.0-rc/server/conn.go:656 +0xee\npanic(0x27c2a80, 0xc0113c3b40)\n\t/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/planner/core.(*DataSource).PruneColumns(0xc00061d860, 0xc012097498, 0x1, 0x1, 0x0, 0x0)\n\t/tidb-4.0.0-rc/planner/core/rule_column_pruning.go:227 +0xab1\ngithub.com/pingcap/tidb/planner/core.(*LogicalUnionAll).PruneColumns(0xc011398f30, 0xc012097498, 0x1, 0x1, 0x1, 0x4)\n\t/tidb-4.0.0-rc/planner/core/rule_column_pruning.go:190 +0x36f\ngithub.com/pingcap/tidb/planner/core.(*LogicalProjection).PruneColumns(0xc001183550, 0xc012097490, 0x1, 0x1, 0x1, 0x1)\n\t/tidb-4.0.0-rc/planner/core/rule_column_pruning.go:76 +0x4f8\ngithub.com/pingcap/tidb/planner/core.(*LogicalProjection).PruneColumns(0xc0011831e0, 0xc0120973d0, 0x1, 0x1, 0x2719a20, 0xc001152960)\n\t/tidb-4.0.0-rc/planner/core/rule_column_pruning.go:76 +0x4f8\ngithub.com/pingcap/tidb/planner/core.(*columnPruner).optimize(0x428f240, 0x2cdd5e0, 0xc0112f40f0, 0x2d149a0, 0xc0011831e0, 0x2d149a0, 0xc0011831e0, 0x0, 0x0)\n\t/tidb-4.0.0-rc/planner/core/rule_column_pruning.go:31 +0x6b\ngithub.com/pingcap/tidb/planner/core.logicalOptimize(0x2cdd5e0, 0xc0112f40f0, 0x23a2, 0x2d149a0, 0xc0011831e0, 0xeda9aa, 0x282ca80, 0x2901820, 0x2c9a101)\n\t/tidb-4.0.0-rc/planner/core/optimizer.go:155 +0x116\ngithub.com/pingcap/tidb/planner/core.DoOptimize(0x2cdd5e0, 0xc0112f40f0, 0x2d15ca0, 0xc0120e3900, 0x23a2, 0x2d149a0, 0xc0011831e0, 0x0, 0x0, 0x0, ...)\n\t/tidb-4.0.0-rc/planner/core/optimizer.go:124 +0x60\ngithub.com/pingcap/tidb/planner.optimize(0x2cdd5e0, 0xc0112f40f0, 0x2d15ca0, 0xc0120e3900, 0x2cdf1a0, 0xc0019c8340, 0x2d0ade0, 0xc01206e870, 0x0, 0x0, ...)\n\t/tidb-4.0.0-rc/planner/optimize.go:189 +0x5a9\ngithub.com/pingcap/tidb/planner.Optimize(0x2cdd5e0, 0xc0112f40f0, 0x2d15ca0, 0xc0120e3900, 0x2cdf1a0, 0xc0019c8340, 0x2d0ade0, 0xc01206e870, 0x0, 0x0, ...)\n\t/tidb-4.0.0-rc/planner/optimize.go:63 +0x28f\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile(0xc000ae4dc8, 0x2cdd5e0, 0xc0112f40f0, 0x2ce4a20, 0xc0019c8340, 0x0, 0x0, 0x0)\n\t/tidb-4.0.0-rc/executor/compiler.go:61 +0x253\ngithub.com/pingcap/tidb/session.(*session).execute(0xc0120e3900, 0x2cdd5e0, 0xc0112f40f0, 0xc0011d90e1, 0x25, 0xc000b39ea0, 0x0, 0x0, 0xc000ae5178, 0x23f610a)\n\t/tidb-4.0.0-rc/session/session.go:1135 +0x5cf\ngithub.com/pingcap/tidb/session.(*session).Execute(0xc0120e3900, 0x2cdd5e0, 0xc0112f40f0, 0xc0011d90e1, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/tidb-4.0.0-rc/session/session.go:1089 +0xdb\ngithub.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc0112f4480, 0x2cdd5e0, 0xc0112f40f0, 0xc0011d90e1, 0x25, 0xeff1e1, 0x2a06fc8, 0xc000ae5278, 0xc000ae5268, 0xf9f572)\n\t/tidb-4.0.0-rc/server/driver_tidb.go:248 +0x7c\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc0016735f0, 0x2cdd5e0, 0xc0112f40f0, 0xc0011d90e1, 0x25, 0x0, 0x0)\n\t/tidb-4.0.0-rc/server/conn.go:1256 +0x91\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc0016735f0, 0x2cdd5e0, 0xc0112f40f0, 0xc0011d90e1, 0x26, 0x25, 0x0, 0x0)\n\t/tidb-4.0.0-rc/server/conn.go:897 +0x5e2\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc0016735f0, 0x2cdd5e0, 0xc0112f40f0)\n\t/tidb-4.0.0-rc/server/conn.go:711 +0x27c\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc000ccb290, 0xc0016735f0)\n\t/tidb-4.0.0-rc/server/server.go:415 +0xaf9\ncreated by github.com/pingcap"]
```
I can reproduce this both on the RC and the latest master (commit 7e71069ffa6052b497eaaaa2c3863bff4fe0ef3f).

Environment:
```
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: 
Git Commit Hash: 
Git Branch: 
UTC Build Time: 2020-04-15 06:06:10
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
The classification assigns a P0 to `Process crash, etc.`, which is why I propose this severity level.

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close #17808 

Problem Summary:
When TiDB uses `HASH(not c)` as the partition condition, it will convert `not c` to `UnaryOperationExpr` instead of `FuncCallExpr` to check whether the expression is valid.

### What is changed and how it works?

What's Changed:
When we use `checkPartitionExprArgs` for checking whether the expression is valid. , we add `UnaryOperationExpr` into consideration. And if the operand is not, we will report an error.

Before this PR:
```
mysql> CREATE TABLE t1(c0 INT) PARTITION BY HASH((NOT c0)) PARTITIONS 2;
Query OK, 0 rows affected (0.00 sec)
```

After this PR:
```
mysql> CREATE TABLE t1(c0 INT) PARTITION BY HASH((NOT c0)) PARTITIONS 2;
ERROR 1564 (HY000): This partition function is not allowed
```

How it Works:

Tests 

- Unit test
- Integration test

### Release note 

- add the `not` expression check when creating a partition table

### CODE REVIEW

File: ddl/partition.go [hunk 1]
```diff
@@ -1690,42 +1690,47 @@ func checkPartitionExprFuncAllowed(_ sessionctx.Context, _ *model.TableInfo, e a
...
-		return errors.Trace(checkResultOK(hasTimestampArgs(tblInfo, expr)))
-	case ast.FromDays:
-		if err := checkResultOK(hasDateArgs(tblInfo, expr)); err != nil {
-			return errors.Trace(err)
-		}
-		return errors.Trace(checkResultOK(hasTimeArgs(tblInfo, expr)))
-	case ast.Extract:
-		switch expr.Args[0].(*ast.TimeUnitExpr).Unit {
-		case ast.TimeUnitYear, ast.TimeUnitYearMonth, ast.TimeUnitQuarter, ast.TimeUnitMonth, ast.TimeUnitDay:
+	switch expr := e.(type) {
```
Comment (xiongjiwei) [inline ddl/partition.go:1693]: do not change here, this function is used to the `expression args`. you should put `opcode.Not2` and `opcode.Not` to function `checkPartitionExprAllowed`

Comment (Reminiscent) [reply ddl/partition.go:1676]: > do not change here, this function is used to check the `function's` args. you should put `opcode.Not2` and `opcode.Not` to function `checkPartitionExprAllowed`

@xiongjiwei Update. PTAL~

Comment (xiongjiwei) [reply ddl/partition.go:1676]: we can combine `checkPartitionExprFuncAllowed` and `checkPartitionExprAllowed`. I forgot why I split it into two functions. And make `allowedFuncMap` a global variable in this file to avoid memory allocation every time.

File: ddl/db_partition_test.go [hunk 2]
```diff
@@ -3156,3 +3156,16 @@ func (s *testIntegrationSuite7) TestAddPartitionForTableWithWrongType(c *C) {
 	c.Assert(err, NotNil)
 	c.Assert(ddl.ErrWrongTypeColumnValue.Equal(err), IsTrue)
 }
+
+func (s *testIntegrationSuite5) TestBuildPartitionWithExpr(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
```
Comment (xiongjiwei) [inline ddl/db_partition_test.go:3161]: there is a test `TestCreateTableWithHashPartition`, we can put the test into it.  BTW, if we just test expression in partition, we can also use the `list` or `range` partition to test it since they are `table drive` test.

File: ddl/partition.go [hunk 3]
```diff
@@ -1664,31 +1664,13 @@ func checkPartitionExprAllowed(_ sessionctx.Context, _ *model.TableInfo, e ast.E
...
-		if v.Op == opcode.BitNeg {
+		switch v.Op {
+		case opcode.BitNeg, opcode.Not, opcode.Not2:
 			return errors.Trace(ErrPartitionFunctionIsNotAllowed)
 		}
 	}
 	return nil
 }
-
-func checkPartitionExprFuncAllowed(_ sessionctx.Context, _ *model.TableInfo, e ast.ExprNode) error {
```
Comment (xiongjiwei) [inline ddl/partition.go:1674]: this check is needed because only these functions are allowed to be partition expression. please add them to function `checkPartitionExprAllowed`

**Comment by Reminiscent** [comment]
@xiongjiwei @wjhuang2016 @tiancaiamao All tests passed. PTAL

**Comment by xiongjiwei** [comment]
a white-list of allowed expression of partition table will be much easier to compatible with MySQL because MySQL uses white-list too. we will always not sure whether we miss some expressions check if we use black-list.

**Comment by Reminiscent** [comment]
@wjhuang2016 @xiongjiwei Do you have some ideas on why the randgen tests in `common-test` and `integration-common-test` will fail? It seems that this PR will not affect the failed test.

File: ddl/partition.go [hunk 4]
```diff
@@ -1707,37 +1706,22 @@ func (p *partitionExprChecker) extractColumns(_ sessionctx.Context, _ *model.Tab
...
-	}
-	allowedFuncMap := map[string]struct{}{
-		ast.ToDays: {}, ast.ToSeconds: {}, ast.DayOfMonth: {}, ast.Month: {}, ast.DayOfYear: {},
-		ast.Quarter: {}, ast.YearWeek: {}, ast.Year: {}, ast.Weekday: {}, ast.DayOfWeek: {}, ast.Day: {},
-		ast.Hour: {}, ast.Minute: {}, ast.Second: {}, ast.TimeToSec: {}, ast.MicroSecond: {},
-		ast.UnixTimestamp: {}, ast.FromDays: {}, ast.Extract: {}, ast.Abs: {}, ast.Ceiling: {},
-		ast.DateDiff: {}, ast.Floor: {}, ast.Mod: {},
-	}
-	if _, ok := allowedFuncMap[expr.FnName.L]; ok {
+	case *ast.FuncCastExpr, *ast.CaseExpr, *ast.SubqueryExpr, *ast.WindowFuncExpr, *ast.RowExpr, *ast.DefaultExpr, *ast.ValuesExpr,
```
Comment (xiongjiwei) [inline ddl/partition.go:1721]: we should explicitly list the `expr` which is allowed in partition expression. Although there are many `expr`, only a few of them are allowed.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by xiongjiwei — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
