### PR TITLE
planner: fix index merge doesn't take effect when using prefix key

### LINKED ISSUE #16407: Index merge doesn't take effect when using prefix key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
```
create table t(a int,b char(100),key(a),key(b(10));
desc select /*+ use_index_merge(t) */ * from t where a=10 or b="x";
```
### 2. What did you expect to see?
use_index_merge takes effect
### 3. What did you see instead?
```
+-------------------------+----------+-----------+---------------+-------------------------------------+
| id                      | estRows  | task      | access object | operator info                       |
+-------------------------+----------+-----------+---------------+-------------------------------------+
| TableReader_7           | 8000.00  | root      |               | data:Selection_6                    |
| └─Selection_6           | 8000.00  | cop[tikv] |               | or(eq(d1.t.a, 10), eq(d1.t.b, "x")) |
|   └─TableFullScan_5     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo      |
+-------------------------+----------+-----------+---------------+-------------------------------------+
3 rows in set, 1 warning (0.01 sec)
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Release Version: v4.0.0-rc-33-gd69868961
Git Commit Hash: d69868961361126d4788b68fd6cd597adb3ef66c
Git Branch: release-4.0
UTC Build Time: 2020-04-15 02:59:00
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by tangwz**
### What problem does this PR solve?

Issue Number: close #16407 

Problem Summary:

Index merge doesn't take effect when using prefix key.

### What is changed and how it works?

The condition `tableFilter` is not empty is too strict.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- None

### Release note 

- None

### CODE REVIEW

File: planner/core/stats.go [hunk 1]
```diff
@@ -549,6 +541,12 @@ func (ds *DataSource) buildIndexMergeOrPath(partialPaths []*util.AccessPath, cur
 	indexMergePath := &util.AccessPath{PartialIndexPaths: partialPaths}
 	indexMergePath.TableFilters = append(indexMergePath.TableFilters, ds.pushedDownConds[:current]...)
 	indexMergePath.TableFilters = append(indexMergePath.TableFilters, ds.pushedDownConds[current+1:]...)
+	for _, path := range partialPaths {
+		if len(path.TableFilters) > 0 {
+			indexMergePath.TableFilters = append(indexMergePath.TableFilters, ds.pushedDownConds[current])
+			break
+		}
+	}
```
Comment (eurekaka) [inline planner/core/stats.go:549]: Theoretically, we should update the estimated row count of `TableRowIDScan` and `Selection` for this index merge plan as well, though it is pretty hard to figure out the row count. See also function `buildIndexMergeTableScan`. @time-and-fate any thoughts?

File: planner/core/integration_test.go [hunk 2]
```diff
@@ -1229,14 +1229,34 @@ func (s *testIntegrationSerialSuite) TestIssue16837(c *C) {
...
+		"  ├─IndexRangeScan_5(Build) 10.00 cop[tikv] table:t, index:idx_ab(a, b) range:[1,1], keep order:false, stats:pseudo",
+		"  ├─IndexRangeScan_6(Build) 1.00 cop[tikv] table:t, index:c(c) range:[1,1], keep order:false, stats:pseudo",
+		"  └─Selection_8(Probe) 0.01 cop[tikv]  or(eq(test.t.a, 1), and(eq(test.t.e, 1), eq(test.t.c, 1)))",
+		"    └─TableRowIDScan_7 10.00 cop[tikv] table:t keep order:false, stats:pseudo"))
+	tk.MustQuery("show warnings").Check(testkit.Rows())
 	tk.MustExec("insert into t values (2, 1, 1, 1, 2)")
 	tk.MustQuery("select /*+ use_index_merge(t,c,idx_ab) */ * from t where a = 1 or (e = 1 and c = 1)").Check(testkit.Rows())
 }
 
+func (s *testIntegrationSerialSuite) TestIssue16407(c *C) {
```
Comment (qw4990) [inline planner/core/integration_test.go:1243]: How about adding one more case:
```
create table t (a int, b int, unique key(a), unique key(b));
desc select /*+ use_index_merge(t) */ * from t where a =1 or (b=1 and b+2>1);
desc select /*+ use_index_merge(t) */ * from t where a =1 or (b=1 and mod(b, 3)=1);
```

File: planner/core/stats.go (hunk 1 above)
Comment (time-and-fate) [reply planner/core/stats.go:549]: I think we can use all `partialPath.AccessConds` instead of currently the entire DNF condition to calculate selectivity in `generateIndexMergeOrPaths()`. 
As for the `Selection` above the `TableRowIDScan`, I think we can choose not to modify it, but I wonder if using `ds.stats` directly instead of the current `selectivity(tableFilters) * totalRowCount`  could be better in `buildIndexMergeTableScan()`.

File: planner/core/integration_test.go (hunk 2 above)
Comment (tangwz) [reply planner/core/integration_test.go:1264]: Thanks. I agree with you.
@qw4990  PTAL.

File: planner/core/stats.go (hunk 1 above)
Comment (qw4990) [reply planner/core/stats.go:555]: Updated, PTAL. @time-and-fate @eurekaka

File: planner/core/integration_test.go [hunk 3]
```diff
@@ -1229,14 +1229,55 @@ func (s *testIntegrationSerialSuite) TestIssue16837(c *C) {
...
+		"Projection_4 1.80 root  test.t.a, test.t.b",
+		"└─IndexMerge_9 2.00 root  ",
+		"  ├─IndexRangeScan_5(Build) 1.00 cop[tikv] table:t, index:a(a) range:[1,1], keep order:false, stats:pseudo",
+		"  ├─Selection_7(Build) 0.80 cop[tikv]  gt(plus(test.t.b, 2), 1)",
+		"  │ └─IndexRangeScan_6 1.00 cop[tikv] table:t, index:b(b) range:[1,1], keep order:false, stats:pseudo",
+		"  └─TableRowIDScan_8(Probe) 2.00 cop[tikv] table:t keep order:false, stats:pseudo"))
+	tk.MustQuery("show warnings").Check(testkit.Rows())
+
+	tk.MustQuery("desc select /*+ use_index_merge(t) */ * from t where a =1 or (b=1 and mod(b, 3)=1)").Check(testkit.Rows(
+		"Selection_5 8000.00 root  or(eq(test.t.a, 1), and(eq(test.t.b, 1), 1))",
```
Comment (eurekaka) [inline planner/core/integration_test.go:1258]: Why IndexMerge is not chosen for this case?

Comment (qw4990) [reply planner/core/integration_test.go:1258]: Because `mod` cannot be pushed down to TiKV, it let `ds.pushedDownConds` empty and then `IndexMerge` is eliminated by this [`isPossibleIdxMerge` check](https://github.com/pingcap/tidb/blob/master/planner/core/stats.go#L311).
I have updated this test to use another function `length`, which can avoid this problem. @eurekaka

**Review by eurekaka — COMMENTED** [review]
LGTM

File: planner/core/stats.go [hunk 4]
```diff
@@ -549,6 +547,12 @@ func (ds *DataSource) buildIndexMergeOrPath(partialPaths []*util.AccessPath, cur
 	indexMergePath := &util.AccessPath{PartialIndexPaths: partialPaths}
 	indexMergePath.TableFilters = append(indexMergePath.TableFilters, ds.pushedDownConds[:current]...)
 	indexMergePath.TableFilters = append(indexMergePath.TableFilters, ds.pushedDownConds[current+1:]...)
+	for _, path := range partialPaths {
+		if len(path.TableFilters) > 0 {
+			indexMergePath.TableFilters = append(indexMergePath.TableFilters, ds.pushedDownConds[current])
```
Comment (time-and-fate) [inline planner/core/stats.go:552]: Should we append the entire DNF in the `pushedDownConds` or just the `path.TableFilters`?

Comment (qw4990) [reply planner/core/stats.go:552]: `path.TableFilters` is enough, since `ds.pushedDownConds[current] = path.TableFilters + path.AccessConds` and `path.AccessConds` will take effect when scan. @time-and-fate

**Comment by time-and-fate** [comment]
LGTM

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by zz-jason** [comment]
it's better to cherry-pick to release-4.0 as well.
