### PR TITLE
*: support load data for table with generated columns

### LINKED ISSUE #39885: load data with generated column will report an error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t(a int, b int generated ALWAYS AS (a+1));
Query OK, 0 rows affected (0.06 sec)

mysql> insert into t(a) values (1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t(a) values (2);
Query OK, 1 row affected (0.00 sec)

mysql> load data infile '/tmp/1.sql' into table t;
ERROR 8067 (HY000): Load data: unmatched columns
```

### 2. What did you expect to see? (Required)

success

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #39885

Problem Summary:

### What is changed and how it works?

Dump a table with generated columns, and load it back, it should work!

In the field mapping step, keep the generated column.
And in `parserData2TableData`, ignore the parserData, just set the generated column data to NULL and let `getRow` fill it.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: server/server_test.go [hunk 1]
```diff
@@ -591,6 +592,69 @@ func (cli *testServerClient) runTestLoadDataAutoRandomWithSpecialTerm(t *testing
...
+		require.NoError(t, rows.Close())
+
+		// Specify the column b
+		dbt.MustExec(`delete from t_gen2`)
+		dbt.MustExec(fmt.Sprintf("load data local infile %q into table t_gen2 (b)", tmpFileName))
+		rows = dbt.MustQuery("select * from t_gen2")
+		cli.checkRows(t, rows, "2 1", "3 2")
+		require.NoError(t, rows.Close())
+		// TODO: should get warning here.
+		// rows = dbt.MustQuery("show warnings")
```
Comment (lance6716) [inline server/server_test.go:637]: I remeber I have implemented warnings. Can you turn on these tests?

**Comment by tiancaiamao** [comment]
/test check-dev2
CI is unstable but not by the change itself.
https://github.com/pingcap/tidb/pull/43139

File: server/server_test.go (hunk 1 above)
Comment (bb7133) [reply server/server_test.go:637]: +1, I confirmed that the warning is there. You could just uncomment them and move it before checking the result by `select`?

File: server/server_test.go [hunk 2]
```diff
@@ -591,6 +592,69 @@ func (cli *testServerClient) runTestLoadDataAutoRandomWithSpecialTerm(t *testing
...
+		// 	"Warning 1262 Row 2 was truncated; it contained more data than there were input columns")
+		// require.NoError(t, rows.Close())
+
+		// Specify the column a
+		dbt.MustExec(`delete from t_gen2`)
+		dbt.MustExec(fmt.Sprintf("load data local infile %q into table t_gen2 (a)", tmpFileName))
+		rows = dbt.MustQuery("select * from t_gen2")
+		cli.checkRows(t, rows, "<nil> <nil>", "<nil> <nil>")
+		require.NoError(t, rows.Close())
+		// TODO: should get warning here.
```
Comment (bb7133) [inline server/server_test.go:649]: Ditto.

**Review by bb7133 — APPROVED** [review]
LGTM

File: server/server_test.go [hunk 3]
```diff
@@ -591,6 +592,67 @@ func (cli *testServerClient) runTestLoadDataAutoRandomWithSpecialTerm(t *testing
 	})
 }
 
+func (cli *testServerClient) runTestLoadDataForGeneratedColumns(t *testing.T) {
```
Comment (D3Hunter) [inline server/server_test.go:595]: please move those test to `executer/loaddatatest`

Comment (tiancaiamao) [reply server/server_test.go:595]: > please move those test to `executer/loaddatatest`

executor/loaddatatest does not support this kind of test.
Because the load data protocol is not the normal `handleQuery`, this test can't be done with `testkit.NewTestkit()`
In server package, the testkit is much like a integration test which handles the complete protocol layer.

@D3Hunter

File: executor/loaddatatest/load_data_test.go [hunk 4]
```diff
@@ -498,3 +501,19 @@ func TestLoadDataIntoPartitionedTable(t *testing.T) {
...
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec("create table t_gen (a int, b int generated ALWAYS AS (a+1));")
+	tk.MustExec("insert into t_gen (a) values (1);")
+	tk.MustExec("insert into t_gen (a) values (2);")
+	tmpFileName := path.Join(os.TempDir(), "tidb_test_loaddata_generated_column.txt")
+	tk.MustExec(fmt.Sprintf("select * from t_gen into outfile '%s'", tmpFileName))
+	defer os.Remove(tmpFileName)
+	tk.MustExec("delete from t_gen")
+	tk.MustExec(fmt.Sprintf("load data infile '%s' into table t_gen", tmpFileName))
```
Comment (D3Hunter) [inline executor/loaddatatest/load_data_test.go:516]: this won't run(load from server disk)

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: executor/loaddatatest/load_data_test.go [hunk 5]
```diff
@@ -16,6 +16,9 @@ package loaddatatest
 
 import (
 	"context"
+	"fmt"
+	"os"
+	"path"
```
Comment (D3Hunter) [inline executor/loaddatatest/load_data_test.go:21]: may cause lint err

**Review by D3Hunter — APPROVED** [review]
