### PR TITLE
ddl: clean up DDL backfill metrics when they are done

### LINKED ISSUE #65860: too many ddl metrics
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

An user do a lot ddl operation. 
Some of the metrics use {db}+{table}+{index} as label type, so there are so many metrics 

curl http://127.0.0.1:10080/metrics eventually timeout and prometheus can not collect metrics from the DDL leader tidb.

Image

### 2. What did you expect to see? (Required)

clean up useless metrics

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #65860

Problem Summary:

Prior to this fix, we never clean up the DDL backfill progress related metrics.
We use {db}-{table}-{idx} naming pattern for the labels, so they explode after a lot DDL operations.
Result in toooo many metrics for http://127.0.0.1:10080/metrics, and finally prometheus timeout to fetch the metrics.

### What changed and how does it work?

After the DDL operation done, those metrics are useless, we should just keep it in prometheus database, but remove them from tidb memory.

-  Introduce `cleanupBackfillMetrics` function to cleanup the backfill metrics (which is called by `cleanupDDLReorgHandles`)
- Code refactor for handling reorg Action type to metrics label. Before this commit, generate label is only used by updateBackfillProgress, but now both update and clean metrics need the same label, so the refactor is introduced 
- rename `getTableTotalCount` to `getTableEstimatedCount`, because the old name is misleading ... backfill progress is calculated based on the estimated value, from user's env, I see a lot value 0

Known drawback: DDL reorg progress update is called in tidb DDL owner, so it might happen that one tidb node is once DDL owner and update the metrics, and later, the owner transfer to some other tidb node. The metrics clean up finally happen on the latest DDL owner, so in such case it could be misleading... 

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

After the fix, the metrics is not **continuous**, the value disappear suddenly.
But that is expected. It is removed from tidb-server's memory.

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented unbounded backfill metric growth by ensuring metrics are cleaned up when DDL/backfill operations complete.
  * Improved backfill progress computation to avoid reporting spurious progress when row estimates are not meaningful.

* **Chores**
  * Backfill metrics are now tracked and keyed by physical table ID for accurate aggregation and lifecycle management.
  * Metric cleanup is invoked when tables/partitions become fully public and during reorg/cleanup flows.

* **Tests**
  * Added unit tests validating metric registration, partitioned-table handling, idempotent cleanup, and post-cleanup state.

### CODE REVIEW

**Comment by wjhuang2016** [comment]
@fzzf678 PTAL

**Comment by joechenrh** [comment]
Feel free to open previous PR. But remember to consider DXF scenarios, where non-owner node also create metrics.

**Comment by tiancaiamao** [comment]
PTAL @wjhuang2016 @bb7133

**Review by fzzf678 — APPROVED** [review]

File: pkg/ddl/backfill_metrics.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+	if rInfo == nil {
+		return 0
+	}
+	if !isPartitionReorgDDL(rInfo.Type) {
+		return rInfo.PhysicalTableID
+	}
+	if rInfo.Job == nil {
+		return rInfo.PhysicalTableID
+	}
+	if isPartitionReorgBackfillMetricLabel(label) {
```
Comment (zimulala) [inline pkg/ddl/backfill_metrics.go:70]: Could this also handle `cleanup_idx_rate` for `DROP PARTITION` / `TRUNCATE PARTITION` with global indexes?

Those paths call `cleanGlobalIndexEntriesFromDroppedPartitions()` and then `newCleanUpIndexWorker(..., metrics.LblCleanupIdxRate, ...)`, so the metric may be registered under the old partition physical ID. However, the new cleanup path clears `job.TableID` and the current `Partition.Definitions`; after drop/truncate, the old partition ID is no longer in `Definitions`, so the metric may be left behind.

Could we either key this cleanup metric by the logical table ID for these partition DDLs, or explicitly clear the old dropped/truncated partition IDs?

Comment (tiancaiamao) [reply pkg/ddl/backfill_metrics.go:70]: I've change it to logical table ID now @zimulala

**Review by zimulala — APPROVED** [review]
