### PR TITLE
ddl, lightning: support detecting duplicate keys in different batch

### LINKED ISSUE #40698: Data inconsistent after adding unique index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table t;
create table t (a int primary key, b int);
insert into t values (1, 1), (10000, 1);
split table t by (5000);
alter table t add unique index idx(b);
admin check table t;
```

### 2. What did you expect to see? (Required)

```
mysql> alter table t add unique index idx(b);
ERROR 1062 (23000): Duplicate entry '1' for key 't.idx'
```

### 3. What did you see instead (Required)

```
mysql> alter table t add unique index idx(b);
admin check table t;
Query OK, 0 rows affected (1.59 sec)

mysql> admin check table t;
ERROR 8223 (HY000): data inconsistency in table: t, index: idx, handle: 1, index-values:"handle: 10000, values: [KindInt64 1]" != record-values:"handle: 1, values: [KindInt64 1]"
```

### 4. What is your TiDB version? (Required)

1f44d20

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #40698

Problem Summary: Previously, we only check if the key is duplicated in the same batch.

### What is changed and how it works?

This PR supports returning a duplicate key error when importing with the lightning.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/config/config.go [hunk 1]
```diff
@@ -384,6 +384,9 @@ const (
 	// DupeResAlgRemove records all duplicate records like the 'record' algorithm and remove all information related to the
 	// duplicated rows. Users need to analyze the lightning_task_info.conflict_error_v1 table to add back the correct rows.
 	DupeResAlgRemove
+
+	// DupeResAlgErr reports an error and stops the import process.
+	DupeResAlgErr
```
Comment (gozssky) [inline br/pkg/lightning/config/config.go:389]: Please add a comment that this value is for internal use only.

**Review by gozssky — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by wjhuang2016 — APPROVED** [review]
