### PR TITLE
Makefile: add staticcheck

### LINKED ISSUE #13456: staticcheck report some errors
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
run
```
GO111MODULE=on staticcheck ./...
```

2. What did you expect to see?
No output

3. What did you see instead?
```
cmd/ddltest/random.go:21:6: func randomInt is unused (U1000)
cmd/ddltest/random.go:25:6: func randomIntn is unused (U1000)
cmd/ddltest/random.go:29:6: func randomFloat is unused (U1000)
cmd/ddltest/random.go:33:6: func randomString is unused (U1000)
cmd/ddltest/random.go:48:6: func randomNum is unused (U1000)
cmd/ddltest/random.go:66:6: func randomFloat64 is unused (U1000)
cmd/ddltest/random.go:78:6: func randomBool is unused (U1000)
config/config.go:154:9: assigning the result of this type assertion to a variable (switch v := v.(type)) could eliminate the following type assertions:
	/Users/zhouqiang/go/src/github.com/pingcap/tidb/config/config.go:156:27 (S1034)
config/config.go:635:5: no value of type uint is less than 0 (SA4003)
kv/memdb_buffer.go:31:2: field bufferLenLimit is unused (U1000)
owner/fail_test.go:92:38: grpc.ErrClientConnClosing is deprecated: this error should not be relied upon by users; use the status code of Canceled instead.  (SA1019)
owner/fail_test.go:110:38: grpc.ErrClientConnClosing is deprecated: this error should not be relied upon by users; use the status code of Canceled instead.  (SA1019)
owner/manager.go:379:26: grpc.ErrClientConnClosing is deprecated: this error should not be relied upon by users; use the status code of Canceled instead.  (SA1019)
store/tikv/oracle/oracles/export_test.go:36:6: func ClearOracleHook is unused (U1000)
types/convert_test.go:958:33: should use make(map[string]interface{}) instead (S1019)
types/datum.go:1662:17: func (*Datum).convergeType is unused (U1000)
types/export_test.go:17:5: var CheckTimestampTypeForTest is unused (U1000)
types/json/binary.go:360:22: func BinaryJSON.marshalValueEntryTo is unused (U1000)
types/time.go:2255:5: var weekdayAbbrev is unused (U1000)
types/time.go:2495:5: var twoDigitRegex is unused (U1000)
types/time.go:2505:6: func parseTwoNumeric is unused (U1000)
types/time.go:2619:6: func abbreviatedWeekday is unused (U1000)
types/time.go:2665:6: func dayOfMonthWithSuffix is unused (U1000)
types/time.go:2674:6: func parseOrdinalNumbers is unused (U1000)
util/chunk/codec.go:296:62: invalid operation: shift count bitOffset (variable of type int) must be unsigned integer (compile)
util/encrypt/aes.go:55:2: redundant return statement (S1023)
util/encrypt/crypt.go:91:21: func (*sqlCrypt).reinit is unused (U1000)
util/kvcache/simple_lru.go:51:5: no value of type uint is less than 0 (SA4003)
util/kvcache/simple_lru.go:93:5: no value of type uint64 is less than 0 (SA4003)
util/mvmap/fnv.go:21:2: only the first constant in this group has an explicit type (SA9004)
util/plancodec/codec.go:223:7: identical expressions on the left and right side of the '!=' operator (SA4000)
util/profile/profile.go:113:19: this result of append is never used, except maybe in other appends (SA4010)
util/stringutil/string_util.go:191:7: const caseDiff is unused (U1000)
util/stringutil/string_util_test.go:65:4: string literal contains the Unicode control character U+0005, consider using the '\x05' escape sequence (ST1018)
util/stringutil/string_util_test.go:65:4: string literal contains the Unicode control character U+0018, consider using the '\x18' escape sequence (ST1018)
util/stringutil/string_util_test.go:65:22: string literal contains the Unicode control character U+0005, consider using the '\x05' escape sequence (ST1018)
util/stringutil/string_util_test.go:65:22: string literal contains the Unicode control character U+0018, consider using the '\x18' escape sequence (ST1018)
util/testutil/testutil.go:153:34: should use make([]testCases, len(res.input)) instead (S1019)
util/testutil/testutil.go:276:23: should use make([]byte, len(buf.Bytes())) instead (S1019)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
master

### PR DESCRIPTION
**Pull request by mahjonp**
### What problem does this PR solve? 

Use staticcheck to perform some static checks on TiDB repo. fix #13456

### What is changed and how it works?

Here is the rule lists

| Rule | Short description |
| :--: | :--:|
| S1002 | Omit comparison with boolean constant |
| S1004 |Replace call to bytes.Compare with bytes.Equal|
| S1007 | Simplify regular expression by using raw string literal |
| S1010 | Omit default slice index |
| S1012 | Replace time.Now().Sub(x) with time.Since(x) |
| S1019 | Simplify make call by omitting redundant arguments|
| S1020 | Omit redundant nil check in type assertion |
| S1021 | Merge variable declaration and assignment |
| S1024 |	Replace x.Sub(time.Now()) with time.Until(x) |
| S1030 |	Use bytes.Buffer.String or bytes.Buffer.Bytes |
| SA2* | Concurrency issues |
| SA3* |  Testing issues |
| ~~SA1012~~ | A nil context.Context is being passed to a function, consider using context.TODO instead |
| SA4009 |  A function argument is overwritten before its first use |
| SA5* | Correctness issues|
| SA6000 |  Using regexp.Match or related in a loop, should use regexp.Compile |
| SA6005 | Inefficient string comparison with strings.ToLower or strings.ToUpper |

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

 None

Related changes

None.

Release note

None.

### CODE REVIEW

File: executor/hash_table.go [hunk 1]
```diff
@@ -162,8 +162,7 @@ func (c *hashRowContainer) PutChunk(chk *chunk.Chunk) error {
 // key of hash table: hash value of key columns
 // value of hash table: RowPtr of the corresponded row
 func (c *hashRowContainer) PutChunkSelected(chk *chunk.Chunk, selected []bool) error {
-	var chkIdx uint32
-	chkIdx = uint32(c.rowContainer.NumChunks())
+	var chkIdx = uint32(c.rowContainer.NumChunks())
```
Comment (jackysp) [inline executor/hash_table.go]:
```suggestion
	chkIdx := uint32(c.rowContainer.NumChunks())
```

File: executor/index_merge_reader.go [hunk 2]
```diff
@@ -544,8 +544,7 @@ func (w *partialIndexWorker) fetchHandles(ctx context.Context, result distsql.Se
 			}
 		}
 	}()
-	var chk *chunk.Chunk
-	chk = chunk.NewChunkWithCapacity([]*types.FieldType{types.NewFieldType(mysql.TypeLonglong)}, w.maxChunkSize)
+	var chk = chunk.NewChunkWithCapacity([]*types.FieldType{types.NewFieldType(mysql.TypeLonglong)}, w.maxChunkSize)
```
Comment (jackysp) [inline executor/index_merge_reader.go]:
```suggestion
	chk := chunk.NewChunkWithCapacity([]*types.FieldType{types.NewFieldType(mysql.TypeLonglong)}, w.maxChunkSize)
```

File: expression/bench_test.go [hunk 3]
```diff
@@ -1256,8 +1256,7 @@ func testVectorizedBuiltinFunc(c *C, vecExprCases vecExprBenchCases) {
 					c.Assert(err, IsNil, commentf(i))
 					c.Assert(isNull, Equals, output.IsNull(i), commentf(i))
 					if !isNull {
-						var cmp int
-						cmp = json.CompareBinary(val, output.GetJSON(i))
+						var cmp = json.CompareBinary(val, output.GetJSON(i))
```
Comment (jackysp) [inline expression/bench_test.go]:
```suggestion
						cmp := json.CompareBinary(val, output.GetJSON(i))
```
