### PR TITLE
pkg/server/handler/optimizor: stabilize plan replayer tests

### LINKED ISSUE #65729: pkg/server/handler/optimizor: stabilize plan replayer UT
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run the plan replayer unit test repeatedly:
- `go test ./pkg/server/handler/optimizor -run '^TestPlanReplayerWithMultiForeignKey$' -count=50 --tags=intest -timeout 30m`

### 2. What did you expect to see? (Required)

The plan replayer test should pass reliably, including the binding effect check (`@@last_plan_from_binding=1`).

### 3. What did you see instead (Required)

Intermittent failures such as:
- Binding check not taking effect in time (observing `@@last_plan_from_binding=0`).
- After `PLAN REPLAYER LOAD`, the session default DB could end up not being `planReplayer`, so unqualified `SELECT ... FROM t` may query the wrong schema and miss the intended binding.
- Server startup barrier race when multiple servers are started in the same test binary: `server.RunInGoTestChan` is a global channel closed after the first server start, so waiting on it without recreating it can lose the barrier and race.

### 4. What is your TiDB version? (Required)

TiDB: master (commit e705836a1f2313c2122e1b8be77ed44f69de0a55)

Notes:
- This is a unit test flake (not a runtime SQL bug), so `SELECT tidb_version()` is not applicable.
- Fix PR: #65735

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #65729

Problem Summary:

Plan replayer unit tests were flaky due to shared global server startup state, implicit default DB after `PLAN REPLAYER LOAD`, and async binding propagation/caching.

### What changed and how does it work?

- Recreate `server.RunInGoTestChan` before starting a server in the test helper.
- After `PLAN REPLAYER LOAD`, explicitly `USE planReplayer` and enable plan baselines.
- Use `require.Eventually` to wait until the binding takes effect.
- Cleanup dump-created global bindings to avoid interference.

### Check List

Tests 

- [ ] Unit test
  - `go test ./pkg/server/handler/optimizor -run '^TestPlanReplayerWithMultiForeignKey$' -tags=intest`
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] The change is for stabilizing unit tests; CI will cover it.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/handler/optimizor/plan_replayer_test.go [hunk 1]
```diff
@@ -359,6 +362,8 @@ func TestPlanReplayerWithMultiForeignKey(t *testing.T) {
 		config.AllowAllFiles = true
 	}))
 	require.NoError(t, err, "Error connecting")
+	db.SetMaxOpenConns(1)
```
Comment (0xPoe) [inline pkg/server/handler/optimizor/plan_replayer_test.go:365]: We could include some comments here.

File: pkg/server/handler/optimizor/plan_replayer_test.go [hunk 2]
```diff
@@ -487,13 +508,22 @@ func prepareData4Issue43192(t *testing.T, client *testserverclient.TestServerCli
...
+	// Cleanup the binding created for dumping to avoid interference when the same server later loads the replayer file.
+	tk.MustExec("drop global binding for select a, b from t where a in (1, 2, 3)")
 	return filename
 }
 
 func prepareData4Issue56458(t *testing.T, client *testserverclient.TestServerClient, dom *domain.Domain) string {
 	h := dom.StatsHandle()
 	db, err := sql.Open("mysql", client.GetDSN())
 	require.NoError(t, err, "Error connecting")
+	db.SetMaxOpenConns(1)
```
Comment (0xPoe) [inline pkg/server/handler/optimizor/plan_replayer_test.go:525]: ditto
