### PR TITLE
ttl: fix time zone issue in TTL

### LINKED ISSUE #51675: ttl: 1 hour's deviation for 'expire time' in TTL
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Set time zone as 'PDT': `set @@time_zone='America/Los_Angeles'` on PDT time.
2. Run test 'TestSubmitJob':
```
go test --tags=intest -timeout 30s -run ^TestSubmitJob$ "github.com/pingcap/tidb/pkg/ttl/ttlworker"
```

### 2. What did you expect to see? (Required)

Test succeeded.

### 3. What did you see instead (Required)

Test failed:
```
--- FAIL: TestSubmitJob (0.96s)
    job_manager_integration_test.go:477:
        	Error Trace:	/Users/bb7133/Projects/gopath/src/github.com/pingcap/tidb/pkg/ttl/ttlworker/job_manager_integration_test.go:477
        	Error:      	Max difference between 1710172125 and 1710175725 allowed is 300, but difference was -3600
        	Test:       	TestSubmitJob
FAIL
```

### 4. What is your TiDB version? (Required)
Latest master branch

### 5. Root cause
The [calculation of 'expire time'](https://github.com/pingcap/tidb/blob/e2718640b58e3cef5eb2be1275ad59fdab36ea61/pkg/ttl/cache/table.go#L199-L201) is problematic when facing daylight saving time:
```
fmt.Sprintf("SELECT FROM_UNIXTIME(0) + INTERVAL %d SECOND - INTERVAL %s %s", now.Unix(), expireExpr, unit.String()),
```
For areas like Los Angeles, the time of `FROM_UNIXTIME(0)` is in PST when `now()` is in PDT, there will be 1-hour deviation.

As a result, users will also notice this bug checking job status in PDT time:

```
tidb> create table ttlp1(a int, t timestamp) TTL=`t`+interval 1 HOUR PARTITION BY RANGE (a) (
    -> PARTITION p0 VALUES LESS THAN (10),
    -> PARTITION p1 VALUES LESS THAN (100));
Query OK, 0 rows affected (0.09 sec)

tidb> select * from mysql.tidb_ttl_table_status\G
...
*************************** 3. row ***************************
                      table_id: 110
               parent_table_id: 109
              table_statistics: NULL
                   last_job_id: bfbe0a4394ad4a50852ef6da315a9640
           last_job_start_time: 2024-03-11 14:20:39
          last_job_finish_time: 2024-03-11 14:20:54
           **last_job_ttl_expire**: 2024-03-11 12:20:39
...
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #51675

### What changed and how does it work?

fix the time zone issue again after we reverted #51701. In this PR, we still use SQL to compute the expired time to make sure it has the same behavior as the expression. However, to make the result right we:

1. Set the session's time zone to UTC to make the time zone stable and has no daylight-saving time.
2. Make a new start time with the same string value but it is in time zone 'UTC'. For example, if the input now is `2020-01-01 08:00:00 +08:00`, the new start time is `2020-01-01 08:00:00 UTC`.
3. Compute the expired time with the new started time, for example, if the expire interval is `1 hour`, the expire time is `2020-01-01 07:00:00 UTC`
4. The interval between the above two times is the expired duration.
5. Compute the real expired time by `now.Add(-interval)`

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
 fix time zone issue in TTL
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

File: pkg/ttl/cache/table.go [hunk 1]
```diff
@@ -185,28 +185,98 @@ func (t *PhysicalTable) ValidateKeyPrefix(key []types.Datum) error {
...
+		_, restoreErr := se.ExecuteSQL(ctx, "SET @@time_zone=%?", originalTZ)
+		if err == nil {
+			err = restoreErr
+		}
+	}()
+
+	// Firstly, we should use the UTC time zone to compute the expired time to avoid time shift caused by DST.
+	// The start time should be a time with the same datetime string as `now` but it is in the UTC timezone.
+	nowInGlobalTZ := now.In(globalTz)
+	startTime := time.Date(
```
Comment (bb7133) [inline pkg/ttl/cache/table.go:245]: I don't really get the point here: `nowInGlobalTZ` and `startTime` are `time.Time`, what's the difference between this and `startTime := time.In(UTC)`?

File: pkg/ttl/ttlworker/job_manager_integration_test.go [hunk 2]
```diff
@@ -63,6 +64,45 @@ func sessionFactory(t *testing.T, store kv.Storage) func() session.Session {
...
+
+	// global time zone should not change
+	tk.MustQuery("select @@global.time_zone").Check(testkit.Rows("Europe/Berlin"))
+	tz, err := se.GlobalTimeZone(context.TODO())
+	require.NoError(t, err)
+	require.Equal(t, "Europe/Berlin", tz.String())
+	// session variables should be set
+	tk.MustQuery("select @@time_zone, @@tidb_retry_limit, @@tidb_enable_1pc, @@tidb_enable_async_commit").
+		Check(testkit.Rows("UTC 0 1 1"))
+
```
Comment (bb7133) [inline pkg/ttl/ttlworker/job_manager_integration_test.go:98]: Please remove this blank line.

File: pkg/ttl/cache/table.go [hunk 3]
```diff
@@ -185,28 +185,98 @@ func (t *PhysicalTable) ValidateKeyPrefix(key []types.Datum) error {
...
+		nowInGlobalTZ.Hour(), nowInGlobalTZ.Minute(), nowInGlobalTZ.Second(),
+		nowInGlobalTZ.Nanosecond(), time.UTC,
+	)
+
 	rows, err = se.ExecuteSQL(
 		ctx,
 		// FROM_UNIXTIME does not support negative value, so we use `FROM_UNIXTIME(0) + INTERVAL <current_ts>`
 		// to present current time
-		fmt.Sprintf("SELECT FROM_UNIXTIME(0) + INTERVAL %d SECOND - INTERVAL %s %s", now.Unix(), expireExpr, unit.String()),
+		fmt.Sprintf("SELECT FROM_UNIXTIME(0) + INTERVAL %d MICROSECOND - INTERVAL %s %s",
```
Comment (bb7133) [inline pkg/ttl/cache/table.go:255]: It would be much easier(and more robust) way to calculate the expire time without SQL executions here. However, there's no straightforward way to do it because of `expireExpr`.

I can't imagine a better way but this can be treated as a backlog.

File: pkg/ttl/cache/table.go (hunk 1 above)
Comment (lcwangchao) [reply pkg/ttl/cache/table.go:245]: For example, if global time zone is `Asia/Shanghai` and nowInGlobalTZ is `2020-01-01 08:00:00 +08:00`.

`nowInGlobalTZ.In(time.UTC)` is: `2020-01-01 00:00:00 +00:00`
`startTime` is: `2020-01-01 08:00:00 +00:00`

`startTime` should have a same formated time string with `nowInGlobalTZ` but it they are not the same point

File: pkg/ttl/cache/table.go (hunk 3 above)
Comment (lcwangchao) [reply pkg/ttl/cache/table.go:255]: I think we can use `expression.ParseSimpleExpr` to parse it to an expression and evaluate it. But an `expression.BuildContext` is not very easy to build now. Maybe we can make it after expression refactor finished.

File: pkg/ttl/cache/table.go (hunk 1 above)
Comment (bb7133) [reply pkg/ttl/cache/table.go:245]: This is a bit confusing, could you please add your example to the comment?

Comment (lcwangchao) [reply pkg/ttl/cache/table.go:248]: Done

**Review by bb7133 — APPROVED** [review]
LGTM
