### PR TITLE
br: add retry for raw kv client put

### LINKED ISSUE #58845: br: got rpcClient is idle error during log meta restore
## Bug Report

A customer found error `rpcClient is idle` during log restore and causes the restore to fail, looks like some issue with the `client-go` lib that when it recycles the connection a request comes in and will fail with such error. 

At BR side we can probably add a retry logic and next try should create a new connection and works just fine

similar report https://github.com/tikv/client-go/issues/568

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #58845

Problem Summary:

### What changed and how does it work?

Adds a retry logic in raw kv client to mask temporary connection error from the client_go library 

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Adds retry logic for raw kv client put operation when doing log meta restore to mask any temporary errors from the client_go (tikv) library
```

### CODE REVIEW

File: br/pkg/restore/log_client/client.go [hunk 1]
```diff
@@ -1961,3 +1967,26 @@ func (rc *LogClient) FailpointDoChecksumForLogRestore(
 
 	return eg.Wait()
 }
+
+func PutRawKvWithRetry(ctx context.Context, client *rawkv.RawKVBatchClient, key, value []byte, originTs uint64) error {
+	retry := utils.InitialRetryState(rawKVMaxRetries, rawKVInitialRetryInterval, rawKVMaxRetryInterval)
+	for retry.ShouldRetry() {
```
Comment (3pointer) [inline br/pkg/restore/log_client/client.go:1973]: you can use `utils.WithRetry` if you define the InitialRetryState.

File: br/pkg/utils/backoff.go [hunk 2]
```diff
@@ -343,6 +347,7 @@ func NewDiskCheckBackoffStrategy() BackoffStrategy {
 	return NewBackoffStrategy(
 		WithRemainingAttempts(resetTSRetryTime),
 		WithDelayTime(resetTSWaitInterval),
+		WithMaxDelayTime(resetTSMaxWaitInterval),
```
Comment (BornChanger) [inline br/pkg/utils/backoff.go:350]: can those change break the br behavior?

File: br/pkg/utils/backoff.go [hunk 3]
```diff
@@ -353,6 +358,7 @@ func NewRecoveryBackoffStrategy(isRetryErrFunc func(error) bool) BackoffStrategy
 	return NewBackoffStrategy(
 		WithRemainingAttempts(recoveryMaxAttempts),
 		WithDelayTime(recoveryDelayTime),
+		WithMaxDelayTime(recoveryMaxDelayTime),
```
Comment (BornChanger) [inline br/pkg/utils/backoff.go:361]: ditto

File: br/pkg/utils/backoff.go [hunk 4]
```diff
@@ -363,6 +369,7 @@ func NewFlashBackBackoffStrategy() BackoffStrategy {
 	return NewBackoffStrategy(
 		WithRemainingAttempts(FlashbackRetryTime),
 		WithDelayTime(FlashbackWaitInterval),
+		WithMaxDelayTime(FlashbackMaxWaitInterval),
```
Comment (BornChanger) [inline br/pkg/utils/backoff.go:372]: ditto

File: br/pkg/utils/backoff.go [hunk 5]
```diff
@@ -373,12 +380,24 @@ func NewChecksumBackoffStrategy() BackoffStrategy {
 	return NewBackoffStrategy(
 		WithRemainingAttempts(ChecksumRetryTime),
 		WithDelayTime(ChecksumWaitInterval),
+		WithMaxDelayTime(ChecksumMaxWaitInterval),
```
Comment (BornChanger) [inline br/pkg/utils/backoff.go:383]: ditto

**Review by BornChanger — COMMENTED** [review]
rest lgtm.

File: br/pkg/utils/backoff.go (hunk 2 above)
Comment (Tristan1900) [reply br/pkg/utils/backoff.go:350]: sounds good, I think that's a good point. will open another one

**Comment by Tristan1900** [comment]
@BornChanger @3pointer please take another look when you get a chance, thanks!

**Review by BornChanger — APPROVED** [review]

File: br/pkg/utils/backoff.go [hunk 6]
```diff
@@ -53,6 +53,10 @@ const (
 	recoveryMaxAttempts  = 16
 	recoveryDelayTime    = 30 * time.Second
 	recoveryMaxDelayTime = 4 * time.Minute
+
+	rawClientMaxAttempts  = 5
```
Comment (3pointer) [inline br/pkg/utils/backoff.go:57]: is 5 times(12~13s) retry enough for the special workload?

Can we make it longer?

**Review by 3pointer — APPROVED** [review]

File: br/pkg/utils/backoff.go (hunk 6 above)
Comment (Tristan1900) [reply br/pkg/utils/backoff.go:57]: it's mainly for retrying on removing the idle connection and create a new connection, I think it should be done within seconds, setting total retry to be >10s should be safe.
