### PR TITLE
disttask: fix executor err handling missing part

### LINKED ISSUE #50417: add index status is rollback done after inject network partition between ddl owner and one of tikv
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、tidb_enable_dist_task='on' and enable global sort
2、add index
3、inject network partition between ddl owner and one of tikv last for 3mins and recover

### 2. What did you expect to see? (Required)
after fault recover，add index can success

### 3. What did you see instead (Required)
after fault recover，add index status is rollback done 

the status of ddl job is not synced or done or running or queueing (now: 2024-01-13 19:21:28, jobId: 491, job type: add index /* ingest cloud */, state: rollback done)
operatorLogs:
[2024-01-13 19:03:00] ###### start adding index
alter table sbtest1 add index index_test_1705143780092 (c)
[2024-01-13 19:03:00] ###### wait for ddl job finish
[2024-01-13 19:21:28] ###### wait for ddl job to finish failed
select job_id, job_type, state from information_schema.ddl_jobs where query = 'alter table sbtest1 add index index_test_1705143780092 (c)'
jobId: 491, job type: add index /* ingest cloud */, state: rollback done

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.6.0
Edition: Community
Git Commit Hash: 2df8bd1fc0fb5100bddf94f6bebe4e43878becc2
Git Branch: heads/refs/tags/v7.6.0
UTC Build Time: 2024-01-12 02:51:35
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-01-13T18:46:17.819+0800

tidb logs:
[2024/01/13 19:21:09.480 +08:00] [INFO] [handle.go:186] ["task not resumable"] [taskKey=ddl/backfill/491]
[2024/01/13 19:21:09.782 +08:00] [ERROR] [handle.go:92] ["task reverted"] [task-id=210029] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:09.783 +08:00] [WARN] [index.go:2203] ["cannot get task"] [category=ddl] [task_key=ddl/backfill/491] [error="task not found"]
[2024/01/13 19:21:09.784 +08:00] [WARN] [reorg.go:232] ["run reorg job done"] [category=ddl] ["handled rows"=35232986] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:09.790 +08:00] [WARN] [ddl_worker.go:1118] ["run DDL job error"] [worker="worker 2, tp add index"] [category=ddl] [jobID=491] [conn=710937990] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:09.797 +08:00] [INFO] [ddl_worker.go:982] ["run DDL job failed, sleeps a while then retries it."] [worker="worker 2, tp add index"] [category=ddl] [jobID=491] [conn=710937990] [waitTime=1s] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:10.797 +08:00] [INFO] [ddl_worker.go:1367] ["schema version doesn't change"] [category=ddl]
[2024/01/13 19:21:10.807 +08:00] [INFO] [ddl_worker.go:1156] ["run DDL job"] [worker="worker 3, tp add index"] [category=ddl] [jobID=491] [conn=710937990] [category=ddl] [job="ID:491, Type:add index, State:running, SchemaState:write reorganization, SchemaID:104, TableID:245, RowCount:35232986, ArgLen:0, start time: 2024-01-13 19:03:00.09 +0800 CST, Err:[tikv:9005]Region is unavailable, ErrCount:510, SnapshotVersion:446993211166556275, LocalMode: false, UniqueWarnings:0"]
[2024/01/13 19:21:10.808 +08:00] [INFO] [index.go:888] ["index backfill state running"] [category=ddl] ["job ID"=491] [table=sbtest1] ["ingest mode"=true] [index=index_test_1705143780092]
[2024/01/13 19:21:10.813 +08:00] [INFO] [handle.go:186] ["task not resumable"] [taskKey=ddl/backfill/491]
[2024/01/13 19:21:11.115 +08:00] [ERROR] [handle.go:92] ["task reverted"] [task-id=210029] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:11.116 +08:00] [WARN] [index.go:2203] ["cannot get task"] [category=ddl] [task_key=ddl/backfill/491] [error="task not found"]
[2024/01/13 19:21:11.116 +08:00] [WARN] [reorg.go:232] ["run reorg job done"] [category=ddl] ["handled rows"=35232986] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:11.122 +08:00] [WARN] [ddl_worker.go:1118] ["run DDL job error"] [worker="worker 3, tp add index"] [category=ddl] [jobID=491] [conn=710937990] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:11.129 +08:00] [INFO] [ddl_worker.go:1367] ["schema version doesn't change"] [category=ddl]
[2024/01/13 19:21:11.139 +08:00] [INFO] [ddl_worker.go:1156] ["run DDL job"] [worker="worker 2, tp add index"] [category=ddl] [jobID=491] [conn=710937990] [category=ddl] [job="ID:491, Type:add index, State:running, SchemaState:write reorganization, SchemaID:104, TableID:245, RowCount:35232986, ArgLen:0, start time: 2024-01-13 19:03:00.09 +0800 CST, Err:[tikv:9005]Region is unavailable, ErrCount:511, SnapshotVersion:446993211166556275, LocalMode: false, UniqueWarnings:0"]
[2024/01/13 19:21:11.140 +08:00] [INFO] [index.go:888] ["index backfill state running"] [category=ddl] ["job ID"=491] [table=sbtest1] ["ingest mode"=true] [index=index_test_1705143780092]
[2024/01/13 19:21:11.146 +08:00] [INFO] [handle.go:186] ["task not resumable"] [taskKey=ddl/backfill/491]
[2024/01/13 19:21:11.448 +08:00] [ERROR] [handle.go:92] ["task reverted"] [task-id=210029] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:11.450 +08:00] [WARN] [index.go:2203] ["cannot get task"] [category=ddl] [task_key=ddl/backfill/491] [error="task not found"]
[2024/01/13 19:21:11.450 +08:00] [WARN] [reorg.go:232] ["run reorg job done"] [category=ddl] ["handled rows"=35232986] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:11.461 +08:00] [WARN] [index.go:1087] ["run add index job failed, convert job to rollback"] [category=ddl] [job="ID:491, Type:add index, State:running, SchemaState:write reorganization, SchemaID:104, TableID:245, RowCount:35232986, ArgLen:6, start time: 2024-01-13 19:03:00.09 +0800 CST, Err:[tikv:9005]Region is unavailable, ErrCount:511, SnapshotVersion:446993211166556275, LocalMode: false, UniqueWarnings:0"] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:11.501 +08:00] [WARN] [ddl_worker.go:1118] ["run DDL job error"] [worker="worker 2, tp add index"] [category=ddl] [jobID=491] [conn=710937990] [error="[tikv:9005]Region is unavailable"]
[2024/01/13 19:21:11.511 +08:00] [INFO] [domain.go:272] ["diff load InfoSchema success"] [currentSchemaVersion=436] [neededSchemaVersion=437] ["start time"=1.220424ms] [gotSchemaVersion=437] [phyTblIDs="[245]"] [actionTypes="[7]"] [diffTypes="[\"add index\"]"]
[2024/01/13 19:21:11.546 +08:00] [INFO] [domain.go:873] ["mdl gets lock, update to owner"] [jobID=491] [version=437]

[tidb-0.tar.gz](https://github.com/pingcap/tidb/files/13935648/tidb-0.tar.gz)
[tidb-1.tar.gz](https://github.com/pingcap/tidb/files/13935652/tidb-1.tar.gz)

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #50417

Problem Summary:

### What changed and how does it work?
Every error in taskExecutor.run should check retryable.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 1]
```diff
@@ -680,15 +683,24 @@ func (s *BaseTaskExecutor) markSubTaskCanceledOrFailed(ctx context.Context, subt
...
+	} else {
+		logger := logutil.Logger(s.logCtx)
+		backoffer := backoff.NewExponential(scheduler.RetrySQLInterval, 2, scheduler.RetrySQLMaxInterval)
+		err1 := handle.RunWithRetry(s.logCtx, scheduler.RetrySQLTimes, backoffer, logger,
+			func(_ context.Context) (bool, error) {
+				return true, s.taskTable.UpdateErrorToSubtask(ctx, s.id, taskID, err)
+			},
+		)
+		if err1 == nil {
+			logger.Warn("update error to subtask success", zap.Error(err))
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply pkg/disttask/framework/taskexecutor/task_executor.go:701]: why a `success` log is `warn`😓

[the remark this answers is not in the document]
Comment (ywqzzy) [reply pkg/disttask/framework/taskexecutor/task_executor.go:701]: indicate there is error for the subtask

File: pkg/disttask/framework/taskexecutor/task_executor_test.go [hunk 2]
```diff
@@ -526,3 +527,146 @@ func TestCheckBalanceSubtask(t *testing.T) {
...
+	mockSubtaskTable.EXPECT().GetFirstSubtaskInStates(gomock.Any(), "id", taskID, proto.StepOne,
+		unfinishedNormalSubtaskStates...).Return(nil, nil)
+	mockSubtaskTable.EXPECT().GetTaskByID(gomock.Any(), gomock.Any()).Return(&proto.Task{ID: taskID, Step: proto.StepTwo}, nil)
+	mockSubtaskExecutor.EXPECT().Cleanup(gomock.Any()).Return(cleanupErr)
+	mockExtension.EXPECT().IsRetryableError(gomock.Any()).Return(false)
+	mockSubtaskTable.EXPECT().UpdateErrorToSubtask(runCtx, taskExecutor.id, gomock.Any(), cleanupErr)
+	require.NoError(t, taskExecutor.Run(runCtx, &proto.Task{Step: proto.StepOne, Type: tp, ID: taskID, Concurrency: concurrency}))
+	require.True(t, ctrl.Satisfied())
+
+	// 9. runSummaryCollectLoop met retryable error
```
Comment (ywqzzy) [inline pkg/disttask/framework/taskexecutor/task_executor_test.go:659]:
```suggestion
	// 9. runSummaryCollectLoop met non retryable error
```

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 3]
```diff
@@ -166,6 +166,10 @@ func (s *BaseTaskExecutor) Run(ctx context.Context, task *proto.Task) (err error
 	if s.mu.handled {
 		return err
 	}
+	if err == nil {
+		// may have error in defer function in run(ctx, task)
+		err = s.getError()
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:171]: we depends on too much on `getError()`, it's actually replacing the responsiblity of `error of method return`

but ok for now

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 4]
```diff
@@ -680,15 +683,24 @@ func (s *BaseTaskExecutor) markSubTaskCanceledOrFailed(ctx context.Context, subt
...
+	} else {
+		logger := logutil.Logger(s.logCtx)
+		backoffer := backoff.NewExponential(scheduler.RetrySQLInterval, 2, scheduler.RetrySQLMaxInterval)
+		err1 := handle.RunWithRetry(s.logCtx, scheduler.RetrySQLTimes, backoffer, logger,
+			func(_ context.Context) (bool, error) {
+				return true, s.taskTable.UpdateErrorToSubtask(ctx, s.id, taskID, err)
+			},
+		)
+		if err1 == nil {
+			logger.Info("updating an error to subtask succeed", zap.Error(err))
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:701]:
```suggestion
			logger.Info("updating an error to subtask succeed", zap.NamedError("subtask-err", err))
```

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 5]
```diff
@@ -175,7 +179,6 @@ func (s *BaseTaskExecutor) Run(ctx context.Context, task *proto.Task) (err error
 func (s *BaseTaskExecutor) runStep(ctx context.Context, task *proto.Task) (resErr error) {
 	if ctx.Err() != nil {
 		s.onError(ctx.Err())
-		return s.getError()
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:178]: what's the point of keep running when context cancelled?

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 6]
```diff
@@ -680,15 +683,24 @@ func (s *BaseTaskExecutor) markSubTaskCanceledOrFailed(ctx context.Context, subt
...
-	err1 := handle.RunWithRetry(s.logCtx, scheduler.RetrySQLTimes, backoffer, logger,
-		func(_ context.Context) (bool, error) {
-			return true, s.taskTable.UpdateErrorToSubtask(ctx, s.id, taskID, err)
-		},
-	)
-	if err1 == nil {
-		logger.Warn("update error to subtask success", zap.Error(err))
+	if s.IsRetryableError(err) {
+		logger.Warn("meet retryable error", zap.Error(err))
+	} else if common.IsContextCanceledError(err) {
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:690]: seems we still need the `ctx cause` handling as in `markSubTaskCanceledOrFailed`

File: pkg/disttask/framework/taskexecutor/task_executor_test.go [hunk 7]
```diff
@@ -526,3 +527,159 @@ func TestCheckBalanceSubtask(t *testing.T) {
...
+	task := &proto.Task{Step: proto.StepOne, Type: tp}
+	taskExecutor := NewBaseTaskExecutor(ctx, "id", task, mockSubtaskTable)
+	taskExecutor.Extension = mockExtension
+
+	// 1. GetSubtaskExecutor meet retryable error.
+	getSubtaskExecutorErr := errors.New("get executor err")
+	mockExtension.EXPECT().GetSubtaskExecutor(gomock.Any(), gomock.Any(), gomock.Any()).Return(nil, getSubtaskExecutorErr)
+	mockExtension.EXPECT().IsRetryableError(gomock.Any()).Return(true)
+	require.NoError(t, taskExecutor.Run(runCtx, &proto.Task{Step: proto.StepOne, Type: tp, ID: taskID, Concurrency: concurrency}))
+	require.True(t, ctrl.Satisfied())
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor_test.go:553]: error return from GetSubtaskExecutor should be fatal that will not be retried(we need comment this in the api definition)

File: pkg/disttask/framework/taskexecutor/task_executor_test.go [hunk 8]
```diff
@@ -526,3 +527,159 @@ func TestCheckBalanceSubtask(t *testing.T) {
...
+	require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/mockSummaryCollectErr"))
+
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/mockSummaryCollectErr", "return()"))
+	mockExtension.EXPECT().IsRetryableError(gomock.Any()).Return(true)
+	require.NoError(t, taskExecutor.Run(runCtx, &proto.Task{Step: proto.StepOne, Type: tp, ID: taskID, Concurrency: concurrency}))
+	require.True(t, ctrl.Satisfied())
+	require.NoError(t, failpoint.Disable("github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/mockSummaryCollectErr"))
+
+	// 10. runSummaryCollectLoop meet non retryable error
+	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/mockSummaryCollectErr", "return()"))
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor_test.go:673]: why enable/disable repeatedly?

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/disttask/framework/taskexecutor/task_executor.go (hunk 3 above)
Comment (ywqzzy) [reply pkg/disttask/framework/taskexecutor/task_executor.go]: Will refactor it

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 9]
```diff
@@ -679,16 +690,52 @@ func (s *BaseTaskExecutor) markSubTaskCanceledOrFailed(ctx context.Context, subt
...
+		logger.Info("canceled one subtask succeed", zap.NamedError("subtask-cancel", err))
+	}
+	return err1
+}
+
+// updateSubtask check the error type and decide the subtasks' state.
+// 1. Only cancel subtasks when meet ErrCancelSubtask.
+// 2. Only fail subtasks when meet non retryable error.
+// 3. When meet other errors, don't change subtasks' state.
+// Handled errors should not happened during subtasks execution.
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:726]:
```suggestion
// Handled errors should not happen during subtasks execution.
```

**Review by D3Hunter — APPROVED** [review]

File: pkg/disttask/framework/storage/task_table.go [hunk 10]
```diff
@@ -530,8 +530,8 @@ func (mgr *TaskManager) GetFirstSubtaskInStates(ctx context.Context, tidbID stri
 	return Row2SubTask(rs[0]), nil
 }
 
-// UpdateErrorToSubtask updates the error to subtask.
-func (mgr *TaskManager) UpdateErrorToSubtask(ctx context.Context, execID string, taskID int64, err error) error {
+// FailedSubtask update the task's subtask state to failed and set the err.
+func (mgr *TaskManager) FailedSubtask(ctx context.Context, execID string, taskID int64, err error) error {
```
Comment (tangenta) [inline pkg/disttask/framework/storage/task_table.go:534]: Failed -> Fail? The present tense is better.

Comment (ywqzzy) [reply pkg/disttask/framework/storage/task_table.go:534]: > Failed -> Fail? The present tense is better.

Followed task related naming, "Failed" represent the expected state after the function

File: pkg/disttask/framework/storage/task_table.go [hunk 11]
```diff
@@ -555,6 +555,26 @@ func (mgr *TaskManager) UpdateErrorToSubtask(ctx context.Context, execID string,
...
+		end_time = CURRENT_TIMESTAMP()
+		where exec_id = %? and 
+		task_key = %? and 
+		state in (%?, %?) 
+		limit 1;`,
+		proto.SubtaskStateCanceled,
+		execID,
+		taskID,
+		proto.TaskStatePending,
+		proto.TaskStateRunning)
```
Comment (D3Hunter) [inline pkg/disttask/framework/storage/task_table.go:574]:
```suggestion
		proto.SubtaskStatePending,
		proto.SubtaskStateRunning)
```

File: pkg/disttask/framework/storage/task_table.go (hunk 10 above)
Comment (ywqzzy) [reply pkg/disttask/framework/storage/task_table.go]: Done

File: pkg/disttask/framework/storage/task_table.go (hunk 11 above)
Comment (ywqzzy) [reply pkg/disttask/framework/storage/task_table.go]: https://github.com/pingcap/tidb/pull/50429/commits/015ac40079ffa1e33a5535a204107ffef3b68d2d
So many place need to change, will fire another pr to change all of them since this pr needs to cp

Comment (D3Hunter) [reply pkg/disttask/framework/storage/task_table.go]: lgtm

**Review by wjhuang2016 — APPROVED** [review]
