### PR TITLE
planner: don't handle collation in `in expression` if it contains a row function.

### LINKED ISSUE #31273: mysql test `row` failed.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select (1,2,(3,4)) IN ((3,2,(3,4)), (1,2,(3,4)));
```
### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
Operand should contain 2 column(s)
### 4. What is your TiDB version? (Required)
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/7946/pipeline/86/
master

### LINKED ISSUE #31300: The results of InStatement and EqualStatement are inconsistent
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
create table t(`COL2` tinyint(16) DEFAULT NULL);
insert into t values(0);
select * from t WHERE COL2 IN (0xfc);
select * from t WHERE COL2 = 0xfc;
```
### 2. What did you expect to see? (Required)
mysql> select * from t WHERE COL2 IN (0xfc);
Empty set (0.00 sec)

mysql> select * from t WHERE COL2 = 0xfc;
Empty set (0.00 sec)
### 3. What did you see instead (Required)
```
mysql> select * from t WHERE COL2 IN (0xfc);
+------+
| COL2 |
+------+
|    0 |
+------+
1 row in set, 2 warnings (0.00 sec)

mysql> select * from t WHERE COL2 = 0xfc;
Empty set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.5.0-alpha
Edition: Community
Git Commit Hash: 974b5784adbbd47d14659916d47dd986effa7b4e
Git Branch: release-5.4
UTC Build Time: 2022-01-04 01:55:18
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #31273 and close #31300

Problem Summary:
It's vary hard to derive and set the best collation for `in expression` if it contains a row function.
For example: ("a", ("c", ("d", "e"))) in ("a", ("c"  collate bin, ("d", "e" collate general)))
We don't have a good idea to set the collation. So We decide that we don't handle collation in `in expression` if it contains a row function.

### What is changed and how it works?
Don't handle collation in `in expression` if it contains a row function.
If' acceptable and users rarely depend on it.
### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -1522,55 +1522,37 @@ func (er *expressionRewriter) inToExpression(lLen int, not bool, tp *types.Field
 }
 
 // deriveCollationForIn derives collation for in expression.
-func (er *expressionRewriter) deriveCollationForIn(colLen int, elemCnt int, stkLen int, args []expression.Expression) []*expression.ExprCollation {
-	coll := make([]*expression.ExprCollation, 0, colLen)
+// We don't handle the cases if the element is a tuple, such as (a, b, c) in ((x1, y1, z1), (x2, y2, z2)).
```
Comment (winoros) [inline planner/core/expression_rewriter.go:1525]:
```suggestion
// **We don't handle the cases if the element is a tuple, such as (a, b, c) in ((x1, y1, z1), (x2, y2, z2)).**
```

**Review by winoros — APPROVED** [review]

**Review by xiongjiwei — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]
LGTM
