### PR TITLE
lightning: support auto_random column in composite primary key

### LINKED ISSUE #41454: lightning: cannot generate value for auto_random column if it's in a composite primary key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

on tidb 6.5, we can create a table with auto_random column and it's in a composite primary key, while we cannot do it on 6.1
currently lightning check it using pkIsHandle, so will not auto generate data for this column in local backend(tidb backend don't has this problem) if it's the extra column added in downstream but it doesn't exist in source file
https://github.com/pingcap/tidb/blob/8497f7d32b13e7217fd097551efa753363affed6/br/pkg/lightning/backend/kv/sql2kv.go#L497

we should check it with this now
https://github.com/pingcap/tidb/blob/8497f7d32b13e7217fd097551efa753363affed6/ddl/ddl_api.go#L1552

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #41454

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
support generate value for auto_random column when it's in a composite primary key
```

### CODE REVIEW

File: br/tests/lightning_auto_random_default/run.sh [hunk 1]
```diff
@@ -60,3 +60,30 @@ for backend in tidb local; do
     run_sql "SELECT max(id & b'000001111111111111111111111111111111111111111111111111111111111') >= $NEXT_AUTO_RAND_VAL as ge FROM auto_random.t"
     check_contains 'ge: 1'
 done
+
+function run_for_auro_random_data2() {
+		create_table=$1
```
Comment (gozssky) [inline br/tests/lightning_auto_random_default/run.sh:65]:
```suggestion
    create_table=$1
```

**Review by gozssky — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by D3Hunter** [comment]
lightning ci pass https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/15225/pipeline
