### PR TITLE
server: fix the missing detachment for the mem/disk tracker

### LINKED ISSUE #17420: Detach memory tracker for insert/update
## Development Task

Currently, for the session memory tracker, it won't detach from the global memory tracker for `insert` and `update` which would cause the inaccurate memory usage statistical information. We need to detach the memory tracker in these cases.

### PR DESCRIPTION
**Pull request by Yisaer**
### What problem does this PR solve?
Currently, we detach session tracker from global tracker in `CloseRecordSet` function. If the query have no `RecordSet` returned (eg: `insert`), the session tracker won't be detached from global tracker which would cause the inaccurate memory usage statistical information.

Issue Number: close #17420 

### What is changed and how it works?

How it Works:

If the ExecuteStmt have no result returned in the `handleQuery`, we will directly detach the tracker 

### Release note
* No release note

### CODE REVIEW

**Comment by Yisaer** [comment]
@SunRunAway @qw4990  PTAL

File: executor/executor.go [hunk 1]
```diff
@@ -1515,15 +1515,6 @@ func (e *UnionExec) Close() error {
...
 	vars := ctx.GetSessionVars()
-	// Detach the Memory and disk tracker for the previous stmtCtx from GlobalMemoryUsageTracker and GlobalDiskUsageTracker
-	if stmtCtx := vars.StmtCtx; stmtCtx != nil {
-		if stmtCtx.DiskTracker != nil {
-			stmtCtx.DiskTracker.DetachFromGlobalTracker()
-		}
-		if stmtCtx.MemTracker != nil {
-			stmtCtx.MemTracker.DetachFromGlobalTracker()
-		}
-	}
```
Comment (Yisaer) [inline executor/executor.go:1526]: This is unnecessary now.

File: server/conn.go [hunk 2]
```diff
@@ -1456,8 +1459,23 @@ func (cc *clientConn) handleStmt(ctx context.Context, stmt ast.StmtNode, warns [
...
+		defer func() {
+			if sc != nil {
+				if sc.MemTracker != nil {
+					sc.MemTracker.DetachFromGlobalTracker()
+				}
+				if sc.DiskTracker != nil {
+					sc.DiskTracker.DetachFromGlobalTracker()
+				}
+			}
+		}()
```
Comment (qw4990) [inline server/conn.go:1478]: Emmmm, can we put this logic in `seesion.ExecuteStmt()`?
Since code in `conn.go` is about dealing with the network, it's better to not put it here.

Comment (qw4990) [reply server/conn.go:1478]: What're your options? @SunRunAway @Yisaer

Comment (SunRunAway) [reply server/conn.go:1478]: Why not put them into [handleNoDelay](https://github.com/pingcap/tidb/blob/915d84d7ad4a0335df8479dacce555b68d7363ac/executor/adapter.go#L372)?

Comment (Yisaer) [reply server/conn.go]: updated.

File: executor/adapter.go [hunk 3]
```diff
@@ -369,7 +369,22 @@ func (a *ExecStmt) Exec(ctx context.Context) (_ sqlexec.RecordSet, err error) {
 	}, nil
 }
 
-func (a *ExecStmt) handleNoDelay(ctx context.Context, e Executor, isPessimistic bool) (bool, sqlexec.RecordSet, error) {
+func (a *ExecStmt) handleNoDelay(ctx context.Context, e Executor, isPessimistic bool) (handled bool, rs sqlexec.RecordSet, err error) {
+	sc := a.Ctx.GetSessionVars().StmtCtx
+	defer func() {
```
Comment (qw4990) [inline executor/adapter.go:374]: Does it seem we cannot put it here since the `rs` has not been executed yet in this place? @Yisaer

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
Should we pick this PR to 4.0?

**Comment by Yisaer** [comment]
> Should we pick this PR to 4.0?

sure

File: server/conn.go [hunk 4]
```diff
@@ -954,12 +954,15 @@ func (cc *clientConn) dispatch(ctx context.Context, data []byte) error {
 	case mysql.ComStmtPrepare:
 		return cc.handleStmtPrepare(ctx, dataStr)
 	case mysql.ComStmtExecute:
+		// TODO: handle detaching stmt memory/disk tracker from global tracker
```
Comment (SunRunAway) [inline server/conn.go:957]: Should these TODOs be removed now?

Comment (qw4990) [reply server/conn.go:957]: PTAL @Yisaer

Comment (Yisaer) [reply server/conn.go]: updated.

**Review by SunRunAway — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
