### PR TITLE
expression: fix bugs in builtinfunction ArithmeticMinusInt logic

### LINKED ISSUE #22387: Bug in signed minus unsigned builtin function, result not forced to signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='';
select 12 - cast(15 as unsigned) ;          
```

### 2. What did you expect to see? (Required)
```
(1690, "BIGINT UNSIGNED value is out of range in '(12 - cast(15 as unsigned))'")
```

### 3. What did you see instead (Required)
```
+----------------------------+
| 12 - cast(15 as unsigned)  |
+----------------------------+
| 18446744073709551613       |
+----------------------------+
```

### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #22389: Bug in signed minus signed builtin function, result forced into signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='NO_UNSIGNED_SUBTRACTION';  
create table tb5(a bigint, b bigint);
insert into tb5 values (10, -9223372036854775808);
select a - b from tb5;
```

### 2. What did you expect to see? (Required)
```
(1690, "BIGINT value is out of range in '(`employees`.`tb5`.`a` - `employees`.`tb5`.`b`)'")
```

### 3. What did you see instead (Required)
```
+----------------------+
| a - b                |
+----------------------+
| -9223372036854775798 |
+----------------------+
```

### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #22390: Bug in signed minus signed builtin function, result not forced to signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='';  
create table tb5(a bigint, b bigint);
insert into tb5 values (10, -9223372036854775808);
select a - b from tb5;
```

### 2. What did you expect to see? (Required)
```
(1690, "BIGINT value is out of range in '(`employees`.`tb5`.`a` - `employees`.`tb5`.`b`)'")
```

### 3. What did you see instead (Required)
```
+----------------------+
| a - b                |
+----------------------+
| -9223372036854775798 |
+----------------------+
```

### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #22442: Bug in unsigned minus unsigned builtin function, result not forced to signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='';     
select cast(-1 as unsigned) - cast(-1 as unsigned);             
```

### 2. What did you expect to see? (Required)
```
+---------------------------------------------+
| cast(-1 as unsigned) - cast(-1 as unsigned) |
+---------------------------------------------+
| 0                                           |
+---------------------------------------------+
```

### 3. What did you see instead (Required)
```
(1690, "BIGINT UNSIGNED value is out of range in '(18446744073709551615 - 18446744073709551615)'")
```

### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #22444: Bug in unsigned minus unsigned builtin function, result forced to signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='NO_UNSIGNED_SUBTRACTION';      
select cast(-1 as unsigned) - cast(-10000 as unsigned);

```

### 2. What did you expect to see? (Required)
```
+-------------------------------------------------+
| cast(-1 as unsigned) - cast(-10000 as unsigned) |
+-------------------------------------------------+
| 9999                                            |
+-------------------------------------------------+
```

### 3. What did you see instead (Required)
```
(1690, "BIGINT UNSIGNED value is out of range in '(18446744073709551615 - 18446744073709541616)'")

```

### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #22445: Bug in unsigned minus unsigned builtin function, result forced to signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='NO_UNSIGNED_SUBTRACTION';      
select cast(-12 as unsigned) - cast(-1 as unsigned);
```

### 2. What did you expect to see? (Required)
```
+----------------------------------------------+
| cast(-12 as unsigned) - cast(-1 as unsigned) |
+----------------------------------------------+
| -11                                          |
+----------------------------------------------+
```

### 3. What did you see instead (Required)
```
(1690, "BIGINT UNSIGNED value is out of range in '(18446744073709551604 - 18446744073709551615)'")
```

### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #22446: Bug in unsigned minus signed builtin function, result forced to signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
set sql_mode='NO_UNSIGNED_SUBTRACTION'; 
select cast(-1 as unsigned) - 9223372036854775808         

### 2. What did you expect to see? (Required)
```
+--------------------------------------------+
| cast(-1 as unsigned) - 9223372036854775808 |
+--------------------------------------------+
| 9223372036854775807                        |
+--------------------------------------------+
```
### 3. What did you see instead (Required)
```
(1690, "BIGINT UNSIGNED value is out of range in '(18446744073709551615 - 9223372036854775808)'")
```
### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### LINKED ISSUE #22447: Bug in signed minus unsigned builtin function, result forced to signed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set sql_mode='NO_UNSIGNED_SUBTRACTION';      
select 9223372036854775808 - cast(-1 as unsigned)
```

### 2. What did you expect to see? (Required)
```
+--------------------------------------------+
| 9223372036854775808 - cast(-1 as unsigned) |
+--------------------------------------------+
| -9223372036854775807                       |
+--------------------------------------------+
```
### 3. What did you see instead (Required)
```
(1690, "BIGINT UNSIGNED value is out of range in '(9223372036854775808 - 18446744073709551615)'")
```
### 4. What is your TiDB version? (Required)

```
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-2016-g3dd842f50                    |
| Edition: Community                                                |
| Git Commit Hash: 3dd842f50a75ebbf9a4f9d7b30fb2ce8a8dd4b37         |
| Git Branch: master                                                |
| UTC Build Time: 2021-01-13 14:08:28                               |
| GoVersion: go1.15.5                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by Tjianke**
### What problem does this PR solve?

Issue Number: 

- closes #22390 
- closes #22389  
- closes #22387 
- closes #22442 
- closes #22444 
- closes #22445
- closes #22446
- closes #22447

Problem Summary:

### What is changed and how it works?

What's Changed:

Original logic is wrongful since it fails to handle case like `a < 0 && b < 0 && a > b` where a and b are both unsigned.

A concrete example: 
- `NO_UNSIGNED_SUBTRACTION` mode is on
- Input args are unsigned, 18446744073709551615 and 18446744073709551614 respectively
- Correct result should be 1, but origin logic will throw error due to `a < 0`(after casting to signed) 

Origin code: 
```
if forceToSigned && mysql.HasUnsignedFlag(s.args[0].GetType().Flag) {
     if a < 0 {
	return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", s.args[0].String(), s.args[1].String()))
}

if forceToSigned && mysql.HasUnsignedFlag(s.args[1].GetType().Flag) {
     if b < 0 {
	return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", s.args[0].String(), s.args[1].String()))
}
```

Overflow detection logics:

note: `uMaxInt64` = `uint64(math.MaxInt64)`, `uMinInt64` = `uint64(math.MaxInt64+1)`

- `minusFUU`: 
    - `(ulh >= urh && ulh-urh > uMaxInt64)` || 
    - `(ulh < urh && urh-ulh > uMinInt64)`
- `minusFUS`: 
    - `(lh < 0 && rh > 0 && uint64(lh) > uint64(math.MaxInt64+rh))` ||
    - `(lh < 0 && rh <= 0)` ||
    - `(lh >= 0 && rh < 0 && (rh == math.MinInt64 || -rh > math.MaxInt64-lh))`
- `minusFSU`: 
    - `(lh >= 0 && rh < 0 && uint64(rh)-uint64(lh) > uint64(math.MaxInt64+1))` || 
    - `(lh < 0 && rh >= 0 && -rh < math.MinInt64-lh) || (lh < 0 && rh < 0`
- `minusUU`: `uint64(lh) < uint64(rh)`
- `minusUS`: 
    - `rh >= 0 && uint64(lh) < uint64(rh)` || 
    - `rh < 0 && uint64(lh) > math.MaxUint64-uint64(-rh)`
- `minusSU`: 
    - `lh < 0` || 
    - `uint64(lh) < uint64(rh)`
- `minusSS`: 
    - `(lh >= 0 && rh == math.MinInt64)` || 
    - `(lh > 0 && -rh > math.MaxInt64-lh)` || 
    - `(lh < 0 && -rh < math.MinInt64-lh)`

Key function `minusFUS` detection logic:
```
lh >= 0 && rh >= 0 : never overflow
lh >= 0 && rh < 0 : (-rh > maxint64 - lh) || lh >= 0 && rh == minint64
lh < 0 && rh > 0 : uint64(lh) - uint64(rh) > maxint64
lh < 0 && rh <= 0 : definitely overflow
```

Key function `minusFSU` detection logic:
```
lh >= 0 && rh >= 0 : never overflow
lh >= 0 && rh < 0 : uint64(rh) - uint64(lh) > maxint64 + 1
lh < 0 && rh >= 0 : lh - rh < minint64
lh < 0 && rh < 0 : definitely overflow
```

### Related changes

Tests 

- Unit test
- Integration test

### Release note 

- fix bugs in builtinfunction ArithmeticMinusInt logic

### CODE REVIEW

**Comment by breeswish** [comment]
Hi, considering that this is a bug fix, could you also supply some unit tests to prove (and ensure) that the fix works? Thanks! /cc @lzmhhh123 @XuHuaiyu

**Comment by Tjianke** [comment]
> Hi, considering that this is a bug fix, could you also supply some unit tests to prove (and ensure) that the fix works? Thanks! /cc @lzmhhh123 @XuHuaiyu

Sure, I'll add UT right away

**Comment by Tjianke** [comment]
As I rechecked the code of `ArithmeticMinusInt`, more bugs were found:

#22442, #22444, #22445

File: types/const_test.go [hunk 1]
```diff
@@ -173,7 +309,7 @@ func (s *testMySQLConstSuite) TestNoUnsignedSubtractionMode(c *C) {
 	c.Assert(rs.Close(), IsNil)
 	rs, _ = tk.Exec("SELECT CAST(9223372036854775808 as UNSIGNED) - 1")
 	_, err = session.GetRows4Test(ctx, tk.Se, rs)
-	c.Assert(err, NotNil)
+	c.Assert(err, IsNil)
```
Comment (Tjianke) [inline types/const_test.go:312]: Correct UT result,  `SELECT CAST(9223372036854775808 as UNSIGNED) - 1` should be valid under `NO_UNSIGNED_SUBTRACTION` mode.

File: expression/builtin_arithmetic.go [hunk 2]
```diff
@@ -416,37 +416,48 @@ func (s *builtinArithmeticMinusIntSig) evalInt(row chunk.Row) (val int64, isNull
 		return 0, isNull, err
 	}
 	forceToSigned := s.ctx.GetSessionVars().SQLMode.HasNoUnsignedSubtractionMode()
-	isLHSUnsigned := !forceToSigned && mysql.HasUnsignedFlag(s.args[0].GetType().Flag)
-	isRHSUnsigned := !forceToSigned && mysql.HasUnsignedFlag(s.args[1].GetType().Flag)
+	isLHSUnsigned := mysql.HasUnsignedFlag(s.args[0].GetType().Flag)
+	isRHSUnsigned := mysql.HasUnsignedFlag(s.args[1].GetType().Flag)
 
-	if forceToSigned && mysql.HasUnsignedFlag(s.args[0].GetType().Flag) {
-		if a < 0 {
```
Comment (Tjianke) [inline expression/builtin_arithmetic.go:423]: Wrongful logic, fails to handle case like `a < 0 && b < 0 && a > b`

**Comment by breeswish** [comment]
/cc @wshwsh12 @qw4990 

PTAL, thanks!

File: expression/builtin_arithmetic.go [hunk 3]
```diff
@@ -416,37 +416,48 @@ func (s *builtinArithmeticMinusIntSig) evalInt(row chunk.Row) (val int64, isNull
...
-			return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", s.args[0].String(), s.args[1].String()))
+	switch {
+	case forceToSigned && isLHSUnsigned && isRHSUnsigned:
+		ua, ub, uMaxInt64, uMinInt64 := uint64(a), uint64(b), uint64(math.MaxInt64), uint64(math.MaxInt64+1)
+		if (ua >= ub && ua-ub > uMaxInt64) || (ua < ub && ub-ua > uMinInt64) {
+			return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT", fmt.Sprintf("(%s + %s)", s.args[0].String(), s.args[1].String()))
```
Comment (mmyj) [inline expression/builtin_arithmetic.go:426]: Why this error message is "(%s + %s)"?

Comment (Tjianke) [reply expression/builtin_arithmetic.go:426]: I reused the report format from [vec version](https://github.com/pingcap/tidb/blob/master/expression/builtin_arithmetic_vec.go#L388).

```
if lh < 0 {
	return types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", b.args[0].String(), b.args[1].String()))
}

if rh < 0 {
	return types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", b.args[0].String(), b.args[1].String()))
}

if (lh > 0 && -rh > math.MaxInt64-lh) || (lh < 0 && -rh < math.MinInt64-lh) {
	return types.ErrOverflow.GenWithStackByArgs("BIGINT", fmt.Sprintf("(%s + %s)", b.args[0].String(), b.args[1].String()))
}
```



After recheck I think we found another bug, `minusFUU`, `minusFUS`, `minusFSU` all report in `%s+%s` format.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — COMMENTED** [review]
It seems that if `NO_UNSIGNED_SUBTRACTION` is set, the overflow error message will never be thrown.

When `forceToSigned` is true, we can run the following code for FUS and FSU?
``` sql
		resulti64s[i] = int64(uint64(lh) - uint64(rh))
```

File: expression/builtin_arithmetic.go (hunk 3 above)
Comment (Tjianke) [reply expression/builtin_arithmetic.go]: Changed `%s + %s` to `%s - %s` in row version eval.

File: expression/builtin_arithmetic.go [hunk 4]
```diff
@@ -416,37 +416,48 @@ func (s *builtinArithmeticMinusIntSig) evalInt(row chunk.Row) (val int64, isNull
...
-	isRHSUnsigned := !forceToSigned && mysql.HasUnsignedFlag(s.args[1].GetType().Flag)
+	isLHSUnsigned := mysql.HasUnsignedFlag(s.args[0].GetType().Flag)
+	isRHSUnsigned := mysql.HasUnsignedFlag(s.args[1].GetType().Flag)
 
-	if forceToSigned && mysql.HasUnsignedFlag(s.args[0].GetType().Flag) {
-		if a < 0 {
-			return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", s.args[0].String(), s.args[1].String()))
+	switch {
+	case forceToSigned && isLHSUnsigned && isRHSUnsigned:
+		ua, ub, uMaxInt64, uMinInt64 := uint64(a), uint64(b), uint64(math.MaxInt64), uint64(math.MaxInt64+1)
```
Comment (XuHuaiyu) [inline expression/builtin_arithmetic.go:424]: uMinInt64  --> uAbsMinInt64

File: expression/builtin_arithmetic_vec.go [hunk 5]
```diff
@@ -400,12 +393,14 @@ func (b *builtinArithmeticMinusIntSig) minusFUS(result *chunk.Column, lhi64s, rh
 		}
 		lh, rh := lhi64s[i], rhi64s[i]
 
-		if lh < 0 {
-			return types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", b.args[0].String(), b.args[1].String()))
-		}
-
-		if (lh > 0 && -rh > math.MaxInt64-lh) || (lh < 0 && -rh < math.MinInt64-lh) {
-			return types.ErrOverflow.GenWithStackByArgs("BIGINT", fmt.Sprintf("(%s + %s)", b.args[0].String(), b.args[1].String()))
+		// lh >= 0 && rh >= 0 : never overflow
```
[the remark this answers is not in the document]
Comment (Tjianke) [reply expression/builtin_arithmetic_vec.go:396]: Sure we can, but I am not sure whether introducing extra function calls will worsen performance. I chose not to abstract these code into function, because in some other `builtinArithmetics` that met similar situations, `builtinArithmeticModIntSig` for instance, they did not abstract the check logic into function as well.

File: expression/builtin_arithmetic.go [hunk 6]
```diff
@@ -416,37 +416,48 @@ func (s *builtinArithmeticMinusIntSig) evalInt(row chunk.Row) (val int64, isNull
...
+		if (ua >= ub && ua-ub > uMaxInt64) || (ua < ub && ub-ua > uMinInt64) {
+			return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT", fmt.Sprintf("(%s - %s)", s.args[0].String(), s.args[1].String()))
 		}
-	}
-	if forceToSigned && mysql.HasUnsignedFlag(s.args[1].GetType().Flag) {
-		if b < 0 {
-			return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT UNSIGNED", fmt.Sprintf("(%s - %s)", s.args[0].String(), s.args[1].String()))
+	case forceToSigned && isLHSUnsigned && !isRHSUnsigned:
+		if (a < 0 && b > 0 && uint64(a) > uint64(math.MaxInt64+b)) ||
+			(a < 0 && b <= 0) ||
```
Comment (XuHuaiyu) [inline expression/builtin_arithmetic.go:430]: what about 
``` sql
mysql> select cast(-9223372036854775809 as unsigned) - 0;
+--------------------------------------------+
| cast(-9223372036854775809 as unsigned) - 0 |
+--------------------------------------------+
|                                          0 |
+--------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

Comment (Tjianke) [reply expression/builtin_arithmetic.go:430]: Wrong result is caused by a bug in cast function, check #22827.

As for the query `select cast(-9223372036854775809 as unsigned) - 0`, if we run an equivalent query `select cast(9223372036854775808 as unsigned) - 0;`, the output is within expectation, leading to overflow.

```
select cast(9223372036854775808 as unsigned) - 0;                                                                                                             
(1690, "BIGINT value is out of range in '(9223372036854775808 - 0)'")
```

File: expression/builtin_arithmetic.go (hunk 4 above)
Comment (Tjianke) [reply expression/builtin_arithmetic.go]: Renamed

File: expression/builtin_arithmetic_vec.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (XuHuaiyu) [reply expression/builtin_arithmetic_vec.go:396]: It'll be hard to maintain the code in the future if we do not extract the code.

File: expression/builtin_arithmetic.go (hunk 6 above)
Comment (XuHuaiyu) [reply expression/builtin_arithmetic.go:430]: It's my fault here.
The example above is the result of MySQL.
I test using this commit, TiDB returns the same result.

File: expression/builtin_arithmetic_vec.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Tjianke) [reply expression/builtin_arithmetic_vec.go:396]: I see, so do you think we should also extract overflow detection logic in other builtin functions as well, `builtinArithmeticModIntSig` for instance?

[the remark this answers is not in the document]
Comment (XuHuaiyu) [reply expression/builtin_arithmetic_vec.go]: We can do it in another PR is ok.
We'd better make a PR as small as possible to make it easy to be reviewed.

File: expression/builtin_arithmetic.go [hunk 7]
```diff
@@ -416,42 +479,44 @@ func (s *builtinArithmeticMinusIntSig) evalInt(row chunk.Row) (val int64, isNull
...
 		}
-	case !isLHSUnsigned && !isRHSUnsigned:
-		// We need `(a >= 0 && b == math.MinInt64)` due to `-(math.MinInt64) == math.MinInt64`.
-		// If `a<0 && b<=0`: `a-b` will not overflow even though b==math.MinInt64.
-		// If `a<0 && b>0`: `a-b` will not overflow only if `math.MinInt64<=a-b` satisfied
-		if (a >= 0 && b == math.MinInt64) || (a > 0 && -b > math.MaxInt64-a) || (a < 0 && -b < math.MinInt64-a) {
-			return 0, true, types.ErrOverflow.GenWithStackByArgs("BIGINT", fmt.Sprintf("(%s - %s)", s.args[0].String(), s.args[1].String()))
+	case !forceToSigned && !isLHSUnsigned && isRHSUnsigned:
+		err := s.checkOverflowSU(a, b)
+		if err != nil {
```
Comment (XuHuaiyu) [inline expression/builtin_arithmetic.go:518]: Can we check the err outside of switch-case

**Review by XuHuaiyu — COMMENTED** [review]
Did you check the source code of mysql?
Maybe we can use the same check logic of [Item_func_minus::int_op](https://github.com/mysql/mysql-server/blob/8.0/sql/item_func.cc#L2009) here, it seems to be easier.

File: expression/builtin_arithmetic.go (hunk 7 above)
Comment (Tjianke) [reply expression/builtin_arithmetic.go:518]: The problem is to detect overflow, we need signess of args and `forcedToSigned` flag, do you have any suggestion on how to distinguish different args and flags, without switch statement?

File: expression/integration_test.go [hunk 8]
```diff
@@ -3441,7 +3471,56 @@ func (s *testIntegrationSuite) TestArithmeticBuiltin(c *C) {
...
+	rs, err = tk.Exec("select cast(12 as unsigned) - (14);")
+	c.Assert(rs, NotNil)
+	rows, err = session.GetRows4Test(ctx, tk.Se, rs)
+	c.Assert(rows, IsNil)
+	c.Assert(err, NotNil)
+	c.Assert(err.Error(), Equals, "[types:1690]BIGINT UNSIGNED value is out of range in '(12 - 14)'")
+	c.Assert(rs.Close(), IsNil)
+
+	// minusSS overflow case: a - b > math.MaxInt64
+	rs, err = tk.Exec("select cast(9223372036854775807 as signed) - cast(-1 as signed);")
```
Comment (XuHuaiyu) [inline expression/integration_test.go:3497]: Can we use tk.QueryToErr() to replace this check logic

File: types/const_test.go [hunk 9]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
 	r.Check(testkit.Rows("helloworld"))
 }
 
+func (s *testMySQLConstSuite) TestIssue22387(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	ctx := context.Background()
+	tk.MustExec("set sql_mode=''")
+	rs, _ := tk.Exec("select 12 - cast(15 as unsigned);")
```
Comment (XuHuaiyu) [inline types/const_test.go:160]: I tested in MySQL 5.7. No matter the value of sql_mode, this query will raise the same error.

File: types/const_test.go [hunk 10]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	c.Assert(err, NotNil)
+	c.Assert(err.Error(), Equals, "[types:1690]BIGINT UNSIGNED value is out of range in '(12 - 15)'")
+	c.Assert(rs.Close(), IsNil)
+}
+
+func (s *testMySQLConstSuite) TestIssue22389(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	ctx := context.Background()
+	tk.MustExec("use test")
+	tk.MustExec("set sql_mode='NO_UNSIGNED_SUBTRACTION';")
```
Comment (XuHuaiyu) [inline types/const_test.go:172]: MySQL 5.7 will return an error despite of the sql_mode

File: types/const_test.go [hunk 11]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	c.Assert(err, NotNil)
+	c.Assert(err.Error(), Equals, "[types:1690]BIGINT value is out of range in '(test.tb5.a - test.tb5.b)'")
+	c.Assert(rs.Close(), IsNil)
+}
+
+func (s *testMySQLConstSuite) TestIssue22390(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	ctx := context.Background()
+	tk.MustExec("use test")
+	tk.MustExec("set sql_mode='';")
```
Comment (XuHuaiyu) [inline types/const_test.go:188]: ditto

File: types/const_test.go [hunk 12]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	rows, err := session.GetRows4Test(ctx, tk.Se, rs)
+	c.Assert(err, NotNil)
+	c.Assert(rows, IsNil)
+	c.Assert(err.Error(), Equals, "[types:1690]BIGINT value is out of range in '(test.tb5.a - test.tb5.b)'")
+	c.Assert(rs.Close(), IsNil)
+}
+
+func (s *testMySQLConstSuite) TestIssue22442(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("set sql_mode='';")
```
Comment (XuHuaiyu) [inline types/const_test.go:202]: ditto

File: types/const_test.go [hunk 13]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	tk.MustQuery("select cast(-1 as unsigned) - cast(-1 as unsigned);  ").Check(testkit.Rows("0"))
+}
+
+func (s *testMySQLConstSuite) TestIssue22444(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("set sql_mode='NO_UNSIGNED_SUBTRACTION'; ")
```
Comment (XuHuaiyu) [inline types/const_test.go:208]: ditto

File: types/const_test.go [hunk 14]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	tk.MustQuery("select cast(-1 as unsigned) - cast(-10000 as unsigned); ").Check(testkit.Rows("9999"))
+}
+
+func (s *testMySQLConstSuite) TestIssue22445(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("set sql_mode='NO_UNSIGNED_SUBTRACTION'; ")
```
Comment (XuHuaiyu) [inline types/const_test.go:214]: Add a test when `set sql_mode='NO_UNSIGNED_SUBTRACTION'`

File: types/const_test.go [hunk 15]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	tk.MustQuery("select cast(-12 as unsigned) - cast(-1 as unsigned); ").Check(testkit.Rows("-11"))
+}
+
+func (s *testMySQLConstSuite) TestIssue22446(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("set sql_mode='NO_UNSIGNED_SUBTRACTION'; ")
```
Comment (XuHuaiyu) [inline types/const_test.go:220]: mysql return the same value depite of the value of sql_mode

File: types/const_test.go [hunk 16]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	tk.MustQuery("select cast(-1 as unsigned) - 9223372036854775808").Check(testkit.Rows("9223372036854775807"))
+}
+
+func (s *testMySQLConstSuite) TestIssue22447(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("set sql_mode='NO_UNSIGNED_SUBTRACTION'; ")
```
Comment (XuHuaiyu) [inline types/const_test.go:226]: add a case for `set sql_mode=''`

File: types/const_test.go [hunk 17]
```diff
@@ -153,16 +153,226 @@ func (s *testMySQLConstSuite) TestPipesAsConcatMode(c *C) {
...
+	rs, err = tk.Exec("SELECT CAST(9223372036854775808 as UNSIGNED) - 0;")
+	rows, err = session.GetRows4Test(ctx, tk.Se, rs)
+	c.Assert(rows, IsNil)
+	c.Assert(err, NotNil)
+	c.Assert(err.Error(), Equals, "[types:1690]BIGINT value is out of range in '(9223372036854775808 - 0)'")
+	c.Assert(rs.Close(), IsNil)
+
+	tk.MustQuery("SELECT CAST(-1 as UNSIGNED) - (9223372036854775808);").Check(testkit.Rows("9223372036854775807"))
+
+	// 3.3 minusFUS, a >= 0 && b < 0 && (b == math.MinInt64 || -b > math.MaxInt64-a)
```
Comment (XuHuaiyu) [inline types/const_test.go:318]: outdated comment, and the others

Comment (Tjianke) [reply types/const_test.go]: Done.

**Review by XuHuaiyu — APPROVED** [review]
LGTM
