### PR TITLE
*: ref all the jobs before sending to jobToWorkerCh

### LINKED ISSUE #64666: [next-gen] data inconsistency in table after simulated kill tidb-worker repeatedly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run sysbench
2、add index for two tables
3、simulated kill all tidb-worker repeatedly

### 2. What did you expect to see? (Required)
data inconsistency in table if add index successfully

### 3. What did you see instead (Required)
data inconsistency in table after simulated kill tidb-worker repeatedly

case logs
admin check failed (Error 8223 (HY000): data inconsistency in table: sbtest2, index: index_test_1764052165225, handle: 5402730, index-values:"" != record-values:"handle: 5402730, values: [KindString 16960352122-53417868865-19761453644-60931175938-11266666891-26482692461-21719450064-35170464548-23376004353-52869623519]")
operatorLogs:
[2025-11-25 14:29:25] ###### start adding index
ALTER TABLE `sbtest2` ADD INDEX `index_test_1764052165225`(`c`)
[2025-11-25 14:29:25] ###### wait for ddl job finish
[2025-11-25 15:22:53] ###### ddl job finished
select job_id, db_name, table_name, job_type, create_time, start_time, end_time, state, query from information_schema.ddl_jobs where query = 'ALTER TABLE `sbtest2` ADD INDEX `index_test_1764052165225`(`c`)'
jobId: 7408, job type: add index, state: synced, comments: 
add index done, it takes: 53m27.992383292s
[2025-11-25 15:22:53] ###### start admin check

### 4. What is your TiDB version? (Required)
./tidb-server -V
Release Version: v9.0.0-beta.2.pre-810-gbf57e58
Edition: Enterprise
Git Commit Hash: https://github.com/pingcap/tidb/commit/bf57e58556e73b679c7c774a05392694eca8e25a
Git Branch: HEAD
UTC Build Time: 2025-11-24 03:31:04
GoVersion: go1.23.12
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Enterprise Extension Commit Hash: dc633aae52eb11b4e3549e3a7ef5b0ed14e159b1
Kernel Type: Next Generation

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #64666

Problem Summary:
In the generateAndSendJob function, we previously referenced one region job at a time and immediately sent it to jobToWorkerCh. If a job (especially an empty job) finished before the next job was referenced, the reference count could drop to 0, causing memoryIngestData to be cleaned unexpectedly. This prevented other jobs still being processed from accessing the data, leading to data inconsistency.
Only the partition table might meet this issue. Because we group keys by index id, not partition id, some ranges might cross many partitions, and the created region job might be empty and trigger this issue

### What changed and how does it work?
We modified the logic in generateAndSendJob to reference all jobs before sending them to jobToWorkerCh. Specifically, we first call job.ref(jobWg) for all generated jobs in a loop, and then send them to the channel one by one in a separate loop.

This ensures all jobs have their reference counts incremented before any of them are sent to the channel. Even if some jobs (like empty jobs) finish quickly and call done(), as long as other jobs still hold references, ingestData will not be cleaned prematurely. Only when all jobs complete and call done() will the reference count reach 0, at which point ingestData can be safely cleaned, preventing data inconsistency issues.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
Pass the tidb-x HA add index test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/backend/local/local.go [hunk 1]
```diff
@@ -1132,8 +1132,11 @@ func (local *Backend) generateAndSendJob(
 						}
 						return err
 					}
+					// reference the job to prevent the job from being GCed before being put into jobToWorkerCh.
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/local.go]:
```suggestion
					// we need to increase the ref count before sending jobs to
					// jobToWorkerCh, in case some job finished quickly and decrease
					// the ref count to zero and cause the data being released.
```

File: pkg/lightning/backend/local/local.go [hunk 2]
```diff
@@ -1276,6 +1279,35 @@ func (local *Backend) GetExternalEngine(engineUUID uuid.UUID) *external.Engine {
...
+		onDup := extEngine.GetOnDup()
+		if onDup == engineapi.OnDuplicateKeyRecord || onDup == engineapi.OnDuplicateKeyRemove {
+			return errors.Errorf("OnDuplicateKeyRecord and OnDuplicateKeyRemove are not yet implemented for local backend. " +
+				"When implementing these options, please also implement the statistics verification for them.")
+		}
+
+		// Verify the imported statistics after import.
+		// For external engine, use the total number of KVs loaded in LoadIngestData
+		// (i.e., len(e.memKVsAndBuffers.kvs) across all batches) as the expected count.
+		expectedLength := extEngine.GetTotalLoadedKVsCount()
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/local.go]:
```suggestion
		expectedKVCount := extEngine.GetTotalLoadedKVsCount()
```

File: pkg/lightning/backend/local/local.go [hunk 3]
```diff
@@ -1276,6 +1279,35 @@ func (local *Backend) GetExternalEngine(engineUUID uuid.UUID) *external.Engine {
 	return ext
 }
 
+// verifyImportedStatistics verifies the imported statistics for external engines.
+// It checks if OnDuplicateKeyRecord or OnDuplicateKeyRemove is used (which are not yet implemented),
+// and verifies that the imported length matches the expected length.
+func verifyImportedStatistics(e engineapi.Engine, importedLength int64) error {
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/local.go]:
```suggestion
// and verifies that the imported KV count matches the expected one.
func verifyImportedStatistics(e engineapi.Engine, importedKVCount int64) error {
```

**Comment by D3Hunter** [comment]
please also node in the detail that only partition table might meet this issue. as we are grouping keys by index id, not partition id, so some range might cross many partition, and the created region job might be empty and trigger this issue
