### PR TITLE
executor: correct range calculation for CHAR column

### LINKED ISSUE #10397: Incorrect range for CHAR column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

## 1. What did you do?

```sql
drop table if exists t;
create table t(a char(2) primary key, b char(2));
insert into t values("a ", "b ");
set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";
select * from t tmp where a = "a";
```

## 2. What did you expect to see?

the correct result should be empty:
```sql
MySQL(root@localhost:test) > select * from t tmp where a = "a";
Empty set (0.00 sec)
```

mysql version:
```sql
MySQL(root@localhost:test) > select version();
+-----------+
| version() |
+-----------+
| 8.0.11    |
+-----------+
1 row in set (0.00 sec)
```

## 3. What did you see instead?

In TiDB the result is:
```sql
TiDB(root@127.0.0.1:test) > select * from t tmp where a = "a";
+---+------+
| a | b    |
+---+------+
| a | b    |
+---+------+
1 row in set (0.00 sec)
```

the range is:
```sql
TiDB(root@127.0.0.1:test) > desc select * from t tmp where a = "a";
+-------------------+-------+------+---------------------------------------------------------------------+
| id                | count | task | operator info                                                       |
+-------------------+-------+------+---------------------------------------------------------------------+
| IndexLookUp_7     | 10.00 | root |                                                                     |
| ├─IndexScan_5     | 10.00 | cop  | table:tmp, index:a, range:["a","a"], keep order:false, stats:pseudo |
| └─TableScan_6     | 10.00 | cop  | table:t, keep order:false, stats:pseudo                             |
+-------------------+-------+------+---------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

actually the range should be: `["a ","a "]`

## 4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```sql
TiDB(root@127.0.0.1:test) > select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-beta.1-231-g78ecec45e
Git Commit Hash: 78ecec45e8c02d6a8747b1e95ee25373c93d3edd
Git Branch: master
UTC Build Time: 2019-05-09 01:11:02
GoVersion: go version go1.12.4 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### LINKED ISSUE #10398: Incorrect range for CHAR BINARY column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

## 1. What did you do?

```sql
drop table if exists t;
create table t(a char(2) binary primary key, b char(2));
insert into t values("  ", "  ");
insert into t values("a ", "b ");

-- case 1:
set @@sql_mode="";
select * from t tmp where a = "a ";

-- case 2:
set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";
select * from t tmp where a = "a  ";
```

## 2. What did you expect to see?

In MySQL the results of case 1 and case 2 are not empty:

```sql
MySQL(root@localhost:test) > -- case 1:
MySQL(root@localhost:test) > set @@sql_mode="";
Query OK, 0 rows affected (0.00 sec)

MySQL(root@localhost:test) > select * from t tmp where a = "a ";
+---+------+
| a | b    |
+---+------+
| a | b    |
+---+------+
1 row in set (0.00 sec)
```

```sql
MySQL(root@localhost:test) > -- case 2:
MySQL(root@localhost:test) > set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";
Query OK, 0 rows affected (0.00 sec)

MySQL(root@localhost:test) > select * from t tmp where a = "a  ";
+----+------+
| a  | b    |
+----+------+
| a  | b    |
+----+------+
1 row in set (0.00 sec)
```

MySQL version:
```sql
MySQL(root@localhost:test) > select version();
+-----------+
| version() |
+-----------+
| 8.0.11    |
+-----------+
1 row in set (0.00 sec)
```

## 3. What did you see instead?

In TiDB both results are empty:
```sql
TiDB(root@127.0.0.1:test) > -- case 1:
TiDB(root@127.0.0.1:test) > set @@sql_mode="";
Query OK, 0 rows affected (0.01 sec)

TiDB(root@127.0.0.1:test) > select * from t tmp where a = "a ";
Empty set (0.00 sec)

TiDB(root@127.0.0.1:test) > desc select * from t tmp where a = "a ";
+-------------------+-------+------+-----------------------------------------------------------------------+
| id                | count | task | operator info                                                         |
+-------------------+-------+------+-----------------------------------------------------------------------+
| IndexLookUp_7     | 10.00 | root |                                                                       |
| ├─IndexScan_5     | 10.00 | cop  | table:tmp, index:a, range:["a ","a "], keep order:false, stats:pseudo |
| └─TableScan_6     | 10.00 | cop  | table:t, keep order:false, stats:pseudo                               |
+-------------------+-------+------+-----------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

```sql
TiDB(root@127.0.0.1:test) > -- case 2:
TiDB(root@127.0.0.1:test) > set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";
Query OK, 0 rows affected (0.00 sec)

TiDB(root@127.0.0.1:test) > select * from t tmp where a = "a  ";
Empty set (0.00 sec)

TiDB(root@127.0.0.1:test) > desc select * from t tmp where a = "a  ";
+-------------------+-------+------+-------------------------------------------------------------------------+
| id                | count | task | operator info                                                           |
+-------------------+-------+------+-------------------------------------------------------------------------+
| IndexLookUp_7     | 10.00 | root |                                                                         |
| ├─IndexScan_5     | 10.00 | cop  | table:tmp, index:a, range:["a  ","a  "], keep order:false, stats:pseudo |
| └─TableScan_6     | 10.00 | cop  | table:t, keep order:false, stats:pseudo                                 |
+-------------------+-------+------+-------------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

## 4. What version of TiDB are you using?

```sql
TiDB(root@127.0.0.1:test) > select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-beta.1-231-g78ecec45e
Git Commit Hash: 78ecec45e8c02d6a8747b1e95ee25373c93d3edd
Git Branch: master
UTC Build Time: 2019-05-09 01:11:02
GoVersion: go version go1.12.4 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by zz-jason**
### What problem does this PR solve? 

fix the wrong range calculation for:
- point get char[n], char[n] binary, binary[n] column
- index lookup char[n], char[n] binary, binary[n] column

This PR can:
- close #10397 
- close #10398 

### What is changed and how it works?

specially handle the "PAD_CHAR_TO_FULL_LENGTH" for char column.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: executor/point_get.go [hunk 1]
```diff
@@ -115,22 +119,82 @@ func (e *PointGetExecutor) Next(ctx context.Context, req *chunk.RecordBatch) err
...
+	targetStr, err := val.ToString()
+	if err != nil {
+		return val, err
+	}
+
+	hasBinaryFlag := mysql.HasBinaryFlag(ft.Flag)
+	isVarchar := ft.Tp == mysql.TypeVarString || ft.Tp == mysql.TypeVarchar
+	isChar := ft.Tp == mysql.TypeString
+	isBinary := ft.Tp == mysql.TypeString && ft.Collate == charset.CollationBin
+	isVarBinary := ft.Tp == mysql.TypeString && ft.Collate == charset.CollationBin
```
Comment (qw4990) [inline executor/point_get.go]: The conditions of `isVarBinary` it the same as `isBinary`?

File: executor/point_get_test.go [hunk 2]
```diff
@@ -56,3 +56,242 @@ func (s *testSuite1) TestPointGet(c *C) {
...
+
+	// Test trailing spaces without sql mode `PAD_CHAR_TO_FULL_LENGTH`.
+	tk.MustExec(`set @@sql_mode="";`)
+	tk.MustPointGet(`select * from t where a = "a";`).Check(testkit.Rows(`a b`))
+	tk.MustPointGet(`select * from t where a = "a ";`).Check(testkit.Rows())
+	tk.MustPointGet(`select * from t where a = "a  ";`).Check(testkit.Rows())
+
+	// Test trailing spaces with sql mode `PAD_CHAR_TO_FULL_LENGTH`.
+	tk.MustExec(`set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";`)
+	tk.MustPointGet(`select * from t where a = "a";`).Check(testkit.Rows())
```
Comment (qw4990) [inline executor/point_get_test.go]: In my MySQL 5.7.25, this SQL returns `a b` 😱 ...
```
ERROR 1054 (42S22): Unknown column 'version' in 'field list'
mysql> select version();
+-----------+
| version() |
+-----------+
| 5.7.25    |
+-----------+
1 row in set (0.00 sec)

mysql> set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";
Query OK, 0 rows affected (0.00 sec)

mysql> select * from t where a = "a";
+----+------+
| a  | b    |
+----+------+
| a  | b    |
+----+------+
1 row in set (0.00 sec)
```

Comment (zz-jason) [reply executor/point_get_test.go]: I think it's a bug according to the mysql 5.7 document, and it's fixed in mysql 8.0:
```sql
MySQL(root@localhost:test) > drop table t;
Query OK, 0 rows affected (0.11 sec)

MySQL(root@localhost:test) > create table t(a char(2) primary key, b char(2));
Query OK, 0 rows affected (0.06 sec)

MySQL(root@localhost:test) > insert into t values("a ", "b ");
Query OK, 1 row affected (0.03 sec)

MySQL(root@localhost:test) > set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";
Query OK, 0 rows affected (0.01 sec)

MySQL(root@localhost:test) > select * from t where a = "a";
Empty set (0.00 sec)

MySQL(root@localhost:test) > select version();
+-----------+
| version() |
+-----------+
| 8.0.11    |
+-----------+
1 row in set (0.00 sec)
```

File: executor/point_get.go (hunk 1 above)
Comment (zz-jason) [reply executor/point_get.go]: fixed

File: executor/point_get_test.go (hunk 2 above)
Comment (qw4990) [reply executor/point_get_test.go]: In my local MySQL 8.0.12, all tests below return `a, b`:
```
	tk.MustExec(`truncate table t;`)
	tk.MustExec(`insert into t values("a ", "b ");`)

	// Test trailing spaces without sql mode `PAD_CHAR_TO_FULL_LENGTH`.
	tk.MustExec(`set @@sql_mode="";`)
	tk.MustPointGet(`select * from t where a = "a";`).Check(testkit.Rows(`a b`))
	tk.MustPointGet(`select * from t where a = "a ";`).Check(testkit.Rows())
	tk.MustPointGet(`select * from t where a = "a  ";`).Check(testkit.Rows())

	// Test trailing spaces with sql mode `PAD_CHAR_TO_FULL_LENGTH`.
	tk.MustExec(`set @@sql_mode="PAD_CHAR_TO_FULL_LENGTH";`)
	tk.MustPointGet(`select * from t where a = "a";`).Check(testkit.Rows())
	tk.MustPointGet(`select * from t where a = "a ";`).Check(testkit.Rows(`a b`))
	tk.MustPointGet(`select * from t where a = "a  ";`).Check(testkit.Rows())
```

And in MySQL document: `As of MySQL 8.0.13, PAD_CHAR_TO_FULL_LENGTH is deprecated. It will be removed in a future version of MySQL.`

So it seems that MySQL 8.0.11~8.0.13 have different behavior on `PAD_CHAR_TO_FULL_LENGTH `.......... 🤣

Comment (zz-jason) [reply executor/point_get_test.go]: Orz

File: util/ranger/points.go [hunk 3]
```diff
@@ -265,6 +281,59 @@ func (r *builder) buildFormBinOp(expr *expression.ScalarFunction) []point {
 	return nil
 }
 
+// HandlePadCharToFullLength handles the "PAD_CHAR_TO_FULL_LENGTH" sql mode for
+// CHAR[N] index columns.
+// NOTE: kv.ErrNotExist is returned to indicate that this value can not match
+//		 any (key, value) pair in tikv storage. This error should be handled by
+//		 the caller.
+func HandlePadCharToFullLength(sc *stmtctx.StatementContext, ft *types.FieldType, val types.Datum) (types.Datum, error) {
+	targetStr, err := val.ToString()
```
Comment (lamxTyler) [inline util/ranger/points.go]: Can we only call `TopString` for the needed types?

Comment (zz-jason) [reply util/ranger/points.go]: Comment addressed, PTAL. Thanks.
