### PR TITLE
dxf: add API to change max runtime slots of task in nextgen

### LINKED ISSUE #65192: dxf: add a mechanism for global sort tasks to workaround OOM issues in nextgen
## Enhancement
global-sort cache and sort KVs in memory, so the memory usage of DXF nodes is very high, it's prone to be OOM if some component failed to limit memory usage below what we have allocated for the task through slots, causing the TiDB repeatly restart, such as this issue https://github.com/pingcap/tidb/issues/64911

suppose we have a task with concurrency 8 on on 8c16g node, it OOM, i.e. the task will over allocate memory during execution, suppose it will over allocated memory around the memory share of 1 slot(2G), it means the task allocated 8 slots, but to successfully run, it need resource of about 9 slots.

currently, `task.Concurrent` field is used for both slot allocation and task running concurrency. we want to separate this 2 concerns, so we can reduce the concurrency without reduce the slots allocated.

Note: we have manually to change the concurrency to workaround OOM, as we don't have a way in kernel to detect whether the instance has OOM and restart repeatedly. since OOM is a quite rare event, and it's ok for now and current goal.

for the above example, the node only have 8 slots, and the task already takes all the slots, so we cannot workaround the OOM by increase resource, but we can reduce the concurrency. if we can allocate 8 slots, but run with concurrency <= 7, it can also run without OOM.

#### Q: can we reduce the `task.Concurrent` directly on OOM?

it's ok if there are only 1 task running on DXF. but if there are many tasks, they might allocate resources too, reducing the `task.Concurrent` directly will also reduce its allocated slots, other tasks might successfully allocate those resource and start running. since the task that trigger OOM will over allocate memory, running those tasks together it might still cause OOM.

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #65192

Problem Summary:

### What changed and how does it work?
add a API in SYSTEM ks only to change the MaxRuntimeSlots param for a task
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

```
[root@tc-tidb-0 /]# curl -X POST "localhost:10080/dxf/task/2/max_runtime_slots?value=5&target_step=2&target_step=3"
{
 "max_runtime_slots": 5,
 "required_slots": 7,
 "target_steps": [
  "post-process",
  "encode"
 ],
 "task_id": 2,
 "task_key": "SYSTEM/ImportInto/2"
}
```
during encode step, call above API, then we restart the tidb, we can see before restart encode uses 7 slots, after that,  the encode/post-process use 5 slots, while ingest uses 7
```
[2025/12/29 10:53:14.260 +00:00] [INFO] [task_executor.go:417] ["execute task step start"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=encode] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=7, Mem=12.9GiB]"]
[2025/12/29 10:54:47.397 +00:00] [INFO] [task_executor.go:444] ["execute task step completed"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=encode] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=7, Mem=12.9GiB]"] [takeTime=1m33.136720262s] []
[2025/12/29 10:54:57.149 +00:00] [INFO] [task_executor.go:417] ["execute task step start"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=encode] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=5, Mem=9.214GiB]"]
[2025/12/29 10:57:42.489 +00:00] [INFO] [task_executor.go:444] ["execute task step completed"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=encode] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=5, Mem=9.214GiB]"] [takeTime=2m45.339504062s] []
[2025/12/29 10:57:42.500 +00:00] [INFO] [task_executor.go:417] ["execute task step start"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=ingest] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=7, Mem=12.9GiB]"]
[2025/12/29 10:59:59.738 +00:00] [INFO] [task_executor.go:444] ["execute task step completed"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=ingest] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=7, Mem=12.9GiB]"] [takeTime=2m17.238811013s] []
[2025/12/29 10:59:59.739 +00:00] [INFO] [task_executor.go:417] ["execute task step start"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=post-process] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=5, Mem=9.214GiB]"]
[2025/12/29 11:00:05.264 +00:00] [INFO] [task_executor.go:444] ["execute task step completed"] [keyspaceName=SYSTEM] [task-id=2] [task-key=SYSTEM/ImportInto/2] [step=post-process] [mem-limit-percent=0.7] [server-mem-limit=80%] [resource="[CPU=5, Mem=9.214GiB]"] [takeTime=5.525659153s] []
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/server/handler/tikvhandler/dxf.go [hunk 1]
```diff
@@ -40,25 +42,19 @@ const (
...
 }
 
 // ServeHTTP handles request of resigning ddl owner.
-func (h *DXFScheduleStatusHandler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
+func (*DXFScheduleStatusHandler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
 	if req.Method != http.MethodGet {
 		handler.WriteError(w, errors.Errorf("This api only support GET method"))
 		return
 	}
-	if h.store.GetKeyspace() != keyspace.System {
```
Comment (D3Hunter) [inline pkg/server/handler/tikvhandler/dxf.go:58]: now, those API are not registered in normal keyspace
