### PR TITLE
planner: rewrite semi join when to predicate push down

### LINKED ISSUE #58958: `SEMI_JOIN_REWRITE` hint failed when inexplicit cast happened on JOIN KEY
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t1(a int);
create table t2(a varchar(10));
create table t3(a int);

explain select * from t1 where exists(select /*+ semi_join_rewrite() */ 1 from t2 where t1.a=t2.a);
explain select * from t1 where exists(select /*+ semi_join_rewrite() */ 1 from t3 where t1.a=t3.a);
```

### 2. What did you expect to see? (Required)

Hints inside two SQLs all worked.

### 3. What did you see instead (Required)

```
mysql> explain select * from t1 where exists(select /*+ semi_join_rewrite() */ 1 from t2 where t1.a=t2.a);
+------------------------------+----------+-----------+---------------+--------------------------------------------------------------------+
| id                           | estRows  | task      | access object | operator info                                                      |
+------------------------------+----------+-----------+---------------+--------------------------------------------------------------------+
| HashJoin_11                  | 8000.00  | root      |               | semi join, left side:Projection_13, equal:[eq(Column#6, Column#7)] |
| ├─Projection_16(Build)       | 10000.00 | root      |               | cast(test.t2.a, double BINARY)->Column#7                           |
| │ └─TableReader_18           | 10000.00 | root      |               | data:TableFullScan_17                                              |
| │   └─TableFullScan_17       | 10000.00 | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                     |
| └─Projection_13(Probe)       | 10000.00 | root      |               | test.t1.a, cast(test.t1.a, double BINARY)->Column#6                |
|   └─TableReader_15           | 10000.00 | root      |               | data:TableFullScan_14                                              |
|     └─TableFullScan_14       | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                     |
+------------------------------+----------+-----------+---------------+--------------------------------------------------------------------+
7 rows in set, 1 warning (0.01 sec)

mysql> explain select * from t1 where exists(select /*+ semi_join_rewrite() */ 1 from t3 where t1.a=t3.a);
+----------------------------------+----------+-----------+---------------+----------------------------------------------------------+
| id                               | estRows  | task      | access object | operator info                                            |
+----------------------------------+----------+-----------+---------------+----------------------------------------------------------+
| HashJoin_12                      | 9990.00  | root      |               | inner join, equal:[eq(test.t1.a, test.t3.a)]             |
| ├─HashAgg_22(Build)              | 7992.00  | root      |               | group by:test.t3.a, funcs:firstrow(test.t3.a)->test.t3.a |
| │ └─TableReader_23               | 7992.00  | root      |               | data:HashAgg_17                                          |
| │   └─HashAgg_17                 | 7992.00  | cop[tikv] |               | group by:test.t3.a,                                      |
| │     └─Selection_21             | 9990.00  | cop[tikv] |               | not(isnull(test.t3.a))                                   |
| │       └─TableFullScan_20       | 10000.00 | cop[tikv] | table:t3      | keep order:false, stats:pseudo                           |
| └─TableReader_16(Probe)          | 9990.00  | root      |               | data:Selection_15                                        |
|   └─Selection_15                 | 9990.00  | cop[tikv] |               | not(isnull(test.t1.a))                                   |
|     └─TableFullScan_14           | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                           |
+----------------------------------+----------+-----------+---------------+----------------------------------------------------------+
9 rows in set (0.00 sec)
```

The first one failed.

### 4. What is your TiDB version? (Required)

current master.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #58958

Problem Summary:

### What changed and how does it work?

When we perform predicate pushdown, we simplify the predicates. After simplification, the join may have the opportunity to undergo semi join rewrite. Therefore, we attempt semi join rewrite on the join that has undergone predicate pushdown.

Additionally, there is another issue here. When we process LogicalApply and call predicate pushdown, the object being operated on is actually a LogicalJoin. If we return the LogicalJoin at this point, it will cause problems. Therefore, the correct approach here is to return p.Self().

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 1]
```diff
@@ -1774,6 +1776,97 @@ func mergeOnClausePredicates(p *LogicalJoin, predicates []expression.Expression)
...
+	subAgg.BuildSelfKeyInfo(subAgg.Schema())
+	innerJoin := LogicalJoin{
+		JoinType:        base.InnerJoin,
+		HintInfo:        p.HintInfo,
+		PreferJoinType:  p.PreferJoinType,
+		PreferJoinOrder: p.PreferJoinOrder,
+		EqualConditions: make([]*expression.ScalarFunction, 0, len(p.EqualConditions)),
+	}.Init(p.SCtx(), p.QueryBlockOffset())
+	innerJoin.SetChildren(p.Children()[0], subAgg)
+	innerJoin.SetSchema(expression.MergeSchema(p.Children()[0].Schema().Clone(), subAgg.Schema().Clone()))
```
Comment (hawkingrei) [inline pkg/planner/core/operator/logicalop/logical_join.go:1860]: This schema needs to be cloned; otherwise, there will be problems.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 2]
```diff
@@ -1774,6 +1776,97 @@ func mergeOnClausePredicates(p *LogicalJoin, predicates []expression.Expression)
...
+// will be rewriten to:
+//
+//	select * from t join (select a from s group by a) s on t.a = s.a;
+func (p *LogicalJoin) SemiJoinRewrite() (base.LogicalPlan, error) {
+	// If it's not a join, or not a (outer) semi join. We just return it since no optimization is needed.
+	// Actually the check of the preferRewriteSemiJoin is a superset of checking the join type. We remain them for a better understanding.
+	if !(p.JoinType == base.SemiJoin || p.JoinType == base.LeftOuterSemiJoin) {
+		return p.Self(), nil
+	}
+	if _, ok := p.Self().(*LogicalApply); ok {
```
Comment (hawkingrei) [inline pkg/planner/core/operator/logicalop/logical_join.go:1796]: We don't support apply, so we skip here.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 3]
```diff
@@ -1774,6 +1776,97 @@ func mergeOnClausePredicates(p *LogicalJoin, predicates []expression.Expression)
...
+		return p.Self(), nil
+	}
+	// Gate by hint or session variable.
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_join.go]:
```suggestion
	// Get by hint or session variable.
```

Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Updated

**Review by winoros — APPROVED** [review]
