### PR TITLE
planner: fix the wrong join estimation depending on missing or uninitialized stats

### LINKED ISSUE #61602: planner: wrong Join estimation depending on uninitialized or missing stats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Root Cause:
    1. In join estimation, we use `left-rows*right-rows/max(left-ndv, right-ndv)`. 
    2. When deriving NDV from index-stats, we didn't check whether it was loaded or missing. After adding a new index without analyzing, the index-stats might be missing, 
    3. If it's missing, we'll use the wrong `NDV=0 or 1` to calculate join estimation, and finally get a high error result.

See the pic below, the join estimation has a huge error:

Image

### 4. What is your TiDB version? (Required)

v7.5.6

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #61602

Problem Summary: planner: fix the wrong join estimation depending on missing or uninitialized stats

### What changed and how does it work?

planner: fix the wrong join estimation depending on missing or uninitialized stats

It's hard to construct test cases for this issue since it depends on stats cache's status. So I tested it locally, and this PR can work for this scenario:

image

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/stats.go [hunk 1]
```diff
@@ -472,7 +472,7 @@ func getGroupNDVs(ds *logicalop.DataSource) []property.GroupNDV {
 					break
 				}
 			}
-			if match {
+			if match && idx.IsEssentialStatsLoaded() {
```
Comment (hawkingrei) [inline pkg/planner/core/stats.go:475]: Can you add some test cases for it?

Comment (qw4990) [reply pkg/planner/core/stats.go:475]: It's hard to add test cases for this issue since it depends on stats cache's status, but I've tested it locally, please see the PR description.

File: pkg/planner/core/stats.go [hunk 2]
```diff
@@ -472,7 +472,7 @@ func getGroupNDVs(ds *logicalop.DataSource) []property.GroupNDV {
 					break
 				}
 			}
-			if match {
```
Comment (elsa0520) [inline pkg/planner/core/stats.go:475]: If there is no stats in the cache which means that it will return false in here. So what is the behavior of this situation ?

File: pkg/planner/core/stats.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/planner/core/stats.go:475]: Get

Comment (hawkingrei) [reply pkg/planner/core/stats.go:475]: You can update the result of the integration test.

**Review by AilinKid — APPROVED** [review]

File: tests/integrationtest/r/executor/index_lookup_merge_join.result [hunk 3]
```diff
@@ -11,14 +11,12 @@ insert into t1 values(1,1,1,1),(2,2,2,2),(3,3,3,3);
...
-│ └─IndexLookUp	10000.00	root		
-│   ├─IndexFullScan(Build)	10000.00	cop[tikv]	table:t1, index:PRIMARY(a, b, c)	keep order:true, desc, stats:pseudo
-│   └─TableRowIDScan(Probe)	10000.00	cop[tikv]	table:t1	keep order:false, stats:pseudo
-└─IndexLookUp(Probe)	10000.00	root		
-  ├─IndexRangeScan(Build)	10000.00	cop[tikv]	table:t2, index:PRIMARY(a, b, c)	range: decided by [eq(executor__index_lookup_merge_join.t2.a, executor__index_lookup_merge_join.t1.a) eq(executor__index_lookup_merge_join.t2.b, executor__index_lookup_merge_join.t1.b) eq(executor__index_lookup_merge_join.t2.c, executor__index_lookup_merge_join.t1.c)], keep order:false, stats:pseudo
-  └─TableRowIDScan(Probe)	10000.00	cop[tikv]	table:t2	keep order:false, stats:pseudo
+Sort	12500.00	root		executor__index_lookup_merge_join.t1.a:desc
+└─HashJoin	12500.00	root		left outer join, left side:TableReader, equal:[eq(executor__index_lookup_merge_join.t1.a, executor__index_lookup_merge_join.t2.a) eq(executor__index_lookup_merge_join.t1.c, executor__index_lookup_merge_join.t2.c) eq(executor__index_lookup_merge_join.t1.b, executor__index_lookup_merge_join.t2.b)]
```
Comment (qw4990) [inline tests/integrationtest/r/executor/index_lookup_merge_join.result:15]: `12500` seems more reasonable, the prior `100000000.00` it not accurate.

File: pkg/planner/core/stats.go (hunk 1 above)
Comment (0xPoe) [inline pkg/planner/core/stats.go:475]: Can we add some comments to explain why we need this extra check? Thanks!

**Review by 0xPoe — COMMENTED** [review]
Thanks!

**Review by hawkingrei — APPROVED** [review]
