### PR TITLE
*: support tidb_redact_log for explain

### LINKED ISSUE #54565: The tidb_redact_log cannot be applied to the explain.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int primary key);
set session tidb_redact_log=MARKER;
explain select * from t where a = 1;
```

### 2. What did you expect to see? (Required)

```
+---------------------+-----------+-----------+---------------+--------------------------------+
| id                  | estRows   | task      | access object | operator info                  |
+---------------------+-----------+-----------+---------------+--------------------------------+
| TableReader_7       | 174.87    | root      | partition:p1  | data:Selection_6               |
| └─Selection_6       | 174.87    | cop[tikv] |               | eq(test.t.a, <1>)                |
|   └─TableFullScan_5 | 174868.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+---------------------+-----------+-----------+---------------+--------------------------------+
```
### 3. What did you see instead (Required)

```
+---------------------+-----------+-----------+---------------+--------------------------------+
| id                  | estRows   | task      | access object | operator info                  |
+---------------------+-----------+-----------+---------------+--------------------------------+
| TableReader_7       | 174.87    | root      | partition:p1  | data:Selection_6               |
| └─Selection_6       | 174.87    | cop[tikv] |               | eq(test.t.a, 1)                |
|   └─TableFullScan_5 | 174868.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+---------------------+-----------+-----------+---------------+--------------------------------+
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #54565

Problem Summary:

### What changed and how does it work?

The main issue is that TiDB's explain function does not support tidb_redact_log, which has caused this problem to occur.

Due to the substantial size of this PR, I will outline the modifications made and the tests conducted.

#### The changement of ```StringCtx```

```StringCtx``` is used to generate information in the explain function and is also utilized in log generation. Therefore, it cannot directly read ```ctx``` to determine the redact mode.

So the changement of expression package is to add the ```redact``` parameter into ```StringCtx``` and force using the ```redactDisable``` mode when to raise the error.

so I refactor the  ```StringWithCtx```'s implementation of ```Constant```,```Column```. but ```planner/core.ToString/StringifyExpressionsWithCtx``` is to print the debug info for testing. so it forces to use the ```redactDisable```

```pkg/util/ranger/types.go``` is to support the redact for the ```ranger```.

#### the changement of the ```planner```

The main focus is on the physical operator to resolve the explain output. The primary modifications include enabling the expression to support redaction by passing the redact parameter into the expression's explain method. Additionally, some parameters of the operator itself are subjected to redaction.

#### the changement of the ```ranger```

Enable the range to support redaction mode.

#### the main test cases 

- [x] pkg/planner/core/tests/redact
- [x] pkg/planner/core/plan_cache_test.go  
      - avoid plan cache polluting by the redact.

### Check List

Tests 

- [x] Unit test

1. I add some test cases to make redact results right
2. To prevent redaction from affecting the plan cache and plan digest tests, specific tests were conducted for different redaction scenarios to observe the plan cache hit rate.

- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: pkg/planner/core/explain.go [hunk 1]
```diff
@@ -202,17 +205,18 @@ func (p *PhysicalTableScan) OperatorInfo(normalized bool) string {
...
-				buffer.WriteString(AccessCondition.StringWithCtx(ectx))
+				buffer.WriteString(AccessCondition.StringWithCtx(ectx, redact))
 			}
 			buffer.WriteString("], ")
 		}
 	} else if len(p.Ranges) > 0 {
 		if normalized {
 			buffer.WriteString("range:[?,?], ")
 		} else if !p.isFullScan() {
+			redact := p.SCtx().GetSessionVars().EnableRedactLog
```
Comment (windtalker) [inline pkg/planner/core/explain.go:216]: Why not use the `redact` declared in L189

File: pkg/expression/explain.go [hunk 2]
```diff
@@ -166,32 +178,50 @@ func (expr *Constant) format(dt types.Datum) string {
...
 			}
 		case *Constant:
-			v := expr.StringWithCtx(ctx)
+			redactOn := redactMode == errors.RedactLogEnable
+			RedactMarker := redactMode == errors.RedactLogMarker
+			v := expr.StringWithCtx(ctx, errors.RedactLogDisable)
 			length := 64
 			if len(v) < length {
-				builder.WriteString(v)
+				if redactOn {
```
Comment (windtalker) [inline pkg/expression/explain.go:198]: why not call `writeRedactMarker` here?

File: pkg/expression/explain.go [hunk 3]
```diff
@@ -166,32 +178,50 @@ func (expr *Constant) format(dt types.Datum) string {
...
+				} else if RedactMarker {
+					builder.WriteString("‹")
+					builder.WriteString(v)
+					builder.WriteString("›")
+				} else {
+					builder.WriteString(v)
+				}
 			} else {
-				builder.WriteString(v[:length])
+				if redactOn {
```
Comment (windtalker) [inline pkg/expression/explain.go:208]: Ditto

File: pkg/util/ranger/types.go [hunk 4]
```diff
@@ -173,15 +173,38 @@ func HasFullRange(ranges []*Range, unsignedIntHandle bool) bool {
...
+		return input
+	} else if redact == errors.RedactLogEnable {
+		return "?"
+	}
+	return fmt.Sprintf("‹%s›", input)
+}
+
 // String implements the Stringer interface.
+// don't use it in the product.
 func (ran *Range) String() string {
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/util/ranger/types.go:190]: In fact, we use it in the UT for planner package.

File: pkg/expression/explain.go [hunk 5]
```diff
@@ -29,10 +30,10 @@ import (
 
 // ExplainInfo implements the Expression interface.
 func (expr *ScalarFunction) ExplainInfo(ctx EvalContext) string {
-	return expr.explainInfo(ctx, false)
+	return expr.explainInfo(ctx, false, ctx.GetTiDBRedactLog() == errors.RedactLogMarker)
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/expression/explain.go:33]: Now, it is removed.

File: pkg/executor/aggfuncs/func_group_concat.go [hunk 6]
```diff
@@ -74,9 +75,9 @@ func (e *baseGroupConcat4String) handleTruncateError(ctx AggFuncUpdateContext) (
 
 	if atomic.CompareAndSwapInt32(e.truncated, 0, 1) {
 		if !tc.Flags().TruncateAsWarning() {
-			return expression.ErrCutValueGroupConcat.GenWithStackByArgs(e.args[0].StringWithCtx(ctx))
+			return expression.ErrCutValueGroupConcat.GenWithStackByArgs(e.args[0].StringWithCtx(ctx, errors.RedactLogDisable))
 		}
-		tc.AppendWarning(expression.ErrCutValueGroupConcat.FastGenByArgs(e.args[0].StringWithCtx(ctx)))
+		tc.AppendWarning(expression.ErrCutValueGroupConcat.FastGenByArgs(e.args[0].StringWithCtx(ctx, errors.RedactLogDisable)))
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/executor/aggfuncs/func_group_concat.go:80]: Slow log have supported the ```tidb_redact_log```. it have been tracked in the https://github.com/pingcap/tidb/issues/51306. We can consider it as the default behavior.

File: pkg/planner/core/logical_table_scan.go [hunk 7]
```diff
@@ -50,7 +51,7 @@ func (ts *LogicalTableScan) ExplainInfo() string {
 	ectx := ts.SCtx().GetExprCtx().GetEvalCtx()
 	buffer := bytes.NewBufferString(ts.Source.ExplainInfo())
 	if ts.Source.HandleCols != nil {
-		fmt.Fprintf(buffer, ", pk col:%s", ts.Source.HandleCols.StringWithCtx(ectx))
+		fmt.Fprintf(buffer, ", pk col:%s", ts.Source.HandleCols.StringWithCtx(ectx, errors.RedactLogDisable))
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/logical_table_scan.go:54]: It can been updated to care about redact.

File: pkg/expression/explain.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/expression/explain.go]: It has been refacted.

File: pkg/expression/explain.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/expression/explain.go]: Done

**Review by windtalker — APPROVED** [review]
lgtm

**Review by lance6716 — COMMENTED** [review]
/approve

File: pkg/planner/core/exhaust_physical_plans.go [hunk 8]
```diff
@@ -1018,13 +1018,14 @@ func (ijHelper *indexJoinBuildHelper) buildRangeDecidedByInformation(idxCols []*
...
 	ectx := ijHelper.join.SCtx().GetExprCtx().GetEvalCtx()
+	redact := ectx.GetTiDBRedactLog()
 	for _, access := range ijHelper.chosenAccess {
 		if !isFirst {
 			buffer.WriteString(" ")
 		} else {
 			isFirst = false
 		}
-		fmt.Fprintf(buffer, "%v", access.StringWithCtx(ectx))
+		fmt.Fprintf(buffer, "%v", access.StringWithCtx(ectx, redact))
```
Comment (hawkingrei) [inline pkg/planner/core/exhaust_physical_plans.go:1028]: It is to build the range info which is used in explain.

File: pkg/expression/constant.go [hunk 9]
```diff
@@ -149,9 +150,14 @@ func (c *Constant) StringWithCtx(ctx ParamValues) string {
...
-		return c.DeferredExpr.StringWithCtx(ctx)
+		return c.DeferredExpr.StringWithCtx(ctx, redact)
 	}
-	return fmt.Sprintf("%v", c.Value.GetValue())
+	if redact == perrors.RedactLogDisable {
+		return fmt.Sprintf("%v", c.Value.GetValue())
+	} else if redact == perrors.RedactLogMarker {
+		return fmt.Sprintf("‹%v›", c.Value.GetValue())
+	}
+	return "?"
```
Comment (tangenta) [inline pkg/expression/constant.go:160]: String comparison is slow. Why not use a custom type like `type RedactOpt int8` instead?

Comment (hawkingrei) [reply pkg/expression/constant.go:160]: The root cause is that this enum was originally defined as a string. This also involves the slow log and other sections controlled by tidb_redact_log. Therefore, if we need to make changes, it would be better to create a new PR to address the issue

**Review by tangenta — APPROVED** [review]

**Review by qw4990 — APPROVED** [review]
