### PR TITLE
variables: add constraints on tidb_super_read_only when tidb_restricted_read_only is turned on

### LINKED ISSUE #31745: turning on tidb_restricted_read_only doesn't affects super_read_only
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

when turning on tidb_restricted_read_only it is also meant to turn on tidb_super_read_only, and when tidb_restricted_read_only is on, the user can't turn off tidb_super_read_only.

### 2. What did you expect to see? (Required)

as described

### 3. What did you see instead (Required)

the constraints are not enforced

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #31745 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below) @SunRunAway 
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fixed a bug that turning on tidb_restricted_read_only won't automatically turn on tidb_super_read_only
```

### CODE REVIEW

File: domain/sysvar_cache.go [hunk 1]
```diff
@@ -229,7 +229,14 @@ func (do *Domain) checkEnableServerGlobalVar(name, sVal string) {
...
 	case variable.TiDBRestrictedReadOnly:
-		variable.RestrictedReadOnly.Store(variable.TiDBOptOn(sVal))
+		on := variable.TiDBOptOn(sVal)
+		if on {
+			// when restricted readonly is on, super readonly must be on
+			variable.VarTiDBSuperReadOnly.Store(on)
+		}
+		variable.RestrictedReadOnly.Store(on)
+	case variable.TiDBSuperReadOnly:
+		variable.VarTiDBSuperReadOnly.Store(variable.TiDBOptOn(sVal))
```
Comment (morgo) [inline domain/sysvar_cache.go:239]: Can you make the code here match the `SetGlobal` func for the sysvar?

We only execute this code here when receiving a notification from etcd, but the behavior should be the same when running without etcd so we can test in the testsuite.

(In future, we might eliminate the code here and run the `SetGlobal` func on each tidb-instance, but that's not the case currently.)

Comment (ichn-hu) [reply domain/sysvar_cache.go]: sure

**Comment by ichn-hu** [comment]
@morgo PTAL again, thanks

File: sessionctx/variable/sysvar.go [hunk 2]
```diff
@@ -1119,7 +1119,29 @@ var defaultSysVars = []*SysVar{
...
+			result, err := s.GlobalVarsAccessor.GetGlobalSysVar(TiDBRestrictedReadOnly)
+			if err != nil {
+				return err
+			}
+			if TiDBOptOn(result) {
+				return fmt.Errorf("can't turn off %s when %s is on", TiDBSuperReadOnly, TiDBRestrictedReadOnly)
+			}
+		}
+		return nil
+	}},
```
Comment (morgo) [inline sessionctx/variable/sysvar.go:1144]: Sorry, for consistency can you move the error handling to a `Validation` func? That way the `SetGlobal` func can become simpler and just change the value.

Comment (ichn-hu) [reply sessionctx/variable/sysvar.go:1144]: that makes sense, let me change it

**Review by SunRunAway — APPROVED** [review]
Test Points:

- Privilege
    - tidb_super_read_only
        - ✅ SUPER and system_variables_admin can toggle this
        - ✅ Non-SUPER or Non-system_variables_admin cannot toggle this
        - ✅ Any privilege (like USAGE) can see values of tidb_super_read_only
    - tidb_restricted_read_only
        - If SEM is on
            - ✅ restricted_variables_admin can see this variable.
            - ✅ restricted_variables_admin+system_variables_admin can toggle this variable.
            - ✅ Other privileges can not see this variable.
            - ✅ Other privileges can not toggle this variable.
        - If SEM is off
            - ✅ SUPER and system_variables_admin can see and toggle this.
            - ✅ Restricted_system_variable_admin cannot toggle this, can see this.
            - ✅ Other privileges can see, but can not toggle this variable.
- Transmissibility
        - ✅ Set tidb_restricted_read_only to ON -> tidb_super_read_only to ON
        - ✅ Set tidb_restricted_read_only to OFF -> tidb_super_read_only is unchanged
        - ✅ If tidb_restricted_read_only is ON, tidb_super_read_only cannot be set to OFF
- run DDL & DML & LOCK
        - If tidb_restricted_read_only is ON or tidb_super_read_only is ON
            - ✅RESTRICTED_REPLICA_WRITER_ADMIN can run DDL & DML & LOCK
            - ✅ restricted_variables_admin can not run DDL & DML & LOCK.
            - ✅ SUPER can not run DDL & DML & LOCK, can run DQL
            - ✅ Any others can not run DDL & DML & LOCK

**Comment by SunRunAway** [comment]
@morgo ptal

File: sessionctx/variable/sysvar.go [hunk 3]
```diff
@@ -1119,7 +1119,29 @@ var defaultSysVars = []*SysVar{
...
+			result, err := vars.GlobalVarsAccessor.GetGlobalSysVar(TiDBRestrictedReadOnly)
+			if err != nil {
+				return normalizedValue, err
+			}
+			if TiDBOptOn(result) {
+				return normalizedValue, fmt.Errorf("can't turn off %s when %s is on", TiDBSuperReadOnly, TiDBRestrictedReadOnly)
+			}
+		}
+		return normalizedValue, nil
+	}},
```
Comment (morgo) [inline sessionctx/variable/sysvar.go:1144]: There should be a `SetGlobal` func to set the value without relying on the sysvar_cache. This will ensure that it applies locally immediately and does not require an etcd notification.

```suggestion
	{Scope: ScopeGlobal, Name: TiDBSuperReadOnly, Value: BoolToOnOff(DefTiDBSuperReadOnly), Type: TypeBool, Validation: func(vars *SessionVars, normalizedValue string, _ string, _ ScopeFlag) (string, error) {
		on := TiDBOptOn(normalizedValue)
		if !on {
			result, err := vars.GlobalVarsAccessor.GetGlobalSysVar(TiDBRestrictedReadOnly)
			if err != nil {
				return normalizedValue, err
			}
			if TiDBOptOn(result) {
				return normalizedValue, fmt.Errorf("can't turn off %s when %s is on", TiDBSuperReadOnly, TiDBRestrictedReadOnly)
			}
		}
		return normalizedValue, nil
	}, SetGlobal: func(s *SessionVars, val string) error {
		VarTiDBSuperReadOnly.Store(variable.TiDBOptOn(val))
		return nil
	}
},
```

Otherwise LGTM

Comment (ichn-hu) [reply sessionctx/variable/sysvar.go]: thanks for the tip!

**Review by morgo — APPROVED** [review]
