### PR TITLE
import: fix memory leak

### LINKED ISSUE #39331: Lightning: Memory Leak on Large Source Files
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Prepare a large CSV file as the data source
2. Create the Lightning task with strict-mode set to false
3. Observe the memory usage of Lightning

### 2. What did you expect to see? (Required)
The memory usage should be stable, even if the source data is large, because Lightning is streaming-processing the data.  

### 3. What did you see instead (Required)
The memory of Lightning process is increasing continuously.  I suspect there might be memory leaks.

### 4. What is your TiDB version? (Required)
latest version

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #39331 

Problem Summary:

### What is changed and how it works?
When `kvMemBuf` reuses the byte buffer in the available byte buffer pool, iterate on all the byte buffer's capacity.  If it can find at least one byte buffer with a large capacity, it will choose to reuse it, rather than create a new byte buffer.  

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
    compile the modified version, and check whether memory leak has been fixed.  Here are the heap profiles of the Lightning process after the modification: 
976b2e0d-e741-45fb-b147-b582870993c5
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dsdashun** [comment]
integration br test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/11150/pipeline

**Review by lance6716 — COMMENTED** [review]
seems we can add a simple unit test that after some `AllocateBuf`/`Set` and `Recycle`, the `mb.availableBufs` does not grow badly

File: br/pkg/lightning/backend/kv/session.go [hunk 1]
```diff
@@ -99,8 +99,20 @@ func (mb *kvMemBuf) Recycle(buf *bytesBuf) {
 func (mb *kvMemBuf) AllocateBuf(size int) {
 	mb.Lock()
 	size = mathutil.Max(units.MiB, int(utils.NextPowerOfTwo(int64(size)))*2)
-	if len(mb.availableBufs) > 0 && mb.availableBufs[0].cap >= size {
-		mb.buf = mb.availableBufs[0]
+	var (
+		existingBuf    *bytesBuf
+		existingBufIdx int
+	)
+	for i, buf := range mb.availableBufs {
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/kv/session.go:106]: should we limit max length of `mb.availableBufs`? in case `encodeLoop` is slow down for we might loop through all availableBufs on every `AllocateBuf` in worst case

Comment (dsdashun) [reply br/pkg/lightning/backend/kv/session.go:106]: Maybe no need to limit the max length.  There are two reasons: 
1. the allocation size is by the power of 2, starting from 1MB.  So the possible byte buffer capacities are 1MB, 2MB, 4MB, ...  Since the memory limit is typically around 256GB, and the reuse mechanism has fixed now, in the extreme case without any reuse, the available byte buffer pool's size is around 18 (1MB, 2MB, 4MB, .... 256GB), otherwise a reuse will happen .  
2. the typical allocation size will fall into only some byte buffer sizes.  Since the reuse mechanism has fixed now, the reuse will happen frequently.  So the overall `availableBufs` size is controllable.  

But it is OK to add a defending mechanism for the performance degration here.

**Comment by dsdashun** [comment]
> seems we can add a simple unit test that after some `AllocateBuf`/`Set` and `Recycle`, the `mb.availableBufs` does not grow badly

Fixed in a71021c4d153035f252e6464c37beaccd682f4f9

File: br/pkg/lightning/backend/kv/session.go (hunk 1 above)
Comment (dsdashun) [reply br/pkg/lightning/backend/kv/session.go:114]: Fixed in a71021c4d153035f252e6464c37beaccd682f4f9

**Comment by dsdashun** [comment]
integration br test passed: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_br_test/detail/tidb_ghpr_integration_br_test/11182/pipeline

**Review by D3Hunter — APPROVED** [review]

File: br/pkg/lightning/backend/kv/session_internal_test.go [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+		}
+		require.Equal(t, len(tc.FinalAvailableByteBufCaps), len(testKVMemBuf.availableBufs))
+		for i, bb := range testKVMemBuf.availableBufs {
+			require.Equal(t, tc.FinalAvailableByteBufCaps[i], bb.cap)
+		}
+	}
+}
+
+func TestKVMemBufBatchAllocAndRecycle(t *testing.T) {
+	type testCase struct {
```
Comment (lance6716) [inline br/pkg/lightning/backend/kv/session_internal_test.go:93]: this type is not used?

**Review by lance6716 — APPROVED** [review]
