### PR TITLE
ddl: Fix partition value type check

### LINKED ISSUE #20979: partition columns value should be same type
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table t
(
    b int(10)
) partition by range columns (b) (
    partition p0 values less than (0x10),
    partition p3 values less than (0x20)
);

create table t
(
    b int(10)
) partition by range columns (b) (
    partition p0 values less than ('g'),
    partition p3 values less than ('k')
);

create table t
(
    b char(10)
) partition by range columns (b) (
    partition p0 values less than (30),
    partition p3 values less than (60)
);
```

### 2. What did you expect to see? (Required)

`[HY000][1654] Partition column values of incorrect type`

### 3. What did you see instead (Required)

create table success

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #20979

Problem Summary:

Create partition table and the partition column values type not same as columns type can be succeeded.

### What is changed and how it works?

What's Changed:

Add more type check for partition range or list values.

### Related changes

- No

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Breaking some error message report.

### Release note 

- ddl: Fix partition table's partition column values type check

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @tiancaiamao @crazycs520

**Review by crazycs520 — COMMENTED** [review]
LGTM

**Comment by tiancaiamao** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

File: ddl/db_partition_test.go [hunk 1]
```diff
@@ -2866,3 +2866,36 @@ func (s *testIntegrationSuite7) TestCommitWhenSchemaChange(c *C) {
...
+	)`)
+	c.Assert(err, NotNil)
+	c.Assert(ddl.ErrWrongTypeColumnValue.Equal(err), IsTrue)
+
+	_, err = tk.Exec(`create table t(
+	b char(10)
+	) partition by range columns (b) (
+		partition p0 values less than (30),
+		partition p3 values less than (60)
+	)`)
```
Comment (xiongjiwei) [inline ddl/db_partition_test.go:2898]:
```sql
create table t
(
    col datetime
)
partition by range columns (col) (
        PARTITION p0 VALUES less than ('g'),
        PARTITION p1 VALUES less than ('m')
);
```

can you please test this case? this SQL statement will fail in MySQL

Comment (blacktear23) [reply ddl/db_partition_test.go:2898]: This will not fail in TiDB with this PR. I think we need more complex check on datetime field.

**Comment by blacktear23** [comment]
@bb7133 please remove merge tag. This PR not handle datetime type check.

**Comment by blacktear23** [comment]
@xiongjiwei I add datetime type value check logic, PTAL

**Comment by xiongjiwei** [comment]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Review by bb7133 — APPROVED** [review]

**Comment by xiongjiwei** [comment]
@blacktear23 hi, I am not sure whether we have this check in `alter table ... add partition`  statement. can you please confirm that?

File: ddl/db_partition_test.go [hunk 2]
```diff
@@ -825,7 +825,7 @@ func (s *testIntegrationSuite5) TestAlterTableAddPartitionByListColumns(c *C) {
 			ddl.ErrMultipleDefConstInListPart,
 		},
 		{"alter table t add partition (partition p6 values in (('a','a')))",
-			ddl.ErrNotAllowedTypeInPartition,
+			ddl.ErrWrongTypeColumnValue,
```
Comment (xiongjiwei) [inline ddl/db_partition_test.go:828]: @bb7133 @blacktear23  sorry, this test case show that we have do this check in `alter` statement. 😥

**Comment by xiongjiwei** [comment]
I think this PR can also close https://github.com/pingcap/tidb/issues/20277

File: ddl/db_partition_test.go (hunk 2 above)
Comment (blacktear23) [reply ddl/db_partition_test.go:828]: I have test this in mysql, this fix result is same as mysql.

**Comment by blacktear23** [comment]
> @blacktear23 hi, I am not sure whether we have this check in `alter table ... add partition` statement. can you please confirm that?

I will add more test then.

File: ddl/db_partition_test.go (hunk 2 above)
Comment (blacktear23) [reply ddl/db_partition_test.go:828]: below is mysql result:

```sql
mysql> create table t (id int, name varchar(10)) partition by list columns (id,name) (
    ->     partition p0 values in ((1,'a'),(2,'b')),
    ->     partition p1 values in ((3,'a'),(4,'b')),
    ->     partition p3 values in ((5,null))
    -> );
Query OK, 0 rows affected (0.03 sec)

mysql> alter table t add partition (partition p6 values in (('a','a')));
ERROR 1654 (HY000): Partition column values of incorrect type
```

**Comment by blacktear23** [comment]
@xiongjiwei `alter table add partition` and `create table` use same value type check function, so this PR can also cover `alter table add partition` statements.

File: ddl/db_partition_test.go (hunk 2 above)
Comment (blacktear23) [reply ddl/db_partition_test.go:828]: By the way seems there may have double check for type on `alter table add partition` logic. Shall we need to find it out and remove the logic? @bb7133

Comment (xiongjiwei) [reply ddl/db_partition_test.go:828]: > By the way seems there may have double check for partition values type 

there are many double-check, even triple check  😂, a lot of work should be done.

**Review by wjhuang2016 — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
