### PR TITLE
planner: avoid have two `ExtraPhysTblID` row in same schema

### LINKED ISSUE #44615: Query result if not correct when using partition table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tpcc 100 warehouse and hash(10) patition using warehouse id
tpcc check query is not 0
maybe introduced by https://github.com/pingcap/tidb/pull/44360
the follow query expect result is 0 but got 12, but I found the query result is indeed 12 from current data. Maybe the data is not correct when do dml.
```
SELECT
    c_id,
    c_d_id,
    c1,
    c_ytd_payment,
    sm
FROM
    (
        SELECT
            c.c_id,
            c.c_d_id,
            c.c_balance c1,
            c_ytd_payment,
            (
                SELECT
                    sum(ol_amount)
                FROM
                    orders STRAIGHT_JOIN order_line
                WHERE
                    OL_W_ID = O_W_ID
                    AND OL_D_ID = O_D_ID
                    AND OL_O_ID = O_ID
                    AND OL_DELIVERY_D IS NOT NULL
                    AND O_W_ID = 2
                    AND O_D_ID = c.C_D_ID
                    AND O_C_ID = c.C_ID
            ) sm
        FROM
            customer c
        WHERE
            c.c_w_id = 2
    ) t1
WHERE
    c1 + c_ytd_payment <> sm;
```
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #44615

Problem Summary: When a schema has two `ExtraPhysTblID` rows, the first one will return 0 in TiKV side which caused `SelectLock` failed. And in some reasons, the `SelectLock` will ignore this problem, see https://github.com/pingcap/tidb/blob/bd278a05dae96861c94cc9dc69203c26b77fe15b/executor/executor.go#L1281-L1288
So we should avoid it in planner part.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: planner/core/physical_plans.go [hunk 1]
```diff
@@ -991,6 +1010,24 @@ func (ts *PhysicalTableScan) SetIsChildOfIndexLookUp(isIsChildOfIndexLookUp bool
 	ts.isChildOfIndexLookUp = isIsChildOfIndexLookUp
 }
 
+// AddExtraPhysTblIDColumn for partition table.
+// For keepOrder with partition table,
+// we need use partitionHandle to distinct two handles,
+// the `_tidb_rowid` in differenct partition will same in some scenario.
+func (ts *PhysicalTableScan) AddExtraPhysTblIDColumn() bool {
```
Comment (mjonss) [inline planner/core/physical_plans.go:1017]: Would it be possible to add a new struct with the common fields from PhysicalTableScan and PhysicalIndexScan and then use that for composing the two different structs?
Then this code would not need to be duplicated.

Comment (Defined2014) [reply planner/core/physical_plans.go]: Tried to reorganize code to avoid duplications

File: tests/realtikvtest/txntest/txn_test.go [hunk 2]
```diff
@@ -251,3 +253,34 @@ func TestAssertionWhenPessimisticLockLost(t *testing.T) {
...
+	var finish atomic.Bool
+	go func() {
+		finish.Store(false)
+		tk2.MustExec("use test")
+		tk2.MustExec("begin")
+		// block here, until tk1 finish
+		tk2.MustExec("select * from t use index(idx) where a = 1 and b = 1 for update")
+		finish.Store(true)
+	}()
+	time.Sleep(10 * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (Defined2014) [reply tests/realtikvtest/txntest/txn_test.go:280]: updated, the sleep here is to make sure select stmt executed

**Comment by Defined2014** [comment]
Updated, PTAL @mjonss

File: tests/realtikvtest/txntest/txn_test.go [hunk 3]
```diff
@@ -251,3 +252,41 @@ func TestAssertionWhenPessimisticLockLost(t *testing.T) {
...
+	tk2 := testkit.NewTestKit(t, store)
+
+	tk1.MustExec("use test")
+	tk1.MustExec("create table t(a int, b int, c int, key idx(a, b, c)) PARTITION BY HASH (c) PARTITIONS 10")
+	tk1.MustExec("insert into t values (1, 1, 1)")
+	tk1.MustExec("analyze table t")
+	tk1.MustExec("begin")
+	tk1.HasPlan("select * from t use index(idx) where a = 1 and b = 1 for update", "IndexLookUp_9")
+	tk1.MustExec("select * from t use index(idx) where a = 1 and b = 1 for update")
+	ch := make(chan bool, 1)
```
Comment (mjonss) [inline tests/realtikvtest/txntest/txn_test.go:268]: If you make it an unbuffered channel instead, you can use it as a semaphore/sync object, and skip the need for the sleep.
```suggestion
	ch := make(chan bool)
```

File: tests/realtikvtest/txntest/txn_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (mjonss) [reply tests/realtikvtest/txntest/txn_test.go:280]: If you use an unbuffered channel instead, you can just do `<-ch` here and it will wait until the SelectLock is done.

**Review by mjonss — APPROVED** [review]
Just some minor suggestion for syncing in the test.

File: tests/realtikvtest/txntest/txn_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Defined2014) [reply tests/realtikvtest/txntest/txn_test.go:280]: `SelectLock` will block until tk1 commit. I'm adding a sleep in the test case just to make sure the `SelectLock` is running and being blocked.

File: tests/realtikvtest/txntest/txn_test.go (hunk 3 above)
Comment (mjonss) [reply tests/realtikvtest/txntest/txn_test.go:268]: Sorry for misunderstanding, you want the sleep to make sure the SelectLock starts to execute and blocks internally.

**Review by winoros — APPROVED** [review]
