### PR TITLE
planner: enforce the required property when hint cannot satisfy it

### LINKED ISSUE #15571: INL_JOIN does not work
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

<!-- If possible, provide a recipe for reproducing the error. -->
``` sql
create table t(a int primary key);
desc select /*+inl_join(t2)*/ t1.a, t2.a from t t1 left join t t2 on t2.a=t1.a
 right join t t3 on t3.a=t2.a;
```

### 2. What did you expect to see?
INL_JOIN can work

### 3. What did you see instead?
``` sql
tidb> create table t(a int primary key);
Query OK, 0 rows affected (0.02 sec)

tidb> desc select /*+inl_join(t2)*/ t1.a, t2.a from t t1 left join t t2 on t2.a=t1.a right join t t3 on t3.a=t2.a;
+-----------------------------------+----------+-----------+---------------------------------------------------------+
| id                                | estRows  | task      | operator info                                           |
+-----------------------------------+----------+-----------+---------------------------------------------------------+
| Projection_7                      | 15625.00 | root      | test.t.a, test.t.a                                      |
| └─MergeJoin_8                     | 15625.00 | root      | right outer join, left key:test.t.a, right key:test.t.a |
|   ├─MergeJoin_11(Build)           | 12500.00 | root      | inner join, left key:test.t.a, right key:test.t.a       |
|   │ ├─TableReader_24(Build)       | 10000.00 | root      | data:TableFullScan_23                                   |
|   │ │ └─TableFullScan_23          | 10000.00 | cop[tikv] | table:t2, keep order:true, stats:pseudo                 |
|   │ └─TableReader_22(Probe)       | 10000.00 | root      | data:TableFullScan_21                                   |
|   │   └─TableFullScan_21          | 10000.00 | cop[tikv] | table:t1, keep order:true, stats:pseudo                 |
|   └─TableReader_26(Probe)         | 10000.00 | root      | data:TableFullScan_25                                   |
|     └─TableFullScan_25            | 10000.00 | cop[tikv] | table:t3, keep order:true, stats:pseudo                 |
+-----------------------------------+----------+-----------+---------------------------------------------------------+
9 rows in set, 1 warning (0.00 sec)

tidb> show warnings;
+---------+------+----------------------------------------------------------------------------+
| Level   | Code | Message                                                                    |
+---------+------+----------------------------------------------------------------------------+
| Warning | 1815 | Optimizer Hint /*+ INL_JOIN(t2) */ or /*+ TIDB_INLJ(t2) */ is inapplicable |
+---------+------+----------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
``` sql
tidb> select tidb_Version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_Version()                                                                                                                                                                                                                                                                                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta-492-gfd0235d03
Git Commit Hash: fd0235d030b492330e692e14398bd8876cc10434
Git Branch: master
UTC Build Time: 2020-03-23 05:50:50
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### LINKED ISSUE #16017: INL_MERGE_JOIN hint results in an error "Internal : Can't find a proper physical plan for this query"
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
SELECT /*+ INL_MERGE_JOIN(t1) */ * FROM t0 NATURAL JOIN t1 WHERE t0.c0 IS NULL;
```
Unexpectedly, the hint results in an internal error `ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query`.

This bug might be related to https://github.com/pingcap/tidb/issues/15961. However, unlike the referenced issue, this bug is reliably triggered on the latest TiDB version. /cc @francis0407

Environment:
```
mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-167-gaa7ef9c46
Git Commit Hash: aa7ef9c46435bb20d42fa0badcf09fc16f9609a9
Git Branch: master
UTC Build Time: 2020-04-02 09:15:47
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by francis0407**
### What problem does this PR solve?

Issue Number: close #15571, close #16017 

Problem Summary: 
This PR fixes some cases that the optimizer hint is not applied even if it is applicable.
Here are some examples:
```
mysql> desc t;
+-------+---------+------+------+---------+-------+
| Field | Type    | Null | Key  | Default | Extra |
+-------+---------+------+------+---------+-------+
| a     | int(11) | NO   | PRI  | NULL    |       |
| b     | int(11) | YES  | MUL  | NULL    |       |
+-------+---------+------+------+---------+-------+
2 rows in set (0.00 sec)
```

```
mysql> desc select /*+ INL_JOIN(t2) */ * from t t1, t t2 where t1.a = t2.b order by t2.a ;
+------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------+
| id                           | estRows  | task      | access object | operator info                                                              |
+------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------+
| IndexJoin_30                 | 12487.50 | root      |               | inner join, inner:TableReader_29, outer key:hints.t.b, inner key:hints.t.a |
| ├─TableReader_38(Build)      | 9990.00  | root      |               | data:Selection_37                                                          |
| │ └─Selection_37             | 9990.00  | cop[tikv] |               | not(isnull(hints.t.b))                                                     |
| │   └─TableFullScan_36       | 10000.00 | cop[tikv] | table:t2      | keep order:true, stats:pseudo                                              |
| └─TableReader_29(Probe)      | 1.00     | root      |               | data:TableRangeScan_28                                                     |
|   └─TableRangeScan_28        | 1.00     | cop[tikv] | table:t1      | range: decided by [hints.t.b], keep order:false, stats:pseudo              |
+------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------+
6 rows in set, 1 warning (0.00 sec)

mysql> desc select /*+ INL_HASH_JOIN(t2) */ * from t t1, t t2 where t1.a = t2.b order by t2.a ;
+------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------+
| id                           | estRows  | task      | access object | operator info                                                              |
+------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------+
| IndexJoin_30                 | 12487.50 | root      |               | inner join, inner:TableReader_29, outer key:hints.t.b, inner key:hints.t.a |
| ├─TableReader_38(Build)      | 9990.00  | root      |               | data:Selection_37                                                          |
| │ └─Selection_37             | 9990.00  | cop[tikv] |               | not(isnull(hints.t.b))                                                     |
| │   └─TableFullScan_36       | 10000.00 | cop[tikv] | table:t2      | keep order:true, stats:pseudo                                              |
| └─TableReader_29(Probe)      | 1.00     | root      |               | data:TableRangeScan_28                                                     |
|   └─TableRangeScan_28        | 1.00     | cop[tikv] | table:t1      | range: decided by [hints.t.b], keep order:false, stats:pseudo              |
+------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------+
6 rows in set, 1 warning (0.00 sec)
```

The two queries above are the same but with different join hint. But the hints don't work. 
The root cause is that optimizer has two branches for the query above: `PhysicalSort -> IndexJoin(t2 is inner)` and `NominalSort -> IndexJoin(t1 is inner)`. The second branch cannot make the hint work, because **the hint does not match the required property** `order by t2.a`. 
In the end, the second branch has a lower cost, so the optimizer choose it.

More examples:
```
mysql> desc select /*+inl_merge_join(t2)*/ t1.a, t2.a from t t1, t t2 ,t t3 where t1.a = t2.a and t3.a=t2.a;
+-----------------------------------+----------+-----------+---------------+-----------------------------------------------------+
| id                                | estRows  | task      | access object | operator info                                       |
+-----------------------------------+----------+-----------+---------------+-----------------------------------------------------+
| Projection_9                      | 15625.00 | root      |               | hints.t.a, hints.t.a                                |
| └─MergeJoin_10                    | 15625.00 | root      |               | inner join, left key:hints.t.a, right key:hints.t.a |
|   ├─MergeJoin_24(Build)           | 12500.00 | root      |               | inner join, left key:hints.t.a, right key:hints.t.a |
|   │ ├─TableReader_37(Build)       | 10000.00 | root      |               | data:TableFullScan_36                               |
|   │ │ └─TableFullScan_36          | 10000.00 | cop[tikv] | table:t2      | keep order:true, stats:pseudo                       |
|   │ └─TableReader_35(Probe)       | 10000.00 | root      |               | data:TableFullScan_34                               |
|   │   └─TableFullScan_34          | 10000.00 | cop[tikv] | table:t1      | keep order:true, stats:pseudo                       |
|   └─TableReader_23(Probe)         | 10000.00 | root      |               | data:TableFullScan_22                               |
|     └─TableFullScan_22            | 10000.00 | cop[tikv] | table:t3      | keep order:true, stats:pseudo                       |
+-----------------------------------+----------+-----------+---------------+-----------------------------------------------------+
9 rows in set, 1 warning (0.00 sec)

mysql> desc select * from t t1, (select /*+ HASH_AGG() */ b, max(a) from t t2 group by b) t2 where t1.b = t2.b order by t1.b;
+----------------------------------+---------+-----------+----------------------+-----------------------------------------------------------------------------------------+
| id                               | estRows | task      | access object        | operator info                                                                           |
+----------------------------------+---------+-----------+----------------------+-----------------------------------------------------------------------------------------+
| Projection_46                    | 9990.00 | root      |                      | hints.t.a, hints.t.b, hints.t.b, Column#5                                               |
| └─MergeJoin_47                   | 9990.00 | root      |                      | inner join, left key:hints.t.b, right key:hints.t.b                                     |
|   ├─StreamAgg_32(Build)          | 7992.00 | root      |                      | group by:hints.t.b, funcs:max(Column#6)->Column#5, funcs:firstrow(hints.t.b)->hints.t.b |
|   │ └─IndexReader_33             | 7992.00 | root      |                      | index:StreamAgg_29                                                                      |
|   │   └─StreamAgg_29             | 7992.00 | cop[tikv] |                      | group by:hints.t.b, funcs:max(hints.t.a)->Column#6                                      |
|   │     └─IndexFullScan_31       | 9990.00 | cop[tikv] | table:t2, index:b(b) | keep order:true, stats:pseudo                                                           |
|   └─IndexReader_28(Probe)        | 9990.00 | root      |                      | index:IndexFullScan_27                                                                  |
|     └─IndexFullScan_27           | 9990.00 | cop[tikv] | table:t1, index:b(b) | keep order:true, stats:pseudo                                                           |
+----------------------------------+---------+-----------+----------------------+-----------------------------------------------------------------------------------------+
8 rows in set (0.00 sec)
```
### What is changed and how it works?

What's Changed:

change the method `exhaustPhysicalPlans(prop *property.PhysicalProperty) []PhysicalPlan` to `exhaustPhysicalPlans(prop *property.PhysicalProperty) ([]PhysicalPlan, bool)`.
The second returned values means: if there is a hint that cannot match the property. If so, we should enforce the property and try the hint again.

How it Works:

To solve this problem, we should make hint work whatever the required property is. We can
enforce the property when the hint cannot match it. 

### Related changes

- Need to cherry-pick to the release branch 4.0(maybe 3.1 is also required)

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
Fix some cases optimizer hint is not applicable

### CODE REVIEW

File: planner/core/exhaust_physical_plans.go [hunk 1]
```diff
@@ -1281,27 +1303,23 @@ func (p *LogicalJoin) tryToGetIndexJoin(prop *property.PhysicalProperty) (indexJ
...
+	// but we cannot generate IndexHashJoin because of the required property, we set `XXXHashJoinMatchProp` = false.
+	// And we will enforce a sort above the join and try to get the IndexHashJoin again.
+	// Because IndexJoin and IndexHashJoin can satisfy the same property, so we use the variable `xxxxHashJoinMatchProp` for them.
+	// IndexMergeJoin has stricter condition, so it uses a separate variable `xxxxMergeJoinMatchProp`.
+	//
+	// In fact, we can simply check whether `prop.IsEmpty` when a hint is inapplicable, then enforce that property and try to apply
+	// the hint again. But this may introduce some useless search. For example, if the join's inner child is not DataSource, it cannot
+	// use IndexJoin whatever the required property is empty or not.
+	leftOuterHashJoinMatchProp, rightOuterHashJoinMatchProp := true, true
+	leftOuterMergeJoinMatchProp, rightOuterMergeJoinMatchProp := true, true
```
Comment (francis0407) [inline planner/core/exhaust_physical_plans.go]: This might be too complicated. We can simplfy it to `if (needForce && !canForce &&  !prop.IsEmpty) then enforce the property`. But we have a trade off here:
1. If we use the simple method, we may enforce the property for the hint which is inapplicable even if there is not property. For example, if the inner child is not DataSource, the hint cannot work anyway.
2. If we use the complicated method, it looks too ugly and is difficult to understand..

Comment (francis0407) [reply planner/core/exhaust_physical_plans.go]: I'm trying to use the simple method.

File: planner/core/find_best_task.go [hunk 2]
```diff
@@ -169,7 +169,15 @@ func (p *baseLogicalPlan) findBestTask(prop *property.PhysicalProperty) (bestTas
...
 		prop.Items = []property.Item{}
 	}
-	physicalPlans := p.self.exhaustPhysicalPlans(prop)
+	physicalPlans, hasUnmatchedHint := p.self.exhaustPhysicalPlans(prop)
+	if hasUnmatchedHint {
+		// If there is a hint in the plan and the hint cannot match the property,
+		// we enforce this property and try to generate the PhysicalPlan again to
+		// make sure the hint can work.
+		prop.Items = []property.Item{}
+		physicalPlans, _ = p.self.exhaustPhysicalPlans(prop)
```
Comment (SunRunAway) [inline planner/core/find_best_task.go]: If `prop.Enforced` is `true` at line 161, this line may be hit with enforced once through `findBestTask` at line 164. Which is a redundant calculation with line 172

File: planner/core/plan.go [hunk 3]
```diff
@@ -177,7 +177,11 @@ type LogicalPlan interface {
 	PreparePossibleProperties(schema *expression.Schema, childrenProperties ...[][]*expression.Column) [][]*expression.Column
 
 	// exhaustPhysicalPlans generates all possible plans that can match the required property.
-	exhaustPhysicalPlans(*property.PhysicalProperty) []PhysicalPlan
+	// It will return:
+	// 1. All possible plans that can match the required property.
+	// 2. Whether there is a hint that cannot satisfy the required property. If so
+	//    we should enforce the property in advance.
+	exhaustPhysicalPlans(*property.PhysicalProperty) (physicalPlans []PhysicalPlan, hasUnmatchedHint bool)
```
Comment (SunRunAway) [inline planner/core/plan.go]: Better to use positive voice.
```suggestion
	exhaustPhysicalPlans(*property.PhysicalProperty) (physicalPlans []PhysicalPlan, hintFitsProp bool)
```

Comment (francis0407) [reply planner/core/plan.go]: addressed

File: planner/core/find_best_task.go (hunk 2 above)
Comment (francis0407) [reply planner/core/find_best_task.go]: I refactor the implementation of `baseLogicalPlan.findBestTask`. PTAL

File: planner/core/plan.go [hunk 4]
```diff
@@ -177,7 +177,10 @@ type LogicalPlan interface {
 	PreparePossibleProperties(schema *expression.Schema, childrenProperties ...[][]*expression.Column) [][]*expression.Column
 
 	// exhaustPhysicalPlans generates all possible plans that can match the required property.
-	exhaustPhysicalPlans(*property.PhysicalProperty) []PhysicalPlan
+	// It will return:
+	// 1. All possible plans that can match the required property.
+	// 2. Whether the SQL hint can satisfy the required property. Return true if there is no hint.
+	exhaustPhysicalPlans(*property.PhysicalProperty) (physicalPlans []PhysicalPlan, hintFitsProp bool)
```
Comment (zz-jason) [inline planner/core/plan.go]: Does `hintFitsProp` is true means all the candidate physical plan in the return result satisfy the hint?

Comment (francis0407) [reply planner/core/plan.go]: Yes

File: planner/core/find_best_task.go [hunk 5]
```diff
@@ -132,46 +132,9 @@ func (p *LogicalShowDDLJobs) findBestTask(prop *property.PhysicalProperty) (task
...
-	}
-
-	if prop.TaskTp != property.RootTaskType {
-		// Currently all plan cannot totally push down.
-		p.storeTask(prop, invalidTask)
-		return invalidTask, nil
-	}
-
-	bestTask = invalidTask
+func (p *baseLogicalPlan) getBestTask(physicalPlans []PhysicalPlan, prop *property.PhysicalProperty) (task, error) {
```
Comment (SunRunAway) [inline planner/core/find_best_task.go]:
```suggestion
func (p *baseLogicalPlan) enumeratePhysicalPlans(physicalPlans []PhysicalPlan, prop *property.PhysicalProperty) (task, error) {
```

File: planner/core/find_best_task.go [hunk 6]
```diff
@@ -205,11 +168,76 @@ func (p *baseLogicalPlan) findBestTask(prop *property.PhysicalProperty) (bestTas
...
-		if curTask.cost() < bestTask.cost() {
+		if curTask.cost() < bestTask.cost() || (bestTask.invalid() && !curTask.invalid()) {
 			bestTask = curTask
 		}
 	}
+	return bestTask, nil
+}
+
+// findBestTask implements LogicalPlan interface.
+func (p *baseLogicalPlan) findBestTask(prop *property.PhysicalProperty) (bestTask task, err error) {
```
Comment (SunRunAway) [inline planner/core/find_best_task.go]: A unit test for this method is appreciated.

File: planner/core/find_best_task.go [hunk 7]
```diff
@@ -205,11 +168,76 @@ func (p *baseLogicalPlan) findBestTask(prop *property.PhysicalProperty) (bestTas
...
+		p.storeTask(prop, invalidTask)
+		return invalidTask, nil
+	}
+
+	bestTask = invalidTask
+
+	// prop should be read only because its cached hashcode might be not consistent
+	// when it is changed. So we clone a new one for the temporary changes.
+	newProp := prop.Clone()
+	newProp.Enforced = prop.Enforced
```
[the remark this answers is not in the document]
Comment (francis0407) [reply planner/core/find_best_task.go]: The new implementation don't need this now.

File: planner/core/find_best_task.go (hunk 5 above)
Comment (francis0407) [reply planner/core/find_best_task.go]: addressed

File: planner/core/find_best_task.go (hunk 6 above)
Comment (francis0407) [reply planner/core/find_best_task.go]: I'm working on this, it need some time...

**Comment by francis0407** [comment]
I found some bugs when adding unit tests. I'm still working on this.

File: planner/core/exhaust_physical_plans.go [hunk 8]
```diff
@@ -1762,37 +1753,38 @@ func (la *LogicalAggregation) exhaustPhysicalPlans(prop *property.PhysicalProper
...
 	streamAggs := la.getStreamAggs(prop)
 	if streamAggs != nil && preferStream {
-		return streamAggs
+		return streamAggs, true
 	}
 
-	if streamAggs == nil && preferStream {
+	aggs := make([]PhysicalPlan, 0, len(hashAggs)+len(streamAggs))
+	aggs = append(aggs, hashAggs...)
+	aggs = append(aggs, streamAggs...)
```
Comment (lzmhhh123) [inline planner/core/exhaust_physical_plans.go:1766]:
```suggestion
	aggs := append(hashAggs, streamAggs...)
```
