### PR TITLE
distsql: control the sending rate of copIteratorTaskSender if keepOrder is true

### LINKED ISSUE #11468: distsql: All data may be stored in memory(potential OOM) if kvReq.KeepOrder is true with a slow client
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Run `select * from sbtest1 order by pk` with a client that does not receive data from its connection.
After a while, tidb-server holds all data from sbtest1 into its memory.

When kvReq.KeepOrder is true, each copTask has its own channel so that each of them will be filled by copIteratorWorker. 

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

newest master (e09745bd02cd20b497861f0e587f01541ccac8b2)

### PR DESCRIPTION
**Pull request by SunRunAway**
### What problem does this PR solve? 

Closes #11468 

### What is changed and how it works?

- Introduce `sendRate` to control the number of inflight tasks within concurrency * 2.

If `keepOrder` is true, we must control the sending rate to prevent all tasks being done (aka. all of the responses are buffered) by `copIteratorWorker`. We keep the number of inflight tasks within the number of `concurrency * 2`. It sends one more task if a task has been finished in `copIterator.Next`.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 - hard to add unit test :(

Code changes

 - None

Side effects

 - None

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by tiancaiamao** [comment]
Use a bare channel makes the code difficult to read, would you like to define a simple `rateLimit` type:


```
type rateLimit struct {
     tokens chan struct{}
}

func newRateLimit(n int) *rateLimit {
     return &rateLimit{
	     tokens: make(chan struct{}, n),
     }
}

func (r *rateLimit) getToken() {
	r.tokens <- chan struct{}{}
}

func (r *rateLimit) putToken() {
	<-r.tokens
}
```


in the sender:

```
for _, t := range sender.tasks {
	rateLimit.getToken()
	exit := sender.sendToTaskCh(t)
	...
}
```

and in the worker, when the task is done:
```
rateLimit.releaseToken()
```

**Comment by SunRunAway** [comment]
@tiancaiamao 
Since we need to a `rateLimit` supporting `putToken` before `getToken`, it has to do an initialization step for the channel buffer.

So the `rateLimit` must be implemented like below.
```go
type rateLimit struct {
	token chan struct{}
}

func newRateLimit(initToken, bufLen int) *rateLimit {
	if initToken > bufLen {
		initToken = bufLen
	}
	rl := &rateLimit{
		token : make(chan struct{}, bufLen),
	}
	for i := 0; i < initToken; i++ {
		rl.putToken()
	}
	return rl
}

func (r *rateLimit) getToken(done <-chan struct{}) (exit bool) {
	select {
	case <-done:
		return true
	case <-r.token:
		return false
	}
}

func (r *rateLimit) putToken() {
	r.token<-struct{}{}
}
```

Do you have any better idea?

**Comment by SunRunAway** [comment]
@tiancaiamao @zz-jason @XuHuaiyu comment addressed, PTAL again, thanks.

**Comment by tiancaiamao** [comment]
LGTM

File: store/tikv/coprocessor.go [hunk 1]
```diff
@@ -832,6 +852,33 @@ func (it *copIterator) Close() error {
...
+	case r.token <- struct{}{}:
+		return false
+	}
+}
+
+func (r *rateLimit) putToken() {
+	select {
+	case <-r.token:
+	default:
+		panic("put a redundant token")
```
Comment (zz-jason) [inline store/tikv/coprocessor.go]: It's better to return an error instead of just panic.

Comment (SunRunAway) [reply store/tikv/coprocessor.go]: It's a `not reachable` path and we should panic here.
An example: https://github.com/golang/go/blob/master/src/bufio/bufio.go#L395-L396

[the remark this answers is not in the document]
Comment (SunRunAway) [reply store/tikv/coprocessor.go]: It's a `not reachable` path and we should panic here.
An example: https://github.com/golang/go/blob/master/src/bufio/bufio.go#L395-L396

File: store/tikv/coprocessor.go [hunk 2]
```diff
@@ -222,9 +224,11 @@ func buildCopTasks(bo *Backoffer, cache *RegionCache, ranges *copRanges, desc bo
...
 			nextI := mathutil.Min(i+rangesPerTask, rLen)
 			tasks = append(tasks, &copTask{
-				region:   region,
-				ranges:   ranges.slice(i, nextI),
-				respChan: make(chan *copResponse, 1),
+				region: region,
+				ranges: ranges.slice(i, nextI),
+				// Channel buffer is 2 for handling region split.
+				// In a common case, two region split tasks will not be blocked.
+				respChan: make(chan *copResponse, 2),
```
[the remark this answers is not in the document]
Comment (SunRunAway) [reply store/tikv/coprocessor.go]: A tiny adjustment.

File: store/tikv/coprocessor.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (XuHuaiyu) [reply store/tikv/coprocessor.go]: Why can't we return an error for an unreachable path?

Comment (zz-jason) [reply store/tikv/coprocessor.go]: It's unreachable only when programmer writes code correctly. But everyone makes mistake. It's better to return an error to make our user notice that we have made a mistake. And that mistake should not impact the long running database service.

File: store/tikv/coprocessor.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (XuHuaiyu) [reply store/tikv/coprocessor.go]: I do not really understand, if a region is split, two new tasks will be constructed.
Where will the block happen?

[the remark this answers is not in the document]
Comment (SunRunAway) [reply store/tikv/coprocessor.go]: Task B will be blocked when Task A is sent into `respChan` but the client hasn't received it.

File: store/tikv/coprocessor.go (hunk 1 above)
Comment (SunRunAway) [reply store/tikv/coprocessor.go]: There are several cons using error but not panic:
1. `rateLimit.putToken` is dirty with an unmeaning error return value.
2. The user of `rateLimit.putToken` has to do a redundant error check.
3. Make a bug hard and late to reveal.

Besides, we should consider using `recover` to handle mistakes made by programmers.

Comment (SunRunAway) [reply store/tikv/coprocessor.go]: You can see many cases with `panic("unreachable")` in go world and every mistake make by programmers may panic and let bugs revealed.

https://github.com/golang/go/search?q=panic%28%22unreachable%22%29&unscoped_q=panic%28%22unreachable%22%29

[the remark this answers is not in the document]
Comment (SunRunAway) [reply store/tikv/coprocessor.go]: Let's discuss in the thread below.

Comment (XuHuaiyu) [reply store/tikv/coprocessor.go]: > 1. rateLimit.putToken is dirty with an unmeaning error return value.
> 2. The user of rateLimit.putToken has to do a redundant error check.
> 3. Make a bug hard and late to reveal.

IMHO,
Golang is a tool that the programmers will use, while TiDB is a tool that the customers will use.
These 3 points are all from the perspective of a programmer, but not from the perspective of a customer.
We need to make the behavior be more acceptable to the customers.

Comment (zz-jason) [reply store/tikv/coprocessor.go]: Agreed with @XuHuaiyu. That's why we changed most of the panic in our codebase to error in the past few PRs.

Comment (SunRunAway) [reply store/tikv/coprocessor.go]: For customers, we should use `defer` to handle this sort of panic.
like https://github.com/pingcap/tidb/blob/master/server/conn.go#L1258-L1276

Comment (zz-jason) [reply store/tikv/coprocessor.go]: `recover()` on that goroutine doesn't work. If you are going to use the `panic-recover` mechanism, you should `recover` in the gogoutine where the function caller belongs to.

Comment (SunRunAway) [reply store/tikv/coprocessor.go]: Otherwise, in this circumstance, if a token cannot be put into the channel, it may lead to unexpected behavior, I do not think the caller could handle the expectation correctly.

Comment (SunRunAway) [reply store/tikv/coprocessor.go]: > `recover()` on that goroutine doesn't work. If you are going to use the `panic-recover` mechanism, you should `recover` in the gogoutine where the function caller belongs to.

Yes, it's recovered by https://github.com/pingcap/tidb/blob/730e140/server/conn.go#L1258-L1276 with `streamResult` and  https://github.com/pingcap/tidb/blob/730e1408cfbf75ed3c45fd98e3a8bdcf5b15d89a/distsql/select_result.go#L90-L102 with `selectResult`.

Comment (zz-jason) [reply store/tikv/coprocessor.go]: okay.
