### PR TITLE
planner: support left outer join into anti semi join | tidb-test=pr/2649

### LINKED ISSUE #64329: "xxxx IS NULL" Condition Cannot Be Pushed Down in TiDB, Forcing Hash Join
## Bug Report

In TiDB, this condition cannot be optimized through constant propagation, nor can it be pushed down to the appropriate location in the execution plan. As a result, it stays below the join, which forces this part of the query to use a hash join exclusively.

### 1. Minimal reproduce step (Required)

```
mysql> explain SELECT
    ->   *
    -> FROM
    ->   `rto` `r2_0`
    ->   LEFT JOIN `rto` `r3_0`
    ->     ON `r3_0`.`id` > `r2_0`.`id`
    ->     AND `r3_0`.`c_id` = `r2_0`.`c_id`
    ->     where `r3_0`.`id` IS NULL;
+--------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                             | estRows  | task      | access object | operator info                                                                                                                                                                                                                          |
+--------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Selection_8                    | 9990.00  | root      |               | isnull(test.rto_delivery_run_sheet_mappings.id)                                                                                                                                                                                        |
| └─HashJoin_23                  | 12487.50 | root      |               | left outer join, equal:[eq(test.rto_delivery_run_sheet_mappings.consignment_id, test.rto_delivery_run_sheet_mappings.consignment_id)], other cond:gt(test.rto_delivery_run_sheet_mappings.id, test.rto_delivery_run_sheet_mappings.id) |
|   ├─TableReader_35(Build)      | 9990.00  | root      |               | data:Selection_34                                                                                                                                                                                                                      |
|   │ └─Selection_34             | 9990.00  | cop[tikv] |               | not(isnull(test.rto_delivery_run_sheet_mappings.consignment_id))                                                                                                                                                                       |
|   │   └─TableFullScan_33       | 10000.00 | cop[tikv] | table:r3_0    | keep order:false, stats:pseudo                                                                                                                                                                                                         |
|   └─TableReader_32(Probe)      | 10000.00 | root      |               | data:TableFullScan_31                                                                                                                                                                                                                  |
|     └─TableFullScan_31         | 10000.00 | cop[tikv] | table:r2_0    | keep order:false, stats:pseudo                                                                                                                                                                                                         |
+--------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
7 rows in set (0.00 sec)
```

Rewrite it as d3_0.id = ''
```
mysql> mysql> explain SELECT   * FROM   `rto_delivery_run_sheet_mappings` `r2_0`   LEFT JOIN `rto_delivery_run_sheet_mappings` `r3_0`     ON `r3_0`.`id` > `r2_0`.`id`  `r3_0`.`consignment_id` = `r2_0`.`consignment_id`     where `r3_0`.`id` ='';
+------------------------------------+---------+-----------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows | task      | access object                                                                        | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------------------+---------+-----------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_9                       | 1.25    | root      |                                                                                      | test.rto_delivery_run_sheet_mappings.id, test.rto_delivery_run_sheet_mappings.rto_drs_id, test.rto_delivery_run_sheet_mappings.fe_id, test.rto_delivery_run_sheet_mappings.is_active, test.rto_delivery_run_sheet_mappings.waybill_no, test.rto_delivery_run_sheet_mappings.consignment_id, test.rto_delivery_run_sheet_mappings.created_at, test.rto_delivery_run_sheet_mappings.updated_at, test.rto_delivery_run_sheet_mappings.id, test.rto_delivery_run_sheet_mappings.rto_drs_id, test.rto_delivery_run_sheet_mappings.fe_id, test.rto_delivery_run_sheet_mappings.is_active, test.rto_delivery_run_sheet_mappings.waybill_no, test.rto_delivery_run_sheet_mappings.consignment_id, test.rto_delivery_run_sheet_mappings.created_at, test.rto_delivery_run_sheet_mappings.updated_at |
| └─IndexHashJoin_16                 | 1.25    | root      |                                                                                      | inner join, inner:IndexLookUp_13, outer key:test.rto_delivery_run_sheet_mappings.consignment_id, inner key:test.rto_delivery_run_sheet_mappings.consignment_id, equal cond:eq(test.rto_delivery_run_sheet_mappings.consignment_id, test.rto_delivery_run_sheet_mappings.consignment_id)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|   ├─Selection_26(Build)            | 1.00    | root      |                                                                                      | not(isnull(test.rto_delivery_run_sheet_mappings.consignment_id))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|   │ └─Point_Get_25                 | 1.00    | root      | table:rto_delivery_run_sheet_mappings                                                | handle:0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|   └─IndexLookUp_13(Probe)          | 1.25    | root      |                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|     ├─Selection_12(Build)          | 1.25    | cop[tikv] |                                                                                      | not(isnull(test.rto_delivery_run_sheet_mappings.consignment_id))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|     │ └─IndexRangeScan_10          | 1.25    | cop[tikv] | table:r2_0, index:rto_delivery_run_sheet_mappings_consignment_id_IDX(consignment_id) | range: decided by [eq(test.rto_delivery_run_sheet_mappings.consignment_id, test.rto_delivery_run_sheet_mappings.consignment_id) gt(0, test.rto_delivery_run_sheet_mappings.id)], keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|     └─TableRowIDScan_11(Probe)     | 1.25    | cop[tikv] | table:r2_0                                                                           | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+------------------------------------+---------+-----------+--------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
8 rows in set, 2 warnings (0.01 sec)
```



What is your TiDB version? (Required)
v8.5.3

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #64329 

Problem Summary: planner: support left outer join into anti semi join

### What changed and how does it work?

This PR introduces two optimization patterns for transforming LEFT JOIN queries into NOT EXISTS subqueries when checking for missing matches.

#### Scenario 1: IS NULL on the Join Condition Column

- In this scenario, the IS NULL filter is applied directly to the join key from the inner table.

##### Table Schema
```
CREATE TABLE Table_A (
    id INT,
    name VARCHAR(50)
);

CREATE TABLE Table_B (
    id INT, -- Join Key
    info VARCHAR(50)
);
```

##### Plan

```
-- The optimizer rewrites the LEFT JOIN ... WHERE ... IS NULL pattern into an efficient
-- Anti Semi Join to retrieve rows from Table A that have no match in Table B.
SELECT 
    Table_A.id, 
    Table_A.name
FROM 
    Table_A
LEFT JOIN 
    Table_B ON Table_A.id = Table_B.id
WHERE 
    Table_B.id IS NULL;
```

```
+--------------------------+-----------+---------------+--------------------------------------------------------------------------------------+
| id                       | task      | access object | operator info                                                                        |
+--------------------------+-----------+---------------+--------------------------------------------------------------------------------------+
| Projection               | root      |               | test.table_a.id, test.table_a.name                                                   |
| └─Selection              | root      |               | isnull(test.table_b.id)                                                              |
|   └─HashJoin             | root      |               | left outer join, left side:TableReader, equal:[eq(test.table_a.id, test.table_b.id)] |
|     ├─TableReader(Build) | root      |               | data:Selection                                                                       |
|     │ └─Selection        | cop[tikv] |               | not(isnull(test.table_b.id))                                                         |
|     │   └─TableFullScan  | cop[tikv] | table:B       | keep order:false, stats:pseudo                                                       |
|     └─TableReader(Probe) | root      |               | data:TableFullScan                                                                   |
|       └─TableFullScan    | cop[tikv] | table:A       | keep order:false, stats:pseudo                                                       |
+--------------------------+-----------+---------------+--------------------------------------------------------------------------------------+
```
=>

```
+----------------------+-----------+---------------+-------------------------------------------------------------------------------------+
| id                   | task      | access object | operator info                                                                       |
+----------------------+-----------+---------------+-------------------------------------------------------------------------------------+
| HashJoin             | root      |               | anti semi join, left side:TableReader, equal:[eq(test.table_a.id, test.table_b.id)] |
| ├─TableReader(Build) | root      |               | data:Selection                                                                      |
| │ └─Selection        | cop[tikv] |               | not(isnull(test.table_b.id))                                                        |
| │   └─TableFullScan  | cop[tikv] | table:B       | keep order:false, stats:pseudo                                                      |
| └─TableReader(Probe) | root      |               | data:TableFullScan                                                                  |
|   └─TableFullScan    | cop[tikv] | table:A       | keep order:false, stats:pseudo                                                      |
+----------------------+-----------+---------------+-------------------------------------------------------------------------------------+
```

#### Scenario 2: IS NULL on a Non-Join NOT NULL Column

If a column in the inner table is defined as `NOT NULL` in the schema, but is filtered as `IS NULL` after the join, it implies that the join failed to find a match. This allows us to convert the join into ```ANTI SEMI JOIN``` even if the column is not part of the join keys. （just guarantee that  the condition only filter those null rows only generated from null supplied side）

##### Table Schema:

```
CREATE TABLE Table_A (
    id INT,
    name VARCHAR(50)
);

CREATE TABLE Table_B (
    id INT,
    status VARCHAR(20) NOT NULL -- Non-join column with NOT NULL constraint
);
```
##### Plan 

```
-- Even though 'status' is not a join key, its NOT NULL constraint 
-- ensures that 'B.status IS NULL' only occurs when no match is found.
SELECT A.* FROM Table_A A 
LEFT JOIN Table_B B ON A.id = B.id 
WHERE B.status IS NULL;
```

```
+--------------------------+-----------+---------------+--------------------------------------------------------------------------------------+
| id                       | task      | access object | operator info                                                                        |
+--------------------------+-----------+---------------+--------------------------------------------------------------------------------------+
| Projection               | root      |               | test.table_a.id, test.table_a.name                                                   |
| └─Selection              | root      |               | isnull(test.table_b.status)                                                          |
|   └─HashJoin             | root      |               | left outer join, left side:TableReader, equal:[eq(test.table_a.id, test.table_b.id)] |
|     ├─TableReader(Build) | root      |               | data:Selection                                                                       |
|     │ └─Selection        | cop[tikv] |               | not(isnull(test.table_b.id))                                                         |
|     │   └─TableFullScan  | cop[tikv] | table:B       | keep order:false, stats:pseudo                                                       |
|     └─TableReader(Probe) | root      |               | data:TableFullScan                                                                   |
|       └─TableFullScan    | cop[tikv] | table:A       | keep order:false, stats:pseudo                                                       |
+--------------------------+-----------+---------------+--------------------------------------------------------------------------------------+
```

=>

```
+----------------------+-----------+---------------+-------------------------------------------------------------------------------------+
| id                   | task      | access object | operator info                                                                       |
+----------------------+-----------+---------------+-------------------------------------------------------------------------------------+
| HashJoin             | root      |               | anti semi join, left side:TableReader, equal:[eq(test.table_a.id, test.table_b.id)] |
| ├─TableReader(Build) | root      |               | data:Selection                                                                      |
| │ └─Selection        | cop[tikv] |               | not(isnull(test.table_b.id))                                                        |
| │   └─TableFullScan  | cop[tikv] | table:B       | keep order:false, stats:pseudo                                                      |
| └─TableReader(Probe) | root      |               | data:TableFullScan                                                                  |
|   └─TableFullScan    | cop[tikv] | table:A       | keep order:false, stats:pseudo                                                      |
+----------------------+-----------+---------------+-------------------------------------------------------------------------------------+
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

https://github.com/PingCAP-QE/planreplayertest/pull/31

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+
+import (
+	"context"
+
+	"github.com/pingcap/tidb/pkg/planner/core/base"
+	"github.com/pingcap/tidb/pkg/planner/core/operator/logicalop"
+)
+
+// OuterJoinToSemiJoin is a logical optimization rule that converts outer joins followed by selections into semi-joins.
+type OuterJoinToSemiJoin struct{}
```
Comment (qw4990) [inline pkg/planner/core/rule/rule_outer_join_to_semi_join.go:52]: Please add more comments for the rule, especially how it works and some examples..

Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go:52]: OK, I have updated the comments and add more comments for it.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 2]
```diff
@@ -265,6 +267,196 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+					// range loop has exited/stopped
+					return
+				}
+			}
+		}
+	}
+}
+
+// filterOutOtherCondition4ConvertAntiJoin is to iterate all other condition's out columns except GT, GE, LE, LT, NE ones.
+func filterOutOtherCondition4ConvertAntiJoin(inner int, sf []expression.Expression) iter.Seq[*expression.Column] {
```
Comment (qw4990) [inline pkg/planner/core/operator/logicalop/logical_join.go]: Could we avoid using this `iter.Seq` and just use `[]*expression.Column`? These special structures make our code more complex...

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 3]
```diff
@@ -265,6 +267,196 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	for idx, c := range proj.Schema().Columns {
+		if !c.Equals(proj.Exprs[idx]) {
+			return false
+		}
+	}
+	return true
+}
+
+// CanConvertAntiJoin is used in outer-join-to-semi-join rule.
+func (p *LogicalJoin) CanConvertAntiJoin(ret []expression.Expression, selectSch *expression.Schema, proj *LogicalProjection) (result *LogicalProjection, selConditionColInOuter bool) {
```
Comment (qw4990) [inline pkg/planner/core/operator/logicalop/logical_join.go]: Please add more comments with SQLs or plan trees to describe in which scenarios we expect to convert the join.
For example: 
```
Selection(inner.col is null)
    LeftOuterJoin()
```

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: OK, I have refactor this code.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: OK, I have updated more comments here.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 4]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	if len(selectCond) != 1 || (len(p.EqualConditions) == 0 && len(p.OtherConditions) == 0) {
+		// selectCond can only have one expression.
+		// The inner expression can definitely be pushed down, so selectCond must be the outer expression.
+		// If they are semantically similar, leaving only one and the other should be eliminable.
+		return nil, false
+	}
+	if _, ok := p.Self().(*LogicalApply); ok {
+		return nil, false
+	}
+	innerChildIdx := 0
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]:
```suggestion
	var innerChildIdx int
```

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 5]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	// Get the Column in the IsNull
+	isNullcol, ok = args[0].(*expression.Column)
+	if !ok {
+		return nil, false
+	}
+	inner := p.children[innerChildIdx]
+	innerSch := inner.Schema()
+	outerSchSet := intset.NewFastIntSet()
+	// Obtain all the columns that meet the requirements in the eq condition and other condition.
+	// If the column that is isnull is an outside column in the eq/other condition,
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: Guess you should refine this comment

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 6]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+		return nil, false
+	}
+	args := sf.GetArgs()
+	// Get the Column in the IsNull
+	isNullcol, ok = args[0].(*expression.Column)
+	if !ok {
+		return nil, false
+	}
+	inner := p.children[innerChildIdx]
+	innerSch := inner.Schema()
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: In tidb code, `Schema` is never abbreviated as `Sch`. I suggest avoid using `Sch` to keep the naming consistent.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 7]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	for _, s := range eq {
+		if s.FuncName.L == ast.NullEQ {
+			continue
+		}
+		col1, col2, ok := expression.IsColOpCol(s)
+		if ok {
+			var col *expression.Column
+			// In left outer join，equal condition is inner colomn =  outer column
+			// In right outer join, equal condition is outer colomn = inner column
+			if inner == 0 {
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: This check is dangerous.
I think you should check schema to decide whether `col1` is from inner side of outer side.
Because if some code flip the left and right side of the join condition(whether intentionally or not), it will lead to semantic error here.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 8]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
 	return ret, newnChild, err
 }
 
+// filterOutNullEQAndOtherCondition4ConvertAntiJoin is to iterate all equal condition's out columns except NullEQ ones
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_join.go]: This function is mainly to find the not null columns.
We can make its name easier to understand.
The comments also need updating.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 9]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+		// If they are semantically similar, leaving only one and the other should be eliminable.
+		return nil, false
+	}
+	if _, ok := p.Self().(*LogicalApply); ok {
+		return nil, false
+	}
+	innerChildIdx := 0
+	switch p.JoinType {
+	case base.LeftOuterJoin:
+		innerChildIdx = 0
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: I think you mess up the inner and outer index here.
In tidb code, we treat `innerChildIdx` as the index of the inner side of JOIN, which is the null-producing side.
So for LEFT OUTER JOIN, `innerChildIdx` should be 1.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 10]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+		}
+	}
+	return true
+}
+
+// CanConvertAntiJoin is used in outer-join-to-semi-join rule.
+/*
+#### Scenario 1: IS NULL on the Join Condition Column
+
+- In this scenario, the IS NULL filter is applied directly to the join key from the outer table.
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_join.go]: from the example `a left join b on a.id=b.id where b.id is null`, the is null is from its inner side, not the outer side.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 11]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+| ├─TableReader(Build) | root      |               | data:Selection                                                                      |
+| │ └─Selection        | cop[tikv] |               | not(isnull(test.table_b.id))                                                        |
+| │   └─TableFullScan  | cop[tikv] | table:B       | keep order:false, stats:pseudo                                                      |
+| └─TableReader(Probe) | root      |               | data:TableFullScan                                                                  |
+|   └─TableFullScan    | cop[tikv] | table:A       | keep order:false, stats:pseudo                                                      |
++----------------------+-----------+---------------+-------------------------------------------------------------------------------------+
+```
+#### Scenario 2: IS NULL on a Non-Join NOT NULL Column
+
+If a column in the outer table is defined as `NOT NULL` in the schema, but is filtered as `IS NULL` after the join, it implies that the join failed to find a match. This allows us to convert the join into ```ANTI SEMI JOIN``` even if the column is not part of the join keys.
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_join.go]: The following description is also wrong:(

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 12]
```diff
@@ -265,6 +265,277 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	// If the column that is isnull is an outside column in the eq/other condition,
+	// It can be directly converted into an anti semi join.
+	expression.ExtractColumnsSetFromExpressions(&outerSchSet, func(c *expression.Column) bool {
+		return !innerSch.Contains(c)
+	}, expression.Column2Exprs(p.Schema().Columns)...)
+	joinOuterKeySch := intset.NewFastIntSet()
+	if !vaildProj4ConvertAntiJoin(proj) {
+		return nil, false
+	}
+	filterOutNullEQAndOtherCondition4ConvertAntiJoin(innerChildIdx, &joinOuterKeySch, p.EqualConditions, p.OtherConditions)
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_join.go]: Do we need this extra `joinOuterKeySchema` while we've created `outerSchemaSet`?

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 4 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Done

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 6 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Updated.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 7 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have updated.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 10 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have updated.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 11 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have updated.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 12 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have refactored this code.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 8 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have renamed this function.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 9 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have rewrite this code here.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 5 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have updated.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 13]
```diff
@@ -265,6 +265,275 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+Currently, we only support projections with column mapping relationships, not transformation relationships.
+
+	Projection[null->col1,null->col2,col3,col4] <- anti semi join[outer side: col1 col2, inner side: col3 col4]
+
+*/
+func (p *LogicalJoin) CanConvertAntiJoin(selectCond []expression.Expression, selectSch *expression.Schema, proj *LogicalProjection) (resultProj *LogicalProjection, selConditionColInInner bool) {
+	if len(selectCond) != 1 || (len(p.EqualConditions) == 0 && len(p.OtherConditions) == 0) {
+		// selectCond can only have one expression.
+		// The inner expression can definitely be pushed down, so selectCond must be the outer expression.
+		// If they are semantically similar, leaving only one and the other should be eliminable.
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: what does this comment mean? can you explain in more detail

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 14]
```diff
@@ -265,6 +265,275 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	case base.RightOuterJoin:
+		outerChildIdx = 1
+	default:
+		return nil, false
+	}
+
+	var sf *expression.ScalarFunction
+	var ok bool
+	var isNullcol *expression.Column
+	sf, ok = selectCond[0].(*expression.ScalarFunction)
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: nit:
```suggestion
	sf, ok := selectCond[0].(*expression.ScalarFunction)
```

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 15]
```diff
@@ -265,6 +265,275 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	if !ok || sf == nil {
+		return nil, false
+	}
+	if sf.FuncName.L != ast.IsNull {
+		return nil, false
+	}
+	args := sf.GetArgs()
+	// Get the Column in the IsNull
+	isNullcol, ok = args[0].(*expression.Column)
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: `isNullcol` -> `isNullCol` ?

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 16]
```diff
@@ -265,6 +265,275 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+			return false
+		}
+	}
+	return true
+}
+
+// CanConvertAntiJoin is used in outer-join-to-semi-join rule.
+/*
+#### Scenario 1: IS NULL on the Join Condition Column
+
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: Can you refine this comments:
1. remove redundant empty lines to make comment more compact
2. remove the output of explain, and use SQL to illustrate, like `SELECT * FROM t1 LEFT JOIN t2 ON t1.id = t2.id where t2.id IS NULL` -> `SELECT * FROM t1 WHERE NOT EXISTS (SELECT 1 FROM t2 WHERE t1.id = t2.id)

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 17]
```diff
@@ -265,6 +265,275 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	// Obtain all the columns that meet the requirements in the eq condition and other condition.
+	// If the column that is isnull is an inner column in the eq/other condition,
+	// It can be directly converted into an anti semi join.
+	expression.ExtractColumnsSetFromExpressions(&innerSchemaSet, func(c *expression.Column) bool {
+		return !outerSchema.Contains(c)
+	}, expression.Column2Exprs(p.Schema().Columns)...)
+	if !vaildProj4ConvertAntiJoin(proj) {
+		return nil, false
+	}
+	selConditionColInInner = isNullFromInner(&innerSchemaSet, isNullcol.UniqueID, p.EqualConditions, p.OtherConditions)
```
Comment (guo-shaoge) [inline pkg/planner/core/operator/logicalop/logical_join.go]: why not consider `rightCond` for LEFT JOIN and `leftCond` for RIGHT JOIN?
for example:
`select * from t1 left join t2 on t2.id < 10 where t2.id is null`

File: pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_in.json [hunk 18]
```diff
@@ -0,0 +1,61 @@
...
+      // GROUP 8: Projecting columns from both tables (Negative cases for Semi Join conversion)
+      // These conversions should NOT happen because Semi/Anti-Semi Join cannot project columns from the inner table.
+      "select A.*, B.val from A left join B on A.id = B.a_id where B.val > 10",
+      "select A.id, B.val from A left join B on A.id <=> B.a_id where B.val > 0",
+      "select A.id, B.non_null_col from A left join B on A.id = B.a_id where B.non_null_col IS NULL",
+      "select B.id, A.val from A right join B on A.id = B.a_id where A.val > 10",
+      "select B.val, A.id from A right join B on A.val <=> B.val where A.id IS NULL",
+      "select A.id, B.id from A left join B on A.id < B.a_id where B.id is null",
+      "select A.val, B.val from A left join B on A.val = B.val where B.non_null_col IS NULL",
+      "select A.id, B.val from A left join B on A.id = B.a_id where B.val > 0"
```
Comment (guo-shaoge) [inline pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_in.json:62]: Could you add some cases to cover more edge cases for join eq cond, like the following cases:
You can see the first LEFT JOIN is not equal to the second ANTI SEMI JOIN semantically.
Looks like your PR didn't consider this situation?
```
TiDB root@127.0.0.1:test> select * from t1 left join t2 on t1.c1 = t2.c1 is null where t2.c1 is null;
+----+--------+
| c1 | c1     |
+----+--------+
| 1  | <null> |
| 2  | <null> |
+----+--------+
2 rows in set
Time: 0.008s
TiDB root@127.0.0.1:test> select * from t1 where not exists (select * from t2 where t1.c1 = t2.c1 is null);
+----+
| c1 |
+----+
+----+
0 rows in set
Time: 0.007s
```

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 13 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Yes, I updated.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 14 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Done

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 15 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: update.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 16 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have updated.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 17 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: Sometimes, this occurs under "other conditions," making it difficult to distinguish.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 19]
```diff
@@ -265,6 +265,240 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
 	return ret, newnChild, err
 }
 
+// isNullFromInner is to iterate all equal condition's inner columns except NullEQ ones
+// and all other condition's columns except GT, GE, LE, LT, NE ones. and then check where
+// is null columns is from the join key in the inner table.
+func isNullFromInner(innerSchSet *intset.FastIntSet, isNullColumnID int64, eq []*expression.ScalarFunction, other []expression.Expression) bool {
```
Comment (winoros) [inline pkg/planner/core/operator/logicalop/logical_join.go]: This is to filter cols that are null-rejective by the given predicates.
So its name is not appropriate.

File: pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_in.json (hunk 18 above)
Comment (hawkingrei) [reply pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_in.json:62]: We have considered this situation and I updated this test case.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 19 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: OK, I have updated this code.

File: pkg/planner/core/optimizer.go [hunk 20]
```diff
@@ -104,6 +104,7 @@ var optRuleList = []base.LogicalOptRule{
 	&PushDownTopNOptimizer{},
 	&rule.SyncWaitStatsLoadPoint{},
 	&JoinReOrderSolver{},
+	&rule.OuterJoinToSemiJoin{},
```
Comment (guo-shaoge) [inline pkg/planner/core/optimizer.go:107]: Why put it here, for example if we can put it before rule_join_reorder, we may get better join order.
The order of this rule is very **subtle**.
But I think it's ok to tweak this order in the future.

File: pkg/planner/core/logical_plan_builder.go [hunk 21]
```diff
@@ -592,12 +592,12 @@ func (b *PlanBuilder) buildJoin(ctx context.Context, joinNode *ast.Join) (base.L
...
 		// left outer join need to be checked elimination
-		b.optFlag = b.optFlag | rule.FlagEliminateOuterJoin
+		b.optFlag = b.optFlag | rule.FlagEliminateOuterJoin | rule.FlagOuterJoinToSemiJoin
 		joinPlan.JoinType = base.LeftOuterJoin
 		util.ResetNotNullFlag(joinPlan.Schema(), leftPlan.Schema().Len(), joinPlan.Schema().Len())
 	case ast.RightJoin:
 		// right outer join need to be checked elimination
-		b.optFlag = b.optFlag | rule.FlagEliminateOuterJoin
+		b.optFlag = b.optFlag | rule.FlagEliminateOuterJoin | rule.FlagOuterJoinToSemiJoin
 		joinPlan.JoinType = base.RightOuterJoin
```
Comment (guo-shaoge) [inline pkg/planner/core/logical_plan_builder.go:601]: Is there any reason that this flag is not added in function `buildApplyWithJoinType`

**Comment by guo-shaoge** [comment]
feel free to unhold if you're ready to merge

File: pkg/planner/core/optimizer.go (hunk 20 above)
Comment (hawkingrei) [reply pkg/planner/core/optimizer.go:107]: It is placed here to prevent affecting join reorder. Currently, join reorder has insufficient support for anti semi, which will block join reorder.

File: pkg/planner/core/logical_plan_builder.go (hunk 21 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go:601]: I have added the commit for it.

File: pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_out.json [hunk 22]
```diff
@@ -0,0 +1,634 @@
...
+        "Plan": [
+          "HashJoin root  anti semi join, left side:TableReader, equal:[eq(test.a.id, test.b.a_id)]",
+          "├─TableReader(Build) root  data:Selection",
+          "│ └─Selection cop[tikv]  not(isnull(test.b.a_id))",
+          "│   └─TableFullScan cop[tikv] table:B keep order:false, stats:pseudo",
+          "└─TableReader(Probe) root  data:TableFullScan",
+          "  └─TableFullScan cop[tikv] table:A keep order:false, stats:pseudo"
+        ],
+        "Result": [
+          "3 <nil> 300",
```
Comment (AilinKid) [inline pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_out.json:81]: result is not stable for the order

File: pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_in.json [hunk 23]
```diff
@@ -0,0 +1,64 @@
...
+      // GROUP 1: LEFT JOIN to SEMI JOIN (Positive cases, equi-join on id)
+      "select A.* from A left join B on A.id = B.a_id where B.val > 0",
+      "select A.* from A left join B on A.id = B.a_id is null where B.val > 0",
+      "select A.* from A left join B on A.id <=> B.a_id where B.val > 0",
+      "select A.* from A left join B on A.id = B.a_id and B.val > 100 where B.id is not null",
+
+      // GROUP 2: LEFT JOIN to ANTI SEMI JOIN (Positive cases, equi-join on id)
+      "select A.* from A left join B on A.id = B.a_id where B.id IS NULL",
+      "select A.* from A left join B on A.id = B.a_id where B.non_null_col IS NULL",
+      "select A.* from A left join B on A.id = B.a_id is null where B.non_null_col IS NULL",
```
Comment (AilinKid) [inline pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_in.json:14]: join condition is quite strange, A.id = B.a_id is null, which means the A.id only be equal to 0 or 1, is this expected?

Comment (AilinKid) [reply pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_in.json:14]: i see jiangtao‘s suggestions, ok

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 24]
```diff
@@ -265,6 +265,244 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	SELECT 1 FROM Table_B B WHERE A.id = B.id
+);
+```
+
+Additionally, we found that there may be a projection between select and join.
+	Select[isnull(col1)] <- Projection[col1,col2,col3,col4] <- left outer join[outer side: col1 col2, inner side: col3 col4]
+Currently, we only support projections with column mapping relationships, not transformation relationships.
+	Projection[null->col1,null->col2,col3,col4] <- anti semi join[outer side: col1 col2, inner side: col3 col4]
+*/
+func (p *LogicalJoin) CanConvertAntiJoin(selectCond []expression.Expression, selectSch *expression.Schema, proj *LogicalProjection) (resultProj *LogicalProjection, canConvertToAntiSemiJoin bool) {
```
Comment (AilinKid) [inline pkg/planner/core/operator/logicalop/logical_join.go]: since it is more related about the rule xform logic, can we just move it into the OuterJoinToSemiJoin{}, and also migrate the comment here.

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 25]
```diff
@@ -265,6 +265,244 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	// Obtain all the columns that meet the requirements in the eq condition and other condition.
+	// If the column that is isnull is an inner column in the eq/other condition,
+	// It can be directly converted into an anti semi join.
+	expression.ExtractColumnsSetFromExpressions(&innerSchemaSet, func(c *expression.Column) bool {
+		return !outerSchema.Contains(c)
+	}, expression.Column2Exprs(p.Schema().Columns)...)
+	if !validProj4ConvertAntiJoin(proj) {
+		return nil, false
+	}
+	canConvertToAntiSemiJoin = joinCondNullRejectsInnerCol(&innerSchemaSet, isNullCol.UniqueID, p.EqualConditions, p.OtherConditions)
```
Comment (AilinKid) [inline pkg/planner/core/operator/logicalop/logical_join.go]: i think this value name can changed as
···
joinCondNRInnerCol := joinCondNullRejectsInnerCol(xxx)
canConvertToAntiSemiJoin := joinCondNRInnerCol  && jsNullCol
···
which will be more logic corresponding

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 26]
```diff
@@ -265,6 +265,244 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	// resultProj is to generate the NULL values for the columns of the inner table, which is the
+	// expected result for this kind of anti-join query.
+	if canConvertToAntiSemiJoin {
+		// Scenario 1: column in IsNull expression is from the inner side columns in the eq/other condition.
+		if proj != nil {
+			resultProj = p.generateProject4ConvertAntiJoin(&innerSchemaSet, proj.Schema())
+		} else {
+			resultProj = p.generateProject4ConvertAntiJoin(&innerSchemaSet, selectSch)
+		}
+	} else if innerSchemaSet.Has(int(isNullCol.UniqueID)) {
```
Comment (AilinKid) [inline pkg/planner/core/operator/logicalop/logical_join.go]: ditto for this 
canConvertToAntiSemiJoin := notNullColAttri && jsNullCol

File: pkg/planner/core/operator/logicalop/logical_join.go [hunk 27]
```diff
@@ -265,6 +265,244 @@ func (p *LogicalJoin) PredicatePushDown(predicates []expression.Expression) (ret
...
+	}, expression.Column2Exprs(p.Schema().Columns)...)
+	if !validProj4ConvertAntiJoin(proj) {
+		return nil, false
+	}
+	canConvertToAntiSemiJoin = joinCondNullRejectsInnerCol(&innerSchemaSet, isNullCol.UniqueID, p.EqualConditions, p.OtherConditions)
+	// resultProj is to generate the NULL values for the columns of the inner table, which is the
+	// expected result for this kind of anti-join query.
+	if canConvertToAntiSemiJoin {
+		// Scenario 1: column in IsNull expression is from the inner side columns in the eq/other condition.
+		if proj != nil {
```
Comment (AilinKid) [inline pkg/planner/core/operator/logicalop/logical_join.go]: we can simplify the code here generateProject4ConvertAntiJoin only care about the schema, just pass the proj.schema() or scelectSchema is ok.

Comment (AilinKid) [reply pkg/planner/core/operator/logicalop/logical_join.go]: and for this check
```
expression.Column2Exprs(p.Schema().Columns)...)
	if !validProj4ConvertAntiJoin(proj) {
		return nil, false
	}
```
i think it can be move out of this function, which means parameter proj *LogicalProjection can be eliminated, and since proj's expr are all same as proj.schema, and selection's schema only refers it child, we can only use selectSchema here.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 24 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: OK, I have moved them into rule.

File: pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_out.json (hunk 22 above)
Comment (hawkingrei) [reply pkg/planner/core/casetest/rule/testdata/outer_to_semi_join_suite_out.json:81]: OK, I have updated.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 25 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: OK, I have refactored this code.

File: pkg/planner/core/operator/logicalop/logical_join.go (hunk 27 above)
Comment (hawkingrei) [reply pkg/planner/core/operator/logicalop/logical_join.go]: I have moved out of this function

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go [hunk 28]
```diff
@@ -0,0 +1,342 @@
...
+	}
+
+	if canConvertToAntiSemiJoin {
+		// Anti-semi join's first child is outer, the second child is inner. join condition is outer op inner
+		// right outer join's first child is inner, the second child is outer, join condition is inner op outer
+		// left outer join's  first child is outer, the second child is inner. join condition is outer op inner
+		// So we have to swap it here.
+		ctx := p.SCtx().GetExprCtx()
+		if p.JoinType == base.RightOuterJoin {
+			for idx, expr := range p.EqualConditions {
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go:289]: Grent.

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go [hunk 29]
```diff
@@ -0,0 +1,338 @@
...
+			p.LeftConditions = p.RightConditions
+			p.RightConditions = tmp
+		}
+		p.JoinType = base.AntiSemiJoin
+		p.MergeSchema()
+	}
+	return resultProj, canConvertToAntiSemiJoin
+}
+
+func validProjForConvertAntiJoin(proj *logicalop.LogicalProjection) bool {
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go]: I have fixed it.

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go [hunk 30]
```diff
@@ -0,0 +1,338 @@
...
+			for idx, expr := range p.EqualConditions {
+				args := expr.GetArgs()
+				p.EqualConditions[idx] = expression.NewFunctionInternal(ctx, expr.FuncName.L, expr.GetType(ctx.GetEvalCtx()), args[1], args[0]).(*expression.ScalarFunction)
+			}
+			args := p.Children()
+			p.SetChildren(args[1], args[0])
+			tmp := p.LeftConditions
+			p.LeftConditions = p.RightConditions
+			p.RightConditions = tmp
+		}
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go:299]: Has fixed.

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go [hunk 31]
```diff
@@ -0,0 +1,338 @@
...
+	//  We need to check whether inner column is not null in the origin table schema.
+	//  If it is not null column, it can be directly converted into an anti-semi join.
+	innerSch := p.Children()[1^outerChildIdx].Schema()
+	// if isNullColInnerSchIdx < 0, it means the is null column is not in the inner schema.
+	isNullColInnerSchIdx := innerSch.ColumnIndex(isNullCol)
+	isNullColInInnerSch := isNullColInnerSchIdx >= 0 &&
+		mysql.HasNotNullFlag(innerSch.Columns[isNullColInnerSchIdx].RetType.GetFlag())
+
+	// meet either scenario can be converted to anti-semi join.
+	canConvertToAntiSemiJoin = joinCondNRInnerCol || isNullColInInnerSch
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go]: I have updated.

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go [hunk 32]
```diff
@@ -0,0 +1,338 @@
...
+							p.SetChild(idx, cc)
+						}
+						isChanged = true
+					}
+				}
+			}
+		}
+		updatedChild := p.Children()[idx]
+		_, changed := o.recursivePlan(updatedChild)
+		isChanged = isChanged || changed
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go]: Done

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go]: Done

File: pkg/planner/core/rule/rule_outer_join_to_semi_join.go [hunk 33]
```diff
@@ -0,0 +1,366 @@
...
+		if innerSchSet.Has(int(c.UniqueID)) {
+			projExprs = append(projExprs, expression.NewNull())
+		} else {
+			projExprs = append(projExprs, c.Clone())
+		}
+	}
+	proj = logicalop.LogicalProjection{Exprs: projExprs}.Init(p.SCtx(), p.QueryBlockOffset())
+	proj.SetSchema(parentNodeSchema.Clone())
+	return
+}
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply pkg/planner/core/rule/rule_outer_join_to_semi_join.go]: projection will be removed.
