### PR TITLE
streamhelper/advancer: Fix owner transfer metric

### LINKED ISSUE #42419: grafana show pitr lag more than 30m when inject kill one tidb
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
http://perf.pingcap.net:3000/d/WOw1JWmVk/ha-test-case-detail?orgId=1&refresh=10s&var-case_id=2610659
kill one tidb

### 2. What did you expect to see? (Required)
pitr lag less than 5m

### 3. What did you see instead (Required)
grafana show pitr lag more than 30m when inject kill one tidb
image

### 4. What is your TiDB version? (Required)
git hash：56412f514ecad4209cb0d92878b68644ed94469a

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve?

Issue Number: close #42419

Problem Summary:
When the owner get evicted but not restarted, its checkpoint metric may consist. 

### What is changed and how it works?
```commit-message
This PR make the owner remove the last checkpoint when it loses its ownership.
```

### Check List

Tests 

- [x] Unit test
(I think this could be covered by the existing tests in AdvancerDaemon.)
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
(TBD)
- [ ] No code

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fixed a bug that may cause PITR lag in the metrics grows too high when TiDB stop.
```

### CODE REVIEW

File: br/pkg/streamhelper/advancer_daemon.go [hunk 1]
```diff
@@ -48,6 +48,7 @@ func (c *CheckpointAdvancer) Name() string {
 
 func (c *CheckpointAdvancer) onStop() {
 	metrics.AdvancerOwner.Set(0.0)
+	metrics.LastCheckpoint.Reset()
```
Comment (3pointer) [inline br/pkg/streamhelper/advancer_daemon.go:51]: How about other metrics?  should also reset them?

Comment (YuJuncen) [reply br/pkg/streamhelper/advancer_daemon.go:51]: I think perhaps we don't need to reset them before some problems with them evaluated. 🤔

**Review by 3pointer — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]

File: br/pkg/streamhelper/advancer_daemon.go (hunk 1 above)
Comment (Tristan1900) [reply br/pkg/streamhelper/advancer_daemon.go:51]: can we put a comment here saying other metrics potentially need to be audit as well? And maybe a comment describing why do we need to reset checkpoint for this issue? I don't have context on this so just looking at the code I'm very clear what needs to be done. Thanks!

**Comment by Tristan1900** [comment]
Thanks for the fix!  
BTW can we put a commit message for this PR? I think you might need to wrap the description with quotes for commit message
