### PR TITLE
executor: disable closest replica read if cluster is not balanced

### LINKED ISSUE #35926: more flexible follower read dispatch strategy
## Enhancement

In the cloud environment, the tidb clusters are commonly deployed across multiple "Access Zone"(AZ for short)s. Because the traffic cost across different AZ is much higher than within the same AZ. We can reduce the cost by dispatching read request to 
the TiKV/TiFlash with a higher priority. 

#28033 introduced a new `tidb_replica_read` option "closest-replica" that always dispatch all read request to the closest TiKV. But since the "follower read" feature need to propose an extra "readIndex" message through the raft state machine. This overhead may cause performance regression. For cop requests with small response, read from local AZ can not save the traffic because the extra "readIndex" messages are always cross AZ traffic. And the extra cpu usage to process these raft message can hurt the performance.

I propose to add a new option "closest-adaptive" for `tidb_replica_read` variable. This new option tries to dispatch request to the nearest store only when the response size is bigger than a certain threshold which is define by a new variable "tidb_adaptive_closest_read_threshold".

BTW, when the cop traffic from tidbs in different AZ are not evenly distributed, it may cause high load in some store while other are low loaded. This can cause high tail-lantency and low overall throughput. So when follow-read is enabled, the tikv client may need to track the load of each storage and force fallback to leader read when some stores' load are high.

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: ref #35926

Problem Summary:

### What is changed and how it works?
#35927 has introduce a new replica_read type `closest-replica` which will dispatch read request to the store within the same AZ. But in this mode, if the read traffic is not evenly distributed across AZs, it may cause unbalanced load in tikv and affect the overall performance. 

This PR alleviate this problem by add a periodically check when `closest-replica` is enabled. Every 60s, it checks that all AZs contain both tidb and tikv instances, if not it will disables `closest-replica` and fallback to leader read. In this simple way, we can avoid the traffic skew in most cases.

NOTE: in my benchmark, there are two problems that may affect the effect of this check:
1. The check depends on `infosync.GetAllServerInfo` to fetch all active tidb instances. This information is stored in etcd with a ttl of 10min. Because of #36793, tidb is likely to panic at exit and can't delete self from the etcd which may cause misjudgement.
2. If the app uses long conneciton, when a new tidb is up, the traffic can't be dispatch to it because exist connection can't be moved. Thus though the cluster itself is even, but the traffic is still not even. This PR can't hanle this kind of cases.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
@qw4990 @nolouch  PTAL, thank you

**Comment by glorv** [comment]
@nolouch @qw4990 Could you please take a look? The related tidb-operator PR is merged now.

File: domain/domain.go [hunk 1]
```diff
@@ -932,6 +940,91 @@ func (do *Domain) initLogBackup(ctx context.Context, pdClient pd.Client) error {
...
+	}
+
+	zones := make(map[string]int)
+	for _, s := range stores {
+		// skip tumbstone stores or tiflash
+		if s.NodeState == metapb.NodeState_Removing || s.NodeState == metapb.NodeState_Removed || engine.IsTiFlash(s) {
+			continue
+		}
+		for _, label := range s.Labels {
+			if label.Key == placement.DCLabelKey && label.Value != "" {
```
Comment (nolouch) [inline domain/domain.go:993]: will tikv be label `zone=xxx` in cloud?

File: domain/domain.go [hunk 2]
```diff
@@ -932,6 +940,91 @@ func (do *Domain) initLogBackup(ctx context.Context, pdClient pd.Client) error {
...
+	}
+	if matches {
+		for _, count := range zones {
+			if count == 0 {
+				matches = false
+				break
+			}
+		}
+	}
+	if variable.SetEnableAdaptiveReplicaRead(matches) {
```
Comment (nolouch) [inline domain/domain.go:1022]: What's the difference between `closest-adaptive` and `closest-read` after the PR https://github.com/pingcap/tidb/pull/35927?  Do them has the same dispatch strategy?

**Review by nolouch — COMMENTED** [review]
I think do not change the `close-replica`

File: domain/domain.go (hunk 1 above)
Comment (glorv) [reply domain/domain.go:993]: Yes.This special labels is assign either the user provide zone label or from the k8s label `topology.kubernetes.io/zone`. I'm not sure if it's better to allow the user to config the DCLabelKey instead

File: domain/domain.go (hunk 2 above)
Comment (glorv) [reply domain/domain.go:1022]: The only different is that `closest-read` always try to dispatch all request to the closest store while `closest-adaptive` only dispatch request to the closest store when the estimate response size exceeds certain threshold and fallback other requests to region leader.

File: domain/domain.go (hunk 1 above)
Comment (nolouch) [reply domain/domain.go:993]: but I check a cloud, the label key is `failure-domain.beta.kubernetes.io/zone`,  it is not equal to the `placement.DCLabelKey`.

Comment (glorv) [reply domain/domain.go:993]: `failure-domain.beta.kubernetes.io/zone` is the deprecated k8s location label. In newer version, the label is `topology.kubernetes.io/zone`.

Comment (glorv) [reply domain/domain.go:993]: I have update the logic in tidb-operator to use one of ["zone", "topology.kubernetes.io/zone", "failure-domain.beta.kubernetes.io/zone"], so it can be compatible in most case.

Comment (nolouch) [reply domain/domain.go:993]: Can we use `zone` directly? if the label key is too long, there is a performance issue https://github.com/tikv/pd/issues/5360. and also, it's more friendly for the user on the cloud to use placement rules.

Comment (glorv) [reply domain/domain.go:993]: Yes. operator will always set the `zone` label with one of `["zone", "topology.kubernetes.io/zone", "failure-domain.beta.kubernetes.io/zone"]`'s value, so we don't need to change the logic in tidb.
See:   https://github.com/pingcap/tidb-operator/blob/7551e27bede5938a868f2a6e718ab503e60203e8/pkg/manager/member/tidb_member_manager.go#L1120

File: domain/domain.go [hunk 3]
```diff
@@ -932,6 +940,91 @@ func (do *Domain) initLogBackup(ctx context.Context, pdClient pd.Client) error {
...
+		if v, ok := s.Labels[placement.DCLabelKey]; ok && v != "" {
+			if _, ok := zones[v]; !ok {
+				matches = false
+				break
+			}
+			zones[v] += 1
+		}
+	}
+	if matches {
+		for _, count := range zones {
```
Comment (nolouch) [inline domain/domain.go:1015]: I think we should avoid only deploying on one `zone`, it should not be enabled.

Comment (glorv) [reply domain/domain.go]: ok. I added a check handle this case.

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by glorv** [comment]
@qw4990 @winoros  PTAL

**Review by qw4990 — APPROVED** [review]

**Comment by glorv** [comment]
There is a goleak found related to br:

```
[2022-09-07T03:39:52.041Z] goleak: Errors on successful test run: found unexpected goroutines:

[2022-09-07T03:39:52.041Z] [Goroutine 16818 in state select, with go.etcd.io/etcd/client/v3.waitRetryBackoff on top of the stack:

[2022-09-07T03:39:52.041Z] goroutine 16818 [select]:

[2022-09-07T03:39:52.041Z] go.etcd.io/etcd/client/v3.waitRetryBackoff({0x422dcb8, 0xc000bd9c80}, 0x4?, 0xc001e78600?)

[2022-09-07T03:39:52.041Z] 	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.2/retry_interceptor.go:302 +0xa5

[2022-09-07T03:39:52.041Z] go.etcd.io/etcd/client/v3.(*Client).unaryClientInterceptor.func1({0x422dc80?, 0xc00243c300?}, {0x3cb51a1, 0x16}, {0x3ba3260, 0xc002318000}, {0x3b5bf20, 0xc002256050}, 0xc000d3c000, 0x3dab8b8, ...)

[2022-09-07T03:39:52.041Z] 	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.2/retry_interceptor.go:50 +0x1fa

[2022-09-07T03:39:52.041Z] google.golang.org/grpc.(*ClientConn).Invoke(0x60?, {0x422dc80?, 0xc00243c300?}, {0x3cb51a1?, 0x6?}, {0x3ba3260?, 0xc002318000?}, {0x3b5bf20?, 0xc002256050?}, {0xc00243c360, ...})

[2022-09-07T03:39:52.041Z] 	/go/pkg/mod/google.golang.org/grpc@v1.45.0/call.go:35 +0x223

[2022-09-07T03:39:52.041Z] go.etcd.io/etcd/api/v3/etcdserverpb.(*kVClient).Range(0xc000fb9fb0, {0x422dc80, 0xc00243c300}, 0xc002318000?, {0xc00243c360, 0x4, 0x6})

[2022-09-07T03:39:52.041Z] 	/go/pkg/mod/go.etcd.io/etcd/api/v3@v3.5.2/etcdserverpb/rpc.pb.go:6460 +0xc9

[2022-09-07T03:39:52.041Z] go.etcd.io/etcd/client/v3.(*retryKVClient).Range(0xc0021a3200, {0x422dc80, 0xc00243c300}, 0x691a80?, {0x6408be0, 0x3, 0x3})

[2022-09-07T03:39:52.041Z] 	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.2/retry.go:105 +0x133

[2022-09-07T03:39:52.041Z] go.etcd.io/etcd/client/v3.(*kv).Do(0xc001252d80, {_, _}, {0x1, {0xc0017be120, 0x11, 0x18}, {0xc0017be138, 0x11, 0x11}, ...})

[2022-09-07T03:39:52.041Z] 	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.2/kv.go:149 +0x1e8

[2022-09-07T03:39:52.041Z] go.etcd.io/etcd/client/v3.(*kv).Get(0x422dc48?, {0x422dc80, 0xc00243c300}, {0x3ca2f12?, 0x2?}, {0xc001502370?, 0x0?, 0x0?})

[2022-09-07T03:39:52.041Z] 	/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.2/kv.go:119 +0xdc

[2022-09-07T03:39:52.041Z] github.com/pingcap/tidb/domain/infosync.getInfo({0x422dc48?, 0xc000328000?}, 0xc001818e00, {0x3ca2f12, 0x11}, 0x5, 0x30?, {0xc001502370, 0x1, 0x1})

[2022-09-07T03:39:52.041Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/domain/infosync/info.go:938 +0x17e

[2022-09-07T03:39:52.041Z] github.com/pingcap/tidb/domain/infosync.(*InfoSyncer).getAllServerInfo(0xc0025ce1c0, {0x422dc48, 0xc000328000})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/domain/infosync/info.go:594 +0xc7

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/domain/infosync.GetAllServerInfo({0x422dc48, 0xc000328000})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/domain/infosync/info.go:341 +0x45

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/infoschema.GetTiDBServerInfo({0xc001f88ad0?, 0x33afad9?})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/infoschema/tables.go:1647 +0x3c

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/infoschema.GetClusterServerInfo({0x4292410, 0xc001b79b80})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/infoschema/tables.go:1632 +0xf9

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.fetchClusterConfig({0x4292410, 0xc001b79b80}, 0xc001f88e88, 0xc001f88e88)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:170 +0x70

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.(*ShowExec).fetchShowClusterConfigs(0xc00115e840, {0x0?, 0x400?})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/show.go:1253 +0x11e

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.(*ShowExec).fetchAll(0x4231ee0?, {0x422dcb8?, 0xc001bd89f0?})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/show.go:150 +0x18c

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.(*ShowExec).Next(0xc00115e840, {0x422dcb8, 0xc001bd89f0}, 0xc0007a64b0)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/show.go:115 +0xc8

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.Next({0x422dcb8, 0xc001bd89f0}, {0x4231ee0, 0xc00115e840}, 0xc0007a64b0)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/executor.go:324 +0x4f2

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.(*SelectionExec).Next(0xc001eb8410, {0x422dcb8, 0xc001bd89f0}, 0xc0007a6640)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/executor.go:1560 +0xf7

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.Next({0x422dcb8, 0xc001bd89f0}, {0x4231d20, 0xc001eb8410}, 0xc0007a6640)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/executor.go:324 +0x4f2

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.(*ExecStmt).next(0xc002926870, {0x422dcb8, 0xc001bd89f0}, {0x4231d20, 0xc001eb8410}, 0xc0006fa800?)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/adapter.go:937 +0x78

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/executor.(*recordSet).Next(0xc0007a65f0, {0x422dcb8?, 0xc001bd89f0?}, 0xc0007a6640)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/executor/adapter.go:152 +0xc5

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/session.drainRecordSet({0x422dcb8, 0xc001bd89f0}, 0xc001b79b80, {0x422e540, 0xc001bd93b0}, {0x0?, 0x0?})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/session/session.go:1284 +0xea

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/session.(*session).ExecRestrictedSQL.func1({0x422dcb8, 0xc001bd8990}, 0xc001b79b80)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/session/session.go:1940 +0x2f7

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/session.(*session).withRestrictedSQLExecutor(0x38469e0?, {0x422dcb8, 0xc001bd8990}, {0x0, 0x0, 0xc000328000?}, 0xc0013b38c0)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/session/session.go:1913 +0x2e8

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/session.(*session).ExecRestrictedSQL(0xafef70f690bb78f5?, {0x422dcb8?, 0xc001bd8990?}, {0x0?, 0x0?, 0x0?}, {0x3d082b1?, 0xc000ef7440?}, {0x0, 0x0, ...})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/session/session.go:1917 +0x8e

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/br/pkg/utils.IsLogBackupEnabled({0x7fa21c329cd8, 0xc001b78780})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/br/pkg/utils/db.go:72 +0xa2

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/br/pkg/utils.CheckLogBackupEnabled({0x4292410?, 0xc001b78780?})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/br/pkg/utils/db.go:54 +0x56

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/store/gcworker.(*GCWorker).checkLeader(0xc000d28000, {0x422dcb8, 0xc00265f530})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:1793 +0x12f

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/store/gcworker.(*GCWorker).tick(0xc0013b3e60?, {0x422dcb8, 0xc00265f530})

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:286 +0x45

[2022-09-07T03:39:52.042Z] github.com/pingcap/tidb/store/gcworker.(*GCWorker).start(0xc000d28000, {0x422dcb8, 0xc00265f530}, 0xc000328008?)

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:229 +0x4e5

[2022-09-07T03:39:52.042Z] created by github.com/pingcap/tidb/store/gcworker.(*GCWorker).Start

[2022-09-07T03:39:52.042Z] 	/home/jenkins/agent/workspace/tidb_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb/store/gcworker/gc_worker.go:120 +0x118

[2022-09-07T03:39:52.042Z] 

[2022-09-07T03:39:52.042Z] ]
```
/cc @3pointer
