### PR TITLE
executor: fix group_concat for cases like group_concat(123,null)

### LINKED ISSUE #9920: wrong result of `select group_concat(123, null)`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```sql
mysql> select group_concat(123,null);
```

2. What did you expect to see?
```sql
mysql> select group_concat(123,null);

+------------------------+
| group_concat(123,null) |
+------------------------+
| NULL                   |
+------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```sql
mysql> select group_concat(123,null);

+------------------------+
| group_concat(36, null) |
+------------------------+
|                        |
+------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
``` sql
Release Version: v3.0.0-beta.1-8-g7cabaac61
Git Commit Hash: 7cabaac61dbc7fa65948ee7fbd11018af7765369
Git Branch: master
UTC Build Time: 2019-03-27 01:47:14
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
### What problem does this PR solve? 
fix #9920 

### What is changed and how it works?
Make the behavior of group_concat be compatible with the MySQL manual:
> It returns NULL if there are no non-NULL values

Before this commit, we regard **every** argument as an item of the result of group_concat.
But actually, **all the arguments value in one row** should be regarded as one item. If any one of the arguments is null, the group_concat result of **this row** is null.

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects

N/A

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: executor/aggregate_test.go [hunk 1]
```diff
@@ -408,6 +408,9 @@ func (s *testSuite1) TestGroupConcatAggr(c *C) {
 
 	result = tk.MustQuery("select id, group_concat(name SEPARATOR '123') from test group by id order by id")
 	result.Check(testkit.Rows("1 101232012330", "2 20", "3 200123500"))
+
+	// #issue 9920
```
Comment (zz-jason) [inline executor/aggregate_test.go]:
```suggestion
	// issue #9920
```
