### PR TITLE
planner: fix the panic when we calculate the partition range

### LINKED ISSUE #23622: tidb panic: runtime error: slice bounds out of range
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table t2 (a int, b int) partition by range (a) (partition p0 values less than (0), partition p1 values less than (5));
insert into t2(a) values (-1), (1);
select * from t2 where a > 10 or b =  NULL;
```

### 2. What did you expect to see? (Required)
tidb not panic 
### 3. What did you see instead (Required)
tidb panic
```bash
2021/03/29 14:10:03.557 +08:00] [ERROR] [conn.go:736] ["connection running loop panic"] [conn=3] [lastSQL="select * from t2 where a > 10 or b =  NULL"] [err="runtime error: slice bounds out of range [1:0]"] [stack="goroutine 664 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x6a0cd40, 0xc0108699e0, 0xc00096da00)\n\t/Users/aytrack/gitproject/pingcap/tidb/server/conn.go:734 +0xf5\npanic(0x63c8640, 0xc013fbca80)\n\t/usr/local/go/src/runtime/panic.go:969 +0x175\ngithub.com/pingcap/tidb/planner/core.partitionRangeOR.simplify(0xc0129675f0, 0x0, 0x3, 0xc013fe8540, 0x69d9100, 0xc013fdd500)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:656 +0x1d7\ngithub.com/pingcap/tidb/planner/core.partitionRangeOR.union(...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:645\ngithub.com/pingcap/tidb/planner/core.partitionRangeForOrExpr(0x6a4fe40, 0xc010884400, 0x6a7b9a0, 0xc013fe5400, 0x6a7b720, 0xc013fe8540, 0x69d9100, 0xc013fdd500, 0x5464538, 0x6a4fe40, ...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:894 +0x1e5\ngithub.com/pingcap/tidb/planner/core.partitionRangeForExpr(0x6a4fe40, 0xc010884400, 0x6a7b9a0, 0xc013fe5540, 0x69d9100, 0xc013fdd500, 0xc0129675c0, 0x1, 0x3, 0x40, ...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:831 +0x33b\ngithub.com/pingcap/tidb/planner/core.partitionRangeForCNFExpr(0x6a4fe40, 0xc010884400, 0xc0139fc530, 0x1, 0x1, 0x69d9100, 0xc013fdd500, 0xc0129675c0, 0x1, 0x3, ...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:817 +0xa5\ngithub.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneRangePartition(0x831e5e0, 0x6a4fe40, 0xc010884400, 0xc0126cfa40, 0x6a443c0, 0xc0116ed340, 0xc0139fc530, 0x1, 0x1, 0xc013fd8d20, ...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:747 +0x310\ngithub.com/pingcap/tidb/planner/core.(*partitionProcessor).processRangePartition(0x831e5e0, 0xc013e28780, 0xc0126cfa40, 0x1, 0x6a7b9a0, 0x2, 0x2)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:752 +0x10e\ngithub.com/pingcap/tidb/planner/core.(*partitionProcessor).prune(0x831e5e0, 0xc013e28780, 0x10, 0x649d5c0, 0x12600000000, 0x0)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:540 +0x205\ngithub.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource(0x831e5e0, 0x6a4de80, 0xc013e28780, 0x1, 0x649d5c0, 0x0, 0x0)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:64 +0x78\ngithub.com/pingcap/tidb/planner/core.(*partitionProcessor).rewriteDataSource(0x831e5e0, 0x6a4e880, 0xc013ac7ea0, 0x0, 0xc00f80a870, 0x6316e40, 0xc00f80a870)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:92 +0x13e\ngithub.com/pingcap/tidb/planner/core.(*partitionProcessor).optimize(0x831e5e0, 0x6a0cd40, 0xc013fee330, 0x6a4e880, 0xc013ac7ea0, 0x6a4e880, 0xc013ac7ea0, 0x0, 0x0)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/rule_partition_processor.go:57 +0x3f\ngithub.com/pingcap/tidb/planner/core.logicalOptimize(0x6a0cd40, 0xc013fee330, 0x22a2, 0x6a4e880, 0xc013ac7ea0, 0x60616f3b, 0xc01099e488, 0x409a906, 0x60616f3b)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/optimizer.go:198 +0x11b\ngithub.com/pingcap/tidb/planner/core.DoOptimize(0x6a0cd40, 0xc013fee330, 0x6a4fe40, 0xc010884400, 0x2a2, 0x6a4e880, 0xc013ac7ea0, 0x0, 0x0, 0x0, ...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/core/optimizer.go:132 +0x77\ngithub.com/pingcap/tidb/planner.optimize(0x6a0cd40, 0xc013fee330, 0x6a4fe40, 0xc010884400, 0x6a23e80, 0xc013a76d00, 0x6a47c80, 0xc012880e60, 0x0, 0x0, ...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/optimize.go:289 +0x77f\ngithub.com/pingcap/tidb/planner.Optimize(0x6a0cd40, 0xc013fee330, 0x6a4fe40, 0xc010884400, 0x6a23e80, 0xc013a76d00, 0x6a47c80, 0xc012880e60, 0x0, 0x0, ...)\n\t/Users/aytrack/gitproject/pingcap/tidb/planner/optimize.go:125 +0x4a9\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile(0xc01099eda8, 0x6a0cd40, 0xc013fee330, 0x6a2a180, 0xc013a76d00, 0x0, 0x0, 0x0)\n\t/Users/aytrack/gitproject/pingcap/tidb/executor/compiler.go:62 +0x305\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc010884400, 0x6"]
```
### 4. What is your TiDB version? (Required)
```sql
mysql root@127.0.0.1:test> select tidb_version()\G
Reconnecting...
***************************[ 1. row ]***************************
tidb_version() | Release Version: v4.0.0-beta.2-2479-g1e3921aff
Edition: Community
Git Commit Hash: 1e3921aff5f7f2bcc02a3d520244ba1db547d734
Git Branch: master
UTC Build Time: 2021-03-29 06:03:42
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

```

### PR DESCRIPTION
**Pull request by Reminiscent**
### What problem does this PR solve?

Issue Number: close #23622 

Problem Summary: When we simplify the partition range, we do not consider the length of the slice. So it will cause panic in some cases.

### What is changed and how it works?
Check the length before the `simplify` first. If the length of the slice is zero, we should return early.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- fix the panic when we calculate the partition range

### CODE REVIEW

File: planner/core/rule_partition_processor.go [hunk 1]
```diff
@@ -655,6 +655,10 @@ func (or partitionRangeOR) Swap(i, j int) {
 
 func (or partitionRangeOR) union(x partitionRangeOR) partitionRangeOR {
 	or = append(or, x...)
+	// if the length of the `or` is zero. We should return early.
+	if len(or) == 0 {
+		return or
+	}
 	return or.simplify()
```
Comment (qw4990) [inline planner/core/rule_partition_processor.go:662]: How about moving this logic into `or.simplify()`?

**Review by qw4990 — APPROVED** [review]

File: planner/core/rule_partition_processor.go [hunk 2]
```diff
@@ -659,6 +659,10 @@ func (or partitionRangeOR) union(x partitionRangeOR) partitionRangeOR {
 }
 
 func (or partitionRangeOR) simplify() partitionRangeOR {
+	// if the length of the `or` is zero. We should return early.
```
Comment (wjhuang2016) [inline planner/core/rule_partition_processor.go:662]: If the length of the `or` is zero, is it expected?

Comment (zz-jason) [reply planner/core/rule_partition_processor.go:662]: could you add an example to illustrate in which scenario the length of `or` can be 0?

Comment (Reminiscent) [reply planner/core/rule_partition_processor.go:662]: It's expected. For example, we take the test case's conditions `where a > 10 or b is NULL` into consideration. 
1. `a > 10` will not generate the `partitionRange` in `partitionRangeOR`, because of the partition key `a` is less than 5.
2. `b is null` will not generate the `partitionRange` in `partitionRangeOR` too, because the column `b` is not the partition key. 
So the length of `or` is zero. @wjhuang2016 @zz-jason PTAL

Comment (wjhuang2016) [reply planner/core/rule_partition_processor.go:662]: Ok

Comment (zz-jason) [reply planner/core/rule_partition_processor.go:662]: Actually I mean to add it to the code comment :joy:
