### PR TITLE
range: wrongly skip the candidate in the extractBestCNFItemRanges

### LINKED ISSUE #62547: Only partial column is used for composite index scan under mixed single-column and multi-column conditions
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int, b int, c int, d int, index(a,b));
explain select * from t where  (a, b, c) in ((1, 1, 1), (2, 2, 2));
explain select * from t where  (a, b, c) in ((1, 1, 1), (2, 2, 2)) and d=1;
```

### 2. What did you expect to see? (Required)

The second query can use the two columns to build index range like the first query.

Rewrite as one multi-column condition:
```
mysql> explain select * from t where  (a, b, c, d) in ((1, 1, 1, 1), (2, 2, 2, 1));
+-------------------------------+---------+-----------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows | task      | access object          | operator info                                                                                                                                                            |
+-------------------------------+---------+-----------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_11                | 0.16    | root      |                        |                                                                                                                                                                          |
| ├─IndexRangeScan_8(Build)     | 0.20    | cop[tikv] | table:t, index:a(a, b) | range:[1 1,1 1], [2 2,2 2], keep order:false, stats:pseudo                                                                                                               |
| └─Selection_10(Probe)         | 0.16    | cop[tikv] |                        | or(and(and(eq(test.t.a, 1), eq(test.t.b, 1)), and(eq(test.t.c, 1), eq(test.t.d, 1))), and(and(eq(test.t.a, 2), eq(test.t.b, 2)), and(eq(test.t.c, 2), eq(test.t.d, 1)))) |
|   └─TableRowIDScan_9          | 0.20    | cop[tikv] | table:t                | keep order:false, stats:pseudo                                                                                                                                           |
+-------------------------------+---------+-----------+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> explain select * from t where  (a, b, c) in ((1, 1, 1), (2, 2, 2)) and d=1;
+-------------------------------+---------+-----------+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows | task      | access object          | operator info                                                                                                                                 |
+-------------------------------+---------+-----------+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_11                | 0.00    | root      |                        |                                                                                                                                               |
| ├─IndexRangeScan_8(Build)     | 20.00   | cop[tikv] | table:t, index:a(a, b) | range:[1,1], [2,2], keep order:false, stats:pseudo                                                                                            |
| └─Selection_10(Probe)         | 0.00    | cop[tikv] |                        | eq(test.t.d, 1), or(and(eq(test.t.a, 1), and(eq(test.t.b, 1), eq(test.t.c, 1))), and(eq(test.t.a, 2), and(eq(test.t.b, 2), eq(test.t.c, 2)))) |
|   └─TableRowIDScan_9          | 20.00   | cop[tikv] | table:t                | keep order:false, stats:pseudo                                                                                                                |
+-------------------------------+---------+-----------+------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

v7.1.2

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #62547 

Problem Summary:

### What changed and how does it work?

https://github.com/pingcap/tidb/blob/cbab9b225939870f52cd600bd828c627f64bee0c/pkg/util/ranger/detacher.go#L313-L353

image

The implementation here has an issue. If a remaining condition is found in `extractBestCNFItemRanges`, it will not be considered in the final range, which is incorrect.

for example 

```
create table t2 (a varchar(10), b varchar(10), c varchar(10), d varchar(10), index idx(a(2), b(2), c(2)));

select * from t2 where (a, b) in (('aaa', 'bbb'), ('ccc', 'ddd')) and c = 'eee';
```

Because his index is a very restrictive condition, selection filtering is needed to make good use of this index. At this time, this range must be retained instead of being excluded just because it also contains remaining conditions.

before this PR

```
+---------------------------+---------+-----------+------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| id                        | estRows | task      | access object                | operator info                                                                                                              |
+---------------------------+---------+-----------+------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_12            | 1.00    | root      |                              |                                                                                                                            |
| ├─IndexRangeScan_9(Build) | 20.00   | cop[tikv] | table:t2, index:idx(a, b, c) | range:["aa","aa"], ["cc","cc"], keep order:false, stats:pseudo                                                             |
| └─Selection_11(Probe)     | 1.00    | cop[tikv] |                              | eq(test.t2.c, "eee"), or(and(eq(test.t2.a, "aaa"), eq(test.t2.b, "bbb")), and(eq(test.t2.a, "ccc"), eq(test.t2.b, "ddd"))) |
|   └─TableRowIDScan_10     | 20.00   | cop[tikv] | table:t2                     | keep order:false, stats:pseudo                                                                                             |
+---------------------------+---------+-----------+------------------------------+----------------------------------------------------------------------------------------------------------------------------+
```

after this pr

```
+---------------------------+---------+-----------+------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| id                        | estRows | task      | access object                | operator info                                                                                                              |
+---------------------------+---------+-----------+------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_12            | 1.00    | root      |                              |                                                                                                                            |
| ├─IndexRangeScan_9(Build) | 1.25    | cop[tikv] | table:t2, index:idx(a, b, c) | range:["aa" "bb" "ee","aa" "bb" "ee"], ["cc" "dd" "ee","cc" "dd" "ee"], keep order:false, stats:pseudo                     |
| └─Selection_11(Probe)     | 1.00    | cop[tikv] |                              | eq(test.t2.c, "eee"), or(and(eq(test.t2.a, "aaa"), eq(test.t2.b, "bbb")), and(eq(test.t2.a, "ccc"), eq(test.t2.b, "ddd"))) |
|   └─TableRowIDScan_10     | 1.25    | cop[tikv] | table:t2                     | keep order:false, stats:pseudo                                                                                             |
+---------------------------+---------+-----------+------------------------------+----------------------------------------------------------------------------------------------------------------------------+
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/util/ranger/detacher.go [hunk 1]
```diff
@@ -338,13 +338,12 @@ func extractBestCNFItemRanges(sctx *rangerctx.RangerContext, conds []expression.
 		}
 		// take the union of the two columnValues
 		columnValues = unionColumnValues(columnValues, res.ColumnValues)
-		if len(res.AccessConds) == 0 || len(res.RemainedConds) > 0 {
+		if len(res.AccessConds) == 0 {
```
Comment (AilinKid) [inline pkg/util/ranger/detacher.go:341]: nice fix
how about add the comment here
// for a=1 or b =1 and c =1 of index(a,b), although we can only use first two of them as access conds.
		// we can also keep the range from (a=1 or b =1) into consecutive merge consideration.

Comment (hawkingrei) [reply pkg/util/ranger/detacher.go:341]: add the comment here.

**Comment by hawkingrei** [comment]
/hold

@guo-shaoge PTAL
