### PR TITLE
ddl notifier: allow another error in CI assert

### LINKED ISSUE #59501: flaky test on DDLNotifier
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/27040/pipeline

```
panic: assert failed, error processing events: session pool closed [recovered]

	panic: assert failed, error processing events: session pool closed



goroutine 132297 [running]:

github.com/pingcap/tidb/pkg/ddl/notifier.(*DDLNotifier).OnBecomeOwner.func1({0x8beb040, 0xc048a9e3f0})

	pkg/ddl/notifier/subscribe.go:338 +0x45

github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithRecover.func1.1()

	pkg/util/wait_group_wrapper.go:195 +0x43

panic({0x8beb040?, 0xc048a9e3f0?})

	GOROOT/src/runtime/panic.go:785 +0x132

github.com/pingcap/tidb/pkg/util/intest.doPanic(...)

	pkg/util/intest/assert.go:62

github.com/pingcap/tidb/pkg/util/intest.Assert(...)

	pkg/util/intest/assert.go:30

github.com/pingcap/tidb/pkg/ddl/notifier.(*DDLNotifier).start(0xc02fd50120)

	pkg/ddl/notifier/subscribe.go:164 +0x765

github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithRecover.func1()

	pkg/util/wait_group_wrapper.go:199 +0xa6

created by github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithRecover in goroutine 126710

	pkg/util/wait_group_wrapper.go:191 +0x125
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #59501

Problem Summary:

### What changed and how does it work?

seems when domain is closing, DDL notifier may not exit in time. So we tolerate some error

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [x] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/notifier/subscribe.go [hunk 1]
```diff
@@ -162,7 +162,9 @@ func (n *DDLNotifier) start() {
 		case <-ticker.C:
 			if err := n.processEvents(ctx); err != nil {
 				intest.Assert(
-					errors.ErrorEqual(err, context.Canceled) || strings.Contains(err.Error(), "mock handleTaskOnce error"),
+					errors.ErrorEqual(err, context.Canceled) ||
+						strings.Contains(err.Error(), "mock handleTaskOnce error") ||
+						strings.Contains(err.Error(), "session pool closed"),
```
Comment (Rustin170506) [inline pkg/ddl/notifier/subscribe.go:167]: Could you also update the one from the DDL handler?

**Review by Rustin170506 — COMMENTED** [review]
Thanks!

**Review by Rustin170506 — APPROVED** [review]
Thanks! :shipit:

**Review by wjhuang2016 — APPROVED** [review]
