### PR TITLE
planner: increase default tidb_stmt_summary_max_sql_length and better error

### LINKED ISSUE #63671: CREATE GLOBAL BINDING FROM HISTORY USING PLAN DIGEST fails on long queries
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Get the output from this shell script:
```bash
cols=28
#                  1         2         3         4         5        6
#        1234567890123456789012345678901234567890123456789012345678901234
tblname="long_table_name_just_fill_out_the_plan_and_sql_digest_text_fill"
colname="long_column_name_just_fill_out_the_plan_and_sql_digest_text"
echo "drop table if exists ${tblname};"
echo "create table ${tblname} (pk int primary key,"
for i in $(jot $cols)
do
	echo "${colname}_${i} varchar(255),"
done
echo "col_end int);"

echo "select pk,"
for i in $(jot $cols)
do
	echo "${colname}_${i},"
done
echo "col_end FROM ${tblname}"
echo "WHERE"

for i in $(jot $cols)
do
	echo "${colname}_${i} = 'filler${i}' AND"
done
echo "col_end = 'last cond';"
echo "select digest, digest_text, query_sample_text, plan_digest, plan, '' as History from information_schema.cluster_statements_summary where digest_text ilike 'select%${colname}%'"
echo "UNION ALL"
echo "select digest, digest_text, query_sample_text, plan_digest, plan, 'H' as History from information_schema.cluster_statements_summary_history where digest_text like 'select%${colname}%'\G"
```
Notice that the digest text will end with "...A(len:4120)" so it will truncate the text
Then try to create a binding from history by `CREATE GLOBAL BINDING FROM HISTORY USING PLAN DIGEST '34905d92850ad6e2f8a75c3402ec9157ad2d4582ac30e9e0ad5aa8d7ebbeceab'`

### 2. What did you expect to see? (Required)
Success

### 3. What did you see instead (Required)
Failure:
```
ERROR 1105 (HY000): binding failed: line 59 column 78 near "A(len:4120)" . Plan Digest: 34905d92850ad6e2f8a75c3402ec9157ad2d4582ac30e9e0ad5aa8d7ebbeceab
```

### 4. What is your TiDB version? (Required)
```
tidb_version(): Release Version: v9.0.0-beta.2.pre-528-g8f24f95670
Edition: Community
Git Commit Hash: 8f24f95670be0d8180647fad5b000394b88304be
Git Branch: master
UTC Build Time: 2025-09-22 13:58:15
GoVersion: go1.24.2
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Kernel Type: Classic
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #63671

Problem Summary:
For queries longer than 4096 characters, it will be truncated in the statements_summary tables, resulting in CREATE GLOBAL BINDING FROM HISTORY USING PLAN DIGEST '<digest>' does not work, and it gives a cryptic error from the parser.

### What changed and how does it work?
Increased the default from 4k to 32k and updated the error message, to point to `tidb_stmt_summary_max_sql_length` global system variable, controlling the length.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [x] Performance regression: Consumes more Memory
  > - Only if actually using such long queries.
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Changed default `tidb_stmt_summary_max_sql_length` from 4096 to 32768 to not truncate medium/large queries in the statements_summary tables.
```

### CODE REVIEW

**Comment by hawkingrei** [comment]
@mjonss Please fix the CI.

File: pkg/planner/core/planbuilder.go [hunk 1]
```diff
@@ -946,6 +947,14 @@ func constructSQLBindOPFromPlanDigest(
 	if query == "" {
 		return nil, errors.New("can't find any plans for '" + planDigest + "'")
 	}
+	// Check if the SQL is truncated (ends with "(len:<num>)" pattern)
+	if query[len(query)-1] == ')' {
+		match, err2 := regexp.MatchString(`\(len:\d+\)$`, query)
+		if match || err2 != nil {
+			return nil, errors.NewNoStackErrorf("binding failed: SQL query is truncated due to tidb_stmt_summary_max_sql_length limit. "+
+				"Please increase tidb_stmt_summary_max_sql_length. Plan Digest: %v", planDigest)
```
Comment (henrybw) [inline pkg/planner/core/planbuilder.go:955]: I would consider using the `vardef.TiDBStmtSummaryMaxSQLLength` constant instead of hardcoding `tidb_stmt_summary_max_sql_length` in the error message, but I don't consider it a blocking issue.

**Review by wddevries — APPROVED** [review]

**Review by terry1purcell — APPROVED** [review]

**Review by yudongusa — COMMENTED** [review]
Please also open a document PR
