### PR TITLE
pkg/util/schemacmp: allow utf8/latin1 < utf8mb4 charset/collation join

### LINKED ISSUE #67777: pkg/util/schemacmp: allow joining utf8/latin1 with utf8mb4
## Enhancement

`pkg/util/schemacmp` currently treats column/table `charset` and `collation` as strict singletons. This makes schema comparison/join fail when one side uses `utf8` (or `latin1`) while the other side is `utf8mb4` (often the default), even though `utf8/latin1 -> utf8mb4` is a safe and common upgrade path.

Expected behavior: allow `utf8 (utf8mb3) < utf8mb4` and `latin1 < utf8mb4` for both charset and collation (same suffix for collations), so the join can pick `utf8mb4`.

This reduces false incompatibility errors during schema comparison/join.

ref https://github.com/pingcap/tiflow/issues/11696

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #67777

Problem Summary:

`pkg/util/schemacmp` previously treated `charset` / `collation` as strict singletons, which makes schema compare/join fail for common upgrade paths like `utf8 (utf8mb3) -> utf8mb4` or `latin1 -> utf8mb4`.

### What changed and how does it work?

- Add `Charset` and `Collation` lattices with ordering:
  - `utf8 (utf8mb3) < utf8mb4`
  - `latin1 < utf8mb4`
  - for collations, only allow joining when the suffix matches (e.g. `utf8_bin < utf8mb4_bin`).
- Use them when encoding `types.FieldType` and `model.TableInfo` in `pkg/util/schemacmp`.
- Extend unit tests to cover the new join behavior.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **New Features**
  * Schema comparison now normalizes charsets and collations, with explicit compatibility rules and deterministic join results across compatible families.

* **Bug Fixes**
  * Restoration and encoding now consistently derive and emit CHARSET/COLLATE from stored collation, improving correctness for mixed charset/collation schemas.
  * New, clearer incompatibility errors for charset vs collation mismatch cases.

* **Tests**
  * Added comprehensive tests for normalization, comparison ordering, join outcomes, and error messages.

### CODE REVIEW

**Comment by kennytm** [comment]
(legit failure in `idc-jenkins-ci-tidb/build`)

File: pkg/util/schemacmp/charset_collation.go [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+func (a charsetLattice) Compare(other Lattice) (int, error) {
+	b, ok := other.(charsetLattice)
+	if !ok {
+		return 0, typeMismatchError(a, other)
+	}
+
+	if a.family == b.family {
+		if a.family == charsetFamilyOther && a.value != b.value {
+			return 0, incompatibleCharsetError(a.value, b.value)
+		}
```
[the remark this answers is not in the document]
Comment (lance6716) [reply pkg/util/schemacmp/charset_collation.go]: Maybe I can save ToLower result to the `value` field 🤔

File: pkg/util/schemacmp/charset_collation.go [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+	charsetFamilyUTF8MB4
+)
+
+// Charset is a lattice for comparing/joining character sets. Currently it
+// supports the ordering: latin1 < utf8mb4 and utf8(utf8mb3) < utf8mb4. Other
+// charsets are only comparable when identical.
+func Charset(cs string) Lattice {
+	ret := charsetLattice{value: cs}
+
+	normalized := strings.ToLower(cs)
```
Comment (kennytm) [inline pkg/util/schemacmp/charset_collation.go:31]: I think you can do the normalization (ToLower and utf8mb3→utf8), but there's no need to cache the family calculation into the `Charset`. 

Basically,

```go
type charsetLattice struct { value string }
```

and directly compare by strings

```go
func (a charsetLattice) Compare(other Lattice) (int, error) {
    ...
    switch {
    case a.value == b.value:
        return 0, nil
    // this must be compatible with checkModifyCharsetAndCollation().
    case a.value == tidbcharset.CharsetUTF8MB4 && (b.value == tidbcharset.CharsetUTF8 || b.value == tidbcharset.CharsetLatin1):
        return 1, nil
    case b.value == tidbcharset.CharsetUTF8MB4 && (a.value == tidbcharset.CharsetUTF8 || a.value == tidbcharset.CharsetLatin1):
        return -1, nil
    default:
		return 0, incompatibleCharsetError(a.value, b.value) 
}
```

File: pkg/util/schemacmp/charset_collation.go [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+	}
+	return b, nil
+}
+
+type collationLattice struct {
+	value string
+	// suffix will be set to normalized value when family is collationFamilyOther for
+	// implementation simplicity.
+	suffix string
+	family collationFamily
```
Comment (kennytm) [inline pkg/util/schemacmp/charset_collation.go]: ditto this should be 

```go
type collationLattice struct {
    charset charsetLattice
    suffix  string
}
```

File: pkg/util/schemacmp/table.go [hunk 4]
```diff
@@ -271,8 +271,8 @@ func encodeTableInfoToLattice(ti *model.TableInfo) Tuple {
 	}
 
 	return Tuple{
-		Singleton(ti.Charset),
-		Singleton(ti.Collate),
+		Charset(ti.Charset),
+		Collation(ti.Collate),
```
Comment (kennytm) [inline pkg/util/schemacmp/table.go:273]: since the collation *contained* the charset i think we can remove the charset from the tuple.

File: pkg/util/schemacmp/type.go [hunk 5]
```diff
@@ -86,8 +86,8 @@ func encodeFieldTypeToLattice(ft *types.FieldType) Tuple {
 		Byte(encodeAntiKeys(ft.GetFlag())),
 		defVal,
 
-		Singleton(ft.GetCharset()),
-		Singleton(ft.GetCollate()),
+		Charset(ft.GetCharset()),
+		Collation(ft.GetCollate()),
```
Comment (kennytm) [inline pkg/util/schemacmp/type.go:88]: ditto

File: pkg/util/schemacmp/charset_collation.go (hunk 2 above)
Comment (lance6716) [reply pkg/util/schemacmp/charset_collation.go:31]: The original input is only kept for error message, to avoid confusing the user (maybe the user don't know utf8 is utf8mb3?). OK now I also think not worth it 😂

Comment (kennytm) [reply pkg/util/schemacmp/charset_collation.go:31]: TiDB already does normalization elsewhere. I don't think a user will be confused by `utf8 == utf8mb3` if they already know what is `utf8mb3`.

```sql
mysql> create table a (a varchar(99) charset utf8mb3, b varchar(99) charset utf8);
Query OK, 0 rows affected (0.04 sec)

mysql> show create table a;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                          |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| a     | CREATE TABLE `a` (
  `a` varchar(99) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `b` varchar(99) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

File: pkg/util/schemacmp/charset_collation.go [hunk 6]
```diff
@@ -0,0 +1,145 @@
...
+	}
+
+	cmp, err := a.Compare(b)
+	if err != nil {
+		return nil, err
+	}
+	if cmp >= 0 {
+		return a, nil
+	}
+	return b, nil
```
[the remark this answers is not in the document]
Comment (lance6716) [reply pkg/util/schemacmp/charset_collation.go]: Oh, very complicated 😂 not sure we should support it

File: pkg/util/schemacmp/charset_collation.go [hunk 7]
```diff
@@ -0,0 +1,145 @@
...
+//
+// (same suffix only).
+//
+// Other collations are only comparable when identical.
+func Collation(co string) collationLattice {
+	normalized := strings.ToLower(co)
+
+	charsetName, suffix, _ := strings.Cut(normalized, "_")
+
+	return collationLattice{charset: Charset(charsetName), suffix: suffix}
```
Comment (kennytm) [inline pkg/util/schemacmp/charset_collation.go]: to avoid double `ToLower`ing you could write this as

```go
charsetName, suffix, _ := strings.Cut(normalized, "_")
return collationLattice{
    charset: Charset(charsetName), 
    suffix: strings.ToLower(suffix),
}
```

File: pkg/util/schemacmp/charset_collation_test.go [hunk 8]
```diff
@@ -0,0 +1,87 @@
...
+	require.Equal(t, 1, cmp)
+
+	_, err = Charset("other1").Compare(Charset("other2"))
+	require.ErrorContains(t, err, "incompatible mysql charset (other1 vs other2)")
+
+	_, err = Charset("other1").Compare(Charset("utf8"))
+	require.ErrorContains(t, err, "incompatible mysql charset (other1 vs utf8)")
+}
+
+func TestCollationCompare(t *testing.T) {
```
Comment (kennytm) [inline pkg/util/schemacmp/charset_collation_test.go:52]: include a test case for the `binary` collation (handle the valid path where `suffix == ""`)

File: pkg/util/schemacmp/lattice.go [hunk 9]
```diff
@@ -36,6 +36,10 @@ const (
 	ErrMsgDistinctSingletons = "distinct singletons (%v vs %v)"
 	// ErrMsgIncompatibleType is the error message for incompatible type.
 	ErrMsgIncompatibleType = "incompatible mysql type (%v vs %v)"
+	// ErrMsgIncompatibleCharset is the error message for incompatible charset.
+	ErrMsgIncompatibleCharset = "incompatible mysql charset (%v vs %v)"
+	// ErrMsgIncompatibleCollation is the error message for incompatible collation.
+	ErrMsgIncompatibleCollation = "incompatible mysql collation (%v vs %v)"
```
Comment (kennytm) [inline pkg/util/schemacmp/lattice.go]:
```suggestion
	// ErrMsgIncompatibleCharset is the error message for incompatible charset.
	ErrMsgIncompatibleCharset = "incompatible charset (%v vs %v)"
	// ErrMsgIncompatibleCollation is the error message for incompatible collation.
	ErrMsgIncompatibleCollation = "incompatible collation (%v vs %v)"
```
"charset" and "collation" are unambiguous even without the "mysql" adjective, unlike the "mysql type" above.

File: pkg/util/schemacmp/table.go [hunk 10]
```diff
@@ -270,9 +270,18 @@ func encodeTableInfoToLattice(ti *model.TableInfo) Tuple {
...
 
+	collate := ti.Collate
+	if collate == "" && ti.Charset != "" {
+		if defaultCollate, err := pcharset.GetDefaultCollation(ti.Charset); err == nil {
+			collate = defaultCollate
+		} else {
+			// Fall back to charset-only if the default collation isn't known.
+			collate = ti.Charset
+		}
+	}
```
Comment (kennytm) [inline pkg/util/schemacmp/table.go]: do have have any TableInfo which `collate == "" && charset != ""` ?

File: pkg/util/schemacmp/table.go [hunk 11]
```diff
@@ -324,13 +333,15 @@ func restoreTableInfoFromUnwrapped(ctx *format.RestoreCtx, table []any, tableNam
...
-		ctx.WriteKeyWord(charset)
-	}
-	if collate := table[tableInfoTupleIndexCollate].(string); collate != "" {
-		ctx.WriteKeyWord(" COLLATE ")
-		ctx.WriteKeyWord(collate)
+		ctx.WriteKeyWord(cs)
+		if hasSuffix {
+			ctx.WriteKeyWord(" COLLATE ")
+			ctx.WriteKeyWord(collate)
+		}
```
Comment (kennytm) [inline pkg/util/schemacmp/table.go]: ditto

File: pkg/util/schemacmp/charset_collation.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (lance6716) [reply pkg/util/schemacmp/charset_collation.go]: @kennytm Should I follow this comment? Which means `utf8 JOIN latin1 = utf8mb4`. I think it's reasonable.

[the remark this answers is not in the document]
Comment (kennytm) [reply pkg/util/schemacmp/charset_collation.go]: @lance6716 I think it is fine. The implication is that though, if we have 2 shards and the user goes

```sql
alter table t1 add column c text collate latin1_bin;
alter table t2 add column c text collate utf8mb3_bin;
```
it will end up in downstream TiDB as (if i remembered what optimistic sharding works correctly):
```sql
alter table t add column c text collate latin1_bin;
alter table t modify column c text collate utf8mb4_bin; # ← result of join
```

File: pkg/util/schemacmp/table.go (hunk 10 above)
Comment (lance6716) [reply pkg/util/schemacmp/table.go]: I guess you mean this branch is not run at all? https://github.com/pingcap/tidb/pull/67778/commits/d505f247aa73efdb3bcba5aa5c75141a34eabf59

I have a simple check by looking for DM's call sites. DM will build the TableInfo with `BuildTableInfoFromAST(metabuild.NewContext(), stmt)`, yes it's not run.

BTW I think it should be `BuildTableInfoFromAST(metabuild.NewNonStrictContext(), stmt)`. Will reproduce and open an issue later

File: pkg/util/schemacmp/charset_collation.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (lance6716) [reply pkg/util/schemacmp/charset_collation.go]: My coding agent pushed a commit https://github.com/pingcap/tidb/pull/67778/changes/67b337bf40e8d9ad0333b49186fcffae6d5cdf4d for this comment but I haven't reviewed it 😂  I'll do a self review first

File: pkg/util/schemacmp/table.go (hunk 10 above)
Comment (kennytm) [reply pkg/util/schemacmp/table.go]: yeah afaik the charset & collation are always populated, even for like INT fields, so the defensive empty-string checks are probably not needed.

**Comment by lance6716** [comment]
I have reviewed AI's code. PTAL @kennytm @GMHDBJD

File: pkg/util/schemacmp/table.go [hunk 12]
```diff
@@ -324,14 +322,15 @@ func restoreTableInfoFromUnwrapped(ctx *format.RestoreCtx, table []any, tableNam
...
-		ctx.WriteKeyWord(collate)
-	}
+
+	collate := table[tableInfoTupleIndexCollate].(string)
+	// MySQL's collation name is "<charset>_<suffix>" or "binary".
+	cs, _, _ := strings.Cut(collate, "_")
+	ctx.WriteKeyWord(" CHARSET ")
+	ctx.WriteKeyWord(cs)
+	ctx.WriteKeyWord(" COLLATE ")
+	ctx.WriteKeyWord(collate)
```
Comment (GMHDBJD) [inline pkg/util/schemacmp/table.go]: Will tblInfo.Charset = "" or tblInfo.Collate = ""?

Comment (kennytm) [reply pkg/util/schemacmp/table.go]: afaik the `Charset`/`Collate` are always filled in. even if they are `""`, because "Restore is for debug use only" it shouldn't affect any significant process

**Comment by lance6716** [comment]
@pantheon-ai PTAL

**Comment by lance6716** [comment]
ping @GMHDBJD @kennytm

**Review by GMHDBJD — APPROVED** [review]

File: pkg/util/schemacmp/charset_collation.go [hunk 13]
```diff
@@ -0,0 +1,160 @@
...
+
+	if a.suffix != b.suffix {
+		return 0, incompatibleCollationError(a.unwrapString(), b.unwrapString())
+	}
+
+	cmp, err := a.charset.Compare(b.charset)
+	if err != nil {
+		return 0, err
+	}
+	return cmp, nil
```
Comment (kennytm) [inline pkg/util/schemacmp/charset_collation.go]:
```suggestion
	return a.charset.Compare(b.charset)
```

File: pkg/util/schemacmp/table.go (hunk 12 above)
Comment (kennytm) [inline pkg/util/schemacmp/table.go]:
```suggestion
	ctx.WriteKeyWord(" COLLATE ")
	ctx.WritePlain(collate)
```

collation already implied the charset. also the rest of this repository mostly used `WritePlain` for the collation name

**Review by kennytm — COMMENTED** [review]
rest lgtm

**Review by kennytm — APPROVED** [review]
