### PR TITLE
expression, executor: fix duration column <cmp> constant(#3884)

### LINKED ISSUE #3884: compare result is wrong for `string <cmp> duration`
1. What did you do?

```
DROP TABLE IF EXISTS t;
CREATE TABLE t (
c1 date,
c2 datetime,
c3 timestamp,
c4 time,
c5 year
);
INSERT INTO t values ("2000-01-01", "2000-01-01 12:12:12", "2000-01-01 12:12:12", "12:12:12", "2000");
INSERT INTO t values ("2000-02-01", "2000-02-01 12:12:12", "2000-02-01 12:12:12", "13:12:12", 2000);
INSERT INTO t values ("2000-03-01", "2000-03-01", "2000-03-01 12:12:12", "1 12:12:12", 2000);
INSERT INTO t SET c1 = "2000-04-01", c2 = "2000-04-01", c3 = "2000-04-01 12:12:12", c4 = "-1 13:12:12", c5 = 2000;
SELECT c4 FROM t where c4 < "-13:12:12";
```

2. What did you expect to see?

-37:12:12

3. What did you see instead?

empty result

4. What version of TiDB are you using (`tidb-server -V`)?

### PR DESCRIPTION
**Pull request by XuHuaiyu**
fix #3884 
PTAL @hanfei1991 @lamxTyler @zz-jason

### CODE REVIEW

File: expression/builtin_compare.go [hunk 1]
```diff
@@ -319,13 +319,21 @@ func (c *compareFunctionClass) getFunction(args []Expression, ctx context.Contex
 		} else if isTemporalColumn(args[0]) && isConst1 ||
 			isTemporalColumn(args[1]) && isConst0 {
 			/*
-				<time column> <cmp> <non-time constant>
+				<temporal column> <cmp> <non-temporal constant>
 				or
-				<non-time constant> <cmp> <time column>
+				<non-temporal constant> <cmp> <temporal column>
 
 				Convert the constant to time type.
```
Comment (lamxTyler) [inline expression/builtin_compare.go]: Does this also need to be updated?

**Comment by XuHuaiyu** [comment]
PTAL @lamxTyler

**Comment by lamxTyler** [comment]
LGTM
