### PR TITLE
expression: fix comparing json with string

### LINKED ISSUE #11883: unexpect invalid json text error when query with `json_extract`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table t1(f1 json);
insert into t1(f1) values ('"asd"'),('"asdf"'),('"asasas"');
select f1 from t1 where json_extract(f1,"$") in ("asd","asasas","asdf");
```

2. What did you expect to see?

image

3. What did you see instead?

image

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

image

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @XuHuaiyu

### LINKED ISSUE #13710: Incompatible issue related to JSON functions
## Bug Report

Seems there's an incompatible issue related to JSON functions

1. What did you do?
```
select json_extract("\"asd\"","$") in ("asd","abcd");
```

2. What did you expect to see?

in MySQL:5.7
```
mysql> select json_extract("\"asd\"","$") in ("asd","abcd");
+----------------------------------------------+
| json_extract("\"asd\"","$") in ("asd","abc") |
+----------------------------------------------+
|                                            0 |
+----------------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

in MySQL:8
```
mysql> select json_extract("\"asd\"","$") in ("asd","abcd");
+-----------------------------------------------+
| json_extract("\"asd\"","$") in ("asd","abcd") |
+-----------------------------------------------+
|                                             1 |
+-----------------------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
MySQL [(none)]> select json_extract("\"asd\"","$") in ("asd","abcd");
ERROR 3140 (22032): Invalid JSON text: The document root must not be followed by other values.
MySQL [(none)]>
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v4.0.0-alpha-940-g92e774913
Git Commit Hash: 92e774913a2f6166b104d3d8eaed5513733f1830
Git Branch: master
UTC Build Time: 2019-11-24 03:10:38
GoVersion: go version go1.13.1 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by ichn-hu**
### What problem does this PR solve?

Issue Number: close #11883 , also close #13710

Problem Summary:

### What is changed and how it works?

What's Changed: remove Parse json tag

How it Works:

MySQL won't implicitly cast string to JSON during comparison.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
Side effects

### Release note 

- No release note.

### CODE REVIEW

File: expression/builtin_other.go [hunk 1]
```diff
@@ -145,6 +145,17 @@ func (c *inFunctionClass) getFunction(ctx sessionctx.Context, args []Expression)
 		sig.setPbCode(tipb.ScalarFuncSig_InDuration)
 	case types.ETJson:
 		sig = &builtinInJSONSig{baseBuiltinFunc: bf}
+		for i := range bf.args {
+			arg := bf.args[i]
+			// if we need to implicitly cast string to JSON, we only make it a string literal in JSON, instead of parsing it.
+			switch arg.(type) {
+			case *ScalarFunction:
+				f := arg.(*ScalarFunction).Function
```
Comment (XuHuaiyu) [inline expression/builtin_other.go:153]: Can we do this in `WrapWithCastAsJSON`?

Comment (ichn-hu) [reply expression/builtin_other.go:153]: Seems not, it might break things like insert string as json, which needs to parse the string.

Comment (XuHuaiyu) [reply expression/builtin_other.go:153]: It seems that `insert` will not invoke the `WrapCastAsxx` funcs.

Comment (ichn-hu) [reply expression/builtin_other.go:153]: Actually in https://github.com/pingcap/tidb/pull/21903/commits/aafc91327bc7720e13a5d4cbb1b40ae5e709f3e7 the first version, I did this at WrapCastAsJSON, but it breaks the test.

Comment (ichn-hu) [reply expression/builtin_other.go:153]: Okay, after a more careful research, the failed test is not because of `insert`, it is because the function `json_type` will parse the string, which used `WrapCastAsJSON` to cast string to JSON.

Comment (ichn-hu) [reply expression/builtin_other.go:153]: I think "not parse json string" is a special case for comparing json with other data types, therefore the current change is appropriate.

Comment (ichn-hu) [reply expression/builtin_other.go:153]: other json functions require parsing:

* json_valid
* json_type
* JSON_LENGTH
* JSON_DEPTH
* JSON_KEYS
so on so forth, most of json functions require parsing json.

**Comment by ichn-hu** [comment]
@XuHuaiyu @lzmhhh123 PTAL

File: expression/builtin_other.go [hunk 2]
```diff
@@ -145,6 +145,17 @@ func (c *inFunctionClass) getFunction(ctx sessionctx.Context, args []Expression)
 		sig.setPbCode(tipb.ScalarFuncSig_InDuration)
 	case types.ETJson:
 		sig = &builtinInJSONSig{baseBuiltinFunc: bf}
+		for i := range bf.args {
```
Comment (lzmhhh123) [inline expression/builtin_other.go:148]: Need `constructBinaryOpFunction` change too?

File: executor/executor_test.go [hunk 3]
```diff
@@ -7228,6 +7228,18 @@ func (s *testSuite) Test12178(c *C) {
 	tk.MustQuery("select * from ta").Check(testkit.Rows("1234567890123456789012345678901234567890123456789012345.00"))
 }
 
+func (s *testSuite) Test11883(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t1")
+	tk.MustExec("create table t1 (f1 json)")
+	tk.MustExec("insert into t1(f1) values ('\"asd\"'),('\"asdf\"'),('\"asasas\"')")
+	tk.MustQuery("select f1 from t1 where json_extract(f1,\"$\") in (\"asd\",\"asasas\",\"asdf\")").Check(testkit.Rows("\"asd\"", "\"asdf\"", "\"asasas\""))
```
Comment (lzmhhh123) [inline executor/executor_test.go:7237]: Please also add some compare function tests like:

```sql
json_extract(f1,"$") = "asd"
case json_extract(f1,"$") = "asd" when ...
json_extract(f1,"$") <=> "asd"
```

File: expression/builtin_other.go (hunk 2 above)
Comment (ichn-hu) [reply expression/builtin_other.go:148]: Seems not, because it is already fixed by #8564

**Comment by ichn-hu** [comment]
@XuHuaiyu @lzmhhh123 PTAL

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
