### PR TITLE
fix(runaway): prevent marking quarantine when settings expired

### LINKED ISSUE #61834: Expired WATCH resource group settings should no longer take effect
### 1. Minimal reproduce step (Required)

Let's assume at T1 we have a resource group `rg1` with `QUERY_LIMIT` like:

```sql
ALTER RESOURCE GROUP rg1 QUERY_LIMIT=(EXEC_ELAPSED='60s', ACTION=KILL, WATCH=SIMILAR DURATION='10m');
```

We change this resource group at T2 to:

```sql
ALTER RESOURCE GROUP rg1 QUERY_LIMIT=(RU = 1000, ACTION=SWITCH_GROUP(default), WATCH=SIMILAR DURATION='10m');
```

Then, a SQL query that starts between T1 and T2 reaches its previous `EXEC_ELAPSED` threshold at T3, triggering a watch rule that uses the expired `QUERY_LIMIT` settings to be added.

### 2. What did you expect to see? (Required)

Once the `QUERY_LIMIT` settings are changed after T2, the old watch rule should not take effect any more.

### 3. What did you see instead (Required)

After T3, both types of rules will be triggered within a maximum of 10 minutes.

### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/commit/56ba961c7076da1677e1f471356e4651dca3051e

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: close #61834

### What changed and how does it work?

Introduced a check to ensure that quarantine marking only proceeds if the current resource group settings match the existing settings.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

Slow SQL will be killed after 10s:

image

Before:

image

After:

image

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue where expired `WATCH` rule still take effect after the `QUERY_LIMIT` setting is modified.
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: pkg/resourcegroup/runaway/checker.go [hunk 1]
```diff
@@ -262,6 +263,11 @@ func (r *Checker) markQuarantine(now *time.Time, exceedCause string) {
 	if r.settings == nil || r.settings.Watch == nil {
 		return
 	}
+	// If the latest group settings have been changed, do not mark quarantine.
+	group, err := r.manager.ResourceGroupCtl.GetResourceGroup(r.resourceGroupName)
+	if err != nil || group == nil || !proto.Equal(r.settings, group.RunawaySettings) {
+		return
```
Comment (okJiang) [inline pkg/resourcegroup/runaway/checker.go:269]: How about printing some logs here?

Comment (JmPotato) [reply pkg/resourcegroup/runaway/checker.go:269]: I'm concerned that adding a log here could become overwhelming if many SQL queries meet this condition during high QPS. A metrics-based approach might be more suitable. However, the current implementation lacks sufficient observability, which we can address as an enhancement after merging this PR.
