### PR TITLE
ddl: fix float precision larger than 53

### LINKED ISSUE #20447: float precision should not larger than 53
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```sql
create table t1(a float(54));
```

### 2. What did you expect to see? (Required)
```sql
mysql > create table t1(a float(54));
(1063, "Incorrect column specifier for column 'a'")
```

### 3. What did you see instead (Required)
```sql
mysql test> create table t1(a float(54));
Query OK, 0 rows affected
Time: 0.153s
mysql test> show create table t1;
+-------+------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                               |
+-------+------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (\n  `a` float DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------+

```
### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
 tidb_version()                                                                                                                                                                                                                                                                                                             |
+-----------+
| Release Version: v4.0.7
Edition: Community
Git Commit Hash: ed939f3f11599b5a38352c5c160c917df3ebf3eb
Git Branch: heads/refs/tags/v4.0.7
UTC Build Time: 2020-09-29 06:56:48
GoVersion: go1.13\nRace Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 

```

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve?

Issue Number: close #20447 

Problem Summary:

### What is changed and how it works?

What's Changed:
check `mysql.MaxDoublePrecisionLength`

How it Works:

### Check List 

Tests 

- Unit test

### Release note 

- fix float precision larger than 53

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
PTAL @wjhuang2016 @zimulala

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -819,11 +819,17 @@ func checkColumn(colDef *ast.ColumnDef) error {
 			return err
 		}
 	case mysql.TypeFloat, mysql.TypeDouble:
-		if tp.Decimal > mysql.MaxFloatingTypeScale {
-			return types.ErrTooBigScale.GenWithStackByArgs(tp.Decimal, colDef.Name.Name.O, mysql.MaxFloatingTypeScale)
-		}
-		if tp.Flen > mysql.MaxFloatingTypeWidth {
-			return types.ErrTooBigPrecision.GenWithStackByArgs(tp.Flen, colDef.Name.Name.O, mysql.MaxFloatingTypeWidth)
+		if tp.Decimal == -1 {
```
Comment (wjhuang2016) [inline planner/core/preprocess.go:822]: Any information about this logic? such as MySQL's document.

Comment (b41sh) [reply planner/core/preprocess.go:824]: The document is [here](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html), but its description is not detailed enough.
Use MySQL to test, we can find such constraints:

FLOAT(p) allows p from 0 to 53.
DOUBLE(p) is not allowed.
FLOAT(M,D) and DOUBLE(M,D) allows M from 0 to 255 and D from 0 to 30.

image
PTAL @qw4990  @wjhuang2016

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by wjhuang2016** [comment]
@AilinKid @djshow832 PTAL

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by AilinKid** [comment]
hi~ could you pls resolve the conflicts above?

**Review by AilinKid — DISMISSED** [review]

**Review by AilinKid — DISMISSED** [review]
LGTM

**Comment by AilinKid** [comment]
@b41sh  can you please resolve the conflicts for a while, this pr is ready to merge now~

**Comment by b41sh** [comment]
> @b41sh can you please resolve the conflicts for a while, this pr is ready to merge now~

conflicts have fixed, PTAL @AilinKid

**Review by AilinKid — APPROVED** [review]
LGTM
