### PR TITLE
server: try to use latest infoschema if failed to get snapshot infoschema in historical stats HTTP API

### LINKED ISSUE #44648: can't download historical stats of the time before GC safe point through HTTP API even the historical stats exist
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a table, insert data, and analyze it several times
2. wait for 10min+
3. start a new tidb to join the cluster
4. on the new tidb, try to use HTTP API (`http://{TiDBIP}:10080/stats/dump/{db}/{table}/{yyyyMMddHHmmss}`) to download the stats with the time right after the first analyze.

### 2. What did you expect to see? (Required)

Successfully download the stats of the first analyze.

### 3. What did you see instead (Required)

```
[tikv:9006]GC life time is shorter than transaction duration, transaction starts at xxx, GC safe point is xxx
```
### 4. What is your TiDB version? (Required)

7.1, master

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #44648

Problem Summary:

Please see the issue.

### What is changed and how it works?

As the title says

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Since it's not easy to mock such a scenario in UT. I choose to test it manually.
Tested as specified in the issue.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: server/statistics_handler.go [hunk 1]
```diff
@@ -128,21 +131,30 @@ func (sh StatsHistoryHandler) ServeHTTP(w http.ResponseWriter, req *http.Request
 		return
 	}
 	snapshot := oracle.GoTimeToTS(t1)
-	is, err := sh.do.GetSnapshotInfoSchema(snapshot)
+	tbl, err := getSnapshotTableInfo(sh.do, snapshot, params[pDBName], params[pTableName])
 	if err != nil {
-		writeError(w, err)
-		return
+		logutil.BgLogger().Info("fail to get snapshot TableInfo in historical stats API, switch to use latest infoschema", zap.Error(err))
```
Comment (AilinKid) [inline server/statistics_handler.go:136]: better to clarify this in the doc？

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

File: server/statistics_handler.go (hunk 1 above)
Comment (time-and-fate) [reply server/statistics_handler.go:136]: Currently, the historical stats lack docs. This PR aims to make historical stats at least usable as soon as possible since it's already been enabled now.
The behavior changed here is a bit too detailed for the user. I think we can clarify this when we add doc for the historical stats.

**Review by AilinKid — APPROVED** [review]
