### PR TITLE
planner: ONLY_FULL_GROUP_BY sql_mode was not working with VIEWs

### LINKED ISSUE #53175: SQL_MODE not considered for VIEWs
## Bug Report

Please answer these questions before submitting your issue. Thanks!

SQL_MODE is not used properly in views, like ONLY_FULL_GROUP_BY is not in effect.

See test case, where no warning is given for TiDB, while it is given for MySQL.

### 1. Minimal reproduce step (Required)

```mysql
create table t (a int);
set @@sql_mode = default;
create view v as select * from t group by null;
select * from v;
set @@sql_mode = '';
select * from v;
```

### 2. What did you expect to see? (Required)
```mysql
mysql> create table t (a int);
Query OK, 0 rows affected (0,02 sec)

mysql> set @@sql_mode = default;
Query OK, 0 rows affected (0,00 sec)

mysql> create view v as select * from t group by null;
Query OK, 0 rows affected (0,00 sec)

mysql> select * from v;
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test.t.a' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
mysql> set @@sql_mode = '';
Query OK, 0 rows affected (0,00 sec)

mysql> select * from v;
Empty set (0,00 sec)
```
### 3. What did you see instead (Required)
```mysql
tidb> create table t (a int);
Query OK, 0 rows affected (0.08 sec)

tidb> set @@sql_mode = default;
Query OK, 0 rows affected (0.00 sec)

tidb> create view v as select * from t group by null;
Query OK, 0 rows affected (0.10 sec)

tidb> select * from v;
Empty set (0.00 sec)

tidb> set @@sql_mode = '';
Query OK, 0 rows affected (0.01 sec)

tidb> select * from v;
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v8.0.0
Edition: Community
Git Commit Hash: 8ba1fa452b1ccdbfb85879ea94b9254aabba2916
Git Branch: HEAD
UTC Build Time: 2024-03-28 14:22:34
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: close #53175

Problem Summary:
Since the underlying table was not preprocessed, it was not found during the check for full group by.

### What changed and how does it work?
If the table was not found in the cache, retrieve it through the information schema.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
ONLY_FULL_GROUP_BY sql_mode was not working with VIEWs.
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

File: pkg/planner/core/issuetest/planner_issue_test.go [hunk 1]
```diff
@@ -119,3 +119,18 @@ func TestIssue54535(t *testing.T) {
 	tk.MustQuery("select /*+ inl_join(tmp) */ * from t1 inner join (select col_1, group_concat(col_2) from t2 group by col_1) tmp on t1.col_1 = tmp.col_1;").Check(testkit.Rows())
 	tk.MustQuery("select /*+ inl_join(tmp) */ * from t1 inner join (select col_1, group_concat(distinct col_2 order by col_2) from t2 group by col_1) tmp on t1.col_1 = tmp.col_1;").Check(testkit.Rows())
 }
+
+func TestIssue53175(t *testing.T) {
```
Comment (bb7133) [inline pkg/planner/core/issuetest/planner_issue_test.go:123]: Could you please try to move this test to 'tests/integrationtest'?
