### PR TITLE
*: fix a bug when aggregate function meet subquery.

### LINKED ISSUE #2428: The planner will report an error when a subquery and aggregation functions appear in select fields.
mysql> create table abc(id int, a int, name varchar(10));
Query OK, 0 rows affected (0.00 sec)

mysql> select aa.name, avg(aa.a) as c,(select count(*) from abc cc where aa.id = cc.id) from abc aa;
ERROR 1105 (HY000): Unknown column  aa id.

mysql> select (select count(*) from abc cc where aa.id = cc.id) from abc aa;
Empty set (0.00 sec)

### PR DESCRIPTION
**Pull request by hanfei1991**
fix #2428 
We won't add first_row for ast any more, we use the same schema columns for col and first_row(col) to solve it.
@shenli @coocood @zimulala @winoros @XuHuaiyu PTAL

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

File: ast/functions_test.go [hunk 1]
```diff
@@ -1,84 +0,0 @@
...
-	. "github.com/pingcap/check"
-	"github.com/pingcap/tidb/model"
-)
-
-var _ = Suite(&testFunctionsSuite{})
-
-type testFunctionsSuite struct {
-}
-
-func (ts *testFunctionsSuite) TestAggregateFuncExtractor(c *C) {
```
Comment (shenli) [inline ast/functions_test.go]: Should we move this to the plan package?

Comment (hanfei1991) [inline ast/functions_test.go]: No longer, we remove the FirstRow logic and extractor is quite simple now. I think we can abandon it in future.
