### PR TITLE
lightning, ddl: set TS to engineMeta after ResetEngineSkipAllocTS 

### LINKED ISSUE #57980: non-DXF ADD INDEX of large table (trigger import due to disk quota) will write KV with TS = 0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use this diff to trigger disk quota import on small tables

```diff
diff --git a/pkg/ddl/ingest/backend.go b/pkg/ddl/ingest/backend.go
index f11849f70b..cd08ec14c5 100644
--- a/pkg/ddl/ingest/backend.go
+++ b/pkg/ddl/ingest/backend.go
@@ -187,6 +187,8 @@ func (bc *litBackendCtx) Flush(indexID int64, mode FlushMode) (flushed, imported
        }

        shouldFlush, shouldImport := bc.checkFlush(mode)
+       shouldFlush = true
+       shouldImport = true
        if !shouldFlush {
                return false, false, nil
        }
```

and print TS used in import, or check TiKV

run `TestAddIndexRemoteDuplicateCheck` with the change, or other ADD INDEX that can trigger disk-quota import

```diff
diff --git a/tests/realtikvtest/addindextest4/ingest_test.go b/tests/realtikvtes
t/addindextest4/ingest_test.go
index 2e393ce4f8..7a3f91f031 100644
--- a/tests/realtikvtest/addindextest4/ingest_test.go
+++ b/tests/realtikvtest/addindextest4/ingest_test.go
@@ -407,7 +407,8 @@ func TestAddIndexRemoteDuplicateCheck(t *testing.T) {
        tk.MustExec("insert into t values(100000, 1, 1);")

        ingest.ForceSyncFlagForTest = true
-       tk.MustGetErrCode("alter table t add unique index idx(b);", errno.ErrDupEntry)
+       tk.MustExec("alter table t add index idx_test(b);")
+       //tk.MustGetErrCode("alter table t add unique index idx(b);", errno.ErrDupEntry)
        ingest.ForceSyncFlagForTest = false

        tk.MustExec("set global tidb_ddl_reorg_worker_cnt=4;")
```

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

TiKV panic due to it has data with TS = 0

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #57980

Problem Summary:

### What changed and how does it work?

Previously, after reset engine we set the TS to `EngineConfig`. But `engineMeta` is the place that really take effect. The conversion from `EngineConfig` to `engineMeta` happens when 1) engine is opened, or 2) external engine is closed normally. In disk-quota triggered import, above conversion does not happen

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: pkg/lightning/backend/local/region_job.go [hunk 1]
```diff
@@ -436,6 +436,10 @@ func (local *Backend) doWrite(ctx context.Context, j *regionJob) error {
 		allPeers = append(allPeers, peer)
 	}
 	dataCommitTS := j.ingestData.GetTS()
+	if dataCommitTS == 0 {
+		intest.Assert(false, "data commitTS is 0")
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/region_job.go:440]:
```suggestion
```

File: pkg/lightning/backend/local/region_job.go [hunk 2]
```diff
@@ -436,6 +436,10 @@ func (local *Backend) doWrite(ctx context.Context, j *regionJob) error {
 		allPeers = append(allPeers, peer)
 	}
 	dataCommitTS := j.ingestData.GetTS()
+	if dataCommitTS == 0 {
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/region_job.go:439]: for `intest` maybe add a range test that TS should be in range `[now-1m, now)`

File: pkg/lightning/backend/local/local.go [hunk 3]
```diff
@@ -1602,12 +1602,25 @@ func (local *Backend) ResetEngine(ctx context.Context, engineUUID uuid.UUID) err
...
+// invalid. Caller must use AllocTSAfterResetEngine to set a valid TS before
+// import the engine.
 func (local *Backend) ResetEngineSkipAllocTS(ctx context.Context, engineUUID uuid.UUID) error {
 	return local.engineMgr.resetEngine(ctx, engineUUID, true)
 }
 
+// AllocTSAfterResetEngine allocates a new TS for the engine after it's reset.
+// This is typically called after persisting the chosen TS of the engine to make
+// sure TS is not changed after task failover.
+func (local *Backend) AllocTSAfterResetEngine(engineUUID uuid.UUID, ts uint64) error {
```
Comment (D3Hunter) [inline pkg/lightning/backend/local/local.go:1614]:
```suggestion
func (local *Backend) SetTSAfterResetEngine(engineUUID uuid.UUID, ts uint64) error {
```
there is no `alloc`, we only set it

File: pkg/lightning/backend/backend.go [hunk 4]
```diff
@@ -319,13 +319,6 @@ func (engine *OpenedEngine) LocalWriter(ctx context.Context, cfg *LocalWriterCon
 	return engine.backend.LocalWriter(ctx, cfg, engine.uuid)
 }
 
-// SetTS sets the TS of the engine. In most cases if the caller wants to specify
-// TS it should use the TS field in EngineConfig. This method is only used after
-// a ResetEngine.
-func (engine *OpenedEngine) SetTS(ts uint64) {
-	engine.config.TS = ts
```
Comment (D3Hunter) [inline pkg/lightning/backend/backend.go:326]: can you also update the comment of `EngineConfig.TS`

File: pkg/lightning/backend/local/region_job.go (hunk 1 above)
Comment (lance6716) [reply pkg/lightning/backend/local/region_job.go:440]: I added it because DDL can retry the whole ingest task. Without this line, the newly added unit test can pass, because when the second task has zero TS it will fail, and DDL continues from checkpoint.

File: pkg/lightning/backend/local/region_job.go (hunk 2 above)
Comment (lance6716) [reply pkg/lightning/backend/local/region_job.go:439]: In real world execution, the TS is determined and persisted in subtask metadata, maybe it's earlier than now-1m. When we test failover, chaos test, or wjhuang2016's SQL fuzzing, intest flag may be turned on and become flaky tests

Comment (D3Hunter) [reply pkg/lightning/backend/local/region_job.go:439]: anyway, we need some basic range check, either 1m, 1h, or even 1d

File: pkg/lightning/backend/local/region_job.go (hunk 1 above)
Comment (D3Hunter) [reply pkg/lightning/backend/local/region_job.go:440]: > DDL can retry the whole ingest task.

shouldn't this be a fatal error?

**Comment by lance6716** [comment]
/hold

checking tests

**Comment by lance6716** [comment]
/unhold

checked that without the code part changes, the new test `TestAddIndexDiskQuotaTS` will cause TiKV panic

File: tests/realtikvtest/addindextest3/ingest_test.go [hunk 5]
```diff
@@ -448,6 +448,27 @@ func TestAddIndexMockFlushError(t *testing.T) {
 	require.True(t, strings.Contains(jobTp, "ingest"), jobTp)
 }
 
+func TestAddIndexDiskQuotaTS(t *testing.T) {
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest3/ingest_test.go:451]: I know add-index with DXF shouldn't have such issue, but can you add a case to cover it too?

Comment (lance6716) [reply tests/realtikvtest/addindextest3/ingest_test.go:451]: OK, I can add one test for DXF enabled. But we should leave more test improvements in future in a separate PR. Like iterate all variables combinations like {DXF = on/off, disk quota = on/off, ...} and provide a helper function to prepare environment, and run the testing logic will all combinations.
