### PR TITLE
*: Move log category into a real field

### LINKED ISSUE #45057: Move log category to a proper field
## Enhancement

Instead of
```go
logutil.BgLogger().Warn("[ddl-ingest] cannot read sort path", zap.Error(err))
```

Use
```go
logutil.BgLogger().Warn("cannot read sort path", zap.Error(err), zap.String("category", "ddl-ingest"))
```

This changes the JSON logging from:
```json
{
  "level": "WARN",
  "time": "2023/06/29 12:37:30.769 +02:00",
  "caller": "env.go:52",
  "message": "[ddl-ingest] initialize environment failed",
  "storage limitation": "only support TiKV storage",
  "current storage": "unistore",
  "lightning is initialized": false
}
```

To:
```json
{
  "level": "WARN",
  "time": "2023/06/29 12:37:30.769 +02:00",
  "caller": "env.go:52",
  "message": "initialize environment failed",
  "storage limitation": "only support TiKV storage",
  "current storage": "unistore",
  "lightning is initialized": false,
  "category": "ddl-ingest"
}
```

This allows JQ to do filtering like this:
```
$ jq 'select(.category == "ddl")' /tmp/tidb.log 
{
  "level": "INFO",
  "time": "2023/06/29 13:53:32.903 +02:00",
  "caller": "ddl.go:762",
  "message": "start DDL",
  "category": "ddl",
  "ID": "b7bc92eb-9b3f-4f3b-9506-22f7a300b472",
  "runWorker": true
}
...
```

This would also allow more efficient filtering and indexing in tools like ElasticSearch or when using a table on a TiDB server to store logging.

When using the text logging instead of JSON logging this looks like this:
```
[2023/06/29 14:05:18.888 +02:00] [INFO] [ddl.go:762] ["start DDL"] [category=ddl] [ID=221d1e06-f3cd-490b-9286-3d90099ebee4] [runWorker=true]
```

Instead of this:
```
[2023/06/29 14:05:18.888 +02:00] [INFO] [ddl.go:762] ["[ddl] start DDL"] [ID=221d1e06-f3cd-490b-9286-3d90099ebee4] [runWorker=true]
```

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #45057 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
The category of the log message was moved from the `message` field to it's own field.
```

### CODE REVIEW

File: bindinfo/handle.go [hunk 1]
```diff
@@ -738,12 +738,12 @@ func (h *BindHandle) newBindRecord(row chunk.Row) (string, *BindRecord, error) {
 func (h *BindHandle) setBindRecord(hash string, meta *BindRecord) {
 	newCache, err0 := h.bindInfo.Value.Load().(*bindCache).Copy()
 	if err0 != nil {
-		logutil.BgLogger().Warn("[sql-bind] BindHandle.setBindRecord", zap.Error(err0))
```
Comment (lance6716) [inline bindinfo/handle.go:741]: we can use `With()` to create the logger, so no need to repeated add the zap Fields?

Comment (dveeden) [reply bindinfo/handle.go:741]: I think that can be used on a case-by-case bases. Seems quite useful.

https://pkg.go.dev/go.uber.org/zap#Logger.With

Comment (dveeden) [reply bindinfo/handle.go:741]: I assume this would be something like this?

Instead of
```go
logutil.BgLogger().Warn("[sql-bind] BindHandle.setBindRecord", zap.Error(err0))

// or

logutil.BgLogger().Warn("BindHandle.setBindRecord", zap.Error(err0), zap.String("category", "sql-bind"))
```

Use
```go
bindLog := logutil.BgLogger().With(zap.String("category", "sql-bind"))

...

bindLog.Warn("BindHandle.setBindRecord", zap.Error(err0))
```

**Review by tangenta — APPROVED** [review]

File: bindinfo/handle.go (hunk 1 above)
Comment (lance6716) [reply bindinfo/handle.go:741]: @dveeden do you want to finish this PR as-is, and leave my suggestions for future change? If so, I can give a lgtm

Comment (dveeden) [reply bindinfo/handle.go:741]: @lance6716 Yes.

**Review by lance6716 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

File: autoid_service/autoid.go [hunk 2]
```diff
@@ -327,7 +327,7 @@ func (s *Service) Close() {
 			if v.base > 0 {
 				err := v.forceRebase(context.Background(), s.store, k.dbID, k.tblID, v.base, v.isUnsigned)
 				if err != nil {
-					logutil.BgLogger().Warn("[autoid service] save cached ID fail when service exit",
+					logutil.BgLogger().Warn("save cached ID fail when service exit", zap.String("category", "autoid service"),
```
Comment (hawkingrei) [inline autoid_service/autoid.go:330]: We can create a package which uses ```logutil.Bglogger().Named("xxxx")```. it is easy to reuse the code.

**Comment by hawkingrei** [comment]
> /retest

This pr need configure reviewer's approve.

**Review by bb7133 — APPROVED** [review]
LGTM
