### PR TITLE
planner: allow correlated exists subqueries to early-out | tidb-test=pr/2593

### LINKED ISSUE #63348: NO_DECORRELATE EXISTS subquery does not early-out
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t1` (
  `a` int,
  `b` int,
  `c` int,
  Primary KEY (`a`),
  KEY `ib` (`b`)
);
set @@cte_max_recursion_depth=10000000;
INSERT INTO t1 (a, b, c)
SELECT a, mod(a, 1000) AS b, mod(a, 10) AS c
FROM (
    WITH RECURSIVE x AS (
        SELECT 1 AS a
        UNION ALL
        SELECT a + 1 AS a
        FROM x
        WHERE a < 1000000
    )
    SELECT a
    FROM x
) AS subquery;
Analyze table t1;
```
Then test the following SQLs - where adding LIMIT 1 will simulate early-out.
Note - column a is PK. column b is indexed. column c is not indexed. Each example has one SQL without limit, and one with limit.
```
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.b = t1.b),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.b = t1.b limit 1),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.c = t1.c),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.c = t1.c limit 1),1,0) from t2 t1 where c < 2;
```
### 2. What did you expect to see? (Required)

Would expect to see similar performance with and without LIMIT 1.

### 3. What did you see instead (Required)

Correlated on b
without LIMIT == 2 min 50 sec
with LIMIT == approx 600 millisec

Correlated on c
without LIMIT == 940 millisec
with LIMIT == approx 350 millisec

### 4. What is your TiDB version? (Required)

master branch

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: ref #51116 close #63348

Problem Summary:

### What changed and how does it work?

Enhancement to add LIMIT 1 to EXISTS correlated subqueries (where NO_DECORRELATE hint exists) if no existing LIMIT applies within the subquery.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

To test - here are the recreate steps:
```
CREATE TABLE `t1` (
  `a` int,
  `b` int,
  `c` int,
  Primary KEY (`a`),
  KEY `ib` (`b`)
);
set @@cte_max_recursion_depth=10000000;
INSERT INTO t1 (a, b, c)
SELECT a, mod(a, 1000) AS b, mod(a, 10) AS c
FROM (
    WITH RECURSIVE x AS (
        SELECT 1 AS a
        UNION ALL
        SELECT a + 1 AS a
        FROM x
        WHERE a < 1000000
    )
    SELECT a
    FROM x
) AS subquery;
Analyze table t1;
```
Then test the following SQLs - where adding LIMIT 1 will replicate what this PR is delivering.
Note - column a is PK. column b is indexed. column c is not indexed. Each example has one SQL without limit, and one with limit.
```
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.a = t1.a),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.a = t1.a limit 1),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.b = t1.b),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.b = t1.b limit 1),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.c = t1.c),1,0) from t2 t1 where c < 2;
explain analyze select a, if(exists(select /*+ NO_DECORRELATE() */ 1 from t2 t2 where t2.c = t1.c limit 1),1,0) from t2 t1 where c < 2;
```
For the above tests - all queries would the same result before/after with the LIMIT 1 vs without - since this PR will implicitly add the LIMIT 1. This PR (or adding LIMIT 1) can be used to test the performance benefit of early-out.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -1039,9 +1039,22 @@ func (er *expressionRewriter) handleExistSubquery(ctx context.Context, planCtx *
...
 		return v, true
 	}
-	np = er.popExistsSubPlan(planCtx, np)
+	// Add LIMIT 1 when noDecorrelate is true for EXISTS subqueries to enable early exit
 	corCols := coreusage.ExtractCorColumnsBySchema4LogicalPlan(np, planCtx.plan.Schema())
 	noDecorrelate := isNoDecorrelate(planCtx, corCols, hintFlags)
+	if noDecorrelate {
+		// Create a LIMIT 1 clause for performance optimization
+		limitClause := &ast.Limit{
+			Count: ast.NewValueExpr(1, "", ""),
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/expression_rewriter.go]: Other examples in our codebase use the same approach that is in my PR

File: pkg/planner/core/logical_plans_test.go [hunk 2]
```diff
@@ -2392,6 +2392,34 @@ func TestRemoveOrderbyInSubquery(t *testing.T) {
...
+		},
+	}
+
+	s := coretestsdk.CreatePlannerSuiteElems()
+	defer s.Close()
+	ctx := context.TODO()
+	for i, tt := range tests {
+		comment := fmt.Sprintf("case:%v sql:%s", i, tt.sql)
+		stmt, err := s.GetParser().ParseOneStmt(tt.sql, "", "")
+		require.NoError(t, err, comment)
```
Comment (hawkingrei) [inline pkg/planner/core/logical_plans_test.go:2416]:
```suggestion
		stmt, err := s.GetParser().ParseOneStmt(tt.sql, "", "")
		require.NoErrorf(t, err, "case:%v sql:%s", i, tt.sql)
```

**Review by guo-shaoge — APPROVED** [review]

**Review by mjonss — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]

**Comment by hawkingrei** [comment]
/hold 


@time-and-fate PTAL

File: pkg/planner/core/expression_rewriter.go [hunk 3]
```diff
@@ -2676,3 +2690,21 @@ func hasCurrentDatetimeDefault(col *model.ColumnInfo) bool {
 	}
 	return strings.ToLower(x) == ast.CurrentTimestamp
 }
+
+// hasLimit checks if the plan already contains a LIMIT operator
+func (er *expressionRewriter) hasLimit(plan base.LogicalPlan) bool {
```
Comment (AilinKid) [inline pkg/planner/core/expression_rewriter.go]: this func is not er related, can we just impl it as a simple func without receiver

File: pkg/planner/core/expression_rewriter.go [hunk 4]
```diff
@@ -2676,3 +2690,21 @@ func hasCurrentDatetimeDefault(col *model.ColumnInfo) bool {
...
+	if plan == nil {
+		return false
+	}
+	// Check if this is a LogicalLimit
+	if _, ok := plan.(*logicalop.LogicalLimit); ok {
```
Comment (AilinKid) [inline pkg/planner/core/expression_rewriter.go:2702]: maxOneRow is another kind of operator, maybe, which only allow output one row

File: pkg/planner/core/expression_rewriter.go [hunk 5]
```diff
@@ -1043,10 +1043,24 @@ func (er *expressionRewriter) handleExistSubquery(ctx context.Context, planCtx *
...
 	noDecorrelate := isNoDecorrelate(planCtx, corCols, hintFlags, handlingExistsSubquery)
-
+	if noDecorrelate {
+		// Only add LIMIT 1 if the query doesn't already contain a LIMIT clause
+		if !er.hasLimit(np) {
+			limitClause := &ast.Limit{
+				Count: ast.NewValueExpr(1, "", ""),
+			}
+			var err error
+			np, err = planCtx.builder.buildLimit(np, limitClause)
```
Comment (AilinKid) [inline pkg/planner/core/expression_rewriter.go:1056]: since we have made some special rewrite here, i'm not sure whether we need to care about the plan cache, maybe not, same pattern should always use this limit to improve their perf

**Review by AilinKid — APPROVED** [review]

File: pkg/planner/core/expression_rewriter.go (hunk 3 above)
Comment (terry1purcell) [reply pkg/planner/core/expression_rewriter.go]: Done

File: pkg/planner/core/expression_rewriter.go (hunk 4 above)
Comment (terry1purcell) [reply pkg/planner/core/expression_rewriter.go:2702]: After testing the maxOneRow approach - I found that this won't work because it is designed for scalar subqueries that guarantee only 1 row is returned. It will return an error if I use maxOneRow in this context for an EXISTS subquery. It will succeed for EXISTS with a unique/PK (since one row is guaranteed) but will fail if used with EXISTS that uses a non-unique index (or no index).

File: pkg/planner/core/expression_rewriter.go (hunk 5 above)
Comment (terry1purcell) [reply pkg/planner/core/expression_rewriter.go:1056]: As you highlight - it will always use the same pattern - so there is no change for plan cache behavior.

**Comment by terry1purcell** [comment]
/unhold

All questions have been answered.
