### PR TITLE
executor: Fix the panic in `approx_percentile` function

### LINKED ISSUE #40463: parallel hash aggregation panicked
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `4f380f26-9af6-4df8-959d-ad6296eff914` (
  `f7a9a4be-3728-449b-a5ea-df9b957eec67` enum('bkdv0','9rqy','lw','neud','ym','4nbv','9a7','bpkfo','xtfl','59','6vjj') NOT NULL DEFAULT 'neud',
  `43ca0135-1650-429b-8887-9eabcae2a234` set('8','5x47','xc','o31','lnz','gs5s','6yam','1','20ea','i','e') NOT NULL DEFAULT 'e',
  PRIMARY KEY (`f7a9a4be-3728-449b-a5ea-df9b957eec67`,`43ca0135-1650-429b-8887-9eabcae2a234`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;
INSERT INTO `4f380f26-9af6-4df8-959d-ad6296eff914` VALUES ('bkdv0','gs5s'),('lw','20ea'),('neud','8'),('ym','o31'),('4nbv','o31'),('xtfl','e');

CREATE TABLE `ba35a09f-76f4-40aa-9b48-13154a24bdd2` (
  `9b2a7138-14a3-4e8f-b29a-720392aad22c` set('zgn','if8yo','e','k7','bav','xj6','lkag','m5','as','ia','l3') DEFAULT 'zgn,if8yo,e,k7,ia,l3',
  `a60d6b5c-08bd-4a6d-b951-716162d004a5` set('6li6','05jlu','w','l','m','e9r','5q','d0ol','i6ajr','csf','d32') DEFAULT '6li6,05jlu,w,l,m,d0ol,i6ajr,csf,d32',
  `fb753d37-6252-4bd3-9bd1-0059640e7861` year(4) DEFAULT '2065',
  UNIQUE KEY `51816c39-27df-4bbe-a0e7-d6b6f54be2a2` (`fb753d37-6252-4bd3-9bd1-0059640e7861`),
  KEY `b0dfda0a-ffed-4c5b-9a72-4113bc1cbc8e` (`9b2a7138-14a3-4e8f-b29a-720392aad22c`,`fb753d37-6252-4bd3-9bd1-0059640e7861`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin /*T! SHARD_ROW_ID_BITS=5 */;
insert into `ba35a09f-76f4-40aa-9b48-13154a24bdd2` values ("if8yo", "6li6,05jlu,w,l,m,d0ol,i6ajr,csf,d32", 2065);

CREATE TABLE `07ccc74e-14c3-4685-bb41-c78a069b1a6d` (
  `8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae` bigint(20) NOT NULL DEFAULT '-4604789462044748682',
  `30b19ecf-679f-4ca3-813f-d3c3b8f7da7e` date NOT NULL DEFAULT '5030-11-23',
  `1c52eaf2-1ebb-4486-9410-dfd00c7c835c` decimal(7,5) DEFAULT '-81.91307',
  `4b09dfdc-e688-41cb-9ffa-d03071a43077` float DEFAULT '1.7989023',
  PRIMARY KEY (`30b19ecf-679f-4ca3-813f-d3c3b8f7da7e`,`8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae`) /*T![clustered_index] CLUSTERED */,
  KEY `ae7a7637-ca52-443b-8a3f-69694f730cc4` (`8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae`),
  KEY `42640042-8a17-4145-9510-5bb419f83ed9` (`8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae`),
  KEY `839f4f5a-83f3-449b-a7dd-c7d2974d351a` (`30b19ecf-679f-4ca3-813f-d3c3b8f7da7e`),
  KEY `c474cde1-6fe4-45df-9067-b4e479f84149` (`8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae`),
  KEY `f834d0a9-709e-4ca8-925d-73f48322b70d` (`8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk COLLATE=gbk_chinese_ci;
set sql_mode="";
INSERT INTO `07ccc74e-14c3-4685-bb41-c78a069b1a6d` VALUES (616295989348159438,'0000-00-00',1.00000,1.7989023),(2215857492573998768,'1970-02-02',0.00000,1.7989023),(2215857492573998768,'1983-05-13',0.00000,1.7989023),(-2840083604831267906,'1984-01-30',1.00000,1.7989023),(599388718360890339,'1986-09-09',1.00000,1.7989023),(3506764933630033073,'1987-11-22',1.00000,1.7989023),(3506764933630033073,'2002-02-26',1.00000,1.7989023),(3506764933630033073,'2003-05-14',1.00000,1.7989023),(3506764933630033073,'2007-05-16',1.00000,1.7989023),(3506764933630033073,'2017-02-20',1.00000,1.7989023),(3506764933630033073,'2017-08-06',1.00000,1.7989023),(2215857492573998768,'2019-02-18',1.00000,1.7989023),(3506764933630033073,'2020-08-11',1.00000,1.7989023),(3506764933630033073,'2028-06-07',1.00000,1.7989023),(3506764933630033073,'2036-08-16',1.00000,1.7989023);


select  /*+ use_index_merge( `4f380f26-9af6-4df8-959d-ad6296eff914` ) */ /*+  stream_agg() */  approx_percentile( `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` , 77 ) as r0 , `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` as r1 from `4f380f26-9af6-4df8-959d-ad6296eff914` where not( IsNull( `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` ) ) and not( `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` in ( select `8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae` from `07ccc74e-14c3-4685-bb41-c78a069b1a6d` where `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` in ( select `a60d6b5c-08bd-4a6d-b951-716162d004a5` from `ba35a09f-76f4-40aa-9b48-13154a24bdd2` where not( `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` between 'bpkfo' and '59' ) and not( `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` in ( select `fb753d37-6252-4bd3-9bd1-0059640e7861` from `ba35a09f-76f4-40aa-9b48-13154a24bdd2` where IsNull( `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` ) or not( `4f380f26-9af6-4df8-959d-ad6296eff914`.`43ca0135-1650-429b-8887-9eabcae2a234` in ( select `8a93bdc5-2214-4f96-b5a7-1ba4c0d396ae` from `07ccc74e-14c3-4685-bb41-c78a069b1a6d` where IsNull( `4f380f26-9af6-4df8-959d-ad6296eff914`.`43ca0135-1650-429b-8887-9eabcae2a234` ) and not( `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67` between 'neud' and 'bpkfo' ) ) ) ) ) ) ) ) group by `4f380f26-9af6-4df8-959d-ad6296eff914`.`f7a9a4be-3728-449b-a5ea-df9b957eec67`;
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
``` 
[aggregate.go:454] ["parallel hash aggregation panicked"] [error="runtime error: index out of range [0] with length 0"] [stack="github.com/pingcap/tidb/executor.recoveryHashAgg\n\t/Users/bba/pc/tidb/executor/aggregate.go:454\ngithub.com/pingcap/tidb/executor.(*HashAggFinalWorker).run.func1\n\t/Users/bba/pc/tidb/executor/aggregate.go:768\nruntime.gopanic\n\t/Users/bba/.gvm/gos/go1.19/src/runtime/panic.go:884\nruntime.goPanicIndex\n\t/Users/bba/.gvm/gos/go1.19/src/runtime/panic.go:113\ngithub.com/pingcap/tidb/util/chunk.(*Column).AppendInt64\n\t/Users/bba/pc/tidb/util/chunk/column.go:247\ngithub.com/pingcap/tidb/util/chunk.(*Chunk).AppendInt64\n\t/Users/bba/pc/tidb/util/chunk/chunk.go:489\ngithub.com/pingcap/tidb/executor/aggfuncs.(*percentileOriginal4Int).AppendFinalResult2Chunk\n\t/Users/bba/pc/tidb/executor/aggfuncs/func_percentile.go:177\ngithub.com/pingcap/tidb/executor.(*HashAggFinalWorker).loadFinalResult\n\t/Users/bba/pc/tidb/executor/aggregate.go:734\ngithub.com/pingcap/tidb/executor.(*HashAggFinalWorker).run\n\t/Users/bba/pc/tidb/executor/aggregate.go:778"]
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #40463 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/aggfuncs/aggfunc_test.go [hunk 1]
```diff
@@ -586,16 +586,6 @@ func testAggFunc(t *testing.T, p aggTest) {
...
-
-	// test the empty input
-	resultChk.Reset()
-	finalFunc.ResetPartialResult(finalPr)
-	err = finalFunc.AppendFinalResult2Chunk(ctx, finalPr, resultChk)
-	require.NoError(t, err)
-	dt = resultChk.GetRow(0).GetDatum(0, desc.RetTp)
-	result, err = dt.Compare(ctx.GetSessionVars().StmtCtx.TypeCtx(), &p.results[0], ctor)
-	require.NoError(t, err)
-	require.Equalf(t, 0, result, "%v != %v", dt.String(), p.results[0])
```
Comment (SeaRise) [inline pkg/executor/aggfuncs/aggfunc_test.go:598]: why removing this test case?

File: pkg/executor/aggfuncs/builder.go [hunk 2]
```diff
@@ -144,6 +144,25 @@ func buildApproxCountDistinct(aggFuncDesc *aggregation.AggFuncDesc, ordinal int)
...
+	if aggFuncDesc.Args[0].GetType().GetType() == mysql.TypeBit {
+		evalType = types.ETString // same as other aggregate function
+	}
+
+	if hasEnumSetAsIntFlag {
+		arg0FieldType.SetFlag(mysql.EnumSetAsIntFlag)
+	}
+
+	return evalType
+}
```
Comment (SeaRise) [inline pkg/executor/aggfuncs/builder.go:164]: Can you add some comments about why deleting `mysql.EnumSetAsIntFlag` and setting it later?

File: pkg/executor/aggfuncs/aggfunc_test.go (hunk 1 above)
Comment (xzhangxian1008) [reply pkg/executor/aggfuncs/aggfunc_test.go:598]: > why removing this test case?

This is duplicate with the test above.

File: pkg/executor/aggfuncs/builder.go (hunk 2 above)
Comment (xzhangxian1008) [reply pkg/executor/aggfuncs/builder.go:164]: > Can you add some comments about why deleting `mysql.EnumSetAsIntFlag` and setting it later?

Because maybe this flag will be used in other place. I will add comment.

File: pkg/executor/aggfuncs/aggfunc_test.go (hunk 1 above)
Comment (SeaRise) [reply pkg/executor/aggfuncs/aggfunc_test.go:598]: ok

File: pkg/executor/aggfuncs/builder.go (hunk 2 above)
Comment (SeaRise) [reply pkg/executor/aggfuncs/builder.go:164]: Why does the original logic cause tidb to crash?

File: pkg/executor/aggfuncs/builder.go [hunk 3]
```diff
@@ -144,6 +144,19 @@ func buildApproxCountDistinct(aggFuncDesc *aggregation.AggFuncDesc, ordinal int)
...
 
+func getEvalTypeForApproxPercentile(aggFuncDesc *aggregation.AggFuncDesc) types.EvalType {
+	evalType := aggFuncDesc.Args[0].GetType().EvalType()
+	argType := aggFuncDesc.Args[0].GetType().GetType()
+
+	// When argType == mysql.TypeEnum, the field flag may be set with mysql.EnumSetAsIntFlag
+	// and the evalType will be set to types.ETInt, it's an unexpected behavior.
+	if argType == mysql.TypeEnum || argType == mysql.TypeBit {
+		evalType = types.ETString
+	}
```
Comment (SeaRise) [inline pkg/executor/aggfuncs/builder.go:155]:
```suggestion
	if argType == mysql.TypeBit {
		evalType = types.ETString // just same as other aggregate function
	}
	// Sometimes `mysql.EnumSetAsIntFlag` may be set to true, such as when join,
	// which is unexpected for `buildApproxPercentile` and `mysql.TypeEnum` and `mysql.TypeSet` will return unexpected `ETInt` here,
	// so here `evalType` are forcibly set to `ETString`.
	if argType == mysql.TypeEnum {
		evalType = types.ETString
	}
```

File: pkg/executor/aggfuncs/builder.go [hunk 4]
```diff
@@ -144,6 +144,20 @@ func buildApproxCountDistinct(aggFuncDesc *aggregation.AggFuncDesc, ordinal int)
...
 }
 
+func getEvalTypeForApproxPercentile(aggFuncDesc *aggregation.AggFuncDesc) types.EvalType {
+	evalType := aggFuncDesc.Args[0].GetType().EvalType()
+	argType := aggFuncDesc.Args[0].GetType().GetType()
+
+	// Sometimes `mysql.EnumSetAsIntFlag` may be set to true, such as when join,
+	// which is unexpected for `buildApproxPercentile` and `mysql.TypeEnum` and `mysql.TypeSet` will return unexpected `ETInt` here,
+	// so here `evalType` are forcibly set to `ETString`.
+	if argType == mysql.TypeEnum || argType == mysql.TypeSet || argType == mysql.TypeBit {
```
Comment (SeaRise) [inline pkg/executor/aggfuncs/builder.go:154]: And the comment for `mysql.TypeBit`?

Comment (SeaRise) [reply pkg/executor/aggfuncs/builder.go:154]: For `mysql.TypeBit`, just same as other aggregate function

Comment (xzhangxian1008) [reply pkg/executor/aggfuncs/builder.go:154]: > And the comment for `mysql.TypeBit`?

ok

File: pkg/executor/aggfuncs/func_percentile_test.go [hunk 5]
```diff
@@ -57,3 +59,12 @@ func TestPercentile(t *testing.T) {
 		require.Equal(t, want, data[index])
 	}
 }
+
+func TestFix40463(t *testing.T) {
```
Comment (SeaRise) [inline pkg/executor/aggfuncs/func_percentile_test.go:63]: And add the sql in https://github.com/pingcap/tidb/issues/40463 to ft?
https://github.com/pingcap/tidb/tree/master/tests/integrationtest

**Review by SeaRise — APPROVED** [review]
Others LGTM

File: pkg/executor/aggfuncs/func_percentile_test.go (hunk 5 above)
Comment (xzhangxian1008) [reply pkg/executor/aggfuncs/func_percentile_test.go:63]: > And add the sql in #40463 to ft? https://github.com/pingcap/tidb/tree/master/tests/integrationtest

okk

**Review by guo-shaoge — APPROVED** [review]
