### PR TITLE
stmtsummary: check authUsers using the polymorphic stmtSummaryStats

### LINKED ISSUE #58403: DATA RACE in the TestStmtSummaryIssue35340
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
fatal error: concurrent map read and map write
goroutine 86208 [running]:
github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).isAuthed(...)
	pkg/util/stmtsummary/reader.go:145
github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).getStmtByDigestElementRow(0xc019d22a10, 0xc00188b808, 0xc00c446d88)
	pkg/util/stmtsummary/reader.go:184 +0xef
github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).getStmtByDigestRow(0xc019d22a10, 0xc00c446d88, 0x67639a40)
	pkg/util/stmtsummary/reader.go:178 +0xd4
github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).GetStmtSummaryCurrentRows(0xc019d22a10)
	pkg/util/stmtsummary/reader.go:103 +0x2c5
github.com/pingcap/tidb/pkg/executor.(*stmtSummaryRetriever).initSummaryRowsReader(0xc01f9ecdb0, {0x359d300, 0xc0069b3d48})
	pkg/executor/stmtsummary.go:165 +0x309
github.com/pingcap/tidb/pkg/executor.(*stmtSummaryRetriever).ensureRowsReader(0xc01f9ecdb0, {0x359d300, 0xc0069b3d48})
	pkg/executor/stmtsummary.go:117 +0xe5
github.com/pingcap/tidb/pkg/executor.(*stmtSummaryRetriever).retrieve(0xc01f9ecdb0, {0x30?, 0xc001cefc98?}, {0x359d300?, 0xc0069b3d48?})
	pkg/executor/stmtsummary.go:91 +0x28
github.com/pingcap/tidb/pkg/executor.(*MemTableReaderExec).Next(0xc012729b00, {0x3504560, 0xa91c420}, 0xc00a609310)
	pkg/executor/memtable_reader.go:136 +0x29c
github.com/pingcap/tidb/pkg/executor/internal/exec.Next({0x3504560, 0xa91c420}, {0x353b2e0, 0xc012729b00}, 0xc00a609310)
	pkg/executor/internal/exec/executor.go:460 +0x29f
github.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).fetchChildData(0xc010452dc8, {0x3504560, 0xa91c420}, 0xc007fd7dc0?)
	pkg/executor/aggregate/agg_hash_executor.go:479 +0x165
created by github.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).prepare4ParallelExec in goroutine 14945
	pkg/executor/aggregate/agg_hash_executor.go:558 +0xc5 
```

```
==================
WARNING: DATA RACE
Write at 0x00c0085626c0 by goroutine 15266:
  runtime.mapaccess2_faststr()
      /opt/homebrew/opt/go/libexec/src/runtime/map_faststr.go:117 +0x42c
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryStats).add()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/statement_summary.go:775 +0x8c
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryByDigest).add.func1()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/statement_summary.go:645 +0xcc
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryByDigest).add()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/statement_summary.go:675 +0x48
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryByDigestMap).AddStatement()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/statement_summary.go:382 +0x3c0
  github.com/pingcap/tidb/pkg/util/stmtsummary/v2.Add()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/v2/stmtsummary.go:540 +0x90
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).SummaryStmt()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:2023 +0x119c
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).FinishExecuteStmt()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:1423 +0x42c
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).CloseRecordSet()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:1549 +0x44
  github.com/pingcap/tidb/pkg/executor.(*recordSet).Close()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:230 +0x280
  github.com/pingcap/tidb/pkg/session.(*execStmtResult).Close()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:2378 +0x68
  github.com/pingcap/tidb/pkg/session.ResultSetToStringSlice()
      /Users/weizhenwang/tmp/tidb/pkg/session/tidb.go:365 +0x98
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).ResultSetToResultWithCtx()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:317 +0x6c
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQueryWithContext()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:243 +0x1f0
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQuery()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:176 +0xac
  github.com/pingcap/tidb/pkg/infoschema/test/clustertablestest.TestStmtSummaryIssue35340.func1()
      /Users/weizhenwang/tmp/tidb/pkg/infoschema/test/clustertablestest/cluster_tables_test.go:439 +0x128

Previous read at 0x00c0085626c0 by goroutine 16086:
  runtime.mapassign_fast64ptr()
      /opt/homebrew/opt/go/libexec/src/runtime/map_fast64.go:214 +0x36c
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).isAuthed()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/reader.go:145 +0x114
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).getStmtByDigestElementRow()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/reader.go:184 +0x118
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).getStmtByDigestRow()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/reader.go:178 +0x168
  github.com/pingcap/tidb/pkg/util/stmtsummary.(*stmtSummaryReader).GetStmtSummaryCurrentRows()
      /Users/weizhenwang/tmp/tidb/pkg/util/stmtsummary/reader.go:103 +0x3e8
  github.com/pingcap/tidb/pkg/executor.(*stmtSummaryRetriever).initSummaryRowsReader()
      /Users/weizhenwang/tmp/tidb/pkg/executor/stmtsummary.go:165 +0x2e4
  github.com/pingcap/tidb/pkg/executor.(*stmtSummaryRetriever).ensureRowsReader()
      /Users/weizhenwang/tmp/tidb/pkg/executor/stmtsummary.go:117 +0x120
  github.com/pingcap/tidb/pkg/executor.(*stmtSummaryRetriever).retrieve()
      /Users/weizhenwang/tmp/tidb/pkg/executor/stmtsummary.go:91 +0x38
  github.com/pingcap/tidb/pkg/executor.(*MemTableReaderExec).Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/memtable_reader.go:136 +0x2d8
  github.com/pingcap/tidb/pkg/executor/internal/exec.Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/internal/exec/executor.go:460 +0x270
  github.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).fetchChildData()
      /Users/weizhenwang/tmp/tidb/pkg/executor/aggregate/agg_hash_executor.go:479 +0x1c0
  github.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).prepare4ParallelExec.gowrap1()
      /Users/weizhenwang/tmp/tidb/pkg/executor/aggregate/agg_hash_executor.go:558 +0x58

Goroutine 15266 (running) created at:
  github.com/pingcap/tidb/pkg/infoschema/test/clustertablestest.TestStmtSummaryIssue35340()
      /Users/weizhenwang/tmp/tidb/pkg/infoschema/test/clustertablestest/cluster_tables_test.go:430 +0x214
  github.com/pingcap/tidb/pkg/session.(*session).replaceGlobalVariablesTableValue()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:1279 +0x19c
  github.com/pingcap/tidb/pkg/session.(*session).SetGlobalSysVar()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:1341 +0x1f4
  github.com/pingcap/tidb/pkg/executor.(*SetExecutor).setSysVariable()
      /Users/weizhenwang/tmp/tidb/pkg/executor/set.go:155 +0x504
  github.com/pingcap/tidb/pkg/executor.(*SetExecutor).Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/set.go:105 +0xaf8
  github.com/pingcap/tidb/pkg/executor/internal/exec.Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/internal/exec/executor.go:460 +0x270
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:1269 +0x5c
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:1018 +0x484
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:851 +0x29c
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:614 +0xf58
  github.com/pingcap/tidb/pkg/session.runStmt()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:2289 +0x3cc
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:2151 +0x132c
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:425 +0xb6c
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:159 +0x64
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:154 +0xd8
  github.com/pingcap/tidb/pkg/infoschema/test/clustertablestest.TestStmtSummaryIssue35340()
      /Users/weizhenwang/tmp/tidb/pkg/infoschema/test/clustertablestest/cluster_tables_test.go:421 +0x120
  github.com/pingcap/tidb/pkg/session.(*session).replaceGlobalVariablesTableValue()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:1279 +0x19c
  github.com/pingcap/tidb/pkg/session.(*session).SetGlobalSysVar()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:1341 +0x1f4
  github.com/pingcap/tidb/pkg/executor.(*SetExecutor).setSysVariable()
      /Users/weizhenwang/tmp/tidb/pkg/executor/set.go:155 +0x504
  github.com/pingcap/tidb/pkg/executor.(*SetExecutor).Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/set.go:105 +0xaf8
  github.com/pingcap/tidb/pkg/executor/internal/exec.Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/internal/exec/executor.go:460 +0x270
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:1269 +0x5c
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:1018 +0x484
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:851 +0x29c
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:614 +0xf58
  github.com/pingcap/tidb/pkg/session.runStmt()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:2289 +0x3cc
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:2151 +0x132c
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:425 +0xb6c
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:159 +0x64
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:154 +0xd8
  github.com/pingcap/tidb/pkg/infoschema/test/clustertablestest.TestStmtSummaryIssue35340()
      /Users/weizhenwang/tmp/tidb/pkg/infoschema/test/clustertablestest/cluster_tables_test.go:420 +0x100
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:142 +0x704
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseMemoryLimit()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/varsutil.go:375 +0xf0
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func218()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/sysvar.go:1155 +0x40
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:143 +0x758
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func217()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/sysvar.go:1148 +0x48
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/variable.go:377 +0x16c
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:142 +0x704
  fmt.Sscanf()
      /opt/homebrew/opt/go/libexec/src/fmt/scan.go:114 +0x130
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseByteSize()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/varsutil.go:406 +0x20
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func261()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/sysvar.go:1419 +0x30
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:143 +0x758
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadSysVarCacheLoop()
      /Users/weizhenwang/tmp/tidb/pkg/domain/domain.go:1960 +0x6c
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:3537 +0x60c
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func261()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/sysvar.go:1419 +0x30
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:143 +0x758
  github.com/pingcap/tidb/pkg/sessionctx/variable.parseSchemaCacheSize()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/varsutil.go:638 +0xe4
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func620()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/sysvar.go:3318 +0x48
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:143 +0x758
  github.com/pingcap/tidb/pkg/sessionctx/variable.init.func619()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/sysvar.go:3310 +0x48
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      /Users/weizhenwang/tmp/tidb/pkg/sessionctx/variable/variable.go:377 +0x16c
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:142 +0x704
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCacheIfNeeded()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:50 +0x150
  github.com/pingcap/tidb/pkg/domain.(*Domain).GetSessionCache()
      /Users/weizhenwang/tmp/tidb/pkg/domain/sysvar_cache.go:61 +0x34
  github.com/pingcap/tidb/pkg/session.(*session).loadCommonGlobalVariablesIfNeeded()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:3948 +0x204
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:2013 +0xec
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:1524 +0x23c
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadPrivilegeLoop()
      /Users/weizhenwang/tmp/tidb/pkg/domain/domain.go:1900 +0xe0
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:3530 +0x5d8
  github.com/pingcap/tidb/pkg/session.BootstrapSession()
      /Users/weizhenwang/tmp/tidb/pkg/session/session.go:3406 +0xac
  github.com/pingcap/tidb/pkg/testkit.bootstrap()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/mockstore.go:251 +0x88
  github.com/pingcap/tidb/pkg/testkit.CreateMockStoreAndDomain()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/mockstore.go:222 +0xa0
  github.com/pingcap/tidb/pkg/infoschema/test/clustertablestest.TestStmtSummaryIssue35340()
      /Users/weizhenwang/tmp/tidb/pkg/infoschema/test/clustertablestest/cluster_tables_test.go:417 +0x50
  testing.tRunner()
      /opt/homebrew/opt/go/libexec/src/testing/testing.go:1690 +0x184
  testing.(*T).Run.gowrap1()
      /opt/homebrew/opt/go/libexec/src/testing/testing.go:1743 +0x40

Goroutine 16086 (running) created at:
  github.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).prepare4ParallelExec()
      /Users/weizhenwang/tmp/tidb/pkg/executor/aggregate/agg_hash_executor.go:558 +0x13c
  github.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).parallelExec()
      /Users/weizhenwang/tmp/tidb/pkg/executor/aggregate/agg_hash_executor.go:612 +0x60
  github.com/pingcap/tidb/pkg/executor/aggregate.(*HashAggExec).Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/aggregate/agg_hash_executor.go:435 +0xf8
  github.com/pingcap/tidb/pkg/executor/internal/exec.Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/internal/exec/executor.go:460 +0x270
  github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:1269 +0x5c
  github.com/pingcap/tidb/pkg/executor.(*recordSet).Next()
      /Users/weizhenwang/tmp/tidb/pkg/executor/adapter.go:172 +0x148
  github.com/pingcap/tidb/pkg/session.(*execStmtResult).Next()
      <autogenerated>:1 +0x64
  github.com/pingcap/tidb/pkg/session.GetRows4Test()
      /Users/weizhenwang/tmp/tidb/pkg/session/tidb.go:343 +0xb8
  github.com/pingcap/tidb/pkg/session.ResultSetToStringSlice()
      /Users/weizhenwang/tmp/tidb/pkg/session/tidb.go:361 +0x7c
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).ResultSetToResultWithCtx()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:317 +0x6c
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQueryWithContext()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:243 +0x1f0
  github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustQuery()
      /Users/weizhenwang/tmp/tidb/pkg/testkit/testkit.go:176 +0xac
  github.com/pingcap/tidb/pkg/infoschema/test/clustertablestest.TestStmtSummaryIssue35340.func1()
      /Users/weizhenwang/tmp/tidb/pkg/infoschema/test/clustertablestest/cluster_tables_test.go:439 +0x128
==================
```

### PR DESCRIPTION
**Pull request by henrybw**
### What problem does this PR solve?

Issue Number: close #58403

Problem Summary:

`isAuthed` was factored out of `getStmtByDigestElementRow` so it could be shared with `getStmtByDigestCumulativeRow`, but the logic was hardcoded to use the cumulative statement stats, breaking the auth checks for the original interval-based statement summary tables.

### What changed and how does it work?

* In `isAuthed`, check `ssStats.authUsers` rather than checking `ssbd.cumulative.authUsers`.
* Extend `TestAccessPrivilege` to test the same query digests as before, but run as a different user in a new statement summary interval (which should not be able to access rows generated for the old user).

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
```Reverted the fix and confirmed that the modified TestAccessPrivilege test fails.```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: pkg/util/stmtsummary/statement_summary_test.go [hunk 1]
```diff
@@ -1563,4 +1563,32 @@ func TestAccessPrivilege(t *testing.T) {
 	reader.hasProcessPriv = true
 	datums = reader.GetStmtSummaryHistoryRows()
 	require.Len(t, datums, loops)
+
+	// Test the same query digests, but run as a different user in a new statement
+	// summary interval. The old user should not be able to access the rows generated
+	// for the new user.
+	ssMap.beginTimeForCurInterval = time.Now().Unix()
```
Comment (bb7133) [inline pkg/util/stmtsummary/statement_summary_test.go:1570]: Is this required?

Comment (henrybw) [reply pkg/util/stmtsummary/statement_summary_test.go:1570]: I think it is. The intent here is to create a new statement summary interval with a new, empty `authUsers` set, because `authUsers` represents the union of all users who have executed this query for a given interval. If we use the same interval, then `authUsers` will include both users.

More broadly speaking, testing with a new interval makes sure that a user cannot read rows from the current statement summary that they are not authorized to access, even if they ran the same query in the past. (This is what the bug would have allowed, since it was effectively not resetting `authUsers` for new statement summaries.)

Comment (bb7133) [reply pkg/util/stmtsummary/statement_summary_test.go:1512]: Thanks, got it.

**Review by bb7133 — APPROVED** [review]
LGTM
