### PR TITLE
DXF: check the cause of `subtaskCtx` to decide the subtask state

### LINKED ISSUE #58827: import into failed after injection ddl owner network partition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、import into
2、injection ddl owner network partition
3、import into failed

### 2. What did you expect to see? (Required)
import into succeed

### 3. What did you see instead (Required)
import into failed

[2025-01-08 18:13:02] ###### start import into
[2025/01/08 18:14:01.469 +08:00] injection ddl owner network partition lasts for 3mins
[2025/01/08 18:17:01.471 +08:00]  recover fault
[2025-01-08 18:18:02] import into failed

task-id=120007

[tidb-0.log.zip](https://github.com/user-attachments/files/18358146/tidb-0.log.zip)
[tidb-1.log.zip](https://github.com/user-attachments/files/18358151/tidb-1.log.zip)

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v9.0.0-alpha-65-gd1ed962
Edition: Community
Git Commit Hash: d1ed962f95f862696b0837cd1eb67c1ab3ce5173
Git Branch: HEAD
UTC Build Time: 2025-01-08 06:04:38
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2025-01-08T18:12:54.336+0800

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #58827

Problem Summary:

See https://github.com/pingcap/tidb/issues/58827#issuecomment-2582290429

### What changed and how does it work?

1. check `subtaskCtx` instead of `stepCtx` in `markSubTaskCanceledOrFailed`
2. ~~remove `checkCtx` since we introduced `subtaskCtx`~~

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 1]
```diff
@@ -443,23 +447,25 @@ func (e *BaseTaskExecutor) runSubtask(subtask *proto.Subtask) (resErr error) {
...
 			checkCancel()
 			wg.Wait()
-			subtaskCtxCancel()
 		}()
 		return e.stepExec.RunSubtask(subtaskCtx, subtask)
 	}()
-	failpoint.InjectCall("afterRunSubtask", e, &subtaskErr)
+	defer func() {
+		subtaskCancel()
+	}()
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:455]:
```suggestion
	defer subtaskCancel()
```

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 2]
```diff
@@ -566,7 +572,7 @@ func (e *BaseTaskExecutor) markSubTaskCanceledOrFailed(ctx context.Context, subt
 			return e.updateSubtaskStateAndErrorImpl(e.ctx, subtask.ExecID, subtask.ID, proto.SubtaskStateCanceled, nil)
 		}
 
-		e.logger.Info("meet context canceled for gracefully shutdown")
+		e.logger.Info("meet context canceled for gracefully shutdown", zap.Error(ctx.Err()))
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:575]:
```suggestion
		e.logger.Info("meet context canceled for gracefully shutdown")
```
no need to print it again, the message already says about it

File: tests/realtikvtest/addindextest1/disttask_test.go [hunk 3]
```diff
@@ -433,6 +433,14 @@ func TestAddIndexScheduleAway(t *testing.T) {
...
+	var subtaskCtx context.Context
+	testfailpoint.EnableCall(t, "github.com/pingcap/tidb/pkg/disttask/framework/taskexecutor/afterRunSubtask",
+		func(_ taskexecutor.TaskExecutor, _ *error, ctx context.Context) {
+			subtaskCtx = ctx
+		},
+	)
 	tk.MustExec("alter table t add index idx(b);")
 	require.NotEqual(t, int64(0), jobID.Load())
+	require.Error(t, subtaskCtx.Err())
+	require.Equal(t, context.Canceled, context.Cause(subtaskCtx))
```
Comment (D3Hunter) [inline tests/realtikvtest/addindextest1/disttask_test.go:445]: this check is always true due to the `defer`

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 4]
```diff
@@ -425,14 +425,18 @@ func (e *BaseTaskExecutor) runSubtask(subtask *proto.Subtask) (resErr error) {
...
 	logger := e.logger.With(zap.Int64("subtaskID", subtask.ID), zap.String("step", proto.Step2Str(subtask.Type, subtask.Step)))
 	logTask := llog.BeginTask(logger, "run subtask")
+	var (
+		subtaskCtx    context.Context
+		subtaskCancel context.CancelFunc
+	)
 	subtaskErr := func() error {
 		e.currSubtaskID.Store(subtask.ID)
-		subtaskCtx, subtaskCtxCancel := context.WithCancel(e.stepCtx)
+		subtaskCtx, subtaskCancel = context.WithCancel(e.stepCtx)
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:434]:
```suggestion
```

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 5]
```diff
@@ -425,14 +425,18 @@ func (e *BaseTaskExecutor) runSubtask(subtask *proto.Subtask) (resErr error) {
 
 	logger := e.logger.With(zap.Int64("subtaskID", subtask.ID), zap.String("step", proto.Step2Str(subtask.Type, subtask.Step)))
 	logTask := llog.BeginTask(logger, "run subtask")
+	var (
+		subtaskCtx    context.Context
+		subtaskCancel context.CancelFunc
+	)
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:431]:
```suggestion
		subtaskCtx, subtaskCancel := context.WithCancel(e.stepCtx)
```

**Review by tangenta — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]
