### PR TITLE
infoschema: fix schema and data mismatch for TIDB_SERVERS_INFO

### LINKED ISSUE #59245: Wrong column content in INFORMATION_SCHEMA.TIDB_SERVERS_INFO
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

start a TiDB with

```toml
labels = { zone = "us-west-1", dc = "dc1", rack = "rack1", host = "tidb1" }
```

### 2. What did you expect to see? (Required)

```
mysql> select * from INFORMATION_SCHEMA.TIDB_SERVERS_INFO\G
*************************** 1. row ***************************
       DDL_ID: f6c64fdc-d4fe-4268-bbcc-fea3fcf46054
           IP: 2408:8207:1857:3610:4a5:de9e:e383:2cfb
         PORT: 4000
  STATUS_PORT: 10080
        LEASE: 45s
      VERSION: 8.0.11-TiDB-v9.0.0-alpha-197-g43f2fb91d7
     GIT_HASH: 43f2fb91d740aaf45774d99b71554eead12009cc
       LABELS: dc=dc1,host=tidb1,rack=rack1,zone=us-west-1
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from INFORMATION_SCHEMA.TIDB_SERVERS_INFO\G
*************************** 1. row ***************************
       DDL_ID: f6c64fdc-d4fe-4268-bbcc-fea3fcf46054
           IP: 2408:8207:1857:3610:4a5:de9e:e383:2cfb
         PORT: 4000
  STATUS_PORT: 10080
        LEASE: 45s
      VERSION: 8.0.11-TiDB-v9.0.0-alpha-197-g43f2fb91d7
     GIT_HASH: 43f2fb91d740aaf45774d99b71554eead12009cc
BINLOG_STATUS: dc=dc1,host=tidb1,rack=rack1,zone=us-west-1
       LABELS:
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #59245

Problem Summary:

### What changed and how does it work?

as title

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by joccau — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

File: pkg/executor/infoschema_reader_test.go [hunk 1]
```diff
@@ -385,7 +394,7 @@ func TestForServersInfo(t *testing.T) {
 	require.Equal(t, info.Lease, rows[0][4])
 	require.Equal(t, info.Version, rows[0][5])
 	require.Equal(t, info.GitHash, rows[0][6])
-	require.Equal(t, stringutil.BuildStringFromLabels(info.Labels), rows[0][8])
+	require.Equal(t, "dc=dc1", rows[0][7])
```
Comment (dveeden) [inline pkg/executor/infoschema_reader_test.go:397]: @lance6716  Can we get the column by name instead of by number? That might be a better test for this issue.

Comment (lance6716) [reply pkg/executor/infoschema_reader_test.go:397]: seems that the TestKit utils we used in unit tests does not return column names.

Comment (dveeden) [reply pkg/executor/infoschema_reader_test.go:397]: While the `Result` doesn't have the fields, the `sqlexec.RecordSet` does. Maybe we can do it like this:
https://github.com/pingcap/tidb/pull/59259
