### PR TITLE
disttask: fix subtask cannot resume after upgrade

### LINKED ISSUE #50894: add index dist task can't resume after upgrade cluster
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a 7.5.0 cluster
2. set global tidb_ddl_enable_fast_reorg=1;  set global tidb_enable_dist_task=1
3. do add index
4. duraing add index, upgrade the cluster to nightly (134d2bfbe0002b2417715587)
5. check the add index ddl jobs

### 2. What did you expect to see? (Required)
ddl job will continue and add index success
### 3. What did you see instead (Required)
add index subtask in `paused` state and ddl jobs in `running` jobs for a long time
```sql
MySQL [(none)]> select id, task_key, type, state, step, exec_id, create_time, from_unixtime(start_time), end_time, cast(error as char) from mysql.tidb_background_subtask;
+----+----------+------+--------+------+------------------+-------------+---------------------------+----------+---------------------+
| id | task_key | type | state  | step | exec_id          | create_time | from_unixtime(start_time) | end_time | cast(error as char) |
+----+----------+------+--------+------+------------------+-------------+---------------------------+----------+---------------------+
|  4 | 2        |    0 | paused |    1 | tidb-3-peer:4000 | NULL        | 2024-02-01 15:54:04       | NULL     | NULL                |
|  5 | 2        |    0 | paused |    1 | tidb-2-peer:4000 | NULL        | 2024-02-01 15:54:05       | NULL     | NULL                |
|  6 | 2        |    0 | paused |    1 | tidb-2-peer:4000 | NULL        | 2024-02-01 15:54:05       | NULL     | NULL                |
+----+----------+------+--------+------+------------------+-------------+---------------------------+----------+---------------------+
3 rows in set (0.00 sec)

MySQL [(none)]> admin show ddl jobs;
+--------+---------+---------------------------------+---------------------------+----------------------+-----------+-----------------+-----------+---------------------+---------------------+---------------------+----------+
| JOB_ID | DB_NAME | TABLE_NAME                      | JOB_TYPE                  | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID        | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE    |
+--------+---------+---------------------------------+---------------------------+----------------------+-----------+-----------------+-----------+---------------------+---------------------+---------------------+----------+
|    256 | sbtest1 | sbtest4                         | add index /* ingest */    | write reorganization |       102 |             225 |         0 | 2024-02-01 15:51:00 | 2024-02-01 15:54:03 | NULL                | running  |
|    257 | sbtest1 | sbtest1                         | add index /* txn */       | write only           |       102 |             242 |         0 | 2024-02-01 15:51:00 | 2024-02-01 15:54:33 | NULL                | running  |
|    258 | sbtest1 | sbtest3                         | add index                 | none                 |       102 |             228 |         0 | 2024-02-01 15:51:00 | 2024-02-01 15:54:33 | NULL                | queueing |
|    259 | sbtest1 | sbtest5                         | add index                 | none                 |       102 |             226 |         0 | 2024-02-01 15:51:00 | 2024-02-01 15:54:33 | NULL                | queueing |
```
### 4. What is your TiDB version? (Required)
v7.5.0 -> nightly (134d2bfbe0002b2417715587)

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #50894

Problem Summary: See https://github.com/pingcap/tidb/issues/50894#issuecomment-1922695857

```sql
mysql> select id, state, exec_id from mysql.tidb_background_subtask;
+----+--------+----------------------------------------------+
| id | state  | exec_id                                      |
+----+--------+----------------------------------------------+
|  1 | paused | tc-tidb-0.tc-tidb-peer.tidb-cluster.svc:4000 |
+----+--------+----------------------------------------------+
1 row in set (0.00 sec)

mysql> select id, task_key, step, state, concurrency from mysql.tidb_global_task;

+----+------------------+------+----------+-------------+
| id | task_key         | step | state    | concurrency |
+----+------------------+------+----------+-------------+
|  1 | ddl/backfill/104 |    1 | resuming |          16 |
+----+------------------+------+----------+-------------+
1 row in set (0.00 sec)
```

### What changed and how does it work?

Change the task concurrency to a max value supported by current cluster during upgrade.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  https://github.com/tangenta/dbtool/blob/main/cases/issue_50894.go
  After this PR:
  ```
  curl -X POST http://127.0.0.1:10080/upgrade/finish
  ```
  ```sql
  mysql> select id, state, concurrency from mysql.tidb_global_task_history;
  +----+---------+-------------+
  | id | state   | concurrency |
  +----+---------+-------------+
  |  1 | succeed |           8 |
  +----+---------+-------------+
  1 row in set (0.00 sec)
  ```
  ```sql
  mysql> admin show ddl jobs 100 where job_id = 104;
  +--------+---------+------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
  | JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE               | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
  +--------+---------+------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
  |    104 | test    | t          | add index /* ingest */ | public       |         2 |      102 |  10000000 | 2024-02-18 07:29:47 | 2024-02-18 07:29:47 | 2024-02-18 07:38:28 | synced |
  +--------+---------+------------+------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
  1 row in set (0.01 sec)
  ```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/session/sync_upgrade.go [hunk 1]
```diff
@@ -95,6 +97,13 @@ func SyncNormalRunning(s sessionctx.Context) error {
 		logger.Warn("resume the job failed", zap.Error(e))
 	}
 
+	if mgr, _ := dist_store.GetTaskManager(); mgr != nil {
+		err := mgr.AdjustTaskOverflowConcurrency(context.Background(), s)
```
Comment (zimulala) [inline pkg/session/sync_upgrade.go:101]: Will the upgraded server have less than 16 CPU cores but not the server executing the function of `SyncNormalRunning`? In addition, this concurrency has not been written to the `tidb_background_subtask`, so it cannot be determined in `AdjustTaskOverflowConcurrency`.

Comment (tangenta) [reply pkg/session/sync_upgrade.go:101]: We assume that all TiDB servers have the same specs...

Because `tidb_background_subtask` does not have this field in v7.5, there is no problem.

**Review by zimulala — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]
