### PR TITLE
*: in prepared statement limit/offset may be placeholder

### LINKED ISSUE #2180: Limit and Offset not work
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

using go mysql driver `github.com/go-sql-driver/mysql`

sql: `select id from x LIMIT 10 OFFSET 5`

or

sql: `select id from x LIMIT 5,10`

2. What did you expect to see?

10 results returns

3. What did you see instead?

15 results returns (But I run that command in mysql client, it works. Did I missing something?)

4. What version of Go are you using (`go version`)?

go 1.7.4

### PR DESCRIPTION
**Pull request by shenli**
Fix #2180 
In prepareed statement,  limit/offset may be placeholder:
prepare stmt_test_1 from 'select id from prepare_test limit ? offset ?'

### CODE REVIEW

File: plan/logical_plan_builder.go [hunk 1]
```diff
@@ -419,10 +421,43 @@ func (b *planBuilder) buildSort(p LogicalPlan, byItems []*ast.ByItem, aggMapper
...
+	return 0, errors.Errorf("Invalid type %T for Limit/Offset", val)
+}
+
 func (b *planBuilder) buildLimit(src LogicalPlan, limit *ast.Limit) LogicalPlan {
+	var (
+		offset, count uint64
+		err           error
+	)
+	if limit.Offset != nil {
+		offset, err = getUintForLimitOffset(limit.Offset.GetValue())
```
Comment (hanfei1991) [inline plan/logical_plan_builder.go]: How about using evalAstExpr?

Comment (shenli) [inline plan/logical_plan_builder.go]: This expr must be ConstExpr and its real value must be unsigned int.

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
@hanfei1991 PTAL

**Comment by hanfei1991** [comment]
mysql> prepare ppp from "select * from t limit ?";

mysql> set @a = 1.1;
Query OK, 0 rows affected (0.00 sec)

mysql> execute ppp using @a;
+------+------+
| c1   | c2   |
+------+------+
|    1 |    1 |
+------+------+
1 row in set (0.00 sec)

**Comment by shenli** [comment]
@hanfei1991 PTAL
