### PR TITLE
expression, util: add `KeyWithoutTrimRightSpace` for collator

### LINKED ISSUE #35451: String function `position()` treats space to 2 chars
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
select position('world' in 'hello,world');
select position('world' in 'hello world');
```

### 2. What did you expect to see? (Required)

In MySQL:

```sql
+------------------------------------+
| position('world' in 'hello,world') |
+------------------------------------+
| 7                                  |
+------------------------------------+

1 row in set
Time: 0.032s

+------------------------------------+
| position('world' in 'hello world') |
+------------------------------------+
| 7                                  |
+------------------------------------+

1 row in set
Time: 0.008s
```

### 3. What did you see instead (Required)

In TiDB:

```sql
+------------------------------------+
| position('world' in 'hello,world') |
+------------------------------------+
| 7                                  |
+------------------------------------+

1 row in set
Time: 0.007s

+------------------------------------+
| position('world' in 'hello world') |
+------------------------------------+
| 8                                  |
+------------------------------------+

1 row in set
Time: 0.003s
```

### 4. What is your TiDB version? (Required)

```sql
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 5.7.25-TiDB-v6.2.0-alpha-101-gb91bdd087 |
+-----------------------------------------+
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #35451

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by tangenta — APPROVED** [review]

File: expression/util.go [hunk 1]
```diff
@@ -560,7 +560,7 @@ func locateStringWithCollation(str, substr, coll string) int64 {
 	for {
```
Comment (likzn) [inline expression/util.go:560]: Hi, may i ask. What is the effect of this loop? Can we return below code directly?
```
index := bytes.Index(strKey, subStrKey)
	return int64(index + 1)
```

File: util/collate/pinyin_tidb_as_cs.go [hunk 2]
```diff
@@ -28,6 +28,11 @@ func (py *zhPinyinTiDBASCSCollator) Key(str string) []byte {
 	panic("implement me")
 }
 
+// Collator interface, no implements now.
+func (py *zhPinyinTiDBASCSCollator) KeyWithoutTrimRightSpace(str string) []byte {
```
Comment (xiongjiwei) [inline util/collate/pinyin_tidb_as_cs.go:32]: let me remove it

File: expression/util.go [hunk 3]
```diff
@@ -560,7 +560,7 @@ func locateStringWithCollation(str, substr, coll string) int64 {
...
 		r, size := utf8.DecodeRuneInString(str)
 		count += 1
-		index -= len(collator.Key(string(r)))
+		index -= len(collator.KeyWithoutTrimRightSpace(string(r)))
 		if index == 0 {
```
Comment (xiongjiwei) [inline expression/util.go:564]: better change it to 
```suggestion
		if index <= 0 {
```

File: expression/util.go (hunk 1 above)
Comment (xiongjiwei) [reply expression/util.go:560]: no, some of the characters has more than one byte `weight`

File: expression/util.go (hunk 3 above)
Comment (Defined2014) [reply expression/util.go]: Done PTAL @xiongjiwei

**Review by xiongjiwei — APPROVED** [review]
