### PR TITLE
expression: fix compatibility behaviors in zero datetime with MySQL

### LINKED ISSUE #9728: `dayofmonth` `month` `quarter` and `year` are not compatible with Mysql
## Description
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select year(0000-00-00),year("0000-00-00");
select dayofmonth(0000-00-00), dayofmonth("0000-00-00");
select month(0000-00-00), month("0000-00-00");
select quarter(0000-00-00), quarter("0000-00-00");
select extract(MONTH FROM 0000-00-00), extract(MONTH FROM "0000-00-00");
```

2. What did you expect to see?
In Mysql
```
mysql> select year(0000-00-00),year("0000-00-00");
+------------------+--------------------+
| year(0000-00-00) | year("0000-00-00") |
+------------------+--------------------+
|                0 |               NULL |
+------------------+--------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select dayofmonth(0000-00-00), dayofmonth("0000-00-00");
+------------------------+--------------------------+
| dayofmonth(0000-00-00) | dayofmonth("0000-00-00") |
+------------------------+--------------------------+
|                      0 |                     NULL |
+------------------------+--------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select month(0000-00-00), month("0000-00-00");
+-------------------+---------------------+
| month(0000-00-00) | month("0000-00-00") |
+-------------------+---------------------+
|                 0 |                NULL |
+-------------------+---------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select quarter(0000-00-00), quarter("0000-00-00");
+---------------------+-----------------------+
| quarter(0000-00-00) | quarter("0000-00-00") |
+---------------------+-----------------------+
|                   0 |                  NULL |
+---------------------+-----------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select extract(MONTH FROM 0000-00-00), extract(MONTH FROM "0000-00-00");
+--------------------------------+----------------------------------+
| extract(MONTH FROM 0000-00-00) | extract(MONTH FROM "0000-00-00") |
+--------------------------------+----------------------------------+
|                              0 |                             NULL |
+--------------------------------+----------------------------------+
1 row in set, 1 warning (0.00 sec)
```


3. What did you see instead?
In TiDB
```
mysql> select year(0000-00-00),year("0000-00-00");
+------------------+--------------------+
| year(0000-00-00) | year("0000-00-00") |
+------------------+--------------------+
|             NULL |               NULL |
+------------------+--------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select dayofmonth(0000-00-00), dayofmonth("0000-00-00");
+------------------------+--------------------------+
| dayofmonth(0000-00-00) | dayofmonth("0000-00-00") |
+------------------------+--------------------------+
|                   NULL |                     NULL |
+------------------------+--------------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select month(0000-00-00), month("0000-00-00");
+-------------------+---------------------+
| month(0000-00-00) | month("0000-00-00") |
+-------------------+---------------------+
|              NULL |                NULL |
+-------------------+---------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select quarter(0000-00-00), quarter("0000-00-00");
+---------------------+-----------------------+
| quarter(0000-00-00) | quarter("0000-00-00") |
+---------------------+-----------------------+
|                NULL |                  NULL |
+---------------------+-----------------------+
1 row in set, 2 warnings (0.00 sec)

mysql> select extract(MONTH FROM 0000-00-00), extract(MONTH FROM "0000-00-00");
ERROR 1292 (22007): invalid time format: '{0 0 0 0 0 0 0}'
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.0-beta-212-g0681b8125
Git Commit Hash: 0681b8125080045ee0d4747ce61923164c6f2dd1
Git Branch: master
UTC Build Time: 2019-03-14 04:39:19
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```




## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @SunRunAway

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #9728

### What is changed and how it works?

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- fix compatibility behaviors in zero datetime with MySQL.

### CODE REVIEW

**Review by ichn-hu — APPROVED** [review]
LGTM

File: executor/executor_test.go [hunk 1]
```diff
@@ -7002,6 +7002,33 @@ func (s *testSuite) TestIssue20305(c *C) {
...
+		`select EXTRACT(YEAR FROM 0000-00-00), EXTRACT(YEAR FROM "0000-00-00")`,
+		`select EXTRACT(WEEK FROM 0000-00-00), EXTRACT(WEEK FROM "0000-00-00")`,
+		`select EXTRACT(QUARTER FROM 0000-00-00), EXTRACT(QUARTER FROM "0000-00-00")`,
+	}
+
+	store, err := mockstore.NewMockStore()
+	c.Assert(err, IsNil)
+	_, err = session.BootstrapSession(store)
+	c.Assert(err, IsNil)
+	tk := testkit.NewTestKit(c, store)
```
Comment (wshwsh12) [inline executor/executor_test.go:7024]: Use `s.store` directly?

File: expression/builtin_time.go [hunk 2]
```diff
@@ -1079,6 +1079,15 @@ func (b *builtinMonthSig) evalInt(row chunk.Row) (int64, bool, error) {
 
 	if date.IsZero() {
 		if b.ctx.GetSessionVars().SQLMode.HasNoZeroDateMode() {
+			// MySQL compatibility, #11203
```
Comment (wshwsh12) [inline expression/builtin_time.go:1082]: Can the code extract a new function?

**Review by wshwsh12 — COMMENTED** [review]
I think vectorized code should also be modified.

**Review by wshwsh12 — COMMENTED** [review]
(b *builtinExtractDatetimeSig) vecEvalInt should also be modified.

**Comment by lzmhhh123** [comment]
> builtinExtractDatetimeSig

No, `builtinExtractDatetimeSig` has another implementation. And it's right.

**Comment by wshwsh12** [comment]
lgtm

**Review by ti-srebot — APPROVED** [review]
