### PR TITLE
executor: fix IndexMerge handle panic logic

### LINKED ISSUE #41047: tidb panic when query is canceled because of oom
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://github.com/pingcap/tidb/blob/15bac9ea91615c3708df1d84383d213e7cfb605d/executor/index_merge_reader.go#L743-L749

processWorker close resultCh when return.

https://github.com/pingcap/tidb/blob/15bac9ea91615c3708df1d84383d213e7cfb605d/executor/index_merge_reader.go#L1030-L1036

partialIndexWorker/partialTableWorker write resultCh when got error. (In this case, we got: `[2023/02/03 19:04:31.629 +08:00] [ERROR] [index_merge_reader.go:1004] [IndexMergeReaderExecutor.syncErr] [error="Out Of Memory Quota![conn_id=2699305444236591507]"]`)

So if processWorker close resultCh, then partialIndexWorker tries to write error msg, will got "write to closed channel panic".
### 1. Minimal reproduce step (Required)
1. load data using lightning, dataset too large to upload. (ask me if you want to reproduce).
2. run sql as following:

```
set tidb_mem_quota_query = 10<<20;
set tidb_mem_quota_query = 10<<20;
explain analyze select /*+ use_index_merge(tp2) */ * from tp2 where a < 40000000 or b < 40000000;
```

### 2. What did you expect to see? (Required)
runs ok.
### 3. What did you see instead (Required)
tidb crash.

```
panic: send on closed channel [recovered]
        panic: send on closed channel

goroutine 10650 [running]:
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).handleHandlesFetcherPanic.func1({0x4410c20, 0x50a41d0})
        /home/xhy/gjt_data/tidb/executor/index_merge_reader.go:712 +0x1aa
github.com/pingcap/tidb/util.WithRecovery.func1()
        /home/xhy/gjt_data/tidb/util/misc.go:88 +0x58
panic({0x4410c20, 0x50a41d0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/pingcap/tidb/executor.syncErr(...)
        /home/xhy/gjt_data/tidb/executor/index_merge_reader.go:1006
github.com/pingcap/tidb/executor.(*partialIndexWorker).fetchHandles(0xc047f0be48, {0x50d4988, 0xc08441f800}, {0x50cb9f0, 0xc074dae690}, 0xc004446d80, 0xc004446de0, 0x40?, 0xc004446d20, {0x50f4660, ...}, ...)
        /home/xhy/gjt_data/tidb/executor/index_merge_reader.go:1033 +0x5ea
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startPartialIndexWorker.func2.1()
        /home/xhy/gjt_data/tidb/executor/index_merge_reader.go:371 +0x945
github.com/pingcap/tidb/util.WithRecovery(0x50d4a30?, 0x50d4a30?)
        /home/xhy/gjt_data/tidb/util/misc.go:96 +0x53
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startPartialIndexWorker.func2()
        /home/xhy/gjt_data/tidb/executor/index_merge_reader.go:304 +0x1e7
created by github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startPartialIndexWorker
        /home/xhy/gjt_data/tidb/executor/index_merge_reader.go:301 +0x28c
```

```
[2023/02/03 18:55:16.362 +08:00] [ERROR] [index_merge_reader.go:1146] ["panic in IndexMergeReaderExecutor indexMergeTableWorker: Out Of Memory Quota![conn_id=8433441102018642323]"] [conn=8433441102018642323]
[2023/02/03 18:55:16.362 +08:00] [ERROR] [misc.go:91] ["panic in the recoverable goroutine"] [r="\"Out Of Memory Quota![conn_id=8433441102018642323]\""] ["stack trace"="github.com/pingcap/tidb/util.WithRecovery.func1\n\t/home/xhy/gjt_data/tidb/util/misc.go:93\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/xhy/gjt_data/tidb/util/memory/action.go:148\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:437\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:478\ngithub.com/pingcap/tidb/executor.(*indexMergeTableScanWorker).executeTask\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:1182\ngithub.com/pingcap/tidb/executor.(*indexMergeTableScanWorker).pickAndExecTask\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:1128\ngithub.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startIndexMergeTableScanWorker.func1.1\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:620\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/home/xhy/gjt_data/tidb/util/misc.go:96\ngithub.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startIndexMergeTableScanWorker.func1\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:614"]
[2023/02/03 18:55:16.384 +08:00] [ERROR] [index_merge_reader.go:1146] ["panic in IndexMergeReaderExecutor indexMergeTableWorker: Out Of Memory Quota![conn_id=8433441102018642323]"] [conn=8433441102018642323]
[2023/02/03 18:55:16.384 +08:00] [ERROR] [misc.go:91] ["panic in the recoverable goroutine"] [r="\"Out Of Memory Quota![conn_id=8433441102018642323]\""] ["stack trace"="github.com/pingcap/tidb/util.WithRecovery.func1\n\t/home/xhy/gjt_data/tidb/util/misc.go:93\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/xhy/gjt_data/tidb/util/memory/action.go:148\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:437\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:478\ngithub.com/pingcap/tidb/executor.(*indexMergeTableScanWorker).executeTask\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:1182\ngithub.com/pingcap/tidb/executor.(*indexMergeTableScanWorker).pickAndExecTask\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:1128\ngithub.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startIndexMergeTableScanWorker.func1.1\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:620\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/home/xhy/gjt_data/tidb/util/misc.go:96\ngithub.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startIndexMergeTableScanWorker.func1\n\t/home/xhy/gjt_data/tidb/executor/index_merge_reader.go:614"]
[2023/02/03 18:55:16.384 +08:00] [ERROR] [coprocessor.go:995] ["copIteratorWork meet panic"] [r="\"Out Of Memory Quota![conn_id=8433441102018642323]\""] ["stack trace"="github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask.func1\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:997\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/xhy/gjt_data/tidb/util/memory/action.go:148\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:437\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:478\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:885\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopResponse\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1333\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopPagingResult\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1189\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTaskOnce\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1128\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1008\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).run\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:718"]
[2023/02/03 18:55:16.384 +08:00] [ERROR] [coprocessor.go:995] ["copIteratorWork meet panic"] [r="\"Out Of Memory Quota![conn_id=8433441102018642323]\""] ["stack trace"="github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask.func1\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:997\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/xhy/gjt_data/tidb/util/memory/action.go:148\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:437\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/xhy/gjt_data/tidb/util/memory/tracker.go:478\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:885\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopResponse\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1333\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopPagingResult\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1189\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTaskOnce\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1128\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:1008\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).run\n\t/home/xhy/gjt_data/tidb/store/copr/coprocessor.go:718"]
[2023/02/03 18:55:16.384 +08:00] [ERROR] [index_merge_reader.go:709] ["panic in IndexMergeReaderExecutor partialIndexWorker: send on closed channel"] [conn=8433441102018642323]
[2023/02/03 18:55:31.970 +08:00] [INFO] [cpuprofile.go:113] ["parallel cpu profiler started"]
```
### 4. What is your TiDB version? (Required)
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()
                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.6.0-alpha-262-g8ec2612-dirty
Edition: Community
Git Commit Hash: 8ec2612ba2315592d25d55d54f93a7ecd6bb1e6b
Git Branch: HEAD
UTC Build Time: 2023-02-03 06:51:26
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by guo-shaoge**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and 
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: close #41047

Problem Summary:
There are five kinds of workers in IndexMergeReaderExecutor:
1. partialIndexWorker/partialTableWorker: get handles from rows, then send handles to processWorker.
2. processWorker: do Union or Intersection of handles., then send handles to tableScanWorker. Also it send task to main goroutine using **resultCh**.
3. tableScanWorker: fetch row from tikv using handles, then send rows to main goroutine
4. partTblIntersectionWorker: For dynamic partition table, for each partition, start a goroutine to do intersection. This is to speed up intersection processing.
5. main goroutine: wait for tableScanWorker to get rows.

Why panic:
1. processWorker finish, so it close **resultCh**. [code](https://github.com/pingcap/tidb/blob/master/executor/index_merge_reader.go#L747)
2. partialIndexWorker got error, then try to send error using **resultCh**. [code](https://github.com/pingcap/tidb/blob/master/executor/index_merge_reader.go#L1033)
3. got write to closed channel panic.

### What is changed and how it works?
1. partialIndexWorker/partialTableWorker should not use **resultCh** to send error. Instead should use **fetchCh**, which is used to send task to processWorker.
2. processWorker should check err in task, which is received from **fetchCh**. If got error, just stop processing.
3. add **handleIntersectionProcessWorkerPanic()**, which is similar to **handleLoopFetcherPanic**. The latter will **close(resultCh)** when return.
### Check List

Tests <!-- At least one of them must be included. -->

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
  1. load data using lighning, too large to upload
  2. run sql as follows, and tidb doesn't crash when SQL is canceled because oom.
```
use s11_indexmerge_test;

set global tidb_server_memory_limit="500MB";
explain analyze select /*+ use_index_merge(tp2) */ * from tp2 where a < 40000000 or b < 40000000;
explain analyze select /*+ use_index_merge(tp2, ia, ib) */ * from tp2 where a < 40000000 and b < 40000000;

set tidb_mem_quota_query = 1000;
explain analyze select /*+ use_index_merge(tp2) */ * from tp2 where a < 40000000 or b < 40000000;
explain analyze select /*+ use_index_merge(tp2, ia, ib) */ * from tp2 where a < 40000000 and b < 40000000;

set tidb_mem_quota_query = 10<<20;
explain analyze select /*+ use_index_merge(tp2) */ * from tp2 where a < 40000000 or b < 40000000;
explain analyze select /*+ use_index_merge(tp2, ia, ib) */ * from tp2 where a < 40000000 and b < 40000000;

set tidb_mem_quota_query = 500<<20;
explain analyze select /*+ use_index_merge(tp2) */ * from tp2 where a < 40000000 or b < 40000000;
explain analyze select /*+ use_index_merge(tp2, ia, ib) */ * from tp2 where a < 40000000 and b < 40000000;
                                                                                                                                                                                                                                                            set tidb_mem_quota_query = 1<<30;
explain analyze select /*+ use_index_merge(tp2) */ * from tp2 where a < 40000000 or b < 40000000;
explain analyze select /*+ use_index_merge(tp2, ia, ib) */ * from tp2 where a < 40000000 and b < 40000000;

```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
executor: fix IndexMerge handle panic logic
```

### CODE REVIEW

File: executor/index_merge_reader_test.go [hunk 1]
```diff
@@ -797,3 +797,19 @@ func TestIntersectionMemQuota(t *testing.T) {
 	err := tk.QueryToErr("select /*+ use_index_merge(t1, primary, idx1, idx2) */ c1 from t1 where c1 < 1024 and c2 < 1024")
 	require.Contains(t, err.Error(), "Out Of Memory Quota!")
 }
+
+func TestIndexMergeResultChPanic(t *testing.T) {
```
Comment (windtalker) [inline executor/index_merge_reader_test.go:801]: maybe add more failpoint tests that simulate panic happens in the goroutine of all the kinds of workers?

Comment (guo-shaoge) [reply executor/index_merge_reader_test.go]: Done, Add 6 failpoints.

File: executor/index_merge_reader.go [hunk 2]
```diff
@@ -699,21 +735,29 @@ func (e *IndexMergeReaderExecutor) getResultTask() (*indexMergeTableTask, error)
...
 			},
 		}
+		select {
+		case <-ctx.Done():
+			return
+		case <-finished:
+			return
+		case ch <- task:
+			return
+		}
```
Comment (windtalker) [inline executor/index_merge_reader.go:760]: Looks most of the `handleXXXpanic` use the same code, can we reuse the code?

**Review by XuHuaiyu — APPROVED** [review]

File: executor/index_merge_reader.go (hunk 2 above)
Comment (guo-shaoge) [reply executor/index_merge_reader.go:777]: Done. processWorker/partialTableWorker/partialIndexWorker all use `handleWorkerPanic()`. tableScanWorker uses `handleTableScanWorkerPanic()`, because it sends err by task.doneCh instead of resultCh or fetchCh.

**Review by windtalker — APPROVED** [review]
LGTM
