### PR TITLE
ddl: no more sleep when meets nonRetryable error

### LINKED ISSUE #47455: DDL execute too slow when failed.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
create table t ( obj json, arr json, nil json, t json, f json, i json, ui json, f64 json, str json, nul json );
insert into t values ('{\"obj\": 100}', '[-1, 0, 1]', 'null', 'true', 'false', '20200826173501', '20201123', '20200826173501.123456', '\"2020-08-26 17:35:01.123456\"', null);
alter table t modify obj datetime;
```

### 2. What did you expect to see? (Required)

return error directly.

### 3. What did you see instead (Required)

Sleep 1s, then return error.

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.4.0-alpha-483-g9f4792b07c
Edition: Community
Git Commit Hash: 9f4792b07cc7c75f57653f691f3b1f115ff081b8
Git Branch: move-util
UTC Build Time: 2023-09-22 07:21:00
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: true
Store: unistore |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #47455

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

run SQL below,
```
create table t ( obj json, arr json, nil json, t json, f json, i json, ui json, f64 json, str json, nul json );
insert into t values ('{\"obj\": 100}', '[-1, 0, 1]', 'null', 'true', 'false', '20200826173501', '20201123', '20200826173501.123456', '\"2020-08-26 17:35:01.123456\"', null);
alter table t modify obj datetime;
```

`alter table` return error directly, no more sleep.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/ddl_worker.go [hunk 1]
```diff
@@ -836,11 +836,12 @@ func (w *worker) HandleDDLJobTable(d *ddlCtx, job *model.Job) (int64, error) {
 	w.registerSync(job)
 
 	if runJobErr != nil && !dbterror.ErrPausedDDLJob.Equal(runJobErr) {
-		// Omit the ErrPausedDDLJob
-		w.jobLogger(job).Info("run DDL job failed, sleeps a while then retries it.",
-			zap.Duration("waitTime", GetWaitTimeWhenErrorOccurred()), zap.Error(runJobErr))
 		// In test and job is cancelling we can ignore the sleep.
-		if !(intest.InTest && job.IsCancelling()) {
+		// Or error is non-Retryable.
+		if !(intest.InTest && job.IsCancelling()) && errorIsRetryable(runJobErr, job) {
```
Comment (zimulala) [inline ddl/ddl_worker.go:841]: Could we remove `job.IsCancelling()`?

Comment (Defined2014) [reply ddl/ddl_worker.go]: Done. This code also for speed up test before. https://github.com/pingcap/tidb/pull/41034

**Review by zimulala — APPROVED** [review]
LGTM

**Review by tangenta — APPROVED** [review]
