### PR TITLE
executor: fix wrong behavior for `max/min` on ENUM/SET column

### LINKED ISSUE #13961: Wrong behavior when `max(ENUM column)` in Aggregation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
mysql> create table t3(id int, en enum('b', 'a'));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t3 values (1, 'a'), (1, 'b');
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select max(en) from t3 group by id;
+---------+
| max(en) |
+---------+
| b       |
+---------+
1 row in set (0.00 sec)

mysql> select max(en) from t3;
+---------+
| max(en) |
+---------+
| a       |
+---------+
1 row in set (0.00 sec)
```

2. What did you expect to see?
```select max(en) from t3 group by id``` should return `a`, according to [mysql manual](https://dev.mysql.com/doc/refman/8.0/en/enum.html):

> Enumeration Sorting
> ENUM values are sorted based on their index numbers, which depend on the order in which the enumeration members were listed in the column specification. For example, 'b' sorts before 'a' for ENUM('b', 'a'). The empty string sorts before nonempty strings, and NULL values sort before all other enumeration values.


3. What did you see instead?
```
mysql> select max(en) from t3 group by id;
+---------+
| max(en) |
+---------+
| b       |
+---------+
1 row in set (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

current master [91b9071](https://github.com/pingcap/tidb/commit/a1b90715ee60c0ba0bf3b005b3475e1f931bcfe2)

```
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-alpha-1114-ga1b90715e
Git Commit Hash: a1b90715ee60c0ba0bf3b005b3475e1f931bcfe2
Git Branch: master
UTC Build Time: 2019-12-07 03:57:47
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> 
```

### PR DESCRIPTION
**Pull request by pingyu**
<!-- Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?

Issue Number: close #13961 <!-- REMOVE this line if no issue to close -->

Problem Summary:
`max`/`min` produces wrong result on ENUM & SET column.

### What is changed and how it works?

What's Changed:
Fix max/min implementation for ENUM/SET type.

How it Works:
Add max/min implementation for ENUM/SET type.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
No.
- Need to cherry-pick to the release branch
No.

### Check List <!--REMOVE the items that are not applicable-->

Tests <!-- At least one of them must be included. -->

- Unit test
- Manual test (add detailed scripts or steps below)
```sql
create table t3(id int, en enum('b', 'a'));
insert into t3 values (1, 'a'), (1, 'b');

mysql root@127.0.0.1:test> select max(en) from t3 group by id; 
                           select max(en) from t3; 
                                                                                                                                                                                                             
+---------+
| max(en) |
+---------+
| a       |
+---------+
1 row in set
Time: 0.014s

+---------+
| max(en) |
+---------+
| a       |
+---------+
1 row in set
Time: 0.013s
mysql root@127.0.0.1:test>                                                                                                                                                                                   
mysql root@127.0.0.1:test> select min(en) from t3 group by id; 
                           select min(en) from t3; 
                                                                                                                                                                                                             
+---------+
| min(en) |
+---------+
| b       |
+---------+
1 row in set
Time: 0.014s

+---------+
| min(en) |
+---------+
| b       |
+---------+
1 row in set
Time: 0.013s
```

```
create table t4(id int, f set('a', 'b', 'c'));
insert into t4 values(1, 'a'), (2, 'b'), (1, 'a,b,c');

mysql root@127.0.0.1:test> select max(f) from t4; 
                           select max(f) from t4 group by id; 
                                                                                                                                                                                                             
+--------+
| max(f) |
+--------+
| a,b,c  |
+--------+
1 row in set
Time: 0.014s

+--------+
| max(f) |
+--------+
| a,b,c  |
| b      |
+--------+
2 rows in set
Time: 0.013s

mysql root@127.0.0.1:test> select min(f) from t4; 
                           select min(f) from t4 group by id; 
                                                                                                                                                                                                             
+--------+
| min(f) |
+--------+
| a      |
+--------+
1 row in set
Time: 0.015s

+--------+
| min(f) |
+--------+
| a      |
| b      |
+--------+
2 rows in set
Time: 0.014s
```

Side effects
- MySQL Compatibility
MySQL produce MIN/MAX result on string value of ENUM/SET column, rather than index value. Which is in-consist with [manual](https://dev.mysql.com/doc/refman/5.7/en/enum.html), and considered as a [known issue](https://dev.mysql.com/doc/mysql-reslimits-excerpt/8.0/en/known-issues.html).
> In MIN(), MAX(), and other aggregate functions, MySQL currently compares ENUM and SET columns by their string value rather than by the string's relative position in the set.


### Release note <!-- bugfixes or new feature need a release note -->

- Fix wrong behavior for `max/min` on ENUM/SET column.

### CODE REVIEW

File: executor/aggfuncs/func_max_min.go [hunk 1]
```diff
@@ -657,3 +667,129 @@ func (e *maxMin4JSON) MergePartialResult(sctx sessionctx.Context, src, dst Parti
...
+func (e *maxMin4Enum) MergePartialResult(sctx sessionctx.Context, src, dst PartialResult) (memDelta int64, err error) {
+	p1, p2 := (*partialResult4MaxMinEnum)(src), (*partialResult4MaxMinEnum)(dst)
+	if p1.isNull {
+		return 0, nil
+	}
+	if p2.isNull {
+		*p2 = *p1
+		return 0, nil
+	}
+	if e.isMax && p1.val.Value > p2.val.Value || !e.isMax && p1.val.Value < p2.val.Value {
```
Comment (SunRunAway) [inline executor/aggfuncs/func_max_min.go:728]: Should `p1.val.Value > p2.val.Value` be dominated by collation?

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by winoros — APPROVED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
