### PR TITLE
planner: Fix expression rewriting and method signature mismatch in plan cache

### LINKED ISSUE #56772: ERROR 1105 (HY000): baseBuiltinFunc.vecEvalInt() should never be called
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table lrr_test( `COL1` tinyint(16),`COL3` bigint(20) DEFAULT NULL,KEY `UM_COL` (`COL1`,`COL3`));
insert into lrr_test(col3) values(-825024501864323944);
insert into lrr_test values(-2,2295421130981788987);
prepare stmt from 'select * from lrr_test t1 join lrr_test t2 on t1.col1 = t2.col1 where t1. col1 + 10 > ? + 10 or t2. col1 + 10 >= ? + 10;';
set @a=NULL, @b=-2;
execute stmt using @a,@b;
```

### 2. What did you expect to see? (Required)
Mysql:
+------+---------------------+------+---------------------+
| COL1 | COL3                | COL1 | COL3                |
+------+---------------------+------+---------------------+
|   -2 | 2295421130981788987 |   -2 | 2295421130981788987 |
+------+---------------------+------+---------------------+

### 3. What did you see instead (Required)
ERROR 1105 (HY000): baseBuiltinFunc.vecEvalInt() should never be called, please contact the TiDB team for help

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: 2205f332ffcf3553ffc49438cfe1087a0f08dd18
Git Branch: HEAD
UTC Build Time: 2024-10-17 07:36:44
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

### PR DESCRIPTION
**Pull request by dash12653**
### What problem does this PR solve?

Issue Number: close #56772

Problem Summary:

### What changed and how does it work?
In the `expression rewriting` process, when constructing the condition `t1.col1 + 10 > ? + 10`, the argument `? + 10` will go through `argument refinement`, and the final result is set to` NULL`. The type of NULL is determined as `int.` 
Then, the method signature for` t1.col1 + 10 > ? + 10` is set to `builtinArithmeticPlusIntSig`. But the `DeferredExpr` for the expression `plus(NULL, 10)` is not removed, which results in a conflict method signature of `builtinArithmeticPlusRealSig`, 
which cannot handle int types. This leads to an error during execution.

`RemoveMutableConst():` will not traverse all the expressions.
https://github.com/pingcap/tidb/blob/8ecdb54c51a156a40ad1c84215af424dc55add41/pkg/expression/util.go#L1583-L1602

I modified the code to ensure that all expressions are properly traversed and DeferredExpr would be removed.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by dash12653** [comment]
@qw4990 @AilinKid PTAL

**Comment by dash12653** [comment]
@qw4990 @AilinKid Hi, could you help to review this pr when you have a chance? Thanks!

File: pkg/expression/util.go [hunk 1]
```diff
@@ -1599,7 +1599,10 @@ func RemoveMutableConst(ctx BuildContext, exprs []Expression) (err error) {
 			}
 			v.DeferredExpr = nil // do nothing since v.Value has already been evaluated in this case.
 		case *ScalarFunction:
-			return RemoveMutableConst(ctx, v.GetArgs())
+			err := RemoveMutableConst(ctx, v.GetArgs())
```
Comment (AilinKid) [inline pkg/expression/util.go]: nice catch

**Review by AilinKid — APPROVED** [review]

**Comment by AilinKid** [comment]
sorry for didn't notice github notification for sometime, do you mind resolve conflict it runs into

**Comment by dash12653** [comment]
PTAL @AilinKid @qw4990

**Review by windtalker — APPROVED** [review]
lgtm
