### PR TITLE
chunk: fix min/max for enum/set is incompatible with MySQL

### LINKED ISSUE #21451: Aggregation `MIN/MAX` for `ENUM/SET` is incompatible with MySQL
## Bug Report

From MySQL manual https://dev.mysql.com/doc/refman/5.7/en/aggregate-functions.html#function_max:

> For MAX(), MySQL currently compares ENUM and SET columns by their string value rather than by the string's relative position in the set. This differs from how ORDER BY compares them.

### 1. Minimal reproduce step (Required)

```sql
create table t(en enum('c', 'b', 'a'));
insert into t values ('a'), ('b'), ('c');
select max(en) from t;
/*  
+---------+
| max(en) |
+---------+
| a       |
+---------+
*/
select min(en) from t;
/*
+---------+
| min(en) |
+---------+
| c       |
+---------+
*/
```

```sql
create table t2(s set('c', 'b', 'a'));
insert into t2 values ('a'), ('b'), ('c');
select max(s) from t2;
/*
+--------+
| max(s) |
+--------+
| a      |
+--------+
*/
 select min(s) from t2;
/*
+--------+
| min(s) |
+--------+
| c      |
+--------+
*/
```

### 2. What did you expect to see? (Required)

MySQL 5.7:

```sql
create table t(en enum('c', 'b', 'a'));
insert into t values ('a'), ('b'), ('c');
select max(en) from t;
/*  
+---------+
| max(en) |
+---------+
| c       |
+---------+
*/
select min(en) from t;
/*
+---------+
| min(en) |
+---------+
| a       |
+---------+
*/
```

```sql
create table t2(s set('c', 'b', 'a'));
insert into t2 values ('a'), ('b'), ('c');
select max(s) from t2;
/*
+--------+
| max(s) |
+--------+
| c      |
+--------+
*/
 select min(s) from t2;
/*
+--------+
| min(s) |
+--------+
| a      |
+--------+
*/
```

### 3. What is your TiDB version? (Required)

5723034c061711107ecc2edc0fbc97d366e8396e

### PR DESCRIPTION
**Pull request by StoneDotYang**
### What problem does this PR solve?

Issue Number: close #21451  

Problem Summary: Aggregation `MIN/MAX` for `ENUM/SET` is incompatible with MySQL

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
In sort.go file, add a function initCompareFuncs for TopNExec struct. then when type is mysql.TypeSet or mysql.TypeEnum,call the  genCmpNameValueFunc  with paramters collation is added to replace the original method cmpNameValue.

the function genCmpNameValueFunc return a handle func(l Row, lCol int, r Row, rCol int) int

How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- When applying the `MIN()`/`MAX()` aggregate function on an enum column, the string value is now used for comparison. This is required for MySQL compatibility.

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
- Thanks for your contribution. Is this PR ready to be reviewed?
- Please add some test case

**Comment by b41sh** [comment]
As `CompareFunc` is used both by `SortExec` and `TopNExec`, we can't modify `GetCompareFunc` directly. Maybe we can add a function like `GetCompareTopNFunc` to generate compare function for `TopNExec` seperately. And please add some test functions for this case.

**Comment by XuHuaiyu** [comment]
Add some test cases in `executor/executor_test.go`, we can add a function like `TestIssue21451`

**Comment by XuHuaiyu** [comment]
PTAL @b41sh

File: util/chunk/compare.go [hunk 1]
```diff
@@ -25,6 +25,16 @@ import (
 // CompareFunc is a function to compare the two values in Row, the two columns must have the same type.
 type CompareFunc = func(l Row, lCol int, r Row, rCol int) int
 
+// GetCompareTopNFunc get compare funcs by their string value For MAX()/Min() on ENUM and SET field type
```
Comment (b41sh) [inline util/chunk/compare.go:28]: how about modify comment as follow:
// GetCompareTopNFunc gets a compare function for the field type used by TopNExec
// as EnumSet field type is sorted by name in TopNExec, but by value in SortExec

File: executor/executor_test.go [hunk 2]
```diff
@@ -7141,3 +7141,21 @@ func (s *testSuite) Test15492(c *C) {
...
+func (s *testSuite) TestIssue21451(c *C) {
+	tk := testkit.NewTestKitWithInit(c, s.store)
+	tk.MustExec("drop table if exists t")
+	tk.MustExec("create table t (en enum('c', 'b', 'a'));")
+	tk.MustExec("insert into t values ('a'), ('b'), ('c');")
+	tk.MustQuery("select max(en) from t;").Check(testkit.Rows("c"))
+	tk.MustQuery("select min(en) from t;").Check(testkit.Rows("a"))
+	tk.MustQuery("select * from t order by en;").Check(testkit.Rows("c", "b", "a"))
+	tk.MustExec("drop table t")
+
```
Comment (b41sh) [inline executor/executor_test.go:7154]: We'd better move this blank line up one line.

**Comment by pingyu** [comment]
1. `MAX/MIN` for `SET` is implemented [here](https://github.com/pingcap/tidb/blob/ab9cd019be921b4d7ece3cca883b7cac7796e314/executor/aggfuncs/func_max_min.go#L1413). It is not related to `SORT`.

2. Result of `ORDER BY` on `SET` seems to be the same as mysql (compared on relative position in the set. Codes are [here](https://github.com/pingcap/tidb/blob/ab9cd019be921b4d7ece3cca883b7cac7796e314/util/chunk/compare.go#L49)). I think we don't need to modify `SortExec`/`TopNExec`

  * mysql
```sql
mysql> create table t5(en enum('c', 'b', 'a'));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t5 values ('a'), ('b'), ('c');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from t5 order by en;
+------+
| en   |
+------+
| c    |
| b    |
| a    |
+------+
3 rows in set (0.00 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.19    |
+-----------+
1 row in set (0.00 sec)
```

  * TiDB master:
```sql
mysql root@localhost:test> create table t5(en enum('c', 'b', 'a'));                                                                                                                                          
Query OK, 0 rows affected
Time: 0.006s
mysql root@localhost:test> insert into t5 values ('a'), ('b'), ('c');                                                                                                                                         
Query OK, 3 rows affected
Time: 0.005s
mysql root@localhost:test> select * from t5 order by en;                                                                                                                                                      
+----+
| en |
+----+
| c  |
| b  |
| a  |
+----+
3 rows in set
Time: 0.014s
mysql root@localhost:test> select tidb_version();                                                                                                                                                              
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1804-g06cd92e05                    |
| Edition: Community                                                |
| Git Commit Hash: 06cd92e05f0dfff1a139c1e5baca2ee24fb387b2         |
| Git Branch: master                                                |
| UTC Build Time: 2020-12-13 14:20:29                               |
| GoVersion: go1.13.8                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: true                                     |
+-------------------------------------------------------------------+
1 row in set
Time: 0.014s
mysql root@localhost:test>  
```

3. It seems that this issue is introduced by me (#19552) ...I'm so sorry...

**Comment by b41sh** [comment]
@pingyu  from explain info we can see that `StreamAgg` get chunk data from `TopNExec`.
Currently both `SortExec` and `TopNExec` use `initCompareFuncs()` to get compare function, but for `enum/set` field the behavior of `sort by` and `min/max` are diff, so we must modfiy `initCompareFuncs()`

```
mysql> explain select min(en) from t5;
+------------------------------+----------+-----------+---------------+---------------------------------+
| id                           | estRows  | task      | access object | operator info                   |
+------------------------------+----------+-----------+---------------+---------------------------------+
| StreamAgg_13                 | 1.00     | root      |               | funcs:min(test.t5.en)->Column#3 |
| └─TopN_16                    | 1.00     | root      |               | test.t5.en, offset:0, count:1   |
|   └─Selection_20             | 8000.00  | root      |               | not(isnull(test.t5.en))         |
|     └─TableReader_22         | 10000.00 | root      |               | data:TableFullScan_21           |
|       └─TableFullScan_21     | 10000.00 | cop[tikv] | table:t5      | keep order:false, stats:pseudo  |
+------------------------------+----------+-----------+---------------+---------------------------------+
5 rows in set (0.00 sec)
```

**Comment by pingyu** [comment]
Oh...I see.
But modification to `TopNExec` will affect `ORDER BY` too, which should be sorted by relative position.

BTW, `MAX`/`MIN` with `GROUP BY` clause doesn't have `TopN` executor.
```sql
mysql root@localhost:test> create table t6(id int, en enum('c', 'b', 'a'));                                                                                                                              
Query OK, 0 rows affected
Time: 0.023s
mysql root@localhost:test> explain select id, max(en) from t6 group by id;                                                                                                                               
+-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
| id                    | estRows  | task      | access object | operator info                                                                                |
+-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
| Projection_4          | 8000.00  | root      |               | test.t6.id, Column#4                                                                         |
| └─HashAgg_5           | 8000.00  | root      |               | group by:test.t6.id, funcs:max(test.t6.en)->Column#4, funcs:firstrow(test.t6.id)->test.t6.id |
|   └─TableReader_9     | 10000.00 | root      |               | data:TableFullScan_8                                                                         |
|     └─TableFullScan_8 | 10000.00 | cop[tikv] | table:t6      | keep order:false, stats:pseudo                                                               |
+-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
4 rows in set
Time: 0.011s
mysql root@localhost:test>  
```

**Comment by b41sh** [comment]
> Oh...I see.
> But modification to `TopNExec` will affect `ORDER BY` too, which should be sorted by relative position.
> 
> BTW, `MAX`/`MIN` with `GROUP BY` clause doesn't have `TopN` executor.
> 
> ```sql
> mysql root@localhost:test> create table t6(id int, en enum('c', 'b', 'a'));                                                                                                                              
> Query OK, 0 rows affected
> Time: 0.023s
> mysql root@localhost:test> explain select id, max(en) from t6 group by id;                                                                                                                               
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | id                    | estRows  | task      | access object | operator info                                                                                |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | Projection_4          | 8000.00  | root      |               | test.t6.id, Column#4                                                                         |
> | └─HashAgg_5           | 8000.00  | root      |               | group by:test.t6.id, funcs:max(test.t6.en)->Column#4, funcs:firstrow(test.t6.id)->test.t6.id |
> |   └─TableReader_9     | 10000.00 | root      |               | data:TableFullScan_8                                                                         |
> |     └─TableFullScan_8 | 10000.00 | cop[tikv] | table:t6      | keep order:false, stats:pseudo                                                               |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> 4 rows in set
> Time: 0.011s
> mysql root@localhost:test>  
> ```

ok, we also need to modify `maxMin4Enum` and `maxMin4Set`

**Comment by XuHuaiyu** [comment]
@StoneDotYang Do you have any problem addressing [this comment](https://github.com/pingcap/tidb/pull/21566#issuecomment-745044985)?

**Comment by StoneDotYang** [comment]
> Oh...I see.
> But modification to `TopNExec` will affect `ORDER BY` too, which should be sorted by relative position.
> 
> BTW, `MAX`/`MIN` with `GROUP BY` clause doesn't have `TopN` executor.
> 
> ```sql
> mysql root@localhost:test> create table t6(id int, en enum('c', 'b', 'a'));                                                                                                                              
> Query OK, 0 rows affected
> Time: 0.023s
> mysql root@localhost:test> explain select id, max(en) from t6 group by id;                                                                                                                               
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | id                    | estRows  | task      | access object | operator info                                                                                |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> | Projection_4          | 8000.00  | root      |               | test.t6.id, Column#4                                                                         |
> | └─HashAgg_5           | 8000.00  | root      |               | group by:test.t6.id, funcs:max(test.t6.en)->Column#4, funcs:firstrow(test.t6.id)->test.t6.id |
> |   └─TableReader_9     | 10000.00 | root      |               | data:TableFullScan_8                                                                         |
> |     └─TableFullScan_8 | 10000.00 | cop[tikv] | table:t6      | keep order:false, stats:pseudo                                                               |
> +-----------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
> 4 rows in set
> Time: 0.011s
> mysql root@localhost:test>  
> ```

hi,pingyu, I modified the func_max_min.go,

> @StoneDotYang Do you have any problem addressing [this comment](https://github.com/pingcap/tidb/pull/21566#issuecomment-745044985)?

I am modifying the test case

**Comment by b41sh** [comment]
please fix the test @StoneDotYang

**Comment by StoneDotYang** [comment]
> please fix the test @StoneDotYang

yeah,has modified the related test case.

**Comment by b41sh** [comment]
LGTM

**Comment by b41sh** [comment]
@pingyu  PTAL

**Review by wshwsh12 — COMMENTED** [review]
It seems TopN for enum will get a wrong result..   
```
MySQL [test]> create table t(e enum('e','d','c','b','a'));
Query OK, 0 rows affected (0.010 sec)

MySQL [test]> insert into t values('e'),('d'),('c'),('b'),('a');
Query OK, 5 rows affected (0.003 sec)
Records: 5  Duplicates: 0  Warnings: 0

MySQL [test]> select * from t order by e limit 1;
+------+
| e    |
+------+
| e    |
+------+
1 row in set (0.000 sec)
```
But this pr will get a result `a`.

**Comment by b41sh** [comment]
> It seems TopN for enum will get a wrong result..
> 
> ```
> MySQL [test]> create table t(e enum('e','d','c','b','a'));
> Query OK, 0 rows affected (0.010 sec)
> 
> MySQL [test]> insert into t values('e'),('d'),('c'),('b'),('a');
> Query OK, 5 rows affected (0.003 sec)
> Records: 5  Duplicates: 0  Warnings: 0
> 
> MySQL [test]> select * from t order by e limit 1;
> +------+
> | e    |
> +------+
> | e    |
> +------+
> 1 row in set (0.000 sec)
> ```
> 
> But this pr will get a result `a`.

it seems the behavior of enum for MySQL is mixed. 
`select * from t order by e;` is ordered by value, but `select max(e) from t;` is ordered by name.
so we can't use `TopNExec` when the field type is `enum/set` for `max/min` agg functions.

**Comment by wshwsh12** [comment]
> we can't use TopNExec when the field type is enum/set for max/min agg functions.

Yes, I think you are right.

**Comment by b41sh** [comment]
LGTM  cancel

File: planner/core/rule_max_min_eliminate.go [hunk 3]
```diff
@@ -204,6 +204,13 @@ func (a *maxMinEliminator) eliminateMaxMin(p LogicalPlan) LogicalPlan {
 		if len(agg.GroupByItems) != 0 {
 			return agg
 		}
+
```
Comment (b41sh) [inline planner/core/rule_max_min_eliminate.go:207]: please add some comment for this case

**Review by b41sh — CHANGES_REQUESTED** [review]

**Comment by b41sh** [comment]
please fix the conflict @StoneDotYang

File: planner/core/rule_max_min_eliminate.go [hunk 4]
```diff
@@ -210,6 +210,13 @@ func (a *maxMinEliminator) eliminateMaxMin(p LogicalPlan) LogicalPlan {
 				return agg
 			}
 		}
+		// Limit+Sort operators are sorted by value,but ENUM/SET field types are sorted by name.
```
Comment (b41sh) [inline planner/core/rule_max_min_eliminate.go:213]: please put a space after the comma

Comment (StoneDotYang) [reply planner/core/rule_max_min_eliminate.go:214]: ok.has add space.PTAL

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Comment by b41sh** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
