### PR TITLE
lightning: keep started import-into submits alive on cancellation

### LINKED ISSUE #66721: importinto: sibling submit failure may leave another detached job running
### 1. Minimal reproduce step (Required)

Submit two detached `IMPORT INTO` jobs concurrently with the same `GROUP_KEY`.

Make the first one fail immediately on precheck, for example keep `t1` non-empty so `IMPORT INTO t1 ...` returns `PreCheck failed: target table is not empty`. Let the second one (`t2`) be valid.

This can be reproduced from the current `importinto` submit path, where sibling submits share one context and one failure cancels the rest.

### 2. What did you expect to see? (Required)

After one submit fails, no other job from the same submit batch should still be created. If it was already created, `Cancel()` should be able to catch and cancel it reliably.

### 3. What did you see instead (Required)

In one run, `t1` failed first and the caller already entered the cancel path, but TiDB still created the detached job for `t2` a bit later.

Then `t2` stayed in `Import` mode for a while and a later DDL failed with:

```text
[schema:8258] Table t2 is in mode Import
```

Relevant log order:

```text
01:42:50.421 t1 submit failed: PreCheck failed: target table is not empty
01:42:50.422 client starts Cancel()
01:42:50.453 TiDB still creates job 3 for t2
```

It looks like the sibling submit returned early because the shared context was canceled, but the in-flight SQL had already reached TiDB, and the current cancel path missed this late-visible job.

### 4. What is your TiDB version? (Required)

```text
release-version=v9.0.0-beta.2.pre-96-g46f1784af
git-hash=46f1784af1a1abc30640c91b30c2ae0a05a71e66
utc-build-time="2026-03-05 04:15:29"
go-version=go1.25.6
```

TiFlow used TiDB module:

```text
github.com/pingcap/tidb v1.1.0-beta.0.20260205093021-1eb3d0a8c7a9
```

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #66721

Problem Summary:
Concurrent detached `IMPORT INTO` submits share one `errgroup` context today. If one submit fails or the caller cancels the batch while another submit is already in flight, the client can return early before it receives the job ID, while TiDB may still create the detached job later. That leaves the job without a recorded checkpoint and can keep the target table in Import mode.

### What changed and how does it work?
- stop using the shared `errgroup` context for submits that have already started
- run started submits on a bounded `context.WithoutCancel(ctx)` child so they can still return a job ID or a real submit error
- use the same bounded submit context to record the running checkpoint once the job is created
- add regressions for sibling submit failure and parent context cancellation

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Bounded a grace period for in-flight submissions to ensure reliable checkpoint recording and proper cancellation propagation.
  * Added safer pre-checks and thread-safe accumulation of job state to avoid lost or contested updates during cancellation.

* **Tests**
  * Added tests covering cyclic submission/cancellation, grace-timeout behavior, and fresh-timeout recording.
  * Enabled failpoint-driven timeout control and adjusted test parallelism to exercise timing-sensitive scenarios.

### CODE REVIEW

File: lightning/pkg/importinto/job_orchestrator.go [hunk 1]
```diff
@@ -361,21 +375,26 @@ func (o *DefaultJobOrchestrator) submitAllJobs(ctx context.Context, tables []*im
...
+
+				job, err = o.submitter.SubmitTable(submitCtx, table)
 				if err != nil {
 					return errors.Annotatef(err, "submit table %s.%s", table.Database, table.Table)
 				}
 
-				cpCtx, cancel := context.WithTimeout(context.Background(), cancelTimeout)
-				defer cancel()
-				if err := o.recordSubmission(cpCtx, job); err != nil {
+				appendJob(job)
```
Comment (D3Hunter) [inline lightning/pkg/importinto/job_orchestrator.go]: #### ⚠️ **[Major]** Shared 30s submit context can expire before checkpoint persistence

**Why**
This path can still lose checkpoint visibility for a started detached job because `SubmitTable` and `recordSubmission` share one 30s deadline budget.

**Scope**
lightning/pkg/importinto/job_orchestrator.go:390

**Risk if unchanged**
If `SubmitTable` consumes most of the 30s window, checkpoint update may fail with deadline exceeded, so a created job can remain hard to discover and cancel reliably after failures.

**Evidence**
The new flow creates `submitCtx` once (`context.WithTimeout(context.WithoutCancel(ctx), submitGraceTimeout)`), then uses that same context for both `SubmitTable` and `recordSubmission`.

**Change request**
Please give checkpoint persistence an independent timeout budget after submit returns (for example a fresh context) so started-job tracking does not depend on remaining submit time.

File: lightning/pkg/importinto/job_orchestrator_test.go [hunk 2]
```diff
@@ -204,23 +204,35 @@ func TestJobOrchestratorSubmissionErrorStillRecordsSubmittedJobs(t *testing.T) {
...
+			<-t2Started
+			close(t1Failed)
 			return nil, errors.New("submit error")
+		case "t2":
+			close(t2Started)
+			<-t1Failed
+			select {
+			case <-ctx.Done():
+				return nil, ctx.Err()
+			case <-time.After(100 * time.Millisecond):
```
Comment (D3Hunter) [inline lightning/pkg/importinto/job_orchestrator_test.go]: #### 🟡 **[Minor]** Regression tests use fixed sleep windows in synchronization-critical paths

**Why**
This can make cancellation race tests timing-sensitive and flaky under slower CI machines.

**Scope**
lightning/pkg/importinto/job_orchestrator_test.go:221

**Risk if unchanged**
Flaky tests reduce confidence in the cancellation fix and can hide real regressions behind intermittent failures.

**Evidence**
Both new tests use `time.After(100 * time.Millisecond)` as synchronization instead of explicit handshake channels.

**Change request**
Please replace sleep-based waits with explicit channel handshakes so the tests deterministically wait for the intended state transitions.

**Review by D3Hunter — COMMENTED** [review]
**AI-generated review based on @D3Hunter's standards; manual review will be performed after all comments are resolved.**

### Summary

- Total findings: 2
- Inline comments: 2
- Summary-only findings (no inline anchor): 0

<details>
<summary>Findings (highest risk first)</summary>

#### ⚠️ **[Major]** (1)

1. Shared 30s submit context can expire before checkpoint persistence (`lightning/pkg/importinto/job_orchestrator.go:390`)

#### 🟡 **[Minor]** (1)

1. Regression tests use fixed sleep windows in synchronization-critical paths (`lightning/pkg/importinto/job_orchestrator_test.go:221`)

</details>

File: lightning/pkg/importinto/job_orchestrator.go [hunk 3]
```diff
@@ -361,21 +375,26 @@ func (o *DefaultJobOrchestrator) submitAllJobs(ctx context.Context, tables []*im
 					logger.Info("submitting new import job")
 				}
 
-				job, err = o.submitter.SubmitTable(egCtx, table)
+				if err := egCtx.Err(); err != nil {
+					return errors.Trace(err)
+				}
+
+				submitCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), submitGraceTimeout)
```
Comment (D3Hunter) [inline lightning/pkg/importinto/job_orchestrator.go]: #### ⚠️ **[Major]** Detached 30s submit context can misclassify cancellation and trigger unintended job cancel

**Why**
The new submission flow always wraps work in `context.WithTimeout(context.WithoutCancel(ctx), submitGraceTimeout)` and reuses that single deadline for both table submission and submission recording. When control-plane latency is high, or when parent cancellation is expected during failover handoff, expiry can surface as `context deadline exceeded` and be treated as a non-cancel submission failure.

**Scope**
lightning/pkg/importinto/job_orchestrator.go:122, lightning/pkg/importinto/job_orchestrator.go:382, lightning/pkg/importinto/job_orchestrator.go:385, lightning/pkg/importinto/job_orchestrator.go:391

**Risk if unchanged**
IMPORT INTO orchestration can cancel already-submitted jobs during DM failover and also fail normal submissions under transient latency, creating avoidable restart churn and changed upgrade/recovery behavior.

**Evidence**
`submitCtx` is created with `context.WithTimeout(context.WithoutCancel(ctx), submitGraceTimeout)` and reused across `SubmitTable` and `recordSubmission`; timeout errors on this path are not consistently classified as caller cancellation by `common.IsContextCanceledError`, so `SubmitAndWait` can enter the `job submission failed, cancelling submitted jobs` branch.

**Change request**
Please preserve detached grace behavior without imposing one universal 30s budget across submit and checkpoint recording, and ensure already-canceled parent contexts are propagated as cancellation-class errors so failover handoff does not trigger orchestrator-side `o.Cancel`. Add an integration test for canceled-parent plus slow submit/record timeout behavior.

File: lightning/pkg/importinto/job_orchestrator_test.go (hunk 2 above)
Comment (D3Hunter) [inline lightning/pkg/importinto/job_orchestrator_test.go]: #### 🟡 **[Minor]** New cancellation tests rely on wall-clock sleeps instead of deterministic signaling

**Why**
The added tests gate behavior on `time.After(100 * time.Millisecond)` branches, which introduces timing dependence and can reduce determinism under scheduler or CI variance.

**Scope**
lightning/pkg/importinto/job_orchestrator_test.go:221

**Risk if unchanged**
Timing-coupled tests are more brittle and slower, and can intermittently fail to exercise the intended cancellation ordering on constrained or highly loaded runners.

**Evidence**
Both new or updated tests use fixed-delay `time.After(100 * time.Millisecond)` synchronization in `lightning/pkg/importinto/job_orchestrator_test.go:221` and `lightning/pkg/importinto/job_orchestrator_test.go:292`.

**Change request**
Cover the retry and cancel path with deterministic coordination primitives (explicit channels or hooks, or `require.Eventually` on concrete state) instead of fixed sleep windows.

File: lightning/pkg/importinto/job_orchestrator.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (GMHDBJD) [reply lightning/pkg/importinto/job_orchestrator.go]: Fixed. The grace window now starts when the parent context is canceled.

File: lightning/pkg/importinto/job_orchestrator.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (GMHDBJD) [reply lightning/pkg/importinto/job_orchestrator.go]: Fixed. `recordSubmission` now uses an independent grace budget.

File: lightning/pkg/importinto/job_orchestrator.go [hunk 4]
```diff
@@ -329,6 +339,10 @@ func (o *DefaultJobOrchestrator) submitAllJobs(ctx context.Context, tables []*im
 		eg.Go(func() error {
 			logger := o.logger.With(zap.String("database", table.Database), zap.String("table", table.Table))
 
+			if err := egCtx.Err(); err != nil {
```
[the remark this answers is not in the document]
Comment (GMHDBJD) [reply lightning/pkg/importinto/job_orchestrator.go]: Fixed. We still load checkpoints after errgroup cancellation so running jobs can be reconciled.

File: lightning/pkg/importinto/job_orchestrator.go (hunk 1 above)
Comment (GMHDBJD) [reply lightning/pkg/importinto/job_orchestrator.go]: Fixed. Checkpoint persistence now has its own timeout budget.

File: lightning/pkg/importinto/job_orchestrator_test.go (hunk 2 above)
Comment (GMHDBJD) [reply lightning/pkg/importinto/job_orchestrator_test.go]: Fixed. The tests now use explicit channel coordination instead of fixed sleep windows.

File: lightning/pkg/importinto/job_orchestrator.go (hunk 3 above)
Comment (GMHDBJD) [reply lightning/pkg/importinto/job_orchestrator.go]: Fixed. Detached submit no longer shares one timeout with checkpoint recording.

File: lightning/pkg/importinto/job_orchestrator_test.go (hunk 2 above)
Comment (GMHDBJD) [reply lightning/pkg/importinto/job_orchestrator_test.go]: Fixed. The cancellation tests now use deterministic synchronization.

**Review by D3Hunter — APPROVED** [review]
