### PR TITLE
lightning: skip CREATE DATABASE when downstream exists, and return error when parse failed

### LINKED ISSUE #51800: When lightning is less capabile than downstream, `USE <database>` may miss so failed with "no database selected"
The source schema files may contain some unsupported feature, like unsupported chatset. When lightning failed to rewrite the statement, it directly uses the source file content. However, `USE <database>` is missing

https://github.com/pingcap/tidb/blob/c1e3daebf183f93e3ed61e3ef56b8da430621d21/br/pkg/lightning/importer/import.go#L625-L638

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #51800

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/importer/import.go [hunk 1]
```diff
@@ -630,7 +630,8 @@ func (worker *restoreSchemaWorker) addJob(sqlStr string, job *schemaJob) error {
 			zap.String("table", job.tblName),
 			zap.String("statement", sqlStr),
 			zap.Error(err))
-		job.stmts = []string{sqlStr}
+		useStmt := common.SprintfWithIdentifiers("USE %s", job.dbName)
+		job.stmts = []string{useStmt, sqlStr}
```
Comment (D3Hunter) [inline br/pkg/lightning/importer/import.go:634]: we should return error if we cannot parse the sql, so user can see the real err. lightning version >= tidb-version in most case, so there shouldn't be cases that lightning cannot parse, but tidb can execute it.

Comment (lance6716) [reply br/pkg/lightning/importer/import.go:634]: This is a cloud oncall, tiflow's version is lower than downstream TiDB

Comment (D3Hunter) [reply br/pkg/lightning/importer/import.go:634]: then we should update tiflow with latest tidb dependency

also the logic to use original sql is error prone when the unparsable sql already contains dbname that might be the one we want

Comment (lance6716) [reply br/pkg/lightning/importer/import.go:634]: Our rewrite logic will not change the error message if downstream can not execute them, the user still can see a meaningful error message which is reported by downstream TiDB's parser.

Comment (D3Hunter) [reply br/pkg/lightning/importer/import.go:634]: i mean when the sql is unparsable by tiflow, but ok for tidb, then we might created it in the wrong db

Comment (okJiang) [reply br/pkg/lightning/importer/import.go:634]: I agree `update tiflow with latest tidb dependency`

But since we already support the function of executing SQL even if it cannot be parsed, I think this PR can be fixed as a bug. Unless we firmly decide to remove it

Comment (lance6716) [reply br/pkg/lightning/importer/import.go:634]: I should remove the fallback logic if tiflow can be newer than downstream TiDB

File: br/tests/lightning_character_sets/config.toml
Comment (Benjamin2037) [inline br/tests/lightning_character_sets/config.toml:1]: why do we need a empty file in this pr？

Comment (lance6716) [reply br/tests/lightning_character_sets/config.toml:1]: The `run_lightning` script needs a configuration file, otherwise it will report error. Empty file means default configuration.

File: br/pkg/lightning/importer/import.go (hunk 1 above)
Comment (Frank945946) [reply br/pkg/lightning/importer/import.go:634]: I also agree with "update tiflow with latest tidb dependency"

**Review by okJiang — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
