### PR TITLE
ddl: fix a bug that dropping primary key lead to implicit invisible primary key success

### LINKED ISSUE #19280: Drop primary causes implicit invisible primary will success
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` sql
create table t6 (a int not null, b int, unique (a) invisible, primary key(b));
alter table t6 drop primary key;
ERROR 3522 (HY000): A primary key index cannot be invisible
mysql> show create table t6;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                 |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t6    | CREATE TABLE `t6` (
  `a` int(11) NOT NULL,
  `b` int(11) NOT NULL,
  UNIQUE KEY `a` (`a`) /*!80000 INVISIBLE */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

We can see from the `show create table`, the primary key is dropped.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #19280  

Problem Summary:

We check it when the jobSchema is deleteReorg. In this state, the drop index can't be rollbacked.

### What is changed and how it works?

Put checkInvisibleIndexOnPK in checkDropIndex().

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

File: ddl/index.go [hunk 1]
```diff
@@ -686,6 +686,21 @@ func checkDropIndex(t *meta.Meta, job *model.Job) (*model.TableInfo, *model.Inde
...
+	for _, idx := range tblInfo.Indices {
+		if idx.Name.L != indexInfo.Name.L {
+			newIndices = append(newIndices, idx)
+		}
+	}
+	newTbl := tblInfo.Clone()
+	newTbl.Indices = newIndices
+	err = checkInvisibleIndexOnPK(newTbl)
+	if err != nil {
+		job.State = model.JobStateCancelled
```
Comment (zimulala) [inline ddl/index.go:700]: Could we add a test for this logic?

**Review by djshow832 — COMMENTED** [review]
LGTM

File: ddl/index.go [hunk 2]
```diff
@@ -686,6 +686,21 @@ func checkDropIndex(t *meta.Meta, job *model.Job) (*model.TableInfo, *model.Inde
 		return nil, nil, autoid.ErrWrongAutoKey
 	}
 
+	// Check that drop primary index will not cause invisible implicit primary index.
```
Comment (AilinKid) [inline ddl/index.go:689]: how about enclosing this as a small function

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

**Review by zimulala — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
