### PR TITLE
statistics: fix the panic when analyze with collation enabled

### LINKED ISSUE #20874: clustered index + new collation + analyze panic
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->
```
mysql> show create table t;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                  |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` char(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `b` char(20) COLLATE utf8mb4_general_ci NOT NULL,
  `c` int(11) NOT NULL,
  PRIMARY KEY (`a`,`b`,`c`),
  KEY `idx` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

insert into t values ('#', 'C', 10), ('$', 'c', 20), ('a', 'a', 10);

mysql> select * from t;
+---+---+----+
| a | b | c  |
+---+---+----+
| # | C | 10 |
| $ | c | 20 |
| a | a | 10 |
+---+---+----+
3 rows in set (0.00 sec)

mysql> analyze table t;
ERROR 1105 (HY000): analyze worker panic
```

### 2. What did you expect to see? (Required)
No panic
### 3. What did you see instead (Required)
Panic
### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->

master

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #20874  

Problem Summary:

The histogram stores the sort key representation if there's collation. But we compare it as original string. This will compute the sort key from the sort key which would cause panic for some collation.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

Don't compuate the sort key again.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- Fix the panic when analyze with collation enabled

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: executor/analyze.go [hunk 1]
```diff
@@ -558,6 +558,9 @@ func (e *AnalyzeColumnsExec) buildStats(ranges []*ranger.Range, needExtStats boo
 			if err != nil {
 				return nil, nil, nil, nil, err
 			}
+			if collectors[i].Samples[j].Value.Kind() == types.KindString {
+				collectors[i].Samples[j].Value.SetBytes(collectors[i].Samples[j].Value.GetBytes())
```
Comment (XuHuaiyu) [inline executor/analyze.go:562]: What does this mean?

Comment (bb7133) [reply executor/analyze.go:562]: +1, it would be helpful if you can add some comments here.

File: statistics/histogram.go [hunk 2]
```diff
@@ -90,6 +91,13 @@ type scalar struct {
 
 // NewHistogram creates a new histogram.
 func NewHistogram(id, ndv, nullCount int64, version uint64, tp *types.FieldType, bucketSize int, totColSize int64) *Histogram {
+	if tp.EvalType() == types.ETString {
+		// The histogram will store the the string value's Key representation of its collation.
```
Comment (bb7133) [inline statistics/histogram.go:95]:
```suggestion
		// The histogram will store the string value's 'sort key' representation of its collation.
```

File: statistics/histogram.go [hunk 3]
```diff
@@ -90,6 +91,13 @@ type scalar struct {
...
+		// If we directly set the field type's collation to its original one. We would decode the Key representation using its collation.
+		// This would cause panic.
```
Comment (bb7133) [inline statistics/histogram.go:97]:
```suggestion
		// This would cause panic. So we apply a little trick here to avoid decoding it by explicitly changing the collation to 'CollationBin'.
```

Comment (bb7133) [reply statistics/histogram.go:97]: How about this?

**Review by bb7133 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by XuHuaiyu** [comment]
LGTM

File: executor/analyze_test.go [hunk 4]
```diff
@@ -759,3 +760,26 @@ func (s *testSuite1) TestDefaultValForAnalyze(c *C) {
 	tk.MustQuery("explain select * from t where a = 1").Check(testkit.Rows("IndexReader_6 1.00 root  index:IndexRangeScan_5",
 		"└─IndexRangeScan_5 1.00 cop[tikv] table:t, index:a(a) range:[1,1], keep order:false"))
 }
+
+func (s *testSuite1) TestIssue20874(c *C) {
```
Comment (zhangjinpeng1987) [inline executor/analyze_test.go:764]: Better to use the scenario as func name, or when we want to sort out all test cases(see the coverage or optimize ci), it is hard to do such works.
