### PR TITLE
lightning: retry for WaitN error caused by store-write-bwlimit

### LINKED ISSUE #51383: lightning: retry when write tikv is slow and rate limiter context timeout
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

with `store-write-bwlimit` set, if write tikv is slow(might due to tikv io overload), and we cannot wait enough token to write to tikv within 15 minutes, it will report this error, we should retry on this
```
[errorVerbose="rate: Wait(n=28406) would exceed context deadline
github.com/pingcap/errors.AddStack
    /go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174
github.com/pingcap/errors.Trace
    /go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/juju_adaptor.go:15
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).doWrite.func5
    /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/region_job.go:354
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).doWrite
    /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/region_job.go:395
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).writeToTiKV
    /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/region_job.go:190
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).executeJob
    /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/local.go:1436
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).startWorker
    /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/local.go:1345
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).doImport.func5
    /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/local.go:1678
golang.org/x/sync/errgroup.(*Group).Go.func1
    /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1650"
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #51383

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/local/region_job.go [hunk 1]
```diff
@@ -202,6 +202,33 @@ func (local *Backend) writeToTiKV(ctx context.Context, j *regionJob) error {
...
+const defaultWriteTimeout = 15 * time.Minute
+
+func getWriteMaxTimeout(j *regionJob, limiter StoreWriteLimiter) time.Duration {
+	switch v := limiter.(type) {
+	case noopStoreWriteLimiter:
+		return defaultWriteTimeout
+	case *storeWriteLimiter:
+		maxSize := getWriteMaxSize(j)
+		// limit is not 0, otherwise local backend will use noopStoreWriteLimiter
+		durationSec := maxSize / int64(v.limit)
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/local/region_job.go:224]: this value is a few seconds in most cases, seems not that useful to adjust `timeout`

**Review by D3Hunter — APPROVED** [review]

**Review by okJiang — APPROVED** [review]
