### PR TITLE
ddl: handle store closed in doDDLJob

### LINKED ISSUE #18714: doDDLJob may retry and enter dead loop
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

add failpoint in `doDDLJob` around line 490 
```go
        for {
		failpoint.Inject("storeCloseInLoop", func(val failpoint.Value) {
			v := val.(int)
			time.Sleep(time.Duration(v) * time.Second)
		})
		select {
		case <-d.ddlJobDoneCh:
		case <-ticker.C:
```

```go
func (s *testSessionSuite) TestDoDDLJobQuit(c *C) {
	store, err := mockstore.NewMockStore(mockstore.WithStoreType(mockstore.MockTiKV))
	c.Assert(err, IsNil)
	session.SetSchemaLease(10 * time.Millisecond)
	dom, err := session.BootstrapSession(store)
	c.Assert(err, IsNil)
	se, err := session.CreateSession(store)
	c.Assert(err, IsNil)

	c.Assert(failpoint.Enable("github.com/pingcap/tidb/ddl/storeCloseInLoop", `return(2)`), IsNil)
	go func() {
		time.Sleep(time.Second)
		se.Close()
		dom.Close()
		store.Close()
	}()
	// this DDL call will enter deadloop
	c.Assert(dom.DDL().CreateSchema(se, model.NewCIStr("testschema"), nil), IsNil)
	c.Assert(failpoint.Disable("github.com/pingcap/tidb/ddl/storeCloseInLoop"), IsNil)
}
```

### 2. What did you expect to see? (Required)
function returns in proper time.

### 3. What did you see instead (Required)
block and print log forever.
```
[2020-07-21T08:37:23.331Z] [2020/07/21 16:37:22.114 +08:00] [ERROR] [ddl.go:523] ["[ddl] get history DDL job failed, check again"] [component="ddl tracker"] [error="tikv aborts txn: leveldb: closed"] [errorVerbose="tikv aborts txn: leveldb: closed\ngithub.com/pingcap/tidb/store/tikv.extractKeyErr\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:442\ngithub.com/pingcap/tidb/store/tikv.extractLockFromKeyErr\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:423\ngithub.com/pingcap/tidb/store/tikv.(*tikvSnapshot).get\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:368\ngithub.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Get\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:298\ngithub.com/pingcap/tidb/kv.(*unionStore).Get\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/kv/union_store.go:113\ngithub.com/pingcap/tidb/store/tikv.(*tikvTxn).Get\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/txn.go:142\ngithub.com/pingcap/tidb/structure.(*TxStructure).HGet\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/structure/hash.go:59\ngithub.com/pingcap/tidb/meta.(*Meta).getHistoryDDLJob\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/meta/meta.go:743\ngithub.com/pingcap/tidb/meta.(*Meta).GetHistoryDDLJob\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/meta/meta.go:756\ngithub.com/pingcap/tidb/ddl.(*ddl).getHistoryDDLJob.func1\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_worker.go:263\ngithub.com/pingcap/tidb/kv.RunInNewTxn\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/kv/txn.go:47\ngithub.com/pingcap/tidb/ddl.(*ddl).getHistoryDDLJob\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_worker.go:260\ngithub.com/pingcap/tidb/ddl.(*ddl).doDDLJob\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl.go:521\ngithub.com/pingcap/tidb/ddl.(*ddl).DropTable\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_api.go:3689\ngithub.com/pingcap/dm/pkg/schema.(*Tracker).DropTable\n\t/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/pkg/schema/tracker.go:199\ngithub.com/pingcap/dm/syncer.(*RemoteCheckPoint).Rollback\n\t/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:559\ngithub.com/pingcap/dm/syncer.(*Syncer).Process\n\t/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:559\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"] [stack="github.com/pingcap/tidb/ddl.(*ddl).doDDLJob\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl.go:523\ngithub.com/pingcap/tidb/ddl.(*ddl).DropTable\n\t/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_api.go:3689\ngithub.com/pingcap/dm/pkg/schema.(*Tracker).DropTable\n\t/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/pkg/schema/tracker.go:199\ngithub.com/pingcap/dm/syncer.(*RemoteCheckPoint).Rollback\n\t/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:559\ngithub.com/pingcap/dm/syncer.(*Syncer).Process\n\t/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:559"]
```
format this log:
```
errorVerbose=tikv aborts txn: leveldb: closed
github.com/pingcap/tidb/store/tikv.extractKeyErr
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:442
github.com/pingcap/tidb/store/tikv.extractLockFromKeyErr
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:423
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).get
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:368
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Get
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/snapshot.go:298
github.com/pingcap/tidb/kv.(*unionStore).Get
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/kv/union_store.go:113
github.com/pingcap/tidb/store/tikv.(*tikvTxn).Get
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/store/tikv/txn.go:142
github.com/pingcap/tidb/structure.(*TxStructure).HGet
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/structure/hash.go:59
github.com/pingcap/tidb/meta.(*Meta).getHistoryDDLJob
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/meta/meta.go:743
github.com/pingcap/tidb/meta.(*Meta).GetHistoryDDLJob
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/meta/meta.go:756
github.com/pingcap/tidb/ddl.(*ddl).getHistoryDDLJob.func1
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_worker.go:263
github.com/pingcap/tidb/kv.RunInNewTxn
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/kv/txn.go:47
github.com/pingcap/tidb/ddl.(*ddl).getHistoryDDLJob
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_worker.go:260
github.com/pingcap/tidb/ddl.(*ddl).doDDLJob
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl.go:521
github.com/pingcap/tidb/ddl.(*ddl).DropTable
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_api.go:3689
github.com/pingcap/dm/pkg/schema.(*Tracker).DropTable
	/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/pkg/schema/tracker.go:199
github.com/pingcap/dm/syncer.(*RemoteCheckPoint).Rollback
	/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:559
github.com/pingcap/dm/syncer.(*Syncer).Process
	/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:559
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
    
stack=
github.com/pingcap/tidb/ddl.(*ddl).doDDLJob
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl.go:523
github.com/pingcap/tidb/ddl.(*ddl).DropTable
	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20200423094549-0ad7ce6cdae6/ddl/ddl_api.go:3689
github.com/pingcap/dm/pkg/schema.(*Tracker).DropTable
	/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/pkg/schema/tracker.go:199
github.com/pingcap/dm/syncer.(*RemoteCheckPoint).Rollback
	/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/checkpoint.go:559
github.com/pingcap/dm/syncer.(*Syncer).Process
	/home/jenkins/agent/workspace/dm_ghpr_test/go/src/github.com/pingcap/dm/syncer/syncer.go:559
```

### 4. Affected version (Required)

current master

### 5. Root Cause Analysis

`(*ddl).doDDLJob` doesn't have an exit branch:

https://github.com/pingcap/tidb/blob/168fcbb54f7825377736a5f2118ab3d79451f63f/ddl/ddl.go#L490-L499

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #18714 , https://github.com/pingcap/dm/issues/792

Problem Summary: add an exit branch in `doDDLJob`

### What is changed and how it works?

What's Changed:

detected `d.ctx.Done()` in `doDDLJob`, which may caused by worker closed, store closed, ..., to avoid deadloop. Note now `doDDLJob` will fail immediately when worker closed, so changed some 5-year-old test

How it Works:

add an exit branch in `doDDLJob`, add a unit test to verify

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by lance6716** [comment]
PTAL @zimulala

**Comment by lance6716** [comment]
PTAL @zimulala

**Comment by lance6716** [comment]
PTAL @AilinKid @zimulala

File: ddl/ddl.go [hunk 1]
```diff
@@ -488,9 +488,15 @@ func (d *ddl) doDDLJob(ctx sessionctx.Context, job *model.Job) error {
...
 	for {
+		failpoint.Inject("storeCloseInLoop", func(val failpoint.Value) {
+			v := val.(int)
+			time.Sleep(time.Duration(v) * time.Second)
+		})
 		select {
 		case <-d.ddlJobDoneCh:
 		case <-ticker.C:
+		case <-d.ctx.Done():
+			return d.ctx.Err()
```
[the remark this answers is not in the document]
Comment (lance6716) [reply ddl/ddl.go:500]: added in https://github.com/pingcap/tidb/pull/18844/commits/c0a61c828c96d00e2c2ba258f25b9b9b490a2b16

**Comment by csuzhangxc** [comment]
@zimulala PTAL, thanks!

File: ddl/stat_test.go [hunk 2]
```diff
@@ -87,9 +87,7 @@ LOOP:
 	for {
 		select {
 		case <-ticker.C:
-			d.Stop()
 			c.Assert(s.getDDLSchemaVer(c, d), GreaterEqual, ver)
-			d.restartWorkers(context.Background())
```
Comment (zimulala) [inline ddl/stat_test.go:92]: Why remove this test? Will deleting this test reduce test scenarios?

File: session/session_test.go [hunk 3]
```diff
@@ -3231,6 +3231,29 @@ func (s *testSessionSuite2) TestPerStmtTaskID(c *C) {
 	c.Assert(taskID1 != taskID2, IsTrue)
 }
 
+func (s *testSessionSuite) TestDoDDLJobQuit(c *C) {
+	// test https://github.com/pingcap/tidb/issues/18714, imitate DM's use environment
+	store, err := mockstore.NewMockStore(mockstore.WithStoreType(mockstore.MockTiKV))
+	c.Assert(err, IsNil)
+	session.SetSchemaLease(10 * time.Millisecond)
+	dom, err := session.BootstrapSession(store)
```
Comment (zimulala) [inline session/session_test.go:3239]: It is done in `SetUpSuite`, could we remove these code?

File: session/session_test.go [hunk 4]
```diff
@@ -3231,6 +3231,29 @@ func (s *testSessionSuite2) TestPerStmtTaskID(c *C) {
...
+	c.Assert(err, IsNil)
+	se, err := session.CreateSession(store)
+	c.Assert(err, IsNil)
+
+	c.Assert(failpoint.Enable("github.com/pingcap/tidb/ddl/storeCloseInLoop", `return(2)`), IsNil)
+	go func() {
+		time.Sleep(time.Second)
```
Comment (zimulala) [inline session/session_test.go:3246]: I think use `Sleep` and `go` will make the test unstable and "sleep 2s" make the test run a long test.

File: ddl/stat_test.go (hunk 2 above)
Comment (lance6716) [reply ddl/stat_test.go:92]: `d.Stop()`will call `d.cancel()`, which will trigger `doDDLJob` quit

File: session/session_test.go (hunk 3 above)
Comment (lance6716) [reply session/session_test.go:3239]: because we'll manually close `dom`, so can't use suite-shared variable

File: ddl/stat_test.go (hunk 2 above)
Comment (zimulala) [reply ddl/stat_test.go:92]: We can replace `done <- d.doDDLJob(ctx, job)` with checking the job in history. Instead of removing these test scenarios.

**Comment by lance6716** [comment]
seems an error irrelevant to this PR could be reproduce:

```
run test [alter_table1] err: sql:ALTER TABLE m1 ENABLE KEYS, ALGORITHM= INPLACE;: failed to run query \n\"ALTER TABLE m1 ENABLE KEYS, ALGORITHM= INPLACE;\" \n around line 317, \nwe need(158):\nALTER TABLE m1 ENABLE KEYS, ALGORITHM= INPLACE;\nALTER TABLE t1 DROP INDEX i1;\nALTER TABLE t1 DROP INDEX i2;\nALTER TABLE t1 DROP INDEX i3;\nALTER TABLE t1 DROP \nbut got(158):\nALTER TABLE m1 ENABLE KEYS, ALGORITHM= INPLACE;\nError 1846: ALGORITHM=INPLACE is not supported. Reason: Cannot alter table by INPLACE. Try ALGORITHM=INSTANT.\n\n
```

**Comment by lance6716** [comment]
PTAL @zimulala

**Comment by lance6716** [comment]
PTAL @bb7133 @wjhuang2016

File: ddl/table_test.go [hunk 5]
```diff
@@ -417,6 +418,6 @@ func (s *testTableSuite) TestTableResume(c *C) {
 		Type:       model.ActionDropTable,
 		BinlogInfo: &model.HistoryInfo{},
 	}
-	testRunInterruptedJob(c, d, job)
+	c.Assert(d.doDDLJob(mock.NewContext(), job), IsNil)
```
Comment (zimulala) [inline ddl/table_test.go:421]: This test effect is different from the original function of `testRunInterruptedJob`. I think we can do https://github.com/pingcap/tidb/pull/18844/files#diff-4226364954d30f0f8c2648cb19da228eL235 like https://github.com/pingcap/tidb/pull/18844/files#diff-1461e7e6b6b324ad06052b4709e8c1daR87.

File: session/session_test.go (hunk 3 above)
Comment (zimulala) [reply session/session_test.go:3240]: Got it.

**Review by zimulala — COMMENTED** [review]
Rest LGTM

File: ddl/table_test.go (hunk 5 above)
Comment (lance6716) [reply ddl/table_test.go]: now `testRunInterruptedJob` keeps same to caller, and use `*ddl.mu` to avoid data race

File: ddl/ddl.go [hunk 6]
```diff
@@ -488,10 +488,22 @@ func (d *ddl) doDDLJob(ctx sessionctx.Context, job *model.Job) error {
 		metrics.HandleJobHistogram.WithLabelValues(job.Type.String(), metrics.RetLabel(err)).Observe(time.Since(startTime).Seconds())
 	}()
 	for {
+		failpoint.Inject("storeCloseInLoop", func(_ failpoint.Value) {
+			d.cancel()
+		})
+
+		// avoid data race with restartWorkers in ddl_test.go
+		d.mu.RLock()
```
Comment (zimulala) [inline ddl/ddl.go:496]: Could we add this code to [d.doDDLJob(ctx, job)](https://github.com/pingcap/tidb/pull/18844/files#diff-4226364954d30f0f8c2648cb19da228eR239)? Then we needn't change this code.

Comment (lance6716) [reply ddl/ddl.go:496]: i guess if we protect whole function, restartWorker can't run concurrently with doDDLJob, so there's not a test for "interrupted job"

Comment (lance6716) [reply ddl/ddl.go]: done in https://github.com/pingcap/tidb/pull/18844/commits/f7eb7d36d09608b4460fa849fd65023a8992c7f4

Comment (zimulala) [reply ddl/ddl.go]: > guess if we protect whole function, restartWorker can't run concurrently with doDDLJob, so there's not a test for "interrupted job"

Yes. But we'd better don't change original code because of the test.

File: ddl/schema_test.go [hunk 7]
```diff
@@ -226,14 +226,32 @@ func (s *testSchemaSuite) TestSchemaWaitJob(c *C) {
...
-	go func() {
-		done <- d.doDDLJob(ctx, job)
-	}()
+	var (
+		history *model.Job
+		err     error
+	)
+
+	d.mu.RLock()
+	_ = d.doDDLJob(ctx, job)
```
Comment (AilinKid) [inline ddl/schema_test.go:240]: How about adding a check whether d is closed at every beginning of `doDDLJob`.
Avoid the case like that:
`doDDLJob` is called after`d.stop`, actually there is no worker running, so wait never ends in the loop.

Comment (lance6716) [reply ddl/schema_test.go:240]: in the loop of `doDDLJob`, `case <-d.ctx.Done()` added in this PR will be exit branch. I'm afraid these lines will block if worker closed. Should we check `d.ctx.Done()` here?

https://github.com/pingcap/tidb/blob/547c5b14cf2162ca2a018135aca453e57222dc44/ddl/ddl.go#L466-L467

Comment (AilinKid) [reply ddl/schema_test.go:240]: yes, I think so, because of the d.ctx.Done() is triggered, the task won't be added into the queue successfully in `limitDDLJobs`.

 `err := <-task.err ` may hang here.

how check `d.ctx.Done()` at every beginning of `doDDLJob`?

Comment (lance6716) [reply ddl/schema_test.go:240]: > how about checking `d.ctx.Done()` at every beginning of `doDDLJob`?

Maybe it's better to check at `err := <-task.err` and `d.limitJobCh <- task` to reduce gap between check and call.

Comment (AilinKid) [reply ddl/schema_test.go:240]: seems the same? ok

**Review by AilinKid — COMMENTED** [review]
~~LGTM~~

**Comment by lance6716** [comment]
> LGTM

Sorry where's some concurrency problem still, I'll fix it when has some spear time 😢

File: ddl/restart_test.go [hunk 8]
```diff
@@ -0,0 +1,200 @@
...
+	"github.com/pingcap/tidb/util/mock"
+)
+
+// this test file include some test that will cause data race, mainly because restartWorkers modify d.ctx
+
+// restartWorkers is like the function of d.start. But it won't initialize the "workers" and create a new worker.
+// It only starts the original workers.
+func (d *ddl) restartWorkers(ctx context.Context) {
+	d.cancel()
+	d.wg.Wait()
```
Comment (lance6716) [inline ddl/restart_test.go:33]: added these two lines⬆️

**Comment by lance6716** [comment]
now CI is failed because `Sending interrupt signal to process`. waiting for more advice on code @zimulala

**Comment by lance6716** [comment]
Oh finally CI passed

**Review by zimulala — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
