### PR TITLE
planner: correlate subquery rule

### LINKED ISSUE #66320: Planner: correlate a non-correlated IN subquery
## Bug Report

TiDB can "decorrelate" a correlated subquery today, but cannot correlate a subquery that was originally non-correlated.

### 1. Minimal reproduce step (Required)

```
create table t1 (a int, b int, key(a));
create table t2 (a int, b int, key(a));

explain select * from t1 where b = 1 and a in (select t2.a from t2, t1 where t1.a = t2.a);
```

### 2. What did you expect to see? (Required)

```
+-----------------------------------+----------+-----------+----------------------+------------------------------------------------------------------------------------------------------------------+
| id                                | estRows  | task      | access object        | operator info                                                                                                    |
+-----------------------------------+----------+-----------+----------------------+------------------------------------------------------------------------------------------------------------------+
| Apply_81                          | 9.99     | root      |                      | CARTESIAN semi join, left side:TableReader_84                                                                    |
| ├─TableReader_84(Build)           | 9.99     | root      |                      | data:Selection_83                                                                                                |
| │ └─Selection_83                  | 9.99     | cop[tikv] |                      | eq(test.t1.b, 1), not(isnull(test.t1.a))                                                                         |
| │   └─TableFullScan_82            | 10000.00 | cop[tikv] | table:t1             | keep order:false, stats:pseudo                                                                                   |
| └─Limit_91(Probe)                 | 9.99     | root      |                      | offset:0, count:1                                                                                                |
|   └─IndexHashJoin_100             | 9.99     | root      |                      | inner join, inner:IndexReader_120, outer key:test.t2.a, inner key:test.t1.a, equal cond:eq(test.t2.a, test.t1.a) |
|     ├─IndexReader_117(Build)      | 8.91     | root      |                      | index:Selection_116                                                                                              |
|     │ └─Selection_116             | 8.91     | cop[tikv] |                      | eq(test.t2.a, test.t1.a)                                                                                         |
|     │   └─IndexFullScan_115       | 8910.08  | cop[tikv] | table:t2, index:a(a) | keep order:false, stats:pseudo                                                                                   |
|     └─IndexReader_120(Probe)      | 11.14    | root      |                      | index:Selection_119                                                                                              |
|       └─Selection_119             | 11.14    | cop[tikv] |                      | eq(test.t1.a, test.t1.a), not(isnull(test.t1.a))                                                                 |
|         └─IndexRangeScan_118      | 11148.75 | cop[tikv] | table:t1, index:a(a) | range: decided by [eq(test.t1.a, test.t2.a)], keep order:false, stats:pseudo                                     |
+-----------------------------------+----------+-----------+----------------------+------------------------------------------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

```
+---------------------------------+----------+-----------+----------------------+----------------------------------------------------------+
| id                              | estRows  | task      | access object        | operator info                                            |
+---------------------------------+----------+-----------+----------------------+----------------------------------------------------------+
| HashJoin_33                     | 9.99     | root      |                      | inner join, equal:[eq(test.t1.a, test.t2.a)]             |
| ├─TableReader_57(Build)         | 9.99     | root      |                      | data:Selection_56                                        |
| │ └─Selection_56                | 9.99     | cop[tikv] |                      | eq(test.t1.b, 1), not(isnull(test.t1.a))                 |
| │   └─TableFullScan_55          | 10000.00 | cop[tikv] | table:t1             | keep order:false, stats:pseudo                           |
| └─HashAgg_69(Probe)             | 7992.00  | root      |                      | group by:test.t2.a, funcs:firstrow(test.t2.a)->test.t2.a |
|   └─MergeJoin_76                | 12487.50 | root      |                      | inner join, left key:test.t2.a, right key:test.t1.a      |
|     ├─IndexReader_51(Build)     | 9990.00  | root      |                      | index:IndexFullScan_50                                   |
|     │ └─IndexFullScan_50        | 9990.00  | cop[tikv] | table:t1, index:a(a) | keep order:true, stats:pseudo                            |
|     └─IndexReader_49(Probe)     | 9990.00  | root      |                      | index:IndexFullScan_48                                   |
|       └─IndexFullScan_48        | 9990.00  | cop[tikv] | table:t2, index:a(a) | keep order:true, stats:pseudo                            |
+---------------------------------+----------+-----------+----------------------+----------------------------------------------------------+
```

### 4. What is your TiDB version? (Required)

Current/master (TiDB X & 8.5.5)

### PR DESCRIPTION
**Pull request by terry1purcell**
### What problem does this PR solve?

Issue Number: close #66320

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Summary by CodeRabbit

* **New Features**
  * Introduces an alternative optimization round that can convert eligible semi-joins into correlated apply-style plans, improving planner choice between join vs apply and preserving correct NULL semantics for correlated subqueries.

* **Tests**
  * Adds comprehensive test suites and fixtures covering correlated subquery behaviors (IN/EXISTS/NOT IN), null semantics, plan shapes (EXPLAIN), parallel apply, and cost-factor-driven plan selection across planner modes.

### CODE REVIEW

File: pkg/planner/core/rule_correlate.go [hunk 1]
```diff
@@ -0,0 +1,501 @@
...
+	// joins only need to know whether any matching row exists.
+	// This mirrors what expression_rewriter does for NO_DECORRELATE EXISTS.
+	if !hasLimit(innerPlan) {
+		limit := logicalop.LogicalLimit{Count: 1}.Init(join.SCtx(), join.QueryBlockOffset())
+		limit.SetChildren(innerPlan)
+		innerPlan = limit
+	}
+
+	// Build the LogicalApply.
+	ap := logicalop.LogicalApply{}.Init(join.SCtx(), join.QueryBlockOffset())
```
Comment (fixdb) [inline pkg/planner/core/rule_correlate.go:198]: hint fields are not copied into the alternative. This can cause hint behavior regressions.

Comment (terry1purcell) [reply pkg/planner/core/rule_correlate.go:198]: Fixed and added a test to cover this.

File: pkg/planner/core/expression_rewriter.go [hunk 2]
```diff
@@ -1082,6 +1082,14 @@ func (er *expressionRewriter) handleExistSubquery(ctx context.Context, planCtx *
 	// Add LIMIT 1 when noDecorrelate is true for EXISTS subqueries to enable early exit
 	corCols := coreusage.ExtractCorColumnsBySchema4LogicalPlan(np, planCtx.plan.Schema())
 	noDecorrelate := isNoDecorrelate(planCtx, corCols, hintFlags, handlingExistsSubquery)
+	// When EnableCorrelateSubquery is ON (set by the correlate alternative round),
+	// prevent decorrelation of correlated subqueries so they stay as Apply with index lookups.
+	if !noDecorrelate && len(corCols) > 0 {
+		b.ctx.GetSessionVars().RecordRelevantOptVar(vardef.TiDBOptEnableAlternativeLogicalPlans)
+		if b.ctx.GetSessionVars().EnableCorrelateSubquery {
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/expression_rewriter.go:1092]: Done

File: pkg/planner/optimize.go [hunk 3]
```diff
@@ -659,22 +680,31 @@ func optimize(ctx context.Context, sctx planctx.PlanContext, node *resolve.NodeW
...
-			adjust,
-		)
+		// Use a closure so that defer-based cleanup runs at the end of each
+		// iteration, not at function exit. This ensures session state (e.g.
+		// EnableCorrelateSubquery) is restored even if the round panics.
+		func() {
+			if round.setup != nil {
+				round.setup(sessVars)
+				defer round.cleanup(sessVars)
+			}
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/optimize.go:732]: Done

File: pkg/planner/core/rule_correlate.go [hunk 4]
```diff
@@ -0,0 +1,552 @@
...
+func (s *CorrelateSolver) Optimize(ctx context.Context, p base.LogicalPlan) (retPlan base.LogicalPlan, retChanged bool, retErr error) {
+	defer func() {
+		if r := recover(); r != nil {
+			logutil.BgLogger().Warn("CorrelateSolver panic, returning original plan",
+				zap.Any("recover", r),
+				zap.Stack("stack"))
+			retPlan = p
+			retChanged = false
+			retErr = nil
+		}
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/rule_correlate.go:46]: Done

**Comment by terry1purcell** [comment]
@pantheon-bot please review

File: pkg/planner/core/rule_correlate.go [hunk 5]
```diff
@@ -0,0 +1,509 @@
...
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/rule_correlate.go:46]: This is prior to the recent refactor. So no longer applies.

File: pkg/planner/core/rule_correlate.go [hunk 6]
```diff
@@ -0,0 +1,553 @@
...
+		IsIntHandlePath:       src.IsIntHandlePath,
+		IsCommonHandlePath:    src.IsCommonHandlePath,
+		Forced:                src.Forced,
+		ForceKeepOrder:        src.ForceKeepOrder,
+		ForceNoKeepOrder:      src.ForceNoKeepOrder,
+		ForcePartialOrder:     src.ForcePartialOrder,
+		IsUkShardIndexPath:    src.IsUkShardIndexPath,
+		IndexLookUpPushDownBy: src.IndexLookUpPushDownBy,
+		NoncacheableReason:    src.NoncacheableReason,
+	}
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/core/rule_correlate.go]: Resolved with a comment to explain why this is acceptable, and to ensure that a future reviewer/programmer isn't confused.

File: pkg/planner/optimize.go [hunk 7]
```diff
@@ -648,35 +671,57 @@ func optimize(ctx context.Context, sctx planctx.PlanContext, node *resolve.NodeW
...
+				round.adjustFlag,
+			)
+		}()
 		if err != nil {
-			return nil, nil, 0, err
+			// Alternative rounds are optional optimizations. If one fails,
+			// log and continue — the first round's plan is still valid.
+			logutil.BgLogger().Warn("alternative logical plan round failed",
+				zap.Error(err))
+			continue
```
[the remark this answers is not in the document]
Comment (terry1purcell) [reply pkg/planner/optimize.go:754]: Done

**Review by qw4990 — COMMENTED** [review]
Does this PR also solve this issue https://github.com/pingcap/tidb/issues/67854? @AilinKid

File: pkg/planner/core/rule_correlate.go [hunk 8]
```diff
@@ -0,0 +1,558 @@
...
+
+// cloneLogicalSubtree creates a shallow clone of the logical plan subtree,
+// ensuring each node has a fresh plan ID and independent mutable state (children,
+// conditions, AllConds). Immutable data (table info, column info, etc.) is shared.
+// This is used to build the Apply alternative's inner plan without modifying the
+// Join's original inner subtree when PPD pushes correlated conditions down.
+// Returns (clone, true) on success, or (nil, false) if an unhandled operator type
+// is encountered. In the failure case, the caller must abort the correlate
+// optimization to avoid corrupting the original subtree.
+func cloneLogicalSubtree(p base.LogicalPlan) (base.LogicalPlan, bool) {
```
Comment (qw4990) [inline pkg/planner/core/rule_correlate.go]: This method could be used for other purpose, could we move these Clone functions into another _util.go file? And this can also make this rule_correlate file seem simpler.

Comment (terry1purcell) [reply pkg/planner/core/rule_correlate.go]: Done

File: pkg/planner/core/rule/logical_rules.go [hunk 9]
```diff
@@ -47,6 +47,7 @@ const (
 	FlagEliminateUnionAllDualItem
 	FlagEmptySelectionEliminator
 	FlagResolveExpand
+	FlagCorrelate
```
Comment (AilinKid) [inline pkg/planner/core/rule/logical_rules.go]: how about putting FlagCorrelate ahead of FlagResolveExpand (this is annotated as it should be last one)

File: pkg/planner/core/plan_clone_utils.go [hunk 10]
```diff
@@ -69,3 +73,214 @@ func FastClonePointGetForPlanCache(newCtx base.PlanContext, src, dst *physicalop
...
+func cloneProjection(proj *logicalop.LogicalProjection) (*logicalop.LogicalProjection, bool) {
+	children, ok := cloneWithChildren(proj)
+	if !ok {
+		return nil, false
+	}
+	clone := *proj
+	clone.BaseLogicalPlan = logicalop.NewBaseLogicalPlan(
+		proj.SCtx(), proj.TP(), &clone, proj.QueryBlockOffset())
+	clone.SetSchema(proj.Schema().Clone())
+	clone.Exprs = append([]expression.Expression(nil), proj.Exprs...)
```
Comment (AilinKid) [inline pkg/planner/core/plan_clone_utils.go:195]: looks expression here, and aggDesc below and Byitems in the sort, are shallow ref usage, even the Schema().Clone() is not strictly deep-clone implemented inside, i think
1. deep clone interface should be a infra support for all logical op and expression framework, and other extended structure like byItems.
2. do not depend on shallow ref usage, like fieldType a, after shallow ref usage as filedType b by a split agg, one change, and the other change as well.
3. do not depend on pointer to change value, like correlated(*col, datum), previously we depend on A=*corr(X) to pass the datum inside, while it's not suitable for deepclone, once there is topologic with two correlated column as shallow ref usage, like A=*corr(X), B =*corr(X) as well, when deeping clone, it can not detect this same pointer, and basically clone with two different pointer, and this datum passing logic is broken. We can just use unique id to get what their value is just like parameterMarker.

Comment (AilinKid) [reply pkg/planner/core/plan_clone_utils.go:195]: all this ability should be a promising infra to support robust optimizer plan transformation without a backward concern. But it's out of this pr's scope, we can come back later, anyway, this pr do introduce desire of this capbility. /cc @qw4990 @winoros

File: pkg/planner/core/optimizer.go [hunk 11]
```diff
@@ -365,6 +362,19 @@ func adjustOptimizationFlags(flag uint64, logic base.LogicalPlan) uint64 {
 	if !logic.SCtx().GetSessionVars().StmtCtx.UseDynamicPruneMode {
 		flag |= rule.FlagPartitionProcessor // apply partition pruning under static mode
 	}
+	// FlagCorrelate is added by the correlate alternative round's flag adjuster,
+	// not here. EnableCorrelateSubquery is an internal flag toggled by the round.
+	// Recompute FlagPruneColumnsAgain after all conditional flag mutations so
+	// that conditionally-added flags (FlagCorrelate, FlagPartitionProcessor, …)
+	// are taken into account. A second column-prune pass is worthwhile when
```
Comment (AilinKid) [inline pkg/planner/core/optimizer.go]: this flag revert is complex
how about  putting FlagCorrelate ahead of secondColumnPruning, so we don't need to adjust second column pruning rule here.

File: pkg/planner/optimize.go [hunk 12]
```diff
@@ -584,16 +586,49 @@ func shouldTryOrderAwareReorderRound(sessVars *variable.SessionVars) bool {
...
+		name:       "non-decorrelate",
+		adjustFlag: func(flag uint64) uint64 { return flag &^ rule.FlagDecorrelate },
+		enabled:    shouldTryNonDecorrelationRound,
+	},
+	{
+		name:       "order-aware-reorder",
+		adjustFlag: func(flag uint64) uint64 { return flag | rule.FlagOrderAwareJoinReorder },
+		enabled:    shouldTryOrderAwareReorderRound,
+	},
+	func() alternativeRound {
```
Comment (AilinKid) [inline pkg/planner/optimize.go]: how about wrapping it as format above

File: pkg/planner/optimize.go [hunk 13]
```diff
@@ -584,16 +586,49 @@ func shouldTryOrderAwareReorderRound(sessVars *variable.SessionVars) bool {
...
-	func(flag uint64) uint64 { return flag | rule.FlagOrderAwareJoinReorder },
+// alternativeRound describes one alternative logical-plan round.
+// adjustFlag adjusts the optimization flags for the round.
+// enabled returns true when the round should be attempted.
+// setup/cleanup optionally modify session state before/after plan building.
+type alternativeRound struct {
+	name       string
+	adjustFlag func(uint64) uint64
+	enabled    func(*variable.SessionVars) bool
+	setup      func(*variable.SessionVars)
```
Comment (AilinKid) [inline pkg/planner/optimize.go:602]: interesting setup and cleanup, i remember restoreLogicalPlanBuildCtx will restore the session var back to a clean state, maybe it has some overlap with cleanup func here.

**Review by AilinKid — COMMENTED** [review]
rest LGTM, amazing correlate round!

File: pkg/planner/core/plan_clone_utils.go (hunk 10 above)
Comment (qw4990) [reply pkg/planner/core/plan_clone_utils.go:195]: Agree, @AilinKid , we do run into similar problems about shallow/deep plan cloning when supporting features like multi-alternative plans, plan cache, cascades, and complex plan transformations like this rule. We do need a robust, safe plan/op clone infrastructure for the optimizer.
Yeah, and this is beyond this PR's scope. Let's discuss more after merging this.

File: pkg/planner/core/rule_correlate.go [hunk 14]
```diff
@@ -0,0 +1,345 @@
...
+		// PPD failed (e.g., conditions reference columns pruned from the
+		// DataSource schema); abort the correlate optimization.
+		return p, planChanged, nil
+	}
+
+	// Reset stats on DataSources that received correlated conditions so DeriveStats
+	// re-runs during physical optimization. This is necessary because the original
+	// DeriveStats ran before the correlate rule added correlated conditions, so the
+	// index access paths were built without them.
+	resetStatsForCorrelatedDS(innerPlan)
```
Comment (qw4990) [inline pkg/planner/core/rule_correlate.go:184]: Not sure whether we really need to refresh stats, in my opinion, logical optimization doesn't need stats.
Rest LGTM.

**Review by qw4990 — APPROVED** [review]

File: pkg/planner/core/rule_correlate.go (hunk 14 above)
Comment (terry1purcell) [reply pkg/planner/core/rule_correlate.go:184]: Claude code response:  The stats reset isn't for logical optimization's benefit — it's to force DeriveStats to re-run during physical optimization. deriveStats4DataSource (stats.go:112) early-returns when StatsInfo() != nil, skipping fillIndexPath which builds index access ranges. Since our rule pushes correlated conditions into the DataSource after the initial DeriveStats already ran and cached stats, without this reset the access paths would never be rebuilt with the correlated predicates, and the inner side would only do full scans. The name is admittedly a bit misleading — it's really about invalidating the cache so access paths get rebuilt, not about needing stats during logical optimization.

File: pkg/planner/core/plan_clone_utils.go (hunk 10 above)
Comment (terry1purcell) [reply pkg/planner/core/plan_clone_utils.go:195]: Got it - thank you both

File: pkg/planner/core/optimizer.go (hunk 11 above)
Comment (terry1purcell) [reply pkg/planner/core/optimizer.go]: Good call — moving CorrelateSolver (and FlagCorrelate) ahead of the second ColumnPruner in both the rule list and the iota block would let the standard FlagPruneColumnsAgain logic work naturally, eliminating the recomputation block. The correlate rule doesn't depend on PushDownSequence/EliminateUnionAllDualItem/EmptySelectionEliminator/ResolveExpand, so the reorder should be safe.

Change will be made in next commit.

File: pkg/planner/optimize.go (hunk 13 above)
Comment (terry1purcell) [reply pkg/planner/optimize.go:602]: From claude-code:
This comment is reasonable — both are "restore state before/after a round" — but they target different state. 
restoreLogicalPlanBuildCtx doesn't save/restore EnableCorrelateSubquery because it's not part of the plan-build context snapshot.                                                                                                                    
                                                                                                                               
One option would be to add EnableCorrelateSubquery to logicalPlanBuildCtx so everything is restored in one place, eliminating the need for setup/cleanup. But that would couple a round-specific concern into the general restore function. The current approach keeps the correlate round's state management self-contained.

File: pkg/planner/optimize.go (hunk 12 above)
Comment (terry1purcell) [reply pkg/planner/optimize.go]: Fair point that this looks inconsistent.  The cleanest fix is to move old to a package var and use a plain struct literal.

Adding in next commit.

**Review by yudongusa — APPROVED** [review]
Please open a document PR on this
