### PR TITLE
disttask: cancel subtask context if scheduled away

### LINKED ISSUE #58450: Ingest writer memory consumption raised TiDB OOM in the million tables of dml and ddl scenario
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

3 million tables and dml
ddl(add column/index, change column type) of concurrency 64
Image

### 4. What is your TiDB version? (Required)

 Release Version: v8.5.0-alpha-410-gd0ea9e50d5
Edition: Community
Git Commit Hash: d0ea9e50d5a9d78269172c95d641b49293087f5d
Git Branch: HEAD
UTC Build Time: 2024-12-21 05:26:21
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #58450

Problem Summary: See https://github.com/pingcap/tidb/issues/58450#issuecomment-2565218662

### What changed and how does it work?

Cancel subtask context if scheduled away.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 1]
```diff
@@ -307,7 +308,9 @@ func (e *BaseTaskExecutor) Run() {
 		// reset it when we get a subtask
 		checkInterval, noSubtaskCheckCnt = SubtaskCheckInterval, 0
 
-		if e.stepExec != nil && e.stepExec.GetStep() != subtask.Step {
+		if e.stepExec != nil &&
+			(e.stepExec.GetStep() != subtask.Step ||
+				e.stepCtx.Err() != nil) { // Previous step ctx is done, cleanup and use a new one.
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:313]: check `e.stepCtx.Err()` separately, we don't need to recreate step executor when the task is cancelled, we can continue and let L289 breaks it

and you need to handle the case in L146 by cancel a `subtask context`, not a `step context`

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 2]
```diff
@@ -122,7 +122,7 @@ func NewBaseTaskExecutor(ctx context.Context, task *proto.Task, param Param) *Ba
 //     `pending` state, to make sure subtasks can be balanced later when node scale out.
 //   - If current running subtask are scheduled away from this node, i.e. this node
 //     is taken as down, cancel running.
-func (e *BaseTaskExecutor) checkBalanceSubtask(ctx context.Context) {
+func (e *BaseTaskExecutor) checkBalanceSubtask(ctx context.Context, subtaskCancelCtx context.CancelFunc) {
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:125]:
```suggestion
func (e *BaseTaskExecutor) checkBalanceSubtask(ctx context.Context, subtaskCtxCancel context.CancelFunc) {
```

File: pkg/disttask/framework/taskexecutor/task_executor.go [hunk 3]
```diff
@@ -418,23 +425,25 @@ func (e *BaseTaskExecutor) runSubtask(subtask *proto.Subtask) (resErr error) {
 	logTask := llog.BeginTask(logger, "run subtask")
 	subtaskErr := func() error {
 		e.currSubtaskID.Store(subtask.ID)
+		subtaskCtx, subtaskCancelCtx := context.WithCancel(e.stepCtx)
```
Comment (D3Hunter) [inline pkg/disttask/framework/taskexecutor/task_executor.go:428]:
```suggestion
		subtaskCtx, subtaskCtxCancel := context.WithCancel(e.stepCtx)
```

**Review by D3Hunter — APPROVED** [review]
rest lgtm

**Review by wjhuang2016 — APPROVED** [review]
