### PR TITLE
store/copr: fix build batchCop in disaggregated tiflash mode

### LINKED ISSUE #40035: Refine batchCop in disaggregated tiflash mode

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #40035

Problem Summary: 
1. In disaggregated tiflash mode, before send request to tiflash store, send `CmdMPPAlive` to check if it's alive.
2. Send batchCop task by ConsistentHash(region_id)

### Check List

Tests 

- [ ] Unit test
- [x] Integration test: https://github.com/pingcap/endless/pull/1282
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: store/copr/batch_request_sender.go [hunk 1]
```diff
@@ -100,22 +98,18 @@ func (ss *RegionBatchRequestSender) onSendFailForBatchRegions(bo *Backoffer, ctx
 		return tikverr.ErrTiDBShuttingDown
 	}
 
-	if config.GetGlobalConfig().DisaggregatedTiFlash {
```
Comment (guo-shaoge) [inline store/copr/batch_request_sender.go:103]: Delete this if branch because there will be no batchCop protocol in disaggregated tiflash mode. Also mpp error handling will be handled in `mpp.go`

File: store/copr/batch_coprocessor.go [hunk 2]
```diff
@@ -540,49 +515,154 @@ func buildBatchCopTasksForPartitionedTable(bo *backoff.Backoffer,
...
+
+	failpointCheckForConsistentHash(res)
+	return res, nil
+}
+
+func failpointCheckForConsistentHash(tasks []*batchCopTask) {
+	failpoint.Inject("checkOnlyDispatchToTiFlashComputeNodes", func(val failpoint.Value) {
+		logutil.BgLogger().Debug("in checkOnlyDispatchToTiFlashComputeNodes")
+
+		// This failpoint will be tested in test-infra case, because we needs setup a cluster.
```
Comment (guo-shaoge) [inline store/copr/batch_coprocessor.go:647]: case: https://github.com/pingcap/endless/pull/1282/files#diff-905e7ac2f4b906af34cf66a4615707af011934de800374cb252ab9a5ad749d48

File: store/copr/batch_coprocessor.go [hunk 3]
```diff
@@ -540,49 +515,152 @@ func buildBatchCopTasksForPartitionedTable(bo *backoff.Backoffer,
...
-	if len(stores) == 0 {
-		return nil, errors.New("No available tiflash_compute node")
-	}
+func filterAliveStores(ctx context.Context, stores []*tikv.Store, ttl time.Duration, kvStore *kvStore) []*tikv.Store {
+	var aliveStores []*tikv.Store
+	var wg sync.WaitGroup
+	var mu sync.Mutex
+	wg.Add(len(stores))
+	for i := range stores {
+		go func(idx int) {
```
Comment (XuHuaiyu) [inline store/copr/batch_coprocessor.go:524]: will this start too many goroutines?

File: store/copr/mpp.go [hunk 4]
```diff
@@ -254,14 +254,14 @@ func (m *mppIterator) handleDispatchReq(ctx context.Context, bo *Backoffer, req
 	if originalTask != nil {
 		sender := NewRegionBatchRequestSender(m.store.GetRegionCache(), m.store.GetTiKVClient(), m.enableCollectExecutionInfo)
 		rpcResp, retry, _, err = sender.SendReqToAddr(bo, originalTask.ctx, originalTask.regionInfos, wrappedReq, tikv.ReadTimeoutMedium)
-		if err != nil && disaggregatedTiFlash {
```
Comment (XuHuaiyu) [inline store/copr/mpp.go:257]: why remove this?

Comment (guo-shaoge) [reply store/copr/mpp.go:257]: In [(ss *RegionBatchRequestSender) SendReqToAddr](https://github.com/guo-shaoge/tidb/blob/bd76d19d9cfd1310af64217fa17bf2f6a53b3a7a/store/copr/batch_request_sender.go#L80), will check err and set RPCError. Also the returned err will be changed to nil if `onSendFailForBatchRegions` succeed.

File: store/copr/batch_coprocessor.go (hunk 3 above)
Comment (guo-shaoge) [reply store/copr/batch_coprocessor.go:524]: Normally the max number of tiflash will not be greater than 100.

**Review by XuHuaiyu — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]
