### PR TITLE
session, table: fix listColumnPartition data race

### LINKED ISSUE #33030: DATA RACE in the TestLocatePartition
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
==================
WARNING: DATA RACE
Write at 0x00c003f0f748 by goroutine 82:
  github.com/pingcap/tidb/table/tables.(*ForListColumnPruning).buildPartitionValueMapAndSorted()
      /go/tidb/table/tables/partition.go:790 +0x6b4
  github.com/pingcap/tidb/table/tables.(*ForListColumnPruning).LocatePartition()
      /go/tidb/table/tables/partition.go:834 +0x51
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locateColumnPartitionsByCondition()
      /go/tidb/planner/core/rule_partition_processor.go:489 +0x3a7
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locatePartitionByColumn()
      /go/tidb/planner/core/rule_partition_processor.go:472 +0x204
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locatePartition()
      /go/tidb/planner/core/rule_partition_processor.go:406 +0x1a4
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locatePartitionByCNFCondition()
      /go/tidb/planner/core/rule_partition_processor.go:418 +0xfe
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).findUsedListColumnsPartitions()
      /go/tidb/planner/core/rule_partition_processor.go:544 +0x64
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).findUsedListPartitions()
      /go/tidb/planner/core/rule_partition_processor.go:606 +0x1f8
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneListPartition()
      /go/tidb/planner/core/rule_partition_processor.go:625 +0xdd
  github.com/pingcap/tidb/planner/core.PartitionPruning()
      /go/tidb/planner/core/partition_prune.go:49 +0x199
  github.com/pingcap/tidb/planner/core.partitionAccessObject()
      /go/tidb/planner/core/explain.go:394 +0x1e6
  github.com/pingcap/tidb/planner/core.getAccessObjectForTableScan()
      /go/tidb/planner/core/explain.go:345 +0x1e4
  github.com/pingcap/tidb/planner/core.(*PhysicalTableReader).accessObject()
      /go/tidb/planner/core/explain.go:354 +0x18f
  github.com/pingcap/tidb/planner/core.(*Explain).getOperatorInfo()
      /go/tidb/planner/core/common_plans.go:1524 +0x2ef
  github.com/pingcap/tidb/planner/core.(*Explain).prepareOperatorInfo()
      /go/tidb/planner/core/common_plans.go:1480 +0x184
  github.com/pingcap/tidb/planner/core.(*Explain).explainPlanInRowFormat()
      /go/tidb/planner/core/common_plans.go:1318 +0xd5
  github.com/pingcap/tidb/planner/core.(*Explain).RenderResult()
      /go/tidb/planner/core/common_plans.go:1273 +0x268
  github.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo()
      /go/tidb/executor/explain.go:108 +0x72
  github.com/pingcap/tidb/executor.(*ExplainExec).Next()
      /go/tidb/executor/explain.go:59 +0xa4
  github.com/pingcap/tidb/executor.Next()
      /go/tidb/executor/executor.go:302 +0x56f
  github.com/pingcap/tidb/executor.(*recordSet).Next()
      /go/tidb/executor/adapter.go:149 +0x13b
  github.com/pingcap/tidb/session.(*execStmtResult).Next()
      <autogenerated>:1 +0x7b
  github.com/pingcap/tidb/session.GetRows4Test()
      /go/tidb/session/tidb.go:325 +0xea
  github.com/pingcap/tidb/session.ResultSetToStringSlice()
      /go/tidb/session/tidb.go:343 +0xb4
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResultWithCtx()
      /go/tidb/testkit/testkit.go:175 +0xbc
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResult()
      /go/tidb/testkit/testkit.go:170 +0x26a
  github.com/pingcap/tidb/testkit.(*TestKit).MustQuery()
      /go/tidb/testkit/testkit.go:110 +0x270
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition.func1()
      /go/tidb/table/tables/partition_test.go:430 +0x64
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition.func2.1()
      /go/tidb/table/tables/partition_test.go:436 +0x3e
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      /go/tidb/util/wait_group_wrapper.go:33 +0x7e
Previous read at 0x00c003f0f748 by goroutine 165:
  runtime.racereadrange()
      <autogenerated>:1 +0x1b
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locateColumnPartitionsByCondition()
      /go/tidb/planner/core/rule_partition_processor.go:514 +0x6f2
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locatePartitionByColumn()
      /go/tidb/planner/core/rule_partition_processor.go:472 +0x204
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locatePartition()
      /go/tidb/planner/core/rule_partition_processor.go:406 +0x1a4
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).locatePartitionByCNFCondition()
      /go/tidb/planner/core/rule_partition_processor.go:418 +0xfe
  github.com/pingcap/tidb/planner/core.(*listPartitionPruner).findUsedListColumnsPartitions()
      /go/tidb/planner/core/rule_partition_processor.go:544 +0x64
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).findUsedListPartitions()
      /go/tidb/planner/core/rule_partition_processor.go:606 +0x1f8
  github.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneListPartition()
      /go/tidb/planner/core/rule_partition_processor.go:625 +0xdd
  github.com/pingcap/tidb/planner/core.PartitionPruning()
      /go/tidb/planner/core/partition_prune.go:49 +0x199
  github.com/pingcap/tidb/planner/core.partitionAccessObject()
      /go/tidb/planner/core/explain.go:394 +0x1e6
  github.com/pingcap/tidb/planner/core.getAccessObjectForTableScan()
      /go/tidb/planner/core/explain.go:345 +0x1e4
  github.com/pingcap/tidb/planner/core.(*PhysicalTableReader).accessObject()
      /go/tidb/planner/core/explain.go:354 +0x18f
  github.com/pingcap/tidb/planner/core.(*Explain).getOperatorInfo()
      /go/tidb/planner/core/common_plans.go:1524 +0x2ef
  github.com/pingcap/tidb/planner/core.(*Explain).prepareOperatorInfo()
      /go/tidb/planner/core/common_plans.go:1480 +0x184
  github.com/pingcap/tidb/planner/core.(*Explain).explainPlanInRowFormat()
      /go/tidb/planner/core/common_plans.go:1318 +0xd5
  github.com/pingcap/tidb/planner/core.(*Explain).RenderResult()
      /go/tidb/planner/core/common_plans.go:1273 +0x268
  github.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo()
      /go/tidb/executor/explain.go:108 +0x72
  github.com/pingcap/tidb/executor.(*ExplainExec).Next()
      /go/tidb/executor/explain.go:59 +0xa4
  github.com/pingcap/tidb/executor.Next()
      /go/tidb/executor/executor.go:302 +0x56f
  github.com/pingcap/tidb/executor.(*recordSet).Next()
      /go/tidb/executor/adapter.go:149 +0x13b
  github.com/pingcap/tidb/session.(*execStmtResult).Next()
      <autogenerated>:1 +0x7b
  github.com/pingcap/tidb/session.GetRows4Test()
      /go/tidb/session/tidb.go:325 +0xea
  github.com/pingcap/tidb/session.ResultSetToStringSlice()
      /go/tidb/session/tidb.go:343 +0xb4
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResultWithCtx()
      /go/tidb/testkit/testkit.go:175 +0xbc
  github.com/pingcap/tidb/testkit.(*TestKit).ResultSetToResult()
      /go/tidb/testkit/testkit.go:170 +0x26a
  github.com/pingcap/tidb/testkit.(*TestKit).MustQuery()
      /go/tidb/testkit/testkit.go:110 +0x270
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition.func1()
      /go/tidb/table/tables/partition_test.go:430 +0x64
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition.func2.1()
      /go/tidb/table/tables/partition_test.go:436 +0x3e
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      /go/tidb/util/wait_group_wrapper.go:33 +0x7e
Goroutine 82 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      /go/tidb/util/wait_group_wrapper.go:31 +0xde
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition.func2()
      /go/tidb/table/tables/partition_test.go:435 +0x126
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition()
      /go/tidb/table/tables/partition_test.go:440 +0x2eb
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Goroutine 165 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      /go/tidb/util/wait_group_wrapper.go:31 +0xde
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition.func2()
      /go/tidb/table/tables/partition_test.go:435 +0x126
  github.com/pingcap/tidb/table/tables_test.TestLocatePartition()
      /go/tidb/table/tables/partition_test.go:440 +0x2eb
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
================== 
```

### PR DESCRIPTION
**Pull request by zimulala**
### What problem does this PR solve?

Issue Number: close #33030

Problem Summary:
`ForListColumnPruning` has a lot of fields, if we use the lock to fix data race, it will make the code dirty.
So I change the way to fix https://github.com/pingcap/tidb/issues/32416.

#32416 :
**In step 1**

In the bootstrap phase, new collation is true
After bootstrap ends, new collation is false.

**In step 2**

a. In the bootstrap phase, new collation is true. ForListColumnPruning builds the hashMap(generate the partition hash key, by calling  `EncodeKey`) in TableFromMeta

b. After bootstrap ends, new collation is false. The generated partition hash key(by calling `EncodeKey`) could not be found in the hashMap.

### What is changed and how it works?
This way I will rebuild hashMap with `new collation is false` after step 2.a. Then we can find the key in step 2.b.

### Check List

Tests 

- [ ] Unit test
Tests already exist: TestLocatePartition

- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

1. Set the `new_collations_enabled_on_first_bootstrap` item to false and run the SQL statements as follows:
```
set @@session.tidb_enable_list_partition = ON;
set @@tidb_partition_prune_mode = 'dynamic';
drop table if exists github_events;
CREATE TABLE `github_events` (
`id` bigint(20) DEFAULT NULL,
`type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
PARTITION BY LIST COLUMNS(`type`)
(PARTITION `push_event` VALUES IN ("PushEvent"),
PARTITION `watch_event` VALUES IN ("WatchEvent")
);
```
2. Restart TiDB with `new_collations_enabled_on_first_bootstrap = false` and execute the following statements:
```
tidb> set @@session.tidb_enable_list_partition = ON;
Query OK, 0 rows affected (0.00 sec)

tidb> set @@tidb_partition_prune_mode = 'dynamic';
Query OK, 0 rows affected (0.00 sec)

tidb> desc select id,type from github_events  where  type = 'WatchEvent';
+-------------------------+----------+-----------+-----------------------+-------------------------------------------+
| id                      | estRows  | task      | access object         | operator info                             |
+-------------------------+----------+-----------+-----------------------+-------------------------------------------+
| TableReader_7           | 10.00    | root      | partition:watch_event | data:Selection_6                          |
| └─Selection_6           | 10.00    | cop[tikv] |                       | eq(test.github_events.type, "WatchEvent") |
|   └─TableFullScan_5     | 10000.00 | cop[tikv] | table:github_events   | keep order:false, stats:pseudo            |
+-------------------------+----------+-----------+-----------------------+-------------------------------------------+
3 rows in set (0.00 sec)
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the data race when using the list column partition.
```

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @wjhuang2016 @tiancaiamao @crazycs520

**Review by crazycs520 — APPROVED** [review]

**Comment by tiancaiamao** [comment]
PTAL @wjhuang2016

File: table/tables/partition.go [hunk 1]
```diff
@@ -760,22 +763,26 @@ func (lp *ForListPruning) locateListColumnsPartitionByRow(ctx sessionctx.Context
...
 		return nil
 	}
 
-	p := parser.New()
+	return lp.buildListPartitionValueMapAndSorted(p)
+}
+
+// RebuildPartitionValueMapAndSorted rebuilds list columns partition value map for the specified column.
+func (lp *ForListColumnPruning) RebuildPartitionValueMapAndSorted(p *parser.Parser) error {
+	return lp.buildListPartitionValueMapAndSorted(p)
```
Comment (wjhuang2016) [inline table/tables/partition.go:780]: Before rebuilding the new hashMap, do we need to clean the existed hashMap?

**Comment by zimulala** [comment]
PTAL @wjhuang2016

**Review by wjhuang2016 — APPROVED** [review]

**Comment by Defined2014** [comment]
@morgo @bb7133 @cfzjywxk 
PTAL

File: session/bootstrap.go [hunk 2]
```diff
@@ -2002,3 +2004,32 @@ func oldPasswordUpgrade(pass string) (string, error) {
...
+	p := parser.New()
+	is := s.GetInfoSchema().(infoschema.InfoSchema)
+	for _, dbInfo := range is.AllSchemas() {
+		for _, t := range is.SchemaTables(dbInfo.Name) {
+			pi := t.Meta().GetPartitionInfo()
+			if pi == nil || pi.Type != model.PartitionTypeList {
+				continue
+			}
+
+			pe, err := t.(partitionExpr).PartitionExpr()
```
Comment (bb7133) [inline session/bootstrap.go:2023]: I don't think it's a good style, IMO a better way to do it is something like:

```
pt := t.(table.PartitionedTable); err != nil {
    panic(...)
}
pe, err := t.PartitionExpr()
```
Which is more clear. However, some extra changes are required and it might not be a good idea to make it in this PR.

Comment (zimulala) [reply session/bootstrap.go:2023]: However, it is already confirmed that it is a partitioned table, so theoretically this(`t.(partitionExpr)`) should not report an error.

File: session/bootstrap.go [hunk 3]
```diff
@@ -2002,3 +2004,32 @@ func oldPasswordUpgrade(pass string) (string, error) {
...
+			if err != nil {
+				panic("partition table gets partition expression failed")
+			}
+			for _, cp := range pe.ColPrunes {
+				if err = cp.RebuildPartitionValueMapAndSorted(p); err != nil {
+					logutil.BgLogger().Warn("build list column partition value map and sorted failed")
```
[the remark this answers is not in the document]
Comment (zimulala) [reply session/bootstrap.go:2029]: Failure here should only result in failure when locating a partition.

**Comment by zimulala** [comment]
PTAL  @bb7133

**Review by bb7133 — APPROVED** [review]
LGTM
