### PR TITLE
planner/core: fix leading hint mismatch causing missing other conditions

### LINKED ISSUE #65795: planner: LEADING hint cause wrong join results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[case_0002_019bf5c4-4b51-73c4-95fd-c51d8af1de04.zip](https://github.com/user-attachments/files/24846697/case_0002_019bf5c4-4b51-73c4-95fd-c51d8af1de04.zip)

#### Base SQL
  ```sql
  SELECT t1.id AS c0, '2024-01-09 08:34:00' AS c1, ABS(t2.id) AS c2
  FROM t0 RIGHT JOIN t2 ON (t0.k1 = t2.k1)
  JOIN t3 ON (t0.k2 = t3.k2)
  LEFT JOIN t1 ON (t0.k0 = t1.k0)
  WHERE (((t2.k1 < t3.k2) AND (t0.k0 = t1.k0)) AND ((t0.k0 <=> t1.k0) AND (t0.k1 = t3.k2)))
  ORDER BY UPPER('s30');
```
####  Hinted SQL
```sql
  SELECT /*+ LEADING(t0, t2, t3, t1) */ t1.id AS c0, '2024-01-09 08:34:00' AS c1, ABS(t2.id) AS c2
  FROM t0 RIGHT JOIN t2 ON (t0.k1 = t2.k1)
  JOIN t3 ON (t0.k2 = t3.k2)
  LEFT JOIN t1 ON (t0.k0 = t1.k0)
  WHERE (((t2.k1 < t3.k2) AND (t0.k0 = t1.k0)) AND ((t0.k0 <=> t1.k0) AND (t0.k1 = t3.k2)))
  ORDER BY UPPER('s30');
```

### 2. What did you expect to see? (Required)
- Expected (base): cnt=0 checksum=0
### 3. What did you see instead (Required)
- Actual (hinted): cnt=1 checksum=661747633
### 4. What is your TiDB version? (Required)

```
"Release Version: v9.0.0-beta.2.pre-1112-g0dd5a8be21
Edition: Community
Git Commit Hash: 0dd5a8be2182902ace22cb78f79780cde54d0872
Git Branch: HEAD
UTC Build Time: 2026-01-24 01:53:51
GoVersion: go1.25.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Kernel Type: Classic",
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #65795

Problem Summary:   Leading hint processing could remove other conditions when the hint is inapplicable (e.g., split join groups with NullEQ), causing missing filters in the final plan.

### What changed and how does it work?
 Restore other conditions if leading hint processing fails, and add a regression test to ensure the filter stays in the plan when the hint is inapplicable.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: fix leading hint mismatch dropping other conditions
```

### CODE REVIEW

File: pkg/planner/core/rule_join_reorder.go [hunk 1]
```diff
@@ -428,8 +428,16 @@ func (s *baseSingleGroupJoinOrderSolver) generateLeadingJoinGroup(
 	if hintInfo == nil || hintInfo.LeadingList == nil {
 		return false, nil
 	}
+	// Leading hint processing can partially build join trees and consume otherConds.
+	// If the hint is inapplicable, restore original otherConds to avoid losing filters.
+	origOtherConds := make([]expression.Expression, len(s.otherConds))
+	copy(origOtherConds, s.otherConds)
```
Comment (hawkingrei) [inline pkg/planner/core/rule_join_reorder.go]: We can use ```slices.Clone``` here.

**Review by AilinKid — APPROVED** [review]
