### PR TITLE
ddl: merge continuous key ranges in FLASHBACK CLUSTER job args

### LINKED ISSUE #54915: FLASHBACK CLUSTER may enter deadloop if too many databases
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use the UT `TestFlashbackClusterWithManyDBs` in #54914

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #54915

Problem Summary:

### What changed and how does it work?

as title

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/executor/recover_test.go [hunk 1]
```diff
@@ -690,3 +690,37 @@ func MockGC(tk *testkit.TestKit) (string, string, string, func()) {
...
+	backup := kv.TxnEntrySizeLimit.Load()
+	kv.TxnEntrySizeLimit.Store(50000)
+	t.Cleanup(func() {
+		kv.TxnEntrySizeLimit.Store(backup)
+	})
+
+	tk.MustExec("set @@global.tidb_ddl_error_count_limit = 2")
+	tk.MustExec("set @@global.tidb_enable_fast_create_table=ON")
+
+	for i := 0; i < 400; i++ {
```
Comment (D3Hunter) [inline pkg/executor/recover_test.go:713]: you can create them in parallel to be faster, as in https://github.com/pingcap/tidb/pull/55025/files#diff-3c769a746cec11d5c583a7ad47b92b8a90a1b8d8e3cb86a7f368de7deb5f71b9R660-R661

File: pkg/executor/recover_test.go [hunk 2]
```diff
@@ -690,3 +690,37 @@ func MockGC(tk *testkit.TestKit) (string, string, string, func()) {
...
+		tk.MustExec(fmt.Sprintf("create database db_%d", i))
+	}
+
+	ts, _ := tk.Session().GetStore().GetOracle().GetTimestamp(context.Background(), &oracle.Option{})
```
Comment (D3Hunter) [inline pkg/executor/recover_test.go:717]:
```suggestion
	ts, _ := store.CurrentVersion(oracle.GlobalTxnScope)
```

File: pkg/executor/recover_test.go [hunk 3]
```diff
@@ -690,3 +690,37 @@ func MockGC(tk *testkit.TestKit) (string, string, string, func()) {
...
+	flashbackTs := oracle.GetTimeFromTS(ts)
```
Comment (D3Hunter) [inline pkg/executor/recover_test.go:718]: this ts is after all database created, so `flashback cluster` does nothing?

File: pkg/ddl/cluster.go [hunk 4]
```diff
@@ -349,10 +349,52 @@ func GetTableDataKeyRanges(nonFlashbackTableIDs []int64) []kv.KeyRange {
...
+	r       kv.KeyRange
+	exclude bool
+}
+
+// appendContinuousKeyRanges merges not exclude continuous key ranges and appends
+// to given []kv.KeyRange, assuming the gap between key ranges has no data.
+//
+// Precondition: schemaKeyRanges is sorted by start key. schemaKeyRanges are
+// non-overlapping.
+func appendContinuousKeyRanges(result []kv.KeyRange, schemaKeyRanges []keyRangeMayExclude) []kv.KeyRange {
```
Comment (D3Hunter) [inline pkg/ddl/cluster.go:362]:
```suggestion
func mergeContinuousKeyRanges(result []kv.KeyRange, schemaKeyRanges []keyRangeMayExclude) []kv.KeyRange {
```

File: pkg/executor/recover_test.go (hunk 3 above)
Comment (lance6716) [reply pkg/executor/recover_test.go:718]: In the old behaviour this test will fail (stuck) because KV entry exceed limitation. I can add a comment in next commit

File: pkg/ddl/cluster.go (hunk 4 above)
Comment (lance6716) [reply pkg/ddl/cluster.go:362]: I want to mention the input slice will be `append`ed, so I prefer keep the old name

Comment (D3Hunter) [reply pkg/ddl/cluster.go:362]: maybe avoid modifying input param, ok to leave it anyway

**Review by D3Hunter — APPROVED** [review]
