### PR TITLE
config, util.kvcache: support the memory guard to prevent OOM for the plan cache

### LINKED ISSUE #8330: plan-cache memory leak
## Bug Report

1. What did you do?
If possible, provide a recipe for reproducing the error.

- enable plan-cache and set a big plan-cache capacity
- open mulitple connections to tidb and for each of them do a dead loop to "prepare -> execute -> deallocate" 
- see memory metric from granafna or htop.

can reproduce using this java code

```java
		Connection connection = null;
		PreparedStatement ps = null;
		try {
			connection = dataSource.getConnection();
			ps = connection.prepareStatement(" INSERT INTO TEST_TBL (COL0,COL1,COL2,COL3,COL4,COL5,COL6,COL7,COL8) VALUES(?,?,?,?,?,?,?,?,NOW(3)) ON DUPLICATE KEY UPDATE COL6=values(col6), COL7=values(col7), COL8=values(col8)");
			while (true) {
				try {
					for (int i1 = 0; i1 < 100; i1++) {
						ps.setString(1, i1 + "1");
						ps.setInt(2, 1);
						ps.setString(3, "1");
						ps.setInt(4, 1);
						ps.setInt(5, 1);
						ps.setString(6, "1");
						ps.setString(7, "1");
						ps.setDate(8, new Date(System.currentTimeMillis()));
						ps.addBatch();
					}
					ps.executeBatch();
					System.out.println("write one batch");
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			closeAll(connection, ps);
		}
```

with jdbc url param:

```
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
spring.datasource.hikari.data-source-properties.allowMultiQueries=true
```

2. What did you expect to see?

tidb memory increase then keep a value

3. What did you see instead?

always increase and OOM

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

- 2.0.1.rc5

### PR DESCRIPTION
**Pull request by dbjoa**
### What problem does this PR solve? 
Fix #8330 

### What is changed and how it works?
* add new configuration parameters to represent the memory guard ratio and the total memory size  to prevent OOM for the plan cache 
* cache a new input item only if the ratio of the available memory to the total memory size is larger than the memory guard ratio
* compute the current memory usage approximately by using ``gopsutil.VirtualMemory()`` whenever the new element is put

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has changed the default value
 - Has added a new configuration parameter

Side effects

 - None

Related changes

 - Need to be included in the release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/8339)

### CODE REVIEW

**Comment by lysu** [comment]
Hi @dbjoa Thanks for your PR!

but use `runtime.ReadMemStats` to calcualte memory maybe have some question need be address

1. ReadMemStats is global runtime stats

there are maybe other memory alloc happen between 'memBefore' and 'memAfter', e.g. other user request's goroutine are doing hash join.

2. ReadMemStats seem be heavy operation.

```
func ReadMemStats(m *MemStats) {
	stopTheWorld("read mem stats")

	systemstack(func() {
		readmemstats_m(m)
	})

	startTheWorld()
}
```

itself do STW

**Comment by dbjoa** [comment]
@lysu  I also aware that. If new prepared statements are put into the plan cache massively, the PR will be the cause of the performance drop. However, IMHO, the scenario might not be practical because the prepared statements are determined in advance and the number of them can be limited.

File: util/kvcache/simple_lru.go [hunk 1]
```diff
@@ -73,6 +78,13 @@ func (l *SimpleLRUCache) Put(key Key, value Value) {
 		return
 	}
 
+	var rtm runtime.MemStats
+	runtime.ReadMemStats(&rtm)
+
+	if rtm.Alloc > uint64(float64(l.quota)*(1.0-l.guard)) {
```
Comment (eurekaka) [inline util/kvcache/simple_lru.go]: - `MemQuotaQuery` seems to be a session level variable controlling memory usage for each SQL query, while `runtime.ReadMemStats` get memory usage at `tidb-server` process level, these 2 are not comparable?
- if we simply return when guard ratio is hit, it is inconsistent with virtue of LRU. Shall we remove cache entries from back until we can safely put this entry in?

**Comment by zz-jason** [comment]
How about this solution:
1. limit the global memory usage of the plan cache, we can use a new config item to achieve this.
2. use https://github.com/OneOfOne/go-utils/tree/master/memory/ to calculate the memory usage of the to-be-cached plan and key.
3. remove the least used cache item from that session level plan cache until the to-be-cached plan is safe to push into the cache?

**Comment by dbjoa** [comment]
@zz-jason 
(2) I've tested the method mentioned by you already. Due to its performance issue, I had to abandon the using of ``memory.SizeOf``. That is, for a simple plan, ``TableReader``, the ``SizeOf`()`` takes ``7.1s`` to compute the plan size (``103449103``). Here is an example for a simple query:
```
mysql> prepare stmt_sel2 from 'select * from prepare_test where id > ?';
mysql> set @a=1;execute stmt_sel2 using @a;
``` 

How about to remove the least recently used items until the memory guard condition is met?
(Note: this method should call ``runtime.ReadMemStats`` whenever deleting the item)

File: util/kvcache/simple_lru.go (hunk 1 above)
Comment (dbjoa) [reply util/kvcache/simple_lru.go]: @eurekaka 
(1) I agree that ``MemQuotaQuery`` is not the same level. I should define another configuration to represent the system-wide memory quota or detect the system memory size.
(2) Sure, we can remove the least recently used items until the memory guard condition is met.

Comment (dbjoa) [reply util/kvcache/simple_lru.go]: The updated PR addresses the two comments.

File: tidb-server/main.go [hunk 2]
```diff
@@ -403,6 +404,13 @@ func setGlobalVars() {
 	plannercore.SetPreparedPlanCache(config.CheckTableBeforeDrop || cfg.PreparedPlanCache.Enabled)
 	if plannercore.PreparedPlanCacheEnabled() {
 		plannercore.PreparedPlanCacheCapacity = cfg.PreparedPlanCache.Capacity
+		plannercore.PreparedPlanCacheMemoryGuardRatio = cfg.PreparedPlanCache.MemoryGuardRatio
+		plannercore.PreparedPlanCacheMaxMemory = cfg.Performance.MaxMemory
+		if plannercore.PreparedPlanCacheMaxMemory == 0 {
+			v, err := mem.VirtualMemory()
```
Comment (eurekaka) [inline tidb-server/main.go]: According to https://github.com/shirou/gopsutil/blob/3b882b034ca24606010516bb521239cfcaf69cbd/mem/mem_linux.go#L40, though the function name is `VirtualMemory()`, `v.Total` actually is the physical memory of the machine, because the data source is `MemTotal` of `/proc/meminfo`.

While `ReadMemStats` returns golang memory allocator statistics, so it should be virtual memory consumption of this process(see also https://github.com/golang/go/blob/ae65615fd8784919f11e744b3a26d9dfa844c222/src/runtime/mstats.go#L573), so the check would be too strict indeed.

I still think it is pretty tricky to do memory accounting, it is kind of difficult for the DBA to set a proper value for this parameter, especially in cases where multiple TiDB servers are deployed in a single machine.

Comment (dbjoa) [reply tidb-server/main.go]: @eurekaka 
Thank you for the detailed comments. 

The updated PR computes the total memory and the used one from the physical memory only. Thus, the PR should resolve the semantic mismatch in the previous PR.  

I agree that setting a proper value is not simple. However,  we should have provided a way to automatically calculate the value or allow the DBA to define the value in order to reduce or prevent the chance of OOM.

File: util/memory/meminfo.go [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+func MemTotal() (uint64, error) {
+	v, err := mem.VirtualMemory()
+	return v.Total, err
+}
+
+// MemUsed returns the total used amount of RAM on this system
+func MemUsed() (uint64, error) {
+	v, err := mem.VirtualMemory()
+	return v.Total - (v.Free + v.Buffers + v.Cached), err
+}
```
Comment (eurekaka) [inline util/memory/meminfo.go]: Could you please write a bench test for these 2 functions to see how expensive they are? thanks.

**Comment by eurekaka** [comment]
@zz-jason @lysu PTAL

File: util/memory/meminfo.go [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+// MemTotal returns the total amount of RAM on this system
+func MemTotal() (uint64, error) {
+	v, err := mem.VirtualMemory()
+	return v.Total, err
+}
+
+// MemUsed returns the total used amount of RAM on this system
+func MemUsed() (uint64, error) {
+	v, err := mem.VirtualMemory()
+	return v.Total - (v.Free + v.Buffers + v.Cached), err
```
Comment (zz-jason) [inline util/memory/meminfo.go]: Why not directly return `v.Used`?

File: config/config.go [hunk 5]
```diff
@@ -287,6 +289,7 @@ var defaultConf = Config{
 		MetricsInterval: 15,
 	},
 	Performance: Performance{
+		MaxMemory:           0,
```
Comment (zz-jason) [inline config/config.go]: If the configed `MaxMemory` is larger than the total memory of the machine, should we adjust this value to the total memory of that machine?

Comment (zz-jason) [inline config/config.go]: If the configed `MaxMemory` is larger than the total memory of the machine, should we adjust this value to the total memory of that machine?

File: util/memory/meminfo.go (hunk 4 above)
Comment (dbjoa) [reply util/memory/meminfo.go]: ``v.Used`` is ``v.Total - v.Free``. That is, ``v.Free`` does not count ``v.Buffers`` and ``v.Cached``, which can be a free memory.

Comment (zz-jason) [reply util/memory/meminfo.go]: got it.

File: config/config.go (hunk 5 above)
Comment (dbjoa) [reply config/config.go]: The updated PR should address the issue.

File: util/kvcache/simple_lru.go [hunk 6]
```diff
@@ -82,11 +89,25 @@ func (l *SimpleLRUCache) Put(key Key, value Value) {
...
+		if lru == nil {
+			break
+		}
 		l.cache.Remove(lru)
 		delete(l.elements, string(lru.Value.(*cacheEntry).key.Hash()))
 		l.size--
+		if memUsed > uint64(float64(l.quota)*(1.0-l.guard)) {
+			memUsed, err = memory.MemUsed()
+			if err != nil {
+				memUsed = math.MaxUint64
```
[the remark this answers is not in the document]
Comment (dbjoa) [reply util/kvcache/simple_lru.go]: The updated PR should address the issue.
