### PR TITLE
expression: fix functions format_bytes and format_nano_time incorrectly use varbinary

### LINKED ISSUE #15346: functions format_bytes and format_nano_time incorrectly use varbinary (no collation)
## Bug Report

The helper functions introduced in https://github.com/pingcap/tidb/pull/14975 have a bug, where I can't easily use them in the MySQL CLI because they print as hex.

1. What did you do?

```
mysql -P4000 -uroot --column-type-info=1 -e 'SELECT FORMAT_BYTES(1024), CAST(FORMAT_BYTES(1024) as CHAR)'
Field   1:  `FORMAT_BYTES(1024)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  binary (63)
Length:     0
Max_length: 8
Decimals:   31
Flags:      UNSIGNED 

Field   2:  `CAST(FORMAT_BYTES(1024) as CHAR)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_bin (46)
Length:     0
Max_length: 8
Decimals:   31
Flags:      


+----------------------------------------+----------------------------------+
| FORMAT_BYTES(1024)                     | CAST(FORMAT_BYTES(1024) as CHAR) |
+----------------------------------------+----------------------------------+
| 0x312E3030204B6942                     | 1.00 KiB                         |
+----------------------------------------+----------------------------------+
```

2. What did you expect to see?

Here is the behavior of MySQL:

```
./use --column-type-info=1 -e 'SELECT FORMAT_BYTES(1024), CAST(FORMAT_BYTES(1024) as CHAR)'
Field   1:  `FORMAT_BYTES(1024)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     44
Max_length: 8
Decimals:   31
Flags:      

Field   2:  `CAST(FORMAT_BYTES(1024) as CHAR)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     44
Max_length: 8
Decimals:   31
Flags:      


+--------------------+----------------------------------+
| FORMAT_BYTES(1024) | CAST(FORMAT_BYTES(1024) as CHAR) |
+--------------------+----------------------------------+
| 1.00 KiB           | 1.00 KiB                         |
+--------------------+----------------------------------+
```

3. What did you see instead?

This applies to both format_bytes and format_nano_time. They need to be wrapped in a cast function to return printable characters for the mysql cli.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta-385-g107b071e0
Git Commit Hash: 107b071e0c1d8c5678911ccb2808e42db0abf63c
Git Branch: master
UTC Build Time: 2020-03-11 03:54:18
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by gauss1314**
### What problem does this PR solve?

Issue Number: close #15346 

### Check List

Tests

- Unit test

### Release note

- No release note

### CODE REVIEW

**Comment by gauss1314** [comment]
Hi  @qw4990 , in my opinion I can't add test for this. Because this bug is show when exec 
`mysql -P4000 -uroot --column-type-info=1 -e 'SELECT FORMAT_BYTES(1024), CAST(FORMAT_BYTES(1024) as CHAR)'
F`
Which is outside the session. Maybe there is another way to test it?

**Comment by wwar** [comment]
@gauss1314 You could assert that the collation is non binary like this:

```
mysql> select collation(format_bytes(1024)) != 'binary';
+-------------------------------------------+
| collation(format_bytes(1024)) != 'binary' |
+-------------------------------------------+
|                                         0 |
+-------------------------------------------+
1 row in set (0.00 sec)

```

**Comment by gauss1314** [comment]
@wwar Thanks! PTAL @qw4990 .

File: expression/builtin_info.go [hunk 1]
```diff
@@ -976,7 +976,7 @@ func (c *formatNanoTimeFunctionClass) getFunction(ctx sessionctx.Context, args [
 		return nil, err
 	}
 	bf := newBaseBuiltinFuncWithTp(ctx, args, types.ETString, types.ETReal)
-	bf.tp.Flag |= mysql.UnsignedFlag
+	bf.tp.Charset = mysql.DefaultCharset
```
Comment (XuHuaiyu) [inline expression/builtin_info.go:979]: Why do we modify this instead of adding a new line?

Comment (wjhuang2016) [reply expression/builtin_info.go:979]: We should use the connection charset and collation here.

Comment (gauss1314) [reply expression/builtin_info.go]: @XuHuaiyu 
```
$ mysql -h127.0.0.1 -P4000 -uroot --column-type-info=1 -e 'SELECT FORMAT_BYTES(1024), CAST(FORMAT_BYTES(1024) as CHAR)'
Field   1:  `FORMAT_BYTES(1024)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8_bin (83)
Length:     0
Max_length: 8
Decimals:   31
Flags:      
```

`Flags: ` should be empty, so unset `bf.tp.Flag`

Comment (gauss1314) [reply expression/builtin_info.go]: @wjhuang2016 
I use `bf.tp.Charset, bf.tp.Collate = ctx.GetSessionVars().GetCharsetInfo()` but seems wrong, UT failed.
What is the meaning of `connection charset and collation`?

Comment (wjhuang2016) [reply expression/builtin_info.go]: Because the UT is wrong, the result should be 1.
FYI https://dev.mysql.com/doc/refman/8.0/en/charset-connection.html

**Comment by XuHuaiyu** [comment]
PTAL @wjhuang2016

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
