### PR TITLE
lightning: remove some `NOT NULL` constraints on lightning table

### LINKED ISSUE #57578: Should not use `INSERT IGNORE INTO` in lightning tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://github.com/pingcap/tidb/pull/55477 changes `INSERT INTO` to `INSERT IGNORE INTO, which may case data correctness.

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #57578

Problem Summary:

### What changed and how does it work?

https://github.com/pingcap/tidb/pull/55477 change the behavior of null value insert. To adapt to this change, some `NOT NULL` constraints have to be removed.

Previous PR just wrongly change `INSERT INTO` to `INSERT IGNORE INTO`, which may case data correctness.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/lightning/errormanager/errormanager.go [hunk 1]
```diff
@@ -89,10 +89,10 @@ const (
 		CREATE TABLE IF NOT EXISTS %s.` + ConflictErrorTableName + ` (
 			task_id     bigint NOT NULL,
 			create_time datetime(6) NOT NULL DEFAULT now(6),
-			table_name  varchar(261) NOT NULL,
```
Comment (lance6716) [inline pkg/lightning/errormanager/errormanager.go:92]: table name should be NOT NULL. For index-type conflict related columns, because lightning may insert record-type confict into this table, they can be NULL

File: pkg/lightning/errormanager/errormanager.go [hunk 2]
```diff
@@ -89,10 +89,10 @@ const (
...
-			index_name  varchar(128) NOT NULL,
```
Comment (lance6716) [inline pkg/lightning/errormanager/errormanager.go:93]: I also found when it's record-type conflict, `'PRIMARY'` will be used to insert. So this column can also be NOT NULL

**Review by lance6716 — APPROVED** [review]

**Review by fzzf678 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Review by fzzf678 — APPROVED** [review]
