### PR TITLE
ddl, parser: fix resume pd schedule and cancel for `flashback cluster`

### LINKED ISSUE #37584: after flashback, pd schedule didn't resumed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. execute 'flashback cluster as of timestamp xxxx'
2. after ddl return successfully, check pd schedule with "tiup ctl:v6.2.0 pd config -u http://10.2.xx.xx:2379 show"

### 2. What did you expect to see? (Required)
hot-region-schedule-limit 4
leader-schedule-limit 4
merge-schedule-limit 8
region-schedule-limit 2048
replica-schedule-limit 64

### 3. What did you see instead (Required)
hot-region-schedule-limit 0
leader-schedule-limit 0
merge-schedule-limit 0
region-schedule-limit 0
replica-schedule-limit 0

### 4. What is your TiDB version? (Required)

tidb patch

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #37584, #37580

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix resume pd schedule and cancel for `flashback cluster`
```

### CODE REVIEW

**Review by xhebox — APPROVED** [review]

File: ddl/cluster_test.go [hunk 1]
```diff
@@ -99,3 +107,72 @@ func TestGetFlashbackKeyRanges(t *testing.T) {
...
+	dom.DDL().SetHook(hook)
+	tk.MustGetErrCode(fmt.Sprintf("flashback cluster as of timestamp '%s'", oracle.GetTimeFromTS(ts)), errno.ErrCancelledDDLJob)
+	hook.MustCancelDone(t)
+
+	// Try canceled on StateWriteReorganization, cancel failed
+	hook = newCancelJobHook(t, store, dom, func(job *model.Job) bool {
+		return job.SchemaState == model.StateWriteReorganization
+	})
+	dom.DDL().SetHook(hook)
+	tk.MustExec(fmt.Sprintf("flashback cluster as of timestamp '%s'", oracle.GetTimeFromTS(ts)))
```
Comment (xhebox) [inline ddl/cluster_test.go:174]: Should be `tk.MustGetErrCode(`

**Review by xhebox — CHANGES_REQUESTED** [review]

File: ddl/cluster_test.go (hunk 1 above)
Comment (Defined2014) [reply ddl/cluster_test.go:174]: It will run success now, because we can't cancel flashback job in `writeReorg` state.
But if we support sendRPC, it will failed. I will modify it later.

Comment (xhebox) [reply ddl/cluster_test.go:174]: Then there is a prbolem, plz check the unit test failure.

Comment (Defined2014) [reply ddl/cluster_test.go:174]: Seems not related with flashback

```
fastbuild/bin/table/tables/tables_test_/tables_test.runfiles/__main__/table/tables/cache_test.go:234
[2022-09-05T02:16:49.774Z]         	Error:      	Not equal: 
[2022-09-05T02:16:49.774Z]         	            	expected: "[1 101 1001]\n[2 222 222]\n[3 113 1003]\n"
[2022-09-05T02:16:49.774Z]         	            	actual  : "[1 101 1001]\n[2 222 3333]\n[3 113 1003]\n"
[2022-09-05T02:16:49.774Z]         	            	
[2022-09-05T02:16:49.774Z]         	            	Diff:
[2022-09-05T02:16:49.774Z]         	            	--- Expected
[2022-09-05T02:16:49.774Z]         	            	+++ Actual
[2022-09-05T02:16:49.774Z]         	            	@@ -1,3 +1,3 @@
[2022-09-05T02:16:49.774Z]         	            	 [1 101 1001]
[2022-09-05T02:16:49.774Z]         	            	-[2 222 222]
[2022-09-05T02:16:49.774Z]         	            	+[2 222 3333]
[2022-09-05T02:16:49.774Z]         	            	 [3 113 1003]
[2022-09-05T02:16:49.774Z]         	Test:       	TestCacheTableBasicReadAndWrite
[2022-09-05T02:16:49.774Z]         	Messages:   	sql:select * from write_tmp1, args:[]
```

Comment (Defined2014) [reply ddl/cluster_test.go:174]: Done, PTAL

File: ddl/cluster.go [hunk 2]
```diff
@@ -256,34 +249,38 @@ func (w *worker) onFlashbackCluster(d *ddlCtx, t *meta.Meta, job *model.Job) (ve
...
+
 	// Stage 2, check flashbackTS, close GC and PD schedule.
-	if job.SnapshotVer == 0 {
-		if err = checkAndSetFlashbackClusterInfo(w, d, t, job, flashbackTS); err != nil {
-			job.State = model.JobStateCancelled
-			return ver, errors.Trace(err)
-		}
-		snapVer, err := getValidCurrentVersion(d.store)
-		if err != nil {
+	if job.SchemaState == model.StateNone {
```
Comment (xhebox) [inline ddl/cluster.go:267]: If we are using `job.SchemaState` to distinguish the job stage, why not

```
switch job.SchemaState  {
case stage1:
...
default:
}
```

Comment (Defined2014) [reply ddl/cluster.go]: Done, PTAL

**Review by xhebox — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
