### PR TITLE
executor: fix error msg of granting non-table level privilege

### LINKED ISSUE #29302: Granting a db level privilege to a non-existent table should not report `ErrTableNotExists`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

This is introduced by https://github.com/pingcap/tidb/pull/29273

### 1. Minimal reproduce step (Required)

```sql
mysql> drop table tmpdb.t;
Query OK, 0 rows affected (0.01 sec)

mysql> grant create temporary tables on tmpdb.tmpdb to test_user;
ERROR 1146 (42S02): Table 'tmpdb.tmpdb' doesn't exist
```

### 2. What did you expect to see? (Required)

```sql
mysql> grant create temporary tables on tmpdb.t to test_user;
ERROR 1144 (42000): Illegal GRANT/REVOKE command; please consult the manual to see which privileges can be used
```

### 3. What did you see instead (Required)

```sql
mysql> grant create temporary tables on tmpdb.tmpdb to test_user;
ERROR 1146 (42S02): Table 'tmpdb.tmpdb' doesn't exist
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #29302

Problem Summary:

### What is changed and how it works?
- Move privilege check before table existent check
- Bring privilege test case back
- Add test case

### Check List

Tests

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: executor/grant.go [hunk 1]
```diff
@@ -72,8 +72,17 @@ func (e *GrantExec) Next(ctx context.Context, req *chunk.Chunk) error {
 		dbName = e.ctx.GetSessionVars().CurrentDB
 	}
 
-	// Make sure the table exist.
+	// For table , check whether table exists and privilege is valid
 	if e.Level.Level == ast.GrantLevelTable {
+		// Return if privilege is invalid, to fail before not existing table, see issue #29302
+		for _, p := range e.Privs {
+			// TODO: https://github.com/pingcap/parser/pull/581 removed privs from all priv lists
```
Comment (mjonss) [inline executor/grant.go:79]: Since this is done, please update the code accordingly and remove the TODO.

File: executor/grant_test.go [hunk 2]
```diff
@@ -615,3 +615,17 @@ func TestGrantDynamicPrivs(t *testing.T) {
...
 }
+
+func TestNonExistTableIllegalGrant(t *testing.T) {
+	t.Parallel()
+
+	store, clean := testkit.CreateMockStore(t)
+	defer clean()
+
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("create user i29302")
```
Comment (mjonss) [inline executor/grant_test.go:626]: How do you use this user?

File: executor/grant_test.go [hunk 3]
```diff
@@ -615,3 +615,17 @@ func TestGrantDynamicPrivs(t *testing.T) {
...
+	defer tk.MustExec("drop user i29302")
+
+	tk.MustGetErrCode("grant create temporary tables on tmpdb.tmp29302 to test_user", mysql.ErrIllegalGrantForTable)
```
Comment (mjonss) [inline executor/grant_test.go:629]: What is the purpose of this test? Do we know if tmpdb exists? Do we know if tmpdb.tmp29302 exists? (most likely the table does not exist at least)

I assume the purpose is to test Schema level grants (like create table) on table level? But the user and table name are a bit confusing, so it is hard to tell.

File: executor/grant_test.go [hunk 4]
```diff
@@ -615,3 +615,17 @@ func TestGrantDynamicPrivs(t *testing.T) {
...
+	tk.MustGetErrCode("grant lock tables on test.tmp29302 to test_user", mysql.ErrIllegalGrantForTable)
```
Comment (mjonss) [inline executor/grant_test.go:630]: Same here, I would expect test schema to exists but not tmp29302. A better table name would be 'NonExistingTable29302'.
But it is not clear for me what you are testing.

File: executor/grant_test.go (hunk 2 above)
Comment (unconsolable) [reply executor/grant_test.go:626]: Use for grant privilege, sorry for write wrong username.

File: executor/grant_test.go (hunk 4 above)
Comment (unconsolable) [reply executor/grant_test.go]: Same as above.

**Comment by unconsolable** [comment]
/cc @mjonss @djshow832 
PTAL

File: executor/grant.go [hunk 5]
```diff
@@ -72,8 +72,15 @@ func (e *GrantExec) Next(ctx context.Context, req *chunk.Chunk) error {
 		dbName = e.ctx.GetSessionVars().CurrentDB
 	}
 
-	// Make sure the table exist.
+	// For table , check whether table exists and privilege is valid
 	if e.Level.Level == ast.GrantLevelTable {
+		// Return if privilege is invalid, to fail before not existing table, see issue #29302
+		for _, p := range e.Privs {
+			// Exclude column level
+			if len(p.Cols) == 0 && !mysql.AllowedTablePrivs.Has(p.Priv) {
```
Comment (mjonss) [inline executor/grant.go:80]: Why excluding column level? If it is not allowed on table level, how could it be allowed on column level?
Please add some more tests for this as well, if you really want to differentiate between column level and table level.

MySQL returns:
```sql
mysql> grant create temporary tables (column_name) on NotExistsD29302.NotExistsT29302 to u29302;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(column_name) on NotExistsD29302.NotExistsT29302 to u29302' at line 1
```
and depending on the check for `len(p.Cols) == 0` it will return Non-existing table or ErrIllegalGrantForTable which is not correct either. I suggest you create a separate bug for the column grants instead.

File: parser/mysql/privs.go [hunk 6]
```diff
@@ -314,6 +314,9 @@ var AllDBPrivs = Privileges{SelectPriv, InsertPriv, UpdatePriv, DeletePriv, Crea
 // AllTablePrivs is all the privileges in table scope.
 var AllTablePrivs = Privileges{SelectPriv, InsertPriv, UpdatePriv, DeletePriv, CreatePriv, DropPriv, IndexPriv, ReferencesPriv, AlterPriv, CreateViewPriv, ShowViewPriv}
 
+// AllowedTablePrivs is all the privileges allowed in table scope.
+var AllowedTablePrivs = Privileges{SelectPriv, InsertPriv, UpdatePriv, DeletePriv, CreatePriv, DropPriv, IndexPriv, ReferencesPriv, AlterPriv, CreateViewPriv, ShowViewPriv, GrantPriv, UsagePriv, AllPriv}
```
Comment (mjonss) [inline parser/mysql/privs.go:318]: I don't think this should be added.
By adding this, you are changing the behaviour of `GRANT GRANT OPTION ON NonExistingDB.NonExistingTable TO testuser` and `GRANT USAGE ON NonExistingDb.NonExistingTabler TO testuser`. In MySQL the behaviour of these two grants are not documented to my knowledge, but they do return Error 1146, table doesn't exist.

I think it is better to keep the special handling of privileges not included in AllTablePrivs in this case, since it is only done in a single place.

File: executor/grant.go (hunk 5 above)
Comment (unconsolable) [reply executor/grant.go:80]: It will return `Incorrect usage of %s and %s`. Actually I would like to exclude column level to execute column check here https://github.com/pingcap/tidb/blob/ec7a638e33fdde89d07f50b7ad587bc00d1d94f0/executor/grant.go#L671-L674

File: parser/mysql/privs.go (hunk 6 above)
Comment (unconsolable) [reply parser/mysql/privs.go:318]: No, the behavior doesn't change, it is just used to look up table level allowed privileges, to return `ErrIllegalGrantForTable` before table lookup. These two privileges are allowed to be granted to table, so I'd like to include these here.
```
mysql> GRANT GRANT OPTION ON NonExistingDB.NonExistingTable TO testuser;
ERROR 1146 (42S02): Table 'NonExistingDB.NonExistingTable' doesn't exist
mysql> GRANT USAGE ON NonExistingDb.NonExistingTabler TO testuser;
ERROR 1146 (42S02): Table 'NonExistingDb.NonExistingTabler' doesn't exist
```
If you would like I will write test case to ensure that.

File: executor/grant.go (hunk 5 above)
Comment (unconsolable) [reply executor/grant.go]: Update: I moved the column privilege validation to the same place, before finding table, so it will return `ErrWrongUsage` for this sql stmt. I think this comment can be resolved.

File: parser/mysql/privs.go (hunk 6 above)
Comment (unconsolable) [reply parser/mysql/privs.go]: Update: this has been removed, I think it can be marked as resolved.

**Comment by unconsolable** [comment]
Seems encountered an unstable test #29632

**Comment by morgo** [comment]
The mysql-test integration test errors are pre-existing. Both this branch and master report:
```sql
FATA[0000] run test [role] err: sql:DROP ROLE 'role';: run "DROP ROLE 'role';" at line 142 err Error 3530: `engineering`@`%` is not granted to root@127.0.0.1 
+ echo 'tidb-server(PID: 2790867) stopped'
tidb-server(PID: 2790867) stopped
+ kill -9 2790867
```

Which leaves tables around that break the remaining tests. It should be fixed in https://github.com/pingcap/tidb/pull/29667

**Comment by unconsolable** [comment]
> The mysql-test integration test errors are pre-existing. Both this branch and master report:
> 
> ```sql
> FATA[0000] run test [role] err: sql:DROP ROLE 'role';: run "DROP ROLE 'role';" at line 142 err Error 3530: `engineering`@`%` is not granted to root@127.0.0.1 
> + echo 'tidb-server(PID: 2790867) stopped'
> tidb-server(PID: 2790867) stopped
> + kill -9 2790867
> ```
> 
> Which leaves tables around that break the remaining tests. It should be fixed in #29667

After merging the PR, the error in integration test still exists.

**Review by mjonss — APPROVED** [review]
LGTM

**Comment by unconsolable** [comment]
> The mysql-test integration test errors are pre-existing. Both this branch and master report:
> 
> ```sql
> FATA[0000] run test [role] err: sql:DROP ROLE 'role';: run "DROP ROLE 'role';" at line 142 err Error 3530: `engineering`@`%` is not granted to root@127.0.0.1 
> + echo 'tidb-server(PID: 2790867) stopped'
> tidb-server(PID: 2790867) stopped
> + kill -9 2790867
> ```
> 
> Which leaves tables around that break the remaining tests. It should be fixed in #29667

From test results shown on https://github.com/pingcap/tidb/pull/29814#issuecomment-968912096, it seems the error on `[role]` may be fixed, however the `[update]` error still exists.

**Comment by unconsolable** [comment]
@morgo There are no failure in `role` in integration test after #29814 is merged. Now it fails on `case`, `charset`, `update`. Could you please take a look?

**Comment by djshow832** [comment]
> @morgo There are no failure in `role` in integration test after #29814 is merged. Now it fails on `case`, `charset`, `update`. Could you please take a look?

The integration tests are not maintained for a while because they run after PR is merged. I think it's OK if there is no failure about `role`.

**Comment by unconsolable** [comment]
> The integration tests are not maintained for a while because they run after PR is merged. I think it's OK if there is no failure about `role`.

At present it fails on `[type_decimal]`, `[type_enum]`, `[auto_increment]`, `[case]`, `[charset]`, `[update]`. `check_dev_2` fails on `Out Of Memory Quota`, which seems like a common failure in CI now.

**Review by djshow832 — APPROVED** [review]
