### PR TITLE
test: fix wrong failpoint.Disable path

### LINKED ISSUE #62251: make dumpling_unit_test failed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

make dumpling_unit_test 

### 2. What did you expect to see? (Required)

succeed or some failed test

### 3. What did you see instead (Required)

rror"] [errorVerbose="show index error\ngithub.com/pingcap/tidb/dumpling/export.TestPickupPossibleField\n\t/Users/hyi/prs/tidb/dumpling/export/sql_test.go:1688\ntesting.tRunner\n\t/opt/homebrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1792\nruntime.goexit\n\t/opt/homebrew/Cellar/go/1.24.3/libexec/src/runtime/asm_arm64.s:1223"]
[2025/07/07 18:10:38.782 +08:00] [INFO] [conn.go:70] ["cannot execute query"] [retryTime=2] [sql="SHOW INDEX FROM `foo`.`bar`"] [args=null] [error="all expectations were already fulfilled, call to Query 'SHOW INDEX FROM `foo`.`bar`' with args [] was not expected"]
[2025/07/07 18:10:38.983 +08:00] [INFO] [conn.go:70] ["cannot execute query"] [retryTime=3] [sql="SHOW INDEX FROM `foo`.`bar`"] [args=null] [error="all expectations were already fulfilled, call to Query 'SHOW INDEX FROM `foo`.`bar`' with args [] was not expected"]
--- FAIL: TestWriteViewMeta (0.00s)
    writer_test.go:94: 
        	Error Trace:	/Users/hyi/prs/tidb/dumpling/export/writer_test.go:94
        	Error:      	Received unexpected error:
        	           	injected error: fail to close meta file
        	           	github.com/pingcap/tidb/dumpling/export.buildFileWriter.func1
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_util.go:461
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).writeMetaToFile
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:290
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).WriteViewMeta
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:170
        	           	github.com/pingcap/tidb/dumpling/export.TestWriteViewMeta
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_test.go:93
        	           	testing.tRunner
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1792
        	           	runtime.goexit
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/runtime/asm_arm64.s:1223
        	Test:       	TestWriteViewMeta
--- FAIL: TestWriteTableDataWithFileSize (0.00s)
    writer_test.go:180: 
        	Error Trace:	/Users/hyi/prs/tidb/dumpling/export/writer_test.go:180
        	Error:      	Received unexpected error:
        	           	injected error: fail to close data file
        	           	github.com/pingcap/tidb/dumpling/export.buildInterceptFileWriter.func2
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_util.go:504
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).tryToWriteTableData
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:244
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).WriteTableData.func1
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:228
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetry.func1
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:37
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetryV2[...]
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:55
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetry
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:36
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).WriteTableData
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:192
        	           	github.com/pingcap/tidb/dumpling/export.TestWriteTableDataWithFileSize
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_test.go:179
        	           	testing.tRunner
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1792
        	           	runtime.goexit
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/runtime/asm_arm64.s:1223
        	Test:       	TestWriteTableDataWithFileSize
--- FAIL: TestWriteTableDataWithFileSizeAndRows (0.00s)
    writer_test.go:230: 
        	Error Trace:	/Users/hyi/prs/tidb/dumpling/export/writer_test.go:230
        	Error:      	Received unexpected error:
        	           	injected error: fail to close data file
        	           	github.com/pingcap/tidb/dumpling/export.buildInterceptFileWriter.func2
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_util.go:504
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).tryToWriteTableData
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:244
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).WriteTableData.func1
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:228
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetry.func1
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:37
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetryV2[...]
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:55
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetry
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:36
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).WriteTableData
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:192
        	           	github.com/pingcap/tidb/dumpling/export.TestWriteTableDataWithFileSizeAndRows
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_test.go:229
        	           	testing.tRunner
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1792
        	           	runtime.goexit
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/runtime/asm_arm64.s:1223
        	Test:       	TestWriteTableDataWithFileSizeAndRows
--- FAIL: TestWriteTableDataWithStatementSize (0.00s)
    writer_test.go:280: 
        	Error Trace:	/Users/hyi/prs/tidb/dumpling/export/writer_test.go:280
        	Error:      	Received unexpected error:
        	           	injected error: fail to close data file
        	           	github.com/pingcap/tidb/dumpling/export.buildInterceptFileWriter.func2
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_util.go:504
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).tryToWriteTableData
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:244
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).WriteTableData.func1
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:228
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetry.func1
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:37
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetryV2[...]
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:55
        	           	github.com/pingcap/tidb/br/pkg/utils.WithRetry
        	           		/Users/hyi/prs/tidb/br/pkg/utils/retry.go:36
        	           	github.com/pingcap/tidb/dumpling/export.(*Writer).WriteTableData
        	           		/Users/hyi/prs/tidb/dumpling/export/writer.go:192
        	           	github.com/pingcap/tidb/dumpling/export.TestWriteTableDataWithStatementSize
        	           		/Users/hyi/prs/tidb/dumpling/export/writer_test.go:279
        	           	testing.tRunner
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1792
        	           	runtime.goexit
        	           		/opt/homebrew/Cellar/go/1.24.3/libexec/src/runtime/asm_arm64.s:1223
        	Test:       	TestWriteTableDataWithStatementSize
FAIL
coverage: 55.9% of statements
FAIL	github.com/pingcap/tidb/dumpling/export	10.750s
ok  	github.com/pingcap/tidb/dumpling/log	0.509s	coverage: 44.4% of statements
	github.com/pingcap/tidb/dumpling/tests/s3		coverage: 0.0% of statements
FAIL
GOBIN=/Users/hyi/prs/tidb/tools/bin GO111MODULE=on go install github.com/pingcap/failpoint/failpoint-ctl@9b3b6e3
make: *** [dumpling_unit_test] Error 1

### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/commit/b475e1213b4d6f55e535e4691999be3af40be605

### PR DESCRIPTION
**Pull request by yihong0618**
This patch make dumpling_unit_test happy again

because:
failpoint.Disable("github.com/pingcap/tidb/dumpling/export/FailToCloseDataFile=return(true)") 
is not right

Issue Number: close #62251

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: dumpling/export/dump_test.go [hunk 1]
```diff
@@ -312,7 +312,7 @@ func TestSetSessionParams(t *testing.T) {
 		WillReturnError(tikvErr)
 
 	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/dumpling/export/SkipResetDB", "return(true)"))
```
Comment (lance6716) [inline dumpling/export/dump_test.go]: You can try `testfailpoint.Enable`

Comment (yihong0618) [reply dumpling/export/dump_test.go]: seems not work, will raise the same error

Comment (lance6716) [reply dumpling/export/dump_test.go]: Can you provide your diff about `testfailpoint.Enable`? We use it elsewhere and I don't understand why it will not work

Comment (yihong0618) [reply dumpling/export/dump_test.go]: my fault 
the error is that I am running the server
will make another commit

File: dumpling/export/dump_test.go [hunk 2]
```diff
@@ -311,8 +312,8 @@ func TestSetSessionParams(t *testing.T) {
 	mock.ExpectExec("SET SESSION tidb_snapshot").
 		WillReturnError(tikvErr)
 
-	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/dumpling/export/SkipResetDB", "return(true)"))
-	defer failpoint.Disable("github.com/pingcap/tidb/dumpling/export/SkipResetDB=return(true)")
+	testfailpoint.Enable(t, "github.com/pingcap/tidb/dumpling/export/SkipResetDB", "return(true)")
+	defer failpoint.Disable("github.com/pingcap/tidb/dumpling/export/SkipResetDB")
```
Comment (lance6716) [inline dumpling/export/dump_test.go]: this defer can be removed now. `testfailpoint.Enable` will use `t.Cleanup` internally to do the same thing.

File: dumpling/export/writer_test.go [hunk 3]
```diff
@@ -73,8 +74,8 @@ func TestWriteTableMeta(t *testing.T) {
 	require.NoError(t, err)
 	require.Equal(t, "/*!40014 SET FOREIGN_KEY_CHECKS=0*/;\n/*!40101 SET NAMES binary*/;\nCREATE TABLE t (a INT);\n", string(bytes))
 
-	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/dumpling/export/FailToCloseMetaFile", "return(true)"))
-	defer failpoint.Disable("github.com/pingcap/tidb/dumpling/export/FailToCloseMetaFile=return(true)")
+	testfailpoint.Enable(t, "github.com/pingcap/tidb/dumpling/export/FailToCloseMetaFile", "return(true)")
+	defer testfailpoint.Disable(t, "github.com/pingcap/tidb/dumpling/export/FailToCloseMetaFile")
```
Comment (lance6716) [inline dumpling/export/writer_test.go]: ditto

File: dumpling/export/dump_test.go (hunk 2 above)
Comment (yihong0618) [reply dumpling/export/dump_test.go]: learned it thank you

**Comment by yihong0618** [comment]
running make bazel_prepare
bazel run //:gazelle
Starting local Bazel server and connecting to it...
INFO: Reading 'startup' options from /Users/hyi/prs/tidb/.bazelrc: --host_jvm_args=-Xmx4g, --unlimit_coredumps
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=308
INFO: Reading rc options for 'run' from /Users/hyi/prs/tidb/.bazelrc:
  Inherited 'build' options: --http_timeout_scaling=0.1 --announce_rc --experimental_guard_against_concurrent_changes --incompatible_strict_action_env --incompatible_enable_cc_toolchain_resolution
WARNING: Download from http://bazel-cache.pingcap.net:8080/gomod/golang.org/x/tools/org_golang_x_tools-v0.34.0.zip failed: class java.io.IOException Read timed out
WARNING: Download from http://bazel-cache.pingcap.net:8080/gomod/github.com/golangci/golangci-lint/v2/com_github_golangci_golangci_lint_v2-v2.2.1.zip failed: class java.io.IOException Read timed out
WARNING: Download from http://bazel-cache.pingcap.net:8080/gomod/github.com/golangci/misspell/com_github_golangci_misspell-v0.7.0.zip failed: class java.io.IOException Read timed out
Analyzing: target //:gazelle (426 packages loaded, 7112 targets configured)
    Fetching repository @@org_golang_x_tools; starting 18s
    Fetching repository @@com_github_golangci_golangci_lint_v2; starting 18s
    Fetching repository @@com_github_golangci_misspell; starting 18s

File: dumpling/export/writer_test.go [hunk 4]
```diff
@@ -146,7 +146,7 @@ func TestWriteTableData(t *testing.T) {
 	require.Equal(t, expected, string(bytes))
 
 	require.NoError(t, failpoint.Enable("github.com/pingcap/tidb/dumpling/export/FailToCloseDataFile", "return(true)"))
```
Comment (lance6716) [inline dumpling/export/writer_test.go]: here also `testfailpoint.Enable`. A better way to fix the defer bug.

Comment (yihong0618) [reply dumpling/export/writer_test.go]: will also change it

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

**Comment by yihong0618** [comment]
Done

**Comment by lance6716** [comment]
```
Please run `make bazel_prepare` to update `.bazel` files, or just apply the following git diff (run `git apply -` and paste following contents with ctrl-D as ending):
diff --git a/dumpling/export/BUILD.bazel b/dumpling/export/BUILD.bazel
index 72411da133..7b587cb430 100644
--- a/dumpling/export/BUILD.bazel
+++ b/dumpling/export/BUILD.bazel
@@ -111,7 +111,6 @@ go_test(
         "@com_github_data_dog_go_sqlmock//:go-sqlmock",
         "@com_github_go_sql_driver_mysql//:mysql",
         "@com_github_pingcap_errors//:errors",
-        "@com_github_pingcap_failpoint//:failpoint",
         "@com_github_prometheus_client_golang//prometheus/collectors",
         "@com_github_stretchr_testify//require",
         "@org_golang_x_sync//errgroup",

```

/lgtm

**Review by D3Hunter — APPROVED** [review]

**Comment by yihong0618** [comment]
fixed ci
