### PR TITLE
*: refactor `CompilePattern` and `DoMatch` used by `like`

### LINKED ISSUE #20608: The `like` function returns wrong result
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
select '䇇Հ' collate utf8mb4_bin like '___Հ';
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
in mysql
```sql
mysql> select '䇇Հ' collate utf8mb4_bin like '___Հ';
+------------------------------------------+
| '䇇Հ' collate utf8mb4_bin like '___Հ'    |
+------------------------------------------+
|                                        0 |
+------------------------------------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```sql
mysql> select '䇇Հ' collate utf8mb4_bin like '___Հ';
+------------------------------------------+
| '䇇Հ' collate utf8mb4_bin like '___Հ'    |
+------------------------------------------+
|                                        1 |
+------------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

<!-- Paste the output of SELECT tidb_version() -->
```sql
mysql> SELECT tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1415-g99d1163cb-dirty
Edition: Community
Git Commit Hash: 99d1163cbc8eaf49e3c1e21453443faa9c4ec8db
Git Branch: unify-re
UTC Build Time: 2020-10-23 09:03:48
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve?

- Issue Number: close #20608 
- refactor code

Problem Summary:

there are three `CompilePattern` and `DoMatch` function in different places, they are almost the same but in parameters. This PR aims to unify them as one and provide some adapters. And I believe these two functions should take account of "real string" but "bytes of string".

### Check List 

Tests 

- Unit test

### Release note 

- fix a bug that makes the `like` function get the wrong result if pattern string is a Unicode string

### CODE REVIEW

**Review by bb7133 — COMMENTED** [review]
LGTM

File: util/collate/general_ci.go [hunk 1]
```diff
@@ -172,21 +68,23 @@ func (gc *generalCICollator) Pattern() WildcardPattern {
...
 // Compile implements WildcardPattern interface.
 func (p *ciPattern) DoMatch(str string) bool {
-	return doMatchGeneralCI(str, p.patChars, p.patTypes)
+	return stringutil.DoMatchInner(str, p.patChars, p.patTypes, func(a, b rune) bool {
+		return generalCIConverter(a) == generalCIConverter(b)
+	})
 }
 
-func convertRune(r rune) uint16 {
+func generalCIConverter(r rune) uint16 {
```
Comment (wjhuang2016) [inline util/collate/general_ci.go:87]: The function name shouldn't be a noun.

File: expression/integration_test.go [hunk 2]
```diff
@@ -7518,6 +7518,13 @@ func (s *testIntegrationSuite) TestIssue17767(c *C) {
 	tk.MustExec("rollback")
 }
 
+func (s *testIntegrationSuite) TestIssue20608(c *C) {
```
Comment (wjhuang2016) [inline expression/integration_test.go:7521]: The test must be serial.

File: util/stringutil/string_util.go [hunk 3]
```diff
@@ -183,16 +199,16 @@ func CompilePattern(pattern string, escape byte) (patChars, patTypes []byte) {
...
 		patLen++
 	}
-	patChars = patChars[:patLen]
+	patWeights = patWeights[:patLen]
 	patTypes = patTypes[:patLen]
 	return
 }
 
-func matchByte(a, b byte) bool {
+func matchByte(a, b rune) bool {
```
Comment (wjhuang2016) [inline util/stringutil/string_util.go:211]: matchRune?

File: util/collate/general_ci.go (hunk 1 above)
Comment (xiongjiwei) [reply util/collate/general_ci.go]: updated

File: util/stringutil/string_util.go [hunk 4]
```diff
@@ -241,12 +241,12 @@ func CompileLike2Regexp(str string) string {
 
 // DoMatchByte is a adapter for `DoMatchInner`, `str` can only be an ascii string.
 func DoMatchByte(str string, patChars, patTypes []byte) bool {
```
Comment (wjhuang2016) [inline util/stringutil/string_util.go:243]: DoMatchRune? or DoMatchBytes?

Comment (xiongjiwei) [reply util/stringutil/string_util.go]: updated. it should be `DoMatchBytes`, as the comment says this function should only accept an ascii string which one byte represents one character.

File: util/collate/general_ci.go [hunk 5]
```diff
@@ -52,7 +52,9 @@ func (gc *generalCICollator) Key(str string) []byte {
 	str = truncateTailingSpace(str)
 	buf := make([]byte, 0, len(str))
 	i := 0
-	for _, r := range []rune(str) {
+	r := rune(0)
```
Comment (wjhuang2016) [inline util/collate/general_ci.go:55]: Why do u change this？

Comment (xiongjiwei) [reply util/collate/general_ci.go:55]: sorry, I did not see any change here.

File: expression/integration_test.go (hunk 2 above)
Comment (wjhuang2016) [reply expression/integration_test.go]: You don't resolve it yet.

Comment (xiongjiwei) [reply expression/integration_test.go]: updated

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by bb7133** [comment]
Hi @xiongjiwei Please resolve the conflict.

**Comment by xiongjiwei** [comment]
> Hi @xiongjiwei Please resolve the conflict.

@bb7133 updated

**Review by wjhuang2016 — APPROVED** [review]

**Comment by xiongjiwei** [comment]
@qw4990 hi, still need another LGTM,    PTAL

**Comment by xiongjiwei** [comment]
@SunRunAway friendly Ping, can you PTAL?   it blocks pinyin collation dev. Thank you!

**Comment by bb7133** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
