### PR TITLE
dumpling: fix dump failed when sequence exists

### LINKED ISSUE #30149: dumpling: dump failed when a sequence created
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tidb> use test;
tidb> create sequence seq;

./dumpling -h host -u test_user -p test_password -P 4000 --filetype sql --threads 32 -o .

```

return dump failed. Since many people do not know what seq is, and error info is `Error 1051: Unknown table ''`, it will make them confused and worried.

### 2. What did you expect to see? (Required)
dump successfully.

### 3. What did you see instead (Required)

```
dump failed: sql: SELECT * FROM `test`.`seq` LIMIT 1: Error 1051: Unknown table ''
```

### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by sylzd**
### What problem does this PR solve?

Issue Number: close #30149 
Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by sylzd** [comment]
I think `support sequence dump` is a new feature, but dump failed is still a bug that should fix first.  the feature pr can replace the unsupported error then.

File: executor/infoschema_reader.go [hunk 1]
```diff
@@ -578,6 +578,7 @@ func (e *memtableRetriever) setDataFromTables(ctx context.Context, sctx sessionc
 					if rowCount == 0 {
 						rowCount = 1
 					}
+					table.Comment = "SEQUENCE"
```
Comment (lichunzhu) [inline executor/infoschema_reader.go:581]: I don't suggest we change this directly. We need a further discussion.

File: dumpling/export/dump.go [hunk 2]
```diff
@@ -890,6 +896,10 @@ func prepareTableListToDump(tctx *tcontext.Context, conf *Config, db *sql.Conn)
 }
 
 func dumpTableMeta(conf *Config, conn *sql.Conn, db string, table *TableInfo) (TableMeta, error) {
+	if table.Type == TableTypeSequence {
```
Comment (lichunzhu) [inline dumpling/export/dump.go:899]: This will never happen because dumpling doesn't generate TableType through `ParseTableType`.
It's at https://github.com/pingcap/tidb/blob/651e910/dumpling/export/sql.go#L275

**Review by lichunzhu — COMMENTED** [review]
If you really want to fix this, I suggest:
1. check whether do this database has sequence at the very beginning through `select count(*) from INFORMATION_SCHEMA.TABLES where `TABLE_TYPE`='SEQUENCE';`
2. change list type to `listTableByShowFullTables` at https://github.com/pingcap/tidb/blob/651e910/dumpling/export/sql.go#L217
3. Parse `Table_type` to `SEQUENCE` and skip these tables at now.

**Comment by lichunzhu** [comment]
Some results:
```sql
mysql> select count(*) from INFORMATION_SCHEMA.TABLES where `TABLE_TYPE`='SEQUENCE';
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)

mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| s              |
| t              |
+----------------+
2 rows in set (0.00 sec)

mysql> show full tables;
+----------------+------------+
| Tables_in_test | Table_type |
+----------------+------------+
| s              | SEQUENCE   |
| t              | BASE TABLE |
+----------------+------------+
2 rows in set (0.00 sec)

mysql> show table status;
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------+----------+----------------+---------+
| Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation   | Checksum | Create_options | Comment |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------+----------+----------------+---------+
| t    | InnoDB |      10 | Compact    |    0 |              0 |           0 |               0 |            0 |         0 |           NULL | 2021-11-26 15:46:38 | NULL        | NULL       | utf8mb4_bin |          |                |         |
+------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------+----------+----------------+---------+
1 row in set (0.02 sec)
```

File: dumpling/tests/basic/run.sh [hunk 3]
```diff
@@ -88,6 +88,12 @@ actual=$(sed -n '2p' ${DUMPLING_OUTPUT_DIR}/result.000000000.csv)
 echo "expected 2, actual ${actual}"
 [ "$actual" = 2 ]
 
+# Test for dump with sequence
+run_dumpling | tee ${DUMPLING_OUTPUT_DIR}/dumpling.log
+actual=$(grep -w "dump data successfully" ${DUMPLING_OUTPUT_DIR}/dumpling.log|wc -l)
```
Comment (lichunzhu) [inline dumpling/tests/basic/run.sh:93]: This can't prove this dump task succeeds. You need to truncate log first or grep failure dumpling.log and make sure it's 0.

**Review by lichunzhu — APPROVED** [review]

**Comment by lichunzhu** [comment]
LGTM, great job!

File: dumpling/export/sql_test.go [hunk 4]
```diff
@@ -1747,6 +1747,29 @@ func TestPickupPossibleField(t *testing.T) {
 	}
 }
 
+func TestCheckIfSeqExists(t *testing.T) {
+	t.Parallel()
+
+	conn, err := db.Conn(context.Background())
```
Comment (lichunzhu) [inline dumpling/export/sql_test.go:1753]: `db`, `mock` are not initialized:
```suggestion
	db, mock, err := sqlmock.New()
	require.NoError(t, err)
	defer func() {
		require.NoError(t, db.Close())
	}()

	conn, err := db.Conn(context.Background())
```

Comment (sylzd) [reply dumpling/export/sql_test.go:1759]: sorry~ mistake while solving conflicts

**Review by AilinKid — APPROVED** [review]
LGTM
