### PR TITLE
expression: fix bug in sleep function.

### LINKED ISSUE #2737: wrong argument type for builtinSleep
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
select sleep(1.5);
```

or 

```
select sleep(1);
```

2. What did you expect to see?

sleep for a while before return to client.

3. What did you see instead?

server returned result immediately.

In function `builtinSleepSig.eval `, after `evalArgs`,
 the arguments type is int or decimal, not float, so `GetFloat` returns 0 and sleep duration is 0.

### PR DESCRIPTION
**Pull request by hanfei1991**
After fixing:
mysql> select sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.00 sec)

mysql> select sleep(1.5);
+------------+
| sleep(1.5) |
+------------+
|          0 |
+------------+
1 row in set (1.50 sec)

fix #2737

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

File: expression/builtin_other.go [hunk 1]
```diff
@@ -23,7 +23,6 @@ import (
 )
 
 var (
-	_ functionClass = &sleepFunctionClass{}
```
Comment (coocood) [inline expression/builtin_other.go]: Why remove this?

**Comment by coocood** [comment]
LGTM
