### PR TITLE
br: fix tiflash confilct

### LINKED ISSUE #52628: PITR: Run PITR for multiple times could lead to tiflash crash
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Backup snapshot and log using PITR
2. Restore the data within tso1 into a new cluster with tiflash instances by `br restore point`
3. Add tiflash replica(s) for the restored table(s) # or if the backup data contains tiflash replica, the tiflash replica will be added after step 2.
4. Restore the data within tso1...tso2 into the cluster by `br restore point`

### 2. What did you expect to see? (Required)

Restore success and all instances run normally

### 3. What did you see instead (Required)

When running step 4, TiFlash instances crash with backtrace like

```
[FATAL] [Exception.cpp:106] ["Code: 9008, e.displayText() = DB::Exception: Raw TiDB PK: C80000000CC265A2, Prewrite ts: 449057189415092426 can not found in default cf for key: 7480000000003580FFD75F72C80000000CFFC265A20000000000FAF9C4A0DD8D13FEE1, region_id: 43498, applied_index: 31: (applied_term: 7) ...
```

### 4. What is your TiDB version? (Required)

v7.5.1

### PR DESCRIPTION
**Pull request by RidRisR**
### What problem does this PR solve?

Issue Number: close #52628

Problem Summary:
Run PITR for multiple times could lead to tiflash crash

### What changed and how does it work?

Added a new check to prevent pitr if there is tiflash replica on table in pitr range

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Prevent pitr when the target tables have tiflash replica
```

### CODE REVIEW

File: br/pkg/task/stream.go [hunk 1]
```diff
@@ -1412,6 +1412,10 @@ func restoreStream(
 	downstreamIdset := make(map[int64]struct{})
 	for upstreamId, rule := range rewriteRules {
 		downstreamId := restoreutils.GetRewriteTableID(upstreamId, rule)
+		info, ok := mgr.GetDomain().InfoSchema().TableInfoByID(downstreamId)
```
Comment (Leavrth) [inline br/pkg/task/stream.go:1415]: After a few versions, domain will use infoschemaV2 in default. So it may get some tables' info from TiKV instead of memory cache.
Therefore, it can check whether this restore is only has log restore data and if not it can skip check tiflash replica. In most cases, the restore will have a full backup data, and no need to check tiflash replica.

Comment (Leavrth) [reply br/pkg/task/stream.go:1415]: When we check tiflash replica here, we already restore the metakvs into the cluster. So if it returns the error to the user, the cluster has fall into chaotic situation.
Besides, we can ensure no metakvs table with tiflash replica is restored during log restore (see Line:1381 in br/pkg/task/stream.go). Maybe we can check it before restore metakvs?

Comment (RidRisR) [reply br/pkg/task/stream.go]: ok

File: br/tests/br_tiflash_conflict/prepare_data/insert_data.sql [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+-- Insert data into table3
+INSERT INTO table3 (id, score, grade, remarks, is_pass) VALUES
+(3, 88.0, 'B', 'Very good performance', TRUE),
+(4, 78.5, 'C', 'Good performance', TRUE),
+(5, 95.2, 'A', 'Outstanding performance', TRUE),
+(6, 69.4, 'D', 'Satisfactory performance', TRUE),
+(7, 82.3, 'B', 'Very good performance', TRUE),
+(8, 91.0, 'A', 'Excellent performance', TRUE),
+(9, 75.6, 'C', 'Good performance', TRUE),
+(10, 68.9, 'D', 'Satisfactory performance', TRUE);
```
Comment (YuJuncen) [inline br/tests/br_tiflash_conflict/prepare_data/insert_data.sql:35]: Would you add a new line after each text file? Which is a tradition of unix. See https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

File: br/tests/br_tiflash_conflict/prepare_data/insert_data.sql [hunk 3]
```diff
@@ -0,0 +1,35 @@
+-- Switch to the test database
```
Comment (YuJuncen) [inline br/tests/br_tiflash_conflict/prepare_data/insert_data.sql:1]: Also you may add license header in each file.

**Review by YuJuncen — APPROVED** [review]
rest lgtm

File: br/tests/br_tiflash_conflict/prepare_data/insert_data.sql (hunk 3 above)
Comment (RidRisR) [reply br/tests/br_tiflash_conflict/prepare_data/insert_data.sql:1]: Seems that most .sql don't have a license header?

**Review by Leavrth — APPROVED** [review]

File: br/pkg/restore/log_client/client.go [hunk 4]
```diff
@@ -680,6 +680,16 @@ func (rc *LogClient) InitSchemasReplaceForDDL(
 		if err != nil {
 			return nil, errors.Trace(err)
 		}
+		info := rc.dom.InfoSchema()
+		shcemas := info.AllSchemaNames()
+		for _, schema := range shcemas {
+			for _, table := range info.SchemaTables(schema) {
+				tableInfo := table.Meta()
+				if tableInfo.TiFlashReplica != nil && tableInfo.TiFlashReplica.Count > 0 {
+					return nil, errors.Errorf("exist table(s) have tiflash replica, please remove it before restore")
```
Comment (JaySon-Huang) [inline br/pkg/restore/log_client/client.go:689]: Can we give a more explicit reason which table(s) has tiflash replica in the error message?

Comment (RidRisR) [reply br/pkg/restore/log_client/client.go:689]: We could, but it may make the error message too long to read
