### PR TITLE
expression, types: fix datetime and year comparison error

### LINKED ISSUE #20121: datetime and year comparison error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
create table t(a datetime, b year);
insert into t values("2000-05-03 16:44:44", 2018);
select * from t where t.a > t.b;
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t where t.a > t.b;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)
```
mysql> select * from t where t.a > t.b;
+---------------------+------+
| a                   | b    |
+---------------------+------+
| 2000-05-03 16:44:44 | 2018 |
+---------------------+------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

master f6d445c7af707edd34f4f74d657d278c5aeab4d7
release-4.0 0fbe796e98399fc988911170b6711bfebf44bd46

### PR DESCRIPTION
**Pull request by JinLingChristopher**
### What problem does this PR solve?

Issue Number: close #20121 

Problem Summary:

### What is changed and how it works?

For Datetime vs Year, Date vs Year, Timestamp vs Year comparison, CompareTime should be used, and Year should be converted to `Time` before comparing.

What's Changed:

`expression/builtin_cast.go` 
`types/time.go`

How it Works:

For Datetime vs Year, Date vs Year, Timestamp vs Year comparison, CompareTime should be used, and Year should be converted to `Time` before comparing.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
 

- No release note

### CODE REVIEW

File: expression/builtin_cast.go [hunk 1]
```diff
@@ -573,6 +573,15 @@ func (b *builtinCastIntAsTimeSig) evalTime(row chunk.Row) (res types.Time, isNul
 	if isNull || err != nil {
 		return res, isNull, err
 	}
+
+	if b.args[0].GetType().Tp == mysql.TypeYear {
```
Comment (qw4990) [inline expression/builtin_cast.go:577]: Please also update `builtinCastIntAsTimeSig.vecEvalTime`.~

Comment (JinLingChristopher) [reply expression/builtin_cast.go:577]: ok, I will do this late today.

File: expression/builtin_compare.go [hunk 2]
```diff
@@ -1059,6 +1059,9 @@ func getBaseCmpType(lhs, rhs types.EvalType, lft, rft *types.FieldType) types.Ev
 	} else if ((lhs == types.ETInt || lft.Hybrid()) || lhs == types.ETDecimal) &&
 		((rhs == types.ETInt || rft.Hybrid()) || rhs == types.ETDecimal) {
 		return types.ETDecimal
+	} else if types.IsTemporalWithDate(lft.Tp) && rhs == types.ETInt && rft.Tp == mysql.TypeYear ||
```
Comment (XuHuaiyu) [inline expression/builtin_compare.go:1062]: Can `rhs == types.ETInt` and `lhs == types.ETInt` be removed?

**Review by XuHuaiyu — COMMENTED** [review]
rest LGTM

**Comment by XuHuaiyu** [comment]
PTAL @qw4990

File: expression/builtin_compare.go (hunk 2 above)
Comment (JinLingChristopher) [reply expression/builtin_compare.go:1062]: yes, it's redundant.

**Comment by JinLingChristopher** [comment]
there is still some problem that needs to be fixed in `ParseTimeFromYear`, I will change it at later today.

**Comment by XuHuaiyu** [comment]
Is this PR ready to be reviewed now? @JinLingChristopher

**Comment by JinLingChristopher** [comment]
@XuHuaiyu PTAL

File: types/time.go [hunk 3]
```diff
@@ -1712,6 +1712,17 @@ func ParseDate(sc *stmtctx.StatementContext, str string) (Time, error) {
 	return ParseTime(sc, str, mysql.TypeDate, MinFsp)
 }
 
+// ParseTimeFromYear parse a `YYYY` formed year to corresponded Datetime type.
+// year must be in the range [MinYear, MaxYear].
```
Comment (XuHuaiyu) [inline types/time.go:1716]: I do not understand why removing the [MinYear, MaxYear] check?

Comment (JinLingChristopher) [reply types/time.go:1716]: `create table t (a datetime, b year);
insert into t values("2020-11-11 11:11:11", 2019);  success
insert into t values("2020-11-11 11:11:11", 2222); fail. 
`
 At least one of the column is type Year, the data is checked when inserting, it should be guaranteed that invalid year which out of range cannot be inserted successfully.

So we do not need to check it is out of range. IMO, it's impossible ...

Comment (JinLingChristopher) [reply types/time.go:1716]: I mean, the inserted year, must already in the range [MinYear, MaxYear].

**Comment by JinLingChristopher** [comment]
@XuHuaiyu PTAL

File: types/time.go (hunk 3 above)
Comment (XuHuaiyu) [inline types/time.go:1716]: change the comment to:
Note: the invoker must promise the \`year\` is in the range [MinYear, MaxYear]

**Comment by JinLingChristopher** [comment]
@XuHuaiyu PTAL

**Comment by XuHuaiyu** [comment]
LGTM

**Comment by XuHuaiyu** [comment]
PTAL @qw4990

**Review by qw4990 — DISMISSED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Comment by qw4990** [comment]
It seems we should fix this in TiKV also:
```
[2020-10-19T03:36:09.833Z] NoPushDown Output: 
[2020-10-19T03:36:09.833Z] field1
[2020-10-19T03:36:09.833Z] NULL
[2020-10-19T03:36:09.833Z] NULL
[2020-10-19T03:36:09.833Z] 0000-00-00
[2020-10-19T03:36:09.833Z] 0000-00-00
[2020-10-19T03:36:09.833Z] 0000-00-00
[2020-10-19T03:36:09.833Z] 2004-00-00 00:00:00
[2020-10-19T03:36:09.833Z] 2007-00-00 00:00:00

[2020-10-19T03:36:09.833Z] WithPushDown Output: 
[2020-10-19T03:36:09.833Z] field1
[2020-10-19T03:36:09.833Z] NULL
[2020-10-19T03:36:09.833Z] NULL
[2020-10-19T03:36:09.833Z] 0000-00-00
[2020-10-19T03:36:09.833Z] 2004-00-00 00:00:00
[2020-10-19T03:36:09.833Z] 2007-00-00 00:00:00
[2020-10-19T03:36:09.833Z] 2014-00-00 00:00:00
[2020-10-19T03:36:09.833Z] 2021-00-00 00:00:00
```
Could you please help to fix it? @iosmanthus

**Comment by iosmanthus** [comment]
> It seems we should fix this in TiKV also:
> 
> ```
> [2020-10-19T03:36:09.833Z] NoPushDown Output: 
> [2020-10-19T03:36:09.833Z] field1
> [2020-10-19T03:36:09.833Z] NULL
> [2020-10-19T03:36:09.833Z] NULL
> [2020-10-19T03:36:09.833Z] 0000-00-00
> [2020-10-19T03:36:09.833Z] 0000-00-00
> [2020-10-19T03:36:09.833Z] 0000-00-00
> [2020-10-19T03:36:09.833Z] 2004-00-00 00:00:00
> [2020-10-19T03:36:09.833Z] 2007-00-00 00:00:00
> 
> [2020-10-19T03:36:09.833Z] WithPushDown Output: 
> [2020-10-19T03:36:09.833Z] field1
> [2020-10-19T03:36:09.833Z] NULL
> [2020-10-19T03:36:09.833Z] NULL
> [2020-10-19T03:36:09.833Z] 0000-00-00
> [2020-10-19T03:36:09.833Z] 2004-00-00 00:00:00
> [2020-10-19T03:36:09.833Z] 2007-00-00 00:00:00
> [2020-10-19T03:36:09.833Z] 2014-00-00 00:00:00
> [2020-10-19T03:36:09.833Z] 2021-00-00 00:00:00
> ```
> 
> Could you please help to fix it? @iosmanthus

OK! I will take a look at it!

**Comment by JinLingChristopher** [comment]
what I can do to make this to be merged?

**Comment by XuHuaiyu** [comment]
@JinLingChristopher https://github.com/pingcap/tidb/pull/20233#issuecomment-711567704

Or, it'll be nice if you can fix this bug on tikv, too

**Comment by JinLingChristopher** [comment]
> > It seems we should fix this in TiKV also:
> > ```
> > [2020-10-19T03:36:09.833Z] NoPushDown Output: 
> > [2020-10-19T03:36:09.833Z] field1
> > [2020-10-19T03:36:09.833Z] NULL
> > [2020-10-19T03:36:09.833Z] NULL
> > [2020-10-19T03:36:09.833Z] 0000-00-00
> > [2020-10-19T03:36:09.833Z] 0000-00-00
> > [2020-10-19T03:36:09.833Z] 0000-00-00
> > [2020-10-19T03:36:09.833Z] 2004-00-00 00:00:00
> > [2020-10-19T03:36:09.833Z] 2007-00-00 00:00:00
> > 
> > [2020-10-19T03:36:09.833Z] WithPushDown Output: 
> > [2020-10-19T03:36:09.833Z] field1
> > [2020-10-19T03:36:09.833Z] NULL
> > [2020-10-19T03:36:09.833Z] NULL
> > [2020-10-19T03:36:09.833Z] 0000-00-00
> > [2020-10-19T03:36:09.833Z] 2004-00-00 00:00:00
> > [2020-10-19T03:36:09.833Z] 2007-00-00 00:00:00
> > [2020-10-19T03:36:09.833Z] 2014-00-00 00:00:00
> > [2020-10-19T03:36:09.833Z] 2021-00-00 00:00:00
> > ```
> > 
> > 
> > Could you please help to fix it? @iosmanthus
> 
> OK! I will take a look at it!

hello, since I am not good at rust and not know about tikv's code, so can you take a look at this issue, to make it to be sovled?

**Comment by XuHuaiyu** [comment]
@JinLingChristopher 
ok, @iosmanthus will handle this.

**Comment by zhongzc** [comment]
Could you please resolve the conflict? @JinLingChristopher

**Comment by JinLingChristopher** [comment]
@zhongzc , it's fixed.

**Review by XuHuaiyu — APPROVED** [review]
