### PR TITLE
planner: fix getPartitionColumnPos panic

### LINKED ISSUE #25489: tidb panic while query partition table got error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `UK_RP16939` (
  `COL1` tinyint(16) DEFAULT '108' COMMENT 'NUMERIC UNIQUE INDEX',
  `COL2` varchar(20) DEFAULT NULL,
  `COL4` datetime DEFAULT NULL,
  `COL3` bigint(20) DEFAULT NULL,
  `COL5` float DEFAULT NULL,
  UNIQUE KEY `UK_COL1` (`COL1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE ( `COL1`+13 ) (
  PARTITION `P0` VALUES LESS THAN (-44),
  PARTITION `P1` VALUES LESS THAN (-23),
  PARTITION `P2` VALUES LESS THAN (-22),
  PARTITION `P3` VALUES LESS THAN (63),
  PARTITION `P4` VALUES LESS THAN (75),
  PARTITION `P5` VALUES LESS THAN (90),
  PARTITION `PMX` VALUES LESS THAN (MAXVALUE)
) ;

 select col1, col2 from UK_RP16939 where col1 in (116, 48, -30);
```

### 2. What did you expect to see? (Required)
query successfully 
### 3. What did you see instead (Required)
```sql
mysql> select col1, col2 from UK_RP16939 where col1 in (116, 48, -30);
ERROR 1105 (HY000): unique index must include all partition columns
```
### 4. What is your TiDB version? (Required)
release-5.1: 29bfbb28437609d0a524b7b84e6920
master: efc774aa5f9745359c5fe206aaafda768

### PR DESCRIPTION
**Pull request by zhuo-zhi**
### What problem does this PR solve?

Issue Number: close #25489 

Problem Summary:

- tidb panic while query partition table got error 

### What is changed and how it works?

What's Changed:

- change code path in `getPartitionColumnPos`

How it Works:

- new code path prevents potential panic

Tests 

- Unit test

Side effects

- N/A

### Release note 

- planner: fix getPartitionColumnPos panic

### CODE REVIEW

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -1582,22 +1582,17 @@ func getPartitionColumnPos(idx *model.IndexInfo, partitionExpr *tables.Partition
...
 		}
 	case model.PartitionTypeList:
 		// left list columns partition for future development
-		if partitionExpr.ForListPruning.ColPrunes == nil {
-			locateExpr := partitionExpr.ForListPruning.LocateExpr
-			if locateExpr, ok := locateExpr.(*expression.Column); ok {
-				colInfo := findColNameByColID(tbl.Columns, locateExpr)
-				partitionName = colInfo.Name
-			}
+		if locateExpr, ok := partitionExpr.ForListPruning.LocateExpr.(*expression.Column); ok && partitionExpr.ForListPruning.ColPrunes == nil {
```
Comment (rebelice) [inline planner/core/point_get_plan.go:1593]: Could you please add a test for `list partition`?

**Review by qw4990 — APPROVED** [review]

File: planner/core/point_get_plan.go (hunk 1 above)
Comment (zhuo-zhi) [reply planner/core/point_get_plan.go:1593]: Updated. PTAL

**Review by rebelice — APPROVED** [review]
