### PR TITLE
expression: show display name in error messages

### LINKED ISSUE #26397: A minor issue about error message for ERROR 1267 (HY000)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table a(b set('Alice')) collate utf8_unicode_ci;
create table c(d set('Alice')) collate utf8_general_ci;
SELECT d FROM c WHERE d IN(SELECT b FROM a);
```

### 2. What did you expect to see? (Required)
in MySQL:
```
ERROR 1267 (HY000) at line 3: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='
```
### 3. What did you see instead (Required)
```
ERROR 1267 (HY000) at line 3: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation 'eq'
```
Maybe `=` is more readable than `eq`.
### 4. What is your TiDB version? (Required)
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_Version()
                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.2.0-alpha-316-g014005ab6
Edition: Community
Git Commit Hash: 014005ab68b5c9a28795d13c1ca685cf46a3be7e
Git Branch: master
UTC Build Time: 2021-07-17 09:44:18
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by PragmaTwice**
### What problem does this PR solve?

Issue Number: close #26397 

Problem Summary: MySQL error message is more readable than TiDB via showing operators, not builtin names

### What is changed and how it works?

What's Changed: 
- Add an `operatorClass` for `functionClass` with an `opcode.Op`
- Add `GetDisplayName` to translate a function name to its display name
- Fix `illegalMixCollationErr` to show operator name

### Check List 

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
Test failed

**Comment by PragmaTwice** [comment]
@wjhuang2016 Fixed! PTAL.

**Comment by xhebox** [comment]
@PragmaTwice there is pingcap/sql-infra-reviewers, which you can ping and assign.

**Comment by PragmaTwice** [comment]
@xhebox  Got it. Thx!

File: expression/builtin.go [hunk 1]
```diff
@@ -582,6 +584,14 @@ type functionClass interface {
 	verifyArgsByCount(l int) error
 }
 
+// operatorClass is the interface for a operator extended from functionClass
+type operatorClass interface {
```
Comment (xhebox) [inline expression/builtin.go:588]: I think class should decide the display name on their own. Maybe

```
... interface {
  DisplayName() string
}
```

Or even simpler:

```
_, ok := funClass.(fmt.Stringer)
```

Just a suggestion, I am fine with the current solution.

Comment (PragmaTwice) [reply expression/builtin.go:588]: Currently only the operators need to be displayed more visually, but I've come up with a more customizable solution:
```go
type functionClassWithName interface {
    getDisplayName() string
}
```
then in `GetDisplayName`:
```go
switch c := funClass.(type) {
    case functionClassWithName:
        return c.getDisplayName()
    case operatorClass:
        return c.getOpcode().FormatToString()
    default:
        return name
}
```
So when some class want to decide the display name, they can define `getDisplayName`, and others just ignore it or define a `getOperator`.

Comment (PragmaTwice) [reply expression/builtin.go:588]: Currently only the operators need to be displayed more visually, but I've come up with a more customizable solution:
```go
type functionClassWithName interface {
    getDisplayName() string
}
```
then in GetDisplayName:
```go
switch c := funClass.(type) {
    case functionClassWithName:
        return c.getDisplayName()
    case operatorClass:
        return c.getOpcode().FormatToString()
    default:
        return name
}
```
So when some class want to decide the display name, they can define getDisplayName, and others just ignore it or define a getOperator.

Comment (xhebox) [reply expression/builtin.go:588]: That is what I mean, except operator is not special, IMO. There is a fallback, and operator function could define its own `getDisplayName()`, i.e. function returning `=` or `+` in this case.

Comment (PragmaTwice) [reply expression/builtin.go:588]: I think for operators, `getOperator` is more general and we could reuse the operator information (including display name) from the parser, otherwise we should introduce some duplicate strings.

Comment (xhebox) [reply expression/builtin.go:588]: Exposing is good, but I don't known where it can be used. I am not that familiar with expression.

Comment (PragmaTwice) [reply expression/builtin.go]: Sorry, I got your idea now. Done via 7905f1b0cb156f5c6074a79bc7287db88bfac3b2.

**Review by xhebox — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
