### PR TITLE
range:  fix overflow value access index

### LINKED ISSUE #17253: select statement returns constant overflow
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
tidb> create table t6 (a bigint);
Query OK, 0 rows affected (0.00 sec)
tidb> insert into t6 values(9223372036854775807);
Query OK, 1 row affected (0.00 sec)
tidb> alter table t6 add unique key idx(a);
Query OK, 0 rows affected (0.04 sec)
mysql> select * from t6 where a != 9223372036854775808;
ERROR 1690 (22003): constant 9223372036854775808 overflows bigint
```

### 2. What did you expect to see? (Required)
```
mysql> select * from t6 where a != 9223372036854775808;
+---------------------+
| a                   |
+---------------------+
| 9223372036854775807 |
+---------------------+
1 row in set (0.00 sec)
```

### 3. Affected version (Required)
master

### PR DESCRIPTION
**Pull request by luxinle**
### What problem does this PR solve?

Issue Number: close #17253 

Problem Summary:

### What is changed and how it works?

What's Changed:
When the value overflows access index. Replace with a fixed constant value.
How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
```
mysql> select * from t6 where a != 9223372036854775808;
+---------------------+
| a                   |
+---------------------+
| 9223372036854775807 |
+---------------------+
1 row in set (0.00 sec)

mysql>
mysql> create table f(id float,key(id));
Query OK, 0 rows affected (0.02 sec)

mysql> select * from f where id>1e39;
Empty set (0.01 sec)

mysql> select * from f where id>-1e39;
Empty set (0.02 sec)

mysql>
```

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by luxinle** [comment]
@ti-srebot /run-all-tests

**Comment by luxinle** [comment]
@XuHuaiyu  @wjhuang2016  PTAL

**Comment by luxinle** [comment]
@wshwsh12   PTAL

**Comment by luxinle** [comment]
Maybe we can ignore the overflow errors. And control the bound in datum.go when convert

**Comment by luxinle** [comment]
@Reminiscent  @qw4990    PTAL

File: util/ranger/points.go [hunk 1]
```diff
@@ -340,6 +345,48 @@ func handleUnsignedCol(ft *types.FieldType, val types.Datum, op string) (types.D
 	return val, op, false
 }
 
+// handleBoundCol handles the case when column meets overflow value.
+// The three returned values are: fixed constant value, fixed operator, and a boolean
+// which indicates whether the range is valid or not.
+func handleBoundCol(ft *types.FieldType, val types.Datum, op string) (types.Datum, string, bool) {
+	isUnsigned := mysql.HasUnsignedFlag(ft.Flag)
```
Comment (Reminiscent) [inline util/ranger/points.go:352]: When the `isUnsiged = true`, we can return directly.

File: util/ranger/points.go [hunk 2]
```diff
@@ -340,6 +345,48 @@ func handleUnsignedCol(ft *types.FieldType, val types.Datum, op string) (types.D
...
+		if !isUnsigned && !isNegative && val.GetUint64() > math.MaxInt64 {
+			switch op {
+			case ast.GT, ast.GE:
+				return val, op, false
+			case ast.NE, ast.LE, ast.LT:
+				op = ast.LE
+				val = types.NewIntDatum(math.MaxInt64)
+			}
+		}
+	case mysql.TypeFloat:
```
Comment (Reminiscent) [inline util/ranger/points.go:365]: It's possible to handle the `mysql.TypeDouble`?

**Review by Reminiscent — COMMENTED** [review]
Rest LGTM

File: util/ranger/points.go (hunk 2 above)
Comment (luxinle) [reply util/ranger/points.go:369]: Maybe we don't need to control the boundary about mysql.TypeDouble. When the value exceeds math.MaxFloat64, an error will be reported when sql parsing.

**Comment by luxinle** [comment]
@ti-srebot /run-all-tests

**Comment by luxinle** [comment]
@Reminiscent   PTAL   Thx~

File: util/ranger/points.go [hunk 3]
```diff
@@ -340,6 +345,51 @@ func handleUnsignedCol(ft *types.FieldType, val types.Datum, op string) (types.D
...
+		if val.GetFloat64() > math.MaxFloat32 {
+			switch op {
+			case ast.GT, ast.GE:
+				return val, op, false
+			case ast.NE, ast.LE, ast.LT:
+				op = ast.LE
+				val = types.NewFloat32Datum(math.MaxFloat32)
+			}
+		}
+		if val.GetFloat64() < -math.MaxFloat32 {
```
Comment (xuyifangreeneyes) [inline util/ranger/points.go:379]: Maybe `} else if val.GetFloat64() < -math.MaxFloat32 {` is better?

**Comment by xuyifangreeneyes** [comment]
Rest LGTM

File: util/ranger/points.go (hunk 3 above)
Comment (luxinle) [reply util/ranger/points.go]: handled

**Comment by xuyifangreeneyes** [comment]
LGTM

**Comment by xuyifangreeneyes** [comment]
@qw4990 PTAL

**Review by Reminiscent — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]

File: util/ranger/points.go [hunk 4]
```diff
@@ -340,6 +345,50 @@ func handleUnsignedCol(ft *types.FieldType, val types.Datum, op string) (types.D
...
+			switch op {
+			case ast.GT, ast.GE:
+				return val, op, false
+			case ast.NE, ast.LE, ast.LT:
+				op = ast.LE
+				val = types.NewIntDatum(math.MaxInt64)
+			}
+		}
+	case mysql.TypeFloat:
+		if val.GetFloat64() > math.MaxFloat32 {
```
Comment (xuyifangreeneyes) [inline util/ranger/points.go:370]: `if val.Kind() == types.KindFloat64() && val.GetFloat64() > math.MaxFloat32 {`

File: util/ranger/points.go [hunk 5]
```diff
@@ -340,6 +345,50 @@ func handleUnsignedCol(ft *types.FieldType, val types.Datum, op string) (types.D
...
+func handleBoundCol(ft *types.FieldType, val types.Datum, op string) (types.Datum, string, bool) {
+	isUnsigned := mysql.HasUnsignedFlag(ft.Flag)
+	isNegative := val.Kind() == types.KindInt64 && val.GetInt64() < 0
+	if isUnsigned {
+		return val, op, true
+	}
+
+	switch ft.Tp {
+	case mysql.TypeTiny, mysql.TypeShort, mysql.TypeInt24, mysql.TypeLong, mysql.TypeLonglong:
+		if !isNegative && val.GetUint64() > math.MaxInt64 {
```
Comment (xuyifangreeneyes) [inline util/ranger/points.go:360]: `if val.Kind() == types.KindUint64() && val.GetUint64() > math.MaxInt64 {`

File: util/ranger/points.go [hunk 6]
```diff
@@ -340,6 +345,50 @@ func handleUnsignedCol(ft *types.FieldType, val types.Datum, op string) (types.D
...
+			switch op {
+			case ast.GT, ast.GE:
+				return val, op, false
```
Comment (xuyifangreeneyes) [inline util/ranger/points.go:363]: Do we need to consider `ast.EQ` and `ast.NullEQ` here?

**Comment by xuyifangreeneyes** [comment]
@luxinle Can you look at the review and see whether there exists any minor problem, thanks!

**Comment by luxinle** [comment]
@xuyifangreeneyes  I'll  open another pr later

**Comment by luxinle** [comment]
@xuyifangreeneyes   PTAL  #21994
