### PR TITLE
statistics: avoid oom when to gc large stats_history

### LINKED ISSUE #48431: OOM in the ClearOutdatedHistoryStats
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

img_v3_0250_170a3ec3-60f0-4818-867d-95b5574e1c8g

```
goroutine 1464 [chan receive]:
[github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).getResultTask(0xc1b9227180)](http://github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).getResultTask(0xc1b9227180))
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/distsql.go:904](http://github.com/pingcap/tidb/pkg/executor/distsql.go:904) +0x105
[github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).Next](http://github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).Next)(0xc1b9227180, {0x62f3c50?, 0xc0d1bac840?}, 0xc159e0ccd0)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/distsql.go:867](http://github.com/pingcap/tidb/pkg/executor/distsql.go:867) +0xd5
[github.com/pingcap/tidb/pkg/executor/internal/exec.Next](http://github.com/pingcap/tidb/pkg/executor/internal/exec.Next)({0x62f3c50, 0xc0d1bac840}, {0x6309910, 0xc1b9227180}, 0xc159e0ccd0)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278](http://github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278) +0x2ba
[github.com/pingcap/tidb/pkg/executor.(*DeleteExec).deleteSingleTableByChunk](http://github.com/pingcap/tidb/pkg/executor.(*DeleteExec).deleteSingleTableByChunk)(0xc05a5cab40, {0x62f3c50, 0xc0d1bac840})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/delete.go:113](http://github.com/pingcap/tidb/pkg/executor/delete.go:113) +0x665
[github.com/pingcap/tidb/pkg/executor.(*DeleteExec).Next](http://github.com/pingcap/tidb/pkg/executor.(*DeleteExec).Next)(0x62f3c50?, {0x62f3c50?, 0xc0d1bac840?}, 0x1?)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/delete.go:61](http://github.com/pingcap/tidb/pkg/executor/delete.go:61) +0x65
[github.com/pingcap/tidb/pkg/executor/internal/exec.Next](http://github.com/pingcap/tidb/pkg/executor/internal/exec.Next)({0x62f3c50, 0xc0d1bac840}, {0x630a830, 0xc05a5cab40}, 0xc159e0cb90)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278](http://github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278) +0x2ba
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next)(0xc071e7ce10, {0x62f3c50, 0xc0d1bac840}, {0x630a830, 0xc05a5cab40}, 0x0?)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:1226](http://github.com/pingcap/tidb/pkg/executor/adapter.go:1226) +0x6e
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor)(0xc071e7ce10, {0x62f3c50?, 0xc0d1bac840?}, {0x630a830?, 0xc05a5cab40})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:971](http://github.com/pingcap/tidb/pkg/executor/adapter.go:971) +0x396
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay)(0xc071e7ce10, {0x62f3c50, 0xc0d1bac840}, {0x630a830?, 0xc05a5cab40?}, 0x0)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:797](http://github.com/pingcap/tidb/pkg/executor/adapter.go:797) +0x252
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec)(0xc071e7ce10, {0x62f3c50, 0xc0d1bac840})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:578](http://github.com/pingcap/tidb/pkg/executor/adapter.go:578) +0xda5
[github.com/pingcap/tidb/pkg/session.runStmt](http://github.com/pingcap/tidb/pkg/session.runStmt)({0x62f3c50?, 0xc000ea0270?}, 0xc0669d4780, {0x6303700, 0xc071e7ce10?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/session/session.go:2421](http://github.com/pingcap/tidb/pkg/session/session.go:2421) +0x422
[github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt](http://github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt)(0xc0669d4780, {0x62f3c50?, 0xc000ea0270?}, {0x6308298?, 0xc08967b040?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/session/session.go:2271](http://github.com/pingcap/tidb/pkg/session/session.go:2271) +0x109b
[github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal](http://github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal)(0xc0669d4780, {0x62f3c50, 0xc000ea0270}, {0x5a9c7be, 0x6b}, {0xc01eb7c7e0, 0x1, 0x1})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/session/session.go:1645](http://github.com/pingcap/tidb/pkg/session/session.go:1645) +0x23e
[github.com/pingcap/tidb/pkg/statistics/handle/util.Exec](http://github.com/pingcap/tidb/pkg/statistics/handle/util.Exec)({0x636c1d8?, 0xc0669d4780?}, {0x5a9c7be, 0x6b}, {0xc01eb7c7e0, 0x1, 0x1})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:203](http://github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:203) +0x8c
[github.com/pingcap/tidb/pkg/statistics/handle/storage.ClearOutdatedHistoryStats](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.ClearOutdatedHistoryStats)({0x636c1d8, 0xc0669d4780})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:191](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:191) +0x39e
[github.com/pingcap/tidb/pkg/statistics/handle/storage.GCStats](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.GCStats)({0x636c1d8, 0xc0669d4780}, {0x6375170?, 0xc067418a00}, {0x63304f0, 0xc0061b4200}, 0xa7a358200)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:119](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:119) +0x59f
[github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats.func1](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats.func1)({0x636c1d8?, 0xc0669d4780?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:57](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:57) +0x34
[github.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx](http://github.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx)({0x62cf7d0, 0xc0014060f0}, 0xc065cabb00, {0x0, 0x0, 0xc065cabb28?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:110](http://github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:110) +0x194
[github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats)(0xc047dc6ef0, {0x63304f0, 0xc0061b4200}, 0xa7a358200)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:56](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:56) +0x96
[github.com/pingcap/tidb/pkg/domain.(*Domain).updateStatsWorker](http://github.com/pingcap/tidb/pkg/domain.(*Domain).updateStatsWorker)(0xc001436000, {0x0?, 0x0?}, {0x63159c0?, 0xc0676cd900?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/domain/domain.go:2438](http://github.com/pingcap/tidb/pkg/domain/domain.go:2438) +0x7f9
[github.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func3()](http://github.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func3())
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/domain/domain.go:2257](http://github.com/pingcap/tidb/pkg/domain/domain.go:2257) +0x27
[github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1()](http://github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1())
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:96](http://github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:96) +0x6c
created by [github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run](http://github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run) in goroutine 1
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:91](http://github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:91) +0xbd
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #48431

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/statistics/handle/storage/gc.go [hunk 1]
```diff
@@ -182,12 +182,12 @@ func ClearOutdatedHistoryStats(sctx sessionctx.Context) error {
 	}
 	count := rows[0].GetInt64(0)
 	if count > 0 {
-		sql = "delete from mysql.stats_meta_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
+		sql = "delete from mysql.stats_meta_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND limit 5000"
```
Comment (ngaut) [inline pkg/statistics/handle/storage/gc.go:185]: previously, it will clear all the outdated records. the new code limits the count to 5000.
Is Batch statement a better choice?  https://docs.pingcap.com/tidb/stable/non-transactional-dml

File: pkg/statistics/handle/storage/gc.go [hunk 2]
```diff
@@ -182,12 +182,12 @@ func ClearOutdatedHistoryStats(sctx sessionctx.Context) error {
...
 		_, err = util.Exec(sctx, sql, variable.HistoricalStatsDuration.Load().Seconds())
 		if err != nil {
 			return err
 		}
-		sql = "delete from mysql.stats_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
+		sql = "delete from mysql.stats_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND limit 5000"
```
Comment (ngaut) [inline pkg/statistics/handle/storage/gc.go:190]: Ditto.

File: pkg/statistics/handle/storage/gc.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/statistics/handle/storage/gc.go]: Fixed

File: pkg/statistics/handle/storage/gc.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/statistics/handle/storage/gc.go]: Done

File: pkg/statistics/handle/storage/gc.go [hunk 3]
```diff
@@ -182,12 +182,12 @@ func ClearOutdatedHistoryStats(sctx sessionctx.Context) error {
...
 	count := rows[0].GetInt64(0)
 	if count > 0 {
-		sql = "delete from mysql.stats_meta_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
+		sql = "batch on create_time limit 10 delete from mysql.stats_meta_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
 		_, err = util.Exec(sctx, sql, variable.HistoricalStatsDuration.Load().Seconds())
 		if err != nil {
 			return err
 		}
-		sql = "delete from mysql.stats_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
+		sql = "batch on create_time limit 10 delete from mysql.stats_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
```
Comment (qw4990) [inline pkg/statistics/handle/storage/gc.go:190]: Is it too small to use 10 here? What's the default limit of this syntax?

**Review by qw4990 — APPROVED** [review]

File: pkg/statistics/handle/storage/gc.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/statistics/handle/storage/gc.go]: I have changed it as 50.

File: pkg/session/session.go [hunk 4]
```diff
@@ -1641,8 +1641,12 @@ func (s *session) ExecuteInternal(ctx context.Context, sql string, args ...inter
 	if err != nil {
 		return nil, err
 	}
+	if sq, ok := stmtNode.(*ast.NonTransactionalDMLStmt); ok {
+		rs, err = HandleNonTransactionalDML(ctx, sq, s)
```
Comment (ekexium) [inline pkg/session/session.go:1645]: Not sure if this is a good idea. You definitely need more tests and consideration.
Some of the questions that occurred to me:
Is `ExecuteInternal` the right place to put the entrance of `HandleNonTransactionalDML`? How about `ExecuteInternalStmt`, `Execute` and `ExecuteStmt`? 
Non-transactional DML calls `ExecuteStmt`. The entrance was put outside the `session` interface because `ExecuteStmt` is not supposed to be recursively called. Is it safe to put it in `ExecuteInternal`? Should we leave a comment to explain? Should we introduce any check to prevent possible recursion?

File: pkg/statistics/handle/storage/gc.go [hunk 5]
```diff
@@ -182,12 +182,12 @@ func ClearOutdatedHistoryStats(sctx sessionctx.Context) error {
 	}
 	count := rows[0].GetInt64(0)
 	if count > 0 {
-		sql = "delete from mysql.stats_meta_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
+		sql = "batch on create_time limit 10 delete from mysql.stats_meta_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND"
```
Comment (ekexium) [inline pkg/statistics/handle/storage/gc.go]: I guess a larger limit is better. We can decide it based on experiments. The NT-DML doc suggests 1,000-1,000,000.

Comment (hawkingrei) [reply pkg/statistics/handle/storage/gc.go]: It is possible for stats_meta_history to large the limit. but stats_history is too big to happen the OOM.

File: pkg/session/session.go (hunk 4 above)
Comment (hawkingrei) [reply pkg/session/session.go:1645]: I think it can be simplified into a for loop with a limit.

**Review by time-and-fate — APPROVED** [review]

File: pkg/statistics/handle/storage/gc.go [hunk 6]
```diff
@@ -182,15 +190,19 @@ func ClearOutdatedHistoryStats(sctx sessionctx.Context) error {
...
+			sql = "delete from mysql.stats_meta_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND limit 1000 "
+			_, err = util.Exec(sctx, sql, variable.HistoricalStatsDuration.Load().Seconds())
+			if err != nil {
+				return err
+			}
+		}
+		for n := int64(0); n < forCount(count, int64(50)); n++ {
+			sql = "delete from mysql.stats_history use index (idx_create_time) where create_time <= NOW() - INTERVAL %? SECOND limit 50 "
+			_, err = util.Exec(sctx, sql, variable.HistoricalStatsDuration.Load().Seconds())
+			logutil.BgLogger().Info("clear outdated historical stats")
```
Comment (ekexium) [inline pkg/statistics/handle/storage/gc.go:203]: The log could be too verbose.

**Review by ekexium — COMMENTED** [review]
Why to use different limits?

File: pkg/statistics/handle/storage/gc.go (hunk 6 above)
Comment (hawkingrei) [reply pkg/statistics/handle/storage/gc.go]: Fixed

Comment (hawkingrei) [reply pkg/statistics/handle/storage/gc.go]: Fix
