### PR TITLE
planner: refactor Join and Limit's ResolveIndices

### LINKED ISSUE #45758: update plan's inline projection may cause column resolution error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE tb1 (cid INT, code INT, class VARCHAR(10));
CREATE TABLE tb2 (cid INT, code INT, class VARCHAR(10));
INSERT INTO tb1 (cid, code, class) VALUES(1, 1, 'old');
INSERT INTO tb2 (cid, code, class) VALUES(1, 1, 'new');
UPDATE tb1, (SELECT code AS cid, code, MAX(class) AS class FROM tb2 GROUP BY code) tb3 SET tb1.cid = tb3.cid, tb1.code = tb3.code, tb1.class = tb3.class;
```

### 2. What did you expect to see? (Required)

Update executes successfully.

### 3. What did you see instead (Required)
```
[err="runtime error: index out of range [0] with length 0"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1075\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:463\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:113\ngithub.com/pingcap/tidb/util/chunk.(*Column).IsNull\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/chunk/column.go:169\ngithub.com/pingcap/tidb/util/chunk.Row.IsNull\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/chunk/row.go:218\ngithub.com/pingcap/tidb/util/chunk.Row.GetDatumWithBuffer\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/chunk/row.go:162\ngithub.com/pingcap/tidb/util/chunk.Row.GetDatumRowWithBuffer\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/chunk/row.go:125\ngithub.com/pingcap/tidb/util/chunk.Row.GetDatumRow\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/chunk/row.go:119\ngithub.com/pingcap/tidb/executor.(*UpdateExec).updateRows\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/update.go:292\ngithub.com/pingcap/tidb/executor.(*UpdateExec).Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/update.go:239\ngithub.com/pingcap/tidb/executor.Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:326\ngithub.com/pingcap/tidb/executor.(*ExecStmt).next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1202\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:947\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:773\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:568\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2394\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2251\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:294\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2094\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1885\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1372\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1153\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:677"]
```
### 4. What is your TiDB version? (Required)

v7.1.1, master

### LINKED ISSUE #45805: merge join report runtime error index out of range [0] with length
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `signed_estimate_volume` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '',
  `estimate_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `dealer_id` varchar(40) NOT NULL DEFAULT '' COMMENT '',
  `broker_id` varchar(40) NOT NULL DEFAULT '' COMMENT '',
  `real_t0_volume` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `real_t1_volume` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `manager_yid` varchar(32) NOT NULL DEFAULT '' COMMENT '',
   `estimate_volume` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `estimate_year_month` varchar(8) NOT NULL DEFAULT '' COMMENT '',
  `is_dropped` tinyint(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `UNIQ_ESTIMATE_ID` (`estimate_id`),
  UNIQUE KEY `UNIQ_MONTH_YID_BROKER_DEALER_DROPPED` (`estimate_year_month`,`manager_yid`,`broker_id`,`dealer_id`,`is_dropped`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=630002 COMMENT='';

 CREATE TABLE `unsigned_estimate_volume` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '',
  `estimate_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `estimate_year_month` varchar(8) NOT NULL DEFAULT '' COMMENT '',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `broker_id` varchar(40) NOT NULL DEFAULT '' COMMENT '',
  `estimate_volume` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `manager_yid` varchar(32) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `UNIQ_SIGNED_ESTIMATE_ID` (`estimate_id`),
  UNIQUE KEY `UNIQ_BUSINESS_DEALER_MONTH_YID` (`estimate_year_month`,`manager_yid`,`broker_id`,`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=390525 COMMENT='待签约关系预估体量表';


insert into signed_estimate_volume (id, estimate_volume, real_t1_volume) values (1, 100, 200);

SELECT
  `estimate_year_month`,
  `a_manager_yid` AS `manager_yid`,
  `real_t1_volume`,
  `real_t0_volume`,
  `a_estimate_volume` + IFNULL(`b_estimate_volume`, 0) AS `estimate_volume`,
  IFNULL(`a`.`increase_sum`, 0) + IFNULL(`b`.`increase_sum`, 0) AS `increase_sum`,
  IFNULL(`a`.`decrease_sum`, 0) + IFNULL(`b`.`decrease_sum`, 0) AS `decrease_sum`
FROM
  (
    SELECT
      `estimate_year_month`,
      `manager_yid` AS `a_manager_yid`,
      SUM(`real_t1_volume`) AS `real_t1_volume`,
      SUM(`real_t0_volume`) AS `real_t0_volume`,
      SUM(`estimate_volume`) AS `a_estimate_volume`,
      SUM(
        IF(
          `estimate_volume` > `real_t1_volume`,
          `estimate_volume` - `real_t1_volume`,
          0
        )
      ) AS `increase_sum`,
      SUM(
        IF(
          `estimate_volume` < `real_t1_volume`,
          `estimate_volume` - `real_t1_volume`,
          0
        )
      ) AS `decrease_sum`
    FROM
      `signed_estimate_volume`
    GROUP BY
      `manager_yid`
  ) AS `a`
  LEFT JOIN (
    SELECT
      `manager_yid` AS `b_manager_yid`,
      SUM(`estimate_volume`) AS `b_estimate_volume`,
      SUM(`estimate_volume`) AS `increase_sum`,
      0 AS `decrease_sum`
    FROM
      `unsigned_estimate_volume`
    GROUP BY
      `manager_yid`
  ) AS `b` ON a.`a_manager_yid` = b.`b_manager_yid`;
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
query success
### 3. What did you see instead (Required)
return error:
```sql
(1105, 'runtime error: index out of range [0] with length 0')
+------------------------------+----------+-----------+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                           | estRows  | task      | access object                  | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------------------+----------+-----------+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_10                | 1.00     | root      |                                | test.signed_estimate_volume.estimate_year_month, test.signed_estimate_volume.manager_yid, Column#11, Column#12, plus(Column#13, ifnull(Column#23, 0))->Column#25, plus(ifnull(Column#14, 0), ifnull(Column#23, 0))->Column#26, plus(ifnull(Column#15, 0), cast(ifnull(Column#24, 0), decimal(20,0) BINARY))->Column#27                                                                                                                                                                                               |
| └─HashJoin_12                | 1.00     | root      |                                | left outer join, equal:[eq(test.signed_estimate_volume.manager_yid, test.unsigned_estimate_volume.manager_yid)]                                                                                                                                                                                                                                                                                                                                                                                                      |
|   ├─HashAgg_15(Build)        | 1.00     | root      |                                | group by:Column#49, funcs:sum(Column#42)->Column#11, funcs:sum(Column#43)->Column#12, funcs:sum(Column#44)->Column#13, funcs:sum(Column#45)->Column#14, funcs:sum(Column#46)->Column#15, funcs:firstrow(Column#47)->test.signed_estimate_volume.manager_yid, funcs:firstrow(Column#48)->test.signed_estimate_volume.estimate_year_month                                                                                                                                                                              |
|   │ └─Projection_30          | 1.00     | root      |                                | cast(test.signed_estimate_volume.real_t1_volume, decimal(20,0) BINARY)->Column#42, cast(test.signed_estimate_volume.real_t0_volume, decimal(20,0) BINARY)->Column#43, cast(test.signed_estimate_volume.estimate_volume, decimal(20,0) BINARY)->Column#44, cast(if(gt(test.signed_estimate_volume.estimate_volume, test.signed_estimate_volume.real_t1_volume), minus(test.signed_estimate_volume.estimate_volume, test.signed_estimate_volume.real_t1_volume), 0), decimal(20,0) BINARY)->Column#45, cast(if(lt(t... |
|   │   └─TableReader_20       | 1.00     | root      |                                | data:TableFullScan_19                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|   │     └─TableFullScan_19   | 1.00     | cop[tikv] | table:signed_estimate_volume   | keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|   └─Projection_21(Probe)     | 8000.00  | root      |                                | test.unsigned_estimate_volume.manager_yid, Column#23, Column#23, 0->Column#24                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|     └─HashAgg_26             | 8000.00  | root      |                                | group by:test.unsigned_estimate_volume.manager_yid, funcs:sum(Column#40)->Column#23, funcs:firstrow(test.unsigned_estimate_volume.manager_yid)->test.unsigned_estimate_volume.manager_yid                                                                                                                                                                                                                                                                                                                            |
|       └─TableReader_27       | 8000.00  | root      |                                | data:HashAgg_22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|         └─HashAgg_22         | 8000.00  | cop[tikv] |                                | group by:test.unsigned_estimate_volume.manager_yid, funcs:sum(test.unsigned_estimate_volume.estimate_volume)->Column#40                                                                                                                                                                                                                                                                                                                                                                                              |
|           └─TableFullScan_25 | 10000.00 | cop[tikv] | table:unsigned_estimate_volume | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+------------------------------+----------+-----------+--------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

introduced by https://github.com/pingcap/tidb/pull/45158 
related issue: https://github.com/pingcap/tidb/issues/45804
### 4. What is your TiDB version? (Required)
master(522a00840385dfa43509a3af2bc79e6ff50252a8), v7.1.1
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #45758 , close #45805 

Problem Summary:

### What is changed and how it works?

In https://github.com/pingcap/tidb/pull/45158, we use `ResolveIndices` for the inline projection's column matching.

It's possible that the join/limit's child(ren)'s output columns are `[col0, col0, col1]`.
And if we call ResolveIndices, the two `col0` from join/limit will resolve their indexes to the first col0. But actually, the first col0 should resolve to the first col0 of its child(ren). The second should resolve to the second of its child(ren).

This pr aims to solve this issue.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by elsa0520 — APPROVED** [review]
LGTM

**Review by fixdb — APPROVED** [review]
+1

**Review by hawkingrei — APPROVED** [review]

File: planner/core/resolve_indices.go [hunk 1]
```diff
@@ -213,12 +226,25 @@ func (p *PhysicalMergeJoin) ResolveIndices() (err error) {
 	shallowColSlice := make([]*expression.Column, p.schema.Len())
 	copy(shallowColSlice, p.schema.Columns)
 	p.schema = expression.NewSchema(shallowColSlice...)
-	for i := 0; i < colsNeedResolving; i++ {
-		newCol, err := p.schema.Columns[i].ResolveIndices(mergedSchema)
-		if err != nil {
-			return err
+	foundCnt := 0
+	// The two column sets are all ordered. And the colsNeedResolving is the subset of the mergedSchema.
```
Comment (AilinKid) [inline planner/core/resolve_indices.go:230]: so this fix
join-schema(xx, col1, col1, col2)
+--child1
+--child2 (col1,col1,col2)

1: If join's col1 and col1 leverage normal resolve index to do the column index location, it will both redirect to child2's first col1.

2: And join's inline projection will reversely mark `lused` nad `rused` from join itself to its children, a kind of flag mark array, and fill these cols into join chunk result when onMatch or not.

3: So if both come on, the join output chunk result will miss one column size, since filling result could't see the second col2 from flag array `rused` here

4: that's why we redirect the second same col1 in the join schema to the second same col1 in the right child.

5: but we need to notice one case here, we assume that two column sets are all ordered. That means the join schema must occur ordered from the merged schema.
One bad case is about:
```
join schema 里面是 [xx, col2, col1] 下面 limit 承载了 schema [col2 ,col1], 孩子是 sort，其孩子是 proj[col2, col1], datasource是[col1, col2].   
1: proj 留下 replace map 后消除了，limit 承载了 join 的 schema 即使使用 replace 自己替换自己看起来暂时ok，

2: pushTopN down，将 limit 和 sort 整合成 topN，topN 没有 schema！也就是这里回丢失 limit 的 schema。然后 join 直接到孩子 datasource 的 schema[col1, col2].

3: 然后现在就是 join [xx, col2, col1]，右侧孩子 topN 无schema，datasouce[col1, col2]

总结：join schema 的出现，不再根据左右孩子出现的顺序具有一定的偏序关系。遍历的时候可能需要一定的向后寻找才能找到
```

conclusion: The appearance of join schema no longer has a certain partial order relationship based on the order in which the left and right children appear. When traversing, you may need to search backwards to find it.
