### PR TITLE
ingest: skip write when the region has no leader

### LINKED ISSUE #64422: [next-gen] import into failed when kill pd leader
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run workload
2、run import into
3、kill pd leader

[tc2-tidb-0.log](https://github.com/user-attachments/files/23471639/tc2-tidb-0.log)

[tc2-tidb-1.log](https://github.com/user-attachments/files/23471757/tc2-tidb-1.log)

### 2. What did you expect to see? (Required)
import into can succeed

### 3. What did you see instead (Required)
 import into failed
`[2025/11/11 11:52:47.028 +08:00] [ERROR] [task_executor.go:362] ["run subtask failed"] [keyspaceName=SYSTEM] [task-id=90001] [task-key=keyspace_a/ImportInto/90001] [error="type:UNKNOWN message:\"invalid store ID 0, not found\" "] [errorVerbose="type:UNKNOWN message:\"invalid store ID 0, not found\" \ngithub.com/tikv/pd/client.(*client).respForErr\n\t/root/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20250703091733-dfd345b89500/client.go:1411\ngithub.com/tikv/pd/client.(*client).GetStore\n\t/root/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20250703091733-dfd345b89500/client.go:985\ngithub.com/pingcap/tidb/br/pkg/restore/split.(*pdClient).GetStore\n\t/workspace/source/tidb/br/pkg/restore/split/client.go:255\ngithub.com/pingcap/tidb/pkg/ingestor/ingestcli.(*client).Ingest\n\t/workspace/source/tidb/pkg/ingestor/ingestcli/client.go:244\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*objStoreRegionJobWorker).ingest\n\t/workspace/source/tidb/pkg/lightning/backend/local/job_worker.go:386\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*regionJobBaseWorker).runJob\n\t/workspace/source/tidb/pkg/lightning/backend/local/job_worker.go:189\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*regionJobBaseWorker).run\n\t/workspace/source/tidb/pkg/lightning/backend/local/job_worker.go:89\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).doImport.func6\n\t/workspace/source/tidb/pkg/lightning/backend/local/local.go:1535\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).doImport.(*ErrorGroupWithRecover).Go.func11\n\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:263\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/root/go/pkg/mod/golang.org/x/sync@v0.16.0/errgroup/errgroup.go:93\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\ngithub.com/tikv/pd/client.(*client).respForErr\n\t/root/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20250703091733-dfd345b89500/client.go:1411\ngithub.com/tikv/pd/client.(*client).GetStore\n\t/root/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20250703091733-dfd345b89500/client.go:985\ngithub.com/pingcap/tidb/br/pkg/restore/split.(*pdClient).GetStore\n\t/workspace/source/tidb/br/pkg/restore/split/client.go:255\ngithub.com/pingcap/tidb/pkg/ingestor/ingestcli.(*client).Ingest\n\t/workspace/source/tidb/pkg/ingestor/ingestcli/client.go:244\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*objStoreRegionJobWorker).ingest\n\t/workspace/source/tidb/pkg/lightning/backend/local/job_worker.go:386\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*regionJobBaseWorker).runJob\n\t/workspace/source/tidb/pkg/lightning/backend/local/job_worker.go:189\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*regionJobBaseWorker).run\n\t/workspace/source/tidb/pkg/lightning/backend/local/job_worker.go:89\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).doImport.func6\n\t/workspace/source/tidb/pkg/lightning/backend/local/local.go:1535\ngithub.com/pingcap/tidb/pkg/lightning/backend/local.(*Backend).doImport.(*ErrorGroupWithRecover).Go.func11\n\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:263\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/root/go/pkg/mod/golang.org/x/sync@v0.16.0/errgroup/errgroup.go:93\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"]`

### 4. What is your TiDB version? (Required)
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v9.0.0-beta.2.pre-753-g63873b4
Edition: Enterprise
Git Commit Hash: 63873b4c50ee8318fb0013b8d6a847ee27418ee3
Git Branch: HEAD
UTC Build Time: 2025-11-10 13:51:25
GoVersion: go1.23.12
Race Enabled: false
Check Table Before Drop: false
Store: tikv
Enterprise Extension Commit Hash: dc633aae52eb11b4e3549e3a7ef5b0ed14e159b1
Kernel Type: Next Generation |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.04 sec)

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #64422, ref #61702

Problem Summary:

### What changed and how does it work?
this issue only happens in nextgen, as classic region job worker already have an additional leader check after write to tikv, we fix this by check region leader before write, so for classic kernel we can avoid the useless write
https://github.com/pingcap/tidb/blob/87152f7d957d12dd1530b45e5b064039641144cd/pkg/lightning/backend/local/region_job.go#L632

also log the unretryable error, to help debug and direct us to add more retryable error
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

we run the same scenario in the issue, no such error again, and we can see errors like below when there is no leader for some scanned region
```
[2025/11/13 15:46:11.734 +08:00] [INFO] [local.go:1497] ["put job back to jobCh to retry later"] [keyspaceName=SYSTEM] [task-id=120016] [task-key=keyspace_a/ImportInto/120016] [subtaskID=270022] [step=ingest] [startKey=780000017480000000000000C55F7280000000003C8F88] [endKey=780000017480000000000000C55F7280000000003C9901] [stage=regionScanned] [retryCount=1] [waitUntil=2025/11/13 15:46:13.734 +08:00] [error="[KV:ErrNoLeader]region has no leader, region '326782'"]
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by joechenrh — APPROVED** [review]

File: pkg/lightning/backend/local/job_worker.go [hunk 1]
```diff
@@ -160,7 +160,12 @@ func (w *regionJobBaseWorker) runJob(ctx context.Context, job *regionJob) error
 			// if the region has no leader, such as when PD leader fail-over, and
 			// hasn't got the region heartbeat, the scanned regions might not
 			// contain the leader info. it's meaningless to write in this case.
-			if job.region.Leader == nil {
+			// here we check store ID, not the nilness of leader Peer, as PD will
+			// return an empty Peer if no leader instead of nil.
+			// GetStoreId will return 0 if the Peer is nil, so we can handle both
+			// cases here.
+			// Also note, valid store ID > 0.
+			if job.region.Leader.GetStoreId() == 0 {
```
Comment (joechenrh) [inline pkg/lightning/backend/local/job_worker.go:168]: I saw the code in kvproto https://github.com/pingcap/kvproto/blob/1907922fbd18b46f00651f2d11ab5876a008e7c8/pkg/metapb/metapb.pb.go#L760-L765
A small question, when will we get a peer with zero store ID

Comment (D3Hunter) [reply pkg/lightning/backend/local/job_worker.go:168]: i explain it in the comment, when there is no leader, PD returns a empty instance of Peer which has the zero value for it's StoreId field, and is 0

File: pkg/lightning/backend/local/job_worker.go [hunk 2]
```diff
@@ -155,7 +156,20 @@ func (w *regionJobBaseWorker) runJob(ctx context.Context, job *regionJob) error
...
+			// hasn't got the region heartbeat, the scanned regions might not
+			// contain the leader info. it's meaningless to write in this case.
+			// here we check store ID, not the nilness of leader Peer, as PD will
+			// return an empty Peer if no leader instead of nil.
+			// GetStoreId will return 0 if the Peer is nil, so we can handle both
+			// cases here.
+			// Also note, valid store ID > 0.
+			if job.region.Leader.GetStoreId() == 0 {
+				job.lastRetryableErr = errdef.ErrNoLeader.GenWithStackByArgs(job.region.Region.GetId())
+				job.convertStageTo(needRescan)
```
Comment (lance6716) [inline pkg/lightning/backend/local/job_worker.go:170]: If the raft member state are not change and only PD losts the latest state, change to "regionScanned" is better

Comment (D3Hunter) [reply pkg/lightning/backend/local/job_worker.go:170]: how to determine `raft member state are not change and only PD losts the latest state`?

Comment (lance6716) [reply pkg/lightning/backend/local/job_worker.go:170]: If we optimistically & wrongly change to `regionScanned`, later in write RPC TiDB will see "epoch not match", "request too old" and it comes to `needRescan`. Luckily we don't need to scan region, but the tradeoff is we may have an extra round to process the job.

Comment (lance6716) [reply pkg/lightning/backend/local/job_worker.go:170]: I don't know the background context of this issue. If only PD reboot, I think TiKV's raft epoch is not changed, regionScanned is better.

Comment (D3Hunter) [reply pkg/lightning/backend/local/job_worker.go:170]: if we cannot determine based on the scanned region info, we have to write or ingest and let tikv return the error back to us

in the case of this PR, the above check is to check whether the scanned region have leader or not, if no, we have to rescan

Comment (lance6716) [reply pkg/lightning/backend/local/job_worker.go:170]: lgtm
