### PR TITLE
ddl: skip waiting version synced without MDL for multi-schema-change

### LINKED ISSUE #61680: The multi-schema change DDL gets stuck while MDL is disabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> select @@tidb_enable_metadata_lock;
+-----------------------------+
| @@tidb_enable_metadata_lock |
+-----------------------------+
|                           1 |
+-----------------------------+
1 row in set (0.00 sec)

mysql> create table t(col1 int, col2 int, col3 int);
Query OK, 0 rows affected (0.11 sec)

mysql> set global tidb_enable_metadata_lock=off;
Query OK, 0 rows affected (0.02 sec)

mysql> alter table t drop column col1, drop column col2;
```

### 2. What did you expect to see? (Required)

The alter statement returns quickly.
### 3. What did you see instead (Required)

The statement is stuck.
### 4. What is your TiDB version? (Required)

v6.5.12

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #61680

Problem Summary:

See https://github.com/pingcap/tidb/issues/61680#issuecomment-3087986458

### What changed and how does it work?

If `runOneJobStep` returns `ver == 0`, skip waiting version synced.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/meta/model/job.go [hunk 1]
```diff
@@ -392,6 +392,10 @@ type Job struct {
 
 	// SessionVars store session variables
 	SessionVars map[string]string `json:"session_vars,omitempty"`
+
+	// IgnoreVersionUpdate is set if the schema version returned by runOneJobStep is zero.
+	// For non-MDL scenario, scheduler can skip waitVersionSyncedWithoutMDL.
+	IgnoreVersionUpdate bool `json:"ignore_version_update"`
```
Comment (tangenta) [inline pkg/meta/model/job.go]: Is it necessary to persist this field?

Comment (CbcWestwolf) [reply pkg/meta/model/job.go]: Yes, since the job is retrieved in https://github.com/pingcap/tidb/blob/55ff7e8a3a0cca1796b39383bd1aeb5841f1b63e/pkg/ddl/job_scheduler.go#L513
If we do not persist the field, it is always `false` in the next `transitOneJobStepAndWaitSync`

File: pkg/ddl/multi_schema_change_test.go [hunk 2]
```diff
@@ -847,6 +849,44 @@ func TestMultiSchemaChangeMDLView(t *testing.T) {
...
+					res := tk.MustQuery("admin show ddl jobs 1").Rows()
+					return res[0][11] == "synced"
+				}, 3*time.Second, 500*time.Millisecond)
+			}()
+			tk.MustExec("set global tidb_enable_metadata_lock = on;")
+			tk.MustExec("drop table if exists t;")
+			tk.MustExec("create table t(col1 int, col2 int, col3 int, index idx2(col2), index idx3(col2));")
+			tk.MustExec("set global tidb_enable_metadata_lock = off;")
+			tk.MustExec(tc.sql)
+			wg.Wait()
```
Comment (tangenta) [inline pkg/ddl/multi_schema_change_test.go]: If `MustExec` returns, the job state must be synced. I think we can remove the goroutine?

File: pkg/meta/model/job.go (hunk 1 above)
Comment (tangenta) [reply pkg/meta/model/job.go]: Maybe changing it to `lastSchemaVersion` is better for future usage / debugging.

File: pkg/ddl/multi_schema_change_test.go (hunk 2 above)
Comment (CbcWestwolf) [reply pkg/ddl/multi_schema_change_test.go]: [`4cacb29` (#62477)](https://github.com/pingcap/tidb/pull/62477/commits/4cacb29f152b59584b5b32e989f6eb7b87e9fd4d)

File: pkg/meta/model/job.go (hunk 1 above)
Comment (CbcWestwolf) [reply pkg/meta/model/job.go]: [`9d40555` (#62477)](https://github.com/pingcap/tidb/pull/62477/commits/9d405552f3e5ff8a6c440ac1b4218e8b83b29f52)

File: pkg/ddl/job_scheduler.go [hunk 3]
```diff
@@ -582,7 +582,7 @@ func (s *jobScheduler) transitOneJobStepAndWaitSync(wk *worker, jobCtx *jobConte
 				jobCtx.logger.Warn("check MDL info failed", zap.Error(err))
 				return err
 			}
-		} else {
+		} else if job.LastSchemaVersion > 0 {
```
Comment (fzzf678) [inline pkg/ddl/job_scheduler.go:585]: Will non multi-schema change DDL return 0 here?

Comment (CbcWestwolf) [reply pkg/ddl/job_scheduler.go:585]: Yes, some DDLs also return 0 for `runOneJobStep`

**Review by fzzf678 — APPROVED** [review]
