### PR TITLE
ddl: fix create table too many indexes

### LINKED ISSUE #20163: could create more indexes on a single table than doc
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

doc: https://docs.pingcap.com/tidb/stable/tidb-limitations#limitations-on-a-single-table

```golang
package main

import (
	"database/sql"
	"fmt"

	"github.com/go-sql-driver/mysql"
)
import _ "github.com/go-sql-driver/mysql"

func main() {
	db, err := sql.Open("mysql", "root:@tcp(127.0.0.1:4000)/somedb?maxAllowedPacket=0")
	if err != nil {
		panic(err)
	}

	sql := "create table if not exists t1 ("
	for i := 0; i < 100; i++ {
		if i != 0 {
			sql += ","
		}
		sql += fmt.Sprintf("c%d int", i)
	}
	for i := 0; i < 100; i++ {
		sql += ","

		sql += fmt.Sprintf("key k%d(c%d)", i, i)
	}

	sql += ")"

	fmt.Println(sql)

	ret, err := db.Exec(sql)
	if err != nil {
		panic(err)
	}
	a, err := ret.RowsAffected()
	if err != nil {
		panic(err)
	}
	fmt.Println(a)
}
```

### 2. What did you expect to see? (Required)

```
Error 1069: Too many keys specified; max 64 keys allowed
```

### 3. What did you see instead (Required)

no error

### 4. What is your TiDB version? (Required)

```
| Release Version: v4.0.0-beta.2-1274-g462927bf3
Edition: Community
Git Commit Hash: 462927bf31f456b23625fc2b43417cd99a660508
Git Branch: master
UTC Build Time: 2020-09-23 04:08:58
GoVersion: go1.13.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

### PR DESCRIPTION
**Pull request by b41sh**
### What problem does this PR solve?

Issue Number: close #20163

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:
check index numbers when creating a table

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- fix too many indexes

### CODE REVIEW

File: ddl/db_integration_test.go [hunk 1]
```diff
@@ -55,6 +55,7 @@ var _ = Suite(&testIntegrationSuite4{&testIntegrationSuite{}})
 var _ = Suite(&testIntegrationSuite5{&testIntegrationSuite{}})
 var _ = Suite(&testIntegrationSuite6{&testIntegrationSuite{}})
 var _ = SerialSuites(&testIntegrationSuite7{&testIntegrationSuite{}})
+var _ = Suite(&testIntegrationSuite8{&testIntegrationSuite{}})
```
Comment (wjhuang2016) [inline ddl/db_integration_test.go:58]: Please use SerialSuites because the test uses the global variable `TableIndexCountLimit`.

Comment (b41sh) [reply ddl/db_integration_test.go]: done

File: ddl/index.go [hunk 2]
```diff
@@ -487,6 +487,10 @@ func (w *worker) onCreateIndex(d *ddlCtx, t *meta.Meta, job *model.Job, isPK boo
 		indexInfo.ID = allocateIndexID(tblInfo)
 		tblInfo.Indices = append(tblInfo.Indices, indexInfo)
 
+		if err = checkAddIndexTooManyIndexes(len(tblInfo.Indices)); err != nil {
```
Comment (wjhuang2016) [inline ddl/index.go:490]: checkTooManyIndexes?

Comment (b41sh) [reply ddl/index.go]: done

File: ddl/db_integration_test.go [hunk 3]
```diff
@@ -1351,6 +1353,27 @@ func (s *testIntegrationSuite6) TestCreateTableTooLarge(c *C) {
 	atomic.StoreUint32(&ddl.TableColumnCountLimit, originLimit)
 }
 
+func (s *testIntegrationSuite8) TestCreateTableTooManyIndexes(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+
+	count := int(atomic.LoadUint32(&ddl.TableIndexCountLimit) + 1)
```
Comment (wjhuang2016) [inline ddl/db_integration_test.go:1360]: If you use the global variable, the test should be serial.

Comment (b41sh) [reply ddl/db_integration_test.go]: I removed the global variable
PTAL @wjhuang2016

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by bb7133 — COMMENTED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Comment by b41sh** [comment]
can we merge this PR? @wjhuang2016 @bb7133

**Comment by bb7133** [comment]
LGTM, but theoretically this is a potential compatibility-breaker. Maybe we need a configuration to ensure it doesn't break existing TiDB users.

**Comment by b41sh** [comment]
> LGTM, but theoretically this is a potential compatibility-breaker. Maybe we need a configuration to ensure it doesn't break existing TiDB users.

ok

**Review by bb7133 — APPROVED** [review]

**Comment by bb7133** [comment]
> > LGTM, but theoretically this is a potential compatibility-breaker. Maybe we need a configuration to ensure it doesn't break existing TiDB users.
> 
> ok

Hi @b41sh After some discussions, I think it's not necessary to add such configuration since we never find a user that created 64+ indexes. Thanks for your contribution!
