### PR TITLE
*: polish the table cache feature code

### LINKED ISSUE #33167: table cache lease too short cause load data infinitely
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Testing table cache feature, sysbench oltp_read_only, table size 100000, 32 tables, 'alter table cache'
When the machine load is heavy, load table takes more than 3s
However, the default lease time is 3s...
It means the loaded data is outdated immediately, so the date is reloaded, and the process repeat forever

It waste a lot of CPU resource and make the QPS low.

 

### 2. What did you expect to see? (Required)

Table cache lease is long, and load data is fast, so the load data is infrequent and renew lease enlarge the TTL of the loaded data.

### 3. What did you see instead (Required)
Table cache lease is short, and load data takes long.
The data is  outdated immediately after it's loaded! So the loading process repeat again and again

image

### 4. What is your TiDB version? (Required)

master 2ae71323cf925d187338bb6baa0b70687ace51a8

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #33167

Problem Summary:

### What is changed and how it works?

- Ｍake if clear that `StateRemote`  is not thread-safe
- Cache the latest known local state to avoid unnecessary visit to the remote meta data and reduce conflict
- Use pessimistic transaction mode for updating write lock of `StateRemote`
- Fix a bug that write operation doesn't set write lock when it's already in write locked state 
- Fix table cache lease too short cause load data infinitely
- Add a metrics for loading table data duration

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Run a playground tidb cluster, the use sysbench with hybrid workload.
For example, oltp_read_write on tidb server1,   oltp_point_select on tidb server2, and oltp_read_write on tidb server 3 ...
Adjust the order randomly and observe the performance and cluster status.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: table/tables/cache.go [hunk 1]
```diff
@@ -42,8 +44,8 @@ type cachedTable struct {
 	cacheData atomic.Value
 	handle    StateRemote
 	totalSize int64
-
-	renewReadLease tokenLimit
+	// StateRemote is not thread-safe, this tokenLimit is used to keep only one visitor.
+	tokenLimit
```
Comment (lcwangchao) [inline table/tables/cache.go:48]: Just a suggestion... Maybe we can force users to use tokenLimit before using `StateRemote` like:

```
type tokenLimit = chan StateRemote
```

and provide methods:

```
func TakeStateRemoteHandle() StateRemote {
  handle := <- tokenLimit
  return handle
}

func TakeStateRemoteHandleNoWait() StateRemote {
    select {
    case handle := <-tokenLimit:
       return handle
    default:
      return nil
    }
}

func PutRemotehandle(handle StateRemote) {
  tokenLimit <- handle
}
```

It can achieve the thread safe goal and easier to use

File: table/tables/cache.go [hunk 2]
```diff
@@ -273,3 +289,60 @@ func (c *cachedTable) renewLease(ts uint64, data *cacheData, leaseDuration time.
...
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if succ {
+		atomic.StoreUint64(leasePtr, newLease)
+	}
+	return nil
+}
+
+func (c *cachedTable) lockForWrite(ctx context.Context, ts uint64) (uint64, error) {
```
Comment (lcwangchao) [inline table/tables/cache.go:337]: seems `ts` is not used. It can be removed for this method and `WriteLockAndKeepAlive` can also remove `ts` too

Comment (lcwangchao) [inline table/tables/cache.go:337]: seems `ts` is not used. It can be removed for this method and `WriteLockAndKeepAlive` can also remove `ts` too

File: table/tables/cache.go (hunk 1 above)
Comment (tiancaiamao) [reply table/tables/cache.go:48]: This code looks smart, I'll take a try

File: table/tables/cache.go (hunk 2 above)
Comment (tiancaiamao) [reply table/tables/cache.go]: Done

File: table/tables/cache.go (hunk 1 above)
Comment (tiancaiamao) [reply table/tables/cache.go:47]: Done

File: session/session.go [hunk 3]
```diff
@@ -627,13 +626,14 @@ type cachedTableRenewLease struct {
 	exit   chan struct{}
 }
 
-func (c *cachedTableRenewLease) start(ctx context.Context) error {
+func (c *cachedTableRenewLease) start(ctx context.Context, startTS uint64) error {
```
Comment (lcwangchao) [inline session/session.go:629]: startTS is not used now

**Review by lcwangchao — COMMENTED** [review]
Rest LGTM

File: session/session.go (hunk 3 above)
Comment (tiancaiamao) [reply session/session.go]: Done

File: table/tables/cache.go [hunk 4]
```diff
@@ -71,10 +90,10 @@ func newMemBuffer(store kv.Storage) (kv.MemBuffer, error) {
 	return buffTxn.GetMemBuffer(), nil
 }
 
-func (c *cachedTable) TryReadFromCache(ts uint64, leaseDuration time.Duration) kv.MemBuffer {
+func (c *cachedTable) TryReadFromCache(ts uint64, leaseDuration time.Duration) (kv.MemBuffer /*loading*/, bool) {
```
Comment (tangenta) [inline table/tables/cache.go:93]:
```suggestion
func (c *cachedTable) TryReadFromCache(ts uint64, leaseDuration time.Duration) (kv.MemBuffer, bool /*loading*/) {
```

The gofmt does not work well.

File: table/tables/cache.go [hunk 5]
```diff
@@ -165,45 +182,57 @@ func (c *cachedTable) loadDataFromOriginalTable(store kv.Storage, lease uint64)
...
+				return
+			}
+
+			tmp := c.cacheData.Load().(*cacheData)
+			if tmp != nil && tmp.Start == ts {
+				c.cacheData.Store(&cacheData{
+					Start:     startTS,
+					Lease:     tmp.Lease,
+					MemBuffer: mb,
+				})
```
Comment (tangenta) [inline table/tables/cache.go:232]: What if the cacheData is changed immediately after `Load()`?

File: table/tables/cache.go [hunk 6]
```diff
@@ -165,45 +182,57 @@ func (c *cachedTable) loadDataFromOriginalTable(store kv.Storage, lease uint64)
...
-			Start:     startTS,
+			Start:     ts,
 			Lease:     lease,
-			MemBuffer: mb,
+			MemBuffer: nil, // Async loading, this will be set later.
 		})
-		atomic.StoreInt64(&c.totalSize, totalSize)
+
+		// Make the load data process async, in case that loading data takes longer the
+		// lease duration, then the loadad data get staled and that process repeats forever.
```
Comment (tangenta) [inline table/tables/cache.go:216]:
```suggestion
		// lease duration, then the loaded data get staled and that process repeats forever.
```

**Review by lcwangchao — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
