### PR TITLE
*: fix cte nil pointer error when got multiple apply

### LINKED ISSUE #44774: Got nil pointer error when multiple Apply is used with CTE
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
drop table if exists t1;
create table t1(a int);
insert into t1 values(1), (2);
SELECT * FROM t1 dt WHERE EXISTS( WITH RECURSIVE qn AS (SELECT a AS b UNION ALL SELECT b+1 FROM qn WHERE b=0 or b = 1) SELECT * FROM qn dtqn1 where exists (select /*+ NO_DECORRELATE() */ b from qn where dtqn1.b+1));
```
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
runs ok
### 3. What did you see instead (Required)
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
### 4. What is your TiDB version? (Required)
```
MySQL [test]> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.2.0-alpha-467-g9696d8f7c3
Edition: Community
Git Commit Hash: 9696d8f7c3dffac156764d4f2b127bdc755a499b
Git Branch: master
UTC Build Time: 2023-06-19 08:15:44
GoVersion: go1.20.1
Race Enabled: false
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #44774

Problem Summary:
The following plan:
```
Apply-1
    outerSide
    Apply-2
        CTE-1(access CTEProducer-1)
        CTE-2(access CTEProducer-1)

CTEProducer-1 has corCol, which is one of columns of Apply-1's outerSide output)
```
If `CTE-1` and `CTE-2` both access the same CTE Producer(a.k.a. same CTE defition), we use `CTEExec.IsInApply` to control whether reopen CTEStorage.

But `CTE.IsInApply` is not enough here, because CTE-1 and CTE-2 only need to reopen when Apply-1 runs, no need to reopen when Apply-2 runs.

### What is changed and how it works?
Before: Always reopen CTEStorage/CTEProducer when `CTE.IsInApply` is true.

After: Only reopen CTEStorage/CTEProducer when the data of corCol changes.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/cte.go [hunk 1]
```diff
@@ -657,3 +655,29 @@ func (p *cteProducer) checkHasDup(probeKey uint64,
...
+	if len(c1) != len(c2) {
+		return false
+	}
+	for i := 0; i < len(c1); i++ {
+		if c1[i] != c2[i] {
+			return false
+		}
+	}
+	return true
+}
```
Comment (winoros) [inline executor/cte.go:683]: Why do we need this instead of using `bytes.Compare()`?

Comment (guo-shaoge) [reply executor/cte.go]: Done

File: expression/column.go [hunk 2]
```diff
@@ -223,6 +223,17 @@ func (col *CorrelatedColumn) RemapColumn(m map[int64]*Column) (Expression, error
 	}, nil
 }
 
+// HashCode implements Expression interface.
+func (col *CorrelatedColumn) HashCode(sc *stmtctx.StatementContext) []byte {
+	// Doesn't check len(hashcode) because col.Data can be changed anytime,
+	// So always use newest Datum to calc hash code.
+	col.Column.HashCode(sc)
+	if col.Data != nil {
+		col.hashcode = codec.HashCode(col.hashcode, *col.Data)
```
Comment (AilinKid) [inline expression/column.go:232]: don't change the original col's hash code here, after appending with another datum, the changed hash code couldn't be used as the original column's hash code anymore.

Comment (AilinKid) [reply expression/column.go:232]: col.hashcode actually used the original column's hashcode

File: executor/builder.go [hunk 3]
```diff
@@ -5364,10 +5370,16 @@ func (b *executorBuilder) buildCTE(v *plannercore.PhysicalCTE) Executor {
...
-		recursiveExec := b.build(v.RecurPlan)
-		if b.err != nil {
-			return nil
+		var recursiveExec Executor
+		if v.RecurPlan != nil {
+			recursiveExec = b.build(v.RecurPlan)
+			if b.err != nil {
+				return nil
+			}
+			recursiveCorCols := plannercore.ExtractCorrelatedCols4PhysicalPlan(v.RecurPlan)
```
Comment (AilinKid) [inline executor/builder.go:5379]: looks good, any refinement

File: expression/column.go (hunk 2 above)
Comment (guo-shaoge) [reply expression/column.go:232]: CorrelatedColumn copy original Column instead of using pointer

File: executor/builder.go (hunk 3 above)
Comment (guo-shaoge) [reply executor/builder.go]: Done

**Review by AilinKid — APPROVED** [review]

File: expression/column.go [hunk 4]
```diff
@@ -223,6 +223,20 @@ func (col *CorrelatedColumn) RemapColumn(m map[int64]*Column) (Expression, error
 	}, nil
 }
 
+// HashCode implements Expression interface.
+func (col *CorrelatedColumn) HashCode(sc *stmtctx.StatementContext) []byte {
+	// Doesn't check len(hashcode) because col.Data can be changed anytime,
+	// So always use newest Datum to calc hash code.
+	col.hashcode = make([]byte, 0, 9)
```
Comment (guo-shaoge) [inline expression/column.go:230]: Each call of `(*CorrelatedColumn) HashCode) will create a new slice, because we don't know if the datum `col.Data` pointed changed or not.

Comment (guo-shaoge) [reply expression/column.go]: Refined

**Review by wjhuang2016 — APPROVED** [review]
