### PR TITLE
br: fix some bugs for pitr filter

### LINKED ISSUE #65256: bug list for pitr table filter
### major bug list
- [x] [PR1] **Should skip if db/table id is not found in `dbReplaces` from PiTR id map for A<->A PITR.** the metakv restore during log restore will put a default cf kv with original timestamp and rewritten dbID/tableID. Therefore, when retry restore, the kv will be loaded but not found in PiTR id map.
- [x] [PR1] **The restore id is 0 of PiTR id map.**
- [ ] **Database is duplicated.** If a database is created during log restore, and there is already a database with the same name in the downstream cluster, br will create another database with the same name so that the cluster has 2 databases with the same name.
- [x] [PR1] **The restore start ts of block list file should be recorded in the checkpoint.**

### corner case bug list

- [ ] **Constraint name is duplicated.** If log restore a table with a constraint named `chk1` and there is already another table in the same database having a constraint named `chk1` too, it won't report any error. The workaround is log restore by database level to avoid this case.
- [ ] **Table may still be cache status.** br should set `(*model.TableInfo).TableCacheStatusType` to `TableCacheStatusDisable` when rewrite entry for table.
- [x] [PR1] **Maybe the count of write cf meta kv is more than that of default cf meta kv.** `default cf kv is lost when processing write cf kv for table`

### Adjustment suggestions

- [ ] If a foreign key is created during log restore, report error only when recreate the foreign key if PITR only restore child table.
- [ ] Waiting 5 minutes to retry restore is too long after restore exits unexpectedly(oom or panic).
- [x] [PR1] If PITR restore specifies `--restored-ts` and exits unexpectedly(oom or panic), the retry restore cannot specify `--restored-ts`.
- [x] [PR1] blocklist error shows the `RestoreStartTs` too. (for example `cannot restore the table...`).

## Fix PR List
- PR1: #65394

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #65256

Problem Summary:
some bugs recorded in the above issue.
### What changed and how does it work?
fix these bugs
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/task/stream.go [hunk 1]
```diff
@@ -2082,6 +2085,13 @@ func (p *PiTRTaskInfo) hasTiFlashItemsInCheckpoint() bool {
 	return p.CheckpointInfo != nil && p.CheckpointInfo.Metadata != nil && p.CheckpointInfo.Metadata.TiFlashItems != nil
 }
 
+func (p *PiTRTaskInfo) getRestoreStartTS(ctx context.Context, pdClient pd.Client) (uint64, error) {
+	if p.CheckpointInfo != nil && p.CheckpointInfo.Metadata != nil && p.CheckpointInfo.Metadata.RestoreStartTS != 0 {
+		return p.CheckpointInfo.Metadata.RestoreStartTS, nil
+	}
+	return restore.GetTSWithRetry(ctx, pdClient)
```
Comment (RidRisR) [inline br/pkg/task/stream.go:2092]: Seems vulnerable. Considering a breakpoint generated before the update, seems it will allow restore a dup table ID.

**Review by YuJuncen — APPROVED** [review]
