### PR TITLE
executor: fix tidb can not show view data_type

### LINKED ISSUE #22316: tidb 4.0.0 can not show view data_type
image
create view xxx as select * from xxx;
then show column data_type ，select * from INFORMATION_SCHEMA.columns where table_name=‘v_t_store_refund_info’
the data_type column value is "unspecified"

Release Version: v4.0.0
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time: 2020-05-28 01:37:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by beihaiguaishou**
### What problem does this PR solve?

Issue Number: close #22316

Problem Summary: When run "select * from INFORMATION_SCHEMA.columns where table_name=‘some_view’", the row "data_type" and "column_type" can't get correct result.

### What is changed and how it works?

What's Changed: When we fetch column info of a view via "INFORMATION_SCHEMA.columns", we build this view to get the real output schema.

How it Works: When we fetch column info of a view via "INFORMATION_SCHEMA.columns", we build this view to get the real output schema. Just like what we do in fetchShowColumns(executor/show.go).

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test

Side effects

- None

### Release note 

- No release note

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
The data type should be built during `create view`.

File: executor/infoschema_reader.go [hunk 1]
```diff
@@ -565,7 +567,27 @@ func (e *hugeMemTableRetriever) setDataForColumns(ctx sessionctx.Context) error
 	return nil
 }
 
-func (e *hugeMemTableRetriever) dataForColumnsInTable(schema *model.DBInfo, tbl *model.TableInfo) {
+func (e *hugeMemTableRetriever) dataForColumnsInTable(ctx context.Context, sctx sessionctx.Context, schema *model.DBInfo, tbl *model.TableInfo) {
+	if tbl.IsView() {
+		// retrieve view columns info
```
Comment (wjhuang2016) [inline executor/infoschema_reader.go:572]: // Retrieve view columns info.

File: executor/infoschema_reader.go [hunk 2]
```diff
@@ -565,7 +567,27 @@ func (e *hugeMemTableRetriever) setDataForColumns(ctx sessionctx.Context) error
 	return nil
 }
 
-func (e *hugeMemTableRetriever) dataForColumnsInTable(schema *model.DBInfo, tbl *model.TableInfo) {
+func (e *hugeMemTableRetriever) dataForColumnsInTable(ctx context.Context, sctx sessionctx.Context, schema *model.DBInfo, tbl *model.TableInfo) {
+	if tbl.IsView() {
+		// Retrieve view columns info.
+		planBuilder, _ := plannercore.NewPlanBuilder(sctx, infoschema.GetInfoSchema(sctx), &hint.BlockHintProcessor{})
```
Comment (wjhuang2016) [inline executor/infoschema_reader.go:573]: Can we use a function to handle this logic so that we can reuse the code?

Comment (beihaiguaishou) [reply executor/infoschema_reader.go:573]: Yes. But we should discuss which place this function should place, it will be called in "executor/show.go" and "executor/infoschema_reader.go". I think "infoschema/infoschema.go" is a good place for it, or we just put it to "executor/show.go" or "executor/infoschema_reader.go". What do you think?

Comment (beihaiguaishou) [reply executor/infoschema_reader.go:573]: Updated. I test on my side, place it to "infoschema/infoschema.go" is not work, it will cause cycle import.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
