### PR TITLE
planner: check index valid while forUpdateRead

### LINKED ISSUE #21498: RC transactions may see inconsistent data when there are concurrent DDLs
## Bug Report

**The reason**:  In the current implementation of RC transaction, it fetches a latest ts to read data for each read statement. However it always uses the schema at the transaction's startTS (if I'm correct). So if the schema changed while the transaction is running, the transaction may see data that doesn't match the definition of the schema.

### 1. Minimal reproduce step (Required)

There may be various cases. Here are two examples.

#### Case 1: RC transaction uses IndexReader when the index is dropped and before GC.

```sql
create table t (id int primary key, v int, index iv (v));
insert into t values (1, 10), (2, 20), (3, 30), (4, 40);
```

| session1 | session2 | result |
|--|--|--|
| `set transaction isolation level read committed; begin;` | | |
| `explain select * from t where v = 10;` | | `IndexReader/IndexRangeScan` |
| `select * from t where v = 10;` | | `(1, 10)` |
| | `alter table t drop index iv;` | |
| | `update t set v = 11 where id = 1;` | |
| `explain select * from t where v = 10;` | | `IndexReader/IndexRangeScan` |
| `select * from t where v = 10;` | | `(1, 10)` |
| `select * from t where id = 1;` | | `(1, 11)` |

#### Case 2: RC transactionuses IndexLookup when the index is dropped and before GC.

```sql
create table t (id int primary key, v int, index iv (v), v2 int);
insert into t values (1, 10, 100), (2, 20, 200), (3, 30, 300), (4, 40, 400);
```

| session1 | session2 | result |
|--|--|--|
| `set transaction isolation level read committed; begin;` | | |
| `select * from t use index (iv) where v = 10;` | | `(1, 10, 100)` |
| | `alter table t drop index iv;` | |
| | `update t set v = 11 where id = 1;` | |
| `select * from t use index (iv) where v = 10;` | | `(1, 11, 100)` |
| | `update t set id = 5 where id = 1;` | |
| `select * from t use index (iv) where v = 10;` | | `ERROR 1105 (HY000): inconsistent index iv handle count 1 isn't equal to value count 0` |

### 2. What did you expect to see? (Required)

For case 1, there last `select * from t where v = 10;` should return empty result;
For case 2, session 1 should be able to use index (iv) in the last query

### 3. What did you see instead (Required)

As listed in the table above.

### 4. What is your TiDB version? (Required)

master (3a32bd2df58d3f85504b8f928c70787ced75333a), compiled with fail point (but not used)

### PR DESCRIPTION
**Pull request by you06**
Signed-off-by: you06 <you1474600@gmail.com>

### What problem does this PR solve?

Issue Number: workaround for #21498

Problem Summary:

ForUpdateRead will read data using schema version of startTS, this may lead to incorrectness, the cases are listed in #21498

### What is changed and how it works?

What's Changed:

For RC and forUpdateRead in RR, check if index's state is still `StatePublic`.

How it Works:

This check confirms index between snapshotTS and forUpdateTS is not changed, otherwise, the index should not be used.

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU, there is a little regression testing with tpc-c

### Release note 

- Fix a bug that schema change will lead to incorrectness when forUpdateRead

### CODE REVIEW

**Comment by MyonKeminta** [comment]
🤔 Is it ok to fix it directly to release-4.0 without changing master?

**Comment by you06** [comment]
> thinking Is it ok to fix it directly to release-4.0 without changing master?

IMO, there should be a better solution in master.

**Comment by you06** [comment]
tpcc 1000 warehouses, 128 threads
before this PR: tpmC: 16906.1, efficiency: 131.5%
this PR: tpmC: 16607.8, efficiency: 129.1%

It's about 1.8% of regression.

File: planner/core/planbuilder.go [hunk 1]
```diff
@@ -550,16 +557,20 @@ func NewPlanBuilder(sctx sessionctx.Context, is infoschema.InfoSchema, processor
...
+		handleHelper:    &handleColHelper{id2HandleMapStack: make([]map[int64][]*expression.Column, 0)},
+		hintProcessor:   processor,
+		isForUpdateRead: sctx.GetSessionVars().IsPessimisticReadConsistency(),
 	}
 }
 
 // Build builds the ast node to a Plan.
 func (b *PlanBuilder) Build(ctx context.Context, node ast.Node) (Plan, error) {
+	if b.ctx.GetSessionVars().ConnectionID > 0 {
+		logutil.Logger(ctx).Info("MYLOG Build", zap.String("type", fmt.Sprintf("%T", node)))
```
Comment (cfzjywxk) [inline planner/core/planbuilder.go:572]: Need to remove debug log.

File: planner/core/planbuilder.go [hunk 2]
```diff
@@ -1218,13 +1277,34 @@ func (b *PlanBuilder) buildPhysicalIndexLookUpReaders(ctx context.Context, dbNam
...
 	for _, idx := range indices {
 		idxInfo := idx.Meta()
 		if idxInfo.State != model.StatePublic {
 			logutil.Logger(context.Background()).Info("build physical index lookup reader, the index isn't public",
 				zap.String("index", idxInfo.Name.O), zap.Stringer("state", idxInfo.State), zap.String("table", tblInfo.Name.O))
 			continue
 		}
+		if check {
+			if latestIndex, ok := latestIndexes[idxInfo.ID]; !ok || latestIndex.State != model.StatePublic {
+				logutil.BgLogger().Info("build physical index lookup reader, the index isn't public in forUpdateRead",
```
Comment (cfzjywxk) [inline planner/core/planbuilder.go:1303]: Use `logutil.Logger(ctx)` instead or if this is a debug log we could remove it.

File: planner/core/point_get_plan.go [hunk 3]
```diff
@@ -767,6 +767,20 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt) *PointGetP
...
+	loadLatestIndexes := func() bool {
+		latestIndexes, err = getLatestIndexInfo(ctx, tbl.ID, 0)
+		if err != nil {
+			return false
+		}
+		if latestIndexes == nil {
+			check = false
+		}
+		return true
+	}
```
Comment (cfzjywxk) [inline planner/core/point_get_plan.go:782]: We could abstract it in a function and return the result assigning to `check` varible, as well as the `error` value.

File: planner/core/point_get_plan.go [hunk 4]
```diff
@@ -389,7 +389,7 @@ func TryFastPlan(ctx sessionctx.Context, node ast.Node) (p Plan) {
 			p = fp
 			return
 		}
-		if fp := tryPointGetPlan(ctx, x); fp != nil {
+		if fp := tryPointGetPlan(ctx, x, false); fp != nil {
```
Comment (cfzjywxk) [inline planner/core/point_get_plan.go:392]: Should be `true`？

File: session/pessimistic_test.go [hunk 5]
```diff
@@ -1903,3 +1903,106 @@ func (s *testPessimisticSuite) TestResolveStalePessimisticPrimaryLock(c *C) {
 
 	c.Assert(tk2.ExecToErr("admin check table t1"), IsNil)
 }
+
+func (s *testPessimisticSuite) TestIssue21498(c *C) {
```
Comment (cfzjywxk) [inline session/pessimistic_test.go:1907]: Need to add some `unique key uk(varchar_column)` case using the `IndexLookUp` executor fetching data from unique index and look up data in main table.

File: planner/core/planbuilder.go (hunk 2 above)
Comment (you06) [reply planner/core/planbuilder.go]: There are similar log in this function, I think they can both be removed.

File: planner/core/point_get_plan.go (hunk 4 above)
Comment (you06) [reply planner/core/point_get_plan.go]: Changed to `x.LockTp != ast.SelectLockNone` now.

File: session/pessimistic_test.go (hunk 5 above)
Comment (you06) [reply session/pessimistic_test.go:1907]: Added snapshot read and for update read cases for `IndexLookUp`.

**Comment by you06** [comment]
I wonder there will be a better solution for this issue in master and future release versions, do we need to cherry pick this hotfix to master?

**Comment by cfzjywxk** [comment]
> I wonder there will be a better solution for this issue in master and future release versions, do we need to cherry pick this hotfix to master?

Yes, on master maybe we need a better mechanism to solve the concurrent ddl and dml problem so we won't meet this problem.

File: planner/core/planbuilder.go [hunk 6]
```diff
@@ -1218,13 +1262,43 @@ func (b *PlanBuilder) buildPhysicalIndexLookUpReaders(ctx context.Context, dbNam
...
+	check := b.isForUpdateRead && b.ctx.GetSessionVars().ConnectionID > 0
+	var latestIndexes map[int64]*model.IndexInfo
+	var err error
+	if check {
+		latestIndexes, check, err = getLatestIndexInfo(b.ctx, tblInfo.ID, b.is.SchemaMetaVersion())
+		if err != nil {
+			return nil, nil, err
+		}
+		if latestIndexes == nil {
+			check = false
```
Comment (cfzjywxk) [inline planner/core/planbuilder.go:1275]: This is not needed?

File: planner/core/planbuilder.go [hunk 7]
```diff
@@ -1218,13 +1262,43 @@ func (b *PlanBuilder) buildPhysicalIndexLookUpReaders(ctx context.Context, dbNam
...
+		}
+	}
+
 	for _, idx := range indices {
 		idxInfo := idx.Meta()
 		if idxInfo.State != model.StatePublic {
-			logutil.Logger(context.Background()).Info("build physical index lookup reader, the index isn't public",
-				zap.String("index", idxInfo.Name.O), zap.Stringer("state", idxInfo.State), zap.String("table", tblInfo.Name.O))
+			logutil.Logger(ctx).Info("build physical index lookup reader, the index isn't public",
```
Comment (cfzjywxk) [inline planner/core/planbuilder.go:1282]: `isn't public using for update read` is more clear.

Comment (you06) [reply planner/core/planbuilder.go:1282]: This is the check for snapshot schema, the check for "for update read" is below.

File: planner/core/logical_plan_builder.go [hunk 8]
```diff
@@ -2657,6 +2657,11 @@ func (b *PlanBuilder) buildSelect(ctx context.Context, sel *ast.SelectStmt) (p L
 		gbyCols                       []expression.Expression
 	)
 
+	// set for update read to true before building result set node
+	if sel.LockTp != ast.SelectLockNone {
```
Comment (cfzjywxk) [inline planner/core/logical_plan_builder.go:2661]: We may need to abstract a function for it, actually we do not `for update` read using `lock in share mode` as the [doc ](https://docs.pingcap.com/zh/tidb/stable/pessimistic-transaction#%E5%92%8C-mysql-innodb-%E7%9A%84%E5%B7%AE%E5%BC%82)described.

File: planner/core/point_get_plan.go [hunk 9]
```diff
@@ -389,7 +391,7 @@ func TryFastPlan(ctx sessionctx.Context, node ast.Node) (p Plan) {
 			p = fp
 			return
 		}
-		if fp := tryPointGetPlan(ctx, x); fp != nil {
+		if fp := tryPointGetPlan(ctx, x, x.LockTp != ast.SelectLockNone); fp != nil {
```
Comment (cfzjywxk) [inline planner/core/point_get_plan.go:394]: Use the abstracted function above.

File: session/pessimistic_test.go (hunk 5 above)
Comment (cfzjywxk) [reply session/pessimistic_test.go:1907]: How about the `insert into table select from anothertable`, we have another issue https://github.com/pingcap/tidb/issues/21506, what is the expecting behaviour for this case?

File: planner/core/logical_plan_builder.go (hunk 8 above)
Comment (you06) [reply planner/core/logical_plan_builder.go:2661]: May this function in parser?

Comment (cfzjywxk) [reply planner/core/logical_plan_builder.go:2661]: For this pr we could put it in TiDB repo.

File: session/pessimistic_test.go [hunk 10]
```diff
@@ -1903,3 +1903,119 @@ func (s *testPessimisticSuite) TestResolveStalePessimisticPrimaryLock(c *C) {
...
+		tk.MustQuery("select * from t where v = 10").Check(testkit.Rows())
+		tk2.MustExec("update t set id = 5 where id = 1")
+		err = tk.ExecToErr("select * from t use index (iv) where v = 10") // select with
+		c.Assert(err.Error(), Equals, "[planner:1176]Key 'iv' doesn't exist in table 't'")
+		tk.MustQuery("select * from t where v = 10").Check(testkit.Rows())
+		if !partition {
+			// amend transaction does not support partition table
+			tk.MustExec("insert into t(id, v, v2) select 6, v + 20, v2 + 200 from t where id = 4") // insert ... select with index unchanged
+		}
+		err = tk.ExecToErr("insert into t(id, v, v2) select 7, v + 30, v2 + 300 from t use index (iv) where id = 4") // insert ... select with index changed
```
Comment (lysu) [inline session/pessimistic_test.go:1958]: maybe need add more test: prepare plan cache (maybe have question) and plan binding (maybe have no question)

**Comment by lysu** [comment]
LGTM

**Comment by cfzjywxk** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
