### PR TITLE
ddl: use kv.Key as reorg progress marker instead of kv.Handle

### LINKED ISSUE #20727: *: `insufficient bytes decode value` reported when adding index for some split common-handled tables.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tidb> show variables like '%clustered%';


+-----------------------------+-------+
| Variable_name               | Value |
+-----------------------------+-------+
| tidb_enable_clustered_index | ON    |
+-----------------------------+-------+
1 row in set (0.02 sec)
```

```
tidb> create table t (a varchar(255), b int, primary key(a));
Query OK, 0 rows affected (0.02 sec)

tidb> insert into t values ('a', 1), ('b', 2), ('c', 3), ('u', 1);
Query OK, 4 rows affected (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 0

tidb> split table t between ('a') and ('z') regions 5;
+--------------------+----------------------+
| TOTAL_SPLIT_REGION | SCATTER_FINISH_RATIO |
+--------------------+----------------------+
|                  4 |                    1 |
+--------------------+----------------------+
1 row in set (0.01 sec)

tidb> create index idx on t (b);
```

### 2. What did you expect to see? (Required)
The job ran successfully.

### 3. What did you see instead (Required)
Error reported when executing the DDL job:

```
[worker="worker 2, tp add index"] [error="insufficient bytes to decode value"] [errorVerbose="insufficient bytes to decode value
github.com/pingcap/tidb/util/codec.peekBytes
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/util/codec/codec.go:958
github.com/pingcap/tidb/util/codec.peek
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/util/codec/codec.go:933
github.com/pingcap/tidb/util/codec.CutOne
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/util/codec/codec.go:887
github.com/pingcap/tidb/kv.NewCommonHandle
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/kv/key.go:248
github.com/pingcap/tidb/tablecodec.DecodeRowKey
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/tablecodec/tablecodec.go:269
github.com/pingcap/tidb/ddl.decodeHandleRange
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/ddl/backfilling.go:364
github.com/pingcap/tidb/ddl.(*worker).sendRangeTaskToWorkers
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/ddl/backfilling.go:380
github.com/pingcap/tidb/ddl.(*worker).writePhysicalTableRecord
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/ddl/backfilling.go:563
github.com/pingcap/tidb/ddl.(*worker).addPhysicalTableIndex
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/ddl/index.go:1142
github.com/pingcap/tidb/ddl.(*worker).addTableIndex
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/ddl/index.go:1165
github.com/pingcap/tidb/ddl.(*worker).onCreateIndex.func1
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/ddl/index.go:564
github.com/pingcap/tidb/ddl.(*worker).runReorgJob.func1
	/home/bb7133/Projects/gopath/src/github.com/pingcap/tidb/ddl/reorg.go:190
runtime.goexit
	/home/bb7133/Softwares/go/src/runtime/asm_amd64.s:1374"]
```

### 4. What is your TiDB version? (Required)
This can be reproduced in the master version

### Root Cause
For now, `ADD INDEX`(as well as some other DDL jobs that need data-reorganization) assume that the 'startKey' and 'endKey' of a region can always be decoded:

https://github.com/pingcap/tidb/blob/937949f44d0d25e21f5a5722dbb334773de38db9/ddl/backfilling.go#L359

But it is not the case for:
- The previous versions of TiDB-Lightning(https://github.com/pingcap/tidb-lightning/pull/422)
- Explicit `SPLIT TABLE` for clustered index.

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #20727 

Problem Summary: 
> For now, `ADD INDEX`(as well as some other DDL jobs that need data-reorganization) assume that the 'startKey' and 'endKey' of a region can always be decoded as handle out:
> https://github.com/pingcap/tidb/blob/937949f44d0d25e21f5a5722dbb334773de38db9/ddl/backfilling.go#L359

### What is changed and how it works?

What's Changed: 

The reason why TiDB decodes keys to handles during 'ADD INDEX' is that the reorganization progress is persisted in storage. The handles are used as the progress marker. This PR change the type of marker to `kv.Key`.

How it Works:

Using `kv.Key as the marker skips the decoding routine.

### Related changes

N/A

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Compatibility: this PR should not break compatibility because the binary representation of the progress marker is unchanged.
- Performance: to improve human readability, the key is need to be decoded every time TiDB logs. 

### Release note 

- No release note

### CODE REVIEW

File: ddl/backfilling.go [hunk 1]
```diff
@@ -376,69 +376,66 @@ func (w *worker) handleReorgTasks(reorgInfo *reorgInfo, totalAddedCount *int64,
...
-	startHandle, err := tablecodec.DecodeRowKey(keyRange.StartKey)
-	if err != nil {
-		return nil, nil, errors.Trace(err)
-	}
-	endHandle, err := tablecodec.DecodeRowKey(keyRange.EndKey)
+func tryDecodeToHandleString(key kv.Key) string {
+	handle, err := tablecodec.DecodeRowKey(key)
 	if err != nil {
-		return nil, nil, errors.Trace(err)
+		return ""
```
Comment (wjhuang2016) [inline ddl/backfilling.go:422]: How about returning the bytes?

Comment (tangenta) [reply ddl/backfilling.go:422]: This value should be human readable.

Comment (wjhuang2016) [reply ddl/backfilling.go:422]: We can print the bytes likes `show table regions`

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

File: ddl/reorg.go [hunk 2]
```diff
@@ -492,25 +495,29 @@ func buildCommonHandleFromChunkRow(sctx *stmtctx.StatementContext, tblInfo *mode
...
 
 // getTableRange gets the start and end handle of a table (or partition).
-func getTableRange(d *ddlCtx, tbl table.PhysicalTable, snapshotVer uint64, priority int) (startHandle, endHandle kv.Handle, err error) {
+func getTableRange(d *ddlCtx, tbl table.PhysicalTable, snapshotVer uint64, priority int) (startHandleKey, endHandleKey kv.Key, err error) {
 	// Get the start handle of this partition.
-	err = iterateSnapshotRows(d.store, priority, tbl, snapshotVer, nil, nil, true,
+	err = iterateSnapshotRows(d.store, priority, tbl, snapshotVer, nil, nil,
 		func(h kv.Handle, rowKey kv.Key, rawRecord []byte) (bool, error) {
-			startHandle = h
+			startHandleKey = tbl.RecordKey(h)
```
[the remark this answers is not in the document]
Comment (tangenta) [reply ddl/reorg.go]: Good catch.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
