### PR TITLE
br: repair the index that any foreign key is needed in

### LINKED ISSUE #61642: br: add foreign key op does not work with PiTR
## Bug Report

Testing locally found that if adding foreign key during log backup, it will automatically add an index. In the PiTR restore process, it will first drop the index and then recreate it. However due to foreign key constraint, the drop index op will fail since violating constraint, causing the pitr to fail

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #61642

Problem Summary:
repair index should drop the index at first, but there is a foreign key is needed in it to prevent it from being dropped.
### What changed and how does it work?
drop foreign keys before repair indexes, and finally add back them
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/tests/br_pitr/prepare_data/ingest_repair.sql [hunk 1]
```diff
@@ -45,4 +45,44 @@ CREATE TABLE test.pairs11(x int auto_increment primary key, y int DEFAULT RAND()
...
 ALTER TABLE test.pairs11 ADD UNIQUE KEY u1(x, y);
 
-CREATE TABLE test.huge_idx(id int AUTO_INCREMENT, blob1 varchar(1000), blob2 varchar(1000));
\ No newline at end of file
+CREATE TABLE test.huge_idx(id int AUTO_INCREMENT, blob1 varchar(1000), blob2 varchar(1000));
```
Comment (Tristan1900) [inline br/tests/br_pitr/prepare_data/ingest_repair.sql:48]: can we also add back the foreign key test in br_pitr_table_filter cover all ddl test? it will be a good place to verify it's fixed since that's where we found the problem

Comment (Leavrth) [reply br/tests/br_pitr/prepare_data/ingest_repair.sql:48]: done

File: br/pkg/restore/log_client/client.go [hunk 2]
```diff
@@ -1638,6 +1694,29 @@ func (rc *LogClient) RepairIngestIndex(
...
 		}
 	}
+	for i, sql := range fkSqls {
+		tableInfo, err := info.TableByName(ctx, ast.NewCIStr(sql.SchemaName), ast.NewCIStr(sql.TableName))
+		if err != nil {
+			return errors.Trace(err)
+		}
+		fkSqls[i].OldForeignKeyFound = false
+		fkSqls[i].ForeignKeyUpdated = false
+		if fromCheckpoint {
```
Comment (JQWong7) [inline br/pkg/restore/log_client/client.go:1705]: just curious, `fromCheckpoint` means rerun log restore task?

File: br/pkg/restore/ingestrec/foreign_key.go [hunk 3]
```diff
@@ -0,0 +1,145 @@
...
+	ChildSchemaNameO  string
+	ChildTableNameO   string
+	ParentSchemaNameO string
+	ParentTableNameO  string
+	FKNameO           string
+	ChildCols         []ast.CIStr
+	ParentCols        []ast.CIStr
+	OnDelete          int
+	OnUpdate          int
+}
```
Comment (JQWong7) [inline br/pkg/restore/ingestrec/foreign_key.go]: prefer add comment to make sure the fields is consistent with `model.FKInfo` or use `model.FKInfo` directly?🤔

File: br/pkg/restore/log_client/client.go (hunk 2 above)
Comment (Leavrth) [reply br/pkg/restore/log_client/client.go:1705]: Yes, the last execution may failed after the foreign key is dropped and before the foreign key is recreated.

File: br/pkg/restore/ingestrec/foreign_key.go (hunk 3 above)
Comment (Leavrth) [reply br/pkg/restore/ingestrec/foreign_key.go]: done

File: br/tests/br_pitr/incremental_data/ingest_repair.sql [hunk 4]
```diff
@@ -49,3 +49,30 @@ ALTER TABLE test.pairs10 ADD INDEX i1(y);
...
+ALTER TABLE test.pairs14_child ADD CONSTRAINT fk_0 FOREIGN KEY (pid) REFERENCES test.pairs14_parent (id) ON DELETE CASCADE ON UPDATE CASCADE;
+
+-- test foreign key constraint 3
+ALTER TABLE test.pairs15_parent ADD INDEX i1 (id);
+ALTER TABLE test.pairs15_child ADD CONSTRAINT fk_0 FOREIGN KEY (pid) REFERENCES test.pairs15_parent (id) ON DELETE CASCADE ON UPDATE CASCADE;
+
+-- test foreign key constraint 4
+ALTER TABLE test.pairs16_parent ADD INDEX i2 (id);
+ALTER TABLE test.pairs16_child ADD INDEX i2 (pid);
+ALTER TABLE test.pairs16_child ADD CONSTRAINT fk_0 FOREIGN KEY (pid) REFERENCES test.pairs16_parent (id) ON DELETE CASCADE ON UPDATE CASCADE;
```
Comment (JQWong7) [inline br/tests/br_pitr/incremental_data/ingest_repair.sql:72]: 1. i think we can use different reference such as `ON DELETE SET NULL` here.
2. add some cross schema foreign key test case

**Review by River2000i — APPROVED** [review]
rest LGTM

**Comment by Tristan1900** [comment]
/hold

pending comments from river2000i

**Review by Tristan1900 — APPROVED** [review]

File: br/tests/br_pitr/incremental_data/ingest_repair.sql (hunk 4 above)
Comment (Leavrth) [reply br/tests/br_pitr/incremental_data/ingest_repair.sql:72]: done
