### PR TITLE
expression: modify the mean result of time type

### LINKED ISSUE #17726: P3-[4.0 Bug Hunting]-[Aggregate Function]-no warning and wrong result on date column
## Description
Bug Hunter issue tidb-challenge-program/bug-hunting-issue#105

---

## Bug Report


### 1. What did you do?

````
drop table if exists t0; create table t0 (col0 DATE, col1 VARCHAR(18), col2 BIGINT, col3 INT, col4 DATETIME) charset=latin1, engine=MyISAM;

insert into t0 values ('1000-01-02', '12ab7f97-b847-', '9223372036854775807', '-1', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', '2d3897fd-87a8-49', '9223372036854775807', '2147483647', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', '3d6ab42d-6205-', '-9223372036854775808', '2147483647', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', 'd4', '-1', '-2147483648', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', '75e3be2', '1', '0', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', '364ce', '-9223372036854775808', '2147483647', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', 'bf7d4c41-a006-401e', '1', '-2147483648', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', '36e1f594-ba69-47b', '-9223372036854775808', '2147483647', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', '10ad0402-', '0', '-1', '1000-01-02 00:00:00');

insert into t0 values ('1000-01-02', '678ab1cc-8eb9-4069', '1', '0', '1000-01-02 00:00:00');

select max(col0), min(col0), avg(col0) from t0;
````

### 2. What did you expect to see?

This function should return the correct average of the date not converting the value to a numeric.
In MySQL it converts to float.
This could be considered as a feature more than a bug. See https://bugs.mysql.com/bug.php?id=9874 for details.

I think it is better to raise a warning on such case, `avg() expect a numeric argument, passed is date. converting to number`

````
mysql> select max(col0), min(col0), avg(col0) from t0;
+------------+------------+---------------+
| max(col0)  | min(col0)  | avg(col0)     |
+------------+------------+---------------+
| 1000-01-02 | 1000-01-02 | 10000102.0000 |
+------------+------------+---------------+
1 row in set (0.00 sec)
````

### 3. What did you see instead?

````
mysql> select max(col0), min(col0), avg(col0) from t0;
+------------+------------+-----------+
| max(col0)  | min(col0)  | avg(col0) |
+------------+------------+-----------+
| 1000-01-02 | 1000-01-02 |  10000102 |
+------------+------------+-----------+
1 row in set (0.00 sec)
````
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

````
mysql> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: None
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
````
## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

### PR DESCRIPTION
**Pull request by ou-bing**
### What problem does this PR solve?

Issue Number: close #17726 

### What is changed and how it works?

What's Changed:

modify the mean result of time type.

How it Works:

Force 4 decimal places.

### Release note 

- modify the mean result of time type

### CODE REVIEW

**Comment by ou-bing** [comment]
I can't add test cases, because, in the test environment, the process of reading query results is inconsistent with that in the production environment。

This mainly refers to the difference between func ResultSetToStringSlice and dumpTextRow.

**Review by lzmhhh123 — COMMENTED** [review]
What about not directly compare the string result. Parse the float to compare.

**Comment by ou-bing** [comment]
> What about not directly compare the string result. Parse the float to compare.

Maybe it doesn't make any sense? Because it can pass the test without any modification.

**Comment by ou-bing** [comment]
The test case `TestAsyncCommitWithSchemaChange` is passed in my local environment😂

File: expression/integration_test.go [hunk 1]
```diff
@@ -8181,6 +8181,18 @@ func (s *testIntegrationSerialSuite) TestIssue20876(c *C) {
...
+// The actual results do not agree with the test results, It should be modified after the test suite is updated
+func (s *testIntegrationSuite) TestIssue17726(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop table if exists t0")
+	tk.MustExec("create table t0 (c1 DATE, c2 TIME, c3 DATETIME, c4 TIMESTAMP)")
+	tk.MustExec("insert into t0 values ('1000-01-01', '-838:59:59', '1000-01-01 00:00:00', '1970-01-01 08:00:01')")
+	tk.MustExec("insert into t0 values ('9999-12-31', '838:59:59', '9999-12-31 23:59:59', '2038-01-19 11:14:07')")
+	result := tk.MustQuery("select avg(c1), avg(c2), avg(c3), avg(c4) from t0")
+	result.Check(testkit.Rows("54995666 0 54995666117979.5 20040110095704"))
```
Comment (lzmhhh123) [inline expression/integration_test.go:8193]: It seems not as expected.

Comment (ou-bing) [reply expression/integration_test.go:8193]: Do you want me to compare float values?
Are there any related tools in the test suite...

Comment (lzmhhh123) [reply expression/integration_test.go:8193]: OK, the unit test doesn't go through the client connection. The manual test with the MySQL client is right.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by wshwsh12 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
