### PR TITLE
*: fix incorrect handling meta key in IterateHashWithBoundedKey

### LINKED ISSUE #64323: unexcpected key in hashKey range may cause high CPU usage
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Can't not reproduce now.

### 2. What did you expect to see? (Required)
No unexcpected key in hashKey range. If exists, no deadloop in IterateHashWithBoundedKey 

### 3. What did you see instead (Required)
Deadloop in IterateHashWithBoundedKey cause high CPU usage 
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #64323

Problem Summary:
In TiDB version V5.1 and eailer, there is a meta key in hash struct.
We should skip this keys in TestIterateHashWithBoundedKey

### What changed and how does it work?
Skip meta keys in TestIterateHashWithBoundedKey

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix incorrect handling meta key in IterateHashWithBoundedKey
```

### CODE REVIEW

File: pkg/structure/type.go [hunk 1]
```diff
@@ -81,8 +78,8 @@ func (t *TxStructure) decodeStringDataKey(ek kv.Key) ([]byte, error) {
 	return key, errors.Trace(err)
 }
 
-// nolint:unused
-func (t *TxStructure) encodeHashMetaKey(key []byte) kv.Key {
+// EncodeHashMetaKey exports for tests. It's used in version v5.1 and earlier.
+func (t *TxStructure) EncodeHashMetaKey(key []byte) kv.Key {
```
Comment (D3Hunter) [inline pkg/structure/type.go:82]: why not remove it, we are on master

Comment (wjhuang2016) [reply pkg/structure/type.go:82]: Cluster created in V5.1 and eariler has these keys, and we use this function to test now.

**Review by D3Hunter — APPROVED** [review]
