### PR TITLE
ddl: double check collation compatibility before modifying column

### LINKED ISSUE #61668: Unexpected modify column cause data-index inconsistency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `t` (
  `col6bf3` double NOT NULL DEFAULT '1.7493807071127492',
  `col7044` varchar(145) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'xdwzi7tpmjwxeklahyxvg3gl0mt2x08mdhxz9pbdsdnrvj8qghrckfzat38jkukpycmtwsl3n8nnw9m5hgavfeu8nnhf8e5c7yttr8',
  `col397e` date DEFAULT '6275-04-28',
  `colecb5` text DEFAULT NULL,
  `col2611` float DEFAULT '1.6870946',
  PRIMARY KEY (`col6bf3`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='4a6d1ec3'

```

DO DDL concurrently:
``` 
DDL1:
ALTER TABLE t ADD INDEX idx (col7044)

DDL2:
ALTER TABLE `t` modify column `col7044` VARCHAR(206) NULL DEFAULT 'emtlqampngugbkxqy' FIRST
```

Make DDL1 execute first.

### 2. What did you expect to see? (Required)

The second DDL should fail
### 3. What did you see instead (Required)
Both of the DDLs are successful.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #61668

Problem Summary:

There are two roles for DDL execution:
- DDL submitter: the node that accepts DDL SQL submitted from users.
- DDL owner: the node that runs real DDL workers.

It is a TOCTOU issue. The problem is that DDL submitter checks the collation of MODIFY COLUMN job and make sure there is no index defined on the target column. However, an ADD INDEX job is finished, before DDL owner runs the MODIFY COLUMN job.

### What changed and how does it work?

Add double check at DDL owner side (in `onModifyColumn`).

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

File: pkg/metrics/ddl.go [hunk 1]
```diff
@@ -293,6 +293,9 @@ func RegisterLightningCommonMetricsForDDL(jobID int64) *metric.Common {
 
 // UnregisterLightningCommonMetricsForDDL unregisters the registered common metrics.
 func UnregisterLightningCommonMetricsForDDL(jobID int64, metrics *metric.Common) {
+	if metrics == nil {
```
Comment (fzzf678) [inline pkg/metrics/ddl.go:296]: Is this another bug?

**Review by fzzf678 — APPROVED** [review]

File: pkg/metrics/ddl.go (hunk 1 above)
Comment (tangenta) [reply pkg/metrics/ddl.go:296]: Yes. But this only exists in unit test (when store type != tikv)
