### PR TITLE
br: fix pitr system table inconsistency issue

### LINKED ISSUE #60201: br: pitr doesn't support system restore yet
## Bug Report

The latest change enables pitr to restore system tables where previously it was not, but later we found it's not possible to do pitr restore system table since during snapshot restore it's using REPLACE INTO to inject the data into system table. This operation will change the row id of the system table and messed up with log backup row id unless we override it

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #60201

Problem Summary:

### What changed and how does it work?
Prevent pitr to restore system table change during log backup,
only restore full snapshot to be consistent with previous version

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by Tristan1900** [comment]
/hold
wait for tests

**Review by Leavrth — APPROVED** [review]

File: br/pkg/stream/table_mapping.go [hunk 1]
```diff
@@ -293,11 +293,27 @@ func (tm *TableMappingManager) MergeBaseDBReplace(baseMap map[UpstreamID]*DBRepl
...
+				existingDBReplace.Name = baseDBReplace.Name
+			}
+		}
+
 		for upTableID, existingTableReplace := range existingDBReplace.TableMap {
 			if newID, exists := tm.globalIdMap[upTableID]; exists {
 				existingTableReplace.TableID = newID
 			}
 
+			// update table name if empty and exists in baseMap
```
Comment (BornChanger) [inline br/pkg/stream/table_mapping.go:308]: what's the change for? @Leavrth

Comment (BornChanger) [reply br/pkg/stream/table_mapping.go:308]: please elaborate the comments then

File: br/pkg/stream/table_mapping.go [hunk 2]
```diff
@@ -293,11 +293,27 @@ func (tm *TableMappingManager) MergeBaseDBReplace(baseMap map[UpstreamID]*DBRepl
 			existingDBReplace.DbID = newID
 		}
 
+		// update db name if empty and exists in baseMap
```
Comment (BornChanger) [inline br/pkg/stream/table_mapping.go:296]: ditto

**Review by BornChanger — APPROVED** [review]

File: br/pkg/stream/table_mapping.go [hunk 3]
```diff
@@ -293,11 +293,29 @@ func (tm *TableMappingManager) MergeBaseDBReplace(baseMap map[UpstreamID]*DBRepl
 			existingDBReplace.DbID = newID
 		}
 
+		// db replace in `TableMappingManager` has no name yet, it is determined by baseMap.
+		// TODO: update the name of the db replace that is not exists in baseMap. Now it is OK because user tables' name is not used.
```
Comment (Leavrth) [inline br/pkg/stream/table_mapping.go:297]:
```suggestion
		// TODO: update the name of the db replace that is not exists in baseMap.
		// Now it is OK because user tables' name is not used.
```

File: br/pkg/stream/table_mapping.go [hunk 4]
```diff
@@ -293,11 +293,29 @@ func (tm *TableMappingManager) MergeBaseDBReplace(baseMap map[UpstreamID]*DBRepl
...
+			}
+		}
+
 		for upTableID, existingTableReplace := range existingDBReplace.TableMap {
 			if newID, exists := tm.globalIdMap[upTableID]; exists {
 				existingTableReplace.TableID = newID
 			}
 
+			// table replace in `TableMappingManager` has no name yet, it is determined by baseMap.
+			// TODO: update the name of the table replace that is not exists in baseMap. Now it is OK because user tables' name is not used.
```
Comment (Leavrth) [inline br/pkg/stream/table_mapping.go:310]:
```suggestion
			// TODO: update the name of the table replace that is not exists in baseMap.
			// Now it is OK because user tables' name is not used.
```
