### PR TITLE
*: extract column into map in the constant propagation

### LINKED ISSUE #64128: unnecessary to extract column into slices when to constant propagation
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Image

In the `solve` of constant propagation, the slices of `ExtractColumn` will be converted into a map and deduplicated. Therefore, directly converting them into a map is better than converting them into slices.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #64128

Problem Summary:

### What changed and how does it work?

Image

In the solve of constant propagation, the slices of ExtractColumn will be converted into a map and deduplicated. Therefore, directly converting them into a map is better than converting them into slices.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

before 
```
BenchmarkTPCHQ3-8   	     924	   1159361 ns/op	 1739137 B/op	   23110 allocs/op
BenchmarkTPCDSQ64-8   	     153	   7266446 ns/op	12807037 B/op	  137175 allocs/op
```

after 
```
BenchmarkTPCHQ3-8   	     966	   1149071 ns/op	 1738760 B/op	   23045 allocs/op
BenchmarkTPCDSQ64-8   	     165	   6948597 ns/op	12797896 B/op	  136460 allocs/op
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/constant_propagation.go [hunk 1]
```diff
@@ -469,10 +469,14 @@ func (s *propConstSolver) solve(keepJoinKey bool, conditions []Expression) []Exp
...
 	s.conditions = slices.Grow(s.conditions, len(conditions))
+	mp := GetUniqueIDToColumnMap()
 	for _, cond := range conditions {
 		s.conditions = append(s.conditions, SplitCNFItems(cond)...)
-		s.insertCols(ExtractColumns(cond)...)
+		ExtractColumnsMapFromExpressionsWithReusedMap(mp, nil, cond)
+		s.insertCols(mp)
+		clear(mp)
 	}
+	PutUniqueIDToColumnMap(mp)
```
Comment (windtalker) [inline pkg/expression/constant_propagation.go]: maybe use defer to put mp back?

File: pkg/planner/core/planbuilder.go [hunk 2]
```diff
@@ -2101,7 +2101,7 @@ func (b *PlanBuilder) addColumnsWithVirtualExprs(tbl *resolve.TableNameW, cols *
 	}
 
 	virtualExprs := columnSelector(columns)
-	relatedCols := make(map[int64]*expression.Column, len(tblInfo.Columns))
+	relatedCols := expression.GetUniqueIDToColumnMap()
```
Comment (windtalker) [inline pkg/planner/core/planbuilder.go:2104]: ditto

File: pkg/expression/constant_propagation.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/expression/constant_propagation.go]: The lifecycle here is clear, and the optimization steps are very time-consuming. So we should put it into the pool immediately after it has been used up.

Comment (hawkingrei) [reply pkg/expression/constant_propagation.go]: I refactor the code to use defer

File: pkg/planner/core/planbuilder.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/planner/core/planbuilder.go:2104]: Done

File: pkg/expression/util.go [hunk 3]
```diff
@@ -188,6 +189,23 @@ func ExtractColumnsMapFromExpressions(filter func(*Column) bool, exprs ...Expres
...
+func GetUniqueIDToColumnMap() map[int64]*Column {
+	return uniqueIDToColumnMapPool.Get().(map[int64]*Column)
+}
+
+// PutUniqueIDToColumnMap puts map[int64]*Column map back to the pool.
+func PutUniqueIDToColumnMap(m map[int64]*Column) {
+	clear(m)
+	uniqueIDToColumnMapPool.Put(m)
+}
+
```
Comment (henrybw) [inline pkg/expression/util.go:208]: Why do we need a pool of these? Are these created and destroyed frequently enough that it measurably hurts performance to not use a pool? I would be curious what the performance impact of not using a pool would be.

File: pkg/expression/constant_propagation.go [hunk 4]
```diff
@@ -863,6 +864,23 @@ func (s *propOuterJoinConstSolver) solve(keepJoinKey bool, joinConds, filterCond
...
+		ExtractColumnsMapFromExpressionsWithReusedMap(mp, nil, cond)
+		s.insertCols(mp)
+		clear(mp)
+	}
+	for _, cond := range filterConds {
+		s.filterConds = append(s.filterConds, SplitCNFItems(cond)...)
+		ExtractColumnsMapFromExpressionsWithReusedMap(mp, nil, cond)
+		s.insertCols(mp)
+		clear(mp)
+	}
```
Comment (henrybw) [inline pkg/expression/constant_propagation.go]: These loops seem very similar to each other, and to the above `extractColumns` implementation. Is there any way we can refactor this so there is one implementation of this pattern of looping?

File: pkg/expression/util.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/expression/util.go:208]: Memory reuse can reduce the number of objects on the heap. In fact, TiDB has always had a serious issue: it doesn’t pay much attention to memory reuse, which leads to excessive memory allocation on the heap. As a result, the GoLang GC needs to scan a large number of small objects, significantly increasing the Stop-The-World time.

Comment (hawkingrei) [reply pkg/expression/util.go:208]: Another reason is that the map size here is not easy to determine, which makes the map prone to resizing. The performance of resizing a map in GoLang is relatively poor, as it involves creating a new map. Therefore, the advantage of reusing a map is that the final reused map can be utilized again, avoiding the possibility of further resizing.

File: pkg/expression/constant_propagation.go (hunk 4 above)
Comment (hawkingrei) [reply pkg/expression/constant_propagation.go]: I have refactored this part of the code.

File: pkg/expression/util.go (hunk 3 above)
Comment (hawkingrei) [reply pkg/expression/util.go:208]: image

The phenomenon looks like this

**Comment by hawkingrei** [comment]
> Overall I think this is okay, but I'm skeptical that an object pool for these maps is necessary.
> 
> How often do these maps actually get reused? In addition to making the code more complicated, I'm concerned that using a pool will lead to us hanging onto more maps than we actually need: a pool that is mostly unused seems wasteful compared to just allocating maps each time.
> 
> Do you have any measurements or performance data for how much these maps are reused?

Actually, there's a trick here: TiDB supports Pyroscope. You just need to inject Pyroscope information into the environment to continuously collect profilers and obtain detailed profiler data over a large time span.

**Comment by hawkingrei** [comment]
> Overall I think this is okay, but I'm skeptical that an object pool for these maps is necessary.
> 
> How often do these maps actually get reused? In addition to making the code more complicated, I'm concerned that using a pool will lead to us hanging onto more maps than we actually need: a pool that is mostly unused seems wasteful compared to just allocating maps each time.
> 
> Do you have any measurements or performance data for how much these maps are reused?

Additionally, the benchmark data can be obtained from the benchmark results within the `tpch/tpcds` directory in `planner/core/casetest`. The `gobench` tool will display the number of allocations, and we can observe a reduction in allocations, indicating that our optimizations have taken effect.

I have already posted the gobench data in the issue description.

File: pkg/expression/util.go (hunk 3 above)
Comment (henrybw) [reply pkg/expression/util.go:208]: Makes sense. Thanks for explaining.

**Review by henrybw — APPROVED** [review]
Thanks! LGTM.
