### PR TITLE
executor: return error when recover indexHash/MergeJoin worker (#18509)

### LINKED ISSUE #18070: memory-quota: inl_hash_join doesn't raise error when the usage of memory exceeds
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
_tide-config 
oom-action = "cancel"_
```sql
create table t1(a int, index(a));
create table t2(a int, index(a));
insert into t1 values(1),(2);
insert into t2 values(1),(1),(2),(2);
set @@tidb_mem_quota_query=1000;
select /*+ inl_hash_join(t1)*/ * from t1 join t2 on t1.a = t2.a;
```

### 2. What did you expect to see? (Required)
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=1]

### 3. What did you see instead (Required)
Empty set 
### 4. Affected version (Required)
v4.0.0

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #18509 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #18070  

Problem Summary:

### What is changed and how it works?

What's Changed:
return the OOM error when indexHashJoin worker panics

How it Works:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

N/A

### Release note 

- executor: return the OOM error when indexHashJoin worker panics

### CODE REVIEW

File: executor/index_lookup_merge_join.go [hunk 1]
```diff
@@ -300,12 +300,21 @@ func (e *IndexLookUpMergeJoin) getFinishedTask(ctx context.Context) {
...
 		if r := recover(); r != nil {
+<<<<<<< HEAD
+=======
+			task := &lookUpMergeJoinTask{
+				doneErr: errors.New(fmt.Sprintf("%v", r)),
+				results: make(chan *indexMergeJoinResult, numResChkHold),
+			}
+			close(task.results)
+			omw.resultCh <- task
+>>>>>>> 30858ec... executor: return error when recover indexHash/MergeJoin worker (#18509)
```
Comment (SunRunAway) [inline executor/index_lookup_merge_join.go:312]: Please resolve this conflict.
