### PR TITLE
ddl: consider paused job when check runnable

### LINKED ISSUE #54383: [conn.go:1024] ["connection running loop panic"]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- /go-tpc ch prepare  -P 4000 --warehouses 100 -D tpcc
- /go-tpc ch run -P 4000 --warehouses 100 -T 8 -D tpcc  --acThreads 0 --conn-params \"tidb_isolation_read_engines='tikv,tidb'\" --ignore-error"

### 2. What did you expect to see? (Required)
work well

### 3. What did you see instead (Required)
 [conn.go:1024] ["connection running loop panic"] [conn=132120934] [session_alias=] [lastSQL="INSERT into order_line (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_quantity, ol_amount, ol_dist_info) VALUES (?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?),(?,?,?,?,?,?,?,?,?) [arguments: (3123, 6, 62, 1, 81757, 62, 2, 144.826473888, \"YGUZJCHOKDKQEIUUMONOYUCU\", 3123, 6, 62, 2, 98365, 62, 4, 273.77857451200003, \"LQOCFPZWIJBHNGSGVJQRENIS\", 3123, 6, 62, 3, 16804, 62, 3, 194.4719453424, \"YMKKZYWNRNDSAWNFOGYCUWHS\", 3123, 6, 62, 4, 94585, 62, 6, 145.15265964, \"CULSRIGAEZTATTZQFUXXNRVD\", 3123, 6, 62, 5, 48315, 62, 5, 489.2786280000001, \"ESJODMAFIWSRJPFRBJARLHXP\")]"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1\n\t/workspace/source/tidb/pkg/server/conn.go:1027\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile.func1\n\t/workspace/source/tidb/pkg/executor/compiler.go:57\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/pingcap/tidb/pkg/expression.ColumnInfos2ColumnsAndNames\n\t/workspace/source/tidb/pkg/expression/expression.go:1018\ngithub.com/pingcap/tidb/pkg/expression.TableInfo2SchemaAndNames\n\t/workspace/source/tidb/pkg/expression/expression.go:966\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildInsert\n\t/workspace/source/tidb/pkg/planner/core/planbuilder.go:3633\ngithub.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).Build\n\t/workspace/source/tidb/pkg/planner/core/planbuilder.go:508\ngithub.com/pingcap/tidb/pkg/planner.buildLogicalPlan\n\t/workspace/source/tidb/pkg/planner/optimize.go:564\ngithub.com/pingcap/tidb/pkg/planner.optimize\n\t/workspace/source/tidb/pkg/planner/optimize.go:481\ngithub.com/pingcap/tidb/pkg/planner.Optimize\n\t/workspace/source/tidb/pkg/planner/optimize.go:349\ngithub.com/pingcap/tidb/pkg/planner/core.generateNewPlan\n\t/workspace/source/tidb/pkg/planner/core/plan_cache.go:302\ngithub.com/pingcap/tidb/pkg/planner/core.GetPlanFromPlanCache\n\t/workspace/source/tidb/pkg/planner/core/plan_cache.go:251\ngithub.com/pingcap/tidb/pkg/planner.OptimizeExecStmt\n\t/workspace/source/tidb/pkg/planner/optimize.go:541\ngithub.com/pingcap/tidb/pkg/planner.Optimize\n\t/workspace/source/tidb/pkg/planner/optimize.go:163\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile\n\t/workspace/source/tidb/pkg/executor/compiler.go:99\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\t/workspace/source/tidb/pkg/session/session.go:2098\ngithub.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt\n\t/workspace/source/tidb/pkg/server/driver_tidb.go:294\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).executePreparedStmtAndWriteResult\n\t/workspace/source/tidb/pkg/server/conn_stmt.go:306\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).executePlanCacheStmt\n\t/workspace/source/tidb/pkg/server/conn_stmt.go:234\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmtExecute\n\t/workspace/source/tidb/pkg/server/conn_stmt.go:225\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\n\t/workspace/source/tidb/pkg/server/conn.go:1386\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\n\t/workspace/source/tidb/pkg/server/conn.go:1125\ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn\n\t/workspace/source/tidb/pkg/server/server.go:739"]

### 4. What is your TiDB version? (Required)
tidb git_hash: `e21109913d02ac37184fd54ef5c748664ad89284`

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #54383, ref #53246

Problem Summary:

|    | session 1                   | session 2                                       | session 3                    |
|----|-----------------------------|-------------------------------------------------|------------------------------|
| t1 | create table t (a int);  OK |                                                 |                              |
| t2 |                             | alter table t modify column a tinyint; -- job 1 |                              |
| t3 | admin pause ddl jobs 1;  OK | Paused                                          |                              |
| t4 |                             | Paused                                          | alter table t add column c int; |
|    |                             |                                                 | // Should be blocked!        |

As the table shown above, we run `add column` when the previous job `modify column` is not finished. This is unexpected because they reference the same table.

### What changed and how does it work?

This PR moves the unfinished jobs to pending jobs after `delivery2Worker()` complete, in order to prevent `getJob()` obtaining new jobs that affect the same table.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

File: pkg/ddl/job_table.go [hunk 1]
```diff
@@ -526,10 +523,15 @@ func (s *jobScheduler) delivery2Worker(wk *worker, pool *workerPool, job *model.
...
-	s.wg.RunWithLog(func() {
+	s.wg.Run(func() {
 		defer func() {
+			r := recover()
+			if r != nil {
+				logutil.DDLLogger().Error("panic in delivery2Worker", zap.Any("recover", r), zap.Stack("stack"))
+			}
 			failpoint.InjectCall("afterDelivery2Worker", job)
-			s.runningJobs.removeRunning(jobID, involvedSchemaInfos)
+			moveRunningJobsToPending := r != nil || (job != nil && job.IsPaused())
```
Comment (lance6716) [inline pkg/ddl/job_table.go:533]: how about when `delivery2Worker` exits, if the job is not in final states, we move it to pending.

File: pkg/ddl/ddl_running_jobs.go [hunk 2]
```diff
@@ -233,11 +233,23 @@ func (j *runningJobs) addRunning(jobID int64, involves []model.InvolvingSchemaIn
 	}
 }
 
+func (j *runningJobs) removeRunningOrPending(jobID int64, involves []model.InvolvingSchemaInfo, moveToPending bool) {
```
Comment (lance6716) [inline pkg/ddl/ddl_running_jobs.go:236]: Maybe `FinishOrPendJob`

File: pkg/ddl/job_table.go (hunk 1 above)
Comment (tangenta) [reply pkg/ddl/job_table.go]: https://github.com/pingcap/tidb/pull/54419/commits/7820b1f9906a583c40a8f2300158cc687e021d52

File: pkg/ddl/ddl_running_jobs.go (hunk 2 above)
Comment (tangenta) [reply pkg/ddl/ddl_running_jobs.go]: https://github.com/pingcap/tidb/pull/54419/commits/7820b1f9906a583c40a8f2300158cc687e021d52

**Review by D3Hunter — APPROVED** [review]

File: pkg/ddl/job_table.go (hunk 1 above)
Comment (D3Hunter) [reply pkg/ddl/job_table.go]: if not panic/owner change, pause is the only state if we exit here actually, see `job.InFinalState()` branch

Comment (lance6716) [reply pkg/ddl/job_table.go]: just in case we will have more states in future (for example, somehow we revert to the old way to handle job, to let this function only forward one schema state). I think checking "not finished" is more correct.

Comment (D3Hunter) [reply pkg/ddl/job_table.go]: lgtm

> more correct

you mean 'more robust'?

Comment (lance6716) [reply pkg/ddl/job_table.go]: yes, more robust.
