### PR TITLE
ddl: the column flag is changed after modifying column name

### LINKED ISSUE #23872: ddl: the column flag is changed after modifying column name
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t1(id smallint,id1 int, primary key (id));
ALTER TABLE t1 CHANGE id id_new INT ;
```

### 2. What did you expect to see? (Required)
The column flags of column `id_new`  should be the same as the original column `id`.

### 3. What did you see instead (Required)
The `NoDefaultValueFlag` flag is added to the column `id_new`.

### 4. What is your TiDB version? (Required)
master branch
7b4817da9d28d82b52cf7f92ed2ae3b4da3f4fd9

### PR DESCRIPTION
**Pull request by Howie59**
### What problem does this PR solve?

Issue Number: close #23872 
- mysql add the flag when create table, tidb lack it

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

File: ddl/db_test.go [hunk 1]
```diff
@@ -6662,3 +6662,20 @@ func (s *testSerialSuite) TestTruncateAllPartitions(c *C) {
 	tk1.MustExec("alter table partition_table truncate partition all;")
 	tk1.MustQuery("select count(*) from partition_table;").Check(testkit.Rows("0"))
 }
+
+func (s *testSerialSuite) TestIssue23872(c *C) {
```
Comment (xiongjiwei) [inline ddl/db_test.go:6666]: can you please add a test like `create table t(a int default 1, primary key(a));`

File: ddl/db_test.go [hunk 2]
```diff
@@ -6662,3 +6662,20 @@ func (s *testSerialSuite) TestTruncateAllPartitions(c *C) {
...
+
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test;")
+	tk.MustExec("drop table if exists test_create_table;")
+	defer func() {
+		tk.MustExec("drop table if exists test_create_table;")
+	}()
```
Comment (xiongjiwei) [inline ddl/db_test.go:6673]:
```suggestion
defer tk.MustExec("drop table if exists test_create_table;")
```

File: ddl/db_test.go [hunk 3]
```diff
@@ -6662,3 +6662,24 @@ func (s *testSerialSuite) TestTruncateAllPartitions(c *C) {
...
+	cols := rs.Fields()
+	expectFlag := uint16(mysql.NotNullFlag | mysql.PriKeyFlag | mysql.NoDefaultValueFlag)
+	c.Assert(cols[0].Column.Flag, Equals, uint(expectFlag))
+	_, err = tk.Exec("create table t(a int default 1, primary key(a));")
+	c.Assert(err, IsNil)
+	defer tk.MustExec("drop table if exists t;")
+	rs1, err := tk.Exec("select * from t;")
+	c.Assert(err, IsNil)
+	cols1 := rs1.Fields()
+	c.Assert(cols1[0].Column.Flag, Equals, uint(expectFlag))
```
Comment (xiongjiwei) [inline ddl/db_test.go:6684]: I test it in MySQL, this should **NOT** contain `NoDefaultValueFlag`. PTAL

File: ddl/db_test.go [hunk 4]
```diff
@@ -6663,6 +6663,28 @@ func (s *testSerialSuite) TestTruncateAllPartitions(c *C) {
 	tk1.MustQuery("select count(*) from partition_table;").Check(testkit.Rows("0"))
 }
 
+func (s *testSerialSuite) TestIssue23872(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test;")
+	tk.MustExec("drop table if exists test_create_table;")
+	defer tk.MustExec("drop table if exists test_create_table;")
+	_, err := tk.Exec("create table test_create_table(id smallint,id1 int, primary key (id));")
```
Comment (xiongjiwei) [inline ddl/db_test.go:6671]: why not `MustExec`

**Review by xiongjiwei — COMMENTED** [review]
Rest lgtm

**Review by xiongjiwei — APPROVED** [review]
/lgtm
