### PR TITLE
lightning, importer: improve value conversion cast error message

### LINKED ISSUE #66916: lightning/import-into: Improve value conversion error message for cast failures
### 1. Minimal reproduce step (Required)
1. Prepare a table, e.g. `CREATE TABLE t(c1 TINYINT);` (or `CREATE TABLE t(c1 ENUM('a','b'));`).
2. Import data via `tidb-lightning` / `IMPORT INTO` with an invalid value (overflow / invalid enum).
   - Example CSV row: `c1` = `10000000` for `TINYINT`, or `c1` = `c` for `ENUM('a','b')`.

### 2. What did you expect to see? (Required)
A stable, user-friendly error message that includes column name, expected type, bad value, and the cast/type conversion error reason (while allowing redaction of the bad value when `tidb_redact_log` is enabled).

Example:
`Value conversion failed for column 'c1'. Expected type: tinyint(4), received value: 10000000. Reason: <cast error>.`

### 3. What did you see instead (Required)
The current error is either:
- a wrapped cast error with an unstable format like `failed to cast value as ... for column ... (#...)`, or
- a raw cast error without column/value context in some `IMPORT INTO` paths.

### 4. What is your TiDB version? (Required)
master (commit 5766c79bbf)

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #66916

Problem Summary:
- Lightning / IMPORT INTO cast/type conversion errors are hard to troubleshoot because the returned error message is unstable and may miss column/type/value context.

### What changed and how does it work?
- Add a normalized error `ErrCastValue` with a stable, user-friendly message.
- When a value conversion fails, return `ErrCastValue` including column, expected type, bad value (redactable), and the original cast error message as reason.
- Route `IMPORT INTO` early cast failures through the same conversion-failure path.
- Add unit tests.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Improve Lightning / IMPORT INTO value conversion error message to include column, expected type, bad value, and the cast error reason.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved import cast-failure reporting: errors now include column, expected type, received value (stable formatting), and a clear reason, with proper redaction support.
* **Tests**
  * Added tests validating cast-failure messages (overflow, invalid enum), value-format representation, and error redaction behavior.
* **Chores**
  * Increased test sharding/parallelism for related test suites.

### CODE REVIEW

File: pkg/lightning/backend/kv/base.go [hunk 1]
```diff
@@ -312,6 +312,19 @@ func (e *BaseKVEncoder) EvalGeneratedColumns(record []types.Datum,
...
+	}
+	s, err := types.DatumsToStringSmart([]types.Datum{d}, true)
+	if err != nil {
+		return "<unprintable>"
+	}
+	return s
+}
+
 // LogKVConvertFailed logs the error when converting a row to KV pair failed.
 func (e *BaseKVEncoder) LogKVConvertFailed(row []types.Datum, j int, colInfo *model.ColumnInfo, err error) error {
```
Comment (lance6716) [inline pkg/lightning/backend/kv/base.go:329]: (Seems line 337 forget to redact)

File: pkg/lightning/backend/kv/base.go [hunk 2]
```diff
@@ -338,10 +351,14 @@ func (e *BaseKVEncoder) LogKVConvertFailed(row []types.Datum, j int, colInfo *mo
...
-		"failed to cast value as %s for column `%s` (#%d)", &colInfo.FieldType, colInfo.Name.O, j+1,
-	)
+
+	if err == nil {
+		return nil
+	}
+
+	badValue := datumToValueStringForCastError(original)
+	reason := err.Error()
+	return common.ErrCastValue.GenWithStackByArgs(colInfo.Name.O, &colInfo.FieldType, badValue, reason)
```
[the remark this answers is not in the document]
Comment (GMHDBJD) [reply pkg/lightning/backend/kv/base.go:361]: Addressed in 74848199ca.

- `ErrCastValue` is now only created at confirmed `CastColumnValue` failure sites.
- Generic `ProcessColDatum` failures now keep a generic conversion wrapper instead of being reclassified as cast errors.
- The cast `reason` is redacted with the active redact mode before formatting `ErrCastValue`.
- Added regression coverage for a real overflow under redact mode and for a non-cast importer failure.

File: pkg/lightning/backend/kv/base.go (hunk 1 above)
Comment (GMHDBJD) [reply pkg/lightning/backend/kv/base.go:329]: `RowArrayMarshaller` already redacts row values before logging via `redact.Value(str)` in `MarshalLogArray`.

File: pkg/lightning/common/errors.go [hunk 3]
```diff
@@ -78,16 +78,21 @@ var (
...
+	ErrInvalidSchemaStmt = errors.Normalize("invalid schema statement: '%s'", errors.RFCCodeText("Lightning:Restore:ErrInvalidSchemaStmt"))
+	ErrCreateSchema      = errors.Normalize("create schema failed, table: %s, stmt: %s", errors.RFCCodeText("Lightning:Restore:ErrCreateSchema"))
+	ErrUnknownColumns    = errors.Normalize("unknown columns in header (%s) for table %s", errors.RFCCodeText("Lightning:Restore:ErrUnknownColumns"))
+	ErrChecksumMismatch  = errors.Normalize("checksum mismatched remote vs local => (checksum: %d vs %d) (total_kvs: %d vs %d) (total_bytes:%d vs %d)", errors.RFCCodeText("Lighting:Restore:ErrChecksumMismatch"))
+	ErrRestoreTable      = errors.Normalize("restore table %s failed", errors.RFCCodeText("Lightning:Restore:ErrRestoreTable"))
+	ErrEncodeKV          = errors.Normalize("encode kv error in file %s at offset %d", errors.RFCCodeText("Lightning:Restore:ErrEncodeKV"))
+	ErrCastValue         = errors.Normalize(
+		"Value conversion failed for column '%s'. Expected type: %s, received value: %s. Reason: %s.",
+		errors.RFCCodeText("Lightning:Restore:ErrCastValue"),
```
Comment (D3Hunter) [inline pkg/lightning/common/errors.go]:
```suggestion
		errors.RFCCodeText("Import:ErrCastValue"),
```
since it's shared, let's call them `Import` for new errors

File: pkg/lightning/backend/kv/base.go [hunk 4]
```diff
@@ -312,6 +318,38 @@ func (e *BaseKVEncoder) EvalGeneratedColumns(record []types.Datum,
...
+	return s
+}
+
+func redactCastErrorReason(reason string) string {
+	redactMode := errors.RedactLogEnabled.Load()
+	if redactMode == "" {
+		redactMode = errors.RedactLogDisable
+	}
+	return redact.String(redactMode, reason)
+}
```
Comment (D3Hunter) [inline pkg/lightning/backend/kv/base.go]: dup with `redact.Value`

File: pkg/lightning/backend/kv/base.go [hunk 5]
```diff
@@ -312,6 +318,38 @@ func (e *BaseKVEncoder) EvalGeneratedColumns(record []types.Datum,
...
+
+// WrapCastValueError normalizes a cast failure with the column/type/value context.
+func (e *BaseKVEncoder) WrapCastValueError(colInfo *model.ColumnInfo, original types.Datum, err error) error {
+	if err == nil {
+		return nil
+	}
+
+	badValue := datumToValueStringForCastError(original)
+	reason := redactCastErrorReason(err.Error())
```
Comment (D3Hunter) [inline pkg/lightning/backend/kv/base.go]: why redact the reason?

File: pkg/lightning/common/errors_test.go [hunk 6]
```diff
@@ -92,3 +92,20 @@ func TestNormalizeOrWrapErr(t *testing.T) {
 	require.Error(t, err)
 	require.True(t, berrors.Is(err, ErrInvalidArgument))
 }
+
+func TestErrCastValueRedact(t *testing.T) {
```
Comment (D3Hunter) [inline pkg/lightning/common/errors_test.go:102]: please add test for `WrapCastValueError` to make sure the reason not redacted

File: pkg/lightning/backend/kv/base.go (hunk 5 above)
Comment (GMHDBJD) [reply pkg/lightning/backend/kv/base.go]: https://github.com/pingcap/tidb/pull/66917#discussion_r2918027067

Comment (GMHDBJD) [reply pkg/lightning/backend/kv/base.go]: I will revert [7484819](https://github.com/pingcap/tidb/pull/66917/commits/74848199cae095e35e936ee45f97397000e08e73) to not redact the reason

Comment (D3Hunter) [reply pkg/lightning/backend/kv/base.go]: i think the `err.Error()` which is from tidb already handle redact, such as
https://github.com/pingcap/errors/blob/9fe26b1b0b1f428bf8d7bbf4c81d006c081b74fe/normalize.go#L219-L224

File: pkg/lightning/backend/kv/base.go [hunk 7]
```diff
@@ -338,10 +351,14 @@ func (e *BaseKVEncoder) LogKVConvertFailed(row []types.Datum, j int, colInfo *mo
...
-	return errors.Annotatef(
-		err,
-		"failed to cast value as %s for column `%s` (#%d)", &colInfo.FieldType, colInfo.Name.O, j+1,
-	)
+
+	if err == nil {
+		return nil
+	}
+
+	badValue := datumToValueStringForCastError(original)
```
[the remark this answers is not in the document]
Comment (GMHDBJD) [reply pkg/lightning/backend/kv/base.go:359]: No change is needed here because the badValue passed to ErrCastValue is a newly rendered and truncated string from DatumsToStringSmart, not a zero-copy alias of the original parser buffer.
