### PR TITLE
planner: fix the issue that the optimizer caches wrong TableDual plans under binary protocol

### LINKED ISSUE #34678: time column in binary protocol
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepared-plan-cache.enabled = true
```
package main

import (
	"context"
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

var (
	dsn ="root:@tcp(172.16.4.181:17000)/test"
)

func mustExec(c *sql.Conn, query string) {
	_, err := c.ExecContext(context.Background(), query)
	if err != nil {
		panic(err)
	}
}

func main() {
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	c, err := db.Conn(context.Background())
	if err != nil {
		panic(err)
	}
	defer c.Close()

	mustExec(c, "drop table if exists IDT_MULTI15917STROBJSTROBJ")
	mustExec(c, "CREATE TABLE IDT_MULTI15917STROBJSTROBJ (COL2 smallint(41) DEFAULT NULL, COL3 time(5) DEFAULT NULL, KEY U_M_COL5 (COL3,COL2)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;")
	mustExec(c, `insert into IDT_MULTI15917STROBJSTROBJ values(-8761, "-619:40:20.00000");`)
	
	stmt, err := db.Prepare("select col2 from IDT_MULTI15917STROBJSTROBJ where col2 not between ? and ? and col3 = ?;")
	if err != nil {
		panic(err)
	}

	ss := [][]interface{}{
		[]interface{}{1, 1, "693:33:29.655435"},
		[]interface{}{-32564, -32564, "-619:40:20.00000"},
	}
	for _, v := range ss {
		rows, err := stmt.Query(v...)
		if err != nil {
			panic(err)
		}

		count := 0
		for rows.Next() {
			var str1 string

			rows.Scan(&str1)
			//fmt.Printf("%s\n", str1)
			count++
		}
		rows.Close()
		fmt.Printf("%v\n", count)
	}
	
	c.ExecContext(context.Background(), "prepare stmt from 'select col2 from IDT_MULTI15917STROBJSTROBJ where col2 not between ? and ? and col3 = ?;'")
	c.ExecContext(context.Background(), "set @a=-32564, @b=-32564, @c='-619:40:20.00000'")

	rows, err := c.QueryContext(context.Background(), "execute stmt using @a, @b, @c")
	count := 0
	for rows.Next() {
		var str3 []byte
		rows.Scan(&str3)
		count++
	}
	rows.Close()
	fmt.Printf("%v\n", count)
}
```
### 2. What did you expect to see? (Required)
```
0
1
1
```
### 3. What did you see instead (Required)
```
0
0
1
```
### 4. What is your TiDB version? (Required)

master

### LINKED ISSUE #34690: enum column in binary protocol
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepared-plan-cache.enabled = true

```
package main

import (
	"context"
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

var (
	dsn ="root:@tcp(172.16.4.181:17000)/test"
)

func mustExec(c *sql.Conn, query string) {
	_, err := c.ExecContext(context.Background(), query)
	if err != nil {
		panic(err)
	}
}

func main() {
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	c, err := db.Conn(context.Background())
	if err != nil {
		panic(err)
	}
	defer c.Close()

	mustExec(c, "drop table if exists IDT_MULTI15842STROBJSTROBJ;")
	mustExec(c, "CREATE TABLE IDT_MULTI15842STROBJSTROBJ (COL1 enum('aa', 'bb') DEFAULT NULL,  COL2 smallint(41) DEFAULT NULL, COL3 datetime DEFAULT NULL, KEY U_M_COL4 (COL1,COL2), KEY U_M_COL5 (COL3,COL2)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;")
	mustExec(c, `insert into IDT_MULTI15842STROBJSTROBJ values("aa", 10107, "0871-07-11 22:22:40");`)
	stmt, err := db.Prepare("select col2 from IDT_MULTI15842STROBJSTROBJ where col2 between ? and ? and col1 in (?, ?, ?)")
	if err != nil {
		panic(err)
	}

	ss := [][]interface{}{
		[]interface{}{-286425994142, 539889691716, "none", "none", "none"},
		[]interface{}{-879193018085, 32676, "aa", "aa", "aa"},
	}
	for _, v := range ss {
		rows, err := stmt.Query(v...)
		if err != nil {
			panic(err)
		}

		count := 0
		for rows.Next() {
			var str1 string

			rows.Scan(&str1)
			//fmt.Printf("%s\n", str1)
			count++
		}
		rows.Close()
		fmt.Printf("%v\n", count)
	}
	
	c.ExecContext(context.Background(), "prepare stmt from 'select col2 from IDT_MULTI15842STROBJSTROBJ where col2 between ? and ? and col1 in (?, ?, ?)'")
	c.ExecContext(context.Background(), "set @a=-879193018085, @b=32676, @c='aa', @d='aa', @e='aa'")


	rows, err := c.QueryContext(context.Background(), "execute stmt using @a, @b, @c, @c, @d")
	count := 0
	for rows.Next() {
		var str3 []byte
		rows.Scan(&str3)
		count++
	}
	rows.Close()
	fmt.Printf("%v\n", count)
}
```
### 2. What did you expect to see? (Required)
```
0
1
1
```

### 3. What did you see instead (Required)
```
0
0
1
```
### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #34678, close #34690

Problem Summary: fix the issue that the optimizer caches wrong TableDual plans under binary protocol

### What is changed and how it works?

We didn't consider binary protocol when checking whether variable types are changed in `getPhyscalPlan` before.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by qw4990** [comment]
This PR can be covered by our [rand-gen tests](https://github.com/pingcap/qa/tree/master/comp/yy/prepare-execute) and it's hard to add binary test cases as UTs, so I didn't add any UT for this PR. I also test this PR locally and it can pass #34678 and #34690.

File: planner/core/common_plans.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ type Execute struct {
 
 	Name          string
 	UsingVars     []expression.Expression
-	PrepareParams []types.Datum
+	PrepareParams []types.Datum // parsed parameter values, only used for binary protocol
```
Comment (winoros) [inline planner/core/common_plans.go:194]: What about commenting on these two lines together?
The `UsingVars` is for the txt protocol and the `PreparedParams` is for the binary protocol.

Comment (qw4990) [reply planner/core/common_plans.go]: Updated, PTAL.

**Review by Reminiscent — APPROVED** [review]

File: planner/core/common_plans.go [hunk 2]
```diff
@@ -189,10 +189,10 @@ type Prepare struct {
 type Execute struct {
 	baseSchemaProducer
 
-	Name          string
-	UsingVars     []expression.Expression
-	PrepareParams []types.Datum
-	ExecID        uint32
+	Name         string
+	TxtProtoVars []expression.Expression // parsed variables under text protocol
+	BinProtoVars []types.Datum           // parsed variables under binary protocol
```
Comment (qw4990) [inline planner/core/common_plans.go:194]: Just rename `UsingVars -> TxtProtoVars`, `PrepareParams -> BinProtoVars`.

File: planner/core/common_plans.go [hunk 3]
```diff
@@ -456,15 +456,28 @@ func (e *Execute) getPhysicalPlan(ctx context.Context, sctx sessionctx.Context,
...
+
+	var varsNum int
+	var binVarTypes []byte
+	var txtVarTypes []*types.FieldType
+	isBinProtocol := len(e.BinProtoVars) > 0
+	if isBinProtocol { // binary protocol
+		varsNum = len(e.BinProtoVars)
+		for _, param := range e.BinProtoVars {
+			binVarTypes = append(binVarTypes, param.Kind())
+		}
```
Comment (qw4990) [inline planner/core/common_plans.go:468]: We cannot parse variables correctly under binary protocol before.

**Review by winoros — APPROVED** [review]
