### PR TITLE
planner: fix only full group constant collector can not feel column = unary-op(constant).

### LINKED ISSUE #62617: ONLY_FULL_GROUP_BY check fails due to negative value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t(a int);
explain select a,min(a) from t where a=-1;

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)
`ERROR 8123 (HY000): In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'a'; this is incompatible with sql_mode=only_full_group_by`

### 4. What is your TiDB version? (Required)

v7.5.5

### PR DESCRIPTION
**Pull request by AilinKid**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/62617

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by King-Dylan — APPROVED** [review]

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -3236,13 +3236,27 @@ func extractSingeValueColNamesFromWhere(p base.LogicalPlan, where ast.ExprNode,
...
+				if _, ok := u.V.(ast.ValueExpr); ok {
+					addGbyOrSingleValueColName(p, colExpr.Name, gbyOrSingleValueColNames)
+				}
+			}
 		} else if colExpr, ok := binOpExpr.R.(*ast.ColumnNameExpr); ok {
+			// value = a
 			if _, ok := binOpExpr.L.(ast.ValueExpr); ok {
 				addGbyOrSingleValueColName(p, colExpr.Name, gbyOrSingleValueColNames)
 			}
+			// - value = a
```
Comment (guo-shaoge) [inline pkg/planner/core/logical_plan_builder.go:3254]: also add test case for this branch?

File: pkg/planner/core/logical_builder_test.go [hunk 2]
```diff
@@ -0,0 +1,30 @@
+// Copyright 2025 PingCAP, Inc.
```
Comment (guo-shaoge) [inline pkg/planner/core/logical_builder_test.go]: logical_builder_test.go -> logical_plan_builder_test.go?

Comment (hawkingrei) [reply pkg/planner/core/logical_builder_test.go]: move it into `pkg/planner/core/casetest/plan_test.go` or `pkg/planner/core/issuetest/planner_issue_test.go`

File: pkg/planner/core/logical_plan_builder.go (hunk 1 above)
Comment (AilinKid) [reply pkg/planner/core/logical_plan_builder.go:3254]: good sure

**Review by hawkingrei — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]
