### PR TITLE
executor: fix issue that some query execution stats was omitted when execution was interrupted

### LINKED ISSUE #51660: some query execution stats was omitted when execution was interrupted
### 1. Minimal reproduce step (Required)

Execute query with max_execution_time, and make the query execution was interrupted, cause by maximum statement execution time exceeded.

Then the query slow info is following, the executor rpc stats was omitted!!!

image

### 4. What is your TiDB version? (Required)

master: f2ae6987cafdc46c45ea8f1a03b4e4618b5943ef

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve?

Issue Number: close #51660

Problem Summary: fix issue that some query execution stats was omitted when execution was interrupted.

### What changed and how does it work?

This PR:

Execute query with max_execution_time, and make the query execution was interrupted, cause by maximum statement execution time exceeded. Then the slow query info still have executor stats.

image

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by you06 — APPROVED** [review]

**Review by lcwangchao — APPROVED** [review]

File: pkg/distsql/select_result.go [hunk 1]
```diff
@@ -603,6 +603,13 @@ func (r *selectResult) Close() error {
 	if respSize > 0 {
 		r.memConsume(-respSize)
 	}
+	if unconsumed, ok := r.resp.(copr.HasUnconsumedCopRuntimeStats); ok && unconsumed != nil {
+		unconsumedCopStats := unconsumed.CollectUnconsumedCopRuntimeStats()
```
Comment (Benjamin2037) [inline pkg/distsql/select_result.go:607]: Since here handle unconsumed cop stats, could we directly release all the stats instead of release every one stats by loop?

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
I think this PR introduced a panic:

```log
[2024/03/19 09:52:29.783 +08:00] [ERROR] [analyze.go:520] ["analyze worker panicked"] [recover="runtime error: invalid memory address or nil pointer dereference"] [stack="github.com/pingcap/tidb/pkg/executor.(*AnalyzeExec).analyzeWorker.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/analyze.go:520\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:861\ngithub.com/pingcap/tidb/pkg/distsql.(*selectResult).Close\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/distsql/select_result.go:610\ngithub.com/pingcap/tidb/pkg/executor.closeAll\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/distsql.go:138\ngithub.com/pingcap/tidb/pkg/executor.(*AnalyzeIndexExec).buildStats.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/analyze_idx.go:102\ngithub.com/pingcap/tidb/pkg/executor.(*AnalyzeIndexExec).buildStats\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/analyze_idx.go:109\ngithub.com/pingcap/tidb/pkg/executor.analyzeIndexPushdown\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/analyze_idx.go:59\ngithub.com/pingcap/tidb/pkg/executor.(*AnalyzeExec).analyzeWorker\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/analyze.go:547\ngithub.com/pingcap/tidb/pkg/executor.(*AnalyzeExec).Next.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/analyze.go:119\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupPool).Run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:213\ngithub.com/tiancaiamao/gp.worker\n\t/go/pkg/mod/github.com/tiancaiamao/gp@v0.0.0-20221230034425-4025bc8a4d4a/gp.go:37"]
```
