### PR TITLE
ranger: avoid overflow and truncate error when building range.

### LINKED ISSUE #5557: Unexpected behavior in ranger.
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(a int, index idx(a));
select * from t use index(idx) where a > 9223372036854775807;

drop table if exists t;
create table t(a float(3, 2), index idx(a));
explain select * from t use index(idx) where a > '999999999.99999999999';
```

2. What did you expect to see?

No error should occurs.

3. What did you see instead?

Error occurs when building range.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

### PR DESCRIPTION
**Pull request by winoros**
To temporarily fix #5557 .
PTAL @hanfei1991 @XuHuaiyu

### CODE REVIEW

File: util/ranger/ranger.go [hunk 1]
```diff
@@ -353,3 +359,19 @@ func fixRangeDatum(v *types.Datum, length int) {
 		v.SetBytes(v.GetBytes()[:length])
 	}
 }
+
+func newFieldType(tp *types.FieldType) *types.FieldType {
```
Comment (XuHuaiyu) [inline util/ranger/ranger.go]: add a comment for this.

**Comment by winoros** [comment]
@XuHuaiyu PTAL
