### PR TITLE
lightning: support null value for auto-incr column on local backend

### LINKED ISSUE #34208: Lightning import fails if auto_increment / auto_random column is NULL and backend is local/importer
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
- create a table with auto increment / auto random bigint as primary key

CREATE TABLE `t_auto_incr` (
    `id` bigint PRIMARY KEY AUTO_INCREMENT,
    `c` char(40) NOT NULL DEFAULT '');

CREATE TABLE `t_auto_random` (
    `id` bigint PRIMARY KEY AUTO_RANDOM(3),
    `c` char(40) NOT NULL DEFAULT '');

- create sql file for tidb-lightning import, which contains 2 rows, and primary key  column is NULL

[root@centos76_vm auto_increment]# more test.t_auto_incr.1.sql
INSERT INTO `t_auto_incr` VALUES
(NULL, 'HhdyJnKnnFkYMltimhLCZnzTyvHYgZKmqcsxidPV');
INSERT INTO `t_auto_incr` VALUES
(NULL, 'TaCiCHTXSlpWtqdjmExJLsvWdWZvpWqFSeyQNTky');

- Use tidb-linghtning to import the rows in the SQL file  to TiDB using local or importer backend

2. What did you expect to see?
- Import should be successfully, and id column is auto generated.

3. What did you see instead?
- Lightning import fails with below errors, only one row inserted into TiDB whose id is 0.

Note: Import is OK if tidb backend is used for lightning import.

[root@centos76_vm auto_increment]# tiup tidb-lightning:v5.0.2 -config lighting.toml
Starting component `tidb-lightning`: /root/.tiup/components/tidb-lightning/v5.0.2/tidb-lightning -config lighting.toml
Verbose debug logs will be written to tidb-lightning.log

Error: checksum mismatched remote vs local => (checksum: 8717407354590535884 vs 10040980041112552038) (total_kvs: 1 vs 2) (total_bytes:63 vs 126)
tidb lightning encountered error:  checksum mismatched remote vs local => (checksum: 8717407354590535884 vs 10040980041112552038) (total_kvs: 1 vs 2) (total_bytes:63 vs 126)
Error: run `/root/.tiup/components/tidb-lightning/v5.0.2/tidb-lightning` (wd:/root/.tiup/data/SawwSYl) failed: exit status 1

MySQL [test]> select * from t_auto_incr;
+----+------------------------------------------+
| id | c                                        |
+----+------------------------------------------+
|  0 | TaCiCHTXSlpWtqdjmExJLsvWdWZvpWqFSeyQNTky |
+----+------------------------------------------+
1 row in set (0.01 sec)

4. What version of BR and TiDB/TiKV/PD are you using?

br: v5.0.2 and v5.1.0

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #34208

Problem Summary:

### What is changed and how it works?

When encoding the SQL into a TiDB KV for importing, if the value is NULL in a 'not-null' column, go on further processing on special column types rather than convert those NULL values into zero values directly 
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/kv/sql2kv.go [hunk 1]
```diff
@@ -361,31 +361,47 @@ func (kvcodec *tableKVEncoder) Encode(
 		j := columnPermutation[i]
 		isAutoIncCol := mysql.HasAutoIncrementFlag(col.GetFlag())
 		isPk := mysql.HasPriKeyFlag(col.GetFlag())
-		switch {
-		case j >= 0 && j < len(row):
-			value, err = table.CastValue(kvcodec.se, row[j], col.ToInfo(), false, false)
-			if err == nil {
-				err = col.HandleBadNull(&value, kvcodec.se.vars.StmtCtx)
+		value, err = func() (types.Datum, error) {
```
Comment (gozssky) [inline br/pkg/lightning/backend/kv/sql2kv.go:364]: Can we extract this function to the outside? For better readability and testing.

File: br/tests/lightning_issue_34208/run.sh [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+check_contains "2:null_pk_02"
+check_contains "3:null_pk_03"
+check_contains "4:normal_pk_04"
+run_sql "SELECT COUNT(*) AS row_count FROM issue34208.t_auto_incr;"
+check_contains "row_count: 4"
+
+run_sql "SELECT CONCAT_WS(':', id, c) AS row_data FROM issue34208.t_auto_random;"
+check_contains "1:normal_pk_01"
+check_contains "1152921504606846978:null_pk_02"
+check_contains "1152921504606846979:null_pk_03"
```
Comment (gozssky) [inline br/tests/lightning_issue_34208/run.sh:33]: I think we shouldn't assume the auto random id is stable.

File: br/tests/lightning_issue_34208/run.sh [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+check_contains "2:null_pk_02"
+check_contains "3:null_pk_03"
+check_contains "4:normal_pk_04"
+run_sql "SELECT COUNT(*) AS row_count FROM issue34208.t_auto_incr;"
+check_contains "row_count: 4"
+
+run_sql "SELECT CONCAT_WS(':', id, c) AS row_data FROM issue34208.t_auto_random;"
+check_contains "1:normal_pk_01"
+check_contains ":null_pk_02"
+check_contains ":null_pk_03"
```
Comment (gozssky) [inline br/tests/lightning_issue_34208/run.sh:33]: Maybe need to check if the id is not zero.

**Review by gozssky — COMMENTED** [review]
rest LGTM

File: br/pkg/lightning/backend/kv/sql2kv.go [hunk 4]
```diff
@@ -440,12 +440,20 @@ func isPKCol(colInfo *model.ColumnInfo) bool {
...
+func (kvcodec *tableKVEncoder) getActualDatum(rowID int64, colIndex int, inputDatum *types.Datum) (types.Datum, error) {
 	var (
 		value types.Datum
 		err   error
 	)
+
 	tblMeta := kvcodec.tbl.Meta()
+	cols := kvcodec.tbl.Cols()
+
+	if colIndex < 0 || colIndex >= len(cols) {
```
Comment (gozssky) [inline br/pkg/lightning/backend/kv/sql2kv.go:452]: Why change `cols` to `colIndex`? It introduces redundant checks.

Comment (dsdashun) [reply br/pkg/lightning/backend/kv/sql2kv.go:452]: Because the kvcodec contains the table and the columns itself,  passing an index can prevent the caller using an arbitrary column not belonging to the table as an argument.

File: br/tests/lightning_issue_34208/run.sh [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+check_contains "row_data: 4:normal_pk_04"
+run_sql "SELECT COUNT(*) AS row_count FROM issue34208.t_auto_incr;"
+check_contains "row_count: 4"
+
+run_sql "SELECT CONCAT_WS(':', id, c) AS row_data FROM issue34208.t_auto_random;"
+check_contains "row_data: 1:normal_pk_01"
+check_contains ":null_pk_02"
+check_not_contains "row_data: 0:null_pk_02"
+check_contains ":null_pk_03"
+check_not_contains "row_data: 0:null_pk_02"
```
Comment (gozssky) [inline br/tests/lightning_issue_34208/run.sh:35]:
```suggestion
check_not_contains "row_data: 0:null_pk_03"
```

**Review by gozssky — APPROVED** [review]

File: br/tests/lightning_issue_34208/config.toml [hunk 6]
```diff
@@ -0,0 +1,2 @@
+[tikv-importer]
```
Comment (D3Hunter) [inline br/tests/lightning_issue_34208/config.toml:1]: prefer we name the test directory more clearly, it's hard to know what's inside at first glance

File: br/pkg/lightning/backend/kv/sql2kv.go [hunk 7]
```diff
@@ -356,57 +356,35 @@ func (kvcodec *tableKVEncoder) Encode(
...
-		if isAutoIncCol {
+		if isAutoIncCol(col.ToInfo()) {
 			alloc := kvcodec.tbl.Allocators(kvcodec.se).Get(autoid.AutoIncrementType)
 			if err := alloc.Rebase(context.Background(), getAutoRecordID(value, &col.FieldType), false); err != nil {
 				return nil, errors.Trace(err)
 			}
 		}
 	}
 
+	// the table has an extra auto-generated row-ID column
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/kv/sql2kv.go:387]: what's this comment for?

File: br/pkg/lightning/backend/kv/sql2kv.go (hunk 4 above)
Comment (D3Hunter) [reply br/pkg/lightning/backend/kv/sql2kv.go:452]: since it's a internal function, we can remove this check

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

**Comment by D3Hunter** [comment]
current behavior looks odd to me, in data file it's `null` for a `auto_incrment primary key` column, then we generate an id automatically for it. what if it's just an corrupted data file, in that case we should not do it:

also what's current behavior for case below:

table is `create table t(id int primary key auto_increment, v varchar(10));`, but in data file(csv), we have:
```
1,aaa
NULL,bbb
NULL,ccc
2,ddd
```

**Comment by gozssky** [comment]
@D3Hunter TiDB supports insert `NULL` as `auto_incrment` column.
```sql
mysql> create table t(id int primary key auto_increment, v varchar(10));
Query OK, 0 rows affected (0.12 sec)

mysql> insert into t values (1, 'aaa');
Query OK, 1 row affected (0.03 sec)

mysql> insert into t values (NULL, 'bbb');
Query OK, 1 row affected (0.02 sec)

mysql> insert into t values (NULL, 'ccc');
Query OK, 1 row affected (0.01 sec)

mysql> insert into t values (2, 'ddd');
ERROR 1062 (23000): Duplicate entry '2' for key 'PRIMARY'
mysql> select * from t;
+----+------+
| id | v    |
+----+------+
|  1 | aaa  |
|  2 | bbb  |
|  3 | ccc  |
+----+------+
3 rows in set (0.01 sec)
```
For local backend, we need to enable `duplicate-resolution` to detect the primary key conflict.

**Review by D3Hunter — APPROVED** [review]
