### PR TITLE
ddl: limit the minimum region batch size in local sort

### LINKED ISSUE #64566: add index using local sort in DXF should be optimize for small table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

For a small table, we should not split the add index task into too many subtasks. 
These tasks' range overlaps and may cause the "too many SST files" problem.
### 2. What did you expect to see? (Required)
N/A
### 3. What did you see instead (Required)
N/A

### 4. What is your TiDB version? (Required)
master, v8.5

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #64566

Problem Summary:
For local sort, it's better to do at most 3 partial imports. So the subtask count should be limited to 3.

### What changed and how does it work?
Set up a minimum region batch in local sort. 
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
start a cluster with 9db, 15 kv by
```
tiup playground nightly --db=9 --kv=15 --tiflash=0 --db.binpath=/Users/bba/pc/tidb/bin/tidb-server
```

Create a table with 20 regions:
``` sql
create table t(a int);
insert into t values (1), (2), (3), (4), (5);
insert into t select * from t;
...
insert into t select * from t;

split table t between (0) and (20000)  regions 20;
```

result:

```
mysql> alter table t add index idx(a);
Query OK, 0 rows affected (3.025 sec)

admin show ddl jobs;
116 | test    | t                     | add index     | public       |       112 |      114 |     40960 | 2025-11-20 13:37:22.784000 | 2025-11-20 13:37:22.834000 | 2025-11-20 13:37:25.384000 | synced | ingest, DXF, max_node_count=5

select count(*) from mysql.tidb_background_subtask_history;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.006 sec)
```

Then add more data and increase the region count to 200.

``` sql
mysql> insert into t select * from t;
Query OK, 163840 rows affected (0.638 sec)
Records: 163840  Duplicates: 0  Warnings: 0

mysql> split table t between (0) and (220000)  regions 201;
+--------------------+----------------------+
| TOTAL_SPLIT_REGION | SCATTER_FINISH_RATIO |
+--------------------+----------------------+
|                200 |                    1 |
+--------------------+----------------------+
1 row in set (38.645 sec)

mysql> alter table t add index idx2(a);
Query OK, 0 rows affected (12.012 sec)
(new cluster)
mysql> select count(*) from mysql.tidb_background_subtask_history;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.001 sec)

```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
limit the minimum region batch size in local sort
```

### CODE REVIEW

File: pkg/ddl/backfilling_dist_scheduler.go [hunk 1]
```diff
@@ -426,14 +426,20 @@ func CalculateRegionBatch(totalRegionCnt int, nodeCnt int, useLocalDisk bool) in
 		failpoint.Return(val.(int))
 	})
 	var regionBatch int
+	if useLocalDisk {
+		// We want to avoid too may partial imports when using local disk. So we limit the node count to 3 so that
+		// at most 3 partial imports if disk space is enough.
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_dist_scheduler.go]:
```suggestion
		// We want to avoid too may partial imports when using local disk. So we
		// limit the node count to 3 so that at most 3 partial imports if disk
		// space is enough.
```

File: pkg/ddl/backfilling_dist_scheduler.go [hunk 2]
```diff
@@ -426,14 +426,20 @@ func CalculateRegionBatch(totalRegionCnt int, nodeCnt int, useLocalDisk bool) in
...
+		nodeCnt = min(3, nodeCnt)
+	}
 	avgTasksPerInstance := (totalRegionCnt + nodeCnt - 1) / nodeCnt // ceiling
 	if useLocalDisk {
 		regionBatch = avgTasksPerInstance
+		// Special handling for small table, in this case, we want to do it on one node. 100 region data is about 10GiB.
+		regionBatch = min(max(100, regionBatch), totalRegionCnt)
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_dist_scheduler.go]:
```suggestion
		// Special handling for small table, in this case, we want to do it on
		// one node. 100 region data is about 10GiB.
		regionBatch = min(max(100, avgTasksPerInstance), totalRegionCnt)
```
