### PR TITLE
ddl: concurrent safe api for using rule bundles cache

### LINKED ISSUE #21913: DATA RACE:github.com/pingcap/tidb/infoschema.(*infoSchema).RuleBundles() failed
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/61632/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/61632/display/redirect</a>

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #21913

Problem Summary: Introduce a new concurrent-safe(by RWMutex) api for rule cache framework. Adapt all the tests that is using the old API, and code that relies on the internal map rather than using API.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note

### CODE REVIEW

File: executor/infoschema_reader.go [hunk 1]
```diff
@@ -1819,23 +1819,22 @@ func (e *memtableRetriever) setDataForStatementsSummary(ctx sessionctx.Context,
 func (e *memtableRetriever) setDataForPlacementPolicy(ctx sessionctx.Context) error {
 	checker := privilege.GetPrivilegeManager(ctx)
 	is := infoschema.GetInfoSchema(ctx)
-	ruleBundles := is.RuleBundles()
 	var rows [][]types.Datum
-	for _, bundle := range ruleBundles {
+	if err := is.ForEachBundle(func(bundle *placement.Bundle) error {
```
Comment (djshow832) [inline executor/infoschema_reader.go:1823]: The operations inside this iteration may be slow, which blocks other operations. I prefer to clone it within a lock, and then iterate the cloned snapshot.

Comment (xhebox) [reply executor/infoschema_reader.go:1823]: Done

File: infoschema/infoschema.go [hunk 2]
```diff
@@ -56,10 +57,10 @@ type InfoSchema interface {
 	FindTableByPartitionID(partitionID int64) (table.Table, *model.DBInfo, *model.PartitionDefinition)
 	// BundleByName is used to get a rule bundle.
 	BundleByName(name string) (*placement.Bundle, bool)
-	// RuleBundles returns all placement rule bundles.
-	RuleBundles() map[string]*placement.Bundle
-	// MockBundles is only used for TEST.
-	MockBundles(map[string]*placement.Bundle)
+	// SetBundle is only used for TEST
```
Comment (djshow832) [inline infoschema/infoschema.go:60]: Not only test.

File: infoschema/infoschema.go [hunk 3]
```diff
@@ -405,16 +407,32 @@ func GetInfoSchemaBySessionVars(sessVar *variable.SessionVars) InfoSchema {
...
+	for _, bundle := range is.ruleBundleMap {
+		bundles = append(bundles, bundle)
+	}
+	return bundles
+}
+
+func (is *infoSchema) SetBundle(bundle *placement.Bundle) {
+	is.ruleBundleMutex.Lock()
+	defer is.ruleBundleMutex.Unlock()
+	is.ruleBundleMap[bundle.ID] = bundle
```
Comment (djshow832) [inline infoschema/infoschema.go:429]: How do you guarantee that the map is initialized?

Comment (xhebox) [reply infoschema/infoschema.go:429]: I did not promise, I assume, and there is only one initialization from `infoschema/builder.go`. So it should be initialized unless you are not using the infoschema builder to build infoschema

```
infoschema/builder.go:
ruleBundleMap:       map[string]*placement.Bundle{},
```

Comment (djshow832) [reply infoschema/infoschema.go:429]: Please check and initialize it in the interfaces. Do not assume the callers of these interfaces.

Comment (xhebox) [reply infoschema/infoschema.go:429]: OK. But I do think there is a need for a standard rule or common sense among different modules/coders: just make sure everyone will initialize the struct by its new methods. Otherwise, there are redundant checks everywhere.

Comment (djshow832) [reply infoschema/infoschema.go:438]: The thing is, some creation of `infoSchema` doesn't initialize `ruleBundleMap`, such as `MockInfoSchema` and `MockInfoSchemaWithSchemaVer`. It's hard to say the structs created by those functions won't be used to get or set rule bundles in the future.

Comment (xhebox) [reply infoschema/infoschema.go:438]: Then, these methods should use a consistent way to initialize `infoSchema`. IMO, this is just another assumption/common sense: `infoSchema` is not initialized by some unified/standard methods.

But simplicity favors regularity. I would choose to standardize the initialization of `infoSchema`, which will lead to an always non-nil/valid state of `ruleBundleMap`. Possibly, some refactoring on the `infoschema builder` API would work.

I could file an issue and look into this if you think it is a good idea.

**Review by djshow832 — COMMENTED** [review]
LGTM

**Comment by djshow832** [comment]
LGTM

**Comment by djshow832** [comment]
LGTM

**Comment by djshow832** [comment]
LGTM

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
