### PR TITLE
*: fix columns table query unstable

### LINKED ISSUE #51829: select from information_schema.columns contains duplicate records
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

<!-- a step by step guide for reproducing the bug. -->

this bug is found during import 10K tables using lightning, and it get duplicate columns from tidb

```
mysql> SELECT table_name, column_name, column_type, generation_expression, extra FROM information_schema.columns WHERE table_schema = 'coms' ORDER BY table_name, ordinal_position limit 10;
+------------+-------------+---------------+-----------------------+-------+
| table_name | column_name | column_type   | generation_expression | extra |
+------------+-------------+---------------+-----------------------+-------+
| PK_10200   | COL1        | varbinary(10) |                       |       |
| PK_10200   | COL1        | varbinary(10) |                       |       |
| PK_10200   | COL2        | varchar(20)   |                       |       |
| PK_10200   | COL2        | varchar(20)   |                       |       |
| PK_10200   | COL4        | datetime      |                       |       |
| PK_10200   | COL4        | datetime      |                       |       |
| PK_10200   | COL3        | bigint(20)    |                       |       |
| PK_10200   | COL3        | bigint(20)    |                       |       |
| PK_10200   | COL5        | float         |                       |       |
| PK_10200   | COL5        | float         |                       |       |
+------------+-------------+---------------+-----------------------+-------+
10 rows in set (0.15 sec)
```
it works if i filter by `table_name`
```
mysql> SELECT table_name, column_name, column_type, generation_expression, extra FROM information_schema.columns WHERE table_schema = 'coms' and table_name='PK_10200' ORDER BY table_name, ordinal_position;
+------------+-------------+---------------+-----------------------+-------+
| table_name | column_name | column_type   | generation_expression | extra |
+------------+-------------+---------------+-----------------------+-------+
| PK_10200   | COL1        | varbinary(10) |                       |       |
| PK_10200   | COL2        | varchar(20)   |                       |       |
| PK_10200   | COL4        | datetime      |                       |       |
| PK_10200   | COL3        | bigint(20)    |                       |       |
| PK_10200   | COL5        | float         |                       |       |
+------------+-------------+---------------+-----------------------+-------+
```

### 2. What did you expect to see? (Required)
no duplicate
### 3. What did you see instead (Required)
duplicate
### 4. What is your TiDB version? (Required)
```
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.0.0-alpha
Edition: Community
Git Commit Hash: 630651209d7c5163d6f32a90587b17c15dc7be13
Git Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time: 2024-03-14 11:45:40
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: close #51829

Problem Summary:

### What changed and how does it work?
Revert the change for V2
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/executor/infoschema_reader.go [hunk 1]
```diff
@@ -781,11 +782,16 @@ func (e *hugeMemTableRetriever) setDataForColumns(ctx context.Context, sctx sess
...
 	is := sctx.GetInfoSchema().(infoschema.InfoSchema)
-	for ; e.dbsIdx < len(e.dbs); e.dbsIdx++ {
+	for e.dbsIdx < len(e.dbs) {
 		schema := e.dbs[e.dbsIdx]
-		tables := is.SchemaTables(schema)
-		for e.tblIdx < len(tables) {
-			table := tables[e.tblIdx]
+		if len(e.tables) == 0 {
+			e.tables = is.SchemaTables(schema)
+			sort.Slice(e.tables, func(i, j int) bool {
```
Comment (hawkingrei) [inline pkg/executor/infoschema_reader.go:789]: slices.SortFunc will be better. It can avoid unnecessary bounds check elimination.

File: pkg/executor/infoschema_reader.go [hunk 2]
```diff
@@ -807,6 +813,8 @@ func (e *hugeMemTableRetriever) setDataForColumns(ctx context.Context, sctx sess
 			}
 		}
 		e.tblIdx = 0
+		e.dbsIdx++
+		e.tables = e.tables[:0]
```
Comment (hawkingrei) [inline pkg/executor/infoschema_reader.go:817]:
```suggestion
		clear(e.tables)
```

File: pkg/executor/infoschema_reader.go (hunk 1 above)
Comment (ywqzzy) [reply pkg/executor/infoschema_reader.go]: The sort is really slow, I prefer to revert change from https://github.com/pingcap/tidb/pull/51436 for now to avoid regression

**Comment by Benjamin2037** [comment]
Please add test to cover the bug fix scenario.

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Comment by ywqzzy** [comment]
> Please add test to cover the bug fix scenario.

No need to add tests since we just revert the code change. And lightning run the test daily.

**Review by D3Hunter — APPROVED** [review]
