### PR TITLE
planner: fix uninitialized stats for expression index

### LINKED ISSUE #57090: Optimizer cannot correctly display the statistics info for "stored generated indexes" in the operator info
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Create a database and a table:
```sql
set @@global.tidb_enable_auto_analyze = 'OFF';

create database business_db;
USE business_db;
CREATE TABLE `event_log` (
    `id` varchar(255) NOT NULL,
    `created_time` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
    `modified_time` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
    `money_info` json DEFAULT NULL,
    `actors` json DEFAULT NULL,
    `recipient` varchar(255) GENERATED ALWAYS AS (json_extract(`actors`, _utf8mb4'$[*].recipient')) STORED,
    `operator_id` varchar(255) GENERATED ALWAYS AS (json_extract(`actors`, _utf8mb4'$[*].operator_id')) STORED,
    `category` varchar(255) DEFAULT NULL,
    `action` varchar(255) DEFAULT NULL,
    `cancelled_by_id` varchar(255) DEFAULT NULL,
    `cancellation_of_id` varchar(255) DEFAULT NULL,
    `metadata` json DEFAULT NULL,
    `money_details` json DEFAULT NULL,
    PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
    KEY `idx_operator_id` (`operator_id`),
    KEY `idx_created_time` (`created_time`),
    KEY `idx_category` (`category`),
    KEY `idx_action` (`action`),
    KEY `idx_recipient` (`recipient`),
    KEY `idx_cancelled_by_id` (`cancelled_by_id`),
    KEY `idx_cancellation_of_id` (`cancellation_of_id`),
    KEY `idx_metadata_location_id` ((
        cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
2. Load the stats json for the table:

[business_db.event_log.json](https://github.com/user-attachments/files/17613536/business_db.event_log.json)

```sql
LOAD STATS './TCOC-2724/business_db.event_log.json';
```

3. explain analyze the query:

```sql
explain analyze
SELECT SQL_NO_CACHE e.id, e.category, e.created_time, e.money_info
FROM `event_log` e
WHERE e.`category` = "payment"
AND e.`created_time` BETWEEN "2024-09-30 15:00:00.000" AND "2099-01-01 00:00:01.000"
AND (cast(json_unquote(json_extract(e.`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) = "498"
ORDER BY e.`created_time` DESC
LIMIT 70000;
```

### 2. What did you expect to see? (Required)

```sql
+--------------------------------+-------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+
|id                              |estRows|actRows|task     |access object                                                                                                                                  |execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |operator info                                                                                                                                                                                                                                               |memory   |disk   |
+--------------------------------+-------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+
|Projection_8                    |14.84  |0      |root     |                                                                                                                                               |time:3.13ms, loops:1, RU:0.964042, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                              |2.86 KB  |N/A    |
|└─TopN_11                       |14.84  |0      |root     |                                                                                                                                               |time:3.13ms, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |business_db.event_log.created_time:desc, offset:0, count:70000                                                                                                                                                                                              |0 Bytes  |0 Bytes|
|  └─Projection_26               |14.84  |0      |root     |                                                                                                                                               |time:3.1ms, loops:2, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255))|3.48 KB  |N/A    |
|    └─IndexLookUp_25            |14.84  |0      |root     |                                                                                                                                               |time:3.1ms, loops:2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                            |245 Bytes|N/A    |
|      ├─IndexRangeScan_22(Build)|827.01 |0      |cop[tikv]|table:e, index:idx_metadata_location_id(cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin)|time:3.05ms, loops:1, cop_task: {num: 1, max: 509.4µs, proc_keys: 0, tot_proc: 42.1µs, tot_wait: 63.8µs, copr_cache_hit_ratio: 0.00, build_task_duration: 6.46µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:2, total_time:717.3µs}, rpc_errors:{epoch_not_match:1}}, backoff{regionMiss: 2ms}, tikv_task:{time:1ms, loops:1}, scan_detail: {total_keys: 1, get_snapshot_time: 30.8µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 42.1µs, total_wait_time: 63.8µs, total_kv_read_wall_time: 1ms, tikv_wall_time: 208.1µs}|range:["498","498"], keep order:false, stats:partial[idx_metadata_location_id_0:AllLoaded]                                                                                                                                                          |N/A      |N/A    |
|      └─Selection_24(Probe)     |14.84  |0      |cop[tikv]|                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |eq(business_db.event_log.category, "payment"), ge(business_db.event_log.created_time, 2024-09-30 15:00:00.000000), le(business_db.event_log.created_time, 2099-01-01 00:00:01.000000)                                                                       |N/A      |N/A    |
|        └─TableRowIDScan_23     |827.01 |0      |cop[tikv]|table:e                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                                               |N/A      |N/A    |
+--------------------------------+-------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+

```

```diff
-range:["498","498"], keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]
+range:["498","498"], keep order:false, stats:partial[idx_metadata_location_id_0:AllLoaded]
```

### 3. What did you see instead (Required)

```sql
+--------------------------------+-------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+
|id                              |estRows|actRows|task     |access object                                                                                                                                  |execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |operator info                                                                                                                                                                                                                                               |memory   |disk   |
+--------------------------------+-------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+
|Projection_8                    |14.84  |0      |root     |                                                                                                                                               |time:3.13ms, loops:1, RU:0.964042, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                              |2.86 KB  |N/A    |
|└─TopN_11                       |14.84  |0      |root     |                                                                                                                                               |time:3.13ms, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |business_db.event_log.created_time:desc, offset:0, count:70000                                                                                                                                                                                              |0 Bytes  |0 Bytes|
|  └─Projection_26               |14.84  |0      |root     |                                                                                                                                               |time:3.1ms, loops:2, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255))|3.48 KB  |N/A    |
|    └─IndexLookUp_25            |14.84  |0      |root     |                                                                                                                                               |time:3.1ms, loops:2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                            |245 Bytes|N/A    |
|      ├─IndexRangeScan_22(Build)|827.01 |0      |cop[tikv]|table:e, index:idx_metadata_location_id(cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin)|time:3.05ms, loops:1, cop_task: {num: 1, max: 509.4µs, proc_keys: 0, tot_proc: 42.1µs, tot_wait: 63.8µs, copr_cache_hit_ratio: 0.00, build_task_duration: 6.46µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:2, total_time:717.3µs}, rpc_errors:{epoch_not_match:1}}, backoff{regionMiss: 2ms}, tikv_task:{time:1ms, loops:1}, scan_detail: {total_keys: 1, get_snapshot_time: 30.8µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 42.1µs, total_wait_time: 63.8µs, total_kv_read_wall_time: 1ms, tikv_wall_time: 208.1µs}|range:["498","498"], keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                          |N/A      |N/A    |
|      └─Selection_24(Probe)     |14.84  |0      |cop[tikv]|                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |eq(business_db.event_log.category, "payment"), ge(business_db.event_log.created_time, 2024-09-30 15:00:00.000000), le(business_db.event_log.created_time, 2099-01-01 00:00:01.000000)                                                                       |N/A      |N/A    |
|        └─TableRowIDScan_23     |827.01 |0      |cop[tikv]|table:e                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                                               |N/A      |N/A    |
+--------------------------------+-------+-------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+

```

### 4. What is your TiDB version? (Required)

v8.3.0

<!-- Paste the output of SELECT tidb_version() -->

### PR DESCRIPTION
**Pull request by guo-shaoge**
<!--

Thank you for contributing to TiDB!

PR Title Format:
1. pkg [, pkg2, pkg3]: what's changed
2. *: what's changed

-->

### What problem does this PR solve?
<!--

Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.

-->

Issue Number: close #57090

Problem Summary:

For the following case, the explain analyze output shows `unInitialized` for that expression index(`idx_expr`), which is confusing.
```
set @@global.tidb_enable_auto_analyze = 'OFF';
drop table if exists t1;
-- This is required to make sure the expression collation is same when creating table and using it in select stmt.
set names utf8mb4;
create table t1(id int, c1 int, c2 varchar(100), primary key(id), key idx_expr ((cast(json_unquote(json_extract(`c2`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin)));
insert into t1 values(1, 1, '{"foo": "bar"}'), (2, 1, '{"foo": "bar"}');
analyze table t1 all columns;
-- You may need to run multiple times to trigger load stats
explain analyze select /*+ use_index(t1, idx_expr) */ * from t1 where (cast(json_unquote(json_extract(`c2`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) > '100'  and c2 > 'abc';

TiDB root@127.0.0.1:test> explain analyze select /*+ use_index(t1, idx_expr) */ * from t1 where (cast(json_unquote(json_extract(`c2`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) > '100'  and c2 > 'abc';
+-----------------------------+---------+---------+-----------+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+-----------+------+
| id                          | estRows | actRows | task      | access object                                                                                                              | execution info                                                                                                                                                                                                                                                                                 | operator info                                                                     | memory    | disk |
+-----------------------------+---------+---------+-----------+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+-----------+------+
| Projection_4                | 1.00    | 0       | root      |                                                                                                                            | time:631.5µs, open:72.2µs, close:10.5µs, loops:1, RU:0.48, Concurrency:OFF                                                                                                                                                                                                                     | test.t1.id, test.t1.c1, test.t1.c2                                                | 10.1 KB   | N/A  |
| └─IndexLookUp_10            | 1.00    | 0       | root      |                                                                                                                            | time:614.3µs, open:62µs, close:7.71µs, loops:1                                                                                                                                                                                                                                                 |                                                                                   | 182 Bytes | N/A  |
|   ├─IndexRangeScan_7(Build) | 1.00    | 0       | cop[tikv] | table:t1, index:idx_expr(cast(json_unquote(json_extract(`c2`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) | time:410.6µs, open:0s, close:0s, loops:1, cop_task: {num: 1, max: 343.8µs, proc_keys: 0, copr_cache_hit_ratio: 0.00, build_task_duration: 20.8µs, max_distsql_concurrency: 1}, fetch_resp_duration: 384.4µs, rpc_info:{Cop:{num_rpc:1, total_time:297.6µs}}, tikv_task:{time:185.4µs, loops:0} | range:("100",+inf], keep order:false, stats:partial[_v$_idx_expr_0:unInitialized] | N/A       | N/A  |
|   └─Selection_9(Probe)      | 1.00    | 0       | cop[tikv] |                                                                                                                            |                                                                                                                                                                                                                                                                                                | gt(test.t1.c2, "abc")                                                             | N/A       | N/A  |
|     └─TableRowIDScan_8      | 1.00    | 0       | cop[tikv] | table:t1                                                                                                                   |                                                                                                                                                                                                                                                                                                | keep order:false, stats:partial[_v$_idx_expr_0:unInitialized]                     | N/A       | N/A  |
+-----------------------------+---------+---------+-----------+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+-----------+------+
```

For expression index `idx_expr`, there will be both original column stats and index stats when [calculating selectivity](https://github.com/pingcap/tidb/blob/3e7f31765ebe78bea7e4fdbd762180e20ade300b/pkg/planner/cardinality/selectivity.go#L55). 

Check the following debug output, you can see the column stats is `unInitialized` and the index stats is ready. So for expression index, should use index stats and its column stats.
```
(dlv) p coll.columns[4].Info
("*github.com/pingcap/tidb/pkg/meta/model.ColumnInfo")(0x14038993ce0)
*github.com/pingcap/tidb/pkg/meta/model.ColumnInfo {
	ID: 4,
	Name: github.com/pingcap/tidb/pkg/parser/ast.CIStr {
		O: "_V$_idx_expr_0",
		L: "_v$_idx_expr_0",},
	Offset: 3,
	OriginDefaultValue: interface {} nil,
	OriginDefaultValueBit: []uint8 len: 0, cap: 0, nil,
	DefaultValue: interface {} nil,
	DefaultValueBit: []uint8 len: 0, cap: 0, nil,
	DefaultIsExpr: false,
	GeneratedExprString: "cast(json_unquote(json_extract(`c2`, _utf8mb4'$.location_id')) a...+32 more",
	GeneratedStored: false,
	Dependences: map[string]struct {} [
		"c2": {},
	],
	FieldType: github.com/pingcap/tidb/pkg/parser/types.FieldType {
		tp: 253,
		flag: 8,
		flen: 255,
		decimal: -1,
		charset: "utf8mb4",
		collate: "utf8mb4_bin",
		elems: []string len: 0, cap: 0, nil,
		elemsIsBinaryLit: []bool len: 0, cap: 0, nil,
		array: false,},
	State: StatePublic (5),
	Comment: "",
	Hidden: true,
	ChangeStateInfo: *github.com/pingcap/tidb/pkg/meta/model.ChangeStateInfo nil,
	Version: 2,}
(dlv) p coll.columns[4].StatsLoadedStatus
github.com/pingcap/tidb/pkg/statistics.StatsLoadedStatus {statsInitialized: false, evictedStatus: 0}
```


```
(dlv) p coll.indices[1].Info
("*github.com/pingcap/tidb/pkg/meta/model.IndexInfo")(0x140389c0f00)
*github.com/pingcap/tidb/pkg/meta/model.IndexInfo {
	ID: 1,
	Name: github.com/pingcap/tidb/pkg/parser/ast.CIStr {
		O: "idx_expr",
		L: "idx_expr",},
	Table: github.com/pingcap/tidb/pkg/parser/ast.CIStr {O: "", L: ""},
	Columns: []*github.com/pingcap/tidb/pkg/meta/model.IndexColumn len: 1, cap: 1, [
		*(*"github.com/pingcap/tidb/pkg/meta/model.IndexColumn")(0x14038b5c4e0),
	],
	State: StatePublic (5),
	BackfillState: BackfillStateInapplicable (0),
	Comment: "",
	Tp: IndexTypeBtree (1),
	Unique: false,
	Primary: false,
	Invisible: false,
	Global: false,
	MVIndex: false,
	VectorInfo: *github.com/pingcap/tidb/pkg/meta/model.VectorIndexInfo nil,
	InvertedInfo: *github.com/pingcap/tidb/pkg/meta/model.InvertedIndexInfo nil,
	FullTextInfo: *github.com/pingcap/tidb/pkg/meta/model.FullTextIndexInfo nil,}
(dlv) p coll.indices[1].StatsLoadedStatus
github.com/pingcap/tidb/pkg/statistics.StatsLoadedStatus {statsInitialized: true, evictedStatus: 0}
```
### What changed and how does it work?

### Check List

Tests <!-- At least one of them must be included. -->

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > <!-- Or your custom  "No need to test" reasons -->

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

<!-- compatibility change, improvement, bugfix, and new feature need a release note -->

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by AilinKid** [comment]
image

**Review by AilinKid — APPROVED** [review]

File: pkg/planner/cardinality/selectivity_test.go [hunk 1]
```diff
@@ -2093,3 +2093,20 @@ func TestLastBucketEndValueHeuristic(t *testing.T) {
 		require.InDelta(t, 109.99, idxOtherCount.Est, 0.1, "Index other count should be approximately 109.99")
 	}
 }
+
+func TestUninitializedStats(t *testing.T) {
+	store, _ := testkit.CreateMockStoreAndDomain(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("set @@global.tidb_enable_auto_analyze = 'OFF';")
```
Comment (0xPoe) [inline pkg/planner/cardinality/selectivity_test.go:2100]: I think this is unnecessary in the unit test because it doesn’t reach the analyze threshold.

**Comment by 0xPoe** [comment]
Before fix:
```sql
+--------------------------------------+---------+---------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
| id                                   | estRows | actRows | task      | access object                                                                                                                                   | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | operator info                                                                                                                                                                                                                                                | memory    | disk    |
+--------------------------------------+---------+---------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
| Projection_8                         | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:1, RU:0.952986, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                               | 2.86 KB   | N/A     |
| └─TopN_11                            | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | business_db.event_log.created_time:desc, offset:0, count:70000                                                                                                                                                                                               | 0 Bytes   | 0 Bytes |
|   └─Projection_26                    | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:2, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)) | 3.48 KB   | N/A     |
|     └─IndexLookUp_25                 | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                              | 238 Bytes | N/A     |
|       ├─IndexRangeScan_22(Build)     | 827.01  | 0       | cop[tikv] | table:e, index:idx_metadata_location_id(cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) | time:2.71ms, loops:1, cop_task: {num: 1, max: 197.1µs, proc_keys: 0, tot_proc: 8.96µs, tot_wait: 49.5µs, copr_cache_hit_ratio: 0.00, build_task_duration: 4.46µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:2, total_time:371.2µs}, rpc_errors:{epoch_not_match:1}}, backoff{regionMiss: 2ms}, tikv_task:{time:0s, loops:1}, scan_detail: {total_keys: 1, get_snapshot_time: 43.8µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 8.96µs, total_wait_time: 49.5µs, tikv_wall_time: 89.8µs}          | range:["498","498"], keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                           | N/A       | N/A     |
|       └─Selection_24(Probe)          | 14.84   | 0       | cop[tikv] |                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | eq(business_db.event_log.category, "payment"), ge(business_db.event_log.created_time, 2024-09-30 15:00:00.000000), le(business_db.event_log.created_time, 2099-01-01 00:00:01.000000)                                                                        | N/A       | N/A     |
|         └─TableRowIDScan_23          | 827.01  | 0       | cop[tikv] | table:e                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                                                | N/A       | N/A     |
```
After fix:
```sql
+----------------------------------------+------------+---------+-----------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+------+ | id                                     | estRows    | actRows | task      | access object                                 | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | operator info                                                                                                                                                                                                                                                | memory    | disk |
+----------------------------------------+------------+---------+-----------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+------+
| Projection_8                           | 14.84      | 0       | root      |                                               | time:445.7µs, open:9.42µs, close:7.29µs, loops:1, RU:0.48, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                               | 57.0 KB   | N/A  |
| └─Limit_15                             | 14.84      | 0       | root      |                                               | time:441.8µs, open:7.13µs, close:6.46µs, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | offset:0, count:70000                                                                                                                                                                                                                                        | N/A       | N/A  |
|   └─Selection_33                       | 620485.03  | 0       | root      |                                               | time:440µs, open:6.33µs, close:6.29µs, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | eq(cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)), "498")                                                                                                                      | 2.86 KB   | N/A  |
|     └─Projection_32                    | 775606.29  | 0       | root      |                                               | time:437µs, open:4.29µs, close:6.04µs, loops:1, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)) | 31.7 KB   | N/A  |
|       └─IndexLookUp_31                 | 775606.29  | 0       | root      |                                               | time:416.9µs, open:3.92µs, close:2.71µs, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                              | 247 Bytes | N/A  |
|         ├─IndexRangeScan_28(Build)     | 1396311.43 | 0       | cop[tikv] | table:e, index:idx_created_time(created_time) | time:377.3µs, open:0s, close:0s, loops:1, cop_task: {num: 1, max: 362.8µs, proc_keys: 0, tot_proc: 25.3µs, tot_wait: 76.1µs, copr_cache_hit_ratio: 0.00, build_task_duration: 5.58µs, max_distsql_concurrency: 1}, fetch_resp_duration: 371µs, rpc_info:{Cop:{num_rpc:1, total_time:352.6µs}}, tikv_task:{time:0s, loops:1}, scan_detail: {total_keys: 1, get_snapshot_time: 60.2µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 25.3µs, total_wait_time: 76.1µs, tikv_grpc_process_time: 17.6µs, tikv_grpc_wait_time: 145.2µs, tikv_wall_time: 164.3µs}              | range:[2024-09-30 15:00:00.000,2099-01-01 00:00:01.000], keep order:true, desc                                                                                                                                                                               | N/A       | N/A  |
|         └─Selection_30(Probe)          | 775606.29  | 0       | cop[tikv] |                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | eq(business_db.event_log.category, "payment")                                                                                                                                                                                                                | N/A       | N/A  |

```

File: pkg/planner/cardinality/selectivity.go [hunk 2]
```diff
@@ -129,6 +129,11 @@ func Selectivity(
 	for _, col := range extractedCols {
 		id := col.UniqueID
 		colStats := coll.GetCol(id)
+		if col.IsHidden && col.VirtualExpr != nil {
+			// For expression index, only the index stats should be used,
+			// column stats can be ignored.
+			continue
+		}
```
Comment (0xPoe) [inline pkg/planner/cardinality/selectivity.go]:
```suggestion
if col.IsHidden && col.VirtualExpr != nil {
	// For expression index, only the index stats should be used,
	// column stats can be ignored.
	continue
}
id := col.UniqueID
colStats := coll.GetCol(id)
```

**Comment by guo-shaoge** [comment]
> Before fix:
> 
> ```sql
> +--------------------------------------+---------+---------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
> | id                                   | estRows | actRows | task      | access object                                                                                                                                   | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | operator info                                                                                                                                                                                                                                                | memory    | disk    |
> +--------------------------------------+---------+---------+-----------+-------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+---------+
> | Projection_8                         | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:1, RU:0.952986, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                               | 2.86 KB   | N/A     |
> | └─TopN_11                            | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | business_db.event_log.created_time:desc, offset:0, count:70000                                                                                                                                                                                               | 0 Bytes   | 0 Bytes |
> |   └─Projection_26                    | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:2, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)) | 3.48 KB   | N/A     |
> |     └─IndexLookUp_25                 | 14.84   | 0       | root      |                                                                                                                                                 | time:2.73ms, loops:2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                              | 238 Bytes | N/A     |
> |       ├─IndexRangeScan_22(Build)     | 827.01  | 0       | cop[tikv] | table:e, index:idx_metadata_location_id(cast(json_unquote(json_extract(`metadata`, _utf8mb4'$.location_id')) as char(255)) collate utf8mb4_bin) | time:2.71ms, loops:1, cop_task: {num: 1, max: 197.1µs, proc_keys: 0, tot_proc: 8.96µs, tot_wait: 49.5µs, copr_cache_hit_ratio: 0.00, build_task_duration: 4.46µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:2, total_time:371.2µs}, rpc_errors:{epoch_not_match:1}}, backoff{regionMiss: 2ms}, tikv_task:{time:0s, loops:1}, scan_detail: {total_keys: 1, get_snapshot_time: 43.8µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 8.96µs, total_wait_time: 49.5µs, tikv_wall_time: 89.8µs}          | range:["498","498"], keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                           | N/A       | N/A     |
> |       └─Selection_24(Probe)          | 14.84   | 0       | cop[tikv] |                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | eq(business_db.event_log.category, "payment"), ge(business_db.event_log.created_time, 2024-09-30 15:00:00.000000), le(business_db.event_log.created_time, 2099-01-01 00:00:01.000000)                                                                        | N/A       | N/A     |
> |         └─TableRowIDScan_23          | 827.01  | 0       | cop[tikv] | table:e                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | keep order:false, stats:partial[_v$_idx_metadata_location_id_0:unInitialized]                                                                                                                                                                                | N/A       | N/A     |
> ```
> 
> After fix:
> 
> ```sql
> +----------------------------------------+------------+---------+-----------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+------+ | id                                     | estRows    | actRows | task      | access object                                 | execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | operator info                                                                                                                                                                                                                                                | memory    | disk |
> +----------------------------------------+------------+---------+-----------+-----------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+------+
> | Projection_8                           | 14.84      | 0       | root      |                                               | time:445.7µs, open:9.42µs, close:7.29µs, loops:1, RU:0.48, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | business_db.event_log.id, business_db.event_log.category, business_db.event_log.created_time, business_db.event_log.money_info                                                                                                                               | 57.0 KB   | N/A  |
> | └─Limit_15                             | 14.84      | 0       | root      |                                               | time:441.8µs, open:7.13µs, close:6.46µs, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | offset:0, count:70000                                                                                                                                                                                                                                        | N/A       | N/A  |
> |   └─Selection_33                       | 620485.03  | 0       | root      |                                               | time:440µs, open:6.33µs, close:6.29µs, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | eq(cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)), "498")                                                                                                                      | 2.86 KB   | N/A  |
> |     └─Projection_32                    | 775606.29  | 0       | root      |                                               | time:437µs, open:4.29µs, close:6.04µs, loops:1, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | business_db.event_log.id, business_db.event_log.created_time, business_db.event_log.money_info, business_db.event_log.category, cast(json_unquote(cast(json_extract(business_db.event_log.metadata, $.location_id), var_string(16777216))), var_string(255)) | 31.7 KB   | N/A  |
> |       └─IndexLookUp_31                 | 775606.29  | 0       | root      |                                               | time:416.9µs, open:3.92µs, close:2.71µs, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                              | 247 Bytes | N/A  |
> |         ├─IndexRangeScan_28(Build)     | 1396311.43 | 0       | cop[tikv] | table:e, index:idx_created_time(created_time) | time:377.3µs, open:0s, close:0s, loops:1, cop_task: {num: 1, max: 362.8µs, proc_keys: 0, tot_proc: 25.3µs, tot_wait: 76.1µs, copr_cache_hit_ratio: 0.00, build_task_duration: 5.58µs, max_distsql_concurrency: 1}, fetch_resp_duration: 371µs, rpc_info:{Cop:{num_rpc:1, total_time:352.6µs}}, tikv_task:{time:0s, loops:1}, scan_detail: {total_keys: 1, get_snapshot_time: 60.2µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 25.3µs, total_wait_time: 76.1µs, tikv_grpc_process_time: 17.6µs, tikv_grpc_wait_time: 145.2µs, tikv_wall_time: 164.3µs}              | range:[2024-09-30 15:00:00.000,2099-01-01 00:00:01.000], keep order:true, desc                                                                                                                                                                               | N/A       | N/A  |
> |         └─Selection_30(Probe)          | 775606.29  | 0       | cop[tikv] |                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | eq(business_db.event_log.category, "payment")                                                                                                                                                                                                                | N/A       | N/A  |
> ```

I opened an issue for this plan change: https://github.com/pingcap/tidb/issues/63985

File: pkg/planner/cardinality/selectivity.go (hunk 2 above)
Comment (guo-shaoge) [reply pkg/planner/cardinality/selectivity.go]: done

File: pkg/planner/cardinality/selectivity_test.go (hunk 1 above)
Comment (guo-shaoge) [reply pkg/planner/cardinality/selectivity_test.go:2100]: I think it's not a big deal. I will leave as it is.
