### PR TITLE
ddl: Fix the way to notify the reorganization worker after 'admin resume'

### LINKED ISSUE #44217: DDL jobs resume problem when from pause state.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1, create table sbtest1,  with rows;
| sbtest1 | CREATE TABLE `sbtest1` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `k` bigint(20) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=3504049056
PARTITION BY RANGE (`id`)
(PARTITION `p0` VALUES LESS THAN (100000000),
 PARTITION `p1` VALUES LESS THAN (200000000),
 PARTITION `p2` VALUES LESS THAN (300000000),
 PARTITION `p3` VALUES LESS THAN (400000000),
 PARTITION `p4` VALUES LESS THAN (500000000),
 PARTITION `p5` VALUES LESS THAN (600000000),
 PARTITION `p6` VALUES LESS THAN (700000000),
 PARTITION `p7` VALUES LESS THAN (800000000),
 PARTITION `p8` VALUES LESS THAN (900000000),
 PARTITION `p9` VALUES LESS THAN (1000000000),
 PARTITION `p10` VALUES LESS THAN (1100000000),
 PARTITION `p11` VALUES LESS THAN (1200000000),
 PARTITION `p12` VALUES LESS THAN (1300000000),
 PARTITION `p13` VALUES LESS THAN (1400000000),
 PARTITION `p14` VALUES LESS THAN (1500000000),
 PARTITION `p15` VALUES LESS THAN (1600000000),
 PARTITION `p16` VALUES LESS THAN (1700000000),
 PARTITION `p17` VALUES LESS THAN (1800000000),
 PARTITION `p18` VALUES LESS THAN (1900000000),
 PARTITION `p19` VALUES LESS THAN (2000000000),
 PARTITION `p20` VALUES LESS THAN (2100000000),
 PARTITION `p21` VALUES LESS THAN (2200000000),
 PARTITION `p22` VALUES LESS THAN (2300000000),
 PARTITION `p23` VALUES LESS THAN (2400000000),
 PARTITION `p24` VALUES LESS THAN (2500000000),
 PARTITION `p25` VALUES LESS THAN (2600000000),
 PARTITION `p26` VALUES LESS THAN (2700000000),
 PARTITION `p27` VALUES LESS THAN (2800000000),
 PARTITION `p28` VALUES LESS THAN (2900000000),
 PARTITION `p29` VALUES LESS THAN (MAXVALUE)) |
2, prepare 3.5b rows for table;
3. add index and pause in write reorg state; pause success;
alter table sbtest1 add index idxx(k)
4. wait a while and resume the add index job;
5. Resume return successful, but job can not resume to running normal, it stacked.

err:[ddl:8210]Invalid %!!(string=index)s(MISSING) state: %!!(model.SchemaState=5)v(MISSING), ErrCount:23, SnapshotVersion:441748034448785415,

After job canceled because retry times overflow, you can not create same name index again.

### 2. What did you expect to see? (Required)
Add index resume successful and create index successful.

### 3. What did you see instead (Required)
Adding index job stacked and after canceled, we can not add a same name index again.

### 4. What is your TiDB version? (Required)
5cc1c3b39eef1596d9432fe5db74ee02b83be46b

### PR DESCRIPTION
**Pull request by dhysum**
### What problem does this PR solve?

Issue Number: close #44217

Problem Summary: fail to resume the paused ddl job

### What is changed and how it works?

1. Fix bug in notify the reorganization worker after 'admin resume'
2. Better logging to reduce noise

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/ddl.go [hunk 1]
```diff
@@ -550,10 +550,8 @@ func (dc *ddlCtx) removeReorgCtx(jobID int64) {
 func (dc *ddlCtx) notifyReorgWorkerJobStateChange(job *model.Job) {
 	rc := dc.getReorgCtx(job.ID)
 	if rc == nil {
-		logutil.BgLogger().Error("cannot find reorgCtx", zap.Int64("jobID", job.ID))
```
Comment (zimulala) [inline ddl/ddl.go:553]: Why remove these two logs?

File: ddl/ddl_worker.go [hunk 2]
```diff
@@ -977,14 +983,15 @@ func (w *worker) runDDLJob(d *ddlCtx, t *meta.Meta, job *model.Job) (ver int64,
 	failpoint.Inject("mockPanicInRunDDLJob", func(val failpoint.Value) {})
 
 	if job.Type != model.ActionMultiSchemaChange {
-		logutil.Logger(w.logCtx).Info("[ddl] run DDL job", zap.String("job", job.String()))
+		logutil.Logger(w.logCtx).Debug("[ddl] run DDL job", zap.String("job", job.String()))
```
Comment (zimulala) [inline ddl/ddl_worker.go:986]: Please don't modify this level. This is a log that prints for each state, and if you delete it, it's hard to debug later.

File: parser/model/ddl.go [hunk 3]
```diff
@@ -854,6 +854,19 @@ func (job *Job) IsRollbackable() bool {
 	return true
 }
 
+func (job *Job) NeedNotifyAndStopReorgWorker() bool {
```
Comment (zimulala) [inline parser/model/ddl.go:858]: This function is complex(goes into more detail) and only used in ddl. I think putting it to `ddl/reorg.go` is better.

**Review by zimulala — COMMENTED** [review]
In the PR description, UT is selected, but I don't seem to see UT on the side of the code, did you forget to write it?

File: ddl/ddl.go (hunk 1 above)
Comment (dhysum) [reply ddl/ddl.go:553]: seams not necessary, I'd like to change it to be debug but not remove it.

File: ddl/ddl_worker.go (hunk 2 above)
Comment (dhysum) [reply ddl/ddl_worker.go:986]: Kind of noise since it will print every time we come here.

File: parser/model/ddl.go (hunk 3 above)
Comment (dhysum) [reply parser/model/ddl.go:858]: This is a kind of design issue. 

The who procedure of this function is not out of Job, even though which is for reorg.go only.  Once we design the whole architecture as Object Oriented, we may do it like this, otherwise depends.

**Review by zimulala — APPROVED** [review]
LGTM

**Review by Benjamin2037 — APPROVED** [review]
LGTM
