### PR TITLE
types: fix wrong hash key for decimal

### LINKED ISSUE #19112: Got incorrect result when using hash join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1, t2;
create table t1 ( c_int int, c_decimal decimal(12, 6), key(c_int), unique key(c_decimal) );
create table t2 like t1;
insert into t1 (c_int, c_decimal) values (1, 4.064000), (2, 0.257000), (3, 1.010000);
insert into t2 (c_int, c_decimal) values (1, 4.064000), (3, 1.010000);
select /*+ INL_MERGE_JOIN(t1,t2) */  * from t1 join t2 on t1.c_decimal = t2.c_decimal order by t1.c_int;
select /*+ HASH_JOIN(t1,t2) */  * from t1 join t2 on t1.c_decimal = t2.c_decimal order by t1.c_int;
```

### 2. What did you expect to see? (Required)

```
+-------+-----------+-------+-----------+
| c_int | c_decimal | c_int | c_decimal |
+-------+-----------+-------+-----------+
|     1 |  4.064000 |     1 |  4.064000 |
|     3 |  1.010000 |     3 |  1.010000 |
+-------+-----------+-------+-----------+
```

### 3. What did you see instead (Required)

```
mysql> select /*+ INL_MERGE_JOIN(t1,t2) */  * from t1 join t2 on t1.c_decimal = t2.c_decimal order by t1.c_int;
+-------+-----------+-------+-----------+
| c_int | c_decimal | c_int | c_decimal |
+-------+-----------+-------+-----------+
|     1 |  4.064000 |     1 |  4.064000 |
|     3 |  1.010000 |     3 |  1.010000 |
+-------+-----------+-------+-----------+
2 rows in set (0.09 sec)

mysql> select /*+ HASH_JOIN(t1,t2) */  * from t1 join t2 on t1.c_decimal = t2.c_decimal order by t1.c_int;
+-------+-----------+-------+-----------+
| c_int | c_decimal | c_int | c_decimal |
+-------+-----------+-------+-----------+
|     1 |  4.064000 |     1 |  4.064000 |
|     2 |  0.257000 |     3 |  1.010000 |
|     3 |  1.010000 |     3 |  1.010000 |
+-------+-----------+-------+-----------+
3 rows in set (0.06 sec)

```

### 4. What is your TiDB version? (Required)

master @ 8978773f5e3d43a100550e6babea9904a99e5938
release-4.0 @ 7cac557b024f0aaca6825193477e5e6daea7055b

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #19112

### What is changed and how it works?

What's Changed: `MyDecimal.ToHashKey` should consider the length of `int` and `Frac`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- fix wrong hash key for decimal

### CODE REVIEW

File: types/mydecimal.go [hunk 1]
```diff
@@ -1301,6 +1302,12 @@ func (d *MyDecimal) ToHashKey() ([]byte, error) {
 		// thus ErrTruncated may be raised, we can ignore it here.
 		err = nil
 	}
+	precBuff := make([]byte, 4)
```
Comment (breeswish) [inline types/mydecimal.go:1305]: Can you use some fuzz test to check whether `a eq b ==> hash(a) eq hash(b)` always be true?

TiKV's [Decimal hash](https://github.com/tikv/tikv/pull/6047) implementation passed such fuzz test.

Comment (lzmhhh123) [reply types/mydecimal.go:1305]: Here are the tests: https://github.com/lzmhhh123/tidb/blob/6320bea24d3f790714908844cd519e5267c4ac2e/types/mydecimal_test.go#L154, actually, is `a eq b <=> hash(a) eq hash(b)` rather than `a eq b ==> hash(a) eq hash(b)`

Comment (breeswish) [reply types/mydecimal.go:1305]: Fuzz tests are tests that uses a fuzzer to run, instead of unit tests. (Also i don't quite understand the necessarity of ensuring that `Hash(a) eq Hash(b) => a eq b`. If this can be ensured, then there would be no hash collision?)

Comment (lzmhhh123) [reply types/mydecimal.go:1305]: IMHO, if we add fuzzer test, other types of hash functions also need to be involved in fuzzer test. It's another thing. Perhaps we can discuss it in another issue. And for `Hash(a) eq Hash(b) => a eq b`, because we use the function to compare decimal in some places.

Comment (SunRunAway) [reply types/mydecimal.go:1305]: Agree with @lzmhhh123 , `Hash(a) eq Hash(b) => a eq b` is still necessary, and this should be no hash collision by the unlimited hash size.

**Comment by breeswish** [comment]
This test case shows that current implementation is still incorrect:

```go
func TestDec(t *testing.T) {
	dec1 := &MyDecimal{}
	if err := dec1.FromString([]byte(".1is column 'ommand den6ser '%-956465")); err != nil {
		panic("dec1")
	}

	dec2 := &MyDecimal{}
	if err := dec2.FromString([]byte("0.10s e8s'@'%-.664000000000000000000000000000")); err != nil {
		panic("dec2")
	}

	if dec1.Compare(dec2) != 0 {
		panic("dec not equal")
	}

	h1, err := dec1.ToHashKey()
	if err != nil {
		panic(err)
	}

	h2, err := dec2.ToHashKey()
	if err != nil {
		panic(err)
	}

	if bytes.Compare(h1, h2) != 0 {
		panic("dec1 eq dec2 but dec1 hash not eq dec2 hash")
	}
}
```

```
panic: dec1 eq dec2 but dec1 hash not eq dec2 hash
```

**Comment by lzmhhh123** [comment]
> This test case shows that current implementation is still incorrect:
> 
> ```go
> func TestDec(t *testing.T) {
> 	dec1 := &MyDecimal{}
> 	if err := dec1.FromString([]byte(".1is column 'ommand den6ser '%-956465")); err != nil {
> 		panic("dec1")
> 	}
> 
> 	dec2 := &MyDecimal{}
> 	if err := dec2.FromString([]byte("0.10s e8s'@'%-.664000000000000000000000000000")); err != nil {
> 		panic("dec2")
> 	}
> 
> 	if dec1.Compare(dec2) != 0 {
> 		panic("dec not equal")
> 	}
> 
> 	h1, err := dec1.ToHashKey()
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	h2, err := dec2.ToHashKey()
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	if bytes.Compare(h1, h2) != 0 {
> 		panic("dec1 eq dec2 but dec1 hash not eq dec2 hash")
> 	}
> }
> ```
> 
> ```
> panic: dec1 eq dec2 but dec1 hash not eq dec2 hash
> ```

0.1 and 0.10 have different hash key. It's another bug.

File: types/mydecimal.go [hunk 2]
```diff
@@ -1301,6 +1302,12 @@ func (d *MyDecimal) ToHashKey() ([]byte, error) {
...
+	digitBuff := make([]byte, 4)
+	binary.LittleEndian.PutUint32(precBuff, uint32(prec))
+	binary.LittleEndian.PutUint32(digitBuff, uint32(digitsFrac))
+	buf = append(buf, precBuff...)
+	buf = append(buf, digitBuff...)
```
Comment (SunRunAway) [inline types/mydecimal.go:1310]: > ToBin converts decimal to its binary fixed-length representation
two representations of the same length can be compared with memcmp
with the correct -1/0/+1 result

It should be modified in `ToBin` method.
And some unit tests for comparison are better to be added.

**Comment by lzmhhh123** [comment]
@breeswish @SunRunAway PTAL. Already fixed.

**Comment by breeswish** [comment]
Here is a case that value eq but hash not eq using the latest code base:

dec1 = `0000000000000000000000000000000000000000000.0000000000005987000000000000000/000000000000000000000000000000000000`
dec2 = `00000000000000000000000000000.000000000000598700`

**Comment by breeswish** [comment]
I found some new bugs. "ToHashKey" function will return errors in some cases. I'm not sure whether this case should be handled:

```
dec1 = 4e-41
dec2 = 4e-41
```

**Comment by lzmhhh123** [comment]
> I found some new bugs. "ToHashKey" function will return errors in some cases. I'm not sure whether this case should be handled:
> 
> ```
> dec1 = 4e-41
> dec2 = 4e-41
> ```

TiDB's `MaxDecimalScale` is 30.

**Comment by ichn-hu** [comment]
This PR could close https://github.com/pingcap/tidb/issues/17216

**Comment by lzmhhh123** [comment]
also fixed https://github.com/pingcap/tidb/issues/11852

File: types/mydecimal.go [hunk 3]
```diff
@@ -1301,6 +1305,12 @@ func (d *MyDecimal) ToHashKey() ([]byte, error) {
 		// thus ErrTruncated may be raised, we can ignore it here.
 		err = nil
 	}
+	precBuff := make([]byte, 4)
+	digitBuff := make([]byte, 4)
+	binary.LittleEndian.PutUint32(precBuff, uint32(prec))
+	binary.LittleEndian.PutUint32(digitBuff, uint32(digitsFrac))
```
Comment (SunRunAway) [inline types/mydecimal.go:1311]: I think storing `digitsFrac` is enough after removing the leading and trailing zeros.

File: types/mydecimal.go [hunk 4]
```diff
@@ -1227,10 +1228,13 @@ func (d *MyDecimal) WriteBin(precision, frac int, buf []byte) ([]byte, error) {
 		}
 	}
 
-	if fracSize < fracSizeFrom {
+	if fracSize < fracSizeFrom ||
+		(fracSize == fracSizeFrom && (trailingDigits <= trailingDigitsFrom || wordsFrac <= wordsFracFrom)) {
```
Comment (SunRunAway) [inline types/mydecimal.go:1232]: Could you add some tests when `trailingDigits > trailingDigitsFrom` or  `wordsFrac > wordsFracFrom`?

File: types/mydecimal_test.go [hunk 5]
```diff
@@ -571,6 +573,17 @@ func (s *testMyDecimalSuite) TestToBinFromBin(c *C) {
 		{"000000000.01", 7, 3, "0.010", nil},
 		{"123.4", 10, 2, "123.40", nil},
 		{"1000", 3, 0, "0", ErrOverflow},
+		{"0.1", 1, 1, "0.1", nil},
+		{"0.100", 1, 1, "0.1", ErrTruncated},
+		{"0.1000", 1, 1, "0.1", ErrTruncated},
+		{"0.10000", 1, 1, "0.1", ErrTruncated},
+		{"0.100000", 1, 1, "0.1", ErrTruncated},
+		{"0.1000000", 1, 1, "0.1", ErrTruncated},
+		{"0.10", 1, 1, "0.1", ErrTruncated},
```
Comment (SunRunAway) [inline types/mydecimal_test.go:582]: better to add some test cases like `ToHashKey(0.1)` with `ToHashKey(0.10)` in `TestToHashKey`

**Comment by ichn-hu** [comment]
> This PR could close #17216

Would you please add a test case for this issue? It has a minial test case here https://github.com/pingcap/tidb/issues/17216#issuecomment-671705007

File: types/mydecimal_test.go (hunk 5 above)
Comment (lzmhhh123) [reply types/mydecimal_test.go:582]: There are already similar cases in `TestToHashKey` functions.

Comment (SunRunAway) [reply types/mydecimal_test.go:582]: `TestToHashKey` has not `0.10` case.
