### PR TITLE
lightning: Fix panic when downstream table schema has changed

### LINKED ISSUE #34163: lightning: panic when de-duplication
## Bug Report

lightning 5.4.0 panic when de-duplication when there's previous leftted data in `conflict_error_v1` and the table ddl is different with previous task which also has this table

```
2022-04-21 23:54:58	
github.com/pingcap/tidb/br/pkg/lightning/errormanager.(*ErrorManager).ResolveAllConflictKeys.func2(0x0, 0x0)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/local.go:1443 +0xb8
2022-04-21 23:54:58	
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*local).ResolveDuplicateRows.func2(0x4760048, 0xc001949c00, 0xc001b30000, 0x3e8, 0x400, 0x0, 0x200)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/local.go:1500 +0x4e7
2022-04-21 23:54:58	
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*local).deleteDuplicateRows(0xc00155a300, 0x4760048, 0xc001949c00, 0xc001949b80, 0xc001b30000, 0x3e8, 0x400, 0xc001949bc0, 0x0, 0x0)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/kv/kv2sql.go:68 +0x85
2022-04-21 23:54:58	
github.com/pingcap/tidb/br/pkg/lightning/backend/kv.(*TableKVDecoder).IterRawIndexKeys(0xc001949bc0, 0x4794278, 0xc01bcd5260, 0xc000b12160, 0x15d, 0x15d, 0xc0019f3a40, 0x133e065, 0xc000daa898)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/kv/kv2sql.go:51 +0xfb
2022-04-21 23:54:58	
github.com/pingcap/tidb/br/pkg/lightning/backend/kv.(*TableKVDecoder).DecodeRawRowData(0xc001949bc0, 0x4794278, 0xc01bcd5260, 0xc000b12160, 0x15d, 0x15d, 0xc0018d3a00, 0x42e72f0, 0x134915b, 0x364b0e5, ...)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/table/tables/tables.go:996 +0x806
2022-04-21 23:54:58	
github.com/pingcap/tidb/table/tables.DecodeRawRowData(0x47ac658, 0xc143e46c00, 0xc00083c000, 0x4794278, 0xc01bcd5260, 0xc0030541a0, 0x33, 0x33, 0xc000b12160, 0x15d, ...)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/tablecodec/tablecodec.go:465 +0x6e
2022-04-21 23:54:58	
github.com/pingcap/tidb/tablecodec.DecodeRowToDatumMap(0xc000b12160, 0x15d, 0x15d, 0xc000fbf628, 0x672d4e0, 0x1ae3, 0xc000fbf518, 0x1354393)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/tablecodec/tablecodec.go:401 +0x22a
2022-04-21 23:54:58	
github.com/pingcap/tidb/tablecodec.DecodeRowWithMapNew(0xc000b12160, 0x15d, 0x15d, 0xc000fbf628, 0x672d4e0, 0xc001b83980, 0x0, 0x3bfeea0, 0xc0003acfb0)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/util/rowcodec/decoder.go:83 +0x315
2022-04-21 23:54:58	
github.com/pingcap/tidb/util/rowcodec.(*DatumMapDecoder).DecodeToDatumMap(0xc0019f3370, 0xc000b12160, 0x15d, 0x15d, 0xc001b83980, 0x18, 0x8, 0xc000cebe00)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/util/rowcodec/decoder.go:127 +0x969
2022-04-21 23:54:58	
github.com/pingcap/tidb/util/rowcodec.(*DatumMapDecoder).decodeColDatum(0xc000fbf370, 0xc000c54530, 0xc000b12278, 0x4, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/util/codec/decimal.go:59 +0x1b2
2022-04-21 23:54:58	
github.com/pingcap/tidb/util/codec.DecodeDecimal(0xc000b1227a, 0x2, 0x43, 0xd, 0x7faf3f0a9590, 0x0, 0x1aea, 0xc000fbf0f0, 0x1354393, 0x7faf3ec37db8, ...)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/types/mydecimal.go:1404 +0x933
2022-04-21 23:54:58	
github.com/pingcap/tidb/types.(*MyDecimal).FromBin(0xc0018d13e0, 0xc000b1227a, 0x2, 0x43, 0x52, 0x55, 0xc001bd9140, 0x19509f3, 0xc001d80940)
2022-04-21 23:54:58	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/types/mydecimal.go:1486
2022-04-21 23:54:58	
github.com/pingcap/tidb/types.DecimalBinSize(...)
2022-04-21 23:54:58	
goroutine 40146 [running]:
2022-04-21 23:54:58	

2022-04-21 23:54:58	
panic: runtime error: index out of range [-3]
```

root cause is this sql didn't specify taskid, so  data of previous task is queried, when decoding using current ddl, panic.
https://github.com/pingcap/tidb/blob/55f3b24c1c9f506bd652ef1d162283541e428872/br/pkg/lightning/errormanager/errormanager.go#L110-L114

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
panic
### 4. What is your TiDB version? (Required)
5.3.1

### PR DESCRIPTION
**Pull request by ForwardStar**
### What problem does this PR solve?

Issue Number: close #34163 

Problem Summary:

### What is changed and how it works?

Throw an error instead of panic.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: types/mydecimal.go [hunk 1]
```diff
@@ -1403,8 +1403,14 @@ func (d *MyDecimal) FromBin(bin []byte, precision, frac int) (binSize int, err e
 	if bin[binIdx]&0x80 > 0 {
 		mask = 0
 	}
-	binSize = DecimalBinSize(precision, frac)
+	binSize, err = DecimalBinSize(precision, frac)
+	if err != nil {
+		return 0, err
+	}
 	dCopy := make([]byte, 40)
+	if binSize < 0 || binSize > 40 {
```
Comment (D3Hunter) [inline types/mydecimal.go:1411]: can move this `if` up for one line

File: br/pkg/lightning/backend/local/local.go [hunk 2]
```diff
@@ -1681,6 +1683,12 @@ func (local *local) ResolveDuplicateRows(ctx context.Context, tbl table.Table, t
 				if err == nil {
 					return nil
 				}
+				if terror.ErrorEqual(err, types.ErrBadNumber) {
+					logger.Warn("delete duplicate rows encounter error", log.ShortError(err))
+					return fmt.Errorf(`delete duplicate rows encounter error: %s
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/local/local.go:1688]: maybe use a named error in `common/errors.go`

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: types/mydecimal.go [hunk 3]
```diff
@@ -1479,13 +1485,16 @@ func (d *MyDecimal) FromBin(bin []byte, precision, frac int) (binSize int, err e
 }
 
 // DecimalBinSize returns the size of array to hold a binary representation of a decimal.
-func DecimalBinSize(precision, frac int) int {
+func DecimalBinSize(precision, frac int) (int, error) {
```
Comment (D3Hunter) [inline types/mydecimal.go:1488]: add some `ut` for the new branch

for code below too

File: util/codec/codec.go [hunk 4]
```diff
@@ -157,7 +157,12 @@ func EstimateValueSize(sc *stmtctx.StatementContext, val types.Datum) (int, erro
 	case types.KindString, types.KindBytes:
 		l = valueSizeOfBytes(val.GetBytes())
 	case types.KindMysqlDecimal:
-		l = valueSizeOfDecimal(val.GetMysqlDecimal(), val.Length(), val.Frac()) + 1
+		var err error
+		l, err = valueSizeOfDecimal(val.GetMysqlDecimal(), val.Length(), val.Frac())
```
Comment (lyzx2001) [inline util/codec/codec.go:161]: Maybe can change to 'err := ' instead of 'var err error', to be in accordance with other 'err := '

Comment (ForwardStar) [reply util/codec/codec.go:161]: This may redefine ``l`` as a local variable in this case, which leads to a wrong logic.

Comment (lyzx2001) [reply util/codec/codec.go:161]: Right

**Comment by lyzx2001** [comment]
LGTM

File: br/pkg/lightning/backend/local/local.go [hunk 5]
```diff
@@ -1681,6 +1682,10 @@ func (local *local) ResolveDuplicateRows(ctx context.Context, tbl table.Table, t
 				if err == nil {
 					return nil
 				}
+				if types.ErrBadNumber.Equal(err) {
+					logger.Warn("delete duplicate rows encounter error", log.ShortError(err))
+					return common.ErrInconsistentSchema.GenWithStackByArgs(tableName)
```
Comment (D3Hunter) [inline br/pkg/lightning/backend/local/local.go:1687]: from `ErrBadNumber` we cannot conclude there're inconsistent schema, although it's the case we met.

prefer we  name it `ErrResolveDuplicateRows` and add the guess in extra err message

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

@lance6716 does this pr need review from tidb side?

File: br/pkg/lightning/backend/local/local.go (hunk 5 above)
Comment (ForwardStar) [reply br/pkg/lightning/backend/local/local.go:1687]: I check the codes where return ``ErrBadNumber`` error. This comes from when we assume the data type should be ``Decimal`` but it is not. So I think type inconsistent or table schema inconsistent may be the raw cause. But for sure, I think your suggestion is legitimate.

Besides, there are still some errors we did not handle in this infinite loop. For example: https://github.com/pingcap/tidb/blob/1436ab9e7b4dc9fef3ab4ac359a6c0ae3452c453/util/codec/decimal.go#L53 I suggest modifying it to ``ErrBadNumber`` as well.

Comment (ForwardStar) [reply br/pkg/lightning/backend/local/local.go:1687]: Although not related to our issue, I worried that some potential problems may occur. Therefore, I think extra reviews are appreciated.

**Comment by lance6716** [comment]
@XuHuaiyu @ekexium PTAL about codec changes

**Review by ekexium — COMMENTED** [review]
The codec change LGTM

File: br/pkg/lightning/backend/local/local.go (hunk 5 above)
Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1687]: > Besides, there are still some errors we did not handle in this infinite loop

we can do it in later pr

File: br/pkg/lightning/common/errors.go [hunk 6]
```diff
@@ -81,19 +81,20 @@ var (
...
+	ErrUnknownColumns       = errors.Normalize("unknown columns in header (%s) for table %s", errors.RFCCodeText("Lightning:Restore:ErrUnknownColumns"))
+	ErrChecksumMismatch     = errors.Normalize("checksum mismatched remote vs local => (checksum: %d vs %d) (total_kvs: %d vs %d) (total_bytes:%d vs %d)", errors.RFCCodeText("Lighting:Restore:ErrChecksumMismatch"))
+	ErrRestoreTable         = errors.Normalize("restore table %s failed", errors.RFCCodeText("Lightning:Restore:ErrRestoreTable"))
+	ErrEncodeKV             = errors.Normalize("encode kv error in file %s at offset %d", errors.RFCCodeText("Lightning:Restore:ErrEncodeKV"))
+	ErrAllocTableRowIDs     = errors.Normalize("allocate table row id error", errors.RFCCodeText("Lightning:Restore:ErrAllocTableRowIDs"))
+	ErrInvalidMetaStatus    = errors.Normalize("invalid meta status: '%s'", errors.RFCCodeText("Lightning:Restore:ErrInvalidMetaStatus"))
+	ErrTableIsChecksuming   = errors.Normalize("table '%s' is checksuming", errors.RFCCodeText("Lightning:Restore:ErrTableIsChecksuming"))
+	ErrResolveDuplicateRows = errors.Normalize("resolve duplicate rows error on table '%s'", errors.RFCCodeText("Lightning:Restore:ErrResolveDuplicateRows"))
```
Comment (D3Hunter) [inline br/pkg/lightning/common/errors.go:97]: do `make errdoc`

Comment (ForwardStar) [reply br/pkg/lightning/common/errors.go:97]: Done otherwise ``check_dev`` test would fail.

Comment (D3Hunter) [reply br/pkg/lightning/common/errors.go:97]: i remember a xml file will be changed

Comment (ForwardStar) [reply br/pkg/lightning/common/errors.go:97]: I think the changed file is ``errors.toml``.

**Review by D3Hunter — APPROVED** [review]

**Review by gozssky — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Comment by D3Hunter** [comment]
ci pass, merged
https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/12870/pipeline
