### PR TITLE
ddl: fix creating expression in clustered index table

### LINKED ISSUE #26371: generate index with ERROR 1072 (42000)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> show create table sbtest5\G
*************************** 1. row ***************************
       Table: sbtest5
Create Table: CREATE TABLE `sbtest5` (
  `id` int(10) unsigned NOT NULL,
  `k` int(10) unsigned NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  `kv` bigint(20) GENERATED ALWAYS AS (`k` + 1) VIRTUAL,
  `kv1` bigint(20) GENERATED ALWAYS AS (right(`k`, 1)) VIRTUAL,
  `kv3` bigint(20) GENERATED ALWAYS AS (`k` % power(10, 2) * power(10, length(`k`) - 2) + `k` div power(10, 2)) VIRTUAL,
  PRIMARY KEY (`id`,`k`,`c`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_k_c_pad` (`k`,`c`,`pad`),
  KEY `idx_kv` (`kv`),
  KEY `idx_kv1` (`kv1`),
  KEY `idx_kv3` (`kv3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin /*T![auto_id_cache] AUTO_ID_CACHE=4 */
1 row in set (0.00 sec)

mysql> CREATE INDEX idx_test ON sbtest5 ((lower(k)));
ERROR 1072 (42000): column does not exist: _v$_idx_test_0

### 2. What did you expect to see? (Required)
create index success
### 3. What did you see instead (Required)
ERROR 1072 (42000): column does not exist: _v$_idx_test_0

### 4. What is your TiDB version? (Required)

Release Version: v5.0.3
Edition: Community
Git Commit Hash: 0b5c1546892b3b4195485303c70f30492c4b1d71
Git Branch: heads/refs/tags/v5.0.3
UTC Build Time: 2021-07-01 15:45:42
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #26371 

Problem Summary:
When checking the length of the expression index, we should consider the new hidden columns.

### What is changed and how it works?

Use a new variable `finalColumns` to hold the previous columns and the new hidden columns.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by lysu — APPROVED** [review]

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -5140,13 +5140,16 @@ func (d *ddl) CreateIndex(ctx sessionctx.Context, ti ast.Ident, keyType ast.Inde
 		return errors.Trace(err)
 	}
 
+	finnalColumns := make([]*model.ColumnInfo, len(tblInfo.Columns), len(tblInfo.Columns) + len(hiddenCols))
```
Comment (lysu) [inline ddl/ddl_api.go:5143]: maybe a typo finnal should be final~

**Review by bb7133 — APPROVED** [review]
