### PR TITLE
*: fix a bug occurred when insert into time column

### LINKED ISSUE #6424: inconsistent behavior with MySQL when insert into time col
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
create table t(a time(6));
insert into t value(20070219173709.055870);
insert into t value('20070219173709.055870');
select *  from t;
```


2. What did you expect to see?
``` sql
mysql(127.0.0.1)> select * from t;
+-----------------+
| a               |
+-----------------+
| 17:37:09.055870 |
| 17:37:09.055870 |
+-----------------+
1 row in set (0.00 sec)
```


3. What did you see instead?
``` sql
tidb(127.0.0.1)> insert into t value(20070219173709.055870);
ERROR 1105 (HY000): cannot convert datum from bigint to type time.
tidb(127.0.0.1)> select * from t;
+-----------------+
| a               |
+-----------------+
| 17:37:09.000000 |
+-----------------+
1 row in set (0.00 sec)
```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
``` sql
tidb(127.0.0.1)> select tidb_version();

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.0.0-rc.3-12-gb6b708aa4
Git Commit Hash: b6b708aa4369f89147a3f9a31a9daff38c489999
Git Branch: master
UTC Build Time: 2018-04-03 08:14:49
GoVersion: go version go1.9.5 linux/amd64
TiKV Min Version: 1.1.0-dev.2 |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by XuHuaiyu**
Fix #6424 
1. `insert into t(time_col) value('20000101121212.123456')`
Before this commit,
TiDB will set the `fsp` of value to be `DefaultFsp(0)` during processing.
This commit gets fsp from the string instead of setting a default fsp.
2. `insert into t(time_col) value(20000101121212,123456)`
Before this commit,
TiDB will throw an error when converting int/ double/ decimal to duration.
This commit will first convert int/ double/ decimal into string,
and then convert the string to duration.
PTAL @zz-jason @tiancaiamao

### CODE REVIEW

File: executor/write_test.go [hunk 1]
```diff
@@ -213,6 +213,15 @@ func (s *testSuite) TestInsert(c *C) {
 	tk.MustQuery("select * from test use index (id) where id = 2").Check(testkit.Rows("2 2"))
 	tk.MustExec("insert into test values(2, 3)")
 	tk.MustQuery("select * from test use index (id) where id = 2").Check(testkit.Rows("2 2", "2 3"))
+
+	// issue 6424
+	tk.MustExec("drop table if exists t")
```
Comment (zz-jason) [inline executor/write_test.go]: In MySQL 5.7.22:
```sql
MySQL(localhost:3306) > drop table t;
Query OK, 0 rows affected (0.04 sec)

MySQL(localhost:3306) > create table t(a time(6));
Query OK, 0 rows affected (0.03 sec)

MySQL(localhost:3306) > insert into t value('20070219173709.055870'), ('20070219173709.055'), ('-20070219173709.055870'), ('20070219173709.055870123');
Query OK, 4 rows affected, 4 warnings (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 4

MySQL(localhost:3306) > show warnings;
+-------+------+--------------------------------------------------------------------------+
| Level | Code | Message                                                                  |
+-------+------+--------------------------------------------------------------------------+
| Note  | 1292 | Incorrect time value: '20070219173709.055870' for column 'a' at row 1    |
| Note  | 1292 | Incorrect time value: '20070219173709.055' for column 'a' at row 2       |
| Note  | 1292 | Incorrect time value: '-20070219173709.055870' for column 'a' at row 3   |
| Note  | 1292 | Incorrect time value: '20070219173709.055870123' for column 'a' at row 4 |
+-------+------+--------------------------------------------------------------------------+
4 rows in set (0.00 sec)

MySQL(localhost:3306) > select * from t;
+-----------------+
| a               |
+-----------------+
| 17:37:09.055870 |
| 17:37:09.055000 |
| 17:37:09.055870 |
| 17:37:09.055870 |
+-----------------+
4 rows in set (0.01 sec)

MySQL(localhost:3306) > truncate table t;
Query OK, 0 rows affected (0.02 sec)

MySQL(localhost:3306) > insert into t value(20070219173709.055870), (20070219173709.055), (-20070219173709.055870), (20070219173709.055870123);
ERROR 1292 (22007): Incorrect time value: '-20070219173709.055870' for column 'a' at row 3
MySQL(localhost:3306) > select * from t;
Empty set (0.00 sec)
```

**Comment by shenli** [comment]
Could you add more description for the bug?

File: types/convert_test.go [hunk 2]
```diff
@@ -618,12 +618,12 @@ func (s *testTypeConvertSuite) TestConvert(c *C) {
 	signedAccept(c, mysql.TypeDuration, "10:11:12", "10:11:12")
 	signedAccept(c, mysql.TypeDuration, ZeroDatetime, "00:00:00")
 	signedAccept(c, mysql.TypeDuration, ZeroDuration, "00:00:00")
+	signedAccept(c, mysql.TypeDuration, 0, "00:00:00")
 
 	signedDeny(c, mysql.TypeDate, "2012-08-x", "0000-00-00")
 	signedDeny(c, mysql.TypeDatetime, "2012-08-x", "0000-00-00 00:00:00")
 	signedDeny(c, mysql.TypeTimestamp, "2012-08-x", "0000-00-00 00:00:00")
 	signedDeny(c, mysql.TypeDuration, "2012-08-x", "00:00:00")
-	signedDeny(c, mysql.TypeDuration, 0, "<nil>")
```
Comment (zhexuany) [inline types/convert_test.go]: why remove this test?

File: types/datum.go [hunk 3]
```diff
@@ -1009,6 +1009,19 @@ func (d *Datum) convertToMysqlDuration(sc *stmtctx.StatementContext, target *Fie
 		if err != nil {
 			return ret, errors.Trace(err)
 		}
+	case KindInt64, KindFloat32, KindFloat64, KindMysqlDecimal:
+		// TODO: We need a ParseDurationFromNum to avoid the cost of converting a num to string.
```
Comment (zhexuany) [inline types/datum.go]: maybe we need create a lira issue rather than adding a "TODO". People are all joking about "TODO" is just another expression of "never do". lol

File: types/time.go [hunk 4]
```diff
@@ -962,66 +959,63 @@ func ParseDuration(str string, fsp int) (Duration, error) {
...
-			} else if len(str) == 2 {
-				// SS
-				_, err = fmt.Sscanf(str, "%2d", &second)
-			} else if len(str) == 1 {
-				// 0S
-				_, err = fmt.Sscanf(str, "%1d", &second)
-			} else {
-				// Maybe only contains date.
+			switch len(integeralPart) {
+			case 7: // HHHMMSS
```
Comment (zhexuany) [inline types/time.go]: alternative way is using a map whose key is int and value is string. 

Suppose such may is `timeFmt`, then `timeFmt[7]` could just return `"%3d%2d%2d"`

File: types/convert_test.go (hunk 2 above)
Comment (XuHuaiyu) [reply types/convert_test.go]: It's moved to line 621, which is consistent with MySQL now.

File: types/time.go (hunk 4 above)
Comment (XuHuaiyu) [reply types/time.go]: Yes, but it seems that every element in `timeFmt` will only be used in this function now.
I'm not sure whether it's better than using switch-case.

File: types/datum.go (hunk 3 above)
Comment (XuHuaiyu) [reply types/datum.go]: Ok, I'll create a jira issue after this PR is merged.

**Comment by XuHuaiyu** [comment]
PTAL @zhexuany @zz-jason

File: types/time.go (hunk 4 above)
Comment (zz-jason) [reply types/time.go]: map access is slower than a switch case, I prefer not to use map.

**Comment by zz-jason** [comment]
LGTM

File: types/time.go [hunk 5]
```diff
@@ -377,6 +377,17 @@ func (t Time) RoundFrac(sc *stmtctx.StatementContext, fsp int) (Time, error) {
 	return Time{Time: nt, Type: t.Type, Fsp: fsp}, nil
 }
 
+// GetFsp gets the fsp of a string.
+func GetFsp(s string) (fsp int) {
+	fsp = len(s) - strings.Index(s, ".") - 1
```
Comment (tiancaiamao) [inline types/time.go]: You may like `strings.LastIndex`

File: types/time.go [hunk 6]
```diff
@@ -1224,12 +1218,12 @@ func parseTime(sc *stmtctx.StatementContext, str string, tp byte, fsp int, isFlo
 
 // ParseDatetime is a helper function wrapping ParseTime with datetime type and default fsp.
 func ParseDatetime(sc *stmtctx.StatementContext, str string) (Time, error) {
-	return ParseTime(sc, str, mysql.TypeDatetime, DefaultFsp)
+	return ParseTime(sc, str, mysql.TypeDatetime, GetFsp(str))
```
Comment (tiancaiamao) [inline types/time.go]: Is this line the whole change of this PR?

File: types/convert_test.go (hunk 2 above)
Comment (zhexuany) [reply types/convert_test.go]: gotcha

File: types/time_test.go [hunk 7]
```diff
@@ -53,7 +53,7 @@ func (s *testTimeSuite) TestDateTime(c *C) {
 		{"121231113045", "2012-12-31 11:30:45"},
 		{"2012-02-29", "2012-02-29 00:00:00"},
 		{"00-00-00", "0000-00-00 00:00:00"},
-		{"00-00-00 00:00:00.123", "2000-00-00 00:00:00"},
+		{"00-00-00 00:00:00.123", "2000-00-00 00:00:00.123"},
```
Comment (tiancaiamao) [inline types/time_test.go]:
```
mysql> create table t2 (t datetime);
Query OK, 0 rows affected (0.23 sec)

mysql> insert into t2 values ('00-00-00 00:00:00.123');
Query OK, 1 row affected (0.01 sec)

mysql> select * from t2;
+---------------------+
| t                   |
+---------------------+
| 2000-00-00 00:00:00 |
+---------------------+
1 row in set (0.00 sec)
```

Check this one

**Comment by tiancaiamao** [comment]
Maybe we should not determine fsp by the string itself, the context may affect, and we should take truncate into consideration too. @XuHuaiyu

File: types/time_test.go (hunk 7 above)
Comment (XuHuaiyu) [reply types/time_test.go]: In MySQL:
``` sql
mysql(127.0.0.1)> create table t(a datetime);
Query OK, 0 rows affected (0.04 sec)

mysql(127.0.0.1)> insert into t value("00-00-00 00:00:00.123");
ERROR 1292 (22007): Incorrect datetime value: '00-00-00 00:00:00.123' for column 'a' at row 1

mysql(127.0.0.1)>  insert into t value("2001-10-10 12:12:12.12345");
Query OK, 1 row affected (0.00 sec)

mysql(127.0.0.1)> select * from t;

+---------------------+
| a                   |
+---------------------+
| 2001-10-10 12:12:12 |
+---------------------+
1 row in set (0.01 sec)
```
In TiDB:
``` sql
tidb(127.0.0.1)> create table t(a datetime);
Query OK, 0 rows affected (0.01 sec)

tidb(127.0.0.1)> insert into t values ('00-00-00 00:00:00.123');
ERROR 1292 (22007): Incorrect datetime value: '2000-00-00'

tidb(127.0.0.1)> insert into t value("2001-10-10 12:12:12.12345");
Query OK, 1 row affected (0.10 sec)

tidb(127.0.0.1)> select * from t;
+---------------------+
| a                   |
+---------------------+
| 2001-10-10 12:12:12 |
+---------------------+
1 row in set (0.01 sec)
```

File: types/time.go (hunk 6 above)
Comment (XuHuaiyu) [reply types/time.go]: And this cast branch:
https://github.com/pingcap/tidb/pull/6451/files#diff-88da33c1e3eaab083f98c6e9e260373aR1012

**Comment by XuHuaiyu** [comment]
fixed, 
PTAL @tiancaiamao
