### PR TITLE
br: enable parallel restore

### LINKED ISSUE #58725: br: use dedicated checkpoint table for each br task
## Enhancement

separate out the checkpoint table so can enable multiple restore task execution. Right now there is only one set of checkpoint tables per cluster, it doesn't work if more than one restore happens at the same time

### PR DESCRIPTION
**Pull request by Tristan1900**
### What problem does this PR solve?

Issue Number: close #58725

Problem Summary:

### What changed and how does it work?

1. To allow parallel restore tasks, we introduced a restore id for each task, the id is allocated by an internal TiDB registry table and it's monotonic increasing, the table is in mysql db called `tide_restore_registry`
2. We add this restore id to the suffix of checkpoint DB and storage, so each task can have their own checkpoint and not messing with others
3. For each new task, it registers itself to the registry, and make sure tables it's going to restore is not overlapping with restore task that has a smaller restore id. If there is conflict it will abort the restore and show the reason.
4. After finishing the restore, it will unregister itself from the registry
5. In case of failure, for a graceful one, it will change the task status in registry from running to pause, so next time user can retry and reusing the checkpoint. If disaster happens like OOM that BR didn't get a chance to pause, user needs to manually clean it up. We have a heartbeat mechanism that update the restore task timestamp, it can provide some hints whether this task is active or orphaned.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/task/restore.go [hunk 1]
```diff
@@ -822,38 +835,92 @@ func RunRestore(c context.Context, g glue.Glue, cmdName string, cfg *RestoreConf
...
 	if restoreError != nil {
+		// if err happens at register phase no restoreID will be generated and default is 0.
+		if cfg.RestoreID == 0 {
+			return errors.Trace(restoreError)
+		}
+		// if checkpoint is not persisted, let's just unregister the task since we don't need it
+		if hasCheckpointPersisted(c, cfg) {
+			log.Info("pausing restore task from registry",
+				zap.Uint64("restoreId", cfg.RestoreID), zap.Error(restoreError))
+			if err := restoreRegistry.PauseTask(c, cfg.RestoreID); err != nil {
```
Comment (Leavrth) [inline br/pkg/task/restore.go:846]: What if BR is killed because OOM? BR might not have chance to pause the task.

File: br/pkg/registry/registration.go [hunk 2]
```diff
@@ -0,0 +1,523 @@
+// Copyright 2025 PingCAP, Inc.
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply br/pkg/registry/registration.go:1]: let me see what I can do, it's calling sql so not sure unit test can easily cover that

File: br/pkg/registry/registration.go [hunk 3]
```diff
@@ -0,0 +1,523 @@
...
+		if foundUUID == operationUUID {
+			log.Info("successfully resumed existing registration by this process",
+				zap.Uint64("restore_id", taskID),
+				zap.String("uuid", operationUUID),
+				zap.Strings("filters", info.FilterStrings))
+			return taskID, nil
+		}
+		// task exists but was either created by another process or has been running
+		// check if it's in running state
+		runningRows, _, err := execCtx.ExecRestrictedSQL(
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply br/pkg/registry/registration.go:258]: ah yes you are right

File: br/pkg/registry/registration.go [hunk 4]
```diff
@@ -0,0 +1,523 @@
...
+	log.Info("ensured restore registration table exists",
+		zap.String("db", RegistrationDBName),
+		zap.String("table", RegistrationTableName))
+
+	return nil
+}
+
+// ResumeOrCreateRegistration first looks for an existing registration with the given parameters.
+// If found and paused, it tries to resume it. Otherwise, it creates a new registration.
+func (r *Registry) ResumeOrCreateRegistration(ctx context.Context, info RegistrationInfo) (uint64, error) {
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply br/pkg/registry/registration.go:201]: That was my first try, maybe we can discuss offline cuz based on my observation `ExecRestrictedSQL` doesn't work with nested transaction, it appears to be a single transaction for admin purpose. But maybe I'm wrong.

File: br/pkg/task/restore.go (hunk 1 above)
Comment (Tristan1900) [reply br/pkg/task/restore.go:846]: good call, let me think about that

File: br/pkg/registry/registration.go [hunk 5]
```diff
@@ -0,0 +1,558 @@
...
+	"github.com/pingcap/tidb/br/pkg/utils"
+	"github.com/pingcap/tidb/pkg/domain"
+	"github.com/pingcap/tidb/pkg/kv"
+	"github.com/pingcap/tidb/pkg/util/sqlexec"
+	filter "github.com/pingcap/tidb/pkg/util/table-filter"
+	"go.uber.org/zap"
+)
+
+const (
+	RegistrationDBName    string = utils.TemporaryDBNamePrefix + "Restore_Registration_DB"
```
Comment (BornChanger) [inline br/pkg/registry/registration.go:37]: why not keep it in mysql db since the records might last for long?

File: br/pkg/task/common.go [hunk 6]
```diff
@@ -663,11 +663,14 @@ func (cfg *Config) ParseFromFlags(flags *pflag.FlagSet) error {
 				Schema: db,
 				Name:   tbl,
 			})
+			cfg.FilterStr = []string{fmt.Sprintf("`%s`.`%s`", db, tbl)}
 		} else {
 			cfg.TableFilter = filter.NewSchemasFilter(db)
+			cfg.FilterStr = []string{fmt.Sprintf("`%s`.*", db)}
```
[the remark this answers is not in the document]
Comment (Tristan1900) [reply br/pkg/task/common.go:669]: that should be escaped and filter can identify an escaped * and a wildcard *.

File: br/pkg/registry/registration.go (hunk 5 above)
Comment (Tristan1900) [reply br/pkg/registry/registration.go]: user can always manually clean up, there is nothing to prevent them deleting it. And I have a heartbeat mechanism to publish heartbeat to each task, suggesting the liveness of those tasks, so user can have confidence when deleting it. 


Update: actually it's not possible to make race condition free when doing concurrent create and delete. The idea of making a long term table is better. Thanks for the suggestion!

File: pkg/session/bootstrap.go [hunk 7]
```diff
@@ -730,6 +730,29 @@ const (
...
+		id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
+		filter_strings TEXT NOT NULL,
+		filter_hash VARCHAR(64) NOT NULL,
+		start_ts BIGINT UNSIGNED NOT NULL,
+		restored_ts BIGINT UNSIGNED NOT NULL,
+		upstream_cluster_id BIGINT UNSIGNED,
+		with_sys_table BOOLEAN NOT NULL DEFAULT TRUE,
+		status VARCHAR(20) NOT NULL DEFAULT 'running',
+		cmd TEXT,
+		start_timestamp BIGINT UNSIGNED NOT NULL,
```
Comment (benmeadowcroft) [inline pkg/session/bootstrap.go]: From a user perspective I find the column naming confusing.

First, it is not clear how this is different from `start_ts` referenced above. Can you clarifying the naming here? If they are used for different things, is the a better name that can be used to make it more obvious? Or is this just intended to offer different levels of precision (if so why the same data type)?

Second, the suffix of the column name `_timestamp` implies this is a`TIMESTAMP` while the type is specified as `BIGINT`. This is confusing and inconsistent.

File: pkg/session/bootstrap.go [hunk 8]
```diff
@@ -730,6 +730,29 @@ const (
 		update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 		PRIMARY KEY (restore_id, restored_ts, upstream_cluster_id, segment_id));`
 
+	// CreateRestoreRegistryTable is a table that tracks active restore tasks to prevent conflicts.
+	CreateRestoreRegistryTable = `CREATE TABLE IF NOT EXISTS mysql.tidb_restore_registry (
```
Comment (benmeadowcroft) [inline pkg/session/bootstrap.go:734]: Please use consistent suffixes for `_time` and `_ts` and consistent data types for the desired level of precision.

**Review by benmeadowcroft — CHANGES_REQUESTED** [review]

File: pkg/session/bootstrap.go (hunk 7 above)
Comment (Tristan1900) [reply pkg/session/bootstrap.go]: thanks for taking a look!
yes you are absolutely right the name is confusing, let me rename the latter one.

**Review by windtalker — APPROVED** [review]
expression/executor part lgtm

**Review by benmeadowcroft — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]

**Review by winoros — APPROVED** [review]

**Comment by winoros** [comment]
for planner part
