### PR TITLE
planner: fix stat for CTE

### LINKED ISSUE #26260: enhance estimate rows on recursive CTE
running tpc-ds query 78 against TiDB, 1GB dataset, the query out of memory when the @@tidb_mem_quota_query=1GB, need to increase to @@tidb_mem_quota_query to make the query successful.

cause analyze: currently TiDB hard code the estimated rows for  recursive CTE as 1, causing poor join method.

Enhance request: optimizer should provide accurate estimate rows for the CTE expression.

```
    id                                                                  task        estRows     operator info
            │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ └─CTEFullScan_537         root        1           CTE:cs_ui, data:CTE_0

```

```
with cs_ui as
 (select cs_item_sk
        ,sum(cs_ext_list_price) as sale,sum(cr_refunded_cash+cr_reversed_charge+cr_store_credit) as refund
  from catalog_sales
      ,catalog_returns
  where cs_item_sk = cr_item_sk
    and cs_order_number = cr_order_number
  group by cs_item_sk
  having sum(cs_ext_list_price)>2*sum(cr_refunded_cash+cr_reversed_charge+cr_store_credit)),
cross_sales as
 (select i_product_name product_name
     ,i_item_sk item_sk
     ,s_store_name store_name
     ,s_zip store_zip
     ,ad1.ca_street_number b_street_number
     ,ad1.ca_street_name b_street_name
     ,ad1.ca_city b_city
     ,ad1.ca_zip b_zip
     ,ad2.ca_street_number c_street_number
     ,ad2.ca_street_name c_street_name
     ,ad2.ca_city c_city
     ,ad2.ca_zip c_zip
     ,d1.d_year as syear
     ,d2.d_year as fsyear
     ,d3.d_year s2year
     ,count(*) cnt
     ,sum(ss_wholesale_cost) s1
     ,sum(ss_list_price) s2
     ,sum(ss_coupon_amt) s3
  FROM   store_sales
        ,store_returns
        ,cs_ui
        ,date_dim d1
        ,date_dim d2
        ,date_dim d3
        ,store
        ,customer
        ,customer_demographics cd1
        ,customer_demographics cd2
        ,promotion
        ,household_demographics hd1
        ,household_demographics hd2
        ,customer_address ad1
        ,customer_address ad2
        ,income_band ib1
        ,income_band ib2
        ,item
  WHERE  ss_store_sk = s_store_sk AND
         ss_sold_date_sk = d1.d_date_sk AND
         ss_customer_sk = c_customer_sk AND
         ss_cdemo_sk= cd1.cd_demo_sk AND
         ss_hdemo_sk = hd1.hd_demo_sk AND
         ss_addr_sk = ad1.ca_address_sk and
         ss_item_sk = i_item_sk and
         ss_item_sk = sr_item_sk and
         ss_ticket_number = sr_ticket_number and
         ss_item_sk = cs_ui.cs_item_sk and
         c_current_cdemo_sk = cd2.cd_demo_sk AND
         c_current_hdemo_sk = hd2.hd_demo_sk AND
         c_current_addr_sk = ad2.ca_address_sk and
         c_first_sales_date_sk = d2.d_date_sk and
         c_first_shipto_date_sk = d3.d_date_sk and
         ss_promo_sk = p_promo_sk and
         hd1.hd_income_band_sk = ib1.ib_income_band_sk and
         hd2.hd_income_band_sk = ib2.ib_income_band_sk and
         cd1.cd_marital_status <> cd2.cd_marital_status and
         i_color in ('maroon','burnished','dim','steel','navajo','chocolate') and
         i_current_price between 35 and 35 + 10 and
         i_current_price between 35 + 1 and 35 + 15
group by i_product_name
       ,i_item_sk
       ,s_store_name
       ,s_zip
       ,ad1.ca_street_number
       ,ad1.ca_street_name
       ,ad1.ca_city
       ,ad1.ca_zip
       ,ad2.ca_street_number
       ,ad2.ca_street_name
       ,ad2.ca_city
       ,ad2.ca_zip
       ,d1.d_year
       ,d2.d_year
       ,d3.d_year
)
select cs1.product_name
     ,cs1.store_name
     ,cs1.store_zip
     ,cs1.b_street_number
     ,cs1.b_street_name
     ,cs1.b_city
     ,cs1.b_zip
     ,cs1.c_street_number
     ,cs1.c_street_name
     ,cs1.c_city
     ,cs1.c_zip
     ,cs1.syear
     ,cs1.cnt
     ,cs1.s1 as s11
     ,cs1.s2 as s21
     ,cs1.s3 as s31
     ,cs2.s1 as s12
     ,cs2.s2 as s22
     ,cs2.s3 as s32
     ,cs2.syear
     ,cs2.cnt
from cross_sales cs1,cross_sales cs2
where cs1.item_sk=cs2.item_sk and
     cs1.syear = 2000 and
     cs2.syear = 2000 + 1 and
     cs2.cnt <= cs1.cnt and
     cs1.store_name = cs2.store_name and
     cs1.store_zip = cs2.store_zip
order by cs1.product_name
       ,cs1.store_name
       ,cs2.cnt
       ,cs1.s1
       ,cs2.s1;

	id                                                              	task     	estRows 	operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     	actRows	execution info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	memory   	disk
	Sort_56                                                         	root     	0.64    	tpcds1.item.i_product_name, tpcds1.store.s_store_name, Column#387, Column#369, Column#388                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	0      	time:10s, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	0 Bytes  	0 Bytes
	└─Projection_58                                                 	root     	0.64    	tpcds1.item.i_product_name, tpcds1.store.s_store_name, tpcds1.store.s_zip, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_zip, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_zip, tpcds1.date_dim.d_year, Column#368, Column#369, Column#370, Column#371, Column#388, Column#389, Column#390, tpcds1.date_dim.d_year, Column#387                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	0      	time:10s, loops:1, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	16.6 KB  	N/A
	  └─HashJoin_59                                                 	root     	0.64    	inner join, equal:[eq(tpcds1.item.i_item_sk, tpcds1.item.i_item_sk) eq(tpcds1.store.s_store_name, tpcds1.store.s_store_name) eq(tpcds1.store.s_zip, tpcds1.store.s_zip)], other cond:le(Column#387, Column#368)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	0      	time:10s, loops:1, build_hash_table:{total:10.3s, fetch:10.3s, build:0s}                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	0 Bytes  	0 Bytes
	    ├─Selection_61                                              	root     	0.80    	eq(tpcds1.date_dim.d_year, 2000), not(isnull(Column#368)), not(isnull(tpcds1.item.i_item_sk)), not(isnull(tpcds1.store.s_store_name)), not(isnull(tpcds1.store.s_zip))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	0      	time:10s, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	12.7 KB  	N/A
	    │ └─CTEFullScan_581                                         	root     	1       	CTE:cs1, data:CTE_1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	0      	time:10s, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	0 Bytes  	0 Bytes
	    └─Selection_582                                             	root     	0.80    	eq(tpcds1.date_dim.d_year, 2001), not(isnull(Column#387)), not(isnull(tpcds1.item.i_item_sk)), not(isnull(tpcds1.store.s_store_name)), not(isnull(tpcds1.store.s_zip))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	8      	time:10.3s, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	12.7 KB  	N/A
	      └─CTEFullScan_667                                         	root     	1       	CTE:cs2, data:CTE_1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	36     	time:10.3s, loops:3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	0 Bytes  	71.9 KB
	CTE_1                                                           	root     	1       	Non-Recursive CTE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 	0      	time:10s, loops:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	0 Bytes  	0 Bytes
	└─Projection_148                                                	root     	6.19    	tpcds1.item.i_product_name, tpcds1.item.i_item_sk, tpcds1.store.s_store_name, tpcds1.store.s_zip, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_zip, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_zip, tpcds1.date_dim.d_year, tpcds1.date_dim.d_year, tpcds1.date_dim.d_year, Column#349, Column#350, Column#351, Column#352                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	95     	time:10.3s, loops:7, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	12.7 KB  	N/A
	  └─HashAgg_149                                                 	root     	6.19    	group by:tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_zip, tpcds1.customer_address.ca_zip, tpcds1.date_dim.d_year, tpcds1.date_dim.d_year, tpcds1.date_dim.d_year, tpcds1.item.i_item_sk, tpcds1.item.i_product_name, tpcds1.store.s_store_name, tpcds1.store.s_zip, funcs:count(1)->Column#349, funcs:sum(tpcds1.store_sales.ss_wholesale_cost)->Column#350, funcs:sum(tpcds1.store_sales.ss_list_price)->Column#351, funcs:sum(tpcds1.store_sales.ss_coupon_amt)->Column#352, funcs:firstrow(tpcds1.date_dim.d_year)->tpcds1.date_dim.d_year, funcs:firstrow(tpcds1.date_dim.d_year)->tpcds1.date_dim.d_year, funcs:firstrow(tpcds1.date_dim.d_year)->tpcds1.date_dim.d_year, funcs:firstrow(tpcds1.store.s_store_name)->tpcds1.store.s_store_name, funcs:firstrow(tpcds1.store.s_zip)->tpcds1.store.s_zip, funcs:firstrow(tpcds1.customer_address.ca_street_number)->tpcds1.customer_address.ca_street_number, funcs:firstrow(tpcds1.customer_address.ca_street_name)->tpcds1.customer_address.ca_street_name, funcs:firstrow(tpcds1.customer_address.ca_city)->tpcds1.customer_address.ca_city, funcs:firstrow(tpcds1.customer_address.ca_zip)->tpcds1.customer_address.ca_zip, funcs:firstrow(tpcds1.customer_address.ca_street_number)->tpcds1.customer_address.ca_street_number, funcs:firstrow(tpcds1.customer_address.ca_street_name)->tpcds1.customer_address.ca_street_name, funcs:firstrow(tpcds1.customer_address.ca_city)->tpcds1.customer_address.ca_city, funcs:firstrow(tpcds1.customer_address.ca_zip)->tpcds1.customer_address.ca_zip, funcs:firstrow(tpcds1.item.i_item_sk)->tpcds1.item.i_item_sk, funcs:firstrow(tpcds1.item.i_product_name)->tpcds1.item.i_product_name	95     	time:10.3s, loops:7, partial_worker:{wall_time:10.314044566s, concurrency:5, task_num:1, tot_wait:51.566839361s, tot_exec:565.827µs, tot_time:51.567450959s, max:9.999137835s, p95:9.999137835s}, final_worker:{wall_time:10.315517321s, concurrency:5, task_num:5, tot_wait:51.56998602s, tot_exec:5.371427ms, tot_time:51.575364623s, max:9.999189014s, p95:9.999189014s}                                                                                                                                                                  	127.9 KB 	N/A
	    └─Projection_150                                            	root     	6.19    	tpcds1.store_sales.ss_wholesale_cost, tpcds1.store_sales.ss_list_price, tpcds1.store_sales.ss_coupon_amt, tpcds1.date_dim.d_year, tpcds1.date_dim.d_year, tpcds1.date_dim.d_year, tpcds1.store.s_store_name, tpcds1.store.s_zip, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_zip, tpcds1.customer_address.ca_street_number, tpcds1.customer_address.ca_street_name, tpcds1.customer_address.ca_city, tpcds1.customer_address.ca_zip, tpcds1.item.i_item_sk, tpcds1.item.i_product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	95     	time:10.3s, loops:3, Concurrency:OFF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	12.4 KB  	N/A
	      └─IndexJoin_157                                           	root     	6.19    	inner join, inner:TableReader_153, outer key:tpcds1.customer.c_current_cdemo_sk, inner key:tpcds1.customer_demographics.cd_demo_sk, equal cond:eq(tpcds1.customer.c_current_cdemo_sk, tpcds1.customer_demographics.cd_demo_sk), other cond:ne(tpcds1.customer_demographics.cd_marital_status, tpcds1.customer_demographics.cd_marital_status)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     	95     	time:10.3s, loops:3, inner:{total:3.09ms, concurrency:5, task:2, construct:454.6µs, fetch:2.59ms, build:44.5µs}, probe:432.9µs                                                                                                                                                                                                                                                                                                                                                                                                             	0 Bytes  	N/A
	        ├─IndexJoin_170                                         	root     	6.19    	inner join, inner:TableReader_166, outer key:tpcds1.store_sales.ss_cdemo_sk, inner key:tpcds1.customer_demographics.cd_demo_sk, equal cond:eq(tpcds1.store_sales.ss_cdemo_sk, tpcds1.customer_demographics.cd_demo_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	120    	time:20.3s, loops:5, inner:{total:3.75ms, concurrency:5, task:2, construct:638.6µs, fetch:3.06ms, build:43.4µs}, probe:148.2µs                                                                                                                                                                                                                                                                                                                                                                                                             	0 Bytes  	N/A
	        │ ├─IndexJoin_180                                       	root     	6.19    	inner join, inner:IndexReader_179, outer key:tpcds1.store_sales.ss_item_sk, tpcds1.store_sales.ss_ticket_number, inner key:tpcds1.store_returns.sr_item_sk, tpcds1.store_returns.sr_ticket_number, equal cond:eq(tpcds1.store_sales.ss_item_sk, tpcds1.store_returns.sr_item_sk), eq(tpcds1.store_sales.ss_ticket_number, tpcds1.store_returns.sr_ticket_number)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	160    	time:20.3s, loops:5, inner:{total:264.7ms, concurrency:5, task:8, construct:2.14ms, fetch:262.5ms, build:94.5µs}, probe:670.9µs                                                                                                                                                                                                                                                                                                                                                                                                             	1.13 MB  	N/A
	        │ │ ├─IndexJoin_307                                     	root     	6.19    	inner join, inner:TableReader_304, outer key:tpcds1.customer.c_first_shipto_date_sk, inner key:tpcds1.date_dim.d_date_sk, equal cond:eq(tpcds1.customer.c_first_shipto_date_sk, tpcds1.date_dim.d_date_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	1707   	time:20.3s, loops:11, inner:{total:363.5ms, concurrency:5, task:8, construct:1.68ms, fetch:361.2ms, build:577.2µs}, probe:2.05ms                                                                                                                                                                                                                                                                                                                                                                                                             	1.13 MB  	N/A
	        │ │ │ ├─IndexJoin_318                                   	root     	6.19    	inner join, inner:TableReader_315, outer key:tpcds1.customer.c_first_sales_date_sk, inner key:tpcds1.date_dim.d_date_sk, equal cond:eq(tpcds1.customer.c_first_sales_date_sk, tpcds1.date_dim.d_date_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	1707   	time:20.3s, loops:11, inner:{total:273.2ms, concurrency:5, task:8, construct:1.83ms, fetch:270.8ms, build:555.7µs}, probe:2.06ms                                                                                                                                                                                                                                                                                                                                                                                                             	1.13 MB  	N/A
	        │ │ │ │ ├─IndexJoin_329                                 	root     	6.19    	inner join, inner:TableReader_326, outer key:tpcds1.customer.c_current_addr_sk, inner key:tpcds1.customer_address.ca_address_sk, equal cond:eq(tpcds1.customer.c_current_addr_sk, tpcds1.customer_address.ca_address_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	1707   	time:20.3s, loops:11, inner:{total:380.8ms, concurrency:5, task:8, construct:1.78ms, fetch:378.4ms, build:555.4µs}, probe:2.1ms                                                                                                                                                                                                                                                                                                                                                                                                              	1.13 MB  	N/A
	        │ │ │ │ │ ├─IndexJoin_340                               	root     	6.19    	inner join, inner:TableReader_337, outer key:tpcds1.household_demographics.hd_income_band_sk, inner key:tpcds1.income_band.ib_income_band_sk, equal cond:eq(tpcds1.household_demographics.hd_income_band_sk, tpcds1.income_band.ib_income_band_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	1707   	time:20.3s, loops:11, inner:{total:335ms, concurrency:5, task:8, construct:1.69ms, fetch:333.2ms, build:87.1µs}, probe:1.89ms                                                                                                                                                                                                                                                                                                                                                                                                                	983.8 KB 	N/A
	        │ │ │ │ │ │ ├─IndexJoin_353                             	root     	6.19    	inner join, inner:TableReader_349, outer key:tpcds1.customer.c_current_hdemo_sk, inner key:tpcds1.household_demographics.hd_demo_sk, equal cond:eq(tpcds1.customer.c_current_hdemo_sk, tpcds1.household_demographics.hd_demo_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	1707   	time:20.3s, loops:11, inner:{total:332.4ms, concurrency:5, task:8, construct:1.5ms, fetch:330.3ms, build:627.5µs}, probe:1.84ms                                                                                                                                                                                                                                                                                                                                                                                                              	1008.5 KB	N/A
	        │ │ │ │ │ │ │ ├─IndexJoin_366                           	root     	6.19    	inner join, inner:TableReader_362, outer key:tpcds1.store_sales.ss_customer_sk, inner key:tpcds1.customer.c_customer_sk, equal cond:eq(tpcds1.store_sales.ss_customer_sk, tpcds1.customer.c_customer_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	2161   	time:20.3s, loops:11, inner:{total:613.7ms, concurrency:5, task:9, construct:1.96ms, fetch:610.9ms, build:826.4µs}, probe:2.02ms                                                                                                                                                                                                                                                                                                                                                                                                             	1.32 MB  	N/A
	        │ │ │ │ │ │ │ │ ├─IndexJoin_377                         	root     	6.19    	inner join, inner:TableReader_374, outer key:tpcds1.store_sales.ss_sold_date_sk, inner key:tpcds1.date_dim.d_date_sk, equal cond:eq(tpcds1.store_sales.ss_sold_date_sk, tpcds1.date_dim.d_date_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	2301   	time:20.3s, loops:12, inner:{total:749.6ms, concurrency:5, task:9, construct:1.84ms, fetch:747ms, build:760.1µs}, probe:2.72ms                                                                                                                                                                                                                                                                                                                                                                                                               	1.19 MB  	N/A
	        │ │ │ │ │ │ │ │ │ ├─IndexJoin_388                       	root     	6.19    	inner join, inner:TableReader_385, outer key:tpcds1.store_sales.ss_addr_sk, inner key:tpcds1.customer_address.ca_address_sk, equal cond:eq(tpcds1.store_sales.ss_addr_sk, tpcds1.customer_address.ca_address_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	2301   	time:20.3s, loops:12, inner:{total:709.1ms, concurrency:5, task:9, construct:1.89ms, fetch:706.4ms, build:843.8µs}, probe:2.14ms                                                                                                                                                                                                                                                                                                                                                                                                             	1.19 MB  	N/A
	        │ │ │ │ │ │ │ │ │ │ ├─IndexJoin_399                     	root     	6.19    	inner join, inner:TableReader_396, outer key:tpcds1.household_demographics.hd_income_band_sk, inner key:tpcds1.income_band.ib_income_band_sk, equal cond:eq(tpcds1.household_demographics.hd_income_band_sk, tpcds1.income_band.ib_income_band_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	2301   	time:20.3s, loops:12, inner:{total:753.5ms, concurrency:5, task:9, construct:1.81ms, fetch:751.5ms, build:119.7µs}, probe:1.71ms                                                                                                                                                                                                                                                                                                                                                                                                             	992.6 KB 	N/A
	        │ │ │ │ │ │ │ │ │ │ │ ├─IndexJoin_412                   	root     	6.19    	inner join, inner:TableReader_408, outer key:tpcds1.store_sales.ss_hdemo_sk, inner key:tpcds1.household_demographics.hd_demo_sk, equal cond:eq(tpcds1.store_sales.ss_hdemo_sk, tpcds1.household_demographics.hd_demo_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	2301   	time:20.3s, loops:12, inner:{total:959.2ms, concurrency:5, task:9, construct:1.87ms, fetch:956.5ms, build:805.4µs}, probe:1.53ms                                                                                                                                                                                                                                                                                                                                                                                                             	1.00 MB  	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ ├─IndexJoin_423                 	root     	6.19    	inner join, inner:TableReader_420, outer key:tpcds1.store_sales.ss_promo_sk, inner key:tpcds1.promotion.p_promo_sk, equal cond:eq(tpcds1.store_sales.ss_promo_sk, tpcds1.promotion.p_promo_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	2301   	time:20.3s, loops:12, inner:{total:1.6s, concurrency:5, task:9, construct:1.82ms, fetch:1.6s, build:601.5µs}, probe:1.6ms                                                                                                                                                                                                                                                                                                                                                                                                                    	1.00 MB  	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ ├─IndexJoin_434               	root     	6.19    	inner join, inner:TableReader_431, outer key:tpcds1.store_sales.ss_store_sk, inner key:tpcds1.store.s_store_sk, equal cond:eq(tpcds1.store_sales.ss_store_sk, tpcds1.store.s_store_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	2301   	time:20.2s, loops:12, inner:{total:1.09s, concurrency:5, task:9, construct:1.74ms, fetch:1.09s, build:49µs}, probe:1.57ms                                                                                                                                                                                                                                                                                                                                                                                                                    	1.03 MB  	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─IndexJoin_448             	root     	6.19    	inner join, inner:TableReader_444, outer key:tpcds1.store_sales.ss_item_sk, inner key:tpcds1.item.i_item_sk, equal cond:eq(tpcds1.store_sales.ss_item_sk, tpcds1.item.i_item_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	2346   	time:20.2s, loops:12, inner:{total:25.8s, concurrency:5, task:200, construct:4.86s, fetch:21s, build:169.2µs}, probe:881.8ms                                                                                                                                                                                                                                                                                                                                                                                                                 	447.9 MB 	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─IndexHashJoin_461       	root     	128.76  	inner join, inner:IndexLookUp_458, outer key:tpcds1.catalog_sales.cs_item_sk, inner key:tpcds1.store_sales.ss_item_sk, equal cond:eq(tpcds1.catalog_sales.cs_item_sk, tpcds1.store_sales.ss_item_sk)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              	4744682	time:19.4s, loops:4639, inner:{total:51.8s, concurrency:5, task:18, construct:33ms, fetch:46.4s, build:6.65ms, join:5.39s}                                                                                                                                                                                                                                                                                                                                                                                                                    	502.1 MB 	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─Selection_471         	root     	0.80    	not(isnull(tpcds1.catalog_sales.cs_item_sk))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	34338  	time:1.94s, loops:44                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	88.8 KB  	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ └─CTEFullScan_537     	root     	1       	CTE:cs_ui, data:CTE_0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	34338  	time:1.94s, loops:40                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	2.98 MB  	3.67 MB
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ └─IndexLookUp_458       	root     	160.95  	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	5086956	time:46.3s, loops:4994, index_task: {total_time: 35.7s, fetch_handle: 5.9s, build: 892.1µs, wait: 29.8s}, table_task: {total_time: 3m34.4s, num: 344, concurrency: 90}                                                                                                                                                                                                                                                                                                                                                                       	2.18 MB  	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │   ├─IndexRangeScan_455  	cop[tikv]	222.29  	table:store_sales, index:PRIMARY(ss_item_sk, ss_ticket_number), range: decided by [eq(tpcds1.store_sales.ss_item_sk, tpcds1.catalog_sales.cs_item_sk)], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	5586950	time:5.48s, loops:5535, cop_task: {num: 76, max: 3.98s, min: 807.6µs, avg: 366.4ms, p95: 1.97s, max_proc_keys: 653186, p95_proc_keys: 446985, tot_proc: 24.2s, tot_wait: 3.4s, rpc_num: 76, rpc_time: 27.8s, copr_cache_hit_ratio: 0.01}, tikv_task:{proc max:672ms, min:0s, p80:95ms, p95:436ms, iters:5780, tasks:76}, scan_detail: {total_process_keys: 5561253, total_keys: 5595442, rocksdb: {delete_skipped_count: 0, key_skipped_count: 5561253, block: {cache_hit_count: 140831, read_count: 0, read_byte: 0 Bytes}}}                	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │   └─Selection_457       	cop[tikv]	160.95  	not(isnull(tpcds1.store_sales.ss_addr_sk)), not(isnull(tpcds1.store_sales.ss_cdemo_sk)), not(isnull(tpcds1.store_sales.ss_customer_sk)), not(isnull(tpcds1.store_sales.ss_hdemo_sk)), not(isnull(tpcds1.store_sales.ss_promo_sk)), not(isnull(tpcds1.store_sales.ss_sold_date_sk)), not(isnull(tpcds1.store_sales.ss_store_sk))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	5086956	time:3m11.2s, loops:6239, cop_task: {num: 2064, max: 1.66s, min: 6.26ms, avg: 394.4ms, p95: 881.5ms, max_proc_keys: 4026, p95_proc_keys: 3898, tot_proc: 10m20.5s, tot_wait: 2m59.3s, rpc_num: 2064, rpc_time: 13m33.8s, copr_cache_hit_ratio: 0.01}, tikv_task:{proc max:245ms, min:2ms, p80:211ms, p95:220ms, iters:14198, tasks:2064}, scan_detail: {total_process_keys: 5579484, total_keys: 5620499, rocksdb: {delete_skipped_count: 0, key_skipped_count: 82475, block: {cache_hit_count: 19034699, read_count: 0, read_byte: 0 Bytes}}}	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │     └─TableRowIDScan_456	cop[tikv]	222.29  	table:store_sales, keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	5586950	tikv_task:{proc max:242ms, min:2ms, p80:210ms, p95:219ms, iters:14198, tasks:2064}                                                                                                                                                                                                                                                                                                                                                                                                                                                            	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ └─TableReader_444         	root     	0.00    	data:Selection_443                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	29     	time:20.9s, loops:229, cop_task: {num: 200, max: 651.3ms, min: 2.65ms, avg: 104.4ms, p95: 459.6ms, max_proc_keys: 391, p95_proc_keys: 381, tot_proc: 11.9s, tot_wait: 8.65s, rpc_num: 200, rpc_time: 20.9s, copr_cache_hit_ratio: 0.08}                                                                                                                                                                                                                                                                                                       	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │   └─Selection_443         	cop[tikv]	0.00    	ge(tpcds1.item.i_current_price, 35), ge(tpcds1.item.i_current_price, 36), in(tpcds1.item.i_color, "maroon", "burnished", "dim", "steel", "navajo", "chocolate"), le(tpcds1.item.i_current_price, 45), le(tpcds1.item.i_current_price, 50)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	29     	tikv_task:{proc max:24ms, min:0s, p80:17ms, p95:21ms, iters:756, tasks:200}, scan_detail: {total_process_keys: 49610, total_keys: 58241, rocksdb: {delete_skipped_count: 0, key_skipped_count: 32459, block: {cache_hit_count: 248486, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                   	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ │     └─TableRangeScan_442  	cop[tikv]	1       	table:item, range: decided by [tpcds1.store_sales.ss_item_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	53875  	tikv_task:{proc max:24ms, min:0s, p80:17ms, p95:21ms, iters:756, tasks:200}                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │ └─TableReader_431           	root     	1       	data:TableRangeScan_430                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	54     	time:1.09s, loops:18, cop_task: {num: 9, max: 473.8ms, min: 546.4µs, avg: 120.8ms, p95: 473.8ms, max_proc_keys: 6, p95_proc_keys: 6, tot_proc: 2ms, tot_wait: 1.08s, rpc_num: 9, rpc_time: 1.09s, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                                	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ │   └─TableRangeScan_430      	cop[tikv]	1       	table:store, range: decided by [tpcds1.store_sales.ss_store_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 	54     	tikv_task:{proc max:1ms, min:0s, p80:1ms, p95:1ms, iters:9, tasks:9}, scan_detail: {total_process_keys: 54, total_keys: 72, rocksdb: {delete_skipped_count: 0, key_skipped_count: 54, block: {cache_hit_count: 288, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                                      	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │ └─TableReader_420             	root     	1       	data:TableRangeScan_419                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	1399   	time:1.59s, loops:18, cop_task: {num: 9, max: 624.4ms, min: 1.17ms, avg: 176.8ms, p95: 624.4ms, max_proc_keys: 255, p95_proc_keys: 255, tot_proc: 833ms, tot_wait: 740ms, rpc_num: 9, rpc_time: 1.59s, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                            	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ │   └─TableRangeScan_419        	cop[tikv]	1       	table:promotion, range: decided by [tpcds1.store_sales.ss_promo_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	1399   	tikv_task:{proc max:5ms, min:1ms, p80:4ms, p95:5ms, iters:27, tasks:9}, scan_detail: {total_process_keys: 1399, total_keys: 1668, rocksdb: {delete_skipped_count: 0, key_skipped_count: 1137, block: {cache_hit_count: 2942, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                             	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │ └─TableReader_408               	root     	1       	data:Selection_407                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	2244   	time:953.1ms, loops:18, cop_task: {num: 9, max: 428.3ms, min: 2.69ms, avg: 105.7ms, p95: 428.3ms, max_proc_keys: 494, p95_proc_keys: 494, tot_proc: 309ms, tot_wait: 630ms, rpc_num: 9, rpc_time: 951ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                          	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │   └─Selection_407               	cop[tikv]	1       	not(isnull(tpcds1.household_demographics.hd_income_band_sk))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	2244   	tikv_task:{proc max:8ms, min:2ms, p80:7ms, p95:8ms, iters:32, tasks:9}, scan_detail: {total_process_keys: 2244, total_keys: 2358, rocksdb: {delete_skipped_count: 0, key_skipped_count: 232, block: {cache_hit_count: 10825, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                             	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ │     └─TableRangeScan_406        	cop[tikv]	1       	table:hd1, range: decided by [tpcds1.store_sales.ss_hdemo_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	2244   	tikv_task:{proc max:8ms, min:2ms, p80:7ms, p95:8ms, iters:32, tasks:9}                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │ └─TableReader_396                 	root     	1       	data:TableRangeScan_395                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	178    	time:748.9ms, loops:18, cop_task: {num: 9, max: 324ms, min: 431.6µs, avg: 83.1ms, p95: 324ms, max_proc_keys: 20, p95_proc_keys: 20, tot_proc: 2ms, tot_wait: 743ms, rpc_num: 9, rpc_time: 747.7ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                               	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ │   └─TableRangeScan_395            	cop[tikv]	1       	table:ib1, range: decided by [tpcds1.household_demographics.hd_income_band_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	178    	tikv_task:{proc max:1ms, min:0s, p80:1ms, p95:1ms, iters:9, tasks:9}, scan_detail: {total_process_keys: 178, total_keys: 189, rocksdb: {delete_skipped_count: 0, key_skipped_count: 178, block: {cache_hit_count: 66, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                                    	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │ └─TableReader_385                   	root     	1.00    	data:TableRangeScan_384                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	2288   	time:702.8ms, loops:18, cop_task: {num: 9, max: 292.9ms, min: 3.04ms, avg: 78ms, p95: 292.9ms, max_proc_keys: 509, p95_proc_keys: 509, tot_proc: 40ms, tot_wait: 650ms, rpc_num: 9, rpc_time: 701ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ │   └─TableRangeScan_384              	cop[tikv]	1.00    	table:ad1, range: decided by [tpcds1.store_sales.ss_addr_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	2288   	tikv_task:{proc max:7ms, min:2ms, p80:7ms, p95:7ms, iters:32, tasks:9}, scan_detail: {total_process_keys: 2288, total_keys: 2312, rocksdb: {delete_skipped_count: 0, key_skipped_count: 48, block: {cache_hit_count: 12226, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ │ │ │ │ │ │ │ └─TableReader_374                     	root     	1       	data:TableRangeScan_373                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	1956   	time:743.7ms, loops:18, cop_task: {num: 9, max: 248.7ms, min: 2.45ms, avg: 82.5ms, p95: 248.7ms, max_proc_keys: 428, p95_proc_keys: 428, tot_proc: 291ms, tot_wait: 439ms, rpc_num: 9, rpc_time: 742.3ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                         	N/A      	N/A
	        │ │ │ │ │ │ │ │ │   └─TableRangeScan_373                	cop[tikv]	1       	table:d1, range: decided by [tpcds1.store_sales.ss_sold_date_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	1956   	tikv_task:{proc max:5ms, min:1ms, p80:4ms, p95:5ms, iters:30, tasks:9}, scan_detail: {total_process_keys: 1956, total_keys: 2316, rocksdb: {delete_skipped_count: 0, key_skipped_count: 857, block: {cache_hit_count: 7718, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ │ │ │ │ │ │ └─TableReader_362                       	root     	0.87    	data:Selection_361                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	2156   	time:606.5ms, loops:18, cop_task: {num: 9, max: 225.6ms, min: 3.47ms, avg: 67.3ms, p95: 225.6ms, max_proc_keys: 510, p95_proc_keys: 510, tot_proc: 209ms, tot_wait: 382ms, rpc_num: 9, rpc_time: 604.8ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                         	N/A      	N/A
	        │ │ │ │ │ │ │ │   └─Selection_361                       	cop[tikv]	0.87    	not(isnull(tpcds1.customer.c_current_addr_sk)), not(isnull(tpcds1.customer.c_current_cdemo_sk)), not(isnull(tpcds1.customer.c_current_hdemo_sk)), not(isnull(tpcds1.customer.c_first_sales_date_sk)), not(isnull(tpcds1.customer.c_first_shipto_date_sk))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	2156   	tikv_task:{proc max:8ms, min:2ms, p80:8ms, p95:8ms, iters:32, tasks:9}, scan_detail: {total_process_keys: 2296, total_keys: 2301, rocksdb: {delete_skipped_count: 0, key_skipped_count: 10, block: {cache_hit_count: 12821, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ │ │ │ │ │ │     └─TableRangeScan_360                	cop[tikv]	1       	table:customer, range: decided by [tpcds1.store_sales.ss_customer_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	2296   	tikv_task:{proc max:8ms, min:2ms, p80:8ms, p95:8ms, iters:32, tasks:9}                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	N/A      	N/A
	        │ │ │ │ │ │ │ └─TableReader_349                         	root     	1       	data:Selection_348                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	1669   	time:327ms, loops:16, cop_task: {num: 8, max: 157.5ms, min: 1.43ms, avg: 40.8ms, p95: 157.5ms, max_proc_keys: 494, p95_proc_keys: 494, tot_proc: 202ms, tot_wait: 118ms, rpc_num: 8, rpc_time: 325.8ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                           	N/A      	N/A
	        │ │ │ │ │ │ │   └─Selection_348                         	cop[tikv]	1       	not(isnull(tpcds1.household_demographics.hd_income_band_sk))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	1669   	tikv_task:{proc max:4ms, min:1ms, p80:4ms, p95:4ms, iters:27, tasks:8}, scan_detail: {total_process_keys: 1669, total_keys: 1736, rocksdb: {delete_skipped_count: 0, key_skipped_count: 138, block: {cache_hit_count: 8129, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ │ │ │ │ │     └─TableRangeScan_347                  	cop[tikv]	1       	table:hd2, range: decided by [tpcds1.customer.c_current_hdemo_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	1669   	tikv_task:{proc max:4ms, min:1ms, p80:4ms, p95:4ms, iters:27, tasks:8}                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	N/A      	N/A
	        │ │ │ │ │ │ └─TableReader_337                           	root     	1       	data:TableRangeScan_336                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	160    	time:329.5ms, loops:16, cop_task: {num: 8, max: 159.5ms, min: 357.2µs, avg: 39.6ms, p95: 159.5ms, max_proc_keys: 20, p95_proc_keys: 20, rpc_num: 8, rpc_time: 316.1ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                                                           	N/A      	N/A
	        │ │ │ │ │ │   └─TableRangeScan_336                      	cop[tikv]	1       	table:ib2, range: decided by [tpcds1.household_demographics.hd_income_band_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	160    	tikv_task:{proc max:0s, min:0s, p80:0s, p95:0s, iters:8, tasks:8}, scan_detail: {total_process_keys: 160, total_keys: 168, rocksdb: {delete_skipped_count: 0, key_skipped_count: 160, block: {cache_hit_count: 48, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                                       	N/A      	N/A
	        │ │ │ │ │ └─TableReader_326                             	root     	1.00    	data:TableRangeScan_325                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	1699   	time:375.3ms, loops:16, cop_task: {num: 8, max: 182.4ms, min: 2.32ms, avg: 46.8ms, p95: 182.4ms, max_proc_keys: 509, p95_proc_keys: 509, tot_proc: 167ms, tot_wait: 200ms, rpc_num: 8, rpc_time: 373.9ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                         	N/A      	N/A
	        │ │ │ │ │   └─TableRangeScan_325                        	cop[tikv]	1.00    	table:ad2, range: decided by [tpcds1.customer.c_current_addr_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	1699   	tikv_task:{proc max:5ms, min:1ms, p80:5ms, p95:5ms, iters:27, tasks:8}, scan_detail: {total_process_keys: 1699, total_keys: 1713, rocksdb: {delete_skipped_count: 0, key_skipped_count: 28, block: {cache_hit_count: 9168, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                               	N/A      	N/A
	        │ │ │ │ └─TableReader_315                               	root     	1       	data:TableRangeScan_314                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	1629   	time:267.8ms, loops:16, cop_task: {num: 8, max: 151ms, min: 1.72ms, avg: 33.4ms, p95: 151ms, max_proc_keys: 472, p95_proc_keys: 472, tot_proc: 89ms, tot_wait: 171ms, rpc_num: 8, rpc_time: 266.5ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ │ │   └─TableRangeScan_314                          	cop[tikv]	1       	table:d2, range: decided by [tpcds1.customer.c_first_sales_date_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	1629   	tikv_task:{proc max:4ms, min:1ms, p80:3ms, p95:4ms, iters:26, tasks:8}, scan_detail: {total_process_keys: 1629, total_keys: 1738, rocksdb: {delete_skipped_count: 0, key_skipped_count: 226, block: {cache_hit_count: 7774, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ │ └─TableReader_304                                 	root     	1       	data:TableRangeScan_303                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	1629   	time:358.5ms, loops:16, cop_task: {num: 8, max: 179.7ms, min: 1.84ms, avg: 44.7ms, p95: 179.7ms, max_proc_keys: 472, p95_proc_keys: 472, tot_proc: 197ms, tot_wait: 152ms, rpc_num: 8, rpc_time: 357.3ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                         	N/A      	N/A
	        │ │ │   └─TableRangeScan_303                            	cop[tikv]	1       	table:d3, range: decided by [tpcds1.customer.c_first_shipto_date_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	1629   	tikv_task:{proc max:3ms, min:1ms, p80:3ms, p95:3ms, iters:26, tasks:8}, scan_detail: {total_process_keys: 1629, total_keys: 1738, rocksdb: {delete_skipped_count: 0, key_skipped_count: 226, block: {cache_hit_count: 7774, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                              	N/A      	N/A
	        │ │ └─IndexReader_179                                   	root     	1       	index:IndexRangeScan_178                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	160    	time:258.8ms, loops:16, cop_task: {num: 8, max: 160ms, min: 2.21ms, avg: 32.2ms, p95: 160ms, max_proc_keys: 57, p95_proc_keys: 57, tot_proc: 26ms, tot_wait: 227ms, rpc_num: 8, rpc_time: 257.1ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                                	398 Bytes	N/A
	        │ │   └─IndexRangeScan_178                              	cop[tikv]	1       	table:store_returns, index:PRIMARY(sr_item_sk, sr_ticket_number), range: decided by [eq(tpcds1.store_returns.sr_item_sk, tpcds1.store_sales.ss_item_sk) eq(tpcds1.store_returns.sr_ticket_number, tpcds1.store_sales.ss_ticket_number)], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	160    	tikv_task:{proc max:6ms, min:1ms, p80:4ms, p95:6ms, iters:9, tasks:8}, scan_detail: {total_process_keys: 160, total_keys: 1867, rocksdb: {delete_skipped_count: 0, key_skipped_count: 160, block: {cache_hit_count: 10242, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                               	N/A      	N/A
	        │ └─TableReader_166                                     	root     	1       	data:Selection_165                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	120    	time:2.3ms, loops:4, cop_task: {num: 4, max: 1.25ms, min: 677µs, avg: 903.5µs, p95: 1.25ms, max_proc_keys: 50, p95_proc_keys: 50, tot_proc: 3ms, rpc_num: 4, rpc_time: 3.42ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                                                  	N/A      	N/A
	        │   └─Selection_165                                     	cop[tikv]	1       	not(isnull(tpcds1.customer_demographics.cd_marital_status))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	120    	tikv_task:{proc max:1ms, min:0s, p80:1ms, p95:1ms, iters:6, tasks:4}, scan_detail: {total_process_keys: 120, total_keys: 120, rocksdb: {delete_skipped_count: 0, key_skipped_count: 0, block: {cache_hit_count: 724, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                                     	N/A      	N/A
	        │     └─TableRangeScan_164                              	cop[tikv]	1       	table:cd1, range: decided by [tpcds1.store_sales.ss_cdemo_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   	120    	tikv_task:{proc max:1ms, min:0s, p80:1ms, p95:1ms, iters:6, tasks:4}                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	N/A      	N/A
	        └─TableReader_153                                       	root     	1       	data:Selection_152                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	120    	time:2.08ms, loops:4, cop_task: {num: 4, max: 990.7µs, min: 484.5µs, avg: 797.3µs, p95: 990.7µs, max_proc_keys: 45, p95_proc_keys: 45, tot_proc: 3ms, rpc_num: 4, rpc_time: 3ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                                              	N/A      	N/A
	          └─Selection_152                                       	cop[tikv]	1       	not(isnull(tpcds1.customer_demographics.cd_marital_status))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	120    	tikv_task:{proc max:1ms, min:0s, p80:1ms, p95:1ms, iters:6, tasks:4}, scan_detail: {total_process_keys: 120, total_keys: 120, rocksdb: {delete_skipped_count: 0, key_skipped_count: 0, block: {cache_hit_count: 722, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                                     	N/A      	N/A
	            └─TableRangeScan_151                                	cop[tikv]	1       	table:cd2, range: decided by [tpcds1.customer.c_current_cdemo_sk], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	120    	tikv_task:{proc max:1ms, min:0s, p80:1ms, p95:1ms, iters:6, tasks:4}                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	N/A      	N/A
	CTE_0                                                           	root     	1       	Non-Recursive CTE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 	34338  	time:1.94s, loops:40                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	2.98 MB  	3.67 MB
	└─Projection_474                                                	root     	14316.80	tpcds1.catalog_sales.cs_item_sk, Column#64, Column#65                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	17169  	time:968.4ms, loops:18, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	118.4 KB 	N/A
	  └─Selection_475                                               	root     	14316.80	gt(Column#64, mul(2, Column#65))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	17169  	time:968.3ms, loops:18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	90.0 KB  	N/A
	    └─HashAgg_476                                               	root     	17896   	group by:Column#412, funcs:sum(Column#409)->Column#64, funcs:sum(Column#410)->Column#65, funcs:firstrow(Column#411)->tpcds1.catalog_sales.cs_item_sk                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              	17862  	time:964.5ms, loops:22, partial_worker:{wall_time:954.138964ms, concurrency:5, task_num:143, tot_wait:4.68086352s, tot_exec:81.501124ms, tot_time:4.768953065s, max:954.108071ms, p95:954.108071ms}, final_worker:{wall_time:968.273771ms, concurrency:5, task_num:25, tot_wait:4.76746738s, tot_exec:66.90266ms, tot_time:4.834382153s, max:968.260699ms, p95:968.260699ms}                                                                                                                                                                  	15.4 MB  	N/A
	      └─Projection_536                                          	root     	144067  	tpcds1.catalog_sales.cs_ext_list_price, plus(plus(tpcds1.catalog_returns.cr_refunded_cash, tpcds1.catalog_returns.cr_reversed_charge), tpcds1.catalog_returns.cr_store_credit)->Column#410, tpcds1.catalog_sales.cs_item_sk, tpcds1.catalog_sales.cs_item_sk                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	144067 	time:952.1ms, loops:144, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	1.40 MB  	N/A
	        └─Projection_478                                        	root     	144067  	tpcds1.catalog_sales.cs_item_sk, tpcds1.catalog_sales.cs_ext_list_price, tpcds1.catalog_returns.cr_refunded_cash, tpcds1.catalog_returns.cr_reversed_charge, tpcds1.catalog_returns.cr_store_credit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	144067 	time:951.9ms, loops:144, Concurrency:5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	1.67 MB  	N/A
	          └─IndexHashJoin_485                                   	root     	144067  	inner join, inner:IndexLookUp_482, outer key:tpcds1.catalog_returns.cr_item_sk, tpcds1.catalog_returns.cr_order_number, inner key:tpcds1.catalog_sales.cs_item_sk, tpcds1.catalog_sales.cs_order_number, equal cond:eq(tpcds1.catalog_returns.cr_item_sk, tpcds1.catalog_sales.cs_item_sk), eq(tpcds1.catalog_returns.cr_order_number, tpcds1.catalog_sales.cs_order_number)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	144067 	time:951.8ms, loops:144, inner:{total:54.4s, concurrency:5, task:23, construct:244.5ms, fetch:4.14s, build:29.5ms, join:50s}                                                                                                                                                                                                                                                                                                                                                                                                                  	30.9 MB  	N/A
	            ├─TableReader_515                                   	root     	144067  	data:TableFullScan_514                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	288134 	time:346.8ms, loops:294, cop_task: {num: 2, max: 174.6ms, min: 171.7ms, avg: 173.1ms, p95: 174.6ms, max_proc_keys: 144067, p95_proc_keys: 144067, tot_proc: 286ms, tot_wait: 1ms, rpc_num: 2, rpc_time: 346.1ms, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                                  	18.7 MB  	N/A
	            │ └─TableFullScan_514                               	cop[tikv]	144067  	table:catalog_returns, keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	288134 	tikv_task:{proc max:105ms, min:99ms, p80:105ms, p95:105ms, iters:290, tasks:2}, scan_detail: {total_process_keys: 288134, total_keys: 288136, rocksdb: {delete_skipped_count: 0, key_skipped_count: 288134, block: {cache_hit_count: 992, read_count: 0, read_byte: 0 Bytes}}}                                                                                                                                                                                                                                                                	N/A      	N/A
	            └─IndexLookUp_482                                   	root     	1       	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	176803 	time:4s, loops:202, index_task: {total_time: 3.06s, fetch_handle: 3.06s, build: 55.9µs, wait: 238.2µs}, table_task: {total_time: 17s, num: 57, concurrency: 115}                                                                                                                                                                                                                                                                                                                                                                            	15.4 KB  	N/A
	              ├─IndexRangeScan_480                              	cop[tikv]	1       	table:catalog_sales, index:PRIMARY(cs_item_sk, cs_order_number), range: decided by [eq(tpcds1.catalog_sales.cs_item_sk, tpcds1.catalog_returns.cr_item_sk) eq(tpcds1.catalog_sales.cs_order_number, tpcds1.catalog_returns.cr_order_number)], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	176803 	time:3.05s, loops:233, cop_task: {num: 61, max: 453.7ms, min: 290.8µs, avg: 74.5ms, p95: 389.1ms, max_proc_keys: 17203, p95_proc_keys: 16976, tot_proc: 4.32s, tot_wait: 3ms, rpc_num: 61, rpc_time: 4.54s, copr_cache_hit_ratio: 0.11}, tikv_task:{proc max:431ms, min:0s, p80:129ms, p95:374ms, iters:357, tasks:61}, scan_detail: {total_process_keys: 174783, total_keys: 349566, rocksdb: {delete_skipped_count: 0, key_skipped_count: 349376, block: {cache_hit_count: 1048362, read_count: 0, read_byte: 0 Bytes}}}                   	N/A      	N/A
	              └─TableRowIDScan_481                              	cop[tikv]	1       	table:catalog_sales, keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	176803 	time:2.17s, loops:265, cop_task: {num: 72, max: 114.3ms, min: 718.2µs, avg: 33.1ms, p95: 101.7ms, max_proc_keys: 8843, p95_proc_keys: 8025, tot_proc: 2.14s, tot_wait: 3ms, rpc_num: 72, rpc_time: 2.38s, copr_cache_hit_ratio: 0.10}, tikv_task:{proc max:105ms, min:1ms, p80:42ms, p95:93ms, iters:490, tasks:72}, scan_detail: {total_process_keys: 173828, total_keys: 179323, rocksdb: {delete_skipped_count: 0, key_skipped_count: 11217, block: {cache_hit_count: 540057, read_count: 0, read_byte: 0 Bytes}}}                        	N/A      	N/A
```

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #26260 

Problem Summary:

CTE didn't implement DeriveStats, so the cost is wrong.

### What is changed and how it works?

Implement DeriveStats for CTE and CTETable.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note 

- No release note

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

File: planner/core/logical_plans.go [hunk 1]
```diff
@@ -1219,6 +1222,7 @@ type LogicalCTE struct {
 type LogicalCTETable struct {
 	logicalSchemaProducer
 
+	seedPlan     LogicalPlan
```
Comment (winoros) [inline planner/core/logical_plans.go:1225]: Why do we need to add it here? and only add the seed part without the recursive part together

**Review by winoros — APPROVED** [review]
