### PR TITLE
planner/core: fix a bug of adding enforcer.

### LINKED ISSUE #22081: Incorrect result when doing merge join on partitioned tables in a transaction
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* init */ drop table if exists t1, t2;
/* init */ create table t1  (c_int int, c_str varchar(40), primary key (c_int)) partition by hash (c_int) partitions 4;
/* init */ create table t2  (c_int int, c_str varchar(40), primary key(c_int, c_str));
/* init */ insert into t1 (`c_int`, `c_str`) values (11, 'keen williamson'), (10, 'gracious hermann');
/* init */ insert into t2 (`c_int`, `c_str`) values (10, 'gracious hermann');

/* test */ begin;
/* test */ insert into t2 values (11, 'amazing merkle');
/* test */ insert into t2 values (12, 'magical hoover');
/* test */ select /*+ MERGE_JOIN(t1,t2) */ * from t1, t2 where t1.c_int = t2.c_int and t1.c_int = t2.c_int order by t1.c_int, t2.c_str;
/* test */ select /*+ MERGE_JOIN(t1,t2) */ * from t1, t2 where t1.c_int = t2.c_int order by t1.c_int, t2.c_str;
/* test */ commit;
```

### 2. What did you expect to see? (Required)

Both `select` in transaction return
```
+-------+------------------+-------+------------------+
| c_int | c_str            | c_int | c_str            |
+-------+------------------+-------+------------------+
|    10 | gracious hermann |    10 | gracious hermann |
|    11 | keen williamson  |    11 | amazing merkle   |
+-------+------------------+-------+------------------+
```

### 3. What did you see instead (Required)

```
mysql> begin;
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t2 values (11, 'amazing merkle');
Query OK, 1 row affected (0.04 sec)

mysql> insert into t2 values (12, 'magical hoover');
Query OK, 1 row affected (0.05 sec)

mysql> select /*+ MERGE_JOIN(t1,t2) */  * from t1, t2 where t1.c_int = t2.c_int and t1.c_int = t2.c_int order by t1.c_int, t2.c_str;
+-------+------------------+-------+------------------+
| c_int | c_str            | c_int | c_str            |
+-------+------------------+-------+------------------+
|    10 | gracious hermann |    10 | gracious hermann |
+-------+------------------+-------+------------------+
1 row in set (0.05 sec)

mysql> select /*+ MERGE_JOIN(t1,t2) */  * from t1, t2 where t1.c_int = t2.c_int order by t1.c_int, t2.c_str;
+-------+------------------+-------+------------------+
| c_int | c_str            | c_int | c_str            |
+-------+------------------+-------+------------------+
|    10 | gracious hermann |    10 | gracious hermann |
|    11 | keen williamson  |    11 | amazing merkle   |
+-------+------------------+-------+------------------+
2 rows in set (0.05 sec)
```

### 4. What is your TiDB version? (Required)

release-5.0-rc (c4f5d865574695a9700476aba966fa94ee1bbd70)

### PR DESCRIPTION
**Pull request by hanfei1991**
### What problem does this PR solve?

Issue Number: close #22081 

Problem Summary: The `sort` enforcer is added under the UnionScan.
before the last PR #22056 . We clone 'physical property' without `enforced` field. This ensure the correctness of always add an enforcer above the whole subplan. This is very important to UnionScan, because UnionScan doesn't assure an order so we must sort afterwards.
This bug occurs because I copy the **enforced** field in 'physical property''s Clone interface. Because according to the name, copying every field really makes sense. But in `exhuastedPhysicalPlan`, UnionScan copies the property without setting `enforced` false, which result in an excepted bug.

### What is changed and how it works?

What's Changed:
Change the logic back. In addition, I make the function names more reasonable. Clone is essentionally **CloneEssentionFields** and Enforced really means **CanAddEnforcer**. That will not confuse the newbies anymore.

### Related changes

- planner/core

### Check List 

Tests 

- Unit test

### Release note 

- fix a bug of adding enforcer

### CODE REVIEW

File: planner/property/physical_property.go [hunk 1]
```diff
@@ -196,16 +196,13 @@ func (p *PhysicalProperty) String() string {
 	return fmt.Sprintf("Prop{cols: %v, TaskTp: %s, expectedCount: %v}", p.SortItems, p.TaskTp, p.ExpectedCnt)
 }
 
-// Clone returns a copy of PhysicalProperty. Currently, this function is only used to build new
-// required property for children plan in `exhaustPhysicalPlans`, so we don't copy `Enforced` field
-// because if `Enforced` is true, the `SortItems` must be empty now, this makes `Enforced` meaningless
-// for children nodes.
-func (p *PhysicalProperty) Clone() *PhysicalProperty {
+// CloneEssentialFields returns a copy of PhysicalProperty. We only copy the essential fields that really indicate the
+// property.
```
Comment (eurekaka) [inline planner/property/physical_property.go:200]:
```suggestion
// property, specifically, `CanAddEnforcer` should not be included.
```

**Review by eurekaka — COMMENTED** [review]
LGTM

**Review by winoros — COMMENTED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
