### PR TITLE
ddl, parser: make generated column and expression index same as MySQL

### LINKED ISSUE #39826: Generate column shouldn't store schema name and table name
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
create table t(a int);
alter table t add column b int as ((lower(test.t.a)));
rename table t to t1;
insert into t1(a) values (1);
```

### 2. What did you expect to see? (Required)

insert success

### 3. What did you see instead (Required)

```
mysql> insert into t1(a) values (1);
ERROR 1054 (42S22): Unknown column 'test.t.a' in 'expression'
```

### 4. What is your TiDB version? (Required)

```
master
```

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #39826

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/ddl_api.go [hunk 1]
```diff
@@ -1142,7 +1142,7 @@ func columnDefToCol(ctx sessionctx.Context, offset int, colDef *ast.ColumnDef, o
 				}
 				col.GeneratedExprString = sb.String()
 				col.GeneratedStored = v.Stored
-				_, dependColNames := findDependedColumnNames(colDef)
+				_, dependColNames, _ := findDependedColumnNames("", "", colDef)
```
Comment (mjonss) [inline ddl/ddl_api.go:1145]: Why not checking the possible error?

File: ddl/generated_column.go [hunk 2]
```diff
@@ -122,13 +122,19 @@ func findPositionRelativeColumn(cols []*table.Column, pos *ast.ColumnPosition) (
...
 // the names of the columns that are depended by colDef.
-func findDependedColumnNames(colDef *ast.ColumnDef) (generated bool, colsMap map[string]struct{}) {
+func findDependedColumnNames(schemaName string, tableName string, colDef *ast.ColumnDef) (generated bool, colsMap map[string]struct{}, err error) {
 	colsMap = make(map[string]struct{})
 	for _, option := range colDef.Options {
 		if option.Tp == ast.ColumnOptionGenerated {
 			generated = true
 			colNames := FindColumnNamesInExpr(option.Expr)
 			for _, depCol := range colNames {
+				if depCol.Schema.O != "" && schemaName != "" && depCol.Schema.O != schemaName {
```
Comment (mjonss) [inline ddl/generated_column.go:132]: Is it possible that the original name have different Case and should be compared as `depCol.Schema.L` instead or with `strings.EqualFold()` instead?

File: ddl/ddl_api.go [hunk 3]
```diff
@@ -1561,7 +1561,7 @@ func IsAutoRandomColumnID(tblInfo *model.TableInfo, colID int64) bool {
 	return false
 }
 
-func checkGeneratedColumn(ctx sessionctx.Context, colDefs []*ast.ColumnDef) error {
+func checkGeneratedColumn(ctx sessionctx.Context, schemaName string, tableName string, colDefs []*ast.ColumnDef) error {
```
Comment (mjonss) [inline ddl/ddl_api.go:1564]: Maybe use CIString instead of string? (I'm OK with string, just curious which you consider is the better option here?)

File: ddl/generated_column.go [hunk 4]
```diff
@@ -122,13 +122,19 @@ func findPositionRelativeColumn(cols []*table.Column, pos *ast.ColumnPosition) (
 
 // findDependedColumnNames returns a set of string, which indicates
 // the names of the columns that are depended by colDef.
-func findDependedColumnNames(colDef *ast.ColumnDef) (generated bool, colsMap map[string]struct{}) {
+func findDependedColumnNames(schemaName string, tableName string, colDef *ast.ColumnDef) (generated bool, colsMap map[string]struct{}, err error) {
```
Comment (mjonss) [inline ddl/generated_column.go:125]: Maybe consider CIStr instead of string?

File: ddl/generated_column.go [hunk 5]
```diff
@@ -192,7 +198,7 @@ func (c *generatedColumnChecker) Leave(inNode ast.Node) (node ast.Node, ok bool)
 //  3. check if the modified expr contains non-deterministic functions
 //  4. check whether new column refers to any auto-increment columns.
 //  5. check if the new column is indexed or stored
-func checkModifyGeneratedColumn(sctx sessionctx.Context, tbl table.Table, oldCol, newCol *table.Column, newColDef *ast.ColumnDef, pos *ast.ColumnPosition) error {
+func checkModifyGeneratedColumn(sctx sessionctx.Context, schemaName string, tbl table.Table, oldCol, newCol *table.Column, newColDef *ast.ColumnDef, pos *ast.ColumnPosition) error {
```
Comment (mjonss) [inline ddl/generated_column.go:201]: Maybe CIStr instead of string?

File: ddl/generated_column.go (hunk 2 above)
Comment (Defined2014) [reply ddl/generated_column.go]: Yes, you're right. The PR is updated.

File: ddl/ddl_api.go (hunk 1 above)
Comment (Defined2014) [reply ddl/ddl_api.go]: Updated. It was checked before, but I think rechecking `error` here makes it easier to read.

**Comment by Defined2014** [comment]
Updated, PTAL @mjonss

**Review by mjonss — APPROVED** [review]
LGTM

**Review by tiancaiamao — APPROVED** [review]
