### PR TITLE
ddl: fix reorg handle not resumed after changing DDL owner

### LINKED ISSUE #56506: reorg handle not resumed after changing DDL owner
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Modify column on a large table, trigger a reorganization.
2. Switch DDL owner.

### 2. What did you expect to see? (Required)

Another TiDB instance should pick up the modifying column work.

### 3. What did you see instead (Required)

The entire modifying column is restarted.

### 4. What is your TiDB version? (Required)

v8.1.1

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #56506

Problem Summary:

1. `doneTaskKeeper` starts from `0`, but `taskIDAllocator` starts from `1`.
2. "not owner" error is eaten by `context.Canceled`.

### What changed and how does it work?

Allocate `task ID` from `0`.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

File: pkg/ddl/backfilling.go [hunk 1]
```diff
@@ -845,12 +846,20 @@ func (dc *ddlCtx) writePhysicalTableRecord(
...
-) error {
+) (err error) {
 	startKey, endKey := reorgInfo.StartKey, reorgInfo.EndKey
 
 	if err := dc.isReorgRunnable(reorgInfo.Job.ID, false); err != nil {
 		return errors.Trace(err)
 	}
+	defer func() {
+		if err != nil && ctx.Err() != nil {
+			// Prevent "not owner" error being overwritten by context.Canceled.
```
Comment (lance6716) [inline pkg/ddl/backfilling.go:857]: maybe use `WithCancelCause` to create the context, and use `cancel(dbterror.ErrNotOwner)` to cancel

**Review by lance6716 — APPROVED** [review]
