### PR TITLE
planner : fix unsigned_decimal_col=-int_cnst access index

### LINKED ISSUE #10447: unexpected behavior of `decimal_col = int_cnst`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` sql
CREATE TABLE `table20_int_autoinc` (
  `col_decimal_40_20_signed_key` decimal(40,20) DEFAULT NULL,
  `col_decimal_10_4_signed_key` decimal(10,4) DEFAULT NULL,
  `col_bigint_signed_key` bigint(20) DEFAULT NULL,
  `col_double_signed` double DEFAULT NULL,
  `col_bigint_unsigned_key` bigint(20) unsigned DEFAULT NULL,
  `col_bigint_signed` bigint(20) DEFAULT NULL,
  `col_char_20_utf8` char(20) CHARACTER SET utf8 DEFAULT NULL,
  `col_decimal_40_20_unsigned` decimal(40,20) unsigned DEFAULT NULL,
  `col_decimal_40_20_unsigned_key` decimal(40,20) unsigned DEFAULT NULL,
  `col_float_signed` float DEFAULT NULL,
  `col_varchar_20_utf8` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_bigint_unsigned` bigint(20) unsigned DEFAULT NULL,
  `col_double_unsigned` double unsigned DEFAULT NULL,
  `col_varchar_20_utf8_key` varchar(20) CHARACTER SET utf8 DEFAULT NULL,
  `col_double_signed_key` double DEFAULT NULL,
  `col_decimal_10_4_signed` decimal(10,4) DEFAULT NULL,
  `col_float_unsigned` float unsigned DEFAULT NULL,
  `col_decimal_6_3_signed` decimal(6,3) DEFAULT NULL,
  `col_char_20_utf8_key` char(20) CHARACTER SET utf8 DEFAULT NULL,
  `col_decimal_10_4_unsigned` decimal(10,4) unsigned DEFAULT NULL,
  `col_decimal_10_4_unsigned_key` decimal(10,4) unsigned DEFAULT NULL,
  `col_decimal_6_3_unsigned` decimal(6,3) unsigned DEFAULT NULL,
  `col_decimal_40_20_signed` decimal(40,20) DEFAULT NULL,
  `col_double_unsigned_key` double unsigned DEFAULT NULL,
  `col_float_unsigned_key` float unsigned DEFAULT NULL,
  `col_decimal_6_3_unsigned_key` decimal(6,3) unsigned DEFAULT NULL,
  `col_float_signed_key` float DEFAULT NULL,
  `col_decimal_6_3_signed_key` decimal(6,3) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_decimal_40_20_signed_key` (`col_decimal_40_20_signed_key`),
  KEY `col_decimal_10_4_signed_key` (`col_decimal_10_4_signed_key`),
  KEY `col_bigint_signed_key` (`col_bigint_signed_key`),
  KEY `col_bigint_unsigned_key` (`col_bigint_unsigned_key`),
  KEY `col_decimal_40_20_unsigned_key` (`col_decimal_40_20_unsigned_key`),
  KEY `col_varchar_20_utf8_key` (`col_varchar_20_utf8_key`),
  KEY `col_double_signed_key` (`col_double_signed_key`),
  KEY `col_char_20_utf8_key` (`col_char_20_utf8_key`),
  KEY `col_decimal_10_4_unsigned_key` (`col_decimal_10_4_unsigned_key`),
  KEY `col_double_unsigned_key` (`col_double_unsigned_key`),
  KEY `col_float_unsigned_key` (`col_float_unsigned_key`),
  KEY `col_decimal_6_3_unsigned_key` (`col_decimal_6_3_unsigned_key`),
  KEY `col_float_signed_key` (`col_float_signed_key`),
  KEY `col_decimal_6_3_signed_key` (`col_decimal_6_3_signed_key`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,0.0000,0,NULL,0,0,'that\'s',0.00000000000000000000,11737.00000000000000000000,0,'aurbxfccm',1,0,0,'e',-98,-31944.0000,0,0.000,'x',0.0000,0.0000,0.000,0.00000000000000000000,0,0,0.000,4,NULL);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,-9293.0000,0,13108,0,25025,NULL,17.00000000000000000000,21271.00000000000000000000,112,'vau',2,13781,NULL,'k',0,-15003.0000,0,-999.999,'think',0.0000,0.0000,0.000,0.00000000000000000000,NULL,0,0.000,15160,NULL);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,107.0000,0,NULL,NULL,0,'were',0.00000000000000000000,15713.00000000000000000000,NULL,NULL,3,19827,0,'not',0,0.0000,0,0.000,'qkv',NULL,0.0000,0.000,25949.00000000000000000000,0,12591,0.000,NULL,103.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,0.0000,0,NULL,0,8094657380245045248,'jqk',0.00000000000000000000,0.00000000000000000000,0,'b',4,7,0,'g',-122,70.0000,27,0.000,'u',0.0000,0.0000,0.000,NULL,0,0,0.000,8209,0.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,-78.0000,-30781,-34,0,54,NULL,0.00000000000000000000,0.00000000000000000000,0,NULL,5,0,12193,'njqkvaurb',-108,-125.0000,0,0.000,'come',0.0000,0.0000,0.000,-77.00000000000000000000,0,18071,0.000,0,999.999);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,0.0000,0,0,NULL,0,'I',0.00000000000000000000,0.00000000000000000000,44,'y',6,0,0,'onjqkvaurbxfccm',0,0.0000,0,0.000,'conjqkvaurbxfcc',0.0000,0.0000,0.000,7.00000000000000000000,82,0,0.000,NULL,44.000);
INSERT INTO `table20_int_autoinc` VALUES (NULL,0.0000,31,NULL,0,7829226477206896640,'but',0.00000000000000000000,0.00000000000000000000,0,'as',7,0,0,'a',0,1641.0000,0,-999.999,'see',0.0000,0.0000,0.000,-31047.00000000000000000000,0,18845,0.000,0,0.000);
INSERT INTO `table20_int_autoinc` VALUES (NULL,0.0000,13799,0,NULL,16286,'k',0.00000000000000000000,0.00000000000000000000,-17954,'fco',8,8888979764522516480,0,'wfconjqk',0,0.0000,0,0.000,'hwfcon',0.0000,0.0000,0.000,96.00000000000000000000,0,0,999.999,-59,0.000);
INSERT INTO `table20_int_autoinc` VALUES (NULL,0.0000,NULL,0,0,3377699720527872000,'zhwfcon',0.00000000000000000000,0.00000000000000000000,-9712,'or',9,0,0,'her',0,NULL,0,0.000,'w',0.0000,0.0000,0.000,0.00000000000000000000,0,0,0.000,-28440,0.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,-31556.0000,0,16,0,NULL,'will',0.00000000000000000000,NULL,0,'l',10,10495,0,'xzhwfc',0,NULL,NULL,0.000,'ix',0.0000,0.0000,0.000,0.00000000000000000000,0,14,0.000,0,NULL);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,0.0000,NULL,NULL,0,NULL,'I',0.00000000000000000000,NULL,15542,NULL,11,75,14,NULL,0,-7440.0000,24221,0.000,'u',0.0000,0.0000,0.000,-24028.00000000000000000000,0,100,0.000,99,0.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,16144.0000,0,NULL,0,0,'z',8.00000000000000000000,11.00000000000000000000,0,'a',12,3285,24232,NULL,9311,0.0000,0,999.999,'y',0.0000,0.0000,0.000,NULL,0,0,38.000,0,0.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,4375.0000,-16,11,0,NULL,'p',NULL,0.00000000000000000000,0,'got',13,0,NULL,'j',0,20344.0000,NULL,-999.999,'tzix',80.0000,NULL,0.000,0.00000000000000000000,0,0,999.999,NULL,0.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,-4328.0000,0,111,86,0,'otzixzhwf',0.00000000000000000000,0.00000000000000000000,NULL,NULL,14,NULL,15950,'like',-1500,0.0000,NULL,60.000,'p',71.0000,0.0000,0.000,37.00000000000000000000,0,0,0.000,0,105.000);
INSERT INTO `table20_int_autoinc` VALUES (16846.00000000000000000000,0.0000,0,0,5819776618469523456,88,'c',0.00000000000000000000,0.00000000000000000000,114,NULL,15,0,NULL,'of',0,0.0000,0,0.000,'now',0.0000,0.0000,0.000,34.00000000000000000000,0,0,0.000,NULL,0.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,NULL,0,0,9,NULL,'z',NULL,NULL,10877,'for',16,112,44,NULL,NULL,-53.0000,0,NULL,'his',0.0000,0.0000,0.000,0.00000000000000000000,30822,0,NULL,0,-47.000);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,-8630.0000,-14663,NULL,0,NULL,'would',17676.00000000000000000000,0.00000000000000000000,-19590,NULL,17,0,0,NULL,0,0.0000,0,0.000,'right',0.0000,0.0000,0.000,125.00000000000000000000,19896,0,50.000,0,999.999);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,6489.0000,-74,54,0,-1752181730023833600,'not',0.00000000000000000000,0.00000000000000000000,110,'tell',18,NULL,10194,'want',0,19179.0000,NULL,-104.000,'v',0.0000,0.0000,0.000,0.00000000000000000000,4668,0,94.000,0,-98.000);
INSERT INTO `table20_int_autoinc` VALUES (-28776.00000000000000000000,NULL,0,-105,0,-20992,'y',0.00000000000000000000,0.00000000000000000000,0,'and',19,10907,21409,NULL,0,0.0000,0,999.999,NULL,0.0000,0.0000,NULL,NULL,0,NULL,27.000,-88,999.999);
INSERT INTO `table20_int_autoinc` VALUES (0.00000000000000000000,58.0000,-117,0,0,3717721492394344448,'fotzixzhwf',NULL,NULL,0,'ef',20,0,NULL,'p',0,0.0000,0,-999.999,'could',0.0000,0.0000,0.000,0.00000000000000000000,0,0,0.000,NULL,NULL);
SELECT a FROM (SELECT `col_decimal_10_4_unsigned_key` AS a, `col_float_unsigned_key` AS b FROM `table20_int_autoinc` ) tmp WHERE a = -2147483648 ORDER BY a;
```

2. What did you expect to see?
empty set

3. What did you see instead?
error reported

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
`373317f6a55fb01f656f247e1596ef789e15ba1c` in master branch

### PR DESCRIPTION
**Pull request by erwadba**
### What problem does this PR solve?

Issue Number: close #10447 

Problem Summary:

### What is changed and how it works?

What's Changed:
when access data use index. Handle the unsigned column type consider the decimal and float and double values too.
How it Works:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
```
mysql> create table t(decimal_unsigned decimal(10,4) unsigned,key(decimal_unsigned));
Query OK, 0 rows affected (0.01 sec)

mysql> select * from t where decimal_unsigned=-100;
Empty set (0.08 sec)

mysql>
```

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by erwadba** [comment]
@lzmhhh123   PTAL

**Comment by erwadba** [comment]
@zz-jason  PTAL

**Comment by erwadba** [comment]
@ti-srebot /run-all-tests

**Comment by erwadba** [comment]
@ti-srebot /run-all-tests

**Comment by erwadba** [comment]
@ti-srebot /run-all-tests

**Review by Reminiscent — COMMENTED** [review]
LGTM

File: util/ranger/points.go [hunk 1]
```diff
@@ -306,23 +306,31 @@ func (r *builder) buildFormBinOp(expr *expression.ScalarFunction) []point {
...
 // The three returned values are: fixed constant value, fixed operator, and a boolean
 // which indicates whether the range is valid or not.
-func handleUnsignedIntCol(ft *types.FieldType, val types.Datum, op string) (types.Datum, string, bool) {
+func handleUnsignedCol(ft *types.FieldType, val types.Datum, op string) (types.Datum, string, bool) {
 	isUnsigned := mysql.HasUnsignedFlag(ft.Flag)
-	isIntegerType := mysql.IsIntegerType(ft.Tp)
-	isNegativeInteger := (val.Kind() == types.KindInt64 && val.GetInt64() < 0)
+	isNegative := (val.Kind() == types.KindInt64 && val.GetInt64() < 0) ||
+		(val.Kind() == types.KindMysqlDecimal && val.GetMysqlDecimal().IsNegative()) ||
+		(val.Kind() == types.KindFloat64 && val.GetFloat64() < 0)
```
Comment (wjhuang2016) [inline util/ranger/points.go:316]: Do we need to handle KindFloat32?

**Comment by erwadba** [comment]
@wjhuang2016   PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by XuHuaiyu — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
