### PR TITLE
types: report error for json object with key length >= 65536

### LINKED ISSUE #9995: json_object with repeat a long num is wrong.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```SQL
select json_object( REPEAT('a', 2 * 16 ), 1 );
select json_object( REPEAT('a', 64 * 1024), 1 );
```

2. What did you expect to see?
### In MySQL
```SQL
mysql> select json_object( REPEAT('a', 2 * 16), 1 );
+-----------------------------------------+
| json_object( REPEAT('a', 2 * 16), 1 )   |
+-----------------------------------------+
| {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa": 1} |
+-----------------------------------------+
1 row in set (0.00 sec)
mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.7.25-0ubuntu0.18.04.2 |
+-------------------------+
1 row in set (0.00 sec)

mysql> 

```
**( AS 64 * 1024 , is too long , will not print in here).**

3. What did you see instead?
## In TiDB
```SQL

mysql> select json_object( REPEAT('a', 2 * 16), 1 );
+-----------------------------------------+
| json_object( REPEAT('a', 2 * 16), 1 )   |
+-----------------------------------------+
| {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa": 1} |
+-----------------------------------------+
1 row in set (0.00 sec)

mysql> select json_object( REPEAT('a', 64 * 1024), 1 );
+------------------------------------------+
| json_object( REPEAT('a', 64 * 1024), 1 ) |
+------------------------------------------+
| {"": 1}                                  |
+------------------------------------------+
1 row in set (0.01 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-beta-321-gc6a757b24
Git Commit Hash: c6a757b2435965a72ada9d61ea8b7a367bd89b5f
Git Branch: master
UTC Build Time: 2019-04-02 02:38:04
GoVersion: go version go1.12.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.01 sec)

mysql> 

```

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

### PR DESCRIPTION
**Pull request by dyzsr**
### What problem does this PR solve?

Issue Number: close #9995 
Note: this is **NOT** a complete fix of #9995. https://github.com/pingcap/tidb/pull/21594 can fix it completely, but it'll be a compatibility-breaker. Thus we use this commit as a tradeoff and create an issue for future work https://github.com/pingcap/tidb/issues/21781.

Problem Summary: TiDB doesn't support json object with key length >= 65536.

### What is changed and how it works?

- Report error when the key length >= 65536.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: https://github.com/pingcap/docs/pull/4399
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- Report error for json object with key length >= 65536.

### CODE REVIEW

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Comment by XuHuaiyu** [comment]
CI needs to be fixed

File: types/json/binary_functions.go [hunk 1]
```diff
@@ -803,7 +828,7 @@ func mergeBinaryArray(elems []BinaryJSON) BinaryJSON {
 	return buildBinaryArray(buf)
 }
 
-func mergeBinaryObject(objects []BinaryJSON) BinaryJSON {
+func mergeBinaryObject(objects []BinaryJSON) (BinaryJSON, error) {
```
Comment (lzmhhh123) [inline types/json/binary_functions.go:831]: `mergeBinaryObject` and `MergeBinary` are unnecessary to return error.

**Comment by dyzsr** [comment]
PTAL @lzmhhh123 , @XuHuaiyu

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
