### PR TITLE
session: make `TxnInfo()` return even if process info is empty

### LINKED ISSUE #57043: DDL internal txn reports "GC life time is shorter than transaction duration"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Prepare a large dataset.
2. Create an index for a wide column.
3. It may take more than 10 min to finish the partial import.

### 2. What did you expect to see? (Required)

Adding index complete without errors.

### 3. What did you see instead (Required)

The state of adding index becomes "rollback done". 
```
GC life time is shorter than transaction duration
```

### 4. What is your TiDB version? (Required)

b314a9c6037b

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #57043

Problem Summary:

https://github.com/pingcap/tidb/blob/c240fdf085ce24c6110a6764e8b9657a3788abfe/pkg/session/session.go#L4026-L4030

`TxnInfo()` could be nil if process info is not set(see the implementation of `TxnInfo()`). Such sessions are commonly used in DDL/DXF:

https://github.com/pingcap/tidb/blob/c240fdf085ce24c6110a6764e8b9657a3788abfe/pkg/ddl/backfilling_operators.go#L533-L539

And they only invoke `session.Begin()` before using:

https://github.com/pingcap/tidb/blob/c240fdf085ce24c6110a6764e8b9657a3788abfe/pkg/ddl/index_cop.go#L43-L48

As a result, the `startTS` from internal DDL sessions will not be reported to etcd, and GC safepoint will be advanced unexpectedly.

### What changed and how does it work?

Make TxnInfo() return even if process info is empty.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/session/session.go [hunk 1]
```diff
@@ -4027,6 +4027,10 @@ func GetStartTSFromSession(se any) (startTS, processInfoID uint64) {
 	if txnInfo != nil {
 		startTS = txnInfo.StartTS
 		processInfoID = txnInfo.ConnectionID
+	} else {
+		tmp.sessionVars.TxnCtxMu.Lock()
```
Comment (YangKeao) [inline pkg/session/session.go:4031]: `sessionVars.TxnCtx` will not be cleaned before executing another statement, so using the `StartTS` from `TxnCtx` will block the GC for very long time if some internal sessions are not used (e.g. stored in a pool).

It's possible to clean the `sessionVars.TxnCtx`. But IMO, it'd be simpler to use:

```go
txn := tmp.Txn(false)
if txn != nil {
    startTS = txn.StartTS()
}
```

It should have the same value with `txnInfo.StartTS` (ref `changePendingToValid`, it sets the `txnInfo.StartTS` with `t.StartTS()`), and it doesn't depend on the `ProcessInfo`.

File: pkg/testkit/mocksessionmanager.go [hunk 2]
```diff
@@ -158,8 +158,8 @@ func (msm *MockSessionManager) GetInternalSessionStartTSList() []uint64 {
 			txn := se.TxnInfo()
```
Comment (YangKeao) [inline pkg/testkit/mocksessionmanager.go:158]: As it also used `TxnInfo`, should we also modify it to align with the logic in `GetStartTSFromSession`?

File: pkg/session/session.go (hunk 1 above)
Comment (tangenta) [reply pkg/session/session.go]: https://github.com/pingcap/tidb/pull/57044/commits/2cfe63653e9a67e221d560b7345a3cd1657617f9

Comment (tangenta) [reply pkg/session/session.go]: Maybe we still need `TxnInfo()` because `processInfoID` will be used to filter analyze SQL.

File: pkg/session/session.go [hunk 3]
```diff
@@ -467,6 +467,7 @@ func (s *session) FieldList(tableName string) ([]*resolve.ResultField, error) {
 }
 
 // TxnInfo returns a pointer to a *copy* of the internal TxnInfo, thus is *read only*
+// ProcessInfo fields may not initialize if this is a session that used internally.
```
Comment (tangenta) [inline pkg/session/session.go:470]:
```suggestion
// Process field may not initialize if this is a session used internally.
```

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by lcwangchao — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]
