### PR TITLE
ebs br: make sure fsr credit is full filled

### LINKED ISSUE #48629: ebs br: fsr is not really enabled
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Call AWS API to enable snapshot fsr
Checking snapshot status until snapshot status is fsr enabled
Create ebs volumes 
Disable fsr right away

### 2. What did you expect to see? (Required)

The restored volume should have the best performance

### 3. What did you see instead (Required)

The volume's performance is bad as if never been fsr enabled

### PR DESCRIPTION
**Pull request by BornChanger**
### What problem does this PR solve?

Issue Number: close #48629

Problem Summary:

### What is changed and how it works?

Make sure ebs snapshot fsr credit is enough before creating volumes against them. IAM privilege of `cloudwatch:GetMetricStatistics` is required.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/aws/ebs.go [hunk 1]
```diff
@@ -326,6 +326,36 @@ func (e *EC2Session) EnableDataFSR(meta *config.EBSBasedBRMeta, targetAZ string)
...
+
+	// We have to sleep for at least fillElapsedTime minutes in order to make credits are filled to 1.0
+	// Let's heartbeat every 5 minutes
+	for time.Since(start) <= time.Duration(fillElapsedTime)*time.Minute {
+		log.Info("FSR enablement is ongoing, going to sleep for 5 minutes...")
+		time.Sleep(5 * time.Minute)
+	}
+
 	// Create a map to store the strings as keys
 	pendingSnapshots := make(map[string]struct{})
```
Comment (nkg-) [inline br/pkg/aws/ebs.go:361]: Nit question for https://github.com/pingcap/tidb/blob/7430f05c3f4a29a2f40aed38dac035956d5852e8/br/pkg/aws/ebs.go#L381. 

Why not check for "enabled" and remove those snapshots from the pending list. There should be much fewer enabled snapshots. Also seems simpler.

File: br/pkg/aws/ebs.go [hunk 2]
```diff
@@ -326,6 +326,36 @@ func (e *EC2Session) EnableDataFSR(meta *config.EBSBasedBRMeta, targetAZ string)
...
+
+	for _, s := range resp.Snapshots {
+		if *s.VolumeSize > maxVolumeSize {
+			maxVolumeSize = *s.VolumeSize
+		}
+	}
+
+	// Calculate the time in minutes to fill 1.0 credit according to
+	// https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html#volume-creation-credits
+	fillElapsedTime := 60.0 / (min(10, 1024.0/maxVolumeSize))
```
Comment (nkg-) [inline br/pkg/aws/ebs.go:350]: Instead of checking for fill rate, can we query the actual cloud watch metric fastsnapshotrestorecreditbalance. You can use the sdk for querying it. https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.GetMetricData

Maybe as a separate PR, after this temporary fix.

Comment (nkg-) [inline br/pkg/aws/ebs.go:350]: This seems to match the exact fillRate. Given AWS wants the creditBalance >= 1. Maybe pad some time here. Lets say 5 mins to be sure.

Comment (BornChanger) [reply br/pkg/aws/ebs.go]: Yes. 5 more minutes is added.

Comment (BornChanger) [reply br/pkg/aws/ebs.go]: I added the cloudwatch check support.

File: br/pkg/aws/ebs.go (hunk 1 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go:392]: I am afraid there could some conflict fsr operation to those snapshots in case.

File: br/pkg/aws/ebs.go [hunk 3]
```diff
@@ -324,8 +327,64 @@ func (e *EC2Session) EnableDataFSR(meta *config.EBSBasedBRMeta, targetAZ string)
...
+		} else {
+			if creditBalance == 0 {
+				if retryCount >= 3 {
+					return errors.Errorf("cloudwatch metrics for %s operation failed after retrying", *snapShotIDs[startIdx])
+				}
+				retryCount++
+			}
+			time.Sleep(1 * time.Minute)
+		}
+	}
```
Comment (nkg-) [inline br/pkg/aws/ebs.go:386]: Not a blocking comment. Now that you are checking the actual fsrCreditBalance, why do you still want to keep the time based heuristic in 351-360.

File: br/pkg/aws/ebs.go (hunk 1 above)
Comment (nkg-) [reply br/pkg/aws/ebs.go:390]: What does this mean. What conflicts?

File: br/pkg/aws/ebs.go [hunk 4]
```diff
@@ -378,6 +437,50 @@ func (e *EC2Session) waitDataFSREnabled(snapShotIDs []*string, targetAZ string)
 	}
 }
 
+// getFSRCreditBalance is used to get maximum fsr credit balance of snapshot for last 5 minutes
+func (e *EC2Session) getFSRCreditBalance(snapshotID *string, targetAZ string) (float64, error) {
+	// Set the time range to query for metrics
+	startTime := time.Now().Add(-5 * time.Minute)
+	endTime := time.Now()
+
+	// Prepare the input for the GetMetricData API call
```
Comment (nkg-) [inline br/pkg/aws/ebs.go:446]: Nit: s/GetMetricData/GetMetricStatisticsWithContext/

File: br/pkg/aws/ebs.go [hunk 5]
```diff
@@ -324,8 +327,64 @@ func (e *EC2Session) EnableDataFSR(meta *config.EBSBasedBRMeta, targetAZ string)
...
+	// Wait that all snapshot has enough fsr credit balance, it's very likely true since we have wait for long enough
+	log.Info("Start check and wait all snapshots have enough fsr credit balance")
+
+	startIdx := 0
+	retryCount := 0
+	for startIdx < len(snapShotIDs) {
+		creditBalance, err := e.getFSRCreditBalance(snapShotIDs[startIdx], targetAZ)
+		if err != nil {
+			return errors.Trace(err)
+		}
```
Comment (nkg-) [inline br/pkg/aws/ebs.go:372]: You should retry if the api fails. Similar to retry below for `creditBalance == 0` (from "No result for metric"). Maybe for that, you can return an error as well. And consolidate the retry logic.

File: br/pkg/aws/ebs.go [hunk 6]
```diff
@@ -591,12 +698,16 @@ func ec2Tag(key, val string) *ec2.Tag {
...
 }
 
-func (e *EC2Session) HandleDescribeVolumesResponse(resp *ec2.DescribeVolumesOutput) (int64, []*string) {
+func (e *EC2Session) HandleDescribeVolumesResponse(resp *ec2.DescribeVolumesOutput, fsrEnabledRequired bool) (int64, []*string, error) {
 	totalVolumeSize := int64(0)
 
 	var unfinishedVolumes []*string
 	for _, volume := range resp.Volumes {
 		if *volume.State == ec2.VolumeStateAvailable {
+			if fsrEnabledRequired && !*volume.FastRestored {
```
Comment (nkg-) [inline br/pkg/aws/ebs.go:707]: Nice! Makes sense to check the FSR status of the restored volume as well

File: br/pkg/aws/ebs.go (hunk 5 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go:372]: Error here comes from a cloudwatch api service, it's an AWS service issue and retrying might not solve the problem.

File: br/pkg/aws/ebs.go (hunk 3 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go:386]: It's possible cloud watch data is not synced up yet. So, I issued 3 times retrying at 1 minute intervals.

File: br/pkg/aws/ebs.go (hunk 5 above)
Comment (YuJuncen) [reply br/pkg/aws/ebs.go:372]: The AWS API should have an [internal retry](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/#standard-retryer) of about 20 seconds. Is this enough? 🤔

File: br/pkg/aws/ebs.go [hunk 7]
```diff
@@ -378,6 +437,50 @@ func (e *EC2Session) waitDataFSREnabled(snapShotIDs []*string, targetAZ string)
...
+	// Call cloudwatchClient API to retrieve the FastSnapshotRestoreCreditsBalance metric data
+	resp, err := e.cloudwatchClient.GetMetricStatisticsWithContext(context.Background(), input)
+	if err != nil {
+		return 0, errors.Trace(err)
+	}
+
+	// parse the response
+	if len(resp.Datapoints) == 0 {
+		log.Warn("No result for metric FastSnapshotRestoreCreditsBalance returned", zap.Stringp("snapshot", snapshotID))
+		return 0, nil
```
Comment (YuJuncen) [inline br/pkg/aws/ebs.go:477]: I will prefer returning a `NaN` here and retry if the result is `Nan`. Zero should be a meaningful result of this series. Once AWS changes their algorithm of fulfilling credits (say, refresh the credit every 30 minutes.), we may fail in that case.
Returning an error and retry will also be fine I guess.

**Review by YuJuncen — APPROVED** [review]
generally lgtm

File: br/pkg/aws/ebs.go (hunk 5 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go:372]: > The AWS go SDK should have an [internal retry](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/#standard-retryer) of about 20 seconds. Is this enough? 🤔

Make sense. Checking from https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Alarms.html, the default cloudwatch interval is 5 seconds.

File: br/pkg/aws/ebs.go (hunk 7 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go]: Changed are made accordinngly.

File: br/pkg/aws/ebs.go [hunk 8]
```diff
@@ -324,8 +327,63 @@ func (e *EC2Session) EnableDataFSR(meta *config.EBSBasedBRMeta, targetAZ string)
...
+	}
+
+	// Wait that all snapshot has enough fsr credit balance, it's very likely true since we have wait for long enough
+	log.Info("Start check and wait all snapshots have enough fsr credit balance")
+
+	startIdx := 0
+	retryCount := 0
+	for startIdx < len(snapShotIDs) {
+		creditBalance, _ := e.getFSRCreditBalance(snapShotIDs[startIdx], targetAZ)
+		if creditBalance != nil && *creditBalance >= 1.0 {
```
Comment (3pointer) [inline br/pkg/aws/ebs.go:370]: if creditBalance > 0 && `creditBalance < 1.0. shall we sleep and retry too?

**Review by 3pointer — APPROVED** [review]

File: br/pkg/aws/ebs.go [hunk 9]
```diff
@@ -324,8 +327,63 @@ func (e *EC2Session) EnableDataFSR(meta *config.EBSBasedBRMeta, targetAZ string)
...
+	start := time.Now()
+
+	//  get the maximum size of volumes, in GiB
+	var maxVolumeSize int64 = 0
+	resp, err := e.ec2.DescribeSnapshots(&ec2.DescribeSnapshotsInput{SnapshotIds: snapShotIDs})
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if len(resp.Snapshots) <= 0 {
+		return errors.Errorf("specified snapshot [%s] is not found", *snapShotIDs[0])
```
[the remark this answers is not in the document]
Comment (BornChanger) [reply br/pkg/aws/ebs.go:342]: The caller has checked the empty set.

File: br/pkg/aws/ebs.go (hunk 8 above)
Comment (BornChanger) [reply br/pkg/aws/ebs.go:370]: Yes. It's true
