### PR TITLE
expression: explore all possibilities of tryToReplaceCond as much as possible

### LINKED ISSUE #64325: it is unstable to push down the predicate
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```

func TestABC(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec(`CREATE TABLE t1 (a int PRIMARY KEY, b int);`)
	tk.MustExec(`CREATE TABLE t2 (a int PRIMARY KEY, b int);`)
	for i := range 100 {
		t.Log(i)
		tk.MustQuery(`EXPLAIN FORMAT='plan_tree' SELECT STRAIGHT_JOIN * FROM t1 LEFT JOIN t2 ON t1.a = t2.a WHERE t1.a IN(t2.a, t2.b);`).Check(testkit.Rows(
			`MergeJoin root  inner join, left key:test.t1.a, right key:test.t2.a, other cond:in(test.t1.a, test.t2.a, test.t2.b)`,
			`├─TableReader(Build) root  data:Selection`,
			`│ └─Selection cop[tikv]  in(test.t2.a, test.t2.a, test.t2.b)`,
			`│   └─TableFullScan cop[tikv] table:t2 keep order:true, stats:pseudo`,
			`└─TableReader(Probe) root  data:TableFullScan`,
			`  └─TableFullScan cop[tikv] table:t1 keep order:true, stats:pseudo`))
	}
}
```

### 2. What did you expect to see? (Required)

```
MergeJoin root  inner join, left key:test.t1.a, right key:test.t2.a, other cond:in(test.t1.a, test.t2.a, test.t2.b)
├─TableReader(Build) root  data:Selection
│ └─Selection cop[tikv]  in(test.t2.a, test.t2.a, test.t2.b)
│   └─TableFullScan cop[tikv] table:t2 keep order:true, stats:pseudo
└─TableReader(Probe) root  data:TableFullScan
```
### 3. What did you see instead (Required)

```
MergeJoin root  inner join, left key:test.t1.a, right key:test.t2.a, other cond:in(test.t1.a, test.t2.a, test.t2.b)
├─TableReader(Build) root  data:TableFullScan
│ └─TableFullScan cop[tikv] table:t2 keep order:true, stats:pseudo
└─TableReader(Probe) root  data:TableFullScan
```

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #64325

Problem Summary:

### What changed and how does it work?

The case is like this.

It has a join, and the schemas of the two children are as follows.

```
right schema: [3,4]
left schema: [1,2]
```

It has an equal condition `1=3` and now we need to perform constant propagation on the following expressions.

```
1 in (3, 4)
```

The order of  1=3  will affect the changes here in the tryToReplaceCond.

When we call tryToReplaceCond to replace 3 by 1. `1 in (1,4)` has two columns, which are in the difference schema. So it cannot push down the child.

But the problem is that it will not continue to try to replace 1 by 3. If it can do it,
`3 in (3,4)` can push down into the child.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/expression/constant_propagation.go [hunk 1]
```diff
@@ -371,18 +371,16 @@ func (s *propConstSolver) propagateColumnEQ() {
 				replaced, _, newExpr := tryToReplaceCond(s.ctx, coli, colj, cond, false)
 				if replaced {
 					// TODO(hawkingrei): if it is the true expression, we can remvoe it.
-					if !isConstant(newExpr) && s.vaildExprFunc != nil && !s.vaildExprFunc(newExpr) {
-						continue
+					if isConstant(newExpr) || s.vaildExprFunc == nil || s.vaildExprFunc(newExpr) {
```
Comment (AilinKid) [inline pkg/expression/constant_propagation.go:374]: looks like revert the inside out？
there is no quick continue, and it will fall into L378?

Comment (AilinKid) [reply pkg/expression/constant_propagation.go:374]: better comment what the specific case , what kind of expression you want to explore and pushdown here

Comment (hawkingrei) [reply pkg/expression/constant_propagation.go:374]: Done
