### PR TITLE
ddl: better error handling during PauseJobs/ResumeJobs/CancelJobs

### LINKED ISSUE #44002: can not pause the ddl job while upgrade cluster(`admin pause/resume/cancel ddl jobs` needs return error correctly)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. using tiup deploy a cluster with 3 tidb instances
2. load some data and do add index
3. upgrade cluster during add index
4. check the ddl jobs

### 2. What did you expect to see? (Required)
1. paused the user ddl during upgrade cluster
2. upgrade the cluster success 
### 3. What did you see instead (Required)
1. tiup cluster upgrade report timeout 
```bash
Starting component `cluster`: /root/.tiup/components/cluster/v1.12.1/tiup-cluster /root/.tiup/components/cluster/v1.12.1/tiup-cluster upgrade ddl_upgrade nightly --pre-upgrade-script sh /home/tidb/prescript.sh -y
Error: failed to restart: tidb-1-peer tidb-4000.service, please check the instance's log(/tiup/deploy/tidb-4000/log) for more detail.: timed out waiting for port 4000 to be started after 2m0s
Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2023-05-19-14-43-21.log.
```
2. user ddl state is pausing and running continue
图片
3. some mock ddl start_time is after the user ddl end_time
图片

### 4. What is your TiDB version? (Required)
图片

### PR DESCRIPTION
**Pull request by dhysum**
### What problem does this PR solve?

Issue Number: close #44002 

Problem Summary:

Once try times are exhausted, it should return en error, but now it just return nil as error.

### What is changed and how it works?

Return error if try too much times during `admin pause/resume/cancel ddl jobs`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Comment by zimulala** [comment]
Duplicated with https://github.com/pingcap/tidb/pull/44006/files？

File: ddl/ddl.go [hunk 1]
```diff
@@ -1507,10 +1507,10 @@ func resumePausedJob(se *sess.Session, job *model.Job,
 func processJobs(process func(*sess.Session, *model.Job, model.AdminCommandOperator) (err error),
 	sessCtx sessionctx.Context,
 	ids []int64,
-	byWho model.AdminCommandOperator) ([]error, error) {
+	byWho model.AdminCommandOperator) (jobErrs []error, err error) {
 	failpoint.Inject("mockFailedCommandOnConcurencyDDL", func(val failpoint.Value) {
 		if val.(bool) {
-			failpoint.Return(nil, errors.New("mock commit error"))
+			failpoint.Return(nil, errors.New("mock failed admin command on ddl jobs"))
```
Comment (zimulala) [inline ddl/ddl.go:1513]: Do we need to update this error to distinguish error messages with https://github.com/pingcap/tidb/pull/44007/files#diff-a185df836b8926c4afe351d4def1b56d1e282c65aabe6677c2fa2c54590cc4b2R1568？

File: ddl/ddl.go [hunk 2]
```diff
@@ -1547,36 +1545,43 @@ func processJobs(process func(*sess.Session, *model.Job, model.AdminCommandOpera
...
 
 			err = updateDDLJob2Table(ns, job, true)
 			if err != nil {
-				errs[i] = err
+				jobErrs[i] = err
 				continue
 			}
 		}
 
+		failpoint.Inject("mockCommitFailedOnDDLCommand", func(val failpoint.Value) {
```
Comment (zimulala) [inline ddl/ddl.go:1566]: It seems we can use `mockCommitErrorInNewTxn` instead of this one, so we can remove this one.

Comment (dhysum) [reply ddl/ddl.go:1566]: It doesn't work though.

Comment (zimulala) [reply ddl/ddl.go:1566]: It feels like `TestCancelJobWriteConflict` is working. Why doesn't pause work?

Comment (dhysum) [reply ddl/ddl.go:1566]: No.

It works because of `mockFailedCommandOnConcurencyDDL`, but not `mockCommitErrorInNewTxn`.

Comment (dhysum) [reply ddl/ddl.go:1566]: Or, could we redesign the whole test here later on? The scattered 'fail point' may need to be reviewed as a whole.

`mockCommitErrorInNewTxn` is injected in `RunInNewTxn` while `mockCommitError` is injected in `doCommit`, and they look like two different transaction mechanism. Here in `cancel`, `pause` and `resume`, they are using the `doCommit` but not `RunInNewTxn` which may need to be reviewed too.

**Review by zimulala — APPROVED** [review]
LGTM

**Review by Benjamin2037 — APPROVED** [review]
LGTM
