### PR TITLE
br: deal with mddljob when pitr restores

### LINKED ISSUE #35372: log-backup: drop table meta only, not delete record and index belonged to table.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
log backup
- create log-backup task by command `br log start` in upstream-cluster;
- create table `t` and insert several records;
- drop table `t` in upstream-cluster;

restore point
- restore these logs above by command `br restore point`;

### 2. What did you expect to see? (Required)
- The table meta and record/index belonged to table should be removed from TiKV.

### 3. What did you see instead (Required)
- The table meta has been removed  but record/index not.

### 4. What is your TiDB version? (Required)
- tidb-6.2.0-nighty

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #35372

Problem Summary: drop table meta only, not delete record and index belonged to table.

### What is changed and how it works?

deal with the mddl job, and insert rows into table `mysql.gc_delete_range`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/stream/rewrite_meta_rawkv.go [hunk 1]
```diff
@@ -461,3 +469,318 @@ func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string) (*kv.Entry, err
...
+		if len(physicalTableIDs) > 0 {
+			// delete partition id instead of table id
+			for i := 0; i < len(physicalTableIDs); i++ {
+				newPid, exist := tableReplace.PartitionMap[physicalTableIDs[i]]
+				if !exist {
+					return errors.Errorf("DropTable/TruncateTable: try to drop a non-existent table, missing oldPartitionID")
+				}
+				physicalTableIDs[i] = newPid
+			}
+			if err := insertDeleteRangeForTable(ctx, newJobID, physicalTableIDs, sr.RewriteTS); err != nil {
```
Comment (3pointer) [inline br/pkg/stream/rewrite_meta_rawkv.go:572]: is `sr.RewriteTS` can make sure that GC worker won't start load this task until we finish the point restore?

**Comment by 3pointer** [comment]
need format code https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check/detail/tidb_ghpr_check/71143/pipeline

File: br/pkg/stream/rewrite_meta_rawkv.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/stream/rewrite_meta_rawkv.go:570]: sr.RewriteTS is the timestamp when restore starts. Generally, db starts gc these ranges in about 10 minutes.

gc will be done in advance, if restore takes more than 10 mins. In this case, rows will be moved to table `gc_delete_range_done` from table `gc_delete_range`, so that some kvs may be still retained. 😭

Comment (Leavrth) [reply br/pkg/stream/rewrite_meta_rawkv.go]: insert rows into `gc_delete_range` after `RestoreKVFiles` is done.

File: br/pkg/stream/rewrite_meta_rawkv.go [hunk 2]
```diff
@@ -432,9 +432,19 @@ func (sr *SchemasReplace) rewriteValue(
...
 
 // RewriteKvEntry uses to rewrite tableID/dbID in entry.key and entry.value
-func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string) (*kv.Entry, error) {
+func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string, insertDeleteRangeForTable InsertDeleteRangeForTable, insertDeleteRangeForIndex InsertDeleteRangeForIndex) (*kv.Entry, error) {
 	// skip mDDLJob
+
 	if !strings.HasPrefix(string(e.Key), "mDB") {
+		if strings.HasPrefix(string(e.Key), "mDDLJobH") { // mDDLJobHistory
+			job := &model.Job{}
+			if err := job.Decode(e.Value); err != nil {
```
Comment (3pointer) [inline br/pkg/stream/rewrite_meta_rawkv.go:441]: miss return?

Comment (Leavrth) [reply br/pkg/stream/rewrite_meta_rawkv.go:441]: done

**Review by joccau — APPROVED** [review]
rest LGTM

File: br/pkg/stream/rewrite_meta_rawkv.go [hunk 3]
```diff
@@ -432,9 +432,21 @@ func (sr *SchemasReplace) rewriteValue(
 }
 
 // RewriteKvEntry uses to rewrite tableID/dbID in entry.key and entry.value
-func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string) (*kv.Entry, error) {
+func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string, insertDeleteRangeForTable InsertDeleteRangeForTable, insertDeleteRangeForIndex InsertDeleteRangeForIndex) (*kv.Entry, error) {
 	// skip mDDLJob
+
```
Comment (joccau) [inline br/pkg/stream/rewrite_meta_rawkv.go:437]: whether it has some different value between default-cf and write-cf ?

File: br/pkg/restore/client.go [hunk 4]
```diff
@@ -1976,6 +1983,111 @@ func (rc *Client) UpdateSchemaVersion(ctx context.Context) error {
...
+			if j != batchEnd-1 {
+				buf.WriteString(",")
+			}
+			elementID += 1
+		}
+		rc.deleteRangeQueryCh <- buf.String()
+	}
+}
+
+// insertDeleteRangeForTable generates query to insert index delete job into table `gc_delete_range`.
```
Comment (joccau) [inline br/pkg/restore/client.go:2021]:
```suggestion
// InsertDeleteRangeForIndex generates query to insert index delete job into table `gc_delete_range`.
```

File: br/pkg/restore/client.go [hunk 5]
```diff
@@ -1976,6 +1983,111 @@ func (rc *Client) UpdateSchemaVersion(ctx context.Context) error {
...
+func (rc *Client) InsertDeleteRangeForIndex(jobID int64, elementID *int64, tableID int64, indexIDs []int64) {
```
Comment (3pointer) [inline br/pkg/restore/client.go:2022]: why use `elementID` pointer here?🤔

File: br/pkg/stream/rewrite_meta_rawkv.go [hunk 6]
```diff
@@ -432,9 +432,21 @@ func (sr *SchemasReplace) rewriteValue(
...
 	if !strings.HasPrefix(string(e.Key), "mDB") {
+		if strings.HasPrefix(string(e.Key), "mDDLJobH") { // mDDLJobHistory
+			job := &model.Job{}
+			if err := job.Decode(e.Value); err != nil {
+				log.Debug("failed to decode the job", zap.String("error", err.Error()), zap.String("job", string(e.Value)))
+				// some mddlJob kv's value is not json data, just skip it
```
Comment (3pointer) [inline br/pkg/stream/rewrite_meta_rawkv.go:443]: maybe explain why some mddlJob kv's value is not json data and give a clear comment here

File: br/pkg/task/stream.go [hunk 7]
```diff
@@ -1103,6 +1104,10 @@ func restoreStream(
 		return errors.Annotate(err, "failed to clean up")
 	}
 
+	if err = client.InsertGCRows(ctx); err != nil {
```
Comment (3pointer) [inline br/pkg/task/stream.go:1107]: If we had error here. the cluster still can be used. so I think we can put it at last after `client.SaveSchemas`. WDYT?

File: br/pkg/stream/rewrite_meta_rawkv.go (hunk 3 above)
Comment (Leavrth) [reply br/pkg/stream/rewrite_meta_rawkv.go:437]: It seems that the key with prefix `mddlJobHistory` whose value can be decoded into `model.Job` uses default-cf. Maybe we can directly try to decode the value ignoring its cf.

File: br/pkg/restore/client.go (hunk 5 above)
Comment (Leavrth) [reply br/pkg/restore/client.go:2022]: For example, a table with 3 partitions, we need to remove each partition's indexes. They have the same jobID while the table `gc_delete_range`'s primary key is (jobID, elementID), so each partition's elementIDs should be different.

Otherwise, we can use function InsertDeleteRangeForIndex(jobID int64, tableID []int64, indexIDs []int64) to remove paramter `elementID`

File: br/pkg/stream/rewrite_meta_rawkv.go (hunk 6 above)
Comment (Leavrth) [reply br/pkg/stream/rewrite_meta_rawkv.go]: done.  Please take another look.

File: br/pkg/stream/rewrite_meta_rawkv.go [hunk 8]
```diff
@@ -432,9 +432,22 @@ func (sr *SchemasReplace) rewriteValue(
...
+func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string, insertDeleteRangeForTable InsertDeleteRangeForTable, insertDeleteRangeForIndex InsertDeleteRangeForIndex) (*kv.Entry, error) {
 	// skip mDDLJob
+
 	if !strings.HasPrefix(string(e.Key), "mDB") {
+		if strings.HasPrefix(string(e.Key), "mDDLJobH") { // mDDLJobHistory
+			job := &model.Job{}
+			if err := job.Decode(e.Value); err != nil {
+				log.Debug("failed to decode the job", zap.String("error", err.Error()), zap.String("job", string(e.Value)))
+				// The value in write-cf is like "p\XXXX\XXX" need not restore. skip it
+				// The valud in default-cf that can Decode() need restore.
```
Comment (3pointer) [inline br/pkg/stream/rewrite_meta_rawkv.go:444]:
```suggestion
				// The value in default-cf that can Decode() need restore.
```

**Review by 3pointer — APPROVED** [review]
rest LGTM

**Comment by Leavrth** [comment]
issue: https://github.com/pingcap/tidb/issues/34742

Temporary version: return error when meet ddl `exchange-table-partition`

File: br/pkg/stream/rewrite_meta_rawkv.go [hunk 9]
```diff
@@ -432,9 +432,26 @@ func (sr *SchemasReplace) rewriteValue(
 }
 
 // RewriteKvEntry uses to rewrite tableID/dbID in entry.key and entry.value
-func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string) (*kv.Entry, error) {
+func (sr *SchemasReplace) RewriteKvEntry(e *kv.Entry, cf string, insertDeleteRangeForTable InsertDeleteRangeForTable, insertDeleteRangeForIndex InsertDeleteRangeForIndex) (*kv.Entry, error) {
 	// skip mDDLJob
+
 	if !strings.HasPrefix(string(e.Key), "mDB") {
+		if strings.HasPrefix(string(e.Key), "mDDLJobH") { // mDDLJobHistory
```
Comment (joccau) [inline br/pkg/stream/rewrite_meta_rawkv.go:439]: check the condition `cf == default_cf`, I suggest.
