### PR TITLE
planner/core: add missing GeneratedColumnFlag for TiFlash store

### LINKED ISSUE #59831: GeneratedColumn flag is missed when push down table scan to tiflash for partition table
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/75695928b955564835e1284dcdc2c7785cfe1d67/pkg/table/tables/tables.go#L1781-L1793

L1785 calls `ColumnsToProto()`, it assume `isTiFlashStore` is false(the last argument), which is wrong. Because tiflash can also call this function.

And the `GeneratedColumnFlag` will be missed because this bug, check https://github.com/pingcap/tidb/blob/75695928b955564835e1284dcdc2c7785cfe1d67/pkg/util/misc.go#L425

In most case, tiflash will fill default value into this virtual generated column. But sometimes tiflash will not see the schema of virtual column (check https://github.com/pingcap/tidb/issues/40663#issuecomment-1385138160), and issue/40663 will happen.

### 4. What is your TiDB version? (Required)
master 75695928b955564835e1284dcdc2c7785cfe1d67

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #59831

Problem Summary:

In https://github.com/pingcap/tidb/pull/55463, we moved the logic of adding `GeneratedColumnFlag` from the plan-building phase into `ColumnToProto()`, to prevent mutating `*model.ColumnInfo` pointers shared via the infoschema cache. However, the `isTiFlashStore` parameter was incorrectly set to `false` in two call sites:

1. **`BuildPartitionTableScanFromInfos`** (`tables.go`) — This function is exclusively called from `partitionTableScanToPBForFlash()`, so it is always a TiFlash code path. It should pass `isTiFlashStore=true`.
2. **Vector search `ColumnToProto` call** (`find_best_task.go`) — Vector search always goes through TiFlash, so `isTiFlashStore` should be `true`.

As a result, for **partitioned tables** with **virtual generated columns** queried through **TiFlash MPP with dynamic partition pruning**, the `GeneratedColumnFlag` was missing from the protobuf sent to TiFlash. TiFlash uses this flag to know a column is virtual-generated and should have a placeholder value. Without it, TiFlash may mishandle the column during schema desynchronization (the rare condition described in https://github.com/pingcap/tidb/issues/40663).

The bug is hard to reproduce at the SQL level because TiFlash usually computes virtual columns from its own schema regardless of the flag — the failure only occurs when TiFlash doesn't have the virtual column schema (a race condition during DDL schema changes).

### What changed and how does it work?

1. `BuildPartitionTableScanFromInfos`: Changed `isTiFlashStore` from `false` to `true` (this function is only used for TiFlash).
2. `ColumnToProto` for vector prop: Changed `isTiFlashStore` from `false` to `true` (vector search always goes through TiFlash).
3. Added `TestGeneratedColumnFlagForTiFlash` unit test that verifies `BuildPartitionTableScanFromInfos` correctly sets the `GeneratedColumnFlag` on virtual generated columns. The test fails on master and passes with the fix.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

## Release Notes

* **New Features**
  * Enhanced compression ratio estimation mechanism for data import operations.

* **Refactor**
  * Optimized control flow in index scan processing.

* **Tests**
  * Added test coverage for TiFlash-specific behavior.

* **Chores**
  * Updated statistics schema with new column.
  * Removed unused API methods (QueryBytes, ExtractTopN).
  * Improved TiFlash support for vector index and partition table scans.

### CODE REVIEW

File: pkg/planner/core/find_best_task.go [hunk 1]
```diff
@@ -2419,7 +2419,7 @@ func convertToTableScan(ds *logicalop.DataSource, prop *property.PhysicalPropert
 				prop.VectorProp.TopK,
 				ts.Table.Columns[candidate.path.Index.Columns[0].Offset].Name.L,
```
Comment (hawkingrei) [inline pkg/planner/core/find_best_task.go:2605]: Can you add a test case for it?

Comment (joechenrh) [reply pkg/planner/core/find_best_task.go:2605]: I can't reproduce the problem for now. Do you have some advices on how to add test case?

**Review by AilinKid — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
