### PR TITLE
ddl: fix bug when create primary key with invisible index

### LINKED ISSUE #17066: Expect throw error when create primary key with invisible index
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```sql
create table t1(c1 int not null, primary key(c1) invisible);
```

### 2. What did you expect to see?

```
mysql> create table t1(c1 int not null, primary key(c1) invisible);
ERROR 3522 (HY000): A primary key index cannot be invisible
```

### 3. What did you see instead?

```
mysql> create table t1(c1 int NOT NULL, primary key(c1) invisible); 
Query OK, 0 rows affected (0.01 sec) 
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

c70ed2a22c75c17722a2f9b7a9213e02396fade9

### PR DESCRIPTION
**Pull request by Deardrops**
### What problem does this PR solve?

Issue Number: close #17066 

Problem Summary:

Expect throw error when create primary key with invisible index

### What is changed and how it works?

What's Changed:

When meet the case `pk_is_handle`, do a check if primary key is invisible.

How it Works:

Before this PR, when `pk_is_handle`, it will skip create a **real** index struct on for primary key, so we cannot check if primary key is invisible index when iterator all index struct on a table.

In this PR, we add a check for this case.

### Related changes

- None

### Check List 

Tests 

- Manual test

Side effects

- None

### Release note 
- Nothing to say.

### CODE REVIEW

File: ddl/serial_test.go [hunk 1]
```diff
@@ -163,6 +163,12 @@ func (s *testSerialSuite) TestPrimaryKey(c *C) {
 	tk.MustExec("alter table tt add index (`primary`);")
 	_, err = tk.Exec("drop index `primary` on tt")
 	c.Assert(err.Error(), Equals, "[ddl:8200]Unsupported drop primary key when alter-primary-key is false")
+
+	// primary key cannot be invisible, for the case pk_is_handle
```
Comment (zimulala) [inline ddl/serial_test.go:167]:
```suggestion
	// The primary key cannot be invisible, for the case pk_is_handle.
```

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -1243,6 +1249,11 @@ func buildTableInfo(
 				switch lastCol.Tp {
 				case mysql.TypeLong, mysql.TypeLonglong,
 					mysql.TypeTiny, mysql.TypeShort, mysql.TypeInt24:
+					// Primary key cannot be invisible
```
Comment (zimulala) [inline ddl/ddl_api.go:1252]: Please add `.` at the end of a complete line.

File: ddl/ddl_api.go [hunk 3]
```diff
@@ -1106,6 +1106,12 @@ func checkConstraintNames(constraints []*ast.Constraint) error {
 
 // checkInvisibleIndexOnPK check if primary key is invisible index.
 func checkInvisibleIndexOnPK(tblInfo *model.TableInfo) error {
+	// PKIsHandle == true means the table already has a visible primary key,
```
Comment (bb7133) [inline ddl/ddl_api.go:1109]: Please move this comment above the signature of this function(L1107) so that it is more obvious to the possible developers in the future.

Comment (Deardrops) [reply ddl/ddl_api.go]: @bb7133 addressed, PTAL

**Comment by Deardrops** [comment]
./run-common-test tidb-test=pr/1055
