### PR TITLE
planner: fix "can't find column" when projection wrongly added above table reader after agg pushed down

### LINKED ISSUE #23736: Can't find column in schema Column: [Column#10] Unique key: [] when using stream_agg()  hint
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table t0(a int, b int, c int as (a + b) virtual, unique index (c) invisible);
create table t1(a int, b int, c int as (a + b) virtual);
insert into t0(a, b) values (12, -1), (8, 7);
insert into t1(a, b) values (12, -1), (8, 7);
select /*+ stream_agg() */ count(1) from t0 where c > 10 and b < 2;
select /*+ stream_agg() */ count(1) from t1 where c > 10 and b < 2;
```

### 2. What did you expect to see? (Required)
```sql
mysql > select /*+ stream_agg() */ count(1) from t0 where c > 10 and b < 2;
+----------+
| count(1) |
+----------+
| 1        |
+----------+

1 row in set
Time: 0.133s
mysql > select /*+ stream_agg() */ count(1) from t1 where c > 10 and b < 2;
+----------+
| count(1) |
+----------+
| 1        |
+----------+

```
### 3. What did you see instead (Required)
```sql
mysql > select /*+ stream_agg() */ count(1) from t0 where c > 10 and b < 2;
(1105, "Can't find column hchwang.t0.b in schema Column: [Column#6] Unique key: []")
mysql > select /*+ stream_agg() */ count(1) from t1 where c > 10 and b < 2;
(1105, "Can't find column hchwang.t1.b in schema Column: [Column#6] Unique key: []")
```
### 4. What is your TiDB version? (Required)
master: f43f750fb551f2f

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve?

Issue Number: close #23736 

Problem Summary:

A projection was added between the partial agg and the final agg, and the schema between them was broken.

### What is changed and how it works?

Not to add the extra projection if the agg was pushed down.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- no release note.

### CODE REVIEW

File: planner/core/task.go [hunk 1]
```diff
@@ -960,7 +960,20 @@ func (t *copTask) convertToRootTaskImpl(ctx sessionctx.Context) *rootTask {
...
+		// If we add the projection here, the projection will be between the final agg and the partial agg, then the
+		// schema will be broken, the final agg will fail to find needed columns in ResolveIndices().
+		// Besides, the agg would only be pushed down if it doesn't contain virtual columns, so virtual column should not be affected.
+		aggPushedDown := false
+		switch p.tablePlan.(type) {
+		case *PhysicalHashAgg, *PhysicalStreamAgg:
+			aggPushedDown = true
+		}
+
+		if needExtraProj && !aggPushedDown {
```
Comment (wjhuang2016) [inline planner/core/task.go:976]: If we don't add the selection here, where should we add it?

Comment (time-and-fate) [reply planner/core/task.go:976]: Sorry...I didn't get it. This change should only affect the PhysicalProjection.

Comment (wjhuang2016) [reply planner/core/task.go:976]: Sorry,  I was wrong.

File: planner/core/task.go [hunk 2]
```diff
@@ -960,7 +960,20 @@ func (t *copTask) convertToRootTaskImpl(ctx sessionctx.Context) *rootTask {
 		}.Init(ctx, t.tablePlan.SelectBlockOffset())
 		p.PartitionInfo = t.partitionInfo
 		p.stats = t.tablePlan.statsInfo()
-		if needExtraProj {
+
+		// If agg was pushed down, the partial agg was placed on the top of tablePlan, the final agg will be placed
```
Comment (wjhuang2016) [inline planner/core/task.go:964]: s/was/is

Comment (time-and-fate) [reply planner/core/task.go]: I prefer "was" because when it comes here, the "push down" process has been done.
I slightly changed the comments to try to make it more clear, do you think it's ok?

**Review by winoros — APPROVED** [review]
i got the idea.
Root cause is that planner haven't done any pruning after push plan into the tikv.

**Comment by winoros** [comment]
It's a little hard for now to not add projection when the virtual column only occurs in the where clause not in the select fields.

File: planner/core/integration_test.go [hunk 3]
```diff
@@ -3134,3 +3134,14 @@ func (s *testIntegrationSuite) TestMultiColMaxOneRow(c *C) {
...
 }
+
+func (s *testIntegrationSuite) TestIssue23736(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("create table t0(a int, b int, c int as (a + b) virtual, unique index (c) invisible);")
+	tk.MustExec("create table t1(a int, b int, c int as (a + b) virtual);")
+	tk.MustExec("insert into t0(a, b) values (12, -1), (8, 7);")
+	tk.MustExec("insert into t1(a, b) values (12, -1), (8, 7);")
+	tk.MustQuery("select /*+ stream_agg() */ count(1) from t0 where c > 10 and b < 2;").Check(testkit.Rows("1"))
```
Comment (wjhuang2016) [inline planner/core/integration_test.go:3145]: the result is wrong:
``` sql
mysql> select * from t0;
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    5 |    1 |    6 |
+------+------+------+
1 row in set (0.00 sec)

mysql> select /*+ stream_agg() */ count(1) from t0 where c > 10 and b < 2;
+----------+
| count(1) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)

mysql> desc select /*+ stream_agg() */ count(1) from t0 where c > 10 and b < 2;
+--------------------------------+---------+-----------+---------------+--------------------------------+
| id                             | estRows | task      | access object | operator info                  |
+--------------------------------+---------+-----------+---------------+--------------------------------+
| StreamAgg_9                    | 1.00    | root      |               | funcs:count(1)->Column#5       |
| └─Selection_18                 | 1.00    | root      |               | gt(test.t0.c, 10)              |
|   └─Projection_17              | 1.00    | root      |               | test.t0.b, test.t0.c           |
|     └─TableReader_16           | 0.11    | root      |               | data:Selection_15              |
|       └─Selection_15           | 0.11    | cop[tikv] |               | lt(test.t0.b, 2)               |
|         └─TableFullScan_14     | 1.00    | cop[tikv] | table:t0      | keep order:false, stats:pseudo |
+--------------------------------+---------+-----------+---------------+--------------------------------+
6 rows in set (0.00 sec)
```

**Review by wjhuang2016 — CHANGES_REQUESTED** [review]

File: planner/core/integration_test.go (hunk 3 above)
Comment (time-and-fate) [reply planner/core/integration_test.go:3145]: Nice catch!

An example wrong query plan:
```
+------------------------------+---------+-----------+---------------+------------------------------------+
| id                           | estRows | task      | access object | operator info                      |
+------------------------------+---------+-----------+---------------+------------------------------------+
| HashAgg_13                   | 1.00    | root      |               | funcs:count(Column#6)->Column#5    |
| └─TableReader_14             | 1.00    | root      |               | data:HashAgg_6                     |
|   └─HashAgg_6                | 1.00    | cop[tikv] |               | funcs:count(1)->Column#6           |
|     └─Selection_12           | 0.11    | cop[tikv] |               | lt(test.t0.b, 2), lt(test.t0.b, 2) |
|       └─TableFullScan_11     | 1.00    | cop[tikv] | table:t0      | keep order:false, stats:pseudo     |
+------------------------------+---------+-----------+---------------+------------------------------------+
```

The reason is that in `getOriginalPhysicalTableScan()`, the PhysicalTableScan.filterCondition and path.TableFilters share the same underlying array.

https://github.com/pingcap/tidb/blob/91bcb21b57bd07f77987e144dc63f1e8efc793ce/planner/core/find_best_task.go#L1744-L1757

When it is modified in addPushedDownSelection() => SplitSelCondsWithVirtualColumn()
https://github.com/pingcap/tidb/blob/cd5b91fa0388091d720e8554161b983ee980eab0/planner/core/find_best_task.go#L1527

https://github.com/pingcap/tidb/blob/91bcb21b57bd07f77987e144dc63f1e8efc793ce/planner/core/find_best_task.go#L1728-L1729

https://github.com/pingcap/tidb/blob/91bcb21b57bd07f77987e144dc63f1e8efc793ce/planner/core/find_best_task.go#L1184-L1193

Actually, what L1189 doing is changing the underlying array from [c > 10, b < 2] into [b < 2, b < 2]

The original AccessPath.TableFilters is also modified, all the plans generated after this are all wrong.

**Review by wjhuang2016 — APPROVED** [review]

**Review by winoros — APPROVED** [review]
