### PR TITLE
executor: resolve errors caused by `in null` in point/batch .

### LINKED ISSUE #18839: IN(NULL) causes "cannot convert <nil>(type <nil>) to string"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t ( id bigint(10) primary key, f varchar(191) default null, unique key `idx_f` (`f`));
select * from t where f in (null);
```

### 2. What did you expect to see? (Required)
This query should return no results, but it should complete without any error.

### 3. What did you see instead (Required)

```
ERROR 1105 (HY000): cannot convert <nil>(type <nil>) to string
```

### 4. Affected version (Required)

All 4.0 releases are affected.

TiDB v3.0.16 is not affected.

### PR DESCRIPTION
**Pull request by qw4990**
cherry pick for https://github.com/pingcap/tidb/pull/18848 

---

### What problem does this PR solve?

Issue Number: close #18839 

Problem Summary: resolve errors caused by `in null` in point/batch get operators

### What is changed and how it works?
Skip null values when casting.

### Check List 

Tests 

- Unit test
### Release note 

- executor: resolve errors caused by `in null` in point/batch get operators

### CODE REVIEW

File: executor/point_get.go [hunk 1]
```diff
@@ -157,10 +157,14 @@ func (e *PointGetExecutor) Next(ctx context.Context, req *chunk.Chunk) error {
...
 	}
 	if e.idxInfo != nil {
-		e.idxKey, err = encodeIndexKey(e.base(), e.tblInfo, e.idxInfo, e.idxVals, tblID)
+		hasNull := false
+		e.idxKey, hasNull, err = encodeIndexKey(e.base(), e.tblInfo, e.idxInfo, e.idxVals, tblID)
 		if err != nil && !kv.ErrNotExist.Equal(err) {
 			return err
 		}
+		if hasNull {
+			return nil
```
Comment (tiancaiamao) [inline executor/point_get.go:166]: `x in (1,2,3,null)` return nil?

Comment (qw4990) [reply executor/point_get.go:166]: This case will use `BatchGet` instad of `PointGet`:
```
mysql> select * from t where f in (null, 2);
+----+------+
| id | f    |
+----+------+
|  2 | 2    |
+----+------+
1 row in set (0.00 sec)

mysql> explain select * from t where f in (null, 2);
+-------------------+---------+------+-------------------------+------------------------------+
| id                | estRows | task | access object           | operator info                |
+-------------------+---------+------+-------------------------+------------------------------+
| Batch_Point_Get_1 | 2.00    | root | table:t, index:idx_f(f) | keep order:false, desc:false |
+-------------------+---------+------+-------------------------+------------------------------+
1 row in set (0.00 sec)

mysql> select * from t;
+----+------+
| id | f    |
+----+------+
|  1 | NULL |
|  2 | 2    |
+----+------+
2 rows in set (0.00 sec)
```

**Comment by tiancaiamao** [comment]
LGTM

**Comment by imtbkcat** [comment]
/run-all-tests tidb-test=release-4.0 tikv=release-4.0 pd=release-4.0
