### PR TITLE
bindinfo, planner: restore binding match cache for plan cache

### LINKED ISSUE #65760: There is a 4.5% performance regression in sysbench after PR#65484
### 1. Minimal reproduce step (Required)

1. Deploy a cluster with 3 TiDB and 3 Tikv.
2. Run benchmark sysbench (select_random_ranges).

### 2. What did you expect to see? (Required)

No performance regression.

### 3. What did you see instead (Required)

QPS regression <no value> in benchmark sysbench (select_random_ranges) compared to baseline 66188.00 after #65484.

| description       | tidb                                                    | tikv                                                 | pd                                               | QPS avg                                            |
| ----------------- | ------------------------------------------------------- | ---------------------------------------------------- | ------------------------------------------------ | ----------------------------------------------------------------------------------------------- |
| last success      | pingcap/tidb@e87fd0b11005f17330a939d5fca6d8279bb94768     | tikv/tikv@76c8a2dc650ed7013419e8b192b40b58d70aab83     | tikv/pd@65213831e3e0602939d79cefad63c8fb4dae39bf     | 66221.23         |
| first regression  | pingcap/tidb@27a4771206dfbbdc5f40493edb8361cb5a80629b | tikv/tikv@76c8a2dc650ed7013419e8b192b40b58d70aab83 | tikv/pd@65213831e3e0602939d79cefad63c8fb4dae39bf | 63236.72 |

### 4. What is your TiDB version? (Required)

pingcap/tidb@27a4771206dfbbdc5f40493edb8361cb5a80629b

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #65760

### Problem Summary:
  Plan cache key generation regressed after removing per-PlanCacheStmt binding match cache, causing
  repeated NormalizeStmtForBinding/CollectTableNames per execution and slowing benchmarks like
  BenchmarkNonPartitionPointGetPlanCacheOn.

  ### What changed and how does it work?
  - Restore BindingMatchInfo on PlanCacheStmt and use it in MatchSQLBindingForPlanCache to reuse
  normalization results across executions.
  - Keep StmtCtx cache for same-stmt execution, without changing semantics.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Manual test steps:

```
go test -run ^$ -bench BenchmarkNonPartitionPointGetPlanCacheOn ./pkg/planner/core/...
go test -run ^$ -bench BenchmarkPlanCacheBindingMatch ./pkg/planner/core/...
```

before
```
BenchmarkNonPartitionPointGetPlanCacheOn-8   	   37118	     55860 ns/op
BenchmarkPlanCacheBindingMatch-8   	           36598	     41149 ns/op
```

after
```
BenchmarkNonPartitionPointGetPlanCacheOn-8   	   68763	     18730 ns/op
BenchmarkPlanCacheBindingMatch-8   	           29524	     33877 ns/op
```

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/bindinfo/binding.go [hunk 1]
```diff
@@ -134,8 +134,8 @@ type BindingMatchInfo struct {
 }
 
 // MatchSQLBindingForPlanCache matches binding for plan cache.
-func MatchSQLBindingForPlanCache(sctx sessionctx.Context, stmtNode ast.StmtNode) (bindingSQL string) {
-	binding, matched, _ := matchSQLBinding(sctx, stmtNode)
+func MatchSQLBindingForPlanCache(sctx sessionctx.Context, stmtNode ast.StmtNode, info *BindingMatchInfo) (bindingSQL string) {
```
Comment (qw4990) [inline pkg/bindinfo/binding.go]: Could we merge `matchSQLBindingForPlanCache` and `MatchSQLBindingForPlanCache` into a single function...

File: pkg/bindinfo/binding.go [hunk 2]
```diff
@@ -187,19 +187,56 @@ func matchSQLBinding(sctx sessionctx.Context, stmtNode ast.StmtNode) (binding *B
...
 }
 
-func matchSQLBindingInternal(sctx sessionctx.Context, sessionVars *variable.SessionVars, stmtNode ast.StmtNode) (binding *Binding, matched bool, scope string) {
-	_, noDBDigest := NormalizeStmtForBinding(stmtNode, "", true)
-	tableNames := CollectTableNames(stmtNode)
+func matchSQLBindingForPlanCache(sctx sessionctx.Context, stmtNode ast.StmtNode, info *BindingMatchInfo) (binding *Binding, matched bool, scope string) {
+	sessionVars := sctx.GetSessionVars()
+	defer func(begin time.Time) {
+		sessionVars.DurationOptimizer.BindingMatch = time.Since(begin)
+	}(time.Now())
```
Comment (qw4990) [inline pkg/bindinfo/binding.go]: Better to record this at the most internal function, which should be `matchSQLBindingInternal` here.

Comment (hawkingrei) [reply pkg/bindinfo/binding.go]: I have refactored the code.

File: pkg/bindinfo/binding.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/bindinfo/binding.go]: OK, I have merged.

**Review by qw4990 — APPROVED** [review]
