### PR TITLE
executor: skip ignore check for not update indexes

### LINKED ISSUE #23892: insert ignore on duplicate got wrong result when index value unchanged
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t6 (a int, b int, c int, primary key(a, b) clustered, unique key idx_14(b), unique key idx_15(b), unique key idx_16(a, b));
insert into t6 select 10, 10, 20;
insert ignore into t6 set a = 20, b = 10 on duplicate key update a = 100;
```

### 2. What did you expect to see? (Required)

on duplicate on `b=10` and update a to 100

### 3. What did you see instead (Required)

update nothing

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by lysu**
### What problem does this PR solve?

Issue Number: close #23892 

Problem Summary:

for `insert ignore on duplicate update` stmt, "ignore check" should only check the index that real change

only new row value meet duplicated in indexes need be ignore, and it can continue update if new value == old value, due to old row/indexes will be removed before upsert

### What is changed and how it works?

What's Changed, How it Works:

only ignore check for real changed indexes

### Related changes

- Need to cherry-pick to the release branch 5.0.x

### Check List 

Tests 

- Unit test

Side effects

- n/a

### Release note 

- No release note

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/tidb/23894)

### CODE REVIEW

File: table/tables/tables.go [hunk 1]
```diff
@@ -1450,11 +1450,11 @@ func FindIndexByColName(t table.Table, name string) table.Index {
 
 // CheckHandleOrUniqueKeyExistForUpdateIgnoreOrInsertOnDupIgnore check whether recordID key or unique index key exists. if not exists, return nil,
 // otherwise return kv.ErrKeyExists error.
-func CheckHandleOrUniqueKeyExistForUpdateIgnoreOrInsertOnDupIgnore(ctx context.Context, sctx sessionctx.Context, t table.Table, recordID kv.Handle, data []types.Datum) error {
+func CheckHandleOrUniqueKeyExistForUpdateIgnoreOrInsertOnDupIgnore(ctx context.Context, sctx sessionctx.Context, t table.Table, recordID kv.Handle, oldRow, newRow []types.Datum) error {
```
Comment (jackysp) [inline table/tables/tables.go:1453]: I think you could use `modified` in `updateRecord` to avoid compare once again.

File: table/tables/tables.go [hunk 2]
```diff
@@ -1481,18 +1481,27 @@ func CheckHandleOrUniqueKeyExistForUpdateIgnoreOrInsertOnDupIgnore(ctx context.C
...
-		for _, idx := range t.Indices() {
-			if !IsIndexWritable(idx) {
-				continue
+		canSkipIgnoreCheck := func(idx table.Index) bool {
+			if !IsIndexWritable(idx) || !idx.Meta().Unique || (t.Meta().IsCommonHandle && idx.Meta().Primary) {
+				return true
+			}
+			for _, c := range idx.Meta().Columns {
+				if modified[c.Offset] {
+					return true
```
Comment (cfzjywxk) [inline table/tables/tables.go:1490]: A bit confused, if this index related column value is changed, should we do the check?

Comment (lysu) [reply table/tables/tables.go]: 😵 my fault when extract method..fixed

File: table/tables/tables.go [hunk 3]
```diff
@@ -1481,18 +1481,27 @@ func CheckHandleOrUniqueKeyExistForUpdateIgnoreOrInsertOnDupIgnore(ctx context.C
 
 	// Check unique key exists.
 	{
-		for _, idx := range t.Indices() {
-			if !IsIndexWritable(idx) {
-				continue
+		canSkipIgnoreCheck := func(idx table.Index) bool {
+			if !IsIndexWritable(idx) || !idx.Meta().Unique || (t.Meta().IsCommonHandle && idx.Meta().Primary) {
```
Comment (cfzjywxk) [inline table/tables/tables.go:1485]: Should we skip `t.Meta().PKIsHandle && idx.Meta().Primary` too?

Comment (lysu) [reply table/tables/tables.go:1485]: i think we can skip that because 

https://github.com/pingcap/tidb/pull/23894/files#diff-ccb2771ef1931990c0d0ce3703def7dd53bd21d00a8f6b40b59ca0115f776a60R1469-R1480

had check handle, primary key should be same as handle if it's clustered index

Comment (lysu) [reply table/tables/tables.go:1485]: ... it seems, there are no indexInfo named Primary when table is PKIsHandle after debug

for example:

`create table t4(id int primary key clustered, k int, v int, unique key uk1(k))`

`t.indices` only contain `uk1`'s info

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
CI failed.

File: table/tables/tables.go [hunk 4]
```diff
@@ -1481,18 +1481,27 @@ func CheckHandleOrUniqueKeyExistForUpdateIgnoreOrInsertOnDupIgnore(ctx context.C
 
 	// Check unique key exists.
 	{
-		for _, idx := range t.Indices() {
-			if !IsIndexWritable(idx) {
-				continue
+		canSkipIgnoreCheck := func(idx table.Index) bool {
```
Comment (coocood) [inline table/tables/tables.go:1484]: `can` indicates optimization, if it is a bug fix, `should` is more propriate.

**Comment by lysu** [comment]
@coocood
