### PR TITLE
lightning: add PK to internal tables

### LINKED ISSUE #57479: lightning's internal table does not have PK so can't work with sql_require_primary_key=ON
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

turn on `sql_require_primary_key` and run lightning

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

lightning will create some internal tables, and failed with error `Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.` This is because these tables have no PK

### 4. What is your TiDB version? (Required)

all version

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #57479

Problem Summary:

### What changed and how does it work?

as title

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: lightning/tests/lightning_config_max_error/run.sh [hunk 1]
```diff
@@ -28,7 +28,7 @@ duplicated_row_count=$(( ${total_row_count} - ${uniq_row_count} ))
 remaining_row_count=$(( ${uniq_row_count} + ${duplicated_row_count}/2 ))
 
 run_sql 'DROP TABLE IF EXISTS mytest.testtbl'
-run_sql 'DROP TABLE IF EXISTS lightning_task_info.conflict_error_v3'
+run_sql 'DROP TABLE IF EXISTS lightning_task_info.conflict_error_v4'
```
Comment (Benjamin2037) [inline lightning/tests/lightning_config_max_error/run.sh:31]: Here we changed name of table，will this result we possible leave lightning_task_info.conflict_error_v3' table can not be drop forever

Comment (lance6716) [reply lightning/tests/lightning_config_max_error/run.sh:31]: Yes. This is integration test script to cleanup old data. But in real cases user may see old tables. Just as the old behaviour, lightning will not automatically drop them.

Comment (Benjamin2037) [reply lightning/tests/lightning_config_max_error/run.sh:31]: Can we also enable drop old version table and create new version one to avoid the old tables are still there.

**Review by D3Hunter — APPROVED** [review]

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by yudongusa — APPROVED** [review]
