### PR TITLE
executor, codec: hash join build wrong hash key for ENUM/SET value

### LINKED ISSUE #48991: Wrong hash key constructed for hash join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tidb-a: Nontransactional-Delete
tidb-b: normal-delete
execute same dml sql, and check with
 "select * from tbl_3 order by col_11,col_12,col_13,col_14,col_15"

### 2. What did you expect to see? (Required)
results are same in tidb-a and tidb-b clusters
### 3. What did you see instead (Required)
```
[2023/11/29 01:14:15.948 +00:00] [INFO] [listener.go:96] [summary] [PASSED=0] [FAILED=1] [SKIPPED=0]
Error: result digests mismatch: 68fa1daaf82245b3bd96b6bc7f598180908aa080 != 9b010d9c9ce8b2b9ee071fd9813dbad657b8de7a "select * from tbl_3 o
rder by col_11,col_12,col_13,col_14,col_15"
+----------+---------+----------+---------------------+---------------------+
|  COL 11  | COL 12  |  COL 13  |       COL 14        |       COL 15        |
+----------+---------+----------+---------------------+---------------------+
|  1407620 | Charlie | 12:08:52 | 1975-01-20 00:00:00 | #g                  |
|  1479390 | Alice   | 12:40:08 | 1984-06-09 00:00:00 | LeoVONgN~iJz&inj    |
|  2483729 | Charlie | 06:43:13 | 1970-09-09 00:00:00 | w6o6WFYyL5          |
|  2584327 | Charlie | 13:27:40 | 2034-07-17 00:00:00 |                     |
|  2621671 | Bob     | 12:48:52 | 2014-04-16 00:00:00 | vG                  |
|  3222667 | Alice   | 18:15:37 | 2023-11-19 00:00:00 |                     |
|  3694249 | Alice   | 19:27:53 | 2032-03-03 00:00:00 | 1=(Dbd6X~           |
|  4135401 | Charlie | 11:30:34 | 2017-06-06 00:00:00 | 2FZmy9lanL8         |
|  4692415 | Bob     | 16:55:35 | 1987-01-06 00:00:00 | 8q$7EWaQ54L^b$L     |
|  4696775 | Charlie | 21:07:43 | 1984-07-31 00:00:00 | SKOW9I^sM$4xNk      |
|  5332195 | Bob     | 16:53:00 | 2002-08-27 00:00:00 | 7~                  |
|  6484463 | David   | 01:31:54 | 1986-02-05 00:00:00 | V                   |
|  7109734 | Alice   | 13:32:10 | 2005-06-07 00:00:00 | axaj!6&v+^ndnvgMA   |
|  7439047 | Charlie | 08:40:15 | 2030-10-31 00:00:00 | )iWtLS=)W-K         |
|  7871477 | Charlie | 15:18:48 | 2027-05-29 00:00:00 | b=y^@zIex           |
|  8096311 | David   | 16:37:23 | 1981-11-06 00:00:00 | )@6Xs5              |
|  8714024 | Bob     | 10:52:16 | 1992-12-05 00:00:00 | x5uJJv0q            |
|  8745941 | David   | 00:02:17 | 1986-04-23 00:00:00 | K7v1                |
|  8838143 | David   | 15:41:27 | 1993-02-23 00:00:00 | g0q~Z0b*PpMPKJxYbIE |
|  8851748 | Alice   | 03:24:14 | 2018-06-20 00:00:00 | %                   |
|  8963236 | Alice   | 00:18:31 | 2022-04-17 00:00:00 | v4DsE               |
|  9024936 | Alice   | 02:14:39 | 2004-07-06 00:00:00 | u9=JcZH*nTH21       |
|  9048951 | Alice   | 21:19:47 | 2018-09-22 00:00:00 | sJ!vs               |
|  9082223 | Alice   | 17:25:16 | 2035-11-08 00:00:00 | i                   |
|  9665624 | Bob     | 03:42:54 | 2033-09-11 00:00:00 | 8&fu9G0j~7fTy3Ft    |
| 10427825 | Charlie | 07:27:35 | 1986-12-25 00:00:00 | tWJ                 |
| 11872083 | Alice   | 16:28:00 | 2007-11-08 00:00:00 | 0+EGQrQNs           |
| 12569440 | Charlie | 15:24:08 | 2004-05-12 00:00:00 | E!W0#*g45!          |
| 12794792 | Charlie | 20:10:08 | 2034-08-07 00:00:00 | hvpXVQyuP           |
| 13070243 | Alice   | 11:04:26 | 2027-10-26 00:00:00 | +6i+3avaw=ai        |
| 13943500 | Charlie | 12:07:38 | 2020-08-01 00:00:00 | yNistRS8V           |
| 13975230 | David   | 13:48:05 | 1971-09-08 00:00:00 | JCLW%Qky(d$uieux8^X |
| 14204170 | David   | 18:10:06 | 2010-12-13 00:00:00 | 0%u                 |
| 14509869 | Alice   | 09:19:53 | 2011-10-20 00:00:00 | S4Kk!i)1RPz@*aE     |
| 15124716 | Charlie | 02:27:48 | 2013-01-24 00:00:00 |                     |
| 15372932 | Charlie | 03:35:25 | 1985-11-25 00:00:00 | Ss~Wu2ePvfpmJ=f     |
| 15528343 | Charlie | 03:55:08 | 1978-07-25 00:00:00 | t=7eD6uwhzFRJCR     |
| 16294639 | Alice   | 05:08:43 | 2006-09-23 00:00:00 | 3ss                 |
+----------+---------+----------+---------------------+---------------------+

+----------+---------+----------+---------------------+---------------------+
|  COL 11  | COL 12  |  COL 13  |       COL 14        |       COL 15        |
+----------+---------+----------+---------------------+---------------------+
|  1407620 | Charlie | 12:08:52 | 1975-01-20 00:00:00 | #g                  |
|  2483729 | Charlie | 06:43:13 | 1970-09-09 00:00:00 | w6o6WFYyL5          |
|  2584327 | Charlie | 13:27:40 | 2034-07-17 00:00:00 |                     |
|  2621671 | Bob     | 12:48:52 | 2014-04-16 00:00:00 | vG                  |
|  3222667 | Alice   | 18:15:37 | 2023-11-19 00:00:00 |                     |
|  3694249 | Alice   | 19:27:53 | 2032-03-03 00:00:00 | 1=(Dbd6X~           |
|  4692415 | Bob     | 16:55:35 | 1987-01-06 00:00:00 | 8q$7EWaQ54L^b$L     |
|  5332195 | Bob     | 16:53:00 | 2002-08-27 00:00:00 | 7~                  |
|  6484463 | David   | 01:31:54 | 1986-02-05 00:00:00 | V                   |
|  7109734 | Alice   | 13:32:10 | 2005-06-07 00:00:00 | axaj!6&v+^ndnvgMA   |
|  7439047 | Charlie | 08:40:15 | 2030-10-31 00:00:00 | )iWtLS=)W-K         |
|  7871477 | Charlie | 15:18:48 | 2027-05-29 00:00:00 | b=y^@zIex           |
|  8096311 | David   | 16:37:23 | 1981-11-06 00:00:00 | )@6Xs5              |
|  8714024 | Bob     | 10:52:16 | 1992-12-05 00:00:00 | x5uJJv0q            |
|  8745941 | David   | 00:02:17 | 1986-04-23 00:00:00 | K7v1                |
|  8838143 | David   | 15:41:27 | 1993-02-23 00:00:00 | g0q~Z0b*PpMPKJxYbIE |
|  8851748 | Alice   | 03:24:14 | 2018-06-20 00:00:00 | %                   |
|  8963236 | Alice   | 00:18:31 | 2022-04-17 00:00:00 | v4DsE               |
|  9024936 | Alice   | 02:14:39 | 2004-07-06 00:00:00 | u9=JcZH*nTH21       |
|  9048951 | Alice   | 21:19:47 | 2018-09-22 00:00:00 | sJ!vs               |
|  9082223 | Alice   | 17:25:16 | 2035-11-08 00:00:00 | i                   |
|  9665624 | Bob     | 03:42:54 | 2033-09-11 00:00:00 | 8&fu9G0j~7fTy3Ft    |
| 10427825 | Charlie | 07:27:35 | 1986-12-25 00:00:00 | tWJ                 |
| 11872083 | Alice   | 16:28:00 | 2007-11-08 00:00:00 | 0+EGQrQNs           |
| 12569440 | Charlie | 15:24:08 | 2004-05-12 00:00:00 | E!W0#*g45!          |
| 12794792 | Charlie | 20:10:08 | 2034-08-07 00:00:00 | hvpXVQyuP           |
| 13070243 | Alice   | 11:04:26 | 2027-10-26 00:00:00 | +6i+3avaw=ai        |
| 13943500 | Charlie | 12:07:38 | 2020-08-01 00:00:00 | yNistRS8V           |
| 13975230 | David   | 13:48:05 | 1971-09-08 00:00:00 | JCLW%Qky(d$uieux8^X |
| 14204170 | David   | 18:10:06 | 2010-12-13 00:00:00 | 0%u                 |
| 14509869 | Alice   | 09:19:53 | 2011-10-20 00:00:00 | S4Kk!i)1RPz@*aE     |
| 15124716 | Charlie | 02:27:48 | 2013-01-24 00:00:00 |                     |
| 15372932 | Charlie | 03:35:25 | 1985-11-25 00:00:00 | Ss~Wu2ePvfpmJ=f     |
| 15528343 | Charlie | 03:55:08 | 1978-07-25 00:00:00 | t=7eD6uwhzFRJCR     |
| 16294639 | Alice   | 05:08:43 | 2006-09-23 00:00:00 | 3ss                 |
+----------+---------+----------+---------------------+---------------------+
### 4. What is your TiDB version? (Required)

["Git Commit Hash"=877198dde22010e428be26aa0d7bdc5aab75d629]

v6.5.6 and master

### PR DESCRIPTION
**Pull request by winoros**
### What problem does this PR solve?

Issue Number: close #48991 

Problem Summary:

### What changed and how does it work?

When the projection disables the ColumnEvaluator, it will eval the ENUM and parse a new ENUM. But the new ENUM value's value index will be set to 0.

But when we construct the hash value for the join key, we use the value index to seek the string value. So a wrong hash key is constructed.

This pull aims to solve the case.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix the issue that hash join will construct wrong join key for ENUM type
```

### CODE REVIEW

File: pkg/util/codec/codec.go [hunk 1]
```diff
@@ -360,11 +360,14 @@ func encodeHashChunkRowIdx(typeCtx types.Context, row chunk.Row, tp *types.Field
...
 		} else {
 			flag = compactBytesFlag
-			v := row.GetEnum(idx).Value
-			str := ""
-			if enum, err := types.ParseEnumValue(tp.GetElems(), v); err == nil {
-				// str will be empty string if v out of definition of enum.
-				str = enum.Name
+			enumVal := row.GetEnum(idx)
+			str := enumVal.Name
+			if str == "" {
```
Comment (XuHuaiyu) [inline pkg/util/codec/codec.go:365]: when will `str` be an empty string

**Review by XuHuaiyu — APPROVED** [review]

**Review by guo-shaoge — APPROVED** [review]
