### PR TITLE
ddl: find old column by name for old version modify column job

### LINKED ISSUE #63895: Modify column unexpectedly rollback during upgrade
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run modify column DDL job during upgrade.

### 2. What did you expect to see? (Required)

The ddl job should succeed.

### 3. What did you see instead (Required)

```
mysql> admin show ddl jobs 100 where job_id = 259;
+--------+---------+------------+---------------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+---------------+----------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE      | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME                | START_TIME                 | END_TIME                   | STATE         | COMMENTS |
+--------+---------+------------+---------------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+---------------+----------+
|    259 | sbtest1 | sbtest1    | modify column | none         |       244 |      242 |   4776512 | 2025-10-10 11:25:14.481000 | 2025-10-10 11:27:46.722000 | 2025-10-10 11:30:14.621000 | rollback done |          |
+--------+---------+------------+---------------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+---------------+----------+
1 row in set (0.09 sec)
```

```
[2025/10/10 11:29:50.353 +08:00] [INFO] [job_worker.go:831] ["run DDL job"] [category=ddl] [jobID=259] [conn=782237702] [job="ID:259, Type:modify column, State:queueing, SchemaState:write reorganization, SchemaID:244, TableID:242, RowCount:4240296, ArgLen:0, start time: 2025-10-10 11:25:14.481 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:461390968775245827, Version: v1, UniqueWarnings:0"]
[2025/10/10 11:29:50.354 +08:00] [INFO] [modify_column.go:231] ["run modify column job, init old column id"] [category=ddl] [oldColumnName=c] [oldColumnID=3]
...
[2025/10/10 11:30:04.039 +08:00] [INFO] [backfilling.go:443] ["backfill worker exit"] [category=ddl] [worker="backfill-worker 1, tp update column"] [jobID=259]
[2025/10/10 11:30:05.410 +08:00] [INFO] [job_worker.go:831] ["run DDL job"] [category=ddl] [jobID=259] [conn=782237702] [job="ID:259, Type:modify column, State:running, SchemaState:write reorganization, SchemaID:244, TableID:242, RowCount:4427763, ArgLen:0, start time: 2025-10-10 11:25:14.481 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:461390968775245827, Version: v1, UniqueWarnings:0"]
[2025/10/10 11:30:05.411 +08:00] [INFO] [modify_column.go:231] ["run modify column job, init old column id"] [category=ddl] [oldColumnName=c] [oldColumnID=3]
...
[2025/10/10 11:30:10.428 +08:00] [INFO] [job_worker.go:831] ["run DDL job"] [category=ddl] [jobID=259] [conn=782237702] [job="ID:259, Type:modify column, State:running, SchemaState:write reorganization, SchemaID:244, TableID:242, RowCount:4691945, ArgLen:0, start time: 2025-10-10 11:25:14.481 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:461390968775245827, Version: v1, UniqueWarnings:0"]
[2025/10/10 11:30:10.429 +08:00] [INFO] [modify_column.go:231] ["run modify column job, init old column id"] [category=ddl] [oldColumnName=c] [oldColumnID=3]
...
[2025/10/10 11:30:14.602 +08:00] [INFO] [reorg.go:416] ["run reorg job done"] [category=ddl] ["handled rows"=4776512]
[2025/10/10 11:30:14.621 +08:00] [INFO] [domain.go:350] ["diff load InfoSchema success"] [isV2=false] [currentSchemaVersion=313] [neededSchemaVersion=314] ["elapsed time"=1.166098ms] [gotSchemaVersion=314] [phyTblIDs="[242]"] [actionTypes="[12]"] [diffTypes="[\"modify column\"]"]
[2025/10/10 11:30:14.626 +08:00] [INFO] [domain.go:1092] ["mdl gets lock, update self version to owner"] [jobID=259] [version=314]
[2025/10/10 11:30:14.629 +08:00] [INFO] [schema_version.go:392] ["wait latest schema version changed(get the metadata lock if tidb_enable_metadata_lock is true)"] [category=ddl] [ver=314] ["take time"=10.954681ms] [job="ID:259, Type:modify column, State:running, SchemaState:public, SchemaID:244, TableID:242, RowCount:4776512, ArgLen:8, start time: 2025-10-10 11:25:14.481 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:461390968775245827, Version: v1, UniqueWarnings:0"]
[2025/10/10 11:30:14.635 +08:00] [INFO] [job_worker.go:831] ["run DDL job"] [category=ddl] [jobID=259] [conn=782237702] [job="ID:259, Type:modify column, State:running, SchemaState:public, SchemaID:244, TableID:242, RowCount:4776512, ArgLen:0, start time: 2025-10-10 11:25:14.481 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:461390968775245827, Version: v1, UniqueWarnings:0"]
[2025/10/10 11:30:14.637 +08:00] [INFO] [modify_column.go:231] ["run modify column job, init old column id"] [category=ddl] [oldColumnName=c] [oldColumnID=5]
[2025/10/10 11:30:14.637 +08:00] [WARN] [job_worker.go:767] ["run DDL job error"] [category=ddl] [jobID=259] [conn=782237702] [error="[ddl:8245]column c id 3 does not exist, this column may have been updated by other DDL ran in parallel"]
```

### 4. What is your TiDB version? (Required)

Upgrade from lower version to 8.5.4

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #63895

Problem Summary:

Once the job arg is initialized at old version TiDB, appending new arg in new version TiDB doesn't work.

https://github.com/pingcap/tidb/blob/1e571855e1be7f37b861eea60ddaed5f67b671de/pkg/ddl/modify_column.go#L238-L243

Line 239 cannot persist to the storage because `args.OldColumnID` doesn't bind to `job.args` in `(a *ModifyColumnArgs) decodeV1`:

https://github.com/pingcap/tidb/blob/1e571855e1be7f37b861eea60ddaed5f67b671de/pkg/meta/model/job_args.go#L1758-L1763

`&a.OldColumnID` is ignored, as `job.RawArgs` has fewer elements:

https://github.com/pingcap/tidb/blob/1e571855e1be7f37b861eea60ddaed5f67b671de/pkg/meta/model/job.go#L580

### What changed and how does it work?

Find old column by name for old version DDL job. Consider the removing name first to locate the old column.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/executor.go [hunk 1]
```diff
@@ -6962,14 +6962,10 @@ func (e *executor) RefreshMeta(sctx sessionctx.Context, args *model.RefreshMetaA
 }
 
 func getScatterScopeFromSessionctx(sctx sessionctx.Context) string {
-	var scatterScope string
-	val, ok := sctx.GetSessionVars().GetSystemVar(vardef.TiDBScatterRegion)
-	if !ok {
-		logutil.DDLLogger().Info("won't scatter region since system variable didn't set")
```
Comment (D3Hunter) [inline pkg/ddl/executor.go:6968]: keep this log?

File: pkg/ddl/modify_column.go [hunk 2]
```diff
@@ -234,12 +234,19 @@ func getModifyColumnInfo(
...
-		oldCol = model.FindColumnInfo(tblInfo.Columns, args.OldColumnName.L)
+		// Lower version TiDB doesn't persist the old column ID to job arguments.
+		// We have to use the old column name to locate the old column.
+		oldCol = model.FindColumnInfo(tblInfo.Columns, getRemovingObjName(args.OldColumnName.L))
+		if oldCol == nil {
+			// The old column maybe not in removing state.
+			oldCol = model.FindColumnInfo(tblInfo.Columns, args.OldColumnName.L)
+		}
 		if oldCol != nil {
-			args.OldColumnID = oldCol.ID
```
Comment (D3Hunter) [inline pkg/ddl/modify_column.go:239]: maybe keep this one, if the job is submitted by old version tidb, if new version tidb run it from start, then later we can persist and use OldColumnID directly in later steps

File: pkg/ddl/executor.go (hunk 1 above)
Comment (tangenta) [reply pkg/ddl/executor.go:6968]: ~It will pollute the log because in most case the system table map in memory don't have this entry.~
