### PR TITLE
session: fix data race between stats loop update and bind info loop load

### LINKED ISSUE #15843: data race for bind handle in session bootstrap
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

I filed a PR and CI failed, because data race is detected.

### 2. What did you expect to see?

All tests should pass.

### 3. What did you see instead?

Data race reported as:
```
[2020-03-30T07:48:41.682Z] WARNING: DATA RACE

[2020-03-30T07:48:41.682Z] Write at 0x00c0095c0140 by goroutine 161:

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/domain.(*Domain).LoadBindInfoLoop()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:874 +0xe1

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.BootstrapSession()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1722 +0x4cf

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1029 +0x3d9

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1027 +0x3ac

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1025 +0x37f

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1023 +0x352

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1021 +0x325

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1019 +0x2f8

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1017 +0x2cb

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.682Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1015 +0x29e

[2020-03-30T07:48:41.682Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1013 +0x271

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1011 +0x244

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1009 +0x217

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1007 +0x1ea

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1005 +0x1bd

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1004 +0x190

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1003 +0x163

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1002 +0x136

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:1000 +0x109

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:998 +0xdc

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.doDDLWorks()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:996 +0x5b

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.bootstrap()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/bootstrap.go:306 +0x1a1

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.runInBootstrapSession()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1753 +0xe2

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.BootstrapSession()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1653 +0xb3f

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/server.(*HTTPHandlerTestSuite).startServer()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/server/http_handler_test.go:346 +0x1d5

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/server.(*HTTPHandlerTestSuite).TestGetTableMVCC()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/server/http_handler_test.go:431 +0x60

[2020-03-30T07:48:41.683Z]   runtime.call32()

[2020-03-30T07:48:41.683Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2020-03-30T07:48:41.683Z]   reflect.Value.Call()

[2020-03-30T07:48:41.683Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2020-03-30T07:48:41.683Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa

[2020-03-30T07:48:41.683Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113

[2020-03-30T07:48:41.683Z] 

[2020-03-30T07:48:41.683Z] Previous read at 0x00c0095c0140 by goroutine 12:

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/planner.getBindRecord()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:866 +0x298

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/planner.Optimize()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/optimize.go:73 +0x41d

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/executor.(*Compiler).Compile()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/compiler.go:61 +0x298

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.(*session).execute()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1133 +0x887

[2020-03-30T07:48:41.683Z]   github.com/pingcap/tidb/session.(*session).Execute()

[2020-03-30T07:48:41.683Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1084 +0xee

[2020-03-30T07:48:41.684Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).initStatsMeta()

[2020-03-30T07:48:41.684Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/bootstrap.go:63 +0x101

[2020-03-30T07:48:41.684Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).InitStats()

[2020-03-30T07:48:41.684Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/bootstrap.go:313 +0x19f

[2020-03-30T07:48:41.684Z]   github.com/pingcap/tidb/domain.(*Domain).loadStatsWorker()

[2020-03-30T07:48:41.684Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:1016 +0x20a
```

In `BootstrapSession`, `UpdateTableStatsLoop` is called before `LoadBindInfoLoop`.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
acad2feb519414331fc4229b62ac4c4e563d0bd4
```

### PR DESCRIPTION
**Pull request by lzmhhh123**
### What problem does this PR solve?

Issue Number: close #15843 

Problem Summary: The stats loop update thread has the SQL which will access the `global.bindhandle`, but the start of bind info loop load thread inits the `global.bindhandle`. That causes the data race.

### What is changed and how it works?

What's Changed: move the `LoadBindInfoLoop` before the `UpdateTableStatsLoop`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### CODE REVIEW

**Comment by lzmhhh123** [comment]
> should we init `dom.bindHandle` in the very beginning, before any other background session started?

It's enough to move it before all threads which execute SQL roundly.

File: session/session.go [hunk 1]
```diff
@@ -1679,6 +1679,19 @@ func BootstrapSession(store kv.Storage) (*domain.Domain, error) {
...
 
+	se2, err := createSession(store)
+	if err != nil {
+		return nil, err
+	}
+	se3, err := createSession(store)
+	if err != nil {
+		return nil, err
+	}
+	err = dom.LoadBindInfoLoop(se2, se3)
```
Comment (zz-jason) [inline session/session.go]: please add a comment here: why we should call this function before others.
