### PR TITLE
ddl: reimplement get flashback cluster related key ranges

### LINKED ISSUE #40318: flashback does not properly handle dropped tables
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
create table t(a int);
select now();
insert into t values (1);
drop table t;
flashback cluster to timestamp 'xxx'; // flashback to timestamp before insert
select * from t;
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t;
Empty set (0.01 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t;
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

6ae151a9bc2dd2b4e7f7091a89d881c57cdebbc4

### LINKED ISSUE #40477: flashback to transaction begin fail for "Duplicate entry '30004' for key 'GLOBAL_VARIABLES.PRIMARY'"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

'CREATE TABLE t (a INT);'
'alter table t set tiflash replica 1'
'do sleep(10)'
'insert into t values(1),(1),(2);'
-----flashback target timestamp
'begin;'
'do sleep(4)'
'update t set a=111 where a=1;'
'commit;'
flashback cluster to timestamp '2023-01-10 21:41:13' --before "begin"
'do sleep(3)'
flashback cluster to timestamp '2023-01-10 21:41:13'

### 2. What did you expect to see? (Required)
flashback success

### 3. What did you see instead (Required)
(IntegrityError(1062, "Duplicate entry '30004' for key 'GLOBAL_VARIABLES.PRIMARY'")

### 4. What is your TiDB version? (Required)
[tidb@101 ~]$ /home/tidb/deploy/tidb-4000/bin/tidb-server -V
Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: 7e64d04f734667e20125ec7885495cb228987ad0
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2023-01-05 14:32:46
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
[tidb@101 ~]$

### PR DESCRIPTION
**Pull request by Defined2014**
### What problem does this PR solve?

Issue Number: close #40318, close #40477

Problem Summary: After this PR, we will flashback all non-system table ranges, whether the table actually exists or not.
And also flashback schema ranges.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: tablecodec/tablecodec.go [hunk 1]
```diff
@@ -209,6 +209,15 @@ func EncodeMetaKey(key []byte, field []byte) kv.Key {
 	return ek
 }
 
+// EncodeMetaKeyPrefix encodes the key prefix into meta key
+func EncodeMetaKeyPrefix(key []byte) kv.Key {
```
Comment (xhebox) [inline tablecodec/tablecodec.go:213]: I think you could just use `EncodeMetaKey(key, nil)`?

**Review by xhebox — APPROVED** [review]

File: tablecodec/tablecodec.go (hunk 1 above)
Comment (Defined2014) [reply tablecodec/tablecodec.go:213]: In `EncodeBytes`, `nil` will be transfer to `[0, 0, 0, 0, 0, 0, 0, 0, 247]`

**Review by bb7133 — APPROVED** [review]
LGTM
