### PR TITLE
executor: Fix IndexMergeReader works incorrectly under RC isolation level

### LINKED ISSUE #21151: buildIndexMergeReader doesn't refresh for update ts in RC isolation level
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (id int primary key, value int, a int not null, b int not null,
    index ia (a),  index ib (b));

insert into t values (1, 10, 2, 0), (2, 10, 4, 4), (3, 10, 0, 2), (4, 10, 0, 0);
```
```
MySQL [test]> select * from t;
+----+-------+---+---+
| id | value | a | b |
+----+-------+---+---+
|  1 |    10 | 2 | 0 |
|  2 |    10 | 4 | 4 |
|  3 |    10 | 0 | 2 |
|  4 |    10 | 0 | 0 |
+----+-------+---+---+
```

| session 1 | session 2 | comment |
|-----------|-----------|---------|
|`set transaction isolation level read committed; begin;`| | |
|`select /*+ NO_INDEX_MERGE() */ * from t where a > 3 or b > 3;`| | Returns `(2, 10, 4, 4)` |
|`select /*+ USE_INDEX_MERGE(t, ia, ib) */ * from t where a > 3 or b > 3;`| | Returns `(2, 10, 4, 4)` |
| | `update t set value = 11 where id = 2;` | |
|`select /*+ NO_INDEX_MERGE() */ * from t where a > 3 or b > 3;`| | Returns `(2, 11, 4, 4)` |
|`select /*+ USE_INDEX_MERGE(t, ia, ib) */ * from t where a > 3 or b > 3;`| | Returns `(2, 10, 4, 4)`，latest write become invisible |

### 2. What did you expect to see? (Required)

The last statement above in session 1 should returns `(2, 11, 4, 4)`, because `value = 11` is set by session 2 and session 1 is in a RC transaction.

### 3. What did you see instead (Required)

The last write in session 2 is invisible to the last statement in session 1.

### 4. What is your TiDB version? (Required)

master (f9f44d0a492a85a9200d9ae476eedfd505db5d7e)

**Note**:

This is caused by not invoking `refreshForUpdateTSForRC` when building IndexMergeReader. It must be invoked when building executors that can access data without nesting other executor.
We'd better have some mechanism to avoid forgetting invoking it.

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

Issue Number: close #21151

Problem Summary: When IndexMerge is used in a RC transaction, it may not see the latest committed write, because it forgot 
to refresh forUpdateTS..

### What is changed and how it works?

What's Changed:

The `refreshForUpdateTSForRC` invoking is moved to `getSnapshotTS` function. ~A parameter `forTxnRead` is added to `getSnapshotTS`, and when it's false it doesn't need to refresh it. So for `ChecksumTable` the ts refreshing can be skipped.~ This is a try to avoid forgetting refreshing for update ts for new reader executors in the future.

### Related changes

- Need to cherry-pick to the release branch
  - Release 4.0

### Check List 

Tests 

- Unit test

### Release note 

- Fix the issue that when Index Merge is used in a transaction with RC isolation level, the result may be incorrect.

### CODE REVIEW

**Comment by MyonKeminta** [comment]
I'd like to double check the correctness of these changes. Please continue reviewing it but don't merge it too quickly.

File: executor/builder.go [hunk 1]
```diff
@@ -73,11 +73,12 @@ var (
...
 type executorBuilder struct {
-	ctx        sessionctx.Context
-	is         infoschema.InfoSchema
-	snapshotTS uint64 // The consistent snapshot timestamp for the executor to read data.
-	err        error  // err is set when there is error happened during Executor building process.
-	hasLock    bool
+	ctx              sessionctx.Context
+	is               infoschema.InfoSchema
+	snapshotTS       uint64 // The consistent snapshot timestamp for the executor to read data.
+	snapshotTSCached bool
```
Comment (jackysp) [inline executor/builder.go:79]: Still need it?

Comment (MyonKeminta) [reply executor/builder.go:79]: Yes. The reason why it's needed is in `getSnapshotTS`.

Comment (jackysp) [reply executor/builder.go:79]: I think it won't happen.

Comment (MyonKeminta) [reply executor/builder.go:79]: I'm not sure. I think  it's better to keep the additional check before we are sure that this case never happens.

Comment (jackysp) [reply executor/builder.go:79]: What do you think @lzmhhh123 ?

**Comment by cfzjywxk** [comment]
LGTM

File: executor/builder.go (hunk 1 above)
Comment (lzmhhh123) [reply executor/builder.go:79]: I think we still need this. For some SQLs with a limit statement, although it will be interrupted when required rows are satified. The operator will be canceled step by step(some internal goroutines). It may still under execution. Then the new operators will call `Open` function by `index join`.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: executor/builder.go (hunk 1 above)
Comment (MyonKeminta) [reply executor/builder.go:79]: Is this case covered by any test?

Comment (MyonKeminta) [reply executor/builder.go:79]: And by the way, does IndexLookupJoin has the same problem? I found that it didn't force cache the snapshotTS
