### PR TITLE
tables: disable row insertion consistency check in mutation checker; and fix the cache problem

### LINKED ISSUE #35103: Mutation checker can use up to 30% of CPU time when executing `insert into select`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`insert into t_1 select * from t_2` where t_2 is a huge table.

### 2. What did you expect to see? (Required)

The mutation checker doesn't have a large impact on performance.

### 3. What did you see instead (Required)

The mutation checker uses 30% of the CPU time.

image

### PR DESCRIPTION
**Pull request by ekexium**
### What problem does this PR solve?

Issue Number: close #35103

Problem Summary:

### What is changed and how it works?

- RowInsertionConsistency contributes the least to defending data-index consistency, and consumes the most CPU time. So I would like to disable it.
- Fix the bug that column maps are not cached and thus built from scratch every time.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

In the execution of a single `insert into t_1 select * from t_2`, it uses up to 8.8% of the total CPU

image

image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: store/driver/txn/txn_driver.go [hunk 1]
```diff
@@ -42,6 +42,7 @@ type tikvTxn struct {
 	*tikv.KVTxn
 	idxNameCache        map[int64]*model.TableInfo
 	snapshotInterceptor kv.SnapshotInterceptor
+	columnMapsCache     interface{}
```
Comment (XuHuaiyu) [inline store/driver/txn/txn_driver.go:45]: Do we need a comment for this

File: table/tables/mutation_checker.go [hunk 2]
```diff
@@ -90,14 +90,6 @@ func CheckDataConsistency(
 
 	columnMaps := getColumnMaps(txn, t)
 
-	if rowToInsert != nil {
```
Comment (cfzjywxk) [inline table/tables/mutation_checker.go:93]: Seems this is not "disable" but  "remove". Maybe we could change this part to comments first and enable it after refactoring?

**Review by cfzjywxk — APPROVED** [review]
