### PR TITLE
executor, expression: Fixed the warning messages when calling date_add function failed

### LINKED ISSUE #19853: another DATETIME's behaviour is different from mysql
## Bug Report

Please answer these questions before submitting your issue. Thanks!

similar to #11329 

### 1. Minimal reproduce step (Required)
```sql
select date_add('2001-01-00', interval -2 hour);
```

### 2. What did you expect to see? (Required)

in MySQL 8.0: 
```sql
mysql root@127.0.0.1:app> select date_add('2001-01-00', interval -2 hour);
+------------------------------------------+
| date_add('2001-01-00', interval -2 hour) |
+------------------------------------------+
| <null>                                   |
+------------------------------------------+
1 row in set
Time: 0.021s
mysql root@127.0.0.1:app> show warnings;
+---------+------+----------------------------------------+
| Level   | Code | Message                                |
+---------+------+----------------------------------------+
| Warning | 1292 | Incorrect datetime value: '2001-01-00' |
+---------+------+----------------------------------------+
```

### 3. What did you see instead (Required)

in TiDB 
```sql
mysql root@127.0.0.1:(none)> select date_add('2001-00-01', interval -2 hour);
+------------------------------------------+
| date_add('2001-00-01', interval -2 hour) |
+------------------------------------------+
| 2000-11-30 22:00:00                      |
+------------------------------------------+
```

### 4. What is your TiDB version? (Required)

```sql
mysql root@127.0.0.1:(none)> select tidb_version() \G;
***************************[ 1. row ]***************************
tidb_version() | Release Version: v4.0.0-beta.2-1165-g726341146-dirty
Edition: Community
Git Commit Hash: 726341146b99485335a195b16a803b95e4875228
Git Branch: master
UTC Build Time: 2020-09-08 01:55:13
GoVersion: go1.14.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

1 row in set
Time: 0.009s
```

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @lzmhhh123

### PR DESCRIPTION
**Pull request by xiaodong-ji**
### What problem does this PR solve?

Issue Number: close #19853

Problem Summary: Inconsistent output of message when calling date_add function failed.

### What is changed and how it works?

What's Changed: The judgment of NoZeroDate has been added.

### Check List

Tests

- Unit test

### Release note

- Fixed the warning messages when calling date_add function failed

### CODE REVIEW

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

File: expression/builtin_time.go [hunk 1]
```diff
@@ -3434,6 +3434,14 @@ func (b *builtinAddDateStringIntSig) evalTime(row chunk.Row) (types.Time, bool,
 		return types.ZeroTime, true, err
 	}
 
+	dateStr, isNull, err := b.args[0].EvalString(b.ctx, row)
```
Comment (SunRunAway) [inline expression/builtin_time.go:3437]: Should this logic be in `b.getDateFromString`? 

Maybe we should fix them in all these signatures `builtin{Add|Sub}DateString{String|Int|Real|decimal}Sig`

Comment (SunRunAway) [reply expression/builtin_time.go:3437]: And we should also consider the vectorized version in `b.vecEvalTime` and better to add some comparison tests in https://github.com/pingcap/tidb/blob/baf6c99b956503b3122d8db463d7016c7b178fef/expression/builtin_time_vec_test.go#L243-L244

**Comment by xiaodong-ji** [comment]
PTAL @SunRunAway

File: expression/builtin_time.go [hunk 2]
```diff
@@ -2721,6 +2721,10 @@ func (du *baseDateArithmitical) getDateFromString(ctx sessionctx.Context, args [
 
 	sc := ctx.GetSessionVars().StmtCtx
 	date, err := types.ParseTime(sc, dateStr, dateTp, types.MaxFsp)
+
```
Comment (SunRunAway) [inline expression/builtin_time.go:2724]: Should the err be considered  `err != nil` first?

File: expression/builtin_time_vec_test.go [hunk 3]
```diff
@@ -240,8 +240,150 @@ var vecBuiltinTimeCases = map[string][]vecExprBenchCase{
...
 		},
 	},
-	ast.SubDate: {},
-	ast.AddDate: {},
+	ast.SubDate: {
+		{
+			retEvalType:   types.ETDatetime,
+			childrenTypes: []types.EvalType{types.ETString, types.ETString, types.ETString},
+			geners: []dataGenerator{
+				&dateStrGener{NullRation: 0.2, randGen: newDefaultRandGen()},
```
Comment (SunRunAway) [inline expression/builtin_time_vec_test.go:248]: Maybe `dateStrGener` should generate some zero date to cover the case of this issue.

File: expression/builtin_time.go (hunk 2 above)
Comment (xiaodong-ji) [reply expression/builtin_time.go]: done

File: expression/builtin_time_vec_test.go (hunk 3 above)
Comment (xiaodong-ji) [reply expression/builtin_time_vec_test.go:248]: done

**Comment by xiaodong-ji** [comment]
PTAL @SunRunAway

**Comment by lzmhhh123** [comment]
@xiaodong-ji Please fix the CI.

**Comment by xiaodong-ji** [comment]
> @xiaodong-ji Please fix the CI.

I'm trying to fix it.

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by xiaodong-ji** [comment]
PTAL @SunRunAway  @lzmhhh123

**Review by lzmhhh123 — APPROVED** [review]
