### PR TITLE
auto_inc,constraint: Ignore check constraint for auto-increment check

### LINKED ISSUE #38894: CREATE TABLE failed: ERROR 1105 (HY000): runtime error: index out if range [0] with length 0
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
a. use mysql connect tidb
b. execute sql: use test;
CREATE TABLE item_map (
id VARCHAR(128) NOT NULL,
created_at DATETIME(6),
updated_at DATETIME(6),
deleted_at DATETIME(6),
deleted BOOL,
item_id INTEGER NOT NULL AUTO_INCREMENT,
provider VARCHAR(255),
attribute VARCHAR(255),
PRIMARY KEY (id, item_id),
CHECK (deleted IN (0, 1)),
KEY idx_autoinc_item_id (item_id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
### 2. What did you expect to see? (Required)
Query OK
### 3. What did you see instead (Required)
ERROR 1105 (HY000): runtime error: index out if range [0] with length 0
### 4. What is your TiDB version? (Required)
| Release Version: v6.1.1
Edition: Community
Git Commit Hash: 5263a0abda61f102122735049fd0dfabc7b7f8b2
Git Branch: heads/refs/tags/v6.1.1
UTC Build Time: 2022-08-25 10:42:41
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Issue Number: close #38894 

Problem Summary:

While checking the auto-increment column is a key and iterating through the constraints, the check constraint doesn't have any key and return an error.

### What is changed and how it works?

If the constraint is a `check`, just ignore it in this function. 

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that the auto increment column cannot be used with check constraint.
```

### CODE REVIEW

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -675,6 +675,10 @@ func checkAutoIncrementOp(colDef *ast.ColumnDef, index int) (bool, error) {
 
 func isConstraintKeyTp(constraints []*ast.Constraint, colDef *ast.ColumnDef) bool {
```
Comment (xhebox) [inline planner/core/preprocess.go:676]: BTW, can we change the name of this function? I am worrying that somebody will use this function for non-auto-incr columns.

**Review by xhebox — APPROVED** [review]

File: planner/core/preprocess.go (hunk 1 above)
Comment (YangKeao) [reply planner/core/preprocess.go:676]: It returns whether the column is a constraint key.

I think it's fine to use it for other purpose, at least the change in this PR doesn't break it, because the `CHECK` constraint cannot be regarded as a key (and is not supported by TiDB, as described in the document) :thinking: .

File: planner/core/integration_test.go [hunk 2]
```diff
@@ -7823,3 +7823,14 @@ func TestNullConditionForPrefixIndex(t *testing.T) {
...
 }
+
+func TestAutoIncrementCheckWithCheckConstraint(t *testing.T) {
+	store := testkit.CreateMockStore(t)
+	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("use test")
+	tk.MustExec(`CREATE TABLE t (
+		id INTEGER NOT NULL AUTO_INCREMENT,
+		CHECK (id IN (0, 1)),
+		KEY idx_autoinc_id (id)
```
Comment (mjonss) [inline planner/core/integration_test.go:7834]: Is this KEY needed?

**Review by mjonss — APPROVED** [review]
LGTM, with a minor question

File: planner/core/integration_test.go (hunk 2 above)
Comment (YangKeao) [reply planner/core/integration_test.go:7834]: Yes. The `AUTO_INCREMENT` column has to be defines as a key (any kind is fine).

**Comment by YangKeao** [comment]
@xhebox @mjonss If there is no more comments, could you help me to merge this PR?
