### PR TITLE
meta: handle 0 concurrency in IterAllTables

### LINKED ISSUE #64450: tidb panic with error [r="runtime error: integer divide by zero"] during autoanalyze
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run br restore

### 2. What did you expect to see? (Required)
no panic

### 3. What did you see instead (Required)
tidb panic with error [r="runtime error: integer divide by zero"] during autoanalyze
`[2025/11/13 02:32:31.603 +08:00] [ERROR] [session.go:322] ["EnterOperation error: panic occurs, avoid to use session again"] [keyspaceName=SYSTEM] [panic="runtime error: integer divide by zero"] [seqStart=36] [seqEnd=37] [sctx=*session.session(0xc002694008)] [caller=*syssession.Session(0xc000b6fc48)] [owner=*syssession.Session(0xc000b6fc48)] [stack="github.com/pingcap/tidb/pkg/session/syssession.(*session).EnterOperation.func1.1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:330\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).EnterOperation.func1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:392\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:791\nruntime.panicdivide\n\t/usr/local/go/src/runtime/panic.go:241\ngithub.com/pingcap/tidb/pkg/meta.splitRangeInt64Max\n\t/workspace/source/tidb/pkg/meta/meta.go:1079\ngithub.com/pingcap/tidb/pkg/meta.IterAllTables\n\t/workspace/source/tidb/pkg/meta/meta.go:1108\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).fetchAllTablesAndBuildAnalysisJobs.func1\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:231\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.WrapTxn\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:197\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1.1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:95\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext.func1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:519\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).OwnerWithSctx\n\t/workspace/source/tidb/pkg/session/syssession/session.go:278\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext\n\t/workspace/source/tidb/pkg/session/syssession/session.go:518\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:83\ngithub.com/pingcap/tidb/pkg/session/syssession.(*AdvancedSessionPool).WithSession\n\t/workspace/source/tidb/pkg/session/syssession/pool.go:274\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:82\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).fetchAllTablesAndBuildAnalysisJobs\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:207\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).rebuildWithoutLock\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:194\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).Initialize\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:152\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/refresher.(*Refresher).AnalyzeHighestPriorityTables\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/refresher/refresher.go:106\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze.(*statsAnalyze).handleAutoAnalyze\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/autoanalyze.go:343\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze.(*statsAnalyze).HandleAutoAnalyze.func1\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/autoanalyze.go:298\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1.1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:97\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext.func1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:519\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).OwnerWithSctx\n\t/workspace/source/tidb/pkg/session/syssession/session.go:278\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext\n\t/workspace/source/tidb/pkg/session/syssession/session.go:518\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:83\ngithub.com/pingcap/tidb/pkg/session/syssession.(*AdvancedSessionPool).WithSession\n\t/workspace/source/tidb/pkg/session/syssession/pool.go:274\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:82\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze.(*statsAnalyze).HandleAutoAnalyze\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/autoanalyze.go:297\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).autoAnalyzeWorker\n\t/workspace/source/tidb/pkg/domain/domain.go:2310\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func3\n\t/workspace/source/tidb/pkg/domain/domain.go:1965\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func5\n\t/workspace/source/tidb/pkg/domain/domain.go:1978\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1\n\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:103"]
[2025/11/13 02:32:31.603 +08:00] [ERROR] [misc.go:118] ["panic in the recoverable goroutine"] [keyspaceName=SYSTEM] [label=stats] [funcInfo=CallWithSCtx] [r="runtime error: integer divide by zero"] [stack="github.com/pingcap/tidb/pkg/util.Recover\n\t/workspace/source/tidb/pkg/util/misc.go:122\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:791\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).EnterOperation.func1.1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:332\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).EnterOperation.func1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:392\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:791\nruntime.panicdivide\n\t/usr/local/go/src/runtime/panic.go:241\ngithub.com/pingcap/tidb/pkg/meta.splitRangeInt64Max\n\t/workspace/source/tidb/pkg/meta/meta.go:1079\ngithub.com/pingcap/tidb/pkg/meta.IterAllTables\n\t/workspace/source/tidb/pkg/meta/meta.go:1108\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).fetchAllTablesAndBuildAnalysisJobs.func1\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:231\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.WrapTxn\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:197\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1.1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:95\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext.func1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:519\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).OwnerWithSctx\n\t/workspace/source/tidb/pkg/session/syssession/session.go:278\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext\n\t/workspace/source/tidb/pkg/session/syssession/session.go:518\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:83\ngithub.com/pingcap/tidb/pkg/session/syssession.(*AdvancedSessionPool).WithSession\n\t/workspace/source/tidb/pkg/session/syssession/pool.go:274\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:82\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).fetchAllTablesAndBuildAnalysisJobs\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:207\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).rebuildWithoutLock\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:194\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue.(*AnalysisPriorityQueue).Initialize\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/priorityqueue/queue.go:152\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/refresher.(*Refresher).AnalyzeHighestPriorityTables\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/refresher/refresher.go:106\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze.(*statsAnalyze).handleAutoAnalyze\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/autoanalyze.go:343\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze.(*statsAnalyze).HandleAutoAnalyze.func1\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/autoanalyze.go:298\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1.1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:97\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext.func1\n\t/workspace/source/tidb/pkg/session/syssession/session.go:519\ngithub.com/pingcap/tidb/pkg/session/syssession.(*session).OwnerWithSctx\n\t/workspace/source/tidb/pkg/session/syssession/session.go:278\ngithub.com/pingcap/tidb/pkg/session/syssession.(*Session).WithSessionContext\n\t/workspace/source/tidb/pkg/session/syssession/session.go:518\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx.func1\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:83\ngithub.com/pingcap/tidb/pkg/session/syssession.(*AdvancedSessionPool).WithSession\n\t/workspace/source/tidb/pkg/session/syssession/pool.go:274\ngithub.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx\n\t/workspace/source/tidb/pkg/statistics/handle/util/util.go:82\ngithub.com/pingcap/tidb/pkg/statistics/handle/autoanalyze.(*statsAnalyze).HandleAutoAnalyze\n\t/workspace/source/tidb/pkg/statistics/handle/autoanalyze/autoanalyze.go:297\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).autoAnalyzeWorker\n\t/workspace/source/tidb/pkg/domain/domain.go:2310\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func3\n\t/workspace/source/tidb/pkg/domain/domain.go:1965\ngithub.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func5\n\t/workspace/source/tidb/pkg/domain/domain.go:1978\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1\n\t/workspace/source/tidb/pkg/util/wait_group_wrapper.go:103"]`

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v9.0.0-beta.2.pre-763-g9e38acf
Edition: Enterprise
Git Commit Hash: 9e38acfdbfaf2bcfd1ad81da127980c3fd84253c
Git Branch: HEAD
UTC Build Time: 2025-11-12 14:02:26
GoVersion: go1.23.12
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Enterprise Extension Commit Hash: dc633aae52eb11b4e3549e3a7ef5b0ed14e159b1
Kernel Type: Next Generation

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What problem does this PR solve?

Issue Number: close #64450

Problem Summary:
Caller may pass 0 concurrency to IterAllTables
### What changed and how does it work?
handle 0 concurrency in IterAllTables
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
fix tidb auto analyze panic in 1C machine
```

### CODE REVIEW

File: pkg/meta/meta.go [hunk 1]
```diff
@@ -1101,9 +1101,7 @@ func IterAllTables(ctx context.Context, store kv.Storage, startTs uint64, concur
 	defer cancel()
 	workGroup, egCtx := util.NewErrorGroupWithRecoverWithCtx(cancelCtx)
 
-	if concurrency >= 15 {
-		concurrency = 15
-	}
+	concurrency = max(1, min(15, concurrency))
```
Comment (D3Hunter) [inline pkg/meta/meta.go:1105]: please comment the reason on why we have `max(1, xx`

Comment (wjhuang2016) [reply pkg/meta/meta.go:1105]: done
