### PR TITLE
planner: implement Clone for PhysicalIndexJoin

### LINKED ISSUE #59863: *core.PhysicalIndexJoin doesn't support cloning causes apply can't be executed in parallel
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set tidb_enable_parallel_apply = on;
create table t(a int, b int, index idx(a));
desc select  t3.a from t t3 where (select /*+ inl_join(t1) */  count(*) from t t1 join t t2 on t1.a=t2.a and t1.b>t3.b);
```

### 2. What did you expect to see? (Required)
No warnings, apply execute in parallel.
### 3. What did you see instead (Required)
```
tidb> drop table t;
Query OK, 0 rows affected (0.02 sec)

tidb> set tidb_enable_parallel_apply = on;
Query OK, 0 rows affected (0.00 sec)

tidb> create table t(a int, b int, index idx(a));
rom t t3 where (select /*+ inl_join(t1) */  count(*) from t t1 join t t2 on t1.a=t2.a and t1.b>t3.b)Query OK, 0 rows affected (0.01 sec)

tidb> desc select  t3.a from t t3 where (select /*+ inl_join(t1) */  count(*) from t t1 join t t2 on t1.a=t2.a and t1.b>t3.b);
+---------------------------------------+--------------+-----------+------------------------+-------------------------------------------------------------------------------------------------------------+
| id                                    | estRows      | task      | access object          | operator info                                                                                               |
+---------------------------------------+--------------+-----------+------------------------+-------------------------------------------------------------------------------------------------------------+
| Projection_14                         | 10000.00     | root      |                        | test.t.a                                                                                                    |
| └─Apply_16                            | 10000.00     | root      |                        | CARTESIAN inner join                                                                                        |
|   ├─TableReader_18(Build)             | 10000.00     | root      |                        | data:TableFullScan_17                                                                                       |
|   │ └─TableFullScan_17                | 10000.00     | cop[tikv] | table:t3               | keep order:false, stats:pseudo                                                                              |
|   └─Selection_19(Probe)               | 8000.00      | root      |                        | Column#10                                                                                                   |
|     └─HashAgg_20                      | 10000.00     | root      |                        | funcs:count(1)->Column#10                                                                                   |
|       └─IndexJoin_39                  | 99900000.00  | root      |                        | inner join, inner:IndexLookUp_38, outer key:test.t.a, inner key:test.t.a, equal cond:eq(test.t.a, test.t.a) |
|         ├─IndexReader_51(Build)       | 99900000.00  | root      |                        | index:IndexFullScan_50                                                                                      |
|         │ └─IndexFullScan_50          | 99900000.00  | cop[tikv] | table:t2, index:idx(a) | keep order:false, stats:pseudo                                                                              |
|         └─IndexLookUp_38(Probe)       | 99900000.00  | root      |                        |                                                                                                             |
|           ├─Selection_36(Build)       | 124875000.00 | cop[tikv] |                        | not(isnull(test.t.a))                                                                                       |
|           │ └─IndexRangeScan_34       | 125000000.00 | cop[tikv] | table:t1, index:idx(a) | range: decided by [eq(test.t.a, test.t.a)], keep order:false, stats:pseudo                                  |
|           └─Selection_37(Probe)       | 99900000.00  | cop[tikv] |                        | gt(test.t.b, test.t.b)                                                                                      |
|             └─TableRowIDScan_35       | 124875000.00 | cop[tikv] | table:t1               | keep order:false, stats:pseudo                                                                              |
+---------------------------------------+--------------+-----------+------------------------+-------------------------------------------------------------------------------------------------------------+
14 rows in set, 1 warning (0.01 sec)

tidb> show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                               |
+---------+------+-------------------------------------------------------------------------------------------------------+
| Warning | 1105 | Some apply operators can not be executed in parallel: *core.PhysicalIndexJoin doesn't support cloning |
+---------+------+-------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #59863 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
Seems `TestPhysicalPlanClone` should be modified to cover this change

**Comment by lance6716** [comment]
> (method AppendChildCandidate has pointer receiver)

Maybe you should use `&PhysicalIndexJoin`. Here's a diff that can run (but I didn't set reasonable values to fields)

```diff
diff --git i/pkg/planner/core/planbuilder_test.go w/pkg/planner/core/planbuilder_test.go
index abcb231aec..f1c92604c6 100644
--- i/pkg/planner/core/planbuilder_test.go
+++ w/pkg/planner/core/planbuilder_test.go
@@ -42,6 +42,7 @@ import (
 	"github.com/pingcap/tidb/pkg/types"
 	"github.com/pingcap/tidb/pkg/util/hint"
 	"github.com/pingcap/tidb/pkg/util/mock"
+	"github.com/pingcap/tidb/pkg/util/ranger"
 	"github.com/stretchr/testify/require"
 )
 
@@ -398,6 +399,14 @@ func TestPhysicalPlanClone(t *testing.T) {
 	mergeJoin = mergeJoin.Init(ctx, stats, 0)
 	mergeJoin.SetSchema(schema)
 	require.NoError(t, checkPhysicalPlanClone(mergeJoin))
+
+	indexJoin := &PhysicalIndexJoin{
+		innerPlan: indexScan,
+		Ranges:    ranger.Ranges{},
+	}
+	indexJoin = indexJoin.Init(ctx, stats, 0)
+	indexJoin.SetSchema(schema)
+	require.NoError(t, checkPhysicalPlanClone(indexJoin))
 }
 
 //go:linkname valueInterface reflect.valueInterface
```

File: pkg/planner/core/physical_plans.go [hunk 1]
```diff
@@ -1626,6 +1627,30 @@ type PhysicalIndexJoin struct {
 	InnerHashKeys []*expression.Column
 }
 
+// Clone implements op.PhysicalPlan interface.
+func (p *PhysicalIndexJoin) Clone(newCtx base.PlanContext) (base.PhysicalPlan, error) {
```
Comment (AilinKid) [inline pkg/planner/core/physical_plans.go:1631]: we need an UT to dive into to assert the element inside

**Review by lance6716 — APPROVED** [review]
