### PR TITLE
domain: fix unstable test TestAbnormalSessionPool

### LINKED ISSUE #36153: unstable test TestAbnormalSessionPool
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2022-07-12T15:16:07.490Z]     db_test.go:115: 

[2022-07-12T15:16:07.490Z]         	Error Trace:	db_test.go:115

[2022-07-12T15:16:07.490Z]         	Error:      	Received unexpected error:

[2022-07-12T15:16:07.490Z]         	            	unix socket /tmp/tidb-{Port}.sock exists and is functional, not removing it

[2022-07-12T15:16:07.490Z]         	            	github.com/pingcap/errors.AddStack

[2022-07-12T15:16:07.490Z]         	            		external/com_github_pingcap_errors/errors.go:174

[2022-07-12T15:16:07.490Z]         	            	github.com/pingcap/errors.Trace

[2022-07-12T15:16:07.490Z]         	            		external/com_github_pingcap_errors/juju_adaptor.go:15

[2022-07-12T15:16:07.490Z]         	            	github.com/pingcap/tidb/server.NewServer

[2022-07-12T15:16:07.490Z]         	            		server/server.go:260

[2022-07-12T15:16:07.490Z]         	            	github.com/pingcap/tidb/domain_test.TestAbnormalSessionPool

[2022-07-12T15:16:07.490Z]         	            		domain/db_test.go:114

[2022-07-12T15:16:07.490Z]         	            	testing.tRunner

[2022-07-12T15:16:07.490Z]         	            		GOROOT/src/testing/testing.go:1439

[2022-07-12T15:16:07.490Z]         	            	runtime.goexit

[2022-07-12T15:16:07.490Z]         	            		GOROOT/src/runtime/asm_amd64.s:1571

[2022-07-12T15:16:07.491Z]         	Test:       	TestAbnormalSessionPool
```

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #36153

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: domain/db_test.go [hunk 1]
```diff
@@ -76,8 +77,8 @@ func TestNormalSessionPool(t *testing.T) {
 	info, err1 := infosync.GlobalInfoSyncerInit(context.Background(), "t", func() uint64 { return 1 }, nil, true)
 	require.NoError(t, err1)
 	conf := config.GetGlobalConfig()
-	conf.Port = 0
-	conf.Status.StatusPort = 10045
+	conf.Port = uint(4000 + rand.Intn(1000))
```
Comment (tangenta) [inline domain/db_test.go:80]: Please use `freeport.GetFreePorts()` instead.

Comment (xhebox) [reply domain/db_test.go:80]: I suggest other fixes, just use `0` since it will allocate a freeport automatically. @hawkingrei 

The real problem is that, socket address is not computed using the allocated free port but 0. It can be fixed by recomputing the address here. Note L254:

https://github.com/pingcap/tidb/blob/756a81701430e3ac496a70dbcc1743b2cbe312dd/server/server.go#L254-L259

Also note that socket path computing is happend in the main binary only:

```
tidb-server/main.go
444:            cfg.Socket = *socket
657:    cfg.Socket = strings.Replace(cfg.Socket, "{Port}", fmt.Sprintf("%d", cfg.Port), 1)
```

That means the path will not changed in tests even if the port is unique.

**Review by tangenta — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by hawkingrei** [comment]
upgrade the bazel config

/merge
