### PR TITLE
executor: fix LEAD and LAG's default value can not adapt to field type

### LINKED ISSUE #11755: Window function LEAD and LAG's default value can not adapt to field type automatically
## Description
## Bug Report

1. What did you do?

```sql
create table lt (d decimal(10, 4));
insert into lt values(0.2),(0.2);
select LEAD(d,1,1) OVER(), LAG(d,1,1) OVER() from lt;
```

2. What did you expect to see?

in mysql 8.0, it is

```sql
+--------------------+-------------------+
| LEAD(d,1,1) OVER() | LAG(d,1,1) OVER() |
+--------------------+-------------------+
|             0.2000 |            1.0000 |
|             1.0000 |            0.2000 |
+--------------------+-------------------+
2 rows in set (0.00 sec)

```

3. What did you see instead?

```sql
+--------------------+-------------------+
| LEAD(d,1,1) OVER() | LAG(d,1,1) OVER() |
+--------------------+-------------------+
|             0.2000 |                 1 |
|                  1 |            0.2000 |
+--------------------+-------------------+
2 rows in set (0.00 sec)

```


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?


```sql
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                              |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v3.0.2
Git Commit Hash: 94498e7d06a244196bb41c3a05dd4c1f6903099a
Git Branch: HEAD
UTC Build Time: 2019-08-07 02:35:52
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```





## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @SunRunAway

### PR DESCRIPTION
**Pull request by blueseason**
### What problem does this PR solve?

Issue Number: close #11755 

Problem Summary: fix LEAD and LAG's default value can not adapt to field type 

### What is changed and how it works?

convert LEAD/LAG default value to field type

### Check List 

Tests 
- Integration test

### Release note 
- fix LEAD and LAG's default value can not adapt to field type

### CODE REVIEW

**Review by wshwsh12 — COMMENTED** [review]
LGTM

File: executor/aggfuncs/builder.go [hunk 1]
```diff
@@ -676,6 +676,13 @@ func buildLeadLag(aggFuncDesc *aggregation.AggFuncDesc, ordinal int) baseLeadLag
 	defaultExpr = expression.NewNull()
 	if len(aggFuncDesc.Args) == 3 {
 		defaultExpr = aggFuncDesc.Args[2]
+		switch et := defaultExpr.(type) {
+		case *expression.Constant:
+			res, err1 := et.Value.ConvertTo(ctx.GetSessionVars().StmtCtx, aggFuncDesc.RetTp)
+			if err1 == nil {
+				defaultExpr = &expression.Constant{Value: res, RetType: aggFuncDesc.RetTp}
+			}
```
Comment (ichn-hu) [inline executor/aggfuncs/builder.go:684]: what if `err1` is not nil?

Comment (blueseason) [reply executor/aggfuncs/builder.go:684]: if err1 not null,  the type conversion is failed, just do nothing and go to the normal process

**Comment by wjhuang2016** [comment]
@ichn-hu PTAL

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by wjhuang2016** [comment]
@blueseason Please resolve the conflict.

**Review by SunRunAway — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
