### PR TITLE
local backend: fix worker err overriden by job generation err

### LINKED ISSUE #47992: import into 10T data with local sort fail for "[BR:PD:ErrPDBatchScanRegion]batch scan region"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. local sort
2. MySQL [smalltable]> IMPORT INTO smalltable.txn_history_new FROM "ks3://qe-testing/kernel-testing/paypay-10t-csv/big.txn_history.*.csv?access-key=xxx&secret-access-key=xxx&endpoint=ksyuncs.com&force-path-style=false&region=Beijing&provider=ks" with thread=16,detached; 

### 2. What did you expect to see? (Required)
import into successfully
### 3. What did you see instead (Required)
```
| 180001 | ks3://qe-testing/kernel-testing/paypay-10t-csv/big.txn_history.*.csv?access-key=xxxxxx&endpoint=xxx&force-path-style=false&provider=ks&region=Beijing&secret-access-key=xxxxxx     | `smalltable`.`txn_history_new`  |      136 | importing | failed    | 9.917TB          |          NULL | [BR:PD:ErrPDBatchScanRegion]batch scan region                                                                                                                                                                              | 2023-10-25 20:48:08.268159 | 2023-10-25 20:48:11.623530 | 2023-10-26 03:32:56.402580 | root@%     |
```
### 4. What is your TiDB version? (Required)

af7b32ced793fdb00d241fe1bcbc4b047ef6daf1
4cd4d5f703e0043c00c36689ae6c50354bae7b6a

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #47992

Problem Summary:

### What is changed and how it works?

put job generation into the same error group as worker

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
send a dummy job before scan region in generating job, and let worker returns error directly

```
| 300001 | //small-2.csv | `test`.`t`|148 | importing| failed | 16B  | NULL | [0]the remaining storage capacity of TiKV is less than 10%%; please increase the storage capacity of TiKV and try again | 2023-11-01 17:42:42.330981 | 2023-11-01 17:42:44.665693 | 2023-11-01 17:42:50.674848 | root@%  |
```
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/lightning/backend/local/localhelper_test.go [hunk 1]
```diff
@@ -252,6 +252,13 @@ func (c *testSplitClient) GetOperator(ctx context.Context, regionID uint64) (*pd
 func (c *testSplitClient) ScanRegions(ctx context.Context, key, endKey []byte, limit int) ([]*split.RegionInfo, error) {
 	c.mu.Lock()
 	defer c.mu.Unlock()
+
+	select {
+	case <-ctx.Done():
```
Comment (lance6716) [inline br/pkg/lightning/backend/local/localhelper_test.go:257]: if err := ctx.Err(); err != nil { ... }

File: br/pkg/lightning/backend/local/local.go [hunk 2]
```diff
@@ -1679,29 +1685,30 @@ func (local *Backend) doImport(ctx context.Context, engine common.Engine, region
...
-		if !common.IsContextCanceledError(err2) {
-			log.FromContext(ctx).Error("worker meets error", zap.Error(err2))
+		return nil
+	})
+	if err := workGroup.Wait(); err != nil {
+		if !common.IsContextCanceledError(err) {
+			log.FromContext(ctx).Error("do import meets error", zap.Error(err))
 		}
-		return firstErr.Get()
+		firstErr.Set(err)
```
Comment (lance6716) [inline br/pkg/lightning/backend/local/local.go:1710]: seems we don't need firstErr, because error group can maintain first error.

File: br/pkg/lightning/backend/local/local.go [hunk 3]
```diff
@@ -1679,29 +1685,30 @@ func (local *Backend) doImport(ctx context.Context, engine common.Engine, region
...
+			regionSplitKeys,
+			jobToWorkerCh,
+			&jobWg,
+		)
+		if err != nil {
+			return err
+		}
+
+		jobWg.Wait()
 		workerCancel()
```
Comment (lance6716) [inline br/pkg/lightning/backend/local/local.go:1703]: also we don't need workerCancel? error group will automatically cancel the derived context when wg.Go returns error

File: br/pkg/lightning/backend/local/local.go (hunk 2 above)
Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1710]: there is a routine above managing job wait and retry, we need it for now, below too

**Review by lance6716 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

File: br/pkg/lightning/backend/local/local.go (hunk 3 above)
Comment (D3Hunter) [reply br/pkg/lightning/backend/local/local.go:1703]: also used to cancel worker when retry count of some job exhausted
