### PR TITLE
ddl: add index prefix length check in modify column

### LINKED ISSUE #64061: modify column doesn't check index constraint during execution
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

First create table

```SQL
create table t(id int, c1 int)
```

Then execute two ddl in parallel:

```SQL
alter table add index idx_c1(c1);
alter table modify column c1 text;
```

### 2. What did you expect to see? (Required)

The second executed ddl should fail with error `ERROR 1170 (42000): BLOB/TEXT column 'c1' used in key specification without a key length`.

### 3. What did you see instead (Required)

Both two ddls may succeed, and we get a structure like:

```SQL
CREATE TABLE `t` (
  `id` int(11) DEFAULT NULL,
  `c1` text DEFAULT NULL,
  KEY `idx_c1` (`c1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"
```

### PR DESCRIPTION
**Pull request by joechenrh**
### What problem does this PR solve?

Issue Number: close #64061

Problem Summary:

As described in issue, we may create some invalid struct like

```SQL
CREATE TABLE `t` (
  `id` int(11) DEFAULT NULL,
  `c1` text DEFAULT NULL,
  KEY `idx_c1` (`c1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"
``` 

If we insert some values with trailing space, index side will truncate these trailing space while table side reserves them, which leads to data inconsistency.

### What changed and how does it work?

Add index has already checked this during execution, just need to do the same check for modify column.

### Check List

Tests 

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/modify_column.go [hunk 1]
```diff
@@ -165,6 +165,18 @@ func (w *worker) onModifyColumn(jobCtx *jobContext, job *model.Job) (ver int64,
...
 
+	// Check index prefix length for the first time
+	if job.SchemaState == model.StateNone {
+		columns := getReplacedColumns(tblInfo, oldCol, args.Column)
+		allIdxs := buildRelatedIndexInfos(tblInfo, oldCol.ID)
+		for _, idx := range allIdxs {
+			if err := checkIndexInModifiableColumns(columns, idx); err != nil {
+				job.State = model.JobStateCancelled
+				return ver, errors.Trace(err)
+			}
```
Comment (joechenrh) [inline pkg/ddl/modify_column.go:176]: I'm not sure if it's ok to convert job to cancelled after check failed.

**Review by fzzf678 — APPROVED** [review]
