### PR TITLE
*: fix PointGet will return an stale value when `tidb_enable_plan_replayer_capture` is set

### LINKED ISSUE #40194: PointGet will return an stale value when `tidb_enable_plan_replayer_capture` is on
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set @@tidb_enable_plan_replayer_capture=1;
create table t1(id int primary key, v int);
insert into t1 values(1, 10);
prepare s from 'select * from t1 where id=1';
execute s;
execute s;
update t1 set v=v+1;
execute s;
```

### 2. What did you expect to see? (Required)

The last `execute s` should return a row (1, 10)

```
mysql> execute s;
+----+------+
| id | v    |
+----+------+
|  1 |   11 |
+----+------+
```

### 3. What did you see instead (Required)

It returns an stale value:

```
mysql> execute s;
+----+------+
| id | v    |
+----+------+
|  1 |   10 |
+----+------+
```

### 4. What is your TiDB version? (Required)

```
mysql> SELECT tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.19.4
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #40194

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: executor/adapter.go [hunk 1]
```diff
@@ -295,8 +296,12 @@ func (a *ExecStmt) PointGet(ctx context.Context) (*recordSet, error) {
 	}
 	a.Ctx.GetSessionVars().StmtCtx.Priority = kv.PriorityHigh
 
+	var pointExecutor *PointGetExecutor
+	useMaxTS := startTs == math.MaxUint64
+
 	// try to reuse point get executor
-	if a.PsStmt.Executor != nil {
+	// We should only use the cached the executor when the startTS is MaxUint64
+	if a.PsStmt.Executor != nil && useMaxTS {
```
Comment (qw4990) [inline executor/adapter.go:304]: Could you add some comments around [the definition of `PlanCacheStmt.Executor`](https://github.com/pingcap/tidb/blob/master/planner/core/plan_cache_utils.go#L412) as well to indicate there is a dangerous assumption that the cached Executor always uses `MaxTS`?

Comment (lcwangchao) [reply executor/adapter.go:304]: Done

**Review by qw4990 — APPROVED** [review]

File: sessiontxn/isolation/optimistic.go [hunk 2]
```diff
@@ -110,7 +110,7 @@ func (p *OptimisticTxnContextProvider) GetStmtForUpdateTS() (uint64, error) {
 // AdviseOptimizeWithPlan providers optimization according to the plan
 // It will use MaxTS as the startTS in autocommit txn for some plans.
 func (p *OptimisticTxnContextProvider) AdviseOptimizeWithPlan(plan interface{}) (err error) {
-	if p.optimizeWithMaxTS || p.isTidbSnapshotEnabled() || p.isBeginStmtWithStaleRead() {
+	if p.optimizeWithMaxTS || p.isTidbSnapshotEnabled() || p.isBeginStmtWithStaleRead() || p.txn != nil {
```
Comment (cfzjywxk) [inline sessiontxn/isolation/optimistic.go:113]: Why add this condition?

File: executor/compiler.go [hunk 3]
```diff
@@ -157,6 +157,11 @@ func (c *Compiler) Compile(ctx context.Context, stmtNode ast.StmtNode) (_ *ExecS
 			}
 		}
 	}
+
+	if err = sessiontxn.OptimizeWithPlanAndThenWarmUp(c.Ctx, stmt.Plan); err != nil {
```
Comment (cfzjywxk) [inline executor/compiler.go:161]: Why move the `OptimizeWithPlanAndThenWarmUp` here from `ExecuteStmt`?

File: sessiontxn/isolation/optimistic.go (hunk 2 above)
Comment (lcwangchao) [reply sessiontxn/isolation/optimistic.go:113]: `AdviseOptimizeWithPlan` is an optimization and should not have too many strong assumptions.  If the txn is already active, it's better to keep the statement goes well without error.

File: executor/compiler.go (hunk 3 above)
Comment (lcwangchao) [reply executor/compiler.go:161]: If `IsPlanReplayerCaptureEnabled` is true, it will invoke `GetReadStmt` and activate the txn. Moving `OptimizeWithPlanAndThenWarmUp` here is to keep the pointget still be optimized before it.

File: sessiontxn/isolation/optimistic.go (hunk 2 above)
Comment (cfzjywxk) [reply sessiontxn/isolation/optimistic.go:113]: It's more clear to use a method like `IsActive` to check whether it's already activated compared with `p.txn != nil`, maybe we could do some improvements in later PRs.

File: executor/compiler.go (hunk 3 above)
Comment (cfzjywxk) [reply executor/compiler.go:161]: Better to add some comments about this constraint here or the possible implicit activation on the interface `GetStmtReadTS` and `GetStmtForUpdateTS`.

**Review by cfzjywxk — APPROVED** [review]

File: executor/compiler.go (hunk 3 above)
Comment (lcwangchao) [reply executor/compiler.go:161]: Added some comments

File: sessiontxn/isolation/optimistic.go (hunk 2 above)
Comment (lcwangchao) [reply sessiontxn/isolation/optimistic.go]: Some comments added

File: executor/adapter.go [hunk 4]
```diff
@@ -295,8 +296,12 @@ func (a *ExecStmt) PointGet(ctx context.Context) (*recordSet, error) {
 	}
 	a.Ctx.GetSessionVars().StmtCtx.Priority = kv.PriorityHigh
 
+	var pointExecutor *PointGetExecutor
+	useMaxTS := startTs == math.MaxUint64
+
 	// try to reuse point get executor
-	if a.PsStmt.Executor != nil {
+	// We should only use the cached the executor when the startTS is MaxUint64
```
Comment (crazycs520) [inline executor/adapter.go:303]: why?
