### PR TITLE
executor: return error for GRANT ALL ON performance_schema.*

### LINKED ISSUE #27867: GRANT ALL ON performance_schema.* succeeds
### 1. Minimal reproduce step (Required)

```sql
create user u1;
grant all on performance_schema.* to u1;
```

### 2. What did you expect to see? (Required)

Error:
```sql
mysql> create user u1;
Query OK, 0 rows affected (0,03 sec)

mysql> grant all on performance_schema.* to u1;
ERROR 1044 (42000): Access denied for user 'root'@'localhost' to database 'performance_schema'
```

### 3. What did you see instead (Required)

Success
```sql
tidb> create user u1;
Query OK, 0 rows affected (0,01 sec)

tidb> grant all on performance_schema.* to u1;
Query OK, 0 rows affected (0,01 sec)
```

### 4. What is your TiDB version? (Required)

```sql
tidb> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.3.0-alpha-36-gceaf67047
Edition: Community
Git Commit Hash: ceaf6704774e6dee9a04b50f75338d51cf3ed7e7
Git Branch: master
UTC Build Time: 2021-09-07 13:06:06
GoVersion: go1.16.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0,00 sec)
```

### PR DESCRIPTION
**Pull request by unconsolable**
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>

### What problem does this PR solve?

Issue Number: close #27867

### What is changed and how it works?

What's Changed:

Return `ErrDBaccessDenied` when dbName is `performance_schema` and priv is `AllPriv` in func `grantDBLevel`

### Release note

```release-note
GRANT ALL ON performance_schema.* will error as follows instead of succeeding:
ERROR 1044 (42000): Access denied for user 'root'@'%' to database 'performance_schema'
```

### CODE REVIEW

**Comment by unconsolable** [comment]
/cc @mjonss @morgo 
PTAL

File: executor/grant_test.go [hunk 1]
```diff
@@ -415,6 +416,16 @@ func (s *testSuite3) TestIssue22721(c *C) {
 	tk.MustExec("GRANT USAGE ON test.xx TO 'sync_ci_data'@'%';")
 }
 
+func (s *testSuite3) TestIssue27867(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("create user issue27867;")
+	c.Assert(tk.Se.Auth(&auth.UserIdentity{Username: "root", Hostname: "localhost"}, nil, nil), IsTrue)
+	err := tk.ExecToErr("grant all on performance_schema.* to issue27867;")
```
Comment (morgo) [inline executor/grant_test.go:424]: Can you test on `PERFormanCE_schema` as well? Schema objects are insensitive in TiDB. There might have been a lower prior to executor/grant.go line 493

File: executor/grant.go [hunk 2]
```diff
@@ -487,6 +487,13 @@ func (e *GrantExec) grantDBLevel(priv *ast.PrivElem, user *ast.UserSpec, interna
 		dbName = e.ctx.GetSessionVars().CurrentDB
 	}
 
+	// Attempts to use GRANT ALL as shorthand for granting privileges
+	// at the database leval fail with an error
+	// See https://dev.mysql.com/doc/refman/8.0/en/performance-schema-table-characteristics.html for more detail
+	if dbName == "performance_schema" && priv.Priv == mysql.AllPriv {
```
Comment (morgo) [inline executor/grant.go:493]: We need to test this doesn't fail with upper cased dbName (see test comment below)

**Review by morgo — CHANGES_REQUESTED** [review]

File: executor/grant_test.go (hunk 1 above)
Comment (unconsolable) [reply executor/grant_test.go:424]: Added.

File: executor/grant.go (hunk 2 above)
Comment (unconsolable) [reply executor/grant.go]: `==` has been replaced by `strings.EqualFold`, thank you for your review.

**Review by morgo — APPROVED** [review]

**Comment by sylzd** [comment]
Maybe it's not a bug, it's the same action as the mysql: https://dev.mysql.com/doc/refman/8.0/en/performance-schema-table-characteristics.html

> Because only a limited set of privileges apply to Performance Schema tables, attempts to use GRANT ALL as shorthand for granting privileges at the database or table leval fail with an error:
```
mysql> GRANT ALL ON performance_schema.*
       TO 'u1'@'localhost';
ERROR 1044 (42000): Access denied for user 'root'@'localhost'
to database 'performance_schema'
mysql> GRANT ALL ON performance_schema.setup_instruments
       TO 'u2'@'localhost';
ERROR 1044 (42000): Access denied for user 'root'@'localhost'
to database 'performance_schema'
```

**Review by mjonss — APPROVED** [review]
LGTM

File: executor/grant.go [hunk 3]
```diff
@@ -487,6 +487,13 @@ func (e *GrantExec) grantDBLevel(priv *ast.PrivElem, user *ast.UserSpec, interna
 		dbName = e.ctx.GetSessionVars().CurrentDB
 	}
 
+	// Attempts to use GRANT ALL as shorthand for granting privileges
+	// at the database leval fail with an error
+	// See https://dev.mysql.com/doc/refman/8.0/en/performance-schema-table-characteristics.html for more detail
+	if strings.EqualFold(dbName, "performance_schema") && priv.Priv == mysql.AllPriv {
```
Comment (Defined2014) [inline executor/grant.go:493]: It's only denied `grant all` statement, TiDB also has different behavior with MySQL in `grant alter`, `grant create`, `grant execute` and so on.

Comment (Defined2014) [reply executor/grant.go:493]: Maybe the best way to fix this issue is to add a permission check for every table?

Comment (unconsolable) [reply executor/grant.go:493]: IMO we can extend the `Priv` check range here to have the same behavior with MySQL, but I wonder why the privilege management works incompatible on `performance_schema` and whether we can fix it via working on that as your suggestion, instead of introducing a special case like this PR. (I am not so familiar to TiDB codebase though.....) cc. @morgo

Comment (djshow832) [reply executor/grant.go:493]: - we can extend the Priv check range here to have the same behavior with MySQL  - Yes
- why the privilege management works incompatible on `performance_schema`  - `performance_schema` is a special system database in MySQL and TiDB ignores the privilege management part previously
- whether we can fix it via working on that as your suggestion - We can try granting every privilege to `performance_schema.*` in MySQL to see the behavior and then copy it to TiDB. Besides, MySQL also forbids granting some privileges to one single table in `performance_schema`.

Comment (unconsolable) [reply executor/grant.go:493]: Got it. I will try granting privileges in MySQL and copy the results to TiDB. I think in this PR we can mainly focus on database level privileges. Thank you for your review~

File: executor/grant.go [hunk 4]
```diff
@@ -487,6 +487,13 @@ func (e *GrantExec) grantDBLevel(priv *ast.PrivElem, user *ast.UserSpec, interna
 		dbName = e.ctx.GetSessionVars().CurrentDB
 	}
 
+	// Some privilege can not be granted to performance_schema.* in MySQL.
+	// As TiDB ignores the privilege management part for this system database,
+	// check is performed here
+	if strings.EqualFold(dbName, "performance_schema") && e.checkPerformanceSchemaPriv(priv.Priv) {
```
Comment (unconsolable) [inline executor/grant.go:493]: `Priv` check has been split to another func.

**Review by djshow832 — APPROVED** [review]
