### PR TITLE
executor: fix auto-id allocation during statements retry

### LINKED ISSUE #20629: Cannot get auto-id in retry 'INSERT INTO ... SELECT FROM'
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Initialization: 
```sql
set @@tidb_txn_mode=""; -- use optimistic transaction
create table t (id int not null auto_increment unique key, idx int unique key, c int);
create table src (a int);
```
Session1, Session2 execute for 100 times:
```sql
insert into t(idx, c) select 1 as idx, 1 as c from src on duplicate key update c = %d;
```
Session3 executes for 100 times:
```sql
insert into src values (null);
```

When these sessions run concurrently:
- session 1 and session 2 conflict each other on the record `(null, 1, %d)`. This triggers the transaction retry.
- The `auto_increment` ids are allocated before conflicts. They are reused in the following retry.
- Since the number of row records in table `src` keep increasing, the auto ids that allocated before conflicts are not enough in retry. As a result, an `index-out-of-range` error is converted to `Cannot get auto-id in retry`.

<details><summary> <strong>The complete test code </strong> </summary>

```go
func (s *seqTestSuite) TestInsertFromSelectConflictRetryAutoID(c *C) {
        tk := testkit.NewTestKitWithInit(c, s.store)
        tk.MustExec("drop table if exists t;")
        tk.MustExec("create table t (id int not null auto_increment unique key, idx int unique key, c int);")
        tk.MustExec("create table src (a int);")
        concurrency := 2
        var wg sync.WaitGroup
        var err []error
        wgCount := concurrency + 1
        wg.Add(wgCount)
        err = make([]error, concurrency)
        for i := 0; i < concurrency; i++ {
                tk := testkit.NewTestKitWithInit(c, s.store)
                tk.MustExec("set autocommit = 1")
                go func(idx int) {
                        for i := 0; i < 10; i++ {
                                sql := fmt.Sprintf("insert into t(idx, c) select 1 as idx, 1 as c from src on duplicate key update c = %[1]d", i)
                                _, e := tk.Exec(sql)
                                if e != nil {
                                        err[idx] = e
                                        wg.Done()
                                        return
                                }
                        }
                        wg.Done()
                }(i)
        }
        var insertErr error
        go func() {
                tk := testkit.NewTestKitWithInit(c, s.store)
                tk.MustExec("set autocommit = 1")
                for i := 0; i < 10; i++ {
                        _, e := tk.Exec("insert into src values (null);")
                        if e != nil {
                                insertErr = e
                                wg.Done()
                                return
                        }
                }
                wg.Done()
        }()
        wg.Wait()
        for _, e := range err {
                c.Assert(e, IsNil)
        }
        c.Assert(insertErr, IsNil)
}
```

</details>

### 2. What did you expect to see? (Required)

All of these statements should encounter no error.

### 3. What did you see instead (Required)

release-3.0: 
```
cannot get valid auto-increment id in retry
```
release-4.0/master
```
Cannot get a valid auto-ID when retrying the statement
```

### 4. What is your TiDB version? (Required)

All of the TiDB versions.

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #20629 

### What is changed and how it works?

What's Changed: 

Since the inserting rows might be different between transaction retries, the auto IDs array in `RetryInfo` can be treated as a buffer: TiDB always try to reuse the IDs in this buffer. Only if the buffer is empty, a new auto ID is allocated from TiKV.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

N/A

### Release note 

- Fix auto-id allocation failed because of transaction's write-conflict retry.

### CODE REVIEW

**Comment by bb7133** [comment]
There is a failed case(https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/57413/pipeline): 

```
[2020-10-27T09:41:30.036Z] session_test.go:1167:
[2020-10-27T09:41:30.036Z]     tk.MustExec("commit")
[2020-10-27T09:41:30.036Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:208:
[2020-10-27T09:41:30.036Z]     tk.c.Assert(err, check.IsNil, check.Commentf("sql:%s, %v, error stack %v", sql, args, errors.ErrorStack(err)))
[2020-10-27T09:41:30.036Z] ... value *errors.withMessage = previous statement: update t set c2 = 33 where c2 = 1: [kv:1062]Duplicate entry '0' for key 'PRIMARY'
[2020-10-27T09:41:30.036Z] ... sql:commit, [], error stack [kv:1062]Duplicate entry '0' for key 'PRIMARY'
[2020-10-27T09:41:30.036Z] previous statement: update t set c2 = 33 where c2 = 1
```
PTAL @tangenta

File: executor/insert_common.go [hunk 1]
```diff
@@ -598,7 +599,7 @@ func (e *InsertValues) fillRow(ctx context.Context, row []types.Datum, hasValue
 
 // isAutoNull can help judge whether a datum is AutoIncrement Null quickly.
 // This used to help lazyFillAutoIncrement to find consecutive N datum backwards for batch autoID alloc.
-func (e *InsertValues) isAutoNull(ctx context.Context, d types.Datum, col *table.Column) bool {
+func (e *InsertValues) isAutoNull(ctx context.Context, d *types.Datum, col *table.Column) bool {
```
Comment (bb7133) [inline executor/insert_common.go:602]: IMHO we don't need to change it to pass-by-reference in case that it may be modified carelessly in the future?

File: executor/insert_common.go [hunk 2]
```diff
@@ -619,41 +620,20 @@ func (e *InsertValues) isAutoNull(ctx context.Context, d types.Datum, col *table
...
-			autoDatum.SetAutoID(id, col.Flag)
-
-			if err = col.HandleBadNull(&autoDatum, e.ctx.GetSessionVars().StmtCtx); err != nil {
-				return nil, err
-			}
-			rows[i][colIdx] = autoDatum
-		}
-	}
-	return rows, nil
+func setDatumAutoIDWithCast(ctx sessionctx.Context, d *types.Datum, id int64, col *table.Column) error {
```
Comment (bb7133) [inline executor/insert_common.go:632]: Do we need `HandleBadNull`?

Comment (tangenta) [reply executor/insert_common.go:632]: Since we `d.SetAutoID` explicitly , the datum must be not null. `HandleBadNull` is meaningless.

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

File: executor/seqtest/seq_executor_test.go [hunk 3]
```diff
@@ -1312,6 +1312,52 @@ func (s *seqTestSuite) TestPessimisticConflictRetryAutoID(c *C) {
...
+				insertErr = e
+				wg.Done()
+				return
+			}
+		}
+		wg.Done()
+	}()
+	wg.Wait()
+	for _, e := range err {
+		c.Assert(e, IsNil)
```
Comment (AilinKid) [inline executor/seqtest/seq_executor_test.go:1356]: should we use the begin/commit to control the ts of txn2 between the begin and commit of txn1? that will make sure the retry is necessary.

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

File: executor/seqtest/seq_executor_test.go (hunk 3 above)
Comment (tangenta) [reply executor/seqtest/seq_executor_test.go:1356]: It seems the explicit `commit` does not trigger auto-retry:
```sql
mysql> create table t (id int auto_increment unique key, idx int unique key, c int);
Query OK, 0 rows affected (0.00 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t(idx, c) values (1, 1) on duplicate key update c = 2;
Query OK, 1 row affected (0.01 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)
```

```sql
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t(idx, c) values (1, 1) on duplicate key update c = 2;
Query OK, 1 row affected (0.00 sec)

mysql> commit;
ERROR 9007 (HY000): Write conflict, txnStartTS=420644278338322432, conflictStartTS=420644277094973440, conflictCommitTS=420644294221365248, key={tableID=49, indexID=2, indexValues={1, }} primary=[]byte(nil) [try again later]
```

Comment (AilinKid) [reply executor/seqtest/seq_executor_test.go:1356]: Because `PessimisticTxn` is set to true by default ...

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
