### PR TITLE
planner: fix a bug for chunk cost model.

### LINKED ISSUE #14146: Can find physical plan when use Chunk Cost model
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Run the following SQL:
```
use test;
drop table t;
create table t(
    a varchar(10)
);
insert into t values(NULL);
analyze table t;
select * from t;
```

2. What did you expect to see?

Get result.

3. What did you see instead?

`ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve? 

Fixes #14146 
When using chunk cost model for some table, it maybe get `Can’t find a proper physical plan for this query`.

### What is changed and how it works?

Check `avgSize`  before using `Log2(avgSize)`

### Check List 

Tests 

Code changes

Side effects

Related changes

Release note

### CODE REVIEW

File: statistics/histogram.go [hunk 1]
```diff
@@ -176,6 +179,9 @@ func (c *Column) AvgColSizeListInDisk(count int64) float64 {
 	// Keep two decimal place.
 	// Minus Log2(avgSize) for unfixed-len type LEN.
 	avgSize := float64(c.TotColSize) / float64(count)
+	if avgSize < 1 {
+		return math.Round((avgSize)*100) / 100
+	}
```
Comment (SunRunAway) [inline statistics/histogram.go]: Could you add unit test in `testStatsSuite.TestAvgColLen`?
