### PR TITLE
ddl, planner, types: add M>=D checking for decimal column definition with default value

### LINKED ISSUE #21835: ddl: add M>=D checking for decimal column definition with default value
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t( col decimal(1,2) not null default 0);

### 2. What did you expect to see? (Required)

ERROR 1427 (42000): For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'col').

### 3. What did you see instead (Required)

ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference

### 4. What is your TiDB version? (Required)

v4.0.8

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #21835  

Problem Summary:

### What is changed and how it works?

What's Changed:
add M>=D checking for decimal column definition with default value
How it Works:
return error if M >= D for decimal column definition
### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

- No release note

### CODE REVIEW

**Comment by blacktear23** [comment]
@TszKitLo40 please take a look at https://github.com/pingcap/tidb/blob/master/planner/core/preprocess.go#L882

**Comment by TszKitLo40** [comment]
> @TszKitLo40 please take a look at:
> https://github.com/pingcap/tidb/blob/master/planner/core/preprocess.go#L882
> I think you can put some grammar check at there.

But the grammar check method here is private

**Comment by blacktear23** [comment]
@TszKitLo40 I mean grammar check such as M >= D can put in planner/core/preprocess.go in `checkColumn` function. As you can see the M's max and D's max check is in this function. Every SQL query is parse by parser and AST will process by executor module and executor module will use planner to create a plan and `preprocess.go` will check the AST's grammar errors before generate the real plan. So I think we should put M >= D check in `preprocess.go`. This will make grammar check code more centralized. :)

**Comment by TszKitLo40** [comment]
> @TszKitLo40 I mean grammar check such as M >= D can put in planner/core/preprocess.go in `checkColumn` function. As you can see the M's max and D's max check is in this function. Every SQL query is parsed by parser and AST will process by executor module and executor module will use planner to create a plan and `preprocess.go` will check the AST's grammar errors before generate the real plan. So I think we should put M >= D check in `preprocess.go`. This will make grammar check code more centralized. :)

It is reasonable. If we add this check in `preprocess.go`, will the planner check M >= D before the check in ddl?

**Comment by blacktear23** [comment]
> > @TszKitLo40 I mean grammar check such as M >= D can put in planner/core/preprocess.go in `checkColumn` function. As you can see the M's max and D's max check is in this function. Every SQL query is parsed by parser and AST will process by executor module and executor module will use planner to create a plan and `preprocess.go` will check the AST's grammar errors before generate the real plan. So I think we should put M >= D check in `preprocess.go`. This will make grammar check code more centralized. :)
> 
> It is reasonable. If we add this check in `preprocess.go`, will the planner check M >= D before the check in ddl?

Yes!

**Comment by TszKitLo40** [comment]
Do you think we should keep the logic I changed? I think we shouldn't ignore the err in `convertToMysqlDecimal`.

**Comment by blacktear23** [comment]
> Do you think we should keep the logic I changed? I think we shouldn't ignore the err in `convertToMysqlDecimal`. @blacktear23

I think yes.

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -935,6 +935,9 @@ func checkColumn(colDef *ast.ColumnDef) error {
 				return types.ErrTooBigDisplayWidth.GenWithStackByArgs(colDef.Name.Name.O, mysql.MaxFloatingTypeWidth)
 			}
 		}
+		if tp.Flen < tp.Decimal {
```
Comment (blacktear23) [inline planner/core/preprocess.go:938]: Below code should move into upper else block. float type can only provide `Flen` and the `Decimal` is `-1`. So current code could break `f float(64)`.

Comment (TszKitLo40) [reply planner/core/preprocess.go]: ok

**Comment by TszKitLo40** [comment]
It seems this PR can also close [#21063](https://github.com/pingcap/tidb/issues/21063)

File: ddl/ddl_api.go [hunk 2]
```diff
@@ -953,6 +953,9 @@ func checkDefaultValue(ctx sessionctx.Context, c *table.Column, hasDefaultValue
 			return nil
 		}
 		if _, err := table.GetColDefaultValue(ctx, c.ToInfo()); err != nil {
+			if types.ErrMBiggerThanD.Equal(err) {
```
Comment (AilinKid) [inline ddl/ddl_api.go:956]: I think this can be removed?

File: types/datum.go [hunk 3]
```diff
@@ -1294,6 +1294,10 @@ func (d *Datum) convertToMysqlDecimal(sc *stmtctx.StatementContext, target *Fiel
 	if err == nil && err1 != nil {
 		err = err1
 	}
+	if err != nil {
+		ret.SetMysqlDecimal(dec)
```
Comment (AilinKid) [inline types/datum.go:1298]: I think this can be removed?

**Review by AilinKid — COMMENTED** [review]
Rest LGTM

**Comment by AilinKid** [comment]
Since we have processed in `precessor.go`, the rest code seems unnecessary?

File: types/datum.go (hunk 3 above)
Comment (TszKitLo40) [reply types/datum.go:1298]: But I think this error can't be ignored.

Comment (bb7133) [reply types/datum.go:1298]: PTAL @breeswish @lysu

Comment (TszKitLo40) [reply types/datum.go:1300]: I have added comment the this line. Do you think it is appropriate? PTAL @breeswish @lysu

File: ddl/ddl_api.go (hunk 2 above)
Comment (TszKitLo40) [reply ddl/ddl_api.go]: Yes. I have removed it.

File: types/datum.go (hunk 3 above)
Comment (AilinKid) [reply types/datum.go:1300]: could you add a test to cover the code?

Comment (TszKitLo40) [reply types/datum.go:1300]: L242 in `types/convert_test.go` can reach the code.

Comment (AilinKid) [reply types/datum.go:1300]: when I remove your code here, the test can also pass...

Comment (TszKitLo40) [reply types/datum.go:1300]: Do you run the test `TestConvertType`?

Comment (AilinKid) [reply types/datum.go:1300]: Yes I did

Comment (TszKitLo40) [reply types/datum.go:1300]: I have sent a screenshot to you. See slack.

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]

**Review by wjhuang2016 — APPROVED** [review]
