### PR TITLE
planner: play replay load restore the table with foreign key with right order.

### LINKED ISSUE #56456: play replay load cannot restore the table with foreign key
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE authors (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE books (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    publication_date DATE NOT NULL,
    author_id INT,
    FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
);

```

### 2. What did you expect to see? (Required)

succeed to run
### 3. What did you see instead (Required)

```
(1824, "Failed to open the referenced table 'authors'")
```

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #56456

Problem Summary:

### What changed and how does it work?

when restoring the table schema, some tables have these dependencies between each other. so we need to disable the ForeignKeyChecks to create table.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
planner: play replay load restore the table with foreign key with right order
```

### CODE REVIEW

File: pkg/executor/plan_replayer.go [hunk 1]
```diff
@@ -467,6 +468,99 @@ func loadStats(ctx sessionctx.Context, f *zip.File) error {
...
+
+func getTableNameFromZipFilename(name string) string {
+	// dbName.tableName.schema.txt
+	s := strings.Split(name, ".")
+	intest.Assert(len(s) == 4, "invalid zip file name")
+	t := strings.Split(s[0], "/")
+	return t[1] + "." + s[1]
+}
+
+func topoSortTable(input []*zip.File) (result []*zip.File, err error) {
```
Comment (YangKeao) [inline pkg/executor/plan_replayer.go:494]: How about turn off [foreign_key_checks](https://docs.pingcap.com/zh/tidb/stable/system-variables#foreign_key_checks) temporarily in the session? Then it will allow creating child table first :thinking: .

Comment (hawkingrei) [reply pkg/executor/plan_replayer.go]: Great, I have refactored the code according to your suggestion.

File: pkg/executor/plan_replayer.go [hunk 2]
```diff
@@ -530,3 +522,24 @@ func (e *PlanReplayerLoadInfo) Update(data []byte) error {
 	}
 	return nil
 }
+
+func (e *PlanReplayerLoadInfo) createTable(z *zip.Reader) error {
+	origin := e.Ctx.GetSessionVars().ForeignKeyChecks
+	e.Ctx.GetSessionVars().ForeignKeyChecks = false
+	defer func() {
+		e.Ctx.GetSessionVars().ForeignKeyChecks = origin
+	}()
```
Comment (winoros) [inline pkg/executor/plan_replayer.go:531]: Add a comment for future reader

**Review by winoros — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

File: pkg/executor/plan_replayer.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/executor/plan_replayer.go]: I have added it.

**Review by lance6716 — APPROVED** [review]
