### PR TITLE
ddl: fix job's row count for global sort

### LINKED ISSUE #59897: Row count is not displayed in `ADMIN SHOW DDL JOBS`
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set @@global.tidb_ddl_enable_fast_reorg = 1;
set @@global.tidb_enable_dist_task = 1;
set @@global.tidb_cloud_storage_uri = "s3://globalsort?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http://127.0.0.1:9000&force-path-style=true";

mysql> create table t(a int, b int);

Query OK, 0 rows affected (0.05 sec)

mysql> insert into t values (1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> select * from t;
+------+------+
| a    | b    |
+------+------+
|    1 |    1 |
+------+------+
1 row in set (0.00 sec)

mysql> alter table t add index idx(a);
Query OK, 0 rows affected (2.93 sec)

mysql> admin show ddl jobs 1;
+--------+---------+------------+-----------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+--------+--------------------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE  | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME                | START_TIME                 | END_TIME                   | STATE  | COMMENTS           |
+--------+---------+------------+-----------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+--------+--------------------+
|    112 | test    | t          | add index | public       |         2 |      110 |         0 | 2025-03-04 18:27:52.579000 | 2025-03-04 18:27:52.579000 | 2025-03-04 18:27:55.529000 | synced | ingest, DXF, cloud |
+--------+---------+------------+-----------+--------------+-----------+----------+-----------+----------------------------+----------------------------+----------------------------+--------+--------------------+
1 row in set (0.01 sec)
```

### 2. What did you expect to see? (Required)

row_count should not be zero.

### 3. What did you see instead (Required)

row_count is zero.

### 4. What is your TiDB version? (Required)

b500d9e1eba04

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #59897

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/backfilling_operators.go [hunk 1]
```diff
@@ -742,77 +738,25 @@ func NewIndexIngestOperator(
...
-	if rs.Added == 0 {
-		return
-	}
-	w.rowCntListener.Written(rs.Added)
-	err = w.backendCtx.IngestIfQuotaExceeded(w.ctx, ck.ID, rs.Added)
-	if err != nil {
-		w.ctx.onError(err)
-		return
-	}
-	rs.Total = w.backendCtx.TotalKeyCount()
```
Comment (D3Hunter) [inline pkg/ddl/backfilling_operators.go:811]: do we need to keep this for local sort?

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: pkg/ddl/backfilling_operators.go (hunk 1 above)
Comment (tangenta) [reply pkg/ddl/backfilling_operators.go:811]: `rs.Total` is not used by anyone, let me remove this field.

**Review by CbcWestwolf — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]
