### PR TITLE
executor: fix the incorrect untouch used in optimistic transactions

### LINKED ISSUE #30410: Lazy constraint check may cause data inconsistency
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* t */ drop table if exists t;
/* t */ create table t (c0 int, c1 varchar(20), c2 varchar(20), unique key(c0), key(c2));
/* t */ insert into t (c0, c1, c2) values (1, null, 'green');

/* t */ set tidb_constraint_check_in_place=0;
/* t */ begin optimistic;
/* t */ insert into t (c0, c1, c2) values (1, 'red', 'white');
/* t */ delete from t where c1 is null;
/* t */ update t set c2 = 'green' where c2 between 'purple' and 'white';
/* t */ commit;
/* t */ admin check table t;
```

Note that tidb_constraint_check_in_place is off by default!

### 2. What did you expect to see? (Required)

No error reported by admin check table.

### 3. What did you see instead (Required)

```sql
/* t */ admin check table t;
-- t >> E8133: handle 1, index:types.Datum{k:0x1, decimal:0x0, length:0x0, i:1, collation:"", b:[]uint8(nil), x:interface {}(nil)} != record:<nil>
```

### 4. What is your TiDB version? (Required)

master (28446605c2e019e84e934602f4bd136294a61ff3)

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What problem does this PR solve?

Issue Number: close #30410

Problem Summary:

When the optimistic transaction is used, the `untouched key` optimization is not compatible with lazy existence check and results in data inconsistency.

### What is changed and how it works?

Disable the `untouched` optimization for this situation when the `presumeNotExist` flag is set.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

Documentation

### Release note

```release-note
Fix the data inconsistency caused by invalid usage of lazy existence check and untouch key optimization.
```

### CODE REVIEW

**Review by zyguan — APPROVED** [review]
LGTM. I've tested this PR with tp-test, no new issue found.

**Review by sticnarf — APPROVED** [review]
LGTM

File: table/tables/index.go [hunk 1]
```diff
@@ -169,8 +169,22 @@ func (c *index) Create(sctx sessionctx.Context, txn kv.Transaction, indexedValue
...
+			// The key is marked as deleted in the memory buffer, as the existence check is done lazily
+			// for optimistic transactions by default. The "untouched" key could still exist in the store,
+			// it's needed to commit this key to do the existence check so unset the untouched flag.
+			if !txn.IsPessimistic() {
+				keyFlags, err := txn.GetMemBuffer().GetFlags(key)
+				if err != nil {
+					return nil, err
+				}
+				if keyFlags.HasPresumeKeyNotExists() {
+					opt.Untouched = false
```
Comment (you06) [inline table/tables/index.go:185]: This will recover the deleted `c0 -> r2` record, then we got the following weird case:

```sql
/* t */ delete from t where c1 is null;
-- t >> 1 rows affected
/* t */ select * from t force index(c0);
-- t >> +----+----+----+
-- t    | C0 | C1 | C2 |
-- t    +----+----+----+
-- t    +----+----+----+
/* t */ update t set c2 = 'green' where c2 between 'purple' and 'white';
-- t >> 1 rows affected
/* t */ select * from t force index(c0);
-- t >> +----+-----+-------+
-- t    | C0 | C1  |  C2   |
-- t    +----+-----+-------+
-- t    |  1 | red | green |
-- t    +----+-----+-------+
/* t */ commit;
-- t >> E1062: Duplicate entry '1' for key 'c0'
```

A risky fix is to return this function directly here since the presume-not-exist keys will be checked when committing.

File: table/tables/index.go [hunk 2]
```diff
@@ -169,8 +169,22 @@ func (c *index) Create(sctx sessionctx.Context, txn kv.Transaction, indexedValue
...
+			}
+			// The key is marked as deleted in the memory buffer, as the existence check is done lazily
+			// for optimistic transactions by default. The "untouched" key could still exist in the store,
+			// it's needed to commit this key to do the existence check so unset the untouched flag.
+			if !txn.IsPessimistic() {
+				keyFlags, err := txn.GetMemBuffer().GetFlags(key)
+				if err != nil {
+					return nil, err
+				}
+				if keyFlags.HasPresumeKeyNotExists() {
```
Comment (youjiali1995) [inline table/tables/index.go:184]: The key is filtered by it before https://github.com/pingcap/tidb/blob/d83ee8cfdad434d212d3229c0be24d9d81ef7ab3/store/driver/txn/txn_driver.go#L290-L292

How about changing `TiDBKVFilter.IsUnnecessaryKeyValue()`? TiDB should commit the key as long as it has `flagPresumeKNE`.

File: table/tables/index.go (hunk 1 above)
Comment (cfzjywxk) [reply table/tables/index.go:185]: Do you mean the current fix will recover the `c0 -> r2` record?

File: table/tables/index.go (hunk 2 above)
Comment (youjiali1995) [reply table/tables/index.go:184]: Ah, the value can't be recognized in this case.

**Review by youjiali1995 — APPROVED** [review]

File: table/tables/index.go (hunk 2 above)
Comment (cfzjywxk) [reply table/tables/index.go:184]: Should we add an assertion at https://github.com/pingcap/tidb/blob/d83ee8cfdad434d212d3229c0be24d9d81ef7ab3/store/driver/txn/txn_driver.go#L290-L292 that if the value is encoded in `unnecessary` format it should not contain certain flags like `flagPresumeKNE`?

Comment (youjiali1995) [reply table/tables/index.go:184]: Good idea!

File: table/tables/index.go (hunk 1 above)
Comment (you06) [reply table/tables/index.go:185]: Yes.

File: store/driver/txn/txn_driver.go [hunk 3]
```diff
@@ -288,5 +289,10 @@ type TiDBKVFilter struct{}
 
 // IsUnnecessaryKeyValue defines which kinds of KV pairs from TiDB needn't be committed.
 func (f TiDBKVFilter) IsUnnecessaryKeyValue(key, value []byte, flags tikvstore.KeyFlags) bool {
-	return tablecodec.IsUntouchedIndexKValue(key, value)
+	isUntouchedValue := tablecodec.IsUntouchedIndexKValue(key, value)
+	if isUntouchedValue && flags.HasPresumeKeyNotExists() {
+		panic(fmt.Sprintf("unexpected path the untouched key=%s value=%s contains PresumeKeyNotExists flag keyFlags=%v",
```
Comment (youjiali1995) [inline store/driver/txn/txn_driver.go:294]: Panic may be too strict. How about making `KVFilter.IsUnnecessaryKeyValue()` return `(bool, error)`? 
https://github.com/tikv/client-go/blob/c0e876615440ebe603550f7bdcfe750ebe90dd5d/txnkv/transaction/2pc.go#L382-L385

If error is not nil, `twoPhaseCommitter.initKeysAndMutations()` reports it to user.

File: table/tables/index.go (hunk 1 above)
Comment (cfzjywxk) [reply table/tables/index.go:185]: It's caused by the same situation that `unionScan` executor dose not merge unique key results, after the delete statement the newly inserted row still exists in memory buffer:
```
r1 -> 1, null, green
1 -> r1

begin;  // insert a conflict row
r2 -> 1, red, white
1 -> r2

// after delete statement.
r2 -> 1, red, white
del r1 -> xxx
del 1 -> r2

```

Comment (you06) [reply table/tables/index.go:185]: > after the delete statement the newly inserted row still exists in memory buffer:

Yes, however, the index `1 -> r2` is missing.

```
// after delete statement.
r2 -> 1, red, white
del r1 -> xxx
del 1 -> r2

// after update statement.
r2 -> 1, red, white
del r1 -> xxx
1 -> r2 // it's recovered here
```

Actually, the ideal solution will be not to delete `1 -> r2` when deleting `1 -> r1`, however, it's too complex for a must-abort transaction.
