### PR TITLE
table/tables: fix a DATA RACE in TestHashPartitionAddRecord

### LINKED ISSUE #53678: DATA RACE in the TestHashPartitionAddRecord
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
==================
WARNING: DATA RACE
Read at 0x00c00299c640 by goroutine 42905:
  reflect.Value.pointer()
      GOROOT/src/reflect/value.go:113 +0x276
  reflect.Value.Pointer()
      GOROOT/src/reflect/value.go:2162 +0x264
  github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf()
      pkg/infoschema/internal/sizer.go:86 +0x399
  github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf()
      pkg/infoschema/internal/sizer.go:53 +0xcc4
  github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf()
      pkg/infoschema/internal/sizer.go:64 +0xaa7
  github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf()
      pkg/infoschema/internal/sizer.go:93 +0x604
  github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf()
      pkg/infoschema/internal/sizer.go:141 +0x207
  github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf()
      pkg/infoschema/internal/sizer.go:64 +0xaa7
  github.com/pingcap/tidb/pkg/infoschema/internal.Sizeof()
      pkg/infoschema/internal/sizer.go:28 +0x1b7
  github.com/pingcap/tidb/pkg/infoschema.(*entry[go.shape.struct { github.com/pingcap/tidb/pkg/infoschema.tableID int64; github.com/pingcap/tidb/pkg/infoschema.schemaVersion int64 },go.shape.interface { AddRecord(github.com/pingcap/tidb/pkg/table/context.MutateContext, []github.com/pingcap/tidb/pkg/types.Datum, ...github.com/pingcap/tidb/pkg/table.AddRecordOption) (github.com/pingcap/tidb/pkg/kv.Handle, error); Allocators(github.com/pingcap/tidb/pkg/table/context.AllocatorContext) github.com/pingcap/tidb/pkg/meta/autoid.Allocators; Cols() []*github.com/pingcap/tidb/pkg/table.Column; DeletableCols() []*github.com/pingcap/tidb/pkg/table.Column; FullHiddenColsAndVisibleCols() []*github.com/pingcap/tidb/pkg/table.Column; GetPartitionedTable() github.com/pingcap/tidb/pkg/table.PartitionedTable; HiddenCols() []*github.com/pingcap/tidb/pkg/table.Column; IndexPrefix() github.com/pingcap/tidb/pkg/kv.Key; Indices() []github.com/pingcap/tidb/pkg/table.Index; Meta() *github.com/pingcap/tidb/pkg/parser/model.TableInfo; RecordPrefix() github.com/pingcap/tidb/pkg/kv.Key; RemoveRecord(github.com/pingcap/tidb/pkg/table/context.MutateContext, github.com/pingcap/tidb/pkg/kv.Handle, []github.com/pingcap/tidb/pkg/types.Datum) error; Type() github.com/pingcap/tidb/pkg/table.Type; UpdateRecord(context.Context, github.com/pingcap/tidb/pkg/table/context.MutateContext, github.com/pingcap/tidb/pkg/kv.Handle, []github.com/pingcap/tidb/pkg/types.Datum, []github.com/pingcap/tidb/pkg/types.Datum, []bool) error; VisibleCols() []*github.com/pingcap/tidb/pkg/table.Column; WritableCols() []*github.com/pingcap/tidb/pkg/table.Column }]).Size()
      pkg/infoschema/sieve.go:36 +0x67
  github.com/pingcap/tidb/pkg/infoschema.(*Sieve[go.shape.struct { github.com/pingcap/tidb/pkg/infoschema.tableID int64; github.com/pingcap/tidb/pkg/infoschema.schemaVersion int64 },go.shape.interface { AddRecord(github.com/pingcap/tidb/pkg/table/context.MutateContext, []github.com/pingcap/tidb/pkg/types.Datum, ...github.com/pingcap/tidb/pkg/table.AddRecordOption) (github.com/pingcap/tidb/pkg/kv.Handle, error); Allocators(github.com/pingcap/tidb/pkg/table/context.AllocatorContext) github.com/pingcap/tidb/pkg/meta/autoid.Allocators; Cols() []*github.com/pingcap/tidb/pkg/table.Column; DeletableCols() []*github.com/pingcap/tidb/pkg/table.Column; FullHiddenColsAndVisibleCols() []*github.com/pingcap/tidb/pkg/table.Column; GetPartitionedTable() github.com/pingcap/tidb/pkg/table.PartitionedTable; HiddenCols() []*github.com/pingcap/tidb/pkg/table.Column; IndexPrefix() github.com/pingcap/tidb/pkg/kv.Key; Indices() []github.com/pingcap/tidb/pkg/table.Index; Meta() *github.com/pingcap/tidb/pkg/parser/model.TableInfo; RecordPrefix() github.com/pingcap/tidb/pkg/kv.Key; RemoveRecord(github.com/pingcap/tidb/pkg/table/context.MutateContext, github.com/pingcap/tidb/pkg/kv.Handle, []github.com/pingcap/tidb/pkg/types.Datum) error; Type() github.com/pingcap/tidb/pkg/table.Type; UpdateRecord(context.Context, github.com/pingcap/tidb/pkg/table/context.MutateContext, github.com/pingcap/tidb/pkg/kv.Handle, []github.com/pingcap/tidb/pkg/types.Datum, []github.com/pingcap/tidb/pkg/types.Datum, []bool) error; VisibleCols() []*github.com/pingcap/tidb/pkg/table.Column; WritableCols() []*github.com/pingcap/tidb/pkg/table.Column }]).Set()
      pkg/infoschema/sieve.go:102 +0x3bd
  github.com/pingcap/tidb/pkg/infoschema.(*infoschemaV2).TableByName()
      pkg/infoschema/infoschema_v2.go:396 +0x764
  github.com/pingcap/tidb/pkg/infoschema.(*SessionExtendedInfoSchema).TableByName()
      pkg/infoschema/infoschema.go:749 +0x2e3
  github.com/pingcap/tidb/pkg/planner/core.(*preprocessor).tableByName()
      pkg/planner/core/preprocess.go:496 +0x3d6
  github.com/pingcap/tidb/pkg/planner/core.(*preprocessor).handleTableName()
      pkg/planner/core/preprocess.go:1576 +0x2f9
  github.com/pingcap/tidb/pkg/planner/core.(*preprocessor).Leave()
      pkg/planner/core/preprocess.go:597 +0x367
  github.com/pingcap/tidb/pkg/parser/ast.(*TableName).Accept()
      pkg/parser/ast/dml.go:452 +0x1dc
  github.com/pingcap/tidb/pkg/parser/ast.(*TableSource).Accept()
      pkg/parser/ast/dml.go:604 +0x90
  github.com/pingcap/tidb/pkg/parser/ast.(*Join).Accept()
      pkg/parser/ast/dml.go:244 +0xb9
  github.com/pingcap/tidb/pkg/parser/ast.(*TableRefsClause).Accept()
      pkg/parser/ast/dml.go:827 +0x8b
  github.com/pingcap/tidb/pkg/parser/ast.(*SelectStmt).Accept()
      pkg/parser/ast/dml.go:1499 +0x50b
  github.com/pingcap/tidb/pkg/planner/core.Preprocess()
      pkg/planner/core/preprocess.go:138 +0x354
  github.com/pingcap/tidb/pkg/executor.(*Compiler).Compile()
      pkg/executor/compiler.go:67 +0x47c
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      pkg/session/session.go:2094 +0xe93
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal()
      pkg/session/session.go:1519 +0x3b9
  github.com/pingcap/tidb/pkg/timer/tablestore.executeSQL()
      pkg/timer/tablestore/store.go:438 +0x16f
  github.com/pingcap/tidb/pkg/timer/tablestore.(*tableTimerStoreCore).List()
      pkg/timer/tablestore/store.go:141 +0x2ec
  github.com/pingcap/tidb/pkg/timer/runtime.(*TimerGroupRuntime).fullRefreshTimers()
      pkg/timer/runtime/runtime.go:234 +0x128
  github.com/pingcap/tidb/pkg/timer/runtime.(*TimerGroupRuntime).loop()
      pkg/timer/runtime/runtime.go:186 +0x6ee
  github.com/pingcap/tidb/pkg/timer/runtime.(*TimerGroupRuntime).loop-fm()
      <autogenerated>:1 +0x3d
  github.com/pingcap/tidb/pkg/timer/runtime.withRecoverUntil.func1()
      pkg/timer/runtime/runtime.go:494 +0x45
  github.com/pingcap/tidb/pkg/util.WithRecovery()
      pkg/util/misc.go:97 +0x77
  github.com/pingcap/tidb/pkg/timer/runtime.withRecoverUntil()
      pkg/timer/runtime/runtime.go:493 +0xcd
  github.com/pingcap/tidb/pkg/timer/runtime.(*TimerGroupRuntime).Start.func1()
      pkg/timer/runtime/runtime.go:127 +0x7b
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:157 +0x86
Previous write at 0x00c00299c640 by goroutine 38327:
  github.com/pingcap/tidb/pkg/table/tables.(*TableCommon).getCols()
      pkg/table/tables/tables.go:341 +0x1cc
  github.com/pingcap/tidb/pkg/table/tables.(*TableCommon).Cols.func1()
      pkg/table/tables/tables.go:351 +0xe7
  sync.(*Once).doSlow()
      GOROOT/src/sync/once.go:74 +0xf0
  sync.(*Once).Do()
      GOROOT/src/sync/once.go:65 +0x44
  github.com/pingcap/tidb/pkg/table/tables.(*TableCommon).Cols()
      pkg/table/tables/tables.go:348 +0x7e
  github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildDataSource()
      pkg/planner/core/logical_plan_builder.go:4875 +0x68ee
  github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildResultSetNode()
      pkg/planner/core/logical_plan_builder.go:449 +0x25a
  github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildJoin()
      pkg/planner/core/logical_plan_builder.go:934 +0xfa5
  github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildResultSetNode()
      pkg/planner/core/logical_plan_builder.go:435 +0xe4
  github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildTableRefs()
      pkg/planner/core/logical_plan_builder.go:427 +0x117
  github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).buildSelect()
      pkg/planner/core/logical_plan_builder.go:4106 +0xb2d
  github.com/pingcap/tidb/pkg/planner/core.(*PlanBuilder).Build()
      pkg/planner/core/planbuilder.go:515 +0xbb1
  github.com/pingcap/tidb/pkg/planner.buildLogicalPlan()
      pkg/planner/optimize.go:549 +0x311
  github.com/pingcap/tidb/pkg/planner.optimize()
      pkg/planner/optimize.go:466 +0xd04
  github.com/pingcap/tidb/pkg/planner.Optimize()
      pkg/planner/optimize.go:334 +0x2737
  github.com/pingcap/tidb/pkg/executor.(*Compiler).Compile()
      pkg/executor/compiler.go:99 +0x7ea
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      pkg/session/session.go:2094 +0xe93
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal()
      pkg/session/session.go:1519 +0x3b9
  github.com/pingcap/tidb/pkg/timer/tablestore.executeSQL()
      pkg/timer/tablestore/store.go:438 +0x16f
  github.com/pingcap/tidb/pkg/timer/tablestore.(*tableTimerStoreCore).List()
      pkg/timer/tablestore/store.go:141 +0x2ec
  github.com/pingcap/tidb/pkg/timer/api.(*defaultTimerClient).GetTimers()
      pkg/timer/api/client.go:188 +0x13a
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*TTLTimersSyncer).SyncTimers()
      pkg/ttl/ttlworker/timer_sync.go:166 +0x33a
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).onTimerTick()
      pkg/ttl/ttlworker/job_manager.go:306 +0x409
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).jobLoop()
      pkg/ttl/ttlworker/job_manager.go:205 +0x127b
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).jobLoop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).loop()
      pkg/ttl/ttlworker/worker.go:134 +0xbb
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).loop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:157 +0x86
Goroutine 42905 (running) created at:
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run()
      pkg/util/wait_group_wrapper.go:155 +0xe4
  github.com/pingcap/tidb/pkg/timer/runtime.(*TimerGroupRuntime).Start()
      pkg/timer/runtime/runtime.go:126 +0x1eb
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*ttlTimerRuntime).Resume()
      pkg/ttl/ttlworker/timer.go:283 +0x35b
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).onTimerTick()
      pkg/ttl/ttlworker/job_manager.go:295 +0x2b1
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).jobLoop()
      pkg/ttl/ttlworker/job_manager.go:205 +0x127b
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*JobManager).jobLoop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).loop()
      pkg/ttl/ttlworker/worker.go:134 +0xbb
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).loop-fm()
      <autogenerated>:1 +0x33
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
      pkg/util/wait_group_wrapper.go:157 +0x86
Goroutine 38327 (running) created at:
  github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run()
      pkg/util/wait_group_wrapper.go:155 +0xe4
  github.com/pingcap/tidb/pkg/ttl/ttlworker.(*baseWorker).Start()
      pkg/ttl/ttlworker/worker.go:71 +0x12e
  github.com/pingcap/tidb/pkg/domain.(*Domain).StartTTLJobManager()
      pkg/domain/domain.go:2990 +0x1c9
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3533 +0x1b71
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:146 +0x974
  github.com/pingcap/tidb/pkg/sessionctx/variable.glob..func204()
      pkg/sessionctx/variable/sysvar.go:1067 +0x58
  github.com/pingcap/tidb/pkg/sessionctx/variable.(*SysVar).ValidateWithRelaxedValidation()
      pkg/sessionctx/variable/variable.go:365 +0x23e
  github.com/pingcap/tidb/pkg/domain.(*Domain).rebuildSysVarCache()
      pkg/domain/sysvar_cache.go:145 +0x904
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadSysVarCacheLoop()
      pkg/domain/domain.go:1747 +0x93
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3426 +0x864
  github.com/pingcap/tidb/pkg/domain.(*Domain).GetSessionCache()
      pkg/domain/sysvar_cache.go:61 +0x50
  github.com/pingcap/tidb/pkg/session.(*session).loadCommonGlobalVariablesIfNeeded()
      pkg/session/session.go:3794 +0x2ce
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt()
      pkg/session/session.go:2008 +0x184
  github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal()
      pkg/session/session.go:1519 +0x3b9
  github.com/pingcap/tidb/pkg/domain.(*Domain).LoadPrivilegeLoop()
      pkg/domain/domain.go:1690 +0x108
  github.com/pingcap/tidb/pkg/session.bootstrapSessionImpl()
      pkg/session/session.go:3419 +0x804
  github.com/pingcap/tidb/pkg/session.BootstrapSession()
      pkg/session/session.go:3318 +0xad
  github.com/pingcap/tidb/pkg/testkit.bootstrap()
      pkg/testkit/mockstore.go:294 +0x94
  github.com/pingcap/tidb/pkg/testkit.CreateMockStoreAndDomain()
      pkg/testkit/mockstore.go:265 +0xd2
  pkg/table/tables/test/partition/partition_test.TestHashPartitionAddRecord()
      pkg/table/tables/test/partition/partition_test.go:143 +0x4c
  testing.tRunner()
      GOROOT/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1648 +0x44
================== 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/logs/tidb_data_race/1796052159523983360#1:build-log.txt%3A18078

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #53678 

Problem Summary:

### What changed and how does it work?

After a add a `table.Table` to cache, it should be read-only and immutable.
But currently the `Cols()` function use lazy-initialization, it initialize (write) some fields and cause read-write confliction, and the data race.

This change avoid the lazy-initialization way, initialize all the fields when creating `table.Table`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)

```
cd pkg/table/tables/test/partition/
go test -race -tags intest -c
./partition.test -test.run ^TestHashPartitionAddRecord$
```

DATA RACE is not easy to reproduce stability.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by hawkingrei — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

File: pkg/table/tables/tables.go [hunk 1]
```diff
@@ -260,6 +260,11 @@ func initTableCommon(t *TableCommon, tblInfo *model.TableInfo, physicalTableID i
 	t.writableColumnsOnce = new(sync.Once)
 	t.fullHiddenColsAndVisibleColumnsOnce = new(sync.Once)
 	t.writableConstraintsOnce = new(sync.Once)
+	_ = t.Cols()
+	_ = t.VisibleCols()
+	_ = t.HiddenCols()
+	_ = t.WritableCols()
+	_ = t.FullHiddenColsAndVisibleCols()
```
Comment (tangenta) [inline pkg/table/tables/tables.go:267]: This PR seems to go the opposite way from https://github.com/pingcap/tidb/pull/50062

Comment (zimulala) [reply pkg/table/tables/tables.go:267]: Now we call `Cols` using `t.publicColumnsOnce`. It feels like there should be no DataRace. Could you explain it here? @tiancaiamao 
https://github.com/pingcap/tidb/pull/53798/files#diff-2b615fee1d4e99193f0469ddef5bb5fa6d372da03767dc4643c24e4982424a1dR354

**Review by zimulala — CHANGES_REQUESTED** [review]

**Comment by tiancaiamao** [comment]
close https://github.com/pingcap/tidb/issues/54651

File: pkg/table/tables/tables.go (hunk 1 above)
Comment (tiancaiamao) [reply pkg/table/tables/tables.go:267]: This data race comes from infoschema V2, and can't be get rid of by using sync.Once.
In infoschema v2, we have cache for tables instead of loading all tables into memory.
Before a table is put into cache, its size need to be calculated. 
How to calculate the size? we use reflect to visit the field of an object recursively...
So when calling sizeof, we're not using the Cols() API, but we do visit the fields of table's columns.
This is the reader part of the DATA RACE.

When someone use the table object, and the lazy initialization logic would modify the object.
So the DATA RACE happen. @zimulala

Comment (D3Hunter) [reply pkg/table/tables/tables.go:267]: only do it for v2?

**Comment by D3Hunter** [comment]
/hold

need fix comments

File: pkg/table/tables/tables.go (hunk 1 above)
Comment (zimulala) [reply pkg/table/tables/tables.go:267]: Currently, I think we can consider dealing with v2 only.
Or if we really want to do it like this PR, how about getting rid of sync.Once?

**Comment by River2000i** [comment]
close https://github.com/pingcap/tidb/issues/54377

**Comment by tiancaiamao** [comment]
Updated and remove the unnecessary old syn.Once 
PTAL @zimulala @D3Hunter

File: pkg/table/tables/tables.go [hunk 2]
```diff
@@ -100,26 +89,45 @@ type TableCommon struct {
...
+			t.writableConstraints = append(t.writableConstraints, con)
+		}
+	}
 }
 
 // Copy copies a TableCommon struct, and reset its column cache. This is not a deep copy.
 func (t *TableCommon) Copy() TableCommon {
 	newTable := *t
-	newTable.ClearColumnsCache()
+	// newTable.ClearColumnsCache()
```
Comment (zimulala) [inline pkg/table/tables/tables.go:130]: Remove this line？

**Review by zimulala — APPROVED** [review]

File: pkg/table/tables/tables.go (hunk 1 above)
Comment (tiancaiamao) [reply pkg/table/tables/tables.go]: Done

**Review by hawkingrei — APPROVED** [review]
