### PR TITLE
ddl: fix the batch check for unique index

### LINKED ISSUE #40592: panic in batchCheckTemporaryUniqueKey
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I don't figure out how to reproduce it. What I know now it's the error in the tidb log.
``` 
["panic in the recoverable goroutine"] [label=ddl] [funcInfo=backfillWorker.run] [r={}] [stack="github.com/pingcap/tidb/util.Recover\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/util/misc.go:120\nruntime.gopanic\n\t/usr/local/go1.19.3/src/runtime/panic.go:884\nruntime.goPanicIndex\n\t/usr/local/go1.19.3/src/runtime/panic.go:113\nencoding/binary.bigEndian.Uint64\n\t/usr/local/go1.19.3/src/encoding/binary/binary.go:179\ngithub.com/pingcap/tidb/tablecodec.DecodeHandleInUniqueIndexValue\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/tablecodec/tablecodec.go:1532\ngithub.com/pingcap/tidb/ddl.(*mergeIndexWorker).batchCheckTemporaryUniqueKey\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/ddl/index_merge_tmp.go:63\ngithub.com/pingcap/tidb/ddl.(*mergeIndexWorker).BackfillDataInTxn.func1\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/ddl/index_merge_tmp.go:133\ngithub.com/pingcap/tidb/kv.RunInNewTxn\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/kv/txn.go:129\ngithub.com/pingcap/tidb/ddl.(*mergeIndexWorker).BackfillDataInTxn\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/ddl/index_merge_tmp.go:118\ngithub.com/pingcap/tidb/ddl.(*backfillWorker).handleBackfillTask\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/ddl/backfilling.go:377\ngithub.com/pingcap/tidb/ddl.(*backfillWorker).run\n\t/Users/pingcap/workspace/build-common@4/go/src/github.com/pingcap/tidb/ddl/backfilling.go:479"]
```

 

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
Add unique index can't finish because of the panic.
### 4. What is your TiDB version? (Required)
master

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve?

Issue Number: close #40592, related to #40464.

Problem Summary:

Previously, I didn't consider the `null` values for #40464. For the unique index, the null column value keys are encoded as `null_val(00)+handle` and the value is empty. However, TiDB tries to decode the handle from index value, the panic happened.

### What is changed and how it works?

This PR takes the null values into consideration, and refine the batch check logic by getting the original key to prevent data inconsistency.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: ddl/index_merge_tmp.go [hunk 1]
```diff
@@ -48,25 +48,12 @@ func (w *mergeIndexWorker) batchCheckTemporaryUniqueKey(txn kv.Transaction, idxR
...
-				// Prevent deleting an unexpected index KV.
-				hdInVal, err := tablecodec.DecodeHandleInUniqueIndexValue(val, w.table.Meta().IsCommonHandle)
-				if err != nil {
-					return errors.Trace(err)
-				}
-				if !idxRecords[i].handle.Equal(hdInVal) {
-					idxRecords[i].skip = true
-				}
+			// Found a value in the original index key.
+			err := checkTempIndexKey(txn, idxRecords[i], val, w.table)
```
Comment (Benjamin2037) [inline ddl/index_merge_tmp.go:54]: if the err is not duplicate key, what react about add index tasks? will it rollback? or just retry?

**Review by Benjamin2037 — APPROVED** [review]
LGTM

File: ddl/index_merge_tmp_test.go [hunk 2]
```diff
@@ -405,6 +406,70 @@ func TestAddIndexMergeDeleteUniqueOnWriteOnly(t *testing.T) {
...
+		case model.StateWriteOnly:
+			_, err := tk1.Exec("insert into t values (1, 1);")
+			assert.NoError(t, err)
+		}
+	}
+	callback.OnJobUpdatedExported.Store(&onJobUpdatedExportedFunc)
+	d.SetHook(callback)
+
+	ddl.MockDMLExecution = func() {
+		_, err := tk1.Exec("delete from t where id = 1;")
```
Comment (hawkingrei) [inline ddl/index_merge_tmp_test.go:459]: use ```tk1.MustExec```.

Comment (tangenta) [reply ddl/index_merge_tmp_test.go:459]: It is executed in the goroutine of add index worker. We had better use `assert` instead of `require`.

**Review by wjhuang2016 — APPROVED** [review]
