### PR TITLE
util/chunk: avoid reuse duplicated chunk column in the pool

### LINKED ISSUE #29554: sometimes the stream_agg return wrong results
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
source [test.txt](https://github.com/pingcap/tidb/files/7495237/test.txt);

// if you can't reproduce, please execute several times
select /*+ hash_agg() */ count(col1), max(col2), min(col2), count(col2), count(1), count(*) from IDT_MULTI21872 where col2 is not null group by col1, col2;

select /*+ stream_agg() */ count(col1), max(col2), min(col2), count(col2), count(1), count(*) from IDT_MULTI21872 where col2 is not null group by col1, col2;
```

### 2. What did you expect to see? (Required)
```
mysql> select /*+ stream_agg() */ count(col1), max(col2), min(col2), count(col2), count(1), count(*) from IDT_MULTI21872 where col2 is not null group by col1, col2;
+-------------+----------------------+----------------------+-------------+----------+----------+
| count(col1) | max(col2)            | min(col2)            | count(col2) | count(1) | count(*) |
+-------------+----------------------+----------------------+-------------+----------+----------+
|           1 |  3483474160408538637 |  3483474160408538637 |           1 |        1 |        1 |
|           1 |  -712285148954991773 |  -712285148954991773 |           1 |        1 |        1 |
...
|           1 | -8957794185274125772 | -8957794185274125772 |           1 |        1 |        1 |
+-------------+----------------------+----------------------+-------------+----------+----------+
103 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
```
mysql> select /*+ stream_agg() */ count(col1), max(col2), min(col2), count(col2), count(1), count(*) from IDT_MULTI21872 where col2 is not null group by col1, col2;
+----------------------+----------------------+----------------------+-------------+----------+----------+
| count(col1)          | max(col2)            | min(col2)            | count(col2) | count(1) | count(*) |
+----------------------+----------------------+----------------------+-------------+----------+----------+
| -4522959929954248182 | -4522959929954248182 | -4522959929954248182 |           1 |        1 |        1 |
|  8785184831897790124 |  8785184831897790124 |  8785184831897790124 |           1 |        1 |        1 |
...
|  7320670807156461105 |  7320670807156461105 |  7320670807156461105 |           1 |        1 |        1 |
+----------------------+----------------------+----------------------+-------------+----------+----------+
103 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-45-ge98d58757
Edition: Community
Git Commit Hash: e98d587577d66e358c50edaa39f08852a0b3314d
Git Branch: master
UTC Build Time: 2021-11-08 06:43:19
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve?

Issue Number: close #29554 and https://github.com/pingcap/tics/issues/3406

Problem Summary:

### What is changed and how it works?

Not all the chunk columns are allocated, some are just reference to other columns.

For example, here the second column is the same with the third column, and the fourth column is even a reference to another chunk column:

image

So when we recycle the chunk column for  reuse, we must deduplication to avoid introduce the same chunk column to the pool twice. The old array is changed to a map.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by guo-shaoge — APPROVED** [review]

File: util/chunk/alloc.go [hunk 1]
```diff
@@ -123,32 +123,33 @@ func (alloc *poolColumnAllocator) put(col *Column) {
...
 	l.push(col)
 }
 
-type freeList struct {
-	data []*Column
-}
+// freeList is defined as a map, rather than a list, because when recycling chunk
+// columns, there could be duplicated one: some of the chunk columns are just the
+// reference to the others.
+type freeList map[*Column]struct{}
```
Comment (guo-shaoge) [inline util/chunk/alloc.go:135]: Does this map affects the performance improvements?

Comment (tiancaiamao) [reply util/chunk/alloc.go:135]: It's allocated once and reused...

**Review by lcwangchao — APPROVED** [review]
