### PR TITLE
planner: Add table engine name check

### LINKED ISSUE #21082: wrong engine type
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table t(id int) engine="innodb\\"#test";

### 2. What did you expect to see? (Required)
ERROR 1286 (42000): Unknown storage engine 'innodb"#test'

### 3. What did you see instead (Required)
Query OK, 0 rows affected (0.01 sec)

### 4. What is your TiDB version? (Required)
Version: None
Edition: Community
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

you can check this on master branch, I used git commit ID: c5c3053c31b0fcf1d5d604d7b38554f0c1f6df20(of master)

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #21082 

### What is changed and how it works?

What's Changed:

Add table engine check on preprocessor.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- No

### Release note 

- planner: Add storage engine check

### CODE REVIEW

File: planner/core/preprocess.go [hunk 1]
```diff
@@ -822,11 +822,37 @@ func checkUnsupportedTableOptions(options []*ast.TableOption) error {
...
+			err := checkTableEngine(option.StrValue)
+			if err != nil {
+				return err
+			}
 		}
 	}
 	return nil
 }
 
+var mysqlValidTableEngineNames = map[string]string{
```
Comment (xiongjiwei) [inline planner/core/preprocess.go:835]: use `map[string]struct{}` may better if we only use the key

**Comment by bb7133** [comment]
LGTM

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by XuHuaiyu — DISMISSED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

**Comment by XuHuaiyu** [comment]
@blacktear23 Please resolve the conflicts

**Comment by XuHuaiyu** [comment]
@bb7133 should we cherrypick this to release-4.0?

**Review by XuHuaiyu — APPROVED** [review]

**Review by xiongjiwei — COMMENTED** [review]
/merge

**Comment by bb7133** [comment]
There are some internal tests we may need to update.

**Comment by blacktear23** [comment]
I found there has a test bug, SQL is: 
```
create table t1 (a int)
engine = x
partition by key (a);
```
that will cause unknown storage engine error.

**Review by bb7133 — APPROVED** [review]

**Comment by blacktear23** [comment]
@bb7133 I think we should ask end user, do they use some table engine not in list. Such as XtraDB, or some MariaDB's table engine.
