### PR TITLE
planner: ensure that the path of the plan replayer file generated by the old and new versions of TiDB is the same

### LINKED ISSUE #66347: The file generated by `Plan Replayer` has changed its storage path.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. start a tidb cluster with TiDB version 550a05a2ff087bab7260f5dc6f8542b1f82e22e8;
2. execute `plan replayer`
3. check the file path
4. start a tidb cluster with TiDB master branch 45621f684102f111d6eccd34a4d4f12767943bbe
5. repeat 2,3
### 2. What did you expect to see? (Required)
The paths to the generated files should be the same in both cases.

### 3. What did you see instead (Required)
The paths to the generated files are not the same in both cases.

### PR DESCRIPTION
**Pull request by zeminzhou**
### What problem does this PR solve?

Issue Number: close #66347

Problem Summary:

#### Root cause
getLocalPathDirName() in pkg/planner/extstore/extstore.go decides the local storage root for plan replayer when no cloud storage URI is set. Plan replayer then writes objects under GetPlanReplayerDirName() (i.e. the "replayer" segment) relative to that root. So the effective path is <getLocalPathDirName()>/replayer/<filename>. For backward compatibility, this must match the old layout: <log_dir>/replayer/<filename>, i.e. the storage root must be the log directory, not a path that already includes replayer.
#### Fix
Ensure getLocalPathDirName() returns the log directory (filepath.Dir(config.GetGlobalConfig().Log.File.Filename)), same as the old behavior, so the storage root is unchanged.
Keep writability checks so we only use this log dir when we can actually write there (or when we can write under the replayer subdir, depending on the chosen check).
No change to how plan replayer builds object keys: it still uses replayer/<filename>, so the final path remains <log_dir>/replayer/<filename> and matches old TiDB.
#### Result
Old and new TiDB versions use the same plan replayer file location for local storage, so upgrades and path-dependent tooling remain compatible.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/extstore/extstore_test.go [hunk 1]
```diff
@@ -152,11 +152,11 @@ func TestGetLocalPathDirNameWithWritePerm(t *testing.T) {
 	})
 
 	fs := afero.NewMemMapFs()
-	require.NoError(t, fs.MkdirAll("/var/log/tidb", 0o755))
+	require.NoError(t, fs.MkdirAll("/var/log/tidb/replayer", 0o755))
```
Comment (hawkingrei) [inline pkg/planner/extstore/extstore_test.go:155]: Please use ```t.TempDir``` in the test case.
