### PR TITLE
 planner: avoid cartesian join for OR+IN subquery in filters | tidb-test=pr/2682

### LINKED ISSUE #64333: `a > 1 or a in (subquery)` will lead the CARTESIAN join
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1(a int default null);
create table t(a int not null);
explain select * from t1 where t1.a>1 or t1.a in (select a from t);
```

### 2. What did you expect to see? (Required)

we can rewrite it as
```
explain select * from t1 where t1.a>1 or exists (select a from t where t1.a = t.a);
```

```
+-----------------------------+----------+-----------+---------------+---------------------------------------------------------------------------------+
| id                          | estRows  | task      | access object | operator info                                                                   |
+-----------------------------+----------+-----------+---------------+---------------------------------------------------------------------------------+
| Projection_8                | 8000.00  | root      |               | test.t1.a                                                                       |
| └─Selection_11              | 8000.00  | root      |               | or(gt(test.t1.a, 1), Column#5)                                                  |
|   └─HashJoin_20             | 10000.00 | root      |               | left outer semi join, left side:TableReader_22, equal:[eq(test.t1.a, test.t.a)] |
|     ├─TableReader_24(Build) | 10000.00 | root      |               | data:TableFullScan_23                                                           |
|     │ └─TableFullScan_23    | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo                                                  |
|     └─TableReader_22(Probe) | 10000.00 | root      |               | data:TableFullScan_21                                                           |
|       └─TableFullScan_21    | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                  |
+-----------------------------+----------+-----------+---------------+---------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

```
+-----------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
| id                          | estRows  | task      | access object | operator info                                                                                |
+-----------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
| Projection_7                | 8000.00  | root      |               | test.t1.a                                                                                    |
| └─Selection_10              | 8000.00  | root      |               | or(gt(test.t1.a, 1), Column#5)                                                               |
|   └─HashJoin_19             | 10000.00 | root      |               | CARTESIAN left outer semi join, left side:TableReader_21, other cond:eq(test.t1.a, test.t.a) |
|     ├─TableReader_23(Build) | 10000.00 | root      |               | data:TableFullScan_22                                                                        |
|     │ └─TableFullScan_22    | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo                                                               |
|     └─TableReader_21(Probe) | 10000.00 | root      |               | data:TableFullScan_20                                                                        |
|       └─TableFullScan_20    | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                               |
+-----------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by fixdb**
### What problem does this PR solve?

Issue Number: close #64333

Problem Summary:
Queries like "a > 1 OR a IN (SELECT ...)" could produce a CARTESIAN left outer semi join. OR forces IN(subquery) to be rewritten as a scalar expression. The scalar-IN path marks the equality as EQCondFromIn (via Column.InOperand), which prevents it from being extracted into Join.EqualConditions, leaving HashJoin with no join keys.

### What changed and how does it work?
In WHERE/HAVING boolean chains composed only of AND/OR, treat scalar IN(subquery) as EXISTS-like filter semantics and avoid setting InOperand. This allows the equality to be extracted as normal join keys, preventing CARTESIAN plans while preserving correctness in observable-NULL contexts.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fixes issues where queries like "a > 1 OR a IN (SELECT ...)" could produce a CARTESIAN left outer semi join.
```

### CODE REVIEW

File: pkg/planner/core/expression_rewriter.go [hunk 1]
```diff
@@ -675,6 +678,30 @@ func (er *expressionRewriter) Enter(inNode ast.Node) (ast.Node, bool) {
 	return inNode, false
 }
 
+func (er *expressionRewriter) canTreatInSubqueryAsExistsForFilter(planCtx *exprRewriterPlanCtx) bool {
```
Comment (winoros) [inline pkg/planner/core/expression_rewriter.go:683]: Maybe we can add some comments

Comment (fixdb) [reply pkg/planner/core/expression_rewriter.go:683]: done

**Review by hawkingrei — APPROVED** [review]
