### PR TITLE
resourcemanager: fix TaskController.Stop() can't make producer exit in spmcpool 

### LINKED ISSUE #41015: Call `TaskController.Stop()` can't make producer exit in spmcpool
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
TestAddIndexUniqueFailOnDuplicate with TiDBEnableDistributeReorg(true) 

### 2. What did you expect to see? (Required)
Executed successfully.

### 3. What did you see instead (Required)

We encountered an error and the consumer exits early by calling `TaskController.Stop()`, but the producer doesn't exit, so the test can't return normally.

```
goroutine 13890 [chan send, 9 minutes]:
github.com/pingcap/tidb/util/gpool/spmc.(*Pool[...]).AddProduceBySlice.func1()
	/Users/xia/workspace/src/github.com/pingcap/tidb/util/gpool/spmc/spmcpool.go:299 +0x2be
created by github.com/pingcap/tidb/util/gpool/spmc.(*Pool[...]).AddProduceBySlice
	/Users/xia/workspace/src/github.com/pingcap/tidb/util/gpool/spmc/spmcpool.go:277 +0x44d
```

It seems we need to notify the producer when `TaskController.Stop()`.

### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/pull/40542

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### What problem does this PR solve?

Issue Number: close #41015

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: resourcemanager/pooltask/task.go [hunk 1]
```diff
@@ -127,35 +127,37 @@ type GPool[T any, U any, C any, CT any, TF Context[CT]] interface {
...
-	<-t.close
+	<-t.closeCh
 	t.wg.Wait()
 	close(t.resultCh)
 	t.pool.DeleteTask(t.taskID)
 }
 
 // Stop is to send stop command to the task. But you still need to wait the task to stop.
 func (t *TaskController[T, U, C, CT, TF]) Stop() {
-	t.pool.StopTask(t.TaskID())
```
Comment (zimulala) [inline resourcemanager/pooltask/task.go:158]: Why remove this code?

Comment (hawkingrei) [reply resourcemanager/pooltask/task.go:158]: Sorry, It is unnecessary to delete.

File: util/gpool/spmc/spmcpool.go [hunk 2]
```diff
@@ -297,6 +300,11 @@ func (p *Pool[T, U, C, CT, TF]) AddProduceBySlice(producer func() ([]T, error),
 					Task: task,
 				}
 				inputCh <- task
```
Comment (zimulala) [inline util/gpool/spmc/spmcpool.go:302]: Maybe we will block it here after we close(`productCloseCh`). e.g. We get 3 tasks when putting the second task to `inputCh`, the `productCloseCh` is closed and the consumer is exit

File: resourcemanager/pooltask/task.go [hunk 3]
```diff
@@ -127,34 +127,38 @@ type GPool[T any, U any, C any, CT any, TF Context[CT]] interface {
...
+	t.prodWg.Wait()
 	t.wg.Wait()
 	close(t.resultCh)
 	t.pool.DeleteTask(t.taskID)
 }
 
 // Stop is to send stop command to the task. But you still need to wait the task to stop.
 func (t *TaskController[T, U, C, CT, TF]) Stop() {
+	close(t.productCloseCh)
+	t.wg.Wait()
```
Comment (zimulala) [inline resourcemanager/pooltask/task.go:161]: Feeling like a deadlock? Here may be no consumer consumption task

File: resourcemanager/pooltask/task.go [hunk 4]
```diff
@@ -127,35 +129,40 @@ type GPool[T any, U any, C any, CT any, TF Context[CT]] interface {
...
 	close(t.resultCh)
 	t.pool.DeleteTask(t.taskID)
 }
 
 // Stop is to send stop command to the task. But you still need to wait the task to stop.
 func (t *TaskController[T, U, C, CT, TF]) Stop() {
+	close(t.productCloseCh)
+	t.prodWg.Wait()
 	t.pool.StopTask(t.TaskID())
+	channel.Clear(t.resultCh)
```
Comment (zimulala) [inline resourcemanager/pooltask/task.go:165]: line162 close `productCloseCh`, but it is no consumer consumption task. Is it a deadlock？

Comment (hawkingrei) [reply resourcemanager/pooltask/task.go]: Fix

File: util/gpool/spmc/spmcpool.go (hunk 2 above)
Comment (hawkingrei) [reply util/gpool/spmc/spmcpool.go]: fix

File: util/gpool/spmc/spmcpool_test.go [hunk 5]
```diff
@@ -114,10 +114,49 @@ func TestStopPool(t *testing.T) {
...
+			return []int{1, 2, 3}, nil
+		}
+	}
+	// add new task
+	resultCh, control := pool.AddProduceBySlice(pfunc, myArgs, pooltask.NilContext{}, WithConcurrency(4))
+
+	var wg sync.WaitGroup
+	wg.Add(1)
+	go func() {
+		defer wg.Done()
```
Comment (zimulala) [inline util/gpool/spmc/spmcpool_test.go:152]: Could we add the `control.Stop()` here, like https://github.com/pingcap/tidb/pull/40542/files#diff-192b5bb5d7cd86dfa5e5223cdece209444dc6b5de220d92648d4385098228b9bR183-R190

File: resourcemanager/pooltask/task.go [hunk 6]
```diff
@@ -127,35 +129,44 @@ type GPool[T any, U any, C any, CT any, TF Context[CT]] interface {
...
 	t.pool.DeleteTask(t.taskID)
 }
 
 // Stop is to send stop command to the task. But you still need to wait the task to stop.
 func (t *TaskController[T, U, C, CT, TF]) Stop() {
+	close(t.productExitCh)
+	// Clear all the task in the task queue and mark all task complete.
+	// so that ```t.Wait``` is able to close resultCh
+	for range t.inputCh {
+		t.wg.Done()
```
Comment (zimulala) [inline resourcemanager/pooltask/task.go:165]: Why call `Done` here? I seem we call `Done` https://github.com/pingcap/tidb/pull/41016/files#diff-526c36d8ad42670e920fd84ae336d6b60196c61639bfa1c3a572adad64d1836cR283.

Comment (hawkingrei) [reply resourcemanager/pooltask/task.go:165]: This ```waitgroup``` is to wait for the producer and all tasks to be completed. But when we force the produce and all workers to stop, Some tasks are still in the queue. we need to mark this complete. then ```Wait``` can exit.

File: util/gpool/spmc/spmcpool_test.go (hunk 5 above)
Comment (hawkingrei) [reply util/gpool/spmc/spmcpool_test.go:156]: Done

**Review by zimulala — APPROVED** [review]
LGTM

**Comment by zimulala** [comment]
PTAL @YangKeao @Benjamin2037

File: util/gpool/spmc/spmcpool.go [hunk 7]
```diff
@@ -260,9 +259,9 @@ func (p *Pool[T, U, C, CT, TF]) AddProduceBySlice(producer func() ([]T, error),
 	taskID := p.NewTaskID()
 	var wg sync.WaitGroup
 	result := make(chan U, opt.ResultChanLen)
-	closeCh := make(chan struct{})
+	productExitCh := make(chan struct{})
 	inputCh := make(chan pooltask.Task[T], opt.TaskChanLen)
```
Comment (lance6716) [inline util/gpool/spmc/spmcpool.go:263]: https://github.com/uber-go/guide/blob/master/style.md#channel-size-is-one-or-none

In my experience, it's really helpful to force us to think about more extreme situations and avoid bug in advance. I'm more like unbuffered channel now because we always need to deal with sender's blocking (golang has no unlimited length channel) and unbuffered channel means we do not need to drain elements when receiver is closing

File: util/gpool/spmc/spmcpool.go [hunk 8]
```diff
@@ -274,29 +273,35 @@ func (p *Pool[T, U, C, CT, TF]) AddProduceBySlice(producer func() ([]T, error),
...
 			}
-			close(closeCh)
 			close(inputCh)
+			wg.Done()
 		}()
 		for {
-			tasks, err := producer()
-			if err != nil {
-				if errors.Is(err, gpool.ErrProducerClosed) {
+			select {
```
Comment (Benjamin2037) [inline util/gpool/spmc/spmcpool.go:286]: this part code seem same with line 342，could we merge them into one func？

File: util/gpool/spmc/spmcpool.go (hunk 7 above)
Comment (hawkingrei) [reply util/gpool/spmc/spmcpool.go:263]: Agree with you. Let me set TaskChanLen's default value as 1.

Comment (hawkingrei) [reply util/gpool/spmc/spmcpool.go:263]: Done

File: util/gpool/spmc/spmcpool.go (hunk 8 above)
Comment (hawkingrei) [reply util/gpool/spmc/spmcpool.go]: Done

**Comment by zimulala** [comment]
PTAL @Benjamin2037 @lance6716

File: util/gpool/spmc/option.go [hunk 9]
```diff
@@ -103,8 +103,8 @@ func loadTaskOptions(options ...TaskOption) *TaskOptions {
 	if opts.ResultChanLen == 0 {
 		opts.ResultChanLen = uint64(opts.Concurrency)
 	}
-	if opts.ResultChanLen == 0 {
-		opts.ResultChanLen = uint64(opts.Concurrency)
+	if opts.TaskChanLen == 0 {
+		opts.TaskChanLen = 1
```
Comment (Benjamin2037) [inline util/gpool/spmc/option.go:107]: Could we use meaningful const instead of 0 or 1 to make code more readable?

Comment (hawkingrei) [reply util/gpool/spmc/option.go]: Done, add ```defaultTaskChanLen`` const.

**Comment by hawkingrei** [comment]
PTAL @YangKeao @Benjamin2037

**Review by Benjamin2037 — APPROVED** [review]
LGTM
