### PR TITLE
executor: keep analyze status remaining time in UTC

### LINKED ISSUE #67230: show analyze status: Remaining_seconds can become negative in non-UTC sessions
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t (a INT PRIMARY KEY, b INT);
INSERT INTO t VALUES (1, 1), (2, 2);
ANALYZE TABLE t;

DELETE FROM mysql.analyze_jobs;
SET @@time_zone = '+08:00';
INSERT INTO mysql.analyze_jobs (
    table_schema,
    table_name,
    partition_name,
    job_info,
    processed_rows,
    start_time,
    state,
    instance
) VALUES (
    'test',
    't',
    '',
    'analyze table all indexes, all columns with 256 buckets, 100 topn, 1 samplerate',
    1,
    CURRENT_TIMESTAMP - INTERVAL 1 MINUTE,
    'running',
    'tidb-server:4000'
);

SHOW ANALYZE STATUS WHERE table_name = 't' AND state = 'running';
```

### 2. What did you expect to see? (Required)

`Remaining_seconds` should be non-negative for a running analyze job.

### 3. What did you see instead (Required)

`Remaining_seconds` is negative when the session `time_zone` is ahead of UTC. For example:

```sql
+--------------+------------+------------------+
| TABLE_NAME   | STATE      | REMAINING_SECONDS|
+--------------+------------+------------------+
| t            | running    | -7h58m59s        |
+--------------+------------+------------------+
```

The issue is that `SHOW ANALYZE STATUS` converts `start_time` to the session timezone for display and then reuses that display value as if it were UTC when computing the remaining duration.

### 4. What is your TiDB version? (Required)

master

### PR DESCRIPTION
**Pull request by 0xPoe**
### What problem does this PR solve?

Issue Number: close #67230

Problem Summary:

`SHOW ANALYZE STATUS` can report a negative `Remaining_seconds` when the session `time_zone` is ahead of UTC.

### What changed and how does it work?

Keep the UTC `start_time` for remaining-time calculation and continue using the session-local time only for display. This PR also adds a regression test that reproduces the negative duration under `+08:00`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Validation commands:
- `make failpoint-enable`
- `go test -run '^TestShowAnalyzeStatus$' -tags=intest,deadlock ./pkg/executor`
- `make failpoint-disable`
- `make lint`

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix negative Remaining_seconds in SHOW ANALYZE STATUS when the session time_zone is ahead of UTC.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed duration/remaining-time calculation for running analyze jobs by using a UTC-based start time and stricter validation to avoid negative or invalid remaining-time displays.

* **Tests**
  * Added a test verifying analyze-job durations display correctly when the session time zone is non-default.

### CODE REVIEW

File: pkg/executor/infoschema_reader.go [hunk 1]
```diff
@@ -2548,11 +2548,13 @@ func dataForAnalyzeStatusHelper(ctx context.Context, e *memtableRetriever, sctx
...
 		processedRows := chunkRow.GetInt64(4)
 		var startTime, endTime any
+		var startTimeUTC *time.Time
 		if !chunkRow.IsNull(5) {
 			t, err := chunkRow.GetTime(5).GoTime(time.UTC)
 			if err != nil {
 				return nil, err
 			}
+			startTimeUTC = &t
 			startTime = types.NewTime(types.FromGoTime(t.In(sctx.GetSessionVars().TimeZone)), mysql.TypeDatetime, 0)
```
Comment (0xPoe) [inline pkg/executor/infoschema_reader.go:2560]: This is where the original bug comes form. We use the session time, but we applied it as UTC in later usage.

File: pkg/executor/infoschema_reader.go [hunk 2]
```diff
@@ -2617,16 +2618,12 @@ func dataForAnalyzeStatusHelper(ctx context.Context, e *memtableRetriever, sctx
 
 func getRemainDurationForAnalyzeStatusHelper(
 	ctx context.Context,
-	sctx sessionctx.Context, startTime *types.Time,
+	sctx sessionctx.Context, startTimeUTC *time.Time,
 	dbName, tableName, partitionName string, processedRows int64,
 ) (_ *time.Duration, percentage, totalCnt float64, err error) {
 	remainingDuration := time.Duration(0)
-	if startTime != nil {
-		start, err := startTime.GoTime(time.UTC)
```
Comment (0xPoe) [inline pkg/executor/infoschema_reader.go:2623]: Buggy code!

File: pkg/executor/infoschema_reader.go [hunk 3]
```diff
@@ -2548,11 +2548,13 @@ func dataForAnalyzeStatusHelper(ctx context.Context, e *memtableRetriever, sctx
 		jobInfo := chunkRow.GetString(3)
 		processedRows := chunkRow.GetInt64(4)
 		var startTime, endTime any
+		var startTimeUTC *time.Time
```
Comment (winoros) [inline pkg/executor/infoschema_reader.go:2553]:
```suggestion
		// startTime and endTime use the local timezone for displaying.
		// startTimeUTC is used to calculate the remaining duration of the job.
		var startTime, endTime any
		var startTimeUTC *time.Time
```

Comment (0xPoe) [reply pkg/executor/infoschema_reader.go:2553]: Thank you! Updated.

File: pkg/executor/infoschema_reader.go [hunk 4]
```diff
@@ -2615,16 +2620,12 @@ func dataForAnalyzeStatusHelper(ctx context.Context, e *memtableRetriever, sctx
...
 ) (_ *time.Duration, percentage, totalCnt float64, err error) {
 	remainingDuration := time.Duration(0)
-	if startTime != nil {
-		start, err := startTime.GoTime(time.UTC)
-		if err != nil {
-			return nil, percentage, totalCnt, err
-		}
-		duration := time.Now().UTC().Sub(start)
+	if startTimeUTC != nil {
+		duration := time.Now().UTC().Sub(startTimeUTC.UTC())
```
Comment (mjonss) [inline pkg/executor/infoschema_reader.go]: Why not `time.Now().Sub(startTimeUTC)` ? in Golang the time zone should not affect the actual time, only how to present it.

Comment (0xPoe) [reply pkg/executor/infoschema_reader.go]: Updated. Thank you!
