### PR TITLE
planner: fix the issue that planner hints don't work in some batch/point-get plans

### LINKED ISSUE #23570: planner: hints don't work in some batch/point get cases
## Bug Report

Please answer these questions before submitting your issue. Thanks!

## Development Task
```
CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  `d` int(11) DEFAULT NULL,
  UNIQUE KEY `abc` (`a`,`b`,`c`)
)
========================================================================
============================= the first case =================================
========================================================================
mysql> explain select * from t where a=1 and b =1 and c=1;
+-------------+---------+------+-----------------------------+---------------+
| id          | estRows | task | access object               | operator info |
+-------------+---------+------+-----------------------------+---------------+
| Point_Get_1 | 1.00    | root | table:t, index:abc(a, b, c) |               |
+-------------+---------+------+-----------------------------+---------------+

mysql> explain select * from t ignore index(abc) where a=1 and b =1 and c=1;
+-------------+---------+------+-----------------------------+---------------+
| id          | estRows | task | access object               | operator info |
+-------------+---------+------+-----------------------------+---------------+
| Point_Get_1 | 1.00    | root | table:t, index:abc(a, b, c) |               |
+-------------+---------+------+-----------------------------+---------------+

========================================================================
============================= the second case ===============================
========================================================================
mysql> explain select * from t where a=1 and (b>=1 and b<=1) and c=1;
+-------------+---------+------+-----------------------------+---------------+
| id          | estRows | task | access object               | operator info |
+-------------+---------+------+-----------------------------+---------------+
| Point_Get_5 | 1.00    | root | table:t, index:abc(a, b, c) |               |
+-------------+---------+------+-----------------------------+---------------+
1 row in set (0.00 sec)

mysql> explain select * from t ignore index(abc) where a=1 and (b>=1 and b<=1) and c=1;
+-------------------------+---------+-----------+---------------+--------------------------------------------------------------------+
| id                      | estRows | task      | access object | operator info                                                      |
+-------------------------+---------+-----------+---------------+--------------------------------------------------------------------+
| TableReader_7           | 0.00    | root      |               | data:Selection_6                                                   |
| └─Selection_6           | 0.00    | cop[tikv] |               | eq(test.t.a, 1), eq(test.t.c, 1), ge(test.t.b, 1), le(test.t.b, 1) |
|   └─TableFullScan_5     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo                                     |
+-------------------------+---------+-----------+---------------+--------------------------------------------------------------------+
3 rows in set (0.00 sec)
```
As you see above, the `ignore hint` doesn't work in the first case but can control the second.

### 2. What did you expect to see? (Required)
Both cases can be controlled by the hint.

### 3. What did you see instead (Required)
Only the second case can.

### 4. What is your TiDB version? (Required)
`5.7.25-TiDB-v4.0.0-beta.2-2438-g906828b15-dirty`

### 5. Root cause  analysis
The root cause is that TiDB handles `point/batch get` plans in two places.
The first is in `TryFastPlan` which is in front of logical optimization, so all `point/batch get` plans handled in this place cannot be controlled by hints.
The second is in `DataSource.convertToPointGet` which is a step of physical optimization, so hints can work there.

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve?

Issue Number: close #23570 

Problem Summary: planner: fix the issue that planner hints don't work in some batch/point-get plans

### What is changed and how it works?
Add some logic about checking planner hints in `TryFastPlan`.
Please see the root cause and more details in https://github.com/pingcap/tidb/issues/23570.

### Check List 

Tests 

- Unit test

### Release note 

- planner: fix the issue that planner hints don't work in some batch/point-get plans

### CODE REVIEW

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -896,6 +897,36 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
 	return nil
 }
 
+func pkIsAvailableByHints(idxHints []*ast.IndexHint) bool {
+	return indexIsAvailableByHints(&model.IndexInfo{Name: model.NewCIStr("primary")}, idxHints)
```
Comment (winoros) [inline planner/core/point_get_plan.go:901]: Use a const var here to avoid allocating the "primary" every time?

File: planner/core/point_get_plan.go [hunk 2]
```diff
@@ -896,6 +897,36 @@ func tryPointGetPlan(ctx sessionctx.Context, selStmt *ast.SelectStmt, check bool
...
+			for _, name := range hint.IndexNames {
+				if name.L == idxInfo.Name.L {
+					return true
+				}
+			}
+		}
+	}
+	return false
+}
+
```
Comment (rebelice) [inline planner/core/point_get_plan.go:929]: There is a little problem here. If we have unique index `idx_a` and `idx_b` for `select a from t where a = 1 ignore index(idx_b)`, we can not use `point get` because `len(idxHints) != 0` and no `HintForce` `HintUse` for `idx_a`.

Comment (qw4990) [reply planner/core/point_get_plan.go:929]: Oh nice cache. I'll fix it soon.

Comment (qw4990) [reply planner/core/point_get_plan.go]: updated

**Review by winoros — APPROVED** [review]
