### PR TITLE
BR: support detect unrecognized pattern

### LINKED ISSUE #67016: br: old br:v8.5.5 restore silently loses merge_option attributes from new backup
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This issue happens on the tool-version split:
- cluster: `v8.5.5`
- new backup tool: BR containing `#66637`
- old restore tool: `br:v8.5.5`

A minimal local Playground reproduction is:

1. Start a local cluster:
   ```bash
   tiup playground v8.5.5 --db 1 --pd 1 --kv 1 --tiflash 0 --without-monitor
   ```
2. Create a normal table with `merge_option=allow`:
   ```sql
   create database compat66637;
   create table compat66637.t_normal (a int primary key, b varchar(100));
   insert into compat66637.t_normal values (1,'test1'),(2,'test2'),(3,'test3');
   alter table compat66637.t_normal attributes='merge_option=allow';
   ```
3. Verify before backup:
   ```sql
   select id, type, attributes
   from information_schema.attributes
   where db_name='compat66637' and table_name='t_normal';
   ```
   The attribute is present before backup.
4. Use a new BR that already contains `#66637` to run backup.
5. Decode or inspect the backup metadata and confirm it contains the new field:
   - `is_merge_option_allowed: true`
6. Restore the backup with old `br:v8.5.5`:
   ```bash
   tiup br:v8.5.5 restore full -s local:///tmp/compat66637-repro/normal_backup --pd 127.0.0.1:18379
   ```
7. Check after restore:
   ```sql
   select count(*) from compat66637.t_normal;
   select id, type, attributes
   from information_schema.attributes
   where db_name='compat66637' and table_name='t_normal';
   ```

The same problem can also be reproduced on a partitioned table where:
- table-level attribute is `merge_option=allow`
- partition-level attribute is `merge_option=deny`

### 2. What did you expect to see? (Required)

I expected that if the new backup artifact already carries the `merge_option` metadata, then restore should preserve those attributes.

Concretely:
- restore should succeed
- row counts should remain correct
- `information_schema.attributes` should still show the same `merge_option` attributes after restore

### 3. What did you see instead (Required)

Old `br:v8.5.5` restore succeeded and data was restored correctly, but the `merge_option` attributes were silently lost.

For the normal table case:
- row count after restore stayed `3`
- but `information_schema.attributes` became empty for that table

For the partition table case:
- row count after restore stayed `2`
- but both table-level and partition-level attributes disappeared

A control restore of the same backup with the new BR preserved the attributes, so the backup artifact itself is correct. The loss happens on the old restore path.

### 4. What is your TiDB version? (Required)

Cluster version:
```text
Release Version: v8.5.5
```

### Additional context

This is not simply an old feature limitation.

`merge_option` attributes can already exist on a `v8.5.5` cluster. The compatibility bug is that a new BR backup artifact really contains the metadata, but an old `br:v8.5.5` restore tool still drops it silently.

This is a tool-version compatibility issue in the restore path: restore appears successful, but metadata semantics are incomplete afterward.

The reproduction was validated locally with Playground. The new backup tool was a BR built from `origin/release-8.5` at `0d5390c1de`, which contains commit `8f1e9a98f9` / PR `#66637`. A detailed local report artifact is available on my side if needed.

### PR DESCRIPTION
**Pull request by JoyC-dev**
### What problem does this PR solve?

Issue Number: close #67016 

Problem Summary:

### What changed and how does it work?
Add backup_version and unrecognized_meta_data feedback. 
Applied these data to --check-requirements, now backup can have ability to control meta-data changes.
### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
BR: support detect unrecognized pattern
```

## Summary by CodeRabbit

* **New Features**
  * Restore now validates backup metadata compatibility (schema version and unknown protobuf fields) before proceeding; strictness is configurable (error vs. warn). New backups record the current backup schema version.

* **Tests**
  * Added and strengthened tests for schema-version enforcement, unknown-field detection, and rejection of newer-schema backups in restore and log-client flows.

* **Chores**
  * Updated dependency pins and test build settings to include updated protobuf sources.

### CODE REVIEW

File: br/pkg/metautil/metafile.go [hunk 1]
```diff
@@ -58,6 +58,65 @@ const (
...
+		"backupmeta contains unknown protobuf fields. restoring with an older BR may silently ignore "+
+			"newer backup metadata. backup cluster version: %s, backup BR version: %s. use "+
+			"--check-requirements=false to skip this check",
+		backupMeta.GetClusterVersion(),
+		backupMeta.GetBrVersion(),
+	)
+	if checkRequirements {
+		return err
+	}
+	log.Warn(err.Error())
```
Comment (YuJuncen) [inline br/pkg/metautil/metafile.go]: Don't directly log error. Use `logutil.ShortError(err)`.

File: br/pkg/metautil/metafile.go [hunk 2]
```diff
@@ -58,6 +58,65 @@ const (
...
+	return nil
+}
```
Comment (YuJuncen) [inline br/pkg/metautil/metafile.go]: Consider move this to call side.

File: br/pkg/metautil/metafile.go [hunk 3]
```diff
@@ -58,6 +58,65 @@ const (
...
+			CurrentBackupSchemaVersion,
+			backupMeta.GetClusterVersion(),
+			backupMeta.GetBrVersion(),
+		)
+		if checkRequirements {
+			return err
+		}
+		log.Warn(err.Error())
+		return nil
+	}
```
Comment (YuJuncen) [inline br/pkg/metautil/metafile.go]: Ditto

File: br/pkg/task/restore_test.go [hunk 4]
```diff
@@ -248,6 +248,85 @@ func TestCheckNewCollationEnable(t *testing.T) {
...
+				err := task.CheckBackupMetaCompatibility(ca.backupMeta, ca.checkRequirements)
+				if ca.isErr {
+					require.Error(t, err)
+					require.Contains(t, err.Error(), ca.expectedErr)
+					return
+				}
+				require.NoError(t, err)
+			})
+		}
+	})
```
Comment (YuJuncen) [inline br/pkg/task/restore_test.go]: It seems replicated with the one in `metafile_test`

File: br/pkg/metautil/metafile.go [hunk 5]
```diff
@@ -58,6 +58,65 @@ const (
 	MetaV2
 )
 
+const (
+	// CurrentBackupSchemaVersion is the newest backup metadata compatibility
+	// version this BR binary knows how to read. Version 0 is reserved for
+	// backups created before the field existed.
+	CurrentBackupSchemaVersion uint32 = 1
```
Comment (YuJuncen) [inline br/pkg/metautil/metafile.go]: Better to read this from kvproto package.

File: br/pkg/task/restore.go [hunk 6]
```diff
@@ -816,6 +817,25 @@ func CheckNewCollationEnable(
...
 }
 
+// CheckBackupMetaUnknownFields blocks restore when backup metadata contains
+// protobuf fields the current BR binary does not recognize.
+func CheckBackupMetaUnknownFields(
+	backupMeta *backuppb.BackupMeta,
+	checkRequirements bool,
+) error {
+	return metautil.CheckBackupMetaUnknownFields(backupMeta, checkRequirements)
+}
```
Comment (YuJuncen) [inline br/pkg/task/restore.go]: Remove this trivial wrapper.

File: br/pkg/task/restore.go [hunk 7]
```diff
@@ -816,6 +817,25 @@ func CheckNewCollationEnable(
...
+
+// CheckBackupMetaCompatibility blocks restore when backup metadata requires a
+// newer metadata schema reader or contains protobuf fields the current BR
+// binary does not recognize.
+func CheckBackupMetaCompatibility(
+	backupMeta *backuppb.BackupMeta,
+	checkRequirements bool,
+) error {
+	return metautil.CheckBackupMetaCompatibility(backupMeta, checkRequirements)
+}
```
Comment (YuJuncen) [inline br/pkg/task/restore.go]: And this.

File: br/pkg/task/stream.go [hunk 8]
```diff
@@ -1820,6 +1820,7 @@ func createLogClient(ctx context.Context, g glue.Glue, cfg *RestoreConfig, mgr *
 	keepaliveCfg := GetKeepalive(&cfg.Config)
 	keepaliveCfg.PermitWithoutStream = true
 	client := logclient.NewLogClient(mgr.GetPDClient(), mgr.GetPDHTTPClient(), mgr.GetTLSConfig(), keepaliveCfg)
+	client.SetCheckRequirements(cfg.CheckRequirements)
```
Comment (YuJuncen) [inline br/pkg/task/stream.go:1823]: in `br/pkg/task/stream.go#L1336-L1353` and `br/pkg/task/stream.go#L1935-L2022`.

During stream restore preflight, the code reads the log/full backup `BackupMeta` and directly uses `StartVersion` and `ClusterId` to derive `cfg.RestoreTS`, `cfg.StartTS`, and cluster/range validation. However, these paths never call `CheckBackupMetaCompatibility`.

As a result, although `--check-requirements` was introduced for this purpose, it is ineffective on these paths. If a newer `backupmeta` format is encountered, an older BR may still use its values to plan the restore while silently ignoring newer semantics. This is the primary risk.

File: br/pkg/metautil/metafile.go [hunk 9]
```diff
@@ -58,6 +58,65 @@ const (
...
+)
+
+// CheckBackupMetaUnknownFields blocks restore when backup metadata contains
+// protobuf fields the current BR binary does not recognize.
+func CheckBackupMetaUnknownFields(
+	backupMeta *backuppb.BackupMeta,
+	checkRequirements bool,
+) error {
+	if backupMeta == nil || len(backupMeta.XXX_unrecognized) == 0 {
```
Comment (YuJuncen) [inline br/pkg/metautil/metafile.go]: The new “reject unknown protobuf fields” logic only checks unknown fields on the top-level `BackupMeta`. It does not cover unknown fields inside nested messages. So the protection exists, but is not fully comprehensive.

**Review by YuJuncen — COMMENTED** [review]
Some comments from agent, rest lgtm

File: br/pkg/task/stream.go (hunk 8 above)
Comment (JoyC-dev) [reply br/pkg/task/stream.go:1823]: Updated.

File: br/pkg/metautil/metafile.go (hunk 9 above)
Comment (JoyC-dev) [reply br/pkg/metautil/metafile.go]: Yes, XXX_unrecognized only detect the top-level, that's why we involve the backupSchemeVersion.

Comment (YuJuncen) [reply br/pkg/metautil/metafile.go]: I mean, you may need to recursively check it or just don't check it as we have backupSchemeVersion?

Comment (JoyC-dev) [reply br/pkg/metautil/metafile.go]: Using backupSchemaVersion is enough. XXX_unrecognized is helpful for top-level meta (partial protection). first edition solely depends backup version, but after discussing in group meeting, top-level protection and version control both are required......
