### PR TITLE
planner: preserve outer refs in window subqueries

### LINKED ISSUE #56532: subquery in window function cannot reference column outside, while mysql can
## Bug Report

When using subquery in window function, the subselect cannot reference columns of outer query.
When using window function in `coalesce`, the subquery outside window function cannot reference columns of outer query too.

### 1. Minimal reproduce step (Required)
```sql
create table t1 (c1 int primary key);
create table t2 (c1 int primary key, c2 text);

select 
  count((select ref_1.c2 from t1 limit 1)) 
from t2 as ref_1
group by ref_1.c1;

select 
  count((select ref_1.c2 from t1 limit 1)) over (partition by ref_1.c1)
from t2 as ref_1;

select 
coalesce(
    count(*) over (partition by ref_1.c1), 
    (select ref_1.c2 from t1)
)
from t2 as ref_1;
```

### 2. What did you expect to see? (Required)
In MySQL:
```
mysql> create table t1 (c1 int primary key);
Query OK, 0 rows affected (0.01 sec)

mysql> create table t2 (c1 int primary key, c2 text);
Query OK, 0 rows affected (0.02 sec)

mysql> select 
    -> count((select ref_1.c2 from t1 limit 1)) 
    -> from t2 as ref_1
    -> group by ref_1.c1;
Empty set (0.00 sec)

mysql> select 
    -> count((select ref_1.c2 from t1 limit 1)) over (partition by ref_1.c1)
    -> from t2 as ref_1;
Empty set (0.00 sec)

mysql> select 
    -> coalesce(
    ->     count(*) over (partition by ref_1.c1), 
    ->     (select ref_1.c2 from t1)
    -> )
    -> from t2 as ref_1;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)
In TiDB:
```
tidb> create table t1 (c1 int primary key);
Query OK, 0 rows affected (0.14 sec)

tidb> create table t2 (c1 int primary key, c2 text);
Query OK, 0 rows affected (0.17 sec)

tidb> select 
    -> count((select ref_1.c2 from t1 limit 1)) 
    -> from t2 as ref_1
    -> group by ref_1.c1;
Empty set (0.01 sec)

tidb> select 
    -> count((select ref_1.c2 from t1 limit 1)) over (partition by ref_1.c1)
    -> from t2 as ref_1;
ERROR 1054 (42S22): Unknown column 'ref_1.c2' in 'field list'

tidb> select 
    -> coalesce(
    ->     count(*) over (partition by ref_1.c1), 
    ->     (select ref_1.c2 from t1)
    -> )
    -> from t2 as ref_1;
ERROR 1054 (42S22): Unknown column 'ref_1.c2' in 'field list'

```
### 4. What is your TiDB version? (Required)
8.1.0 and latest nightly version

### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in TiDB that may lead to database logic error.

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #56532

Problem Summary:

Window function expressions and peer expressions that contain correlated scalar subqueries can lose access to outer columns during the deferred window rewrite path. This makes queries that work in MySQL fail in TiDB with unknown-column errors.

Review also found that the auxiliary-field collection path could rewrite non-scalar subqueries inside window expressions through the scalar-subquery path, incorrectly introducing `MaxOneRow` for valid `IN` / `ANY` cases.

### What changed and how does it work?

- collect outer columns referenced by subqueries inside window expressions, window specs, and related ORDER BY items, and append them as auxiliary fields before window planning
- keep Apply-produced columns in the projection built for window arguments so ResolveIndices still finds them after pruning
- preserve `EXISTS`, `IN`, and quantified subquery expressions as complete expressions during auxiliary-field extraction so non-scalar subqueries do not get rewritten as scalar subqueries
- extend the window casetests with a regression that exercises multi-row non-scalar subqueries inside window expressions, and add deferred cleanup for the existing table-based regression

### Check List

Tests 

- [x] Unit test
  - `make failpoint-enable`
  - `go test -run 'TestWindowWithCorrelatedSubQuery|TestWindowSubqueryOuterRef|TestWindowNonScalarSubqueryInWindowExpr' -tags=intest,deadlock ./pkg/planner/core/casetest/windows`
  - `make failpoint-disable`
  - `make lint`
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [x] Changes MySQL compatibility

### Release note

```release-note
Fix queries with correlated and non-scalar subqueries inside window expressions that incorrectly report unknown-column or subquery cardinality errors.
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved correctness of window-function resolution and rewrites for correlated and non-scalar subqueries, fixing cases involving outer-referenced subqueries.

* **Tests**
  * Added extensive test suites covering window functions with correlated/non-scalar subqueries and outer references (multiple new cases).

* **Documentation**
  * Added planner notes documenting deferred window rewrite and subquery handling.

* **Chores**
  * Increased test parallelism for window tests.

### CODE REVIEW

File: pkg/planner/core/logical_plan_builder.go [hunk 1]
```diff
@@ -2536,6 +2525,105 @@ func (b *PlanBuilder) resolveHavingAndOrderBy(ctx context.Context, sel *ast.Sele
...
+	switch subq := n.(type) {
+	case *ast.SubqueryExpr:
+		e.exprs = append(e.exprs, subq)
+		return n, true
+	case *ast.ExistsSubqueryExpr:
+		e.exprs = append(e.exprs, subq)
+		return n, true
+	case *ast.CompareSubqueryExpr:
+		e.exprs = append(e.exprs, subq)
+		return n, true
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go:2543]: can we merge these 3 case togther?

File: pkg/planner/core/logical_plan_builder.go [hunk 2]
```diff
@@ -2536,6 +2525,105 @@ func (b *PlanBuilder) resolveHavingAndOrderBy(ctx context.Context, sel *ast.Sele
...
+		extractor := &subqueryExprExtractor{}
+		node.Accept(extractor)
+		for _, expr := range extractor.exprs {
+			// Correlated aggregates are handled separately; here we only need the outer columns
+			// so subqueries inside deferred window expressions can still resolve against this query block.
+			_, np, err := b.rewrite(ctx, expr, p, nil, true)
+			if err != nil {
+				return nil, errors.Trace(err)
+			}
+			correlatedCols := coreusage.ExtractCorrelatedCols4LogicalPlan(np)
```
Comment (AilinKid) [inline pkg/planner/core/logical_plan_builder.go:2609]: currently the pre-build phase is just for detecting and preparing the ast.Field, while this expression built this time is no considered and reused later, it's a kind of waste, we can add a todo here, for other database, analyzing phase is always lightweight.

**Review by AilinKid — COMMENTED** [review]
rest LGTM

File: pkg/planner/core/logical_plan_builder.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go:2543]: This probably won't work; you'll need to write a SetExpr function.

File: pkg/planner/core/logical_plan_builder.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/planner/core/logical_plan_builder.go:2609]: I have added.

File: docs/note/planner/window_subquery_notes.md [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+  - correlated scalar subqueries inside window expressions,
+  - `EXISTS` subqueries,
+  - redundant `USING` / `NATURAL JOIN` outer-column lookup through `FullSchema`.
+- `TestWindowNonScalarSubqueryInWindowExpr` adds direct coverage for valid multi-row non-scalar subqueries inside window expressions:
+  - `count(1 in (select t2.c1 from t2)) over ()`
+  - `count(1 = any (select t2.c1 from t2)) over ()`
+
+Validation commands:
+- `make failpoint-enable`
+- `go test -run 'TestWindowWithCorrelatedSubQuery|TestWindowSubqueryOuterRef|TestWindowNonScalarSubqueryInWindowExpr' -tags=intest,deadlock ./pkg/planner/core/casetest/windows`
```
[the remark this answers is not in the document]
Comment (hawkingrei) [reply docs/note/planner/window_subquery_notes.md]: Good catch. The note was still using the old test names after I merged the hand-written regressions into `TestWindowSubqueryRewrite`.

Updated `docs/note/planner/window_subquery_notes.md` to keep the documented coverage and validation command aligned with the current package tests:
- `TestWindowSubqueryRewrite`
- `TestWindowSubqueryOuterRef`

The command is now:
`go test -run 'TestWindowSubqueryRewrite|TestWindowSubqueryOuterRef' -tags=intest,deadlock ./pkg/planner/core/casetest/windows`

Fixed in commit e4799aa586.
