### PR TITLE
types, expression: fix gotime.local problem

### LINKED ISSUE #13626: Potential timezone related bugs caused by `gotime.Local` location
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
When dealing with timestamps, currently there are several pieces of codes that used `gotime.Local` as the timezone location rather than system/global/session variables, which may lead to unexpected errors:

- https://github.com/pingcap/tidb/blob/61f24d246995ceb6181da779c934c9a05438c3a9/types/mytime.go#L79

- https://github.com/pingcap/tidb/blob/61f24d246995ceb6181da779c934c9a05438c3a9/types/time.go#L433

- ...

  For example, #13605 is a bug caused by such codes, we should try to avoid using `gotime.Local` to prevent such errors. 

2. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Such codes exist in all TiDB versions.

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: close #13626 

Problem Summary:
Remove usages of gotime.local

### Check List 

Tests 

- No code

Side effects

### Release note 

- No release note

### CODE REVIEW

**Review by AilinKid — APPROVED** [review]
LGTM

File: types/time.go [hunk 1]
```diff
@@ -1765,7 +1771,7 @@ func ParseDuration(sc *stmtctx.StatementContext, str string, fsp int8) (Duration
 		return ZeroDuration, ErrTruncatedWrongVal.GenWithStackByArgs("time", str)
 	}
 
-	return d.RoundFrac(fsp)
+	return d.RoundFrac(fsp, sc.TimeZone)
```
Comment (AilinKid) [inline types/time.go:1774]: `sc` may be nil for some test case

Comment (bb7133) [reply types/time.go:1774]: So I think it's better to fix `nil` for the test cases.

Comment (wjhuang2016) [reply types/time.go:1774]: OK, I think I need to fix the test.

**Review by wshwsh12 — COMMENTED** [review]
Please fix CI..
And do we need port the change to TiKV/TiFlash?

**Comment by wjhuang2016** [comment]
> Please fix CI..
> And do we need port the change to TiKV/TiFlash?

I not sure if tikv or tiflash have this problem

File: expression/builtin_cast.go [hunk 2]
```diff
@@ -1438,7 +1438,7 @@ func (b *builtinCastTimeAsDurationSig) evalDuration(row chunk.Row) (res types.Du
 	if err != nil {
 		return res, false, err
 	}
-	res, err = res.RoundFrac(int8(b.tp.Decimal))
+	res, err = res.RoundFrac(int8(b.tp.Decimal), b.ctx.GetSessionVars().TimeZone)
```
Comment (morgo) [inline expression/builtin_cast.go:1441]: It might be possible that `GetSessionVars().TimeZone` is not set if this is used by internal sql. See: https://github.com/pingcap/tidb/issues/25700 for a similar bug.

Is it possible to use Location()

**Review by morgo — APPROVED** [review]
