### PR TITLE
variable: change tidb_redact_log to global variable

### LINKED ISSUE #62890: variable: session variable tidb_redact_log will set global error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/55cf58bf1681fe1d584e95cede4fa49c7197682a/pkg/sessionctx/variable/sysvar.go#L2542-L2546

### 2. What did you expect to see? (Required)

Should be global only

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve?

Issue Number: close #62890

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
change global/session variable tidb_redact_log to global variable
```

### CODE REVIEW

File: tests/realtikvtest/addindextest2/global_sort_test.go [hunk 1]
```diff
@@ -404,12 +404,10 @@ func TestGlobalSortDuplicateErrMsg(t *testing.T) {
 	}
 
 	checkRedactMsgAndReset := func(addUniqueKeySQL string) {
-		tk.MustExec("set session tidb_redact_log = on;")
 		// tidb_redact_log is actually a instance variable. We should avoid other sessions overwriting it.
```
Comment (tangenta) [inline tests/realtikvtest/addindextest2/global_sort_test.go]:
```suggestion
```

**Comment by lance6716** [comment]
/lgtm

I also update the "Documentation" section of PR description. Please also check document.

File: pkg/expression/exprstatic/evalctx.go [hunk 2]
```diff
@@ -465,6 +466,11 @@ func newSessionVarsWithSystemVariables(vars map[string]string) (*variable.Sessio
 			cs = []string{name, val}
 		case vardef.CollationConnection:
 			col = []string{name, val}
+		case vardef.TiDBRedactLog:
```
Comment (XuHuaiyu) [inline pkg/expression/exprstatic/evalctx.go:469]: why add this check？

**Review by bb7133 — APPROVED** [review]
LGTM

**Review by yudongusa — APPROVED** [review]

File: pkg/expression/exprstatic/evalctx.go (hunk 2 above)
Comment (xhebox) [reply pkg/expression/exprstatic/evalctx.go:469]: It became a global variable which can not be set by `SetSystemVar` or `set @@tidb_redact_log=xx`.
