### PR TITLE
br: remove evict slow store scheduler

### LINKED ISSUE #50566: one tikv has no leader and slow down br restore speed
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. use br to restore a full backup of 30TB 500k table cluster to a 20 TiKV nodes new cluster.
```
/br  restore  full "-s" "gcs://aaa/bbb-500k-table-30tb-backup-with-stats-3" "-u" "http://tc-pd:2379" "--check-requirements=false" "--ddl-batch-size=128" "--tikv-max-restore-concurrency=128" "--granularity=coarse-grained" "--send-credentials-to-tikv=true" "--checksum=false"
```

### 2. What did you expect to see? (Required)
all tikv should have restore tasks.

### 3. What did you see instead (Required)
One TiKV has no leader, and slow down the br restore speed.

image

### 4. What is your TiDB version? (Required)

[root@br-0 tmp]# /br -V
Release Version: v7.6.0-pr50518
Git Commit Hash: https://github.com/pingcap/tidb/commit/4888198abe9f8de0081975aa498f6b970833305a
Git Branch: heads/refs/tags/v7.6.0-pr50518
Go Version: go1.21.5
UTC Build Time: 2024-01-18 02:50:49
Race Enabled: false

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve?

Issue Number: close #50566 

Problem Summary:
one tikv has no leader and slow down br restore spee
### What changed and how does it work?
remove `evict-slow-store-scheduler` when restore
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

image

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: br/pkg/pdutil/pd.go [hunk 1]
```diff
@@ -95,6 +95,8 @@ var (
 		"shuffle-leader-scheduler":     {},
 		"shuffle-region-scheduler":     {},
 		"shuffle-hot-region-scheduler": {},
+
+		"evict-slow-store-scheduler": {},
```
Comment (3pointer) [inline br/pkg/pdutil/pd.go:99]: LGTM, but what if PD add new scheduler in future?

**Review by 3pointer — APPROVED** [review]

File: br/pkg/pdutil/pd.go (hunk 1 above)
Comment (Leavrth) [reply br/pkg/pdutil/pd.go:99]: PD hasn't the list of all the scheduler.

**Review by YuJuncen — APPROVED** [review]
