### PR TITLE
ddl: constraint name uniquness is enforced for check constraints

### LINKED ISSUE #48038: Constraint name uniqueness is not enforced for check constraints
## Bug Report

Not enforcing the same name uniqueness as MySQL might cause issues with compatibility leading to migration and/or replication (TiCDC) issues.

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50));
CREATE TABLE t2 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50));
```

### 2. What did you expect to see? (Required)

On MySQL 8.2.0:
```
sql> CREATE TABLE t1 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50));
Query OK, 0 rows affected (0.0505 sec)

sql> CREATE TABLE t2 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50));
ERROR: 3822 (HY000): Duplicate check constraint name 'c1'.
```

### 3. What did you see instead (Required)

On TiDB:
```
sql> SET GLOBAL tidb_enable_check_constraint=ON;
Query OK, 0 rows affected (0.0080 sec)

sql> CREATE TABLE t1 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50));
Query OK, 0 rows affected (0.0254 sec)

sql> CREATE TABLE t2 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50));
Query OK, 0 rows affected (0.0182 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v7.6.0-alpha-23-gdfd9080bcf-dirty
Edition: Community
Git Commit Hash: dfd9080bcf49083e52d6cb714668da9b881dc54d
Git Branch: master
UTC Build Time: 2023-10-27 06:35:10
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore
1 row in set (0.0009 sec)
```

### PR DESCRIPTION
**Pull request by highpon**
### What problem does this PR solve?

Issue Number: close #48038

Problem Summary:
Currently, when `tidb_enable_check_constraint` is ON, the uniqueness of constraint names is not enforced by the check constraint when creating a table creation. This PR fixes this problem and enforces check constraints.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  >   

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/ddl/db_table_test.go [hunk 1]
```diff
@@ -858,3 +858,18 @@ func TestDropTables(t *testing.T) {
...
+	tk := testkit.NewTestKit(t, store)
+
+	tk.MustExec("use test")
+	tk.MustExec("DROP TABLE IF EXISTS t1, t2")
+	tk.MustExec("set @@global.tidb_enable_check_constraint = 1")
+	tk.MustExec("CREATE TABLE t1 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50))")
+	failedSQL := "CREATE TABLE t2 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50))"
+	tk.MustGetErrCode(failedSQL, errno.ErrCheckConstraintDupName)
+
+	defer tk.MustExec("DROP TABLE IF EXISTS t1, t2")
```
[the remark this answers is not in the document]
Comment (highpon) [reply pkg/ddl/db_table_test.go]: fix: https://github.com/pingcap/tidb/pull/48062/commits/e906e3d4d367e2191ed0ccd27b78989c24259edc

File: pkg/ddl/db_table_test.go [hunk 2]
```diff
@@ -858,3 +858,18 @@ func TestDropTables(t *testing.T) {
...
+
+	tk := testkit.NewTestKit(t, store)
+
+	tk.MustExec("use test")
+	tk.MustExec("DROP TABLE IF EXISTS t1, t2")
+	tk.MustExec("set @@global.tidb_enable_check_constraint = 1")
+	tk.MustExec("CREATE TABLE t1 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50))")
+	failedSQL := "CREATE TABLE t2 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50))"
+	tk.MustGetErrCode(failedSQL, errno.ErrCheckConstraintDupName)
+
```
[the remark this answers is not in the document]
Comment (highpon) [reply pkg/ddl/db_table_test.go:873]: fix: https://github.com/pingcap/tidb/pull/48062/commits/e906e3d4d367e2191ed0ccd27b78989c24259edc#diff-be978de198efe73429f122352ae60ee3a4bb7737f32dc1fb0f74b5a0b300f23bR878-R883

File: pkg/ddl/db_table_test.go [hunk 3]
```diff
@@ -858,3 +858,18 @@ func TestDropTables(t *testing.T) {
...
+	store := testkit.CreateMockStore(t, mockstore.WithDDLChecker())
+
+	tk := testkit.NewTestKit(t, store)
+
+	tk.MustExec("use test")
+	tk.MustExec("DROP TABLE IF EXISTS t1, t2")
+	tk.MustExec("set @@global.tidb_enable_check_constraint = 1")
+	tk.MustExec("CREATE TABLE t1 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50))")
+	failedSQL := "CREATE TABLE t2 (id INT PRIMARY KEY, CONSTRAINT c1 CHECK (id<50))"
+	tk.MustGetErrCode(failedSQL, errno.ErrCheckConstraintDupName)
```
[the remark this answers is not in the document]
Comment (highpon) [reply pkg/ddl/db_table_test.go:872]: fix: https://github.com/pingcap/tidb/pull/48062/commits/a55f7078f7cc21f0bf9f9f7b276a7ab910676275, https://github.com/pingcap/tidb/pull/48062/commits/e906e3d4d367e2191ed0ccd27b78989c24259edc

**Comment by highpon** [comment]
@mjonss 
Thanks for you review!
I have corrected your point. Please re-review this PR.

File: pkg/ddl/table.go [hunk 4]
```diff
@@ -1476,6 +1485,23 @@ func checkTableNotExists(d *ddlCtx, t *meta.Meta, schemaID int64, tableName stri
 	return checkTableNotExistsFromStore(t, schemaID, tableName)
 }
 
+func checkConstraintNamesNotExists(t *meta.Meta, schemaID int64, constrains []*model.ConstraintInfo) error {
+	tbInfos, err := t.ListTables(schemaID)
```
Comment (mjonss) [inline pkg/ddl/table.go:1489]: Please do an early check and return nil `if len(contraints) == 0`. Otherwise this will loop over all tables in the schema for every CREATE TABLE even if there are no constraints.
Also notice the typo `constrains` -> `constraints` with a `t`.
```suggestion
	if len(constraints) == 0 {
		return nil
	}
	tbInfos, err := t.ListTables(schemaID)
```

File: pkg/ddl/constraint.go [hunk 5]
```diff
@@ -139,6 +139,21 @@ func checkAddCheckConstraint(t *meta.Meta, job *model.Job) (*model.DBInfo, *mode
...
+
+	for _, tbl := range tblInfos {
+		if tbl.ID != tblInfo.ID {
+			if constraintInfo := tbl.FindConstraintInfoByName(constraintInfo1.Name.L); constraintInfo != nil {
+				job.State = model.JobStateCancelled
+				return nil, nil, nil, nil, infoschema.ErrCheckConstraintDupName.GenWithStackByArgs(constraintInfo1.Name.L)
+			}
+		}
+	}
+
```
Comment (mjonss) [inline pkg/ddl/constraint.go:156]: Can we use `checkConstraintNamesNotExists` instead?
```suggestion

	err = checkConstraintNamesNotExists(t, schemaID, []*model.ConstraintInfo{constraintInfo1})
	if err != nil {
		job.State = model.JobStateCancelled
		return nil, nil, nil, nil, err
	}

```

**Review by mjonss — COMMENTED** [review]
LGTM, with some minor suggestions. Please consider the early return in `checkConstraintNamesNotExists` to not cause unnecessary performance degradations in create table without constraints.

File: pkg/ddl/table.go (hunk 4 above)
Comment (highpon) [reply pkg/ddl/table.go:1492]: fix: https://github.com/pingcap/tidb/pull/48062/commits/5f9ffa4fba5a6e56b891f9cfa70fe8117167e221

File: pkg/ddl/constraint.go (hunk 5 above)
Comment (highpon) [reply pkg/ddl/constraint.go]: fix: https://github.com/pingcap/tidb/pull/48062/commits/f4720bb7dc4c089a18d36235dcccd5577b5b8e12

**Comment by highpon** [comment]
@mjonss 
Thanks for your review!
PR updated

**Comment by mjonss** [comment]
@highpon please check the unit test TestAlterConstraintAddDrop and the integration test (tests/integrationtest) ddl/constraint, they seem to fail in CI.

**Comment by highpon** [comment]
@mjonss 
Thanks for you review.
PR updated to pass CI.

**Review by mjonss — APPROVED** [review]

**Review by tangenta — APPROVED** [review]
