### PR TITLE
coprocessor: append bucket information in log when errors are returned in coprocess response

### LINKED ISSUE #35229: coprocessor: more log information is needed when coprocess tasks returns error
We need bucket information in logs for analyzing what's wrong in coprocess task failure.

Ex: https://github.com/tikv/tikv/issues/12784.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
Signed-off-by: SpadeA-Tang <u6748471@anu.edu.au>

### What problem does this PR solve?

Issue Number: close #35229

Problem Summary:

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: store/copr/coprocessor.go [hunk 1]
```diff
@@ -981,6 +981,8 @@ func (worker *copIteratorWorker) handleCopResponse(bo *Backoffer, rpcCtx *tikv.R
 		logutil.Logger(bo.GetCtx()).Warn("other error",
 			zap.Uint64("txnStartTS", worker.req.StartTs),
 			zap.Uint64("regionID", task.region.GetID()),
+			zap.Uint64("bucketsVer", task.bucketsVer),
+			zap.Uint64("number of ranges", uint64(task.ranges.Len())),
```
Comment (cfzjywxk) [inline store/copr/coprocessor.go:985]:
```suggestion
			zap.Int("number of ranges", task.ranges.Len()),
```

**Review by cfzjywxk — APPROVED** [review]

File: store/copr/coprocessor.go [hunk 2]
```diff
@@ -981,6 +981,8 @@ func (worker *copIteratorWorker) handleCopResponse(bo *Backoffer, rpcCtx *tikv.R
 		logutil.Logger(bo.GetCtx()).Warn("other error",
 			zap.Uint64("txnStartTS", worker.req.StartTs),
 			zap.Uint64("regionID", task.region.GetID()),
+			zap.Uint64("bucketsVer", task.bucketsVer),
```
Comment (youjiali1995) [inline store/copr/coprocessor.go:984]: Should log `resp.pbResp.GetLatestBucketsVersion()` too.

Comment (SpadeA-Tang) [reply store/copr/coprocessor.go:984]: Good catch.

File: store/copr/coprocessor.go (hunk 1 above)
Comment (SpadeA-Tang) [reply store/copr/coprocessor.go]: Good catch.

File: store/copr/coprocessor.go [hunk 3]
```diff
@@ -981,6 +981,10 @@ func (worker *copIteratorWorker) handleCopResponse(bo *Backoffer, rpcCtx *tikv.R
 		logutil.Logger(bo.GetCtx()).Warn("other error",
 			zap.Uint64("txnStartTS", worker.req.StartTs),
 			zap.Uint64("regionID", task.region.GetID()),
+			zap.Uint64("bucketsVer in request", task.bucketsVer),
+			zap.Uint64("bucketsVer in response", resp.pbResp.GetLatestBucketsVersion()),
+			zap.Int("number of ranges", task.ranges.Len()),
+			zap.String("start and end keys in ranges", task.ranges.String()),
```
Comment (youjiali1995) [inline store/copr/coprocessor.go:987]: I'm afraid it can be too long. I think log the first key and the last key of the ranges is enough, because it represents the range of the bucket.

File: store/copr/coprocessor.go [hunk 4]
```diff
@@ -981,6 +981,10 @@ func (worker *copIteratorWorker) handleCopResponse(bo *Backoffer, rpcCtx *tikv.R
 		logutil.Logger(bo.GetCtx()).Warn("other error",
 			zap.Uint64("txnStartTS", worker.req.StartTs),
 			zap.Uint64("regionID", task.region.GetID()),
+			zap.Uint64("bucketsVer in request", task.bucketsVer),
+			zap.Uint64("bucketsVer in response", resp.pbResp.GetLatestBucketsVersion()),
+			zap.Int("number of ranges", task.ranges.Len()),
```
Comment (youjiali1995) [inline store/copr/coprocessor.go:986]: It's better to follow CamelCase as other fields.
```suggestion
			zap.Uint64("bucketsVer", task.bucketsVer),
			zap.Uint64("latestBucketsVer", resp.pbResp.GetLatestBucketsVersion()),
			zap.Int("rangeNums", task.ranges.Len()),
```

File: store/copr/coprocessor.go (hunk 3 above)
Comment (SpadeA-Tang) [reply store/copr/coprocessor.go:987]: That's what I thought before. I might have to add another method for KvRange.

File: store/copr/coprocessor.go [hunk 5]
```diff
@@ -978,9 +978,19 @@ func (worker *copIteratorWorker) handleCopResponse(bo *Backoffer, rpcCtx *tikv.R
 	}
 	if otherErr := resp.pbResp.GetOtherError(); otherErr != "" {
 		err := errors.Errorf("other error: %s", otherErr)
+
+		kvRanges := task.ranges.ToPBRanges()
```
Comment (youjiali1995) [inline store/copr/coprocessor.go:982]: No need to do this. `KeyRanges` has an `At()` function which can get the first and the last key range.

Comment (SpadeA-Tang) [reply store/copr/coprocessor.go]: Okay, I have modified it.

**Review by youjiali1995 — APPROVED** [review]
