### PR TITLE
statistics: add `for update` into write to avoid inaccurate results

### LINKED ISSUE #56062: exchange partition lead to inaccurate stats_meta
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

there might be an issue with transactions updating the row count and modify_count

when we exchange partition, 

img_v3_02el_d0c39630-3a3f-45a3-807c-6aa0df7fdcbg

img_v3_02el_b8139eb2-1469-4e0c-9cf3-cd3b6a6af16g

We will read this value and then perform operations on it. However, the problem is that he forgot to use "FOR UPDATE" when reading it to lock the data. As a result, subsequent updates may corrupt the data, leading to incorrect statistical values.

In scenarios with frequent write and delete operations, this can potentially lead to significant discrepancies

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #56062

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

do concurrency delete/update operate and exchange partition. The count is right.

- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by winoros — APPROVED** [review]

File: pkg/statistics/handle/storage/read.go [hunk 1]
```diff
@@ -43,7 +43,20 @@ import (
...
+	return statsMetaCountAndModifyCount(sctx, tableID, false)
+}
+
+// StatsMetaCountAndModifyCountForUpdate reads count and modify_count for the given table from mysql.stats_meta with lock.
+func StatsMetaCountAndModifyCountForUpdate(sctx sessionctx.Context, tableID int64) (count, modifyCount int64, isNull bool, err error) {
+	return statsMetaCountAndModifyCount(sctx, tableID, false)
+}
+
+func statsMetaCountAndModifyCount(sctx sessionctx.Context, tableID int64, forUpdate bool) (count, modifyCount int64, isNull bool, err error) {
+	sql := "select count, modify_count from mysql.stats_meta where table_id = %?"
```
Comment (you06) [inline pkg/statistics/handle/storage/read.go:55]: The ` sctx.GetSessionVars().TxnMode` is empty for internal sessions(which means optimistic by default), I'm afraid the `for update` may be omitted here if we don't use `begin pessimistic`.

File: pkg/statistics/handle/storage/read.go [hunk 2]
```diff
@@ -43,7 +43,20 @@ import (
 
 // StatsMetaCountAndModifyCount reads count and modify_count for the given table from mysql.stats_meta.
 func StatsMetaCountAndModifyCount(sctx sessionctx.Context, tableID int64) (count, modifyCount int64, isNull bool, err error) {
-	rows, _, err := util.ExecRows(sctx, "select count, modify_count from mysql.stats_meta where table_id = %?", tableID)
+	return statsMetaCountAndModifyCount(sctx, tableID, false)
+}
+
+// StatsMetaCountAndModifyCountForUpdate reads count and modify_count for the given table from mysql.stats_meta with lock.
+func StatsMetaCountAndModifyCountForUpdate(sctx sessionctx.Context, tableID int64) (count, modifyCount int64, isNull bool, err error) {
```
Comment (you06) [inline pkg/statistics/handle/storage/read.go:50]: This function is unused.

File: pkg/statistics/handle/storage/read.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/statistics/handle/storage/read.go:55]: image

We use ```WrapTxn``` to start running the transaction. so it will not lead to problem.

File: pkg/statistics/handle/storage/read.go (hunk 2 above)
Comment (hawkingrei) [reply pkg/statistics/handle/storage/read.go:50]: update the code.

File: pkg/statistics/handle/storage/read.go [hunk 3]
```diff
@@ -43,7 +43,20 @@ import (
...
+	return statsMetaCountAndModifyCount(sctx, tableID, false)
```
Comment (you06) [inline pkg/statistics/handle/storage/read.go:51]:
```suggestion
	return statsMetaCountAndModifyCount(sctx, tableID, true)
```

**Review by you06 — APPROVED** [review]
