### PR TITLE
privilege: fix a null pointer error in `ConnectionVerification`

### LINKED ISSUE #42151: Null pointer error in `ConnectionVerification`
If we have a `nil` value in `UserPrivileges.Handle`, `ConnectionVerification` would panic.

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What problem does this PR solve?

Issue Number: close #42151

Problem Summary:

If we enable `SkipGrantTable`, `ConnectionVerification` should return directly.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
Fix a `nil` pointer error in ConnectionVerification
```

### CODE REVIEW

File: privilege/privileges/privileges_test.go [hunk 1]
```diff
@@ -3202,3 +3202,11 @@ func TestVerificationInfoWithSessionTokenPlugin(t *testing.T) {
 	err = tk.Session().Auth(user, nil, nil)
 	require.ErrorContains(t, err, "Access denied")
 }
+
+func TestNilHandleInConnectionVerification(t *testing.T) {
+	config.GetGlobalConfig().Security.SkipGrantTable = true
```
Comment (lance6716) [inline privilege/privileges/privileges_test.go:3207]: Should reset it after the test is finished? like

```
defer config.RestoreFunc()()
	config.UpdateGlobal(func(conf *config.Config) {
		conf.Security.SkipGrantTable = true
	})
```

**Review by lance6716 — APPROVED** [review]

**Review by hawkingrei — APPROVED** [review]
