### PR TITLE
planner: fix should not use point get plan

### LINKED ISSUE #21123: planner: Point get plan will cause wrong result set
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (id varchar(20) primary key);
insert into t values ('asdf'), ('1');

mysql> select * from t where id in (0, 1);
+----+
| id |
+----+
| 1  |
+----+
1 row in set (0.00 sec)

mysql> select * from t where id = 0;
Empty set (0.00 sec)
```

### 2. What did you expect to see? (Required)

```
create table t (id varchar(20) primary key);
insert into t values ('asdf'), ('1');

mysql> select * from t where id in (0, 1);
+------+
| id   |
+------+
| 1    |
| asdf |
+------+
2 rows in set, 1 warning (0.00 sec)

mysql> select * from t where id = 0;
+------+
| id   |
+------+
| asdf |
+------+
1 row in set, 1 warning (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1585-ga426a0e5f
Edition: Community
Git Commit Hash: a426a0e5ff45300bed9b7e569d2004c3401ec401
Git Branch: master
UTC Build Time: 2020-11-18 12:10:17
GoVersion: go1.15.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### LINKED ISSUE #21204: planner: Point get plan will cause wrong result set
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Related issue: https://github.com/pingcap/tidb/issues/21123

```sql
create table t (id bit(64) primary key);
insert into t values (48);
```

### 2. What did you expect to see? (Required)

```sql
test> select * from t where id in ('0');
+----+
| id |
+----+
0 rows in set
```

### 3. What did you see instead (Required)

```sql
test> select * from t where id  in ('0');
+----------+
| id       |
+----------+
| 0 |
+----------+
1 row in set. 
```

### 4. What is your TiDB version? (Required)

```sql
test> select tidb_version();
+-------------------------------------------------------------------+
| tidb_version()                                                    |
+-------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1609-gb085cad80                    |
| Edition: Community                                                |
| Git Commit Hash: b085cad80c3196beb470718d38594a161be3bae8         |
| Git Branch: master                                                |
| UTC Build Time: 2020-11-23 06:53:25                               |
| GoVersion: go1.14.4                                               |
| Race Enabled: false                                               |
| TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306 |
| Check Table Before Drop: false                                    |
+-------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #21123 , close #21204

Problem Summary:

In MySQL string convert to numbers it will use number prefix to convert to number, for example:

```
'asdf' => 0
'123asdf' => 123
```

So if we create a table like `create table t (id varchar(10) primary key)`, then insert ('asdf'), ('1asdf') into this table. When we execute a query like:
```
select * from t where id = 0;
```

the plan should be convert column id into int and compare with number 0, so we should get 'asdf' as the result. But in TiDB it will convert number 0 to string '0' and use point get plan to fetch `id = '0'` rows, so we will get an empty set result.

### What is changed and how it works?

What's Changed:

Add type check for TryFastPlan, if column type is string like and `in` or `=` value is number just return empty plan.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

- planner: fix wrong point get plan generation in fast plan code path

### CODE REVIEW

File: planner/core/point_get_plan.go [hunk 1]
```diff
@@ -1039,6 +1066,22 @@ func getNameValuePairs(stmtCtx *stmtctx.StatementContext, tbl *model.TableInfo,
 	return nil, false
 }
 
+func checkCanUseConvertTo(col *model.ColumnInfo, d types.Datum) bool {
```
Comment (wjhuang2016) [inline planner/core/point_get_plan.go:1069]: I think checkCanConvertInPointGet would be more clear.

File: planner/core/point_get_plan.go [hunk 2]
```diff
@@ -1039,6 +1066,22 @@ func getNameValuePairs(stmtCtx *stmtctx.StatementContext, tbl *model.TableInfo,
...
+	dKind := d.Kind()
+	switch col.FieldType.EvalType() {
+	case ptypes.ETString:
+		switch dKind {
```
Comment (wjhuang2016) [inline planner/core/point_get_plan.go:1073]: Should we use the white list?

Comment (blacktear23) [reply planner/core/point_get_plan.go:1073]: For now I just find String type column with numeric constant will cause the bug. So I just use black list style.

File: planner/core/point_get_plan_test.go [hunk 3]
```diff
@@ -562,3 +562,55 @@ func (s *testPointGetSuite) TestBatchPointGetWithInvisibleIndex(c *C) {
...
+func (s *testPointGetSuite) TestShouldNotUsePointGetWithCharColumn(c *C) {
+	tk := testkit.NewTestKit(c, s.store)
+	tk.MustExec("use test")
+	tk.MustExec("drop tables if exists t1, t2, t3, t4")
+	tk.MustExec("create table t1(id varchar(20) primary key)")
+	tk.MustExec("create table t2(id varchar(20), unique(id))")
+	tk.MustExec("create table t3(id varchar(20), d varchar(20), unique(id, d))")
+	tk.MustExec("create table t4(id int, d varchar(20), c varchar(20), unique(id, d))")
+
+	tk.MustQuery("explain select * from t1 where id = 0").Check(testkit.Rows(
```
Comment (lzmhhh123) [inline planner/core/point_get_plan_test.go:575]: Please use the test data to record the plan test.

File: planner/core/point_get_plan.go [hunk 4]
```diff
@@ -1039,6 +1066,20 @@ func getNameValuePairs(stmtCtx *stmtctx.StatementContext, tbl *model.TableInfo,
 	return nil, false
 }
 
+func checkCanConvertInPointGet(col *model.ColumnInfo, d types.Datum) bool {
+	kind := d.Kind()
+	switch col.FieldType.EvalType() {
+	case ptypes.ETString:
+		switch kind {
+		case types.KindInt64, types.KindUint64,
+			types.KindFloat32, types.KindFloat64, types.KindMysqlDecimal:
```
Comment (lzmhhh123) [inline planner/core/point_get_plan.go:1075]: Should `bit` be contained here?

Comment (blacktear23) [reply planner/core/point_get_plan.go:1075]: I will do bit type test on mysql later.

Comment (lzmhhh123) [reply planner/core/point_get_plan.go:1075]: OK, please also test `year` and other int like types.

Comment (blacktear23) [reply planner/core/point_get_plan.go:1075]: datetime serise is tested, no problem now. do we need test case for this?

Comment (lzmhhh123) [reply planner/core/point_get_plan.go:1075]: That's much better. More test cases of different types could help us avoid this problem in the future.

Comment (blacktear23) [reply planner/core/point_get_plan.go:1075]: @lzmhhh123 `bit` and `Hex binary literal` tested same as MySQL, so just `char` column with `numeric` literal need to be reject from try point get plan.

**Comment by blacktear23** [comment]
@lzmhhh123 datetime series literal equals with char column has some corner case. But with numeric literal and bit or hex literal is perform same as MySQL.

**Comment by lzmhhh123** [comment]
> @lzmhhh123 datetime series literal equals with char column has some corner case. But with numeric literal and bit or hex literal is perform same as MySQL.

The corner case between `datetime` and `char` could be fixed in another PR.

**Review by lzmhhh123 — COMMENTED** [review]
LGTM

**Comment by blacktear23** [comment]
@lzmhhh123 PTAL #21167

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by crazycs520** [comment]
@blacktear23 I found a related bug too, Could you take a look? https://github.com/pingcap/tidb/issues/21204

**Comment by blacktear23** [comment]
> @blacktear23 I found a related bug too, Could you take a look? #21204

Yes

**Comment by blacktear23** [comment]
@crazycs520 PTAL

**Review by crazycs520 — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]

**Review by crazycs520 — COMMENTED** [review]
LGTM

**Comment by blacktear23** [comment]
@bb7133 do we need cherry-pick?
