### PR TITLE
planner: remove empty selection

### LINKED ISSUE #62240: planner predicate simplification #61739 cause tiflash_regression_test_daily to fail
## Bug Report

ref https://github.com/pingcap/tiflash/issues/10276

### 1. Minimal reproduce step (Required)

```
drop database if exists mpp_complex_sql1000;
CREATE DATABASE /*!32312 IF NOT EXISTS*/ mpp_complex_sql1000 /*!40100 DEFAULT CHARACTER SET latin1 */;
use mpp_complex_sql1000; 
CREATE TABLE A ( col_int int(11) DEFAULT NULL, col_varchar_10 varchar(10) DEFAULT NULL, pk int(11) NOT NULL AUTO_INCREMENT, col_varchar_10_not_null varchar(10) NOT NULL, col_int_not_null int(11) NOT NULL, col_decimal decimal(10,0) DEFAULT NULL, col_datetime datetime DEFAULT NULL, col_decimal_not_null decimal(10,0) NOT NULL, col_varchar_1024 varchar(1024) DEFAULT NULL, col_datetime_not_null datetime NOT NULL, col_varchar_1024_not_null varchar(1024) NOT NULL, PRIMARY KEY (pk) ) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=latin1;
alter table mpp_complex_sql1000.A set tiflash replica 1;

CREATE TABLE G ( col_varchar_10 varchar(10) DEFAULT NULL, col_datetime_not_null datetime NOT NULL, col_int_not_null int(11) NOT NULL, col_int int(11) DEFAULT NULL, col_varchar_1024_not_null varchar(1024) NOT NULL, col_varchar_1024 varchar(1024) DEFAULT NULL, col_decimal decimal(10,0) DEFAULT NULL, col_decimal_not_null decimal(10,0) NOT NULL, pk int(11) NOT NULL AUTO_INCREMENT, col_datetime datetime DEFAULT NULL, col_varchar_10_not_null varchar(10) NOT NULL, PRIMARY KEY (pk) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
alter table mpp_complex_sql1000.G set tiflash replica 1;

CREATE TABLE J ( col_varchar_10 varchar(10) DEFAULT NULL, col_int int(11) DEFAULT NULL, col_varchar_10_not_null varchar(10) NOT NULL, pk int(11) NOT NULL AUTO_INCREMENT, col_datetime datetime DEFAULT NULL, col_int_not_null int(11) NOT NULL, col_decimal decimal(10,0) DEFAULT NULL, col_datetime_not_null datetime NOT NULL, col_varchar_1024_not_null varchar(1024) NOT NULL, col_varchar_1024 varchar(1024) DEFAULT NULL, col_decimal_not_null decimal(10,0) NOT NULL, PRIMARY KEY (pk) ) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;
alter table mpp_complex_sql1000.J set tiflash replica 1;

CREATE TABLE L ( col_decimal decimal(10,0) DEFAULT NULL, col_int_not_null int(11) NOT NULL, col_datetime_not_null datetime NOT NULL, col_decimal_not_null decimal(10,0) NOT NULL, col_datetime datetime DEFAULT NULL, col_varchar_1024_not_null varchar(1024) NOT NULL, col_varchar_10_not_null varchar(10) NOT NULL, col_int int(11) DEFAULT NULL, col_varchar_1024 varchar(1024) DEFAULT NULL, pk int(11) NOT NULL AUTO_INCREMENT, col_varchar_10 varchar(10) DEFAULT NULL, PRIMARY KEY (pk) ) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;
alter table mpp_complex_sql1000.L set tiflash replica 1;


set @@tidb_isolation_read_engines='tiflash,tidb'; 
set @@tidb_allow_mpp=1;
SELECT table1 . pk AS field1 , table2 . col_int_not_null AS field2 , table1 . pk AS field3 , table1 . col_int_not_null AS field4 FROM A AS table1 LEFT JOIN G AS table2 INNER JOIN J AS table3 INNER JOIN J AS table4 RIGHT JOIN L AS table5 ON table4 . col_datetime = table5 . col_datetime_not_null ON table3 . col_int_not_null = table5 . pk ON table2 . col_datetime_not_null = table3 . col_datetime_not_null ON table1 . col_datetime = table2 . col_datetime_not_null WHERE table1 . pk = 3 HAVING (field1 != 7 OR field2 > 1) ORDER BY field1, field2, field3, field4 ASC LIMIT 2 OFFSET 7 ;
```

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

```
ERROR 1105 (HY000): other error for mpp stream: Code: 42, e.displayText() = DB::Exception: Number of arguments for function two_value_and doesn't match: passed 0, should be at least 2., e.what() = DB::Exception,
```

### 4. What is your TiDB version? (Required)

since #61739

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve?

Issue Number: close #62240 

Problem Summary:

### What changed and how does it work?

In some cases, we have observed that after predicate optimization, the selection becomes empty. In such situations, it is necessary to remove this empty selection to ensure normal execution.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No need to test
  > - [ ] I checked and no code files have been changed.
  > 

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

```release-note
None
```

### CODE REVIEW

File: pkg/planner/core/optimizer.go [hunk 1]
```diff
@@ -112,6 +112,7 @@ var optRuleList = []base.LogicalOptRule{
 	&PushDownSequenceSolver{},
 	&EliminateUnionAllDualItem{},
 	&ResolveExpand{},
+	&EmptySelectionEliminator{},
```
Comment (AilinKid) [inline pkg/planner/core/optimizer.go:114]: better always keep ResolveExpand as the last rule

File: pkg/planner/core/rule_eliminate_empty_selection.go [hunk 2]
```diff
@@ -0,0 +1,53 @@
+// Copyright 2023 PingCAP, Inc.
```
Comment (AilinKid) [inline pkg/planner/core/rule_eliminate_empty_selection.go]:
```suggestion
// Copyright 2025 PingCAP, Inc.
```

File: pkg/planner/core/rule_eliminate_empty_selection.go [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+	"github.com/pingcap/tidb/pkg/planner/core/base"
+	"github.com/pingcap/tidb/pkg/planner/core/operator/logicalop"
+	"github.com/pingcap/tidb/pkg/planner/util/optimizetrace"
+)
+
+// EmptySelectionEliminator is a logical optimization rule that removes empty selections
+type EmptySelectionEliminator struct{}
+
+// Optimize implements base.LogicalOptRule.<0th> interface.
+func (e *EmptySelectionEliminator) Optimize(_ context.Context, p base.LogicalPlan, opt *optimizetrace.LogicalOptimizeOp) (base.LogicalPlan, bool, error) {
```
Comment (AilinKid) [inline pkg/planner/core/rule_eliminate_empty_selection.go:29]: you better add a cascades format rule as well

File: pkg/planner/core/rule_eliminate_empty_selection.go [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+		} else {
+			e.recursivePlan(child, opt)
+		}
+	}
+	return p
+}
+
+// Name implements base.LogicalOptRule.<1st> interface.
+func (*EmptySelectionEliminator) Name() string {
+	return "derive_topn_from_window"
```
Comment (AilinKid) [inline pkg/planner/core/rule_eliminate_empty_selection.go]: the name is wrong

File: pkg/planner/core/optimizer.go (hunk 1 above)
Comment (hawkingrei) [reply pkg/planner/core/optimizer.go:114]: Updated

**Review by AilinKid — APPROVED** [review]

**Review by King-Dylan — APPROVED** [review]
