### PR TITLE
executor: fix skipped update when the value is treated as the same in CI collations

### LINKED ISSUE #20724: charset, transaction: update is skipped when the value is treated as the same in CI collations
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When the new collation is enabled:
```
tidb> select * from mysql.tidb;
+-----------------------+----------------+----------------------------------------------------+
| VARIABLE_NAME         | VARIABLE_VALUE | COMMENT                                            |
+-----------------------+----------------+----------------------------------------------------+
| bootstrapped          | True           | Bootstrap flag. Do not delete.                     |
| tidb_server_version   | 51             | Bootstrap version. Do not delete.                  |
| system_tz             | Asia/Shanghai  | TiDB Global System Timezone.                       |
| new_collation_enabled | True           | If the new collations are enabled. Do not edit it. |
+-----------------------+----------------+----------------------------------------------------+
4 rows in set (0.01 sec)
```
And run the following SQLs:
```
tidb> create table t1(a varchar(10) collate utf8mb4_general_ci);
Query OK, 0 rows affected (0.02 sec)

tidb> insert into t1 values ('a');
Query OK, 1 row affected (0.01 sec)

tidb> update t1 set a = 'A';
Query OK, 0 rows affected (0.01 sec)
Rows matched: 1  Changed: 0  Warnings: 0

tidb> select * from t1;
+------+
| a    |
+------+
| a    |
+------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
```
tidb> select * from t1;
+------+
| a    |
+------+
| A    |
+------+
1 row in set (0.00 sec)
```
(Same with MySQL)

### 3. What did you see instead (Required)
```
tidb> select * from t1;
+------+
| a    |
+------+
| a    |
+------+
1 row in set (0.00 sec)
```
Please notice that the `Changed Rows` of `UPDATE` is 0.
### 4. What is your TiDB version? (Required)
It can be reproduced in 4.0 and master branch.

### Root Cause
Before updating the records, TiDB checks if there is anything that is 'really changed':

https://github.com/pingcap/tidb/blob/13bd62e183f81582248e68227a89b64421af607f/executor/write.go#L95

When "new collation" is enabled, the compare of datum is affected by the collation, '`a'` and '`A`' is equal in CI collations. So TiDB treats the update as 'nothing changed' and skips it.

We need to make the `CompareDatum` compare by something like binary collation and solve this issue.

## SIG slack channel

 [#sig-DDL](https://slack.tidb.io/invite?team=tidb-community&channel=sig-ddl&ref=high-performance)

## Score

- 600

## Mentor

- @bb7133

### PR DESCRIPTION
**Pull request by TszKitLo40**
### What problem does this PR solve?

Issue Number: close #20724  

Problem Summary:

### What is changed and how it works?

What's Changed:
Fix skipped update when the value is treated as the same in CI collations
How it Works:
Use binary collation to compare datum.
### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

File: executor/write.go [hunk 1]
```diff
@@ -92,7 +93,11 @@ func updateRecord(ctx context.Context, sctx sessionctx.Context, h kv.Handle, old
 
 	// 3. Compare datum, then handle some flags.
 	for i, col := range t.Cols() {
+		collation := newData[i].Collation()
+		// We should use binary collation to compare datum, otherwise the result will be incorrect.
+		newData[i].SetCollation(charset.CollationUTF8MB4)
```
Comment (xiongjiwei) [inline executor/write.go:98]: a collation should not be a charset.

Comment (TszKitLo40) [reply executor/write.go:98]: Do you think it is better to use `utf8mb4_bin` directyly?

Comment (xiongjiwei) [reply executor/write.go:98]: sorry, I made a mistake

Comment (xiongjiwei) [reply executor/write.go:98]: why set the collation to `CollationUTF8MB4`?  what if the `newData[i]`'s charset is not `utf8mb4`?

Comment (TszKitLo40) [reply executor/write.go:98]: We have to use binary collation here to compare the datum, otherwise 'a' and 'A' will be treated as the same. After comparing the datum, we need to set the original collation back to ensure the correctness.

Comment (xiongjiwei) [reply executor/write.go:98]: right, but if `newData[i]'s` charset is not `utf8mb4`, it seems the charset and collation is mismatched

Comment (TszKitLo40) [reply executor/write.go:98]: So do you think we should set the collation based on the charset?

Comment (xiongjiwei) [reply executor/write.go:98]: yes, if you fix the issue that way, but I still feel it is tricky to set a binary collation. Is there another way to solve this problem?

Comment (bb7133) [reply executor/write.go:98]: I think it may be fine to set `binary`(not `utf8mb4_bin`) directly. Since it is simply a trick here. The mismatch is temporary.

**Comment by bb7133** [comment]
PTAL @wjhuang2016 , and we need at least 1 LGTM from the sig-transaction team.

File: executor/write.go (hunk 1 above)
Comment (coocood) [reply executor/write.go:98]: `utf8mb4_bin` is not the same as `binary` because of padding.
We should use the `binary` collation.

Comment (TszKitLo40) [reply executor/write.go]: Yes, I have fixed it.

File: executor/write.go [hunk 2]
```diff
@@ -92,7 +93,11 @@ func updateRecord(ctx context.Context, sctx sessionctx.Context, h kv.Handle, old
 
 	// 3. Compare datum, then handle some flags.
 	for i, col := range t.Cols() {
+		collation := newData[i].Collation()
+		// We should use binary collation to compare datum, otherwise the result will be incorrect.
+		newData[i].SetCollation(charset.CharsetBin)
```
Comment (coocood) [inline executor/write.go:98]: prefer `chasert.CollationBIn` although it's the same string.

Comment (TszKitLo40) [reply executor/write.go]: Good idea. It will be more clear.

**Comment by coocood** [comment]
LGTM

**Review by AilinKid — COMMENTED** [review]
LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Review by ti-srebot — DISMISSED** [review]

File: executor/write_test.go [hunk 3]
```diff
@@ -2963,3 +2964,15 @@ func (s *testSuite4) TestWriteListColumnsPartitionTable(c *C) {
 	tk.MustExec("delete from t partition (p3,p2)")
 	tk.MustQuery("select * from t order by id").Check(testkit.Rows("1 a", "2 b"))
 }
+
+func (s *testSuite7) TestIssue20724(c *C) {
```
Comment (wjhuang2016) [inline executor/write_test.go:2968]: Please change the test suite to a serial test suite.

**Review by wjhuang2016 — CHANGES_REQUESTED** [review]

File: executor/write_test.go (hunk 3 above)
Comment (TszKitLo40) [reply executor/write_test.go]: OK, I have fixed it.

**Review by wjhuang2016 — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
